[[ccc-section-1-chapter-2]]
= Capítulo segundo: Dios al encuentro del hombre

[[ccc-50]]
^50^ Mediante la razón natural, el hombre puede conocer a Dios con certeza a partir de sus obras. Pero existe otro orden de conocimiento que el hombre no puede de ningún modo alcanzar por sus propias fuerzas, el de la Revelación divina (cf. Concilio Vaticano I: DS 3015). Por una decisión enteramente libre, Dios se revela y se da al hombre. Lo hace revelando su misterio, su designio benevolente que estableció desde la eternidad en Cristo en favor de todos los hombres. Revela plenamente su designio enviando a su Hijo amado, nuestro Señor Jesucristo, y al Espíritu Santo.

[[ccc-section-1-chapter-2-article-1]]
== Artículo 1: La revelación de Dios

[[ccc-section-1-chapter-2-article-1-1]]
=== I. Dios revela su designio amoroso

[[ccc-51]]
^51^ "Dispuso Dios en su sabiduría revelarse a sí mismo y dar a conocer el misterio de su voluntad, mediante el cual los hombres, por medio de Cristo, Verbo encarnado, tienen acceso al Padre en el Espíritu Santo y se hacen consortes de la naturaleza divina" (DV 2).
