[[evangelii-nuntiandi-part-2]]
= II - ¿QUÉ ES EVANGELIZAR?

[[evangelii-nuntiandi-17]]
== Complejidad de la acción evangelizadora

17&#46; En la acción evangelizadora de la Iglesia, entran a formar parte ciertamente algunos elementos y aspectos que hay que tener presentes. Algunos revisten tal importancia que se tiene la tendencia a identificarlos simplemente con la evangelización. De ahí que se haya podido definir la evangelización en términos de anuncio de Cristo a aquellos que lo ignoran, de predicación, de catequesis, de bautismo y de administración de los otros sacramentos.

Ninguna definición parcial y fragmentaria refleja la realidad rica, compleja y dinámica que comporta la evangelización, si no es con el riesgo de empobrecerla e incluso mutilarla. Resulta imposible comprenderla si no se trata de abarcar de golpe todos sus elementos esenciales.

Estos elementos insistentemente subrayados a lo largo del reciente Sínodo siguen siendo profundizados con frecuencia, en nuestros días, bajo la influencia del trabajo sinodal. Nos alegramos de que, en el fondo, sean situados en la misma línea de los que nos ha transmitido el Concilio Vaticano II, sobre todo en Lumen gentium, Gaudium et spes, Ad gentes.

[[evangelii-nuntiandi-18]]
== Renovación de la humanidad...

:fn-46: footnote:[Ap. 21, 5; cf. 2 Cor. 5, 17; Gál. 6, 15.]
:fn-47: footnote:[Cf. Rom. 6, 4.]
:fn-48: footnote:[Cf. Ef. 4, 23-24; Col. 3, 9-10.]
:fn-49: footnote:[Cf. Rom. 1, 16; 1 Cor. 1, 18; 2, 4.]

18&#46; Evangelizar significa para la Iglesia llevar la Buena Nueva a todos los ambientes de la humanidad y, con su influjo, transformar desde dentro, renovar a la misma humanidad: "He aquí que hago nuevas todas las cosas"{fn-46}. Pero la verdad es que no hay humanidad nueva si no hay en primer lugar hombres nuevos con la novedad del bautismo{fn-47} y de la vida según el Evangelio{fn-48}. La finalidad de la evangelización es por consiguiente este cambio interior y, si hubiera que resumirlo en una palabra, lo mejor sería decir que la Iglesia evangeliza cuando, por la sola fuerza divina del Mensaje que proclama{fn-49}, trata de convertir al mismo tiempo la conciencia personal y colectiva de los hombres, la actividad en la que ellos están comprometidos, su vida y ambiente concretos.

[[evangelii-nuntiandi-19]]
== ... y de sectores de la humanidad

19&#46; Sectores de la humanidad que se transforman: para la Iglesia no se trata solamente de predicar el Evangelio en zonas geográficas cada vez más vastas o poblaciones cada vez más numerosas, sino de alcanzar y transformar con la fuerza del Evangelio los criterios de juicio, los valores determinantes, los puntos de interés, las líneas de pensamiento, las fuentes inspiradoras y los modelos de vida de la humanidad, que están en contraste con la palabra de Dios y con el designio de salvación.

[[evangelii-nuntiandi-20]]
== Evangelización de las culturas

:fn-50: footnote:[Cf. 53: AAS 58 (1966), p. 1075.]

20&#46; Posiblemente, podríamos expresar todo esto diciendo: lo que importa es evangelizar —no de una manera decorativa, como un barniz superficial, sino de manera vital, en profundidad y hasta sus mismas raíces— la cultura y las culturas del hombre en el sentido rico y amplio que tienen sus términos en la Gaudium et spes{fn-50}, tomando siempre como punto de partida la persona y teniendo siempre presentes las relaciones de las personas entre sí y con Dios.

El Evangelio y, por consiguiente, la evangelización no se identifican ciertamente con la cultura y son independientes con respecto a todas las culturas. Sin embargo, el reino que anuncia el Evangelio es vivido por hombres profundamente vinculados a una cultura, y la construcción del reino no puede por menos de tomar los elementos de la cultura y de las culturas humanas. Independientes con respecto a las culturas, Evangelio y evangelización no son necesariamente incompatibles con ellas, sino capaces de impregnarlas a todas sin someterse a ninguna.

La ruptura entre Evangelio y cultura es sin duda alguna el drama de nuestro tiempo, como lo fue también en otras épocas. De ahí que hay que hacer todos los esfuerzos con vistas a una generosa evangelización de la cultura, o más exactamente de las culturas. Estas deben ser regeneradas por el encuentro con la Buena Nueva. Pero este encuentro no se llevará a cabo si la Buena Nueva no es proclamada.

[[evangelii-nuntiandi-21]]
== Importancia primordial del testimonio

:fn-51: footnote:[Cf. Tertuliano, Apologeticum, 39: CCL, I, pp. 150-153; Minucio Félix, Octavius 9 y 31: CSLP, Augustae Taurinorum 1963, pp. 11-13, 47-48.]

21&#46; La Buena Nueva debe ser proclamada en primer lugar, mediante el testimonio.
Supongamos un cristiano o un grupo de cristianos que, dentro de la comunidad humana donde viven, manifiestan su capacidad de comprensión y de aceptación, su comunión de vida y de destino con los demás, su solidaridad en los esfuerzos de todos en cuanto existe de noble y bueno. Supongamos además que irradian de manera sencilla y espontánea su fe en los valores que van más allá de los valores corrientes, y su esperanza en algo que no se ve ni osarían soñar. A través de este testimonio sin palabras, estos cristianos hacen plantearse, a quienes contemplan su vida, interrogantes irresistibles: ¿Por qué son así? ¿Por qué viven de esa manera? ¿Qué es o quién es el que los inspira? ¿Por qué están con nosotros? Pues bien, este testimonio constituye ya de por sí una proclamación silenciosa, pero también muy clara y eficaz, de la Buena Nueva. Hay en ello un gesto inicial de evangelización. Son posiblemente las primeras preguntas que se plantearán muchos no cristianos, bien se trate de personas a las que Cristo no había sido nunca anunciado, de bautizados no practicantes, de gentes que viven en una sociedad cristiana pero según principios no cristianos, bien se trate de gentes que buscan, no sin sufrimiento, algo o a Alguien que ellos adivinan pero sin poder darle un nombre. Surgirán otros interrogantes, más profundos y más comprometedores, provocados por este testimonio que comporta presencia, participación, solidaridad y que es un elemento esencial, en general al primero absolutamente en la evangelización{fn-51}.

Todos los cristianos están llamados a este testimonio y, en este sentido, pueden ser verdaderos evangelizadores. Se nos ocurre pensar especialmente en la responsabilidad que recae sobre los emigrantes en los países que los reciben.

[[evangelii-nuntiandi-22]]
== Necesidad de un anuncio explícito

:fn-52: footnote:[1 Pe. 3, 15.]

22&#46; Y, sin embargo, esto sigue siendo insuficiente, pues el más hermoso testimonio se revelará a la larga impotente si no es esclarecido, justificado —lo que Pedro llamaba dar "razón de vuestra esperanza"{fn-52}—, explicitado por un anuncio claro e inequívoco del Señor Jesús. La Buena Nueva proclamada por el testimonio de vida deberá ser pues, tarde o temprano, proclamada por la palabra de vida. No hay evangelización verdadera, mientras no se anuncie el nombre, la doctrina, la vida, las promesas, el reino, el misterio de Jesús de Nazaret Hijo de Dios.

La historia de la Iglesia, a partir del discurso de Pedro en la mañana de Pentecostés, se entremezcla y se confunde con la historia de este anuncio. En cada nueva etapa de la historia humana, la Iglesia, impulsada continuamente por el deseo de evangelizar, no tiene más que una preocupación: ¿a quién enviar para anunciar este misterio? ¿Cómo lograr que resuene y llegue a todos aquellos que lo deben escuchar? Este anuncio —kerygma, predicación o catequesis— adquiere un puesto tan importante en la evangelización que con frecuencia es en realidad sinónimo. Sin embargo, no pasa de ser un aspecto.

[[evangelii-nuntiandi-23]]
== Hacia una adhesión vital y comunitaria

:fn-53: footnote:[Cf. Conc. Ecum. Vat. II, Const. dogm. Lumen gentium, 1, 9, 48: AAS 57 (1965), pp. 5, 12-14, 53-54; Const. past. Gaudium et spes, 42, 45; AAS 58 (1966), pp. 1060-1061, 1065-1066; Decr. Ad gentes, 1, 5; AAS 58 (1966), pp. 947, 951-952.]
:fn-54: footnote:[Cf. Rom. 1, 16; 1 Cor. 1, 18.]

23&#46; Efectivamente, el anuncio no adquiere toda su dimensión más que cuando es escuchado, aceptado, asimilado y cuando hace nacer en quien lo ha recibido una adhesión de corazón. Adhesión a las verdades que en su misericordia el Señor ha revelado, es cierto. Pero, más aún, adhesión al programa de vida —vida en realidad ya transformada— que él propone. En una palabra, adhesión al reino, es decir, al "mundo nuevo", al nuevo estado de cosas, a la nueva manera de ser, de vivir juntos, que inaugura el Evangelio. Tal adhesión, que no puede quedarse en algo abstracto y desencarnado, se revela concretamente por medio de una entrada visible, en una comunidad de fieles. Así pues, aquellos cuya vida se ha transformado entran en una comunidad que es en sí misma signo de la transformación, signo de la novedad de vida: la Iglesia, sacramento visible de la salvación{fn-53}. Pero a su vez, la entrada en la comunidad eclesial se expresará a través de muchos otros signos que prolongan y despliegan el signo de la Iglesia. En el dinamismo de la evangelización, aquel que acoge el Evangelio como Palabra que salva{fn-54}, lo traduce normalmente en estos gestos sacramentales: adhesión a la Iglesia, acogida de los sacramentos que manifiestan y sostienen esta adhesión, por la gracia que confieren.

[[evangelii-nuntiandi-24]]
== Impulso nuevo al apostolado

24&#46; Finalmente, el que ha sido evangelizado evangeliza a su vez. He ahí la prueba de la verdad, la piedra de toque de la evangelización: es impensable que un hombre haya acogido la Palabra y se haya entregado al reino sin convertirse en alguien que a su vez da testimonio y anuncia.

Al terminar estas consideraciones sobre el sentido de la evangelización, se debe formular una última observación que creemos esclarecedora para las reflexiones siguientes.

La evangelización, hemos dicho, es un paso complejo, con elementos variados: renovación de la humanidad, testimonio, anuncio explícito, adhesión del corazón, entrada en la comunidad, acogida de los signos, iniciativas de apostolado. Estos elementos pueden parecer contrastantes, incluso exclusivos. En realidad son complementarios y mutuamente enriquecedores. Hay que ver siempre cada uno de ellos integrado con los otros. El mérito del reciente Sínodo ha sido el habernos invitado constantemente a componer estos elementos, más bien que oponerlos entre sí, para tener la plena comprensión de la actividad evangelizadora de la Iglesia.

En esta visión global lo que queremos ahora exponer, examinando el contenido de la evangelización, los medios de evangelizar, precisando a quién se dirige el anuncio evangélico y quién tiene hoy el encargo de hacerlo.
