[[evangelii-nuntiandi-part-3]]
= III - CONTENIDO DE LA EVANGELIZACIÓN

[[evangelii-nuntiandi-25]]
== Contenido esencial y elementos secundarios

25&#46; En el mensaje que anuncia la Iglesia hay ciertamente muchos elementos secundarios, cuya presentación depende en gran parte de los cambios de circunstancias. Tales elementos cambian también. Pero hay un contenido esencial, una substancia viva, que no se puede modificar ni pasar por alto sin desnaturalizar gravemente la evangelización misma.

[[evangelii-nuntiandi-26]]
== Un testimonio al amor del Padre

:fn-55: footnote:[Cf. Act. 17, 22-23.]
:fn-56: footnote:[1 Jn. 3, 1; cf. Rom. 8, 14-17.]

26&#46; No es superfluo recordarlo: evangelizar es, ante todo, dar testimonio, de una manera sencilla y directa, de Dios revelado por Jesucristo mediante el Espíritu Santo. Testimoniar que ha amado al mundo en su Verbo Encarnado, ha dado a todas las cosas el ser y ha llamado a los hombres a la vida eterna. Para muchos, es posible que este testimonio de Dios desconocido{fn-55}, a quien adoran sin darle un nombre concreto, o al que buscar por sentir una llamada secreta en el corazón, al experimentar la vacuidad de todos los ídolos. Pero este testimonio resulta plenamente evangelizador cuando pone de manifiesto que para el hombre el Creador no es un poder anónimo y lejano: es Padre. "Nosotros somos llamados hijos de Dios, y en verdad lo somos"{fn-56} y, por tanto, somos hermanos los unos de los otros, en Dios.

[[evangelii-nuntiandi-27]]
== Centro del mensaje: la salvación en Jesucristo

:fn-57: footnote:[Cf. Ef. 2, 8; Rom. 1, 16. Cf. Sagrada Congregación para la Doctrina de la Fe, Declaratio ad fidem tuendam in mysteria Incarnationis et SS. Trinitatis a quibusdam recentibus erroribus (21 de febrero de 1972): AAS 64 (1972), pp. 237-241.]

27&#46; La evangelización también debe contener siempre —como base, centro y a la vez culmen de su dinamismo— una clara proclamación de que en Jesucristo, Hijo de Dios hecho hombre, muerto y resucitado, se ofrece la salvación a todos los hombres, como don de la gracia y de la misericordia de Dios{fn-57}. No una salvación puramente inmanente, a medida de las necesidades materiales o incluso espirituales que se agotan en el cuadro de la existencia temporal y se identifican totalmente con los deseos, las esperanzas, los asuntos y las luchas temporales, sino una salvación que desborda todos estos límites para realizarse en una comunión con el único Absoluto Dios, salvación trascendente, escatológica, que comienza ciertamente en esta vida, pero que tiene su cumplimiento en la eternidad.

[[evangelii-nuntiandi-28]]
== Bajo el signo de la esperanza

:fn-58: footnote:[Cf. 1 Jn. 3, 2; Rom. 8, 29; Flp. 3, 20-21. Cf. Conc. Ecum. Vat. II, Const. dogm. Lumen gentium, 48-51: AAS 57 (1965), pp. 55-58.]
:fn-59: footnote:[Cf. Sagrada Congregación para la Doctrina de la Fe, Declaratio circa Catholicam Doctrinam de Ecclesia contra nonnullos errores hodiernos tuendam (24 de junio de 1973): AAS 65 (1973), pp. 396-408.]

28&#46; Por consiguiente, la evangelización no puede por menos de incluir el anuncio profético de un más allá, vocación profunda y definitiva del hombre, en continuidad y discontinuidad a la vez con la situación presente: más allá del tiempo y de la historia, más allá de la realidad de ese mundo, cuya dimensión oculta se manifestará un día; más allá del hombre mismo, cuyo verdadero destino no se agota en su dimensión temporal sino que nos será revelado en la vida futura{fn-58}. La evangelización comprende además la predicación de la esperanza en las promesas hechas por Dios mediante la nueva alianza en Jesucristo; la predicación del amor de Dios para con nosotros y de nuestro amor hacia Dios, la predicación del amor fraterno para con todos los hombres —capacidad de donación y de perdón, de renuncia, de ayuda al hermano— que por descender del amor de Dios, es el núcleo del Evangelio; la predicación del misterio del mal y de la búsqueda activa del bien. Predicación, asimismo, y ésta se hace cada vez más urgente, de la búsqueda del mismo Dios a través de la oración, sobre todo de adoración y de acción de gracias, y también a través de la comunión con ese signo visible del encuentro con Dios que es la Iglesia de Jesucristo; comunión que a su vez se expresa mediante la participación en esos otros signos de Cristo, viviente y operante en la Iglesia, que son los sacramentos. Vivir de tal suerte los sacramentos hasta conseguir en su celebración una verdadera plenitud, no es, como algunos pretenden, poner un obstáculo o aceptar una desviación de la evangelización: es darle toda su integridad. Porque la totalidad de la evangelización, aparte de la predicación del mensaje, consiste en implantar la Iglesia, la cual no existe sin este respiro de la vida sacramental culminante en la Eucaristía{fn-59}.

[[evangelii-nuntiandi-29]]
== Un mensaje que afecta a toda la vida

:fn-60: footnote:[Cf. Conc. Ecum. Vat. II, Const. past. Gaudium et spes, 47-52: AAS 58 (1966), pp. 1067-1074; Pablo VI, Encicl. Humanae vitae: AAS 60 (1968), pp. 481-503.]

29&#46; La evangelización no sería completa si no tuviera en cuenta la interpelación recíproca que en el curso de los tiempos se establece entre el Evangelio y la vida concreta, personal y social, del hombre. Precisamente por esto la evangelización lleva consigo un mensaje explícito, adaptado a las diversas situaciones y constantemente actualizado, sobre los derechos y deberes de toda persona humana, sobre la vida familiar sin la cual apenas es posible el progreso personal{fn-60}, sobre la vida comunitaria de la sociedad, sobre la vida internacional, la paz, la justicia, el desarrollo; un mensaje, especialmente vigoroso en nuestros días, sobre la liberación.

[[evangelii-nuntiandi-30]]
== Un mensaje de liberación

30&#46; Es bien sabido en qué términos hablaron durante el reciente Sínodo numerosos obispos de todos los continentes y, sobre todo, los obispos del Tercer Mundo, con un acento pastoral en el que vibraban las voces de millones de hijos de la Iglesia que forman tales pueblos. Pueblos, ya lo sabemos, empeñados con todas sus energías en el esfuerzo y en la lucha por superar todo aquello que los condena a quedar al margen de la vida: hambres, enfermedades crónicas, analfabetismo, depauperación, injusticia en las relaciones internacionales y, especialmente, en los intercambios comerciales, situaciones de neocolonialismo económico y cultural, a veces tan cruel como el político, etc. La Iglesia, repiten los obispos, tiene el deber de anunciar la liberación de millones de seres humanos, entre los cuales hay muchos hijos suyos; el deber de ayudar a que nazca esta liberación, de dar testimonio de la misma, de hacer que sea total. Todo esto no es extraño a la evangelización.

[[evangelii-nuntiandi-31]]
== En conexión necesaria con la promoción humana

:fn-61: footnote:[Pablo VI, Discurso en la apertura de la III Asamblea General del Sínodo de los Obispos (27 septiembre 1974): AAS 66 (1974), p. 562.]

31&#46; Entre evangelización y promoción humana (desarrollo, liberación) existen efectivamente lazos muy fuertes. Vínculos de orden antropológico, porque el hombre que hay que evangelizar no es un ser abstracto, sino un ser sujeto a los problemas sociales y económicos. Lazos de orden teológico, ya que no se puede disociar el plan de la creación del plan de la redención que llega hasta situaciones muy concretas de injusticia, a la que hay que combatir y de justicia que hay que restaurar. Vínculos de orden eminentemente evangélico como es el de la caridad: en efecto, ¿cómo proclamar el mandamiento nuevo sin promover, mediante la justicia y la paz, el verdadero, el auténtico crecimiento del hombre? Nos mismos lo indicamos, al recordar que no es posible aceptar "que la obra de evangelización pueda o deba olvidar las cuestiones extremadamente graves, tan agitadas hoy día, que atañen a la justicia, a la liberación, al desarrollo y a la paz en el mundo. Si esto ocurriera, sería ignorar la doctrina del Evangelio acerca del amor hacia el prójimo que sufre o padece necesidad"{fn-61}.

Pues bien, las mismas voces que con celo, inteligencia y valentía abordaron durante el Sínodo este tema acuciante, adelantaron, con gran complacencia por nuestra parte, los principios iluminadores para comprender mejor la importancia y el sentido profundo de la liberación tal y como la ha anunciado y realizado Jesús de Nazaret y la predica la Iglesia.

[[evangelii-nuntiandi-32]]
== Sin reducciones ni ambigüedades

:fn-62: footnote:[Pablo VI, Discurso en la apertura de la III Asamblea General del Sínodo de los Obispos (27 septiembre 1974): AAS 66 (1974), p. 562.]

32&#46; No hay por qué ocultar, en efecto, que muchos cristianos generosos, sensibles a las cuestiones dramáticas que lleva consigo el problema de la liberación, al querer comprometer a la Iglesia en el esfuerzo de liberación han sentido con frecuencia la tentación de reducir su misión a las dimensiones de un proyecto puramente temporal; de reducir sus objetivos, a una perspectiva antropocéntrica; la salvación, de la cual ella es mensajera y sacramento, a un bienestar material; su actividad —olvidando toda preocupación espiritual y religiosa— a iniciativas de orden político o social. Si esto fuera así, la Iglesia perdería su significación más profunda. Su mensaje de liberación no tendría ninguna originalidad y se prestaría a ser acaparado y manipulado por los sistemas ideológicos y los partidos políticos. No tendría autoridad para anunciar, de parte de Dios, la liberación. Por eso quisimos subrayar en la misma alocución de la apertura del Sínodo "la necesidad de reafirmar claramente la finalidad específicamente religiosa de la evangelización. Esta última perdería su razón de ser si se desviara del eje religioso que la dirige: ante todo el reino de Dios, en su sentido plenamente teológico"{fn-62}.

[[evangelii-nuntiandi-33]]
== La liberación evangélica...

33&#46; Acerca de la liberación que la evangelización anuncia y se esfuerza por poner en práctica, más bien hay que decir:

—no puede reducirse a la simple y estrecha dimensión económica, política, social o cultural, sino que debe abarcar al hombre entero, en todas sus dimensiones, incluida su apertura al Absoluto, que es Dios;

—va por tanto unida a una cierta concepción del hombre, a un antropología que no puede nunca sacrificarse a las exigencias de una estrategia cualquiera, de una praxis o de un éxito a corto plazo.

[[evangelii-nuntiandi-34]]
== ... centrada en el reino de Dios...

34&#46; Por eso, al predicar la liberación y al asociarse a aquellos que actúan y sufren por ella, la Iglesia no admite el circunscribir su misión al solo terreno religioso, desinteresándose de los problemas temporales del hombre; sino que reafirma la primacía de su vocación espiritual, rechaza la substitución del anuncio del reino por la proclamación de las liberaciones humanas, y proclama también que su contribución a la liberación no sería completa si descuidara anunciar la salvación en Jesucristo.

[[evangelii-nuntiandi-35]]
== ... en una visión evangélica del hombre...

35&#46; La Iglesia asocia, pero no identifica nunca, liberación humana y salvación en Jesucristo, porque sabe por revelación, por experiencia histórica y por reflexión de fe, que no toda noción de liberación es necesariamente coherente y compatible con una visión evangélica del hombre, de las cosas y de los acontecimientos; que no es suficiente instaurar la liberación, crear el bienestar y el desarrollo para que llegue el reino de Dios.

Es más, la Iglesia está plenamente convencida de que toda liberación temporal, toda liberación política —por más que ésta se esfuerce en encontrar su justificación en tal o cual página del Antiguo o del Nuevo Testamento; por más que acuda, para sus postulados ideológicos y sus normas de acción, a la autoridad de los datos y conclusiones teológicas; por más que pretenda ser la teología de hoy— lleva dentro de sí misma el germen de su propia negación y decae del ideal que ella misma se propone, desde el momento en que sus motivaciones profundas no son las de la justicia en la caridad, la fuerza interior que la mueve no entraña una dimensión verdaderamente espiritual y su objetivo final no es la salvación y la felicidad en Dios.

[[evangelii-nuntiandi-36]]
== ... que exige una necesaria conversión

36&#46; La Iglesia considera ciertamente importante y urgente la edificación de estructuras más humanas, más justas, más respetuosas de los derechos de la persona, menos opresivas y menos avasalladoras; pero es consciente de que aun las mejores estructuras, los sistemas más idealizados se convierten pronto en inhumanos si las inclinaciones inhumanas del hombre no son saneadas si no hay una conversión de corazón y de mente por parte de quienes viven en esas estructuras o las rigen.

[[evangelii-nuntiandi-37]]
== Exclusión de la violencia

:fn-63: footnote:[Pablo VI, Discurso a los campesinos de Colombia (23 agosto 1968): AAS 60 (1968), p. 623.]
:fn-64: footnote:[Pablo VI, Discurso en la "Jornada del Desarrollo" en Bogotá (23 agosto 1968): AAS 60 (1968), p. 627; cf. S. Agustín, Epístola 229, 2: PL 33, 1020.]

37&#46; La Iglesia no puede aceptar la violencia, sobre todo la fuerza de las armas —incontrolable cuando se desata— ni la muerte de quienquiera que sea, como camino de liberación, porque sabe que la violencia engendra inexorablemente nuevas formas de opresión y de esclavitud, a veces más graves que aquellas de las que se pretende liberar. "Os exhortamos —decíamos ya durante nuestro viaje a Colombia— a no poner vuestra confianza en la violencia ni en la revolución; esta actitud es contraria al espíritu cristiano e incluso puede retardar, en vez de favorecer, la elevación social a la que legítimamente aspiráis"{fn-63}. "Debemos decir y reafirmar que la violencia no es ni cristiana ni evangélica, y que los cambios bruscos o violentos de las estructuras serán engañosos, ineficaces en sí mismos y ciertamente no conformes con la dignidad del pueblo"{fn-64}.

[[evangelii-nuntiandi-38]]
== Contribución específica de la Iglesia

:fn-65: footnote:[Pablo VI, Discurso en la clausura de la III Asamblea General del Sínodo de los Obispos (26 octubre 1974): AAS 66 (1974), p. 637.]

38&#46; Dicho esto, nos alegramos de que la Iglesia tome una conciencia cada vez más viva de la propia forma, esencialmente evangélica, de colaborar a la liberación de los hombres. Y ¿qué hace? Trata de suscitar cada vez más numerosos cristianos que se dediquen a la liberación de los demás. A estos cristianos "liberadores" les da una inspiración de fe, una motivación de amor fraterno, una doctrina social a la que el verdadero cristiano no sólo debe prestar atención, sino que debe ponerla como base de su prudencia y de su experiencia para traducirla concretamente en categorías de acción, de participación y de compromiso. Todo ello, sin que se confunda con actitudes tácticas ni con el servicio a un sistema político, debe caracterizar la acción del cristiano comprometido. La Iglesia se esfuerza por inserir siempre la lucha cristiana por la liberación en el designio global de salvación que ella misma anuncia.

Todo lo que acabamos de recordar aquí se trató más de una vez en los debates del Sínodo. También Nos quisimos consagrar a este tema algunas palabras de esclarecimiento en la alocución que dirigimos a los padres al final de la Asamblea{fn-65}.

Esperamos que todas estas consideraciones puedan ayudar a evitar la ambigüedad que reviste frecuentemente la palabra "liberación" en las ideologías, los sistemas o los grupos políticos. La liberación que proclama y prepara la evangelización es la que Cristo mismo ha anunciado y dado al hombre con su sacrificio.

[[evangelii-nuntiandi-39]]
== Libertad religiosa

:fn-66: footnote:[Catequesis del 15 octubre 1975, L'Osservatore Romano, Edición en lengua española, 19 octubre, pág. 3.]

39&#46; De esta justa liberación, vinculada a la evangelización, que trata de lograr estructuras que salvaguarden la libertad humana, no se puede separar la necesidad de asegurar todos los derechos fundamentales del hombre, entre los cuales la libertad religiosa ocupa un puesto de primera importancia. Recientemente hemos hablado acerca de la actualidad de un importante aspecto de esta cuestión, poniendo de relieve como "muchos cristianos, todavía hoy, precisamente porque son cristianos o católicos, viven sofocados por una sistemática opresión. El drama de la fidelidad a Cristo y de la libertad de religión, si bien paliado por declaraciones categóricas en favor de los derechos de la persona y de la sociabilidad humana, continúa"{fn-66}.
