:fn-67: footnote:[Pablo VI, Discurso a los miembros del Consilium de Laicis (2 octubre 1974): AAS 66 (1974), p. 568.]
:fn-68: footnote:[Cf. 1 Pe. 3, 1.]
:fn-69: footnote:[Rom. 10, 14. 17.]
:fn-70: footnote:[Cf. 1 Cor. 2, 1-5.]
:fn-71: footnote:[Rom. 10, 17.]
:fn-72: footnote:[Cf. Mt. 10, 27; Lc. 12, 3.]

[[evangelii-nuntiandi-part-4]]
= IV - MEDIOS DE EVANGELIZACIÓN

[[evangelii-nuntiandi-40]]
== A la búsqueda de los medios adecuados

40&#46; La evidente importancia del contenido no debe hacer olvidar la importancia de los métodos y medios de la evangelización.

Este problema de cómo evangelizar es siempre actual, porque las maneras de evangelizar cambian según las diversas circunstancias de tiempo, lugar, cultura; por eso plantean casi un desafío a nuestra capacidad de descubrir y adaptar.

A nosotros, Pastores de la Iglesia, incumbe especialmente el deber de descubrir con audacia y prudencia, conservando la fidelidad al contenido, las formas más adecuadas y eficaces de comunicar el mensaje evangélico a los hombres de nuestro tiempo.

Bástenos aquí recordar algunos sistemas de evangelización, que por un motivo u otro, tienen una importancia fundamental.

[[evangelii-nuntiandi-41]]
== El testimonio de vida

41&#46; Ante todo, y sin necesidad de repetir lo que ya hemos recordado antes, hay que subrayar esto: para la Iglesia el primer medio de evangelización consiste en un testimonio de vida auténticamente cristiana, entregada a Dios en una comunión que nada debe interrumpir y a la vez consagrada igualmente al prójimo con un celo sin límites. "El hombre contemporáneo escucha más a gusto a los que dan testimonio que a los que enseñan —decíamos recientemente a un grupo de seglares—, o si escuchan a los que enseñan, es porque dan testimonio"{fn-67}. San Pedro lo expresaba bien cuando exhortaba a una vida pura y respetuosa, para que si alguno se muestra rebelde a la palabra, sea ganado por la conducta{fn-68}. Será sobre todo mediante su conducta, mediante su vida, como la Iglesia evangelizará al mundo, es decir, mediante un testimonio vivido de fidelidad a Jesucristo, de pobreza y desapego de los bienes materiales, de libertad frente a los poderes del mundo, en una palabra de santidad.

[[evangelii-nuntiandi-42]]
== Una predicación viva

42&#46; No es superfluo subrayar a continuación la importancia y necesidad de la predicación: "Pero ¿cómo invocarán a Aquel en quien no han creído? Y, ¿cómo creerán sin haber oído de El? Y ¿cómo oirán si nadie les predica?... Luego, la fe viene de la audición, y la audición, por la palabra de Cristo"{fn-69}. Esta ley enunciada un día por San Pablo conserva hoy todo su vigor.

Sí, es siempre indispensable la predicación, la proclamación verbal de un mensaje. Sabemos bien que el hombre moderno, hastiado de discursos, se muestra con frecuencia cansado de escuchar y, lo que es peor, inmunizado contra las palabras. Conocemos también las ideas de numerosos psicólogos y sociólogos, que afirman que el hombre moderno ha rebasado la civilización de la palabra, ineficaz e inútil en estos tiempos, para vivir hoy en la civilización de la imagen. Estos hechos deberían ciertamente impulsarnos a utilizar, en la transmisión del mensaje evangélico, los medios modernos puestos a disposición por esta civilización. Es verdad que se han realizado esfuerzos muy válidos en este campo. Nos no podemos menos de alabarlos y alentarlos, a fin de que se desarrollen todavía más. El tedio que provocan hoy tantos discursos vacíos, y la actualidad de muchas otras formas de comunicación, no deben sin embargo disminuir el valor permanente de la palabra, ni hacer prender la confianza en ella. La palabra permanece siempre actual, sobre todo cuando va acompañada del poder de Dios{fn-70}. Por esto conserva también su actualidad el axioma de San Pablo: "la fe viene de la audición"{fn-71}, es decir, es la Palabra oída la que invita a creer.

[[evangelii-nuntiandi-43]]
== Liturgia de la Palabra

43&#46; Esta predicación evangelizadora toma formas muy diversas, que el celo sugeriría cómo renovar constantemente. En efecto, son innumerables los acontecimientos de la vida y las situaciones humanas que ofrecen la ocasión de anunciar, de modo discreto pero eficaz, lo que el Señor desea decir en una determinada circunstancia. Basta una verdadera sensibilidad espiritual para leer en los acontecimientos el mensaje de Dios. Además en un momento en que la liturgia renovada por el Concilio ha valorizado mucho la "liturgia de la Palabra", sería un error no ver en la homilía un instrumento válido y muy apto para la evangelización. Cierto que hay que conocer y poner en práctica las exigencias y posibilidades de la homilía para que ésta adquiera toda su eficacia pastoral. Pero sobre todo hay que estar convencido de ello y entregarse a la tarea con amor. Esta predicación, inserida de manera singular en la celebración eucarística, de la que recibe una fuerza y vigor particular, tiene ciertamente un puesto especial en la evangelización, en la medida en que expresa la fe profunda del ministro sagrado que predica y está impregnada de amor. Los fieles, congregados para formar una Iglesia pascual que celebra la fiesta del Señor presente en medio de ellos, esperan mucho de esta predicación y sacan fruto de ella con tal que sea sencilla, clara, directa, acomodada, profundamente enraizada en la enseñanza evangélica y fiel al Magisterio de la Iglesia, animada por un ardor apostólico equilibrado que le viene de su carácter propio, llena de esperanza, fortificadora de la fe y fuente de paz y de unidad. Muchas comunidades, parroquiales o de otro tipo, viven y se consolidan gracias a la homilía de cada domingo, cuando ésta reúne dichas cualidades.

Añadamos que, gracias a la renovación de la liturgia, la celebración eucarística no es el único momento apropiado para la homilía. Esta tiene también un lugar propio, y no debe ser olvidada, en la celebración de todos los sacramentos, en las paraliturgias, con ocasión de otras reuniones de fieles. La homilía será siempre una ocasión privilegiada para comunicar la Palabra del Señor.

[[evangelii-nuntiandi-44]]
== La catequesis

44&#46; A propósito de la evangelización, un medio que no se puede descuidar es la enseñanza catequética. La inteligencia, sobre todo tratándose de niños y adolescentes, necesita aprender mediante una enseñanza religiosa sistemática los datos fundamentales, el contenido vivo de la verdad que Dios ha querido transmitirnos y que la Iglesia ha procurado expresar de manera cada vez más perfecta a lo largo de la historia. A nadie se le ocurrirá poner en duda que esta enseñanza se ha de impartir con el objeto de educar las costumbres, no de estacionarse en un plano meramente intelectual. Con toda seguridad, el esfuerzo de evangelización será grandemente provechoso, a nivel de la enseñanza catequética dada en la iglesia, en las escuelas donde sea posible o en todo caso en los hogares cristianos, si los catequistas disponen de textos apropiados, puestos al día sabia y competentemente, bajo la autoridad de los obispos. Los métodos deberán ser adaptados a la edad, a la cultura, a la capacidad de las personas, tratando de fijar siempre en la memoria, la inteligencia y el corazón las verdades esenciales que deberán impregnar la vida entera. Ante todo, es menester preparar buenos catequistas —catequistas parroquiales, instructores, padres— deseosos de perfeccionarse en este arte superior, indispensable y exigente que es la enseñanza religiosa. Por lo demás, sin necesidad de descuidar de ninguna manera la formación de los niños, se viene observando que las condiciones actuales hacen cada día más urgente la enseñanza catequética bajo la modalidad de un catecumenado para un gran número de jóvenes y adultos que, tocados por la gracia, descubren poco a poco la figura de Cristo y sienten la necesidad de entregarse a El.

[[evangelii-nuntiandi-45]]
== Utilización de los medios de comunicación social

45&#46; En nuestro siglo influenciado por los medios de comunicación social, el primer anuncio, la catequesis o el ulterior ahondamiento de la fe, no pueden prescindir de esos medios, como hemos dicho antes.

Puestos al servicio del Evangelio, ellos ofrecen la posibilidad de extender casi sin límites el campo de audición de la Palabra de Dios, haciendo llegar la Buena Nueva a millones de personas. La Iglesia se sentiría culpable ante Dios si no empleara esos poderosos medios, que la inteligencia humana perfecciona cada vez más. Con ellos la Iglesia "pregona sobre los terrados"{fn-72} el mensaje del que es depositaria. En ellos encuentra una versión moderna y eficaz del "púlpito". Gracias a ellos puede hablar a las masas.

Sin embargo, el empleo de los medios de comunicación social en la evangelización supone casi un desafío: el mensaje evangélico deberá, sí, llegar, a través de ellos, a las muchedumbres, pero con capacidad para penetrar en las conciencias, para posarse en el corazón de cada hombre en particular, con todo lo que éste tiene de singular y personal, y con capacidad para suscitar en favor suyo una adhesión y un compromiso verdaderamente personal.

[[evangelii-nuntiandi-46]]
== Contacto personal indispensable

46&#46; Por estos motivos, además de la proclamación que podríamos llamar colectiva del Evangelio, conserva toda su validez e importancia esa otra transmisión de persona a persona. El Señor la ha practicado frecuentemente —como lo prueban, por ejemplo, las conversaciones con Nicodemo, Zaqueo, la Samaritana, Simón el fariseo— y lo mismo han hecho los Apóstoles. En el fondo, ¿hay otra forma de comunicar el Evangelio que no sea la de transmitir a otro la propia experiencia de fe? La urgencia de comunicar la Buena Nueva a las masas de hombres no debería hacer olvidar esa forma de anunciar mediante la cual se llega a la conciencia personal del hombre y se deja en ella el influjo de una palabra verdaderamente extraordinaria que recibe de otro hombre. Nunca alabaremos suficientemente a los sacerdotes que, a través del sacramento de la penitencia o a través del diálogo pastoral, se muestran dispuestos a guiar a las personas por el camino del Evangelio, a alentarlas en sus esfuerzos, a levantarlas si han caído, a asistirlas siempre con discreción y disponibilidad.

[[evangelii-nuntiandi-47]]
== La función de los sacramentos

47&#46; Sin embargo, nunca se insistirá bastante en el hecho de que la evangelización no se agota con la predicación y la enseñanza de una doctrina. Porque aquella debe conducir a la vida: a la vida natural a la que da un sentido nuevo gracias a las perspectivas evangélicas que le abre; a la vida sobrenatural, que no es una negación, sino purificación y elevación de la vida natural. Esta vida sobrenatural encuentra su expresión viva en los siete sacramentos y en la admirable fecundidad de gracia y santidad que contienen.

La evangelización despliega de este modo toda su riqueza cuando realiza la unión más íntima, o mejor, una intercomunicación jamás interrumpida, entre la Palabra y los sacramentos. En un cierto sentido es un equívoco oponer, como se hace a veces, la evangelización a la sacramentalización. Porque es seguro que si los sacramentos se administran sin darles un sólido apoyo de catequesis sacramental y de catequesis global, se acabaría por quitarles gran parte de su eficacia. La finalidad de la evangelización es precisamente la de educar en la fe, de tal manera, que conduzca a cada cristiano a vivir —y no a recibir de modo pasivo o apático— los sacramentos como verdaderos sacramentos de la fe.

[[evangelii-nuntiandi-48]]
== Piedad popular

48&#46; Con ello estamos tocando un aspecto de la evangelización que no puede dejarnos insensibles. Queremos referirnos ahora a esa realidad que suele ser designada en nuestros días con el término de religiosidad popular.

Tanto en las regiones donde la Iglesia está establecida desde hace siglos, como en aquellas donde se está implantando, se descubren en el pueblo expresiones particulares de búsqueda de Dios y de la fe. Consideradas durante largo tiempo como menos puras, y a veces despreciadas, estas expresiones constituyen hoy el objeto de un nuevo descubrimiento casi generalizado. Durante el Sínodo, los obispos estudiaron a fondo el significado de las mismas, con un realismo pastoral y un celo admirable.

La religiosidad popular, hay que confesarlo, tiene ciertamente sus límites. Está expuesta frecuentemente a muchas deformaciones de la religión, es decir, a las supersticiones. Se queda frecuentemente a un nivel de manifestaciones culturales, sin llegar a una verdadera adhesión de fe. Puede incluso conducir a la formación de sectas y poner en peligro la verdadera comunidad eclesial.

Pero cuando está bien orientada, sobre todo mediante una pedagogía de evangelización, contiene muchos valores. Refleja una sed de Dios que solamente los pobres y sencillos pueden conocer. Hace capaz de generosidad y sacrificio hasta el heroísmo, cuando se trata de manifestar la fe. Comporta un hondo sentido de los atributos profundos de Dios: la paternidad, la providencia, la presencia amorosa y constante. Engendra actitudes interiores que raramente pueden observarse en el mismo grado en quienes no poseen esa religiosidad: paciencia, sentido de la cruz en la vida cotidiana, desapego, aceptación de los demás, devoción. Teniendo en cuenta esos aspectos, la llamamos gustosamente "piedad popular", es decir, religión del pueblo, más bien que religiosidad.

La caridad pastoral debe dictar, a cuantos el Señor ha colocado como jefes de las comunidades eclesiales, las normas de conducta con respecto a esta realidad, a la vez tan rica y tan amenazada. Ante todo, hay que ser sensible a ella, saber percibir sus dimensiones interiores y sus valores innegables, estar dispuesto a ayudarla a superar sus riesgos de desviación. Bien orientada, esta religiosidad popular puede ser cada vez más, para nuestras masas populares, un verdadero encuentro con Dios en Jesucristo.