[[evangelii-nuntiandi-part-5]]
= V - LOS DESTINATARIOS DE LA EVANGELIZACIÓN

[[evangelii-nuntiandi-49]]
== Destino universal

49&#46; Las últimas palabras de Jesús en el Evangelio de Marcos confieren a la evangelización, que el Señor confía a los Apóstoles, una universalidad sin fronteras: "Id por todo el mundo y predicad el Evangelio a toda criatura"[73].

Los Doce y la primera generación de cristianos han comprendido bien la lección de este texto y de otros parecidos; han hecho de ellos su programa de acción. La misma persecución, al dispersar a los Apóstoles, contribuyó a diseminar la Palabra y a implantar la Iglesia hasta en las regiones más remotas. La admisión de Pablo entre los Apóstoles y su carisma de predicador de la venida de Jesucristo a los paganos —no judíos— subrayó todavía más esta universalidad.

[[evangelii-nuntiandi-50]]
== A pesar de los obstáculos

50&#46; A lo largo de veinte siglos de historia, las generaciones cristianas han afrontado periódicamente diversos obstáculos a esta misión de universalidad. Por una parte, la tentación de los mismos evangelizadores de estrechar bajo distintos pretextos su campo de acción misionera. Por otra, las resistencias, muchas veces humanamente insuperables de aquellos a quienes el evangelizador se dirige. Además, debemos constatar con tristeza que la obra evangelizadora de la Iglesia es gravemente dificultada, si no impedida, por los poderes públicos. Sucede, incluso en nuestros días, que a los anunciadores de la palabra de Dios se les priva de sus derechos, son perseguido, amenazados, eliminados sólo por el hecho de predicar a Jesucristo y su Evangelio. Pero abrigamos la confianza de que finalmente, a pesar de estas pruebas dolorosas, la obra de estos apóstoles no faltará en ninguna región del mundo.

No obstante estas adversidades, la Iglesia reaviva siempre su inspiración más profunda, la que le viene directamente del Maestro: ¡A todo el mundo! ¡A toda criatura! ¡Hasta los confines de la tierra! Lo ha hecho nuevamente en el Sínodo, como una llamada a no encadenar el anuncio evangélico limitándolo a un sector de la humanidad o a una clase de hombres o a un solo tipo de cultura. Algunos ejemplos podrían ser reveladores.

[[evangelii-nuntiandi-51]]
== Primer anuncio a los que están lejos

51&#46; Revelar a Jesucristo y su Evangelio a los que no los conocen: he ahí el programa fundamental que la Iglesia, desde la mañana de Pentecostés, ha asumido, como recibido de su Fundador. Todo el Nuevo Testamento, y de manera especial los Hechos de los Apóstoles, testimonian el momento privilegiado, y en cierta manera ejemplar, de este esfuerzo misionero que jalonará después toda la historia de la Iglesia.

La Iglesia lleva a efecto este primer anuncio de Jesucristo mediante una actividad compleja y diversificada, que a veces se designa con el nombre de "pre-evangelización", pero que muy bien podría llamarse evangelización, aunque en un estadio de inicio y ciertamente incompleto. Cuenta con una gama casi infinita de medios: la predicación explícita, por supuesto, pero también el arte, los intentos científicos, la investigación filosófica, el recurso legítimo a los sentimientos del corazón del hombre podrían colocarse en el ámbito de esta finalidad.

[[evangelii-nuntiandi-52]]
== Anuncio al mundo descristianizado

52&#46; Aunque este primer anuncio va dirigido de modo específico a quienes nunca han escuchado la Buena Nueva de Jesús o a los niños, se está volviendo cada vez más necesario, a causa de las situaciones de descristianización frecuentes en nuestros días, para gran número de personas que recibieron el bautismo, pero viven al margen de toda vida cristiana; para las gentes sencillas que tienen una cierta fe, pero conocen poco los fundamentos de la misma; para los intelectuales que sienten necesidad de conocer a Jesucristo bajo una luz distinta de la enseñanza que recibieron en su infancia, y para otros muchos.

[[evangelii-nuntiandi-53]]
== Religiones no cristianas

53&#46; Asimismo se dirige a inmensos sectores de la humanidad que practican religiones no cristianas. La Iglesia respeta y estima estas religiones no cristianas, por ser la expresión viviente del alma de vastos grupos humanos. Llevan en sí mismas el eco de milenios a la búsqueda de Dios; búsqueda incompleta pero hecha frecuentemente con sinceridad y rectitud de corazón. Poseen un impresionante patrimonio de textos profundamente religiosos. Han enseñado a generaciones de personas a orar. Todas están llenas de innumerables "semillas del Verbo"[74] y constituyen una auténtica "preparación evangélica"[75], por citar una feliz expresión del Concilio Vaticano II tomada de Eusebio de Cesarea.

Ciertamente, tal situación suscita cuestiones complejas y delicadas, que conviene estudiar a la luz de la Tradición cristiana y del Magisterio de la Iglesia, con el fin de ofrecer a los misioneros de hoy y de mañana nuevos horizontes en sus contactos con las religiones no cristianas. Ante todo, queremos poner ahora de relieve que ni el respeto ni la estima hacia estas religiones, ni la complejidad de las cuestiones planteadas implican para la Iglesia una invitación a silenciar ante los no cristianos el anuncio de Jesucristo. Al contrario, la Iglesia piensa que estas multitudes tienen derecho a conocer la riqueza del misterio de Cristo[76], dentro del cual creemos que toda la humanidad puede encontrar, con insospechada plenitud, todo lo que busca a tientas acerca de Dios, del hombre y de su destino, de la vida y de la muerte, de la verdad. De ahí que, aun frente a las expresiones religiosas naturales más dignas de estima, la Iglesia se funde en el hecho de que la religión de Jesús, la misma que Ella anuncia por medio de la evangelización, sitúa objetivamente al hombre en relación con el plan de Dios, con su presencia viva, con su acción; hace hallar de nuevo el misterio de la Paternidad divina que sale al encuentro de la humanidad. En otras palabras, nuestra religión instaura efectivamente una relación auténtica y viviente con Dios, cosa que las otras religiones no lograron establecer, por más que tienen, por decirlo así, extendidos sus brazos hacia el cielo.

Por eso la Iglesia mantiene vivo su empuje misionero e incluso desea intensificarlo en un momento histórico como el nuestro. La Iglesia se siente responsable ante todos los pueblos. No descansará hasta que no haya puesto de su parte todo lo necesario para proclamar la Buena Nueva de Jesús Salvador. Prepara siempre nuevas generaciones de apóstoles. Lo constatamos con gozo en unos momentos en que no faltan quienes piensan, e incluso dicen, que el ardor y el empuje misionero son cosa del pasado. El Sínodo acaba de responder que el anuncio misionero no se agota y que la Iglesia se esforzará siempre en conseguir su perfeccionamiento.

[[evangelii-nuntiandi-54]]
== Ayuda a la fe de los fieles

54&#46; Sin embargo, la Iglesia no se siente dispensada de prestar una atención igualmente infatigable hacia aquellos que han recibido la fe y que, a veces desde hace muchas generaciones permanecen en contacto con el Evangelio. Trata así de profundizar, consolidar, alimentar, hacer cada vez más madura la fe de aquellos que se llaman ya fieles o creyentes, a fin de que lo sean cada vez más.

Esta fe está casi siempre enfrentada al secularismo, es decir, a un ateísmo militante; es una fe expuesta a pruebas y amenazas, más aún, una fe asediada y combatida. Corre el riesgo de morir por asfixia o por inanición, si no se la alimenta y sostiene cada día. Por tanto evangelizar debe ser, con frecuencia, comunicar a la fe de los fieles —particularmente mediante una catequesis llena de savia evangélica y con un lenguaje adaptado a los tiempos y a las personas— este alimento y este apoyo necesarios.

La Iglesia católica abriga un vivo anhelo de los cristianos que no están en plena comunión con Ella: mientras prepara con ellos la unidad querida por Cristo, y precisamente para preparar la unidad en la verdad, tiene conciencia de que faltaría gravemente a su deber si no diese testimonio, ante ellos, de la plenitud de la revelación de que es depositaria.

[[evangelii-nuntiandi-55]]
== Secularismo ateo

55&#46; Igualmente significativa es la preocupación, presente en el Sínodo, hacia dos esferas muy diferentes la una de la otra y sin embargo muy próximas entre sí por el desafío que, cada una a su modo, lanzan a la evangelización. La primera es aquella que podemos llamar el aumento de la incredulidad en el mundo moderno. El Sínodo se propuso describir este mundo moderno: bajo este nombre genérico, ¡cuántas corrientes de pensamiento, valores y contravalores, aspiraciones latentes o semillas de destrucción, convicciones antiguas que desaparecen y convicciones nuevas que se imponen!

Desde el punto de vista espiritual, este mundo moderno parece debatirse siempre en lo que un autor contemporáneo ha llamado "el drama del humanismo ateo"[77].

Por una parte, hay que constatar en el corazón mismo de este mundo contemporáneo un fenómeno, que constituye como su marca más característica: el secularismo. No hablamos de la secularización en el sentido de un esfuerzo, en sí mismo justo y legítimo, no incompatible con la fe y la religión, por descubrir en la creación, en cada cosa o en cada acontecimiento del universo, las leyes que los rigen con una cierta autonomía, con la convicción interior de que el Creador ha puesto en ellos sus leyes. El reciente Concilio afirmó, en este sentido, la legítima autonomía de la cultura y, particularmente, de las ciencias[78]. Tratamos aquí del verdadero secularismo: una concepción del mundo según la cual este último se explica por sí mismo sin que sea necesario recurrir a Dios; Dios resultaría pues superfluo y hasta un obstáculo. Dicho secularismo, para reconocer el poder del hombre, acaba por sobrepasar a Dios e incluso por renegar de El.

Nuevas formas de ateísmo —un ateísmo antropocéntrico, no ya abstracto y metafísico, sino pragmático y militante— parecen desprenderse de él. En unión con este secularismo ateo, se nos propone todos los días, bajo las formas más distintas, una civilización del consumo, el hedonismo erigido en valor supremo, una voluntad de poder y de dominio, de discriminaciones de todo género: constituyen otras tantas inclinaciones inhumanas de este "humanismo".

Por otra parte, y paradójicamente, en este mismo mundo moderno, no se puede negar la existencia de valores inicialmente cristianos o evangélicos, al menos bajo forma de vida o de nostalgia. No sería exagerado hablar de un poderoso y trágico llamamiento a ser evangelizado.

[[evangelii-nuntiandi-56]]
== Los que no practican

56&#46; Una segunda esfera es la de los no practicantes; toda una muchedumbre, hoy día muy numerosa, de bautizados que, en gran medida, no han renegado formalmente de su bautismo, pero están totalmente al margen del mismo y no lo viven. El fenómeno de los no practicantes es muy viejo en la historia del cristianismo y supone una debilidad natural, una gran incongruencia que nos duele en lo más profundo de nuestro corazón. Sin embargo, hoy día presenta aspectos nuevos. Se explica muchas veces por el desarraigo típico de nuestra época. Nace también del hecho de que los cristianos se aproximan hoy a los no creyentes y reciben constantemente el influjo de la incredulidad. Por otra parte, los no practicantes contemporáneos, más que los de otras épocas tratan de explicar y justificar su posición en nombre de una religión interior, de una autonomía o de una autenticidad personal.

Ateos y no creyentes por una parte, no practicantes por otra, oponen a la evangelización resistencias no pequeñas. Los primeros, la resistencia de un cierto rechazo, la incapacidad de comprender el nuevo orden de las cosas, el nuevo sentido del mundo, de la vida, de la historia, que resulta una empresa imposible si no se parte del Absoluto que es Dios. Los otros, la resistencia de la inercia, la actitud un poco hostil de alguien que se siente como de casa, que dice saberlo todo, haber probado todo y ya no cree en nada.

Secularismo ateo y ausencia de práctica religiosa se encuentran en los adultos y en los jóvenes, en la élite y en la masa, en las antiguas y en las jóvenes Iglesias. La acción evangelizadora de la Iglesia, que no puede ignorar estos dos mundos ni detenerse ante ellos, debe buscar constantemente los medios y el lenguaje adecuados para proponerles la revelación de Dios y la fe en Jesucristo.

[[evangelii-nuntiandi-57]]
== Anuncio a las muchedumbres

57&#46; Como Cristo durante el tiempo de su predicación, como los Doce en la mañana de Pentecostés, la Iglesia tiene también ante sí una inmensa muchedumbre humana que necesita del Evangelio y tiene derecho al mismo, pues Dios "quiere que todos los hombres se salven y lleguen al conocimiento de la verdad"[79].

Sensible a su deber de predicar la salvación a todos sabiendo que el mensaje evangélico no está reservado a un pequeño grupo de iniciados, de privilegiados o elegidos, sino que está destinado a todos, la Iglesia hace suya la angustia de Cristo ante las multitudes errantes y abandonadas "como ovejas sin pastor" y repite con frecuencia su palabra: "Tengo compasión de la muchedumbre"[80].

Pero también es consciente de que, por medio de una eficaz predicación evangélica, debe dirigir su mensaje al corazón de las masas, a las comunidades de fieles, cuya acción puede y debe llegar a los demás.

[[evangelii-nuntiandi-58]]
== Comunidades eclesiales de base

58&#46; El Sínodo se ocupó mucho de estas "pequeñas comunidades" o "comunidades de base", ya que en la Iglesia de hoy se las menciona con frecuencia. ¿Qué son y por qué deben ser destinatarias especiales de la evangelización y al mismo tiempo evangelizadoras?

Florecen un poco por todas partes en la Iglesia, según los distintos testimonios escuchados durante el Sínodo, y se diferencian bastante entre sí aun dentro de una misma región, y mucho más de una región a otra.

En ciertas regiones surgen y se desarrollan, salvo alguna excepción, en el interior de la Iglesia, permaneciendo solidarias con su vida, alimentadas con sus enseñanzas, unidas a sus Pastores. En estos casos, nacen de la necesidad de vivir todavía con más intensidad la vida de la Iglesia; o del deseo y de la búsqueda de una dimensión más humana que difícilmente pueden ofrecer las comunidades eclesiales más grandes, sobre todo en las metrópolis urbanas contemporáneas que favorecen a la vez la vida de masa y el anonimato. Pero igualmente pueden prolongar a nivel espiritual y religioso —culto, cultivo de una fe más profunda, caridad fraterna, oración, comunión con los Pastores— la pequeña comunidad sociológica, el pueblo, etc. O también quieren reunir para escuchar y meditar la Palabra, para los sacramentos y el vínculo del agápe, grupos homogéneos por la edad, la cultura, el estado civil o la situación social, como parejas, jóvenes, profesionales, etc., personas éstas que la vida misma encuentra ya unidas en la lucha por la justicia, la ayuda fraterna a los pobres, la promoción humana, etc. O, en fin, reúnen a los cristianos donde la penuria de sacerdotes no favorece la vida normal de una comunidad parroquial. Todo esto, por supuesto, al interior de las comunidades constituidas por la Iglesia, sobre todo de las Iglesias particulares y de las parroquias.

En otras regiones, por el contrario, las comunidades de base se reúnen con un espíritu de crítica amarga hacia la Iglesia, que estigmatizan como "institucional" y a la que se oponen como comunidades carismáticas, libres de estructuras, inspiradas únicamente en el Evangelio. Tienen pues como característica una evidente actitud de censura y de rechazo hacia las manifestaciones de la Iglesia: su jerarquía, sus signos. Contestan radicalmente esta Iglesia. En esta línea, su inspiración principal se convierte rápidamente en ideológica y no es raro que sean muy pronto presa de una opción política, de una corriente, y más tarde de un sistema, o de un partido, con el riesgo de ser instrumentalizadas.

La diferencia es ya notable: las comunidades que por su espíritu de contestación se separan de la Iglesia, cuya unidad perjudican, pueden llamarse "comunidades de base", pero ésta es una denominación estrictamente sociológica. No pueden, sin abusar del lenguaje, llamarse comunidades eclesiales de base, aunque tengan la pretensión de perseverar en la unidad de la Iglesia, manteniéndose hostiles a la jerarquía. Este nombre pertenece a las otras, a las que se forman en Iglesia para unirse a la Iglesia y para hacer crecer a la Iglesia.

Estas últimas comunidades serán un lugar de evangelización, en beneficio de las comunidades más vastas, especialmente de las Iglesias particulares, y serán una esperanza para la Iglesia universal, como Nos mismo dijimos al final del Sínodo, en la medida en que:

— buscan su alimento en la palabra de Dios y no se dejan aprisionar por la polarización política o por las ideologías de moda, prontas a explotar su inmenso potencial humano;

— evitan la tentación siempre amenazadora de la contestación sistemática y del espíritu hipercrítico, bajo pretexto de autenticidad y de espíritu de colaboración;

— permanecen firmemente unidas a la Iglesia local en la que ellas se insieren, y a la Iglesia universal, evitando así el peligro muy real de aislarse en sí mismas, de creerse, después, la única auténtica Iglesia de Cristo y, finalmente, de anatemizar a las otras comunidades eclesiales;

— guardan una sincera comunión con los Pastores que el Señor ha dado a su Iglesia y al Magisterio que el Espíritu de Cristo les ha confiado;

— no se creen jamás el único destinatario o el único agente de evangelización, esto es, el único depositario del Evangelio, sino que, conscientes de que la Iglesia es mucho más vasta y diversificada, aceptan que la Iglesia se encarna en formas que no son las de ellas;

— crecen cada día en responsabilidad, celo, compromiso e irradiación misioneros;

— se muestran universalistas y no sectarias.

Con estas condiciones, ciertamente exigentes pero también exaltantes, las comunidades eclesiales de base corresponderán a su vocación más fundamental: escuchando el Evangelio que les es anunciado, y siendo destinatarias privilegiadas de la evangelización, ellas mismas se convertirán rápidamente en anunciadoras del Evangelio.
