[[evangelii-nuntiandi-part-6]]
= VI - AGENTES DE LA EVANGELIZACIÓN

[[evangelii-nuntiandi-59]]
== La Iglesia entera es misionera

:fn-81: footnote:[Rom. 10, 15.]
:fn-82: footnote:[Decl. Dignitatis humanae, 13: AAS 58 (1966), p. 939; cf. Const. dogm. Lumen gentium, 5: AAS 57 (1965), pp. 7-8; Decr. Ad gentes, I: AAS 58 (1966), p. 947.]
:fn-83: footnote:[Cf. Decr. Ad gentes, 35: AAS 58 (1966), p. 983.]
:fn-84: footnote:[S. Agustín, Enarrat, in Ps 44, 23: CCL XXXVIII, p. 510; cf. Conc. Ecum. Vat. II, Decr. Ad gentes, 1: AAS 58 (1966), p. 947.]

59&#46; Si hay hombres que proclaman en el mundo el Evangelio de salvación, lo hacen por mandato, en nombre y con la gracia de Cristo Salvador. "¿Cómo predicarán si no son enviados?"{fn-81}, escribía el que fue sin duda uno de los más grandes evangelizadores. Nadie puede hacerlo, sin haber sido enviado.

¿Quién tiene, pues, la misión de evangelizar?

El Concilio Vaticano II ha dado una respuesta clara: "Incumbe a la Iglesia por mandato divino ir por todo el mundo y anunciar el Evangelio a toda creatura"{fn-82}. Y en otro texto afirma: "La Iglesia entera es misionera, la obra de evangelización es un deber fundamental del pueblo de Dios"{fn-83}.

Hemos recordado anteriormente esta vinculación íntima entre la Iglesia y la evangelización. Cuando la Iglesia anuncia el reino de Dios y lo construye, ella se implanta en el corazón del mundo como signo e instrumento de ese reino que está ya presente y que viene. El Concilio ha recogido, porque son muy significativas, estas palabras de San Agustín sobre la acción misionera de los Doce: "predicando la palabra de verdad, engendraron las Iglesias"{fn-84}.

[[evangelii-nuntiandi-60]]
== Un acto eclesial

60&#46; La constatación de que la Iglesia es enviada y tiene el mandato de evangelizar a todo el mundo, debería despertar en nosotros una doble convicción.

Primera: evangelizar no es para nadie un acto individual y aislado, sino profundamente eclesial. Cuando el más humilde predicador, catequista o Pastor, en el lugar más apartado, predica el Evangelio, reúne su pequeña comunidad o administra un sacramento, aun cuando se encuentra solo, ejerce un acto de Iglesia y su gesto se enlaza mediante relaciones institucionales ciertamente, pero también mediante vínculos invisibles y raíces escondidas del orden de la gracia, a la actividad evangelizadora de toda la Iglesia. Esto supone que lo haga, no por una misión que él se atribuye o por inspiración personal, sino en unión con la misión de la Iglesia y en su nombre.

De ahí, la segunda convicción: si cada cual evangeliza en nombre de la Iglesia, que a su vez lo hace en virtud de un mandato del Señor, ningún evangelizador es el dueño absoluto de su acción evangelizadora, con un poder discrecional para cumplirla según los criterios y perspectivas individualistas, sino en comunión con la Iglesia y sus Pastores.

La Iglesia es toda ella evangelizadora, como hemos subrayado. Esto significa que para el conjunto del mundo y para cada parte del mismo donde ella se encuentra, la Iglesia se siente responsable de la tarea de difundir el Evangelio.

[[evangelii-nuntiandi-61]]
== La perspectiva de la Iglesia universal

:fn-85: footnote:[S. Gregorio Magno, Homil. in Evangelia 19, 1: PL 76, 1154.]
:fn-86: footnote:[Act 1, 8; cf. Didaché, 9, 1: Funk, Patres Apostolici, 1, 22.]
:fn-87: footnote:[Mt. 28, 20.]
:fn-88: footnote:[Cf. Mt. 13, 32.]
:fn-89: footnote:[Cf. Mt. 13, 47.]
:fn-90: footnote:[Cf. Jn. 21, 11.]
:fn-91: footnote:[Cf. Jn. 10, 1-16.]

61&#46; Llegados a este punto de nuestra reflexión nos detenemos con vosotros, hermanos e hijos, sobre una cuestión particularmente importante en nuestros días.

En su celebración litúrgica, en su testimonio ante los jueces y los verdugos, en sus textos apologéticos, los primeros cristianos manifestaban gustosamente su fe profunda en la Iglesia, indicándola como extendida por todo el universo. Tenían plena conciencia de pertenecer a una gran comunidad que ni el espacio ni el tiempo podían limitar: "Desde el justo Abel hasta el último elegido"{fn-85}, "hasta los extremos de la tierra"{fn-86}, "hasta la consumación del mundo"{fn-87}.

Así ha querido el Señor a su Iglesia: universal, árbol grande cuyas ramas dan cobijo a las aves del cielo{fn-88}, red que recoge toda clase de peces{fn-89} o que Pedro saca cargada de 153 grandes peces{fn-90}, rebaño que un solo pastor conduce a los pastos{fn-91}. Iglesia universal sin límites ni fronteras, salvo, por desgracia, las del corazón y del espíritu del hombre pecador.

[[evangelii-nuntiandi-62]]
== La perspectiva de la Iglesia particular

62&#46; Sin embargo, esta Iglesia universal se encarna de hecho en las Iglesias particulares, constituidas de tal o cual porción de humanidad concreta, que hablan tal lengua, son tributarias de una herencia cultural, de una visión del mundo, de un pasado histórico, de un substrato humano determinado. La apertura a las riquezas de la Iglesia particular responde a una sensibilidad especial del hombre contemporáneo.

Guardémonos bien de concebir la Iglesia universal como la suma o, si se puede decir, la federación más o menos anómala de Iglesias particulares esencialmente diversas. En el pensamiento del Señor es la Iglesia, universal por vocación y por misión, la que, echando sus raíces en la variedad de terrenos culturales, sociales, humanos, toma en cada parte del mundo aspectos, expresiones externas diversas.

Por lo mismo, una Iglesia particular que se desgajara voluntariamente de la Iglesia universal perdería su referencia al designio de Dios y se empobrecería en su dimensión eclesial. Pero, por otra parte, la Iglesia "difundida por todo el orbe" se convertiría en una abstracción, si no tomase cuerpo y vida precisamente a través de las Iglesias particulares. Sólo una atención permanente a los dos polos de la Iglesia nos permitirá percibir la riqueza de esta relación entre la Iglesia universal e Iglesias particulares.

[[evangelii-nuntiandi-63]]
== Adaptación y fidelidad de lenguaje

:fn-92: footnote:[Cf. Conc. Ecum. Vat. II, Const. Sacrosanctum Concilium, 37-38: AAS 56 (1964), p. 110. Cf. también los libros litúrgicos y los demás documentos emanados posteriormente de la Santa Sede para llevar a cabo la reforma litúrgica preconizada por el mismo Concilio.]

63&#46; Las Iglesias particulares profundamente amalgamadas, no sólo con las personas, sino también con las aspiraciones, las riquezas y límites, las maneras de orar, de amar, de considerar la vida y el mundo que distinguen a tal o cual conjunto humano, tienen la función de asimilar lo esencial del mensaje evangélico, de trasvasarlo, sin la menor traición a su verdad esencial, al lenguaje que esos hombres comprenden, y, después de anunciarlo en ese mismo lenguaje.

Dicho trasvase hay que hacerlo con el discernimiento, la seriedad, el respeto y la competencia que exige la materia, en el campo de las expresiones litúrgicas{fn-92}, de las catequesis, de la formulación teológica, de las estructuras eclesiales secundarias, de los ministerios. El lenguaje debe entenderse aquí no tanto a nivel semántico o literario cuanto al que podría llamarse antropológico y cultural.

El problema es sin duda delicado. La evangelización pierde mucho de su fuerza y de su eficacia, si no toma en consideración al pueblo concreto al que se dirige, si no utiliza su "lengua", sus signos y símbolos, si no responde a las cuestiones que plantea, no llega a su vida concreta. Pero, por otra parte, la evangelización corre el riesgo de perder su alma y desvanecerse, si se vacía o desvirtúa su contenido, bajo pretexto de traducirlo; si queriendo adaptar una realidad universal a un espacio local, se sacrifica esta realidad y se destruye la unidad sin la cual no hay universalidad. Ahora bien, solamente una Iglesia que mantenga la conciencia de su universalidad y demuestre que es de hecho universal puede tener un mensaje capaz de ser entendido por encima de los límites regionales, en el mundo entero.

Una legítima atención a las Iglesias particulares no puede menos de enriquecer a la Iglesia. Es indispensable y urgente. Responde a las aspiraciones más profundas de los pueblos y de las comunidades humanas de hallar cada vez más su propia fisonomía.

[[evangelii-nuntiandi-64]]
== Apertura de la Iglesia universal

64&#46; Pero este enriquecimiento exige que las Iglesias locales mantengan esa clara apertura a la Iglesia universal. Hay que notar bien, por lo demás, que los cristianos más sencillos, más evangélicos, más abiertos al verdadero sentido de la Iglesia, tienen una sensibilidad espontánea con respecto a esta dimensión universal; sienten instintiva y profundamente su necesidad; se reconocen fácilmente en ella, vibran con ella y sufren en lo más hondo de sí mismos cuando, en nombre de teorías que ellos no comprenden, se les quiere imponer una iglesia desprovista de esta universalidad, iglesia regionalista, sin horizontes.

Por otra parte, como demuestra la historia, cada vez que tal o cual Iglesia particular, a veces con las mejores intenciones, con argumentos teológicos, sociológicos, políticos o pastorales, o también con el deseo de una cierta libertad de movimiento o de acción, se ha desgajado de la Iglesia universal y de su centro viviente y visible, muy difícilmente ha escapado —si es que lo ha logrado— a dos peligros igualmente graves: peligro, por una parte, de aislamiento esterilizador y también, a corto plazo, de desmoronamiento, separándose de ella las células, igual que ella se ha separado del núcleo central; y, por otra parte, peligro de perder su libertad cuando, desgajada del centro y de las otras Iglesias que le comunicaban fuerza y energía, se encuentra abandonada, quedando sola frente a las fuerzas más diversas de servilismo y explotación.

Cuanto más ligada está una Iglesia particular por vínculos sólidos a la Iglesia universal —en la caridad y la lealtad, en la apertura al Magisterio de Pedro, en la unidad de la Lex orandi, que es también Lex credendi, en el deseo de unidad con todas las demás Iglesias que componen la universalidad—, tanto más esta Iglesia será capaz de traducir el tesoro de la fe en la legítima variedad de expresiones de la profesión de fe, de la oración y del culto, de la vida y del comportamiento cristianos, del esplendor del pueblo en que ella se inserta. Tanto más será también evangelizadora de verdad, es decir, capaz de beber en el patrimonio universal para lograr que el pueblo se aproveche de él, así como de comunicar a la Iglesia universal la experiencia y la vida de su pueblo, en beneficio de todos.

[[evangelii-nuntiandi-65]]
== El inalterable depósito de la fe

:fn-93: footnote:[Pablo VI, Discurso en la clausura de la III Asamblea General del Sínodo de los Obispos (23 octubre 1974): AAS 66 (1974), p. 636.]

65&#46; Precisamente en este sentido quisimos pronunciar, en la clausura del Sínodo, una palabra clara y llena de paterno afecto, insistiendo sobre la función del Sucesor de Pedro como principio visible, viviente y dinámico de la unidad entre las Iglesias y, consiguientemente, de la universalidad de la única Iglesia{fn-93}. Insistíamos también sobre la grave responsabilidad que nos incumbe, que compartimos con nuestros hermanos en el Episcopado, de guardar inalterable el contenido de la fe católica que el Señor confió a los Apóstoles: traducido en todos los lenguajes, revestido de símbolos propios en cada pueblo, explicitado por expresiones teológicas que tienen en cuenta medios culturales, sociales y también raciales diversos, debe seguir siendo el contenido de la fe católica tal cual el Magisterio eclesial lo ha recibido y lo transmite.

[[evangelii-nuntiandi-66]]
== Tareas diferenciadas

:fn-94: footnote:[Cf. Jn. 15, 16; Mc. 3, 13-19; Lc. 6, 13-16.]
:fn-95: footnote:[Cf. Act. 21-22.]
:fn-96: footnote:[Cf. Mc. 3, 14.]
:fn-97: footnote:[Cf. Mc. 3, 15; Lc. 9, 2.]

66&#46; Toda la Iglesia está pues llamada a evangelizar y, sin embargo, en su seno tenemos que realizar diferentes tareas evangelizadoras. Esta diversidad de servicios en la unidad de la misma misión constituye la riqueza y la belleza de la evangelización. Recordemos estas tareas en pocas palabras.

En primer lugar, séanos permitido señalar en las páginas del Evangelio la insistencia con la que el Señor confía a los Apóstoles la función de anunciar la Palabra. El los ha escogido{fn-94}, formado durante varios años de intimidad{fn-95}, constituido{fn-96} y mandado{fn-97} como testigos y maestros autorizados del mensaje de salvación. Y los Doce han enviado a su vez a sus sucesores que, en la línea apostólica, continúan predicando la Buena Nueva.

[[evangelii-nuntiandi-67]]
== El Sucesor de Pedro

:fn-98: footnote:[Act. 4, 8: cf. 2, 14; 2, 12.]
:fn-99: footnote:[Cf. S. León Magno, Sermo 69, 3; Sermo 70, 1-3; Sermo 94, 3; Sermo 95, 2: S. Ch. 200, pp. 50-52; 58-66; 258-260; 268.]
:fn-100: footnote:[Cf. Conc. Ecum. Lugdunense I. Const. Ad apostolicae dignitatis: Conciliorum Oecumenicorum Decreta, Ed. Instituto per le Scienze Religiose, Bolonia 1973, p. 278; Conc. Ecum. Viennense, Const. Ad providam Christi, ed. cit., p. 343; Conc. Ecum. Lateranense V. Bula In apostolici culminis, ed. cit., p. 606; Bula Postquam ad universalis, ed. cit., p. 609; Const. Supernae dispositionis, ed. cit., p. 614; Const. Divina disponente clementia, ed. cit., p. 638.]
:fn-101: footnote:[Decr. Ad gentes, 38: AAS 58 (1966), p. 985.]
:fn-102: footnote:[Cf. Conc. Ecum. Vat. II, Const. dogm. Lumen gentium 22: AAS 57 (1965), p. 26.]

67&#46; El Sucesor de Pedro, por voluntad de Cristo, está encargado del ministerio preeminente de enseñar la verdad revelada. El Nuevo Testamento presenta frecuentemente a Pedro "lleno del Espíritu Santo", tomando la palabra en nombre de todos{fn-98}. Por eso mismo San León Magno habla de él como de aquel que ha merecido el primado del apostolado{fn-99}. Por la misma razón la voz de la Iglesia presenta al Papa "en el culmen —in apice, in specula—, del apostolado"{fn-100}. El Concilio Vaticano II ha querido subrayarlo, declarando que "el mandato de Cristo de predicar el Evangelio a toda criatura (cf. Mc 16, 15) se refiere ante todo e inmediatamente a los obispos con Pedro y bajo la guía de Pedro"{fn-101}.

La potestad plena, suprema y universal{fn-102} que Cristo ha confiado a su Vicario para el gobierno pastoral de su Iglesia, consiste por tanto especialmente en la actividad, que ejerce el Papa, de predicar y de hacer predicar la Buena Nueva de la salvación.

[[evangelii-nuntiandi-68]]
== Obispos y Sacerdotes

:fn-103: footnote:[Cf. Conc. Ecum. Vat. II, Const. dogm. Lumen gentium, 10, 37: AAS 57 (1965), pp. 14, 43; Decr. Ad gentes, 39: AAS 58 (1966), p. 986; Decr. Presbyterorum ordinis, 2. 12, 13; AAS 58 (1966), pp. 992, 1010, 1011.]
:fn-104: footnote:[Cf. 1 Tes. 2, 9.]
:fn-105: footnote:[Cf. 1 Pe. 5, 4.]

68&#46; Unidos al Sucesor de Pedro, los obispos, sucesores de los Apóstoles, reciben en virtud de su ordenación episcopal, la autoridad para enseñar en la Iglesia la verdad revelada. Son los maestros de la fe.

A los obispos están asociados en el ministerio de la evangelización, como responsables a título especial, los que por la ordenación sacerdotal obran en nombre de Cristo{fn-103}, en cuanto educadores del pueblo de Dios en la fe, predicadores, siendo además ministros de la Eucaristía y de los otros sacramentos.

Todos nosotros, los Pastores, estamos pues invitados a tomar conciencia de este deber, más que cualquier otro miembro de la Iglesia. Lo que constituye la singularidad de nuestro servicio sacerdotal, lo que da unidad profunda a la infinidad de tareas que nos solicitan a lo largo de la jornada y de la vida, lo que confiere a nuestras actividades una nota específica, es precisamente esta finalidad presente en toda acción nuestra: "anunciar el Evangelio de Dios"{fn-104}.

He ahí un rasgo de nuestra identidad, que ninguna duda debiera atacar, ni ninguna objeción eclipsar: en cuanto Pastores, hemos sido escogidos por la misericordia del Supremo Pastor{fn-105}, a pesar de nuestra insuficiencia, para proclamar con autoridad la Palabra de Dios; para reunir al pueblo de Dios que estaba disperso: para alimentar a este pueblo con los signos de la acción de Cristo que son los sacramentos; para ponerlo en el camino de la salvación; para mantenerlo en esa unidad de la que nosotros somos, a diferentes niveles, instrumentos activos y vivos; para animar sin cesar a esta comunidad reunida en torno a Cristo siguiendo la línea de su vocación más íntima. Y cuando, en la medida de nuestros límites humanos y secundando la gracia de Dios, cumplimos todo esto, realizamos una labor de evangelización: Nos, como Pastor de la Iglesia universal; nuestros hermanos los obispos, a la cabeza de las Iglesias locales; los sacerdotes y diáconos, unidos a sus obispos, de los que son colaboradores, por una comunión que tiene su fuente en el sacramento del orden y en la caridad de la Iglesia.

[[evangelii-nuntiandi-69]]
== Los religiosos

69&#46; Los religiosos, también ellos, tienen en su vida consagrada un medio privilegiado de evangelización eficaz. A través de su ser más íntimo, se sitúan dentro del dinamismo de la Iglesia, sedienta de lo Absoluto de Dios, llamada a la santidad. Es de esta santidad de la que ellos dan testimonio. Ellos encarnan la Iglesia deseosa de entregarse al radicalismo de las bienaventuranzas. Ellos son por su vida signo de total disponibilidad para con Dios, la Iglesia, los hermanos.

Por esto, asumen una importancia especial en el marco del testimonio que, como hemos dicho anteriormente, es primordial en la evangelización. Este testimonio silencioso de pobreza y de desprendimiento, de pureza y de transparencia, de abandono en la obediencia puede ser a la vez que una interpelación al mundo y a la Iglesia misma, una predicación elocuente, capaz de tocar incluso a los no cristianos de buena voluntad, sensibles a ciertos valores.

En esta perspectiva se intuye el papel desempeñado en la evangelización por los religiosos y religiosas consagrados a la oración, al silencio, a la penitencia, al sacrificio. Otros religiosos, en gran número, se dedican directamente al anuncio de Cristo. Su actividad misionera depende evidentemente de la jerarquía y debe coordinarse con la pastoral que ésta desea poner en práctica. Pero, ¿quién no mide el gran alcance de lo que ellos han aportado y siguen aportando a la evangelización? Gracias a su consagración religiosa, ellos son, por excelencia, voluntarios y libres para abandonar todo y lanzarse a anunciar el Evangelio hasta los confines de la tierra. Ellos son emprendedores y su apostolado está frecuentemente marcado por una originalidad y una imaginación que suscitan admiración. Son generosos: se les encuentra no raras veces en la vanguardia de la misión y afrontando los más grandes riesgos para su salud y su propia vida. Sí, en verdad, la Iglesia les debe muchísimo.

[[evangelii-nuntiandi-70]]
== Los seglares

70&#46; Los seglares, cuya vocación específica los coloca en el corazón del mundo y a la guía de las más variadas tareas temporales, deben ejercer por lo mismo una forma singular de evangelización.

Su tarea primera e inmediata no es la institución y el desarrollo de la comunidad eclesial —esa es la función específica de los Pastores—, sino el poner en práctica todas las posibilidades cristianas y evangélicas escondidas, pero a su vez ya presentes y activas en las cosas del mundo. El campo propio de su actividad evangelizadora, es el mundo vasto y complejo de la política, de lo social, de la economía, y también de la cultura, de las ciencias y de las artes, de la vida internacional, de los medios de comunicación de masas, así como otras realidades abiertas a la evangelización como el amor, la familia, la educación de los niños y jóvenes, el trabajo profesional, el sufrimiento, etc. Cuantos más seglares hayan impregnados del Evangelio, responsables de estas realidades y claramente comprometidos en ellas, competentes para promoverlas y conscientes de que es necesario desplegar su plena capacidad cristianas, tantas veces oculta y asfixiada, tanto más estas realidades —sin perder o sacrificar nada de su coeficiente humano, al contrario, manifestando una dimensión trascendente frecuentemente desconocida— estarán al servicio de la edificación del reino de Dios y, por consiguiente, de la salvación en Cristo Jesús.

[[evangelii-nuntiandi-71]]
== La familia

:fn-106: footnote:[Const. dogm. Lumen gentium, 11: AAS 57 91965), p. 16; Decr. Apostolicam actuositatem, 11: AAS 58 (1966), p. 848; S. Juan Crisóstomo, in Genesim Serm. VI, 2; VI, 1: PG 54, 607-608.]

71&#46; En el seno del apostolado evangelizador de los seglares, es imposible dejar de subrayar la acción evangelizadora de la familia. Ella ha merecido muy bien, en los diferentes momentos de la historia y en el Concilio Vaticano II, el hermoso nombre de "Iglesia doméstica"{fn-106}. Esto significa que en cada familia cristiana deberían reflejarse los diversos aspectos de la Iglesia entera. Por otra parte, la familia, al igual que la Iglesia, debe ser un espacio donde el Evangelio es transmitido y desde donde éste se irradia.

Dentro, pues, de una familia consciente de esta misión, todos los miembros de la misma evangelizan y son evangelizados. Los padres no sólo comunican a los hijos el Evangelio, sino que pueden a su vez recibir de ellos este mismo Evangelio profundamente vivido. También las familias formadas por un matrimonio mixto tienen el deber de anunciar a Cristo a los hijos en la plenitud de las implicaciones del bautismo común; tienen además la no fácil tarea de hacerse artífices de unidad.

Una familia así se hace evangelizadora de otras muchas familias y del ambiente en que ella vive.

[[evangelii-nuntiandi-72]]
== Los jóvenes

72&#46; Las circunstancias nos invitan a prestar una atención especialísima a los jóvenes. Su importancia numérica y su presencia creciente en la sociedad, los problemas que se les plantean deben despertar en nosotros el deseo de ofrecerles con celo e inteligencia el ideal que deben conocer y vivir. Pero, además, es necesario que los jóvenes bien formados en la fe y arraigados en la oración, se conviertan cada vez más en los apóstoles de la juventud. La Iglesia espera mucho de ellos. Por nuestra parte, hemos manifestado con frecuencia la confianza que depositamos en la juventud.

[[evangelii-nuntiandi-73]]
== Ministerios diversificados

73&#46; Es así como adquiere toda su importancia la presencia activa de los seglares en medio de las realidades temporales. No hay que pasar pues por alto u olvidar otra dimensión: los seglares también pueden sentirse llamados o ser llamados a colaborar con sus Pastores en el servicio de la comunidad eclesial, para el crecimiento y la vida de ésta, ejerciendo ministerios muy diversos según la gracia y los carismas que el Señor quiera concederles.

No sin experimentar íntimamente un gran gozo, vemos cómo una legión de Pastores, religiosos y seglares, enamorados de su misión evangelizadora, buscan formas cada vez más adaptadas de anunciar eficazmente el Evangelio, y alentamos la apertura que, en esta línea y con este afán, la Iglesia está llevando a cabo hoy día. Apertura a la reflexión en primer lugar, luego a los ministerios eclesiales capaces de rejuvenecer y de reforzar su propio dinamismo evangelizador.

Es cierto que al lado de los ministerios con orden sagrado, en virtud de los cuales algunos son elevados al rango de Pastores y se consagran de modo particular al servicio de la comunidad, la Iglesia reconoce un puesto a ministerios sin orden sagrado, pero que son aptos a asegurar un servicio especial a la Iglesia.

Una mirada sobre los orígenes de la Iglesia es muy esclarecedora y aporta el beneficio de una experiencia en materia de ministerios, experiencia tanto más valiosa en cuanto que ha permitido a la Iglesia consolidarse, crecer y extenderse. No obstante, esta atención a las fuentes debe ser completada con otra: la atención a las necesidades actuales de la humanidad y de la Iglesia. Beber en estas fuentes siempre inspiradoras, no sacrificar nada de estos valores y saber adaptarse a las exigencias y a las necesidades actuales, tales son los ejes que permitirán buscar con sabiduría y poner en claro los ministerios que necesita la Iglesia y que muchos de sus miembros querrán abrazar para la mayor vitalidad de la comunidad eclesial. Estos ministerios adquirirán un verdadero valor pastoral y serán constructivos en la medida en que se realicen con respecto absoluto de la unidad, beneficiándose de la orientación de los Pastores, que son precisamente los responsables y artífices de la unidad de la Iglesia.

Tales ministerios, nuevos en apariencia pero muy vinculados a experiencias vividas por la Iglesia a lo largo de su existencia —catequistas, animadores de la oración y del canto, cristianos consagrados al servicio de la palabra de Dios o a la asistencia de los hermanos necesitados, jefes de pequeñas comunidades, responsables de Movimientos apostólicos u otros responsables—, son preciosos para la implantación, la vida y el crecimiento de la Iglesia y para su capacidad de irradiarse en torno a ella y hacia los que están lejos. Nos debemos asimismo nuestra estima particular a todos los seglares que aceptan consagrar una parte de su tiempo, de sus energías y, a veces, de su vida entera, al servicio de las misiones.

Para los agentes de la evangelización se hace necesaria una seria preparación. Tanto más para quienes se consagran al ministerio de la Palabra. Animados por la convicción, cada vez mayor, de la grandeza y riqueza de la palabra de Dios, quienes tienen la misión de transmitirla deben prestar gran atención a la dignidad, a la precisión y a la adaptación del lenguaje. Todo el mundo sabe que el arte de hablar reviste hoy día una grandísima importancia. ¿Cómo podrían descuidarla los predicadores y los catequistas?

Deseamos vivamente, que en cada Iglesia particular, los obispos vigilen por la adecuada formación de todos los ministros de la Palabra. Esta preparación llevada a cabo con seriedad aumentará en ellos la seguridad indispensable y también el entusiasmo para anunciar hoy día a Cristo.
