[[evangelii-nuntiandi-part-7]]
= VII - EL ESPÍRITU DE LA EVANGELIZACIÓN

[[evangelii-nuntiandi-74]]
== Exhortación apremiante

74&#46; No quisiéramos poner fin a este coloquio con nuestros hermanos e hijos amadísimos, sin hacer una llamada referente a las actitudes interiores que deben animar a los obreros de la evangelización.

En nombre de nuestro Señor Jesucristo, de los Apóstoles Pedro y Pablo, exhortamos a todos aquellos que, gracias a los carismas del Espíritu y al mandato de la Iglesia, son verdaderos evangelizadores, a ser dignos de esta vocación, a ejercerla sin resistencias debidas a la duda o al temor, a no descuidar las condiciones que harán esta evangelización no sólo posible, sino también activa y fructuosa. He aquí, entre otras las condiciones fundamentales que queremos subrayar.

[[evangelii-nuntiandi-75]]
== Bajo el aliento del Espíritu

:fn-107: footnote:[Mt. 3, 17.]
:fn-108: footnote:[Mt. 4, 1.]
:fn-109: footnote:[Lc. 4, 14.]
:fn-110: footnote:[Lc. 4, 18, 21 cf. Is 61, 1.]
:fn-111: footnote:[Jn. 20, 22.]
:fn-112: footnote:[Act. 2, 17.]
:fn-113: footnote:[Cf. Act. 4, 8.]
:fn-114: footnote:[Cf. Act. 9, 17.]
:fn-115: footnote:[Cf. Act. 6, 5. 10; 7, 55.]
:fn-116: footnote:[Cf. Act. 10, 44.]
:fn-117: footnote:[Cf. Act. 9, 31.]
:fn-118: footnote:[Cf. Conc. Ecum. Vat. II, Decr. Ad gentes, 4: AAS 58 (1966), pp. 950-951.]

75&#46; No habrá nunca evangelización posible sin la acción del Espíritu Santo. Sobre Jesús de Nazaret el Espíritu descendió en el momento del bautismo, cuando la voz del Padre —"Tú eres mi hijo muy amado, en ti pongo mi complacencia"—{fn-107} manifiesta de manera sensible su elección y misión.

Es "conducido por el Espíritu" para vivir en el desierto el combate decisivo y la prueba suprema antes de dar comienzo a esta misión{fn-108}. "Con la fuerza del Espíritu"{fn-109}vuelve a Galilea e inaugura en Nazaret su predicación, aplicándose a sí mismo el pasaje de Isaías: "El Espíritu del Señor está sobre mí". "Hoy —proclama El— se cumple esta Escritura"{fn-110}. A los Discípulos, a quienes está para enviar, les dice alentando sobre ellos: "Recibid el Espíritu Santo"{fn-111}.

En efecto, solamente después de la venida del Espíritu Santo, el día de Pentecostés, los Apóstoles salen hacia todas las partes del mundo para comenzar la gran obra de evangelización de la Iglesia, y Pedro explica el acontecimiento como la realización de la profecía de Joel: "Yo derramaré mi Espíritu"{fn-112}. Pedro, lleno del Espíritu Santo habla al pueblo acerca de Jesús Hijo de Dios{fn-113}. Pablo mismo está lleno del Espíritu Santo{fn-114} ante de entregarse a su ministerio apostólico, como lo está también Esteban cuando es elegido diácono y más adelante, cuando da testimonio con su sangre{fn-115}. El Espíritu que hace hablar a Pedro, a Pablo y a los Doce, inspirando las palabras que ellos deben pronunciar, desciende también "sobre los que escuchan la Palabra"{fn-116}.

"Gracias al apoyo del Espíritu Santo, la Iglesia crece"{fn-117}. El es el alma de esta Iglesia. El es quien explica a los fieles el sentido profundo de las enseñanzas de Jesús y su misterio. El es quien, hoy igual que en los comienzos de la Iglesia, actúa en cada evangelizador que se deja poseer y conducir por El, y pone en los labios las palabras que por sí solo no podría hallar, predisponiendo también el alma del que escucha para hacerla abierta y acogedora de la Buena Nueva y del reino anunciado.

Las técnicas de evangelización son buenas, pero ni las más perfeccionadas podrían reemplazar la acción discreta del Espíritu. La preparación más refinada del evangelizador no consigue absolutamente nada sin El. Sin El, la dialéctica más convincente es impotente sobre el espíritu de los hombres. Sin El, los esquemas más elaborados sobre bases sociológicas o sicológicas se revelan pronto desprovistos de todo valor.

Nosotros vivimos en la Iglesia un momento privilegiado del Espíritu. Por todas partes se trata de conocerlo mejor, tal como lo revela la Escritura. Uno se siente feliz de estar bajo su moción. Se hace asamblea en torno a El. Quiere dejarse conducir por El.

Ahora bien, si el Espíritu de Dios ocupa un puesto eminente en la vida de la Iglesia, actúa todavía mucho más en su misión evangelizadora. No es una casualidad que el gran comienzo de la evangelización tuviera lugar la mañana de Pentecostés, bajo el soplo del Espíritu.

Puede decirse que el Espíritu Santo es el agente principal de la evangelización: El es quien impulsa a cada uno a anunciar el Evangelio y quien en lo hondo de las conciencias hace aceptar y comprender la Palabra de salvación{fn-118}. Pero se puede decir igualmente que El es el término de la evangelización: solamente El suscita la nueva creación, la humanidad nueva a la que la evangelización debe conducir, mediante la unidad en la variedad que la misma evangelización querría provocar en la comunidad cristiana. A través de El, la evangelización penetra en los corazones, ya que El es quien hace discernir los signos de los tiempos —signos de Dios— que la evangelización descubre y valoriza en el interior de la historia.

El Sínodo de los Obispos de 1974, insistiendo mucho sobre el puesto que ocupa el Espíritu Santo en la evangelización, expresó asimismo el deseo de que Pastores y teólogos —y añadiríamos también los fieles marcados con el sello del Espíritu en el bautismo— estudien profundamente la naturaleza y la forma de la acción del Espíritu Santo en la evangelización de hoy día. Este es también nuestro deseo, al mismo tiempo que exhortamos a todos y cada uno de los evangelizadores a invocar constantemente con fe y fervor al Espíritu Santo y a dejarse guiar prudentemente por El como inspirador decisivo de sus programas, de sus iniciativas, de su actividad evangelizadora.

[[evangelii-nuntiandi-76]]
== Testigos auténticos

:fn-119: footnote:[Cf. Jn. 17, 21.]
:fn-120: footnote:[Cf. Act. 20, 28.]
:fn-121: footnote:[Cf. Decr. Presbyterorum ordinis, 13: AAS 58 (1966), p. 1011.]
:fn-122: footnote:[Cf. Heb. 11, 27.]

76&#46; Consideramos ahora la persona misma de los evangelizadores. Se ha repetido frecuentemente en nuestros días que este siglo siente sed de autenticidad. Sobre todo con relación a los jóvenes, se afirma que éstos sufren horrores ante lo ficticio, ante la falsedad, y que además son decididamente partidarios de la verdad y la transparencia.

A estos "signos de los tiempos" debería corresponder en nosotros una actitud vigilante. Tácitamente o a grandes gritos, pero siempre con fuerza, se nos pregunta: ¿Creéis verdaderamente en lo que anunciáis? ¿Vivís lo que creéis? ¿Predicáis verdaderamente lo que vivís? Hoy más que nunca el testimonio de vida se ha convertido en una condición esencial con vistas a una eficacia real de la predicación. Sin andar con rodeos, podemos decir que en cierta medida nos hacemos responsables del Evangelio que proclamamos.

Al comienzo de esta reflexión, nos hemos preguntado: ¿Qué es de la Iglesia, diez años después del Concilio? ¿Está anclada en el corazón del mundo y es suficientemente libre e independiente para interpelar al mundo? ¿Da testimonio de la propia solidaridad hacia los hombres y al mismo tiempo del Dios Absoluto? ¿Ha ganado en ardor contemplativo y de adoración, y pone más celo en la actividad misionera, caritativa, liberadora? ¿Es suficiente su empeño en el esfuerzo de buscar el restablecimiento de la plena unidad entre los cristianos, lo cual hace más eficaz el testimonio común, con el fin de que el mundo crea?{fn-119}. Todos nosotros somos responsables de las respuestas que pueden darse a estos interrogantes.

Exhortamos, pues, a nuestros hermanos en el Episcopado, puestos por el Espíritu Santo para gobernar la Iglesia de Dios{fn-120}. Exhortamos a los sacerdotes y a los diáconos, colaboradores de los obispos para congregar el pueblo de Dios y animar espiritualmente las comunidades locales. Exhortamos también a los religiosos y religiosas, testigos de una Iglesia llamada a la santidad y, por tanto, invitados de manera especial a una vida que dé testimonio de las bienaventuranzas evangélicas. Exhortamos asimismo a los seglares: familias cristianas, jóvenes y adultos, a todos los que tienen un cargo, a los dirigentes, sin olvidar a los pobres tantas veces ricos de fe y de esperanza, a todos los seglares conscientes de su papel evangelizador al servicio de la Iglesia o en el corazón de la sociedad y del mundo. Nos les decimos a todos: es necesario que nuestro celo evangelizador brote de una verdadera santidad de vida y que, como nos lo sugiere el Concilio Vaticano II, la predicación alimentada con la oración y sobre todo con el amor a la Eucaristía, redunde en mayor santidad del predicador{fn-121}.

Paradójicamente, el mundo, que a pesar de los innumerables signos de rechazo de Dios lo busca sin embargo por caminos insospechados y siente dolorosamente su necesidad, el mundo exige a los evangelizadores que le hablen de un Dios a quien ellos mismos conocen y tratan familiarmente, como si estuvieran viendo al Invisible{fn-122}. El mundo exige y espera de nosotros sencillez de vida, espíritu de oración, caridad para con todos, especialmente para los pequeños y los pobres, obediencia y humildad, desapego de sí mismos y renuncia. Sin esta marca de santidad, nuestra palabra difícilmente abrirá brecha en el corazón de los hombres de este tiempo. Corre el riesgo de hacerse vana e infecunda.

[[evangelii-nuntiandi-77]]
== Búsqueda de la unidad

:fn-123: footnote:[Decr. Ad gentes, 6: AAS 58 (1966), pp. 954-955; cf. Decr. Unitatis redintegratio, 1: AAS 57 (1965), pp. 90-91.]
:fn-124: footnote:[Bula Apostolorum limina, VII: AAS 66 (1974), p. 305.]
:fn-125: footnote:[Rom. 5, 5.]

77&#46; La fuerza de la evangelización quedará muy debilitada si los que anuncian el Evangelio están divididos entre sí por tantas clases de rupturas. ¿No estará quizás ahí uno de los grandes males de la evangelización? En efecto, si el Evangelio que proclamamos aparece desgarrado por querellas doctrinales, por polarizaciones ideológicas o por condenas recíprocas entre cristianos, al antojo de sus diferentes teorías sobre Cristo y sobre la Iglesia, e incluso a causa de sus distintas concepciones de la sociedad y de las instituciones humanas, ¿cómo pretender que aquellos a los que se dirige nuestra predicación no se muestren perturbados, desorientados, si no escandalizados?

El testamento espiritual del Señor nos dice que la unidad entre sus seguidores no es solamente la prueba de que somos suyos, sino también la prueba de que El es el enviado del Padre, prueba de credibilidad de los cristianos y del mismo Cristo. Evangelizadores: nosotros debemos ofrecer a los fieles de Cristo, no la imagen de hombres divididos y separados por las luchas que no sirven para construir nada, sino la de hombres adultos en la fe, capaces de encontrarse más allá de las tensiones reales gracias a la búsqueda común, sincera y desinteresada de la verdad. Sí, la suerte de la evangelización está ciertamente vinculada al testimonio de unidad dado por la Iglesia. He aquí una fuente de responsabilidad, pero también de consuelo.

Dicho esto, queremos subrayar el signo de la unidad entre todos los cristianos, como camino e instrumento de evangelización. La división de los cristianos constituye una situación de hecho grave, que viene a cercenar la obra misma de Cristo. El Concilio Vaticano II dice clara y firmemente que esta división "perjudica la causa santísima de la predicación del Evangelio a toda criatura y cierra a muchos las puertas de la fe"{fn-123}.

Por eso, al anunciar el Año Santo creímos necesario recordar a todos los fieles del mundo católico que "la reconciliación de todos los hombres con Dios, nuestro Padre, depende del restablecimiento de la comunión de aquellos que ya han reconocido y aceptado en la fe a Jesucristo como Señor de la misericordia, que libera a los hombres y los une en el espíritu de amor y de verdad"{fn-124}.

Con una gran sensación de esperanza vemos los esfuerzos que se realizan en el mundo cristiano en orden al restablecimiento de la plena unidad, deseada por Cristo. San Pablo nos lo asegura: "la esperanza no quedará confundida"{fn-125}. Mientras seguimos trabajando para obtener del Señor la plena unidad, queremos que se intensifique la oración; además, hacemos nuestros los deseos de los padres del III Sínodo de los Obispos, que se colabore con mayor empeño con los hermanos cristianos a quienes todavía no estamos unidos por una comunión perfecta, basándonos en el fundamento del bautismo y de la fe que nos es común, para ofrecer desde ahora mediante la misma obra de evangelización un testimonio común más amplio de Cristo ante el mundo. Nos impulsa a ello el mandato de Cristo. Lo exige el deber de predicar y dar testimonio del Evangelio.

[[evangelii-nuntiandi-78]]
== Servidores de la verdad

:fn-126: footnote:[Cf. Jn. 8, 32.]

78&#46; El Evangelio que nos ha sido encomendado es también palabra de verdad. Una verdad que hace libres{fn-126} y que es la única que procura la paz del corazón; esto es lo que la gente va buscando cuando le anunciamos la Buena Nueva. La verdad acerca de Dios, la verdad acerca del hombre y de su misterioso destino, la verdad acerca del mundo. Verdad difícil que buscamos en la Palabra de Dios y de la cual nosotros no somos, lo repetimos una vez más, ni los dueños, ni los árbitros, sino los depositarios, los herederos, los servidores.

De todo evangelizador se espera que posea el culto a la verdad, puesto que la verdad que él profundiza y comunica no es otra que la verdad revelada y, por tanto, más que ninguna otra, forma parte de la verdad primera que es el mismo Dios. El predicador del Evangelio será aquel que, aun a costa de renuncias y sacrificios, busca siempre la verdad que debe transmitir a los demás. No vende ni disimula jamás la verdad por el deseo de agradar a los hombres, de causar asombro, ni por originalidad o deseo de aparentar. No rechaza nunca la verdad. No obscurece la verdad revelada por pereza de buscarla, por comodidad, por miedo. No deja de estudiarla. La sirve generosamente sin avasallarla.

Pastores del pueblo de Dios: nuestro servicio pastoral nos pide que guardemos, defendamos y comuniquemos la verdad sin reparar en sacrificio. Muchos eminentes y santos Pastores nos han legado el ejemplo de este amor, en muchos casos heroicos, a la verdad. El Dios de verdad espera de nosotros que seamos los defensores vigilantes y los predicadores devotos de la misma.

Doctores, ya seáis teólogos o exégetas, o historiadores: la obra de la evangelización tiene necesidad de vuestra infatigable labor de investigación y también de vuestra atención y delicadeza en la transmisión de la verdad, a la que vuestros estudios os acercan, pero que siempre desborda el corazón del hombre porque es la verdad misma de Dios.

Padres y maestros: vuestra tarea, que los múltiples conflictos actuales hacen difícil, es la de ayudar a vuestros hijos y alumnos a descubrir la verdad, comprendida la verdad religiosa y espiritual.

[[evangelii-nuntiandi-79]]
== Animados por el amor

:fn-127: footnote:[1 Tes. 2, 8: cf. Flp. 1, 8.]
:fn-128: footnote:[Cf. 1 Tes. 2, 7. 11; 1 Cor. 4, 15; Gál. 4, 19.]
:fn-129: footnote:[Cf. 1 Cor. 8, 9-13; Rom. 14, 15.]

79&#46; La obra de la evangelización supone, en el evangelizador, un amor fraternal siempre creciente hacia aquellos a los que evangeliza. Un modelo de evangelizador como el Apóstol San Pablo escribía a los tesalonicenses estas palabras que son todo un programa para nosotros: "Así, llevados de nuestro amor por vosotros, queremos no sólo daros el Evangelio de Dios, sino aun nuestras propias vidas: tan amados vinisteis a sernos"{fn-127}.

¿De qué amor se trata? Mucho más que el de un pedagogo; es el amor de un padre; más aún, el de una madre{fn-128}. Tal es el amor que el Señor espera de cada predicador del Evangelio, de cada constructor de la Iglesia.

Un signo de amor será el deseo de ofrecer la verdad y conducir a la unidad. Un signo de amor será igualmente dedicarse sin reservas y sin mirar atrás al anuncio de Jesucristo. Añadamos ahora otros signos de este amor.

El primero es el respeto a la situación religiosa y espiritual de la persona que se evangeliza. Respeto a su ritmo que no se puede forzar demasiado. Respecto a su conciencia y a sus convicciones, que no hay que atropellar.

Otra señal de este amor es el cuidado de no herir a los demás, sobre todo si son débiles en su fe{fn-129}, con afirmaciones que pueden ser claras para los iniciados, pero que pueden ser causa de perturbación o escándalo en los fieles, provocando una herida en sus almas.

Será también una señal de amor el esfuerzo desplegado para transmitir a los cristianos certezas sólidas basadas en la palabra de Dios, y no dudas o incertidumbres nacidas de una erudición mal asimilada. Los fieles tienen necesidad de esas certezas en su vida cristiana; tienen derecho a ellas en cuanto hijos de Dios que, poniéndose en sus brazos, se abandonan totalmente a las exigencias del amor.

[[evangelii-nuntiandi-80]]
== Con el fervor de los Santos

:fn-130: footnote:[Cf. Rom. 12, 11.]
:fn-131: footnote:[Cf. Conc. Ecum. Vat. II, Decl. Dignitatis humanae, 4: AAS 58 (1966), p. 933.]
:fn-132: footnote:[Cf. ib., 9-14: AAS, pp. 935-940.]
:fn-133: footnote:[Cf. Conc. Ecum. Vat. II, Decr. Ad gentes, 7: AAS 58 (1966), p. 955.]
:fn-134: footnote:[Cf. Rom. 1, 16.]

80&#46; Nuestra llamada se inspira ahora en el fervor de los más grandes predicadores y evangelizadores, cuya vida fue consagrada al apostolado. De entre ellos nos complacemos en recordar aquellos que Nos mismo hemos propuesto a la veneración de los fieles durante el Año Santo. Ellos han sabido superar todos los obstáculos que se oponían a la evangelización.

De tales obstáculos, que perduran en nuestro tiempo, nos limitaremos a citar la falta de fervor, tanto más grave cuanto que viene de dentro. Dicha falta de fervor se manifiesta en la fatiga y desilusión, en la acomodación al ambiente y en el desinterés, y sobre todo en la falta de alegría y de esperanza. Por ello, a todos aquellos que por cualquier título o en cualquier grado tienen la obligación de evangelizar, Nos los exhortamos a alimentar siempre el fervor del espíritu{fn-130}.

Este fervor exige, ante todo, que evitemos recurrir a pretextos que parecen oponerse a la evangelización. Los más insidiosos son ciertamente aquellos para cuya justificación se quieren emplear ciertas enseñanzas del Concilio.

Con demasiada frecuencia y bajo formas diversas se oye decir que imponer una verdad, por ejemplo la del Evangelio; que imponer una vía, aunque sea la de la salvación, no es sino una violencia cometida contra la libertad religiosa. Además, se añade, ¿para qué anunciar el Evangelio, ya que todo hombre se salva por la rectitud del corazón? Por otra parte, es bien sabido que el mundo y la historia están llenos de "semillas del Verbo". ¿No es, pues, una ilusión pretender llevar el Evangelio donde ya está presente a través de esas semillas que el mismo Señor ha esparcido?

Cualquiera que haga un esfuerzo por examinar a fondo, a la luz de los documentos conciliares, las cuestiones de tales y tan superficiales razonamientos plantean, encontrará una bien distinta visión de la realidad.

Sería ciertamente un error imponer cualquier cosa a la conciencia de nuestros hermanos. Pero proponer a esa conciencia la verdad evangélica y la salvación ofrecida por Jesucristo, con plena claridad y con absoluto respeto hacia las opciones libres que luego pueda hacer —sin coacciones, solicitaciones menos rectas o estímulos indebidos—{fn-131}, lejos de ser un atentado contra la libertad religiosa, es un homenaje a esta libertad, a la cual se ofrece la elección de un camino que incluso los no creyentes juzgan noble y exaltante. O, ¿puede ser un crimen contra la libertad ajena proclamar con alegría la Buena Nueva conocida gracias a la misericordia del Señor?{fn-132}. O, ¿por qué únicamente la mentira y el error, la degradación y la pornografía han de tener derecho a ser propuestas y, por desgracia, incluso impuestas con frecuencia por una propaganda destructiva difundida mediante los medios de comunicación social, por la tolerancia legal, por el miedo de los buenos y la audacia de los malos? Este modo respetuoso de proponer la verdad de Cristo y de su reino, más que un derecho es un deber del evangelizador. Y es a la vez un derecho de sus hermanos recibir a través de él, el anuncio de la Buena Nueva de la salvación. Esta salvación viene realizada por Dios en quien El lo desea, y por caminos extraordinarios que sólo El conoce{fn-133}. En realidad, si su Hijo ha venido al mundo ha sido precisamente para revelarnos, mediante su palabra y su vida, los caminos ordinarios de la salvación. Y El nos ha ordenado transmitir a los demás, con su misma autoridad, esta revelación. No sería inútil que cada cristiano y cada evangelizador examinasen en profundidad, a través de la oración, este pensamiento: los hombres podrán salvarse por otros caminos, gracias a la misericordia de Dios, si nosotros no les anunciamos el Evangelio; pero ¿podremos nosotros salvarnos si por negligencia, por miedo, por vergüenza —lo que San Pablo llamaba avergonzarse del Evangelio—{fn-134}, o por ideas falsas omitimos anunciarlo? Porque eso significaría ser infieles a la llamada de Dios que, a través de los ministros del Evangelio, quiere hacer germinar la semilla; y de nosotros depende el que esa semilla se convierta en árbol y produzca fruto.

Conservemos, pues, el fervor espiritual. Conservemos la dulce y confortadora alegría de evangelizar, incluso cuando hay que sembrar entre lágrimas. Hagámoslo —como Juan el Bautista, como Pedro y Pablo, como los otros Apóstoles, como esa multitud de admirables evangelizadores que se han sucedido a lo largo de la historia de la Iglesia— con un ímpetu interior que nadie ni nada sea capaz de extinguir. Sea ésta la mayor alegría de nuestras vidas entregadas. Y ojalá que el mundo actual —que busca a veces con angustia, a veces con esperanza— pueda así recibir la Buena Nueva, no a través de evangelizadores tristes y desalentados, impacientes o ansiosos, sino a través de ministros del Evangelio, cuya vida irradia el fervor de quienes han recibido, ante todo en sí mismos, la alegría de Cristo, y aceptan consagrar su vida a la tarea de anunciar el reino de Dios y de implantar la Iglesia en el mundo.
