[[exodus]]
= Éxodo

[[exodus-1]]
== Capítulo 1

[[exodus-1-1]]
^1^ Estos son los nombres de los israelitas que entraron con Jacob en Egipto, cada uno con su familia:

[[exodus-1-2]]
^2^ Rubén, Simeón, Leví, Judá,

[[exodus-1-3]]
^3^ Isacar, Zabulón, Benjamín,

[[exodus-1-4]]
^4^ Dan, Neftalí, Gad y Aser.

[[exodus-1-5]]
^5^ El número de los descendientes de Jacob era de setenta personas. José estaba ya en Egipto.

[[exodus-1-6]]
^6^ Murió José, y todos sus hermanos, y toda aquella generación;

[[exodus-1-7]]
^7^ pero los israelitas fueron fecundos y se multiplicaron; llegaron a ser muy numerosos y fuertes y llenaron el país.

[[exodus-1-8]]
^8^ Se alzó en Egipto un nuevo rey, que nada sabía de José;

[[exodus-1-9]]
^9^ y que dijo a su pueblo: «Mirad, los israelitas son un pueblo más númeroso y fuerte que nosotros.

[[exodus-1-10]]
^10^ Tomemos precauciones contra él para que no siga multiplicándose, no sea que en caso de guerra se una también él a nuestros enemigos para luchar contra nosotros y salir del país».

[[exodus-1-11]]
^11^ Les impusieron pues, capataces para aplastarlos bajo el peso de duros trabajos; y así edificaron para Faraón las ciudades de depósito: Pitom y Ramsés.

[[exodus-1-12]]
^12^ Pero cuanto más les oprimían, tanto más crecían y se multiplicaban, de modo que los egipcios llegaron a temer a los israelitas.

[[exodus-1-13]]
^13^ Y redujeron a cruel servidumbre a los israelitas,

[[exodus-1-14]]
^14^ les amargaron la vida con rudos trabajos de arcilla y ladrillos, con toda suerte de labores del campo y toda clase de servidumbre que les imponían por crueldad.

[[exodus-1-15]]
^15^ El rey de Egipto dio también orden a las parteras de las hebreas, una de las cuales se llamaba Sifrá, y la otra Puá,

[[exodus-1-16]]
^16^ diciéndoles: «Cuando asistáis a las hebreas, observad bien las dos piedras: si es niño, hacedle morir; si es niña dejadla con vida».

[[exodus-1-17]]
^17^ Pero las parteras temían a Dios, y no hicieron lo que les había mandado el rey de Egipto, sino que dejaban con vida a los niños.

[[exodus-1-18]]
^18^ Llamó el rey de Egipto a las parteras y les dijo: «¿ Por qué habéis hecho esto y dejáis con vida a los niños?»

[[exodus-1-19]]
^19^ Respondieron las parteras a Faraón: «Es que las hebreas no son como las egipcias. Son más robustas, y antes que llegue la partera, ya han dado a luz».

[[exodus-1-20]]
^20^ Y Dios favoreció a las parteras. El pueblo se multiplicó y se hizo muy poderoso.

[[exodus-1-21]]
^21^ Y por haber temido las parteras a Dios, les concedió numerosa prole.

[[exodus-1-22]]
^22^ Entonces Faraón dio a todo su pueblo esta orden: «Todo niño que nazca lo echaréis al Río; pero a las niñas las dejaréis con vida».
[[exodus-2]]
== Capítulo 2

[[exodus-2-1]]
^1^ Un hombre de la casa de Leví fue a tomar por mujer una hija de Leví.

[[exodus-2-2]]
^2^ Concibió la mujer y dio a luz un hijo; y viendo que era hermoso lo tuvo escondido durante tres meses.

[[exodus-2-3]]
^3^ Pero no pudiendo ocultarlo ya por más tiempo, tomó una cestilla de papiro, la calafateó con betún y pez, metió en ella al niño, y la puso entre los juncos, a la orilla del Río.

[[exodus-2-4]]
^4^ La hermana del niño se apostó a lo lejos para ver lo que le pasaba.

[[exodus-2-5]]
^5^ Bajó la hija de Faraón a bañarse en el Río y, mientras sus doncellas se paseaban por la orilla del Río, divisó la cestilla entre los juncos, y envió una criada suya para que la cogiera.

[[exodus-2-6]]
^6^ Al abrirla, vio que era un niño que lloraba. Se compadeció de él y exclamó: «Es uno de los niños hebreos».

[[exodus-2-7]]
^7^ Entonces dijo la hermana a la hija de Faraón: «¿Quieres que yo vaya y llame una nodriza de entre las hebreas para que te críe este niño?»

[[exodus-2-8]]
^8^ «Vete», le contestó la hija de Faraón. Fue, pues, la joven y llamó a la madre del niño.

[[exodus-2-9]]
^9^ Y la hija de Faraón le dijo: «Toma este niño y críamelo que yo te pagaré». Tomó la mujer al niño y lo crió.

[[exodus-2-10]]
^10^ El niño creció, y ella lo llevó entonces a la hija de Faraón, que lo tuvo por hijo, y le llamó Moisés, diciendo: «De las aguas lo he sacado».

[[exodus-2-11]]
^11^ En aquellos días, cuando Moisés ya fue mayor, fue a visitar a sus hermanos, y comprobó sus penosos trabajos; vio también cómo un egipcio golpeaba a un hebreo, a uno de sus hermanos.

[[exodus-2-12]]
^12^ Miró a uno y a otro lado, y no viendo a nadie, mató al egipcio y lo escondió en la arena.

[[exodus-2-13]]
^13^ Salió al día siguiente y vio a dos hebreos que reñían. Y dijo al culpable: «¿Por qué pegas a tu compañero?»

[[exodus-2-14]]
^14^ El respondió: «¿Quién te ha puesto de jefe y juez sobre nosotros? ¿Acaso estás pensando en matarme como mataste al egipcio?» Moisés, lleno de temor, se dijo: «La cosa ciertamente se sabe».

[[exodus-2-15]]
^15^ Supo Faraón lo sucedido y buscaba a Moisés para matarle; pero él huyó de la presencia de Faraón, y se fue a vivir al país de Madián. Se sentó junto a un pozo.

[[exodus-2-16]]
^16^ Tenía un sacerdote de Madián siete hijas, que fueron a sacar agua y llenar los pilones para abrevar las ovejas de su padre.

[[exodus-2-17]]
^17^ Pero vinieron los pastores y las echaron. Entonces, levantándose Moisés, salió en su defensa y les abrevó el rebaño.

[[exodus-2-18]]
^18^ Al volver ellas a donde su padre Reuel, éste les dijo: «Cómo es que venís hoy tan pronto?»

[[exodus-2-19]]
^19^ Respondieron: «Un egipcio nos libró de las manos de los pastores, y además sacó agua para nosotras y abrevó el rebaño».

[[exodus-2-20]]
^20^ Preguntó entonces a sus hijas: «¿Y dónde está? ¿Cómo así habéis dejado a ese hombre? Llamadle para que coma».

[[exodus-2-21]]
^21^ Aceptó Moisés morar con aquel hombre, que dio a Moisés su hija Seforá.

[[exodus-2-22]]
^22^ Esta dio a luz un hijo y llamóle Guersom, pues dijo: «Forastero soy en tierra extraña».

[[exodus-2-23]]
^23^ Durante este largo período murió el rey de Egipto; los israelitas, gimiendo bajo la servidumbre, clamaron, y su clamor, que brotaba del fondo de su esclavitud, subió a Dios.

[[exodus-2-24]]
^24^ Oyó Dios sus gemidos, y acordóse Dios de su alianza con Abraham, Isaac y Jacob.

[[exodus-2-25]]
^25^ Y miró Dios a los hijos de Israel y conoció...
[[exodus-3]]
== Capítulo 3

[[exodus-3-1]]
^1^ Moisés era pastor del rebaño de Jetró su suegro, sacerdote de Madián. Una vez llevó las ovejas más allá del desierto; y llegó hasta Horeb, la montaña de Dios.

[[exodus-3-2]]
^2^ El ángel de Yahveh se le apareció en forma de llama de fuego, en medio de una zarza. Vio que la zarza estaba ardiendo, pero que la zarza no se consumía.

[[exodus-3-3]]
^3^ Dijo, pues, Moisés: «Voy a acercarme para ver este extraño caso: por qué no se consume la zarza».

[[exodus-3-4]]
^4^ Cuando vio Yahveh que Moisés se acercaba para mirar, le llamó de en medio de la zarza, diciendo: «¡Moisés, Moisés!» El respondió: «Heme aquí».

[[exodus-3-5]]
^5^ Le dijo: «No te acerques aquí; quita las sandalias de tus pies, porque el lugar en que estás es tierra sagrada».

[[exodus-3-6]]
^6^ Y añadió: «Yo soy el Dios de tu padre, el Dios de Abraham, el Dios de Isaac y el Dios de Jacob». Moisés se cubrió el rostro, porque temía ver a Dios.

[[exodus-3-7]]
^7^ Dijo Yahveh: «Bien vista tengo la aflicción de mi pueblo en Egipto, y he escuchado su clamor en presencia de sus opresores; pues ya conozco sus sufrimientos.

[[exodus-3-8]]
^8^ He bajado para librarle de la mano de los egipcios y para subirle de esta tierra a una tierra buena y espaciosa; a una tierra que mana leche y miel, al país de los cananeos, de los hititas, de los amorreos, de los perizitas, de los jivitas y de los jebuseos.

[[exodus-3-9]]
^9^ Así pues, el clamor de los israelitas ha llegado hasta mí y he visto además la opresión con que los egipcios los oprimen.

[[exodus-3-10]]
^10^ Ahora, pues, ve; yo te envío a Faraón, para que saques a mi pueblo, los israelitas, de Egipto».

[[exodus-3-11]]
^11^ Dijo Moisés a Dios: ¿Quién soy yo para ir a Faraón y sacar de Egipto a los israelitas?»

[[exodus-3-12]]
^12^ Respondió: «Yo estaré contigo y esta será para ti la señal de que yo te envío: Cuando hayas sacado al pueblo de Egipto daréis culto a Dios en este monte».

[[exodus-3-13]]
^13^ Contestó Moisés a Dios: «Si voy a los israelitas y les digo: “El Dios de vuestros padres me ha enviado a vosotros”; cuando me pregunten: “¿Cuál es su nombre?”, ¿qué les responderé?»

[[exodus-3-14]]
^14^ Dijo Dios a Moisés: «Yo soy el que soy». Y añadió: «Así dirás a los israelitas: “Yo soy” me ha enviado a vosotros».

[[exodus-3-15]]
^15^ Siguió Dios diciendo a Moisés: «Así dirás a los israelitas: Yahveh, el Dios de vuestros padres, el Dios de Abraham, el Dios de Isaac y el Dios de Jacob, me ha enviado a vosotros. Este es mi nombre para siempre, por él seré invocado de generación en generación».

[[exodus-3-16]]
^16^ «Ve, y reúne a los ancianos de Israel, y diles: “Yahveh, el Dios de vuestros padres, el Dios de Abraham, de Isaac y de Jacob, se me apareció y me dijo: Yo os he visitado y he visto lo que os han hecho en Egipto.

[[exodus-3-17]]
^17^ Y he decidido sacaros de la tribulación de Egipto al país de los cananeos, los hititas, los amorreos, perizitas, jivitas y jebuseos, a una tierra que mana leche y miel.”

[[exodus-3-18]]
^18^ Ellos escucharán tu voz, y tú irás con los ancianos de Israel donde el rey de Egipto; y le diréis: “Yahveh, el Dios de los hebreos, se nos ha aparecido. Permite, pues, que vayamos camino de tres días al desierto, para ofrecer sacrificios a Yahveh, nuestro Dios.”

[[exodus-3-19]]
^19^ Ya sé que el rey de Egipto no os dejará ir sino forzado por mano poderosa.

[[exodus-3-20]]
^20^ Pero yo extenderé mi mano y heriré a Egipto con toda suerte de prodigios que obraré en medio de ellos y después os dejará salir».

[[exodus-3-21]]
^21^ «Yo haré que este pueblo halle gracia a los ojos de los egipcios, de modo que cuando partáis, no saldréis con las manos vacías,

[[exodus-3-22]]
^22^ sino que cada mujer pedirá a su vecina y a la que mora en su casa objetos de plata, objetos de oro y vestidos, que pondréis a vuestros hijos y a vuestras hijas, y así despojaréis a los egipcios».
[[exodus-4]]
== Capítulo 4

[[exodus-4-1]]
^1^ Respondió Moisés y dijo: «No van a creerme, ni escucharán mi voz; pues dirán: “No se te ha aparecido Yahveh.”»

[[exodus-4-2]]
^2^ Díjole Yahveh: «¿Qué tienes en tu mano?» «Un cayado», respondió él.

[[exodus-4-3]]
^3^ Yahveh le dijo: «Echalo a tierra». Lo echó a tierra y se convirtió en serpiente; y Moisés huyó de ella.

[[exodus-4-4]]
^4^ Dijo Yahveh a Moisés: «Extiende tu mano y agárrala por la cola». Extendió la mano, la agarró, y volvió a ser cayado en su mano...

[[exodus-4-5]]
^5^ «Para que crean que se te ha aparecido Yahveh, el Dios de sus padres, el Dios de Abraham, el Dios de Isaac y el Dios de Jacob».

[[exodus-4-6]]
^6^ Y añadió Yahveh: «Mete tu mano en el pecho». Metió él la mano en su pecho y cuando la volvió a sacar estaba cubierta de lepra, blanca como la nieve.

[[exodus-4-7]]
^7^ Y le dijo: «Vuelve a meter la mano en tu pecho». La volvió a meter y, cuando la sacó de nuevo, estaba ya como el resto de su carne.

[[exodus-4-8]]
^8^ «Así pues, si no te creen ni escuchan la voz por la primera señal, creerán por la segunda.

[[exodus-4-9]]
^9^ Y si no creen tampoco por estas dos señales y no escuchan tu voz, tomarás agua del Río y la derramarás en el suelo; y el agua que saques del Río se convertirá en sangre sobre el suelo».

[[exodus-4-10]]
^10^ Dijo Moisés a Yahveh: «¡Por favor, Señor! Yo no he sido nunca hombre de palabra fácil, ni aun después de haber hablado tú con tu siervo; sino que soy torpe de boca y de lengua».

[[exodus-4-11]]
^11^ Le respondió Yahveh: «¿Quién ha dado al hombre la boca? ¿? Quién hace al mudo y al sordo, al que ve y al ciego? ¿No soy yo, Yahveh?

[[exodus-4-12]]
^12^ Así pues, vete, que yo estaré en tu boca y te enseñaré lo que debes decir».

[[exodus-4-13]]
^13^ El replicó: «Por favor, envía a quien quieras».

[[exodus-4-14]]
^14^ Entonces se encendió la ira de Yahveh contra Moisés, y le dijo: «¿No tienes a tu hermano Aarón el levita? Sé que él habla bien; he aquí que justamente ahora sale a tu encuentro, y al verte se alegrará su corazón.

[[exodus-4-15]]
^15^ Tu le hablarás y pondrás las palabras en su boca; yo estaré en tu boca y en la suya, y os enseñaré lo que habéis de hacer.

[[exodus-4-16]]
^16^ El hablará por ti al pueblo, él será tu boca y tú serás su dios.

[[exodus-4-17]]
^17^ Toma también en tu mano este cayado, porque con él has de hacer las señales».

[[exodus-4-18]]
^18^ Moisés volvió y regresó a casa de Jetró, su suegro, y le dijo: «Con tu permiso, me vuelvo a ver a mis hermanos de Egipto para saber si viven todavía». Dijo Jetró a Moisés: «Vete en paz».

[[exodus-4-19]]
^19^ Yahveh dijo a Moisés en Madián: «Anda, vuelve a Egipto ; pues han muerto todos los que buscaban tu muerte».

[[exodus-4-20]]
^20^ Tomó, pues, Moisés a su mujer y a su hijo y, montándolos sobre un asno, volvió a la tierra de Egipto. Tomó también Moisés el cayado de Dios en su mano.

[[exodus-4-21]]
^21^ Y dijo Yahveh a Moisés: «Cuando vuelvas a Egipto, harás delante de Faraón todos los prodigios que yo he puesto en tu mano; yo, por mi parte, endureceré su corazón, y no dejará salir al pueblo.

[[exodus-4-22]]
^22^ Y dirás a Faraón: Así dice Yahveh: Israel es mi hijo, mi primogénito.

[[exodus-4-23]]
^23^ Yo te he dicho: “Deja ir a mi hijo para que me dé culto,” pero como tú no quieres dejarle partir, mira que yo voy a matar a tu hijo, a tu primogénito».

[[exodus-4-24]]
^24^ Y sucedió que en el camino le salió al encuentro Yahveh en el lugar donde pasaba la noche y quiso darle muerte.

[[exodus-4-25]]
^25^ Tomó entonces Seforá un cuchillo de pedernal y, cortando el prepucio de su hijo, tocó los pies de Moisés, diciendo: «Tú eres para mí esposo de sangre».

[[exodus-4-26]]
^26^ Y Yahveh le soltó; ella había dicho: «esposo de sangre», por la circuncisión.

[[exodus-4-27]]
^27^ Dijo Yahveh a Aarón: «Vete al desierto al encuentro de Moisés». Partió, pues, y le encontró en el monte de Dios y le besó.

[[exodus-4-28]]
^28^ Moisés contó a Aaron todas las palabras que Yahveh le había encomendado y todas las señales que le había mandado hacer.

[[exodus-4-29]]
^29^ Fueron, pues, Moisés y Aarón y reunieron a todos los ancianos de los israelitas.

[[exodus-4-30]]
^30^ Aarón refirió todas las palabras que Yahveh había dicho a Moisés, el cual hizo las señales delante del pueblo.

[[exodus-4-31]]
^31^ El pueblo creyó, y al oír que Yahveh había visitado a los israelitas y había visto su aflicción, se postraron y adoraron.
[[exodus-5]]
== Capítulo 5

[[exodus-5-1]]
^1^ Después se presentaron Moisés y Aarón a Faraón y le dijeron: «Así dice Yahveh, el Dios de Israel: Deja salir a mi pueblo para que me celebre una fiesta en el desierto».

[[exodus-5-2]]
^2^ Respondió Faraón: «¿Quién es Yahveh para que yo escuche su voz y deje salir a Israel? No conozco a Yahveh y no dejaré salir a Israel».

[[exodus-5-3]]
^3^ Ellos dijeron: «El Dios de los hebreos se nos ha aparecido; permite, pues, que vayamos camino de tres días al desierto para ofrecer sacrificios a Yahveh, nuestro Dios, no sea que nos castigue con peste o espada».

[[exodus-5-4]]
^4^ El rey de Egipto les replicó: «¿Por qué vosotros, Moisés y Aarón, apartáis al pueblo de sus trabajos? Idos a vuestra tarea».

[[exodus-5-5]]
^5^ Y añadió Faraón: «Ahora que el pueblo de esa región es numeroso ¿queréis interrumpir sus trabajos?»

[[exodus-5-6]]
^6^ Aquel mismo día dio Faraón esta orden a los capataces del pueblo y a los escribas:

[[exodus-5-7]]
^7^ «Ya no daréis como antes paja al pueblo para hacer ladrillos; que vayan ellos mismos a buscársela.

[[exodus-5-8]]
^8^ Pero que hagan la misma cantidad de ladrillos que hacían antes, sin rebajarla; pues son unos perezosos. Y por eso claman diciendo: Vamos a ofrecer sacrificios a nuestro Dios.

[[exodus-5-9]]
^9^ Que se aumente el trabajo de estos hombres para que estén ocupados en él y no den oídos a palabras mentirosas.

[[exodus-5-10]]
^10^ Salieron los capataces del pueblo diciendo: «Esto dice Faraón: No os daré ya más paja;

[[exodus-5-11]]
^11^ id vosotros mismos a buscárosla donde la podáis hallar. Pero vuestra tarea no se disminuirá en nada».

[[exodus-5-12]]
^12^ Esparcióse, pues, el pueblo por el país de Egipto en busca de rastrojo para emplearlo como paja.

[[exodus-5-13]]
^13^ Los capataces por su lado los apremiaban, diciendo: «Terminad la tarea que os ha sido fijada para cada día, como cuando había paja».

[[exodus-5-14]]
^14^ A los escribas de los israelitas, que los capataces de Faraón habían puesto al frente de aquéllos, se les castigó, diciéndoles: «¿Por qué no habéis hecho, ni ayer ni hoy, la misma cantidad de ladrillos que antes?»

[[exodus-5-15]]
^15^ Los escribas de los israelitas fueron a quejarse a Faraón, diciendo: «¿Por qué tratas así a tus siervos?

[[exodus-5-16]]
^16^ No se da paja a tus siervos y sin embargo nos dicen: “Haced ladrillos.” Y he aquí que tus siervos son castigados..».

[[exodus-5-17]]
^17^ El respondió: «Haraganes sois, grandes haraganes; por eso decís: “Vamos a ofrecer sacrificios a Yahveh.”

[[exodus-5-18]]
^18^ Pues, id a trabajar; no se os dará paja, y habéis de entregar la cantidad de ladrillos señalada».

[[exodus-5-19]]
^19^ Los escribas de los israelitas se vieron en grande aprieto, pues les ordenaron: «No disminuiréis vuestra producción diaria de ladrillos».

[[exodus-5-20]]
^20^ Encontráronse, pues, con Moisés y Aarón, que les estaban esperando a la salida de su entrevista con Faraón,

[[exodus-5-21]]
^21^ y les dijeron: Que Yahveh os examine y que él os juzgue por habernos hecho odiosos a Faraón y a sus siervos y haber puesto la espada en sus manos para matarnos».

[[exodus-5-22]]
^22^ Volvióse entonces Moisés a Yahveh y dijo: «Señor, ¿por qué maltratas a este pueblo? ¿por qué me has enviado?

[[exodus-5-23]]
^23^ Pues desde que fui a Faraón para hablarle en tu nombre está maltratando a este pueblo, y tú no haces nada por librarle».
[[exodus-6]]
== Capítulo 6

[[exodus-6-1]]
^1^ Respondió Yahveh a Moisés: «Ahora verás lo que voy a hacer con Faraón; porque bajo fuerte mano tendrá que dejarles partir y bajo fuerte mano él mismo los expulsará de su territorio».

[[exodus-6-2]]
^2^ Habló Dios a Moisés y le dijo: «Yo soy Yahveh.

[[exodus-6-3]]
^3^ Me aparecí a Abraham, a Isaac y a Jacob como El Sadday; pero mi nombre de Yahveh no se lo di a conocer.

[[exodus-6-4]]
^4^ También con ellos establecí mi alianza, para darles la tierra de Canaán, la tierra en que peregrinaron y en la que moraron como forasteros.

[[exodus-6-5]]
^5^ Y ahora, al oír el gemido de los israelitas, reducidos a esclavitud por los egipcios, he recordado mi alianza.

[[exodus-6-6]]
^6^ Por tanto, di a los hijos de Israel: Yo soy Yahveh; Yo os libertaré de los duros trabajos de los egipcios, os libraré de su esclavitud y os salvaré con brazo tenso y castigos grandes.

[[exodus-6-7]]
^7^ Yo os haré mi pueblo, y seré vuestro Dios; y sabréis que yo soy Yahveh, vuestro Dios, que os sacaré de la esclavitud de Egipto.

[[exodus-6-8]]
^8^ Yo os introduciré en la tierra que he jurado dar a Abraham, a Isaac y a Jacob, y os la daré en herencia. Yo, Yahveh».

[[exodus-6-9]]
^9^ Moisés dijo esto a los israelitas; pero ellos no escucharon a Moisés, consumidos por la dura servidumbre.

[[exodus-6-10]]
^10^ Entonces Yahveh habló a Moisés diciendo:

[[exodus-6-11]]
^11^ «Ve a hablar con Faraón, rey de Egipto, para que deje salir a los israelitas fuera de su territorio».

[[exodus-6-12]]
^12^ Respondió Moisés ante Yahveh: «Si los israelitas no escuchan: ¿cómo me va a escuchar Faraón, a mí que soy torpe de palabra?»

[[exodus-6-13]]
^13^ Pero Yahveh habló a Moisés y a Aarón, y les dio órdenes para los israelitas y para Faraón, rey de Egipto, a fin de sacar del país de Egipto a los israelitas.

[[exodus-6-14]]
^14^ Estos son los jefes de sus casas paternas: Hijos de Rubén, primogénito de Israel: Henoc, Pallú, Jesrón y Karmí, éstas son las familias de Rubén.

[[exodus-6-15]]
^15^ Hijos de Simeón: Yemuel, Yamín, Ohad, Yakín, Sójar y Saúl, hijo de la cananea; éstas son las familias de Simeón.

[[exodus-6-16]]
^16^ Y éstos son los nombres de los hijos de Leví por sus linajes: Guerson, Quehat, Merarí. Los años de la vida de Leví fueron 137.

[[exodus-6-17]]
^17^ Hijos de Guerson: Libní y Simei según sus familias.

[[exodus-6-18]]
^18^ Hijos de Quehat: Amram, Yishar, Hebrón y Uzziel. Los años de la vida de Quehat fueron 133 años.

[[exodus-6-19]]
^19^ Hijos de Merarí: Majlí y Musí. Estas son las familias de los levitas, por sus linajes.

[[exodus-6-20]]
^20^ Amram tomó por mujer a Yokébed, su tía, de la cual nacieron Aarón y Moisés. Y los años de la vida de Amram fueron 137.

[[exodus-6-21]]
^21^ Hijos de Yishar: Coré, Néfeg y Zikrí.

[[exodus-6-22]]
^22^ Hijos de Uzziel: Missael, Elsafán y Sitrí.

[[exodus-6-23]]
^23^ Aarón tomó por mujer a Isabel, hija de Amminadab, hermana de Najsón; de la cual le nacieron Nadab, Abihú, Eleazar e Itamar.

[[exodus-6-24]]
^24^ Hijos de Coré: Assir, Elcaná y Abiasaf. Estas son la familias de los coreítas.

[[exodus-6-25]]
^25^ Eleazar, hijo de Aarón, tomó por mujer a una de las hijas de Putiel y de ella nació Pinjás. Estos son los jefes de las casas paternas de los levitas, según sus familias.

[[exodus-6-26]]
^26^ Estos son, pues, aquel Aarón y aquel Moisés a quienes dijo Yahveh: «Sacad a los israelitas de la tierra de Egipto en orden de campaña».

[[exodus-6-27]]
^27^ Estos son los que hablaron a Faraón, rey de Egipto, para sacar de Egipto a los israelitas. Estos son Moisés y Aarón.

[[exodus-6-28]]
^28^ El día en que Yahveh habló a Moisés en el país de Egipto,

[[exodus-6-29]]
^29^ le dijo: «Yo soy Yahveh; di a Faraón, rey de Egipto, cuanto yo te diga».

[[exodus-6-30]]
^30^ Moisés respondió ante Yahveh: «Siendo yo torpe de palabra, ¿cómo me va a escuchar Faraón?»
[[exodus-7]]
== Capítulo 7

[[exodus-7-1]]
^1^ Dijo Yahveh a Moisés: «Mira que te he constituido como dios para Faraón y Aarón, tu hermano, será tu profeta;

[[exodus-7-2]]
^2^ tú le dirás cuanto yo te mande; y Aarón, tu hermano, se lo dirá a Faraón, para que deje salir de su país a los israelitas.

[[exodus-7-3]]
^3^ Yo, por mi parte, endureceré el corazón de Faraón, y multiplicaré mis señales y mis prodigios en el país de Egipto.

[[exodus-7-4]]
^4^ Faraón no os escuchará, pero yo pondré mi mano sobre Egipto y sacaré de la tierra de Egipto a mi ejército, mi pueblo, los israelitas, a fuerza de duros castigos.

[[exodus-7-5]]
^5^ Y los egipcios reconocerán que yo soy Yahveh, cuando extienda mi mano sobre Egipto y saque de en medio de ellos a los hijos de Israel».

[[exodus-7-6]]
^6^ Moisés y Aarón hicieron lo que les mandó Yahveh.

[[exodus-7-7]]
^7^ Tenía Moisés ochenta años, y Aarón 83 cuando hablaron a Faraón.

[[exodus-7-8]]
^8^ Habló Yahveh a Moisés y Aarón, y dijo:

[[exodus-7-9]]
^9^ «Cuando Faraón os diga: Haced algún prodigio, dirás a Aarón: “Toma tu cayado y échalo delante de Faraón, y que se convierta en serpiente.”»

[[exodus-7-10]]
^10^ Presentáronse, pues, Moisés y Aarón a Faraón, e hicieron lo que Yahveh había ordenado: Aarón echó su cayado delante de Faraón y de sus servidores, y se convirtió en serpiente.

[[exodus-7-11]]
^11^ También Faraón llamó a los sabios y a los hechiceros, y también ellos, los sabios egipcios, hicieron con sus encantamientos las mismas cosas.

[[exodus-7-12]]
^12^ Echó cada cual su vara, y se trocaron en serpientes; pero el cayado de Aarón devoró sus varas.

[[exodus-7-13]]
^13^ Sin embargo el corazón de Faraón se endureció, y no les escuchó, conforme había predicho Yahveh.

[[exodus-7-14]]
^14^ Entonces dijo Yahveh a Moisés: «El corazón de Faraón es obstinado; se niega a dejar salir al pueblo.

[[exodus-7-15]]
^15^ Preséntate a Faraón por la mañana, cuando vaya a la ribera. Le saldrás al encuentro a la orilla del Río, llevando en tu mano el cayado que se convirtió en serpiente.

[[exodus-7-16]]
^16^ Y le dirás: Yahveh, el Dios de los hebreos, me ha enviado a ti para decirte: “Deja partir a mi pueblo, para que me den culto en el desierto”; pero hasta el presente no has escuchado.

[[exodus-7-17]]
^17^ Así dice Yahveh: En esto conoceras que yo soy Yahveh: Mira que voy a golpear con el cayado que tengo en la mano las aguas del Río, y se convertirán en sangre.

[[exodus-7-18]]
^18^ Los peces del Río morirán, y el Río quedará apestado de modo que los egipcios no podrán ya beber agua del Río».

[[exodus-7-19]]
^19^ Yahveh dijo a Moisés: «Di a Aarón: Toma tu cayado, y extiende tu mano sobre las aguas de Egipto, sobre sus canales, sobre sus ríos, sobre sus lagunas y sobre todos sus depósitos de agua. Se convertirán en sangre; y habrá sangre en toda la tierra de Egipto, hasta en los árboles y la piedras».

[[exodus-7-20]]
^20^ Moisés y Aarón hicieron lo que Yahveh les había mandado: alzó el cayado y golpeó las aguas que hay en el Rió en presencia de Faraón y de sus servidores, y todas las aguas del Rió se convirtieron en sangre.

[[exodus-7-21]]
^21^ Los peces del Río murieron, el Río quedó apestado de modo que los egipcios nos pudieron beber el agua del Río; hubo sangre en todo el país de Egipto.

[[exodus-7-22]]
^22^ Pero lo mismo hicieron con sus encantamientos los magos de Egipto; y el corazón de Faraón se endureció y no les escuchó, como había dicho Yahveh.

[[exodus-7-23]]
^23^ Se volvió Faraón y entró en su casa sin hacer caso de ello.

[[exodus-7-24]]
^24^ Y todos los egipcios tuvieron que cavar en los alrededores del Río en busca de agua potable, porque no podían beber las aguas del Río.

[[exodus-7-25]]
^25^ Pasaron siete días desde que Yahveh hirió el Río.

[[exodus-7-26]]
^26^ Y dijo Yahveh a Moisés: «Preséntate a Faraón y dile: Así dice Yahveh: “Deja salir a mi pueblo para que me dé culto.”

[[exodus-7-27]]
^27^ Si te niegas a dejarle partir infestaré de ranas todo tu país.

[[exodus-7-28]]
^28^ El Río bullirá de ranas, que subirán y entrarán en tu casa, en tu dormitorio y en tu lecho, en las casas de tus servidores y en tu pueblo, en tus hornos y en tus artesas.

[[exodus-7-29]]
^29^ Subirán la ranas sobre ti, sobre tu pueblo, y sobre tus siervos».
[[exodus-8]]
== Capítulo 8

[[exodus-8-1]]
^1^ Dijo Yahveh a Moisés: «Di a Aarón: Extiende tu mano con tu cayado sobre los canales, sobre los ríos y sobre las lagunas, y haz que suban las ranas sobre la tierra de Egipto».

[[exodus-8-2]]
^2^ Aarón extendió su mano sobre las aguas de Egipto; subieron la ranas y cubrieron la tierra de Egipto.

[[exodus-8-3]]
^3^ Pero los magos hicieron lo mismo con sus encantamientos, e hicieron subir las ranas sobre la tierra de Egipto.

[[exodus-8-4]]
^4^ Faraón llamó a Moisés y a Aarón y dijo: «Pedid a Yahveh que aparte las ranas de mí y de mi pueblo, y yo dejaré salir al pueblo para que ofrezca sacrificios a Yahveh».

[[exodus-8-5]]
^5^ Respondió Moisés a Faraón: «Dígnate indicarme cuándo he de rogar por ti, por tus siervos y por tu pueblo, para que se alejen las ranas de ti y de tus casas, y queden solamente en el Río».

[[exodus-8-6]]
^6^ «Mañana», contestó el. Replicó Moisés: «Será conforme a tu palabra, para que sepas que no hay como Yahveh, nuestro Dios.

[[exodus-8-7]]
^7^ Las ranas se apartarán de ti, de tus casas, de tus siervos y de tu pueblo, y quedarán sólo en el Río».

[[exodus-8-8]]
^8^ Salieron Moisés y Aarón de la presencia de Faraón, invocó Moisés a Yahveh acerca de las ranas que afligían a Faraón,

[[exodus-8-9]]
^9^ y Yahveh hizo lo que Moisés pedía: murieron las ranas de las casas, de los patios y de los campos.

[[exodus-8-10]]
^10^ Las juntaron en montones y el país apestaba.

[[exodus-8-11]]
^11^ Pero Faraón viendo que tenía este respiro, endureció su corazón, y no les escuchó como había predicho Yahveh.

[[exodus-8-12]]
^12^ Dijo Yahveh a Moisés: «Di a Aarón: extiende tu cayado y golpea el polvo de la tierra que se convertirá en mosquitos sobre todo el país de Egipto».

[[exodus-8-13]]
^13^ Así lo hicieron: Aarón extendió su mano con el cayado y golpeó el polvo de la tierra; y hubo mosquitos sobre los hombres y sobre los ganados. Todo el polvo de la tierra se convirtió en mosquitos sobre todo el país de Egipto.

[[exodus-8-14]]
^14^ Los magos intentaron con sus encantamientos hacer salir mosquitos, pero no pudieron. Hubo, pues, mosquitos sobre hombres y ganados.

[[exodus-8-15]]
^15^ Dijeron los magos a Faraón: «¡es el dedo de Dios!» Pero el corazón de Faraón se endureció, y no les escuchó, como había dicho Yahveh.

[[exodus-8-16]]
^16^ Yahveh dijo a Moisés: «Levántate muy de mañana, preséntate a Faraón cuando vaya a la ribera, y dile: Así dice Yahveh: “Deja salir a mi pueblo, para que me dé culto.”

[[exodus-8-17]]
^17^ Si no dejas salir a mi pueblo, mira que voy a enviar tábanos contra ti, contra tus siervos, tu pueblo y tus casas, de manera que las casas de los egipcios y hasta el suelo sobre el cual están se llenarán de tábanos.

[[exodus-8-18]]
^18^ Pero exceptuaré ese día la región de Gosen, donde está mi pueblo, para que no haya allí tábanos, a fin de que sepas que yo soy Yahveh en medio de la tierra;

[[exodus-8-19]]
^19^ haré distinción entre mi pueblo y el tuyo. Este prodigio sucederá mañana».

[[exodus-8-20]]
^20^ Así lo hizo Yahveh, y un enorme enjambre de tábanos vino sobre la casa de Faraón y la casas de sus siervos; y toda la tierra de Egipto; la tierra fue devastada por los tábanos.

[[exodus-8-21]]
^21^ Entonces llamó Faraón a Moisés y a Aarón y les dijo: «Id y ofreced sacrificios a vuestro Dios en este país».

[[exodus-8-22]]
^22^ Moisés respondió: «No conviene que se haga así, porque el sacrificio que ofrecemos a Yahveh, nuestro Dios, es abominación para los egipcios. ¿No nos apedrearían los egipcios si ofreciéramos ante sus ojos un sacrificio que para ellos es abominable?

[[exodus-8-23]]
^23^ Iremos tres jornadas de camino por el desierto, y allí ofreceremos sacrificios a Yahveh, nuestro Dios, según él nos ordena».

[[exodus-8-24]]
^24^ Contestó Faraón: «Os dejaré ir, para que ofrezcáis en el desierto sacrificios a Yahveh, vuestro Dios, con tal que no vayáis demasiado lejos. Rogad por mí».

[[exodus-8-25]]
^25^ Moisés respondió: «En cuanto salga rogaré a Yahveh, y mañana los tábanos se alejarán de Faraón, de sus siervos y de su pueblo; pero que no nos siga engañando Faraón, impidiendo que el pueblo vaya a ofrecer sacrificios a Yahveh».

[[exodus-8-26]]
^26^ Salió, pues, Moisés de la presencia de Faraón, y rogó a Yahveh.

[[exodus-8-27]]
^27^ Hizo Yahveh lo que Moisés pedía, y alejó los tábanos del Faraón, de sus siervos y de su pueblo, sin quedar ni uno.

[[exodus-8-28]]
^28^ Pero también esta vez endureció Faraón su corazón y no dejó salir al pueblo.
[[exodus-9]]
== Capítulo 9

[[exodus-9-1]]
^1^ Yahveh dijo a Moisés: «Preséntate a Faraón y dile: Así dice Yahveh, el Dios de los hebreos: “Deja salir a mi pueblo para que me den culto.”

[[exodus-9-2]]
^2^ Si te niegas a dejarles salir y los sigues reteniendo,

[[exodus-9-3]]
^3^ mira que la mano de Yahveh caerá sobre tus ganados del campo, sobre los caballos, sobre los asnos, sobre los camellos, sobre la vacadas y sobre las ovejas; habrá una grandísima peste.

[[exodus-9-4]]
^4^ Pero Yahveh hará distinción entre el ganado de Israel y el ganado de los egipcios, de modo que nada perecerá de lo perteneciente a Israel».

[[exodus-9-5]]
^5^ Y Yahveh fijó el plazo, diciendo: «Mañana hará esto Yahveh en el país».

[[exodus-9-6]]
^6^ Al día siguiente cumplió Yahveh su palabra y murió todo el ganado de los egipcios; mas del ganado de los israelitas no murió ni una sola cabeza.

[[exodus-9-7]]
^7^ Faraón mandó hacer averiguaciones, y se vio que del ganado de Israel no había muerto ni un solo animal. Sin embargo, se endureció el corazón de Faraón y no dejó salir al pueblo.

[[exodus-9-8]]
^8^ Dijo Yahveh a Moisés y a Aarón: «Tomad dos grandes puñados de hollín de horno, y que Moisés lo lance hacia el cielo, en presencia de Faraón;

[[exodus-9-9]]
^9^ se convertirá en polvo fino sobre todo el territorio de Egipto, y formará erupciones pustulosas, en hombres y ganados, por toda la tierra de Egipto».

[[exodus-9-10]]
^10^ Tomaron, pues, hollín de horno y presentándose ante Faraón, lo lanzó Moisés hacia el cielo, y hubo erupciones pustulosas en hombres y ganados.

[[exodus-9-11]]
^11^ Ni los magos pudieron permanecer delante de Moisés a causa de las erupciones; pues los magos tenían las mismas erupciones que todos los egipcios.

[[exodus-9-12]]
^12^ Pero Yahveh endureció el corazón de Faraón, que nos les escuchó, según Yahveh había dicho a Moisés.

[[exodus-9-13]]
^13^ Dijo Yahveh a Moisés: «Levántate de mañana, preséntate a Faraón y dile: Así dice Yahveh, el Dios de los hebreos: “Deja salir a mi pueblo para que me den culto.”

[[exodus-9-14]]
^14^ Porque esta vez voy a enviar todas mis plagas sobre ti, sobre tus siervos y sobre tu pueblo para que sepas que no hay como yo en toda la tierra.

[[exodus-9-15]]
^15^ Si yo hubiera extendido mi mano y te hubiera herido a ti y a tu pueblo con peste, ya habrías desaparecido de la tierra;

[[exodus-9-16]]
^16^ pero te he dejado con vida, para hacerte ver mi poder, y para que sea celebrado mi nombre sobre toda la tierra.

[[exodus-9-17]]
^17^ Tú te opones todavía a mi pueblo, para no dejarle salir.

[[exodus-9-18]]
^18^ Pues mira que mañana, a esta hora, haré llover una granizada tan fuerte, como no hubo otra en Egipto desde el día en que fue fundado hasta el presente.

[[exodus-9-19]]
^19^ Ahora, pues, manda poner a salvo tu ganado y cuanto tienes en del campo; porque el granizo descargará sobre todos los hombres y animales que se hallan en el campo, y cuantos no se hayan recogido bajo techumbre perecerán».

[[exodus-9-20]]
^20^ Aquéllos de los siervos de Faraón que temieron la palabra de Yahveh pusieron al abrigo a sus siervos y su ganado;

[[exodus-9-21]]
^21^ mas los que no hicieron caso de la palabra de Yahveh, dejaron en el campo a sus siervos y su ganado.

[[exodus-9-22]]
^22^ Dijo Yahveh a Moisés: «Extiende tu mano hacia el cielo, y que caiga granizo en toda la tierra de Egipto, sobre los hombres, sobre los ganados y sobre todas las hierbas del campo que hay en la tierra de Egipto».

[[exodus-9-23]]
^23^ Extendió Moisés su cayado hacia el cielo, y Yahveh envió truenos y granizo; cayeron rayos sobre la tierra, y Yahveh hizo llover granizo sobre el país de Egipto.

[[exodus-9-24]]
^24^ El granizo y los rayos mezclados con el granizo cayeron con fuerza tan extraordinaria que nunca hubo semejante en toda la tierra de Egipto desde que comenzó a ser nación.

[[exodus-9-25]]
^25^ El granizo hirió cuanto había en el campo en todo el país de Egipto, desde los hombres hasta los ganados. El granizo machacó también toda la hierba del campo, y quebró todos los árboles del campo.

[[exodus-9-26]]
^26^ Tan sólo en la región de Gosen, donde habitaban los israelitas, no hubo granizo.

[[exodus-9-27]]
^27^ Faraón hizo llamar a Moisés y a Aarón y les dijo: «Ahora sí, he pecado; Yahveh es el justo, y yo y mi pueblo somos inicuos.

[[exodus-9-28]]
^28^ Rogad a Yahveh que cesen ya los truenos y el granizo; y os dejaré salir. No tendréis que quedaros más tiempo aquí».

[[exodus-9-29]]
^29^ Moisés le respondió: «Cuando salga de la ciudad extenderé mis manos hacia Yahveh, cesarán los truenos, y no habrá más granizo, para que sepas que la tierra es de Yahveh.

[[exodus-9-30]]
^30^ Pero bien sé que ni tú ni tus siervos teméis todavía a Yahveh, Dios».

[[exodus-9-31]]
^31^ Fueron destrozados el lino y la cebada, pues la cebada estaba ya en espiga, y el lino en flor.

[[exodus-9-32]]
^32^ El trigo y la espelta no fueron destrozados por ser tardíos.

[[exodus-9-33]]
^33^ Dejando a Faraón, salió Moisés de la ciudad, extendió las manos hacia Yahveh, y cesaron los truenos y granizos, y no cayó más lluvia sobre la tierra.

[[exodus-9-34]]
^34^ Cuando Faraón vio que había cesado la lluvia, el granizo y los truenos, volvió a pecar, endureciendo su corazón, tanto él como sus siervos.

[[exodus-9-35]]
^35^ Endurecióse, pues, el corazón de Faraón y no dejó salir a los israelitas como Yahveh había dicho por boca de Moisés.
[[exodus-10]]
== Capítulo 10

[[exodus-10-1]]
^1^ Dijo Yahveh a Moisés: «Ve a Faraón, porque he endurecido su corazón y el corazón de sus siervos, para obrar estas señales mías en medio de ellos;

[[exodus-10-2]]
^2^ y para que puedas contar a tu hijo, y al hijo de tu hijo, cómo me divertí con Egipto y las señales que realicé entre ellos, y sepáis que yo soy Yahveh».

[[exodus-10-3]]
^3^ Fueron, pues, Moisés y Aarón donde Faraón y le dijeron: «Así dice Yahveh, el Dios de los hebreos: ¿Hasta cuándo te resistirás a humillarte ante mí? Deja salir a mi pueblo para que me dé culto.

[[exodus-10-4]]
^4^ Si te niegas a dejar salir a mi pueblo, mira que mañana traeré langostas sobre tu territorio;

[[exodus-10-5]]
^5^ y cubrirán la superficie del país, de suerte que ni podrá verse el suelo. Devorarán lo que os quedó de la granizada, y comerán todos los árboles que os crecen en el campo.

[[exodus-10-6]]
^6^ Llenarán tus casas, las casas de todos los egipcios, como nunca vieron tus padres, ni los padres de tus padres, desde el día en que existieron sobre la tierra hasta el día de hoy». Y retirándose salió de la presencia de Faraón.

[[exodus-10-7]]
^7^ Dijeron entonces a Faraón sus siervos: «¿Hasta cuándo ha de ser este hombre causa de nuestra ruina? Deja salir a esa gente y que den culto a Yahveh, su Dios. ¿Te darás cuenta a tiempo de que Egipto se pierde?»

[[exodus-10-8]]
^8^ Hicieron, pues, volver a Moisés y a Aarón a la presencia de Faraón; el cual les dijo: «Id a dar culto a Yahveh, vuestro Dios. ¿Quiénes van a ir?»

[[exodus-10-9]]
^9^ Respondió Moisés: «Saldremos con nuestros niños y nuestros ancianos, con nuestros hijos y nuestras hijas, con nuestras ovejas y nuestras vacadas; porque es nuestra fiesta de Yahveh».

[[exodus-10-10]]
^10^ Contestóles: «¡Así esté Yahveh con vosotros como voy a dejaros salir a vosotros con vuestros pequeños! Ved cómo a la vista están vuestras malas intenciones.

[[exodus-10-11]]
^11^ No será así; salid si queréis los varones solos y dad culto a Yahveh, pues eso es lo que buscabais». Y fueron echados de la presencia de Faraón.

[[exodus-10-12]]
^12^ Yahveh dijo a Moisés: «Extiende tu mano sobre la tierra de Egipto para que venga la langosta; que suba sobre el país de Egipto y coma toda la hierba del país, todo lo que dejó el granizo».

[[exodus-10-13]]
^13^ Moisés extendió su cayado sobre la tierra de Egipto; y Yahveh hizo soplar el solano sobre el país todo aquel día y toda la noche. Y cuando amaneció, el solano había traído la langosta.

[[exodus-10-14]]
^14^ La langosta invadió todo el país de Egipto, y se posó en todo el territorio egipcio, en cantidad tan grande como nunca había habido antes tal plaga de langosta ni la habría después.

[[exodus-10-15]]
^15^ Cubrieron toda la superficie del país hasta oscurecer la tierra; devoraron toda la hierba del país y todos los frutos de los árboles que el granizo había dejado; no quedó nada verde ni en los árboles ni en las hierbas del campo en toda la tierra de Egipto.

[[exodus-10-16]]
^16^ Entonces Faraón llamó a toda prisa a Moisés y a Aaron, y dijo: «He pecado contra Yahveh, vuestro Dios, y contra vosotros.

[[exodus-10-17]]
^17^ Ahora, pues, perdonad por favor mi pecado, siquiera por esta vez; rogad a Yahveh, vuestro Dios, que aparte de mí al menos esta mortandad».

[[exodus-10-18]]
^18^ Salió Moisés de la presencia de Faraón y rogó a Yahveh.

[[exodus-10-19]]
^19^ Yahveh hizo que soplara con gran violencia un viento del mar que se llevó la langosta y la echó al mar de Suf. No quedó ni una langosta en todo el territorio de Egipto.

[[exodus-10-20]]
^20^ Pero Yahveh endureció el corazón de Faraón, que no dejó salir a los israelitas.

[[exodus-10-21]]
^21^ Yahveh dijo a Moisés: «Extiende tu mano hacia el cielo, y haya sobre la tierra de Egipto tinieblas que puedan palparse».

[[exodus-10-22]]
^22^ Extendió, pues, Moisés su mano hacia el cielo, y hubo por tres días densas tinieblas en todo el país de Egipto.

[[exodus-10-23]]
^23^ No se veían unos a otros, y nadie se levantó de su sitio por espacio de tres días, mientras que todos los israelitas tenían luz en sus moradas.

[[exodus-10-24]]
^24^ Llamó Faraón a Moisés y dijo: «Id y dad culto a Yahveh; que se queden solamente vuestras ovejas y vuestras vacadas. También vuestros pequeños podrán ir con vosotros».

[[exodus-10-25]]
^25^ Respondió Moisés: «Nos tienes que conceder también sacrificios y holocaustos, para que los ofrendemos a Yahveh, nuestro Dios.

[[exodus-10-26]]
^26^ También nuestro ganado ha de venir con nosotros. No quedará ni una pezuña; porque de ellos hemos de tomar para dar culto a Yahveh, nuestro Dios. Y no sabemos todavía qué hemos de ofrecer a Yahveh hasta que lleguemos allá».

[[exodus-10-27]]
^27^ Yahveh endureció el corazón de Faraón, que no quiso dejarles salir.

[[exodus-10-28]]
^28^ Y dijo Faraón a Moisés: «¡Retírate de mi presencia! ¡Guárdate de volver a ver mi rostro, pues el día en que veas mi rostro, morirás!»

[[exodus-10-29]]
^29^ Respondió Moisés: «Tú lo has dicho: no volveré a ver tu rostro».
[[exodus-11]]
== Capítulo 11

[[exodus-11-1]]
^1^ Dijo Yahveh a Moisés: «Todavía traeré una plaga más sobre Faraón y sobre Egipto; tras de lo cual os dejará marchar de aquí y cuando, por fin, os deje salir del país, él mismo os expulsará de aquí.

[[exodus-11-2]]
^2^ Habla, pues, al pueblo y que cada hombre pida a su vecino, y cada mujer a su vecina, objetos de plata y objetos de oro».

[[exodus-11-3]]
^3^ Yahveh hizo que el pueblo se ganase el favor de los egipcios. Además, Moisés era un gran personaje en la tierra de Egipto, tanto a los ojos de los servidores de Faraón como a los ojos del pueblo.

[[exodus-11-4]]
^4^ Moisés dijo: «Así dice Yahveh: hacia media noche pasaré yo a través de Egipto;

[[exodus-11-5]]
^5^ y morirá en el país de Egipto todo primogénito, desde el primogénito de Faraón que se sienta en su trono hasta el primogénito de la esclava encargada de moler, así como todo primer nacido del ganado.

[[exodus-11-6]]
^6^ Y se elevará en todo el país de Egipto un alarido tan grande como nunca lo hubo, ni lo habrá.

[[exodus-11-7]]
^7^ Pero entre los israelitas ni siquiera un perro ladrará ni contra hombre ni contra bestia; para que sepáis cómo Yahveh hace distinción entre Egipto e Israel.

[[exodus-11-8]]
^8^ Entonces vendrán a mí todos estos siervos tuyos y se postrarán delante de mí, diciendo: Sal, tú y todo el pueblo que te sigue. Y entonces, saldré». Y, ardiendo en cólera, salió de la presencia de Faraón.

[[exodus-11-9]]
^9^ Y dijo Yahveh a Moisés: «no os escuchará Faraón, para que así pueda yo multiplicar mis prodigios en la tierra de Egipto».

[[exodus-11-10]]
^10^ Moisés y Aarón obraron todos estos prodigios ante Faraón; pero Yahveh endureció el corazón de Faraón, que no dejó salir de su país a los israelitas.
[[exodus-12]]
== Capítulo 12

[[exodus-12-1]]
^1^ Dijo Yahveh a Moisés y Aarón en el país de Egipto:

[[exodus-12-2]]
^2^ «Este mes será para vosatros el comienzo de los meses; será el primero de los meses del año.

[[exodus-12-3]]
^3^ Hablad a toda la comunidad de Israel y decid: El día diez de este mes tomará cada uno para sí una res de ganado menor por familia, una res de ganado menor por casa.

[[exodus-12-4]]
^4^ Y si la familia fuese demasiado reducida para una res de ganado menor, traerá al vecino más cercano a su casa, según el número de personas y conforme a lo que cada cual pueda comer.

[[exodus-12-5]]
^5^ El animal será sin defecto, macho, de un año. Lo escogeréis entre los corderos o los cabritos.

[[exodus-12-6]]
^6^ Lo guardaréis hasta el día catorce de este mes; y toda la asamblea de la comunidad de los israelitas lo inmolará entre dos luces.

[[exodus-12-7]]
^7^ Luego tomarán la sangre y untarán las dos jambas y el dintel de las casas donde lo coman.

[[exodus-12-8]]
^8^ En aquella misma noche comerán la carne. La comerán asada al fuego, con ázimos y con hierbas amargas.

[[exodus-12-9]]
^9^ Nada de él comeréis crudo ni cocido, sino asado, con su cabeza, sus patas y sus entrañas.

[[exodus-12-10]]
^10^ Y no dejaréis nada de él para la mañana; lo que sobre al amanecer lo quemaréis.

[[exodus-12-11]]
^11^ Así lo habéis de comer: ceñidas vuestras cinturas, calzados vuestros pies, y el bastón en vuestra mano; y lo comeréis de prisa. Es Pascua de Yahveh.

[[exodus-12-12]]
^12^ Yo pasaré esta noche por la tierra de Egipto y heriré a todos los primogénitos del país de Egipto, desde los hombres hasta los ganados, y me tomaré justicia de todos los dioses de Egipto. Yo, Yahveh.

[[exodus-12-13]]
^13^ La sangre será vuestra señal en las casas donde moráis. Cuando yo vea la sangre pasaré de largo ante vosotros, y no habrá entre vosotros plaga exterminadora cuando yo hiera el país de Egipto.

[[exodus-12-14]]
^14^ Este será un día memorable para vosotros, y lo celebraréis como fiesta en honor de Yahveh de generación en generación. Decretaréis que sea fiesta para siempre».

[[exodus-12-15]]
^15^ «Durante siete días comeréis ázimos; ya desde el primer día quitaréis de vuestras casas la levadura. Todo el que desde el día primero hasta el día séptimo coma pan fermentado, ese tal será exterminado de en medio de Israel.

[[exodus-12-16]]
^16^ El primer día tendréis reunión sagrada; también el día séptimo os reuniréis en reunión sagrada. Ningún trabajo se hará en esos días, salvo la comida para cada uno. Esto es lo único que podréis hacer.

[[exodus-12-17]]
^17^ Guardad la fiesta de los Azimos, porque en ese mismo día saqué yo vuestros ejércitos de la tierra de Egipto. Guardad este día de generación en generación como decreto perpetuo.

[[exodus-12-18]]
^18^ Comeréis ázimos en el mes primero, desde la tarde del día catorce del mes hasta la tarde del día veintiuno.

[[exodus-12-19]]
^19^ No habrá levadura en vuestras casas por espacio de siete días; todo aquel que coma algo fermentado, sea forastero o natural del país, será exterminado de la comunidad de Israel.

[[exodus-12-20]]
^20^ No comeréis nada fermentado; en todo lugar donde habitéis, comeréis ázimos».

[[exodus-12-21]]
^21^ Llamó Moisés a todos los ancianos de Israel y les dijo: «Id en busca de reses menores para vuestras familias e inmolad la pascua.

[[exodus-12-22]]
^22^ Tomaréis un manojo de hisopo, lo mojaréis en la sangre que está en la vasija y untaréis el dintel y las dos jambas con la sangre de la vasija; y ninguno de vosotros saldrá de la puerta de su casa hasta la mañana.

[[exodus-12-23]]
^23^ Yahveh pasará y herirá a los egipcios, pero al ver la sangre en el dintel y en las dos jambas, Yahveh pasará de largo por aquella puerta y no permitirá que el Exterminador entre en vuestras casas para herir.

[[exodus-12-24]]
^24^ Guardad este mandato como decreto perpetuo para vosotros y vuestros hijos.

[[exodus-12-25]]
^25^ También guardaréis este rito cuando entréis en la tierra que os dará Yahveh, según su promesa.

[[exodus-12-26]]
^26^ Y cuando os pregunten vuestros hijos: “¿Qué significa para vosotros este rito?”,

[[exodus-12-27]]
^27^ responderéis: “Este es el sacrificio de la Pascua de Yahveh, que pasó de largo por las casas de los israelitas en Egipto cuando hirió a los egipcios y salvó nuestras casas.”» Entonces el pueblo se postró para adorar.

[[exodus-12-28]]
^28^ Fueron los israelitas e hicieron lo que había mandado Yahveh a Moisés y a Aarón; así lo hicieron.

[[exodus-12-29]]
^29^ Y sucedió que, a media noche, Yahveh hirió en el país de Egipto a todos los primogénitos, desde el primogénito de Faraón, que se sienta sobre su trono, hasta el primogénito del preso en la cárcel, y a todo primer nacido del ganado.

[[exodus-12-30]]
^30^ Levantóse Faraón aquella noche, con todos sus servidores y todos los egipcios; y hubo grande alarido en Egipto, porque no había casa donde no hubiese un muerto.

[[exodus-12-31]]
^31^ Llamó Faraón a Moisés y a Aarón, durante la noche, y les dijo: «Levantaos y salid de en medio de mi pueblo, vosotros y los israelitas, e id a dar culto a Yahveh, como habéis dicho.

[[exodus-12-32]]
^32^ Tomad también vuestros rebaños y vuestras vacadas, como dijisteis. Marchaos y bendecidme también a mí».

[[exodus-12-33]]
^33^ Los egipcios por su parte instaban al pueblo para acelerar su salida del país, pues decían. «Vamos a morir todos».

[[exodus-12-34]]
^34^ Tomó, pues, el pueblo la masa, antes que fermentara y, envolviendo en los mantos las artesas de la harina, se las cargaron a hombros.

[[exodus-12-35]]
^35^ Los israelitas hicieron lo que les dijo Moisés y pidieron a los egipcios objetos de plata, objetos de oro y vestidos.

[[exodus-12-36]]
^36^ Yahveh hizo que el pueblo se ganara el favor de los egipcios, los cuales se los prestaron. Así despojaron a los egipcios.

[[exodus-12-37]]
^37^ Los israelitas partieron de Ramsés hacia Sukkot, unos 600.000 hombres de a pie, sin contar los niños.

[[exodus-12-38]]
^38^ Salió también con ellos una muchedumbre abigarrada y grandes rebaños de ovejas y vacas.

[[exodus-12-39]]
^39^ De la masa que habían sacado de Egipto cocieron tortas ázimas, porque no había fermentado todavía; pues al ser echados de Egipto no pudieron tomar víveres ni provisiones para el camino.

[[exodus-12-40]]
^40^ Los israelitas estuvieron en Egipto 430 años.

[[exodus-12-41]]
^41^ El mismo día que se cumplían los 430 años, salieron de la tierra de Egipto todos los ejércitos de Yahveh.

[[exodus-12-42]]
^42^ Noche de guardia fue ésta para Yahveh, para sacarlos de la tierra de Egipto. Esta misma noche será la noche de guardia en honor de Yahveh para todos los israelitas, por todas sus generaciones.

[[exodus-12-43]]
^43^ Dijo Yahveh a Moisés y a Aarón: «Estas son las normas sobre la Pascua: no comerá de ella ningún extranjero.

[[exodus-12-44]]
^44^ Todo siervo, comprado por dinero, a quien hayas circuncidado, podrá comerla.

[[exodus-12-45]]
^45^ Pero el residente y el jornalero no la comerán.

[[exodus-12-46]]
^46^ Se ha de comer dentro de casa; no sacaréis fuera de casa nada de carne, ni le quebraréis ningún hueso.

[[exodus-12-47]]
^47^ Toda la comunidad de Israel la celebrará.

[[exodus-12-48]]
^48^ Si un forastero que habita contigo quiere celebrar la Pascua de Yahveh, que se circunciden todos sus varones, y entonces podrá acercarse para celebrarla, pues será como los nativos; pero ningún incircunciso podrá comerla.

[[exodus-12-49]]
^49^ Una misma ley habrá para el nativo y para el forastero que habita en medio de vosotros».

[[exodus-12-50]]
^50^ Así lo hicieron todos los israelitas. Tal como había mandado Yahveh a Moisés y a Aarón, así lo hicieron.

[[exodus-12-51]]
^51^ Y en aquel mismo día sacó Yahveh del país de Egipto a los israelitas en orden de campaña.
[[exodus-13]]
== Capítulo 13

[[exodus-13-1]]
^1^ Habló Yahveh a Moisés, diciendo:

[[exodus-13-2]]
^2^ «Conságrame todo primogénito, todo lo que abre el seno materno entre los israelitas. Ya sean hombres o animales, míos son todos».

[[exodus-13-3]]
^3^ Dijo, pues, Moisés al pueblo: «Acordaos de este día en que salisteis de Egipto, de la casa de servidumbre, pues Yahveh os ha sacado de aquí con mano fuerte; y no comáis pan fermentado.

[[exodus-13-4]]
^4^ Salís hoy, en el mes de Abib.

[[exodus-13-5]]
^5^ Así, cuando Yahveh te haya introducido en la tierra de los cananeos, de los hititas, de los amorreos, de los jivitas y de los jebuseos, que juró a tus padres que te daría, tierra que mana leche y miel, celebrarás ese rito en este mes.

[[exodus-13-6]]
^6^ Siete días comerás ázimos y el día séptimo será fiesta de Yahveh.

[[exodus-13-7]]
^7^ Se comerán ázimos durante siete días, y no se verá pan fermentado en tu casa, ni levadura en tu casa, en todo tu territorio.

[[exodus-13-8]]
^8^ En aquel día harás saber a tu hijo: “Esto es con motivo de lo que hizo conmigo Yahveh cuando salí de Egipto.”

[[exodus-13-9]]
^9^ Y esto te servirá como señal en tu mano, y como recordatorio ante tus ojos, para que la ley de Yahveh esté en tu boca; porque con mano fuerte te sacó Yahveh de Egipto.

[[exodus-13-10]]
^10^ Guardarás este precepto, año por año, en el tiempo debido».

[[exodus-13-11]]
^11^ Cuando Yahveh te haya introducido en la tierra del cananeo, como lo tiene jurado a ti y a tus padres, y te la haya dado,

[[exodus-13-12]]
^12^ consagrarás a Yahveh todo lo que abre el seno materno. Todo primer nacido de tus ganados, si son machos, pertenecen también a Yahveh.

[[exodus-13-13]]
^13^ Todo primer nacido del asno lo rescatarás con un cordero; y si no lo rescatas lo desnucarás. Rescatarás también todo primogénito de entre tus hijos.

[[exodus-13-14]]
^14^ Y cuando el día de mañana te pregunte tu hijo: “¿Qué significa esto?”, le dirás: “Con mano fuerte nos sacó Yahveh de Egipto, de la casa de servidumbre.”

[[exodus-13-15]]
^15^ Como Faraón se obstinó en no dejarnos salir, Yahveh mató a todos los primogénitos en el país de Egipto, desde el primogénito del hombre hasta el primogénito del ganado. Por eso sacrifico a Yahveh todo macho que abre el seno materno, y rescato todo primogénito de mis hijos.

[[exodus-13-16]]
^16^ Esto será como señal en tu mano y como insignia entre tus ojos; porque con mano fuerte nos sacó Yahveh de Egipto».

[[exodus-13-17]]
^17^ Cuando Faraón dejó salir al pueblo, Dios no los llevó por el camino de la tierra de los filisteos, aunque era más corto; pues se dijo Dios: «No sea que, al verse atacado, se arrepienta el pueblo y se vuelva a Egipto».

[[exodus-13-18]]
^18^ Hizo Dios dar un rodeo al pueblo por el camino del desierto del mar de Suf. Los israelitas salieron bien equipados del país de Egipto.

[[exodus-13-19]]
^19^ Moisés tomó consigo los huesos de José, pues éste había hecho jurar solemnemente a los israelitas, diciendo: «Ciertamente Dios os visitará, y entonces llevaos de aquí mis huesos con vosotros.”

[[exodus-13-20]]
^20^ Partieron de Sukkot y acamparon en Etam, al borde del desierto.

[[exodus-13-21]]
^21^ Yahveh iba al frente de ellos, de día en columna de nube para guiarlos por el camino, y de noche en columna de fuego para alumbrarlos, de modo que pudiesen marchar de día y de noche.

[[exodus-13-22]]
^22^ No se apartó del pueblo ni la columna de nube por el día, ni la columna de fuego por la noche.
[[exodus-14]]
== Capítulo 14

[[exodus-14-1]]
^1^ Habló Yahveh a Moisés, diciendo:

[[exodus-14-2]]
^2^ «Di a los israelitas que se vuelvan y acampen frente a Pi Hajirot, entre Migdol y el mar, enfrente de Baal Sefón. Frente a ese lugar acamparéis, junto al mar.

[[exodus-14-3]]
^3^ Faraón dirá de los israelitas: “Andan errantes en el país, y el desierto les cierra el paso.”

[[exodus-14-4]]
^4^ Yo endureceré el corazón de Faraón, y os perseguirá; pero yo manifestaré mi gloria a costa de Faraón y de todo su ejército, y sabrán los egipcios que yo soy Yahveh». Así lo hicieron.

[[exodus-14-5]]
^5^ Cuando anunciaron al rey de Egipto que había huido el pueblo, se mudó el corazón de Faraón y de sus servidores respecto del pueblo, y dijeron: «¿Qué es lo que hemos hecho dejando que Israel salga de nuestro servicio?»

[[exodus-14-6]]
^6^ Faraón hizo enganchar su carro y llevó consigo sus tropas.

[[exodus-14-7]]
^7^ Tomó seiscientos carros escogidos y todos los carros de Egipto, montados por sus combatientes.

[[exodus-14-8]]
^8^ Endureció Yahveh el corazón de Faraón rey de Egipto, el cual persiguió a los israelitas, pero los israelitas salieron con la mano alzada.

[[exodus-14-9]]
^9^ Los egipcios los persiguieron: todos los caballos, los carros de Faraón, con la gente de los carros y su ejército; y les dieron alcance mientras acampaban junto al mar, cerca de Pi Hajirot, frente a Baal Sefón.

[[exodus-14-10]]
^10^ Al acercarse Faraón, los israelitas alzaron sus ojos, y viendo que los egipcios marchaban tras ellos, temieron mucho los israelitas y clamaron a Yahveh.

[[exodus-14-11]]
^11^ Y dijeron a Moisés: «¿Acaso no había sepulturas en Egipto para que nos hayas traído a morir en el desierto? ¿Qué has hecho con nosotros sacándonos de Egipto?

[[exodus-14-12]]
^12^ ¿No te dijimos claramente en Egipto: Déjanos en paz, queremos servir a los egipcios? Porque mejor nos es servir a los egipcios que morir en el desierto».

[[exodus-14-13]]
^13^ Contestó Moisés al pueblo: «No temáis; estad firmes, y veréis la salvación que Yahveh os otorgará en este día, pues los egipcios que ahora veis, no los volveréis a ver nunca jamás.

[[exodus-14-14]]
^14^ Yahveh peleará por vosotros, que vosotros no tendréis que preocuparos».

[[exodus-14-15]]
^15^ Dijo Yahveh a Moisés: «¿Por qué sigues clamando a mí? Di a los israelitas que se pongan en marcha.

[[exodus-14-16]]
^16^ Y tú, alza tu cayado, extiende tu mano sobre el mar y divídelo, para que los israelitas entren en medio del mar a pie enjuto.

[[exodus-14-17]]
^17^ Que yo voy a endurecer el corazón de los egipcios para que los persigan, y me cubriré de gloria a costa de Faraón y de todo su ejército, de sus carros y de los guerreros de los carros.

[[exodus-14-18]]
^18^ Sabrán los egipcios que yo soy Yahveh, cuando me haya cubierto de gloria a costa de Faraón, de sus carros y de sus jinetes.

[[exodus-14-19]]
^19^ Se puso en marcha el Angel de Yahveh que iba al frente del ejército de Israel, y pasó a retaguardia. También la columna de nube de delante se desplazó de allí y se colocó detrás,

[[exodus-14-20]]
^20^ poniéndose entre el campamento de los egipcios y el campamento de los israelitas. La nube era tenebrosa y transcurrió la noche sin que pudieran trabar contacto unos con otros en toda la noche.

[[exodus-14-21]]
^21^ Moisés extendió su mano sobre el mar, y Yahveh hizo soplar durante toda la noche un fuerte viento del Este que secó el mar, y se dividieron las aguas.

[[exodus-14-22]]
^22^ Los israelitas entraron en medio del mar a pie enjuto, mientras que las aguas formaban muralla a derecha e izquierda.

[[exodus-14-23]]
^23^ Los egipcios se lanzaron en su persecución, entrando tras ellos, en medio del mar, todos los caballos de Faraón, y los carros con sus guerreros.

[[exodus-14-24]]
^24^ Llegada la vigilia matutina, miró Yahveh desde la columna de fuego y humo hacia el ejército de los egipcios, y sembró la confusión en el ejército egipcio.

[[exodus-14-25]]
^25^ Trastornó la ruedas de sus carros, que no podían avanzar sino con gran dificultad. Y exclamaron los egipcios: «Huyamos ante Israel, porque Yahveh pelea por ellos contra los egipcios».

[[exodus-14-26]]
^26^ Yahveh dijo a Moisés: Extiende tu mano sobre el mar, y las aguas volverán sobre los egipcios, sobre sus carros y sobre los guerreros de los carros».

[[exodus-14-27]]
^27^ Extendió Moisés su mano sobre el mar, y al rayar el alba volvió el mar a su lecho; de modo que los egipcios, al querer huir, se vieron frente a las aguas. Así precipitó Yahveh a los egipcios en medio del mar,

[[exodus-14-28]]
^28^ pues al retroceder las aguas cubrieron los carros y a su gente, a todo el ejército de Faraón, que había entrado en el mar para perseguirlos; no escapó ni uno siquiera.

[[exodus-14-29]]
^29^ Mas los israelitas pasaron a pie enjuto por en medio del mar, mientras las aguas hacían muralla a derecha e izquierda.

[[exodus-14-30]]
^30^ Aquel día salvó Yahveh a Israel del poder de los egipcios; e Israel vio a los egipcios muertos a orillas del mar.

[[exodus-14-31]]
^31^ Y viendo Israel la mano fuerte que Yahveh había desplegado contra los egipcios, temió el pueblo a Yahveh, y creyeron en Yahveh y en Moisés, su siervo.
[[exodus-15]]
== Capítulo 15

[[exodus-15-1]]
^1^ Entonces Moisés y los israelitas cantaron este cántico a Yahveh. Dijeron: «Canto a Yahveh pues se cubrió de gloria arrojando en el mar caballo y carro.

[[exodus-15-2]]
^2^ Mi fortaleza y mi canción es Yah. El es mi salvación. El, mi Dios, yo le glorifico, el Dios de mi padre, a quien exalto.

[[exodus-15-3]]
^3^ ¡Un guerrero Yahveh, Yahveh es su nombre!

[[exodus-15-4]]
^4^ Los carros de Faraón y sus soldados precipitó en el mar. La flor de sus guerreros tragó el mar de Suf;

[[exodus-15-5]]
^5^ cubriólos el abismo, hasta el fondo cayeron como piedra.

[[exodus-15-6]]
^6^ Tu diestra, Yahveh,relumbra por su fuerza; tu diestra, Yahveh, aplasta al enemigo.

[[exodus-15-7]]
^7^ En tu gloria inmensa derribas tus contrarios, desatas tu furor y los devora como paja.

[[exodus-15-8]]
^8^ Al soplo de tu ira se apiñaron las aguas, se irguieron las olas como un dique, los abismos cuajaron en el corazón del mar.

[[exodus-15-9]]
^9^ Dijo el enemigo: «Marcharé a su alcance, repartiré despojos, se saciará mi alma, sacaré mi espada y los aniquilará mi mano».

[[exodus-15-10]]
^10^ Mandaste tu soplo, cubriólos el mar; se hundieron como plomo en las temibles aguas.

[[exodus-15-11]]
^11^ ¿Quién como tú, Yahveh, entre los dioses? ¿Quién como tú, glorioso en santidad, terrible en prodigios, autor de maravillas?

[[exodus-15-12]]
^12^ Tendiste tu diestra y los tragó la tierra.

[[exodus-15-13]]
^13^ Guiaste en tu bondad al pueblo rescatado. Tu poder los condujo a tu santa morada.

[[exodus-15-14]]
^14^ Oyéronlo los pueblos, se turbaron, dolor como de parto en Filistea.

[[exodus-15-15]]
^15^ Los príncipes de Edom se estremecieron, se angustiaron los jefes de Moab y todas las gentes de Canaán temblaron.

[[exodus-15-16]]
^16^ Pavor y espanto cayó sobre ellos. La fuerza de tu brazo los hizo enmudecer como una piedra, hasta que pasó tu pueblo, oh Yahveh, hasta pasar el pueblo que compraste.

[[exodus-15-17]]
^17^ Tú le llevas y le plantas en el monte de tu herencia, hasta el lugar que tú te has preparado para tu sede, ¡oh Yahveh! Al santuario, Adonay, que tus manos prepararon.

[[exodus-15-18]]
^18^ ¡Yahveh reinará por siempre jamás!»

[[exodus-15-19]]
^19^ Porque cuando los caballos de Faraón y los carros con sus guerreros entraron en el mar, Yahveh hizo que las aguas del mar volvieran sobre ellos, mientras que los israelitas pasaron a pie enjuto por medio del mar.

[[exodus-15-20]]
^20^ María, la profetisa, hermana de Aarón tomó en sus manos un tímpano y todas la mujeres la seguían con tímpanos y danzando en coro.

[[exodus-15-21]]
^21^ Y María les entonaba el estribillo: «Cantad a Yahveh pues se cubrió de gloria. arrojando en el mar caballo y carro».

[[exodus-15-22]]
^22^ Moisés hizo partir a los israelitas del mar de Suf y se dirigieron hacia el desierto de Sur: caminaron tres días por el desierto sin encontrar agua.

[[exodus-15-23]]
^23^ Luego llegaron a Mará, porque era amarga. Por eso se llama aquel lugar Mará.

[[exodus-15-24]]
^24^ El pueblo murmuró contra Moisés, diciendo: «¿Qué vamos a beber?»

[[exodus-15-25]]
^25^ Entonces Moisés invocó a Yahveh, y Yahveh le mostró un madero que Moisés echó al agua, y el agua se volvió dulce. Allí dio a Israel decretos y normas, y allí le puso a prueba.

[[exodus-15-26]]
^26^ Y dijo: «Si de veras escuchas la voz de Yahveh, tu Dios, y haces lo que es recto a sus ojos, dando oídos a sus mandatos y guardando todos sus preceptos, no traeré sobre ti ninguna de las plagas que envié sobre los egipcios; porque yo soy Yahveh, el que te sana».

[[exodus-15-27]]
^27^ Después llegaron a Elim, donde hay doce fuentes de agua y setenta palmeras, y acamparon allí junto a las aguas.
[[exodus-16]]
== Capítulo 16

[[exodus-16-1]]
^1^ Partieron de Elim, y toda la comunidad de los israelitas llegó al desierto de Sin, que está entre Elim y el Sinaí, el día quince del segundo mes después de su salida del país de Egipto.

[[exodus-16-2]]
^2^ Toda la comunidad de los israelitas empezó a murmurar contra Moisés y Aarón en el desierto.

[[exodus-16-3]]
^3^ Los israelitas les decían: «¡Ojalá hubiéramos muerto a manos de Yahveh en la tierra de Egipto cuando nos sentábamos junto a las ollas de carne, cuando comíamos pan hasta hartarnos! Vosotros nos habéis traído a este desierto para matar de hambre a toda esta asamblea».

[[exodus-16-4]]
^4^ Yahveh dijo a Moisés: «Mira, yo haré llover sobre vosotros pan del cielo; el pueblo saldrá a recoger cada día la porción diaria; así le pondré a prueba para ver si anda o no según mi ley.

[[exodus-16-5]]
^5^ Mas el día sexto, cuando preparen lo que hayan traído, la ración será doble que la de los demás días».

[[exodus-16-6]]
^6^ Dijeron, pues, Moisés y Aarón a toda la comunidad de los israelitas: «Esta tarde sabréis que es Yahveh quien os ha sacado del país de Egipto;

[[exodus-16-7]]
^7^ y por la mañana veréis la gloria de Yahveh. Porque ha oído vuestras murmuraciones contra Yahveh; pues ¿qué somos nosotros para que murmuréis contra nosotros?»

[[exodus-16-8]]
^8^ Y añadió Moisés: «Yahveh os dará esta tarde carne para comer, y por la mañana pan en abundancia; porque Yahveh ha oído vuestras murmuraciones contra él; pues ¿qué somos nosotros? No van contra nosotros vuestras murmuraciones, sino contra Yahveh».

[[exodus-16-9]]
^9^ Dijo entonces Moisés a Aarón: «Ordena a toda la comunidad de los israelitas: Acercaos a Yahveh, pues él ha oído vuestras murmuraciones».

[[exodus-16-10]]
^10^ Aún estaba hablando Aarón a toda la comunidad de los israelitas, cuando ellos miraron hacia el desierto, y he aquí que la gloria de Yahveh se apareció en forma de nube.

[[exodus-16-11]]
^11^ Y Yahveh habló a Moisés, diciendo:

[[exodus-16-12]]
^12^ «He oído las murmuraciones de los israelitas. Diles: Al atardecer comeréis carne y por la mañana os hartaréis de pan; y así sabréis que yo soy Yahveh, vuestro Dios».

[[exodus-16-13]]
^13^ Aquella misma tarde vinieron las codornices y cubrieron el campamento; y por la mañana había una capa de rocío en torno al campamento.

[[exodus-16-14]]
^14^ Y al evaporarse la capa de rocío apareció sobre el suelo del desierto una cosa menuda, como granos, parecida a la escarcha de la tierra.

[[exodus-16-15]]
^15^ Cuando los israelitas la vieron, se decían unos a otros: «¿Qué es esto?» Pues no sabían lo que era. Moisés les dijo: «Este es el pan que Yahveh os da por alimento.

[[exodus-16-16]]
^16^ He aquí lo que manda Yahveh: Que cada uno recoja cuanto necesite para comer, un gomor por cabeza, según el número de los miembros de vuestra familia; cada uno recogerá para la gente de su tienda».

[[exodus-16-17]]
^17^ Así lo hicieron los israelitas; unos recogieron mucho y otros poco.

[[exodus-16-18]]
^18^ Pero cuando lo midieron con el gomor, ni los que recogieron poco tenían de menos. Cada uno había recogido lo que necesitaba para su sustento.

[[exodus-16-19]]
^19^ Moisés les dijo: «Que nadie guarde nada para el día siguiente».

[[exodus-16-20]]
^20^ Pero no obedecieron a Moisés, y algunos guardaron algo para el día siguiente; pero se llenó de gusanos y se pudrió; y Moisés se irritó contra ellos.

[[exodus-16-21]]
^21^ Lo recogían por las mañanas, cada cual según lo que necesitaba; y luego, con el calor del sol, se derretía.

[[exodus-16-22]]
^22^ El día sexto recogieron doble racíon, dos gomor por persona. Todos los jefes de la comunidad fueron a decírselo a Moisés;

[[exodus-16-23]]
^23^ él les respondió: «Esto es lo que manda Yahveh: Mañana es sábado, día de descanso consagrado a Yahveh. Coced lo que se deba cocer, hervid lo que se tenga que hervir; y lo sobrante, guardadlo como reserva para mañana».

[[exodus-16-24]]
^24^ Ellos lo guardaron para el día siguiente, según la orden de Moisés; y no se pudrió, ni se agusanó.

[[exodus-16-25]]
^25^ Dijo entonces Moisés: «Hoy comeréis esto, porque es sábado de Yahveh; y en tal día no hallaréis nada en el campo.

[[exodus-16-26]]
^26^ Seis días podéis recogerlo, pero el día séptimo, que es sábado, no habrá nada».

[[exodus-16-27]]
^27^ A pesar de todo, salieron algunos del pueblo a recogerlo el séptimo día, pero no encontraron nada.

[[exodus-16-28]]
^28^ Yahveh dijo a Moisés: «¿Hasta cuándo os negaréis a guardar mi mandatos y mis leyes?

[[exodus-16-29]]
^29^ Mirad que Yahveh os ha puesto el sábado; por eso el día sexto os da ración para dos días. Quédese cada uno en su sitio, y que nadie se mueva de su lugar el día séptimo».

[[exodus-16-30]]
^30^ Y el día séptimo descansó el pueblo.

[[exodus-16-31]]
^31^ La casa de Israel lo llamó maná. Era como semilla de cilantro, blanco, y con sabor a torta de miel.

[[exodus-16-32]]
^32^ Dijo Moisés: «Esto manda Yahveh: Llenad un gomor de maná, y conservadlo, para vuestros descendientes, para que vean el pan con que os alimenté en el desierto cuando os saqué del país de Egipto».

[[exodus-16-33]]
^33^ Dijo, pues, Moisés a Aarón: «Toma una vasija, pon en ella un gomor lleno de maná, y colócalo ante Yahveh, a fin de conservarlo para vuestros descendientes».

[[exodus-16-34]]
^34^ Tal como Yahveh se lo mandó a Moisés, Aarón lo puso ante el Testimonio para conservarlo.

[[exodus-16-35]]
^35^ Los israelitas comieron el maná por espacio de cuarenta años, hasta que llegaron a tierra habitada. Lo estuvieron comiendo hasta que llegaron a los confines del país de Canaán.

[[exodus-16-36]]
^36^ El gomor es la décima parte de la medida.
[[exodus-17]]
== Capítulo 17

[[exodus-17-1]]
^1^ Toda la comunidad de los israelitas partió del desierto de Sin, a la orden de Yahveh, para continuar sus jornadas; y acamparon en Refidim, donde el pueblo no encontró agua para beber.

[[exodus-17-2]]
^2^ El pueblo entonces se querelló contra Moisés, diciendo: «Danos agua para beber». Respondióles Moisés: «¿Por qué os querelláis conmigo? ¿Por qué tentáis a Yahveh?»

[[exodus-17-3]]
^3^ Pero el pueblo, torturado por la sed, siguió murmurando contra Moisés: «¿Nos has hecho salir de Egipto para hacerme morir de sed, a mí, a mis hijos y a mis ganados?»

[[exodus-17-4]]
^4^ Clamó Moisés a Yahveh y dijo: «¿ Qué puedo hacer con este pueblo? Poco falta para que me apedreen».

[[exodus-17-5]]
^5^ Respondió Yahveh a Moisés: «Pasa delante del pueblo, llevando contigo algunos de los ancianos de Israel; lleva también en tu mano el cayado con que golpeaste el Río y vete,

[[exodus-17-6]]
^6^ que allí estaré yo ante ti, sobre la piña, en Horeb; golpearás la peña, y saldrá de ella agua para que beba el pueblo». Moisés lo hizo así a la vista de los ancianos de Israel.

[[exodus-17-7]]
^7^ Aquel lugar se llamó Massá y Meribá, a causa de la querella de los israelitas, y por haber tentado a Yahveh, diciendo: «¿Está Yahveh entre nosotros o no?»

[[exodus-17-8]]
^8^ Vinieron los amalecitas y atacaron a Israel en Refidim.

[[exodus-17-9]]
^9^ Moisés dijo a Josué: «Elígete algunos hombres, y sal mañana a combatir contra Amalec. Yo me pondré en la cima del monte, con el cayado de Dios en mi mano».

[[exodus-17-10]]
^10^ Josué cumplió las órdenes de Moisés, y salió a combatir contra Amalec. Mientras tanto, Moisés, Aarón y Jur subieron a la cima del monte.

[[exodus-17-11]]
^11^ Y sucedió que, mientras Moisés tenía alzadas las manos, prevalecía Israel; pero cuando las bajaba, prevalecía Amalec.

[[exodus-17-12]]
^12^ Se le cansaron las manos a Moisés, y entonces ellos tomaron una piedra y se la pusieron debajo; él se sentó sobre ella, mientras Aarón y Jur le sostenían las manos, uno a un lado y otro al otro. Y así resistieron sus manos hasta la puesta del sol.

[[exodus-17-13]]
^13^ Josué derrotó a Amalec y a su pueblo a filo de espada.

[[exodus-17-14]]
^14^ Yahveh dijo Moisés: «Escribe esto en un libro para que sirva de recuerdo, y haz saber a Josué que yo borraré por completo la memoria de Amalec de debajo de los cielos».

[[exodus-17-15]]
^15^ Después edificó Moisés un altar, al que puso por nombre Yahveh Nissí

[[exodus-17-16]]
^16^ diciendo: «La bandera de Yahveh en la mano; Yahveh está en guerra con Amalec de generación en generación».
[[exodus-18]]
== Capítulo 18

[[exodus-18-1]]
^1^ Jetró, sacerdote de Madián, suegro de Moisés, se enteró de lo que había hecho Dios en favor de Moisés y de Israel, su pueblo, y cómo Yahveh había sacado a Israel de Egipto.

[[exodus-18-2]]
^2^ Entonces Jetró, suegro de Moisés, tomó a Séfora, mujer de Moisés, a la que Moisés había despedido,

[[exodus-18-3]]
^3^ y a sus hijos; el uno se llamaba Guersom, pues Moisés dijo: «Forastero soy en tierra extraña,»

[[exodus-18-4]]
^4^ y el otro se llamaba Eliezer, pues dijo Moisés: «El Dios de mi padre es mi protector y me ha librado de la espada de Faraón».

[[exodus-18-5]]
^5^ Llegó, pues, Jetró, suegro de Moisés, con los hijos y la mujer de Moisés, al desierto, donde estaba acampado junto al monte de Dios.

[[exodus-18-6]]
^6^ Y dijo a Moisés: Yo, Jetró, tu suegro, vengo a ti con tu mujer y sus dos hijos».

[[exodus-18-7]]
^7^ Moisés salió al encuentro de su suegro, se postró y le besó. Se saludaron ambos y entraron en la tienda.

[[exodus-18-8]]
^8^ Moisés contó a su suegro todo lo que Yahveh había hecho a Faraón y a los egipcios, en favor de Israel; todos los trabajos sufridos en el camino y cómo Yahveh les había librado de ellos.

[[exodus-18-9]]
^9^ Jetró se alegró de todo el bien que Yahveh había hecho a Israel, librándole de la mano de los egipcios.

[[exodus-18-10]]
^10^ Y dijo Jetró: «¡Bendito sea Yahveh, que os ha librado de la mano de los egipcios y de la mano de Faraón y ha salvado al pueblo del poder de los egipcios!

[[exodus-18-11]]
^11^ Ahora reconozco que Yahveh es más grande que todos los dioses..».

[[exodus-18-12]]
^12^ Después Jetró, suegro de Moisés, ofreció un holocausto y sacrificios a Dios; y Aarón y todos los ancianos de Israel fueron a comer con el suegro de Moisés en presencia de Dios.

[[exodus-18-13]]
^13^ Al día siguiente, se sentó Moisés para juzgar al pueblo; y el pueblo estuvo ante Moisés desde la mañana hasta la noche.

[[exodus-18-14]]
^14^ El suegro de Moisés vio el trabajo que su yerno se imponía por el pueblo, y dijo: «¿Cómo haces eso con el pueblo? ¿Por qué te sientas tú solo haciendo que todo el pueblo tenga que permanecer delante de ti desde la mañana hasta la noche?»

[[exodus-18-15]]
^15^ Contestó Moisés a su suegro: «Es que el pueblo viene a mí para consultar a Dios.

[[exodus-18-16]]
^16^ Cuando tienen un pleito, vienen a mí; yo dicto sentencia entre unos y otros, y les doy a conocer los preceptos de Dios y sus leyes».

[[exodus-18-17]]
^17^ Entonces el suegro de Moisés le dijo: «No está bien lo que estás haciendo.

[[exodus-18-18]]
^18^ Acabarás agotándote, tú y este pueblo que está contigo; porque este trabajo es superior a tus fuerzas; no podrás hacerlo tú solo.

[[exodus-18-19]]
^19^ Así que escúchame; te voy a dar un consejo, y Dios estará contigo. Sé tú el representante del pueblo delante de Dios y lleva ante Dios sus asuntos.

[[exodus-18-20]]
^20^ Enséñales los preceptos y las leyes, dales a conocer el camino que deben seguir y las obras que han de practicar.

[[exodus-18-21]]
^21^ Pero elige de entre el pueblo hombres capaces, temerosos de Dios, hombres fieles e incorruptibles, y ponlos al frente del pueblo como jefes de mil, jefes de ciento, jefes de cincuenta y jefes de diez.

[[exodus-18-22]]
^22^ Ellos juzgarán al pueblo en todo momento; te presentarán a ti los asuntos más graves, pero en los asuntos de menor importancia, juzgarán ellos. Así se aliviará tu carga, pues ellos te ayudarán a llevarla.

[[exodus-18-23]]
^23^ Si haces esto, Dios te comunicará sus órdenes, tú podrás resistir, y todo este pueblo por su parte podrá volver en paz a su lugar».

[[exodus-18-24]]
^24^ Escuchó Moisés la voz de su suegro e hizo todo lo que le había dicho.

[[exodus-18-25]]
^25^ Eligió, pues, hombres capaces de entre todo Israel, y los puso al frente del pueblo, como jefes de mil, jefes de ciento, jefes de cincuenta, y jefes de diez.

[[exodus-18-26]]
^26^ Estos juzgaban al pueblo en todo momento; los asuntos graves se los presentaban a Moisés, mas en todos los asuntos menores juzgaban por sí mismos.

[[exodus-18-27]]
^27^ Después Moisés despidió a su suegro, que se volvió a su tierra.
[[exodus-19]]
== Capítulo 19

[[exodus-19-1]]
^1^ Al tercer mes después de la salida de Egipto, ese mismo día, llegaron los hijos de Israel al desierto de Sinaí.

[[exodus-19-2]]
^2^ Partieron de Refidim, y al llegar al desierto de Sinaí acamparon en el desierto. Allí acampó Israel frente al monte.

[[exodus-19-3]]
^3^ Moisés subió hacia Dios. Yahveh le llamó desde el monte, y le dijo: «Así dirás a la casa de Jacob y esto anunciarás a los hijos de Israel:

[[exodus-19-4]]
^4^ “Ya habéis visto lo que he hecho con los egipcios, y cómo a vosotros os he llevado sobre alas de águila y os he traído a mí.

[[exodus-19-5]]
^5^ Ahora, pues, si de veras escucháis mi voz y guardáis mi alianza, vosotros seréis mi propiedad personal entre todos los pueblos, porque mía es toda la tierra;

[[exodus-19-6]]
^6^ seréis para mí un reino de sacerdotes y una nación santa.” Estas son las palabras que has de decir a los hijos de Israel».

[[exodus-19-7]]
^7^ Fue, pues, Moisés y convocó a los ancianos del pueblo y les expuso todas estas palabras que Yahveh le había mandado.

[[exodus-19-8]]
^8^ Todo el pueblo a una respondió diciendo: «Haremos todo cuanto ha dicho Yahveh». Y Moisés llevó a Yahveh la respuesta del pueblo.

[[exodus-19-9]]
^9^ Dijo Yahveh a Moisés: «Mira: Voy a presentarme a ti en una densa nube para que el pueblo me oiga hablar contigo, y así te dé crédito para siempre». Y Moisés refirió a Yahveh las palabras del pueblo.

[[exodus-19-10]]
^10^ Yahveh dijo a Moisés: «Ve donde el pueblo y haz que se santifiquen hoy y mañana; que laven sus vestidos

[[exodus-19-11]]
^11^ y estén preparados para el tercer día; porque al día tercero descenderá Yahveh a la vista de todo el pueblo sobre el monte Sinaí.

[[exodus-19-12]]
^12^ Deslinda el contorno de la montaña, y di: Guardaos de subir al monte y aun de tocar su falda. Todo aquel que toque el monte morirá.

[[exodus-19-13]]
^13^ Pero nadie pondrá la mano sobre el culpable, sino que será lapidado o asaeteado; sea hombre o bestia, no quedará con vida. Cuando resuene el cuerno, subirán ellos al monte».

[[exodus-19-14]]
^14^ Bajó, pues, Moisés del monte, adonde estaba el pueblo, y ellos lavaron sus vestidos.

[[exodus-19-15]]
^15^ Y dijo al pueblo: «Estad preparados para el tercer día, y absteneos de mujer».

[[exodus-19-16]]
^16^ Al tercer día, al rayar el alba, hubo truenos y relámpagos y una densa nube sobre el monte y un poderoso resonar de trompeta; y todo el pueblo que estaba en el campamento se echó a temblar.

[[exodus-19-17]]
^17^ Entonces Moisés hizo salir al pueblo del campamento para ir al encuentro de Dios, y se detuvieron al pie del monte.

[[exodus-19-18]]
^18^ Todo el monte Sinaí humeaba, porque Yahveh había descendido sobre él en el fuego. Subía el humo como de un horno, y todo el monte retemblaba con violencia.

[[exodus-19-19]]
^19^ El sonar de la trompeta se hacía cada vez más fuerte; Moisés hablaba y Dios le respondía con el trueno.

[[exodus-19-20]]
^20^ Yahveh bajó al monte Sinaí, a la cumbre del monte; llamó Yahveh a Moisés a la cima de la montaña y Moisés subió.

[[exodus-19-21]]
^21^ Dijo Yahveh a Moisés: «Baja y conjura al pueblo que no traspase las lindes para ver a Yahveh, porque morirían muchos de ellos;

[[exodus-19-22]]
^22^ aun los sacerdotes que se acercan a Yahveh deben santificarse para que Yahveh no irrumpa contra ellos».

[[exodus-19-23]]
^23^ Moisés respondió a Yahveh: «El pueblo no podrá subir al monte Sinaí, porque tú nos lo has prohibido, diciendo: Señala un límite alrededor del monte y decláralo sagrado».

[[exodus-19-24]]
^24^ Yahveh le dijo: «Anda, baja, y luego subes tú y Aarón contigo; pero los sacerdotes y el pueblo no traspasarán las lindes para subir hacia Yahveh a fin de que no irrumpa contra ellos.”

[[exodus-19-25]]
^25^ Bajó, pues, Moisés adonde estaba el pueblo y les dijo...
[[exodus-20]]
== Capítulo 20

[[exodus-20-1]]
^1^ Entonces pronunció Dios todas estas palabras diciendo:

[[exodus-20-2]]
^2^ «Yo, Yahveh, soy tu Dios, que te he sacado del país de Egipto, de la casa de servidumbre.

[[exodus-20-3]]
^3^ No habrá para ti otros dioses delante de mí.

[[exodus-20-4]]
^4^ No te harás escultura ni imagen alguna ni de lo que hay arriba en los cielos, ni de lo que hay abajo en la tierra, ni de lo que hay en las aguas debajo de la tierra.

[[exodus-20-5]]
^5^ No te postrarás ante ellas ni les darás culto, porque yo Yahveh, tu Dios, soy un Dios celoso, que castigo la iniquidad de los padres en los hijos hasta la tercera y cuarta generación de los que me odian,

[[exodus-20-6]]
^6^ y tengo misericordia por millares con los que me aman y guardan mis mandamientos.

[[exodus-20-7]]
^7^ No tomarás en falso el nombre de Yahveh, tu Dios; porque Yahveh no dejará sin castigo a quien toma su nombre en falso.

[[exodus-20-8]]
^8^ Recuerda el día del sábado para santificarlo.

[[exodus-20-9]]
^9^ Seis días trabajarás y harás todos tus trabajos,

[[exodus-20-10]]
^10^ pero el día séptimo es día de descanso para Yahveh, tu Dios. No harás ningún trabajo, ni tú, ni tu hijo, ni tu hija, ni tu siervo, ni tu sierva, ni tu ganado, ni el forastero que habita en tu ciudad.

[[exodus-20-11]]
^11^ Pues en seis días hizo Yahveh el cielo y la tierra, el mar y todo cuanto contienen, y el séptimo descansó; por eso bendijo Yahveh el día del sábado y lo hizo sagrado.

[[exodus-20-12]]
^12^ Honra a tu padre y a tu madre, para que se prolonguen tus días sobre la tierra que Yahveh, tu Dios, te va a dar.

[[exodus-20-13]]
^13^ No matarás.

[[exodus-20-14]]
^14^ No cometerás adulterio.

[[exodus-20-15]]
^15^ No robarás.

[[exodus-20-16]]
^16^ No darás testimonio falso contra tu prójimo.

[[exodus-20-17]]
^17^ No codiciarás la casa de tu prójimo, ni codiciarás la mujer de tu prójimo, ni su siervo, ni su sierva, ni su buey, ni su asno, ni nada que sea de tu prójimo».

[[exodus-20-18]]
^18^ Todo el pueblo percibía los truenos y relámpagos, el sonido de la trompeta y el monte humeante, y temblando de miedo se mantenía a distancia.

[[exodus-20-19]]
^19^ Dijeron a Moisés: «Habla tú con nosotros, que podremos entenderte, pero que no hable Dios con nosotros, no sea que muramos».

[[exodus-20-20]]
^20^ Respondió Moisés al pueblo: «No temáis, pues Dios ha venido para poneros a prueba, para que su temor esté ante vuestros ojos, y no pequéis».

[[exodus-20-21]]
^21^ Y el pueblo se mantuvo a distancia, mientras Moisés se acercaba a la densa nube donde estaba Dios.

[[exodus-20-22]]
^22^ Dijo Yahveh a Moisés: Así dirás a los israelitas: Vosotros mismos habéis visto que os he hablado desde el cielo.

[[exodus-20-23]]
^23^ No haréis junto a mí dioses de plata, ni os haréis dioses de oro.

[[exodus-20-24]]
^24^ Hazme un altar de tierra para ofrecer sobre él tus holocaustos y tus sacrificios de comunión, tus ovejas y tus bueyes. En todo lugar donde haga yo memorable mi nombre, vendré a ti y te bendeciré.

[[exodus-20-25]]
^25^ Y si me haces un altar de piedra, no lo edificarás de piedras labradas; porque al alzar tu cincel sobre ella queda profanada.

[[exodus-20-26]]
^26^ Tampoco subirás por gradas a mi altar, para que no se descubra tu desnudez sobre él.
[[exodus-21]]
== Capítulo 21

[[exodus-21-1]]
^1^ Estas con las normas que has de dar:

[[exodus-21-2]]
^2^ Cuando compres un esclavo hebreo, servirá seis años, y el séptimo quedará libre sin pagar rescate.

[[exodus-21-3]]
^3^ Si entró solo, solo saldrá; si tenía mujer, su mujer saldrá con él.

[[exodus-21-4]]
^4^ Si su amo le dio mujer, y ella le dio a luz hijos o hijas, la mujer y sus hijos serán del amo, y él saldrá solo.

[[exodus-21-5]]
^5^ Si el esclavo declara: «Yo quiero a mi señor, a mi mujer y a mis hijos; renucio a la libertad»

[[exodus-21-6]]
^6^ su amo le llevará ante Dios y, arrimándolo a la puerta o a la jamba, su amo le horadará la oreja con una lezna; y quedará a su servicio para siempre.

[[exodus-21-7]]
^7^ Si un hombre vende a su hija por esclava, ésta no saldrá de la esclavitud como salen los esclavos.

[[exodus-21-8]]
^8^ Si no agrada a su señor que la había destinado para sí, éste permitirá su rescate; y no podrá venderla a gente extraña, tratándola con engaño.

[[exodus-21-9]]
^9^ Si la destina para su hijo, le dará el mismo trato que a sus hijas.

[[exodus-21-10]]
^10^ Si toma para sí otra mujer, no le disminuirá a la primera la comida, ni el vestido ni los derechos conyugales.

[[exodus-21-11]]
^11^ Y si no le da estas tres cosas, ella podrá salirse de balde sin pagar rescate.

[[exodus-21-12]]
^12^ El que hiera mortalmente a otro, morirá;

[[exodus-21-13]]
^13^ pero si no estaba al acecho, sino que Dios se lo puso al alcance de la mano, yo te señalaré un lugar donde éste pueda refugiarse.

[[exodus-21-14]]
^14^ Pero al que se atreva a matar a su prójimo con alevosía, hasta de mi altar le arrancarás para matarle.

[[exodus-21-15]]
^15^ El que pegue a su padre o a su madre morirá.

[[exodus-21-16]]
^16^ Quien rapte a una persona - la haya vendido o esté todavía en su poder - morirá.

[[exodus-21-17]]
^17^ Quien maldiga a su padre o a su madre morirá.

[[exodus-21-18]]
^18^ Si dos hombres riñen y uno hiere a otro con una piedra o con el puño, pero no muere, sino que, después de guardar cama,

[[exodus-21-19]]
^19^ puede levantarse y andar por la calle, apoyado en su bastón, el que le hirió quedará exculpado, pero pagará el tiempo perdido y los gastos de la curación completa.

[[exodus-21-20]]
^20^ Si un hombre golpea a su siervo o a su sierva con un palo y muere a sus manos, cae bajo la ley de venganza.

[[exodus-21-21]]
^21^ Pero si sobrevive un día o dos, no será vengado, pues lo había comprado con dinero.

[[exodus-21-22]]
^22^ Si unos hombres, en el curso de una riña, dan un golpe a una mujer encinta, y provocan el parto sin más daño, el culpable será multado conforme a lo que imponga el marido de la mujer y mediante arbitrio.

[[exodus-21-23]]
^23^ Pero si resultare daño, darás vida por vida,

[[exodus-21-24]]
^24^ ojo por ojo, diente por diente, mano por mano, pie por pie,

[[exodus-21-25]]
^25^ quemadura por quemadura, herida por herida, cardenal por cardenal.

[[exodus-21-26]]
^26^ Si un hombre hiere a su siervo o a su sierva en el ojo y le deja tuerto, le dará libertad en compensación del ojo.

[[exodus-21-27]]
^27^ Si uno salta un diente a su siervo o a su sierva, le pondrá en libertad en compensación del diente.

[[exodus-21-28]]
^28^ Si un buey acornea a un hombre o a una mujer, y le causa la muerte, el buey será apedreado, y no se comerá su carne, pero el dueño del buey quedará exculpado.

[[exodus-21-29]]
^29^ Mas si el buey acorneaba ya desde tiempo atrás, y su dueño, aun advertido, no le vigiló, y ese buey mata a un hombre o a una mujer, el buey será apedreado, y también su dueño morirá.

[[exodus-21-30]]
^30^ Si se le impone un precio por ello, dará en rescate de su vida cuanto le impongan.

[[exodus-21-31]]
^31^ Si acornea a un muchacho o a una muchacha, se seguirá esta misma norma.

[[exodus-21-32]]
^32^ Si el buey acornea a un siervo o a una sierva, se pagarán treinta siclos de plata al dueño de ellos, y el buey será apedreado.

[[exodus-21-33]]
^33^ Si un hombre deja abierto un pozo, o si cava un pozo y no lo tapa, y cae en él un buey o un asno,

[[exodus-21-34]]
^34^ el propietario del pozo pagará al dueño de ellos el precio en dinero, y el animal muerto será suyo.

[[exodus-21-35]]
^35^ Si el buey de uno acornea al buey de otro, causándole la muerte, venderán el buey vivo y se repartirán el precio, repartiendo igualmente el buey muerto.

[[exodus-21-36]]
^36^ Pero si era notorio que el buey acorneaba desde tiempo atrás, y su dueño no le vigiló, pargará buey por buey y el buey muerto será suyo.

[[exodus-21-37]]
^37^ Si un hombre roba un buey o una oveja, y los mata o vende, pagará cinco bueyes por el buey, y cuatro ovejas por la oveja.
[[exodus-22]]
== Capítulo 22

[[exodus-22-1]]
^1^ Si el ladrón, sorprendido al perforar la pared, es herido mortalmente, no habrá venganza de sangre.

[[exodus-22-2]]
^2^ Mas si esto sucede salido ya el sol, su sangre será vengada. - Debe restituir; si no tiene con qué, será vendido para restituir por su robo.

[[exodus-22-3]]
^3^ Si lo robado, sea buey, asno u oveja, fuere hallado vivo en su poder, restituirá el doble.

[[exodus-22-4]]
^4^ Si un hombre causa daño en un campo o en una viña, dejando suelto su ganado de modo que pazca en campo ajeno, restituirá con lo mejor de su propio campo y lo mejor de su propia viña.

[[exodus-22-5]]
^5^ Si se declara un fuego, y se incrementa con zarzales de modo que se abrasen las hacinas, la mies, o el campo, el autor del incendio deberá resarcir el daño.

[[exodus-22-6]]
^6^ Cuando un hombre dé a otro dinero o utensilios en depósito para que se lo guarde, y son robados de la casa de éste, el ladrón, si es hallado, restituirá el doble.

[[exodus-22-7]]
^7^ Pero si no es hallado, el dueño de la casa se presentará ante Dios para declarar que no ha puesto su mano sobre los bienes de su prójimo.

[[exodus-22-8]]
^8^ En todo caso delictivo, ya se trate de buey, asno, oveja, ropa o de cualquier cosa desaparecida, de la que uno diga: «Es esto», la causa de ambos se llevará ante Dios; y aquel a quien Dios declare culpable, restituirá el doble a su prójimo.

[[exodus-22-9]]
^9^ Si un hombre entrega a otro un asno, buey, oveja, o cualquier otro animal para su custodia, y éstos mueren o sufren daño o son robados sin que nadie lo vea,

[[exodus-22-10]]
^10^ mediará entre los dos el juramento de Yahveh para atestiguar que el depositario no ha puesto su mano sobre la hacienda de su prójimo; el dueño tomará lo que quede y el otro no tendrá que restituir.

[[exodus-22-11]]
^11^ Pero si el animal le ha sido robado estando él cerca, restituirá a su dueño.

[[exodus-22-12]]
^12^ Si el animal ha sido despedazado, que traiga como testimonio los despojos y no tendrá que restituir.

[[exodus-22-13]]
^13^ Si un hombre pide a otro que le preste un ganado y éste sufre un daño o muere, en ausencia de su dueño, tendrá que restituir.

[[exodus-22-14]]
^14^ Si estaba presente su dueño, nada se restituirá. Si lo había alquilado, el dueño recibirá el precio del alquiler.

[[exodus-22-15]]
^15^ Si un hombre seduce a una virgen, no desposada, y se acuesta con ella, le pagará la dote, y la tomará por mujer.

[[exodus-22-16]]
^16^ Y si el padre de ella no quiere dársela, el seductor pagará el dinero de la dote de las vírgenes.

[[exodus-22-17]]
^17^ A la hechicera no la dejarás con vida.

[[exodus-22-18]]
^18^ Todo el que peque con bestia, morirá.

[[exodus-22-19]]
^19^ El que ofrece sacrificios a otros dioses, será entregado al anatema.

[[exodus-22-20]]
^20^ No maltratarás al forastero, ni le oprimirás, pues forasteros fuisteis vosotros en el país de Egipto.

[[exodus-22-21]]
^21^ No vejarás a viuda ni a huérfano.

[[exodus-22-22]]
^22^ Si le vejas y clama a mí, no dejaré de oír su clamor,

[[exodus-22-23]]
^23^ se encenderá mi ira y os mataré a espada; vuestras mujeres quedarán viudas y vuestros hijos huérfanos.

[[exodus-22-24]]
^24^ Si prestas dinero a uno de mi pueblo, al pobre que habita contigo, no serás con él un usurero; no le exigiréis interés.

[[exodus-22-25]]
^25^ Si tomas en prenda el manto de tu prójimo, se lo devolverás al ponerse el sol,

[[exodus-22-26]]
^26^ porque con él se abriga; es el vestido de su cuerpo. ¿Sobre qué va a dormir, si no? Clamará a mí, y yo le oiré, porque soy compasivo.

[[exodus-22-27]]
^27^ No blasfemarás contra Dios, ni maldecirás al principal de tu pueblo.

[[exodus-22-28]]
^28^ No tardarás en ofrecerme de tu abundancia y de tus jugos. Me darás el primogénito de tus hijos.

[[exodus-22-29]]
^29^ Lo mismo has de hacer con el de tus vacas y ovejas. Siete días estará con su madre, y al octavo me lo darás.

[[exodus-22-30]]
^30^ Hombres santos seréis para mí. No comáis la carne despedazada por una fiera en el campo; echádsela a los perros.
[[exodus-23]]
== Capítulo 23

[[exodus-23-1]]
^1^ No levantes testimonio falso, ni ayudes al malvado dando testimonio injusto.

[[exodus-23-2]]
^2^ No sigas a la mayoría para hacer el mal; ni te inclines en un proceso por la mayoría en contra de la justicia.

[[exodus-23-3]]
^3^ Tampoco favorecerás al pobre en su pleito.

[[exodus-23-4]]
^4^ Si encuentras el buey de tu enemigo o su asno extraviado, se lo llevarás.

[[exodus-23-5]]
^5^ Si ves caído bajo la carga el asno del que te aborrece, no rehúses tu ayuda. Acude a ayudarle.

[[exodus-23-6]]
^6^ No tuerzas el derecho de tu pobre en su pleito.

[[exodus-23-7]]
^7^ Aléjate de causas mentirosas, no quites la vida al inocente y justo; y no absuelvas al malvado.

[[exodus-23-8]]
^8^ No recibas regalos; porque el regalo ciega a los perspicaces y pervierte las causas justas.

[[exodus-23-9]]
^9^ No oprimas al forastero; ya sabéis lo que es ser forastero, porque forasteros fuisteis vosotros en la tierra de Egipto.

[[exodus-23-10]]
^10^ Seis años sembrarás tu tierra y recogerás su producto;

[[exodus-23-11]]
^11^ al séptimo la dejarás descansar y en barbecho, para que coman los pobres de tu pueblo, y lo que quede lo comerán los animales del campo. Harás lo mismo con tu viña y tu olivar.

[[exodus-23-12]]
^12^ Seis días harás tus trabajos, y el séptimo descansarás, para que reposen tu buey y tu asno, y tengan un respiro el hijo de tu sierva y el forastero.

[[exodus-23-13]]
^13^ Guardad todo lo que os he dicho. No invocarás el nombre de otros dioses: ni se oiga en vuestra boca.

[[exodus-23-14]]
^14^ Tres veces al año me celebrarás fiesta.

[[exodus-23-15]]
^15^ Guardarás la fiesta de los Azimos. Durante siete días comerás ázimos, como te he mandado, en el tiempo señalado, en el mes de Abib; pues en él saliste de Egipto. Nadie se presentará delante de mí con las manos vacías.

[[exodus-23-16]]
^16^ También guardarás la fiesta de la Siega, de las primicias de tus trabajos, de lo que hayas sembrado en el campo; y la fiesta de la Recolección al término del año, al recoger del campo los frutos de tu trabajo.

[[exodus-23-17]]
^17^ Tres veces al año se presentarán tus varones delante de Yahveh, el Señor.

[[exodus-23-18]]
^18^ No ofrecerás la sangre de mi sacrificio con pan fermentado ni guardarás hasta el día siguiente la grasa de mi fiesta.

[[exodus-23-19]]
^19^ Llevarás a la Casa de Yahveh, tu Dios, las mejores primicias de tu suelo. No cocerás el cabrito en la leche de su madre.

[[exodus-23-20]]
^20^ He aquí que yo voy a enviar un ángel delante de ti, para que te guarde en el camino y te conduzca al lugar que te tengo preparado.

[[exodus-23-21]]
^21^ Pórtate bien en su presencia y escucha su voz; no le seas rebelde, que no perdonará vuestras transgresiones, pues en él está mi Nombre.

[[exodus-23-22]]
^22^ Si escuchas atentamente su voz y haces todo lo que yo diga, tus enemigos serán mis enemigos y tus adversarios mis adversarios.

[[exodus-23-23]]
^23^ Mi ángel caminará delante de ti y te introducirá en el país de los amorreos, de los hititas, de los perizitas, de los cananeos, de los jivitas y de los jebuseos; y yo los exterminaré.

[[exodus-23-24]]
^24^ No te mostrarás ante sus dioses, ni les darás culto, ni imitarás su conducta; al contrario, los destruirás por completo y romperás sus estelas.

[[exodus-23-25]]
^25^ Vosotros daréis culto a Yahveh, vuestro Dios, yo bendeciré tu pan y tu agua. Y apartaré de ti las enfermedades.

[[exodus-23-26]]
^26^ No habrá en tu tierra mujer que aborte ni que sea estéril; y colmaré el número de tus días.

[[exodus-23-27]]
^27^ «Sembraré delante de ti mi terror; llenaré de turbación a todos los pueblos donde llegues; y haré que todos tus enemigos huyan ante ti.

[[exodus-23-28]]
^28^ Enviaré avispas delante de ti que ahuyentarán de tu presencia al jivita, al cananeo y al hitita.

[[exodus-23-29]]
^29^ No les expulsaré de tu presencia en un solo año, no sea que al quedar desierta la tierra se multipliquen contra ti las fieras del campo.

[[exodus-23-30]]
^30^ Les expulsaré de tu vista poco a poco, hasta que tú te multipliques y te apoderes de la tierra.

[[exodus-23-31]]
^31^ Y fijaré tus confines desde el mar de Suf hasta el mar de los filisteos, y desde el desierto hasta el Río, pues entregaré en tus manos a los habitantes del país para que los arrojes de tu presencia.

[[exodus-23-32]]
^32^ No hagas pacto con ellos ni con sus dioses.

[[exodus-23-33]]
^33^ No habitarán en tu tierra, no sea que te hagan pecar contra mí, pues dando culto a sus dioses caerías en un lazo».
[[exodus-24]]
== Capítulo 24

[[exodus-24-1]]
^1^ Dijo a Moisés: «Sube donde Yahveh, tú, Aarón, Nadab y Abihú, con setenta de los ancianos de Israel; os postraréis desde lejos.

[[exodus-24-2]]
^2^ Sólo Moisés se acercará a Yahveh; ellos no se acercarán. Tampoco el pueblo subirá con ellos».

[[exodus-24-3]]
^3^ Vino, pues, Moisés y refirió al pueblo todas las palabras de Yahveh y todas sus normas. Y todo el pueblo respondió a una voz: «Cumpliremos todas las palabras que ha dicho Yahveh».

[[exodus-24-4]]
^4^ Entonces escribió Moisés todas las palabras de Yahveh; y, levantándose de mañana, alzó al pie del monte un altar y doce estelas por las doce tribus de Israel.

[[exodus-24-5]]
^5^ Luego mandó a algunos jóvenes, de los israelitas, que ofreciesen holocaustos e inmolaran novillos como sacrificios de comunión para Yahveh.

[[exodus-24-6]]
^6^ Tomó Moisés la mitad de la sangre y la echó en vasijas; la otra mitad la derramó sobre el altar.

[[exodus-24-7]]
^7^ Tomó después el libro de la Alianza y lo leyó ante el pueblo, que respondió: «Obedeceremos y haremos todo cuanto ha dicho Yahveh».

[[exodus-24-8]]
^8^ Entonces tomó Moisés la sangre, roció con ella al pueblo y dijo: «Esta es la sangre de la Alianza que Yahveh ha hecho con vosotros, según todas estas palabras».

[[exodus-24-9]]
^9^ Moisés subió con Aarón, Nadab y Abihú y setenta de los ancianos de Israel,

[[exodus-24-10]]
^10^ y vieron al Dios de Israel. Bajo sus pies había como un pavimento de zafiro tan puro como el mismo cielo.

[[exodus-24-11]]
^11^ No extendió él su mano contra los notables de Israel, que vieron a Dios, comieron y bebieron.

[[exodus-24-12]]
^12^ Dijo Yahveh a Moisés: «Sube hasta mí, al monte; quédate allí, y te daré las tablas de piedra - la ley y los mandamientos - que tengo escritos para su instrucción».

[[exodus-24-13]]
^13^ Se levantó Moisés, con Josué, su ayudante; y subieron al monte de Dios.

[[exodus-24-14]]
^14^ Dijo a los ancianos: «Esperadnos aquí que volvamos a vosotros. Ahí quedan con vosotros Aarón y Jur. El que tenga alguna cuestión que recurra a ellos».

[[exodus-24-15]]
^15^ Y subió Moisés al monte. La nube cubrió el monte.

[[exodus-24-16]]
^16^ La gloria de Yahveh descansó sobre el monte Sinaí y la nube lo cubrió por seis días. Al séptimo día, llamó Yahveh a Moisés de en medio de la nube.

[[exodus-24-17]]
^17^ La gloria de Yahveh aparecía a la vista de los hijos de Israel como fuego devorador sobre la cumbre del monte.

[[exodus-24-18]]
^18^ Moisés entró dentro de la nube y subió al monte. Y permaneció Moisés en el monte cuarenta días y cuarenta noches.
[[exodus-25]]
== Capítulo 25

[[exodus-25-1]]
^1^ Yahveh habló a Moisés diciendo:

[[exodus-25-2]]
^2^ Di a los israelitas que reserven ofrendas para mí. Me reservaréis la ofrenda de todo aquel a quien su corazón mueva.

[[exodus-25-3]]
^3^ De ellos reservaréis lo siguiente: oro, plata y bronce;

[[exodus-25-4]]
^4^ púrpura violeta y escarlata, carmesí, lino fino y pelo de cabra;

[[exodus-25-5]]
^5^ pieles de carnero teñidas de rojo, cueros finos y maderas de acacia;

[[exodus-25-6]]
^6^ aceite para el alumbrado, aromas para el óleo de la unción y para el incienso aromático;

[[exodus-25-7]]
^7^ piedras de ónice y piedras de engaste para el efod y el pectoral.

[[exodus-25-8]]
^8^ Me harás un Santuario para que yo habite en medio de ellos.

[[exodus-25-9]]
^9^ Lo haréis comforme al modelo de la Morada y al modelo de todo su mobiliario que yo voy a mostrarte.

[[exodus-25-10]]
^10^ Harás un arca de madera de acacia de dos codos y medio de largo, codo y medio de ancho y codo y medio de alto.

[[exodus-25-11]]
^11^ La revestirás de oro puro; por dentro y por fuera la revestirás; y además pondrás en su derredor una moldura de oro.

[[exodus-25-12]]
^12^ Fundirás para ella cuatro anillas de oro, que pondrás en sus cuatro pies, dos anillas a un costado, y dos anillas al otro.

[[exodus-25-13]]
^13^ Harás también varales de madera de acacia, que revestirás de oro,

[[exodus-25-14]]
^14^ y los pasarás por las anillas de los costados del arca, para transportarla.

[[exodus-25-15]]
^15^ Los varales deben quedar en las anillas del arca, y no se sacarán de allí.

[[exodus-25-16]]
^16^ En el arca pondrás el Testimonio que yo te voy a dar.

[[exodus-25-17]]
^17^ Harás asimismo uno propiciatorio de oro puro, de dos codos y medio de largo y codo y medio de ancho.

[[exodus-25-18]]
^18^ Harás, además, dos querubines de oro macizo; los harás en los dos extremos del propiciatorio:

[[exodus-25-19]]
^19^ haz el primer querubín en un extremo y el segundo en el otro. Los querubines formarán un cuerpo con el propiciatorio, en sus dos extremos.

[[exodus-25-20]]
^20^ Estarán con las alas extendidas por encima, cubriendo con ellas el propiciatorio, uno frente al otro, con las caras vueltas hacia el propiciatorio.

[[exodus-25-21]]
^21^ Pondrás el propiciatorio encima del arca; y pondrás dentro del arca el Testimonio que yo te daré.

[[exodus-25-22]]
^22^ Allí me encontraré contigo; desde encima del propiciatorio, de en medio de los dos querubines colocados sobre el arca del Testimonio, te comunicaré todo lo que haya de ordenarte para los israelitas.

[[exodus-25-23]]
^23^ Harás una mesa de madera de acacia, de dos codos de largo, uno de ancho, y codo y medio de alto.

[[exodus-25-24]]
^24^ La revestirás de oro puro y le pondrás alrededor una moldura de oro.

[[exodus-25-25]]
^25^ Harás también en torno de ella un reborde de una palma de ancho, con una moldura de oro alrededor del mismo. Exodo 25:26 Le harás cuatro anillas de oro, y pondrás las anillas en los cuatro ángulos correspondientes a sus cuatro pies.

[[exodus-25-27]]
^27^ Estarán las anillas junto al reborde, para pasar por ellas los varales y transportar la mesa.

[[exodus-25-28]]
^28^ Harás los varales de madera de acacia y los revestirás de oro. Con ellos se transportará la mesa.

[[exodus-25-29]]
^29^ Harás también las fuentes, los vasos, los jarros y las tazas para las libaciones. De oro puro los harás.

[[exodus-25-30]]
^30^ Y sobre la mesa pondrás perpetuamente delante de mí el pan de la Presencia.

[[exodus-25-31]]
^31^ Harás también un candelabro de oro puro. Harás de oro macizo el candelabro, su pie y su tallo. Sus cálices - corolas y flores - formarán un cuerpo con él.

[[exodus-25-32]]
^32^ Saldrán seis brazos de sus lados: tres brazos de un lado y tres del otro.

[[exodus-25-33]]
^33^ El primer brazo tendrá tres cálices en forma de flor de almendro, con corola y flor; también el segundo brazo tendrá tres cálices en forma de flor de almendro, con corola y flor; y así los seis brazos que salen del candelabro.

[[exodus-25-34]]
^34^ En el mismo candelabro habrá cuatro cálices en forma de flor de almendro, con sus corolas y sus flores:

[[exodus-25-35]]
^35^ una corola debajo de los dos primeros brazos que forman cuerpo con el candelabro; una corola, debajo de los dos siguientes, y una corola, debajo de los dos últimos brazos; así con los seis brazos que salen del candelabro.

[[exodus-25-36]]
^36^ Las corolas y los brazos formarán un cuerpo con el candelabro. Todo ello formará un cuerpo de oro puro macizo.

[[exodus-25-37]]
^37^ Harás sus siete lámparas que colocarás encima de manera que den luz al frente.

[[exodus-25-38]]
^38^ Sus despabiladeras y sus ceniceros serán de oro puro.

[[exodus-25-39]]
^39^ Se empleará un talento de oro puro para hacer el candelabro con todos estos utensilios.

[[exodus-25-40]]
^40^ Fíjate para que lo hagas según los modelos que te han sido mostrados en el monte.
[[exodus-26]]
== Capítulo 26

[[exodus-26-1]]
^1^ Harás la Morada con diez tapices, de lino fino torzal, de púrpura violeta y escarlata y de carmesí; bordarás en ellos unos querubines.

[[exodus-26-2]]
^2^ La longitud de cada tapiz será de veintiocho codos y la anchura de cuatro. Todos los tapices tendrán las mismas medidas.

[[exodus-26-3]]
^3^ Cinco tapices estarán unidos entre sí y lo mismo los otros cinco.

[[exodus-26-4]]
^4^ Pondrás lazos de púrpura violeta en el borde del tapiz con que termina la primera serie, y lo mismo harás en el borde del tapiz con que termina el segundo conjunto.

[[exodus-26-5]]
^5^ Pondrás cincuenta lazos en el primer tapiz y otros cincuenta en el borde del último tapiz del segundo conjunto, correspondiéndose los lazos unos a otros.

[[exodus-26-6]]
^6^ Harás cincuenta broches de oro y con los broches enlazarás entre sí los tapices, para que la Morada forme un espacio único.

[[exodus-26-7]]
^7^ Tejerás también piezas de pelo de cabra para que a modo de tienda cubran la Morada. Tejerás once de estas piezas.

[[exodus-26-8]]
^8^ La longitud de cada pieza será de treinta codos; de cuatro, la anchura. Las once piezas tendrán las mismas medidas.

[[exodus-26-9]]
^9^ Juntarás cinco piezas en una parte y seis en la otra y doblarás la sexta pieza ante la fachada de la Tienda.

[[exodus-26-10]]
^10^ Harás cincuenta lazos en el borde de la última pieza del primer conjunto, y cincuenta lazos en el borde de la última pieza del segundo conjunto.

[[exodus-26-11]]
^11^ Harás cincuenta broches de bronce e introducirás los broches en los lazos, uniendo así la Tienda de modo que forme un espacio único.

[[exodus-26-12]]
^12^ Como las piezas de la Tienda exceden en amplitud, harás extender la mitad de la pieza excedente por detrás de la Morada.

[[exodus-26-13]]
^13^ Lo que excede en longitud de las piezas de la Tienda - un codo por cada lado - se extenderá a ambos lados de la Morada, a un lado y a otro, para cubrirla.

[[exodus-26-14]]
^14^ También harás para la Tienda un toldo de pieles de carnero teñidas de rojo; y encima otro toldo de cueros finos.

[[exodus-26-15]]
^15^ También harás para la Morada tableros de madera de acacia, y los pondrás de pie.

[[exodus-26-16]]
^16^ Cada tablero tendrá diez codos de largo y codo y medio de ancho.

[[exodus-26-17]]
^17^ Tendrá además dos espigas paralelas. Harás lo mismo para todos los tableros de la Morada.

[[exodus-26-18]]
^18^ Pondrás veinte de los tableros en el flanco del Négueb, hacia el sur.

[[exodus-26-19]]
^19^ Harás cuarenta basas de plata para colocarlas debajo de los veinte tableros: dos basas debajo de un tablero para sus dos espigas y dos basas debajo del otro tablero para sus dos espigas.

[[exodus-26-20]]
^20^ Para el segundo flanco de la Morada, la parte del norte, otros veinte tableros,

[[exodus-26-21]]
^21^ con sus cuarenta basas de plata: dos basas debajo de un tablero y dos basas debajo de otro tablero.

[[exodus-26-22]]
^22^ Para la parte posterior de la Morada, hacia el occidente, harás seis tableros;

[[exodus-26-23]]
^23^ y para los ángulos de la Morada, en su parte posterior, dos más,

[[exodus-26-24]]
^24^ que estarán unidos, desde abajo hasta arriba, hasta la primera anilla. Así se hará con los dos tableros destinados a los dos ángulos.

[[exodus-26-25]]
^25^ Serán, pues, ocho tableros con sus basas de plata; dieciséis basas, dos debajo del otro tablero.

[[exodus-26-26]]
^26^ Harás, además, cinco travesaños de madera de acacia para los tableros de un flanco de la Morada,

[[exodus-26-27]]
^27^ cinco travesaños para los tableros del otro flanco, y cinco travesaños para los tableros de la parte posterior de la Morada, hacia el occidente.

[[exodus-26-28]]
^28^ El travesaño central pasará a media altura de los tableros, de un extremo al otro.

[[exodus-26-29]]
^29^ Revestirás de oro los tableros y les harás anillas de oro, para pasar los travesaños. También revestirás de oro los travesaños.

[[exodus-26-30]]
^30^ Erigirás la Morada según la norma que te ha sido mostrada en el monte.

[[exodus-26-31]]
^31^ Harás un velo de púrpura violeta y escarlata, de carmesí y lino fino torzal; bordarás en él unos querubines.

[[exodus-26-32]]
^32^ Lo colgarás de cuatro postes de acacia, revestidos de oro, provistos de ganchos de oro y de sus cuatro basas de plata.

[[exodus-26-33]]
^33^ Colgarás el velo debajo de los broches; y allá, detrás del velo, llevarás el arca del Testimonio, y el velo os servirá para separar el Santo del Santo de los Santos.

[[exodus-26-34]]
^34^ Pondrás el propiciatorio sobre el arca del Testimonio, en el Santo de los Santos.

[[exodus-26-35]]
^35^ Fuera del velo colocarás la mesa, y frente a la mesa, en el lado meridional de la Morada, el candelabro; pondrás la mesa en el lado norte.

[[exodus-26-36]]
^36^ Harás para la entrada de la Tienda una cortina de púrpura violeta y escarlata, de carmesí y lino fino torzal, labor de recamador.

[[exodus-26-37]]
^37^ Para la cortina harás cinco postes de acacia, que revestirás de oro; sus ganchos serán también de oro, y fundirás para ellos cinco basas de bronce.
[[exodus-27]]
== Capítulo 27

[[exodus-27-1]]
^1^ Harás el altar de madera de acacia de cinco codos de largo y cinco de ancho; será cuadrado y tendrá tres codos de alto.

[[exodus-27-2]]
^2^ Harás sobresalir de sus cuatro ángulos unos cuernos, que formarán un cuerpo con él; lo revestirás de bronce.

[[exodus-27-3]]
^3^ Le harás ceniceros para la grasa incinerada, badiles y acetres, tenedores y braseros. Fundirás de bronce todos estos utensilios.

[[exodus-27-4]]
^4^ Fabricarás para él una rejilla de bronce, en forma de red; y en los cuatro extremos de la red fijarás cuatro anillas de bronce.

[[exodus-27-5]]
^5^ La colocarás bajo la cornisa inferior del altar, de modo que llegue desde abajo hasta la mitad del altar.

[[exodus-27-6]]
^6^ Harás varales para el altar, varales de madera de acacia, que revestirás de bronce.

[[exodus-27-7]]
^7^ Para transportar el altar, se pasarán estos varales por las anillas de ambos lados del altar.

[[exodus-27-8]]
^8^ Harás el altar hueco, de paneles; conforme a lo que se te ha mostrado en el monte, así lo harás.

[[exodus-27-9]]
^9^ También harás el atrio de la Morada. Del lado del Négueb, hacia el sur, el atrio tendrá un cortinaje de lino fino torzal, en una longitud de cien codos a uno de los lados.

[[exodus-27-10]]
^10^ Sus veinte postes descansarán sobre veinte basas de bronce; sus ganchos y varillas serán de plata.

[[exodus-27-11]]
^11^ A lo largo del lado septenrional habrá igualmente un cortinaje en una longitud de cien codos, con sus veinte postes que descansarán sobre veinte basas de bronce; los ganchos de los postes y sus varillas serán de plata.

[[exodus-27-12]]
^12^ A lo ancho del atrio, por el lado occidental, habrá un cortinaje de cincuenta codos; sus postes serán diez, y diez igualmente las basas en que descansarán.

[[exodus-27-13]]
^13^ La anchura del atrio, al este, al oriente, será de cincuenta codos.

[[exodus-27-14]]
^14^ Quince codos tendrá el cortinaje de un lado, con sus tres postes y sus tres basas.

[[exodus-27-15]]
^15^ Por el otro lado, otro cortinaje de quince codos, con sus tres postes y sus tres basas.

[[exodus-27-16]]
^16^ La puerta del atrio tendrá un tapiz de veinte codos, de púrpura violeta y escarlata, de carmesí y lino fino torzal, labor de recamador. Tendrá cuatro postes y cuatro basas.

[[exodus-27-17]]
^17^ Todos los postes que rodean al atrio tendrán varillas de plata; sus ganchos serán de plata y sus basas de bronce.

[[exodus-27-18]]
^18^ El atrio tendrá cien codos de largo, cincuenta codos de ancho y cinco codos de alto; todo de lino fino torzal y con sus basas de bronce.

[[exodus-27-19]]
^19^ Todos los utensilios de la Morada para toda clase de servicios con todo su clavazón y toda la clavazón del atrio, serán de bronce.

[[exodus-27-20]]
^20^ Mandarás a los israelitas que te traigan aceite puro de oliva molida para el alumbrado, para alimentar continuamente la llama.

[[exodus-27-21]]
^21^ Aarón y sus hijos lo tendrán dispuesto delante de Yahveh desde la tarde hasta la mañana en Tienda del Encuentro, fuera del velo que cuelga delante del Testimonio. Decreto perpetuo será éste para las generaciones de los israelitas.
[[exodus-28]]
== Capítulo 28

[[exodus-28-1]]
^1^ Manda acercarse a ti de en medio de los israelitas a tu hermano Aarón, con sus hijos, para que ejerza mi sacerdocio: Aarón, con Nadab y Abihú, Eleazar e Itamar, hijos de Aarón.

[[exodus-28-2]]
^2^ Harás para Aarón, tu hermano, vestiduras sagradas, que le den majestad y esplendor.

[[exodus-28-3]]
^3^ Hablarás tú con todos los artesanos hábiles a quienes he llenado de espíritu de sabiduría; ellos harán las vestiduras de Aarón para que sea consagrado sacerdote mío.

[[exodus-28-4]]
^4^ Harán las vestituras siguientes: un pectoral, un efod, un manto, una túnica bordada, una tiara y una faja. Harán, pues, a tu hermano Aarón y a sus hijos vestiduras sagradas para que ejerzan mi sacerdocio.

[[exodus-28-5]]
^5^ Tomarán para ello oro, púrpura violeta y escarlata, carmesí y lino fino.

[[exodus-28-6]]
^6^ Bordarán el efod de oro, púrpura violeta y escarlata, carmesí y lino fino torzal.

[[exodus-28-7]]
^7^ Se le pondrán dos hombreras y se fijará por sus dos extremos.

[[exodus-28-8]]
^8^ La cinta con que se ciña el efod será de la misma hechura y formará con él una misma pieza: de oro, púrpura violeta y escarlata, carmesí y lino fino torzal.

[[exodus-28-9]]
^9^ Tomarás dos piedras de ónice, sobre las cuales grabarás los nombres de los hijos de Israel:

[[exodus-28-10]]
^10^ seis de sus nombres en una piedra y los seis restantes en la otra, por orden de nacimiento.

[[exodus-28-11]]
^11^ Como se tallan las piedras y se graban los sellos, así harás grabar esas dos piedras con los nombres de los hijos de Israel; las harás engarzar en engastes de oro.

[[exodus-28-12]]
^12^ Después pondrás las dos piedras sobre las hombreras del efod, como piedras que me hagan recordar a los hijos de Israel, y así llevará Aarón sus nombres sobre sus dos hombros para recuerdo delante de Yahveh.

[[exodus-28-13]]
^13^ Harás engarces de oro;

[[exodus-28-14]]
^14^ y también dos cadenillas de oro puro; las harás trenzadas a manera de cordones, y fijarás las cadenillas trenzadas en los engarces.

[[exodus-28-15]]
^15^ Bordarás también el pectoral del juicio; lo harás al estilo de la labor del efod. Lo harás de oro, púrpura violeta y escarlata, de carmesí y lino fino torzal.

[[exodus-28-16]]
^16^ Será cuadrado y doble, de un palmo de largo y otro de ancho.

[[exodus-28-17]]
^17^ Lo llenarás de pedrería, poniendo cuatro filas de piedras: en la primera fila, un sardio, un topacio y una esmeralda;

[[exodus-28-18]]
^18^ en la segunda fila, un rubí, un zafiro y un diamante;

[[exodus-28-19]]
^19^ en la tercera fila, un ópalo, una ágata y una amatista;

[[exodus-28-20]]
^20^ en la cuarta fila, un crisólito, un ónice y un jaspe; todas estarán engastadas en oro.

[[exodus-28-21]]
^21^ Las piedras corresponderán a los nombres de los hijos de Israel: doce, como los nombres de ellos. Estarán grabadas como los sellos, cada una con su nombre, conforme a las doce tribus.

[[exodus-28-22]]
^22^ Para el pectoral harás cadenillas de oro puro, trenzadas a manera de cordones;

[[exodus-28-23]]
^23^ y harás también para el pectoral dos anillas de oro que fijarás en sus dos extremos.

[[exodus-28-24]]
^24^ Pasarás los dos cordones de oro por las dos anillas, en los extremos del pectoral;

[[exodus-28-25]]
^25^ unirás los dos extremos de los dos cordones a los dos engarces, y los fijarás en la parte delantera de las hombreras del efod.

[[exodus-28-26]]
^26^ Harás otras dos anillas de oro que pondrás en los dos extremos del pectoral, en el borde interior que mira hacia el efod.

[[exodus-28-27]]
^27^ Harás otras dos anillas de oro y las fijarás en la parte inferior de las dos hombreras del efod, por delante, cerca de su unión encima de la cinta del efod.

[[exodus-28-28]]
^28^ Sujetarán el pectoral por sus anillas a las anillas del efod, con un cordón de púrpura violeta, para que el pectoral quede sobre la cinta del efod y no se desprenda del efod.

[[exodus-28-29]]
^29^ Así llevará Aarón sobre su corazón los nombres de los hijos de Israel, en el pectoral del juicio, siempre que entre en el Santuario, para recuerdo perpetuo delante de Yahveh.

[[exodus-28-30]]
^30^ En el pectoral del juicio pondrás el Urim y el Tummim, que estarán sobre el corazón de Aarón cuando se presente ante Yahveh. Así llevará Aarón constantemente sobre su corazón, delante de Yahveh, el oráculo de los hijos de Israel.

[[exodus-28-31]]
^31^ Tejerás el manto del efod todo él de púrpura violeta.

[[exodus-28-32]]
^32^ Habrá en su centro una abertura para la cabeza; esta abertura llevará en derredor una orla, tejida como el cuello de una cota, para que no se rompa.

[[exodus-28-33]]
^33^ En todo su ruedo inferior harás granadas de púrpura violeta y escarlata, de carmesí y lino fino torzal; y entre ellas, también alrededor, pondrás campanillas de oro:

[[exodus-28-34]]
^34^ una campanilla de oro y una granada; otra campanilla de oro y otra granada; así por todo el ruedo inferior del manto.

[[exodus-28-35]]
^35^ Aarón lo llevará en su ministerio y se oirá el tintineo cuando entre en el Santuario, ante Yahveh, y cuando salga; así no morirá.

[[exodus-28-36]]
^36^ Harás, además, una lámina de oro puro y en ella grabarás como se graban los sellos: «“Consagrado a Yahveh».

[[exodus-28-37]]
^37^ La sujetarás con un cordón de púrpura violeta, de modo que esté fija sobre la tiara; estará en la parte delantera de la tiara.

[[exodus-28-38]]
^38^ Quedará sobre la frente de Aarón; pues Aarón cargará con las faltas cometidas por los israelitas en las cosas sagradas; es decir, al ofrecer toda clase de santas ofrendas. La tendrá siempre sobre su frente, para que hallen favor delante de Yahveh.

[[exodus-28-39]]
^39^ Tejerás la túnica con lino fino; harás también la tiara de lino fino, y la faja con brocado.

[[exodus-28-40]]
^40^ Para los hijos de Aarón harás túnicas. Les harás también fajas y mitras que les den majestad y esplendor.

[[exodus-28-41]]
^41^ Vestirás así a tu hermano Aarón y a sus hijos; los ungirás, los investirás y los consagrarás para que ejerzan mi sacerdocio.

[[exodus-28-42]]
^42^ Hazles también calzones de lino, para cubrir su desnudez desde la cintura hasta los muslos.

[[exodus-28-43]]
^43^ Aarón y sus hijos los llevarán al entrar en la Tienda del Encuentro, o al acercarse al altar para oficiar en el Santuario, para que no incurran en culpa y mueran. Decreto perpetuo será éste para él y su posteridad.
[[exodus-29]]
== Capítulo 29

[[exodus-29-1]]
^1^ Para consagrarlos a mi sacerdocio has de proceder con ellos de esta manera. Toma un novillo y dos carneros sin defecto,

[[exodus-29-2]]
^2^ panes ázimos y tortas sin levadura: unas, amasadas con aceite, y otras, untadas en aceite. Las harás con flor de harina de trigo.

[[exodus-29-3]]
^3^ Las pondrás en un canastillo y las presentarás en él junto con el novillo y los dos carneros.

[[exodus-29-4]]
^4^ Mandarás que Aarón y sus hijos se acerquen a la entrada de la Tienda del Encuentro, donde los bañarás con agua.

[[exodus-29-5]]
^5^ Tomarás las vestiduras y vestirás a Aarón con la túnica, el manto del efod, el efod y el pectoral, que ceñirás con la cinta del efod.

[[exodus-29-6]]
^6^ Pondrás la tiara sobre su cabeza, y sobre la tiara colocarás la diadema sagrada.

[[exodus-29-7]]
^7^ Entonces tomarás el óleo de la unción, lo derramarás sobre su cabeza y así le ungirás.

[[exodus-29-8]]
^8^ Harás igualmente que se acerquen sus hijos y los vestirás con túnicas;

[[exodus-29-9]]
^9^ ceñirás a Aarón y a sus hijos las fajas y les pondrás las mitras. A ellos les corresponderá el sacerdocio por decreto perpetuo. Así investirás a Aarón y a sus hijos.

[[exodus-29-10]]
^10^ Presentarás el novillo ante la Tienda del Encuentro, y Aarón y sus hijos impondrán las manos sobre la cabeza del novillo.

[[exodus-29-11]]
^11^ Luego inmolarás el novillo delante de Yahveh, a la entrada de la Tienda del Encuentro.

[[exodus-29-12]]
^12^ Tomando sangre del novillo, untarás con tu dedo los cuernos del altar, y derramarás toda la sangre al pie del altar.

[[exodus-29-13]]
^13^ Saca todo el sebo que cubre las entrañas, el que queda junto al hígado, y los dos riñones con el sebo que los envuelve, para quemarlo en el altar.

[[exodus-29-14]]
^14^ Pero quemarás fuera del campamento la carne del novillo, con su piel y sus excrementos. Es sacrificio por el pecado.

[[exodus-29-15]]
^15^ Después tomarás uno de los carneros y Aarón y sus hijos impondrán las manos sobre la cabeza del carnero.

[[exodus-29-16]]
^16^ Una vez inmolado el carnero, tomarás su sangre y la derramarás en torno al altar.

[[exodus-29-17]]
^17^ Luego despedazarás el carnero, lavarás sus entrañas y sus patas; las pondrás sobre sus porciones y sobre su cabeza,

[[exodus-29-18]]
^18^ y quemarás todo el carnero en el altar. Es holocausto para Yahveh, calmante aroma de manjares abrasados en honor de Yahveh.

[[exodus-29-19]]
^19^ Tomarás también el segundo carnero, y Aarón y sus hijos impondrán las manos sobre la cabeza del carnero.

[[exodus-29-20]]
^20^ Una vez inmolado, tomarás su sangre y untarás con ella el lóbulo de la oreja derecha de Aarón y el lóbulo de la oreja derecha de sus hijos; el pulgar de su mano derecha y el pulgar de su pie derecho, y derramarás la sangre alrededor del altar.

[[exodus-29-21]]
^21^ Tomarás luego sangre de la que está sobre el altar, y óleo de la unción, para rociar a Aarón y sus vestiduras, a sus hijos y las vestiduras de sus hijos juntamente con él. Así quedará consagrado él y sus vestiduras y con él sus hijos y las vestiduras de sus hijos.

[[exodus-29-22]]
^22^ Toma después el sebo de este carnero: la cola, el sebo que cubre las entrañas, el que queda junto al hígado, los dos riñones con el sebo que lo envuelve y la pierna derecha, porque se trata del carnero de la investidura.

[[exodus-29-23]]
^23^ Toma del canastillo de los ázimos que está delante de Yahveh un pan redondo, una torta de pan de aceite y otra, untada de aceite.

[[exodus-29-24]]
^24^ Lo pondrás todo sobre las palmas de las manos de Aarón y de sus hijos; y lo mecerás como ofrenda mecida delante de Yahveh.

[[exodus-29-25]]
^25^ Después lo tomarás de sus manos y lo quemarás en el altar junto al holocausto como calmante aroma ante Yahveh. Es un manjar abrasado en honor de Yahveh.

[[exodus-29-26]]
^26^ Tomarás también el pecho del carnero inmolado por la investidura de Aarón, y lo mecerás como ofrenda mecida delante de Yahveh; esa será tu porción.

[[exodus-29-27]]
^27^ Así santificarás el pecho de la ofrenda mecida y la pierna de la ofrenda reservada, es decir, lo que ha sido mecido y reservado del carnero de la investidura de Aarón y de sus hijos;

[[exodus-29-28]]
^28^ según decreto perpetuo, pertenecerán a Aarón y a sus hijos, como porción recibida de los israelitas, porque es ofrenda reservada; será reservada de lo que ofrecen los israelitas, en sus sacrificios de comunión como ofrenda reservada a Yahveh.

[[exodus-29-29]]
^29^ Las vestiduras sagradas de Aarón serán, después de él, para sus hijos, de modo que, vestidos con ellas, sean ungidos e investidos.

[[exodus-29-30]]
^30^ Por siete días las vestirá aquel de sus hijos que le suceda como sacerdote y entre en la Tienda del Encuentro para oficiar en el Santuario.

[[exodus-29-31]]
^31^ Tomarás después el carnero de la investidura y cocerás su carne en lugar sagrado;

[[exodus-29-32]]
^32^ Aarón y sus hijos comerán a la entrada de la Tienda del Encuentro la carne del carnero y el pan del canastillo.

[[exodus-29-33]]
^33^ Comerán aquello que ha servido para su expiación al investirlos y consagrarlos; pero que ningún laico coma de ello, porque es cosa sagrada.

[[exodus-29-34]]
^34^ Si a la mañana siguiente sobra algo de la carne o del pan de la investidura, quemarás este resto; no ha de comerse, porque es cosa sagrada.

[[exodus-29-35]]
^35^ Harás, pues, con Aarón y con sus hijos de esta manera, según todo lo que te he mandado. Siete días invertirás en la investidura.

[[exodus-29-36]]
^36^ Cada día ofrecerás un novillo en expiación como sacrificio por el pecado; y purificarás, mediante tu expiación, el altar, que ungirás para consagrarlo.

[[exodus-29-37]]
^37^ Siete días harás la expiación por el altar, y lo santificarás; el altar será cosa sacratísima; todo cuanto toque al altar quedará consagrado.

[[exodus-29-38]]
^38^ He aquí lo que has de ofrecer sobre el altar: dos corderos primales cada día, perpetuamente.

[[exodus-29-39]]
^39^ Ofrecerás un cordero por la mañana y el otro entre dos luces;

[[exodus-29-40]]
^40^ y con el primer cordero, una décima de medida de flor de harina, amasada con un cuarto de sextario de aceite de oliva molida, y como libación un cuarto de sextario de vino.

[[exodus-29-41]]
^41^ Ofrecerás el otro cordero entre dos luces; lo ofrecerás con la misma oblación que a la mañana y con la misma libación, como calmante aroma del manjar abrasado en honor de Yahveh,

[[exodus-29-42]]
^42^ en holocausto perpetuo, de generación en generación, ante Yahveh, a la entrada de la Tienda del Encuentro, donde me encontraré contigo, para hablarte allí.

[[exodus-29-43]]
^43^ Me encontraré con los israelitas en ese lugar que será consagrado por mi gloria.

[[exodus-29-44]]
^44^ Consagraré la Tienda del Encuentro y el altar, y consagraré también a Aarón y a sus hijos para que ejerzan mi sacerdocio.

[[exodus-29-45]]
^45^ Moraré en medio de los israelitas, y seré para ellos Dios.

[[exodus-29-46]]
^46^ Y reconocerán que yo soy Yahveh, su Dios, que los saqué del país de Egipto para morar entre ellos. Yo, Yahveh, su Dios.
[[exodus-30]]
== Capítulo 30

[[exodus-30-1]]
^1^ Harás también un altar para quemar el incienso. De madera de acacia lo harás.

[[exodus-30-2]]
^2^ Será cuadrado: de un codo de largo y otro de ancho; su altura será de dos codos. Sus cuernos formarán un solo cuerpo con él.

[[exodus-30-3]]
^3^ Lo revestirás de oro puro, tanto su parte superior como sus costados, así como sus cuernos. Pondrás en su derredor una moldura de oro,

[[exodus-30-4]]
^4^ y debajo de la moldura, a los costados, harás dos anillas. Las harás a ambos lados, para meter por ellas los varales con que transportarlo.

[[exodus-30-5]]
^5^ Harás los varales de madera de acacia y los revestirás de oro.

[[exodus-30-6]]
^6^ Colocarás el altar delante del velo que está junto al arca del Testimonio y ante el propiciatorio que cubre el Testimonio, donde yo me encontraré contigo.

[[exodus-30-7]]
^7^ Aarón quemará en él incienso aromático; lo quemará todas la mañanas, al preparar las lámparas,

[[exodus-30-8]]
^8^ y lo quemará también cuando al atardecer alimente las lámparas. Será incienso continuo ante Yahveh, de generación en generación.

[[exodus-30-9]]
^9^ No ofrezcáis sobre él incienso profano, ni holocausto ni oblación, ni derraméis sobre él libación alguna.

[[exodus-30-10]]
^10^ Aarón una vez al año hará expiación sobre los cuernos de este altar. Con la sangre del sacrificio por el pecado, es decir, el de la expiación, una vez cada año hará expiación por él en vuestras sucesivas generaciones. Cosa sacratísima es el altar en honor de Yahveh.

[[exodus-30-11]]
^11^ Habló Yahveh a Moisés, diciendo:

[[exodus-30-12]]
^12^ Cuando cuentes el número de los israelitas para hacer su censo, cada uno pagará a Yahveh el rescate por su vida al ser empadronado, para que no haya plaga entre ellos con motivo del empadronamiento.

[[exodus-30-13]]
^13^ Esto es lo que ha de dar cada uno de los comprendidos en el censo: medio siclo, en siclos del Santuario. Este siclo es de veinte óbolos. El tribruto reservado a Yahveh es medio siclo.

[[exodus-30-14]]
^14^ Todos los comprendidos en el censo, de veinte años en adelante, pagarán el tributo reservado a Yahveh.

[[exodus-30-15]]
^15^ El rico no dará más, ni el pobre menos del medio siclo, al pagar el tributo a Yahveh como rescate de vuestras vidas.

[[exodus-30-16]]
^16^ Tomarás el dinero del rescate de parte de los israelitas, y lo darás para el servicio de la Tienda del Encuenro; y será para los israelitas como recordatorio ante Yahveh por el rescate de sus vidas.

[[exodus-30-17]]
^17^ Habló Yahveh a Moisés, diciendo:

[[exodus-30-18]]
^18^ Haz una pila de bronce, con su base de bronce, para las abluciones. Colócala entre la Tienda del Encuentro y el altar, y echa agua en ella,

[[exodus-30-19]]
^19^ para que Aarón y sus hijos se laven las manos y los pies con su agua.

[[exodus-30-20]]
^20^ Antes de entrar en la Tienda del Encuentro se han de lavar con agua para que no mueran; también antes de acercarse al altar para el ministerio de quemar los manjares que se abrasan en honor de Yahveh.

[[exodus-30-21]]
^21^ Se lavarán las manos y los pies, y no morirán. Este será decreto perpetuo para ellos, para Aarón y su posteridad, de generación en generación.

[[exodus-30-22]]
^22^ Habló Yahveh a Moisés, diciendo:

[[exodus-30-23]]
^23^ Toma tú aromas escogidos: de mirra pura, quinientos siclos; de cinamomo, la mitad, o sea, 250; de caña aromática, 250;

[[exodus-30-24]]
^24^ de casia, quinientos, en siclos del Santuario, y un sextario de aceite de oliva.

[[exodus-30-25]]
^25^ Prepararás con ello el óleo para la unción sagrada, perfume aromático como lo prepara el perfumista. Este será el óleo para la unción sagrada.

[[exodus-30-26]]
^26^ Con él ungirás la Tienda del Encuentro y el arca del Testimonio,

[[exodus-30-27]]
^27^ la mesa con todos sus utensilios, el candelabro con todos sus utensilios, el altar del incienso,

[[exodus-30-28]]
^28^ el altar del holocausto con todos sus utensilios y la pila con su base.

[[exodus-30-29]]
^29^ Así los consagrarás y serán cosa sacratísima. Todo cuanto los toque quedará santificado.

[[exodus-30-30]]
^30^ Ungirás también a Aarón y a sus hijos y los consagrarás para que ejerzan mi sacerdocio.

[[exodus-30-31]]
^31^ Hablarás a los israelitas, diciendo: Este será para vosotros el óleo de la unción sagrada de generación en generación.

[[exodus-30-32]]
^32^ No debe derramarse sobre el cuerpo de ningún hombre; no haréis ningún otro de composición parecida a la suya. Santo es y lo tendréis por cosa sagrada.

[[exodus-30-33]]
^33^ Cualquiera que prepare otro semejante, o derrame de él sobre un laico, será exterminado de su pueblo.

[[exodus-30-34]]
^34^ Dijo Yahveh a Moisés: Procúrate en cantidades iguales aromas: estacte, uña marina y gálbano, especias aromáticas e incienso puro.

[[exodus-30-35]]
^35^ Prepara con ello, según el arte del perfumista, un incienso perfumado, sazonado con sal, puro y santo;

[[exodus-30-36]]
^36^ pulverizarás una parte que pondrás delante del Testimonio, en la Tienda del Encuentro, donde yo me encontraré contigo. Será para vosotros cosa sacratísima.

[[exodus-30-37]]
^37^ Y en cuanto a la composición de este incienso que vas a hacer, no la imitéis para vuestro uso. Lo tendrás por consagrado a Yahveh.

[[exodus-30-38]]
^38^ Cualquiera que prepare otro semejante para aspirar su fragancia, será exterminado de en medio de su pueblo.
[[exodus-31]]
== Capítulo 31

[[exodus-31-1]]
^1^ Habló Yahveh a Moisés diciendo:

[[exodus-31-2]]
^2^ Mira que he designado a Besalel, hijo de Urí, hijo de Jur, de la tribu de Judá;

[[exodus-31-3]]
^3^ y le he llenado del espíritu de Dios concediéndole habilidad, pericia y experiencia en toda clase de trabajos;

[[exodus-31-4]]
^4^ para concebir y realizar proyectos en oro, plata y bronce;

[[exodus-31-5]]
^5^ para labrar piedras de engaste, tallar la madera y ejecutar cualquier otra labor.

[[exodus-31-6]]
^6^ Mira que yo le he dado por colaborador a Oholiab, hijo de Ajisamak, de la tribu de Dan; y además, en el corazón de todos los hombres hábiles he infundido habilidad para que hagan todo lo que te he mandado:

[[exodus-31-7]]
^7^ la Tienda del Encuentro, el arca del Testimonio, el propiciatorio que la cubre y todos los utensilios de la Tienda;

[[exodus-31-8]]
^8^ la mesa con sus utensilios, el candelabro con todos sus utensilios, el altar del incienso,

[[exodus-31-9]]
^9^ el altar del holocausto con todos sus utensilios, la pila con su base;

[[exodus-31-10]]
^10^ las vestiduras de ceremonia, las vestiduras sagradas del sacerdote Aarón, y las vestiduras de sus hijos para las funciones sacerdotales:

[[exodus-31-11]]
^11^ el óleo de la unción y el incienso aromático para el Santuario. Ellos lo harán conforme a todo lo que te he ordenado.

[[exodus-31-12]]
^12^ Habló Yahveh a Moisés diciendo:

[[exodus-31-13]]
^13^ Habla tú a los israelitas y diles: No dejéis de guardar mis sábados; porque el sábado es una señal entre yo y vosotros, de generación en generación, para que sepáis que yo, Yahveh, soy el que os santifico.

[[exodus-31-14]]
^14^ Guardad el sábado, porque es sagrado para vosotros. El que lo profane morirá. Todo el que haga algún trabajo en él será exterminado de en medio de su pueblo.

[[exodus-31-15]]
^15^ Seis días se trabajará; pero el día séptimo será día de descanso completo, consagrado a Yahveh. Todo aquel que trabaje en sábado, morirá.

[[exodus-31-16]]
^16^ Los israelitas guardarán el sábado celebrándolo de generación en generación como alianza perpetua.

[[exodus-31-17]]
^17^ Será entre yo y los israelitas una señal perpetua; pues en seis días hizo Yahveh los cielos y la tierra, y el día séptimo descansó y tomó respiro.

[[exodus-31-18]]
^18^ Después de hablar con Moisés en el monte Sinaí, le dio las dos tablas del Testimonio, tablas de piedra, escritas por el dedo de Dios.
[[exodus-32]]
== Capítulo 32

[[exodus-32-1]]
^1^ Cuando el pueblo vio que Moisés tardaba en bajar del monte, se reunió el pueblo en torno a Aarón y le dijeron: «Anda, haznos un dios que vaya delante de nosotros, ya que no sabemos qué ha sido de Moisés, el hombre que nos sacó de la tierra de Egipto».

[[exodus-32-2]]
^2^ Aarón les respondió: «Quitad los pendientes de oro de las orejas de vuestras mujeres, de vuestros hijos y vuestras hijas, y traédmelos».

[[exodus-32-3]]
^3^ Y todo el pueblo se quitó los pendientes de oro que llevaba en las orejas, y los entregó a Aarón.

[[exodus-32-4]]
^4^ Los tomó él de sus manos, hizo un molde y fundió un becerro. Entonces ellos exclamaron: «Este es tu Dios, Israel, el que te ha sacado de la tierra de Egipto».

[[exodus-32-5]]
^5^ Viendo esto Aarón, erigió un altar ante el becerro y anunció: «Mañana habrá fiesta en honor de Yahveh».

[[exodus-32-6]]
^6^ Al día siguiente se levantaron de madrugada y ofrecieron holocaustos y presentaron sacrificios de comunión. Luego se sentó el pueblo a comer y beber, y después se levantaron para solazarse.

[[exodus-32-7]]
^7^ Entonces habló Yahveh a Moisés, y dijo: «¡Anda, baja! Porque tu pueblo, el que sacaste de la tierra de Egipto, ha pecado.

[[exodus-32-8]]
^8^ Bien pronto se han apartado el camino que yo les había prescrito. Se han hecho un becerro fundido y se han postrado ante él; le han ofrecido sacrificios y han dicho: “Este es tu Dios, Israel, el que te ha sacado de la tierra de Egipto.”»

[[exodus-32-9]]
^9^ Y dijo Yahveh a Moisés: «Ya veo que este pueblo es un pueblo de dura cerviz.

[[exodus-32-10]]
^10^ Déjame ahora que se encienda mi ira contra ellos y los devore; de ti, en cambio, haré un gran pueblo».

[[exodus-32-11]]
^11^ Pero Moisés trató de aplacar a Yahveh su Dios, diciendo: “¿Por qué, oh Yahveh, ha de encenderse tu ira contra tu pueblo, el que tú sacaste de la tierra de Egipto con gran poder y mano fuerte?

[[exodus-32-12]]
^12^ ¿Van a poder decir los egipcios: Por malicia los ha sacado, para matarlos en las montañas y exterminarlos de la faz de la tierra? Abandona el ardor de tu cólera y renuncia a lanzar el mal contra tu pueblo.

[[exodus-32-13]]
^13^ Acuérdate de Abraham, de Isaac y de Israel, siervos tuyos, a los cuales juraste por ti mismo: Multiplicaré vuestra descendencia como las estrellas del cielo; toda esta tierra que os tengo prometida, la daré a vuestros descendientes, y ellos la poseerán como herencia para siempre».

[[exodus-32-14]]
^14^ Y Yahveh renunció a lanzar el mal con que había amenazado a su pueblo.

[[exodus-32-15]]
^15^ Volvióse Moisés y bajó del monte, con las dos tablas del Testimonio en su mano, tablas escritas por ambos lados; por una y otra cara estaban escritas.

[[exodus-32-16]]
^16^ Las tablas eran obra de Dios, y la escritura, grabada sobre las mismas, era escritura de Dios.

[[exodus-32-17]]
^17^ Cuando Josué oyó la voz del pueblo que gritaba, dijo a Moisés: «Gritos de guerra en el campamento».

[[exodus-32-18]]
^18^ Respondió Moisés: «No son gritos de victoria, ni alarido de derrota. Cantos a coro es lo que oigo».

[[exodus-32-19]]
^19^ Cuando Moisés llegó cerca del campamento y vio el becerro y las danzas, ardió en ira, arrojó de su mano las tablas y las hizo añicos al pie del monte.

[[exodus-32-20]]
^20^ Luego tomó el becerro que habían hecho, lo quemó y lo molió hasta redurcirlo a polvo, que esparció en el agua, y se lo dio a beber a los israelitas.

[[exodus-32-21]]
^21^ Y dijo Moisés a Aarón: «¿Qué te hizo este pueblo para que hayas traído sobre él tan gran pecado?»

[[exodus-32-22]]
^22^ Aarón respondió: «No se encienda la ira de mi señor. Tú mismo sabes que este pueblo es inclinado al mal.

[[exodus-32-23]]
^23^ Me dijeron: “Haznos un dios que vaya delante de nosotros, ya que no sabemos qué le ha sucedido a Moisés, el hombre que nos sacó de la tierra de Egipto.”

[[exodus-32-24]]
^24^ Yo les contesté: “El que tenga oro despréndase.” Ellos se lo quitaron y me lo dieron; yo lo eché al fuego y salió este becerro».

[[exodus-32-25]]
^25^ Vio Moisés al pueblo desenfrenado - pues Aarón les había permitido entregarse a la idolatría en medio de sus adversarios -

[[exodus-32-26]]
^26^ y se puso Moisés a la puerta del campamento, y exclamó: «¡A mí los de Yahveh!» y se le unieron todos los hijos de Leví.

[[exodus-32-27]]
^27^ El les dijo: «Así dice Yahveh, el Dios de Israel: Cíñase cada uno su espada al costado; pasad y repasad por el campamento de puerta en puerta, y matad cada uno a su hermano, a su amigo y a su pariente».

[[exodus-32-28]]
^28^ Cumplieron los hijos de Leví la orden de Moisés; y cayeron aquel día unos 3000 hombres del pueblo.

[[exodus-32-29]]
^29^ Y dijo Moisés: «Hoy habéis recibido la investidura como sacerdotes de Yahveh, cada uno a costa de vuestros hijos y vuestros hermanos, para que él os dé hoy la bendición».

[[exodus-32-30]]
^30^ Al día siguiente dijo Moisés al pueblo: «Habéis cometido un gran pecado. Yo voy a subir ahora donde Yahveh; acaso pueda obtener la expiación de vuestro pecado».

[[exodus-32-31]]
^31^ Volvió Moisés donde Yahveh y dijo: «¡Ay! Este pueblo ha cometido un gran pecado al hacerse un dios de oro.

[[exodus-32-32]]
^32^ Con todo, si te dignas perdonar su pecado..., y si no, bórrame del libro que has escrito».

[[exodus-32-33]]
^33^ Yahveh respondió a Moisés: Al que peque contra mí, le borraré yo de mi libro.

[[exodus-32-34]]
^34^ Ahora ve y conduce al pueblo adonde te he dicho. He aquí que mi ángel irá delante de ti, mas en el día de mi visita los castigaré yo por su pecado».

[[exodus-32-35]]
^35^ Y Yahveh castigó al pueblo a causa del becerro fabricado por Aarón.
[[exodus-33]]
== Capítulo 33

[[exodus-33-1]]
^1^ Dijo Yahveh a Moisés: «Anda, sube de aquí, tú y el pueblo que sacaste de Egipto, a la tierra que yo prometí con juramento a Abraham, a Isaac y a Jacob, diciendo: “A tu posteridad se la daré.”

[[exodus-33-2]]
^2^ Enviaré delante de ti un ángel y expulsaré al cananeo, al amorreo, al hitita, al perizita, al jivita y al jebuseo.

[[exodus-33-3]]
^3^ Sube a una tierra que mana leche y miel; que yo no subiré contigo, pues eres un pueblo de dura cerviz; no sea que te destruya en el camino».

[[exodus-33-4]]
^4^ Al oír el pueblo estas duras palabras, hizo duelo y nadie se vistió sus galas.

[[exodus-33-5]]
^5^ Dijo entonces Yahveh a Moisés: «Di a los israelitas: Vosotros sois un pueblo de dura cerviz. Si yo saliera contigo, aunque fuera un solo momento, te destruiría. Ahora, pues, quítate tus galas, para que yo sepa qué he de hacer contigo».

[[exodus-33-6]]
^6^ Y los israelitas se despojaron de sus galas a partir del monte Horeb.

[[exodus-33-7]]
^7^ Tomó Moisés la Tienda y la plantó para él a cierta distancia fuera del campamento; la llamó Tienda del Encuentro. De modo que todo el que tenía que consultar a Yahveh salía hacia la Tienda del Encuentro, que estaba fuera del campamento.

[[exodus-33-8]]
^8^ Cuando salía Moisés hacia la Tienda, todo el pueblo se levantaba y se quedaba de pie a la puerta de su tienda, siguiendo con la vista a Moisés hasta que entraba en la Tienda.

[[exodus-33-9]]
^9^ Y una vez entrado Moisés en la tienda, bajaba la columna de nube y se detenía a la puerta de la Tienda, mientras Yahveh hablaba con Moisés.

[[exodus-33-10]]
^10^ Todo el pueblo veía la columna de nube detenida a la puerta de la Tienda y se levantaba el pueblo, y cada cual se postraba junto a la puerta de su tienda.

[[exodus-33-11]]
^11^ Yahveh hablaba con Moisés cara a cara, como habla un hombre con su amigo. Luego volvía Moisés al campamento, pero su ayudante, el joven Josué, hijo de Nun, no se apartaba del interior de la Tienda.

[[exodus-33-12]]
^12^ Dijo Moisés a Yahveh: «Mira, tú me dices: Haz subir a este pueblo; pero no me has indicado a quién enviarás conmigo; a pesar de que me has dicho: “Te conozco por tu nombre”, y también: “Has hallado gracia a mis ojos.”

[[exodus-33-13]]
^13^ Ahora, pues, si realmente he hallado gracia a tus ojos, hazme saber tu camino, para que yo te conozca y halle gracia a tus ojos, y mira que esta gente es tu pueblo».

[[exodus-33-14]]
^14^ Respondió él: «Yo mismo iré contigo y te daré descanso».

[[exodus-33-15]]
^15^ Contestóle: «Si no vienes tú mismo, no nos hagas partir de aquí.

[[exodus-33-16]]
^16^ Pues ¿en qué podrá conocerse que he hallado gracia a tus ojos, yo y tu pueblo, sino en eso, en que tú marches con nosotros? Así nos distinguiremos, yo y tu pueblo, de todos los pueblos que hay sobre la tierra».

[[exodus-33-17]]
^17^ Respondió Yahveh a Moisés: «Haré también esto que me acabas de pedir, pues has hallado gracia a mis ojos, y yo te conozco por tu nombre».

[[exodus-33-18]]
^18^ Entonces dijo Moisés: «Déjame ver, por favor, tu gloria».

[[exodus-33-19]]
^19^ El le contestó: «Yo haré pasar ante tu vista toda mi bondad y pronunciaré delante de ti el nombre de Yahveh; pues hago gracia a quien hago gracia y tengo misericordia con quien tengo misericordia».

[[exodus-33-20]]
^20^ Y añadió: «Pero mi rostro no podrás verlo; porque no puede verme el hombre y seguir viviendo».

[[exodus-33-21]]
^21^ Luego dijo Yahveh: «Mira, hay un lugar junto a mí; tú te colocarás sobre la peña.

[[exodus-33-22]]
^22^ Y al pasar mi gloria, te pondré en una hendidura de la peña y te cubriré con mi mano hasta que yo haya pasado.

[[exodus-33-23]]
^23^ Luego apartaré mi mano, para que veas mis espaldas; pero mi rostro no se puede ver».
[[exodus-34]]
== Capítulo 34

[[exodus-34-1]]
^1^ Dijo Yahveh a Moisés. «Labra dos tablas de piedra como las primeras, sube donde mí, al monte y yo escribiré en las tablas las palabras que había en las primeras tablas que rompiste.

[[exodus-34-2]]
^2^ Prepárate para subir mañana temprano al monte Sinaí; allí en la cumbre del monte te presentarás a mí.

[[exodus-34-3]]
^3^ Que nadie suba contigo, ni aparezca nadie en todo el monte. Ni oveja ni buey paste en el monte».

[[exodus-34-4]]
^4^ Labró Moisés dos tablas de piedra como las primeras y, levantándose de mañana, subió al monte Sinaí como le había mandado Yahveh, llevando en su mano las dos tablas de piedra.

[[exodus-34-5]]
^5^ Descendió Yahveh en forma de nube y se puso allí junto a él. Moisés invocó el nombre de Yahveh.

[[exodus-34-6]]
^6^ Yahveh pasó por delante de él y exclamó: «Yahveh, Yahveh, Dios misericordioso y clemente, tardo a la cólera y rico en amor y fidelidad,

[[exodus-34-7]]
^7^ que mantiene su amor por millares, que perdona la iniquidad, la rebeldía y el pecado, pero no los deja impunes; que castiga la iniquidad de los padres en los hijos y en los hijos de los hijos hasta la tercera y cuarta generación».

[[exodus-34-8]]
^8^ Al instante, Moisés cayó en tierra de rodillas y se postró,

[[exodus-34-9]]
^9^ diciendo: «Si en verdad he hallado gracia a tus ojos, oh Señor, dígnese mi Señor venir en medio de nosotros, aunque sea un pueblo de dura cerviz; perdona nuestra iniquidad y nuestro pecado, y recíbenos por herencia tuya».

[[exodus-34-10]]
^10^ Respondió él: «Mira, voy a hacer una alianza; realizaré maravillas delante de todo tu pueblo, cono nunca se han hecho en toda la tierra ni en nación alguna; y todo el pueblo que te rodea verá la obra de Yahveh; porque he de hacer por medio de ti cosas que causen temor.

[[exodus-34-11]]
^11^ Observa bien lo que hoy te mando. He aquí que voy a expulsar delante de ti al amorreo, al cananeo, al hitita, al perizita, al jivita y al jebuseo.

[[exodus-34-12]]
^12^ Guárdate de hacer pacto con los habitantes del país en que vas a entrar, para que no sean un lazo en medio de ti.

[[exodus-34-13]]
^13^ Al contrario, destruiréis sus altares, destrozaréis sus estelas y romperéis sus cipos.

[[exodus-34-14]]
^14^ No te postrarás ante ningún otro dios, pues Yahveh se llama Celoso, es un Dios celoso.

[[exodus-34-15]]
^15^ No hagas pacto con los moradores de aquella tierra, no sea que cuando se prostituyan tras sus dioses y les ofrezcan sacrificios, te inviten a ti y tú comas de sus sacrificios;

[[exodus-34-16]]
^16^ y no sea que tomes sus hijas para tus hijos, y que al prostituirse sus hijas tras sus dioses, hagan también que tus hijos se prostituyan tras los dioses de ellas.

[[exodus-34-17]]
^17^ No te harás dioses de fundición.

[[exodus-34-18]]
^18^ Guardarás la fiesta de los Azimos; siete días comerás ázimos como te he mandado, al tiempo señalado, esto es, en el mes de Abib, pues en el mes de Abib saliste de Egipto.

[[exodus-34-19]]
^19^ Todo lo que abre el seno es mío, todo primer nacido, macho, sea de vaca o de oveja, es mío.

[[exodus-34-20]]
^20^ El primer nacido de asno lo rescatarás con una oveja; y si no lo rescatas, lo desnucarás. Rescatarás todos los primogénitos de tus hijos, y nadie se presentará ante mí con las manos vacías.

[[exodus-34-21]]
^21^ Seis días trabajarás, mas en el séptimo descansarás; descansarás en tiempo de siembra y siega.

[[exodus-34-22]]
^22^ Celebrarás la fiesta de las Semanas: la de las primicias de la siega del trigo, y también la fiesta de la recolección al final del año.

[[exodus-34-23]]
^23^ Tres vecees al año se presentarán todos tus varones ante Yahveh, el Señor, el Dios de Israel.

[[exodus-34-24]]
^24^ Pues cuando yo expulse a los pueblos delante de ti y ensanche tus fronteras, nadie codiciará tu tierra cuando tres veces al año subas a presentarte ante Yahveh, tu Dios.

[[exodus-34-25]]
^25^ No inmolarás con pan fermentado la sangre de mi sacrificio, ni quedará hasta el día siguiente la víctima de la fiesta de Pascua.

[[exodus-34-26]]
^26^ Llevarás a la casa de Yahveh, tu Dios, lo mejor de las primicias de los frutos de tu suelo. No cocerás el cabrito en la leche de su madre».

[[exodus-34-27]]
^27^ Dijo Yahveh a Moisés: «Consigna por escrito estas palabras, pues a tenor de ellas hago alianza contigo y con Israel».

[[exodus-34-28]]
^28^ Moisés estuvo allí con Yahveh cuarenta días y cuarenta noches, sin comer pan ni beber agua. Y escribió en las tablas las palabras de la alianza, las diez palabras.

[[exodus-34-29]]
^29^ Luego, bajó Moisés del monte Sinaí y, cuando bajó del monte con las dos tablas del Testimonio en su mano, no sabía que la piel de su rostro se había vuelto radiante, por haber hablado con él.

[[exodus-34-30]]
^30^ Aarón y todos los israelitas miraron a Moisés, y al ver que la piel de su rostro irradiaba, temían acercarse a él.

[[exodus-34-31]]
^31^ Moisés los llamó. Aarón y todos los jefes de la comunidad se volvieron a él y Moisés habló con ellos.

[[exodus-34-32]]
^32^ Se acercaron a continuación todos los israelitas y él les conminó cuanto Yahveh le había dicho en el monte Sinaí.

[[exodus-34-33]]
^33^ Cuando Moisés acabó de hablar con ellos, se puso un velo sobre el rostro.

[[exodus-34-34]]
^34^ Siempre que Moisés se presentaba delante de Yahveh para hablar con él, se quitaba el velo hasta que salía, y al salir decía a los israelitas lo que Yahveh había ordenado.

[[exodus-34-35]]
^35^ Los israelitas veían entonces que el rostro de Moisés irradiaba, y Moisés cubría de nuevo su rostro hasta que entraba a hablar con Yahveh.
[[exodus-35]]
== Capítulo 35

[[exodus-35-1]]
^1^ Moisés reunió a toda la comunidad de los israelitas y les dijo: «Esto es lo que Yahveh ha mandado hacer.

[[exodus-35-2]]
^2^ Durante seis días se trabajará, pero el día séptimo será sagrado para vosotros, día de descanso completo en honor de Yahveh. Cualquiera que trabaje en ese día, morirá.

[[exodus-35-3]]
^3^ En ninguna de vuestras moradas encenderéis fuego en día de sábado».

[[exodus-35-4]]
^4^ Moisés habló así a toda la comunidad de los israelitas: «Esta es la orden de Yahveh:

[[exodus-35-5]]
^5^ Reservad de vuestros bienes una ofrenda para Yahveh. Que reserven ofrenda para Yahveh todos aquellos a quienes su corazón mueva: oro, plata y bronce,

[[exodus-35-6]]
^6^ púrpura violeta y escarlata, carmesí, lino fino, pelo de cabra,

[[exodus-35-7]]
^7^ pieles de carnero teñidas de rojo, cueros finos y maderas de acacia,

[[exodus-35-8]]
^8^ aceite para el alumbrado, aromas para el óleo de la unción y para el incienso aromático,

[[exodus-35-9]]
^9^ piedras de ónice y piedras de engaste para el efod y el pectoral.

[[exodus-35-10]]
^10^ Que vengan los artífices hábiles de entre vosotros a realizar cuanto Yahveh ha ordenado:

[[exodus-35-11]]
^11^ la Morada, su Tienda y su toldo, sus broches, sus tableros, sus travesaños, sus postes y sus basas;

[[exodus-35-12]]
^12^ el Arca y sus varales, el propiciatorio y el velo que lo cubre;

[[exodus-35-13]]
^13^ la mesa con sus varales y todos sus utensilios, el pan de la Presencia,

[[exodus-35-14]]
^14^ el candelabro para el alumbrado con sus utensilios, y sus lámparas, y el aceite del alumbrado;

[[exodus-35-15]]
^15^ el altar del incienso con sus varales; el óleo de la unción, el incienso aromático, la cortina del vano de la entrada a la Morada,

[[exodus-35-16]]
^16^ el altar de los holocaustos con su rejilla de bronce, sus varales y todos su utensilios; la pila con su base;

[[exodus-35-17]]
^17^ los cortinajes del atrio con sus postes y sus basas; el tapiz de la entrada del atrio;

[[exodus-35-18]]
^18^ la clavazón de la Morada y la clavazón del atrio y sus cuerdas;

[[exodus-35-19]]
^19^ los ornamentos de ceremonia para oficiar en el Santuario; las vestiduras sagradas para el sacerdote Aarón y las vestiduras de sus hijos para sus funciones sacerdotales».

[[exodus-35-20]]
^20^ Entonces, toda la comunidad de los israelitas se retiró de la presencia de Moisés;

[[exodus-35-21]]
^21^ todos aquellos a quienes impulsaba su corazón y movía su espíritu vinieron a traer la ofrenda reservada a Yahveh, para los trabajos de la Tienda del Encuentro, para todo su servicio y para las vestiduras sagradas.

[[exodus-35-22]]
^22^ Venían hombres y mujeres: todos los que eran movidos por su corazón traían zarcillos, pendientes, anillos de oro, el oro que cada uno presentaba como ofrenda mecida para Yahveh.

[[exodus-35-23]]
^23^ Cuantos poseían púrpura violeta y escarlata, y carmesí, lino fino, pelo de cabra, pieles de carnero teñidas de rojo y cueros finos, los traían también.

[[exodus-35-24]]
^24^ Cuantos pudieron reservar una ofrenda de plata o de bronce, la llevaron como ofrenda reservada a Yahveh. Lo mismo hicieron los que poseían madera de acacia, que sirviera para los trabajos de la obra.

[[exodus-35-25]]
^25^ Todas las mujeres hábiles en el oficio hilaron con sus manos y llevaron la púrpura violeta y escarlata, el carmesí y lino fino que habían hilado.

[[exodus-35-26]]
^26^ Todas las mujeres hábiles en hilar, hilaron pelo de cabra, movidas por su corazón.

[[exodus-35-27]]
^27^ Los jefes trajeron piedras de ónice y piedras de engaste para el efod y el pectoral;

[[exodus-35-28]]
^28^ aromas y aceite para el alumbrado, para el óleo de la unción y para el incienso aromático.

[[exodus-35-29]]
^29^ Todos los israelitas, hombres y mujeres, cuyo corazón les había impulsado a llevar algo para cualquiera de los trabajos que Yahveh, por medio de Moisés, les había encomendado, presentaron sus ofrendas voluntarias a Yahveh.

[[exodus-35-30]]
^30^ Moisés dijo entonces a los israelitas: «Mirad, Yahveh ha designado a Besalel, hijo de Urí, hijo de Jur, de la tribu de Judá,

[[exodus-35-31]]
^31^ y le ha llenado del espíritu de Dios, confiriéndole habilidad, pericia y experiencia en toda clase de trabajos,

[[exodus-35-32]]
^32^ para concebir y realizar proyectos en oro, plata y bronce,

[[exodus-35-33]]
^33^ para labrar piedras de engaste, tallar la madera y ejecutar cualquier otra labor de artesanía;

[[exodus-35-34]]
^34^ a él y Oholiab, hijo de Ajisamak de la tribu de Dan, les ha puesto en el corazón el don de enseñar.

[[exodus-35-35]]
^35^ Les ha llenado de habilidad para toda clase de labores en talla y bordado, en recamado de púrpura violeta y escarlata, de carmesí y lino fino, y en labores de tejidos. Son capaces de ejecutar toda clase de trabajos y de idear proyectos».
[[exodus-36]]
== Capítulo 36

[[exodus-36-1]]
^1^ Así, pues, Besalel, Oholiab y todos los hombres hábiles en quienes Yahveh había infundido habilidad y pericia para saber realizar todos los trabajos en servicio del Santuario, ejecutaron todo conforme había mandado Yahveh.

[[exodus-36-2]]
^2^ LLamó Moisés a Besalel y a Oholiab y a todos los hombres hábiles en cuyo corazón Yahveh había infundido habilidad, a todos los que su corazón movía a ponerse al trabajo para realizarlo.

[[exodus-36-3]]
^3^ Recibieron de Moisés todas las ofrendas que los israelitas habían reservado para la ejecución de la obra del Santuario. Entre tanto los israelitas seguían entregando a Moisés cada mañana ofrendas voluntarias.

[[exodus-36-4]]
^4^ Por eso, todos los artífices dedicados a los trabajos del Santuario dejaron cada cual su trabajo,

[[exodus-36-5]]
^5^ y fueron a hablar con Moisés, diciendo: «El pueblo entrega más de lo que se precisa para la realización de las obras que Yahveh ha mandado hacer».

[[exodus-36-6]]
^6^ Entonces Moisés mandó correr la voz por el campamento: «Ni hombre ni mujer reserve ya más ofrendas para el Santuario». Suspendió el pueblo su aportación,

[[exodus-36-7]]
^7^ pues había material suficiente para ejecutar todos los trabajos; y aun sobraba.

[[exodus-36-8]]
^8^ Entonces los artífices más expertos de entre los que ejecutaban el trabajo hicieron la Morada. La hizo con diez tapices de lino fino torzal, de púrpura violeta y escarlata y de carmesí con querubines bordados.

[[exodus-36-9]]
^9^ La longitud de cada tapiz era de veintiocho codos y la anchura de cuatro. Todos los tapices tenían las mismas medias.

[[exodus-36-10]]
^10^ Unió cinco tapices entre sí y lo mismo los otros cinco.

[[exodus-36-11]]
^11^ Puso lazos de púrpura violeta en el borde del tapiz con que termina el primer conjunto; los puso también en el borde del tapiz con que termina el segundo conjunto.

[[exodus-36-12]]
^12^ Puso cincuenta lazos en el primer tapiz y otros cincuenta en el borde del último tapiz del segundo conjunto, correspondiéndose los lazos unos a otros.

[[exodus-36-13]]
^13^ Hizo también cincuenta broches de oro, y con los broches enlazó entre sí los tapices, de modo que la Morada vino a formar un espacio único.

[[exodus-36-14]]
^14^ Tejió también piezas de pelo de cabra para que, a modo de tienda, cubrieran la Morada. Tejió once de estas piezas.

[[exodus-36-15]]
^15^ La longitud de cada pieza era de treinta codos y de cuatro la anchura. Las once piezas tenían las mismas medidas.

[[exodus-36-16]]
^16^ Juntó cinco piezas en una parte y seis en la otra.

[[exodus-36-17]]
^17^ Hizo cincuenta lazos en el borde de la última pieza del primer conjunto, y cincuenta lazos en el borde de la última pieza del segundo conjunto.

[[exodus-36-18]]
^18^ Hizo cincuenta broches de bronce para unir la Tienda, formando un espacio único.

[[exodus-36-19]]
^19^ Hizo además para la Tienda un toldo de pieles de carnero teñidas de rojo, y encima otro toldo de cueros finos.

[[exodus-36-20]]
^20^ Para la Morada hizo los tableros de madera de acacia y los puso de pie.

[[exodus-36-21]]
^21^ Cada tablero tenía diez codos de largo, y codo y medio de ancho.

[[exodus-36-22]]
^22^ Tenía además dos espigas paralelas. Hizo lo mismo todos los tableros de la Morada.

[[exodus-36-23]]
^23^ Puso los tableros para la Morada: veinte para el flanco del Négueb, hacia el sur;

[[exodus-36-24]]
^24^ hizo cuarenta basas de plata para colocarlas debajo de los veinte tableros: dos basas debajo de un tablero para sus dos espigas y dos basas debajo del otro tablero para sus dos espigas.

[[exodus-36-25]]
^25^ Para el segundo flanco de la Morada, la parte del norte, hizo otros veinte tableros,

[[exodus-36-26]]
^26^ con sus cuarenta basas de plata; dos basas debajo de un tablero y dos basas debajo del otro tablero.

[[exodus-36-27]]
^27^ Para la parte posterior de la Morada, hacia el occidente, hizo seis tableros;

[[exodus-36-28]]
^28^ para los ángulos de la Morada en su parte posterior, dos más,

[[exodus-36-29]]
^29^ que estaban unidos desde abajo hasta arriba, hasta la primera anilla. Así lo hizo con los dos tableros destinados a los dos ángulos.

[[exodus-36-30]]
^30^ Eran, pues, ocho tableros con sus basas de plata; dieciséis basas, dos debajo de cada tablero.

[[exodus-36-31]]
^31^ Después hizo travesaños de madera de acacia: cinco travesaños para los tableros de un flanco de la Morada;

[[exodus-36-32]]
^32^ y cinco travesaños para los tableros del otro flanco de la Morada; y otros cinco para los tableros de la parte posterior de la Morada hacia el occidente.

[[exodus-36-33]]
^33^ Hizo el travesaño central de tal suerte que pasase a media altura de los tableros, de un extremo al otro.

[[exodus-36-34]]
^34^ Revistió de oro los tableros; de oro hizo también sus anillas para pasar los travesaños, y los revistió igualmente de oro.

[[exodus-36-35]]
^35^ Hizo el velo de púrpura violeta y escarlata, de carmesí y lino fino torzal; bordó en él unos querubines.

[[exodus-36-36]]
^36^ Hizo para colgarlo cuatro postes de acacia, revestidos de oro y provistos de ganchos de oro; fundió para ellos cuatro basas de plata.

[[exodus-36-37]]
^37^ Hizo para la entrada de la Tienda una cortina de púrpura violeta y escarlata, de carmesí y lino fino torzal, labor de recamador,

[[exodus-36-38]]
^38^ con sus cinco postes y sus ganchos. Revistió de oro sus capiteles y sus varillas y fundió en bronce sus cinco basas.
[[exodus-37]]
== Capítulo 37

[[exodus-37-1]]
^1^ Besalel hizo el arca de madera de acacia, de dos codos y medio de largo, codo y medio de ancho, y codo y medio de alto.

[[exodus-37-2]]
^2^ La revistió de oro puro, por dentro y por fuera, y además puso en su derredor una moldura de oro.

[[exodus-37-3]]
^3^ Fundió cuatro anillas de oro para sus cuatro pies, dos anillas a un costado y dos anillas al otro.

[[exodus-37-4]]
^4^ Hizo también varales de madera de acacia, que revistió de oro;

[[exodus-37-5]]
^5^ pasó los varales por las anillas de los costados del arca, para transportarla.

[[exodus-37-6]]
^6^ Después hizo un propiciatorio de oro puro, de dos codos y medio de largo, y de codo y medio de ancho.

[[exodus-37-7]]
^7^ Hizo igualmente dos querubines de oro macizo; los hizo en los dos extremos del propiciatorio;

[[exodus-37-8]]
^8^ el primer querubín en un extremo y el segundo en el otro; hizo los querubines formando un cuerpo con el propiciatorio en sus dos extremos.

[[exodus-37-9]]
^9^ Estaban los querubines con las alas extendidas por encima, cubriendo con ellas el propiciatorio, uno frente al otro, con las caras vueltas hacia el propiciatorio.

[[exodus-37-10]]
^10^ Hizo, además, la mesa de madera de acacia, de dos codos de largo, un codo de ancho y codo y medio de alto.

[[exodus-37-11]]
^11^ La revistió de oro puro y le puso alrededor una moldura de oro.

[[exodus-37-12]]
^12^ Hizo además, en torno de ella, un reborde de una palma de ancho, con una moldura de oro alrededor del mismo.

[[exodus-37-13]]
^13^ Le hizo cuatro anillas de oro y puso las anillas en los cuatro ángulos, correspondientes a sus cuatro pies.

[[exodus-37-14]]
^14^ Junto al reborde se hallabam las anillas para pasar por ellas los varales y transportar la mesa.

[[exodus-37-15]]
^15^ Hizo los varales de madera de acacia y los revistió de oro.

[[exodus-37-16]]
^16^ Asimismo hizo de oro puro los utensilios que habían de estar sobre la mesa; sus fuentes, sus vasos, sus tazas y sus jarros con los que se hacían las libaciones.

[[exodus-37-17]]
^17^ Hizo el candelabro de oro puro. Hizo el candelabro de oro macizo, su pie y su tallo. Sus cálices - corolas y flores - formaban con él un cuerpo.

[[exodus-37-18]]
^18^ De sus lados salían seis brazos: tres brazos de un lado, y tres brazos de otro.

[[exodus-37-19]]
^19^ El primer brazo tenía tres cálices en forma de flor de almendro, con corola y flor; y así los seis brazos que salían del candelabro.

[[exodus-37-20]]
^20^ En el mismo candelabro había cuatro cálices, en forma de flor de almendro, con sus corolas y flores;

[[exodus-37-21]]
^21^ una corola debajo de los dos primeros brazos que formaban cuerpo con él, una corola debajo de los siguientes, y una corola debajo de los dos últimos brazos; así con los seis brazos que salían del mismo.

[[exodus-37-22]]
^22^ Las corolas y los brazos formaban un cuerpo con el candelabro; todo ello formaba un cuerpo de oro puro macizo.

[[exodus-37-23]]
^23^ Hizo también de oro puro sus siete lámparas, sus despabiladeras y sus ceniceros.

[[exodus-37-24]]
^24^ Empleó un talento de oro puro para el candelabro y todos sus utensilios.

[[exodus-37-25]]
^25^ Hizo también de madera de acacia el altar del incienso, de un codo de largo y uno de ancho, cuadrado, y de dos codos de alto. Sus cuernos formaban un solo cuerpo con él.

[[exodus-37-26]]
^26^ Lo revistió de oro puro, por su parte superior, sus costados y también sus cuernos. Puso en su derredor una moldura de oro.

[[exodus-37-27]]
^27^ Y debajo de la moldura, a los costados, hizo dos anillas a sus dos lados, para meter por ellas los varales con que transportarlo.

[[exodus-37-28]]
^28^ Hizo los varales de madera de acacia y los revistió de oro.

[[exodus-37-29]]
^29^ Preparó también el óleo sagrado de la unción, y el incienso aromático puro, como lo prepara el perfumista.
[[exodus-38]]
== Capítulo 38

[[exodus-38-1]]
^1^ Hizo el altar de los holocaustos de madera de acacia, de cinco codos de largo y cinco de ancho, cuadrado, y de tres codos de alto.

[[exodus-38-2]]
^2^ Hizo sobresalir de sus cuatro ángulos unos cuernos que formaban un cuerpo con él, y lo revistió de bronce.

[[exodus-38-3]]
^3^ Hizo, además, todos los utensilios del altar: Los ceniceros, los badiles, los acetres, los tenedores y los braseros. Fundió de bronce todos sus utensilios.

[[exodus-38-4]]
^4^ Fabricó para el altar una rejilla de bronce en forma de red, bajo la cornisa inferior, de modo que llegaba hasta la mitad del altar.

[[exodus-38-5]]
^5^ Fijó cuatro anillas para los cuatro extremos de la rejilla de bronce, para meter los varales.

[[exodus-38-6]]
^6^ Hizo los varales de madera de acacia, y los revistió de bronce,

[[exodus-38-7]]
^7^ y pasó los varales por las anillas a los flancos del altar, para transportarlo así. Hizo el altar hueco, de paneles.

[[exodus-38-8]]
^8^ Hizo la pila y la basa de bronce, con los espejos de las mujeres que servían a la entrada de la Tienda del Encuentro.

[[exodus-38-9]]
^9^ Hizo también el atrio; por el lado del Négueb, hacia el sur, estaba el cortinaje del atrio, de lino fino torzal, de cien codos.

[[exodus-38-10]]
^10^ Sus postes eran veinte, y veintes sus basas de bronce; los ganchos de los postes y sus varillas eran de plata.

[[exodus-38-11]]
^11^ Por el lado septentrional había igualmente un cortinaje de cien codos. Sus postes eran veinte, y veinte sus basas de bronce; los ganchos de los postes y sus varillas eran de plata.

[[exodus-38-12]]
^12^ En el lado occidental había un cortinaje de cincuenta codos. Sus postes eran diez, y diez sus basas; los ganchos de los postes y sus varillas eran de plata.

[[exodus-38-13]]
^13^ En el lado Este, al oriente, colgaban también cincuenta codos de cortinaje.

[[exodus-38-14]]
^14^ El cortinaje era de quince codos, con tres columnas y tres basas, por un lado de la entrada;

[[exodus-38-15]]
^15^ y por el otro lado - a ambos lados de la entrada del atrio - había un cortinaje de quince codos; sus postes eran tres, y tres sus basas.

[[exodus-38-16]]
^16^ Todos los cortinajes del recinto del atrio eran de lino fino torzal.

[[exodus-38-17]]
^17^ Las basas de los postes eran de bronce, sus ganchos y sus varillas de plata. También sus capiteles estaban revestidos de plata, y todos los postes del atrio llevaban varillas de plata.

[[exodus-38-18]]
^18^ El tapiz de la puerta del atrio era labor de recamador y estaba recamado de púrpura violeta y escarlata, de carmesí y lino fino torzal. Tenía veinte codos de largo; su altura - en el ancho - era de cinco codos, lo mismo que los cortinajes del atrio.

[[exodus-38-19]]
^19^ Sus cuatro postes y sus cuatro basas eran de bronce; sus ganchos de plata, como también el revestimiento de sus capiteles y sus varillas.

[[exodus-38-20]]
^20^ Toda la clavazón de la Morada y del atrio que la rodeaba era de bronce.

[[exodus-38-21]]
^21^ Este es el inventario de la Morada, de la Morada del testimonio, realizado por orden de Moisés, y hecho por los levitas bajo la dirección de Itamar, hijo del sacerdote Aarón.

[[exodus-38-22]]
^22^ Besalel, hijo de Urí, hijo de Jur, de la tribu de Judá, hizo todo cuanto Yahveh había mandado a Moisés,

[[exodus-38-23]]
^23^ juntamente con Oholiab, hijo de Ajisamak, de la tribu de Dan, que era artífice, bordador y recamador en púrpura violeta y escarlata, en carmesí y lino fino.

[[exodus-38-24]]
^24^ El total del oro empleado en el trabajo, en todo el trabajo del Santuario, es decir, el oro de la ofrenda reservada, fue de veintinueve talentos y 730 siclos, en siclos del Santuario;

[[exodus-38-25]]
^25^ la plata de los incluidos en el censo de la comunidad, cien talentos y 1.775 siclos, en siclos del Santuario:

[[exodus-38-26]]
^26^ un becá por cabeza, o sea medio siclo, en siclos del Santuario, para cada hombre comprendido en el censo de los 603.550 hombres, de veinte años en adelante.

[[exodus-38-27]]
^27^ Los cien talentos de plata se emplearon en fundir las basas del Santuario y las basas del velo; cien basas correspondientes a los cien talentos, un talento por basa.

[[exodus-38-28]]
^28^ De los 1.775 siclos hizo ganchos para los postes, revistió sus capiteles y los unió con varillas.

[[exodus-38-29]]
^29^ El bronce de la ofrenda reservada fue de setenta talentos y 2.400 siclos.

[[exodus-38-30]]
^30^ Con él hizo las basas para la entrada de la Tienda del Encuentro, el altar de bronce con su rejilla de bronce y todos los utensilios del altar,

[[exodus-38-31]]
^31^ las basas del recinto del atrio y las basas de la entrada del atrio, toda la clavazón de la Morada y toda la clavazón del atrio que la rodeaba.
[[exodus-39]]
== Capítulo 39

[[exodus-39-1]]
^1^ Hicieron para el servicio del Santuario vestiduras de ceremonia de púrpura violeta y escarlata, de carmesí y lino fino. Hicieron también las vestiduras sagradas de Aarón, como Yahveh había mandado a Moisés.

[[exodus-39-2]]
^2^ Hicieron, pues, el efod, de oro, de púrpura violeta y escarlata, de carmesí y lino fino torzal.

[[exodus-39-3]]
^3^ Batieron oro en láminas y las cortaron en hilos para hacer bordado junto con la púrpura violeta y escarlata, con el carmesi y el lino fino.

[[exodus-39-4]]
^4^ Pusieron al efod hombreras y lo fijaron por sus dos extremos.

[[exodus-39-5]]
^5^ La cinta con que se ciñe el efod era de la misma hechura y formaba con él una sola pieza: era de oro, púrpura violeta y escarlata, carmesí y lino fino torzal, como Yahveh se lo había mandado a Moisés.

[[exodus-39-6]]
^6^ Prepararon igualmente las piedras de ónice engastadas en engastes de oro y grabadas como se graban los sellos, con los nombres de los hijos de Israel;

[[exodus-39-7]]
^7^ las colocaron sobre las hombreras del efod, como piedras que sirvieran a Yahveh de recuerdo de los hijos de Israel, según Yahveh había ordenado a Moisés.

[[exodus-39-8]]
^8^ Bordaron también el pectoral, al estilo de la labor del efod, de oro, púrpura violeta y escarlata, carmesí y lino fino torzal.

[[exodus-39-9]]
^9^ El pectoral era cuadrado y lo hicieron doble; tenía un palmo de largo y otro de ancho; era doble.

[[exodus-39-10]]
^10^ Lo llenaron de cuatro filas de piedras. En la primera fila había un sardio, un topacio y una esmeralda;

[[exodus-39-11]]
^11^ en la segunda fila: un rubí, un zafiro y un diamante;

[[exodus-39-12]]
^12^ en la tercera fila: un ópalo, una ágata y una amatista;

[[exodus-39-13]]
^13^ y en la cuarta: un crisólito, un ónice y un jaspe. Todas ellas estaban engastadas en engarces de oro.

[[exodus-39-14]]
^14^ Las piedras eran doce, correspondientes a los nombres de los hijos de Israel, grabadas con sus nombres como se graban los sellos, cada una con su nombre, conforme a las doce tribus.

[[exodus-39-15]]
^15^ Hicieron para el pectoral cadenillas de oro puro, trenzadas a manera de cordones.

[[exodus-39-16]]
^16^ Hicieron dos engastes de oro y dos anillas de oro; fijaron las dos anillas en los dos extremos del pectoral.

[[exodus-39-17]]
^17^ Pasaron después las dos cadenillas de oro por las dos anillas en los extremos del pectoral.

[[exodus-39-18]]
^18^ Unieron los otros dos extremos de las dos cadenillas a los dos engarces, que fijaron del efod.

[[exodus-39-19]]
^19^ Hicieron otras dos anillas de oro y las pusieron en los otros dos extremos del pectoral en el borde interior que mira hacia el efod.

[[exodus-39-20]]
^20^ E hicieron otras dos anillas de oro, que fijaron en la parte inferior de las dos hombreras del efod, por delante, cerca de su unión, encima de la cinta del efod.

[[exodus-39-21]]
^21^ Y por medio de sus anillas sujetaron el pectoral a las anillas del efod, con un cordón de púrpura violeta, para que quedase el pectoral sobre la cinta del efod y no se desprendiese del efod, como Yahveh había mandado a Moisés.

[[exodus-39-22]]
^22^ Tejieron el manto del efod, todo de púrpura violeta.

[[exodus-39-23]]
^23^ Había una abertura en el centro del manto, semejante al cuello de una cota, con una orla alrededor de la abertura para que no se rompiese.

[[exodus-39-24]]
^24^ En el ruedo inferior del manto hicieron granadas de púrpura violeta y escarlata, de carmesí y lino fino torzal.

[[exodus-39-25]]
^25^ Hicieron campanillas de oro puro, colocándolas entre las granadas, en todo el ruedo.

[[exodus-39-26]]
^26^ Una campanilla y una granada alternaban con otra campanilla y otra granada, en el ruedo inferior del manto. Servía para oficiar, como Yahveh había ordenado a Moisés.

[[exodus-39-27]]
^27^ Tejieron también las túnicas de lino fino para Aarón y sus hijos;

[[exodus-39-28]]
^28^ la tiara de lino fino, los adornos de las mitras de lino fino y también los calzones de lino fino torzal,

[[exodus-39-29]]
^29^ lo mismo que las fajas recamadas de lino fino torzal, de púrpura violeta y escarlata y de carmesí, tal como Yahveh había ordenado a Moisés.

[[exodus-39-30]]
^30^ E hicieron de oro puro una lámina, la diadema sagrada en la que grabaron, como se graban los sellos: «Consagrado a Yahveh».

[[exodus-39-31]]
^31^ Fijaron en ella un cordón de púrpura violeta para sujetarla en la parte superior de la tiara, como Yahveh había mandado a Moisés.

[[exodus-39-32]]
^32^ Así fue acabada toda la obra de la Morada y de la Tienda del Encuentro. Los israelitas hicieron toda la obra conforme a lo que Yahveh había mandado a Moisés. Así lo hicieron.

[[exodus-39-33]]
^33^ Presentaron a Moisés la Morada, la Tienda y todos sus utensilios; los broches, los tableros, los travesaños, los postes y las basas;

[[exodus-39-34]]
^34^ el toldo de pieles de carnero teñidas de rojo, el toldo de cueros finos y el velo protector;

[[exodus-39-35]]
^35^ el arca del Testimonio con sus varales y el propiciatorio;

[[exodus-39-36]]
^36^ la mesa con todos sus utensilios y el pan de la Presencia;

[[exodus-39-37]]
^37^ el candelabro de oro puro con sus lámparas - las lámparas que habían de colocarse en él -, todos sus utensilios y el aceite del alumbrado;

[[exodus-39-38]]
^38^ el altar de oro, el óleo de la unción, el incienso aromático y la cortina para la entrada de la Tienda;

[[exodus-39-39]]
^39^ el altar de bronce con su rejilla de bronce, sus varales y todos sus utensilios; la pila con su base;

[[exodus-39-40]]
^40^ el cortinaje del atrio, los postes con sus basas, el tapiz para la entrada del atrio, sus cuerdas, su clavazón y todos los utensilios del servicio de la Morada para la Tienda del Encuentro;

[[exodus-39-41]]
^41^ las vestiduras de ceremonia para el servicio en el Santuario: los ornamentos sagrados para el sacerdote Aarón y las vestiduras de sus hijos para ejercer el sacerdocio.

[[exodus-39-42]]
^42^ Conforme a cuanto Yahveh había ordenado a Moisés, así hicieron los hijos de Israel toda la obra.

[[exodus-39-43]]
^43^ Moisés vio todo el trabajo y comprobó que lo habían llevado a cabo; tal como había mandado Yahveh, así lo habían hecho. Y Moisés los bendijo.
[[exodus-40]]
== Capítulo 40

[[exodus-40-1]]
^1^ Yahveh habló así a Moisés:

[[exodus-40-2]]
^2^ «El día primero del primer mes alzarás la Morada de la Tienda del Encuentro.

[[exodus-40-3]]
^3^ Allí pondrás el arca del Testimonio y cubrirás el arca con el velo.

[[exodus-40-4]]
^4^ LLevarás la mesa y colocarás lo que hay que ordenar sobre ella; llevarás también el candelabro y pondrás encima las lámparas.

[[exodus-40-5]]
^5^ Colocarás el altar de oro para el incienso delante del arca del Testimonio y colgarás la cortina a la entrada de la Morada.

[[exodus-40-6]]
^6^ Colocarás el altar de los holocaustos ante la entrada de la Morada de la Tienda del Encuentro.

[[exodus-40-7]]
^7^ Pondrás la pila entre la Tienda del Encuentro y el altar, y echarás agua en ella.

[[exodus-40-8]]
^8^ En derredor levantarás el atrio y tenderás el tapiz a la entrada del atrio.

[[exodus-40-9]]
^9^ Entonces tomarás el óleo de la unción y ungirás la Morada y todo lo que contiene. La consagrarás con todo su mobiliario y será cosa sagrada.

[[exodus-40-10]]
^10^ Ungirás además el altar de los holocaustos con todos sus utensilios. Consagrarás el altar, y el altar será cosa sacratísima.

[[exodus-40-11]]
^11^ Asimismo ungirás la pila y su base, y la consagrarás.

[[exodus-40-12]]
^12^ Después mandarás que Aarón y sus hijos se acerquen a la entrada de la Tienda del Encuentro y los lavarás con agua.

[[exodus-40-13]]
^13^ Vestirás a Aarón con las vestiduras sagradas, le ungirás, y le consagrarás para que ejerza mi sacerdocio.

[[exodus-40-14]]
^14^ Mandarás también que se acerquen sus hijos; los vestirás con túnicas,

[[exodus-40-15]]
^15^ los ungirás, como ungiste a su padre, para que ejerzan mi sacerdocio. Así se hará para que su unción les confiera un sacerdocio sempiterno de generación en generación».

[[exodus-40-16]]
^16^ Moisés hizo todo conforme a lo que Yahveh le había mandado. Así lo hizo.

[[exodus-40-17]]
^17^ En el primer mes del año segundo, el día primero del mes, fue alzada la Morada.

[[exodus-40-18]]
^18^ Moisés alzó la Morada, asentó las basas, colocó sus tableros, metió sus travesaños y erigió sus postes.

[[exodus-40-19]]
^19^ Después desplegó la Tienda por encima de la Morada y puso además por encima el toldo de la Tienda, como Yahveh había mandado a Moisés.

[[exodus-40-20]]
^20^ Luego tomó el Testimonio y lo puso en el arca; puso al arca los varales y sobre ella colocó el propiciatorio en la parte superior.

[[exodus-40-21]]
^21^ LLevó entonces el arca a la Morada, colgó el velo de protección y cubrió así el arca del Testimonio, como Yahveh había mandado a Moisés.

[[exodus-40-22]]
^22^ Colocó también la mesa en la Tienda del Encuentro, al lado septentrional de la Morada, fuera del velo.

[[exodus-40-23]]
^23^ Dipuso sobre ella las filas de los panes de la Presencia delante de Yahveh, como Yahveh había ordenado a Moisés.

[[exodus-40-24]]
^24^ Luego instaló el candelabro en la Tienda del Encuentro, frente a la mesa, en el lado meridional de la Morada,

[[exodus-40-25]]
^25^ y colocó encima las lámparas delante de Yahveh, como Yahveh había mandado a Moisés.

[[exodus-40-26]]
^26^ Asimismo puso el altar de oro en la Tienda del Encuentro, delante del velo;

[[exodus-40-27]]
^27^ y quemó sobre él incienso aromático como Yahveh había mandado a Moisés.

[[exodus-40-28]]
^28^ A la entrada de la Morada colocó la cortina,

[[exodus-40-29]]
^29^ y en la misma entrada de la Morada de la Tienda del Encuentro colocó también el altar de los holocaustos, sobre el cual ofreció el holocausto y la oblación, como Yahveh había mandado a Moisés.

[[exodus-40-30]]
^30^ Situó la pila entre la Tienda del Encuentro y el altar, y echó en ella agua para las abluciones;

[[exodus-40-31]]
^31^ Moisés, Aarón y sus hijos se lavaron en ella las manos y los pies.

[[exodus-40-32]]
^32^ Siempre que entraban en la Tienda del Encuentro y siempre que se acercaban al altar, se lavaban, como Yahveh había mandado a Moisés.

[[exodus-40-33]]
^33^ Por fin alzó el atrio que rodeaba la Morada y el altar, y colgó el tapiz a la entrada del atrio. Así acabó Moisés los trabajos.

[[exodus-40-34]]
^34^ La Nube cubrió entonces la Tienda del Encuentro y la gloria de Yahveh llenó la Morada.

[[exodus-40-35]]
^35^ Moisés no podía entrar en la Tienda del Encuentro, pues la Nube moraba sobre ella y la gloria de Yahveh llenaba la Morada.

[[exodus-40-36]]
^36^ En todas las marchas, cuando la Nube se elevaba de encima de la Morada, los israelitas levantaban el campamento.

[[exodus-40-37]]
^37^ Pero si la Nube no se elevaba, ellos no levantaban el campamento, en espera del día en que se elevara.

[[exodus-40-38]]
^38^ Porque durante el día la Nube de Yahveh estaba sobre la Morada y durante la noche había fuego a la vista de toda la casa de Israel. Así sucedía en todas sus marchas.
