[[leviticus]]
= Levítico

[[leviticus-1]]
== Capítulo 1

[[leviticus-1-1]]
^1^ Yahveh llamó a Moisés y le habló así desde la Tienda del Encuentro:

[[leviticus-1-2]]
^2^ Habla a los israelitas y diles: Cuando alguno de vosotros presente a Yahveh una ofrenda, podréis hacer vuestras ofrendas de ganado, mayor o menor.

[[leviticus-1-3]]
^3^ Si su ofrenda es un holocausto de ganado mayor ofrecerá un macho sin defecto; lo ofrecerá a la entrada de la Tienda del Encuentro, para que sea grato ante Yahveh.

[[leviticus-1-4]]
^4^ Impondrá su mano sobre la cabeza de la víctima y le será aceptada para que le sirva de expiación.

[[leviticus-1-5]]
^5^ Inmolará el novillo ante Yahveh; los hijos de Aarón, los sacerdotes, ofrecerán la sangre y la derramarán alrededor del altar situado a la entrada de la Tienda del Encuentro.

[[leviticus-1-6]]
^6^ Desollará después la víctima y la descuartizará;

[[leviticus-1-7]]
^7^ los hijos de Aarón, los sacerdotes, pondrán fuego sobre el altar y colocarán leña sobre el fuego;

[[leviticus-1-8]]
^8^ luego, los hijos de Aarón, los sacerdotes, dispondrán las porciones, la cabeza y el sebo, encima de la leña colocada sobre el fuego del altar.

[[leviticus-1-9]]
^9^ El lavará con agua las entrañas y las patas y el sacerdote lo quemará todo en el altar. Es un holocausto, un manjar abrasado de calmante aroma par Yahveh.

[[leviticus-1-10]]
^10^ Si su ofrenda es de ganado menor, de corderos o cabras, para holocausto, ofrecerá un macho sin defecto.

[[leviticus-1-11]]
^11^ Lo inmolará al lado septentrional del altar ante Yahveh, y los hijos de Aarón los sacerdotes, derramarán la sangre alrededor del altar.

[[leviticus-1-12]]
^12^ Luego, lo despedazará en porciones, y el sacerdote las dispondrá, con la cabeza y el sebo, encima de la leña colocada sobre el fuego del altar.

[[leviticus-1-13]]
^13^ Lavará él con agua las entrañas y las patas, y el sacerdote lo ofrecerá todo y lo quemará en el altar. Es un holocausto, un manjar abrasado de calmante aroma para Yahveh.

[[leviticus-1-14]]
^14^ Si su ofrenda a Yahveh es un holocausto de aves, presentará como ofrenda tórtolas o pichones.

[[leviticus-1-15]]
^15^ El sacerdote la ofrecerá en el altar, descervigará su cabeza y la quemará en el altar; su sangre será exprimida contra la pared del altar.

[[leviticus-1-16]]
^16^ Quitará entonces el buche con las plumas y los arrojará al lado oriental del altar, al lugar donde se echan las cenizas.

[[leviticus-1-17]]
^17^ Abrirá el ave entre las alas, sin llegar a partirla; y la quemará en el altar, encima de la leña colocado sobre el fuego. Es un holocausto, un manjar abrasado de calmante aroma para Yahveh.
[[leviticus-2]]
== Capítulo 2

[[leviticus-2-1]]
^1^ Cuando alguien ofrezca a Yahveh una oblación, su ofrenda consistirá en flor de harina, sobre la que derramará aceite y pondrá incienso.

[[leviticus-2-2]]
^2^ La llevará a los hijos de Aarón, a los sacerdotes; tomará un puñado de la harina con aceite y todo el incienso; el sacerdote lo quemará en el altar como memorial, manjar abrasado de calmante aroma para Yahveh.

[[leviticus-2-3]]
^3^ El resto de la oblación será para Aarón y para sus hijos, como porción sacrastísima del manjar abrasado para Yahveh.

[[leviticus-2-4]]
^4^ Cuando ofrezcas una oblación de pasta cocida al horno, será de flor de harina en panes ázimos amasados con aceite, o en tortas ázimas untadas en aceite.

[[leviticus-2-5]]
^5^ Si tu ofrenda es una oblación preparada en la chapa, ha de ser de flor de harina, amasada con aceite, sin levadura.

[[leviticus-2-6]]
^6^ La partirás en trozos y encima derramarás aceite. Es una oblación.

[[leviticus-2-7]]
^7^ Si tu ofrenda es una oblación preparada en cazuela, se hará de flor de harina con aceite.

[[leviticus-2-8]]
^8^ La oblación que ha sido preparada con estas cosas, se la llevarás a Yahveh. Será presentada al sacerdote, quien la llevará al altar.

[[leviticus-2-9]]
^9^ El sacerdote reservará parte de la oblación como memorial y lo quemará en el altar, como manjar abrasado de calmante aroma para Yahveh.

[[leviticus-2-10]]
^10^ El resto de la oblación será para Aarón y para sus hijos, como porción sacratísima del manjar abrasado de Yahveh.

[[leviticus-2-11]]
^11^ Toda la oblación que ofrezcáis a Yahveh será preparada sin levadura, pues ni de fermento ni de miel quemaréis nada como manjar abrasado para Yahveh.

[[leviticus-2-12]]
^12^ Sí que los podréis ofrecer como ofrenda de primicias, pero no subirán al altar como sacrificio de calmante aroma.

[[leviticus-2-13]]
^13^ Sazonarás con sal toda oblación que ofrezcas; en ninguna de tus oblaciones permitirás que falte nunca la sal de la alianza de tu Dios; en todas tus ofrendas ofrecerás sal.

[[leviticus-2-14]]
^14^ Si ofreces a Yahveh una oblación de primicias ofrecerás, como oblación de tus primicias, espigas tostadas al fuego o grano tierno majado.

[[leviticus-2-15]]
^15^ Derramarás sobre ella aceite y le echarás además incienso; es una oblación.

[[leviticus-2-16]]
^16^ El sacerdote quemará, como memorial de la misma, parte del grano majado y del aceite, con todo el incienso, como manjar abrasado para Yahveh.
[[leviticus-3]]
== Capítulo 3

[[leviticus-3-1]]
^1^ Si su ofrenda es un sacrificio de comunión, si lo que ofrece es vacuno, macho o hembra, ofrecerá ante Yahveh una res sin defecto.

[[leviticus-3-2]]
^2^ Impondrá su mano sobre la cabeza de la ofrenda y la inmolará en la entrade de la Tienda del Encuentro. Luego los hijos de Aarón, los sacerdotes, derramarán la sangre alrededor del altar.

[[leviticus-3-3]]
^3^ El ofrecerá parte del sacrificio de communión como manjar abrasado para Yahveh: el sebo que cubre las entrañas y todo el que hay sobre las mismas;

[[leviticus-3-4]]
^4^ los dos riñones y el sebo adherido a ellos y a los lomos; y el resto que cubre el hígado; quitará todo este sebo junto con los riñones.

[[leviticus-3-5]]
^5^ Los hijos de Aarón lo quemarán en el altar encima del holocausto que está sobre la leña, que está encima del fuego. Será un manjar abrasado de calmante aroma para Yahveh.

[[leviticus-3-6]]
^6^ Si su ofrenda de sacrificio de comunión para Yahveh es de ganado menor, macho o hembra, ofrecerá una res sin defecto.

[[leviticus-3-7]]
^7^ Si ofrece como ofrenda un cordero, lo prensentará ante Yahveh,

[[leviticus-3-8]]
^8^ impondrá su mano sobre la cabeza de la ofrenda y la inmolará ante la Tienda del Encuentro; los hijos de Aarón derramarán la sangre alrededor del altar.

[[leviticus-3-9]]
^9^ El ofrecerá, de este sacrificio de comunión, el sebo, como manjar abrasado para Yahveh: el rabo entrero que se cortará desde la rabadilla; el sebo que cubre las entrañas y todo el que hay sobre las mismas;

[[leviticus-3-10]]
^10^ los dos riñones y el sebo adherido a ellos y a los lomos, y el resto que cubre el hígado; quitará todo este sebo junto con los riñones.

[[leviticus-3-11]]
^11^ El sacerdote lo quemará en el altar como alimento, manjar abrasado para Yahveh.

[[leviticus-3-12]]
^12^ Si su ofrenda consiste en una cabra, la presentará ante Yahveh,

[[leviticus-3-13]]
^13^ impondrá la mano sobre su cabeza y la inmolará ante la Tienda del Encuentro; los hijos de Aarón derramarán su sangre alrededor del altar.

[[leviticus-3-14]]
^14^ Presentará de ella como ofrenda suya, manjar abrasado para Yahveh: el sebo que cubre las entrañas y todo el que hay sobre las mismas;

[[leviticus-3-15]]
^15^ los dos riñones y el sebo adherido a ellos y a los lomos; y el resto que cubre el hígado; quitará todo este sebo junto con los riñones.

[[leviticus-3-16]]
^16^ El sacerdote lo quemará en el altar como alimento, manjar abrasado de calmante aroma para Yahveh. Toda la grasa perpetua de generación en generación, dondequiera que habitéis: no comeréis nada de grasa ni de sangre.
[[leviticus-4]]
== Capítulo 4

[[leviticus-4-1]]
^1^ Yahveh habló así a Moisés:

[[leviticus-4-2]]
^2^ Habla a los israelitas y diles: Si alguien peca por inadvertencia contra cualquiera de los mandamientos de Yahveh sobre lo que no se debe hacer y comete una de estas acciones prohibidas:

[[leviticus-4-3]]
^3^ Si el que peca es el sacerdote ungido, haciendo culpable al pueblo, entonces ofrecerá a Yahveh por el pecado que ha cometido un novillo sin defecto, como sacrificio por el pecado.

[[leviticus-4-4]]
^4^ Llevará el novillo a la entrada de la tienda del Encuentro ante Yahveh, impondrá la mano sobre la cabeza del novillo y lo inmolará ante Yahveh.

[[leviticus-4-5]]
^5^ El sacerdote ungido tomará parte de la sangre del novillo y la llevará a la Tienda del Encuentro.

[[leviticus-4-6]]
^6^ El sacerdote mojará su dedo en la sangre y rociará con ella siete veces ante Yahveh frente al velo del Santuario.

[[leviticus-4-7]]
^7^ El sacerdote pondrá parte de la sangre en los cuernos del altar del incienso aromático ante Yahveh en la Tienda del Encuentro, y verterá toda la sangre del novillo al pie del altar de los holocaustos que se encuentra a la entrada de la Tienda del Encuentro.

[[leviticus-4-8]]
^8^ De todo el sebo del novillo sacrificado por el pecado, reservará el sebo que cubre las entrañas y todo el que hay sobre las mismas;

[[leviticus-4-9]]
^9^ los dos riñones y el sebo adherido a ellos y a los lomos, y el resto que cubre el hígado; quitará todo este sebo junto con los riñones, -

[[leviticus-4-10]]
^10^ todo como lo reservado del novillo del sacrificio de comunión - y el sacerdote lo quemará sobre el altar de los holocaustos.

[[leviticus-4-11]]
^11^ La piel del novillo, toda su carne, con su cabeza y sus patas, sus entrañas con los excrementos,

[[leviticus-4-12]]
^12^ el novillo entero, lo sacará fuera del campamento, a un lugar puro, al vertedero de las cenizas. Lo quemará con fuego de leña; será quemado en el vertedero de las cenizas.

[[leviticus-4-13]]
^13^ Si toda la comunidad de Israel peca por inadvertencia, haciendo cualquiera de las cosas prohibidas por los mandamientos de Yahveh, haciéndose así culpable, quedando el hecho oculto a los ojos de la asamblea;

[[leviticus-4-14]]
^14^ en cuanto llegue a saberse el pecado cometido en ella, la asamblea ofrecerá un novillo en sacrificio por el pecado. Lo llevarán ante la Tienda del Encuentro;

[[leviticus-4-15]]
^15^ los ancianos de la comunidad impondrán las manos sobre la cabeza del novillo ante Yahveh y se inmolará el novillo ante Yahveh.

[[leviticus-4-16]]
^16^ Luego, el sacerdote ungido llevará parte de la sangre del novillo a la Tienda del Encuentro;

[[leviticus-4-17]]
^17^ el sacerdote mojará su dedo en la sangre y rociará siete veces ante Yahveh frente al velo.

[[leviticus-4-18]]
^18^ Pondrá parte de la sangre en los cuernos del altar que se halla ante Yahveh en la Tienda del Encuentro, y derramará el resto de la sangre al pie del altar de los holocaustos, situado a la entrada de la Tienda del Encuentro.

[[leviticus-4-19]]
^19^ Reservará todo el sebo del novillo y lo quemará en el altar,

[[leviticus-4-20]]
^20^ haciendo con este novillo como con el novillo del sacrificio por el pecado. Lo mismo hará con él. Así el sacerdote hará expiación por ellos y se les perdonará.

[[leviticus-4-21]]
^21^ Sacará el novillo fuera del campamento y lo quemará como el novillo anterior. Este es el sacrificio por el pecado de la asamblea.

[[leviticus-4-22]]
^22^ Si es un príncipe el que ha pecado, haciendo por inadvertencia cualquiera de las cosas prohibidas por los mandamientos de Yahveh su Dios, haciéndose así culpable;

[[leviticus-4-23]]
^23^ si se le advierte del pecado cometido, llevará como ofrenda un macho cabrío sin defecto.

[[leviticus-4-24]]
^24^ Impondrá su mano sobre la cabeza del macho cabrío y lo inmolará en el lugar donde se inmola el holocausto ante Yahveh. Es un sacrificio por el pecado.

[[leviticus-4-25]]
^25^ El sacerdote mojará su dedo en la sangre de la víctima, untará los cuernos del altar de los holocaustos y derramará la sangre al pie del altar de los holocaustos.

[[leviticus-4-26]]
^26^ Quemará todo el sebo en el altar como el sebo del sacrificio de comunión. El sacerdote hará así la expiación por él, por su pecado, y se le perdonará.

[[leviticus-4-27]]
^27^ Si uno cualquiera del pueblo de la tierra peca por inadvertencia haciendo algo prohibido por los mandamientos de Yahveh, haciéndose así culpable;

[[leviticus-4-28]]
^28^ si se le advierte del pecado cometido, presentará como ofrenda por el pecado cometido una cabra sin defecto.

[[leviticus-4-29]]
^29^ Impondrá su mano sobre la cabeza de la víctima y la inmolará en el mismo lugar de los holocaustos.

[[leviticus-4-30]]
^30^ El sacerdote mojará su dedo en la sangre, untará los cuernos del altar de los holocaustos, y derramará toda la sangre al pie del altar.

[[leviticus-4-31]]
^31^ Separará todo el sebo de la víctima, como se separa el sebo de un sacrificio de comunión, y el sacerdote lo quemará en el altar como calmante aroma para Yahveh. El sacerdote hará así expiación por él y se le perdonará.

[[leviticus-4-32]]
^32^ Si lleva un cordero como ofrenda suya por el pecado, sea lo que lleve una hembra sin defecto;

[[leviticus-4-33]]
^33^ impondrá su mano sobre la cabeza de la víctima y la inmolará como sacrificio por el pecado en el lugar donde se inmola el holocausto.

[[leviticus-4-34]]
^34^ El sacerdote mojará su dedo en la sangre de la víctima y untará los cuernos del altar de los holocaustos, y derramará toda la sangre al pie del mismo altar.

[[leviticus-4-35]]
^35^ Separará todo el sebo de la víctima, como se separa el sebo del cordero del sacrificio de comunión, y el sacerdote lo quemará en el altar, junto con los manjares abrasados de Yahveh. El sacerdote hará expiación por él, por el pecado cometido, y se le perdonará.
[[leviticus-5]]
== Capítulo 5

[[leviticus-5-1]]
^1^ Si alguien peca en uno de estos casos: Uno ha oído la fórmula conjuratoria, y es testigo, porque lo ha visto u oído, y no lo declara y se carga así con su iniquidad;

[[leviticus-5-2]]
^2^ o bien, uno toca cualquier cosa impura, sea el cadáver de una fiera impura, o el de ganado impuro o el de un bicho impuro, y, aun sin darse cuenta, se hace así él mismo impuro y culpable;

[[leviticus-5-3]]
^3^ o bien, uno toca cualquiera de las inmundicias humanas con que puede contaminarse, sin darse cuenta; y, saberlo, se hace culpable;

[[leviticus-5-4]]
^4^ o bien, uno pronuncia con los labios sin darse cuenta un juramento favorable o desfavorable, en cualquiera de las cosas que el hombre suele jurar y, al saberlo, se hace culpable de ello;

[[leviticus-5-5]]
^5^ el que es culpable en uno de estos casos confesará aquello en que ha pecado,

[[leviticus-5-6]]
^6^ y como sacrificio de reparación por el pecado cometido, llevará a Yahveh una hembra de ganado menor, oveja o cabra, como sacrificio por el pecado. Y el sacerdote hará por él expiación de su pecado.

[[leviticus-5-7]]
^7^ Cuando sus recursos no alcancen para una res menor, presentará a Yahveh, como sacrificio de reparación por su pecado, dos tórtolas o dos pichones, uno como sacrificio por el pecado y otro en holocausto.

[[leviticus-5-8]]
^8^ Los llevará al sacerdote, quien ofrecerá primero el que se destina al sacrificio por el pecado. Con las uñas descervigará la cabeza junto a la nuca sin arrancarla.

[[leviticus-5-9]]
^9^ Rociará con sangre de la víctima el lateral del altar, y el resto de la sangre será exprimida al pie del altar. Es un sacrificio por el pecado.

[[leviticus-5-10]]
^10^ Con el segundo hará un holocausto, conforme a la norma. El sacerdote le hará así expiación por el pecado cometido y le será perdonado.

[[leviticus-5-11]]
^11^ Si no le alcanza para dos tórtolas o dos pichones, presentará, como ofrenda suya por haber pecado, una décima de medida de flor de harina como sacrificio por el pecado. No añadirá aceite, ni echará sobre ella incienso, porque es sacrificio por el pecado.

[[leviticus-5-12]]
^12^ La llevará al sacerdote; y el sacerdote, tomando de ella un puñado como memorial, lo quemará en el altar, junto con los manjares que se abrasan para Yahveh. Es un sacrificio por el pecado.

[[leviticus-5-13]]
^13^ El sacerdote hará expíación por él, a causa del pecado que cometió en cualquiera de aquellos casos, y se le perdonará. El sacerdote tendrá su parte como en la oblación.

[[leviticus-5-14]]
^14^ Habló Yahveh a Moisés, diciendo:

[[leviticus-5-15]]
^15^ Si alguien comete una prevaricación pecando por inadvertencia contra los derechos sagrados de Yahveh, ofrecerá a Yahveh, como sacrificio de reparación, un carnero del rebaño, sin defecto, valorado en siclos de plata, en siclos del Santuario, como sacrificio de reparación.

[[leviticus-5-16]]
^16^ Resarcirá lo que defraudó pecando contra los derechos sagrados, y añadirá un quinto más, y se lo dará al sacerdote. El sacerdote hará por él la expiación con el carnero del sacrificio de reparación; y se le perdonará.

[[leviticus-5-17]]
^17^ Si alguien peca sin darse cuenta, haciendo algo prohibido por los mandamientos de Yahveh, se hace culpable y cargará con su iniquidad.

[[leviticus-5-18]]
^18^ Llevará al sacerdote, como sacrificio de reparación, un carnero del rebaño, sin defecto, según su valoración; y el sacerdote hará expiación por él a causa del error que cometió sin darse cuenta, y se le perdonará.

[[leviticus-5-19]]
^19^ Es un sacrificio de reparación, pues era ciertamente culpable ante Yahveh.

[[leviticus-5-20]]
^20^ Habló Yahveh a Moisés, diciendo:

[[leviticus-5-21]]
^21^ Si uno peca y comete una prevaricación contra Yahveh engañando a su prójimo acerca de un depósito o de un objeto confiado a sus manos, o de algo robado, o bien oprimiendo a su prójimo violentamente,

[[leviticus-5-22]]
^22^ o si halla un objeto perdido y lo niega, o jura en falso acerca de cualquiera de las cosas en que el hombre suele pecar;

[[leviticus-5-23]]
^23^ cuando así peca, haciéndose culpable, devolverá lo robado, o lo exigido con violencia, o el depósito que se le confió, o la cosa perdida que halló,

[[leviticus-5-24]]
^24^ o todo aquello sobre lo cual juró en falso. Lo restituirá íntegramente, añadiendo un quinto más, y lo devolverá a quien lo poseía en el día en que se hizo culpable.

[[leviticus-5-25]]
^25^ Entregará para Yahveh su sacrificio de reparación: un carnero del rebaño, sin defecto, según su valoración, como sacrificio de reparación ante el sacerdote.

[[leviticus-5-26]]
^26^ El sacerdote hará por él la expiación delante de Yahveh, y será perdonado en cualquiera de los casos en que fuera culpable.
[[leviticus-6]]
== Capítulo 6

[[leviticus-6-1]]
^1^ Habló así Yahveh a Moisés:

[[leviticus-6-2]]
^2^ Da esta orden a Aarón y a sus hijos: Esta es la ley del holocausto. (Este es el holocausto que estará sobre el fuego encendido, sobre el altar, toda la noche hasta la mañana, y que el fuego del altar mantendrá encendido.)

[[leviticus-6-3]]
^3^ El sacerdote se vestirá su túnica de lino y cubrirá su cuerpo con calzones de lino. Sacará las cenizas a que el fuego haya reducido las grasas del holocausto sobre el altar y las depositará junto al altar.

[[leviticus-6-4]]
^4^ Después se quitará los vestidos y se pondrá otros para llevar las cenizas fuera del campamento a un lugar puro.

[[leviticus-6-5]]
^5^ Arderá el fuego sobre el altar sin apagarse; el sacerdote lo alimentará con leña todas las mañanas, colocará encima el holocausto y sobre él quemará el sebo de los sacrificios de comunión.

[[leviticus-6-6]]
^6^ Fuego permanente arderá sobre el altar sin apagarse.

[[leviticus-6-7]]
^7^ Esta es la ley de la oblación: Los hijos de Aarón la presentarán delante de Yahveh, frente al altar;

[[leviticus-6-8]]
^8^ uno de ellos tomará de la oblación un puñado de flor de harina (con su aceite, y todo el incienso que se añade a la oblación), y lo quemará en el altar, en memorial, como calmante aroma para Yahveh.

[[leviticus-6-9]]
^9^ Aarón y sus hijos comerán lo que quede de ella; debe comerse sin levadura, en lugar santo. Han de comerlo en el atrio de la Tienda del Encuentro.

[[leviticus-6-10]]
^10^ No se la cocerá con levadura: es la porción que yo les doy de los manjares que se abrasan para mí. Es cosa sacratísima, como el sacrificio por el pecado y como el sacrificio de reparación.

[[leviticus-6-11]]
^11^ Todos los varones de los hijos de Aarón podrán comer de ello. Es ley perpetua para vuestros descendientes, relativa a los manjares que se abrasan para Yahveh. Todo cuanto los toque quedará consagrado.

[[leviticus-6-12]]
^12^ Habló Yahveh a Moisés, diciendo:

[[leviticus-6-13]]
^13^ Esta es la ofrenda que Aarón y sus hijos ofrecerán a Yahveh el día de su unción: una décima de medida de flor de harina, como oblación perpetua, la mitad por la mañana, y la mitad por la tarde.

[[leviticus-6-14]]
^14^ Será preparada con aceite en la sartén; la ofrecerás bien frita y la presentarás partida en trozos como una oblación, como calmante aroma para Yahveh.

[[leviticus-6-15]]
^15^ También la ofrecerá el sacerdote ungido que le suceda de entre sus hijos. Es decreto perpetuo. La oblación será totalmente quemada para Yahveh.

[[leviticus-6-16]]
^16^ Cualquier oblación de sacerdote será total; no se podrá comer.

[[leviticus-6-17]]
^17^ Habló Yahveh a Moisés, diciendo:

[[leviticus-6-18]]
^18^ Habla a Aarón y a sus hijos y diles: Esta es la ley del sacrificio por el pecado: En el lugar donde se inmola el holocausto, delante de Yahveh, será inmolada también la víctima por el pecado. Es cosa sacratísima.

[[leviticus-6-19]]
^19^ La comerá el sacerdote que ofrece la víctima por el pecado. Será comida en lugar santo, en el atrio de la Tienda del Encuentro.

[[leviticus-6-20]]
^20^ Todo cuanto toque esta carne quedará consagrado y, si su sangre salpica los vestidos, lavarás en lugar santo la parte salpicada.

[[leviticus-6-21]]
^21^ La vasija de barro en que haya sido cocida se romperá; y si ha sido cocida en vasija de bronce, ésta se fregará y lavará con agua.

[[leviticus-6-22]]
^22^ Todos los varones de entre los sacerdotes podrán comer de ella. Es cosa sacratísima.

[[leviticus-6-23]]
^23^ Pero no se comerá ninguna víctima ofrecida por el pecado, cuya sangre haya sido introducida en la Tienda del Encuentro para hacer la expiación en el Santuario: será consumida por el fuego.
[[leviticus-7]]
== Capítulo 7

[[leviticus-7-1]]
^1^ Esta es la ley del sacrificio de reparación: Es cosa sacratísima.

[[leviticus-7-2]]
^2^ En el lugar donde inmolan el holocausto inmolarán la víctima de reparación, y su sangre se derramará sobre todos los lados del altar.

[[leviticus-7-3]]
^3^ Se ofrecerá todo el sebo de la víctima: el rabo y el sebo que cubre las entrañas;

[[leviticus-7-4]]
^4^ los dos riñones y el sebo adherido a ellos y a los lomos, y el resto que cubre el hígado; se quitará todo este sebo junto con los riñones.

[[leviticus-7-5]]
^5^ El sacerdote lo quemará sobre el altar como manjar abrasado para Yahveh. Es un sacrificio de reparación.

[[leviticus-7-6]]
^6^ Podrán comerlo todos los varones de entre los sacerdotes; se comerá en lugar sagrado. Es cosa sacratísima.

[[leviticus-7-7]]
^7^ El sacrificio por el pecado es como el sacrifico de reparación: tienen la misma ley. La víctima pertenece al sacerdote que hace la expiación con ella.

[[leviticus-7-8]]
^8^ El sacerdote que ofrece el holocausto de una persona se quedará con la piel de la víctima que le han ofrecido.

[[leviticus-7-9]]
^9^ También toda oblación cocida al horno y toda la preparada en cazuela o en sartén pertenece al sacerdote que la ofrece;

[[leviticus-7-10]]
^10^ pero toda oblación amasada con aceite, o seca, se dará a todos los hijos de Aarón, en porciones iguales.

[[leviticus-7-11]]
^11^ Esta es la ley del sacrificio de comunión que se ofrece a Yahveh:

[[leviticus-7-12]]
^12^ Si se ofrece en alabanza, se ofrecerán, juntamente con el sacrificio de alabanza, panes ázimos amasados con aceite, tortas ázimas untadas de aceite y tortas de flor de harina amasadas con aceite.

[[leviticus-7-13]]
^13^ Se añadirá esta ofrenda a las tortas de pan fermentado y al sacrificio de comunión en alabanza.

[[leviticus-7-14]]
^14^ Se reservará una pieza de cada clase como ofrenda reservada a Yahveh y corresponderá al sacerdote que derrama la sangre del sacrificio de comunión.

[[leviticus-7-15]]
^15^ La carne del sacrificio de comunión en alabanza se comerá el mismo día de su ofrecimiento, sin dejar nada de ella para la mañana siguiente.

[[leviticus-7-16]]
^16^ Si se ofrece la víctima en cumplimiento de un voto, o como ofrenda voluntaria, se comerá el mismo día en que ha sido ofrecida, y lo que sobre deberá comerse al día siguiente.

[[leviticus-7-17]]
^17^ Pero el tercer día será quemado lo que quede de la carne de la víctima.

[[leviticus-7-18]]
^18^ Si se come la carne de un sacrificio de comunión al tercer día, no obtendrá favor el oferente del mismo; no se le tendrá en cuenta. Será abominación. Y quien coma de ella, cargará con su iniquidad.

[[leviticus-7-19]]
^19^ No podrá comerse la carne que haya tocado cualquier cosa impura; será consumida por el fuego. Toda persona pura podrá comer la carne.

[[leviticus-7-20]]
^20^ Pero quien, en estado de impureza, coma carne del sacrificio de comunión presentado a Yahveh, ése será exterminado de su parentela.

[[leviticus-7-21]]
^21^ Si alguien toca cualquier cosa inmunda, sea inmundicia de hombre, o de animal, o cualquier otra abominación impura y luego come de la carne del sacrificio de comunión ofrecido a Yahveh, será exterminado de su parentela.

[[leviticus-7-22]]
^22^ Habló Yahveh a Moisés, diciendo:

[[leviticus-7-23]]
^23^ Habla a los israelitas y diles: No comeréis sebo de buey, ni de cordero ni de cabra.

[[leviticus-7-24]]
^24^ El sebo de animal muerto o destrozado podrá servir para cualquier uso, pero en modo alguno lo comeréis.

[[leviticus-7-25]]
^25^ Porque todo aquel que coma sebo de animal del que suele ofrecerse manjar abrasado a Yahveh, será exterminado de su parentela.

[[leviticus-7-26]]
^26^ Tampoco comeréis sangre, ni de ave ni de animal, en ninguno de los lugares en que habitaréis.

[[leviticus-7-27]]
^27^ Todo el que coma cualquier clase de sangre, ése será exterminado de su parentela.

[[leviticus-7-28]]
^28^ Yahveh habló a Moisés, diciendo:

[[leviticus-7-29]]
^29^ Habla a los israelitas y diles: Quien ofrezca a Yahveh un sacrificio de comunión, presente a Yahveh una porción de su sacrificio.

[[leviticus-7-30]]
^30^ Con sus propias manos llevará los manjares que se abrasarán para Yahveh: él mismo presentará el sebo y el pecho; el pecho para mecerlo como ofrenda mecida ante Yahveh.

[[leviticus-7-31]]
^31^ El sacerdote quemará el sebo sobre el altar; el pecho será para Aarón y sus hijos.

[[leviticus-7-32]]
^32^ Daréis también al sacerdote, como ofrenda reservada, la pierna derecha de vuestros sacrificios de comunión.

[[leviticus-7-33]]
^33^ Esta pierna derecha pertenecerá a aquel de los hijos de Aarón que haya ofrecido la sangre y el sebo de los sacrificios de comunión.

[[leviticus-7-34]]
^34^ Pues yo sustraigo a los israelitas, de sus sacrificios de comunión, el pecho mecido y la pierna reservada para dárselos al sacerdote Aarón y a sus hijos, por decreto perpetuo entre los israelitas.

[[leviticus-7-35]]
^35^ Esta es la porción de Aarón y la porción de sus hijos, en los manjares que se abrasan en honor de Yahveh, desde el día en que los presentó para ejercer el sacerdocio de Yahveh.

[[leviticus-7-36]]
^36^ Esto mandó Yahveh que los israelitas les dieran el día en que los ungió, como decreto perpetuo de generación en generación.

[[leviticus-7-37]]
^37^ Esta es la ley del holocausto, de la oblación, del sacrificio por el pecado, del sacrificio de reparación, del sacrificio de investidura y del sacrificio de comunión,

[[leviticus-7-38]]
^38^ que Yahveh prescribió a Moisés en el monte Sinaí, el día en que mandó a los israelitas que presentaran sus ofrendas a Yahveh en el desierto del Sinaí.
[[leviticus-8]]
== Capítulo 8

[[leviticus-8-1]]
^1^ Yahveh habló así a Moisés:

[[leviticus-8-2]]
^2^ «Toma a Aarón y con él a sus hijos, y también las vestiduras, el óleo de la unción, el novillo para el sacrificio por el pecado, los dos carneros y el canastillo de los ázimos;

[[leviticus-8-3]]
^3^ y congrega a toda la comunidad a la entrada de la Tienda del Encuentro».

[[leviticus-8-4]]
^4^ Moisés hizo como Yahveh le había mandado, y se congregó la comunidad a la entrada de la Tienda del Encuentro.

[[leviticus-8-5]]
^5^ Moisés dijo a la comunidad: «Esto es lo que Yahveh ha ordenado hacer».

[[leviticus-8-6]]
^6^ Moisés mandó entonces que Aarón y sus hijos se acercaran y los lavó con agua.

[[leviticus-8-7]]
^7^ Puso sobre Aarón la túnica y se la ciñó con la faja; lo vistió con el manto y poniéndole encima el efod, se lo ciñó atándoselo con la cinta del efod.

[[leviticus-8-8]]
^8^ Lueg o, le impuso el pectoral en el que depositó el Urim y el Tummim.

[[leviticus-8-9]]
^9^ Colocó también la tiara sobre su cabeza y puso en su parte delantera la lámina de oro, la diadema santa, como Yahveh había mandado a Moisés.

[[leviticus-8-10]]
^10^ Después Moisés tomó el óleo de la unción y ungió la Morada con todas las cosas que contenía para consagrarlas.

[[leviticus-8-11]]
^11^ Roció con él por siete veces el altar y ungió el altar con todos su utensilios, así como la pila con su base, para consagrarlos.

[[leviticus-8-12]]
^12^ Y derramando óleo de la unción sobre la cabeza de Aarón, lo ungió para consagrarlo.

[[leviticus-8-13]]
^13^ Luego Moisés mandó que se acercaran los hijos de Aarón; los vistió con las túnicas, les ciñó la faja y les puso las mitras, como Yahveh había mandado a Moisés.

[[leviticus-8-14]]
^14^ Después hizo traer el novillo para el sacrificio por el pecado, y Aarón y sus hijos impusieron las manos sobre la cabeza del novillo, víctima por el pecado.

[[leviticus-8-15]]
^15^ Moisés lo inmoló. Tomó la sangre y mojó con su dedo los cuernos del altar, todo en derredor, para purificarlo. Después derramó la sangre al pie del altar; de esta manera lo consagró haciendo por él la expiación.

[[leviticus-8-16]]
^16^ Tomó luego todo el sebo que cubre las entrañas, el que queda junto al hígado, y los dos riñones con su sebo; y lo quemó Moisés sobre el altar.

[[leviticus-8-17]]
^17^ Pero en cuanto a la piel, la carne y los excrementos del novillo, los quemó fuera del campamento, como Yahveh había mandado a Moisés.

[[leviticus-8-18]]
^18^ Después hizo traer el carnero del holocausto, sobre cuya cabeza Aarón y sus hijos impusieron las manos.

[[leviticus-8-19]]
^19^ Moisés lo inmoló y roció con la sangre todos los lados del altar.

[[leviticus-8-20]]
^20^ El carnero fue partido en trozos y Moisés quemó la cabeza, los trozos y el sebo;

[[leviticus-8-21]]
^21^ después de lavar en agua las entrañas y las patas, Moisés quemó todo el carnero en el altar, como holocausto de calmante aroma, manjar abrasado para Yahveh, como Yahveh había mandado a Moisés.

[[leviticus-8-22]]
^22^ Hizo luego traer el segundo carnero, el carnero del sacrificio de la investidura, y Aarón y sus hijos impusieron las manos sobre la cabeza del carnero.

[[leviticus-8-23]]
^23^ Moisés lo inmoló, y, tomando su sangre, mojó el lóbulo de la oreja derecha de Aarón, el pulgar de su mano derecha de Aarón, el pulgar de su mano derecha y el de su pie derecho.

[[leviticus-8-24]]
^24^ Después Moisés hizo que se acercaran los hijos de Aarón, les untó con la sangre el lóbulo de la oreja derecha, el pulgar de su mano derecha y el de su pie derecho; y derramó la sangre sobre el altar, todo en derredor.

[[leviticus-8-25]]
^25^ Tomó luego el sebo: el rabo, todo el sebo que cubre las entrañas, el que queda junto al hígado, los dos riñones con su sebo y la pierna derecha.

[[leviticus-8-26]]
^26^ Sacó del canastillo de los ázimos que estaba ante Yahveh un pan ázimo, una torta de pan amasada con aceite y otra torta untada, y las puso sobre el sebo y sobre la pierna derecha.

[[leviticus-8-27]]
^27^ Entregó todo esto en manos de Aarón y en manos de sus hijos haciéndolo mecer como ofrenda mecida ante Yahveh.

[[leviticus-8-28]]
^28^ Moisés lo recibió de sus manos y lo quemó en el altar, encima del holocausto. Era el sacrificio de investidura, calmante aroma, manjar abrasado en honor de Yahveh.

[[leviticus-8-29]]
^29^ Moisés tomó entonces el pecho y lo meció como ofrenda mecida ante Yahveh; era ésta la porción del carnero de la investidura que pertenecía a Moisés, como Yahveh se lo había mandado.

[[leviticus-8-30]]
^30^ Después Moisés tomó óleo de la unción y sangre de la que había encima del altar, roció a Aarón y sus vestiduras de sus hijos. Así consagró a Aarón y sus vestiduras, así como a sus hijos y las vestiduras de sus hijos.

[[leviticus-8-31]]
^31^ Moisés dijo a Aarón y a sus hijos: «Coced la carne a la entrada de la Tienda del Encuentro y comedla allí mismo; comed también el pan del canastillo de la investidura tal como lo he mandado diciendo: Aarón y sus hijos lo comerán.

[[leviticus-8-32]]
^32^ Quemaréis la carne sobrante y el pan.

[[leviticus-8-33]]
^33^ Y no os apartaréis de la entrada de la Tienda del Encuentro por espacio de siete días, hasta el día en que se cumplan los días de vuestra investidura; porque siete días durará vuestra investidura.

[[leviticus-8-34]]
^34^ Yahveh mandó que se procediera como se ha procedido hoy para hacer expiación por vosotros.

[[leviticus-8-35]]
^35^ Así quedaréis siete días, día y noche, a la entrada de la Tienda del Encuentro, guardando la norma de Yahveh para no morir, pues así me fue ordenado».

[[leviticus-8-36]]
^36^ Aarón y sus hijos hicieron cuanto Yahveh había mandado por medio de Moisés.
[[leviticus-9]]
== Capítulo 9

[[leviticus-9-1]]
^1^ El día octavo Moisés llamó a Aarón y a sus hijos, y a los ancianos de Israel.

[[leviticus-9-2]]
^2^ Dijo a Aarón: «Trae un becerro para el sacrificio por el pecado y un carnero para el holocausto, ambos sin defecto, para ofrecerlos ante Yahveh.

[[leviticus-9-3]]
^3^ Hablarás a los israelitas, diciendo: “Tomad un macho cabrío para el sacrificio por el pecado y un becerro y un cordero, ambos de un año y sin defecto, para el holocausto;

[[leviticus-9-4]]
^4^ para los sacrificios de comunión, un toro y un carnero, que se sacrificarán ante Yahveh; y una oblación amasada con aceite. Cierto que hoy se os mostrará Yahveh.”»

[[leviticus-9-5]]
^5^ Trajeron, pues, ante la Tienda del Encuentro lo que Moisés había mandado; toda la comunidad se acercó y se mantuvo delante de Yahveh.

[[leviticus-9-6]]
^6^ Dijo entonces Moisés: «Esto es lo que ha mandado Yahveh; hacedlo y se os mostrará la gloria de Yahveh».

[[leviticus-9-7]]
^7^ Después Moisés dijo a Aarón: «Acércate al altar, ofrece tu sacrificio por el pecado y tu holocausto, y haz la expiación por ti mismo y por tu casa; presenta también la ofrenda del pueblo y haz la expiación por ellos, como Yahveh lo ha prescrito».

[[leviticus-9-8]]
^8^ Acercóse, pues, Aarón al altar e inmoló el becerro del sacrificio por su propio pecado.

[[leviticus-9-9]]
^9^ Los hijos de Aarón le presentaron la sangre; y él, mojando su dedo en la sangre, untó con ella los cuernos del altar y derramó la sangre al pie del altar.

[[leviticus-9-10]]
^10^ Luego quemó sobre el altar el sebo, los riñones y lo que queda junto al hígado de la víctima por el pecado, como Yahveh había mandado a Moisés;

[[leviticus-9-11]]
^11^ pero quemó la carne y la piel fuera del campamento.

[[leviticus-9-12]]
^12^ Después inmoló la víctima del holocausto y los hijos de Aarón le presentaron la sangre, que derramó sobre todos los lados del altar.

[[leviticus-9-13]]
^13^ Le presentaron la víctima del holocausto en trozos, juntamente con la cabeza, y lo quemó todo sobre el altar.

[[leviticus-9-14]]
^14^ Y habiendo lavado las entrañas y las patas, las quemó encima del holocausto sobre el altar.

[[leviticus-9-15]]
^15^ Después presentó la ofrenda del pueblo: tomó el macho cabrío correspondiente al sacrificio por el pecado del pueblo, lo inmoló y lo sacrificó como el primero.

[[leviticus-9-16]]
^16^ Ofreció el holocausto, haciéndolo según la norma.

[[leviticus-9-17]]
^17^ Además presentó lo oblación. Tomando un puñado de ella, la quemó en el altar encima del holocausto de la mañana.

[[leviticus-9-18]]
^18^ Inmoló asimismo el toro y el carnero como sacrificio de comunión por el pueblo. Los hijos de Aarón le entregaron la sangre, que él derramó sobre todos los lados del altar.

[[leviticus-9-19]]
^19^ En cuanto a las partes grasas del toro y del carnero, el rabo, el sebo que cubre las entrañas, los riñones y lo que queda junto al hígado,

[[leviticus-9-20]]
^20^ las puso sobre los pechos de las víctimas, y él las quemó sobre el altar;

[[leviticus-9-21]]
^21^ Aarón por su parte meció los pechos y la pierna derecha como ofrenda mecida ante Yahveh conforme Moisés había mandado.

[[leviticus-9-22]]
^22^ Entonces Aarón, alzando las manos hacia el pueblo, lo bendijo; después de haber acabado el sacrificio por el pecado, el holocausto y el sacrificio de comunión, descendió.

[[leviticus-9-23]]
^23^ Luego Moisés y Aarón entraron en la Tienda del Encuentro y, cuando salieron, bendijeron al pueblo. La gloria de Yahveh se dejó ver de todo el pueblo.

[[leviticus-9-24]]
^24^ Salió fuego de la presencia de Yahveh que consumió el holocausto y las partes grasas puestas sobre el altar. Todo el pueblo al verlo prorrumpió en gritos de júbilo y cayó rostro en tierra.
[[leviticus-10]]
== Capítulo 10

[[leviticus-10-1]]
^1^ Nadab y Abihú, hijos de Aarón, tomaron cada uno su incensario, pusieron fuego en ellos y, tras echar incienso encima, ofrecieron ante Yahveh un fuego profano, que él no les había mandado.

[[leviticus-10-2]]
^2^ Entonces salió de la presencia de Yahveh un fuego que los devoró, y murieron delante de Yahveh.

[[leviticus-10-3]]
^3^ Moisés dijo entonces a Aarón: «Esto es lo que Yahveh ha declarado diciendo: Entre los cercanos a mí mostraré mi santidad. y ante la faz del pueblo manifestaré mi gloria». Aarón no dijo nada.

[[leviticus-10-4]]
^4^ Moisés llamó a Missael y a Elsafán, hijos de Uzziel, tío paterno de Aarón, y les dijo: «Acercaos, retirad a vuestros hermanos de delante del santuario y llevadlos fuera del campamento».

[[leviticus-10-5]]
^5^ Se acercaron y los llevaron en sus propias túnicas fuera del campamento, como Moisés había mandado.

[[leviticus-10-6]]
^6^ Moisés dijo a Aarón y a sus hijos, Eleazar e Itamar: «No llevéis la cabeza desgreñada, ni rasguéis vuestros vestidos, para no morir, pues la ira de Yahveh recae sobre toda la comunidad. Vuestros hermanos, toda la casa de Israel, llorarán a los abrasados por el fuego de Yahveh.

[[leviticus-10-7]]
^7^ No os apartéis de la entrada de la Tienda del Encuentro, no sea que muráis, pues tenéis sobre vosotros la unción de Yahveh». Ellos obedecieron a la palabra de Moisés.

[[leviticus-10-8]]
^8^ Yahveh habló a Aarón, diciendo:

[[leviticus-10-9]]
^9^ «Cuando hayáis de entrar en la Tienda del Encuentro, no bebáis vino ni bebida que pueda embriagar, ni tú ni tus hijos, no sea que muráis. Decreto perpetuo es éste para vuestros descendientes,

[[leviticus-10-10]]
^10^ para que podáis distinguir entre lo sagrado y lo profano, entre lo impuro y lo puro,

[[leviticus-10-11]]
^11^ y enseñar a los israelitas todos los preceptos que Yahveh les ha dado por medio de Moisés.

[[leviticus-10-12]]
^12^ Moisés dijo a Aarón y a Eleazar e Itamar, los hijos que le quedaban: «Tomad la oblación que queda de los manjares que se abrasan en honor de Yahveh y comedla sin levadura junto al altar, pues es cosa sacratísima.

[[leviticus-10-13]]
^13^ La comeréis en lugar sagrado, por ser la porción tuya y la porción de tus hijos, de los manjares que se abrasan en honor de Yahveh, pues así me ha ordenado.

[[leviticus-10-14]]
^14^ Tú, y contigo tus hijos y tus hijas, comeréis también en lugar puro el pecho mecido y la pierra reservada, porque os han sido dados como porción tuya y de tus hijos, de los sacrificios de comunión de los israelitas.

[[leviticus-10-15]]
^15^ Ellos traerán la pierna reservada y el pecho mecido, además de las grasas que han de ser abrasadas para Yahveh como ofrenda mecida delante de Yahveh; serán la porción perpetua para ti y para tus hijos junto a ti, según ha mandado Yahveh».

[[leviticus-10-16]]
^16^ Moisés preguntó con interés acerca del macho cabrío del sacrificio por el pecado; pero he aquí que había sido ya quemado. Irritado contra Eleazar e Itamar, los hijos que le habían quedado a Aarón, dijo:

[[leviticus-10-17]]
^17^ «¿Por qué no comisteis en lugar sagrado la víctima del sacrificio por el pecado? Pues era cosa sacratísima que se os daba a vosotros para quitar la falta de la comunidad, haciendo expiación por ellos ante Yahveh.

[[leviticus-10-18]]
^18^ Teníais que haberla comido en lugar sagrado según os había ordenado, porque su sangre no había sido llevada al interior del santuario».

[[leviticus-10-19]]
^19^ Respondió Aarón a Moisés: «Mira que ellos han presentado hoy su sacrificio por el pecado y su holocausto delante de Yahveh, y me ha sucedido esto; ¿si yo hubiera comido la víctima por el pecado, acaso hubiera sido esto grato a Yahveh?»

[[leviticus-10-20]]
^20^ Cuando Moisés oyó esto, se dio por satisfecho.
[[leviticus-11]]
== Capítulo 11

[[leviticus-11-1]]
^1^ Yahveh habló a Moisés y a Aarón, diciéndoles:

[[leviticus-11-2]]
^2^ Hablad a los israelitas y decidles: De entre todos los animales terrestres podréis comer estos:

[[leviticus-11-3]]
^3^ cualquier animal de pezuña partida, hendida en mitades y que rumia, sí lo podréis comer.

[[leviticus-11-4]]
^4^ Pero entre los que rumian o tienen pezuña hendida, no comeréis: camello, pues aunque rumia, no tiene partida la pezuña; será impuro para vosotros;

[[leviticus-11-5]]
^5^ ni damán, porque rumia, pero no tiene partida la pezuña; será impuro para vosotros:

[[leviticus-11-6]]
^6^ ni liebre porque rumia, pero no tiene la pezuña partida; será impura para vosotros;

[[leviticus-11-7]]
^7^ ni cerdo, pues aunque tiene la pezu4na partida, hendida en mitades, no rumia; será impuro para vosotros.

[[leviticus-11-8]]
^8^ No comeréis su carne ni tocaréis sus cadáveres; serán impuros para vosotros.

[[leviticus-11-9]]
^9^ De entre todos los animales que viven en las aguas, podréis comer éstos: cuantos tienen aletas y escamas sean de mar o río, los podréis comer.

[[leviticus-11-10]]
^10^ Pero serán cosa abominable para vosotros todos los que carezcan de aletas y escamas, entre todos los que bullen en las aguas, en mares y ríos, y entre todos los demás animales que viven en el agua.

[[leviticus-11-11]]
^11^ Serán abominables para vosotros: no comeréis su carne y tendréis sus cadáveres como abominables.

[[leviticus-11-12]]
^12^ Tendréis por abominable todo cuanto en las aguas carece de aletas y escamas.

[[leviticus-11-13]]
^13^ Las siguientes de entre las aves tendréis por inmundas, y no podrán comer por ser abominación: el águila, el quebrantahuesos, el águila marina,

[[leviticus-11-14]]
^14^ el buitre, el halcón en todas sus especies,

[[leviticus-11-15]]
^15^ toda clase de cuervos,

[[leviticus-11-16]]
^16^ el avestruz, la lechuza, la gaviota, el gavilán en todas sus especies,

[[leviticus-11-17]]
^17^ el búho, el somormujo, el ibis,

[[leviticus-11-18]]
^18^ el cisne, el pelícano, el calamón,

[[leviticus-11-19]]
^19^ la cigüeña, la garza en todas sus especies, la abubilla y el murciélago.

[[leviticus-11-20]]
^20^ Será abominable para vosotros todo bicho alado que anda sobre cuatro patas.

[[leviticus-11-21]]
^21^ Pero de todos los bichos alados que andan sobre cuatro patas, podréis comer aquellos que además de sus cuatro patas tienen zancas para saltar con ellas sobre el suelo.

[[leviticus-11-22]]
^22^ De ellos podréis comer: la langosta en sus diversas especies y toda clase de solam, de jargol y de jagab.

[[leviticus-11-23]]
^23^ Cualquier otro bicho alado de cuatro patas será para vosotros abominable.

[[leviticus-11-24]]
^24^ Por estos animales podéis contraer impureza. El que toque su cadáver quedará impuro hasta la tarde.

[[leviticus-11-25]]
^25^ El que levante alguno de sus cadáveres tendrá que lavar sus vestidos y quedará impuro hasta la tarde.

[[leviticus-11-26]]
^26^ Asimismo todos los animales que tienen pezuña no partida en dos uñas y no rumian, serán impuros para vosotros. Todo aquel que los toque quedará impuro.

[[leviticus-11-27]]
^27^ De entre los cuadrúpedos os serán impuros todos los que andan sobre las plantas de sus pies. El que toque sus cadáveres quedará impuro hasta la tarde.

[[leviticus-11-28]]
^28^ El que levante el cadáver de uno de ellos tendrá que lavar sus vestidos, y quedará impuro hasta la tarde; son impuros para vosotros.

[[leviticus-11-29]]
^29^ De entre los bichos pequeños que andan arrastrándose por el suelo serán impuros para vosotros: la comadreja, el ratón el lagarto en sus diversas especies,

[[leviticus-11-30]]
^30^ el erizo, el cocodrilo, el camaleón, la salamandra y el topo.

[[leviticus-11-31]]
^31^ Entre todos los bichos, éstos serán impuros para vosotros. Todo el que toque su cadáver quedará impuro hasta la tarde.

[[leviticus-11-32]]
^32^ Quedará impuro cualquier objeto sobre el que caiga uno de sus cadáveres; ya sea un instrumento de madera, o un vestido, una piel, un saco o cualquier utensilio. Será metido en agua y quedará impuro.

[[leviticus-11-33]]
^33^ Si cae uno de estos cadáveres en una vasija de barro, cuanto haya dentro de ella quedará impuro y romperéis la vasija.

[[leviticus-11-34]]
^34^ Toda cosa comestible preparada con dicha agua será impura, y toda bebida que se beba en una de esas vasijas será impura.

[[leviticus-11-35]]
^35^ Cualquier objeto sobre el que caiga alguno de esos cadáveres quedará impuro: el horno y el doble fogón serán derribados; son impuros y los tendréis por impuros.

[[leviticus-11-36]]
^36^ (Solamente las fuentes y cisternas, donde se recogen las aguas, permanecerán puras), pero el que toque sus cadáveres quedará impuro.

[[leviticus-11-37]]
^37^ De igual manera cuando caiga alguno de esos cadáveres sobre una semilla que va a sembrarse, quedará pura;

[[leviticus-11-38]]
^38^ mas si cayese alguno de esos cadáveres sobre semilla mojada, la tendréis por impura.

[[leviticus-11-39]]
^39^ Cuando muera uno de aquellos animales de los que podéis comer, el que toque su cadáver quedará impuro hasta la tarde.

[[leviticus-11-40]]
^40^ El que coma carne de ese cadáver deberá lavar sus vestidos y quedará impuro hasta la tarde. Y el que levante ese cadáver habrá de lavar sus vestidos y quedará impuro hasta la tarde.

[[leviticus-11-41]]
^41^ Todo bicho que anda arrastrándose sobre la tierra es cosa abominable; no se podrá comer.

[[leviticus-11-42]]
^42^ No comeréis ningún animal de los que caminan sobre su vientre o sobre cuatro patas o sobre muchos pies, es decir, ningún bicho que se arrastra por el suelo, porque son abominación.

[[leviticus-11-43]]
^43^ No os hagáis inmundos con ninguna clase de bicho que se arrastra, ni os hagáis impuros con ellos, para que no os contaminéis por su causa.

[[leviticus-11-44]]
^44^ Porque yo soy Yahveh, vuestro Dios; santificaos y sed santos, pues yo soy santo. No os haréis impuros con ninguno de esos bichos que se arrastran por el suelo.

[[leviticus-11-45]]
^45^ Pues yo soy Yahveh, el que os he subido de la tierra de Egipto, para ser vuestro Dios. Sed, pues, santos porque yo soy santo.

[[leviticus-11-46]]
^46^ Esta es la ley acerca de los animales, de las aves, y de todos los seres vivientes que se mueven en el agua, y de todos los que andan arrastrándose sobre la tierra;

[[leviticus-11-47]]
^47^ para que hagáis distinción entre lo impuro y lo puro, entre el animal que puede comerse y el que no puede comerse.
[[leviticus-12]]
== Capítulo 12

[[leviticus-12-1]]
^1^ Yahveh habló a Moisés y dijo:

[[leviticus-12-2]]
^2^ Habla a los israelitas y diles: Cuando una mujer conciba y tenga un hijo varón, quedará impura durante siete días; será impura como en el tiempo de sus reglas.

[[leviticus-12-3]]
^3^ Al octavo día será circuncidado el niño en la carne de su prepucio;

[[leviticus-12-4]]
^4^ pero ella permanecerá todavía 33 días purificándose de su sangre. No tocará ninguna cosa santa ni irá al santuario hasta cumplirse los días de su purificación.

[[leviticus-12-5]]
^5^ Mas si da a luz una niña, durante dos semanas será impura, como en el tiempo de sus reglas, y permanecerá 66 días más purificándose de su sangre.

[[leviticus-12-6]]
^6^ Al cumplirse los días de su purificación, sea por niño o niña, presentará al sacerdote, a la entrada de la Tienda del Encuentro, un cordero de un año como holocausto, y un pichón o una tórtola como sacrificio por el pecado.

[[leviticus-12-7]]
^7^ El sacerdote lo ofrecerá ante Yahveh, haciendo expiación por ella, y quedará purificada del flujo de su sangre. Esta es la ley referente a la mujer que da a luz a un niño o una niña.

[[leviticus-12-8]]
^8^ Mas si a ella no le alcanza para presentar una res menor, tome dos tórtolas o dos pichones, uno como holocausto y otro como sacrificio por el pecado; y el sacerdote hará expiación por ella y quedará pura.
[[leviticus-13]]
== Capítulo 13

[[leviticus-13-1]]
^1^ Yahveh habló a Moisés y a Aarón, diciendo:

[[leviticus-13-2]]
^2^ Cuando uno tenga en la piel de su carne tumor, erupción o mancha blancuzca brillante, y se forme en la piel de su carne como una llaga de lepra, será llevado al sacerdote Aarón o a uno de sus hijos, los sacerdotes.

[[leviticus-13-3]]
^3^ El sacerdote examinará la llaga en la piel de la carne; si el pelo en la llaga se ha vuelto blanco, y la llaga parece más hundida que la piel de su carne, es llaga de lepra; cuando el sacerdote lo haya comprobado, le declarará impuro.

[[leviticus-13-4]]
^4^ Mas si hay en la piel de su carne una mancha blancuzca brillante sin que parezca más hundida que la piel, y sin que el pelo se haya vuelto blanco, el sacerdote recluirá durante siete días al afectado.

[[leviticus-13-5]]
^5^ Al séptimo día el sacerdote lo examinará, y si comprueba que la llaga se ha detenido, no se ha extendido por la piel, el sacerdote entonces lo recluirá otros siete días.

[[leviticus-13-6]]
^6^ Pasados estos siete días, el sacerdote lo examinará nuevamente: si ve que la llaga ha perdido su color y no se ha extendido en la piel, el sacerdote lo declarará puro; no se trata más que de una erupción. Lavará sus vestidos y quedará puro.

[[leviticus-13-7]]
^7^ Pero si después que el sacerdote le ha examinado y declarado puro, sigue la erupción extendiéndose por la piel, se presentará de nuevo al sacerdote.

[[leviticus-13-8]]
^8^ El sacerdote, al comprobar que la erupción se extiende por la piel, lo declarará impuro: es un caso de lepra.

[[leviticus-13-9]]
^9^ Cuando en un hombre se manifieste una llaga como de lepra, será llevado al sacerdote.

[[leviticus-13-10]]
^10^ El sacerdote lo examinará, y si observa un tumor blancuzco en la piel, el color del pelo mudado en blanco y una úlcera en la hinchazón,

[[leviticus-13-11]]
^11^ se trata de lepra arraigada en su piel; el sacerdote lo declarará impuro y no le recluirá, porque es impuro.

[[leviticus-13-12]]
^12^ Pero si la lepra se ha extendido por la piel hasta cubrir toda la piel del enfermo desde la cabeza hasta los pies, en cuanto alcanza a verlo el sacerdote,

[[leviticus-13-13]]
^13^ éste lo examinará, y si la lepra ha cubierto toda su carne, declarará puro al afectado por la llaga: se ha vuelto todo blanco; es puro.

[[leviticus-13-14]]
^14^ Pero cuando se vea en él una úlcera, quedará impuro;

[[leviticus-13-15]]
^15^ en cuanto el sacerdote vea la úlcera, lo declarará impuro. La úlcera es impura; es un caso de lepra.

[[leviticus-13-16]]
^16^ Pero si la úlcera cambia, volviéndose blanca, el afectado ha de presentarse al sacerdote.

[[leviticus-13-17]]
^17^ El sacerdote lo examinará, y al ver que la llaga se ha vuelto blanca, declarará puro al afectado por la enfermedad: es puro.

[[leviticus-13-18]]
^18^ Cuando en la piel de alguno se ha curado un divieso,

[[leviticus-13-19]]
^19^ y en el lugar del divieso aparece un tumor blanco, o una mancha de color blanco rojizo, ése habrá de presentarse al sacerdote.

[[leviticus-13-20]]
^20^ El sacerdote lo examinará, y si la mancha parece más hundida que la piel y su pelo se ha vuelto blanco, el sacerdote lo declarará impuro. Es llaga de lepra que se ha producido en el divieso.

[[leviticus-13-21]]
^21^ Pero si el sacerdote ve que no hay en ella pelo blanco, ni está más hundida que la piel, y que ha perdido color, le recluirá por siete días.

[[leviticus-13-22]]
^22^ Si entonces se extiende por la piel, el sacerdote lo declarará impuro; es un caso de lepra.

[[leviticus-13-23]]
^23^ Pero si la mancha sigue estacionaria, sin extenderse, es la cicatriz del divieso; el sacerdote lo declarará puro.

[[leviticus-13-24]]
^24^ Cuando en la piel de alguien hay una quemadura, y sobre la quemadura se forma una mancha de color blanco rojizo o sólo blanco,

[[leviticus-13-25]]
^25^ el sacerdote la examinará; y si el pelo se ha vuelto blanco en la mancha blanca y ésta aparece más hundida que la piel, es que se ha producido lepra en la quemadura. El sacerdote lo declarará impuro; es un caso de lepra.

[[leviticus-13-26]]
^26^ Si, en cambio, el sacerdote observa que en la mancha no aparece pelo blanco, que no está más hundida que la piel y que ha perdido color, lo recluirá siete días.

[[leviticus-13-27]]
^27^ Al séptimo día lo examinará, y si se ha extendido por la piel, el sacerdote lo declarará impuro; es un caso de lepra.

[[leviticus-13-28]]
^28^ Pero si la mancha sigue estacionaria sin extenderse por la piel y ha perdido color, se trata de la hinchazón de la quemadura, y el sacerdote lo declarará puro; pues es la cicatriz de la quemadura.

[[leviticus-13-29]]
^29^ Cuando un hombre o una mujer tengan una llaga en la cabeza o en la barbilla,

[[leviticus-13-30]]
^30^ el sacerdote examinará la llaga, y si ésta aparece más hundida que la piel, y si hay en ella pelo amarillento y más ralo, el sacerdote lo declarará impuro; es tiña, o sea, lepra de la cabeza o de la barbilla.

[[leviticus-13-31]]
^31^ Mas si el sacerdote ve que la llaga de tiña no aparece más hundida que la piel, y que no hay en ella pelo amarillento, recluirá al afectado por la tiña durante siete días.

[[leviticus-13-32]]
^32^ Al séptimo, el sacerdote examinará el mal, y si no se ha extendido la tiña, ni hay en ella pelo amarillento, ni la llaga aparece más hundida que la piel,

[[leviticus-13-33]]
^33^ aquella persona se afeitará, excepto en el lugar de la tiña; y el sacerdote recluirá al afectado durante otros siete días.

[[leviticus-13-34]]
^34^ Al séptimo día el sacerdote lo examinará y si no se ha extendido la llaga por la piel, ni aparece más hundida que la piel, le declarará puro; lavará sus vestidos y quedará puro.

[[leviticus-13-35]]
^35^ Pero si la tiña, después de la purificación, se extiende mucho por la piel,

[[leviticus-13-36]]
^36^ el sacerdote lo examinará. Si comprueba que la tiña se ha extendido por la piel, el sacerdote ya no tendrá que buscar pelo amarillento; aquella persona es impura.

[[leviticus-13-37]]
^37^ Mas si, según su opinión, la tiña no se ha extendido y ha brotado en ella pelo negro, se ha curado la tiña. Esa persona es pura y el sacerdote la declarará pura.

[[leviticus-13-38]]
^38^ Cuando un hombre o una mujer tengan en su piel manchas brillantes, manchas blancas,

[[leviticus-13-39]]
^39^ el sacerdote las examinará; si comprueba que las manchas de la piel son de color blanco, se trata de un eccema que ha brotado en la piel; esta persona es pura.

[[leviticus-13-40]]
^40^ Si a alguno se le cae el pelo de la cabeza y queda calvo por detrás, es puro.

[[leviticus-13-41]]
^41^ Si se le cae el pelo de la parte delantera de la cabeza, es calvo por delante, pero es puro.

[[leviticus-13-42]]
^42^ Pero si en la calva, por detrás o por delante, aparece una llaga de color rojizo, es lepra que se ha producido en la calva, sea por detrás o por delante.

[[leviticus-13-43]]
^43^ El sacerdote la examinará y si la hinchazón de la llaga en la parte calva es de color blanco rojizo, con aspecto de lepra en la piel,

[[leviticus-13-44]]
^44^ se trata de un leproso: es impuro. El sacerdote le declarará impuro; tiene lepra en la cabeza.

[[leviticus-13-45]]
^45^ El afectado por la lepra llevará los vestido rasgados y desgreñada la cabeza, se cubrirá hasta el bigote e irá gritando: «¡Impuro, impuro!»

[[leviticus-13-46]]
^46^ Todo el tiempo que dure la llaga, quedará impuro. Es impuro y habitará solo; fuera del campamento tendrá su morada.

[[leviticus-13-47]]
^47^ Cuando aparezca una llaga de lepra en un vestido de lana o de lino,

[[leviticus-13-48]]
^48^ o en tejido o cobertor de lino o lana, o en una piel, o en cualquier objeto de cuero,

[[leviticus-13-49]]
^49^ si la mancha en el vestido o en la piel, o en el tejido o en el cobertor, o en cualquier objeto hecho de cuero, tiene color verdoso o rojizo, es llaga de lepra y debe ser mostrada al sacerdote.

[[leviticus-13-50]]
^50^ El sacerdote examinará la mancha y encerrará el objeto manchado durante siete días.

[[leviticus-13-51]]
^51^ Al séptimo, el sacerdote examinará la mancha y si se ha extendido por el vestido, tejido, cobertor, piel o por un objeto de cuero, es un caso de lepra maligna y el objeto es impuro.

[[leviticus-13-52]]
^52^ Se quemará el vestido, tejido, cobertor de lana o de lino o el objeto de cuero en que se encuentre la mancha, pues es lepra maligna; será quemado.

[[leviticus-13-53]]
^53^ Pero si el sacerdote ve que no se ha extendido la mancha por el vestido, tejido, cobertor o el objeto de cuero,

[[leviticus-13-54]]
^54^ hará lavar el objeto manchado y lo encerrará otros siete días.

[[leviticus-13-55]]
^55^ Si el sacerdote ve que la mancha, después de haber sido lavada, no ha mudado de aspecto, aunque la mancha no se haya extendido, el objeto es impuro; lo entregarás al fuego: es una infección por la cara y el envés.

[[leviticus-13-56]]
^56^ Pero si el sacerdote ve que la parte manchada, después de lavada, ha perdido color, la rasgará del vestido, del cuero, del tejido o del cobertor.

[[leviticus-13-57]]
^57^ Pero si vuelve a aparecer en el vestido, tejido, cobertor o en un objeto de cuero, es mal contagioso; quemarás lo que está afectado por la lepra.

[[leviticus-13-58]]
^58^ En cuanto al vestido, tejido, cobertor o el objeto de cuero, que después de ser lavado pierdan la mancha, serán lavados por segunda vez y quedarán puros.

[[leviticus-13-59]]
^59^ Estas es la ley para la mancha de lepra que se halla en los vestidos de lana o de lino, en el tejido e en el cobertor o en cualquier objeto hecho de cuero, para declararlos puros o impuros.
[[leviticus-14]]
== Capítulo 14

[[leviticus-14-1]]
^1^ Yahveh habló a Moisés diciendo:

[[leviticus-14-2]]
^2^ Esta es la ley que ha de aplicarse al leproso en el día de su purificacíon. Se le conducirá al sacerdote,

[[leviticus-14-3]]
^3^ y el sacerdote saldrá fuera del campamento; si, tras de haberlo examinado, comprueba que el leproso está ya curado de la llaga de lepra,

[[leviticus-14-4]]
^4^ el sacerdote mandará traer para el que ha de ser purificado dos pájaros vivos y puros, madera de cedro, púrpura escarlata e hisopo.

[[leviticus-14-5]]
^5^ Después mandará inmolar uno de los pájaros sobre una vasija de barro con agua viva.

[[leviticus-14-6]]
^6^ Tomará luego el pájaro vivo, la madera de cedro, la púrpura escarlata y el hisopo, los mojará, juntamente con el pájaro vivo, en la sangre del pájaro inmolado sobre el agua viva,

[[leviticus-14-7]]
^7^ y rociará siete veces al que ha de ser purificado de la lepra. Y, tras de declararlo puro, soltará en el campo el pájaro vivo.

[[leviticus-14-8]]
^8^ El que se purifica lavará sus vestidos, se afeitará todo su pelo, se bañará en agua, y quedará limpio. Después podrá entrar en el campamento; pero durante siete días ha de habitar fuera de su tienda.

[[leviticus-14-9]]
^9^ El día séptimo se afeitará todo su pelo, su cabellera, su barba, sus cejas, es decir, se afeitará todo su pelo, lavará también sus vestidos, bañará su cuerpo en agua y quedará limpio.

[[leviticus-14-10]]
^10^ El día octavo tomará dos corderos sin defecto y una cordera de un año sin defecto; y como oblación, tres décimas de flor de harina amasada con aceite y un cuartillo de aceite.

[[leviticus-14-11]]
^11^ El sacerdote que hace la purificación presentará ante Yahveh, junto con todas esas cosas, al hombre que ha de purificarse, a la entrada de la Tienda del Encuentro.

[[leviticus-14-12]]
^12^ El sacerdote tomará uno de los corderos para ofrecerlo como sacrificio de reparación, además del cuartillo de aceite, y lo mecerá como ofrenda ante Yahveh.

[[leviticus-14-13]]
^13^ Luego inmolará el cordero en el lugar donde se inmola el sacrificio por el pecado y el holocausto, en lugar sagrado; porque, tanto en el sacrificio por el pecado como en el sacrificio de reparación, la víctima pertenece al sacerdote; es cosa sacratísima.

[[leviticus-14-14]]
^14^ Después el sacerdote tomará sangre de la víctima de reparación y mojará el lóbulo de la oreja derecha del que se está purificando, el pulgar de su mano derecha y el de su pie derecho.

[[leviticus-14-15]]
^15^ Y, tomando del cuartillo de aceite, el sacerdote echará parte de él sobre la palma de su mano izquierda.

[[leviticus-14-16]]
^16^ Después untará un dedo de su mano derecha en el aceite que tiene en la palma de su mano izquierda, y con su dedo hará siete aspersiones de aceite delante de Yahveh.

[[leviticus-14-17]]
^17^ Con el aceite restante que tiene en su mano el sacerdote untará el lóbulo de la oreja derecha del que se purifica, el pulgar de su mano derecha y el de su pie derecho sobre la sangre de la víctima de reparación.

[[leviticus-14-18]]
^18^ El resto del aceite que quede en la mano del sacerdote, se echará sobre la cabeza del que se purifica. El sacerdote expiará así por él ante Yahveh.

[[leviticus-14-19]]
^19^ El sacerdote ofrecerá el sacrificio por el pecado y hará expiación por el que se purifica de su impureza; después inmolará el holocausto.

[[leviticus-14-20]]
^20^ Y ofrecerá sobre el altar el holocausto y la oblación. De esta manera el sacerdote hará expiación por él y quedará limpio.

[[leviticus-14-21]]
^21^ Si es pobre y no tiene suficientes recursos, tomará un cordero com sacrificio de reparación, como ofrenda mecida, para hacer expiación por él, y además, como oblación, una décima de flor de harina amasada con aceite, un cuartillo de aceite,

[[leviticus-14-22]]
^22^ y dos tórtolas o dos pichones, según sus recursos, uno como sacrificio por el pecado, y otro como holocausto.

[[leviticus-14-23]]
^23^ Al octavo día, los llevará al sacerdote, a la entrada de la Tienda del Encuentro para su purificación delante de Yahveh.

[[leviticus-14-24]]
^24^ El sacerdote tomará el cordero del sacrificio de reparación y el cuartillo de aceite, y los mecerá como ofrenda ante Yahveh.

[[leviticus-14-25]]
^25^ Después de haber inmolado el cordero del sacrificio de reparación, el sacerdote tomará sangre de la víctima de reparación y mojará el lóbulo de la oreja derecha del que se purifica, el pulgar de su mano derecha y el de su pie derecho.

[[leviticus-14-26]]
^26^ Luego derramará parte del aceite sobre la palma de su mano izquierda;

[[leviticus-14-27]]
^27^ con un dedo de su mano derecha hará ante Yahveh siete aspersiones con el aceite que tiene en la palma de la mano izquierda,

[[leviticus-14-28]]
^28^ untará con el aceite que tiene en su mano el lóbulo de la oreja derecha del que se purifica, el pulgar de su mano derecha y el de su pie derecho, en el lugar donde puso la sangre de la víctima de reparación.

[[leviticus-14-29]]
^29^ Derramará el resto del aceite que le quede en la mano sobre la cabeza del que se purifica, haciendo expiación por él ante Yahveh.

[[leviticus-14-30]]
^30^ Luego ofrecerá, conforme a los recursos suyos, una de las tórtolas o de los pichones,

[[leviticus-14-31]]
^31^ es decir, lo que alcanzan sus recursos, uno como sacrificio por el pecado, y otro como holocausto, además de la oblación. De este modo el sacerdote hará expiación ante Yahveh por aquel que se purifica.

[[leviticus-14-32]]
^32^ Esta es la ley de purificación para aquel que tiene llaga de lepra y cuyos recursos son limitados.

[[leviticus-14-33]]
^33^ Yahveh habló a Moisés y a Aarón diciendo:

[[leviticus-14-34]]
^34^ Cuando hayáis entrado en la tierra de Canaán que yo os doy en posesión, y castigue con lepra alguna de las casas de la tierra que poseeréis,

[[leviticus-14-35]]
^35^ el propietario de la casa irá a avisar al sacerdote, diciendo: «Ha aparecido algo como lepra en mi casa».

[[leviticus-14-36]]
^36^ El sacerdote, antes de entrar en la casa para examinar la lepra, ordenará que desocupen la casa, para que nada quede inmundo de cuanto hay en ella. Después entrará el sacerdote a examinar la casa.

[[leviticus-14-37]]
^37^ Si al examinarla observa que la mancha forma en las paredes de la casa cavidades verdosas y rojizas que parecen hundidas en la pared,

[[leviticus-14-38]]
^38^ el sacerdote saldrá a la puerta de la casa y la cerrará durante siete días.

[[leviticus-14-39]]
^39^ Volverá al día séptimo, y si comprueba que la mancha se ha extendido por las paredes de la casa,

[[leviticus-14-40]]
^40^ mandará arrancar las piedras manchadas y arrojarlas fuera de la ciudad en un lugar inmundo.

[[leviticus-14-41]]
^41^ Hará raspar todo el interior de la casa; y echarán fuera de la ciudad, en un lugar inmundo, el polvo que hayan quitado.

[[leviticus-14-42]]
^42^ Luego tomarán otras piedras y las pondrán en lugar de las primeras; y también argamasa nueva para revocar la casa.

[[leviticus-14-43]]
^43^ Si la mancha vuelve a extenderse por la casa después de haber arrancado las piedras, y de haberla raspado y revocado,

[[leviticus-14-44]]
^44^ el sacerdote entrará de nuevo; y si comprueba que la mancha se ha extendido por la casa, hay un caso de lepra maligna en la casa, y ésta es impura.

[[leviticus-14-45]]
^45^ Se derribará la casa. Sus piedras, sus maderas y todo el material de la casa será sacado fuera de la ciudad a un lugar inmundo.

[[leviticus-14-46]]
^46^ Quien entre en esa casa durante el tiempo que esté clausurada quedará impuro hasta la tarde.

[[leviticus-14-47]]
^47^ El que duerma en ella habrá de lavar sus vestidos; y también el que coma en ella habrá de lavarlos.

[[leviticus-14-48]]
^48^ Mas si el sacerdote comprueba al entrar que, después de revocada la casa, la mancha no se ha extendido por ella, la declarará pura, pues se ha curado del mal.

[[leviticus-14-49]]
^49^ Entonces, para ofrecer por la casa un sacrificio por el pecado, tomará dos pájaros, madera de cedro, púrpura escarlata e hisopo;

[[leviticus-14-50]]
^50^ inmolará uno de los pájaros sobre una vasija de barro con agua viva

[[leviticus-14-51]]
^51^ y, tomando la madera de cedro, el hisopo y la púrpura escarlata, con el pájaro vivo, los mojará en la sangre del pájaro degollado y en el agua viva; y rociará la casa siete veces.

[[leviticus-14-52]]
^52^ Y, tras haber realizado el sacrificio por el pecado en favor de la casa con la sangre del pájaro, con el agua viva, el pájaro vivo, la madera de cedro, el hisopo y la lana escarlata,

[[leviticus-14-53]]
^53^ soltará el pájaro vivo fuera de la ciudad, en el campo. De este modo hará expiación por la casa, la cual quedará pura.

[[leviticus-14-54]]
^54^ Esta es la ley para toda clase de lepra o de tiña,

[[leviticus-14-55]]
^55^ para la lepra del vestido y de la casa,

[[leviticus-14-56]]
^56^ para los tumores, erupciones y manchas blancas,

[[leviticus-14-57]]
^57^ y para declarar los períodos de impureza y de pureza. Esta es la ley de la lepra.
[[leviticus-15]]
== Capítulo 15

[[leviticus-15-1]]
^1^ Yahveh habló a Moisés y Aarón diciendo:

[[leviticus-15-2]]
^2^ Hablad a los israelitas y decidles: Cualquier hombre que padece flujo seminal es impuro a causa del flujo.

[[leviticus-15-3]]
^3^ En esto consiste la impureza causada por su flujo: sea que su cuerpo deje destilar el flujo, o lo retenga, es impuro.

[[leviticus-15-4]]
^4^ Todo lecho en que duerma el que padece flujo será impuro y todo asiento en que se siente será impuro.

[[leviticus-15-5]]
^5^ Quien toque su lecho lavará sus vestidos, se bañará en agua y quedará impuro hasta la tarde.

[[leviticus-15-6]]
^6^ Quien se siente sobre un mueble donde se haya sentado cualquiera que padece flujo lavará sus vestidos, se bañará en agua y será impuro hasta la tarde.

[[leviticus-15-7]]
^7^ Quien toque el cuerpo del que padece flujo lavará sus vestidos, se bañará en agua y será impuro hasta la tarde.

[[leviticus-15-8]]
^8^ Si el que tiene flujo escupe sobre un hombre puro, éste lavará sus vestidos, se bañará en agua y quedará impuro hasta la tarde.

[[leviticus-15-9]]
^9^ Todo aparejo sobre el cual haya montado el que padece flujo será inmundo.

[[leviticus-15-10]]
^10^ Quien toque un objeto que haya estado debajo de él quedará impuro hasta la tarde. Y el que los lleve lavará sus vestidos, se bañará en agua y será impuro hasta la tarde.

[[leviticus-15-11]]
^11^ Todo aquel a quien toque el que padece flujo sin haberse lavado las manos con agua lavará sus vestidos, se bañará en agua y quedará impuro hasta la tarde.

[[leviticus-15-12]]
^12^ Toda vasija de barro tocada por el que padece flujo será rota, y todo utensilio de madera será lavado con agua.

[[leviticus-15-13]]
^13^ Si el que padece flujo sana de él, se contarán siete días para su purificaión; después lavará sus vestidos, se bañará en agua viva y quedará puro.

[[leviticus-15-14]]
^14^ Al día octavo tomará dos tórtolas o dos pichones y se presentará ante Yahveh a la entrada de la Tienda del Encuentro, para entregarlos al sacerdote.

[[leviticus-15-15]]
^15^ El sacerdote los ofrecerá, uno como sacrificio por el pecado, el otro como holocausto, y de esta manera el sacerdote hará expiación por él ante Yahveh, a causa de su flujo.

[[leviticus-15-16]]
^16^ El hombre que tenga derrame seminal lavará con agua todo su cuerpo y quedará impuro hasta la tarde.

[[leviticus-15-17]]
^17^ Toda ropa y todo cuero sobre los cuales se haya derramado el semen serán lavados con agua y quedarán impuros hasta la tarde.

[[leviticus-15-18]]
^18^ Cuando una mujer se acueste con un hombre, produciéndose efusión de semen, se bañarán ambos con agua y quedarán impuros hasta la tarde.

[[leviticus-15-19]]
^19^ La mujer que tiene flujo, el flujo de sangre de su cuerpo, permanecerá en su impureza por espacio de siete días. Y quien la toque será impuro hasta la tarde.

[[leviticus-15-20]]
^20^ Todo aquello sobre lo que se acueste durante su impureza quedará impuro; y todo aquello sobre lo que se siente quedará impuro.

[[leviticus-15-21]]
^21^ Quien toque su lecho lavará los vestidos, se bañará en agua y permanecerá impuro hasta la tarde.

[[leviticus-15-22]]
^22^ Quien toque un mueble cualquiera sobre el que ella se haya sentado lavará sus vestidos, se bañará en agua y será impuro hasta la tarde.

[[leviticus-15-23]]
^23^ Quien toque algo que esté puesto sobre el lecho o sobre el mueble donde ella se sienta quedará impuro hasta la tarde.

[[leviticus-15-24]]
^24^ Si uno se acuesta con ella se contamina de la impureza de sus reglas y queda impuro siete días; todo lecho en que él se acueste será impuro.

[[leviticus-15-25]]
^25^ Cuando una mujer tenga flujo de sangre durante muchos días, fuera del tiempo de sus reglas o cuando sus reglas se prolonguen, quedará impura mientras dure el flujo de su impureza como en los días del flujo menstrual.

[[leviticus-15-26]]
^26^ Todo lecho en que se acueste mientras dura su flujo será impuro como el lecho de la menstruación, y cualquier mueble sobre el que se siente quedará impuro como en la impureza de las reglas.

[[leviticus-15-27]]
^27^ Quien los toque quedará impuro y lavará sus vestidos, se bañará en agua u quedará impuro hasta la tarde.

[[leviticus-15-28]]
^28^ Una vez que ella sane de su flujo, contará siete días, quedando después pura.

[[leviticus-15-29]]
^29^ Al octavo día tomará para sí dos tórtolas o dos pichones y los presentará al sacerdote a la entrada de la Tienda del Encuentro.

[[leviticus-15-30]]
^30^ El sacerdote los ofrecerá uno como sacrificio por el pecado, el otro como holocausto; y hará expiación por ella ante Yahveh por la impureza de su flujo.

[[leviticus-15-31]]
^31^ Mantendréis alejados a los israelitas de sus impurezas para que no mueran a causa de ellas por contaminar mi Morada, la que está en medio de ellos.

[[leviticus-15-32]]
^32^ Esta es la ley relativa al hombre que padece flujo o que se hace impuro con efusión de semen,

[[leviticus-15-33]]
^33^ a la indispuesta por el flujo menstrual, a aquel que padece flujo, sea varón o mujer, y a aquel que se acueste con una mujer en período de impureza.
[[leviticus-16]]
== Capítulo 16

[[leviticus-16-1]]
^1^ Yahveh habló a Moisés después de la muerte de los dos hijos de Aarón que murieron al acercarse a Yahveh.

[[leviticus-16-2]]
^2^ Dijo Yahveh a Moisés: Di a tu hermano Aarón que no entre en cualquier tiempo en el santuario que está tras el velo, ante el propiciatorio que está encima del arca, no sea que muera: pues yo me hago ver en la nube encima del propiciatorio.

[[leviticus-16-3]]
^3^ Sólo en estas condiciones podrá entrar Aarón en el santuario: con un novillo para el sacrificio por el pecado y un carnero para el holocausto.

[[leviticus-16-4]]
^4^ Se vestirá con la túnica sagrada de lino, se pondrá los calzones de lino, se ceñirá la faja de lino y se cubrirá con la tiara de lino. Estas son las vestiduras sagradas que vestirás después de haberse lavado con agua.

[[leviticus-16-5]]
^5^ Recibirá de la comunidad de los israelitas dos machos cabríos para el holocausto.

[[leviticus-16-6]]
^6^ Después de ofrecer su novillo por el pecado como expiación por sí mismo y por su casa,

[[leviticus-16-7]]
^7^ tomará Aarón los dos machos cabríos y los presentará ante Yahveh, a la entrada de la Tienda del Encuentro.

[[leviticus-16-8]]
^8^ Luego echará suertes sobre los dos machos cabríos, una para Yahveh, y otra para Azazel.

[[leviticus-16-9]]
^9^ Presentará el macho cabrío sobre el cual haya caído la suerte «para Yahveh» ofreciéndolo como sacrificio por el pecado.

[[leviticus-16-10]]
^10^ El macho cabrío sobre el cual haya caído la suerte «para Azazel», lo colocará vivo delante de Yahveh para hacer sobre él la expiación y echarlo al desierto, para Azazel.

[[leviticus-16-11]]
^11^ Entonces ofrecerá Aarón su novillo por el pecado para hacer expiación por sí mismo y por su casa, y lo inmolará.

[[leviticus-16-12]]
^12^ Tomará después un incensario lleno de brasas tomadas del altar que está ante Yahveh y dos puñados de incienso aromático en polvo y, llevándolo detrás del velo,

[[leviticus-16-13]]
^13^ pondrá el incienso sobre el fuego, delante de Yahveh, para que la nube del incienso envuelva el propiciatorio que está encima del Testimonio y él no muera.

[[leviticus-16-14]]
^14^ Tomando luego la sangre del novillo, rociará con su dedo el lado oriental del propiciatorio, y con su dedo hará siete aspersiones de sangre delante del propiciatorio.

[[leviticus-16-15]]
^15^ Después inmolará el macho cabrío como sacrificio por el pecado del pueblo y llevará su sangre detrás del velo, haciendo con su sangre lo que hizo con la sangre del novillo: rociará el propiciatorio y su parte anterior.

[[leviticus-16-16]]
^16^ Así purificará el santuario de las impurezas de los israelitas y de sus rebeldías en todos sus pecados. Lo mismo hará con la Tienda del Encuentro que mora con ellos en medio de sus impurezas.

[[leviticus-16-17]]
^17^ Nadie debe estar en la Tienda del Encuentro cuando Aarón entre a hacer la expiación dentro del santuario, hasta que salga. Después de haber hecho expiación por sí mismo, por su casa y por toda la asamblea de Israel,

[[leviticus-16-18]]
^18^ saldrá hacia el altar que se halla ante Yahveh, y hará por él expiación tomando sangre del novillo y del macho cabrío y untando los cuernos en torno del altar.

[[leviticus-16-19]]
^19^ Hará sobre él con su dedo siete aspersiones de sangre, y así lo purificará y lo separará de las impurezas de los israelitas.

[[leviticus-16-20]]
^20^ Acabada la expiación del santuario, de la Tienda del Encuentro y del altar, Aarón presentará el macho cabrío vivo.

[[leviticus-16-21]]
^21^ Imponiendo ambas manos sobre la cabeza del macho cabrío vivo hará confesión sobre él de todas las iniquidades de los israelitas y de todas las rebeldías en todos los pecados de ellos y cargándolas sobre la cabeza del macho cabrío, lo enviará al desierto por medio de un hombre dispuesto para ello.

[[leviticus-16-22]]
^22^ Así el macho cabrío llevará sobre sí todas las iniquidades de ellos, hacia una tierra árida; y soltará el macho cabrío en el desierto.

[[leviticus-16-23]]
^23^ Luego entrará Aarón en la Tienda del Encuentro y, despojándose de las vestiduras de lino con que se había vestido al entrar en el santuario, las dejará allí;

[[leviticus-16-24]]
^24^ lavará su cuerpo con agua en lugar sagrado y se pondrá sus vestiduras. Después saldrá y ofrecerá su holocausto y el holocausto del pueblo, hará la expiación por sí mismo y por el pueblo,

[[leviticus-16-25]]
^25^ y quemará sobre el altar el sebo de la víctima por el pecado.

[[leviticus-16-26]]
^26^ El hombre encargado de soltar el macho cabrío para Azazel lavará sus vestidos y bañará su cuerpo en agua; después de esto podrá entrar en el campamento.

[[leviticus-16-27]]
^27^ Del novillo del sacrificio por el pecado y del macho cabrío inmolado por el pecado, cuya sangre fue introducida en el santuario para hacer expiación, serán sacados fuera del campamento y quemados con fuego sus pieles, su carne y sus excrementos.

[[leviticus-16-28]]
^28^ El que los queme lavará sus vestidos y se bañará en agua; después de esto podrá entrar en el campamento.

[[leviticus-16-29]]
^29^ Será éste para vosotros un decreto perpetuo: En el mes séptimo, el día décimo del mes, ayunaréis, y no haréis trabajo alguno, ni el nativo ni el forastero que reside en medio de vosotros.

[[leviticus-16-30]]
^30^ Porque en ese día se hará expiación por vosotros para purificaros. De todos vuestros pecados quedaréis limpios delante de Yahveh.

[[leviticus-16-31]]
^31^ Será para vosotros día de descanso completo, en el que habéis de ayunar: decreto perpetuo.

[[leviticus-16-32]]
^32^ Hará la expiación el sacerdote ungido y de manos consagradas para ejercer el sacerdocio como sucesor de su padre: él se vestirá las vestiduras de lino, las vestiduras sagradas,

[[leviticus-16-33]]
^33^ y hará la expiación del santuario sagrado, de la Tienda del Encuentro y del altar. El hará también la expiación por los sacerdotes y por todo el pueblo de la asamblea.

[[leviticus-16-34]]
^34^ Tendréis esto como decreto perpetuo: hacer la expiación por los israelitas, por todos sus pecados, una vez al año. Y se hizo como Yahveh había mandado a Moisés.
[[leviticus-17]]
== Capítulo 17

[[leviticus-17-1]]
^1^ Yahveh habló a Moisés, diciendo:

[[leviticus-17-2]]
^2^ Habla a Aarón y a sus hijos, y a todos los israelitas, y diles: Esta es la orden que ha dado Yahveh:

[[leviticus-17-3]]
^3^ Cualquier hombre de la casa de Israel que inmole buey, oveja o cabra dentro del campamento, o fuera del mismo,

[[leviticus-17-4]]
^4^ sin llevarlos a la entrada de la Tienda del Encuentro, para presentarlos como ofrenda a Yahveh ante la Morada de Yahveh, será considerado reo de sangre. Tal hombre ha derramado sangre y será exterminado de en medio de su pueblo.

[[leviticus-17-5]]
^5^ Por eso los israelitas presentarán al sacerdote, para Yahveh, a la entrade de la Tienda del Encuentro, aquellas víctimas que suelen inmolar en el campo, para que se ofrezcan como sacrificios de comunión.

[[leviticus-17-6]]
^6^ El sacerdote derramará la sangre sobre el altar de Yahveh, a la entrada de la Tienda del Encuentro, y quemará las grasas como calmante aroma para Yahveh.

[[leviticus-17-7]]
^7^ De este modo ellos ya no seguirán sacrificando sus sacrificios a los sátiros tras los cuales estaban prostituyéndose. Decreto perpetuo será éste para ellos de generación en generación.

[[leviticus-17-8]]
^8^ Diles: Cualquier hombre de la casa de Israel, o de los forasteros que residen en medio de ellos, que ofrezca holocausto o sacrificio,

[[leviticus-17-9]]
^9^ y no lo traiga a la entrada de la Tienda del Encuentro para sacrificarlo en honor de Yahveh, ese será exterminado de entre su parentela.

[[leviticus-17-10]]
^10^ Si un hombre cualquiera de la casa de Israel, o de los forasteros que residen en medio de ellos, come cualquier clase de sangre, yo volveré mi rostro contra el que coma sangre y los exterminaré de en medio de su pueblo.

[[leviticus-17-11]]
^11^ Porque la vida de la carne está en la sangre, y yo os la doy para hacer expiación en el altar por vuestras vidas, pues la expiación por la vida, con la sangre se hace.

[[leviticus-17-12]]
^12^ Por eso tengo dicho a los israelitas: «Ninguno de vosotros comerá sangre; ni tampoco coma sangre el forastero que reside en medio de vosotros».

[[leviticus-17-13]]
^13^ Cualquier hombre de la casa de Israel, o de los forasteros que residen en medio de ellos, que cace un animal o un ave que es lícito comer, derramará su sangre y la cubrirá con tierra.

[[leviticus-17-14]]
^14^ Porque la vida de toda carne es su sangre. Por eso mando a los israelitas: «No comeréis la sangre de ninguna carne, pues la vida de toda carne es su sangre. Quien la coma, será exterminado».

[[leviticus-17-15]]
^15^ Todo nativo o forastero que coma carne de bestia muerta o destrozada lavará sus vestidos, se bañará en agua y quedará impuro hasta la tarde; después será puro.

[[leviticus-17-16]]
^16^ Si no los lava ni baña su cuerpo, cargará con su iniquidad.
[[leviticus-18]]
== Capítulo 18

[[leviticus-18-1]]
^1^ Habló Yahveh a Moisés, diciendo:

[[leviticus-18-2]]
^2^ Habla a los israelitas, y diles: Yo soy Yahveh vuestro Dios.

[[leviticus-18-3]]
^3^ No hagáis como se hace en la tierra de Egipto, donde habéis habitado, ni hagáis como se hace en la tierra de Canaán a donde os llevo; no debéis seguir sus costumbres.

[[leviticus-18-4]]
^4^ Cumplid mis normas y guardad mis preceptos, caminando según ellos. Yo soy Yahveh, vuestro Dios.

[[leviticus-18-5]]
^5^ Guardad mis preceptos y mis normas. El hombre que los cumpla, por ellos vivirá. Yo, Yahveh.

[[leviticus-18-6]]
^6^ Ninguno de vosotros se acerque a una consanguínea suya para descubrir su desnudez. Yo, Yahveh.

[[leviticus-18-7]]
^7^ No descubrirás la desnudez de tu padre ni la desnudez de tu madre. Es tu madre; no descubrirás su desnudez.

[[leviticus-18-8]]
^8^ No descubrirás la desnudez de la mujer de tu padre; es la misma desnudez de tu padre.

[[leviticus-18-9]]
^9^ No descubrirás la desnudez de tu hermana, hija de tu padre o hija de tu madre, nacida en casa o fuera de ella.

[[leviticus-18-10]]
^10^ No descubrirás la desnudez de la hija de tu hijo o de la hija de tu hija, pues es tu propia desnudez.

[[leviticus-18-11]]
^11^ Nu descubrirás la desnudez de la hija de la mujer de tu padre, engendrada de tu padre, que es tu hermana.

[[leviticus-18-12]]
^12^ No descubrirás la desnudez de la hermana de tu padre; es carne de tu padre.

[[leviticus-18-13]]
^13^ No descubrirás la desnudez de la hermana de tu madre; es carne de tu madre.

[[leviticus-18-14]]
^14^ No descubrirás la desnudez del hermano de tu padre; no te acercarás a su mujer; es la mujer de tu tío.

[[leviticus-18-15]]
^15^ No descubrirás la desnudez de tu nuera, es la mujer de tu hijo; no descubrirás su desnudez.

[[leviticus-18-16]]
^16^ No descubrirás la desnudez de la mujer de tu hermano; es la desnudez de tu hermano.

[[leviticus-18-17]]
^17^ No descubrirás la desnudez de una mujer y la de su hija, ni tomarás la hija de su hijo ni la hija de su hija para descubrir su desnudez; son tu propia carne; sería un incesto.

[[leviticus-18-18]]
^18^ No tomarás a una mujer juntamente con su hermana, haciéndola rival de ella y descubriendo su desnudez mientras viva la primera.

[[leviticus-18-19]]
^19^ Tampoco te acercarás a una mujer durante la impureza menstrual, para descubrir su desnudez.

[[leviticus-18-20]]
^20^ No te juntes carnalmente con la mujer de tu prójimo, contaminándote con ella.

[[leviticus-18-21]]
^21^ No darás ningún hijo tuyo para hacerlo pasar ante Mólek; no profanarás así el nombre de tu Dios. Yo, Yahveh.

[[leviticus-18-22]]
^22^ No te acostarás con varón como con mujer; es abominación.

[[leviticus-18-23]]
^23^ No te unirás con bestia haciéndote impuro por ella. La mujer no se pondrá ante una bestia para unirse con ella; es una imfamia.

[[leviticus-18-24]]
^24^ No os hagáis impuros con ninguna de estas acciones, pues con ellas se han hecho impuras las naciones que yo voy a arrojar ante vosotros.

[[leviticus-18-25]]
^25^ Se ha hecho impuro el país; por eso he castigado su iniquidad, y el país ha vomitado a sus habitantes.

[[leviticus-18-26]]
^26^ Vosotros, pues, guardad mis preceptos y mis normas, y nos cometáis ninguna de estas abominaciones, ni los de vuestro pueblo ni los forasteros que residen entre vosotros.

[[leviticus-18-27]]
^27^ Porque todas estas abominaciones han cometido los hombres que habitaron el país antes que vosotros, y por eso el país se ha llenado de impurezas.

[[leviticus-18-28]]
^28^ Y no os vomitará la tierra por vuestras impurezas, del mismo modo que vomitó a las naciones anteriores a vosotros;

[[leviticus-18-29]]
^29^ sino que todos los que cometan una de estas abominaciones, ésos serán exterminados de en medio de su pueblo.

[[leviticus-18-30]]
^30^ Guardad, pues, mis observancias; no practicaréis ninguna de las costumbres abominables que se practicaban antes de vosotros, ni os hagáis impuros con ellas. Yo, Yahveh, vuestro Dios.
[[leviticus-19]]
== Capítulo 19

[[leviticus-19-1]]
^1^ Habló Yahveh a Moisés, diciendo:

[[leviticus-19-2]]
^2^ Habla a toda la comunidad de los israelitas y diles: Sed santos, porque yo, Yahveh, vuestro Dios, soy santo.

[[leviticus-19-3]]
^3^ Respete cada uno de vosotros a su madre y a su padre. Guardad mis sábados. Yo, Yahveh, vuestro Dios.

[[leviticus-19-4]]
^4^ No os volváis hacia los ídolos, ni os hagáis dioses de fundición. Yo, Yahveh, vuestro Dios.

[[leviticus-19-5]]
^5^ Cuando sacrifiquéis a Yahveh un sacrificio de comunión, sacrificadlo de modo que le seáis gratos.

[[leviticus-19-6]]
^6^ La víctima se ha de comer el mismo día en que la inmoléis, o al día siguiente; y lo que sobre hasta el día tercero, será quemado.

[[leviticus-19-7]]
^7^ Si se come algo al tercer día, será un manjar corrompido; el sacrificio no será grato.

[[leviticus-19-8]]
^8^ El que lo coma, cargará con su iniquidad, porque ha profanado la Santidad de Yahveh. Esa persona será externinada de entre su parentela.

[[leviticus-19-9]]
^9^ Cuando cosechéis la mies de vuestra tierra, no siegues hasta el borde de tu campo, ni espigues los restos de tu mies.

[[leviticus-19-10]]
^10^ Tampoco harás rebusco de tu viña, ni recogerás de tu huerto los frutos caídos; los dejarás para el pobre y el forastero. Yo, Yahveh, vuestro Dios.

[[leviticus-19-11]]
^11^ No hurtaréis; no mentiréis ni os defraudaréis unos a otros.

[[leviticus-19-12]]
^12^ No juraréis en falso por mi nombre: profanarías el nombre de tu Dios. Yo, Yahveh.

[[leviticus-19-13]]
^13^ No oprimirás a tu prójimo, ni lo despojarás. No retendrás el salario del jornalero hasta el día siguiente.

[[leviticus-19-14]]
^14^ No maldecirás a un mudo, ni pondrás tropiezo ante un ciego, sino que temerás a tu Dios. Yo, Yahveh.

[[leviticus-19-15]]
^15^ Siendo juez no hagas injusticia, ni por favor del pobre, ni por respeto al grande: con justicia juzgarás a tu prójimo.

[[leviticus-19-16]]
^16^ No andes difamando entre los tuyos; no demandes contra la vida de tu prójimo. Yo, Yahveh.

[[leviticus-19-17]]
^17^ No odies en tu corazón a tu hermano, pero corrige a tu prójimo, para que no te cargues con pecado por su causa.

[[leviticus-19-18]]
^18^ No te vengarás ni guardarás rencor contre los hijos de tu pueblo. Amarás a tu prójimo como a ti mismo. Yo, Yahveh.

[[leviticus-19-19]]
^19^ Guardad mis preceptos. No aparearás ganado tuyo de diversa especie. No siembres tu campo con dos clases distintas de grano. No uses ropa de dos clases de tejido.

[[leviticus-19-20]]
^20^ Si un hombre se acuesta maritalmente con una mujer que es una sierva perteneciente a otro, sin que haya sido rescatada ni liberada, será él castigado, pero no con pena de muerte, pues ella no era libre.

[[leviticus-19-21]]
^21^ El ofrecerá un carnero, su sacrificio de reparación para Yahveh, a la entrade de la Tienda del Encuentro; será un carnero de reparación.

[[leviticus-19-22]]
^22^ Con el carnero de reparación, el sacerdote hará expiación por él ante Yahveh por el pecado que cometío, y se le perdonará su pecado.

[[leviticus-19-23]]
^23^ Cuando entréis en la tierra y plantéis toda clase de árboles frutales, consideraréis impuro su fruto, como incircunciso; por tres años os serán como incircuncisos y no se podrán comer.

[[leviticus-19-24]]
^24^ Al cuarto año todos su frutos serán consagrados en fiesta de alabanza en honor de Yahveh.

[[leviticus-19-25]]
^25^ Y en el quinto año podréis comer de su fruto y almacenar en vuestro provecho su producto. Yo, Yahveh, vuestro Dios.

[[leviticus-19-26]]
^26^ No comáis nada con sangre. No practiquéis encantamiento ni astrología.

[[leviticus-19-27]]
^27^ No rapéis en redondo vuestra cabellera, ni cortes los bordes de tu barba.

[[leviticus-19-28]]
^28^ No haréis incisiones en vuestra carne por los muertos; ni os haréis tatuaje. Yo, Yahveh.

[[leviticus-19-29]]
^29^ No profanarás a tu hija, prostituyéndola; no sea que la tierra se prostituya y se llene de incestos.

[[leviticus-19-30]]
^30^ Guardad mis sábados y respetad mi santuario. Yo, Yahveh.

[[leviticus-19-31]]
^31^ No os dirijáis a los nigromantes, ni consultéis a los adivinos haciéndoos impuros por su causa. Yo, Yahveh, vuestro Dios.

[[leviticus-19-32]]
^32^ Ponte en pie ante las canas y honra el rostro del anciano; teme a tu Dios. Yo, Yahveh.

[[leviticus-19-33]]
^33^ Cuando un forastero resida junto a ti, en vuestra tierra, no le molestéis.

[[leviticus-19-34]]
^34^ Al forastero que reside junto a vosotros, le miraréis como a uno de vuestro pueblo y lo amarás como a ti mismo; pues forasteros fuisteis vosotros en la tierra de Egipto. Yo, Yahveh, vuestro Dios.

[[leviticus-19-35]]
^35^ No cometáis injustica en los juicios, ni en las medidas de longitud, de peso o de capacidad:

[[leviticus-19-36]]
^36^ tened balanza justa, peso justo, medida justa y sextario justo. Yo soy Yahveh vuestro Dios, que os saqué del país de Egipto.

[[leviticus-19-37]]
^37^ Guardad todos mis preceptos y todas mis normas, y ponedlos en práctica. Yo, Yahveh.
[[leviticus-20]]
== Capítulo 20

[[leviticus-20-1]]
^1^ Habló Yahveh a Moisés y dijo:

[[leviticus-20-2]]
^2^ Dirás a los israelitas: Si un hombre cualquiera de entre los israelitas o de los forasteros que residen en Israel entrega uno de sus hijos a Mólek, morirá sin remedio; el pueblo de la tierra lo lapidara.

[[leviticus-20-3]]
^3^ Yo mismo volveré mi rostro contra ese hombre y los exterminaré de en medio de su pueblo, por haber entregado un hijo suyo a Mólek, haciendo impuro mi santuario y profanando mi nombre santo.

[[leviticus-20-4]]
^4^ Si el pueblo de la tierra cierra los ojos ante ese hombre que entregó uno de sus hijos a Mólek, y no le da muerte,

[[leviticus-20-5]]
^5^ yo mismo volveré mi rostro contra ese hombre y contra su familia, y lo exterminaré de entre su pueblo, a él y a todos los que como él se prostituyan tras Mólek.

[[leviticus-20-6]]
^6^ Si alguien consulta a los nigromantes, y a los adivinos, prostituyéndose en pos de ellos, yo volveré mi rostro contra él y lo exterminaré de en medio de su pueblo.

[[leviticus-20-7]]
^7^ Santificaos y sed santos; porque yo soy Yahveh, vuestro Dios.

[[leviticus-20-8]]
^8^ Guardad mis preceptos y cumplidlos. Yo soy Yahveh, el que os santifico.

[[leviticus-20-9]]
^9^ Quien maldiga a su padre o a su madre, será muerto sin remedio, pues ha maldecido a su padre o a su madre; su sangre caerá sobre él.

[[leviticus-20-10]]
^10^ Si un hombre comete adulterio con la mujer de su prójimo, será muerto tanto el adúltero como la adúltera.

[[leviticus-20-11]]
^11^ El que se acueste con la mujer de su padre, ha descubierto la desnudez de su padre; ambos morirán: caerá sobre ellos su sangre.

[[leviticus-20-12]]
^12^ Si un hombre se acuesta con su nuera, ambos morirán; han hecho una infamia: su sangre caerá sobre ellos.

[[leviticus-20-13]]
^13^ Si alguien se acuesta con varón, como se hace con mujer, ambos han cometido abominación: morirán sin remedio; su sangre caerá sobre ellos.

[[leviticus-20-14]]
^14^ Si uno toma por esposas a una mujer y a su madre, es un incesto. Serán quemados tanto él como ellas para que no haya tal incesto en medio de vosotros.

[[leviticus-20-15]]
^15^ El que se una con bestia, morirá sin remedio. Mataréis también la bestia.

[[leviticus-20-16]]
^16^ Si una mujer se acerca a una bestia para unirse a ella, matarás a la mujer y a las bestia. Morirán; caerá sobre ellos su sangre.

[[leviticus-20-17]]
^17^ Si alguien toma por esposa a su hermana, hija de su padre o hija de su madre, viendo así la desnudez de ella y ella la desnudez de él, es una ignominia. Serán exterminados en presencia de los hijos de su pueblo. Ha descubierto la desnudez de su hermana: cargará con su iniquidad.

[[leviticus-20-18]]
^18^ El que se acueste con mujer durante el tiempo de la reglas descubriendo la desnudez de ella, ha puesto al desnudo la fuente de su flujo y ella también ha descubierto la fuente de su sangre. Ambos serán exterminados de entre su pueblo.

[[leviticus-20-19]]
^19^ No descubras la desnudez de la hermana de tu madre ni de la hermana de tu padre, porque desnudas su propia carne; por eso cargarán con su iniquidad.

[[leviticus-20-20]]
^20^ El que se acueste con la mujer de su tío paterno, descubre la desnudez de éste. Cargarán con su pecado; morirán sin hijos.

[[leviticus-20-21]]
^21^ Si uno toma por esposa a la mujer de su hermano, es cosa impura, pues descubre la desnudez de su hermano; quedarán sin hijos.

[[leviticus-20-22]]
^22^ Guardad, pues, todos mis preceptos y todas mis normas, y cumplidlos; así no os vomitará la tierra adonde os llevo para que habitéis en ella.

[[leviticus-20-23]]
^23^ No caminéis según las costumbres de las naciones que yo voy a expulsar ante vosotros; pues, porque han obrado así, yo estoy asqueado de ellas.

[[leviticus-20-24]]
^24^ Pero a vosotros os he dicho: «Poseeréis su suelo, el que yo os daré en herencia, tierra que mana leche y miel». Yo soy Yahveh, vuestro Dios, que os ha separado de estos pueblos.

[[leviticus-20-25]]
^25^ Habéis de hacer separación entre animales puros e impuros, y entre aves impuras y puras; para que no os hagáis abominables, ni con animales ni con aves, ni con lo que se arrastra por el suelo; porque os he separado todo eso como impuro.

[[leviticus-20-26]]
^26^ Sed, pues, santos para mí, porque yo, Yahveh, soy santo, y os he separado de entre los pueblos, para que seáis míos.

[[leviticus-20-27]]
^27^ El hombre o la mujer en que haya espíritu de nigromante o adivino, morirá sin remedio: los lapidarán. Caerá su sangre sobre ellos.
[[leviticus-21]]
== Capítulo 21

[[leviticus-21-1]]
^1^ Dijo Yahveh a Moisés: Habla a los sacerdotes, hijos de Aarón, y diles: Nadie se haga impuro por el cadáver de alguno de los suyos,

[[leviticus-21-2]]
^2^ como no sea pariente cercano suyo: la madre, el padre, el hijo, la hija, el hermano,

[[leviticus-21-3]]
^3^ una hermana virgen, que viva con él y no haya sido desposada aún; por ella puede hacerse impuro.

[[leviticus-21-4]]
^4^ Pues no debe hacerse impuro, siendo señor entre los suyos; se profanaría.

[[leviticus-21-5]]
^5^ Los sacerdotes no se raparán la cabeza, ni se cortarán los bordes de la barba, ni se harán incisiones en su cuerpo.

[[leviticus-21-6]]
^6^ Santos han de ser para su Dios y no profanarán el nombre de su Dios, pues son ellos los que presentan los manjares que se han de abrasar para Yahveh, el alimento de su Dios; han de ser santos.

[[leviticus-21-7]]
^7^ No tomarán por esposa a una mujer prostituta ni profanada, ni tampoco una mujer repudiada por su marido; pues el sacerdote está consagrado a su Dios.

[[leviticus-21-8]]
^8^ Le tendrás por santo, porque él es quien presenta el alimento de tu Dios; por tanto será santo para ti, pues santo soy yo, Yahveh, el que os santifico.

[[leviticus-21-9]]
^9^ Si la hija de un sacerdote prostituyéndose se profana, a su padre profana; será quemada.

[[leviticus-21-10]]
^10^ El sumo sacerdote, superior a sus hermanos, sobre cuya cabeza fue derramado el óleo de la unción y que recibió la investidura para vestir los ornamentos, no llevará desgreñada su cabellera ni rasgará sus vestidos,

[[leviticus-21-11]]
^11^ ni se acercará a ningún cadáver; ni siquiera por su padre o por su madre puede hacerse impuro.

[[leviticus-21-12]]
^12^ No saldrá del santuario para no profanar el santuario de su Dios; pues lleva sobre sí la consagración del óleo de la unción de su Dios. Yo, Yahveh.

[[leviticus-21-13]]
^13^ Tomará una virgen por esposa.

[[leviticus-21-14]]
^14^ No se casará con viuda ni repudiada ni profanada por prostitución, sino que tomará por esposa una virgen de entre su parentela.

[[leviticus-21-15]]
^15^ No profanará su descendencia entre su pueblo, pues soy, yo, Yahveh, el que lo santifico.

[[leviticus-21-16]]
^16^ Yahveh habló a Moisés y dijo:

[[leviticus-21-17]]
^17^ Habla a Aarón y dile: Ninguno de tus descendientes en cualquiera de sus generaciones, si tiene un defecto corporal, podrá acercarse a ofrecer el alimento de su Dios;

[[leviticus-21-18]]
^18^ pues ningún hombre que tenga defecto corporal ha de acercarse: ni ciego ni cojo ni deforme ni monstruoso,

[[leviticus-21-19]]
^19^ ni el que tenga roto el pie o la mano;

[[leviticus-21-20]]
^20^ ni jorobado ni raquítico ni enfermo de los ojos, ni el que padezca sarna o tiña, ni el eunuco.

[[leviticus-21-21]]
^21^ Ningún descendiente de Aarón que tenga defecto corporal puede acercarse a ofrecer los manjares que se abrasan en honor de Yahveh. Tiene defecto; no se acercará a ofrecer los manjares que se abrasan en honor de Yahveh. Tiene defecto; no se acercará a ofrecer el alimento de su Dios.

[[leviticus-21-22]]
^22^ Sin embargo, podrá comer el alimento de su Dios, las cosas sacratísimas, y las sagradas;

[[leviticus-21-23]]
^23^ mas no entrará hasta el velo ni se acercará al altar, porque tiene defecto, para no profanar mi santuario, pues yo soy Yahveh, el que los santifico.

[[leviticus-21-24]]
^24^ Moisés dijo esto a Aarón y a sus hijos y a todos los israelitas.
[[leviticus-22]]
== Capítulo 22

[[leviticus-22-1]]
^1^ Habló Yahveh a Moisés y dijo:

[[leviticus-22-2]]
^2^ Di a Aarón y a sus hijos que se abstengan de algunas ofrendas sagradas que los israelitas me consagran, para no profanar mi santo nombre. Yo, Yahveh.

[[leviticus-22-3]]
^3^ Diles: Cualquier descendiente vuestro, en todas las generaciones, que, estando impuro, se acerque a las cosas sagradas que los israelitas consagran a Yahveh, ése será exterminado de mi presencia. Yo, Yahveh.

[[leviticus-22-4]]
^4^ Ningún descendiente de Aarón, que sea leproso o padezca flujo comerá de las cosas sagradas hasta que se purifique. El que toque lo que es impuro por un cadáver, o el que haya tenido un derrame seminal,

[[leviticus-22-5]]
^5^ o el que haya tocado un bicho que le ha hecho impuro o a un hombre que le ha hecho impuro con cualquier clase de impureza;

[[leviticus-22-6]]
^6^ quien toque estas cosas, quedará impuro hasta la tarde, y no comerá de las cosas sagradas, sino que lavará su cuerpo con agua;

[[leviticus-22-7]]
^7^ puesto el sol, quedará limpio y podrá luego comer de las cosas sagradas, pues son su alimento.

[[leviticus-22-8]]
^8^ No comerá animal muerto o destrozado que le haga impuro. Yo, Yahveh.

[[leviticus-22-9]]
^9^ Que guarden mis observancias, no sea que, cargados así de pecado, al profanarlas mueran por ello. Yo, Yahveh, el que los santifico.

[[leviticus-22-10]]
^10^ Ningún laico comerá de las cosas sagradas; ningún huésped del sacerdote ni jornalero suyo comerá de las cosas sagradas.

[[leviticus-22-11]]
^11^ Pero si un sacerdote con su dinero compra una persona, ésta podrá comer de las cosas sagradas; y también el siervo nacido en la casa: ambos pueden comer del pan del sacerdote.

[[leviticus-22-12]]
^12^ La hija de un sacerdote, casada con un laico, no podrá comer de la ofrenda reservada de las cosas sagradas.

[[leviticus-22-13]]
^13^ Pero si la hija de un sacerdote queda viuda o es repudiada, y sin tener prole vuelve a la casa de su padre, podrá comer del pan de su padre, como en su juventud. Pero ningún laico comerá de él.

[[leviticus-22-14]]
^14^ Quien, por inadvertencia, coma de cosa sagrada, la restituirá al sacerdote, añadiendo un quinto de más.

[[leviticus-22-15]]
^15^ No profanen, pues, las cosas sagradas de los israelitas, reservadas para Yahveh,

[[leviticus-22-16]]
^16^ porque al comerlas cargarían con una iniquidad que debe ser reparada. Yo soy Yahveh, el que los santifico.

[[leviticus-22-17]]
^17^ Yahveh habló a Moisés, diciendo:

[[leviticus-22-18]]
^18^ Habla a Aarón y a sus hijos, y a todos los israelitas y diles: Si alguno de la casa de Israel, o de los forasteros residentes en Israel, en cumplimiento de un voto, o como ofrenda voluntaria, presenta una ofrenda que como holocausto ofrece a Yahveh

[[leviticus-22-19]]
^19^ para que os alcance favor, la víctima habrá de ser macho, sin defecto, buey, oveja o cabra.

[[leviticus-22-20]]
^20^ No ofrezcáis nada defectuoso, pues no os sería aceptado.

[[leviticus-22-21]]
^21^ Si alguno ofrece a Yahveh ganado mayor o menor como sacrificio de comunión, sea en cumplimiento de un voto, o como ofrenda voluntaria, ha de ser una res sin defecto para alcanzar favor; no debe tener defecto alguno.

[[leviticus-22-22]]
^22^ No presentaréis ante Yahveh animal ciego, quebrado, mutilado, ulcerado, sarnoso o ruin; de ellos nada pondréis en el altar como manjar que se abrasa para Yahveh.

[[leviticus-22-23]]
^23^ Si es buey u oveja desproporcionado o enano, podréis presentarlo como ofrenda voluntaria, pero no será aceptado en cumplimiento de voto.

[[leviticus-22-24]]
^24^ No ofreceréis a Yahveh animal que tenga los testículos aplastados, majados, arrancados o cortados. No hagáis est en vuestra tierra.

[[leviticus-22-25]]
^25^ Y de esto nada recibiréis de la mano del extranjero como alimento de vuestro Dios, porque su deformidad es un defecto; no os serán aceptados.

[[leviticus-22-26]]
^26^ Habló Yahveh a Moisés, diciendo:

[[leviticus-22-27]]
^27^ Cuando nazca un ternero, o un cordero, o cabrito, quedará siete días con su madre; y desde el día octavo en adelante será grato como ofrenda de manjar abrasado para Yahveh.

[[leviticus-22-28]]
^28^ No inmoléis en el mismo día vaca u oveja juntamente con su cría.

[[leviticus-22-29]]
^29^ Al sacrificar a Yahveh un sacrificio de alabanza, lo haréis de tal modo que os sea aceptado.

[[leviticus-22-30]]
^30^ Será comido en el mismo día, sin dejar nada de él hasta la mañana siguiente. Yo, Yahveh.

[[leviticus-22-31]]
^31^ Guardad mis mandamientos y cumplidlos. Yo, Yahveh.

[[leviticus-22-32]]
^32^ No profanéis mi santo nombre, para que yo sea santificado en medio de los israelitas. Yo soy Yahveh, el que os santifica,

[[leviticus-22-33]]
^33^ el que os ha sacado de la tierra de Egipto para ser vuestro Dios. Yo, Yahveh.
[[leviticus-23]]
== Capítulo 23

[[leviticus-23-1]]
^1^ Habló Yahveh a Moisés, diciendo:

[[leviticus-23-2]]
^2^ Habla a los israelitas y diles: Solemnidades de Yahveh que convocaréis como asambleas santas. Estas son mis solemnidades:

[[leviticus-23-3]]
^3^ Seis días se trabajará, pero el séptimo día será de descanso completo, reunión sagrada en que no haréis trabajo alguno. Será descanso de Yahveh dondequiera que habitéis.

[[leviticus-23-4]]
^4^ Estas son las solemnidades de Yahveh, las reuniones sagradas que convocaréis en las fechas señaladas.

[[leviticus-23-5]]
^5^ El mes primero, el día catorce del mes, entre dos luces, será la Pascua de Yahveh.

[[leviticus-23-6]]
^6^ El quince de este mes se celebrará la fiesta de los Azimos en honor de Yahveh. Durante siete días comeréis panes ázimos.

[[leviticus-23-7]]
^7^ El día primero tendréis reunión sagrada; no haréis ningún trabajo servil.

[[leviticus-23-8]]
^8^ Ofreceréis durante siete días manjares abrasados a Yahveh. El séptimo día celebraréis reunión sagrada; no haréis ningún trabajo servil.

[[leviticus-23-9]]
^9^ Habló Yahveh a Moisés, diciendo:

[[leviticus-23-10]]
^10^ Habla a los israelitas y diles: Cuando, después de entrar en la tierra que yo os doy, seguéis allí su mies, llevaréis una gavilla, como primicias de vuestra cosecha, al sacerdote,

[[leviticus-23-11]]
^11^ que mecerá la gavilla delante de Yahveh, para alcanzaros su favor. El día siguiente al sábado la mecerá el sacerdote.

[[leviticus-23-12]]
^12^ Ese mismo día en que mecieres la gavilla, sacrificaréis un cordero de un año, sin defecto, como holocausto a Yahveh,

[[leviticus-23-13]]
^13^ junto con su oblación de dos décimas de flor de harina amasada con aceite, como manjar abrasado de calmante aroma para Yahveh. Su libación de vino será un cuarto de sextario.

[[leviticus-23-14]]
^14^ No comeréis pan ni grano tostado ni grano tierno hasta ese mismo día, hastar traer la ofrenda de vuestro Dios. Decreto perpetuo será éste de generación en generación dondequiera que habitéis.

[[leviticus-23-15]]
^15^ Contaréis siete semanas enteras a partir del día siguiente al sábado, desde el día en que habréis llevado la gavilla de la ofrenda mecida;

[[leviticus-23-16]]
^16^ hasta el día siguiente al séptimo sábado, contaréis cincuenta días y entonces ofreceréis a Yahveh una oblación nueva.

[[leviticus-23-17]]
^17^ Llevaréis de vuestras casas como ofrenca mecida dos panes, hechos con dos décimas de flor de harina y cocidos con levadura, como primicias para Yahveh.

[[leviticus-23-18]]
^18^ Juntamente con el pan ofreceréis a Yahveh siete corderos de un año, sin defecto, un novillo y dos carneros: serán el holocausto para Yahveh además de su ofrenda y sus libaciones, como manjar abrasado de calmante aroma para Yahveh.

[[leviticus-23-19]]
^19^ Ofreceréis también un macho cabrío como sacrificio por el pecado, y dos corderos de un año como sacrificio de comunión.

[[leviticus-23-20]]
^20^ El sacerdote los mecerá como ofrenda ante Yahveh, juntamente con el pan de las primicias y con los dos corderos; serán consagrados a Yahveh y pertenecerán al sacerdote.

[[leviticus-23-21]]
^21^ Ese mismo día convocaréis una reunión sagrada; la celebraréis y no haréis ningún trabajo servil. Decreto perpetuo será éste de generación en generacíon dondequiera que habitéis.

[[leviticus-23-22]]
^22^ Cuando cosechéis la mies de vuestra tierra, no siegues hasta el borde de tu campo, ni espigues los restos de tu mies; los dejarás para el pobre y para el forastero. Yo, Yahveh, vuestro Dios.

[[leviticus-23-23]]
^23^ Habló Yahveh a Moisés, diciendo:

[[leviticus-23-24]]
^24^ Habla a los israelitas y diles: En el mes séptimo, el primer día del mes será para vosotros de gran descanso, una fiesta conmemorativa con clamor de trompetas, una reunión sagrada.

[[leviticus-23-25]]
^25^ No haréis ningún trabajo servil, y ofreceréis manjares abrasados a Yahveh.

[[leviticus-23-26]]
^26^ Habló Yahveh a Moisés, diciendo:

[[leviticus-23-27]]
^27^ Además el día décimo de este séptimo mes será el día de la Expiación, en el cual tendréis reunión sagrada; ayunaréis y ofreceréis manjares abrasados a Yahveh.

[[leviticus-23-28]]
^28^ No haréis en ese mismo día ningún trabajo, pues es el día de Expiación, en el que se ha de hacer la expiación por vosotros delante de Yahveh, vuestro Dios.

[[leviticus-23-29]]
^29^ El que no ayune ese día será exterminado de entre su pueblo.

[[leviticus-23-30]]
^30^ Al que haga en tal día un trabajo cualquiera, yo lo haré perecer de en medio de su pueblo.

[[leviticus-23-31]]
^31^ No haréis, pues, trabajo alguno. Es decreto perpetuo, de generación en generación, dondequiera que habitéis.

[[leviticus-23-32]]
^32^ Será para vosotros día de descanso completo y ayunaréis; el día nueve del mes, por la tarde, de tarde a tarde, guardaréis descanso.

[[leviticus-23-33]]
^33^ Habló Yahveh a Moisés, diciendo:

[[leviticus-23-34]]
^34^ Habla a los israelitas y diles: El día quince de ese séptimo mes celebraréis durante siete días la fiesta de las Tiendas en honor a Yahveh.

[[leviticus-23-35]]
^35^ El día primero habrá reunión sagrada y no haréis trabajo servil alguno.

[[leviticus-23-36]]
^36^ Durante siete días ofreceréis manjares abrasados a Yahveh. El día octavo tendréis reunión sagrada y ofreceréis manjares abrasados a Yahveh. Habrá asamblea solemne. No haréis trabajo servil alguno.

[[leviticus-23-37]]
^37^ Estas son las solemnidades de Yahveh en las que habéis de convocar reunión sagrada para ofrecer manjares abrasados a Yahveh, holocaustos y oblaciones, víctimas y libaciones, cada cosa en su día,

[[leviticus-23-38]]
^38^ sin contar los sábados de Yahveh, sin contar vuestros dones, sin contar todos vuestros votos, sin contar todas vuestras oblaciones voluntarias, las que ofrezcáis a Yahveh.

[[leviticus-23-39]]
^39^ El día quince del séptimo mes, después de haber cosechado el producto de la tierra, celebraréis la fiesta en honor de Yahveh durante siete días. El primer día será de descanso completo e igualmente el octavo.

[[leviticus-23-40]]
^40^ El primer día tomaréis frutos de los mejores árboles, ramos de palmeras, ramas de árboles frondosos y sauces de río; y os alegraréis en la presencia de Yahveh, vuestro Dios, por espacio de siete días.

[[leviticus-23-41]]
^41^ Celebraréis fiesta en honor de Yahveh durante siete días cada año. Será decreto perpetuo de generación en generación. En el séptimo mes la celebraréis.

[[leviticus-23-42]]
^42^ Durante siete días habitaréis en cabañas. Todos los naturales de Israel morarán en cabañas,

[[leviticus-23-43]]
^43^ para que sepan vuestros descendientes que yo hice habitar en cabañas a los israelitas cuando los saqué de la tierra de Egitpo. Yo, Yahveh, vuestro Dios.

[[leviticus-23-44]]
^44^ Moisés promulgó las solemnidades de Yahveh a los israelitas.
[[leviticus-24]]
== Capítulo 24

[[leviticus-24-1]]
^1^ Yahveh habló a Moisés, diciendo:

[[leviticus-24-2]]
^2^ Manda a los israelitas que te traigan para el alumbrado aceite puro de oliva molida, para alimentar continuamente la llama.

[[leviticus-24-3]]
^3^ Aarón lo preparará fuera del velo del Testimonio, en la Tienda del Encuentro para que arda de continuo ante Yahveh desde la tarde hasta la mañana. Es decreto perpetuo para vuestros descendientes.

[[leviticus-24-4]]
^4^ El colocará las lámparas sobre el candelabro puro que permanece ante Yahveh.

[[leviticus-24-5]]
^5^ Tomarás flor de harina, y cocerás con ella doce tortas, dos décimas para cada una.

[[leviticus-24-6]]
^6^ Las colocarás en dos filas, seis en cada fila, sobre la mesa pura en la presencia de Yahveh.

[[leviticus-24-7]]
^7^ Pondrás sobre cada fila incienso puro, que hará del pan un memorial, manjar abrasado para Yahveh.

[[leviticus-24-8]]
^8^ Se colocará en orden cada sábado en presencia continua ante Yahveh de parte de los israelitas, como alianza perpetua.

[[leviticus-24-9]]
^9^ Será de Aarón y de sus hijos, y lo comerán en lugar sagrado; porque lo considerarás como cosa sacratísima, de los manjares que se abrasan para Yahveh. Decreto perpetuo.

[[leviticus-24-10]]
^10^ Había salido con los israelitas el hijo de una mujer israelita y de padre egipcio. Cuando el hijo de la israelita y un hombre de Israel riñeron en el campo,

[[leviticus-24-11]]
^11^ el hijo de la israelita balsfemó y maldijo el Nombre, por lo que le llevaron ante Moisés. Su madre se llamaba Selomit, hija de Dibrí, de la tribu de Dan.

[[leviticus-24-12]]
^12^ Lo retuvieron en custodia hasta decidir el caso por sentencia de Yahveh.

[[leviticus-24-13]]
^13^ Y entonces Yahveh habló a Moisés y dijo:

[[leviticus-24-14]]
^14^ Saca al blasfemo fuera del campamento; todos los que lo oyeron pongan las manos sobre su cabeza, y que lo lapide toda la comunidad.

[[leviticus-24-15]]
^15^ Y hablarás así a los israelitas: Cualquier hombre que maldiga a su Dios, cargará con su pecado.

[[leviticus-24-16]]
^16^ Quien blasfeme el Nombre de Yahveh, será muerto; toda la comunidad lo lapidará. Sea forastero o nativo, si blasfema el Nombre, morirá.

[[leviticus-24-17]]
^17^ El que hiera mortalmente a cualquier otro hombre, morirá.

[[leviticus-24-18]]
^18^ El que hiera de muerte a un animal indemnizará por él: vida por vida.

[[leviticus-24-19]]
^19^ Si alguno causa una lesión a su prójimo, como él hizo así se le hará:

[[leviticus-24-20]]
^20^ fractura por fractura, ojo por ojo, diente por diente; se le hará la misma lesión que él haya causado a otro.

[[leviticus-24-21]]
^21^ El que mate un animal, indemnizará por él; mas el que mate a un hombre, morirá.

[[leviticus-24-22]]
^22^ Del mismo modo juzgarás al forastero y al nativo; porque yo soy Yahveh vuestro Dios.

[[leviticus-24-23]]
^23^ Habló entonces Moisés a los israelitas. Sacaron al blasfemo fuera del campamento y lo lapidaron. Los israelitas hicieron como Yahveh había mandado a Moisés.
[[leviticus-25]]
== Capítulo 25

[[leviticus-25-1]]
^1^ Habló Yahveh a Moisés en el monte Sinaí diciendo:

[[leviticus-25-2]]
^2^ Habla a los israelitas y diles: Cuando hayáis entrado en la tierra que yo voy a daros, la tierra tendrá también su descanso en honor de Yahveh.

[[leviticus-25-3]]
^3^ Seis años sembrarás tu campo, seis años podarás tu viña y cosecharás sus productos;

[[leviticus-25-4]]
^4^ pero el séptimo año será de completo descanso para la tierra, un sábado en honor de Yahveh: no sembrarás tu campo, ni podarás tu viña.

[[leviticus-25-5]]
^5^ No segarás los rebrotes de la última siega, ni vendimiarás los racimos de tu viña sin podar. Será año de descanso completo para la tierra.

[[leviticus-25-6]]
^6^ Aun en descanso, la tierra os alimentará a ti, a tu siervo, a tu sierva, a tu jornalero, a tu huésped. que residen junto a ti.

[[leviticus-25-7]]
^7^ También a tus ganados y a los animales de tu tierra servirán de alimento todos sus productos.

[[leviticus-25-8]]
^8^ Contarás siete semanas de años, siete veces siete años; de modo que el tiempo de las siete semanas de años vendrá a sumar cuarenta y nueve años.

[[leviticus-25-9]]
^9^ Entonces en el mes séptimo, el diez del mes, harás resonar clamor de trompetas; en el día de la Expiación haréis resonar el cuerno por toda vuestra tierra.

[[leviticus-25-10]]
^10^ Declararéis santo el año cincuenta, y proclamaréis en la tierra liberación para todos sus habitantes. Será para vosotros un jubileo; cada uno recobrará su propiedad, y cada cual regresará a su familia.

[[leviticus-25-11]]
^11^ Este año cincuenta será para vosotros un jubileo: no sembraréis, ni segaréis los rebrotes, ni vendimiaréis la viña que ha quedado sin podar,

[[leviticus-25-12]]
^12^ porque es el jubileo, que será sagrado para vosotros. Comeréis lo que el campo dé de sí.

[[leviticus-25-13]]
^13^ En este año jubilar recobraréis cada uno vuestra propiedad.

[[leviticus-25-14]]
^14^ Si vendéis algo a vuestro prójimo o le compráis algo, ved que nadie dañe a su hermano.

[[leviticus-25-15]]
^15^ Comprarás a tu prójimo atendiendo el número de años que siguen al jubileo; u según el número de los años de cosecha, él te fijará el precio de venta:

[[leviticus-25-16]]
^16^ a mayor número de años, mayor precio cobrarás; cuantos menos años queden, tanto menor será su precio, porque lo que él te vende es el número de cosechas.

[[leviticus-25-17]]
^17^ Ninguno de vosotros dañe a su prójimo, antes bien teme a tu Dios; pues yo soy Yahveh vuestro Dios.

[[leviticus-25-18]]
^18^ Cumplid mis preceptos; guardad mis normas y cumplidlas; así viviréis seguros en esta tierra.

[[leviticus-25-19]]
^19^ Y la tierra dará su fruto, y comeréis hasta saciaros; y habitaréis seguros en ella.

[[leviticus-25-20]]
^20^ Si preguntáis: «¿Qué comeremos el año séptimo, puesto que no podremos sembrar ni cosechar nuestros productos?» -

[[leviticus-25-21]]
^21^ Yo os mandaré mi bendición en el año sexto, de modo que producirá para tres años;

[[leviticus-25-22]]
^22^ sembraréis el año octavo y seguiréis comiendo de la cosecha anterior hasta el año noveno. Hasta que venga su cosecha, seguiréis comiendo de la anterior.

[[leviticus-25-23]]
^23^ La tierra no puede venderse para siempre, porque la tierra es mía, ya que vosotros sois para mí como forasteros y huéspedes.

[[leviticus-25-24]]
^24^ En todo terreno de vuestra propiedad concederéis derecho a rescatar la tierra.

[[leviticus-25-25]]
^25^ Si se empobrece tu hermano y vende algo de su propiedad, su goel más cercano vendrá y rescatará lo vendido por su hermano.

[[leviticus-25-26]]
^26^ Si alguno no tiene goel, adquiera por sí mismo recursos suficientes para su rescate;

[[leviticus-25-27]]
^27^ calcule los años pasados desde la venta y devuelva al comprador la cantidad del tiempo que falta; así volverá a su propiedad.

[[leviticus-25-28]]
^28^ Pero si no halla lo suficiente para recuperarla, lo vendido quedará en poder del comprador hasta el año jubilar, y en el jubileo quedará libre; y el vendedor volverá a su posesión.

[[leviticus-25-29]]
^29^ Si uno vendiere una vivienda en ciudad amurallada, su derecho a rescatarla durará hasta que se cumpla el año de su venta; un año entero durará su derecho de rescate.

[[leviticus-25-30]]
^30^ En caso de no ser rescatada para él dentro de un año entero, la casa situada en ciudad amurallada quedará a perpetuidad para el comprador y sus descendientes y no quedará libre en el jubileo.

[[leviticus-25-31]]
^31^ Mas las casas de las aldeas sin murallas que las rodeen serán tratadas como los campos del país: hay derecho de rescate y en el año jubilar quedan libres.

[[leviticus-25-32]]
^32^ En cuanto a las ciudades de los levitas, los levitas tendrán siempre derecho de rescate sobre las casas de las ciudades de su propiedad.

[[leviticus-25-33]]
^33^ En el caso de que se haya de rescatar de mano de un levita, lo vendido - una casa que es propiedad suya en la ciudad - quedará libre en el jubileo; porque las casas de las ciudades de los levitas son su propiedad en medio de los israelitas.

[[leviticus-25-34]]
^34^ No pueden venderse los campos que rodean sus ciudades, pues son su propiedad para siempre.

[[leviticus-25-35]]
^35^ Si tu hermano se empobrece y vacila su mano en asuntos contigo, lo mantendrás como forastero o huésped, para que pueda vivir junto a ti.

[[leviticus-25-36]]
^36^ No tomarás de él interés ni usura, antes bien teme a tu Dios y deja vivir a tu hermano junto a ti.

[[leviticus-25-37]]
^37^ No le darás por interés tu dinero ni le darás tus víveres a usura.

[[leviticus-25-38]]
^38^ Yo soy Yahveh, vuestro Dios, que os saqué de la tierra de Egipto, para daros la tierra de Canaán y ser vuestro Dios.

[[leviticus-25-39]]
^39^ Si se empobrece tu hermano en asuntos contigo y tú lo compras, no le impondrás trabajos de esclavo;

[[leviticus-25-40]]
^40^ estará contigo como jornalero o como huésped, y trabajará junto a ti hasta el año del jubileo.

[[leviticus-25-41]]
^41^ Entonces saldrá de tu casa, él y sus hijos con él, volverá a su familia y a la propiedad de sus padres.

[[leviticus-25-42]]
^42^ Porque ellos son siervos míos, a quienes yo saqué de la tierra de Egipto; no han de ser vendidos como se vende un esclavo.

[[leviticus-25-43]]
^43^ No serás tirano con él, sino que temerás a tu Dios.

[[leviticus-25-44]]
^44^ Los siervos y las siervas que tengas, serán de las naciones que os rodean; de ellos podréis adquirir siervos y siervas.

[[leviticus-25-45]]
^45^ También podréis comprarlos entre los hijos de los huéspedes que residen en medio de vosotros, y de sus familias que viven entre vosotros, es decir, de los nacidos en vuestra tierra. Esos pueden ser vuestra propiedad,

[[leviticus-25-46]]
^46^ y los dejaréis en herencia a vuestros hijos después de vosotros como propiedad perpetua. A éstos los podréis tener como siervos; pero si se trata de vuestros hermanos, los israelitas, tú, como entre hermanos, no le mandarás con tiranía.

[[leviticus-25-47]]
^47^ Si el forastero o huésped que mora contigo adquiere bienes, y, en cambio, tu hermano se empobrece en asuntos con él y se vende al forastero, al que mora contigo, o a algún descendiente de familia de forastero,

[[leviticus-25-48]]
^48^ después de haberse vendido le quedará el derecho al rescate: uno de sus hermanos podrá rescatarlo.

[[leviticus-25-49]]
^49^ Lo rescatará su tío paterno, o el hijo de su tío, o algún otro pariente cercano suyo dentro de su familia, o, si alcanzan sus recursos, él mismo podrá rescatarse.

[[leviticus-25-50]]
^50^ Contará con su comprador los años desde el de la venta hasta el año jubilar; y el precio se calculará en proporción de los años, valorando sus días de trabajo como los de un jornalero.

[[leviticus-25-51]]
^51^ Si faltan todavía muchos años, en proporción a ellos devolverá, como precio de su rescate, una parte del precio de venta.

[[leviticus-25-52]]
^52^ Si faltan pocos años hasta el jubileo, se le calculará en proporción a ellos, y lo pagará como rescate,

[[leviticus-25-53]]
^53^ como quien trabaja a jornal año por año. No permitas que se le trate con tiranía ante tus ojos.

[[leviticus-25-54]]
^54^ Si nos es rescatado por otros, quedará libre el año del jubileo, él y sus hijos con él.

[[leviticus-25-55]]
^55^ Porque a mí es a quien sirven los israelitas; siervos míos son, a quienes yo he sacado del país de Egipto. Yo, Yahveh, vuestro Dios.
[[leviticus-26]]
== Capítulo 26

[[leviticus-26-1]]
^1^ No os hagáis ídolos, ni pongáis imágenes o estelas, ni coloquéis en vuestra tierra piedras grabadas para postraros ante ellas, porque yo soy Yahveh vuestro Dios.

[[leviticus-26-2]]
^2^ Guardaréis mis sábados, y respetaréis mi santuario. Yo, Yahveh.

[[leviticus-26-3]]
^3^ Si camináis según mis preceptos y guardáis mis mandamientos, poniéndolos en práctica,

[[leviticus-26-4]]
^4^ os enviaré las lluvias a su tiempo, para que la tierra dé sus frutos y el árbol del campo su fruto.

[[leviticus-26-5]]
^5^ El tiempo de trilla alcanzará hasta la vendimia, y la vendimia hasta la siembra; comeréis vuestro pan hasta saciaros y habitaréis seguros en vuestra tierra.

[[leviticus-26-6]]
^6^ Yo daré paz a la tierra y dormiréis sin que nadie os turbe; haré desaparecer del país las bestias feroces, y la espada no pasará por vuestra tierra.

[[leviticus-26-7]]
^7^ Perseguiréis a vuestros enemigos; que caerán ante vosotros a filo de espada.

[[leviticus-26-8]]
^8^ Cinco de vosotros perseguiréis a cien, y cien de vosotros perseguiréis a 10.000; vuestros enemigos ante vosotros caerán a filo de espada.

[[leviticus-26-9]]
^9^ Yo me volveré hacia vosotros. Yo os haré fecundos, os multiplicaré y mantendré mi alianza con vosotros.

[[leviticus-26-10]]
^10^ Comeréis de cosecha añeja y llegaréis a echar la añeja para dar cabida a la nueva.

[[leviticus-26-11]]
^11^ Estableceré mi morada en medio de vosotros y no os rechazaré.

[[leviticus-26-12]]
^12^ Me pasearé en medio de vosotros, y seré para vosotros Dios, y vosotros seréis para mí un pueblo.

[[leviticus-26-13]]
^13^ Yo soy Yahveh, vuestro Dios, que os saqué del país de Egipto, para que no fueseis sus esclavos; rompi las coyundas de vuestro yugo y os hice andar con la cabeza erguida.

[[leviticus-26-14]]
^14^ Pero si no me escucháis y no cumplís todos estos mandamientos;

[[leviticus-26-15]]
^15^ si despreciáis mis preceptos y rechazáis mis normas, no haciendo caso de todos mis mandamientos y rompiendo mi alianza,

[[leviticus-26-16]]
^16^ también yo haré lo mismo con vosotros. Traeré sobre vosotros el terror, la tisis y la fiebre, que os abrasen los ojos y os consuman el alma. Sembraréis en vano vuestra semilla, pues se la comerán vuestros enemigos.

[[leviticus-26-17]]
^17^ Me volveré contra vosotros y seréis derrotados ante vuestros enemigos; os tiranizarán los que os aborrecen y huiréis sin que nadie os persiga.

[[leviticus-26-18]]
^18^ Si ni aun con esto me obedecéis, volveré a castigaros siete veces más por vuestros pecados.

[[leviticus-26-19]]
^19^ Quebrantaré vuestra orgullosa fuerza y haré vuestro cielo como hierro y vuestra tierra como bronce.

[[leviticus-26-20]]
^20^ Vuestras fuerzas se consumirán en vano, pues vuestra tierra no dará sus productos ni el árbol del campo sus frutos.

[[leviticus-26-21]]
^21^ Y si seguís enfrentándoos conmigo y no queréis oírme, volveré a castigaros siete veces más a causa de vuestros pecados.

[[leviticus-26-22]]
^22^ Soltaré contra vosotros las fieras salvajes, que os privarán de vuestros hijos, exterminarán vuestro ganado y os reducirán a unos pocos, de modo que vuestros caminos queden desiertos.

[[leviticus-26-23]]
^23^ Si aun con esto no os corregís ante mí, sino que seguís enfrentándoos conmigo,

[[leviticus-26-24]]
^24^ también yo me enfrentaré con vosotros, y os azotaré yo mismo siete veces más por vuestros pecados.

[[leviticus-26-25]]
^25^ Traeré sobre vosotros la espada vengadora de la alianza. Os reuniréis entonces en vuestras ciudades, pero yo enviaré la peste en medio de vosotros y seréis entregados en manos del enemigo.

[[leviticus-26-26]]
^26^ Cuando yo os retire el bastón del pan diez mujeres cocerán todo vuestro pan en un solo horno, y os lo darán tan medido que comeréis y no os saciaréis.

[[leviticus-26-27]]
^27^ Si con esto no me obedecéis y seguís enfrentándoos conmigo,

[[leviticus-26-28]]
^28^ yo me enfrentaré a vosotros con ira, y os castigaré yo mismo siete veces más por vuestros pecados.

[[leviticus-26-29]]
^29^ Comeréis la carne de vuestros hijos y la carne de vuestras hijas comeréis.

[[leviticus-26-30]]
^30^ Destruiré vuestros altos, abatiré vuestros altares de incienso, amontonaré vuestros cadáveres sobre los cadáveres de vuestros ídolos, y yo mismo os aborreceré.

[[leviticus-26-31]]
^31^ Reduciré vuestras ciudades a ruina y devastaré vuestros santuarios, no aspiraré ya más vuestros calmantes aromas.

[[leviticus-26-32]]
^32^ Yo asolaré la tierra, y de ello quedarán atónitos vuestros mismos enemigos al venir a ocuparla.

[[leviticus-26-33]]
^33^ A vosotros os esparciré entre las naciones, y desanvainaré la espada en pos de vosotros. Vuestra tierra será un yermo y vuestras ciudades una ruina.

[[leviticus-26-34]]
^34^ Entonces pagará la tierra sus sábados, durante todos los días que esté desolada mientras vosotros estéis en el país de vuestros enemigos; entonces sí que descansará la tierra y pagará sus sábados.

[[leviticus-26-35]]
^35^ Durante todo el tiempo de la desolación descansará, por lo que no pudo descansar en vuestros sábados cuando habitabais en ella.

[[leviticus-26-36]]
^36^ A los que quedaren de vosotros, les infundiré pánico en sus corazones, en el país de sus enemigos; el ruido de una hoja caída los ahuyentará, huirán como quien huye de la espada, y caerán sin que nadie los persiga.

[[leviticus-26-37]]
^37^ Se atropellarán unos a otros, como delante de la espada, aunque nadie los persiga. No podréis teneros en pie en presencia de vuestros enemigos.

[[leviticus-26-38]]
^38^ Pereceréis entre las naciones, y os devorará el país de vuestros enemigos.

[[leviticus-26-39]]
^39^ Y quienes de vosotros sobrevivan, se pudrirán a causa de su iniquidad en los países de vuestros enemigos; por las iniquidades de sus padres unidas a las suyas, se pudrirán.

[[leviticus-26-40]]
^40^ Entonces confesarán su iniquidad y la iniquidad de sus padres, en la rebeldía con que se rebelaron contra mí; y aun más, porque se enfrentaron conmigo.

[[leviticus-26-41]]
^41^ También yo me enfrentaré con ellos y los llevaré al país de sus enemigos. Entonces se humillará su corazón incircunciso y aceptarán el castigo de su iniquidad.

[[leviticus-26-42]]
^42^ Y yo me acordaré de mi alianza con Jacob, y de mi alianza con Isaac; y recordaré mi alianza con Abraham; y recordaré la tierra.

[[leviticus-26-43]]
^43^ Pero la tierra será antes abandonada por ellos y pagará sus sábados, mientras quede desolada con su ausencia; pero ellos también pagarán el castigo de su iniquidad, por cuanto desecharon mis normas y su alma aborreció mis preceptos.

[[leviticus-26-44]]
^44^ A pesar de todo, cuando estén ellos en tierra enemiga, no los desecharé ni los aborreceré hasta su total exterminio, anulando mi alianza con ellos, porque yo soy Yahveh, su Dios;

[[leviticus-26-45]]
^45^ me acordaré, en su favor, de la alianza hecha con sus antepasados, a quienes saqué de la tierra de Egipto, ante los ojos de las naciones, para ser su Dios, yo Yahveh.

[[leviticus-26-46]]
^46^ Estos son los preceptos, normas y leyes que Yahveh estableció entre él y los israelitas en el monte Sinaí, por medio de Moisés.
[[leviticus-27]]
== Capítulo 27

[[leviticus-27-1]]
^1^ Habló Yahveh a Moisés, diciendo;

[[leviticus-27-2]]
^2^ Habla a los israelitas y diles: Si alguien quiere cumplir ante Yahveh un voto relativo al valor de tasación de una persona,

[[leviticus-27-3]]
^3^ si se trata de un varón de veinte a sesenta años, el valor se estimará en cincuenta siclos de plata, en siclos del santuario.

[[leviticus-27-4]]
^4^ Mas si se trata de una mujer, el valor será de treinta siclos.

[[leviticus-27-5]]
^5^ De los cinco a los veinte años el valor será: para varón, veinte siclos; para mujer, diez siclos.

[[leviticus-27-6]]
^6^ De un mes hasta la edad de cinco años, el valor será: para niño, cinco siclos de plata; para niña, tres siclos de plata.

[[leviticus-27-7]]
^7^ De sesenta años en adelante el valor será: para varón, quince siclos; para mujer, diez siclos.

[[leviticus-27-8]]
^8^ Si uno es tan pobre que no puede pagar esta valoración, presentará la persona al sacerdote, el cual estimará su valor; el sacerdote la valuará en proporción a los recursos del oferente.

[[leviticus-27-9]]
^9^ Si se trata de un animal que se puede ofrecer a Yahveh como ofrenda, todo lo que se entregue así a Yahveh será cosa sagrada.

[[leviticus-27-10]]
^10^ No se cambiará ni se sustituirá bueno por malo, ni malo por bueno; y si se sustituye un animal por otro, tanto el permutado como su sustituto serán cosa sagrada.

[[leviticus-27-11]]
^11^ Mas si se trata de un animal impuro, de los que no se pueden ofrecer como ofrenda a Yahveh, se presentará el animal al sacerdote,

[[leviticus-27-12]]
^12^ el cual lo tasará según sea bueno o malo; y se estará a su tasación.

[[leviticus-27-13]]
^13^ Si uno quiere rescatarlo, añadirá un quinto más a su valuación.

[[leviticus-27-14]]
^14^ Si alguno consagra su casa, como cosa sagrada, a Yahveh, el sacerdote la tasará, según sea buena o mala. Conforme a la tasación del sacerdote, así se fijará.

[[leviticus-27-15]]
^15^ Si el que consagró la casa desea rescatarla, añadirá la quinta parte al precio de su tasación, y será suya.

[[leviticus-27-16]]
^16^ Si uno consagra parte del campo de su propiedad a Yahveh, será estimado según su sembradura, a razón de cincuenta siclos de plata por cada carga de cebada de sembradura.

[[leviticus-27-17]]
^17^ Si él consagró su campo durante el año del jubileo se atenderá a esta tasación.

[[leviticus-27-18]]
^18^ Pero si consagra su campo después del jubileo, el sacerdote calculará su precio a razón de los años que quedan hasta el año del jubileo; y lo descontará de la tasación.

[[leviticus-27-19]]
^19^ Si el que consagró el campo desea rescartarlo, añadirá la quinta parte al precio de la tasación, y será suyo.

[[leviticus-27-20]]
^20^ Pero si nos rescata el campo, y éste se vende o otro, el campo no podrá ser rescatado en adelante.

[[leviticus-27-21]]
^21^ Ese campo, cuando quede libre en el jubileo, será consagrada a Yahveh como campo de anatema y será propiedad del sacerdote.

[[leviticus-27-22]]
^22^ Si alguno consagra a Yahveh un campo que compró y que no forma parte de su propiedad,

[[leviticus-27-23]]
^23^ el sacerdote calculará el importe de su valor hasta el año del jubileo; y él pagará ese mismo día la suma de la tasación como cosa sagrada de Yahveh.

[[leviticus-27-24]]
^24^ El año del jubileo volverá el campo al vendedor, al que pertenece como propiedad de la tierra.

[[leviticus-27-25]]
^25^ Toda tasación se hará en siclos del santuario; veinte óbolos equivalen a un siclo.

[[leviticus-27-26]]
^26^ Nadie, sin embargo, podrá consagrar los primogénitos de su ganado que ya, por ser tales, pertenecen a Yahveh. Sean del ganado mayor o del menor, pertenecen a Yahveh.

[[leviticus-27-27]]
^27^ Si se trata de un animal impuro, y lo quiere rescatar según la tasación, añadirá la quinta parte al precio; pero si no es rescatado, será vendido, conforme a la tasación.

[[leviticus-27-28]]
^28^ Nada de lo que a uno pertenece - hombre, animal o campo de su propiedad - que haya sido consagrado a Yahveh con anatema podrá venderse ni rescatarse. Todo anatema es cosa sacratísima para Yahveh.

[[leviticus-27-29]]
^29^ Ningún ser humano consagrado como anatema podrá ser rescatado; deberá morir.

[[leviticus-27-30]]
^30^ El diezmo entero de la tierra, tanto de las semillas de la tierra como de los frutos de los árboles, es de Yahveh; es cosa sagrada de Yahveh.

[[leviticus-27-31]]
^31^ Si alguno quiere rescatar parte de su diezmo, añadirá la quinta parte de su valor.

[[leviticus-27-32]]
^32^ Todo diezmo de ganado mayor o menor, es decir, cada décima cabeza que pasa bajo el cayado, será cosa sagrada de Yahveh.

[[leviticus-27-33]]
^33^ No se escogerá entre animal bueno o malo, ni se le puede sustituir; y si se hace cambio, tanto el animal permutado como su sustituto serán cosas sagradas; no podrán ser rescatados.

[[leviticus-27-34]]
^34^ Estos son los mandamientos que Yahveh encomendó a Moisés para los hijos de Israel en el monte Sinaí.
