[[numbers]]
= Números

[[numbers-1]]
== Capítulo 1

[[numbers-1-1]]
^1^ Yahveh habló a Moisés en el desierto del Sinaí, en la Tienda del Encuentro, el día primero del mes segundo, el año segundo de la salida de Egipto. Les dijo:

[[numbers-1-2]]
^2^ «Haced el censo de toda la comunidad de los israelitas, por clanes y por familias, contando los nombres de todos los varones, uno por uno.

[[numbers-1-3]]
^3^ Alistaréis, tú y Aarón, a todos los de veinte años para arriba, a todos los útiles para la guerra, por cuerpos de ejército.

[[numbers-1-4]]
^4^ Os ayudará un hombre por cada tribu, que sea jefe de su familia.

[[numbers-1-5]]
^5^ Estos son los nombres de los que os ayudarán: Por Rubén, Elisur, hijo de Sedeur.

[[numbers-1-6]]
^6^ Por Simeón, Selumiel, hijo de Surisadday.

[[numbers-1-7]]
^7^ Por Judá, Najsón, hijo de Aminadab.

[[numbers-1-8]]
^8^ Por Isacar, Natanael, hijo de Suar.

[[numbers-1-9]]
^9^ Por Zabulón, Eliab, hijo de Jelón.

[[numbers-1-10]]
^10^ Por los hijos de José: por Efraím, Elisamá, hijo de Ammihud; por Manasés, Gamaliel, hijo de Pedahsur.

[[numbers-1-11]]
^11^ Por Benjamín, Abidán, hijo de Guideoní.

[[numbers-1-12]]
^12^ Por Dan, Ajiézer, hijo de Ammisadday.

[[numbers-1-13]]
^13^ Por Aser, Paguiel, hijo de Okrán.

[[numbers-1-14]]
^14^ Por Gad, Elyasaf, hijo de Reuel.

[[numbers-1-15]]
^15^ Por Neftalí, Ajirá, hijo de Enán».

[[numbers-1-16]]
^16^ Eran éstos afamados en la comunidad, principales de las tribus de sus antepasados, jefes de milar de Israel.

[[numbers-1-17]]
^17^ Moisés y Aarón tomaron a aquellos hombres que habían sido designados por sus nombres,

[[numbers-1-18]]
^18^ y convocaron a toda la comunidad, el día primero del mes segundo. Fueron afiliados por clanes y familias, anotando uno por uno los nombres de los de veinte años para arriba.

[[numbers-1-19]]
^19^ Tal como Yahveh se lo había mandado, les pasó revista Moisés en el desierto del Sinaí.

[[numbers-1-20]]
^20^ Hecho el recuento de las parentelas de los hijos de Rubén, primogénito de Israel, por clanes y familias, anotados uno por uno los nombres de todos los varones de veinte años para arriba, útiles para la guerra,

[[numbers-1-21]]
^21^ resultaron los revistados de la tribu de Rubén, 46.500

[[numbers-1-22]]
^22^ Parentelas de los hijos de Simeón, por clanes y familias, anotados uno por uno los nombres de todos los varones de veinte años para arrriba, útiles para la guerra:

[[numbers-1-23]]
^23^ 59.300 revistados de la tribu de Simeón.

[[numbers-1-24]]
^24^ Parentelas de los hijos de Gad, por clanes y familias, anotados uno por uno los nombres de todos los varones de veinte años para arriba, útiles para la guerra:

[[numbers-1-25]]
^25^ 45.650 revistados de la tribu de Gad.

[[numbers-1-26]]
^26^ Parentelas de los hijos de Judá, por clanes y familias, anotados uno por uno los nombres de todos los varones de veinte años para arriba, útiles para la guerra:

[[numbers-1-27]]
^27^ 74.600 revistados de la tribu de Judá.

[[numbers-1-28]]
^28^ Parentelas de los hijos de Isacar, por clanes y familias, anotados uno por uno los nombres de todos los varones de veinte años para arriba, útiles para la guerra:

[[numbers-1-29]]
^29^ 54.400 revistados de la tribu de Isacar.

[[numbers-1-30]]
^30^ Parentelas de los hijos de Zabulón por clanes y familias, anotados uno por uno los nombres de todos los varones de veinte años para arriba, útiles para la guerra:

[[numbers-1-31]]
^31^ 57.400 revistados de la tribu de Zabulón.

[[numbers-1-32]]
^32^ De los hijos de José: Parentelas de los hijos de Efraím, por clanes y familias, anotados uno por uno los nombres de todos los varones de veinte años para arriba, útiles para la guerra:

[[numbers-1-33]]
^33^ 40.500 revistados de la tribu de Efraím.

[[numbers-1-34]]
^34^ Parentelas de los hijos de Manasés por clanes y familias, anotados uno por uno los nombres de todos los varones de veinte años para arriba, útiles para la guerra:

[[numbers-1-35]]
^35^ 32.200 revistados de la tribu de Manasés.

[[numbers-1-36]]
^36^ Parentelas de los hijos de Benjamín, por clanes y familias, anotados uno por uno los nombres de todos los varones de veinte años para arriba, útiles para la guerra:

[[numbers-1-37]]
^37^ 35.400 revistados de la tribu de Benjamín.

[[numbers-1-38]]
^38^ Parentelas de los hijos de Dan, por clanes y familias, anotados uno por uno los nombres de todos los varones de veinte años para arriba, útiles para la guerra:

[[numbers-1-39]]
^39^ 62.700 revistados de la tribu de Dan.

[[numbers-1-40]]
^40^ Parentelas de los hijos de Aser, por clanes y familias, anotados uno por uno los nombres de todos los varones de veinte años para arriba, útiles para la guerra:

[[numbers-1-41]]
^41^ 41.500 revistados de la tribu de Aser.

[[numbers-1-42]]
^42^ Parentelas de los hijos de Neftalí, por clanes y familias, anotados uno por uno los nombres de todos los varones de veinte años para arriba, útiles para la guerra:

[[numbers-1-43]]
^43^ 53.400 revistados de la tribu de Neftalí.

[[numbers-1-44]]
^44^ Estos fueron los revistados por Moisés y Aarón y por los doce principales de Israel, que pertenecían cada uno a una casa paterna.

[[numbers-1-45]]
^45^ Sacado el total de los israelitas de veinte años para arriba, de todos los que había en Israel, útiles para la guerra, revistados por sus casas paternas,

[[numbers-1-46]]
^46^ resultó el total de revistados: 603.550.

[[numbers-1-47]]
^47^ Pero los levitas, y su tribu paterna, no fueron revistados con ellos.

[[numbers-1-48]]
^48^ Yahveh habló a Moisés y le dijo:

[[numbers-1-49]]
^49^ «No pases revista a la tribu de Levi ni hagas su padrón entre los demás israelitas.

[[numbers-1-50]]
^50^ Alista tú mismo a los levitas para el servicio de la Morada del Testimonio, de todos sus utensilios y de todo lo que se relaciona con ella. Ellos han de llevar la Morada con todos sus utensilios, estarán al servicio de ella y acamparán en torno a ella.

[[numbers-1-51]]
^51^ Cuando haya de trasladarse la Morada, la desmontarán los levitas, y cuando la Morada se detenga, los levitas la montarán. El laico que se acerque, será muerto.

[[numbers-1-52]]
^52^ Los israelitas acamparán cada uno en su campamento y bajo su bandera, por cuerpos de ejército.

[[numbers-1-53]]
^53^ Pero los levitas acamparán alrededor de la Morada del Testimonio; y así no se desatará la Cólera contra la comunidad de los israelitas. Los levitas se encargarán del ministerio de la Morada del Testimonio».

[[numbers-1-54]]
^54^ Los israelitas lo hicieron tal como se lo había mandado Yahveh a Moisés. Así lo hicieron.
[[numbers-2]]
== Capítulo 2

[[numbers-2-1]]
^1^ Habló Yahveh a Moisés y Aarón y les dijo:

[[numbers-2-2]]
^2^ «Los israelitas acamparán cada uno bajo su bandera, bajo las enseñas de sus casas paternas, alrededor de la Tienda del Encuentro, a cierta distancia.

[[numbers-2-3]]
^3^ Acamparán al este, hacia la salida del sol: La bandera del campamento de Judá, por cuerpos de ejército. Principal de los hijos de Judá, Najsón, hijo de Aminadab.

[[numbers-2-4]]
^4^ Su cuerpo de ejército, según el censo: 74.600.

[[numbers-2-5]]
^5^ Acampados junto a él: La tribu de Isacar. Principal de los hijos de Isacar, Natanael, hijo de Suar.

[[numbers-2-6]]
^6^ Su cuerpo de ejército, según el censo: 54.400.

[[numbers-2-7]]
^7^ La tribu de Zabulón. Principal de los hijos de Zabulón, Eliab, hijo de Jelón.

[[numbers-2-8]]
^8^ Su cuerpo de ejército, según el censo, 57.400.

[[numbers-2-9]]
^9^ Total de alistados en el campamento de Judá: 186.400, reartidos en cuerpos de ejército. Marcharán en vanguardia.

[[numbers-2-10]]
^10^ Al sur, la bandera del campamento de Rubén, por cuerpos de ejército. Principal de los hijos de Rubén, Elisur, hijo de Sedeur.

[[numbers-2-11]]
^11^ Su cuerpo de ejército, según el censo: 46.500.

[[numbers-2-12]]
^12^ Acampan junto a él: La tribu de Simeón. Principal de los hijos de Simeón, Selumiel, hijo de Surisadday.

[[numbers-2-13]]
^13^ Su cuerpo de ejército, según el censo: 59.300.

[[numbers-2-14]]
^14^ La tribu de Gad. Principal de los hijos de Gad, Elyasaf, hijo de Reuel.

[[numbers-2-15]]
^15^ Su cuerpo de ejército, según el censo: 45.650.

[[numbers-2-16]]
^16^ Total de alistados en el campamento de Rubén: 151.450, repartidos en cuerpos de ejército. Marcharán en segundo lugar.

[[numbers-2-17]]
^17^ Partirá entonces la Tienda del Encuentro, pues el campamento de los levitas está en medio de los demás campamentos. En el orden en que acamparon partirán, cada uno por su lado, bajo su propia bandera.

[[numbers-2-18]]
^18^ Al occidente, la bandera del campamento de Efraím, por cuerpos de ejército. Principal de los hijos de Efraím, Elisamá, hijo de Ammihud.

[[numbers-2-19]]
^19^ Su cuerpo de ejército, según el censo: 40.500.

[[numbers-2-20]]
^20^ Junto a él: La tribu de Manasés. Principal de los hijos de Manasés, Gamaliel, hijo de Pedahsur.

[[numbers-2-21]]
^21^ Su cuerpo de ejército, según el censo: 32.200.

[[numbers-2-22]]
^22^ La tribu de Benjamín. Principal de los hijos de Benjamín, Abidán, hijo de Guideoní.

[[numbers-2-23]]
^23^ Su cuerpo de ejército, según el censo: 35.400.

[[numbers-2-24]]
^24^ Total de alistados en el campamento de Efraím: 108.100, repartidos en cuerpos de ejército. Marcharán en tercer lugar.

[[numbers-2-25]]
^25^ Al norte, la bandera de campamento de Dan, por cuerpos de ejército. Principal de los hijos de Dan, Ajiézer, hijo de Ammisadday.

[[numbers-2-26]]
^26^ Su cuerpo de ejército, según el censo: 62.700.

[[numbers-2-27]]
^27^ Acampan junto a él: La tribu de Aser. Principal de los hijos de Aser, Paguiel, hijo de Okrán.

[[numbers-2-28]]
^28^ Su cuerpo de ejército, según el censo: 41.500.

[[numbers-2-29]]
^29^ La tribu de Neftalí. Principal de los hijos de Neftalí, Ajirá, hijo de Enán.

[[numbers-2-30]]
^30^ Su cuerpo de ejército, según el censo: 53.400.

[[numbers-2-31]]
^31^ Total de alistados del campamento de Dan: 157.600. Marcharán en retaguardia, repartidos en banderas».

[[numbers-2-32]]
^32^ Estos fueron los israelitas revistados por casas paternas. Total de alistados en los campamentos, repartidos en cuerpos de ejército, 603.550.

[[numbers-2-33]]
^33^ Pero los levitas no fueron alistados entre los demás israelitas, según había mandado Yahveh a Moisés.

[[numbers-2-34]]
^34^ Los israelitas hicieron todo tal como Yahveh había mandado a Moisés: así acampaban bajo sus banderas y así emprendían la marcha, cada uno entre los demás de su clan y con su familia.
[[numbers-3]]
== Capítulo 3

[[numbers-3-1]]
^1^ Esta era la descendencia de Aarón y de Moisés, cuando Yahveh habló a Moisés en el monte Sinaí.

[[numbers-3-2]]
^2^ Estos eran los nombres de los hijos de Aarón: Nadab, el primogénito, Abihú, Eleazar e Itamar.

[[numbers-3-3]]
^3^ Estos eran los nombres de los hijos de Aarón, que fueron ungidos sacerdotes, y cuyas manos fueron consagradas para ejercer el sacerdocio.

[[numbers-3-4]]
^4^ Nadab y Abihú murieron delante de Yahveh, al presentar un fuego profano delante de Yahveh en el desierto del Sinaí. Como no tenían hijos, fueron Eleazar e Itamar los que ejercieron el sacerdocio en presencia de su padre Aarón.

[[numbers-3-5]]
^5^ Yahveh habló a Moisés y le dijo:

[[numbers-3-6]]
^6^ «Manda que se acerque la tribu de Leví y ponlos delante del sacerdote Aarón, que estén a su servicio.

[[numbers-3-7]]
^7^ Se encargarán de las obligaciones que incumben a él y a toda la comunidad ante la Tienda del Encuentro, prestando el servicio en la Morada.

[[numbers-3-8]]
^8^ Cuidarán de todos los utensilios de la Tienda del Encuentro, de las obligaciones que incumben a los israelitas prestando servicio en la Morada.

[[numbers-3-9]]
^9^ Donarás los levitas a Aarón y a sus hijos en concepto de donados. Le serán donados de parte de los israelitas.

[[numbers-3-10]]
^10^ A Aarón y a sus hijos los alistarás para que se encarguen de sus funciones sacerdotales. El laico que se acerque, será muerto».

[[numbers-3-11]]
^11^ Yahveh habló a Moisés y le dijo:

[[numbers-3-12]]
^12^ «Mira que he elegido a los levitas de entre los demás israelitas en lugar de todos los primogénitos de los israelitas que abren el seno materno. Los levitas serán para mí.

[[numbers-3-13]]
^13^ Porque todo primogénito me pertenece. El día en que herí a todos los primogénitos de Egipto, consagré para mí a todos los primogénitos de Israel, tanto de hombre como de ganado. Son para mí. Yo, Yahveh».

[[numbers-3-14]]
^14^ Habló Yahveh a Moisés en el desierto del Sinaí. Le dijo:

[[numbers-3-15]]
^15^ «Alista a los hijos de Levi por familias y por clanes: alistarás a todo varón de un mes para arriba».

[[numbers-3-16]]
^16^ Moisés los alistó según la orden de Yahveh, tal como Yahveh se lo había mandado.

[[numbers-3-17]]
^17^ Los nombres de los hijos de Leví son: Guersón, Quehab y Merarí.

[[numbers-3-18]]
^18^ Los nombres de los hijos de Ghersón, por clanes, son: Libní y Semeí.

[[numbers-3-19]]
^19^ Los hijos de Quehat, por clanes: Amram, Yishar, Hebrón y Uzziel;

[[numbers-3-20]]
^20^ los hijos de Merarí, por clanes: Majlí y Musí. Estos son los clanes de Leví, repartidos por familias.

[[numbers-3-21]]
^21^ De Guesón procedían el clan libnita y el clan semeíta: ésos son los clanes guersonitas.

[[numbers-3-22]]
^22^ El total de los alistados, contando todos los varones de un mes para arriba: 7.500.

[[numbers-3-23]]
^23^ Los clanes guersonitas acampaban detrás de la Morada, al poniente.

[[numbers-3-24]]
^24^ El principal de la casa paterna de Guersón era Elyasaf, hijo de Lael.

[[numbers-3-25]]
^25^ Los hijos de Guersón estaban encargados, en la Tienda del Encuentro, de la Morada, de la Tienda, de su toldo y del tapiz de entrada a la Tienda del Encuentro;

[[numbers-3-26]]
^26^ del cortinaje del atrio y de la cortina de entrada al atrio que rodea la Morada y el altar, y de las cuerdas necesarias para todo su servicio.

[[numbers-3-27]]
^27^ De Quehat procedían el clan amramita, el clan yisharita, el clan hebronita y el clan uzzielita: ésos son los clanes quehatitas.

[[numbers-3-28]]
^28^ Contando todos los varones de un mes para arriba, eran 8.300. Tenían a su cargo el servicio del santuario.

[[numbers-3-29]]
^29^ Los clanes quehatitas acampaban al lado meridional de la Morada.

[[numbers-3-30]]
^30^ El principal de la casa paterna de los clanes quehatitas era Elisafán, hijo de Uzziel.

[[numbers-3-31]]
^31^ A su cargo estaban el arca, la mesa, el candelabro, los altares, los objetos sagrados que se usan en el culto, el velo y todo su servicio.

[[numbers-3-32]]
^32^ El principal de los principales de Leví era Eleazar, hijo del sacerdote Aarón. Ejercía la supervisión de todos los encargados del santuario.

[[numbers-3-33]]
^33^ De Merarí, el clan majlita y el clan musita: ésos eran los clanes meraritas .

[[numbers-3-34]]
^34^ Sus alistados, contando todos los varones de un mes para arriba, eran 6.200.

[[numbers-3-35]]
^35^ El principal de la casa paterna de los clanes meraritas era Suriel, hijo de Abijayil. Acampaban al lado septentrional de la Morada.

[[numbers-3-36]]
^36^ A los hijos de Merarí les estaba encomendado el cuidado de los tableros de la Morada, de sus travesaños, postes y basas, de todos sus utensilios y todo su servicio;

[[numbers-3-37]]
^37^ y de los postes que rodean el atrio, de sus basas, clavazón y cuerdas.

[[numbers-3-38]]
^38^ Acampaban al este, frente a la Morada, delante de la Tienda del Encuentro hacia oriente, Moisés y Aarón con sus hijos que estaban encargados del santuario en nombre de los israelitas. Cualquier laico que se acercara, sería muerto.

[[numbers-3-39]]
^39^ El total de levitas alistados, de los que registró Moisés por clanes, siguiendo la orden de Yahveh, de todos los varones de un mes para arriba: 22.000.

[[numbers-3-40]]
^40^ Dijo Yahveh a Moisés: «Registra a todos los primogénitos varones de los israelitas, de un mes para arriba, y anota sus nombres.

[[numbers-3-41]]
^41^ Luego, tomas a los levitas para mí, Yahveh, en lugar de todos los primogénitos de los israelitas; y el ganado de los levitas en lugar de todos los primogénitos del ganado de los israelitas».

[[numbers-3-42]]
^42^ Moisés registró, según le había ordenado Yahveh, a todos los primogénitos de los israelitas.

[[numbers-3-43]]
^43^ Y resultó ser el total de los primogénitos varones, contando los nombres desde la edad de un mes para arriba, según el censo, 22.273.

[[numbers-3-44]]
^44^ Habló entonces Yahveh a Moisés y le dijo:

[[numbers-3-45]]
^45^ «Toma a los levitas en lugar de todos los primogénitos de los israelitas y el ganado de los levitas en lugar de su ganado; los levitas serán míos, yo Yahveh.

[[numbers-3-46]]
^46^ Por el rescate de los 273 primogénitos de los israelitas que exceden del número de los levitas,

[[numbers-3-47]]
^47^ tomarás cinco siclos por cabeza, en siclos del santuario, a razón de veinte óbolos por siclo.

[[numbers-3-48]]
^48^ La plata se la entregarás a Aarón y a sus hijos, por el rescate de los que sobrepasan el número».

[[numbers-3-49]]
^49^ Moisés tomó la plata del rescate de los que pasaban del número de los rescatados por los levitas.

[[numbers-3-50]]
^50^ Tomó la plata de los primogénitos de Israel: 1.365 siclos, en siclos del santuario.

[[numbers-3-51]]
^51^ Y entregó Moisés la plata del rescate a Aarón y a sus hijos, según la orden de Yahveh, como había mandado Yahveh a Moisés.
[[numbers-4]]
== Capítulo 4

[[numbers-4-1]]
^1^ Yahveh habló a Moisés y Aarón, diciendo:

[[numbers-4-2]]
^2^ «Haz el censo de los hijos de Quehat, hijos de Leví, por clanes y por familias,

[[numbers-4-3]]
^3^ de treinta años en adelante hasta los cincuenta, de todos los aptos para la milicia, que prestan el servicio de la Tienda del Encuentro.

[[numbers-4-4]]
^4^ Este será el servicio de los hijos de Quehat en la Tienda del Encuentro: el de las cosas sacratísimas.

[[numbers-4-5]]
^5^ Cuando se levante el campamento, irán Aarón y sus hijos, descolgarán el velo de protección y cubrirán con él el arca del Testimonio.

[[numbers-4-6]]
^6^ Pondrán sobre ella una cubierta de cuero fino y extenderán encima un paño todo de púrpura; luego le pondrán los varales.

[[numbers-4-7]]
^7^ Sobre la mesa de la presencia extenderán un paño de púrpura, y pondrán sobre ella las fuentes, copas, tazas y jarros de libación: el pan estará perpetuamente encima.

[[numbers-4-8]]
^8^ Extenderán sobre ella un paño carmesí que cubrirán con una cubierta de cuero fino, y después le pondrán los varales.

[[numbers-4-9]]
^9^ Tomarán entonces un paño de púrpura y cubrirán el candelabro del alumbrado con sus lámparas, despabiladeras y ceniceros, y todos los vasos de aceite que se utilizan en el servicio del candelabro.

[[numbers-4-10]]
^10^ Lo pondrán con todos sus utensilios en una cubierta de cuero fino y lo colocarán sobre las angarillas.

[[numbers-4-11]]
^11^ Sobre el altar de oro extenderán un paño de púrpura, lo cubrirán con una cubierta de cuero fino, y le pondrán los varales.

[[numbers-4-12]]
^12^ Tomarán todos los vasos que se emplean en el servicio del santuario, los pondrán en un paño de púrpura, los cubrirán con una cubierta de cuero fino y los colocarán sobre las angarillas.

[[numbers-4-13]]
^13^ Quitarán la grasa incinerada del altar y extenderán sobre él un paño escarlata;

[[numbers-4-14]]
^14^ pondrán encima todos los utensilios que se emplean en el servicio del altar: los braseros, tenedores, badiles, acetres: todos los utensilios del altar; extenderán sobre él una cubierta de cuero fino y le pondrán los varales.

[[numbers-4-15]]
^15^ Después que Aarón y sus hijos hayan terminado de envolver las cosas sagradas con todos sus utensilios, al ponerse en marcha el campamento, llegarán los hijos de Quehat para transportarlas; pero que no toquen lo sagrado pues morirían. Esta es la carga de los hijos de Quehat en la Tienda del Encuentro.

[[numbers-4-16]]
^16^ Pero Eleazar, hijo del sacerdote Aarón, estará al cuidado del aceite del alumbrado, del incienso aromático, de la oblación perpetua y del óleo de la unción; al cuidado de toda la Morada y de cuanto hay en ella, sean cosas sagradas o sus utensilios».

[[numbers-4-17]]
^17^ Habló Yahveh a Moisés y a Aarón y dijo:

[[numbers-4-18]]
^18^ «No separéis de los demás levitas la tribu de los clanes quehatitas.

[[numbers-4-19]]
^19^ Haced con ellos de esta manera, para que vivan y no mueran al acercarse a las cosas sacratísimas: Aarón y sus hijos irán y pondrán a cada uno en su servicio y junto a su carga.

[[numbers-4-20]]
^20^ Y no entrarán, ni por un instante, a ver las cosas sagradas; de lo contrario morirían».

[[numbers-4-21]]
^21^ Yahveh habló a Moisés y le dijo:

[[numbers-4-22]]
^22^ «Haz también el censo de los hijos de Guersón, por familias y clanes.

[[numbers-4-23]]
^23^ Alistarás a los de treinta años en adelante hasta los cincuenta a todos los aptos para la milicia para que presten el servicio de la Tienda del Encuentro.

[[numbers-4-24]]
^24^ Este será el servicio de los clanes guersonitas, su servicio y su carga.

[[numbers-4-25]]
^25^ Llevarán los tapices de la Morada, la Tienda del Encuentro, su toldo y el toldo de cueros finos que la cubre por encima y el tapiz de entrada a la Tienda del Encuentro;

[[numbers-4-26]]
^26^ el cortinaje del atrio y la cortina de la entrada al atrio que rodea la Morada y el altar, con sus cuerdas y todos los utensilios de su servicio: todo lo que se necesita para ellos. Prestarán su servicio;

[[numbers-4-27]]
^27^ pero todo el servicio de los hijos de Guersón, todas sus funciones y cargas, las desempeñarán a las órdenes de Aarón y de sus hijos. Los vigilaréis en el ministerio de su cargo.

[[numbers-4-28]]
^28^ Este será el servicio de los clanes guersonitas en la Tienda del Encuentro. Lo desempeñarán a las órdenes de Itamar, hijo del sacerdote Aarón.

[[numbers-4-29]]
^29^ Harás el censo de los hijos de Merarí, por clanes y familias.

[[numbers-4-30]]
^30^ Harás el censo de los de treinta años en adelante hasta los cincuenta, de todos los aptos para la milicia para que presten el servicio de la Tienda del Encuentro.

[[numbers-4-31]]
^31^ Esto es lo que han de transportar y este es todo su servicio en la Tienda del Encuentro: los tableros de la Morada, sus travesaños, postes y basas;

[[numbers-4-32]]
^32^ los postes que rodean el atrio con sus basas, clavazón y cuerdas; todos sus utensilios y todo lo preciso para su servicio. Nominalmente señalaréis cada uno de los objetos con que han de cargar.

[[numbers-4-33]]
^33^ Ese es el servicio de los clanes meraritas. Para todo su servicio en la Tienda del Encuentro estarán a disposición de Itamar, hijo del sacerdote Aarón».

[[numbers-4-34]]
^34^ Moisés y Aarón y los principales de la comunidad hicieron el censo de los hijos de Quehat, por clanes y familias,

[[numbers-4-35]]
^35^ de treinta años en adelante hasta los cincuenta, de todos los aptos para la milicia, para que prestaran el servicio de la Tienda del Encuentro.

[[numbers-4-36]]
^36^ Los registrados de los diversos clanes fueron 2.750.

[[numbers-4-37]]
^37^ Esos fueron los registrados en los clanes quehatitas, todos los que habían de servir en la Tienda del Encuentro. Los alistaron Moisés y Aarón, según había ordenado Yahveh por medio de Moisés.

[[numbers-4-38]]
^38^ Se hizo el censo de los hijos de Guersón, por clanes y familias,

[[numbers-4-39]]
^39^ de treinta años para arriba hasta los cincuenta, de todos los aptos para la milicia para que prestaran el servicio de la Tienda del Encuentro.

[[numbers-4-40]]
^40^ Los alistados de los diversos clanes y familias fueron 2.630.

[[numbers-4-41]]
^41^ Esos fueron los registrados de los clanes de los hijos de Guersón, todos los que habían de servir en la Tienda del Encuentro. Los alistaron Moisés y Aarón según la orden de Yahveh.

[[numbers-4-42]]
^42^ Se hizo el censo de los clanes de los hijos de Merarí, por clanes y familias,

[[numbers-4-43]]
^43^ de treinta años para arriba hasta los cincuenta, de todos los aptos para la milicia, para que prestaran el servicio de la Tienda del Encuentro.

[[numbers-4-44]]
^44^ Los revistados de los diversos clanes fueron 3.200.

[[numbers-4-45]]
^45^ Esos fueron los revistados de los clanes de los hijos de Merarí. Los alistaron Moisés y Aarón, según había ordenado Yahveh por medio de Moisés.

[[numbers-4-46]]
^46^ El total de los levitas que Moisés, Aarón y los principales de Israel registraron por clanes y familias,

[[numbers-4-47]]
^47^ de los de treinta años en adelante hasta los cincuenta, de todos los aptos para entrar al servicio y el transporte de la Tienda del Encuentro,

[[numbers-4-48]]
^48^ fue, según el censo, 8.580.

[[numbers-4-49]]
^49^ Se hizo su censo por orden de Yahveh transmitida por Moisés, asignando a cada uno su servicio y su carga: su censo se hizo tal como lo había ordenado Yahveh a Moisés.
[[numbers-5]]
== Capítulo 5

[[numbers-5-1]]
^1^ Habló Yahveh a Moisés y le dijo:

[[numbers-5-2]]
^2^ «Manda a los israelitas que echen del campamento a todo leproso, al que padece flujo y a todo impuro por contacto de cadáver.

[[numbers-5-3]]
^3^ Los has de echar, sean hombre o mujer; fuera del campamento los echarás, para que no contaminen sus campamentos, donde yo habito en medio de ellos».

[[numbers-5-4]]
^4^ Así lo hicieron los israelitas: los echaron fuera del campamento. Los israelitas lo hicieron tal como había dicho Yahveh a Moisés.

[[numbers-5-5]]
^5^ Yahveh habló a Moisés y le dijo:

[[numbers-5-6]]
^6^ «Habla a los israelitas: Si un hombre o una mujer comete cualquier pecado en perjuicio de otro, ofendiendo a Yahveh, el tal será reo de delito.

[[numbers-5-7]]
^7^ Confesará el pecado cometido y restituirá la suma de que es deudor, más un quinto. Se la devolverá a aquel de quien es deudor.

[[numbers-5-8]]
^8^ Y si el hombre no tiene pariente a quien se pueda restituir, la suma que en tal caso se ha de restituir a Yahveh, será para el sacerdote; aparte del carnero expiatorio con que el sacerdote expiará por él.

[[numbers-5-9]]
^9^ Y toda ofrenda reservada de lo que los hijos de Israel consagran y presentan al sacerdote, será para éste.

[[numbers-5-10]]
^10^ Lo que cada uno consagra, es suyo; pero lo que se presenta al sacerdote, es para el sacerdote».

[[numbers-5-11]]
^11^ Yahveh habló a Moisés y le dijo:

[[numbers-5-12]]
^12^ «Habla a los israelitas. Diles: Cualquier hombre cuya mujer se haya desviado y le haya engañado:

[[numbers-5-13]]
^13^ ha dormido un hombre con ella con relación carnal a ocultas del marido; ella se ha manchado en secreto, no hay ningún testigo, no ha sido sorprendida;

[[numbers-5-14]]
^14^ si el marido es atacado de celos y recela de su mujer, que efectivamente se ha manchado; o bien le atacan los celos y se siente celoso de su mujer, aunque ella no se haya manchado;

[[numbers-5-15]]
^15^ ese hombre llevará a su mujer ante el sacerdote y presentará por ella la ofrenda correspondiente: una décima de medida de harina de cebada. No derramará aceite sobre la ofrenda, ni la pondrá incienso, pues es «oblación de celos», oblación conmemorativa para recordar una falta.

[[numbers-5-16]]
^16^ El sacerdote presentará a la mujer y la pondrá delante de Yahveh.

[[numbers-5-17]]
^17^ Echará luego agua viva en un vaso de barro y, tomando polvo del pavimento de la Morada, lo esparcirá sobre el agua.

[[numbers-5-18]]
^18^ Pondrá el sacerdote a la mujer delante de Yahveh, le descubrirá la cabeza y pondrá en sus manos la oblación conmemorativa, o sea, la oblación de los celos. El sacerdote tendrá en sus manos las aguas de maldición y funestas.

[[numbers-5-19]]
^19^ Entonces, el sacerdote conjurará a la mujer y le dirá: “Si no ha dormido un hombre contigo, si no te has desviado ni manchado desde que estás bajo la postestad de tu marido, sé inmune a estas aguas amargas y funestas.

[[numbers-5-20]]
^20^ Pero si, estando bajo la potestad de tu marido, te has desviado y te has manchado, durmiendo con un hombre distinto de tu marido...”

[[numbers-5-21]]
^21^ El sacerdote entonces proferirá sobre la mujer este juramento, y dirá el sacerdote a la mujer: “... Que Yahveh te ponga como maldición y execración en medio de tu pueblo, que haga languidecer tus caderas e infle tu vientre.

[[numbers-5-22]]
^22^ Que entren estas aguas de maldición en tus entrañas, para que inflen tu vientre y hagan languidecer tus caderas.” Y la mujer responderá: “¡Amén, amén!”

[[numbers-5-23]]
^23^ Después el sacerdote escribirá en una hoja estas imprecaciones y las borrará con las aguas amargas.

[[numbers-5-24]]
^24^ Hará beber a la mujer las aguas de maldición y funestas, y las aguas funestas entrarán en ella para hacérsele amargas.

[[numbers-5-25]]
^25^ El sacerdote tomará entonces de la mano de la mujer la oblación de los celos, mecerá la oblación delante de Yahveh y la presentará en el altar.

[[numbers-5-26]]
^26^ El sacerdote tomará de la oblación un puñado, el memorial, y lo quemará sobre el altar, y le hará beber a la mujer las aguas.

[[numbers-5-27]]
^27^ Cuando le haga beber de las aguas, si la mujer está manchada y de hecho ha engañado a su marido, cuando entren en ella las aguas funestas le serán amargas: se inflará su vientre, languidecerán sus caderas y será mujer de maldición en medio de su pueblo.

[[numbers-5-28]]
^28^ Pero si la mujer no se ha manchado, sino que es pura, estará exenta de toda culpa y tendrá hijos.

[[numbers-5-29]]
^29^ Este es el rito de los celos, para cuando una mujer, después de estar bajo la potestad de su marido, se haya desviado y manchado;

[[numbers-5-30]]
^30^ o para cuando un hombre, atacado de celos, recele de su mujer: entonces pondrá a su mujer en presencia de Yahveh y el sacerdote realizará con ella todo este rito.

[[numbers-5-31]]
^31^ El marido estará exento de culpa, y la mujer cargará con la suya».
[[numbers-6]]
== Capítulo 6

[[numbers-6-1]]
^1^ Habló Yahveh a Moisés y le dijo:

[[numbers-6-2]]
^2^ Diles esto a los israelitas: «Si un hombre o mujer se decide a hacer voto de nazir, consagrándose a Yahveh,

[[numbers-6-3]]
^3^ se abstendrá de vino y de bebidas embriagantes. No beberá vinagre de vino ni de bebida embriagante; tampoco beberá ningún zumo de uvas, ni comerá uvas, frescas o pasas.

[[numbers-6-4]]
^4^ En todo el tiempo de su nazireato no tomará nada de lo que se obtiene de la vid, desde el agraz hasta el orujo.

[[numbers-6-5]]
^5^ En todos los días de su voto de nazireato no pasará navaja por su cabeza: hasta cumplirse los días por los que se consagró a Yahveh, será sagrado y se dejará crecer la cabellera.

[[numbers-6-6]]
^6^ No se acercará, en todos los días de su nazireato en honor de Yahveh, a ningún cadáver.

[[numbers-6-7]]
^7^ Ni por su padre, ni por su madre, ni por su hermano, ni por su hermana se manchará, en el caso de que murieran, pues lleva sobre su cabeza el nazireato de su Dios.

[[numbers-6-8]]
^8^ Todos los días de su nazireato es un consagrado a Yahveh.

[[numbers-6-9]]
^9^ Si alguien muere de repente junto a él y mancha así su cabellera de nazir, se rapará la cabeza el día de su purificación, se la rapará el día séptimo.

[[numbers-6-10]]
^10^ El día octavo llevará un par de tórtolas o un par de pichones al sacerdote, a la entrada de la Tienda del Encuentro.

[[numbers-6-11]]
^11^ El sacerdote ofrecerá uno en sacrificio por el pecado y el otro en holocausto; y expiará por aquel hombre la falta contraída a causa del muerto. Aquel día consagrará su cabeza:

[[numbers-6-12]]
^12^ se consagrará a Yahveh por todo el tiempo de su nazireato y ofrecerá un cordero de un año como sacrificio de reparación. Los días anteriores son nulos, por haberse manchado su cabellera.

[[numbers-6-13]]
^13^ Este es el rito del nazir, para cuando se cumplan los días de su nazireato. Llevado hasta la entrada de la Tienda del Encuentro,

[[numbers-6-14]]
^14^ presentará su ofrenda a Yahveh: un cordero de un año, sin defecto, en holocausto; una cordera de un año, sin defecto, en sacrificio por el pecado; un carnero sin defecto como sacrificio de comunión;

[[numbers-6-15]]
^15^ un canastillo de panes ázimos de flor de harina amasada con aceite y tortas sin levadura untadas en aceite, con sus correspondientes oblaciones y libaciones.

[[numbers-6-16]]
^16^ El sacerdote lo presentará delante de Yahveh y ofrecerá el sacrificio por el pecado y el holocausto del nazir.

[[numbers-6-17]]
^17^ Hará con el carnero un sacrificio de comunión a Yahveh, junto con el canastillo de ázimos, ofrecerá luego el sacerdote la correspondiente oblación y libación.

[[numbers-6-18]]
^18^ Entonces el nazir se rapará su cabellera de nazir, a la entrada de la Tienda del Encuentro; tomara la cabellera de su nazireato y la echará al fuego que arde debajo del sacrificio de comunión.

[[numbers-6-19]]
^19^ El sacerdote tomará un brazuelo, ya cocido, del carnero, un pan ázimo del canastillo y una torta sin levadura, y lo pondrá todo en manos del nazir, una vez que se haya rapado su cabellera de nazir.

[[numbers-6-20]]
^20^ El sacerdote presentará todo ello como ofrenda mecida delante de Yahveh. Es cosa santa, pertenece al sacerdote, además del pecho mecido y de la pierna reservada. Luego el nazir beberá vino.

[[numbers-6-21]]
^21^ Ese es el rito del nazir que, además de su nazireato, ha prometido una ofrenda a Yahveh (aparte de lo que sus posibilidades le permitan): a tenor del voto que prometió lo cumplirá además de lo prescrito para su nazireato».

[[numbers-6-22]]
^22^ Habló Yahveh a Moisés y le dijo:

[[numbers-6-23]]
^23^ Habla a Aarón y a sus hijos y diles: «Así habéis de bendecir a los israelitas. Les diréis:

[[numbers-6-24]]
^24^ Yahveh te bendiga y te guarde;

[[numbers-6-25]]
^25^ ilumine Yahveh su rostro sobre ti y te sea propicio;

[[numbers-6-26]]
^26^ Yahveh te muestre su rostro y te conceda la paz».

[[numbers-6-27]]
^27^ Que invoquen así mi nombre sobre los israelitas y yo los bendeciré».
[[numbers-7]]
== Capítulo 7

[[numbers-7-1]]
^1^ El día en que Moisés acabó de montar la Morada, la ungió y la consagró con todo su mobiliario, así como el altar con todos sus utensilios. Cuando lo hubo ungido y consagrado,

[[numbers-7-2]]
^2^ los principales de Israel, jefes de familias, y principales de las tribus, que habían presidido el censo, hicieron una ofrenda.

[[numbers-7-3]]
^3^ Pusieron su ofrenda delante de Yahveh: seis carretas cubiertas y doce bueyes: una carreta por cada dos principales y un buey por cada uno. Lo presentaron delante de la Morada.

[[numbers-7-4]]
^4^ Yahveh habló a Moisés y le dijo:

[[numbers-7-5]]
^5^ «Tómaselos y que presten servicio en la Tienda del Encuentro. Dáselos a los levitas, a cada uno según su servicio».

[[numbers-7-6]]
^6^ Moisés recibió las carretas y los bueyes y se los dio a los levitas:

[[numbers-7-7]]
^7^ dos carretas y cuatro bueyes dio a los hijos de Guersón, según sus servicios;

[[numbers-7-8]]
^8^ cuatro carretas y ocho bueyes a los hijos de Merarí, según los servicios que desempeñaban a las órdenes de Itamar, hijo del sacerdote Aarón.

[[numbers-7-9]]
^9^ Pero a los hijos de Quehat no les dio, porque su carga sagrada la tenían que llevar al hombro.

[[numbers-7-10]]
^10^ Los principales hicieron la ofrenda de la dedicación del altar, el día en que fue ungido. Hicieron los principales su ofrenda delante del altar.

[[numbers-7-11]]
^11^ Y dijo Yahveh a Moisés: «Que ofrezca un principal cada día su ofrenda por la dedicación del altar».

[[numbers-7-12]]
^12^ El que ofreció su ofrenda el primer día fue Najsón, hijo de Aminadab, de la tribu de Judá.

[[numbers-7-13]]
^13^ Su ofrenda consistía en una fuente de plata de 130 siclos de peso, un acetre de plata de setenta siclos, en siclos del santuario, ambos llenos de flor de harina amasada con aceite, para la oblación;

[[numbers-7-14]]
^14^ una naveta de oro de diez siclos, llena de incienso;

[[numbers-7-15]]
^15^ un novillo, un carnero, un cordero de un año, para el holocausto;

[[numbers-7-16]]
^16^ un chivo para el sacrificio por el pecado;

[[numbers-7-17]]
^17^ y para el sacrificio de comunión, dos bueyes, cinco carneros, cinco machos cabríos y cinco corderos de un año. Esa fue la ofrenda de Najson, hijo de Aminadab.

[[numbers-7-18]]
^18^ El segundo día ofreció su ofrenda Natanael, hijo de Suar, principal de Isacar.

[[numbers-7-19]]
^19^ Su ofrenda consistía en una fuente de plata de 130 siclos de peso, un acetre de plata de setenta siclos, en siclos del santuario, ambos llenos de flor de harina amasada con aceite, para la oblación;

[[numbers-7-20]]
^20^ una naveta de oro de diez siclos, llena de incienso;

[[numbers-7-21]]
^21^ un novillo, un carnero, un cordero de un año, para el holocausto;

[[numbers-7-22]]
^22^ un chivo para el sacrificio por el pecado;

[[numbers-7-23]]
^23^ y para el sacrificio de comunión, dos bueyes, cinco carneros, cinco machos cabríos y cinco corderos de un año. Esa fue la ofrenda de Natanael, hijo de Suar.

[[numbers-7-24]]
^24^ El tercer día, el principal de los hijos de Zabulón, Eliab, hijo de Jelón.

[[numbers-7-25]]
^25^ Su ofrenda consistía en una fuente de plata de 130 siclos de peso, un acetre de plata de setenta siclos, en siclos del santuario, ambos llenos de flor de harina amasada con aceite, para la oblación;

[[numbers-7-26]]
^26^ una naveta de oro de diez siclos, llena de incienso;

[[numbers-7-27]]
^27^ un novillo, un carnero, un cordero de un año, para el holocausto;

[[numbers-7-28]]
^28^ un chivo para el sacrificio por el pecado;

[[numbers-7-29]]
^29^ y para el sacrificio de comunión, dos bueyes, cinco carneros, cinco machos cabríos y cinco corderos de un año. Esa fue la ofrenda de Eliab, hijo de Jelón.

[[numbers-7-30]]
^30^ El día cuarto, el principal de los hijos de Rubén, Elisur, hijo de Sedeur.

[[numbers-7-31]]
^31^ Su ofrenda consistía en una fuente de plata de 130 siclos de peso; un acetre de plata de setenta siclos, en siclos del santuario, ambos llenos de flor de harina amasada con aceite, para la oblación;

[[numbers-7-32]]
^32^ una naveta de diez siclos de oro llena de incienso;

[[numbers-7-33]]
^33^ un novillo, un carnero, un cordero de un año, para el holocausto;

[[numbers-7-34]]
^34^ un chivo para el sacrificio por el pecado;

[[numbers-7-35]]
^35^ y para el sacrificio de comunión, dos bueyes, cinco carneros, cinco machos cabríos, cinco corderos de un año. Esa fue la ofrenda de Elisur, hijo de Sedeur.

[[numbers-7-36]]
^36^ El día quinto, el principal de los hijos de Simeón, Selumiel, hijo de Surisadday.

[[numbers-7-37]]
^37^ Su ofrenda consistía en una fuente de plata de 130 siclos de peso, un acetre de plata de setenta siclos, en siclos del santuario, ambos llenos de flor de harina amasada con aceite, para la oblación;

[[numbers-7-38]]
^38^ una naveta de oro de diez siclos, llena de incienso;

[[numbers-7-39]]
^39^ un novillo, un carnero, un cordero de un año, para el holocausto;

[[numbers-7-40]]
^40^ un chivo para el sacrificio por el pecado;

[[numbers-7-41]]
^41^ y para el sacrificio de comunión, dos bueyes, cinco carneros, cinco machos cabríos y cinco corderos de un año. Esa fue la ofrenda de Selumiel, hijo de Surisadday.

[[numbers-7-42]]
^42^ El día sexto, el principal de los hijos de Gad, Elyasaf, hijo de Reuel.

[[numbers-7-43]]
^43^ Su ofrenda consistía en una fuente de plata de 130 siclos; un acetre de plata de setenta siclos, en siclos del santuario, ambos llenos de flor de harina amasada con aceite, para la oblación;

[[numbers-7-44]]
^44^ una naveta de oro de diez siclos, llena de incienso;

[[numbers-7-45]]
^45^ un novillo, un carnero y un cordero de un año, para el holocausto;

[[numbers-7-46]]
^46^ un chivo para el sacrificio por el pecado;

[[numbers-7-47]]
^47^ y para el sacrificio de comunión, dos bueyes, cinco carneros, cinco machos cabríos y cinco corderos de un año. Esa fue la ofrenda de Elyasaf, hijo de Reuel.

[[numbers-7-48]]
^48^ El día séptimo, el principal de los hijos de Efraím, Elisamá, hijo de Ammihud.

[[numbers-7-49]]
^49^ Su ofrenda consistía en una fuente de plata de 130 siclos de peso, un acetre de plata de setenta siclos, en siclos del santuario, ambos llenos de flor de harina amasada con aceite, para la oblación;

[[numbers-7-50]]
^50^ una naveta de oro de diez siclos, llena de incienso;

[[numbers-7-51]]
^51^ un novillo, un carnero, un cordero de un año, para el holocausto;

[[numbers-7-52]]
^52^ un chivo, para el sacrificio por el pecado;

[[numbers-7-53]]
^53^ y para el sacrificio de comunión, dos bueyes, cinco carneros, cinco machos cabríos y cinco corderos de un año. Esa fue la ofrenda de Elisamá, hijo de Ammihud.

[[numbers-7-54]]
^54^ El día octavo, el principal de los hijos de Manasés, Gamaliel, hijo de Pedahsur.

[[numbers-7-55]]
^55^ Su ofrenda consistía en una fuente de plata de 130 siclos de peso, un acetre de plata de setenta siclos, en siclos del santuario, ambos llenos de flor de harina amasada con aceite, para la oblación;

[[numbers-7-56]]
^56^ una naveta de oro de diez siclos, llena de incienso;

[[numbers-7-57]]
^57^ un novillo, un carnero, un cordero de un año, para el holocausto;

[[numbers-7-58]]
^58^ un chivo para el sacrificio por el pecado;

[[numbers-7-59]]
^59^ y para el sacrificio de comunión, dos bueyes, cinco carneros, cinco machos cabríos y cinco corderos de un año. Esa fue la ofrenda de Gamaliel, hijo de Pedahsur.

[[numbers-7-60]]
^60^ El día nono, el principal de los hijos de Benjamín, Abidán, hijo de Guideoní.

[[numbers-7-61]]
^61^ Su ofrenda consistía en una fuente de plata de 130 siclos de peso, un acetre de plata de setenta siclos, en siclos del santuario, ambos llenos de flor de harina amasada con aceite, para la oblación;

[[numbers-7-62]]
^62^ una naveta de oro de diez siclos, llena de incienso;

[[numbers-7-63]]
^63^ un novillo, un carnero, un cordero de un año, para el holocausto;

[[numbers-7-64]]
^64^ un chivo para el sacrificio por el pecado;

[[numbers-7-65]]
^65^ y para el sacrificio de comunión, dos bueyes, cinco carneros, cinco machos cabríos y cinco corderos de un año. Esa fue la ofrenda de Abidán, hijo de Guideoní.

[[numbers-7-66]]
^66^ El día décimo, el principal de los hijos de Dan, Ajiézer, hijo de Ammisadday.

[[numbers-7-67]]
^67^ Su ofrenda consistía en una fuente de plata de 130 siclos de peso, un acetre de plata de setenta siclos, en siclos del santuario, ambos llenos de flor de harina amasada con aceite, para la oblación;

[[numbers-7-68]]
^68^ una naveta de oro de diez siclos, llena de incienso;

[[numbers-7-69]]
^69^ un novillo, un carnero, un cordero de un año, para el holocausto;

[[numbers-7-70]]
^70^ un chivo para el sacrificio por el pecado;

[[numbers-7-71]]
^71^ y para el sacrificio de comunión, dos bueyes, cinco carneros, cinco machos cabríos y cinco corderos de un año. Esa fue la ofrenda de Ajiézer, hijo de Ammisadday.

[[numbers-7-72]]
^72^ El día undécimo, el principal de los hijos de Aser, Paguiel, hijo de Okrán.

[[numbers-7-73]]
^73^ Su ofrenda consistía en una fuente de plata de 130 siclos de peso, un acetre de plata de setenta siclos, en siclos del santuario, ambos llenos de flor de harina amasada con aceite, para la oblación;

[[numbers-7-74]]
^74^ una naveta de oro de diez siclos, llena de incienso;

[[numbers-7-75]]
^75^ un novillo, un carnero, un cordero de un año, para el holocausto;

[[numbers-7-76]]
^76^ un chivo para el sacrificio por el pecado;

[[numbers-7-77]]
^77^ y para el sacrificio de comunión, dos bueyes, cinco carneros, cinco machos cabríos y cinco corderos de un año. Esa fue la ofrenda de Paguiel, hijo de Okrán.

[[numbers-7-78]]
^78^ El día duodécimo, el principal de los hijos de Neftalí, Ajirá, hijo de Enán.

[[numbers-7-79]]
^79^ Su ofrenda consistía en una fuente de plata de 130 siclos de peso, un acetre de plata de setenta siclos, en siclos del santuario, ambos llenos de flor de harina amasada con aceite, para la oblación;

[[numbers-7-80]]
^80^ una naveta de oro de diez siclos, llena de incienso;

[[numbers-7-81]]
^81^ un novillo, un carnero, un cordero de un año, para el holocausto;

[[numbers-7-82]]
^82^ un chivo para el sacrificio por el pecado;

[[numbers-7-83]]
^83^ y para el sacrificio de comunión, dos bueyes, cinco carneros, cinco machos cabríos y cinco corderos de un año. Esa fue la ofrenda de Ajirá, hijo de Enán.

[[numbers-7-84]]
^84^ Esta fue la ofrenda de los principales de Israel en la dedicación del altar, el día en que fue ungido: doce fuentes de plata, doce acetres de plata y doce navetas de oro.

[[numbers-7-85]]
^85^ Cada fuente era de 130 siclos, y cada acetre de setenta. Los siclos de plata de estos objetos eran en total 2.400, en siclos del santuario.

[[numbers-7-86]]
^86^ Las navetas de oro eran doce, llenas de incienso. Cada naveta era de diez siclos, en siclos del santuario. Los siclos de oro de las navetas eran en total 120.

[[numbers-7-87]]
^87^ El total del ganado para el holocausto, doce novillos, doce carneros, doce corderos de un año, con sus oblaciones correspondientes; para el sacrificio por el pecado, doce chivos.

[[numbers-7-88]]
^88^ El total del ganado para los sacrificios de comunión: veinticuatro novillos, sesenta carneros, sesenta machos cabríos y sesenta corderos de un año. Esas fueron las ofrendas de la dedicación del altar, una vez que fue ungido.

[[numbers-7-89]]
^89^ Cuando Moisés entraba en la Tienda del Encuentro para hablar con El, oía la voz que le hablaba de lo alto del propiciatorio que está sobre el arca del Testimonio, de entre los dos querubines. Entonces hablabla con El.
[[numbers-8]]
== Capítulo 8

[[numbers-8-1]]
^1^ Habló Yahveh a Moisés y le dijo:

[[numbers-8-2]]
^2^ Habla a Aarón y dile: «Cuando coloques las lámparas, habrán de alumbrar las siete lámparas hacia la parte delantera del candelabro».

[[numbers-8-3]]
^3^ Así lo hizo Aarón: colocó las lámparas en la parte delantera del candelabro, tal como había mandado Yahveh a Moisés.

[[numbers-8-4]]
^4^ Este candelabro era de oro macizo; desde el pie hasta las flores era de oro macizo. Hizo el candelabro según el modelo que Yahveh había mostrado a Moisés.

[[numbers-8-5]]
^5^ Habló Yahveh a Moisés y le dijo:

[[numbers-8-6]]
^6^ «Aparta a los levitas del resto de los israelitas y purifícalos.

[[numbers-8-7]]
^7^ Para esta purificación harás con ellos de la siguiente manera: los rociarás con agua lustral; se rasurarán ellos todo el cuerpo, lavarán sus vestidos y así quedarán purificados.

[[numbers-8-8]]
^8^ Tomarán luego un novillo, con su correspondiente oblación de flor de harina amasada con aceite y tú tomarás otro novillo como sacrificio por el pecado.

[[numbers-8-9]]
^9^ Mandarás que se acerquen los levitas a la Tienda del Encuentro y convocarás a toda la comunidad de los israelitas.

[[numbers-8-10]]
^10^ Harás que se acerquen los levitas ante Yahveh, y los israelitas les impondrán las manos.

[[numbers-8-11]]
^11^ Entonces Aarón presentará a los levitas como ofrenda mecida delante de Yahveh, de parte de los israelitas. Así quedarán destinados al servicio de Yahveh.

[[numbers-8-12]]
^12^ Los levitas impondrán sus manos sobre la cabeza de los novillos y tú ofrecerás uno como sacrificio por el pecado y otro en holocausto a Yahveh para expiar por los levitas.

[[numbers-8-13]]
^13^ Pondrás luego a los levitas delante de Aarón y de sus hijos y los presentarás como ofrenda mecida a Yahveh.

[[numbers-8-14]]
^14^ Así separarás a los levitas del resto de los israelitas para que me pertenezcan.

[[numbers-8-15]]
^15^ Después comenzarán los levitas a servir en la Tienda del Encuentro. Los purificarás y los presentarás como ofrenda mecida,

[[numbers-8-16]]
^16^ porque son «donados», son donados a mí, de entre los israelitas, en lugar de todos los que abren el seno materno, de todos los primogénitos; los he tomado para mí de entre los demás israelitas.

[[numbers-8-17]]
^17^ Porque míos son todos los primogénitos entre los israelitas, igual de hombres que de ganados: me los consagré el día que heri a todos los primogénitos en Egipto.

[[numbers-8-18]]
^18^ Y tomé a los levitas para sustituir a todos los primogénitos de los israelitas.

[[numbers-8-19]]
^19^ Yo cedo los levitas, como «donados», a Aarón y a sus hijos, de entre los israelitas, para que presten el servicio, en nombre de los israelitas, en la Tienda del Encuentro, y para expiar por los israelitas de manera que ningún israelita incurra en castigo por acercarse al Santuario».

[[numbers-8-20]]
^20^ Moisés y Aarón y toda la comunidad de los israelitas hicieron con los levitas conforme había mandado Yahveh a Moisés; así hicieron con ellos los israelitas.

[[numbers-8-21]]
^21^ Los levitas se purificaron, lavaron sus vestidos, y Aarón los presentó como ofrenda mecida delante de Yahveh; y Aarón hizo expiación por ellos para purificarlos.

[[numbers-8-22]]
^22^ Después de lo cual entraron los levitas a prestar servicio en la Tienda del Encuentro en presencia de Aarón y de sus hijos. Según había mandado Yahveh a Moisés acerca de los levitas, así hicieron con ellos.

[[numbers-8-23]]
^23^ Habló Yahveh a Moisés y le dijo:

[[numbers-8-24]]
^24^ «Esto es lo referente a los levitas. De veinticinco años para arriba entrará al servicio de la Tienda del Encuentro,

[[numbers-8-25]]
^25^ y desde los cincuenta años cesará en el servicio; no servirá ya más.

[[numbers-8-26]]
^26^ Ayudará a sus hermanos en la Tienda del Encuentro en el desempeño de su ministerio, mas no prestará servicio. Así harás con los levitas en lo tocante a sus funciones».
[[numbers-9]]
== Capítulo 9

[[numbers-9-1]]
^1^ Habló Yahveh a Moisés, en el desierto del Sinaí, el año segundo de la salida de Egipto, el mes primero, y le dijo:

[[numbers-9-2]]
^2^ «Que los israelitas celebren la Pascua a su tiempo.

[[numbers-9-3]]
^3^ La celebrarán el día catorce de este mes, entre dos luces, al tiempo debido. La celebrarán según todos sus preceptos y normas».

[[numbers-9-4]]
^4^ Moisés dijo a los israelitas que celebraran la Pascua.

[[numbers-9-5]]
^5^ La celebraron en el desierto del Sinaí, el primer mes, el día catorce del mes, entre dos luces. Según había mandado Yahveh a Moisés lo hicieron los israelitas.

[[numbers-9-6]]
^6^ Pero sucedió que algunos hombres estaban impuros por contacto de cadáver humano y no podían celebrar la Pascua aquel día. Se presentaron a Moisés y Aarón el mismo día

[[numbers-9-7]]
^7^ y les dijeron: «Estamos impuros por contacto de cadáver humano. ¿Por qué hemos de quedar excluidos de presentar la ofrenda a Yahveh a su tiempo con los demás israelitas?»

[[numbers-9-8]]
^8^ Moisés les respondió: «Esperad, que voy a consultar lo que os manda Yahveh».

[[numbers-9-9]]
^9^ Yahveh habló a Moisés y le dijo:

[[numbers-9-10]]
^10^ «Diles a los israelitas: Si uno de vosotros o de vuestros descendientes está impuro por cadáver, o está de viaje en tierra lejana, también celebrará la Pascua en honor de Yahveh.

[[numbers-9-11]]
^11^ La celebrarán el mes segundo, el día catorce, entre dos luces. La comerán con panes ázimos y hierbas amargas.

[[numbers-9-12]]
^12^ No dejarán nada para la mañana, ni le quebrantarán ningún hueso. Según todo el ritual de la Pascua la celebrarán.

[[numbers-9-13]]
^13^ Pero el que, encontrándose puro y no habiendo estado de viaje, deje de celebrar la Pascua, ese tal será extirpado de su pueblo. Ese hombre cargará con su pecado, por no haber presentado la ofrenda a Yahveh a su tiempo.

[[numbers-9-14]]
^14^ Y si un forastero reside entre vosotros y celebra la Pascua en honor de Yahveh, la celebrará según los preceptos y normas de la Pascua. Uno mismo será el ritual para vosotros, tanto para el forastero como para el nativo del país».

[[numbers-9-15]]
^15^ El día en que se erigió la Morada, la Nube cubrió la Morada, la Tienda del Testimonio. Por la tarde se quedaba sobre la Morada, con aspecto de fuego, hasta la mañana.

[[numbers-9-16]]
^16^ Así sucedía permanentemente: la Nube la cubría y por la noche tenía aspecto de fuego.

[[numbers-9-17]]
^17^ Cuando se levantaba la Nube de encima de la Tienda, los israelitas levantaban el campamento, y en el lugar en que se paraba la Nube, acampaban los israelitas.

[[numbers-9-18]]
^18^ A la orden de Yahveh partían los israelitas y a la orden de Yahveh acampaban. Quedaban acampados todos los días que la Nube estaba parada sobre la Morada.

[[numbers-9-19]]
^19^ Si se detenía la Nube muchos días sobre la Morada, los israelitas cumplían con el culto de Yahveh y no partían.

[[numbers-9-20]]
^20^ En cambio, si la Nube estaba sobre la Morada pocos días, a la orden de Yahveh acampaban y a la orden de Yahveh partían.

[[numbers-9-21]]
^21^ Si la Nube estaba sobre la Morada sólo de la noche a la mañana, y por la mañana se alzaba, ellos partían. Si estaba un día y una noche y luego se elevaba, partían.

[[numbers-9-22]]
^22^ Si, en cambio, se detenía sobre la Morada dos días, o un mes, o un año, reposando sobre ella, los israelitas se quedaban en el campamento y no partían; pero en cuanto se elevaba, partían.

[[numbers-9-23]]
^23^ A la orden de Yahveh acampaban y a la orden de Yahveh movían el campamento. Rendían culto a Yahveh, según la orden de Yahveh transmitida por Moisés.
[[numbers-10]]
== Capítulo 10

[[numbers-10-1]]
^1^ Habló Yahveh a Moisés y le dijo:

[[numbers-10-2]]
^2^ «Hazte dos trompetas: las harás de plata maciza. Te servirán para convocar a la comunidad y dar la señal de mover el campamento.

[[numbers-10-3]]
^3^ Cuando suenen las dos, se reunirá junto a ti toda la comunidad, a la entrada de la Tienda del Encuentro.

[[numbers-10-4]]
^4^ Pero cuando suene una sola, se reunirán contigo los principales, jefes de millares de Israel.

[[numbers-10-5]]
^5^ Cuando toquéis a clamoreo, partirán los que acampan a oriente.

[[numbers-10-6]]
^6^ Cuando toquéis a clamoreo por segunda vez, partirán los campamentos que acampan al mediodía, Tocaréis a clamoreo para partir;

[[numbers-10-7]]
^7^ en cambio, para congregar la asamblea, tocaréis sin clamoreo.

[[numbers-10-8]]
^8^ Los hijos de Aarón, los sacerdotes, serán los que toquen las trompetas: este serán un decreto perpetuo para vosotros y para vuestra descendencia.

[[numbers-10-9]]
^9^ Cuando, ya en vuestra tierra, partáis para el combate contra un enemigo que os oprime, tocaréis las trompetas a clamoreo; así se acordará Yahveh, vuestro Dios, de vosotros, y seréis librados de vuestros enemigos.

[[numbers-10-10]]
^10^ En vuestros días de fiesta, solemnidades, neomenias, tocaréis las trompetas durante vuestros holocaustos y sacrificios de comunión. Así haréis que vuestro Dios se acuerde de vosotros. Yo, Yahveh, vuestro Dios».

[[numbers-10-11]]
^11^ El año segundo, el mes segundo, el día veinte del mes, se levantó la Nube de encima de la Morada del Testimonio,

[[numbers-10-12]]
^12^ y los israelitas partieron, en orden de marcha, del desierto del Sinaí. La nube se detuvo en el desierto de Parán.

[[numbers-10-13]]
^13^ Partieron en vanguardia según la orden que Yahveh había dado a Moisés:

[[numbers-10-14]]
^14^ la bandera del campamento de los hijos de Judá en primer lugar, por cuerpos de ejército. Al frente de su tropa, iba Najsón, hijo de Aminadab;

[[numbers-10-15]]
^15^ al frente de la tropa de la tribu de los hijos de Isacar, Natanael, hijo de Suar;

[[numbers-10-16]]
^16^ al frente de la tropa de la tribu de los hijos de Zabulón, Eliab, hijo de Jelón.

[[numbers-10-17]]
^17^ Entonces fue desmontada la Morada y partieron los hijos de Guerson y los hijos de Merarí, llevando la Morada.

[[numbers-10-18]]
^18^ Partió luego la bandera del campamento de Rubén, por cuerpos de ejército: al frente de su tropa iba Elisur, hijo de Sedeur;

[[numbers-10-19]]
^19^ al frente de la tropa de la tribu de los hijos de Simeón, Selumiel, hijo de Surisadday;

[[numbers-10-20]]
^20^ al frente de la tropa de la tribu de los hijos de Gad, Elyasaf, hijo de Reuel.

[[numbers-10-21]]
^21^ Entonces partieron los quehatitas, que llevaban el santuario (la Morada se montaba antes de que llegaran).

[[numbers-10-22]]
^22^ Partió luego la bandera del campamento de los hijos de Efraím, por cuerpos de ejército; al frente de su tropa iba Elisamá, hijo de Ammihud.

[[numbers-10-23]]
^23^ Al frente de la tropa de la tribu de los hijos de Manasés, Gamaliel, hijo de Pedahsur;

[[numbers-10-24]]
^24^ al frente de la tropa de la tribu de los hijos de Benjamín, Abidán, hijo de Guideoní.

[[numbers-10-25]]
^25^ Luego, cerrando la marcha de todos los campamentos, partió la bandera del campamento de los hijos de Dan, por cuerpos de ejército. Al frente de su tropa iba Ajiézer, hijo de Ammisadday;

[[numbers-10-26]]
^26^ al frente de la tropa de la tribu de los hijos de Aser, Paguiel, hijo de Okrán;

[[numbers-10-27]]
^27^ al frente de la tropa de la tribu de los hijos de Neftalí, Ajirá, hijo de Enán.

[[numbers-10-28]]
^28^ Este fue el orden de marcha de los israelitas, repartidos en cuerpos de ejército. Y así partieron.

[[numbers-10-29]]
^29^ Dijo Moisés a Jobab, hijo de Reuel el madianito, suegro de Moisés: «Nosotros partimos para el lugar del que ha dicho Yahveh: Os lo daré. Ven con nosotros y te trataremos bien, porque Yahveh ha prometido bienestar a Israel».

[[numbers-10-30]]
^30^ El respondió: «No iré, sino que me volveré a mi tierra y a mi parentela».

[[numbers-10-31]]
^31^ Moisés insistió: «Por favor, no os dejes; tú conoces los sitios donde acampar en el desierto; tú serás nuestros ojos.

[[numbers-10-32]]
^32^ Si vienes con nosotros, te haremos partícipe del bienestar con que Yahveh nos va a favorecer».

[[numbers-10-33]]
^33^ Partieron del monte de Yahveh para hacer tres jornadas. El arca de la alianza de Yahveh iba delante de ellos los tres días de camino, buscándoles donde hacer alto.

[[numbers-10-34]]
^34^ La Nube de Yahveh iba de día sobre ellos, desde que dejaron el campamento.

[[numbers-10-35]]
^35^ Cuando partía el arca, decía Moisés: «Levántate, Yahveh, que tus enemigos se dispersen, huyan delante de ti los que te odian».

[[numbers-10-36]]
^36^ Y cuando se detenía, decía: «Vuelve, Yahveh, a las miríadas de Israel».
[[numbers-11]]
== Capítulo 11

[[numbers-11-1]]
^1^ El pueblo profería quejas amargas a los oídos de Yahveh, y Yahveh lo oyó. Se encendió su ira y ardió un fuego de Yahveh entre ellos y devoró un extremo del campamento.

[[numbers-11-2]]
^2^ El pueblo clamó a Moisés y Moisés intercedió ante Yahveh, y el fuego se apagó.

[[numbers-11-3]]
^3^ Por eso se llamó aquel lugar Taberá, porque había ardido contra ellos el fuego de Yahveh.

[[numbers-11-4]]
^4^ La chusma que se había mezclado al pueblo se dejó llevar de su apetito. También los israelitas volvieron a sus llantos diciendo: «¿Quién nos dará carne para comer?

[[numbers-11-5]]
^5^ ¡Cómo nos acordamos del pescado que comíamos de balde en Egipto, y de los pepinos, melones, puerros, cebollas y ajos!

[[numbers-11-6]]
^6^ En cambio ahora tenemos el alma seca. No hay de nada. Nuestros ojos no ven más que el maná».

[[numbers-11-7]]
^7^ El maná era como la semilla del cilantro; su aspecto era como el del bedelio.

[[numbers-11-8]]
^8^ El pueblo se desparramaba para recogerlo; lo molian en la muela o lo majaban en el mortero; luego lo cocían en la olla y hacían con él tortas. Su sabor era parecido al de una torta de aceite.

[[numbers-11-9]]
^9^ Cuando, por la noche, caía el rocío sobre el campamento, caía también sobre él el maná.

[[numbers-11-10]]
^10^ Moisés oyó llorar al pueblo, cada uno en su familia, a la puerta de su tienda. Se irritó mucho la ira de Yahveh. A Moisés le pareció mal,

[[numbers-11-11]]
^11^ y le dijo a Yahveh: «¿Por qué tratas mal a tu siervo? ¿Por qué no he hallado gracia a tus ojos, para que hayas echado sobre mí la carga de todo este pueblo?

[[numbers-11-12]]
^12^ ¿Acaso he sido yo el que ha concebido a todo este pueblo y lo ha dado a luz, para que me digas: “Llévalo en tu regazo, como lleva la nodriza al niño de pecho, hasta la tierra que prometí con juramento a sus padres?”

[[numbers-11-13]]
^13^ ¿De dónde voy a sacar carne para dársela a todo este pueblo, que me llora diciendo: Danos carne para comer?

[[numbers-11-14]]
^14^ No puedo cargar yo solo con todo este pueblo: es demasiado pesado para mí.

[[numbers-11-15]]
^15^ Si vas a tratarme así, mátame, por favor, si he hallado gracia a tus ojos, para que no vea más mi desventura».

[[numbers-11-16]]
^16^ Yahveh respondió a Moisés: «Reúneme setenta ancianos de Israel, de los que sabes que son ancianos y escribas del pueblo. Llévalos a la Tienda del Encuentro y que estén allí contigo.

[[numbers-11-17]]
^17^ Yo bajaré a hablar contigo; tomaré parte del espíritu que hay en ti y lo pondré en ellos, para que lleven contigo la carga del pueblo y no la tengas que llevar tú solo.

[[numbers-11-18]]
^18^ «Y al pueblo le dirás: Santificaos para mañana, que vais a comer carne, ya que os habéis lamentado a oídos de Yahveh, diciendo: “¿Quién nos dará carne para comer? Mejor nos iba en Egipto.” Pues Yahveh os va a dar carne, y comeréis.

[[numbers-11-19]]
^19^ No un día, ni dos, ni cinco, ni diez ni veinte la comeréis,

[[numbers-11-20]]
^20^ sino un mes entero, hasta que os salga por las narices y os dé náuseas, pues habéis rechazado a Yahveh, que está en medio de vosotros, y os habéis lamentado en su presencia, diciendo: ¿Por qué salimos de Egipto?»

[[numbers-11-21]]
^21^ Moisés respondió: «El pueblo en que estoy cuenta 600.000 de a pie, ¿y tú dices que les darás carne para comer un mes entero?

[[numbers-11-22]]
^22^ Aunque se mataran para ellos rebaños de ovejas y bueyes, ¿bastaría acaso? Aunque se juntaran todos los peces del mar ¿habría suficiente?»

[[numbers-11-23]]
^23^ Pero Yahveh respondió a Moisés: «¿Es acaso corta la mano de Yahveh? Ahora vas a ver si vale mi palabra o no».

[[numbers-11-24]]
^24^ Salió Moisés y transmitió al pueblo las palabras de Yahveh. Luego reunió a setenta ancianos del pueblo y los puso alrededor de la Tienda.

[[numbers-11-25]]
^25^ Bajó Yahveh en la Nube y le habló. Luego tomó algo del espíritu que había en él y se lo dio a los sententa ancianos. Y en cuanto reposó sobre ellos el espíritu, se pusieron a profetizar, pero ya no volvieron a hacerlo más.

[[numbers-11-26]]
^26^ Habían quedado en el campamento dos hombres, uno llamado Eldad y el otro Medad. Reposó también sobre ellos el espíritu, pues aunque no habían salido a la Tienda, eran de los designados. Y profetizaban en el campamento.

[[numbers-11-27]]
^27^ Un muchacho corrió a anunciar a Moisés: «Eldad y Medad están profetizando en el campamento».

[[numbers-11-28]]
^28^ Josué, hijo de Nun, que estaba al servicio de Moisés desde su mocedad, respondió y dijo: «Mi señor Moisés, prohíbeselo».

[[numbers-11-29]]
^29^ Le respondió Moisés: «¿Es que estás tú celoso por mí? ¡Quién me diera que todo el pueblo de Yahveh profetizara porque Yahveh les daba su espíritu!»

[[numbers-11-30]]
^30^ Luego Moisés volvió al campamento con los ancianos de Israel.

[[numbers-11-31]]
^31^ Se alzó un viento, enviado por Yahveh, que hizo pasar codornices del lado del mar, y las extendió sobre el campamento, en una extensión de una jornada de camino a uno y otro lado alrededor del campamento, y a una altura de dos codos por encima del suelo.

[[numbers-11-32]]
^32^ El puebblo se dedicó todo aquel día y toda la noche y todo el día siguiente a capturar las codornices. El que menos, reunió diez modios, y las tendieron alrededor del campamento.

[[numbers-11-33]]
^33^ Y todavía tenían la carne entre los dientes, todavía la estaban masticando, cuando se encendió la ira de Yahveh contra el pueblo, y lo hirió Yahveh con una plaga muy grande.

[[numbers-11-34]]
^34^ Se llamó a aquel lugar Quibrot Hattaavá, porque allí sepultaron a la muchedumbre de glotones.

[[numbers-11-35]]
^35^ De Quibrot Hattaavá partió el pueblo hacia Jaserot, y acamparon en Jaserot.
[[numbers-12]]
== Capítulo 12

[[numbers-12-1]]
^1^ María y Aarón murmuraron contra Moisés por causa de la mujer kusita que había tomado por esposa: por haberse casado con una kusita.

[[numbers-12-2]]
^2^ Decían: «¿Es que Yahveh no ha hablado más que con Moisés? ¿No ha hablado también con nosotros?» Y Yahveh lo oyó.

[[numbers-12-3]]
^3^ Moisés era un hombre muy humilde, más que hombre alguno sobre la haz de la tierra.

[[numbers-12-4]]
^4^ De improviso, Yahveh dijo a Moisés, a Aarón y a María: «Salid los tres a la Tienda del Encuentro». Y salieron los tres.

[[numbers-12-5]]
^5^ Bajó Yahveh en la columna de Nube y se quedó a la puerta de la Tienda. Llamó a Aarón y a María y se adelantaron los dos.

[[numbers-12-6]]
^6^ Dijo Yahveh: «Escuchad mis palabras: Si hay entre vosotros un profeta, en visión me revelo a él, y hablo con él en sueños.

[[numbers-12-7]]
^7^ No así con mi siervo Moisés: él es de toda confianza en mi casa;

[[numbers-12-8]]
^8^ boca a boca hablo con él, abiertamente y no enigmas, y contempla la imagen de Yahveh. ¿Por qué, pues, habéis osado hablar contra mi siervo Moisés?»

[[numbers-12-9]]
^9^ Y se encendió la ira de Yahveh contra ellos. Cuando se marchó,

[[numbers-12-10]]
^10^ y la Nube se retiró de encima de la Tienda, he aquí que María estaba leprosa, blanca como la nieve. Aarón se volvió hacia María y vio que estaba leprosa.

[[numbers-12-11]]
^11^ Y dijo Aarón a Moisés: «Perdón, Señor mío, no cargues sobre nosotros el pecado que neciamente hemos cometido.

[[numbers-12-12]]
^12^ Por favor, que no sea ella como quien nace muerto del seno de su madre, con la carne medio consumida».

[[numbers-12-13]]
^13^ Moisés clamó a Yahveh diciendo: «Oh Dios, cúrala, por favor».

[[numbers-12-14]]
^14^ Yahveh respondió a Moisés: «Si tu padre le hubiera escupido al rostro, ¿no tendría que pasar siete días de vergüenza? Que quede siete días fuera del campamento y luego sea admitida otra vez.

[[numbers-12-15]]
^15^ María quedó siete días excluida del campamento. Pero el pueblo no partió hasta que ella se reintegró.

[[numbers-12-16]]
^16^ Después el pueblo partió de Jaserot y acamparon en el desierto de Parán.
[[numbers-13]]
== Capítulo 13

[[numbers-13-1]]
^1^ Yahveh habló a Moisés y le dijo:

[[numbers-13-2]]
^2^ «Envía algunos hombres, uno por cada tribu paterna, para que exploren la tierra de Canaán que voy a dar a los israelitas. Que sean todos principales entre ellos».

[[numbers-13-3]]
^3^ Los envió Moisés, según la orden de Yahveh, desde el desierto de Parán: todos ellos eran jefes de los israelitas.

[[numbers-13-4]]
^4^ Sus nombres eran éstos: por la tribu de Rubén, Sammúa, hijo de Zakkur;

[[numbers-13-5]]
^5^ por la tribu de Simeón, Safat, hijo de de Jorí;

[[numbers-13-6]]
^6^ por la tribu de Judá, Caleb, hijo de Yefunné;

[[numbers-13-7]]
^7^ por la tribu de Isacar, Yigal, hijo de José;

[[numbers-13-8]]
^8^ por la tribu de Efraím, Hosea, hijo de Nun;

[[numbers-13-9]]
^9^ por la tribu de Benjamín, Paltí, hijo de Rafú;

[[numbers-13-10]]
^10^ por la tribu de Zabulón, Gaddiel, hijo de Sodí;

[[numbers-13-11]]
^11^ por la tribu de José: por la tribu de Manasés, Gaddí, hijo de Susí;

[[numbers-13-12]]
^12^ por la tribu de Dan, Ammiel, hijo de Guemalí;

[[numbers-13-13]]
^13^ por la tribu de Aser, Setur, hijo de Miguel;

[[numbers-13-14]]
^14^ por la tribu de Neftalí, Najbí, hijo de Vafsí;

[[numbers-13-15]]
^15^ por la tribu de Gad, Gueuel, hijo de Makí.

[[numbers-13-16]]
^16^ Esos son los nombres de los que envió Moisés a explorar el país. Pero a Hosea, hijo de Nun, Moisés le llamo Josué.

[[numbers-13-17]]
^17^ Moisés los envió a explorar el país de Canaán, y les dijo: «Subid ahí al Négueb y después subiréis a la montaña.

[[numbers-13-18]]
^18^ Reconoced el país, a ver qué tal es, y el pueblo que lo habita, si es fuerte o débil, escaso o numeroso;

[[numbers-13-19]]
^19^ y qué tal es el país en que viven, bueno o malo; cómo son las ciudades en que habitan, abiertas o fortificadas;

[[numbers-13-20]]
^20^ y cómo es la tierra, fértil o pobre, si tiene árboles o no. Tened valor y traed algunos productos del país». Era el tiempo de las primeras uvas.

[[numbers-13-21]]
^21^ Subieron y exploraron el país, desde el desierto de Sin hasta Rejob, a la Entrada de Jamat.

[[numbers-13-22]]
^22^ Subieron por el Négueb y llegaron hasta Hebrón, donde residían Ajimán, Sesay y Talmay, los descendientes de Anaq. Hebrón había sido fundada siete años antes que Tanis de Egipto.

[[numbers-13-23]]
^23^ Llegaron al Valle de Eskol y cortaron allí un sarmiento con un racimo de uva, que transportaron con una pértiga entre dos, y también granadas e higos.

[[numbers-13-24]]
^24^ Al lugar aquél se le llamó Valle de Eskol, por el racimo que cortaron allí los israelitas.

[[numbers-13-25]]
^25^ Al cabo de cuarenta días volvieron de explorar la tierra.

[[numbers-13-26]]
^26^ Fueron y se presentaron a Moisés, a Aarón y a toda la comunidad de los israelitas, en el desierto de Parán, en Cadés. Les hicieron una relación a ellos y a toda la comunidad, y les mostraron los productos del país.

[[numbers-13-27]]
^27^ Les contaron lo siguiente: «Fuimos al país al que nos enviaste, y en verdad que mana leche y miel; éstos son sus productos.

[[numbers-13-28]]
^28^ Sólo que el pueblo que habita en el país es poderoso; las ciudades, fortificadas y muy grandes; hasta hemos visto allí descendientes de Anaq.

[[numbers-13-29]]
^29^ El amalecita ocupa la región del Négueb; el hitita, el amorreo y el jebuseo ocupan la montaña; el cananeo, la orilla del mar y la ribera del Jordán».

[[numbers-13-30]]
^30^ Caleb acalló al pueblo delante de Moisés, diciendo: «Subamos, y conquistaremos el país, porque sin duda podremos con él».

[[numbers-13-31]]
^31^ Pero los hombres que habían ido con él dijeron: «No podemos subir contra ese pueblo, porque es más fuerte que nosotros».

[[numbers-13-32]]
^32^ Y empezaron a hablar mal a los israelitas del país que habían explorado, diciendo: «El país que hemos recorrido y explorado es un país que devora a sus propios habitantes. Toda la gente que hemos visto allí es gente alta.

[[numbers-13-33]]
^33^ Hemos visto también gigantes, hijos de Anaq, de la raza de los gigantes. Nosotros nos teníamos ante ellos como saltamontes, y eso mismo les parecíamos a ellos».
[[numbers-14]]
== Capítulo 14

[[numbers-14-1]]
^1^ Entonces toda la comunidad alzó la voz y se puso a gritar; y la gente estuvo llorando aquella noche.

[[numbers-14-2]]
^2^ Luego murmuraron todos los israelitas contra Moisés y Aarón, y les dijo toda la comunidad: «¡Ojalá hubiéramos muerto en Egipto! Y si no, ¡ojalá hubiéramos muerto en el desierto!

[[numbers-14-3]]
^3^ ¿Por qué Yahveh nos trae a este país para hacernos caer a filo de espada y que nuestras mujeres y niños caigan en cautiverio? ¿No es mejor que volvamos a Egipto?»

[[numbers-14-4]]
^4^ Y se decían unos a otros: «Nombremos a uno jefe y volvamos a Egipto».

[[numbers-14-5]]
^5^ Moisés y Aarón cayeron rostro en tierra delante de toda la asamblea de la comunidad de los israelitas.

[[numbers-14-6]]
^6^ Pero Josué, hijo de Nun, y Caleb, hijo de Yefunné, que eran de los que habían explorado el país, rasgaron sus vestiduras

[[numbers-14-7]]
^7^ y dijeron a toda la comunidad de los israelitas: «La tierra que hemos recorrido y explorado es muy buena tierra.

[[numbers-14-8]]
^8^ Si Yahveh nos es favorable, nos llevará a esa tierra y nos la entregará. Es una tierra que mana leche y miel.

[[numbers-14-9]]
^9^ No os rebeléis contra Yahveh, ni temáis a la gente del país, porque son pan comido. Se ha retirado de ellos su sombra, y en cambio Yahveh está con nosotros. No tengáis miedo».

[[numbers-14-10]]
^10^ Toda la comunidad hablaba de apedrearlos, cuando la gloria de Yahveh se apareció en la Tienda del Encuentro, a todos los israelitas.

[[numbers-14-11]]
^11^ Y dijo Yahveh a Moisés: «¿Hasta cuándo me va a despreciar este pueblo? ¿Hasta cuándo van a desconfiar de mí, con todas las señales que he hecho entre ellos?

[[numbers-14-12]]
^12^ Los heriré de peste y los desheredaré. Pero a ti te convertiré en un pueblo más grande y poderoso que ellos».

[[numbers-14-13]]
^13^ Moisés respondió a Yahveh: «Pero los egipcios saben muy bien que, con tu poder, sacaste a este pueblo de en medio de ellos.

[[numbers-14-14]]
^14^ Se lo han contado a los habitantes de este país. Estos se han enterado de que tú, Yahveh, estás en medio de este pueblo, y te das a ver cara a cara; de que tú, Yahveh, permaneces en tu Nube sobre ellos, y caminas delante de ellos de día en la columna de Nube, y por la noche en la columna de fuego.

[[numbers-14-15]]
^15^ Si haces perecer a este pueblo como un solo hombre, dirán los pueblos que han oído hablar de ti:

[[numbers-14-16]]
^16^ Yahveh, como no ha podido introducir a ese pueblo en la tierra que les había prometido con juramento, los ha matado en el desierto.”

[[numbers-14-17]]
^17^ Muestra, pues, ahora tu poder, mi Señor, como prometiste diciendo:

[[numbers-14-18]]
^18^ Yahveh es tardo a la cólera y rico en bondad, tolera iniquidad y rebeldía; aunque nada deja sin castigo, castigando la iniquidad de los padres en los hijos hasta la tercera y cuarta generación.”

[[numbers-14-19]]
^19^ Perdona, pues, la iniquidad de este pueblo conforme a la grandeza de tu bondad, como has soportado a este pueblo desde Egipto hasta aquí».

[[numbers-14-20]]
^20^ Dijo Yahveh: «Le perdono, según tus palabras.

[[numbers-14-21]]
^21^ Pero, vivo yo y la gloria de Yahveh llena toda la tierra,

[[numbers-14-22]]
^22^ que ninguno de los que han visto mi gloria y las señales que he realizado en Egipto y en el desierto, que me han puesto a prueba ya diez veces y no han escuchado mi voz,

[[numbers-14-23]]
^23^ verá la tierra que prometí con juramento a sus padres. No la verá ninguno de los que me han despreciado.

[[numbers-14-24]]
^24^ Pero a mi siervo Caleb, ya que fue animado de otro espíritu y me obedeció puntualmente, le haré entrar en la tierra donde estuvo, y su descendencia la poseerá.

[[numbers-14-25]]
^25^ El amalecita y el cananeo habitan en el llano. Mañana, volveos y partid para el desierto, camino del mar de Suf».

[[numbers-14-26]]
^26^ Yahveh habló a Moisés y Aarón y dijo:

[[numbers-14-27]]
^27^ «¿Hasta cuándo esta comunidad perversa, que está murmurando contra mí? He oído las quejas de los israelitas, que están murmurando contra mí.

[[numbers-14-28]]
^28^ Diles: Por mi vida - oráculo de Yahveh - que he de hacer con vosotros lo que habéis hablado a mis oídos.

[[numbers-14-29]]
^29^ Por haber murmurado contra mí, en este desierto caerán vuestros cadáveres, los de todos los que fuisteis revistados y contados, de veinte años para arriba.

[[numbers-14-30]]
^30^ Os juro que no entraréis en la tierra en la que, mano en alto, juré estableceros. Sólo a Caleb, hijo de Yefunné y a Josué, hijo de Nun,

[[numbers-14-31]]
^31^ y a vuestros pequeñuelos, de los que dijisteis que caerían en cautiverio, los introduciré, y conocerán la tierra que vosotros habéis despreciado.

[[numbers-14-32]]
^32^ Vuestros cadáveres caerán en este desierto,

[[numbers-14-33]]
^33^ y vuestros hijos serán nómadas cuarenta años en el desierto, cargando con vuestra infidelidad, hasta que no falte uno solo de vuestros cadáveres en el desierto.

[[numbers-14-34]]
^34^ Según el número de los días que empleasteis en explorar el país, cuarenta días, cargaréis cuarenta años con vuestros pecados, un año por cada día. Así sabréis lo que es apartarse de mí.

[[numbers-14-35]]
^35^ Yo, Yahveh, he hablado. Eso es lo que haré con toda esta comunidad perversa, amotinada contra mí. En este desierto no quedará uno: en él han de morir».

[[numbers-14-36]]
^36^ Los hombres que había enviado Moisés a explorar la tierra, que al volver habían incitado a toda la comunidad a murmurar contra él, poniéndose a hablar mal del país,

[[numbers-14-37]]
^37^ aquellos hombres que habían hablado mal del país, cayeron muertos delante de Yahveh.

[[numbers-14-38]]
^38^ En cambio, Josué, hijo de Nun, y Caleb, hijo de Yefunné, sobrevivieron de entre los hombres que habían ido a explorar la tierra.

[[numbers-14-39]]
^39^ Refirió Moisés estas palabras a todos los israelitas y se afligió mucho el pueblo.

[[numbers-14-40]]
^40^ Madrugaron y subieron a la cumbre del monte, diciendo: «Vamos a subir a ese lugar respecto del cual ha dicho Yahveh que hemos pecado».

[[numbers-14-41]]
^41^ Moisés les respondió: «¿Por qué hacéis eso, pasando por encima de la orden de Yahveh? Eso no tendrá buen éxito.

[[numbers-14-42]]
^42^ No subáis, porque Yahveh no está en medio de vosotros, no vayáis a ser derrotados frente a vuestros enemigos.

[[numbers-14-43]]
^43^ Porque el amalecita y el cananeo están allí contra vosotros, y caeréis a filo de espada, pues después de haber abandonado vosotros a Yahveh, Yahveh no está con vosotros».

[[numbers-14-44]]
^44^ Pero ellos se obstinaron en subir a la cumbre del monte. Ni el arca de la alianza de Yahveh, ni Moisés se movieron del campamento.

[[numbers-14-45]]
^45^ Bajaron los amalecitas y los cananeos que habitaban en aquella montaña, los batieron y los destrozaron hasta llegar a Jormá.
[[numbers-15]]
== Capítulo 15

[[numbers-15-1]]
^1^ Habló Yahveh a Moisés y le dijo:

[[numbers-15-2]]
^2^ «Habla a los israelitas y diles: Cuando entréis en la tierra que yo os daré por morada,

[[numbers-15-3]]
^3^ y ofrezcáis manjares abrasados a Yahveh en holocausto o sacrificio, para cumplir un voto, o como ofrenda voluntaria o con acasión de vuestras fiestas, ofreciendo así, de vuestros bueyes u ovejas, calmante aroma para Yahveh,

[[numbers-15-4]]
^4^ el oferente presentará, para su ofrenda a Yahveh, una oblación de una décima de flor de harina amasada con un cuarto de sextario de aceite.

[[numbers-15-5]]
^5^ Harás una libación de un cuarto de sextario de vino por cada cordero, además del holocausto o sacrificio.

[[numbers-15-6]]
^6^ Si es un carnero, la oblación será de dos décimas de flor de harina amasada con un tercio de sextario de aceite,

[[numbers-15-7]]
^7^ y la libación, de un tercio de sextario de vino, que ofrecerás como calmante aroma para Yahveh.

[[numbers-15-8]]
^8^ Y si ofreces a Yahveh un novillo en holocausto o sacrificio, para cumplir un voto, o como sacrificio de comunión,

[[numbers-15-9]]
^9^ se ofrecerá además del novillo una oblación de tres décimas de flor de harina amasada con medio sextario de aceite,

[[numbers-15-10]]
^10^ y una libación de medio sextario de vino, como manjar abrasado de calmante aroma para Yahveh.

[[numbers-15-11]]
^11^ Así se hará con nada novillo y con las reses menores, cordero o cabrito.

[[numbers-15-12]]
^12^ Haréis así con cada uno de los que inmoléis, con tantos como hubiere.

[[numbers-15-13]]
^13^ Así hará todo hombre de vuestro pueblo, cuando ofrezca un manjar abrasado como calmante aroma para Yahveh.

[[numbers-15-14]]
^14^ Si reside entre vosotros o entre vuestros descendientes un forastero, y ofrece un manjar abrasado como calmante aroma para Yahveh, lo mismo que vosotros hará

[[numbers-15-15]]
^15^ la asamblea. No habrá más que una norma para vosotros y para el forastero residente. Es decreto perpetuo para vuestros descendientes: igual será delante de Yahveh para vosotros que para el forastero.

[[numbers-15-16]]
^16^ Una sola ley y una sola norma regirá para vosotros y para el forastero que reside entre vosotros».

[[numbers-15-17]]
^17^ Yahveh habló así a Moisés:

[[numbers-15-18]]
^18^ «Habla a los israelitas y diles: Cuando entréis en la tierra a la que os voy a llevar,

[[numbers-15-19]]
^19^ y comáis el pan del país, reservaréis primero la ofrenda para Yahveh.

[[numbers-15-20]]
^20^ Como primicias de vuestra molienda reservaréis como ofrenda una torta; la reservaréis igual que se hace en la era.

[[numbers-15-21]]
^21^ Reservaréis a Yahveh una ofrenda de las primicias de vuestra molienda, por todas vuestras generaciones.

[[numbers-15-22]]
^22^ «Cuando por inadvertencia no cumpláis alguno de estos preceptos que Yahveh ha comunicado a Moisés,

[[numbers-15-23]]
^23^ algo de lo que os ha mandado Yahveh por medio de Moisés, desde que Yahveh lo ordenó en adelante, por todas vuestras generaciones,

[[numbers-15-24]]
^24^ en el caso de que la inadvertencia se haya cometido por descuido de la comunidad, toda la comunidad ofrecerá un novillo en holocausto, como calmante aroma para Yahveh, con su correspondiente oblación y libación según costumbre, y un macho cabrío en sacrificio por el pecado.

[[numbers-15-25]]
^25^ El sacerdote expiará por toda la comunidad de los israelitas, y se les perdonará, porque ha sido un descuido. Cuando presenten sus ofrendas, como manjar abrasado a Yahveh, y su sacrificio por el pecado delante de Yahveh por su descuido,

[[numbers-15-26]]
^26^ se le perdonará a la comunidad de los israelitas y al forastero que reside entre ellos, pues el pueblo entero lo ha hecho por inadvertencia.

[[numbers-15-27]]
^27^ En el caso de que una sola persona haya pecado por inadvertencia, ofrecerá en sacrificio por el pecado una cabrita de un año.

[[numbers-15-28]]
^28^ El sacerdote expiará delante de Yahveh por la persona que se ha descuidado con ese pecado de inadvertencia; cuando se haga expiación por ella, se le perdonará,

[[numbers-15-29]]
^29^ lo mismo al ciudadano israelita que al forastero residente entre vosotros: no tendréis más que una sola ley para el que obra por inadvertencia.

[[numbers-15-30]]
^30^ Pero el que obra con descaro, sea ciudadano o forastero, ultraja a Yahveh. Tal individuo será extirpado de su pueblo,

[[numbers-15-31]]
^31^ por haber despreciado la palabra de Yahveh, quebrantado su mandato. Será exterminado tal individuo: su pecado pesa sobre él».

[[numbers-15-32]]
^32^ Cuando los israelitas estaban en el desierto, se encontró a un hombre que andaba buscando leña en día de sábado.

[[numbers-15-33]]
^33^ Los que lo encontraron buscando leña, lo presentaron a Moisés, a Aarón y a toda la comunidad.

[[numbers-15-34]]
^34^ Le pusieron bajo custodia, porque no estaba determinado lo que había que hacer con él.

[[numbers-15-35]]
^35^ Yahveh dijo a Moisés: «Que muera ese hombre. Que lo apedree toda la comunidad fuera del campamento».

[[numbers-15-36]]
^36^ Lo sacó toda la comunidad fuera del campamento y lo apedrearon hasta que murió, según había mandado Yahveh a Moisés.

[[numbers-15-37]]
^37^ Yahveh dijo a Moisés:

[[numbers-15-38]]
^38^ «Habla a los israelitas y diles que ellos y sus descendientes se hagan flecos en los bordes de sus vestidos, y pongan en el fleco de sus vestidos un hilo de púrpura violeta.

[[numbers-15-39]]
^39^ Tendréis, pues flecos para que, cuando los veáis, os acordéis de todos los preceptos de Yahveh. Así los cumpliréis y no seguiréis los caprichos de vuestros corazones y de vuestros ojos, que os han arrastrado a prostituiros.

[[numbers-15-40]]
^40^ Así os acordaréis de todos mis mandamientos y los cumpliréis, y seréis hombres consagrados a vuestro Dios.

[[numbers-15-41]]
^41^ Yo, Yahveh, vuestro Dios, que os saqué de Egipto para ser Dios vuestro. Yo, Yahveh, vuestro Dios.
[[numbers-16]]
== Capítulo 16

[[numbers-16-1]]
^1^ Coré, hijo de Yishar, hijo de Quehat, hijo de Leví, Datán y Abirón, hijos de Eliab, y On, hijo de Pélet, hijos de Rubén, se enorgullecieron,

[[numbers-16-2]]
^2^ y se alzaron contra Moisés junto con 250 israelitas, principales de la comunidad, distinguidos en la asamblea, personajes famosos.

[[numbers-16-3]]
^3^ Se amotinaron contra Moisés y Aarón y les dijeron: «Esto ya pasa de la raya. Toda la comunidad entera, todos ellos están consagrados y Yahveh está en medio de ellos. ¿Por qué, pues, os encumbráis por encima de la asamblea de Yahveh?»

[[numbers-16-4]]
^4^ Lo oyó Moisés y cayó rostro en tierra.

[[numbers-16-5]]
^5^ Dijo luego a Coré y a toda su cuadrilla: «Mañana por la mañana hará saber Yahveh quién es el suyo, quién es el consagrado y le dejará acercarse. Al que Yahveh haya elegido le dejará acercarse.

[[numbers-16-6]]
^6^ Mirad, pues, lo que habéis de hacer: Tomad los incensarios de Coré y de toda su cuadrilla,

[[numbers-16-7]]
^7^ ponedles fuego y mañana les echaréis incienso ante Yahveh. Aquel a quien elija Yahveh, será el consagrado; ¡esto ya pasa de la raya, hijos de Leví!»

[[numbers-16-8]]
^8^ Dijo Moisés a Coré: «Oídme, hijos de Leví.

[[numbers-16-9]]
^9^ ¿Os parece poco que el Dios de Israel os haya apartado de la comunidad de Israel para ponerlos junto a sí, prestar el servicio a la Morada de Yahveh y estar al frente de la comunidad atendiendo al culto en lugar de ella?

[[numbers-16-10]]
^10^ Te ha puesto junto a sí, a ti y a todos tus hermanos, los hijos de Leví, y ¡todavía se os ha antojado el sacerdocio!

[[numbers-16-11]]
^11^ Por eso, contra Yahveh os habéis amotinado, tú y toda tu cuadrilla; porque ¿quién es Aarón, para que murmuréis contra él?»

[[numbers-16-12]]
^12^ Mandó Moisés llamar a Datán y Abirón, hijos de Eliab. Pero ellos respondieron: «No queremos ir.

[[numbers-16-13]]
^13^ ¿Te parece poco habernos sacado de una tierra que mana leche y miel para hacernos morir en el desierto, que todavía te eriges como príncipe sobre nosotros?

[[numbers-16-14]]
^14^ No nos has traído a ningún país que mana leche y miel, ni nos has dado una herencia de campos y vergeles. ¿Pretendes cegar los ojos de estos hombres? ¡No iremos!»

[[numbers-16-15]]
^15^ Moisés se enojó mucho y dijo a Yahveh: «No mires a su oblación. Yo no les he quitado ni un solo asno, ni le he hecho mal a ninguno de ellos».

[[numbers-16-16]]
^16^ Dijo Moisés a Coré: «Tú y toda tu cuadrilla presentaos mañana delante de Yahveh: tú, ellos y Aarón.

[[numbers-16-17]]
^17^ Que tome cada uno su incensario, le ponga incienso y lo presente delante de Yahveh; cada uno su incensario: 250 incensarios en total. Tú también, y Aarón, presentad cada uno vuestro incensario».

[[numbers-16-18]]
^18^ Tomaron cada uno su incensario, le pusieron fuego, le echaron incienso y se presentaron a la entrada de la Tienda del Encuentro, lo mismo que Moisés y Aarón.

[[numbers-16-19]]
^19^ Coré convocó ante éstos a toda la comunidad a la puerta de la Tienda del Encuentro y se apareció la gloria de Yahveh a toda la comunidad.

[[numbers-16-20]]
^20^ Habló Yahveh a Moisés y Aarón y les dijo:

[[numbers-16-21]]
^21^ «Apartaos de esa comunidad, que los voy a devorar en un instante».

[[numbers-16-22]]
^22^ Ellos cayeron rostro en tierra y clamaron: «Oh Dios, Dios de los espíritus de toda carne: un solo hombre ha pecado, ¿y te enojas con toda la comunidad?»

[[numbers-16-23]]
^23^ Respondió Yahveh a Moisés:

[[numbers-16-24]]
^24^ «Habla a esa comunidad y diles: Alejaos de los alrededores de la morada de Coré».

[[numbers-16-25]]
^25^ Se levantó Moisés y fue donde Datán y Abirón; los ancianos de Israel le siguieron.

[[numbers-16-26]]
^26^ Y habló a la comunidad diciendo: «Apartaos, por favor, de las tiendas de estos hombres malvados, y no toquéis nada de cuanto les pertenece, no sea que perezcáis por todos sus pecados».

[[numbers-16-27]]
^27^ Ellos se apartaron de los alrededores de la morada de Coré. Datán y Abirón habían salido y estaban a la puerta de sus tiendas, con sus mujeres, hijos y pequeñuelos.

[[numbers-16-28]]
^28^ Moisés dijo: «En esto conoceréis que Yahveh me ha enviado para hacer todas estas obras, y que no es ocurrencia mía:

[[numbers-16-29]]
^29^ si mueren estos hombres como muere cualquier mortal, alcanzados por la sentencia común a todo hombre, es que Yahveh no me ha enviado.

[[numbers-16-30]]
^30^ Pero si Yahveh obra algo portentoso, si la tierra abre su boca y los traga con todo lo que les pertenece, y bajan vivos al seol, sabréis que esos hombres han rechazado a Yahveh.

[[numbers-16-31]]
^31^ Y sucedió que, nada más terminar de decir estas palabras, se abrió el suelo debajo de ellos;

[[numbers-16-32]]
^32^ la tierra abrió su boca y se los tragó, con todas sus familias, así como a todos los hombres de Coré, con todos sus bienes.

[[numbers-16-33]]
^33^ Bajaron vivos al seol con todo lo que tenían. Los cubrió la tierra y desaparecieron de la asamblea.

[[numbers-16-34]]
^34^ A sus gritos huyeron todos los israelitas que estaban a su alrededor, pues se decían: «No vaya a tragarnos la tierra».

[[numbers-16-35]]
^35^ Brotó fuego de Yahveh, que devoró a los 250 hombres que habían ofrecido el incienso.
[[numbers-17]]
== Capítulo 17

[[numbers-17-1]]
^1^ Habló Yahveh a Moisés y le dijo:

[[numbers-17-2]]
^2^ «Di a Eleazar, hijo del sacerdote Aarón, que saque los incensarios de entre las cenizas y esparza el fuego a distancia,

[[numbers-17-3]]
^3^ porque esos incensarios de pecado están consagrados a precio de la vida de esos hombres. Haced con ellos láminas de metal, para cubrir el altar, pues fueron presentados a Yahveh y consagrados. Serán una señal para los israelitas».

[[numbers-17-4]]
^4^ Tomó el sacerdote Eleazar los incensarios de bronce que habían presentado los que fueron abrasados, y los laminó con destino al altar.

[[numbers-17-5]]
^5^ Sirven para recordar a los israelitas que no se acerque ningún laico, que no sea de la descendencia de Aarón, a ofrecer el incienso delante de Yahveh; no le ocurra lo que a Coré y a su cuadrilla, según se lo había dicho Yahveh por medio de Moisés.

[[numbers-17-6]]
^6^ Al día siguiente, murmuró toda la comunidad de los israelitas contra Moisés y Aarón, diciendo: «Vosotros habéis matado al pueblo de Yahveh».

[[numbers-17-7]]
^7^ Como se amotinaba la comunidad contra Moisés y Aarón, se volvieron éstos hacia la Tienda del Encuentro. Y vieron que la Nube la había cubierto y se había aparecido la gloria de Yahveh.

[[numbers-17-8]]
^8^ Moisés y Aarón se llegaron hasta delante de la Tienda del Encuentro.

[[numbers-17-9]]
^9^ Yahveh habló a Moisés y le dijo:

[[numbers-17-10]]
^10^ «Alejaos de esa comunidad, que voy a consumirlos en un instante». Ellos cayeron rostro en tierra.

[[numbers-17-11]]
^11^ Dijo entonces Moisés a Aarón: «Toma el incensario, ponle fuego del que hay sobre el altar, echa incienso y vete rápidamente donde la comunidad a expiar por ellos. Porque ha salido ya la Cólera de la presencia de Yahveh y ha comenzado la Plaga».

[[numbers-17-12]]
^12^ Aarón lo tomó como le había dicho Moisés y corrió a ponerse en medio de la asamblea; la Plaga había comenzado ya en el pueblo. Echó el incienso e hizo la expiación por el pueblo.

[[numbers-17-13]]
^13^ Se plantó entre los muertos y los vivos, y la Plaga se detuvo.

[[numbers-17-14]]
^14^ Los muertos por aquella plaga fueron 14.700, sin contar los que murieron por causa de Coré.

[[numbers-17-15]]
^15^ Luego Aarón se volvió donde Moisés a la puerta de la Tienda del Encuentro: había cesado ya la Plaga.

[[numbers-17-16]]
^16^ Habló Yahveh a Moisés y le dijo:

[[numbers-17-17]]
^17^ «Habla a los israelitas. Que te den una rama por cada familia paterna: que entre todos los principales, en representación de sus familias paternas, de den doce ramas. Y escribe el nombre de cada uno en su rama.

[[numbers-17-18]]
^18^ En la rama de Leví escribe el nombre de Aarón, pues ha de haber también una rama para el jefe de la familia de Leví.

[[numbers-17-19]]
^19^ Las depositarás en la Tienda del Encuentro, delante del Testimonio, donde me suelo manifestar a ti.

[[numbers-17-20]]
^20^ El hombre cuya rama retoñe, será el que yo elijo. Así dejarán de llegar hasta mí las murmuraciones que los israelitas profieren contra vosotros».

[[numbers-17-21]]
^21^ Moisés habló a los israelitas, y cada uno de los principales le dio una rama, doce ramas, en representación de todas las familias paternas. Entre sus ramas estaba también la rama de Aarón.

[[numbers-17-22]]
^22^ Moisés depositó las ramas delante de Yahveh en la Tienda del Testimonio.

[[numbers-17-23]]
^23^ Al día siguiente, cuando entró Moisés en la Tienda del Testimonio, vio que había retoñado la rama de Aarón, por la casa de Leví: le habían brotado yemas, había florecido y había producido almrendras.

[[numbers-17-24]]
^24^ Moisés sacó todas las ramas de la presencia de Yahveh, ante los israelitas; las vieron, y tomarón cada uno su rama.

[[numbers-17-25]]
^25^ Entonces dijo Yahveh a Moisés: «Vuelve a poner la rama de Aarón delante del Testimonio, para guardarla como señal para los rebeldes: acabará con las murmuraciones, que no llegarán ya hasta mí, y así no morirán».

[[numbers-17-26]]
^26^ Moisés lo hizo así; como le había mandado Yahveh lo hizo.

[[numbers-17-27]]
^27^ Dijeron los israelitas a Moisés: «¡Estamos perdidos! ¡Hemos perecido! ¡Todos hemos perecido!

[[numbers-17-28]]
^28^ Cualquiera que se acerca a la Morada de Yahveh, muere. ¿Es que vamos a perecer hasta no quedar uno?»
[[numbers-18]]
== Capítulo 18

[[numbers-18-1]]
^1^ Entonces Yahveh dijo a Aarón: «Tú, tus hijos y la casa de tu padre contigo, cargaréis con las faltas cometidas contra el santuario. Tú y tus hijos cargaréis con las faltas de vuestro sacerdocio.

[[numbers-18-2]]
^2^ Haz que se acerquen también contigo tus hermanos de la rama de Leví, de la tribu de tu padre. Que sean tus ayudantes y te sirvan a ti y a tus hijos, delante de la Tienda del Testimonio.

[[numbers-18-3]]
^3^ Atenderán a tu ministerio y al de toda la Tienda. Pero que no se acerquen ni a los objetos sagrados ni al altar, para que no muráis ni ellos ni vosotros.

[[numbers-18-4]]
^4^ Serán tus ayudantes, desempeñarán el ministerio en la Tienda, y ningún laico se acercará a vosotros.

[[numbers-18-5]]
^5^ Vosotros desempeñaréis el ministerio en el santuario y en el altar, y así no vendrá de nuevo la Cólera sobre los israelitas.

[[numbers-18-6]]
^6^ Yo he elegido a vuestros hermanos los levitas, de entre los demás israelitas. Son un don que os hago; son «donados» a Yahveh para prestar servicio en la Tienda del Encuentro.

[[numbers-18-7]]
^7^ Pero tú y tus hijos os ocuparéis de vuestro sacerdocio en todo lo referente al altar y a todo lo de detrás del velo y prestaréis vuestro servicio. Como un servicio gratuito os doy vuestro sacerdocio. El laico que se acerque morirá».

[[numbers-18-8]]
^8^ Dijo Yahveh a Aarón: «Yo te doy el servicio de lo que se reserva para mí. Todo lo consagrado por los israelitas te lo doy a tí y a tus hijos, como porción tuya, por decreto perpetuo.

[[numbers-18-9]]
^9^ Esto es lo que será tuyo de las cosas sacratísimas, del manjar que se abrasa: todas las ofrendas que me restituyan los israelitas, como oblación, como sacrificio por el pecado, o como sacrificio de reparación, son sacratísimas: serán para ti y para tus hijos.

[[numbers-18-10]]
^10^ De las cosas sacratísimas os alimentaréis. Todo varón lo podrá comer. Lo considerarás como sagrado.

[[numbers-18-11]]
^11^ También te pertenecerá la ofrenda reservada de todo lo que los israelitas den a mecer; te lo doy a ti y a tus hijos y a tus hijas por decreto perpetuo. Cualquiera que esté puro en tu casa lo podrá comer.

[[numbers-18-12]]
^12^ Todo lo mejor del aceite y la flor del mosto y del trigo, las primicias que ofrezcan a Yahveh, te las doy a ti.

[[numbers-18-13]]
^13^ Los primeros productos que lleven a Yahveh, de todo lo que produzca su tierra, serán para ti. Todo el que esté puro en tu casa lo podrá comer.

[[numbers-18-14]]
^14^ Cuanto caiga bajo el anatema en Israel, será para ti.

[[numbers-18-15]]
^15^ Todo primogénito que se presente a Yahveh de cualquier especie, hombre o animal, será para ti. Pero harás rescatar al primogénito del hombre y harás también rescatar al primogénito de animal impuro.

[[numbers-18-16]]
^16^ Los harás rescatar al mes de nacidos, valorándolos en cinco siclos de plata, en siclos del santuario, que son de veinte óbolos.

[[numbers-18-17]]
^17^ Pero al primogénito de vaca, o de oveja, o de cabra, no lo rescatarás: es sagrado. Derramarás su sangre sobre el altar y su grasa la harás arder como manjar abrasado de calmante aroma para Yahveh.

[[numbers-18-18]]
^18^ Su carne será para ti, así como el pecho del rito del mecimiento y la pierna derecha.

[[numbers-18-19]]
^19^ Todo lo reservado de las cosas sagradas que los israelitas reservan a Yahveh, te lo doy a ti y a tus hijos e hijas, por decreto perpetuo. Alianza de sal es ésta, para siempre, delante de Yahveh, para ti y tu descendencia».

[[numbers-18-20]]
^20^ Yahveh dijo a Aarón: «Tú no tendrás heredad ninguna en su tierra; no habrá porción para ti entre ellos. Yo soy tu porción para ti entre ellos. Yo soy tu porción y tu heredad entre los israelitas.

[[numbers-18-21]]
^21^ A los hijos de Leví, les doy en herencia todos los diezmos de Israel, a cambio de su servicio: del servicio que prestan en la Tienda del Encuentro.

[[numbers-18-22]]
^22^ Los israelitas no se volverán a acercar a la Tienda del Encuentro: cargarían con un pecado y morirían.

[[numbers-18-23]]
^23^ Será Leví el que preste servicio en la Tiendal del Encuentro: ellos cargarán con sus faltas. Es decreto perpetuo para vuestros descendientes: no tendrán heredad entre los israelitas,

[[numbers-18-24]]
^24^ porque yo les doy en herencia a los levitas los diezmos que los israelitas reservan para Yahveh. Por eso les he dicho que no tendrán heredad entre los israelitas».

[[numbers-18-25]]
^25^ Habló Yahveh a Moisés y le dijo:

[[numbers-18-26]]
^26^ «Hablarás a los levitas y les dirás: Cuando percibáis de los israelitas el diezmo que yo tomo de ellos y os doy en herencia, reservaréis de él la reserva de Yahveh: el diezmo del diezmo.

[[numbers-18-27]]
^27^ Equivaldrá a vuestra ofrenda reservada, lo mismo que el trigo tomado de la era y el mosto del lagar.

[[numbers-18-28]]
^28^ Así también vosotros reservaréis previamente la reserva de Yahveh de todos los diezmos que percibáis de los israelitas. Se lo daréis como ofrenda reservada de Yahveh al sacerdote Aarón.

[[numbers-18-29]]
^29^ De todos los dones que recibáis, reservaréis la reserva de Yahveh; separaréis la parte sagrada de todo lo mejor.

[[numbers-18-30]]
^30^ Les dirás: Una vez que hayáis reservado lo mejor, que equivale para los levitas al producto de la era y al producto del lagar,

[[numbers-18-31]]
^31^ lo podréis comer, en cualquier lugar, vosotros y vuestras familias: es vuestro salario por vuestro servicio en la Tienda del Encuentro.

[[numbers-18-32]]
^32^ No tendréis que cargar por ello con ningún pecado, pues antes habéis reservado lo mejor: así no profanaréis las cosas consagradas por los israelitas y no moriréis».
[[numbers-19]]
== Capítulo 19

[[numbers-19-1]]
^1^ Habló Yahveh a Moisés y a Aarón y les dijo:

[[numbers-19-2]]
^2^ «Este es uno de los preceptos legales, prescrito por Yahveh con estas palabras: Diles a los israelitas que te traigan una vaca roja, sin defecto, que no tenga manchas, y que no haya llevado yugo.

[[numbers-19-3]]
^3^ Dádsela al sacerdote Eleazar. Que la saquen fuera del campamento y sea inmolada en su presencia.

[[numbers-19-4]]
^4^ Entonces el sacerdote Eleazar untará su dedo en la sangre de la vaca y hará con la sangre siete aspersiones hacia la entrada de la Tienda del Encuentro.

[[numbers-19-5]]
^5^ Será quemada la vaca en su presencia, con su piel, su carne, su sangre e incluso sus excrementos.

[[numbers-19-6]]
^6^ Tomará el sacerdote leña de cedro, hisopo y grana, y la echará en medio de la hoguera de la vaca.

[[numbers-19-7]]
^7^ El sacerdote purificará sus vestidos y se lavará el cuerpo con agua; luego podrá ya entrar en el campamento; pero será impuro el sacerdote hasta la tarde.

[[numbers-19-8]]
^8^ El que haya quemado la vaca purificará sus vestidos con agua y lavará su cuerpo con agua; pero será impuro hasta la tarde.

[[numbers-19-9]]
^9^ Un hombre puro recogerá las cenizas de la vaca y las depositará fuera del campamento, en lugar puro. Servirán a la comunidad de los israelitas para el rito de hacer el agua lustral: es un sacrificio por el pecado.

[[numbers-19-10]]
^10^ El que haya recogido las cenizas de la vaca lavará sus vestidos y será impuro hasta la tarde. Este será decreto perpetuo tanto para los israelitas como para el forastero residente entre ellos.

[[numbers-19-11]]
^11^ El que toque a un muerto, cualquier cadáver humano, será impuro siete días.

[[numbers-19-12]]
^12^ Se purificará con aquellas aguas los días tercero y séptimo, y quedará puro. Pero si no se ha purificado los días tercero y séptimo, no quedará puro.

[[numbers-19-13]]
^13^ Todo el que toca un muerto, un cadáver humano, y no se purifica, mancha la Morada de Yahveh; ese individuo será extirpado de Israel, porque las aguas lustrales no han corrido sobre él: es impuro; su impureza sigue sobre él.

[[numbers-19-14]]
^14^ Esta es la ley para cuando uno muere en la tienda. Todo el que entre en la tienda, y todo el que esté en la tienda, será impuro siete días.

[[numbers-19-15]]
^15^ Y todo recipiente descubierto, que no esté cerrado con tapa o cuerda, será impuro.

[[numbers-19-16]]
^16^ Todo el que toque, en pleno campo, a un muerto a espada, o a un muerto, o huesos de hombre, o una sepultura, será impuro siete días.

[[numbers-19-17]]
^17^ Se tomará para el impuro ceniza de la víctima inmolada en sacrificio por el pecado, y se verterá encima agua viva de una vasija.

[[numbers-19-18]]
^18^ Un hombre puro tomará el hisopo, lo mojará en agua y rociará la tienda y todos los objetos y personas que había en ella, e igualmente al que tocó los huesos o al asesinado, o al muerto, o la sepultura.

[[numbers-19-19]]
^19^ El hombre puro rociará al impuro los días tercero y séptimo: el séptimo día le habrá limpiado de su pecado. Lavará el impuro sus vestidos, se lavará con agua, y será puro por la tarde.

[[numbers-19-20]]
^20^ Pero el hombre que quedó impuro y no se purificó, ése será extirpado de la asamblea, pues ha manchado el santuario de Yahveh. Las aguas lustrales no han corrido sobre él: es un impuro.

[[numbers-19-21]]
^21^ Este será para vosotros decreto perpetuo. El que haga la aspersión con las aguas lustrales lavará sus vestidos, y el que haya tocado las aguas lustrales será impuro hasta la tarde.

[[numbers-19-22]]
^22^ Y todo lo que haya sido tocado por el impuro, será impuro; y la persona que le toque a él, será impura hasta la tarde.
[[numbers-20]]
== Capítulo 20

[[numbers-20-1]]
^1^ Los israelitas, toda la comunidad, llegaron al desierto de Sin el mes primero, y se quedó todo el pueblo en Cadés. Allí murió María y allí la enterraron.

[[numbers-20-2]]
^2^ No había agua para la comunidad, por lo que se amotinaron contra Moisés y contra Aarón.

[[numbers-20-3]]
^3^ El pueblo protestó contra Moisés, diciéndole: «Ojalá hubiéramos perecido igual que perecieron nuestros hermanos delante de Yahveh.

[[numbers-20-4]]
^4^ ¿Por qué habéis traído la asamblea de Yahveh a este desierto, para que muramos en él nosotros y nuestros ganados?

[[numbers-20-5]]
^5^ ¿Por qué nos habéis subido de Egipto, para traernos a este lugar pésimo: un lugar donde no hay sembrado, ni higuera, ni viña, ni ganado, y donde no hay ni agua para beber?»

[[numbers-20-6]]
^6^ Moisés y Aarón dejaron la asamblea, se fueron a la entrada de la Tienda del Encuentro, y cayeron rostro en tierra. Y se les apareció la gloria de Yahveh.

[[numbers-20-7]]
^7^ Yahveh habló con Moisés y le dijo:

[[numbers-20-8]]
^8^ «Toma la vara y reúne a la comunidad, tú con tu hermano Aarón. Hablad luego a la peña en presencia de ellos, y ella dará sus aguas. Harás brotar para ellos agua de la peña, y darás de beber a la comunidad y a sus ganados».

[[numbers-20-9]]
^9^ Tomó Moisés la vara de la presencia de Yahveh como se lo había mandado.

[[numbers-20-10]]
^10^ Convocaron Moisés y Aarón la asamblea ante la peña y él les dijo: «Escuchadme, rebeldes. ¿Haremos brotar de esta peña agua para vosotros?»

[[numbers-20-11]]
^11^ Y Moisés alzó la mano y golpeó la peña con su vara dos veces. El agua brotó en abundancia, y bebió la comunidad y su ganado.

[[numbers-20-12]]
^12^ Dijo Yahveh a Moisés y Aarón: «Por no haber confiado en mí, honrándome ante los israelitas, os aseguro que no guiaréis a esta asamblea hasta la tierra que les he dado».

[[numbers-20-13]]
^13^ Estas son las aguas de Meribá, donde protestaron los israelitas contra Yahveh, y con las que él manifestó su santidad.

[[numbers-20-14]]
^14^ Envió Moisés mensajeros desde Cadés: «Al rey de Edom. Así dice tu hermano Israel: Ya sabes por qué gran calamidad hemos pasado.

[[numbers-20-15]]
^15^ Nuestros padres bajaron a Egipto y nos quedamos en Egipto mucho tiempo. Pero los egipcios nos trataron mal, a nosotros igual que a nuestros padres.

[[numbers-20-16]]
^16^ Clamamos entonces a Yahveh, y escuchó nuestra voz: envió un angel, y nos sacó de Egipto. Ahora estamos en Cadés, ciudad fronteriza de tu territorio.

[[numbers-20-17]]
^17^ Déjanos, por favor, pasar por tu tierra. No cruzaremos por campo ni por viñedo, ni beberemos agua de pozo. Seguiremos el camino real, sin torcer ni a la derecha ni a la izquierda hasta que crucemos tus fronteras».

[[numbers-20-18]]
^18^ Edom le respondió: «No pasarás por mí. Si lo haces, saldré espada en mano a tu encuentro».

[[numbers-20-19]]
^19^ Le respondieron los israelitas: «Seguiremos por la calzada, y si bebemos agua tuya, yo y mis rebaños, pagaremos su precio. Se trata de pasar a pie: no tiene importancia».

[[numbers-20-20]]
^20^ Respondió él: «No pasarás». Y salió Edom a su encuentro con mucha gente y mano poderosa.

[[numbers-20-21]]
^21^ Como Edom negó el paso a Israel por su territorio, Israel dio un rodeo.

[[numbers-20-22]]
^22^ Partieron de Cadés los israelitas, toda la comunidad, y llegaron a Hor de la Montaña.

[[numbers-20-23]]
^23^ Y dijo Yahveh a Moisés y Aarón en Hor de la Montaña, en la frontera del país de Edom:

[[numbers-20-24]]
^24^ «Que se reúna Aarón con los suyos, porque no debe entrar en la tierra que he dado a los israelitas, por haberos rebelado contra mi voz en las aguas de Meribá.

[[numbers-20-25]]
^25^ Toma a Aarón y a su hijo Eleazar y súbelos a la montaña de Hor.

[[numbers-20-26]]
^26^ Le quitarás a Aarón sus vestiduras y se las pondrás a su hijo Eleazar. Entonces Aarón se reunirá con los suyos: allí morirá».

[[numbers-20-27]]
^27^ Moisés hizo como le había mandado Yahveh. Subieron a Hor de la Montaña a la vista de toda la comunidad.

[[numbers-20-28]]
^28^ Quitó Moisés a Aarón sus vestiduras y se las puso a su hijo Eleazar. Y murió allí Aarón, en la cumbre del monte. Moisés y Eleazar bajaron de la montaña.

[[numbers-20-29]]
^29^ Toda la comunidad se dio cuenta de que había fallecido Aarón, y lloró a Aarón toda la casa de Israel durante treinta días.
[[numbers-21]]
== Capítulo 21

[[numbers-21-1]]
^1^ Oyó el rey de Arad, cananeo, que ocupaba el Négueb, que llegaba Israel por el camino de Atarim, y atacó a Israel y le hizo algunos prisioneros.

[[numbers-21-2]]
^2^ Entonces Israel formuló este voto a Yahveh: «Si entregas a ese pueblo en mi mano, consagraré al anatema sus ciudades».

[[numbers-21-3]]
^3^ Oyó Yahveh la voz de Israel y les entregó aquel cananeo. Los consagraron al anatema a ellos y a sus ciudades. Por eso se llamó aquel lugar Jormá.

[[numbers-21-4]]
^4^ Partieron de Hor de la Montaña, camino del mar de Suf, rodeando la tierra de Edom. El pueblo se impacientó por el camino.

[[numbers-21-5]]
^5^ Y habló el pueblo contra Dios y contra Moisés: «¿Por qué nos habéis subido de Egipto para morir en el desierto? Pues no tenemos ni pan ni agua, y estamos cansados de ese manjar miserable».

[[numbers-21-6]]
^6^ Envió entonces Yahveh contra el pueblo serpientes abrasadoras, que mordían al pueblo; y murió mucha gente de Israel.

[[numbers-21-7]]
^7^ El pueblo fue a decirle a Moisés: «Hemos pecado por haber hablado contra Yahveh y contra ti. Intercede ante Yahveh para que aparte de nosotros las serpientes,» Moisés intercedió por el pueblo.

[[numbers-21-8]]
^8^ Y dijo Yahveh a Moisés: «Hazte un Abrasador y ponlo sobre un mástil. Todo el que haya sido mordido y lo mire, vivirá».

[[numbers-21-9]]
^9^ Hizo Moisés una serpiente de bronce y la puso en un mástil. Y si una serpiente mordía a un hombre y éste miraba la serpiente de bronce, quedaba con vida.

[[numbers-21-10]]
^10^ Partieron los israelitas y acamparon en Obot.

[[numbers-21-11]]
^11^ Partieron de Obot y acamparon en Iyyé Haabarim, en el desierto que limita con Moab, hacia la salida del sol.

[[numbers-21-12]]
^12^ Partieron de allí y acamparon en el torrente de Zered.

[[numbers-21-13]]
^13^ De allí partieron y acamparon más allá del Arnón. Este estaba en el desierto y salía del territorio de los amorreos, pues el Arnón hacía de frontera de Moab, entre moabitas y amorreos.

[[numbers-21-14]]
^14^ Por eso se dice en el libro de las Guerras de Yahveh: ... Vaheb, cerca de Sufá y el torrente del Arnón,

[[numbers-21-15]]
^15^ y el declive del torrente que corre hacia la región de Ar y se apoya en la frontera de Moab.

[[numbers-21-16]]
^16^ Y de allí fueron a Beer - Este es el pozo a propósito del cual dijo Yahveh a Moisés: «Reúne al pueblo y les daré agua».

[[numbers-21-17]]
^17^ Entonces Israel entonó este cántico: Sobre el Pozo. Cantadle,

[[numbers-21-18]]
^18^ Pozo que cavaron Príncipes, que excavaron los jefes del pueblo, con el cetro, con sus bastones. - Y del desierto a Mattaná,

[[numbers-21-19]]
^19^ de Mattaná a Najaliel, de Najaliel a Bamot,

[[numbers-21-20]]
^20^ y de Bamot al valle que está en el campo de Moab, hacia la cumbre del Pisgá, que domina la parte del desierto.

[[numbers-21-21]]
^21^ Israel envió mensajeros a decir a Sijón, rey de los amorreos:

[[numbers-21-22]]
^22^ «Quisiera pasar por tu tierra. No me desviaré por campos y viñedos, ni beberé agua de pozo. Seguiremos el camino real hasta que crucemos tus fronteras».

[[numbers-21-23]]
^23^ Pero Sijón negó a Israel el paso por su territorio; reunió toda su gente y salió al desierto, al encuentro de Israel, hasta Yahás, donde atacó a Israel.

[[numbers-21-24]]
^24^ Pero Israel le hirió a filo de espada y se apoderó de su tierra, desde el Arnón hasta el Yabboq, hasta los límites de los hijos de Ammón, porque Yazer estaba en la frontera de los hijos de Ammón.

[[numbers-21-25]]
^25^ Israel tomó todas aquellas ciudades. Ocupó Israel todos los pueblos de los amorreos, Jesbón y todas sus aldeas.

[[numbers-21-26]]
^26^ Porque Jesbón era la ciudad de Sijón, rey de los amorreos. Este había combatido al primer rey de Moab, y le había quitado toda su tierra hasta el Arnón.

[[numbers-21-27]]
^27^ Por eso dicen los trovadores: ¡Venid a Jesbón, que sea construida, fortificada, la ciudad de Sijón!

[[numbers-21-28]]
^28^ Porque fuego ha salido de Jesbón, una llama de la ciudad de Sijón: ha devorado Ar Moab, ha tragado las alturas del Arnón.

[[numbers-21-29]]
^29^ ¡Ay de ti, Moab!, perdido estás, pueblo de Kemós. Entrega sus hijos a la fuga y sus hijas al cautiverio, en manos de Sijón, el rey amorreo.

[[numbers-21-30]]
^30^ Su posteridad ha perecido, desde Jesbón hasta Dibón, y hemos dado fuego desde Nofaj hasta Mádaba.

[[numbers-21-31]]
^31^ Israel se estableció en la tierra de los amorreos.

[[numbers-21-32]]
^32^ Moisés mandó a explorar Yazer y la tomaron junto con sus aldeas despojando al amorreo que vivía allí.

[[numbers-21-33]]
^33^ Se volvieron y subieron camino de Basán. Og, rey de Basán, salió a su encuentro con toda su gente, para darles batalla en Edreí.

[[numbers-21-34]]
^34^ Yahveh dijo a Moisés: «No le temas, porque lo he puesto en tu mano con todo su pueblo y su tierra. Harás con él como hiciste con Sijón, el rey amorreo que habitaba en Jesbón».

[[numbers-21-35]]
^35^ Y le batieron a él, a sus hijos y a toda su gente, hasta que no quedó nadie a salvo. Y se apoderaron de su tierra.
[[numbers-22]]
== Capítulo 22

[[numbers-22-1]]
^1^ Luego partieron los israelitas y acamparon en las Estepas de Moab, al otro lado del Jordán, a la altura de Jericó.

[[numbers-22-2]]
^2^ Vio Balaq, hijo de Sippor, todo lo que había hecho Israel con los amorreos

[[numbers-22-3]]
^3^ y se estremeció Moab ante pueblo, pues era muy numeroso. Tuvo miedo Moab de los israelitas

[[numbers-22-4]]
^4^ y dijo a los ancianos de Madián: «Ahora veréis cómo esa multitud va a devastarlo todo a nuestro alrededor, como devasta el buey la hierba del campo». Balaq, hijo de Sippor, era rey de Moab por aquel tiempo.

[[numbers-22-5]]
^5^ Envió mensajeros a buscar a Balaam, hijo de Beor, a Petor del Río, en tierra de los hijos de Ammav, para decirle: «He aquí que el pueblo que ha salido de Egipto ha cubierto la superficie de la tierra y se ha establecido frente a mí.

[[numbers-22-6]]
^6^ Ven, pues, por favor, maldíceme a ese pueblo, pues es más fuerte que yo, a ver si puedo vencerle y lo arrojo del país. Pues sé que el que tú bendices queda bendito y el que maldices, maldito».

[[numbers-22-7]]
^7^ Fueron los ancianos de Moab y los ancianos de Madián, con la paga del vaticinio en sus manos. Llegaron donde Balaam y le dijeron las palabras de Balaq.

[[numbers-22-8]]
^8^ El les contestó: «Pasad aquí la noche y os responderé según lo que me diga Yahveh». Los jefes de Moab se quedaron en casa de Balaam.

[[numbers-22-9]]
^9^ Entró Yahveh donde Balaam y le dijo: «¿Qué hombres son ésos que están en tu casa?»

[[numbers-22-10]]
^10^ Le respondió Balaam a Dios: «Balaq, hijo de Sippor, rey de Moab, me ha enviado a decir:

[[numbers-22-11]]
^11^ El pueblo que ha salido de Egipto ha cubierto la superficie de la tierra. Ven, pues, maldícemelo, a ver si puedo vencerlo y expulsarlo».

[[numbers-22-12]]
^12^ Pero dijo Dios a Balaam: «No vayas con ellos, no maldigas a ese pueblo porque es bendito».

[[numbers-22-13]]
^13^ Se levantó Balaam de madrugada y dijo a los jefes de Balaq: «Id a vuestra tierra, porque Yahveh no quiere dejarme ir con vosotros».

[[numbers-22-14]]
^14^ Se levantaron, pues, los jefes de Moab, volvieron donde Balaq y le dijeron: «Balaam se ha negado a venir con nosotros».

[[numbers-22-15]]
^15^ Balaq envió otra vez jefes en mayor número y más ilustres que los anteriores.

[[numbers-22-16]]
^16^ Fueron donde Balaam y le dijeron: «Así dice Balaq, hijo de Sippor: No rehúses, por favor, venir a mí,

[[numbers-22-17]]
^17^ que te recompensaré con grandes honores y haré todo lo que me digas. Ven, por favor, y maldíceme a ese pueblo».

[[numbers-22-18]]
^18^ Respondió Balaam a los siervos de Balaq: «Aunque me diera Balaq su casa llena de plata y oro, no podría traspasar la orden de Yahveh mi Dios en nada, ni poco ni mucho.

[[numbers-22-19]]
^19^ Quedaos aquí también vosotros esta noche y averiguaré qué más me dice Yahveh».

[[numbers-22-20]]
^20^ Entró Dios donde Balaam por la noche y le dijo: «¿No han venido esos hombres a llamarte? Levántate y vete con ellos. Pero has de cumplir la palabra que yo te diga».

[[numbers-22-21]]
^21^ Se levantó Balaam de madrugada, aparejó su asna y se fue con los jefes de Moab.

[[numbers-22-22]]
^22^ Cuando iba, se encendió la ira de Yahveh y el Angel de Yahveh se puso en el camino para estorbarle. El montaba la burra y sus dos muchachos iban con él.

[[numbers-22-23]]
^23^ La burra vio al Angel de Yahveh plantado en el camino, la espada desenvainada en la mano. La burra se apartó del camino y se fue a campo traviesa. Balaam pegó a la burra para hacerla volver al camino.

[[numbers-22-24]]
^24^ Pero el Angel de Yahveh se puso en un sendero entre las viñas, con una pared a un lado y otra a otro.

[[numbers-22-25]]
^25^ Al ver la burra al Angel de Yahveh, se arrimó a la pared y raspó el pie de Balaam contra la pared. El le pegó otra vez.

[[numbers-22-26]]
^26^ Volvió el Angel de Yahveh a cambiar de sitio, y se puso en un paso estrecho, donde no había espacio para apartarse ni a la derecha ni a la izquierda.

[[numbers-22-27]]
^27^ Vio la burra al Angel de Yahveh y se echó con Balaam encima. Balaam se enfureció y pegó a la burra con un palo.

[[numbers-22-28]]
^28^ Entonces Yahveh abrió la boca de la burra, que dijo a Balaam: «¿qué te he hecho yo para que me pegues con ésta ya tres veces?»

[[numbers-22-29]]
^29^ Respondió Balaam a la burra: «Porque te has burlado de mí. Ojalá tuviera una espada en la mano; ahora mismo te mataba».

[[numbers-22-30]]
^30^ Respondió la burra a Balaam: «¿No soy yo tu burra, y me has montado desde siempre hasta el dia de hoy? ¿Acaso acostumbro a portarme así contigo?» Respondió él: «No».

[[numbers-22-31]]
^31^ Entonces abrió Yahveh los ojos de Balaam, que vio al Angel de Yahveh, de pie en el camino, la espada desenvainada en la mano; y se inclinó y postró rostro en tierra.

[[numbers-22-32]]
^32^ El Angel de Yahveh le dijo; «¿Por qué has pegado a tu burra con ésta ya tres veces? He sido yo el que he salido a cerrarte el paso, porque delante de mí se tuerce el camino.

[[numbers-22-33]]
^33^ La burra me ha visto y se ha apartado de mí tres veces. Gracias a que se ha desviado, porque si no, para ahora te habría matado y a ella la habría dejado con vida».

[[numbers-22-34]]
^34^ Dijo entonces Balaam al Angel de Yahveh: «He pecado, pues no sabía que tú te habías puesto en mi camino. Pero ahora mismo, si esto te parece mal, me vuelvo».

[[numbers-22-35]]
^35^ Respondió el Angel de Yahveh a Balaam: «Vete con esos hombres, pero no dirás nada más que lo que yo te diga». Balaam marchó con los jefes de Balaq.

[[numbers-22-36]]
^36^ Oyó Balaq que llegaba Balaam y salió a su encuentro hacia Ar Moab, en la frontera del Arnón, en los confines del territorio.

[[numbers-22-37]]
^37^ Dijo Balaq a Balaam: «¿No te mandé llamar? ¿Por qué no viniste donde mí? ¿Es que no puedo recompensarte?»

[[numbers-22-38]]
^38^ Respondió Balaam a Balaq: «Mira que ahora ya he venido donde ti. A ver si puedo decir algo. La palabra que ponga Dios en mi boca es la que diré».

[[numbers-22-39]]
^39^ Marchó Balaam con Balaq y llegaron a Quiryat Jusot.

[[numbers-22-40]]
^40^ Sacrificó Balaq una vaca y una oveja y le envió porciones a Balaam y a los jefes que le acompañaban.

[[numbers-22-41]]
^41^ A la mañana, tomó Balaq a Balaam y lo hizo subir a Bamot Baal, desde donde se veía un extremo del campamento.
[[numbers-23]]
== Capítulo 23

[[numbers-23-1]]
^1^ Dijo Balaam a Balaq: «Constrúyeme aquí siete altares y prepárame siete novillos y siete carneros».

[[numbers-23-2]]
^2^ Balaq hizo lo que le había dicho Balaam, y ofreció en holocausto un novillo y un carnero en cada altar.

[[numbers-23-3]]
^3^ Dijo entonces Balaam a Balaq: «Quédate junto a tus holocaustos, mientras yo voy a ver si me sale al encuentro Yahveh. La palabra que me manifieste, te la communicaré». Y se fue a un monte pelado.

[[numbers-23-4]]
^4^ Salió Dios al encuentro de Balaam y éste le dijo: «Siete altares he preparado y he ofrecido en holocausto un novillo y un carnero sobre cada altar».

[[numbers-23-5]]
^5^ Yahveh entonces puso una palabra en la boca de Balaam y le dijo: «Vuelve donde Balaq y esto le dirás».

[[numbers-23-6]]
^6^ Volvió donde él y estaba aún de pie junto a su holocausto, con todos los príncipes de Moab.

[[numbers-23-7]]
^7^ El entonó su trova y dijo: «De Aram me hace venir Balaq, el rey de Moab desde los montes de Quédem: “Ven, maldíceme a Jacob; ven, execra a Israel.”

[[numbers-23-8]]
^8^ ¿Cómo maldeciré, si no maldice Dios? ¿Cómo execraré, si no execra Yahveh?

[[numbers-23-9]]
^9^ De la cumbre de las peñas lo diviso, de lo alto de las colinas lo contemplo: es un pueblo que vive aparte; no es contado entre las naciones.

[[numbers-23-10]]
^10^ ¿Quién contará el polvo de Jacob, quién numerará la polvareda de Israel? Muera mi alma con la muerte de los justos, Sea mi paradero como el suyo».

[[numbers-23-11]]
^11^ Dijo Balaq a Balaam: «¿Qué me has hecho? ¡Para maldecir a mis enemigos te he traído y los has colmado de bendiciones!»

[[numbers-23-12]]
^12^ Le respondió diciendo: «¿No tengo yo que esmerarme en hablar todo lo que Yahveh me pone en la boca?»

[[numbers-23-13]]
^13^ Le respondió Balaq: «Ven, pues, a otro sitio conmigo porque lo que ves desde aquí no es más que un extremo, no lo ves entero. Maldícemelo desde allí».

[[numbers-23-14]]
^14^ Y le llevó al Campo de los Centinelas, hacia la cumbre del Pisgá. Construyó siete altares y ofreció en holocausto un novillo y un carnero en cada altar.

[[numbers-23-15]]
^15^ Balaam dijo a Balaq: «Quédate aquí junto a tus holocaustos, mientras yo salgo al encuentro».

[[numbers-23-16]]
^16^ Salió Yahveh al encuentro de Balaam, puso una palabra en su boca y le dijo: «Vuelve donde Balaq y esto le dirás».

[[numbers-23-17]]
^17^ Volvió donde él y lo encontró aún de pie junto a sus holocaustos, con los príncipes de Moab. Le dijo Balaq: «¿Qué ha dicho Yahveh?»

[[numbers-23-18]]
^18^ El entonó su trova diciendo: «Levántate, Balaq, y escucha, prestame oídos, hijo de Sippor.

[[numbers-23-19]]
^19^ No es Dios un hombre, para mentir, ni hijo de hombre, para volverse atrás. ¿Es que él dice y no hace, habla y no lo mantiene?

[[numbers-23-20]]
^20^ He aquí que me ha tocado bendecir; bendeciré y no me retractaré.

[[numbers-23-21]]
^21^ No he divisado maldad en Jacob, ni he descubierto infortunio en Israel. Yahveh su Dios está con él, y en él se oye proclamar a un rey.

[[numbers-23-22]]
^22^ Dios le hace salir de Egipto, como cuernos de búfalo es para él.

[[numbers-23-23]]
^23^ No hay presagio contra Jacob, ni sortilegio contra Israel. Según se le está diciendo a Jacob y a Israel: «¿Qué hace tu Dios?»,

[[numbers-23-24]]
^24^ he aquí que un pueblo se levanta como leona, se yergue como león: no se acostará hasta devorar la presa y beber la sangre de sus víctimas».

[[numbers-23-25]]
^25^ Balaq dijo a Balaam: «Ya que no le maldices, por lo menos no le bendigas».

[[numbers-23-26]]
^26^ Respondió Balaam y dijo a Balaq: «¿No te he dicho que hago todo lo que me dice Yahveh?»

[[numbers-23-27]]
^27^ Dijo Balaq a Balaam: «Ven, por favor, que te lleve a otro sitio, a ver si le place a Dios que me lo maldigas desde allí».

[[numbers-23-28]]
^28^ LLevó Balaq a Balaam a la cumbre del Peor, que domina la parte del desierto.

[[numbers-23-29]]
^29^ Dijo Balaam a Balaq: «Constrúyeme aquí siete altares y prepárame aquí siete novillos y siete carneros».

[[numbers-23-30]]
^30^ Balaq hizo lo que le había dicho Balaam, y ofreció en holocausto un novillo y un carnero en cada altar.
[[numbers-24]]
== Capítulo 24

[[numbers-24-1]]
^1^ Vio Balaam que agradaba a Yahveh bendecir a Israel, y ya no fue como las otras veces al encuentro de los augurios, sino que se volvió cara al desierto.

[[numbers-24-2]]
^2^ Y al alzar los ojos, vio Balaam a Israel acampado por tribus. Y le invadió el espíritu de Dios.

[[numbers-24-3]]
^3^ Entonó su trova y dijo: «Oráculo de Balaam, hijo de Beor, oráculo del varón clarividente.

[[numbers-24-4]]
^4^ Oráculo del que oye los dichos de Dios, del que ve la visión de Sadday del que obtiene respuesta, y se le abren los ojos.

[[numbers-24-5]]
^5^ ¡Qué hermosas son tus tiendas, Jacob, y tus moradas, Israel!

[[numbers-24-6]]
^6^ Como valles espaciosos, como jardines a la vera del río, como áloes que plantó Yahveh, como cedros a la orilla de las aguas.

[[numbers-24-7]]
^7^ Sale un héroe de su descendencia, domina sobre pueblos numerosos. Se alza su rey por encima de Agag, se alza su reinado.

[[numbers-24-8]]
^8^ Dios le hace salir de Egipto, como cuernos de búfalo es para él. Devora el cadáver de sus enemigos y les quebranta los huesos.

[[numbers-24-9]]
^9^ Se agacha, se acuesta, como león, como leona, ¿quién le hará levantar? ¡Bendito el que te bendiga! ¡Maldito el que te maldiga!»

[[numbers-24-10]]
^10^ Se enfureció Balaq contra Balaam, palmoteó fuertemente, y dijo a Balaam: «Te he llamado para maldecir a mis enemigos y he aquí que los has llenado de bendiciones ya por tercera vez.

[[numbers-24-11]]
^11^ Lárgate ya a tu tierra. Te dije que te colmaría de honores, pero Yahveh te ha privado de ellos».

[[numbers-24-12]]
^12^ Respondió Balaam a Balaq: «¿No les dije yo a los mensajeros que me enviaste:

[[numbers-24-13]]
^13^ “Aunque me diera Balaq su casa llena de plata y oro, no podría salirme de la orden de Yahveh, ni hacer por mi cuenta nada, bueno ni malo; lo que me diga Yahveh, eso es lo que diré?”

[[numbers-24-14]]
^14^ Ahora, pues, que me marcho a mi pueblo, ven, que te voy a anunciar lo que hará este pueblo al cabo del tiempo».

[[numbers-24-15]]
^15^ Entonó su trova y dijo: «Oráculo de Balaam, hijo de Beor, oráculo del varón clarividente.

[[numbers-24-16]]
^16^ oráculo del que escucha los dichos de Dios, del que conoce la ciencia del Altísimo; del que ve lo que le hace ver Sadday, del que obtiene la respuesta, y se le abren los ojos.

[[numbers-24-17]]
^17^ Lo veo, aunque no para ahora, lo diviso, pero no de cerca: de Jacob avanza una estrella, un cetro surge de Israel. Aplasta las sienes de Moab, el cráneo de todos los hijos de Set.

[[numbers-24-18]]
^18^ Será Edom tierra conquistada, tierra conquistada Seír. Israel despliega su poder,

[[numbers-24-19]]
^19^ Jacob domina a sus enemigos, aniquila a los fugitivos de Ar».

[[numbers-24-20]]
^20^ Vio Balaam a Amalec, entonó su trova y dijo: «Primicias de las naciones, Amalec; pero al cabo perecerá para siempre».

[[numbers-24-21]]
^21^ Vio luego a los quenitas, entonó su trova y dijo: «Firme es tu morada, Caín, en la peña está puesto tu nido.

[[numbers-24-22]]
^22^ Pero el nido es de Beor; ¿hasta cuándo te tendrá cautivo Asur?

[[numbers-24-23]]
^23^ Entonó luego su trova y dijo: Pueblos del Mar reviven por el Norte,

[[numbers-24-24]]
^24^ barcos por el lado de Kittim. Oprimen a Asur, oprimen a Héber; también él perecerá para siempre».

[[numbers-24-25]]
^25^ Luego se levantó Balaam, y se fue de vuelta a su país. También Balaq se fue por su camino.
[[numbers-25]]
== Capítulo 25

[[numbers-25-1]]
^1^ Israel se estableció en Sittim. Y el pueblo se puso a fornicar con las hijas de Moab.

[[numbers-25-2]]
^2^ Estas invitaron al pueblo a los sacrificios de sus dioses, y el pueblo comió y se postró ante sus dioses.

[[numbers-25-3]]
^3^ Israel se adhirió así al Baal de Peor, y se encendió la ira de Yahveh contra Israel.

[[numbers-25-4]]
^4^ Dijo Yahveh a Moisés: «Toma a todos los jefes del pueblo y empálalos en honor de Yahveh, cara al sol; así cederá el furor de la cólera de Yahveh contra Israel».

[[numbers-25-5]]
^5^ Dijo Moisés a los jueces de Israel: «Matad cada uno a los vuestros que se hayan adherido a Baal de Peor».

[[numbers-25-6]]
^6^ Sucedió que un hombre, un israelita, vino y presentó ante sus hermanos a la madianita, a los mismos ojos de Moisés y de toda la comunidad de los israelitas, que estaban llorando a la entrada de la Tienda del Encuentro.

[[numbers-25-7]]
^7^ Al verlos Pinjás, hijo de Eleazar, hijo del sacerdote Aarón, se levantó de entre la comunidad, lanza en mano,

[[numbers-25-8]]
^8^ entró tras el hombre a la alcoba y los atravesó a los dos, al israelita y a la mujer, por el bajo vientre. Y se detuvo la plaga que azotaba a los israelitas.

[[numbers-25-9]]
^9^ Los muertos por la plaga fueron 24.000.

[[numbers-25-10]]
^10^ Yahveh habló a Moisés y le dijo:

[[numbers-25-11]]
^11^ «Pinjás, hijo de Eleazar, hijo del sacerdote Aarón, ha aplacado mi furor contra los israelitas, porque él ha sido, de entre vosotros, el que ha sentido celo por mí; por eso no he acabado con los israelitas a impulso de mis celos.

[[numbers-25-12]]
^12^ Por eso digo: Le concedo a él mi alianza de paz.

[[numbers-25-13]]
^13^ Habrá para él y para su descendencia después de él una alianza de sacerdocio perpetuo. En recompensa de haber sentido celo por su Dios, celebrará el rito de expiación sobre los israelitas».

[[numbers-25-14]]
^14^ El israelita herido, el que fue herido con la madianita, se llamaba Zimri, hijo de Salú, principal de una casa paterna de Simeón.

[[numbers-25-15]]
^15^ Y la mujer herida, la madianita, se llamaba Kozbí, hija de Sur. Este era jefe de su clan, de una casa paterna de Madián.

[[numbers-25-16]]
^16^ Habló Yahveh a Moisés y le dijo:

[[numbers-25-17]]
^17^ «Atacad a los madianitas y batidlos,

[[numbers-25-18]]
^18^ porque ellos os han atacado a vosotros engañándoos con sus malas artes, con lo de Peor, y con lo de su hermana Kozbí, hija de un príncipe de Madián, la que fue herida el día de la plaga que hubo por lo de Peor».

[[numbers-25-19]]
^19^ Después de la plaga,
[[numbers-26]]
== Capítulo 26

[[numbers-26-1]]
^1^ Yahveh habló a Moisés y a Eleazar, hijo del sacerdote Aarón, y les dijo:

[[numbers-26-2]]
^2^ «Haced el recuento de toda la comunidad de los israelitas, por casas paternas, de veinte años en adelante, de todos los útiles para la guerra».

[[numbers-26-3]]
^3^ Moisés y el sacerdote Eleazar les pasaron revista en las Estepas de Moab, cerca del Jordán, a la altura de Jericó,

[[numbers-26-4]]
^4^ como había mandado Yahveh a Moisés y a los israelitas cuando salían de Egipto. De veinte años en adelante:

[[numbers-26-5]]
^5^ Rubén, primogénito de Israel. Hijos de Rubén: de Henoc, el clan henoquita; de Pallú, el clan paluita;

[[numbers-26-6]]
^6^ de Jesrón, el clan jesronita; de Karmí, el clan karmita.

[[numbers-26-7]]
^7^ Esos eran los clanes rubenitas. Hecho el censo, resultaron ser 43.730.

[[numbers-26-8]]
^8^ Hijos de Pallú: Eliab.

[[numbers-26-9]]
^9^ Hijos de Eliab: Nemuel, Datán y Abirón. Estos Datán y Abirón eran famosos en la comunidad y se rebelaron contra Moisés y Aarón con la cuadrilla de Coré, cuando ésta se rebeló contra Yahveh.

[[numbers-26-10]]
^10^ La tierra abrió su boca y los tragó a ellos y a Coré, cuando el fuego devoró a 250 hombres, para que sirvieran de escarmiento.

[[numbers-26-11]]
^11^ Pero los hijos de Coré no murieron.

[[numbers-26-12]]
^12^ Hijos de Simeón, por clanes: De Nemuel, el clan nemuelita; de Yamín, el clan yaminita; de Yakín, el clan yakinita;

[[numbers-26-13]]
^13^ de Zéraj, el clan zerajita; de Saúl, el clan saulita.

[[numbers-26-14]]
^14^ Esos eran los clanes simeonitas. Fueron contados: 22.200.

[[numbers-26-15]]
^15^ Hijos de Gad, por clanes: De Sefón, el clan sefonita; de Jagguí, el clan jagguita; de Suní, el clan sunita;

[[numbers-26-16]]
^16^ de Ozní, el clan oznita; de Erí, el clan erita;

[[numbers-26-17]]
^17^ de Arod, el clan arodita; de Arelí, el clan arelita.

[[numbers-26-18]]
^18^ Esos eran los clanes de los hijos de Gad. Según el censo fueron contados: 40.500.

[[numbers-26-19]]
^19^ Hijos de Judá: Er y Onán. Er y Onán murieron en la tierra de Canaán.

[[numbers-26-20]]
^20^ Los hijos de Judá, por clanes, eran: de Selá, el clan selanita; de Peres, el clan peresita; de Zéraj, el clan zerajita.

[[numbers-26-21]]
^21^ Hijos de Peres fueron: de Jesrón, el clan jesronita; de Jamul, el clan jamulita.

[[numbers-26-22]]
^22^ Esos eran los clanes de Judá. Según el censo fueron contados: 76.500.

[[numbers-26-23]]
^23^ Hijos de Isacar, por clanes: de Tolá, el clan tolaíta; de Puvá el clan puvita

[[numbers-26-24]]
^24^ de Yasub, el clan yasubita; de Simrón, el clan simronita.

[[numbers-26-25]]
^25^ Esos eran los clanes de Isacar. Según el censo fueron contados 64.300.

[[numbers-26-26]]
^26^ Hijos de Zabulón, por clanes: de Séred, el clan sardita; de Elón, el clan elonita; de Yajleel, el clan yajleelita.

[[numbers-26-27]]
^27^ Esos eran los clanes de Zabulón. Según el censo: 60.500.

[[numbers-26-28]]
^28^ Hijos de José, por clanes: Manasés y Efraím.

[[numbers-26-29]]
^29^ Hijos de Manasés: de Makir, el clan makirita. Makir engendró a Galaad. De Galaad, el clan galaadita.

[[numbers-26-30]]
^30^ Los hijos de Galaad eran: de Yézer, el clan Yezerita; de Jéleq, el clan jelequita;

[[numbers-26-31]]
^31^ Asriel, el clan asrielita; Sekem, el clan sekemita;

[[numbers-26-32]]
^32^ Semidá, el clan semidaita; Jéfer, el clan jeferita;

[[numbers-26-33]]
^33^ Selofjad, hijo de Jéfer, no tuvo hijos; solamente hijas. Se llamaban las hijas de Selofjad: Majlá, Noá, Jojlá, Milká y Tirsá.

[[numbers-26-34]]
^34^ Esos eran los clanes de Manasés, según el censo: 52.700.

[[numbers-26-35]]
^35^ Estos eran los hijos de Efraím, por clanes: de Sutélaj, el clan sutelajita; de Beker, el clan bekerita; de Taján, el clan tajanita.

[[numbers-26-36]]
^36^ Estos son los hijos de Sutélaj: de Erán, el clan eranita.

[[numbers-26-37]]
^37^ Esos eran los clanes de los hijos de Efraím. Según el censo fueron contados: 32.500. Esos eran los hijos de José, por clanes.

[[numbers-26-38]]
^38^ Hijos de Benjamín, por clanes: de Belá, el clan belaíta; de Asbel, el clan asbelita; de Ajiram, el clan ajiramita;

[[numbers-26-39]]
^39^ de Sefufam, el clan sefufamita; de Jufam, el clan jufamita.

[[numbers-26-40]]
^40^ Fueron los hijos de Belá, Ard y Naamán: el clan ardita; de Naamán, el clan naamanita.

[[numbers-26-41]]
^41^ Esos eran los hijos de Benjamín, por clanes. Según el censo fueron contados: 45.600.

[[numbers-26-42]]
^42^ Estos eran los hijos de Dan, por clanes: de Sujam, el clan sujamita. Estos eran los clanes de Dan, por clanes:

[[numbers-26-43]]
^43^ Todos los clanes sujamitas. Según el censo fueron contados: 64.400.

[[numbers-26-44]]
^44^ Hijos de Aser, por clanes: de Yimná, el clan yimnita; de Yisví, el clan yisvita; de Beriá, el clan berita.

[[numbers-26-45]]
^45^ De los hijos de Beriá: de Jéber, el clan jeberita; de Malkiel, el clan malkielita.

[[numbers-26-46]]
^46^ La hija de Aser, se llamaba Sáraj.

[[numbers-26-47]]
^47^ Esos eran los clanes de los hijos de Aser. Según el censo fueron contados: 53.400.

[[numbers-26-48]]
^48^ Hijos de Neftalí, por clanes: de Yajseel, el clan yajseelita; de Guní, el clan gunita;

[[numbers-26-49]]
^49^ de Yéser, el clan yisrita; de Sillem, el clan silemita.

[[numbers-26-50]]
^50^ Esos eran los clanes de Neftalí, por clanes. Según el censo fueron contados: 45.400.

[[numbers-26-51]]
^51^ Los revistados de los israelitas resultaron ser 601.730.

[[numbers-26-52]]
^52^ Habló Yahveh a Moisés y le dijo:

[[numbers-26-53]]
^53^ «A éstos les has de repartir la tierra en herencia, conforme al número de alistados:

[[numbers-26-54]]
^54^ al grande le aumentarás la herencia y al pequeño se la reducirás; a cada uno se le dará la herencia según el número de sus alistados.

[[numbers-26-55]]
^55^ Pero el reparto se hará a suertes; según el número de alistados de cada tribu paterna se hará la distribución.

[[numbers-26-56]]
^56^ A suertes distribuirás la herencia, distinguiendo entre el grande y el pequeño.

[[numbers-26-57]]
^57^ Estos fueron los alistados de Leví, por clanes. De Guerson, el clan guersonita; de Quehat, el clan quehatita; de Merarí, el clan merarita.

[[numbers-26-58]]
^58^ Estos eran los clanes de Leví: el clan libnita, el clan hebronita, el clan majlita, el clan musita, el clan coreíta. Quehat engendró a Amram.

[[numbers-26-59]]
^59^ La mujer de Amram se llamaba Yokebed, hija de Leví, que le nació a Leví en Egipto. Amram tuvo de ella a Aarón, a Moisés y a María su hermana.

[[numbers-26-60]]
^60^ Aarón engendró a Nadab y Abihú, a Eleazar e Itamar.

[[numbers-26-61]]
^61^ Nadab y Abihú murieron al ofrecer fuego profano delante de Yahveh.

[[numbers-26-62]]
^62^ El total del censo de todos los varones de un mes en adelante fue 23.000. Porque no fueron alistados con los demás israelitas, pues no se les daba herencia entre los demás israelitas.

[[numbers-26-63]]
^63^ Estos fueron los revistados por Moisés y el sacerdote Eleazar. Revistaron a los israelitas en las Estepas de Moab, cerca del Jordán a la altura de Jericó.

[[numbers-26-64]]
^64^ Entre ellos no quedaba nadie de los que habían sido alistados por Moisés y por el sacerdote Aarón, cuando hicieron el censo de los israelitas en el desierto del Sinaí.

[[numbers-26-65]]
^65^ Es que Yahveh les había dicho que morirían en el desierto, sin que quedara uno de ellos, excepto Caleb, hijo de Yefunné, y Josué, hijo de Nun.
[[numbers-27]]
== Capítulo 27

[[numbers-27-1]]
^1^ Entonces se acercaron las hijas de Selofjad, hijo de Jéfer, hijo de Galaad, hijo de Makir, hijo de Manasés, de los clanes de Manasés, hijo de José. Se llamaban las hijas: Majlá, Noá, Joglá, Milká y Tirsá.

[[numbers-27-2]]
^2^ Se presentaron a Moisés y al sacerdote Eleazar, a los principales y a toda la comunidad, a la entrada de la Tienda del Encuentro, y dijeron:

[[numbers-27-3]]
^3^ «Nuestro padre murió en el desierto. No era de la facción que se amotinó contra Yahveh, de la facción de Coré; por sus propios pecados murió sin tener hijos.

[[numbers-27-4]]
^4^ ¿Por qué ha de ser borrado de su clan el nombre de nuestro padre, sólo por no haber tenido hijos? Danos alguna propiedad entre los hermanos de nuestro padre».

[[numbers-27-5]]
^5^ Moisés expuso su caso ante Yahveh.

[[numbers-27-6]]
^6^ Respondió Yahveh a Moisés:

[[numbers-27-7]]
^7^ «Han hablado bien las hijas de Selofjad. Dales, pues, en propiedad una heredad entre los hermanos de su padre; traspásales a ellas la herencia de su padre.

[[numbers-27-8]]
^8^ Y dirás a los israelitas: Si un hombre muere y no tiene ningún hijo, traspasará su herencia a su hija.

[[numbers-27-9]]
^9^ Si tampoco tiene hija, daréis la herencia a sus hermanos.

[[numbers-27-10]]
^10^ Si tampoco tiene hermanos, daréis la herencia a los hermanos de su padre.

[[numbers-27-11]]
^11^ Y si su padre no tenía hermanos, daréis la herencia al pariente más próximo de su clan, el cual tomará posesión de ella. Esta será norma de derecho para los israelitas, según lo ordenó Yahveh a Moisés».

[[numbers-27-12]]
^12^ Dijo Yahveh a Moisés: «Sube ahí a la sierra de Abarim y mira la tierra que he dado a los israelitas.

[[numbers-27-13]]
^13^ Cuando la veas, irás a reunirte tú también a los tuyos, como se reunió tu hermano Aarón.

[[numbers-27-14]]
^14^ Porque os rebelasteis en el desierto de Sin, cuando protestó la comunidad y cuando os mandé manifestar delante de ella mi santidad, por medio del agua». Estas son las aguas de Meribá de Cadés, en el desierto de Sin.

[[numbers-27-15]]
^15^ Habló Moisés a Yahveh y le dijo:

[[numbers-27-16]]
^16^ «Que Yahveh, Dios de los espíritus de toda carne, ponga un hombre al frente de esta comunidad,

[[numbers-27-17]]
^17^ uno que salga y entre delante de ellos y que los haga salir y entrar, para que no quede la comunidad de Yahveh como rebaño sin pastor».

[[numbers-27-18]]
^18^ Respondió Yahveh a Moisés: «Toma a Josué, hijo de Nun, hombre en quien está el espíritu, impónle tu mano,

[[numbers-27-19]]
^19^ y colócalo delante del sacerdote Eleazar y delante de toda la comunidad para darle órdenes en presencia de ellos

[[numbers-27-20]]
^20^ y comunicarle parte de tu dignidad, con el fin de que le obedezca toda la comunidad de los israelitas.

[[numbers-27-21]]
^21^ Que se presente al sacerdote Eleazar y que éste consulte acerca de él, según el rito del Urim, delante de Yahveh. A sus órdenes saldrán y a sus órdenes entrarán él y todos los israelitas, toda la comunidad».

[[numbers-27-22]]
^22^ Moisés hizo como le había mandado Yahveh: tomó a Josué y lo puso delante del sacerdote Eleazar, y delante de toda la comunidad.

[[numbers-27-23]]
^23^ Le impuso su mano y le dio sus órdenes, como había dicho Yahveh por Moisés.
[[numbers-28]]
== Capítulo 28

[[numbers-28-1]]
^1^ Habló Yahveh a Moisés y le dijo:

[[numbers-28-2]]
^2^ «Manda a los israelitas en estos términos: Tendréis cuidado de traer a su tiempo mi ofrenda, mi alimento, manjares míos abrasados de calmante aroma.

[[numbers-28-3]]
^3^ Les dirás: Este será el manjar abrasado que ofreceréis a Yahveh: «Corderos de un año, sin defecto, dos al día, como holocausto perpetuo.

[[numbers-28-4]]
^4^ Uno de los corderos lo ofrecerás en holocausto por la mañana, y el otro cordero entre dos luces;

[[numbers-28-5]]
^5^ y como oblación, una décima de medida de flor de harina, amasada con un cuarto de sextario de aceite virgen.

[[numbers-28-6]]
^6^ Es el holocausto perpetuo ofrecido antaño en el monte Sinaí como calmante aroma, manjar abrasado para Yahveh.

[[numbers-28-7]]
^7^ Y la libación correspondiente: un cuarto de sextario por cada cordero. La libación de bebida fermentada para Yahveh la derramarás en el santuario.

[[numbers-28-8]]
^8^ El segundo cordero lo ofrecerás entre dos luces: lo ofrecerás con la misma oblación y libación que el de la mañana, como manjar abrasado de calmante aroma para Yahveh.

[[numbers-28-9]]
^9^ «El día de sábado, dos corderos de un año, sin tacha, y como oblación dos décimas de flor de harina amasada con aceite, y su correspondiente libación.

[[numbers-28-10]]
^10^ El holocausto del sábado, con su libación, se añadirá los sábados al holocausto perpetuo.

[[numbers-28-11]]
^11^ Los primeros de mes ofreceréis un holocausto a Yahveh: dos novillos, un carnero y siete corderos de un año, sin tacha.

[[numbers-28-12]]
^12^ Como oblación tres décimas de flor de harina amasada con aceite por cada novillo; dos décimas de flor de harina amasada con aceite, como oblación por el carnero;

[[numbers-28-13]]
^13^ una décima de flor de harina amasada con aceite, por cada cordero. Es un holocausto de calmante aroma, manjar abrasado para Yahveh.

[[numbers-28-14]]
^14^ Las libaciones correspondientes serán: medio sextario de vino por novillo, un tercio de sextario por carnero y un cuarto de sextario por cordero. Este será el holocausto mensual, todos los meses del año uno tras otro.

[[numbers-28-15]]
^15^ Ofrecerás también a Yahveh, como sacrificio por el pecado, un macho cabrío con su libación, además del holocausto perpetuo.

[[numbers-28-16]]
^16^ «El mes primero, el día catorce del mes, es la Pascua de Yahveh,

[[numbers-28-17]]
^17^ y el día quince del mismo mes es día de fiesta. Durante siete días comeréis panes ázimos.

[[numbers-28-18]]
^18^ El día primero habrá reunión sagrada. No haréis ningún trabajo servil.

[[numbers-28-19]]
^19^ Ofreceréis como manjar abrasado en holocausto a Yahveh: dos novillos, un carnero, siete corderos de un año, sin tacha.

[[numbers-28-20]]
^20^ La oblación correspondiente de flor de harina amasada con aceite será de tres décimas por novillo, dos décimas por el carnero,

[[numbers-28-21]]
^21^ y una décima por cada uno de los siete corderos;

[[numbers-28-22]]
^22^ y un macho cabrío como sacrificio por el pecado, para expiar por vosotros.

[[numbers-28-23]]
^23^ Esto, además del holocausto de la mañana, que ofreceréis como holocausto perpetuo.

[[numbers-28-24]]
^24^ Así haréis los siete días. Es un alimento, un manjar abrasado de calmante aroma para Yahveh: se ofrece además del holocausto perpetuo y de su libación.

[[numbers-28-25]]
^25^ El día séptimo tendréis reunión sagrada; no haréis ningún trabajo servil.

[[numbers-28-26]]
^26^ «El día de las primicias, cuando ofrezcáis a Yahveh oblación de frutos nuevos en vuestra fiesta de las Semanas, tendréis reunión sagrada; no haréis ningún trabajo servil.

[[numbers-28-27]]
^27^ Ofreceréis en holocausto, como calmante aroma para Yahveh, dos novillos, un carnero y siete corderos de un año.

[[numbers-28-28]]
^28^ La oblación correspondiente será de flor de harina amasada con aceite: tres décimas por novillo, dos décimas por el carnero,

[[numbers-28-29]]
^29^ y una décima por cada uno de los siete corderos;

[[numbers-28-30]]
^30^ y un macho cabrío como sacrificio por el pecado para hacer expiación por vosotros.

[[numbers-28-31]]
^31^ Haréis esto además del holocausto perpetuo, con su oblación y su libaciones.
[[numbers-29]]
== Capítulo 29

[[numbers-29-1]]
^1^ «El mes séptimo, el primero de mes, tendréis reunión sagrada; no haréis ningún trabajo servil. Será para vosotros el día de los Clamores.

[[numbers-29-2]]
^2^ Ofreceréis un holocausto como calmante aroma para Yahveh: un novillo, un carnero, siete corderos de un año, sin tacha.

[[numbers-29-3]]
^3^ La oblación correspondiente de flor de harina amasada con aceite, será de tres décimas por el novillo, dos décimas por el carnero

[[numbers-29-4]]
^4^ y una décima por cada uno de los siete corderos;

[[numbers-29-5]]
^5^ y un macho cabrío como sacrificio por el pecado, para hacer la expiación por vosotros.

[[numbers-29-6]]
^6^ Esto, además del holocausto mensual y de su oblación, del holocausto perpetuo y de su oblación y sus libaciones, según la norma correspondiente, como calmante aroma, manjar abrasado para Yahveh.

[[numbers-29-7]]
^7^ «El día décimo del mismo mes séptimo tendréis reunión sagrada; ayunaréis y no haréis ningún trabajo.

[[numbers-29-8]]
^8^ Ofreceréis en holocausto a Yahveh, como calmante aroma, un novillo, un carnero, siete corderos de un año, que habrán de ser sin defecto;

[[numbers-29-9]]
^9^ su oblación de flor de harina amasada con aceite, será: tres décimas por el novillo, dos décimas por el carnero,

[[numbers-29-10]]
^10^ una décima por cada uno de los siete corderos;

[[numbers-29-11]]
^11^ y un macho cabrío, como sacrificio por el pecado de la fiesta de la Expiación, del holocausto perpetuo, de su oblación y sus libaciones.

[[numbers-29-12]]
^12^ «El día quince del mes séptimo tendréis reunión sagrada; no haréis ningún trabajo servil y celebraréis fiesta en honor de Yahveh durante siete días.

[[numbers-29-13]]
^13^ Ofreceréis en holocausto un manjar abrasado de calmante aroma para Yahveh: trece novillos, dos carneros, catorce corderos de un año, que serán sin defecto;

[[numbers-29-14]]
^14^ la oblación correspondiente será de flor de harina amasada con aceite, tres décimas por cada uno de los trece novillos, dos décimas por cada uno de los dos carneros,

[[numbers-29-15]]
^15^ y una décima por cada uno de los catorce corderos;

[[numbers-29-16]]
^16^ y un macho cabrío como sacrificio por el pecado; además del holocausto perpetuo, de su oblación y su libación.

[[numbers-29-17]]
^17^ El día segundo, doce novillos, dos carneros, catorce corderos de un año, sin tacha,

[[numbers-29-18]]
^18^ con las oblaciones y libaciones correspondientes a los novillos, carneros y corderos, conforme a su número y según la norma;

[[numbers-29-19]]
^19^ y un macho cabrío, como sacrificio por el pecado; además del holocausto perpetuo, de su oblación y sus libaciones.

[[numbers-29-20]]
^20^ El día tercero: once novillos, dos carneros, catorce corderos de un año, sin tacha,

[[numbers-29-21]]
^21^ con las oblaciones y libaciones correspondientes a los novillos, carneros y corderos, conforme a su número y según la norma;

[[numbers-29-22]]
^22^ y un macho cabrío como sacrificio por el pecado; además del holocausto perpetuo, de su oblación y su libación.

[[numbers-29-23]]
^23^ El día cuarto: diez novillos, dos carneros, catorce corderos de un año, sin tacha;

[[numbers-29-24]]
^24^ las oblaciones y libaciones correspondientes a los novillos, carneros y corderos, conforme a su número y según la norma;

[[numbers-29-25]]
^25^ y un macho cabrío, como sacrificio por el pecado; además del holocausto perpetuo, de su oblación y su libación.

[[numbers-29-26]]
^26^ El día quinto: nueve novillos, dos carneros, catorce corderos de un año, sin tacha;

[[numbers-29-27]]
^27^ las oblaciones y libaciones correspondientes a los novillos, carneros y corderos, conforme a su número y según la norma;

[[numbers-29-28]]
^28^ y un macho cabrío, como sacrificio por el pecado; además del holocausto perpetuo, de su oblación y su libación.

[[numbers-29-29]]
^29^ El día sexto: ocho novillos, dos carneros, catorce corderos de un año, sin tacha;

[[numbers-29-30]]
^30^ las oblaciones y libaciones correspondientes a los novillos, carneros y corderos, conforme a su número y según la norma;

[[numbers-29-31]]
^31^ y un macho cabrío, como sacrificio por el pecado; además del holocausto perpetuo, de su oblación y su libación.

[[numbers-29-32]]
^32^ El día séptimo: siete novillos, dos carneros, catorce corderos de un año, sin tacha;

[[numbers-29-33]]
^33^ las oblaciones y libaciones correspondientes a los novillos, carneros y corderos, conforme a su número y según la norma;

[[numbers-29-34]]
^34^ y un macho cabrío como sacrificio por el pecado; además del holocauso perpetuo y de su oblación y su libación.

[[numbers-29-35]]
^35^ El día octavo será para vosotros de reunión solemne; no haréis ningún trabajo servil.

[[numbers-29-36]]
^36^ Ofreceréis un holocausto, como manjar abrasado de calmante aroma para Yahveh: un novillo, un carnero, siete corderos de un año, sin tacha;

[[numbers-29-37]]
^37^ la oblación y libaciones correspondientes al novillo, al carnero y a los corderos, conforme a su número y según la norma;

[[numbers-29-38]]
^38^ y un macho cabrío como sacrificio por el pecado; además del holocausto perpetuo, de su oblación y su libación.

[[numbers-29-39]]
^39^ Estos son los sacrificios que ofreceréis a Yahveh en vuestras solemnidades, aparte de vuestras ofrendas votivas y espontáneas, holocaustos, oblaciones, libaciones y sacrificios de comunión».
[[numbers-30]]
== Capítulo 30

[[numbers-30-1]]
^1^ Moisés habló a los israelitas conforme en todo a lo que le había ordenado Yahveh.

[[numbers-30-2]]
^2^ Habló Moisés a los jefes de tribu de los israelitas y les dijo: «Esto es lo que ha ordenado Yahveh:

[[numbers-30-3]]
^3^ Si un hombre hace un voto a Yahveh, o se compromete a algo con juramento, no violará su palabra: cumplirá todo lo que ha salido de su boca.

[[numbers-30-4]]
^4^ Y si una mujer hace un voto a Yahveh, o adquiere un compromiso, en su juventud, cuando está en casa de su padre,

[[numbers-30-5]]
^5^ si su padre se entera de su voto o del compromiso que ha contraído, y no le dice nada su padre, serán firmes todos sus votos, y todos los compromisos que ha contraído serán firmes.

[[numbers-30-6]]
^6^ Pero si su padre, el mismo día en que se entera de cualquiera de sus votos o de los compromisos que ha contraído, lo desaprueba, no serán firmes. Yahveh no se lo tendrá en cuenta, pues su padre lo ha desaprobado.

[[numbers-30-7]]
^7^ Y si se casa cuando todavía está ligada por sus votos o por un compromiso que inconsideradamente contrajeron sus labios,

[[numbers-30-8]]
^8^ si su marido se entera, y el mismo día en que se entera no lo desaprueba, serán firmes sus votos, y los compromisos que adquirió serán válidos.

[[numbers-30-9]]
^9^ Pero si el día en que se entera su marido, lo desaprueba, anula el voto que la obligaba y el compromiso que inconsideradamente contrajeron sus labios. Yahveh no se lo tendrá en cuenta.

[[numbers-30-10]]
^10^ El voto de una mujer viuda o repudiada, y todos los compromisos contraídos por ella, serán firmes.

[[numbers-30-11]]
^11^ Si una mujer ha hecho votos en casa de su marido, o se ha comprometido con juramento,

[[numbers-30-12]]
^12^ y se entera su marido y no le dice nada, no lo desaprueba, serán firmes todos sus votos, y todo compromiso que haya adquirido será firme.

[[numbers-30-13]]
^13^ Pero si su marido se los anula el mismo día en que se entera, no será firme nada de lo que ha salido de sus labios, sea voto o compromiso. Yahveh no se lo tendrá en cuenta, porque su marido se los anuló.

[[numbers-30-14]]
^14^ Cualquier voto o compromiso jurado que grava a la mujer, puede ratificarlo o anularlo el marido.

[[numbers-30-15]]
^15^ Si no le dice nada su marido para el día siguiente, es que confirma cualquier voto o compromiso que tenga; los confirma por no haberle dicho nada el día que se enteró.

[[numbers-30-16]]
^16^ Pero si los anula más tarde, cargará él con la falta de ella».

[[numbers-30-17]]
^17^ Estos son los preceptos que Yahveh dio a Moisés acerca de las relaciones entre marido y mujer, y entre el padre y la hija que, durante su juventud, vive todavía en casa de su padre.
[[numbers-31]]
== Capítulo 31

[[numbers-31-1]]
^1^ Habló Yahveh a Moisés y le dijo:

[[numbers-31-2]]
^2^ «Haz que los israelitas tomen venganza de los madianitas. Luego irás a reunirte con tu parentela».

[[numbers-31-3]]
^3^ Moisés habló al pueblo y le dijo: «Que se armen algunos de vosotros para la guerra de Yahveh contra Madián, para tomar de Madián la venganza de Yahveh.

[[numbers-31-4]]
^4^ Pondréis sobre las armas mil de cada tribu, de todas las tribus de Israel».

[[numbers-31-5]]
^5^ Los millares de Israel suministraron, a razón de mil por cada tribu, 12.000 hombres armados para la guerra.

[[numbers-31-6]]
^6^ Moisés envió al combate mil por cada tribu, y con ellos a Pinjás, hijo del sacerdote Eleazar, que llevaba en su mano los objetos sagrados y las trompetas del clamoreo.

[[numbers-31-7]]
^7^ Atacaron a Madián como había mandado Yahveh a Moisés y mataron a todos los varones.

[[numbers-31-8]]
^8^ Mataron también a los reyes de Madián: Eví, Réquem, Sur, Jur y Rebá, cinco reyes madianitas; y a Balaam, hijo de Beor, lo mataron a filo de espada.

[[numbers-31-9]]
^9^ Los israelitas hicieron cautivas a las mujeres de Madián y a sus niños y saquearon su ganado, sus rebaños, y todos sus bienes.

[[numbers-31-10]]
^10^ Dieron fuego a todas las ciudades en que habitaban y a todos sus campamentos.

[[numbers-31-11]]
^11^ Reunieron todo el botín que habían capturado, hombres y bestias,

[[numbers-31-12]]
^12^ y llevaron los cautivos, la presa y el botín ante Moisés, ante el sacerdote Eleazar y ante toda la comunidad de los israelitas, al campamento, en las Estepas de Moab, que están cerca del Jordán, a la altura de Jericó.

[[numbers-31-13]]
^13^ Moisés, el sacerdote Eleazar y todos los principales de la comunidad salieron a su encuentro hasta fuera del campamento.

[[numbers-31-14]]
^14^ Moisés se encolerizó contra los jefes de las tropas, jefes de millar y jefes de cien, que volvían de la expedición guerrera.

[[numbers-31-15]]
^15^ Les dijo Moisés: «¿Pero habéis dejado con vida a todas las mujeres?

[[numbers-31-16]]
^16^ Precisamente ellas fueron las que indujeron a prevaricar contra Yahveh a los israelitas, siguiendo el consejo de Balaam, cuando lo de Peor; por eso azotó la plaga a la comunidad de Yahveh.

[[numbers-31-17]]
^17^ Matad, pues, a todos los niños varones. Y a toda mujer que haya conocido varón, que haya dormido con varón, matadla también.

[[numbers-31-18]]
^18^ Pero dejad con vida para vosotros a todas las muchachas que no hayan dormido con varón.

[[numbers-31-19]]
^19^ Y vosotros, todos los que hayáis matado a alguno y todos los que hayaís tocado a algún muerto, acampad fuera del campamento siete días. Purificaos vosotros y vuestros cautivos, el día tercero y el día séptimo.

[[numbers-31-20]]
^20^ Purificad también todos los vestidos, todos los objetos de cuero, todo tejido de pelo de cabra y todo objeto de madera».

[[numbers-31-21]]
^21^ Dijo el sacerdote Eleazar a los hombres de la tropa que habían ido a la guerra: «Este es el precepto de la Ley que ordenó Yahveh a Moisés.

[[numbers-31-22]]
^22^ El oro, la plata, el bronce, el hierro, el estaño y el plomo,

[[numbers-31-23]]
^23^ todo lo que puede pasar por el fuego, lo pasaréis por el fuego y quedará puro. Pero será purificado con las aguas lustrales. Pero todo lo que no pueda pasar por el fuego lo pasaréis por las aguas».

[[numbers-31-24]]
^24^ Lavaréis vuestros vestidos el día séptimo y quedaréis puros. Luego podréis entrar en el campamento.

[[numbers-31-25]]
^25^ Habló Yahveh a Moisés y le dijo:

[[numbers-31-26]]
^26^ «Sacad la cuenta, tú, el sacerdote Eleazar y los principales de las familias de la comunidad, del botín y de los cautivos, hombres y bestias.

[[numbers-31-27]]
^27^ Luego repartirás el botín, la mitad para los combatientes que fueron a la guerra y la otra mitad para toda la comunidad.

[[numbers-31-28]]
^28^ Reservarás para Yahveh, de la parte de los combatientes que fueron a la guerra, uno por cada quinientos, sean hombres, bueyes, asnos u ovejas.

[[numbers-31-29]]
^29^ Lo tomarás de la mitad que les corresponde y se lo darás al sacerdote Eleazar, como reserva para Yahveh.

[[numbers-31-30]]
^30^ Y de la mitad de los israelitas, uno por cada cincuenta, sean hombres, bueyes, asnos u ovejas, cualquier clase de bestias, y se lo darás a los levitas, que están encargados del ministerio de la Morada de Yahveh.

[[numbers-31-31]]
^31^ Moisés y el sacerdote Eleazar hicieron como había mandado Yahveh a Moisés.

[[numbers-31-32]]
^32^ Fue el botín, el remanente de lo que la gente de guerra había saqueado: 675.000 cabezas de ganado lanar,

[[numbers-31-33]]
^33^ 72.000 de vacuno

[[numbers-31-34]]
^34^ y 61.000 de ganado asnal.

[[numbers-31-35]]
^35^ En cuanto a las personas, las mujeres que no habían dormido con varón eran, en total, 32.000.

[[numbers-31-36]]
^36^ La mitad correspondiente a los que fueron al combate: 337.500 cabezas de ganado lanar,

[[numbers-31-37]]
^37^ siendo la parte de Yahveh de ganado lanar, 675 cabezas;

[[numbers-31-38]]
^38^ 36.000 de vacuno, siendo la parte de Yahveh 72,

[[numbers-31-39]]
^39^ 30.500 de asnal, siendo la parte de Yahveh 61.

[[numbers-31-40]]
^40^ Las personas eran 16.000, correspondiendo a Yahveh, 32.

[[numbers-31-41]]
^41^ Moisés dio al sacerdote Eleazar la reserva de Yahveh, como había ordenado Yahveh a Moisés.

[[numbers-31-42]]
^42^ La mitad perteneciente a los israelitas, que había separado Moisés de la de los combatientes,

[[numbers-31-43]]
^43^ esta mitad correspondiente a la comunidad era de 337.500 cabezas de ganado lanar;

[[numbers-31-44]]
^44^ 36.000 de vacuno;

[[numbers-31-45]]
^45^ 30.500 de asnal,

[[numbers-31-46]]
^46^ y 16.000 personas.

[[numbers-31-47]]
^47^ Tomó Moisés de la mitad de los israelitas, a razón de uno por cincuenta, hombres y bestias, y se los dio a los levitas, que se encargan del ministerio de la Morada de Yahveh, como había ordenado Yahveh a Moisés.

[[numbers-31-48]]
^48^ Se presentaron ante Moisés los jefes de las tropas de Israel que habían ido a la guerra, jefes de millar y jefes de cien,

[[numbers-31-49]]
^49^ y dijeron a Moisés: «Tus siervos han sacado la cuenta de los combatientes que tenían a sus órdenes, y no falta ni uno.

[[numbers-31-50]]
^50^ Por eso traemos de ofrenda a Yahveh lo que cada uno de nosotros ha encontrado en objetos de oro, brazaletes, ajorcas, anillos, arracadas y collares, para hacer expiación por nosotros delante de Yahveh».

[[numbers-31-51]]
^51^ Moisés y el sacerdote Eleazar recibieron de ellos el oro y las joyas.

[[numbers-31-52]]
^52^ El total del oro de la reserva que reservaron para Yahveh, de parte de los jefes de millar y de cien, fue 16.750 siclos.

[[numbers-31-53]]
^53^ Los combatientes habían tomado cada uno su botín.

[[numbers-31-54]]
^54^ Pero Moisés y el sacerdote Eleazar recibieron el oro de los jefes de millar y de cien y lo llevaron a la Tienda del Encuentro, para que sirviera ante Yahveh de memorial en favor de los israelitas.
[[numbers-32]]
== Capítulo 32

[[numbers-32-1]]
^1^ Los hijos de Rubén y los hijos de Gad tenían muchos rebaños, muy grandes. Vieron que el país de Yazer y el país de Galaad eran tierra propia para el pastoreo,

[[numbers-32-2]]
^2^ y los hijos de Gad y los hijos de Rubén fueron y dijeron a Moisés, al sacerdote Eleazar y a los principales de la comunidad:

[[numbers-32-3]]
^3^ «Atarot, Dibón, Yazer, Nimrá, Jesbón, Elalé, Sebam, Nebo, y Meón,

[[numbers-32-4]]
^4^ el país que Yahveh conquistó delante de la comunidad de Israel es tierra de ganado, y tus siervos tienen ganado».

[[numbers-32-5]]
^5^ Y añadieron: «Si hemos hallado gracia a tus ojos, que se nos dé esta tierra a tus siervos en propiedad; no nos hagas pasar el Jordán».

[[numbers-32-6]]
^6^ Respondió Moisés a los hijos de Gad y a los hijos de Rubén: «¿Es que vuestros hermanos van a ir al combate y vosotros os vais a quedar aquí?

[[numbers-32-7]]
^7^ ¿Por qué os oponéis a que los israelitas pasen a la tierra que les ha dado Yahveh?

[[numbers-32-8]]
^8^ Así hicieron ya vuestros padres, cuando los mandé de Cadés Barnea a ver la tierra:

[[numbers-32-9]]
^9^ subieron al valle de Eskol, vieron la tierra e impidieron que los israelitas entrasen en la tierra que les había dado Yahveh.

[[numbers-32-10]]
^10^ Por eso se encendió la ira de Yahveh aquel día y juró diciendo:

[[numbers-32-11]]
^11^ “Nunca verán los hombres que salieron de Egipto, de veinte años para arriba, la tierra que prometí con juramento a Abraham, a Isaac y a Jacob..., porque no me han sido fieles,

[[numbers-32-12]]
^12^ excepto Caleb, hijo de Yefunné el quenizeo, y Josué, hijo de Nun, que fueron fieles a Yahveh.”

[[numbers-32-13]]
^13^ Se encendió la ira de Yahveh contra Israel y los hizo andar errantes por el desierto durante cuarenta años, hasta que se acabó toda aquella generación que había obrado mal a los ojos de Yahveh.

[[numbers-32-14]]
^14^ ¡Y ahora vosotros os alzáis a imitación de vuestros padres, comos retoño de hombres pecadores, para atizar más el fuego de la ira de Yahveh contra Israel!

[[numbers-32-15]]
^15^ Si os apartáis de él, volverá a retenernos en el desierto, y acarrearéis el desastre a todo este pueblo».

[[numbers-32-16]]
^16^ Entonces se acercaron a Moisés y le dijeron: «Podemos construir aquí rediles para nuestras ovejas y ciudades para nuestros niños.

[[numbers-32-17]]
^17^ Pero nosotros tomaremos las armas a la cabeza de los israelitas, hasta que los introduzcamos en sus lugares, mientras que nuestros hijos de quedarán en las plazas fuertes, al abrigo de los habitantes del país.

[[numbers-32-18]]
^18^ No volveremos a nuestras casas hasta que los israelitas se posesionen cada uno de su herencia.

[[numbers-32-19]]
^19^ Que nosotros no tendremos herencia con ellos al otro lado del Jordán, pues nuestra herencia nos ha tocado del lado oriental del Jordán».

[[numbers-32-20]]
^20^ Moisés les dijo: «Si hacéis lo que habéis dicho, si os armáis para combatir delante de Yahveh,

[[numbers-32-21]]
^21^ y todos vuestros combatientes pasan el Jordán delante de Yahveh, hasta que arroje a sus enemigos ante vosotros,

[[numbers-32-22]]
^22^ y la tierra es ocupada delante de Yahveh, podéis volver después y quedaréis exentos de culpa ante Yahveh y ante Israel. Esta tierra os pertenecerá en propiedad delante de Yahveh.

[[numbers-32-23]]
^23^ Pero si no lo hacéis así, habréis pecado contra Yahveh, y sabed que vuestro pecado os saldrá al encuentro.

[[numbers-32-24]]
^24^ Construíos ciudades para vuestros niños, y rediles para vuestros rebaños; pero haced lo que habéis prometido».

[[numbers-32-25]]
^25^ Dijeron los hijos de Gad y los hijos de Rubén a Moisés: «Tus siervos harán como mi Señor manda.

[[numbers-32-26]]
^26^ Nuestros hijos, nuestras mujeres, nuestros rebaños y todo nuestro ganado, se quedarán aquí en las ciudades de Galaad.

[[numbers-32-27]]
^27^ Pero tus siervos, todos los que llevan armas, pasarán delante de Yahveh, para ir a la guerra, como dice mi Señor».

[[numbers-32-28]]
^28^ Moisés dio orden al sacerdote Eleazar, a Josué, hijo de Nun, y a los jefes de las casas paternas de las tribus de los israelitas,

[[numbers-32-29]]
^29^ y les dijo Moisés: «Si los hijos de Gad y los hijos de Rubén, todos los que llevan armas, pasan con vosotros el Jordán, para combatir delante de Yahveh, y la tierra queda dominada por vosotros, les daréis el país de Galaad en propiedad.

[[numbers-32-30]]
^30^ Pero si los que llevan armas no pasan con vosotros, tendrán su herencia entre vosotros en el país de Canaán».

[[numbers-32-31]]
^31^ Respondieron los hijos de Gad y los hijos de Rubén: «Lo que ha hablado Yahveh a tus siervos, eso haremos.

[[numbers-32-32]]
^32^ Nosotros pasaremos armados delante de Yahveh al país de Canaán; pero danos la propiedad de nuestra herencia a este lado del Jordán».

[[numbers-32-33]]
^33^ Moisés dio a los hijos de Gad, a los hijos de Rubén y a la media tribu de Manasés, hijo de José, el reino de Sijón, rey de los amorreos, y el reino de Og, rey de Basán; el país con las ciudades comprendidas en sus fronteras y las ciudades colindantes.

[[numbers-32-34]]
^34^ Los hijos de Rubén construyeron las plazas fuertes de Dibón, Atarot y Aroer,

[[numbers-32-35]]
^35^ Atrot Sofán, Yazer, Yogbohá,

[[numbers-32-36]]
^36^ Bet Nimrá, Bet Harán, y rediles para los rebaños.

[[numbers-32-37]]
^37^ Los hijos de Rubén construyeron Jesbón, Elalé, Quiryatáyim,

[[numbers-32-38]]
^38^ Nebo, Baal Meón, cambiadas de nombre, y Sibmá. Y pusieron nombres a las ciudades que construyeron.

[[numbers-32-39]]
^39^ Los hijos de Makir, hijo de Manasés, fueron a Galaad, la conquistaron y expulsaron a los amorreos que habitaban allí.

[[numbers-32-40]]
^40^ Moisés dio Galaad a Makir, hijo de Manasés, que se estableció allí.

[[numbers-32-41]]
^41^ Yaír, hijo de Manasés, fue y se apoderó de los aduares de ellos y los llamó Aduares de Yaír.

[[numbers-32-42]]
^42^ Nóbaj fue y se apoderó de Quenat y de sus filiales, y le puso su propio nombre Nóbaj.
[[numbers-33]]
== Capítulo 33

[[numbers-33-1]]
^1^ Estas son las etapas de los israelitas, que salieron de Egipto por cuerpos de ejército, a las órdenes de Moisés y Aarón.

[[numbers-33-2]]
^2^ Moisés, por orden de Yahveh, escribió los puntos de donde partían, etapa por etapa. Estas fueron sus etapas, con indicación de los puntos de partida.

[[numbers-33-3]]
^3^ Partieron de Ramsés el mes primero. El día quince del mes primero, al día siguiente de la Pascua, salieron los israelitas, la mano en alto, en presencia de todos los egipcios.

[[numbers-33-4]]
^4^ Los egipcios estaban enterrando a los suyos que habían sido heridos por Yahveh, a todos los primogénitos; Yahveh había hecho justicia de sus dioses.

[[numbers-33-5]]
^5^ Partieron los israelitas de Ramsés y acamparon en Sukkot.

[[numbers-33-6]]
^6^ Partieron de Sukkot y acamparon en Etam, que está en el extremo del desierto.

[[numbers-33-7]]
^7^ Partieron de Etam y se detuvieron en Pi Hajirot, que está frente a Baal Sefón y acamparon delante de Migdol.

[[numbers-33-8]]
^8^ Partieron de Pi Hajirot y pasaron por medio del mar hasta el desierto. Anduvieron tres días de camino por el desierto de Etam y acamparon en Mará.

[[numbers-33-9]]
^9^ Partieron de Mará y llegaron a Elim. En Elim había doce fuentes de agua y setenta palmeras; allí acamparon.

[[numbers-33-10]]
^10^ Partieron de Elim y acamparon cerca del mar de Suf.

[[numbers-33-11]]
^11^ Partieron del mar de Suf y acamparon en el desierto de Sin.

[[numbers-33-12]]
^12^ Partieron del desierto de Sin y acamparon en Dofcá.

[[numbers-33-13]]
^13^ Partieron de Dofcá y acamparon en Alús.

[[numbers-33-14]]
^14^ Partieron de Alús y acamparon en Refidim, pero no había allí agua para que bebiera la gente.

[[numbers-33-15]]
^15^ Partieron de Refidim y acamparon en el desierto del Sinaí.

[[numbers-33-16]]
^16^ Partieron del desierto del Sinaí y acamparon en Quibrot Hattaavá.

[[numbers-33-17]]
^17^ Partieron de Quibrot Hattaavá y acamparon en Jaserot.

[[numbers-33-18]]
^18^ Partieron de Jaserot y acamparon en Ritmá.

[[numbers-33-19]]
^19^ Partieron de Ritmá y acamparon en Rimmón Peres.

[[numbers-33-20]]
^20^ Partieron de Rimmón Peres y acamparon en Libná.

[[numbers-33-21]]
^21^ Partieron de Libná y acamparon en Rissá.

[[numbers-33-22]]
^22^ Partieron de Rissá y acamparon en Quehelatá.

[[numbers-33-23]]
^23^ Partieron de Quehelatá y acamparon en el monte Séfer.

[[numbers-33-24]]
^24^ Partieron del monte Séfer y acamparon en Jaradá.

[[numbers-33-25]]
^25^ Partieron de Jaradá y acamparon en Maqhelot.

[[numbers-33-26]]
^26^ Partieron de Maqhelot y acamparon en Tájat.

[[numbers-33-27]]
^27^ Partieron de Tájat y acamparon en Táraj.

[[numbers-33-28]]
^28^ Partieron de Táraj y acamparon en Mitcá.

[[numbers-33-29]]
^29^ Partieron de Mitcá y acamparon en Jasmoná.

[[numbers-33-30]]
^30^ Partieron de Jasmona y acamparon en Moserot.

[[numbers-33-31]]
^31^ Partieron de Moserot y acamparon en Bene Yaacán.

[[numbers-33-32]]
^32^ Partieron de Bene Yaacán y acamparon en Jor Haguidgad.

[[numbers-33-33]]
^33^ Partieron de Jor Haguidgad y acamparon en Yotbatá.

[[numbers-33-34]]
^34^ Partieron de Yotbatá y acamparon en Abroná.

[[numbers-33-35]]
^35^ Partieron de Abroná y acamparon en Esyón Guéber.

[[numbers-33-36]]
^36^ Partieron de Esyón Guéber y acamparon en el desierto de Sin, es decir, en Cadés.

[[numbers-33-37]]
^37^ Partieron de Cadés y acamparon en Hor de la Montaña, en la frontera del país de Edom.

[[numbers-33-38]]
^38^ El sacerdote Aarón subió a Hor de la Montaña, según la orden de Yahveh, y murió allí, el año cuarenta de la salida de los israelitas de Egipto, el mes quinto, el primero del mes.

[[numbers-33-39]]
^39^ Tenía Aarón 123 años cuando murió en Hor de la Montaña.

[[numbers-33-40]]
^40^ El rey cananeo de Arad, que habitaba en el Négueb, en el país de Canaán, se enteró de que llegaban los israelitas.

[[numbers-33-41]]
^41^ Partieron de Hor de la Montaña y acamparon en Salmoná.

[[numbers-33-42]]
^42^ Partieron de Salmoná y acamparon en Punón.

[[numbers-33-43]]
^43^ Partieron de Punón y acamparon en Obot.

[[numbers-33-44]]
^44^ Partieron de Obot y acamparon en Iyyé Haabarim, en la frontera de Moab.

[[numbers-33-45]]
^45^ Partieron de Iyyim, y acamparon en Dibón Gad.

[[numbers-33-46]]
^46^ Partieron de Dibón Gad y acamparon en Almón Diblatáyim.

[[numbers-33-47]]
^47^ Partieron de Almón Diblatáyim, y acamparon en los montes de Abarim, frente al Nebó.

[[numbers-33-48]]
^48^ partieron de los montes de Abarim y acamparon en las Estepas de Moab, cerca del Jordán, a la altura de Jericó.

[[numbers-33-49]]
^49^ Acamparon cerca del Jordán entre Bet Hayesimot y Abel Hassittim en las Estepas de Moab.

[[numbers-33-50]]
^50^ Yahveh habló a Moisés en las Estepas de Moab, cerca del Jordán, a la altura de Jericó, y le dijo:

[[numbers-33-51]]
^51^ «Habla a los israelitas y diles: Cuando paséis el Jordán hacia el país de Canaán,

[[numbers-33-52]]
^52^ arrojaréis delante de vosotros a todos los habitantes del país. Destruiréis todas sus imágenes pintadas, destruiréis sus estatuas de fundición, saquearéis todos sus altos.

[[numbers-33-53]]
^53^ Os apoderaréis de la tierra y habitaréis en ella, pues os doy a vosotros todo el país en propiedad.

[[numbers-33-54]]
^54^ Repartiréis la tierra a suertes entre vuestros clanes. Al grande le aumentaréis la herencia y al pequeño se la reduciréis. Donde le caiga a cada uno la suerte, allí será su propiedad. Haréis el reparto por tribus paternas.

[[numbers-33-55]]
^55^ Pero si no expulsáis delante de vosotros a los habitantes del país, los que dejéis se os convertirán en espinas de vuestros ojos y en aguijones de vuestros costados y os oprimirán en el país en que vais a habitar.

[[numbers-33-56]]
^56^ Y yo os trataré a vosotros en la forma en que había pensado tratarles a ellos».
[[numbers-34]]
== Capítulo 34

[[numbers-34-1]]
^1^ Habló Yahveh a Moisés y le dijo:

[[numbers-34-2]]
^2^ «Da esta orden a los israelitas: Cuando entréis en el país de Canaán, éste será el territorio que os caerá en herencia: el país de Canaán con todas sus fronteras.

[[numbers-34-3]]
^3^ Por el sur, os pertenecerá desde el desierto de Sin, siguiendo el límite de Edom. Vuestra frontera meridional empezará por el oriente en la extremidad del mar de la Sal.

[[numbers-34-4]]
^4^ Torcerá vuestra frontera por el sur hacia la subida de los Escorpiones, pasará por Sin y terminará por el sur en Cadés Barnea. Luego irá hacia Jasar Addar y pasará por Asmón.

[[numbers-34-5]]
^5^ Torcerá la frontera de Asmón hacia el Torrente de Egipto y acabará en el Mar.

[[numbers-34-6]]
^6^ Vuestra frontera occidental será el mar Grande. Esta frontera será vuestro límite al oeste.

[[numbers-34-7]]
^7^ Vuestra frontera por el norte será la siguiente: Desde el mar Grande trazaréis el límite hasta Hor de la Montaña.

[[numbers-34-8]]
^8^ De Hor de la Montaña, trazaréis el límite hasta la Entrada de Jamat, y vendrá a salir la frontera a Sedad.

[[numbers-34-9]]
^9^ Seguirá luego la frontera hacia Zifrón y terminará en Jasar Enán. Esa será vuestra frontera septentrional.

[[numbers-34-10]]
^10^ Luego trazaréis vuestra frontera oriental desde Jasar Enán hasta Sefam.

[[numbers-34-11]]
^11^ La frontera bajará de Sefam hacia Arbel, al oriente de Ayín. Seguirá bajando la frontera, y, tocando la orilla del mar de Kinnéret por el oriente,

[[numbers-34-12]]
^12^ bajará al Jordán y vendrá a dar en el mar de la Sal. Esa será vuestra tierra con las fronteras que la circunscriben».

[[numbers-34-13]]
^13^ Moisés dio esta orden a los israelitas: «Este es el país que habéis de repartir a suertes, el que Yahveh mandó dar a las nueve tribus y a la mitad de la otra,

[[numbers-34-14]]
^14^ pues la tribu de los hijos de Rubén con sus distintas casas paternas y la tribu de los hijos de Gad con sus distintas casas paternas, han recibido ya su herencia; y la media tribu de Manasés ha recibido también su herencia.

[[numbers-34-15]]
^15^ Las dos tribus y la otra media tribu han recibido ya su herencia más allá del Jordán, a oriente de Jericó, hacia la salida del sol».

[[numbers-34-16]]
^16^ Habló Yahveh a Moisés y le dijo:

[[numbers-34-17]]
^17^ «Estos son los nombres de los que os han de repartir la tierra: el sacerdote Eleazar y Josué, hijo de Nun.

[[numbers-34-18]]
^18^ Elegiréis también un principal de cada tribu, para que repartan la tierra.

[[numbers-34-19]]
^19^ Estos son sus nombres: por la tribu de Judá, Caleb, hijo de Yefunné;

[[numbers-34-20]]
^20^ por la tribu de los hijos de Simeón, Semuel, hijo de Ammihud;

[[numbers-34-21]]
^21^ por la tribu de Benjamín, Elidad, hijo de Kislón;

[[numbers-34-22]]
^22^ por la tribu de los hijos de Dan, el principal Buquí, hijo de Yoglí;

[[numbers-34-23]]
^23^ por los hijos de José: por la tribu de los hijos de Manasés, el principal Janniel, hijo de Efod;

[[numbers-34-24]]
^24^ y por la tribu de los hijos de Efraím, el principal Quemuel, hijo de Siftán;

[[numbers-34-25]]
^25^ por la tribu de los hijos de Zabulón, el principal Elisafán, hijo de Parnak;

[[numbers-34-26]]
^26^ por la tribu de los hijos de Isacar, el principal Paltiel, hijo de Azzán;

[[numbers-34-27]]
^27^ por la tribu de los hijos de Aser, el principal Ajihud, hijo de Selomí;

[[numbers-34-28]]
^28^ por la tribu de los hijos de Neftalí, el principal Pedahel, hijo de Ammihud».

[[numbers-34-29]]
^29^ A éstos mandó Yahveh repartir la herencia a los israelitas en el país de Canaán.
[[numbers-35]]
== Capítulo 35

[[numbers-35-1]]
^1^ Habló Yahveh a Moisés en las Estepas de Moab, cerca del Jordán, a la altura de Jericó, y le dijo:

[[numbers-35-2]]
^2^ «Manda a los israelitas que cedan a los levitas, de la herencia que les pertenece, ciudades en las que puedan habitar y pastos de alrededor de las ciudades. Se las daréis a los levitas.

[[numbers-35-3]]
^3^ Esas ciudades serán su morada, y sus pastos serán para sus bestias, su ganado y todos sus animales.

[[numbers-35-4]]
^4^ Los pastos de las ciudades que cedáis a los levitas comprenderán mil codos alrededor de la ciudad, a contar desde las murallas.

[[numbers-35-5]]
^5^ Mediréis, fuera de la ciudad, 2000 codos a oriente, 2000 codos a mediodía, 2000 codos a occidente y 2000 codos al norte, teniendo la ciudad como centro. Estos serán los pastos de las ciudades.

[[numbers-35-6]]
^6^ Las ciudades que daréis a los levitas serán las seis de asilo, que cederéis para que se pueda refugiar en ellas el homicida, y además les daréis otras 42 ciudades.

[[numbers-35-7]]
^7^ El total de ciudades que daréis a los levitas será 48 ciudades, todas ellas con sus pastos.

[[numbers-35-8]]
^8^ Estas ciudades que cederéis de la propiedad de los israelitas, las tomaréis en mayor número del grande y en menor del pequeño; cada uno cederá ciudades a los levitas en proporción a la herencia que le haya tocado».

[[numbers-35-9]]
^9^ Habló Yahveh a Moisés y le dijo:

[[numbers-35-10]]
^10^ «Habla a los israelitas y diles: Cuando paséis el Jordán hacia la tierra de Canaán,

[[numbers-35-11]]
^11^ encontraréis ciudades de las que haréis ciudades de asilo: en ellas se refugiará el homicida, el que ha herido a un hombre por inadvertencia.

[[numbers-35-12]]
^12^ Esas ciudades os servirán de asilo contra el vengador; no debe morir el homicida hasta que comparezca ante la comunidad para ser juzgado.

[[numbers-35-13]]
^13^ De las ciudades que les cedáis, seis ciudades serán de asilo:

[[numbers-35-14]]
^14^ tres ciudades les cederéis al otro lado del Jordán y tres ciudades en el país de Canaán; serán ciudades de asilo.

[[numbers-35-15]]
^15^ Las seis ciudades serán de asilo tanto para los israelitas como para el forastero y para el huésped que viven en medio de vosotros, para que se pueda refugiar en ellas todo aquel que haya matado a un hombre por inadvertencia.

[[numbers-35-16]]
^16^ Pero si le ha herido con un instrumento de hierro, y muere, es un homicida. El homicida debe morir.

[[numbers-35-17]]
^17^ Si le hiere con una piedra como para causar la muerte con ella, y muere, es homicida. El homicida debe morir.

[[numbers-35-18]]
^18^ Si le hiere con un instrumento de madera como para matarle, y muere, es un homicida. El homicida debe morir.

[[numbers-35-19]]
^19^ El mismo vengador de la sangre dará muerte al homicida: en cuanto le encuentre, lo matará.

[[numbers-35-20]]
^20^ Si el homicida lo ha matado por odio, o le ha lanzado algo con intención, y muere,

[[numbers-35-21]]
^21^ o si por enemistad le ha golpeado con las manos, y muere, el que le ha herido tiene que morir: es un homicida. El vengador de la sangre dará muerte al homicida en cuanto le encuentre.

[[numbers-35-22]]
^22^ Pero si lo derribó de casualidad y sin enemistad, o le lanzó cualquier objeto sin ninguna mala intención,

[[numbers-35-23]]
^23^ o le tiró, sin verle, una piedra capaz de matarle, y le causó la muerte, sin que fuera su enemigo ni buscara su daño,

[[numbers-35-24]]
^24^ la comunidad juzgará entre el homicida y el vengador de la sangre según estas normas,

[[numbers-35-25]]
^25^ y salvará la comunidad al homicida de la mano del vengador de la sangre. Le hará volver la comunidad a la ciudad de asilo en la que se refugió y en ella vivirá hasta que muera el Sumo Sacerdote ungido con el óleo santo.

[[numbers-35-26]]
^26^ Pero si sale el homicida de los límites de la ciudad de asilo en que se ha refugiado,

[[numbers-35-27]]
^27^ y le encuentra el vengador de la sangre fuera del término de su ciudad de asilo, el vengador de la sangre podrá matar al homicida, sin ser responsable de su sangre,

[[numbers-35-28]]
^28^ porque aquél debía permanecer en la ciudad de asilo hasta la muerte del Sumo Sacerdote. Cuando muera el Sumo Sacerdote, el homicida podrá volver a la tierra de su propiedad.

[[numbers-35-29]]
^29^ Esto será norma de derecho para vosotros y para vuestros descendientes, dondequiera que habitéis.

[[numbers-35-30]]
^30^ En cualquier caso de homicidio, se matará al homicida según la declaración de los testigos; pero un solo testigo no bastará para condenar a muerte a un hombre.

[[numbers-35-31]]
^31^ No aceptaréis rescate por la vida de un homicida reo de muerte, pues debe morir.

[[numbers-35-32]]
^32^ Tampoco aceptaréis rescate por el que se ha refugiado en la ciudad de asilo y quiere volver a habitar en su tierra antes que muera el Sumo Sacerdote.

[[numbers-35-33]]
^33^ No profanaréis la tierra en que estáis, porque aquella sangre profana la tierra, y la tierra no queda expiada de la sangre derramada más que con la sangre del que la derramó.

[[numbers-35-34]]
^34^ No harás impura la tierra en que habitáis, porque yo habito en medio de ella, pues yo, Yahveh, tengo mi morada entre los israelitas.
[[numbers-36]]
== Capítulo 36

[[numbers-36-1]]
^1^ Los jefes de familia del clan de los hijos de Galaad, hijo de Makir, hijo de Manasés, uno de los clanes de los hijos de José, se presentaron y dijeron delante de Moisés y de los principales jefes de las casas paternas de los israelitas:

[[numbers-36-2]]
^2^ «Yahveh mandó a mi Señor que diera la tierra en herencia, por suertes, a los israelitas, y mi Señor recibió orden de Yahveh de dar la herencia de Selofjad, nuestro hermano, a sus hijas.

[[numbers-36-3]]
^3^ Si resulta que se casan con alguno de otra tribu israelita, será arrancada su parte de la herencia de nuestras familias. Aumentará entonces la herencia de la tribu a la que vayan a pertenecer, y se reducirá la herencia que nos tocó en suerte.

[[numbers-36-4]]
^4^ Y cuando llegue el jubileo para los israelitas, se añadirá la herencia de ellas a la herencia de la tribu a la que vayan a pertenecer y se restará su herencia de la herencia de la tribu de nuestros padres».

[[numbers-36-5]]
^5^ Moisés, según la orden de Yahveh, mandó lo siguiente a los israelitas: «Dice bien la tribu de los hijos de José.

[[numbers-36-6]]
^6^ Esto es lo que Yahveh ordenó acerca de las hijas de Selofjad: Tomarán por esposos a los que bien les parezca, con tal que se casen dentro de los clanes de la tribu de su padre.

[[numbers-36-7]]
^7^ La herencia de los israelitas no podrá pasar de una tribu a otra, sino que los israelitas estarán vinculados cada uno a la herencia de la tribu de sus padres.

[[numbers-36-8]]
^8^ Y toda hija que posea una herencia en una de las tribus de los israelitas se casará con uno de un clan de la tribu de su padre para que cada uno de los israelitas posea la herencia de sus padres.

[[numbers-36-9]]
^9^ No podrá pasar una herencia de una tribu a otra. Cada una de las tribus de los israelitas quedará vinculada a su heredad».

[[numbers-36-10]]
^10^ Tal como había mandado Yahveh a Moisés, así hicieron las hijas de Selofjad.

[[numbers-36-11]]
^11^ Majlá, Tirsá, Joglá, Milká y Noá, las hijas de Selofjad, se casaron con los hijos de sus tíos paternos.

[[numbers-36-12]]
^12^ Tomaron marido de los clanes de los hijos de Manasés, hijo de José, y así su herencia fue para la tribu del clan de su padre.

[[numbers-36-13]]
^13^ Estas son las órdenes y normas que dio Yahveh, por medio de Moisés, a los israelitas, en las Estepas de Moab, cerca del Jordán, a la altura de Jericó.
