[[joshua]]
= Josué

[[joshua-1]]
== Capítulo 1

[[joshua-1-1]]
^1^ Sucedió después de la muerte de Moisés, siervo de Yahveh, que habló Yahveh a Josué, hijo de Nun, y ayudante de Moisés, y le dijo:

[[joshua-1-2]]
^2^ «Moisés, mi siervo, ha muerto; arriba, pues; pasa ese Jordán, tú con todo este pueblo, hacia la tierra que yo les doy (a los israelitas).

[[joshua-1-3]]
^3^ Os doy todo lugar que sea hollado por la planta de vuestros pies, según declaré a Moisés.

[[joshua-1-4]]
^4^ Desde el desierto y el Líbano hasta el Río grande, el Eufrates, (toda la tierra de los hititas) y hasta el mar Grande de poniente, será vuestro territorio.

[[joshua-1-5]]
^5^ Nadie podrá mantenerse delante de ti en todos los días de tu vida: lo mismo que estuve con Moisés estaré contigo; no te dejaré ni te abandonaré.

[[joshua-1-6]]
^6^ «Sé valiente y firme, porque tú vas a dar a este pueblo la posesión del país que juré dar a sus padres.

[[joshua-1-7]]
^7^ Sé, pues, valiente y muy firme, teniendo cuidado de cumplir toda la Ley que te dio mi siervo Moisés. No te apartes de ella ni a la derecha ni a la izquierda, para que tengas éxito dondequiera que vayas.

[[joshua-1-8]]
^8^ No se aparte el libro de esta Ley de tus labios: medítalo día y noche; así procurarás obrar en todo conforme a lo que en él está escrito, y tendrás suerte y éxito en tus empresas.

[[joshua-1-9]]
^9^ ¿No te he mandado que seas valiente y firme? No tengas miedo ni te acobardes, porque Yahveh tu Dios estará contigo dondequiera que vayas».

[[joshua-1-10]]
^10^ Josué, pues, dio a los escribas del pueblo la orden siguiente:

[[joshua-1-11]]
^11^ «Pasad por medio del campamento y dad esta orden al pueblo: Haced provisiones, porque dentro de tres días pasaréis ese Jordán, para entrar a poseer la tierra que Yahveh vuestro Dios os da en posesión».

[[joshua-1-12]]
^12^ A los rubenitas, a los gaditas y a la medio tribu de Manasés les habló así:

[[joshua-1-13]]
^13^ «Recordad la orden que os dio Moisés, siervo de Yahveh: Yahveh vuestro Dios os ha concedido descanso, dándoos esta tierra.

[[joshua-1-14]]
^14^ Vuestras mujeres, vuestros pequeños y vuestros rebaños se quedarán en la tierra que os ha dado Moisés al otro lado del Jordán. Pero vosotros, todos los guerreros esforzados, pasaréis en orden de batalla al frente de vuestros hermanos y les ayudaréis

[[joshua-1-15]]
^15^ hasta que Yahveh conceda descanso a vuestros hermanos igual que a vosotros, y también ellos tomen posesión de la tierra que Yahveh vuestro Dios les da. Entonces volveréis al país que os pertenece, el que os dio Moisés, siervo de Yahveh, al lado oriental del Jordán».

[[joshua-1-16]]
^16^ Ellos respondieron a Josué: «Todo lo que nos has mandado, lo haremos; dondequiera que nos envíes, iremos.

[[joshua-1-17]]
^17^ Lo mismo que obedecimos en todo a Moisés, te obedeceremos a ti. Basta con que Yahveh tu Dios esté contigo como estuvo con Moisés.

[[joshua-1-18]]
^18^ A todo el que sea rebelde a tu voz y no obedezca tus órdenes, en cualquier cosa que le mandes, se le hará morir. Tú, sé valiente y firme».
[[joshua-2]]
== Capítulo 2

[[joshua-2-1]]
^1^ Josué, hijo de Nun, envió secretamente desde Sittim dos espías con esta orden: «Id y explorad el país y Jericó». Fueron y entraron en casa de una prostituta, llamada Rajab, y durmieron allí.

[[joshua-2-2]]
^2^ Se le dijo al rey de Jericó: «Mira que unos hombres israelitas han entrado aquí por la ncohe para explorar el país».

[[joshua-2-3]]
^3^ Entonces el rey de Jericó mandó decir a Rajab: «Haz salir a los hombres que han entrado donde ti - que han entrado a tu casa - porque han venido para explorar todo el país».

[[joshua-2-4]]
^4^ Pero la mujer tomó a los dos hombres y los escondió. Luego respondió: «Es verdad que esos hombres han venido a mi casa, pero yo no sabía de dónde eran.

[[joshua-2-5]]
^5^ Cuando se iba a cerrar la puerta por la noche, esos hombres salieron y no sé adónde han ido. Perseguidles aprisa, que los alcanzaréis».

[[joshua-2-6]]
^6^ Pero ella los había hecho subir al terrado y los había escondido entre unos haces de lino que tenía amontanados en el terrado.

[[joshua-2-7]]
^7^ Salieron algunos hombres en su persecución camino del Jordán, hacia los vados, y se cerró la puerta en cuanto los perseguidores salieron tras ellos.

[[joshua-2-8]]
^8^ Todavía ellos no se habían acostado cuando Rajab subió al terrado, donde ellos

[[joshua-2-9]]
^9^ y les dijo: «Ya sé que Yahveh os ha dado la tierra, que nos habéis aterrorizado y que todos los habitantes de esta región han temblado ante vosotros:

[[joshua-2-10]]
^10^ porque nos hemos enterado de cómo Yahveh secó las aguas del mar de Suf delante de vosotros a vuestra salida de Egipto, y lo que habéis hecho con los dos reyes amorreos del otro lado del Jordán, Sijón y Og, a quienes consagrasteis al anatema.

[[joshua-2-11]]
^11^ Al oírlo, ha desfallecido nuestro corazón y no se encuentra ya nadie con aliento en vuestra presencia, porque Yahveh vuestro Dios, es Dios arriba en los cielos y abajo en la tierra.

[[joshua-2-12]]
^12^ Juradme, pues, ahora por Yahveh, ya que os he tratado con bondad, que vosotros también trataréis con bondad a la casa de mi padre, y dadme una señal segura;

[[joshua-2-13]]
^13^ que respetaréis la vida de mi padre y de mi madre, de mis hermanos y hermanas, y de todos los suyos, y que libraréis nuestras vidas de la muerte».

[[joshua-2-14]]
^14^ Los hombres le respondieron: «Muramos nosotros en vez de vosotros, con tal de que no divulguéis nuestro asunto. Cuando Yahveh no haya entregado la tierra, te trataremos a ti con bondad y lealtad».

[[joshua-2-15]]
^15^ Ella los descolgó con una cuerda por la ventana, pues su casa estaba en la pared de la muralla y vivía en la misma muralla.

[[joshua-2-16]]
^16^ Les dijo: «Id hacia la montaña, para que no os encuentren los que os persiguen. Estad escondidos allí tres días hasta que vuelvan los perseguidores: después podéis seguir vuestro camino».

[[joshua-2-17]]
^17^ Los hombres le respondieron: «Nosotros quedaremos libres de ese juramento que nos has exigido.

[[joshua-2-18]]
^18^ Cuando estemos entrando en el país, atarás este cordón de hilo escarlata a la ventana por la que nos has descolgado, y reunirás junto a ti en casa a tu padre, a tu madre, a tus hermanos y a toda la familia de tu padre.

[[joshua-2-19]]
^19^ Si alguno sale fuera de las puertas de tu casa, caiga su sangre sobre su cabeza. Nosotros seremos inocentes. Pero la sangre de todos los que estén contigo en casa, caiga sobre nuestras cabezas, si alguien pone su mano sobre ellos.

[[joshua-2-20]]
^20^ Mas si divulgas nuestro asunto, quedaremos libres del juramento que nos has exigido».

[[joshua-2-21]]
^21^ Ella respondió: «Sea según vuestras palabras». Y los hizo marchar; ellos se fueron, y ella ató el cordón escarlata a la ventana.

[[joshua-2-22]]
^22^ Marcharon ellos y se metieron en el monte. Se quedaron allí tres días, hasta que regresaron los perseguidores. Estos los habían buscado por todo el camino, pero no los encontraron.

[[joshua-2-23]]
^23^ Entonces los dos hombres volvieron a bajar del monte, pasaron el río y fueron donde Josué, hijo de Nun, a quien contaron todo lo que les había ocurrido.

[[joshua-2-24]]
^24^ Dijeron a Josué: «Cierto que Yahveh ha puesto en nuestras manos todo el país; todos los habitantes del país tiemblan ya ante nosotros».
[[joshua-3]]
== Capítulo 3

[[joshua-3-1]]
^1^ Josué se levantó de mañana, partieron de Sittim y llegaron hasta el Jordán, él y todos los israelitas. Allí pernoctaron antes de pasar.

[[joshua-3-2]]
^2^ Al cabo de tres días, los escribas pasaron por medio del campamento

[[joshua-3-3]]
^3^ y dieron al pueblo esta orden: «Cuando veáis el arca de la alianza de Yahveh vuestro Dios y a los sacerdotes levitas que la llevan, partiréis del sitio donde estáis e iréis tras ella,

[[joshua-3-4]]
^4^ para que sepáis qué camino habéis de seguir, pues no habéis pasado nunca hasta ahora por este camino. Pero que haya entre vosotros y el arca una distancia de unos 2.000 codos: no os acerquéis».

[[joshua-3-5]]
^5^ Josúe dijo al pueblo: «Purificaos, porque mañana Yahveh va a obrar maravillas en medio de vosotros».

[[joshua-3-6]]
^6^ Y dijo Josué a los sacerdotes: «Tomad el arca de la alianza y pasad al frente del pueblo». Ellos tomaron el arca de la alianza y partieron al frente del pueblo.

[[joshua-3-7]]
^7^ Yahveh dijo a Josué: «Hoy mismo voy a empezar a engrandecerte a los ojos de todo Israel, para que sepan que, lo mismo que estuve con Moisés, estoy contigo.

[[joshua-3-8]]
^8^ Tú darás esta orden a los sacerdotes que llevan el arca de la alianza: “En cuanto lleguéis a la orilla del agua del Jordán, os pararéis en el Jordán.”»

[[joshua-3-9]]
^9^ Josué dijo a los Israelitas: «Acercaos y escuchad las palabras de Yahveh vuestro Dios».

[[joshua-3-10]]
^10^ Y dijo Josué: «En esto conoceréis que el Dios vivo está en medio de vosotros y que arrojará ciertamente de delante de vosotros al cananeo, al hitita, al jivita, al perizita, al guirgasita, al amorreo y al jebuseo.

[[joshua-3-11]]
^11^ He aquí que el arca de Yahveh, Señor de toda la tierra, va a pasar el Jordán delante de vosotros.

[[joshua-3-12]]
^12^ Escoged, pues, doce hombres de las tribus de Israel, un hombre por cada tibu.

[[joshua-3-13]]
^13^ En cuanto las plantas de los pies de los sacerdotes que llevan el arca de Yahveh, Señor de toda la tierra, pisen las aguas del Jordán, las aguas del Jordán las que vienen de arriba, quedarán cortadas y se pararán formando un solo bloque».

[[joshua-3-14]]
^14^ Cuando el pueblo partió de sus tiendas para pasar el Jordán, los sacerdotes llevaban el arca de la alianza a la cabeza del pueblo.

[[joshua-3-15]]
^15^ Y en cuanto los que llevaban el arca llegaron al Jordán, y los pies de los sacerdotes que llevaban el arca tocaron la orilla de las aguas, y el Jordán baja crecido hasta los bordes todo el tiempo de la siega,

[[joshua-3-16]]
^16^ las aguas que bajaban de arriba se detuvieron y formaron un solo bloque a gran distancia, en Adam, la ciudad que está al lado de Sartán, mientras que las que bajaban hacia el mar de la Arabá, o mar de la Sal, se separaron por completo, y el pueblo pasó frente a Jericó.

[[joshua-3-17]]
^17^ Los sacerdotes que llevaban el arca de la alianza de Yahveh se estuvieron a pie firme, en seco, en medio del Jordán, mientras que todo Israel pasaba en seco, hasta que toda la gente acabó de pasar el Jordán.
[[joshua-4]]
== Capítulo 4

[[joshua-4-1]]
^1^ Cuando todo el pueblo acabó de pasar el Jordán, Yahveh habló a Josué y le dijo:

[[joshua-4-2]]
^2^ «Escoged doce hombres del pueblo, un hombre por cada tribu,

[[joshua-4-3]]
^3^ y dadles esta orden: “Sacad de aquí, del medio del Jordán, doce piedras, que pasaréis con vosotros y depositaréis en el lugar donde paséis la noche.”»

[[joshua-4-4]]
^4^ Llamó Josué a los doce hombres que había elegido entre los israelitas, uno por cada tribu,

[[joshua-4-5]]
^5^ y les dijo: «Pasad delante del arca de Yahveh vuestro Dios, hasta el medio del Jordán, y cada uno de vosotros cargue sobre sus hombros una piedra, según el número de las tribus israelitas,

[[joshua-4-6]]
^6^ para que sea esto una señal en medio de vosotros; cuando el día de mañana vuestros hijos os pregunten: “¿Qué significan para vosotros estas piedras?”,

[[joshua-4-7]]
^7^ les diréis: “Es que las aguas del Jordán se separaron delante del arca de la alianza de Yahveh; cuando atravesó el Jordán, las aguas del Jordán se separaron. Estas piedras serán para los israelitas memorial para siempre.”

[[joshua-4-8]]
^8^ Así lo hicieron los israelitas, según las órdenes de Josué: sacaron doce piedras del medio del Jordán, según el número de las tribus israelitas, como había mandado Yahveh a Josué, las llevaron al lugar donde iban a pasar la noche y las depositaron allí.

[[joshua-4-9]]
^9^ Y Josué levantó doce piedras en medio del Jordán, donde habían pisado los pies de los sacerdotes portadores del arca de la alianza, y allí están todavía hoy.

[[joshua-4-10]]
^10^ Los sacerdotes portadores del arca estaban parados en medio del Jordán hasta que se cumpliera todo lo que Yahveh había mandado a Josué que dijera al pueblo (según todo lo que Moisés había ordenado a Josué); y el pueblo se apresuró a pasar.

[[joshua-4-11]]
^11^ En cuanto terminó de pasar todo el pueblo, pasó el arca de Yahveh, yendo los sacerdotes a la cabeza del pueblo.

[[joshua-4-12]]
^12^ Los rubenitas, los gaditas y la media tribu de Manasés pasaron en orden de batalla al frente de los israelitas, como les había dicho Moisés.

[[joshua-4-13]]
^13^ Pasaron unos 40.000 guerreros armados, dispuestos al combate, delante de Yahveh, hacia la llanura de Jericó.

[[joshua-4-14]]
^14^ Aquel día Yahveh engrandeció a Josué delante de todo Israel; y le respetaron a él como habían respetado a Moisés durante toda su vida.

[[joshua-4-15]]
^15^ Yahveh dijo a Josué:

[[joshua-4-16]]
^16^ «Manda a los sacerdotes que llevan el arca del Testimonio que salgan del Jordán».

[[joshua-4-17]]
^17^ Josué mandó a los sacerdotes: «Salid del Jordán».

[[joshua-4-18]]
^18^ Cuando los sacerdotes portadores del arca de la alianza de Yahveh salieron del Jordán, apenas las plantas de sus pies tocaron la orilla, las aguas del Jordán volvieron a su cauce y empezaron a correr como antes, por todas sus riberas.

[[joshua-4-19]]
^19^ El pueblo salió del Jordán el día diez del mes primero y acamparon en Guilgal al oriente de Jericó.

[[joshua-4-20]]
^20^ Las doce piedras que habían sacado del Jordán las erigió Josué en Guilgal.

[[joshua-4-21]]
^21^ Y dijo a los israelitas: «Cuando el día de mañana vuestros hijos pregunten a sus padres: “¿Qué significan estas piedras?”

[[joshua-4-22]]
^22^ se lo explicaréis a vuestros hijos diciendo: “A pie enjuto pasó Israel ese Jordán,

[[joshua-4-23]]
^23^ porque Yahveh vuestro Dios secó delante de vosotros las aguas del Jordán hasta que pasarais, lo mismo que había hecho Yahveh vuestro Dios con el mar de Suf, que secó delante de nosotros hasta que pasamos,

[[joshua-4-24]]
^24^ para que todos los pueblos de la tierra reconozcan lo fuerte que es la mano de Yahveh, y para que teman siempre a Yahveh vuestro Dios.”»
[[joshua-5]]
== Capítulo 5

[[joshua-5-1]]
^1^ Cuando oyeron todos los reyes de los amorreos que habitaban al otro lado del Jordán, al poniente, y todos los reyes de los cananeos que vivían hacia el mar, que Yahveh había secado las aguas del Jordán ante los israelitas hasta que pasaron, desfalleció su corazón y les faltó el aliento ante la presencia de los israelitas.

[[joshua-5-2]]
^2^ En aquel tiempo dijo Yahveh a Josué: «Hazte cuchillos de pedernal y vuelve a circuncidar (por segunda vez) a los israelitas».

[[joshua-5-3]]
^3^ Josué se hizo cuchillos de pedernal y circuncidó a los israelitas en el Collado de los Prepucios.

[[joshua-5-4]]
^4^ Por este motivo hizo Josué esta circuncisión: toda la población masculina salida de Egipto, los útiles para la guerra, había muerto en el desierto, por el camino, después de la salida de Egipto.

[[joshua-5-5]]
^5^ Estaba circuncidada toda la población que había salido, pero el pueblo nacido en el desierto, de camino, después de la salida de Egipto, no había sido circuncidado.

[[joshua-5-6]]
^6^ Porque durante cuarenta años anduvieron los israelitas por el desierto, hasta que pereció toda la nación, los hombres salidos de Egipto útiles para la guerra. No obedecieron a la voz de Yahveh y Yahveh les juró que no les dejaría ver la tierra que había prometido a sus padres que nos daría, tierra que mana leche y miel.

[[joshua-5-7]]
^7^ En su lugar puso a sus hijos y éstos son los que Josué circuncidó, porque eran incircuncisos, ya que no los habían circuncidado por el camino.

[[joshua-5-8]]
^8^ Cuando acabó de circuncidarse toda la gente, se quedaron donde estaban en el campamento hasta que se curaron.

[[joshua-5-9]]
^9^ Y dijo Yahveh a Josué: «Hoy os he quitado de encima el oprobio de Egipto». Por eso se llamó aquel lugar Guilgal, hasta el día de hoy.

[[joshua-5-10]]
^10^ Los israelitas acamparon en Guilgal y celebraron allí la Pascua el día catorce del mes, a la tarde, en los llanos de Jericó.

[[joshua-5-11]]
^11^ Al día siguiente de la Pascua comieron ya de los productos del país: panes ázimos y espigas tostadas, ese mismo día.

[[joshua-5-12]]
^12^ Y el maná cesó desde el día siguiente, en que empezaron a comer los productos del país. Los israelitas no tuvieron en adelante maná, y se alimentaron ya aquel año de los productos de la tierra de Canaán.

[[joshua-5-13]]
^13^ Sucedió que estando Josué cerca de Jericó, levantó los ojos y vio a un hombre plantado frente a él con una espada desnuda en la mano. Josué se adelantó hacia él y le dijo: «¿Eres de los nuestros o de nuestros enemigos?»

[[joshua-5-14]]
^14^ Respondió: «No, sino que soy el jefe del ejército de Yahveh. He venido ahora». Cayó Josué rostro en tierra, le adoró y dijo: «¿Qué dice mi Señor a su siervo?»

[[joshua-5-15]]
^15^ El jefe del ejército de Yahveh respondió a Josué: «Quítate las sandalias de tus pies, porque el lugar en que estás es sagrado». Así lo hizo Josué.
[[joshua-6]]
== Capítulo 6

[[joshua-6-1]]
^1^ Jericó estaba cerrada a cal y canto por mielo a los israelitas: nadie salía ni entraba.

[[joshua-6-2]]
^2^ Yahveh dijo a Josué: «Mira, yo pongo en tus manos a Jericó y a sus rey. Vosotros, valientes guerreros,

[[joshua-6-3]]
^3^ todos los hombres de guerra, rodearéis la ciudad, (dando una vuelta alrededor. Así harás durante seis días.

[[joshua-6-4]]
^4^ Siete sacerdotes llevarán las siete trompetas de cuerno de carnero delante del arca. El séptimo día daréis la vuelta a la ciudad siete veces y los sacerdotes tocarán las trompetas).

[[joshua-6-5]]
^5^ Cuando el cuerno de carnero suene (cuando oigáis la voz de la trompeta), todo el pueblo prorrumpirá en un gran clamoreo y el muro de la ciudad se vendrá abajo. Y el pueblo se lanzará al asalto cada uno por frente a sí».

[[joshua-6-6]]
^6^ Josué, hijo de Nun, llamó a los sacerdotes y les dijo: «Tomad el arca de la alianza y que siete sacerdotes lleven las trompetas de cuerno de carnero delante del arca de Yahveh».

[[joshua-6-7]]
^7^ Al pueblo le dijo: «Pasad y dad la vuelta a la ciudad y que la vanguardia pase delante del arca de Yahveh».

[[joshua-6-8]]
^8^ (Se hizo según la orden dada por Josué al pueblo). Siete sacerdotes llevando las siete trompetas de cuerno de carnero delante de Yahveh pasaron y tocaron las trompetas; el arca de la alianza de Yahveh iba tras ellos;

[[joshua-6-9]]
^9^ la vanguardia iba delante de los sacerdotes que tocaban las trompetas y la retaguardia marchaba detrás del arca. Según iban caminando, tocaban las trompetas.

[[joshua-6-10]]
^10^ Josué había dado esta orden al pueblo: «No gritéis, ni dejéis oír vuestras voces (que no salga ni una palabra de vuestra boca) hasta el día en que yo os diga: “Gritad.” Entonces gritaréis».

[[joshua-6-11]]
^11^ Hizo que el arca de Yahveh diera la vuelta a la ciudad (rodeándola una vez); luego volvieron al campamento, donde pasaron la noche.

[[joshua-6-12]]
^12^ Josué se levantó de mañana y los sacerdotes tomaron el arca de Yahveh.

[[joshua-6-13]]
^13^ Siete sacerdotes, llevando las siete trompetas de cuerno de carnero delante del arca de Yahveh, iban caminando y tocando las trompetas según caminaban. La vanguardia iba delante de ellos y la retaguardia detrás del arca de Yahveh, desfilando al son de las trompetas.

[[joshua-6-14]]
^14^ Dieron (el segundo día) una vuelta a la ciudad y volvieron al campamento. Se hizo lo mismo los seis días.

[[joshua-6-15]]
^15^ El séptimo día, se levantaron con el alba y dieron la vuelta a la ciudad (según el mismo rito) siete veces. (Sólo aquel día dieron la vuelta a la ciudad siete veces.)

[[joshua-6-16]]
^16^ La séptima vez, los sacerdotes tocaron la trompeta y Josué dijo al pueblo: «¡Lanzad el grito de guerra, porque Yahveh os ha entregado la ciudad!»

[[joshua-6-17]]
^17^ «La ciudad será consagrada como anatema a Yahveh con todo lo que haya en ella; únicamente, Rajab, la prostituta, quedará con vida, así como todos los que están con ella en su casa, por haber ocultado a los emisarios que enviamos.

[[joshua-6-18]]
^18^ Pero vosotros guardoos del anatema, no vayáis a quedaros, llevados de la codicia, con algo de lo que es anatema, porque convertiráis en anatema todo el campamento de Israel y le acarrearíais la desgracia.

[[joshua-6-19]]
^19^ Toda la plata y todo el oro, todos los objetos de bronce y de hierro, están consagrados a Yahveh: ingresarán en su tesoro».

[[joshua-6-20]]
^20^ El pueblo clamó y se tocaron las trompetas. Al escuchar el pueblo la voz de la trompeta, prorrumpió en gran clamor, y el muro se vino abajo. La gente escaló la ciudad, cada uno frente a sí, y se apoderaron de ella.

[[joshua-6-21]]
^21^ Consagraron al anatema todo lo que había en la ciudad, hombres y mujeres, jóvenes y viejos, bueyes, ovejas y asnos, a filo de espada.

[[joshua-6-22]]
^22^ Josué dijo a los dos hombres que habían explorado el país: «Entrad en la casa de la prostituta y haced salir de ella a esa mujer con todos los suyos, como se lo habéis jurado».

[[joshua-6-23]]
^23^ Los jóvenes espías fueron e hicieron salir a Rajab, a su padre, a su madre, a sus hermanos y a todos los suyos. También hicieron salir a todos los de su familia y los pusieron a salvo, fuera del campamento de Israel.

[[joshua-6-24]]
^24^ Prendieron fuego a la ciudad con todo lo que contenía. Sólo la plata, el oro y los objetos de bronce y de hierro los depositaron el el tesoro de la casa de Yahveh.

[[joshua-6-25]]
^25^ Pero a Rajab, la prostituta, así como a la casa de su padre y a todos los suyos, Josúe los conservó con vida. Ella se quedó en Israel hasta el día de hoy, por haber escondido a los emisarios que Josué había enviado a explorar Jericó.

[[joshua-6-26]]
^26^ En aquel tiempo Josué pronunció este juramento: ¡Maldito sea delante de Yahveh el hombre que se levante y reconstruya esta ciudad (de Jericó)! ¡Sobre su primogénito echará su cimiento y sobre su pequeño colocará las puertas!

[[joshua-6-27]]
^27^ Y Yahveh estuvo con Josué, cuya fama se extendió por toda la tierra.
[[joshua-7]]
== Capítulo 7

[[joshua-7-1]]
^1^ Pero los israelitas cometieron un delito en lo del anatema. Akán, hijo de Karmí, hijo de Zabdí, hijo de Zéraj, de la tribu de Judá, se quedó con algo del anatema, y la ira de Yahveh se encendió contra los israelitas.

[[joshua-7-2]]
^2^ Josué envió de Jericó a Ay, que está (junto a Bet Avén) al oriente de Betel, unos hombres, diciéndoles: «Subid a explorar el país». Los hombres subieron y exploraron Ay.

[[joshua-7-3]]
^3^ Volvieron donde Josué y le dijeron: «Que no suba toda la gente; para atacar a Ay basta con que suban dos o 3.000 hombres. No molestes a toda la gente haciéndoles subir hasta allí, porque ellos son pocos».

[[joshua-7-4]]
^4^ Subieron a Ay unos 3.000 hombres del pueblo, pero tuvieron que huir ante los hombres de Ay.

[[joshua-7-5]]
^5^ Los hombres de Ay les mataron como unos 36 hombres y los persiguieron más allá de la puerta hasta Sebarim, batiéndolos en la bajada. Entonces desfalleció el corazón del pueblo y se derritió como agua.

[[joshua-7-6]]
^6^ Josué desgarró sus vestidos, se postró rostro en tierra delante del arca de Yahveh hasta la tarde, junto con los ancianos de Israel, y todos esparcieron polvo sobre sus cabezas.

[[joshua-7-7]]
^7^ Dijo Josué: «¡Ah, Señor Yahveh! ¿Por qué has hecho pasar el Jordán a este pueblo, para entregarnos en manos de los amorreos y destruirnos? ¡Ojalá nos hubiésemos empeñado en establecernos al otro lado del Jordán!

[[joshua-7-8]]
^8^ ¡Perdón, Señor! ¿Qué puedo decir ahora que Israel ha vuelto la espalda a sus enemigos?

[[joshua-7-9]]
^9^ Se enterarán los cananeos y todos los habitantes del país: se aliarán contra nosotros y borrarán nuestro nombre de la tierra. ¿Que harás tú entonces por tu gran nombre?»

[[joshua-7-10]]
^10^ Yahveh respondió a Josué: «¡Arriba! ¡Vamos! ¿Por qué te estás así rostro en tierra?

[[joshua-7-11]]
^11^ Israel ha pecado, también ha violado la alianza que yo le había impuesto. Y hasta se han quedado con algo del anatema, y lo han robado, y lo han escondido y lo han puesto entre sus utensilios.

[[joshua-7-12]]
^12^ Los israelitas no podrán sostenerse ante sus enemigos; volverán la espalda ante sus enemigos, porque se han convertido en anatema. Yo no estaré ya con vosotros, si no hacéis desaparecer el anatema de en medio de vosotros.

[[joshua-7-13]]
^13^ Levántate, purifica al pueblo y diles: Purificaos para mañana, porque así dice Yahveh, el Dios de Israel: El anatema está dentro de ti, Israel; no podrás mantenerte delante de tus enemigos hasta que estirpéis el anatema de entre vosotros.

[[joshua-7-14]]
^14^ Os presentaréis, pues, mañana por la mañana, por tribus: la tribu que Yahveh designe por la suerte se presentará por clanes, el clan que Yahveh designe se presentará por familias, y la familia que Yahveh designe se presentará hombre por hombre.

[[joshua-7-15]]
^15^ El designado por la suerte en lo del anatema será entregado al fuego con todo lo que le pertenece, por haber violado la alianza de Yahveh y cometido una infamia en Israel».

[[joshua-7-16]]
^16^ Josué se levantó de mañana; mandó que se acercara Israel por tribus, y fue designada por la suerte la tribu de Judá.

[[joshua-7-17]]
^17^ Mandó que se acercaran los clanes de Judá, y fue designado por la suerte el clan de Zéraj. Mandó que se acercara el clan de Zéraj por familias, y fue designado por la suerte Zabdí.

[[joshua-7-18]]
^18^ Mandó que se acercara la familia de Zabdí, hombre por hombre, y fue designado por la suerte Akán, hijo de Karmí, hijo de Zabdí, hijo de Zéraj, de la tribu de Judá.

[[joshua-7-19]]
^19^ Dijo entonces Josué a Akán: «Hijo mío, da gloria a Yahveh, Dios de Israel y tribútale alabanza; declárame lo que has hecho, no me lo ocultes».

[[joshua-7-20]]
^20^ Akán respondió a Josué: «En verdad, yo soy el que ha pecado contra Yahveh, Dios de Israel; esto y esto es lo que he hecho:

[[joshua-7-21]]
^21^ Vi entre el botín un hermoso manto de Senaar, doscientos siclos de plata y un lingote de oro de cincuenta siclos de peso, me gustaron y me los guardé. Están escondidos en la tierra en medio de mi tienda, y la plata debajo».

[[joshua-7-22]]
^22^ Josué envió emisarios, que fueron corriendo a la tienda, y en efecto el manto estaba escondido en la tienda y la plata debajo.

[[joshua-7-23]]
^23^ Lo sacaron de la tienda y se lo llevaron a Josué y a todos los israelitas delante de Yahveh.

[[joshua-7-24]]
^24^ Entonces Josué tomó a Akán, hijo de Zéraj, con la plata, el manto y el lingote de oro, a sus hijos, sus hijas, su toro, su asno y su oveja, su tienda y todo lo suyo y los hizo subir al valle de Akor. Todo Israel le acompañaba.

[[joshua-7-25]]
^25^ Josué dijo: «¿Por qué nos has traído la desgracia? Que Yahveh te haga desgraciado en este día». Y todo Israel lo apedreó (y los quemaron en la hoguera y los apedrearon).

[[joshua-7-26]]
^26^ Levantaron sobre él un gran montón de piedras, que existe todavía hoy. Así Yahveh se calmó del furor de su cólera. Por eso se llama aquel lugar Valle de Akor hasta el día de hoy.
[[joshua-8]]
== Capítulo 8

[[joshua-8-1]]
^1^ Yahveh dijo entonces a Josué: «¡No tengas miedo ni te asustes! Toma contigo a toda la gente de guerra; levántate y sube contra Ay. Mira que entrego en tus manos al rey de Ay, a su pueblo, su ciudad y su territorio.

[[joshua-8-2]]
^2^ Harás con Ay y con su rey lo que has hecho con Jericó y con su rey. Pero como botín sólo tomaréis los despojos y el ganado. Pon una emboscada a espaldas de la ciudad».

[[joshua-8-3]]
^3^ Josué se levantó con toda la gente de guerra para marchar sobre Ay. Escogió Josué 30.000 guerreros valientes y les hizo salir de noche,

[[joshua-8-4]]
^4^ dándoles esta orden: «Mirad, vosotros vais a estar emboscados a espaldas de la ciudad, pero no os alejéis mucho de ella, y estad todos alerta.

[[joshua-8-5]]
^5^ Yo y toda la gente que me acompaña nos acercaremos a la ciudad y, cuando la gente de Ay salga a nuestro encuentro como la primera vez, huiremos ante ellos.

[[joshua-8-6]]
^6^ Saldrán tras de nosotros hasta que los alejemos de la ciudad, porque se dirán: “Huyen delante de nosotros como la primera vez.

[[joshua-8-7]]
^7^ Entonces vosotros saldréis de la emboscada y os apoderaréis de la ciudad; Yahveh, vuestro Dios, la pondrá en vuestras manos.

[[joshua-8-8]]
^8^ En cuanto toméis la ciudad la incendiaréis. Lo haréis según la orden de Yahveh. Mirad que os lo mando yo».

[[joshua-8-9]]
^9^ Los envió Josué y fueron al lugar de la emboscada, y se apostaron entre Betel y Ay, al occidente de Ay; Josué pasó aquella noche en medio de la gente.

[[joshua-8-10]]
^10^ Se levantó de mañana Josué, revistó la tropa y subió contra Ay, con los ancianos de Israel al frente de la tropa.

[[joshua-8-11]]
^11^ Toda la gente de guerra que estaba con él subió y se acercó hasta llegar ante la ciudad. Acamparon al norte de Ay. El valle quedaba entre ellos y la ciudad.

[[joshua-8-12]]
^12^ Tomó unos 5.000 hombres y tendió con ellos una emboscada entre Betel y Ay, al oeste de la ciudad.

[[joshua-8-13]]
^13^ Pero la tropa formó el grueso del campamento que estaba al norte de la ciudad, quedando emboscada al oeste de la ciudad. Josué pasó aquella noche en medio del valle.

[[joshua-8-14]]
^14^ En cuanto vio esto el rey de Ay, se dieron prisa, se levantaron temprano y salieron él y toda su gente a presentar batalla a Israel en la bajada, frente a la Arabá, sin saber que tenía una emboscada a espaldas de la ciudad.

[[joshua-8-15]]
^15^ Josué y todo Israel se hicieron los derrotados por ellos y huyeron camino del desierto.

[[joshua-8-16]]
^16^ Toda la gente que estaba en la ciudad se puso a dar grandes alaridos saliendo tras ellos y al perseguir a Josué, se alejaron de la ciudad.

[[joshua-8-17]]
^17^ No quedó un solo hombre en Ay (ni en Betel) que no saliera en persecución de Israel. Y dejaron la ciudad abierta por perseguir a Israel.

[[joshua-8-18]]
^18^ Yahveh dijo entonces a Josué: «Tiende hacia Ay el dardo que tienes en tu mano porque en tu mano te la entrego». Josué tiendió el dardo que tenía en la mano hacia la ciudad.

[[joshua-8-19]]
^19^ Tan pronto como extendió la mano, los emboscados surgieron rápidemente de su puesto, corrieron y entraron en la ciudad, se apoderaron de ella y a toda prisa la incendiaron.

[[joshua-8-20]]
^20^ Cuando los hombres de Ay volvieron la vista atrás y vieron la humareda que subía de la ciudad hacia el cielo, no tuvieron fuerza para huir por un lado o por otro. El pueblo que iba huyendo hacia el desierto se volvió contra los perseguidores.

[[joshua-8-21]]
^21^ Viendo Josué y todo Israel que los emboscados habían tomado la ciudad y que subía de ella una humareda, se volvieron y batieron a los hombres de Ay.

[[joshua-8-22]]
^22^ Los otros salieron de la ciudad a su encuentro, de modo que los hombres de Ay se encontraron en medio de los israelitas, unos por un lado y otros por otro. Estos los derrotaron hasta que no quedó superviviente ni fugitivo.

[[joshua-8-23]]
^23^ Pero al rey de Ay lo prendieron vivo y lo condujeron ante Josué.

[[joshua-8-24]]
^24^ Cuando Israel acabó de matar a todos los habitantes de Ay en el campo y en el desierto, hasta donde habían salido en su persecución, y todos ellos cayeron a filo de espada hasta no quedar uno, todo Israel volvió a Ay y pasó a su población a filo de espada.

[[joshua-8-25]]
^25^ El total de los que cayeron aquel día, hombres y mujeres, fue 12.000, todos los habitantes de Ay.

[[joshua-8-26]]
^26^ Josué no retiró la mano que tenía extendida con el dardo hasta que consagró al anatema a todos los habitantes de Ay.

[[joshua-8-27]]
^27^ Israel se repartió solamente el ganado y los despojos de dicha ciudad, según la orden que Yahveh había dado a Josué.

[[joshua-8-28]]
^28^ Josué incendió Ay y la convirtió para siempre en una ruina, en desolación hasta el día de hoy.

[[joshua-8-29]]
^29^ Al rey de Ay lo colgó de un árbol hasta la tarde; y a la puesta del sol ordenó Josué que bajaran el cadáver del árbol. Lo echaron luego a la entrada de la puerta de la ciudad y amontonaron sobre él un gran montón de piedras, que existe todavía hoy.

[[joshua-8-30]]
^30^ Entonces Josué construyó un altar a Yahveh, Dios de Israel, en el monte Ebal,

[[joshua-8-31]]
^31^ como había mandado Moisés, siervo de Yahveh, a los israelitas, según está escrito en el libro de la Ley de Moisés: un altar de piedras sin labrar, a las que no haya tocado el hierro. Ofrecieron sobre él holocaustos a Yahveh e inmolaron sacrificios de comunión.

[[joshua-8-32]]
^32^ Josué escribió allí mismo, sobre las piedras, una copia de la Ley que Moisés había escrito delante de los israelitas.

[[joshua-8-33]]
^33^ Y todo Israel, sus ancianos, sus escribas y sus jueces, de pie a los lados del arca, delante de los sacerdotes levitas que llevaban el arca de la alianza de Yahveh, todos, tanto forasteros como ciudadanos, se colocaron la mitad en la falda del monte Garizim y la otra mitad en la falda del monte Ebal, según la orden de Moisés, siervo de Yahveh, para bendecir por primera vez al pueblo de Israel.

[[joshua-8-34]]
^34^ Luego, Josué leyó todas las palabras de la Ley - la bendición y la maldición - a tenor de cuanto está escrito en el libro de la Ley.

[[joshua-8-35]]
^35^ No hubo ni una palabra de cuanto Moisés había mandado que no la leyera Josué en presencia de toda la asamblea de Israel, incluidas las mujeres, los niños y los forasteros que vivían en medio de ellos.
[[joshua-9]]
== Capítulo 9

[[joshua-9-1]]
^1^ En cuanto se enteraron todos los reyes que estaban de este lado del Jordán, en la Montaña, en la Tierra Baja, a lo largo de la costa del mar Grande hasta la región del Líbano, hititas, amorreos, cananeos, perizitas, jivitas y jebuseos,

[[joshua-9-2]]
^2^ se aliaron para combatir como un solo hombre contra Josué e Israel.

[[joshua-9-3]]
^3^ Pero los habitantes de Gabaón se enteraron de lo que había hecho Josué con Jericó y Ay,

[[joshua-9-4]]
^4^ y recurrieron también ellos a la astucia. Fueron y se proveyeron de víveres, tomaron alforjas viejas para sus asnos y odres de vino viejes, rotos y recosidos;

[[joshua-9-5]]
^5^ sandalias viejas y remendadas en sus pies y vestidos viejos. Todo el pan que llevaban para su alimento era seco y desmigado.

[[joshua-9-6]]
^6^ Fueron donde Josué, al campamento de Guilgal, y le dijeron a él y a los hombres de Israel: «Venimos de un país lejano: haced, pues, alianza con nosotros.

[[joshua-9-7]]
^7^ Los hombres de Israel respondieron a aquellos jivitas: «Acaso habitáis en medio de nosotros y entonces no podemos hacer alianza con vosotros».

[[joshua-9-8]]
^8^ Respondieron a Josué: «Somos tus siervos». Josué les dijo: «¿Quiénes sois vosotros y de dónde venís?»

[[joshua-9-9]]
^9^ Le respondieron: «De muy lejana tierra vienen tus siervos, por la fama de Yahveh tu Dios, pues hemos oído hablar de él, de todo lo que ha hecho en Egipto

[[joshua-9-10]]
^10^ y de todo lo que ha hecho con los dos reyes amorreos del otro lado del Jordán, Sijón, rey de Jesbón y Og, rey de Basán, que vivía en Astarot.

[[joshua-9-11]]
^11^ Y nos han dicho nuestros ancianos y todos los habitantes de nuestra tierra: «Tomad en vuestras manos provisiones para el viaje, id a su encuentro y decidles: “Siervos vuestros somos: haced, pues, alianza con nosotros.”

[[joshua-9-12]]
^12^ Este nuestro pan estaba caliente cuando hicimos provisión de él en nuestras casas para el viaje, el día en que partimos para venir a vuestro encuentro: miradlo ahora duro y desmigado.

[[joshua-9-13]]
^13^ Estos odres de vino, que eran nuevos cuando los llenamos, se han roto; nuestras sandalias y nuestros vestidos están gastados por lo largo del camino».

[[joshua-9-14]]
^14^ Los hombres hicieron aprecio de sus provisiones sin consultar el oráculo de Yahveh.

[[joshua-9-15]]
^15^ Josué hizo las paces con ellos, hizo con ellos pacto de conservarles la vida, y los principales de la comunidad se lo juraron.

[[joshua-9-16]]
^16^ Sucedió que, al cabo de tres días de cerrado este pacto, supieron que vivían cerca y habitaban en medio de Israel.

[[joshua-9-17]]
^17^ Los israelitas partieron del campamento y llegaron al tercer día a sus ciudades, que eran Gabaón, Kefirá, Beerot y Quiryat Yearim.

[[joshua-9-18]]
^18^ Los israelitas no los mataron porque los principales de la comunidad se lo habían jurado por Yahveh Dios de Israel. Pero toda la comunidad murmuró de los principales.

[[joshua-9-19]]
^19^ Todos los principales declararon a la comunidad reunida: «Nosotros lo hemos jurado por Yahveh Dios de Israel; no podemos, pues, tocarlos.

[[joshua-9-20]]
^20^ Lo que hemos de hacer con ellos es: Déjalos con vida para que no venga sobre nosotros la Cólera por el juramento que hemos hecho».

[[joshua-9-21]]
^21^ Les dijeron también los principales: «Que vivan, pero que sean leñadores y aguadores de toda la comunidad». Así les dijeron los principales.

[[joshua-9-22]]
^22^ Josué los llamó y les dijo: «¿Por qué nos habéis engañado diciendo: «Vivimos muy lejos de vosotros», siendo así que habitáis en medio de nosotros?

[[joshua-9-23]]
^23^ Sois, pues, unos malditos y nunca dejaréis de servir como leñadores y aguadores de la casa de mi Dios».

[[joshua-9-24]]
^24^ Le respondieron a Josué: «Es que tus siervos estaban bien enterados de la orden que había dado Yahveh tu Dios a Moisés su siervo, de entregaros todo este país y exterminar delante de vosotros a todos sus habitantes. Temimos mucho por nuestras vidas a vuestra llegada y por eso hemos hecho esto.

[[joshua-9-25]]
^25^ Ahora, aquí estamos en tus manos: haz con nosotros lo que te parezca bueno y justo».

[[joshua-9-26]]
^26^ Así hizo con ellos, los salvó de la mano de los israelitas, que no los mataron.

[[joshua-9-27]]
^27^ Aquel día los puso Josué como leñadores y aguadores de la comunidad y del altar de Yahveh hasta el día de hoy, en en lugar que Yahveh había de elegir.
[[joshua-10]]
== Capítulo 10

[[joshua-10-1]]
^1^ Sucedió, pues, que Adoni Sédeq, rey de Jerusalén, se enteró de que Josué se había apoderado de Ay y la había consagrado al anatema, haciendo con Ay y su rey como había hecho con Jericó y su rey, y de que los habitantes de Gabaón habían hecho las paces con Israel y que estaban en medio de Israel.

[[joshua-10-2]]
^2^ Se atemorizó mucho con ello, porque Gabaón era una ciudad grande, como una ciudad real, mayor que Ay, y todos sus hombres eran valientes.

[[joshua-10-3]]
^3^ Entonces Adoni Sédeq, rey de Jerusalén, mandó a decir a Hohán, rey de Hebrón, a Piram, rey de Yarmut, a Yafia, rey de Lakís, y a Debir, rey de Eglón:

[[joshua-10-4]]
^4^ «Venid en mi auxilio para que derrotemos a Gabaón, pues ha hecho las paces con Josué y con los israelitas».

[[joshua-10-5]]
^5^ Se juntaron y subieron los cinco reyes amorreos: el rey de Jerusalén, el rey de Hebrón, el rey de Yarmut, el rey de Lakís y el rey de Eglón, con todas sus tropas; asediaron Gabaón y la atacaron.

[[joshua-10-6]]
^6^ Los gabaonitas mandaron a decir a Josué al campamento de Guilgal: No dejes solos a tus siervos; sube aprisa donde nosotros, sálvanos y socórrenos, porque se han aliado contra nosotros todos los reyes amorreos que habitan en la montaña».

[[joshua-10-7]]
^7^ Josué subió de Guilgal con toda la gente de guerra y todos los guerreros valientes.

[[joshua-10-8]]
^8^ Y Yahveh dijo a Josué: «No les temas, porque los he puesto en tus manos; ninguno de ellos te podrá resistir».

[[joshua-10-9]]
^9^ Josué cayó sobre ellos de improviso, tras haber caminado toda la noche desde Guilgal.

[[joshua-10-10]]
^10^ Yahveh los puso en fuga delante de Israel y les causó una gran derrota en Gabaón: los persiguió por el camino de la subida de Bet Jorón, y los batió hasta Azecá (y hasta Maquedá).

[[joshua-10-11]]
^11^ Mientras huían ante Israel por la bajada de Bet Jorón, Yahveh lanzó del cielo sobre ellos hasta Azecá grandes piedras, y murieron. Y fueron más los que murieron por las piedras que los que mataron los israelitas a filo de espada.

[[joshua-10-12]]
^12^ Entonces habló Josué a Yahveh, el día que Yahveh entregó al amorreo en manos de los israelitas, a los ojos de Israel y dijo: «Deténte, sol, en Gabaón, y tú, luna, en el valle de Ayyalón».

[[joshua-10-13]]
^13^ Y el sol se detuvo y la luna se paró hasta que el pueblo se vengó de sus enemigos. ¿ No está esto escrito en el libre del Justo? El sol se paró en medio del cielo y no tuvo prisa en ponerse como un día entero.

[[joshua-10-14]]
^14^ No hubo día semejante ni antes ni después, en que obedeciera Yahveh a la voz de un hombre. Es que Yahveh combatía por Israel.

[[joshua-10-15]]
^15^ Josué volvió con todo Israel al campamento de Guilgal.

[[joshua-10-16]]
^16^ Aquellos cinco reyes habían huido y se habían escondido en la cueva de Maquedá.

[[joshua-10-17]]
^17^ Se dio aviso a Josué: «Han sido descubiertos los cinco reyes, escondidos en la cueva de Maqedá».

[[joshua-10-18]]
^18^ Josué respondió: «Rodad unas piedras grandes a la boca de la cueva y poned junto a ella hombres que la guarden.

[[joshua-10-19]]
^19^ Y vosotros no os quedéis quietos: perseguid a vuestros enemigos, cortadles la retirada, no les dejéis entrar en sus ciudades, porque Yahveh vuestro Dios los ha puesto en vuestras manos».

[[joshua-10-20]]
^20^ Cuando Josué y los israelitas acabaron de causarles una grandísima derrota, hasta acabar con ellos, los supervivientes se les escaparon y se metieron en las plazas fuertes.

[[joshua-10-21]]
^21^ Todo el pueblo volvió sano y salvo al campamento, junto a Josué, a Maquedá, y no hubo nadie que ladrara contra los israelitas.

[[joshua-10-22]]
^22^ Dijo entonces Josué: «Abrid la boca de la cueva y sacadme de ella a esos cinco reyes».

[[joshua-10-23]]
^23^ Así lo hicieron: le sacaron de la cueva a los cinco reyes: el rey de Jerusalén, el rey de Hebrón, el rey de Yarmut, el rey de Lakís y el rey de Eglón.

[[joshua-10-24]]
^24^ En cuanto sacaron a los reyes, Josué llamó a todos los hombres de Israel y dijo a los capitanes de tropa que le habían acompañado: «Acercaos y poned vuestros pies sobre la nuca de esos reyes». Ellos se acercaron y pusieron los pies sobre las nucas.

[[joshua-10-25]]
^25^ «No tengáis miedo - les dijo Josué - ni os desaniméis; sed valientes y decididos, porque así hará Yahveh con todos los enemigos con quienes tenéis que combatir».

[[joshua-10-26]]
^26^ Acto seguido, Josué los hirió, les dio muerte y los hizo colgar de cinco árboles, de los que quedaron colgados hasta la tarde.

[[joshua-10-27]]
^27^ A la hora de la puesta del sol, a una orden de Josué, los descolgaron de los árboles y los arrojaron a la cueva en que se habían escondido, y echaron unas piedras grandes a la boca de la cueva: allí están todavía hoy.

[[joshua-10-28]]
^28^ El mismo día Josué tomó Maquedá y la pasó a filo de espada, a ella y a su rey: los consagró al anatema con todos los seres vivientes que había en ella. No dejó escapar a nadie, e hizo con el rey de Maquedá como había hecho con el rey de Jericó.

[[joshua-10-29]]
^29^ Josué, con todo Israel, pasó de Maquedá a Libná y la atacó.

[[joshua-10-30]]
^30^ Y Yahveh la entregó también, con su rey, en manos de Israel, que la pasó a filo de espada con todos los seres vivientes que había en ella: no dejó en ella ni uno solo con vida. Hizo con su rey como había hecho con el rey de Jericó.

[[joshua-10-31]]
^31^ Josué, con todo Israel, pasó de Libná a Lakís, la asedió y atacó.

[[joshua-10-32]]
^32^ Yahveh entregó Lakís en manos de Israel, que la tomó al seguno día, y la pasó a cuchillo con todos los seres vivientes que había en ella, lo mismo que había hecho con Libná.

[[joshua-10-33]]
^33^ Entonces Horam, el rey de Guézer, subió en ayuda de Lakís, pero Josué le derrotó a él y a su pueblo, hasta no dejar ni un superviviente.

[[joshua-10-34]]
^34^ Josué, con todo Israel, pasó de Lakís a Eglón. La sitiaron y atacaron.

[[joshua-10-35]]
^35^ La tomaron aquel mismo día y la pasaron a cuchillo. Consagró al anatema aquel día a todos los seres vivientes que había en ella, lo mismo que había hecho con Lakís.

[[joshua-10-36]]
^36^ Josué, con todo Israel, subió de Eglón a Hebrón y a la atacaron.

[[joshua-10-37]]
^37^ La tomaron y la pasaron a cuchillo, con su rey, todas sus ciudades y todos los seres vivientes que había en ella. No dejó ni un superviviente, igual que había hecho con Eglón. La consagró al anatema, a ella y a todos los seres vivientes que había en ella.

[[joshua-10-38]]
^38^ Entonces Josué, con todo Israel, se volvió contra Debir y la atacó.

[[joshua-10-39]]
^39^ Se apoderó de ella, de su rey y de todas sus ciudades, las pasaron a filo de espada y consagraron al anatema a todos los seres vivientes que había en ella, sin dejar uno solo con vida. Como había hecho con Hebrón, así hizo con Debir y su rey, igual que había hecho con Libná y con su rey.

[[joshua-10-40]]
^40^ Batió, pues, Josué todo el país: la Montaña, el Négueb, la Tierra Baja y las laderas, con todos sus reyes, sin dejar ni un superviviente. Consagró a todos los seres vivientes al anatema, como Yahveh, el Dios de Israel, le había ordenado.

[[joshua-10-41]]
^41^ Josué los batió desde Cadés Barnea hasta Gaza, y toda la región de Gosen hasta Gabaón.

[[joshua-10-42]]
^42^ Se apoderó Josué de todos aquellos reyes y de sus territorios de una sola vez, porque Yahveh, el Dios de Israel, peleaba en favor de Israel.

[[joshua-10-43]]
^43^ Josué, con todo Israel, se volvió al campamento de Guilgal.
[[joshua-11]]
== Capítulo 11

[[joshua-11-1]]
^1^ Cuando Yabín, rey de Jasor, se enteró, mandó aviso a Yobab, rey de Merom, al rey de Simrón, al rey de Aksaf,

[[joshua-11-2]]
^2^ y a los reyes de la parte norte de la montaña, del valle al sur de Kinerot, de la Tierra Baja y de las alturas del oeste de Dor.

[[joshua-11-3]]
^3^ El cananeo estaba al oriente y al occidente; el amorreo, el jivita, el perizita y el jebuseo en la montaña; el hitita en las faldas del Hermón, en el país de Mispá.

[[joshua-11-4]]
^4^ Partieron, pues, con todas sus tropas: una muchedumbre innumerable como la arena de la orilla del mar y con gran número de caballos y carros.

[[joshua-11-5]]
^5^ Se juntaron todos estos reyes, llegaron y acamparon juntos hacia las aguas de Merom para luchar contra Israel.

[[joshua-11-6]]
^6^ Yahveh dijo entonces a Josué: «No les tengas miedo, porque mañana a esta misma hora los dejará a todos ellos atravesados ante Israel; tú desjarretarás sus caballos y quemarás sus carros».

[[joshua-11-7]]
^7^ Josué, con toda su gente de guerra, los alcanzó de improvisio junto a las aguas de Merom y cayó sobre ellos.

[[joshua-11-8]]
^8^ Yahveh los entregó en manos de Israel, que los batió y persiguió por occidente hasta Sidón la Grande y hasta Misrefot y, por oriente, hasta el valle de Mispá. Los batió hasta que no quedó ni uno vivo.

[[joshua-11-9]]
^9^ Josué los trató como le había dicho Yahveh: desjarretó sus caballos y quemó sus carros.

[[joshua-11-10]]
^10^ Por entonces, Josué se volvió y tomó Jasor, y mató a su rey a espada. Jasor era antiguamente la capital de todos aquellos reinos.

[[joshua-11-11]]
^11^ Pasaron a cuchillo a todo ser viviente que había en ella, dando cumplimiento al anatema. No quedó alma viva y Jasor fue entregada a las llamas.

[[joshua-11-12]]
^12^ Josué se apoderó de todas las ciudades de aquellos reyes, y de todos sus reyes y los pasó a cuchillo para cumplir en ellos el anatema, según le había mandado Moisés, siervo de Yahveh.

[[joshua-11-13]]
^13^ Pero Israel no quemó ninguna de las ciudades emplazadas sobre sus montículos de ruinas; con la única excepción de Jasor, que fue incendiada por Josué.

[[joshua-11-14]]
^14^ El botín de estas ciudades, incluso el ganado, se lo repartieron los israelitas. Pero pasaron a cuchillo a todo ser humano hasta acabar con todos. No dejaron ninguno con vida.

[[joshua-11-15]]
^15^ Tal como Yahveh había ordenado a su siervo Moisés, Moisés se lo había ordenado a Josué, Josué lo ejecutó: no dejó de pasar una sola palabra de lo que Yahveh había ordenado a Moisés.

[[joshua-11-16]]
^16^ Josué se apoderó de todo el país: de la montaña, de todo el Négueb y de todo el país de Gosen, de la Tierra Baja, de la Arabá, de la montaña de Israel y de sus estribaciones.

[[joshua-11-17]]
^17^ Desde el monte Pelado, que sube hacia Seír, hasta Baal Gad en el valle del Líbano, al pie del monte Hermon, apreso a todos sus reyes y los hirió de muerte.

[[joshua-11-18]]
^18^ Largo tiempo estuvo Josué haciendo la guerra a todos estos reyes;

[[joshua-11-19]]
^19^ no hubo ciudad que hiciera paz con los israelitas, excepto los jivitas que vivían en Gabaón: de todas se apoderaron por la fuerza.

[[joshua-11-20]]
^20^ Porque de Yahveh provenía el endurecer su corazón para combatir a Israel, para ser así consagradas al anatema sin remisión y para ser exterminadas, como había mandado Yahveh a Moisés.

[[joshua-11-21]]
^21^ Por entonces fue Josué y exterminó a los anaquitas de la Montaña, de Hebrón, de Debir, de Anab, de toda la montaña de Judá y de toda la montaña de Israel: los consagró al anatema con sus ciudades.

[[joshua-11-22]]
^22^ No quedó un anaquita en el país de los israelitas; sólo quedaron en Gaza, Gad y Asdod.

[[joshua-11-23]]
^23^ Josué se apoderó de toda la tierra tal como Yahveh le había dicho a Moisés, y se la dio en herencia a Israel según las suertes de las tribus. Y el país vivió en paz tras la guerra.
[[joshua-12]]
== Capítulo 12

[[joshua-12-1]]
^1^ Estos son los reyes del país vencidos por los israelitas y despojados de su territorio en Transjordania, al oriente, desde el torrente Arnón hasta el monte Hermón, con toda la Arabá oriental:

[[joshua-12-2]]
^2^ Sijón, rey de los amorreos, que residía en Jesbón, y dominaba desde Aroer, situada a la orilla del torrente Arnón, la cuenca del torrente y la mitad de Galaad hasta el torrente Yabboq, que sirve de frontera con los ammonitas,

[[joshua-12-3]]
^3^ y, al oriente, la Arabá hasta el mar de Kinerot por una parte y hasta el mar de la Arabá, o mar de la Sal, por otra, camino de Bet Hayesimot, hasta llegar por el sur al pie de las laderas del Pisgá.

[[joshua-12-4]]
^4^ Y Og, rey de Basán, un residuo de los Refaím, que residía en Astarot y en Edreí,

[[joshua-12-5]]
^5^ y dominaba en la montaña de Hermón y Salká, y todo el Basán hasta la frontera de los guesuritas y los maakatitas, y la mitad de Galaad hasta la frontera de Sijón, rey de Jesbón.

[[joshua-12-6]]
^6^ Moisés, siervo de Yahveh, y los israelitas los habían vencido, y Moisés, siervo de Yahveh, había dado el territorio en propiedad a los rubenitas, a los gaditas y a la medio tribu de Manasés.

[[joshua-12-7]]
^7^ Estos son los reyes del país, vencidos por Josué y los israelitas, del lado occidental del Jordán, desde Baal Gad, en el valle del Líbano, hasta el monte Pelado, que se alza hacia Seír, y cuya tierra repartió Josué en herencia a las tribus de Israel según sus suertes:

[[joshua-12-8]]
^8^ en la montaña, en la Tierra Baja, en la Arabá, en las laderas, en le desierto, en el Négueb: hititas, amorreos, cananeos, perizitas, jivitas y jebuseos:

[[joshua-12-9]]
^9^ el rey de Jericó, uno; el rey de Ay, que está junto a Betel

[[joshua-12-10]]
^10^ el rey de Jerusalén, uno; el rey de Hebrón, uno;

[[joshua-12-11]]
^11^ el rey de Yarmut, uno; el rey de Lakís, uno;

[[joshua-12-12]]
^12^ el rey de Eglón, uno; el rey de Guézer, uno;

[[joshua-12-13]]
^13^ el rey de Debir, uno ; el rey de Guéder, uno;

[[joshua-12-14]]
^14^ el rey de Jormá, uno; el rey de Arad, uno;

[[joshua-12-15]]
^15^ el rey de Libná, uno; el rey de Adullam, uno;

[[joshua-12-16]]
^16^ el rey de Maquedá, uno; el rey de Betel, uno;

[[joshua-12-17]]
^17^ el rey de Tappuaj, uno; el rey de Jéfer, uno;

[[joshua-12-18]]
^18^ el rey de Afeq, uno; el rey de Sarón, uno;

[[joshua-12-19]]
^19^ el rey de Merom, uno; el rey de Jasor, uno;

[[joshua-12-20]]
^20^ el rey de Simron Merón, uno; el rey de Aksaf, uno;

[[joshua-12-21]]
^21^ el rey de Tanak, uno; el rey de Meguiddó, uno;

[[joshua-12-22]]
^22^ el rey de Quedés, uno; el rey de Yoqneam, en el Carmelo, uno;

[[joshua-12-23]]
^23^ el rey de Dor, en la región de Dor, uno; el rey de las naciones, en Galilea, uno;

[[joshua-12-24]]
^24^ el rey de Tirsá, uno; Total de reyes: 31
[[joshua-13]]
== Capítulo 13

[[joshua-13-1]]
^1^ Josué era ya viejo y entrado en años. Yahveh le dijo: «Eres viejo y entrado en años, y queda todavía muchísima tierra por conquistar.

[[joshua-13-2]]
^2^ Esta es la tierra que queda: «Todos los distritos de los filisteos y todo lo de los guesuritas;

[[joshua-13-3]]
^3^ desde Sijor, que esta al lado de Egipto, hasta el límite de Ecron por el norte, es considerado como de los cananeos. Los cinco tiranos de los filisteos son el de Gaza, el de Asdod, el de Ascalón, el de Gat y el de Ecrón. Los avitas

[[joshua-13-4]]
^4^ éstan al sur. Todo el país de los cananeos, y Mearah, que es de los sidonios, hasta Afeqá y hasta la frontera de los amorreos;

[[joshua-13-5]]
^5^ luego el país de los guiblitas con todo el Líbano hacia la salida del sol, desde Baal Gad, al pie del monte Hermón, hasta la Entrada de Jamat.

[[joshua-13-6]]
^6^ «Yo arrojaré de la presencia de los israelitas a todos los habitantes de la montaña, desde el Líbano hasta Misrefot al occidente: a todos los sidonios. Tú solamente reparte por suertes la tierra como heredad entre los israelitas, según te he ordenado.

[[joshua-13-7]]
^7^ Reparte ya esta tierra como heredad entre las nueve tribus y la media tribu de Manasés: se la darás desde el Jordán hasta el mar Grande de occidente; el mar Grande será su límite».

[[joshua-13-8]]
^8^ La otra nedia tribu de Manasés, junto con los rubenitas y los gaditas, había recibido ya la parte de la heredad que Moisés les había dado al lado oriental del Jordán, como Moisés, siervo de Yahveh, les había dado:

[[joshua-13-9]]
^9^ la tierra desde Aroer, que está a orillas del torrente Arnón, y la ciudad que está en medio de la vaguada: y toda la llanura desde Medbá hasta Dibón;

[[joshua-13-10]]
^10^ todas las ciudades de Sijón, rey de los amorreos, que había reinado en Jesbón, hasta la frontera de los ammonitas.

[[joshua-13-11]]
^11^ Además, Galaad y el territorio de los guesuritas y los maakatitas con toda la montaña del Hermón y todo Basán hasta Salká;

[[joshua-13-12]]
^12^ y dentro de Basán todo el reino de Og, que había reinado en Astarot y en Edreí, y era último residuo de los Refaím. Moisés los había batido y desposeído.

[[joshua-13-13]]
^13^ Pero los israelitas no desposeyeron ni a los guesuritas ni a los maakatitas, de manera que Guesur y Maaká siguen todavía hoy habitando en medio de Israel.

[[joshua-13-14]]
^14^ La tribu de Leví fue la única a la que no se dio heredad: Yahveh, Dios de Israel, fue su heredad, como se lo había dicho.

[[joshua-13-15]]
^15^ Moisés había dado a la tribu de los hijos de Rubén una parte por clanes.

[[joshua-13-16]]
^16^ Su territorio fue desde Aroer, que está a orillas del torrente Arnón, incluida la ciudad que está en medio de la vaguada, y todo el llano hasta Medbá;

[[joshua-13-17]]
^17^ Jesbón con todas las ciudades situadas en el llano: Dibón, Bamot, Baal, Bet Baal Meón,

[[joshua-13-18]]
^18^ Yahás, Quedemot, Mefaat,

[[joshua-13-19]]
^19^ Quiryatáyim, Sibmá, y Seret Hassajar, en el monte del valle;

[[joshua-13-20]]
^20^ Bet Peor, las laderas del Pisgá, Bet Hayesimot,

[[joshua-13-21]]
^21^ todas las ciudades del llano y todo el reino de Sijón, rey de los amorreos, que reinó en Jesbón y a quien venció Moisés, igual que a los príncipes de Madián: Eví, Réquem, Sur, Jur, Rebá, vasallos de Sijón, que habitaban en el país.

[[joshua-13-22]]
^22^ Al adivino Balaam, hijo de Beor, los israelitas lo habían pasado a cuchillo con otras víctimas.

[[joshua-13-23]]
^23^ Así el territorio de los rubenitas llegaba hasta el Jordán. Esta fue la heredad de los hijos de Rubén por clanes: las ciudades y sus aldeas.

[[joshua-13-24]]
^24^ A la tribu de Gad, a los hijos de Gad, había dado Moisés una parte conforme a sus clanes.

[[joshua-13-25]]
^25^ Su territorio fue Yazer, todas las ciudades de Galaad, la mitad del país de los ammonitas hasta Aroer, que está enfrente de Rabbá,

[[joshua-13-26]]
^26^ y desde Jesbón hasta Ramat Hammispá y Betonim, y desde Majanáyim hasta el territorio de Lo Debar;

[[joshua-13-27]]
^27^ y en el valle: Bet Jaram, Bet Nimrá, Sukkot, Safón - el resto del reino de Sijón, rey de Jesbón -, el Jordán y el territorio hasta la punta del mar de Kinnéret, al lado oriental del Jordán.

[[joshua-13-28]]
^28^ Esta fue la heredad de los hijos de Gad por clanes: las ciudades y sus aldeas.

[[joshua-13-29]]
^29^ A la media tribu de Manasés le había dado Moisés una parte conforme a sus clanes.

[[joshua-13-30]]
^30^ Su territorio comprendía, desde Majanáyim, todo el Basán, todos los Aduares de Yaír en Basán: sesenta ciudades;

[[joshua-13-31]]
^31^ la mitad de Galaad, Astarot y Edreí, ciudades del reino de Og en Basán. Pasaron a ser de los hijos de Makir, hijo de Manasés, de la mitad de los hijos de Makir por clanes.

[[joshua-13-32]]
^32^ Esto fue lo que repartió en heredad Moisés en las Estepas de Moab, al otro lado del Jordán, al oriente de Jericó.

[[joshua-13-33]]
^33^ Pero Moisés no dio heredad a la tribu de Leví: Yahveh, el Dios de Israel, es su heredad, como se lo había dicho.
[[joshua-14]]
== Capítulo 14

[[joshua-14-1]]
^1^ Esto es lo que recibieron como heredad los israelitas en el país de Canaán, lo que les repartieron como heredad el sacerdote Eleazar y Josué, hijo de Nun, y los cabezas de familia de las tribus de Israel.

[[joshua-14-2]]
^2^ El reparto para las nueve tribus de Israel y la media tribu se hizo a suertes, como Yahveh había ordenado por medio de Moisés.

[[joshua-14-3]]
^3^ Porque Moisés había dado su heredad a las dos tribus y media de Transjordania sin dar a los levitas heredad entre ellas.

[[joshua-14-4]]
^4^ Pues los hijos de José vinieron a formar dos tribus: Manasés y Efraím, pero a los levitas no se les dio ninguna parte en el territorio sino sólo ciudades para residir, con los pastos correspondientes para sus ganados y su hacienda.

[[joshua-14-5]]
^5^ Como Yahveh había mandado a Moisés, así hicieron los israelitas en el reparto de la tierra.

[[joshua-14-6]]
^6^ Se acercaron los hijos de Judá a Josué en Guilgal, y Caleb, hijo de Yefunné el quenizita, le dijo: «Ya sabes lo que le dijo Yahveh a Moisés, el hombre de Dios, de ti y de mí en Cadés Barnea.

[[joshua-14-7]]
^7^ Cuarenta años tenía yo cuando Moisés, siervo de Yahveh, me envió de Cadés Barnea a explorar esta tierra y yo le di un informe con toda sinceridad.

[[joshua-14-8]]
^8^ Los hermanos que habían subido conmigo desanimaron al pueblo, pero yo me mantuve fiel a Yahveh mi Dios.

[[joshua-14-9]]
^9^ Aquel día Moisés hizo este juramento: “Te juro que la tierra que ha hollado tu pie será heredad tuya y de tus hijos para siempre. Porque has sido fiel a Yahveh mi Dios.”

[[joshua-14-10]]
^10^ Pues ahora mira cómo Yahveh me ha conservado con vida según lo prometió. Hace 45 años que Yahveh le dijo esto a Moisés, cuando Israel iba por el desierto, y ahora tengo 85 años.

[[joshua-14-11]]
^11^ Todavía estoy tan fuerte como el día en que Moisés me envió. Conservo todo mi vigor de entonces para combatir y para ir y venir.

[[joshua-14-12]]
^12^ Dame ya esta montaña que me prometió Yahveh aquel día. Ya entonces supiste que hay en ella anaquitas y ciudades grandes y fuertes. Si Yahveh está conmigo, los expulsaré, como me prometió Yahveh».

[[joshua-14-13]]
^13^ Josué bendijo a Caleb, hijo de Yefunné, y le dio Hebrón por heredad.

[[joshua-14-14]]
^14^ Por eso Hebrón sigue siendo hasta el día de hoy heredad de Caleb, hijo de Yefunné el quenizita, por haber sido fiel a Yahveh, Dios de Israel.

[[joshua-14-15]]
^15^ El nombre primitivo de Hebrón era Quiryat Arbá. Arbá era el hombre más alto entre los anaquitas. Y el país vivió en paz tras la guerra.
[[joshua-15]]
== Capítulo 15

[[joshua-15-1]]
^1^ La suerte que tocó a la tribu de los hijos de Judá conforme a sus clanes cayó hacia la frontera de Edom, desde el desierto de Sin hacia el mediodía hasta Cadés en el extremo sur.

[[joshua-15-2]]
^2^ Su límite meridional partía del extremo del mar de la Sal, desde la lengua que da hacia el sur;

[[joshua-15-3]]
^3^ luego se dirigía por el sur de la subida de los Escorpiones, pasaba hacia Sin y subía por el sur de Cadés Barnea; pasando por Jesrón, subía hacia Adar y volvía a Carcá;

[[joshua-15-4]]
^4^ pasaba por Asmón, iba hacia el torrente de Egipto y venía a salir al mar. Esa será vuestra frontera por el sur.

[[joshua-15-5]]
^5^ Al oriente el límite era el mar de la Sal hasta la desembocadura del Jordán. La frontera por el lado norte partía de la lengua de mar que hay en la desembocadura del Jordán.

[[joshua-15-6]]
^6^ El límite subía a Bet Joglá, pasaba al norte de Bet Haarabá y subía hasta la Peña de Boján, hijo de Rubén.

[[joshua-15-7]]
^7^ El límite subía desde el valle de Akor hasta Debir y volvía al norte hacia el círculo de piedras que hay enfrente de la subida de Adummim, que está al sur del Torrente. El límite pasaba hacia las aguas de En Semes y venía a salir a En Roguel.

[[joshua-15-8]]
^8^ Subía después por el valle de Ben Hinnom, por el sur, al Hombro del Jebuseo, es decir, Jerusalén; subía el límite por el oeste a la cima del monte que hay frente al valle de Hinnom, al extremo norte del valle de los Refaím.

[[joshua-15-9]]
^9^ El límite torcía de la cumbre del monte hacia la fuente de agua de Neftoaj y seguía hacia las ciudades del monte Efrón para torcer en dirección a Baalá, o sea, Quiryat Yearim.

[[joshua-15-10]]
^10^ De Baalá, el límite doblaba por el oeste hacia el monte Seír y, pasando por la vertiente norte del monte Yearim, o sea Kesalón, bajaba a Bet Semes, pasaba a Timná,

[[joshua-15-11]]
^11^ iba hacia el lado norte de Ecrón, doblaba hacia Sikkarón, pasaba por el monte de Baalá, salía por Yabneel. La frontera terminaba en el mar.

[[joshua-15-12]]
^12^ El límite occidental era el mar Grande. Este era el límite que rodeaba el territorio de los hijos de Judá por clanes.

[[joshua-15-13]]
^13^ A Caleb, hijo de Yefunné, se le dio una parte entre los hijos de Judá, según la orden de Yahveh a Josué: Quiryat Arbá, la ciudad del padre de Anaq, que es Hebrón.

[[joshua-15-14]]
^14^ Caleb echó de allí a los tres hijos de Anaq: Sesay, Ajimán y Talmay, descendientes de Anaq.

[[joshua-15-15]]
^15^ De allí se dirigió hacia los habitantes de Debir, que antiguamente se llamaba Quiryat Séfer.

[[joshua-15-16]]
^16^ Entonces dijo Caleb: «Al que derrote a Quiryat Séfer y la tome, le daré mi hija Aksá por mujer».

[[joshua-15-17]]
^17^ El que la tomó fue Otniel, hijo de Quenaz, hermano de Caleb, y éste le dio su hija Aksá por mujer.

[[joshua-15-18]]
^18^ Cuando iba a casa de su marido, éste le incitó a que pidiera a su padre un campo; ella se apeó del asno y Caleb le preguntó: «¿Qué quieres?»

[[joshua-15-19]]
^19^ Ella respondió: «Hazme un regalo; ya que me has dado el desierto de Négueb, dame fuentes de agua». Y él le dio las fuentes de arriba y las fuentes de abajo.

[[joshua-15-20]]
^20^ Esta fue la heredad de la tribu de los hijos de Judá por clanes.

[[joshua-15-21]]
^21^ Ciudades fronterizas de la tribu de los hijos de Judá, hacia la frontera de Edom en el Négueb: Cabseel, Eder, Yagur,

[[joshua-15-22]]
^22^ Quiná, Dimón, Adadá,

[[joshua-15-23]]
^23^ Quedes, Jasor Yitnam,

[[joshua-15-24]]
^24^ Zif, Télem, Bealot,

[[joshua-15-25]]
^25^ Jasor Jadattá, Queriyyot Jesrón (que es Jasor),

[[joshua-15-26]]
^26^ Amam, Semá, Moladá,

[[joshua-15-27]]
^27^ Jasar Gaddá, Jesmón, Bet Pélet,

[[joshua-15-28]]
^28^ Jasar Sual, Berseba y sus filiales,

[[joshua-15-29]]
^29^ Baalá, Iyyim, Esem,

[[joshua-15-30]]
^30^ Eltolad, Kesil, Jormá,

[[joshua-15-31]]
^31^ Siquelag, Madmanná, Sansanná,

[[joshua-15-32]]
^32^ Lebaot, Siljim, Ayin y Rimmón. En total veintinueve ciudades con sus aldeas.

[[joshua-15-33]]
^33^ En la Tierra Baja: Estaol, Sorá, Asná,

[[joshua-15-34]]
^34^ Zanoaj, En Gannim, Tappuaj, Enam,

[[joshua-15-35]]
^35^ Yarmut, Adullam, Sokó, Azecá,

[[joshua-15-36]]
^36^ Saaráyim, Aditáyim, Hag Guederá, Guederotáyim: catorce ciudades con sus aldeas.

[[joshua-15-37]]
^37^ Senán, Jadasá, Migdal Gad,

[[joshua-15-38]]
^38^ Dilán, Ham Mispé, Yoqteel,

[[joshua-15-39]]
^39^ Lakís, Boscat, Eglón,

[[joshua-15-40]]
^40^ Kabbón, Lajmás, Kitlís,

[[joshua-15-41]]
^41^ Guederot, Bet Dagón, Naamá, Maquedá: dieciséis ciudades con sus aldeas.

[[joshua-15-42]]
^42^ Libná, Eter, Asán,

[[joshua-15-43]]
^43^ Iftaj, Asná, Nesib,

[[joshua-15-44]]
^44^ Queilá, Akzib, Maresá: nueve ciudades con sus aldeas.

[[joshua-15-45]]
^45^ Ecrón con sus filiales y aldeas.

[[joshua-15-46]]
^46^ De Ecrón hasta el mar, todo lo que está al lado de Asdod con sus aldeas.

[[joshua-15-47]]
^47^ Asdod con sus filiales y aldeas, Gaza con sus filiales y aldeas hasta el Torrente de Egipto, limitando con el mar Grande.

[[joshua-15-48]]
^48^ En la montaña: Samir, Yattir, Sokó,

[[joshua-15-49]]
^49^ Danná, Quiryat, Sanná, que es Debir,

[[joshua-15-50]]
^50^ Anab, Estemoa, Anim,

[[joshua-15-51]]
^51^ Gosen, Jolón, Guiló: once ciudades y sus aldeas.

[[joshua-15-52]]
^52^ Arab, Dumá, Esan,

[[joshua-15-53]]
^53^ Yanum, Bet Tappuaj, Afeqá,

[[joshua-15-54]]
^54^ Jumtá, Quiryat Arbá, que es Hebrón, Sior: nueve ciudades y sus aldeas.

[[joshua-15-55]]
^55^ Maón, Carmelo, Zif, Yuttá,

[[joshua-15-56]]
^56^ Yizreel, Yoqdeam, Zanoaj,

[[joshua-15-57]]
^57^ Haqcayim, Guibeá y Timná: diez ciudades con sus aldeas.

[[joshua-15-58]]
^58^ Jaljul, Bet Sur, Guedor,

[[joshua-15-59]]
^59^ Maarat, Bet Anot, Eltecón: seis ciudades con sus aldeas. Técoa, Efratá, que es Belén, Peor, Etam, Culón, Tatam, Sores, Karem, Gallim, Béter, Manaj: once ciudades con sus aldeas.

[[joshua-15-60]]
^60^ Quiryat Baal, que es Quiryat Yearim, y Harabbá: dos ciudades con sus aldeas.

[[joshua-15-61]]
^61^ En el desierto: Bet Haarabá, Middin, Sekaká,

[[joshua-15-62]]
^62^ Nibsán, la ciudad de la Sal y Engadí: seis ciudades con sus aldeas.

[[joshua-15-63]]
^63^ Pero los hijos de Judá no pudieron echar a los jebuseos que ocupaban Jerusalén. Por eso los jebuseos siguen habitando en Jerusalén junto a los hijos de Judá hasta el día de hoy.
[[joshua-16]]
== Capítulo 16

[[joshua-16-1]]
^1^ La suerte que tocó a los hijos de José comenzaba, por el lado oriental, en el Jordán, a la altura de Jericó (las aguas de Jericó), en el desierto que sube de Jericó a la montaña de Betel;

[[joshua-16-2]]
^2^ siguiendo de Betel a Luz, pasaba hacia la frontera de los arquitas por Atarot;

[[joshua-16-3]]
^3^ bajaba después al oeste hacia la frontera de los yafletitas, hasta Guézer, y venía a salir al mar.

[[joshua-16-4]]
^4^ Esta fue la heredad de los hijos de José, Manasés y Efraím.

[[joshua-16-5]]
^5^ Límite de los hijos de Efraím por clanes: el límite de su heredad era por el este Atrot Arak hasta Bet Jorón de Arriba

[[joshua-16-6]]
^6^ e iba e salir el límite al mar... el Mikmetat al norte, y el límite doblaba al oriente hacia Taanat Silo, y la cruzaba al este hacia Yanojá;

[[joshua-16-7]]
^7^ bajaba de Yanojá a Atarot y a Naará y tocaba en Jericó para terminar en el Jordán.

[[joshua-16-8]]
^8^ De Tappuaj iba el límite hacia occidente por el torrente de Caná y venía a parar en el mar. Esta fue la heredad de la tribu de los hijos de Efraím según sus clanes,

[[joshua-16-9]]
^9^ además de las ciudades reservadas para los hijos de Efraím de la herencia de los hijos de Manasés; todas estas ciudades y sus aldeas.

[[joshua-16-10]]
^10^ El cananeo que ocupaba Guézer no fue expulsado y así continúa en medio de Efraím hasta el día de hoy, pero sujeto a servidumbre.
[[joshua-17]]
== Capítulo 17

[[joshua-17-1]]
^1^ A la tribu de Manasés le correspondió suerte, porque era el primogénito de José: a Makir, primogénito de Manasés y padre de Galaad, como era hombre de guerra, le tocó Galaad y Basán;

[[joshua-17-2]]
^2^ y a los otros hijos de Manasés, según sus clanes: a los hijos de Abiezer, a los hijos de Jeleq, a los hijos de Asriel, a los hijos de Sekem, a los hijos de Jéfer, a los hijos de Semidá, estos eran los hijos varones de Manasés, hijo de José, por clanes.

[[joshua-17-3]]
^3^ Pero Selofjad, hijo de Jéfer, hijo de Galaad, hijo de Makir, hijo de Manasés, no tenía hijos; sólo tenía hijas. Sus hijas se llamaban: Majlá, Noá, Joglá, Milká y Tirsá.

[[joshua-17-4]]
^4^ Estas se presentaron ante el sacerdote Eleazar, ante Josué, hijo de Nun, y ante los principales, y dijeron: «Yahveh ordenó a Moisés que nos diera una heredad entre nuestros hermanos». Les dio, pues, según la orden de Yahveh, una heredad entre los hermanos de su padre.

[[joshua-17-5]]
^5^ Tocaron a Manasés diez porciones además del país de Galaad y de Basán, situado en Transjordania,

[[joshua-17-6]]
^6^ pues las hijas de Manasés obtuvieron una heredad entre sus hijos. El país de Galaad pertenecía a los otros hijos de Manasés.

[[joshua-17-7]]
^7^ El límite de Manasés era por el lado de Aser, Mikmetat, que está en frente de Siquem; de allí iba hacia la derecha, hacia Yasib, en la fuente de Tappuaj.

[[joshua-17-8]]
^8^ El país de Tappuaj era de Manasés, pero Tappuaj, en la frontera de Manasés, era de los hijos de Efraím.

[[joshua-17-9]]
^9^ El límite bajaba por el torrente de Caná; al sur del torrente estaban las ciudades de Efraím, además de las que tenía Efraím entre las ciudades de Manasés, y el territorio de Manasés estaba al norte del torrente, e iba a salir al mar.

[[joshua-17-10]]
^10^ Lo del sur era de Efraím y lo del norte de Manasés, y el mar era su frontera; lindaban con Aser al norte y con Isacar al este.

[[joshua-17-11]]
^11^ Manasés tenía, en Isacar y en Aser, Bet Seán y sus filiales, Yibleam y sus filiales, los habitantes de Dor y sus filiales, los habitantes de Tanak y Meguiddó y sus filiales, y un tercio de Néfet.

[[joshua-17-12]]
^12^ Los hijos de Manasés no pudieron apoderarse de estas ciudades y los cananeos lograron mantenerse en aquel país.

[[joshua-17-13]]
^13^ Pero, cuando los israelitas se hicieron más fuertes, sometieron a los cananeos a servidumbre, aunque no llegaron a expulsarlos.

[[joshua-17-14]]
^14^ Los hijos de José se dirigieron a Josué y le dijeron: «¿Por qué no me has asignado en heredad más que una suerte, una sola porción, siendo tan numeroso como soy porque Yahveh me ha bendecido?»

[[joshua-17-15]]
^15^ Josué respondió: «Si eres un pueblo tan numeroso sube a los bosques y corta para ti el de la región de los perizitas y de los refaítas, pues la montaña de Efraím es demasiado estrecha para ti».

[[joshua-17-16]]
^16^ Los hijos de José respondieron: «La montaña no nos basta, y todos los cananeos que habitan en el llano tienen carros de hierro, lo mismo los de Bet Seán y sus filiales que los de la llanura de Yizreel».

[[joshua-17-17]]
^17^ Josué dijo a la casa de José, a Efraím y a Manasés: «Eres un pueblo grande y tienes mucha fuerza; no tendrás sólo una parte,

[[joshua-17-18]]
^18^ sino que tendrás también la montaña; está cubierta de bosques pero tú la talarás y serás tuya la región resultante; y expulsarás al cananeo, aunque tiene carros de hierro y es muy fuerte».
[[joshua-18]]
== Capítulo 18

[[joshua-18-1]]
^1^ Todo la comunidad de los israelitas se reunió en Silo, donde alzaron la Tienda del Encuentro; todo el país les estaba sometido.

[[joshua-18-2]]
^2^ Pero quedaban todavía entre los israelitas siete tribus que no se habían repartido su heredad.

[[joshua-18-3]]
^3^ Josué, pues, dijo a los israelitas: «¿Hasta cuándo vais a retardar el ir a tomar posesión de la tierra que os ha dado Yahveh, el Dios de vuestros padres?

[[joshua-18-4]]
^4^ Escoged tres hombres por cada tribu, y los enviaré para que vayan a recorrer el país y hagan una descripción de él en orden al reparto; luego volverán donde mí.

[[joshua-18-5]]
^5^ Dividirán la tierra en siete partes. Judá se quedará en su territorio al sur y la casa de José se quedará en su territorio al norte.

[[joshua-18-6]]
^6^ Vosotros haréis una descripcíon del país en siete partes, y me la traeréis para que os la sortee aquí, en presencia de Yahveh nuestro Dios.

[[joshua-18-7]]
^7^ Porque los levitas no tienen su parte entre vosotros, pues el sacerdocio de Yahveh es su heredad; y Gad, Rubén y la media tribu de Manasés, han recibido ya al lado oriental del Jordán, la heredad que les dio Moisés, siervo de Yahveh».

[[joshua-18-8]]
^8^ Los hombres se pusieron en camino. Josué dio esta orden a los que iban a hacer la descripción del país: «Id, recorred el país y describidlo, y después volved donde mí; yo os haré el sorteo de la tierra aquí delante de Yahveh, en Silo».

[[joshua-18-9]]
^9^ Fueron los hombres, recorrieron la comarca, y la describieron ciudad por ciudad, en siete partes, en un escrito que llevaron a Josué, al campamento de Silo.

[[joshua-18-10]]
^10^ Josué les echó suertes en Silo, delante de Yahveh, y repartió allí la tierra entre los israelitas, conforme a sus particiones.

[[joshua-18-11]]
^11^ Tocó una suerte a la tribu de los hijos de Benjamin por clanes: los límites de su suerte resultaron comprendidos entre los de los hijos de Judá y los de los hijos de José.

[[joshua-18-12]]
^12^ Su límite, por el lado norte, partía del Jordán, subía por el flanco norte de Jericó, hasta alcanzar la montaña hacia el oeste, y venía a salir al desierto de Bet Avén.

[[joshua-18-13]]
^13^ De allí pasaba el límite hacia Luz, por el flanco sur de Luz, que es Betel, y bajaba a Atrot Addar sobre el monte que está al sur de Bet Jorón de Abajo.

[[joshua-18-14]]
^14^ Torcía el límite y volvía por el oeste hacia el sur, desde el monte que está al lado meridional de Bet Jorón, para ir a salir hacia Quiryat Baal, que es Quiryat Yearim, ciudad de los hijos de Judá. Ese era el lado oeste.

[[joshua-18-15]]
^15^ Y el lado sur: desde el extremo de Quiryat Yearim, el límite seguía hacia Gasín y salía cerca de la fuente de las aguas de Neftóaj,

[[joshua-18-16]]
^16^ luego bajaba hacia el extremo del monte que está frente al valle de Ben Hinnom, al norte del valle de Refaím, bajaba al valle de Hinnom por el flanco sur del jebuseo y seguía bajando hasta En Roguel.

[[joshua-18-17]]
^17^ Doblaba luego por el norte, salía en En Semes y salía hacia el círculo de piedras que hay frente a la subida de Adummim; bajaba a la Peña de Boján, hijo de Rubén;

[[joshua-18-18]]
^18^ pasaba luego hacia la vertiente de Bet Haarabá por el norte y bajaba hacia la Arabá;

[[joshua-18-19]]
^19^ pasaba el límite hacia la pendiente de Bet Joglá al norte, e iba a dar el límite a la lengua septentrional del mar de la Sal, en el extremo sur del Jordán. Ese era el límite meridional.

[[joshua-18-20]]
^20^ El Jordán era el límite del lado oriental. Esa fue la heredad de los hijos de Benjamín, conforme a sus clanes, con los límites que la rodean.

[[joshua-18-21]]
^21^ Las ciudades de la tribu de los hijos de Benjamín, por clanes, fueron: Jericó, Bet Joglá, Emeq Quesís;

[[joshua-18-22]]
^22^ Bet Haarabá, Semaráyim, Betel;

[[joshua-18-23]]
^23^ Avvim, Pará, Ofrá;

[[joshua-18-24]]
^24^ Kefar Haamoní, Ofní, Gabá: doce ciudades con sus aldeas.

[[joshua-18-25]]
^25^ Gabaón, Ramá, Beerot,

[[joshua-18-26]]
^26^ Mispé, Kefirá, Mosá;

[[joshua-18-27]]
^27^ Réquem, Yirpeel, Taralá;

[[joshua-18-28]]
^28^ Sela Haalef, el Jebuseo, es decir Jerusalén, Guibeá y Quiryat: catorce ciudades con sus aldeas. Esa fue la heredad de los hijos de Benjamín, por clanes.
[[joshua-19]]
== Capítulo 19

[[joshua-19-1]]
^1^ La segunda suerte cayó a Simeón, a la tribu de los hijos de Simeón, por clanes: su heredad estaba en medio de la heredad de los hijos de Judá.

[[joshua-19-2]]
^2^ Les correspondió como heredad: Berseba, Semá, Moladá;

[[joshua-19-3]]
^3^ Jasar Sual, Balá, Esem;

[[joshua-19-4]]
^4^ Eltolad, Betul, Jormá;

[[joshua-19-5]]
^5^ Siquelag, Bet Hammarkabot; Jasar Susá;

[[joshua-19-6]]
^6^ Bet Lebaot y Sarujem: trece ciudades y sus aldeas;

[[joshua-19-7]]
^7^ Ayín, Rimmón, Eter y Asán; cuatro ciudades y sus aldeas.

[[joshua-19-8]]
^8^ Adémas todas las aldeas de los alrededores de estas ciudades hasta Baalat Beer, Ramá del Négueb. Esa fue la heredad de la tribu de los hijos de Simeón, por clanes.

[[joshua-19-9]]
^9^ La heredad de los hijos de Simeón se tomó de la porción de los hijos de Judá, porque la parte de los hijos de Judá era demasiado grande para ellos. Los hijos de Simeón recibieron, pues, su heredad en medio de la heredad de los hijos de Judá.

[[joshua-19-10]]
^10^ La tercera suerte tocó a los hijos de Zabulón, por clanes: el límite de su heredad se extendía hasta Sadud;

[[joshua-19-11]]
^11^ su límite subía al occidente hacia Maraalá y tocaba en Dabbéset y luego en el torrente que hay frente a Yoqneam.

[[joshua-19-12]]
^12^ De Sadud volvía el límite hacia el este, hacia la salida del sol, hasta el límite de Kislot Tabor, seguía hacia Daberat y subía a Yafía.

[[joshua-19-13]]
^13^ De allí pasaba hacia el este, al oriente, por Gat Jéfer y por Itta Casín, iba hacia Rimmón y volvía hacia Neá.

[[joshua-19-14]]
^14^ El límite volvía por el norte hacia Jannatón e iba a salir al valle de Yiftaj El.

[[joshua-19-15]]
^15^ Además, Cattat, Nahalal, Simrón, Yiralá y Belén: doce ciudades con sus aldeas.

[[joshua-19-16]]
^16^ Esa fue la heredad de los hijos de Zabulón, por clanes: esas ciudades y sus aldeas.

[[joshua-19-17]]
^17^ La cuarta suerte tocó a Isacar, a los hijos de Isacar, por clanes.

[[joshua-19-18]]
^18^ Su territorio se extendía hasta Yizreel y comprendía Kesulot y Sunem;

[[joshua-19-19]]
^19^ Jafaráyim, Sión, Anajarat,

[[joshua-19-20]]
^20^ Daberat, Quisyón, Ebes;

[[joshua-19-21]]
^21^ Rémet y En Gannim, En Jaddá y Bet Passés.

[[joshua-19-22]]
^22^ Su límite tocaba en el Tabor, en Sajasima y en Bet Semes, y el límite terminaba en el Jordán; dieciséis ciudades con su aldeas.

[[joshua-19-23]]
^23^ Esa fue la heredad de la tribu de los hijos de Isacar, por clanes: las ciudades y sus aldeas.

[[joshua-19-24]]
^24^ La quinta suerte tocó a la tribu de los hijos de Aser, por clanes.

[[joshua-19-25]]
^25^ Su territorio comprendía: Jelcat, Jalí, Beten, Aksaf,

[[joshua-19-26]]
^26^ Alammélek, Amad, Misal; tocaba en el Carmelo por el oeste y en el curso del Libnat;

[[joshua-19-27]]
^27^ volvía luego hacia la salida del sol hasta Bet Dagón y tocaba por el norte en Zabulón y en el valle de Yiftaj El, y Bet Haemeq y Neiel, yendo a parar hacia Kabul por la izquierda con

[[joshua-19-28]]
^28^ Abdón, Rejob, Jammón y Caná hasta Sidón la Grande.

[[joshua-19-29]]
^29^ El límite volvía a Ramá y hasta la plaza fuerte de Tiro y hasta Josá, e iba a terminar en el mar. Majaleb, Akzib,

[[joshua-19-30]]
^30^ Akko, Afeq, Rejob: veintidós ciudades con sus aldeas.

[[joshua-19-31]]
^31^ Esa fue la heredad de la tribu de los hijos de Aser, por clanes: esas ciudades y sus aldeas.

[[joshua-19-32]]
^32^ A los hijos de Neftalí les tocó la sexta suerte; a los hijos de Neftalí, por clanes:

[[joshua-19-33]]
^33^ su límite iba de Jélef y de la Encina de Saanannim y Adamí Hannéqueb y Yabneel hasta Laqcum e iba a salir al Jordán.

[[joshua-19-34]]
^34^ Volvía el límite hacia el oeste por Aznot Tabor y de allí a salir a Juqcoq, lindaba con Zabulón al sur, con Aser al oeste y con el Jordán al oriente.

[[joshua-19-35]]
^35^ Y las ciudades fuertes eran: Siddim, Ser, Jammat, Raqcat, Kinneret,

[[joshua-19-36]]
^36^ Adamá, Ramá, Jasor;

[[joshua-19-37]]
^37^ Quedes, Edreí, En Jasor,

[[joshua-19-38]]
^38^ Yirón, Migdal El, Jórem, Bet Anat, Bet Semes: diecinueve ciudades con sus aldeas.

[[joshua-19-39]]
^39^ Esa fue la heredad de los hijas de Neftalí, por clanes: las ciudades y sus aldeas.

[[joshua-19-40]]
^40^ A la tribu de los hijos de Dan, por clanes, tocó la séptima suerte.

[[joshua-19-41]]
^41^ El territorio de su heredad comprendía: Sorá, Estaol, Ir Simes.

[[joshua-19-42]]
^42^ Saalbim, Ayyalón, Silatá;

[[joshua-19-43]]
^43^ Elón, Timná, Ecrón,

[[joshua-19-44]]
^44^ Eltequé, Guibbetón, Baalat;

[[joshua-19-45]]
^45^ Azor, Bené Beraq, Gat Rimmón;

[[joshua-19-46]]
^46^ y hacia el mar Yeraqón con el territorio de enfrente de Joppe.

[[joshua-19-47]]
^47^ Pero el territorio de los hijos de Dan quedaba fuera de su poder. Por eso, los hijos de Dan subieron a atacar a Lésem; la tomaron y la pasaron a cuchillo. Tomada la ciudad, se establecieron en ella y a Lésem la llamaron Dan, del nombre de Dan su padre.

[[joshua-19-48]]
^48^ Esa fue la heredad de la tribu de los hijos de Dan, por clanes: esas ciudades y sus aldeas.

[[joshua-19-49]]
^49^ Acabaron, pues, de sortear el país con sus límites. Y los israelitas dieron a Josué, hijo de Nun, una heredad en medio de ellos;

[[joshua-19-50]]
^50^ según orden de Yahveh, le dieron la ciudad que había pedido, Timnat Sérak, en la montaña de Efraím. Reconstruyó la ciudad y se estableció en ella.

[[joshua-19-51]]
^51^ Esas son las heredades que el sacerdote Eleazar, Josué, hijo de Nun, y los jefes de familia sortearon entre las tribus de Israel en Silo, en presencia de Yahveh, a la entrada de la Tienda del Encuentro; y así se terminó el reparto de la tierra.
[[joshua-20]]
== Capítulo 20

[[joshua-20-1]]
^1^ Yahveh dijo a Josué:

[[joshua-20-2]]
^2^ «Habla a los israelitas y diles: Señalaos las ciudades de asilo de las que os hablé por medio de Moisés,

[[joshua-20-3]]
^3^ a las que pueda huir el homicida que haya matado a alguien por inadvertencia (sin querer), y que le sirvan de asilo contra el vengador de la sangre.

[[joshua-20-4]]
^4^ (El homicida huirá a una de estas ciudades: se detendrá a la entrada de la puerta de la ciudad y expondrá su caso a los ancianos de la ciudad. Estos le admitirán en su ciudad y le señalarán una casa para que habite con ellos.

[[joshua-20-5]]
^5^ Si el vengador de la sangre le persigue, no le entregarán al homicida en su manos, pues ha herido a su prójimo sin querer, y no le tenía odio anteriormente.

[[joshua-20-6]]
^6^ El homicida habrá de permanecer en la ciudad, hasta que comparezca en juicio ante la comunidad, hasta la muerte del Sumo Sacerdote que esté en funciones por aquel tiempo. Entonces el homicida podrá volver a sus ciudad y a su casa, a la ciudad de la que huyó».

[[joshua-20-7]]
^7^ Consagraron: Quedes en Galilea, en la montaña de Neftalí, Siquem en la montaña de Efraím, Quiryat Arbá, o sea Hebrón, en la montaña de Judá.

[[joshua-20-8]]
^8^ En Transjordania, al oriente de Jericó, se designó Béser, de la tribu de Rubén, en el desierto, en el llano; Ramot en Galaad, de la tribu de Gad, y Golán en Basán, de la tribu de Manasés.

[[joshua-20-9]]
^9^ Estas son las ciudades designadas para todos los israelitas, así como para el forastero residente entre ellos, para que pueda refugiarse en ellas cualquiera que haya matado a alguien por inadvertencia, y no muera a manos del vengador de la sangre, hasta que comparezca ante la comunidad.
[[joshua-21]]
== Capítulo 21

[[joshua-21-1]]
^1^ Se acercaron los cabezas de familia de los levitas al sacerdote Eleazar, a Josué, hijo de Nun, y a los cabezas de familia de las tribus de Israel,

[[joshua-21-2]]
^2^ cuando estaban en Silo, en tierra de Canaán, y les dijeron: «Yahveh ordenó por medio de Moisés que se nos dieran ciudades donde residir, con sus pastos para nuestro ganado».

[[joshua-21-3]]
^3^ Los israelitas, conforme a la orden de Yahveh, dieron a los levitas, de su heredad, las siguientes ciudades con sus pastos.

[[joshua-21-4]]
^4^ Se hizo el sorteo para los clanes quehatitas: y a los levitas hijos del sacerdote Aarón les tocaron trece ciudades de las tribus de Judá, Simeón, y Benjamín;

[[joshua-21-5]]
^5^ a los otros hijos de Quehat, por clanes, diez ciudades de las tribus de Efraím, de Dan y de la media tribu de Manasés.

[[joshua-21-6]]
^6^ A los hijos de Guerson, por clanes, les tocaron trece ciudades de las tribus de Isacar, Aser, Neftalí y de la media tribu de Manasés, en Basán.

[[joshua-21-7]]
^7^ A los hijos de Merarí, por clanes, les tocaron doce ciudades de las tribus de Rubén, Gad y Zabulón.

[[joshua-21-8]]
^8^ Los israelitas dieron a los levitas por suertes esas ciudades y sus pastos, como Yahveh había ordenado por boca de Moisés.

[[joshua-21-9]]
^9^ De la tribu de Judá y de la tribu de Simeón les dieron las ciudades que se nombran a continuación;

[[joshua-21-10]]
^10^ esta fue la parte de los hijos de Aarón, pertenecientes al clan quehatita, de los hijos de Levi; porque la primera suerte fue para ellos.

[[joshua-21-11]]
^11^ Les dieron Quiryat Arbá (ciudad del padre de Anaq), o sea Hebrón, en la montaña de Judá, con los pastos circundantes.

[[joshua-21-12]]
^12^ Pero la campiña de esta ciudad con sus aldeas se la dieron en propiedad a Caleb, hijo de Yefunné.

[[joshua-21-13]]
^13^ A los hijos del sacerdote Aarón les dieron, como ciudad de asilo para los homicidas, Hebrón con sus pastos, y además Libná y sus pastos,

[[joshua-21-14]]
^14^ Yattir con sus pastos, Estemoa con sus pastos

[[joshua-21-15]]
^15^ Jolón con sus pastos, Debir con sus pastos,

[[joshua-21-16]]
^16^ Asan con sus pastos, Yutta con sus pastos, Bet Semes con sus pastos: nueve ciudades de esas dos tribus.

[[joshua-21-17]]
^17^ De la tribu de Benjamín, Gabaón y sus pastos, Gueba y sus pastos,

[[joshua-21-18]]
^18^ Anatot y sus pastos, Almón y sus pastos: cuatro ciudades.

[[joshua-21-19]]
^19^ Total de las ciudades de los sacerdotes hijos de Aarón: trece ciudades con sus pastos.

[[joshua-21-20]]
^20^ A los clanes de los hijos de Quehat, a los levitas restantes entre los hijos de Quehat, les tocaron en suerte ciudades de la tribu de Efraím.

[[joshua-21-21]]
^21^ Se les dio, como ciudad de asilo para los homicidas, Siquem con sus pastos, en la montaña de Efraím, y además Guézer con sus pastos.

[[joshua-21-22]]
^22^ Quibsáyim con sus pastos, Bet Jorón con sus pastos: cuatro ciudades.

[[joshua-21-23]]
^23^ De la tribu de Dan, Eltequé con sus pastos, Guibbetón con sus pastos,

[[joshua-21-24]]
^24^ Ayyalón con sus pastos, Gat Rimmón con sus pastos: cuatro ciudades.

[[joshua-21-25]]
^25^ De la media tribu de Manasés, Tanak con sus pastos y Yibleam con sus pastos: dos ciudades.

[[joshua-21-26]]
^26^ Total: diez ciudades con sus pastos para lo restantes clanes de los hijos de Quehat.

[[joshua-21-27]]
^27^ A los hijos de Guersón, de los clanes levíticos, les dieron: de la media tribu de Manasés, como ciudad de asilo para los homicidas, Golán en Basán con sus pastos, y Astarot con sus pastos: dos ciudades.

[[joshua-21-28]]
^28^ De la tribu de Isacar, Quisyón con sus pastos, Daberat con sus pastos

[[joshua-21-29]]
^29^ Yarmut con sus pastos, En Gannim con sus pastos: cuatro ciudades.

[[joshua-21-30]]
^30^ De la tribu de Aser, Misal con sus pastos, Abdón con sus pastos,

[[joshua-21-31]]
^31^ Jelcat con sus pastos, Rejob con sus pastos: cuatro ciudades.

[[joshua-21-32]]
^32^ De la tribu de Neftalí, como ciudad de asilo para los homicidas, Quedes en Galilea con sus pastos, Jammot Dor con sus pastos, Raqcat con sus pastos: tres ciudades.

[[joshua-21-33]]
^33^ Total de ciudades de los guersonitas, por clanes: trece ciudades con sus pastos.

[[joshua-21-34]]
^34^ A los clanes de los hijos de Merarí, al resto de los levitas: de la tribu de Zabulón: Yoqneam con sus pastos, Cartá con sus pastos,

[[joshua-21-35]]
^35^ Rimmón con sus pastos, Nahalal con sus pastos: cuatro ciudades;

[[joshua-21-36]]
^36^ al otro lado del Jordán, de la tribu de Rubén, como ciudad de asilo para los homicidas, Béser en el desierto, en el llano, con sus pastos, y además Yahás con sus pastos,

[[joshua-21-37]]
^37^ Quedemot con sus pastos, Mefaat con sus pastos: cuatro ciudades.

[[joshua-21-38]]
^38^ De la tribu de Gad, como ciudad de asilo para los homicidas, Ramot en Galaad, y Majanáyim

[[joshua-21-39]]
^39^ Jesbón con sus pastos, Yazer con sus pastos: cuatro ciudades.

[[joshua-21-40]]
^40^ Total de ciudades asignadas por suerte a los hijos de Merarí, por clanes, es decir, al resto de los clanes levíticos: doce ciudades.

[[joshua-21-41]]
^41^ Total de las ciudades de los levitas en medio de la propiedad de los israelitas: 48 ciudades con sus pastos.

[[joshua-21-42]]
^42^ Cada una de las ciudades comprendía la ciudad y los pastos circundantes. Así todas las ciudades mencionadas.

[[joshua-21-43]]
^43^ Yahveh dio a los israelitas toda la tierra que había jurado dar a sus padres. La ocuparon y se establecieron en ella.

[[joshua-21-44]]
^44^ Yahveh les concedió paz en todos sus confines, tal como había jurado a sus padres, y ninguno de sus enemigos pudo hacerles frente. Yahveh entregó a todos sus enemigos en sus manos.

[[joshua-21-45]]
^45^ No falló una sola de todas las espléndidas promesas que Yahveh había hecho a la casa de Israel. Todo se cumplió.
[[joshua-22]]
== Capítulo 22

[[joshua-22-1]]
^1^ Josué convocó a los rubenitas, a los gaditas y a la media tribu de Manasés,

[[joshua-22-2]]
^2^ y les dijo: «Habéis cumplido todo lo que os mandó Moisés, siervo de Yahveh, y habéis atendido a mis órdenes siempre que os he mandado algo.

[[joshua-22-3]]
^3^ No habéis abandonado a vuestros hermanos durante tan largo tiempo hasta el día de hoy; habéis cumplido la orden que os encomendó Yahveh vuestro Dios.

[[joshua-22-4]]
^4^ Ahora Yahveh vuestro Dios ha dado a vuestros hermnaos el descanso que les había prometido. Volveos, pues, e id a vuestras tiendas, a la tierra de vuestra propiedad, la que os dio Moisés, siervo de Yahveh, al otro lado del Jordán.

[[joshua-22-5]]
^5^ Unicamente preocupaos de guardar el mandato y la Ley que os dio Moisés, siervo de Yahveh: que améis a Yahveh vuestro Dios, que sigáis siempre sus caminos, que guardéis sus mandamientos y os mantengáis unidos a él y le sirváis con todo vuestro corazón y con toda vuestra alma».

[[joshua-22-6]]
^6^ Josué los bendijo y los despidió, y ellos se fueron a sus tiendas.

[[joshua-22-7]]
^7^ Moisés había dado a la media tribu de Manasés su parte en Basán; a la otra media se la dio Josué entre sus hermanos, al lado occidental del Jordán. Cuando los mandó Josué a sus tiendas, les dio la bendición

[[joshua-22-8]]
^8^ y les dijo: «Volvéis a vuestras tiendas con grandes riquezas, rebaños numerosos, plata, oro, bronce, hierro y gran cantidad de vestidos; repartid con vuestros hermanos el botín de vuestros enemigos».

[[joshua-22-9]]
^9^ Los rubenitas y los gaditas, con la media tribu de Manasés, se volvieron y dejaron a los israelitas en Silo, en la tierra de Canaán, para volver a la tierra de Galaad, tierra de su propiedad donde se habían establecido según la orden de Yahveh dada por medio de Moisés.

[[joshua-22-10]]
^10^ Cuando llegaron a los circulos de piedras del Jordán, en tierra de Canaán, los rubenitas y los gaditas y la media tribu de Manasés levantaron allí un altar a orillas del Jordán, un altar de grandioso aspecto.

[[joshua-22-11]]
^11^ Se enteraron los israelitas y dijeron: «Mirad, los rubenitas, los gaditas y la media tribu de Manasés han levantado ese altar, frente al país de Canaán, junto a los círculos de piedras del Jordán, del lado de los israelitas».

[[joshua-22-12]]
^12^ Al oír esto los israelitas, se reunió en Silo toda la comunidad de los israelitas para hacerles guerra.

[[joshua-22-13]]
^13^ Los israelitas enviaron donde los rubenitas, los gaditas y la media tribu de Manasés, al país de Galaad, al sacerdote Pinjás, hijo de Eleazar

[[joshua-22-14]]
^14^ y a diez principales con él, un principal por cada familia, por cada tribu de Israel: cada uno de ellos era cabeza de su familia en los clanes de Israel.

[[joshua-22-15]]
^15^ Cuando llegaron donde los rubenitas, los rubenitas, los gaditas y la media tribu de Manasés, al país de Galaad, les hablaron así:

[[joshua-22-16]]
^16^ «Esto ha dicho toda la comunidad de Yahveh: ¿Qué significa esa prevaricación que habéis cometido contra el Dios de Israel, apartándoos hoy de Yahveh, al construiros un altar, rebelándoos hoy contra Yahveh?

[[joshua-22-17]]
^17^ «¿No teníamos bastante con el crimen de Peor, del que hoy todavía no hemos acabado de purificarnos, a pesar de que vino la plaga sobre la comunidad de Yahveh?

[[joshua-22-18]]
^18^ Si vosotros hoy os apartáis de Yahveh, hoy os rebeláis vosotros contra Yahveh, y mañana se encenderá él contra toda la comunidad de Israel.

[[joshua-22-19]]
^19^ «Ahora bien, si nos parece impura vuestra propiedad, pasad a la tierra de propiedad de Yahveh, donde ha fijado su morada, y estableceos entre nosotros. Pero no os rebeléis contra Yahveh, ni nos arrastréis en vuestra rebeldía al construiros un altar aparte del altar de Yahveh nuestro Dios.

[[joshua-22-20]]
^20^ ¿No prevaricó Akán, hijo de Zéraj, en el anatema, y la Coléra alcanzó a toda la comunidad de Israel, aunque él no era más que un solo individuo? ¿No murió por su crimen?»

[[joshua-22-21]]
^21^ Respondieron los rubenitas, los gaditas y la media tribu de Manasés y dijeron a los jefes de los clanes de Israel:

[[joshua-22-22]]
^22^ «El Dios de los dioses, Yahveh, el Dios de los dioses, Yahveh, lo sabe bien, y que lo sepa también Israel: si ha habido por nuestra parte rebelión o prevaricación contra Yahveh, que no nos salve hoy;

[[joshua-22-23]]
^23^ y si hemos levantado un altar para apartarnos de Yahveh y para ofrecer en él holocausto y oblación o para hacer sobre él sacrificios de comunión, que Yahveh nos lo demande.

[[joshua-22-24]]
^24^ En verdad, lo hemos hecho así por preocupación y razonadamente, diciéndonos: El día de mañana podrían decir vuestros hijos a los nuestros: “¿Qué tenéis que ver vosotros con Yahveh el Dios de Israel?

[[joshua-22-25]]
^25^ Yahveh ha puesto entre nosotros y vosotros, rubenitas y gaditas, la frontera del Jordán. No tenéis parte con Yahveh.” Así vuestros hijos harían que nuestros hijos dejaran de temer a Yahveh.

[[joshua-22-26]]
^26^ «Y nos hemos dicho: Vamos a construir este altar, pero no para holocaustos, ni sacrificios,

[[joshua-22-27]]
^27^ sino para que sea testigo entre nosotros y vosotros y entre nuestros descendientes después de nosotros, de que rendimos culto a Yahveh en su presencia con nuestros holocaustos, nuestras víctimas y nuestros sacrificios de comunión. Así no podrán decir mañana vuestros hijos a los nuestros: “No tenéis parte con Yahveh.”

[[joshua-22-28]]
^28^ No hemos dicho: Si llega a suceder que nos hablen así a nosotros o el día de mañana a nuestros descendientes, les podremos responder: “Mirad la edificación del altar de Yahveh que hicieron nuestros padres, no para ofrecer holocaustos ni sacrificios, sino como testigo entre nosotros y vosotros.”

[[joshua-22-29]]
^29^ Lejos de nosotros rebelarnos contra Yahveh y desertar hoy de su servicio, levantando, para ofrecer en él holocaustos, oblaciones o sacrificios, un altar aparte del altar de Yahveh nuestro Dios erigido delante de su morada».

[[joshua-22-30]]
^30^ Cuando el sacerdote Pinjás, los principales de la comunidad y los jefes de los clanes de Israel que le acompañaban, oyeron las palabras pronunciadas por los gaditas, los rubenitas y los manasitas, les pareció bien.

[[joshua-22-31]]
^31^ Y el sacerdote Pinjás, hijo de Eleazar, dijo a los rubenitas, los gaditas y los manasitas: «Ahora reconocemos que Yahveh está en medio de nosotros, pues no habéis cometido tan grande prevaricación contra él. Así habéis salvado a los israelitas de la mano de Yahveh».

[[joshua-22-32]]
^32^ El sacerdote Pinjás, hijo de Eleazar, y los principales, dejando a los rubenitas y a los gaditas, volvieron del país de Galaad al de Canaán, a donde los israelitas, y les dieron la respuesta.

[[joshua-22-33]]
^33^ La cosa pareció bien a los israelitas: los israelitas dieron gracias a Dios y no hablaron más de hacerles la guerra y devastar el territorio habitado por los rubenitas y los gaditas.

[[joshua-22-34]]
^34^ Los rubenitas y gaditas llamaron al altar..., porque decían: «Será testigo entre nosotros de que Yahveh es Dios».
[[joshua-23]]
== Capítulo 23

[[joshua-23-1]]
^1^ Sucedió, mucho tiempo después de que Yahveh concediera a Israel la paz de todos los enemigos de alrededor, - Josué era ya viejo y avanzado en días -

[[joshua-23-2]]
^2^ que Josué convocó a todo Israel, a sus ancianos, sus jefes, sus jueces, sus escribas y les dijo: «Yo ya soy viejo, avanzado en días;

[[joshua-23-3]]
^3^ y vosotros habéis visto todo lo que Yahveh, vuestro Dios, ha hecho en atención a vosotros con todos estos pueblos; pues Yahveh vuestro Dios era el que combatía por vosotros.

[[joshua-23-4]]
^4^ Mirad, yo os he dado por suertes, como heredad para vuestras tribus, esos pueblos que quedan por conquistar, así como todos los pueblos que yo exterminé desde el Jordán hasta el mar Grande de occidente.

[[joshua-23-5]]
^5^ Yahveh mismo, vuestro Dios, los arrojará delante de vosotros, los expulsará de delante de vosotros, y vosotros tomaréis posesión de su tierra, como os lo ha prometido Yahveh vuestro Dios.

[[joshua-23-6]]
^6^ «Esforzaos mucho en guardar y cumplir todo lo que está escrito en el libro de la Ley de Moisés, no apartándoos de ella ni a la derecha ni a la izquierda,

[[joshua-23-7]]
^7^ no mezclándoos con esos pueblos que quedan todavía entre vosotros. No recordaréis el nombre de sus dioses ni juraréis por ellos, no les serviréis ni os postraréis ante ellos,

[[joshua-23-8]]
^8^ sino manteneos unidos a Yahveh vuestro Dios, como habéis hecho hasta el día de hoy.

[[joshua-23-9]]
^9^ Yahveh ha arrojado de vuestra presencia a pueblos numerosos y fuertes, y nadie os ha podido resistir hasta el presente.

[[joshua-23-10]]
^10^ Uno solo de vosotros perseguía a mil, porque Yahveh mismo, vuestro Dios, peleaba por vosotros, como os lo había prometido.

[[joshua-23-11]]
^11^ Tendréis buen cuidado, por vuestra vida, de amar a Yahveh vuestro Dios.

[[joshua-23-12]]
^12^ «Pero si os desviáis y os unís a ese resto de naciones que quedan todavía entre vosotros, emparentáis con ellas y entráis en tratos con ellas,

[[joshua-23-13]]
^13^ tened por sabido que Yahveh vuestro Dios no seguirá arrojando de delante de vosotros a esos pueblos; serán para vosotros red, lazo, espinas en vuestros costados y aguijones en vuestros ojos, hasta que desaparezcáis de esta espléndida tierra que os ha dado Yahveh vuestro Dios.

[[joshua-23-14]]
^14^ «Mirad que yo me voy ya por el camino de todo el mundo. Reconoced con todo vuestro corazón y con toda vuestra alma que, de todas las promesas que Yahveh vuestro Dios había hecho en vuestro favor, no ha fallado ni una sola: todas se os han cumplido. Ni una sola ha fallado.

[[joshua-23-15]]
^15^ «Pues de la misma manera que se os han cumplido todas las espléndidas promesas hechas por Yahveh vuestro Dios en vuestro favor, igualmente acarreará Yahveh contra vosotros todas sus amenazas, hasta borraros de la espléndida tierra que Yahveh vuestro Dios os ha dado.

[[joshua-23-16]]
^16^ «Si quebrantáis la alianza que Yahveh vuestro Dios os ha impuesto, si vos vais a servir a otros dioses, y os postráis ante ellos, la ira de Yahveh se encenderá contra vosotros y desapareceréis rápidamente de la espléndida tierra que os ha dado».
[[joshua-24]]
== Capítulo 24

[[joshua-24-1]]
^1^ Josué reunió a todas las tribus de Israel en Siquem, llamó a los ancianos de Israel, a sus jefes, jueces y escribas que se situaron en presencia de Dios.

[[joshua-24-2]]
^2^ Josué dijo a todo el pueblo: «Esto dice Yahveh el Dios de Israel: Al otro lado del Río habitaban antaño vuestros padres, Téraj, padre de Abraham y de Najor, y servían a otros dioses.

[[joshua-24-3]]
^3^ Yo tomé a vuestro padre Abraham del otro lado del Río y le hice recorrer toda la tierra de Canaán, multipliqué su descendencia y le di por hijo a Isaac.

[[joshua-24-4]]
^4^ A Isaac le di por hijos a Jacob y Esaú. A Esaú le di en propiedad la montaña de Seír. Jacob y sus hijos bajaron a Egipto.

[[joshua-24-5]]
^5^ Envié después a Moisés y Aarón y herí a Egipto con los prodigios que obré en medio de él. Luego os saqué de allí.

[[joshua-24-6]]
^6^ Saqué a vuestros padres de Egipto y llegasteis al mar; los egipcios persiguieron a vuestros padres con los carros y sus guerreros hasta el mar de Suf.

[[joshua-24-7]]
^7^ Clamaron entonces a Yahveh, el cual tendió unas densas nieblas entre vosotros y los egipcios, e hizo volver sobre ellos el mar, que los cubrió. Visteis con vuestros propios ojos lo que hice con Egipto; luego habitasteis largo tiempo en el desierto.

[[joshua-24-8]]
^8^ Os introduje después en la tierra de los amorreos, que habitaban al otro lado del Jordán; ellos os declararon la guerra y yo los entregué en vuestras manos; y así pudisteis poseer su tierra, porque yo los exterminé delante de vosotros.

[[joshua-24-9]]
^9^ Después se levantó Balaq, hijo de Sippor, rey de Moab, para pelear contra Israel, y mandó llamar a Balaam, hijo de Beor, para que os maldijera.

[[joshua-24-10]]
^10^ Pero no quise escuchar a Balaam, y hasta tuvo que bendeciros; así os salvé yo de su mano.

[[joshua-24-11]]
^11^ «Pasasteis el Jordán y llegasteis a Jericó; pero las gentes de Jericó os hicieron la guerra, igual que los amorreos, los perizitas, los cananeos, los hititas, los guirgasitas, los jivitas y los jebuseos, pero yo los entregué en vuestras manos.

[[joshua-24-12]]
^12^ Mandé delante de vosotros avispas que expulsaron, antes que llegarais, a los dos reyes de los amorreos; no fue con tu espada ni con tu arco.

[[joshua-24-13]]
^13^ Os he dado una tierra que no os ha costado fatiga, unas ciudades que no habéis construido y en las que sin embargo habitáis, viñas y olivares que no habéis plantado y de las que os alimentáis.

[[joshua-24-14]]
^14^ «Ahora, pues, temed a Yahveh y servidle perfectamente, con fidelidad; apartaos de los dioses a los que sirvieron vuestros padres más allá del Río y en Egipto y servid a Yahveh.

[[joshua-24-15]]
^15^ Pero, si no os parece bien servir a Yahveh, elegid hoy a quién habéis de servir, o a los dioses a quienes servían vuestros padres más allá del Río, o a los dioses de los amorreos en cuyo país habitáis ahora. Yo y mi familia serviremos a Yahveh».

[[joshua-24-16]]
^16^ El pueblo respondió: «Lejos de nosotros abandonar a Yahveh para servir a otros dioses.

[[joshua-24-17]]
^17^ Porque Yahveh nuestro Dios es el que nos hizo subir, a nosotros y a nuestros padres, de la tierra de Egipto, de la casa de servidumbre, y el que delante de nuestros ojos obró tan grandes señales y nos guardó por todo el camino que recorrimos y en todos los pueblos por los que pasamos.

[[joshua-24-18]]
^18^ Además Yahveh expulsó delante de nosotros a todos esos pueblos y a los amorreos que habitaban en el país. También nosotros serviremos a Yahveh, porque él es nuestro Dios».

[[joshua-24-19]]
^19^ Entonces Josué dijo al pueblo: «No podréis servir a Yahveh, porque es un Dios santo, es un Dios celoso, que no perdonará ni vuestras rebeldías ni vuestros pecados.

[[joshua-24-20]]
^20^ Si abandonáis a Yahveh para servir a los dioses del extranjero, él a su vez traerá el mal sobre vosotros y acabará con vosotros, después de haberos hecho tanto bien».

[[joshua-24-21]]
^21^ El pueblo respondió a Josué: «No; nosotros serviremos a Yahveh».

[[joshua-24-22]]
^22^ Josué dijo al pueblo: «Vosotros sois testigos contra vosotros mismos de que habéis elegido a Yahveh para servirle». Respondieron ellos: «¡Testigos somos!» -

[[joshua-24-23]]
^23^ «Entonces, apartad los dioses del extranjero que hay en medio de vosotros e inclinad vuestro corazón hacia Yahveh, Dios de Israel».

[[joshua-24-24]]
^24^ El pueblo respondió a Josué: «A Yahveh nuestro Dios serviremos y a sus voz atenderemos».

[[joshua-24-25]]
^25^ Aquél día, Josué pactó una alianza para el pueblo; le impuso decretos y normas en Siquem.

[[joshua-24-26]]
^26^ Josué escribió estas palabras en el libro de la Ley de Dios. Tomó luego una gran piedra y la plantó allí, al pie de la encina que hay en el santuario de Yahveh.

[[joshua-24-27]]
^27^ Josué dijo al todo el pueblo: «Mirad, esta piedra será testigo contra nosotros, pues ha oído todas las palabras que Yahveh ha hablado con nosotros; ella será testigo contra vosotros para que no reneguéis de vuestro Dios».

[[joshua-24-28]]
^28^ Y Josué despidió al pueblo cada uno a su heredad.

[[joshua-24-29]]
^29^ Después de estos acontecimientos, murió Josué, hijo de Nun, siervo de Yahveh, a la edad de 110 años.

[[joshua-24-30]]
^30^ Fue enterrado en el término de su heredad, en Timnat Séraj, que está en la montaña de Efraím, al norte del monte Gaás.

[[joshua-24-31]]
^31^ Israel sirvió a Yahveh todos los días de Josué y todos los días de los ancianos que siguieron viviendo después de Josué y que sabían todas las hazañas que Yahveh había hecho en favor de Israel.

[[joshua-24-32]]
^32^ Los huesos de José, que los hijos de Israel habían subido de Egipto, fueron sepultados en Siquem, en la parcela de campo que había comprado Jacob a los hijos de Jamor, padre de Siquem, por cien pesos, y que pasó a ser heredad de los hijos de José.

[[joshua-24-33]]
^33^ También Eleazar, hijo de Aarón, murió y lo enterraron en Guibeá, ciudad de su hijo Pinjás, que le había sido dada en la montaña de Efraím.
