[[judges]]
= Jueces

[[judges-1]]
== Capítulo 1

[[judges-1-1]]
^1^ Después de la muerte de Josué, los israelitas hicieron esta consulta a Yahveh: «¿Quién de nosotros subirá el primero a combatir a los cananeos?»

[[judges-1-2]]
^2^ Yahveh repondió: «Subirá Judá, he puesto el país en sus manos».

[[judges-1-3]]
^3^ Judá dijo a su hermano Simeón: «Sube conmigo al territorio que me ha tocado; atacaremos al cananeo; y luego yo también iré contigo a tu territorio». Y Simeón marchó con él.

[[judges-1-4]]
^4^ Subió Judá; Yahveh puso en sus manos a los cananeos y a los perizitas, y derrotaron en Bezeq a 10.000 hombres.

[[judges-1-5]]
^5^ Habiendo encontrado en Bezeq a Adoni Bézeq, le atacaron y derrotaron a los cananeos y a los perizitas.

[[judges-1-6]]
^6^ Huyó Adoni Bézeq, pero le persiguieron, le capturaron y le cortaron los pulgares de manos y pies.

[[judges-1-7]]
^7^ Y Adoni Bézeq dijo: «Setenta reyes, con los pulgares de manos y pies cortados, andaban recogiendo migajas bajo mi mesa. Según lo que yo hice, así me ha pagado Dios». Le llevaron a Jerusalén, y allí murió.

[[judges-1-8]]
^8^ (Los hijos de Judá atacaron a Jerusalén, la tomaron, la pasaron a cuchillo y prendieron fuego a la ciudad).

[[judges-1-9]]
^9^ Después, los hijos de Judá bajaron a atacar a los cananeos, que ocupaban la Montaña, el Négueb y la Tierra Baja.

[[judges-1-10]]
^10^ Luego Judá marchó contra los cananeos que habitaban en Hebrón - el nombre de Hebrón era antes Quiryat Arbá - y derrotó a Sesay, Ajimán y Talmay.

[[judges-1-11]]
^11^ De allí marchó contra los habitantes de Debir - el nombre de Debir era antes Quiryat Séfer. -

[[judges-1-12]]
^12^ Y Caleb dijo: «Al que derrote a Quiryat Séfer y la tome, le daré mi hija Aksá por mujer».

[[judges-1-13]]
^13^ La tomó Otniel, hijo de Quenaz, el hermano menor de Caleb. Y éste le dio su hija Aksá por mujer.

[[judges-1-14]]
^14^ Cuando ella vino donde el marido, le incitó a que pidiera a su padre un campo. Ella se apeó del asno, y Caleb le preguntó: «¿Qué quieres?»

[[judges-1-15]]
^15^ Ella respondió: «Hazme un regalo. Ya que me has dado la tierra del Négueb, dame fuentes de agua». Y Caleb le dio las fuentes de arriba y las fuentes de abajo.

[[judges-1-16]]
^16^ Los hijos de Jobab el quenita, suegro de Moisés, subieron con los hijos de Judá de la ciudad de las Palmeras al desierto de Judá, que está en el Négueb de Arad, y fueron a habitar con el pueblo.

[[judges-1-17]]
^17^ Judá se fue con su hermano Simeón, derrotaron a los cananeos que habitaban en Sefat y consagraron la ciudad al anatema. Por eso la ciudad se llamó Jormá.

[[judges-1-18]]
^18^ Judá se apoderó de Gaza y su comarca, de Ascalón y su comarca, de Ecrón y su comarca;

[[judges-1-19]]
^19^ Yahveh estuvo con Judá, que conquistó la Montaña; pero no pudo expulsar a los habitantes del llano, porque tenían carros de hierro.

[[judges-1-20]]
^20^ Dieron Hebrón a Caleb, según el mandato de Moisés: y él arrojó de allí a los tres hijos de Anaq.

[[judges-1-21]]
^21^ Los hijos de Benjamín no expulsaron a los jebuseos que habitaban en Jerusalén; por eso los jebuseos siguen habitando en Jerusalén con los hijos de Benjamín, hasta el día de hoy.

[[judges-1-22]]
^22^ También la casa de José subió a Betel; Yahveh estuvo con ella.

[[judges-1-23]]
^23^ La casa de José hizo una exploración por Betel. (Antes la ciudad se llamaba Luz.)

[[judges-1-24]]
^24^ Los espías vieron a un hombre que salía de la ciudad y le dijeron: «Indícanos la entrada de la ciudad y te lo agradeceremos».

[[judges-1-25]]
^25^ El les enseñó la entrada de la ciudad: la pasaron a cuchillo, y dejaron libre a aquel hombre con toda su familia.

[[judges-1-26]]
^26^ El hombre se fue al país de los hititas y construyó una ciudad, a la que llamó Luz. Es el nombre que tiene hasta la fecha.

[[judges-1-27]]
^27^ Manasés no se apoderó de Bet Seán y sus filiales, ni de Tanak y sus filiales. No expulsó a los habitantes de Dor y sus filiales, ni a los de Yibleam y sus filiales, ni a los de Meguiddó y sus filiales: los cananeos siguieron ocupando el territorio.

[[judges-1-28]]
^28^ Sin embargo, cuando Israel cobró más fuerza, sometió a los cananeos a tributo, aunque no llegó a expulsarlos.

[[judges-1-29]]
^29^ Tampoco Efraím expulsó a los cananeos que habitaban en Guézer, de manera que los cananeos siguieron viviendo en Guézer, en medio de Israel.

[[judges-1-30]]
^30^ Zabulón no expulsó a los habitantes de Quitrón, ni a los de Nahalol. Los cananeos se quedaron en medio de Zabulón, pero fueron sometidos a tributo.

[[judges-1-31]]
^31^ Aser no expulsó a los habitantes de Akko, ni a los de Sidón, de Majaleb, de Akzib, de Jelbá, de Afiq, ni de Rejob.

[[judges-1-32]]
^32^ Los aseritas se establecieron, pues, entre los cananeos que habitaban en el país, porque no los expulsaron.

[[judges-1-33]]
^33^ Neftalí no expulsó a los habitantes de Bet Semes, ni a los de Bet Anat, y se estableció entre los cananeos que habitaban en el país; pero los habitantes de Bet Semes y de Bet Anat fueron sus tributarios.

[[judges-1-34]]
^34^ Los amorreos rechazaron hacia la montaña a los hijos de Dan sin dejarles bajar a la llanura.

[[judges-1-35]]
^35^ Los amorreos se mantuvieron en Har Jéres, en Ayyalón y en Saalbim, pero luego pesó sobre ellos la mano de la casa de José y fueron reducidos a tributo.

[[judges-1-36]]
^36^ (La frontera de los edomitas va desde la cuesta de los Escorpiones, desde la Peña, y hacia arriba.)
[[judges-2]]
== Capítulo 2

[[judges-2-1]]
^1^ El Angel de Yahveh subió de Guilgal a Betel y dijo: «Yo os hice subir de Egipto y os introduje en la tierra que había prometido con juramento a vuestros padres. Yo dije: “No romperé jamás mi alianza con vosotros.

[[judges-2-2]]
^2^ Pero vosotros no pactaréis con los habitantes de este país; sino que destruiréis sus altares.” Pero no habéis escuchado mi voz. ¿Por qué habéis hecho esto?

[[judges-2-3]]
^3^ Por eso os digo: No los arrojaré delante de vosotros; serán vuestros opresores y sus dioses una trampa para vosotros».

[[judges-2-4]]
^4^ Así que el Angel de Yahveh dijo estas palabras a todos los israelitas, el pueblo se puso a llorar a gritos.

[[judges-2-5]]
^5^ Llamaron a aquel lugar Bokim, y ofrecieron allí sacrificios a Yahveh.

[[judges-2-6]]
^6^ Josué despidió al pueblo, y los israelitas se volvieron cada uno a su heredad para ocupar la tierra.

[[judges-2-7]]
^7^ El pueblo sirvió a Yahveh en vida de Josué y de los ancianos que le sobrevivieron y que habían sido testigos de todas las grandes hazañas que Yahveh había hecho a favor de Israel.

[[judges-2-8]]
^8^ Josué, hijo de Nun, siervo de Yahveh, murió a la edad de 110 años.

[[judges-2-9]]
^9^ Le enterraron en el término de su heredad, en Timnat Jeres, en la montaña de Efraím, al norte del monte Gaás.

[[judges-2-10]]
^10^ También aquella generación fue a reunirse con sus padres y les sucedió otra generación que no conocía a Yahveh ni lo que había hecho por Israel.

[[judges-2-11]]
^11^ Entonces los hijos de Israel hicieron lo que desagradaba a Yahveh y sirvieron a los Baales.

[[judges-2-12]]
^12^ Abandonaron a Yahveh, el Dios de sus padres, que los había sacado de la tierra de Egipto, y siguieron a otros dioses de los pueblos de alrededor; se postraron ante ellos, irritaron a Yahveh;

[[judges-2-13]]
^13^ dejaron a Yahveh y sirvieron a Baal y a las Astartés.

[[judges-2-14]]
^14^ Entonces se encendió la ira de Yahveh contra Israel. Los puso en manos de salteadores que los despojaron, los dejó vendidos en manos de los enemigos de alrededor y no pudieron ya sostenerse ante sus enemigos.

[[judges-2-15]]
^15^ En todas sus campañas la mano de Yahveh intervenía contra ellos para hacerles daño, como Yahveh se lo tenía dicho y jurado. Los puso así en gran aprieto.

[[judges-2-16]]
^16^ Entonces Yahveh suscitó jueces que los salvaron de la mano de los que los saqueaban.

[[judges-2-17]]
^17^ Pero tampoco a sus jueces los escuchaban. Se prostituyeron siguiendo a otros dioses, y se postraron ante ellos. Se desviaron muy pronto del camino que habían seguido sus padres, que atendían a los mandamientos de Yahveh; no los imitaron.

[[judges-2-18]]
^18^ Cuando Yahveh les suscitaba jueces, Yahveh estaba con el juez y los salvaba de la mano de sus enemigos mientras vivía el juez, porque Yahveh se conmovía de los gemidos que proferían ante los que los maltrataban y oprimían.

[[judges-2-19]]
^19^ Pero cuando moría el juez, volvían a corromperse más todavía que sus padres, yéndose tras de otros dioses, sirviéndoles y postrándose ante ellos, sin renunciar en nada a las prácticas y a la conducta obstinada de sus padres.

[[judges-2-20]]
^20^ Se encendió la ira de Yahveh contra el pueblo de Israel y dijo: «Ya que este pueblo ha quebrantado la alianza que prescribí a sus padres y no ha escuchado mi voz,

[[judges-2-21]]
^21^ tampoco yo arrojaré en adelante de su presencia a ninguno de los pueblos que dejó Josué cuando murió».

[[judges-2-22]]
^22^ Era para probar con ellos a Israel, a ver si seguían o no los caminos de Yahveh, como los habían seguido sus padres.

[[judges-2-23]]
^23^ Yahveh dejó en paz a estos pueblos, en vez de expulsarlos enseguida, y no los puso en manos de Josué.
[[judges-3]]
== Capítulo 3

[[judges-3-1]]
^1^ Estos son los pueblos que Yahveh dejó subsistir para probar con ellos a Israel, a cuantos no habían conocido ninguna de las guerras de Canaán.

[[judges-3-2]]
^2^ (Era sólo para que aprendieran las generaciones de los hijos de Israel, para enseñarles el arte de la guerra; por lo menos los que antes no lo habían conocido):

[[judges-3-3]]
^3^ los cinco príncipes de los filisteos y todos los cananeos, los sidonios y los hititas que vivían en el monte Líbano, desde la montaña de Baal Hermón hasta la entrada de Jamat.

[[judges-3-4]]
^4^ Sirvieron para probar con ellos a Israel, a ver si guardaban los mandamientos que Yahveh había prescrito a sus padres por medio de Moisés.

[[judges-3-5]]
^5^ Y los israelitas habitaron en medio de los cananeos, hititas, amorreos, perizitas, jivitas y jebuseos;

[[judges-3-6]]
^6^ se casaron con sus hijas, dieron sus propias hijas a los hijos de aquellos y sirvieron a sus dioses.

[[judges-3-7]]
^7^ Los israelitas hicieron lo que desagradaba a Yahveh. Se olvidaron de Yahveh su Dios y sirvieron a los Baales y a las Aserás.

[[judges-3-8]]
^8^ Se encendió la ira de Yahveh contra Israel y los dejó a merced de Kusán Riseatáyim, rey de Edom, y los israelitas sirvieron a Kusán Riseatáyim durante ocho años.

[[judges-3-9]]
^9^ Los israelitas clamaron a Yahveh y Yahveh suscitó a los israelitas un libertador que los salvó: Otniel, hijo de Quenaz y hermano menor de Caleb.

[[judges-3-10]]
^10^ El espíritu de Yahveh vino sobre él, fue juez de Israel y salió a la guerra. Yahveh puso en sus manos a Kusán Riseatáyim, rey de Edom y triumfó sobre Kusán Riseatáyim.

[[judges-3-11]]
^11^ El país quedó tranquilo cuarenta años. Y murió Otniel, hijo de Quenaz.

[[judges-3-12]]
^12^ Los israelitas volvieron a hacer lo que desagradaba a Yahveh; y Yahveh fortaleció a Eglón, rey de Moab, por encima de Israel, porque hacían lo que desagradaba a Yahveh.

[[judges-3-13]]
^13^ A Eglón se le juntaron los hijos de Ammón y de Amalec; salió y derrotó a Israel, y tomó la ciudad de las Palmeras.

[[judges-3-14]]
^14^ Los israelitas estuvieron sometidos a Eglón, rey de Moab, dieciocho años.

[[judges-3-15]]
^15^ Entonces los israelitas clamaron a Yahveh y Yahveh les suscitó un libertador: Ehúd, hijo de Guerá, benjaminita, que era zurdo. Los israelitas le encargaron de llevar el tributo a Eglón, rey de Moab.

[[judges-3-16]]
^16^ Ehúd se hizo un puñal de dos filos, de un codo de largo, se lo ciño debajo de la ropa sobre el muslo derecho,

[[judges-3-17]]
^17^ y presentó el tributo a Eglón, rey de Moab. Eglón era un hombre muy obeso.

[[judges-3-18]]
^18^ En cuanto terminó de presentar el tributo, Ehúd mandó marchar a la gente que había llevado el tributo;

[[judges-3-19]]
^19^ pero él, al llegar a los Idolos que hay en la región de Guilgal, volvió otra vez y dijo: «Tengo un mensaje secreto para ti ¡oh rey!» El rey respondió: ¡Silencio!» y salieron de su presencia todos los que estaban con él.

[[judges-3-20]]
^20^ Ehúd se le acercó . El rey estaba sentado en su galería fresca particular. Ehúd le dijo: «Tengo una palabra de Dios para tí». El rey se levantó de su silla.

[[judges-3-21]]
^21^ Ehúd alargó su mano izquierda, cogió el puñal de su cadera derecha y se lo hundió en el vientre.

[[judges-3-22]]
^22^ Detrás de la hoja entró incluso el mango, y la grasa se cerró sobre la hoja, pues Ehúd no le sacó el puñal del vientre. Luego escapó por la ventana.

[[judges-3-23]]
^23^ Ehúd salió por el pórtico; había cerrado tras de sí las puertas de la galería y echado el cerrojo.

[[judges-3-24]]
^24^ Después que se fue, llegaron los criados y vieron que las puertas de la galería tenían echado el cerrojo. Y se dijeron para sí: «Sin duda se está cubriendo los pies en el aposento de la galería fresca».

[[judges-3-25]]
^25^ Estuvieron esperando hasta quedar desconcertados, porque no acababan de abrirse las puertas de la galería. Cogieron la llave y abrieron. Su amo yacía en tierra, muerto.

[[judges-3-26]]
^26^ Mientras esperaban, Ehúd había huido: había pasado los Idolos y se había puesto a salvo en Hasseirá.

[[judges-3-27]]
^27^ En cuanto llegó tocó el cuerno en la montaña de Efraím y los israelitas bajaron con él de la montaña. El se puso al frente de ellos,

[[judges-3-28]]
^28^ y les dijo: «Seguidme, porque Yahveh ha entregado a Moab, vuestro enemigo, en vuestras manos». Bajaron tras él, cortaron a Moab los vados del Jordán y no dejaron pasar a nadie.

[[judges-3-29]]
^29^ Derrotaron en aquella ocasión a los de Moab; eran unos 10.000 hombres, todos fuertes y valientes, y no escapó ni uno.

[[judges-3-30]]
^30^ Aquél día fue humillado Moab bajo la mano de Israel, y el país quedó tranquilo ochenta años.

[[judges-3-31]]
^31^ Después de él vino Samgar, hijo de Anat. Derrotó a los filisteos, que eran seiscientos hombres, con una aguijada de bueyes; él también salvó a Israel.
[[judges-4]]
== Capítulo 4

[[judges-4-1]]
^1^ Cuando murió Ehúd los israelitas volvieron a hacer lo que desagradaba a Yahveh,

[[judges-4-2]]
^2^ y Yahveh los dejó a merced de Yabín, rey de Canaán, que reinaba en Jasor. El jefe de su ejército era Sísara, que habitaba en Jaróset Haggoyim.

[[judges-4-3]]
^3^ Entonces los israelitas clamaron a Yahveh. Porque Yabín tenía novecientos carros de hierro y había oprimido duramente a los israelitas durante veinte años.

[[judges-4-4]]
^4^ En aquel tiempo, Débora, una profetisa, mujer de Lappidot, era juez en Israel.

[[judges-4-5]]
^5^ Se sentaba bajo la palmera de Débora, entre Ramá y Betel, en la montaña de Efraím; y los israelitas subían donde ella en busca de justicia.

[[judges-4-6]]
^6^ Esta mandó llamar a Baraq, hijo de Abinoam, de Quédes de Neftalí, y le dijo: «¿Acaso no te ordena esto Yahveh, Dios de Israel: “Vete, y en el monte Tabor recluta y toma contigo 10.000 hombres de los hijos de Neftalí y de los hijos de Zabulón.

[[judges-4-7]]
^7^ Yo atraeré hacia ti al torrente Quison a Sísara,jefe del ejército de Yabín, con sus carros y sus tropas, y los pondré en tus manos”?»

[[judges-4-8]]
^8^ Baraq le respondió: «Si vienes tú conmigo, voy. Pero si no vienes conmigo, no voy, porque no sé en qué día me dará la victoria el Angel de Yahveh».

[[judges-4-9]]
^9^ «Iré contigo - dijo ella - sólo que entonces no será tuya la gloria del camino que emprendes, porque Yahveh entregará a Sísara en manos de una mujer». Débora se levantó y marchó con Baraq a Quédes.

[[judges-4-10]]
^10^ Y Baraq convocó en Quédes a Zabulón y Neftalí. Subieron tras él 10.000 hombres y Débora subió con el.

[[judges-4-11]]
^11^ Jéber el quenita, se había separado de la tribu de Caín y del clan de los hijos de Jobab, el suegro de Moisés; había plantado su tienda cerca de la Encina de Saanannim, cerca de Quédes.

[[judges-4-12]]
^12^ Le comunicaron a Sísara que Baraq, hijo de Abinoam, había subido al monte Tabor.

[[judges-4-13]]
^13^ Reunió Sísara todos sus carros, y todas las tropas que tenía y las llevó de Jaróset Haggoyim al Torrente de Quisón.

[[judges-4-14]]
^14^ Débora dijo a Baraq: «Levántate, porque este es el día en que Yahveh ha entregado a Sísara en tus manos. ¿No es cierto que Yahveh marcha delante de ti?» Baraq bajó del monte Tabor seguido de los 10.000 hombres.

[[judges-4-15]]
^15^ Yahveh sembró el panico en Sísara, en todos sus carros y en todo su ejército ante Baraq. Sísara bajó de su carro y huyó a pie.

[[judges-4-16]]
^16^ Baraq persiguió a los carros y al ejército hasta Jaróset Haggoyim. Todo el ejército de Sísara cayó a filo de espada: no quedó ni uno.

[[judges-4-17]]
^17^ Pero Sísara huyó a pie hacia la tienda de Yael, mujer de Jéber el quenita, porque reinaba la paz entre Yabín, rey de Jasor, y la casa de Jéber el quenita.

[[judges-4-18]]
^18^ Yael salió al encuentro de Sísara y le dijo: «Entra, señor mío, entra en mi casa. No temas». Y entró en su tienda y ella lo tapó con un cobertor.

[[judges-4-19]]
^19^ El le dijo: «Por favor, dame de beber un poco de agua, porque tengo sed». Ella abrió el odre de la leche, le dio de beber y lo volvió a tapar.

[[judges-4-20]]
^20^ El le dijo; «Estáte a la entrada de la tienda y si alguno viene, te pregunta y te dice: “¿Hay alguien aquí?, respóndele que no».

[[judges-4-21]]
^21^ Pero Yael, mujer de Jéber, cogió una clavija de la tienda, tomó el martillo en su mano, se le acercó callando y le hincó la clavija en la sien hasta clavarla en tierra. El estaba profundamente dormido, agotado de cansancio; y murió.

[[judges-4-22]]
^22^ Cuando llegó Baraq persiguiendo a Sísara, Yael salió a su encuentro y le dijo: «Ven, que te voy a mostrar al hombre que buscas». Entró donde ella, y Sísara yacía muerto con la clavija en la sien.

[[judges-4-23]]
^23^ Así humilló Dios aquel día a Yabín, rey de Canaán, ante los israelitas.

[[judges-4-24]]
^24^ La mano de los israelitas fue haciéndose cada vez más pesada sobre Yabín, rey de Canaán, hasta que acabaron con Yabín, rey de Canaán.
[[judges-5]]
== Capítulo 5

[[judges-5-1]]
^1^ Aquel día, Débora y Baraq, hijo de Abinoam, entonaron este cántico:

[[judges-5-2]]
^2^ Al soltarse en Israel la cabellera, cuando el pueblo se ofrece voluntario, ¡bendecid a Yahveh!

[[judges-5-3]]
^3^ ¡Escuchad, reyes! ¡Prestad oídos, príncipes! yo a Yahveh, yo voy a cantar. tocaré el salterio para Yahveh, Dios de Israel.

[[judges-5-4]]
^4^ Cuando saliste de Seír, Yahveh, cuando avanzaste por los campos de Edom, tembló la tierra, gotearon los cielos, las nubes en agua se fundieron.

[[judges-5-5]]
^5^ Los montes se licuaron delante de Yahveh, el del Sinaí, delante de Yahveh, el Dios de Israel.

[[judges-5-6]]
^6^ En los días de Samgar, hijo de Anat, en los días de Yael, no había caravanas; los que hollaban calzadas marchaban por senderos desviados,

[[judges-5-7]]
^7^ Vacíos en Israel quedaron los problados, vacíos hasta tu despertar, oh Débora, hasta tu despertar, oh madre de Israel.

[[judges-5-8]]
^8^ Se elegían dioses nuevos; por entonces la guerra en las puertas; ni un escudo se ve ni una lanza para 40.000 en Israel!

[[judges-5-9]]
^9^ Mi corazón con los jefes de Israel, con los voluntarios del pueblo. ¡Bendecid a Yahveh!

[[judges-5-10]]
^10^ Los que cabalgáis en blancas asnas, los que os sentáis sobre tapices, los que vais por el camino, cantad,

[[judges-5-11]]
^11^ al clamor de los repartidores junto a los abrevaderos. Allí se cantan los favores de Yahveh, los favores a sus poblados de Israel. (Entonces el pueblo de Yahveh bajó a las puertas).

[[judges-5-12]]
^12^ Despierta, Débora, despierta! ¡Despierta, despierta, entona un cantar! ¡Animo! ¡Arriba, Baraq! ¡Apresa a los que te apresaron, hijo de Abinoam!

[[judges-5-13]]
^13^ Entonces Israel bajó a las puertas, el pueblo de Yahveh bajó por él, como un héroe.

[[judges-5-14]]
^14^ Los principales de Efraím en el valle. Detrás de ti Benjamín entre tu gente. De Makir han bajado capitanes, de Zabulón los que manejan cetro.

[[judges-5-15]]
^15^ Los jefes de Isacar están con Débora, y Neftalí, con Baraq, en la llanura, lanzado tras sus huellas. En los arroyos de Rubén, magnánimas decisiones.

[[judges-5-16]]
^16^ ¿Por qué te has quedado en los corrales, escuchando silbidos entre los rebaños? (En los arroyos de Rubén, magnánimas decisiones.)

[[judges-5-17]]
^17^ Allende el Jordán, Galaad se queda, y Dan, ¿por qué vive en naves extranjeras? Aser se ha quedado a orillas del mar, tranquilo en sus puertos mora.

[[judges-5-18]]
^18^ Zabulón es un pueblo que reta a la muerte, y Neftalí, en las alturas del país.

[[judges-5-19]]
^19^ Vinieron los reyes, combatieron, entonces combatieron los reyes de Canaán, en Tanak, en las aguas de Meguiddó, mas sin lograr botín de plata.

[[judges-5-20]]
^20^ Desde los cielos lucharon las estrellas, desde sus órbitas lucharon contra Sísara.

[[judges-5-21]]
^21^ El torrente Quisón barriólos, ¡el viejo torrente, el torrente Quisón! ¡Avanza, alma mía, con denuedo!

[[judges-5-22]]
^22^ Cascos de caballos sacuden el suelo: ¡galopan, galopan sus corceles!

[[judges-5-23]]
^23^ Maldecid a Meroz, dice el Angel de Yahveh, maldecid, maldecid a sus moradores: pues no vinieron en ayuda de Yahveh, en ayuda de Yahveh como los héroes.

[[judges-5-24]]
^24^ ¡Bendita entre las mujeres Yael (la mujer de Jéber el quenita), entre las mujeres que habitan en tiendas, bendita sea!

[[judges-5-25]]
^25^ Pedía agua, le dio leche, en la copa de los nobles le sirvió nata.

[[judges-5-26]]
^26^ Tendió su mano a la clavija, la diestra al martillo de los carpinteros. Hirió a Sísara, le partió la cabeza, le golpeó y le partió la sien;

[[judges-5-27]]
^27^ a sus pies se desplomó, cayó, durmió, a sus pies se desplomó, cayó; donde se desplomó, allí cayó, deshecho.

[[judges-5-28]]
^28^ A la ventana se asoma y atisba la madre de Sísara, por las celosías: «¿Por qué tarda en llegar su carro? ¿por qué se retrasa el galopar de su carroza?

[[judges-5-29]]
^29^ La más discreta de sus princesas le responde; ella se lo repite a sí misma:

[[judges-5-30]]
^30^ ¡«Será que han cogido botín y lo reparten: una doncella, dos doncellas para cada guerrero; botín de paños de colores para Sísara, botín de paños de colores; un manto, dos mantos bordados para mi cuello!»

[[judges-5-31]]
^31^ ¡Así perezcan todos tus enemigos, oh Yahveh! ¡Y sean los que te aman como el salir del sol con todo su fulgor! Y el país quedó tranquilo cuarenta años.
[[judges-6]]
== Capítulo 6

[[judges-6-1]]
^1^ Los israelitas hicieron lo que desagradaba a Yahveh y Yahveh los entregó durante siete años en manos de Madián,

[[judges-6-2]]
^2^ y la mano de Madián pesó sobre Israel. Para escapar de Madián, los israelitas se valieron de las hendiduras de las montañas, de las cuevas y las cumbres escarpadas.

[[judges-6-3]]
^3^ Cuando sembraba Israel, venía Madián, con Amalec y los hijos de Oriente: subían contra Israel,

[[judges-6-4]]
^4^ acampaban en sus tierras y devastaban los productos de la tierra hasta la entrada de Gaza. No dejaban víveres en Israel: ni ovejas, ni bueyes, ni asnos,

[[judges-6-5]]
^5^ porque subían numerosos como langostas, con sus ganados y sus tiendas. Ellos y sus camellos eran innumerables e invadían el país para saquearlo.

[[judges-6-6]]
^6^ Así Madián redujo a Israel a una gran miseria y los israelitas clamaron a Yahveh.

[[judges-6-7]]
^7^ Cuando los israelitas clamaron a Yahveh por causa de Madián,

[[judges-6-8]]
^8^ Yahveh envió a los israelitas un profeta que les dijo: «Así habla Yahveh, Dios de Israel: Yo os hice subir de Egipto, y os saqué de la casa de servidumbre.

[[judges-6-9]]
^9^ Os libré de la mano de los egipcios y de todos los que os oprimían. Los arrojé de delante de vosotros, os di su tierra,

[[judges-6-10]]
^10^ y os dije: “Yo soy Yahveh, vuestro Dios. No veneréis a los dioses de los amorreos, en cuya tierra habitáis.” Pero no habéis escuchado mi voz».

[[judges-6-11]]
^11^ Vino el Angel de Yahveh y se sentó bajo el terebinto de Ofrá, que pertenecía a Joás de Abiézer. Su hijo Gedeón majaba trigo en el lagar para ocultárselo a Madián,

[[judges-6-12]]
^12^ cuando el Angel de Yahveh se le apareció y le dijo: «Yahveh contigo, valiente guerrero».

[[judges-6-13]]
^13^ Contestó Gedeón: «Perdón, señor mío. Si Yahveh está con nosotros ¿por qué nos ocurre todo esto? ¿Dónde están todos esos prodigios que nos cuentan nuestros padres cuando dicen: “¿No nos hizo subir Yahveh de Egipto?” Pero ahora Yahveh nos ha abandonado, nos ha entregado en manos de Madián..».

[[judges-6-14]]
^14^ Entonces Yahveh se volvió hacia él y dijo: «Vete con esa fuerza que tienes y salvarás a Israel de la mano de Madián. ¿No soy yo el que te envía?»

[[judges-6-15]]
^15^ Le respondió Gedeón: «Perdón, señor mío, ¿cómo voy a salvar yo a Israel? Mi clan es el más pobre de Manasés y yo el último en la casa de mi padre».

[[judges-6-16]]
^16^ Yahveh le respondió: «Yo estaré contigo y derrotarás a Madián como si fuera un hombre solo».

[[judges-6-17]]
^17^ Gedeón le dijo: «Si he hallado gracia a tus ojos dame una señal de que eres tú el que me hablas.

[[judges-6-18]]
^18^ No te marches de aquí, por favor, hasta que vuelva donde ti. Te traeré mi ofrenda y la pondré delante de ti». El respondió: «Me quedaré hasta que vuelvas».

[[judges-6-19]]
^19^ Gedeón se fue, preparó un cabrito y con una medida de harina hizo unas tortas ázimas; puso la carne en un canastillo y el caldo en una olla, y lo llevó bajo el terebinto. Cuando se acercaba,

[[judges-6-20]]
^20^ le dijo el Angel de Yahveh: «Toma la carne y las tortas ázimas, ponlas sobre esa roca y vierte el caldo». Gedeón lo hizo así.

[[judges-6-21]]
^21^ Entonces el Angel de Yahveh extendió la punta del bastón que tenía en la mano y tocó la carne y las tortas ázimas. Salió fuego de la roca, consumió la carne y las tortas ázimas, y el Angel de Yahveh desapareció de su vista.

[[judges-6-22]]
^22^ Entonces Gedeón se dio cuenta de que era el Angel de Yahveh y dijo: «¡Ay, mi señor Yahveh! ¡Pues he visto al Angel de Yahveh cara a cara!»

[[judges-6-23]]
^23^ Yahveh le respondió: «La paz sea contigo. No temas, no morirás».

[[judges-6-24]]
^24^ Gedeón levantó en aquel lugar un altar a Yahveh y lo llamó Yahveh-Paz. Todavía hoy está en Ofrá de Abiezer.

[[judges-6-25]]
^25^ Sucedió que aquella misma noche Yahveh dijo a Gedeón: «Toma el toro de tu padre, el toro de siete años; vas a derribar el altar de Baal propiedad de tu padre y cortar el cipo que está junto a él.

[[judges-6-26]]
^26^ Luego construirás a Yahveh tu Dios, en la cima de esa altura escarpada, un altar bien preparado. Tomarás el toro y lo quemarás en holocausto, con la leña del cipo que habrás cortado».

[[judges-6-27]]
^27^ Gedeón tomó entonces diez hombres de entre sus criados e hizo como Yahveh le había ordenado. Pero, como temía a su familia y a la gente de la ciudad, en lugar de hacerlo de día, lo hizo de noche.

[[judges-6-28]]
^28^ A la mañana siguiente se levantó la gente de la ciudad; el altar de Baal estaba derruido, el cipo que se alzaba junto a él, cortado; y el toro había sido ofrecido en holocausto sobre el altar recién construido.

[[judges-6-29]]
^29^ Entonces se dijeron unos a otros: «¿Quién habrá hecho esto?» Tras indagar y buscar dijeron: «Es Gedeón, hijo de Joás, el que lo ha hecho».

[[judges-6-30]]
^30^ La gente de la ciudad dijo entonces a Joás: «Haz salir a tu hijo, y que muera, pues ha derruido el altar de Baal y cortado el cipo que se alzaba a su lado».

[[judges-6-31]]
^31^ Joás repondió a todos los que tenía delante: «¿Es que vosotros vais a salir en defensa de Baal? ¿Vosotros le vais a salvar? (El que defiende a Baal, tiene que morir antes del amanecer.) Si es dios, que pleitee con él, ya que le destruyó su altar».

[[judges-6-32]]
^32^ Aquel día se llamó a Gedeón Yerubbaal, porque decían: «¡Que Baal pleitee con él, pues le destruyó su altar!».

[[judges-6-33]]
^33^ Todo Madián, Amalec y los hijos de Oriente se juntaron, pasaron el Jordán, y acamparon en la llanura de Yizreel.

[[judges-6-34]]
^34^ El espíritu de Yahveh revistió a Gedeón; él tocó el cuerno y Abiezer se reunió a él.

[[judges-6-35]]
^35^ Envió mensajeros por todo Manasés, que se reunió también con él; y envió mensajeros por Aser, Zabulón y Neftalí, que le salieron al encuentro.

[[judges-6-36]]
^36^ Gedeón dijo a Dios: «Si verdaderamente vas a salvar por mi mano a Israel, como has dicho,

[[judges-6-37]]
^37^ yo voy a tender un vellón sobre la era; si hay rocío solamente sobre el vellón y todo el suelo queda seco, sabré que tú salvarás a Israel por mi mano, como has prometido».

[[judges-6-38]]
^38^ Así sucedió. Gedeón se levantó de madrugada, estrujó el vellón y exprimió su rocío, una copa llena de agua.

[[judges-6-39]]
^39^ Gedeón dijo a Dios: «No te irrites contra mí si me atrevo a hablar de nuevo. Por favor, quisiera hacer por última vez la prueba con el vellón: que quede seco sólo el vellón y que haya rocío por todo el suelo».

[[judges-6-40]]
^40^ Y Dios lo hizo así aquella noche. Quedó seco solamente el vellón y por todo el suelo había rocío.
[[judges-7]]
== Capítulo 7

[[judges-7-1]]
^1^ Madrugó Yerubbaal (o sea Gedeón), así como todo el pueblo que estaba con él, y acampó junto a En Jarod; el campamento de Madián quedaba al norte del suyo, al pie de la colina de Moré, en el valle.

[[judges-7-2]]
^2^ Yahveh dijo a Gedeón: «Demasiado numeroso es el pueblo que te acompaña para que ponga yo a Madián en sus manos; no se vaya a enorgullecer Israel de ello a mi costa diciendo: “¡Mi propia mano me ha salvado!”

[[judges-7-3]]
^3^ Ahora pues, pregona esto a oídos del pueblo: “El que tenga miedo y tiemble, que se vuelva y mire desde el monte Gelboé”. 22.000 hombres de la tropa se volvieron y quedaron 10.000.

[[judges-7-4]]
^4^ Yahveh dijo a Gedeón: «Hay todavía demasiada gente; hazles bajar al agua y allí te los pondré a prueba. Aquel de quien te diga: “Que vaya contigo”, ése irá contigo. Y aquel de quien te diga: “Que no vaya contigo”, no ha de ir».

[[judges-7-5]]
^5^ Gedeón hizo bajar la gente al agua y Yahveh le dijo: «A todos los que lamieren el agua con la lengua como lame un perro, los pondrás a un lado y a todos los que se arrodillen para beber, los pondrás al otro».

[[judges-7-6]]
^6^ El número de los que lamieron el agua con las manos a la boca resultó ser de trescientos. Todo el resto del pueblo se había arrodillado para beber.

[[judges-7-7]]
^7^ Entonces Yahveh dijo a Gedeón: «Con los trescientos hombres que han lamido el agua os salvaré, y entregaré a Madián en tus manos. Que todos los demás vuelvan cada uno a su casa».

[[judges-7-8]]
^8^ Tomaron en sus manos las provisiones del pueblo y sus cuernos, y mandó a todos los israelitas cada uno a su tienda, quedándose sólo con los trescientos hombres. El campamento de Madián estaba debajo del suyo en el valle.

[[judges-7-9]]
^9^ Aquella noche le dijo Yahveh: «Levántate y baja al campamento, porque lo he puesto en tus manos.

[[judges-7-10]]
^10^ No obstante, si temes bajar, baja al campamento con tu criado Purá,

[[judges-7-11]]
^11^ y escucha lo que dicen. Se fortalecerá tu mano con ello y luego bajarás a atacar al campamento. Bajó, pues, con su criado Purá hasta la extremidad de las avanzadillas del campamento.

[[judges-7-12]]
^12^ Madián, Amalec y todos los hijos de Oriente habían caído sobre el valle, numerosos como langostas, y sus camellos eran innumerables como la arema de la orilla del mar.

[[judges-7-13]]
^13^ Se acercó Gedeón y he aquí que un hombre contaba un sueño a su vecino; decía: «He tenido un sueño: una hogaza de pan de cebada rodaba por el campamento de Madián, llegó hasta la tienda, chocó contra ella y la volcó lo de arriba abajo».

[[judges-7-14]]
^14^ Su vecino le respondió: «Esto no puede significar más que la espada de Gedeón, hijo de Joás, el israelita. Dios ha entregado en sus manos a Madián y a todo el campamento».

[[judges-7-15]]
^15^ Cuando Gedeón oyó la narración del sueño y su explicación, se postró, volvió al campamento de Israel y dijo: «¡Levantaos! porque Yahveh ha puesto en vuestras manos el campamento de Madián».

[[judges-7-16]]
^16^ Gedeón dividió a los trescientos hombres en tres cuerpos. Les dio a todos cuernos y cántaros vacíos, con antorchas dentro de los cántaros.

[[judges-7-17]]
^17^ Les dijo: «Miradme a mí y haced lo mismo. Cuando llegue yo al extremo del campamento, lo que yo haga lo haréis vosotros.

[[judges-7-18]]
^18^ Yo y todos mis compañeros tocaremos los cuernos; vosotros también tocaréis los cuernos alrededor del campamento y gritaréis: ¡Por Yahveh y por Gedeón!»

[[judges-7-19]]
^19^ Gedeón y los cien hombres que le acompañaban llegaron al extremo del campamento al comienzo de la guardia de la medianoche, cuando acababan de hacer el relevo de los centinelas; tocaron los cuernos y rompieron los cántaros que llevaban en la mano.

[[judges-7-20]]
^20^ Entonces los tres cuerpos del ejército tocaron los cuernos, y rompieron los cántaros; en la izquierda tenían las antorchas y en la derecha los cuernos para tocarlos; gritaban: «Espada por Yahveh y por Gedeón!»

[[judges-7-21]]
^21^ Y se quedaron quietos cada uno en su lugar alrededor del campamento. Todo el campamento se despertó y, lanzando alaridos, se dieron a la fuga.

[[judges-7-22]]
^22^ Mientras los trescientos tocaban los cuernos, Yahveh volvió la espada de cada uno contra su compañero por todo el campamento. La tropa huyó hasta Bet Hassittá, hacia Sartán, hasta la orilla de Abel Mejolá frente a Tabbat.

[[judges-7-23]]
^23^ Los hombres de Israel se reunieron, de Neftalí, de Aser y de todo Manasés, y persiguieron a Madián.

[[judges-7-24]]
^24^ Gedeón envió mensajeros por toda la montaña de Efraím diciendo: «Bajad al encuentro de Madián y cortadles los vados hasta Bet Bará y el Jordán». Se reunieron todos los hombres de Efraím y ocuparon los vados hasta Bet Bará y el Jordán.

[[judges-7-25]]
^25^ Hicieron prisioneros a los dos jefes de Madián, Oreb y Zeeb; mataron a Oreb en la Peña de Oreb y a Zeeb en el Lagar de Zeeb. Persiguieron a Madián y llevaron a Gedeón, al otro lado del Jordán, las cabezas de Oreb y Zeeb.
[[judges-8]]
== Capítulo 8

[[judges-8-1]]
^1^ La gente de Efraím dijo a Gedeón: «¿Por qué has hecho esto con nosotros, no convocándonos cuando has ido a combatir a Madián?» Y discutieron con él violentamente.

[[judges-8-2]]
^2^ El les respondió: «¿Qué he hecho yo en comparación de lo que habéis hecho vosotros? ¿No vale más el rebusco de Efraím que la vendimia de Abiézer?

[[judges-8-3]]
^3^ Dios ha entregado a los jefes de Madián en vuestras manos, a Oreb y a Zeeb. ¿Qué he podido hacer yo en comparación con vosotros?» Con estas palabras que les dijo, se calmó su animosidad contra él.

[[judges-8-4]]
^4^ Gedeón llegó al Jordán y lo pasó; pero él y los trescientos hombres que tenía consigo estaban agotados por la persecución.

[[judges-8-5]]
^5^ Dijo, pues, a la gente de Sukkot: «Dad, por favor, tortas de pan a la tropa que me sigue, porque está agotada, y voy persiguiendo a Zébaj y a Salmunná, reyes de Madián.

[[judges-8-6]]
^6^ Pero los jefes de Sukkot respondieron: «¿Acaso has sujetado ya las manos de Zébaj y Salmunná para que demos pan a tu ejército?»

[[judges-8-7]]
^7^ Gedeón les respondió: «Bien; cuando Yahveh haya entregado en mis manos a Zébaj y a Salmunná, os desgarraré las carnes con espinas del desierto y con cardos».

[[judges-8-8]]
^8^ De allí subió a Penuel y les habló de igual manera. Pero la gente de Penuel le respondió como lo había hecho la gente de Sukkot.

[[judges-8-9]]
^9^ El respondió a los de Penuel: «Cuando vuelva vencedor, derribaré esa torre».

[[judges-8-10]]
^10^ Zébaj y Salmunná estaban en Carcor con su ejército, unos 15.000 hombres, todos los que habían quedado del ejército de los hijos de Oriente. Los que habían caído eran 120.000 guerreros.

[[judges-8-11]]
^11^ Gedeón subió por el camino de los que habitan en tiendas, al este de Nóbaj y de Yogbohá, y derrotó al ejército, cuando se creían ya seguros.

[[judges-8-12]]
^12^ Zébaj y Salmunná huyeron. El los persiguió e hizo prisioneros a los dos reyes de Madián, Zébaj y Salmunná. Y destruyó todo el ejército.

[[judges-8-13]]
^13^ Después de la batalla, Gedeón, hijo de Joás, volvió por la pendiente de Jares.

[[judges-8-14]]
^14^ Habiendo detenido a un joven de la gente de Sukkot, le interrogó, y él le dio por escrito los jefes de Sukkot y los ancianos: 77 hombres.

[[judges-8-15]]
^15^ Gedeón se dirigió entonces a la gente de Sukkot y dijo: «Aquí tenéis a Zébaj y Salmunná, a propósito de los cuales me injuriasteis diciendo: ¿Acaso has sujetado ya las manos de Zébaj y Salmunná para que demos pan a tus tropas agotadas?»

[[judges-8-16]]
^16^ Tomó entonces a los ancianos de la ciudad y cogiendo espinas del desierto y cardos, desgarró a los hombres de Sukkot.

[[judges-8-17]]
^17^ Derribó la torre de Penuel y mató a los habitantes de la ciudad.

[[judges-8-18]]
^18^ Luego dijo a Zébaj y Salmunná: «¿Cómo eran los hombres que matasteis en el Tabor?» Ellos respondieron: «Se parecían a ti; cualquiera de ellos tenía la apariencia de un hijo de rey».

[[judges-8-19]]
^19^ Respondió Gedeón: «Eran mis hermanos, hijos de mi madre. ¡Vive Yahveh que, si los hubieseis dejado vivos, no os mataría!»

[[judges-8-20]]
^20^ Y dijo a Yéter, su hijo mayor: «¡Levántate! ¡Mátalos!» Pero el muchacho no desenvainó la espada; no se atrevía, porque era todavía muy joven.

[[judges-8-21]]
^21^ Zébaj y Salmunná dijeron entonces: «Levántate tú, hiérenos, porque según es el hombre es su valentía». Gedeón se levantó, mató a Zébaj y a Salmunná y tomó las lunetas que sus camellos llevaban al cuello.

[[judges-8-22]]
^22^ Los hombres de Israel dijeron a Gedeón: «Reina sobre nosotros tú, tu hijo y tu nieto, pues nos has salvado de la mano de Madián».

[[judges-8-23]]
^23^ Pero Gedeón les respondió: «No seré yo el que reine sobre vosotros ni mi hijo; Yahveh será vuestro rey».

[[judges-8-24]]
^24^ Y añadio Gedeón: «Os voy a pedir una cosa: que cada uno me dé un anillo de su botín». Porque los vencidos tenían anillos de oro, pues eran ismaelitas.

[[judges-8-25]]
^25^ Respondieron ellos: «Te los damos con mucho gusto». Extendió él su manto y ellos echaron en él cada uno un anillo de su botín.

[[judges-8-26]]
^26^ El peso de los anillos de oro que les había pedido, se elevó a 1.700 siclos de oro, sin contar las lunetas, los pendientes y los vestidos de púrpura que llevaban los reyes de Madián, ni tampoco los collares que pendían del cuello de sus camellos.

[[judges-8-27]]
^27^ Gedeón hizo con todo ello un efod, que colocó en su ciudad, en Ofrá. Y todo Israel se prostituyó allí tras él y vino a ser una trampa para Gedeón y su familia.

[[judges-8-28]]
^28^ Allí fue humillado Madián ante los israelitas, y no volvió a levantar cabeza. El país estuvo tranquilo cuarenta años, mientras vivió Gedeón.

[[judges-8-29]]
^29^ Se fue, pues, Yerubbaal, hijo de Joás, y se quedó en su casa.

[[judges-8-30]]
^30^ Gedeón tuvo setenta hijos, nacidos de él, pues tenía muchas mujeres.

[[judges-8-31]]
^31^ Y la concubina que tenía en Siquem, le dio a luz también un hijo, a quien puso por nombre Abimélek.

[[judges-8-32]]
^32^ Murió Gedeón, hijo de Joás, después de una dichosa vejez y fue enterrado en la tumba de su padre Joás, en Ofrá de Abiézer.

[[judges-8-33]]
^33^ Después de la muerte de Gedeón, los israelitas volvieron a prostituirse ante los Baales y tomaron por dios a Baal Berit.

[[judges-8-34]]
^34^ Los israelitas olvidaron a Yahveh su Dios, que los había librado de la mano de todos los enemigos de alrededor.

[[judges-8-35]]
^35^ No fueron agradecidos con la casa de Yerubbaal-Gedeón, por todo el bien que había hecho a Israel.
[[judges-9]]
== Capítulo 9

[[judges-9-1]]
^1^ Abimélek, hijo de Yerubbaal, marchó a Siquem, donde los hermanos de su madre, y les dijo a ellos y a todo el clan de la familia de su madre:

[[judges-9-2]]
^2^ «Decid esto, por favor, a oídos de todos los señores de Siquem: ¿Qué es mejor para vosotros, que os estén mandando setenta hombres, todos los hijos de Yerubbaal, o que os mande uno solo? Recordad además que yo soy de vuestros huesos y de vuestra carne».

[[judges-9-3]]
^3^ Los hermanos de su madre hablaron de él en los mismos términos a todos los señores de Siquem, y su corazón se inclinó hacia Abimélek, porque se decían: «Es nuestro hermano».

[[judges-9-4]]
^4^ Le dieron setenta siclos de plata del templo de Baal Berit, con los que Abimélek contrató a hombres miserables, y vagabundos, que se fueron con él.

[[judges-9-5]]
^5^ Fue entonces a casa de su padre, en Ofrá, y mató a sus hermanos, los hijos de Yerubbaal, setenta hombres, sobre una misma piedra. Sólo escapó Jotam, el hijo menor de Yerubbaal, porque se escondió.

[[judges-9-6]]
^6^ Luego se reunieron todos los señores de Siquem y todo Bet Milló, y fueron y proclamaron rey a Abimélek junto al Terebinto de la estela que hay en Siquem.

[[judges-9-7]]
^7^ Se lo anunciaron a Jotam, quien se colocó en la cumbre del monte Garizim, alzó la voz y clamó: «Escuchadme, señores de Siquem, y que Dios os escuche.

[[judges-9-8]]
^8^ Los árboles se pusieron en camino para ungir a uno como su rey. Dijeron al olivo: “Sé tú nuestro rey.”

[[judges-9-9]]
^9^ Les respondió el olivo: “¿Voy a renunciar a mi aceite con el que gracias a mí son honrados los dioses y los hombres, para ir a vagar por encima de los árboles?”

[[judges-9-10]]
^10^ Los árboles dijeron a la higuera: “Ven tú, reina sobre nosotros.”

[[judges-9-11]]
^11^ Les respondió la higuera: “¿Voy a renunciar a mi dulzura y a mi sabroso fruto, para ir a vagar por encima de los árboles?

[[judges-9-12]]
^12^ Los árboles dijeron a la vid: “Ven tú, reina sobre nosotros.”

[[judges-9-13]]
^13^ Les respondió la vid: “¿Voy a renunciar a mi mosto, el que alegra a los dioses y a los hombres, para ir a vagar por encima de los árboles?”

[[judges-9-14]]
^14^ Todos los árboles dijeron a la zarza: “Ven tú, reina sobre nosotros.”

[[judges-9-15]]
^15^ La zarza respondió a los árboles: “Si con sinceridad venís a ungirme a mí para reinar sobre vosotros, llegad y cobijaos a mi sombra. Y si no es así, brote fuego de la zarza y devore los cedros del Líbano.”»

[[judges-9-16]]
^16^ «Ahora pues, ¿habéis obrado con sinceridad y lealtad al elegir rey a Abimélek? ¿Os habéis portado bien con Yerubbaal y su casa y le habéis tratado según el mérito de sus manos?

[[judges-9-17]]
^17^ Mi padre combatió por vosotros, arriesgó su vida, os libró de la mano de Madián;

[[judges-9-18]]
^18^ y vosotros os habéis alzado hoy contra la casa de mi padre, habéis matado a sus hijos, setenta hombres sobre una misma piedra, y habéis puesto por rey a Abimélek, el hijo de su esclava, sobre los señores de Siquem, por ser él vuestro hermano.

[[judges-9-19]]
^19^ Si, pues, habéis obrado con sinceridad y lealtad con Yerubbaal y con su casa en el día de hoy, que Abimélek sea vuestra alegría y vosotros la suya.

[[judges-9-20]]
^20^ De lo contrario, que salga fuego de Abimélek y devore a los señores de Siquem y de Bet Milló; y que salga fuego de los señores de Siquem y Bet Milló y devore a Abimélek».

[[judges-9-21]]
^21^ Y Jotam huyó, se puso a salvo y fue a Beer, donde se estableció, lejos del alcance de su hermano Abimélek.

[[judges-9-22]]
^22^ Abimélek gobernó tres años en Israel.

[[judges-9-23]]
^23^ Pero Dios envió un espíritu de discordia entre Abimélek y los señores de Siquem; y los señores de Siquem traicionaron a Abimélek,

[[judges-9-24]]
^24^ para que el crimen cometido contra los setenta hijos de Yerubbaal fuera vengado y su sangre cayera sobre su hermano Abimélek, que los había asesinado, y sobre los señores de Siquem, que le habían ayudado a asesinar a sus hermanos.

[[judges-9-25]]
^25^ Los señores de Siquem prepararon contra él emboscadas en las cimas de los montes y saqueaban a todo el que pasaba cerca por el camino. Y se dio aviso a Abimélek.

[[judges-9-26]]
^26^ Gaal, hijo de Obed, acompañando a sus hermanos, vino a pasar por Siquem y se ganó la confianza de los señores de Siquem.

[[judges-9-27]]
^27^ Salieron éstos al campo a vendimiar sus viñas, pisaron las uvas, hicieron fiesta y entraron en el templo de su dios. Comieron y bebieron y maldijeron a Abimélek.

[[judges-9-28]]
^28^ Entonces Gaal, hijo de Obed, exclamó: «¿Quién es Abimélek y qué es Siquem para que le sirvamos? ¿por qué el hijo de Yerubbaal y Zebul, su lugarteniente, no han de servir a la gente de Jamor, padre de Siquem? ¿Por qué hemos de servirles nosotros?

[[judges-9-29]]
^29^ ¡Quién pusiera este pueblo en mis manos! Yo echaría a Abimélek y le diría: Refuerza tu ejército y sal a la lucha».

[[judges-9-30]]
^30^ Zebul, gobernador de la ciudad, se enteró de la propuesta de Gaal, hijo de Obed, y montó en cólera.

[[judges-9-31]]
^31^ Envió secretamente mensajeros donde Abimélek, para decirle: «Mira que Gaal, hijo de Obed, con sus hermanos, ha llegado a Siquem y están soliviantando a la ciudad contra ti.

[[judges-9-32]]
^32^ Por tanto, levántate de noche, tú y la gente que tienes contigo, y tiende una emboscada en el campo;

[[judges-9-33]]
^33^ por la mañana temprano, en cuanto salga el sol, te levantas y te lanzas contra la ciudad. Cuando Gaal salga a tu encuentro con su gente, harás con él lo que te venga a mano».

[[judges-9-34]]
^34^ Abimélek se levantó de noche con todas las tropas de que disponía y tendieron una emboscada frente a Siquem, repartidos en cuatro grupos.

[[judges-9-35]]
^35^ Cuando Gaal, hijo de Obed, salió y se detuvo a la entrada de la puerta de la ciudad, Abimélek y la tropa que le acompañaba salieron de su emboscada.

[[judges-9-36]]
^36^ Gaal vio la tropa y dijo a Zebul: «Mira la gente que baja de las cumbres de los montes». Zebul respondió: «Es la sombra de los montes lo que ves y te parecen hombres».

[[judges-9-37]]
^37^ Gaal volvió a decir: «Mirad la gente que baja del lado del Ombligo de la Tierra, y otra partida llega por el camino de la Encina de los Adivinos».

[[judges-9-38]]
^38^ Zebul le dijo entonces: «¿Qué has hecho de tu boca tú que decías: “¿Quién es Abimélek para que le sirvamos?” ¿ No es esa la gente que despreciaste? Sal, pues, ahora y pelea contra ellos».

[[judges-9-39]]
^39^ Gaal salió al frente de los señores de Siquem y presentó batalla a Abimélek.

[[judges-9-40]]
^40^ Abimélek persiguió a Gaal, pero se le escapó; y muchos cayeron muertos antes de llegar a la puerta.

[[judges-9-41]]
^41^ Abimélek habitó en Arumá; y Zebul expulsó a Gaal y a sus hermanos y no les dejó habitar en Siquem.

[[judges-9-42]]
^42^ Al día siguiente el pueblo salió al campo. Se dio aviso de ello a Abimélek,

[[judges-9-43]]
^43^ que tomó su tropa, la repartió en tres grupos y tendió una emboscada en el campo. Cuando vio que la gente salía de la ciudad, cayó sobre ellos y los derrotó.

[[judges-9-44]]
^44^ Abimélek y el grupo que estaba con él, atacó y tomó posiciones a la entrada de la puerta de la ciudad; los otros dos grupos se lanzaron contra todos los que estaban en el campo y los derrotaron.

[[judges-9-45]]
^45^ Todo aquel día estuvo Abimélek atacando a la ciudad. Cuando la tomó, mató a la población, arrasó la ciudad y la sembró de sal.

[[judges-9-46]]
^46^ Al saberlo los vecinos de Migdal Siquem se metieron en la cripta del templo de El Berit.

[[judges-9-47]]
^47^ Se comunicó a Abimélek que todos los señores de Migdal Siquem estaban juntos;

[[judges-9-48]]
^48^ entonces Abimélek subió al monte Salmón, con toda su tropa, y tomando un hacha en sus manos, cortó una rama de árbol, la alzó y echándosela al hombro dijo a la tropa que le acompañaba: «Lo que me habéis visto hacer, deprisa, hacedlo también vosotros».

[[judges-9-49]]
^49^ Y todos sus hombres cortaron cada uno su rama; luego siguieron a Abimélek, pusieron las ramas sobre la cripta y prendieron fuego a la cripta con ellos debajo. Así murieron también todos los habitantes de Migdal Siquem, unos mil hombres y mujeres.

[[judges-9-50]]
^50^ Marchó Abimélek contra Tebés, la asedió y tomó.

[[judges-9-51]]
^51^ Había en medio de la ciudad una torre fuerte, y en ella se refugiaron todos los hombres y mujeres, y todos los señores de la ciudad. Cerraron por dentro y subieron a la terraza de la torre.

[[judges-9-52]]
^52^ Abimélek llegó hasta la torre, la atacó y alcanzó la puerta de la torre con ánimo de prenderle fuego.

[[judges-9-53]]
^53^ Entonces una mujer le arrojó una muela de molino a la cabeza y le partió el cráneo.

[[judges-9-54]]
^54^ El llamó enseguida a su escudero y le dijo: «Desenvaina tu espada y mátame, para que no digan de mí: Lo ha matado una mujer». Su escudero lo atravesó y murió.

[[judges-9-55]]
^55^ Cuando la gente de Israel vio que Abimélek había muerto, se volvió cada uno a su lugar.

[[judges-9-56]]
^56^ Así devolvió Dios a Abimélek el mal que había hecho a su padre al matar a sus setenta hermanos.

[[judges-9-57]]
^57^ Y también sobre la cabeza de la gente de Siquem hizo Dios caer toda su maldad. De este modo se cumplió en ellos la maldición de Jotam, hijo de Yerubbaal.
[[judges-10]]
== Capítulo 10

[[judges-10-1]]
^1^ Después de Abimélek surgió para salvar a Israel Tolá, hijo de Puá, hijo de Dodó. Era de Isacar y habitaba en Samir, en la montaña de Efraím.

[[judges-10-2]]
^2^ Fue juez de Israel veintitrés años; murió y fue sepultado en Samir.

[[judges-10-3]]
^3^ Tra él surgió Yaír, de Galaad, que fue juez de Israel veintidós años.

[[judges-10-4]]
^4^ Tenía treinta hijos que montaban treinta pollinos y tenían treinta ciudades, que se llaman todavía hoy los Aduares de Yaír, en el país de Galaad.

[[judges-10-5]]
^5^ Murió Yaír, y fue sepultado en Camón.

[[judges-10-6]]
^6^ Los israelitas volvieron a hacer lo que desagradaba a Yahveh. Sirvieron a los Baales y a las Astartés, a los dioses de Aram y Sidón, a los dioses de Moab, a los de los ammonitas y de los filisteos. Abandonaron a Yahveh y ya no le servían.

[[judges-10-7]]
^7^ Entonces se encendió la cólera de Yahveh contra Israel y los entregó en manos de los filisteos y en manos de los ammonitas.

[[judges-10-8]]
^8^ Estos molestaron y oprimieron a los israelitas desde aquel año durante dieciocho años, a todos los israelitas que vivían en Transjordania, en el país amorreo de Galaad.

[[judges-10-9]]
^9^ Los ammonitas pasaron el Jordán para atacar también a Judá, a Benjamín y a la casa de Efraím, e Israel pasó por grave aprieto.

[[judges-10-10]]
^10^ Los israelitas clamaron a Yahveh diciendo: «Hemos pecado contra tí, porque hemos abandonado a Yahveh nuestro Dios para servir a los Baales».

[[judges-10-11]]
^11^ Y Yahveh dijo a los israelitas: «Cuando los egipcios, los amorreos, los ammonitas, los filisteos,

[[judges-10-12]]
^12^ los sidonios, Amalec y Madián os oprimían y clamasteis a mí ¿no os salvé de sus manos?

[[judges-10-13]]
^13^ Pero vosotros me habéis abandonado y habéis servido a otros dioses. Por eso no he de salvaros otra vez.

[[judges-10-14]]
^14^ Id y gritad a los dioses que habéis elegido: que os salven ellos en el tiempo de vuestra angustia».

[[judges-10-15]]
^15^ Los israelitas respondieron a Yahveh: «Hemos pecado, haz con nosotros todo lo que te plazca; pero, por favor, sálvanos hoy».

[[judges-10-16]]
^16^ Y retiraron de en medio de ellos a los dioses extranjeros y sirvieron a Yahveh. Y Yahveh no pudo soportar el sufrimiento de Israel.

[[judges-10-17]]
^17^ Los ammonitas se concentraron y vinieron a acampar en Galaad. Los israelitas se reunieron y acamparon en Mispá.

[[judges-10-18]]
^18^ Entonces el pueblo, los jefes de Galaad, se dijeron unos a otros: «¿Quién será el hombre que emprenda el ataque contra los hijos de Ammón? El estará al frente de todos los habitantes de Galaad».
[[judges-11]]
== Capítulo 11

[[judges-11-1]]
^1^ Jefté el galaadita, era un valiente guerrero. Era hijo de una prostituta. Y era Galaad el que había engendrado a Jefté.

[[judges-11-2]]
^2^ Pero la mujer de Galaad le había dado hijos, y crecieron los hijos de la mujer y echaron a Jefté diciéndole: «Tú no tendrás herencia en la casa de nuestro padre, porque eres hijo de otra mujer».

[[judges-11-3]]
^3^ Jefté huyó lejos de sus hermanos y se quedó en el país de Tob. Se le juntó una banda de gente miserable, que hacía correrías con él.

[[judges-11-4]]
^4^ Andando el tiempo, los ammonitas vinieron a combatir contra Israel.

[[judges-11-5]]
^5^ Y cuando los ammonitas estaban atacando a Israel, los ancianos de Galaad fueron a buscar a Jefté al país de Tob.

[[judges-11-6]]
^6^ Dijeron a Jefté: «Ven, tú serás nuestro caudillo en la guerra con los ammonitas».

[[judges-11-7]]
^7^ Pero Jefté respondió a los ancianos de Galaad: «¿No sois vosotros los que me odiasteis y me echasteis de la casa de mi padre? ¿Por qué acudís a mí ahora que estáis en aprieto?»

[[judges-11-8]]
^8^ Los ancianos de Galaad replicaron a Jefté: «Por eso ahora volvemos donde ti: ven con nosotros; tú atacarás a los ammonitas y serás nuestro jefe y el de todos los habitantes de Galaad».

[[judges-11-9]]
^9^ Jefté respondió a los ancianos de Galaad: «Si me hacéis volver para combatir a los ammonitas y Yahveh me los entrega, yo seré vuestro jefe».

[[judges-11-10]]
^10^ Respondieron a Jefté los ancianos de Galaad: «Yahveh sea testigo entre nosotros si no hacemos como tú has dicho».

[[judges-11-11]]
^11^ Jefté partió con los ancianos de Galaad y el pueblo le hizo su jefe y caudillo; y Jefté repitió todas sus condiciones delante de Yahveh en Mispá.

[[judges-11-12]]
^12^ Jefté envió al rey de los ammonitas mensajeros que le dijeran: «¿Qué tenemos que ver tú y yo para que vengas a atacarme en mi propio país?»

[[judges-11-13]]
^13^ El rey de los ammonitas respondió a los mensajeros de Jefté: «Porque Israel, cuando subía de Egipto, se apoderó de mi país desde el Arnón hasta el Yabboq y el Jordán. Así que ahora devuélvemelo por las buenas».

[[judges-11-14]]
^14^ Jefté envió de nuevo mensajeros al rey de los ammonitas

[[judges-11-15]]
^15^ y le dijo: «Así habla Jefté: Israel no se ha apoderado ni del país de Moab ni del de los ammonitas.

[[judges-11-16]]
^16^ Cuando subió de Egipto, Israel caminó por el desierto hasta el mar de Suf y llegó a Cadés.

[[judges-11-17]]
^17^ Entonces Israel envió mensajeros al rey de Edom para decirle: “Déjame, por favor, pasar por tu país”, pero el rey de Edom no les atendió. Los envió también al rey de Moab, el cual tampoco accedió, e Israel se quedó en Cadés;

[[judges-11-18]]
^18^ luego, avanzando por el desierto, rodeó el país de Edom y el de Moab y llegó al oriente del país de Moab. Acamparon a la otra parte del Arnón, sin cruzar la frontera de Moab, pues el Arnón es el límite de Moab.

[[judges-11-19]]
^19^ Israel envió mensajeros a Sijón, rey de los amorreos, que reinaba en Jesbón, y le dijo: “Déjame, por favor, pasar por tu país hasta llegar a mi destino.”

[[judges-11-20]]
^20^ Pero Sijón le negó a Israel el paso por su territorio, reunió toda su gente, que acampó en Yahsá, y atacó a Israel.

[[judges-11-21]]
^21^ Yahveh, Dios de Israel, puso a Sijón y a todo su pueblo en manos de Israel, que los derrotó, y conquistó Israel todo el país de los amorreos que habitaban allí.

[[judges-11-22]]
^22^ Así conquistaron todo el territorio de los amorreos, desde el Arnón hasta el Yabboq y desde el desierto hasta el Jordán.

[[judges-11-23]]
^23^ Con que Yahveh, Dios de Israel, quitó su heredad a los amorreos en favor de su pueblo Israel, ¿y tú se la vas a quitar?

[[judges-11-24]]
^24^ ¿No posees ya todo lo que tu dios Kemós ha quitado para ti a sus poseedores? Igualmente nosotros poseemos todo lo que Yahveh nuestro Dios ha quitado para nosotros a sus poseedores.

[[judges-11-25]]
^25^ ¿Vas a ser tú más que Balaq, hijo de Sippor, rey de Moab? ¿Pudo acaso él hacerse fuerte contra Israel y luchar contra él?

[[judges-11-26]]
^26^ Cuando se estableció Israel en Jesbón y en sus filiales, en Aroer y en sus filiales y en todas las ciudades que están a ambos lados del Arnón, (trescientos años) ¿por qué no las habéis recuperado desde entonces?

[[judges-11-27]]
^27^ Yo no te he ofendido; eres tú el que te portas mal conmigo si me atacas. Yahveh, el Juez, juzgue hoy entre los hijos de Israel y los hijos de Ammón».

[[judges-11-28]]
^28^ Pero el rey de los ammonitas no hizo caso de las palabras que Jefté le mandó decir.

[[judges-11-29]]
^29^ El espíritu de Yahveh vino sobre Jefté, que recorrió Galaad y Manasés, pasó por Mispá de Galaad y de Mispá de Galaad pasó donde los ammonitas.

[[judges-11-30]]
^30^ Y Jefté hizo un voto a Yahveh: «Si entregas en mis manos a los ammonitas,

[[judges-11-31]]
^31^ el primero que salga de las puertas de mi casa a mi encuentro cuando vuelva victorioso de los ammonitas, será para Yahveh y lo ofreceré en holocausto».

[[judges-11-32]]
^32^ Jefté pasó donde los ammonitas para atacarlos, y Yahveh los puso en sus manos.

[[judges-11-33]]
^33^ Los derrotó desde Aroer hasta cerca de Minnit (veinte ciudades) y hasta Abel Keramim. Fue grandísima derrota y los ammonitas fueron humillados delante de los israelitas.

[[judges-11-34]]
^34^ Cuando Jefté volvió a Mispá, a su casa, he aquí que su hija salía a su encuentro bailando al son de las panderetas. Era su única hija; fuera de ella no tenía ni hijo ni hija.

[[judges-11-35]]
^35^ Al verla, rasgó sus vestiduras y gritó: «¡Ay, hija mía! ¡Me has destrozado! ¿Habías de ser tú la causa de mi desgracia? Abrí la boca ante Yahveh y no puedo volverme atrás».

[[judges-11-36]]
^36^ Ella le respondió: «Padre mío, has abierto tu boca ante Yahveh, haz conmigo lo que salió de tu boca, ya que Yahveh te ha concedido vengarte de tus enemigos los ammonitas».

[[judges-11-37]]
^37^ Después dijo a su padre: «Que se me conceda esta gracia: déjame dos meses para ir a vagar por las montañas y llorar con mis compañeras mi virginidad».

[[judges-11-38]]
^38^ El le dijo: «Vete». Y la dejó marchar dos meses. Ella se fue con sus compañeras y estuvo llorando su virginidad por los montes.

[[judges-11-39]]
^39^ Al cabo de los dos meses, volvió donde su padre y él cumplió en ella el voto que había hecho. La joven no había conocido varón. Y se hizo costumbre en Israel:

[[judges-11-40]]
^40^ de año en año las hijas de Israel van a lamentarse cuatro días al año por la hija de Jefté el galaadita.
[[judges-12]]
== Capítulo 12

[[judges-12-1]]
^1^ Los hombres de Efraím se juntaron, pasaron el Jordán en dirección a Safón y dijeron a Jefté: «Por qué has ido a atacar a los ammonitas y no nos has invitado a marchar contigo? Vamos a prender fuego a tu casa contigo dentro».

[[judges-12-2]]
^2^ Jefté les respondió: «Teníamos un gran conflicto mi pueblo y yo con los ammonitas; os pedí ayuda y no me librasteis de sus manos.

[[judges-12-3]]
^3^ Cuando vi que nadie venía a ayudarme, arriesgué la vida, marché contra los ammonitas y Yahveh los entregó en mis manos. ¿Por qué, pues, habéis subido hoy contra mí para hacerme la guerra?»

[[judges-12-4]]
^4^ Entonces Jefté reunió a todos los hombres de Galaad y atacó a Efraím, los de Galaad derrotaron a los de Efraím, porque éstos decían: «vosotros los galaaditas sois fugitivos de Efraím, en medio de Efraím, en medio de Manasés».

[[judges-12-5]]
^5^ Galaad cortó a Efraím los vados del Jordán y cuando los fugitivos de Efraím decían: «Dejadme pasar», los hombres de Galaad preguntaban: «¿Eres efraimita?» Y si repondía: «No»,

[[judges-12-6]]
^6^ le añadían: «Pues di Sibbólet». Pero él decía: «Sibbólet» porque no podía pronunciarlo así. Entonces le echaban mano y lo degollaban junto a los vados del Jordán. Perecieron en aquella ocasión 42.000 hombres de Efraím.

[[judges-12-7]]
^7^ Jefté juzgó a Israel seis años; luego Jefté el galaadita murió y fue sepultado en su ciudad, Mispá de Galaad.

[[judges-12-8]]
^8^ Después de él fue juez en Israel Ibsán de Belén.

[[judges-12-9]]
^9^ Tenía treinta hijos y treinta hijas. A éstas las casó fuera y de fuera trajo treinta mujeres para sus hijos. Fue juez en Israel siete años.

[[judges-12-10]]
^10^ Y murió Ibsán y fue sepultado en Belén.

[[judges-12-11]]
^11^ Después de él fue juez en Israel Elón de Zabulón. Juzgó a Israel diez años.

[[judges-12-12]]
^12^ Y murió Elón de Zabulón y fue sepultado en Ayyalón, en tierra de Zabulón.

[[judges-12-13]]
^13^ Después de él fue juez en Israel Abdón, hijo de Hillel, de Piratón.

[[judges-12-14]]
^14^ Tenía cuarenta hijos y treinta nietos, que montaban setenta pollinos. Juzgó a Israel ocho años.

[[judges-12-15]]
^15^ Y murió Abdón, hijo de Hillel de Piratón, y fue sepultado en Piratón, en tierra de Efraím, en la montaña de los amalecitas.
[[judges-13]]
== Capítulo 13

[[judges-13-1]]
^1^ Los israelitas volvieron a hacer lo que desagradaba a Yahveh y Yahveh los entregó a merced de los filisteos durante cuarenta años.

[[judges-13-2]]
^2^ Había un hombre en Sorá, de la tribu de Dan, llamado Manóaj. Su mujer era estéril y no había tenido hijos.

[[judges-13-3]]
^3^ El ángel de Yahveh se apareció a esta mujer y le dijo: «Bien sabes que eres estéril y que no has tenido hijos,

[[judges-13-4]]
^4^ pero concebirás y darás a luz un hijo. En adelante guárdate de beber vino ni bebida fermentada y no comas nada impuro.

[[judges-13-5]]
^5^ Porque vas a concebir y a dar a luz un hijo. No pasará la navaja por su cabeza, porque el niño será nazir de Dios desde el seno de su madre. El comenzará a salvar a Israel de la mano de los filisteos».

[[judges-13-6]]
^6^ La mujer fue a decírselo a su marido: «Un hombre de Dios ha venido donde mí; su aspecto era como el del Angel de Dios, muy terrible. No le he preguntado de dónde venía ni él me ha manifestado su nombre.

[[judges-13-7]]
^7^ Pero me ha dicho: “Vas a concebir y a dar a luz un hijo. En adelante no bebas vino ni bebida fermentada y no comas nada impuro, porque el niño será nazir de Dios desde el seno de su madre hasta el día de su muerte».

[[judges-13-8]]
^8^ Manóaj invocó a Yahveh y dijo: «Te ruego, Señor, que el hombre de Dios que has enviado venga otra vez donde nosotros y nos enseñe lo que hemos de hacer con el niño cuando nazca».

[[judges-13-9]]
^9^ Dios escuchó a Manóaj y el Angel de Dios vino otra vez donde la mujer cuando estaba sentada en el campo. Manóaj, su marido, no estaba con ella.

[[judges-13-10]]
^10^ La mujer corrió enseguida a informar a su marido y le dijo: «Mira, se me ha aparecido el hombre que vino donde mí el otro día».

[[judges-13-11]]
^11^ Manóaj se levantó y, siguiendo a su mujer, llegó donde el hombre y le dijo: «¿Eres tú el que has hablado con esta mujer?» El respondió: «Yo soy».

[[judges-13-12]]
^12^ Le dijo Manóaj: «Cuando tu palabra se cumpla ¿cuál deberá ser la norma del niño y su conducta?»

[[judges-13-13]]
^13^ El Angel de Yahveh repondió a Manóaj: «Deberá abstenerse él de todo lo que indiqué a esta mujer.

[[judges-13-14]]
^14^ No probará nada de lo que procede de la viña, no beberá vino ni bebida fermentada, no comerá nada impuro y observará todo lo que yo le he mandado».

[[judges-13-15]]
^15^ Manóaj dijo entonces al Angel de Yahveh: «Permítenos retenerte y prepararte un cabrito».

[[judges-13-16]]
^16^ Pero el Angel de Yahveh dijo a Manóaj: «Aunque me obligues a quedarme no probaré tu comida. Pero si quieres preparar un holocausto, ofréceselo a Yahveh». Porque Manóaj no sabía que era el Angel de Yahveh.

[[judges-13-17]]
^17^ Manóaj dijo entonces al Angel de Yahveh: «¿Cuál es tu nombre para que, cuando se cumpla tu palabra, te podamos honrar?»

[[judges-13-18]]
^18^ El Angel de Yahveh le respondió: «¿Por qué me preguntas el nombre, si es maravilloso?».

[[judges-13-19]]
^19^ Manóaj tomó el cabrito y la oblación y lo ofreció en holocausto, sobre la roca, a Yahveh, que obra maravillas. Manóaj y su mujer estaban mirando.

[[judges-13-20]]
^20^ Cuando la llama subía del altar hacia el cielo, el Angel de Yahveh subía en la llama. Manóaj y su mujer lo estaban viendo y cayeron rostro en tierra.

[[judges-13-21]]
^21^ Al desaparecer el Angel de Yahveh de la vista de Manóaj y su mujer, Manóaj se dio cuenta de que era el Angel de Yahveh.

[[judges-13-22]]
^22^ Y dijo Manóaj a su mujer: «Seguro que vamos a morir, porque hemos visto a Dios».

[[judges-13-23]]
^23^ Su mujer le respondió: «Si Yahveh hubiera querido matarnos no habría aceptado de nuestra mano el holocausto ni la oblación, no nos habría mostrado todas estas cosas ni precisamente ahora nos habría hecho oír esto».

[[judges-13-24]]
^24^ La mujer dio a luz un hijo y le llamó Sansón. El niño creció y Yahveh le bendijo.

[[judges-13-25]]
^25^ Y el espíritu de Yahveh comenzó a excitarle en el Campamento de Dan, entre Sorá y Estaol.
[[judges-14]]
== Capítulo 14

[[judges-14-1]]
^1^ Sansón bajó a Timná y se fijó en Timná en una mujer entre las hijas de los filisteos.

[[judges-14-2]]
^2^ Subió y se lo dijo a su padre y a su madre: «He visto en Timná una mujer de entre las hijas de los filisteos: tomádmela para esposa».

[[judges-14-3]]
^3^ Su padre y su madre le dijeron: «¿No hay ninguna mujer entre las hijas de tus hermanos y en todo mi pueblo, para que vayas a tomar mujer entre esos filisteos incircuncisos?» Pero Sansón respondió a su padre: «Toma a ésa para mí, porque esa es la que me gusta».

[[judges-14-4]]
^4^ Su padre y su madre no sabían que esto venía de Yahveh, que buscaba un pretexto contra los filisteos, pues por aquel tiempo los filisteos dominaban a Israel.

[[judges-14-5]]
^5^ Sansón bajó a Timná y al llegar a las viñas de Timná, vio un leoncillo que venía rugiendo a su encuentro.

[[judges-14-6]]
^6^ El espíritu de Yahveh le invadió, y sin tener nada en la mano, Sansón despedazó al león como se despedaza un cabrito; pero no contó ni a su padre ni a su madre lo que había hecho.

[[judges-14-7]]
^7^ Bajó y habló con la mujer, la cual le agradó.

[[judges-14-8]]
^8^ Algún tiempo después, volvió Sansón para casarse con ella. Dio un rodeo para ver el cadáver del león y he aquí que en el cuerpo del león había un enjambre de abejas con miel.

[[judges-14-9]]
^9^ La recogió en su mano y según caminaba la iba comiendo. Cuando llegó donde su padre y su madre les dio miel y comieron, pero no les dijo que la había cogido del cadáver del león.

[[judges-14-10]]
^10^ Su padre bajó donde la mujer y Sansón hizo allí un banquete, pues así suelen hacer los jóvenes.

[[judges-14-11]]
^11^ Pero, al verle, eligieron treinta compañeros para que estuvieran con él.

[[judges-14-12]]
^12^ Sansón les dijo: «Os voy a proponer una adivinanza. Si me dais la solución dentro de los siete días de la fiesta y acertáis, os daré treinta túnicas y treinta mudas.

[[judges-14-13]]
^13^ Pero si no podéis darme la solución, entonces me daréis vosotros treinta túnicas y treinta mudas». Ellos le dijeron: «Propón tu adivinanza, que te escuchamos».

[[judges-14-14]]
^14^ El les dijo: «Del que come salió comida, y del fuerte salió dulzura». A los tres días aún no habían acertado la adivinanza.

[[judges-14-15]]
^15^ Al cuarto día dijeron a la mujer de Sansón: «Convence a tu marido para que nos explique la adivinanza. Si no, te quemaremos a ti y a la casa de tu padre. ¿O es que nos habéis invitado para robarnos?»

[[judges-14-16]]
^16^ La mujer de Sansón se puso a llorar sobre él, y dijo: «Tú me odias y no me amas. Has propuesto una adivinanza a los hijos de mi pueblo y a mí no me la has explicado». El le respondió: «Ni a mi padre ni a mi madre se la he explicado ¿y te la voy a explicar a ti?»

[[judges-14-17]]
^17^ Ella estuvo llorando encima de él los siete días que duró la fiesta. Por fin el séptimo día se la explicó, porque lo tenía asediado y ella explicó la adivinanza a los hijos de su pueblo.

[[judges-14-18]]
^18^ El séptimo día, antes que entrara en la alcoba, la gente de la ciudad dijo a Sansón: «¿Qué hay más dulce que la miel, y qué más fuerte que el león?» El les repondió: «Si no hubierais arado con mi novilla, no habríais acertado mi adivinanza».

[[judges-14-19]]
^19^ Luego el espíritu de Yahveh le invadió, bajó a Ascalón y mató allí a treinta hombres, tomó sus despojos y entregó las mudas a los acertantes de la adivinanza; luego, encendido en cólera, subió a la casa de su padre.

[[judges-14-20]]
^20^ La mujer de Sansón pasó a ser de un compañero suyo, el que había sido su amigo de confianza.
[[judges-15]]
== Capítulo 15

[[judges-15-1]]
^1^ Algún tiempo después, por los días de la siega del trigo, fue Sansón a visitar a su mujer llevando un cabrito y dijo: «Quiero llegarme a mi mujer, en la alcoba». Pero el padre de ella no le dejó entrar.

[[judges-15-2]]
^2^ y le dijo: «Yo pensé que ya no la querías y se la di a tu compañero. ¿No vale más su hermana menor? Sea tuya en lugar de la otra».

[[judges-15-3]]
^3^ Sansón les replicó: «Esta vez no tengo culpa con los con los filisteos si les hago daño».

[[judges-15-4]]
^4^ Se fue Sansón, y cazó trescientas zorras; cogió unas teas y, juntando a los animales cola con cola, puso una tea en medio entre las dos colas.

[[judges-15-5]]
^5^ Prendió fuego a las teas y luego, soltando las zorras por las mieses de los filisteos, incendió las gavillas y el trigo todavía en pie y hasta las viñas y olivares.

[[judges-15-6]]
^6^ Los filisteos preguntaron: «¿Quién ha hecho esto?» Y les respondieron: «Sansón, el yerno del timnita, porque éste tomó a su mujer y se la dio a su compañero». Entonces los filisteos subieron y quemaron a aquella mujer y la casa de su padre.

[[judges-15-7]]
^7^ Sansón les dijo: «Ya que os portáis así no he de parar hasta vengarme de vosotros».

[[judges-15-8]]
^8^ Y les midió las costillas causándoles un gran estrago. Después bajó a la gruta de la roca de Etam y se quedó allí.

[[judges-15-9]]
^9^ Los filisteos subieron a acampar en Judá e hicieron una incursión por Lejí.

[[judges-15-10]]
^10^ Y les dijeron los hombres de Judá: «¿Por qué habéis subido contra nosotros?» Respondieron: «Hemos subido para amarrar a Sansón, para hacer con él lo que él ha hecho con nosotros».

[[judges-15-11]]
^11^ 3.000 hombres de Judá bajaron a la gruta de la roca de Etam y dijeron a Sansón: «¿No sabes que los filisteos nos están dominando? ¿Qué nos has hecho?» El les repondió: «Como me trataron a mí, les he tratado yo a ellos».

[[judges-15-12]]
^12^ Ellos le dijeron: «Hemos bajado para amarrarte y entregarte en manos de los filisteos». Sansón les dijo: «Juradme que no me vais a matar vosotros mismos».

[[judges-15-13]]
^13^ Le respondieron: «No; sólo queremos amarrarte y entregarte, no te mataremos». Lo amarraron, pues, con dos cordeles nuevos y lo sacaron de entre las rocas.

[[judges-15-14]]
^14^ Cuando llegaba a Lejí y los filisteos corrían a su encuentro, con gritos de triunfo, el espíritu de Yahveh vino sobre él: los cordeles que sujetaban sus brazos fueron como hilos de lino que se queman al fuego y las ligaduras se deshicieron entre sus manos.

[[judges-15-15]]
^15^ Encontró una quijada de asno todavía fresca, alargó la mano, la cogió y mató con ella a mil hombres.

[[judges-15-16]]
^16^ Sansón dijo entonces: «Con quijada de asno los amontoné. Con quijada de asno, a mil hombres sacudí».

[[judges-15-17]]
^17^ Cuando terminó de hablar, tiró la quijada: por eso se llamó aquel lugar Ramat Lejí.

[[judges-15-18]]
^18^ Entonces sintió una sed terrible e invocó a Yahveh diciendo: «Tú has logrado esta gran victoria por mano de tu siervo y ahora ¿voy a morir de sed y a caer en manos de los incircuncisos?»

[[judges-15-19]]
^19^ Entonces Dios hendió la cavidad que hay en Lejí y brotó agua de ella. Sansón bebió, recobró su espíritu y se reanimó. Por eso se dio el nombre de En Haccoré a la fuente que existe todavía hoy en Lejí.

[[judges-15-20]]
^20^ Sansón fue juez en Israel en la época de los filisteos por espacio de veinte años.
[[judges-16]]
== Capítulo 16

[[judges-16-1]]
^1^ De allí Sansón se dirigió a Gaza, vio allí una meretriz y entró donde ella.

[[judges-16-2]]
^2^ Se dio aviso a los hombres de Gaza: «Ha venido Sansón». Ellos le rodearon y le estuvieron acechando a la puerta de la ciudad. Estuvieron quietos toda la noche pensando: «Esperemos hasta que despunte el día y lo mataremos».

[[judges-16-3]]
^3^ Sansón estuvo durmiendo hasta media noche; y a media noche se levantó, cogió las hojas de la puerta de la ciudad con sus dos jambas, las arrancó junto con la barra, se las cargó a la espalda, y las subió hasta la cumbre del monte que está frente a Hebrón.

[[judges-16-4]]
^4^ Después de esto, se enamoró de una mujer de la vaguada de Soreq, que se llamaba Dalila.

[[judges-16-5]]
^5^ Los tiranos de los filisteos subieron donde ella y le dijeron: «Sonsácale y entérate de dónde le viene esa fuerza tan enorme, y cómo podríamos dominarlo para amarrarlo y tenerlo sujeto. Nosotros te daremos cada uno 1.100 siclos de plata».

[[judges-16-6]]
^6^ Dalila dijo a Sansón: «Dime, por favor, ¿de dónde te viene esa fuerza tan grande y con qué habría que atarte para tenerte sujeto?»

[[judges-16-7]]
^7^ Sansón le respondió: «Si me amarraran con siete cuerdas de arco todavía frescas, sin dejarlas secar, me debilitaría y sería como un hombre cualquiera».

[[judges-16-8]]
^8^ Los tiranos de los filisteos llevaron a Dalila siete cuerdas de arco frescas, sin secar aún, y lo amarró con ellas.

[[judges-16-9]]
^9^ Tenía ella hombres apostados en la alcoba y le gritó: «Los filisteos contra ti, Sansón». El rompió las cuerdas de arco como se rompe el hilo de estopa en cuanto siente el fuego. Así no se descubrió el secreto de la fuerza.

[[judges-16-10]]
^10^ Entonces Dalila dijo a Sansón: «Te has reído de mí y me has dicho mentiras; dime pues, por favor, con qué habría que atarte».

[[judges-16-11]]
^11^ El le respondió: «Si me amarraran bien con cordeles nuevos sin usar, me debilitaría y sería como un hombre cualquiera».

[[judges-16-12]]
^12^ Dalila cogió unos cordeles nuevos, lo amarró con ellos y le gritó: «Los filisteos contra ti, Sansón». Tenía ella hombres apostados en la alcoba, pero él rompió los cordeles de sus brazos como un hilo.

[[judges-16-13]]
^13^ Entonces Dalila dijo a Sansón: «Hasta ahora te has estado burlando de mi y no me has dicho más que mentiras. Dime con qué habría de amarrarte». El le respondió: «Si tejieras las siete trenzas de mi cabellera con la trama y las clavaras con la clavija del tejedor, me debilitaría y sería como un hombre cualquiera».

[[judges-16-14]]
^14^ Ella le hizo dormir, tejió luego las siete trenzas de su cabellera con la trama, las clavó con la clavija y le gritó: «Los filisteos contra ti, Sansón». El se despertó de su sueño y arrancó la trama y la clavija. Así no se descubrió el secreto de su fuerza.

[[judges-16-15]]
^15^ Dalila le dijo: «¿Cómo puedes decir: “Te amo “, si tu corazón no está conmigo? Tres veces te has reído ya de mí y no me has dicho en qué consiste esa fuerza tan grande».

[[judges-16-16]]
^16^ Como todos los días le asediaba con sus palabras y le importunaba, aburrido de la vida,

[[judges-16-17]]
^17^ le abrió todo su corazón y le dijo: «La navaja no ha pasado jamás por mi cabeza, porque soy nazir de Dios desde el vientre de mi madre. Si me rasuraran, mi fuerza se retiraría de mí, me debilitaría y sería como un hombre cualquiera».

[[judges-16-18]]
^18^ Dalila comprendió entonces que le había abierto todo su corazón, mandó llamar a los tiranos de los filisteos y les dijo: «Venid esta vez, pues me ha abierto todo su corazón». Y los tiranos de los filisteos vinieron donde ella con el dinero en la mano.

[[judges-16-19]]
^19^ Ella hizo dormir a Sansón sobre sus rodillas y llamó a un hombre que le cortó las siete trenzas de su cabeza. Entonces ella comenzó a humillarlo, y se retiró de él su vigor.

[[judges-16-20]]
^20^ Ella gritó: «Los filisteos contra ti, Sansón». El se despertó de su sueño y se dijo: «Saldré como las otras veces y me desembarazaré». No sabía que Yahveh se había apartado de él.

[[judges-16-21]]
^21^ Los filisteos le echaron mano, le sacaron los ojos, y lo bajaron a Gaza. Allí lo ataron con una doble cadena de bronce y daba vueltas a la muela en la cárcel.

[[judges-16-22]]
^22^ Pero el pelo de su cabeza, nada más rapado, empezó a crecer.

[[judges-16-23]]
^23^ Los tiranos de los filisteos se reunieron para ofrecer un gran sacrificio a su dios Dagón y hacer gran fiesta. Decían: «Nuestro dios ha puesto en nuestras manos a Sansón nuestro enemigo».

[[judges-16-24]]
^24^ En cuanto lo vio la gente, alababa a su dios diciendo: «Nuestro dios ha puesto en nuestras manos a Sansón nuestro enemigo, al que devastaba nuestro país y multiplicaba nuestras víctimas».

[[judges-16-25]]
^25^ Y como su corazón estaba alegre, dijeron: «Llamad a Sansón para que nos divierta». Trajeron, pues, a Sansón de la cárcel, y él les estuvo divirtiendo; luego lo pusieron de pie entre las columnas.

[[judges-16-26]]
^26^ Sansón dijo entonces al muchacho que lo llevaba de la mano: «Ponme donde pueda tocar las columnas en las que descansa la casa para que me apoye en ellas».

[[judges-16-27]]
^27^ La casa estaba llena de hombres y mujeres. Estaban dentro todos los tiranos de los filisteos y, en el terrado, unos 3.000 hombres y mujeres comtemplando los juegos de Sansón.

[[judges-16-28]]
^28^ Sansón invocó a Yahveh y exclamó: «Señor Yahveh, dígnate acordarte de mí, hazme fuerte nada más que esta vez, oh Dios, para que de un golpe me vengue de los filisteos por mis dos ojos».

[[judges-16-29]]
^29^ Y Sansón palpó las dos columnas centrales sobre las que descansaba la casa, se apoyó contra ellas, en una con su brazo derecho, en la otra con el izquierdo,

[[judges-16-30]]
^30^ y gritó: «¡Muera yo con los filisteos!» Apretó con todas sus fuerzas y la casa se derrumbó sobre los tiranos y sobre toda la gente allí reunida. Los muertos que mató al morir fueron más que los que había matado en vida.

[[judges-16-31]]
^31^ Sus hermanos y toda la casa de su padre bajaron y se lo llevaron. Lo subieron y sepultaron entre Sorá y Estaol, en el sepulcro de su padre Manóaj. Había juzgado a Israel por espacio de veinte años.
[[judges-17]]
== Capítulo 17

[[judges-17-1]]
^1^ Había en la montaña de Efraím un hombre llamado Miqueas.

[[judges-17-2]]
^2^ Dijo a su madre: «Los 1.100 siclos de plata que te quitaron y por los que lanzaste una maldición, incluso oí que dijiste... esa plata la tengo yo; yo la robé». Su madre respondió: «Que mi hijo sea bendito de Yahveh».

[[judges-17-3]]
^3^ Y él le devolvió los 1.100 siclos de plata. Y su madre dijo: «Yo consagré solemne y espontáneamente, por mi hijo, esta plata a Yahveh, para hacer con ella una imagen y un ídolo de fundición, pero ahora te la devuelvo». Y él devolvió la plata a su madre.

[[judges-17-4]]
^4^ Su madre tomó doscientos siclos de plata y los entregó al fundidor. Este le hizo una imagen (y un ídolo de metal fundido) que quedó en casa de Miqueas.

[[judges-17-5]]
^5^ Este hombre, Miká, tenía una Casa de Dios; hizo un efod y unos terafim e invistió a uno de sus hijos que vino a ser su sacerdote.

[[judges-17-6]]
^6^ En aquel tiempo no había rey en Israel y hacía cada uno lo que le parecía bien.

[[judges-17-7]]
^7^ Había un joven de Belén de Judá, de la familia de Judá, que era levita y residía allí como forastero.

[[judges-17-8]]
^8^ Este hombre dejó la ciudad de Belén de Judá para ir a residir donde pudiera. Haciendo su camino llegó a la montaña de Efraím, a la casa de Miká.

[[judges-17-9]]
^9^ Miká le preguntó: «¿De dónde vienes?» Le respondió: «Soy un levita de Belén de Judá. Vengo de paso para residir donde pueda».

[[judges-17-10]]
^10^ Miká le dijo: «Quédate en mi casa, y serás para mí un padre y un sacerdote; yo te daré diez siclos de plata al año, el vestido y la comida».

[[judges-17-11]]
^11^ El levita accedió a quedarse en casa de aquel hombre y el joven fue para él como uno de sus hijos.

[[judges-17-12]]
^12^ Miká invistió al levita; el joven fue su sacerdote y se quedó en casa de Miká.

[[judges-17-13]]
^13^ Y dijo Miká: «Ahora sé que Yahveh me favorecerá, porque tengo a este levita como sacerdote».
[[judges-18]]
== Capítulo 18

[[judges-18-1]]
^1^ Por aquel tiempo no había rey en Israel. Por entonces la tribu de Dan buscaba un territorio donde habitar, pues hasta aquel día no le había tocado heredad entre las tribus de Israel.

[[judges-18-2]]
^2^ Los danitas enviaron a cinco hombres de su familia, hombres valientes de Sorá y Estaol, para recorrer el país y explorarlo. Y les dijeron: «Id a explorar esa tierra». Llegaron a la montaña de Efraím cerca de la casa de Miká, y pasaron allí la noche.

[[judges-18-3]]
^3^ Como estaban cerca de la casa de Miká, reconocieron la voz del joven levita, y llegándose allá le dijeron: «¿Quién te ha traído por acá?, ¿qué haces en este lugar? ¿qué se te ha perdido aquí?»

[[judges-18-4]]
^4^ El les respondió: «Esto y esto ha hecho por mí Miká. Me ha tomado a sueldo y soy su sacerdote».

[[judges-18-5]]
^5^ Le dijeron: «Consulta, pues, a Dios, para que sepamos si el viaje que estamos haciendo tendrá feliz término».

[[judges-18-6]]
^6^ Les respondió el sacerdote: «Id en paz; el viaje que hacéis está bajo la mirada de Yahveh».

[[judges-18-7]]
^7^ Los cinco hombres partieron y llegaron a Lais. Vieron que las gentes que habitaban allí vivían seguras, según las costumbres de los sidonios, tranquilas y confiadas; que nada faltaba allí de cuanto produce la tierra, que estaban lejos de los sidonios y no tenían relaciones con los arameos.

[[judges-18-8]]
^8^ Volvieron entonces donde sus hermanos, a Sorá y Estaol, y éstos les preguntaron: «¿Qué noticias traéis?»

[[judges-18-9]]
^9^ Ellos repondieron: «¿Arriba!, vayamos contra ellos, porque hemos visto el país y es excelente. Pero ¿por qué estáis parados sin decir nada? No dudéis en partir para ir a conquistar aquella tierra.

[[judges-18-10]]
^10^ Cuando lleguéis, os encontraréis con un pueblo tranquilo. El país es espacioso: Dios lo ha puesto en nuestras manos; es un lugar en el que no falta nada de lo que puede haber sobre la tierra».

[[judges-18-11]]
^11^ Partieron, pues, de allí, del clan de los danitas, de Sorá y Estaol, seiscientos hombres bien armados.

[[judges-18-12]]
^12^ Subieron y acamparon en Quiryat Yearim, en Judá. Por eso, todavía hoy, se llama aquel lugar el Campamento de Dan. Está detrás de Quiryat Yearim.

[[judges-18-13]]
^13^ De allí pasaron a la montaña de Efraím y llegaron a la casa de Miká.

[[judges-18-14]]
^14^ Los cinco hombres que habían ido a recorrer la tierra, tomaron la palabra y dijeron a sus hermanos: «¿No sabéis que hay aquí en estas casas un efod, unos terafim, una imagen y un ídolo de metal fundido? Considerad, pues, lo que habéis de hacer».

[[judges-18-15]]
^15^ Llegándose allá entraron en la casa del joven levita, la casa de Miká, y le dieron el saludo de paz.

[[judges-18-16]]
^16^ Los seiscientos hombres danitas con sus armas de guerra estaban en el umbral de la puerta.

[[judges-18-17]]
^17^ Los cinco hombres que habían ido a recorrer la tierra subieron, entraron dentro y cogieron la imagen, el efod, los terafim y el ídolo de fundición; entre tanto el sacerdote estaba en el umbral de la puerta con los seiscientos hombres armados.

[[judges-18-18]]
^18^ Aquéllos, pues, entrando en la casa de Miká, cogieron la imagen, el efod, los terafim y el ídolo de fundición. El sacerdote les dijo: «¿Qué estáis haciendo?»

[[judges-18-19]]
^19^ «Calla - le contestaron - pon la mano en la boca y ven con nosotros. Serás para nosotros padre y sacerdote. ¿Prefieres ser sacerdote de la casa de un particular a ser sacerdote de una tribu y de un clan de Israel?»

[[judges-18-20]]
^20^ Se alegró con ello el corazón del sacerdote, tomó el efod, los terafim y la imagen y se fue en medio de la tropa.

[[judges-18-21]]
^21^ Reemprendieron el camino colocando en la cabeza a las mujeres, los miños, los rebaños y los objetos preciosos.

[[judges-18-22]]
^22^ Estaban ya lejos de la casa de Miká, cuando los hombres de las casas vecinas a la casa de Miká dieron la alarma y salieron en persecución de los danitas,

[[judges-18-23]]
^23^ y les gritaron. Se volvieron éstos y dijeron a Miká: «¿Qué te pasa para gritar así?»

[[judges-18-24]]
^24^ Respondió: «Me habéis quitado a mi dios, el que yo me había hecho, y a mi sacerdote. Vosotros os marcháis, y a mí ¿qué me queda? y encima me decís: ¿Qué te pasa?»

[[judges-18-25]]
^25^ Los danitas le contestaron: «Calla de una vez, no sea que algunos irritados caigan sobre vosotros y pierdas tu vida y la de tu casa».

[[judges-18-26]]
^26^ Los danitas siguieron su camino; y Miká, viendo que eran más fuertes, se volvió a su casa.

[[judges-18-27]]
^27^ Ellos tomaron el dios que Miká había fabricado y el sacerdote que tenía, y marcharon contra Lais, pueblo tranquilo y confiado. Pasaron a cuchillo a la población e incendiaron la ciudad.

[[judges-18-28]]
^28^ Nadie vino en su ayuda, porque estaba lejos de Sidón y no tenía relaciones con los arameos. Estaba situada en el valle que se extiende hacia Bet Rejob. Reconstruyeron la ciudad, se establecieron en ella,

[[judges-18-29]]
^29^ y le pusieron el nombre de Dan, en recuerdo de su padre Dan, hijo de Israel. Aunque antiguamente la ciudad se llamaba Lais.

[[judges-18-30]]
^30^ Los danitas erigieron para sí la imagen. Jonatán, hijo de Guersón, hijo de Moisés, y después sus hijos, fueron sacerdotes de la tribu de Dan hasta el día de la deportación del país.

[[judges-18-31]]
^31^ Se erigieron la imagen que había hecho Miká y allí permaneció mientras estuvo en Silo la casa de Dios.
[[judges-19]]
== Capítulo 19

[[judges-19-1]]
^1^ En aquel tiempo, cuando aún no había rey en Israel, hubo un hombre, levita, que residía como forastero en los confines de la montaña de Efraím. Tomó por concubina a una mujer de Belén de Judá.

[[judges-19-2]]
^2^ Se enfadó con él su concubina y lo dejó para volver a la casa de su padre en Belén de Judá, donde permanició bastante tiempo, unos cuatro meses.

[[judges-19-3]]
^3^ Su marido se puso en camino y fue donde ella, para hablarle al corazón y hacerla volver; llevaba consigo a su criado y un par de asnos. Cuando llegó a casa del padre de ella, le vio el padre de la joven y salió contento a su encuentro.

[[judges-19-4]]
^4^ Su suegro, el padre de la joven, lo retuvo y él se quedó con él tres días; comieron y bebieron y pasaron allí la noche.

[[judges-19-5]]
^5^ Al cuarto día se levantaron de madrugada y el levita se dispuso a partir; el padre de la joven dijo a su yerno: «Toma un bocado de pan para cobrar ánimo, y luego marcharás».

[[judges-19-6]]
^6^ Se sentaron, y se pusieron a comer y beber los dos juntos. Luego el padre de la joven dijo al hombre: «Decídete, pasa aquí la noche y que se alegre tu corazón».

[[judges-19-7]]
^7^ Se levantó el hombre para marchar, pero el suegro le porfió y se quedó aquella noche.

[[judges-19-8]]
^8^ Al quinto día madrugó para marchar, pero el padre de la joven le dijo: «Cobra ánimo primero, por favor». Y pasaron el tiempo hasta declinar el día y comieron juntos.

[[judges-19-9]]
^9^ Se levantaron para marchar el marido con su concubina y su siervo, pero su suegro, el padre de la joven, le dijo: «Mira que la tarde está al caer. Pasa aquí la noche y que se alegre tu corazón. Mañana de madrugada marcharéis y volverás a tu tienda».

[[judges-19-10]]
^10^ Pero el hombre no quiso pasar la noche allí; se levantó, partió y llegó frente a Jebús, o sea, Jerusalén. Llevaba consigo los dos asnos cargados, su concubina y su criado.

[[judges-19-11]]
^11^ Cuando llegaban cerca de Jebús, era ya hora muy avanzada. El criado dijo a su amo: «Vamos, dejemos el camino y entremos en esa ciudad de los jebuseos para pasar allí la noche».

[[judges-19-12]]
^12^ Su amo le respondió: «No vamos a entrar en una ciudad de extranjeros, que no son israelitas; pasaremos de largo hasta Guibeá».

[[judges-19-13]]
^13^ Y añadió a su criado: «Vamos a acercarnos a uno de esos poblados; pasaremos la noche en Guibeá o Ramá».

[[judges-19-14]]
^14^ Pasaron, pues, de largo y continuaron su marcha. Y a la puesta del sol, llegaron frente a Guibeá de Benjamín.

[[judges-19-15]]
^15^ Se desviaron hacia allí y fueron a pasar la noche en Guibeá. El levita entró y se sentó en la plaza de la ciudad, pero no hubo nadie que les ofreciera casa donde pasar la noche.

[[judges-19-16]]
^16^ Llegó un viejo que volvía por la tarde de sus faenas del campo. Era un hombre de la montaña de Efraím que residía como forastero en Guibeá; mientras que la gente del lugar era benjaminita.

[[judges-19-17]]
^17^ Alzando los ojos, se fijó en el viajero que estaba en la plaza de la ciudad, y el anciano le dijo: «¿A dónde vas y de dónde vienes?»

[[judges-19-18]]
^18^ Y el otro le respondió: «Estamos de paso, venimos de Belén de Judá y vamos hasta los confines de la montaña de Efraím, de donde soy. Fui a Belén de Judá y ahora vuelvo a mi casa, pero nadie me ha ofrecido su casa.

[[judges-19-19]]
^19^ Y eso que tenemos paja y forraje para nuestros asnos, y pan y vino para mí, para tu sierva y para el joven que acompaña a tu siervo. No nos falta de nada».

[[judges-19-20]]
^20^ El viejo le dijo: «La paz sea contigo; yo proveeré a todas tus necesidades; pero no pases la noche en la plaza».

[[judges-19-21]]
^21^ Le llevó, pues, a su casa y echó pienso a los asnos. Y ellos se lavaron los pies, comieron y bebieron.

[[judges-19-22]]
^22^ Mientras alegraban su corazón, los hombres de la ciudad, gente malvada, cercaron la casa y golpeando la puerta le dijeron al viejo, dueño de la casa: «Haz salir al hombre que ha entrado en tu casa para que lo conozcamos».

[[judges-19-23]]
^23^ El dueño de la casa salió donde ellos y les dijo: «No, hermanos míos; no os portéis mal. Puesto que este hombre ha entrado en mi casa no cometáis esa infamia.

[[judges-19-24]]
^24^ Aquí está mi hija, que es doncella. Os la entregaré. Abusad de ella y haced con ella lo que os parezca; pero no cometáis con este hombre semejante infamia».

[[judges-19-25]]
^25^ Pero aquellos hombres no quisieron escucharle. Entonces el hombre tomó a su concubina y se la sacó fuera. Ellos la conocieron, la maltrataron toda la noche hasta la mañana y la dejaron al amanecer.

[[judges-19-26]]
^26^ Llegó la mujer de madrugada y cayó a la entrada de la casa del hombre donde estaba su marido; allí quedó hasta que fue de día.

[[judges-19-27]]
^27^ Por la mañana se levantó su marido, abrió las puertas de la casa y salió para continuar su camino; y vio que la mujer, su concubina, estaba tendida a la entrada de la casa, con las manos en el umbral,

[[judges-19-28]]
^28^ y le dijo: «Levántate, vámonos». Pero no le respondió. Entonces el hombre la cargó sobre su asno y se puso camino de su pueblo.

[[judges-19-29]]
^29^ Llegado a su casa, cogió un cuchillo y tomando a su concubina la partió miembro por miembro en doce trozos y los envió por todo el territorio de Israel.

[[judges-19-30]]
^30^ Y dio esta orden a su emisarios: «Esto habéis de decir a todos los israelitas: ¿Se ha visto alguna vez cosa semejante desde que los israelitas subieron del país de Egipto hasta hoy? Pensad en ello, pedid consejo y tomad una decisión». Y todos los que lo veían, decían: «Nunca ha ocurrido ni se ha visto cosa igual desde que los israelitas subieron del país de Egipto hasta hoy».
[[judges-20]]
== Capítulo 20

[[judges-20-1]]
^1^ Salieron, pues, todos los israelitas y se reunió toda la comunidad como un solo hombre, desde Dan hasta Berseba y el país de Galaad, delante de Yahveh, en Mispá.

[[judges-20-2]]
^2^ Los principales de todo el pueblo y todas las tribus de Israel acudieron a la asamblea del pueblo de Dios: 400.000 hombres de a pie, armados de espada.

[[judges-20-3]]
^3^ Oyeron los benjaminitas que los hijos de Israel habían subido a Mispá... Los israelitas dijeron: «Decidnos cómo ha sido el crimen».

[[judges-20-4]]
^4^ El levita, marido de la mujer asesinada, tomó la palabra y dijo: «Había llegado yo con mi concubina a Guibeá de Benjamín para pasar la noche.

[[judges-20-5]]
^5^ Los señores de Guibeá se levantaron contra mí y rodearon por la noche la casa; intentaron matarme a mí, y abusaron tanto de mi concubina que murió.

[[judges-20-6]]
^6^ Tomé entonces a mi concubina, la descuarticé y la envié por todo el territorio de la heredad de Israel, porque habían cometido una vergüenza y una infamia en Israel.

[[judges-20-7]]
^7^ Aquí estáis todos, israelitas: tratadlo y tomad aquí mismo una resolución».

[[judges-20-8]]
^8^ Todo el pueblo se levantó como un solo hombre diciendo: «Ninguno de nosotros marchará a su tienda, nadie volverá a su casa.

[[judges-20-9]]
^9^ Esto es lo que hemos de hacer con Guibeá. Echaremos a suertes

[[judges-20-10]]
^10^ y tomaremos de todas las tribus de Israel diez hombres por cada cien, cien por cada mil, y mil por cada 10.000; ellos recogerán víveres para la tropa, para hacer, en cuanto lleguen, con Guibeá de Benjamín según la infamia que han cometido en Israel».

[[judges-20-11]]
^11^ Así se juntó contra la ciudad toda la gente de Israel como un solo hombre.

[[judges-20-12]]
^12^ Las tribus de Israel enviaron emisarios a toda la tribu de Benjamín diciendo: «¿Qué crimen es ése que se ha cometido entre vosotros?

[[judges-20-13]]
^13^ Ahora, pues, entregadnos a esos hombres malvados de Guibeá, para que los matemos y desaparezca el mal de Israel». Pero los benjaminitas no quisieron hacer caso a sus hermanos los israelitas.

[[judges-20-14]]
^14^ Los benjaminitas, dejando sus ciudades, se reunieron en Guibeá para salir al combate contra los israelitas.

[[judges-20-15]]
^15^ Aquel día los benjaminitas llegados de las diversas ciudades hicieron el censo, que dio en total 25.000 hombres armados de espada, sin contar los habitantes de Guibeá.

[[judges-20-16]]
^16^ En toda esta tropa había setecientos hombres elegidos, zurdos, capaces todos ellos de lanzar una piedra con la honda contra un cabello sin errar el tiro.

[[judges-20-17]]
^17^ La gente de Israel hizo también el censo. Sin contar a Benjamín, eran 400.000 armados de espada; todos hombres de guerra.

[[judges-20-18]]
^18^ Partieron, pues, y subieron a Betel. Consultaron a Dios y le preguntaron los israelitas: «¿Quién de nosotros subirá el primero a combatir contra los benjaminitas?» Y Yahveh respondió: «Judá subirá primero».

[[judges-20-19]]
^19^ Los israelitas se levantaron temprano y acamparon frente a Guibeá.

[[judges-20-20]]
^20^ Salieron los hombres de Israel para combatir contra Benjamín y se pusieron en orden de batalla frente a Guibeá.

[[judges-20-21]]
^21^ Pero los benjaminitas salieron de Guibeá y dejaron muertos en tierra aquel día a 22.000 hombres de Israel.

[[judges-20-22]]
^22^ Los israelitas subieron a llorar delante de Yahveh hasta la tarde y luego consultaron a Yahveh diciendo: «¿He de entablar combate otra vez contra los hijos de mi hermano Benjamín?» Yahveh respondió: «Subid contra él».

[[judges-20-23]]
^23^ Entonces la tropa de Israel recobró su valor y volvió a ponerse en orden de batalla en el mismo lugar que el primer día.

[[judges-20-24]]
^24^ El segundo día los israelitas se acercaron a los benjaminitas;

[[judges-20-25]]
^25^ pero también aquel segundo día Benjamín salió de Guibeá a su encuentro y volvió a dejar tendidos en tierra a 18.000 israelitas; todos ellos armados de espada.

[[judges-20-26]]
^26^ Entonces todos los israelitas y todo el pueblo subieron hasta Betel, lloraron, se quedaron allí delante de Yahveh, ayunaron todo el día hasta la tarde y ofrecieron holocaustos y sacrificios de comunión delante de Yahveh.

[[judges-20-27]]
^27^ Consultaron luego los israelitas a Yahveh, pues el arca de la alianza de Dios se encontraba allí,

[[judges-20-28]]
^28^ y Pinjás, hijo de Eleazar, hijo de Aarón, estaba entonces a su servicio. Dijeron: «¿He de salir otra vez a combatir a los hijos de mi hermano Benjamín o debo dejarlo?» Yahveh respondió: «Subid, porque mañana lo entregaré en vuestras manos».

[[judges-20-29]]
^29^ Israel puso gente emboscada alrededor de Guibeá.

[[judges-20-30]]
^30^ Al tercer día los israelitas marcharon contra los benjaminitas y se pusieron en orden de batalla como las otras veces frente a Guibeá.

[[judges-20-31]]
^31^ Los benjaminitas salieron a su encuentro y se dejaron atraer lejos de la ciudad. Comenzaron como las otras veces a matar gente del pueblo por los caminos que suben, uno a Betel y otro a Guibeá, a campo raso: unos treinta hombres de Israel.

[[judges-20-32]]
^32^ Los benjaminitas se dijeron: «Han sido derrotados ante nosotros como la primera vez». Pero los israelitas se habían dicho: «Vamos a huir para atraerlos lejos de la ciudad hacia los caminos».

[[judges-20-33]]
^33^ Entonces todos los hombres de Israel se levantaron de sus puestos, tomaron posiciones en Baal Tamar, y los emboscados de Israel atacaron desde su puesto al oeste de Gueba.

[[judges-20-34]]
^34^ 10.000 hombres elegidos de todo Israel llegaron frente a Guibeá. El combate se endureció; los benjaminitas no se daban cuenta de la calamidad que se les venía encima.

[[judges-20-35]]
^35^ Yahveh derrotó a Benjamín ante Israel y aquel día los israelitas mataron en Benjamín a 25.100 hombres, todos ellos armados de espada.

[[judges-20-36]]
^36^ Los benjaminitas se vieron derrotados. Los hombres de Israel habían cedido terreno a Benjamín porque contaban con la emboscada que habían puesto contra Guibeá.

[[judges-20-37]]
^37^ Los emboscados marcharon a toda prisa contra Guibeá, se desplegaron y pasaron a cuchillo a toda la ciudad.

[[judges-20-38]]
^38^ La gente de Israel y los emboscados habían convenido en levantar una humareda, como señal, desde la ciudad;

[[judges-20-39]]
^39^ entonces harían frente a los combatientes de Israel. Benjamín comenzó matando a algunos israelitas, unos treinta hombres. Y se decían: «Están completamente derrotados ante nosotros, como en la primera batalla».

[[judges-20-40]]
^40^ Pero entonces, la señal, la columna de humo, comenzó a levantarse de la ciudad, y Benjamín, mirando atrás, vio que toda la ciudad subía en llamas al cielo.

[[judges-20-41]]
^41^ Entonces los hombres de Israel hicieron frente y los benjaminitas temblaron al ver la calamidad que se les venía encima.

[[judges-20-42]]
^42^ Volvieron la espalda ante la gente de Israel camino del desierto, pero los combatientes los acosaban, y los que venían de la ciudad los destrozaban cogiéndolos en medio.

[[judges-20-43]]
^43^ Así envolvieron a Benjamín, lo persiguieron sin descanso y lo aplastaron hasta llegar frente a Gueba por el oriente.

[[judges-20-44]]
^44^ Cayeron de Benjamín 18.000 hombres, todos ellos hombres valerosos.

[[judges-20-45]]
^45^ Volvieron la espalda y huyeron al desierto, hacia la Peña de Rimmón. Los israelitas fueron atrapando por los caminos a 5.000 hombres. Luego persiguieron a Benjamín hasta Guidom y le mataron 2.000 hombres.

[[judges-20-46]]
^46^ El tota de los benjaminitas que cayeron aquel día fue de 25.000 hombres, armados de espada, todos ellos hombres valerosos.

[[judges-20-47]]
^47^ Seiscientos hombres habían podido volverse y escapar al desierto, hacia la Peña de Rimmón. Se quedaron en la Peña de Rimmón cuatro meses.

[[judges-20-48]]
^48^ Las tropas de Israel se volvieron contra los benjaminitas, y pasaron a cuchillo a los varones de la ciudad, al ganado, y a todo lo que encontraron. Incendiaron también todas las ciudades que encontraron.
[[judges-21]]
== Capítulo 21

[[judges-21-1]]
^1^ Los hombres de Israel habían jurado en Mispá: «Ninguno de nosotros dará su hija en matrimonio a Benjamín».

[[judges-21-2]]
^2^ El pueblo fue a Betel y allí permaneció delante de Dios hasta la tarde clamando y llorando con grandes gemidos.

[[judges-21-3]]
^3^ Decían: «Yahveh, Dios de Israel, ¿por qué ha de suceder esto en Israel, que desaparezca hoy de Israel una de sus tribus?»

[[judges-21-4]]
^4^ Al día siguiente el pueblo se levantó de madrugada, construyó allí un altar, y ofreció holocaustos y sacrificios de comunión.

[[judges-21-5]]
^5^ Dijeron los israelitas: «¿Quién de entre todas las tribus de Israel no acudió a la asamblea ante Yahveh?» Porque se había jurado solemnemente que el que no subiera a Mispá ante Yahveh tenía que morir.

[[judges-21-6]]
^6^ Los israelitas estaban apenados por su hermano Benjamín y decían: «Hoy ha sido arrancada una tribu de Israel.

[[judges-21-7]]
^7^ ¿Qué haremos para proporcionar mujeres a los que quedan? Pues nosotros hemos jurado por Yahveh no darles nuestras hijas en matrimonio».

[[judges-21-8]]
^8^ Entonces se dijeron: «¿Cuál es la única tribu de Israel que no subió ante Yahveh a Mispá?» Y vieron que nadie de Yabés de Galaad había ido al campamento, a la asamblea.

[[judges-21-9]]
^9^ Hicieron el censo del pueblo y no había ninguno de los habitantes de Yabés de Galaad.

[[judges-21-10]]
^10^ Entonces la comunidad mandó allá 12.000 hombres de los valientes y les dio esta orden: «Id y pasad a cuchillo a los habitantes de Yabés de Galaad, incluidos las mujeres y los niños.

[[judges-21-11]]
^11^ Esto es lo que habéis de hacer: Consagraréis al anatema a todo varón y a toda mujer que haya conocido varón, pero dejaréis con vida a las doncellas». Así lo hicieron.

[[judges-21-12]]
^12^ Entre los habitantes de Yabés de Galaad encontraron cuatrocientas muchachas vírgenes que no habían conocido varón y las llevaron al campamento (de Silo, que está en el país de Canaán).

[[judges-21-13]]
^13^ Toda la comunidad mandó emisarios a los benjaminitas que estaban en la Peña de Rimmón para hacer las paces.

[[judges-21-14]]
^14^ Volvió entonces Benjamín. Les dieron las mujeres de Yabés de Galaad que habían quedado con vida, pero no hubo suficientes para todos.

[[judges-21-15]]
^15^ El pueblo se compadeció de Benjamín, pues Yahveh había abierto una brecha entre las tribus de Israel.

[[judges-21-16]]
^16^ Decían los ancianos de la comunidad: «¿Qué podemos hacer para proporcionar mujeres a los que quedan, pues las mujeres de Benjamín han sido exterminadas?»

[[judges-21-17]]
^17^ Y añadían: «¿Cómo conservar un resto a Benjamín para que no sea borrada una tribu de Israel?

[[judges-21-18]]
^18^ Porque nosotros no podemos darles nuestras hijas en matrimonio». Es que los israelitas habían pronunciado este juramento: «Maldito sea el que dé mujer a Benjamín».

[[judges-21-19]]
^19^ Pero se dijeron: «Es ahora la fiesta de Yahveh, la que se celebra todos los años en Silo». (La ciudad está al norte de Betel, al oriente de la calzada que sube de Betel a Siquem y al sur de Leboná.)

[[judges-21-20]]
^20^ Dieron esta orden a los benjaminitas: «Id a poner una emboscada entre las viñas.

[[judges-21-21]]
^21^ Estaréis alerta, y cuando las muchachas de Silo salgan para danzar en corro, saldréis de las viñas y raptaréis cada uno una mujer de entre las muchachas de Silo y os iréis a la tierra de Benjamín.

[[judges-21-22]]
^22^ Si sus padres o sus hermanos vienen a querellarse contra vosotros, les diremos: “Hacednos el favor de perdonarles, pues no hemos podido tomar cada uno una mujer en el combate; porque no sois vosotros los que se las habéis dado, porque entonces seríais culpables».

[[judges-21-23]]
^23^ Así lo hicieron los benjaminitas y se llevaron tantas mujeres cuantos eran ellos de entre las danzarinas que raptaron; luego se fueron, volvieron a su heredad, reedificaron las ciudades y se establecieron en ellas.

[[judges-21-24]]
^24^ Los israelitas se marcharon entonces de allí cada uno a su tribu y a su clan y partieron de allí cada uno a su heredad.

[[judges-21-25]]
^25^ Por aquel tiempo no había rey en Israel y cada uno hacía lo que le parecía bien.
