[[ruth]]
= Rut

[[ruth-1]]
== Capítulo 1

[[ruth-1-1]]
^1^ En los días en que juzgaban los Jueces hubo hambre en el país, y un hombre de Belén de Judá se fue a residir, con su mujer y sus dos hijos, a los campos de Moab.

[[ruth-1-2]]
^2^ Este hombre se llamaba Elimélek, su mujer Noemí y sus dos hijos Majlón y Kilyón; eran efrateos de Belén de Judá. Llegados a los campos de Moab, se establecieron allí.

[[ruth-1-3]]
^3^ Murió Elimélek, el marido de Noemí, y quedó ella con sus dos hijos.

[[ruth-1-4]]
^4^ Estos se casaron con mujeres moabitas, una de las cuales se llamaba Orpá y la otra Rut. Y habitaron allí unos diez años.

[[ruth-1-5]]
^5^ Murieron también ellos dos, Majlón y Kilyón, y quedó sola Noemí, sin sus dos hijos y sin marido.

[[ruth-1-6]]
^6^ Entonces decidió regresar de los campos de Moab con sus dos nueras, porque oyó en los campos de Moab que Yahveh había visitado a su pueblo y le daba pan.

[[ruth-1-7]]
^7^ Salió, pues, con sus nueras, del país donde había vivido y se pusieron en camino, para volver a la tierra de Judá.

[[ruth-1-8]]
^8^ Noemí dijo a sus dos nueras: «Andad, volveos cada una a casa de vuestra madre. Que Yahveh tenga piedad con vosotras como vosotras la habéis tenido con los que murieron y conmigo.

[[ruth-1-9]]
^9^ Que Yahveh os conceda encontrar vida apacible en la casa de un marido». Y las besó. Pero ellas rompieron a llorar,

[[ruth-1-10]]
^10^ y dijeron: «No; contigo volveremos a tu pueblo».

[[ruth-1-11]]
^11^ Noemí respondió: «Volveos, hijas mías, ¿por qué vais a venir conmigo? ¿Acaso tengo yo aún hijos en mi seno que puedan ser maridos vuestros?

[[ruth-1-12]]
^12^ Volveos, hijas mías, andad, porque yo soy demasiado vieja para casarme otra vez. Y aun cuando dijera que no he perdido toda esperanza, que esta misma noche voy a tener un marido y que tendré hijos

[[ruth-1-13]]
^13^ ¿habríais de esperar hasta que fueran mayores? ¿dejaríais por eso de casaros? No, hijas mías, yo tengo gran pena por vosotros, porque la mano de Yahveh ha caído sobre mí».

[[ruth-1-14]]
^14^ Ellas rompieron a llorar de nuevo; después Orpá besó a su suegra y se volvió a su pueblo, pero Rut se quedó junto a ella.

[[ruth-1-15]]
^15^ Entonces Noemí dijo: «Mira, tu cuñada se ha vuelto a su pueblo y a su dios, vuélvete tú también con ella».

[[ruth-1-16]]
^16^ Pero Rut respondió: «No insistas en que te abandone y me separe de ti, porque donde tú vayas, yo iré, donde habites, habitaré. Tu pueblo será mi pueblo y tu Dios será mi Dios.

[[ruth-1-17]]
^17^ Donde tú mueras moriré y allí seré enterrada. Que Yahveh me dé este mal y añada este otro todavía si no es tan sólo la muerte lo que nos ha de separar».

[[ruth-1-18]]
^18^ Viendo Noemí que Rut estaba decidida a acompañarla, no insistió más.

[[ruth-1-19]]
^19^ Caminaron, pues, las dos juntas hasta Belén. Cuando llegaron a Belén se conmovió toda la ciudad por ellas. Las mujeres exclamaban: «¿No es esta Noemí?»

[[ruth-1-20]]
^20^ Mas ella respondía: «¡No me llaméis ya Noemí, llamadme Mará, porque Sadday me ha llenado de amargura!

[[ruth-1-21]]
^21^ Colmada partí yo, vacía me devuelve Yahveh. ¿Por qué me llamáis aún Noemí, cuando Yahveh da testimonio contra mí y Sadday me ha hecho desdichada?»

[[ruth-1-22]]
^22^ Así fue como regresó Noemí, con su nuera Rut la moabita, la que vino de los campos de Moab. Llegaron a Be1len al comienzo de la siega de la cebada.
[[ruth-2]]
== Capítulo 2

[[ruth-2-1]]
^1^ Tenía Noemí por parte de su marido un pariente de buena posición, de la familia de Elimélek, llamado Booz.

[[ruth-2-2]]
^2^ Rut la moabita dijo a Noemí: «Déjame ir al campo a espigar detrás de aquél a cuyos ojos halle gracia»; ella respondió: «Vete, hija mía».

[[ruth-2-3]]
^3^ Fue ella y se puso a espigar en el campo detrás de los segadores, y quiso su suerte que fuera a dar en una parcela de Booz, el de la familia de Elimélek.

[[ruth-2-4]]
^4^ Llegaba entonces Booz de Belén y dijo a los segadores: «Yahveh con vosotros». Le respondieron: «Que Yahveh te bendiga».

[[ruth-2-5]]
^5^ Preguntó Booz al criado que estaba al frente de los segadores: «¿De quién es esta muchacha?»

[[ruth-2-6]]
^6^ El criado que estaba al frente de los segadores dijo: «Es la joven moabita que vino con Noemí de los campos de Moab.

[[ruth-2-7]]
^7^ Ella dijo: “Permitidme, por favor, espigar y recoger detrás de los segadores.” Ha venido y ha permanecido en pie desde la mañana hasta ahora».

[[ruth-2-8]]
^8^ Booz dijo a Rut: «¿Me oyes, hija mía? No vayas a espigar a otro campo ni te alejes de aquí; quédate junto a mis criados.

[[ruth-2-9]]
^9^ Fíjate en la parcela que sieguen y vete detrás de ellos. ¿No he mandado a mis criados que no te molesten? Si tienes sed vete a las vasijas y bebe de lo que saquen del pozo los criados».

[[ruth-2-10]]
^10^ Cayó ella sobre su rostro y se postró en tierra y le dijo: «¿Cómo he hallado gracia a tus ojos para que te fijes en mí, que no soy más que una extranjera?»

[[ruth-2-11]]
^11^ Booz le respondió: «Me han contado al detalle todo lo que hiciste con tu suegra después de la muerte de tu marido, y cómo has dejado a tu padre y a tu madre y la tierra en que naciste, y has venido a un pueblo que no conocías ni ayer ni anteayer.

[[ruth-2-12]]
^12^ Que Yahveh te recompense tu obra y que tu recompensa sea colmada de parte de Yahveh, Dios de Israel, bajo cuyas alas has venido a refugiarte».

[[ruth-2-13]]
^13^ Ella dijo: «Halle yo gracia a tus ojos, mi señor, pues me has consolado y has hablado al corazón de tu sierva, cuando yo no soy ni siquiera como una de tus siervas».

[[ruth-2-14]]
^14^ A la hora de la comida, Booz le dijo: «Acércate aquí, puedes comer pan y mojar tu bocado en el vinagre». Ella se sentó junto a los segadores, y él le ofreció un puñado de grano tostado. Comió ella hasta saciarse y aun le sobró.

[[ruth-2-15]]
^15^ Cuando se levantó ella para seguir espigando, Booz ordenó a sus criados: «Dejadla espigar también entre las gavillas y no la molestéis.

[[ruth-2-16]]
^16^ Sacad incluso para ella espigas de las gavillas y dejadlas caer para que las espigue, y no la riñáis».

[[ruth-2-17]]
^17^ Estuvo espigando en el campo hasta el atardecer y, cuando desgranó lo que había espigado, había como una medida de cebada.

[[ruth-2-18]]
^18^ Ella se lo llevó y entró en la ciudad, y su suegra vio lo que había espigado. Sacó lo que le había sobrado después de haberse saciado y se lo dio.

[[ruth-2-19]]
^19^ Su suegra le dijo: «¿Dónde has estado espigando hoy y qué has hecho? ¡Bendito sea el que se ha fijado en ti!» Ella contó a su suegra con quién había estado trabajando y añadió: «El hombre con quien he trabajado hoy se llama Booz».

[[ruth-2-20]]
^20^ Noemí dijo a su nuera: «Bendito sea Yahveh que no deja de mostrar su bondad hacia los vivos y los muertos». Le dijo Noemí: «Ese hombre es nuestro pariente, es uno de los que tienen derecho de rescate sobre nosotros».

[[ruth-2-21]]
^21^ Dijo Rut a su suegra: «Hasta me ha dicho: Quédate con mis criados hasta que hayan acabado toda mi cosecha».

[[ruth-2-22]]
^22^ Dijo Noemí a Rut su nuera: «Es mejor que salgas con sus criados, hija mía, así no te molestarán en otro campo».

[[ruth-2-23]]
^23^ Se quedó, pues, con los criados de Booz para espigar hasta que acabó la recolección de la cebada y la recolección del trigo, y siguió viviendo con su suegra.
[[ruth-3]]
== Capítulo 3

[[ruth-3-1]]
^1^ Noemí, su suegra, le dijo: «Hija mia, ¿es que no debo procurarte una posición segura que te convenga?

[[ruth-3-2]]
^2^ Ahora bien: ¿Acaso no es pariente nuestro aquel Booz con cuyos criados estuviste? Pues mira: Esta noche estará aventando la cebada en la era.

[[ruth-3-3]]
^3^ Lávate, perfúmate y ponte encima el manto, y baja a la era; que no te reconozca ese hombre antes que acabe de comer y beber.

[[ruth-3-4]]
^4^ Cuando se acueste, mira el lugar en que se haya acostado, vas, descubres un sitio a sus pies y te acuestas; y él mismo te indicará lo que debes hacer».

[[ruth-3-5]]
^5^ Ella le dijo: «Haré cuanto me has dicho».

[[ruth-3-6]]
^6^ Bajó a la era e hizo cuanto su suegra le había mandado.

[[ruth-3-7]]
^7^ Booz comió y bebió y su corazón se puso alegre. Entonces fue a acostarse junto al montón de cebada. Vino ella sigilosamente, descubrió un sitio a sus pies y se acostó.

[[ruth-3-8]]
^8^ A media noche sintió el hombre un escalofrío, se volvió y notó que había una mujer acostada a sus pies.

[[ruth-3-9]]
^9^ Dijo: «¿Quien eres tú?», y ella respondió: «Soy Rut tu sierva. Extiende sobre tu sierva el borde de tu manto, porque tienes derecho de rescate».

[[ruth-3-10]]
^10^ El dijo: «Bendita seas de Yahveh, hija mía; tu último acto de piedad filial ha sido mejor que el primero, porque no has pretendido a ningún joven, pobre o rico.

[[ruth-3-11]]
^11^ Y ahora, hija mía, no temas; haré por ti cuanto me digas, porque toda la gente de mi pueblo sabe que tú eres una mujer virtuosa.

[[ruth-3-12]]
^12^ Ahora bien: es verdad que tengo derecho de rescate, pero hay un pariente más cercano que yo con derecho de rescate.

[[ruth-3-13]]
^13^ Pasa aquí esta noche, y mañana, si él quiere ejercer su derecho, que lo ejerza; y si no quiere, yo te rescataré, ¡vive Yahveh! Acuéstate hasta el amanecer».

[[ruth-3-14]]
^14^ Se acostó ella a sus pies hasta la madrugada; se levantó él a la hora en que todavía un hombre no puede reconocer a otro, pues se decía: «Que no se sepa que la mujer ha venido a la era».

[[ruth-3-15]]
^15^ El dijo: «Trae el manto que tienes encima y sujeta bien». Sujetó ella, y él midió seis medidas de cebada y se las puso a cuestas, y él entró en la ciudad.

[[ruth-3-16]]
^16^ Volvió ella donde su suegra que le dijo: «¿Cómo te ha ido, hija mía?» Y le contó cuanto el hombre había hecho por ella,

[[ruth-3-17]]
^17^ y añadió: «Me ha dado estas seis medidas de cebada, pues dijo: “No debes volver de vacío donde tu suegra.”»

[[ruth-3-18]]
^18^ Noemí le dijo: «Quédate tranquila, hija mía, hasta que sepas cómo acaba el asunto; este hombre no parará hasta concluirlo hoy mismo».
[[ruth-4]]
== Capítulo 4

[[ruth-4-1]]
^1^ Mientras tanto Booz subió a la puerta de la ciudad y se sentó allí. Acertó a pasar el pariente de que había hablado Booz, y le dijo: «Acércate y siéntate aquí, fulano». Y éste fue y se sentó.

[[ruth-4-2]]
^2^ Tomó diez de los ancianos de la ciudad y dijo: «Sentaos aquí». Y se sentaron.

[[ruth-4-3]]
^3^ Dijo entonces al que tenía el derecho de rescate: «Noemí, que ha vuelto de los campos de Moab, vende la parcela de campo de nuestro hermano Elimélek.

[[ruth-4-4]]
^4^ He querido hacértelo saber y decirte: «Adquiérela en presencia de los aquí sentados, en presencia de los ancianos de mi pueblo. Si vas a rescatar, rescata; si nos vas a rescatar, dímelo para que yo lo sepa, porque fuera de ti no hay otro que tenga derecho de rescate, pues voy yo después de ti». El dijo: «Yo rescataré».

[[ruth-4-5]]
^5^ Booz añadió: «El día que adquieras la parcela para ti de manos de Noemí tienes que adquirir también a Rut la moabita, mujer del difunto, para perpetuar el nombre del difunto en su heredad».

[[ruth-4-6]]
^6^ El pariente respondió: «Así no puedo rescatar, porque podría perjudicar mi herencia. Usa tú mi derecho de rescate, porque yo no puedo usarlo».

[[ruth-4-7]]
^7^ Antes en Israel, en caso de rescate o de cambio, para dar fuerza al contrato, había la costumbre de quitarse uno la sandalia y dársela al otro. Esta era la manera de testificar en Israel.

[[ruth-4-8]]
^8^ El que tenía el derecho de rescate dijo a Booz: «Adquiérela para ti». Y se quitó la sandalia.

[[ruth-4-9]]
^9^ Entonces dijo Booz a los ancianos y a todo el pueblo: «Testigos sois vosotros hoy de que adquiero todo lo de Elimélek y todo lo de Kilyón y Majlón de manos de Noemí

[[ruth-4-10]]
^10^ y de que adquiero también a Rut la moabita, la que fue mujer de Kilyón, para que sea mi mujer a fin de perpetuar el nombre del difunto en su heredad y que el nombre del difunto no sea borrado entre sus hermanos y en la puerta de su localidad. Vosotros sois hoy testigos».

[[ruth-4-11]]
^11^ Toda la gente que estaba en la puerta y los ancianos repondieron: «Somos testigos. Haga Yahveh que la mujer que entra en tu casa sea como Raquel y como Lía, las dos que edificaron la casa de Israel. Hazte poderoso en Efratá y sé famoso en Belén.

[[ruth-4-12]]
^12^ Sea tu casa como la casa de Peres, el que Tamar dio a Judá, gracias a la descendencia que Yahveh te conceda por esta joven».

[[ruth-4-13]]
^13^ Booz tomó a Rut, y ella fue su mujer; se unió a ella, y Yahveh hizo que concibiera, y dio a luz un niño.

[[ruth-4-14]]
^14^ Las mujeres dijeron a Noemí: «Bendito sea Yahveh que no ha permitido que te falte hoy uno que te rescate para perpetuar su nombre en Israel.

[[ruth-4-15]]
^15^ Será el consuelo de tu alma y el apoyo de tu ancianidad, porque lo ha dado a luz tu nuera que te quiere y es para ti mejor que siete hijos».

[[ruth-4-16]]
^16^ Tomó Noemí al niño y le puso en su seno y se encargó de criarlo.

[[ruth-4-17]]
^17^ Las vecinas le pusieron un nombre diciendo: «Le ha nacido un hijo a Noemí» y le llamaron Obed. Es el padre de Jesé, padre de David.

[[ruth-4-18]]
^18^ Estos son los descendientes de Peres. Peres engendró a Jesrón.

[[ruth-4-19]]
^19^ Jesrón engendró a Ram y Ram engendró a Aminadab.

[[ruth-4-20]]
^20^ Aminadab engendró a Najsón y Najsón engendró a Salmón.

[[ruth-4-21]]
^21^ Salmón engendró a Booz y Booz engendró a Obed.

[[ruth-4-22]]
^22^ Obed engendró a Jesé y Jesé engendró a David.
