[[first-samuel]]
= Primer libro de Samuel

[[first-samuel-1]]
== Capítulo 1

[[first-samuel-1-1]]
^1^ Hubo un hombre de Ramatáyim, sufita de la montaña de Efraím, que se llamaba Elcaná, hijo de Yeroján, hijo de Elihú, hijo de Toju, hijo de Suf, efraimita.

[[first-samuel-1-2]]
^2^ Tenía dos mujeres: una se llamaba Ana y la otra Peninná; Peninná tenía hijos, pero Ana no los tenía.

[[first-samuel-1-3]]
^3^ Este hombre subía de año en año desde su ciudad para adorar y ofrecer sacrificios a Yahveh Sebaot en Silo, donde estaban Jofní y Pinjás, los dos hijos de Elí, sacerdotes de Yahveh.

[[first-samuel-1-4]]
^4^ El día en que Elcaná sacrificaba, daba sendas porciones a su mujer Peninná y a cada uno de sus hijos e hijas,

[[first-samuel-1-5]]
^5^ pero a Ana le daba solamente una porción, pues aunque era su preferida, Yahveh había cerrado su seno.

[[first-samuel-1-6]]
^6^ Su rival la zahería y vejaba de continuo, porque Yahveh la había hecho estéril.

[[first-samuel-1-7]]
^7^ Así sucedía año tras año; cuando subían al templo de Yahveh la mortificaba. Ana lloraba de continuo y no quería comer.

[[first-samuel-1-8]]
^8^ Elcaná su marido le decía: «Ana, ¿por qué lloras y no comes? ¿Por qué estás triste? ¿Es que no soy para ti mejor que diez hijos?»

[[first-samuel-1-9]]
^9^ Pero después que hubieron comido en la habitación, se levantó Ana y se puso ante Yahveh. - El sacerdote Elí estaba sentado en su silla, contra la jamba de la puerta del santuario de Yahveh.

[[first-samuel-1-10]]
^10^ Estaba ella llena de amargura y oró a Yahveh llorando sin consuelo,

[[first-samuel-1-11]]
^11^ e hizo este voto: «¡Oh Yahveh Sebaot! Si te dignas mirar la aflicción de tu sierva y acordarte de mí, no olvidarte de tu sierva y darle un hijo varón, yo lo entregaré a Yahveh por todos los días de su vida y la navaja no tocará su cabeza».

[[first-samuel-1-12]]
^12^ Como ella prolongase su oración ante Yahveh, Elí observaba sus labios.

[[first-samuel-1-13]]
^13^ Ana oraba para sí; se movían sus labios, pero no se oía su voz, y Elí creyó que estaba ebria,

[[first-samuel-1-14]]
^14^ y le dijo: «¿Hasta cuándo va a durar tu embriaguez? ¡Echa el vino que llevas!»

[[first-samuel-1-15]]
^15^ Pero Ana le respondió: «No, señor; soy una mujer acongojada; no he bebido vino ni cosa embriagante, sino que desahogo mi alma ante Yahveh.

[[first-samuel-1-16]]
^16^ No juzgues a tu sierva como una mala mujer; hasta ahora sólo por pena y pesadumbre he hablado».

[[first-samuel-1-17]]
^17^ Elí le respondió: «Vete en paz y que el Dios de Israel te conceda lo que le has pedido».

[[first-samuel-1-18]]
^18^ Ella dijo: «Que tu sierva halle gracia a tus ojos». Se fue la mujer por su camino, comió y no pareció ya la misma.

[[first-samuel-1-19]]
^19^ Se levantaron de mañana y, después de haberse postrado ante Yahveh, regresaron, volviendo a su casa, en Ramá. Elcaná se unió a su mujer Ana y Yahveh se acordó de ella.

[[first-samuel-1-20]]
^20^ Concibió Ana y llegado el tiempo dio a luz un niño a quien llamó Samuel, «porque, dijo, se lo he pedido a Yahveh».

[[first-samuel-1-21]]
^21^ Subió el marido Elcaná con toda su familia, para ofrecer a Yahveh el sacrificio anual y cumplir su voto,

[[first-samuel-1-22]]
^22^ pero Ana no subió, porque dijo a su marido: «Cuando el niño haya sido destetado, entonces le llevaré, será presentado a Yahveh y se quedará allí para siempre».

[[first-samuel-1-23]]
^23^ Elcaná, su marido, le respondió: «Haz lo que mejor te parezca, y quédate hasta que lo destetes; así Yahveh cumpla su palabra». Se quedó, pues, la mujer y amamantó a su hijo hasta su destete.

[[first-samuel-1-24]]
^24^ Cuando lo hubo destetado, lo subió consigo, llevando además un novillo de tres años, una medida de harina y un odre de vino, e hizo entrar en la casa de Yahveh, en Silo, al niño todavía muy pequeño.

[[first-samuel-1-25]]
^25^ Inmolaron el novillo y llevaron el niño a Elí

[[first-samuel-1-26]]
^26^ y ella dijo: «Oyeme, señor. Por tu vida, señor, yo soy la mujer que estuvo aquí junto a ti, orando a Yahveh.

[[first-samuel-1-27]]
^27^ Este niño pedía yo y Yahveh me ha concedido la petición que le hice.

[[first-samuel-1-28]]
^28^ Ahora yo se lo cedo a Yahveh por todos los días de su vida; está cedido a Yahveh». Y le dejó allí, a Yahveh.
[[first-samuel-2]]
== Capítulo 2

[[first-samuel-2-1]]
^1^ Entonces Ana dijo esta oración: «Mi corazón exulta en Yahveh, mi cuerno se levanta en Dios, mi boca se dilata contra mis enemigos, porque me he gozado en tu socorro.

[[first-samuel-2-2]]
^2^ No hay Santo como Yahveh, (porque nadie fuera de ti), ni roca como nuestro Dios.

[[first-samuel-2-3]]
^3^ No multipliquéis palabras altaneras. No salga de vuestra boca la arrogancia. Dios de sabiduría es Yahveh, suyo es juzgar las acciones.

[[first-samuel-2-4]]
^4^ El arco de los fuertes se ha quebrado, los que tambalean se ciñen de fuerza.

[[first-samuel-2-5]]
^5^ Los hartos se contratan por pan, los hambrientos dejan su trabajo. La estéril da a luz siete veces, la de muchos hijos se marchita.

[[first-samuel-2-6]]
^6^ Yahveh da muerte y vida, hace bajar al seol y retornar.

[[first-samuel-2-7]]
^7^ Yahveh enriquece y despoja, abate y ensalza.

[[first-samuel-2-8]]
^8^ Levanta del polvo al humilde, alza del muladar al indigente para hacerle sentar junto a los nobles, y darle en heredad trono de gloria, pues de Yahveh los pilares de la tierra y sobre ellos ha sentado el universo.

[[first-samuel-2-9]]
^9^ Guarda los pasos de sus fieles, y los malos perecen en tinieblas, (pues que no por la fuerza triunfa el hombre).

[[first-samuel-2-10]]
^10^ Yahveh, ¡quebrantados sus rivales! el Altísimo truena desde el cielo. Yahveh juzga los confines de la tierra, da pujanza a su Rey, exalta el cuerno de su Ungido».

[[first-samuel-2-11]]
^11^ Partió Elcaná para Ramá, y el niño se quedó para servir a Yahveh a las órdenes del sacerdote Elí.

[[first-samuel-2-12]]
^12^ Los hijos de Elí eran unos malvados que no conocían a Yahveh

[[first-samuel-2-13]]
^13^ ni las normas de los sacerdotes respecto del pueblo: cuando alguien ofrecía un sacrificio, venía el criado del sacerdote, mientras se estaba cociendo la carne, con el tenedor de tres dientes en la mano,

[[first-samuel-2-14]]
^14^ lo hincaba en el caldero o la olla, en la cacerola o el puchero, y todo lo que sacaba el tenedor, el sacerdote se lo quebada; y así hacían con todos los israelitas que iban allí, a Silo.

[[first-samuel-2-15]]
^15^ Incluso antes de que quemasen la grasa, venía el criado del sacerdote y decía al que sacrificaba: «Dame carne para asársela al sacerdote, no te aceptará carne hervida, sino solamente carne cruda».

[[first-samuel-2-16]]
^16^ Y si el hombre le decías: «Primero se quema la grasa, y después tomarás cuanto se te antoje», le respondía: «No, me lo darás ahora o lo tomo por la fuerza».

[[first-samuel-2-17]]
^17^ El pecado de los jóvenes era muy grande ante Yahveh, porque trataban con desprecio la ofrenda hecha a Yahveh.

[[first-samuel-2-18]]
^18^ Estaba Samuel al servicio de Yahveh, muchacho vestido con efod de lino.

[[first-samuel-2-19]]
^19^ Le hacía su madre un vestido pequeño que le llevaba de año en año, cuando subía con su marido para ofrecer el sacrificio anual.

[[first-samuel-2-20]]
^20^ Bendecía luego Elí a Elcaná y a su mujer diciendo: «Que Yahveh te conceda descendencia de esta mujer, a cambio del préstamo que ella ha cedido a Yahveh». Y ellos se volvían a su lugar.

[[first-samuel-2-21]]
^21^ En efecto, Yahveh visitó a Ana, que concibió y dio a luz tres hijos y dos hijas; el niño Samuel crecía ante Yahveh.

[[first-samuel-2-22]]
^22^ Elí era muy anciano; oyó todo cuanto sus hijos hacían a todo Israel,

[[first-samuel-2-23]]
^23^ y les dijo: «¿Por qué os portáis de ese modo que yo mismo he oído comentar a todo el pueblo?

[[first-samuel-2-24]]
^24^ No, hijos míos, los rumores que oigo no son buenos...

[[first-samuel-2-25]]
^25^ Si un hombre peca contra otro hombre, Dios será el árbitro; pero si el hombre peca contra Yahveh ¿quién intercederá por él?» Pero ellos no escucharon la voz de su padre, porque Yahveh deseaba hacerles morir.

[[first-samuel-2-26]]
^26^ Cuanto al niño Samuel, iba creciendo y haciéndose grato tanto a Yahveh como a los hombres.

[[first-samuel-2-27]]
^27^ Vino un hombre de Dios a Elí y le dijo: Así ha dicho Yahveh. Claramente me he revelado a la casa de tu padre, cuando ellos estaban en Egipto al servicio de la casa de Faraón.

[[first-samuel-2-28]]
^28^ Y le elegí entre todas las tribus de Israel para ser mi sacerdote, para subir a mi altar, incensar la ofrenda y llevar el efod en mi presencia, y he concedido a la casa de tu padre parte en todos los sacrificios por el fuego de los hijos de Israel.

[[first-samuel-2-29]]
^29^ ¿Por qué pisoteáis el sacrificio y la oblación que yo he ordenado y pesan tus hijos más que yo, cebándoos con lo mejor de todas las oblaciones de mi pueblo Israel?

[[first-samuel-2-30]]
^30^ Por eso - palabra de Yahveh, Dios de Israel - yo había dicho que tu casa y la casa de tu padre andarían siempre en mi presencia, pero ahora - palabra de Yahveh - me guardaré bien de ello. Porque a los que me honran, yo les honro, pero los que me desprecian son viles.

[[first-samuel-2-31]]
^31^ He aquí que vienen días en que amputarán tu brazo y el brazo de la casa de tu padre, de suerte que en tu casa los hombres no lleguen a madurar.

[[first-samuel-2-32]]
^32^ Tú mirarás al lado de la Morada todo el bien que yo haga a Israel y nunca habrá hombres maduros en tu casa.

[[first-samuel-2-33]]
^33^ Conservaré a alguno de los tuyos cabe mi altar para que sus ojos se consuman y su alma se marchite, pero la mayor parte de los tuyos perecerá por la espada de los hombres.

[[first-samuel-2-34]]
^34^ Será para ti señal lo que va a suceder a tus dos hijos Jofní y Pinjás: en el mismo día morirán los dos.

[[first-samuel-2-35]]
^35^ Yo me suscitaré un sacerdote fiel, que obre según mi corazón y mis deseos, le edificaré una casa permanente y caminará siempre en presencia de mi ungido.

[[first-samuel-2-36]]
^36^ El que quedare de tu casa vendrá a postrarse ante él para conseguir algún dinero o una torta de pan y dirá: “Destíname, por favor, a una función sacerdotal cualquiera, para que tenga un bocado de pan que comer.”»
[[first-samuel-3]]
== Capítulo 3

[[first-samuel-3-1]]
^1^ Servía el niño Samuel a Yahveh a las órdenes de Elí; en aquel tiempo era rara la palabra de Yahveh, y no eran corrientes las visiones.

[[first-samuel-3-2]]
^2^ Cierto día, estaba Elí acostado en su habitación - sus ojos iban debilitándose y ya no podía ver -

[[first-samuel-3-3]]
^3^ no estaba aún apagada la lámpara de Dios, y Samuel estaba acostado en el Santuario de Yahveh, donde se encontraba el arca de Dios.

[[first-samuel-3-4]]
^4^ Llamó Yahveh: «¡Samuel, Samuel!» El respondió: «¡Aquí estoy!»,

[[first-samuel-3-5]]
^5^ y corrió donde Elí diciendo: «¡Aquí estoy, porque me has llamado». Pero Elí le contestó: «Yo no te he llamado; vuélvete a acostar». El se fue y se acostó.

[[first-samuel-3-6]]
^6^ Volvió a llamar Yahveh: «¡Samuel!» Se levantó Samuel y se fue donde Elí diciendo: «Aquí estoy, porque me has llamado». Elí le respondió: «Yo no te he llamado, hijo mío, vuélvete a acostar».

[[first-samuel-3-7]]
^7^ Aún no conocía Samuel a Yahveh, pues no le había sido revelada la palabra de Yahveh.

[[first-samuel-3-8]]
^8^ Tercera vez llamó Yahveh a Samuel y él se levantó y se fue donde Elí diciendo: «Aquí estoy, porque me has llamado». Comprendió entonces Elí que era Yahveh quien llamaba al niño,

[[first-samuel-3-9]]
^9^ y dijo a Samuel: «Vete y acuéstate, y si te llaman, dirás: Habla, Yahveh, que tu siervo escucha». Samuel se fue y se acostó en su sitio.

[[first-samuel-3-10]]
^10^ Vino Yahveh, se paró y llamó como las veces anteriores «Samuel, Samuel!» Respondió Samuel: «¡Habla, que tu siervo escucha».

[[first-samuel-3-11]]
^11^ Dijo Yahveh a Samuel: «Voy a ejecutar una cosa tal en Israel, que a todo el que la oiga le zumbarán los oídos.

[[first-samuel-3-12]]
^12^ Ese día cumpliré contra Elí todo cuanto he dicho contra su casa, desde el principio hasta el fin.

[[first-samuel-3-13]]
^13^ Tú le anunciarás que yo condeno su casa para siempre, porque sabía que sus hijos vilipendiaban a Dios y no los ha corregido.

[[first-samuel-3-14]]
^14^ Por esto juro a la casa de Elí que ni sacrificio ni oblación expiarán jamás la iniquidad de la casa de Elí».

[[first-samuel-3-15]]
^15^ Samuel siguió acostado hasta la mañana y después abrió las puertas de la Casa de Yahveh. Samuel temía contar la visión a Elí,

[[first-samuel-3-16]]
^16^ pero Elí le llamó y le dijo: «Samuel, hijo mío»; él respondió: «Aquí estoy».

[[first-samuel-3-17]]
^17^ El preguntó: «¿Qué es lo que te ha dicho? ¡No me ocultes nada! Que Dios te haga esto y añada esto otro si me ocultas una palabra de lo que te ha dicho».

[[first-samuel-3-18]]
^18^ Entonces Samuel se lo manifestó todo, sin ocultarle nada; Elí dijo: «El es Yahveh. Que haga lo que bien le parezca».

[[first-samuel-3-19]]
^19^ Samuel crecía, Yahveh estaba con él y no dejó caer en tierra ninguna de sus palabras.

[[first-samuel-3-20]]
^20^ Todo Israel, desde Dan hasta Berseba, supo que Samuel estaba acreditado como profeta de Yahveh.

[[first-samuel-3-21]]
^21^ Yahveh continuó manifestándose en Silo, porque en Silo se revelaba a Samuel la palabra de Yahveh.
[[first-samuel-4]]
== Capítulo 4

[[first-samuel-4-1]]
^1^ Y la palabra de Samuel llegaba a todo Israel. Elí era muy anciano, mientras que sus hijos persistían en su malvada conducta respecto de Yahveh. Ocurrió en aquel tiempo que los filisteos se reunieron para combatir a Israel, y los israelitas salieron a su encuentro para el combate. Acamparon cerca de Eben Haézer, mientras que los filisteos habían acampado en Afeq.

[[first-samuel-4-2]]
^2^ Se pusieron los filisteos en orden de batalla contra Israel; se libró un gran combate y fue batido Israel por los filisteos, muriendo en las filas, en campo abierto, cerca de 4.000 hombres.

[[first-samuel-4-3]]
^3^ Volvió el ejército al campamento, y los ancianos de Israel dijeron: «¿Por qué nos ha derrotado hoy Yahveh delante de los filisteos? Vamos a buscar en Silo el arca de nuestro Dios; que venga en medio de nosotros y que nos salve del poder de nuestros enemigos».

[[first-samuel-4-4]]
^4^ El pueblo envió a Silo y sacaron de allí el arca de Yahveh Sebaot que está sobre los querubines; acompañaron al arca Jofní y Pinjás, los dos hijos de Elí.

[[first-samuel-4-5]]
^5^ Cuando el arca de Yahveh llegó al campamento, todos los israelitas lanzaron un gran clamor que hizo retumbar las tierras.

[[first-samuel-4-6]]
^6^ Los filisteos oyeron el estruendo del clamoreo y dijeron: «¿Qué significa este gran clamor en el campamento de los hebreos?» Y se enteraron de que el arca de Yahveh había llegado al campamento.

[[first-samuel-4-7]]
^7^ Temieron entonces los filisteos, porque se decían: «Dios ha venido al campamento». Y exclamaron: «¡Ay de nosotros! Nunca había sucedido tal cosa.

[[first-samuel-4-8]]
^8^ ¡Ay de nosotros! ¿Quién nos librará de la mano de estos dioses poderosos? ¡Estos son los dioses que castigaron a Egipto con toda clase de plagas en el desierto!

[[first-samuel-4-9]]
^9^ ¡Cobrad ánimo y sed hombres, filisteos, para no tener que servir a los hebreos como ellos os han servido a vosotros; sed hombres y pelead!»

[[first-samuel-4-10]]
^10^ Trabaron batalla los filisteos. Israel fue batido y cada cual huyó a sus tiendas; la mortandad fue muy grande, cayendo de Israel 30.000 infantes.

[[first-samuel-4-11]]
^11^ El arca de Dios fue capturada y murieron Jofní y Pinjás, los dos hijos de Elí.

[[first-samuel-4-12]]
^12^ Un hombre de Benjamín salió corriendo del campo de batalla y llegó a Silo aquel mismo día, con los vestidos rotos y la cabeza cubierta de polvo.

[[first-samuel-4-13]]
^13^ Cuando llegó, estaba Elí en su asiento, a la puerta, atento al camino, porque su corazón temblaba por el arca de Dios. Vino, pues, este hombre a traer la noticia a la ciudad, y toda la ciudad comenzó a gritar.

[[first-samuel-4-14]]
^14^ Oyó Elí los gritos y preguntó: «¿Qué tumulto es éste?» Diose prisa el hombre y se lo anunció a Elí.

[[first-samuel-4-15]]
^15^ Contaba éste 98 años, tenía las pupilas inmóviles y no podía ver.

[[first-samuel-4-16]]
^16^ El hombre dijo a Elí: «Vengo del campo de batalla, he huido hoy del campo». Elí preguntó: ¿Qué ha pasado, hijo mío?»

[[first-samuel-4-17]]
^17^ El mensajero respondió: «Israel ha huido ante los filisteos. Además el ejército ha sufrido una gran derrota, también han muerto tus dos hijos y hasta el arca de Dios ha sido capturada».

[[first-samuel-4-18]]
^18^ A la mención del arca de Dios, cayó Elí de su asiento, hacia atrás, en medio de la puerta, se rompió la nuca y murió, pues era anciano y estaba ya torpe. Había sido juez en Israel durante cuarenta años.

[[first-samuel-4-19]]
^19^ Su nuera, la mujer de Pinjás, estaba encinta y para dar a luz. Cuando oyó la noticia de que el arca de Dios había sido capturada y la muerte de su suegro y su marido, se encogió y dio a luz, pues la habían acometido sus dolores.

[[first-samuel-4-20]]
^20^ Estando a la muerte, las que la asistían le dijeron: «Animo, que es un niño lo que has dado a luz», pero ella no respondió ni prestó atención.

[[first-samuel-4-21]]
^21^ Llamó al niño Ikabod, diciendo: «La gloria ha sido desterrada de Israel», aludiendo a la captura del arca de Dios, a su suegro y a su marido.

[[first-samuel-4-22]]
^22^ Y dijo: «La gloria ha sido desterrada de Israel, porque el arca de Dios ha sido capturada».
[[first-samuel-5]]
== Capítulo 5

[[first-samuel-5-1]]
^1^ Los filisteos, por su parte, tomaron el arca de Dios y la llevaron de Eben Haézer a Asdod.

[[first-samuel-5-2]]
^2^ Tomaron los filisteos el arca de Dios, la introdujeron en el templo de Dagón y la colocaron al lado de Dagón.

[[first-samuel-5-3]]
^3^ A la mañana siguiente vinieron los asdodeos al templo de Dagón y he aquí que Dagón estaba caído de bruces en tierra, delante del arca de Yahveh. Levantaron a Dagón y le volvieron a su sitio.

[[first-samuel-5-4]]
^4^ Pero a la mañana siguiente temprano, Dagón estaba caído de bruces en tierra, delante del arca de Yahveh y la cabeza de Dagón y sus dos manos estaban rotas en el umbral; sólo quedaba el tronco de Dagón.

[[first-samuel-5-5]]
^5^ Por eso los sacerdotes de Dagón y todos los que entran en el templo de Dagón no pisan el umbral de Dagón en Asdod hasta el día de hoy.

[[first-samuel-5-6]]
^6^ La mano de Yahveh cayó pesadamente sobre los asdodeos hiriéndolos con tumores, a Asdod y su comarca.

[[first-samuel-5-7]]
^7^ Cuando los vecinos de Asdod vieron lo que sucedía, dijeron: «Que no se quede entre nosotros el arca del Dios de Israel, porque su mano se ha endurecido contra nosotros y contra nuestro dios Dagón».

[[first-samuel-5-8]]
^8^ Hicieron, pues, convocar junto a ellos a todos los tiranos de los filisteos y dijeron: «¿Qué debemos hacer con el arca del Dios de Israel?» Decidieron: «El arca del Dios de Israel se trasladará a Gat». Y trasladaron allí el arca del Dios de Israel.

[[first-samuel-5-9]]
^9^ Pero así que la trasladaron, la mano de Yahveh cayó sobre la ciudad provocando gran terror; los varones de la ciudad, desde el más pequeño hasta el mayor, fueron castigados, saliéndoles tumores.

[[first-samuel-5-10]]
^10^ Enviaron entonces el arca de Dios a Ecrón, exclamaron los ecronitas: Han encaminado hacia mí el arca del Dios de Israel para hacerme perecer con mi pueblo».

[[first-samuel-5-11]]
^11^ Hicieron convocar a todos los tiranos de los filisteos y dijeron: «Devolved el arca del Dios de Israel; que vuelva a su sitio y no me haga morir a mí y a mi pueblo». Pues había un terror mortal en toda la ciudad, porque descargó allí duramente la mano de Dios.

[[first-samuel-5-12]]
^12^ Los que no murieron fueron atacados de tumores y los alaridos de angustia de la ciudad subieron hasta el cielo.
[[first-samuel-6]]
== Capítulo 6

[[first-samuel-6-1]]
^1^ Siete meses estuvo el arca de Yahveh en territorio filisteo.

[[first-samuel-6-2]]
^2^ Llamaron los filisteos a los sacerdotes y adivinos y preguntaron: «¿Qué debemos hacer con el arca de Yahveh? Hacednos saber cómo la hemos de enviar a su sitio».

[[first-samuel-6-3]]
^3^ Ellos respondieron: «Si queréis devolver el arca del Dios de Israel, no la devolváis de vacío, ofrecedle una reparación y entonces sanaréis y sabréis por qué no se ha apartado su mano de vosotros».

[[first-samuel-6-4]]
^4^ Preguntaron ellos: «¿Qué reparación hemos de ofrecer?» Y respondieron: «Conforme al número de los tiranos de los filisteos, cinco tumores de oro y cinco ratas de oro, porque el mismo castigo sufrís vosotros que vuestros tiranos.

[[first-samuel-6-5]]
^5^ Haced imágenes de vuestros tumores y de vuestras ratas que devastan el país y dad gloria al Dios de Israel. Acaso aligere su mano de sobre vosotros, vuestros dioses y vuestra tierra.

[[first-samuel-6-6]]
^6^ ¿Por qué habéis de endurecer vuestros corazones como endurecieron su corazón los egipcios y Faraón? ¿No los tuvieron que dejar partir después que Dios los hubo maltratado?

[[first-samuel-6-7]]
^7^ Ahora, pues tomad y preparad una carreta nueva y dos vacas que estén criando y que no hayan llevado yugo; unciréis las vacas a la carreta y haréis volver sus becerros al establo.

[[first-samuel-6-8]]
^8^ Tomaréis el arca de Yahveh y la pondréis sobre la carreta. Cuanto a los objetos de oro que le habéis ofrecido como reparación, los meteréis en un cofre a su lado, y la dejaréis marchar.

[[first-samuel-6-9]]
^9^ Y fijaos: si toma el camino de su país, hacia Bet Semes, es él el que nos ha causado esta gran calamidad; si no, sabremos que no ha sido su mano la que nos ha castigado y que todo esto nos ha sucedido por casualidad».

[[first-samuel-6-10]]
^10^ Así lo hicieron aquellos hombres: tomaron dos vacas que estaban criando y las uncieron a la carreta, pero retuvieron las crías en el establo.

[[first-samuel-6-11]]
^11^ Colocaron sobre la carreta el arca de Yahveh y el cofre con las ratas de oro y las imágenes de sus tumores.

[[first-samuel-6-12]]
^12^ Tomaron las vacas en derechura por el camino de Bet Semes y mantuvieron la misma ruta; caminaban mugiendo, sin desviar ni a derecha ni a izquierda. Los tiranos de los filisteos las siguieron hasta los confines de Bet Semes.

[[first-samuel-6-13]]
^13^ Estaban los de Bet Semes segando el trigo en el valle, y alzando la vista vieron el arca y fueron gozosos a su encuentro.

[[first-samuel-6-14]]
^14^ Al llegar la carreta al campo de Josué de Bet Semes, se detuvo; había allí una gran piedra. Astillaron la madera de la carreta y ofrecieron las vacas en holocausto a Yahveh.

[[first-samuel-6-15]]
^15^ Los levitas bajaron el arca de Yahveh y el cofre que estaba a su lado y que contenía los objetos de oro, y lo depositaron todo sobre la gran piedra. Los de Bet Semes ofrecieron aquel día holocaustos e hicieron sacrificios a Yahveh.

[[first-samuel-6-16]]
^16^ Cuando los cinco tiranos filisteos lo vieron, se tornaron a Ecrón el mismo día.

[[first-samuel-6-17]]
^17^ Estos son los tumores de oro que los filisteos ofrecieron en reparación a Yahveh: uno por Asdod, uno por Gaza, uno por Ascalón, uno por Gat, uno por Ecrón.

[[first-samuel-6-18]]
^18^ Y ratas de oro, tantas cuantas son las ciudades de los filisteos, las de los cinco tiranos, desde las ciudades fortificadas hasta las aldeas abiertas. Testigo, la gran piedra sobre la que se colocó el arca de Yahveh y que está en el campo de Josué de Bet Semes, hasta el día de hoy.

[[first-samuel-6-19]]
^19^ De entre los habitantes de Bet Semes, los hijos de Jeconías no se alegraron cuando vieron el arca de Yahveh y castigo Yahveh a setenta de sus hombres. El pueblo hizo duelo porque Yahveh los había castigado duramente.

[[first-samuel-6-20]]
^20^ Dijeron entonces las gentes de Bet Semes: «¿Quién podrá resistir delante de Yahveh, el Dios Santo? ¿A quién subirá, alejándose de nosotros?

[[first-samuel-6-21]]
^21^ Enviaron mensajeros a los habitantes de Quiryat Yearim para decirles: «Los filisteos han devuelto el arca de Yahveh. Bajad y subidla con vosotros».
[[first-samuel-7]]
== Capítulo 7

[[first-samuel-7-1]]
^1^ Vinieron las gentes de Quiryat Yearim y subieron el arca de Yahveh. La llevaron a la casa de Abinadab, en la loma, y consagraron a su hijo Eleazar para que custodiase el arca de Yahveh.

[[first-samuel-7-2]]
^2^ Pasaron muchos días - veinte años - desde el día en que el arca se instaló en Quiryat Yearim, y toda la casa de Israel suspiró por Yahveh.

[[first-samuel-7-3]]
^3^ Entonces Samuel habló así a toda la casa de Israel: «Si os volvéis a Yahveh con todo vuestro corazón, quitad de en medio de vosotros los dioses extranjeros y las Astartés, fijad vuestro corazón en Yahveh y servidle a él solo y entonces él os librará de la mano de los filisteos».

[[first-samuel-7-4]]
^4^ Los israelitas quitaron los Baales y las Astartés y sirvieron sólo a Yahveh.

[[first-samuel-7-5]]
^5^ Samuel dijo: «Congregad a todo Israel en Mispá y yo suplicaré a Yahveh por vosotros».

[[first-samuel-7-6]]
^6^ Se congregaron, pues, en Mispá, sacaron agua, que derramaron ante Yahveh, ayunaron aquel día y dijeron: «Hemos pecado contra Yahveh». Samuel juzgó a los israelitas en Mispá.

[[first-samuel-7-7]]
^7^ Cuando los filisteos supieron que los israelitas se habían reunido en Mispá, subieron los tiranos de los filisteos contra Israel. Habiéndolo oído los israelitas, temieron a los filisteos

[[first-samuel-7-8]]
^8^ y dijeron los israelitas a Samuel: «No dejes de invocar a Yahveh nuestro Dios, para que él nos salve de la mano de los filisteos».

[[first-samuel-7-9]]
^9^ Tomó Samuel un cordero lechal y lo ofreció entero en holocausto a Yahveh, invocó a Yahveh en favor de Israel y Yahveh le escuchó.

[[first-samuel-7-10]]
^10^ Estaba Samuel ofreciendo el holocausto, cuando los filisteos presentaron batalla a Israel, pero tronó Yahveh aquel día con gran estruendo sobre los filisteos, los llenó de terror y fueron batidos ante Israel.

[[first-samuel-7-11]]
^11^ Los hombres de Israel salieron de Mispá y persiguieron a los filisteos desbaratándolos hasta más abajo de Bet Kar.

[[first-samuel-7-12]]
^12^ Tomó entonces Samuel una piedra y la erigió entre Mispá y Yesaná y le dio el nombre de Eben Haézer, diciendo: «Hasta aquí nos ha socorrido Yahveh».

[[first-samuel-7-13]]
^13^ Los filisteos fueron humillados. No volvieron más sobre el territorio de Israel y la mano de Yahveh pesó sobre los filisteos durante toda la vida de Samuel.

[[first-samuel-7-14]]
^14^ Las ciudades que los filisteos habían tomado a los israelitas fueron devueltas a Israel, desde Ecrón hasta Gat, liberando Israel su territorio del dominio de los filisteos. Y hubo paz entre Israel y los amorreos.

[[first-samuel-7-15]]
^15^ Samuel juzgó a Israel todos los días de su vida.

[[first-samuel-7-16]]
^16^ Hacía cada año un recorrido por Betel, Guilgal, Mispá, juzgando a Israel en todos estos lugares.

[[first-samuel-7-17]]
^17^ Después se volvía a Ramá porque allí tenía su casa, y juzgaba a Israel. Y edificó allí un altar a Yahveh.
[[first-samuel-8]]
== Capítulo 8

[[first-samuel-8-1]]
^1^ Cuando Samuel se hizo viejo, puso a sus hijos como jueces en Israel.

[[first-samuel-8-2]]
^2^ Su primogénito se llamaba Joel y el otro, Abías; juzgaban en Israel en Berseba.

[[first-samuel-8-3]]
^3^ Pero sus hijos no siguieron su camino: fueron atraídos por el lucro, aceptaron regalos y torcieron el derecho.

[[first-samuel-8-4]]
^4^ Se reunieron, pues, todos los ancianos de Israel y se fueron donde Samuel a Ramá,

[[first-samuel-8-5]]
^5^ y le dijeron: «Mira, tú te has hecho viejo y tus hijos no siguen tu camino. Pues bien, ponnos un rey para que nos juzgue, como todas las naciones».

[[first-samuel-8-6]]
^6^ Disgustó a Samuel que dijeran: «Danos un rey para que nos juzgue» e invocó a Yahveh. .

[[first-samuel-8-7]]
^7^ Pero Yahveh dijo a Samuel: «Haz caso a todo lo que el pueblo te dice. Porque no te han rechazado a ti, me han rechazado a mí, para que no reine sobre ellos.

[[first-samuel-8-8]]
^8^ Todo lo que ellos me han hecho desde el día que los saqué de Egipto hasta hoy, abandonándome y sirviendo a otros dioses, te han hecho también a ti.

[[first-samuel-8-9]]
^9^ Escucha, sin embargo, su petición. Pero les advertirás claramente y les enseñarás el fuero del rey que va a reinar sobre ellos».

[[first-samuel-8-10]]
^10^ Samuel repitió todas estas palabras de Yahveh al pueblo que le pedía un rey,

[[first-samuel-8-11]]
^11^ diciendo: «He aquí el fuero del rey que va a reinar sobre vosotros. Tomará vuestros hijos y los destinará a sus carros y a sus caballos y tendrán que correr delante de su carro.

[[first-samuel-8-12]]
^12^ Los empleará como jefes de mil y jefes de cincuenta; les hará labrar sus campos, segar su cosecha, fabricar sus armas de guerra y los arreos de sus carros.

[[first-samuel-8-13]]
^13^ Tomara vuestras hijas para perfumistas, cocineras y panaderas.

[[first-samuel-8-14]]
^14^ Tomará vuestros campos, vuestras viñas y vuestros mejores olivares y se los dará a sus servidores.

[[first-samuel-8-15]]
^15^ Tomará el diezmo de vuestros cultivos y vuestras viñas para dárselo a sus eunucos y a sus servidores.

[[first-samuel-8-16]]
^16^ Tomará vuestros criados y criadas, y vuestros mejores bueyes y asnos y les hará trabajar para él.

[[first-samuel-8-17]]
^17^ Sacará el diezmo de vuestros rebaños y vosotros mismos seréis sus esclavos.

[[first-samuel-8-18]]
^18^ Ese día os lamentaréis a causa del rey que os habéis elegido, pero entonces Yahveh no os responderá».

[[first-samuel-8-19]]
^19^ El pueblo no quiso eschuchar a Samuel y dijo: «¡No! Tendremos un rey

[[first-samuel-8-20]]
^20^ y nosotros seremos también como los demás pueblos: nuestro rey nos juzgará, irá al frente de nosotros y combatirá nuestros combates».

[[first-samuel-8-21]]
^21^ Oyó Samuel todas las palabras del pueblo y las repitió a los oídos de Yahveh.

[[first-samuel-8-22]]
^22^ Pero Yahveh dijo a Samuel: «Hazles caso y ponles un rey». Samuel dijo entonces a todos los hombres de Israel: «Volved cada uno a vuestra ciudad».
[[first-samuel-9]]
== Capítulo 9

[[first-samuel-9-1]]
^1^ Había un hombre de Benjamín, llamado Quis, hijo de Abiel, hijo de Seror, hijo de Bekorat, hijo de Afiaj. Era un benjaminita y hombre bien situado.

[[first-samuel-9-2]]
^2^ Tenía un hijo llamado Saúl, joven aventajado y apuesto. Nadie entre los israelitas le superaba en gallardía; de los hombros arriba aventajaba a todos.

[[first-samuel-9-3]]
^3^ Se habían extraviado unas asnas pertenecientes a su padre Quis. Dijo Quis a su hijo Saúl: «Toma contigo uno de los criados y vete a buscar las asnas».

[[first-samuel-9-4]]
^4^ Atravesaron la montaña de Efraím y cruzaron el territorio de Salisá sin encontrar nada; crusaron el país de Saalim, pero no estaban allí, atravesaron el país de Benjamín sin encontrar nada.

[[first-samuel-9-5]]
^5^ Cuando llegaron a la comarca de Suf, dijo Saúl a su criado que le acompañaba: «Vamos a volvernos, no sea que mi padre olvidando las asnas se inquiete por nosotros».

[[first-samuel-9-6]]
^6^ Pero él respondió: «Cabalmente hay en esta ciudad un hombre de Dios. Es hombre acreditado: todo lo que dice se cumple con seguridad. Vamos, pues, allá y acaso nos oriente acerca del viaje que hemos emprendido».

[[first-samuel-9-7]]
^7^ Saúl dijo a su criado: «Vamos a ir, pero ¿qué ofreceremos a ese hombre? No queda pan en nuestros zurrones y no tenemos ningún regalo que llevar al hombre de Dios. ¿Qué le podemos dar?»

[[first-samuel-9-8]]
^8^ Replicó el criado y dijo a Saúl: «Es el caso que tengo en mi poder un cuarto de siclo de plata; se lo daré al hombre de Dios y nos orientará sobre nuestro viaje».

[[first-samuel-9-9]]
^9^ Antes, en Israel, cuando alguien iba a consultar a Dios, decía: «Vayamos al vidente,» porque en vez de «profeta» como hoy, antes se decía «vidente».

[[first-samuel-9-10]]
^10^ Saúl dijo a su criado: «Tienes razón; vamos, pues». Y se fueron a la ciudad donde se encontraba el hombre de Dios.

[[first-samuel-9-11]]
^11^ Cuando subían por la cuesta de la ciudad, encontraron a unas muchachas que salían a sacar agua y les preguntaron: «¿Está aquí el vidente?»

[[first-samuel-9-12]]
^12^ Ellas les respondieron con estas palabras: «Sí, ahí delante está el vidente. Cabalmente acaba de llegar ahora a la ciudad, porque hay hoy un sacrificio por el pueblo en el alto.

[[first-samuel-9-13]]
^13^ En cuanto entréis en la ciudad, le encontraréis antes de que suba al alto para la comida. El pueblo no comerá antes que él llegue, porque es él quien ha de bendecir el sacrificio; y a continuación comerán los invitados. Subid ahora y al momento le encontraréis».

[[first-samuel-9-14]]
^14^ Subieron, pues, a la ciudad. Entraban ellos por la puerta, cuando Samuel salía en dirección a ellos para subir al alto.

[[first-samuel-9-15]]
^15^ Ahora bien, la víspera de la venida de Saúl había hecho Yahveh está revelación a Samuel:

[[first-samuel-9-16]]
^16^ «Mañana, a esta misma hora, te enviaré un hombre de la tierra de Benjamín, le ungirás como jefe de mi pueblo Israel y él librará a mi pueblo de la mano de los filisteos, porque he visto la aflicción de mi pueblo y su clamor ha llegado hasta mí».

[[first-samuel-9-17]]
^17^ Y cuando Samuel vio a Saúl, Yahveh le indicó: «Este es el hombre del que te he hablado. El regirá a mi pueblo».

[[first-samuel-9-18]]
^18^ Saúl se acercó a Samuel en medio de la puerta, y le dijo: «Indícame, por favor, dónde está la casa del vidente».

[[first-samuel-9-19]]
^19^ Samuel respondió a Saúl: Yo soy el vidente; sube delante de mí al alto y comeréis hoy conmigo. Mañana por la mañana te despediré y te descubriré todo lo que hay en tu corazón.

[[first-samuel-9-20]]
^20^ No te preocupes por las asnas que perdiste hace tres días, porque ya han aparecido. Por lo demás, ¿para quién es lo mejor de Israel? ¿No es para ti y para la casa de tu padre?»

[[first-samuel-9-21]]
^21^ Saúl respondió: ¿No soy yo de Benjamín, la menor de las tribus de Israel? ¿No es mi familia la más pequeña de todas las de la tribu de Benjamín? ¿Cómo me dices estas cosas?»

[[first-samuel-9-22]]
^22^ Tomó Samuel a Saúl y a su criado y los hizo entrar en la sala, y les dio un asiento a la cabecera de los invitados, que eran unos treinta.

[[first-samuel-9-23]]
^23^ Después dijo Samuel al cocinero: «Sirve la porcíon que te entregué, la que te dije que pusieras aparte».

[[first-samuel-9-24]]
^24^ Tomó el cocinero la pierna y el rabo poniéndolos delante de Saúl. Y dijo: «Aquí tienes, ante ti, lo que se guardó. Come..». Aquel día Saúl comió con Samuel.

[[first-samuel-9-25]]
^25^ Bajaron del alto a la ciudad. Se extendió una estera para Saúl en el terrado,

[[first-samuel-9-26]]
^26^ y se acostó. Cuando apuntó el alba, llamó Samuel a Saúl en el terrado y le dijo: «Levántate, que voy a despedirte». Se levantó Saúl y salieron ambos afuera, Samuel y Saúl.

[[first-samuel-9-27]]
^27^ Habían bajabo hasta las afueras de la ciudad, cuando Samuel dijo a Saúl: «Manda a tu criado que se adelante, y tú quédate ahora para que te de a conocer la palabra de Dios».
[[first-samuel-10]]
== Capítulo 10

[[first-samuel-10-1]]
^1^ Tomó Samuel el cuerno de aceite y lo derramó sobre la cabeza de Saúl, y después le besó diciendo: «¿No es Yahveh quien te ha ungido como jefe de su pueblo Israel? Tú regirás al pueblo de Yahveh y le librarás de la mano de los enemigos que le rodean. Y ésta será para ti la señal de que Yahveh te ha ungido como caudillo de su heredad.

[[first-samuel-10-2]]
^2^ En cuanto te separes hoy de mí, encontrarás dos hombres junto a la tumba de Raquel, sobre la frontera de Benjamín... y ellos te dirán: “Las asnas que has ido a buscar ya han aparecido. Ahora tu padre ha olvidado el asunto de las asnas y está preocupado por vosotros, diciendo: ¿Qué debo hacer por mi hijo?”

[[first-samuel-10-3]]
^3^ Pasando más allá, y en llegando a la Encina del Tabor, encontrarás tres hombres que suben hacia Dios, a Betel, uno llevará tres cabritos, otro llevará tres tortas de pan, y el tercero llevará un odre de vino.

[[first-samuel-10-4]]
^4^ Te saludarán y te darán dos panes, que tú tomarás de su mano.

[[first-samuel-10-5]]
^5^ Llegarás después a Guibeá de Dios (donde se encuentra el gobernador de los filisteos) y a la entrada de la ciudad tropezarás con un grupo de profetas que bajan del alto, precedidos del añafil, el adufe, la flauta y la cítara, en trance profético.

[[first-samuel-10-6]]
^6^ Te invadirá entonces el espíritu de Yahveh, entrarás en trance con ellos y quedarás cambiado en otro hombre.

[[first-samuel-10-7]]
^7^ Cuando se te hayan cumplido estas señales, haz lo que te viniere a mano, porque Dios está contigo.

[[first-samuel-10-8]]
^8^ Bajarás delante de mí a Guilgal, y yo me reuniré allí contigo para ofrecer holocaustos y sacrificios de comunión. Esperarás siete días a que yo vaya a tu encuentro y te diré lo que debes hacer».

[[first-samuel-10-9]]
^9^ Apenas volvió las espaldas para dejar a Samuel, le cambió Dios el corazón y todas las señales se realizaron aquel mismo día.

[[first-samuel-10-10]]
^10^ Desde allí fueron a Guibeá, y he aquí que venía frente a él un grupo de profetas; le invadió el espíritu de Dios y se puso en trance en medio de ellos.

[[first-samuel-10-11]]
^11^ Los que le conocían de toda la vida le vieron profetizando con los profetas, y todos los del pueblo se decían entre sí: «¿Qué le ha pasado al hijo de Quis? ¿Conque también Saúl anda entre los profetas?»

[[first-samuel-10-12]]
^12^ Replicó uno de allá: «Y ¿quién es su padre?» Y así pasó a proverbio: «¿Conque también Saúl entre los profetas?».

[[first-samuel-10-13]]
^13^ Y cuando salió del trance se fue a casa.

[[first-samuel-10-14]]
^14^ El tío de Saúl le dijo a él y a su criado: «¿A dónde habéis ido?» Contestó: «A buscar las asnas. Y como no vimos nada, acudimos a Samuel».

[[first-samuel-10-15]]
^15^ Dijo el tío de Saúl: Vamos, cuéntame qué os ha dicho Samuel».

[[first-samuel-10-16]]
^16^ Saúl dijo a su tío: «Sencillamente, nos avisó que las asnas habían aparecido». Pero no le dijo ni palabra de lo que le había dicho Samuel acerca del reino.

[[first-samuel-10-17]]
^17^ Samuel convocó al pueblo en Mispá junto a Yahveh.

[[first-samuel-10-18]]
^18^ Y dijo a los israelitas: Así ha dicho Yahveh, el Dios de Israel: Yo hice subir a Israel de Egipto y os libré de los egipcios y de todos los reinos que os tenían oprimidos.

[[first-samuel-10-19]]
^19^ Pero vosotros ahora habéis rechazado a vuestro Dios, a aquel mismo que os salvó de todos vuestros males y aprietos, y le habéis dicho: “No: tú ponnos un rey.” Ahora, pues, compareced delante de Yahveh distribuidos por tribus y familias».

[[first-samuel-10-20]]
^20^ Samuel hizo acercarse a todas las tribus de Israel y fue designada la tribu de Benjamín.

[[first-samuel-10-21]]
^21^ Hizo que se acercara la tribu de Benjamín por familias y fue designada la familia de Matrí, y luego mandó acercarse a la familia de Matrí por inviduos y quedó finalmente Saúl, hijo de Quis, y le buscaron, pero no le encontraron.

[[first-samuel-10-22]]
^22^ Entonces volvieron a interrogar a Yahveh: «¿Ha venido ése?» Dijo Yahveh: «Aquí le tenéis escondido entre la impedimenta».

[[first-samuel-10-23]]
^23^ Corrieron y lo sacaron de allí y, puesto en medio del pueblo, les llevaba a todos la cabeza.

[[first-samuel-10-24]]
^24^ Dijo Samuel a todo el pueblo: «¿Veis al que ha elegido Yahveh? No hay como él en todo el pueblo». Y todo el pueblo gritó: «¡Viva el rey!».

[[first-samuel-10-25]]
^25^ Samuel dictó al pueblo el fuero real y lo puso por escrito, depositándolo delante de Yahveh, y despidió Samuel a cada cual a su casa.

[[first-samuel-10-26]]
^26^ También Saúl se fue a su casa, a Guibeá; le acompañaron algunos valientes a quienes Dios tocó el corazón.

[[first-samuel-10-27]]
^27^ Pero algunos malvados dijeron: «Qué nos va a salvar ése!» Y le despreciaron y no le llevaron regalos. Cosa de un mes más tarde,
[[first-samuel-11]]
== Capítulo 11

[[first-samuel-11-1]]
^1^ subió Najás el ammonita, y acampó contra Yabés de Galaad. Y todos los de Yabés dijeron a Najás. «Ponnos condiciones y te serviremos».

[[first-samuel-11-2]]
^2^ Dijo Najás el ammonita: «Estas son mis condiciones: saltar a todos el ojo derecho y quedará en ridículo todo Israel».

[[first-samuel-11-3]]
^3^ Y los ancianos de Yabés le dijeron: «Danos una tregua de siete días y mandaremos mensajeros por todo el territorio de Israel y, si no hay quien nos socorra, entonces nos rendiremos a ti».

[[first-samuel-11-4]]
^4^ Llegaron los mensajeros a Guibeá de Saúl, y dijeron estas palabras a oídos del pueblo, y todo el pueblo lloró a voces.

[[first-samuel-11-5]]
^5^ He aquí que venía Saúl del campo detrás de los bueyes y dijo:«¿Qué tiene el pueblo que esta llorando?», y le contaron las palabras de los de Yabés.

[[first-samuel-11-6]]
^6^ Invadió a Saúl el espíritu de Dios en oyendo estas palabras, y se irritó sobremanera.

[[first-samuel-11-7]]
^7^ Y tomando una yunta de bueyes los despedazó y los repartió por todo el territorio de Israel por medio de mensajeros, diciendo: «Así se hará con los bueyes del que no salga detrás de Saúl». Y el temor de Yahveh cayó sobre el pueblo, y salieron como un solo hombre.

[[first-samuel-11-8]]
^8^ Les pasó revista en Bézeq, y eran los israelitas 300.000 y los de Judá 30.000.

[[first-samuel-11-9]]
^9^ Dijeron a los mensajeros que habían venido: «Así diréis a los de Yabés de Galaad: Mañana, cuando el sol apriete , seréis liberados». Fueron los mensajeros y lo anunciaron a los de Yabés, que se alegraron.

[[first-samuel-11-10]]
^10^ Y dijeron los de Yabés a Najás: «Mañana salimos a vosotros y hacéis con nosotros lo que mejor os parezca».

[[first-samuel-11-11]]
^11^ A la mañana siguiente dispuso Saúl a sus hombres en tres columnas que irrumpieron en el campamento durante la guardia de la madrugada, y batieron a los ammonitas hasta que apretó el sol. Y los demás huyeron no quedando dos juntos.

[[first-samuel-11-12]]
^12^ El pueblo dijo a Samuel: «¿Quién andaba preguntando si Saúl iba a reinar sobre nosotros? Dadnos esos hombres y los haremos morir».

[[first-samuel-11-13]]
^13^ Pero Saúl dijo: «Que no muera nadie en este día, porque Yahveh ha realizado hoy una liberación en Israel».

[[first-samuel-11-14]]
^14^ Samuel dijo al pueblo: «Vamos todos a Guilgal e inauguraremos allí la monarquía».

[[first-samuel-11-15]]
^15^ Fue todo el pueblo a Guilgal, y allí en Guilgal, proclamaron rey a Saúl delante de Yahveh, ofreciendo allí sacrificios de communión delante de Yahveh; y Saúl y todos los israelitas se alegraron en extremo.
[[first-samuel-12]]
== Capítulo 12

[[first-samuel-12-1]]
^1^ Samuel dijo a todo Israel: «Ya veis que os he atendido en todo lo que me habéis pedido y he puesto un rey sobre vosotros.

[[first-samuel-12-2]]
^2^ En adelante, el rey marchara delante de vosotros. Cuanto a mí, he envejecido y encanecido, y mis hijos entre vosotros están. He andado delante de vosotros desde mi juventud hasta hoy.

[[first-samuel-12-3]]
^3^ Aquí me tenéis. Atestiguad contra mí delante de Yahveh y delante de su ungido. ¿De quién he tomado yo el buey o de quién he tomado el asno? ¿A quién he atropellado u oprimido? ¿Quién me ha sobornado para que cerrara los ojos? Yo os lo restituiré».

[[first-samuel-12-4]]
^4^ Respondieron: «No nos has atropellado ni oprimido, y nada has recibido de nadie».

[[first-samuel-12-5]]
^5^ El les dijo: «Yahveh es testigo contra vosotros, y su ungido es testigo hoy de que vosotros no habéis encontrado nada en mis manos». Respondieron: «Es testigo».

[[first-samuel-12-6]]
^6^ Dijo entonces Samuel al pueblo: «Testigo es aquel Yahveh que suscitó a Moisés y Aarón y que hizo subir a vuestros padres del país de Egipto.

[[first-samuel-12-7]]
^7^ Presentaos ahora para que yo pleitee con vosotros ante Yahveh y para recordaros todos los beneficios que Yahveh ha llevado a cabo en favor vuestro y de vuestros padres.

[[first-samuel-12-8]]
^8^ Cuando Jacob entró en Egipto, los egipcios los oprimieron y vuestros padres clamaron a Yahveh. Entonces Yahveh envió a Moisés y Aarón que sacaron a vuestros padres de Egipto y los puso en este lugar.

[[first-samuel-12-9]]
^9^ Pero ellos olvidaron a Yahveh su Dios, y él los entregó en manos de Sísara, jefe del ejército de Jasor, en manos de los filisteos y del rey de Moab, que combatieron contra ellos.

[[first-samuel-12-10]]
^10^ Clamaron a Yahveh diciendo: “Hemos pecado, porque hemos abandonado a Yahveh y servido a los Baales y a las Astartés. Pero ahora, líbranos de las manos de nuestros enemigos y te serviremos.”

[[first-samuel-12-11]]
^11^ Envió entonces Yahveh a Yerubbaal, a Baraq, a Jefté y a Samuel, os ha librado de los enemigos que os rodeaban y habéis vivido en seguridad.

[[first-samuel-12-12]]
^12^ Pero, en cuanto habéis visto que Najás, rey de los ammonitas, venía contra vosotros, me habéis dicho: “¡No! Que reine un rey sobre nosotros,” siendo así que vuestro rey es Yahveh, Dios vuestro.

[[first-samuel-12-13]]
^13^ Aquí tenéis ahora al rey que os habéis elegido. Yahveh ha establecido un rey sobre vosotros.

[[first-samuel-12-14]]
^14^ Si teméis a Yahveh y le servís, si escucháis su voz y no os rebeláis contra las órdenes de Yahveh; si vosotros y el rey que reine sobre vosotros seguís a Yahveh vuestro Dios, está bien.

[[first-samuel-12-15]]
^15^ Pero si no escucháis la voz de Yahveh, si os rebeláis contra las órdenes de Yahveh, entonces la mano de Yahveh pesará sobre vosotros y sobre vuestro rey.

[[first-samuel-12-16]]
^16^ Una vez más, quedaos para ver este gran prodigio que Yahveh realiza a vuestros ojos.

[[first-samuel-12-17]]
^17^ ¿No es ahora la cosecha del trigo? Pues bien, voy a invocar a Yahveh para que haga tronar y llover. Reconoced y ved el gran mal que habéis hecho a los ojos de Yahveh, a pedir un rey para vosotros».

[[first-samuel-12-18]]
^18^ Invocó Samuel a Yahveh, que hizo tronar y llover aquel mismo día, y todo el pueblo cobró mucho temor a Yahveh y a Samuel.

[[first-samuel-12-19]]
^19^ Dijo todo el pueblo a Samuel: «Suplica a Yahveh tu Dios en favor de tus siervos, para que no muramos; hemos colmado nuestros pecados pidiendo en rey para nosotros».

[[first-samuel-12-20]]
^20^ Pero Samuel dijo al pueblo: «No temáis. Cierto que habéis hecho esta maldad. Pero ahora, no os alejéis de Yahveh y servidle con todo vuestro corazón,

[[first-samuel-12-21]]
^21^ y no os apartéis en pos de los que no son nada, que no sirven ni salvan porque no son nada.

[[first-samuel-12-22]]
^22^ Pues Yahveh no rechazará a su pueblo por el honor de su gran nombre, porque Yahveh se ha dignado hacer de vosotros su pueblo.

[[first-samuel-12-23]]
^23^ Por mi parte, lejos de mí pecar contra Yahveh dejando de suplicar por vosotros y de enseñaros el camino bueno y recto.

[[first-samuel-12-24]]
^24^ Sólo a Yahveh temeréis y le serviréis fielmente, con todo vuestro corazón, porque habéis visto esta cosa grandiosa que ha realizado en medio de vosotros.

[[first-samuel-12-25]]
^25^ Pero si os portáis mal, pereceréis, vosotros y vuestro rey».
[[first-samuel-13]]
== Capítulo 13

[[first-samuel-13-1]]
^1^ ...

[[first-samuel-13-2]]
^2^ Se eligió Saúl 3.000 hombres de Israel; había 2.000 con Saúl en Mikmás y en las montañas de Betel, y mil con Jonatán en Gueba de Benjamín, y el resto del pueblo lo devolvió a sus tiendas.

[[first-samuel-13-3]]
^3^ Jonatán mató al gobernador de los filisteos que se hallaba en Guibeá, y supieron los filisteos que los hebreos se habian rebelado. Saúl hizo sonar el cuerno por toda la tierra,

[[first-samuel-13-4]]
^4^ y todo Israel oyó la noticia: «Saúl ha matado al gobernador de los filisteos. Israel se ha hecho odioso a los filisteos». Y se reunió el pueblo tras Saúl en Guilgal.

[[first-samuel-13-5]]
^5^ Se concentraron los filisteos para combatir a Israel: 3.000 carros, 6.000 caballos y un ejército tan numeroso como la arena de la orilla del mar; y acamparon en Mikmás, al este de Bet Avén.

[[first-samuel-13-6]]
^6^ Cuando los hombres de Israel se vieron en peligro, porque se les apretaba de cerca, se escondió la gente en las cavernas, los agujeros, las hendiduras de las peñas, los subterráneos y las cisternas.

[[first-samuel-13-7]]
^7^ Algunos hebreos pasaron también el Jordán al país de Gad y Galaad. Saúl estaba todavía en Guilgal y todo el pueblo temblaba junto a él.

[[first-samuel-13-8]]
^8^ Esperó siete días conforme al plazo que Samuel había fijado, pero Samuel no llegó a Guilgal y el ejército se desbandó, abandonando a Saúl.

[[first-samuel-13-9]]
^9^ Entonces Saúl dijo: «Acercadme el holocausto y los sacrificios de comunión», y ofreció el holocausto.

[[first-samuel-13-10]]
^10^ Acababa él de ofrecer el holocausto, cuando llegó Samuel, y Saúl le salió al encuentro para saludarle.

[[first-samuel-13-11]]
^11^ Samuel dijo: «¿Qué has hecho?» Y Saúl respondió: «Como vi que el ejército me abandonaba y se desbandaba, que, por otro lado, tú no venías en el plazo fijado, y que los filisteos estaban ya concentrados en Mikmás,

[[first-samuel-13-12]]
^12^ me dije: Ahora los filisteos van a bajar contra mí a Guilgal y no he apaciguado a Yahveh. Entonces me he visto forzado a ofrecer el holocausto».

[[first-samuel-13-13]]
^13^ Samuel dijo a Saúl: «Te has portado como un necio. Si hubieras cumplido la orden que Yahveh tu Dios te ha dado, entonces Yahveh hubiera afianzado tu reino para siempre sobre Israel.

[[first-samuel-13-14]]
^14^ Pero ahora tu reino no se mantendrá. Yahveh se ha buscado un hombre según su corazón, al que ha designado caudillo de su pueblo, porque tú no has cumplido lo que Yahveh te había ordenado».

[[first-samuel-13-15]]
^15^ Se levantó Samuel y partió de Guilgal para seguir su camino. Los que quedaban del pueblo subieron tras Saúl al encuentro de los hombres de guerra, y vino de Guilgal a Gueba de Benjamín. Saúl pasó revista a las tropas que tenía con él: había unos seiscientos hombres.

[[first-samuel-13-16]]
^16^ Saúl, su hijo Jonatán y las tropas que estaban con ellos, se hallaban situados en Gueba de Benjamín, mientras que los filisteos acampaban en Mikmás.

[[first-samuel-13-17]]
^17^ La fuerza de choque salió del campo filisteo en tres columnas: una columna tomó la dirección de Ofrá, en la comarca de Sual;

[[first-samuel-13-18]]
^18^ otra tomó la dirección de Bet Jorón y la tercera tomó la dirección del alto que domina el valle de los Seboím, hacia el desierto.

[[first-samuel-13-19]]
^19^ No había herreros en todo el territorio de Israel, porque los filisteos se decían: «Que no hagan los hebreos espadas ni lanzas».

[[first-samuel-13-20]]
^20^ Así todos los israelitas tenían que bajar a los filisteos para vaciar cada cual su reja, su hacha, su azuela o su aguijada.

[[first-samuel-13-21]]
^21^ El precio era dos tercios de siclo por aguzar las azuelas y enderezar la aguijada.

[[first-samuel-13-22]]
^22^ Y así ocurrió que el día de la batalla nadie, en toda la tropa que estaba con Saúl y Jonatán, tenía en la mano espada ni lanza. Las había sólo para Saúl y para su hijo Jonatán.

[[first-samuel-13-23]]
^23^ Una avanzadilla de filisteos partió hacia el paso de Mikmás.
[[first-samuel-14]]
== Capítulo 14

[[first-samuel-14-1]]
^1^ Un día, Jonatán, hijo de Saúl, dijo a su escudero: «Ven, vamos a cruzar hasta la avanzadilla de los filisteos que están en este paso», pero nada dijo a su padre.

[[first-samuel-14-2]]
^2^ Saúl estaba situado en el límite de Gueba, bajo el granado que está cerca de la era, y las gentes que estaban con él eran como unos seiscientos hombres.

[[first-samuel-14-3]]
^3^ Ajías, hijo de Ajitub, hermano de Ikabod, hijo de Pinjás, hijo de Elí, sacerdote de Yahveh en Silo, llevaba el efod. La tropa no advirtió que Jonatán se había marchado.

[[first-samuel-14-4]]
^4^ En el paso que Jonatán intentaba franquear para llegar a la avanzadilla de los filisteos, hay un picacho por un lado y un picacho por el otro. Uno se llama Boses y el otro Senné;

[[first-samuel-14-5]]
^5^ el primer picacho está al norte, frente a Mikmás, el segundo al sur, frente a Gueba.

[[first-samuel-14-6]]
^6^ Jonatán dijo a su escudero: «Ven, crucemos hasta la avanzadilla de esos incircuncisos. Acaso Yahveh haga algo por nosotros, porque nada impide a Yahveh dar la victoria con pocos o con muchos».

[[first-samuel-14-7]]
^7^ Su escudero respondió: «Haz todo lo que tu corazón te dicte. Por mi parte estoy contigo, a tu voluntad».

[[first-samuel-14-8]]
^8^ Jonatán dijo: «Vamos a pasar hacia esa gente y nos haremos ver de ellos.

[[first-samuel-14-9]]
^9^ Si nos dicen: “¡Alto ahí! hasta que lleguemos a vosotros”, nos quedaremos en el sitio y no subiremos a ellos.

[[first-samuel-14-10]]
^10^ Pero si nos dicen: “Subid hacia nosotros,” subiremos, porque Yahveh los ha entregado en nuestras manos; esto nos servirá de señal».

[[first-samuel-14-11]]
^11^ Cuando se dejaron ver de la avanzadilla de los filisteos, éstos dijeron: «Mirad los hebreos que salen de los escondrijos donde se habían metido».

[[first-samuel-14-12]]
^12^ Y la gente de la avanzadilla, dirigiéndose a Jonatán y a su escudero, dijeron: «Subid hacia nosotros, que os vamos a enseñar algo». Entonces Jonatán dijo a su escudero: «Sube detrás de mí, pues Yahveh los ha entregado en manos de Israel».

[[first-samuel-14-13]]
^13^ Subió Jonatán ayudándose de pies y manos, y su escudero le seguía. Caían los filisteos ante Jonatán y detrás de él su escudero los iba rematando.

[[first-samuel-14-14]]
^14^ Este primer estrago que hicieron Jonatán y su escudero fue de una veintena de hombres...

[[first-samuel-14-15]]
^15^ Cundió el terror en el campo y en el campamento y en la gente toda; la avanzadilla y los cuerpos de descubierta fueron presa del espanto, la tierra tembló y hubo un terror de Dios.

[[first-samuel-14-16]]
^16^ Los escuchas de Saúl que estaban en Gueba de Benjamín vieron que el campamento se agitaba de un lado para otro,

[[first-samuel-14-17]]
^17^ y Saúl dijo a las tropas que estaban con él: «Pasad revista y ved quién se ha marchado de los nuestros». Se pasó revista y vieron que faltaban Jonatán y su escudero.

[[first-samuel-14-18]]
^18^ Entonces Saúl dijo a Ajías: «Trae el efod», porque este era el que llevaba el efod en presencia de Israel.

[[first-samuel-14-19]]
^19^ Pero mientras Saúl hablaba al sacerdote, el tumulto del campamento filisteo iba creciendo y Saúl dijo al sacerdote: «Retira tu mano».

[[first-samuel-14-20]]
^20^ Saúl y toda la tropa que estaba con él se reunieron y llegaron al campo de batalla, y he aquí que la espada de cada uno se volvía contra el otro, ¡un enorme desconcierto!

[[first-samuel-14-21]]
^21^ Los hebreos que de antes estaban al servicio de los filisteos y que habían subido con ellos al campamento, también desertaron y se pasaron a los israelitas que estaban con Saúl y Jonatán.

[[first-samuel-14-22]]
^22^ Todos los israelitas que se habían escondido en la montaña de Efraím, al saber que los filisteos huían, los persiguieron hostigándolos.

[[first-samuel-14-23]]
^23^ Aquel día Yahveh dio la victoria a Israel. El combate se extendió más allá de Bet Jorón.

[[first-samuel-14-24]]
^24^ Los hombres de Israel estaban en gran apuro aquel día y Saúl pronunció una imprecación sobre el pueblo: «Maldito el hombre que coma algo antes del anochecer, antes que me haya vengado de mis enemigos». Y nadie del pueblo probó bocado.

[[first-samuel-14-25]]
^25^ Había, pues, un panal de miel por el suelo,

[[first-samuel-14-26]]
^26^ y el pueblo llegó al panal cuando la miel estaba destilando, pero nadie se llevó la mano a su boca, porque el pueblo temía la imprecación.

[[first-samuel-14-27]]
^27^ Jonatán no había oído la imprecación que su padre había pronunciado sobre el pueblo y alargó la punta de la vara que tenía en la mano, la metió en el panal y después llevó la mano a su boca y le brillaron los ojos.

[[first-samuel-14-28]]
^28^ Uno del pueblo le habló diciendo: «Tu padre ha pronunciado solemnemente esta imprecación sobre el pueblo; ha dicho “Maldito el hombre que coma hoy algo.”»

[[first-samuel-14-29]]
^29^ Jonatán respondió: «Mi padre ha causado un trastorno al país. Ved cómo tengo los ojos más brillantes por haber tomado este poco de miel.

[[first-samuel-14-30]]
^30^ Pues si la tropa hubiese comido hoy del botín tomado al enemigo ¿no hubiera sido mayor el estrago de los filisteos?»

[[first-samuel-14-31]]
^31^ Aquel día fueron batidos los filisteos desde Mikmás hasta Ayyalón y la gente quedó extenuada.

[[first-samuel-14-32]]
^32^ La tropa se arrojó sobre el botín y tomando ganado menor, bueyes y terneros, los immoló sobre el suelo y lo comieron con la sangre.

[[first-samuel-14-33]]
^33^ Avisaron a Saúl: «El pueblo está pecando contra Yahveh comiendo la sangre». El entonces dijo: «Habéis sido infieles. Rodadme hasta aquí una piedra grande».

[[first-samuel-14-34]]
^34^ Luego dijo: «Repartíos entre el pueblo y decidles: que cada uno traiga su buey o su carnero; los immolaréis aquí y comeréis, sin pecar contra Yahveh por comerlo con sangre». Todos los hombres llevaron cada cual lo que tenía aquella noche y lo immolaron allí.

[[first-samuel-14-35]]
^35^ Alzó Saúl un altar a Yahveh; este fue el primer altar que edificó.

[[first-samuel-14-36]]
^36^ Saúl dijo: «Bajemos durante la noche en persecución de los filisteos y saqueémoslos hasta el amanecer; no dejaremos ni un solo hombre». Le respondieron: «Haz lo que mejor te parezca». Pero el sacerdote dijo: «Acerquémonos aquí a Dios».

[[first-samuel-14-37]]
^37^ Consultó Saúl a Dios: «¿Bajaré en persecución de los filisteos? ¿Los entregarás en manos de Israel?» Pero no respondió en aquella ocasión.

[[first-samuel-14-38]]
^38^ Entonces dijo Saúl: «Acercaos aquí todos los principales del pueblo. Investigad en qué ha consistido el pecado de hoy.

[[first-samuel-14-39]]
^39^ ¡Vive Yahveh! que ha salvado a Israel, que aunque se trate de mi hijo Jonatán, morirá sin remisión». Nadie del pueblo se atrevió a responderle.

[[first-samuel-14-40]]
^40^ Dijo a todo Israel: «Poneos a un lado, y yo y mi hijo Jonatán nos pondremos al otro», y el pueblo respondió a Saúl: «Haz lo que mejor te parezca».

[[first-samuel-14-41]]
^41^ Dijo entonces Saúl: «Yahveh Dios de Israel, ¿por qué no respondes hoy a tu siervo? Si el pecado es mío o de mi hijo Jonatán, Yahveh Dios de Israel, da urim; si el pecado es de tu pueblo Israel, da tummim». Fueron señalado Saúl y Jonatán, quedando libre el pueblo.

[[first-samuel-14-42]]
^42^ Saúl dijo: «Sortead entre mi hijo Jonatán y yo»; y fue señalado Jonatán.

[[first-samuel-14-43]]
^43^ Dijo entonces Saúl a Jonatán: «Cuéntame lo que has hecho». Jonatán respondió: «No he hecho más que probar un poco de miel con la punta de la vara que tenía en la mano. Estoy dispuesto a morir».

[[first-samuel-14-44]]
^44^ Saúl replicó: «Que Dios me haga esto y me añada esto otro si no mueres, Jonatán».

[[first-samuel-14-45]]
^45^ Pero el pueblo dijo a Saúl: «¿Es que va a morir Jonatán siendo él quien ha conseguido esta gran victoria en Israel? ¡Dios nos libre! ¡Vive Yahveh! que no caerá en tierra ni un cabello de su cabeza, porque con ayuda de Dios lo hizo». Así rescató el pueblo a Jonatán y no murió.

[[first-samuel-14-46]]
^46^ Regresó Saúl de la persecución de los filisteos y los filisteos alcanzaron su país.

[[first-samuel-14-47]]
^47^ Cuando Saúl se constituyó rey sobre Israel guerreó por todas partes contre todos sus enemigos: contra Moab, los ammonitas, Edom, el rey de Sobá y los filisteos; doquiera se dirigía resultaba vencedor.

[[first-samuel-14-48]]
^48^ Hizo proezas de valor, batió a los amalecitas y libró a Israel del poder de los que le saqueaban.

[[first-samuel-14-49]]
^49^ Los hijos de Saúl fueron: Jonatán, Isyó y Malki Súa. Los nombres de sus dos hijas eran: Merab la mayor y Mikal la más pequeña.

[[first-samuel-14-50]]
^50^ La mujer de Saúl se llamaba Ajinoam, hija de Ajimaas. El jefe de su ejército se llamaba Abner, hijo de Ner, tío de Saúl:

[[first-samuel-14-51]]
^51^ Quis, padre de Saúl, y Ner, padre de Abner, eran hijos de Abiel.

[[first-samuel-14-52]]
^52^ Hubo una guerra encarnizada contra los filisteos toda la vida de Saúl. En cuanto Saúl veía un hombre fuerte y valeroso, se lo incorporaba.
[[first-samuel-15]]
== Capítulo 15

[[first-samuel-15-1]]
^1^ Samuel dijo a Saúl: «Yahveh me ha enviado para consagrarte rey sobre su pueblo Israel. Escucha, pues, las palabras de Yahveh:

[[first-samuel-15-2]]
^2^ Esto dice Yahveh Sebaot: He decidido castigar lo que Amalec hizo a Israel, cortándole el camino cuando subía de Egipto.

[[first-samuel-15-3]]
^3^ Ahora, vete y castiga a Amalec, consagrándolo al anatema con todo lo que posee, no tengas compasión de él, mata hombres y mujeres, niños y lactantes, bueyes y ovejas, camellos y asnos».

[[first-samuel-15-4]]
^4^ Convocó Saúl al pueblo y le pasó revista en Telam: 200.000 infantes y 10.000 hombres de Judá.

[[first-samuel-15-5]]
^5^ Avanzó Saúl hasta la capital de Amalec y se emboscó en el barranco.

[[first-samuel-15-6]]
^6^ Dijo Saúl a los quenitas: «Marchaos, apartaos de los amalecitas, no sea que os haga desaparecer con ellos, pues os portasteis bien con todos los israelitas cuando subían de Egipto»; y los quenitas se apartaron de los amalecitas.

[[first-samuel-15-7]]
^7^ Batió Saúl a los amalecitas desde Javilá, en dirección de Sur que está al este de Egipto.

[[first-samuel-15-8]]
^8^ Capturo vivo a Agag, rey de los amalecitas, y pasó a todo el pueblo a filo de espada en cumplimiento del anatema.

[[first-samuel-15-9]]
^9^ Pero Saúl y la tropa perdonaron a Agag y a lo más escogido del ganado mayor y menor, las reses cebadas y los corderos y todo lo bueno. No quisieron consagrarlo al anatema, pero consagraron al anatema toda la hacienda vil y sin valor.

[[first-samuel-15-10]]
^10^ Le fue dirigida la palabra de Dios a Samuel diciendo:

[[first-samuel-15-11]]
^11^ «Me arrepiento de haber dedo la realeza a Saúl, porque se ha apartado de mí y no ha ejecutado mis órdenes». Se conmovió Samuel y estuvo clamando a Yahveh toda la noche.

[[first-samuel-15-12]]
^12^ Se levantó Samuel por la mañana al encuentro de Saúl. Avisaron a Samuel: «Saúl ha ido a Carmelo y se ha erigido un monumento; después ha seguido y ha bajado a Guilgal».

[[first-samuel-15-13]]
^13^ Llegó Samuel donde Saúl y éste dijo: «Bendito seas de Yahveh. Ya he ejecutado la orden de Yahveh».

[[first-samuel-15-14]]
^14^ Pero Samuel preguntó: «¿Y qué son esos balidos que vienen a mis oídos y esos mugidos que oigo?»

[[first-samuel-15-15]]
^15^ Respondió Saúl: «Los hemos traído de Amalec porque el pueblo ha perdonado lo mejor del ganado mayor y menor con intención de ofrecerlo en sacrificio a Yahveh tu Dios. Cuanto a lo demás, lo hemos entregado al anatema».

[[first-samuel-15-16]]
^16^ Pero Samuel dijo a Saúl: «Basta ya y deja que te anuncie lo que Yahveh me ha revelado esta noche». El le dijo: «Habla».

[[first-samuel-15-17]]
^17^ Entonces Samuel dijo: «Aunque tú eres pequeño a tus propios ojos ¿no eres el jefe de las tribus de Israel? Yahveh te ha ungido rey de Israel.

[[first-samuel-15-18]]
^18^ Yahveh te ha enviado por el camino y te ha dicho: “Vete, y consagra al anatema a estos pecadores, los amalecitas, hazles la guerra hasta el exterminio”.

[[first-samuel-15-19]]
^19^ Por qué no has eschuchado a Yahveh? ¿Por qué te has lanzado sobre el botín y has hecho lo que desagrada a Yahveh?»

[[first-samuel-15-20]]
^20^ Saúl respondió a Samuel: «¡Yo he obedecido a Yahveh! Anduve por el camino por el que me envió, he traído a Agag, rey de Amalec, y he entregado al anatema a los amalecitas.

[[first-samuel-15-21]]
^21^ Del botín, el pueblo ha tomado el ganado mayor y menor, lo mejor del anatema, para sacrificarlo a Yahveh tu Dios en Guilgal».

[[first-samuel-15-22]]
^22^ Pero Samuel dijo: ¿Acaso se complace Yahveh en los holocaustos y sacrificios como en la obediencia a la palabra de Yahveh? Mejor es obedecer que sacrificar, mejor la docilidad que la grasa de los carneros.

[[first-samuel-15-23]]
^23^ Como pecado de hechicería es la rebeldía, crimen de terafim la contumacia. Porque has rechazado la palabra de Yahveh, él te rechaza para que no seas rey.

[[first-samuel-15-24]]
^24^ Saúl dijo a Samuel: «He pecado traspasando la orden de Yahveh y tus mandatos, porque tuve miedo al pueblo y le escuché.

[[first-samuel-15-25]]
^25^ Ahora, pues, perdona mi pecado, por favor, y ven conmigo para que adore a Yahveh».

[[first-samuel-15-26]]
^26^ Pero Samuel respondió a Saúl: «No iré más contigo; ya que has rechazado la palabra de Yahveh, Yahveh te ha rechazado para que no seas rey de Israel».

[[first-samuel-15-27]]
^27^ Y como Samuel se volviera para marcharse, le asió Saúl el extremo del manto, que se desgarró,

[[first-samuel-15-28]]
^28^ y Samuel dijo: «Hoy te ha desgarrado Yahveh el reino de Israel y se lo ha dado a otro mejor que tú».

[[first-samuel-15-29]]
^29^ (Y la Gloria de Israel no miente ni se arrepiente, porque no es un hombre para arrepentirse).

[[first-samuel-15-30]]
^30^ Saúl dijo: «He pecado, pero, con todo, te ruego que me honres ahora delante de los ancianos de mi pueblo y delante de Israel y vengas conmigo para que adore a Yahveh tu Dios».

[[first-samuel-15-31]]
^31^ Volvió Samuel con Saúl y éste adoró a Yahveh.

[[first-samuel-15-32]]
^32^ Después dijo Samuel: «Traedme a Agag, rey de los amalecitas», y vino Agag hacia él y se resistía diciendo: «En verdad es amarga la muerte».

[[first-samuel-15-33]]
^33^ Samuel dijo: «Como tu espada ha privado a las mujeres de sus hijos, así entre las mujeres, privada de su hijo será tu madre», y Samuel despedazó a Agag ante Yahveh en Guilgal.

[[first-samuel-15-34]]
^34^ Partió Samuel para Ramá, y Saúl subió a su casa en Guibeá de Saúl.

[[first-samuel-15-35]]
^35^ Samuel no vio más a Saúl hasta el día de su muerte. Y lloraba Samuel por Saúl, pero Yahveh se había arrepentido de haberle hecho rey de Israel.
[[first-samuel-16]]
== Capítulo 16

[[first-samuel-16-1]]
^1^ Dijo Yahveh a Samuel: «¿Hasta cuándo vas a estar llorando por Saúl, después que yo le he rechazado para que no reine sobre Israel? Llena tu cuerno de aceite y vete. Voy a enviarte a Jesé, de Belén, porque he visto entre sus hijos un rey para mí».

[[first-samuel-16-2]]
^2^ Samuel replicó: «¿Cómo voy a ir? Se enterará Saúl y me matará». Respondió Yahveh: «Lleva contigo una becerra y di: “He venido a sacrificar a Yahveh.”

[[first-samuel-16-3]]
^3^ Invitarás a Jesé al sacrificio y yo te indicaré lo que tienes que hacer, y me ungirás a aquel que yo te diga».

[[first-samuel-16-4]]
^4^ Hizo Samuel lo que Yahveh le había ordenado y se fue a Belén. Salieron temblando a su encuentro los ancianos de la ciudad y le preguntaron: «¿Es de paz tu venida, vidente?»

[[first-samuel-16-5]]
^5^ Samuel respondió: «Sí; he venido a sacrificar a Yahveh. Purificaos y venid conmigo al sacrificio». Purificó a Jesé y a sus hijos y les invitó al sacrificio.

[[first-samuel-16-6]]
^6^ Cuando ellos se presentaron vio a Eliab y se dijo: «Sin duda está ante Yahveh su ungido».

[[first-samuel-16-7]]
^7^ Pero Yahveh dijo a Samuel: «No mires su apariencia ni su gran estatura, pues yo le he descartado. La mirada de Dios no es como la mirada del hombre, pues el hombre mira las apariencias, pero Yahveh mira el corazón».

[[first-samuel-16-8]]
^8^ Llamó Jesé a Abinadab y le hizo pasar ante Samuel, que dijo: «Tampoco a éste ha elegido Yahveh».

[[first-samuel-16-9]]
^9^ Jesé hizo pasar a Sammá, pero Samuel dijo: «Tampoco a éste ha elegido Yahveh».

[[first-samuel-16-10]]
^10^ Hizo pasar Jesé a sus siete hijos ante Samuel, pero Samuel dijo: «A ninguno de éstos ha elegido Yahveh».

[[first-samuel-16-11]]
^11^ Preguntó, pues, Samuel a Jesé: «¿No quedan ya más muchachos?» El respondió: «Todavía falta el más pequeño, que está guardando el rebaño». Dijo entonces Samuel a Jesé: «Manda que lo traigan, porque no comeremos hasta que haya venido».

[[first-samuel-16-12]]
^12^ Mandó, pues, que lo trajeran; era rubio, de bellos ojos y hermosa presencia. Dijo Yahveh: «Levántate y úngelo, porque éste es».

[[first-samuel-16-13]]
^13^ Tomó Samuel el cuerno de aceite y le ungió en medio de sus hermanos. Y a partir de entonces, vino sobre David el espíritu de Yahveh. Samuel se levantó y se fue a Ramá.

[[first-samuel-16-14]]
^14^ El espíritu de Yahveh se había apartado de Saúl y un espíritu malo que venía de Yahveh le perturbaba.

[[first-samuel-16-15]]
^15^ Dijéronle, pues, los servidores de Saúl: «Mira, un espíritu malo de Dios te aterroriza;

[[first-samuel-16-16]]
^16^ permítenos, señor, que tus siervos que están en tu presencia te busquen un hombre que sepa tocar la cítara, y cuando te asalte el espíritu malo de Dios tocará y te hará bien».

[[first-samuel-16-17]]
^17^ Dijo Saúl a sus servidores: «Buscadme, pues, un hombre que sepa tocar bien y traédmelo».

[[first-samuel-16-18]]
^18^ Tomó la palabra uno de los servidores y dijo: «He visto a un hijo de Jesé el belemita que sabe tocar; es valeroso, buen guerrero, de palabra amena, de agradable presencia y Yahveh está con él».

[[first-samuel-16-19]]
^19^ Despachó Saúl mensajeros a Jesé que le dijeran: «Envíame a tu hijo David, el que está con el rebaño».

[[first-samuel-16-20]]
^20^ Tomó Jesé cinco panes, un odre de vino y un cabrito y lo envió a Saúl con su hijo David.

[[first-samuel-16-21]]
^21^ Llegó David donde Saúl y se quedó a su servicio. Saúl le cobró mucho afecto y le hizo su sescudero.

[[first-samuel-16-22]]
^22^ Mandó Saúl a decir a Jesé: «Te ruego que tu hijo David se quede a mi servicio, porque ha hallado gracia a mis ojos».

[[first-samuel-16-23]]
^23^ Cuando el espíritu de Dios asaltaba a Saúl, tomaba David la cítara, la tocaba, Saúl, encontraba calma y bienestar y el espíritu malo se apartaba de él.
[[first-samuel-17]]
== Capítulo 17

[[first-samuel-17-1]]
^1^ Reunieron los filisteos sus tropas para la guerra y se concentraron en Soko de Judá, acampando entre Soko y Azeca, en Efes Dammim.

[[first-samuel-17-2]]
^2^ Se reunieron Saúl y los hombres de Israel, acamparon en el valle del Terebinto y se ordenaron en batalla frente a los filisteos.

[[first-samuel-17-3]]
^3^ Ocupaban los filisteos una montaña por un lado y los israelitas ocupaban la montaña frontera, quedando el valle por medio.

[[first-samuel-17-4]]
^4^ Salió de las filas de los filisteos un hombre de las tropas de choque, llamado Goliat, de Gat, de seis codos y un palmo de estatura;

[[first-samuel-17-5]]
^5^ tenía un yelmo de bronce sobre su cabeza y estaba revestido de una coraza de escamas, siendo el peso de la coraza 5.000 siclos de bronce.

[[first-samuel-17-6]]
^6^ Tenía en las piernas grebas de bronce y una jabalina de bronce entre los hombros.

[[first-samuel-17-7]]
^7^ El asta de su lanza era como enjullo de tejedor y la punta de su lanza pesaba seiscientos siclos de hierro. Su escudero le precedía.

[[first-samuel-17-8]]
^8^ Goliat se plantó y gritó a las filas de Israel diciéndoles: «¿Para qué habéis salido a poneros en orden de batalla? ¿Acaso no soy yo filisteo y vosotros servidores de Saúl? Escogeos un hombre y que baje contra mí.

[[first-samuel-17-9]]
^9^ Si es capaz de pelear conmigo y me mata, seremos vuestros esclavos pero si yo le venzo y le mato, seréis nuestros esclavos y nos serviréis».

[[first-samuel-17-10]]
^10^ Y añadió el filisteo: «Yo desafío hoy a las filas de Israel; dadme un hombre y lucharemos mano a mano».

[[first-samuel-17-11]]
^11^ Oyó Saúl y todo Israel estas palabras del filisteo y se consternaron y se llenaron de miedo.

[[first-samuel-17-12]]
^12^ Era David hijo de un efrateo de Belén de Judá, llamado Jesé, que tenía ocho hijos. En tiempo de Saúl este hombre era ya anciano, muy entrado en años.

[[first-samuel-17-13]]
^13^ Los tres hijos mayores de Jesé se fueron a la guerra con Saúl; el nombre de los tres hijos suyos que marcharon a la guerra era Eliab, el primogénito, Abinadab, el segundo, y Sammá, el tercero.

[[first-samuel-17-14]]
^14^ David era el más pequeño; cuanto a los tres mayores, habían seguido a Saúl.

[[first-samuel-17-15]]
^15^ (David alternaba sus viajes al campamento de Saúl con el cuidado del rebaño de su padre en Belén).

[[first-samuel-17-16]]
^16^ El filisteo se acercaba mañana y tarde y se presentó así durante cuarenta días.

[[first-samuel-17-17]]
^17^ Jesé dijo a su hijo David: «Lleva a tus hermanos esta medida de trigo tostado y estos diez panes y corre al campamento a donde tus hermanos.

[[first-samuel-17-18]]
^18^ Y estos diez requesones llévalos al jefe de millar; entérate de la salud de tus hermanos y toma señal de recibo de ellos.

[[first-samuel-17-19]]
^19^ Están Saúl, ellos y todos los hombres de Israel en el valle del Terebinto, guerreando con los filisteos».

[[first-samuel-17-20]]
^20^ Se levantó David de madrugada, dejó el rebaño al guarda y, tomado las cosas, se fue como le había mandado Jesé, y llegó al círculo del campamento justo cuando salía el ejército para ordenarse en batalla, lanzando el grito de guerra.

[[first-samuel-17-21]]
^21^ Israel y los filisteos se pusieron en orden de batalla, fila contra fila.

[[first-samuel-17-22]]
^22^ Dejó David las cosas en manos del guardia de la impedimenta y corrió a las filas y fue a preguntar a sus hermanos cómo estaban.

[[first-samuel-17-23]]
^23^ Mientras hablaba con ellos el hombre de las tropas de choque, llamado Goliat, el filisteo de Gat, subía de las filas de los filisteos, diciendo las mismas palabras, y le oyó David.

[[first-samuel-17-24]]
^24^ En viéndole todos los hombres de Israel huyeron delante de él, llenos de miedo.

[[first-samuel-17-25]]
^25^ Los hombres de Israel decían: «¿Habéis visto a este hombre que sube? Sube a provocar a Israel. A quien lo mate colmará el rey de grandes riquezas y le dará su hija y librará de tributo la casa de su padre en Israel».

[[first-samuel-17-26]]
^26^ Preguntó, pues, David a los hombres que estaban a su lado: «¿Qué se hará al hombre que mate a ese filisteo y aparte la afrenta de Israel? Pues ¿quién es ese filisteo incircunciso para injuriar a las huestes de Dios vivo?»

[[first-samuel-17-27]]
^27^ Y el pueblo le repitió las mismas palabras: «Así se hará al hombre que lo mate».

[[first-samuel-17-28]]
^28^ Se enteró Eliab, su hermano mayor, de su pregunta a los hombres y se encendió en cólera Eliab contra David, y le dijo: «¿Para qué has bajado, y a quién has dejado aquel pequeño rebaño en el desierto? Ya sé yo tu atrevimiento y la maldad de tu corazón. Has bajado para ver la batalla».

[[first-samuel-17-29]]
^29^ Respondió David: «Pues ¿qué he hecho yo? ¿es que uno no puede hablar?»

[[first-samuel-17-30]]
^30^ Y volviéndose se dirigió a otro y preguntó lo mismo y la gente le respondió como la primera vez.

[[first-samuel-17-31]]
^31^ Fueron oídas las palabras que decía David y se lo contaron a Saúl, que le hizo venir.

[[first-samuel-17-32]]
^32^ Dijo David a Saúl: «Que nadie se acobarde por ése. Tu siervo irá a combatir con ese filisteo».

[[first-samuel-17-33]]
^33^ Dijo Saúl a David: «No puedes ir contra ese filisteo para luchar con él, porque tú eres un niño y él es hombre de guerra desde su juventud».

[[first-samuel-17-34]]
^34^ Respondió David a Saúl: «Cuando tu siervo estaba guardando el rebaño de su padre y venía el león o el oso y se llevaba una oveja del rebaño,

[[first-samuel-17-35]]
^35^ salía tras él, le golpeaba y se la arrancaba de sus fauces, y si se revolvía contra mí, lo sujetaba por la quijada y lo golpeaba hasta matarlo.

[[first-samuel-17-36]]
^36^ Tu siervo ha dado muerte al león y al oso, y ese filisteo incircunciso será como uno de ellos, pues ha insultado a las huestes de Dios vivo».

[[first-samuel-17-37]]
^37^ Añadió David: «Yahveh que me ha librado de las garras del león y del oso, me librará de la mano de ese filisteo». Dijo Saúl a David: «Vete, y que Yahveh sea contigo».

[[first-samuel-17-38]]
^38^ Mandó Saúl que vistieran a David con sus propios vestidos y le puso un casco de bronce en la cabeza y le cubrió con una coraza.

[[first-samuel-17-39]]
^39^ Ciñó a David su espada sobre su vestido. Intentó David caminar, pues aún no estaba acostumbrado, y dijo a Saúl: «No puedo caminar con esto, pues nunca lo he hecho». Entonces se lo quitaron.

[[first-samuel-17-40]]
^40^ Tomó su cayado en la mano, escogió en el torrente cinco cantos lisos y los puso en su zurrón de pastor, en su morral , y con su honda en la mano se acercó al filisteo.

[[first-samuel-17-41]]
^41^ El filisteo fue avanzando y acercándose a David, precedido de su escudero.

[[first-samuel-17-42]]
^42^ Volvió los ojos el filisteo, y viendo a David, lo despreció, porque era un muchacho rubio y apuesto.

[[first-samuel-17-43]]
^43^ Dijo el filisteo a David: «¿Acaso soy un perro, pues vienes contra mí con palos?» Y maldijo a David el filisteo por sus dioses,

[[first-samuel-17-44]]
^44^ y dijo el filisteo a David: «Ven hacia mí y daré tu carne a las aves del cielo y a las fieras del campo».

[[first-samuel-17-45]]
^45^ Dijo David al filisteo: «Tú vienes contra mí con espada, lanza y jabalina, pero yo voy contra ti en nombre de Yahveh Sebaot, Dios de los ejércitos de Israel, a los que has desafiado.

[[first-samuel-17-46]]
^46^ Hoy mismo te entrega Yahveh en mis manos, te mataré y te cortaré la cabeza y entragaré hoy mismo tu cadáver y los cadáveres del ejército filisteo a las aves del cielo y a las fieras de la tierra, y sabrá toda la tierra que hay Dios para Israel.

[[first-samuel-17-47]]
^47^ Y toda esta asamblea sabrá que no por la espada ni por la lanza salva Yahveh, porque de Yahveh es el combate y os entrega en nuestras manos».

[[first-samuel-17-48]]
^48^ Se levantó el filisteo y fue acercándose al encuentro de David; se apresuró David, salió de las filas y corrió al encuentro del filisteo.

[[first-samuel-17-49]]
^49^ Metió su mano David en su zurrón, sacó de él una piedra, la lanzó con la honda e hirió al filisteo en la frente; la piedra se clavó en su frente y cayó de bruces en tierra.

[[first-samuel-17-50]]
^50^ Y venció David al filisteo con la honda y la piedra; hirió al filisteo y le mató sin tener espada en su mano.

[[first-samuel-17-51]]
^51^ Corrió David, se detuvo sobre el filisteos y tomando la espada de éste de sacó de su vaina, le mató y le cortó la cabeza. Viendo los filisteos que había muerto su campeón, huyeron.

[[first-samuel-17-52]]
^52^ Se levantaron los hombres de Israel y de Judá y, lanzando el grito de guerra, persiguieron a los filisteos hasta la entrada de Gat y hasta las puertas de Ecrón. Los cadáveres de los filisteos cubrían el camino, desde Saaráyim hasta Gat y Ecrón.

[[first-samuel-17-53]]
^53^ Cuando los hijos de Israel regresaron de perseguir sañudamente a los filisteos, saquearon el campamento.

[[first-samuel-17-54]]
^54^ Tomó David la cabeza del filisteo, y la llevó a Jerusalén; pero sus armas las colocó en su tienda.

[[first-samuel-17-55]]
^55^ Cuando Saúl vio a David salir al encuentro del filisteo, preguntó a Abner, jefe del ejército: «¿De quién es hijo este muchacho, Abner?» Abner respondió: «Por tu vida, oh rey, que no lo sé».

[[first-samuel-17-56]]
^56^ El rey dijo: «Pregunta de quién es hijo este muchacho».

[[first-samuel-17-57]]
^57^ Cuando volvió David de matar al filisteo, le tomó Abner y le llevó ante Saúl con la cabeza del filisteo en la mano .

[[first-samuel-17-58]]
^58^ Saúl le preguntó: «¿De quién eres hijo, muchacho?» David respondió: «De tu siervo Jesé, de Belén».
[[first-samuel-18]]
== Capítulo 18

[[first-samuel-18-1]]
^1^ En acabando de hablar David a Saúl, el alma de Jonatán se apegó al alma de David, y le amó Jonatán como a sí mismo.

[[first-samuel-18-2]]
^2^ Le retuvo Saúl aquel día y no le permitió regresar a casa de su padre.

[[first-samuel-18-3]]
^3^ Hizo Jonatán alianza con David, pues le amaba como a sí mismo.

[[first-samuel-18-4]]
^4^ Se quitó Jonatán el manto que llevaba y se lo dio a David, su vestido y también su espada, su arco y su cinturón.

[[first-samuel-18-5]]
^5^ David lograba éxito en todas las campañas que Saúl le encomendaba, y le puso Saúl al frente de hombres de guerra, y se hizo querer de todo el pueblo, también de los servidores de Saúl.

[[first-samuel-18-6]]
^6^ A su regreso, cuando volvió David de matar al filisteo, salían las mujeres de todas la ciudades de Israel al encuentro del rey Saúl para cantar danzando al son de adufes y triángulos con cantos de alegria.

[[first-samuel-18-7]]
^7^ Las mujeres, danzando, cantaban a coro: «Saúl mató sus millares y David sus miríadas.

[[first-samuel-18-8]]
^8^ Irritóse mucho Saúl y le disgustó el suceso, pues decía: «Dan miríadas a David y a mí millares; sólo le falta ser rey».

[[first-samuel-18-9]]
^9^ Y desde aquel día en adelante miraba Saúl a David con ojos de envidia.

[[first-samuel-18-10]]
^10^ Al día siguiente se apoderó de Saúl un espíritu malo de Dios y deliraba en medio de la casa; David tocaba como otras veces. Tenía Saúl la lanza en la mano.

[[first-samuel-18-11]]
^11^ Blandió Saúl la lanza y dijo: «Voy a clavar a David en la pared». Pero David le esquivó dos veces.

[[first-samuel-18-12]]
^12^ Temía Saúl a David porque Yahveh estaba con David y de Saúl se había apartado

[[first-samuel-18-13]]
^13^ y le alejó Saúl de junto a sí, nombrándole jefe de mil y entraba y salía a la cabeza de la tropa.

[[first-samuel-18-14]]
^14^ David ejecutaba con éxito todas sus empresas y Yahveh estaba con él.

[[first-samuel-18-15]]
^15^ Viendo Saúl que tenía mucho éxito le temió.

[[first-samuel-18-16]]
^16^ Todo Israel y Judá quería a David, pues salía y entraba a la cabeza de ellos.

[[first-samuel-18-17]]
^17^ Dijo Saúl a David: «Voy a darte por mujer a mi hija mayor Merab, tan sólo con que me seas valeroso y luches las batallas de Yahveh». Saúl se había dicho: «Que no muera por mi mano, sino por mano de los filisteos».

[[first-samuel-18-18]]
^18^ Dijo David a Saúl: «¿Quién soy yo y cuál es mi linaje, la casa de mi padre en Israel, para ser yerno del rey?»

[[first-samuel-18-19]]
^19^ Pero cuando llegó el tiempo de entregar a Merab, la hija de Saúl, a David, fue entregada a Adriel de Mejolá.

[[first-samuel-18-20]]
^20^ Mikal, hija de Saúl, se enamoró de David; se lo dijeron a Saúl y le agradó la noticia.

[[first-samuel-18-21]]
^21^ Dijo Saúl: «Se la entregaré, pero será para él un lazo, pues caerá sobre él la mano de los filisteos». (Saúl, pues, dijo dos veces a David: «Ahora serás mi yerno».)

[[first-samuel-18-22]]
^22^ Ordenó Saúl a sus servidores: «Insinuad a David: Mira que el rey te estima; también te estiman todos sus servidores; procura ser yerno del rey».

[[first-samuel-18-23]]
^23^ Los servidores de Saúl dijeron estas palabras a oídos de David y David replicó: «¿Os parece sencillo ser yerno del rey? Yo soy un hombre pobre y ruin».

[[first-samuel-18-24]]
^24^ Comunicaron a Saúl sus servidores: «Estas palabras ha dicho David».

[[first-samuel-18-25]]
^25^ Respondió Saúl: «Decid así a David: No quiere el rey dote, sino cien prepucios de filisteos para vengarse de los enemigos del rey». Tramaba el rey hacer sucumbir a David a manos de los filisteos.

[[first-samuel-18-26]]
^26^ Los servidores comunicaron a David estas palabras y la cosa pareció bien a David para llegar a ser yerno del rey. No se había cumplido el plazo,

[[first-samuel-18-27]]
^27^ cuando se levantó David y partió con sus hombres. Mató a los filisteos doscientos hombres y trajo David sus prepucios que entregó cumplidamente al rey para ser yerno del rey. Saúl le dio a su hija Mikal por mujer.

[[first-samuel-18-28]]
^28^ Temió Saúl, pues sabía que Yahveh estaba con David y que toda la casa de Israel le amaba.

[[first-samuel-18-29]]
^29^ Aumentó el temor de Saúl hacia David y fue siempre hostil a David.

[[first-samuel-18-30]]
^30^ Salían los jefes de los filisteos, pero en todas sus incursiones obtenía David más éxito que los demás servidores de Saúl, y su nombre se hizo muy famoso.
[[first-samuel-19]]
== Capítulo 19

[[first-samuel-19-1]]
^1^ Saúl dijo a su hijo Jonatán y a todos sus servidores que haría morir a David; pero Jonatán, hijo de Saúl, amaba mucho a David,

[[first-samuel-19-2]]
^2^ y avisó Jonatán a David diciéndole: «Mi padre Saúl te busca para matarte. Anda sobre aviso mañana por la mañana; retírate a un lugar oculto y escóndete.

[[first-samuel-19-3]]
^3^ Yo saldré y estaré junto a mi padre en el campo, donde tú estés, y hablaré por ti a mi padre; veré lo que hay y te avisaré».

[[first-samuel-19-4]]
^4^ Habló Jonatán a Saúl su padre en favor de David y dijo: «No peque el rey contra su siervo David, porque él no ha pecado contra ti, sino que te ha hecho grandes servicios.

[[first-samuel-19-5]]
^5^ Puso su vida en peligro, mató al filisteo y concedió Yahveh una gran victoria para todo Israel. Tú lo viste y te alegraste. ¿Por qué, pues, vas a pecar contra sangre inocente haciendo morir a David sin motivo?»

[[first-samuel-19-6]]
^6^ Escuchó Saúl las palabras de Jonatán y juró: «¡Vive Yahveh!, no morirá».

[[first-samuel-19-7]]
^7^ Llamó entonces Jonatán a David, le contó todas estas palabras y llevó a David donde Saúl, y se quedó a su servicio como antes.

[[first-samuel-19-8]]
^8^ Reanudada la guerra, partió David para combatir a los filisteos, les causó una gran derrota y huyeron ante él.

[[first-samuel-19-9]]
^9^ Se apoderó de Saúl un espíritu malo de Yahveh; estaba sentado en medio de la casa con su lanza en su mano y David tocaba.

[[first-samuel-19-10]]
^10^ Intentó Saúl clavar con su lanza a David en la pared; esquivó David a Saúl y la lanza se clavó en la pared; huyó David y se puso a salvo. Aquella misma noche

[[first-samuel-19-11]]
^11^ envió Saúl gente a la casa de David para vigilarle y matarle por la mañana, pero su mujer Mikal advirtió a David: «Si no te pones a salvo esta misma noche, mañana morirás».

[[first-samuel-19-12]]
^12^ Mikal hizo bajar a David por la ventana. El partió y huyó poniéndose a salvo.

[[first-samuel-19-13]]
^13^ Tomó Mikal uno de los terafim y lo puso en el lecho, colocó una estera de pelos de cabra a la cabecera y la cubrió con un vestido.

[[first-samuel-19-14]]
^14^ Cuando Saúl mandó gente para prender a David, ella dijo: «Está enfermo».

[[first-samuel-19-15]]
^15^ Pero Saúl envió de nuevo los emisarios para ver a David y les dijo: «Traédmelo en su lecho, para matarlo».

[[first-samuel-19-16]]
^16^ Entraron los enviados y hallaron un terafim en el lecho y la estera de pelos de cabra en la cabecera.

[[first-samuel-19-17]]
^17^ Dijo Saúl a Mikal: «¿Por qué me has engañado y has dejado escapar a mi enemigo para que se salve?» Respondió Mikal a Saúl: «El me dijo: déjame escapar o te mato».

[[first-samuel-19-18]]
^18^ Huyó, pues, David y se puso a salvo, yéndose a donde Samuel, en Ramá, y le contó cuanto Saúl le había hecho. Después, él y Samuel se fueron a habitar en las celdas.

[[first-samuel-19-19]]
^19^ Avisaron a Saúl: «Mira, David está en las celdas de Ramá».

[[first-samuel-19-20]]
^20^ Mandó Saúl emisarios para prender a David; vieron éstos la agrupación de los profetas en trance de profetizar, con Samuel a la cabeza. Vino sobre los emisarios de Saúl el espíritu de Dios y también ellos se pusieron en trance.

[[first-samuel-19-21]]
^21^ Se lo comunicaron a Saúl y envió nuevos emisarios que también se pusieron en trance. Saúl volvió a enviar mensajeros por tercera vez y también éstos se pusieron en trance.

[[first-samuel-19-22]]
^22^ Entonces partió él mismo para Ramá y llegó a la gran cisterna de la era que está en Seku y preguntó: «¿Dónde están Samuel y David?», y le dijeron: «Están en las celdas de Ramá».

[[first-samuel-19-23]]
^23^ Se fue de allí a las celdas de Ramá y vino también sobre él el espíritu de Dios e iba caminando en trance hasta que llegó a las celdas de Ramá.

[[first-samuel-19-24]]
^24^ También él se quitó sus vestidos y se puso en trance profético ante Samuel, y quedó desnudo en tierra todo aquel día y toda aquella noche, por lo que se suele decir: «¿Conque también Saúl entre los profetas?»
[[first-samuel-20]]
== Capítulo 20

[[first-samuel-20-1]]
^1^ Huyó David de las celdas de Ramá y se fue a decir a Jonatán: «¿Qué he hecho, cuál es mi falta y en qué he pecado contra tu padre para que busque mi muerte?»

[[first-samuel-20-2]]
^2^ Jonatán le dijo: «De ninguna manera, no morirás. Mi padre no hace ninguna cosa, grande o pequeña, sin descubrírmela; ¿por qué me había de ocultar mi padre este asunto? ¡No puede ser!»

[[first-samuel-20-3]]
^3^ Pero David volvió a jurar: «Save muy bien tu padre que me tienes mucho afecto y se ha dicho: “Que no lo sepa Jonatán para que no se apene.” Y, con todo, por Yahveh y por tu vida, que no hay más que un paso entre yo y la muerte».

[[first-samuel-20-4]]
^4^ Dijo Jonatán a David: «Dime lo que deseas y te lo haré».

[[first-samuel-20-5]]
^5^ Dijo David a Jonatán: «Mira, mañana es el novilunio; yo tendría que sentarme con el rey a comer, pero tú me dejarás marchar y me esconderé en el campo hasta la noche.

[[first-samuel-20-6]]
^6^ Si tu padre nota mi ausencia, dirás: “David me ha pedido con insistencia que le deje hacer una escapada a Belén, su ciudad, porque se celebra el sacrificio anual de toda la familia.”

[[first-samuel-20-7]]
^7^ Si tu padre dice: “Está bien,” tu siervo está a salvo; pero si se enfurece, sabrás que por su parte está decretada la ruina.

[[first-samuel-20-8]]
^8^ Haz este favor a tu siervo ya que hiciste que tu siervo estableciera contigo alianza de Yahveh; si hay falta en mí, dame tú mismo la muerte; ¿para qué llevarme hasta tu padre?»

[[first-samuel-20-9]]
^9^ Respondió Jonatán: «¡Lojos de ti! Si yo supiera con certeza que por parte de mi padre está decretado que venga la ruina sobre ti, ¿no te lo avisaría?»

[[first-samuel-20-10]]
^10^ Respondió David a Jonatán: «¿Quién me avisará si tu padre te responde con aspereza?»

[[first-samuel-20-11]]
^11^ Respondió Jonatán a David: «Ven, salgamos al campo». Y salieron ambos al campo.

[[first-samuel-20-12]]
^12^ Dijo Jonatán a David: «Por Yahveh, Dios de Israel, te juro que mañana a esta misma hora sondearé a mi padre; si la cosa se pone bien para David y no envío quien te lo haga saber,

[[first-samuel-20-13]]
^13^ que Yahveh haga esto a Jonatán y añada esto otro. Si mi padre decide hacerte mal, te lo haré saber para que te pongas a salvo y vayas en paz. Y que Yahveh sea contigo como lo fue con mi padre.

[[first-samuel-20-14]]
^14^ Si para entonces estoy vivo todavía, usa conmigo la bondad de Yahveh y, si muerto,

[[first-samuel-20-15]]
^15^ nunca apartes tu misericordia de mi casa. Y cuando Yahveh haya exterminado a los enemigos de David de la faz de la tierra,

[[first-samuel-20-16]]
^16^ que no sea exterminado Jonatán con la casa de Saúl; de lo contrario, que Yahveh pida cuentas a David».

[[first-samuel-20-17]]
^17^ Juró de nuevo Jonatán a David por el amor que le tenía, pues le amaba como a sí mismo.

[[first-samuel-20-18]]
^18^ Jonatán le dijo: «Mañana es novilunio y se notará tu ausencia, porque mirarán tu asiento.

[[first-samuel-20-19]]
^19^ Pasado mañana se notará más; tú irás al sitio en que te escondiste el día del suceso aquel, y te pones junto a la loma que tú sabes.

[[first-samuel-20-20]]
^20^ Ese mismo día iré a lanzar flechas por esa parte, como para tirar al blanco.

[[first-samuel-20-21]]
^21^ Mandaré al muchacho: “Anda, busca la flecha.” Si digo al muchacho: “La flecha está más acá de ti, tómala,” vienes, porque todo va bien para ti y no hay nada, por Yahveh.

[[first-samuel-20-22]]
^22^ Pero si digo al muchacho: “La flecha está más allá de ti,” vete, porque Yahveh quiere que te vayas.

[[first-samuel-20-23]]
^23^ Cuanto a la palabra que tú y yo tenemos hablada, mira, Yahveh está entre los dos para siempre».

[[first-samuel-20-24]]
^24^ David se escondió en el campo. Llegado el novilunio, el rey se puso a la mesa para comer.

[[first-samuel-20-25]]
^25^ Se sentó el rey en su asiento, como de costumbre, en el asiento de la pared; Jonatán se sentó enfrente y Abner al lado de Saúl; el asiento de David quedó vacío.

[[first-samuel-20-26]]
^26^ Saúl no dijo nada aquel día, porque pensó: «Será un accidente, no estará puro por no haberse purificado».

[[first-samuel-20-27]]
^27^ Al día siguiente del novilunio, el segundo día, se fijaron en el asiento de David, y Saúl dijo a su hijo Jonatán: ¿Por qué no ha venido a comer ni ayer ni hoy el hijo de Jesé?»

[[first-samuel-20-28]]
^28^ Jonatán respondió a Saúl: «David me pidió con insistencia poder ir a Belén.

[[first-samuel-20-29]]
^29^ Me dijo: “Déjame ir, por favor, porque es nuestro sacrificio de familia en la ciudad y mis hermanos me han reclamado. Así que, si he hallado gracia a tus ojos, déjame hacer una escapada para ver a mis hermanos.” Por esto no ha venido a la mesa del rey».

[[first-samuel-20-30]]
^30^ Se encendió la cólera de Saúl contra Jonatán y le dijo: «¡Hijo de una perdida! ¿Acaso no sé yo que prefieres al hijo de Jesé para vergüenza tuya y vergüenza de la desnudez de tu madre?

[[first-samuel-20-31]]
^31^ Pues mientras viva sobre el suelo el hijo de Jesé, no estarás a salvo ni tú ni tu realeza; así que manda a buscarlo y tráemelo, porque es reo de muerte».

[[first-samuel-20-32]]
^32^ Respondió Jonatán a su padre Saúl y le dijo: «¿Por qué ha de morir? ¿Qué ha hecho?»

[[first-samuel-20-33]]
^33^ Blandió Saúl su lanza contra él para herirle y comprendió Jonatán que por parte de su padre la muerte de David era cosa decidida.

[[first-samuel-20-34]]
^34^ Se levantó Jonatán de la mesa ardiendo en ira y no comió el segundo día del novilunio, pues estaba afligido por David, porque su padre le había injuriado.

[[first-samuel-20-35]]
^35^ A la mañana siguiente salió Jonatán con un muchacho al campo, a la hora acordada con David.

[[first-samuel-20-36]]
^36^ Dijo al muchacho: «Corre a buscar las flechas que voy a tirar». Corrió el muchacho, y entonces Jonatán lanzó las flechas más allá de él.

[[first-samuel-20-37]]
^37^ Cuando el muchacho llegaba al lugar donde había lanzado la flecha Jonatán, éste gritó detrás de él: «¿ Acaso no está la flecha más allá de ti?»,

[[first-samuel-20-38]]
^38^ y siguió gritando detrás del muchacho: «Pronto, date prisa, no te detengas». Tomó el muchacho de Jonatán la flecha y volvió donde su señor.

[[first-samuel-20-39]]
^39^ El muchacho no se enteró de nada. Solamente lo entendían Jonatán y David.

[[first-samuel-20-40]]
^40^ Dio Jonatán sus armas al muchacho que estaba con él y le dijo: «Anda, llévalas a la ciudad».

[[first-samuel-20-41]]
^41^ Se marchó el muchacho y David se levantó de junto a la loma y, cayendo sobre su rostro en tierra, se postró tres veces. Se abrazaron los dos y lloraron copiosamente.

[[first-samuel-20-42]]
^42^ Dijo Jonatán a David: Vete en paz, ya que nos hemos jurado en nombre de Yahveh: “Que Yahveh esté entre tú y yo, entre mi descendencia y la tuya para siempre.”»
[[first-samuel-21]]
== Capítulo 21

[[first-samuel-21-1]]
^1^ Se levantó David y se fue, y Jonatán volvió a la ciudad.

[[first-samuel-21-2]]
^2^ Llegó David a Nob, donde el sacerdote Ajimélek; vino Ajimélek temblando al encuentro de David y le preguntó: «Por qué vienes solo y no hay nadie contigo?»

[[first-samuel-21-3]]
^3^ Respondió David al sacerdote Ajimélek: «El rey me ha dado una orden y me ha dicho: «Que nadie sepa el asunto a que te mando y lo que te ordeno». A los muchachos los he citado en tal lugar.

[[first-samuel-21-4]]
^4^ Así pues, ¿qué tienes a mano? Dame cinco panes o lo que haya».

[[first-samuel-21-5]]
^5^ Respondió el sacerdote a David: «No tengo a mano pan profano, pero hay pan consagrado, si es que los muchachos se han abstenido al menos del trato con mujeres».

[[first-samuel-21-6]]
^6^ Respondió David al sacerdote:» Ciertamente que la mujer nos está prohibida, como siempre que salgo a campaña, y los cuerpos de los muchachos están puros; aunque es un viaje profano, cierto que hoy sus cuerpos están puros».

[[first-samuel-21-7]]
^7^ Diole entonces el sacerdote panes consagrados, porque no había allí otro pan sino el pan de la presencia, el retirado de delante de Yahveh para colocar pan reciente el día que tocaba retirarlo.

[[first-samuel-21-8]]
^8^ Estaba allí aquel día uno de los servidores de Saúl, detenido ante Yahveh; se llamaba Doeg, edomita, el más robusto de los pastores de Saúl.

[[first-samuel-21-9]]
^9^ Dijo David a Ajimélek: «¿No tienes aquí a mano una lanza o una espada? Porque ni siquera he cogido mi espada y mis armas, pues urgía la orden del rey».

[[first-samuel-21-10]]
^10^ Respondió el sacerdote: «Ahí está la espada de Goliat el filisteo que mataste en el valle del Terebinto, envuelta en un paño detrás del efod; si la quieres tómala; fuera de ésta, no hay otra». Dijo David: «Ninguna mejor. Dámela».

[[first-samuel-21-11]]
^11^ Se levantó David y huyó aquel día de Saúl, yendo donde Akís, rey de Gat.

[[first-samuel-21-12]]
^12^ Los servidores de Akís le dijeron: «¿No es este David, rey de la tierra? ¿No es éste a quien cantaban en corro : Saúl mató sus millares y David sus miríadas?»

[[first-samuel-21-13]]
^13^ Meditó David estas palabras y temió mucho a Akís, rey de Gat.

[[first-samuel-21-14]]
^14^ Y se fingió demente ante sus ojos haciéndose el loco en medio de ellos; tamborileaba sobre el batiente de la puerta y dejaba caer la saliva sobre su barba.

[[first-samuel-21-15]]
^15^ Dijo pues Akís a sus servidores: «Mirad, este hombre está loco. ¿Para qué me lo habéis traído?

[[first-samuel-21-16]]
^16^ ¿Es que me hacen falta locos, que me habéis traído a este para que haga el loco a mi costa? ¿Va a entrar éste en mi casa?»
[[first-samuel-22]]
== Capítulo 22

[[first-samuel-22-1]]
^1^ Yéndose de allí David se refugió en la caverna de Adullam. Lo supieron sus hermanos y toda la casa de su padre y bajaron allí, junto a él.

[[first-samuel-22-2]]
^2^ Todos los entrampados y desesperados se unieron a él y fue jefe de ellos. Había con él unos cuatrocientos hombres.

[[first-samuel-22-3]]
^3^ De allí se fue David a Mispé de Moab y dijo al rey de Moab: «Permite que mi padre y mi madre se queden con vosostros hasta que yo sepa qué va a hacer conmigo Dios».

[[first-samuel-22-4]]
^4^ Los dejó con el rey de Moab, y se quedaron con él todo el tiempo que David estuvo en el refugio.

[[first-samuel-22-5]]
^5^ El profeta Gad dijo a David: «No te quedes en el refugio. Vete y penetra en las tierras de Judá». Partió David y entró en el bosque de Jéret.

[[first-samuel-22-6]]
^6^ Oyó Saúl que David y los hombres que estaban con él habían sido descubiertos. Estaba Saúl en Guibeá, en el alto, debajo del tamarisco, con la lanza en la mano, rodeado de todos sus servidores.

[[first-samuel-22-7]]
^7^ Dijo Saúl a todos los servidores que le rodeaban: «Oídme todos, benjaminitas: ¿también a cada uno de vosotros os va a dar el hijo de Jesé campos y viñas y os va a nombrar a todos jefes de millares y jefes de cien,

[[first-samuel-22-8]]
^8^ pues conspiráis todos contra mí y no ha habido quien me descubriera la alianza de mi hijo con el hijo de Jesé, nadie que se compadeciera de mí y me avisara que mi hijo hacía que mi servidor atentase contra mí, como ocurre hoy mismo?»

[[first-samuel-22-9]]
^9^ Respondió Doeg el edomita, que estaba entre los servidores de Saúl: «Yo he visto al hijo de Jesé venir a Nob, donde Ajimélek, hijo de Ajitub.

[[first-samuel-22-10]]
^10^ Consultó por él a Yahveh, le dio víveres e incluso llegó a entregarle la espada de Goliat el filisteo».

[[first-samuel-22-11]]
^11^ Mandó el rey llamar al sacerdote Ajimélek, hijo de Ajitub, y a toda la casa de su padre, a los sacerdotes que había en Nob, y vinieron todos donde el rey.

[[first-samuel-22-12]]
^12^ Dijo Saúl: «Oye, hijo de Ajitub». Este respondió: «Aquí estoy, mi señor».

[[first-samuel-22-13]]
^13^ Díjole Saúl: «¿Por qué conspiráis contra mí tú y el hijo de Jesé, pues le diste pan y una espada y consultaste a Dios por él, para que se alzase contra mí, como ahora está sucediendo?»

[[first-samuel-22-14]]
^14^ Respondió Ajimélek al rey: «¿Y quién, entre todos tus servidores, es como David, el fiel, el yerno del rey y el jefe de tu guardia personal y honrado en tu propia casa?

[[first-samuel-22-15]]
^15^ ¿Es que he comenzado hoy a consultar a Dios por él? ¡Líbreme Dios! No achaque el rey a su siervo y a toda la casa de mi padre una cosa tal porque nada sabe tu siervo de esto, ni poco ni mucho».

[[first-samuel-22-16]]
^16^ Respondió el rey: «Vas a morir, Ajimélek, tú y toda la casa de tu padre».

[[first-samuel-22-17]]
^17^ Dijo pues el rey a los corredores que estaban a su lado: «Acercaos y dad muerte a los sacerdotes de Yahveh porque también su mano está con David y, sabiendo que él huía, no me lo hicieron saber». Pero los servidores del rey no quisieron alzar su mano para herir a los sacerdotes de Yahveh.

[[first-samuel-22-18]]
^18^ Dijo, pues, el rey a Doeg: «Acércate tú y hiere a los sacerdotes». Acercóse Doeg el edomita y él mismo hirió a los sacerdotes; mató aquel día a 85 hombres que llevaban efod de lino.

[[first-samuel-22-19]]
^19^ Saúl pasó a filo de espada a Nob, la ciudad de los sacerdotes, hombres, mujeres, niños y lactantes, bueyes, asnos y ovejas, todos a cuchillo.

[[first-samuel-22-20]]
^20^ Pudo escapar un hijo de Ajimélek, hijo de Ajitub, llamado Abiatar, y huyó donde David.

[[first-samuel-22-21]]
^21^ Abiatar notificó a David que Saúl había dado muerte a los sacerdotes de Yahveh.

[[first-samuel-22-22]]
^22^ David dijo a Abiatar: «Ya sabía yo aquel día que, estando allí Doeg el edomita, no dejaría de avisar a Saúl. Yo soy el responsable de todas las vidas de la casa de tu padre.

[[first-samuel-22-23]]
^23^ Quédate conmigo y no temas, que quien busca tu muerte busca la mía, y junto a mí estarás bien custodiado».
[[first-samuel-23]]
== Capítulo 23

[[first-samuel-23-1]]
^1^ Avisaron a David: «Mira, los filisteos están atacando a Queilá y han saqueado las eras».

[[first-samuel-23-2]]
^2^ Consultó David a Yahveh: «¿Debo ir a batir a esos filiesteos?» Yahveh respondió a David: «Vete, batirás a los filisteos y salvarás a Queilá».

[[first-samuel-23-3]]
^3^ Dijeron a David sus hombres: «Mira, ya en Judá estamos con temor ¿y todavía vamos a marchar a Queilá contra las huestes de los filisteos?»

[[first-samuel-23-4]]
^4^ David consultó de nuevo a Yahveh. Yahveh respondió: «Levántate, baja a Queilá porque he entregado a los filisteos en tus manos».

[[first-samuel-23-5]]
^5^ Fue David con sus hombres a Queilá, atacó a los filisteos, se llevó sus rebaños, les causó una gran mortandad y libró David a los habitantes de Queilá.

[[first-samuel-23-6]]
^6^ Cuando Abiatar, hijo de Ajimélek, huyó a donde David, descendió también a Queilá, llevando en su mano el efod.

[[first-samuel-23-7]]
^7^ Se avisó a Saúl que David había entrado en Queilá y dijo: «Dios lo ha entregado en mis manos, pues él mismo se ha encerrado yendo a una ciudad con puertas y cerrojos».

[[first-samuel-23-8]]
^8^ Llamó Saúl a todo el pueblo a las armas para bajar a Queilá y cercar a David y sus hombres.

[[first-samuel-23-9]]
^9^ Supo David que Saúl tramitaba su ruina, y dijo al sacerdote Abiatar: «Acerca el efod».

[[first-samuel-23-10]]
^10^ Dijo David: «Yahveh, Dios de Israel, tu siervo ha oído que Saúl intenta venir a Queilá para destruir la ciudad por mi causa.

[[first-samuel-23-11]]
^11^ ¿Descenderá de verdad Saúl como tu siervo ha oído? Yahveh, Dios de Israel, hazlo saber por favor a tu siervo». Yahveh respondió: «Bajará».

[[first-samuel-23-12]]
^12^ Preguntó David: «¿Me entregarán los vecinos de Queilá, a mí y a mis hombres, en manos de Saúl?» Respondió Yahveh: «Te entregarán».

[[first-samuel-23-13]]
^13^ Se levantó David con sus hombres, que eran unos trescientos; salieron de Queilá, y anduvieron errando. Avisaron a Saúl que David se había escapado de Queilá y suspendió la expedición.

[[first-samuel-23-14]]
^14^ David se asentó en el desierto, en refugios, y se quedó en la montaña del desierto de Zif; Saúl le buscaba sin cesar, pero Dios no le entregó en sus manos.

[[first-samuel-23-15]]
^15^ Se enteró David de que Saúl había salido a campaña para buscar su muerte. Estaba entonces David en el desierto de Zif, en Jorsa.

[[first-samuel-23-16]]
^16^ Jonatán, hijo de Saúl, se levantó y fue donde David, en Jorsa, le dio ánimos en Dios,

[[first-samuel-23-17]]
^17^ y le dijo: «No temas, porque la mano de Saúl, mi padre, no te alcanzará; tú reinarás sobre Israel y yo seré tu segundo. Hasta mi padre Saúl lo tiene sabido».

[[first-samuel-23-18]]
^18^ Hicieron ambos una alianza ante Yahveh; David se quedó en Jorsa, y Jonatán se volvió a su casa.

[[first-samuel-23-19]]
^19^ Subieron algunos zifitas a Guibeá, donde Saúl, para decirle: «¿No se esconde David entre nosotros, en los refugios de Jorsa, en la colina de Jakilá, que está al sur de la estepa?

[[first-samuel-23-20]]
^20^ Tú deseas con toda tu alma, oh rey, descender. Desciende y es cosa nuestra entregarlo en manos del rey».

[[first-samuel-23-21]]
^21^ Respondió Saúl: «Que Yahveh os bendiga por haberos compadecido de mí.

[[first-samuel-23-22]]
^22^ Id, pues; aseguraos bien, enteraos, mirad el lugar donde se pone su pie y quién le ha visto allí, porque me han dicho que es muy astuto.

[[first-samuel-23-23]]
^23^ Mirad y reconoced todos los escondrijos en que pueda esconderse, y volved a mí cuando estéis seguros y subiré con vosotros, y si está en la comarca le rebuscaré entre todas las familias de Judá».

[[first-samuel-23-24]]
^24^ Se levantaron y se fueron a Zif, precediendo a Saúl. Estaban David y sus hombres en el desierto de Maón, en la llanura, al sur del desierto.

[[first-samuel-23-25]]
^25^ Fue Saúl con sus hombres en su busca; avisaron a David y bajó al tajo que está en el desierto de Maón. Lo oyó Saúl y persiguió a David en el desierto de Maón.

[[first-samuel-23-26]]
^26^ Iba Saúl y sus hombres por un lado de la montaña, y David y sus hombres por el lado de la otra. Huía David a toda prisa ante Saúl, mientras Saúl y sus hombres intentaban pasar a la parte de David y sus hombres para apresarlos,

[[first-samuel-23-27]]
^27^ cuando he aquí que llegó un mensajero a Saúl y le dijo: «Date prisa y ven, porque los filisteos han invadido la tierra».

[[first-samuel-23-28]]
^28^ Abandonó Saúl la persecución de David y marchó al encuentro de los filisteos. Por eso se llamó aquel lugar «Peña de la Separación».
[[first-samuel-24]]
== Capítulo 24

[[first-samuel-24-1]]
^1^ Subió de allí David y se asentó en los refugios de Engadí.

[[first-samuel-24-2]]
^2^ Cuando regresó Saúl de perseguir a los filisteos, le avisaron: «David está en el desierto de Engadí».

[[first-samuel-24-3]]
^3^ Tomó entonces Saúl 3.000 hombres selectos de todo Israel y partió en busca de David y de sus hombres al este del roquedal de Yeelim.

[[first-samuel-24-4]]
^4^ Llegó a unos rediles de ganado junto al camino; había allí una cueva y Saúl entró en ella para hacer sus necesidades. David y sus hombres estaban instalados en el fondo de la cueva.

[[first-samuel-24-5]]
^5^ Los hombres de David le dijeron: «Mira, este es el día que Yahveh te anunció: Yo pongo a tu enemigo en tus manos, haz de él lo que te plazca». Levantóse David y silenciosamente cortó la punta del manto de Saúl.

[[first-samuel-24-6]]
^6^ Después su corazón le latía fuertemente por haber cortado la punta del manto de Saúl,

[[first-samuel-24-7]]
^7^ y dijo a sus hombres: «Yahveh me libre de hacer tal cosa a mi señor y de alzar mi mano contra él, porque es el ungido de Yahveh».

[[first-samuel-24-8]]
^8^ David habló con energía a sus hombres para que no se lanzasen contra Saúl. Saúl marchó de la cueva y continuó su camino,

[[first-samuel-24-9]]
^9^ tras lo cual se levantó David, salió de la cueva y gritó detrás de Saúl: «¡Oh rey, mi señor!» Volvió Saúl la vista, e inclinándose David, rostro en tierra, se postró ante él,

[[first-samuel-24-10]]
^10^ y dijo David a Saúl: «¿Por qué escuchas a las gentes que te dicen: David busca tu ruina?

[[first-samuel-24-11]]
^11^ Hoy mismo han visto tus ojos que Yahveh te ha puesto en mis manos en la cueva, pero no he querido matarte, te he perdonado, pues me he dicho: No alzaré mi mano contra mi señor, porque es el ungido de Yahveh.

[[first-samuel-24-12]]
^12^ Mira, padre mío, mira la punta de tu manto en mi mano; si he cortado la punta de tu manto y no te he matado, reconoce y mira que no hay en mi camino maldad ni crimen, ni he pecado contra ti, mientras que tú me pones insidias para quitarme la vida.

[[first-samuel-24-13]]
^13^ Que juzgue Yahveh entre los dos y que Yahveh me vengue de ti, pero mi mano no te tocará,

[[first-samuel-24-14]]
^14^ pues como dice el antiguo proverbio: De los malos sale malicia, pero mi mano no te tocará.

[[first-samuel-24-15]]
^15^ ¿Contra quién sale el rey de Israel, a quién estás persiguiendo? A un perro muerto, a una pulga.

[[first-samuel-24-16]]
^16^ Que Yahveh juzgue y sentencie entre los dos, que él vea y defienda mi causa y me haga justicia librándome de tu mano».

[[first-samuel-24-17]]
^17^ Cuando David hubo acabado de decir estas palabras a Saúl, dijo Saúl: «¿Es ésta tu voz, hijo mío David?» Y alzando Saúl su voz, rompió a llorar,

[[first-samuel-24-18]]
^18^ y dijo a David: «Más justo eres tú que yo, pues tú me haces beneficios y yo te devuelvo males;

[[first-samuel-24-19]]
^19^ hoy has mostrado tu bondad, pues Yahveh me ha puesto en tus manos y no me has matado.

[[first-samuel-24-20]]
^20^ ¿Qué hombre encuentra a su enemigo y le permite seguir su camino en paz? Que Yahveh te premie por el bien que hoy me has hecho.

[[first-samuel-24-21]]
^21^ Ahora tengo por cierto que reinarás y que el reino de Israel se afirmará en tus manos.

[[first-samuel-24-22]]
^22^ Ahora, pues, júrame por Yahveh que no exterminarás mi descendencia después de mí y que no borrarás mi nombre de la casa de mi padre».

[[first-samuel-24-23]]
^23^ David se lo juró a Saúl. Saúl se fue a su casa y David y sus hombres subieron al refugio.
[[first-samuel-25]]
== Capítulo 25

[[first-samuel-25-1]]
^1^ Samuel murió. Todo Israel se congregó para llorarle y lo sepultaron en su heredad, en Ramá. David se levantó y bajó al desierto de Maón.

[[first-samuel-25-2]]
^2^ Había un hombre en Maón que tenía su hacienda en Carmelo. Era un hombre muy rico; poseía 3.000 ovejas y mil cabras. Estaba entonces en Carmelo, esquilando su rebaño.

[[first-samuel-25-3]]
^3^ El hombre se llamaba Nabal y su mujer se llamaba Abigaíl; ella era muy prudente y hermosa, pero el hombre era duro y de mala conducta. Era calebita.

[[first-samuel-25-4]]
^4^ Supo David en el desierto que Nabal estaba esquilando su rebaño

[[first-samuel-25-5]]
^5^ y mandó diez muchachos diciéndoles: «Subid a Carmelo y llegad donde Nabal y le saludáis en mi nombre,

[[first-samuel-25-6]]
^6^ y hablad así a mi hermano; Salud para tí, salud para tu casa y salud para todo lo tuyo.

[[first-samuel-25-7]]
^7^ He sabido que estás de esquileo; pues bien, tus pastores han estado con nosotros y nunca les hemos molestado ni han echado en falta nada de lo suyo mientras estuvieron en Carmelo.

[[first-samuel-25-8]]
^8^ Pregunta a tus criados y ellos te lo dirán. Que estos muchachos encuentren, pues gracia a tus ojos, ya que hemos venido en un día de fiesta, y dales lo que tengas a mano para tus siervos y tu hijo David.”»

[[first-samuel-25-9]]
^9^ Llegaron los muchachos de David, dijeron a Nabal todas estas palabras en nombre de David y se quedaron esperando.

[[first-samuel-25-10]]
^10^ Pero Nabal respondió a los servidores de David: «¿Quién es David y quién es el hijo de Jesé? Abundan hoy en día los siervos que andan huídos de sus señores.

[[first-samuel-25-11]]
^11^ ¿Voy a tomar acaso mi pan y mi vino y las reses que he sacrificado para los esquiladores y se las voy a dar a unos hombres que no sé de dónde son?»

[[first-samuel-25-12]]
^12^ Los muchachos de David dieron la vuelta y se volvieron por su camino, y en llegando le conmunicaron todas estas palabras.

[[first-samuel-25-13]]
^13^ David dijo a sus hombres: «Que cada uno ciña su espada». Todos ciñeron su espada. También David se ciñó su espada. Subieron detrás de David unos cuatrocientos hombres, quedándose doscientos con el bagaje.

[[first-samuel-25-14]]
^14^ Uno de los servidores avisó a Abigaíl, mujer de Nabal, diciendo: «Mira que David ha enviado mensajeros desde el desierto para saludar a nuestro amo, y se ha lanzado contra ellos.

[[first-samuel-25-15]]
^15^ Sin embargo, esos hombres han sido muy buenos con nosotros, y nada echamos en falta mientras anduvimos con ellos, cuando estábamos en el campo.

[[first-samuel-25-16]]
^16^ Fueron nuestra defensa noche y día todo el tiempo que estuvimos con ellos guardando el ganado.

[[first-samuel-25-17]]
^17^ Date cuenta y mira lo que debes hacer, porque ya está decretada la ruina de nuestro amo y de toda la casa, y es un necio al que nada se puede decir.

[[first-samuel-25-18]]
^18^ Tomó Abigaíl a toda prisa doscientos panes y dos ordres de vino, cinco carneros ya preparados, cinco arrobas de trigo tostado, cien racimos de uvas pasas y doscientos panes de higos secos, y lo cargó sobre unos asnos,

[[first-samuel-25-19]]
^19^ diciendo a sus servidores: «Pasad delante de mí, que yo os sigo». Pero nada dijo a su marido Nabal.

[[first-samuel-25-20]]
^20^ Cuando bajaba ella, montada en el asno, por lo cubierto de la montaña, David y sus hombres bajaban en dirección contraria y se tropezó con ellos.

[[first-samuel-25-21]]
^21^ David se decía: «Muy en vano he guardado en el desierto todo lo de este hombre para que nada de lo suyo le faltase, pues me devuelve mal por bien.

[[first-samuel-25-22]]
^22^ Esto haga Dios a David y esto otro añada si para el alba dejo con vida ni un solo varón de los de Nabal».

[[first-samuel-25-23]]
^23^ Apenas vio a David, se apresuró Abigaíl a bajar del asno y cayendo ante David se postró en tierra, y

[[first-samuel-25-24]]
^24^ arrojándose a sus pies le dijo: «Caiga sobre mí la falta, señor. Deja que tu sierva hable a tus oídos y eschucha las palabras de tu sierva.

[[first-samuel-25-25]]
^25^ No haga caso mi señor de este necio de Nabal; porque le va bien el nombre: necio se llama y la necedad está con él; yo, tu sierva, no vi a los siervos que mi señor había enviado.

[[first-samuel-25-26]]
^26^ Ahora, mi señor, por Yahveh y por tu vida, por Yahveh que te ha impedido derramar sangre y tomarte la justicia por tu propia mano, que sean como Nabal tus enemigos y los que buscan la ruina de mi señor.

[[first-samuel-25-27]]
^27^ Cuanto a este presente que tu sierva ha hecho traer para mi señor, que sea entregado a los muchachos que marchan en pos de mi señor.

[[first-samuel-25-28]]
^28^ Perdona, por favor, la falta de tu sierva, ya que ciertamente hará Yahveh una casa permanente a mi señor, pues mi señor combate las batallas de Yahveh y no vendrá mal sobre ti en toda tu vida.

[[first-samuel-25-29]]
^29^ Y aunque se alza un hombre para perseguirte y buscar tu vida, la vida de mi señor está encerrada en la bolsa de la vida, al lado de Yahveh tu Dios, mientras que la vida de los enemigos de mi señor la volteará en el hueco de la honda.

[[first-samuel-25-30]]
^30^ Cuando haga Yahveh a mi señor todo el bien que te ha prometido y te haya establecido como caudillo de Israel,

[[first-samuel-25-31]]
^31^ que no haya turbación ni remordimiento en el corazón de mi señor por haber derramado sangre inocente y haberse tomado mi señor la justicia por su mano; y cuando Yahveh haya favorecido a mi señor. acuérdase de tu sierva».

[[first-samuel-25-32]]
^32^ David dijo a Abigaíl: «Bendito sea Yahveh, Dios de Israel, que te ha enviado hoy a mi encuentro.

[[first-samuel-25-33]]
^33^ Bendita sea tu prudencia y bendita tú misma que me has impedido derramar sangre y tomarme la justicia por mi mano.

[[first-samuel-25-34]]
^34^ Pero con todo, vive Yahveh, Dios de Israel, que me ha impedido hacerte mal, que de no haberte apresurado a venir a mi encuentro, no le hubiera quedado a Nabal, al romper el alba, ni un solo varón».

[[first-samuel-25-35]]
^35^ Tomó David de mano de ella lo que le traía y le dijo: «Sube en paz a tu casa; mira, he escuchado tu voz y he accedido a tu petición».

[[first-samuel-25-36]]
^36^ Cuando Abigaíl llegó donde Nabal, estaba celebrando en su casa un banquete regio; estaba alegre su corazón y completamente borracho. No le dijo una palabra, ni grande ni pequeña, hasta el lucir del día.

[[first-samuel-25-37]]
^37^ Pero a la mañana, cuando se le pasó el vino a Nabal, le contó su mujer lo sucedido; el corazón se le murió en el pecho y se le quedó como una piedra.

[[first-samuel-25-38]]
^38^ Al cabo de unos diez días hirió Yahveh a Nabal y murió.

[[first-samuel-25-39]]
^39^ Oyó David que Nabal había muerto y dijo: «Bendito sea Yahveh que ha defendido mi causa contra la injuria de Nabal y ha preservado a su siervo de hacer mal. Yahveh ha hecho caer la maldad de Nabal sobre su cabeza». Envió David mensajeros para proponer a Abigaíl que fuera su mujer.

[[first-samuel-25-40]]
^40^ Llegaron los mensajeros de David a casa de Abigaíl en Carmelo y le hablaron diciendo: «David nos envía a ti para tomarte por mujer».

[[first-samuel-25-41]]
^41^ Se levantó ella y se postró rostro en tierra diciendo: «Tu sierva es una esclava para lavar los pies de los siervos de mi señor».

[[first-samuel-25-42]]
^42^ Se levantó Abigaíl apresuradamente, montó en su asno y, seguida de cinco de sus siervas, se fue tras los enviados de David y fue su mujer.

[[first-samuel-25-43]]
^43^ David había tomado también por mujer a Ajinoam de Yizreel y las dos fueron mujeres suyas.

[[first-samuel-25-44]]
^44^ Saúl había dado su hija Mikal, mujer de David, a Paltí, hijo de Layis, de Gallim.
[[first-samuel-26]]
== Capítulo 26

[[first-samuel-26-1]]
^1^ Llegaron los zifitas donde Saúl, en Guibeá, diciendo: «¿Acaso no está escondido David en la colina de Jakilá, hacia el este de la estepa?»

[[first-samuel-26-2]]
^2^ Se levantó Saúl y bajó al desierto de Zif, con tres mil hombres escogidos de Israel, para buscar a David en el desierto de Zif.

[[first-samuel-26-3]]
^3^ Acampó Saúl en la colina de Jakilá, que está al este de la estepa, junto al camino. Andaba David por el desierto y vió que entraba Saúl en el desierto para perseguirle.

[[first-samuel-26-4]]
^4^ Envió David exploradores y supo con seguridad que Saúl había venido.

[[first-samuel-26-5]]
^5^ Se levantó David y llegó al lugar donde acampaba Saúl. Observó el sitio en que estaban acostados Saúl y Abner, hijo de Ner, jefe de su tropa. Dormía Saúl en el círculo del campamento, estando la tropa acampada en derredor de él.

[[first-samuel-26-6]]
^6^ David dirigió la palabra a Ajimélek, hitita, y a Abisay, hijo de Sarvia, hermano de Joab, diciendo: «¿Quién quiere bajar conmigo al campamento, donde Saúl?» Abisay respondió: «Yo bajo contigo».

[[first-samuel-26-7]]
^7^ David y Abisay se dirigieron de noche hacia la tropa. Saúl dormía acostado en el centro del campamento, con su lanza, clavada en tierra, a su cabecera; Abner y el ejército estaban acostados en torno a él.

[[first-samuel-26-8]]
^8^ Dijo entonces Abisay a David: «Hoy ha copado Dios a tu enemigo en tu mano. Déjame que ahora mismo lo clave en tierra con la lanza de un solo golpe. No tendré que repetir».

[[first-samuel-26-9]]
^9^ Pero David dijo a Abisay: «No lo mates. ¿Quién atentó contra el ungido de Yahveh y quedó impune?»

[[first-samuel-26-10]]
^10^ Añadió David: «Vive Yahveh, que ha de ser Yahveh quien le hiera, bien que llegue su día y muera, bien que baje al combate y perezca.

[[first-samuel-26-11]]
^11^ Líbreme Yahveh de levantar mi mano contra el ungido de Yahveh. Ahora toma la lanza de su cabecera y el jarro de agua y vámonos».

[[first-samuel-26-12]]
^12^ Tomó David la lanza y el jarro de la cabecera de Saúl y se fueron. Nadie los vio, nadie se enteró, nadie se despertó. Todos dormían porque se había abatido sobre ellos el sopor profundo de Yahveh.

[[first-samuel-26-13]]
^13^ Pasó David al otro lado y se colocó lejos, en la cumbre del monte, quedando un gran espacio entre ellos.

[[first-samuel-26-14]]
^14^ Gritó David a la gente y a Abner, hijo de Ner, diciendo : «¿No me respondes, Abner?» Respondió Abner: «¿Quién eres tú que me llamas?»

[[first-samuel-26-15]]
^15^ Dijo David a Abner: «¿No eres tú un hombre? ¿Quién como tú en Israel? ¿Por qué, pues, no has custadiado al rey tu señor? Pues uno del pueblo ha entrado para matar al rey, tu señor.

[[first-samuel-26-16]]
^16^ No está bien esto que has hecho. Vive Yahveh que sois reos de muerte por no haber velado sobre vuestro señor, el ungido de Yahveh. Mira ahora. ¿Dónde está la lanza del rey y el jarro del agua que había junto a la cabecera?»

[[first-samuel-26-17]]
^17^ Reconoció Saúl la voz de David y preguntó: «¿Es ésta tu voz, hijo mío David?» Respondió David: «Mi voz es, oh rey, mi señor,»

[[first-samuel-26-18]]
^18^ y añadió: «¿Por qué persigue mi señor a su siervo? ¿Qué he hecho y qué maldad hay en mí?

[[first-samuel-26-19]]
^19^ Que el rey mi señor se digne escuchar ahora las palabras de su siervo. Si es Yahveh quien te excita contra mí, que sea aplacado con una oblación, pero si son los hombres, malditos sean ante Yahveh, porque me expulsan hoy para que no participe en le heredad de Yahveh, diciéndose: «Que vaya a servir a otros dioses».

[[first-samuel-26-20]]
^20^ Que no caiga ahora mi sangre en tierra lejos de la presencia de Yahveh, pues ha salido el rey de Israel a la caza de mi vida como quien persigue una perdiz en los montes».

[[first-samuel-26-21]]
^21^ Respondió Saúl: «He pecado. Vuelve, hijo mío, David, no te haré ya ningún mal, ya que mi vida ha sido hoy preciosa a tus ojos. Me he portado como un necio y estaba totalmente equivocado».

[[first-samuel-26-22]]
^22^ Respondió David: «Aquí está la lanza del rey. Que pase uno de los servidores y la tome.

[[first-samuel-26-23]]
^23^ Yahveh devolverá a cada uno según su justicia y su fidelidad; pues hoy te ha entregado Yahveh en mis manos, pero no he querido alzar mi mano contra el ungido de Yahveh.

[[first-samuel-26-24]]
^24^ De igual modo que tu vida ha sido hoy de gran precio a mis ojos, así será de gran precio la mía a los ojos de Yahveh, de suerte que me libere de toda angustia».

[[first-samuel-26-25]]
^25^ Dijo Saúl a David: «Bendito seas, hijo mío David. Triunfarás en todas tus empresas». Siguió David por su camino y Saúl se volvió a su casa.
[[first-samuel-27]]
== Capítulo 27

[[first-samuel-27-1]]
^1^ David se dijo a sí mismo: «Algún día voy a perecer a manos de Saúl. Lo mejor será refugiarme en tierra de filisteos. Saúl dejará de perseguirme por todos los términos de Israel y escaparé de sus manos».

[[first-samuel-27-2]]
^2^ Levantóse David y pasó, con los seiscientos hombres que tenía, a Akís, hijo de Maok, rey de Gat.

[[first-samuel-27-3]]
^3^ Se asentó David con Akís en Gat, él y sus hombres, cada cual con su familia; David con sus dos mujeres, Ajinoam de Yizreel y Abigaíl, mujer de Nabal, de Carmelo.

[[first-samuel-27-4]]
^4^ Se dio aviso a Saúl que David había huido a Gat y dejó de buscarlo.

[[first-samuel-27-5]]
^5^ Dijo David a Akís: «Si he hallado gracia a tus ojos, que se me asigne un lugar en una de las ciudades del territorio, para residir en ella. ¿Por qué ha de morar tu siervo a tu lado, en la ciudad real?»

[[first-samuel-27-6]]
^6^ Aquel mismo día le asignó Akís Siquelag; por esto Siquelag pertenece hasta el día de hoy a los reyes de Judá.

[[first-samuel-27-7]]
^7^ El número de días que moró David en territorio de los filisteos fue de un año y cuatro meses.

[[first-samuel-27-8]]
^8^ Subía David con su gente y hacía incursiones contra los guesuritas, los guirzitas y los amalecitas, pues éstos son los habitantes de la región, desde Telam, yendo hacia Sur, hasta la tierra de Egipto.

[[first-samuel-27-9]]
^9^ Devastaba David la tierra y no dejaba con vida hombre ni mujer; se apoderaba de las ovejas y bueyes, asnos y camellos y vestidos, y se volvía para llevarlos a Akís.

[[first-samuel-27-10]]
^10^ Akís preguntaba: «¿Donde habéis hecho hoy la incursión?», y David respondía: «Contra el Négueb de Judá, contra el Négueb de Yerajmeel, contra el Négueb de los quenitas».

[[first-samuel-27-11]]
^11^ David no dejaba llevar a Gat con vida hombres ni mujeres, pues decía: «No se que den aviso contra nosotros y digan: “Esto ha hecho David.” «De esta forma se comportó David todo el tiempo que moró en territorio de filisteos.

[[first-samuel-27-12]]
^12^ Akís confiaba en David diciéndose: «Seguramente se ha hecho odioso a su pueblo Israel y será mi servidor para siempre».
[[first-samuel-28]]
== Capítulo 28

[[first-samuel-28-1]]
^1^ Por aquellos días reunieron los filisteos sus tropas para ir a la guerra contra Israel; Akís dijo a David: «Bien sabes que debes venir a la guerra conmigo, tú y tus hombres».

[[first-samuel-28-2]]
^2^ Respondió David a Akís: «Ahora vas a saber bien lo que va a hacer tu servidor». Dijo Akís a David: «Con seguridad te haré mi guardia personal para siempre».

[[first-samuel-28-3]]
^3^ Samuel había muerto, todo Israel le había llorado y fué sepultado en Ramá, su ciudad. Saúl había echado del país a los nigromantes y adivinos.

[[first-samuel-28-4]]
^4^ Habiéndose reunido los filisteos vinieron a acampar en Sunem. Reunió Saúl a todo Israel y acampó en Gelboé.

[[first-samuel-28-5]]
^5^ Vio Saúl el campamento de los filisteos y tuvo miedo, temblando sobremanera su corazón.

[[first-samuel-28-6]]
^6^ Consultó Saúl a Yahveh, pero Yahveh no le respondió ni por sueños ni por los urim, ni por los profetas.

[[first-samuel-28-7]]
^7^ Dijo Saúl a sus servidores: «Buscadme una nigromante para que vaya a consultarla». Dijéronle sus servidores: «Aquí mismo, en Endor, hay una nigromante».

[[first-samuel-28-8]]
^8^ Se disfrazó Saúl poniéndose otras ropas y fue con dos de sus hombres; llegó donde la mujer de noche y dijo: «Adivíname por un muerto y evócame el que yo te diga».

[[first-samuel-28-9]]
^9^ La mujer le respondió: «Bien sabes lo que hizo Saúl, que suprimió de esta tierra a los nigromantes y adivinos. ¿Por qué tiendes un lazo a mi vida para hacerme morir?»

[[first-samuel-28-10]]
^10^ Saúl juró por Yahveh diciendo: «¡Vive Yahveh! Ningún castigo te vendrá por este hecho».

[[first-samuel-28-11]]
^11^ La mujer dijo: «¿A quién debo invocar para ti?» Respondió: «Evócame a Samuel».

[[first-samuel-28-12]]
^12^ Vio entonces la mujer a Samuel y lanzó un gran grito. Dijo la mujer a Saúl: «¿Por qué me has engañado? ¡Tú eres Saúl¡»

[[first-samuel-28-13]]
^13^ El rey le dijo: «No temas, pero ¿qué has visto?» La mujer respondió a Saúl: «Veo un espectro que sube de la tierra».

[[first-samuel-28-14]]
^14^ Saúl le preguntó: «¿Qué aspecto tiene?» Ella respondió: «Es un hombre anciano que sube envuelto en su manto». Comprendió Saúl que era Samuel y cayendo rostro en tierra se postró.

[[first-samuel-28-15]]
^15^ Samuel dijo a Saúl: «¿Por qué me perturbas evocándome?» Respondió Saúl: «Estoy en grande augustia; los filisteos mueven guerra contra mí, Dios se ha apartado de mí y ya no me responde ni por los profetas ni en sueños. Te he llamado para que me indiques lo que debo hacer».

[[first-samuel-28-16]]
^16^ Dijo Samuel: «¿Para qué me consultas si Yahveh se ha separado de ti y se ha pasado a otro?

[[first-samuel-28-17]]
^17^ Yahveh te ha cumplido lo que dijo por mi boca: ha arrancado Yahveh el reino de tu mano y se lo ha dado a otro, a David,

[[first-samuel-28-18]]
^18^ porque no oíste la indignación de su ira contra Amalec. Por eso te trata hoy Yahveh de esta manera.

[[first-samuel-28-19]]
^19^ También a Israel entregará Yahveh en manos de los filisteos. Mañana tú y tus hijos estaréis conmigo. Yahveh ha entregado también el ejército de Israel en manos de los filisteos».

[[first-samuel-28-20]]
^20^ Al instante Saúl cayó en tierra cuan largo era. Estaba aterrado por las palabras de Samuel: se hallaba, además, sin fuerzas, porque no había comido nada en todo el día y toda la noche.

[[first-samuel-28-21]]
^21^ Acercóse la mujer donde Saúl, y viendo que estaba tan conturbado, le dijo: «Tu sierva ha escuchado tu voz y he puesto mi vida en peligro por obedecer las órdenes que me diste.

[[first-samuel-28-22]]
^22^ Escucha, pues, tú también la voz de tu sierva y permíteme que te sirva un bocado de pan para que comas y tengas fuerzas para ponerte en camino».

[[first-samuel-28-23]]
^23^ Saúl se negó diciendo: «No quiero comer». Pero sus servidores, a una con la mujer, le insistieron hasta que accedió. Se levantó del suelo y se sentó en el diván.

[[first-samuel-28-24]]
^24^ Tenía la mujer en casa un ternero cebado y se apresuró a degollarlo. Tomó harina, la amasó y coció unos ázimos.

[[first-samuel-28-25]]
^25^ Lo sirvió a Saúl y sus servidores, comieron y levantandose se marcharon aquella misma noche.
[[first-samuel-29]]
== Capítulo 29

[[first-samuel-29-1]]
^1^ Los filisteos concentraron todo su ejército en Afeq, mientras que los israelitas acamparon en la fuente que hay en Yizreel.

[[first-samuel-29-2]]
^2^ Los tiranos de los filisteos marcharon al frente de las centurias y millares; David y sus hombres marchaban a retaguardia con Akís.

[[first-samuel-29-3]]
^3^ Dijeron los jefes de los filisteos: «¿Qué hacen estos hebreos?» Akís respondió a los jefes de los filisteos: «Es David, el servidor de Saúl, el rey de Israel; ha estado conmigo un año o dos y no he hallado nada contra él desde el día en que vino a mí hasta hoy».

[[first-samuel-29-4]]
^4^ Pero los tiranos de los filisteos se irritaron contra él y le dijeron: «Manda regresar a ese hombre y que se vuelva al lugar que le señalaste. Que no baje con nosotros a la batalla, no sea que se vuelva contra nosotros durante la lucha. ¿Cómo se ganará éste el favor de su dueño mejor que con las cabezas de estos hombres?

[[first-samuel-29-5]]
^5^ No es éste David de quien cantaban en coro: Saúl mató sus millares y David sus miríadas?»

[[first-samuel-29-6]]
^6^ Akís llamó a David y le dijo: «! Vive Yahveh! que tú eres leal y me hubiera gustado que salieras y entraras conmigo en el campamento, pues nada malo he hallado en ti desde el día en que viniste a mí hasta hoy, pero no eres bien visto por los tiranos.

[[first-samuel-29-7]]
^7^ Ahora vuélvete y vete en paz, y así no harás nada malo a los ojos de los tiranos de los filisteos».

[[first-samuel-29-8]]
^8^ David dijo a Akís: «¿Qué he hecho yo y qué has hallado en tu siervo, desde el día en que me puse a tu servicio hasta hoy, para que no pueda ir a luchar contigo contra los enemigos del rey, mi señor?»

[[first-samuel-29-9]]
^9^ Respondió Akís a David: «Bien sabes que me eres grato como un ángel de Dios; pero los tiranos filisteos han dicho: “No bajará al combate con nosotros.”

[[first-samuel-29-10]]
^10^ Levántate, pues, de mañana, con los servidores de tu señor que han venido contigo e id al sitio que os he asignado. No guardes resentimiento en tu corazón, porque me eres grato. Levantaos de mañana y partid en cuanto sea de día».

[[first-samuel-29-11]]
^11^ David y sus hombres se levantaron temprano para partir por la mañana y volverse a la tierra de los filisteos. Los filisteos por su parte subieron a Yizreel.
[[first-samuel-30]]
== Capítulo 30

[[first-samuel-30-1]]
^1^ Cuando David y sus hombres llegaron al tercer día a Siquelag, los amalecitas habían hecho una incursión contra el Négueb y contra Siquelag, y habían irrumpido en Siquelag incendiándola,

[[first-samuel-30-2]]
^2^ y llevándose las mujeres y cuanto allí había, pequeños y grandes. No mataron a nadie, sino que se los llevaron cautivos y se fueron por su camino.

[[first-samuel-30-3]]
^3^ Cuando David y sus hombres llegaron a la ciudad, se encontraron con que estaba incendiada, y sus mujeres, sus hijos y sus hijas habían sido llevados.

[[first-samuel-30-4]]
^4^ David y las tropas que con él estaban alzaron su voz y lloraron hasta quedar sin aliento.

[[first-samuel-30-5]]
^5^ Habían sido llevadas las dos mujeres de David, Ajinoam de Yizreel y Abigaíl, mujer de Nabal de Carmelo.

[[first-samuel-30-6]]
^6^ David se hallaba en grave apuro porque la gente hablaba de apedrearlo, pues el alma de todo el pueblo estaba llena de amargura, cada uno por sus hijos y sus hijas. Pero David halló fortaleza en Yahveh su Dios.

[[first-samuel-30-7]]
^7^ Dijo David al sacerdote Abiatar, hijo de Ajimélek: «Acércame el efod». Abiatar acercó el efod a David.

[[first-samuel-30-8]]
^8^ Consultó David a Yahveh diciendo: «¿Debo perseguir a esta banda? ¿Le daré alcance?» Le contestó: «Persíguela, porque de cierto la alcanzarás y librarás a los cautivos».

[[first-samuel-30-9]]
^9^ Partió David con los seiscientos hombres que tenía y llegaron al torrente Besor.

[[first-samuel-30-10]]
^10^ Continuó David la persecución con cuatrocientos hombres, quedándose doscientos que estaban demasiado fatigados para atravesar el torrente Besor.

[[first-samuel-30-11]]
^11^ Encontraron en el campo a un egipcio y lo llevaron a David. Le dieron pan, que él comió, y agua para beber.

[[first-samuel-30-12]]
^12^ Diéronle también un trozo de pan de higos secos y dos racimos de pasas. Cuando hubo comido, recobró su espíritu, pues había estado tres días y tres noches sin comer pan ni beber agua.

[[first-samuel-30-13]]
^13^ David le preguntó: «¿A quién perteneces y de dónde eres?» Respondió: «Soy un muchacho egipcio, esclavo de un amalecita, pero mi dueño me abandonó porque me puse enfermo hace tres días.

[[first-samuel-30-14]]
^14^ Hemos hecho una incursión contra el Négueb de los kereteos y el de Judá y contra el Négueb de Caleb, incendiando Siquelag».

[[first-samuel-30-15]]
^15^ Díjole David: «¿Podrías guiarme hacia esa banda?» Respondió: «Júrame por Dios que no me matarás y que no me entregarás en manos de mi dueño, y te guiaré hacia esa banda».

[[first-samuel-30-16]]
^16^ Les guió, y los hallaron desparramados por todo el campo, comiendo, bebiendo y bailando por el gran botín que habían tomado en tierra de filisteos y en tierra de Judá.

[[first-samuel-30-17]]
^17^ David los batió desde el alba al anochecer; sólo se salvaron de entre ellos cuatrocientos jóvenes que montaron en camellos y huyeron.

[[first-samuel-30-18]]
^18^ Salvó David todo lo que los amalecitas habían capturado. También rescató David a sus dos mujeres.

[[first-samuel-30-19]]
^19^ Nada les faltó, ni pequeño ni grande, ni el botín, ni sus hijos, ni sus hijas, ni nada de cuanto les habían capturado. David se llevó todo.

[[first-samuel-30-20]]
^20^ Tomaron todo el ganado mayor y menor y lo condujeron ante él diciendo: «Este es el botín de David».

[[first-samuel-30-21]]
^21^ Llegó David donde los doscientos hombres que, demasiado fatigados para seguirle, se habían quedado en el torrente Besor. Salieron al encuentro de David y de la gente que venía con él; se acercaron David y la tropa y les saludaron.

[[first-samuel-30-22]]
^22^ Pero todos los perversos y malvados de entre los hombres que habían ido con David, contestaron: «A los que no han ido con nosotros no se les dará el botín que hemos salvado, sino sólo su mujer y sus hijos; que lo tomen y se vayan».

[[first-samuel-30-23]]
^23^ David dijo: «No hagáis esto con lo que Yahveh nos ha concedido. Nos ha guardado y ha entregado en nuestras manos a esa banda que vino contra nosotros.

[[first-samuel-30-24]]
^24^ ¿Quién os dará la razón en este caso? Porque: Esta es la parte del que baja a la batalla y ésta la parte del que se queda con la impedimenta. Se partirá por igual».

[[first-samuel-30-25]]
^25^ Y desde aquel día en adelante lo estableció como decreto y norma para Israel, hasta el día de hoy.

[[first-samuel-30-26]]
^26^ Llegó David a Siquelag y envió parte del botín a los ancianos de Judá, según sus ciudades, diciendo: «Aquí tenéis un presente del botín tomado a los enemigos de Yahveh»,

[[first-samuel-30-27]]
^27^ a los de Betul, a los de Ramá del Négueb, a los de Yattir,

[[first-samuel-30-28]]
^28^ a los de Aroer, a los de Sifmot, a los de Estemoa,

[[first-samuel-30-29]]
^29^ a los de Carmelo, a los de las ciudades de Yerajmeel, a los de las ciudades de los quenitas,

[[first-samuel-30-30]]
^30^ a los de Jormá, a los de Bor Asan, a los de Eter,

[[first-samuel-30-31]]
^31^ a los de Hebrón y a todos los lugares por donde anduvo David con su gente.
[[first-samuel-31]]
== Capítulo 31

[[first-samuel-31-1]]
^1^ Trabaron batalla los filisteos contra Israel y huyeron los hombres de Israel ante los filisteos y cayeron heridos de muerte en el monte Gelboé.

[[first-samuel-31-2]]
^2^ Apretaron de cerca los filisteos a Saúl y a sus hijos y mataron los filisteos a Jonatán, Abinadab y Malki Súa, hijos de Saúl.

[[first-samuel-31-3]]
^3^ El peso de la batalla cargó sobre Saúl. Los arqueros tiron sobre él y fue herido por ellos.

[[first-samuel-31-4]]
^4^ Dijo Saúl a su escudero: «Saca tu espada y traspásame, no sea que lleguen esos incircuncisos y hagan mofa de mí », pero el escudero no quiso pues estaba lleno de temor. Entonces Saúl tomó la espada y se arrojó sobre ella.

[[first-samuel-31-5]]
^5^ Viendo el escudero que Saúl había muerto, se arrojó también sobre su espada y murió con él.

[[first-samuel-31-6]]
^6^ Así murieron aquel día juntamente Saúl y sus tres hijos y su escudero.

[[first-samuel-31-7]]
^7^ Cuando los hombres de Israel que estaban del lado frontero del valle y del otro lado del Jordán vieron que las tropas de Israel se daban a la fuga y que Saúl y sus hijos habían muerto, abandonaron sus ciudades y huyeron; vinieron los filisteos y se establecieron en ellas.

[[first-samuel-31-8]]
^8^ Al otro día vinieron los filisteos para despojar a los muertos y encontraron a Saúl y a sus tres hijos caídos en el monte Gelboé.

[[first-samuel-31-9]]
^9^ Cortaron su cabeza y le despojaron de sus armas que hicieron pasear a la redonda por el país de los filisteos para anunciar la buena nueva a sus dioses y a su pueblo.

[[first-samuel-31-10]]
^10^ Depositaron sus armas en el templo de Astarté y colgaron su cuerpo de los muros de Bet San.

[[first-samuel-31-11]]
^11^ Supieron los habitantes de Yabés de Galaad lo que los filisteos habían hecho con Saúl,

[[first-samuel-31-12]]
^12^ se levantaron todos los valientes y caminando durante toda la noche, tomaron del muro de Bet San el cuerpo de Saúl y los cuerpos de sus hijos y llevándolos a Yabés los quemaron allí.

[[first-samuel-31-13]]
^13^ Tomaron sus huesos y los sepultaron bajo el tamarisco de Yabés y ayunaron siete días.
