[[first-chronicles]]
= Primer libro de las Crónicas

[[first-chronicles-1]]
== Capítulo 1

[[first-chronicles-1-1]]
^1^ Adán, Set, Enós;

[[first-chronicles-1-2]]
^2^ Quenán, Mahalalel, Yered;

[[first-chronicles-1-3]]
^3^ Henoc, Matusalén, Lámek;

[[first-chronicles-1-4]]
^4^ Noé, Sem, Cam y Jafet.

[[first-chronicles-1-5]]
^5^ Hijos de Jafet: Gómer, Magog, los medos, Yaván, Túbal, Mések y Tirás.

[[first-chronicles-1-6]]
^6^ Hijos de Gómer: Askenaz, Rifat y Togarmá

[[first-chronicles-1-7]]
^7^ Hijos de Yaván: Elisá, Tarsis, Kittim y Rodanim.

[[first-chronicles-1-8]]
^8^ Hijos de Cam: Kus y Misrayim, Put y Canaán.

[[first-chronicles-1-9]]
^9^ Hijos de Kus: Sebá, Javilá, Sabtá, Ramá y Sabteká. Hijos de Ramá: Sebá y Dedán.

[[first-chronicles-1-10]]
^10^ Kus engendró a Nimrod, que fue el primer hombre poderoso de la tierra.

[[first-chronicles-1-11]]
^11^ Misrayim engendró a los luditas, anamitas, lahabitas, naftujitas,

[[first-chronicles-1-12]]
^12^ patrusitas, kaslujitas y kaftoritas, de donde proceden los filisteos.

[[first-chronicles-1-13]]
^13^ Canaán engendró a Sidón, su primogénito, a Jet,

[[first-chronicles-1-14]]
^14^ y al jebuseo, al amorreo, al guirgasita,

[[first-chronicles-1-15]]
^15^ al jivita, al arquita, al sinita,

[[first-chronicles-1-16]]
^16^ al arvadita, al semarita y al jamatita.

[[first-chronicles-1-17]]
^17^ Hijos de Sem: Elam, Assur, Arpaksad, Lud y Aram. Hijos de Aram: Us, Jul, Guéter y Mések.

[[first-chronicles-1-18]]
^18^ Arpaksad engendró a Sélaj y Sélaj engendró a Héber.

[[first-chronicles-1-19]]
^19^ A Héber le nacieron dos hijos: el nombre del primero era Pélej, porque en sus días fue dividida la tierra, y el nombre de su hermano era Yoqtán.

[[first-chronicles-1-20]]
^20^ Yoqtán engendró a Almodad, Sélef, Jasarmávet, Yéraj,

[[first-chronicles-1-21]]
^21^ Hadoram, Uzal, Diqlá,

[[first-chronicles-1-22]]
^22^ Ebal, Abimael, Sebá,

[[first-chronicles-1-23]]
^23^ Ofir, Javilá, Yobab: todos ellos hijos de Yoqtán.

[[first-chronicles-1-24]]
^24^ Arpaksad, Sélaj,

[[first-chronicles-1-25]]
^25^ Héber, Pélej, Reú,

[[first-chronicles-1-26]]
^26^ Serug, Najor, Téraj,

[[first-chronicles-1-27]]
^27^ Abram, o sea Abraham.

[[first-chronicles-1-28]]
^28^ Hijos de Abraham: Isaac e Ismael.

[[first-chronicles-1-29]]
^29^ Sus descendientes son éstos: El primogénito de Ismael: Nebayot; después, Quedar, Adbeel, Mibsam,

[[first-chronicles-1-30]]
^30^ Mismá, Dumá, Massá, Jadad, Temá,

[[first-chronicles-1-31]]
^31^ Yetur, Nafís y Quedmá. Estos son los hijos de Ismael.

[[first-chronicles-1-32]]
^32^ Hijos de Queturá, concubina de Abraham. Dio a luz a Zimrán, Joqsán, Medán, Madián, Yisbaq y Súaj. Hijos de Yoqsán: Sebá y Dedán.

[[first-chronicles-1-33]]
^33^ Hijos de Madián: Efá, Efer, Henoc, Abidá y Eldaá. Todos ellos son hijos de Queturá.

[[first-chronicles-1-34]]
^34^ Abraham engendró a Isaac. Hijos de Isaac: Esaú e Israel.

[[first-chronicles-1-35]]
^35^ Hijos de Esaú: Elifaz, Reuel, Yeús, Yalam y Coré.

[[first-chronicles-1-36]]
^36^ Hijos de Elifaz: Temán, Omar, Sefí, Gatam, Quenaz, Timná y Amalec.

[[first-chronicles-1-37]]
^37^ Hijos de Reuel: Nájat, Zéraj, Sammá y Mizzá.

[[first-chronicles-1-38]]
^38^ Hijos de Seír: Lotán, Sobal, Sibón, Aná, Disón, Eser y Disán.

[[first-chronicles-1-39]]
^39^ Hijos de Lotán: Jorí y Homán. Hermana de Lotán fue Timná.

[[first-chronicles-1-40]]
^40^ Hijos de Sobal: Alyán, Manájat. Ebal, Sefí y Onam. Hijos de Sibón: Ayyá y Aná.

[[first-chronicles-1-41]]
^41^ Hijos de Aná: Disón. Hijos de Disón: Jamrán, Esbán, Yitrán y Kerán.

[[first-chronicles-1-42]]
^42^ Hijos de Eser: Bilhán, Zaaván y Yaacán. Hijos de Disón: Us y Arán.

[[first-chronicles-1-43]]
^43^ Estos son los reyes que reinaron en el país de Edom antes de que hubiera rey entre los israelitas: Bela, hijo de Beor; el nombre de su ciudad era Dinhabá.

[[first-chronicles-1-44]]
^44^ Murió Bela, y reinó en su lugar Yobab, hijo de Zéraj, de Bosrá.

[[first-chronicles-1-45]]
^45^ Murió Yobab y reinó en su lugar Jusam, del país de los temanitas.

[[first-chronicles-1-46]]
^46^ Y murió Jusam, y en su lugar reinó Hodad, hijo de Bedad, que derrotó a los madianitas en los campos de Moab; el nombre de su ciudad fue Avit.

[[first-chronicles-1-47]]
^47^ Murió Hodad, y reinó en su lugar Samlá, de Masrecá.

[[first-chronicles-1-48]]
^48^ Murió Samlá, y reinó en su lugar Saúl, de Rejobot Hannahar.

[[first-chronicles-1-49]]
^49^ Murió Saúl y reinó en su lugar Baal Janán, hijo de Akbor.

[[first-chronicles-1-50]]
^50^ Murió Baal Janán y reinó en su lugar Hodad. El nombre de su ciudad era Paí, y el de su mujer Mehetabel, hija de Matred, hija de Mezahab.

[[first-chronicles-1-51]]
^51^ Murió Hodad, y hubo jeques en Edom: el jeque Timná, el jeque Alyá, el jeque Yetet,

[[first-chronicles-1-52]]
^52^ el jeque Oholibamá, el jeque Elá, el jeque Pinón,

[[first-chronicles-1-53]]
^53^ el jeque Quenaz, el jeque Temán, el jeque Mibsar,

[[first-chronicles-1-54]]
^54^ el jeque Magdiel, el jeque Iram. Estos fueron los jeques de Edom.
[[first-chronicles-2]]
== Capítulo 2

[[first-chronicles-2-1]]
^1^ Estos son los hijos de Israel: Rubén, Simeón, Leví y Judá, Isacar y Zabulón,

[[first-chronicles-2-2]]
^2^ Dan, José y Benjamín, Neftalí, Gad y Aser.

[[first-chronicles-2-3]]
^3^ Hijos de Judá: Er, Onán y Selá; los tres le nacieron de Bat Súa la cananea. Er, primogénito de Judá, era malo a los ojos de Yahveh, que le quitó la vida.

[[first-chronicles-2-4]]
^4^ Tamar, nuera de Judá, le dio a luz a Peres y Zéraj. Todos los hijos de Judá fueron cinco.

[[first-chronicles-2-5]]
^5^ Hijos de Peres: Jesrón y Jamul.

[[first-chronicles-2-6]]
^6^ Hijos de Zéraj: Zimrí, Etán, Hemán, Kalkol y Dardá, en total cinco.

[[first-chronicles-2-7]]
^7^ Hijos de Karmí: Akar, que perturbó a Israel por haber violado el anatema.

[[first-chronicles-2-8]]
^8^ Hijos de Etán: Azarías.

[[first-chronicles-2-9]]
^9^ Hijos de que le nacieron a Jesrón: Yerajmeel, Ram y Kelubay.

[[first-chronicles-2-10]]
^10^ Ram engendró a Aminadab, Aminadab engendró a Najsón, príncipe de los hijos de Judá.

[[first-chronicles-2-11]]
^11^ Najsón engendró a Salmá, y Salmá engendró a Booz.

[[first-chronicles-2-12]]
^12^ Booz engendró a Obed y Obed engendró a Jesé.

[[first-chronicles-2-13]]
^13^ Jesé engendró a su primogénito Eliab; Abinadab, el segundo; Simá, el tercero;

[[first-chronicles-2-14]]
^14^ Netanel, el cuarto; Radday, el quinto;

[[first-chronicles-2-15]]
^15^ Osem, el sexto; David, el séptimo.

[[first-chronicles-2-16]]
^16^ Hermanas suyas fueron Sarvia y Abigaíl. Hijos de Sarvia: Abisay, Joab y Asahel, tres.

[[first-chronicles-2-17]]
^17^ Abigaíl dio a luz a Amasá, el padre de Amasá fue Yéter el ismaelita.

[[first-chronicles-2-18]]
^18^ Caleb, hijo de Jesrón, engendró a Yeriot, de su mujer Azubá. Estos son sus hijos: Yéser, Sobab y Ardón.

[[first-chronicles-2-19]]
^19^ Murió Azubá y Caleb tomó por mujer a Efratá, de la que tuvo a Jur.

[[first-chronicles-2-20]]
^20^ Jur engendró a Urí, y Urí engendró a Besalel.

[[first-chronicles-2-21]]
^21^ Después se unió Jesrón a la hija de Makir, padre de Galaad. Tenía él sesenta años cuando la tomó por mujer; y le dijo a luz a Segub.

[[first-chronicles-2-22]]
^22^ Segub engendró a Yaír, que poseyó veintitrés ciudades en el país de Galaad.

[[first-chronicles-2-23]]
^23^ Los guesuritas y los arameos les tomaron las aldeas de Yaír, Quenat y sus aduares: sesenta ciudades. Todo esto pertenece a los hijos de Makir, padre de Galaad.

[[first-chronicles-2-24]]
^24^ Después de morir Jesrón, Caleb se unió a Efratá, mujer de su padre Jesrón, la cual le dio a luz a Asjur, padre de Técoa.

[[first-chronicles-2-25]]
^25^ Los hijos de Yerajmeel, primogénito de Jesrón, fueron: Ram, el primogénito, y Buná, Orén, Osem y Ajías.

[[first-chronicles-2-26]]
^26^ Yerajmeel tuvo otra mujer cuyo nombre era Atará, que fue madre de Onam.

[[first-chronicles-2-27]]
^27^ Los hijos de Ram, primogénito de Yerajmeel, fueron: Maás, Yamín y Equer.

[[first-chronicles-2-28]]
^28^ Y los hijos de Onam fueron Sammay y Yadá; los hijos de Sammay, Nadab y Abisur.

[[first-chronicles-2-29]]
^29^ La mujer de Abisur se llamaba Abihayil, que le dio a luz a Ajbán y Molid.

[[first-chronicles-2-30]]
^30^ Los hijos de Nadab fueron Séled y Efraím; Séled murió sin hijos.

[[first-chronicles-2-31]]
^31^ Hijo de Efraím fue Yisí; hijo de Yisí, Sesán; hijo de Sesán, Ajlay.

[[first-chronicles-2-32]]
^32^ Hijos de Yadá, hermano de Sammay, fueron Yéter y Jonatán; Yéter murió sin hijos.

[[first-chronicles-2-33]]
^33^ Hijos de Jonatán: Pélet y Zazá. Estos fueron los descendientes de Yerajmeel.

[[first-chronicles-2-34]]
^34^ Sesán no tuvo hijos, sino hijas; tenía Sesán un siervo egipcio que se llamaba Yarjá.

[[first-chronicles-2-35]]
^35^ Y dio Sesán una hija suya a su siervo Yarjá por esposa, la cual le engendró a Attay,

[[first-chronicles-2-36]]
^36^ Attay engendró a Natán, Natán engendró a Zabad,

[[first-chronicles-2-37]]
^37^ Zabad engendró a Eflal, Eflal engendró a Obed,

[[first-chronicles-2-38]]
^38^ Obed engendró a Jehú, Jehú engendró a Azarías,

[[first-chronicles-2-39]]
^39^ Azarías engendró a Jeles, Jeles engendró a Elasá,

[[first-chronicles-2-40]]
^40^ Elasá engendró a Sismay, Sismay engendró a Sallum,

[[first-chronicles-2-41]]
^41^ Sallum engendró a Yecamías, Yecamías engendró a Elisamá.

[[first-chronicles-2-42]]
^42^ Hijos de Caleb, hermano de Yerajmeel: Mesá, su primogénito, que fue padre de Zif; tuvo por hijo a Maresá, padre de Hebrón.

[[first-chronicles-2-43]]
^43^ Hijos de Hebrón: Coré, Tappúaj, Réquem y Sema.

[[first-chronicles-2-44]]
^44^ Sema engendró a Rájam, padre de Yorqueam; Réquem engendró a Sammay.

[[first-chronicles-2-45]]
^45^ Hijo de Sammay fue Maón, y Maón fue padre de Bet Sur.

[[first-chronicles-2-46]]
^46^ Efá, concubina de Caleb, dio a luz a Jarán, Mosá y Gazez; Jarán engendró a Gazez.

[[first-chronicles-2-47]]
^47^ Hijos de Yahday: Reguem, Jotam, Guesán, Pélet, Efá y Sáaf.

[[first-chronicles-2-48]]
^48^ Maaká, concubina de Caleb, dio a luz a Séber y Tirjaná.

[[first-chronicles-2-49]]
^49^ Engendró también a Sáaf, padre de Madmanná, y a Sevá, padre de Makdená y padre de Guibeá. Hija de Caleb fue Aksá.

[[first-chronicles-2-50]]
^50^ Estos fueron los hijos de Caleb. Hijos de Jur, primogénito de Efratá: Sobal, padre de Quiryat Yearim;

[[first-chronicles-2-51]]
^51^ Salmá, padre de Belén; Járef, padre de Bet Gáder.

[[first-chronicles-2-52]]
^52^ Sobal, padre de Quiryat Yearim, tuvo por hijos a Haroé, es decir, la mitad de los manajatitas

[[first-chronicles-2-53]]
^53^ y las familias de Quiryat Yearim; los yitríes, los putíes, los sumatíes y los misraíes. De ellos salieron los soratíes y los de Estaol.

[[first-chronicles-2-54]]
^54^ Hijos de Salmá: Belén y los netofatíes, Atrot Bet Joab, la otra mitad de los manajatitas, los soríes

[[first-chronicles-2-55]]
^55^ y las familias de los sofríes que habitaban en Yabés, los tiratíes, los simatíes, los sukatíes. Estos son kineos, descendientes de Jamat, padre de la casa de Rebak.
[[first-chronicles-3]]
== Capítulo 3

[[first-chronicles-3-1]]
^1^ Estos son los hijos que le nacieron a David en Hebrón: el primogénito Amnón, hijo de Ajinoam, de Yizreel; el segundo, Daniel, hijo de Abigaíl de Carmelo;

[[first-chronicles-3-2]]
^2^ el tercero, Absalón, hijo de Maaká, hija de Talmay, rey de Guesur; el cuarto, Adonías, hijo de Jagguit;

[[first-chronicles-3-3]]
^3^ el quinto, Sefatías, de Abital; el sexto, Yitream, de su mujer Eglá.

[[first-chronicles-3-4]]
^4^ Estos seis le nacieron en Hebrón, donde reinó siete años y seis meses. Reinó en Jerusalén 33 años.

[[first-chronicles-3-5]]
^5^ Estos son los que le nacieron en Jerusalén: Simá, Sobab, Natán, Salomón, los cuatro de Bat Súa, hija de Ammiel.

[[first-chronicles-3-6]]
^6^ Además, Yibjar, Elisamá, Elifélet,

[[first-chronicles-3-7]]
^7^ Nogah, Néfeg, Yafía,

[[first-chronicles-3-8]]
^8^ Elisamá, Elyadá, Elifélet: nueve.

[[first-chronicles-3-9]]
^9^ Estos son todos los hijos de David, sin contar los hijos de las concubinas. Hermana de ellos fue Tamar.

[[first-chronicles-3-10]]
^10^ Hijo de Salomón: Roboam; hijo suyo, Abías; hijo suyo, Asá; hijo suyo, Josafat;

[[first-chronicles-3-11]]
^11^ hijo suyo, Joram; hijo suyo, Ocozías; hijo suyo, Joás;

[[first-chronicles-3-12]]
^12^ hijo suyo, Amasías; hijo suyo, Azarías; hijo suyo, Jotam;

[[first-chronicles-3-13]]
^13^ hijo suyo, Acaz; hijo suyo, Ezequías; hijo suyo, Manasés;

[[first-chronicles-3-14]]
^14^ hijo suyo, Amón; hijo suyo, Josías.

[[first-chronicles-3-15]]
^15^ Hijos de Josías: Yojanán, el primogénito; Yoyaquim, el segundo; Sedecías, el tercero; Sallum, el cuarto.

[[first-chronicles-3-16]]
^16^ Hijos de Yoyaquim: su hijo Joaquim y su hijo Sedecías.

[[first-chronicles-3-17]]
^17^ Hijos de Joaquín, el cautivo: Sealtiel su hijo;

[[first-chronicles-3-18]]
^18^ Malkiram, Pedaías, Senassar, Yecamías, Hosamá, Nedabías.

[[first-chronicles-3-19]]
^19^ Hijos de Pedaías: Zorobabel y Simí. Hijos de Zorobabel: Mesullam, Jananías y Selomit, hermana de ellos.

[[first-chronicles-3-20]]
^20^ Hijos de Mesullam: Jasubá, Ohel, Berekías, Jasadías y Yusab Jésed: cinco.

[[first-chronicles-3-21]]
^21^ Hijos de Jananías: Pelatías; Isaías, hijo suyo; Refaías, hijo suyo; Arnán, hijo suyo; Abdías, hijo suyo; Sekanías, hijo suyo.

[[first-chronicles-3-22]]
^22^ Hijos de Sekanías: Semaías, Jattús, Yigal, Baríaj, Nearías y Safat: seis.

[[first-chronicles-3-23]]
^23^ Hijos de Nearías: Elyoenay, Ezequías, Azricam: tres. Hijos de Elyoenay: Hodaías, Elyasib, Pelaías, Aqcub, Yojanán, Delaías y Ananí: siete.
[[first-chronicles-4]]
== Capítulo 4

[[first-chronicles-4-1]]
^1^ Hijos de Judá: Peres, Jesrón, Karmí, Jur y Sobal.

[[first-chronicles-4-2]]
^2^ Reaías, hijo de Sobal, engendró a Yájat. Yájat engendró a Ajumay y Lahad. Estas son familias de los soreatitas.

[[first-chronicles-4-3]]
^3^ Estos son los hijos de Jur, padre de Etam: Yizreel, Yismá y Yibdás. Su hermana se llamaba Haslelponí.

[[first-chronicles-4-4]]
^4^ Penuel fue el padre de Guedor, y Ezer padre de Jusá. Estos son los hijos de Jur, primogénito de Efratá, padre de Belén.

[[first-chronicles-4-5]]
^5^ Asjur, padre de Técoa, tuvo dos mujeres: Jelá y Naará.

[[first-chronicles-4-6]]
^6^ Naará dio a luz a Ajuzzam, Jéfer, los timnitas y los ajastaritas. Estos son los hijos de Naará.

[[first-chronicles-4-7]]
^7^ Hijos de Jelá: Séret, Sójar, Etnán.

[[first-chronicles-4-8]]
^8^ Cos engendró a Anub y Hossobebá y las familias de Ajarjel, hijo de Harum.

[[first-chronicles-4-9]]
^9^ Pero Yabés fue más ilustre que sus hermanos, y su madre le dio el nombre de Yabés, diciendo: «Di a luz con dolor».

[[first-chronicles-4-10]]
^10^ Yabés invocó al Dios de Israel, exclamando: «Si de verdad me bendices, ensancharás mis términos, tu mano estará conmigo y alejarás el mal para que no padezca aflicción». Y otorgóle Dios su petición.

[[first-chronicles-4-11]]
^11^ Kelub, hermano de Sujá, engendró a Mejir, que fue padre de Estón.

[[first-chronicles-4-12]]
^12^ Estón engendró a Bet Rafá, Paséaj y Tejinná, padre de Ir Najás. Estos son los hombres de Rekal.

[[first-chronicles-4-13]]
^13^ Hijos de Quenaz: Otniel y Seraías. Hijos de Otniel: Jatat y Meonotay.

[[first-chronicles-4-14]]
^14^ Meonotay engendró a Ofrá, y Seraías engendró a Joab, padre de Gue Jarasim, pues eran artesanos.

[[first-chronicles-4-15]]
^15^ Hijos de Caleb, hijo de Yefunné: Ir, Elá y Náam; hijo de Elá: Quenaz.

[[first-chronicles-4-16]]
^16^ Hijos de Yehallelel: Zif, Zifá, Tiryá y Asarel.

[[first-chronicles-4-17]]
^17^ Hijos de Ezrá: Yéter, Méred, Efer y Yalón. Ella concibió a María, Samay y Yisbaj, padre de Estemoa.

[[first-chronicles-4-18]]
^18^ Su mujer, la de Judá, dio a luz a Yéred, padre de Guedor, a Héber, padre de Sokó, y a Yecutiel, padre de Zanóaj. Estos son los hijos de Bitía, hija del Faraón, que Méred había tomado por esposa.

[[first-chronicles-4-19]]
^19^ Hijos de la mujer de Odías, hermana de Nájam, padre de Queilá el garmita y Estemoa el maakatita.

[[first-chronicles-4-20]]
^20^ Hijos de Simón: Ammón y Rinná, Ben Janán y Tilón. Hijos de Yisí: Zójet y Ben Zójet.

[[first-chronicles-4-21]]
^21^ Hijos de Sela, hijo de Judá: Er, padre de Leká, y Ladá, padre de Maresá, y las familias de los que trabajan el lino en Bet Asbea.

[[first-chronicles-4-22]]
^22^ Yoquim, los hombres de Kozebá; y Joás y Saraf, que se casaron en Moab, antes de volver a Belén. Estas son cosas muy antiguas.

[[first-chronicles-4-23]]
^23^ Ellos eran alfareros y habitaban en Netaím y Guederá; moraban allí con el rey, trabajando a su servicio.

[[first-chronicles-4-24]]
^24^ Hijos de Simeón: Nemuel, Yamín, Yarib, Zéraj y Saúl,

[[first-chronicles-4-25]]
^25^ Sallum, su hijo; Mibsam, su hijo; Mismá, su hijo.

[[first-chronicles-4-26]]
^26^ Hijos de Mismá: Jammuel, hijo suyo; Zakkur, hijo suyo; Simí, hijo suyo.

[[first-chronicles-4-27]]
^27^ Simí tuvo dieciséis hijos y seis hijas, pero sus hermanos no tuvieron muchos hijos, no se multiplicaron todas sus familias como los hijos de Judá.

[[first-chronicles-4-28]]
^28^ Habitaban en Berseba, Moladá, Jasar-Sual,

[[first-chronicles-4-29]]
^29^ Bilhá, Esem y Tolad,

[[first-chronicles-4-30]]
^30^ Betuel, Jormá, Siquelag,

[[first-chronicles-4-31]]
^31^ Bet Markabot, Jasar Susim, Bet Birí y Saaráyim. Estas fueron sus ciudades hasta el reino de David.

[[first-chronicles-4-32]]
^32^ También sus aldeas: Etam, Ayim, Rimmón, Tokén y Asán, cinco ciudades,

[[first-chronicles-4-33]]
^33^ y todas sus aldeas que están en torno a aquellas ciudades, hasta Baalat. Aquí habitaron y éste fue su registro genealógico.

[[first-chronicles-4-34]]
^34^ Mesobab, Yamlek, Yosá, hijo de Amasías,

[[first-chronicles-4-35]]
^35^ Joel, Jehú, hijo de Yosibías, hijo de Seraías, hijo de Asiel;

[[first-chronicles-4-36]]
^36^ Elyoenay, Yaacobá, Yesojaías, Asaías, Adiel, Yesimiel y Benaías,

[[first-chronicles-4-37]]
^37^ Zizá, hijo de Sifí, hijo de Allón, hijo de Yedaías, hijo de Simrí, hijo de Semaías.

[[first-chronicles-4-38]]
^38^ Estos que han sido citados por sus nombres, fueron jefes en sus familias y sus casas paternas y se multiplicaron grandemente.

[[first-chronicles-4-39]]
^39^ Se dirigieron a la entrada de Guerar, hasta el oriente del valle, buscando pastos para sus ganados.

[[first-chronicles-4-40]]
^40^ Y hallaron pastos pingües y buenos y una tierra espaciosa, tranquila y segura, pues antes habían morado allí los descendientes de Cam.

[[first-chronicles-4-41]]
^41^ Estos que se han citado por sus nombres vinieron en tiempos de Ezequías, rey de Judá, y destruyeron las tiendas de aquéllos, y los refugios que allí se encontraban, entregándolos al anatema hasta el día de hoy; y habitaron en lugar de ellos, ya que había allí pastos para sus ganados.

[[first-chronicles-4-42]]
^42^ Algunos de los hijos de Simeón, en número de quinientos hombres, se fueron a la montaña de Seír; sus jefes eran Pelatías, Nearías, Refaías, Uzziel, hijos de Yisí:

[[first-chronicles-4-43]]
^43^ derrotaron a los restos de Amalec, que habían escapado, y habitaron allí hasta el día de hoy.
[[first-chronicles-5]]
== Capítulo 5

[[first-chronicles-5-1]]
^1^ Hijos de Rubén, primogénito de Israel. Rubén había nacido el primero, mas por haber manchado el tálamo de su padre fue dada su primogenitura a los hijos de José, hijo de Israel. Con todo, José no fue inscrito en las genealogías como el primogénito,

[[first-chronicles-5-2]]
^2^ pues Judá se hizo poderoso entre sus hermanos y de él procede el príncipe, pero la primogenitura pertenece a José.

[[first-chronicles-5-3]]
^3^ Hijos de Rubén, primogénito de Israel: Henoc, Pallú, Jesrón y Karmí.

[[first-chronicles-5-4]]
^4^ Hijos de Joel: Semaías, hijo suyo; Gog, hijo suyo; Simí, hijo suyo;

[[first-chronicles-5-5]]
^5^ Miká, hijo suyo; Reaías, hijo suyo; Báal, hijo suyo;

[[first-chronicles-5-6]]
^6^ Beerá, hijo suyo, al cual Teglatfalasar, rey de Asiria, llevó cautivo. Era jefe de los rubenitas.

[[first-chronicles-5-7]]
^7^ Hermanos suyos, por familias, agrupados según sus genealogías: el primero, Yeiel, Zacarías,

[[first-chronicles-5-8]]
^8^ Belá, hijo de Azaz, hijo de Sema, hijo de Joel. Este habitaba en Aroer y hasta Nebo y Báal Meón.

[[first-chronicles-5-9]]
^9^ Habitaban, asimismo, al oriente hasta el borde del desierto que se extiende desde el río Eufrates, pues sus ganados se habían multiplicado en la tierra de Galaad.

[[first-chronicles-5-10]]
^10^ En los días de Saúl hicieron guerra contra los agareos, que cayeron en sus manos; y habitaron en sus tiendas por toda la parte oriental de Galaad.

[[first-chronicles-5-11]]
^11^ Los hijos de Gad habitaban junto a ellos en la tierra de Basán hasta Salká.

[[first-chronicles-5-12]]
^12^ Joel fue el primero, Safán el segundo; luego Yanay y Safat, en Basán.

[[first-chronicles-5-13]]
^13^ Sus hermanos, por casas paternas, fueron: Miguel, Mesullam, Seba, Yoray, Yakán, Zía y Héber: siete.

[[first-chronicles-5-14]]
^14^ He aquí los hijos de Abijáyil, hijo de Jurí, hijo de Yaróaj, hijo de Guilad, hijo de Miguel, hijo de Yesisay, hijo de Yajdó, hijo de Buz.

[[first-chronicles-5-15]]
^15^ Ají, hijo de Abdiel, hijo de Guní, era cabeza de sus casas paternas.

[[first-chronicles-5-16]]
^16^ Habitaban en Galaad, en Basán y sus aldeas, y en todos los ejidos de Sarón hasta sus confines.

[[first-chronicles-5-17]]
^17^ Todos ellos fueron registrados en los días de Jotam, rey de Judá, y en los días de Jeroboam, rey de Israel.

[[first-chronicles-5-18]]
^18^ Los hijos de Rubén, los de Gad y la media tribu de Manasés eran hombres valientes, llevaban escudo y espada, manejaban el arco y eran diestros en la guerra. Salían a campaña en número de 44.760.

[[first-chronicles-5-19]]
^19^ Hicieron guerra contra los agareos, contra Yetur, Nafis y Nodab,

[[first-chronicles-5-20]]
^20^ y Dios les ayudó contra ellos, de suerte que los agareos y todos los que con ellos estaban fueron entregados en sus manos; pues en la batalla clamaron a Dios y les fue propicio, por cuanto confiaban en él.

[[first-chronicles-5-21]]
^21^ Capturaron sus ganados: sus camellos, en número de 50.000, 250.000 ovejas, 2.000 asnos y 100.000 personas,

[[first-chronicles-5-22]]
^22^ pues, por ser guerra de Dios, cayeron muertos muchos. Habitaron el lugar de ellos hasta el destierro.

[[first-chronicles-5-23]]
^23^ Los hijos de la media tribu de Manasés habitaron en el país desde Basán hasta Báal Hermón, Senir y la montaña de Hermón. Eran muy numerosos.

[[first-chronicles-5-24]]
^24^ He aquí los jefes de sus casas paternas: Efer, Yisi, Eliel, Azriel, Jeremías, Hodavías y Yajdiel, hombres valerosos, gente famosa, jefes de sus casas paternas.

[[first-chronicles-5-25]]
^25^ Pero fueron infieles al Dios de sus padres y se prostituyeron siguiendo a los dioses de los pueblos del país que Dios había destruido delante de ellos.

[[first-chronicles-5-26]]
^26^ Por lo cual el Dios de Israel suscitó el espíritu de Pil, rey de Asiria, que deportó a los rubenitas, los gaditas y la media tribu de Manasés, y los llevó a Jalaj, Jabor, Jará y el río Gozán, hasta el día de hoy.

[[first-chronicles-5-27]]
^27^ Hijos de Leví: Guersón, Quehat y Merarí.

[[first-chronicles-5-28]]
^28^ Hijos de Quehat: Amram, Yishar, Hebrón y Uzziel.

[[first-chronicles-5-29]]
^29^ Hijos de Amram: Aarón, Moisés y María. Hijos de Aarón: Nadab, Abihú, Eleazar e Itamar.

[[first-chronicles-5-30]]
^30^ Eleazar engendró a Pinjás, Pinjás engendró a Abisúa.

[[first-chronicles-5-31]]
^31^ Abisúa engendró a Buqquí y Buqquí engendró a Uzzí,

[[first-chronicles-5-32]]
^32^ Uzzí engendró a Zerajías, Zerajías engendró a Merayot,

[[first-chronicles-5-33]]
^33^ Merayot engendró a Amarías, Amarías engendró a Ajitub,

[[first-chronicles-5-34]]
^34^ Ajitub engendró a Sadoq, Sadoq engendró a Ajimaas,

[[first-chronicles-5-35]]
^35^ Ajimaas engendró a Azarías, Azarías engendró a Yojanán,

[[first-chronicles-5-36]]
^36^ Yojanán engendró a Azarías, el cual ejerció el sacerdocio en la Casa que Salomón edificó en Jerusalén.

[[first-chronicles-5-37]]
^37^ Azarías engendró a Amarías, Amarías engendró a Ajitub,

[[first-chronicles-5-38]]
^38^ Ajitub engendró a Sadoq, Sadoq engendró a Sallum,

[[first-chronicles-5-39]]
^39^ Sallum engendró a Jilquías, Jilquías engendró a Azarías,

[[first-chronicles-5-40]]
^40^ Azarías engendró a Seraías, Seraías engendró a Yehosadaq,

[[first-chronicles-5-41]]
^41^ Yehosadaq marchó cuando Yahveh deportó a Judá y Jerusalén por mano de Nabucodonosor.
[[first-chronicles-6]]
== Capítulo 6

[[first-chronicles-6-1]]
^1^ Hijos de Leví: Guersón, Quehat y Merarí.

[[first-chronicles-6-2]]
^2^ Estos son los nombres de los hijos de Guersón: Libní y Simí.

[[first-chronicles-6-3]]
^3^ Hijos de Quehat: Amram, Yishar, Hebrón y Uzziel.

[[first-chronicles-6-4]]
^4^ Hijos de Merarí: Majlí y Musí. Estas son las familias de los levitas según sus casas paternas.

[[first-chronicles-6-5]]
^5^ De Guersóm: Libní, hijo suyo; Yájat, hijo suyo: Zimmá, hijo suyo;

[[first-chronicles-6-6]]
^6^ Yoaj, hijo suyo; Iddó, hijo suyo; Zéraj, hijo suyo; Yeatray, hijo suyo.

[[first-chronicles-6-7]]
^7^ Hijos de Quehat: Amminadab, hijo suyo; Coré, hijo suyo; Assir, hijo suyo;

[[first-chronicles-6-8]]
^8^ Elcaná, hijo suyo; Ebyasaf, hijo suyo; Assir, hijo suyo;

[[first-chronicles-6-9]]
^9^ Tájat, hijo suyo; Uriel, hijo suyo; Uzzías, hijo suyo; Saúl, hijo suyo.

[[first-chronicles-6-10]]
^10^ Hijos de Elca1na: Amasay y Ajimot.

[[first-chronicles-6-11]]
^11^ Elcaná, hijo suyo; Sufay, hijo suyo; Nájat, hijo suyo.

[[first-chronicles-6-12]]
^12^ Eliab, hijo suyo; Yerojam, hijo suyo; Elcaná, hijo suyo.

[[first-chronicles-6-13]]
^13^ Hijos de Elcaná: Samuel, el primogénito y Abías, el segundo.

[[first-chronicles-6-14]]
^14^ Hijos de Merarí: Majlí; Libní, hijo suyo; Simí, hijo suyo; Uzzá, hijo suyo;

[[first-chronicles-6-15]]
^15^ Simá, hijo suyo; Jagguías, hijo suyo; Asaías, hijo suyo.

[[first-chronicles-6-16]]
^16^ Estos son los que puso David para dirigir el canto en la Casa de Yahveh, desde que el arca tuvo un lugar de reposo.

[[first-chronicles-6-17]]
^17^ Ejercían el ministerio de cantores ante la Morada de la Tienda del Encuentro, hasta que Salomón edificó la Casa de Yahveh en Jerusalén. Cumplían su servicio conforme a su reglamento.

[[first-chronicles-6-18]]
^18^ Estos son los que ejercían ese ministerio con sus hijos: De los hijos de Quehat: Hemán el cantor, hijo de Joel, hijo de Samuel,

[[first-chronicles-6-19]]
^19^ hijo de Elcaná, hijo de Yerojam, hijo de Eliel, hijo de Tóaj,

[[first-chronicles-6-20]]
^20^ hijo de Suf, hijo de Elcaná, hijo de Májat, hijo de Amasay,

[[first-chronicles-6-21]]
^21^ hijo de Elcaná, hijo de Joel, hijo de Azarías, hijo de Sofonías,

[[first-chronicles-6-22]]
^22^ hijo de Tájat, hijo de Assir, hijo de Ebyasaf, hijo de Coré,

[[first-chronicles-6-23]]
^23^ hijo de Yishar, hijo de Quehat, hijo de Leví, hijo de Israel.

[[first-chronicles-6-24]]
^24^ Su hermano Asaf, que asistía a su derecha: Asaf, hijo de Berekías, hijo de Simá,

[[first-chronicles-6-25]]
^25^ hijo de Miguel, hijo de Baasías, hijo de Malkías,

[[first-chronicles-6-26]]
^26^ hijo de Etní, hijo de Zéraj, hijo de Adaías,

[[first-chronicles-6-27]]
^27^ hijo de Etán, hijo de Zimmá, hijo de Simí,

[[first-chronicles-6-28]]
^28^ hijo de Yájat, hijo de Guersom, hijo de Leví.

[[first-chronicles-6-29]]
^29^ Los hijos de Merarí, hermanos de ellos, asistían a la izquierda: Etán, hijo de Quisí, hijo de Abdí, hijo de Malluk,

[[first-chronicles-6-30]]
^30^ hijo de Jasabías, hijo de Amasías, hijo de Jilquías,

[[first-chronicles-6-31]]
^31^ hijo de Amsí, hijo de Baní, hijo de Sémer,

[[first-chronicles-6-32]]
^32^ hijo de Majlí, hijo de Musí, hijo de Merarí, hijo de Leví.

[[first-chronicles-6-33]]
^33^ Sus hermanos, los levitas, estaban dedicados a los servicios de la Morada de la Casa de Dios.

[[first-chronicles-6-34]]
^34^ Aarón y sus hijos quemaban las ofrendas en el altar del holocausto y en el altar de los perfumes, según todo el servicio de las cosas sacratísimas, y hacían la expiación por todo Israel, conforme a todo cuanto había mandado Moisés, siervo de Dios.

[[first-chronicles-6-35]]
^35^ Estos son los hijos de Aarón: Eleazar, su hijo; Pinjás, su hijo: Abisúa, su hijo;

[[first-chronicles-6-36]]
^36^ Buqquí, su hijo; Uzzí, su hijo; Zerajías, su hijo;

[[first-chronicles-6-37]]
^37^ Merayot, su hijo; Amarías, su hijo; Ajitub, su hijo;

[[first-chronicles-6-38]]
^38^ Sadoq, su hijo; Ajimaas, su hijo.

[[first-chronicles-6-39]]
^39^ He aquí sus residencias según el orden de sus fronteras: A los hijos de Aarón, de la familia de los quehatitas - pues la suerte cayó sobre ellos -

[[first-chronicles-6-40]]
^40^ se les dio Hebrón en la tierra de Judá, con sus ejidos circundantes;

[[first-chronicles-6-41]]
^41^ pero el campo de la ciudad y sus aldeas se dieron a Caleb, hijo de Yefunné.

[[first-chronicles-6-42]]
^42^ Se dio a los hijos de Aarón como ciudades de asilo: Hebrón, Libná con sus ejidos, Yattir y Estemoa con sus ejidos,

[[first-chronicles-6-43]]
^43^ Jilaz con sus ejidos, Debir con sus ejidos,

[[first-chronicles-6-44]]
^44^ Asán con sus ejidos y Bet Semes con sus ejidos.

[[first-chronicles-6-45]]
^45^ De la tribu de Benjamín: Gueba con sus ejidos, Alémet con sus ejidos y Anatot con sus ejidos. El total de todas sus ciudades: trece ciudades según sus familias.

[[first-chronicles-6-46]]
^46^ A los otros hijos de Quehat les dieron por sorteo, conforme a sus familias, diez ciudades de la tribu de Efraím, de la tribu de Dan y de la media tribu de Manasés.

[[first-chronicles-6-47]]
^47^ A los hijos de Guersom, según sus familias, trece ciudades de la tribu de Isacar, de la tribu de Aser, de la tribu de Neftalí y de la tribu de Manasés en el Basán.

[[first-chronicles-6-48]]
^48^ A los hijos de Merarí, según sus familias, les tocaron en suerte doce ciudades de la tribu de Rubén, de la tribu de Gad y de la tribu de Zabulón;

[[first-chronicles-6-49]]
^49^ los israelitas dieron a los levitas estas ciudades con sus ejidos.

[[first-chronicles-6-50]]
^50^ De la tribu de los hijos de Judá, de la tribu de los hijos de Benjamín, les tocaron en suerte las ciudades a las que pusieron sus nombres.

[[first-chronicles-6-51]]
^51^ En la tribu de Efraím se tomaron ciudades para algunas familias de los hijos de Quehat.

[[first-chronicles-6-52]]
^52^ Se les asignó como ciudades de asilo: Siquem con sus ejidos, en la montaña de Efraím, Guézer con sus ejidos,

[[first-chronicles-6-53]]
^53^ Yoqmeam con sus ejidos y Bet Jorón con sus ejidos,

[[first-chronicles-6-54]]
^54^ Ayyalón con sus ejidos, Gat Rimmón con sus ejidos.

[[first-chronicles-6-55]]
^55^ Y de la media tribu de Manasés: Aner con sus ejidos, Bilam con sus ejidos. Esta para los restantes hijos de Quehat.

[[first-chronicles-6-56]]
^56^ Para los hijos de Guersom: De la familia de la media tribu de Manasés, Golán, en Basán, con sus ejidos, Astarot con sus ejidos.

[[first-chronicles-6-57]]
^57^ De la tribu de Isacar, Cadés con sus ejidos, Dobrat con sus ejidos,

[[first-chronicles-6-58]]
^58^ Ramot con sus ejidos, Anem con sus ejidos.

[[first-chronicles-6-59]]
^59^ De la tribu de Aser, Masal con sus ejidos, Abdón con sus ejidos,

[[first-chronicles-6-60]]
^60^ Jucoq con sus ejidos y Rejob con sus ejidos.

[[first-chronicles-6-61]]
^61^ De la tribu de Neftalí: Cadés en Galilea con sus ejidos, Jammón con sus ejidos y Quiryatáyim con sus ejidos.

[[first-chronicles-6-62]]
^62^ Para los demás hijos de Merarí: de la tribu de Zabulón: Rimmón con sus ejidos y Tabor con sus ejidos.

[[first-chronicles-6-63]]
^63^ Y en la otra parte del Jordán, frente a Jericó, al oriente del Jordán, de la tribu de Rubén: Béser en el desierto, con sus ejidos, y Yahsa con sus ejidos,

[[first-chronicles-6-64]]
^64^ Quedemot con sus ejidos y Mefaat con sus ejidos.

[[first-chronicles-6-65]]
^65^ De la tribu de Gad: Ramot en Galaad con sus ejidos, Majanáyim con sus ejidos,

[[first-chronicles-6-66]]
^66^ Jesbón con sus ejidos y Yazer con sus ejidos.
[[first-chronicles-7]]
== Capítulo 7

[[first-chronicles-7-1]]
^1^ Hijos de Isacar: Tolá, Puá, Yasub, Simrón: cuatro.

[[first-chronicles-7-2]]
^2^ Hijos de Tolá: Uzzí, Refaías, Yeriel, Yajmay, Yibsam y Samuel, jefes de las casas paternas de Tolá. Su número, en los días de David, era, según sus genealogías, de 22.600, valientes guerreros.

[[first-chronicles-7-3]]
^3^ Hijos de Uzzí: Yizrajías; hijos de Yizrajías: Miguel, Abdías, Joel, Yissaías: en total cinco jefes.

[[first-chronicles-7-4]]
^4^ Tenían, según sus genealogías, por sus casas paternas, divisiones de tropas de guerra en número de 36.000; pues tenían muchas mujeres e hijos.

[[first-chronicles-7-5]]
^5^ Sus hermanos de todas las familias de Isacar, eran 87.000, esforzados guerreros, inscritos todos ellos en las genealogías.

[[first-chronicles-7-6]]
^6^ Hijos de Benjamín: Bela, Béker, Yediael: tres.

[[first-chronicles-7-7]]
^7^ Hijos de Bela: Esbón, Uzzí, Uzziel, Yerimot e Irí: cinco jefes de las casas paternas, esforzados guerreros, inscritos en las genealogías en número de 22.034.

[[first-chronicles-7-8]]
^8^ Hijos de Béker: Zamirá, Joás, Eliezer, Elyoenay, Omrí, Yeremot, Abías, Anatot y Alémet; todos éstos hijos de Béker.

[[first-chronicles-7-9]]
^9^ Estaban inscritos según linajes y los jefes de sus casa paternas; tenían 20.200 guerreros esforzados.

[[first-chronicles-7-10]]
^10^ Hijos de Yediael: Bilhán. Hijos de Bilhán: Yeús, Benjamín, Ehúd, Kenaaná, Zetán, Tarsis y Ajisajar.

[[first-chronicles-7-11]]
^11^ Todos estos fueron hijos de Yediael, cabezas de familia, esforzados guerreros, en número de 17.200, aptos para la milicia y la guerra.

[[first-chronicles-7-12]]
^12^ Suppim y Juppim. Hijos de Ir: Jusim; su hijo: Ajer.

[[first-chronicles-7-13]]
^13^ Hijos de Neftalí: Yajseel, Guní, Yézer y Sallum, hijos de Bilhá.

[[first-chronicles-7-14]]
^14^ Hijos de Manasés: Asriel, que le dio a luz su concubina aramea. Esta le dio también a luz a Makir, padre de Galaad.

[[first-chronicles-7-15]]
^15^ Makir tomó una mujer para Juppim y para Suppim, y el nombre de su hermana era Maaká. El nombre del segundo era Selofjad; Selofjad tuvo hijas.

[[first-chronicles-7-16]]
^16^ Maaká, mujer de Makir, dio a luz un hijo, a quien llamó Peres. Su hermano se llamaba Seres y sus hijos Ulam y Réquem.

[[first-chronicles-7-17]]
^17^ Hijos de Ulam: Bedán. Estos son los hijos de Galaad, hijo de Makir, hijo de Manasés.

[[first-chronicles-7-18]]
^18^ Su hermana, Malkat, dio a luz a Ishod, Abiézer y Majlá.

[[first-chronicles-7-19]]
^19^ Los hijos de Semidá fueron: Ajyán, Sékem, Liqjí y Aniam.

[[first-chronicles-7-20]]
^20^ Hijos de Efraím: Sutélaj, Bered, su hijo; Tájat, su hijo; Eladá, su hijo; Tájat, su hijo;

[[first-chronicles-7-21]]
^21^ Zabad, su hijo; Sutélaj, su hijo; Ezer y Elad. Pero los hombres de Gat, nacidos en el país, los mataron, pues habían bajado a apoderarse de sus ganados.

[[first-chronicles-7-22]]
^22^ Su padre Efraím los lloró durante muchos días, y sus hermanos vinieron a consolarle.

[[first-chronicles-7-23]]
^23^ Después se unió a su mujer, que concibió y le dio un hijo, a quien llamó Beriá, porque la desgracia estaba en su casa.

[[first-chronicles-7-24]]
^24^ Hija suya fue Seerá, que edificó a Bet Jorón de arriba y de abajo y a Uzén Seerá.

[[first-chronicles-7-25]]
^25^ Réfaj, hijo suyo; Sutélaj, hijo suyo; Taján, hijo suyo.

[[first-chronicles-7-26]]
^26^ Ladán, hijo suyo; Ammihúd, hijo suyo; Elisamá, hijo suyo;

[[first-chronicles-7-27]]
^27^ Nun, hijo suyo; Josué, hijo suyo.

[[first-chronicles-7-28]]
^28^ Tenían propiedades y habitaban en Betel y sus aldeas anejas, en Naarán hacia el oriente, en Guézer y sus aldeas anejas hacia el occidente, en Siquem y sus aldeas hasta Ayyá y sus aldeas.

[[first-chronicles-7-29]]
^29^ Y en manos de los hijos de Manasés estaban Bet Seán y sus aldeas anejas, Tanak y sus aldeas, Meguiddó y sus aldeas, Dor y sus aldeas. En ellas habitaron los hijos de José, hijo de Israel.

[[first-chronicles-7-30]]
^30^ Hijos de Aser: Yimná, Yisvá, Yisví, Beriá, y Seraj, hermana de éstos.

[[first-chronicles-7-31]]
^31^ Hijos de Beriá: Héber y Malkiel, el cual fue padre de Birzayit.

[[first-chronicles-7-32]]
^32^ Héber engendró a Yaflet, Semer, Jotam y Suá, hermana de ellos.

[[first-chronicles-7-33]]
^33^ Hijos de Yaflet: Pasak, Bimhal y Asvat. Estos son los hijos de Yaflet.

[[first-chronicles-7-34]]
^34^ Hijos de Sémer: Ají, Rohgá, Jubbá y Aram.

[[first-chronicles-7-35]]
^35^ Hijos de Hélem, su hermano: Sofaj, Yimná, Seles y Amal.

[[first-chronicles-7-36]]
^36^ Hijos de Sofaj: Súaj, Jarnéfer, Sual, Berí y Yimrá;

[[first-chronicles-7-37]]
^37^ Béser, Hod, Sammá, Silsá, Yitrán y Beerá.

[[first-chronicles-7-38]]
^38^ Hijos de Yéter: Yefunné, Pispá y Ará.

[[first-chronicles-7-39]]
^39^ Hijos de Ullá: Araj, Janniel y Risías.

[[first-chronicles-7-40]]
^40^ Todos estos fueron hijos de Aser, jefes de familia, gente escogida, esforzados guerreros, jefes de príncipes. EN los registros genealógicos estaban inscritos en número de 26.000 hombres, aptos para la milicia y la guerra.
[[first-chronicles-8]]
== Capítulo 8

[[first-chronicles-8-1]]
^1^ Benjamín engendró a Bela, su primogénito; Asbel, el segundo; Ajiram el tercero;

[[first-chronicles-8-2]]
^2^ Nojá, el cuarto, y Rafá, el quinto.

[[first-chronicles-8-3]]
^3^ Los hijos de Bela fueron: Addar y Guerrá, padre de Ehúd,

[[first-chronicles-8-4]]
^4^ Abisúa, Naamán, Ajoaj,

[[first-chronicles-8-5]]
^5^ Guerá, Sefufán y Juram.

[[first-chronicles-8-6]]
^6^ Estos son los hijos de Ehúd, los jefes de familia de los que moraban en Gueba y a los que deportaron a Manájat:

[[first-chronicles-8-7]]
^7^ Naamán, Ajías y Guerá. Este los deportó, y engendró a Uzzá y Ajijud.

[[first-chronicles-8-8]]
^8^ Sajaráyim engendró hijos en los campos de Moab, después de haber repudiado a sus mujeres Jusim y Baará.

[[first-chronicles-8-9]]
^9^ Y de su nueva mujer engendró a Yobab, Sibías, Mesá, Malckom,

[[first-chronicles-8-10]]
^10^ Yeús, Sakías y Mirmá. Estos son sus hijos, jefes de casas paternas.

[[first-chronicles-8-11]]
^11^ Y de Jusim engendró a Atibub y Elpáal:

[[first-chronicles-8-12]]
^12^ Hijos de Elpáal: Héber. Misam y Semed, el cual edificó Onó, Lud y sus aldeas anejas.

[[first-chronicles-8-13]]
^13^ Beriá y Sema fueron cabezas de familia de los habitantes de Ayyalón, que pusieron en fuga a los moradores de Gat.

[[first-chronicles-8-14]]
^14^ Hermano suyo: Sesaq. Yeremot,

[[first-chronicles-8-15]]
^15^ Zebadías, Arad, Eder.

[[first-chronicles-8-16]]
^16^ Miguel, Yispá, Yojá: eran hijos de Beriá.

[[first-chronicles-8-17]]
^17^ Zebadías, Mesullam, Jizquí, Jáber.

[[first-chronicles-8-18]]
^18^ Yismeray, Yizlías y Yobab: hijos de Elpáal.

[[first-chronicles-8-19]]
^19^ Yaquim, Zikrí, Zabdí,

[[first-chronicles-8-20]]
^20^ Elienay. Silletay, Eliel,

[[first-chronicles-8-21]]
^21^ Adaías, Beraías y Simrat: hijos de Simí.

[[first-chronicles-8-22]]
^22^ Yispán, Héber, Eliel,

[[first-chronicles-8-23]]
^23^ Abdón, Zikrí, Janán,

[[first-chronicles-8-24]]
^24^ Jananías, Elam, Antotías,

[[first-chronicles-8-25]]
^25^ Yifdías y Penuel: hijos de Sesaq.

[[first-chronicles-8-26]]
^26^ Samseray, Serajías, Atalías,

[[first-chronicles-8-27]]
^27^ Yaaresías, Elías y Zikri: hijos de Yerojam.

[[first-chronicles-8-28]]
^28^ Estos eran los jefes de las casas paternas, según sus linages, que habitaban en Jerusalén.

[[first-chronicles-8-29]]
^29^ En Gabaón habitaba Yeiel, padre de Gabaón, cuya mujer se llamaba Maaká.

[[first-chronicles-8-30]]
^30^ Su hijo primogénito: Abdón; después Sur, Quis, Báal, Ner, Nadab,

[[first-chronicles-8-31]]
^31^ Guedor, Ajyó, Záker.

[[first-chronicles-8-32]]
^32^ Miqlot engendró a Simá. También éstos habitaron, igual que sus hermanos, en Jerusalén, con sus hermanos.

[[first-chronicles-8-33]]
^33^ Ner engendró a Quis, Quis engendró a Saúl, Saúl engendró a Jonatán, Malki Súa, Abinadab y Esbáal.

[[first-chronicles-8-34]]
^34^ Hijo de Jonatán: Merib Báal. Merib Báal engendró a Miká.

[[first-chronicles-8-35]]
^35^ Hijos de Miká: Pitón, Mélek, Tarea, Ajaz.

[[first-chronicles-8-36]]
^36^ Ajaz engendró a Yehoaddá, Yehoaddá engendró a Alémet, Azmávet y Zimri; Zimrí engendró a Mosá.

[[first-chronicles-8-37]]
^37^ Mosá engendró a Biná, cuyo hijo fue Rafá, cuyo hijo fue Elasá, cuyo hijo fue Asel.

[[first-chronicles-8-38]]
^38^ Asel tuvo seis hijos, cuyos nombres son: Azricam, su primogénito; después, Israel, Searías, Abdías y Janán. Todos ellos son hijos de Asel.

[[first-chronicles-8-39]]
^39^ Hijos de Eseq, hermano suyo: Ulam, su primogénito, Yeús, el segundo, y Elifélet, el tercero.

[[first-chronicles-8-40]]
^40^ Los hijos de Ulam fueron esforzados guerreros que manejaban el arco; tuvieron muchos hijos y nietos: 150. Todos estos eran descendientes de Benjamín.
[[first-chronicles-9]]
== Capítulo 9

[[first-chronicles-9-1]]
^1^ Todos los israelitas estaban registrados en las genealogías e inscritos en el libro de los reyes de Israel y de Judá, cuando fueron deportados a Babilonia por sus infidelidades.

[[first-chronicles-9-2]]
^2^ Los primeros que volvieron a habitar en sus propiedades y ciudades fueron israelitas, sacerdotes, levitas y donados.

[[first-chronicles-9-3]]
^3^ En Jerusalén habitaron hijos de Judá, hijos de Benjamín, hijos de Efraím y de Mamassés.

[[first-chronicles-9-4]]
^4^ Utay, hijo de Ammihúd, hijo de Omrí, hijo de Imrí, hijo de Baní, de los hijos de Peres, hijo de Judá.

[[first-chronicles-9-5]]
^5^ De los silonitas: Asaías, el primogénito, y sus hijos.

[[first-chronicles-9-6]]
^6^ De los hijos de Zéraj: Yeuel y sus hermanos: 690.

[[first-chronicles-9-7]]
^7^ De los hijos de Benjamín: Sallú, hijo de Mesullam, hijo de Hodavías, hijo de Hassenuá;

[[first-chronicles-9-8]]
^8^ Yibneías, hijo de Yerojam: Ela, hijo de Uzzí, hijo de Mikrí, y Mesullam, hijo de Sefatías, hijo de Reuel, hijo de Yibnías,

[[first-chronicles-9-9]]
^9^ y sus hermanos, según sus genealogías: 956. Todos estos eran jefes de familia en sus respectivas casas paternas.

[[first-chronicles-9-10]]
^10^ De los sacerdotes: Yedaías, Yehoyarib, Yakín,

[[first-chronicles-9-11]]
^11^ Azarías, hijo de Jilquías, hijo de Mesullam, hijo de Sadoq, hijo de Merayot, hijo de Ajitub, príncipe de la Casa de Dios.

[[first-chronicles-9-12]]
^12^ Adaías, hijo de Yerojam, hijo de Pasjur, hijo de Malkías; Masay, hijo de Adiel, hijo de Yajzerá, hijo de Mesullam, hijo de Mesillemit, hijo de Immer;

[[first-chronicles-9-13]]
^13^ y sus hermanos, jefes de sus casas paternas: 1.760 hombres aptos para los ejercicios del culto de la Casa de Dios.

[[first-chronicles-9-14]]
^14^ De los levitas: Semaías, hijo de Jassub, hijo de Azricam, hijo de Jasabías, de los hijos de Merarí.

[[first-chronicles-9-15]]
^15^ Baqbacar, Herés, Galal y Mattanías, hijo de Miká, hijo de Zikrí, hijo de Asaf.

[[first-chronicles-9-16]]
^16^ Abdías, hijo de Semaías, hijo de Galal, hijo de Yedutún; y Berekías, hijo de Asá, hijo de Elcaná, que habitaban en los poblados de los netofatíes.

[[first-chronicles-9-17]]
^17^ Los porteros: Sallum, Aqcub, Talmón, Ajimán y sus hermanos. Sallum era el jefe;

[[first-chronicles-9-18]]
^18^ y están hasta el presente junto a la puerta del rey, al oriente. Estos son los porteros del campamento de los hijos de Leví:

[[first-chronicles-9-19]]
^19^ Sallum, hijo de Qoré, hijo de Ebyasaf, hijo de Coré, y sus hermanos los coreítas, de la misma casa paterna, tenían el servicio del culto como guardianes de los umbrales de la Tienda, pues sus padres habían tenido a su cargo la guardia de acceso al campamento de Yahveh.

[[first-chronicles-9-20]]
^20^ Antiguamente había sido su jefe Pinjás, hijo de Eleazar, con el que estaba Yahveh.

[[first-chronicles-9-21]]
^21^ Zacarías, hijo de Meselemías, era portero de la entrada de la Tienda del Encuentro.

[[first-chronicles-9-22]]
^22^ El total de los elegidos para porteros era de 212, y estaban inscritos en sus problados. David y Samuel el vidente les habían establecido en sus cargos permanentemente.

[[first-chronicles-9-23]]
^23^ Tanto ellos como sus hijos tenían a su cargo las puertas de la Casa de Yahveh, la casa de la Tienda.

[[first-chronicles-9-24]]
^24^ Había porteros a los cuatro vientos: al oriente, al occidente, al norte y al mediodía.

[[first-chronicles-9-25]]
^25^ Sus hermanos, que habitaban en sus poblados, tenían que venir periódicamente a estar con ellos durante siete días,

[[first-chronicles-9-26]]
^26^ porque los cuatro jefes de los porteros eran permanentes; algunos levitas estaban al cuidado de las cámaras y de los tesoros de la Casa de Dios.

[[first-chronicles-9-27]]
^27^ Pasaban la noche alrededor de la Casa de Dios, pues les incumbía su vigilancia y habían de abrirla todas las mañanas.

[[first-chronicles-9-28]]
^28^ Unos tenían el cuidado de los utensilios del culto, y los contaban al meterlos y al sacarlos.

[[first-chronicles-9-29]]
^29^ Otros estaban encargados de los utensilios y de todos los instrumentos del Santuario, de la flor de harina, el vino, el aceite, el incienso y los aromas.

[[first-chronicles-9-30]]
^30^ Los que hacían la mezcla para los aromas eran sacerdotes.

[[first-chronicles-9-31]]
^31^ Mattitías, uno de los levitas, primogénito de Sallum el coreíta, estaba al cuidado constante de las cosas que se freían en sartén.

[[first-chronicles-9-32]]
^32^ Entre los quehatitas, sus hermanos, algunos estaban encargados de poner en filas los panes cada sábado.

[[first-chronicles-9-33]]
^33^ Había también cantores, cabezas de familia de los levitas y moraban en las habitaciones de la Casa, exentos de servicio, pues se ocupaban de día y de noche en su ministerio.

[[first-chronicles-9-34]]
^34^ Estos son, según sus genealogías, los cabezas de familia de los levitas, jefes de sus linajes que habitaban en Jerusalén.

[[first-chronicles-9-35]]
^35^ En Gabaón moraban el padre de Gabaón, Yeiel, cuya mujer se llamaba Maaká

[[first-chronicles-9-36]]
^36^ y Abdón su hijo primogénito; después, Sur, Quis, Báal, Ner, Nadab,

[[first-chronicles-9-37]]
^37^ Guedor, Ajyó, Zacarías y Miqlot.

[[first-chronicles-9-38]]
^38^ Miqlot engendró a Simam. También éstos habitaron en Jerusalén junto a sus hermanos y en unión con éstos.

[[first-chronicles-9-39]]
^39^ Ner engendró a Quis, Quis engendró a Saúl, Saúl engendró a Jonatán, Malki Súa, Abínadab y Esbáal.

[[first-chronicles-9-40]]
^40^ Hijo de Jonatán: Merib Báal. Merib Báal engendró a Miká.

[[first-chronicles-9-41]]
^41^ Hijos de Miká: Pitón, Mélek, Tajrea.

[[first-chronicles-9-42]]
^42^ Ajaz engendró a Yará, Yará engendró a Alémet, Azmavet y Zimrí. Zimrí engendró a Mosá.

[[first-chronicles-9-43]]
^43^ Mosá engendró a Binná. Refaías, hijo suyo: Elasá, hijo suyo; Asel, hijo suyo.

[[first-chronicles-9-44]]
^44^ Asel tuvo seis hijos, cuyos nombres son: Azricam, su primogénito, Ismael, Searías, Obadías y Janán. Estos fueron los hijos de Asel.
[[first-chronicles-10]]
== Capítulo 10

[[first-chronicles-10-1]]
^1^ Trabaron batalla los filisteos contra Israel; huyeron los hombres de Israel ante los filisteos, y cayeron heridos de muerte en el monte Gelboé.

[[first-chronicles-10-2]]
^2^ Los filisteos apretaron de cerca a Saúl y a sus hijos, y mataron a Jonatán, Abinadab y Malki Súa, hijos de Saúl.

[[first-chronicles-10-3]]
^3^ El peso de la batalla cargó sobre Saúl, los arqueros le descubrieron y fue herido por los arqueros.

[[first-chronicles-10-4]]
^4^ Dijo Saúl a su escudero: «Saca tu espada y traspásame con ella; no sea que vengan esos incircuncisos y hagan mofa de mí». Pero el escudero no quiso, pues estaba lleno de temor. Entonces tomó Saúl la espada y se arrojó sobre ella.

[[first-chronicles-10-5]]
^5^ Viendo el escudero que Saúl había muerto, se arrojó, también él, sobre su espada y murió con él.

[[first-chronicles-10-6]]
^6^ Así murió Saúl con sus tres hijos; y toda su casa murió juntamente con él.

[[first-chronicles-10-7]]
^7^ Viendo todos los hombres de Israel, que estaban en el valle, que las tropas de Israel se daban a la fuga y que Saúl y sus hijos habían muerto, abandonaron sus ciudades y huyeron; vinieron los filisteos y se establecieron en ellas.

[[first-chronicles-10-8]]
^8^ Al otro día vinieron los filisteos para despojar a los muertos, y encontraron a Saúl y a sus hijos caídos en el monte Gelboé.

[[first-chronicles-10-9]]
^9^ Despojándole, se llevaron su cabeza y sus armas, y mandaron anunciar la buena nueva por el contorno del país de los filisteos, a sus dioses y al pueblo.

[[first-chronicles-10-10]]
^10^ Depositaron sus armas en el templo de su dios y clavaron su cabeza en el templo de Dagón.

[[first-chronicles-10-11]]
^11^ Supieron todos los habitantes de Yabés de Galaad lo que los filisteos habían hecho con Saúl,

[[first-chronicles-10-12]]
^12^ se levantaron todos los valientes, tomaron el cadáver de Saúl y los cadáveres de sus hijos, y los llevaron a Yabés. Enterraron sus huesos bajo el tamarindo de Yabés, y ayunaron siete días.

[[first-chronicles-10-13]]
^13^ Saúl murió a causa de la infidelidad que había cometido contra Yahveh, porque no guardó la palabra de Yahveh y también por haber interrogado y consultado a una nigromante,

[[first-chronicles-10-14]]
^14^ en vez de consultar a Yahveh, por lo que le hizo morir, y transfirió el reino a David, hijo de Jesé.
[[first-chronicles-11]]
== Capítulo 11

[[first-chronicles-11-1]]
^1^ Congregóse todo Israel en torno a David, en Hebrón, y dijeron: «Mira: hueso tuyo y carne tuya somos nosotros.

[[first-chronicles-11-2]]
^2^ Ya de antes, cuando Saúl era nuestro rey, eras tú el que dirigías las entradas y salidas de Israel; Yahveh, tu Dios, te ha dicho: “Tú apacentarás a mi pueblo Israel.”»

[[first-chronicles-11-3]]
^3^ Vinieron todos los ancianos de Israel adonde el rey, a Hebrón; David hizo un pacto con ellos en Hebrón, en presencia de Yahveh; y ellos ungieron a David como rey sobre Israel, según la palabra que Yahveh había pronunciado por boca de Samuel.

[[first-chronicles-11-4]]
^4^ Después marchó David con todo Israel contra Jerusalén, o sea, Jebús; los habitantes del país eran jebuseos.

[[first-chronicles-11-5]]
^5^ Y decían los habitantes de Jebús a David: «No entrarás aquí». Conquistó David la fortaleza de Sión, que es la Ciudad de David.

[[first-chronicles-11-6]]
^6^ Y dijo David: «El que primero ataque al jebuseo, será jefe y capitán». Subió el primero Joab, hijo de Sarvia, y pasó a ser jefe.

[[first-chronicles-11-7]]
^7^ Se instaló David en la fortaleza; por eso la llamaron Ciudad de David.

[[first-chronicles-11-8]]
^8^ Y edificó en derredor de la ciudad, tanto el Milló como la circunvalación; Joab restauró el resto de la ciudad.

[[first-chronicles-11-9]]
^9^ David iba medrando, y Yahveh Sebaot estaba con él.

[[first-chronicles-11-10]]
^10^ He aquí los jefes de los valientes que tenía David, y que, durante su reinado, se esforzaron con él y con todo Israel para hacerle reinar, conforme a la palabra de Yahveh respecto de Israel.

[[first-chronicles-11-11]]
^11^ Esta es la lista de los héroes que tenía David: Yasobam, hijo de Jakmoní, jefe de los Treinta, que blandió su lanza e hizo más de trescientas bajas de una sola vez.

[[first-chronicles-11-12]]
^12^ Después de él Eleazar, hijo de Dodó, el ajotita, que era uno de los Tres héroes.

[[first-chronicles-11-13]]
^13^ Este estaba con David en Pas Dammim, donde los filisteos se habían concentrado para la batalla. Había allí una parcela toda de cebada, y el pueblo estaba ya huyendo delante de los filisteos,

[[first-chronicles-11-14]]
^14^ pero él se apostó en medio de la parcela, la defendió y derrotó a los filisteos. Yahveh obró allí una gran victoria.

[[first-chronicles-11-15]]
^15^ Tres de los Treinta bajaron a la peña de la cueva de Adullam, donde David, cuando los filisteos se hallaban acampados en el valle de los Refaím.

[[first-chronicles-11-16]]
^16^ David estaba a la sazón en el refugio, mientras que una guarnición de filisteos ocupaba Belén.

[[first-chronicles-11-17]]
^17^ Vínole a David un deseo y dijo: «¡Quién me diera a beber agua de la cisterna que hay a la puerta de Bélen!»

[[first-chronicles-11-18]]
^18^ Rompieron los Tres por el campamento de los filisteos, y sacaron agua de la cisterna que hay a la puerta de Belén, se la llevaron y se la ofrecieron a David, pero David no quiso beberla, sino que la derramó como libación a Yahveh,

[[first-chronicles-11-19]]
^19^ diciendo: «¡Líbreme Dios de hacer tal cosa! ¿Voy a beber yo la sangre de estos hombres junto con sus vidas? Pues con riesgo de sus vidas la han traído». Y no quiso beberla. Esto hicieron los Tres héroes.

[[first-chronicles-11-20]]
^20^ Abisay, hermano de Joab, era el primero de los Treinta. Hirió con su lanza a trescientos hombres, y conquistó renombre entre los Treinta.

[[first-chronicles-11-21]]
^21^ Fue más afamado que los Treinta, llegando a ser su capitán; pero no igualó a los Tres.

[[first-chronicles-11-22]]
^22^ Benaías, hijo de Yehoyadá, hombre valeroso y pródigo en hazañas, de Cabseel, mató a los dos héroes de Moab; además bajó y mató a un león dentro de una cisterna, en un día de nieve.

[[first-chronicles-11-23]]
^23^ Mató también a un egipcio que tenía cinco codos de altura; tenía el egipcio una lanza en su mano del tamaño de un enjullo de tejedor, pero Benaías bajó contra él con un bastón, arrancó la lanza de la mano del egipcio, y con su misma lanza le mató.

[[first-chronicles-11-24]]
^24^ Esto hizo Benaías, hijo de Yehoyadá, y se conquistó renombre entre los Tres héroes.

[[first-chronicles-11-25]]
^25^ Fue muy famoso entre los Treinta, pero no igualó a los Tres; David le hizo jefe de su guardia personal.

[[first-chronicles-11-26]]
^26^ Los valientes esforzados fueron: Asahel, hermano de Joab; Eljanán, hijo de Dodó, de Belén;

[[first-chronicles-11-27]]
^27^ Sammot, de Harod; Jeles, el pelonita;

[[first-chronicles-11-28]]
^28^ Irá, hijo de Iqqués, de Técoa; Abiézer, de Anatot;

[[first-chronicles-11-29]]
^29^ Sibbekay, de Jusá; Ilay, el ajotita;

[[first-chronicles-11-30]]
^30^ Mahray, de Netofá; Jéled, hijo de Baaná, de Netofá;

[[first-chronicles-11-31]]
^31^ Itay, hijo de Ribay, de Guibeá, de los hijos de Benjamín; Benaías, de Piratón;

[[first-chronicles-11-32]]
^32^ Juray, de los torrentes de Gaás; Abiel, el arbatita;

[[first-chronicles-11-33]]
^33^ Azmávet, de Bajurim; Elyajabá, de Saalbón;

[[first-chronicles-11-34]]
^34^ Bené Hasem, el guizonita; Jonatán, hijo de Sagué, de Arar;

[[first-chronicles-11-35]]
^35^ Ajiam, hijo de Sakar, el ararita; Elifélet, hijo de Ur;

[[first-chronicles-11-36]]
^36^ Jéfer, de Mekerá; Ajías, el pelonita;

[[first-chronicles-11-37]]
^37^ Jesró, de Carmelo; Naaray, hijo de Ezbay;

[[first-chronicles-11-38]]
^38^ Joel, hermano de Natán; Mibjar, hijo de Agrí;

[[first-chronicles-11-39]]
^39^ Sélecq, el ammonita; Najray, de Berot, escudero de Joab, hijo de Sarvia;

[[first-chronicles-11-40]]
^40^ Irá, de Yattir; Gareb, de Yattir;

[[first-chronicles-11-41]]
^41^ Urías, el hitita; Zabad, hijo de Ajlay;

[[first-chronicles-11-42]]
^42^ Adiná, hijo de Sizá, el rubenita, jefe de los rubenitas, y con él treinta;

[[first-chronicles-11-43]]
^43^ Janán, hijo de Maaká; Josafat, el mitnita;

[[first-chronicles-11-44]]
^44^ Uzzías, de Astarot: Sama y Yeiel, hijos de Jotam, de Aroer;

[[first-chronicles-11-45]]
^45^ Yediael, hijo de Simrí; Jojá, su hermano, el tisita.

[[first-chronicles-11-46]]
^46^ Eliel, el majavita; Yeribay y Yosavías, hijos de Elnaam; Yitmá, el moabita;

[[first-chronicles-11-47]]
^47^ Eliel, Obed y Yaasiel, de Sobá.
[[first-chronicles-12]]
== Capítulo 12

[[first-chronicles-12-1]]
^1^ Estos son los que vinieron donde David, a Siquelag, cuando estaba retenido lejos de Saúl, hijo de Quis. Estaban también entre los valientes que le ayudaron en la guerra.

[[first-chronicles-12-2]]
^2^ Manejaban el arco con la derecha y con la izquierda, lanzando piedras y flechas con el arco. De los hermanos de Saúl el benjaminita:

[[first-chronicles-12-3]]
^3^ Ajiézer, el jefe, y Joás, hijos de Semaá de Guibeá; Yeziel y Pélet, hijos de Azmávet; Beraká y Jehú, de Anatot;

[[first-chronicles-12-4]]
^4^ Yismaías, de Gabaón, valeroso entre los Treinta y jefe de los mismos;

[[first-chronicles-12-5]]
^5^ Jeremías, Yajaziel, Yojanán, Yozabad, de Guederot;

[[first-chronicles-12-6]]
^6^ Eluzay, Yerimot, Bealías, Semarías y Sefatías, de Jarif;

[[first-chronicles-12-7]]
^7^ Elcaná, Isaías, Azarel, Yoézer, Yasobam, coreítas;

[[first-chronicles-12-8]]
^8^ Yoelá y Zebadías, hijos de Yerojam, de Guedor.

[[first-chronicles-12-9]]
^9^ Y hubo también gaditas que se pasaron a David en el desierto, guerreros valientes, hombres de guerra, preparados para el combate, diestros con el escudo y la lanza. Sus rostros, como rostros de león, y ligeros como la gacela salvaje.

[[first-chronicles-12-10]]
^10^ Su jefe era Ezer; Obadías, el segundo; Eliab, el tercero;

[[first-chronicles-12-11]]
^11^ Masmanná, el cuarto; Yirmeyá, el quinto;

[[first-chronicles-12-12]]
^12^ Attay, el sexto; Eliel, el séptimo;

[[first-chronicles-12-13]]
^13^ Yojanán, el octavo; Elzabad, el noveno;

[[first-chronicles-12-14]]
^14^ Jeremías, el décimo; Makbannay, el undécimo;

[[first-chronicles-12-15]]
^15^ estos eran, entre los hijos de Gad, jefes del ejército; el menor mandaba sobre cien, y el mayor sobre mil.

[[first-chronicles-12-16]]
^16^ Estos fueron los que atraversaron el Jordán en el mes primero, cuando suele desbordarse por todas sus riberas, y pusieron en fuga a todos los habitantes de los valles, a oriente y occidente.

[[first-chronicles-12-17]]
^17^ También vinieron al refugio, donde estaba David, algunos de los hijos de Benjamín y Judá.

[[first-chronicles-12-18]]
^18^ Presentóse David delante de ellos y les dijo: «Si venís a mí en son de paz para ayudarme, mi corazón irá a una con vosotros; pero si es para engañanarme en favor de mis enemigos, sin que hubiere violencia en mis manos, ¡véalo el Dios de nuestros padres y lo castigue!»

[[first-chronicles-12-19]]
^19^ Entonces el espíritu revistió a Amasay, jefe de los Treinta: «¡A ti, David! ¡Contigo, hijo de Jesé! ¡Paz, paz a ti! ¡Y paz a los que te ayuden, pues tu Dios te ayuda a ti!» David los recibió y los puso entre los jefes de las tropas.

[[first-chronicles-12-20]]
^20^ También de Manasés se pasaron algunos a David, cuando éste iba con los filisteos a la guerra contra Saúl, aunque no les ayudaron, porque los tiranos de los filisteos, habido consejo, le despidieron, diciendo: «Se pasará a Saúl, su señor, con nuestras cabezas».

[[first-chronicles-12-21]]
^21^ Cuando regresó a Siquelag, pasáronse a él algunos de los hijos de Manasés: Adná, Yozabad, Yediel, Miguel, Yozabad, Elihú y Silletay, jefes de millares de Manasés.

[[first-chronicles-12-22]]
^22^ Estos ayudaron a David al frente de algunas partidas, pues todos eran hombres valientes y llegaron a ser jefes en el ejército.

[[first-chronicles-12-23]]
^23^ Cada día, en efecto, acudía gente a David para ayudarle, hasta que el campamento llegó a ser grande, como un campamento de Dios.

[[first-chronicles-12-24]]
^24^ Este es el número de los guerreros preparados para la guerra que vinieron donde David, a Hebrón, para transferirle el reino de Saúl, conforme a la orden de Yahveh.

[[first-chronicles-12-25]]
^25^ De los hijos de Judá, llevando escudo y lanza, 6.800, armados para la guerra.

[[first-chronicles-12-26]]
^26^ De los hijos de Simeón, hombres valerosos para la guerra, 7.100.

[[first-chronicles-12-27]]
^27^ De los hijos de Leví, 4.600.

[[first-chronicles-12-28]]
^28^ Yehoyadá, príncipe de los hijos de Aarón, con otros 3.700.

[[first-chronicles-12-29]]
^29^ Sadoq, joven y valeroso, con veintidós jefes de su casa paterna.

[[first-chronicles-12-30]]
^30^ De los hijos de Benjamín, hermano de Saúl, 3.000; hasta entonces la mayor parte de ellos habían permanecido fieles a la casa de Saúl.

[[first-chronicles-12-31]]
^31^ De los hijos de Efraím, 20.800 hombres valientes, famosos en sus casas paternas.

[[first-chronicles-12-32]]
^32^ De la media tribu de Manasés, 18.000, nominalmente designados para ir a proclamar rey a David.

[[first-chronicles-12-33]]
^33^ De los hijos de Isacar, duchos en discernir las oportunidades y saber lo que Israel debía hacer, 200 jefes, y todos sus hermanos bajo sus órdenes.

[[first-chronicles-12-34]]
^34^ De Zabulón, 50.000 aptos para salir a campaña, preparados para la batalla, provistos de todas las armas de guerra, audaces en la lucha, con corazón entero.

[[first-chronicles-12-35]]
^35^ De Neftalí, 1.000 jefes, y con ellos 37.000 hombres con escudo y lanza.

[[first-chronicles-12-36]]
^36^ De los danitas, preparados para la batalla, 28.600.

[[first-chronicles-12-37]]
^37^ De Aser, aptos para salir a campaña y preparados para la batalla, 40.000.

[[first-chronicles-12-38]]
^38^ Y de Transjordania, de los rubenitas, de los gaditas y de la media tribu de Manasés, provistos de todos los pertrechos de guerra para la batalla, 120.000.

[[first-chronicles-12-39]]
^39^ Todos estos hombres de guerra, formados en orden de batalla, vinieron a Hebrón con corazón entero para proclamar a David rey sobre todo Israel; y los demás israelitas estaban unánimes en hacer rey a David.

[[first-chronicles-12-40]]
^40^ Permanecieron allí con David tres días comiendo y bebiendo, porque sus hermanos les proveían.

[[first-chronicles-12-41]]
^41^ Además, los que estaban cerca y hasta de Isacar, Zabulón y Neftalí traían víveres en asnos, camellos, mulos y bueyes; provisiones de harina, tortas de higos y pasas, vino, aceite, ganado mayor y menor en abundancia; pues reinaba la alegría en Israel.
[[first-chronicles-13]]
== Capítulo 13

[[first-chronicles-13-1]]
^1^ Después de consultar David con los jefes de millar y de ciento y con todos los caudillos,

[[first-chronicles-13-2]]
^2^ dijo a toda la asamblea de Israel: «Si os parece bien y la cosa viene de Yahveh, nuestro Dios, vamos a mandar un mensaje a nuestros hermanos que han quedado a todas las regiones de Israel y, además, a los sacerdotes y levitas en sus ciudades y ejidos, para que se reúnan con nosotros;

[[first-chronicles-13-3]]
^3^ y volvamos a traer a nuestro lado el arca de nuestro Dios, ya que no nos hemos preocupado de ella desde los días de Saúl».

[[first-chronicles-13-4]]
^4^ Toda la asamblea resolvió hacerlo así, pues la propuesta pareció bien a todo el pueblo.

[[first-chronicles-13-5]]
^5^ Congregó entonces David a todo Israel, desde Sijor de Egipto hasta la Entrada de Jamat, para traer el arca de Dios desde Quiryat Yearim.

[[first-chronicles-13-6]]
^6^ Fue, pues, David, con todo Israel, hacia Baalá, a Quiryat Yearim de Judá, para subir allí el arca del Dios que lleva el Nombre de Yahveh que está sobre los querubines.

[[first-chronicles-13-7]]
^7^ Cargaron el arca de Dios en una carreta nueva y se la llevaron de la casa de Abinadab; Uzzá y Ajyó conducían la carreta.

[[first-chronicles-13-8]]
^8^ David y todo Israel bailaban delante de Dios con todas sus fuerzas, cantando y tocando cítaras, salterios, adufes, címbalos y trompetas.

[[first-chronicles-13-9]]
^9^ Al llegar a la era de Kidón, extendió Uzzá su mano para sostener el arca, porque los bueyes amenazaban volcarla.

[[first-chronicles-13-10]]
^10^ Se encendió contra Uzzá la ira de Yahveh y le hirió por haber extendido su mano hacia el arca; y Uzzá murió allí delante de Dios.

[[first-chronicles-13-11]]
^11^ Se irritó David porque Yahveh había castigado a Uzzá; y se llamó aquel lugar Peres de Uzzá hasta el día de hoy.

[[first-chronicles-13-12]]
^12^ Y tuvo David aquel día miedo a Dios, y dijo: «¿Cómo voy a llevar a mi casa el arca de Dios»

[[first-chronicles-13-13]]
^13^ Y no trasladó David el arca de Dios a su casa, a la Ciudad de David, sino que la hizo llevar a la casa de Obededom de Gat.

[[first-chronicles-13-14]]
^14^ El arca de Dios habitó tres meses en la casa de Obededom. Y bendijo Yahveh la casa de Obededom y cuanto tenía.
[[first-chronicles-14]]
== Capítulo 14

[[first-chronicles-14-1]]
^1^ Jiram, rey de Tiro, envió a David mensajeros y maderas de cedro, y también albañiles y carpinteros, para edificarle una casa.

[[first-chronicles-14-2]]
^2^ Y conoció David que Yahveh le había confirmado como rey de Israel, pues había ensalzado su realeza por amor a Israel su pueblo.

[[first-chronicles-14-3]]
^3^ Tomó David otras mujeres en Jerusalén y engendró mas hijos e hijas.

[[first-chronicles-14-4]]
^4^ Estos son los nombres de los que tuvo en Jerusalén: Sammúa, Sobab, Natán, Salomón,

[[first-chronicles-14-5]]
^5^ Yibjar, Elisúa, Elpálet,

[[first-chronicles-14-6]]
^6^ Nógah, Néfeg, Yafía,

[[first-chronicles-14-7]]
^7^ Elisamá, Baalyadá y Elifélet.

[[first-chronicles-14-8]]
^8^ Cuando los filisteos oyeron que David había sido ungido rey sobre todo Israel, subieron todos en su busca. Lo supo David y les salió al paso.

[[first-chronicles-14-9]]
^9^ Llegaron los filisteos y se desplegaron por el valle de Refaím.

[[first-chronicles-14-10]]
^10^ Consultó David a Dios, diciendo: «¿Debo subir contra los filisteos? ¿Los entregarás en mis manos?» Yahveh le respondió: «Sube, pues yo los entregaré en tu mano».

[[first-chronicles-14-11]]
^11^ Y subieron a Baal Perasim, donde David los derrotó. Dijo entonces David: «Dios ha abierto brecha entre mis enemigos por mi mano, como una brecha de aguas». Por eso se llamó a aquel lugar Baal Perasim.

[[first-chronicles-14-12]]
^12^ Abandonaron allí a sus ídolos, y dijo David: «Arrojadlos al fuego».

[[first-chronicles-14-13]]
^13^ Otra vez invadieron los filisteos el valle,

[[first-chronicles-14-14]]
^14^ y David volvió a consultar a Dios, y Dios le contestó: «No subas contra ellos: da un rodeo y atácalos frente a las balsameras.

[[first-chronicles-14-15]]
^15^ Y cuando oigas el ruido de pasos en la copa de las balsameras, saldrás a la batalla, porque Dios sale delante de ti para derrotar el campamento de los filisteos».

[[first-chronicles-14-16]]
^16^ Hizo David como le había mandado Dios, y derrotaron al campamento de los filisteos desde Gabaón hasta Guézer.

[[first-chronicles-14-17]]
^17^ La fama de David se extendió por todas las regiones, pues Yahveh le hizo temible a todas las naciones.
[[first-chronicles-15]]
== Capítulo 15

[[first-chronicles-15-1]]
^1^ Se hizo casas en la Ciudad de David, preparó un lugar para el arca de Dios y le levantó una Tienda.

[[first-chronicles-15-2]]
^2^ Entonces dijo David: «Solamente los levitas han de llevar el arca de Dios, pues a ellos los escogió Yahveh para llevar el arca de Yahveh y servirle por siempre».

[[first-chronicles-15-3]]
^3^ Congregó, pues, David a todo Israel en Jerusalén para subir el arca de Yahveh al lugar que para ella había preparado.

[[first-chronicles-15-4]]
^4^ David reunió también a los hijos de Aarón y a los levitas:

[[first-chronicles-15-5]]
^5^ De los hijos de Quehat: a Uriel, el jefe, y a sus hermanos, 120;

[[first-chronicles-15-6]]
^6^ de los hijos de Merarí: a Asaías, el jefe, y a sus hermanos, 220;

[[first-chronicles-15-7]]
^7^ de los hijos de Guersom: a Joel, el jefe, y a sus hermanos, 130;

[[first-chronicles-15-8]]
^8^ de los hijos de Elisafán: a Semaías, el jefe, y a sus hermaos, doscientos;

[[first-chronicles-15-9]]
^9^ de los hijos de Hebrón: a Eliel, el jefe, y a sus hermanos, ochenta;

[[first-chronicles-15-10]]
^10^ de los hijos de Uzziel: a Amminadab, el jefe, y a sus hermanos, 112.

[[first-chronicles-15-11]]
^11^ También llamó David a los sacerdotes Sadoq y Abiatar, y a los levitas Uriel, Asaías, Joel, Semaáis, Eliel y Amminadab,

[[first-chronicles-15-12]]
^12^ y les dijo: «Vosotros sois los cabezas de familia de los levitas. Santificaos, vosotros y vuestros hermanos, para subir el arca de Yahveh, el Dios de Israel, al lugar que para ella tengo preparado;

[[first-chronicles-15-13]]
^13^ pues por no haber estado vosotros la vez primera, Yahveh, nuestro Dios, hizo brecha en nosotros, ya que no le consultamos conforme a la norma».

[[first-chronicles-15-14]]
^14^ Se santificaron, pues, los sacerdotes y los levitas, para subir el arca de Yahveh, Dios de Israel.

[[first-chronicles-15-15]]
^15^ Y los levitas trasladaron el arca de Dios a hombros, como lo había ordenado Moisés, según la palabra de Yahveh, llevando los varales sobre los hombros.

[[first-chronicles-15-16]]
^16^ Dijo David a los jefes de los levitas que dispusieran a sus hermanos los cantores, con instrumentos músicos, salterios, cítaras y címbalos, para que los hiciesen resonar, alzando la voz con júbilo.

[[first-chronicles-15-17]]
^17^ Los levitas designaron a Hemán, hijo de Joel; y de sus hermanos, a Asaf, hijo de Berekías; y de los hijos de Merarí, hermanos suyos, a Etán, hijo de Cusaías.

[[first-chronicles-15-18]]
^18^ Y con ellos, como segundos, a sus hermanos Zacarías, hijo de Yaaziel, Semiramot, Yejiel, Unní, Eliab, Benaías, Maaseías, Mattitías, Eliflehú, Miqneías, Obededom y Yeiel, porteros.

[[first-chronicles-15-19]]
^19^ Los cantores Hemán, Asaf y Etán hacían resonar címbalos de bronce.

[[first-chronicles-15-20]]
^20^ Zacarías, Yaaziel, Semiramot, Yejiel, Unní, Eliab, Maaseías y Benaías tenían salterios de tonos altos.

[[first-chronicles-15-21]]
^21^ Mattitías, Eliflehú, Miqneías, Obededom, Yeiel y Azazaías tenían cítaras de octava, para dirigir el canto.

[[first-chronicles-15-22]]
^22^ Kenanías, jefe de los levitas encargados del transporte, dirigía el traslado, porque era hombre entendido.

[[first-chronicles-15-23]]
^23^ Berekías y Elcaná eran porteros del arca.

[[first-chronicles-15-24]]
^24^ Sebanías, Josafat, Natanael, Amasay, Zacarías, Benaías y Eliezer, sacerdotes, tocaban las trompetas delante del arca de Dios. Obededom y Yejiyías eran porteros del arca.

[[first-chronicles-15-25]]
^25^ Así pues, David los ancianos de Israel y los jefes de millares, fueron a traer el arca de la alianza de Yahveh, desde la casa de Obededom, con alborozo.

[[first-chronicles-15-26]]
^26^ Y habiendo Dios ayudado a los levitas portadores del arca de la alianza de Yahveh, sacrificaron siete becerros y siete carneros.

[[first-chronicles-15-27]]
^27^ David iba revestido de un manto de lino fino, lo mismo que todos los levitas, que portaban el arca, los cantores y Kenanías, el jefe que dirigía el traslado. Llevaba también David sobre sí un efod de lino.

[[first-chronicles-15-28]]
^28^ Todo Israel subía el arca de la alianza de Yahveh entre clamores y resonar de cuernos, trompetas y címbalos, y haciendo sonar los salterios y las cítaras.

[[first-chronicles-15-29]]
^29^ Cuando el arca de la alianza de Yahveh entró en la Ciudad de David, Mikal, hija de Saúl, estaba mirando por una ventana, y vio al rey David que saltaba y bailaba, y le despreció en su corazón.
[[first-chronicles-16]]
== Capítulo 16

[[first-chronicles-16-1]]
^1^ Introdujeron el arca de Dios y la colocaron en medio de la Tienda que David había hecho levantar para ella; y ofrecieron ante Dios holocaustos y sacrificios de comunión.

[[first-chronicles-16-2]]
^2^ Cuando David hubo acabado de ofrecer los holocaustos y los sacrificios de comunión, bendijo al pueblo en nombre de Yahveh,

[[first-chronicles-16-3]]
^3^ y repartió a todo el pueblo de Israel, hombres y mujeres, a cada uno una torta de pan, un pastel de dátiles y un pastel de pasas.

[[first-chronicles-16-4]]
^4^ David estableció los levitas que habían de hacer el servicio delante del arca de Yahveh, celebrando, glorificando y alabando a Yahveh, el Dios de Israel.

[[first-chronicles-16-5]]
^5^ Asaf era el jefe; Zacarías era el segundo; luego Uzziel, Semiramot, Yejiel, Mattitías, Eliab, Benaías, Obededom y Yeiel, con salterios y cítaras. Asaf hacía sonar los címbalos.

[[first-chronicles-16-6]]
^6^ Los sacerdotes Benaáis y Yajaziel tocaban sin interrupción las trompetas delante del arca de la alianza de Dios.

[[first-chronicles-16-7]]
^7^ Aquel día David, alabando el primero a Yahveh, entregó a Asaf y a sus hermanos este canto:

[[first-chronicles-16-8]]
^8^ ¡Dad gracias a Yahveh, aclamad su nombre, divulgad entre los pueblos sus hazañas!

[[first-chronicles-16-9]]
^9^ ¡Cantadle, salmodiad para él, sus maravillas todas recitad!

[[first-chronicles-16-10]]
^10^ ¡Gloriaos en su santo Nombre, se alegre el corazón de los que buscan a Yahveh!

[[first-chronicles-16-11]]
^11^ ¡Buscad a Yahveh y su fuerza, id tras su rostro sin descanso!

[[first-chronicles-16-12]]
^12^ Recordad las maravillas que él ha hecho, sus prodigios y los juicios de su boca,

[[first-chronicles-16-13]]
^13^ raza de Israel, su servidor, hijos de Jacob, sus elegidos.

[[first-chronicles-16-14]]
^14^ El, Yahveh, es nuestro Dios, por toda la tierra sus juicios.

[[first-chronicles-16-15]]
^15^ Recordad para siempre su alianza, palabra que impuso a mil generaciones;

[[first-chronicles-16-16]]
^16^ lo que pactó con Abraham, el juramento que hizo a Isaac.

[[first-chronicles-16-17]]
^17^ Y que puso a Jacob como precepto, a Israel como alianza eterna,

[[first-chronicles-16-18]]
^18^ diciendo: «Yo te daré la tierra de Canaán, por parte de vuestra herencia»,

[[first-chronicles-16-19]]
^19^ cuando erais escasa gente, poco numerosos, y forasteros allí.

[[first-chronicles-16-20]]
^20^ Cuando iban de nación en nación desde un reino a otro pueblo,

[[first-chronicles-16-21]]
^21^ a nadie permitió oprimirles. Por ellos castigó a los reyes.

[[first-chronicles-16-22]]
^22^ «Guardaos de tocar a mis ungidos ni mal alguno hagáis a mis profetas».

[[first-chronicles-16-23]]
^23^ Cantad a Yahveh toda la tierra anunciad su salvación día tras día.

[[first-chronicles-16-24]]
^24^ Contad su gloria a las naciones, a todos los pueblos sus maravillas.

[[first-chronicles-16-25]]
^25^ Que es grande Yahveh y muy digno de alabanza, más temible que todos los dioses.

[[first-chronicles-16-26]]
^26^ Porque nada son todos los dioses de los pueblos, mas Yahveh los cielos hizo.

[[first-chronicles-16-27]]
^27^ Gloria y majestad están ante él, fortaleza y alegría en su Morada.

[[first-chronicles-16-28]]
^28^ ¡Rendid a Yahveh, familias de los pueblos, rendid a Yahveh gloria y poder!

[[first-chronicles-16-29]]
^29^ ¡Rendid a Yahveh la gloria de su Nombre! Traed ofrendas y en sus atrios entrad. ¡Postraos ante Yahveh en esplendor sagrado!

[[first-chronicles-16-30]]
^30^ ¡Tiemble ante su faz la tierra entera! El orbe está seguro, no vacila.

[[first-chronicles-16-31]]
^31^ Alégrense los cielos y la tierra jubile. Decid entre las gentes: «¡Yahveh es rey!»

[[first-chronicles-16-32]]
^32^ ¡Retumbe el mar y cuanto encierra! ¡Exulte el campo y cuanto en él existe!

[[first-chronicles-16-33]]
^33^ Griten de júbilo los árboles de los bosque ante Yahveh, pues viene a juzgar la tierra.

[[first-chronicles-16-34]]
^34^ ¡Dad gracias a Yahveh, porque es bueno, porque es eterno su amor!

[[first-chronicles-16-35]]
^35^ Y decid: «¡Sálvanos, oh Dios de nuestra salvación! Reúnenos y líbranos de las naciones, para dar gracias a tu Nombre santo y gloriarnos en tu alabanza».

[[first-chronicles-16-36]]
^36^ Bendito sea Yahveh, el Dios de Israel, por eternidad de eternidades». Y todo el pueblo dijo: «Amén». Y alabó a Yahveh.

[[first-chronicles-16-37]]
^37^ David dejó allí, ante el arca de la alianza de Yahveh, a Asaf y a sus hermanos, para el ministerio continuo delante del arca, según el rito de cada día;

[[first-chronicles-16-38]]
^38^ y a Obededom, con sus hermanos, en número de 68, y a Obededom, hijo de Yedutún, y a Josá, como porteros;

[[first-chronicles-16-39]]
^39^ y el sacerdote Sadoq y a sus hermanos, los sacerdotes, delante de la Morada de Yahveh, en el alto de Gabaón,

[[first-chronicles-16-40]]
^40^ para que ofreciesen continuamente holocaustos a Yahveh en el altar de los holocaustos, por la mañana y por la tarde, según todo lo escrito en la Ley que Yahveh había mandado a Israel.

[[first-chronicles-16-41]]
^41^ Con ellos estaban Hemán y Yedutún y los restantes escogidos y nominalmente designados para alabar a Yahveh: «Porque es eterno su amor».

[[first-chronicles-16-42]]
^42^ Y con ellos, Hemán y Yedutún, que hacían sonar trompetas, címbalos e instrumentos para los cánticos de Dios. Los hijos de Yedutún eran porteros.

[[first-chronicles-16-43]]
^43^ Luego, todo el pueblo se fue, cada cual a su casa; también David se volvió para bendecir su casa.
[[first-chronicles-17]]
== Capítulo 17

[[first-chronicles-17-1]]
^1^ Morando ya David en su casa, dijo a Natán, profeta: «Mira, yo habito en una casa de cedro, mientras el arca de la alianza de Yahveh está bajo pieles».

[[first-chronicles-17-2]]
^2^ Respondió Natán a David: «Haz todo cuanto tienes en tu corazón, porque Dios está contigo».

[[first-chronicles-17-3]]
^3^ Pero aquella misma noche vino la palabra de Dios a Natán en estos términos:

[[first-chronicles-17-4]]
^4^ «Vete y di a mi siervo David: Así dice Yahveh: No serás tú quien me edifique Casa para que habite yo en ella.

[[first-chronicles-17-5]]
^5^ Pues no he habitado en casa alguna desde el día en que hice subir a los israelitas hasta el día de hoy; sino que he andado de tienda en tienda y de morada en morada.

[[first-chronicles-17-6]]
^6^ En todo el tiempo que he ido de un lado para otro con todo Israel, ¿he dicho acaso a alguno de los Jueces de Israel, a los que mandé me apacentaran a mi pueblo: Por qué no me edificáis una Casa de cedro?

[[first-chronicles-17-7]]
^7^ Di, pues, ahora esto a mi siervo David: Así habla Yahveh Sebaot: Yo te he tomado del pastizal, de detrás del rebaño, para que seas caudillo de mi pueblo Israel.

[[first-chronicles-17-8]]
^8^ He estado contigo donde quiera que has ido, he eliminado a todos tus enemigos de delante de ti y voy a hacerte un nombre grande como el nombre de los grandes de la tierra.

[[first-chronicles-17-9]]
^9^ Fijaré un lugar a mi pueblo Israel, y lo plantaré allí para que more en él; no será ya perturbado, y los malhechores no seguirán oprimiéndole como al principio,

[[first-chronicles-17-10]]
^10^ y como en los días en que instituí Jueces sobre mi pueblo Israel. Someteré a todos tus enemigos. Yahveh te anuncia que Yahveh te edificará una casa.

[[first-chronicles-17-11]]
^11^ Cuando se cumplan tus días para ir con tus padres, afirmaré después de ti la descendencia que saldrá de tus entrañas y consolidaré su reino.

[[first-chronicles-17-12]]
^12^ El me edificará un Casa y yo afirmaré su trono para siempre.

[[first-chronicles-17-13]]
^13^ Yo seré para él un padre, y él será para mi un hijo, y no apartaré de él mi amor, como le aparté de aquel que fue antes de ti.

[[first-chronicles-17-14]]
^14^ Yo le estableceré en mi Casa y en mi reino para siempre, y su trono estará firme eternamente».

[[first-chronicles-17-15]]
^15^ Conforme a todas estas palabras, y conforme a toda esta visión, habló Natán a David.

[[first-chronicles-17-16]]
^16^ Entró entonces el rey David, se sentó delante de Yahveh y dijo: «¿Quien soy yo, oh Yahveh Dios, y qué mi casa, que me has traído hasta aquí?

[[first-chronicles-17-17]]
^17^ Y aun esto es poco a tus ojos, oh Dios, que hablas también a la casa de tu siervo para el futuro lejano y me miras como si fuera un hombre distinguido, oh Yahveh Dios.

[[first-chronicles-17-18]]
^18^ ¿Qué más podrá añadirte David por la gloria que concedes a tu siervo?

[[first-chronicles-17-19]]
^19^ Oh Yahveh, por amor de tu siervo, y según tu corazón, has hecho todas estas cosas tan grandes, para manifestar todas estas grandezas.

[[first-chronicles-17-20]]
^20^ Oh Yahveh, nadie com tú, ni hay Dios fuera de ti, según todo lo que hemos oído con nuestros oídos.

[[first-chronicles-17-21]]
^21^ Y ¿qué otro pueblo hay sobre la tierra como tu pueblo Israel, a quien un dios haya ido a rescatar para hacerle su pueblo, dándole renombre por medio de obras grandes y terribles, arrojando naciones de delante de tu pueblo al que rescataste de Egipto?

[[first-chronicles-17-22]]
^22^ Tú has constituido a Israel tu pueblo como pueblo tuyo para siempre; y tú, Yahveh, te has hecho su Dios.

[[first-chronicles-17-23]]
^23^ Ahora, pues, oh Yahveh, mantén firme eternamente la palabra que has dirigido a tu siervo y a su casa; y haz según tu palabra.

[[first-chronicles-17-24]]
^24^ Sí, sea firme; y sea tu nombre por siempre engrandecido, y que diga: “Yahveh Sebaot, el Dios de Israel, es el Dios para Israel.” Y que la casa de tu siervo David subsista en tu presencia.

[[first-chronicles-17-25]]
^25^ Ya que tú, oh Dios mío, has revelado a tu siervo que vas a edificarle una casa, por eso tu siervo ha encontrado valor para orar en tu presencia.

[[first-chronicles-17-26]]
^26^ Ahora, pues, Yahveh, tú eres Dios, y tú has prometido esta dicha a tu siervo.

[[first-chronicles-17-27]]
^27^ Y ahora te has dignado bendecir la casa de tu siervo, para que permanezca por siempre en tu presencia, porque lo que tú bendices, Yahveh, queda bendito por siempre».
[[first-chronicles-18]]
== Capítulo 18

[[first-chronicles-18-1]]
^1^ Después de esto, batió David a los filisteos y los humilló, tomando Gat y sus dependencias de manos de los filisteos.

[[first-chronicles-18-2]]
^2^ Batió también a los moabitas, que quedaron sometidos a David, pagando tributo.

[[first-chronicles-18-3]]
^3^ Batió David a Hadadézer, rey de Sobá, en Jamat, cuando éste iba a establecer su dominio sobre el río Eufrates.

[[first-chronicles-18-4]]
^4^ David apresó mi carros, 7.000 soldados de carro y 20.000 hombres de a pie; David desjarretó toda la caballería de los carros, reservando cien tiros.

[[first-chronicles-18-5]]
^5^ Los arameos de Damasco vinieron en socorro de Hadadézer, rey de Sobá, y David hizo 22.000 bajas a los arameos.

[[first-chronicles-18-6]]
^6^ Estableció David gobernadores en Aram de Damasco, y los arameos quedaron sometidos a David, pagando tributo. Yahveh hizo triunfar a David doquiera que iba.

[[first-chronicles-18-7]]
^7^ Tomó David los escudos de oro que llevaban los servidores de Hadadézer y los llevó a Jerusalén.

[[first-chronicles-18-8]]
^8^ De Tibjat y Kun, ciudades de Hadadézer, tomó David una gran cantidad de bronce, con el cual hizo Salomón el Mar de bronce, las columnas y los utensilios de bronce.

[[first-chronicles-18-9]]
^9^ Cuando Tou, rey de Jamat, supo que David había derrotado a todas las fuerzas de Hadadézer, rey de Sobá,

[[first-chronicles-18-10]]
^10^ envió a Hadoram, su hijo, donde el rey David para saludarle y para felicitarle por haber atacado y vencido a Hadadézer, ya que Tou estaba en guerra con Hadadézer. Traía Hadoram toda clase de objetos de oro, de plata y de bronce.

[[first-chronicles-18-11]]
^11^ El rey David los consagró también a Yahveh, con la plata y el oro que había tomado a todas las naciones: a Edom, a Moab, a los ammonitas, a los filisteos y a los amalecitas.

[[first-chronicles-18-12]]
^12^ Abisay, hijo de Sarvia, derrotó en el Valle de la Sal a 18.000 edomitas;

[[first-chronicles-18-13]]
^13^ puso gobernadores en Edom; y todos los edomitas quedaron sometidos a David. Yahveh hizo triunfar a David dondequiera iba.

[[first-chronicles-18-14]]
^14^ Reinó David sobre todo Israel administrando derecho y justicia a todo el pueblo.

[[first-chronicles-18-15]]
^15^ Joab, hijo de Sarvia, era jefe del ejército; Josafat, hijo de Ajilud, era el heraldo;

[[first-chronicles-18-16]]
^16^ Sadoq, hijo de Ajitub, y Ajimélek, hijo de Abiatar, eran sacerdotes; Savsá era secretario;

[[first-chronicles-18-17]]
^17^ Benaías, hijo de Yehoyadá, mandaba a los kereteos y a los peleteos, y los hijos de David eran los primeros junto al rey.
[[first-chronicles-19]]
== Capítulo 19

[[first-chronicles-19-1]]
^1^ Después de esto, murió Najas, rey de los ammonitas, y en su lugar reinó su hijo.

[[first-chronicles-19-2]]
^2^ Dijo entonces David: «Tendré con Janún, hijo de Najás, la misma benevolencia que su padre tuvo conmigo». Y envió David mensajeros para que le consolaran por su padre. Pero cuando los servidores de David llegaron al país de los ammonitas, donde Janún, para consolarle,

[[first-chronicles-19-3]]
^3^ dijeron los príncipes de los ammonitas a Janún: «¿ Es que David ha enviado a consolarte porque quiere hacer honor a tu padre ante tus ojos? ¿No han venido a ti sus servidores más bien para explorar y destruir y para espiar el país?»

[[first-chronicles-19-4]]
^4^ Prendió, pues, Janún a los servidores de David, les rapó, cortó a media altura sus vestidos, y los despachó.

[[first-chronicles-19-5]]
^5^ Fueron a avisar a David lo de estos hombres; y él envió gente a su encuentro, porque los hombres estaban cubiertos de vergüenza. El rey les dijo: «Quedaos en Jericó hasta que os crezca la barba y después volveréis».

[[first-chronicles-19-6]]
^6^ Cuando los ammonitas vieron que se habían hecho odiosos a David, Janún y los ammonitas enviaron mil talentos de plata para tomar a sueldo carros y hombres de carro de Aram de Mesopotamia, de Aram de Maaká y de Sobá.

[[first-chronicles-19-7]]
^7^ Tomaron a sueldo 32.000 carros y al rey de Maaká con su ejército, los cuales vinieron y acamparon frente a Medebá. Los ammonitas se congregaron también desde sus ciudades y salieron a campaña.

[[first-chronicles-19-8]]
^8^ David lo supo y envió a Joab con toda la tropa y con los valientes.

[[first-chronicles-19-9]]
^9^ Salieron a campaña los ammonitas y se ordenaron en batalla a la entrada de la ciudad, mientras que los reyes que habían venido estaban aparte en el campo.

[[first-chronicles-19-10]]
^10^ Viendo Joab que tenía un frente de combate por delante y otro por detrás escogió los mejores de Israel y los puso en línea contra Aram.

[[first-chronicles-19-11]]
^11^ Puso el resto del ejército al mando de su hermano Abisay y lo ordenó en batalla frente a los ammonitas.

[[first-chronicles-19-12]]
^12^ Dijo Joab: «Si los arameos me dominan, ven en mi ayuda; y si los hijos de Ammón te dominan a ti, iré en tu socorro.

[[first-chronicles-19-13]]
^13^ ¡Ten fortaleza y esforcémonos por nuestro pueblo y por las ciudades de nuestro Dios! ¡Y que Yahveh haga lo que bien le parezca!»

[[first-chronicles-19-14]]
^14^ Y avanzó Joab con su ejercito para luchar contra los arameos, que huyeron delante de él.

[[first-chronicles-19-15]]
^15^ Viendo los ammonitas que los arameos emprendían la fuga, huyeron también ellos ante Abisay, hermano de Joab, y entraron en la ciudad, mientras que Joab volvió a Jerusalén.

[[first-chronicles-19-16]]
^16^ Al ver los arameos que habían sido vencidos por Israel, enviaron emisarios para hacer venir a los arameos del otro lado del Río; venía a su cabeza Sofak, jefe de las tropas de Hadadézer.

[[first-chronicles-19-17]]
^17^ Se dio aviso a David, que reuniendo a todo Israel pasó el Jordán, llegó donde ellos estaban y tomó posiciones frente a ellos. Se puso David en orden de batalla contra los arameos y éstos trabaron combate con él.

[[first-chronicles-19-18]]
^18^ Huyeron los arameos ante Israel; y David mató a los arameos 7.000 hombres de carro y 40.000 hombres de a pie. Mató también a Sofak, jefe del ejército.

[[first-chronicles-19-19]]
^19^ Cuando los vasallos de Hadadézer vieron que habían sido derrotados por Israel, hicieron la paz con David y le quedaron sometidos; y los arameos no se atrevieron a seguir ayudando a los ammonitas.
[[first-chronicles-20]]
== Capítulo 20

[[first-chronicles-20-1]]
^1^ A la vuelta del año, al tiempo que los reyes salen a campaña, llevó Joab el grueso del ejército y asoló el país de los ammonitas; después fue a poner sitio a Rabbá. Mientras, David se quedó en Jerusalén. Entretanto Joab derrotó a Rabbá y la destruyó.

[[first-chronicles-20-2]]
^2^ David tomó de la cabeza de Milkom la corona y encontró que pesaba un talento de oro. Había en ella una piedra preciosa que fue puesta en la cabeza de David, y se llevó un enorme botín de la ciudad.

[[first-chronicles-20-3]]
^3^ Hizo salir a la gente que había en ella y la empleó en las sierras, en los trillos de dientes de hierro y en las hachas de hierro. Hizo lo mismo con todas las ciudades de los ammonitas, y David se volvió con todo su ejército a Jerusalén.

[[first-chronicles-20-4]]
^4^ Después de esto, tuvo lugar una batalla en Guézer contra los filisteos; entonces Sibbekay, jusatita, mató a Sippay, uno de los descendientes de Rafá. Los filisteos fueron sometidos.

[[first-chronicles-20-5]]
^5^ Hubo otra guerra contra los filisteos, y Eljanán, hijo de Yaír, mató a Lajmí, hermano de Goliat el de Gat, el asta de su lanza era como un enjullo de tejedor.

[[first-chronicles-20-6]]
^6^ Hubo guerra de nuevo en Gat y había un hombre de gran estatura, que tenía veinticuatro dedos, seis en cada extremidad. También éste descendía de Rafá.

[[first-chronicles-20-7]]
^7^ Desafió a Israel y le mató Jonatán, hijo de Simá, hermano de David.

[[first-chronicles-20-8]]
^8^ Estos descendían de Rafá de Gat y sucumbieron a manos de David y de sus veteranos.
[[first-chronicles-21]]
== Capítulo 21

[[first-chronicles-21-1]]
^1^ Alzóse Satán contra Israel, e incitó a David a hacer el censo del pueblo.

[[first-chronicles-21-2]]
^2^ Dijo, pues, David a Joab y a los jefes del ejército: «Id, contad los israelitas desde Berseba hasta Dan, y volved después para que yo sepa su número».

[[first-chronicles-21-3]]
^3^ Respondió Joab: «¡Multiplique Yahveh su pueblo cien veces más de lo que es! ¿Acaso no son, oh rey mi señor, todos ellos siervos de mi señor? ¿Por qué, pues, pide esto mi señor? ¿Por qué acarrear culpa sobre Israel?»

[[first-chronicles-21-4]]
^4^ Pero prevaleció la orden del rey sobre Joab, de modo que éste salió y recorrió todo Israel, volviéndose después a Jerusalén.

[[first-chronicles-21-5]]
^5^ Joab entregó a David la cifra del censo del pueblo: había en todo Israel 1.100.000 hombres capaces de manejar las armas; había en Judá 470.000 hombres capaces de manejar las armas.

[[first-chronicles-21-6]]
^6^ No incluyó en este censo a Leví y Benjamín, porque Joab detestaba la orden del rey.

[[first-chronicles-21-7]]
^7^ Desagradó esto a Dios, por lo cual castigó a Israel.

[[first-chronicles-21-8]]
^8^ Entonces dijo David a Dios: «He cometido un gran pecado haciendo esto. Pero ahora perdona, te ruego, la falta de tu siervo, pues he sido muy necio».

[[first-chronicles-21-9]]
^9^ Y Yahveh habló a Gad, vidente de David, en estos términos:

[[first-chronicles-21-10]]
^10^ «Anda y di a David: Así dice Yahveh: Tres cosas te propongo; elige una de ellas y la llevaré a cabo».

[[first-chronicles-21-11]]
^11^ Llegó Gad donde David y le dijo: «Así dice Yahveh: Elige para ti:

[[first-chronicles-21-12]]
^12^ tres años de hambre, o tres meses de derrotas ante tus enemigos, con la espada de tus enemigos a la espalda, o bien tres días durante los cuales la espada de Yahveh y la peste anden por la tierra y el ángel de Yahveh haga estragos en todo el territorio de Israel. Ahora, pues, mira qué debo responder al que me envía».

[[first-chronicles-21-13]]
^13^ David respondió a Gad: «Estoy en gran angustia. Pero ¡caiga yo en manos de Yahveh, que es grande su misericordia, y no caiga en manos de los hombres!»

[[first-chronicles-21-14]]
^14^ Yahveh envió la peste sobre Israel, y cayeron de Israel 70.000 hombres.

[[first-chronicles-21-15]]
^15^ Mandó Dios un ángel contra Jerusalén para destruirla; pero cuando ya estaba destruyéndola, miró Yahveh y se arrepintió del estrago, y dijo al ángel Exterminador: «¡Basta ya; retira tu mano!» El ángel de Yahveh estaba junto a la era de Ornán el jebuseo.

[[first-chronicles-21-16]]
^16^ Alzando David los ojos vio al ángel de Yahveh que estaba entre la tierra y el cielo con una espada desenvainada en su mano, extendida contra Jerusalén. Entonces David y los ancianos, cubiertos de sayal, cayeron rostro en tierra.

[[first-chronicles-21-17]]
^17^ Y dijo David a Dios: «Yo fui quien mandé hacer el censo del pueblo. Yo fui quien pequé, yo cometí el mal; pero estas ovejas, ¿qué han hecho? ¡Oh Yahveh, Dios mío, caiga tu mano sobre mí y sobre la casa de mi padre, y no haya plaga entre tu pueblo!»

[[first-chronicles-21-18]]
^18^ Entonces el ángel de Yahveh dijo a Gad que diera a David la orden de subir para alzar un altar a Yahveh en la era de Ornán el jebuseo.

[[first-chronicles-21-19]]
^19^ Subió David, según la orden que Gad le había dado en nombre de Yahveh.

[[first-chronicles-21-20]]
^20^ Ornán, que estaba trillando el trigo, se volvió y, al ver al ángel, él y sus cuatro hijos se escondieron.

[[first-chronicles-21-21]]
^21^ Cuando David llegó junto a Ornán, miró Ornán y, viendo a David, salió de la era y postróse ante David, rostro en tierra.

[[first-chronicles-21-22]]
^22^ Dijo David a Ornán: «Dame el sitio de esta era para erigir en él un altar a Yahveh - dámelo por su justo valor en plata - para que la plaga se retire del pueblo».

[[first-chronicles-21-23]]
^23^ Respondió Ornán a David: «Tómalo, y haga mi señor el rey lo que bien le parezca. Mira que te doy los bueyes para holocaustos, los trillos para leña y el trigo para la ofrenda; todo te lo doy».

[[first-chronicles-21-24]]
^24^ Replicó el rey David a Ornán: «No; quiero comprártelo por su justo precio, pues no tomaré para Yahveh lo que es tuyo, ni ofreceré holocaustos de balde».

[[first-chronicles-21-25]]
^25^ Y David dio a Ornán por el sitio la suma de seiscientos siclos de oro.

[[first-chronicles-21-26]]
^26^ David erigió allí un altar a Yahveh y ofreció holocaustos y sacrificios de comunión e invocó a Yahveh, el cual le respondió con fuego del cielo sobre el altar del holocausto.

[[first-chronicles-21-27]]
^27^ Entonces Yahveh ordenó al ángel que volviera la espada a la vaina.

[[first-chronicles-21-28]]
^28^ En aquel tiempo, al ver David que Yahveh le había respondido en la era de Ornán el jebuseo, ofreció allí sacrificios.

[[first-chronicles-21-29]]
^29^ Pues la Morada de Yahveh, que Moisés había hecho en el desierto, y el altar de los holocaustos, estaban a la sazón en el alto de Gabaón;

[[first-chronicles-21-30]]
^30^ pero David no se había atrevido a presentarse delante de Dios para consultarle, porque estaba aterrado ante la espada del ángel de Yahveh.
[[first-chronicles-22]]
== Capítulo 22

[[first-chronicles-22-1]]
^1^ Entonces dijo David: «¡Aquí está la Casa de Yahveh Dios, y aquí el altar de los holocaustos para Israel!»

[[first-chronicles-22-2]]
^2^ Mandó, pues, David reunir a los forasteros residentes en la tierra de Israel, y designó canteros que preparasen piedras talladas para la construcción de la Casa de Dios.

[[first-chronicles-22-3]]
^3^ Preparó también David hierro en abundancia para la clavazón de las hojas de las puertas y para las grapas, incalculable cantidad de bronce,

[[first-chronicles-22-4]]
^4^ y madera de cedro inmumerable, pues los sidonios y los tirios trajeron a David madera de cedro en abundancia.

[[first-chronicles-22-5]]
^5^ Porque David se decía: «Mi hijo Salomón es todavía joven y débil, y la Casa que ha de edificarse para Yahveh debe ser grandiosa sobre toda ponderación, para tener nombre y gloria en todos los países. Así que le haré yo los preparativos». Hizo David, en efecto, grandes preparativos antes de su muerte.

[[first-chronicles-22-6]]
^6^ Después llamó a su hijo Salomón y le mandó que edificase una Casa para Yahveh, el Dios de Israel.

[[first-chronicles-22-7]]
^7^ Dijo David a Salomón: «Hijo mío, yo había deseado edificar una Casa al nombre de Yahveh, mi Dios.

[[first-chronicles-22-8]]
^8^ Pero me fue dirigida la palabra de Yahveh, que me dijo: “Tú has derramado mucha sangre y hecho grandes guerras; no podrás edificar tú la Casa a mi nombre, porque has derramado en tierra mucha sangre delante de mí.

[[first-chronicles-22-9]]
^9^ Mira que te va a nacer un hijo, que será hombre de paz; le concederé paz con todos sus enemigos en derredor, porque Salomón será su nombre y en sus días concederé paz y tranquilidad a Israel.

[[first-chronicles-22-10]]
^10^ El edificará una Casa a mi nombre; él será para mí un hijo y yo seré para él un padre y consolidaré el trono de su reino sobre Israel para siempre.”

[[first-chronicles-22-11]]
^11^ Ahora, pues, hijo mío, que Yahveh sea contigo, para que logres edificar la Casa de Yahveh tu Dios, como él de ti lo ha predicho.

[[first-chronicles-22-12]]
^12^ Quiera Yahveh concederte prudencia y entendimiento y darte órdemes sobre Israel, para que guardes la Ley de Yahveh tu Dios.

[[first-chronicles-22-13]]
^13^ No prosperarás si no cuidas de cumplir los decretos y las normas que Yahveh ha prescrito a Moisés para Israel. ¡Sé fuerte y ten buen ánimo! ¡No temas ni desmayes!

[[first-chronicles-22-14]]
^14^ Mira lo que yo he preparado en mi pequeñez para la Casa de Yahveh: 100.000 talentos de oro, un millón de talentos de plata y una cantidad de cobre y de hierro incalculable por su abundancia. He preparado también maderas y piedras que tú podrás aumentar.

[[first-chronicles-22-15]]
^15^ Y tienes a mano muchos obreros, canteros, artesanos en piedra y en madera, expertos en toda clase de obras.

[[first-chronicles-22-16]]
^16^ El oro, la plata, el bronce y el el hierro son sin número. ¡Levántate, pues! Manos a la obra y que Yahveh sea contigo».

[[first-chronicles-22-17]]
^17^ Mandó David a todos los jefes de Israel que ayudasen a su hijo Salomón:

[[first-chronicles-22-18]]
^18^ «¿No está con vosotros Yahveh vuestro Dios? ¿Y no os ha dado paz por todos lados? Pues él ha entregado en mis manos a los habitantes del país y el país está sujeto ante Yahveh y ante su pueblo.

[[first-chronicles-22-19]]
^19^ Aplicad ahora vuestro corazón y vuestra alma a buscar a Yahveh vuestro Dios. Levantaos y edificad el santuario de Yahveh Dios, para trasladar el arca de la alianza de Yahveh y los utensilios del santuario de Dios a la Casa que ha de edificarse al Nombre de Yahveh».
[[first-chronicles-23]]
== Capítulo 23

[[first-chronicles-23-1]]
^1^ Viejo ya David y colmado de días, proclamó a su hijo Salomón rey de Israel.

[[first-chronicles-23-2]]
^2^ Reunió a todos los jefes de Israel, a los sacerdotes y a los levitas,

[[first-chronicles-23-3]]
^3^ y se hizo el censo de los levitas de treinta años para arriba; su número, contado por cabezas uno a uno, fue de 38.000 varones.

[[first-chronicles-23-4]]
^4^ De éstos, 24.000 estaban al frente del servicio de la Casa de Yahveh; 6.000 eran escribas y jueces,

[[first-chronicles-23-5]]
^5^ 4.000 eran porteros y 4.000 alababan a Yahveh con los instrumentos que David había fabricado para rendir alabanzas.

[[first-chronicles-23-6]]
^6^ David los distribuyó por clases, según los hijos de Leví: Guersón, Quehat y Merarí.

[[first-chronicles-23-7]]
^7^ De los guersonitas: Ladán y Simí.

[[first-chronicles-23-8]]
^8^ Hijos de Ladán: Yejiel, el primero, Zetam y Joel, tres.

[[first-chronicles-23-9]]
^9^ Hijos de Simí: Selomit, Jaziel y Harán, tres. Estos son los jefes de las casas paternas de Ladán.

[[first-chronicles-23-10]]
^10^ Hijos de Simí: Yájat, Zizá, Yeús y Beriá. Estos eran los cuatro hijos de Simí.

[[first-chronicles-23-11]]
^11^ Yájat era el jefe, Zizá, el segundo, Yeús y Beriá no tuvieron muchos hijos, por lo cual representaron en el censo una sola casa paterna.

[[first-chronicles-23-12]]
^12^ Hijos de Quehat: Amram, Yishar, Hebrón y Uzziel, cuatro.

[[first-chronicles-23-13]]
^13^ Hijos de Amram: Aarón y Moisés. Aarón fue separado, juntamente con sus hijos, para consagrar por siempre las cosas sacratísimas, para quemar incienso ante Yahveh, para servirle y para bendecir en su nombre por siempre.

[[first-chronicles-23-14]]
^14^ En cuanto a Moisés, varón de Dios, sus hijos fueron contados en la tribu de Leví.

[[first-chronicles-23-15]]
^15^ Hijos de Moisés: Guersom y Eliezer.

[[first-chronicles-23-16]]
^16^ Hijos de Guersom: Sebuel, el primero.

[[first-chronicles-23-17]]
^17^ Hijos de Eliezer: Rejabías, el primero. Eliezer no tuvo más hijos, pero los hijos de Rejabías fueron muy numerosos.

[[first-chronicles-23-18]]
^18^ Hijos de Yishar: Selomit, el primero,

[[first-chronicles-23-19]]
^19^ Hijos de Hebrón: Yeriyyías, el primero, Amarías, el segundo, Yajaziel, el tercero y Yecamam, el cuarto.

[[first-chronicles-23-20]]
^20^ Hijos de Uzziel: Miká, el primero y Yissías el segundo.

[[first-chronicles-23-21]]
^21^ Hijos de Merarí: Majlí y Musí. Hijos de Majlí: Eleazar y Quis.

[[first-chronicles-23-22]]
^22^ Eleazar murió sin tener hijos; sólo tuvo hijas, a las que los hijos de Quis, sus hermanos, tomaron por mujeres.

[[first-chronicles-23-23]]
^23^ Hijos de Musí: Majlí, Eder y Yeremot, tres.

[[first-chronicles-23-24]]
^24^ Estos son los hijos de Leví, según sus casas paternas, los cabezas de familia, según el censo de ellos, contados nominalmente uno por uno. Estaban encargados del servicio de la Casa de Yahveh desde la edad de veinte años en adelante.

[[first-chronicles-23-25]]
^25^ Pues David había dicho: «Yahveh, el Dios de Israel, ha dado reposo a su pueblo y mora en Jerusalén para siempre.

[[first-chronicles-23-26]]
^26^ Y en cuanto a los levitas, ya no tendrán que transportar la Morada, con todos los utensilios de su servicio».

[[first-chronicles-23-27]]
^27^ Conforme a estas últimas disposiciones de David, se hizo el cómputo de los hijos de Leví de veinte años para arriba.

[[first-chronicles-23-28]]
^28^ Estaban a las órdenes de los hijos de Aarón, para el servicio de la Casa de Yahveh, teniendo a su cargo los atrios y las cámaras, la limpieza de todas las cosas sagradas y la obra del servicio de la Casa de Dios;

[[first-chronicles-23-29]]
^29^ asimismo tenían a su cargo disponer en filas los panes, la flor de harina para la oblación, las tortas sin levadura, lo frito en la sartén, lo cocido y toda clase de medidas de capacidad y longitud.

[[first-chronicles-23-30]]
^30^ «Tenían que estar presentes todas las mañanas y todas las tardes para celebrar y alabar a Yahveh

[[first-chronicles-23-31]]
^31^ y para ofrecer todos los holocaustos a Yahveh en los sábados, novilunios y solemnidades, según su número y su rito especial, delante de Yahveh para siempre,

[[first-chronicles-23-32]]
^32^ guardando en el servicio de la Casa de Dios el ritual de la Tienda del Encuentro, el ritual del santuario y el ritual de los hijos de Aarón, sus hermanos.
[[first-chronicles-24]]
== Capítulo 24

[[first-chronicles-24-1]]
^1^ Estas son las clases de los hijos de Aarón. Hijos de Aarón: Nadab, Abihú, Eleazar e Itamar.

[[first-chronicles-24-2]]
^2^ Nadab y Abihú murieron antes que su padre, sin tener hijos, de modo que ejercieron las funciones sacerdotales Eleazar e Itamar.

[[first-chronicles-24-3]]
^3^ David, junto con Sadoq, de los hijos de Itamar, los clasificó y los inscribió en el registro según sus funciones.

[[first-chronicles-24-4]]
^4^ Se hallaron entre los hijos de Eleazar más varones que entre los hijos de Itamar, por lo que se dividió a los hijos de Eleazar en dieciséis jefes de casas paternas; y a los hijos de Itamar, en ocho jefes de casas paternas.

[[first-chronicles-24-5]]
^5^ Los repartieron por suertes a unos y otros; porque había jefes del santuario y jefes de Dios, tanto entre los hijos de Eleazar como entre los hijos de Itamar.

[[first-chronicles-24-6]]
^6^ Semaías, hijo de Natanael, escriba, uno de los levitas, los inscribió en presencia del rey y de los jefes, y en presencia del sacerdote Sadoq, de Ajimélek, hijo de Abiatar, y de los jefes de familias sacerdotales y levíticas. Se sacaba a suertes: una vez para Itamar y dos veces para Eleazar.

[[first-chronicles-24-7]]
^7^ Tocó la primera suerte a Yehoyarib; la segunda a Yedaías;

[[first-chronicles-24-8]]
^8^ la tercera a Jarim; la cuarta a Seorim;

[[first-chronicles-24-9]]
^9^ la quinta a Malkiyías; la sexta a Miyyamín;

[[first-chronicles-24-10]]
^10^ la séptima a Haqcós; la octava a Abías;

[[first-chronicles-24-11]]
^11^ la novena a Yesúa; la décima a Sekanías;

[[first-chronicles-24-12]]
^12^ la once a Elyasib; la doce a Yaquín;

[[first-chronicles-24-13]]
^13^ la trece a Juppá; la catorce a Yisbáal;

[[first-chronicles-24-14]]
^14^ la quince a Bilgá; la dieciséis a Immer;

[[first-chronicles-24-15]]
^15^ la diecisiete a Jezir; la dieciocho a Happissés;

[[first-chronicles-24-16]]
^16^ la diecinueve a Petajías; la veinte a Ezequiel;

[[first-chronicles-24-17]]
^17^ la veintiuna a Yakín; la veintidós a Gamul;

[[first-chronicles-24-18]]
^18^ la veintitrés a Delaías; la veinticuatro a Maazías.

[[first-chronicles-24-19]]
^19^ Fueron inscritos en el registro según sus servicios para entrar en la Casa de Yahveh conforme al reglamento que Yahveh, el Dios de Israel, había prescrito por medio de Aarón, padre de ellos.

[[first-chronicles-24-20]]
^20^ Respecto de los otros hijos de Leví: De los hijos de Amram: Subael. De los hijos de Subael: Yejdeías.

[[first-chronicles-24-21]]
^21^ De Rejabías: de los hijos de Rejabías, Yissiyías era el primero.

[[first-chronicles-24-22]]
^22^ De los yisharitas, Selomot; de los hijos de Selomot, Yájat.

[[first-chronicles-24-23]]
^23^ Hijos de Hebrón: Yeriyías, el primero; Amarías, el segundo; Yajaziel, el tercero; Yecamam, el cuarto.

[[first-chronicles-24-24]]
^24^ Hijos de Uzziel: Miká; de los hijos de Miká, Samir;

[[first-chronicles-24-25]]
^25^ Yissiyías era hermano de Miká; de los hijos de Yissiyías, Zacarías.

[[first-chronicles-24-26]]
^26^ Hijos de Merarí: Majlí y Musí. Hijos de Yaaziyías, su hijo;

[[first-chronicles-24-27]]
^27^ hijos de Metarí por la línea de Yaaziyías, su hijo: Soham, Zakkur e Ibrí.

[[first-chronicles-24-28]]
^28^ De Majlí: Eleazar, que no tuvo hijos.

[[first-chronicles-24-29]]
^29^ De Quis: los hijos de Quis: Yerajmeel.

[[first-chronicles-24-30]]
^30^ Hijos de Musí: Majlí, Eder y Yerimot. Estos fueron los hijos de los levitas según sus casas paternas.

[[first-chronicles-24-31]]
^31^ También éstos entraron en suerte de la misma manera que sus hermanos, los hijos de Aarón, en presencia del rey David, Sadoq, Ajimélek y los cabezas de familias sacerdotales y los levitas, siendo tradatas las primeras familias igual que las últimas.
[[first-chronicles-25]]
== Capítulo 25

[[first-chronicles-25-1]]
^1^ David y los jefes del ejército separaron para el servicio a los hijos de Asaf, Hemán y Yedutún, profetas, que cantaban con cítaras, salterios y címbalos. Este es el número de personas que se encargaban de este servicio:

[[first-chronicles-25-2]]
^2^ De los hijos de Asaf: Zakkur, José, Netanías, Asarelá, hijos de Asaf, bajo la dirección de Asaf, que profetizaba según las órdenes del rey.

[[first-chronicles-25-3]]
^3^ De Yedutún: los hijos de Yedutún: Guedalías, Serí, Isaías, Jasabías y Mattitías, seis, bajo la dirección de su padre Yedutún que profetizaba al son de la cítara para celebrar y alabar a Yahveh.

[[first-chronicles-25-4]]
^4^ De Hemán: los hijos de Hemán: Buqquiyías, Mattanías, Uzziel, Sebuel, Yerimot, Jananías, Jananí, Eliyatá, Guiddaltí, Romamti Ezer, Yosbecasa, Mallotí, Hotir, Majaziot.

[[first-chronicles-25-5]]
^5^ Todos estos eran hijos de Hemán, vidente del rey; a las palabras de Dios debían hacer sonar la trompa. Dios había dado a Hemán catorce hijos y tres hijas.

[[first-chronicles-25-6]]
^6^ Todos ellos se hallaban bajo la dirección de su padre para el canto de la Casa de Yahveh, con címbalos, salterios y cítaras al servicio de la Casa de Dios, siguiendo las indicaciones del rey, de Asaf, Yedutún y Hemán.

[[first-chronicles-25-7]]
^7^ Su número, contando a sus hermanos, los que estaban instruidos en el canto de Yahveh, todos ellos maestros, era de 288.

[[first-chronicles-25-8]]
^8^ Echaron a suertes el turno del servicio, tanto el pequeño como el grande, el maestro como el discípulo.

[[first-chronicles-25-9]]
^9^ La primera suerte recayó sobre el asafita José; la segunda sobre Guedalías con sus hermanos e hijos, doce;

[[first-chronicles-25-10]]
^10^ la tercera, sobre Zakkur, sus hijos y hermanos, doce;

[[first-chronicles-25-11]]
^11^ la cuarta sobre Yisrí, sus hijos y hermanos, doce;

[[first-chronicles-25-12]]
^12^ la quinta sobre Netanías, sus hijos y hermanos, doce;

[[first-chronicles-25-13]]
^13^ la sexta sobre Buqquiyías, sus hijos y hermanos, doce;

[[first-chronicles-25-14]]
^14^ la séptima sobre Yesarela, sus hijos y hermanos, doce;

[[first-chronicles-25-15]]
^15^ la octava sobre Isaías, sus hijos y hermanos, doce;

[[first-chronicles-25-16]]
^16^ la novena sobre Mattanías, sus hijos y hermanos, doce;

[[first-chronicles-25-17]]
^17^ la décima sobre Simí, sus hijos y hermanos, doce;

[[first-chronicles-25-18]]
^18^ la once sobre Azarel, sus hijos y hermanos, doce;

[[first-chronicles-25-19]]
^19^ la doce sobre Jasabías, sus hijos y hermanos, doce;

[[first-chronicles-25-20]]
^20^ la trece, sobre Subael, sus hijos y hermanos, doce

[[first-chronicles-25-21]]
^21^ la catorce, sobre Mattitías, sus hijos y hermanos, doce;

[[first-chronicles-25-22]]
^22^ la quince, sobre Yeremot, sus hijos y hermanos, doce;

[[first-chronicles-25-23]]
^23^ la dieciséis, sobre Jananías, sus hijos y hermanos, doce;

[[first-chronicles-25-24]]
^24^ la diecisiete, sobre Yosbecasa, sus hijos y hermanos, doce;

[[first-chronicles-25-25]]
^25^ la dieciocho, sobre Jananí, sus hijos y hermanos, doce;

[[first-chronicles-25-26]]
^26^ la diecinueve, sobre Mallotí, sus hijos y hermanos, doce;

[[first-chronicles-25-27]]
^27^ la veinte, sobre Eliyatá, sus hijos y hermanos, doce;

[[first-chronicles-25-28]]
^28^ la veintiuna, sobre Hotir, sus hijos y hermanos, doce;

[[first-chronicles-25-29]]
^29^ la veintidós, sobre Guiddaltí, sus hijos y hermanos, doce;

[[first-chronicles-25-30]]
^30^ la veintitrés, sobre Majaziot, sus hijos y hermanos, doce;

[[first-chronicles-25-31]]
^31^ la veinticuatro, sobre Romamti Ezer, sus hijos y hermanos, doce.
[[first-chronicles-26]]
== Capítulo 26

[[first-chronicles-26-1]]
^1^ Estas son las clases de porteros: De los coreítas: Meselemías, hijo de Qoré, de los hijos de Ebyasaf.

[[first-chronicles-26-2]]
^2^ Meselemías tuvo hijos: el primgénito, Zacarías; el segundo, Yediael; el tercero, Zebadías; el cuarto, Yatniel;

[[first-chronicles-26-3]]
^3^ el quinto, Elam; el sexto, Yehojanán; el séptimo, Elyehoenay.

[[first-chronicles-26-4]]
^4^ Hijos de Obededom: Semaías, el primogénito; Yehozabad, el segundo; Yoaj, el tercero; Sakar, el cuarto; Natanael, el quinto;

[[first-chronicles-26-5]]
^5^ Amiel, el sexto; Isacar el séptimo; Peulletay, el octavo; pues Dios le había bendecido.

[[first-chronicles-26-6]]
^6^ A su hijo Semaáis le nacieron hijos, que se impusieron en sus familias paternas, pues eran hombres valerosos.

[[first-chronicles-26-7]]
^7^ Hijos de Semaáis: Otní, Rafael, Obed, Elzabad y sus hermanos, hombres valerosos, Elihú y Semakías.

[[first-chronicles-26-8]]
^8^ Todos estos eran hijos de Obededom; ellos y sus hijos y sus hermanos eran hombres de gran valor para el servicio. 62 de Obededom.

[[first-chronicles-26-9]]
^9^ Meselemías tuvo hijos y hermanos, dieciocho hombres valerosos.

[[first-chronicles-26-10]]
^10^ Josá, de los hijos de Merarí, tuvo como hijos a Simrí, el primero, pues aunque no fue el primogénito, su padre le puso al frente;

[[first-chronicles-26-11]]
^11^ Jilquías, el segundo; Tebalías, el tercero; Zacarías, el cuarto. El total de los hijos y hermanos de Josá fue de trece.

[[first-chronicles-26-12]]
^12^ Estas secciones de los porteros, los jefes, igual que sus hermanos, tenían el cuidado del ministerio de la Casa de Yahveh.

[[first-chronicles-26-13]]
^13^ Echaron suertes para cada puerta, sobre pequeños y grandes, con arreglo a sus casas paternas.

[[first-chronicles-26-14]]
^14^ Para la puerta oriental cayó la suerte sobre Selemías. Después echaron suertes: tocó la parte norte a su hijo Zacarías, que era un prudente consejero.

[[first-chronicles-26-15]]
^15^ A Obededom le tocó el sur, y a sus hijos los almacenes.

[[first-chronicles-26-16]]
^16^ A Supplim y a Josá, el occidente, con la puerta del tronco abatido, en el camino de la subida, correspondiéndose un puesto de guardia con el otro.

[[first-chronicles-26-17]]
^17^ Al oriente seis por día, al norte cuatro por día, al mediodía cuatro por día y en los almacenes de dos en dos;

[[first-chronicles-26-18]]
^18^ en el Parbar, a occidente, había cuatro para la subida, dos para el Parbar.

[[first-chronicles-26-19]]
^19^ Estas son las clases de los porteros, de entre los hijos de los coreítas y de los hijos de Merarí.

[[first-chronicles-26-20]]
^20^ Los levitas, sus hermanos, custodiaban los tesoros de la Casa de Dios, y los tesoros de las cosas sagradas.

[[first-chronicles-26-21]]
^21^ Los hijos de Ladán, hijos de Guersón por la línea de Ladán, tenían a los yejielitas por jefes de familia de Ladán el guersonita.

[[first-chronicles-26-22]]
^22^ Los yejielitas, Zetam y su hermano Joel, estaban al frente de los tesoros de la Casa de Yahveh.

[[first-chronicles-26-23]]
^23^ Cuanto a los amramíes, los yisharitas, los hebronitas y los ozzielitas:

[[first-chronicles-26-24]]
^24^ Sebuel, hijo de Guersóm, hijo de Moisés, era tesorero mayor.

[[first-chronicles-26-25]]
^25^ Sus hermanos por parte de Eliezer: Rejabías, hijo suyo; Isaías, hijo suyo; Joram, hijo suyo; Zikrí, hijo suyo; Selomit, hijo suyo.

[[first-chronicles-26-26]]
^26^ Este Selomit y sus hermanos estaban al cuidado de los tesoros de las cosas sagradas que habían consagrado el rey David, los cabezas de las casas paternas, los jefes de millar y de cien y los jefes del éjercito.

[[first-chronicles-26-27]]
^27^ Lo habían consagrado del botín de guerra y de los despojos, para el sostenimiento de la Casa de Yahveh.

[[first-chronicles-26-28]]
^28^ Todo lo que habían consagrado el vidente Samuel, Saúl, hijo de Quis, Abner, hijo de Ner, y Joab, hijo de Sarvia: todo lo consagrado estaba al cuidado de Selomit y sus hermanos.

[[first-chronicles-26-29]]
^29^ De los yisharitas: Kenanías y sus hijos administraban como escribas y jueces los negocios exteriores de Israel.

[[first-chronicles-26-30]]
^30^ De los hebronitas: Jasabías y sus hermanos, hombres de valor, en número de 1.700, estaban encargados de la administración de Israel allende el Jordán, al occidente, para todos los asuntos referentes a Yahveh y al servicio del rey.

[[first-chronicles-26-31]]
^31^ El jefe de los hebronitas era Yeriyías. Acerca de los hebronitas, en el año cuarenta del reinado de David, se hicieron investigaciones sobre sus genealogías paternas, y se hallaron entre ellos hombres de valía en Yazer de Galaad.

[[first-chronicles-26-32]]
^32^ Los hermanos de Yeriyías, hombres valerosos, jefes de familias en número de 2.700, fueron constituidos por el rey David sobre los rubenitas, los gaditas y la media tribu de Manasés, en todos los asuntos de Dios y en todos los negocios del rey.
[[first-chronicles-27]]
== Capítulo 27

[[first-chronicles-27-1]]
^1^ Por lo que se refiere al número de los hijos de Israel: Los cabezas de casas paternas, los jefes de millar y de cien y sus escribas atendían al servicio de todo el que acudiera. Las secciones intervenían en todo asunto del rey relevándose todos los meses del año. Cada sección tenía 24.000 hombres.

[[first-chronicles-27-2]]
^2^ Al frente de la primera sección, que era la del primer mes, estaba Yasobam, hijo de Zabdiel; en su sección había 24.000 hombres.

[[first-chronicles-27-3]]
^3^ Pertenecía a los hijos de Peres y era jefe de todos los comandantes del ejército del primer mes.

[[first-chronicles-27-4]]
^4^ Al frente de la sección del segundo mes estaba Doday, el ajojita, su sección tenía 24.000 hombres.

[[first-chronicles-27-5]]
^5^ Jefe del tercer ejército, para el tercer mes, era Benaías, hijo del sacerdote Yehoyadá; en su sección había 24.000 hombres.

[[first-chronicles-27-6]]
^6^ Este Benaías era uno de los Treinta valientes y hallábase al frente de ellos; en su sección estaba su hijo Ammizabad.

[[first-chronicles-27-7]]
^7^ El cuarto, para el cuarto mes, era Asahel, hermano de Joab; le sucedió su hijo Zebadías. En su sección había 24.000 hombres.

[[first-chronicles-27-8]]
^8^ El quinto, para el quinto mes, era el jefe Samhut el zarejita, cuya sección constaba de 24.000 hombres.

[[first-chronicles-27-9]]
^9^ El sexto, para el sexto mes, era Irá, hijo de Iqués, el tecoíta, y en su sección había 24.000 hombres.

[[first-chronicles-27-10]]
^10^ El séptimo, para el séptimo mes, era Jeles el pelonita, de los benjaminitas; su sección constaba de 24.000 hombres.

[[first-chronicles-27-11]]
^11^ El octavo, para el octavo mes, era Sibbekay, de Jusá, el zarejita; su sección constaba de 24.000 hombres.

[[first-chronicles-27-12]]
^12^ El noveno, para el noveno mes, era Abiézer, de Anatot de los benjaminitas; en su sección había 24.000 hombres.

[[first-chronicles-27-13]]
^13^ El décimo, para el décimo mes, era Mahray, de Neftofá, zarejita; su sección constaba de 24.000 hombres.

[[first-chronicles-27-14]]
^14^ El undécimo, para el mes undécimo, era Benaías, de Piratón, de los efraimitas; su sección tenía 24.000 hombres.

[[first-chronicles-27-15]]
^15^ El duodécimo, para el mes duodécimo, era Jelday, de Netofá, de la estirpe de Otniel; su sección comprendía 24.000 hombres.

[[first-chronicles-27-16]]
^16^ Jefes de las tribus de Israel: Jefe de los rubenitas: Eliezer, hijo de Zikrí. De los simeonitas: Sefatías, hijo de Maaká.

[[first-chronicles-27-17]]
^17^ De los levitas: Jasabías, hijo de Quemuel. De Aarón: Sadoq.

[[first-chronicles-27-18]]
^18^ De Judá: Elihú, uno de los hermanos de David. De Isacar: Omrí, hijo de Miguel.

[[first-chronicles-27-19]]
^19^ De Zabulón: Yismaías, hijo de Abdías. De Neftalí: Yerimot, hijo de Azriel.

[[first-chronicles-27-20]]
^20^ De los efraimitas: Oseas, hijo de Azarías. De la media tribu de Manasés: Joel, hijo de Pedaías.

[[first-chronicles-27-21]]
^21^ De la media tribu de Manasés en Galaad: Yiddó, hijo de Zacarías. De Benjamín: Yaasiel, hijo de Abner.

[[first-chronicles-27-22]]
^22^ De Dan: Azarael, hijo de Yerojam. Estos son los jefes de las tribus de Israel.

[[first-chronicles-27-23]]
^23^ David no hizo el censo de los que tenían menos de veinte años, porque Yahveh había dicho que multiplicaría a Israel como las estrellas del cielo.

[[first-chronicles-27-24]]
^24^ Joab, hijo de Sarvia, comenzó a hacer el censo, pero no lo acabó; pues con ese motivo la Cólera descargó sobre Israel, por eso su número no alcanza el número de los Anales del rey David.

[[first-chronicles-27-25]]
^25^ Azmávet, hijo de Adiel, tenía a su cargo los depósitos reales. Sobre los depósitos del campo, de las ciudades, de las aldeas, y de las torres, estaba Jonatán, hijo de Uzzías;

[[first-chronicles-27-26]]
^26^ sobre los labradores del campo que cultivaban las tierras, Ezrí, hijo de Kelub;

[[first-chronicles-27-27]]
^27^ sobre las viñas, Simí, de Ramá; sobre las provisiones de vino de las bodegas, Zabdí, de Sefán;

[[first-chronicles-27-28]]
^28^ sobre los olivares y los sicómoros que había en la Tierra Baja, Báal Janán, de Guéder; sobre los almacenes de aceite, Joás;

[[first-chronicles-27-29]]
^29^ sobre las vacadas que pacían en Sarón, Sitray el saronita; sobre las vacadas de los valles, Safat, hijo de Adlay;

[[first-chronicles-27-30]]
^30^ sobre los camellos, Obil el ismaelita; sobre las asnas, Jejdeías, de Meronot;

[[first-chronicles-27-31]]
^31^ sobre las ovejas, Yaziz el hagarita. Todos estos eran intendentes de la hacienda del rey David.

[[first-chronicles-27-32]]
^32^ Jonatán, tío de David, hombre prudente e instruido, era consejero; él y Yejiel, hijo de Yakmoní, cuidaban de los hijos del rey.

[[first-chronicles-27-33]]
^33^ Ajitófel era consejero del rey, y Jusay el arquita era amigo del rey.

[[first-chronicles-27-34]]
^34^ Después de Ajitófel, lo fueron Yehoyadá, hijo de Benaías, y Abiatar. Joab era el jefe del ejército del rey.
[[first-chronicles-28]]
== Capítulo 28

[[first-chronicles-28-1]]
^1^ David reunió en Jerusalén a todos los jefes de Israel, los jefes de las tribus, los jefes de las secciones que estaban al servicio del rey, los jefes de millar y los jefes de cien, los administradores de la hacienda y del ganado del rey y de sus hijos, a los eunucos, los valientes y todos los hombres de valor.

[[first-chronicles-28-2]]
^2^ Y, poniéndose en pie, dijo el rey David: «Oídme, hermanos míos y pueblo mío: Había decidido en mi corazón edificar una Casa donde descansasa el arca de la alianza de Yahveh y sirviese de escabel de los pies de nuestro Dios. Ya había hecho yo preparativos para la construcción,

[[first-chronicles-28-3]]
^3^ pero Dios me dijo: “No edificarás tú la Casa a mi nombre, pues eres hombre de guerra y has derramado sangre.

[[first-chronicles-28-4]]
^4^ «Sin embargo, Yahveh, el Dios de Israel, me ha elegido de entre toda la casa de mi padre, para que fuese rey de Israel para siempre. Pues escogió a Judá para ser caudillo, y de las familias de Judá a la casa de mi padre, y de entre los hijos de mi padre se ha complacido en mí para establecer un rey sobre todo Israel.

[[first-chronicles-28-5]]
^5^ Y entre todos mis hijos - pues Yahveh me ha dado muchos hijos - eligió a mi hijo Salomón para que se siente en el trono del reino de Yahveh sobre Israel.

[[first-chronicles-28-6]]
^6^ Y El me dijo: “Tú hijo Salomón edificará mi Casa y mis atrios; porque le he escogido a él por hijo mío, y yo seré para él padre.

[[first-chronicles-28-7]]
^7^ Haré estable su reino para siempre, si se mantiene firme en el cumplimiento de mis mandamientos y de mis normas como lo hace hoy.”

[[first-chronicles-28-8]]
^8^ «Ahora, pues, a los ojos de todo Israel, que es la asamblea de Yahveh, y a oídos de nuestro Dios, guardad y meditad todos los mandamientos de Yahveh vuestro Dios, para que podáis poseer esta tierra espléndida y la dejéis como heredad a vuestros hijos después de vosotros para siempre.

[[first-chronicles-28-9]]
^9^ «Y tú, Salomón, hijo mío, reconoce al Dios de tu padre, y sírvele con corazón entero y con ánimo generoso, porque Yahveh sondea todos los corazones y penetra los pensamientos en todas sus formas. Si le buscas, se dejará encontrar; pero si le dejas, él te desechará para siempre.

[[first-chronicles-28-10]]
^10^ Mira ahora que Yahveh te ha elegido para edificar una Casa que sea su santuario. ¡Sé fuerte, y manos a la obra!»

[[first-chronicles-28-11]]
^11^ David dio a su hijo Salomón el diseño del vestíbulo y de los demás edificios, de los almacenes, de las salas altas, de las salas interiores y del lugar del Propiciatorio;

[[first-chronicles-28-12]]
^12^ y también el diseño de todo lo que tenía en su mente respecto de los atrios de la Casa de Yahveh, y de todas las camaras de alrededor, para los tesoros de la Casa de Dios y los tesoros de las cosas sagradas;

[[first-chronicles-28-13]]
^13^ asimismo respecto de las clases de los sacerdotes y de los levitas y del ejercicio del servicio de la Casa de Yahveh, como también de todos los utensilios del servicio de la Casa de Yahveh.

[[first-chronicles-28-14]]
^14^ Cuanto al oro, el peso de oro para cada uno de los utensilios de cada servicio, y también la plata, según el peso que correspondía a cada uno de los utensilios de cada clase de servicio;

[[first-chronicles-28-15]]
^15^ asimismo el peso de los candelabros de oro y sus lámparas de oro, según el peso de cada candelabro y de sus lámparas, y para los candelabros de plata según el peso de cada candelabro y sus lámparas, conforme al servicio de cada candelabro;

[[first-chronicles-28-16]]
^16^ el peso de oro para las mesas de las filas de pan, para cada mesa, y la plata para las mesas de plata;

[[first-chronicles-28-17]]
^17^ oro puro para los tenedores, los acetres y los jarros; y asimismo lo correspondiente para las copas de oro, según el peso de cada copa, y para las copas de plata según el peso de cada copa;

[[first-chronicles-28-18]]
^18^ para el altar del incienso, oro acrisolado según el peso; asimismo según el peso; asimismo el modelo de la carroza y de los querubines que extienden las alas y cubren el arca de la alianza de Yahveh.

[[first-chronicles-28-19]]
^19^ Todo esto conforme a lo que Yahveh había escrito de su mano para hacer comprender todos los detalles del diseño.

[[first-chronicles-28-20]]
^20^ Y dijo David a su hijo Salomón: «¡Sé fuerte y ten buen ánimo; y manos a la obra! No temas ni desmayes, porque Yahveh Dios, el Dios mío, está contigo; no te dejará ni te desamparará, hasta que acabes toda la obra para el servicio de la Casa de Yahveh.

[[first-chronicles-28-21]]
^21^ Ahí tienes las clases de los sacerdotes y de los levitas para todo el servicio de la Casa de Dios; estarán a tu lado para cada clase de obra, todos los hombres de buena voluntad y hábiles para cualquier clase de servicio; y los jefes del pueblo entero están a tus órdenes».
[[first-chronicles-29]]
== Capítulo 29

[[first-chronicles-29-1]]
^1^ Dijo el rey David a toda la asamblea: «Mi hijo Salomón, el único elegido por Dios, es todavía joven y débil, y la obra es grande; pues este alcázar no es para hombre, sino para Yahveh Dios.

[[first-chronicles-29-2]]
^2^ Con todas mis fuerzas he preparado, con destino a la Casa de mi Dios, el oro para los objetos de oro, la plata para los de plata, el bronce para los de bronce, el hierro para los de hierro, y la madera para los de madera; piedras de ónice y de engaste, piedras brillantes y de varios colores, toda suerte de piedras preciosas y piedras de alabastro en abundancia.

[[first-chronicles-29-3]]
^3^ Fuera de esto, en mi amor por la Casa de mi Dios, doy a la Casa de mi Dios el oro y la plata que poseo, además de todo lo que tengo preparado para la Casa del santuario:

[[first-chronicles-29-4]]
^4^ 3.000 talentos de oro, del oro de Ofir, y 7.000 talentos de plata acrisolada para recubrir las paredes de los edificios;

[[first-chronicles-29-5]]
^5^ el oro para los objetos de oro, la plata para los de plata y para todas las obras de orfebrería. ¿Quién, pues, quiere ahora hacer a manos llenas una ofrenda a Yahveh?»

[[first-chronicles-29-6]]
^6^ Entonces los cabezas de familia, los jefes de las tribus de Israel, los jefes de millar y de cien, y los encargados de las obras del rey, ofrecieron espontáneamente sus donativos,

[[first-chronicles-29-7]]
^7^ y dieron para el servicio de la Casa de Dios 5.000 talentos de oro, 10.000 dáricos, 10.000 talentos de plata, 18.000 talentos de bronce y 100.000 talentos de hierro.

[[first-chronicles-29-8]]
^8^ Los que tenían piedras preciosas las entregaron para el tesoro de la Casa de Yahveh, en manos de Yejiel el guersonita .

[[first-chronicles-29-9]]
^9^ Y el pueblo se alegró por estas ofrendas voluntarias; porque de todo corazón la habián ofrecido espontáneamente a Yahveh. También el rey David tuvo un gran gozo.

[[first-chronicles-29-10]]
^10^ Después bendijo David a Yahveh en presencia de toda la asamblea diciendo: «¡Bendito tú, oh Yahveh, Dios de nuestro padre Israel, desde siempre hasta siempre!

[[first-chronicles-29-11]]
^11^ Tuya, oh Yahveh, es la grandeza, la fuerza, la magnificencia, el esplendor y la majestad; pues tuyo es cuanto hay en el cielo y en la tierra. Tuyó, oh Yahveh, es el reino; tú te levantas por encima de todo.

[[first-chronicles-29-12]]
^12^ De ti proceden las riquezas y la gloria. Tú lo gobiernas todo; en tu mano están el poder y la fortaleza, y es tu mano la que todo lo engrandece y a todo da consistencia.

[[first-chronicles-29-13]]
^13^ Pues bien, oh Dios nuestro, te celebramos y alabamos tu Nombre magnífico.

[[first-chronicles-29-14]]
^14^ Pues, ¿quién soy yo y quién es mi pueblo para que podamos ofrecerle estos donativos? Porque todo viene de ti, y de tu mano te lo damos.

[[first-chronicles-29-15]]
^15^ Porque forasteros y huéspedes somos delante de ti, como todos nuestros padres; como sombras son nuestros días sobre la tierra y no hay esperanza.

[[first-chronicles-29-16]]
^16^ Yahveh, Dios nuestro, todo este grande acopio que hemos preparado para edificarte una Casa para tu santo Nombre, viene de tu mano y tuyo es todo.

[[first-chronicles-29-17]]
^17^ Bien sé, Dios mío, que tú pruebas los corazones y amas la rectitud; por eso te he ofrecido voluntariamente todo esto con rectitud de corazón, y ahora veo con regocijo que tu pueblo, que está aquí, te ofrece espontáneamente tus dones.

[[first-chronicles-29-18]]
^18^ Oh Yahveh, Dios de nuestros padres Abraham, Isaac, e Israel, conserva esto perpetuamente para formar los pensamientos en el corazón de tu pueblo, y dirige tú su corazón hacia ti.

[[first-chronicles-29-19]]
^19^ Da a mi hijo Salomón un corazón perfecto, para que guarde tus mandamientos, tus instrucciones y tus preceptos, para que todo lo ponga por obra y edifique el alcázar que yo te he preparado».

[[first-chronicles-29-20]]
^20^ Después dijo David a toda la asamblea: «¡Bendecid a Yahveh, vuestro Dios!» Y toda la asamblea bendijo a Yahveh, el Dios de sus padres, se inclinaron y se postraron ante Yahveh y ante el rey.

[[first-chronicles-29-21]]
^21^ Al día siguiente sacrificaron víctimas a Yahveh y le ofrecieron holocaustos: mil novillos, mil carneros y mil corderos, con sus libaciones y muchos sacrificios por todo Israel.

[[first-chronicles-29-22]]
^22^ Aquel día comieron y bebieron ante Yahveh con gran gozo y por segundo vez proclamaron rey a Salomón, hijo de David; le ungieron como caudillo ante Yahveh, y a Sadoq como sacerdote.

[[first-chronicles-29-23]]
^23^ Sentóse Salomón como rey sobre el trono de Yahveh en lugar de su padre David: él prosperó y todo Israel le obedeció

[[first-chronicles-29-24]]
^24^ Todos los jefes y valientes, y también todos los hijos del rey David, prestaron obediencia al rey Salomón.

[[first-chronicles-29-25]]
^25^ Y Yahveh engrandeció sobremanera a Salomón a los ojos de todo Israel, y le dio un reinado glorioso como nunca había tenido ningún rey de Israel antes de él.

[[first-chronicles-29-26]]
^26^ David, hijo de Jesé, había reinado sobre todo Israel.

[[first-chronicles-29-27]]
^27^ El tiempo que reinó sobre Israel fue de cuarenta años. En Hebrón reinó siete años y en Jerusalén 33.

[[first-chronicles-29-28]]
^28^ Murió en buena vejez, lleno de días, riqueza y gloria; y en su lugar reinó su hijo Salomón.

[[first-chronicles-29-29]]
^29^ Los hechos del rey David, de los primeros a los postreros, están escritos en la historia del vidente Samuel, en la historia del profeta Natán y en la historia del vidente Gad,

[[first-chronicles-29-30]]
^30^ juntamente con todo su reinado y sus hazañas, y las cosas que le sobrevinieron a él, a Israel y a todos los reinos de los demás países.
