[[ezra]]
= Esdras

[[ezra-1]]
== Capítulo 1

[[ezra-1-1]]
^1^ En el año primero de Ciro, rey de Persia, en cumplimiento de la palabra de Yahveh, por boca de Jeremías, movió Yahveh el espíritu de Ciro, rey de Persia, que mandó publicar de palabra y por escrito en todo su reino:

[[ezra-1-2]]
^2^ «Así habla Ciro, rey de Persia: Yahveh, el Dios de los cielos, me ha dado todos los reinos de la tierra. El me ha encargado que le edifique una Casa en Jerusalén, en Judá.

[[ezra-1-3]]
^3^ Quien de entre vosotros pertenezca a su pueblo, sea su Dios con él. Suba a Jerusalén, en Judá, a edificar la Casa de Yahveh, Dios de Israel, el Dios que está en Jerusalén.

[[ezra-1-4]]
^4^ A todo el resto del pueblo, donde residan, que las gentes del lugar les ayuden proporcionándoles plata, oro, hacienda y ganado, así como ofrendas voluntarias para la Casa de Dios que está en Jerusalén».

[[ezra-1-5]]
^5^ Entonces los cabezas de familia de Judá y Benjamín, los sacerdotes y los levitas, todos aquellos cuyo ánimo había movido Dios, se pusieron en marcha para subir a edificar la Casa de Yahveh en Jerusalén;

[[ezra-1-6]]
^6^ y todos sus vecinos les proporcionaron toda clase de ayuda: plata, oro, hacienda, ganado, objetos preciosos en cantidad, además de toda clase de ofrendas voluntarias.

[[ezra-1-7]]
^7^ El rey Ciro mandó tomar los utensilios de la Casa de Yahveh que Nabucodonosor se había llevado de Jerusalén y había depositado en el templo de su dios.

[[ezra-1-8]]
^8^ Ciro, rey de Persia, los puso en manos del tesorero Mitrídates, el cual los contó para entregárselos a Sesbassar, el príncipe de Judá.

[[ezra-1-9]]
^9^ Este es el inventario: fuentes de oro: 30; fuentes de plata: 1.000; reparadas: 29;

[[ezra-1-10]]
^10^ copas de oro: 30; copas de plata: 1.000; estropeadas: 410; otros utensilios: 1.000.

[[ezra-1-11]]
^11^ Total de los utensilios de oro y plata: 5.400. Todo esto se lo llevó Sesbassar cuando se permitió a los deportados volver de Babilonia a Jerusalén.
[[ezra-2]]
== Capítulo 2

[[ezra-2-1]]
^1^ Estas son las personas de la provincia que regresaron del cautiverio, aquellas que había deportado a Babilonia Nabucodonosor, rey de Babilonia, y que volvieron a Jerusalén y Judá, cada uno a su ciudad.

[[ezra-2-2]]
^2^ Vinieron con Zorobabel, Josué, Nehemías, Seraías, Reelaías, Najamaní, Mardoqueo, Bilsán, Mispar, Bigvay, Rejum, Baaná. Lista de los hombres del pueblo de Israel:

[[ezra-2-3]]
^3^ los hijos de Parós: 2.172;

[[ezra-2-4]]
^4^ los hijos de Sefatías: 372;

[[ezra-2-5]]
^5^ los hijos de Araj: 775;

[[ezra-2-6]]
^6^ los hijos de Pajat Moab, por parte de los hijos de Josué y de Joab: 2.812;

[[ezra-2-7]]
^7^ los hijos de Elam: 1.254;

[[ezra-2-8]]
^8^ los hijos de Zattú: 945;

[[ezra-2-9]]
^9^ los hijos de Zakkay: 760;

[[ezra-2-10]]
^10^ los hijos de Baní: 642;

[[ezra-2-11]]
^11^ los hijos de Bebay: 623;

[[ezra-2-12]]
^12^ los hijos de Azgad: 1.222;

[[ezra-2-13]]
^13^ los hijos de Adonicam: 666;

[[ezra-2-14]]
^14^ los hijos de Bigvay: 2.056;

[[ezra-2-15]]
^15^ los hijos de Adín: 454;

[[ezra-2-16]]
^16^ los hijos de Ater, de Ezequías: 98;

[[ezra-2-17]]
^17^ los hijos de Besay: 323;

[[ezra-2-18]]
^18^ los hijos de Yorá: 112;

[[ezra-2-19]]
^19^ los hijos de Jasum: 223;

[[ezra-2-20]]
^20^ los hijos de Guibbar: 95;

[[ezra-2-21]]
^21^ los hombres de Belén: 123;

[[ezra-2-22]]
^22^ los hombres de Netofá: 56;

[[ezra-2-23]]
^23^ los hombres de Anatot: 128;

[[ezra-2-24]]
^24^ los hombres de Azmávet: 42;

[[ezra-2-25]]
^25^ los hombres de Quiryat Yearim, Kefirá y Beerot: 743;

[[ezra-2-26]]
^26^ los hombres de Ramá y Gueba: 621;

[[ezra-2-27]]
^27^ los hombres de Mikmás: 122;

[[ezra-2-28]]
^28^ los hombres de Betel y de Ay: 223;

[[ezra-2-29]]
^29^ los hijos de Nebo: 52;

[[ezra-2-30]]
^30^ los hijos de Magbís: 156,

[[ezra-2-31]]
^31^ los hijos del otro Elam: 1.254;

[[ezra-2-32]]
^32^ los hijos de Jarim: 320;

[[ezra-2-33]]
^33^ los hombres de Lod, Jadid y Onó: 725;

[[ezra-2-34]]
^34^ los hombres de Jericó: 345;

[[ezra-2-35]]
^35^ los hombres de Senaá: 3.630.

[[ezra-2-36]]
^36^ Sacerdotes: los hijos de Yedaías, de la casa de Josué: 973;

[[ezra-2-37]]
^37^ los hijos de Immer: 1.052;

[[ezra-2-38]]
^38^ los hijos de Pasjur: 1.247;

[[ezra-2-39]]
^39^ los hijos de Jarim: 1.017.

[[ezra-2-40]]
^40^ Levitas: los hijos de Josué, y de Cadmiel, de los hijos de Hodavías: 74.

[[ezra-2-41]]
^41^ Cantores: los hijos de Asaf: 128.

[[ezra-2-42]]
^42^ Porteros: los hijos de Sallum, los hijos de Ater, los hijos de Talmón, los hijos de Aqcub, los hijos de Jatitá, los hijos de Sobay: en total 139.

[[ezra-2-43]]
^43^ Donados: los hijos de Sijá, los hijos de Jasufá, los hijos de Tabbaot,

[[ezra-2-44]]
^44^ los hijos de Querós, los hijos de Siahá, los hijos de Padón,

[[ezra-2-45]]
^45^ los hijos de Lebaná, los hijos de Jagabá, los hijos de Aqcub,

[[ezra-2-46]]
^46^ los hijos de Jagab, los hijos de Salmay, los hijos de Janán,

[[ezra-2-47]]
^47^ los hijos de Guiddel, los hijos de Gajar, los hijos de Reaías,

[[ezra-2-48]]
^48^ los hijos de Resín, los hijos de Necodá, los hijos de Gazzam,

[[ezra-2-49]]
^49^ los hijos de Uzzá, los hijos de Paséaj, los hijos de Besay,

[[ezra-2-50]]
^50^ los hijos de Asná, los hijos de los meunitas, los hijos de los nefusitas,

[[ezra-2-51]]
^51^ los hijos de Baqbuq, los hijos de Jacufá, los hijos de Jarjur,

[[ezra-2-52]]
^52^ los hijos de Baslut, los hijos de Mejidá, los hijos de Jarsá,

[[ezra-2-53]]
^53^ los hijos de Barcós, los hijos de Sisrá, los hijos de Témaj,

[[ezra-2-54]]
^54^ los hijos de Nesíaj, los hijos de Jatifá.

[[ezra-2-55]]
^55^ Hijos de los siervos de Salomón: los hijos de Sotay, los hijos de Has Soféret, los hijos de Perudá,

[[ezra-2-56]]
^56^ los hijos de Yaalá, los hijos de Darcón, los hijos de Guiddel,

[[ezra-2-57]]
^57^ los hijos de Sefatías, los hijos de Jattil, los hijos de Pokéret Hassebáyim, los hijos de Amí.

[[ezra-2-58]]
^58^ Total de los donados y de los hijos de los siervos de Salomón: 392.

[[ezra-2-59]]
^59^ Y estos son los que venían de Tel Mélaj, Tel Jarsá, Kerub, Addán e Immer, y que no pudieron probar si su familia y su familia y su estirpe eran de origen israelita:

[[ezra-2-60]]
^60^ los hijos de Delaías, los hijos de Tobías, los hijos de Necodá: 652.

[[ezra-2-61]]
^61^ Y entre los sacerdotes: los hijos de Jobayías, los hijos de Haqcós, los hijos de Barzillay - el cual se había casado con una de las hijas de Barzillay el gaaladita, cuyo nombre adoptó -.

[[ezra-2-62]]
^62^ Estos investigaron en su registro genealógico, pero no figuraban, por lo cual se les excluyó del sacerdocio como ilegítimos,

[[ezra-2-63]]
^63^ y el Gobernador les prohibió comer de las cosas sacratísimas hasta que no se presentara un sacerdote para el Urim y el Tummim.

[[ezra-2-64]]
^64^ La asamblea ascendía a 42.360 personnas,

[[ezra-2-65]]
^65^ sin contar sus siervos y siervas en número de 7.337. Tenían también 200 cantores y cantoras.

[[ezra-2-66]]
^66^ Tenían 736 caballos, 245 mulos,

[[ezra-2-67]]
^67^ 435 camellos y 6.720 asnos.

[[ezra-2-68]]
^68^ Algunos de los cabezas de familia, al llegar a la Casa de Yahveh en Jerusalén, hicieron ofrendas voluntarias para la Casa de Dios, para que fuese reedificada en su mismo emplazamiento.

[[ezra-2-69]]
^69^ Según sus posibilidades, entregaron al tesoro de la obra 61.000 dracmas de oro, 5.000 minas de plata y 100 túnicas sacerdotales.

[[ezra-2-70]]
^70^ Los sacerdotes, los levitas y parte del pueblo se establecieron en Jerusalén; los cantores, los porteros y los donados, en sus ciudades respectivas. Todo Israel estaba, pues, en sus ciudades.
[[ezra-3]]
== Capítulo 3

[[ezra-3-1]]
^1^ Llegado el séptimo mes, los israelitas estaban ya en sus ciudades y entonces todo el pueblo se congregó como un solo hombre en Jerusalén.

[[ezra-3-2]]
^2^ Josué, hijo de Yosadaq, con sus hermanos los sacerdotes, y Zorobabel, hijo de Sealtiel, con sus hermanos, se pusieron a reconstruir el altar del Dios de Israel, para ofrecer en él holocaustos, como está escrito en la Ley de Moisés, hombre de Dios.

[[ezra-3-3]]
^3^ Erigieron el altar en su emplazamiento, a pesar del temor que les infundían los pueblos de la tierra, y ofrecieron en él holocaustos a Yahveh, holocaustos de la mañana y de la tarde;

[[ezra-3-4]]
^4^ celebraron la fiesta de las Tiendas, según está escrito, con el número de holocaustos cotidianos establecidos según el rito de cada día;

[[ezra-3-5]]
^5^ después, ofrecieron el holocausto perpetuo y los de los sábados, novilunios y todas las solemnidades consagradas a Yahveh, además de lo que cada uno quería ofrecer voluntariamente a Yahveh.

[[ezra-3-6]]
^6^ Desde el día primero del séptimo mes, comenzaron a ofrecer holocaustos a Yahveh, aunque no se habían echado todavía los cimientos del santuario de Yahveh.

[[ezra-3-7]]
^7^ Se dio entonces dinero a los canteros y a los carpinteros; a los sidonios y a los tirios se les mandó víveres, bebidas y aceite, para que enviasen por mar a Joppe madera de cedro del Líbano, según la autorización de Ciro, rey de Persia.

[[ezra-3-8]]
^8^ El año segundo de su llegada a la Casa de Dios en Jerusalén, el segundo mes, Zorobabel, hijo de Sealtiel, y Josué, hijo de Yosadaq, con el resto de sus hermanos, los sacerdotes, los levitas y todos los que habían vuelto del destierro a Jerusalén, comenzaron la obra; designaron a algunos levitas, de veinte años en adelante, para dirigir las obras de la Casa de Yahveh.

[[ezra-3-9]]
^9^ Josué, sus hijos y sus hermanos, Cadmiel y sus hijos, los hijos de Hodavías, se pusieron como un solo hombre a dirigir a los que trabajaban en la obra de la Casa de Dios.

[[ezra-3-10]]
^10^ En cuanto los albañiles echaron los cimientos del santuario de Yahveh, se presentaron los sacerdotes, revestidos de lino fino, con trompetas, y los levitas, hijos de Asaf, con címbalos, para alabar a Yahveh según las prescripciones de David, rey de Israel.

[[ezra-3-11]]
^11^ Cantaron alabando y dando gracias a Yahveh: «Porque es bueno, porque es eterno su amor para Israel». Y el pueblo entero prorrumpía en grandes clamores, alabando a Yahveh, porque la Casa de Yahveh tenía ya sus cimientos.

[[ezra-3-12]]
^12^ Muchos sacerdotes, levitas y jefes de familia, ya ancianos, que habían conocido con sus propios ojos la primera Casa, sobre sus cimientos, lloraban con grandes gemidos, mientras que otros lanzaban gozosos clamores.

[[ezra-3-13]]
^13^ Y nadie podía distinguir los acentos de clamor jubiloso de los acentos de lamentación del pueblo, porque el pueblo lanzaba grandes clamores, y el estrépito se podía oír desde muy lejos.
[[ezra-4]]
== Capítulo 4

[[ezra-4-1]]
^1^ Cuando los enemigos de Judá y de Benjamín se enteraron de que los deportados estaban edificando un santuario a Yahveh, Dios de Israel,

[[ezra-4-2]]
^2^ se presentaron a Zorobabel, a Josué y a los cabezas de familia, y les dijeron: «Vamos a edificar junto con vosotros, porque, como vosotros, buscamos a vuestro Dios y le sacrificamos, desde los tiempos de Asarjaddón, rey de Asiria, que nos trajo aquí».

[[ezra-4-3]]
^3^ Zorobabel, Josué y los restantes cabezas de familia israelitas les contestaron: «No podemos edificar juntos nosotros y vosotros una Casa a nuestro Dios: a nosotros solos nos toca construir para Yahveh, Dios de Israel, como nos lo ha mandado Ciro, rey de Persia».

[[ezra-4-4]]
^4^ Entonces el pueblo de la tierra se puso a desanimar al pueblo de Judá y a meterles miedo para que no siguiesen edificando;

[[ezra-4-5]]
^5^ y sobornaron contra ellos a algunos consejeros para hacer fracasar su proyecto; así durante todo el tiempo de Ciro, rey de Persia, hasta el reinado de Darío, rey de Persia.

[[ezra-4-6]]
^6^ Bajo el reinado de Jerjes, al comienzo de su reinado, presentaron ellos por escrito una denuncia contra los habitantes de Judá y Jerusalén.

[[ezra-4-7]]
^7^ En tiempo de Artajerjes, Mitrídates, Tabeel y demás colegas suyos escribieron contra Jerusalén a Artajerjes, rey de Persia. El texto del documento estaba en escritura aramea y en lengua aramea.

[[ezra-4-8]]
^8^ Rejum, gobernador, y Simsay, secretario, escribieron al rey Artajerjes contra Jerusalén una carta.

[[ezra-4-9]]
^9^ Rejum el gobernador, Simsay el secretario y demás colegas; los jueces y los legados, funcionarios persas; las gentes de Uruk, de Babilonia y de Susa - es decir los elamitas -

[[ezra-4-10]]
^10^ y los restantes pueblos que el gran Asurbanipal deportó y estableció en las ciudades de Samaría y en el resto de Transeufratina.

[[ezra-4-11]]
^11^ Esta es la copia de la carta que le enviaron: «Al rey Artajerjes, tus servidores, las gentes de Transeufratina, etc.

[[ezra-4-12]]
^12^ Ha de saber el rey que los judíos que subieron de tu lado hacia nosotros y llegaron a Jerusalén están reconstruyendo esta ciudad rebelde y perversa; tratan de levantar las murallas, y ya han echado los cimientos.

[[ezra-4-13]]
^13^ Sepa, pues, el rey, que si esta ciudad se reconstruye y se levantan sus murallas, no se pagarán más impuestos, contribución ni peaje, y al fin esta ciudad perjudicará a los reyes.

[[ezra-4-14]]
^14^ Ahora bien, a nosotros, puesto que comemos la sal del palacio, nos resulta intolerable ver esta afrenta que se hace al rey; por eso enviamos al rey esta denuncia,

[[ezra-4-15]]
^15^ para que se investigue en las Memorias de tus padres: en estas Memorias encontrarás y te enterarás de que esta ciudad es una ciudad rebelde, molesta para los reyes y las provincias, y que en ella se han fomentado insurrecciones desde antiguo. Por este motivo fue destruida esta ciudad.

[[ezra-4-16]]
^16^ Nosotros informamos al rey que, si esta ciudad se reconstruye y se levantan sus murallas, bien pronto ya no tendrás más territorios en Transeufratina».

[[ezra-4-17]]
^17^ El rey envió esta respuesta: «A Rejum, gobernador, a Simsay, secretario, y a los restantes colegas residentes en Samaría y demás lugares en Transeufratina, paz, etc.

[[ezra-4-18]]
^18^ «El documento que nos habéis enviado ha sido traducido y leído en mi presencia.

[[ezra-4-19]]
^19^ Di orden de que se investigase, y se ha encontrado que esta ciudad se ha venido rebelando contra los reyes desde antiguo, y que por ella se han fomentado revueltas e insurrecciones.

[[ezra-4-20]]
^20^ Que hubo en Jerusalén reyes poderosos, cuyo dominio se extendía sobre toda Transeufratina: se les pagaba impuestos, contribuciones y peaje.

[[ezra-4-21]]
^21^ Ordenad, pues, que se interrumpa la empresa de esos hombres: esa ciudad no debe ser reconstruida hasta nueva orden.

[[ezra-4-22]]
^22^ Guardaos de actuar con negligencia en este asunto, no sea que el mal aumente en perjuicio de los reyes».

[[ezra-4-23]]
^23^ En cuanto la copia del documento del rey Artajerjes fue leída ante Rejum, el gobernador, Simsay, el secretario , y sus colegas, salieron a toda prisa hacia Jerusalén, donde los judíos, y les obligaron a suspender sus obras por la fuerza de las armas.

[[ezra-4-24]]
^24^ Así se suspendieron las obras de la Casa de Dios en Jerusalén: quedaron interrumpidas hasta el año segundo del reinado de Darío, rey de Persia.
[[ezra-5]]
== Capítulo 5

[[ezra-5-1]]
^1^ Los profetas Ageo y Zacarías, hijo de Iddó, empezaron a profetizar a los judíos de Judá y de Jerusalén, en nombre del Dios de Israel que velaba sobre ellos.

[[ezra-5-2]]
^2^ Con esto, Zorobabel, hijo de Sealtiel, y Josué, hijo de Yosadaq, se decidieron a reanudar la construcción de la Casa de Dios en Jerusalén: los profetas de Dios estaban con ellos, apoyándoles.

[[ezra-5-3]]
^3^ Por entonces, Tattenay, sátrapa de Transeufratina, Setar Boznay y sus colegas vinieron donde ellos y les preguntaron: «¿Quién os ha autorizado a construir esta Casa y a rematar este santuario?

[[ezra-5-4]]
^4^ ¿Cómo se llaman los hombres que construyen este edificio?»

[[ezra-5-5]]
^5^ Pero los ojos de su Dios velaban sobre los ancianos de los judíos, y no se les obligó a suspender la obra en espera de que llegase un informe a Darío y volviera un decreto oficial sobre el particular.

[[ezra-5-6]]
^6^ Copia de la carta que Tattenay, sátrapa de Transeufratina, Setar Boznay y sus colegas, las autoridades de Transeufratina, remitieron al rey Darío.

[[ezra-5-7]]
^7^ Le enviaron un escrito de este tenor: «Al rey Darío, paz completa.

[[ezra-5-8]]
^8^ Sepa el rey que nosotros hemos ido a la provincia de Judá, a la Casa del gran Dios: se está reconstruyendo con piedras sillares; se recubren de madera las paredes; la obra se ejecuta cuidadosamente y adelanta en sus manos.

[[ezra-5-9]]
^9^ Preguntando, pues, a estos ancianos, les hemos dicho: “¿Quién os ha autorizado a construir esta Casa y a rematar este santuario?”

[[ezra-5-10]]
^10^ Les hemos preguntado además sus nombres para informarte de ello; y así te damos por escrito los nombres de los hombres que están al frente de ellos.

[[ezra-5-11]]
^11^ «Ellos nos han dado esta respuesta: “Nosotros somos servidores del Dios del cielo y de la tierra; estamos reconstruyendo una Casa que estuvo en pie anteriormente durante muchos años y que un gran rey de Israel construyó y acabó.

[[ezra-5-12]]
^12^ Pero nuestros padres irritaron al Dios del cielo, y él los entregó en manos de Nabucodonosor, el caldeo, rey de Babilonia.

[[ezra-5-13]]
^13^ Sin embargo, el año primero de Ciro, rey de Babilonia, el rey Ciro dio autorización para reconstruir esta Casa de Dios;

[[ezra-5-14]]
^14^ además los utensilios de oro y plata de la Casa de Dios que Nabucodonosor había quitado al santuario de Jerusalén y había llevado al santuario de Babilonia, el rey Ciro los mandó sacar del santuario de Babilonia, y entregar a un hombre llamado Sesbassar, a quien constituyó sátrapa;

[[ezra-5-15]]
^15^ y le dijo: Toma estos utensilios; vete a llevarlos al santuario de Jerusalén y que sea reconstruida la Casa de Dios en su emplazamiento;

[[ezra-5-16]]
^16^ vino, pues, este Sesbassar y echó los cimientos de la Casa de Dios en Jerusalén, y desde entonces hasta el presente se viene reconstruyendo, pero no está acabada.”

[[ezra-5-17]]
^17^ «Ahora, pues, si le place al rey, investíguese en el departamento del tesoro del rey de Babilonia si es verdad que el rey Ciro dio autorización para reconstruir esta Casa de Dios en Jerusalén. Y que se nos remita la decisión del rey sobre este asunto».
[[ezra-6]]
== Capítulo 6

[[ezra-6-1]]
^1^ Entonces, por orden del rey Darío, se investigó en los archivos del tesoro conservado allí en Babilonia,

[[ezra-6-2]]
^2^ y se encontró en Ecbátana, la fortaleza situada en la provincia de los medos, un rollo cuyo tenor era el siguiente: «Memorándum.

[[ezra-6-3]]
^3^ «El año primero del rey Ciro, el rey Ciro ha ordenado: “Casa de Dios en Jerusalén”: «La Casa será construida como lugar donde se ofrezcan sacrificios y sus fundamentos quedarán establecidos. Su altura será de sesenta codos, su anchura de sesenta codos.

[[ezra-6-4]]
^4^ Habrá tres hileras de piedras de sillería y una de madera. Los gastos serán costeados por la casa del rey.

[[ezra-6-5]]
^5^ Además, los utensilios de oro y plata de la Casa de Dios, que Nabucodonosor sacó del santuario de Jerusalén y se llevó a Babilonia, serán restituidos, para que todo vuelva a ocupar su lugar en el santuario de Jerusalén y vuelva a ser colocado en la Casa de Dios.

[[ezra-6-6]]
^6^ «Ahora, pues, Tattenay, sátrapa de Transeufratina, Setar Boznay y vosotros, sus colegas, las autoridades de Transeufratina, retiraos de allí;

[[ezra-6-7]]
^7^ dejad trabajar en esta Casa de Dios al sátrapa de Judá y a los ancianos de los judíos, y que reconstruyan esa Casa de Dios en su emplazamiento.

[[ezra-6-8]]
^8^ Estas son mis órdenes acerca de vuestro proceder con los ancianos de los judíos para la reconstrucción de esa Casa de Dios: de los fondos reales de los impuestos de Transeufratina, se les pagarán a esos hombres los gastos exactamente y sin interrupción.

[[ezra-6-9]]
^9^ Lo que necesiten para holocaustos de Dios del cielo: novillos, carneros y corderos, así como trigo, sal, vino y aceite, se les proporcionará sin falta cada día, según las indicaciones de los sacerdotes de Jerusalén,

[[ezra-6-10]]
^10^ para que se ofrezcan al Dios del cielo ofrendas agradables y se ruegue por la vida del rey y de sus hijos.

[[ezra-6-11]]
^11^ Ordeno, además, lo siguiente: A todo aquel que no cumpla este edicto, le será arrancada de su casa una viga, se le amarrará a ella y será azotado; en cuanto a su casa, será reducida, por este delito, a un montón de escombros.

[[ezra-6-12]]
^12^ Y el Dios que ha puesto allí la morada de su Nombre, aplaste a todo aquel rey o pueblo que trate de transgredir esto, destruyendo esa Casa de Dios en Jerusalén. Yo, Darío, he promulgado este decreto. Sea ejecutado exactamente».

[[ezra-6-13]]
^13^ Entonces Tattenay, sátrapa de Transeufratina, Setar Boznay y sus colegas ejecutaron exactamente las instrucciones mandadas par el rey Darío.

[[ezra-6-14]]
^14^ Así, los ancianos de los judíos continuaron reconstruyendo con éxito, según la profecía de Ageo el profeta, y de Zacarías, hijo de Iddó. Llevaron a término la construcción según la orden del Dios de Israel y la orden de Ciro y de Darío.

[[ezra-6-15]]
^15^ Esta Casa fue terminada el día veintitrés del mes de Adar, el año sexto del reinado del rey Darío.

[[ezra-6-16]]
^16^ Los israelitas - los sacerdotes, los levitas y el resto de los deportados - celebraron con júbilo la dedicación de esta Casa de Dios;

[[ezra-6-17]]
^17^ ofrecieron para la dedicación de esta Casa de Dios cien toros, doscientos carneros, cuatrocientos corderos y, como sacrificio por el pecado de todo Israel, doce machos cabríos, conforme al número de las tribus de Israel.

[[ezra-6-18]]
^18^ Luego establecieron a los sacerdotes según sus categorías, y a los levitas según sus clases, para el servicio de la Casa de Dios en Jerusalén, según está escrito en el libro de Moisés.

[[ezra-6-19]]
^19^ Los deportados celebraron la Pascua el día catorce del primer mes;

[[ezra-6-20]]
^20^ ya que los levitas se habían purificado como un solo hombre, todos estaban puros; inmolaron, pues, la pascua para todos los deportados, para sus hermanos los sacerdotes y para sí mismos.

[[ezra-6-21]]
^21^ Comieron la pascua los israelitas que habían vuelto del destierro y todos aquellos que, habiendo roto con la impureza de las gentes del país se habían unido a ellos para buscar a Yahveh, Dios de Israel.

[[ezra-6-22]]
^22^ Celebraron con júbilo, durante siete días, la fiesta de los Azimos, porque Yahveh les había llenado de gozo, pues volvió hacia ellos el corazón del rey de Asiria, para que reafirmase sus manos en las obras de la Casa de su Dios, el Dios de Israel.
[[ezra-7]]
== Capítulo 7

[[ezra-7-1]]
^1^ Después de estos acontecimientos, bajo el reinado de Artajerjes, rey de Persia, Esdras, hijo de Seraías, hijo de Azarías, hijo de Jilquías,

[[ezra-7-2]]
^2^ hijo de Sallum, hijo de Sadoq, hijo de Ajitub,

[[ezra-7-3]]
^3^ hijo de Amarías, hijo de Azarías, hijo de Merayot,

[[ezra-7-4]]
^4^ hijo de Zerajías, hijo de Uzzí, hijo de Buqquí,

[[ezra-7-5]]
^5^ hijo de Abisúa, hijo de Pinjás, hijo de Eleazar, hijo del sumo sacerdote Aarón,

[[ezra-7-6]]
^6^ este Esdras subió de Babilonia. Era un escriba versado en la Ley de Moisés que había dado Yahveh, Dios de Israel. Como la mano de Yahveh su Dios estaba con él, el rey le concedió todo lo que pedía.

[[ezra-7-7]]
^7^ Subieron también a Jerusalén, el año séptimo del rey Artajerjes, parte de los israelitas, de los sacerdotes, levitas, cantores, porteros y donados.

[[ezra-7-8]]
^8^ El llegó a Jerusalén el mes quinto: era el año séptimo del rey.

[[ezra-7-9]]
^9^ Había dispuesto para el día uno del primer mes su salida de Babilonia, y el día uno del quinto mes llegaba a Jerusalén. ¡La mano bondadosa de su Dios estaba con él!

[[ezra-7-10]]
^10^ Porque Esdras había aplicado su corazón a escrutar la Ley de Yahveh, a ponerla en práctica y a enseñar en Israel los preceptos y las normas.

[[ezra-7-11]]
^11^ Esta es la copia del documento que el rey Artajerjes entregó a Esdras, el sacerdote-escriba dedicado a escribir las palabras de los mandamientos de Yahveh y sus decretos acerca de Israel.

[[ezra-7-12]]
^12^ «Artajerjes, rey de reyes, al sacerdote Esdras, secretario de la Ley del Dios del cielo, paz perfecta, etc.

[[ezra-7-13]]
^13^ «Estas son mis órdenes: Todo aquel que en mi reino pertenezca al pueblo de Israel, a sus sacerdotes o a sus levitas, y quiera volver a Jerusalén, puede partir contigo,

[[ezra-7-14]]
^14^ ya que tú eres enviado por el rey y sus siete consejeros para inspeccionar a Judá y Jerusalén en lo referente a la Ley de tu Dios que está en tus manos,

[[ezra-7-15]]
^15^ y para llevar la plata y el oro que el rey y sus consejeros han ofrecido voluntariamente al Dios de Israel, cuya morada está en Jerusalén,

[[ezra-7-16]]
^16^ así como toda la plata y el oro que hayas reunido de toda la provincia de Babilonia, con las ofrendas voluntarias que el pueblo y los sacerdotes hayan hecho para la Casa de su Dios en Jerusalén.

[[ezra-7-17]]
^17^ Con este dinero procura comprar novillos, carneros, corderos, con las oblaciones y libaciones correspondientes, para ofrecerlo luego sobre el altar de la Casa de vuestro Dios en Jerusalén;

[[ezra-7-18]]
^18^ y la plata y el oro que sobre, lo emplearéis como mejor os parezca a ti y a tus hermanos, conforme a la voluntad de vuestro Dios.

[[ezra-7-19]]
^19^ Los utensilios que se te entregan para el servicio de la Casa de tu Dios, deposítalos delante de tu Dios en Jerusalén.

[[ezra-7-20]]
^20^ Lo que aún se necesite para la Casa de tu Dios y que tú tengas que procurarte, se te dará de los tesoros reales.

[[ezra-7-21]]
^21^ Yo mismo, el rey Artajerjes, doy esta orden a todos los tesoreros de Transeufratina: “Todo lo que os pida el sacerdote Esdras, Secretario de la Ley del Dios del cielo, se lo daréis puntualmente,

[[ezra-7-22]]
^22^ hasta la suma de cien talentos de plata, cien cargas de trigo, cien medidas de vino y cien medidas de aceite; la sal se le dará sin tasa.

[[ezra-7-23]]
^23^ Todo lo que ordena el Dios del cielo, debe ser cumplido con celo para la Casa del Dios del cielo, a fin de que la Cólera no caiga sobre el reino del rey y de sus hijos.

[[ezra-7-24]]
^24^ Os hacemos saber también que no se puede percibir impuesto, contribución o peaje, de ninguno de los sacerdotes, levitas, cantores, porteros, donados, de ninguno de los servidores de esta Casa de Dios.”

[[ezra-7-25]]
^25^ «Y tú, Esdras, conforme a la sabiduría de tu Dios, que posees, establece escribas y jueces que administren la justicia a todo el pueblo de Transeufratina, a todos los que conocen la Ley de tu Dios. A quienes la ignoran, habréis de enseñársela.

[[ezra-7-26]]
^26^ Y a todo aquel que no cumpla la Ley de tu Dios y la ley del rey, aplíquesele una rigurosa justicia: muerte, destierro, multa en dinero o cárcel».

[[ezra-7-27]]
^27^ ¡Bendito sea Yahveh, Dios de nuestros padres, que movió de esta manera el corazón del rey para glorificar la Casa de Yahveh en Jerusalén,

[[ezra-7-28]]
^28^ y a mí me granjeó gracia delante del rey, de sus consejeros y de los altos jefes del rey! Yo cobré ánimo porque la mano de Yahveh mi Dios estaba conmigo, y reuní a los jefes de Israel para que salieran conmigo.
[[ezra-8]]
== Capítulo 8

[[ezra-8-1]]
^1^ Estos son, con su genealogía, los cabezas de familia que subieron conmigo de Babilonia en el reinado del rey Artajerjes:

[[ezra-8-2]]
^2^ De los hijos de Pinjás: Guersom; de los hijos de Itamar: Daniel; de los hijos de David: Jattús,

[[ezra-8-3]]
^3^ hijo de Sekanías; de los hijos de Pardós: Zacarías, con el que fueron registrados 150 varones;

[[ezra-8-4]]
^4^ de los hijos de Pajat Moab: Elyehoenay, hijo de Zerajías, y con él doscientos varones;

[[ezra-8-5]]
^5^ de los hijos de Zattú: Sekanías, hijo de Yajaziel, y con él trescientos varones;

[[ezra-8-6]]
^6^ de los hijos de Adín: Ebed, hijo de Jonatán, y con él cincuenta varones;

[[ezra-8-7]]
^7^ de los hijos de Elam: Isaías, hijo de Atalías, y con él setenta varones;

[[ezra-8-8]]
^8^ de los hijos de Sefatías: Zebadías, hijo de Miguel, y con él ochenta varones;

[[ezra-8-9]]
^9^ de los hijos de Joab: Abdías, hijo de Yejiel y con él 218 varones;

[[ezra-8-10]]
^10^ de los hijos de Baní: Selomit, hijo de Yosifías, y con él 160 varones;

[[ezra-8-11]]
^11^ de los hijos de Bebay: Zacarías, hijo de Bebay, y con él veintiocho varones;

[[ezra-8-12]]
^12^ de los hijos de Azgad: Yojanán, hijo de Haqcadán, y con él 110 varones;

[[ezra-8-13]]
^13^ de los hijos de Adonicam: los últimos, cuyos nombres son: Elifélet, Yeiel y Semaías, y con ellos sesenta varones;

[[ezra-8-14]]
^14^ y de los hijos de Bigvay: Utay, hijo de Zabud, y con él setenta varones.

[[ezra-8-15]]
^15^ Yo los reuní junto al río que corre hacia Ahavá. Allí acampamos tres días. Observé que había laicos y sacerdotes, pero no encontré ningún levita.

[[ezra-8-16]]
^16^ Entonces llamé a Eliezer, Ariel, Semaías, Elnatán, Yarib, Elnatán, Natán, Zacarías, y Mesullam, hombres discretos,

[[ezra-8-17]]
^17^ y les mandé donde Iddó, jefe de la localidad de Kasifías; puse en su boca las palabras que habían de decir a Iddó y a sus hermanos, establecidos en la localidad de Kasifías, para que nos proporcionaran ministros para la Casa de nuestro Dios.

[[ezra-8-18]]
^18^ Y gracias a la mano bondadosa de nuestro Dios que estaba con nosotros, nos trajeron a un hombre experto, de los hijos de Majlí, hijo de Leví, hijo de Israel: a Serebías, con sus hijos y hermanos: dieciocho hombres;

[[ezra-8-19]]
^19^ además a Jasabías, y con él a su hermano Isaías, de los hijos de Merarí, y sus hijos: veinte hombres.

[[ezra-8-20]]
^20^ Y de los donados que David y los jefes habían destinado al servicio de los levitas: 220 donados. Todos ellos fueron designados nominalmente.

[[ezra-8-21]]
^21^ Allí, a orillas del río Ahavá, proclamé un ayuno para humillarnos delante de nuestro Dios y pedirle un viaje feliz para nosotros, nuestros hijos y nestros bienes.

[[ezra-8-22]]
^22^ Pues me daba vergüenza solicitar del rey tropa y gente de a caballo para protegernos del enemigo en el camino; por el contrario, habíamos declarado al rey: «La mano de nuestro Dios está, para bien, con todos los que le buscan; y su poder y su cólera sobre todos los que le abandonan».

[[ezra-8-23]]
^23^ Ayunamos, pues, buscando a nuestro Dios por esta intención, y él nos atendió.

[[ezra-8-24]]
^24^ Elegí a doce jefes de los sacerdotes, y además a Serebías y Jasabías, y con ellos a diez de sus hermanos;

[[ezra-8-25]]
^25^ les pesé la plata, el oro y los utensilios, ofrendas que el rey, sus consejeros, sus jefes y todos los israelitas que se encontraban allí habían reservado para la Casa de nuestro Dios.

[[ezra-8-26]]
^26^ Pesé y les entregué 650 talentos de plata, cien utensilios de plata de dos talentos, cien talentos de oro,

[[ezra-8-27]]
^27^ veinte copas de oro de mil dáricos y dos objetos de hermoso bronce dorado, preciosos como el oro.

[[ezra-8-28]]
^28^ Y les dije: «Vosotros estáis consagrados a Yahveh; estos utensilios son sagrados; esta plata y este oro son una ofrenda voluntaria a Yahveh, Dios de nuestros padres.

[[ezra-8-29]]
^29^ Vigilad y guardadlos hasta que los peséis ante los jefes de los sacerdotes y de los levitas y los cabezas de familia de Israel, en Jerusalén, en las cámaras de la Casa de Yahveh».

[[ezra-8-30]]
^30^ Los sacerdotes y levitas tomaron entonces la plata, todo lo que había sido pesado, el oro y los utensilios, para llevarlos a Jerusalén, a la Casa de nuestro Dios.

[[ezra-8-31]]
^31^ El día doce del primer mes partimos del río Ahavá para ir a Jerusalén: la mano de nuestro Dios estaba con nosotros y nos salvó en el camino de la mano de enemigos y salteadores.

[[ezra-8-32]]
^32^ Llegamos a Jerusalén y descansamos allí tres días.

[[ezra-8-33]]
^33^ El cuarto día, la plata, el oro y los utensilios fueron pesados en la Casa de nuestro Dios y entregados al sacerdote Meremot, hijo de Urías, con quien estaba Eleazar, hijo de Pinjás; les acompañaban los levitas Yozabad, hijo de Josué, y Noadías, hijo de Binnuy.

[[ezra-8-34]]
^34^ Todo se contó y se pesó, y se registró su peso total. En aquel tiempo,

[[ezra-8-35]]
^35^ los deportados que volvían del cautiverio ofrecieron holocaustos al Dios de Israel: doce novillos por todo Israel, 96 carneros, 77 corderos y doce machos cabríos por el pecado: todo en holocausto a Yahveh.

[[ezra-8-36]]
^36^ Y se entregaron los decretos del rey a los sátrapas del rey y a los gobernadores de Transeufratina, los cuales favorecieron al pueblo y la Casa de Dios.
[[ezra-9]]
== Capítulo 9

[[ezra-9-1]]
^1^ Concluido esto, se me presentaron los jefes diciendo: «El pueblo de Israel, los sacerdotes y los levitas no se han separado de las gentes del país, hundidas en sus abominaciones - cananeos, hititas, perizitas, jebuseos, ammonitas, moabitas, egipcios y amorreos -,

[[ezra-9-2]]
^2^ sino que han tomado para ellos y para sus hijos mujeres de entre las hijas de ellos: la raza santa se ha mezclado con las gentes del país; los jefes y los consejeros han sido los primeros en esta rebeldía».

[[ezra-9-3]]
^3^ Al oír esto rasgué mis vestiduras y mi manto, me arranqué los pelos de la cabeza y de la barba, y me senté desolado.

[[ezra-9-4]]
^4^ Todos los temerosos de las palabras del Dios de Israel se reunieron en torno a mí, a causa de esta rebeldía de los deportados. Yo permanecí sentado, desolado, hasta la oblación de la tarde.

[[ezra-9-5]]
^5^ A la hora de la oblación de la tarde salí de mi postración y, con las vestiduras y el manto rasgados, caí de rodillas, extendí las manos hacia Yahveh mi Dios,

[[ezra-9-6]]
^6^ y dije: «Dios mío, harta vergüenza y confusión tengo para levantar mi rostro hacia ti, Dios mío. Porque nuestros crímenes se han multiplicado hasta sobrepasar nuestra cabeza, y nuestro delito ha crecido hasta el cielo.

[[ezra-9-7]]
^7^ Desde los días de nuestros padres hasta el día de hoy nos hemos hecho muy culpables: por nuestros crímenes fuimos entregados, nosotros, nuestros reyes y nuestros sacerdotes, en manos de los reyes de los países, a la espada, al cautiverio, al saqueo y al oprobio, como todavía hoy sucede.

[[ezra-9-8]]
^8^ Mas ahora, en un instante, Yahveh nuestro Dios nos ha concedido la gracia de dejarnos un Resto y de darnos una liberación en su lugar santo: nuestro Dios ha iluminado así nuestros ojos y nos ha reanimado en medio de nuestra esclavitud.

[[ezra-9-9]]
^9^ Porque esclavos fuimos nosotros, pero en nuestra esclavitud nuestro Dios no nos ha abandonado; nos ha granjeado el favor de los reyes de Persia, dándonos ánimos para levantar de nuevo la Casa de nuestro Dios y restaurar sus ruinas y procurándonos un valladar seguro en Judá y Jerusalén.

[[ezra-9-10]]
^10^ Pero ahora, Dios nuestro, ¿qué vamos a decir, si, después de todo esto, hemos abandonado tus mandamientos,

[[ezra-9-11]]
^11^ que por medio de tus siervos los profetas tú habías prescrito en estos términos: “La tierra en cuya posesión vais a entrar es una tierra manchada por la inmundicia de las gentes de la tierra, por las abominaciones con que la han llenado de un extremo a otro con su impureza?

[[ezra-9-12]]
^12^ Así pues, no deis vuestras hijas a sus hijos ni toméis sus hijas para vuestros hijos; no busquéis nunca su paz ni su bienestar, a fin de que podáis haceros fuertes, comáis los mejores frutos de la tierra y la dejéis en herencia a vuestros hijos para siempre.”

[[ezra-9-13]]
^13^ «Mas después de todo lo que nos ha sobrevenido por nuestras malas acciones y nuestras culpas - y eso que tú, Dios nuestro, has disminuido nuestros crímenes y nos has concedido esta liberación -

[[ezra-9-14]]
^14^ ¿hemos de volver a violar tus mandamientos, emparentándonos con estas gentes abominables? ¿No te irritarías tú contra nosotros hasta exterminarnos sin que quedara Resto ni salvación?

[[ezra-9-15]]
^15^ Yahveh, Dios de Israel, justo eres, pues un Resto nos hemos salvado, como en el caso presente: aquí estamos ante ti, con nuestro delito. Pues por su causa nadie resiste en tu presencia».
[[ezra-10]]
== Capítulo 10

[[ezra-10-1]]
^1^ Mientras Esdras, llorando y prosternado ante la Casa de Dios, oraba y hacía esta confesión, una inmensa asamblea de Israel, hombres, mujeres y niños, se había reunido en torno a él: y este pueblo lloraba copiosamente.

[[ezra-10-2]]
^2^ Entonces, Sekanías, hijo de Yejiel, de los hijos de Elam, dijo a Esdras: «Hemos sido rebeldes a nuestro Dios, casándonos con mujeres extranjeras, tomadas de entre las gentes del país. Ahora bien, a pesar de ello, todavía, hay una esperanza para Israel.

[[ezra-10-3]]
^3^ Hagamos alianza con nuestro Dios de despedir a todas las mujeres extranjeras y a los hijos nacidos de ellas, conforme al consejo de mi señor y de los temerosos de los mandamientos de nuestro Dios. Hágase según la Ley.

[[ezra-10-4]]
^4^ Levántate, que este asunto te incumbe a ti; nosotros estaremos a tu lado. ¡Animo y manos a la obra!»

[[ezra-10-5]]
^5^ Entonces Esdras se levantó e hizo jurar a los jefes de los sacerdotes y de los levitas y a todo Israel que harían conforme a lo dicho; y lo juraron.

[[ezra-10-6]]
^6^ Luego Esdras se retiró de delante de la Casa de Dios y se fue al aposento de Yehojanán, hijo de Elyasib, donde pasó la noche sin comer pan ni beber agua, haciendo duelo a causa de la rebeldía de los deportados.

[[ezra-10-7]]
^7^ Se publicó un bando en Judá y Jerusalén a todos los deportados para que se reunirean en Jerusalén.

[[ezra-10-8]]
^8^ Todo aquel que no viniera en el plazo de tres días, según el consejo de los jefes y de los ancianos, vería consagrada al anatema toda su hacienda y sería él mismo excluido de la asamblea de los deportados.

[[ezra-10-9]]
^9^ Todos los hombres de Judá y de Benjamín se reunieron, pues, en Jerusalén en el plazo de tres días: era el día veinte del mes noveno; todo el pueblo se situó en la plaza de la Casa de Dios, temblando, debido al caso, y también porque llovía a cántaros.

[[ezra-10-10]]
^10^ Entonces el sacerdote Esdras se levantó y les dijo: «Habéis sido rebeldes al casaros con mujeres extranjeras, aumentando así el delito de Israel.

[[ezra-10-11]]
^11^ Ahora, pues, dad gracias a Yahveh, Dios de vuestros padres, y cumplid su voluntad separándoos de las gentes del país y de las mujeres extranjeras».

[[ezra-10-12]]
^12^ Toda la asamblea respondió en alta voz: Sí; haremos como tú dices;

[[ezra-10-13]]
^13^ sólo que el pueblo es numeroso, y estamos en la estación de las lluvias: no podemos soportar la intemperie; además, no se trata de una cosa de un día o dos, porque somos muchos los que hemos incurrido en este pecado.

[[ezra-10-14]]
^14^ Nuestros jefes podrían representar a toda la asamblea: todos los que en nuestras ciudades se hayan casado con mujeres extranjeras, vendrían a plazos fijados, acompañados de los ancianos y los jueces de cada ciudad, hasta que hayamos apartado de nosotros el furor de la cólera de nuestro Dios por causa de este asunto».

[[ezra-10-15]]
^15^ Sólo Jonatán, hijo de Asahel, y Yajzeías, hijo de Tiqvá, se opusieron a esto, apoyados por Mesullam y el levita Sabtay.

[[ezra-10-16]]
^16^ Los deportados actuaron según lo convenido. El sacerdote Esdras escogió como colaboradores a los cabezas de familia, según sus casas, todos ellos designados nominalmente. Se comenzaron las sesiones para examinar el caso el día uno del décimo mes.

[[ezra-10-17]]
^17^ Y el día uno del primer mes se había terminado ya con todos los hombres que estaban casados con mujeres extranjeras.

[[ezra-10-18]]
^18^ Entre los sacerdotes, se halló que se habían casado con mujeres extranjeras los siguientes: entre los hijos de Josué, hijo de Yosadaq, y entre sus hermanos: Maaseías, Eliezer, Yarib y Guedalías;

[[ezra-10-19]]
^19^ éstos se comprometieron bajo juramento a despedir a sus mujeres, y ofrecieron por su delito un carnero en sacrificio de reparación.

[[ezra-10-20]]
^20^ Entre los hijos de Immer: Jananí y Zebadías.

[[ezra-10-21]]
^21^ Entre los hijos de Jarim: «Maaseías, Elías, Semaías, Yejiel y Uzziyías.

[[ezra-10-22]]
^22^ Entre los hijos de Pasjur: Elyoenay, Maaseías, Ismael, Natanael, Yozabad y Elasá.

[[ezra-10-23]]
^23^ Entre los levitas: Yozabad, Simí, Quelaías (es decir, Quelitá), Petajías, Judá y Eliezer.

[[ezra-10-24]]
^24^ Entre los cantores: Elyasib y Zakkur. Entre los porteros: Sallum, Telem y Urí.

[[ezra-10-25]]
^25^ Entre los israelitas: de los hijos de Parós: Ramías, Yizziyías, Malkiyías, Miyyamín, Eleazar, Malkiyías y Benaías;

[[ezra-10-26]]
^26^ de los hijos de Elam: Mattanías, Zacarías, Yejiel, Abdí, Yeremot y Elías;

[[ezra-10-27]]
^27^ de los hijos de Zattú: Elyoenáy. Elyasib Mattanías, Yeremot, Zabad y Azizá:

[[ezra-10-28]]
^28^ de los hijos de Bebay: Yehojanán, Jananías, Zabbay, Atlay;

[[ezra-10-29]]
^29^ de los hijos de Bigvay: Mesullam, Malluk, Yedaías, Yasub, Yisal, Yeremot;

[[ezra-10-30]]
^30^ de los hijos de Pajat Moab: Adná, Kelal, Benaías, Maaseías, Mattanías, Besalel, Binnuy y Manasés;

[[ezra-10-31]]
^31^ de los hijos de Jarim: Eliezer, Yissiyías, Malkiyías, Semaías, Simeón,

[[ezra-10-32]]
^32^ Benjamín, Malluk, Semarías;

[[ezra-10-33]]
^33^ de los hijos de Jasum: Mattenay, Mattattá, Zabad, Elifélet, Yeremay, Manasés, Simí;

[[ezra-10-34]]
^34^ de los hijos de Baní: Maaday, Amram, Joel,

[[ezra-10-35]]
^35^ Benaías, Bedías, Kelaías,

[[ezra-10-36]]
^36^ Vanías, Meremot, Elyasib,

[[ezra-10-37]]
^37^ Mattanías, Mattenay y Yaassay;

[[ezra-10-38]]
^38^ de los hijos de Binnuy: Simí,

[[ezra-10-39]]
^39^ Selemías, Natán y Adaías;

[[ezra-10-40]]
^40^ de los hijos de Zakkay: Sasay, Saray,

[[ezra-10-41]]
^41^ Azareel, Selemías, Semarías,

[[ezra-10-42]]
^42^ Sallum, Amarías, José;

[[ezra-10-43]]
^43^ de los hijos de Nebo: Yeiel, Mattitías, Zabad, Zebiná, Yadday, Joel, Benaías.

[[ezra-10-44]]
^44^ Todos éstos se habían casado con mujeres extranjeras, pero despidieron tanto a las mujeres como a sus hijos.
