[[nehemiah]]
= Nehemías

[[nehemiah-1]]
== Capítulo 1

[[nehemiah-1-1]]
^1^ Palabras de Nehemías, hijo de Jakalías. En el mes de Kisléu, el año veinte del rey Artajerjes, estando yo en la ciudadela de Susa,

[[nehemiah-1-2]]
^2^ Jananí, uno de mis hermanos, llegó con algunos hombres venidos de Judá. Yo les pregunté por los judíos - el Resto que se había salvado del cautiverio - y por Jerusalén.

[[nehemiah-1-3]]
^3^ Me respondieron: «Los restos del cautiverio que han quedado allí en la provincia se encuentran en gran estrechez y confusión. La muralla de Jerusalén está llena de brechas, y sus puertas incendiadas».

[[nehemiah-1-4]]
^4^ Al oír estas palabras me senté y me puse a llorar; permanecí en duelo algunos días ayunando y orando ante el Dios del cielo.

[[nehemiah-1-5]]
^5^ Y dije: «Ah, Yahveh, Dios del cielo, tú, el Dios grande y temible, que guardas la alianza y el amor a los que te aman y observan tus mandamientos;

[[nehemiah-1-6]]
^6^ estén atentos tus oídos y abiertos tus ojos para escuchar la oración de tu siervo, que yo hago ahora en tu presencia día y noche, por los hijos de Israel, tus siervos, confesando los pecados que los hijos de Israel hemos cometido contra ti; ¡yo mismo y la casa de mi padre hemos pecado!

[[nehemiah-1-7]]
^7^ Hemos obrado muy mal contigo, no observando los mandamientos, los preceptos y las normas que tú habías prescrito a Moisés tu siervo.

[[nehemiah-1-8]]
^8^ Pero acuérdate de la palabra que confiaste a Moisés tu siervo: “Si sois infieles, yo os dispersaré entre los pueblos;

[[nehemiah-1-9]]
^9^ pero si, volviéndoos a mí guardáis mis mandamientos y los ponéis en práctica, aunque vuestros desterrados estuvieron en los confines de los cielos, yo los reuniré de allí y los conduciré de nuevo al Lugar que he elegido para morada de mi Nombre.”

[[nehemiah-1-10]]
^10^ Aquí tienes a tus siervos y a tu pueblo que tú has rescatado con tu gran poder y tu fuerte mano.

[[nehemiah-1-11]]
^11^ ¡Ea, Señor, estén atentos tus oídos a la oración de tu siervo, a la oración de tus servidores, que desean venerar tu Nombre! Concede ahora, te suplico, gracia a tu siervo y haz que encuentre favor ante ese hombre». Era yo entonces copero del rey.
[[nehemiah-2]]
== Capítulo 2

[[nehemiah-2-1]]
^1^ En el mes de Nisán, el año veinte del rey Artajerjes, siendo yo encargado del vino, tomé vino y se lo ofrecí al rey. Anteriormente nunca había estado yo triste.

[[nehemiah-2-2]]
^2^ Me dijo, pues, el rey: «¿Por qué ese semblante tan triste? Tú, enfermo no estás. ¿Acaso tienes alguna preocupación en el corazón?» Yo quedé muy turbado,

[[nehemiah-2-3]]
^3^ y dije al rey: «¡Viva por siempre el rey! ¿Cómo no ha de estar triste mi semblante, cuando la ciudad donde están las tumbas de mis padres está en ruinas, y sus puertas devoradas por el fuego?»

[[nehemiah-2-4]]
^4^ Replicóme el rey: «¿Qué deseas, pues?» Invoqué al Dios del cielo,

[[nehemiah-2-5]]
^5^ y respondí al rey: «Si le place al rey y estás satisfecho de tu siervo, envíame a Judá, a la ciudad de las tumbas de mis padres, para que yo la reconstruya».

[[nehemiah-2-6]]
^6^ El rey me preguntó, estando la reina sentada a su lado: «¿Cuánto durará tu viaje? ¿Cuándo volverás?» Yo le fijé un plazo que pareció aceptable al rey, y él me envió.

[[nehemiah-2-7]]
^7^ Añadí al rey: «Si le place al rey, que se me den cartas para los gobernadores de Transeufratina, para que me faciliten el camino hasta Judá;

[[nehemiah-2-8]]
^8^ y asimismo una carta para Asaf, el encargado de los parques reales, para que me proporcione madera de construcción para las puertas de la ciudadela del Templo, la muralla de la ciudad y la casa en que yo me he de instalar». El rey me lo concedió, pues la mano bondadosa de mi Dios estaba conmigo.

[[nehemiah-2-9]]
^9^ Me dirigí, pues, a los gobernadores de Transeufratina y les entregué las cartas del rey. El rey me había hecho escoltar por oficiales del ejército y gente de a caballo.

[[nehemiah-2-10]]
^10^ Al enterarse de ello Samballat el joronita y Tobías el servidor ammonita, les sentó muy mal que alguien viniera a procurar el bienestar de los israelitas.

[[nehemiah-2-11]]
^11^ Llegué a Jerusalén y me quedé allí tres días.

[[nehemiah-2-12]]
^12^ Luego me levanté de noche con unos pocos hombres, sin comunicar a nadie lo que mi Dios me había inspirado que hiciera por Jerusalén, y sin llevar conmigo más que la cabalgadura en que iba montado.

[[nehemiah-2-13]]
^13^ Saliendo, pues, de noche por la puerta del Valle, me dirigí hacia la Fuente del Dragón y hacia la puerta del Muladar: inspeccioné la muralla de Jerusalén por donde tenía brechas, y las puertas que habían sido devoradas por el fuego.

[[nehemiah-2-14]]
^14^ Continué luego hacia la puerta de la Fuente y la alberca del Rey, pero no había paso para mi cabalgadura.

[[nehemiah-2-15]]
^15^ Volví a subir, pues, de noche, por el Torrente, inspeccionando la muralla, y volví a entrar por la puerta del Valle. Así regresé a casa.

[[nehemiah-2-16]]
^16^ Los consejeros no supieron dónde había ido ni lo que había hecho. Hasta entonces no había dicho nada a los judíos: ni a los sacerdotes ni a los notables ni a los consejeros ni a los funcionarios;

[[nehemiah-2-17]]
^17^ entonces les dije: «Vosotros mismos veis la triste situación en que nos encontramos, pues Jerusalén está en ruinas, y sus puertas devoradas por el fuego. Vamos a reconstruir la muralla de Jerusalén, y no seremos más objeto de escarnio».

[[nehemiah-2-18]]
^18^ Y les referí cómo la mano bondadosa de mi Dios había estado conmigo, y les relaté también las palabras que el rey me había dicho. Ellos dijeron: «¡Levantémonos y construyamos!» Y se afianzaron en su buen propósito.

[[nehemiah-2-19]]
^19^ Al enterarse de ello Samballat el joronita, Tobías el siervo ammonita y Guésem el árabe, se burlaron de nosotros y vinieron a decirnos: «¿Qué hacéis? ¿Es que os habéis rebelado contra el rey?»

[[nehemiah-2-20]]
^20^ Yo les respondí: «El Dios del cielo nos hará triunfar. Nosotros sus siervos, vamos a ponernos a la obra. En cuanto a vosotros, no tenéis parte ni derecho ni recuerdo en Jerusalén».
[[nehemiah-3]]
== Capítulo 3

[[nehemiah-3-1]]
^1^ El sumo sacerdote Elyasib y sus hermanos los sacerdotes se encargaron de construir la puerta de las Ovejas: la armaron, fijaron sus hojas, barras y goznes, y continuaron hasta la torre de los Cien y hasta la torre de Jananel.

[[nehemiah-3-2]]
^2^ Al lado de ellos construyeron los de Jericó; a su lado constuyó Zakkur, hijo de Imrí.

[[nehemiah-3-3]]
^3^ Los hijos de Hassenáa construyeron la puerta de los Peces: la armaron y fijaron sus hojas, barras y goznes.

[[nehemiah-3-4]]
^4^ A su lado reparó Meremot, hijo de Urías, hijo de Haqcós; a continuación reparó Mesullam, hijo de Berekías, hijo de Mesezabel; a su lado reparó Sadoq, hijo de Baaná.

[[nehemiah-3-5]]
^5^ Junto a él repararon los de Técoa, pero sus notables se negaron a poner su cuello al servicio de sus señores.

[[nehemiah-3-6]]
^6^ La puerta del Barrio nuevo la repararon Yoyadá, hijo de Paséaj, y Mesullam, hijo de Besodías: la armaron y fijaron sus hojas, barras y goznes.

[[nehemiah-3-7]]
^7^ A continuación de éstos repararon Melatías de Gabaón y Yadón de Meronot, así como los de Gabaón y de Mispá, a expensas del gobernador de Transeufratina.

[[nehemiah-3-8]]
^8^ A su lado reparó Uzziel, miembro del gremio de los orfebres, y a continuación reparó Jananías, del gremio de los perfumistas: ellos reconstruyeron Jerusalén hasta el muro de la Plaza.

[[nehemiah-3-9]]
^9^ A continuación reparó Refaías, hijo de Jur, jefe de la mitad del distrito de Jerusalén.

[[nehemiah-3-10]]
^10^ A continuación reparó Yedaías, hijo de Harumaf, delante de su casa; a continuación reparó Jattús, hijo de Hasabneías.

[[nehemiah-3-11]]
^11^ Malkiyías, hijo de Jarim, y Jassub, hijo de Pajat Moab, repararon la parte siguiente, hasta la torre de los Hornos.

[[nehemiah-3-12]]
^12^ A continuación de éstos reparó, con sus hijos, Sallum, hijo de Hallojés, jefe de la mitad del distrito de Jerusalén.

[[nehemiah-3-13]]
^13^ Repararon la puerta del Valle, Hanún y los habitantes de Zanóaj: la construyeron, fijaron sus hojas, barras y goznes, e hicieron mil codos de muro, hasta la puerta del Muladar.

[[nehemiah-3-14]]
^14^ La puerta del Muladar la reparó Malkiyías, hijo de Rekab, jefe del distrito de Bet Hakkérem, con sus hijos: fijó sus hojas, barras y goznes.

[[nehemiah-3-15]]
^15^ La puerta de la Fuente la reparó Sallum, hijo de Kol Jozé, jefe del distrito de Mispá: la construyó, la cubrió y fijó sus hojas, barras y goznes. También restauró el muro de la alberca del canal, que está junto al huerto del rey, hasta las escaleras que bajan de la Ciudad de David.

[[nehemiah-3-16]]
^16^ Después de él Nehemías, hijo de Aztuq, jefe de la mitad del distrito de Bet Sur, reparó hasta enfrente de las tumbas de David, hasta la alberca artificial y hasta la Casa de los Valientes.

[[nehemiah-3-17]]
^17^ A continuación repararon los levitas: Rejum, hijo de Baní; a su lado reparó Jasabías, jefe de la mitad del distrito de Queilá, en su distrito;

[[nehemiah-3-18]]
^18^ a continuación repararon sus hermanos: Binnuy, hijo de Jenadad, jefe de la mitad del distrito de Queilá;

[[nehemiah-3-19]]
^19^ a continuación Ezer, hijo de Josué, jefe de Mispá, reparó otra sección frente a la subida del Arsenal del Angulo.

[[nehemiah-3-20]]
^20^ Después de él Baruc, hijo de Zabbay, reparó otro sector, desde el Angulo hasta la puerta de la casa del sumo sacerdote Elyasib.

[[nehemiah-3-21]]
^21^ Después de él Meremot, hijo de Urías, hijo de Haqcós, reparó otro sector, desde la puerta de la casa de Elyasib hasta el término de la misma.

[[nehemiah-3-22]]
^22^ Después de él prosiguieron la reparación los sacerdotes que habitaban en la Vega.

[[nehemiah-3-23]]
^23^ Repararon a continuación Benjamín y Jassub frente a sus casas. Después de ellos Azarías, hijo de Maaseías, hijo de Ananías, reparó junto a su casa.

[[nehemiah-3-24]]
^24^ Después de él Binnuy, hijo de Jenadad, reparó otra sección, desde la casa de Azarías hasta el Angulo y la esquina.

[[nehemiah-3-25]]
^25^ A continuación Palal, hijo de Uzay, reparó enfrente del Angulo y de la torre en saliente de la casa del rey, la de arriba que da al patio de la cárcel. Después de él Pedaías, hijo de Parós, reparó

[[nehemiah-3-26]]
^26^ hasta la puerta de las Aguas hacia Oriente y hasta delante de la torre en saliente.

[[nehemiah-3-27]]
^27^ A continuación los de Técoa repararon otro sector frente a la torre grande en saliente hasta el muro del Ofel.

[[nehemiah-3-28]]
^28^ Desde la puerta de los Caballos repararon los sacerdotes, cada uno frente a su casa.

[[nehemiah-3-29]]
^29^ Después de ellos reparó Sadoq, hijo de Immer, frente a su casa. Después de él reparó Semaías, hijo de Sekanías, encargado de la puerta Oriental.

[[nehemiah-3-30]]
^30^ Después de él, Jananías, hijo de Selemías, y Janún, sexto hijo de Salaf, repararon otro sector. A continuación reparó Mesullam, hijo de Berekías, frente a su vivienda.

[[nehemiah-3-31]]
^31^ Después de él Malkiyías, del gremio de los orfebres, reparó hasta la casa de los donados y de los comerciantes, frente a la puerta de la Inspección, hasta la cámara alta del ángulo.

[[nehemiah-3-32]]
^32^ Y entre la cámara alta del ángulo y la puerta de las Ovejas, repararon los orfebres y los comerciantes.

[[nehemiah-3-33]]
^33^ Cuando Samballat se enteró de que estábamos reconstruyendo la muralla, montó en cólera y se irritó mucho. Se burlaba de los judíos,

[[nehemiah-3-34]]
^34^ y decía delante de sus hermanos y de la gente principal de Samaría: «¿Qué pretenden hacer esos miserables judíos? ¿Es que quieren terminar en un día? ¿Van a dar vida a esas piedras, sacadas de montones de escombros y calcinadas?»

[[nehemiah-3-35]]
^35^ Tobías el ammonita, que estaba junto a él, dijo: «¡Déjales que construyan; que si un chacal se alza, abrirá brecha en su muralla de piedra!»

[[nehemiah-3-36]]
^36^ ¡Escucha, Dios nuestro, porque nos desprecian. Haz que caiga su insulto sobre su cabeza. Entrégalos al desprecio en un país de cautividad!

[[nehemiah-3-37]]
^37^ No pases por alto su iniquidad, ni su pecado sea borrado en tu presencia, porque han insultado a los constructores.

[[nehemiah-3-38]]
^38^ Construimos, pues, la muralla, que quedó terminada hasta media altura. El pueblo había puesto su corazón en el trabajo.
[[nehemiah-4]]
== Capítulo 4

[[nehemiah-4-1]]
^1^ Cuando Samballat, Tobías, los árabes, los ammonitas y los asdoditas se enteraron de que la reparación de la muralla de Jerusalén adelantaba - pues las brechas comenzaban a taparse - se enfurecieron mucho;

[[nehemiah-4-2]]
^2^ y se conjuraron todos a una para venir a atacar a Jerusalén y a humillarme a mí.

[[nehemiah-4-3]]
^3^ Pero invocamos a nuestro Dios y montamos guardia contra ellos de día y de noche.

[[nehemiah-4-4]]
^4^ Judá decía: «¡Flaquean las fuerzas de los cargadores: hay demasiado escombro; nosotros no podemos reconstruir la muralla!»

[[nehemiah-4-5]]
^5^ Y nuestros enemigos decían: «¡Antes que se enteren o se den cuenta, iremos contra ellos, y los mataremos y pararemos la obra!»

[[nehemiah-4-6]]
^6^ Pero algunos judíos que vivían junto a ellos vinieron a advertirnos por diez veces: «Vienen contra nosotros desde todos los lugares que habitan».

[[nehemiah-4-7]]
^7^ Se apostó, pues, el pueblo en los puntos más bajos, detrás de la muralla y en los lugares descubiertos, y coloqué a la gente por familias, cada uno con sus espadas, sus lanzas y sus arcos.

[[nehemiah-4-8]]
^8^ Al ver su miedo, me levanté y dije a los notables, a los consejeros y al resto del pueblo: «¡No les tengáis miedo; acordaos del Señor, grande y terrible, y combatid por vuestros hermanos, vuestros hijos y vuestras hijas, vuestras mujeres y vuestras casas!»

[[nehemiah-4-9]]
^9^ Cuando nuestros enemigos supieron que estábamos advertidos y que Dios había desbaratado sus planes, se retiraron, y todos nosotros volvimos a la muralla, cada cual a su trabajo.

[[nehemiah-4-10]]
^10^ Pero desde aquel día, sólo la mitad de mis hombres tomaban parte en el trabajo; la otra mitad, provistos de lanzas, escudos, arcos y corazas, se mantenía detrás de toda la casa de Judá

[[nehemiah-4-11]]
^11^ que contruía la muralla. También los cargadores estaban armados: con una mano cuidaba cada uno de su trabajo, con la otra empuñaba el arma.

[[nehemiah-4-12]]
^12^ Cada uno de los constructores tenía ceñida a la cintura su espada mientras trabajaba. Había un corneta junto a mí para sonar el cuerno.

[[nehemiah-4-13]]
^13^ Dije a los notables, a los consejeros y al resto del pueblo: «La obra es importante y extensa, y nosotros estamos diseminados a lo largo de la muralla, lejos unos de otros:

[[nehemiah-4-14]]
^14^ corred a reuniros con nosotros al lugar donde oigáis el sonido del cuerno, y nuestro Dios combatira por nosotros».

[[nehemiah-4-15]]
^15^ Así organizábamos el trabajo desde el despuntar del alba hasta que salían las estrellas.

[[nehemiah-4-16]]
^16^ Dije también entonces al pueblo: «Todos pasarán la noche en Jerusalén con sus criados, y así haremos guardia de noche y trabajaremos de día».

[[nehemiah-4-17]]
^17^ Pero ni yo ni mis hermanos ni mis gentes mi los hombres de guardia que me seguían nos quitábamos la ropa; todos nosotros teníamos el arma en la mano.
[[nehemiah-5]]
== Capítulo 5

[[nehemiah-5-1]]
^1^ Un gran clamor se suscitó entre la gente del pueblo y sus mujeres contra sus hermanos judíos.

[[nehemiah-5-2]]
^2^ Había quienes decían: «Nosotros tenemos que dar en prenda nuestros hijos y nuestras hijas para obtener grano con que comer y vivir».

[[nehemiah-5-3]]
^3^ Había otros que decían: «Nosotros tenemos que empeñar nuestros campos, nuestras viñas y nuestras casas para conseguir grano en esta penuria».

[[nehemiah-5-4]]
^4^ Y otros decían: «Tenemos que pedir prestado dinero a cuenta de nuestros campos y de nuestras viñas para el impuesto del rey;

[[nehemiah-5-5]]
^5^ y siendo así que tenemos la misma carne que nuestros hermanos, y que nuestros hijos son como sus hijos, sin embargo tenemos que entregar como esclavos a nuestros hijos y a nuestras hijas; ¡hay incluso entre nuestras hijas quienes son deshonradas! Y no podemos hacer nada, ya que nuestros campos y nuestras viñas pertenecen a otros».

[[nehemiah-5-6]]
^6^ Yo me indigné mucho al oír su queja y estas palabras.

[[nehemiah-5-7]]
^7^ Tomé decisión en mi corazón de reprender a los notables y a los consejeros, y les dije: «¡Qué carga impone cada uno de vosotros a su hermano!» Congregué contra ellos una gran asamblea,

[[nehemiah-5-8]]
^8^ y les dije: «Nosotros hemos rescatado, en la medida de nuestras posibilidades, a nuestros hermanos judíos que habían sido vendidos a las naciones. ¡Y ahora sois vosotros los que vendéis a vuestros hermanos para que nosotros los rescatemos!» Ellos callaron sin saber qué responder.

[[nehemiah-5-9]]
^9^ Y yo continué: «No está bien lo que estáis haciendo. ¿No queréis caminar en el temor de nuestro Dios, para evitar los insultos de las naciones enemigas?

[[nehemiah-5-10]]
^10^ También yo, mis hermanos y mi gente, les hemos prestado dinero y trigo. Pues bien, condonemos estas deudas.

[[nehemiah-5-11]]
^11^ Restituidles inmediatamente sus campos, sus viñas, sus olivares y sus casas, y perdonadles la deuda del dinero, del trigo, del vino y del aceite que les habéis prestado».

[[nehemiah-5-12]]
^12^ Respondieron ellos: «Restituiremos y no les reclamaremos ya nada; haremos como tú has dicho». Entonces llamé a los sacerdotes y les hice jurar que harían seguir esta promesa.

[[nehemiah-5-13]]
^13^ Luego sacudí los plieges de mi manto diciendo: «¡Así sacuda Dios, fuera de su casa y de su hacienda, a todo aquel que no mantenga esta palabra: así sea sacudido y despojado!» Toda la asamblea respondió: «¡Amén!», y alabó a Yahveh. Y el pueblo cumplió esta palabra.

[[nehemiah-5-14]]
^14^ Además, desde el día en que el rey me mandó ser gobernador del país de Judá, desde el año veinte hasta el 32 del rey Artajerjes, durante doce años, ni yo ni mis hermanos comimos jamás del pan del gobernador.

[[nehemiah-5-15]]
^15^ En cambio los gobernadores anteriores que me precedieron gravaban al pueblo: cada día percibían de él, como contribución por el pan, cuarenta siclos de plata; también sus servidores oprimían al pueblo. Pero yo, por temor de Dios, no hice nunca esto.

[[nehemiah-5-16]]
^16^ Además he ayudado a la obra de la reparación de esta muralla, y, aunque no he adquirido campos, toda mi gente estaba también allí colaborando en la tarea.

[[nehemiah-5-17]]
^17^ A mi mesa se sentaban los jefes y los consejeros en número de 150 sin contar los que venían a nosotros de las naciones vecinas.

[[nehemiah-5-18]]
^18^ Diariamente se aderezaban a expensas mías un toro, seis carneros escogidos y aves; y cada diez días se traía cantidad de odres de vino. Y a pesar de todo, jamás reclamé el pan del gobernador, porque un duro trabajo gravaba ya al pueblo.

[[nehemiah-5-19]]
^19^ ¡Acuérdate, Dios mío, para mi bien, de todo lo que he hecho por este pueblo!
[[nehemiah-6]]
== Capítulo 6

[[nehemiah-6-1]]
^1^ Cuando Samballat, Tobías, Guésem el árabe, y los demás enemigos nuestros se enteraron de que yo había reconstruido la muralla y de que ya no quedaba en ella brecha alguna - aunque en aquel tiempo no estaban colocadas las hojas de las puertas -

[[nehemiah-6-2]]
^2^ Samballat y Guésem mandaron a decirme: «Ven a entrevistarte con nosotros en Hakkefirim, en el valle de Onó». Pero ellos tramaban hacerme mal.

[[nehemiah-6-3]]
^3^ Por eso les envié mensajeros para decirles: «Estoy ocupado en una obra importante y no puedo bajar; ¿por qué voy a dejar que la obra se pare abandonándola para bajar donde vosotros?»

[[nehemiah-6-4]]
^4^ Cuatro veces me enviaron el mismo recado, y yo di la misma respuesta.

[[nehemiah-6-5]]
^5^ Entonces Samballat me envió a decir por quinta vez lo mismo por un criado suyo que traía una carta abierta

[[nehemiah-6-6]]
^6^ en la que estaba escrito: «Se oye entre las naciones, y así lo afirma Gasmu, el rumor de que tú y los judíos estáis pensando sublevaros; que para ello reconstruyes la muralla y tratas de hacerte su rey,

[[nehemiah-6-7]]
^7^ que incluso has designado profetas para proclamar acerca de ti en Jerusalén: ¡Judá tiene rey! Estos rumores van a ser oídos por el rey; así que ven para que tomemos consejo juntos».

[[nehemiah-6-8]]
^8^ Pero yo les mandé decir: «No hay nada de eso que dices; son invenciones de tu corazón».

[[nehemiah-6-9]]
^9^ Porque lo que querían era meternos miedo, pensando: «Desfallecerán sus manos y no acabarán la obra». Pero, por el contrario, yo me reafirmé más.

[[nehemiah-6-10]]
^10^ Había ido yo a casa de Semaías, hijo de Delaías, hijo Mehetabel, que se encontraba detenido. Dijo él: «Démonos cita en la Casa de Dios, en el interior del santuario; cerremos las puertas del santurario; porque van a venir a matarte, esta misma noche vienen a matarte».

[[nehemiah-6-11]]
^11^ Pero yo respondí: «¿Un hombre como yo va a huir? ¿Qué hombre que sea como yo entraría en el santurario para salvar su vida? No iré».

[[nehemiah-6-12]]
^12^ Pues comprendí que él no había sido enviado por Dios, sino que había dicho esta profecía sobre mí porque Tobías le había comprado,

[[nehemiah-6-13]]
^13^ para que yo, llevado del miedo, lo hiciera así y pecase; y esto me diera mala fama y pudieran burlarse de mí.

[[nehemiah-6-14]]
^14^ Acuérdate, Dios mío, de Tobías, por lo que ha hecho; y también de Noadía, la profetisa, y de los demás profetas que trataron de asustarme.

[[nehemiah-6-15]]
^15^ La muralla quedó terminada el día veinticinco de Elul, en 52 días.

[[nehemiah-6-16]]
^16^ Cuando se enteraron todos nuestros enemigos y todas las naciones de alrededor lo vieron, les pareció una gran maravilla y reconocieron que esta obra había sido realizada por nuestro Dios.

[[nehemiah-6-17]]
^17^ En aquellos mismos días, los notables de Judá multiplicaron sus cartas dirigidas a Tobías y recibían las de éste;

[[nehemiah-6-18]]
^18^ porque tenía en Judá muchos aliados, por ser yerno de Sekanías, hijo de Ará, y por estar casado su hijo Yehojanán con la hija de Mesullam, hijo de Berekías.

[[nehemiah-6-19]]
^19^ Incluso llegaron a hablar bien de Tobías en mi presencia y le repetían mis palabras. Y Tobías mandaba cartas para intimidarme.
[[nehemiah-7]]
== Capítulo 7

[[nehemiah-7-1]]
^1^ Reconstruida la muralla, y una vez que hube fijado las hojas de las puertas, se colocaron guardias en las puertas (cantores y levitas).

[[nehemiah-7-2]]
^2^ Puse al frente de Jerusalén a mi hermano Jananí y a Jananías, jefe de la ciudadela, porque era un hombre fiel y temeroso de Dios como pocos;

[[nehemiah-7-3]]
^3^ y les dije: «No se abrirán las puertas de Jerusalén hasta que el sol comience a calentar; y cuando todavía esté alto, se cerrarán y se echarán las barras a las puertas; y se establecerán puestos de guardia de entre los habitantes de Jerusalén, unos en su puesto y otros delante de su casa».

[[nehemiah-7-4]]
^4^ La ciudad era espaciosa y grande, pero tenía muy poca población y no se fundaban nuevas familias.

[[nehemiah-7-5]]
^5^ Me puso Dios en el corazón reunir a los notables, a los consejeros y al pueblo, para hacer el registro genealógico. Hallé el registro genealógico de los que habían venido al principio, y encontré escrito en él:

[[nehemiah-7-6]]
^6^ Estas son las personas de la provincia que regresaron del cautiverio, aquellos que Nabucodonosor, rey de Babilonia, había deportado y que volvieron a Jerusalén y Judea, cada uno a su ciudad.

[[nehemiah-7-7]]
^7^ Vinieron con Zorobabel, Josué, Nehemías, Azarías, Raamías, Najamaní, Mardoqueo, Bilsán, Mispéret, Bigvay, Nejum y Baaná. Lista de los hombres del pueblo de Israel:

[[nehemiah-7-8]]
^8^ los hijos de Parós: 2.172;

[[nehemiah-7-9]]
^9^ los hijos de Sefatías: 372;

[[nehemiah-7-10]]
^10^ los hijos de Araj: 652;

[[nehemiah-7-11]]
^11^ los hijos de Pajat Moab, por parte de los hijos de Josué y de Joab: 2.818;

[[nehemiah-7-12]]
^12^ los hijos de Elam: 1.254;

[[nehemiah-7-13]]
^13^ los hijos de Zattú: 845;

[[nehemiah-7-14]]
^14^ los hijos de Zakkay: 760;

[[nehemiah-7-15]]
^15^ los hijos de Binnuy: 648;

[[nehemiah-7-16]]
^16^ los hijos de Bebay: 628;

[[nehemiah-7-17]]
^17^ los hijos de Azgad: 2.322;

[[nehemiah-7-18]]
^18^ los hijos de Adonicam: 667;

[[nehemiah-7-19]]
^19^ los hijos de Bigvay: 2.067;

[[nehemiah-7-20]]
^20^ los hijos de Adín: 655;

[[nehemiah-7-21]]
^21^ los hijos de Ater, de Ezequías: 98;

[[nehemiah-7-22]]
^22^ los hijos de Jalum: 328;

[[nehemiah-7-23]]
^23^ los hijos de Besay: 324;

[[nehemiah-7-24]]
^24^ los hijos de Jarif: 112;

[[nehemiah-7-25]]
^25^ los hijos de Gabaón: 95;

[[nehemiah-7-26]]
^26^ los hombres de Belén y de Netofá: 188;

[[nehemiah-7-27]]
^27^ los hombres de Anatot: 128;

[[nehemiah-7-28]]
^28^ los hombres de Bet Azmávet: 42;

[[nehemiah-7-29]]
^29^ los hombres de Quiryat Yearim, Kefirá y Beerot: 743;

[[nehemiah-7-30]]
^30^ los hombres de Ramá y Gueba: 621;

[[nehemiah-7-31]]
^31^ los hombres de Mikmás: 122;

[[nehemiah-7-32]]
^32^ los hombres de Betel y de Ay: 123;

[[nehemiah-7-33]]
^33^ los hombres de Nebo: 52;

[[nehemiah-7-34]]
^34^ los hijos del otro Elam: 1.254;

[[nehemiah-7-35]]
^35^ los hijos de Jarim: 320;

[[nehemiah-7-36]]
^36^ los hombres de Jericó: 345;

[[nehemiah-7-37]]
^37^ los hijos de Lod, Jadid y Onó: 721;

[[nehemiah-7-38]]
^38^ los hijos de Senaá: 3.930.

[[nehemiah-7-39]]
^39^ Sacerdotes: los hijos de Yedaías, de la casa de Josué: 973;

[[nehemiah-7-40]]
^40^ los hijos de Immer: 1.052;

[[nehemiah-7-41]]
^41^ los hijos de Pasjur: 1.247;

[[nehemiah-7-42]]
^42^ los hijos de Jarim: 1.017.

[[nehemiah-7-43]]
^43^ Levitas: los hijos de Josué y Cadmiel, de los hijos de Hodías: 74.

[[nehemiah-7-44]]
^44^ Cantores: los hijos de Asaf: 148.

[[nehemiah-7-45]]
^45^ Porteros: los hijos de Sallum, los hijos de Ater, los hijos de Talmón, los hijos de Aqcub, los hijos de Jatitá, los hijos de Sobay: 138.

[[nehemiah-7-46]]
^46^ Donados: los hijos de Sijá, los hijos de Jasufá, los hijos de Tabbaot,

[[nehemiah-7-47]]
^47^ los hijos de Querós, los hijos de Siá, los hijos de Padón,

[[nehemiah-7-48]]
^48^ los hijos de Lebaná, los hijos de Jagabá, los hijos de Salmay,

[[nehemiah-7-49]]
^49^ los hijos de Janán, los hijos de Guiddel, los hijos de Gajar,

[[nehemiah-7-50]]
^50^ los hijos de Reaías, los hijos de Resín, los hijos de Necodá,

[[nehemiah-7-51]]
^51^ los hijos de Gazzam, los hijos de Uzzá, los hijos de Paséaj,

[[nehemiah-7-52]]
^52^ los hijos de Besay, los hijos de los meunitas, los hijos de los nefusitas,

[[nehemiah-7-53]]
^53^ los hijos de Baqbuq, los hijos de Jacufá, los hijos de Jarjur,

[[nehemiah-7-54]]
^54^ los hijos de Baslit, los hijos de Mejidá, los hijos de Jarsá,

[[nehemiah-7-55]]
^55^ los hijos de Barcós, los hijos de Sisrá, los hijos de Témaj,

[[nehemiah-7-56]]
^56^ los hijos de Nesíaj, los hijos de Jatifá.

[[nehemiah-7-57]]
^57^ Los hijos de los siervos de Salomón: los hijos de Setay, los hijos de Soféret, los hijos de Peridá,

[[nehemiah-7-58]]
^58^ los hijos de Yaalá, los hijos de Darcón, los hijos de Guiddel,

[[nehemiah-7-59]]
^59^ los hijos de Sefatías, los hijos de Jattil, los hijos de Pokéret Hassebayim, los hijos de Amón.

[[nehemiah-7-60]]
^60^ Total de los donados y de los hijos de los siervos de Salomón: 392.

[[nehemiah-7-61]]
^61^ Y estos eran los que venían de Tel Mélaj, Tel Jarsá, Kerub, Addón e Immer, y que no pudieron probar si su familia y su estirpe eran de origen israelita:

[[nehemiah-7-62]]
^62^ los hijos de Belaías, los hijos de Tobías, los hijos de Necodá: 642.

[[nehemiah-7-63]]
^63^ Y entre los sacerdotes, los hijos de Jobayías, los hijos Haqcós, los hijos de Barzillay - el cual se había casado con una de las hijas de Barzillay el galaadita, cuyo nombre adoptó -.

[[nehemiah-7-64]]
^64^ Estos investigaron en su registro genealógico, pero no figuraban; por lo cual se les excluyó del sacerdocio como ilegítimos,

[[nehemiah-7-65]]
^65^ y el Gobernador les prohibió comer de las cosas sacratísimas hasta que no se presentara un sacerdote para el Urim y el Tummim.

[[nehemiah-7-66]]
^66^ La asamblea ascendía a 42.360 personas,

[[nehemiah-7-67]]
^67^ sin contar sus siervos y siervas en número de 7.337; tenían también 245 cantores y cantoras.

[[nehemiah-7-68]]
^68^ Tenían (736 caballos, 245 mulos) 435 camellos y 6.720 asnos.

[[nehemiah-7-69]]
^69^ Algunos de los cabezas de familia hicieron ofrendas para la obra. El Gobernador entregó al tesoro mil dracmas de oro, 50 copas y 30 túnicas sacerdotales.

[[nehemiah-7-70]]
^70^ Entre los cabezas de familia entregaron al tesoro de la obra 20.000 dracmas de oro y 2.200 minas de plata.

[[nehemiah-7-71]]
^71^ Lo que entregó el resto del pueblo ascendía a 20.000 dracmas de oro, 2.000 minas de plata y 67 túnicas sacerdotales.

[[nehemiah-7-72]]
^72^ Los sacerdotes, los levitas, los porteros, los cantores, los donados y todos los demás israelitas se establecieron en sus ciudades. Llegado el mes séptimo,
[[nehemiah-8]]
== Capítulo 8

[[nehemiah-8-1]]
^1^ todo el pueblo se congregó como un solo hombre en la plaza que está delante de la puerta del Agua. Dijeron al escriba Esdras que trajera el libro de la Ley de Moisés que Yahveh había prescrito a Israel.

[[nehemiah-8-2]]
^2^ Trajo el sacerdote Esdras la Ley ante la asamblea, integrada por hombres, mujeres y todos los que tenían uso de razón. Era el día uno del mes séptimo.

[[nehemiah-8-3]]
^3^ Leyó una parte en la plaza que está delante de la puerta del Agua, desde el alba hasta el mediodía, en presencia de los hombres, las mujeres y todos los que tenían uso de razón; y los oídos del pueblo estaban atentos al libro de la Ley.

[[nehemiah-8-4]]
^4^ El escriba Esdras estaba de pie sobre un estrado de madera levantado para esta ocasión; junto a él estaban: a su derecha, Matitías, Semá, Anaías, Urías, Jilquías y Maaseías, y a su izquierda, Pedaías, Misael, Malkías, Jasum, Jasbaddaná, Zacarías y Mesullam.

[[nehemiah-8-5]]
^5^ Esdras abrió el libro a los ojos de todo el pueblo - pues estaba más alto que todo el pueblo - y al abrirlo, el pueblo entero se puso en pie.

[[nehemiah-8-6]]
^6^ Esdras bendijo a Yahveh, el Dios grande; y todo el pueblo, alzando las manos, respondió: «¡Amén! ¡Amén!»; e inclinándose se postraron ante Yahveh, rostro en tierra.

[[nehemiah-8-7]]
^7^ (Josué, Baní, Serebías, Yamín, Aqcub, Sabtay, Hodiyías, Maaseías, Quelitá, Azarías, Yozabad, Janán, Pelaías, que eran levitas, explicaban la Ley al pueblo que seguía en pie.)

[[nehemiah-8-8]]
^8^ Y Esdras leyó en el libro de la Ley de Dios, aclarando e interpretando el sentido, para que comprendieran la lectura.

[[nehemiah-8-9]]
^9^ Entonces (Nehemías - el gobernador - y) Esdras, el sacerdote excriba (y los levitas que explicaban al pueblo) dijeron a todo el pueblo: «Este día está consagrado a Yahveh vuestro Dios; no estéis tristes ni lloréis»; pues todo el pueblo lloraba al oír las palabras de la Ley.

[[nehemiah-8-10]]
^10^ Díjoles también: «Id y comed manjares grasos, bebed bebidas dulces y mandad su ración a quien no tiene nada preparado. Porque este día está consagrado a nuestro Señor. No estéis tristes: la alegría de Yahveh es vuestra fortaleza».

[[nehemiah-8-11]]
^11^ También los levitas tranquilizaban al pueblo diciéndole: «Callad: este día es santo. No estéis tristes».

[[nehemiah-8-12]]
^12^ Y el pueblo entero se fue a comer y beber, a repartir raciones y hacer gran festejo, porque habían comprendido las palabras que les habían enseñado.

[[nehemiah-8-13]]
^13^ El segundo día los cabezas de familia de todo el pueblo, los sacerdotes y levitas se reunieron junto al escriba Esdras para comprender las palabras de la Ley.

[[nehemiah-8-14]]
^14^ Y encontraron escrito en la Ley que Yahveh había mandado por medio de Moisés que los hijos de Israel habitaran en cabañas durante la fiesta del séptimo mes.

[[nehemiah-8-15]]
^15^ En cuanto lo oyeron, hicieron pregonar en todas las ciudades y en Jerusalén: «Salid al monte y traed ramas de olivo, de pino, de mirto, de palmera y de otros árboles frondosos, para hacer cabañas conforme a lo escrito».

[[nehemiah-8-16]]
^16^ Salió el pueblo y trajeron ramas y se hicieron cabañas, cada uno en su terrado, en sus patios, en los atrios de la Casa de Dios, en la plaza de la puerta del Agua y en la plaza de la puerta de Efraím.

[[nehemiah-8-17]]
^17^ Toda la asamblea, los que habían vuelto del cautiverio, construyó cabañas y habitó en ellas - cosa que los israelitas no habían hecho desde los días de Josué, hijo de Nun, hasta aquel día - y hubo gran regocijo.

[[nehemiah-8-18]]
^18^ Esdras leyó en el libro de la Ley de Dios diariamente, desde el primer día al último. Durante siete días, se celebró fiesta; al octavo tuvo lugar, según la norma, una asamblea solemne.
[[nehemiah-9]]
== Capítulo 9

[[nehemiah-9-1]]
^1^ El día veinticuatro de aquel mismo mes, se congregaron los israelitas para ayunar, vestidos de sayal y la cabeza cubierta de polvo.

[[nehemiah-9-2]]
^2^ La raza de Israel se separó de todos los extranjeros; y puestos en pie, confesaron sus pecados y las culpas de sus padres.

[[nehemiah-9-3]]
^3^ (De pie y cada uno en su sitio, leyeron en el libro de la Ley de Yahveh su Dios, por espacio de un cuarto de día; durante otro cuarto hacían confesión y se postraban ante Yahveh su Dios.)

[[nehemiah-9-4]]
^4^ (Josué, Binnuy, Cadmiel, Sebanías, Bunní, Serebías, Baní y Quenaní subieron al estrado de los levitas y clamaron en alta voz hacia Yahveh su Dios,

[[nehemiah-9-5]]
^5^ y los levitas Josué, Cadmiel, Baní, Jasabneías, Serebías, Hodiyías, Sebanías y Petajías dijeron: «¡Levantaos, bendecid a Yahveh nuestro Dios!») ¡Bendito seas, Yahveh Dios nuestro, de eternidad en eternidad! ¡Y sea bendito el Nombre de tu Gloria que supera toda bendición y alabanza!

[[nehemiah-9-6]]
^6^ ¡Tú, Yahveh, tú el único! Tú hiciste los cielos, el cielo de los cielos y toda su mesnada, la tierra y todo cuanto abarca, los mares y todo cuanto encierran. Todo esto tú lo animas, y la mesnada de los cielos ante ti se prosterna.

[[nehemiah-9-7]]
^7^ Tú, Yahveh, eres el Dios que elegiste a Abram, le sacaste de Ur de Caldea y le diste el nombre de Abraham.

[[nehemiah-9-8]]
^8^ Hallaste su corazón fiel ante ti, con él hiciste alianza, para darle el país del cananeo, del hitita y del amorreo, del perizita, del jebuseo y del guirgasita, a él y a su posteridad. Y has mantenido tu palabra, porque eres justo.

[[nehemiah-9-9]]
^9^ Tú viste la aflicción de nuestros padres en Egipto, y escuchaste su clamor junto al mar de Suf.

[[nehemiah-9-10]]
^10^ Contra Faraón obraste señales y prodigios, contra sus siervos y todo el pueblo de su país, pues supiste que eran altivos con ellos. ¡Te hiciste un nombre hasta el día de hoy!

[[nehemiah-9-11]]
^11^ Tú hendiste el mar ante ellos: por medio del mar pasaron a pie enjuto. Hundiste en los abismos a sus perseguidores, como una piedra en aguas poderosas.

[[nehemiah-9-12]]
^12^ Con columna de nube los guiaste de día, con columna de fuego por la noche, para alumbrar ante ellos el camino por donde habían de marchar.

[[nehemiah-9-13]]
^13^ Bajaste sobre el monte Sinaí y del cielo les hablaste; les diste normas justas, leyes verdaderas, preceptos y mandamientos excelentes;

[[nehemiah-9-14]]
^14^ les diste a conocer tu santo sábado; les ordenaste mandamientos, preceptos y Ley por mano de Moisés, tu siervo.

[[nehemiah-9-15]]
^15^ Del cielo les mandaste el pan para su hambre, para su sed hiciste brotar el agua de la roca. Y les mandaste ir a apoderarse de la tierra que tú juraste darles mano en alto.

[[nehemiah-9-16]]
^16^ Altivos se volvieron nuestros padres, su cerviz endurecieron y desoyeron tus mandatos.

[[nehemiah-9-17]]
^17^ No quisieron oír, no recordaron los prodigios que con ellos hiciste; endurecieron la cerviz y se obstinaron en volver a Egipto y a su servidumbre. Pero tú eres el Dios de los perdones, clemente y entrañable, tardo a la cólera y rico en bondad. ¡No los desamparaste!

[[nehemiah-9-18]]
^18^ Ni siquiera cuando se fabricaron un becerro de metal fundido y exclamaron: «¡Este es tu dios que te sacó de Egipto!» (grandes desprecios te hicieron).

[[nehemiah-9-19]]
^19^ Tú, en tu inmensa ternura, no los abandonaste en el desierto: la columna de nube no se apartó de ellos, para guiarles de día por la ruta, ni la columna de fuego por la noche, para alumbrar ante ellos el camino por donde habían de marchar.

[[nehemiah-9-20]]
^20^ Tu Espíritu bueno les diste para instruirles, el maná no retiraste de su boca, y para su sed les diste agua.

[[nehemiah-9-21]]
^21^ Cuarenta años los sustentaste en el desierto, y nada les faltó: ni sus vestidos se gastaron ni se hincharon sus pies.

[[nehemiah-9-22]]
^22^ Reinos y pueblos les donaste y las tierras vecinas repartiste: se apoderaron del país de Sijón, rey de Jesbón, y del país de Og, rey de Basán.

[[nehemiah-9-23]]
^23^ Y multiplicaste sus hijos como estrellas del cielo, los llevaste a la tierra que a sus padres dijiste que entrarían a poseer.

[[nehemiah-9-24]]
^24^ Llegaron los hijos y tomaron el país, y tú ante ellos aplastaste a los habitantes del país, los cananeos, los pusiste en sus manos, con sus reyes y las gentes del país, para que los trataran a merced de su capricho.

[[nehemiah-9-25]]
^25^ Ciudades fuertes conquistaron y una tierra generosa; y heredaron casas de toda suerte de bienes rebosantes, cisternas ya excavadas, viñas y olivares, árboles frutales sin medida: comieron, se saciaron, engordaron, se deleitaron en tus inmensos bienes.

[[nehemiah-9-26]]
^26^ Pero después, indóciles, se rebelaron contra ti, arrojaron tu Ley a sus espaldas, mataron a los profetas que les conjuraban a convertirse a ti; (grandes desprecios te hicieron).

[[nehemiah-9-27]]
^27^ Tú los entregaste en poder de sus enemigos que los oprimieron. Durante su opresión clamaban hacia ti, y tú los escuchabas desde el cielo; y en tu inmensa ternura les mandabas salvadores que los libraron de las manos opresoras.

[[nehemiah-9-28]]
^28^ Pero, apenas en paz, volvían a hacer el mal ante ti, y tú los dejabas en mano de sus enemigos que los oprimían. Ellos de nuevo gritaban hacia ti, y tú escuchabas desde el cielo: ¡muchas veces, por ternura, los salvaste!

[[nehemiah-9-29]]
^29^ Les conminaste para volverlos a tu Ley, pero ellos en su orgullo no escucharon tus mandatos; contra tus normas pecaron, contra aquellas que, cumplidas, dan la vida; dieron la espalda, endurecieron su cerviz y no escucharon.

[[nehemiah-9-30]]
^30^ Tuviste paciencia con ellos durante muchos años; les advertiste por tu Espíritu, por boca de tus profetas; pero ellos no escucharon. Y los pusiste en manos de las gentes de los países.

[[nehemiah-9-31]]
^31^ Mas en tu inmensa ternura no los acabaste, no los abandonaste, porque eres tú Dios clemente y lleno de ternura.

[[nehemiah-9-32]]
^32^ Ahora, pues, oh Dios nuestro, tú, Dios grande, poderoso y temible, que mantienes la alianza y el amor, no menosprecies esta miseria que ha caído sobre nosotros, sobre nuestros reyes y príncipes, nuestros sacerdotes y profetas, sobre todo tu pueblo, desde los tiempos de los reyes de Asiria hasta el día de hoy.

[[nehemiah-9-33]]
^33^ Has sido justo en todo lo que nos ha sobrevenido, pues tú fuiste fiel, y nosotros malvados:

[[nehemiah-9-34]]
^34^ nuestros reyes y jefes, nuestros sacerdotes y padres no guardaron tu Ley, no hicieron caso de los mandamientos y dictámenes que tú les diste.

[[nehemiah-9-35]]
^35^ Mientras vivían en su reino, entre los grandes bienes que tú les regalabas, y en la espaciosa y generosa tierra que tú les habías preparado, no te sirvieron ellos ni se convirtieron de sus malas acciones.

[[nehemiah-9-36]]
^36^ Míranos hoy a nosotros esclavos, y en el país que habías dado a nuestros padres para gozar de sus frutos y bienes, mira que aquí en servidumbre nos sumimos.

[[nehemiah-9-37]]
^37^ Sus muchos frutos son para los reyes, que por nuestros pecados tú nos impusiste, y que a capricho dominan nuestras personas, cuerpos y ganados. ¡En gran angustia nos hallamos!
[[nehemiah-10]]
== Capítulo 10

[[nehemiah-10-1]]
^1^ De acuerdo con todo esto, nosotros tomamos un firme compromiso por escrito. En el documento sellado figuran nuestros jefes, nuestros levitas y nuestros sacerdotes...

[[nehemiah-10-2]]
^2^ En el documento sellado figuraban: Nehemías, hijo de Jakalías, y Sedecías.

[[nehemiah-10-3]]
^3^ Seraías, Azarías, Jeremías,

[[nehemiah-10-4]]
^4^ Pasjur, Amarías, Malkías,

[[nehemiah-10-5]]
^5^ Jattús, Sebanías, Malluk,

[[nehemiah-10-6]]
^6^ Jarim, Meremot, Abdías,

[[nehemiah-10-7]]
^7^ Daniel, Guinnetón, Baruc,

[[nehemiah-10-8]]
^8^ Mesullam, Abías, Miyyamín,

[[nehemiah-10-9]]
^9^ Maazías, Bilgay, Semaías: estos son los sacerdotes.

[[nehemiah-10-10]]
^10^ Luego los levitas: Josué, hijo de Azanías, Binnuy, de los hijos de Jenadad, Cadmiel

[[nehemiah-10-11]]
^11^ y sus hermanos Sekanías, Hodavías, Quelitá, Pelaías, Janán,

[[nehemiah-10-12]]
^12^ Miká, Rejob, Jasabías,

[[nehemiah-10-13]]
^13^ Zakkur, Serebías, Sebanías,

[[nehemiah-10-14]]
^14^ Hodiyías, Baní, Quenaní.

[[nehemiah-10-15]]
^15^ Los jefes del pueblo: Parós, Pajat Moab, Elam, Zattú, Baní,

[[nehemiah-10-16]]
^16^ Bunní, Azgad, Bebay,

[[nehemiah-10-17]]
^17^ Adonías, Bigvay, Adín,

[[nehemiah-10-18]]
^18^ Ater, Ezequías, Azzur,

[[nehemiah-10-19]]
^19^ Hodiyías, Jatum, Besay,

[[nehemiah-10-20]]
^20^ Jarif, Anatot, Nobay,

[[nehemiah-10-21]]
^21^ Magpiás, Mesullam, Jezir,

[[nehemiah-10-22]]
^22^ Mesezabel, Sadoq, Yaddúa,

[[nehemiah-10-23]]
^23^ Pelatías, Janán, Hanaías,

[[nehemiah-10-24]]
^24^ Oseas, Jananías, Jassub,

[[nehemiah-10-25]]
^25^ Hallojés, Piljá, Sobeq,

[[nehemiah-10-26]]
^26^ Rejum, Jasabná, Maaseías,

[[nehemiah-10-27]]
^27^ Ajías, Janán, Anán,

[[nehemiah-10-28]]
^28^ Malluk, Jarim, Baaná.

[[nehemiah-10-29]]
^29^ y el resto del pueblo, los sacerdotes y los levitas los porteros, los cantores, los donados y todos los separados de las gentes del país para seguir la Ley de Dios, sus mujeres, sus hijos y sus hijas, cuantos tienen uso de razón,

[[nehemiah-10-30]]
^30^ se adhieren a sus hermanos y a los nobles y se comprometen por imprecación y juramento a caminar en la Ley de Dios, que fue dada por mano de Moisés, siervo de Dios, y a guardar y practicar todos los mandamientos de Yahveh nuestro Señor, sus normas y sus leyes.

[[nehemiah-10-31]]
^31^ A no dar nuestras hijas a las gentes del país ni tomar sus hijas para nuestros hijos.

[[nehemiah-10-32]]
^32^ Si las gentes del país traen, en día de sábado, mercancías o cualquier otra clase de comestibles para vender, nada les compraremos en día de sábado ni en día sagrado. En el año séptimo abandonaremos el producto de la tierra y todas las deudas.

[[nehemiah-10-33]]
^33^ Nos imponemos como obligación: Dar un tercio de siclo al año para el servicio de la Casa de nuestro Dios:

[[nehemiah-10-34]]
^34^ para el pan que se presenta, para la oblación perpetua y el holocausto perpetuo, para los sacrificios de los sábados, de los novilunios, de las solemnidades, para los alimentos sagrados, para los sacrificios por el pecado como expiación por Israel y para toda la obra de la Casa de nuestro Dios;

[[nehemiah-10-35]]
^35^ Hemos echado a suertes - sacerdotes, levitas y pueblo - la ofrenda de la leña que ha de traer a la Casa de nuestro Dios cada familia en su turno, a sus tiempos, cada año, para quemarla sobre el altar de Yahveh nuestro Dios con arreglo a lo escrito en la Ley.

[[nehemiah-10-36]]
^36^ y traer cada año a la Casa de Yahveh las primicias de nuestro suelo y las primicias de los frutos de todos los árboles,

[[nehemiah-10-37]]
^37^ y los primogénitos de nuestros hijos y de nuestro ganado, conforme a lo escrito en la Ley - los primeros nacidos de nuestro ganado mayor y menor, que se traen a la Casa de nuestro Dios son para los sacerdotes que ejercen el ministerio en la casa de nuestro Dios -.

[[nehemiah-10-38]]
^38^ Lo mejor de nuestras moliendas, de los frutos de todo árbol, del vino y del aceite, se lo traeremos a los sacerdotes, a los aposentos de la Casa de nuestro Dios; y el diezmo de nuestro suelo a los levitas, y ellos mismos cobrarán el diezmo en todas las ciudades de nuestra labranza;

[[nehemiah-10-39]]
^39^ un sacerdote, hijo de Aarón, irá con los levitas cuando éstos cobren el diezmo; los levitas subirán el diezmo del diezmo a la Casa de nuestro Dios a los aposentos de la casa del tesoro;

[[nehemiah-10-40]]
^40^ pues a estos aposentos traen los israelitas y los levitas la ofrenda reservada de trigo, vino y aceite; allí se encuentran también los utensilios del santuario, de los sacerdotes que están de servicio y de los porteros y cantores. No abandonaremos más la Casa de nuestro Dios.
[[nehemiah-11]]
== Capítulo 11

[[nehemiah-11-1]]
^1^ Los jefes del pueblo se establecieron en Jerusalén. El resto del pueblo echó a suertes para que de cada diez hombres habitase uno en Jerusalén, la Ciudad Santa, quedando los otros nueve en las ciudades.

[[nehemiah-11-2]]
^2^ Y el pueblo bendijo a todos los hombres que se ofrecieron voluntarios para habitar en Jerusalén.

[[nehemiah-11-3]]
^3^ Estos son los jefes de la provincia que se establecieron en Jerusalén y en las ciudades de Judá; Israel, sacerdotes, levitas, donados e hijos de los siervos de Salomón, vivían en sus ciudades, cada uno en su propiedad.

[[nehemiah-11-4]]
^4^ Habitaban en Jerusalén hijos de Judá e hijos de Benjamín. De los hijos de Judá: Ataías, hijo de Uzzías, hijo de Zacarías, hijo de Amarías, hijo de Sefatías, hijo de Mahalalel, de los hijos de Peres;

[[nehemiah-11-5]]
^5^ Maaseías, hijo de Baruc, hijo de Kol Jozé, hijo de Jazaías, hijo de Adaías, hijo de Yoyarib, hijo de Zacarías, el selanita.

[[nehemiah-11-6]]
^6^ El total de los hijos de Peres que habitaban en Jerusalén era de 468, hombres vigorosos.

[[nehemiah-11-7]]
^7^ Los hijos de Benjamín eran: Sallú, hijo de Mesullam, hijo de Yoed, hijo de Pedaías, hijo de Colaías, hijo de Maaseías, hijo de Itiel, hijo de Isaías,

[[nehemiah-11-8]]
^8^ y sus hermanos, hombres vigorosos: 928.

[[nehemiah-11-9]]
^9^ Joel, hijo de Zikrí, era su encargado y Judá, hijo de Hassenúa, era el segundo jefe de la ciudad.

[[nehemiah-11-10]]
^10^ De los sacerdotes: Yedaías, hijo de Yoyaquim, hijo de

[[nehemiah-11-11]]
^11^ Seraías, hijo de Jilquías, hijo de Mesullam, hijo de Sadoq, hijo de Merayot, hijo de Ajitub, príncipe de la Casa de Dios,

[[nehemiah-11-12]]
^12^ y sus hermanos empleados en la obra de la Casa: 822; Adaías, hijo de Yerojam, hijo de Pelalías, hijo de Amsí, hijo de Zacarías, hijo de Pasjur, hijo de Malkías,

[[nehemiah-11-13]]
^13^ y sus hermanos, cabezas de familia: 242; y Amasay, hijo de Azarel, hijo de Ajzay, hijo de Mesillemot, hijo de Immer,

[[nehemiah-11-14]]
^14^ y sus hermanos, hombres vigorosos: 128. Su encargado era Zabdiel, hijo de Haggadol.

[[nehemiah-11-15]]
^15^ De los levitas: Semaías, hijo de Jassub, hijo de Azricam, hijo de Jasabías, hijo de Bunní;

[[nehemiah-11-16]]
^16^ Sabtay y Yozabad, que entre los jefes de los levitas estaban al frente de los servicios exteriores de la Casa de Dios;

[[nehemiah-11-17]]
^17^ Mattanías, hijo de Miká, hijo de Zabdí, hijo de Asaf, que dirigía los himnos, entonaba la acción de gracias de la oración; Baqbuquías, el segundo entre sus hermanos; Abdías, hijo de Sammúa, hijo de Galal, hijo de Yedutún.

[[nehemiah-11-18]]
^18^ Total de los levitas en la Ciudad santa: 284.

[[nehemiah-11-19]]
^19^ Los porteros: Aqcub, Talmón y sus hermanos, que hacían la guardia de las puertas: 172.

[[nehemiah-11-20]]
^20^ El resto de los israelitas, de los sacerdotes y levitas, se estableció en todas las ciudades de Judá, cada uno en su heredad.

[[nehemiah-11-21]]
^21^ Los donados habitaban el Ofel; Sijá y Guispá estaban al frente de los donados.

[[nehemiah-11-22]]
^22^ El encargado de los levitas en Jerusalén era Uzzí, hijo de Baní, hijo de Jasabías, hijo de Mattanías, hijo de Miká; era uno de los hijos de Asaf que estaban encargados del canto según el servicio de la Casa de Dios;

[[nehemiah-11-23]]
^23^ porque había acerca de los cantores un mandato del rey y un reglamento que fijaba los actos de cada día.

[[nehemiah-11-24]]
^24^ Petajías, hijo de Mesezabel, de los hijos de Zéraj, hijo de Judá, estaba a las órdenes del rey para todos los asuntos del pueblo,

[[nehemiah-11-25]]
^25^ y en los poblados situados en sus campos. Parte de los hijos de Judá habitaban en Quiryat Haarbá y sus aldeas anejas, en Dibón y sus aldeas anejas, en Jeqcabsel y sus poblados,

[[nehemiah-11-26]]
^26^ en Yesúa, en Moladá, en Bet Pélet,

[[nehemiah-11-27]]
^27^ en Jasar Sual, en Berseba y sus aldeas anejas,

[[nehemiah-11-28]]
^28^ en Siquelag, en Mekoná y sus aldeas anejas,

[[nehemiah-11-29]]
^29^ en Enrimmón, en Soreá, en Yarmut,

[[nehemiah-11-30]]
^30^ en Zanóaj, Adullam y sus caseríos; Lakis y su comarca, Azecá y sus aldeas anejas: se establecieron desde Berseba hasta el valle de Hinnón.

[[nehemiah-11-31]]
^31^ Algunos hijos de Benjamín habitaban en Gueba, Midmás, Ayyá, Betel y sus aldeas anejas,

[[nehemiah-11-32]]
^32^ Anatot, Nob, Ananías,

[[nehemiah-11-33]]
^33^ Jasor, Ramá, Guittayim,

[[nehemiah-11-34]]
^34^ Jadid, Seboím, Neballat,

[[nehemiah-11-35]]
^35^ Lod y Onó, y el valle de los Artesanos.

[[nehemiah-11-36]]
^36^ Había grupos de levitas en Judá y en Benjamín.
[[nehemiah-12]]
== Capítulo 12

[[nehemiah-12-1]]
^1^ Estos son los sacerdotes y los levitas que subieron con Zorobabel, hijo de Sealtiel, y con Josué: Seraías, Jeremías, Esdras,

[[nehemiah-12-2]]
^2^ Amarías, Malluk, Hattús,

[[nehemiah-12-3]]
^3^ Sekanías, Rejum, Meremot,

[[nehemiah-12-4]]
^4^ Iddó, Guinnetón, Abías,

[[nehemiah-12-5]]
^5^ Miyyamín, Maadías, Bilgá,

[[nehemiah-12-6]]
^6^ Semaías; además: Yoyarib, Yedaías,

[[nehemiah-12-7]]
^7^ Sallú, Amoq, Jilquías, Yedaías.

[[nehemiah-12-8]]
^8^ Levitas: Josué, Binnuy, Cadmiel, Serebías, Judá, Mattanías - que dirigía con sus hermanos los himnos de acción de gracias,

[[nehemiah-12-9]]
^9^ y Baqbuquías, Unní y sus hermanos les hacían coro en sus ministerios. (*Nehemías 12:7-b) Estos eran los jefes de los sacerdotes y de sus hermanos, en tiempo de Josué.

[[nehemiah-12-10]]
^10^ Josué engendró a Yoyaquim; Yoyaquim engendró a Elyasib; Elyasib engendró a Yoyadá;

[[nehemiah-12-11]]
^11^ Yoyadá engendró a Yojanán, y Yojanán engendró a Yaddúa.

[[nehemiah-12-12]]
^12^ En los días de Yoyaquim los sacerdotes cabezas de familia eran: de la familia de Seraías: Meraías; de la familia de Jeremías: Jananías;

[[nehemiah-12-13]]
^13^ de la de Esdras: Mesullam; de la de Amarías: Yehojanán;

[[nehemiah-12-14]]
^14^ de la de Malluk: Jonatán; de la de Sekanías: José;

[[nehemiah-12-15]]
^15^ de la de Jarim: Azná; de la de Meremot: Jelcay;

[[nehemiah-12-16]]
^16^ de la de Iddó: Zacarías; de la de Guinnetón: Mesullam;

[[nehemiah-12-17]]
^17^ de la de Abías: Zikrí; de la de Miyyamín:... de la de Maadías: Piltay;

[[nehemiah-12-18]]
^18^ de la de Bilgá: Sammúa; de la de Semaías: Jonatán;

[[nehemiah-12-19]]
^19^ además: de la de Yoyarib: Mattenay; de la Yedaías: Uzzí;

[[nehemiah-12-20]]
^20^ de la de Sallú: Callay; de la de Amoq: Héber;

[[nehemiah-12-21]]
^21^ de la de Jilquías: Jasabías; de la de Yedaías: Natanael.

[[nehemiah-12-22]]
^22^ En tiempo de Elyasib, Yoyadá, Yojanán y Yaddúa, los cabezas de familias sacerdotales fueron registrados en el libro de las Crónicas, hasta el reinado de Darío el persa.

[[nehemiah-12-23]]
^23^ Los hijos de Leví: Los cabezas de familia fueron registrados en el libro de las Crónicas, hasta el tiempo de Yojanán, nieto de Elyasib.

[[nehemiah-12-24]]
^24^ Los jefes de los levitas eran: Jasabías, Serebías, Josué, Binnuy, Cadmiel; y sus hermanos, frente por frente para ejecutar los himnos de alabanza y de acción de gracias, conforme a las instrucciones de David, hombre de Dios, en grupos alternos,

[[nehemiah-12-25]]
^25^ eran: Mattanías, Baqbuquías, y Abdías. Y Mesullam, Talmón y Aqcub, porteros, montaban la guardia en los almacenes junto a las puertas.

[[nehemiah-12-26]]
^26^ Estos vivían en tiempo de Yoyaquim, hijo de Josué, hijo de Yosadaq, y en tiempo de Nehemías, el gobernador, y de Esdras, el sacerdote - escriba.

[[nehemiah-12-27]]
^27^ Cuando la dedicación de la muralla de Jerusalén, se buscó a los levitas por todos los lugares para traerlos a Jerusalén, con el fin de celebrar la dedicación con alegría, con cánticos de acción de gracias y música de címbalos, salterios y cítaras.

[[nehemiah-12-28]]
^28^ Los cantores, hijos de Leví, se congregaron de la región circundante de Jerusalén, de los poblados de los netofatíes,

[[nehemiah-12-29]]
^29^ de Bet Haguilgal, de los campos de Gueba y de Azmávet; porque los cantores habían construido poblados alrededor de Jerusalén.

[[nehemiah-12-30]]
^30^ Sacerdotes y levitas se purificaron, y luego purificaron al pueblo, las puertas y la muralla.

[[nehemiah-12-31]]
^31^ Mandé entonces a los jefes de Judá que subieran a la muralla y organicé dos grandes coros. El primero marchaba por encima de la muralla, hacia la derecha, hacia la puerta del Muladar;

[[nehemiah-12-32]]
^32^ detrás de ellos iban Hosaías y la mitad de los jefes de Judá,

[[nehemiah-12-33]]
^33^ Azarías, Esdras, Mesullam,

[[nehemiah-12-34]]
^34^ Judá, Benjamín, Semaías y Jeremías,

[[nehemiah-12-35]]
^35^ elegidos entre los sacerdotes y provistos de trompetas; y Zacarías, hijo de Jonatán, hijo de Semaías, hijo de Mattanías, hijo de Miká, hijo de Zakkur, hijo de Asaf,

[[nehemiah-12-36]]
^36^ con sus hermanos, Semaías, Azarel, Milalay, Guilalay, Maay, Natanael, Judá, Jananí, con los instrumentos músicos de David, hombre de Dios. Y Esdras el escriba iba al frente de ellos.

[[nehemiah-12-37]]
^37^ A la altura de la puerta de la Fuente, subieron a derecho por la escalera de la Ciudad de David, por encima de la muralla, y por la subida de la Casa de David, hasta la puerta del Agua, al Oriente.

[[nehemiah-12-38]]
^38^ El segundo coro marchaba por la izquierda; yo iba detrás, con la mitad de los jefes del pueblo, por encima de la muralla, pasando por la torre de los Hornos, hasta la muralla de la Plaza,

[[nehemiah-12-39]]
^39^ por encima de la puerta de Efraím, la puerta de los Peces, la torre de Jananel, hasta la puerta de las Ovejas; se hizo alto en la puerta de la Prisión.

[[nehemiah-12-40]]
^40^ Luego los dos corros se colocaron en la Casa de Dios. - Tenía yo a mi lado a la mitad de los consejeros,

[[nehemiah-12-41]]
^41^ y a los sacerdotes Elyaquim, Maaseías, Minyamín, Miká, Elyoenay, Zacarías, Jananías, con trompetas,

[[nehemiah-12-42]]
^42^ y Maaseías, Semaías, Eleazar, Uzzí, Yehojanán, Malkiyías, Elam y Ezer -. Los cantores entonaron su canto bajo la dirección de Yizrajías.

[[nehemiah-12-43]]
^43^ Se ofrecieron aquel día grandes sacrificios y la gente se entregó a la algazara, pues Dios les había concedido un gran gozo; también se regocijaron las mujeres y los niños. Y el alborozo de Jerusalén se oía desde lejos.

[[nehemiah-12-44]]
^44^ En aquel tiempo se puso al frente de los aposentos destinados para almacenes de las ofrendas reservadas, de las primicias y de los diezmos, a hombres que recogiesen en ellos, del territorio de las ciudades, las porciones que la Ley otorga a los sacerdotes y a los levitas. Pues Judá se complacía en ver a los sacerdotes y levitas en sus funciones.

[[nehemiah-12-45]]
^45^ Ellos cumplían el ministerio de su Dios y el ministerio de las purificaciones, junto con los cantores y los porteros, conforme a lo mandado por David y su hijo Salomón.

[[nehemiah-12-46]]
^46^ Pues ya desde un principio, desde los días de David y de Asaf, había jefes de cantores y cánticos de alabanza y acción de gracias a Dios.

[[nehemiah-12-47]]
^47^ Y todo Israel, en tiempo de Zorobabel y en tiempo de Nehemías, daba a los cantores y a los porteros las raciones correspondientes a cada día. A los levitas se les entregaban las cosas sagradas, y los levitas entregaban su parte a los hijos de Aarón.
[[nehemiah-13]]
== Capítulo 13

[[nehemiah-13-1]]
^1^ En aquel tiempo se leyó a oídos del pueblo en el libro de Moisés, y se encontró escrito en él: «El ammonita y el moabita no entrarán jamás en la asamblea de Dios,

[[nehemiah-13-2]]
^2^ porque no recibieron a los israelitas con pan y agua. Tomaron a sueldo contra ellos a Balaam, para maldecirles, pero nuestro Dios cambió la maldición en bendición».

[[nehemiah-13-3]]
^3^ Así que, en oyendo la Ley, se excluyó de Israel a todo extranjero.

[[nehemiah-13-4]]
^4^ Antes de esto, el sacerdote Elyasib había sido encargado de los aposentos de la Casa de nuestro Dios. Como era pariente de Tobías,

[[nehemiah-13-5]]
^5^ le había proporcionado un aposento espacioso, donde anteriormente se depositaban las oblaciones, el incienso, los utensilios, el diezmo del trigo, del vino y del aceite, es decir, las porciones de los levitas, los cantores y los porteros, y lo reservado a los sacerdotes.

[[nehemiah-13-6]]
^6^ Cuando sucedía esto, yo no estaba en Jerusalén, porque el año 32 de Artajerjes, rey de Babilonia, había ido donde el rey; pero al cabo de algún tiempo el rey me permitió volver;

[[nehemiah-13-7]]
^7^ volví a Jerusalén, y me enteré de la mala acción que había hecho Elyasib en favor de Tobías, preparándole un aposento en el atrio de la Casa de Dios.

[[nehemiah-13-8]]
^8^ Esto me desagradó mucho; eché fuera del aposento todos los muebles de la casa de Tobías,

[[nehemiah-13-9]]
^9^ y mandé purificar los aposentos y volver a poner en ellos los utensilios de la Casa de Dios, las oblaciones y el incienso.

[[nehemiah-13-10]]
^10^ Me enteré también de que ya no se entregaban las raciones de los levitas, por lo que ellos se habían marchado cada uno a su campo - los levitas y los cantores encargados del servicio -.

[[nehemiah-13-11]]
^11^ Reprendí por ello a los consejeros diciéndoles: «¿Por qué ha sido abandonada la Casa de Dios?» Luego los reuní de nuevo y los restablecí en sus puestos.

[[nehemiah-13-12]]
^12^ Y todo Judá trajo a los almacenes el diezmo del trigo, del vino y del aceite.

[[nehemiah-13-13]]
^13^ Puse al frente de los almacenes al sacerdote Selemías, al escriba Sadoq y Pedaías, uno de los levitas, y como ayundante, a Janán, hijo de Zakkur, hijo de Mattanías, porque eran considerados como personas fieles; les imcumbía distribuir las porciones a sus hermanos.

[[nehemiah-13-14]]
^14^ ¡Acuérdate de mí por esto, Dios mío; no borres las obras de piedad que yo hice por la Casa de mi Dios y por sus servicios!

[[nehemiah-13-15]]
^15^ Por aquellos días, vi que había en Judá quienes pisaban los lagares en día de sábado; otros acarreaban los haces de trigo y los cargaban sobre los asnos, y también vino, uva, higos y toda clase de cargas, para traerlo a Jerusalén en día de sábado: les advertí que no vendiesen sus mercancías.

[[nehemiah-13-16]]
^16^ En Jerusalén, algunos tirios que habitan en ella traían pescado y toda clase de mercancías para verdérselas a los judíos en día de sábado,

[[nehemiah-13-17]]
^17^ Reprendí a los notables de Judá diciendo: «¡Qué mala acción cometéis profanando el día del sábado!

[[nehemiah-13-18]]
^18^ ¿No fue así como obraron vuestros padres y por lo que nuestro Dios hizo caer toda esta desgracia sobre nosotros y sobre esta ciudad? ¡Y vosotros aumentáis así la Cólera contra Israel profanando el sábado!»

[[nehemiah-13-19]]
^19^ Así que ordené que cuando la sombra cubriese las puertas de Jerusalén, la víspera del sábado se cerrasen las puertas, y que no se abriesen hasta después del sábado. Y puse junto a las puertas a algunos de mis hombres para que no entrase carga alguna en día de sábado.

[[nehemiah-13-20]]
^20^ Una o dos veces, algunos mercaderes que vendían toda clase de mercancías pasaron la noche fuera de Jerusalén,

[[nehemiah-13-21]]
^21^ pero yo les avisé diciéndoles: «¿Por qué pasáis la noche junto a la muralla? ¡Si volvéis a hacerlo, os meteré mano!» Desde entonces no volvían más en sábado.

[[nehemiah-13-22]]
^22^ Ordené también a los levitas purificarse y venir a guardar las puertas, para santificar el sábado. ¡También por esto acuérdate de mí, Dios mío, y ten piedad de mí según tu gran misericordia!

[[nehemiah-13-23]]
^23^ Vi también en aquellos días que algunos judíos se habían casado con mujeres asdoditas, ammonitas o moabitas.

[[nehemiah-13-24]]
^24^ De sus hijos, la mitad hablaban asdodeo o la lengua de uno u otro pueblo, pero no sabían ya hablar judío.

[[nehemiah-13-25]]
^25^ Yo les reprendí y les maldije, hice azotar a algunos de ellos y arrancarles los cabellos, y los conjuré en nombre de Dios: «¡No debéis dar vuestras hijas a sus hijos ni tomar ninguna de sus hijas por mujeres ni para vuestros hijos ni para vosotros mismos!

[[nehemiah-13-26]]
^26^ ¿No pecó en esto Salomón, rey de Israel? Entre tantas naciones no había un rey semejante a él; era amado de su Dios; Dios le había hecho rey de todo Israel. Y también a él le hicieron pecar las mujeres extranjeras.

[[nehemiah-13-27]]
^27^ ¿Se tendrá que oír de vosotros que cometéis el mismo gran crimen de rebelaros contra nuestro Dios casándoos con mujeres extranjeras?»

[[nehemiah-13-28]]
^28^ Uno de los hijos de Yoyadá, hijo del sumo sacerdote Elyasib, era yerno de Samballat el joronita. Yo le eché de mi lado.

[[nehemiah-13-29]]
^29^ ¡Acuérdate de estas gentes, Dios mío, por haber mancillado el sacerdocio y la alianza de los sacerdotes y levitas!

[[nehemiah-13-30]]
^30^ Los purifiqué, pues, de todo lo extranjero. Y establecí, para los sacerdotes y levitas, reglamentos que determinaran la tarea de cada uno,

[[nehemiah-13-31]]
^31^ y lo mismo para las ofrendas de leña a plazos fijos y para las primicias. ¡Acuérdate de mí, Dios mío, para mi bien!
