[[job]]
= Job

[[job-1]]
== Capítulo 1

[[job-1-1]]
^1^ Había una vez en el país de Us un hombre llamado Job: hombre cabal, recto, que temía a Dios y se apartaba del mal.

[[job-1-2]]
^2^ Le habían nacido siete hijos y tres hijas.

[[job-1-3]]
^3^ Tenía también 7.000 ovejas, 3.000 camellos, quinientas yuntas de bueyes, quinientas asnas y una servidumbre muy numerosa. Este hombre era, pues, el más grande de todos los hijos de Oriente.

[[job-1-4]]
^4^ Solían sus hijos celebrar banquetes en casa de cada uno de ellos, por turno, e invitaban también a sus tres hermanas a comer y beber con ellos.

[[job-1-5]]
^5^ Al terminar los días de estos convites, Job les mandaba a llamar para purificarlos; luego se levantaba de madrugada y ofrecía holocaustos por cada uno de ellos. Porque se decía: «Acaso mis hijos hayan pecado y maldecido a Dios en su corazón». Así hacía Job siempre.

[[job-1-6]]
^6^ El día que los Hijos de Dios venían a presentarse ante Yahveh, vino también entre ellos el Satán.

[[job-1-7]]
^7^ Yahveh dijo al Satán: «¿De dónde vienes?» El Satán respondió a Yahveh: «De recorrer la tierra y pasearme por ella».

[[job-1-8]]
^8^ Y Yahveh dijo al Satán: «¿No te has fijado en mi siervo Job? ¡No hay nadie como él en la tierra; es un hombre cabal, recto, que teme a Dios y se aparta del mal!»

[[job-1-9]]
^9^ Respondió el Satán a Yahveh: «Es que Job teme a Dios de balde?

[[job-1-10]]
^10^ ¿No has levantado tú una valla en torno a él, a su casa y a todas sus posesiones? Has bendecido la obra de sus manos y sus rebaños hormiguean por el país.

[[job-1-11]]
^11^ Pero extiende tu mano y toca todos sus bienes; ¡verás si no te maldice a la cara!»

[[job-1-12]]
^12^ Dijo Yahveh al Satán: «Ahí tienes todos sus bienes en tus manos. Cuida sólo de no poner tu mano en él». Y el Satán salió de la presencia de Yahveh.

[[job-1-13]]
^13^ El día en que sus hijos y sus hijas estaban comiendo y bebiendo vino en casa del hermano mayor,

[[job-1-14]]
^14^ vino un mensajero donde Job y le dijo: «Tus bueyes estaban arando y las asnas pastando cerca de ellos;

[[job-1-15]]
^15^ de pronto irrumpieron los sabeos y se los llevaron, y a los criados los pasaron a cuchillo. Sólo yo pude escapar para traerte la noticia».

[[job-1-16]]
^16^ Todavía estaba éste hablando, cuando llegó otro que dijo: «Cayó del cielo el fuego de Dios, que quemó las ovejas y pastores hasta consumirlos. Sólo yo pude escapar para traerte la noticia».

[[job-1-17]]
^17^ Aún estaba hablando éste, cuando llegó otro que dijo: «Los caldeos, divididos en tres cuadrillas, se lanzaron sobre los camellos, se los llevaron, y a los criados los pasaron a cuchillo. Sólo yo pude escapar para traerte la noticia».

[[job-1-18]]
^18^ Todavía estaba éste hablando, cuando llegó otro que dijo: «Tus hijos y tus hijas estaban comiendo y bebiendo en casa del hermano mayor.

[[job-1-19]]
^19^ De pronto sopló un fuerte viento del lado del desierto y sacudió las cuatro esquinas de la casa; y ésta se desplomó sobre los jóvenes, que perecieron. Sólo yo pude escapar para traerte la noticia».

[[job-1-20]]
^20^ Entonces Job se levantó, rasgó su manto, se rapó la cabeza, y postrado en tierra,

[[job-1-21]]
^21^ dijo: «Desnudo salí del seno de mi madre, desnudo allá retornaré. Yahveh dio, Yahveh quitó: ¡Sea bendito el nombre de Yahveh!»

[[job-1-22]]
^22^ En todo esto no pecó Job, ni profirió la menor insensatez contra Dios.
[[job-2]]
== Capítulo 2

[[job-2-1]]
^1^ El día en que los Hijos de Dios venían a presentarse ante Yahveh, vino también entre ellos el Satán.

[[job-2-2]]
^2^ Yahveh dijo al Satán: «¿De dónde vienes?» El Satán respondió a Yahveh: «De recorrer la tierra y pasearme por ella».

[[job-2-3]]
^3^ Y Yahveh dijo al Satán: «¿Te has fijado en mi siervo Job? ¡No hay nadie como él en la tierra: es un hombre cabal, recto, que teme a Dios y se aparta del mal! Aún persevera en su entereza, y bien sin razón me has incitado contra él para perderle».

[[job-2-4]]
^4^ Respondió el Satán a Yahveh: «¡Piel por piel! ¡Todo lo que el hombre posee lo da por su vida!

[[job-2-5]]
^5^ Pero extiende tu mano y toca sus huesos y su carne; ¡verás si no te maldice a la cara!»

[[job-2-6]]
^6^ Y Yahveh dijo al Satán: «Ahí le tienes en tus manos; pero respeta su vida».

[[job-2-7]]
^7^ El Satán salió de la presencia de Yahveh, e hirió a Job con una llaga maligna desde la planta de los pies hasta la coronilla de la cabeza.

[[job-2-8]]
^8^ Job tomó una tejoleta para rascarse, y fue a sentarse entre la basura.

[[job-2-9]]
^9^ Entonces su mujer le dijo: «¿Todavía perseveras en tu entereza? ¡Maldice a Dios y muérete!»

[[job-2-10]]
^10^ Pero él le dijo: «Hablas como una estúpida cualquiera. Si aceptamos de Dios el bien, ¿no aceptaremos el mal?» En todo esto no pecó Job con sus labios.

[[job-2-11]]
^11^ Tres amigos de Job se enteraron de todos estos males que le habían sobrevenido, y vinieron cada uno de su país: Elifaz de Temán, Bildad de Súaj y Sofar de Naamat. Y juntos decidieron ir a condolerse y consolarle.

[[job-2-12]]
^12^ Desde lejos alzaron sus ojos y no le reconocieron. Entonces rompieron a llorar a gritos. Rasgaron sus mantos y se echaron polvo sobre su cabeza.

[[job-2-13]]
^13^ Luego se sentaron en el suelo junto a él, durante siete días y siete noches. Y ninguno le dijo una palabra, porque veían que el dolor era muy grande.
[[job-3]]
== Capítulo 3

[[job-3-1]]
^1^ Después de esto, abrió Job la boca y maldijo su día.

[[job-3-2]]
^2^ Tomó Job la palabra y dijo:

[[job-3-3]]
^3^ ¡Perezca el día en que nací,

[[job-3-4]]
^4^ El día aquel hágase tinieblas,

[[job-3-5]]
^5^ Lo reclamen tinieblas y sombras,

[[job-3-6]]
^6^ Sí, la oscuridad de él se apodere,

[[job-3-7]]
^7^ Y aquella noche hágase inerte,

[[job-3-8]]
^8^ Maldíganla los que maldicen el día,

[[job-3-9]]
^9^ Sean tinieblas las estrellas de su aurora,

[[job-3-10]]
^10^ Porque no me cerró las puertas del vientre donde estaba,

[[job-3-11]]
^11^ ¿Por qué no morí cuando salí del seno,

[[job-3-12]]
^12^ ¿Por qué me acogieron dos rodillas?

[[job-3-13]]
^13^ Pues ahora descansaría tranquilo,

[[job-3-14]]
^14^ con los reyes y los notables de la tierra,

[[job-3-15]]
^15^ o con los príncipes que poseen oro

[[job-3-16]]
^16^ O ni habría existido, como aborto ocultado,

[[job-3-17]]
^17^ Allí acaba la agitación de los malvados,

[[job-3-18]]
^18^ También están tranquilos los cautivos,

[[job-3-19]]
^19^ Chicos y grandes son allí lo mismo,

[[job-3-20]]
^20^ ¿Para qué dar la luz a un desdichado,

[[job-3-21]]
^21^ a los que ansían la muerte que no llega

[[job-3-22]]
^22^ a los que se alegran ante el túmulo

[[job-3-23]]
^23^ a un hombre que ve cerrado su camino,

[[job-3-24]]
^24^ Como alimento viene mi suspiro,

[[job-3-25]]
^25^ Porque si de algo tengo miedo, me acaece,

[[job-3-26]]
^26^ No hay para mí tranquilidad ni calma,
[[job-4]]
== Capítulo 4

[[job-4-1]]
^1^ Elifaz de Temán tomó la palabra y dijo:

[[job-4-2]]
^2^ Si se intentara hablarte, ¿lo soportarías?

[[job-4-3]]
^3^ Mira, tú dabas lección a mucha gente,

[[job-4-4]]
^4^ tus razones sostenían al que vacilaba,

[[job-4-5]]
^5^ Y ahora que otro tanto te toca, te deprimes,

[[job-4-6]]
^6^ ¿No es tu confianza la piedad,

[[job-4-7]]
^7^ ¡Recuerda! ¿Qué inocente jamás ha perecido?

[[job-4-8]]
^8^ Así lo he visto: los que labran maldad

[[job-4-9]]
^9^ Bajo el aliento de Dios perecen éstos,

[[job-4-10]]
^10^ Ruge el león, brama la leona,

[[job-4-11]]
^11^ Perece el león falto de presa,

[[job-4-12]]
^12^ A mí se me ha dicho furtivamente una palabra,

[[job-4-13]]
^13^ En las pesadillas por las visiones de la noche,

[[job-4-14]]
^14^ un temblor me entró, un escalofrío,

[[job-4-15]]
^15^ Se escurre un soplo por mi rostro,

[[job-4-16]]
^16^ Alguien surge... no puedo reconocer su cara;

[[job-4-17]]
^17^ «¿Es justo ante Dios algún mortal?

[[job-4-18]]
^18^ Si no se fía de sus mismos servidores,

[[job-4-19]]
^19^ ¡cuánto más a los que habitan estas casas de arcilla,

[[job-4-20]]
^20^ de la noche a la mañana quedan pulverizados.

[[job-4-21]]
^21^ se les arranca la cuerda de su tienda,
[[job-5]]
== Capítulo 5

[[job-5-1]]
^1^ ¡Llama, pues! ¿Habrá quien te responda?

[[job-5-2]]
^2^ En verdad el enojo mata al insensato,

[[job-5-3]]
^3^ Yo mismo he visto al insensato echar raíces,

[[job-5-4]]
^4^ ¡Estén sus hijos lejos de toda salvación,

[[job-5-5]]
^5^ Su cosecha la devora un hambriento,

[[job-5-6]]
^6^ No, no brota la iniquidad el polvo,

[[job-5-7]]
^7^ Es el hombre quien la aflicción engendra,

[[job-5-8]]
^8^ Yo por mí a Dios recurriría,

[[job-5-9]]
^9^ El es autor de obras grandiosas e insondables,

[[job-5-10]]
^10^ El derrama la lluvia sobre la haz de la tierra,

[[job-5-11]]
^11^ Para poner en alto a los postrados,

[[job-5-12]]
^12^ las tramas de los astutos desbarata,

[[job-5-13]]
^13^ Prende a los sabios en su astucia,

[[job-5-14]]
^14^ En pleno día tropiezan con tinieblas,

[[job-5-15]]
^15^ El salva al arruinado de sus fauces

[[job-5-16]]
^16^ Así el débil renace a la esperanza,

[[job-5-17]]
^17^ ¡Oh sí, feliz el hombre a quien corrige Dios!

[[job-5-18]]
^18^ Pues él es el que hiere y el que venda la herida,

[[job-5-19]]
^19^ seis veces ha de librarte de la angustia,

[[job-5-20]]
^20^ Durante el hambre te salvará de la muerte,

[[job-5-21]]
^21^ Estarás a cubierto del punzón de la lengua,

[[job-5-22]]
^22^ Te reirás de la sequía y de la helada,

[[job-5-23]]
^23^ Pues con las piedras del campo harás alianza,

[[job-5-24]]
^24^ Sabrás que tu tienda está a cubierto,

[[job-5-25]]
^25^ Sabrás que tu descendencia es numerosa,

[[job-5-26]]
^26^ Llegarás a la tumba vigoroso,

[[job-5-27]]
^27^ Todo esto es lo que hemos observado: y así es.
[[job-6]]
== Capítulo 6

[[job-6-1]]
^1^ Job tomó la palabra y dijo:

[[job-6-2]]
^2^ ¡Ah, si pudiera pesarse mi aflicción,

[[job-6-3]]
^3^ esarían más que la arena de los mares:

[[job-6-4]]
^4^ Pues las flechas de Sadday están en mí,

[[job-6-5]]
^5^ ¿Rozna el onagro junto a la hierba verde?

[[job-6-6]]
^6^ ¿Se come acaso lo insípido sin sal?

[[job-6-7]]
^7^ Lo que aun tocar me repugnaba

[[job-6-8]]
^8^ ¡Ojalá se realizara lo que pido,

[[job-6-9]]
^9^ que él consintiera en aplastarme,

[[job-6-10]]
^10^ Tendría siquiera este consuelo,

[[job-6-11]]
^11^ ¿Cuál es mi fuerza para que aún espere,

[[job-6-12]]
^12^ ¿Es mi fuerza la fuerza de la roca?

[[job-6-13]]
^13^ ¿No está mi apoyo en una nada?

[[job-6-14]]
^14^ El que retira la compasión al prójimo

[[job-6-15]]
^15^ Me han defraudado mis hermanos lo mismo que un torrente,

[[job-6-16]]
^16^ turbios van de aguas de hielo,

[[job-6-17]]
^17^ pero en tiempo de estiaje se evaporan,

[[job-6-18]]
^18^ Por ellos las caravanas se apartan de su ruta,

[[job-6-19]]
^19^ Las caravanas de Temá los otean,

[[job-6-20]]
^20^ Pero se ve corrida su confianza;

[[job-6-21]]
^21^ Así sois ahora vosotros para mí:

[[job-6-22]]
^22^ ¿He dicho acaso: «Dadme algo,

[[job-6-23]]
^23^ arrancadme de la mano de un rival,

[[job-6-24]]
^24^ Instruidme, que yo me callaré;

[[job-6-25]]
^25^ ¡Qué dulces son las razones ecuánimes!,

[[job-6-26]]
^26^ ¿Intentáis criticar sólo palabras,

[[job-6-27]]
^27^ ¡Vosotros echáis a suerte al mismo huérfano,

[[job-6-28]]
^28^ Y ahora, por favor, volveos a mí,

[[job-6-29]]
^29^ ¡Tornad, pues, que no haya entuerto!

[[job-6-30]]
^30^ ¿Hay entuerto en mis labios?
[[job-7]]
== Capítulo 7

[[job-7-1]]
^1^ ¿No es una milicia lo que hace el hombre en la tierra?

[[job-7-2]]
^2^ Como esclavo que suspira por la sombra,

[[job-7-3]]
^3^ así meses de desencanto son mi herencia,

[[job-7-4]]
^4^ Al acostarme, digo: «¿Cuándo llegará el día?»

[[job-7-5]]
^5^ Mi carne está cubierta de gusanos y de costras terrosas,

[[job-7-6]]
^6^ Mis días han sido más raudos que la lanzadera,

[[job-7-7]]
^7^ Recuerda que mi vida es un soplo,

[[job-7-8]]
^8^ El ojo que me miraba ya no me verá,

[[job-7-9]]
^9^ Una nube se disipa y pasa,

[[job-7-10]]
^10^ No regresa otra vez a su casa,

[[job-7-11]]
^11^ Por eso yo no he de contener mi boca,

[[job-7-12]]
^12^ ¿Acaso soy yo el Mar, soy el monstruo marino,

[[job-7-13]]
^13^ Si digo: «Mi cama me consolará,

[[job-7-14]]
^14^ con sueños entonces tú me espantas,

[[job-7-15]]
^15^ ¡Preferiría mi alma el estrangulamiento,

[[job-7-16]]
^16^ Ya me disuelvo, no he de vivir por siempre;

[[job-7-17]]
^17^ ¿Qué es el hombre para que tanto de él te ocupes,

[[job-7-18]]
^18^ para que le escrutes todas las mañanas

[[job-7-19]]
^19^ ¿Cuándo retirarás tu mirada de mí?

[[job-7-20]]
^20^ Si he pecado, ¿qué te he hecho a ti,

[[job-7-21]]
^21^ ¿Y por qué no toleras mi delito
[[job-8]]
== Capítulo 8

[[job-8-1]]
^1^ Bildad de Súaj tomó la palabra y dijo:

[[job-8-2]]
^2^ ¿Hasta cuándo estarás hablando de ese modo,

[[job-8-3]]
^3^ ¿Acaso Dios tuerce el derecho,

[[job-8-4]]
^4^ Si tus hijos pecaron contra él,

[[job-8-5]]
^5^ Mas si tú a Dios recurres

[[job-8-6]]
^6^ si eres irreprochable y recto,

[[job-8-7]]
^7^ Tu pasado parecerá insignificante

[[job-8-8]]
^8^ Pregunta, si no, a la generación pasada,

[[job-8-9]]
^9^ Nosotros de ayer somos y no sabemos nada,

[[job-8-10]]
^10^ Pero ellos te instruirán y te hablarán,

[[job-8-11]]
^11^ «¿Brota acaso el papiro sin marismas?

[[job-8-12]]
^12^ Aún en su verdor, sin ser cortado,

[[job-8-13]]
^13^ Tal es el fin de los que a Dios olvidan,

[[job-8-14]]
^14^ Su confianza es un hilo solamente,

[[job-8-15]]
^15^ Se apoya en su morada, y no le aguanta,

[[job-8-16]]
^16^ Bien regado ante la faz del sol,

[[job-8-17]]
^17^ Sobre un majano entrelazadas sus raíces,

[[job-8-18]]
^18^ Mas cuando se le arranca de su sitio,

[[job-8-19]]
^19^ Y vedle ya cómo se pudre en el camino,

[[job-8-20]]
^20^ No, Dios no rechaza al íntegro,

[[job-8-21]]
^21^ La risa ha de llenar aún tu boca

[[job-8-22]]
^22^ Tus enemigos serán cubiertos de vergüenza,
[[job-9]]
== Capítulo 9

[[job-9-1]]
^1^ Job tomó la palabra y dijo:

[[job-9-2]]
^2^ Bien sé yo, en verdad, que es así:

[[job-9-3]]
^3^ A quien pretenda litigar con él,

[[job-9-4]]
^4^ Entre los más sabios, entre los más fuertes,

[[job-9-5]]
^5^ El traslada los montes sin que se den cuenta,

[[job-9-6]]
^6^ El sacude la tierra de su sitio,

[[job-9-7]]
^7^ A su veto el sol no se levanta,

[[job-9-8]]
^8^ El solo desplegó los Cielos,

[[job-9-9]]
^9^ El hizo la Osa y Orión,

[[job-9-10]]
^10^ Es autor de obras grandiosas, insondables,

[[job-9-11]]
^11^ Si pasa junto a mí, yo no le veo,

[[job-9-12]]
^12^ Si en algo hace presa, ¿quién le estorbará?

[[job-9-13]]
^13^ Dios no cede en su cólera:

[[job-9-14]]
^14^ ¡Cuánto menos podré yo defenderme

[[job-9-15]]
^15^ Aunque tuviera razón, no hallaría respuesta,

[[job-9-16]]
^16^ Y aunque le llame y me responda,

[[job-9-17]]
^17^ ¡El, que me aplasta por un pelo,

[[job-9-18]]
^18^ y ni aliento recobrar me deja,

[[job-9-19]]
^19^ Si se trata de fuerza, ¡es él el Poderoso!

[[job-9-20]]
^20^ Si me creo justo, su boca me condena,

[[job-9-21]]
^21^ ¿Soy intachable? ¡Ni yo mismo me conozco,

[[job-9-22]]
^22^ Pero todo da igual, y por eso digo:

[[job-9-23]]
^23^ Si un azote acarrea la muerte de improviso,

[[job-9-24]]
^24^ En un país sujeto al poder de un malvado,

[[job-9-25]]
^25^ Mis días han sido más raudos que un correo,

[[job-9-26]]
^26^ Se han deslizado lo mismo que canoas de junco,

[[job-9-27]]
^27^ Si digo: «Voy a olvidar mis quejas,

[[job-9-28]]
^28^ me asalta el temor de todos mis pesares,

[[job-9-29]]
^29^ Y si me he hecho culpable,

[[job-9-30]]
^30^ Aunque me lave con jabón,

[[job-9-31]]
^31^ tú me hundes en el lodo,

[[job-9-32]]
^32^ Que él no es un hombre como yo, para que le responda,

[[job-9-33]]
^33^ No hay entre nosotros árbitro

[[job-9-34]]
^34^ y que de mí su vara aparte

[[job-9-35]]
^35^ Pero hablaré sin temerle,
[[job-10]]
== Capítulo 10

[[job-10-1]]
^1^ Asco tiene mi alma de mi vida:

[[job-10-2]]
^2^ Diré a Dios: ¡No me condenes,

[[job-10-3]]
^3^ ¿Acaso te está bien mostrarte duro,

[[job-10-4]]
^4^ ¿Tienes tú ojos de carne?

[[job-10-5]]
^5^ ¿Son tus días como los de un mortal?

[[job-10-6]]
^6^ ¡para que andes rebuscando mi falta,

[[job-10-7]]
^7^ aunque sabes muy bien que yo no soy culpable,

[[job-10-8]]
^8^ Tus manos me formaron, me plasmaron,

[[job-10-9]]
^9^ Recuerda que me hiciste como se amasa el barro,

[[job-10-10]]
^10^ ¿No me vertiste como leche

[[job-10-11]]
^11^ De piel y de carne me vestiste

[[job-10-12]]
^12^ Luego con la vida me agraciaste

[[job-10-13]]
^13^ Y algo más todavía guardabas en tu corazón,

[[job-10-14]]
^14^ el vigilarme por si peco.

[[job-10-15]]
^15^ Si soy culpable, ¡desgraciado de mí!

[[job-10-16]]
^16^ Y si la levanto, como un león me das caza,

[[job-10-17]]
^17^ Contra mí tu hostilidad renuevas,

[[job-10-18]]
^18^ ¿Para qué me sacaste del seno?

[[job-10-19]]
^19^ sería como si no hubiera existido,

[[job-10-20]]
^20^ ¿No son bien poco los días de mi existencia?

[[job-10-21]]
^21^ antes que me vaya, para ya no volver,

[[job-10-22]]
^22^ tierra de oscuridad y de desorden,
[[job-11]]
== Capítulo 11

[[job-11-1]]
^1^ Sofar de Naamat tomó la palabra y dijo:

[[job-11-2]]
^2^ ¿No habrá respuesta para el charlatán?

[[job-11-3]]
^3^ ¿Tu palabrería hará callar a los demás?

[[job-11-4]]
^4^ Tú has dicho: «Es pura mi conducta,

[[job-11-5]]
^5^ ¡Ojalá Dios hablara,

[[job-11-6]]
^6^ y te revelara los arcanos de la Sabiduría

[[job-11-7]]
^7^ ¿Pretendes alcanzar las honduras de Dios,

[[job-11-8]]
^8^ Más alta es que los cielos: ¿qué harás tú?

[[job-11-9]]
^9^ Más larga que la tierra su amplitud,

[[job-11-10]]
^10^ Si él interviene, encarcela y cita a juicio,

[[job-11-11]]
^11^ Porque él conoce a los hombres de engaño,

[[job-11-12]]
^12^ El insensato se hará cuerdo

[[job-11-13]]
^13^ Pero si tú tu corazón arreglas

[[job-11-14]]
^14^ si alejas la iniquidad que hay en tu mano

[[job-11-15]]
^15^ entonces alzarás tu frente limpia,

[[job-11-16]]
^16^ Dejarás tu infortunio en el olvido

[[job-11-17]]
^17^ Y más radiante que el mediodía surgirá tu existencia,

[[job-11-18]]
^18^ Vivirás seguro porque habrá esperanza,

[[job-11-19]]
^19^ Cuando descanses, nadie te turbará,

[[job-11-20]]
^20^ Mas los ojos de los malvados languidecen,
[[job-12]]
== Capítulo 12

[[job-12-1]]
^1^ Job tomó la palabra y dijo:

[[job-12-2]]
^2^ En verdad, vosotros sois el pueblo,

[[job-12-3]]
^3^ Yo también sé pensar como vosotros,

[[job-12-4]]
^4^ La irrisión de su amigo, eso soy yo,

[[job-12-5]]
^5^ «¡Al infortunio, el desprecio! - opinan los dichosos -;

[[job-12-6]]
^6^ Mientras viven en paz las tiendas de los salteadores,

[[job-12-7]]
^7^ Pero interroga a las bestias, que te instruyan,

[[job-12-8]]
^8^ Te instruirán los reptiles de la tierra,

[[job-12-9]]
^9^ Pues entre todos ellos, ¿quién ignora

[[job-12-10]]
^10^ El, que tiene en su mano el alma de todo ser viviente

[[job-12-11]]
^11^ ¿No es el oído el que aprecia los discursos,

[[job-12-12]]
^12^ ¿No está entre los ancianos el saber,

[[job-12-13]]
^13^ Pero con él sabiduría y poder,

[[job-12-14]]
^14^ Si él destruye, no se puede edificar;

[[job-12-15]]
^15^ Si retiene las aguas, sobreviene sequía,

[[job-12-16]]
^16^ Con él la fuerza y la agudeza;

[[job-12-17]]
^17^ A los consejeros hace él andar descalzos,

[[job-12-18]]
^18^ Desata la banda de los reyes

[[job-12-19]]
^19^ Hace andar descalzos a los sacerdotes

[[job-12-20]]
^20^ Quita el habla a los más hábiles

[[job-12-21]]
^21^ Sobre los nobles vierte el menosprecio

[[job-12-22]]
^22^ Revela la profundidad de las tinieblas,

[[job-12-23]]
^23^ Levanta a las naciones y luego las destruye,

[[job-12-24]]
^24^ Quitá el ánimo a los jefes del país,

[[job-12-25]]
^25^ y andan a tientas en tinieblas, sin luz,
[[job-13]]
== Capítulo 13

[[job-13-1]]
^1^ ¡Oh!, mis ojos han visto todo esto,

[[job-13-2]]
^2^ Sí, yo lo sé tan bien como vosotros,

[[job-13-3]]
^3^ Pero es a Sadday a quien yo hablo,

[[job-13-4]]
^4^ Vosotros no sois más que charlatanes,

[[job-13-5]]
^5^ ¡Oh, si os callarais la boca!

[[job-13-6]]
^6^ Oíd mis descargos, os lo ruego,

[[job-13-7]]
^7^ ¿En defensa de Dios decís falsía,

[[job-13-8]]
^8^ ¿Así lucháis en su favor

[[job-13-9]]
^9^ ¿No convendría que él os sondease?

[[job-13-10]]
^10^ El os dará una severa corrección,

[[job-13-11]]
^11^ ¿Su majestad no os sobrecoge,

[[job-13-12]]
^12^ Máximas de ceniza son vuestras sentencias,

[[job-13-13]]
^13^ ¡Dejad de hablarme, porque voy a hablar yo,

[[job-13-14]]
^14^ Tomo mi carne entre mis dientes,

[[job-13-15]]
^15^ El me puede matar: no tengo otra esperanza

[[job-13-16]]
^16^ Y esto mismo será mi salvación,

[[job-13-17]]
^17^ Escuchad, escuchad mis palabras,

[[job-13-18]]
^18^ Mirad: un proceso he preparado,

[[job-13-19]]
^19^ ¿Quién es el que quiere litigar conmigo?

[[job-13-20]]
^20^ Sólo dos cosas te pido que me ahorres,

[[job-13-21]]
^21^ que retires tu mano que pesa sobre mí,

[[job-13-22]]
^22^ Arguye tú y yo responderé;

[[job-13-23]]
^23^ ¿Cuántas son mis faltas y pecados?

[[job-13-24]]
^24^ ¿Por qué tu rostro ocultas

[[job-13-25]]
^25^ ¿Quieres asustar a una hoja que se lleva el viento,

[[job-13-26]]
^26^ Pues escribes contra mí amargos fallos,

[[job-13-27]]
^27^ pones mis pies en cepos,

[[job-13-28]]
^28^ Y él se deshace cual leño carcomido,
[[job-14]]
== Capítulo 14

[[job-14-1]]
^1^ el hombre, nacido de mujer,

[[job-14-2]]
^2^ Como la flor, brota y se marchita,

[[job-14-3]]
^3^ ¡Y sobre un ser tal abres tú los ojos,

[[job-14-4]]
^4^ Mas ¿quién podrá sacar lo puro de lo impuro?

[[job-14-5]]
^5^ Si es que están contados ya sus días,

[[job-14-6]]
^6^ aparta de él tus ojos, déjale,

[[job-14-7]]
^7^ Una esperanza guarda el árbol:

[[job-14-8]]
^8^ Incluso con raíces en tierra envejecidas,

[[job-14-9]]
^9^ en cuanto siente el agua, reflorece

[[job-14-10]]
^10^ Pero el hombre que muere queda inerte,

[[job-14-11]]
^11^ Podrán agotarse las aguas del mar,

[[job-14-12]]
^12^ que el hombre que yace no se levantará,

[[job-14-13]]
^13^ ¡Ojalá en el seol tú me guardaras,

[[job-14-14]]
^14^ - pues, muerto el hombre, ¿puede revivir? -

[[job-14-15]]
^15^ Me llamarías y te repondería;

[[job-14-16]]
^16^ En lugar de contar mi pasos, como ahora,

[[job-14-17]]
^17^ dentro de un saco se sellaría mi delito,

[[job-14-18]]
^18^ Ay, como el monte acabará por derrumbarse,

[[job-14-19]]
^19^ las aguas desgastarán las piedras,

[[job-14-20]]
^20^ Le aplastas para siempre, y se va,

[[job-14-21]]
^21^ Que sean honrados sus hijos, no lo sabe;

[[job-14-22]]
^22^ Tan solo por él sufre su carne,
[[job-15]]
== Capítulo 15

[[job-15-1]]
^1^ Elifaz de Temán tomó la palabra y dijo:

[[job-15-2]]
^2^ ¿Responde un sabio con una ciencia de aire,

[[job-15-3]]
^3^ replicando con palabras vacías,

[[job-15-4]]
^4^ ¡Tú llegas incluso a destruir la piedad,

[[job-15-5]]
^5^ Ya que tu culpa inspira tus palabras,

[[job-15-6]]
^6^ tu propia boca te condena, que no yo,

[[job-15-7]]
^7^ ¿Has nacido tú el primero de los hombres?

[[job-15-8]]
^8^ ¿Escuchas acaso los secretos de Dios?

[[job-15-9]]
^9^ ¿Qué sabes tú, que nosotros no sepamos?

[[job-15-10]]
^10^ ¡También entre nosotros hay un cano, un anciano,

[[job-15-11]]
^11^ ¿Te parecen poco los consuelos divinos,

[[job-15-12]]
^12^ ¡Cómo te arrebata el corazón,

[[job-15-13]]
^13^ cuando revuelves contra Dios tu furia

[[job-15-14]]
^14^ ¿Cómo puede ser puro un hombre?

[[job-15-15]]
^15^ Si ni en sus santos tiene Dios confianza,

[[job-15-16]]
^16^ ¡cuánto menos un ser abominable y corrompido,

[[job-15-17]]
^17^ Voy a instruirte, escúchame,

[[job-15-18]]
^18^ lo que transmiten los sabios,

[[job-15-19]]
^19^ - a ellos solos les fue dada la tierra,

[[job-15-20]]
^20^ «Todos sus días vive el malvado en tormento,

[[job-15-21]]
^21^ Grito de espanto resuena en sus oídos,

[[job-15-22]]
^22^ No espera escapar a las tinieblas,

[[job-15-23]]
^23^ Asignado como pasto de los buitres,

[[job-15-24]]
^24^ le espanta,

[[job-15-25]]
^25^ ¡Alzaba él su mano contra Dios,

[[job-15-26]]
^26^ Embestía contra él, el cuello tenso,

[[job-15-27]]
^27^ porque tenía el rostro cubierto de grasa,

[[job-15-28]]
^28^ y habitaba ciudades destruidas,

[[job-15-29]]
^29^ No se enriquecerá, no será estable su fortuna,

[[job-15-30]]
^30^ (ni escapará a las tinieblas).

[[job-15-31]]
^31^ No se fíe de su elevada talla,

[[job-15-32]]
^32^ Se amustiará antes de tiempo,

[[job-15-33]]
^33^ Sacudirá como la viña sus agraces,

[[job-15-34]]
^34^ Sí, es estéril la ralea del impío,

[[job-15-35]]
^35^ Quien concibe dolor, desgracia engendra,
[[job-16]]
== Capítulo 16

[[job-16-1]]
^1^ Job tomó la palabra y dijo:

[[job-16-2]]
^2^ ¡He oído muchas cosas como ésas!

[[job-16-3]]
^3^ «¿No acabarán esas palabras de aire?»

[[job-16-4]]
^4^ También yo podría hablar como vosotros,

[[job-16-5]]
^5^ os confortaría con mi boca,

[[job-16-6]]
^6^ Mas si hablo, no cede mi dolor,

[[job-16-7]]
^7^ Ahora me tiene ya extenuado;

[[job-16-8]]
^8^ que me acorrala;

[[job-16-9]]
^9^ su furia me desgarra y me persigue,

[[job-16-10]]
^10^ abren su boca contra mí.

[[job-16-11]]
^11^ A injustos Dios me entrega,

[[job-16-12]]
^12^ Estaba yo tranquilo cuando él me golpeó,

[[job-16-13]]
^13^ me cerca con sus tiros,

[[job-16-14]]
^14^ Abre en mí brecha sobre brecha,

[[job-16-15]]
^15^ Yo he cosido un sayal sobre mi piel,

[[job-16-16]]
^16^ Mi rostro ha enrojecido por el llanto,

[[job-16-17]]
^17^ Y eso que no hay en mis manos violencia, y mi oración es pura.

[[job-16-18]]
^18^ ¡Tierra, no cubras tú mi sangre,

[[job-16-19]]
^19^ Ahora todavía está en los cielos mi testigo,

[[job-16-20]]
^20^ que interpreta ante Dios mis pensamientos;

[[job-16-21]]
^21^ ¡Oh, si él juzgara entre un hombre y Dios,

[[job-16-22]]
^22^ Pues mis años futuros son contados,
[[job-17]]
== Capítulo 17

[[job-17-1]]
^1^ Mi aliento se agota, mis días se apagan

[[job-17-2]]
^2^ ¿No estoy a merced de las burlas,

[[job-17-3]]
^3^ Coloca, pues, mi fianza junto a ti,

[[job-17-4]]
^4^ Tú has cerrado su mente a la razón,

[[job-17-5]]
^5^ Como el que anuncia a sus amigos un reparto,

[[job-17-6]]
^6^ me he hecho yo proverbio de las gentes,

[[job-17-7]]
^7^ Mis ojos se apagan de pesar,

[[job-17-8]]
^8^ Los hombres rectos quedan de ello asombrados,

[[job-17-9]]
^9^ el justo se afianza en su camino,

[[job-17-10]]
^10^ Pero, vosotros todos, volved otra vez,

[[job-17-11]]
^11^ Mis días han pasado con mis planes,

[[job-17-12]]
^12^ Algunos hacen de la noche día:

[[job-17-13]]
^13^ Mas ¿qué espero? Mi casa es el seol,

[[job-17-14]]
^14^ Y grito a la fosa: «¡Tú mi padre!»,

[[job-17-15]]
^15^ ¿Dónde está, pues, mi esperanza?

[[job-17-16]]
^16^ ¿Van a bajar conmigo hasta el seol?
[[job-18]]
== Capítulo 18

[[job-18-1]]
^1^ Bildad de Súaj tomó la palabra y dijo:

[[job-18-2]]
^2^ ¿Cuándo pondréis freno a las palabras?

[[job-18-3]]
^3^ ¿Por qué hemos de ser tenidos como bestias,

[[job-18-4]]
^4^ Oh tú, que te desgarras en tu cólera,

[[job-18-5]]
^5^ Sí, la luz del malvado ha de apagarse,

[[job-18-6]]
^6^ La luz en su tienda se oscurece,

[[job-18-7]]
^7^ Se acortan sus pasos vigorosos,

[[job-18-8]]
^8^ Porque sus pies le meten en la red,

[[job-18-9]]
^9^ Por el talón le apresa un lazo,

[[job-18-10]]
^10^ Oculto en la tierra hay un nudo para él,

[[job-18-11]]
^11^ Por todas partes le estremecen terrores,

[[job-18-12]]
^12^ El hambre es su cortejo,

[[job-18-13]]
^13^ Devora el mal su piel,

[[job-18-14]]
^14^ Se le arranca del seguro de su tienda,

[[job-18-15]]
^15^ Se ocupa su tienda, ya no suya,

[[job-18-16]]
^16^ Por abajo se secan sus raíces,

[[job-18-17]]
^17^ Su recuerdo desaparece de la tierra,

[[job-18-18]]
^18^ Se le arroja de la luz a las tinieblas,

[[job-18-19]]
^19^ Ni prole ni posteridad tiene en su pueblo,

[[job-18-20]]
^20^ De su fin se estremece el Occidente,

[[job-18-21]]
^21^ Tan sólo esto son las moradas del impío,
[[job-19]]
== Capítulo 19

[[job-19-1]]
^1^ Job tomó la palabra y dijo:

[[job-19-2]]
^2^ ¿Hasta cuándo afligiréis mi alma

[[job-19-3]]
^3^ Ya me habéis insultado por diez veces,

[[job-19-4]]
^4^ Aunque de hecho hubiese errado,

[[job-19-5]]
^5^ Si es que aún queréis triunfar de mí

[[job-19-6]]
^6^ sabed ya que es Dios quien me hace entuerto,

[[job-19-7]]
^7^ Si grito: ¡Violencia!, no obtengo respuesta;

[[job-19-8]]
^8^ El ha vallado mi ruta para que yo no pase,

[[job-19-9]]
^9^ Me ha despojado de mi gloria,

[[job-19-10]]
^10^ Por todas partes me mina y desaparezco,

[[job-19-11]]
^11^ Enciende su ira contra mí,

[[job-19-12]]
^12^ En masa sus huestes han llegado,

[[job-19-13]]
^13^ A mis hermanos ha alejado de mí,

[[job-19-14]]
^14^ Parientes y deudos ya no tengo,

[[job-19-15]]
^15^ Por un extraño me tienen mis criadas,

[[job-19-16]]
^16^ Llamo a mi criado y no responde,

[[job-19-17]]
^17^ Mi aliento repele a mi mujer,

[[job-19-18]]
^18^ Hasta los chiquillos me desprecian,

[[job-19-19]]
^19^ Tienen horror de mí todos mis íntimos,

[[job-19-20]]
^20^ Bajo mi piel mi carne cae podrida,

[[job-19-21]]
^21^ ¡Piedad, piedad de mí, vosotros mis amigos,

[[job-19-22]]
^22^ ¿Por qué os cebáis en mí como hace Dios,

[[job-19-23]]
^23^ ¡Ojalá se escribieran mis palabras,

[[job-19-24]]
^24^ y con punzón de hierro y buril,

[[job-19-25]]
^25^ Yo sé que mi Defensor está vivo,

[[job-19-26]]
^26^ Tras mi despertar me alzará junto a él,

[[job-19-27]]
^27^ Yo, sí, yo mismo le veré,

[[job-19-28]]
^28^ Y si vosotros decís: «¿Cómo atraparle,

[[job-19-29]]
^29^ temed la espada por vosotros mismos,
[[job-20]]
== Capítulo 20

[[job-20-1]]
^1^ Sofar de Naamat tomó la palabra y dijo:

[[job-20-2]]
^2^ Por esto mis pensamientos a replicar me incitan:

[[job-20-3]]
^3^ Una lección que me ultraja he escuchado,

[[job-20-4]]
^4^ ¿No sabes tú que desde siempre,

[[job-20-5]]
^5^ es breve la alegría del malvado,

[[job-20-6]]
^6^ Aunque su talla se alzara hasta los cielos

[[job-20-7]]
^7^ como un fantasma desaparece para siempre,

[[job-20-8]]
^8^ Se vuela como un sueño inaprensible,

[[job-20-9]]
^9^ El ojo que le observaba ya no le ve más,

[[job-20-10]]
^10^ A los pobres tendrán que indemnizar sus hijos,

[[job-20-11]]
^11^ Sus huesos rebosaban de vigor juvenil:

[[job-20-12]]
^12^ Si el mal era dulce a su boca,

[[job-20-13]]
^13^ si allí lo guardaba tenazmente

[[job-20-14]]
^14^ su alimento en sus entrañas se corrompe,

[[job-20-15]]
^15^ Vomita las riquezas que engulló,

[[job-20-16]]
^16^ Veneno de áspides chupaba:

[[job-20-17]]
^17^ Ya no verá los arroyos de aceite,

[[job-20-18]]
^18^ Devuelve su ganancia sin tragarla,

[[job-20-19]]
^19^ Porque estrujó las chozas de los pobres,

[[job-20-20]]
^20^ porque su vientre se mostró insaciable,

[[job-20-21]]
^21^ porque a su voracidad nada escapaba,

[[job-20-22]]
^22^ En plena abundancia la estrechez le sorprende,

[[job-20-23]]
^23^ En el momento de llenar su vientre,

[[job-20-24]]
^24^ Si del arma de hierro logra huir,

[[job-20-25]]
^25^ Sale una flecha por su espalda,

[[job-20-26]]
^26^ total tiniebla aguarda a sus tesoros.

[[job-20-27]]
^27^ Los cielos ponen su culpa al descubierto,

[[job-20-28]]
^28^ La hacienda de su casa se derrama,

[[job-20-29]]
^29^ Tal es la suerte que al malvado Dios reserva,
[[job-21]]
== Capítulo 21

[[job-21-1]]
^1^ Job tomó la palabra y dijo:

[[job-21-2]]
^2^ Escuchad, escuchad mis razones,

[[job-21-3]]
^3^ Tened paciencia mientras hablo yo,

[[job-21-4]]
^4^ ¿Acaso me quejo yo de un hombre?

[[job-21-5]]
^5^ Volved hacia mí: quedaréis espantados

[[job-21-6]]
^6^ Que yo mismo me horrorizo al recordarlo,

[[job-21-7]]
^7^ ¿Por qué siguen viviendo los malvados,

[[job-21-8]]
^8^ Su descendencia ante ellos se afianza,

[[job-21-9]]
^9^ En paz sus casas, nada temen,

[[job-21-10]]
^10^ Su toro fecunda sin marrar,

[[job-21-11]]
^11^ Dejan correr a sus niños como ovejas,

[[job-21-12]]
^12^ Cantan con arpa y cítara,

[[job-21-13]]
^13^ Acaban su vida en la ventura,

[[job-21-14]]
^14^ Y con todo, a Dios decían: «¡Lejos de nosotros,

[[job-21-15]]
^15^ ¿Qué es Sadday para que le sirvamos,

[[job-21-16]]
^16^ ¿No está en sus propias manos su ventura,

[[job-21-17]]
^17^ ¿Cuántas veces la lámpara de los malos se apaga,

[[job-21-18]]
^18^ ¿Son como paja ante el viento,

[[job-21-19]]
^19^ ¿Va a guardar Dios para sus hijos su castigo?

[[job-21-20]]
^20^ ¡Vea su ruina con sus propios ojos,

[[job-21-21]]
^21^ ¿Qué le importa la suerte de su casa, después de él,

[[job-21-22]]
^22^ Pero, ¿se enseña a Dios la ciencia?

[[job-21-23]]
^23^ Hay quien muere en su pleno vigor,

[[job-21-24]]
^24^ repletos de grasa su ijares,

[[job-21-25]]
^25^ Y hay quien muere, la amargura en el alma,

[[job-21-26]]
^26^ Juntos luego se acuestan en el polvo,

[[job-21-27]]
^27^ ¡Oh, sé muy bien lo que pensáis,

[[job-21-28]]
^28^ «¿Dónde está, os decís, la casa del magnate?

[[job-21-29]]
^29^ ¿No habéis interrogado a los viandantes?

[[job-21-30]]
^30^ Que el malo es preservado en el día del desastre,

[[job-21-31]]
^31^ Pues, ¿quién le echa en cara su conducta

[[job-21-32]]
^32^ Cuando es llevado al cementerio,

[[job-21-33]]
^33^ Dulces le son los terrones del torrente,

[[job-21-34]]
^34^ ¿Cómo, pues, me consoláis tan en vano?
[[job-22]]
== Capítulo 22

[[job-22-1]]
^1^ Elifaz de Temán tomó la palabra y dijo:

[[job-22-2]]
^2^ ¿Acaso a Dios puede un hombre ser útil?

[[job-22-3]]
^3^ ¿Tiene algún interés Sadday por tu justicia?

[[job-22-4]]
^4^ ¿Acaso por tu piedad él te corrige

[[job-22-5]]
^5^ ¿No será más bien por tu mucha maldad,

[[job-22-6]]
^6^ Porque exigías sin razón prendas a tus hermanos,

[[job-22-7]]
^7^ no dabas agua al sediento,

[[job-22-8]]
^8^ como hombre fuerte que hace suyo el país,

[[job-22-9]]
^9^ despachabas a las viudas con las manos vacías

[[job-22-10]]
^10^ Por eso los lazos te aprisionan

[[job-22-11]]
^11^ La luz se hace tiniebla, y ya no ves,

[[job-22-12]]
^12^ ¿No está Dios en lo alto de los cielos?

[[job-22-13]]
^13^ Y tú has dicho: «¿Qué conoce Dios?

[[job-22-14]]
^14^ Un velo opaco son las nubes para él,

[[job-22-15]]
^15^ ¿Vas a seguir tú la ruta antigua

[[job-22-16]]
^16^ Antes de tiempo fueron aventados,

[[job-22-17]]
^17^ Los que decían a Dios: «¡Apártate de nosotros!

[[job-22-18]]
^18^ Y era él el que colmaba sus casas de ventura,

[[job-22-19]]
^19^ Al verlo los justos se recrean,

[[job-22-20]]
^20^ «¡Cómo acabó nuestro adversario!

[[job-22-21]]
^21^ Reconcíliate con él y haz la paz:

[[job-22-22]]
^22^ Recibe de su boca la enseñanza,

[[job-22-23]]
^23^ Si vuelves a Sadday con humildad,

[[job-22-24]]
^24^ si tiras al polvo el oro,

[[job-22-25]]
^25^ Sadday se te hará lingotes de oro

[[job-22-26]]
^26^ Tendrás entonces en Sadday tus delicias

[[job-22-27]]
^27^ El escuchará cuando le invoques,

[[job-22-28]]
^28^ Todo lo que emprendas saldrá bien,

[[job-22-29]]
^29^ Porque él abate el orgullo de los grandes,

[[job-22-30]]
^30^ El libra al inocente;
[[job-23]]
== Capítulo 23

[[job-23-1]]
^1^ Job tomó la palabra y dijo:

[[job-23-2]]
^2^ Todavía mi queja es una rebelión;

[[job-23-3]]
^3^ ¡Quién me diera saber encontrarle,

[[job-23-4]]
^4^ Un proceso abriría delante de él,

[[job-23-5]]
^5^ Sabría las palabras de su réplica,

[[job-23-6]]
^6^ ¿Precisaría gran fuerza para disputar conmigo?

[[job-23-7]]
^7^ Reconocería en su adversario a un hombre recto,

[[job-23-8]]
^8^ Si voy hacia el oriente, no está allí;

[[job-23-9]]
^9^ Cuando le busco al norte, no aparece,

[[job-23-10]]
^10^ Pero él mis pasos todos sabe:

[[job-23-11]]
^11^ Mi pie se ha adherido a su paso,

[[job-23-12]]
^12^ del mandato de sus labios no me aparto,

[[job-23-13]]
^13^ Mas él decide, ¿quién le hará retractarse?

[[job-23-14]]
^14^ Así ejecutará mi sentencia,

[[job-23-15]]
^15^ Por eso estoy, ante él, horrorizado,

[[job-23-16]]
^16^ Dios me ha enervado el corazón,

[[job-23-17]]
^17^ Pues no he desaparecido en las tinieblas,
[[job-24]]
== Capítulo 24

[[job-24-1]]
^1^ ¿Por qué Sadday no se reserva tiempos,

[[job-24-2]]
^2^ Los malvados remueven los mojones,

[[job-24-3]]
^3^ Se llevan el asno de los huérfanos,

[[job-24-4]]
^4^ Los mendigos tienen que retirarse del camino,

[[job-24-5]]
^5^ Como onagros del desierto salen a su tarea,

[[job-24-6]]
^6^ Cosechan en el campo del inicuo,

[[job-24-7]]
^7^ Pasan la noche desnudos, sin vestido,

[[job-24-8]]
^8^ Calados por el turbión de las montañas,

[[job-24-9]]
^9^ Al huérfano se le arranca del pecho,

[[job-24-10]]
^10^ Desnudos andan, sin vestido;

[[job-24-11]]
^11^ Pasan el mediodía entre dos paredes,

[[job-24-12]]
^12^ Desde la ciudad gimen los que mueren,

[[job-24-13]]
^13^ Otros hay rebeldes a la luz:

[[job-24-14]]
^14^ Aún no es de día cuando el asesino se levanta

[[job-24-15]]
^15^ El ojo del adúltero el crepúsculo espía:

[[job-24-16]]
^16^ Las casas perfora en las tínieblas.

[[job-24-17]]
^17^ Para todos ellos la mañana es sombra,

[[job-24-18]]
^18^ No es más que una paja sobre el agua,

[[job-24-19]]
^19^ Como el calor de sequía arrebata el agua de nieve,

[[job-24-20]]
^20^ El seno que le formó se olvida de él,

[[job-24-21]]
^21^ Maltrataba a la estéril, la que no da a luz,

[[job-24-22]]
^22^ Pero Aquel que agarra con su fuerza a los tiranos

[[job-24-23]]
^23^ Le dejaba apoyarse con seguridad,

[[job-24-24]]
^24^ Se encumbró por un instante, y ya no existe,

[[job-24-25]]
^25^ ¿No es así? ¿quién me puede desmentir
[[job-25]]
== Capítulo 25

[[job-25-1]]
^1^ Bildad de Súaj tomó la palabra y dijo:

[[job-25-2]]
^2^ Es soberano de temible fuerza

[[job-25-3]]
^3^ ¿Puede contar alguien sus tropas?

[[job-25-4]]
^4^ ¿Cómo un hombre será justo ante Dios?

[[job-25-5]]
^5^ Si ni la luna misma tiene brillo,

[[job-25-6]]
^6^ ¡cuánto menos un hombre, esa gusanera,
[[job-26]]
== Capítulo 26

[[job-26-1]]
^1^ Job tomó la palabra y dijo:

[[job-26-2]]
^2^ ¡Qué bien has sostenido al débil

[[job-26-3]]
^3^ ¡Qué bien has aconsejado al ignorante,

[[job-26-4]]
^4^ ¿A quién has dirigido tus discursos,

[[job-26-5]]
^5^ Las Sombras tiemblan bajo tierra,

[[job-26-6]]
^6^ Ante él, el Seol está al desnudo,

[[job-26-7]]
^7^ El extiende el Septentrión sobre el vacío,

[[job-26-8]]
^8^ El encierra las aguas en sus nubes,

[[job-26-9]]
^9^ El encubre la cara de la luna llena,

[[job-26-10]]
^10^ El trazó un cerco sobre la haz de las aguas,

[[job-26-11]]
^11^ Se tambalean las columnas del cielo,

[[job-26-12]]
^12^ Con su poder hendió la mar,

[[job-26-13]]
^13^ Su soplo abrillantó los cielos,

[[job-26-14]]
^14^ Estos son los contornos de sus obras,
[[job-27]]
== Capítulo 27

[[job-27-1]]
^1^ Job continuó pronunciando su discurso y dijo:

[[job-27-2]]
^2^ ¡Vive Dios, que justicia me rehúsa,

[[job-27-3]]
^3^ mientras siga en mí todo mi espíritu

[[job-27-4]]
^4^ no dirán mis labios falsedad,

[[job-27-5]]
^5^ Lejos de mí daros la razón:

[[job-27-6]]
^6^ Me he aferrado a mi justicia, y no la soltaré,

[[job-27-7]]
^7^ ¡Tenga la suerte del malvado mi enemigo,

[[job-27-8]]
^8^ Pues ¿cuál es la esperanza del impío cuando suplica,

[[job-27-9]]
^9^ ¿Acaso Dios escucha su gemido,

[[job-27-10]]
^10^ ¿Tenía él sus delicias en Sadday?

[[job-27-11]]
^11^ Yo os muestro el proceder de Dios,

[[job-27-12]]
^12^ Y si todos vosotros ya lo habéis comprobado,

[[job-27-13]]
^13^ Esta es la suerte que al malvado Dios reserva,

[[job-27-14]]
^14^ Aunque sean muchos sus hijos, son para la espada,

[[job-27-15]]
^15^ Los que queden serán sepultados por la Peste,

[[job-27-16]]
^16^ Si acumula la plata como polvo,

[[job-27-17]]
^17^ ¡que amontone!: un justo se vestirá con ellos,

[[job-27-18]]
^18^ Se edificó una casa de araña,

[[job-27-19]]
^19^ Rico se acuesta, mas por última vez;

[[job-27-20]]
^20^ En pleno día le asaltan los terrores,

[[job-27-21]]
^21^ El solano se lo lleva, y desaparece,

[[job-27-22]]
^22^ Sin compasión por blanco se le toma,

[[job-27-23]]
^23^ Bátense palmas a su ruina,
[[job-28]]
== Capítulo 28

[[job-28-1]]
^1^ Hay, sí, para la plata un venero,

[[job-28-2]]
^2^ Se extrae del suelo el hierro,

[[job-28-3]]
^3^ Se pone fin a las tinieblas,

[[job-28-4]]
^4^ Extranjeros abren galerías

[[job-28-5]]
^5^ Tierra de donde sale el pan,

[[job-28-6]]
^6^ Lugar donde las piedras son zafiro

[[job-28-7]]
^7^ Sendero que no conoce el ave de rapiña,

[[job-28-8]]
^8^ No lo pisaron los hijos del orgullo,

[[job-28-9]]
^9^ Aplica el hombre al pedernal su mano,

[[job-28-10]]
^10^ Abre canales en las rocas,

[[job-28-11]]
^11^ Explora las fuentes de los ríos,

[[job-28-12]]
^12^ Mas la Sabiduría, ¿de dónde viene?

[[job-28-13]]
^13^ Ignora el hombre su sendero,

[[job-28-14]]
^14^ Dice el Abismo: «No está en mí»,

[[job-28-15]]
^15^ No se puede dar por ella oro fino,

[[job-28-16]]
^16^ ni evaluarla con el oro de Ofir,

[[job-28-17]]
^17^ No la igualan el oro ni el vidrio,

[[job-28-18]]
^18^ Corales y cristal ni mencionarlos,

[[job-28-19]]
^19^ No la iguala el topacio de Kus,

[[job-28-20]]
^20^ Mas la Sabiduría, ¿de dónde viene?

[[job-28-21]]
^21^ Ocúltase a los ojos de todo ser viviente,

[[job-28-22]]
^22^ La Perdición y la Muerte dicen:

[[job-28-23]]
^23^ Sólo Dios su camino ha distinguido,

[[job-28-24]]
^24^ (Porque él otea hasta los confines de la tierra,

[[job-28-25]]
^25^ Cuando dio peso al viento

[[job-28-26]]
^26^ cuando a la lluvia impuso ley

[[job-28-27]]
^27^ entonces la vio y le puso precio,

[[job-28-28]]
^28^ Y dijo al hombre:
[[job-29]]
== Capítulo 29

[[job-29-1]]
^1^ Job continuó pronunciando su discurso y dijo:

[[job-29-2]]
^2^ ¡Quién me hiciera volver a los meses de antaño,

[[job-29-3]]
^3^ cuando su lámpara brillaba sobre mi cabeza,

[[job-29-4]]
^4^ como era yo en los días de mi otoño,

[[job-29-5]]
^5^ cuando Sadday estaba aún conmigo,

[[job-29-6]]
^6^ cuando mis pies se bañaban en manteca,

[[job-29-7]]
^7^ Si yo salía a la puerta que domina la ciudad

[[job-29-8]]
^8^ se retiraban los jóvenes al verme,

[[job-29-9]]
^9^ Los notables cortaban sus palabras

[[job-29-10]]
^10^ La voz de los jefes se ahogaba,

[[job-29-11]]
^11^ Oído que lo oía me llamaba feliz,

[[job-29-12]]
^12^ Pues yo libraba al pobre que clamaba,

[[job-29-13]]
^13^ La bendición del moribundo subía hacia mí,

[[job-29-14]]
^14^ Me había puesto la justicia, y ella me revestía,

[[job-29-15]]
^15^ Era yo los ojos del ciego

[[job-29-16]]
^16^ Era el padre de los pobres,

[[job-29-17]]
^17^ Quebraba los colmillos del inicuo,

[[job-29-18]]
^18^ Y me decía: «Anciano moriré,

[[job-29-19]]
^19^ Mi raíz está franca a las aguas,

[[job-29-20]]
^20^ Mi gloria será siempre nueva en mí,

[[job-29-21]]
^21^ Me escuchaban ellos con expectación,

[[job-29-22]]
^22^ Después de hablar yo, no replicaban,

[[job-29-23]]
^23^ Me esperaban lo mismo que a la lluvia,

[[job-29-24]]
^24^ Si yo les sonreía, no querían creerlo,

[[job-29-25]]
^25^ Les indicaba el camino y me ponía al frente,
[[job-30]]
== Capítulo 30

[[job-30-1]]
^1^ Mas ahora ríense de mí

[[job-30-2]]
^2^ Aun la fuerza de sus manos, ¿para qué me servía?;

[[job-30-3]]
^3^ agotado por el hambre y la penuria.

[[job-30-4]]
^4^ Recogían armuelle por los matorrales,

[[job-30-5]]
^5^ De entre los hombres estaban expulsados,

[[job-30-6]]
^6^ Moraban en las escarpas de los torrentes,

[[job-30-7]]
^7^ Entre los matorrales rebuznaban,

[[job-30-8]]
^8^ Hijos de abyección, sí, ralea sin nombre,

[[job-30-9]]
^9^ ¡Y ahora soy yo la copla de ellos,

[[job-30-10]]
^10^ Horrorizados de mí, se quedan a distancia,

[[job-30-11]]
^11^ Porque él ha soltado mi cuerda y me maltrata,

[[job-30-12]]
^12^ Una ralea se alza a mi derecha,

[[job-30-13]]
^13^ Mi sendero han destruido,

[[job-30-14]]
^14^ como por ancha brecha irrumpen,

[[job-30-15]]
^15^ Los terrores se vuelven contra mí,

[[job-30-16]]
^16^ Y ahora en mí se derrama mi alma,

[[job-30-17]]
^17^ De noche traspasa el mal mis huesos,

[[job-30-18]]
^18^ Con violencia agarra él mi vestido,

[[job-30-19]]
^19^ Me ha tirado en el fango,

[[job-30-20]]
^20^ Grito hacia ti y tú no me respondes,

[[job-30-21]]
^21^ Te has vuelto cruel para conmigo,

[[job-30-22]]
^22^ Me llevas a caballo sobre el viento,

[[job-30-23]]
^23^ Pues bien sé que a la muerte me conduces,

[[job-30-24]]
^24^ Y sin embargo, ¿he vuelto yo la mano contra el pobre,

[[job-30-25]]
^25^ ¿No he llorado por el que vive en estrechez?

[[job-30-26]]
^26^ Yo esperaba la dicha, y llegó la desgracia,

[[job-30-27]]
^27^ Me hierven las entrañas sin descanso,

[[job-30-28]]
^28^ Sin haber sol, ando renegrido,

[[job-30-29]]
^29^ Me he hecho hermano de chacales

[[job-30-30]]
^30^ Mi piel se ha ennegrecido sobre mí,

[[job-30-31]]
^31^ ¡Mi cítara sólo ha servido para el duelo,
[[job-31]]
== Capítulo 31

[[job-31-1]]
^1^ Había hecho yo un pacto con mis ojos,

[[job-31-2]]
^2^ Y ¿cuál es el reparto que hace Dios desde arriba,

[[job-31-3]]
^3^ ¿No es acaso desgracia para el inicuo,

[[job-31-4]]
^4^ ¿No ve él mis caminos,

[[job-31-5]]
^5^ ¿He caminado junto a la mentira?

[[job-31-6]]
^6^ ¡Péseme él en balanza de justicia,

[[job-31-7]]
^7^ Si mis pasos del camino se extraviaron,

[[job-31-8]]
^8^ ¡coma otro lo que yo sembré,

[[job-31-9]]
^9^ Si mi corazón fue seducido por mujer,

[[job-31-10]]
^10^ ¡muela para otro mi mujer,

[[job-31-11]]
^11^ Pues sería ello una impudicia,

[[job-31-12]]
^12^ sería fuego que devora hasta la Perdición

[[job-31-13]]
^13^ Si he menospreciado el derecho de mi siervo

[[job-31-14]]
^14^ ¿qué podré hacer cuando Dios se levante?

[[job-31-15]]
^15^ ¿No los hizo él, igual que a mí, en el vientre?

[[job-31-16]]
^16^ Me he negado al deseo de los débiles?

[[job-31-17]]
^17^ ¿Comí solo mi pedazo de pan,

[[job-31-18]]
^18^ ¡Siendo así que desde mi infancia me crió él como un padre,

[[job-31-19]]
^19^ ¿He visto a un miserable sin vestido,

[[job-31-20]]
^20^ sin que en lo íntimo de su ser me bendijera,

[[job-31-21]]
^21^ Si he alzado mi mano contra un huérfano,

[[job-31-22]]
^22^ ¡mi espalda se separe de mi nuca,

[[job-31-23]]
^23^ Pues el terror de Dios caería sobre mí,

[[job-31-24]]
^24^ ¿He hecho del oro mi confianza,

[[job-31-25]]
^25^ ¿Me he complacido en la abundancia de mis bienes,

[[job-31-26]]
^26^ ¿Acaso, al ver el sol cómo brillaba,

[[job-31-27]]
^27^ mi corazón, en secreto, se dejó seducir

[[job-31-28]]
^28^ También hubiera sido una falta criminal,

[[job-31-29]]
^29^ ¿Del infortunio de mi enemigo me alegré,

[[job-31-30]]
^30^ ¡Yo que no permitía a mi lengua pecar

[[job-31-31]]
^31^ ¿No decían las gentes de mi tienda:

[[job-31-32]]
^32^ El forastero no pernoctaba a la intemperie,

[[job-31-33]]
^33^ ¿He disimulado mis culpas a los hombres,

[[job-31-34]]
^34^ porque temiera el rumor público,

[[job-31-35]]
^35^ ¡Oh! ¿quién hará que se me escuche?

[[job-31-36]]
^36^ pienso llevarlo sobre mis espaldas,

[[job-31-37]]
^37^ Del número de mis pasos voy a rendirle cuentas,

[[job-31-38]]
^38^ Si mi tierra grita contra mí,

[[job-31-39]]
^39^ si he comido sus frutos sin pagarlos

[[job-31-40]]
^40^ ¡en vez de trigo broten en ella espinas,
[[job-32]]
== Capítulo 32

[[job-32-1]]
^1^ Aquellos tres hombres dejaron de replicar a Job, porque se

[[job-32-2]]
^2^ Entonces montó en cólera Elihú, hijo de Barakel el buzita, de

[[job-32-3]]
^3^ y también contra sus tres amigos, porque no habían hallado ya

[[job-32-4]]
^4^ Mientras hablaban ellos con Job, Elihú se había mantenido a la

[[job-32-5]]
^5^ Pero cuando vio que en la boca de los tres hombres ya no

[[job-32-6]]
^6^ Tomó, pues, la palabra Elihú, hijo de Barakel el buzita, y

[[job-32-7]]
^7^ Me decía yo: «Hablará la edad,

[[job-32-8]]
^8^ Pero en verdad, es un soplo en el hombre,

[[job-32-9]]
^9^ No son sabios los que están llenos de años,

[[job-32-10]]
^10^ Por eso he dicho: Escuchadme,

[[job-32-11]]
^11^ Hasta ahora vuestras razones esperaba,

[[job-32-12]]
^12^ tenía puesta en vosotros mi atención.

[[job-32-13]]
^13^ No digáis, pues: «Hemos hallado la sabiduría;

[[job-32-14]]
^14^ No hilaré yo palabras como ésas,

[[job-32-15]]
^15^ Han quedado vencidos, no han respondido más:

[[job-32-16]]
^16^ He esperado, pero ya que no hablan,

[[job-32-17]]
^17^ responderé yo por mi parte,

[[job-32-18]]
^18^ Pues estoy lleno de palabras,

[[job-32-19]]
^19^ Es, en mi seno, como vino sin escape,

[[job-32-20]]
^20^ Hablaré para desahogarme,

[[job-32-21]]
^21^ No tomaré el partido de ninguno,

[[job-32-22]]
^22^ Pues yo no sé adular:
[[job-33]]
== Capítulo 33

[[job-33-1]]
^1^ Ten a bien, Job, escuchar mis palabras,

[[job-33-2]]
^2^ Ya ves que he abierto mi boca,

[[job-33-3]]
^3^ Mi corazón dará palabras cuerdas,

[[job-33-4]]
^4^ El soplo de Dios me hizo,

[[job-33-5]]
^5^ Si eres capaz, replícame,

[[job-33-6]]
^6^ Mira, soy como tú, no soy un dios,

[[job-33-7]]
^7^ Por eso mi terror no te ha de espantar,

[[job-33-8]]
^8^ No has hecho más que decir a mis propios oídos,

[[job-33-9]]
^9^ «Puro soy, sin delito;

[[job-33-10]]
^10^ Pero él inventa contra mí pretextos,

[[job-33-11]]
^11^ mis pies pone en el cepo,

[[job-33-12]]
^12^ Pues bien, respondo, en esto no tienes razón,

[[job-33-13]]
^13^ ¿Por qué te querellas tú con él

[[job-33-14]]
^14^ Habla Dios una vez,

[[job-33-15]]
^15^ En sueños, en visión nocturna,

[[job-33-16]]
^16^ entonces abre él el oído de los hombres,

[[job-33-17]]
^17^ para apartar al hombre de sus obras

[[job-33-18]]
^18^ para librar su alma de la fosa

[[job-33-19]]
^19^ También es corregido por el dolor en su camilla,

[[job-33-20]]
^20^ cuando a su vida el alimento asquea

[[job-33-21]]
^21^ cuando su carne desaparece de la vista,

[[job-33-22]]
^22^ cuando su alma a la fosa se aproxima

[[job-33-23]]
^23^ Si hay entonces junto a él un Angel,

[[job-33-24]]
^24^ que de él se apiade y diga:

[[job-33-25]]
^25^ su carne se renueva de vigor juvenil,

[[job-33-26]]
^26^ Invoca a Dios, que le otorga su favor,

[[job-33-27]]
^27^ canta así entre los hombres:

[[job-33-28]]
^28^ Ha librado mi alma de pasar por la fosa,

[[job-33-29]]
^29^ He aquí todo lo que hace Dios,

[[job-33-30]]
^30^ para recobrar su alma de la fosa,

[[job-33-31]]
^31^ Atiende, Job, escúchame,

[[job-33-32]]
^32^ Si tienes algo que decir, replícame,

[[job-33-33]]
^33^ Si no, escúchame,
[[job-34]]
== Capítulo 34

[[job-34-1]]
^1^ Elihú reanudó su discurso y dijo:

[[job-34-2]]
^2^ Escuchad, sabios, mis palabras,

[[job-34-3]]
^3^ Porque el oído aprecia las palabras,

[[job-34-4]]
^4^ Decidamos entre nosotros lo que es justo,

[[job-34-5]]
^5^ Pues Job ha dicho: «Yo soy justo,

[[job-34-6]]
^6^ mi juez se muestra cruel para conmigo,

[[job-34-7]]
^7^ ¿Qué hombre hay como Job,

[[job-34-8]]
^8^ que anda en compañía de malhechores,

[[job-34-9]]
^9^ Pues él ha dicho: «Nada gana el hombre

[[job-34-10]]
^10^ Así pues, escuchadme, como hombres sensatos.

[[job-34-11]]
^11^ que la obra del hombre, él se la paga,

[[job-34-12]]
^12^ En verdad, Dios no hace el mal,

[[job-34-13]]
^13^ ¿Quién, si no, le confió la tierra,

[[job-34-14]]
^14^ Si él retirara a sí su espíritu,

[[job-34-15]]
^15^ a una expiraría toda carne,

[[job-34-16]]
^16^ Si tienes inteligencia, escucha esto,

[[job-34-17]]
^17^ ¿Podría gobernar un enemigo del derecho?

[[job-34-18]]
^18^ ¡Aquel que dice a un rey: «¡Inútil!»,

[[job-34-19]]
^19^ que no hace acepción de príncipes,

[[job-34-20]]
^20^ Mueren ellos de repente a media noche,

[[job-34-21]]
^21^ Pues sus ojos vigilan los caminos del hombre,

[[job-34-22]]
^22^ No hay tinieblas ni sombra

[[job-34-23]]
^23^ No asigna él un plazo al hombre

[[job-34-24]]
^24^ Quebranta a los grandes sin examen,

[[job-34-25]]
^25^ Es que él conoce sus acciones,

[[job-34-26]]
^26^ Como a criminales los azota,

[[job-34-27]]
^27^ porque se apartaron de su seguimiento,

[[job-34-28]]
^28^ hasta hacer llegar a él el gemido del débil

[[job-34-29]]
^29^ Mas si él sigue inmóvil, sin que nadie le perturbe,

[[job-34-30]]
^30^ libra al impío del cepo de la angustia,

[[job-34-31]]
^31^ Cuando éste dice a Dios:

[[job-34-32]]
^32^ si he pecado instrúyeme,

[[job-34-33]]
^33^ ¿Acaso, según tú, tendría él que castigar,

[[job-34-34]]
^34^ Mas los hombres sensatos me dirán,

[[job-34-35]]
^35^ «No habla Job cuerdamente,

[[job-34-36]]
^36^ Que sea Job probado a fondo,

[[job-34-37]]
^37^ Porque a su pecado la rebeldía añade,
[[job-35]]
== Capítulo 35

[[job-35-1]]
^1^ Elihú reanudó su discurso y dijo:

[[job-35-2]]
^2^ ¿Crees que eso es juicioso,

[[job-35-3]]
^3^ cuando dices: «¿Qué te importa a ti,

[[job-35-4]]
^4^ Yo te daré respuesta,

[[job-35-5]]
^5^ ¡Mira a los cielos y ve,

[[job-35-6]]
^6^ Si pecas, ¿qué le causas?,

[[job-35-7]]
^7^ ¿Qué le das, si eres justo,

[[job-35-8]]
^8^ A un hombre igual que tú afecta tu maldad,

[[job-35-9]]
^9^ Bajo la carga de la opresión se gime,

[[job-35-10]]
^10^ mas nadie dice: «¿Dónde está Dios, mi hacedor,

[[job-35-11]]
^11^ el que nos hace más hábiles que las bestias de la tierra,

[[job-35-12]]
^12^ Entonces se grita, sin que responda él,

[[job-35-13]]
^13^ Seguro, la falsedad Dios no la escucha,

[[job-35-14]]
^14^ Mucho menos, el decir que no le adviertes,

[[job-35-15]]
^15^ o también que su cólera no castiga nada,

[[job-35-16]]
^16^ Job, pues, abre en vano su boca,
[[job-36]]
== Capítulo 36

[[job-36-1]]
^1^ Prosiguió Elihú y dijo:

[[job-36-2]]
^2^ Espera un poco, y yo te instruiré,

[[job-36-3]]
^3^ Voy a llevar muy lejos mi saber,

[[job-36-4]]
^4^ En verdad, no son mentira mis palabras,

[[job-36-5]]
^5^ Dios no rechaza al hombre íntegro,

[[job-36-6]]
^6^ ni deja vivir al malvado en plena fuerza.

[[job-36-7]]
^7^ y no quita al justo su derecho.

[[job-36-8]]
^8^ y él los amarra con cadenas,

[[job-36-9]]
^9^ Entonces les pone su obra al descubierto

[[job-36-10]]
^10^ A sus oídos pronuncia una advertencia,

[[job-36-11]]
^11^ Si escuchan y son dóciles,

[[job-36-12]]
^12^ Si no escuchan, pasan el Canal,

[[job-36-13]]
^13^ Y los obstinados que imponen la cólera

[[job-36-14]]
^14^ mueren en plena juventud,

[[job-36-15]]
^15^ El salva al pobre por su misma pobreza,

[[job-36-16]]
^16^ También a ti te arrancará de las fauces de la angustia.

[[job-36-17]]
^17^ Mas no hacías justicia de los malos,

[[job-36-18]]
^18^ Procura, pues, que no te seduzca la abundancia,

[[job-36-19]]
^19^ Haz comparecer al rico como al que nada tiene,

[[job-36-20]]
^20^ No aplastes a aquellos que te son extraños,

[[job-36-21]]
^21^ Guárdate de inclinarte hacia la iniquidad,

[[job-36-22]]
^22^ Mira, Dios es sublime por su fuerza,

[[job-36-23]]
^23^ ¿Quién le señaló el camino a seguir?

[[job-36-24]]
^24^ Acuérdate más bien de ensalzar su obra,

[[job-36-25]]
^25^ Todo hombre la contempla,

[[job-36-26]]
^26^ Sí, Dios es grande y no le comprendemos,

[[job-36-27]]
^27^ El atrae las gotas de agua,

[[job-36-28]]
^28^ que luego derraman las nubes,

[[job-36-29]]
^29^ ¿Quién además comprenderá el despliegue de la nube,

[[job-36-30]]
^30^ Ved que despliega su niebla por encima

[[job-36-31]]
^31^ Pues por ellas sustenta él a los pueblos,

[[job-36-32]]
^32^ En sus manos el rayo levanta

[[job-36-33]]
^33^ Su trueno le anuncia,
[[job-37]]
== Capítulo 37

[[job-37-1]]
^1^ Mi corazón también por eso tiembla,

[[job-37-2]]
^2^ ¡Escuchad, escuchad el fragor de su voz,

[[job-37-3]]
^3^ Hace relampaguear por todo el cielo,

[[job-37-4]]
^4^ Detrás de él una voz ruge:

[[job-37-5]]
^5^ Dios nos da a ver maravillas,

[[job-37-6]]
^6^ Cuando dice a la nieve: «¡Cae sobre la tierra!»,

[[job-37-7]]
^7^ la mano de todo hombre retiene bajo sello,

[[job-37-8]]
^8^ Las fieras a sus guaridas huyen

[[job-37-9]]
^9^ Del sur llega el huracán,

[[job-37-10]]
^10^ Al soplo de Dios se forma el hielo,

[[job-37-11]]
^11^ El carga a la nube de un rayo,

[[job-37-12]]
^12^ y éste, gira girando,

[[job-37-13]]
^13^ Ya como castigo para los pueblos de la tierra,

[[job-37-14]]
^14^ Presta, Job, oído a esto,

[[job-37-15]]
^15^ ¿Sabes acaso cómo Dios los rige,

[[job-37-16]]
^16^ ¿Sabes tú cómo las nubes cuelgan en equilibrio, maravilla de una ciencia consumada?

[[job-37-17]]
^17^ Tú, cuyos vestidos queman

[[job-37-18]]
^18^ ¿puedes extender con él la bóveda del cielo,

[[job-37-19]]
^19^ Enséñanos qué le hemos de decir:

[[job-37-20]]
^20^ Si hablo yo, ¿alguien se lo cuenta?

[[job-37-21]]
^21^ Ahora ya no se ve la luz,

[[job-37-22]]
^22^ y una claridad llega del norte:

[[job-37-23]]
^23^ ¡es Sadday!, no podemos alcanzarle.

[[job-37-24]]
^24^ Por eso le temen los hombres:
[[job-38]]
== Capítulo 38

[[job-38-1]]
^1^ Yahveh repondió a Job desde el seno de la tempestad y dijo:

[[job-38-2]]
^2^ ¿Quién es éste que empaña el Consejo

[[job-38-3]]
^3^ Ciñe tus lomos como un bravo:

[[job-38-4]]
^4^ Dónde estabas tú cuando fundaba yo la tierra?

[[job-38-5]]
^5^ ¿Quién fijó sus medidas? ¿lo sabrías?

[[job-38-6]]
^6^ ¿Sobre qué se afirmaron sus bases?

[[job-38-7]]
^7^ entre el clamor a coro de las estrellas del alba

[[job-38-8]]
^8^ ¿Quién encerró el mar con doble puerta,

[[job-38-9]]
^9^ cuando le puse una nube por vestido

[[job-38-10]]
^10^ cuando le tracé sus linderos

[[job-38-11]]
^11^ «¡Llegarás hasta aquí, no más allá - le dije -,

[[job-38-12]]
^12^ ¿Has mandado, una vez en tu vida, a la mañana,

[[job-38-13]]
^13^ para que agarre a la tierra por los bordes

[[job-38-14]]
^14^ Ella se trueca en arcilla de sello,

[[job-38-15]]
^15^ Se quita entonces su luz a los malvados,

[[job-38-16]]
^16^ ¿Has penetrado hasta las fuentes del mar?

[[job-38-17]]
^17^ ¿Se te han mostrado las puertas de la Muerte?

[[job-38-18]]
^18^ ¿Has calculado las anchuras de la tierra?

[[job-38-19]]
^19^ ¿Por dónde se va a la morada de la luz?

[[job-38-20]]
^20^ para que puedas llevarlas a su término,

[[job-38-21]]
^21^ Si lo sabes, ¡es que ya habías nacido entonces,

[[job-38-22]]
^22^ ¿Has llegado a los depósitos de nieve?

[[job-38-23]]
^23^ que yo guardo para el tiempo de angustia,

[[job-38-24]]
^24^ ¿Por qué camino se reparte la luz,

[[job-38-25]]
^25^ ¿Quién abre un canal al aguacero,

[[job-38-26]]
^26^ para llover sobre tierra sin hombre,

[[job-38-27]]
^27^ para abrevar a las soledades desoladas

[[job-38-28]]
^28^ ¿Tiene padre la lluvia?

[[job-38-29]]
^29^ ¿De qué seno sale el hielo?

[[job-38-30]]
^30^ cuando las aguas se aglutinan como piedra

[[job-38-31]]
^31^ ¿Puedes tú anudar los lazos de las Pléyades

[[job-38-32]]
^32^ ¿Haces salir la Corona a su tiempo?

[[job-38-33]]
^33^ ¿Conoces las leyes de los Cielos?

[[job-38-34]]
^34^ ¿Levantas tu voz hasta las nubes?,

[[job-38-35]]
^35^ A tu orden, ¿los relámpagos parten,

[[job-38-36]]
^36^ ¿Quién puso en el ibis la sabiduría?

[[job-38-37]]
^37^ ¿Quién tiene pericia para contar las nubes?

[[job-38-38]]
^38^ cuando se aglutina el polvo en una masa

[[job-38-39]]
^39^ ¿Cazas tú acaso la presa a la leona?

[[job-38-40]]
^40^ cuando en sus guaridas están acurrucados,

[[job-38-41]]
^41^ ¿Quién prepara su provisión al cuervo,
[[job-39]]
== Capítulo 39

[[job-39-1]]
^1^ ¿Sabes cuándo hacen las rebecas sus crías?

[[job-39-2]]
^2^ ¿has contado los meses de su gestación?

[[job-39-3]]
^3^ Entonces se acurrucan y paren a sus crías,

[[job-39-4]]
^4^ Y cuando ya sus crías se hacen fuertes y grandes,

[[job-39-5]]
^5^ ¿Quién dejó al onagro en libertad

[[job-39-6]]
^6^ Yo le he dado la estepa por morada,

[[job-39-7]]
^7^ Se ríe del tumulto de las ciudades,

[[job-39-8]]
^8^ explora las montañas, pasto suyo,

[[job-39-9]]
^9^ ¿Querrá acaso servirte el buey salvaje,

[[job-39-10]]
^10^ ¿Atarás a su cuello la coyunda?

[[job-39-11]]
^11^ ¿Puedes fiarte de él por su gran fuerza?

[[job-39-12]]
^12^ ¿Estás seguro de que vuelva,

[[job-39-13]]
^13^ El ala del avestruz, ¿se puede comparar

[[job-39-14]]
^14^ Ella en tierra abandona sus huevos,

[[job-39-15]]
^15^ se olvida de que puede aplastarlos algún pie,

[[job-39-16]]
^16^ Dura para sus hijos cual si no fueran suyos,

[[job-39-17]]
^17^ Es que Dios la privó de sabiduría,

[[job-39-18]]
^18^ Pero en cuanto se alza y se remonta,

[[job-39-19]]
^19^ ¿Das tú al caballo la bravura?

[[job-39-20]]
^20^ ¿Le haces brincar como langosta?

[[job-39-21]]
^21^ Piafa de júbilo en el valle,

[[job-39-22]]
^22^ Se ríe del miedo y de nada se asusta,

[[job-39-23]]
^23^ Va resonando sobre él la aljaba,

[[job-39-24]]
^24^ Hirviendo de impaciencia la tierra devora,

[[job-39-25]]
^25^ A cada toque de trompeta dice: «¡Aah!»

[[job-39-26]]
^26^ ¿Acaso por tu acuerdo el halcón emprende el vuelo,

[[job-39-27]]
^27^ ¿Por orden tuya se remonta el águila

[[job-39-28]]
^28^ Pone en la roca su mansión nocturna,

[[job-39-29]]
^29^ Desde allí acecha a su presa,

[[job-39-30]]
^30^ Sus crías lamen sangre;
[[job-40]]
== Capítulo 40

[[job-40-1]]
^1^ Y Yahveh se dirigió a Job y le dijo:

[[job-40-2]]
^2^ ¿Cederá el adversario de Sadday?

[[job-40-3]]
^3^ Y Job respondió a Yahveh:

[[job-40-4]]
^4^ ¡He hablado a la ligera: ¿qué voy a responder?

[[job-40-5]]
^5^ Hablé una vez..., no he de repetir;

[[job-40-6]]
^6^ Yahveh respondió a Job desde el seno de la tempestad y dijo:

[[job-40-7]]
^7^ Ciñe tus lomos como un bravo:

[[job-40-8]]
^8^ ¿De verdad quieres anular mi juicio?,

[[job-40-9]]
^9^ ¿Tienes un brazo tú como el de Dios?

[[job-40-10]]
^10^ ¡Ea, cíñete de majestad y de grandeza,

[[job-40-11]]
^11^ ¡Derrama la explosión de tu cólera,

[[job-40-12]]
^12^ ¡Con una mirada abate al orgulloso,

[[job-40-13]]
^13^ ¡Húndelos juntos en el suelo,

[[job-40-14]]
^14^ ¡Y yo mismo te rendiré homenaje,

[[job-40-15]]
^15^ Mira a Behemot, creatura mía, como tú.

[[job-40-16]]
^16^ Mira su fuerza en sus riñones,

[[job-40-17]]
^17^ Atiesa su cola igual que un cedro,

[[job-40-18]]
^18^ Tubos de bronce son sus vértebras;

[[job-40-19]]
^19^ Es la primera de las obras de Dios:

[[job-40-20]]
^20^ los montes le aportan un tributo,

[[job-40-21]]
^21^ Bajo los lotos se recuesta,

[[job-40-22]]
^22^ Los lotos le recubren con su sombra,

[[job-40-23]]
^23^ Si el río va bravo, no se inquieta,

[[job-40-24]]
^24^ ¿Quién, pues, podrá prenderle por los ojos,

[[job-40-25]]
^25^ Y a Leviatán, ¿le pescarás tú a anzuelo,

[[job-40-26]]
^26^ ¿Harás pasar por su nariz un junco?

[[job-40-27]]
^27^ ¿Te hará por ventura largas súplicas?

[[job-40-28]]
^28^ ¿Pactará contigo un contrato

[[job-40-29]]
^29^ ¿Jugarás con él como con un pájaro,

[[job-40-30]]
^30^ ¿traficarán con él los asociados?

[[job-40-31]]
^31^ ¿Acribillarás su piel de dardos?

[[job-40-32]]
^32^ Pon sobre él tu mano:
[[job-41]]
== Capítulo 41

[[job-41-1]]
^1^ ¡Sería vana tu esperanza

[[job-41-2]]
^2^ No hay audaz que lo despierte,

[[job-41-3]]
^3^ ¿Quién le hizo frente y quedó salvo?

[[job-41-4]]
^4^ Mencionaré también sus miembros,

[[job-41-5]]
^5^ ¿Quién rasgó la delantera de su túnica

[[job-41-6]]
^6^ ¿Quién abrió las hojas de sus fauces?

[[job-41-7]]
^7^ Su dorso son hileras de escudos,

[[job-41-8]]
^8^ Están apretados uno a otro,

[[job-41-9]]
^9^ Están pegados entre sí

[[job-41-10]]
^10^ Echa luz su estornudo,

[[job-41-11]]
^11^ Salen antorchas de sus fauces,

[[job-41-12]]
^12^ De sus narices sale humo,

[[job-41-13]]
^13^ Su soplo enciende carbones,

[[job-41-14]]
^14^ En su cuello se asienta la fuerza,

[[job-41-15]]
^15^ Son compactas las papadas de su carne:

[[job-41-16]]
^16^ Su corazón es duro como roca,

[[job-41-17]]
^17^ Cuando se yergue, se amedrentan las olas,

[[job-41-18]]
^18^ Le alcanza la espada sin clavarse,

[[job-41-19]]
^19^ Para él e hierro es sólo paja,

[[job-41-20]]
^20^ No le ahuyentan los disparos del arco,

[[job-41-21]]
^21^ Una paja le parece la maza,

[[job-41-22]]
^22^ Debajo de él tejas puntiagudas:

[[job-41-23]]
^23^ Hace del abismo una olla borbotante,

[[job-41-24]]
^24^ Deja tras sí una estela luminosa,

[[job-41-25]]
^25^ No hay en la tierra semejante a él,

[[job-41-26]]
^26^ Mira a la cara a los más altos,
[[job-42]]
== Capítulo 42

[[job-42-1]]
^1^ Y Job respondió a Yahveh:

[[job-42-2]]
^2^ Sé que eres todopoderoso:

[[job-42-3]]
^3^ Era yo el que empañaba el Consejo

[[job-42-4]]
^4^ (Escucha, deja que yo hable:

[[job-42-5]]
^5^ Yo te conocía sólo de oídas,

[[job-42-6]]
^6^ Por eso me retracto y me arrepiento

[[job-42-7]]
^7^ Después de hablar a Job de esta manera, Yahveh dijo a Elifaz de Temán: «Mi ira se ha encendido contra ti y contra tus dos amigos, porque no habéis hablado con verdad de mí, como mi siervo Job.

[[job-42-8]]
^8^ Así que tomad siete novillos y siete carneros, id donde mi siervo Job, y ofreced por vosotros un holocausto. Mi siervo Job intercederá por vosotros y, en atención a él, no os castigaré por no haber hablado con verdad de mí, como mi siervo Job».

[[job-42-9]]
^9^ Elifaz de Temán, Bildad de Sáaj, y Sofar de Naamat fueron a cumplir la orden de Yahveh. Y Yahveh atendió a Job.

[[job-42-10]]
^10^ Después Yahveh restauró la situación de Job, al paso que él intercedía en favor de sus amigos; y aumentó Yahveh al doble todos los bienes de Job.

[[job-42-11]]
^11^ Vinieron, pues, donde él todos sus hermanos y todas sus hermanas, así como todos sus conocidos de antaño; y mientras celebraban con él un banquete en su casa, le compadecieron y le consolaron por todo el infortunio que Yahveh había traído sobre él. Y cada uno de ellos le hizo el obsequio de un agno de plata y de un anillo de oro.

[[job-42-12]]
^12^ Yahveh bendijo la nueva situación de Job más aún que la antigua: llegó a poseer 14.000 ovejas, 6.000 camellos, mil yuntas de bueyes y mil asnas.

[[job-42-13]]
^13^ Tuvo además siete hijos y tres hijas.

[[job-42-14]]
^14^ A la primera le puso el nombre de «Paloma», a la segunda el de «Canela» y a la tercera el de «Cuerno de afeites».

[[job-42-15]]
^15^ No había en todo el país mujeres tan bonitas como las hijas de Job. Y su padre les dio parte en la herencia entre sus hermanos.

[[job-42-16]]
^16^ Después de esto, vivió Job todavía 140 años, y vio a sus hijos y a los hijos de sus hijos, cuatro generaciones.

[[job-42-17]]
^17^ Después Job murió anciano y colmado de días.
