[[psalms]]
= Salmos

[[psalms-1]]
== Capítulo 1

[[psalms-1-1]]
^1^ ¡Dichoso el hombre que no sigue

[[psalms-1-2]]
^2^ mas se complace en la ley de Yahveh,

[[psalms-1-3]]
^3^ Es como un árbol plantado

[[psalms-1-4]]
^4^ ¡No así los impíos, no así!

[[psalms-1-5]]
^5^ Por eso, no resistirán en el Juicio los impíos,

[[psalms-1-6]]
^6^ Porque Yahveh conoce el camino de los justos,
[[psalms-2]]
== Capítulo 2

[[psalms-2-1]]
^1^ ¿Por qué se agitan las naciones,

[[psalms-2-2]]
^2^ Se yerguen los reyes de la tierra,

[[psalms-2-3]]
^3^ «¡Rompamos sus coyundas,

[[psalms-2-4]]
^4^ El que se sienta en los cielos se sonríe,

[[psalms-2-5]]
^5^ Luego en su cólera les habla,

[[psalms-2-6]]
^6^ «Ya tengo yo consagrado a mi rey

[[psalms-2-7]]
^7^ Voy a anunciar el decreto de Yahveh:

[[psalms-2-8]]
^8^ Pídeme, y te daré en herencia las naciones,

[[psalms-2-9]]
^9^ Con cetro de hierro, los quebrantarás,

[[psalms-2-10]]
^10^ Y ahora, reyes, comprended,

[[psalms-2-11]]
^11^ Servid a Yahveh con temor,

[[psalms-2-12]]
^12^ con temblor besad sus pies;
[[psalms-3]]
== Capítulo 3

[[psalms-3-1]]
^1^ Salmo. De David. Cuando huía de su hijo Absalón.

[[psalms-3-2]]
^2^ Yahveh, ¡cuán numerosos son mis adversarios,

[[psalms-3-3]]
^3^ ¡Cuántos los que dicen de mi vida:

[[psalms-3-4]]
^4^ Mas tú, Yahveh, escudo que me ciñes,

[[psalms-3-5]]
^5^ A voz en grito clamo hacia Yahveh,

[[psalms-3-6]]
^6^ Yo me acuesto y me duermo,

[[psalms-3-7]]
^7^ No temo a esas gentes que a millares

[[psalms-3-8]]
^8^ ¡Levántate, Yahveh!

[[psalms-3-9]]
^9^ De Yahveh la salvación.
[[psalms-4]]
== Capítulo 4

[[psalms-4-1]]
^1^ Del maestro de coro. Para instrumentos de cuerda. Salmo. De

[[psalms-4-2]]
^2^ Cuando clamo, respóndeme, oh Dios mi justiciero,

[[psalms-4-3]]
^3^ Vosotros, hombres, ¿hasta cuándo seréis torpes de corazón,

[[psalms-4-4]]
^4^ ¡Sabed que Yahveh mima a su amigo,

[[psalms-4-5]]
^5^ Temblad, y no pequéis;

[[psalms-4-6]]
^6^ Ofreced sacrificios de justicia y confiad en Yahveh.

[[psalms-4-7]]
^7^ Muchos dicen: «¿Quién nos hará ver la dicha?»

[[psalms-4-8]]
^8^ tú has dado a mi corazón más alegría

[[psalms-4-9]]
^9^ En paz, todo a una, yo me acuesto y me duermo,
[[psalms-5]]
== Capítulo 5

[[psalms-5-1]]
^1^ Del maestro de coro. Para flautas. Salmo. De David.

[[psalms-5-2]]
^2^ Escucha mis palabras, Yahveh,

[[psalms-5-3]]
^3^ atiende a la voz de mi clamor,

[[psalms-5-4]]
^4^ Yahveh;

[[psalms-5-5]]
^5^ Pues no eres tú un Dios que se complace en la impiedad,

[[psalms-5-6]]
^6^ No, los arrogantes no resisten

[[psalms-5-7]]
^7^ pierdes a los mentirosos;

[[psalms-5-8]]
^8^ Mas yo, por la abundancia de tu amor,

[[psalms-5-9]]
^9^ Guíame, Yahveh, en tu justicia,

[[psalms-5-10]]
^10^ Que no hay en su boca lealtad,

[[psalms-5-11]]
^11^ Trátalos, oh Dios, como culpables,

[[psalms-5-12]]
^12^ Y se alegren los que a ti se acogen,

[[psalms-5-13]]
^13^ Pues tú bendices al justo, Yahveh,
[[psalms-6]]
== Capítulo 6

[[psalms-6-1]]
^1^ Del maestro de coro. Para instrumentos de cuerda. En octava.

[[psalms-6-2]]
^2^ Yahveh, no me corrijas en tu cólera,

[[psalms-6-3]]
^3^ Tenme piedad, Yahveh, que estoy sin fuerzas,

[[psalms-6-4]]
^4^ desmoronada totalmente mi alma,

[[psalms-6-5]]
^5^ Vuélvete, Yahveh, recobra mi alma,

[[psalms-6-6]]
^6^ Porque, en la muerte, nadie de ti se acuerda;

[[psalms-6-7]]
^7^ Estoy extenuado de gemir,

[[psalms-6-8]]
^8^ mi ojo está corroído por el tedio,

[[psalms-6-9]]
^9^ Apartaos de mí todos los malvados,

[[psalms-6-10]]
^10^ Yahveh ha oído mi súplica,

[[psalms-6-11]]
^11^ ¡Todos mis enemigos, confusos, aterrados,
[[psalms-7]]
== Capítulo 7

[[psalms-7-1]]
^1^ Lamentación. De David. La que cantó a Yahveh a propósito del

[[psalms-7-2]]
^2^ Yahveh, Dios mío, a ti me acojo,

[[psalms-7-3]]
^3^ ¡que no arrebate como un león mi vida

[[psalms-7-4]]
^4^ Yahveh, Dios mío, si algo de esto hice,

[[psalms-7-5]]
^5^ si a mi bienhechor con mal he respondido

[[psalms-7-6]]
^6^ ¡que el enemigo me persiga y me alcance,

[[psalms-7-7]]
^7^ Levántate, Yahveh, en tu cólera,

[[psalms-7-8]]
^8^ Que te rodee la asamblea de las naciones,

[[psalms-7-9]]
^9^ (Yahveh, juez de los pueblos.)

[[psalms-7-10]]
^10^ Haz que cese la maldad de los impíos,

[[psalms-7-11]]
^11^ Dios, el escudo que me cubre,

[[psalms-7-12]]
^12^ Dios, el juez justo,

[[psalms-7-13]]
^13^ para el que no se vuelve.

[[psalms-7-14]]
^14^ para sí solo prepara armas de muerte,

[[psalms-7-15]]
^15^ vedle en su preñez de iniquidad,

[[psalms-7-16]]
^16^ Cavó una fosa, recavó bien hondo,

[[psalms-7-17]]
^17^ revierte su obra en su cabeza,

[[psalms-7-18]]
^18^ Doy gracias a Yahveh por su justicia,
[[psalms-8]]
== Capítulo 8

[[psalms-8-1]]
^1^ Del maestro de coro. Según la... de Gat. Salmo. De David.

[[psalms-8-2]]
^2^ ¡Oh Yahveh, Señor nuestro,

[[psalms-8-3]]
^3^ en boca de los niños, los que aún maman,

[[psalms-8-4]]
^4^ Al ver tu cielo, hechura de tus dedos,

[[psalms-8-5]]
^5^ ¿qué es el hombre para que de él te acuerdes,

[[psalms-8-6]]
^6^ Apenas inferior a un dios le hiciste,

[[psalms-8-7]]
^7^ le hiciste señor de las obras de tus manos,

[[psalms-8-8]]
^8^ ovejas y bueyes, todos juntos,

[[psalms-8-9]]
^9^ y las aves del cielo, y los peces del mar,

[[psalms-8-10]]
^10^ ¡Oh Yahveh, Señor nuestro,
[[psalms-9]]
== Capítulo 9

[[psalms-9-1]]
^1^ Del maestro de coro. Para oboes y arpa. Salmo. De David.

[[psalms-9-2]]
^2^ Te doy gracias, Yahveh, de todo corazón,

[[psalms-9-3]]
^3^ quiero alegrarme y exultar en ti,

[[psalms-9-4]]
^4^ Mis enemigos retroceden,

[[psalms-9-5]]
^5^ pues tú has llevado mi juicio y mi sentencia,

[[psalms-9-6]]
^6^ Has reprimido a las gentes, has perdido al impío,

[[psalms-9-7]]
^7^ acabado el enemigo, todo es ruina sin fin,

[[psalms-9-8]]
^8^ Yahveh se sienta para siempre,

[[psalms-9-9]]
^9^ él juzga al orbe con justicia,

[[psalms-9-10]]
^10^ ¡Sea Yahveh ciudadela para el oprimido,

[[psalms-9-11]]
^11^ Y en ti confíen los que saben tu nombre,

[[psalms-9-12]]
^12^ Salmodiad a Yahveh, que se sienta en Sión,

[[psalms-9-13]]
^13^ que él pide cuentas de la sangre, y de ellos se acuerda,

[[psalms-9-14]]
^14^ Tenme piedad, Yahveh, ve mi aflicción,

[[psalms-9-15]]
^15^ para que yo cuente todas tus alabanzas

[[psalms-9-16]]
^16^ Se hundieron los gentiles en la fosa que hicieron,

[[psalms-9-17]]
^17^ Yahveh se ha dado a conocer, ha hecho justicia,

[[psalms-9-18]]
^18^ ¡Vuelvan los impíos al seol,

[[psalms-9-19]]
^19^ Que no queda olvidado el pobre eternamente,

[[psalms-9-20]]
^20^ ¡Levántate, Yahveh, no triunfe el hombre,

[[psalms-9-21]]
^21^ Infunde tú, Yahveh, en ellos el terror,
[[psalms-10]]
== Capítulo 10

[[psalms-10-1]]
^1^ Lámed ¿Por qué, Yahveh, te quedas lejos,

[[psalms-10-2]]
^2^ Por el orgullo del impío es perseguido el desdichado,

[[psalms-10-3]]
^3^ (Mem.) Sí, el impío se jacta de los antojos de su alma,

[[psalms-10-4]]
^4^ (Nun.) el impío, insolente, no le busca:

[[psalms-10-5]]
^5^ En todo tiempo se afianzan sus caminos,

[[psalms-10-6]]
^6^ Dice en su corazón: «¡Jamás vacilaré!»

[[psalms-10-7]]
^7^ maldice.

[[psalms-10-8]]
^8^ al acecho se aposta entre las cañas

[[psalms-10-9]]
^9^ al acecho escondido como león en su guarida,

[[psalms-10-10]]
^10^ (Sade.) Espía, se agazapa, se encoge,

[[psalms-10-11]]
^11^ dice en su corazón: «Dios se ha olvidado,

[[psalms-10-12]]
^12^ Qof. ¡Levántate, Yahveh, alza tu mano, oh Dios!

[[psalms-10-13]]
^13^ ¿Por qué el impío menosprecia a Dios,

[[psalms-10-14]]
^14^ Res. Lo has visto ya, que la pena y la tristeza

[[psalms-10-15]]
^15^ Sin. ¡Quiebra el brazo del impío, del malvado;

[[psalms-10-16]]
^16^ ¡Yahveh es rey por siempre, por los siglos;

[[psalms-10-17]]
^17^ Tau. El deseo de los humildes escuchas tú, Yahveh,

[[psalms-10-18]]
^18^ para hacer justicia al huérfano, al vejado:
[[psalms-11]]
== Capítulo 11

[[psalms-11-1]]
^1^ Del maestro de coro. De David.

[[psalms-11-2]]
^2^ «He aquí que los impíos tensan su arco,

[[psalms-11-3]]
^3^ Si están en ruinas los cimientos, ¿que puede hacer el

[[psalms-11-4]]
^4^ Yahveh en su Templo santo,

[[psalms-11-5]]
^5^ Yahveh explora al justo y al impío;

[[psalms-11-6]]
^6^ ¡Llueva sobre los impíos brasas y azufre,

[[psalms-11-7]]
^7^ Que es justo Yahveh y lo justo ama,
[[psalms-12]]
== Capítulo 12

[[psalms-12-1]]
^1^ Del maestro de coro. En octava. Salmo. De David.

[[psalms-12-2]]
^2^ ¡Salva, Yahveh, que ya no hay fieles,

[[psalms-12-3]]
^3^ Falsedad sólo dicen, cada cual a su prójimo,

[[psalms-12-4]]
^4^ Arranque Yahveh todo labio tramposo,

[[psalms-12-5]]
^5^ los que dicen: «La lengua es nuestro fuerte,

[[psalms-12-6]]
^6^ Por la opresión de los humildes, por el gemido de los pobres,

[[psalms-12-7]]
^7^ Las palabras de Yahveh son palabras sinceras,

[[psalms-12-8]]
^8^ Tú, Yahveh, los guardarás,

[[psalms-12-9]]
^9^ de todas partes se irán los impíos,
[[psalms-13]]
== Capítulo 13

[[psalms-13-1]]
^1^ Del maestro de coro. Salmo. De David.

[[psalms-13-2]]
^2^ ¿Hasta cuándo, Yahveh, me olvidarás? ¿Por siempre?

[[psalms-13-3]]
^3^ ¿Hasta cuándo tendré congojas en mi alma,

[[psalms-13-4]]
^4^ ¡Mira, respóndeme, Yahveh, Dios mío!

[[psalms-13-5]]
^5^ no diga mi enemigo: «¡Le he podido!»,

[[psalms-13-6]]
^6^ Que yo en tu amor confío;
[[psalms-14]]
== Capítulo 14

[[psalms-14-1]]
^1^ Del maestro de coro. De David.

[[psalms-14-2]]
^2^ Se asoma Yahveh desde los cielos

[[psalms-14-3]]
^3^ Todos ellos están descarriados,

[[psalms-14-4]]
^4^ ¿No aprenderán todos los agentes de mal

[[psalms-14-5]]
^5^ Allí de espanto temblarán

[[psalms-14-6]]
^6^ de los planes del desdichado os burláis.

[[psalms-14-7]]
^7^ ¿Quién traerá de Sión la salvación de Israel?
[[psalms-15]]
== Capítulo 15

[[psalms-15-1]]
^1^ Salmo. De David.

[[psalms-15-2]]
^2^ El que ando sin tacha,

[[psalms-15-3]]
^3^ y no calumnia con su lengua;

[[psalms-15-4]]
^4^ con menosprecio mira al réprobo,

[[psalms-15-5]]
^5^ no presta a usura su dinero,
[[psalms-16]]
== Capítulo 16

[[psalms-16-1]]
^1^ A media voz. De David.

[[psalms-16-2]]
^2^ Yo digo a Yahveh: «Tú eres mi Señor.

[[psalms-16-3]]
^3^ ellos, en cambio, a los santos que hay en la tierra:

[[psalms-16-4]]
^4^ Sus ídolos abundan, tras ellos van corriendo.

[[psalms-16-5]]
^5^ Yahveh, la parte de mi herencia y de mi copa,

[[psalms-16-6]]
^6^ la cuerda me asigna un recinto de delicias,

[[psalms-16-7]]
^7^ Bendigo a Yahveh que me aconseja;

[[psalms-16-8]]
^8^ pongo a Yahveh ante mí sin cesar;

[[psalms-16-9]]
^9^ Por eso se me alegra el corazón, mis entrañas retozan,

[[psalms-16-10]]
^10^ pues no has de abandonar mi alma al seol,

[[psalms-16-11]]
^11^ Me enseñarás el caminó de la vida, hartura de goces, delante
[[psalms-17]]
== Capítulo 17

[[psalms-17-1]]
^1^ Oración. De David.

[[psalms-17-2]]
^2^ Mi juicio saldrá de tu presencia,

[[psalms-17-3]]
^3^ Mi corazón tú sondas, de noche me visitas;

[[psalms-17-4]]
^4^ al modo de los hombres.

[[psalms-17-5]]
^5^ ajustando mis pasos;

[[psalms-17-6]]
^6^ Yo te llamo, que tú, oh Dios, me respondes,

[[psalms-17-7]]
^7^ haz gala de tus gracias, tú que salvas

[[psalms-17-8]]
^8^ Guárdame como la pupila de los ojos,

[[psalms-17-9]]
^9^ de esos impíos que me acosan,

[[psalms-17-10]]
^10^ Están ellos cerrados en su grasa,

[[psalms-17-11]]
^11^ Avanzan contra mí, ya me cercan,

[[psalms-17-12]]
^12^ Son como el león ávido de presa,

[[psalms-17-13]]
^13^ ¡Levántate, Yahveh, hazle frente, derríbale;

[[psalms-17-14]]
^14^ de los mortales, con tu mano, Yahveh,

[[psalms-17-15]]
^15^ Mas yo, en la justicia, contemplaré tu rostro,
[[psalms-18]]
== Capítulo 18

[[psalms-18-1]]
^1^ Del maestro de coro. Del siervo de Yahveh, David, que

[[psalms-18-2]]
^2^ Dijo:

[[psalms-18-3]]
^3^ Yahveh, mi roca y mi baluarte,

[[psalms-18-4]]
^4^ Invoco a Yahveh, que es digno de alabanza,

[[psalms-18-5]]
^5^ Las olas de la muerte me envolvían,

[[psalms-18-6]]
^6^ los lazos del seol me rodeaban,

[[psalms-18-7]]
^7^ Clamé a Yahveh en mi angustia,

[[psalms-18-8]]
^8^ La tierra fue sacudida y vaciló,

[[psalms-18-9]]
^9^ una humareda subió de sus narices,

[[psalms-18-10]]
^10^ El inclinó los cielos y bajó,

[[psalms-18-11]]
^11^ cabalgó sobre un querube, emprendió el vuelo,

[[psalms-18-12]]
^12^ Se puso como tienda un cerco de tinieblas,

[[psalms-18-13]]
^13^ del fulgor que le precedía se encendieron

[[psalms-18-14]]
^14^ Tronó Yahveh en los cielos,

[[psalms-18-15]]
^15^ arrojó saetas, y los puso en fuga,

[[psalms-18-16]]
^16^ El fondo del mar quedó a la vista,

[[psalms-18-17]]
^17^ El extiende su mano de lo alto para asirme,

[[psalms-18-18]]
^18^ me libera de un enemigo poderoso,

[[psalms-18-19]]
^19^ Me aguardaban el día de mi ruina,

[[psalms-18-20]]
^20^ me sacó a espacio abierto,

[[psalms-18-21]]
^21^ Yahveh me recompensa conforme a mi justicia,

[[psalms-18-22]]
^22^ porque he guardado los caminos de Yahveh,

[[psalms-18-23]]
^23^ Porque tengo ante mí todos sus juicios,

[[psalms-18-24]]
^24^ he sido ante él irreprochable,

[[psalms-18-25]]
^25^ Y Yahveh me devuelve según mi justicia,

[[psalms-18-26]]
^26^ Con el piadoso eres piadoso,

[[psalms-18-27]]
^27^ con el puro eres puro,

[[psalms-18-28]]
^28^ tú que salvas al pueblo humilde,

[[psalms-18-29]]
^29^ Tú eres, Yahveh, mi lámpara,

[[psalms-18-30]]
^30^ con tu ayuda las hordas acometo,

[[psalms-18-31]]
^31^ Dios es perfecto en sus caminos,

[[psalms-18-32]]
^32^ Pues ¿quién es Dios fuera de Yahveh?

[[psalms-18-33]]
^33^ El Dios que me ciñe de fuerza,

[[psalms-18-34]]
^34^ que hace mis pies como de ciervas,

[[psalms-18-35]]
^35^ el que mis manos para el combate adiestra

[[psalms-18-36]]
^36^ Tú me das tu escudo salvador,

[[psalms-18-37]]
^37^ mis pasos ensanchas ante mí,

[[psalms-18-38]]
^38^ Persigo a mis enemigos, les doy caza,

[[psalms-18-39]]
^39^ los quebranto, no pueden levantarse,

[[psalms-18-40]]
^40^ Para el combate de fuerza me ciñes,

[[psalms-18-41]]
^41^ a mis enemigos haces dar la espalda,

[[psalms-18-42]]
^42^ Claman, mas no hay salvador,

[[psalms-18-43]]
^43^ Los machaco como polvo al viento,

[[psalms-18-44]]
^44^ De las querellas de mi pueblo tú me libras,

[[psalms-18-45]]
^45^ los hijos de extranjeros me adulan,

[[psalms-18-46]]
^46^ los hijos de extranjeros desmayan,

[[psalms-18-47]]
^47^ ¡Viva Yahveh, bendita sea mi roca,

[[psalms-18-48]]
^48^ el Dios que la venganza me concede

[[psalms-18-49]]
^49^ Tú me libras de mis enemigos,

[[psalms-18-50]]
^50^ Por eso he de alabarte entre los pueblos,

[[psalms-18-51]]
^51^ El hace grandes las victorias de su rey
[[psalms-19]]
== Capítulo 19

[[psalms-19-1]]
^1^ Del maestro de coro. Salmo. De David.

[[psalms-19-2]]
^2^ Los cielos cuentan la gloria de Dios,

[[psalms-19-3]]
^3^ el día al día comunica el mensaje,

[[psalms-19-4]]
^4^ No es un mensaje, no hay palabras,

[[psalms-19-5]]
^5^ mas por toda la tierra se adivinan los rasgos,

[[psalms-19-6]]
^6^ y él, como un esposo que sale de su tálamo,

[[psalms-19-7]]
^7^ A un extremo del cielo es su salida,

[[psalms-19-8]]
^8^ La ley de Yahveh es perfecta,

[[psalms-19-9]]
^9^ Los preceptos de Yahveh son rectos,

[[psalms-19-10]]
^10^ El temor de Yahveh es puro,

[[psalms-19-11]]
^11^ apetecibles más que el oro,

[[psalms-19-12]]
^12^ Por eso tu servidor se empapa en ellos,

[[psalms-19-13]]
^13^ Pero ¿quién se da cuenta de sus yerros?

[[psalms-19-14]]
^14^ Guarda también a tu siervo del orgullo,

[[psalms-19-15]]
^15^ ¡Sean gratas las palabras de mi boca,
[[psalms-20]]
== Capítulo 20

[[psalms-20-1]]
^1^ Del maestro de coro. Salmo. De David.

[[psalms-20-2]]
^2^ ¡Yahveh te responda el día de la angustia,

[[psalms-20-3]]
^3^ El te envíe socorro desde su santuario,

[[psalms-20-4]]
^4^ Se acuerde de todas tus ofrendas,

[[psalms-20-5]]
^5^ te otorgue según tu corazón,

[[psalms-20-6]]
^6^ ¡Y nosotros aclamemos tu victoria,

[[psalms-20-7]]
^7^ Ahora conozco que Yahveh

[[psalms-20-8]]
^8^ Unos con los carros, otros con los caballos,

[[psalms-20-9]]
^9^ Ellos se doblegan y caen,

[[psalms-20-10]]
^10^ ¡Oh Yahveh, salva al rey,
[[psalms-21]]
== Capítulo 21

[[psalms-21-1]]
^1^ Del maestro de coro. Salmo. De David.

[[psalms-21-2]]
^2^ Yahveh, en tu fuerza se regocija el rey;

[[psalms-21-3]]
^3^ Tú le has otorgado el deseo de su corazón,

[[psalms-21-4]]
^4^ Pues le precedes de venturosas bendiciones,

[[psalms-21-5]]
^5^ vida te pidió y se la otorgaste,

[[psalms-21-6]]
^6^ Gran gloria le da tu salvación,

[[psalms-21-7]]
^7^ bendiciones haces de él por siempre,

[[psalms-21-8]]
^8^ Sí, en Yahveh confía el rey,

[[psalms-21-9]]
^9^ Tu mano alcanzará a todos tus enemigos,

[[psalms-21-10]]
^10^ harás de ellos como un horno de fuego,

[[psalms-21-11]]
^11^ harás perecer su fruto de la tierra,

[[psalms-21-12]]
^12^ Aunque ellos intenten daño contra ti,

[[psalms-21-13]]
^13^ Que tú les harás volver la espalda,

[[psalms-21-14]]
^14^ ¡Levántate, Yahveh, con tu poder,
[[psalms-22]]
== Capítulo 22

[[psalms-22-1]]
^1^ Del maestro de coro. Sobre «la cierva de la aurora».

[[psalms-22-2]]
^2^ Dios mío, Dios mío, ¿por qué me has abandonado?

[[psalms-22-3]]
^3^ Dios mío, de día clamo, y no respondes,

[[psalms-22-4]]
^4^ ¡Mas tú eres el Santo,

[[psalms-22-5]]
^5^ En ti esperaron nuestros padres,

[[psalms-22-6]]
^6^ a ti clamaron, y salieron salvos,

[[psalms-22-7]]
^7^ Y yo, gusano, que no hombre,

[[psalms-22-8]]
^8^ todos los que me ven de mí se mofan,

[[psalms-22-9]]
^9^ «Se confió a Yahveh, ¡pues que él le libre,

[[psalms-22-10]]
^10^ Sí, tú del vientre me sacaste,

[[psalms-22-11]]
^11^ a ti fui entregado cuando salí del seno,

[[psalms-22-12]]
^12^ ¡No andes lejos de mí, que la angustia está cerca,

[[psalms-22-13]]
^13^ Novillos innumerables me rodean,

[[psalms-22-14]]
^14^ ávidos abren contra mí sus fauces;

[[psalms-22-15]]
^15^ Como el agua me derramo,

[[psalms-22-16]]
^16^ Está seco mi paladar como una teja

[[psalms-22-17]]
^17^ Perros innumerables me rodean,

[[psalms-22-18]]
^18^ Puedo contar todos mis huesos;

[[psalms-22-19]]
^19^ repártense entre sí mis vestiduras

[[psalms-22-20]]
^20^ ¡Mas tú, Yahveh, no te estés lejos,

[[psalms-22-21]]
^21^ libra mi alma de la espada,

[[psalms-22-22]]
^22^ sálvame de las fauces del león,

[[psalms-22-23]]
^23^ ¡Anunciaré tu nombre a mis hermanos,

[[psalms-22-24]]
^24^ «Los que a Yahveh teméis, dadle alabanza,

[[psalms-22-25]]
^25^ Porque no ha despreciado

[[psalms-22-26]]
^26^ De ti viene mi alabanza en la gran asamblea,

[[psalms-22-27]]
^27^ Los pobres comerán, quedarán hartos,

[[psalms-22-28]]
^28^ Le recordarán y volverán a Yahveh todos los confines de la

[[psalms-22-29]]
^29^ Que es de Yahveh el imperio, del señor de las naciones.

[[psalms-22-30]]
^30^ Ante él solo se postrarán todos los poderosos de la tierra,

[[psalms-22-31]]
^31^ le servirá su descendencia:

[[psalms-22-32]]
^32^ venidera,
[[psalms-23]]
== Capítulo 23

[[psalms-23-1]]
^1^ Salmo. De David.

[[psalms-23-2]]
^2^ Por prados de fresca hierba me apacienta.

[[psalms-23-3]]
^3^ y conforta mi alma;

[[psalms-23-4]]
^4^ Aunque pase por valle tenebroso,

[[psalms-23-5]]
^5^ Tú preparas ante mí una mesa

[[psalms-23-6]]
^6^ Sí, dicha y gracia me acompañarán
[[psalms-24]]
== Capítulo 24

[[psalms-24-1]]
^1^ Salmo. De David.

[[psalms-24-2]]
^2^ que él lo fundó sobre los mares,

[[psalms-24-3]]
^3^ ¿Quién subirá al monte de Yahveh?,

[[psalms-24-4]]
^4^ El de manos limpias y puro corazón,

[[psalms-24-5]]
^5^ El logrará la bendición de Yahveh,

[[psalms-24-6]]
^6^ Tal es la raza de los que le buscan,

[[psalms-24-7]]
^7^ ¡Puertas, levantad vuestros dinteles,

[[psalms-24-8]]
^8^ ¿Quién es ese rey de gloria?

[[psalms-24-9]]
^9^ ¡Puertas, levantad vuestros dinteles,

[[psalms-24-10]]
^10^ ¿Quién es ese rey de gloria?
[[psalms-25]]
== Capítulo 25

[[psalms-25-1]]
^1^ De David

[[psalms-25-2]]
^2^ oh Dios mío.

[[psalms-25-3]]
^3^ Guimel. No hay confusión para el que espera en ti,

[[psalms-25-4]]
^4^ Dálet. Muéstrame tus caminos, Yahveh,

[[psalms-25-5]]
^5^ He. Guíame en tu verdad, enséñame,

[[psalms-25-6]]
^6^ Zain. Acuérdate, Yahveh, de tu ternura,

[[psalms-25-7]]
^7^ Jet. De los pecados de mi juventud no te acuerdes,

[[psalms-25-8]]
^8^ Tet. Bueno y recto es Yahveh;

[[psalms-25-9]]
^9^ Yod. conduce en la justicia a los humildes,

[[psalms-25-10]]
^10^ Kaf. Todas las sendas de Yahveh son amor y verdad

[[psalms-25-11]]
^11^ Lámed. Por tu nombre, oh Yahveh,

[[psalms-25-12]]
^12^ Mem. Si hay un hombre que tema a Yahveh,

[[psalms-25-13]]
^13^ Nun. su alma mora en la felicidad,

[[psalms-25-14]]
^14^ Sámek. El secreto de Yahveh es para quienes le temen,

[[psalms-25-15]]
^15^ Ain. Mis ojos están fijos en Yahveh,

[[psalms-25-16]]
^16^ Pe. Vuélvete a mí, tenme piedad,

[[psalms-25-17]]
^17^ Sade. Alivia los ahogos de mi corazón,

[[psalms-25-18]]
^18^ (Qof.) Ve mi aflicción y mi penar,

[[psalms-25-19]]
^19^ Res. Mira cuántos son mis enemigos,

[[psalms-25-20]]
^20^ Sin. Garda mi alma, líbrame,

[[psalms-25-21]]
^21^ Tau. Inocencia y rectitud me amparen,

[[psalms-25-22]]
^22^ Redime, oh Dios, a Israel
[[psalms-26]]
== Capítulo 26

[[psalms-26-1]]
^1^ De David.

[[psalms-26-2]]
^2^ Escrútame, Yahveh, ponme a prueba,

[[psalms-26-3]]
^3^ está tu amor delante de mis ojos,

[[psalms-26-4]]
^4^ No voy a sentarme con los falsos,

[[psalms-26-5]]
^5^ odio la asamblea de malhechores,

[[psalms-26-6]]
^6^ Mis manos lavo en la inocencia

[[psalms-26-7]]
^7^ haciendo resonar la acción de gracias,

[[psalms-26-8]]
^8^ amo, Yahveh, la belleza de tu Casa,

[[psalms-26-9]]
^9^ No juntes mi alma con los pecadores,

[[psalms-26-10]]
^10^ que tienen en sus manos la infamia,

[[psalms-26-11]]
^11^ Yo, en cambio, camino en mi entereza;

[[psalms-26-12]]
^12^ mi pie está firme en suelo llano;
[[psalms-27]]
== Capítulo 27

[[psalms-27-1]]
^1^ De David.

[[psalms-27-2]]
^2^ Cuando se acercan contra mí los malhechores

[[psalms-27-3]]
^3^ Aunque acampe contra mí un ejército,

[[psalms-27-4]]
^4^ Una cosa he pedido a Yahveh,

[[psalms-27-5]]
^5^ Que él me dará cobijo en su cabaña

[[psalms-27-6]]
^6^ Y ahora se alza mi cabeza

[[psalms-27-7]]
^7^ Escucha, Yahveh, mi voz que clama,

[[psalms-27-8]]
^8^ Dice de ti mi corazón:

[[psalms-27-9]]
^9^ No me ocultes tu rostro.

[[psalms-27-10]]
^10^ Si mi padre y mi madre me abandonan,

[[psalms-27-11]]
^11^ Enséñame tu camino, Yahveh,

[[psalms-27-12]]
^12^ no me entregues al ansia de mis adversarios,

[[psalms-27-13]]
^13^ ¡Ay, si estuviera seguro de ver la bondad de Yahveh

[[psalms-27-14]]
^14^ Espera en Yahveh, ten valor y firme corazón,
[[psalms-28]]
== Capítulo 28

[[psalms-28-1]]
^1^ De David.

[[psalms-28-2]]
^2^ Oye la voz de mis plegarias,

[[psalms-28-3]]
^3^ No me arrebates con los impíos,

[[psalms-28-4]]
^4^ Dales, Yahveh, conforme a sus acciones,

[[psalms-28-5]]
^5^ Pues no comprenden los hechos de Yahveh,

[[psalms-28-6]]
^6^ ¡Bendito sea Yahveh, que ha oído

[[psalms-28-7]]
^7^ Yahveh mi fuerza, escudo mío,

[[psalms-28-8]]
^8^ Yahveh, fuerza de su pueblo,

[[psalms-28-9]]
^9^ Salva a tu pueblo, bendice a tu heredad,
[[psalms-29]]
== Capítulo 29

[[psalms-29-1]]
^1^ Salmo. De David.

[[psalms-29-2]]
^2^ Rendid a Yahveh la gloria de su nombre,

[[psalms-29-3]]
^3^ Voz de Yahveh sobre las aguas;

[[psalms-29-4]]
^4^ Voz de Yahveh con fuerza,

[[psalms-29-5]]
^5^ Voz de Yahveh que desgaja los cedros,

[[psalms-29-6]]
^6^ hace brincar como un novillo al Líbano,

[[psalms-29-7]]
^7^ Voz de Yahveh que afila llamaradas.

[[psalms-29-8]]
^8^ Voz de Yahveh, que sacude el desierto,

[[psalms-29-9]]
^9^ Voz de Yahveh, que estremece las encinas,

[[psalms-29-10]]
^10^ Yahveh se sentó para el diluvio,

[[psalms-29-11]]
^11^ Yahveh da el poder a su pueblo,
[[psalms-30]]
== Capítulo 30

[[psalms-30-1]]
^1^ Salmo. Cántico para la dedicación de la Casa. De David.

[[psalms-30-2]]
^2^ Yo te ensalzo, Yahveh, porque me has levantado;

[[psalms-30-3]]
^3^ Yahveh, Dios mío, clamé a ti y me sanaste.

[[psalms-30-4]]
^4^ Tú has sacado, Yahveh, mi alma del seol,

[[psalms-30-5]]
^5^ Salmodiad a Yahveh los que le amáis,

[[psalms-30-6]]
^6^ De un instante es su cólera, de toda una vida su favor;

[[psalms-30-7]]
^7^ Y yo en mi paz decía:

[[psalms-30-8]]
^8^ Yahveh, tu favor me afianzaba sobre fuertes montañas;

[[psalms-30-9]]
^9^ A ti clamo, Yahveh,

[[psalms-30-10]]
^10^ ¿Qué ganancia en mi sangre, en que baje a la fosa?

[[psalms-30-11]]
^11^ ¡Escucha, Yahveh, y ten piedad de mí!

[[psalms-30-12]]
^12^ Has trocado mi lamento en una danza,

[[psalms-30-13]]
^13^ mi corazón por eso te salmodiará sin tregua;
[[psalms-31]]
== Capítulo 31

[[psalms-31-1]]
^1^ Del maestro de coro. Salmo. De David.

[[psalms-31-2]]
^2^ En ti, Yahveh, me cobijo,

[[psalms-31-3]]
^3^ tiende hacia mí tu oído, date prisa!

[[psalms-31-4]]
^4^ pues mi roca eres tú, mi fortaleza,

[[psalms-31-5]]
^5^ Sácame de la red que me han tendido,

[[psalms-31-6]]
^6^ en tus manos mi espíritu encomiendo,

[[psalms-31-7]]
^7^ tú detestas

[[psalms-31-8]]
^8^ ¡exulte yo y en tu amor me regocije!

[[psalms-31-9]]
^9^ no me has entregado en manos del enemigo,

[[psalms-31-10]]
^10^ Tenme piedad, Yahveh,

[[psalms-31-11]]
^11^ Pues mi vida se consume en aflicción,

[[psalms-31-12]]
^12^ De todos mis opresores

[[psalms-31-13]]
^13^ dejado estoy de la memoria como un muerto,

[[psalms-31-14]]
^14^ Escucho las calumnias de la turba,

[[psalms-31-15]]
^15^ Mas yo confío en ti, Yahveh,

[[psalms-31-16]]
^16^ Está en tus manos mi destino, líbrame

[[psalms-31-17]]
^17^ haz que alumbre a tu siervo tu semblante,

[[psalms-31-18]]
^18^ Yahveh, no haya confusión para mí, que te invoco,

[[psalms-31-19]]
^19^ enmudezcan los labios mentirosos

[[psalms-31-20]]
^20^ ¡Qué grande es tu bondad, Yahveh!

[[psalms-31-21]]
^21^ Tú los escondes en el secreto de tu rostro,

[[psalms-31-22]]
^22^ ¡Bendito sea Yahveh que me ha brindado

[[psalms-31-23]]
^23^ ¡Y yo que decía en mi inquietud:

[[psalms-31-24]]
^24^ Amad a Yahveh, todos sus amigos;

[[psalms-31-25]]
^25^ ¡Valor, que vuestro corazón se afirme,
[[psalms-32]]
== Capítulo 32

[[psalms-32-1]]
^1^ De David. Poema.

[[psalms-32-2]]
^2^ Dichoso el hombre a quien Yahveh

[[psalms-32-3]]
^3^ Cuando yo me callaba, se sumían mis huesos

[[psalms-32-4]]
^4^ mientras pesaba, día y noche,

[[psalms-32-5]]
^5^ Mi pecado te reconocí,

[[psalms-32-6]]
^6^ Por eso te suplica todo el que te ama

[[psalms-32-7]]
^7^ Tú eres un cobijo para mí,

[[psalms-32-8]]
^8^ Voy a instruirte, a mostrarte el camino a seguir;

[[psalms-32-9]]
^9^ No seas cual caballo o mulo sin sentido,

[[psalms-32-10]]
^10^ Copiosas son las penas del impío,

[[psalms-32-11]]
^11^ ¡Alegraos en Yahveh,
[[psalms-33]]
== Capítulo 33

[[psalms-33-1]]
^1^ ¡Gritad de júbilo, justos, por Yahveh!,

[[psalms-33-2]]
^2^ ¡dad gracias a Yahveh con la cítara,

[[psalms-33-3]]
^3^ cantadle un cantar nuevo,

[[psalms-33-4]]
^4^ Pues recta es la palabra de Yahveh,

[[psalms-33-5]]
^5^ él ama la justicia y el derecho,

[[psalms-33-6]]
^6^ Por la palabra de Yahveh fueron hechos los cielos

[[psalms-33-7]]
^7^ El recoge, como un dique, las aguas del mar,

[[psalms-33-8]]
^8^ ¡Tema a Yahveh la tierra entera,

[[psalms-33-9]]
^9^ Pues él habló y fue así,

[[psalms-33-10]]
^10^ Yahveh frustra el plan de las naciones,

[[psalms-33-11]]
^11^ mas el plan de Yahveh subsiste para siempre,

[[psalms-33-12]]
^12^ ¡Feliz la nación cuyo Dios es Yahveh,

[[psalms-33-13]]
^13^ Yahveh mira de lo alto de los cielos,

[[psalms-33-14]]
^14^ desde el lugar de su morada observa

[[psalms-33-15]]
^15^ él, que forma el corazón de cada uno,

[[psalms-33-16]]
^16^ No queda a salvo el rey por su gran ejército,

[[psalms-33-17]]
^17^ Vana cosa el caballo para la victoria,

[[psalms-33-18]]
^18^ Los ojos de Yahveh están sobre quienes le temen,

[[psalms-33-19]]
^19^ para librar su alma de la muerte,

[[psalms-33-20]]
^20^ Nuestra alma en Yahveh espera,

[[psalms-33-21]]
^21^ en él se alegra nuestro corazón,

[[psalms-33-22]]
^22^ Sea tu amor, Yahveh, sobre nosotros,
[[psalms-34]]
== Capítulo 34

[[psalms-34-1]]
^1^ De David. Cuando fingiéndose demente ante Abimélek, fue

[[psalms-34-2]]
^2^ Alef. Bendeciré a Yahveh en todo tiempo,

[[psalms-34-3]]
^3^ Bet. en Yahveh mi alma se gloría,

[[psalms-34-4]]
^4^ Guimel. Engrandeced conmigo a Yahveh,

[[psalms-34-5]]
^5^ Dálet. He buscado a Yahveh, y me ha respondido:

[[psalms-34-6]]
^6^ He. Los que miran hacia él, refulgirán:

[[psalms-34-7]]
^7^ Zain. Cuando el pobre grita, Yahveh oye,

[[psalms-34-8]]
^8^ Jet. Acampa el ángel de Yahveh

[[psalms-34-9]]
^9^ Tet. Gustad y ved qué bueno es Yahveh,

[[psalms-34-10]]
^10^ Yod. Temed a Yahveh vosotros, santos suyos,

[[psalms-34-11]]
^11^ Kaf. Los ricos quedan pobres y hambrientos,

[[psalms-34-12]]
^12^ Lámed. Venid, hijos, oídme,

[[psalms-34-13]]
^13^ Mem. ¿Quién es el hombre que apetece la vida,

[[psalms-34-14]]
^14^ Nun. Guarda del mal tu lengua,

[[psalms-34-15]]
^15^ Sámek. apártate del mal y obra el bien,

[[psalms-34-16]]
^16^ Ain. Los ojos de Yahveh sobre los justos,

[[psalms-34-17]]
^17^ Pe el rostro de Yahveh contra los malhechores,

[[psalms-34-18]]
^18^ Sade. Cuando gritan aquéllos, Yahveh oye,

[[psalms-34-19]]
^19^ Qof. Yahveh está cerca de los que tienen roto el corazón.

[[psalms-34-20]]
^20^ Res. Muchas son las desgracias del justo,

[[psalms-34-21]]
^21^ Sin. todos sus huesos guarda,

[[psalms-34-22]]
^22^ Tau. La malicia matará al impío,

[[psalms-34-23]]
^23^ Yahveh rescata el alma de sus siervos,
[[psalms-35]]
== Capítulo 35

[[psalms-35-1]]
^1^ De David.

[[psalms-35-2]]
^2^ embraza el escudo y el pavés,

[[psalms-35-3]]
^3^ blande la lanza y la pica

[[psalms-35-4]]
^4^ ¡Confusión y vergüenza sobre aquellos

[[psalms-35-5]]
^5^ ¡Sean lo mismo que la paja al viento,

[[psalms-35-6]]
^6^ sea su camino tiniebla y precipicio,

[[psalms-35-7]]
^7^ Pues sin causa me han tendido su red,

[[psalms-35-8]]
^8^ ¡Sobre cada uno de ellos caiga de improviso la ruina:

[[psalms-35-9]]
^9^ Y mi alma exultará en Yahveh,

[[psalms-35-10]]
^10^ Dirán todos mis huesos:

[[psalms-35-11]]
^11^ Testigos falsos se levantan,

[[psalms-35-12]]
^12^ me pagan mal por bien,

[[psalms-35-13]]
^13^ Yo, en cambio, cuando eran ellos los enfermos, vestido de

[[psalms-35-14]]
^14^ como por un amigo o un hermano iba y venía,

[[psalms-35-15]]
^15^ Ellos se ríen de mi caída, se reúnen,

[[psalms-35-16]]
^16^ si caigo, me rodean

[[psalms-35-17]]
^17^ ¿Cuánto tiempo, Señor, te quedarás mirando?

[[psalms-35-18]]
^18^ Te daré gracias en la gran asamblea,

[[psalms-35-19]]
^19^ No se rían de mí,

[[psalms-35-20]]
^20^ Pues no es de paz de lo que hablan

[[psalms-35-21]]
^21^ abren bien grande su boca contra mí;

[[psalms-35-22]]
^22^ Tú lo has visto, Yahveh, no te quedes callado,

[[psalms-35-23]]
^23^ despiértate, levántate a mi juicio,

[[psalms-35-24]]
^24^ júzgame conforme a tu justicia, oh Yahveh,

[[psalms-35-25]]
^25^ No digan en su corazón: «¡Ajá, lo que queríamos!»

[[psalms-35-26]]
^26^ ¡Vergüenza y confusión caigan a una

[[psalms-35-27]]
^27^ Exulten y den gritos de júbilo

[[psalms-35-28]]
^28^ Y tu justicia musitará mi lengua,
[[psalms-36]]
== Capítulo 36

[[psalms-36-1]]
^1^ Del maestro de coro. Del siervo de Yahveh. De David.

[[psalms-36-2]]
^2^ Un oráculo para el impío es el pecado

[[psalms-36-3]]
^3^ Con ojo harto lisonjero se mira,

[[psalms-36-4]]
^4^ las palabras de su boca, iniquidad y engaño;

[[psalms-36-5]]
^5^ Sólo maquina iniquidad

[[psalms-36-6]]
^6^ Oh Yahveh, en los cielos tu amor,

[[psalms-36-7]]
^7^ tu justicia, como los montes de Dios,

[[psalms-36-8]]
^8^ oh Dios, ¡qué precioso tu amor!

[[psalms-36-9]]
^9^ Se sacian de la grasa de tu Casa,

[[psalms-36-10]]
^10^ en ti está la fuente de la vida,

[[psalms-36-11]]
^11^ Guarda tu amor a los que te conocen,

[[psalms-36-12]]
^12^ ¡Que el pie del orgullo no me alcance,

[[psalms-36-13]]
^13^ Ved cómo caen los agentes de mal,
[[psalms-37]]
== Capítulo 37

[[psalms-37-1]]
^1^ De David.

[[psalms-37-2]]
^2^ Pues aridecen presto como el heno,

[[psalms-37-3]]
^3^ Bet. Ten confianza en Yahveh y obra el bien,

[[psalms-37-4]]
^4^ ten tus delicias en Yahveh,

[[psalms-37-5]]
^5^ Guimel. Pon tu suerte en Yahveh,

[[psalms-37-6]]
^6^ hará brillar como la luz tu justicia,

[[psalms-37-7]]
^7^ Dálet. Vive en calma ante Yahveh, espera en él,

[[psalms-37-8]]
^8^ He. Desiste de la cólera y abandona el enojo,

[[psalms-37-9]]
^9^ pues serán extirpados los malvados,

[[psalms-37-10]]
^10^ Vau. Un poco más, y no hay impío,

[[psalms-37-11]]
^11^ mas poseerán la tierra los humildes,

[[psalms-37-12]]
^12^ Zain. El impío maquina contra el justo,

[[psalms-37-13]]
^13^ el Señor de él se ríe,

[[psalms-37-14]]
^14^ Jet. Desenvainan la espada los impíos,

[[psalms-37-15]]
^15^ su espada entrará en su propio corazón,

[[psalms-37-16]]
^16^ Tet. Lo poco del justo vale más

[[psalms-37-17]]
^17^ pues los brazos de los impíos serán rotos,

[[psalms-37-18]]
^18^ Yod. Yahveh conoce los días de los íntegros,

[[psalms-37-19]]
^19^ no serán confundidos en tiempo de desgracia,

[[psalms-37-20]]
^20^ Kaf. Perecerán, en cambio, los impíos,

[[psalms-37-21]]
^21^ Lámed. Toma el impío prestado y no devuelve,

[[psalms-37-22]]
^22^ los que él bendice poseerán la tierra,

[[psalms-37-23]]
^23^ Mem. De Yahveh penden los pasos del hombre,

[[psalms-37-24]]
^24^ aunque caiga, no se queda postrado,

[[psalms-37-25]]
^25^ Nun. Fui joven, ya soy viejo,

[[psalms-37-26]]
^26^ En todo tiempo es compasivo y presta,

[[psalms-37-27]]
^27^ Sámek. Apártate del mal y obra el bien,

[[psalms-37-28]]
^28^ porque Yahveh ama lo que es justo

[[psalms-37-29]]
^29^ los justos poseerán la tierra,

[[psalms-37-30]]
^30^ La boca del justo sabiduría susurra,

[[psalms-37-31]]
^31^ la ley de su Dios está en su corazón,

[[psalms-37-32]]
^32^ Espía el impío al justo,

[[psalms-37-33]]
^33^ en su mano Yahveh no le abandona,

[[psalms-37-34]]
^34^ Espera en Yahveh y guarda su camino,

[[psalms-37-35]]
^35^ He visto al impío muy arrogante

[[psalms-37-36]]
^36^ pasé de nuevo y ya no estaba,

[[psalms-37-37]]
^37^ Observa al perfecto, mira al íntegro:

[[psalms-37-38]]
^38^ pero los rebeldes serán a una aniquilados,

[[psalms-37-39]]
^39^ La salvación de los justos viene de Yahveh,

[[psalms-37-40]]
^40^ Yahveh los ayuda y los libera,
[[psalms-38]]
== Capítulo 38

[[psalms-38-1]]
^1^ Salmo De David. En memoria.

[[psalms-38-2]]
^2^ Yahveh, no me corrijas en tu enojo,

[[psalms-38-3]]
^3^ Pues en mí se han clavado tus saetas,

[[psalms-38-4]]
^4^ nada intacto en mi carne por tu enojo,

[[psalms-38-5]]
^5^ Mis culpas sobrepasan mi cabeza,

[[psalms-38-6]]
^6^ mis llagas son hedor y putridez,

[[psalms-38-7]]
^7^ encorvado, abatido totalmente,

[[psalms-38-8]]
^8^ Están mis lomos túmidos de fiebre,

[[psalms-38-9]]
^9^ entumecido, molido totalmente,

[[psalms-38-10]]
^10^ Señor, todo mi anhelo ante tus ojos,

[[psalms-38-11]]
^11^ Me traquetea el corazón, las fuerzas me abandonan,

[[psalms-38-12]]
^12^ Mis amigos y compañeros se partan de mi llaga,

[[psalms-38-13]]
^13^ y tienden lazos los que buscan mi alma,

[[psalms-38-14]]
^14^ Mas yo como un sordo soy, no oigo,

[[psalms-38-15]]
^15^ sí, soy como un hombre que no oye,

[[psalms-38-16]]
^16^ Que en ti, Yahveh, yo espero,

[[psalms-38-17]]
^17^ He dicho: «! No se rían de mí,

[[psalms-38-18]]
^18^ Y ahora ya estoy a punto de caída,

[[psalms-38-19]]
^19^ Sí, mi culpa confieso,

[[psalms-38-20]]
^20^ Aumentan mis enemigos sin razón,

[[psalms-38-21]]
^21^ los que me devuelven mal por bien

[[psalms-38-22]]
^22^ ¡No me abandones, tú, Yahveh,

[[psalms-38-23]]
^23^ Date prisa a auxiliarme,
[[psalms-39]]
== Capítulo 39

[[psalms-39-1]]
^1^ Del maestro de coro. De Yedutún. Salmo. De David.

[[psalms-39-2]]
^2^ Yo me decía: «Guardaré mis caminos,

[[psalms-39-3]]
^3^ Enmudecí, quedé en silencio y calma:

[[psalms-39-4]]
^4^ Dentro de mí mi corazón se acaloraba,

[[psalms-39-5]]
^5^ «Hazme saber, Yahveh, mi fin,

[[psalms-39-6]]
^6^ «Oh sí, de unos palmos hiciste mis días,

[[psalms-39-7]]
^7^ nada más una sombra el humano que pasa,

[[psalms-39-8]]
^8^ Y ahora, Señor, ¿qué puedo yo esperar?

[[psalms-39-9]]
^9^ De todas mis rebeldías líbrame,

[[psalms-39-10]]
^10^ Me callo ya, no abro la boca,

[[psalms-39-11]]
^11^ Retira de mí tus golpes,

[[psalms-39-12]]
^12^ Reprendiendo sus yerros tú corriges al hombre,

[[psalms-39-13]]
^13^ «Escucha mi súplica, Yahveh,

[[psalms-39-14]]
^14^ ¡Retira tu mirada para que respire
[[psalms-40]]
== Capítulo 40

[[psalms-40-1]]
^1^ Del maestro de coro. De David. Salmo.

[[psalms-40-2]]
^2^ En Yahveh puse toda mi esperanza,

[[psalms-40-3]]
^3^ Me sacó de la fosa fatal,

[[psalms-40-4]]
^4^ Puso en mi boca un canto nuevo,

[[psalms-40-5]]
^5^ Dichoso el hombre aquel

[[psalms-40-6]]
^6^ ¡Cuántas maravillas has hecho,

[[psalms-40-7]]
^7^ Ni sacrificio ni oblación querías,

[[psalms-40-8]]
^8^ dije entonces: Heme aquí, que vengo.

[[psalms-40-9]]
^9^ hacer tu voluntad.

[[psalms-40-10]]
^10^ He publicado la justicia

[[psalms-40-11]]
^11^ No he escondido tu justicia en el fondo de mi corazón,

[[psalms-40-12]]
^12^ Y tú, Yahveh, no contengas

[[psalms-40-13]]
^13^ Pues desdichas me envuelven

[[psalms-40-14]]
^14^ ¡Dígnate, oh Yahveh, librarme,

[[psalms-40-15]]
^15^ ¡Queden avergonzados y confusos todos juntos

[[psalms-40-16]]
^16^ Queden consternados de vergüenza

[[psalms-40-17]]
^17^ ¡En ti se gocen y se alegren

[[psalms-40-18]]
^18^ Y yo, pobre soy y desdichado,
[[psalms-41]]
== Capítulo 41

[[psalms-41-1]]
^1^ Del maestro de coro. Salmo. De David.

[[psalms-41-2]]
^2^ ¡Dichoso el que cuida del débil y del pobre!

[[psalms-41-3]]
^3^ Yahveh le guarda, vida y dicha en la tierra le depara,

[[psalms-41-4]]
^4^ le sostiene Yahveh en su lecho de dolor;

[[psalms-41-5]]
^5^ Yo he dicho: «Tenme piedad, Yahveh,

[[psalms-41-6]]
^6^ Mis enemigos hablan mal contra mí:

[[psalms-41-7]]
^7^ Si alguien viene a verme, habla de cosas fútiles,

[[psalms-41-8]]
^8^ A una cuchichean contra mí todos los que me odian,

[[psalms-41-9]]
^9^ «Cosa de infierno ha caído sobre él,

[[psalms-41-10]]
^10^ Hasta mi amigo íntimo en quien yo confiaba,

[[psalms-41-11]]
^11^ Mas tú, Yahveh, tenme piedad,

[[psalms-41-12]]
^12^ en esto sabré que tú eres mi amigo:

[[psalms-41-13]]
^13^ y a mí me mantendrás en mi inocencia,

[[psalms-41-14]]
^14^ ¡Bendito sea Yahveh, Dios de Israel,
[[psalms-42]]
== Capítulo 42

[[psalms-42-1]]
^1^ Del maestro de coro. Poema. De los hijos de Coré.

[[psalms-42-2]]
^2^ Como jadea la cierva,

[[psalms-42-3]]
^3^ Tiene mi alma sed de Dios,

[[psalms-42-4]]
^4^ ¡Son mis lágrimas mi pan,

[[psalms-42-5]]
^5^ Yo lo recuerdo, y derramo

[[psalms-42-6]]
^6^ ¿Por qué, alma mía, desfalleces

[[psalms-42-7]]
^7^ mi Dios!

[[psalms-42-8]]
^8^ Abismo que llama al abismo,

[[psalms-42-9]]
^9^ De día mandará

[[psalms-42-10]]
^10^ Diré a Dios mi Roca:

[[psalms-42-11]]
^11^ Con quebranto en mis huesos

[[psalms-42-12]]
^12^ ¿Por qué, alma mía, desfalleces
[[psalms-43]]
== Capítulo 43

[[psalms-43-1]]
^1^ Hazme justicia, oh Dios, y mi causa defiende

[[psalms-43-2]]
^2^ Tú el Dios de mi refugio:

[[psalms-43-3]]
^3^ Envía tu luz y tu verdad,

[[psalms-43-4]]
^4^ Y llegaré al altar de Dios,

[[psalms-43-5]]
^5^ ¿Por qué, alma mía, desfalleces
[[psalms-44]]
== Capítulo 44

[[psalms-44-1]]
^1^ Del maestro de coro. De los hijos de Coré. Poema.

[[psalms-44-2]]
^2^ Oh Dios, con nuestros propios oídos lo oímos,

[[psalms-44-3]]
^3^ y con tu propia mano.

[[psalms-44-4]]
^4^ no por su espada conquistaron la tierra,

[[psalms-44-5]]
^5^ Tú sólo, oh Rey mío, Dios mío,

[[psalms-44-6]]
^6^ por ti nosotros hundíamos a nuestros adversarios,

[[psalms-44-7]]
^7^ No estaba en mi arco mi confianza,

[[psalms-44-8]]
^8^ que tú nos salvabas de nuestros adversarios,

[[psalms-44-9]]
^9^ en Dios todo el día nos gloriábamos,

[[psalms-44-10]]
^10^ Y con todo, nos has rechazado y confundido,

[[psalms-44-11]]
^11^ nos haces dar la espalda al adversario,

[[psalms-44-12]]
^12^ Como ovejas de matadero nos entregas,

[[psalms-44-13]]
^13^ vendes tu pueblo sin ventaja,

[[psalms-44-14]]
^14^ De nuestros vecinos nos haces la irrisión,

[[psalms-44-15]]
^15^ mote nos haces entre las naciones,

[[psalms-44-16]]
^16^ Todo el día mi ignominia está ante mí,

[[psalms-44-17]]
^17^ bajo los gritos de insulto y de blasfemia,

[[psalms-44-18]]
^18^ Nos llegó todo esto sin haberte olvidado,

[[psalms-44-19]]
^19^ ¡No habían vuelto atrás nuestros corazones,

[[psalms-44-20]]
^20^ para que tú nos aplastaras en morada de chacales,

[[psalms-44-21]]
^21^ Si hubiésemos olvidado el nombre de nuestro Dios

[[psalms-44-22]]
^22^ ¿no se habría dado cuenta Dios,

[[psalms-44-23]]
^23^ Pero por ti se nos mata cada día,

[[psalms-44-24]]
^24^ ¡Despierta ya! ¿Por qué duermes, Señor?

[[psalms-44-25]]
^25^ ¿Por qué ocultas tu rostro,

[[psalms-44-26]]
^26^ Pues nuestra alma está hundida en el polvo,

[[psalms-44-27]]
^27^ ¡Alzate, ven en nuestra ayuda,
[[psalms-45]]
== Capítulo 45

[[psalms-45-1]]
^1^ Del maestro de coro. Según la melodía: «Lirios..». De los

[[psalms-45-2]]
^2^ Bulle mi corazón de palabras graciosas;

[[psalms-45-3]]
^3^ Eres hermoso, el más hermoso de los hijos de Adán,

[[psalms-45-4]]
^4^ Ciñe tu espada a tu costado, oh bravo,

[[psalms-45-5]]
^5^ marcha, cabalga,

[[psalms-45-6]]
^6^ Agudas son tus flechas, bajo tus pies están los pueblos,

[[psalms-45-7]]
^7^ Tu trono es de Dios para siempre jamás;

[[psalms-45-8]]
^8^ tú amas la justicia y odias la impiedad.

[[psalms-45-9]]
^9^ mirra y áloe y casia son todos tus vestidos.

[[psalms-45-10]]
^10^ Hijas de reyes hay entre tus preferidas;

[[psalms-45-11]]
^11^ Escucha, hija, mira y pon atento oído,

[[psalms-45-12]]
^12^ y el rey se prendará de tu belleza.

[[psalms-45-13]]
^13^ La hija de Tiro con presentes,

[[psalms-45-14]]
^14^ Toda espléndida, la hija del rey, va adentro,

[[psalms-45-15]]
^15^ con sus brocados el llevada ante el rey.

[[psalms-45-16]]
^16^ entre alborozo y regocijo avanzan,

[[psalms-45-17]]
^17^ En lugar de tus padres, tendrás hijos;

[[psalms-45-18]]
^18^ ¡Logre yo hacer tu nombre memorable por todas las
[[psalms-46]]
== Capítulo 46

[[psalms-46-1]]
^1^ Del maestro de coro. De los hijos de Coré. Para oboes.

[[psalms-46-2]]
^2^ Dios es para nosotros refugio y fortaleza,

[[psalms-46-3]]
^3^ Por eso no tememos si se altera la tierra,

[[psalms-46-4]]
^4^ aunque sus aguas bramen y borboten,

[[psalms-46-5]]
^5^ ¡Un río! Sus brazos recrean la ciudad de Dios,

[[psalms-46-6]]
^6^ Dios está en medio de ella, no será conmovida,

[[psalms-46-7]]
^7^ Braman las naciones, se tambalean los reinos,

[[psalms-46-8]]
^8^ ¡Con nosotros Yahveh Sebaot,

[[psalms-46-9]]
^9^ Venid a contemplar los prodigios de Yahveh,

[[psalms-46-10]]
^10^ Hace cesar las guerras hasta el extremo de la tierra;

[[psalms-46-11]]
^11^ «¡Basta ya; sabed que yo soy Dios,

[[psalms-46-12]]
^12^ ¡Con nosotros Yahveh Sebaot,
[[psalms-47]]
== Capítulo 47

[[psalms-47-1]]
^1^ Del maestro de coro. De los hijos de Coré. Salmo.

[[psalms-47-2]]
^2^ ¡Pueblos todos, batid palmas,

[[psalms-47-3]]
^3^ Porque Yahveh, el Altísimo, es terrible,

[[psalms-47-4]]
^4^ El somete a nuestro yugo los pueblos,

[[psalms-47-5]]
^5^ él nos escoge nuestra herencia,

[[psalms-47-6]]
^6^ Sube Dios entre aclamaciones,

[[psalms-47-7]]
^7^ ¡salmodiad para nuestro Dios, salmodiad,

[[psalms-47-8]]
^8^ Que de toda la tierra él es el rey:

[[psalms-47-9]]
^9^ Reina Dios sobre las naciones,

[[psalms-47-10]]
^10^ Los príncipes de los pueblos se reúnen
[[psalms-48]]
== Capítulo 48

[[psalms-48-1]]
^1^ Cántico. Salmo. De los hijos de Coré.

[[psalms-48-2]]
^2^ Grande es Yahveh, y muy digno de loa

[[psalms-48-3]]
^3^ de gallarda esbeltez,

[[psalms-48-4]]
^4^ Dios, desde sus palacios,

[[psalms-48-5]]
^5^ He aquí que los reyes se habían aliado,

[[psalms-48-6]]
^6^ apenas vieron, de golpe estupefactos,

[[psalms-48-7]]
^7^ Allí un temblor les invadió,

[[psalms-48-8]]
^8^ tal el viento del este que destroza

[[psalms-48-9]]
^9^ Como habíamos oído lo hemos visto

[[psalms-48-10]]
^10^ Tu amor, oh Dios, evocamos

[[psalms-48-11]]
^11^ ¡como tu nombre, oh Dios, tu alabanza

[[psalms-48-12]]
^12^ el monte Sión se regocija,

[[psalms-48-13]]
^13^ Dad la vuelta a Sión, girad en torno de ella,

[[psalms-48-14]]
^14^ grabad en vuestros corazones sus murallas,

[[psalms-48-15]]
^15^ que así es Dios,
[[psalms-49]]
== Capítulo 49

[[psalms-49-1]]
^1^ Del maestro de coro. De los hijos de Coré. Salmo.

[[psalms-49-2]]
^2^ ¡Oídlo, pueblos todos,

[[psalms-49-3]]
^3^ hijos de Adán, así como hijos de hombre,

[[psalms-49-4]]
^4^ Mi boca va a decir sabiduría,

[[psalms-49-5]]
^5^ tiendo mi oído a un proverbio,

[[psalms-49-6]]
^6^ ¿Por qué temer en días de desgracia

[[psalms-49-7]]
^7^ los que ponen su confianza en su fortuna,

[[psalms-49-8]]
^8^ ¡Si nadie puede redimirse

[[psalms-49-9]]
^9^ es muy cara la redención de su alma,

[[psalms-49-10]]
^10^ para que viva aún y nunca vea la fosa.

[[psalms-49-11]]
^11^ Se ve, en cambio, fenecer a los sabios,

[[psalms-49-12]]
^12^ Sus tumbas son sus casas para siempre,

[[psalms-49-13]]
^13^ El hombre en la opulencia no comprende,

[[psalms-49-14]]
^14^ Así andan ellos, seguros de sí mismos,

[[psalms-49-15]]
^15^ Como ovejas son llevados al seol,

[[psalms-49-16]]
^16^ Pero Dios rescatará mi alma,

[[psalms-49-17]]
^17^ No temas cuando el hombre se enriquece,

[[psalms-49-18]]
^18^ Que a su muerte, nada ha de llevarse,

[[psalms-49-19]]
^19^ Aunque en vida se bendecía a sí mismo

[[psalms-49-20]]
^20^ irá a unirse a la estirpe de sus padres,

[[psalms-49-21]]
^21^ El hombre en la opulencia no comprende,
[[psalms-50]]
== Capítulo 50

[[psalms-50-1]]
^1^ Salmo. De Asaf. El Dios de los dioses, Yahveh, habla

[[psalms-50-2]]
^2^ Desde Sión, la Hermosa sin par, Dios resplandece,

[[psalms-50-3]]
^3^ viene nuestro Dios y no se callará.

[[psalms-50-4]]
^4^ convoca a los cielos desde lo alto,

[[psalms-50-5]]
^5^ «¡Congregad a mis fieles ante mí,

[[psalms-50-6]]
^6^ Anuncian los cielos su justicia,

[[psalms-50-7]]
^7^ «Escucha, pueblo mío, que hablo yo,

[[psalms-50-8]]
^8^ «No es por tus sacrificios por lo que te acuso:

[[psalms-50-9]]
^9^ No tengo que tomar novillo de tu casa,

[[psalms-50-10]]
^10^ «Pues mías son todas las fieras de la selva,

[[psalms-50-11]]
^11^ conozco todas las aves de los cielos,

[[psalms-50-12]]
^12^ «Si hambre tuviera, no habría de decírtelo,

[[psalms-50-13]]
^13^ ¿Es que voy a comer carne de toros,

[[psalms-50-14]]
^14^ «Sacrificio ofrece a Dios de acción de gracias,

[[psalms-50-15]]
^15^ e invócame en el día de la angustia,

[[psalms-50-16]]
^16^ Pero al impío Dios le dice:

[[psalms-50-17]]
^17^ tú que detestas la doctrina,

[[psalms-50-18]]
^18^ «Si a un ladrón ves, te vas con él,

[[psalms-50-19]]
^19^ sueltas tu boca al mal,

[[psalms-50-20]]
^20^ «Te sientas, hablas contra tu hermano,

[[psalms-50-21]]
^21^ Esto haces tú, ¿y he de callarme?

[[psalms-50-22]]
^22^ «¡Entended esto bien los que olvidáis a Dios,

[[psalms-50-23]]
^23^ El que ofrece sacrificios de acción de gracias me da gloria,
[[psalms-51]]
== Capítulo 51

[[psalms-51-1]]
^1^ Del maestro de coro. Salmo. De David.

[[psalms-51-2]]
^2^ Cuando el profeta Natán le visitó después que aquél se había

[[psalms-51-3]]
^3^ Tenme piedad, oh Dios, según tu amor,

[[psalms-51-4]]
^4^ lávame a fondo de mi culpa,

[[psalms-51-5]]
^5^ Pues mi delito yo lo reconozco,

[[psalms-51-6]]
^6^ contra ti, contra ti solo he pecado,

[[psalms-51-7]]
^7^ Mira que en culpa ya nací,

[[psalms-51-8]]
^8^ Mas tú amas la verdad en lo íntimo del ser,

[[psalms-51-9]]
^9^ Rocíame con el hisopo, y seré limpio,

[[psalms-51-10]]
^10^ Devuélveme el son del gozo y la alegría,

[[psalms-51-11]]
^11^ Retira tu faz de mis pecados,

[[psalms-51-12]]
^12^ Crea en mí, oh Dios, un puro corazón,

[[psalms-51-13]]
^13^ no me rechaces lejos de tu rostro,

[[psalms-51-14]]
^14^ Vuélveme la alegría de tu salvación,

[[psalms-51-15]]
^15^ enseñaré a los rebeldes tus caminos,

[[psalms-51-16]]
^16^ Líbrame de la sangre, Dios, Dios de mi salvación,

[[psalms-51-17]]
^17^ abre, Señor, mis labios,

[[psalms-51-18]]
^18^ Pues no te agrada el sacrificio,

[[psalms-51-19]]
^19^ El sacrificio a Dios es un espíritu contrito;

[[psalms-51-20]]
^20^ ¡Favorece a Sión en tu benevolencia,

[[psalms-51-21]]
^21^ Entonces te agradarán los sacrificios justos,
[[psalms-52]]
== Capítulo 52

[[psalms-52-1]]
^1^ Del maestro de coro. Poema. De David.

[[psalms-52-2]]
^2^ Cuando el edomita Doeg vino a avisar a Saúl diciéndole:

[[psalms-52-3]]
^3^ ¿Por qué te glorías del mal,

[[psalms-52-4]]
^4^ pensando estás en crímenes,

[[psalms-52-5]]
^5^ El mal al bien prefieres,

[[psalms-52-6]]
^6^ amas toda palabra de perdición,

[[psalms-52-7]]
^7^ Por eso Dios te aplastará,

[[psalms-52-8]]
^8^ Los justos lo verán y temerán,

[[psalms-52-9]]
^9^ «¡Ese es el hombre que no puso

[[psalms-52-10]]
^10^ Mas yo, como un olivo verde

[[psalms-52-11]]
^11^ Te alabaré eternamente
[[psalms-53]]
== Capítulo 53

[[psalms-53-1]]
^1^ Del maestro de coro. Para la enfermedad. Poema. De David.

[[psalms-53-2]]
^2^ Dice en su corazón el insensato:

[[psalms-53-3]]
^3^ Se asoma Dios desde los cielos

[[psalms-53-4]]
^4^ Todos ellos están descarriados,

[[psalms-53-5]]
^5^ ¿No aprenderán todos los agentes de mal

[[psalms-53-6]]
^6^ Allí de espanto temblarán,

[[psalms-53-7]]
^7^ ¿Quién traerá de Sión la salvación de Israel?
[[psalms-54]]
== Capítulo 54

[[psalms-54-1]]
^1^ Del maestro de coro. Para instrumentos de cuerda. Poema. De

[[psalms-54-2]]
^2^ Cuando los zifitas vinieron a decir a Saúl: «¿No está

[[psalms-54-3]]
^3^ ¡Oh Dios, sálvame por tu nombre,

[[psalms-54-4]]
^4^ oh Dios, escucha mi oración,

[[psalms-54-5]]
^5^ Pues se han alzado contra mí arrogantes,

[[psalms-54-6]]
^6^ Mas ved que Dios viene en mi auxilio,

[[psalms-54-7]]
^7^ ¡El mal recaiga sobre los que me asechan,

[[psalms-54-8]]
^8^ De corazón te ofreceré sacrificios,

[[psalms-54-9]]
^9^ porque de toda angustia me ha librado,
[[psalms-55]]
== Capítulo 55

[[psalms-55-1]]
^1^ Del maestro de coro. Para instrumentos de cuerda. Poema. De

[[psalms-55-2]]
^2^ Escucha, oh Dios, mi oración,

[[psalms-55-3]]
^3^ dame oídos, respóndeme,

[[psalms-55-4]]
^4^ ante la voz del enemigo,

[[psalms-55-5]]
^5^ Se me estremece dentro el corazón,

[[psalms-55-6]]
^6^ miedo y temblor me invaden,

[[psalms-55-7]]
^7^ Y digo: ¡Quién me diera alas como a la paloma

[[psalms-55-8]]
^8^ Huiría entonces lejos,

[[psalms-55-9]]
^9^ En seguida encontraría un asilo

[[psalms-55-10]]
^10^ ¡Oh, piérdelos, Señor,

[[psalms-55-11]]
^11^ rondan día y noche

[[psalms-55-12]]
^12^ insidias dentro de ella,

[[psalms-55-13]]
^13^ Si todavía un enemigo me ultrajara,

[[psalms-55-14]]
^14^ ¡Pero tú, un hombre de mi rango,

[[psalms-55-15]]
^15^ con quien me unía una dulce intimidad,

[[psalms-55-16]]
^16^ caiga la muerte sobre ellos,

[[psalms-55-17]]
^17^ Yo, en cambio, a Dios invoco,

[[psalms-55-18]]
^18^ A la tarde, a la mañana, al mediodía

[[psalms-55-19]]
^19^ En paz mi alma rescata

[[psalms-55-20]]
^20^ Dios escucha y los humilla,

[[psalms-55-21]]
^21^ Cada uno extiende su mano contra sus aliados,

[[psalms-55-22]]
^22^ más blanda que la crema es su boca,

[[psalms-55-23]]
^23^ Descarga en Yahveh tu peso,

[[psalms-55-24]]
^24^ Y tú, oh Dios, los hundirás
[[psalms-56]]
== Capítulo 56

[[psalms-56-1]]
^1^ Del maestro de coro. Según: «La opresión de los príncipes

[[psalms-56-2]]
^2^ Tenme piedad, oh Dios, porque me pisan,

[[psalms-56-3]]
^3^ Me pisan todo el día los que me asechan,

[[psalms-56-4]]
^4^ El día en que temo, en ti confío.

[[psalms-56-5]]
^5^ En Dios, cuya palabra alabo,

[[psalms-56-6]]
^6^ Todo el día retuercen mis palabras,

[[psalms-56-7]]
^7^ se conjuran, se ocultan, mis pisadas observan,

[[psalms-56-8]]
^8^ Por su iniquidad, ¿habrá escape para ellos?

[[psalms-56-9]]
^9^ De mi vida errante llevas tú la cuenta,

[[psalms-56-10]]
^10^ Entonces retrocederán mis enemigos,

[[psalms-56-11]]
^11^ En Dios, cuya palabra alabo,

[[psalms-56-12]]
^12^ en Dios confío y ya no temo,

[[psalms-56-13]]
^13^ A mi cargo, oh Dios, los votos que te hice:

[[psalms-56-14]]
^14^ pues tú salvaste mi alma de la muerte,
[[psalms-57]]
== Capítulo 57

[[psalms-57-1]]
^1^ Del maestro de coro. «No destruyas». De David. A media

[[psalms-57-2]]
^2^ Tenme piedad, oh Dios, tenme piedad,

[[psalms-57-3]]
^3^ Invoco al Dios Altísimo,

[[psalms-57-4]]
^4^ Mande desde los cielos y me salve,

[[psalms-57-5]]
^5^ Mi alma está tendida en medio de leones,

[[psalms-57-6]]
^6^ ¡Alzate, oh Dios, sobre los cielos,

[[psalms-57-7]]
^7^ Tendían ellos una red bajo mis pasos,

[[psalms-57-8]]
^8^ A punto está mi corazón, oh Dios,

[[psalms-57-9]]
^9^ ¡gloria mía, despierta!,

[[psalms-57-10]]
^10^ Te alabaré entre los pueblos, Señor,

[[psalms-57-11]]
^11^ porque tu amor es grande hasta los cielos,

[[psalms-57-12]]
^12^ ¡Alzate, oh Dios, sobre los cielos,
[[psalms-58]]
== Capítulo 58

[[psalms-58-1]]
^1^ Del maestro de coro. «No destruyas». De David. A media

[[psalms-58-2]]
^2^ ¿De veras, dioses, pronunciáis justicia,

[[psalms-58-3]]
^3^ No. que de corazón cometéis injusticias,

[[psalms-58-4]]
^4^ Torcidos están desde el seno los impíos,

[[psalms-58-5]]
^5^ tienen veneno como veneno de serpiente,

[[psalms-58-6]]
^6^ que no oye la voz de los encantadores,

[[psalms-58-7]]
^7^ ¡Oh Dios, rompe sus dientes en su boca,

[[psalms-58-8]]
^8^ ¡Dilúyanse como aguas que se pasan,

[[psalms-58-9]]
^9^ como limaco que marcha deshaciéndose,

[[psalms-58-10]]
^10^ ¡Antes que espinas echen, como la zarza,

[[psalms-58-11]]
^11^ Se alegrará el justo de haber visto la venganza,

[[psalms-58-12]]
^12^ y se dirá: «Sí, hay un fruto para el justo;
[[psalms-59]]
== Capítulo 59

[[psalms-59-1]]
^1^ Del maestro de coro. «No destruyas». De David. A media

[[psalms-59-2]]
^2^ ¡Líbrame de mis enemigos, oh Dios mío,

[[psalms-59-3]]
^3^ líbrame de los agentes de mal,

[[psalms-59-4]]
^4^ Mira que acechan a mi alma,

[[psalms-59-5]]
^5^ sin culpa alguna, corren y se aprestan.

[[psalms-59-6]]
^6^ tú, Yahveh, Dios Sebaot, Dios de Israel,

[[psalms-59-7]]
^7^ Regresan a la tarde,

[[psalms-59-8]]
^8^ Míralos desbarrar a boca llena,

[[psalms-59-9]]
^9^ Mas tú, Yahveh, te ríes de ellos,

[[psalms-59-10]]
^10^ Oh fuerza mía, hacia ti miro.

[[psalms-59-11]]
^11^ el Dios de mi amor viene a mi encuentro.

[[psalms-59-12]]
^12^ ¡Oh, no los mates, no se olvide mi pueblo,

[[psalms-59-13]]
^13^ Pecado es en su boca la palabra de sus labios;

[[psalms-59-14]]
^14^ ¡Suprime con furor, suprímelos, no existan más!

[[psalms-59-15]]
^15^ Regresan a la tarde,

[[psalms-59-16]]
^16^ vedlos buscando qué comer,

[[psalms-59-17]]
^17^ Yo, en cambio, cantaré tu fuerza,

[[psalms-59-18]]
^18^ Oh fuerza mía, para ti salmodiaré,
[[psalms-60]]
== Capítulo 60

[[psalms-60-1]]
^1^ Del maestro de coro. Según «El lirio del testimonio». A

[[psalms-60-2]]
^2^ Cuando luchó contra Aram de Naharáyim y Aram de Sobá, y Joab,

[[psalms-60-3]]
^3^ Nos has rechazado, oh Dios, nos has deshecho,

[[psalms-60-4]]
^4^ Has sacudido la tierra, la has hendido;

[[psalms-60-5]]
^5^ Hiciste ver a tu pueblo duras pruebas,

[[psalms-60-6]]
^6^ Diste a los que le temen la señal

[[psalms-60-7]]
^7^ Para que tus amados salgan libres,

[[psalms-60-8]]
^8^ Ha hablado Dios en su santuario:

[[psalms-60-9]]
^9^ «Mío es Galaad, mío Manasés,

[[psalms-60-10]]
^10^ «Moab, la vasija en que me lavo.

[[psalms-60-11]]
^11^ ¿Quién me conducirá hasta la plaza fuerte,

[[psalms-60-12]]
^12^ ¿No eres tú, oh Dios, que nos has rechazado,

[[psalms-60-13]]
^13^ Danos ayuda contra el adversario,

[[psalms-60-14]]
^14^ ¡Con Dios hemos de hacer proezas,
[[psalms-61]]
== Capítulo 61

[[psalms-61-1]]
^1^ Del maestro de coro. Para instrumentos de cuerda. De David.

[[psalms-61-2]]
^2^ ¡Escucha, oh Dios, mi clamor,

[[psalms-61-3]]
^3^ Desde el extremo de la tierra hacia ti grito,

[[psalms-61-4]]
^4^ pues tú eres mi refugio,

[[psalms-61-5]]
^5^ ¡Que sea yo siempre huésped de tu tienda,

[[psalms-61-6]]
^6^ Porque tú, oh Dios, oyes mis votos:

[[psalms-61-7]]
^7^ A los días del rey añade días,

[[psalms-61-8]]
^8^ ¡Reine por siempre ante la faz de Dios!

[[psalms-61-9]]
^9^ Entonces salmodiaré a tu nombre para siempre,
[[psalms-62]]
== Capítulo 62

[[psalms-62-1]]
^1^ Del maestro de coro... Yedutún. Salmo. De David.

[[psalms-62-2]]
^2^ En Dios sólo el descanso de mi alma,

[[psalms-62-3]]
^3^ sólo él mi roca, mi salvación,

[[psalms-62-4]]
^4^ ¿Hasta cuándo atacaréis a un solo hombre,

[[psalms-62-5]]
^5^ Doblez sólo proyectan,

[[psalms-62-6]]
^6^ En Dios sólo descansa, oh alma mía,

[[psalms-62-7]]
^7^ sólo él mi roca, mi salvación,

[[psalms-62-8]]
^8^ en Dios mi salvación y mi gloria,

[[psalms-62-9]]
^9^ confiad en él,

[[psalms-62-10]]
^10^ Un soplo solamente los hijos de Adán,

[[psalms-62-11]]
^11^ No os fiéis de la opresión,

[[psalms-62-12]]
^12^ Dios ha hablado una vez,

[[psalms-62-13]]
^13^ tuyo, Señor, el amor;
[[psalms-63]]
== Capítulo 63

[[psalms-63-1]]
^1^ Salmo. De David. Cuando estaba en el desierto de Judá.

[[psalms-63-2]]
^2^ Dios, tú mi Dios, yo te busco,

[[psalms-63-3]]
^3^ Como cuando en el santuario te veía,

[[psalms-63-4]]
^4^ - pues tu amor es mejor que la vida,

[[psalms-63-5]]
^5^ así quiero en mi vida bendecirte,

[[psalms-63-6]]
^6^ como de grasa y médula se empapará mi alma,

[[psalms-63-7]]
^7^ Cuando pienso en ti sobre mi lecho,

[[psalms-63-8]]
^8^ porque tú eres mi socorro,

[[psalms-63-9]]
^9^ mi alma se aprieta contra ti,

[[psalms-63-10]]
^10^ Mas los que tratan de perder mi alma,

[[psalms-63-11]]
^11^ ¡Sean pasados al filo de la espada,

[[psalms-63-12]]
^12^ Y el rey en Dios se gozará,
[[psalms-64]]
== Capítulo 64

[[psalms-64-1]]
^1^ Del maestro de coro. Salmo. De David.

[[psalms-64-2]]
^2^ Escucha, oh Dios, la voz de mi gemido,

[[psalms-64-3]]
^3^ ocúltame a la pandilla de malvados,

[[psalms-64-4]]
^4^ Los que afilan su lengua como espada,

[[psalms-64-5]]
^5^ para tirar a escondidas contra el íntegro,

[[psalms-64-6]]
^6^ Se envalentonan en su acción malvada,

[[psalms-64-7]]
^7^ y escrutará nuestros secretos?»

[[psalms-64-8]]
^8^ Una saeta ha tirado Dios,

[[psalms-64-9]]
^9^ les ha hecho caer por causa de su lengua,

[[psalms-64-10]]
^10^ Todo hombre temerá.

[[psalms-64-11]]
^11^ El justo se alegrará en Yahveh,
[[psalms-65]]
== Capítulo 65

[[psalms-65-1]]
^1^ Del maestro de coro. Salmo. De David. Cántico.

[[psalms-65-2]]
^2^ A ti se debe la alabanza,

[[psalms-65-3]]
^3^ tú que escuchas la oración.

[[psalms-65-4]]
^4^ con sus obras culpables;

[[psalms-65-5]]
^5^ Dichoso tu elegido, tu privado,

[[psalms-65-6]]
^6^ Tú nos responderás con prodigios de justicia,

[[psalms-65-7]]
^7^ tú que afirmas los montes con tu fuerza,

[[psalms-65-8]]
^8^ y acallas el estruendo de los mares,

[[psalms-65-9]]
^9^ por tus señales temen los que habitan los confines,

[[psalms-65-10]]
^10^ Tú visitas la tierra y la haces rebosar,

[[psalms-65-11]]
^11^ riegas sus surcos, allanas sus glebas,

[[psalms-65-12]]
^12^ Tú coronas el año con tu benignidad,

[[psalms-65-13]]
^13^ destilan los pastos del desierto,

[[psalms-65-14]]
^14^ las praderas se visten de rebaños,
[[psalms-66]]
== Capítulo 66

[[psalms-66-1]]
^1^ Del maestro de coro. Cántico. Salmo.

[[psalms-66-2]]
^2^ salmodiad a la gloria de su nombre,

[[psalms-66-3]]
^3^ decid a Dios: ¡Qué terribles tus obras!

[[psalms-66-4]]
^4^ toda la tierra se postra ante ti,

[[psalms-66-5]]
^5^ Venid y ved las obras de Dios,

[[psalms-66-6]]
^6^ él convirtió el mar en tierra firme,

[[psalms-66-7]]
^7^ que por su poder domina para siempre.

[[psalms-66-8]]
^8^ Pueblos, bendecid a nuestro Dios,

[[psalms-66-9]]
^9^ él, que devuelve nuestra alma a la vida,

[[psalms-66-10]]
^10^ Tú nos probaste, oh Dios,

[[psalms-66-11]]
^11^ nos prendiste en la red,

[[psalms-66-12]]
^12^ dejaste que un cualquiera a nuestra cabeza cabalgara,

[[psalms-66-13]]
^13^ Con holocaustos entraré en tu Casa,

[[psalms-66-14]]
^14^ los que abrieron mis labios,

[[psalms-66-15]]
^15^ Te ofreceré pingües holocaustos,

[[psalms-66-16]]
^16^ Venid a oír y os contaré,

[[psalms-66-17]]
^17^ A él gritó mi boca,

[[psalms-66-18]]
^18^ Si yo en mi corazón hubiera visto iniquidad,

[[psalms-66-19]]
^19^ Pero Dios me ha escuchado,

[[psalms-66-20]]
^20^ ¡Bendito sea Dios,
[[psalms-67]]
== Capítulo 67

[[psalms-67-1]]
^1^ Del maestro de coro. Para instrumentos de cuerda. Salmo.

[[psalms-67-2]]
^2^ ¡Dios nos tenga piedad y nos bendiga,

[[psalms-67-3]]
^3^ Para que se conozcan en la tierra tus caminos,

[[psalms-67-4]]
^4^ ¡Te den, oh Dios, gracias los pueblos,

[[psalms-67-5]]
^5^ Alégrense y exulten las gentes,

[[psalms-67-6]]
^6^ ¡Te den, oh Dios, gracias los pueblos,

[[psalms-67-7]]
^7^ La tierra ha dado su cosecha:

[[psalms-67-8]]
^8^ ¡Dios nos bendiga, y teman ante él
[[psalms-68]]
== Capítulo 68

[[psalms-68-1]]
^1^ Del maestro de coro. De David. Salmo. Cántico.

[[psalms-68-2]]
^2^ ¡Alcese Dios, sus enemigos se dispersen,

[[psalms-68-3]]
^3^ Cual se disipa el humo, los disipas;

[[psalms-68-4]]
^4^ Mas los justos se alegran y exultan

[[psalms-68-5]]
^5^ Cantad a Dios, salmodiad a su nombre,

[[psalms-68-6]]
^6^ Padre de los huérfanos y tutor de las viudas

[[psalms-68-7]]
^7^ Dios da a los desvalidos el cobijo de una casa,

[[psalms-68-8]]
^8^ Oh Dios, cuando saliste al frente de tu pueblo,

[[psalms-68-9]]
^9^ la tierra retembló,

[[psalms-68-10]]
^10^ Tú derramaste, oh Dios, una lluvia de larguezas,

[[psalms-68-11]]
^11^ tu grey halló una morada, aquella

[[psalms-68-12]]
^12^ El Señor da la palabra:

[[psalms-68-13]]
^13^ Y mientras los reyes, los ejércitos huyen, huyen,

[[psalms-68-14]]
^14^ Mientras vosotros descansáis entre las tapias del aprisco,

[[psalms-68-15]]
^15^ cuando Sadday dispersa a los reyes,

[[psalms-68-16]]
^16^ ¡Monte de Dios, el monte de Basán!

[[psalms-68-17]]
^17^ ¿Por que miráis celosos, montes escarpados,

[[psalms-68-18]]
^18^ Los carros de Dios, por millares de miriadas;

[[psalms-68-19]]
^19^ Tú has subido a la altura, conduciendo cautivos,

[[psalms-68-20]]
^20^ ¡Bendito sea el Señor día tras día!

[[psalms-68-21]]
^21^ Dios libertador es nuestro Dios;

[[psalms-68-22]]
^22^ mas la cabeza de sus enemigos Dios quebranta,

[[psalms-68-23]]
^23^ Dijo el Señor: «De Basán haré volver,

[[psalms-68-24]]
^24^ para que puedas hundir tu pie en la sangre,

[[psalms-68-25]]
^25^ ¡Se han visto, oh Dios, tus procesiones,

[[psalms-68-26]]
^26^ delante los cantores, los músicos detrás,

[[psalms-68-27]]
^27^ A Dios, en coros, bendecían:

[[psalms-68-28]]
^28^ Allí iba Benjamín, el pequeño, abriendo marcha,

[[psalms-68-29]]
^29^ ¡Manda, Dios mío, según tu poder,

[[psalms-68-30]]
^30^ desde tu Templo en lo alto de Jerusalén,

[[psalms-68-31]]
^31^ Increpa a la bestia del cañaveral,

[[psalms-68-32]]
^32^ Los magnates acudan desde Egipto,

[[psalms-68-33]]
^33^ ¡Cantad a Dios, reinos de la tierra,

[[psalms-68-34]]
^34^ para el que cabalga los cielos, los antiguos cielos: Pausa.

[[psalms-68-35]]
^35^ Reconoced el poderío de Dios.

[[psalms-68-36]]
^36^ ¡temible es Dios desde su santuario!
[[psalms-69]]
== Capítulo 69

[[psalms-69-1]]
^1^ Del maestro de coro. Según la melodía: «Lirios..». De

[[psalms-69-2]]
^2^ ¡Sálvame, oh Dios, porque las aguas

[[psalms-69-3]]
^3^ Me hundo en el cieno del abismo,

[[psalms-69-4]]
^4^ Estoy exhausto de gritar, arden mis fauces,

[[psalms-69-5]]
^5^ Son más que los cabellos de mi cabeza

[[psalms-69-6]]
^6^ Tú, oh Dios, mi torpeza conoces,

[[psalms-69-7]]
^7^ ¡No se avergüencen por mí los que en ti esperan,

[[psalms-69-8]]
^8^ Pues por ti sufro el insulto,

[[psalms-69-9]]
^9^ para mis hermanos soy un extranjero,

[[psalms-69-10]]
^10^ pues me devora el celo de tu casa,

[[psalms-69-11]]
^11^ Si mortifico mi alma con ayuno,

[[psalms-69-12]]
^12^ si tomo un sayal por vestido,

[[psalms-69-13]]
^13^ cuento de los que están sentados a la puerta,

[[psalms-69-14]]
^14^ Mas mi oración hacia ti, Yahveh,

[[psalms-69-15]]
^15^ ¡Sácame del cieno, no me hunda,

[[psalms-69-16]]
^16^ ¡El flujo de las aguas no me anegue

[[psalms-69-17]]
^17^ ¡Respóndeme, Yahveh, pues tu amor es bondad;

[[psalms-69-18]]
^18^ no retires tu rostro de tu siervo,

[[psalms-69-19]]
^19^ acércate a mi alma, rescátala,

[[psalms-69-20]]
^20^ Tú conoces mi oprobio,

[[psalms-69-21]]
^21^ El oprobio me ha roto el corazón y desfallezco.

[[psalms-69-22]]
^22^ Veneno me han dado por comida,

[[psalms-69-23]]
^23^ ¡Que su mesa ante ellos se convierta en un lazo,

[[psalms-69-24]]
^24^ anúblense sus ojos y no vean,

[[psalms-69-25]]
^25^ Derrama tu enojo sobre ellos,

[[psalms-69-26]]
^26^ su recinto quede hecho un desierto,

[[psalms-69-27]]
^27^ porque acosan al que tú has herido,

[[psalms-69-28]]
^28^ Culpa añade a su culpa,

[[psalms-69-29]]
^29^ del libro de la vida sean borrados,

[[psalms-69-30]]
^30^ Y yo desdichado, dolorido,

[[psalms-69-31]]
^31^ El nombre de Dios celebraré en un cántico,

[[psalms-69-32]]
^32^ y más que un toro agradará a Yahveh,

[[psalms-69-33]]
^33^ Lo han visto los humildes y se alegran;

[[psalms-69-34]]
^34^ Porque Yahveh escucha a los pobres,

[[psalms-69-35]]
^35^ ¡Alábenle los cielos y la tierra,

[[psalms-69-36]]
^36^ Pues salvará Dios a Sión,

[[psalms-69-37]]
^37^ la heredará la estirpe de sus siervos,
[[psalms-70]]
== Capítulo 70

[[psalms-70-1]]
^1^ Del maestro de coro. De David. En memoria.

[[psalms-70-2]]
^2^ ¡Oh Dios, ven a librarme,

[[psalms-70-3]]
^3^ ¡Queden avergonzados y confusos

[[psalms-70-4]]
^4^ retrocedan de vergüenza

[[psalms-70-5]]
^5^ ¡En ti se gocen y se alegren

[[psalms-70-6]]
^6^ ¡Y yo, desventurado y pobre,
[[psalms-71]]
== Capítulo 71

[[psalms-71-1]]
^1^ A ti, Yahveh, me acojo,

[[psalms-71-2]]
^2^ ¡Por tu justicia sálvame, libérame!

[[psalms-71-3]]
^3^ ¡Sé para mí una roca de refugio,

[[psalms-71-4]]
^4^ ¡Dios mío, líbrame de la mano del impío,

[[psalms-71-5]]
^5^ Pues tú eres mi esperanza, Señor,

[[psalms-71-6]]
^6^ En ti tengo mi apoyo desde el seno,

[[psalms-71-7]]
^7^ Soy el asombro de muchos,

[[psalms-71-8]]
^8^ Mi boca está repleta de tu loa,

[[psalms-71-9]]
^9^ A la hora de mi vejez no me rechaces,

[[psalms-71-10]]
^10^ Porque de mí mis enemigos hablan,

[[psalms-71-11]]
^11^ «¡Dios le ha desamparado, perseguidle,

[[psalms-71-12]]
^12^ ¡Oh Dios, no te estés lejos de mí,

[[psalms-71-13]]
^13^ ¡Confusión y vergüenza sobre aquellos

[[psalms-71-14]]
^14^ Y yo, esperando sin cesar,

[[psalms-71-15]]
^15^ publicará mi boca tu justicia,

[[psalms-71-16]]
^16^ Y vendré a las proezas de Yahveh,

[[psalms-71-17]]
^17^ ¡Oh Dios, desde mi juventud me has instruido,

[[psalms-71-18]]
^18^ Y ahora que llega la vejez y las canas,

[[psalms-71-19]]
^19^ y tu justicia, oh Dios, hasta los cielos!

[[psalms-71-20]]
^20^ Tú que me has hecho ver tantos desastres y desgracias,

[[psalms-71-21]]
^21^ sustentarás mi ancianidad, volverás a consolarme,

[[psalms-71-22]]
^22^ Y yo te daré gracias con las cuerdas del arpa,

[[psalms-71-23]]
^23^ Exultarán mis labios cuando salmodie para ti,

[[psalms-71-24]]
^24^ También mi lengua todo el día
[[psalms-72]]
== Capítulo 72

[[psalms-72-1]]
^1^ De Salomón.

[[psalms-72-2]]
^2^ que con justicia gobierne a tu pueblo,

[[psalms-72-3]]
^3^ Traigan los montes paz al pueblo,

[[psalms-72-4]]
^4^ El hará justicia a los humildes del pueblo,

[[psalms-72-5]]
^5^ Durará tanto como el sol,

[[psalms-72-6]]
^6^ caerá como la lluvia en el retoño,

[[psalms-72-7]]
^7^ En sus días florecerá la justicia,

[[psalms-72-8]]
^8^ dominará de mar a mar,

[[psalms-72-9]]
^9^ Ante él se doblará la Bestia,

[[psalms-72-10]]
^10^ los reyes de Tarsis y las islas

[[psalms-72-11]]
^11^ todos los reyes se postrarán ante él,

[[psalms-72-12]]
^12^ Porque él librará al pobre suplicante,

[[psalms-72-13]]
^13^ se apiadará del débil y del pobre,

[[psalms-72-14]]
^14^ De la opresión, de la violencia, rescatará su alma,

[[psalms-72-15]]
^15^ (y mientras viva se le dará el oro de Sabá).

[[psalms-72-16]]
^16^ Habrá en la tierra abundancia de trigo,

[[psalms-72-17]]
^17^ ¡Sea su nombre bendito para siempre,

[[psalms-72-18]]
^18^ ¡Bendito sea Yahveh, Dios de Israel,

[[psalms-72-19]]
^19^ ¡Bendito sea su nombre glorioso para siempre,

[[psalms-72-20]]
^20^ Fin de las oraciones de David, hijo de Jesé.
[[psalms-73]]
== Capítulo 73

[[psalms-73-1]]
^1^ Salmo. De Asaf.

[[psalms-73-2]]
^2^ Por poco mis pies se me extravían,

[[psalms-73-3]]
^3^ celoso como estaba de los arrogantes,

[[psalms-73-4]]
^4^ No, no hay congojas para ellos,

[[psalms-73-5]]
^5^ no comparten la pena de los hombres,

[[psalms-73-6]]
^6^ Por eso el orgullo es su collar,

[[psalms-73-7]]
^7^ la malicia les cunde de la grasa,

[[psalms-73-8]]
^8^ Se sonríen, pregonan la maldad,

[[psalms-73-9]]
^9^ ponen en el cielo su boca,

[[psalms-73-10]]
^10^ Por eso mi pueblo va hacia ellos:

[[psalms-73-11]]
^11^ Dicen: «¿Cómo va a saber Dios?

[[psalms-73-12]]
^12^ Miradlos: ésos son los impíos,

[[psalms-73-13]]
^13^ ¡Así que en vano guardé el corazón puro,

[[psalms-73-14]]
^14^ cuando era golpeado todo el día,

[[psalms-73-15]]
^15^ Si hubiera dicho: «Voy a hablar como ellos»,

[[psalms-73-16]]
^16^ me puse, pues, a pensar para entenderlo,

[[psalms-73-17]]
^17^ Hasta el día en que entré en los divinos santuarios,

[[psalms-73-18]]
^18^ oh, sí, tú en precipicios los colocas,

[[psalms-73-19]]
^19^ ¡Ah, qué pronto quedan hechos un horror,

[[psalms-73-20]]
^20^ Como en un sueño al despertar, Señor,

[[psalms-73-21]]
^21^ Sí, cuando mi corazón se exacerbaba,

[[psalms-73-22]]
^22^ estúpido de mí, no comprendía,

[[psalms-73-23]]
^23^ Pero a mí, que estoy siempre contigo,

[[psalms-73-24]]
^24^ me guiarás con tu consejo,

[[psalms-73-25]]
^25^ ¿Quién hay para mí en el cielo?

[[psalms-73-26]]
^26^ Mi carne y mi corazón se consumen:

[[psalms-73-27]]
^27^ Sí, los que se alejan de ti perecerán,

[[psalms-73-28]]
^28^ Mas para mí, mi bien es estar junto a Dios;
[[psalms-74]]
== Capítulo 74

[[psalms-74-1]]
^1^ Poema. De Asaf.

[[psalms-74-2]]
^2^ Acuérdate de la comunidad que de antiguo adquiriste,

[[psalms-74-3]]
^3^ Guía tus pasos a estas ruinas sin fin:

[[psalms-74-4]]
^4^ En el lugar de tus reuniones rugieron tus adversarios,

[[psalms-74-5]]
^5^ que no se conocían,

[[psalms-74-6]]
^6^ a una cercenaban sus jambas,

[[psalms-74-7]]
^7^ Prendieron fuego a tu santuario,

[[psalms-74-8]]
^8^ Dijeron en su corazón: «¡Destruyámoslos en bloque!»

[[psalms-74-9]]
^9^ No vemos nuestras enseñas, no existen ya profetas,

[[psalms-74-10]]
^10^ ¿Hasta cuándo, oh Dios, provocará el adversario?

[[psalms-74-11]]
^11^ ¿Por qué retraes tu mano,

[[psalms-74-12]]
^12^ Oh Dios, mi rey desde el principio,

[[psalms-74-13]]
^13^ tú hendiste el mar con tu poder,

[[psalms-74-14]]
^14^ tú machacaste las cabezas de Leviatán

[[psalms-74-15]]
^15^ tú abriste manantiales y torrentes,

[[psalms-74-16]]
^16^ tuyo es el día, tuya también la noche,

[[psalms-74-17]]
^17^ tú trazaste todos los confines de la tierra,

[[psalms-74-18]]
^18^ Recuérdalo, Yahveh: provoca el enemigo,

[[psalms-74-19]]
^19^ No entregues a la bestia el alma de tu tórtola,

[[psalms-74-20]]
^20^ Piensa en la alianza, que están llenos

[[psalms-74-21]]
^21^ ¡No vuelva cubierto de vergüenza el oprimido;

[[psalms-74-22]]
^22^ ¡Alzate, oh Dios, a defender tu causa,

[[psalms-74-23]]
^23^ No olvides el griterío de tus adversarios,
[[psalms-75]]
== Capítulo 75

[[psalms-75-1]]
^1^ Del maestro de coro. «No destruyas». Salmo. De Asaf.

[[psalms-75-2]]
^2^ Te damos gracias, oh Dios, te damos gracias,

[[psalms-75-3]]
^3^ «En el momento en que decida,

[[psalms-75-4]]
^4^ Se estremece la tierra con todos sus habitantes,

[[psalms-75-5]]
^5^ «Digo a los arrogantes: ¡Fuera arrogancias!,

[[psalms-75-6]]
^6^ no levantéis tan alto vuestra frente,

[[psalms-75-7]]
^7^ Pues ya no es por oriente ni por occidente,

[[psalms-75-8]]
^8^ por donde Dios, el juez,

[[psalms-75-9]]
^9^ sino que hay una copa en la mano de Yahveh,

[[psalms-75-10]]
^10^ Y yo lo anunciaré por siempre,

[[psalms-75-11]]
^11^ quebraré toda frente de los impíos,
[[psalms-76]]
== Capítulo 76

[[psalms-76-1]]
^1^ Del maestro de coro. Para instrumentos de cuerda. Salmo. De

[[psalms-76-2]]
^2^ En Judá Dios es conocido,

[[psalms-76-3]]
^3^ su tienda está en Salem,

[[psalms-76-4]]
^4^ allí quebró las ráfagas del arco,

[[psalms-76-5]]
^5^ Fulgurante eres tú, maravilloso

[[psalms-76-6]]
^6^ de que han sido despojados;

[[psalms-76-7]]
^7^ a tu amenaza, oh Dios de Jacob,

[[psalms-76-8]]
^8^ Tú, tú el terrible, ¿quién puede resistir

[[psalms-76-9]]
^9^ Desde los cielos pronuncias la sentencia,

[[psalms-76-10]]
^10^ cuando Dios se levanta para el juicio,

[[psalms-76-11]]
^11^ La cólera del hombre te celebra,

[[psalms-76-12]]
^12^ Haced votos y cumplidlos a Yahveh, vuestro Dios,

[[psalms-76-13]]
^13^ el que corta el aliento a los príncipes,
[[psalms-77]]
== Capítulo 77

[[psalms-77-1]]
^1^ Del maestro de coro... Yedutún. De Asaf. Salmo.

[[psalms-77-2]]
^2^ Mi voz hacia Dios: yo clamo,

[[psalms-77-3]]
^3^ En el día de mi angustia voy buscando al Señor,

[[psalms-77-4]]
^4^ De Dios me acuerdo y gimo,

[[psalms-77-5]]
^5^ Los párpados de mis ojos tú retienes,

[[psalms-77-6]]
^6^ pienso en los días de antaño,

[[psalms-77-7]]
^7^ me acuerdo;

[[psalms-77-8]]
^8^ ¿Acaso por los siglos desechará el Señor,

[[psalms-77-9]]
^9^ ¿Se ha agotado para siempre su amor?

[[psalms-77-10]]
^10^ ¿Se habrá olvidado Dios de ser clemente,

[[psalms-77-11]]
^11^ Y digo: «Este es mi penar:

[[psalms-77-12]]
^12^ Me acuerdo de las gestas de Yahveh,

[[psalms-77-13]]
^13^ medito en toda tu obra,

[[psalms-77-14]]
^14^ ¡Oh Dios, santos son tus caminos!

[[psalms-77-15]]
^15^ Tú, el Dios que obras maravillas,

[[psalms-77-16]]
^16^ con tu brazo a tu pueblo rescataste,

[[psalms-77-17]]
^17^ Viéronte, oh Dios, las aguas,

[[psalms-77-18]]
^18^ Las nubes derramaron sus aguas,

[[psalms-77-19]]
^19^ ¡Voz de tu trueno en torbellino!

[[psalms-77-20]]
^20^ Por el mar iba tu camino,

[[psalms-77-21]]
^21^ Tú guiaste a tu pueblo cual rebaño
[[psalms-78]]
== Capítulo 78

[[psalms-78-1]]
^1^ Poema. De Asaf.

[[psalms-78-2]]
^2^ voy a abrir mi boca en parábolas,

[[psalms-78-3]]
^3^ Lo que hemos oído y que sabemos,

[[psalms-78-4]]
^4^ no se lo callaremos a sus hijos,

[[psalms-78-5]]
^5^ él estableció en Jacob un dictamen,

[[psalms-78-6]]
^6^ que la generación siguiente lo supiera,

[[psalms-78-7]]
^7^ para que pusieran en Dios su confianza,

[[psalms-78-8]]
^8^ para que no fueran, lo mismo que sus padres,

[[psalms-78-9]]
^9^ Los hijos de Efraím, diestros arqueros,

[[psalms-78-10]]
^10^ no guardaban la alianza hecha con Dios,

[[psalms-78-11]]
^11^ tenían olvidados sus portentos,

[[psalms-78-12]]
^12^ prodigios hizo a la vista de sus padres

[[psalms-78-13]]
^13^ Hendió la mar y los pasó a través,

[[psalms-78-14]]
^14^ de día los guiaba con la nube,

[[psalms-78-15]]
^15^ en el desierto hendió las rocas,

[[psalms-78-16]]
^16^ hizo brotar arroyos de la peña

[[psalms-78-17]]
^17^ Pero ellos volvían a pecar contra él,

[[psalms-78-18]]
^18^ a Dios tentaron en su corazón

[[psalms-78-19]]
^19^ Hablaron contra Dios;

[[psalms-78-20]]
^20^ «Ved que él hirió la roca,

[[psalms-78-21]]
^21^ Entonces Yahveh lo oyó y se enfureció,

[[psalms-78-22]]
^22^ porque en Dios no habían tenido fe

[[psalms-78-23]]
^23^ Y a las nubes mandó desde lo alto,

[[psalms-78-24]]
^24^ hizo llover sobre ellos maná para comer,

[[psalms-78-25]]
^25^ pan de Fuertes comió el hombre,

[[psalms-78-26]]
^26^ Hizo soplar en los cielos el solano,

[[psalms-78-27]]
^27^ y llovió sobre ellos carne como polvo,

[[psalms-78-28]]
^28^ las dejó caer en medio de su campo,

[[psalms-78-29]]
^29^ Comieron hasta quedar bien hartos,

[[psalms-78-30]]
^30^ mas aún no habían colmado su avidez,

[[psalms-78-31]]
^31^ cuando la cólera de Dios estalló contra ellos:

[[psalms-78-32]]
^32^ Mas con todo pecaron todavía,

[[psalms-78-33]]
^33^ El consumió sus días con un soplo,

[[psalms-78-34]]
^34^ Cuando los mataba, le buscaban,

[[psalms-78-35]]
^35^ y recordaban que Dios era su roca,

[[psalms-78-36]]
^36^ Mas le halagaban con su boca,

[[psalms-78-37]]
^37^ su corazón no era fiel para con él,

[[psalms-78-38]]
^38^ El, con todo, enternecido,

[[psalms-78-39]]
^39^ se acordaba de que ellos eran carne,

[[psalms-78-40]]
^40^ ¡Cuántas veces se rebelaron contra él en el desierto,

[[psalms-78-41]]
^41^ Otra vez a tentar a Dios volvían,

[[psalms-78-42]]
^42^ no se acordaron de su mano,

[[psalms-78-43]]
^43^ cuando hizo en Egipto sus señales,

[[psalms-78-44]]
^44^ Trocó en sangre sus ríos

[[psalms-78-45]]
^45^ Tábanos les mandó que los comieron,

[[psalms-78-46]]
^46^ entregó a la langosta sus cosechas,

[[psalms-78-47]]
^47^ asoló con granizo sus viñedos,

[[psalms-78-48]]
^48^ entregó sus ganados al pedrisco

[[psalms-78-49]]
^49^ Lanzó contra ellos el fuego de su cólera,

[[psalms-78-50]]
^50^ libre curso dio a su ira.

[[psalms-78-51]]
^51^ hirió en Egipto a todo primogénito,

[[psalms-78-52]]
^52^ Y sacó a su pueblo como ovejas,

[[psalms-78-53]]
^53^ los guió en seguro, sin temor,

[[psalms-78-54]]
^54^ los llevó a su término santo,

[[psalms-78-55]]
^55^ arrojó a las naciones ante ellos;

[[psalms-78-56]]
^56^ Pero ellos le tentaron, se rebelaron contra el Dios Altísimo,

[[psalms-78-57]]
^57^ se extraviaron, infieles, lo mismo que sus padres,

[[psalms-78-58]]
^58^ le irritaron con sus altos,

[[psalms-78-59]]
^59^ Dios lo oyó y se enfureció,

[[psalms-78-60]]
^60^ abandonó la morada de Silo,

[[psalms-78-61]]
^61^ Mandó su fuerza al cautiverio,

[[psalms-78-62]]
^62^ entregó su pueblo a la espada,

[[psalms-78-63]]
^63^ El fuego devoró a sus jóvenes,

[[psalms-78-64]]
^64^ sus sacerdotes cayeron a cuchillo,

[[psalms-78-65]]
^65^ Entonces despertó el Señor como un durmiente,

[[psalms-78-66]]
^66^ hirió a sus adversarios en la espalda,

[[psalms-78-67]]
^67^ Desechó la tienda de José,

[[psalms-78-68]]
^68^ mas eligió a la tribu de Judá,

[[psalms-78-69]]
^69^ Construyó como las alturas del cielo su santuario,

[[psalms-78-70]]
^70^ Y eligió a David su servidor,

[[psalms-78-71]]
^71^ le trajo de detrás de las ovejas,

[[psalms-78-72]]
^72^ El los pastoreaba con corazón perfecto,
[[psalms-79]]
== Capítulo 79

[[psalms-79-1]]
^1^ Salmo. De Asaf.

[[psalms-79-2]]
^2^ han entregado el cadáver de tus siervos

[[psalms-79-3]]
^3^ Han derramado como agua su sangre

[[psalms-79-4]]
^4^ Nos hemos hecho la irrisión de los vecinos,

[[psalms-79-5]]
^5^ ¿Hasta cuándo, Yahveh, tu cólera? ¿hasta el fin?

[[psalms-79-6]]
^6^ Derrama tu furor sobre las gentes,

[[psalms-79-7]]
^7^ Porque han devorado a Jacob

[[psalms-79-8]]
^8^ No recuerdes contra nosotros culpas de antepasados,

[[psalms-79-9]]
^9^ ayúdanos, Dios de nuestra salvación,

[[psalms-79-10]]
^10^ ¿Por qué han de decir las gentes: «¿Dónde está su Dios?»

[[psalms-79-11]]
^11^ ¡Llegue hasta ti el suspiro del cautivo,

[[psalms-79-12]]
^12^ ¡Devuelve siete veces a nuestros vecinos, en su entraña,

[[psalms-79-13]]
^13^ Y nosotros, tu pueblo, rebaño de tu pasto,
[[psalms-80]]
== Capítulo 80

[[psalms-80-1]]
^1^ Del maestro de coro. Según la melodía: «Lirios es el

[[psalms-80-2]]
^2^ Pastor de Israel, escucha,

[[psalms-80-3]]
^3^ ante Efraím, Benjamín y Manasés;

[[psalms-80-4]]
^4^ ¡Oh Dios, haznos volver,

[[psalms-80-5]]
^5^ ¿Hasta cuándo, oh Yahveh Dios Sebaot,

[[psalms-80-6]]
^6^ Les das a comer un pan de llanto

[[psalms-80-7]]
^7^ habladuría nos haces de nuestros convecinos,

[[psalms-80-8]]
^8^ ¡Oh Dios Sebaot, haznos volver,

[[psalms-80-9]]
^9^ Una viña de Egipto arrancaste,

[[psalms-80-10]]
^10^ le preparaste el suelo,

[[psalms-80-11]]
^11^ Su sombra cubría las montañas,

[[psalms-80-12]]
^12^ extendía sus sarmientos hasta el mar,

[[psalms-80-13]]
^13^ ¿Por qué has hecho brecha en sus tapias,

[[psalms-80-14]]
^14^ el jabalí salvaje la devaste,

[[psalms-80-15]]
^15^ ¡Oh Dios Sebaot, vuélvete ya,

[[psalms-80-16]]
^16^ cuídala,

[[psalms-80-17]]
^17^ ¡Los que fuego le prendieron, cual basura,

[[psalms-80-18]]
^18^ Esté tu mano sobre el hombre de tu diestra,

[[psalms-80-19]]
^19^ Ya no volveremos a apartarnos de ti;

[[psalms-80-20]]
^20^ ¡Oh Yahveh, Dios Sebaot, haznos volver,
[[psalms-81]]
== Capítulo 81

[[psalms-81-1]]
^1^ Del maestro de coro. Según la... de Gat. De Asaf.

[[psalms-81-2]]
^2^ ¡Gritad de gozo a Dios, nuestra fuerza,

[[psalms-81-3]]
^3^ ¡Entonad la salmodia, tocad el tamboril,

[[psalms-81-4]]
^4^ tocad la trompeta al nuevo mes,

[[psalms-81-5]]
^5^ Porque es una ley para Israel,

[[psalms-81-6]]
^6^ un dictamen que él impuso en José,

[[psalms-81-7]]
^7^ «Yo liberé sus hombros de la carga,

[[psalms-81-8]]
^8^ en la aflicción gritaste y te salvé.

[[psalms-81-9]]
^9^ Escucha, pueblo mío, yo te conjuro,

[[psalms-81-10]]
^10^ «No haya en ti dios extranjero,

[[psalms-81-11]]
^11^ yo, Yahveh, soy tu Dios,

[[psalms-81-12]]
^12^ «Pero mi pueblo no escuchó mi voz,

[[psalms-81-13]]
^13^ yo les abandoné a la dureza de su corazón,

[[psalms-81-14]]
^14^ «¡Ah!, si mi pueblo me escuchara,

[[psalms-81-15]]
^15^ al punto yo abatiría a sus enemigos,

[[psalms-81-16]]
^16^ «Los que odian a Yahveh le adularían,

[[psalms-81-17]]
^17^ y a él lo sustentaría con la flor del trigo,
[[psalms-82]]
== Capítulo 82

[[psalms-82-1]]
^1^ Salmo. De Asaf.

[[psalms-82-2]]
^2^ «¿Hasta cuándo juzgaréis inicuamente,

[[psalms-82-3]]
^3^ Juzgad en favor del débil y del huérfano,

[[psalms-82-4]]
^4^ al débil y al pobre liberad,

[[psalms-82-5]]
^5^ No saben ni comprenden; caminan en tinieblas,

[[psalms-82-6]]
^6^ Yo había dicho: «¡Vosotros, dioses sois,

[[psalms-82-7]]
^7^ Mas ahora, como el hombre moriréis,

[[psalms-82-8]]
^8^ ¡Alzate, oh Dios, juzga a la tierra,
[[psalms-83]]
== Capítulo 83

[[psalms-83-1]]
^1^ Cántico. Salmo. De Asaf.

[[psalms-83-2]]
^2^ ¡Oh Dios, no te estés mudo,

[[psalms-83-3]]
^3^ Mira cómo tus enemigos braman,

[[psalms-83-4]]
^4^ Contra tu pueblo maquinan intriga,

[[psalms-83-5]]
^5^ dicen: «Venid, borrémoslos de las naciones,

[[psalms-83-6]]
^6^ Así conspiran de corazón a una,

[[psalms-83-7]]
^7^ las tiendas de Edom, los ismaelitas,

[[psalms-83-8]]
^8^ Guebal, Ammón, Amalec,

[[psalms-83-9]]
^9^ también Assur se ha juntado a ellos

[[psalms-83-10]]
^10^ Trátalos como a Madián y como a Sísara, Pausa.

[[psalms-83-11]]
^11^ que fueron exterminados en Endor,

[[psalms-83-12]]
^12^ Trata a sus caudillos como a Oreb y Zeeb,

[[psalms-83-13]]
^13^ que habían dicho: «¡Para nosotros conquistemos

[[psalms-83-14]]
^14^ Dios mío, ponlos como hoja en remolino,

[[psalms-83-15]]
^15^ Como el fuego abrasa una selva,

[[psalms-83-16]]
^16^ así persíguelos con tu tormenta,

[[psalms-83-17]]
^17^ Cubre sus rostros de ignominia,

[[psalms-83-18]]
^18^ ¡Sean avergonzados y aterrados para siempre,

[[psalms-83-19]]
^19^ para que sepan que sólo tú tienes el nombre de Yahveh,
[[psalms-84]]
== Capítulo 84

[[psalms-84-1]]
^1^ Del maestro de coro. Según la... de Gat. De los hijos de

[[psalms-84-2]]
^2^ ¡Qué amables tus moradas,

[[psalms-84-3]]
^3^ Anhela mi alma y languidece

[[psalms-84-4]]
^4^ Hasta el pajarillo ha encontrado una casa,

[[psalms-84-5]]
^5^ Dichosos los que moran en tu casa,

[[psalms-84-6]]
^6^ Dichosos los hombres cuya fuerza está en ti,

[[psalms-84-7]]
^7^ Al pasar por el valle del Bálsamo,

[[psalms-84-8]]
^8^ De altura en altura marchan,

[[psalms-84-9]]
^9^ ¡Yahveh Dios Sebaot, escucha mi plegaria,

[[psalms-84-10]]
^10^ Oh Dios, escudo nuestro, mira,

[[psalms-84-11]]
^11^ Vale más un día en tus atrios

[[psalms-84-12]]
^12^ Porque Yahveh Dios es almena y escudo,

[[psalms-84-13]]
^13^ ¡Oh Yahveh Sebaot,
[[psalms-85]]
== Capítulo 85

[[psalms-85-1]]
^1^ Del maestro de coro. De los hijos de Coré. Salmo.

[[psalms-85-2]]
^2^ Propicio has sido, Yahveh, con tu tierra,

[[psalms-85-3]]
^3^ has quitado la culpa de tu pueblo,

[[psalms-85-4]]
^4^ has retirado todo tu furor,

[[psalms-85-5]]
^5^ ¡Haznos volver, Dios de nuestra salvación,

[[psalms-85-6]]
^6^ ¿Vas a estar siempre airado con nosotros?

[[psalms-85-7]]
^7^ ¿No volverás a darnos vida

[[psalms-85-8]]
^8^ ¡Muéstranos tu amor, Yahveh,

[[psalms-85-9]]
^9^ Voy a escuchar de qué habla Dios.

[[psalms-85-10]]
^10^ Ya está cerca su salvación para quienes le temen,

[[psalms-85-11]]
^11^ Amor y Verdad se han dado cita,

[[psalms-85-12]]
^12^ la Verdad brotará de la tierra,

[[psalms-85-13]]
^13^ El mismo Yahveh dará la dicha,

[[psalms-85-14]]
^14^ La Justicia marchará delante de él,
[[psalms-86]]
== Capítulo 86

[[psalms-86-1]]
^1^ Oración. De David.

[[psalms-86-2]]
^2^ guarda mi alma, porque yo te amo,

[[psalms-86-3]]
^3^ tenme piedad, Señor,

[[psalms-86-4]]
^4^ recrea el alma de tu siervo,

[[psalms-86-5]]
^5^ Pues tú eres, Señor, bueno, indulgente,

[[psalms-86-6]]
^6^ Yahveh, presta oído a mi plegaria,

[[psalms-86-7]]
^7^ En el día de mi angustia yo te invoco,

[[psalms-86-8]]
^8^ entre los dioses, ninguno como tú, Señor,

[[psalms-86-9]]
^9^ Vendrán todas las naciones a postrarse ante ti,

[[psalms-86-10]]
^10^ pues tú eres grande y obras maravillas,

[[psalms-86-11]]
^11^ Enséñame tus caminos Yahveh,

[[psalms-86-12]]
^12^ Gracias te doy de todo corazón, Señor Dios mío,

[[psalms-86-13]]
^13^ pues grande es tu amor para conmigo,

[[psalms-86-14]]
^14^ Oh Dios, los orgullosos se han alzado contra mí,

[[psalms-86-15]]
^15^ Mas tú, Señor, Dios clemente y compasivo,

[[psalms-86-16]]
^16^ ¡vuélvete a mí, tenme compasión!

[[psalms-86-17]]
^17^ Haz conmigo un signo de bondad:
[[psalms-87]]
== Capítulo 87

[[psalms-87-1]]
^1^ De los hijos de Coré. Salmo. Cántico.

[[psalms-87-2]]
^2^ ama Yahveh:

[[psalms-87-3]]
^3^ Glorias se dicen de ti,

[[psalms-87-4]]
^4^ «Yo cuento a Ráhab y Babel

[[psalms-87-5]]
^5^ Pero de Sión se ha de decir:

[[psalms-87-6]]
^6^ Yahveh a los pueblos inscribe en el registro:

[[psalms-87-7]]
^7^ y los príncipes, lo mismo que los hijos,
[[psalms-88]]
== Capítulo 88

[[psalms-88-1]]
^1^ Cántico. Salmo. De los hijos de Coré. Del maestro de coro.

[[psalms-88-2]]
^2^ Yahveh, Dios de mi salvación,

[[psalms-88-3]]
^3^ llegue hasta tí mi súplica,

[[psalms-88-4]]
^4^ Porque mi alma de males está ahíta,

[[psalms-88-5]]
^5^ contado entre los que bajan a la fosa,

[[psalms-88-6]]
^6^ relegado entre los muertos,

[[psalms-88-7]]
^7^ Me has echado en lo profundo de la fosa,

[[psalms-88-8]]
^8^ sobre mí pesa tu furor,

[[psalms-88-9]]
^9^ Has alejado de mí a mis conocidos,

[[psalms-88-10]]
^10^ mi ojo se consume por la pena.

[[psalms-88-11]]
^11^ ¿Acaso para los muertos haces maravillas,

[[psalms-88-12]]
^12^ ¿Se habla en la tumba de tu amor,

[[psalms-88-13]]
^13^ ¿Se conocen en las tinieblas tus maravillas,

[[psalms-88-14]]
^14^ Mas yo grito hacia ti, Yahveh,

[[psalms-88-15]]
^15^ ¿por qué, Yahveh, mi alma rechazas,

[[psalms-88-16]]
^16^ Desdichado y agónico estoy desde mi infancia,

[[psalms-88-17]]
^17^ han pasado tus iras sobre mí,

[[psalms-88-18]]
^18^ Me envuelven como el agua todo el día,

[[psalms-88-19]]
^19^ Has alejado de mí compañeros y amigos,
[[psalms-89]]
== Capítulo 89

[[psalms-89-1]]
^1^ Poema. De Etán el indígena.

[[psalms-89-2]]
^2^ El amor de Yahveh por siempre cantaré,

[[psalms-89-3]]
^3^ Pues tú dijiste: «Cimentado está el amor por siempre,

[[psalms-89-4]]
^4^ «Una alianza pacté con mi elegido,

[[psalms-89-5]]
^5^ Para siempre jamás he fundado tu estirpe,

[[psalms-89-6]]
^6^ Los cielos celebran, Yahveh, tus maravillas,

[[psalms-89-7]]
^7^ Porque ¿quién en las nubes es comparable a Yahveh,

[[psalms-89-8]]
^8^ Dios temible en el consejo de los santos,

[[psalms-89-9]]
^9^ Yahveh, Dios Sebaot, ¿quién como tú?,

[[psalms-89-10]]
^10^ Tú domeñas el orgullo del mar,

[[psalms-89-11]]
^11^ tú machacaste a Ráhab lo mismo que a un cadáver,

[[psalms-89-12]]
^12^ Tuyo es el cielo, tuya también la tierra,

[[psalms-89-13]]
^13^ tú creaste el norte y el mediodía,

[[psalms-89-14]]
^14^ Tuyo es el brazo y su bravura,

[[psalms-89-15]]
^15^ Justicia y Derecho, la base de tu trono,

[[psalms-89-16]]
^16^ Dichoso el pueblo que la aclamación conoce,

[[psalms-89-17]]
^17^ en tu nombre se alegran todo el día,

[[psalms-89-18]]
^18^ Pues tú eres el esplendor de su potencia,

[[psalms-89-19]]
^19^ sí, de Yahveh nuestro escudo;

[[psalms-89-20]]
^20^ Antaño hablaste tú en visión

[[psalms-89-21]]
^21^ «He encontrado a David mi servidor,

[[psalms-89-22]]
^22^ mi mano será firme para él,

[[psalms-89-23]]
^23^ «No le ha de sorprender el enemigo,

[[psalms-89-24]]
^24^ yo aplastaré a sus adversarios ante él,

[[psalms-89-25]]
^25^ «Mi lealtad y mi amor irán con él,

[[psalms-89-26]]
^26^ pondré su mano sobre el mar,

[[psalms-89-27]]
^27^ «El me invocará: ¡Tú, mi Padre,

[[psalms-89-28]]
^28^ Y yo haré de él el primogénito,

[[psalms-89-29]]
^29^ «Le guardaré mi amor por siempre,

[[psalms-89-30]]
^30^ estableceré su estirpe para siempre,

[[psalms-89-31]]
^31^ «Si sus hijos abandonan mi ley,

[[psalms-89-32]]
^32^ si profanan mis preceptos,

[[psalms-89-33]]
^33^ «castigaré su rebelión con vara,

[[psalms-89-34]]
^34^ mas no retiraré de él mi amor,

[[psalms-89-35]]
^35^ «No violaré mi alianza,

[[psalms-89-36]]
^36^ una vez he jurado por mi santidad:

[[psalms-89-37]]
^37^ «Su estirpe durará por siempre,

[[psalms-89-38]]
^38^ por siempre se mantendrá como la luna,

[[psalms-89-39]]
^39^ Pero tú has rechazado y despreciado,

[[psalms-89-40]]
^40^ has desechado la alianza con tu siervo,

[[psalms-89-41]]
^41^ Has hecho brecha en todos sus vallados,

[[psalms-89-42]]
^42^ le han saqueado todos los transeúntes,

[[psalms-89-43]]
^43^ A sus adversarios la diestra has exaltado,

[[psalms-89-44]]
^44^ has embotado el filo de su espada,

[[psalms-89-45]]
^45^ Le has quitado su cetro de esplendor,

[[psalms-89-46]]
^46^ has abreviado los días de su juventud,

[[psalms-89-47]]
^47^ ¿Hasta cuándo te esconderás, Yahveh?

[[psalms-89-48]]
^48^ Recuerda, Señor, qué es la existencia,

[[psalms-89-49]]
^49^ ¿Qué hombre podrá vivir sin ver la muerte,

[[psalms-89-50]]
^50^ ¿Dónde están tus primeros amores, Señor,

[[psalms-89-51]]
^51^ Acuérdate, Señor, del ultraje de tus siervos:

[[psalms-89-52]]
^52^ así ultrajan tus enemigos, Yahveh,

[[psalms-89-53]]
^53^ ¡Bendito sea Yahveh por siempre!
[[psalms-90]]
== Capítulo 90

[[psalms-90-1]]
^1^ Oración. De Moisés, hombre de Dios.

[[psalms-90-2]]
^2^ Antes que los montes fuesen engendrados,

[[psalms-90-3]]
^3^ Tú al polvo reduces a los hombres,

[[psalms-90-4]]
^4^ Porque mil años a tus ojos

[[psalms-90-5]]
^5^ Tú los sumerges en un sueño,

[[psalms-90-6]]
^6^ por la mañana brota y florece,

[[psalms-90-7]]
^7^ Pues por tu cólera somos consumidos,

[[psalms-90-8]]
^8^ Has puesto nuestras culpas ante ti,

[[psalms-90-9]]
^9^ Bajo tu enojo declinan todos nuestros días,

[[psalms-90-10]]
^10^ Los años de nuestra vida son unos setenta,

[[psalms-90-11]]
^11^ ¿Quién conoce la fuerza de tu cólera,

[[psalms-90-12]]
^12^ ¡Enseñanos a contar nuestros días,

[[psalms-90-13]]
^13^ ¡Vuelve, Yahveh! ¿Hasta cuándo?

[[psalms-90-14]]
^14^ Sácianos de tu amor a la mañana,

[[psalms-90-15]]
^15^ Devuélvenos en gozo los días que nos humillaste,

[[psalms-90-16]]
^16^ ¡Que se vea tu obra con tus siervos,

[[psalms-90-17]]
^17^ ¡La dulzura del Señor sea con nosotros!
[[psalms-91]]
== Capítulo 91

[[psalms-91-1]]
^1^ El que mora en el secreto de Elyón

[[psalms-91-2]]
^2^ diciendo a Yahveh: «¡Mi refugio y fortaleza,

[[psalms-91-3]]
^3^ Que él te libra de la red del cazador,

[[psalms-91-4]]
^4^ con sus plumas te cubre,

[[psalms-91-5]]
^5^ No temerás el terror de la noche,

[[psalms-91-6]]
^6^ ni la peste que avanza en las tinieblas,

[[psalms-91-7]]
^7^ Aunque a tu lado caigan mil

[[psalms-91-8]]
^8^ Basta con que mires con tus ojos,

[[psalms-91-9]]
^9^ tú que dices: «¡Mi refugio es Yahveh!»,

[[psalms-91-10]]
^10^ No ha de alcanzarte el mal,

[[psalms-91-11]]
^11^ que él dará orden sobre ti a sus ángeles

[[psalms-91-12]]
^12^ Te llevarán ellos en sus manos,

[[psalms-91-13]]
^13^ pisarás sobre el león y la víbora,

[[psalms-91-14]]
^14^ Pues él se abraza a mí, yo he de librarle;

[[psalms-91-15]]
^15^ Me llamará y le responderé;

[[psalms-91-16]]
^16^ Hartura le daré de largos días,
[[psalms-92]]
== Capítulo 92

[[psalms-92-1]]
^1^ Salmo. Cántico. Para el día de sábado.

[[psalms-92-2]]
^2^ Bueno es dar gracias a Yahveh,

[[psalms-92-3]]
^3^ publicar tu amor por la mañana,

[[psalms-92-4]]
^4^ al son del arpa de diez cuerdas y la lira,

[[psalms-92-5]]
^5^ Pues con tus hechos, Yahveh, me regocijas,

[[psalms-92-6]]
^6^ «¡Qué grandes son tus obras, Yahveh,

[[psalms-92-7]]
^7^ El hombre estúpido no entiende,

[[psalms-92-8]]
^8^ Si brotan como hierba los impíos,

[[psalms-92-9]]
^9^ mas tú, Yahveh, eres excelso por los siglos.

[[psalms-92-10]]
^10^ Mira cómo tus enemigos perecen,

[[psalms-92-11]]
^11^ Pero tú alzas mi frente como la del búfalo,

[[psalms-92-12]]
^12^ mi ojo desafía a los que me acechaban,

[[psalms-92-13]]
^13^ Florece el justo como la palmera,

[[psalms-92-14]]
^14^ Plantados en la Casa de Yahveh,

[[psalms-92-15]]
^15^ Todavía en la vejez producen fruto,

[[psalms-92-16]]
^16^ para anunciar lo recto que es Yahveh:
[[psalms-93]]
== Capítulo 93

[[psalms-93-1]]
^1^ Reina Yahveh, de majestad vestido,

[[psalms-93-2]]
^2^ Desde el principio tu trono esta fijado,

[[psalms-93-3]]
^3^ Levantan los ríos, Yahveh,

[[psalms-93-4]]
^4^ más que la voz de muchas aguas

[[psalms-93-5]]
^5^ Son veraces del todo tus dictámenes;
[[psalms-94]]
== Capítulo 94

[[psalms-94-1]]
^1^ ¡Dios de las venganzas, Yahveh,

[[psalms-94-2]]
^2^ ¡Levántate, juez de la tierra,

[[psalms-94-3]]
^3^ ¿Hasta cuándo los impíos, Yahveh,

[[psalms-94-4]]
^4^ Cacarean, dicen insolencias,

[[psalms-94-5]]
^5^ A tu pueblo, Yahveh, aplastan,

[[psalms-94-6]]
^6^ Matan al forastero y a la viuda,

[[psalms-94-7]]
^7^ Y dicen: «No lo ve Yahveh,

[[psalms-94-8]]
^8^ ¡Comprended, estúpidos del pueblo!,

[[psalms-94-9]]
^9^ El que plantó la oreja, ¿no va a oír?

[[psalms-94-10]]
^10^ El que corrige a las naciones, ¿no ha de castigar?

[[psalms-94-11]]
^11^ Yahveh, conoce los pensamientos del hombre,

[[psalms-94-12]]
^12^ Dichoso el hombre a quien corriges tú, Yahveh,

[[psalms-94-13]]
^13^ para darle descanso en los días de desgracia,

[[psalms-94-14]]
^14^ Pues Yahveh no dejará a su pueblo,

[[psalms-94-15]]
^15^ sino que el juicio volverá a la justicia,

[[psalms-94-16]]
^16^ ¿Quién se alzará por mí contra los malvados?

[[psalms-94-17]]
^17^ Si Yahveh no viniese en mi ayuda,

[[psalms-94-18]]
^18^ Cuando digo: «Vacila mi pie»,

[[psalms-94-19]]
^19^ en el colmo de mis cuitas interiores,

[[psalms-94-20]]
^20^ ¿Eres aliado tú de un tribunal de perdición,

[[psalms-94-21]]
^21^ Se atropella la vida del justo,

[[psalms-94-22]]
^22^ Mas Yahveh es para mí una ciudadela,

[[psalms-94-23]]
^23^ él hará recaer sobre ellos su maldad,
[[psalms-95]]
== Capítulo 95

[[psalms-95-1]]
^1^ Venid, cantemos gozosos a Yahveh,

[[psalms-95-2]]
^2^ con acciones de gracias vayamos ante él,

[[psalms-95-3]]
^3^ Porque es Yahveh un Dios grande,

[[psalms-95-4]]
^4^ en sus manos están las honduras de la tierra,

[[psalms-95-5]]
^5^ suyo el mar, pues él mismo lo hizo,

[[psalms-95-6]]
^6^ Entrad, adoremos, prosternémonos,

[[psalms-95-7]]
^7^ Porque él es nuestro Dios,

[[psalms-95-8]]
^8^ «No endurezcáis vuestro corazón como en Meribá,

[[psalms-95-9]]
^9^ donde me pusieron a prueba vuestros padres,

[[psalms-95-10]]
^10^ «Cuarenta años me asqueó aquella generación,

[[psalms-95-11]]
^11^ Y por eso en mi cólera juré:
[[psalms-96]]
== Capítulo 96

[[psalms-96-1]]
^1^ ¡Cantad a Yahveh un canto nuevo,

[[psalms-96-2]]
^2^ cantad a Yahveh, su nombre bendecid!

[[psalms-96-3]]
^3^ contad su gloria a las naciones,

[[psalms-96-4]]
^4^ Que grande es Yahveh, y muy digno de alabanza,

[[psalms-96-5]]
^5^ Pues nada son todos los dioses de los pueblos.

[[psalms-96-6]]
^6^ gloria y majestad están ante él,

[[psalms-96-7]]
^7^ Rendid a Yahveh, familias de los pueblos,

[[psalms-96-8]]
^8^ rendid a Yahveh la gloria de su nombre.

[[psalms-96-9]]
^9^ postraos ante Yahveh en esplendor sagrado,

[[psalms-96-10]]
^10^ Decid entre las gentes: «¡Yahveh es rey!»

[[psalms-96-11]]
^11^ ¡Alégrense los cielos, regocíjese la tierra,

[[psalms-96-12]]
^12^ exulte el campo y cuanto en él existe,

[[psalms-96-13]]
^13^ ante la faz de Yahveh, pues viene él,
[[psalms-97]]
== Capítulo 97

[[psalms-97-1]]
^1^ ¡Reina Yahveh! ¡La tierra exulte,

[[psalms-97-2]]
^2^ Nube y Bruma densa en torno a él,

[[psalms-97-3]]
^3^ Delante de él avanza fuego

[[psalms-97-4]]
^4^ iluminan el orbe sus relámpagos,

[[psalms-97-5]]
^5^ Los montes como cera se derriten

[[psalms-97-6]]
^6^ los cielos anuncian su justicia,

[[psalms-97-7]]
^7^ ¡Se avergüenzan los que sirven a los ídolos,

[[psalms-97-8]]
^8^ Sión lo oye y se alboroza,

[[psalms-97-9]]
^9^ Porque tú eres Yahveh,

[[psalms-97-10]]
^10^ Yahveh ama a los que el mal detestan,

[[psalms-97-11]]
^11^ La luz se alza para el justo,

[[psalms-97-12]]
^12^ Justos, alegraos en Yahveh,
[[psalms-98]]
== Capítulo 98

[[psalms-98-1]]
^1^ Salmo.

[[psalms-98-2]]
^2^ Yahveh ha dado a conocer su salvación,

[[psalms-98-3]]
^3^ se ha acordado de su amor y su lealtad

[[psalms-98-4]]
^4^ ¡Aclamad a Yahveh, toda la tierra,

[[psalms-98-5]]
^5^ Salmodiad para Yahveh con la cítara,

[[psalms-98-6]]
^6^ con las trompetas y al son del cuerno aclamad

[[psalms-98-7]]
^7^ Brama el mar y cuanto encierra,

[[psalms-98-8]]
^8^ los ríos baten palmas,

[[psalms-98-9]]
^9^ ante el rostro de Yahveh, pues viene
[[psalms-99]]
== Capítulo 99

[[psalms-99-1]]
^1^ Reina Yahveh, los pueblos tiemblan;

[[psalms-99-2]]
^2^ grande es Yahveh en Sión.

[[psalms-99-3]]
^3^ loen tu nombre grande y venerable:

[[psalms-99-4]]
^4^ Poderoso rey que el juicio ama,

[[psalms-99-5]]
^5^ Exaltad a Yahveh nuestro Dios,

[[psalms-99-6]]
^6^ Moisés y Aarón entre sus sacerdotes,

[[psalms-99-7]]
^7^ En la columna de nube les hablaba,

[[psalms-99-8]]
^8^ Yahveh, Dios nuestro, tú les respondías,

[[psalms-99-9]]
^9^ Exaltad a Yahveh nuestro Dios,
[[psalms-100]]
== Capítulo 100

[[psalms-100-1]]
^1^ Salmo. Para la acción de gracias.

[[psalms-100-2]]
^2^ servid a Yahveh con alegría,

[[psalms-100-3]]
^3^ Sabed que Yahveh es Dios,

[[psalms-100-4]]
^4^ ¡Entrad en sus pórticos con acciones de gracias,

[[psalms-100-5]]
^5^ Porque es bueno Yahveh,
[[psalms-101]]
== Capítulo 101

[[psalms-101-1]]
^1^ De David. Salmo.

[[psalms-101-2]]
^2^ cursaré el camino de la perfección:

[[psalms-101-3]]
^3^ no pondré delante de mis ojos

[[psalms-101-4]]
^4^ el corazón perverso está lejos de mí,

[[psalms-101-5]]
^5^ Al que infama a su prójimo en secreto,

[[psalms-101-6]]
^6^ Mis ojos, en los fieles de la tierra,

[[psalms-101-7]]
^7^ No mora dentro de mi casa

[[psalms-101-8]]
^8^ Cada mañana he de aniquilar
[[psalms-102]]
== Capítulo 102

[[psalms-102-1]]
^1^ Oración del afligido que, en su angustia, derrama su llanto

[[psalms-102-2]]
^2^ Yahveh, escucha mi oración,

[[psalms-102-3]]
^3^ ne ocultes lejos de mí tu rostro

[[psalms-102-4]]
^4^ Pues mis días en humo se disipan,

[[psalms-102-5]]
^5^ trillado como el heno, mi corazón se seca,

[[psalms-102-6]]
^6^ ante la voz de mis sollozos,

[[psalms-102-7]]
^7^ Me parezco al búho del yermo,

[[psalms-102-8]]
^8^ insomne estoy y gimo

[[psalms-102-9]]
^9^ me insultan todo el día mis enemigos,

[[psalms-102-10]]
^10^ El pan que como es la ceniza,

[[psalms-102-11]]
^11^ ante tu cólera y tu enojo,

[[psalms-102-12]]
^12^ mis días son como la sombra que declina,

[[psalms-102-13]]
^13^ Mas tú, Yahveh, permaneces para siempre,

[[psalms-102-14]]
^14^ Tú te alzarás, compadecido de Sión,

[[psalms-102-15]]
^15^ que están tus siervos encariñados de sus piedras

[[psalms-102-16]]
^16^ Y temerán las naciones el nombre de Yahveh,

[[psalms-102-17]]
^17^ cuando Yahveh reconstruya a Sión,

[[psalms-102-18]]
^18^ volverá su rostro a la oración del despojado,

[[psalms-102-19]]
^19^ Se escribirá esto para la edad futura,

[[psalms-102-20]]
^20^ que se ha inclinado Yahveh desde su altura santa,

[[psalms-102-21]]
^21^ para oír el suspiro del cautivo,

[[psalms-102-22]]
^22^ Para pregonar en Sión el nombre de Yahveh,

[[psalms-102-23]]
^23^ cuando a una se congreguen los pueblos,

[[psalms-102-24]]
^24^ El ha enervado mi fuerza en el camino,

[[psalms-102-25]]
^25^ Digo: ¡Dios mío, en la mitad de mis días no me lleves!

[[psalms-102-26]]
^26^ Desde antiguo, fundaste tú la tierra,

[[psalms-102-27]]
^27^ ellos perecen, mas tú quedas,

[[psalms-102-28]]
^28^ Pero tú siempre el mismo, no tienen fin tus años.

[[psalms-102-29]]
^29^ Los hijos de tus siervos tendrán una morada,
[[psalms-103]]
== Capítulo 103

[[psalms-103-1]]
^1^ De David.

[[psalms-103-2]]
^2^ bendice a Yahveh, alma mía,

[[psalms-103-3]]
^3^ El, que todas tus culpas perdona,

[[psalms-103-4]]
^4^ rescata tu vida de la fosa,

[[psalms-103-5]]
^5^ satura de bienes tu existencia,

[[psalms-103-6]]
^6^ Yahveh, el que hace obras de justicia,

[[psalms-103-7]]
^7^ manifestó sus caminos a Moisés,

[[psalms-103-8]]
^8^ Clemente y compasivo es Yahveh,

[[psalms-103-9]]
^9^ no se querella eternamente

[[psalms-103-10]]
^10^ no nos trata según nuestros pecados

[[psalms-103-11]]
^11^ Como se alzan los cielos por encima de la tierra,

[[psalms-103-12]]
^12^ tan lejos como está el oriente del ocaso

[[psalms-103-13]]
^13^ Cual la ternura de un padre para con sus hijos,

[[psalms-103-14]]
^14^ que él sabe de qué estamos plasmados,

[[psalms-103-15]]
^15^ ¡El hombre! Como la hierba son sus días,

[[psalms-103-16]]
^16^ pasa por él un soplo, y ya no existe,

[[psalms-103-17]]
^17^ Mas el amor de Yahveh desde siempre hasta siempre

[[psalms-103-18]]
^18^ para aquellos que guardan su alianza,

[[psalms-103-19]]
^19^ Yahveh en los cielos asentó su trono,

[[psalms-103-20]]
^20^ Bendecid a Yahveh, ángeles suyos,

[[psalms-103-21]]
^21^ Bendecid a Yahveh, todas sus huestes,

[[psalms-103-22]]
^22^ Bendecid a Yahveh, todas sus obras,
[[psalms-104]]
== Capítulo 104

[[psalms-104-1]]
^1^ ¡Alma mía, bendice a Yahveh!

[[psalms-104-2]]
^2^ arropado de luz como de un manto,

[[psalms-104-3]]
^3^ levantas sobre las aguas tus altas moradas;

[[psalms-104-4]]
^4^ tomas por mensajeros a los vientos,

[[psalms-104-5]]
^5^ Sobre sus bases asentaste la tierra,

[[psalms-104-6]]
^6^ Del océano, cual vestido, la cubriste,

[[psalms-104-7]]
^7^ al increparlas tú, emprenden la huída,

[[psalms-104-8]]
^8^ y saltan por los montes, descienden por los valles,

[[psalms-104-9]]
^9^ un término les pones que no crucen,

[[psalms-104-10]]
^10^ Haces manar las fuentes en los valles,

[[psalms-104-11]]
^11^ a todas las bestias de los campos abrevan,

[[psalms-104-12]]
^12^ sobre ellas habitan las aves de los cielos,

[[psalms-104-13]]
^13^ De tus altas moradas abrevas las montañas,

[[psalms-104-14]]
^14^ la hierba haces brotar para el ganado,

[[psalms-104-15]]
^15^ y el vino que recrea el corazón del hombre,

[[psalms-104-16]]
^16^ Se empapan bien los árboles de Yahveh,

[[psalms-104-17]]
^17^ allí ponen los pájaros su nido,

[[psalms-104-18]]
^18^ los altos montes, para los rebecos,

[[psalms-104-19]]
^19^ Hizo la luna para marcar los tiempos,

[[psalms-104-20]]
^20^ mandas tú las tinieblas, y es la noche,

[[psalms-104-21]]
^21^ los leoncillos rugen por la presa,

[[psalms-104-22]]
^22^ Cuando el sol sale, se recogen,

[[psalms-104-23]]
^23^ el hombre sale a su trabajo,

[[psalms-104-24]]
^24^ ¡Cuán numerosas tus obras, Yahveh!

[[psalms-104-25]]
^25^ Ahí está el mar, grande y de amplios brazos,

[[psalms-104-26]]
^26^ por allí circulan los navíos,

[[psalms-104-27]]
^27^ Todos ellos de ti están esperando

[[psalms-104-28]]
^28^ tú se lo das y ellos lo toman,

[[psalms-104-29]]
^29^ Escondes tu rostro y se anonadan,

[[psalms-104-30]]
^30^ Envías tu soplo y son creados,

[[psalms-104-31]]
^31^ ¡Sea por siempre la gloria de Yahveh,

[[psalms-104-32]]
^32^ El que mira a la tierra y ella tiembla,

[[psalms-104-33]]
^33^ A Yahveh mientras viva he de cantar,

[[psalms-104-34]]
^34^ ¡Oh, que mi poema le complazca!

[[psalms-104-35]]
^35^ ¡Que se acaben los pecadores en la tierra,
[[psalms-105]]
== Capítulo 105

[[psalms-105-0]]
^0^ ¡Aleluya!

[[psalms-105-1]]
^1^ ¡Dad gracias a Yahveh, aclamad su nombre,

[[psalms-105-2]]
^2^ ¡Cantadle, salmodiad para él,

[[psalms-105-3]]
^3^ gloriaos en su santo nombre,

[[psalms-105-4]]
^4^ ¡Buscad a Yahveh y su fuerza,

[[psalms-105-5]]
^5^ recordad las maravillas que él ha hecho,

[[psalms-105-6]]
^6^ Raza de Abraham, su servidor,

[[psalms-105-7]]
^7^ él, Yahveh, es nuestro Dios,

[[psalms-105-8]]
^8^ El se acuerda por siempre de su alianza,

[[psalms-105-9]]
^9^ lo que pactó con Abraham,

[[psalms-105-10]]
^10^ y que puso a Jacob como precepto,

[[psalms-105-11]]
^11^ diciendo: «Yo te daré la tierra de Canaán

[[psalms-105-12]]
^12^ Aunque ellos eran poco numerosos,

[[psalms-105-13]]
^13^ cuando iban de nación en nación,

[[psalms-105-14]]
^14^ a nadie permitió oprimirles,

[[psalms-105-15]]
^15^ «Guardaos de tocar a mis ungidos,

[[psalms-105-16]]
^16^ Llamó al hambre sobre aquel país,

[[psalms-105-17]]
^17^ delante de ellos envió a un hombre,

[[psalms-105-18]]
^18^ Sus pies vejaron con grilletes,

[[psalms-105-19]]
^19^ hasta que se cumplió su predicción,

[[psalms-105-20]]
^20^ El rey mandó a soltarle,

[[psalms-105-21]]
^21^ le erigió señor sobre su casa,

[[psalms-105-22]]
^22^ para instruir a su gusto a sus magnates,

[[psalms-105-23]]
^23^ Entonces Israel entró en Egipto,

[[psalms-105-24]]
^24^ El aumentó a su pueblo en gran manera,

[[psalms-105-25]]
^25^ cambió el corazón de éstos para que odiasen a su pueblo

[[psalms-105-26]]
^26^ Luego envió a Moisés su servidor,

[[psalms-105-27]]
^27^ que hicieron entre ellos sus señales anunciadas,

[[psalms-105-28]]
^28^ Mandó tinieblas y tinieblas hubo,

[[psalms-105-29]]
^29^ Trocó en sangre sus aguas

[[psalms-105-30]]
^30^ Pululó de ranas su país,

[[psalms-105-31]]
^31^ mandó él, y vinieron los mosquitos,

[[psalms-105-32]]
^32^ Les dio por lluvia el granizo,

[[psalms-105-33]]
^33^ hirió sus viñedos, sus higueras,

[[psalms-105-34]]
^34^ Dio la orden, y llegó la langosta,

[[psalms-105-35]]
^35^ comieron toda hierba en su país,

[[psalms-105-36]]
^36^ E hirió en su país a todo primogénito,

[[psalms-105-37]]
^37^ y a ellos los sacó con plata y oro,

[[psalms-105-38]]
^38^ Egipto se alegró de su salida,

[[psalms-105-39]]
^39^ El desplegó una nube por cubierta,

[[psalms-105-40]]
^40^ Pidieron, y trajo codornices,

[[psalms-105-41]]
^41^ abrió la roca, y brotaron las aguas,

[[psalms-105-42]]
^42^ Recordando su palabra sagrada

[[psalms-105-43]]
^43^ sacó a su pueblo en alborozo,

[[psalms-105-44]]
^44^ Y las tierras les dio de las naciones,

[[psalms-105-45]]
^45^ a fin de que garden sus preceptos
[[psalms-106]]
== Capítulo 106

[[psalms-106-1]]
^1^ ¡Aleluya!

[[psalms-106-2]]
^2^ ¿Quién dirá las proezas de Yahveh,

[[psalms-106-3]]
^3^ ¡Dichosos los que guardan el derecho,

[[psalms-106-4]]
^4^ ¡Acuérdate de mí, Yahveh,

[[psalms-106-5]]
^5^ que vea yo la dicha de tus elegidos,

[[psalms-106-6]]
^6^ Hemos pecado como nuestros padres,

[[psalms-106-7]]
^7^ nuestros padres, en Egipto,

[[psalms-106-8]]
^8^ El los salvó por amor de su nombre,

[[psalms-106-9]]
^9^ Increpó al mar de Suf y éste se secó,

[[psalms-106-10]]
^10^ los salvó de la mano del que odíaba,

[[psalms-106-11]]
^11^ El agua cubrió a sus adversarios,

[[psalms-106-12]]
^12^ Entonces ellos tuvieron fe en sus palabras

[[psalms-106-13]]
^13^ Mas pronto se olvidaron de sus obras,

[[psalms-106-14]]
^14^ en el desierto ardían de avidez,

[[psalms-106-15]]
^15^ El les concedió lo que pedían,

[[psalms-106-16]]
^16^ Y en el campamento, de Moisés tuvieron celos,

[[psalms-106-17]]
^17^ Se abre la tierra, traga a Datán,

[[psalms-106-18]]
^18^ un fuego se enciende contra su cuadrilla,

[[psalms-106-19]]
^19^ En Horeb se fabricaron un becerro,

[[psalms-106-20]]
^20^ y cambiaron su gloria

[[psalms-106-21]]
^21^ Olvidaban a Dios que les salvaba,

[[psalms-106-22]]
^22^ de prodigios en el país de Cam,

[[psalms-106-23]]
^23^ Hablaba ya de exterminarlos,

[[psalms-106-24]]
^24^ Una tierra de delicias desdeñaron,

[[psalms-106-25]]
^25^ murmuraron dentro de sus tiendas,

[[psalms-106-26]]
^26^ Y él, mano en alto, les juró

[[psalms-106-27]]
^27^ desperdigar su raza entre las naciones,

[[psalms-106-28]]
^28^ Luego se vincularon a Baal Peor

[[psalms-106-29]]
^29^ Así le irritaron con sus obras,

[[psalms-106-30]]
^30^ Entonces surgió Pinjás, zanjó,

[[psalms-106-31]]
^31^ esto se le contó como justicia

[[psalms-106-32]]
^32^ En las aguas de Meribá le enojaron,

[[psalms-106-33]]
^33^ pues le amargaron el espíritu,

[[psalms-106-34]]
^34^ No exterminaron a los pueblos

[[psalms-106-35]]
^35^ sino que se mezclaron con las gentes,

[[psalms-106-36]]
^36^ Sirvieron a sus ídolos

[[psalms-106-37]]
^37^ sacrificaban sus hijos

[[psalms-106-38]]
^38^ Sangre inocente derramaban,

[[psalms-106-39]]
^39^ Así se manchaban con sus obras,

[[psalms-106-40]]
^40^ Entonces se inflamó la cólera de Yahveh contra su pueblo,

[[psalms-106-41]]
^41^ Los entregó en mano de las gentes,

[[psalms-106-42]]
^42^ sus enemigos los tiranizaron,

[[psalms-106-43]]
^43^ Muchas veces los libró

[[psalms-106-44]]
^44^ y los miró cuando estaban en apuros,

[[psalms-106-45]]
^45^ Se acordó en favor de ellos de su alianza,

[[psalms-106-46]]
^46^ hizo que de ellos se apiadaran

[[psalms-106-47]]
^47^ ¡Sálvanos, Yahveh, Dios nuestro,

[[psalms-106-48]]
^48^ ¡Bendito sea Yahveh, Dios de Israel,
[[psalms-107]]
== Capítulo 107

[[psalms-107-0]]
^0^ ¡Aleluya!

[[psalms-107-1]]
^1^ Dad gracias a Yahveh, porque es bueno,

[[psalms-107-2]]
^2^ Que lo digan los redimidos de Yahveh,

[[psalms-107-3]]
^3^ los que ha reunido de entre los países,

[[psalms-107-4]]
^4^ En el desierto erraban, por la estepa,

[[psalms-107-5]]
^5^ hambrientos, y sedientos,

[[psalms-107-6]]
^6^ Y hacia Yahveh gritaron en su apuro,

[[psalms-107-7]]
^7^ les condujo por camino recto,

[[psalms-107-8]]
^8^ ¡Den gracias a Yahveh por su amor,

[[psalms-107-9]]
^9^ Porque él sació el alma anhelante,

[[psalms-107-10]]
^10^ Habitantes de tiniebla y sombra,

[[psalms-107-11]]
^11^ por haber sido rebeldes a las órdenes de Dios

[[psalms-107-12]]
^12^ él sometió su corazón a la fatiga,

[[psalms-107-13]]
^13^ Y hacia Yahveh gritaron en su apuro,

[[psalms-107-14]]
^14^ los sacó de la tiniebla y de la sombra,

[[psalms-107-15]]
^15^ ¡Den gracias a Yahveh por su amor,

[[psalms-107-16]]
^16^ Pues las puertas de bronce quebrantó,

[[psalms-107-17]]
^17^ Embotados de resultas de sus yerros,

[[psalms-107-18]]
^18^ todo manjar les daba náusea,

[[psalms-107-19]]
^19^ Y hacia Yahveh gritaron en su apuro,

[[psalms-107-20]]
^20^ su palabra envió para sanarlos

[[psalms-107-21]]
^21^ ¡Den gracias a Yahveh por su amor,

[[psalms-107-22]]
^22^ Ofrezcan sacrificios de acción de gracias, y sus obras

[[psalms-107-23]]
^23^ Los que a la mar se hicieron en sus naves,

[[psalms-107-24]]
^24^ vieron las obras de Yahveh,

[[psalms-107-25]]
^25^ Dijo, y suscitó un viento de borrasca,

[[psalms-107-26]]
^26^ subiendo hasta los cielos, bajando hasta el abismo,

[[psalms-107-27]]
^27^ dando vuelcos, vacilando como un ebrio,

[[psalms-107-28]]
^28^ Y hacia Yahveh gritaron en su apuro,

[[psalms-107-29]]
^29^ a silencio redujo la borrasca,

[[psalms-107-30]]
^30^ Se alegraron de verlas amansarse,

[[psalms-107-31]]
^31^ ¡Den gracias a Yahveh por su amor,

[[psalms-107-32]]
^32^ ¡Ensálcenle en la asamblea del pueblo,

[[psalms-107-33]]
^33^ El cambia los ríos en desierto,

[[psalms-107-34]]
^34^ la tierra fértil en salinas,

[[psalms-107-35]]
^35^ Y él cambia el desierto en un estanque,

[[psalms-107-36]]
^36^ Allí asienta a los hambrientos,

[[psalms-107-37]]
^37^ Y siembran campos, plantan viñas,

[[psalms-107-38]]
^38^ El los bendice y crecen mucho

[[psalms-107-39]]
^39^ Menguados estaban, y abatidos

[[psalms-107-40]]
^40^ El que vierte desprecio sobre príncipes,

[[psalms-107-41]]
^41^ Mas él recobra de la miseria al pobre,

[[psalms-107-42]]
^42^ los hombres rectos lo ven y se recrean,

[[psalms-107-43]]
^43^ ¿Hay algún sabio? ¡Que garde estas cosas,
[[psalms-108]]
== Capítulo 108

[[psalms-108-1]]
^1^ Cántico. Salmo. De David.

[[psalms-108-2]]
^2^ A punto está mi corazón, oh Dios,

[[psalms-108-3]]
^3^ ¡despertad, arpa y cítara!

[[psalms-108-4]]
^4^ Te alabaré entre los pueblos, Yahveh,

[[psalms-108-5]]
^5^ porque tu amor es grande hasta los cielos,

[[psalms-108-6]]
^6^ ¡Alzate, oh Dios, sobre los cielos,

[[psalms-108-7]]
^7^ Para que tus amados salgan libres,

[[psalms-108-8]]
^8^ Ha hablado Dios en su santuario:

[[psalms-108-9]]
^9^ «Mío es Galaad, mío Manasés,

[[psalms-108-10]]
^10^ «Moab, la vasija en que me lavo.

[[psalms-108-11]]
^11^ ¿Quién me conducirá hasta la plaza fuerte,

[[psalms-108-12]]
^12^ ¿No eres tú, oh Dios, que nos has rechazado

[[psalms-108-13]]
^13^ ¡Danos ayuda contra el adversario,

[[psalms-108-14]]
^14^ ¡Con Dios hemos de hacer proezas,
[[psalms-109]]
== Capítulo 109

[[psalms-109-1]]
^1^ Del maestro de coro. De David. Salmo.

[[psalms-109-2]]
^2^ Boca de impío, boca de engaño,

[[psalms-109-3]]
^3^ con palabras de odio me envuelven,

[[psalms-109-4]]
^4^ En pago de mi amor, se me acusa,

[[psalms-109-5]]
^5^ se me devuelve mal por bien

[[psalms-109-6]]
^6^ «¡Suscita a un impío contra él,

[[psalms-109-7]]
^7^ que en el juicio resulte culpable,

[[psalms-109-8]]
^8^ «¡Sean pocos sus días,

[[psalms-109-9]]
^9^ queden sus hijos huérfanos

[[psalms-109-10]]
^10^ «¡Anden sus hijos errantes, mendigando,

[[psalms-109-11]]
^11^ el acreedor le atrape todo lo que tiene,

[[psalms-109-12]]
^12^ «¡Ni uno solo tenga con él amor,

[[psalms-109-13]]
^13^ sea dada al exterminio su posteridad,

[[psalms-109-14]]
^14^ «¡Sea ante Yahveh recordada la culpa de sus padres,

[[psalms-109-15]]
^15^ estén ante Yahveh constantemente,

[[psalms-109-16]]
^16^ Porque él no se acordó de actuar con amor:

[[psalms-109-17]]
^17^ amó la maldición: sobre él recaiga,

[[psalms-109-18]]
^18^ Se vistió de maldición como de un manto:

[[psalms-109-19]]
^19^ ¡Séale cual vestido que le cubra,

[[psalms-109-20]]
^20^ ¡Tal sea de parte de Yahveh la paga de mis acusadores,

[[psalms-109-21]]
^21^ ¡Y tú, Señor Yahveh, actúa por mí en gracia de tu nombre,

[[psalms-109-22]]
^22^ Porque soy pobre y desdichado,

[[psalms-109-23]]
^23^ cual sombra que declina me voy yendo,

[[psalms-109-24]]
^24^ Por tanto ayuno se doblan mis rodillas,

[[psalms-109-25]]
^25^ me he hecho el insulto de ellos,

[[psalms-109-26]]
^26^ ¡Ayúdame, Yahveh, Dios mío,

[[psalms-109-27]]
^27^ ¡Sepan ellos que tu mano es ésta,

[[psalms-109-28]]
^28^ ¡Maldigan ellos, pero tú bendice,

[[psalms-109-29]]
^29^ ¡Los que me acusan queden vestidos de ignominia,

[[psalms-109-30]]
^30^ ¡Copiosas gracias a Yahveh en mi boca,

[[psalms-109-31]]
^31^ porque él se pone a la diestra del pobre
[[psalms-110]]
== Capítulo 110

[[psalms-110-1]]
^1^ De David. Salmo.

[[psalms-110-2]]
^2^ El cetro de tu poder lo extenderá Yahveh desde Sión:

[[psalms-110-3]]
^3^ Para ti el principado el día de tu nacimiento,

[[psalms-110-4]]
^4^ Lo ha jurado Yahveh y no ha de retractarse:

[[psalms-110-5]]
^5^ A tu diestra, Señor,

[[psalms-110-6]]
^6^ sentencia a las naciones, amontona cadáveres,

[[psalms-110-7]]
^7^ En el camino bebe del torrente,
[[psalms-111]]
== Capítulo 111

[[psalms-111-1]]
^1^ ¡Aleluya!

[[psalms-111-2]]
^2^ Guímel. Grandes son las obras de Yahveh,

[[psalms-111-3]]
^3^ He. Esplendor y majestad su obra,

[[psalms-111-4]]
^4^ Zain. De sus maravillas ha dejado un memorial.

[[psalms-111-5]]
^5^ Tet. Ha dado alimento a quienes le temen,

[[psalms-111-6]]
^6^ Kaf. Ha revelado a su pueblo el poder de sus obras,

[[psalms-111-7]]
^7^ Mem. Verdad y justicia, las obras de sus manos,

[[psalms-111-8]]
^8^ Sámek. afirmadas para siempre jamás,

[[psalms-111-9]]
^9^ Pe. Ha enviado redención a su pueblo,

[[psalms-111-10]]
^10^ Res. Principio del saber, el temor de Yahveh;
[[psalms-112]]
== Capítulo 112

[[psalms-112-1]]
^1^ ¡Aleluya!

[[psalms-112-2]]
^2^ Guímel. Fuerte será en la tierra su estirpe,

[[psalms-112-3]]
^3^ He. Hacienda y riquezas en su casa,

[[psalms-112-4]]
^4^ Zain En las tinieblas brilla, como luz de los rectos,

[[psalms-112-5]]
^5^ Tet. Feliz el hombre que se apiada y presta,

[[psalms-112-6]]
^6^ Kaf. No, no será conmovido jamás,

[[psalms-112-7]]
^7^ Mem. no tiene que temer noticias malas,

[[psalms-112-8]]
^8^ Sámek. Seguro está su corazón, no teme:

[[psalms-112-9]]
^9^ Pe. Con largueza da a los pobres;

[[psalms-112-10]]
^10^ Res. Lo ve el impío y se enfurece,
[[psalms-113]]
== Capítulo 113

[[psalms-113-1]]
^1^ ¡Aleluya!

[[psalms-113-2]]
^2^ ¡Bendito sea el nombre de Yahveh,

[[psalms-113-3]]
^3^ ¡De la salida del sol hasta su ocaso,

[[psalms-113-4]]
^4^ ¡Excelso sobre todas las naciones Yahveh,

[[psalms-113-5]]
^5^ ¿Quién como Yahveh, nuestro Dios,

[[psalms-113-6]]
^6^ y se abaja para ver

[[psalms-113-7]]
^7^ El levanta del polvo al desvalido,

[[psalms-113-8]]
^8^ para sentarle con los príncipes,

[[psalms-113-9]]
^9^ El asienta a la estéril en su casa,
[[psalms-114]]
== Capítulo 114

[[psalms-114-0]]
^0^ ¡Aleluya!

[[psalms-114-1]]
^1^ Cuando Israel salió de Egipto,

[[psalms-114-2]]
^2^ se hizo Judá su santuario,

[[psalms-114-3]]
^3^ Lo vio la mar y huyó,

[[psalms-114-4]]
^4^ los montes brincaron lo mismo que carneros,

[[psalms-114-5]]
^5^ Mar, ¿qué es lo que tienes para huir,

[[psalms-114-6]]
^6^ montes, para saltar como carneros,

[[psalms-114-7]]
^7^ ¡Tiembla, tierra, ante la faz del Dueño,

[[psalms-114-8]]
^8^ aquel que cambia la peña en un estanque,
[[psalms-115]]
== Capítulo 115

[[psalms-115-1]]
^1^ ¡No a nosotros, Yahveh, no a nosotros,

[[psalms-115-2]]
^2^ ¿Por qué han de decir las gentes: «¿Dónde está su Dios?»

[[psalms-115-3]]
^3^ Nuestro Dios está en los cielos,

[[psalms-115-4]]
^4^ Plata y oro son sus ídolos,

[[psalms-115-5]]
^5^ Tienen boca y no hablan,

[[psalms-115-6]]
^6^ tienen oídos y no oyen,

[[psalms-115-7]]
^7^ Tienen manos y no palpan,

[[psalms-115-8]]
^8^ Como ellos serán los que los hacen,

[[psalms-115-9]]
^9^ Casa de Israel, confía en Yahveh,

[[psalms-115-10]]
^10^ casa de Aarón, confía en Yahveh,

[[psalms-115-11]]
^11^ los que teméis a Yahveh, confiad en Yahveh,

[[psalms-115-12]]
^12^ Yahveh se acuerda de nosotros, él bendecirá,

[[psalms-115-13]]
^13^ bendecirá a los que temen a Yahveh,

[[psalms-115-14]]
^14^ ¡Yahveh os acreciente

[[psalms-115-15]]
^15^ ¡Benditos vosotros de Yahveh,

[[psalms-115-16]]
^16^ Los cielos, son los cielos de Yahveh,

[[psalms-115-17]]
^17^ No alaban los muertos a Yahveh,

[[psalms-115-18]]
^18^ mas nosotros, los vivos, a Yahveh bendecimos,
[[psalms-116]]
== Capítulo 116

[[psalms-116-0]]
^0^ ¡Aleluya!

[[psalms-116-1]]
^1^ Yo amo, porque Yahveh escucha

[[psalms-116-2]]
^2^ porque hacia mí su oído inclina

[[psalms-116-3]]
^3^ Los lazos de la muerte me aferraban,

[[psalms-116-4]]
^4^ y el nombre de Yahveh invoqué:

[[psalms-116-5]]
^5^ Tierno es Yahveh y justo,

[[psalms-116-6]]
^6^ Yahveh guarda a los pequeños,

[[psalms-116-7]]
^7^ Vuelve, alma mía, a tu reposo,

[[psalms-116-8]]
^8^ Ha guardado mi alma de la muerte, mis ojos de las lágrimas,

[[psalms-116-9]]
^9^ Caminaré en la presencia de Yahveh

[[psalms-116-10]]
^10^ ¡Tengo fe, aún cuando digo:

[[psalms-116-11]]
^11^ yo que he dicho en mi consternación:

[[psalms-116-12]]
^12^ ¿Cómo a Yahveh podré pagar

[[psalms-116-13]]
^13^ La copa de salvación levantaré,

[[psalms-116-14]]
^14^ Cumpliré mis votos a Yahveh,

[[psalms-116-15]]
^15^ Mucho cuesta a los ojos de Yahveh

[[psalms-116-16]]
^16^ ¡Ah, Yahveh, yo soy tu siervo,

[[psalms-116-17]]
^17^ Sacrificio te ofreceré de acción de gracias,

[[psalms-116-18]]
^18^ Cumpliré mis votos a Yahveh,

[[psalms-116-19]]
^19^ en los atrios de la Casa de Yahveh,
[[psalms-117]]
== Capítulo 117

[[psalms-117-0]]
^0^ ¡Aleluya!

[[psalms-117-1]]
^1^ ¡Alabad a Yahveh, todas las naciones,

[[psalms-117-2]]
^2^ Porque es fuerte su amor hacia nosotros,
[[psalms-118]]
== Capítulo 118

[[psalms-118-0]]
^0^ ¡Aleluya!

[[psalms-118-1]]
^1^ ¡Dad gracias a Yahveh, porque es bueno,

[[psalms-118-2]]
^2^ ¡Diga la casa de Israel:

[[psalms-118-3]]
^3^ ¡Diga la casa de Aarón:

[[psalms-118-4]]
^4^ ¡Digan los que temen a Yahveh:

[[psalms-118-5]]
^5^ En mi angustia hacia Yahveh grité,

[[psalms-118-6]]
^6^ Yahveh está por mí, no tengo miedo,

[[psalms-118-7]]
^7^ Yahveh está por mí, entre los que me ayudan,

[[psalms-118-8]]
^8^ Mejor es refugiarse en Yahveh

[[psalms-118-9]]
^9^ mejor es refugiarse en Yahveh

[[psalms-118-10]]
^10^ Me rodeaban todos los gentiles:

[[psalms-118-11]]
^11^ me rodeaban, me asediaban:

[[psalms-118-12]]
^12^ Me rodeaban como avispas,

[[psalms-118-13]]
^13^ Se me empujó, se me empujó para abatirme,

[[psalms-118-14]]
^14^ mi fuerza y mi cántico es Yahveh,

[[psalms-118-15]]
^15^ Clamor de júbilo y salvación,

[[psalms-118-16]]
^16^ excelsa la diestra de Yahveh,

[[psalms-118-17]]
^17^ No, no he de morir, que viviré,

[[psalms-118-18]]
^18^ me castigó, me castigó Yahveh,

[[psalms-118-19]]
^19^ ¡Abridme las puertas de justicia,

[[psalms-118-20]]
^20^ Aquí está la puerta de Yahveh,

[[psalms-118-21]]
^21^ Gracias te doy, porque me has respondido,

[[psalms-118-22]]
^22^ La piedra que los constructores desecharon

[[psalms-118-23]]
^23^ esta ha sido la obra de Yahveh,

[[psalms-118-24]]
^24^ ¡Este es el día que Yahveh ha hecho,

[[psalms-118-25]]
^25^ ¡Ah, Yahveh, da la salvación!

[[psalms-118-26]]
^26^ ¡Bendito el que viene en el nombre de Yahveh!

[[psalms-118-27]]
^27^ Yahveh es Dios, él nos ilumina.

[[psalms-118-28]]
^28^ Tú eres mi Dios, yo te doy gracias,

[[psalms-118-29]]
^29^ ¡Dad gracias a Yahveh, porque es bueno,
[[psalms-119]]
== Capítulo 119

[[psalms-119-1]]
^1^ Alef Dichosos los que van por camino perfecto,

[[psalms-119-2]]
^2^ Dichosos los que guardan sus dictámenes,

[[psalms-119-3]]
^3^ y los que, sin cometer iniquidad,

[[psalms-119-4]]
^4^ Tú tus ordenanzas promulgaste,

[[psalms-119-5]]
^5^ ¡Ojalá mis caminos se aseguren

[[psalms-119-6]]
^6^ Entonces no tendré vergüenza alguna

[[psalms-119-7]]
^7^ Con rectitud de corazón te daré gracias,

[[psalms-119-8]]
^8^ Tus preceptos, los observaré,

[[psalms-119-9]]
^9^ Bet. ¿Cómo el joven guardará puro su camino?

[[psalms-119-10]]
^10^ De todo corazón ando buscándote,

[[psalms-119-11]]
^11^ Dentro del corazón he guardado tu promesa,

[[psalms-119-12]]
^12^ Bendito tú, Yahveh,

[[psalms-119-13]]
^13^ Con mis labios he contado

[[psalms-119-14]]
^14^ En el camino de tus dictámenes me recreo

[[psalms-119-15]]
^15^ En tus ordenanzas quiero meditar

[[psalms-119-16]]
^16^ En tus preceptos tengo mis delicias,

[[psalms-119-17]]
^17^ Guímel. Haz merced a tu siervo y viviré.

[[psalms-119-18]]
^18^ Abre mis ojos para que contemple

[[psalms-119-19]]
^19^ Un forastero soy sobre la tierra,

[[psalms-119-20]]
^20^ Mi alma se consume deseando

[[psalms-119-21]]
^21^ Tú increpas a los soberbios, los malditos,

[[psalms-119-22]]
^22^ Echa lejos de mí oprobio y menosprecio,

[[psalms-119-23]]
^23^ Aunque los príncipes hablen en sesión contra mí,

[[psalms-119-24]]
^24^ Tus dictámenes hacen mis delicias,

[[psalms-119-25]]
^25^ Dálet. Mi alma está pegada al polvo,

[[psalms-119-26]]
^26^ Mis caminos expuse, y tú me respondiste,

[[psalms-119-27]]
^27^ Hazme entender el camino de tus ordenanzas,

[[psalms-119-28]]
^28^ Se va en lágrimas mi alma por el tedio,

[[psalms-119-29]]
^29^ Aléjame del camino de mentira,

[[psalms-119-30]]
^30^ He escogido el camino de la lealtad,

[[psalms-119-31]]
^31^ A tus dictámenes me mantengo adherido,

[[psalms-119-32]]
^32^ Corro por el camino de tus mandamientos,

[[psalms-119-33]]
^33^ He. Enséñame, Yahveh, el camino de tus preceptos,

[[psalms-119-34]]
^34^ Hazme entender, para guardar tu ley

[[psalms-119-35]]
^35^ Llévame por la senda de tus mandamientos

[[psalms-119-36]]
^36^ Inclina mi corazón hacia tus dictámenes,

[[psalms-119-37]]
^37^ Aparta mis ojos de mirar vanidades,

[[psalms-119-38]]
^38^ Mantén a tu siervo tu promesa,

[[psalms-119-39]]
^39^ Aparta de mí el oprobio que me espanta,

[[psalms-119-40]]
^40^ Mira que deseo tus ordenanzas,

[[psalms-119-41]]
^41^ Vau. ¡Llegue hasta mí tu amor, Yahveh,

[[psalms-119-42]]
^42^ Y daré respuesta al que me insulta,

[[psalms-119-43]]
^43^ No quites de mi boca la palabra de verdad,

[[psalms-119-44]]
^44^ Yo observaré sin descanso tu ley

[[psalms-119-45]]
^45^ Y andaré por camino anchuroso,

[[psalms-119-46]]
^46^ De tus dictámenes hablaré ante los reyes,

[[psalms-119-47]]
^47^ Y me deleitaré en tus mandamientos,

[[psalms-119-48]]
^48^ Tiendo mis manos hacia tus mandamientos,

[[psalms-119-49]]
^49^ Zain. Recuerda la palabra dada a tu servidor,

[[psalms-119-50]]
^50^ Este es mi consuelo en mi miseria:

[[psalms-119-51]]
^51^ Los soberbios me insultan hasta el colmo,

[[psalms-119-52]]
^52^ Me acuerdo de tus juicios de otro tiempo,

[[psalms-119-53]]
^53^ Me arrebata el furor por los impíos

[[psalms-119-54]]
^54^ Tus preceptos son cantares para mí

[[psalms-119-55]]
^55^ Me acuerdo por la noche de tu nombre, Yahveh,

[[psalms-119-56]]
^56^ Esta es mi tarea:

[[psalms-119-57]]
^57^ Jet. Mi porción, Yahveh, he dicho,

[[psalms-119-58]]
^58^ Con todo el corazón busco tu favor,

[[psalms-119-59]]
^59^ He examinado mis caminos

[[psalms-119-60]]
^60^ Me doy prisa y no me tardo

[[psalms-119-61]]
^61^ Las redes de los impíos me aprisionan,

[[psalms-119-62]]
^62^ Me levanto a medianoche a darte gracias

[[psalms-119-63]]
^63^ Amigo soy de todos los que te temen

[[psalms-119-64]]
^64^ De tu amor, Yahveh, está la tierra llena,

[[psalms-119-65]]
^65^ Tet. Has sido generoso con tu siervo,

[[psalms-119-66]]
^66^ Cordura y sabiduría enséñame,

[[psalms-119-67]]
^67^ Antes de ser humillado, me descarriaba,

[[psalms-119-68]]
^68^ Tú, que eres bueno y bienhechor,

[[psalms-119-69]]
^69^ Los soberbios me enredan con mentira,

[[psalms-119-70]]
^70^ Como de grasa su corazón está embotado.

[[psalms-119-71]]
^71^ Un bien para mí ser humillado,

[[psalms-119-72]]
^72^ Un bien para mí la ley de tu boca,

[[psalms-119-73]]
^73^ Yod. Tus manos me han hecho y me han formado,

[[psalms-119-74]]
^74^ Los que te temen me ven con alegría,

[[psalms-119-75]]
^75^ Yo sé, Yahveh, que son justos tus juicios,

[[psalms-119-76]]
^76^ Sea tu amor consuelo para mí,

[[psalms-119-77]]
^77^ Me alcancen tus ternuras y viviré,

[[psalms-119-78]]
^78^ Sean confundidos los soberbios que me afligen con mentira,

[[psalms-119-79]]
^79^ Vuélvanse hacia mí los que te temen,

[[psalms-119-80]]
^80^ Sea mi corazón perfecto en tus preceptos,

[[psalms-119-81]]
^81^ Kaf. En pos de tu salvación mi alma languidece,

[[psalms-119-82]]
^82^ Languidecen mis ojos en pos de tu promesa

[[psalms-119-83]]
^83^ Aun hecho igual que un pellejo que se ahúma,

[[psalms-119-84]]
^84^ ¿Cuántos serán los días de tu siervo?

[[psalms-119-85]]
^85^ Los soberbios han cavado fosas para mí

[[psalms-119-86]]
^86^ Todos tus mandamientos son verdad,

[[psalms-119-87]]
^87^ Poco falta para que me borren de la tierra,

[[psalms-119-88]]
^88^ Según tu amor dame la vida,

[[psalms-119-89]]
^89^ Lámed. Para siempre, Yahveh, tu palabra,

[[psalms-119-90]]
^90^ Por todas las edades tu verdad,

[[psalms-119-91]]
^91^ Por tus juicios subsiste todo hasta este día,

[[psalms-119-92]]
^92^ Si tu ley no hubiera sido mi delicia,

[[psalms-119-93]]
^93^ Jamás olvidaré tus ordenanzas,

[[psalms-119-94]]
^94^ Tuyo soy, sálvame,

[[psalms-119-95]]
^95^ Para perderme me acechan los impíos,

[[psalms-119-96]]
^96^ De todo lo perfecto he visto el límite:

[[psalms-119-97]]
^97^ Mem. ¡Oh, cuánto amo tu ley!

[[psalms-119-98]]
^98^ Más sabio me haces que mis enemigos por tu mandamiento,

[[psalms-119-99]]
^99^ Tengo más prudencia que todos mis maestros,

[[psalms-119-100]]
^100^ Poseo más cordura que los viejos,

[[psalms-119-101]]
^101^ Retraigo mis pasos de toda mala senda

[[psalms-119-102]]
^102^ De tus juicios no me aparto,

[[psalms-119-103]]
^103^ ¡Cuán dulce al paladar me es tu promesa,

[[psalms-119-104]]
^104^ Por tus ordenanzas cobro inteligencia,

[[psalms-119-105]]
^105^ Nun. Para mis pies antorcha es tu palabra,

[[psalms-119-106]]
^106^ He jurado, y he de mantenerlo,

[[psalms-119-107]]
^107^ Humillado en exceso estoy, Yahveh,

[[psalms-119-108]]
^108^ Acepta los votos de mi boca, Yahveh,

[[psalms-119-109]]
^109^ Mi alma está en mis manos sin cesar,

[[psalms-119-110]]
^110^ Me tienden un lazo los impíos,

[[psalms-119-111]]
^111^ Tus dictámenes son mi herencia por siempre,

[[psalms-119-112]]
^112^ Inclino mi corazón a practicar tus preceptos,

[[psalms-119-113]]
^113^ Sámek. Aborrezco la doblez

[[psalms-119-114]]
^114^ Mi refugio y mi escudo eres tú,

[[psalms-119-115]]
^115^ ¡Apartaos de mí, malvados,

[[psalms-119-116]]
^116^ Sosténme conforme a tu promesa, y viviré,

[[psalms-119-117]]
^117^ Sé tú mi apoyo, y seré salvo,

[[psalms-119-118]]
^118^ Tú deshaces a todos los que se desvían de tus preceptos,

[[psalms-119-119]]
^119^ Tienes por escoria a todos los impíos de la tierra,

[[psalms-119-120]]
^120^ Por tu terror tiembla mi carne,

[[psalms-119-121]]
^121^ Ain. Juicio y justicia he practicado,

[[psalms-119-122]]
^122^ Sé fiador de tu siervo para el bien,

[[psalms-119-123]]
^123^ En pos de tu salvación languidecen mis ojos,

[[psalms-119-124]]
^124^ Según tu amor trata a tu siervo,

[[psalms-119-125]]
^125^ Yo soy tu servidor, hazme entender,

[[psalms-119-126]]
^126^ Ya es hora de actuar, Yahveh,

[[psalms-119-127]]
^127^ Por eso amo yo tus mandamientos

[[psalms-119-128]]
^128^ Por eso me guío por todas tus ordenanzas

[[psalms-119-129]]
^129^ Pe. Maravillas son tus dictámenes,

[[psalms-119-130]]
^130^ Al abrirse, tus palabras iluminan

[[psalms-119-131]]
^131^ Abro mi boca franca, y hondo aspiro,

[[psalms-119-132]]
^132^ Vuélvete a mí y tenme piedad,

[[psalms-119-133]]
^133^ Mis pasos asegura en tu promesa,

[[psalms-119-134]]
^134^ Rescátame de la opresión del hombre,

[[psalms-119-135]]
^135^ Haz que brille tu faz para tu siervo,

[[psalms-119-136]]
^136^ Mis ojos destilan ríos de lágrimas,

[[psalms-119-137]]
^137^ Sade. ¡Justo eres tú, Yahveh,

[[psalms-119-138]]
^138^ Con justicia impones tus dictámenes,

[[psalms-119-139]]
^139^ Mi celo me consume,

[[psalms-119-140]]
^140^ Acendrada en extremo es tu promesa,

[[psalms-119-141]]
^141^ Pequeño soy y despreciado,

[[psalms-119-142]]
^142^ Justicia eterna es tu justicia,

[[psalms-119-143]]
^143^ Angustia y opresión me han alcanzado,

[[psalms-119-144]]
^144^ Justicia eterna tus dictámenes,

[[psalms-119-145]]
^145^ Qof. Invoco con todo el corazón, respóndeme, Yahveh,

[[psalms-119-146]]
^146^ Yo te invoco, sálvame,

[[psalms-119-147]]
^147^ Me adelanto a la aurora y pido auxilio,

[[psalms-119-148]]
^148^ Mis ojos se adelantan a las vigilias de la noche,

[[psalms-119-149]]
^149^ Por tu amor, Yahveh, escucha mi voz,

[[psalms-119-150]]
^150^ Se acercan a la infamia los que me persiguen,

[[psalms-119-151]]
^151^ Tú estás cerca, Yahveh,

[[psalms-119-152]]
^152^ De tus dictámenes sé desde hace tiempo

[[psalms-119-153]]
^153^ Res Mira mi aflicción y líbrame,

[[psalms-119-154]]
^154^ Aboga por mi causa tú, rescátame,

[[psalms-119-155]]
^155^ Lejos de los impíos la salvación,

[[psalms-119-156]]
^156^ Muchas son tus ternuras, Yahveh,

[[psalms-119-157]]
^157^ Numerosos mis perseguidores y adversarios,

[[psalms-119-158]]
^158^ He visto a los traidores, me disgusta

[[psalms-119-159]]
^159^ Mira que amo tus ordenanzas, Yahveh,

[[psalms-119-160]]
^160^ Es verdad el principio de tu palabra,

[[psalms-119-161]]
^161^ Sin. Príncipes me persiguen sin razón,

[[psalms-119-162]]
^162^ Me regocijo en tu promesa

[[psalms-119-163]]
^163^ La mentira detesto y abomino,

[[psalms-119-164]]
^164^ Siete veces al día te alabo

[[psalms-119-165]]
^165^ Mucha es la paz de los que aman tu ley,

[[psalms-119-166]]
^166^ Espero tu salvación, Yahveh,

[[psalms-119-167]]
^167^ Mi alma guarda tus dictámenes,

[[psalms-119-168]]
^168^ Guardo tus ordenanzas y dictámenes

[[psalms-119-169]]
^169^ Tau. Mi grito llegue hasta tu faz, Yahveh,

[[psalms-119-170]]
^170^ Mi súplica llegue ante tu rostro,

[[psalms-119-171]]
^171^ Mis labios proclaman tu alabanza,

[[psalms-119-172]]
^172^ Mi lengua repita tu promesa,

[[psalms-119-173]]
^173^ Venga tu mano en mi socorro,

[[psalms-119-174]]
^174^ Anhelo tu salvación, Yahveh,

[[psalms-119-175]]
^175^ Viva mi alma para alabarte,

[[psalms-119-176]]
^176^ Me he descarriado como oveja perdida:
[[psalms-120]]
== Capítulo 120

[[psalms-120-1]]
^1^ Canción de las subidas.

[[psalms-120-2]]
^2^ ¡Yahveh, libra mi alma del labio mentiroso,

[[psalms-120-3]]
^3^ ¿Qué te dará y qué te añadirá,

[[psalms-120-4]]
^4^ ¡Flechas de guerrero afiladas

[[psalms-120-5]]
^5^ ¡Qué desgracia para mí vivir en Mések,

[[psalms-120-6]]
^6^ Harto ha vivido ya mi alma

[[psalms-120-7]]
^7^ Que si yo hablo de paz,
[[psalms-121]]
== Capítulo 121

[[psalms-121-1]]
^1^ Canción para las subidas.

[[psalms-121-2]]
^2^ Mi auxilio me viene de Yahveh,

[[psalms-121-3]]
^3^ ¡No deje él titubear tu pie!

[[psalms-121-4]]
^4^ No, no duerme ni dormita

[[psalms-121-5]]
^5^ Yahveh es tu guardián,

[[psalms-121-6]]
^6^ De día el sol no te hará daño,

[[psalms-121-7]]
^7^ Te guarda Yahveh de todo mal,

[[psalms-121-8]]
^8^ Yahveh guarda tus salidas y entradas,
[[psalms-122]]
== Capítulo 122

[[psalms-122-1]]
^1^ Canción de las subidas. De David.

[[psalms-122-2]]
^2^ ¡Ya estamos, ya se posan nuestros pies

[[psalms-122-3]]
^3^ Jerusalén, construida cual ciudad

[[psalms-122-4]]
^4^ a donde suben las tribus,

[[psalms-122-5]]
^5^ Porque allí están los tronos para el juicio,

[[psalms-122-6]]
^6^ Pedid la paz para Jerusalén:

[[psalms-122-7]]
^7^ haya paz en tus muros,

[[psalms-122-8]]
^8^ Por amor de mis hermanos y de mis amigos,

[[psalms-122-9]]
^9^ ¡Por amor de la Casa de Yahveh nuestro Dios,
[[psalms-123]]
== Capítulo 123

[[psalms-123-1]]
^1^ Canción de las subidas.

[[psalms-123-2]]
^2^ míralos, como los ojos de los siervos

[[psalms-123-3]]
^3^ ¡Ten piedad de nosotros, Yahveh, ten piedad de nosotros,

[[psalms-123-4]]
^4^ ¡Nuestra alma está por demás saturada
[[psalms-124]]
== Capítulo 124

[[psalms-124-1]]
^1^ Canción de las subidas. De David.

[[psalms-124-2]]
^2^ si Yahveh no hubiera estado por nosotros,

[[psalms-124-3]]
^3^ vivos entonces nos habrían tragado

[[psalms-124-4]]
^4^ Entonces las aguas nos habrían anegado,

[[psalms-124-5]]
^5^ habrían pasado entonces sobre nuestra alma

[[psalms-124-6]]
^6^ ¡Bendito sea Yahveh que no nos hizo

[[psalms-124-7]]
^7^ Nuestra alma como un pájaro escapó

[[psalms-124-8]]
^8^ nuestro socorro en el nombre de Yahveh,
[[psalms-125]]
== Capítulo 125

[[psalms-125-1]]
^1^ Canción de las subidas.

[[psalms-125-2]]
^2^ ¡Jerusalén, de montes rodeada!

[[psalms-125-3]]
^3^ Jamás ha de caer el cetro de impiedad

[[psalms-125-4]]
^4^ Haz bien, Yahveh, a los buenos,

[[psalms-125-5]]
^5^ ¡Mas a los que yerran por sus caminos tortuosos,
[[psalms-126]]
== Capítulo 126

[[psalms-126-1]]
^1^ Canción de las subidas.

[[psalms-126-2]]
^2^ entonces se llenó de risa nuestra boca

[[psalms-126-3]]
^3^ ¡Sí, grandes cosas hizo con nosotros Yahveh,

[[psalms-126-4]]
^4^ ¡Haz volver, Yahveh, a nuestros cautivos

[[psalms-126-5]]
^5^ Los que siembran con lágrimas

[[psalms-126-6]]
^6^ Al ir, va llorando,
[[psalms-127]]
== Capítulo 127

[[psalms-127-1]]
^1^ Canción de las subidas. De Salomón.

[[psalms-127-2]]
^2^ En vano madrugáis a levantaros,

[[psalms-127-3]]
^3^ La herencia de Yahveh son los hijos,

[[psalms-127-4]]
^4^ como flechas en la mano del héroe,

[[psalms-127-5]]
^5^ Dichoso el hombre que ha llenado
[[psalms-128]]
== Capítulo 128

[[psalms-128-1]]
^1^ Canción de las subidas.

[[psalms-128-2]]
^2^ Del trabajo de tus manos comerás,

[[psalms-128-3]]
^3^ Tu esposa será como parra fecunda

[[psalms-128-4]]
^4^ Así será bendito el hombre

[[psalms-128-5]]
^5^ ¡Bendígate Yahveh desde Sión,

[[psalms-128-6]]
^6^ y veas a los hijos de tus hijos!
[[psalms-129]]
== Capítulo 129

[[psalms-129-1]]
^1^ Canción de las subidas.

[[psalms-129-2]]
^2^ mucho me han asediado desde mi juventud,

[[psalms-129-3]]
^3^ Sobre mi espalda araron aradores,

[[psalms-129-4]]
^4^ Yahveh, el justo ha roto

[[psalms-129-5]]
^5^ ¡Sean avergonzados, retrocedan

[[psalms-129-6]]
^6^ sean como la hierba de los techos

[[psalms-129-7]]
^7^ De ella no llena el segador su mano

[[psalms-129-8]]
^8^ y no dicen tampoco los que pasan:
[[psalms-130]]
== Capítulo 130

[[psalms-130-1]]
^1^ Canción de las subidas.

[[psalms-130-2]]
^2^ ¡Señor, escucha mi clamor!

[[psalms-130-3]]
^3^ Si en cuenta tomas las culpas, oh Yahveh,

[[psalms-130-4]]
^4^ Mas el perdón se halla junto a ti,

[[psalms-130-5]]
^5^ Yo espero en Yahveh, mi alma

[[psalms-130-6]]
^6^ mi alma aguarda al Señor

[[psalms-130-7]]
^7^ aguarde Israel a Yahveh.

[[psalms-130-8]]
^8^ él rescatará a Israel
[[psalms-131]]
== Capítulo 131

[[psalms-131-1]]
^1^ Canción de las subidas. De David.

[[psalms-131-2]]
^2^ No, mantengo mi alma en paz y silencio

[[psalms-131-3]]
^3^ ¡Espera, Israel, en Yahveh
[[psalms-132]]
== Capítulo 132

[[psalms-132-1]]
^1^ Canción de las subidas.

[[psalms-132-2]]
^2^ del juramento que hizo a Yahveh,

[[psalms-132-3]]
^3^ «No he de entrar bajo el techo de mi casa,

[[psalms-132-4]]
^4^ sueño a mis ojos no he de conceder

[[psalms-132-5]]
^5^ mientras no encuentre un lugar para Yahveh,

[[psalms-132-6]]
^6^ Mirad: hemos oído de Ella que está en Efratá,

[[psalms-132-7]]
^7^ ¡Vayamos a la Morada de él,

[[psalms-132-8]]
^8^ ¡Levántate, Yahveh, hacia tu reposo,

[[psalms-132-9]]
^9^ Tus sacerdotes se vistan de justicia,

[[psalms-132-10]]
^10^ En gracia a David, tu servidor,

[[psalms-132-11]]
^11^ Juró Yahveh a David,

[[psalms-132-12]]
^12^ «Si tus hijos guardan mi alianza,

[[psalms-132-13]]
^13^ Porque Yahveh ha escogido a Sión,

[[psalms-132-14]]
^14^ «Aquí está mi reposo para siempre,

[[psalms-132-15]]
^15^ «Sus provisiones bendeciré sin tasa,

[[psalms-132-16]]
^16^ de salvación vestiré a sus sacerdotes,

[[psalms-132-17]]
^17^ «Allí suscitaré a David un fuerte vástago,

[[psalms-132-18]]
^18^ de vergüenza cubriré a sus enemigos,
[[psalms-133]]
== Capítulo 133

[[psalms-133-1]]
^1^ Canción de las subidas. De David.

[[psalms-133-2]]
^2^ Como un ungüento fino en la cabeza,

[[psalms-133-3]]
^3^ Como el rocío del Hermón que baja
[[psalms-134]]
== Capítulo 134

[[psalms-134-1]]
^1^ Cancion de las subidas.

[[psalms-134-2]]
^2^ ¡Por las noches alzad las manos hacia el santuario,

[[psalms-134-3]]
^3^ ¡Bendígate Yahveh desde Sión,
[[psalms-135]]
== Capítulo 135

[[psalms-135-1]]
^1^ ¡Aleluya!

[[psalms-135-2]]
^2^ que servís en la Casa de Yahveh,

[[psalms-135-3]]
^3^ Alabad a Yahveh, porque es bueno Yahveh,

[[psalms-135-4]]
^4^ Pues Yahveh se ha elegido a Jacob,

[[psalms-135-5]]
^5^ Bien sé yo que es grande Yahveh,

[[psalms-135-6]]
^6^ Todo cuanto agrada a Yahveh,

[[psalms-135-7]]
^7^ Levantando las nubes desde el extremo de la tierra,

[[psalms-135-8]]
^8^ El hirió a los primogénitos de Egipto,

[[psalms-135-9]]
^9^ mandó señales y prodigios

[[psalms-135-10]]
^10^ Hirió a naciones en gran número,

[[psalms-135-11]]
^11^ a Sijón, rey de los amorreos,

[[psalms-135-12]]
^12^ y dio sus tierras en herencia,

[[psalms-135-13]]
^13^ ¡Yahveh, tu nombre para siempre,

[[psalms-135-14]]
^14^ Porque Yahveh a su pueblo hace justicia,

[[psalms-135-15]]
^15^ Los ídolos de las naciones, plata y oro,

[[psalms-135-16]]
^16^ tienen boca y no hablan,

[[psalms-135-17]]
^17^ tienen oídos y no oyen,

[[psalms-135-18]]
^18^ Como ellos serán los que los hacen,

[[psalms-135-19]]
^19^ Caza de Israel, bendecid a Yahveh,

[[psalms-135-20]]
^20^ casa de Leví, bendecid a Yahveh,

[[psalms-135-21]]
^21^ ¡Bendito sea Yahveh desde Sión,
[[psalms-136]]
== Capítulo 136

[[psalms-136-0]]
^0^ ¡Aleluya!

[[psalms-136-1]]
^1^ ¡Dad gracias a Yahveh, porque es bueno,

[[psalms-136-2]]
^2^ Dad gracias al Dios de los dioses,

[[psalms-136-3]]
^3^ dad gracias al Señor de los señores,

[[psalms-136-4]]
^4^ El solo hizo maravillas,

[[psalms-136-5]]
^5^ Hizo los cielos con inteligencia,

[[psalms-136-6]]
^6^ sobre las aguas asentó la tierra,

[[psalms-136-7]]
^7^ Hizo las grandes lumbreras,

[[psalms-136-8]]
^8^ el sol para regir el día,

[[psalms-136-9]]
^9^ la luna y las estrellas para regir la noche,

[[psalms-136-10]]
^10^ Hirió en sus primogénitos a Egipto,

[[psalms-136-11]]
^11^ y sacó a Israel de entre ellos,

[[psalms-136-12]]
^12^ con mano fuerte y tenso brazo,

[[psalms-136-13]]
^13^ El mar de Suf partió en dos,

[[psalms-136-14]]
^14^ por medio a Israel hizo pasar,

[[psalms-136-15]]
^15^ y hundió en él a Faraón con sus huestes,

[[psalms-136-16]]
^16^ Guió a su pueblo en el desierto,

[[psalms-136-17]]
^17^ hirió a grandes reyes,

[[psalms-136-18]]
^18^ y dio muerte a reyes poderosos,

[[psalms-136-19]]
^19^ a Sijón, rey de los amorreos,

[[psalms-136-20]]
^20^ y a Og, rey de Basán,

[[psalms-136-21]]
^21^ Y dio sus tierras en herencia,

[[psalms-136-22]]
^22^ en herencia a su siervo Israel,

[[psalms-136-23]]
^23^ En nuestra humillación se acordó de nosotros,

[[psalms-136-24]]
^24^ y nos libró de nuestros adversarios,

[[psalms-136-25]]
^25^ El da el pan a toda carne,

[[psalms-136-26]]
^26^ ¡Dad gracias al Dios de los cielos,
[[psalms-137]]
== Capítulo 137

[[psalms-137-1]]
^1^ A orillas de los ríos de Babilonia

[[psalms-137-2]]
^2^ en los álamos de la orilla

[[psalms-137-3]]
^3^ Allí nos pidieron

[[psalms-137-4]]
^4^ ¿Cómo podríamos cantar

[[psalms-137-5]]
^5^ ¡Jerusalén, si yo de ti me olvido,

[[psalms-137-6]]
^6^ ¡Mi lengua se me pegue al paladar

[[psalms-137-7]]
^7^ Acuérdate, Yahveh,

[[psalms-137-8]]
^8^ ¡Hija de Babel, devastadora,

[[psalms-137-9]]
^9^ feliz quien agarre y estrelle
[[psalms-138]]
== Capítulo 138

[[psalms-138-1]]
^1^ De David.

[[psalms-138-2]]
^2^ hacia tu santo Templo me prosterno.

[[psalms-138-3]]
^3^ El día en que grité, tú me escuchaste,

[[psalms-138-4]]
^4^ Te dan gracias, Yahveh, todos los reyes de la tierra,

[[psalms-138-5]]
^5^ y cantan los caminos de Yahveh:

[[psalms-138-6]]
^6^ ¡Excelso es Yahveh, y ve al humilde,

[[psalms-138-7]]
^7^ Si ando en medio de angustias, tú me das la vida,

[[psalms-138-8]]
^8^ Yahveh lo acabará todo por mí.
[[psalms-139]]
== Capítulo 139

[[psalms-139-1]]
^1^ Del maestro de coro. De David. Salmo.

[[psalms-139-2]]
^2^ sabes cuándo me siento y cuándo me levanto,

[[psalms-139-3]]
^3^ esté yo en camino o acostado, tú lo adviertes,

[[psalms-139-4]]
^4^ Que no está aún en mi lengua la palabra,

[[psalms-139-5]]
^5^ me aprietas por detrás y por delante,

[[psalms-139-6]]
^6^ Ciencia es misteriosa para mí,

[[psalms-139-7]]
^7^ ¿A dónde iré yo lejos de tu espíritu,

[[psalms-139-8]]
^8^ Si hasta los cielos subo, allí estás tú,

[[psalms-139-9]]
^9^ Si tomo las alas de la aurora,

[[psalms-139-10]]
^10^ también allí tu mano me conduce,

[[psalms-139-11]]
^11^ Aunque diga: «¡Me cubra al menos la tiniebla,

[[psalms-139-12]]
^12^ ni la misma tiniebla es tenebrosa para ti,

[[psalms-139-13]]
^13^ Porque tú mis riñones has formado,

[[psalms-139-14]]
^14^ yo te doy gracias por tantas maravillas:

[[psalms-139-15]]
^15^ y mis huesos no se te ocultaban,

[[psalms-139-16]]
^16^ Mi embrión tus ojos lo veían;

[[psalms-139-17]]
^17^ Mas para mí ¡qué arduos son tus pensamientos,

[[psalms-139-18]]
^18^ ¡Son más, si los recuento, que la arena,

[[psalms-139-19]]
^19^ ¡Ah, si al impío, oh Dios, mataras,

[[psalms-139-20]]
^20^ Ellos que hablan de ti dolosamente,

[[psalms-139-21]]
^21^ ¿No odio, Yahveh, a quienes te odian?

[[psalms-139-22]]
^22^ Con odio colmado los odio,

[[psalms-139-23]]
^23^ Sóndame, oh Dios, mi corazón conoce,

[[psalms-139-24]]
^24^ mira no haya en mí camino de dolor,
[[psalms-140]]
== Capítulo 140

[[psalms-140-1]]
^1^ Del maestro de coro. Salmo. De David.

[[psalms-140-2]]
^2^ Líbrame, Yahveh, del hombre malo,

[[psalms-140-3]]
^3^ los que en su corazón maquinan males,

[[psalms-140-4]]
^4^ aguzan su lengua igual que una serpiente,

[[psalms-140-5]]
^5^ Presérvame, Yahveh, de las manos del impío,

[[psalms-140-6]]
^6^ los insolentes que me han ocultado cepo y lazos,

[[psalms-140-7]]
^7^ Yo he dicho a Yahveh: Tú eres mi Dios,

[[psalms-140-8]]
^8^ Oh Yahveh, Señor mío, fuerza de mi salvación,

[[psalms-140-9]]
^9^ No otorgues, Yahveh, al impío su deseo,

[[psalms-140-10]]
^10^ su cabeza, Pausa

[[psalms-140-11]]
^11^ llueva sobre ellos carbones encendidos,

[[psalms-140-12]]
^12^ no arraigue más en la tierra el deslenguado.

[[psalms-140-13]]
^13^ Sé que Yahveh al humilde hará justicia,

[[psalms-140-14]]
^14^ Sí, los justos darán gracias a tu nombre,
[[psalms-141]]
== Capítulo 141

[[psalms-141-1]]
^1^ Salmo. De David.

[[psalms-141-2]]
^2^ Valga ante ti mi oración como incienso,

[[psalms-141-3]]
^3^ Pon, Yahveh, en mi boca un centinela,

[[psalms-141-4]]
^4^ No dejes que tienda mi corazón a cosa mala,

[[psalms-141-5]]
^5^ Que el justo me hiera por amor, y me corrija,

[[psalms-141-6]]
^6^ Han quedado a merced de la Roca, su juez,

[[psalms-141-7]]
^7^ «Como piedra de molino estrellada por tierra

[[psalms-141-8]]
^8^ Hacia ti, Señor Yahveh, miran mis ojos,

[[psalms-141-9]]
^9^ Guárdame del lazo que me tienden,

[[psalms-141-10]]
^10^ Caigan los impíos, cada uno en su red,
[[psalms-142]]
== Capítulo 142

[[psalms-142-1]]
^1^ Poema. De David. Cuando estaba en la cueva. Oración.

[[psalms-142-2]]
^2^ A Yahveh en mi clamor imploro.

[[psalms-142-3]]
^3^ Ante él derramo mi lamento,

[[psalms-142-4]]
^4^ cuando el aliento en mí se apaga;

[[psalms-142-5]]
^5^ A la derecha mira, y ve,

[[psalms-142-6]]
^6^ Hacia ti clamo, Yahveh;

[[psalms-142-7]]
^7^ Atiende a mi clamor,

[[psalms-142-8]]
^8^ ¡Saca mi alma de la cárcel,
[[psalms-143]]
== Capítulo 143

[[psalms-143-1]]
^1^ Salmo. De David.

[[psalms-143-2]]
^2^ no entres en juicio con tu siervo,

[[psalms-143-3]]
^3^ Persigue mi alma el enemigo,

[[psalms-143-4]]
^4^ se apaga en mí el aliento,

[[psalms-143-5]]
^5^ Me acuerdo de los días de antaño,

[[psalms-143-6]]
^6^ hacia ti mis manos tiendo,

[[psalms-143-7]]
^7^ ¡Oh, pronto, respóndeme, Yahveh,

[[psalms-143-8]]
^8^ Haz que sienta tu amor a la mañana,

[[psalms-143-9]]
^9^ Líbrame de mis enemigos, Yahveh

[[psalms-143-10]]
^10^ enséñame a cumplir tu voluntad,

[[psalms-143-11]]
^11^ Por tu nombre, Yahveh, dame la vida,

[[psalms-143-12]]
^12^ por tu amor aniquila a mis enemigos,
[[psalms-144]]
== Capítulo 144

[[psalms-144-1]]
^1^ De David.

[[psalms-144-2]]
^2^ él, mi amor y mi baluarte,

[[psalms-144-3]]
^3^ Yahveh, ¿qué es el hombre para que le conozcas,

[[psalms-144-4]]
^4^ El hombre es semejante a un soplo,

[[psalms-144-5]]
^5^ ¡Yahveh, inclina tus cielos y desciende,

[[psalms-144-6]]
^6^ fulmina el rayo y desconciértalos,

[[psalms-144-7]]
^7^ Extiende tu mano desde lo alto,

[[psalms-144-8]]
^8^ cuya boca profiere falsedad

[[psalms-144-9]]
^9^ Oh Dios, quiero cantarte un canto nuevo,

[[psalms-144-10]]
^10^ tú que das a los reyes la victoria,

[[psalms-144-11]]
^11^ sálvame.

[[psalms-144-12]]
^12^ Sean nuestros hijos como plantas

[[psalms-144-13]]
^13^ nuestros graneros llenos, rebosantes

[[psalms-144-14]]
^14^ nuestras bestias bien cargadas;

[[psalms-144-15]]
^15^ ¡Feliz el pueblo a quien así sucede
[[psalms-145]]
== Capítulo 145

[[psalms-145-1]]
^1^ Himno. De David.

[[psalms-145-2]]
^2^ Bet. todos los días te bendeciré,

[[psalms-145-3]]
^3^ Guímel. grande es Yahveh y muy digno de alabanza,

[[psalms-145-4]]
^4^ Dálet. Una edad a otra encomiará tus obras,

[[psalms-145-5]]
^5^ He. El esplendor, la gloria de tu majestad,

[[psalms-145-6]]
^6^ Vau. Del poder de tus portentos se hablará,

[[psalms-145-7]]
^7^ Zain. se hará memoria de tu inmensa bondad,

[[psalms-145-8]]
^8^ Jet. Clemente y compasivo es Yahveh,

[[psalms-145-9]]
^9^ Tet bueno es Yahveh para con todos,

[[psalms-145-10]]
^10^ Yod. Te darán gracias, Yahveh, todas tus obras

[[psalms-145-11]]
^11^ Kaf. dirán la gloria de tu reino,

[[psalms-145-12]]
^12^ Lámed. para mostrar a los hijos de Adán tus proezas,

[[psalms-145-13]]
^13^ Mem. Tu reino, un reino por los siglos todos,

[[psalms-145-14]]
^14^ Sámek. Yahveh sostiene a todos los que caen,

[[psalms-145-15]]
^15^ Ain. Los ojos de todos fijos en ti, esperan

[[psalms-145-16]]
^16^ Pe. abres la mano tú

[[psalms-145-17]]
^17^ Sade. Yahveh es justo en todos sus caminos,

[[psalms-145-18]]
^18^ Qof. cerca está Yahveh de los que le invocan,

[[psalms-145-19]]
^19^ Res. El cumple el deseo de los que le temen,

[[psalms-145-20]]
^20^ Sin. guarda Yahveh a cuantos le aman,

[[psalms-145-21]]
^21^ Tau. ¡La alabanza de Yahveh diga mi boca,
[[psalms-146]]
== Capítulo 146

[[psalms-146-1]]
^1^ ¡Aleluya!

[[psalms-146-2]]
^2^ A Yahveh, mientras viva, he de alabar,

[[psalms-146-3]]
^3^ No pongáis vuestra confianza en príncipes,

[[psalms-146-4]]
^4^ su soplo exhala, a su barro retorna,

[[psalms-146-5]]
^5^ Feliz aquel que en el Dios de Jacob tiene su apoyo,

[[psalms-146-6]]
^6^ que hizo los cielos y la tierra,

[[psalms-146-7]]
^7^ hace justicia a los oprimidos,

[[psalms-146-8]]
^8^ Yahveh abre los ojos a los ciegos,

[[psalms-146-9]]
^9^ Yahveh protege al forastero,

[[psalms-146-10]]
^10^ Yahveh reina para siempre,
[[psalms-147]]
== Capítulo 147

[[psalms-147-0]]
^0^ ¡Aleluya!

[[psalms-147-1]]
^1^ Alabad a Yahveh, que es bueno salmodiar,

[[psalms-147-2]]
^2^ Edifica Yahveh a Jerusalén,

[[psalms-147-3]]
^3^ él sana a los de roto corazón,

[[psalms-147-4]]
^4^ El cuenta el número de estrellas,

[[psalms-147-5]]
^5^ grande es nuestro Señor, y de gran fuerza,

[[psalms-147-6]]
^6^ Yahveh sostiene a los humildes,

[[psalms-147-7]]
^7^ Cantad a Yahveh en acción de gracias,

[[psalms-147-8]]
^8^ El que cubre de nubes los cielos,

[[psalms-147-9]]
^9^ el que dispensa al ganado su sustento,

[[psalms-147-10]]
^10^ No le agrada el brío del caballo,

[[psalms-147-11]]
^11^ Se complace Yahveh en los que le temen,

[[psalms-147-12]]
^12^ ¡Celebra a Yahveh, Jerusalén,

[[psalms-147-13]]
^13^ Que él ha reforzado los cerrojos de tus puertas,

[[psalms-147-14]]
^14^ pone paz en tu término,

[[psalms-147-15]]
^15^ El envía a la tierra su mensaje,

[[psalms-147-16]]
^16^ como lana distribuye la nieve,

[[psalms-147-17]]
^17^ Arroja su hielo como migas de pan,

[[psalms-147-18]]
^18^ Envía su palabra y hace derretirse,

[[psalms-147-19]]
^19^ El revela a Jacob su palabra,

[[psalms-147-20]]
^20^ no hizo tal con ninguna nación,
[[psalms-148]]
== Capítulo 148

[[psalms-148-1]]
^1^ ¡Aleluya!

[[psalms-148-2]]
^2^ alabadle, ángeles suyos todos, todas sus huestes, alabadle!

[[psalms-148-3]]
^3^ ¡Alabadle, sol y luna,

[[psalms-148-4]]
^4^ alabadle, cielos de los cielos,

[[psalms-148-5]]
^5^ Alaben ellos el nombre de Yahveh:

[[psalms-148-6]]
^6^ él los fijó por siempre, por los siglos,

[[psalms-148-7]]
^7^ ¡Alabad a Yahveh desde la tierra,

[[psalms-148-8]]
^8^ fuego y granizo, nieve y bruma,

[[psalms-148-9]]
^9^ montañas y todas la colinas,

[[psalms-148-10]]
^10^ fieras y todos los ganados,

[[psalms-148-11]]
^11^ reyes de la tierra y pueblos todos,

[[psalms-148-12]]
^12^ jóvenes y doncellas también,

[[psalms-148-13]]
^13^ Alaben el nombre de Yahveh:

[[psalms-148-14]]
^14^ El realza la frente de su pueblo,
[[psalms-149]]
== Capítulo 149

[[psalms-149-1]]
^1^ ¡Aleluya!

[[psalms-149-2]]
^2^ ¡Regocíjese Israel en su hacedor,

[[psalms-149-3]]
^3^ alaben su nombre con la danza,

[[psalms-149-4]]
^4^ Porque Yahveh en su pueblo se complace,

[[psalms-149-5]]
^5^ Exalten de gloria sus amigos,

[[psalms-149-6]]
^6^ los elogios de Dios en su garganta,

[[psalms-149-7]]
^7^ para ejecutar venganza en las naciones,

[[psalms-149-8]]
^8^ para atar con cadenas a sus reyes,

[[psalms-149-9]]
^9^ para aplicarles la sentencia escrita:
[[psalms-150]]
== Capítulo 150

[[psalms-150-1]]
^1^ ¡Aleluya!

[[psalms-150-2]]
^2^ alabadle por sus grandes hazañas,

[[psalms-150-3]]
^3^ Alabadle con clangor de cuerno,

[[psalms-150-4]]
^4^ alabadle con tamboril y danza,

[[psalms-150-5]]
^5^ alabadle con címbalos sonoros,

[[psalms-150-6]]
^6^ ¡Todo cuanto respira alabe a Yahveh!
