[[proverbs]]
= Proverbios

[[proverbs-1]]
== Capítulo 1

[[proverbs-1-1]]
^1^ Proverbios de Salomón, hijo de David, rey de Israel:

[[proverbs-1-2]]
^2^ para aprender sabiduría e instrucción,

[[proverbs-1-3]]
^3^ para alcanzar intrucción y perspicacia,

[[proverbs-1-4]]
^4^ para enseñar a los simples la prudencia,

[[proverbs-1-5]]
^5^ Que atienda el sabio y crecerá en doctrina,

[[proverbs-1-6]]
^6^ para descifrar proverbios y enigmas,

[[proverbs-1-7]]
^7^ El temor de Yahveh es el principio de la ciencia;

[[proverbs-1-8]]
^8^ Escucha, hijo mío, la instrucción de tu padre

[[proverbs-1-9]]
^9^ corona graciosa son para tu cabeza

[[proverbs-1-10]]
^10^ Hijo mío, si los pecadores te quieren seducir,

[[proverbs-1-11]]
^11^ Si te dicen: «¡Vente con nosotros,

[[proverbs-1-12]]
^12^ devorémoslos vivos como el seol,

[[proverbs-1-13]]
^13^ ¡hallaremos toda clase de riquezas,

[[proverbs-1-14]]
^14^ te tocará tu parte igual que a nosotros,

[[proverbs-1-15]]
^15^ no te pongas, hijo mío, en camino con ellos,

[[proverbs-1-16]]
^16^ porque sus pies corren hacia el mal

[[proverbs-1-17]]
^17^ pues es inútil tender la red

[[proverbs-1-18]]
^18^ Contra su propia sangre están acechando,

[[proverbs-1-19]]
^19^ Esa es la senda de todo el que se entrega a la rapiña:

[[proverbs-1-20]]
^20^ La Sabiduría clama por las calles,

[[proverbs-1-21]]
^21^ llama en la esquina de las calles concurridas,

[[proverbs-1-22]]
^22^ «¿Hasta cuándo, simples, amaréis vuestra simpleza

[[proverbs-1-23]]
^23^ Convertíos por mis reprensiones:

[[proverbs-1-24]]
^24^ Ya que os he llamado y no habéis querido,

[[proverbs-1-25]]
^25^ habéis despreciado todos mis consejos,

[[proverbs-1-26]]
^26^ también yo me reiré de vuestra desgracia,

[[proverbs-1-27]]
^27^ cuando llegue, como huracán, vuestro espanto,

[[proverbs-1-28]]
^28^ Entonces me llamarán y no responderé,

[[proverbs-1-29]]
^29^ Porque tuvieron odio a la ciencia

[[proverbs-1-30]]
^30^ no hicieron caso de mi consejo,

[[proverbs-1-31]]
^31^ comerán del fruto de su conducta,

[[proverbs-1-32]]
^32^ Su propio descarrío matará a los simples,

[[proverbs-1-33]]
^33^ Pero el que me escucha vivirá seguro,
[[proverbs-2]]
== Capítulo 2

[[proverbs-2-1]]
^1^ Hijo mío, si das acogida a mis palabras,

[[proverbs-2-2]]
^2^ prestando tu oído a la sabiduría,

[[proverbs-2-3]]
^3^ si invocas a la inteligencia

[[proverbs-2-4]]
^4^ si la buscas como la plata

[[proverbs-2-5]]
^5^ entonces entenderás el temor de Yahveh

[[proverbs-2-6]]
^6^ Porque Yahveh es el que da la sabiduría,

[[proverbs-2-7]]
^7^ Reserva el éxito para los rectos,

[[proverbs-2-8]]
^8^ vigila las sendas de la equidad

[[proverbs-2-9]]
^9^ Entonces entenderás la justicia, la equidad y la rectitud:

[[proverbs-2-10]]
^10^ Cuando entre la sabiduría en tu corazón

[[proverbs-2-11]]
^11^ velará sobre ti la reflexión

[[proverbs-2-12]]
^12^ apartándote del mal camino,

[[proverbs-2-13]]
^13^ de los que abandonan el recto sendero

[[proverbs-2-14]]
^14^ de los que se gozan en hacer el mal,

[[proverbs-2-15]]
^15^ cuyos senderos son tortuosos

[[proverbs-2-16]]
^16^ Ella te apartará de la mujer ajena,

[[proverbs-2-17]]
^17^ que ha dejado al amigo de su juventud

[[proverbs-2-18]]
^18^ su casa está inclinada hacia la muerte,

[[proverbs-2-19]]
^19^ Nadie que entre por ella volverá,

[[proverbs-2-20]]
^20^ Por eso has de ir por el camino de los buenos,

[[proverbs-2-21]]
^21^ Porque los rectos habitarán la tierra

[[proverbs-2-22]]
^22^ pero los malos serán cercenados de la tierra,
[[proverbs-3]]
== Capítulo 3

[[proverbs-3-1]]
^1^ Hijo mío, no olvides mi lección,

[[proverbs-3-2]]
^2^ pues largos días y años de vida

[[proverbs-3-3]]
^3^ La piedad y la lealtad no te abandonen;

[[proverbs-3-4]]
^4^ Así hallarás favor y buena acogida

[[proverbs-3-5]]
^5^ Confía en Yahveh de todo corazón

[[proverbs-3-6]]
^6^ reconócele en todos tus caminos

[[proverbs-3-7]]
^7^ No seas sabio a tus propios ojos,

[[proverbs-3-8]]
^8^ medicina será para tu carne

[[proverbs-3-9]]
^9^ Honra a Yahveh con tus riquezas,

[[proverbs-3-10]]
^10^ tus trojes se llenarán de grano

[[proverbs-3-11]]
^11^ No desdeñes, hijo mío, la instrucción de Yahveh,

[[proverbs-3-12]]
^12^ porque Yahveh reprende a aquel que ama,

[[proverbs-3-13]]
^13^ Dichoso el hombre que ha encontrado la sabiduría

[[proverbs-3-14]]
^14^ más vale su ganancia que la ganancia de plata,

[[proverbs-3-15]]
^15^ Más preciosa es que las perlas,

[[proverbs-3-16]]
^16^ Largos días a su derecha,

[[proverbs-3-17]]
^17^ Sus caminos son caminos de dulzura

[[proverbs-3-18]]
^18^ Es árbol de vida para los que a ella están asidos,

[[proverbs-3-19]]
^19^ Con la Sabiduria fundó Yahveh la tierra,

[[proverbs-3-20]]
^20^ con su ciencia se abrieron los océanos

[[proverbs-3-21]]
^21^ Hijo mío, guarda la prudencia y la reflexión,

[[proverbs-3-22]]
^22^ serán vida para tu alma

[[proverbs-3-23]]
^23^ Así irás tranquilo por tu camino

[[proverbs-3-24]]
^24^ No tendrás miedo al acostarte,

[[proverbs-3-25]]
^25^ No temerás el espanto repentino,

[[proverbs-3-26]]
^26^ porque Yahveh será tu tranquilidad

[[proverbs-3-27]]
^27^ No niegues un favor a quien es debido,

[[proverbs-3-28]]
^28^ No digas a tu prójimo: «Vete y vuelve,

[[proverbs-3-29]]
^29^ No trames mal contra tu prójimo

[[proverbs-3-30]]
^30^ No te querelles contra nadie sin motivo,

[[proverbs-3-31]]
^31^ No envidies al hombre violento,

[[proverbs-3-32]]
^32^ porque Yahveh abomina a los perversos,

[[proverbs-3-33]]
^33^ La maldición de Yahveh en la casa del malvado,

[[proverbs-3-34]]
^34^ Con los arrogantes es también arrogante,

[[proverbs-3-35]]
^35^ La gloria es patrimonio de los sabios
[[proverbs-4]]
== Capítulo 4

[[proverbs-4-1]]
^1^ Escuchad, hijos, la instrucción del padre,

[[proverbs-4-2]]
^2^ porque es buena la doctrina que os enseño;

[[proverbs-4-3]]
^3^ También yo fui hijo para mi padre,

[[proverbs-4-4]]
^4^ El me enseñaba y me decía:

[[proverbs-4-5]]
^5^ Adquiere la sabiduría, adquiere la inteligencia,

[[proverbs-4-6]]
^6^ No la abandones y ella te guardará,

[[proverbs-4-7]]
^7^ El comienzo de la sabiduría es: adquiere la sabiduría,

[[proverbs-4-8]]
^8^ Haz acopio de ella, y ella te ensalzará;

[[proverbs-4-9]]
^9^ pondrá en tu cabeza una diadema de gracia,

[[proverbs-4-10]]
^10^ Escucha, hijo mío, recibe mis palabras,

[[proverbs-4-11]]
^11^ En el camino de la sabiduría te he instruido,

[[proverbs-4-12]]
^12^ Al andar no se enredarán tus pasos,

[[proverbs-4-13]]
^13^ Aférrate a la instrucción, no la sueltes;

[[proverbs-4-14]]
^14^ No te metas por la senda de los perversos,

[[proverbs-4-15]]
^15^ Evítalo, no pases por él,

[[proverbs-4-16]]
^16^ Porque ésos no duermen si no obran el mal,

[[proverbs-4-17]]
^17^ Es que su pan es pan de maldad,

[[proverbs-4-18]]
^18^ La senda de los justos es como la luz del alba,

[[proverbs-4-19]]
^19^ Pero el camino de los malos es como tinieblas,

[[proverbs-4-20]]
^20^ Atiende, hijo mío, a mis palabras,

[[proverbs-4-21]]
^21^ No las apartes de tus ojos,

[[proverbs-4-22]]
^22^ Porque son vida para los que las encuentran,

[[proverbs-4-23]]
^23^ Por encima de todo cuidado, guarda tu corazón,

[[proverbs-4-24]]
^24^ Aparta de ti la falsía de la boca

[[proverbs-4-25]]
^25^ Miren de frente tus ojos,

[[proverbs-4-26]]
^26^ Tantea bien el sendero de tus pies

[[proverbs-4-27]]
^27^ No te tuerzas ni a derecha ni a izquierda,
[[proverbs-5]]
== Capítulo 5

[[proverbs-5-1]]
^1^ Presta, hijo mío, atención a mi sabiduría,

[[proverbs-5-2]]
^2^ para que guardes tú la reflexión

[[proverbs-5-3]]
^3^ pues miel destilan los labios de la extraña,

[[proverbs-5-4]]
^4^ pero al fin es amarga como el ajenjo,

[[proverbs-5-5]]
^5^ Sus pies descienden a la muerte,

[[proverbs-5-6]]
^6^ Por no seguir la senda de la vida,

[[proverbs-5-7]]
^7^ Así pues, hijo mío, escúchame,

[[proverbs-5-8]]
^8^ aleja de ella tu camino,

[[proverbs-5-9]]
^9^ no sea que ella dé tu honor a otro

[[proverbs-5-10]]
^10^ no se harten de tus bienes los extraños,

[[proverbs-5-11]]
^11^ no sea que gimas a la postre

[[proverbs-5-12]]
^12^ y digas: «Ay de mí, que he odiado la instrucción,

[[proverbs-5-13]]
^13^ no he escuchado la voz de mis maestros

[[proverbs-5-14]]
^14^ A punto he estado de cualquier desgracia,

[[proverbs-5-15]]
^15^ Bebe el agua de tu cisterna,

[[proverbs-5-16]]
^16^ ¿Se van a desbordar por fuera tus arroyos,

[[proverbs-5-17]]
^17^ Que sean para ti solo,

[[proverbs-5-18]]
^18^ - Sea tu fuente bendita.

[[proverbs-5-19]]
^19^ cierva amable, graciosa gacela:

[[proverbs-5-20]]
^20^ ¿Por qué apasionarte, hijo mío, de una ajena,

[[proverbs-5-21]]
^21^ Pues los caminos del hombre están en la presencia de Yahveh,

[[proverbs-5-22]]
^22^ El malvado será presa de sus propias maldades,

[[proverbs-5-23]]
^23^ Morirá por su falta de instrucción,
[[proverbs-6]]
== Capítulo 6

[[proverbs-6-1]]
^1^ Si has salido, hijo mío, fiador de tu prójimo,

[[proverbs-6-2]]
^2^ si te has obligado con las palabras de tu boca,

[[proverbs-6-3]]
^3^ haz esto, hijo mío, para quedar libre,

[[proverbs-6-4]]
^4^ no concedas a tus ojos sueño

[[proverbs-6-5]]
^5^ líbrate, como la gacela del lazo,

[[proverbs-6-6]]
^6^ Vete donde la hormiga, perezoso,

[[proverbs-6-7]]
^7^ Ella no tiene jefe,

[[proverbs-6-8]]
^8^ asegura en el verano su sustento,

[[proverbs-6-9]]
^9^ ¿Hasta cuándo, perezoso, estarás acostado?

[[proverbs-6-10]]
^10^ Un poco dormir, otro poco dormitar,

[[proverbs-6-11]]
^11^ y llegará como vagabundo tu miseria

[[proverbs-6-12]]
^12^ Un malvado, un hombre inicuo,

[[proverbs-6-13]]
^13^ guiña el ojo, arrastra los pies,

[[proverbs-6-14]]
^14^ Torcido está su corazón, medita el mal,

[[proverbs-6-15]]
^15^ Por eso vendrá su ruina de repente,

[[proverbs-6-16]]
^16^ Seis cosas hay que aborrece Yahveh,

[[proverbs-6-17]]
^17^ ojos altaneros, lengua mentirosa,

[[proverbs-6-18]]
^18^ corazón que fragua planes perversos,

[[proverbs-6-19]]
^19^ testigo falso que profiere calumnias,

[[proverbs-6-20]]
^20^ Garda, hijo mío, el mandato de tu padre

[[proverbs-6-21]]
^21^ Tenlos atados siempre a tu corazón,

[[proverbs-6-22]]
^22^ en tus pasos ellos serán tu guía;

[[proverbs-6-23]]
^23^ Porque el mandato es una lámpara

[[proverbs-6-24]]
^24^ para librarte de la mujer perversa,

[[proverbs-6-25]]
^25^ No codicies su hermosura en tu corazón,

[[proverbs-6-26]]
^26^ porque un mendrugo de pan basta a la prostituta,

[[proverbs-6-27]]
^27^ ¿Puede uno meter fuego en su regazo

[[proverbs-6-28]]
^28^ ¿Puede uno andar sobre las brasas

[[proverbs-6-29]]
^29^ Así le pasa al que se llega a la mujer del prójimo:

[[proverbs-6-30]]
^30^ No se desprecia al ladrón cuando roba

[[proverbs-6-31]]
^31^ Mas, si le sorprenden, paga el séptuplo,

[[proverbs-6-32]]
^32^ Pero el que hace adulterar a una mujer es un mentecato;

[[proverbs-6-33]]
^33^ encontrará golpes y deshonra

[[proverbs-6-34]]
^34^ Porque los celos enfurecen al marido.

[[proverbs-6-35]]
^35^ No hará caso de compensación alguna;
[[proverbs-7]]
== Capítulo 7

[[proverbs-7-1]]
^1^ Guarda, hijo mío, mis palabras,

[[proverbs-7-2]]
^2^ Guarda mis mandamientos y vivirás;

[[proverbs-7-3]]
^3^ Atalos a tus dedos,

[[proverbs-7-4]]
^4^ Dile a la sabiduría: «Tú eres mi hermana»,

[[proverbs-7-5]]
^5^ para que te guarde de la mujer ajena,

[[proverbs-7-6]]
^6^ Estaba yo a la ventana de mi casa

[[proverbs-7-7]]
^7^ cuando ví, en el grupo de los simples,

[[proverbs-7-8]]
^8^ pasaba por la calle, junto a la esquina donde ella vivía,

[[proverbs-7-9]]
^9^ al atardecer, ya oscurecido,

[[proverbs-7-10]]
^10^ De repente, le sale al paso una mujer,

[[proverbs-7-11]]
^11^ Es alborotada y revoltosa,

[[proverbs-7-12]]
^12^ Tan pronto en las calles como en las plazas,

[[proverbs-7-13]]
^13^ Ella lo agarró y lo abrazó,

[[proverbs-7-14]]
^14^ «Tenía que ofrecer un sacrificio de comunión

[[proverbs-7-15]]
^15^ por eso he salido a tu encuentro

[[proverbs-7-16]]
^16^ He puesto en mi lecho cobertores

[[proverbs-7-17]]
^17^ con mirra mi cama he rociado,

[[proverbs-7-18]]
^18^ Ven, embriaguémonos de amores hasta la mañana,

[[proverbs-7-19]]
^19^ Porque no está el marido en casa,

[[proverbs-7-20]]
^20^ ha llevado en su mano la bolsa del dinero,

[[proverbs-7-21]]
^21^ Con sus muchas artes lo seduce,

[[proverbs-7-22]]
^22^ Se va tras ella en seguida,

[[proverbs-7-23]]
^23^ hasta que una flecha le atraviese el hígado;

[[proverbs-7-24]]
^24^ Ahora pues, hijo mío, escúchame,

[[proverbs-7-25]]
^25^ no se desvíe tu corazón hacia sus caminos,

[[proverbs-7-26]]
^26^ porque a muchos ha hecho caer muertos,

[[proverbs-7-27]]
^27^ Su morada es camino del seol,
[[proverbs-8]]
== Capítulo 8

[[proverbs-8-1]]
^1^ ¿No está llamando la Sabiduría?

[[proverbs-8-2]]
^2^ En la cumbre de las colinas que hay sobre el camino,

[[proverbs-8-3]]
^3^ junto a las puertas, a la salida de la ciudad,

[[proverbs-8-4]]
^4^ «A vosotros, hombres, os llamo,

[[proverbs-8-5]]
^5^ Entended, simples, la prudencia

[[proverbs-8-6]]
^6^ Escuchad: voy a decir cosas importantes

[[proverbs-8-7]]
^7^ Porque verdad es el susurro de mi boca

[[proverbs-8-8]]
^8^ Justos son todos los dichos de mi boca,

[[proverbs-8-9]]
^9^ Todos están abiertos para el inteligente

[[proverbs-8-10]]
^10^ Recibid mi instrucción y no la plata,

[[proverbs-8-11]]
^11^ Porque mejor es la sabiduría que las piedras preciosas,

[[proverbs-8-12]]
^12^ «Yo, la Sabiduría, habito con la prudencia,

[[proverbs-8-13]]
^13^ (El temor de Yahveh es odiar el mal.)

[[proverbs-8-14]]
^14^ Míos son el consejo y la habilidad,

[[proverbs-8-15]]
^15^ Por mí los reyes reinan

[[proverbs-8-16]]
^16^ Por mí los príncipes gobiernan

[[proverbs-8-17]]
^17^ Yo amo a los que me aman

[[proverbs-8-18]]
^18^ Conmigo están la riqueza y la gloria,

[[proverbs-8-19]]
^19^ Mejor es mi fruto que el oro, que el oro puro,

[[proverbs-8-20]]
^20^ Yo camino por la senda de la justicia,

[[proverbs-8-21]]
^21^ para repartir hacienda a los que me aman

[[proverbs-8-22]]
^22^ «Yahveh me creó, primicia de su camino,

[[proverbs-8-23]]
^23^ Desde la eternidad fui fundada,

[[proverbs-8-24]]
^24^ Cuando no existían los abismos fui engendrada,

[[proverbs-8-25]]
^25^ Antes que los montes fuesen asentados,

[[proverbs-8-26]]
^26^ No había hecho aún la tierra ni los campos,

[[proverbs-8-27]]
^27^ Cuando asentó los cielos, allí estaba yo,

[[proverbs-8-28]]
^28^ cuando arriba condensó las nubes,

[[proverbs-8-29]]
^29^ cuando al mar dio su precepto

[[proverbs-8-30]]
^30^ yo estaba allí, como arquitecto,

[[proverbs-8-31]]
^31^ jugando por el orbe de su tierra;

[[proverbs-8-32]]
^32^ «Ahora pues, hijos, escuchadme,

[[proverbs-8-33]]
^33^ Escuchad la instrucción y haceos sabios,

[[proverbs-8-34]]
^34^ Dichoso el hombre que me escucha

[[proverbs-8-35]]
^35^ Porque el que me halla, ha hallado la vida,

[[proverbs-8-36]]
^36^ Pero el que me ofende, hace daño a su alma;
[[proverbs-9]]
== Capítulo 9

[[proverbs-9-1]]
^1^ La Sabiduría ha edificado una casa,

[[proverbs-9-2]]
^2^ ha hecho su matanza, ha mezclado su vino,

[[proverbs-9-3]]
^3^ Ha mandado a sus criadas y anuncia

[[proverbs-9-4]]
^4^ «Si alguno es simple, véngase acá».

[[proverbs-9-5]]
^5^ «Venid y comed de mi pan,

[[proverbs-9-6]]
^6^ dejaos de simplezas y viviréis,

[[proverbs-9-7]]
^7^ El que corrige al arrogante se acarrea desprecio,

[[proverbs-9-8]]
^8^ No reprendas al arrogante, porque te aborrecerá;

[[proverbs-9-9]]
^9^ Da al sabio, y se hará más sabio todavía;

[[proverbs-9-10]]
^10^ Comienzo de la sabiduría es el temor de Yahveh,

[[proverbs-9-11]]
^11^ Pues por mí se multiplicarán tus días

[[proverbs-9-12]]
^12^ Si te haces sabio, te haces sabio para tu provecho,

[[proverbs-9-13]]
^13^ La mujer necia es alborotada,

[[proverbs-9-14]]
^14^ Se sienta a la puerta de su casa,

[[proverbs-9-15]]
^15^ para llamar a los que pasan por el camino,

[[proverbs-9-16]]
^16^ «Si alguno es simple, véngase acá»

[[proverbs-9-17]]
^17^ «Son dulces las aguas robadas

[[proverbs-9-18]]
^18^ No sabe el hombre que allí moran las Sombras;
[[proverbs-10]]
== Capítulo 10

[[proverbs-10-1]]
^1^ Proverbios de Salomón.

[[proverbs-10-2]]
^2^ Tesoros mal adquiridos no aprovechan,

[[proverbs-10-3]]
^3^ Yahveh no permite que el justo pase hambre,

[[proverbs-10-4]]
^4^ Mano indolente empobrece,

[[proverbs-10-5]]
^5^ Amontonar en verano es de hombre sensato,

[[proverbs-10-6]]
^6^ Bendiciones sobre la cabeza del justo;

[[proverbs-10-7]]
^7^ El recuerdo del justo sirve de bendición;

[[proverbs-10-8]]
^8^ El sensato de corazón acepta los mandatos,

[[proverbs-10-9]]
^9^ Quien va a derecho, va seguro,

[[proverbs-10-10]]
^10^ El que guiña de ojos, dará disgustos,

[[proverbs-10-11]]
^11^ Manantial de vida la boca del justo;

[[proverbs-10-12]]
^12^ El odio provoca discusiones,

[[proverbs-10-13]]
^13^ En labios del inteligente se encuentra sabiduría,

[[proverbs-10-14]]
^14^ Los sabios atesoran conocimiento,

[[proverbs-10-15]]
^15^ La fortuna del rico es su plaza fuerte,

[[proverbs-10-16]]
^16^ El salario del justo es para vivir,

[[proverbs-10-17]]
^17^ Camina hacia la vida el que guarda las instrucciones;

[[proverbs-10-18]]
^18^ Los labios mentirosos disimulan el odio;

[[proverbs-10-19]]
^19^ En las muchas palabras no faltará pecado;

[[proverbs-10-20]]
^20^ Plata elegida es la lengua del justo,

[[proverbs-10-21]]
^21^ Los labios del justo apacientan a muchos,

[[proverbs-10-22]]
^22^ La bendición de Yahveh es la que enriquece,

[[proverbs-10-23]]
^23^ Como un juego es para el necio cometer el crimen,

[[proverbs-10-24]]
^24^ Lo que teme el malo, eso le sucede,

[[proverbs-10-25]]
^25^ Cuando pasa la tormenta, ya no existe el malo,

[[proverbs-10-26]]
^26^ Vinagre para los dientes y humo para los ojos:

[[proverbs-10-27]]
^27^ El temor de Yahveh prolonga los días,

[[proverbs-10-28]]
^28^ La espera de los justos es alegría,

[[proverbs-10-29]]
^29^ Fortaleza es para el íntegro la senda de Yahveh;

[[proverbs-10-30]]
^30^ Jamás el justo será conmovido,

[[proverbs-10-31]]
^31^ La boca del justo da frutos de sabiduría,

[[proverbs-10-32]]
^32^ Los labios del justo saben de benevolencia;
[[proverbs-11]]
== Capítulo 11

[[proverbs-11-1]]
^1^ Abominación de Yahveh la balanza falsa,

[[proverbs-11-2]]
^2^ Detrás de la insolencia viene el insulto;

[[proverbs-11-3]]
^3^ A los rectos su integridad les guía;

[[proverbs-11-4]]
^4^ Nada servirán riquezas el día de la ira,

[[proverbs-11-5]]
^5^ A los íntregros su justicia les allana el camino,

[[proverbs-11-6]]
^6^ A los rectos les salva su justicia,

[[proverbs-11-7]]
^7^ En la muerte del malo se esfuma su esperanza,

[[proverbs-11-8]]
^8^ El justo es librado de la angustia,

[[proverbs-11-9]]
^9^ Con la boca el impío pierde a su vecino,

[[proverbs-11-10]]
^10^ Con el bien de los justos la ciudad se regocija,

[[proverbs-11-11]]
^11^ Con la bendición de los rectos, se levanta la ciudad;

[[proverbs-11-12]]
^12^ Quien desprecia a su vecino es un insensato;

[[proverbs-11-13]]
^13^ El que anda calumniando descubre secretos,

[[proverbs-11-14]]
^14^ Donde no hay buen gobierno, el pueblo se hunde;

[[proverbs-11-15]]
^15^ El mal se busca quien avala al desconocido,

[[proverbs-11-16]]
^16^ Mujer graciosa consigue honor,

[[proverbs-11-17]]
^17^ A sí mismo se beneficia el que es compasivo,

[[proverbs-11-18]]
^18^ El malo consigue un jornal falso;

[[proverbs-11-19]]
^19^ Al que establece justicia, la vida,

[[proverbs-11-20]]
^20^ A los de corazón torcido abomina Yahveh;

[[proverbs-11-21]]
^21^ De cierto que el malo no quedará impune,

[[proverbs-11-22]]
^22^ Anillo de oro en nariz de un puerco,

[[proverbs-11-23]]
^23^ El deseo de los justos es sólo el bien,

[[proverbs-11-24]]
^24^ Hay quien gasta y todavía va a más;

[[proverbs-11-25]]
^25^ El alma generosa será colmada,

[[proverbs-11-26]]
^26^ El pueblo maldice al que acapara trigo;

[[proverbs-11-27]]
^27^ Quien busca el bien, se procura favor,

[[proverbs-11-28]]
^28^ Quien confía en su riqueza, ése caerá,

[[proverbs-11-29]]
^29^ Quien desordena su casa, hereda viento,

[[proverbs-11-30]]
^30^ El fruto del justo es un árbol de vida;

[[proverbs-11-31]]
^31^ Si el justo recibe su recompensa en la tierra,
[[proverbs-12]]
== Capítulo 12

[[proverbs-12-1]]
^1^ El que ama la instrucción ama la ciencia,

[[proverbs-12-2]]
^2^ El bueno obtiene el favor de Yahveh;

[[proverbs-12-3]]
^3^ Nadie se afianza por la maldad,

[[proverbs-12-4]]
^4^ Mujer virtuosa, corona del marido,

[[proverbs-12-5]]
^5^ Las intenciones de los justos son equidad,

[[proverbs-12-6]]
^6^ Las palabras de los malos son trampas sangrientas,

[[proverbs-12-7]]
^7^ Derribados los malos, no existen ya más,

[[proverbs-12-8]]
^8^ Se alaba al hombre según su prudencia,

[[proverbs-12-9]]
^9^ Más vale hombre sencillo que tiene un esclavo,

[[proverbs-12-10]]
^10^ El justo se cuida de su ganado,

[[proverbs-12-11]]
^11^ Quien cultiva su tierra se hartará de pan,

[[proverbs-12-12]]
^12^ El placer del impío está en la maquinación de los malvados,

[[proverbs-12-13]]
^13^ En el delito de los labios hay una trampa fatal,

[[proverbs-12-14]]
^14^ Por el fruto de su boca, se harta de bien el hombre,

[[proverbs-12-15]]
^15^ El necio tiene por recto su camino,

[[proverbs-12-16]]
^16^ El necio, al momento descubre su pena,

[[proverbs-12-17]]
^17^ Quien declara la verdad, descubre la justicia;

[[proverbs-12-18]]
^18^ Quien habla sin tino, hiere como espada;

[[proverbs-12-19]]
^19^ Los labios sinceros permanecen por siempre,

[[proverbs-12-20]]
^20^ Fraude en el corazón de quien trama el mal;

[[proverbs-12-21]]
^21^ Ninguna desgracia le sucede al justo,

[[proverbs-12-22]]
^22^ Los labios mentirosos abomina Yahveh;

[[proverbs-12-23]]
^23^ El hombre cauto oculta su ciencia,

[[proverbs-12-24]]
^24^ La mano diligente obtiene el mando;

[[proverbs-12-25]]
^25^ Ansiedad en el corazón deprime al hombre,

[[proverbs-12-26]]
^26^ El justo enseña el camino a su prójimo,

[[proverbs-12-27]]
^27^ El indolente no pone a asar su caza;

[[proverbs-12-28]]
^28^ En la senda de la justicia está la vida;
[[proverbs-13]]
== Capítulo 13

[[proverbs-13-1]]
^1^ El hijo sabio atiende a la instrucción de su padre,

[[proverbs-13-2]]
^2^ Con el fruto de su boca, come el hombre lo que es bueno,

[[proverbs-13-3]]
^3^ Quien vigila su boca, guarda su vida;

[[proverbs-13-4]]
^4^ Tiene hambre el perezoso, mas no se cumple su deseo;

[[proverbs-13-5]]
^5^ El justo odia la palabra mentirosa,

[[proverbs-13-6]]
^6^ La justicia guarda al íntegro en su camino,

[[proverbs-13-7]]
^7^ Hay quien se hace el rico y nada tiene,

[[proverbs-13-8]]
^8^ El precio de la vida de un hombre es su riqueza;

[[proverbs-13-9]]
^9^ La luz de los justos alegremente luce,

[[proverbs-13-10]]
^10^ La insolencia sólo disputas proporciona;

[[proverbs-13-11]]
^11^ Fortuna rápida, vendrá a menos,

[[proverbs-13-12]]
^12^ Espera prolongada enferma el corazón;

[[proverbs-13-13]]
^13^ Quien desprecia la palabra se perderá,

[[proverbs-13-14]]
^14^ La lección del sabio es fuente de vida,

[[proverbs-13-15]]
^15^ Una gran prudencia alcanza favor,

[[proverbs-13-16]]
^16^ Todo hombre cauto obra con conocimiento,

[[proverbs-13-17]]
^17^ Mensajero perverso cae en desgracia,

[[proverbs-13-18]]
^18^ Miseria e ignominia al que rechaza la instrucción,

[[proverbs-13-19]]
^19^ Deseo cumplido, dulzura para el alma,

[[proverbs-13-20]]
^20^ El que anda con los sabios será sabio;

[[proverbs-13-21]]
^21^ A los pecadores los persigue la desgracia,

[[proverbs-13-22]]
^22^ El hombre de bien deja herencia a los hijos de sus hijos,

[[proverbs-13-23]]
^23^ Las roturas de los pobres dan mucho de comer;

[[proverbs-13-24]]
^24^ Quien escatima la vara, odia a su hijo,

[[proverbs-13-25]]
^25^ Come el justo y queda satisfecho,
[[proverbs-14]]
== Capítulo 14

[[proverbs-14-1]]
^1^ La Sabiduría edifica su casa;

[[proverbs-14-2]]
^2^ Quien anda en rectitud, teme a Yahveh;

[[proverbs-14-3]]
^3^ En la boca del necio hay una raíz de orgullo,

[[proverbs-14-4]]
^4^ Donde no hay bueyes, pesebre vacío;

[[proverbs-14-5]]
^5^ Testigo veraz no miente,

[[proverbs-14-6]]
^6^ Busca el arrogante la sabiduría pero en vano,

[[proverbs-14-7]]
^7^ Apártate del hombre necio,

[[proverbs-14-8]]
^8^ Sabiduría del cauto es atender a su conducta,

[[proverbs-14-9]]
^9^ De los necios se aparta el sacrificio expiatorio,

[[proverbs-14-10]]
^10^ El corazón conoce su propia amargura,

[[proverbs-14-11]]
^11^ La casa de los malos será destruida,

[[proverbs-14-12]]
^12^ Hay caminos que parecen rectos,

[[proverbs-14-13]]
^13^ También en el reír padece el corazón,

[[proverbs-14-14]]
^14^ El perverso de corazón está satisfecho de su conducta,

[[proverbs-14-15]]
^15^ El simple cree cuanto se dice,

[[proverbs-14-16]]
^16^ El sabio teme el mal y de él se aparta,

[[proverbs-14-17]]
^17^ El de genio pronto, hace necedades,

[[proverbs-14-18]]
^18^ La herencia de los simples es la necedad,

[[proverbs-14-19]]
^19^ Los malos se postran ante los buenos,

[[proverbs-14-20]]
^20^ Incluso a su vecino es odioso el pobre,

[[proverbs-14-21]]
^21^ Quien desprecia a su vecino comete pecado;

[[proverbs-14-22]]
^22^ ¿No andan extraviados los que planean el mal?;

[[proverbs-14-23]]
^23^ Todo trabajo produce abundancia,

[[proverbs-14-24]]
^24^ Corona de los sabios es la riqueza,

[[proverbs-14-25]]
^25^ Salvador de vidas es el testigo veraz,

[[proverbs-14-26]]
^26^ El temor de Yahveh es seguridad inexpugnable;

[[proverbs-14-27]]
^27^ El temor de Yahveh es fuente de vida,

[[proverbs-14-28]]
^28^ Pueblo numeroso, gloria del rey;

[[proverbs-14-29]]
^29^ El tardo a la ira tiene gran prudencia,

[[proverbs-14-30]]
^30^ El corazón manso es vida del cuerpo;

[[proverbs-14-31]]
^31^ Quien oprime al débil, ultraja a su Hacedor;

[[proverbs-14-32]]
^32^ El malo es derribado por su propia malicia,

[[proverbs-14-33]]
^33^ En corazón inteligente descansa la sabiduría,

[[proverbs-14-34]]
^34^ La justicia eleva a las naciones,

[[proverbs-14-35]]
^35^ El favor del rey para el siervo prudente;
[[proverbs-15]]
== Capítulo 15

[[proverbs-15-1]]
^1^ Una respuesta suave calma el furor,

[[proverbs-15-2]]
^2^ La lengua de los sabios hace agradable la ciencia,

[[proverbs-15-3]]
^3^ En todo lugar, los ojos de Yahveh,

[[proverbs-15-4]]
^4^ Lengua mansa, árbol de vida,

[[proverbs-15-5]]
^5^ El tonto desprecia la corrección de su padre;

[[proverbs-15-6]]
^6^ La casa del justo abunda en riquezas,

[[proverbs-15-7]]
^7^ Los labios de los sabios siembran ciencia,

[[proverbs-15-8]]
^8^ Yahveh abomina el sacrificio de los malos;

[[proverbs-15-9]]
^9^ Yahveh abomina el camino malo;

[[proverbs-15-10]]
^10^ Corrección severa a quien deja el camino;

[[proverbs-15-11]]
^11^ Seol y Perdición están ante Yahveh:

[[proverbs-15-12]]
^12^ El arrogante no quiere ser reprendido,

[[proverbs-15-13]]
^13^ Corazón alegre hace buena cara,

[[proverbs-15-14]]
^14^ Corazón inteligente busca la ciencia,

[[proverbs-15-15]]
^15^ Todos los días del pobre son malos,

[[proverbs-15-16]]
^16^ Mejor es poco con temor de Yahveh,

[[proverbs-15-17]]
^17^ Más vale un plato de legumbres, con cariño,

[[proverbs-15-18]]
^18^ El hombre violento provoca disputas,

[[proverbs-15-19]]
^19^ El camino del perezoso es como un seto de espinos.

[[proverbs-15-20]]
^20^ El hijo sabio es la alegría de su padre,

[[proverbs-15-21]]
^21^ La necedad alegra al insensato,

[[proverbs-15-22]]
^22^ Donde no hay consultas, los planes fracasan;

[[proverbs-15-23]]
^23^ El hombre halla alegría en la respuesta de su boca;

[[proverbs-15-24]]
^24^ Camino de la vida, hacia arriba, para el sabio,

[[proverbs-15-25]]
^25^ La casa de los soberbios la destruye Yahveh,

[[proverbs-15-26]]
^26^ Yahveh abomina los proyectos perversos;

[[proverbs-15-27]]
^27^ Quien se da al robo, perturba su casa,

[[proverbs-15-28]]
^28^ El corazón del justo recapacita para responder,

[[proverbs-15-29]]
^29^ Yahveh se aleja de los malos,

[[proverbs-15-30]]
^30^ Una mirada luminosa alegra el corazón,

[[proverbs-15-31]]
^31^ Oído que escucha reprensión saludable,

[[proverbs-15-32]]
^32^ Quien desatiende la corrección se desprecia a sí mismo,

[[proverbs-15-33]]
^33^ El temor de Yahveh instruye en sabiduría:
[[proverbs-16]]
== Capítulo 16

[[proverbs-16-1]]
^1^ Al hombre, los planes del corazón;

[[proverbs-16-2]]
^2^ Al hombre le parecen puros todos sus caminos,

[[proverbs-16-3]]
^3^ Encomienda tus obras a Yahveh

[[proverbs-16-4]]
^4^ Todas las obras de Yahveh tienen su propio fin,

[[proverbs-16-5]]
^5^ Yahveh abomina al de corazón altivo,

[[proverbs-16-6]]
^6^ Con amor y lealtad se expía la falta;

[[proverbs-16-7]]
^7^ Cuando Yahveh se complace en la conducta de un hombre.

[[proverbs-16-8]]
^8^ Más vale poco, con justicia,

[[proverbs-16-9]]
^9^ El corazón del hombre medita su camino,

[[proverbs-16-10]]
^10^ Oráculo en los labios del rey:

[[proverbs-16-11]]
^11^ De Yahveh son la balanza y los platillos justos,

[[proverbs-16-12]]
^12^ Los reyes aborrecen las malas acciones,

[[proverbs-16-13]]
^13^ El favor del rey para los labios justos;

[[proverbs-16-14]]
^14^ El furor del rey es mensajero de muerte;

[[proverbs-16-15]]
^15^ Si el rostro del rey se ilumina, hay vida;

[[proverbs-16-16]]
^16^ Adquirir sabiduría, cuánto mejor que el oro;

[[proverbs-16-17]]
^17^ La calzada de los rectos es apartarse del mal;

[[proverbs-16-18]]
^18^ La arrogancia precede a la ruina;

[[proverbs-16-19]]
^19^ Mejor es ser humilde con los pobres

[[proverbs-16-20]]
^20^ El que está atento a la palabra encontrará la dicha,

[[proverbs-16-21]]
^21^ Al de corazón sabio, se le llama inteligente,

[[proverbs-16-22]]
^22^ La prudencia es fuente de vida para el que la tiene,

[[proverbs-16-23]]
^23^ El corazón del sabio hace circunspecta su boca,

[[proverbs-16-24]]
^24^ Palabras suaves, panal de miel:

[[proverbs-16-25]]
^25^ Hay caminos que parecen rectos,

[[proverbs-16-26]]
^26^ El ansia del trabajador para él trabaja,

[[proverbs-16-27]]
^27^ El hombre malvado trama el mal,

[[proverbs-16-28]]
^28^ El hombre perverso provoca querellas,

[[proverbs-16-29]]
^29^ El hombre violento seduce al vecino,

[[proverbs-16-30]]
^30^ Quien cierra los ojos es para meditar maldades,

[[proverbs-16-31]]
^31^ Cabellos blancos son corona de honor;

[[proverbs-16-32]]
^32^ Más vale el hombre paciente que el héroe,

[[proverbs-16-33]]
^33^ Se echan las suertes en el seno,
[[proverbs-17]]
== Capítulo 17

[[proverbs-17-1]]
^1^ Mejor es un mendrugo de pan a secas, pero con tranquilidad,

[[proverbs-17-2]]
^2^ El siervo prudente prevalece sobre el hijo sin honra;

[[proverbs-17-3]]
^3^ Crisol para la plata, horno para el oro;

[[proverbs-17-4]]
^4^ El malo está atento a los labios inicuos,

[[proverbs-17-5]]
^5^ Quien se burla de un pobre, ultraja a su Hacedor,

[[proverbs-17-6]]
^6^ Corona de los ancianos son los hijos de los hijos;

[[proverbs-17-7]]
^7^ Al necio no le sienta un lenguaje pulido,

[[proverbs-17-8]]
^8^ El obsequio es un talismán, para el que puede hacerlo;

[[proverbs-17-9]]
^9^ El que cubre un delito, se gana una amistad

[[proverbs-17-10]]
^10^ Más afecta un reproche a un hombre inteligente

[[proverbs-17-11]]
^11^ El malvado sólo busca rebeliones,

[[proverbs-17-12]]
^12^ Mejor topar con osa privada de sus cachorros

[[proverbs-17-13]]
^13^ Si uno devuelve mal por bien

[[proverbs-17-14]]
^14^ Entablar proceso es dar curso libre a las aguas;

[[proverbs-17-15]]
^15^ Justificar al malo y condenar al justo;

[[proverbs-17-16]]
^16^ ¿De qué sirve la riqueza en manos del necio?

[[proverbs-17-17]]
^17^ El amigo ama en toda ocasión,

[[proverbs-17-18]]
^18^ Es hombre insensato el que choca la mano

[[proverbs-17-19]]
^19^ El que ama el pecado, ama los golpes,

[[proverbs-17-20]]
^20^ El de corazón pervertido, no hallará la dicha;

[[proverbs-17-21]]
^21^ El que engendra un necio, es para su mal;

[[proverbs-17-22]]
^22^ El corazón alegre mejora la salud;

[[proverbs-17-23]]
^23^ El malo acepta regalos en su seno,

[[proverbs-17-24]]
^24^ Ante el hombre inteligente está la sabiduría,

[[proverbs-17-25]]
^25^ Hijo necio, tristeza de su padre,

[[proverbs-17-26]]
^26^ No es bueno poner multa al justo,

[[proverbs-17-27]]
^27^ El que retiene sus palabras es conocedor de la ciencia,

[[proverbs-17-28]]
^28^ Hasta al necio, si calla, se le tiene por sabio,
[[proverbs-18]]
== Capítulo 18

[[proverbs-18-1]]
^1^ El que vive apartado, busca su capricho,

[[proverbs-18-2]]
^2^ El necio no halla gusto en la prudencia,

[[proverbs-18-3]]
^3^ Cuando llega la maldad, también llega el desprecio;

[[proverbs-18-4]]
^4^ Las palabras en la boca del hombre son aguas profundas:

[[proverbs-18-5]]
^5^ No es bueno tener miramientos con el malo,

[[proverbs-18-6]]
^6^ Los labios del necio se meten en el proceso,

[[proverbs-18-7]]
^7^ La boca del necio es su ruina,

[[proverbs-18-8]]
^8^ Las palabras del delator son golosinas,

[[proverbs-18-9]]
^9^ El que es perezoso en el trabajo,

[[proverbs-18-10]]
^10^ El nombre de Yahveh es torre fuerte,

[[proverbs-18-11]]
^11^ La fortuna del rico es su plaza fuerte;

[[proverbs-18-12]]
^12^ El corazón humano se engríe antes de la ruina,

[[proverbs-18-13]]
^13^ Si uno responde antes de escuchar

[[proverbs-18-14]]
^14^ El ánimo del hombre lo sostiene en su enfermedad;

[[proverbs-18-15]]
^15^ Corazón inteligente adquiere ciencia,

[[proverbs-18-16]]
^16^ El regalo de un hombre todo se lo allana,

[[proverbs-18-17]]
^17^ Parece justo el primero que pleitea;

[[proverbs-18-18]]
^18^ Las suertes ponen fin a los litigios

[[proverbs-18-19]]
^19^ Un hermano ofendido es peor que una plaza fuerte,

[[proverbs-18-20]]
^20^ Con el fruto de la boca sacia el hombre su vientre,

[[proverbs-18-21]]
^21^ Muerte y vida están en poder de la lengua,

[[proverbs-18-22]]
^22^ Quien halló mujer, halló cosa buena,

[[proverbs-18-23]]
^23^ El pobre habla suplicando,

[[proverbs-18-24]]
^24^ Hay amigos que causan la ruina,
[[proverbs-19]]
== Capítulo 19

[[proverbs-19-1]]
^1^ Mejor es el pobre que camina en su integridad

[[proverbs-19-2]]
^2^ Tampoco es bueno el afán cuando falta la ciencia,

[[proverbs-19-3]]
^3^ La necedad del hombre pervierte su camino,

[[proverbs-19-4]]
^4^ La riqueza multiplica los amigos,

[[proverbs-19-5]]
^5^ El testigo falso no quedará impune,

[[proverbs-19-6]]
^6^ Son numerosos los que halagan al noble,

[[proverbs-19-7]]
^7^ Los hermanos del pobre le odian todos,

[[proverbs-19-8]]
^8^ El que adquiere cordura se ama a sí mismo,

[[proverbs-19-9]]
^9^ El testigo falso no quedará impune,

[[proverbs-19-10]]
^10^ No sienta bien al necio vivir en delicias,

[[proverbs-19-11]]
^11^ La prudencia del hombre domina su ira,

[[proverbs-19-12]]
^12^ Como rugido de león la indignación del rey,

[[proverbs-19-13]]
^13^ El hijo necio, calamidad para su padre,

[[proverbs-19-14]]
^14^ Casa y fortuna se heredan de los padres,

[[proverbs-19-15]]
^15^ La pereza hunde en el sopor,

[[proverbs-19-16]]
^16^ Quien guarda los mandatos se guarda a sí mismo,

[[proverbs-19-17]]
^17^ Quien se apiada del débil, presta a Yahveh,

[[proverbs-19-18]]
^18^ Mientras hay esperanza corrige a tu hijo,

[[proverbs-19-19]]
^19^ El iracundo carga con la multa;

[[proverbs-19-20]]
^20^ Escucha el consejo, acoge la corrección,

[[proverbs-19-21]]
^21^ Muchos proyectos en el corazón del hombre,

[[proverbs-19-22]]
^22^ Lo que se desea en un hombre es la bondad,

[[proverbs-19-23]]
^23^ El temor de Yahveh es para vida,

[[proverbs-19-24]]
^24^ El perezoso hunde la mano en el plato,

[[proverbs-19-25]]
^25^ Golpea al arrogante y el simple se volverá sensato;

[[proverbs-19-26]]
^26^ El que despoja a su padre y expulsa a su madre,

[[proverbs-19-27]]
^27^ Deja ya, hijo, de escuchar la instrucción,

[[proverbs-19-28]]
^28^ El testigo malvado se burla del derecho;

[[proverbs-19-29]]
^29^ Los castigos están hechos para los arrogantes;
[[proverbs-20]]
== Capítulo 20

[[proverbs-20-1]]
^1^ Arrogante es el vino, tumultuosa la bebida;

[[proverbs-20-2]]
^2^ Como rugido de león la indignación del rey,

[[proverbs-20-3]]
^3^ Es gloria para el hombre apartarse de litigios,

[[proverbs-20-4]]
^4^ A partir del otoño, el perezoso no trabaja,

[[proverbs-20-5]]
^5^ El consejo en el corazón del hombre es agua profunda,

[[proverbs-20-6]]
^6^ Muchos hombres se dicen piadosos;

[[proverbs-20-7]]
^7^ El justo camina en la integridad;

[[proverbs-20-8]]
^8^ Un rey sentado en el tribunal

[[proverbs-20-9]]
^9^ ¿Quién puede decir: «Purifiqué mi corazón,

[[proverbs-20-10]]
^10^ Dos pesos y dos medidas,

[[proverbs-20-11]]
^11^ Incluso en sus acciones da el muchacho a conocer

[[proverbs-20-12]]
^12^ El oído que oye y el ojo que ve;

[[proverbs-20-13]]
^13^ No ames el sueño, para no hacerte pobre;

[[proverbs-20-14]]
^14^ «¡Malo, malo!» dice el comprador,

[[proverbs-20-15]]
^15^ Hay oro y numerosas perlas,

[[proverbs-20-16]]
^16^ Tómale su vestido, pues salió fiador de otro;

[[proverbs-20-17]]
^17^ El pan de fraude le es dulce al hombre,

[[proverbs-20-18]]
^18^ Los proyectos con el consejo se afianzan:

[[proverbs-20-19]]
^19^ El que anda murmurando descubre secretos;

[[proverbs-20-20]]
^20^ Al que maldice a su padre y a su madre,

[[proverbs-20-21]]
^21^ Herencia adquirida al principio con presteza,

[[proverbs-20-22]]
^22^ No digas: «Voy a devolver el mal»;

[[proverbs-20-23]]
^23^ Tener dos pesas lo abomina Yahveh;

[[proverbs-20-24]]
^24^ De Yahveh dependen los pasos del hombre:

[[proverbs-20-25]]
^25^ Lazo es para el hombre pronunciar a la ligera: «¡Sagrado!»

[[proverbs-20-26]]
^26^ Un rey sabio aventa a los malos

[[proverbs-20-27]]
^27^ Lámpara de Yahveh es el hálito del hombre

[[proverbs-20-28]]
^28^ Bondad y lealtad custodian al rey,

[[proverbs-20-29]]
^29^ El vigor es la belleza de los jóvenes,

[[proverbs-20-30]]
^30^ Las cicatrices de las heridas son remedio contra el mal,
[[proverbs-21]]
== Capítulo 21

[[proverbs-21-1]]
^1^ Corriente de agua es el corazón del rey en la mano de Yahveh,

[[proverbs-21-2]]
^2^ Al hombre le parecen rectos todos sus caminos,

[[proverbs-21-3]]
^3^ Practicar la justicia y la equidad,

[[proverbs-21-4]]
^4^ Ojos altivos, corazón arrogante,

[[proverbs-21-5]]
^5^ Los proyectos del diligente, todo son ganancia;

[[proverbs-21-6]]
^6^ Hacer tesoros con lengua engañosa,

[[proverbs-21-7]]
^7^ La violencia de los malos los domina,

[[proverbs-21-8]]
^8^ Tortuoso es el camino del hombre criminal,

[[proverbs-21-9]]
^9^ Mejor es vivir en la esquina del terrado,

[[proverbs-21-10]]
^10^ El alma del malvado desea el mal,

[[proverbs-21-11]]
^11^ Cuando se castiga al arrogante, el simple se hace sabio;

[[proverbs-21-12]]
^12^ El Justo observa la casa del malvado,

[[proverbs-21-13]]
^13^ Quien cierra los oídos a las súplicas del débil

[[proverbs-21-14]]
^14^ Regalo a escondidas, aplaca la cólera,

[[proverbs-21-15]]
^15^ Alegría para el justo es el cumplimiento de la justicia,

[[proverbs-21-16]]
^16^ El hombre que se aparta del camino de la prudencia

[[proverbs-21-17]]
^17^ Se arruina el hombre que ama el placer,

[[proverbs-21-18]]
^18^ Rescate del justo es el malo,

[[proverbs-21-19]]
^19^ Mejor es habitar en el desierto

[[proverbs-21-20]]
^20^ Tesoro precioso y aceite en la casa del sabio,

[[proverbs-21-21]]
^21^ Quien va tras la justicia y el amor

[[proverbs-21-22]]
^22^ El sabio escala la ciudad de los fuertes,

[[proverbs-21-23]]
^23^ El que guarda su boca y su lengua,

[[proverbs-21-24]]
^24^ Al insolente y altivo se le llama: «arrogante»;

[[proverbs-21-25]]
^25^ El deseo del perezoso le lleva a la muerte,

[[proverbs-21-26]]
^26^ Todo el día está el malo codicioso;

[[proverbs-21-27]]
^27^ El sacrificio de los malos es abominable,

[[proverbs-21-28]]
^28^ El testigo falso perecerá,

[[proverbs-21-29]]
^29^ El hombre malo se muestra atrevido,

[[proverbs-21-30]]
^30^ No hay sabiduría, ni hay prudencia

[[proverbs-21-31]]
^31^ Se prepara el caballo para el día del combate,
[[proverbs-22]]
== Capítulo 22

[[proverbs-22-1]]
^1^ Más vale buen nombre que muchas riquezas,

[[proverbs-22-2]]
^2^ El rico y el pobre se encuentran,

[[proverbs-22-3]]
^3^ El hombre precavido ve el mal y se esconde,

[[proverbs-22-4]]
^4^ Premio de la humildad, el temor de Yahveh,

[[proverbs-22-5]]
^5^ Espinas y lazos en la senda del malo, el que cuida de su vida,

[[proverbs-22-6]]
^6^ Instruye al joven según sus disposiciones,

[[proverbs-22-7]]
^7^ El rico domina a los pobres,

[[proverbs-22-8]]
^8^ Quien siembra injusticia cosecha miserias

[[proverbs-22-9]]
^9^ El de buena intención será bendito,

[[proverbs-22-10]]
^10^ Expulsa al arrogante y se irá el litigio,

[[proverbs-22-11]]
^11^ El que ama los corazones puros,

[[proverbs-22-12]]
^12^ Los ojos de Yahveh custodian la ciencia,

[[proverbs-22-13]]
^13^ El perezoso dice: «Hay fuera un león;

[[proverbs-22-14]]
^14^ Fosa profunda la boca de las mujeres ajenas:

[[proverbs-22-15]]
^15^ La necedad está enraizada en el corazón del joven,

[[proverbs-22-16]]
^16^ El que oprime a un débil, lo engrandece;

[[proverbs-22-17]]
^17^ Presta oído y escucha las palabras de los sabios,

[[proverbs-22-18]]
^18^ porque te será dulce guardarlas en tu seno,

[[proverbs-22-19]]
^19^ Para que esté en Yahveh tu confianza

[[proverbs-22-20]]
^20^ ¿No he escrito para ti treinta capítulos

[[proverbs-22-21]]
^21^ para hacerte conocer la certeza de las palabras verdaderas,

[[proverbs-22-22]]
^22^ No despojes al débil, porque es débil,

[[proverbs-22-23]]
^23^ porque Yahveh defenderá su causa

[[proverbs-22-24]]
^24^ No tomes por compañero a un hombre airado,

[[proverbs-22-25]]
^25^ no sea que aprendas sus senderos,

[[proverbs-22-26]]
^26^ No seas de los que chocan la mano,

[[proverbs-22-27]]
^27^ porque si no tienes con qué pagar,

[[proverbs-22-28]]
^28^ No desplaces el lindero antiguo

[[proverbs-22-29]]
^29^ ¿Has visto un hombre hábil en su oficio?
[[proverbs-23]]
== Capítulo 23

[[proverbs-23-1]]
^1^ Si te sientas a comer con poderoso,

[[proverbs-23-2]]
^2^ pon un cuchillo a tu garganta

[[proverbs-23-3]]
^3^ no desees sus manjares,

[[proverbs-23-4]]
^4^ No te fatigues por eniquecerte,

[[proverbs-23-5]]
^5^ Pones tus ojos en ello y no hay nada.

[[proverbs-23-6]]
^6^ No comas pan con hombre de malas intenciones,

[[proverbs-23-7]]
^7^ Porque, según lo que calcula en su interior,

[[proverbs-23-8]]
^8^ Nada más comer lo vomitarías

[[proverbs-23-9]]
^9^ A oídos de necio no hables,

[[proverbs-23-10]]
^10^ No desplaces el lindero antiguo,

[[proverbs-23-11]]
^11^ porque su vengador es poderoso,

[[proverbs-23-12]]
^12^ Aplica tu corazón a la instrucción,

[[proverbs-23-13]]
^13^ No ahorres corrección al niño,

[[proverbs-23-14]]
^14^ Con la vara le castigarás

[[proverbs-23-15]]
^15^ Hijo mío, si tu corazón es sabio,

[[proverbs-23-16]]
^16^ y exultarán mis riñones

[[proverbs-23-17]]
^17^ No envidie tu corazón a los pecadores,

[[proverbs-23-18]]
^18^ porque hay un mañana,

[[proverbs-23-19]]
^19^ Escucha, hijo, y serás sabio,

[[proverbs-23-20]]
^20^ No seas de los que se emborrachan de vino,

[[proverbs-23-21]]
^21^ porque borracho y glotón se empobrecen

[[proverbs-23-22]]
^22^ Escucha a tu padre, que él te engendró,

[[proverbs-23-23]]
^23^ Adquiere la verdad y no la vendas:

[[proverbs-23-24]]
^24^ El padre del justo rebosa de gozo,

[[proverbs-23-25]]
^25^ Se alegrarán tu padre y tu madre,

[[proverbs-23-26]]
^26^ Dame, hijo mío, tu corazón,

[[proverbs-23-27]]
^27^ Fosa profunda es la prostituta,

[[proverbs-23-28]]
^28^ También ella como ladrón pone emboscadas,

[[proverbs-23-29]]
^29^ ¿Para quién las «Desgracias»? ¿para quién los «Ayes»?

[[proverbs-23-30]]
^30^ Para los que se eternizan con el vino,

[[proverbs-23-31]]
^31^ No mires el vino: ¡Qué buen color tiene!

[[proverbs-23-32]]
^32^ Pero, a la postre, como serpiente muerde,

[[proverbs-23-33]]
^33^ Tus ojos verán cosas extrañas,

[[proverbs-23-34]]
^34^ Estarás como acostado en el corazón del mar,

[[proverbs-23-35]]
^35^ «Me han golpeado, pero no estoy enfermo;
[[proverbs-24]]
== Capítulo 24

[[proverbs-24-1]]
^1^ No tengas envidia de los malos,

[[proverbs-24-2]]
^2^ porque su corazón trama violencias,

[[proverbs-24-3]]
^3^ Con la sabiduria se construye una casa,

[[proverbs-24-4]]
^4^ con la ciencia se llenan los cilleros

[[proverbs-24-5]]
^5^ El varón sabio está fuerte,

[[proverbs-24-6]]
^6^ porque con sabios consejos harás la guerra,

[[proverbs-24-7]]
^7^ Muy alta está la sabiduría para el necio:

[[proverbs-24-8]]
^8^ Al que piensa en hacer mal,

[[proverbs-24-9]]
^9^ La necedad sólo maquina pecados,

[[proverbs-24-10]]
^10^ Si te dejas abatir el día de la angustia,

[[proverbs-24-11]]
^11^ Libra a los que son llevados a la muerte,

[[proverbs-24-12]]
^12^ Si dices: «Mira que no lo sabíamos»,

[[proverbs-24-13]]
^13^ Come miel, hijo mío, porque es buena.

[[proverbs-24-14]]
^14^ Pues sábete que así será la sabiduría para tu alma,

[[proverbs-24-15]]
^15^ No pongas, malvado, asechanzas en la mansión del justo,

[[proverbs-24-16]]
^16^ Que siete veces cae el justo, pero se levanta,

[[proverbs-24-17]]
^17^ No te alegres por la caída de tu enemigo,

[[proverbs-24-18]]
^18^ no sea que lo vea Yahveh y le desagrade,

[[proverbs-24-19]]
^19^ No te enfurezcas por causa de los malvados,

[[proverbs-24-20]]
^20^ Porque para el malvado no hay un mañana:

[[proverbs-24-21]]
^21^ Teme, hijo mío, a Yahveh y al rey,

[[proverbs-24-22]]
^22^ porque al instante surgirá su calamidad,

[[proverbs-24-23]]
^23^ También esto pertenece a los sabios:

[[proverbs-24-24]]
^24^ Al que dice al malo: «Eres justo»,

[[proverbs-24-25]]
^25^ los que los castigan, viven felices,

[[proverbs-24-26]]
^26^ Besa en los labios,

[[proverbs-24-27]]
^27^ Ordena tus trabajos de fuera

[[proverbs-24-28]]
^28^ No des testimonio, en vano, contra tu prójimo,

[[proverbs-24-29]]
^29^ No digas: «Como él me ha hecho a mí, le haré yo a él,

[[proverbs-24-30]]
^30^ He pasado junto al campo de un perezoso,

[[proverbs-24-31]]
^31^ y estaba todo invadido de ortigas,

[[proverbs-24-32]]
^32^ Al verlo, medité en mi corazón,

[[proverbs-24-33]]
^33^ «Un poco dormir, otro poco dormitar,

[[proverbs-24-34]]
^34^ y llegará, como vagabundo, tu miseria
[[proverbs-25]]
== Capítulo 25

[[proverbs-25-1]]
^1^ También estos son proverbios de Salomón, transcritos por los

[[proverbs-25-2]]
^2^ Es gloria de Dios ocultar una cosa,

[[proverbs-25-3]]
^3^ Los cielos por su altura, la tierra por su profundidad,

[[proverbs-25-4]]
^4^ Quita las escorias de la plata,

[[proverbs-25-5]]
^5^ quita al malo de delante del rey,

[[proverbs-25-6]]
^6^ No te des importancia ante el rey,

[[proverbs-25-7]]
^7^ porque es mejor que te digan: «Sube acá»,

[[proverbs-25-8]]
^8^ no te apresures a llevarlo a juicio;

[[proverbs-25-9]]
^9^ Defiende tu causa contra tu prójimo,

[[proverbs-25-10]]
^10^ no sea que el que lo oye te avergüence,

[[proverbs-25-11]]
^11^ Manzanas de oro con adornos de plata,

[[proverbs-25-12]]
^12^ Anillo de oro, o collar de oro fino,

[[proverbs-25-13]]
^13^ Como frescor de nieve el día de la siega

[[proverbs-25-14]]
^14^ Nubes y viento, pero no lluvia,

[[proverbs-25-15]]
^15^ Con paciencia se persuade al juez,

[[proverbs-25-16]]
^16^ ¿Has hallado miel?, come lo que necesites;

[[proverbs-25-17]]
^17^ Pon tu pie pocas veces en casa del vecino,

[[proverbs-25-18]]
^18^ Martillo, espada, flecha aguda:

[[proverbs-25-19]]
^19^ Diente roto, pie titubeante:

[[proverbs-25-20]]
^20^ como quitar el vestido en día helado.

[[proverbs-25-21]]
^21^ Si tu enemigo tiene hambre, dale de comer,

[[proverbs-25-22]]
^22^ así amontonas sobre su cabeza brasas

[[proverbs-25-23]]
^23^ El viento norte trae la lluvia,

[[proverbs-25-24]]
^24^ Mejor es vivir en la esquina del terrado,

[[proverbs-25-25]]
^25^ Agua fresca en fauces sedientas:

[[proverbs-25-26]]
^26^ Fuente hollada, manantial ensuciado,

[[proverbs-25-27]]
^27^ No es bueno comer mucha miel,

[[proverbs-25-28]]
^28^ Ciudad abierta y sin muralla
[[proverbs-26]]
== Capítulo 26

[[proverbs-26-1]]
^1^ Como nieve en verano y lluvia en la siega,

[[proverbs-26-2]]
^2^ Como se escapa el pájaro y vuela la golondrina,

[[proverbs-26-3]]
^3^ Látigo para el caballo, brida para el asno

[[proverbs-26-4]]
^4^ No respondas al necio según su necedad,

[[proverbs-26-5]]
^5^ Responde al necio según su necedad,

[[proverbs-26-6]]
^6^ Se corta los pies, se empapa de amargura,

[[proverbs-26-7]]
^7^ Como las piernas vacilantes del cojo,

[[proverbs-26-8]]
^8^ Como sujetar una piedra en la honda,

[[proverbs-26-9]]
^9^ Como espino que va a parar a mano de borracho,

[[proverbs-26-10]]
^10^ Como arquero que a todos hiere,

[[proverbs-26-11]]
^11^ Como el perro vuelve a su vómito,

[[proverbs-26-12]]
^12^ ¿Has visto a un hombre que se cree sabio?

[[proverbs-26-13]]
^13^ Dice el perezoso: «¡Un león en el camino!

[[proverbs-26-14]]
^14^ La puerta gira en los goznes,

[[proverbs-26-15]]
^15^ El perezoso hunde la mano en el plato;

[[proverbs-26-16]]
^16^ El perezoso se tiene por más sabio

[[proverbs-26-17]]
^17^ Agarra por las orejas a un perro que pasa

[[proverbs-26-18]]
^18^ Como un loco que arroja saetas escondidas,

[[proverbs-26-19]]
^19^ tal es el hombre que engaña a su prójimo,

[[proverbs-26-20]]
^20^ Cuando se acaba la leña, se apaga el fuego,

[[proverbs-26-21]]
^21^ Carbón sobre brasas y leña sobre fuego,

[[proverbs-26-22]]
^22^ Las palabras del delator son golosinas

[[proverbs-26-23]]
^23^ Plata con escorias esmaltada sobre arcilla,

[[proverbs-26-24]]
^24^ El que odia, disimula con sus labios,

[[proverbs-26-25]]
^25^ si da a su voz un tono amable, no te fíes,

[[proverbs-26-26]]
^26^ Encubrirá su odio con engaño,

[[proverbs-26-27]]
^27^ El que excava una fosa caerá en ella,

[[proverbs-26-28]]
^28^ La lengua mentirosa odia a sus víctimas,
[[proverbs-27]]
== Capítulo 27

[[proverbs-27-1]]
^1^ No te regocijes por el día de mañana,

[[proverbs-27-2]]
^2^ Que otro te alabe y no tu propia boca;

[[proverbs-27-3]]
^3^ Pesada es la piedra y pesada la arena,

[[proverbs-27-4]]
^4^ El furor es cruel, agua desbordada la cólera;

[[proverbs-27-5]]
^5^ Mejor es reprensión manifiesta

[[proverbs-27-6]]
^6^ Leales son las heridas del amigo,

[[proverbs-27-7]]
^7^ Alma saciada pisotea la miel,

[[proverbs-27-8]]
^8^ Como yerra el pájaro lejos de su nido,

[[proverbs-27-9]]
^9^ El aceite y el perfume alegran el corazón,

[[proverbs-27-10]]
^10^ No abandones a tu amigo ni al amigo de tu padre;

[[proverbs-27-11]]
^11^ Sé sabio, hijo mío, y alegra mi corazón;

[[proverbs-27-12]]
^12^ El hombre precavido ve el mal y se esconde,

[[proverbs-27-13]]
^13^ Tómale su vestido, pues salió fiador de otro;

[[proverbs-27-14]]
^14^ Al que ya de mañana a su prójimo bendice en alta voz,

[[proverbs-27-15]]
^15^ Goteo incesante en día de lluvia

[[proverbs-27-16]]
^16^ el que la retiene, retiene viento

[[proverbs-27-17]]
^17^ El hierro con hierro se aguza,

[[proverbs-27-18]]
^18^ El que vigila una higuera come de su fruto,

[[proverbs-27-19]]
^19^ Como en el agua un rostro refleja otro rostro,

[[proverbs-27-20]]
^20^ Seol y Perdición son insaciables;

[[proverbs-27-21]]
^21^ Crisol para la plata, horno para el oro,

[[proverbs-27-22]]
^22^ Aunque machaques al necio en el mortero,

[[proverbs-27-23]]
^23^ Conoce a fondo el estado de tu ganado,

[[proverbs-27-24]]
^24^ porque no es eterna la riqueza,

[[proverbs-27-25]]
^25^ Cortada la hierba, aparecido el retoño,

[[proverbs-27-26]]
^26^ ten corderos para poderte vestir,

[[proverbs-27-27]]
^27^ leche de cabras abundante para tu sustento,
[[proverbs-28]]
== Capítulo 28

[[proverbs-28-1]]
^1^ El malo huye sin que nadie le persiga,

[[proverbs-28-2]]
^2^ Cuando un país es rebelde, son muchos sus príncipes;

[[proverbs-28-3]]
^3^ Hombre malo que oprime a los débiles

[[proverbs-28-4]]
^4^ Los que abandonan la ley alaban al malo,

[[proverbs-28-5]]
^5^ Los hombres malos no entienden de equidad,

[[proverbs-28-6]]
^6^ Mejor es el pobre que camina en su integridad

[[proverbs-28-7]]
^7^ El que guarda la ley es un hijo inteligente,

[[proverbs-28-8]]
^8^ El que aumenta su riqueza por usura e interés,

[[proverbs-28-9]]
^9^ El que aparta su oído para no oír la ley,

[[proverbs-28-10]]
^10^ El que extravía a los rectos por el mal camino,

[[proverbs-28-11]]
^11^ El hombre rico se cree sabio,

[[proverbs-28-12]]
^12^ Cuando se alegran los justos, es grande el regocijo,

[[proverbs-28-13]]
^13^ Al que encubre sus faltas, no le saldrá bien;

[[proverbs-28-14]]
^14^ Dichoso el hombre que siempre está en temor;

[[proverbs-28-15]]
^15^ León rugiente, oso hambriento,

[[proverbs-28-16]]
^16^ Príncipe sin inteligencia multiplica la opresión,

[[proverbs-28-17]]
^17^ El hombre culpable de una muerte huirá hasta la tumba;

[[proverbs-28-18]]
^18^ El que anda sin tacha será salvo,

[[proverbs-28-19]]
^19^ Quien cultiva su tierra se hartará de pan,

[[proverbs-28-20]]
^20^ El hombre leal será muy bendecido,

[[proverbs-28-21]]
^21^ No es bueno hacer acepción de personas,

[[proverbs-28-22]]
^22^ El hombre de malas intenciones corre tras la riqueza,

[[proverbs-28-23]]
^23^ El hombre que reprende halla al cabo más gracia

[[proverbs-28-24]]
^24^ El que roba a su padre y a su madre y dice: «No hay en ello

[[proverbs-28-25]]
^25^ El hombre ambicioso azuza querellas,

[[proverbs-28-26]]
^26^ El que confía en su corazón es un necio,

[[proverbs-28-27]]
^27^ El que da a los pobres no conocerá la indigencia,

[[proverbs-28-28]]
^28^ Cuando se alzan los malos, todos se esconden,
[[proverbs-29]]
== Capítulo 29

[[proverbs-29-1]]
^1^ El hombre que, reprendido, endurece la cerviz,

[[proverbs-29-2]]
^2^ Cuando los justos se multiplican, el pueblo se alegra,

[[proverbs-29-3]]
^3^ El que ama la sabiduría, da alegría a su padre,

[[proverbs-29-4]]
^4^ El rey, con la equidad, mantiene el país,

[[proverbs-29-5]]
^5^ El hombre que adula a su prójimo

[[proverbs-29-6]]
^6^ En el pecado del malo hay una trampa,

[[proverbs-29-7]]
^7^ El justo conoce la causa de los débiles,

[[proverbs-29-8]]
^8^ Los arrogantes turban la ciudad,

[[proverbs-29-9]]
^9^ Cuando el sabio tiene un pleito con el necio,

[[proverbs-29-10]]
^10^ Los hombres sanguinarios odian al intachable,

[[proverbs-29-11]]
^11^ El necio da salida a toda su pasión;

[[proverbs-29-12]]
^12^ Si un jefe hace caso de las palabras mentirosas,

[[proverbs-29-13]]
^13^ El pobre y el opresor se encuentran,

[[proverbs-29-14]]
^14^ El rey que juzga con verdad a los débiles,

[[proverbs-29-15]]
^15^ Vara y reprensión dan sabiduría,

[[proverbs-29-16]]
^16^ Cuando se multiplican los malos, se multiplican los delitos,

[[proverbs-29-17]]
^17^ Corrige a tu hijo y te dejará tranquilo;

[[proverbs-29-18]]
^18^ Cuando no hay visiones, el pueblo se relaja,

[[proverbs-29-19]]
^19^ No se corrige a un siervo con palabras,

[[proverbs-29-20]]
^20^ ¿Has visto un hombre dispuesto siempre a hablar?

[[proverbs-29-21]]
^21^ Si se mima a un esclavo desde niño,

[[proverbs-29-22]]
^22^ El hombre violento provoca querellas,

[[proverbs-29-23]]
^23^ El orgullo del pobre lo humillará;

[[proverbs-29-24]]
^24^ El que reparte con ladrón se odia a sí mismo,

[[proverbs-29-25]]
^25^ Temblar ante los hombres es un lazo;

[[proverbs-29-26]]
^26^ Son muchos los que buscan el favor del jefe,

[[proverbs-29-27]]
^27^ Abominación para los justos es el hombre inicuo
[[proverbs-30]]
== Capítulo 30

[[proverbs-30-1]]
^1^ Palabras de Agur, hijo de Yaqué, de Massá. Oráculo de este

[[proverbs-30-2]]
^2^ ¡Soy el más estúpido de los hombres!

[[proverbs-30-3]]
^3^ No he aprendido la sabiduría,

[[proverbs-30-4]]
^4^ ¿Quién subió a los cielos y volvió a bajar?

[[proverbs-30-5]]
^5^ Probadas son todas las palabras de Dios;

[[proverbs-30-6]]
^6^ No añadas nada a sus palabras,

[[proverbs-30-7]]
^7^ Dos cosas te pido.

[[proverbs-30-8]]
^8^ Aleja de mí la mentira y la palabra engañosa;

[[proverbs-30-9]]
^9^ no sea que llegue a hartarme y reniegue,

[[proverbs-30-10]]
^10^ No calumnies a un siervo ante su amo

[[proverbs-30-11]]
^11^ Hay gente que maldice a su padre,

[[proverbs-30-12]]
^12^ gente que se cree pura

[[proverbs-30-13]]
^13^ ¡gente de qué altivos ojos,

[[proverbs-30-14]]
^14^ gente cuyos dientes son espadas,

[[proverbs-30-15]]
^15^ La sanguijuela tiene dos hijas: «¡Daca, daca!»

[[proverbs-30-16]]
^16^ El seol, el seno estéril,

[[proverbs-30-17]]
^17^ Al ojo que se ríe del padre

[[proverbs-30-18]]
^18^ Tres cosas hay que me desbordan

[[proverbs-30-19]]
^19^ el camino del águila en el cielo,

[[proverbs-30-20]]
^20^ Este es el camino de la mujer adúltera:

[[proverbs-30-21]]
^21^ Por tres cosas tiembla la tierra

[[proverbs-30-22]]
^22^ Por esclavo que llega a rey,

[[proverbs-30-23]]
^23^ por mujer odiada que se casa,

[[proverbs-30-24]]
^24^ Hay cuatro seres los más pequeños de la tierra,

[[proverbs-30-25]]
^25^ las hormigas - multitud sin fuerza -

[[proverbs-30-26]]
^26^ los damanes - multitud sin poder -,

[[proverbs-30-27]]
^27^ las langostas, que sin tener rey,

[[proverbs-30-28]]
^28^ el lagarto, al que se agarra con la mano

[[proverbs-30-29]]
^29^ Hay tres cosas de paso gallardo

[[proverbs-30-30]]
^30^ el león - fuerte entre los animales -,

[[proverbs-30-31]]
^31^ el esbelto gallo o el macho cabrío,

[[proverbs-30-32]]
^32^ Si hiciste el necio, envalentonándote,

[[proverbs-30-33]]
^33^ pues apretando la leche se saca mantequilla
[[proverbs-31]]
== Capítulo 31

[[proverbs-31-1]]
^1^ Palabras de Lemuel, rey de Massá, que le enseño su madre:

[[proverbs-31-2]]
^2^ ¡No, hijo mío, no, hijo de mis entrañas!

[[proverbs-31-3]]
^3^ No entregues tu vigor a las mujeres,

[[proverbs-31-4]]
^4^ No es para los reyes, Lemuel,

[[proverbs-31-5]]
^5^ No sea que, bebiendo, olviden sus decretos

[[proverbs-31-6]]
^6^ Dad bebidas fuertes al que va a perecer

[[proverbs-31-7]]
^7^ que beba y olvide su miseria,

[[proverbs-31-8]]
^8^ Abre tu boca en favor del mudo,

[[proverbs-31-9]]
^9^ abre tu boca, juzga con justicia

[[proverbs-31-10]]
^10^ Alef. Una mujer completa, ¿quién la encontrará?

[[proverbs-31-11]]
^11^ Bet. En ella confía el corazón de su marido,

[[proverbs-31-12]]
^12^ Guímel. Le produce el bien, no el mal,

[[proverbs-31-13]]
^13^ Dálet. Se busca lana y lino

[[proverbs-31-14]]
^14^ He. Es como nave de mercader

[[proverbs-31-15]]
^15^ Vau. Se levanta cuando aún es de noche

[[proverbs-31-16]]
^16^ Zain. Hace cálculos sobre un campo y lo compra;

[[proverbs-31-17]]
^17^ Jet. Se ciñe con fuerza sus lomos

[[proverbs-31-18]]
^18^ Tet. Siente que va bien su trabajo,

[[proverbs-31-19]]
^19^ Tod. Echa mano a la rueca,

[[proverbs-31-20]]
^20^ Kaf. Alarga su palma al desvalido,

[[proverbs-31-21]]
^21^ Lámed. No teme por su casa a la nieve,

[[proverbs-31-22]]
^22^ Mem. Para sí se hace mantos,

[[proverbs-31-23]]
^23^ Nun. Su marido es considerado en las puertas,

[[proverbs-31-24]]
^24^ Sámek. Hace túnicas de lino y las vende,

[[proverbs-31-25]]
^25^ Ain. Se viste de fuerza y dignidad,

[[proverbs-31-26]]
^26^ Pe. Abre su boca con sabiduría,

[[proverbs-31-27]]
^27^ Sade. Está atenta a la marcha de su casa,

[[proverbs-31-28]]
^28^ Qof. Se levantan sus hijos y la llaman dichosa;

[[proverbs-31-29]]
^29^ Res. «¡Muchas mujeres hicieron proezas,

[[proverbs-31-30]]
^30^ Sin. Engañosa es la gracia, vana la hermosura,

[[proverbs-31-31]]
^31^ Tau. Dadle del fruto de sus manos
