[[ecclesiastes]]
= Eclesiastés

[[ecclesiastes-1]]
== Capítulo 1

[[ecclesiastes-1-1]]
^1^ Palabras de Cohélet, hijo de David, rey en Jerusalén.

[[ecclesiastes-1-2]]
^2^ ¡Vanidad de vanidades! - dice Cohélet -, ¡vanidad de vanidades, todo vanidad!

[[ecclesiastes-1-3]]
^3^ ¿Qué saca el hombre de toda la fatiga con que se afana bajo el sol?

[[ecclesiastes-1-4]]
^4^ Una generación va, otra generación viene; pero la tierra para siempre permanece.

[[ecclesiastes-1-5]]
^5^ Sale el sol y el sol se pone; corre hacia su lugar y allí vuelve a salir.

[[ecclesiastes-1-6]]
^6^ Sopla hacia el sur el viento y gira hacia el norte; gira que te gira sigue el viento y vuelve el viento a girar.

[[ecclesiastes-1-7]]
^7^ Todos los ríos van al mar y el mar nunca se llena; al lugar donde los ríos van, allá vuelven a fluir.

[[ecclesiastes-1-8]]
^8^ Todas las cosas dan fastidio. Nadie puede decir que no se cansa el ojo de ver ni el oído de oír.

[[ecclesiastes-1-9]]
^9^ Lo que fue, eso será; lo que se hizo, ese se hará. Nada nuevo hay bajo el sol.

[[ecclesiastes-1-10]]
^10^ Si algo hay de que se diga: «Mira, eso sí que es nuevo», aun eso ya sucedía en los siglos que nos precedieron.

[[ecclesiastes-1-11]]
^11^ No hay recuerdo de los antiguos, como tampoco de los venideros quedará memoria en los que después vendrán.

[[ecclesiastes-1-12]]
^12^ Yo, Cohélet, he sido rey de Israel, en Jerusalén.

[[ecclesiastes-1-13]]
^13^ He aplicado mi corazón a investigar y explorar con la sabiduría cuanto acaece bajo el cielo. ¡Mal oficio éste que Dios encomendó a los humanos para que en él se ocuparan!

[[ecclesiastes-1-14]]
^14^ He observado cuanto sucede bajo el sol y he visto que todo es vanidad y atrapar vientos.

[[ecclesiastes-1-15]]
^15^ Lo torcido no puede enderezarse, lo que falta no se puede contar.

[[ecclesiastes-1-16]]
^16^ Me dije en mi corazón: Tengo una sabiduría grande y extensa, mayor que la de todos mis predecesores en Jerusalén; mi corazón ha contemplado mucha sabiduría y ciencia.

[[ecclesiastes-1-17]]
^17^ He aplicado mi corazón a conocer la sabiduría, y también a conocer la locura y la necedad, he comprendido que aun esto mismo es atrapar vientos,

[[ecclesiastes-1-18]]
^18^ pues: Donde abunda sabiduría, abundan penas, y quien acumula ciencia, acumula dolor.
[[ecclesiastes-2]]
== Capítulo 2

[[ecclesiastes-2-1]]
^1^ Hablé en mi corazón: ¡Adelante! ¡Voy a probarte en el placer; disfruta del bienestar! Pero vi que también esto es vanidad.

[[ecclesiastes-2-2]]
^2^ A la risa la llamé: ¡Locura!; y del placer dije: ¿Para qué vale?

[[ecclesiastes-2-3]]
^3^ Traté de regalar mi cuerpo con el vino, mientras guardaba mi corazón en la sabiduría, y entregarme a la necedad hasta ver en qué consistía la felicidad de los humanos, lo que hacen bajo el cielo durante los contados días de su vida.

[[ecclesiastes-2-4]]
^4^ Emprendí mis grandes obras; me construí palacios, me planté viñas;

[[ecclesiastes-2-5]]
^5^ me hice huertos y jardines, y los planté de toda clase de árboles frutales.

[[ecclesiastes-2-6]]
^6^ Me construí albercas con aguas para regar la frondosa plantación.

[[ecclesiastes-2-7]]
^7^ Tuve siervos y esclavas: poseí servidumbre, así como ganados, vacas y ovejas, en mayor cantidad que ninguno de mis predecesores en Jerusalén.

[[ecclesiastes-2-8]]
^8^ Atesoré también plata y oro, tributos de reyes y de provincias. Me procuré cantores y cantoras, toda clase de lujos humanos, coperos y reposteros.

[[ecclesiastes-2-9]]
^9^ Seguí engrandeciéndome más que cualquiera de mis predecesores en Jerusalén, y mi sabiduría se mantenía.

[[ecclesiastes-2-10]]
^10^ De cuanto me pedían mis ojos, nada les negué ni rehusé a mi corazón ninguna alegría; toda vez que mi corazón se solazaba de todas mis fatigas, y esto me compensaba de todas mis fatigas.

[[ecclesiastes-2-11]]
^11^ Consideré entonces todas las obras de mis manos y el fatigoso afán de mi hacer y vi que todo es vanidad y atrapar vientos, y que ningún provecho se saca bajo el sol.

[[ecclesiastes-2-12]]
^12^ Yo me volví a considerar la sabiduría, la locura y la necedad. ¿Qué hará el hombre que suceda al rey, sino lo que ya otros hicieron?

[[ecclesiastes-2-13]]
^13^ Yo vi que la sabiduría aventaja a la necedad, como la luz a las tieneblas.

[[ecclesiastes-2-14]]
^14^ El sabio tiene sus ojos abiertos, mas el necio en las tinieblas camina. Pero también yo sé que la misma suerte alcanza a ambos.

[[ecclesiastes-2-15]]
^15^ Entonces me dice: Como la suerte del necio será la mía, ¿para qué vales, pues, mi sabiduría? Y pensé que hasta eso mismo es vanidad.

[[ecclesiastes-2-16]]
^16^ No hay recuerdo duradero ni del sabio ni del necio; al correr de los días, todos son olvidados. Pues el sabio muere igual que el necio.

[[ecclesiastes-2-17]]
^17^ He detestado la vida, porque me repugna cuanto se hace bajo el sol, pues todo es vanidad y atrapar vientos.

[[ecclesiastes-2-18]]
^18^ Detesté todos mis fatigosos afanes bajo el sol, que yo dejo a mi sucesor.

[[ecclesiastes-2-19]]
^19^ ¿Quién sabe si será sabio o necio? El se hará dueño de todo mi trabajo, lo que realicé con fatiga y sabiduría bajo el sol. También esto es vanidad.

[[ecclesiastes-2-20]]
^20^ Entregué mi corazón al desaliento, por todos mis fatigosos afanes bajo el sol,

[[ecclesiastes-2-21]]
^21^ pues un hombre que se fatigá con sabiduría, ciencia y destreza, a otro que en nada se fatigó da su propia paga. También esto es vanidad y mal grave.

[[ecclesiastes-2-22]]
^22^ Pues ¿qué le queda a aquel hombre de toda su fatiga y esfuerzo con que se fatigó bajo el sol?

[[ecclesiastes-2-23]]
^23^ Pues todos sus días son dolor, y su oficio, penar; y ni aun de noche su corazón descansa. También esto es vanidad.

[[ecclesiastes-2-24]]
^24^ No hay mayor felicidad para el hombre que comer y beber, y disfrutar en medio de sus fatigas. Yo veo que también esto viene de la mano de Dios,

[[ecclesiastes-2-25]]
^25^ pues quien come y quien bebe, lo tiene de Dios.

[[ecclesiastes-2-26]]
^26^ Porque a quien le agrada, da El sabiduría, ciencia y alegría; mas al pecador, da la tarea de amontonar y atesorir para dejárselo a quien agrada a Dios. También esto es vanidad y atrapar vientos.
[[ecclesiastes-3]]
== Capítulo 3

[[ecclesiastes-3-1]]
^1^ Todo tiene su momento, y cada cosa su tiempo bajo el cielo:

[[ecclesiastes-3-2]]
^2^ Su tiempo el nacer, y su tiempo el morir; su tiempo el plantar, y su tiempo el arrancar lo plantado.

[[ecclesiastes-3-3]]
^3^ Su tiempo el matar, y su tiempo el sanar; su tiempo el destruir, y su tiempo el edificar.

[[ecclesiastes-3-4]]
^4^ Su tiempo el llorar, y su tiempo el reír; su tiempo el lamentarse, y su tiempo el danzar.

[[ecclesiastes-3-5]]
^5^ Su tiempo el lanzar piedras, y su tiempo el recogerlas; su tiempo el abrazarse, y su tiempo el separarse.

[[ecclesiastes-3-6]]
^6^ Su tiempo el buscar, y su tiempo el perder; su tiempo el guardar, y su tiempo el tirar.

[[ecclesiastes-3-7]]
^7^ Su tiempo el rasgar, y su tiempo el coser; su tiempo el callar, y su tiempo el hablar.

[[ecclesiastes-3-8]]
^8^ Su tiempo el amar, y su tiempo el odiar; su tiempo la guerra, y su tiempo la paz.

[[ecclesiastes-3-9]]
^9^ ¿Qué gana el que trabaja con fatiga?

[[ecclesiastes-3-10]]
^10^ He considerado la tarea que Dios ha puesto a los humanos para que en ella se ocupen.

[[ecclesiastes-3-11]]
^11^ El ha hecho todas las cosas apropiadas a su tiempo; también ha puesto el mundo en sus corazones, sin que el hombre llegue a descubrir la obra que Dios ha hecho de principio a fin.

[[ecclesiastes-3-12]]
^12^ Comprendo que no hay para el hombre más felicidad que alegrarse y buscar el bienestar en su vida.

[[ecclesiastes-3-13]]
^13^ Y que todo hombre coma y beba y disfrute bien en medio de sus fatigas, eso es don de Dios.

[[ecclesiastes-3-14]]
^14^ Comprendo que cuanto Dios hace es duradero. Nada hay que añadir ni nada que quitar. Y así hace Dios que se le tema.

[[ecclesiastes-3-15]]
^15^ Lo que es, ya antes fue; lo que será, ya es. Y Dios restaura lo pasado.

[[ecclesiastes-3-16]]
^16^ Todavía más he visto bajo el sol: en la sede del derecho, allí está la iniquidad; y en el sitial del justo, allí el impío.

[[ecclesiastes-3-17]]
^17^ Dije en mi corazón: Dios juzgará al justo y al impío, pues allí hay un tiempo para cada cosa y para toda obra.

[[ecclesiastes-3-18]]
^18^ Dije también en mi corazón acerca de la conducta de los humanos: sucede así para que Dios los pruebe y les demuestre que son como bestias.

[[ecclesiastes-3-19]]
^19^ Porque el hombre y la bestia tienen la misma suerte: muere el uno como la otra; y ambos tienen el mismo aliento de vida. En nada aventaja el hombre a la bestia, pues todo es vanidad.

[[ecclesiastes-3-20]]
^20^ Todos caminan hacia una misma meta; todos han salido del polvo y todos vuelven al polvo.

[[ecclesiastes-3-21]]
^21^ ¿Quién sabe si el aliento de vida de los humanos asciende hacia arriba y si el aliento de vida de la bestia desciende hacia abajo, a la tierra?

[[ecclesiastes-3-22]]
^22^ Veo que no hay para el hombre nada mejor que gozarse en sus obras, pues esa es su paga. Pero ¿quién le guiará a contemplar lo que ha de suceder después de él?
[[ecclesiastes-4]]
== Capítulo 4

[[ecclesiastes-4-1]]
^1^ Yo me volví a considerar todas las violencias perpetradas bajo el sol: vi el llanto de los oprimidos, sin tener quien los consuele; la violencia de sus verdugos, sin tener quien los vengue.

[[ecclesiastes-4-2]]
^2^ Felicité a los muertos que ya perecieron, más que a los vivos que aún viven.

[[ecclesiastes-4-3]]
^3^ Más feliz aún que entrambos es aquel que aún no ha existido, que no ha visto la iniquidad que se comete bajo el sol.

[[ecclesiastes-4-4]]
^4^ He visto que todo afán y todo éxito en una obra excita la envidia del uno contra el otro. También esto es vanidad y atrapar vientos.

[[ecclesiastes-4-5]]
^5^ El necio se cruza de manos, y devora su carne.

[[ecclesiastes-4-6]]
^6^ Más vale llenar un puñado con reposo que dos puñados con fatiga en atrapar vientos.

[[ecclesiastes-4-7]]
^7^ Volví de nuevo a considerar otra vanidad bajo el sol:

[[ecclesiastes-4-8]]
^8^ a saber, un hombre solo, sin sucesor, sin hijos ni hermano; sin límite a su fatiga, sin que sus ojos se harten de riqueza. «Mas ¿para quién me fatigo y privo a mi vida de felicidad?» También esto es vanidad y mal negocio.

[[ecclesiastes-4-9]]
^9^ Más valen dos que uno solo, pues obtienen mayor ganancia de su esfuerzo.

[[ecclesiastes-4-10]]
^10^ Pues si cayeren, el uno levantará a su compañero; pero ¡ay del solo que cae!, que no tiene quien lo levante.

[[ecclesiastes-4-11]]
^11^ Si dos se acuestan, tienen calor; pero el solo ¿cómo se calentará?

[[ecclesiastes-4-12]]
^12^ Si atacan a uno, los dos harán frente. La cuerda de tres hilos no es fácil de romper.

[[ecclesiastes-4-13]]
^13^ Más vale mozo pobre y sabio que rey viejo y necio, que no sabe ya consultar.

[[ecclesiastes-4-14]]
^14^ Pues de prisión salió quien llegó a reinar, aunque pobre en sus dominios naciera.

[[ecclesiastes-4-15]]
^15^ Veo a todos los vivientes que caminan bajo el sol, ponerse junto al mozo, el sucesor, el que ocupará su puesto.

[[ecclesiastes-4-16]]
^16^ Era sin fin la multitud a cuyo frente estaba; tampoco la posteridad se contentará de él. También esto es vanidad y atraper vientos.

[[ecclesiastes-4-17]]
^17^ Guarda tus pasos cuando vas a la Casa de Dios. Acercarse obediente vale más que el sacrificio de los necios, porque ellos no saben que hacen el mal.
[[ecclesiastes-5]]
== Capítulo 5

[[ecclesiastes-5-1]]
^1^ No te precipites a hablar, ni tu corazón se apresure a pronunciar una palabra ante Dios. Pues Dios está en el cielo, pero tú en la tierra: sean por tanto pocas tus palabras.

[[ecclesiastes-5-2]]
^2^ Porque, los sueños vienen de las muchas tareas. la voz necia, de las muchas palabras.

[[ecclesiastes-5-3]]
^3^ Si haces voto a Dios, no tardes en cumplirlo; pues no le agradan los necios. El voto que has hecho, cúmplelo.

[[ecclesiastes-5-4]]
^4^ Es mejor no hacer votos que hacerlos y no cumplirlos.

[[ecclesiastes-5-5]]
^5^ No permitas que tu boca haga de ti un pecador, y luego digas ante el Mensajero que fue inadvertencia. ¿Por qué deberá Dios irritarse por tu palabra y destruir la obra de tus manos?

[[ecclesiastes-5-6]]
^6^ Cuantos los sueños, tantas las vanidades y las muchas palabras. Pero tú teme a Dios.

[[ecclesiastes-5-7]]
^7^ Si en la región ves la opresión del pobre y la violación del derecho y de la justicia, no te asombres por eso. Se te dirá que una dignidad vigila sobre otra dignidad, y otra más dignas sobre ambas.

[[ecclesiastes-5-8]]
^8^ Se invocará el interés común y el servicio del rey.

[[ecclesiastes-5-9]]
^9^ Quien ama el dinero, no se harta de él, y para quien ama riquezas, no bastas ganancias. También esto es vanidad.

[[ecclesiastes-5-10]]
^10^ A muchos bienes, muchos que los devoren; y ¿de qué más sirven a su dueño que de espectáculo para sus ojos?

[[ecclesiastes-5-11]]
^11^ Dulce el sueño del obrero, coma poco o coma mucho; pero al rico la hartura no le deja dormir.

[[ecclesiastes-5-12]]
^12^ Hay un grave mal que yo he visto bajo el sol: riqueza guardada para su dueño, y que solo sirve para su mal,

[[ecclesiastes-5-13]]
^13^ pues las riquezas perecen en un mal negocio, y cuando engendra un hijo, nada queda ya en su mano.

[[ecclesiastes-5-14]]
^14^ Como salió del vientre de su madre, desnudo volverá, como ha venido; y nada podrá sacar de sus fatigas que pueda llevar en la mano.

[[ecclesiastes-5-15]]
^15^ También esto es grave mal: que tal como vino, se vaya; y ¿de qué le vale el fatigarse para el viento?

[[ecclesiastes-5-16]]
^16^ Todos los días pasa en oscuridad, pena, fastidio, enfermedad y rabia.

[[ecclesiastes-5-17]]
^17^ Esto he experimentado: lo mejor para el hombre es comer, beber y disfrutar en todos sus fatigosos afanes bajo el sol, en los contados días de la vida que Dios le da; porque esta es su paga.

[[ecclesiastes-5-18]]
^18^ Y además: cuando a cualquier hombre Dios da riquezas y tesoros, le deja disfrutar de ellos, tomar su paga y holgarse en medio de sus fatigas, esto es un don de Dios.

[[ecclesiastes-5-19]]
^19^ Porque así no recuerda mucho los días de su vida, mientras Dios le llena de alegría el corazón.
[[ecclesiastes-6]]
== Capítulo 6

[[ecclesiastes-6-1]]
^1^ Hay otro mal que observo bajo el sol, y que pesa sobre el hombre:

[[ecclesiastes-6-2]]
^2^ Un hombre a quien Dios da riquezas, tesoros y honores; nada le falta de lo que desea, pero Dios no le deja disfrutar de ello, porque un extraño lo disfruta. Esto es vanidad y gran desgracia.

[[ecclesiastes-6-3]]
^3^ Si alguno que tiene cien hijos y vive muchos años, y por muchos que sean sus años, no se sacia su alma de felicidad y ni siquiera halla sepultura, entonces yo digo: Más feliz es un aborto,

[[ecclesiastes-6-4]]
^4^ pues, entre vanidades vino y en la oscuridad se va; mientras su nombre queda oculto en las tinieblas.

[[ecclesiastes-6-5]]
^5^ No ha visto el sol, no lo ha conocido, y ha tenido más descanso que el otro.

[[ecclesiastes-6-6]]
^6^ Y aunque hubiera vivido por dos veces mil años, pero sin gustar la felicidad, ¿no caminan acaso todos al mismo lugar?

[[ecclesiastes-6-7]]
^7^ Todo el mundo se fatiga para comer, y a pesar de todo nunca se harta.

[[ecclesiastes-6-8]]
^8^ ¿En qué supera el sabio al necio? ¿En qué, al pobre que sabe vivir su vida?

[[ecclesiastes-6-9]]
^9^ Mejor es lo que los ojos ven que lo que el alma desea. También esto es vanidad y atrapar vientos.

[[ecclesiastes-6-10]]
^10^ De lo que existe, ya se anunció su nombre, y se sabe lo que es un hombre: no puede litigar con quien es más fuerte que él.

[[ecclesiastes-6-11]]
^11^ A más palabras, más vanidades. ¿Qué provecho saca el hombre?

[[ecclesiastes-6-12]]
^12^ Porque, ¿quién sabe lo que conviene al hombre en su vida, durante los días contados de su vano vivir, que él los vive como una sombra? Pues ¿quién indicará al hombre lo que sucederá después de él bajo el sol?
[[ecclesiastes-7]]
== Capítulo 7

[[ecclesiastes-7-1]]
^1^ Más vale el renombre que óleo perfumado; y el día de la muerte más que el día del nacimiento.

[[ecclesiastes-7-2]]
^2^ Más vale ir a casa de luto que ir a casa de festín; porque allí termina todo hombre, y allí el que vive, reflexiona.

[[ecclesiastes-7-3]]
^3^ Más vale llorar que reír, pues tras una cara triste hay un corazón feliz.

[[ecclesiastes-7-4]]
^4^ El corazón de los sabios está en la casa de luto, mientras el corazón de los necios en la casa de alegría.

[[ecclesiastes-7-5]]
^5^ Más vale oír reproche de sabio, que oír alabanza de necios.

[[ecclesiastes-7-6]]
^6^ Porque como crepitar de zarzas bajo la olla, así es el reír del necio: y también esto es vanidad.

[[ecclesiastes-7-7]]
^7^ El halago atonta al sabio, y el regalo pervierte el corazón.

[[ecclesiastes-7-8]]
^8^ Más vale el término de una cosa que su comienzo, más vale el paciente que el soberbio.

[[ecclesiastes-7-9]]
^9^ No te dejes llevar del enojo, pues el enojo reside en el pecho de los necios.

[[ecclesiastes-7-10]]
^10^ No digas: ¿Cómo es que el tiempo pasado fue mejor que el presente? Pues no es de sabios preguntar sobre ello.

[[ecclesiastes-7-11]]
^11^ Tan buena es la sabiduría como la hacienda, y aprovecha a los que ven el sol.

[[ecclesiastes-7-12]]
^12^ Porque la sabiduría protege como el dinero, pero el saber le aventaja en que hace vivir al que lo posee.

[[ecclesiastes-7-13]]
^13^ Mira la obra de Dios: ¿quién podrá enderezar lo que él torció?

[[ecclesiastes-7-14]]
^14^ Alégrate en el día feliz y, en el día desgraciado, considera que, tanto uno como otro, Dios lo hace para que el hombre nada descubra de su porvenir.

[[ecclesiastes-7-15]]
^15^ En mi vano vivir, de todo he visto: justos perecer en su justicia, e impíos envejecer en su iniquidad.

[[ecclesiastes-7-16]]
^16^ No quieras ser justo en demasía, ni te vuelvas demasiado sabio. ¿A qué destruirte?

[[ecclesiastes-7-17]]
^17^ No quieras ser demasiado impío, ni te hagas el insensato. ¿A qué morir antes de tu tiempo?

[[ecclesiastes-7-18]]
^18^ Bueno es que mantengas esto sin dejar aquellos de la mano, porque el temeroso de Dios con todo ello se sale.

[[ecclesiastes-7-19]]
^19^ La sabiduría da más fuerza al sabio que diez poderosos que haya en la ciudad.

[[ecclesiastes-7-20]]
^20^ Cierto es que no hay ningún justo en la tierra que haga el bien sin nunca pecar.

[[ecclesiastes-7-21]]
^21^ Tampoco hagas caso de todo lo que se dice, para que no oigas que tu siervo te denigra.

[[ecclesiastes-7-22]]
^22^ Que tu corazón bien sabe cuántas veces también tú has denigrado a otros.

[[ecclesiastes-7-23]]
^23^ Todo esto lo intenté con la sabiduría. Dije: Seré sabio. Pero eso estaba lejos de mí.

[[ecclesiastes-7-24]]
^24^ Lejos está cualquier cosa, y profundo, lo profundo: ¿quién lo encontrará?

[[ecclesiastes-7-25]]
^25^ He aplicado mi corazón a explorar y a buscar sabiduría y razón, a reconocer la maldad como una necedad, y la necedad como una locura.

[[ecclesiastes-7-26]]
^26^ He hallado que la mujer es más amarga que la muerte, porque ella es como una red, su corazón como un lazo, y sus brazos como cadenas: El que agrada a Dios se libra de ella, mas el pecador cae en su trampa.

[[ecclesiastes-7-27]]
^27^ Mira, esto he hallado, dice Cohélet, tratando de razonar, caso por caso.

[[ecclesiastes-7-28]]
^28^ Aunque he seguido buscando, nada más he hallado. Un hombre entre mil, sí que lo hallo; pero mujer entre todas ellas, no la encuentro.

[[ecclesiastes-7-29]]
^29^ Mira, lo que hallé fue sólo esto: Dios hizo sencillo al hombre, pero él se complicó con muchas razones.
[[ecclesiastes-8]]
== Capítulo 8

[[ecclesiastes-8-1]]
^1^ ¿Quién como el sabio? ¿Quién otro sabe explicar una cosa? La sabiduría del hombre hace brillar su rostro, y sus facciones severas transfigura.

[[ecclesiastes-8-2]]
^2^ Aténte al dictado del rey, y por causa del juramento divino

[[ecclesiastes-8-3]]
^3^ no te apresures a irte de su presencia; no te mezcles en conspiración, pues todo cuanto le plazca puede hacerlo,

[[ecclesiastes-8-4]]
^4^ ya que la palabra regia es soberana, y ¿quién va a decirle: Qué haces?

[[ecclesiastes-8-5]]
^5^ Quien se atiene al mandamiento, no sabe de conspiraciones. Y el corazón del sabio sabe el cuándo y el cómo.

[[ecclesiastes-8-6]]
^6^ Porque todo asunto tiene su cuándo y su cómo. Pues es grande el peligro que acecha al hombre,

[[ecclesiastes-8-7]]
^7^ ya que éste ignora lo que está por venir, pues lo que está por venir, ¿quién va a anunciárselo?

[[ecclesiastes-8-8]]
^8^ No es el hombre señor del viento para domeñar al viento. Tampoco hay señorío sobre el día de la muerte, ni hay evasión en la agonía, ni libra la maldad a sus autores.

[[ecclesiastes-8-9]]
^9^ Todo esto tengo visto al aplicar mi corazón a cuanto pasa bajo el sol, cuando el hombre domina en el hombre para causarle el mal.

[[ecclesiastes-8-10]]
^10^ Por ejemplo, he visto a gente mala llevada a la tumba. Partieron del Lugar Santo, y se dio al olvido en la ciudad que hubiesen obrado de aquel modo. ¡Otro absurdo!:

[[ecclesiastes-8-11]]
^11^ que no se ejecute en seguida la sentencia de la conducta del malo, con lo que el corazón de los humanos se llena de ganas de hacer el mal;

[[ecclesiastes-8-12]]
^12^ que el pecador haga el mal veces ciento, y se le den largas. Pues yo tenía entendido que les va bien a los temerosos de Dios, a aquellos que ante su rostro temen,

[[ecclesiastes-8-13]]
^13^ y que no le va bien al malvado, ni alargará sus días como sombra el que no teme ante el rostro de Dios.

[[ecclesiastes-8-14]]
^14^ Pues bien, un absurdo se da en la tierra: Hay justos a quienes les sucede cual corresponde a las obras de los malos, y malos a quienes sucede cual corresponde a las obras de los buenos. Digo que este es otro absurdo.

[[ecclesiastes-8-15]]
^15^ Y yo por mí alabo la alegría, ya que otra coasa buena no existe para el hombre bajo el sol, si no es comer, beber y divertirse; y eso es lo que le acompaña en sus fatigas en los días de vida que Dios le hubiera dado bajo el sol.

[[ecclesiastes-8-16]]
^16^ Cuanto más apliqué mi corazón a estudiar la sabiduría y a contemplar el ajetreo que se da sobre la tierra - pues ni de día ni de noche concilian los ojos el sueño -

[[ecclesiastes-8-17]]
^17^ fui viendo que el ser humano no puede descubrir todas las obras de Dios, las obras que se realizan bajo el sol. Por más que se afane el hombre en buscar, nada descubre, y el mismo sabio, aunque diga saberlo, no es capaz de descubrirlo.
[[ecclesiastes-9]]
== Capítulo 9

[[ecclesiastes-9-1]]
^1^ Pues bien, a todo eso he aplicado mi corazón y todo lo he explorado, y he visto que los justos y los sabios y sus obras están en manos de Dios. Y ni de amor ni de odio saben los hombres nada: todo les resulta

[[ecclesiastes-9-2]]
^2^ absurdo. Como el que haya un destino común para todos, para el justo y para el malvado, el puro y el manchado, el que hace sacrificios y el que no los hace, así el bueno como el pecador, el que jura como el que se recata de jurar.

[[ecclesiastes-9-3]]
^3^ Eso es lo peor de todo cuanto pasa bajo el sol: que haya un destino común para todos, y así el corazón de los humanos está lleno de maldad y hay locura en sus corazones mientras viven, y su final ¡con los muertos!

[[ecclesiastes-9-4]]
^4^ Pues mientras uno sigue unido a todos los vivientes hay algo seguro, pues vale más perro vivo que león muerto.

[[ecclesiastes-9-5]]
^5^ Porque los vivos saben que han de morir, pero los muertos no saben nada, y no hay ya paga para ellos, pues se perdió su memoria.

[[ecclesiastes-9-6]]
^6^ Tanto su amor, como su odio, como sus celos, ha tiempo que pereció, y no tomarán parte nunca jamás en todo lo que pasa bajo el sol.

[[ecclesiastes-9-7]]
^7^ Anda, come con alegría tu pan y bebe de buen grado tu vino, que Dios está ya contento con tus obras.

[[ecclesiastes-9-8]]
^8^ En toda sazón sean tus ropas blancas y no falte ungüento sobre tu cabeza.

[[ecclesiastes-9-9]]
^9^ Vive la vida con la mujer que amas, todo el espacio de tu vana existencia que se te ha dado bajo el sol, ya que tal es tu parte en la vida y en las fatigas con que te afanas bajo el sol.

[[ecclesiastes-9-10]]
^10^ Cualquier cosa que esté a tu alcance el hacerla, hazla según tus fuerzas, porque no existirá obra ni razones ni ciencia ni sabiduría en el seol a donde te encaminas.

[[ecclesiastes-9-11]]
^11^ Vi además que bajo el sol no siempre es de los ligeros el correr ni de los esforzados la pelea; como también hay sabios sin pan, como también discretos sin hacienda, como también hay doctos que no gustan, pues a todos les llega algún mal momento.

[[ecclesiastes-9-12]]
^12^ Porque, además, el hombre ignora su momento: como peces apresados en la red, como pájaros presos en el cepo, así son tratados los humanos por el infortunio cuando les cae encima de improviso.

[[ecclesiastes-9-13]]
^13^ También he visto otro acierto bajo el sol, y grande, a juicio mío:

[[ecclesiastes-9-14]]
^14^ Una ciudad chiquita, con pocos hombres en ella. Llega un gran rey y le pone cerco, levantando frente a ella empalizadas potentes.

[[ecclesiastes-9-15]]
^15^ Encontrábase allí un hombre pobre y sabio. El pudo haber librado la ciudad gracias a su sabiduría, ¡pero nadie paró mientes en aquel pobre!

[[ecclesiastes-9-16]]
^16^ Y yo me digo: Más vale sabiduría que fuerza; pero la sabiduría del pobre se desprecia y sus palabras no se escuchan.

[[ecclesiastes-9-17]]
^17^ Mejor se oyen las palabras sosegadas de los sabios que los gritos del soberano de los necios.

[[ecclesiastes-9-18]]
^18^ Más vale sabiduría que armas de combate, pero un solo yerro echa a perder mucho bueno.
[[ecclesiastes-10]]
== Capítulo 10

[[ecclesiastes-10-1]]
^1^ Una mosca muerta pudre una copa de ungüento de perfumista; monta más un poco de necedad que sabiduría y honor.

[[ecclesiastes-10-2]]
^2^ El sabio tiene el corazón a la derecha, el necio tiene el corazón a la izquierda.

[[ecclesiastes-10-3]]
^3^ Además, en cualquier camino que tome el necio, su entendimiento no le da de sí y dice de todo el mundo: «Ese es un necio».

[[ecclesiastes-10-4]]
^4^ Si el enojo del que manda se abate sobre ti, no abandones tu puesto, que la flema libra de graves yerros.

[[ecclesiastes-10-5]]
^5^ Otra calamidad he visto bajo el sol, como error que emana de la autoridad:

[[ecclesiastes-10-6]]
^6^ La necedad elevada a grandes dignidades, mientras ricos se sentaban abajo.

[[ecclesiastes-10-7]]
^7^ He visto siervos a caballo, y príncipes que iban a pie, como los siervos.

[[ecclesiastes-10-8]]
^8^ El que cava la hoya cae en ella, y al que atraviesa el seto le muerde la culebra.

[[ecclesiastes-10-9]]
^9^ El que saca piedras se lastima con ellas, el que raja maderos puede hacerse daño.

[[ecclesiastes-10-10]]
^10^ Si se embota el hierro y no se afilan sus caras, hay que acrecentar los bríos: también supone ganancia afinar en sabiduría.

[[ecclesiastes-10-11]]
^11^ Si pica culebra por falta de encatamiento no hay ganancia para el encantador.

[[ecclesiastes-10-12]]
^12^ Palabras de boca de sabio agradan, mas los labios del necio a él lo engullen.

[[ecclesiastes-10-13]]
^13^ Empieza diciendo necedades, para acabar en locura de las malas.

[[ecclesiastes-10-14]]
^14^ Y el necio dice más y más palabras. Nadie sabe lo que vas venir, y el remate de todo, ¿quién puede pronosticárselo?

[[ecclesiastes-10-15]]
^15^ Lo que más molesta al necio es que no sabe ir a la ciudad.

[[ecclesiastes-10-16]]
^16^ ¡Ay de ti, tierra, cuyo rey es un chiquillo, y cuyos príncipes comen de mañana!

[[ecclesiastes-10-17]]
^17^ ¡Dichosa tú, tierra, cuyo rey es hidalgo y cuyos príncipes comen a la hora, por cobrar vigor y no por banquetear!

[[ecclesiastes-10-18]]
^18^ Por estar mano sobre mano se desploma la viga, y por brazos caídos la casa se viene abajo.

[[ecclesiastes-10-19]]
^19^ Para holgar preparan su banquete, y el vino alegra la vida, y el dinero todo lo allana.

[[ecclesiastes-10-20]]
^20^ Ni aun en tu rincón faltes al rey, ni en tu misma alcoba faltes al rico, que un pájaro del cielo hace correr la voz, y un ser alado va a contar la cosa.
[[ecclesiastes-11]]
== Capítulo 11

[[ecclesiastes-11-1]]
^1^ Echa tu pan al agua, que al cabo de mucho tiempo lo encontrarás.

[[ecclesiastes-11-2]]
^2^ Reparte con siete, y también con ocho, que no sabes qué mal puede venir sobre la tierra.

[[ecclesiastes-11-3]]
^3^ Si las nubes van llenas, vierten lluvia sobre la tierra, y caiga el árbol al sur o al norte, donde cae el árbol allí se queda.

[[ecclesiastes-11-4]]
^4^ El que vigila el viento no siembra, el que mira a las nubes no siega.

[[ecclesiastes-11-5]]
^5^ Como no sabes cómo viene el espíritu a los huesos en el vientre de la mujer encinta, así tampoco sabes la obra de Dios que todo lo hace.

[[ecclesiastes-11-6]]
^6^ De madrugada siembra tu simiente y a la tarde no des paz a tu mano. Pues no sabes si es menor esto o lo otro o si ambas cosas son igual de buenas.

[[ecclesiastes-11-7]]
^7^ Dulce es la luz y bueno para los ojos ver el sol.

[[ecclesiastes-11-8]]
^8^ Si uno vive muchos años, que se alegre en todos ellos, y tenga en cuenta que los días de tinieblas muchos serán, que es vanidad todo el porvenir.

[[ecclesiastes-11-9]]
^9^ Alégrate, mozo, en tu juventud, ten buen humor en tus años mozos, Vete por donde te lleve el corazón y a gusto de tus ojos; pero a sabiendas de que por todo ello te emplazará Dios a juicio.

[[ecclesiastes-11-10]]
^10^ Aparta el mal humor de tu pecho y aleja el sufrimiento de tu carne, pero juventud y pelo negro, vanidad.
[[ecclesiastes-12]]
== Capítulo 12

[[ecclesiastes-12-1]]
^1^ Acuérdate de tu Creador en tus días mozos, mientras no vengan los días malos, y se echen encima años en que dirás: «No me agradan»;

[[ecclesiastes-12-2]]
^2^ mientras no se nublen el sol y la luz, la luna y las estrellas, y retornen las nubles tras la lluvia;

[[ecclesiastes-12-3]]
^3^ cuando tiemblen los guardas de palacio y se doblen los guerreros, se paren las moledoras, por quedar pocas, se queden a oscuras las que miran por las ventanas,

[[ecclesiastes-12-4]]
^4^ y se cierren las puertas de la calle, ahogándose el son del molino; cundo uno se levante al canto del pájaro, y se enmudezcan todas las canciones.

[[ecclesiastes-12-5]]
^5^ También la altura da recelo, y hay sustos en el camino, florece el almendro, está grávida la langosta, y pierde su sabor la alcaparra; y es que el hombre se va a su eterna morada, y circulan por la calle los del duelo;

[[ecclesiastes-12-6]]
^6^ mientras no se quiebre la hebra de plata, se rompa la bolita de oro, se haga añicos el cántaro contra la fuente, se caiga la polea dentro del pozo,

[[ecclesiastes-12-7]]
^7^ vuelva el polvo a la tierra, a lo que era, y el espíritu vuelva a Dios que es quien lo dio.

[[ecclesiastes-12-8]]
^8^ ¡Vanidad de vanidades! - dice Cohélet -: ¡todo vanidad!

[[ecclesiastes-12-9]]
^9^ Cohélet, a más de ser un sabio, enseñó doctrina al pueblo. Ponderó e investigó, compuso muchos proberbios.

[[ecclesiastes-12-10]]
^10^ Cohélet trabajó mucho en inventar frases felices, y escribir bien sentencias verídicas.

[[ecclesiastes-12-11]]
^11^ Las palabras de los sabios son como aguijadas, o como estacas hincadas, puertas por un pastor para controlar el rebaño.

[[ecclesiastes-12-12]]
^12^ Lo que de ellas se saca, hijo mío, es ilustrarse. Componer muchos libros es nunca acabar, y estudiar demasiado daña la salud.

[[ecclesiastes-12-13]]
^13^ Basta de palabras. Todo está dicho. Teme a Dios y guarda sus mandamientos, que eso es ser hombre cabal.

[[ecclesiastes-12-14]]
^14^ Porque toda obra la emplazará Dios a juicio, también todo lo oculto, a ver si es bueno o malo.
