[[song-of-songs]]
= Cantar de los Cantares

[[song-of-songs-1]]
== Capítulo 1

[[song-of-songs-1-1]]
^1^ Cantar de los cantares, de Salomón.

[[song-of-songs-1-2]]
^2^ ¡Que me bese con los besos de su boca!

[[song-of-songs-1-3]]
^3^ mejores al olfato tus perfumes;

[[song-of-songs-1-4]]
^4^ Llévame en pos de ti: ¡Corramos!

[[song-of-songs-1-5]]
^5^ Negra soy, pero graciosa, hijas de Jerusalén,

[[song-of-songs-1-6]]
^6^ No os fijéis en que estoy morena:

[[song-of-songs-1-7]]
^7^ Indícame, amor de mi alma,

[[song-of-songs-1-8]]
^8^ Si no lo sabes, ¡oh la más bella de las mujeres!,

[[song-of-songs-1-9]]
^9^ A mi yegua, entre los carros de Faraón,

[[song-of-songs-1-10]]
^10^ Graciosas son tus mejillas entre los zarcillos,

[[song-of-songs-1-11]]
^11^ Zarcillos de oro haremos para ti,

[[song-of-songs-1-12]]
^12^ - Mientras el rey se halla en su diván,

[[song-of-songs-1-13]]
^13^ Bolsita de mirra es mi amado para mí,

[[song-of-songs-1-14]]
^14^ Racimo de alheña es mi amado para mí,

[[song-of-songs-1-15]]
^15^ - ¡Qué bella eres, amada mía,

[[song-of-songs-1-16]]
^16^ - ¡Qué hermoso eres, amado mío,

[[song-of-songs-1-17]]
^17^ - Las vigas de nuestra casa son de cedro,
[[song-of-songs-2]]
== Capítulo 2

[[song-of-songs-2-1]]
^1^ - Yo soy el narciso de Sarón,

[[song-of-songs-2-2]]
^2^ - Como el lirio entre los cardos,

[[song-of-songs-2-3]]
^3^ - Como el manzano entre los árboles silvestres,

[[song-of-songs-2-4]]
^4^ Me ha llevado a la bodega,

[[song-of-songs-2-5]]
^5^ Confortadme con pasteles de pasas,

[[song-of-songs-2-6]]
^6^ Su izquierda está bajo mi cabeza,

[[song-of-songs-2-7]]
^7^ - Yo os conjuro,

[[song-of-songs-2-8]]
^8^ ¡La voz de mi amado!

[[song-of-songs-2-9]]
^9^ Semejante es mi amado a una gacela,

[[song-of-songs-2-10]]
^10^ Empieza a hablar mi amado,

[[song-of-songs-2-11]]
^11^ Porque, mira, ha pasado ya el invierno,

[[song-of-songs-2-12]]
^12^ Aparecen las flores en la tierra,

[[song-of-songs-2-13]]
^13^ Echa la higuera sus yemas,

[[song-of-songs-2-14]]
^14^ Paloma mía, en las grietas de la roca,

[[song-of-songs-2-15]]
^15^ Cazadnos las raposas,

[[song-of-songs-2-16]]
^16^ Mi amado es para mí, y yo soy para mi amado:

[[song-of-songs-2-17]]
^17^ Antes que sople la brisa del día
[[song-of-songs-3]]
== Capítulo 3

[[song-of-songs-3-1]]
^1^ En mi lecho, por las noches, he buscado

[[song-of-songs-3-2]]
^2^ Me levantaré, pues, y recorreré la ciudad.

[[song-of-songs-3-3]]
^3^ Los centinelas me encontraron,

[[song-of-songs-3-4]]
^4^ Apenas habíalos pasado,

[[song-of-songs-3-5]]
^5^ Yo os conjuro,

[[song-of-songs-3-6]]
^6^ ¿Qué es eso que sube del desierto,

[[song-of-songs-3-7]]
^7^ Ved la litera de Salomón.

[[song-of-songs-3-8]]
^8^ todos diestros en la espada,

[[song-of-songs-3-9]]
^9^ El rey Salomón

[[song-of-songs-3-10]]
^10^ Ha hecho de plata sus columnas,

[[song-of-songs-3-11]]
^11^ Salid a contemplar,
[[song-of-songs-4]]
== Capítulo 4

[[song-of-songs-4-1]]
^1^ ¡Qué bella eres, amada mía,

[[song-of-songs-4-2]]
^2^ Tus dientes, un rebaño de ovejas de esquileo

[[song-of-songs-4-3]]
^3^ Tus labios, una cinta de escarlata,

[[song-of-songs-4-4]]
^4^ Tu cuello, la torre de David,

[[song-of-songs-4-5]]
^5^ Tus dos pechos, cual dos crías

[[song-of-songs-4-6]]
^6^ Antes que sople la brisa del día,

[[song-of-songs-4-7]]
^7^ ¡Toda hermosa eres, amada mía,

[[song-of-songs-4-8]]
^8^ Ven del Líbano, novia mía,

[[song-of-songs-4-9]]
^9^ Me robaste el corazón,

[[song-of-songs-4-10]]
^10^ ¡Qué hermosos tus amores,

[[song-of-songs-4-11]]
^11^ Miel virgen destilan

[[song-of-songs-4-12]]
^12^ Huerto eres cerrado,

[[song-of-songs-4-13]]
^13^ Tus brotes, un paraíso de granados,

[[song-of-songs-4-14]]
^14^ nardo y azafrán,

[[song-of-songs-4-15]]
^15^ ¡Fuente de los huertos,

[[song-of-songs-4-16]]
^16^ ¡Levántate, cierzo,
[[song-of-songs-5]]
== Capítulo 5

[[song-of-songs-5-1]]
^1^ Ya he entrado en mi huerto,

[[song-of-songs-5-2]]
^2^ Yo dormía, pero mi corazón velaba.

[[song-of-songs-5-3]]
^3^ - «Me he quitado mi túnica,

[[song-of-songs-5-4]]
^4^ ¡Mi amado metió la mano

[[song-of-songs-5-5]]
^5^ Me levanté

[[song-of-songs-5-6]]
^6^ Abrí a mi amado,

[[song-of-songs-5-7]]
^7^ Me encontraron los centinelas,

[[song-of-songs-5-8]]
^8^ Yo os conjuro,

[[song-of-songs-5-9]]
^9^ ¿Qué distingue a tu amado de los otros,

[[song-of-songs-5-10]]
^10^ Mi amado es fúlgido y rubio,

[[song-of-songs-5-11]]
^11^ Su cabeza es oro, oro puro;

[[song-of-songs-5-12]]
^12^ Sus ojos como palomas

[[song-of-songs-5-13]]
^13^ Sus mejillas, eras de balsameras,

[[song-of-songs-5-14]]
^14^ Sus manos, aros de oro,

[[song-of-songs-5-15]]
^15^ Sus piernas, columnas de alabastro,

[[song-of-songs-5-16]]
^16^ Su paladar, dulcísimo, y todo él, un encanto.
[[song-of-songs-6]]
== Capítulo 6

[[song-of-songs-6-1]]
^1^ ¿A dónde se fue tu amado,

[[song-of-songs-6-2]]
^2^ Mi amado ha bajado a su huerto,

[[song-of-songs-6-3]]
^3^ Yo soy para mi amado y mi amado es para mí:

[[song-of-songs-6-4]]
^4^ Hermosa eres, amiga mía, como Tirsá,

[[song-of-songs-6-5]]
^5^ Retira de mí tus ojos,

[[song-of-songs-6-6]]
^6^ Tus dientes, un rebaño de ovejas,

[[song-of-songs-6-7]]
^7^ Tus mejillas, como cortes de granada

[[song-of-songs-6-8]]
^8^ Sesenta son las reinas,

[[song-of-songs-6-9]]
^9^ Unica es mi paloma,

[[song-of-songs-6-10]]
^10^ «¿Quién es ésta que surge cual la aurora,

[[song-of-songs-6-11]]
^11^ Al nogueral había yo bajado

[[song-of-songs-6-12]]
^12^ ¡Sin saberlo, mi deseo me puso
[[song-of-songs-7]]
== Capítulo 7

[[song-of-songs-7-1]]
^1^ ¡Vuelve, vuelve, Sulamita,

[[song-of-songs-7-2]]
^2^ ¡Qué lindos son tus pies en las sandalias,

[[song-of-songs-7-3]]
^3^ Tu ombligo es un ánfora redonda,

[[song-of-songs-7-4]]
^4^ Tus dos pechos, cual dos crías

[[song-of-songs-7-5]]
^5^ Tu cuello, como torre de marfil.

[[song-of-songs-7-6]]
^6^ Tu cabeza sobre ti, como el Carmelo,

[[song-of-songs-7-7]]
^7^ ¡Qué bella eres, qué encantadora,

[[song-of-songs-7-8]]
^8^ Tu talle se parece a la palmera,

[[song-of-songs-7-9]]
^9^ Me dije: Subiré a la palmera,

[[song-of-songs-7-10]]
^10^ tu paladar como vino generoso!

[[song-of-songs-7-11]]
^11^ Yo soy para mi amado,

[[song-of-songs-7-12]]
^12^ ¡Oh, ven, amado mío,

[[song-of-songs-7-13]]
^13^ De mañana iremos a las viñas;

[[song-of-songs-7-14]]
^14^ Las mandrágoras exhalan su fragancia.
[[song-of-songs-8]]
== Capítulo 8

[[song-of-songs-8-1]]
^1^ ¡Ah, si fueras tú un hermano mío,

[[song-of-songs-8-2]]
^2^ Te llevaría, te introduciría

[[song-of-songs-8-3]]
^3^ Su izquierda está bajo mi cabeza,

[[song-of-songs-8-4]]
^4^ Yo os conjuro,

[[song-of-songs-8-5]]
^5^ ¿Quién es ésta que sube del desierto,

[[song-of-songs-8-6]]
^6^ Ponme cual sello sobre tu corazón,

[[song-of-songs-8-7]]
^7^ Grandes aguas no pueden apagar el amor,

[[song-of-songs-8-8]]
^8^ Tenemos una hermana pequeña:

[[song-of-songs-8-9]]
^9^ - Si es una muralla,

[[song-of-songs-8-10]]
^10^ - Yo soy una muralla,

[[song-of-songs-8-11]]
^11^ Salomón tenía una viña

[[song-of-songs-8-12]]
^12^ Mi viña, la mía, está ante mí;

[[song-of-songs-8-13]]
^13^ ¡Oh tú, que moras en los huertos,

[[song-of-songs-8-14]]
^14^ ¡Huye, amado mío,
