[[wisdom]]
= Sabiduría

[[wisdom-1]]
== Capítulo 1

[[wisdom-1-1]]
^1^ Amad la justicia, los que juzgáis la tierra, pensad rectamente del Señor y con sencillez de corazón buscadle.

[[wisdom-1-2]]
^2^ Porque se deja hallar de los que no le tientan, se manifesta a los que no desconfían de él.

[[wisdom-1-3]]
^3^ Pues los pensamientos tortuosos apartan de Dios y el Poder, puesto a prueba, rechaza a los insensatos.

[[wisdom-1-4]]
^4^ En efecto, en alma fraudulenta no entra la Sabiduría, no habita en cuerpo sometido al pecado;

[[wisdom-1-5]]
^5^ pues el espíritu santo que nos educa huye del engaño, se aleja de los pensamientos necios y se ve rechazado al sobrevenir la iniquidad.

[[wisdom-1-6]]
^6^ La Sabiduría es un espíritu que ama al hombre, pero no deja sin castigo los labios del blasfemo; que Dios es testigo de sus riñones, observador veraz de su corazón y oye cuanto dice su lengua.

[[wisdom-1-7]]
^7^ Porque el espíritu del Señor llena la tierra y él, que todo lo mantiene unido, tiene conocimiento de toda palabra.

[[wisdom-1-8]]
^8^ Nadie, pues, que profiera iniquidades quedará oculto, ni le pasará por alto la Justicia vengadora.

[[wisdom-1-9]]
^9^ Las deliberaciones del impío serán examinadas; el eco de sus palabras llegará hasta el Señor para castigo de sus maldades.

[[wisdom-1-10]]
^10^ Un oído celoso lo escucha todo, no se le oculta ni el rumor de la murmuración.

[[wisdom-1-11]]
^11^ Guardaos, pues, de murmuraciones inútiles, preservad vuestra lengua de la maledicencia; que la palabra más secreta no se pronuncia en vano, y la boca mentirosa da muerte al alma.

[[wisdom-1-12]]
^12^ No os busquéis la muerte con los extravíos de vuestra, vida, no os atraigáis la ruina con las obras de vuestras manos;

[[wisdom-1-13]]
^13^ que no fue Dios quien hizo la muerte ni se recrea en la destrucción de los vivientes;

[[wisdom-1-14]]
^14^ él todo lo creó para que subsistiera, las criaturas del mundo non saludables, no hay en ellas veneno de muerte ni imperio del Hades sobre la tierra,

[[wisdom-1-15]]
^15^ porque la justicia es inmortal.

[[wisdom-1-16]]
^16^ Pero los impíos con las manos y las palabras llaman a la muerte; teniéndola por amiga, se desviven por ella, y con ella conciertan un pacto, pues bien merecen que les tenga por suyos.
[[wisdom-2]]
== Capítulo 2

[[wisdom-2-1]]
^1^ Porque se dicen discurriendo desacertadamente: «Corta es y triste nuestra vida; no hay remedio en la muerte del hombre ni se sabe de nadie que haya vuelto del Hades.

[[wisdom-2-2]]
^2^ Por azar llegamos a la existencia y luego seremos como si nunca hubiéramos sido. Porque humo es el aliento de nuestra nariz y el pensamiento, una chispa del latido de nuestro corazón;

[[wisdom-2-3]]
^3^ al apagarse, el cuerpo se volverá ceniza y el espíritu se desvanecerá como aire inconsistente.

[[wisdom-2-4]]
^4^ Caerá con el tiempo nuestro nombre en el olvido, nadie se acordará de nuestras obras; pasará nuestra vida como rastro de nube, se disipará como niebla acosada por los rayos del sol y por su calor vencida.

[[wisdom-2-5]]
^5^ Paso de una sombra es el tiempo que vivimos, no hay retorno en nuestra muerte; porque se ha puesto el sello y nadie regresa.

[[wisdom-2-6]]
^6^ Venid, pues, y disfrutemos de los bienes presentes, gocemos de las criaturas con el ardor de la juventud.

[[wisdom-2-7]]
^7^ Hartémonos de vinos exquisitos y de perfumes, no se nos pase ninguna flor primaveral,

[[wisdom-2-8]]
^8^ coronémonos de rosas antes que se marchiten;

[[wisdom-2-9]]
^9^ ningún prado quede libre de nuestra orgía, dejemos por doquier constancia de nuestro negocijo; que nuestra parte es ésta, ésta nuestra herencia.

[[wisdom-2-10]]
^10^ Oprimamos al justo pobre, no perdonemos a la viuda, no respetemos las canas llenas de años del anciano.

[[wisdom-2-11]]
^11^ Sea nuestra fuerza norma de la justicia, que la debilidad, como se ve, de nada sirve.

[[wisdom-2-12]]
^12^ Tendamos lazos al justo, que nos fastidia, se enfrenta a nuestro modo de obrar, nos echa en cara faltas contra la Ley y nos culpa de faltas contra nuestra educación.

[[wisdom-2-13]]
^13^ Se gloría de tener el conocimiento de Dios y se llama a sí mismo hijo del Señor.

[[wisdom-2-14]]
^14^ Es un reproche de nuestros criterios, su sola presencia nos es insufrible,

[[wisdom-2-15]]
^15^ lleva una vida distinta de todas y sus caminos son extraños.

[[wisdom-2-16]]
^16^ Nos tiene por bastardos, se aparta de nuestros caminos como de impurezas; proclama dichosa la suerte final de los justos y se ufana de tener a Dios por padre.

[[wisdom-2-17]]
^17^ Veamos si sus palabras son verdaderas, examinemos lo que pasará en su tránsito.

[[wisdom-2-18]]
^18^ Pues si el justo es hijo de Dios, él le asistirá y le librará de las manos de sus enemigos.

[[wisdom-2-19]]
^19^ Sometámosle al ultraje y al tormento para conocer su temple y probar su entereza.

[[wisdom-2-20]]
^20^ Condenémosle a una muerte afrentosa, pues, según él, Dios le visitará».

[[wisdom-2-21]]
^21^ Así discurren, pero se equivocan; los ciega su maldad;

[[wisdom-2-22]]
^22^ no conocen los secretos de Dios, no esperan recompensa por la santidad ni creen en el premio de las almas intachables.

[[wisdom-2-23]]
^23^ Porque Dios creó al hombre para la incorruptibilidad, le hizo imagen de su misma naturaleza;

[[wisdom-2-24]]
^24^ mas por envidia del diablo entró la muerte en el mundo, y la experimentan los que le pertenecen.
[[wisdom-3]]
== Capítulo 3

[[wisdom-3-1]]
^1^ En cambio, las almas de los justos están en las manos de Dios y no les alcanzará tormento alguno.

[[wisdom-3-2]]
^2^ A los ojos de los insensatos pareció que habían muerto; se tuvo por quebranto su salida,

[[wisdom-3-3]]
^3^ y su partida de entre nosotros por completa destrucción; pero ellos están en la paz.

[[wisdom-3-4]]
^4^ Aunque, a juicio de los hombres, hayan sufrido castigos, su esperanza estaba llena de inmortalidad;

[[wisdom-3-5]]
^5^ por una corta corrección recibirán largos beneficios. pues Dios los sometió a prueba y los halló dignos de sí;

[[wisdom-3-6]]
^6^ como oro en el crisol los probó y como holocausto los aceptó.

[[wisdom-3-7]]
^7^ El día de su visita resplandecerán, y como chispas en rastrojo correrán.

[[wisdom-3-8]]
^8^ Juzgarán a las naciones y dominarán a los pueblos y sobre ellos el Señor reinará eternamente.

[[wisdom-3-9]]
^9^ Los que en él confían entenderán la verdad y los que son fieles permanecerán junto a él en el amor, porque la gracia y la misericordia son para sus santos y su visita para sus elegidos.

[[wisdom-3-10]]
^10^ En cambio, los impíos tendrán la pena que sus pensamientos merecen, por desdeñar al justo y separarse del Señor.

[[wisdom-3-11]]
^11^ Desgraciados los que desprecian la sabiduría y la instrucción; vana es su esperanza, sin provecho sus fatigas, inútiles sus obras;

[[wisdom-3-12]]
^12^ sus mujeres son insensatas, malvados sus hijos, maldita su posteridad.

[[wisdom-3-13]]
^13^ Dichosa la estéril sin mancilla, la que no conoce lecho de pecado; tendrá su fruto en la visita de las almas.

[[wisdom-3-14]]
^14^ Dichoso también el eunuco que con sus manos no obra iniquidad ni fomenta pensamientos perversos contra el Señor; por su fidelidad se le dará una escogida recompensa, una herencia muy agradable en el Santurario del Señor.

[[wisdom-3-15]]
^15^ Que el fruto de los esfuerzos nobles es glorioso, imperecedera la raíz de la prudencia.

[[wisdom-3-16]]
^16^ En cambio los hijos de adúlteros no llegarán a sazón, desaparecerá la raza nacida de una unión culpable.

[[wisdom-3-17]]
^17^ Si viven largos años, no alcanzarán estima alguna y al fin su ancianidad carecerá de honor.

[[wisdom-3-18]]
^18^ Y si mueren pronto, no tendrán esperanza ni consuelo en el día de la sentencia,

[[wisdom-3-19]]
^19^ pues duro es el fin de una raza inicua.
[[wisdom-4]]
== Capítulo 4

[[wisdom-4-1]]
^1^ Mejor es carencia de hijos acompañada de virtud, pues hay inmortalidad en su recuerdo, porque es conocida por Dios y por los hombres;

[[wisdom-4-2]]
^2^ presente, la imitan, ausente, la añoran; en la eternidad, ceñida de una corona, celebra su triunfo porque venció en la lucha por premios incorruptibles.

[[wisdom-4-3]]
^3^ En cambio, la numerosa prole de los impíos será inútil; viniendo de renuevos bastardos, no echará raíces profundas ni se asentará sobre fundamento sólido.

[[wisdom-4-4]]
^4^ Aunque despliegue por su tiempo su ramaje, precariamente arraigada, será sacudida por el viento, arrancada de raíz por la furia del vendaval;

[[wisdom-4-5]]
^5^ se quebrarán sus ramas todavía tiernas, inútiles serán sus frutos, sin sazón para comerlos, para nada servirán.

[[wisdom-4-6]]
^6^ Que los hijos nacidos de sueños culpables son testigos, en su examen, de la maldad de los padres.

[[wisdom-4-7]]
^7^ El justo, aunque muera prematuramente, halla el descanso.

[[wisdom-4-8]]
^8^ La ancianidad venerable no es la de los muchos días ni se mide por el número de años;

[[wisdom-4-9]]
^9^ la verdadera canicie para el hombre es la prudencia, y la edad provecta, una vida inmaculada.

[[wisdom-4-10]]
^10^ Agradó a Dios y fue amado, y como vivía entre pecadores, fue trasladado.

[[wisdom-4-11]]
^11^ Fue arrebatado para que la maldad no pervitiera su inteligencia o el engaño sedujera su alma;

[[wisdom-4-12]]
^12^ pues la fascinación del mal empaña el bien y los vaivenes de la concupiscencia corrompen el espíritu ingenuo.

[[wisdom-4-13]]
^13^ Alcanzando en breve la perfección, llenó largos años.

[[wisdom-4-14]]
^14^ Su alma era del agrado del Señor, por eso se apresuró a sacarle de entre la maldad. Lo ven las gentes y no comprenden, ni caen en cuenta

[[wisdom-4-15]]
^15^ que la gracia y la misericordia son para sus elegidos y su visita para sus santos.

[[wisdom-4-16]]
^16^ El justo muerto condena a los impíos vivos, y la juventud pronto consumada, la larga ancianidad del inicuo.

[[wisdom-4-17]]
^17^ Ven la muerte del sabio, mas no comprenden los planes del Señor sobre él ni por qué le ha puesto en seguridad;

[[wisdom-4-18]]
^18^ lo ven y lo desprecian, pero el Señor se reirá de ellos.

[[wisdom-4-19]]
^19^ Después serán cadáveres despreciables, objeto de ultraje entre los muertos para siempre. Porque el Señor los quebrará lanzándolos de cabeza, sin habla, los sacudirá de sus cimientos; quedarán totalmentes asolados, sumidos en el dolor, y su recuerdo se perderá.

[[wisdom-4-20]]
^20^ Al tiempo de dar cuenta de sus pecados irán acobardados, y sus iniquidades se les enfrentarán acusándoles.
[[wisdom-5]]
== Capítulo 5

[[wisdom-5-1]]
^1^ Estará entonces el justo en pie con gran confianza en presencia de los que le afligieron y despreciaron sus trabajos.

[[wisdom-5-2]]
^2^ Al verle, quedarán estremecidos de terrible espanto, estupefactos por lo inesperado de su salvación.

[[wisdom-5-3]]
^3^ Se dirán mudando de parecer, gimiendo en la angustia de su espíritu:

[[wisdom-5-4]]
^4^ «Este es aquel a quien hicimos entonces objeto de nuestras burlas, a quien dirigíamos, insensatos, nuestros insultos. Locura nos pareció su vida y su muerte, una ignominia.

[[wisdom-5-5]]
^5^ ¿Cómo, pues, ha sido contado entre los hijos de Dios y tiene su herencia entre los santos?

[[wisdom-5-6]]
^6^ Luego vagamos fuera del camino de la verdad; la luz de la justicia no nos alumbró, no salió el sol para nosotros.

[[wisdom-5-7]]
^7^ Nos hartamos de andar por sendas de iniquidad y perdición, atravesamos desiertos intransitables; pero el camino del Señor, no lo conocimos.

[[wisdom-5-8]]
^8^ ¿De qué nos sirvió nuestro orgullo? ¿De qué la riqueza y la jactancia?

[[wisdom-5-9]]
^9^ Todo aquello pasó como una sombra, como noticia que va corriendo;

[[wisdom-5-10]]
^10^ como nave que atraviesa las aguas agitadas, y no es posible descubrir la huella de su paso ni el rastro de su quilla en las olas;

[[wisdom-5-11]]
^11^ como pájaro que volando atraviesa el aire, y de su vuelo no se encuentra vestigio alguno; con el golpe de sus remos azota el aire ligero, lo corta con agudo silbido, se abre camino batiendo las alas y después, no se descubre señal de su paso;

[[wisdom-5-12]]
^12^ como flecha disparada al blanco; el aire hendido refluye al instante sobre sí y no sabe el camino que la flecha siguió.

[[wisdom-5-13]]
^13^ Lo mismo nosotros: apenas nacidos, dejamos de existir, y no podemos mostrar vestigio alguno de virtud; nos gastamos en nuestra maldad».

[[wisdom-5-14]]
^14^ En efecto, la esperanza del impío es como brizna arrebatada por el viento, como espuma ligera acosada por el huracán, se desvanece como el humo con el viento; pasa como el recuerdo del huésped de un día.

[[wisdom-5-15]]
^15^ Los justos, en cambio, viven eternamente; en el Señor está su recompensa, y su cuidado a cargo del Altísimo.

[[wisdom-5-16]]
^16^ Recibirán por eso de mano del Señor la corona real del honor y la diadema de la hermosura; pues con su diestra los protegerá y los escudará con su brazo.

[[wisdom-5-17]]
^17^ Tomará su celo como armadura, y armará a la creación para rechazar a sus enemigos;

[[wisdom-5-18]]
^18^ por coraza vestirá la justicia, se pondrá por casco un juicio sincero,

[[wisdom-5-19]]
^19^ tomará por escudo su santidad invencible,

[[wisdom-5-20]]
^20^ afilará como espada su cólera inexorable, y el universo saldrá con él a pelear contra los insensatos.

[[wisdom-5-21]]
^21^ Partirán certeros los tiros de los rayos, de las nubes, como de arco bien tendido, saltarán al blanco,

[[wisdom-5-22]]
^22^ de una ballesta se disparará furioso granizo; las olas del mar se encresparán contra ellos, los ríos los anegarán sin piedad;

[[wisdom-5-23]]
^23^ se levantará contra ellos un viento poderoso y como huracán los aventará. Así la iniquidad asolará la tierra entera y la maldad derribará los tronos de los que están en el poder.
[[wisdom-6]]
== Capítulo 6

[[wisdom-6-1]]
^1^ Oíd, pues, reyes, y enteded. Aprended, jueces de los confines de la tierra.

[[wisdom-6-2]]
^2^ Estad atentos los que gobernáis multitudes y estáis orgullosos de la muchedumbre de vuestros pueblos.

[[wisdom-6-3]]
^3^ Porque del Señor habéis recibido el poder, del Altísimo, la soberanía; él examinará vuestras obras y sondeará vuestras intenciones.

[[wisdom-6-4]]
^4^ Si, como ministros que sois de su reino, no habéis juzgado rectamente, ni observado la ley, ni caminado siguiendo la voluntad de Dios,

[[wisdom-6-5]]
^5^ terrible y repentino se presentará ante vosotros. Porque un juicio implacable espera a los que están en lo alto;

[[wisdom-6-6]]
^6^ al pequeño, por piedad, se le perdona, pero los poderosos serán poderosamente examinados.

[[wisdom-6-7]]
^7^ Que el Señor de todos ante nadie retrocede, no hay grandeza que se le imponga; al pequeño como al grande él mismo los hizo y de todos tiene igual cuidado,

[[wisdom-6-8]]
^8^ pero una investigación severa aguarda a los que están en el poder.

[[wisdom-6-9]]
^9^ A vosotros, pues, soberanos, se dirigen mis palabras para que aprendaís sabiduría y no faltéis;

[[wisdom-6-10]]
^10^ porque los que guarden santamente las cosas santas, serán reconocidos santos, y los que se dejen instruir en ellas, encontrarán defensa.

[[wisdom-6-11]]
^11^ Desead, pues, mis palabras; ansiadlas, que ellas os instruirán.

[[wisdom-6-12]]
^12^ Radiante e inmarcesible es la Sabiduría. Fácilmente la contemplan los que la aman y la encuentran los que la buscan.

[[wisdom-6-13]]
^13^ Se anticipa a darse a conocer a los que la anhelan.

[[wisdom-6-14]]
^14^ Quien madruge para buscarla, no se fatigará, que a su puerta la encontrará sentada.

[[wisdom-6-15]]
^15^ Pensar en ella es la perfección de la prudencia, y quien por ella se desvele, pronto se verá sin cuidados.

[[wisdom-6-16]]
^16^ Pues ella misma va por todas partes buscando a los que son dignos de ella: se les muestra benévola en los caminos y les sale al encuentro en todos sus pensamientos.

[[wisdom-6-17]]
^17^ Pues su comienzo es el deseo más verdadero de instrucción, la preocupación por la instrucción es el amor,

[[wisdom-6-18]]
^18^ el amor es la observancia de sus leyes, la atención a las leyes es la garantía de la incorruptibilidad

[[wisdom-6-19]]
^19^ y la incorruptibilidad hace estar cerca de Dios;

[[wisdom-6-20]]
^20^ por tanto, el deseo de la Sabiduría conduce a la realeza.

[[wisdom-6-21]]
^21^ Si, pues, gustáis de tronos y cetros, soberanos de los pueblos, apreciad la Sabiduría para reinéis eternamente.

[[wisdom-6-22]]
^22^ Qué es la Sabiduría y cómo ha nacido lo voy a declarar; no os ocultaré los misterios, sino que seguiré sus huellas desde el comienzo de su existencia, pondré su conocimiento al descubierto y no me apartaré de la verdad.

[[wisdom-6-23]]
^23^ Tampoco me acompañará en mi camino la envidia mezquina, que nada tiene que ver con la Sabiduría.

[[wisdom-6-24]]
^24^ Pues la abundancia de sabios es la salvación del mundo y un rey prudente, la estabilidad del pueblo.

[[wisdom-6-25]]
^25^ Dejaos, pues, instruir por mis palabras: os serán útiles.
[[wisdom-7]]
== Capítulo 7

[[wisdom-7-1]]
^1^ Yo también soy un hombre mortal como todos, un descendiente del primero que fue formado de la tierra. En el seno de una madre fui hecho carne;

[[wisdom-7-2]]
^2^ durante diez meses fui modelado en su sangre, de una semilla de hombre y del placer que acompaña al sueño.

[[wisdom-7-3]]
^3^ Yo también, una vez nacido, aspiré el aire común, caí en la tierra que a todos recibe por igual y mi primera voz fue la de todos: lloré.

[[wisdom-7-4]]
^4^ Me crié entre pañales y cuidados.

[[wisdom-7-5]]
^5^ Pues no hay rey que haya tenido otro comienzo de su existencia;

[[wisdom-7-6]]
^6^ una es la entrada en la vida para todos y una misma la salida.

[[wisdom-7-7]]
^7^ Por eso pedí y se me concedió la prudencia; supliqué y me vino el espíritu de Sabiduría.

[[wisdom-7-8]]
^8^ Y la preferí a cetros y tronos y en nada tuve a la riqueza en comparación de ella.

[[wisdom-7-9]]
^9^ Ni a la piedra más preciosa la equiparé, porque todo el oro a su lado es un puñado de arena y barro parece la plata en su presencia.

[[wisdom-7-10]]
^10^ La amé más que la salud y la hermosura y preferí tenerla a ella más que a la luz, porque la claridad que de ella nace no conoce noche.

[[wisdom-7-11]]
^11^ Con ella me vinieron a la vez todos los bienes, y riquezas incalculables en sus manos.

[[wisdom-7-12]]
^12^ Y yo me regocijé con todos estos bienes porque la Sabiduría los trae, aunque ignoraba que ella fuese su madre.

[[wisdom-7-13]]
^13^ Con sencillez la aprendí y sin envidia la comunico; no me guardo ocultas sus riquezas

[[wisdom-7-14]]
^14^ porque es para los hombres un tesoro inagotable y los que lo adquieren se granjean la amistad de Dios recomendados por los dones que les trae la instrucción.

[[wisdom-7-15]]
^15^ Concédame Dios hablar según él quiere y concebir pensamientos dignos de sus dones, porque él es quien guía a la Sabiduría y quien dirige a los sabios;

[[wisdom-7-16]]
^16^ que nosotros y nuestras palabras en sus manos estamos con toda nuestra prudencia y destreza en el obrar.

[[wisdom-7-17]]
^17^ Fue él quien me concedió un conocimiento verdadero de los seres, para conocer la estructura del mundo y la actividad de los elementos,

[[wisdom-7-18]]
^18^ el principio, el fin y el medio de los tiempos, los cambios de los solsticios y la sucesión de las estaciones,

[[wisdom-7-19]]
^19^ los ciclos del año y la posición de las estrellas,

[[wisdom-7-20]]
^20^ la naturaleza de los animales y los instintos de las fieras, el poder de los espíritus y los pensamientos de los hombres, las variedades de las plantas y las virtudes de las raíces.

[[wisdom-7-21]]
^21^ Cuanto está oculto y cuanto se ve, todo lo conocí, porque el artífice de todo, la Sabiduría, me lo enseñó.

[[wisdom-7-22]]
^22^ Pues hay en ella un espíritu inteligente, santo, único, múltiple, sutil, ágil, perspicaz, inmaculado, claro, impasible, amante del bien, agudo,

[[wisdom-7-23]]
^23^ incoercible, bienhechor, amigo del hombre, firme, seguro, sereno, que todo lo puede, todo lo observa, penetra todos los espíritus, los inteligentes, los puros, los más sutiles.

[[wisdom-7-24]]
^24^ Porque a todo movimiento supera en movilidad la Sabiduría, todo lo atraviesa y penetra en virtud de su pureza.

[[wisdom-7-25]]
^25^ Es un hálito del poder de Dios, una emanación pura de la gloria del Omnipotente, por lo que nada manchado llega a alcanzarla.

[[wisdom-7-26]]
^26^ Es un reflejo de la luz eterna, un espejo sin mancha de la actividad de Dios, una imagen de su bondad.

[[wisdom-7-27]]
^27^ Aun siendo sola, lo puede todo; sin salir de sí misma, renueva el universo; en todas las edades, entrando en las almas santas, forma en ellas amigos de Dios y profetas,

[[wisdom-7-28]]
^28^ porque Dios no ama sino a quien vive con la Sabiduría.

[[wisdom-7-29]]
^29^ Es ella, en efecto, más bella que el sol, supera a todas las constelaciones; comparada con la luz, sale vencedora,

[[wisdom-7-30]]
^30^ porque a la luz sucede la noche, pero contra la Sabiduría no prevalece la maldad.
[[wisdom-8]]
== Capítulo 8

[[wisdom-8-1]]
^1^ Se despliega vigorosamente de un confín al otro del mundo y gobierna de excelente manera el universo.

[[wisdom-8-2]]
^2^ Yo la amé y la pretendí desde mi juventud; me esforcé por hacerla esposa mía y llegué a ser un apasionado de su belleza.

[[wisdom-8-3]]
^3^ Realza su nobleza por su convivencia con Dios, pues el Señor de todas las cosas la amó.

[[wisdom-8-4]]
^4^ Pues está iniciada en la ciencia de Dios y es la que elige sus obras.

[[wisdom-8-5]]
^5^ Si en la vida la riqueza es una posesión deseable, ¿qué cosa más rica que la Sabiduría que todo lo hace?

[[wisdom-8-6]]
^6^ Si la inteligencia es creadora, ¿quién sino la Sabiduría es el artífice de cuanto existe?

[[wisdom-8-7]]
^7^ ¿Amas la justicia? Las virtudes son sus empeños, pues ella enseña la templanza y la prudencia, la justicia y la fortaleza: lo más provechoso para el hombre en la vida.

[[wisdom-8-8]]
^8^ ¿Deseas además gran experiencia? Ella conoce el pasado y conjetura el porvenir, sabe interpretar las máximas y resolver los enigmas, conoce de antemano las señales y los prodigios, así como la sucesión de épocas y tiempos.

[[wisdom-8-9]]
^9^ Decidí, pues, tomarla por compañera de mi vida, sabiendo que me sería una consejera para el bien y un aliento en las preocupaciones y penas:

[[wisdom-8-10]]
^10^ «Tendré gracias a ella gloria entre la gente, y, aunque joven, honor ante los ancianos.

[[wisdom-8-11]]
^11^ Apareceré agudo en el juicio y en presencia de los poderosos seré admirado.

[[wisdom-8-12]]
^12^ Si callo, esperarán; si hablo, prestarán atención; si me alargo hablando, pondrán la mano en su boca.

[[wisdom-8-13]]
^13^ Gracias a ella tendré la inmortalidad y dejaré recuerdo eterno a los que después de mí vengan.

[[wisdom-8-14]]
^14^ Gobernaré a los pueblos, y las naciones me estarán sometidas.

[[wisdom-8-15]]
^15^ Oyendo hablar de mí, soberanos terribles temerán. Me mostraré bueno entre las multitudes y valiente en la guerra.

[[wisdom-8-16]]
^16^ Vuelto a casa, junto a ella descansaré, pues no causa amargura su compañía ni tristeza la convivencia con ella, sino satisfacción y alegría».

[[wisdom-8-17]]
^17^ Pensando esto conmigo mismo y considerando en mi corazón que se encuentra la inmortalidad en emparentar con la Sabiduría,

[[wisdom-8-18]]
^18^ en su amistad un placer bueno, en los trabajos de sus manos inagotables riquezas, prudencia en cultivar su trato y prestigio en conversar con ella, por todos los medios buscaba la manera de hacérmela mía.

[[wisdom-8-19]]
^19^ Era yo un muchacho de buen natural, me cupo en suerte un alma buena,

[[wisdom-8-20]]
^20^ o más bien, siendo bueno, vine a un cuerpo incontaminado;

[[wisdom-8-21]]
^21^ pero, comprendiendo que no podría poseer la Sabiduría si Dios no me la daba, - y ya era un fruto de la prudencia saber de quién procedía esta gracia - recurrí al Señor y le pedí, y dije con todo mi corazón:
[[wisdom-9]]
== Capítulo 9

[[wisdom-9-1]]
^1^ «Dios de los Padres, Señor de la misericordia, que hiciste el universo con tu palabra,

[[wisdom-9-2]]
^2^ y con tu Sabiduría formaste al hombre para que dominase sobre los seres por ti creados,

[[wisdom-9-3]]
^3^ administrase el mundo con santidad y justicia y juzgase con rectitud de espíritu,

[[wisdom-9-4]]
^4^ dame la Sabiduría, que se sienta junto a tu trono, y no me excluyas del número de tus hijos.

[[wisdom-9-5]]
^5^ Que soy un siervo tuyo, hijo de tu sierva, un hombre débil y de vida efímera, poco apto para entender la justicia y las leyes.

[[wisdom-9-6]]
^6^ Pues, aunque uno sea perfecto entre los hijos de los hombres, si le falta la Sabiduría que de ti procede, en nada será tenido.

[[wisdom-9-7]]
^7^ Tú me elegiste como rey de tu pueblo, como juez de tus hijos y tus hijas;

[[wisdom-9-8]]
^8^ tú me ordenaste edificar un santuario en tu monte santo y un altar en la ciudad donde habitas, imitación de la Tienda santa que habías preparado desde el principio.

[[wisdom-9-9]]
^9^ Contigo está la Sabiduría que conoce tus obras, que estaba presente cuando hacías el mundo, que sabe lo que es agradable a tus ojos, y lo que es conforme a tus mandamientos.

[[wisdom-9-10]]
^10^ Envíala de los cielos santos, mándala de tu trono de gloria para que a mi lado participe en mis trabajos y sepa yo lo que te es agradable,

[[wisdom-9-11]]
^11^ pues ella todo lo sabe y entiende. Ella me guiará prudentemente en mis empresas y me protegerá con su gloria.

[[wisdom-9-12]]
^12^ Entonces mis obras serán aceptables, juzgaré a tu pueblo con justicia y seré digno del trono de mi padre.

[[wisdom-9-13]]
^13^ ¿Qué hombre, en efecto, podrá conocer la voluntad de Dios? ¿Quién hacerse idea de lo que el Señor quiere?

[[wisdom-9-14]]
^14^ Los pensamientos de los mortales son tímidos e inseguras nuestras ideas,

[[wisdom-9-15]]
^15^ pues un cuerpo corruptible agobia el alma y esta tienda de tierra abruma el espíritu lleno de preocupaciones.

[[wisdom-9-16]]
^16^ Trabajosamente conjeturamos lo que hay sobre la tierra y con fatiga hallamos lo que está a nuestro alcance; ¿quién, entonces, ha rastreado lo que está en los cielos?

[[wisdom-9-17]]
^17^ Y ¿quién habría conocido tu voluntad, si tú no le hubieses dado la Sabiduría y no le hubieses enviado de lo alto tu espíritu santo?

[[wisdom-9-18]]
^18^ Sólo así se enderezaron los caminos de los moradores de la tierra, así aprendieron los hombres lo que a ti te agrada y gracias a la Sabiduría se salvaron».
[[wisdom-10]]
== Capítulo 10

[[wisdom-10-1]]
^1^ Ella protegió al primer modelado, padre del mundo, que había sido creado solo; ella le sacó de su caída

[[wisdom-10-2]]
^2^ y le dio el poder de dominar sobre todas las cosas.

[[wisdom-10-3]]
^3^ Pero cuando un injusto, en su cólera, se apartó de ella, pereció por su furor fraticida.

[[wisdom-10-4]]
^4^ Cuando por su causa la tierra se vio sumergida, de nuevo la Sabiduría la salvó conduciendo al justo en un vulgar leño.

[[wisdom-10-5]]
^5^ En la confusión que siguió a la común perversión de las naciones, ella conoció al justo, le conservó irreprochable ante Dios y le mantuvo firme contra el entrañable amor a su hijo.

[[wisdom-10-6]]
^6^ Ella, en el exterminio de los impíos, libró al justo cuando escapaba del fuego que bajaba sobre Pentápolis.

[[wisdom-10-7]]
^7^ Como testimonio de aquella maldad queda todavía una tierra desolada humeando, unas plantas cuyos frutos no alcanzan sazón a su tiempo, y, como monumento de un alma incrédula, se alza una columna de sal.

[[wisdom-10-8]]
^8^ Pues, por haberse apartado del camino de la Sabiduría, no sólo sufrieron la desgracia de no conocer el bien, sino que dejaron además a los vivientes un recuerdo de su insensatez, para que ni sus faltas pudieran quedar ocultas.

[[wisdom-10-9]]
^9^ En cambio, a sus servidores la Sabiduría los libró de sus fatigas.

[[wisdom-10-10]]
^10^ Ella al justo que huía de la cólera de su hermano le guió por caminos rectos; le mostró el reino de Dios y le dio el conocimiento de cosas santas; le dio éxito en sus duros trabajos y multiplicó el fruto de sus fatigas;

[[wisdom-10-11]]
^11^ le asistió contra la avaricia de sus opresores y le enriqueció;

[[wisdom-10-12]]
^12^ le preservó de sus enemigos y le protegió de los que le tendían asechanzas; y le concedió la palma en un duro combate para enseñarle que la piedad contra todo prevalece.

[[wisdom-10-13]]
^13^ Ella no desamparó al justo vendido, sino que le libró del pecado;

[[wisdom-10-14]]
^14^ bajó con él a la cisterna y no le abandonó en las cadenas, hasta entregarle el cetro real y el poder sobre sus tiranos, hasta mostrar mentirosos a sus difamadores y concederle una gloria eterna.

[[wisdom-10-15]]
^15^ Ella libró de una nación opresora a un pueblo santo y a una raza irreprochable.

[[wisdom-10-16]]
^16^ Entró en el alma de un servidor del Señor e hizo frente a reyes temibles con prodigios y señales;

[[wisdom-10-17]]
^17^ pagó a los santos el salario de sus trabajos; los guió por un camino maravilloso, fue para ellos cobertura durante el día y lumbre de estrellas durante la noche;

[[wisdom-10-18]]
^18^ les abrió paso por el mar Rojo y los condujo a través de las inmensas aguas,

[[wisdom-10-19]]
^19^ mientras a sus enemigos los sumergió y luego los hizo saltar de las profundidades del abismo.

[[wisdom-10-20]]
^20^ De este modo los justos despojaron a los impíos; entonaron cantos, Señor, a tu santo Nombre y unánimes celebraron tu mano protectora,

[[wisdom-10-21]]
^21^ porque la Sabiduría abrió la boca de los mudos e hizo claras las lenguas de los pequeñuelos.
[[wisdom-11]]
== Capítulo 11

[[wisdom-11-1]]
^1^ Ella dirigió felizmente sus empresas por medio de un profeta santo.

[[wisdom-11-2]]
^2^ Atravesaron un desierto deshabitado y fijaron sus tiendas en parajes inaccesibles;

[[wisdom-11-3]]
^3^ hicieron frente a sus enemigos y rechazaron a sus adversarios.

[[wisdom-11-4]]
^4^ Tuvieron sed y te invocaron: de una roca abrupta se les dio agua, de una piedra dura, remedio para su sed.

[[wisdom-11-5]]
^5^ Lo mismo que fue para sus enemigos un castigo, fue para ellos en su apuro un beneficio.

[[wisdom-11-6]]
^6^ En vez de la fuente perenne de un río enturbiado por una mezcla de sangre y barro

[[wisdom-11-7]]
^7^ en pena de su decreto infanticida, diste a los tuyos inesperadamente un agua abundante,

[[wisdom-11-8]]
^8^ mostrándoles por la sed que entonces sufrieron de qué modo habías castigado a sus adversarios.

[[wisdom-11-9]]
^9^ Pues cuando sufrieron su prueba - si bien con misericordia corregidos - conocieron cómo los impíos, juzgados con cólera, eran torturados;

[[wisdom-11-10]]
^10^ pues a ellos los habías probado como padre que amonesta, pero a los otros los habías castigado como rey severo que condena.

[[wisdom-11-11]]
^11^ Tanto estando lejos como cerca, igualmente se consumían,

[[wisdom-11-12]]
^12^ pues una doble tristeza se apoderó de ellos, y un lamento con el recuerdo del pasado:

[[wisdom-11-13]]
^13^ porque, al oír que lo mismo que era su castigo, era para los otros un beneficio, reconocieron al Señor;

[[wisdom-11-14]]
^14^ pues al que antes hicieron exponer y luego rechazaron con escarnio, al final de los acontecimientos le admiraron después de padecer una sed bien diferente de la de los justos.

[[wisdom-11-15]]
^15^ Por sus locos e inicuos pensamientos por los que, extraviados, adoraban reptiles sin razón y bichos despreciables, les enviaste en castigo muchedumbre de animales sin razón,

[[wisdom-11-16]]
^16^ para que aprendiesen que, por donde uno peca, por allí es castigado.

[[wisdom-11-17]]
^17^ Pues bien podía tu mano omnipotente - ella que de informe materia había creado el mundo - enviar contra ellos muchedumbre de osos o audaces leones,

[[wisdom-11-18]]
^18^ o bien fieras desconocidas, entonces creadas, llenas de furor, respirando aliento de fuego, lanzando humo hediondo o despidiendo de sus ojos terribles centellas,

[[wisdom-11-19]]
^19^ capaces, no ya de aniquilarlos con sus ataques, sino de destruirlos con sólo su estremecedor aspecto.

[[wisdom-11-20]]
^20^ Y aun sin esto, de un simple soplo podían sucumbir, perseguidos por la Justicia, aventados por el soplo de tu poder. Pero tú todo lo dispusiste con medida, número y peso.

[[wisdom-11-21]]
^21^ Pues el actuar con inmenso poder siempre está en tu mano. ¿Quién se podrá oponer a la fuerza de tu brazo?

[[wisdom-11-22]]
^22^ Como lo que basta a inclinar una balanza, es el mundo entero en tu presencia, como la gota de rocío que a la mañana baja sobre la tierra.

[[wisdom-11-23]]
^23^ Te compadeces de todos porque todo lo puedes y disimulas los pecados de los hombres para que se arrepientan.

[[wisdom-11-24]]
^24^ Amas a todos los seres y nada de lo que hiciste aborreces, pues, si algo odiases, no lo habrías hecho.

[[wisdom-11-25]]
^25^ Y ¿cómo habría permanecido algo si no hubieses querido? ¿Cómo se habría conservado lo que no hubieses llamado?

[[wisdom-11-26]]
^26^ Mas tú con todas las cosas eres indulgente, porque son tuyas, Señor que amas la vida,
[[wisdom-12]]
== Capítulo 12

[[wisdom-12-1]]
^1^ pues tu espíritu incorruptible está en todas ellas.

[[wisdom-12-2]]
^2^ Por eso mismo gradualmente castigas a los que caen; les amonestas recordándoles en qué pecan para que, apartándose del mal, crean en ti, Señor.

[[wisdom-12-3]]
^3^ A los antiguos habitantes de tu tierra santa

[[wisdom-12-4]]
^4^ los odiabas, porque cometían las más nefastas acciones, prácticas de hechicería, iniciaciones impías.

[[wisdom-12-5]]
^5^ A estos despiadados asesinos de sus hijos, devoradores de entrañas en banquetes de carne humana y de sangre, a estos iniciados en bacanales,

[[wisdom-12-6]]
^6^ padres asesinos de seres indefensos, habías querido destruirlos a manos de nuestros padres,

[[wisdom-12-7]]
^7^ para que la tierra que te era la más apreciada de todas, recibiera una digna colonia de hijos de Dios.

[[wisdom-12-8]]
^8^ Pero aun con éstos, por ser hombres, te mostraste indulgente, y les enviaste avispas, como precursoras de tu ejército, que les fuesen poco a poco destruyendo.

[[wisdom-12-9]]
^9^ No porque no pudieses en batalla campal entregar a los impíos en manos de los justos, o aniquilarlos de una vez con feroces fieras o con una palabra inexorable,

[[wisdom-12-10]]
^10^ sino que les concedías, con un castigo gradual, una ocasión de arrepentirse; aun sabiendo que era su natural perverso, su malicia innata, y que jamás cambiaría su manera de pensar

[[wisdom-12-11]]
^11^ por ser desde el comienzo una raza maldita. Tampoco por temor a nadie concedías la impunidad a sus pecados.

[[wisdom-12-12]]
^12^ Pues ¿quién podría decirte: «¿Qué has hecho?» ¿Quién se opondría a tu sentencia? ¿Quién te citaría a juicio por destruir naciones por ti creadas? ¿Quién se alzaría contra ti como vengador de hombres inicuos?

[[wisdom-12-13]]
^13^ Pues fuera de ti no hay un Dios que de todas las cosas cuide, a quien tengas que dar cuenta de la justicia de tus juicios;

[[wisdom-12-14]]
^14^ ni hay rey ni soberano que se te enfrente en favor de los que has castigado.

[[wisdom-12-15]]
^15^ Sino que, como eres justo, con justicia administras el universo, y miras como extraño a tu poder condenar a quien no merece ser castigado.

[[wisdom-12-16]]
^16^ Tu fuerza es el principio de tu justicia y tu señorío sobre todos los seres te hace indulgente con todos ellos

[[wisdom-12-17]]
^17^ Ostentas tu fuerza a los que no creen en la plenitud de tu poder, y confundes la audacia de los que la conocen.

[[wisdom-12-18]]
^18^ Dueño de tu fuerza, juzgas con moderación y nos gobiernas con mucha indulgencia porque, con sólo quererlo, lo puedes todo.

[[wisdom-12-19]]
^19^ Obrando así enseñaste a tu pueblo que el justo debe ser amigo del hombre, y diste a tus hijos la buena esperanza de que, en el pecado, das lugar al arrepentimiento.

[[wisdom-12-20]]
^20^ Pues si a los enemigos de tus hijos, merecedores de la muerte, con tanto miramiento e indulgencia los castigaste dándoles tiempo y lugar para apartarse de la maldad,

[[wisdom-12-21]]
^21^ ¿con qué consideración no juzgaste a los hijos tuyos, a cuyos padres con juramentos y pactos tan buenas promesas hiciste?

[[wisdom-12-22]]
^22^ Así pues, para aleccionarnos, a nuestros enemigos los flagelas con moderación, para que, al juzgar, tengamos en cuenta tu bondad y, al ser juzgados, esperemos tu misericordia.

[[wisdom-12-23]]
^23^ Por tanto, también a los que inicuamente habían vivido una vida insensata les atormentaste con sus mismas abominaciones.

[[wisdom-12-24]]
^24^ Demasiado, en verdad, se habían desviado por los caminos del error, teniendo por dioses a los más viles y despreciables, animales, dejándose engañar como pequeñuelos inconscientes.

[[wisdom-12-25]]
^25^ Por eso, como a niños sin seso, les enviaste una irrisión de castigo.

[[wisdom-12-26]]
^26^ Pero los que con una reprimenda irrisoria no se enmendaron, iban a experimentar un castigo digno de Dios.

[[wisdom-12-27]]
^27^ A la vista de los seres que les atormentaban y les indignaban, de aquellos seres que tenían por dioses y eran ahora su castigo, abrieron los ojos y reconocieron por el Dios verdadero a aquel que antes se negaban a conocer. Por lo cual el supremo castigo descargó sobre ellos.
[[wisdom-13]]
== Capítulo 13

[[wisdom-13-1]]
^1^ Sí, vanos por naturaleza todos los hombres en quienes había ignorancia de Dios y no fueron capaces de conocer por las cosas buenas que se ven a Aquél que es, ni, atendiendo a las obras, reconocieron al Artífice;

[[wisdom-13-2]]
^2^ sino que al fuego, al viento, al aire ligero, a la bóveda estrellada, al agua impetuosa o a las lumbreras del cielo los consideraron como dioses, señores del mundo.

[[wisdom-13-3]]
^3^ Que si, cautivados por su belleza, los tomaron por dioses, sepan cuánto les aventaja el Señor de éstos, pues fue el Autor mismo de la belleza quien los creó.

[[wisdom-13-4]]
^4^ Y si fue su poder y eficiencia lo que les dejó sobrecogidos, deduzcan de ahí cuánto más poderoso es Aquel que los hizo;

[[wisdom-13-5]]
^5^ pues de la grandeza y hermosura de las criaturas se llega, por analogía, a contemplar a su Autor.

[[wisdom-13-6]]
^6^ Con todo, no merecen éstos tan grave reprensión, pues tal vez caminan desorientados buscando a Dios y queriéndole hallar.

[[wisdom-13-7]]
^7^ Como viven entre sus obras, se esfuerzan por conocerlas, y se dejan seducir por lo que ven. ¡Tan bellas se presentan a los ojos!

[[wisdom-13-8]]
^8^ Pero, por otra parte, tampoco son éstos excusables;

[[wisdom-13-9]]
^9^ pues si llegaron a adquirir tanta ciencia que les capacitó para indagar el mundo, ¿cómo no llegaron primero a descubrir a su Señor?

[[wisdom-13-10]]
^10^ Desgraciados, en cambio, y con la esperanza puesta en seres sin vida, los que llamaron dioses a obras hechas por mano de hombre, al oro, a la plata, trabajados con arte, a representaciones de animales o a una piedra inútil, esculpida por mano antigua.

[[wisdom-13-11]]
^11^ Un leñador abate con la sierra un árbol conveniente, lo despoja diestramente de toda su corteza, lo trabaja con habilidad y fabrica un objeto útil a las necesidades de la vida.

[[wisdom-13-12]]
^12^ Con los restos de su trabajo se prepara la comida que le deja satisfecho.

[[wisdom-13-13]]
^13^ Queda todavía un resto del árbol que para nada sirve, un tronco torcido y lleno de nudos. Lo toma y lo labra para llenar los ratos de ocio, le da forma con la destreza adquirida en sus tiempos libres; le da el parecido de una imagen de hombre

[[wisdom-13-14]]
^14^ o bien la semejanza de algún vil animal. Lo pinta de bermellón, colorea de rojo su cuerpo y salva todos sus defectos bajo la capa de pintura.

[[wisdom-13-15]]
^15^ Luego le prepara un alojamiento digno y lo pone en una pared asegurándolo con un hierro.

[[wisdom-13-16]]
^16^ Mira por él, no se le caiga, pues sabe que no puede valerse por sí mismo, que sólo es una imagen y necesita que le ayuden.

[[wisdom-13-17]]
^17^ Pues bien, cuando por su hacienda, bodas o hijos ruega, no se le cae la cara al dirigirse a este ser sin vida. Y pide salud a un inválido,

[[wisdom-13-18]]
^18^ vida a un muerto, auxilio al más inexperto, un viaje feliz al que ni de los pies se puede valer,

[[wisdom-13-19]]
^19^ y para sus ganancias y empresas, para el exito en el trabajo de sus manos, al ser más desmañado le pide destreza.
[[wisdom-14]]
== Capítulo 14

[[wisdom-14-1]]
^1^ Otro, preparándose a embarcar para cruzar el mar bravío, invoca a un leño más frágil que la nave que le lleva.

[[wisdom-14-2]]
^2^ Que a la nave, al fin, la inventó el afán de lucro, y la sabiduría fue el artífice que la construyó;

[[wisdom-14-3]]
^3^ y es tu Providencia, Padre, quien la guía, pues también en el mar abriste un camino, una ruta segura a través de las olas,

[[wisdom-14-4]]
^4^ mostrando así que de todo peligro puedes salvar para que hasta el inexperto pueda embarcarse.

[[wisdom-14-5]]
^5^ No quieres que queden inactivas las obras de tu Sabiduría; por eso, a un minúsculo leño fían los hombres su vida, cruzan el oleaje en una barquichuela y arriban salvos a puerto.

[[wisdom-14-6]]
^6^ También al principio, mientras los soberbios gigantes perecían, se refugió en una barquichuela la esperanza del mundo, y, guiada por tu mano, dejó al mundo semilla de una nueva generación.

[[wisdom-14-7]]
^7^ Pues bendito es el leño por el que viene la justicia,

[[wisdom-14-8]]
^8^ pero el ídolo fabricado, maldito él y el que lo hizo; uno por hacerle, el otro porque, corruptible, es llamado dios,

[[wisdom-14-9]]
^9^ y Dios igualmente aborrece al impío y su impiedad;

[[wisdom-14-10]]
^10^ ambos, obra y artífice, serán igualmente castigados.

[[wisdom-14-11]]
^11^ Por eso también habrá una visita para los ídolos de las naciones, porque son una abominación entre las criaturas de Dios, un escándalo para las almas de los hombres, un lazo para los pies de los insensatos.

[[wisdom-14-12]]
^12^ La invención de los ídolos fue el principio de la fornicación; su descubrimiento, la corrupción de la vida.

[[wisdom-14-13]]
^13^ No los hubo al principio ni siempre existirán;

[[wisdom-14-14]]
^14^ por la vanidad de los hombres entraron en el mundo y, por eso, está decidido su rápido fin.

[[wisdom-14-15]]
^15^ Un padre atribulado por un luto prematuro encarga una imagen del hijo malogrado; al hombre muerto de ayer, hoy como un dios le venera y transmite a los suyos misterios y ritos.

[[wisdom-14-16]]
^16^ Luego, la impía costumbre, afianzada con el tiempo, se acata como ley.

[[wisdom-14-17]]
^17^ También por decretos de los soberanos recibían culto las estatuas. Unos hombres que, por vivir apartados, no les podían honrar en persona, representaron su lejana figura encargando una imagen, reflejo del rey venerado; así lisonjearían con su celo al ausente como si presente se hallara.

[[wisdom-14-18]]
^18^ A extender este culto contribuyó la ambición del artista y arrastró incluso a quienes nada del rey sabían;

[[wisdom-14-19]]
^19^ pues deseoso, sin duda, de complacer al soberano, alteró con su arte la semejanza para que saliese más bella,

[[wisdom-14-20]]
^20^ y la muchedumbre seducida por el encanto de la obra, al que poco antes como hombre honraba, le consideró ya objeto de adoración.

[[wisdom-14-21]]
^21^ De aquí provino la asechanza que se le tendió a la vida: que, víctimas de la desgracia o del poder de los soberanos, dieron los hombres a piedras y leños el Nombre incomunicable.

[[wisdom-14-22]]
^22^ Luego, no bastó con errar en el conocimiento de Dios; viviendo además la guerra que esta ignorancia les mueve, ellos a tan graves males les dan el nombre de paz.

[[wisdom-14-23]]
^23^ Con sus ritos infanticidas, sus misterios secretos, sus delirantes orgías de costumbres extravagantes,

[[wisdom-14-24]]
^24^ ni sus vidas ni sus matrimonios conservan ya puros. Uno elimina a otro a traición o le aflige dándole bastardos;

[[wisdom-14-25]]
^25^ por doquiera, en confusión, sangre y muerte, robo y fraude, corrupción, deslealtad, agitación, perjurio,

[[wisdom-14-26]]
^26^ trastorno del bien, olvido de la gratitud, inmundicia en las almas, inversión en los sexos, matrimonios libres, adulterios, libertinaje.

[[wisdom-14-27]]
^27^ Que es culto de los ídolos sin nombre principio, causa y término de todos los males.

[[wisdom-14-28]]
^28^ Porque o se divierten alocadamente, o manifiestan oráculos falsos, o viven una vida de injusticia, o con toda facilidad perjuran:

[[wisdom-14-29]]
^29^ como los ídolos en que confían no tienen vida, no esperan que del perjurio se les siga algún mal.

[[wisdom-14-30]]
^30^ Una justa sanción les alcanzará, sin embargo, por doble motivo: por formarse de Dios una idea falsa al darse a los ídolos y por jurar injustamente contra la verdad con desprecio de toda santidad.

[[wisdom-14-31]]
^31^ Que no es el poder de aquellos en cuyo nombre juran; es la sanción que merece todo el que peca, la que persigue siempre la transgresión de los inicuos.
[[wisdom-15]]
== Capítulo 15

[[wisdom-15-1]]
^1^ Mas tú, Dios nuestro, eres bueno y verdadero, paciente y que con misericordia gobiernas el universo.

[[wisdom-15-2]]
^2^ Aunque pequemos, tuyos somos, porque conocemos tu poder; pero no pecaremos, porque sabemos que somos contados por tuyos.

[[wisdom-15-3]]
^3^ Pues el conocerte a ti es la perfecta justicia y conocer tu poder, la raíz de la inmortalidad.

[[wisdom-15-4]]
^4^ A nosotros no nos extraviaron las creaciones humanas de un arte perverso, ni el inútil trabajo de los pintores, figuras embadurnadas de colores abigarrados,

[[wisdom-15-5]]
^5^ cuya contemplación despierta la pasión en los insensatos que codician la figura sin aliento de una imagen muerta.

[[wisdom-15-6]]
^6^ Apasionados del mal son y dignos de tales esperanzas los que las crean, los que las codician, los que las adoran.

[[wisdom-15-7]]
^7^ Un alfarero trabaja laboriosamente la tierra blanda y modela diversas piezas, todas para nuestro uso; unas van destinadas a usos nobles, otras al contrario, pero todas las modela de igual manera y de la misma arcilla. Sobre el servicio diverso que unas y otras han de prestar, es el alfarero quien decide.

[[wisdom-15-8]]
^8^ Pero luego - ¡mala pena que se toma! - de la misma arcilla modela una vana divinidad. Y la modela él, que poco ha nació de la tierra y que pronto habrá de volver a la tierra de donde fue sacado, cuando le reclamen la devolución de su alma.

[[wisdom-15-9]]
^9^ Pero no se preocupa de que va a morir, de que es efímera su vida; antes rivaliza con orfebres y plateros, imita las obras del broncista y se ufana de modelar falsificaciones.

[[wisdom-15-10]]
^10^ Escoria es su corazón, más vil que la tierra su esperanza, más abyecta que la arcilla su vida,

[[wisdom-15-11]]
^11^ porque desconoció al que le modeló a él, al que le inspiró un alma activa y le infundió un espíritu vivificante.

[[wisdom-15-12]]
^12^ Piensa que la existencia es un juego de niños y la vida, un lucrativo mercado: «Es preciso ganar, dice, por todos los medios, aun malos».

[[wisdom-15-13]]
^13^ Este hombre más que nadie sabe que peca, como quien de una misma masa de tierra fabrica frágiles piezas y estatuas de ídolos.

[[wisdom-15-14]]
^14^ Insensatos todos en sumo grado y más infelices que el alma de un niño, los enemigos de tu pueblo que un día le oprimieron;

[[wisdom-15-15]]
^15^ como que tuvieron por dioses a todos los ídolos de los gentiles, que no pueden valerse de los ojos para ver, ni de la nariz para respirar, ni de los oídos para oír, ni de los dedos de las manos para tocar, y sus pies son torpes para andar.

[[wisdom-15-16]]
^16^ Al fin, un hombre los hizo, uno que recibió en préstamo el espíritu los modeló; y no hay hombre que modele un dios igual a sí mismo;

[[wisdom-15-17]]
^17^ mortal como es, un ser muerto produce con sus manos impías. Vale ciertamente más que las cosas que adora: él, un tiempo al menos, goza de vida, ellos jamás.

[[wisdom-15-18]]
^18^ Adoran, además, a los bichos más repugnantes que en estupidez superan a todos los demás;

[[wisdom-15-19]]
^19^ ni siquiera poseen la belleza de los animales que, a su modo, cautiva al contemplarlos; están excluidos de la aprobación de Dios y de su bendición.
[[wisdom-16]]
== Capítulo 16

[[wisdom-16-1]]
^1^ Por eso, mediante seres semejantes, fueron justamente castigados; una multitud de bichos les sometieron a tormento.

[[wisdom-16-2]]
^2^ En vez de tal castigo, concediste favores a tu pueblo: para satisfacer su voraz apetito, les preparaste como alimento un manjar exquisito: codornices;

[[wisdom-16-3]]
^3^ para que aquéllos, aun ansiando el alimento, por el asqueroso aspecto de los bichos que les enviabas, hasta el apetito natural perdiesen, y éstos, pasadas unas breves privaciones, viniesen a gustar manjares exquisitos.

[[wisdom-16-4]]
^4^ Era razón que aquéllos, los opresores, sufrieran un hambre irremediable, mientras a éstos bastaba mostrarles la clase de tormento que sus enemigos padecían.

[[wisdom-16-5]]
^5^ Incluso cuando cayó sobre ellos la ira terrible de animales feroces, cuando por mordeduras de sinuosas serpientes perecían, no persistió tu cólera hasta el fin.

[[wisdom-16-6]]
^6^ Como advertencia se vieron atribulados por breve tiempo, pues tenían una señal de salvación como recuerdo del mandamiento de tu Ley;

[[wisdom-16-7]]
^7^ y el que a ella se volvía, se salvaba, no por lo que contemplaba, sino por ti, Salvador de todos.

[[wisdom-16-8]]
^8^ De este modo convenciste a nuestros enemigos de que tú eres el que libras de todo mal:

[[wisdom-16-9]]
^9^ a ellos picaduras de langostas y moscas los mataban, - y bien merecían que bichos tales los castigasen - sin que remedio hallaran para su vida;

[[wisdom-16-10]]
^10^ a tus hijos, en cambio, ni dientes de serpientes venenosas los vencieron, pues vino tu misericordia en su socorro y los sanó.

[[wisdom-16-11]]
^11^ Las mordeduras - pronto curadas - les recordaban tus preceptos no fuera que, cayendo en profundo olvido, se vieran excluidos de tu liberalidad.

[[wisdom-16-12]]
^12^ Ni los curó hierba ni emplasto alguno, sino tu palabra, Señor, que todo lo sana.

[[wisdom-16-13]]
^13^ Pues tú tienes el poder sobre la vida y sobre la muerte, haces bajar a las puertas del Hades y de allí subir.

[[wisdom-16-14]]
^14^ El hombre, en cambio, puede matar por su maldad, pero no hacer tornar al espíritu que se fue, ni liberar al alma ya acogida en el Hades.

[[wisdom-16-15]]
^15^ Es imposible escapar de tu mano.

[[wisdom-16-16]]
^16^ Los impíos que rehusaban conocerte fueron fustigados por la fuerza de tu brazo; lluvias insólitas, granizadas, aguaceros implacables los persigueron y el fuego los devoró.

[[wisdom-16-17]]
^17^ Y lo más extraño era que con el agua, que todo lo apaga, el fuego cobraba una violencia mayor. El universo, en efecto, combate en favor de los justos.

[[wisdom-16-18]]
^18^ Las llamas unas veces se amansaban para no consumir a los animales enviados contra los impíos, y darles a entender, por lo que veían, que el juicio de Dios les hostigaba;

[[wisdom-16-19]]
^19^ pero otras, aun en medio de las aguas, abrasaban con fuerza superior a la del fuego para destruir las cosechas de una tierra inicua.

[[wisdom-16-20]]
^20^ A tu pueblo, por el contrario, le alimentaste con manjar de ángeles; les suministraste, sin cesar desde el ciel un pan ya preparado que podía brindar todas las delicias y satisfacer todos los gustos.

[[wisdom-16-21]]
^21^ El sustento que les dabas revelaba tu dulzura con tus hijos pues, adaptándose al deseo del que lo tomaba, se tranformaba en lo que cada uno quería.

[[wisdom-16-22]]
^22^ Nieve y hielo resistían al fuego sin fundirse, para que supieran que el fuego, para destruir las cosechas de sus enemigos, entre el granizo abrasaba y fulguraba entre la lluvia,

[[wisdom-16-23]]
^23^ mientras que, para que los justos pudieran sustentarse, hasta de su natural poder se olvidaba.

[[wisdom-16-24]]
^24^ Porque la creación, sirviéndote a ti, su Hacedor, se embravece para castigo de los inicuos y se amansa en favor de los que en ti confían.

[[wisdom-16-25]]
^25^ Por eso, también entonces, cambiándose en todo, servía a tu liberalidad que a todos sustenta, conforme al deseo de los necesitados.

[[wisdom-16-26]]
^26^ De este modo enseñabas a tus hijos queridos, Señor, que no son las diversas especies de frutos los que alimentan al hombre, sino que es tu palabra la que mantiene a los que creen en ti.

[[wisdom-16-27]]
^27^ El fuego no alcanzaba a disolver lo que sencillamente derretía el calor de un breve rayo de sol.

[[wisdom-16-28]]
^28^ Con ello le enseñabas que debían adelantarse al sol para darte gracias y recurrir a ti al rayar el día,

[[wisdom-16-29]]
^29^ pues la esperanza del ingrato como escarcha invernal se derrite y corre como agua inútil.
[[wisdom-17]]
== Capítulo 17

[[wisdom-17-1]]
^1^ Grandes son en verdad tus juicios e inenarrables, por donde almas ignorantes se vinieron a engañar.

[[wisdom-17-2]]
^2^ Imaginaban los impíos que podrían oprimir a una nación santa; y se encontraron prisioneros de tinieblas, en larga noche trabados, recluidos en sus casas, desterrados de la Providencia eterna.

[[wisdom-17-3]]
^3^ Creían que se mantendrían ocultos con sus secretos pecados bajo el oscuro velo del olvido; y se vieron dispersos, presa de terrible espanto, sobresaltados por apariciones.

[[wisdom-17-4]]
^4^ Pues ni el escondrijo que les protegía les libraba del miedo; que también allí resonaban ruidos escalofriantes y se aparecían espectros sombríos de lúgubre aspecto.

[[wisdom-17-5]]
^5^ No había fuego intenso capaz de alumbrarles, ni las brillantes llamas de las estrellas alcanzaban a esclarecer aquella odiosa noche.

[[wisdom-17-6]]
^6^ Tan sólo una llamarada, por sí misma encendida, se dejaba entrever sembrando el terror; pues en su espanto, al desaparecer la visión, imaginaban más horrible aún lo que acababan de ver.

[[wisdom-17-7]]
^7^ Los artificios de la magia resultaron ineficaces; con gran afrenta quedó refutado su pretendido saber,

[[wisdom-17-8]]
^8^ pues los que prometían expulsar miedos y sobresaltos de las almas enloquecidas, enloquecían ellos mismos con ridículos temores.

[[wisdom-17-9]]
^9^ Incluso cuando otro espanto no les atemorizara, sobresaltados por el paso de los bichos y el silbido de los reptiles,

[[wisdom-17-10]]
^10^ se morían de miedo, y rehusaban mirar aquel aire que de ninguna manera podían evitar.

[[wisdom-17-11]]
^11^ Cobarde es, en efecto, la maldad y ella a sí misma se condena; acosada por la conciencia imagina siempre lo peor;

[[wisdom-17-12]]
^12^ pues no es otra cosa el miedo sino el abandono del apoyo que presta la reflexión;

[[wisdom-17-13]]
^13^ y cuanto menos se cuenta con los recursos interiores, tanto mayor parece la desconocida causa que produce el tormento.

[[wisdom-17-14]]
^14^ Durante aquella noche verdaderamente inerte, surgida de las profundidades del inerte Hades, en un mismo sueño sepultados,

[[wisdom-17-15]]
^15^ al invadirles un miedo repentino e inesperado, se vieron, de un lado, perseguidos de espectrales apariciones y, de otro, paralizados por el abandono de su alma.

[[wisdom-17-16]]
^16^ De este modo, cualquiera que en tal situación cayera, quedaba encarcelado, encerrado en aquella prisión sin hierros;

[[wisdom-17-17]]
^17^ ya fuera labrador o pastor, o bien un obrero dedicado en la soledad a su trabajo, sorprendido, soportaba la ineludible necesidad,

[[wisdom-17-18]]
^18^ atados todos como estaban por una misma cadena de tinieblas. El silbido del viento, el melodioso canto de las aves en la enramada, el ruido regulado del agua que corría impetuosa,

[[wisdom-17-19]]
^19^ el horrísimo fragor de rocas que caían de las alturas, la invisible carrera de animales que saltando pasaban, el rugido de las fieras más salvajes, el eco que devolvían las oquedades de las montañas, todo les aterrorizaba y les dejaba paralizados.

[[wisdom-17-20]]
^20^ Estaba entonces el mundo entero iluminado de luz esplendorosa, y, sin traba alguna, se ocupaba en sus quehaceres;

[[wisdom-17-21]]
^21^ sólo sobre ellos se extendía pesada noche, imagen de las tinieblas que les esperaban recibir. Aunque ellos a sí mismos se eran más pesados que las tinieblas.
[[wisdom-18]]
== Capítulo 18

[[wisdom-18-1]]
^1^ Entre tanto para tus santos había una grandísima luz. Los egipcios, que oían su voz aunque no distinguían su figura, les proclamaban dichosos por no haber padecido ellos también;

[[wisdom-18-2]]
^2^ les daban gracias porque agraviados no se vengaban y les pedían perdón por su conducta hostil.

[[wisdom-18-3]]
^3^ En vez de tinieblas, diste a los tuyos una columna de fuego, guía a través de rutas desconocidas, y sol inofensivo en su gloriosa emigración.

[[wisdom-18-4]]
^4^ Bien merecían verse de luz privados y prisioneros de tinieblas, los que en prisión tuvieron encerrados a aquellos hijos tuyos que habían de dar al mundo la luz incorruptible de la Ley.

[[wisdom-18-5]]
^5^ Por haber decretado matar a los niños de los santos, salvándose de los hijos expuestos uno tan sólo, les arrebataste en castigo la multitud de sus hijos y a ellos, a una, les hiciste perecer bajo la violencia de las aguas.

[[wisdom-18-6]]
^6^ Aquella noche fue previamente conocida por nuestros padres, para que se confortasen al reconocer firmes los juramentos en que creyeron.

[[wisdom-18-7]]
^7^ Tu pueblo esperaba a la vez la salvación de los justos y la destrucción de sus enemigos.

[[wisdom-18-8]]
^8^ Y, en efecto, con el castigo mismo de nuestros adversarios, nos colmaste de gloria llamándonos a ti.

[[wisdom-18-9]]
^9^ Los santos hijos de los buenos ofrecieron sacrificios en secreto y establecieron unánimes esta ley divina: que los santos correrían en común las mismas aventuras y riesgos; y, previamente, cantaron ya los himnos de los Padres.

[[wisdom-18-10]]
^10^ A estos cánticos respondía el discordante clamor de sus enemigos, se disfundían los lamentos de los que lloraban a sus hijos.

[[wisdom-18-11]]
^11^ Un mismo castigo alcanzaba al esclavo y al señor; el hombre del pueblo sufría la misma pena que el rey.

[[wisdom-18-12]]
^12^ Todos a la vez contaban con muertos innumerables abatidos por un mismo género de muerte. Los vivos no se bastaban a darles sepultura, como que, de un solo golpe, había caído la flor de su descendencia.

[[wisdom-18-13]]
^13^ Mantenidos en absoluta incredulidad por los artificios de la magia, acabaron por confesar, ante la muerte de sus primogénitos, que aquel pueblo era hijo de Dios.

[[wisdom-18-14]]
^14^ Cuando un sosegado silencio todo lo envolvía y la noche se encontraba en la mitad de su carrera,

[[wisdom-18-15]]
^15^ tu Palabra omnipotente, cual implacable guerrero, saltó del cielo, desde el trono real, en medio de una tierra condenada al exterminio. Empuñando como afilada espada tu decreto irrevocable,

[[wisdom-18-16]]
^16^ se detuvo y sembró la muerte por doquier; y tocaba el cielo mientras pisaba la tierra.

[[wisdom-18-17]]
^17^ Entonces, de repente, sueños y horribles visiones les sobresaltaron, les sobrevinieron terrores imprevistos.

[[wisdom-18-18]]
^18^ Aquí y allá tendidos, ya moribundos, daban a conocer la causa de su muerte,

[[wisdom-18-19]]
^19^ pues los sueños que les habían pertubado, se lo habían indicado a tiempo para que no muriesen sin saber la razón de su desgracia.

[[wisdom-18-20]]
^20^ También a los justos les alcanzó la prueba de la muerte; una multitud de ellos pereció en el desierto. Pero no duró la Cólera mucho tiempo,

[[wisdom-18-21]]
^21^ que pronto un hombre irreprochable salió en su defensa. Con las armas de su propio ministerio, la oración y el incienso expiatorio, se enfrentó a la ira y dio fin a la plaga, mostrando con ello que era en verdad siervo tuyo.

[[wisdom-18-22]]
^22^ Y venció a la Cólera no con la fuerza de su cuerpo, ni con el poder de las armas, sino que sometió con su palabra al que traía el castigo recordándole los juramentos hechos a los Padres y las alianzas.

[[wisdom-18-23]]
^23^ Cuando ya los muertos, unos sobre otros, yacían hacinados, frenó, interponiéndose, el avance de la Cólera y le cerró el camino hacia los que todavía vivían.

[[wisdom-18-24]]
^24^ Llevaba en su vestido talar el mundo entero, grabados en cuatro hileras de piedras los nombres gloriosos de los Padres y tu majestad en la diadema de su cabeza.

[[wisdom-18-25]]
^25^ Ante esto, el Exterminador cedió y se atemorizó; pues era suficiente la sola experiencia de tu Cólera.
[[wisdom-19]]
== Capítulo 19

[[wisdom-19-1]]
^1^ Pero, sobre los impíos, descargó hasta el fin una ira sin misericordia, pues Dios sabía de antemano lo que iban a tramar:

[[wisdom-19-2]]
^2^ que, luego de permitir marchar a su pueblo y apremiarle en su partida, mudando de parecer, saldrían a perseguirle.

[[wisdom-19-3]]
^3^ Ocupados estaban todavía en su duelo y lamentándose junto a las tumbas de sus muertos, cuando concibieron otro proyecto insensato: a los que con ruegos despacharon, dieron en perseguirlos como fugitivos.

[[wisdom-19-4]]
^4^ Una justa fatalidad los arrastraba a tales extremos y les borraba el recuerdo de los sucesos precedentes; así completarían con un nuevo castigo lo que a sus tormentos faltaba,

[[wisdom-19-5]]
^5^ así mientras tu pueblo gozaba de un viaje maravilloso, ellos encontrarían una muerte extraña.

[[wisdom-19-6]]
^6^ Pues para preservar a tus hijos de todo daño, la creación entera, obediente a tus órdenes, se rehízo de nuevo en su propia naturaleza.

[[wisdom-19-7]]
^7^ Se vio una nube proteger con su sombra el campamento, emerger del agua que la cubría una tierra enjuta, del mar Rojo un camino expedito, una verde llanura del oleaje impetuoso,

[[wisdom-19-8]]
^8^ por donde, formando un solo pueblo, pasaron los que tu mano protegía mientras contemplaban tan admirables prodigios.

[[wisdom-19-9]]
^9^ Como caballos se apacentaban, y retozaban como corderos alabándote a ti, Señor que los habías liberado.

[[wisdom-19-10]]
^10^ Recordaban todavía lo sucedido en su destierro, cómo, en vez de nacer los mosquitos de animales, los produjo la tierra, cómo, en vez de nacer las ranas de seres acuáticos, las vomitó el Río en abundancia.

[[wisdom-19-11]]
^11^ Más tarde, vieron además un modo nuevo de nacer las aves; cuando, llevados de la gula, pidieron manjares delicados,

[[wisdom-19-12]]
^12^ para satisfacerles, subieron codornices desde el mar.

[[wisdom-19-13]]
^13^ Mas sobre los pecadores cayeron los castigos, precedidos, como aviso, de la violencia de los rayos. Con toda justicia sufrían por sus propias maldades, por haber extremado su odio contra el extranjero.

[[wisdom-19-14]]
^14^ Otros no recibieron a unos desconocidos a su llegada. pero éstos redujeron a esclavitud a huéspedes bienhechores.

[[wisdom-19-15]]
^15^ Además habrá una visita para ellos porque recibieron hostilmente a los extranjeros...

[[wisdom-19-16]]
^16^ pero éstos, después de acoger con fiestas a los que ya participaban en los mismos derechos que ellos, los aplastaron con terribles trabajos.

[[wisdom-19-17]]
^17^ Por eso, también fueron éstos heridos de ceguera, como aquéllos a las puertas del justo, cuando, envueltos en inmensas tinieblas, buscaba cada uno el acceso a su puerta.

[[wisdom-19-18]]
^18^ Los elementos se adaptaron de una nueva manera entre sí como cambian la naturaleza del ritmo los sonidos en un salterio sin que cambie por eso su tonalidad, cosa que se puede deducir claramente examinando lo sucedido.

[[wisdom-19-19]]
^19^ Seres terrestres se tornaban acuáticos, y los que nadan pasaban a caminar sobre la tierra.

[[wisdom-19-20]]
^20^ El fuego aumentaba en el agua su fuerza natural y el agua olvidaba su poder de apagar.

[[wisdom-19-21]]
^21^ Por el contrario, las llamas no consumían las carnes de los endebles animales que sobre ellas caminaban, ni fundían aquel alimento divino, parecido a la escarcha, tan fácil de derretirse.

[[wisdom-19-22]]
^22^ En verdad, Señor, que en todo engrandeciste a tu pueblo y le glorificaste, y no te descuidaste en asistirle en todo tiempo y en todo lugar.
