[[sirach]]
= Eclesiástico

[[sirach-prologue]]
== Prólogo

^1^ Muchas e importantes lecciones se nos han transmitido
^2^ por la Ley, los Profetas y los otros que les han seguido,
^3^ por las cuales bien se debe encomiar a Israel por su instrucción y sabiduría.
^4^ Mas como es razón que no sólo los lectores se hagan sabios,
^5^ sino que puedan también estos amigos del saber ser útiles a los de fuera,
^6^ tanto de palabra como por escrito,
^7^ mi abuelo Jesús, después de haberse dado intensamente a la lectura
^8^ de la Ley,
^9^ los Profetas
^10^ y los otros libros de los antepasados,
^11^ y haber adquirido un gran dominio en ellos,
^12^ se propuso también él escribir algo en lo tocante a instrucción y sabiduría,
^13^ con ánimo de que los amigos del saber, lo aceptaran
^14^ y progresaran más todavía en la vida según la Ley.
^15^ Estáis, pues, invitados
^16^ a leerlo
^17^ con benevolencia y atención,
^18^ así como a mostrar indulgencia
^19^ allí donde se crea que, a pesar de nuestros denodados esfuerzos de interpretación,
^20^ no hemos podido acertar en alguna expresión.
^21^ Pues no tienen la misma fuerza
^22^ las cosas expresadas originalmente en hebreo que cuando se traducen a otra lengua.
^23^ Cosa que no sucede sólo en esto,
^24^ sino que también la misma Ley, los Profetas,
^25^ y los otros libros
^26^ presentan no pequeña diferencia respecto de lo que dice el original.
^27^ Fue, pues, en el año treinta y ocho del rey Evergetes
^28^ cuando, después de venir a Egipto y residir allí,
^29^ encontré una obra de no pequeña enseñanza,
^30^ y juzgué muy necesario aportar yo también algún interés y esfuerzo para traducir este libro.

[[sirach-1]]
== Capítulo 1

[[sirach-1-1]]
^1^ Toda sabiduría viene del Señor,

[[sirach-1-2]]
^2^ La arena de los mares, las gotas de la lluvia,

[[sirach-1-3]]
^3^ La altura del cielo, la anchura de la tierra,

[[sirach-1-4]]
^4^ Antes de todo estaba creada la Sabiduría,

[[sirach-1-6]]
^6^ La raíz de la sabiduría ¿a quién fue revelada?,

[[sirach-1-8]]
^8^ Sólo uno hay sabio, en extremo temible,

[[sirach-1-9]]
^9^ El Señor mismo la creó,

[[sirach-1-10]]
^10^ en toda carne conforme a su largueza,

[[sirach-1-11]]
^11^ Gloria es y orgullo el temor del Señor,

[[sirach-1-12]]
^12^ El temor del Señor recrea el corazón,

[[sirach-1-13]]
^13^ Para el que teme al Señor, todo irá bien al fin,

[[sirach-1-14]]
^14^ Principio de la sabiduría es temer al Señor,

[[sirach-1-15]]
^15^ Entre los hombres puso su nido, fundación eterna,

[[sirach-1-16]]
^16^ Plenitud de la sabiduría es temer al Señor,

[[sirach-1-17]]
^17^ Toda su casa colma de cosas deseables,

[[sirach-1-18]]
^18^ Corona de la sabiduría el temor del Señor,

[[sirach-1-19]]
^19^ (El la vio y la contó),

[[sirach-1-20]]
^20^ Raíz de la sabiduría es temer al Señor,

[[sirach-1-22]]
^22^ No puede justificarse la pasión del injusto,

[[sirach-1-23]]
^23^ Hasta su hora aguanta el que es paciente,

[[sirach-1-24]]
^24^ Hasta su hora oculta sus palabras,

[[sirach-1-25]]
^25^ En los tesoros de la sabiduría están las máximas de la

[[sirach-1-26]]
^26^ Si apeteces sabiduría, guarda los mandamientos,

[[sirach-1-27]]
^27^ Pues sabiduría y enseñanza es el temor del Señor;

[[sirach-1-28]]
^28^ No seas indócil al temor del Señor,

[[sirach-1-29]]
^29^ No seas hipócrita delante de los hombres,

[[sirach-1-30]]
^30^ No te exaltes a ti mismo, para no caer

[[sirach-2]]
== Capítulo 2

[[sirach-2-1]]
^1^ Hijo, si te llegas a servir al Señor,

[[sirach-2-2]]
^2^ Endereza tu corazón, manténte firme,

[[sirach-2-3]]
^3^ Adhiérete a él, no te separes,

[[sirach-2-4]]
^4^ Todo lo que te sobrevenga, acéptalo,

[[sirach-2-5]]
^5^ Porque en el fuego se purifica el oro,

[[sirach-2-6]]
^6^ Confíate a él, y él, a su vez, te cuidará,

[[sirach-2-7]]
^7^ Los que teméis al Señor, aguardad su misericordia,

[[sirach-2-8]]
^8^ Los que teméis al Señor, confiaos a él,

[[sirach-2-9]]
^9^ Los que teméis al Señor, esperad bienes,

[[sirach-2-10]]
^10^ Mirad a las generaciones de antaño y ved:

[[sirach-2-11]]
^11^ Que el Señor es compasivo y misericordioso,

[[sirach-2-12]]
^12^ ¡Ay de los corazones flacos y las manos caídas,

[[sirach-2-13]]
^13^ ¡Ay del corazón caído, que no tiene confianza!

[[sirach-2-14]]
^14^ ¡Ay de vosotros que perdisteis el aguante!

[[sirach-2-15]]
^15^ Los que temen al Señor no desobedecen sus palabras,

[[sirach-2-16]]
^16^ Los que temen al Señor buscan su agrado,

[[sirach-2-17]]
^17^ Los que temen al Señor tienen corazón dispuesto,

[[sirach-2-18]]
^18^ Caeremos en manos del Señor y no en manos de los hombres,

[[sirach-1-31]]
^31^ Mucha vigilia y ciencia he puesto en juego

[[sirach-1-32]]
^32^ durante este período,

[[sirach-1-33]]
^33^ hasta llegar a buen término y publicar el libro

[[sirach-1-34]]
^34^ para uso de aquellos que, en el extranjero, quieren ser amigos del saber,

[[sirach-1-35]]
^35^ y conformar sus costumbres a una vida de acuerdo con la Ley.


[[sirach-3]]
== Capítulo 3

[[sirach-3-1]]
^1^ A mí que soy vuestro padre escuchadme, hijos,

[[sirach-3-2]]
^2^ Pues el Señor glorifica al padre en los hijos,

[[sirach-3-3]]
^3^ Quien honra a su padre expía sus pecados;

[[sirach-3-4]]
^4^ como el que atesora es quien da gloria a su madre.

[[sirach-3-5]]
^5^ Quien honra a su padre recibirá contento de sus hijos,

[[sirach-3-6]]
^6^ Quien da gloria al padre vivirá largos días,

[[sirach-3-7]]
^7^ como a su Señor sirve a los que le engendraron.

[[sirach-3-8]]
^8^ En obra y palabra honra a tu padre,

[[sirach-3-9]]
^9^ Pues la bendición del padre afianza la casa de los hijos,

[[sirach-3-10]]
^10^ No te gloríes en la deshonra de tu padre,

[[sirach-3-11]]
^11^ Pues la gloria del hombre procede de la honra de su padre,

[[sirach-3-12]]
^12^ Hijo, cuida de tu padre en su vejez,

[[sirach-3-13]]
^13^ Aunque haya perdido la cabeza, sé indulgente,

[[sirach-3-14]]
^14^ Pues el servicio hecho al padre no quedará en olvido,

[[sirach-3-15]]
^15^ El día de tu tribulación se acordará El de ti;

[[sirach-3-16]]
^16^ Como blasfemo es el que abandona a su padre,

[[sirach-3-17]]
^17^ Haz, hijo, tus obras con dulzura,

[[sirach-3-18]]
^18^ Cuanto más grande seas, más debes humillarte,

[[sirach-3-20]]
^20^ Pues grande es el poderío del Señor,

[[sirach-3-21]]
^21^ No busques lo que te sobrepasa,

[[sirach-3-22]]
^22^ Lo que se te encomienda, eso medita,

[[sirach-3-23]]
^23^ En lo que excede a tus obras no te fatigues,

[[sirach-3-24]]
^24^ Que a muchos descaminaron sus prejuicios,

[[sirach-3-26]]
^26^ El corazón obstinado en mal acaba,

[[sirach-3-27]]
^27^ El corazón obstinado se carga de fatigas,

[[sirach-3-28]]
^28^ Para la adversidad del orgulloso no hay remedio,

[[sirach-3-29]]
^29^ El corazón del prudente medita los enigmas.

[[sirach-3-30]]
^30^ El agua apaga el fuego llameante,

[[sirach-3-31]]
^31^ Quien con favor responde prepara el porvenir,
[[sirach-4]]
== Capítulo 4

[[sirach-4-1]]
^1^ Hijo, no prives al pobre del sustento,

[[sirach-4-2]]
^2^ No entristezcas al que tiene hambre,

[[sirach-4-3]]
^3^ No te ensañes con el corazón exasperado,

[[sirach-4-4]]
^4^ No rechaces al suplicante atribulado,

[[sirach-4-5]]
^5^ No apartes del mendigo tus ojos,

[[sirach-4-6]]
^6^ Pues si maldice en la amargura de su alma,

[[sirach-4-7]]
^7^ Hazte querer de la asamblea,

[[sirach-4-8]]
^8^ Inclina al pobre tus oídos,

[[sirach-4-9]]
^9^ Arranca al oprimido de manos del opresor,

[[sirach-4-10]]
^10^ Sé para los huérfanos un padre,

[[sirach-4-11]]
^11^ La sabiduría a sus hijos exalta,

[[sirach-4-12]]
^12^ El que la ama, ama la vida,

[[sirach-4-13]]
^13^ El que la posee tendrá gloria en herencia,

[[sirach-4-14]]
^14^ Los que la sirven, rinden culto al Santo,

[[sirach-4-15]]
^15^ El que la escucha, juzgará a las naciones,

[[sirach-4-16]]
^16^ Si se confía a ella, la poseerá en herencia,

[[sirach-4-17]]
^17^ Pues, al principio, le llevará por recovecos,

[[sirach-4-18]]
^18^ mas luego le volverá al camino recto, le regocijará

[[sirach-4-19]]
^19^ Que si él se descarría, le abandonará,

[[sirach-4-20]]
^20^ Ten en cuenta el momento y guárdate del mal,

[[sirach-4-21]]
^21^ Porque hay una vergüenza que conduce al pecado,

[[sirach-4-22]]
^22^ No tengas miramientos en contra de ti mismo,

[[sirach-4-23]]
^23^ No contengas la palabra cuando pueda salvar,

[[sirach-4-24]]
^24^ Que la sabiduría se da a conocer en la palabra,

[[sirach-4-25]]
^25^ A la verdad no contradigas,

[[sirach-4-26]]
^26^ No te avergüences de confesar tus pecados,

[[sirach-4-27]]
^27^ No te aplanes ante el hombre insensato,

[[sirach-4-28]]
^28^ Hasta la muerte por la verdad combate,

[[sirach-4-29]]
^29^ No seas atrevido con tu lengua,

[[sirach-4-30]]
^30^ No seas un león en tu casa

[[sirach-4-31]]
^31^ No sea tu mano abierta para recibir,
[[sirach-5]]
== Capítulo 5

[[sirach-5-1]]
^1^ En tus riquezas no te apoyes

[[sirach-5-2]]
^2^ No te dejes arrastrar por tu deseo y tu fuerza

[[sirach-5-3]]
^3^ No digas: «¿Quién me domina a mí?»,

[[sirach-5-4]]
^4^ No digas: «Pequé, y ¿qué me ha pasado?»,

[[sirach-5-5]]
^5^ Del perdón no te sientas tan seguro

[[sirach-5-6]]
^6^ No digas: «Su compasión es grande,

[[sirach-5-7]]
^7^ No te tardes en volver al Señor,

[[sirach-5-8]]
^8^ No te apoyes en riquezas injustas,

[[sirach-5-9]]
^9^ No avientes a cualquier viento,

[[sirach-5-10]]
^10^ Manténte firme en tu pensamiento,

[[sirach-5-11]]
^11^ Sé pronto en escuchar,

[[sirach-5-12]]
^12^ Si sabes alguna cosa, a tu prójimo responde,

[[sirach-5-13]]
^13^ Gloria y deshonra caben en el hablar,

[[sirach-5-14]]
^14^ Que no se te llame maldiciente,

[[sirach-5-15]]
^15^ Ni en lo grande ni en lo pequeño yerres,
[[sirach-6]]
== Capítulo 6

[[sirach-6-1]]
^1^ Porque el mal nombre hereda confusión y oprobio;

[[sirach-6-2]]
^2^ No te engrías en el capricho de tu alma,

[[sirach-6-3]]
^3^ y tus hojas devores, y destruyas tus frutos,

[[sirach-6-4]]
^4^ El mal deseo pierde al que lo adquiere,

[[sirach-6-5]]
^5^ La boca amable multiplica sus amigos,

[[sirach-6-6]]
^6^ Sean muchos los que estén en paz contigo,

[[sirach-6-7]]
^7^ Si te echas un amigo, échatelo probado,

[[sirach-6-8]]
^8^ Porque hay amigo que lo es de ocasión,

[[sirach-6-9]]
^9^ Hay amigo que se vuelve enemigo,

[[sirach-6-10]]
^10^ Hay amigo que comparte tu mesa,

[[sirach-6-11]]
^11^ Cuando te vaya bien, será como otro tú,

[[sirach-6-12]]
^12^ mas si estás humillado, estará contra ti,

[[sirach-6-13]]
^13^ De tus enemigos apártate,

[[sirach-6-14]]
^14^ El amigo fiel es seguro refugio,

[[sirach-6-15]]
^15^ El amigo fiel no tiene precio,

[[sirach-6-16]]
^16^ El amigo fiel es remedio de vida,

[[sirach-6-17]]
^17^ El que teme al Señor endereza su amistad,

[[sirach-6-18]]
^18^ Hijo, desde tu juventud haz acopio de doctrina,

[[sirach-6-19]]
^19^ Como el labrador y el sembrador, trabájala,

[[sirach-6-20]]
^20^ Muy dura es para los ignorantes,

[[sirach-6-21]]
^21^ Como piedra de toque pesa sobre él,

[[sirach-6-22]]
^22^ Pues la sabiduría hace honor a su nombre,

[[sirach-6-23]]
^23^ Escucha, hijo, acoje mi criterio,

[[sirach-6-24]]
^24^ Mete tus pies en sus anillas,

[[sirach-6-25]]
^25^ Encorva tu espalda y cárgala,

[[sirach-6-26]]
^26^ Con toda tu alma acércate de ella,

[[sirach-6-27]]
^27^ Rastréala, búscala, y se te dará a conocer,

[[sirach-6-28]]
^28^ Porque al fin hallarás en ella el descanso,

[[sirach-6-29]]
^29^ Te serán sus anillas protección poderosa,

[[sirach-6-30]]
^30^ Pues adorno de oro es su yugo,

[[sirach-6-31]]
^31^ Como vestidura de gloria te la vestirás,

[[sirach-6-32]]
^32^ Si quieres, hijo, serás adoctrinado,

[[sirach-6-33]]
^33^ Si te gusta escuchar, aprenderás,

[[sirach-6-34]]
^34^ Acude a la reunión de los ancianos;

[[sirach-6-35]]
^35^ Anhela escuchar todo discurso que venga de Dios,

[[sirach-6-36]]
^36^ Si ves un hombre prudente, madruga a seguirle,

[[sirach-6-37]]
^37^ Medita en los preceptos del Señor,
[[sirach-7]]
== Capítulo 7

[[sirach-7-1]]
^1^ No hagas mal, y el mal no te dominará,

[[sirach-7-2]]
^2^ sepárate del injusto, y él se alejará de ti.

[[sirach-7-3]]
^3^ No siempres, hijo, en surcos de injusticia,

[[sirach-7-4]]
^4^ No pidas al Señor la preeminencia,

[[sirach-7-5]]
^5^ No te hagas el justo delante del Señor,

[[sirach-7-6]]
^6^ No te empeñes en llegar a ser juez,

[[sirach-7-7]]
^7^ No peques contra la asamblea de la ciudad,

[[sirach-7-8]]
^8^ En el pecado no te enredes dos veces,

[[sirach-7-9]]
^9^ No digas: «Pondrá él sus ojos en la abundancia de mis dones,

[[sirach-7-10]]
^10^ No seas en tu plegaria pusilánime,

[[sirach-7-11]]
^11^ No te burles del hombre que vive en aflicción,

[[sirach-7-12]]
^12^ No trames mentira contra tu hermano

[[sirach-7-13]]
^13^ Propónte no decir mentira alguna,

[[sirach-7-14]]
^14^ No seas hablador en la reunión de los ancianos,

[[sirach-7-15]]
^15^ No rehúyas el trabajo penoso,

[[sirach-7-16]]
^16^ No te incluyas en el grupo de los pecadores,

[[sirach-7-17]]
^17^ Humilla hondamente tu alma,

[[sirach-7-18]]
^18^ No cambies un amigo por dinero,

[[sirach-7-19]]
^19^ No faltes a la mujer sabia y buena,

[[sirach-7-20]]
^20^ No maltrates al criado que trabaja fielmente,

[[sirach-7-21]]
^21^ Al criado prudente ame tu alma,

[[sirach-7-22]]
^22^ ¿Tienes rebaños? Pásales revista;

[[sirach-7-23]]
^23^ ¿Tienes hijos? Adoctrínalos,

[[sirach-7-24]]
^24^ ¿Tienes hijas? Cuídate de ellas,

[[sirach-7-25]]
^25^ Casa a tu hija y habrás hecho una gran cosa,

[[sirach-7-26]]
^26^ ¿Tienes una mujer que te gusta? No la despidas,

[[sirach-7-27]]
^27^ Con todo tu corazón honra a tu padre,

[[sirach-7-28]]
^28^ Recuerda que por ellos has nacido,

[[sirach-7-29]]
^29^ Con toda tu alma reverencia al Señor,

[[sirach-7-30]]
^30^ Con todas tus fuerzas ama al que te hizo,

[[sirach-7-31]]
^31^ Teme al Señor y honra el sacerdote,

[[sirach-7-32]]
^32^ También al pobre tiéndele tu mano,

[[sirach-7-33]]
^33^ La gracia de tu dádiva llegue a todo viviente,

[[sirach-7-34]]
^34^ No te rezagues ante los que lloran,

[[sirach-7-35]]
^35^ No descuides visitar al enfermo,

[[sirach-7-36]]
^36^ En todas tus acciones ten presente tu fin,
[[sirach-8]]
== Capítulo 8

[[sirach-8-1]]
^1^ No disputes con hombre poderoso,

[[sirach-8-2]]
^2^ No discutas con hombre rico,

[[sirach-8-3]]
^3^ No disputes con hombre charlatán,

[[sirach-8-4]]
^4^ No bromees con el ineducado,

[[sirach-8-5]]
^5^ No reproches al hombre que se vuelve del pecado,

[[sirach-8-6]]
^6^ No deshonres al hombre en su vejez,

[[sirach-8-7]]
^7^ No te alegres de la muerte de nadie,

[[sirach-8-8]]
^8^ No dedeñes lo que narran los sabios,

[[sirach-8-9]]
^9^ No desprecies lo que cuentan los viejos,

[[sirach-8-10]]
^10^ No enciendas los carbones del pecador,

[[sirach-8-11]]
^11^ No te encares con el insolente,

[[sirach-8-12]]
^12^ No prestes al que puede más que tú;

[[sirach-8-13]]
^13^ No salgas fiador por encima de tus medios;

[[sirach-8-14]]
^14^ No entres en pleito con un juez,

[[sirach-8-15]]
^15^ Con el osado no te pongas en camino,

[[sirach-8-16]]
^16^ Con el colérico no entres en pelea,

[[sirach-8-17]]
^17^ No le pidas consejo al insensato,

[[sirach-8-18]]
^18^ Delante de un extraño no hagas cosa secreta,

[[sirach-8-19]]
^19^ No abras tu corazón a todo el mundo,
[[sirach-9]]
== Capítulo 9

[[sirach-9-1]]
^1^ No tengas celos de tu propia mujer,

[[sirach-9-2]]
^2^ No te entregues del todo a tu mujer,

[[sirach-9-3]]
^3^ No vayas al encuentro de una mujer prostituta,

[[sirach-9-4]]
^4^ Con cantadora no frecuentes el trato,

[[sirach-9-5]]
^5^ No te quedes mirando a doncella,

[[sirach-9-6]]
^6^ A prostitutas no te entregues,

[[sirach-9-7]]
^7^ No andes fisgando por los calles de la ciudad,

[[sirach-9-8]]
^8^ Aparta tu ojo de mujer hermosa,

[[sirach-9-9]]
^9^ Junto a mujer casada no te sientes jamás,

[[sirach-9-10]]
^10^ No abandones a un viejo amigo,

[[sirach-9-11]]
^11^ No envidies la gloria del pecador,

[[sirach-9-12]]
^12^ No asientas al éxito de los impíos,

[[sirach-9-13]]
^13^ Ponte lejos del hombre que es capaz de matar,

[[sirach-9-14]]
^14^ Cuando puedas acude a tu prójimo,

[[sirach-9-15]]
^15^ Con los inteligentes ten conversación,

[[sirach-9-16]]
^16^ Varones justos sean tus comensales,

[[sirach-9-17]]
^17^ Por la mano del artista la obra es alabada,

[[sirach-9-18]]
^18^ Temible en su ciudad el hombre charlatán,
[[sirach-10]]
== Capítulo 10

[[sirach-10-1]]
^1^ El juez sabio adoctrina a su pueblo,

[[sirach-10-2]]
^2^ Según el juez del pueblo, así serán sus ministros,

[[sirach-10-3]]
^3^ El rey sin instrucción arruinará a su pueblo,

[[sirach-10-4]]
^4^ En manos del Señor está el gobierno de la tierra,

[[sirach-10-5]]
^5^ En manos del Señor el recto camino del hombre,

[[sirach-10-6]]
^6^ Sea cual fuere su agravio, no guardes rencor al prójimo,

[[sirach-10-7]]
^7^ Odioso es al Señor y a los hombres el orgullo,

[[sirach-10-8]]
^8^ La soberanía pasa de una nación a otra,

[[sirach-10-9]]
^9^ ¿Por qué se enorgullece el que es tierra y ceniza?

[[sirach-10-10]]
^10^ La larga enfermedad deja perplejo al médico,

[[sirach-10-11]]
^11^ Y cuando un hombre muere,

[[sirach-10-12]]
^12^ El comienzo del orgullo del hombre es alejarse del Señor,

[[sirach-10-13]]
^13^ Que el comienzo del orgullo es el pecado,

[[sirach-10-14]]
^14^ Los tronos de los príncipes los volteó el Señor,

[[sirach-10-15]]
^15^ Las raíces de los orgullosos las arrancó el Señor,

[[sirach-10-16]]
^16^ Las comarcas de las naciones las arrasó el Señor,

[[sirach-10-17]]
^17^ Tomó algunos de ellos y los destruyó,

[[sirach-10-18]]
^18^ No se ha hecho para los hombres el orgullo,

[[sirach-10-19]]
^19^ ¿Qué raza es honorable? La del hombre.

[[sirach-10-20]]
^20^ En medio de sus hermanos es honorable el jefe,

[[sirach-10-22]]
^22^ Sean ricos, llenos de gloria o pobres,

[[sirach-10-23]]
^23^ No es justo despreciar al pobre inteligente,

[[sirach-10-24]]
^24^ Grande, juez y poderoso reciben honores,

[[sirach-10-25]]
^25^ Al siervo sabio los hombres libres sirven,

[[sirach-10-26]]
^26^ No te hagas el sabio cuando cumples tu obra,

[[sirach-10-27]]
^27^ Más vale el que trabaja y le sobra de todo

[[sirach-10-28]]
^28^ Hijo, gloríate con moderación,

[[sirach-10-29]]
^29^ Al que peca contra sí mismo, ¿quién le justificará?

[[sirach-10-30]]
^30^ El pobre es honrado por su saber,

[[sirach-10-31]]
^31^ Quien es estimado en la pobreza, ¡cuánto más en la riqueza!
[[sirach-11]]
== Capítulo 11

[[sirach-11-1]]
^1^ La sabiduría del humilde le hace erguir la cabeza,

[[sirach-11-2]]
^2^ No alabes nunca a un hombre por su buen parecer,

[[sirach-11-3]]
^3^ Pequeña entre los que vuelan es la abeja,

[[sirach-11-4]]
^4^ No te gloríes del manto que te envuelve,

[[sirach-11-5]]
^5^ Muchos tiranos se sentaron en el suelo,

[[sirach-11-6]]
^6^ Muchos poderosos fueron muy deshonrados,

[[sirach-11-7]]
^7^ Sin haberte informado no reprendas,

[[sirach-11-8]]
^8^ Sin haber escuchado no respondas

[[sirach-11-9]]
^9^ Por lo que no te incumbe no discutas,

[[sirach-11-10]]
^10^ Hijo, no te metas en múltiples asuntos,

[[sirach-11-11]]
^11^ Hay quien se agota, se fatiga y se apresura,

[[sirach-11-12]]
^12^ Hay quien es débil, necesitado de apoyo,

[[sirach-11-13]]
^13^ Levanta su cabeza,

[[sirach-11-14]]
^14^ Bienes y males, vida y muerte,

[[sirach-11-17]]
^17^ El don del Señor con los piadosos permanece,

[[sirach-11-18]]
^18^ Hay quien se hace rico a fuerza de engaño y avaricia,

[[sirach-11-19]]
^19^ cuando dice: «Ya he logrado reposo,

[[sirach-11-20]]
^20^ Manténte en tu quehacer y conságrate a él,

[[sirach-11-21]]
^21^ No te admires de las obras del pecador,

[[sirach-11-22]]
^22^ La bendición del Señor es la recompensa del piadoso,

[[sirach-11-23]]
^23^ No digas: «¿De qué he menester?

[[sirach-11-24]]
^24^ No digas: «Tengo bastante con ellos,

[[sirach-11-25]]
^25^ Día de bienes, olvido de males,

[[sirach-11-26]]
^26^ Que es fácil al Señor, el día de la muerte,

[[sirach-11-27]]
^27^ El mal de una hora el placer hace olvidar,

[[sirach-11-28]]
^28^ Antes del fin no llames feliz a nadie,

[[sirach-11-29]]
^29^ No metas a cualquiera en tu casa,

[[sirach-11-30]]
^30^ Perdiz cautiva en su jaula, tal es el corazón del orgulloso,

[[sirach-11-31]]
^31^ Cambiando el bien por el mal, está al acecho,

[[sirach-11-32]]
^32^ Con una chispa se enciende un brasero,

[[sirach-11-33]]
^33^ Guárdate del malvado, porque maquina el mal,

[[sirach-11-34]]
^34^ Mete en casa al extraño, y te traerá el desorden,
[[sirach-12]]
== Capítulo 12

[[sirach-12-1]]
^1^ Si haces el bien, mira a quién lo haces,

[[sirach-12-2]]
^2^ Haz bien al piadoso; hallarás recompensa,

[[sirach-12-3]]
^3^ No habrá bienes para el que en mal persiste,

[[sirach-12-4]]
^4^ Da al hombre piadoso,

[[sirach-12-5]]
^5^ Haz bien al humilde

[[sirach-12-6]]
^6^ Que también el Altísimo odia a los pecadores,

[[sirach-12-7]]
^7^ Da al hombre de bien,

[[sirach-12-8]]
^8^ No se demuestra en la prosperidad el amigo,

[[sirach-12-9]]
^9^ Cuando hay prosperidad, los enemigos se entristecen,

[[sirach-12-10]]
^10^ No confíes jamás en tu enemigo,

[[sirach-12-11]]
^11^ Aunque se haga el humilde y camine encorvado,

[[sirach-12-12]]
^12^ No le pongas junto a ti,

[[sirach-12-13]]
^13^ ¿Quién se compadecerá del encantador mordido de serpiente

[[sirach-12-14]]
^14^ Lo mismo le ocurre al que convive con el pecador

[[sirach-12-15]]
^15^ Una hora aguantará contigo,

[[sirach-12-16]]
^16^ En sus labios pone dulzura el enemigo,

[[sirach-12-17]]
^17^ Si los males te visitan, primero que tú le encontrarás allí,

[[sirach-12-18]]
^18^ Meneará su cabeza, batirá palmas,
[[sirach-13]]
== Capítulo 13

[[sirach-13-1]]
^1^ El que toca la pez, se mancha,

[[sirach-13-2]]
^2^ No tomes sobre ti carga pesada,

[[sirach-13-3]]
^3^ El rico agravia y encima se envalentona,

[[sirach-13-4]]
^4^ Si le eres útil, se servirá de ti,

[[sirach-13-5]]
^5^ Si tienes algo, vivirá contigo,

[[sirach-13-6]]
^6^ ¿Ha menester de ti? Tratará de engañarte,

[[sirach-13-7]]
^7^ Te avergonzará en sus festines,

[[sirach-13-8]]
^8^ Guárdate de dejarte engañar,

[[sirach-13-9]]
^9^ Cuando te llame un poderoso, quédate a distancia,

[[sirach-13-10]]
^10^ No te presentes por ti mismo, no sea que te rechace,

[[sirach-13-11]]
^11^ No pretendas hablar con él de igual a igual,

[[sirach-13-12]]
^12^ Despiadado es quien no guarda tus palabras,

[[sirach-13-13]]
^13^ Observa y ponte bien en guardia,

[[sirach-13-15]]
^15^ Todo viviente ama a su semejante,

[[sirach-13-16]]
^16^ Todo animal según su especie se une,

[[sirach-13-17]]
^17^ ¿Cómo podrá convivir lobo con cordero?

[[sirach-13-18]]
^18^ ¿Qué paz puede tener la hiena con el perro?

[[sirach-13-19]]
^19^ Caza de leones son los onagros en el desierto,

[[sirach-13-20]]
^20^ Abonimación para el orgulloso es la humilidad,

[[sirach-13-21]]
^21^ El rico que vacila es sostenido por sus amigos,

[[sirach-13-22]]
^22^ Cuando el rico resbala, muchos le toman en sus brazos,

[[sirach-13-23]]
^23^ Habla el rico, y todos se callan,

[[sirach-13-24]]
^24^ Buena es la riqueza en la que no hay pecado,

[[sirach-13-25]]
^25^ El corazón del hombre modela su rostro

[[sirach-13-26]]
^26^ Signo de un corazón dichoso es un rostro alegre,
[[sirach-14]]
== Capítulo 14

[[sirach-14-1]]
^1^ Feliz el hombre que no se ha deslizado con su boca,

[[sirach-14-2]]
^2^ Feliz aquel a quien su conciencia no reprocha,

[[sirach-14-3]]
^3^ Para el hombre mezquino no es buena la riqueza,

[[sirach-14-4]]
^4^ Quien amontona a expensas de sí mismo, para otros amontona,

[[sirach-14-5]]
^5^ El que es malo para sí, ¿para quién será bueno?

[[sirach-14-6]]
^6^ Nadie peor que el que se tortura a sí mismo,

[[sirach-14-7]]
^7^ Aun si llega a hacer el bien, lo hace por descuido,

[[sirach-14-8]]
^8^ Malo es el de ojo envidioso,

[[sirach-14-9]]
^9^ El ojo del avaro no se satisface con su suerte,

[[sirach-14-10]]
^10^ El ojo malo se alampa por el pan,

[[sirach-14-11]]
^11^ Hijo, trátate bien, conforme a lo que tengas,

[[sirach-14-12]]
^12^ Recuerda que la muerte no se tardará,

[[sirach-14-13]]
^13^ Antes de morir, haz el bien a tu amigo,

[[sirach-14-14]]
^14^ No te prives de pasarte un buen día,

[[sirach-14-15]]
^15^ ¿No dejarás a otro el fruto de tus trabajos

[[sirach-14-16]]
^16^ Da y recibe, y recrea tu alma,

[[sirach-14-17]]
^17^ Toda carne como un vestido envejece,

[[sirach-14-18]]
^18^ Lo mismo que las hojas sobre árbol tupido,

[[sirach-14-19]]
^19^ Toda obra corruptible desaparece,

[[sirach-14-20]]
^20^ Feliz el hombre que se ejercita en la sabiduría,

[[sirach-14-21]]
^21^ que medita sus caminos en su corazón,

[[sirach-14-22]]
^22^ Sale en su busca como el que sigue el rastro,

[[sirach-14-23]]
^23^ Se asoma a sus ventanas,

[[sirach-14-24]]
^24^ Acampa muy cerca de su casa,

[[sirach-14-25]]
^25^ Monta su tienda junto a ella,

[[sirach-14-26]]
^26^ Pone sus hijos a su abrigo,

[[sirach-14-27]]
^27^ Por ella es protegido del calor,
[[sirach-15]]
== Capítulo 15

[[sirach-15-1]]
^1^ Así hace el que teme al Señor,

[[sirach-15-2]]
^2^ Como una madre le sale ella al encuentro,

[[sirach-15-3]]
^3^ Le alimenta con pan de inteligencia,

[[sirach-15-4]]
^4^ Se apoya él en ella y no se dobla,

[[sirach-15-5]]
^5^ Ella le exalta por encima de sus prójimos,

[[sirach-15-6]]
^6^ Contento y corona de gloria encuentra él,

[[sirach-15-7]]
^7^ Jamás la lograrán los insensatos,

[[sirach-15-8]]
^8^ Lejos está del orgullo,

[[sirach-15-9]]
^9^ No cabe la alabanza en boca del pecador,

[[sirach-15-10]]
^10^ Que en la sabiduría se expresa la alabanza,

[[sirach-15-11]]
^11^ No digas: «Por el Señor me he apartado»,

[[sirach-15-12]]
^12^ No digas: «El me ha extraviado»,

[[sirach-15-13]]
^13^ Toda abominación odia el Señor,

[[sirach-15-14]]
^14^ El fue quien al principio hizo al hombre,

[[sirach-15-15]]
^15^ Si tú quieres, guardarás los mandamientos,

[[sirach-15-16]]
^16^ El te ha puesto delante fuego y agua,

[[sirach-15-17]]
^17^ Ante los hombres la vida está y la muerte,

[[sirach-15-18]]
^18^ Que grande es la sabiduría del Señor,

[[sirach-15-19]]
^19^ Sus ojos están sobre los que le temen,

[[sirach-15-20]]
^20^ A nadie ha mandado ser impío,
[[sirach-16]]
== Capítulo 16

[[sirach-16-1]]
^1^ No desees multitud de hijos malvados,

[[sirach-16-2]]
^2^ Aunque sean muchos, no te goces en ellos,

[[sirach-16-3]]
^3^ No pongas en su vida tu confianza,

[[sirach-16-4]]
^4^ Pues uno solo inteligente poblará una ciudad

[[sirach-16-5]]
^5^ Muchas cosas así han visto mis ojos,

[[sirach-16-6]]
^6^ En la reunión de los pecadores prende el fuego,

[[sirach-16-7]]
^7^ No perdonó él a los antiguos gigantes

[[sirach-16-8]]
^8^ No pasó por alto al vecindario de Lot,

[[sirach-16-9]]
^9^ No se apiadó de la nación perdida,

[[sirach-16-10]]
^10^ Igual trató a los seiscientos mil de a pie

[[sirach-16-11]]
^11^ Aunque fuera uno solo el de dura cerviz,

[[sirach-16-12]]
^12^ Tan grande como su misericordia es su severidad,

[[sirach-16-13]]
^13^ No escapará el pecador con su rapiña,

[[sirach-16-14]]
^14^ Para toda limosna tiene él un sitio,

[[sirach-16-17]]
^17^ No digas: «Del Señor me esconderé,

[[sirach-16-18]]
^18^ Mira, el cielo, y el cielo de los cielos,

[[sirach-16-19]]
^19^ A una los montes y los cimientos de la tierra

[[sirach-16-20]]
^20^ Mas en todo esto no piensa el corazón del hombre,

[[sirach-16-21]]
^21^ Hay tempestad que no ve el hombre,

[[sirach-16-22]]
^22^ «Las obras de la justicia, ¿quién las anuncia?

[[sirach-16-23]]
^23^ Esto piensa el ruin de corazón;

[[sirach-16-24]]
^24^ Escúchame, hijo, y el saber aprende,

[[sirach-16-25]]
^25^ Con mesura te revelaré la doctrina,

[[sirach-16-26]]
^26^ Cuando creó el Señor sus obras desde el principio,

[[sirach-16-27]]
^27^ Ordenó para la eternidad sus obras,

[[sirach-16-28]]
^28^ Ninguna choca con otra,

[[sirach-16-29]]
^29^ Después de esto el Señor miró a la tierra,

[[sirach-16-30]]
^30^ De todo ser viviente cubrió su faz,
[[sirach-17]]
== Capítulo 17

[[sirach-17-1]]
^1^ De la tierra creó el Señor al hombre,

[[sirach-17-2]]
^2^ Días contados le dio y tiempo fijo,

[[sirach-17-3]]
^3^ De una fuerza como la suya los revistió,

[[sirach-17-4]]
^4^ Sobre toda carne impuso su temor

[[sirach-17-6]]
^6^ Les formó lengua, ojos,

[[sirach-17-7]]
^7^ De saber e inteligencia los llenó,

[[sirach-17-8]]
^8^ Puso su ojo en sus corazones,

[[sirach-17-10]]
^10^ Por eso su santo nombre alabarán,

[[sirach-17-11]]
^11^ Aun les añadió el saber,

[[sirach-17-12]]
^12^ Alianza eterna estableció con ellos,

[[sirach-17-13]]
^13^ Los ojos de ellos vieron la grandeza de su gloria,

[[sirach-17-14]]
^14^ Y les dijo: «Guardaos de toda iniquidad»,

[[sirach-17-15]]
^15^ Sus caminos están ante él en todo tiempo,

[[sirach-17-17]]
^17^ A cada nación asignó un jefe,

[[sirach-17-19]]
^19^ Todas sus obras están ante él, igual que el sol,

[[sirach-17-20]]
^20^ No se le ocultan sus iniquidades,

[[sirach-17-22]]
^22^ La limosna del hombre es como un sello para él,

[[sirach-17-23]]
^23^ Después se levantará y les retribuirá,

[[sirach-17-24]]
^24^ Pero a los que se arrepienten les concede retorno,

[[sirach-17-25]]
^25^ Conviértete al Señor y deja tus pecados,

[[sirach-17-26]]
^26^ Vuélvete al Altísimo y apártate de la injusticia,

[[sirach-17-27]]
^27^ ¿Quién en el seol alabará al Altísimo

[[sirach-17-28]]
^28^ No hay alabanza que venga de muerto, como de quien no existe;

[[sirach-17-29]]
^29^ ¡Qué grande es la misericordia del Señor,

[[sirach-17-30]]
^30^ Pues no todo puede estar en poder de los hombres,

[[sirach-17-31]]
^31^ ¿Qué hay más luminoso que el sol? Con todo, desaparece.

[[sirach-17-32]]
^32^ Al ejército de lo alto de los cielos pasa él revista,
[[sirach-18]]
== Capítulo 18

[[sirach-18-1]]
^1^ El que vive eternamente lo creó todo por igual,

[[sirach-18-2]]
^2^ sólo el Señor será llamado justo.

[[sirach-18-4]]
^4^ A nadie dio poder de proclamar sus obras,

[[sirach-18-5]]
^5^ El poder de su majestad, ¿quién lo calculará?

[[sirach-18-6]]
^6^ Nada hay que quitar, nada que añadir,

[[sirach-18-7]]
^7^ Cuando el hombre cree acabar, comienza entonces,

[[sirach-18-8]]
^8^ ¿Qué es el hombre? ¿para qué sirve?

[[sirach-18-9]]
^9^ El número de los días del hombre

[[sirach-18-10]]
^10^ Como gota de agua del mar, como grano de arena,

[[sirach-18-11]]
^11^ Por eso el Señor es paciente con ellos,

[[sirach-18-12]]
^12^ El ve y sabe que su fin es miserable,

[[sirach-18-13]]
^13^ La misericordia del hombre sólo alcanza a su prójimo,

[[sirach-18-14]]
^14^ Tiene piedad de los que acogen la instrucción,

[[sirach-18-15]]
^15^ Hijo, con tus beneficios no mezcles el reproche

[[sirach-18-16]]
^16^ ¿No aplaca el rocío el viento ardiente?

[[sirach-18-17]]
^17^ ¿No ves que la palabra es más que un buen presente?

[[sirach-18-18]]
^18^ El necio aun sin dar hace afrenta,

[[sirach-18-19]]
^19^ Antes de hablar infórmate,

[[sirach-18-20]]
^20^ Antes de juzgar examínate a ti mismo,

[[sirach-18-21]]
^21^ Antes de estar enfermo humíllate,

[[sirach-18-22]]
^22^ Nada te impida cumplir tu voto en el momento dado,

[[sirach-18-23]]
^23^ Antes de hacer un voto prepárate;

[[sirach-18-24]]
^24^ Acuérdate de la ira de los últimos días,

[[sirach-18-25]]
^25^ En tiempo de abundancia recuerda el tiempo de hambre,

[[sirach-18-26]]
^26^ De la mañana a la tarde corre el tiempo,

[[sirach-18-27]]
^27^ El hombre sabio es precavido en todo,

[[sirach-18-28]]
^28^ Todo hombre prudente conoce la sabiduría,

[[sirach-18-29]]
^29^ Los prudentes en palabras hacen sabiduría

[[sirach-18-30]]
^30^ No vayas detrás de tus pasiones,

[[sirach-18-31]]
^31^ Si te consientes en todos los deseos,

[[sirach-18-32]]
^32^ No te complazcas en la buena vida,

[[sirach-18-33]]
^33^ No te empobrezcas festejando con dinero prestado,
[[sirach-19]]
== Capítulo 19

[[sirach-19-1]]
^1^ Un obrero bebedor nunca se enriquecerá,

[[sirach-19-2]]
^2^ Vino y mujeres pervierten a los inteligentes,

[[sirach-19-3]]
^3^ De larvas y gusanos será herencia,

[[sirach-19-4]]
^4^ Quien se confía enseguida, ligero es de corazón,

[[sirach-19-5]]
^5^ El que se regodea en el mal será condenado,

[[sirach-19-6]]
^6^ el que odia la verborrea escapará al mal.

[[sirach-19-7]]
^7^ No repitas nunca lo que se dice,

[[sirach-19-8]]
^8^ Ni a amigo ni a enemigo cuentes nada,

[[sirach-19-9]]
^9^ Porque te escucharía y se guardaría de ti,

[[sirach-19-10]]
^10^ ¿Has oído algo? ¡Quede muerto en ti!

[[sirach-19-11]]
^11^ Por una palabra oída ya está el necio en dolores,

[[sirach-19-12]]
^12^ Una flecha clavada en el muslo,

[[sirach-19-13]]
^13^ Interoga a tu amigo: quizá no haya hecho nada,

[[sirach-19-14]]
^14^ Interroga a tu prójimo: quizá no ha dicho nada,

[[sirach-19-15]]
^15^ Interroga a tu amigo: que hay calumnia a menudo,

[[sirach-19-16]]
^16^ A veces se resbala uno sin querer,

[[sirach-19-17]]
^17^ Interroga a tu prójimo antes de amenazarle,

[[sirach-19-20]]
^20^ Toda sabiduría es temor del Señor,

[[sirach-19-22]]
^22^ Mas no es sabiduría el conocimiento del mal,

[[sirach-19-23]]
^23^ Hay un saberlo todo que es abominación,

[[sirach-19-24]]
^24^ Más vale ser vacío de inteligencia y lleno de temor,

[[sirach-19-25]]
^25^ Hay un saberlo todo que sirve a la injusticia,

[[sirach-19-26]]
^26^ Hay malhechor que anda encorvado por el tedio,

[[sirach-19-27]]
^27^ tapándose la cara, haciéndose el sordo,

[[sirach-19-28]]
^28^ Si por su escasa fuerza no se atreve a pecar,

[[sirach-19-29]]
^29^ Por la mirada se reconoce al hombre,

[[sirach-19-30]]
^30^ El atuendo del hombre, la risa de sus dientes,
[[sirach-20]]
== Capítulo 20

[[sirach-20-1]]
^1^ Hay reprensión intempestiva,

[[sirach-20-2]]
^2^ ¡Cuánto mejor reprender que estar airado!

[[sirach-20-3]]
^3^ El que se acusa de su falta evita la pena.

[[sirach-20-4]]
^4^ Como pasión de eunuco por desflorar a una moza,

[[sirach-20-5]]
^5^ Hay silencioso tenido por sabio,

[[sirach-20-6]]
^6^ Hay quien se calla por no tener respuesta,

[[sirach-20-7]]
^7^ El sabio guarda silencio hasta su hora,

[[sirach-20-8]]
^8^ El desmedido en palabras se hace abominable,

[[sirach-20-9]]
^9^ Hay quien encuentra fortuna en la desgracia,

[[sirach-20-10]]
^10^ Hay dádiva que no te da provecho,

[[sirach-20-11]]
^11^ Hay postración causada por la gloria,

[[sirach-20-12]]
^12^ Hay quien compra mucho con poco dinero,

[[sirach-20-13]]
^13^ Por sus palabras se hace amable el sabio,

[[sirach-20-14]]
^14^ El don del insensato no te sirve de nada,

[[sirach-20-15]]
^15^ da poco y echa en cara mucho,

[[sirach-20-16]]
^16^ Dice el necio: «No tengo ni un amigo,

[[sirach-20-17]]
^17^ los que comen mi pan tienen lengua insolente».

[[sirach-20-18]]
^18^ Mejor es resbalar en empredado que resbalar con la lengua,

[[sirach-20-19]]
^19^ Hombre sin gracia es cuento inoportuno

[[sirach-20-20]]
^20^ De boca de necio no se acepta el proverbio,

[[sirach-20-21]]
^21^ Hay quien no puede pecar por indigencia:

[[sirach-20-22]]
^22^ Hay quien se pierde a sí mismo por vergüenza,

[[sirach-20-23]]
^23^ Hay quien por timidez hace promesas a su amigo,

[[sirach-20-24]]
^24^ Gran baldón para un hombre la mentira

[[sirach-20-25]]
^25^ Es preferible un ladrón que el que persiste en la mentira,

[[sirach-20-26]]
^26^ El hábito de mentiroso es una deshonra,

[[sirach-20-27]]
^27^ Por sus palabras el sabio se hace grande,

[[sirach-20-28]]
^28^ El que cultiva la tierra llena hasta arriba su granero,

[[sirach-20-29]]
^29^ Presentes y regalos ciegan los ojos de los sabios,

[[sirach-20-30]]
^30^ Sabiduría escondida y tesoro invisible,

[[sirach-20-31]]
^31^ Más vale hombre que oculta su necedad,
[[sirach-21]]
== Capítulo 21

[[sirach-21-1]]
^1^ Hijo, ¿has pecado? No lo vuelvas a hacer,

[[sirach-21-2]]
^2^ Como de serpiente huye del pecado,

[[sirach-21-3]]
^3^ Como espada de dos filos es toda iniquidad,

[[sirach-21-4]]
^4^ El terror y la violencia arrasan la riqueza,

[[sirach-21-5]]
^5^ La oración del pobre va de su boca a los oídos de Dios,

[[sirach-21-6]]
^6^ El que odia la reprensión sigue las huellas del pecador,

[[sirach-21-7]]
^7^ De lejos se conoce al charlatán,

[[sirach-21-8]]
^8^ Quien edifica su casa con dinero ajeno

[[sirach-21-9]]
^9^ Estopa hacinada es la reunión de los sin ley,

[[sirach-21-10]]
^10^ El camino de los pecadores está bien enlosado,

[[sirach-21-11]]
^11^ El que guarda la Ley controla sus ideas,

[[sirach-21-12]]
^12^ No alcanzará doctrina quien no es habilidoso,

[[sirach-21-13]]
^13^ La ciencia del sabio crecerá como una inundación,

[[sirach-21-14]]
^14^ El interior del necio es como un vaso roto,

[[sirach-21-15]]
^15^ Si un hombre de saber oye palabra sabia,

[[sirach-21-16]]
^16^ El relato del necio es como fardo en el camino,

[[sirach-21-17]]
^17^ La boca del sensato es buscada en la asamblea,

[[sirach-21-18]]
^18^ Como casa en ruinas, así la sabiduría del necio,

[[sirach-21-19]]
^19^ Cadenas en los pies, es la educación para el mentecato,

[[sirach-21-20]]
^20^ El necio, cuando ríe, lo hace a carcajadas,

[[sirach-21-21]]
^21^ Adorno de oro es la educación para el sensato,

[[sirach-21-22]]
^22^ El pie del necio entra rápido en la casa,

[[sirach-21-23]]
^23^ Desde la puerta el insensato fisga el interior,

[[sirach-21-24]]
^24^ Es falta de educación escuchar a la puerta,

[[sirach-21-25]]
^25^ Los labios de los habladores repiten las palabras ajenas,

[[sirach-21-26]]
^26^ En la boca de los necios está su corazón,

[[sirach-21-27]]
^27^ Cuando el impío maldice a Satanás,

[[sirach-21-28]]
^28^ El murmurador mancha su propia alma,
[[sirach-22]]
== Capítulo 22

[[sirach-22-1]]
^1^ A una piedra sucia se parece el perezoso,

[[sirach-22-2]]
^2^ Bola de excrementos es el perezoso,

[[sirach-22-3]]
^3^ Es vergüenza de un padre tener un hijo ineducado,

[[sirach-22-4]]
^4^ Para la hija prudente la herencia es su marido,

[[sirach-22-5]]
^5^ La hija insolente es la vergüenza del padre y del marido,

[[sirach-22-6]]
^6^ Música en duelo es un relato inoportuno,

[[sirach-22-9]]
^9^ Como pegar cascotes es enseñar al necio,

[[sirach-22-10]]
^10^ Conversar con el necio es conversar con un dormido;

[[sirach-22-11]]
^11^ Llora al muerto, pues la luz le abandonó,

[[sirach-22-12]]
^12^ El duelo por un muerto dura siete días,

[[sirach-22-13]]
^13^ Con el insensato no multipliques las palabras,

[[sirach-22-14]]
^14^ ¿Qué hay más pesado que el plomo?

[[sirach-22-15]]
^15^ Arena, sal, o una bola de hierro

[[sirach-22-16]]
^16^ El maderamen bien trabado de una casa

[[sirach-22-17]]
^17^ Corazón apoyado en reflexión prudente

[[sirach-22-18]]
^18^ Estacas plantadas en altura

[[sirach-22-19]]
^19^ Quien hiere el ojo hace correr las lágrimas,

[[sirach-22-20]]
^20^ Quien tira una piedra a un pájaro, lo ahuyenta,

[[sirach-22-21]]
^21^ Si has sacado la espada contra tu amigo,

[[sirach-22-22]]
^22^ si contra tu amigo has abierto la boca,

[[sirach-22-23]]
^23^ Gana la confianza de tu prójimo en la pobreza,

[[sirach-22-24]]
^24^ Antes del fuego sale vapor del horno y humo,

[[sirach-22-25]]
^25^ No me avergonzaré yo de proteger a un amigo,

[[sirach-22-26]]
^26^ y si por su causa me ocurre algún mal,

[[sirach-22-27]]
^27^ ¿Quién pondrá guardia a mi boca,
[[sirach-23]]
== Capítulo 23

[[sirach-23-1]]
^1^ Oh Señor, padre y dueño de mi vida,

[[sirach-23-2]]
^2^ ¿Quién aplicará el látigo a mis pensamientos,

[[sirach-23-3]]
^3^ No sea que mis yerros aumenten,

[[sirach-23-4]]
^4^ Señor, padre y Dios de mi vida,

[[sirach-23-5]]
^5^ aparta de mí la pasión.

[[sirach-23-6]]
^6^ Que el apetito sensual y la lujuria no se apoderen de mí,

[[sirach-23-7]]
^7^ La instrucción de mi boca escuchad, hijos,

[[sirach-23-8]]
^8^ Por sus labios es atrapado el pecador,

[[sirach-23-9]]
^9^ Al juramento no acostumbres tu boca,

[[sirach-23-10]]
^10^ Porque, igual que un criado vigilado de continuo

[[sirach-23-11]]
^11^ Hombre muy jurador, lleno está de iniquidad,

[[sirach-23-12]]
^12^ Hay un lenguaje que equivale a la muerte,

[[sirach-23-13]]
^13^ A la baja grosería no habitúes tu boca,

[[sirach-23-14]]
^14^ Acuérdate de tu padre y de tu madre,

[[sirach-23-15]]
^15^ El hombre habituado a palabras ultrajantes

[[sirach-23-16]]
^16^ Dos clases de gente multiplican los pecados,

[[sirach-23-17]]
^17^ El alma ardiente como fuego encendido,

[[sirach-23-18]]
^18^ El hombre que su propio lecho viola

[[sirach-23-19]]
^19^ lo que teme son los ojos de los hombres;

[[sirach-23-20]]
^20^ Antes de ser creadas, todas las cosas le eran conocidas,

[[sirach-23-21]]
^21^ En las plazas de la ciudad será éste castigado,

[[sirach-23-22]]
^22^ Así también la mujer que ha sido infiel a su marido

[[sirach-23-23]]
^23^ Primero, ha desobedecido a la ley del Altísimo, segundo, ha

[[sirach-23-24]]
^24^ Esta será llevada a la asamblea,

[[sirach-23-25]]
^25^ Sus hijos no echarán raíces,

[[sirach-23-26]]
^26^ Dejará un recuerdo que será maldito,

[[sirach-23-27]]
^27^ Y reconocerán los que queden
[[sirach-24]]
== Capítulo 24

[[sirach-24-1]]
^1^ La sabiduría hace su propio elogio,

[[sirach-24-2]]
^2^ En la asamblea del Altísimo abre su boca,

[[sirach-24-3]]
^3^ «Yo salí de la boca del Altísimo,

[[sirach-24-4]]
^4^ Yo levanté mi tienda en las alturas,

[[sirach-24-5]]
^5^ Sola recorrí la redondez del cielo,

[[sirach-24-6]]
^6^ Las ondas del mar, la tierra entera,

[[sirach-24-7]]
^7^ Entre todas estas cosas buscaba reposo,

[[sirach-24-8]]
^8^ Entonces me dio orden el creador del universo,

[[sirach-24-9]]
^9^ Antes de los siglos, desde el principio, me creó,

[[sirach-24-10]]
^10^ En la Tienda Santa, en su presencia, he ejercido el

[[sirach-24-11]]
^11^ en la ciudad amada me ha hecho él reposar ,

[[sirach-24-12]]
^12^ He arraigado en un pueblo glorioso,

[[sirach-24-13]]
^13^ Como cedro me he elevado en el Líbano,

[[sirach-24-14]]
^14^ Como palmera me he elevado en Engadí,

[[sirach-24-15]]
^15^ Cual cinamomo y aspálato aromático he dado fragancia,

[[sirach-24-16]]
^16^ Cual terebinto he alargado mis ramas,

[[sirach-24-17]]
^17^ Como la vid he hecho germinar la gracia, y mis flores son

[[sirach-24-19]]
^19^ Venid a mí los que me deseáis,

[[sirach-24-20]]
^20^ Que mi recuerdo es más dulce que la miel,

[[sirach-24-21]]
^21^ Los que me comen quedan aún con hambre de mí,

[[sirach-24-22]]
^22^ Quien me obedece a mí, no queda avergonzado,

[[sirach-24-23]]
^23^ Todo esto es el libro de la alianza del Dios Altísimo,

[[sirach-24-25]]
^25^ la que inunda de sabiduría como el Pisón,

[[sirach-24-26]]
^26^ la que desborda inteligencia como el Eufrates,

[[sirach-24-27]]
^27^ la que rebosa doctrina como el Nilo,

[[sirach-24-28]]
^28^ El primero no ha acabado aún de conocerla,

[[sirach-24-29]]
^29^ Porque es más vasto que el mar su pensamiento,

[[sirach-24-30]]
^30^ Y yo, como canal derivado de un río,

[[sirach-24-31]]
^31^ y dije: «Voy a regar mi huerto,

[[sirach-24-32]]
^32^ Aún haré lucir como la aurora la instrucción,

[[sirach-24-33]]
^33^ Aún derramaré la enseñanza como profecía,

[[sirach-24-34]]
^34^ Ved que no sólo para mí me he fatigado,
[[sirach-25]]
== Capítulo 25

[[sirach-25-1]]
^1^ Con tres cosas me adorno y me presento bella

[[sirach-25-2]]
^2^ Mas tres clases de gente odia mi alma,

[[sirach-25-3]]
^3^ Si en la juventud no has hecho acopio,

[[sirach-25-4]]
^4^ ¡Qué bien sienta el juicio a las canas,

[[sirach-25-5]]
^5^ ¡Qué bien parece la sabiduría en los viejos,

[[sirach-25-6]]
^6^ Corona de los viejos es la mucha experiencia,

[[sirach-25-7]]
^7^ Nueve cosas que imagino tengo por felices en mi corazón,

[[sirach-25-8]]
^8^ Feliz quien vive con mujer juiciosa,

[[sirach-25-9]]
^9^ feliz quien ha encontrado la prudencia,

[[sirach-25-10]]
^10^ ¡Qué grande el que ha encontrado la sabiduría!

[[sirach-25-11]]
^11^ El temor del Señor sobresale por encima de todo,

[[sirach-25-13]]
^13^ ¡Cualquier herida, pero no herida del corazón!

[[sirach-25-14]]
^14^ ¡Cualquier desgracia, pero no desgracia de parte de

[[sirach-25-15]]
^15^ No hay veneno como veneno de serpiente,

[[sirach-25-16]]
^16^ Prefiero convivir con león o dragón

[[sirach-25-17]]
^17^ La maldad de la mujer desfigura su semblante,

[[sirach-25-18]]
^18^ En medio de sus vecinos se sienta su marido,

[[sirach-25-19]]
^19^ Toda malicia es poca junto a la malicia de mujer,

[[sirach-25-20]]
^20^ Cuesta arenosa bajo los pies de un viejo,

[[sirach-25-21]]
^21^ No te dejes llevar por belleza de mujer,

[[sirach-25-22]]
^22^ Blanco de ira, de deshonra y gran vergüenza,

[[sirach-25-23]]
^23^ Corazón abatido, rostro sombrío,

[[sirach-25-24]]
^24^ Por la mujer fue el comienzo del pecado,

[[sirach-25-25]]
^25^ No des salida al agua,

[[sirach-25-26]]
^26^ Si no camina como marca tu mano,
[[sirach-26]]
== Capítulo 26

[[sirach-26-1]]
^1^ Feliz el marido de mujer buena,

[[sirach-26-2]]
^2^ Mujer varonil da contento a su marido,

[[sirach-26-3]]
^3^ Mujer buena es buena herencia,

[[sirach-26-4]]
^4^ sea rico o pobre, su corazón es feliz,

[[sirach-26-5]]
^5^ Tres cosas hay que teme mi corazón,

[[sirach-26-6]]
^6^ pero dolor de corazón y duelo es una mujer celosa de otra,

[[sirach-26-7]]
^7^ Yugo mal sujeto es la mujer mala,

[[sirach-26-8]]
^8^ Blanco de gran ira es la mujer bebedora,

[[sirach-26-9]]
^9^ La lujuria de la mujer se ve en la procacidad de sus ojos,

[[sirach-26-10]]
^10^ Sobre hija desenvuelta refuerza la guardia,

[[sirach-26-11]]
^11^ Guárdate de ir tras ojos descarados,

[[sirach-26-12]]
^12^ Cual caminante sediento abre ella la boca,

[[sirach-26-13]]
^13^ La gracia de la mujer recrea a su marido,

[[sirach-26-14]]
^14^ Un don del Señor la mujer silenciosa,

[[sirach-26-15]]
^15^ Gracia de gracias la mujer pudorosa,

[[sirach-26-16]]
^16^ Sol que sale por las alturas del Señor

[[sirach-26-17]]
^17^ Lámpara que brilla en sagrado candelero

[[sirach-26-18]]
^18^ Columnas de oro sobre basas de plata,

[[sirach-26-28]]
^28^ Dos cosas entristecen mi corazón

[[sirach-26-29]]
^29^ Difícilmente se libra de falta el negociante,
[[sirach-27]]
== Capítulo 27

[[sirach-27-1]]
^1^ Por amor a la ganancia han pecado muchos,

[[sirach-27-2]]
^2^ Entre dos piedras juntas se planta una estaca,

[[sirach-27-3]]
^3^ Quien no se aferra enseguida al temor del Señor,

[[sirach-27-4]]
^4^ Cuando la criba se sacude, quedan los desechos;

[[sirach-27-5]]
^5^ El horno prueba las vasijas de alfarero,

[[sirach-27-6]]
^6^ El fruto manifiesta el cultivo del árbol;

[[sirach-27-7]]
^7^ Antes que se pronuncie no elogies a nadie,

[[sirach-27-8]]
^8^ Si persigues la justicia, la alcanzarás,

[[sirach-27-9]]
^9^ Los pájaros van a posarse donde sus semejantes,

[[sirach-27-10]]
^10^ El león acecha a su presa,

[[sirach-27-11]]
^11^ La conversación del piadoso es siempre sabiduría,

[[sirach-27-12]]
^12^ En medio de imbéciles aguarda tu momento,

[[sirach-27-13]]
^13^ La conversación de los necios es algo irritante,

[[sirach-27-14]]
^14^ El hablar del jurador eriza los cabellos,

[[sirach-27-15]]
^15^ Disputa de orgullosos trae efusión de sangre,

[[sirach-27-16]]
^16^ Quien revela los secretos, pierde el crédito,

[[sirach-27-17]]
^17^ Ama a tu amigo y confíate a él,

[[sirach-27-18]]
^18^ porque como el que mata elimina a su víctima,

[[sirach-27-19]]
^19^ Como a pájaro que soltaste de tu mano,

[[sirach-27-20]]
^20^ No vayas en su busca, porque se fue lejos,

[[sirach-27-21]]
^21^ Que la herida puede ser vendada,

[[sirach-27-22]]
^22^ Quien guiña el ojo, anda urdiendo el mal,

[[sirach-27-23]]
^23^ Ante tus ojos pone dulce su boca,

[[sirach-27-24]]
^24^ Muchas cosas detesto, mas nada como a éste,

[[sirach-27-25]]
^25^ Quien tira una piedra al aire, sobre su propia cabeza la tira,

[[sirach-27-26]]
^26^ Quien cava una fosa, caerá en ella,

[[sirach-27-27]]
^27^ Quien hace el mal, lo verá caer sobre sí

[[sirach-27-28]]
^28^ Escarnio y ultraje son cosa de orgulloso,

[[sirach-27-29]]
^29^ Caerán en la red los que se alegran de la caída de los

[[sirach-27-30]]
^30^ Rencor e ira son también abominables,
[[sirach-28]]
== Capítulo 28

[[sirach-28-1]]
^1^ El que se venga, sufrirá venganza del Señor,

[[sirach-28-2]]
^2^ Perdona a tu prójimo el agravio,

[[sirach-28-3]]
^3^ Hombre que a hombre guarda ira,

[[sirach-28-4]]
^4^ De un hombre como él piedad no tiene,

[[sirach-28-5]]
^5^ El, que sólo es carne, guarda rencor,

[[sirach-28-6]]
^6^ Acuérdate de las postrimerías, y deja ya de odiar,

[[sirach-28-7]]
^7^ Recuerda los mandamientos, y no tengas rencor a tu prójimo,

[[sirach-28-8]]
^8^ Absténte de disputas y evitarás el pecado,

[[sirach-28-9]]
^9^ El pecador enzarza a los amigos,

[[sirach-28-10]]
^10^ Según sea la leña, así arde el fuego,

[[sirach-28-11]]
^11^ Riña súbita prende fuego,

[[sirach-28-12]]
^12^ Si soplas una chispa, prenderá,

[[sirach-28-13]]
^13^ Al soplón de lengua doble, maldícele,

[[sirach-28-14]]
^14^ A muchos sacudió la lengua triple,

[[sirach-28-15]]
^15^ La lengua triple repudió a mujeres varoniles,

[[sirach-28-16]]
^16^ El que la atiende no encontrará reposo,

[[sirach-28-17]]
^17^ El golpe del látigo produce cardenales,

[[sirach-28-18]]
^18^ Muchos han caído a filo de espada,

[[sirach-28-19]]
^19^ Feliz el que de ella se resguarda,

[[sirach-28-20]]
^20^ Porque su yugo es yugo de hierro,

[[sirach-28-21]]
^21^ Muerte funesta la muerte que ella da,

[[sirach-28-22]]
^22^ Mas no tiene poder sobre los piadosos,

[[sirach-28-23]]
^23^ Los que abandonan al Señor caerán en ella,

[[sirach-28-24]]
^24^ Mira, cerca tu hacienda con espinos,

[[sirach-28-25]]
^25^ A tus palabras pon balanza y peso,

[[sirach-28-26]]
^26^ Guárdate bien de resbalar por ella,
[[sirach-29]]
== Capítulo 29

[[sirach-29-1]]
^1^ Quien hace misericordia, presta al prójimo,

[[sirach-29-2]]
^2^ Presta a tu prójimo cuando se halle en necesidad,

[[sirach-29-3]]
^3^ Mantén tu palabra y ten confianza en él,

[[sirach-29-4]]
^4^ Muchos consideran el préstamo como una ganga,

[[sirach-29-5]]
^5^ Hasta que no recibe, besa las manos de su prójimo,

[[sirach-29-6]]
^6^ Si puede, el otro recibirá apenas la mitad,

[[sirach-29-7]]
^7^ Muchos, sin malicia, vuelven las espaldas,

[[sirach-29-8]]
^8^ Pero con el humilde muéstrate paciente,

[[sirach-29-9]]
^9^ En atención al mandamiento, acoge al indigente,

[[sirach-29-10]]
^10^ Gasta dinero por el hermano y el amigo,

[[sirach-29-11]]
^11^ Coloca tu tesoro según los mandamientos del Altísimo,

[[sirach-29-12]]
^12^ Encierra la limosna en tus graneros,

[[sirach-29-13]]
^13^ Mejor que recio escudo y que pesada lanza

[[sirach-29-14]]
^14^ El hombre bueno sale fiador de su prójimo,

[[sirach-29-15]]
^15^ No olvides los favores de tu fiador,

[[sirach-29-16]]
^16^ El pecador dilapida los bienes de su fiador,

[[sirach-29-17]]
^17^ La fianza perdió a muchos que iban bien,

[[sirach-29-18]]
^18^ Echó de su patria a hombres poderosos,

[[sirach-29-19]]
^19^ Pecador que se presta a la fianza

[[sirach-29-20]]
^20^ Acoge al prójimo según tus recursos,

[[sirach-29-21]]
^21^ Lo primero para vivir es agua, pan, vestido,

[[sirach-29-22]]
^22^ Más vale vida de pobre bajo techo de tablas

[[sirach-29-23]]
^23^ En lo poco y en lo mucho ten buena cara,

[[sirach-29-24]]
^24^ Triste vida andar de casa en casa:

[[sirach-29-25]]
^25^ Hospedarás y darás de beber a desagradecidos,

[[sirach-29-26]]
^26^ «Pasa, huésped, adereza la mesa,

[[sirach-29-27]]
^27^ - «Vete, huésped, cede el puesto a uno más digno,

[[sirach-29-28]]
^28^ Duro es para un hombre de sentimiento
[[sirach-30]]
== Capítulo 30

[[sirach-30-1]]
^1^ El que ama a su hijo, le azota sin cesar,

[[sirach-30-2]]
^2^ El que enseña a su hijo, sacará provecho de él,

[[sirach-30-3]]
^3^ El que instruye a su hijo, pondrá celoso a su enemigo,

[[sirach-30-4]]
^4^ Murió su padre, y como si no hubiera muerto,

[[sirach-30-5]]
^5^ En su vida le mira con contento,

[[sirach-30-6]]
^6^ Contra sus enemigos deja un vengador,

[[sirach-30-7]]
^7^ El que mima a su hijo, vendará sus heridas,

[[sirach-30-8]]
^8^ Caballo no domado, sale indócil,

[[sirach-30-9]]
^9^ Halaga a tu hijo, y te dará sorpresas

[[sirach-30-10]]
^10^ No rías con él, para no llorar

[[sirach-30-11]]
^11^ No le des libertad en su juventud,

[[sirach-30-12]]
^12^ Doblega su cerviz mientras es joven,

[[sirach-30-13]]
^13^ Enseña a tu hijo y trabaja en él,

[[sirach-30-14]]
^14^ Vale más pobre sano y fuerte de constitución

[[sirach-30-15]]
^15^ Salud y buena constitución valen más que todo el oro,

[[sirach-30-16]]
^16^ Ni hay riqueza mejor que la salud del cuerpo,

[[sirach-30-17]]
^17^ Mejor es la muerte que una vida amarga,

[[sirach-30-18]]
^18^ Manjares derramados sobre boca cerrada,

[[sirach-30-19]]
^19^ ¿De qué le sirve el sacrificio a un ídolo?

[[sirach-30-20]]
^20^ que mira con sus ojos y gime.

[[sirach-30-21]]
^21^ No entregues tu alma a la tristeza,

[[sirach-30-22]]
^22^ La alegría de corazón es la vida del hombre,

[[sirach-30-23]]
^23^ Engaña tu alma y consuela tu corazón,

[[sirach-30-24]]
^24^ Envidia y malhumor los días acortan,

[[sirach-30-25]]
^25^ Un corazón radiante viene bien en las comidas,
[[sirach-31]]
== Capítulo 31

[[sirach-31-1]]
^1^ El insomnio por la riqueza consume las carnes,

[[sirach-31-2]]
^2^ Las preocupaciones del día impiden dormir,

[[sirach-31-3]]
^3^ Se afana el rico por juntar riquezas,

[[sirach-31-4]]
^4^ Se afana el pobre por falta de sustento,

[[sirach-31-5]]
^5^ El que ama el oro no se verá justificado,

[[sirach-31-6]]
^6^ Muchos se arruinaron por causa del oro,

[[sirach-31-7]]
^7^ Es leño de tropiezo para los que le ofrecen sacrificios,

[[sirach-31-8]]
^8^ Feliz el rico que fue hallado intachable,

[[sirach-31-9]]
^9^ ¿Quién es, y le felicitaremos?,

[[sirach-31-10]]
^10^ ¿Quién sufrió esta prueba y fue hallado perfecto?

[[sirach-31-11]]
^11^ Sus bienes se consolidarán,

[[sirach-31-12]]
^12^ ¿En mesa suntuosa te has sentado?,

[[sirach-31-13]]
^13^ Recuerda que es cosa mala tener un ojo ávido,

[[sirach-31-14]]
^14^ Donde mire tu huésped no extiendas tú la mano,

[[sirach-31-15]]
^15^ Juzga al prójimo como a ti mismo,

[[sirach-31-16]]
^16^ Come como hombre bien educado lo que tienes delante,

[[sirach-31-17]]
^17^ Termina el primero por educación,

[[sirach-31-18]]
^18^ Si en medio de muchos te has sentado a la mesa,

[[sirach-31-19]]
^19^ ¡Qué poco le basta a un hombre bien educado!,

[[sirach-31-20]]
^20^ A vientre moderado, sueño saludable,

[[sirach-31-21]]
^21^ Si te viste obligado a comer demasiado,

[[sirach-31-22]]
^22^ Oyeme, hijo, y no me desprecies,

[[sirach-31-23]]
^23^ Al espléndido en las comidas le bendicen los labios,

[[sirach-31-24]]
^24^ Al mezquino en la comida le murmura la ciudad,

[[sirach-31-25]]
^25^ Con el vino no te hagas el valiente,

[[sirach-31-26]]
^26^ El horno prueba el temple del acero,

[[sirach-31-27]]
^27^ Como la vida es el vino para el hombre,

[[sirach-31-28]]
^28^ Regocijo del corazón y contento del alma

[[sirach-31-29]]
^29^ Amargura del alma, el vino bebido con exceso

[[sirach-31-30]]
^30^ La embriaguez acrecienta el furor del insensato hasta su

[[sirach-31-31]]
^31^ En banquete no reproches a tu prójimo,
[[sirach-32]]
== Capítulo 32

[[sirach-32-1]]
^1^ ¿Te han nombrado presidente? No te engrías,

[[sirach-32-2]]
^2^ Cuando hayas cumplido todo tu menester, tomo asiento,

[[sirach-32-3]]
^3^ Habla, anciano, que te está bien,

[[sirach-32-4]]
^4^ Durante la audición, no derrames locuacidad,

[[sirach-32-5]]
^5^ Sello de carbunclo en alhaja de oro,

[[sirach-32-6]]
^6^ Sello de esmeralda en montura de oro,

[[sirach-32-7]]
^7^ Habla, joven, si te es necesario,

[[sirach-32-8]]
^8^ Resume tu discurso, di mucho en poco,

[[sirach-32-9]]
^9^ Entre grandes no te iguales a ellos,

[[sirach-32-10]]
^10^ Al trueno se adelanta el relámpago,

[[sirach-32-11]]
^11^ Llegada la hora levántate, no te rezagues,

[[sirach-32-12]]
^12^ Allí, diviértete y haz lo que te plazca,

[[sirach-32-13]]
^13^ Y por todo esto bendice a tu Hacedor,

[[sirach-32-14]]
^14^ El que teme al Señor acepta la instrucción,

[[sirach-32-15]]
^15^ El que busca la ley se llena de ella,

[[sirach-32-16]]
^16^ Los que temen al Señor son justificados,

[[sirach-32-17]]
^17^ El pecador rehúye la reprensión,

[[sirach-32-18]]
^18^ El varón de consejo no descuida la reflexión,

[[sirach-32-19]]
^19^ Sin consejo no hagas nada,

[[sirach-32-20]]
^20^ Por caminos escabrosos no vayas,

[[sirach-32-21]]
^21^ No te confies en camino inexplorado,

[[sirach-32-22]]
^22^ y de tus hijos guárdate.

[[sirach-32-23]]
^23^ En todos tus actos vela sobre ti,

[[sirach-32-24]]
^24^ El que tiene confianza en la ley atiende a los mandamientos,
[[sirach-33]]
== Capítulo 33

[[sirach-33-1]]
^1^ Al que teme al Señor ningún mal le sucede,

[[sirach-33-2]]
^2^ El varón sabio no aborrece la ley,

[[sirach-33-3]]
^3^ El hombre inteligente pone su confianza en la ley,

[[sirach-33-4]]
^4^ Prepara tu discurso, y serás así escuchado,

[[sirach-33-5]]
^5^ Rueda de carro son las entrañas del necio, como eje que da

[[sirach-33-6]]
^6^ Caballo de remonta, así el amigo burlón,

[[sirach-33-7]]
^7^ ¿Por qué un día es superior a otro,

[[sirach-33-8]]
^8^ En la mente del Señor fueron diferenciados,

[[sirach-33-9]]
^9^ A unos los ensalzó y santificó,

[[sirach-33-10]]
^10^ Así todos los hombres vienen del suelo,

[[sirach-33-11]]
^11^ Con su gran sabiduría los diferenció el Señor,

[[sirach-33-12]]
^12^ A unos los bendijo y ensalzó,

[[sirach-33-13]]
^13^ Como la arcilla del alfarero está en su mano,

[[sirach-33-14]]
^14^ Frente al mal está el bien,

[[sirach-33-15]]
^15^ Fíjate, pues, en todas las obras del Altísimo,

[[sirach-33-16]]
^16^ También yo, el último, me he desvelado,

[[sirach-33-17]]
^17^ Por la bendición del Señor me he adelantado,

[[sirach-33-18]]
^18^ Mirad que no para mí solo me he afanado,

[[sirach-33-19]]
^19^ Escuchadme, grandes del pueblo,

[[sirach-33-20]]
^20^ A hijo y mujer, a hermano y amigo

[[sirach-33-21]]
^21^ Mientras vivas y haya aliento en ti,

[[sirach-33-22]]
^22^ Pues es mejor que tus hijos te pidan,

[[sirach-33-23]]
^23^ En todas tus obras muéstrate con dominio,

[[sirach-33-24]]
^24^ Cuando se acaben los días de tu vida,

[[sirach-33-25]]
^25^ Al asno, forraje, palo y carga,

[[sirach-33-26]]
^26^ Haz trabajar al siervo, y encontrarás descanso,

[[sirach-33-27]]
^27^ Yugo y riendas doblegan la cerviz,

[[sirach-33-28]]
^28^ Mándale trabajar para que no esté ocioso,

[[sirach-33-29]]
^29^ Ponle trabajo como le corresponde,

[[sirach-33-30]]
^30^ Pero no te sobrepases con nadie,

[[sirach-33-31]]
^31^ Si tienes un criado, sea como tú,

[[sirach-33-32]]
^32^ Si tienes un criado, trátale como hermano,

[[sirach-33-33]]
^33^ Si le maltratas, y levantándose, se escapa,
[[sirach-34]]
== Capítulo 34

[[sirach-34-1]]
^1^ Las esperanzas vanas y engañosas son para el imbécil,

[[sirach-34-2]]
^2^ Tratar de asir una sombra o perseguir el viento

[[sirach-34-3]]
^3^ Espejo y sueño son casas semejantes,

[[sirach-34-4]]
^4^ De los impuros, ¿qué pureza puede resultar?

[[sirach-34-5]]
^5^ Adivinaciones, augurios y sueños cosas vanas son,

[[sirach-34-6]]
^6^ A menos que te sean enviadas por el Altísimo en visita,

[[sirach-34-7]]
^7^ Que a muchos extraviaron los sueños,

[[sirach-34-8]]
^8^ Sin dolo se ha de cumplir la Ley,

[[sirach-34-9]]
^9^ Hombre que ha corrido mundo sabe muchas cosas,

[[sirach-34-10]]
^10^ Quien no ha pasado pruebas poco sabe,

[[sirach-34-11]]
^11^ Muchas cosas he visto en el curso de mis viajes,

[[sirach-34-12]]
^12^ Bien de veces he estado en peligro de muerte,

[[sirach-34-13]]
^13^ El espíritu de los que temen al Señor vivirá,

[[sirach-34-14]]
^14^ Quien teme al Señor de nada tiene miedo,

[[sirach-34-15]]
^15^ Feliz el alma del que teme al Señor:

[[sirach-34-16]]
^16^ Los ojos del Señor sobre quienes le aman,

[[sirach-34-17]]
^17^ que levanta el alma, alumbra los ojos,

[[sirach-34-18]]
^18^ Sacrificar cosa injusta es hacer ofrenda rechazada,

[[sirach-34-19]]
^19^ No se complace el Altísimo en ofrendas de impíos,

[[sirach-34-20]]
^20^ Inmola a un hijo a los ojos de su padre

[[sirach-34-21]]
^21^ Pan de indigentes es la vida de los pobres,

[[sirach-34-22]]
^22^ Mata a su prójimo quien le arrebata su sustento,

[[sirach-34-23]]
^23^ Uno edifica, el otro destruye,

[[sirach-34-24]]
^24^ Uno bendice, el otro maldice,

[[sirach-34-25]]
^25^ Quien se purifica del contacto de un muerto y le vuelve a

[[sirach-34-26]]
^26^ Así el hombre que ayuna por sus pecados
[[sirach-35]]
== Capítulo 35

[[sirach-35-1]]
^1^ Observar la ley es hacer muchas ofrendas,

[[sirach-35-2]]
^2^ Devolver favor es hacer oblación de flor de harina,

[[sirach-35-3]]
^3^ Apartarse del mal es complacer al Señor,

[[sirach-35-4]]
^4^ No te presentes ante el Señor con las manos vacías,

[[sirach-35-5]]
^5^ La ofrenda del justo unge el altar,

[[sirach-35-6]]
^6^ El sacrificio del justo es aceptado,

[[sirach-35-7]]
^7^ Con ojo generoso glorifica al Señor,

[[sirach-35-8]]
^8^ En todos tus dones pon tu rostro alegre,

[[sirach-35-9]]
^9^ Da al Altísimo como él te ha dado a ti,

[[sirach-35-10]]
^10^ Porque el Señor sabe pagar,

[[sirach-35-11]]
^11^ No trates de corromperle con presentes, porque no los acepta,

[[sirach-35-12]]
^12^ Porque el Señor es juez,

[[sirach-35-13]]
^13^ No hace acepción de personas contra el pobre,

[[sirach-35-14]]
^14^ No desdeña la súplica del huérfano,

[[sirach-35-15]]
^15^ Las lágrimas de la viuda, ¿no bajan por su mejilla,

[[sirach-35-16]]
^16^ Quien sirve de buena gana, es aceptado,

[[sirach-35-17]]
^17^ La oración del humilde las nubes atraviesa,

[[sirach-35-18]]
^18^ Y no desiste hasta que vuelve los ojos el Altísimo,

[[sirach-35-19]]
^19^ Y el Señor no se tardará,

[[sirach-35-20]]
^20^ hasta no haber machacado los lomos de los sin entrañas,

[[sirach-35-21]]
^21^ haber extirpado el tropel de los soberbios,

[[sirach-35-22]]
^22^ hasta no haber pagado a cada cual según sus actos,

[[sirach-35-23]]
^23^ haber hecho justicia a su pueblo,

[[sirach-35-24]]
^24^ Grata es la misericordia en tiempo de tribulación,
[[sirach-36]]
== Capítulo 36

[[sirach-36-1]]
^1^ Ten piedad de nosotros, Dios, dueño de todas las cosas, mira

[[sirach-36-2]]
^2^ Alza tu mano contra las naciones extranjeras,

[[sirach-36-3]]
^3^ Como ante ellas te has mostrado santo con nosotros,

[[sirach-36-4]]
^4^ Que te reconozcan, como nosotros hemos reconocido

[[sirach-36-5]]
^5^ Renueva las señales, repite tus maravillas,

[[sirach-36-6]]
^6^ Despierta tu furor y derrama tu ira,

[[sirach-36-7]]
^7^ Acelera la hora, recuerda el juramento,

[[sirach-36-8]]
^8^ Que el fuego de la ira devore al que se escape,

[[sirach-36-9]]
^9^ Aplasta la cabeza de los jefes enemigos,

[[sirach-36-10]]
^10^ Congrega todas las tribus de Jacob,

[[sirach-36-11]]
^11^ Ten piedad, Señor, del pueblo llamado con tu nombre,

[[sirach-36-12]]
^12^ Ten compasión de tu santa ciudad,

[[sirach-36-13]]
^13^ Llena a Sión de tu alabanza,

[[sirach-36-14]]
^14^ Da testimonio a tus primeras criaturas,

[[sirach-36-15]]
^15^ Da su recompensa a los que te aguardan,

[[sirach-36-16]]
^16^ Escucha, Señor, la súplica de tus siervos,

[[sirach-36-17]]
^17^ Y todos los de la tierra reconozcan

[[sirach-36-18]]
^18^ Todo alimento traga el vientre,

[[sirach-36-19]]
^19^ El paladar distingue por el gusto la carne de caza,

[[sirach-36-20]]
^20^ El corazón perverso da tristeza,

[[sirach-36-21]]
^21^ A cualquier marido acepta la mujer,

[[sirach-36-22]]
^22^ La belleza de la mujer recrea la mirada,

[[sirach-36-23]]
^23^ Si en su lengua hay ternura y mansedumbre,

[[sirach-36-24]]
^24^ El que adquiere una mujer, adquiere el comienzo de la fortuna,

[[sirach-36-25]]
^25^ Donde no hay valla, la propiedad es saqueada,

[[sirach-36-26]]
^26^ ¿Quién se fiará del ladrón ágil

[[sirach-36-27]]
^27^ Así tampoco del hombre que no tiene nido
[[sirach-37]]
== Capítulo 37

[[sirach-37-1]]
^1^ Todo amigo dice: «También yo soy tu amigo»,

[[sirach-37-2]]
^2^ ¿No es para uno una mortal tristeza

[[sirach-37-3]]
^3^ ¡Oh intención perversa! ¿de dónde saliste

[[sirach-37-4]]
^4^ El compañero disfruta en el contento del amigo,

[[sirach-37-5]]
^5^ El compañero compadece al amigo por interés,

[[sirach-37-6]]
^6^ No te olvides de tu amigo en tu alma,

[[sirach-37-7]]
^7^ Todo consejero da consejos,

[[sirach-37-8]]
^8^ Del consejero guarda tu alma,

[[sirach-37-9]]
^9^ y te diga: «Bueno es tu camino»,

[[sirach-37-10]]
^10^ No te aconsejes del que te mira con desprecio,

[[sirach-37-11]]
^11^ ni te aconsejes con mujer sobre su rival,

[[sirach-37-12]]
^12^ Sino recurre siempre a un hombre piadoso,

[[sirach-37-13]]
^13^ Y mantén firme el consejo de tu corazón,

[[sirach-37-14]]
^14^ Pues el alma del hombre puede a veces advertir

[[sirach-37-15]]
^15^ Y por encima de todo esto suplica al Altísimo,

[[sirach-37-16]]
^16^ Principio de toda obra es la palabra,

[[sirach-37-17]]
^17^ Raíz de los pensamientos es el corazón,

[[sirach-37-18]]
^18^ bien y mal, vida y muerte,

[[sirach-37-19]]
^19^ Hay hombre diestro que adoctrina a muchos,

[[sirach-37-20]]
^20^ Hay quien se hace el sabio en palabras y es aborrecido,

[[sirach-37-21]]
^21^ Pues no se le dio la gracia que viene del Señor,

[[sirach-37-22]]
^22^ Hay quien para sí mismo es sabio,

[[sirach-37-23]]
^23^ El varón sabio enseña a su pueblo,

[[sirach-37-24]]
^24^ El varón sabio es colmado de bendiciones,

[[sirach-37-25]]
^25^ La vida del hombre tiene días contados,

[[sirach-37-26]]
^26^ El sabio en su pueblo se gana la confianza,

[[sirach-37-27]]
^27^ Hijo, en tu vida prueba tu alma,

[[sirach-37-28]]
^28^ Pues no a todos les conviene todo,

[[sirach-37-29]]
^29^ No seas insaciable de todo placer,

[[sirach-37-30]]
^30^ porque en el exceso de alimento hay enfermedad,

[[sirach-37-31]]
^31^ Por intemperancia han muerto muchos,
[[sirach-38]]
== Capítulo 38

[[sirach-38-1]]
^1^ Da al médico, por sus servicios, los honores que merece,

[[sirach-38-2]]
^2^ Pues del Altísimo viene la curación,

[[sirach-38-3]]
^3^ La ciencia del médico realza su cabeza,

[[sirach-38-4]]
^4^ El Señor puso en la tierra medicinas,

[[sirach-38-5]]
^5^ ¿No fue el agua endulzada con un leño

[[sirach-38-6]]
^6^ El mismo dio a los hombres la ciencia

[[sirach-38-7]]
^7^ Con ellas cura él y quita el sufrimiento,

[[sirach-38-8]]
^8^ Así nunca se acaban sus obras,

[[sirach-38-9]]
^9^ Hijo, en tu enfermedad, no seas negligente,

[[sirach-38-10]]
^10^ Aparta las faltas, endereza tus manos,

[[sirach-38-11]]
^11^ Ofrece incienso y memorial de flor de harina,

[[sirach-38-12]]
^12^ Recurre luego al médico, pues el Señor le creó también a él,

[[sirach-38-13]]
^13^ Hay momentos en que en su mano está la solución,

[[sirach-38-14]]
^14^ pues ellos también al Señor suplicarán

[[sirach-38-15]]
^15^ El que peca delante de su Hacedor

[[sirach-38-16]]
^16^ Hijo, por un muerto lágrimas derrama,

[[sirach-38-17]]
^17^ Llora amargamente, date fuertes golpes de pecho,

[[sirach-38-18]]
^18^ Porque de la tristeza sale la muerte,

[[sirach-38-19]]
^19^ En la adversidad permanece también la tristeza,

[[sirach-38-20]]
^20^ No des tu corazón a la tristeza,

[[sirach-38-21]]
^21^ No lo olvides: no hay retorno,

[[sirach-38-22]]
^22^ «Recuerda mi sentencia, que será también la tuya:

[[sirach-38-23]]
^23^ Cuando un muerto reposa, deja en paz su memoria,

[[sirach-38-24]]
^24^ La sabiduría del escriba se adquiere en los ratos de sosiego,

[[sirach-38-25]]
^25^ ¿Cómo va a hacerse sabio el que empuña el arado,

[[sirach-38-26]]
^26^ Aplica su corazón a abrir surcos,

[[sirach-38-27]]
^27^ De igual modo todo obrero o artesano,

[[sirach-38-28]]
^28^ También el herrero sentado junto al yunque,

[[sirach-38-29]]
^29^ De igual modo el alfarero sentado a su tarea

[[sirach-38-30]]
^30^ con su brazo moldea la arcilla,

[[sirach-38-31]]
^31^ Todos éstos ponen su confianza en sus manos,

[[sirach-38-32]]
^32^ Sin ellos no se construiría ciudad alguna,

[[sirach-38-33]]
^33^ Mas para el consejo del pueblo no se les busca,

[[sirach-38-34]]
^34^ No demuestran instrucción ni juicio,
[[sirach-39]]
== Capítulo 39

[[sirach-39-1]]
^1^ No así el que aplica su alma

[[sirach-39-2]]
^2^ conserva los relatos de varones célebres,

[[sirach-39-3]]
^3^ busca los secretos de los proverbios

[[sirach-39-4]]
^4^ En medio de los grandes ejerce su servicio,

[[sirach-39-5]]
^5^ Aplica su corazón a ir bien de mañana

[[sirach-39-6]]
^6^ Si el gran Señor lo quiere,

[[sirach-39-7]]
^7^ Enderezará su consejo y su ciencia.

[[sirach-39-8]]
^8^ Mostrará la instrucción recibida,

[[sirach-39-9]]
^9^ Muchos elogiarán su inteligencia,

[[sirach-39-10]]
^10^ Su sabiduría comentarán las naciones,

[[sirach-39-11]]
^11^ Mientras viva, su nombre dejará atrás a mil,

[[sirach-39-12]]
^12^ Aún voy a hablar después de meditar,

[[sirach-39-13]]
^13^ Escuchadme, hijos piadosos, y creced

[[sirach-39-14]]
^14^ Como incienso derramad buen olor,

[[sirach-39-15]]
^15^ Engrandeced su nombre,

[[sirach-39-16]]
^16^ ¡Qué hermosas son todas las obras del Señor!

[[sirach-39-17]]
^17^ A su orden el agua se detiene en una masa,

[[sirach-39-18]]
^18^ A una orden suya se hace todo lo que desea,

[[sirach-39-19]]
^19^ Las obras de toda carne están delante de él,

[[sirach-39-20]]
^20^ Su mirada abarca de eternidad a eternidad,

[[sirach-39-21]]
^21^ No hay por qué decir: ¿Qué es esto? Y esto ¿para qué?,

[[sirach-39-22]]
^22^ Su bendición se ha desbordado como un río,

[[sirach-39-23]]
^23^ De igual modo las naciones recibirán en herencia su ira,

[[sirach-39-24]]
^24^ Sus caminos rectos son para los santos,

[[sirach-39-25]]
^25^ Los bienes están desde el principio creados para los buenos,

[[sirach-39-26]]
^26^ De primera necesidad para la vida del hombre

[[sirach-39-27]]
^27^ Todo esto son bienes para los piadosos,

[[sirach-39-28]]
^28^ Hay vientos creados para el castigo,

[[sirach-39-29]]
^29^ Fuego y granizo, hambre y muerte,

[[sirach-39-30]]
^30^ Y dientes de fieras, escorpiones, víboras

[[sirach-39-31]]
^31^ Todos hallan contento en hacer su mandato,

[[sirach-39-32]]
^32^ Por eso desde el principio me reafirmé,

[[sirach-39-33]]
^33^ «Las obras del Señor son todas buenas,

[[sirach-39-34]]
^34^ No hay por qué decir: Esto es peor que aquello,

[[sirach-39-35]]
^35^ Y ahora con todo el corazón y la boca cantad himnos
[[sirach-40]]
== Capítulo 40

[[sirach-40-1]]
^1^ Grandes trabajos han sido creados para todo hombre,

[[sirach-40-2]]
^2^ Sus reflexiones, el miedo de su corazón

[[sirach-40-3]]
^3^ Desde el que está sentado en un trono glorioso,

[[sirach-40-4]]
^4^ desde el que lleva púrpura y corona,

[[sirach-40-5]]
^5^ A la hora del descanso en la cama,

[[sirach-40-6]]
^6^ Poco, casi nada, reposa,

[[sirach-40-7]]
^7^ A la hora de su turno se despierta,

[[sirach-40-8]]
^8^ Para toda carne, del hombre hasta la bestia,

[[sirach-40-9]]
^9^ Muerte, sangre, discordia, espada,

[[sirach-40-10]]
^10^ Contra los sin ley fue creado todo esto,

[[sirach-40-11]]
^11^ Todo cuanto de tierra viene, a tierra vuelve,

[[sirach-40-12]]
^12^ Todo don e injusticia serán aventados,

[[sirach-40-13]]
^13^ Las riquezas de los injustos se esfumarán como un torrente,

[[sirach-40-14]]
^14^ Cuando él abre las manos, se contenta,

[[sirach-40-15]]
^15^ Los vástagos de los impíos no tienen muchas ramas,

[[sirach-40-16]]
^16^ Caña que brota en toda agua o borde de río

[[sirach-40-17]]
^17^ La caridad es como un paraíso de bendición,

[[sirach-40-18]]
^18^ La vida del que se basta a sí mismo y del obrero es dulce,

[[sirach-40-19]]
^19^ Los hijos y la fundación de una ciudad perpetúan el nombre,

[[sirach-40-20]]
^20^ El vino y la música ponen contento el corazón,

[[sirach-40-21]]
^21^ La flauta y el salterio hacen el canto suave,

[[sirach-40-22]]
^22^ Gracia y belleza el ojo anhela,

[[sirach-40-23]]
^23^ Amigo y compañero se encuentran a su hora,

[[sirach-40-24]]
^24^ Amigos y socorro para el tiempo de tribulación,

[[sirach-40-25]]
^25^ Oro y plata hacen el paso firme,

[[sirach-40-26]]
^26^ La riqueza y la fuerza realzan el corazón,

[[sirach-40-27]]
^27^ El temor del Señor como un paraíso de bendición,

[[sirach-40-28]]
^28^ Hijo, no lleves una vida de mendicidad,

[[sirach-40-29]]
^29^ Hombre que mira a la mesa de otro

[[sirach-40-30]]
^30^ En la boca del descarado la mendicidad resulta dulce,
[[sirach-41]]
== Capítulo 41

[[sirach-41-1]]
^1^ ¡Oh muerte, qué amargo es tu recuerdo

[[sirach-41-2]]
^2^ ¡Oh muerte, buena es tu sentencia

[[sirach-41-3]]
^3^ No temas la sentencia de la muerte,

[[sirach-41-4]]
^4^ Esta sentencia viene del Señor sobre toda carne,

[[sirach-41-5]]
^5^ Hijos abominables son los hijos de los pecadores

[[sirach-41-6]]
^6^ La herencia de los hijos de los pecadores va a la ruina,

[[sirach-41-7]]
^7^ Al padre impío le reprochan sus hijos,

[[sirach-41-8]]
^8^ ¡Ay de vosotros, impíos,

[[sirach-41-9]]
^9^ Si nacéis, para la maldición nacéis,

[[sirach-41-10]]
^10^ Todo cuanto viene de tierra, a tierra volverá,

[[sirach-41-11]]
^11^ El duelo de los hombres se dirige a sus cuerpos,

[[sirach-41-12]]
^12^ Preocúpate de tu nombre, que eso te queda,

[[sirach-41-13]]
^13^ La vida buena tiene un límite de días,

[[sirach-41-14]]
^14^ Conservad la instrucción en paz, hijos.

[[sirach-41-15]]
^15^ Más vale hombre que oculta su necedad,

[[sirach-41-16]]
^16^ Así pues, ruborizaos de lo que os voy a señalar,

[[sirach-41-17]]
^17^ Ante un padre y una madre avergonzaos de la fornicación,

[[sirach-41-18]]
^18^ del extravío, ante juez y el magistrado,

[[sirach-41-19]]
^19^ de la injusticia, ante el compañero y el amigo,

[[sirach-41-20]]
^20^ y ante la verdad de Dios y la alianza:

[[sirach-41-21]]
^21^ de despreciar la recepción y el don,

[[sirach-41-22]]
^22^ de mirar a mujer prostituta,

[[sirach-41-23]]
^23^ de quitar la parte y el don de otro,

[[sirach-41-24]]
^24^ de intimidades con la criada

[[sirach-41-25]]
^25^ de palabras injuriosas ante los amigos

[[sirach-41-26]]
^26^ de repetir la palabra oída,

[[sirach-41-27]]
^27^ Serás entonces de verdad un hombre ruboroso,
[[sirach-42]]
== Capítulo 42

[[sirach-42-1]]
^1^ Pero de lo que sigue no te avergüences,

[[sirach-42-2]]
^2^ de la ley del Altísimo y de su alianza,

[[sirach-42-3]]
^3^ de contar con compañero de viaje,

[[sirach-42-4]]
^4^ de la exactitud de balanzas y pesas,

[[sirach-42-5]]
^5^ de provecho en la venta a comerciantes,

[[sirach-42-6]]
^6^ Con mujer mala es bueno usar el sello,

[[sirach-42-7]]
^7^ Lo que entregues, hazlo con cuenta y medida,

[[sirach-42-8]]
^8^ No te avergüences de enseñar al tonto y al necio,

[[sirach-42-9]]
^9^ Una hija es para el padre un secreto desvelo,

[[sirach-42-10]]
^10^ Cuando virgen, no sea mancillada

[[sirach-42-11]]
^11^ Sobre la hija desenvuelta refuerza la vigilancia,

[[sirach-42-12]]
^12^ De ningún hombre te quedes mirando la belleza,

[[sirach-42-13]]
^13^ Porque de los vestidos sale la polilla,

[[sirach-42-14]]
^14^ Vale más maldad de hombre que bondad de mujer,

[[sirach-42-15]]
^15^ Voy a evocar las obras del Señor,

[[sirach-42-16]]
^16^ El sol mira a todo iluminándolo,

[[sirach-42-17]]
^17^ No son capaces los Santos del Señor

[[sirach-42-18]]
^18^ El sondea el abismo y el corazón humano,

[[sirach-42-19]]
^19^ Anuncia lo pasado y lo futuro,

[[sirach-42-20]]
^20^ No se le escapa ningún pensamiento,

[[sirach-42-21]]
^21^ Las grandezas de su sabiduría las puso en orden,

[[sirach-42-22]]
^22^ ¡Qué amables son todas sus obras!:

[[sirach-42-23]]
^23^ Todo esto vive y permanece eternamente,

[[sirach-42-24]]
^24^ Todas las cosas de dos en dos, una frente a otra,

[[sirach-42-25]]
^25^ Cada cosa afirma la excelencia de la otra,
[[sirach-43]]
== Capítulo 43

[[sirach-43-1]]
^1^ Orgullo de las alturas, firmamento de pureza,

[[sirach-43-2]]
^2^ El sol apareciendo proclama a su salida:

[[sirach-43-3]]
^3^ En su mediodía reseca la tierra,

[[sirach-43-4]]
^4^ Se atiza el horno para obras de forja:

[[sirach-43-5]]
^5^ Grande es el Señor que lo hizo,

[[sirach-43-6]]
^6^ También la luna: sale siempre a su hora,

[[sirach-43-7]]
^7^ De la luna procede la señal de las fiestas,

[[sirach-43-8]]
^8^ Lleva el mes su nombre;

[[sirach-43-9]]
^9^ Hermosura del cielo es la gloria de las estrellas.

[[sirach-43-10]]
^10^ Por las palabras del Señor están fijas según su orden.

[[sirach-43-11]]
^11^ Mira el arco iris y a su Hacedor bendice,

[[sirach-43-12]]
^12^ Rodea el cielo con aureola de gloria,

[[sirach-43-13]]
^13^ Con su orden precipita la nieve,

[[sirach-43-14]]
^14^ Por eso se abren sus cilleros,

[[sirach-43-15]]
^15^ Con su grandeza hace espesas las nubes,

[[sirach-43-16]]
^16^ a su vista se conmueven los montes.

[[sirach-43-17]]
^17^ El bramido de su trueno insulta a la tierra,

[[sirach-43-18]]
^18^ Como pájaros que se posan esparce la nieve,

[[sirach-43-19]]
^19^ El derrama también sobre la tierra la escarcha como sal,

[[sirach-43-20]]
^20^ El viento frío del norte sopla

[[sirach-43-21]]
^21^ Devora los montes, quema el desierto,

[[sirach-43-22]]
^22^ Como remedio de todo llega presto la niebla,

[[sirach-43-23]]
^23^ Según su designio domeña el abismo,

[[sirach-43-24]]
^24^ Los que surcan el mar hablan de sus peligros,

[[sirach-43-25]]
^25^ Allí están las cosas raras y maravillosas,

[[sirach-43-26]]
^26^ Gracias a Dios tiene éxito su mensajero,

[[sirach-43-27]]
^27^ Muchos más podríamos decir y nunca acabaríamos;

[[sirach-43-28]]
^28^ ¿Dónde hallar fuerza para glorificarle?

[[sirach-43-29]]
^29^ Temible es el Señor, inmensamente grande,

[[sirach-43-30]]
^30^ Con vuestra alabanza ensalzad al Señor,

[[sirach-43-31]]
^31^ ¿Quién le ha visto para que pueda describirle?

[[sirach-43-32]]
^32^ Mayores que éstas quedan ocultas muchas cosas,

[[sirach-43-33]]
^33^ Porque el Señor lo hizo todo,
[[sirach-44]]
== Capítulo 44

[[sirach-44-1]]
^1^ Hagamos ya el elogio de los hombres ilustres,

[[sirach-44-2]]
^2^ Grandes glorias que creó el Señor,

[[sirach-44-3]]
^3^ Hubo soberanos en sus reinos,

[[sirach-44-4]]
^4^ guías del pueblo por sus consejos,

[[sirach-44-5]]
^5^ inventores de melodías musicales,

[[sirach-44-6]]
^6^ hombres ricos bien provistos de fuerza,

[[sirach-44-7]]
^7^ Todos estos fueron honrados en su generación,

[[sirach-44-8]]
^8^ Hubo entre ellos quienes dejaron nombre,

[[sirach-44-9]]
^9^ De otros no ha quedado recuerdo,

[[sirach-44-10]]
^10^ Mas de otro modo estos hombres de bien,

[[sirach-44-11]]
^11^ Con su linaje permanece

[[sirach-44-12]]
^12^ En las alianzas se mantuvo su linaje,

[[sirach-44-13]]
^13^ Para siempre permanece su linaje,

[[sirach-44-14]]
^14^ Sus cuerpos fueron sepultados en paz,

[[sirach-44-15]]
^15^ Su sabiduría comentarán los pueblos,

[[sirach-44-16]]
^16^ Henoc agradó al Señor, y fue arrebatado,

[[sirach-44-17]]
^17^ Perfectamente justo Noé fue hallado,

[[sirach-44-18]]
^18^ Alianzas eternas fueron con él pactadas,

[[sirach-44-19]]
^19^ Abraham, padre insigne de una multitud de naciones,

[[sirach-44-20]]
^20^ El guardó la ley del Altísimo,

[[sirach-44-21]]
^21^ Por eso Dios le prometió con juramento

[[sirach-44-22]]
^22^ A Isaac le aseguró lo mismo,

[[sirach-44-23]]
^23^ La bendición de todos los hombres y la alianza
[[sirach-45]]
== Capítulo 45

[[sirach-45-1]]
^1^ Hizo salir de él un hombre de bien,

[[sirach-45-2]]
^2^ Le hizo en gloria comparable a los santos,

[[sirach-45-3]]
^3^ Por su palabra puso fin a los prodigios,

[[sirach-45-4]]
^4^ En fidelidad y mansedumbre le santificó,

[[sirach-45-5]]
^5^ Le hizo oír su voz,

[[sirach-45-6]]
^6^ Exaltó a Aarón, un santo semejante a éste,

[[sirach-45-7]]
^7^ Le afirmó como alianza eterna,

[[sirach-45-8]]
^8^ Le vistió de honor perfecto,

[[sirach-45-9]]
^9^ Le puso alrededor granadas,

[[sirach-45-10]]
^10^ y vestimenta sacra, de oro y de jacinto

[[sirach-45-11]]
^11^ piedras preciosas, grabadas como sellos,

[[sirach-45-12]]
^12^ corona de oro por encima de la tiara,

[[sirach-45-13]]
^13^ Galanuras no hubo tales antes de él,

[[sirach-45-14]]
^14^ Sus sacrificios se consumían totalmente

[[sirach-45-15]]
^15^ Llenó Moisés sus manos,

[[sirach-45-16]]
^16^ Le eligió entre todos los vivientes

[[sirach-45-17]]
^17^ Le dio, por sus mandamientos,

[[sirach-45-18]]
^18^ Se confabularon contra él extranjeros

[[sirach-45-19]]
^19^ Lo vió el Señor y se irritó,

[[sirach-45-20]]
^20^ Aumentó la gloria de Aarón

[[sirach-45-21]]
^21^ Por eso comen ellos los sacrificios del Señor,

[[sirach-45-22]]
^22^ Aunque en la tierra del pueblo no tiene heredad,

[[sirach-45-23]]
^23^ Pinjás, hijo de Eleazar, tercero en gloria,

[[sirach-45-24]]
^24^ Por eso se hizo con él una alianza de paz,

[[sirach-45-25]]
^25^ Hubo también alianza con David,

[[sirach-45-26]]
^26^ Dé Dios sabiduría a vuestro corazón
[[sirach-46]]
== Capítulo 46

[[sirach-46-1]]
^1^ Esforzado en la guerra fue Josué, hijo de Nun,

[[sirach-46-2]]
^2^ ¡Qué gloria ganó cuando alzaba la mano

[[sirach-46-3]]
^3^ ¿Quién antes de él tan firme fue?

[[sirach-46-4]]
^4^ ¿No se detuvo el sol ante su mano

[[sirach-46-5]]
^5^ El invocó al Altísimo Soberano,

[[sirach-46-6]]
^6^ Cayó de golpe sobre la nación hostil,

[[sirach-46-7]]
^7^ Pues caminó en seguimiento del Todopoderoso,

[[sirach-46-8]]
^8^ Y ellos dos solos se salvaron

[[sirach-46-9]]
^9^ Y el Señor dio a Caleb la fuerza

[[sirach-46-10]]
^10^ para que sepan todos los hijos de Israel

[[sirach-46-11]]
^11^ También los jueces, cada cual según su nombre,

[[sirach-46-12]]
^12^ reflorezcan sus huesos en la tumba,

[[sirach-46-13]]
^13^ Amado fue de su Señor Samuel,

[[sirach-46-14]]
^14^ Según la ley del Señor juzgó a la asamblea,

[[sirach-46-15]]
^15^ Por su fidelidad se acreditó como profeta,

[[sirach-46-16]]
^16^ Invocó al Señor Todopoderoso

[[sirach-46-17]]
^17^ Y tronó el Señor desde los cielos,

[[sirach-46-18]]
^18^ aplastó a los jefes adversarios

[[sirach-46-19]]
^19^ Antes de la hora de su sueño eterno,

[[sirach-46-20]]
^20^ Y después de dormido todavía profetizó
[[sirach-47]]
== Capítulo 47

[[sirach-47-1]]
^1^ Después de él surgió Natán

[[sirach-47-2]]
^2^ Como grasa puesta aparte en el sacrificio de comunión,

[[sirach-47-3]]
^3^ Con leones jugó cual con cabritos,

[[sirach-47-4]]
^4^ ¿No mató de joven al gigante,

[[sirach-47-5]]
^5^ Pues invocó al Señor Altísimo,

[[sirach-47-6]]
^6^ Por eso le dieron gloria por diez mil,

[[sirach-47-7]]
^7^ Pues él aplastó a los enemigos del contorno,

[[sirach-47-8]]
^8^ En todas sus obras elevó acción de gracias

[[sirach-47-9]]
^9^ Ante el altar instituyó salmistas

[[sirach-47-10]]
^10^ Dio a las fiestas esplendor,

[[sirach-47-11]]
^11^ El Señor le perdonó sus pecados

[[sirach-47-12]]
^12^ Después de él surgió un hijo sabio,

[[sirach-47-13]]
^13^ Reinó Salomón en días de paz,

[[sirach-47-14]]
^14^ ¡Qué sabio eras en tu juventud,

[[sirach-47-15]]
^15^ Cubrió tu alma la tierra,

[[sirach-47-16]]
^16^ Tu nombre llegó hasta las islas lejanas,

[[sirach-47-17]]
^17^ Por tus cantos, tus sentencias, tus proverbios

[[sirach-47-18]]
^18^ En nombre del Señor Dios,

[[sirach-47-19]]
^19^ Mas reclinaste tu costado en mujeres,

[[sirach-47-20]]
^20^ Pusiste así tacha a tu gloria,

[[sirach-47-21]]
^21^ hasta quedar partida en dos la dinastía

[[sirach-47-22]]
^22^ Pero el Señor no renuncia jamás a su misericordia,

[[sirach-47-23]]
^23^ Descansó Salomón con sus padres,

[[sirach-47-24]]
^24^ Y Jeroboam, hijo de Nabat, fue el que hizo pecar a Israel,

[[sirach-47-25]]
^25^ Toda clase de maldades frecuentaron,
[[sirach-48]]
== Capítulo 48

[[sirach-48-1]]
^1^ Después surgió el profeta Elías como fuego,

[[sirach-48-2]]
^2^ El atrajo sobre ellos el hambre,

[[sirach-48-3]]
^3^ Por la palabra del Señor cerró los cielos,

[[sirach-48-4]]
^4^ ¡Qué glorioso fuiste, Elías, en tus portentos!

[[sirach-48-5]]
^5^ Tú que despertaste a un cadáver de la muerte

[[sirach-48-6]]
^6^ que hiciste caer a reyes en la ruina,

[[sirach-48-7]]
^7^ oíste en el Sinaí la reprensión,

[[sirach-48-8]]
^8^ ungiste reyes para tomar venganza,

[[sirach-48-9]]
^9^ en torbellino de fuego fuiste arrebatado

[[sirach-48-10]]
^10^ fuiste designado en los reproches futuros,

[[sirach-48-11]]
^11^ Felices aquellos que te vieron

[[sirach-48-12]]
^12^ Cuando Elías en el torbellino quedó envuelto,

[[sirach-48-13]]
^13^ Nada era imposible para él,

[[sirach-48-14]]
^14^ Durante su vida hizo prodigios,

[[sirach-48-15]]
^15^ Con todo esto, el pueblo no se arrepintió,

[[sirach-48-16]]
^16^ Sólo quedó un pueblo reducido,

[[sirach-48-17]]
^17^ Fortificó Ezequías su ciudad

[[sirach-48-18]]
^18^ En sus días, subió Senaquerib,

[[sirach-48-19]]
^19^ Temblaron entonces corazones y manos,

[[sirach-48-20]]
^20^ Invocaron al Señor misericordioso,

[[sirach-48-21]]
^21^ Hirió el real de los asirios,

[[sirach-48-22]]
^22^ Porque hizo Ezequías lo que agrada al Señor,

[[sirach-48-23]]
^23^ En sus días el sol retrocedió,

[[sirach-48-24]]
^24^ Con el poder del espíritu vio el fin de los tiempos,

[[sirach-48-25]]
^25^ Hasta la eternidad reveló el porvenir
[[sirach-49]]
== Capítulo 49

[[sirach-49-1]]
^1^ La memoria de Josías es mixtura de incienso

[[sirach-49-2]]
^2^ El llevó a buen fin la conversión del pueblo,

[[sirach-49-3]]
^3^ Enderezó su corazón hacia el Señor,

[[sirach-49-4]]
^4^ Fuera de David, Ezequías y Josías,

[[sirach-49-5]]
^5^ Pues entregaron a otros su cuerno,

[[sirach-49-6]]
^6^ Prendieron fuego a la elegida ciudad del santuario,

[[sirach-49-7]]
^7^ según la palabra de Jeremías, a quien habían maltratado,

[[sirach-49-8]]
^8^ Ezequiel tuvo la visión de la gloria

[[sirach-49-9]]
^9^ porque se acordó de los enemigos en la tempestad,

[[sirach-49-10]]
^10^ Cuanto a los doce profetas,

[[sirach-49-11]]
^11^ ¿Cómo celebraremos a Zorobabel?

[[sirach-49-12]]
^12^ así como Josué hijo de Josedec!

[[sirach-49-13]]
^13^ También de Nehemías es grande la memoria,

[[sirach-49-14]]
^14^ Nadie fue creado en la tierra igual a Henoc,

[[sirach-49-15]]
^15^ Ni como José nació hombre alguno,

[[sirach-49-16]]
^16^ Sem y Set fueron gloriosos entre los hombres,
[[sirach-50]]
== Capítulo 50

[[sirach-50-1]]
^1^ Simón, hijo de Onías, fue el sumo sacerdote

[[sirach-50-2]]
^2^ El echó los cimientos de la altura doble,

[[sirach-50-3]]
^3^ En sus días fue excavado el depósito de agua,

[[sirach-50-4]]
^4^ El cuidó de su pueblo para evitar su ruina

[[sirach-50-5]]
^5^ ¡Que glorioso era, rodeado de su pueblo,

[[sirach-50-6]]
^6^ Como el lucero del alba en medio de las nubes,

[[sirach-50-7]]
^7^ como el sol que brilla sobre el Templo del Altísimo,

[[sirach-50-8]]
^8^ como flor del rosal en primavera,

[[sirach-50-9]]
^9^ como fuego e incienso en el incensario,

[[sirach-50-10]]
^10^ como olivo floreciente de frutos,

[[sirach-50-11]]
^11^ Cuando se ponía la vestidura de gala

[[sirach-50-12]]
^12^ Y cuando recibía las porciones de manos de los sacerdotes,

[[sirach-50-13]]
^13^ todos los hijos de Aarón en su esplendor,

[[sirach-50-14]]
^14^ Y cuando cumplía el ministerio de los altares

[[sirach-50-15]]
^15^ alargaba su mano a la copa,

[[sirach-50-16]]
^16^ Entonces prorrumpían en gritos los hijos de Aarón,

[[sirach-50-17]]
^17^ Todo el pueblo entonces de repente, en masa,

[[sirach-50-18]]
^18^ Y los salmistas también le alababan con sus voces,

[[sirach-50-19]]
^19^ Y suplicaba el pueblo al Señor Altísimo,

[[sirach-50-20]]
^20^ Entonces bajaba y elevaba sus manos

[[sirach-50-21]]
^21^ Y por segunda vez todos se postraban

[[sirach-50-22]]
^22^ Y ahora bendecid al Dios del universo,

[[sirach-50-23]]
^23^ Que nos dé contento de corazón,

[[sirach-50-24]]
^24^ Que su misericordia sea fiel con nosotros

[[sirach-50-25]]
^25^ Hay dos naciones que mi alma detesta,

[[sirach-50-26]]
^26^ los habitantes de la montaña de Seír, los filisteos

[[sirach-50-27]]
^27^ Instrucción de inteligencia y ciencia

[[sirach-50-28]]
^28^ Feliz quien repase esto a menudo;

[[sirach-50-29]]
^29^ Y si lo practica, para todo será fuerte,
[[sirach-51]]
== Capítulo 51

[[sirach-51-1]]
^1^ Quiero darte gracias, Señor, Rey,

[[sirach-51-2]]
^2^ Pues protector y auxilio has sido para mí,

[[sirach-51-3]]
^3^ según la abundancia de tu misericordia y la gloria de tu

[[sirach-51-4]]
^4^ del ahogo del fuego que me envolvía,

[[sirach-51-5]]
^5^ de la hondura de las entrañas del seol,

[[sirach-51-6]]
^6^ - calumnia de lengua injusta ante el rey.

[[sirach-51-7]]
^7^ Por todas partes me asediaban y no había quien auxiliara,

[[sirach-51-8]]
^8^ Entonces me acordé de tu misericordia, Señor,

[[sirach-51-9]]
^9^ Y elevé de la tierra mi plegaria,

[[sirach-51-10]]
^10^ Clamé al Señor, padre de mi Señor:

[[sirach-51-11]]
^11^ Y mi oración fue escuchada,

[[sirach-51-12]]
^12^ Por eso te daré gracias y te alabaré,

[[sirach-51-13]]
^13^ Siendo joven aún, antes de ir por el mundo,

[[sirach-51-14]]
^14^ a la puerta delante del templo la pedí,

[[sirach-51-15]]
^15^ En su flor, como en racimo que madura,

[[sirach-51-16]]
^16^ Incliné un poco mi oído y la recibí,

[[sirach-51-17]]
^17^ Gracias a ella he hecho progesos,

[[sirach-51-18]]
^18^ Pues decidí ponerla en práctica,

[[sirach-51-19]]
^19^ Mi alma ha luchado por ella,

[[sirach-51-20]]
^20^ Hacia ella endurecé mi alma,

[[sirach-51-21]]
^21^ Mis entrañas se conmovieron por buscarla,

[[sirach-51-22]]
^22^ Me dio el Señor una lengua en recompensa,

[[sirach-51-23]]
^23^ Acercaos a mí, ignorantes,

[[sirach-51-24]]
^24^ ¿Por qué habéis de decir que estáis privados de ella,

[[sirach-51-25]]
^25^ He abierto mi boca y he hablado:

[[sirach-51-26]]
^26^ someted al yugo vuestro cuello,

[[sirach-51-27]]
^27^ Ved con vuestros ojos lo poco que he penado

[[sirach-51-28]]
^28^ Participad de la instrucción con una gran suma de dinero,

[[sirach-51-29]]
^29^ Que vuestra alma se recree en la misericordia del Señor,

[[sirach-51-30]]
^30^ Ejecutad vuestra obra antes del momento fijado,
