[[lamentations]]
= Lamentaciones

[[lamentations-1]]
== Capítulo 1

[[lamentations-1-1]]
^1^ Alef. ¡Cómo, ay, yace solitaria

[[lamentations-1-2]]
^2^ Bet. Llora que llora por la noche,

[[lamentations-1-3]]
^3^ Guímel. Judá está desterrada, en postración

[[lamentations-1-4]]
^4^ Dálet. Las calzadas de Sión están de luto,

[[lamentations-1-5]]
^5^ He. Sus adversarios están a la cabeza,

[[lamentations-1-6]]
^6^ Vau. De la hija de Sión se ha ido

[[lamentations-1-7]]
^7^ Zain. Jerusalén recuerda

[[lamentations-1-8]]
^8^ Jet. Mucho ha pecado Jerusalén,

[[lamentations-1-9]]
^9^ Tet. Su inmundicia se pega a su ropa;

[[lamentations-1-10]]
^10^ Yod. El adversario ha echado mano

[[lamentations-1-11]]
^11^ Kaf. Su pueblo entero gime

[[lamentations-1-12]]
^12^ Lámed. Vosotros, todos los que pasáis por el camino,

[[lamentations-1-13]]
^13^ Mem. Ha lanzado fuego de lo alto,

[[lamentations-1-14]]
^14^ Nun. Ligado ha sido el yugo de mis delitos,

[[lamentations-1-15]]
^15^ Sámek. Ha desechado a todos mis valientes

[[lamentations-1-16]]
^16^ Ain. Por esto lloro yo;

[[lamentations-1-17]]
^17^ Pe. Tiende Sión sus manos:

[[lamentations-1-18]]
^18^ Sade. Justo, justo es Yahveh,

[[lamentations-1-19]]
^19^ Qof. He llamado a mis amantes:

[[lamentations-1-20]]
^20^ Res. ¡Mira, Yahveh, que estoy en angustias!

[[lamentations-1-21]]
^21^ Sin. ¡Oye cómo gimo:

[[lamentations-1-22]]
^22^ Tau. ¡Llegue ante ti toda su maldad,
[[lamentations-2]]
== Capítulo 2

[[lamentations-2-1]]
^1^ Alef. ¡Cómo, ay, ha anublado, en su cólera,

[[lamentations-2-2]]
^2^ Bet. El Señor ha destruido sin piedad

[[lamentations-2-3]]
^3^ Guímel. En el ardor de su cólera ha quebrado

[[lamentations-2-4]]
^4^ Dálet. Ha tensado su arco, igual que un enemigo,

[[lamentations-2-5]]
^5^ He. Se ha portado el Señor como enemigo;

[[lamentations-2-6]]
^6^ Vau. Ha forzado, como a un huerto, su cerca,

[[lamentations-2-7]]
^7^ Zain. El Señor ha rechazado su altar,

[[lamentations-2-8]]
^8^ Jet. Yahveh decidió destruir

[[lamentations-2-9]]
^9^ Tet. Sus puertas en tierra se han hundido,

[[lamentations-2-10]]
^10^ Yod. En tierra están sentados, en silencio,

[[lamentations-2-11]]
^11^ Kaf. Se agotan de lágrimas mis ojos,

[[lamentations-2-12]]
^12^ Lámed. Dicen ellos a sus madres:

[[lamentations-2-13]]
^13^ Mem. ¿A quién te compararé? ¿A quién te asemejaré,

[[lamentations-2-14]]
^14^ Nun. Tus profetas vieron para ti visiones

[[lamentations-2-15]]
^15^ Sámek. Sobre ti baten palmas

[[lamentations-2-16]]
^16^ Pe. Abren su boca contra ti todos tus enemigos; silban y rechinan de dientes, dicen: «¡Nos la hemos tragado! ¡Ah, éste es el Día que esperábamos! ¡Ya lo alcanzamos, ya lo vemos!»

[[lamentations-2-17]]
^17^ Ain. Yahveh ha hecho lo que había resuelto,

[[lamentations-2-18]]
^18^ Sade. ¡Clama, pues, al Señor,

[[lamentations-2-19]]
^19^ Qof. ¡En pie, lanza un grito en la noche,

[[lamentations-2-20]]
^20^ Res. Mira, Yahveh, y considera:

[[lamentations-2-21]]
^21^ Sin. Por tierra yacen en las calles

[[lamentations-2-22]]
^22^ Tau. Como en día solemne congregaste
[[lamentations-3]]
== Capítulo 3

[[lamentations-3-1]]
^1^ Alef. Yo soy el hombre que ha visto la miseria

[[lamentations-3-2]]
^2^ El me ha llevado y me ha hecho caminar

[[lamentations-3-3]]
^3^ Contra mí solo vuelve él y revuelve

[[lamentations-3-4]]
^4^ Bet. Mi carne y mi piel ha consumido,

[[lamentations-3-5]]
^5^ Ha levantado contra mí en asedio

[[lamentations-3-6]]
^6^ Me ha hecho morar en las tinieblas,

[[lamentations-3-7]]
^7^ Guímel. Me ha emparedado y no puedo salir;

[[lamentations-3-8]]
^8^ Aun cuando grito y pido auxilio,

[[lamentations-3-9]]
^9^ Ha cercado mis caminos con piedras sillares,

[[lamentations-3-10]]
^10^ Dálet. Oso en acecho ha sido para mí,

[[lamentations-3-11]]
^11^ Intrincando mis caminos, me ha desgarrado,

[[lamentations-3-12]]
^12^ Ha tensado su arco y me ha fijado

[[lamentations-3-13]]
^13^ He. Ha clavado en mis lomos

[[lamentations-3-14]]
^14^ De todo mi pueblo me he hecho la irrisión,

[[lamentations-3-15]]
^15^ El me ha colmado de amargura,

[[lamentations-3-16]]
^16^ Vau. Ha quebrado mis dientes con guijarro,

[[lamentations-3-17]]
^17^ Mi alma está alejada de la paz,

[[lamentations-3-18]]
^18^ Digo: ¡Ha fenecido mi vigor,

[[lamentations-3-19]]
^19^ Zain. Recuerda mi miseria y vida errante:

[[lamentations-3-20]]
^20^ Lo recuerda, lo recuerda, y se hunde

[[lamentations-3-21]]
^21^ Esto revolveré en mi corazón,

[[lamentations-3-22]]
^22^ Jet. Que el amor de Yahveh no se ha acabado,

[[lamentations-3-23]]
^23^ cada mañana se renuevan:

[[lamentations-3-24]]
^24^ «¡Mi porción es Yahveh, dice mi alma,

[[lamentations-3-25]]
^25^ Tet. Bueno es Yahveh para el que en él espera,

[[lamentations-3-26]]
^26^ Bueno es esperar en silencio

[[lamentations-3-27]]
^27^ Bueno es para el hombre soportar

[[lamentations-3-28]]
^28^ Yod. Que se siente solitario y silencioso,

[[lamentations-3-29]]
^29^ que ponga su boca en el polvo:

[[lamentations-3-30]]
^30^ que tienda la mejilla a quien lo hiere,

[[lamentations-3-31]]
^31^ Kaf. Porque no desecha para siempre

[[lamentations-3-32]]
^32^ si llega a afligir, se apiada luego

[[lamentations-3-33]]
^33^ pues no de corazón humilla él

[[lamentations-3-34]]
^34^ Lámed. Cuando se aplasta bajo el pie

[[lamentations-3-35]]
^35^ cuando se tuerce el derecho de un hombre

[[lamentations-3-36]]
^36^ cuando se causa entuerto a un hombre en su proceso,

[[lamentations-3-37]]
^37^ Mem. ¿Quién habló y ello fue?

[[lamentations-3-38]]
^38^ ¿No salen de la boca del Altísimo

[[lamentations-3-39]]
^39^ ¿De qué, pues, se queja el hombre?

[[lamentations-3-40]]
^40^ Nun. Examinemos nuestros caminos, escudriñémoslos,

[[lamentations-3-41]]
^41^ Alcemos nuestro corazón y nuestras manos

[[lamentations-3-42]]
^42^ Nosotros hemos sido rebeldes y traidores:

[[lamentations-3-43]]
^43^ Sámek. Te has envuelto en cólera y nos has perseguido,

[[lamentations-3-44]]
^44^ te has arropado en una nube

[[lamentations-3-45]]
^45^ basura y abyección nos has hecho

[[lamentations-3-46]]
^46^ Pe. Abren su boca contra nosotros

[[lamentations-3-47]]
^47^ Terror y fosa es nuestra suerte,

[[lamentations-3-48]]
^48^ Arroyos de lágrimas derraman mis ojos

[[lamentations-3-49]]
^49^ Ain. Mis ojos fluyen y no cesan;

[[lamentations-3-50]]
^50^ hasta que mire y vea

[[lamentations-3-51]]
^51^ Me hacen daño mis ojos

[[lamentations-3-52]]
^52^ Sade. Cazar me cazaron como a un pájaro,

[[lamentations-3-53]]
^53^ Sofocaron mi vida en una fosa

[[lamentations-3-54]]
^54^ Sumergieron las aguas mi cabeza,

[[lamentations-3-55]]
^55^ Qof. Invoqué tu Nombre, Yahveh,

[[lamentations-3-56]]
^56^ Tú oíste mi grito: «¡No cierres

[[lamentations-3-57]]
^57^ Te acercaste el día en que te invocaba,

[[lamentations-3-58]]
^58^ Res. Tú has defendido, Señor, la causa de mi alma,

[[lamentations-3-59]]
^59^ Has visto, Yahveh, el entuerto que me hacían:

[[lamentations-3-60]]
^60^ Has visto toda su venganza,

[[lamentations-3-61]]
^61^ Sin. Has oído sus insultos, Yahveh,

[[lamentations-3-62]]
^62^ los labios de mis agresores y sus tramas,

[[lamentations-3-63]]
^63^ Estén sentados o en pie, mira:

[[lamentations-3-64]]
^64^ Tau. Retribúyeles, Yahveh,

[[lamentations-3-65]]
^65^ Dales embotamiento de corazón,

[[lamentations-3-66]]
^66^ ¡Persíguelos con saña, extírpalos
[[lamentations-4]]
== Capítulo 4

[[lamentations-4-1]]
^1^ Alef. ¡Cómo, ay, se ha deslucido, el oro se ha alterado

[[lamentations-4-2]]
^2^ Bet. Los hijos de Sión, los excelentes,

[[lamentations-4-3]]
^3^ Guímel. Hasta los chacales desnudan la teta,

[[lamentations-4-4]]
^4^ Dálet. La lengua del niño de pecho se pega

[[lamentations-4-5]]
^5^ He. Los que comían manjares deliciosos

[[lamentations-4-6]]
^6^ Vau. La culpa de la hija de mi pueblo supera

[[lamentations-4-7]]
^7^ Zain. Más limpios que la nieve eran sus nazireos,

[[lamentations-4-8]]
^8^ Jet. Más ocuro es su semblante que el hollín,

[[lamentations-4-9]]
^9^ Tet. Más dichosos fueron los muertos a cuchillo

[[lamentations-4-10]]
^10^ Yod. Las mismas manos de tiernas mujeres

[[lamentations-4-11]]
^11^ Kaf. Yahveh ha apurado su furor,

[[lamentations-4-12]]
^12^ Lámed. Nunca creyeron los reyes de la tierra

[[lamentations-4-13]]
^13^ Mem. ¡Fue por los pecados de sus profetas,

[[lamentations-4-14]]
^14^ Nun. Titubeaban por las calles como ciegos,

[[lamentations-4-15]]
^15^ Sámek. «¡Apartaos! ¡Un impuro!», les gritaban,

[[lamentations-4-16]]
^16^ Pe. El Rostro de Yahveh los dispersó,

[[lamentations-4-17]]
^17^ Ain. Y aún se consumían nuestros ojos,

[[lamentations-4-18]]
^18^ Sade. Se acechaban nuestros pasos,

[[lamentations-4-19]]
^19^ Qof. Nuestros perseguidores eran raudos,

[[lamentations-4-20]]
^20^ Res. Nuestro aliento vital, el ungido de Yahveh,

[[lamentations-4-21]]
^21^ Sin. ¡Regocíjate, exulta, hija de Edom,

[[lamentations-4-22]]
^22^ Tau. ¡Se ha borrado tu culpa, hija de Sión;
[[lamentations-5]]
== Capítulo 5

[[lamentations-5-1]]
^1^ ¡Acuérdate, Yahveh, de lo que nos ha sobrevenido,

[[lamentations-5-2]]
^2^ Nuestra heredad ha pasado a extranjeros,

[[lamentations-5-3]]
^3^ Somos huérfanos, sin padre;

[[lamentations-5-4]]
^4^ A precio de plata bebemos nuestra agua,

[[lamentations-5-5]]
^5^ El yugo a nuestro cuello, andamos acosados;

[[lamentations-5-6]]
^6^ Hacia Egipto tendemos nuestra mano,

[[lamentations-5-7]]
^7^ Nuestros padres pecaron: ya no existen;

[[lamentations-5-8]]
^8^ Esclavos nos dominan,

[[lamentations-5-9]]
^9^ A riesgo de la vida logramos nuestro pan,

[[lamentations-5-10]]
^10^ Nuestra piel abrasa como un horno,

[[lamentations-5-11]]
^11^ Han violado a las mujeres en Sión,

[[lamentations-5-12]]
^12^ Colgados fueron por sus manos los príncipes;

[[lamentations-5-13]]
^13^ Han arrastrado la muela los muchachos,

[[lamentations-5-14]]
^14^ Los ancianos han dejado de acudir a la puerta,

[[lamentations-5-15]]
^15^ Ha cesado la alegría de nuestro corazón,

[[lamentations-5-16]]
^16^ Ha caído la corona de nuestra cabeza. ¡Ay de nosotros, que

[[lamentations-5-17]]
^17^ Por eso está dolorido nuestro corazón,

[[lamentations-5-18]]
^18^ por el monte Sión, que está asolado;

[[lamentations-5-19]]
^19^ Mas tú, Yahveh, para siempre te sientas;

[[lamentations-5-20]]
^20^ ¿Por qué has de olvidarnos para siempre,

[[lamentations-5-21]]
^21^ ¡Haznos volver a ti, Yahveh, y volveremos.

[[lamentations-5-22]]
^22^ si es que no nos has desechado totalmente,
