[[daniel]]
= Daniel

[[daniel-1]]
== Capítulo 1

[[daniel-1-1]]
^1^ El año tercero del reinado de Yoyaquim, rey de Judá, Nabucodonosor, rey de Babilonia, vino a Jerusalén y la sitió.

[[daniel-1-2]]
^2^ El Señor entregó en sus manos a Yoyaquim rey de Judá, así como parte de los objetos de la Casa de Dios. El los llevó al país de Senaar y depositó los objetos en la casa del tesoro de sus dioses.

[[daniel-1-3]]
^3^ El rey mandó a Aspenaz, jefe de sus eunucos, tomar de entre los israelitas de estirpe real o de familia noble,

[[daniel-1-4]]
^4^ algunos jóvenes, sin defecto corporal, de buen parecer, instruidos en toda sabiduría, cultos e inteligentes, idóneos para servir en la corte del rey, con el fin de enseñarles la escritura y la lengua de los caldeos.

[[daniel-1-5]]
^5^ El rey les asignó una ración diaria de los manjares del rey y del vino de su mesa. Deberían ser educados durante tres años, después de lo cual entrarían al servicio del rey.

[[daniel-1-6]]
^6^ Entre ellos se encontraban Daniel, Ananías, Misael y Azarías, que eran judíos.

[[daniel-1-7]]
^7^ El jefe de los eunucos les puso nombres nuevos: Daniel se llamaría Beltsassar, Ananías Sadrak, Misael Mesak y Azarías Abed Negó.

[[daniel-1-8]]
^8^ Daniel, que tenía el propósito de no mancharse compartiendo los manjares del rey y el vino de su mesa, pidió al jefe de los eunucos permiso para no mancharse.

[[daniel-1-9]]
^9^ Dios concedió a Daniel hallar gracia y benevolencia ante el jefe de los eunucos.

[[daniel-1-10]]
^10^ Pero el jefe de los eunucos dijo a Daniel: «Temo al rey, mi señor; él ha asignado vuestra comida y vuestra bebida, y si llega a ver vuestros rostros más macilentos que los de los jóvenes de vuestra edad, expondríais mi cabeza a los ojos del rey».

[[daniel-1-11]]
^11^ Daniel dijo entonces al guarda a quien el jefe de los eunucos había confiado el cuidado de Daniel, Ananías, Misael y Azarías:

[[daniel-1-12]]
^12^ «Por favor, pon a prueba a tus siervos durante diez días: que nos den de comer legumbres y de beber agua;

[[daniel-1-13]]
^13^ después puedes comparar nuestro aspecto con el de los jóvenes que comen los manjares del rey, y hacer con tus siervos con arreglo a lo que hayas visto».

[[daniel-1-14]]
^14^ Aceptó él la propuesta y les puso a prueba durante diez días.

[[daniel-1-15]]
^15^ Al cabo de los diez días se vio que tenían mejor aspecto y estaban más rollizos que todos los jóvenes que comían los manjares del rey.

[[daniel-1-16]]
^16^ Desde entonces el guarda retiró sus manjares y el vino que tenían que beber, y les dio legumbres.

[[daniel-1-17]]
^17^ A estos cuatro jóvenes les concedió Dios ciencia e inteligencia en toda clase de letras y sabiduría. Particularmente Daniel poseía el discernimiento de visiones y sueños.

[[daniel-1-18]]
^18^ Al cabo del tiempo establecido por el rey para que le fueran presentados los jóvenes, el jefe de los eunucos los llevó ante Nabucodonosor.

[[daniel-1-19]]
^19^ El rey conversó con ellos, y entre todos no se encontró ningún otro como Daniel, Ananías, Misael y Azarías. Quedaron, pues, al servicio del rey.

[[daniel-1-20]]
^20^ Y en cuantas cosas de sabiduría o de inteligencia les consultó el rey, los encontró diez veces superiores a todos los magos y adivinos que había en todo su reino.

[[daniel-1-21]]
^21^ Daniel permaneció allí hasta el año primero del rey Ciro.
[[daniel-2]]
== Capítulo 2

[[daniel-2-1]]
^1^ El año segundo del reinado de Nabucodonosor, Nabucodonosor tuvo sueños, y su espíritu se turbó hasta el punto de no poder dormir.

[[daniel-2-2]]
^2^ El rey mandó llamar a los magos y adivinos, encantadores y caldeos para que manifestaran al rey sus sueños. Vinieron ellos y se presentaron al rey.

[[daniel-2-3]]
^3^ El rey les dijo: «He tenido un sueño y mi espíritu se ha turbado por el deseo de comprender este sueño».

[[daniel-2-4]]
^4^ Los caldeos respondieron al rey: (Arameo) «¡Viva el rey eternamente! Cuenta el sueño a tus siervos, y nosotros te daremos su interpretación».

[[daniel-2-5]]
^5^ Respondió el rey y dijo a los caldeos: «Tened bien presente mi decisión: si no me dais a conocer el sueño y su interpretación, seréis cortados en pedazos y vuestras casas serán reducidas a escombros.

[[daniel-2-6]]
^6^ Pero si me dais a conocer el sueño y su interpretación, recibiréis de mí regalos, obsequios y grandes honores. Así pues, dadme a conocer el sueño y su interpretación».

[[daniel-2-7]]
^7^ Respondieron ellos por segunda vez: «Cuente el rey el sueño a sus siervos, que nosotros le daremos su interpretación».

[[daniel-2-8]]
^8^ Pero el rey replicó: «Bien veo que lo que queréis vosotros es ganar tiempo, sabiendo que mi decisión está tomada.

[[daniel-2-9]]
^9^ Si no me dais a conocer el sueño, una misma será vuestra sentencia. Habéis acordado entre vosotros decirme palabras mentirosas y falsas, mientras cambian los tiempos. Por tanto, indicadme el sueño y sabré que podéis darme su interpretación».

[[daniel-2-10]]
^10^ Los caldeos respondieron ante el rey: «No hay nadie en el mundo capaz de descubrir lo que quiere el rey; y por eso mismo ningún rey, por grande y poderoso que sea, pregunta jamás cosa semejante a ningún mago, adivino o caldeo.

[[daniel-2-11]]
^11^ Lo que el rey pide es difícil, y nadie se lo puede descubrir al rey, excepto los dioses; pero ellos no viven entre los seres de carne».

[[daniel-2-12]]
^12^ Entonces el rey se enfureció terriblemente y mandó matar a todos los sabios de Babilonia.

[[daniel-2-13]]
^13^ Promulgado el decreto de matar a los sabios, se buscó también a Daniel y a sus compañeros para matarlos.

[[daniel-2-14]]
^14^ Pero Daniel se dirigió con palabras sabias y prudentes a Aryok, jefe de la guardia real, que se disponía a matar a los sabios de Babilonia.

[[daniel-2-15]]
^15^ Tomó la palabra y dijo a Aryok, oficial del rey: «Por qué ha dado el rey un decreto tan tajante?» Aryok explicó la cosa a Daniel,

[[daniel-2-16]]
^16^ y Daniel se fue a pedir al rey que se le concediese un plazo para declarar al rey la interpretación.

[[daniel-2-17]]
^17^ Daniel regresó a su casa e informó del caso a sus compañeros Ananías, Misael y Azarías,

[[daniel-2-18]]
^18^ invitándoles a implorar la misericordia del Dios del Cielo, acerca de este misterio, a fin de que no se diese muerte a Daniel y a sus compañeros con el resto de los sabios de Babilonia.

[[daniel-2-19]]
^19^ Entonces el misterio fue revelado a Daniel en una visión nocturna. Y Daniel bendijo al Dios del Cielo.

[[daniel-2-20]]
^20^ Tomó Daniel la palabra y dijo: «Bendito sea el Nombre de Dios por los siglos de los siglos, pues suyos son el saber y la fuerza.

[[daniel-2-21]]
^21^ El hace alternar estaciones y tiempos, depone a los reyes, establece a los reyes, da a los sabios sabiduría, y ciencia a los que saben discernir.

[[daniel-2-22]]
^22^ El revela honduras y secretos, conoce lo que ocultan las tinieblas, y la luz mora junto a él.

[[daniel-2-23]]
^23^ A ti, Dios de mis padres, doy yo gracias y alabo, porque me has concedido sabiduría y fuerza; y ahora me has dado a conocer lo que te habíamos pedido, la cosa del rey nos has dado a conocer».

[[daniel-2-24]]
^24^ Después Daniel se fue donde Aryok, a quien el rey había encomendado la matanza de los sabios de Babilonia. Entró y le dijo: «No mates a los sabios de Babilonia. Llévame a la presencia del rey y yo declararé al rey la interpretación».

[[daniel-2-25]]
^25^ Aryok se apresuró a introducir a Daniel ante el rey y le dijo: «He encontrado entre los deportados de Judá un hombre que puede dar a conocer al rey la interpretación».

[[daniel-2-26]]
^26^ Tomó el rey la palabra y dijo a Daniel (por sobrenombre Beltsassar): «¿Eres tú capaz de darme a conocer el sueño que he tenido y su interpretación?»

[[daniel-2-27]]
^27^ Daniel tomó la palabra en presencia del rey y dijo: «El misterio que el rey quiere saber, no hay sabios, adivinos, magos ni astrólogos que lo puedan revelar al rey;

[[daniel-2-28]]
^28^ pero hay un Dios en el cielo, que revela los misterios y que ha dado a conocer al rey Nabucodonosor lo que sucederá al fin de los días. Tu sueño y las visiones de tu cabeza cuando estabas en tu lecho eran éstos:

[[daniel-2-29]]
^29^ «Oh rey, los pensamientos que agitaban tu mente en el lecho se referían a lo que ha de suceder en el futuro, y el que revela los misterios te ha dado a conocer lo que sucederá.

[[daniel-2-30]]
^30^ A mí, sin que yo posea más sabiduría que cualquier otro ser viviente, se me ha revelado este misterio con el solo fin de dar a conocer al rey su interpretación y de que tú conozcas los pensamientos de tu corazón.

[[daniel-2-31]]
^31^ «Tú, oh rey, has tenido esta visión: una estatua, una enorme estatua, de extraordinario brillo, de aspecto terrible, se levantaba ante ti.

[[daniel-2-32]]
^32^ La cabeza de esta estatua era de oro puro, su pecho y sus brazos de plata, su vientre y sus lomos de bronce,

[[daniel-2-33]]
^33^ sus piernas de hierro, sus pies parte de hierro y parte de arcilla.

[[daniel-2-34]]
^34^ Tú estabas mirando, cuando de pronto una piedra se desprendió, sin intervención de mano alguna, vino a dar a la estatua en sus pies de hierro y arcilla, y los pulverizó.

[[daniel-2-35]]
^35^ Entonces quedó pulverizado todo a la vez: hierro, arcilla, bronce, plata y oro; quedaron como el tamo de la era en verano, y el viento se lo llevó sin dejar rastro. Y la piedra que había golpeado la estatua se convirtió en un gran monte que llenó toda la tierra.

[[daniel-2-36]]
^36^ Tal fue el sueño: ahora diremos ante el rey su interpretación.

[[daniel-2-37]]
^37^ Tú, oh rey, rey de reyes, a quien el Dios del cielo ha dado reino, fuerza, poder y gloria

[[daniel-2-38]]
^38^ - los hijos de los hombres, las bestias del campo, los pájaros del cielo, dondequiera que habiten, los ha dejado en tus manos y te ha hecho soberano de ellos -, tú eres la cabeza de oro.

[[daniel-2-39]]
^39^ Después de ti surgirá otro reino, inferior a ti, y luego un tercer reino, de bronce, que dominará la tierra entera.

[[daniel-2-40]]
^40^ Y habrá un cuarto reino, duro como el hierro, como el hierro que todo lo pulveriza y machaca: como el hierro qué aplasta, así él pulverizará y aplastará a todos los otros.

[[daniel-2-41]]
^41^ Y lo que has visto, los pies y los dedos, parte de arcilla de alfarero y parte de hierro, es un reino que estará dividido; tendrá la solidez del hierro, según has visto el hierro mezclado con la masa de arcilla.

[[daniel-2-42]]
^42^ Los dedos de los pies, parte de hierro y parte de arcilla, es que el reino será en parte fuerte y en parte fragil.

[[daniel-2-43]]
^43^ Y lo que has visto: el hierro mezclado con la masa de arcilla, es que se mezclarán ellos entre sí por simiente humana, pero no se aglutinarán el uno al otro, de la misma manera que el hierro no se mezcla con la arcilla.

[[daniel-2-44]]
^44^ En tiempo de estos reyes, el Dios del cielo hará surgir un reino que jamás será destruido, y este reino no pasará a otro pueblo. Pulverizará y aniquilará a todos estos reinos, y él subsistirá eternamente:

[[daniel-2-45]]
^45^ tal como has visto desprenderse del monte, sin intervención de mano humana, la piedra que redujo a polvo el hierro, el bronce, la arcilla, la plata y el oro. El Dios grande ha dado a conocer al rey lo que ha de suceder. Tal es verdaderamente el sueño, y su interpretación digna de confianza».

[[daniel-2-46]]
^46^ Entonces el rey Nabucodonosor cayó rostro en tierra, se postró ante Daniel, y ordenó que se le ofreciera oblación y calmante aroma.

[[daniel-2-47]]
^47^ El rey tomó la palabra y dijo a Daniel: «Verdaderamente vuestro Dios es el Dios de los dioses y el señor de los reyes, el revelador de los misterios, ya que tú has podido revelar este misterio».

[[daniel-2-48]]
^48^ Y el rey confirió a Daniel un alto rango y le dio muchos y magníficos regalos. Le hizo gobernador de toda la provincia de Babilonia y jefe supremo de todos los sabios de Babilonia.

[[daniel-2-49]]
^49^ Daniel pidió al rey que encargara de la administración de la provincia de Babilonia a Sadrak, Mesak y Abed Negó, quedando Daniel en la corte del rey.
[[daniel-3]]
== Capítulo 3

[[daniel-3-1]]
^1^ El rey Nabucodonosor hizo una estatua de oro, de sesenta codos de alta por seis de ancha, y la erigió en el llano de Dura, en la provincia de Babilonia.

[[daniel-3-2]]
^2^ El rey Nabucodonosor mandó a los sátrapas, prefectos, gobernadores, consejeros, tesoreros, juristas y jueces y a todas las autoridades provinciales, que se reuniran y asistieran a la dedicación de la estatua erigida por el rey Nabucodonosor.

[[daniel-3-3]]
^3^ Se reunieron, pues, los sátrapas, prefectos, gobernadores, consejeros, tesoreros, juristas y jueces y todas las autoridades provinciales para la dedicación de la estatua erigida por el rey Nabucodonosor; todos estaban en pie ante la estatua erigida por el rey Nabucodonosor.

[[daniel-3-4]]
^4^ El heraldo pregonó con fuerza: «A vosotros, pueblos, naciones y lenguas, se os hace saber:

[[daniel-3-5]]
^5^ En el momento en que oigáis el cuerno, el pífano, la cítara, la sambuca, el salterio, la zampoña y toda clase de música, os postraréis y adoraréis la estatua de oro que ha erigido el rey Nabucodonosor.

[[daniel-3-6]]
^6^ Aquél que no se postre y la adore, será inmediatamente arrojado en el horno de fuego ardiente».

[[daniel-3-7]]
^7^ Con tal motivo, en cuanto se oyó sonar el cuerno, el pífano, la cítara, la sambuca, el salterio, la zampoña y toda clase de música, todos los pueblos, naciones y lenguas se postraron y adoraron la estatua de oro que había erigido el rey Nabucodonosor.

[[daniel-3-8]]
^8^ Sin embargo, algunos caldeos se presentaron a denunciar a los judíos.

[[daniel-3-9]]
^9^ Tomaron la palabra y dijeron al rey Nabucodonosor: «¡Viva el rey eternamente!

[[daniel-3-10]]
^10^ Tú, oh rey, has ordenado que todo hombre, en cuanto oiga sonar el cuerno, el pífano, la cítara, la sambuca, el salterio, la zampoña y toda clase de música, se postre y adore la estatua de oro,

[[daniel-3-11]]
^11^ y que aquél que no se postre para adorarla sea arrojado en el horno de fuego ardiente.

[[daniel-3-12]]
^12^ Pues hay algunos judíos a quienes has encargado de la administración de la provincia de Babilonia: Sadrak, Mesak y Abed Negó, que no te hacen caso, oh rey; no sirven a tu dios ni adoran la estatua de oro que has erigido».

[[daniel-3-13]]
^13^ Ebrio de cólera, Nabucodonosor mandó llamar a Sadrak, Mesak y Abed Negó, que fueron introducidos ante el rey.

[[daniel-3-14]]
^14^ Nabucodonosor tomó la palabra y dijo: «¿Es verdad, Sadrak, Mesak y Abed Negó, que no servís a mis dioses ni adoráis la estatua de oro que yo he erigido?

[[daniel-3-15]]
^15^ ¿Estáis dispuestos ahora, cuando oigáis sonar el cuerno, el pífano, la cítara, la sambuca, el salterio, la zampoña y toda clase de música, a postraros y adorar la estatua que yo he hecho? Si no la adoráis, seréis inmediatamente arrojados en el horno de fuego ardiente; y ¿qué dios os podrá librar de mis manos?»

[[daniel-3-16]]
^16^ Sadrak, Mesak y Abed Negó tomaron la palabra y dijeron al rey Nabucodonosor: «No necesitamos darte una respuesta sobre este particular.

[[daniel-3-17]]
^17^ Si nuestro Dios, a quien servimos, es capaz de librarnos, nos librará del horno de fuego ardiente y de tu mano, oh rey;

[[daniel-3-18]]
^18^ y si no lo hace, has de saber, oh rey, que nosotros no serviremos a tus dioses ni adoraremos la estatua de oro que has erigido».

[[daniel-3-19]]
^19^ Entonces el rey Nabucodonosor, lleno de cólera y demudada la expresión de su rostro contra Sadrak, Mesak y Abed Negó, dio orden de que se encendiese el horno siete veces más de lo corriente,

[[daniel-3-20]]
^20^ y mandó a los hombres más fuertes de su ejército que ataran a Sadrak, Mesak y Abed Negó y los arrojaran al horno de fuego ardiente.

[[daniel-3-21]]
^21^ Fueron, pues, atados estos hombres, con sus zaragüelles, túnicas, gorros y vestidos, y arrojados al horno de fuego ardiente.

[[daniel-3-22]]
^22^ Como la orden del rey era perentoria y el horno estaba excesivamente encendido, la llamarada mató a los hombres que habían llevado allá a Sadrak, Mesak y Abed Negó.

[[daniel-3-23]]
^23^ Y los tres hombres, Sadrak, Mesak y Abed Negó, cayeron, atados, en medio del horno de fuego ardiente.

[[daniel-3-24]]
^24^ Iban ellos por entre las llamas alabando a Dios y bendiciendo al Señor.

[[daniel-3-25]]
^25^ Y Azarías, de pie en medio del fuego, tomó la palabra y oró así:

[[daniel-3-26]]
^26^ «Bendito seas, Señor, Dios de nuestros padres, digno de loor, y tu nombre sea glorificado eternamente.

[[daniel-3-27]]
^27^ Porque eres justo en todo lo que nos has hecho, todas tus obras son verdad, rectos todos tus caminos, verdad todos tus juicios.

[[daniel-3-28]]
^28^ Juicio fiel has hecho en todo lo que sobre nosotros has traído, y sobre la ciudad santa de nuestros padres, Jerusalén. Pues con verdad y justicia has provocado todo esto, por nuestros pecados.

[[daniel-3-29]]
^29^ Sí, pecamos, obramos inicuamente alejándonos de ti, sí, mucho en todo pecamos, no dimos oído a tus mandamientos,

[[daniel-3-30]]
^30^ no los observamos, no cumplimos lo que se nos mandaba para nuestro bien.

[[daniel-3-31]]
^31^ Sí, todo lo que sobre nosotros has traído, todo lo que nos has hecho, con juicio fiel lo has hecho.

[[daniel-3-32]]
^32^ Nos has entregado en manos de nuestros enemigos, gentes sin ley, pésimos impíos, en manos de un rey injusto, el más perverso de la tierra toda.

[[daniel-3-33]]
^33^ Y hoy no podemos abrir nuestra boca, la vergüenza y el oprobio han alcanzado a los que te sirven y te adoran.

[[daniel-3-34]]
^34^ ¡Oh, no nos abandones para siempre, - por amor de tu nombre - no repudies tu alianza,

[[daniel-3-35]]
^35^ no nos retires tu misericordia, por Abraham tu amado, por Isaac tu siervo, por Israel tu santo,

[[daniel-3-36]]
^36^ a quienes tú prometiste multiplicar su linaje como las estrellas del cielo y como la arena de la orilla del mar!

[[daniel-3-37]]
^37^ Señor, que somos más pequeños que todas las naciones, que hoy estamos humillados en toda la tierra, por causa de nuestros pecados;

[[daniel-3-38]]
^38^ ya no hay, en esta hora, príncipe, profeta ni caudillo, holocausto, sacrificio, oblación ni incienso ni lugar donde ofrecerte las primicias,

[[daniel-3-39]]
^39^ y hallar gracia a tus ojos. Mas con alma contrita y espíritu humillado te seamos aceptos, como con holocaustos de carneros y toros, y con millares de corderos pingües;

[[daniel-3-40]]
^40^ tal sea hoy nuestro sacrificio ante ti, y te agrade que plenamente te sigamos, porque no hay confusión para los que en ti confian.

[[daniel-3-41]]
^41^ Y ahora te seguimos de todo corazón, te tememos y buscamos tu rostro. No nos dejes en la confusión,

[[daniel-3-42]]
^42^ trátanos conforme a tu bondad y según la abundancia de tu misericordia.

[[daniel-3-43]]
^43^ Líbranos según tus maravillas, y da, Señor, gloria a tu nombre.

[[daniel-3-44]]
^44^ Sean confundidos los que a tus siervos hacen daño, queden cubiertos de vergüenza, privados de todo su poder, sea aplastada su fuerza.

[[daniel-3-45]]
^45^ Y sepan que tú eres el único Dios y Señor, glorioso por toda la tierra».

[[daniel-3-46]]
^46^ Los siervos del rey que los habían arrojado al horno no cesaban de atizar el fuego con nafta, pez, estopa y sarmientos,

[[daniel-3-47]]
^47^ tanto que la llama se elevaba por encima del horno hasta cuarenta y nueve codos,

[[daniel-3-48]]
^48^ y al extenderse abrasó a los caldeos que encontró alrededor del horno.

[[daniel-3-49]]
^49^ Pero el ángel del Señor bajó al horno junto a Azarías y sus compañeros, empujó fuera del horno la llama de fuego,

[[daniel-3-50]]
^50^ y les sopló, en medio del horno, como un frescor de brisa y de rocío, de suerte que el fuego nos los tocó siquiera ni les causó dolor ni molestia.

[[daniel-3-51]]
^51^ Entonces los tres, a coro, se pusieron a cantar, glorificando y bendiciendo a Dios dentro del horno, y diciendo:

[[daniel-3-52]]
^52^ «Bendito seas, Señor, Dios de nuestros padres, loado, exaltado eternamente. Bendito el santo nombre de tu gloria, loado, exaltado eternamente.

[[daniel-3-53]]
^53^ Bendito seas en el templo de tu santa gloria, cantado, enaltecido eternamente.

[[daniel-3-54]]
^54^ Bendito seas en el trono de tu reino, cantado, exaltado eternamente.

[[daniel-3-55]]
^55^ Bendito tú, que sondas los abismos, que te sientas sobre querubines, loado, exaltado eternamente.

[[daniel-3-56]]
^56^ Bendito seas en el firmamento del cielo, cantado, glorificado eternamente.

[[daniel-3-57]]
^57^ Obras todas del Señor, bendecid al Señor, cantadle, exaltadle eternamente.

[[daniel-3-58]]
^58^ Angeles del Señor, bendecid al Señor, cantadle, exaltadle eternamente.

[[daniel-3-59]]
^59^ Cielos, bendecid al Señor, cantadle, exaltadle eternamente.

[[daniel-3-60]]
^60^ Aguas todas que estáis sobre los cielos, bendecid al Señor, cantadle, exaltadle eternamente.

[[daniel-3-61]]
^61^ Potencias todas del Señor, bendecid al Señor, cantadle, exaltadle eternamente.

[[daniel-3-62]]
^62^ Sol y luna, bendecid al Señor, cantadle, exaltadle eternamente.

[[daniel-3-63]]
^63^ Astros del cielo, bendecid al Señor, cantadle, exaltadle eternamente.

[[daniel-3-64]]
^64^ Lluvia toda y rocío, bendecid al Señor, cantadle, exaltadle eternamente.

[[daniel-3-65]]
^65^ Vientos todos, bendecid al Señor, cantadle, exaltadle eternamente.

[[daniel-3-66]]
^66^ Fuego y calor, bendecid al Señor, cantadle, exaltadle eternamente.

[[daniel-3-67]]
^67^ Frío y ardor, bendecid al Señor, cantadle, exaltadle eternamente.

[[daniel-3-68]]
^68^ Rocíos y escarchas, bendecid al Señor, cantadle, exaltadle eternamente.

[[daniel-3-69]]
^69^ Hielos y frío, bendecid al Señor, cantadle, exaltadle eternamente.

[[daniel-3-70]]
^70^ Heladas y nieves, bendecid al Señor, cantadle, exaltadle eternamente.

[[daniel-3-71]]
^71^ Noches y días, bendecid al Señor, cantadle, exaltadle eternamente.

[[daniel-3-72]]
^72^ Luz y tinieblas, bendecid al Señor, cantadle, exaltadle eternamente.

[[daniel-3-73]]
^73^ Rayos y nubes, bendecid al Señor, cantadle, exaltadle eternamente.

[[daniel-3-74]]
^74^ Bendiga la tierra al Señor, le cante, le exalte eternamente.

[[daniel-3-75]]
^75^ Montes y colinas, bendecid al Señor, cantadle, exaltadle eternamente.

[[daniel-3-76]]
^76^ Todo lo que germina en la tierra, bendecid al Señor, cantadle, exaltadle eternamente.

[[daniel-3-77]]
^77^ Fuentes, bendecid al Señor, cantadle, exaltadle eternamente.

[[daniel-3-78]]
^78^ Mares y ríos, bendecid al Señor, cantadle, exaltadle eternamente.

[[daniel-3-79]]
^79^ Cetáceos y todo lo que se mueve en las aguas, bendecid al Señor, cantadle, exaltadle eternamente.

[[daniel-3-80]]
^80^ Pájaros todos del cielo, bendecid al Señor, cantadle, exaltadle eternamente.

[[daniel-3-81]]
^81^ Fieras todas y bestias, bendecid al Señor, cantadle, exaltadle eternamente.

[[daniel-3-82]]
^82^ Hijos de los hombres, bendecid al Señor, cantadle, exaltadle eternamente.

[[daniel-3-83]]
^83^ Israel, bendice al Señor, cantadle, exaltadle eternamente.

[[daniel-3-84]]
^84^ Sacerdotes del Señor, bendecid al Señor, cantadle, exaltadle eternamente.

[[daniel-3-85]]
^85^ Siervos del Señor, bendecid al Señor, cantadle, exaltadle eternamente.

[[daniel-3-86]]
^86^ Espíritus y almas de los justos, bendecid al Señor, cantadle, exaltadle eternamente.

[[daniel-3-87]]
^87^ Santos y humildes de corazón, bendecid al Señor, cantadle, exaltadle eternamente.

[[daniel-3-88]]
^88^ Ananías, Azarías, Misael, bendecid al Señor, cantadle, exaltadle eternamente. Porque él nos ha arrancado del infierno, nos ha salvado de la mano del la muerte, nos ha sacado del horno de llama abrasadora, nos ha rescatado de en medio de la llama.

[[daniel-3-89]]
^89^ Dad gracias al Señor, porque es bueno, porque es eterna su misericordia.

[[daniel-3-90]]
^90^ Todos los que veneráis al Señor, bendecid al Dios de los de los dioses, cantadle, dadle gracias, porque es eterna su misericordia».

[[daniel-3-91]]
^91^ Entonces el rey Nabucodonosor, estupefacto, se levantó a toda prisa y preguntó a sus consejeros: «¿No hemos echado nosotros al fuego a estos tres hombres atados?» Respondieron ellos: «Indudablemente, oh rey».

[[daniel-3-92]]
^92^ Dijo el rey: «Pero yo estoy viendo cuatro hombres que se pasean libremente por el fuego sin sufrir daño alguno, y el cuarto tiene el aspecto de un hijo de los dioses».

[[daniel-3-93]]
^93^ Y Nabucodonosor se acercó a la boca del horno de fuego ardiente y dijo: «Sadrak, Mesak y Abed Negó, servidores del Dios Altísimo, salid y venid aquí». Entonces Sadrak, Mesak y Abed Negó salieron de en medio del fuego.

[[daniel-3-94]]
^94^ Los sátrapas, prefectos, gobernadores y consejeros del rey se reunieron para ver a estos hombres: el fuego no había tenido ningún poder sobre su cuerpo, los cabellos de su cabeza no estaban chamuscados, sus mantos no se habían alterado, y ni el olor del fuego se les había pegado.

[[daniel-3-95]]
^95^ Nabucodonosor exclamó: «Bendito sea el Dios de Sadrak, Mesak y Abed Negó, que ha enviado a su ángel a librar a sus siervos que, confiando en él, quebrantaron la orden del rey y entregaron su cuerpo antes que servir y adorar a ningún otro fuera de su Dios.

[[daniel-3-96]]
^96^ Y yo promulgo este edicto: Pueblos, naciones y lenguas, todo aquel que hable ligeramente del Dios de Sadrak, Mesak y Abed Negó, será cortado en pedazos y su casa será reducida a escombros, porque no hay otro dios que pueda salvar de este modo».

[[daniel-3-97]]
^97^ Y el rey hizo prosperar a Sadrak, Mesak y Abed Negó en la provincia de Babilonia.

[[daniel-3-98]]
^98^ Nabucodonosor, Rey, a todos los pueblos, naciones y lenguas de toda la tierra: ¡Sea grande vuestra paz!

[[daniel-3-99]]
^99^ Me ha parecido bien daros a conocer las señales y milagros que ha hecho el Dios Altísimo.

[[daniel-3-100]]
^100^ ¡Que grandes sus prodigios, qué poderosos sus milagros! ¡Reino eterno es su reino, su imperio de generación en generación!
[[daniel-4]]
== Capítulo 4

[[daniel-4-1]]
^1^ Yo, Nabucodonosor, estaba tranquilo en mi casa, y satisfecho en mi palacio.

[[daniel-4-2]]
^2^ Y tuve un sueño que me aterrorizó. Las obsesiones que tuve en mi lecho y las visiones de mi cabeza me aterraron.

[[daniel-4-3]]
^3^ Entonces di orden de traer a mi presencia a todos los sabios de Babilonia para que me dieran a conocer la interpretación del sueño.

[[daniel-4-4]]
^4^ Vinieron los magos, adivinos, caldeos y astrólogos y, en su presencia, conté el sueño, pero su interpretación no me la dieron.

[[daniel-4-5]]
^5^ Después se presentó ante mí Daniel, por sobrenombre Beltsassar, según el nombre de mi dios, en quien reside el espíritu de los dioses santos. Yo le conté el sueño:

[[daniel-4-6]]
^6^ «Beltsassar, jefe de los magos, ya sé que tú posees el espíritu de los dioses santos y que ningún misterio ofrece para ti dificultad: mira el sueño que he tenido; dime su interpretación.

[[daniel-4-7]]
^7^ «En mi lecho, contemplaba las visiones de mi cabeza: «Un árbol había en el centro de la tierra, de altura muy grande.

[[daniel-4-8]]
^8^ El árbol creció, se hizo corpulento, su altura llegaba hasta el cielo, su expansión, hasta los confines de la tierra.

[[daniel-4-9]]
^9^ Era hermoso su ramaje, abundante su fruto; había en él comida para todos, a su sombra se cobijaban las bestias del campo, en sus ramas anidaban los pájaros del cielo, y toda carne se alimentaba de él.

[[daniel-4-10]]
^10^ Yo contemplaba, en mi lecho, las visiones de mi cabeza. En esto, un Vigilante, un santo, bajaba del cielo.

[[daniel-4-11]]
^11^ Con recia voz gritaba así: “Abatid el árbol, cortad sus ramas, arrancad sus hojas, tirad sus frutos; váyanse las bestias de debajo de él, y los pájaros de sus ramas.

[[daniel-4-12]]
^12^ Pero dejad en tierra tocón y raíces con ataduras de hierro y bronce, entre la hierba del campo. Sea bañado del rocío del cielo y comparta con las bestias la hierba de la tierra.

[[daniel-4-13]]
^13^ Deje de ser su corazón de hombre, désele un corazón de bestia y pasen por él siete tiempos.

[[daniel-4-14]]
^14^ Es la sentencia dictada por los Vigilantes, la cuestión decidida por los Santos, para que sepa todo ser viviente que el Altísimo domina sobre el reino de los hombres: se lo da a quien le place y exalta al más humilde de los hombres.”»

[[daniel-4-15]]
^15^ «Tal es el sueño que he tenido yo, el rey Nabucodonosor. Tú, Beltsassar, dime su interpretación, ya que ninguno de los sabios de mi reino ha podido darme a conocer su interpretación; pero tú puedes, porque en ti reside el espíritu de los dioses santos».

[[daniel-4-16]]
^16^ Entonces Daniel, por sobrenombre Beltsassar, quedó un instante aturdido y turbado en sus pensamientos. El rey tomó la palabra y dijo: «Beltsassar, no te turbe este sueño y su interpretación». Respondió Beltsassar: «¡ Oh mi señor, sea este sueño para tus enemigos y su interpretación para tus adversarios!

[[daniel-4-17]]
^17^ Ese árbol que has visto, que se hizo grande y corpulento, cuya altura llegaba hasta el cielo y que era visible en toda la tierra,

[[daniel-4-18]]
^18^ que tenía hermoso ramaje y abundante fruto, en el que había alimento para todos, bajo el cual se cobijaban las bestias del campo y en cuyas ramas anidaban los pájaros del cielo,

[[daniel-4-19]]
^19^ eres tú, oh rey, que te has hecho grande y poderoso, cuya grandeza ha crecido y ha llegado hasta el cielo, y cuyo dominio se extiende hasta los confines de la tierra.

[[daniel-4-20]]
^20^ «En cuanto a lo que ha visto el rey: un Vigilante, un santo que bajaba del cielo y decía: “Abatid el árbol, destruidlo, pero el tocón y sus raíces dejadlos en tierra, con ataduras de hierro y bronce, entre la hierba del campo, y sea bañado del rocío del cielo y comparta la suerte con las bestias del campo hasta que hayan pasado por él siete tiempos”,

[[daniel-4-21]]
^21^ ésta es su interpretación, oh rey, y el decreto del Altísimo que ha tocado a mi señor el rey:

[[daniel-4-22]]
^22^ «Serás arrojado de entre los hombres y con las bestias del campo morarás; hierba, como los bueyes, tendrás por comida, y serás bañado del rocío del cielo; siete tiempos pasarán por ti, hasta que reconozcas que el Altísimo domina sobre el imperio de los hombres y que se lo da a quien le place.

[[daniel-4-23]]
^23^ «Y la orden de dejar el tocón y las raíces del árbol, significa que tu reino se te conservará hasta que hayas reconocido que todo poder viene del Cielo.

[[daniel-4-24]]
^24^ Por eso, oh rey, acepta mi consejo: rompe tus pecados con obras de justicia y tus iniquidades con misericordia para con los pobres, para que tu ventura sea larga».

[[daniel-4-25]]
^25^ Todo esto le sobrevino al rey Nabucodonosor.

[[daniel-4-26]]
^26^ Doce meses después, paseándose por la terraza del palacio real de Babilonia,

[[daniel-4-27]]
^27^ iba diciendo el rey: «¿No es ésta la gran Babilonia que yo he edificado como mi residencia real, con el poder de mi fuerza y para la gloria de mi majestad?»

[[daniel-4-28]]
^28^ Aún estaban estas palabras en la boca del rey, cuando una voz cayó del cielo: «¡A ti se te habla, rey Nabucodonosor! La realeza se te ha ido.

[[daniel-4-29]]
^29^ De entre los hombres serás arrojado, con las bestias del campo morarás; hierba como los bueyes tendrás por comida, y siete tiempos pasarán por ti, hasta que reconozcas que el Altísimo domina sobre el reino de los hombres, y se lo da a quien le place».

[[daniel-4-30]]
^30^ Y al punto se cumplió la palabra en Nabucodonosor: fue arrojado de entre los hombres, se alimentó de hierba como los bueyes, su cuerpo fue bañado del rocío del cielo, hasta crecerle sus cabellos como plumas de águila y sus uñas como las de las aves.

[[daniel-4-31]]
^31^ «Al cabo del tiempo fijado, yo, Nabucodonosor, levanté los ojos al cielo, y la razón volvió a mí; entonces bendije al Altísimo, alabando y exaltando al que vive eternamente, cuyo imperio es un imperio eterno, y cuyo reino dura por todas las generaciones.

[[daniel-4-32]]
^32^ Los habitantes todos de la tierra ante él, como si no contaran, hace lo que quiere con el ejército del cielo y con los habitantes de la tierra. Nadie puede detener su mano o decirle: “¿Qué haces?”

[[daniel-4-33]]
^33^ «En aquel momento, la razón volvió a mí, y para gloria de mi realeza volvieron también a mí majestad y esplendor; mis consejeros y mis grandes me reclamaron, se me restableció en mi reino, y se me dio una grandeza todavía mayor.

[[daniel-4-34]]
^34^ Ahora, pues, yo, Nabucodonosor, alabo, exalto y glorifico al Rey del Cielo, porque sus obras todas son verdad, justicia todos sus caminos; él sabe humillar a los que caminan con orgullo».
[[daniel-5]]
== Capítulo 5

[[daniel-5-1]]
^1^ El rey Baltasar dio un gran festín en honor de sus mil dignatarios, y, en presencia de estos mil, bebió vino.

[[daniel-5-2]]
^2^ Bajo el efecto del vino, Baltasar mandó traer los vasos de oro y plata que su padre Nabucodonosor se había llevado del Templo de Jerusalén, para que bebieran en ellos el rey, sus dignatorios, sus mujeres y sus concubinas.

[[daniel-5-3]]
^3^ Se trajeron, pues, los vasos de oro y plata tomados de la Casa de Dios en Jerusalén, y en ellos bebieron el rey, sus dignatorios, sus mujeres y sus concubinas.

[[daniel-5-4]]
^4^ Bebieron vino y alabaron a sus dioses de oro y plata, de bronce y hierro, de madera y piedra.

[[daniel-5-5]]
^5^ De pronto aparecieron los dedos de una mano humana que se pusieron a escribir, detrás del candelabro, en la cal de la pared del palacio real, y el rey vio la palma de la mano que escribía.

[[daniel-5-6]]
^6^ Entonces el rey cambió de color, sus pensamientos le turbaron, las articulaciones de sus caderas se le relajaron y sus rodillas se pusieron a castañetear.

[[daniel-5-7]]
^7^ Y el rey mandó a buscar a gritos a los adivinos, caldeos y astrólogos. Tomó el rey la palabra y dijo a los sabios de Babilonia: «El que lea este escrito y me dé a conocer su interpretación, será vestido de púrpura, se le pondrá al cuello un collar de oro, y mandará como tercero en el reino».

[[daniel-5-8]]
^8^ Vinieron, pues, todos los sabios del rey; pero no pudieron leer el escrito ni declarar al rey su interpretación.

[[daniel-5-9]]
^9^ El rey Baltasar se turbó mucho y su semblante cambió de color; también sus dignatarios quedaron desconcertados.

[[daniel-5-10]]
^10^ En la sala del festín entró la reina, enterada por las palabras del rey y de sus dignatarios. Y dijo la reina: «¡Viva el rey eternamente! No te turben tus pensamientos ni tu semblante cambie de color.

[[daniel-5-11]]
^11^ Hay en tu reino un hombre en quien reside el espíritu de los dioses santos. Ya en tiempo de tu padre se halló en él luz, inteligencia y sabiduría semejante a la sabiduría de los dioses, y tu padre, el rey Nabucodonosor, le nombró jefe de los magos, adivinos, caldeos y astrólogos.

[[daniel-5-12]]
^12^ Por tanto, ya que en este Daniel, a quien el rey puso por sobrenombre Beltsassar, se encontró un espíritu extraordinario, ciencia, inteligencia y arte de interpretar sueños, de descifrar enigmas y de resolver dificultades, sea llamado Daniel y él dará a conocer la interpretación».

[[daniel-5-13]]
^13^ En seguida fue introducido Daniel a la presencia del rey, y el rey dijo a Daniel: «¿Eres tú Daniel, uno de los judíos deportados, que mi padre el rey trajo de Judá?

[[daniel-5-14]]
^14^ He oído decir que en ti reside el espíritu de los dioses y que hay en ti luz, inteligencia y sabiduría extraordinarias.

[[daniel-5-15]]
^15^ Han sido introducidos ahora en mi presencia los sabios y adivinos para que leyeran este escrito y me declararan su interpretación, pero han sido incapaces de descubrir su sentido.

[[daniel-5-16]]
^16^ He oído decir que tú puedes dar interpretaciones y resolver dificultades. Si, pues, logras leer este escrito y declararme su interpretación, serás vestido de púrpura, llevarás al cuello un collar de oro, y mandarás como tercero en el reino».

[[daniel-5-17]]
^17^ Daniel tomó la palabra y dijo delante del rey: «Quédate con tus regalos y da tus obsequios a otro, que yo leeré igualmente al rey este escrito y le daré a conocer su interpretación.

[[daniel-5-18]]
^18^ Oh rey, el Dios Altísimo dio a tu padre Nabucodonosor reino, grandeza, gloria y majestad.

[[daniel-5-19]]
^19^ Y por esta grandeza que le dio, todos los pueblos, naciones y lenguas temblaban de miedo en su presencia: mataba él a quien quería, dejaba vivir a quien quería, exaltaba a quien quería y a quien quería humillaba.

[[daniel-5-20]]
^20^ Pero habiéndose engreído su corazón y obstinado su espíritu hasta la arrogancia, fue depuesto de su trono real, y se le quitó su gloria.

[[daniel-5-21]]
^21^ Fue expulsado de entre los hombres y su corazón se hizo semejante al de las bestias; estuvo conviviendo con los onagros; se alimentó de hierba como los bueyes, y su cuerpo fue bañado del rocío del cielo, hasta que reconoció que el Dios Altísimo domina sobre el reino de los hombres y pone en él a quien le place.

[[daniel-5-22]]
^22^ Pero tú, Baltasar, hijo suyo, no has humillado tu corazón, a pesar de que sabías todo esto;

[[daniel-5-23]]
^23^ te has engreído contra el Señor del Cielo, se han traído a tu presencia los vasos de su Casa, y tú, tus dignatorios, tus mujeres y tus concubinas, habéis bebido vino en ellos. Habéis celebrado a los dioses de plata y oro, de bronce y hierro, de madera y piedra, que no ven ni oyen ni entienden, pero no has glorificado al Dios que tiene en sus manos tu propio aliento y de quien dependen todos tus caminos.

[[daniel-5-24]]
^24^ Por eso ha enviado él esa mano que trazó este escrito.

[[daniel-5-25]]
^25^ La escritura trazada es: Mené, Mené, Teqel y Parsín.

[[daniel-5-26]]
^26^ Y ésta es la interpretación de las palabras: Mené: Dios ha medido tu reino y le ha puesto fin;

[[daniel-5-27]]
^27^ Tequel: has sido pesado en la balanza y encontrado falto de peso;

[[daniel-5-28]]
^28^ Parsín: tu reino ha sido dividido y entregado a los medos y los persas».

[[daniel-5-29]]
^29^ Entonces Baltasar mandó revestir de púrpura a Daniel, ponerle un collar de oro al cuello y proclamar que mandaba como tercero en el reino.

[[daniel-5-30]]
^30^ Aquella noche fue asesinado Baltasar, el rey de los caldeos.
[[daniel-6]]
== Capítulo 6

[[daniel-6-1]]
^1^ Y recibió el reino Darío el Medo, que contaba sesenta y dos años.

[[daniel-6-2]]
^2^ Plugo a Darío establecer en su reino ciento veinte sátrapas que estuvieran por todo el reino,

[[daniel-6-3]]
^3^ bajo el mando de tres ministros - Daniel era uno de ellos -, a los que los sátrapas deberían rendir cuentas, con el fin de impedir que el rey recibiera daño alguno.

[[daniel-6-4]]
^4^ Este mismo Daniel se distinguía entre los ministros y los sátrapas, porque había en él un espíritu extraordinario, y el rey se proponía ponerle al frente del reino entero.

[[daniel-6-5]]
^5^ Por ello los ministros y los sátrapas se pusieron a buscar un motivo de acusación contra Daniel en algún asunto de Estado; pero no pudieron encontrar ningún motivo de acusación ni falta alguna, porque él era fiel y no se le podía reprochar de negligencia ni falta.

[[daniel-6-6]]
^6^ Entonces se dijeron aquellos hombres: «No encontraremos ningún motivo de acusación contra este Daniel si no es en materia de la ley de su Dios».

[[daniel-6-7]]
^7^ Los ministros y sátrapas acudieron, pues, atropelladamente ante el rey y le hablaron así: «¡Viva eternamente el rey Darío!

[[daniel-6-8]]
^8^ Todos los ministros del reino, prefectos, sátrapas, consejeros y gobernadores, aconsejan unánimemente que se promulgue un edicto real para poner en vigor la prohibición siguiente: Todo aquel que en el término de treinta días dirija una oración a quienquiera que sea, dios u hombre, fuera de ti, oh rey, será arrojado al foso de los leones.

[[daniel-6-9]]
^9^ Ahora pues, oh rey, da fuerza de ley a esta prohibición firmando el edicto, de suerte que no se cambie nada, con arreglo a la ley de los medos y persas, que es irrevocable».

[[daniel-6-10]]
^10^ Ante esto, el rey Darío firmó el edicto de prohibición.

[[daniel-6-11]]
^11^ Al saber que había sido firmado el edicto, Daniel entró en su casa. Las ventanas de su cuarto superior estaban orientadas hacia Jerusalén y tres veces al día se ponía él de rodillas, para orar y dar gracias a su Dios; así lo había hecho siempre.

[[daniel-6-12]]
^12^ Aquellos hombres vinieron atropelladamente y sorprendieron a Daniel invocando y suplicando a su Dios.

[[daniel-6-13]]
^13^ Entonces se presentaron al rey y le dijeron acerca de la prohibición real: «¿No has firmado tú una prohibición según la cual todo el que dirigiera, en el término de treinta días, una oración a quienquiera que fuese, dios u hombre, fuera de ti, oh rey, sería arrojado al foso de los leones?» Respondió el rey: «La cosa está decidida, según la ley de los medos y los persas, que es irrevocable».

[[daniel-6-14]]
^14^ Entonces ellos dijeron en presencia del rey: «Daniel, ese deportado de Judá, no hace caso de ti, oh rey, ni de la prohibición que tú has firmado: tres veces al día hace su oración».

[[daniel-6-15]]
^15^ Al oír estas palabras, el rey se afligió mucho y se propuso salvar a Daniel; hasta la puesta del sol estuvo buscando el modo de librarle.

[[daniel-6-16]]
^16^ Pero aquellos hombres volvieron atropelladamente ante el rey y le dijeron: «Ya sabes, oh rey, que según la ley de los medos y los persas ninguna prohibición o edicto dado por el rey puede ser modificado».

[[daniel-6-17]]
^17^ Entonces el rey dio orden de traer a Daniel y de arrojarle al foso de los leones. El rey dijo a Daniel: «Tu Dios, a quien sirves con perseverancia, te librará».

[[daniel-6-18]]
^18^ Se trajo una piedra que fue colocada a la entrada del foso, y el rey la selló con su anillo y con el anillo de sus dignatarios, para que no se pudiese cambiar la suerte de Daniel.

[[daniel-6-19]]
^19^ Después el rey volvió a su palacio y pasó la noche en ayuno; no dejó que le trajeran concubinas y el sueño huyó de él.

[[daniel-6-20]]
^20^ Al amanecer, al rayar el alba, el rey se levantó y se dirigió a toda prisa al foso de los leones.

[[daniel-6-21]]
^21^ Acercándose al foso, gritó a Daniel con voz angustiada: «Daniel, servidor del Dios vivo, tu Dios, a quien sirves con perseverencia, ¿ha podido librarte de los leones?»

[[daniel-6-22]]
^22^ Entonces Daniel habló con el rey: «¡Viva el rey eternamente!

[[daniel-6-23]]
^23^ Mi Dios ha enviado a su ángel, que ha cerrado la boca de los leones y no me han hecho ningún mal, porque he sido hallado inocente ante él. Y tampoco ante ti, oh rey, he cometido falta alguna».

[[daniel-6-24]]
^24^ El rey entonces se alegró mucho y mandó sacar a Daniel del foso. Sacaron a Daniel del foso y no se le encontró herida alguna, porque había confiado en su Dios.

[[daniel-6-25]]
^25^ Y el rey mandó traer a aquellos hombres que habían acusado a Daniel y echarlos al foso de los leones, a ellos, y a sus hijos y mujeres. Y no habían llegado aún al fondo del foso cuando ya los leones se habían lanzado sobre ellos y les habían triturado todos los huesos.

[[daniel-6-26]]
^26^ Entonces, el rey Darío escribió a todos los pueblos, naciones y lenguas que habitaban en toda la tierra: «¡Sea grande vuestra paz!

[[daniel-6-27]]
^27^ Por mí se decreta que en todos los dominios de mi reino se tema y se tiemble ante el Dios de Daniel, porque él es el Dios vivo, que subsiste por siempre, - su reino no será destruido y su imperio durará hasta el fin -

[[daniel-6-28]]
^28^ el que salva y libera, obra señales y milagros en los cielos y en la tierra; el que ha salvado a Daniel del poder de los leones».

[[daniel-6-29]]
^29^ Y este mismo Daniel floreció en el reinado de Darío y en el reinado de Ciro el Persa.
[[daniel-7]]
== Capítulo 7

[[daniel-7-1]]
^1^ El año primero de Baltasar, rey de Babilonia, Daniel tuvo un sueño y visiones de su cabeza, mientras se hallaba en su lecho. En seguida puso el sueño por escrito. Comienzo del relato:

[[daniel-7-2]]
^2^ Daniel tomó la palabra y dijo: Contemplaba yo en mi visión durante la noche lo siguiente: los cuatro vientos del cielo agitaron el mar grande,

[[daniel-7-3]]
^3^ y cuatro bestias enormes, diferentes todas entre sí, salieron del mar.

[[daniel-7-4]]
^4^ La primera era como un león con alas de águila. Mientras yo la miraba, le fueron arrancadas las alas, fue levantada de la tierra, se incorporó sobre sus patas como un hombre, y se le dio un corazón de hombre.

[[daniel-7-5]]
^5^ A continuación, otra segunda bestia, semejante a un oso, levantada de un costado, con tres costillas en las fauces, entre los dientes. Y se le decía: «Levántate, devora mucha carne».

[[daniel-7-6]]
^6^ Después, yo seguía mirando y vi otra bestia como un leopardo con cuatro alas de ave en su dorso; la bestia tenía cuatro cabezas, y se le dio el dominio.

[[daniel-7-7]]
^7^ Después seguí mirando, en mis visiones nocturnas, y vi una cuarta bestia, terrible, espantosa, extraordinariamente fuerte; tenía enormes dientes de hierro; comía, triburaba, y lo sobrante lo pisoteaba con sus patas. Era diferente de las bestias anteriores y tenía diez cuernos.

[[daniel-7-8]]
^8^ Estaba yo observando los cuernos, cuando en esto despuntó entre ellos otro cuerno, pequeño, y tres de los primeros cuernos fueron arrancados delante de él. Tenía este cuerno ojos como los de un hombre, y una boca que decía grandes cosas.

[[daniel-7-9]]
^9^ Mientras yo contemplaba: Se aderezaron unos tronos y un Anciano se sentó. Su vestidura, blanca como la nieve; los cabellos de su cabeza, puros como la lana. Su trono, llamas de fuego, con ruedas de fuego ardiente.

[[daniel-7-10]]
^10^ Un río de fuego corría y manaba delante de él. Miles de millares le servían, miriadas de miriadas estaban en pie delante de él. El tribunal se sentó, y se abrieron los libros.

[[daniel-7-11]]
^11^ Miré entonces, atraído por el ruido de las grandes cosas que decía el cuerno, y estuve mirando hasta que la bestia fue muerta y su cuerpo destrozado y arrojado a la llama de fuego.

[[daniel-7-12]]
^12^ A las otras bestias se les quitó el dominio, si bien se les concedió una prolongación de vida durante un tiempo y hora determinados.

[[daniel-7-13]]
^13^ Yo seguía contemplando en las visiones de la noche: Y he aquí que en las nubes del cielo venía como un Hijo de hombre. Se dirigió hacia el Anciano y fue llevado a su presencia.

[[daniel-7-14]]
^14^ A él se le dio imperio, honor y reino, y todos los pueblos, naciones y lenguas le sirvieron. Su imperio es un imperio eterno, que nunca pasará, y su reino no será destruido jamás.

[[daniel-7-15]]
^15^ Yo, Daniel, quedé muy impresionado en mi espíritu por estas cosas, y las visiones de mi cabeza me dejaron turbado.

[[daniel-7-16]]
^16^ Me acerqué a uno de los que estaban allí de pie y le pedí que me dijera la verdad acerca de todo esto. El me respondió y me indicó la interpretación de estas cosas:

[[daniel-7-17]]
^17^ «Estas cuatro grandes bestias son cuatro reyes que surgirán de la tierra.

[[daniel-7-18]]
^18^ Los que han de recibir el reino son los santos del Altísimo, que poseerán el reino eternamente, por los siglos de los siglos».

[[daniel-7-19]]
^19^ Después quise saber la verdad sobre la cuarta bestia, que era diferente de las otras, extraordinariamente terrible, con dientes de hierro y uñas de bronce, que comía, trituraba y pisoteaba con sus patas lo sobrante;

[[daniel-7-20]]
^20^ y acerca de los diez cuernos que había en su cabeza, y del otro cuerno que había despuntado, ante el cual cayeron los tres primeros; y de este cuerno que tenía ojos y una boca que decía grandes cosas, y cuyo aspecto era mayor que el de los otros.

[[daniel-7-21]]
^21^ Yo contemplaba cómo este cuerno hacía la guerra a los santos y los iba subyugando,

[[daniel-7-22]]
^22^ hasta que vino el Anciano a hacer justicia a los santos del Altísimo, y llegó el tiempo en que los santos poseyeron el reino.

[[daniel-7-23]]
^23^ El habló así: «La cuarta bestia será un cuarto reino que habrá en la tierra, diferente de todos los reinos. Devorará toda la tierra, la aplastará y la pulverizará.

[[daniel-7-24]]
^24^ Y los diez cuernos: de este reino saldrán diez reyes, y otro saldrá después de ellos; será diferente de los primeros y derribará a tres reyes;

[[daniel-7-25]]
^25^ proferirá palabras contra el Altísimo y pondrá a prueba a los santos del Altísimo. Tratará de cambiar los tiempos y la ley, y los santos serán entregados en sus manos por un tiempo y tiempos y medio tiempo.

[[daniel-7-26]]
^26^ Pero el tribunal se sentará, y el dominio le será quitado, para ser destruido y aniquilado definitivamente.

[[daniel-7-27]]
^27^ Y el reino y el imperio y la grandeza de los reinos bajo los cielos todos serán dados al pueblo de los santos del Altísimo. Reino eterno es su reino, y todos los imperios le servirán y le obedecerán».

[[daniel-7-28]]
^28^ Hasta aquí la relación. Yo, Daniel, quedé muy turbado en mis pensamientos, se me demudó el color del rostro y guardé estas cosas en mi corazón.
[[daniel-8]]
== Capítulo 8

[[daniel-8-1]]
^1^ El año tercero del reinado del rey Baltasar, yo, Daniel, tuve una visión después de la tenida anteriormente.

[[daniel-8-2]]
^2^ Miré durante la visión y me veía en Susa, la plaza fuerte que está en la provincia de Elam; en la visión miré, y me encontraba en la puerta del Ulay.

[[daniel-8-3]]
^3^ Levanté los ojos para ver, y vi un carnero que estaba delante de la puerta. Tenía dos cuernos; los dos cuernos eran altos, pero uno más que otro y el más alto había despuntado el último.

[[daniel-8-4]]
^4^ Vi que el carnero acometía contra el oeste, el norte y el sur. Ninguna bestia podía resistirle, nada podía escapar a su poder. Hacía lo que le parecía y así se hizo grande.

[[daniel-8-5]]
^5^ Estaba yo cavilando, y he aquí que un macho cabrío vino de occidente, recorriendo la tierra entera sin tocar el suelo; este macho cabrío tenía un cuerno «magnífico» entre los ojos.

[[daniel-8-6]]
^6^ Vino donde el carnero de dos cuernos que yo había visto en pie delante de la puerta y corrió hacia él con todo el ardor de su fuerza.

[[daniel-8-7]]
^7^ Vi cómo alcanzaba al carnero, enfurecido contra él; embistió al carnero, y le rompió los dos cuernos, sin que el carnero tuviera fuerzas para resistirle; lo echó por tierra y lo pisoteó; no había nadie que librara al carnero de su mano.

[[daniel-8-8]]
^8^ El macho cabrío se hizo muy grande, pero cuando estaba en la plenitud de su poder, el gran cuerno se rompió y en su lugar despuntaron cuatro «magníficos» en la dirección de los cuatro vientos del cielo.

[[daniel-8-9]]
^9^ De uno de ellos salió un cuerno, pequeño, que creció mucho en dirección del sur, del oriente y de la Tierra del Esplendor.

[[daniel-8-10]]
^10^ Creció hasta el ejército del cielo, precipitó en tierra parte del ejército y de las estrellas, y las pisoteó con sus pies.

[[daniel-8-11]]
^11^ Llegó incluso hasta el Jefe del ejército, abolió el sacrificio perpetuo y sacudió el cimiento de su santuario

[[daniel-8-12]]
^12^ y al ejército; en el lugar del sacrificio puso la iniquidad y tiró por tierra la verdad; así obró y le acompañó el éxito.

[[daniel-8-13]]
^13^ Oí entonces a un santo que hablaba, y a otro santo que decía al que hablaba: «¿Hasta cuándo la visión: el sacrificio perpetuo, la iniquidad desoladora, el santuario y el ejército pisoteados?»

[[daniel-8-14]]
^14^ Le respondió: «Hasta dos mil trescientas tardes y mañanas: después será reivindicado el santuario».

[[daniel-8-15]]
^15^ Mientras yo, Daniel, contemplaba esta visión y trataba de comprenderla, vi de pronto delante de mí como una apariencia de hombre,

[[daniel-8-16]]
^16^ y oí una voz de hombre, sobre el Ulay, que gritaba: «Gabriel, explícale a éste la visión».

[[daniel-8-17]]
^17^ El se acercó al lugar donde yo estaba y, cuando llegó, me aterroricé y caí de bruces. Me dijo: «Hijo de hombre, entiende: la visión se refiere al tiempo del Fin».

[[daniel-8-18]]
^18^ Mientras él me hablaba, yo me desvanecí, rostro en tierra. El me tocó y me hizo incorporarme donde estaba.

[[daniel-8-19]]
^19^ Luego dijo: «Mira, voy a manifestarte lo que ocurrirá al fin de la Ira, porque el Fin está fijado.

[[daniel-8-20]]
^20^ El carnero que has visto, sus dos cuernos, son los reyes de los medos y los persas.

[[daniel-8-21]]
^21^ El macho cabrío velludo es el rey de Yaván; el cuerno grande entre sus ojos, es el primer rey.

[[daniel-8-22]]
^22^ El cuerno roto y los cuatro cuernos que despuntaron en su lugar, son cuatro reinos salidos de su nación, pero que no tendrán su fuerza.

[[daniel-8-23]]
^23^ «Y al término de su reino, cuando lleguen al colmo los pecados, surgirá un rey, insolente y hábil en engaños.

[[daniel-8-24]]
^24^ Se hará poderosa su fuerza - mas no por su fuerza misma - tramará cosas inauditas, prosperará en sus empresas, destruirá a poderosos y al pueblo de los santos.

[[daniel-8-25]]
^25^ Y, por su habilidad, triunfará el engaño entre sus manos. Se exaltará en su corazón, y por sorpresa destruirá a muchos. Se alzará contra el Príncipe de los Príncipes, pero - sin que mano alguna intervenga - será quebrantado.

[[daniel-8-26]]
^26^ Es verdad la visión de las tardes y mañanas que se ha dicho, mas tú guarda en secreto la visión, pues habrá aún para muchos días».

[[daniel-8-27]]
^27^ Yo, Daniel, desfallecí y estuve enfermo unos cuantos días. Luego me levanté para ocuparme de los asuntos del rey. Seguía perplejo por la visión, que no se podía comprender.
[[daniel-9]]
== Capítulo 9

[[daniel-9-1]]
^1^ El año primero de Darío, hijo de Asuero, de la raza de los medos, que subió al trono del reino de Caldea,

[[daniel-9-2]]
^2^ el año primero de su reinado, yo, Daniel, me puse a investigar en las Escrituras sobre el número de años que, según la palabra de Yahveh dirigida al profeta Jeremías, debían pasar sobre las ruinas de Jerusalén, a saber setenta años.

[[daniel-9-3]]
^3^ Volví mi rostro hacia el Señor Dios para implorarle con oraciones y súplicas, en ayuno, sayal y ceniza.

[[daniel-9-4]]
^4^ Derramé mi oración a Yahveh mi Dios, y le hice esta confesión: «¡Ah, señor, Dios grande y temible, que guardas la Alianza y el amor a los que te aman y observan tus mandamientos.

[[daniel-9-5]]
^5^ Nosotros hemos pecado, hemos cometido iniquidad, hemos sido malos, no hemos rebelado y nos hemos apartado de tus mandamientos y de tus normas.

[[daniel-9-6]]
^6^ No hemos escuchado a tus siervos los profetas que en tu nombre hablaban a nuestros reyes, a nuestros príncipes, a nuestros padres, a todo el pueblo de la tierra.

[[daniel-9-7]]
^7^ A ti, Señor, la justicia, a nosotros la vergüenza en el rostro, como sucede en este día, a nosotros, a los hombres de Judá, a los habitantes de Jerusalén y a Israel entero, próximos y lejanos, en todos los países donde tú los dispersaste a causa de las infidelidades que cometieron contra ti.

[[daniel-9-8]]
^8^ Yahveh, a nosotros la vergüenza, a nuestros reyes, a nuestros príncipes, a nuestros padres, porque hemos pecado contra ti.

[[daniel-9-9]]
^9^ Al Señor Dios nuestro, la piedad y el perdón, porque nos hemos rebelado contra él,

[[daniel-9-10]]
^10^ y no hemos escuchado la voz de Yahveh nuestro Dios para seguir sus leyes, que él nos había dado por sus siervos los profetas.

[[daniel-9-11]]
^11^ Todo Israel ha transgredido tu ley, ha desertado sin querer escuchar tu voz, y sobre nosotros han caído la maldición y la imprecación escritas en la ley de Moisés, siervo de Dios, porque hemos pecado contra él.

[[daniel-9-12]]
^12^ El ha cumplido las palabras que había pronunciado contra nosotros y contra los príncipes que nos gobernaban: que haría venir sobre nosotros una calamidad tan grande como no habría jamás bajo el cielo otra mayor que la que alcanzara a Jerusalén.

[[daniel-9-13]]
^13^ Según está escrito en la ley de Moisés, toda esta calamidad nos ha sobrevenido, pero nosotros no hemos aplacado el rostro de Yahveh nuestro Dios, convirtiéndonos de nuestras iniquidades y aprendiendo a conocer tu verdad.

[[daniel-9-14]]
^14^ Yahveh ha estado atento a esta calamidad, la ha descargado sobre nosotros. Porque es justo Yahveh nuestro Dios en todas las obras que ha hecho, pero nosotros no hemos escuchado su voz.

[[daniel-9-15]]
^15^ Y ahora, Señor Dios nuestro, que con mano fuerte sacaste a tu pueblo del país de Egipto y te granjeaste con ello un nombre que dura hasta el presente, nosotros hemos pecado, hemos sido malos.

[[daniel-9-16]]
^16^ Señor, por todas tus justicias, retira tu cólera y tu furor de Jerusalén, tu ciudad, monte santo tuyo; pues, a causa de nuestros pecados y de las iniquidades de nuestros padres, Jerusalén y tu pueblo son el escarnio de todos los que nos circundan.

[[daniel-9-17]]
^17^ Y ahora, oh Dios nuestro, escucha la oración de tu siervo y sus súplicas. Ilumine tu rostro tu santuario desolado, ¡por ti mismo, Señor!

[[daniel-9-18]]
^18^ Inclina, Dios mío, tu oído y escucha. Abre tus ojos y mira nuestras ruinas y la ciudad sobre la cual se invoca tu nombre. No, no nos apoyamos en nuestras obras justas para derramar ante ti nuestras súplicas, sino en tus grandes misericordias.

[[daniel-9-19]]
^19^ ¡Señor, escucha! ¡Señor, perdona! ¡Señor, atiende y obra! ¡No tardes más, por ti mismo, Dios mío, pues tu nombre se invoca sobre tu ciudad y sobre tu pueblo».

[[daniel-9-20]]
^20^ Todavía estaba yo hablando, haciendo mi oración, confesando mis pecados y los pecados de mi pueblo Israel, y derramando mi súplica ante Yahveh mi Dios, por el santo monte de mi Dios;

[[daniel-9-21]]
^21^ aún estaba hablando en oración, cuando Gabriel, el personaje que yo había visto en visión al principio, vino volando donde mí a la hora de la oblación de la tarde.

[[daniel-9-22]]
^22^ Vino y me habló. Dijo: «Daniel, he salido ahora para ilustrar tu inteligencia.

[[daniel-9-23]]
^23^ Desde el comienzo de tu súplica, una palabra se emitió y yo he venido a revelártela, porque tú eres el hombre de las predilecciones. Comprende la palabra, entiende la visión:

[[daniel-9-24]]
^24^ Setenta semanas están fijadas sobre tu pueblo y tu ciudad santa para poner fin a la rebeldía, para sellar los pecados, para expiar la culpa, para instaurar justicia eterna, para sellar visión y profecía, para ungir el santo de los santos.

[[daniel-9-25]]
^25^ «Entiende y comprende: Desde el instante en que salió la orden de volver a construir Jerusalén, hasta un Príncipe Mesías, siete semanas y sesenta y dos semanas, plaza y foso serán reconstruidos, pero en la angustia de los tiempos.

[[daniel-9-26]]
^26^ Y después de las sesenta y dos semanas un mesías será suprimido, y no habrá para él... y destruirá la ciudad y el santuario el pueblo de un príncipe que vendrá. Su fin será en un cataclismo y, hasta el final, la guerra y los desastres decretados.

[[daniel-9-27]]
^27^ El concertará con muchos una firme alianza una semana; y en media semana hará cesar el sacrificio y la oblación, y en el ala del Templo estará la abominación de la desolación, hasta que la ruina decretada se derrame sobre el desolador».
[[daniel-10]]
== Capítulo 10

[[daniel-10-1]]
^1^ El año tercero de Ciro, rey de Persia, una palabra fue revelada a Daniel, por sobrenombre Beltsassar. Palabra verdadera: gran lucha. El comprendió la palabra; le fue dada en visión su inteligencia.

[[daniel-10-2]]
^2^ En aquel tiempo, yo, Daniel, hice penitencia durante tres semanas:

[[daniel-10-3]]
^3^ no comí alimento sabroso; ni carne ni vino entraron en mi boca, ni me ungí, hasta el término de estas tres semanas.

[[daniel-10-4]]
^4^ El día veinticuatro del primer mes, estando a orillas del río grande, el Tigris,

[[daniel-10-5]]
^5^ levanté los ojos para ver. Vi esto: Un hombre vestido de lino, ceñidos los lomos de oro puro:

[[daniel-10-6]]
^6^ su cuerpo era como de crisólito, su rostro, como el aspecto del relámpago, sus ojos como antorchas de fuego, sus brazos y sus piernas como el fulgor del bronce bruñido, y el son de sus palabras como el ruido de una multitud.

[[daniel-10-7]]
^7^ Sólo yo, Daniel, contemplé esta visión: los hombres que estaban conmigo no veían la visión, pero un gran temblor les invadió y huyeron a esconderse.

[[daniel-10-8]]
^8^ Quedé yo solo contemplando esta gran visión; estaba sin fuerzas; se demudó mi rostro, desfigurado, y quedé totalmente sin fuerzas.

[[daniel-10-9]]
^9^ Oí el son de sus palabras y, al oírlo, caí desvanecido, rostro en tierra.

[[daniel-10-10]]
^10^ En esto una mano me tocó, haciendo castañear mis rodillas y las palmas de mis manos.

[[daniel-10-11]]
^11^ Y me dijo: «Daniel, hombre de las predilecciones, comprende las palabras que voy a decirte, e incorpórate, porque yo he sido enviado ahora donde ti». Al decirme estas palabras me incorporé temblando.

[[daniel-10-12]]
^12^ Luego me dijo: «No temas, Daniel, porque desde el primer día en que tú intentaste de corazón comprender y te humillaste delante de tu Dios, fueron oídas tus palabras, y precisamente debido a tus palabras he venido yo.

[[daniel-10-13]]
^13^ El Príncipe del reino de Persia me ha hecho resistencia durante veintiún días, pero Miguel, uno de los Primeros Príncipes, ha venido en mi ayuda. Le he dejado allí junto a los reyes de Persia

[[daniel-10-14]]
^14^ y he venido a manifestarte lo que le ocurirá a tu pueblo al fin de los días. Porque hay todavía una visión para esos días».

[[daniel-10-15]]
^15^ Al decirme estas palabras, di con mi rostro en tierra y quedé en silencio;

[[daniel-10-16]]
^16^ y he aquí que una figura de hijo de hombre me tocó los labios. Abrí la boca para hablar y dije a aquel que estaba delante de mí: «Señor mío, ante esta visión la angustia me invade y ya no tengo fuerzas.

[[daniel-10-17]]
^17^ Y ¿cómo este siervo de mi Señor podría hablar con mi Señor, cuando ahora las fuerzas me faltan y ni aliento me queda?»

[[daniel-10-18]]
^18^ El que tenía aspecto de hombre me tocó de nuevo y me reanimó.

[[daniel-10-19]]
^19^ Me dijo: «No temas, hombre de las predilecciones; la paz sea contigo, cobra fuerza y ánimo». Y, mientras me hablaba, me sentí reanimado y dije: «Hable mi Señor, porque me has confortado».

[[daniel-10-20]]
^20^ Me dijo entonces: «¿Sabes por qué he venido donde ti? Y ahora volveré a luchar con el Príncipe de Persia: cuando haya terminado, verás que viene el Príncipe de Yaván.

[[daniel-10-21]]
^21^ Pero voy a revelarte lo que está consignado en el Libro de la Verdad. Nadie me presta ayuda para esto, excepto Miguel, vuestro Príncipe,
[[daniel-11]]
== Capítulo 11

[[daniel-11-1]]
^1^ mi apoyo para darme ayuda y sostenerme.

[[daniel-11-2]]
^2^ Pero ahora voy a revelarte la verdad. «Mira: En Persia habrá todavía tres reyes; el cuarto tendrá más riquezas que todos ellos, y cuando por su riqueza se haya hecho poderoso provocará a todos los reinos de Yaván.

[[daniel-11-3]]
^3^ Surgirá entonces un rey valeroso que dominará en un gran imperio y actuará a placer.

[[daniel-11-4]]
^4^ En trance de engrandecerse, su reino será quebrantado y repartido a los cuatros vientos del cielo, pero no entre su descendencia ni con un dominio como el que él había ejercido, porque su reino será extirpado y entregado a otros distintos de aquélla.

[[daniel-11-5]]
^5^ «El rey del Mediodía se hará fuerte; uno de sus príncipes se hará más fuerte que él y tendrá un imperio mayor que el suyo.

[[daniel-11-6]]
^6^ Algunos años después concertarán una alianza, y la hija del rey del Mediodía vendrá donde el rey del Norte para realizar el convenio. Pero no resistirá la fuerza de su brazo, ni subsistirá su descendencia: será entregada, ella y las personas de su séquito, así como su hijo y el que era su apoyo. En aquel tiempo,

[[daniel-11-7]]
^7^ se alzará en su lugar un retoño de sus raíces, que vendrá contra el ejército, entrará en la fortaleza del rey del Norte, y los tratará como vencedor.

[[daniel-11-8]]
^8^ Sus mismos dioses, sus estatuas y sus objetos preciosos de plata y oro serán el botín que se llevará a Egipto, y durante algunos años se mantendrá a distancia del rey del Norte.

[[daniel-11-9]]
^9^ Este entrará en el reino del rey del Mediodía y luego regresará a su país.

[[daniel-11-10]]
^10^ Sus hijos se prepararán para la guerra y reunirán una gran multitud de tropas, y él vendrá, irrumpirá como un río, pasará y se levantará de nuevo en guerra hasta su fortaleza.

[[daniel-11-11]]
^11^ Entonces el rey del Mediodía, montando en cólera, saldrá a combatir contra el rey del Norte, que movilizará una gran multitud; pero esta multitud caerá en sus manos.

[[daniel-11-12]]
^12^ La multitud quedará aniquilada; su corazón se exaltará entonces, aplastará a miriadas de hombres, pero no durará su fuerza.

[[daniel-11-13]]
^13^ El rey del Norte volverá a la carga después de movilizar una multitud más numerosa que la primera, y al cabo de algunos años irrumpirá con un gran ejército y abundante aparato.

[[daniel-11-14]]
^14^ Por entonces se levantarán muchos contra el rey del Mediodía y los violentos de entre los de tu pueblo se alzarán con ánimo de cumplir la visión, pero fracasarán.

[[daniel-11-15]]
^15^ Vendrá el rey del Norte, levantará trincheras y tomará una ciudad fortificada. Los brazos del rey del Mediodía no resistirán; ni siquiera lo mejor del pueblo tendrá fuerzas para resistir.

[[daniel-11-16]]
^16^ Aquel que avanza contra él le tratará a su capricho, sin que haya quien pueda resistirle: se establecerá en la Tierra del Esplendor, llevando en sus manos la destrucción.

[[daniel-11-17]]
^17^ Concebirá el proyecto de subyugar su reino entero; luego hará un pacto con él dándole una hija de las mujeres con el fin de destruirle, pero esto no se logrará ni resultará así.

[[daniel-11-18]]
^18^ Entonces se volverá hacia las islas y tomará un buen número de ellas; pero un magistrado pondrá fin a su ultraje sin que él pueda devolverle el ultraje.

[[daniel-11-19]]
^19^ «Luego se volverá hacia los baluartes de su país, pero tropezará, caerá y no se le encontrará más.

[[daniel-11-20]]
^20^ En su lugar surgiró otro, que enviará un exactor contra el esplendor real: en pocos días será destruido, mas no en público ni en guerra.

[[daniel-11-21]]
^21^ «En su lugar se levantará un miserable, a quien no se le darán los honores reales. Se insinuará astutamente y se apoderará del reino por intrigas.

[[daniel-11-22]]
^22^ Las fuerzas invasoras se hundirán ante él y serán destruidas, así como también el Príncipe de una alianza.

[[daniel-11-23]]
^23^ Por medio de sus cómplices obrará con engaño y, aunque con poca gente, se irá haciendo fuerte.

[[daniel-11-24]]
^24^ Invadirá a placer los lugares ricos de la provincia y hará lo que no habían hecho ni sus padres ni los padres de sus padres: distribuirá entre ellos botín, despojos y riquezas, y tramará maquinaciones contra las fortalezas, aunque sólo por un tiempo.

[[daniel-11-25]]
^25^ «Incitará su fuerza y su corazón contra el rey del Mediodía con un gran ejército. El rey del Mediodía saldrá a la guerra con un ejército muy grande y muy poderoso, pero no podrá resistir, pues se tramarán contra él maquinaciones.

[[daniel-11-26]]
^26^ Y los mismos que compartían sus manjares le destruirán; su ejército quedará hundido y caerán muchos muertos.

[[daniel-11-27]]
^27^ «En cuanto a los dos reyes, su corazón lleno de maldad, incluso sentados a la misma mesa, sólo se dirán mentiras; pero no lograrán nada, porque el tiempo fijado está aún por venir.

[[daniel-11-28]]
^28^ El volverá a su país con grandes riquezas, su corazón contra la Alianza santa; actuará y luego regresará a su país.

[[daniel-11-29]]
^29^ Llegado el momento, volverá de nuevo hacia el Mediodía, pero esta vez no resultará como la primera.

[[daniel-11-30]]
^30^ Vendrán contra él las naves de los Kittim, y se desanimará. Volverá atrás y se encorajinará furiosamente contra la Alianza santa, y una vez más tendrá en consideración a los que abandonen la Alianza santa.

[[daniel-11-31]]
^31^ «De su parte surgirán fuerzas armadas, profanarán el santuario - ciudadela, abolirán el sacrificio perpetuo y pondrán allí la abominación de la desolación.

[[daniel-11-32]]
^32^ A los violadores de la Alianza los corromperá con halagos, pero el pueblo de los que conocen a su Dios se mantendrá firme y actuará.

[[daniel-11-33]]
^33^ Los doctos del pueblo instruirán a la multitud; mas sucumbirán bajo la espada y la llama, la cautividad y la expoliación, durante algún tiempo.

[[daniel-11-34]]
^34^ Cuando sucumban, recibirán poca ayuda; y muchos se unirán a ellos traidoramente.

[[daniel-11-35]]
^35^ Entre los doctos sucumbirán algunos, para que entre ellos haya quienes sean purgados, lavados y blanqueados, hasta el tiempo del Fin, porque el tiempo fijado está aún por venir.

[[daniel-11-36]]
^36^ «El rey actuará a placer; se engreirá y se exaltará por encima de todos los dioses, y contra el Dios de los dioses proferirá cosas inauditas; prosperará hasta que se haya colmado la Ira, - porque lo que está decidido se cumplirá.

[[daniel-11-37]]
^37^ No hará caso de los dioses de sus padres, no se cuidará del favorito de las mujeres ni de ningún otro dios; sólo a sí mismo se exaltará por encima de todos.

[[daniel-11-38]]
^38^ En su lugar venerará al dios de las fortalezas; venerará con oro y plata, piedras preciosas y joyas, a un dios a quien sus padres no conocieron.

[[daniel-11-39]]
^39^ Pondrá como defensores de las fortalezas al pueblo de un dios extranjero; a los que le reconozcan, les colmará de honores dándoles dominio sobre muchos y repartiéndoles la tierra como recompensa.

[[daniel-11-40]]
^40^ «Al tiempo del Fin, el rey del Mediodía se enfrentará a él; el rey del Norte irrumpirá contra aquél con carros, jinetes y numerosas naves. Entrará en sus tierras, las invadirá y atravesará.

[[daniel-11-41]]
^41^ Vendrá a la Tierra del Esplendor, donde caerán muchos, pero de sus manos escaparán los siguientes: Edom, Moab y los restos de los ammonitas.

[[daniel-11-42]]
^42^ «Extenderá su mano sobre los países: ni el país de Egipto escapará.

[[daniel-11-43]]
^43^ Se apoderará de los tesoros de oro y plata y de todos los objetos preciosos de Egipto. Libios y kusitas le seguirán.

[[daniel-11-44]]
^44^ Pero noticias venidas del Oriente y del Norte le turbarán; saldrá entonces con gran furor, con ánimo de destruir y exterminar a muchos.

[[daniel-11-45]]
^45^ Plantará sus tiendas reales entre el mar y el santo monte de la Tierra del Esplendor. Entonces llegará a su fin y nadie vendrá en su ayuda.
[[daniel-12]]
== Capítulo 12

[[daniel-12-1]]
^1^ «En aquel tiempo surgirá Miguel, el gran Príncipe que defiende a los hijos de tu pueblo. Será aquél un tiempo de angustia como no habrá habido hasta entonces otro desde que existen las naciones. En aquel tiempo se salvará tu pueblo: todos los que se encuentren inscritos en el Libro.

[[daniel-12-2]]
^2^ Muchos de los que duermen en el polvo de la tierra se despertarán, unos para la vida eterna, otros para el oprobio, para el horror eterno.

[[daniel-12-3]]
^3^ Los doctos brillarán como el fulgor del firmamento, y los que enseñaron a la multitud la justicia, como las estrellas, por toda la eternidad.

[[daniel-12-4]]
^4^ «Y tú, Daniel, guarda en secreto estas palabras y sella el libro hasta el tiempo del Fin. Muchos andarán errantes acá y allá, y la iniquidad aumentará».

[[daniel-12-5]]
^5^ Yo, Daniel, miré y vi a otros dos que estaban de pie a una y otra parte del río.

[[daniel-12-6]]
^6^ Uno de ellos dijo al hombre vestido de lino que estaba sobre las aguas del río: «¿Cuándo será el cumplimiento de estas maravillas?»

[[daniel-12-7]]
^7^ Y oí al hombre vestido de lino, que estaba sobre las aguas del río, jurar, levantando al cielo la mano derecha y la izquierda, por Aquel que vive eternamente: «Un tiempo, tiempos y medio tiempo, y todas estas cosas se cumplirán cuando termine el quebrantamiento de la fuerza del Pueblo santo».

[[daniel-12-8]]
^8^ Yo oí, pero no comprendí. Luego dije: «Señor mío, ¿cuál será la última de estas cosas?»

[[daniel-12-9]]
^9^ Dijo: «Anda, Daniel, porque estas palabras están cerradas y selladas hasta el tiempo del Fin.

[[daniel-12-10]]
^10^ Muchos serán lavados, blanqueados y purgados; los impíos seguirán haciendo el mal; ningún impío comprenderá nada; sólo los doctos comprenderán.

[[daniel-12-11]]
^11^ Contando desde el momento en que sea abolido el sacrificio perpetuo e instalada la abominación de la desolación: mil doscientos noventa días.

[[daniel-12-12]]
^12^ Dichoso aquel que sepa esperar y alcance mil trescientos treinta y cinco días.

[[daniel-12-13]]
^13^ Y tú, vete a descansar; te levantarás para recibir tu suerte al Fin de los días».
[[daniel-13]]
== Capítulo 13

[[daniel-13-1]]
^1^ Vivía en Babilonia un hombre llamado Joaquín.

[[daniel-13-2]]
^2^ Se había casado con una mujer llamada Susana, hija de Jilquías, que era muy bella y temerosa de Dios;

[[daniel-13-3]]
^3^ sus padres eran justos y habían educado a su hija según la ley de Moisés.

[[daniel-13-4]]
^4^ Joaquín era muy rico, tenía un jardín contiguo a su casa, y los judíos solían acudir donde él, porque era el más prestigioso de todos.

[[daniel-13-5]]
^5^ Aquel año habían sido nombrados jueces dos ancianos, escogidos entre el pueblo, de aquellos de quienes dijo el Señor: «La iniquidad salió en Babilonia de los ancianos y jueces que se hacían guías del pueblo».

[[daniel-13-6]]
^6^ Venían éstos a menudo a casa de Joaquín, y todos los que tenían algún litigio se dirigían a ellos.

[[daniel-13-7]]
^7^ Cuando todo el mundo se había retirado ya, a mediodía, Susana entraba a pasear por el jardín de su marido.

[[daniel-13-8]]
^8^ Los dos ancianos, que la veían entrar a pasear todos los días, empezaron a desearla.

[[daniel-13-9]]
^9^ Perdieron la cabeza dejando de mirar hacia el cielo y olvidando sus justos juicios.

[[daniel-13-10]]
^10^ Estaban, pues, los dos apasionados por ella, pero no se descubrían mutuamente su tormento,

[[daniel-13-11]]
^11^ por vergüenza de confesarse el deseo que tenían de unirse a ella,

[[daniel-13-12]]
^12^ y trataban afanosamente de verla todos los días.

[[daniel-13-13]]
^13^ Un día, después de decirse el uno al otro: «Vamos a casa, que es hora de comer», salieron y se fueron cada uno por su lado.

[[daniel-13-14]]
^14^ Pero ambos volvieron sobre sus pasos y se encontraron de nuevo en el mismo sitio. Preguntándose entonces mutuamente el motivo, se confesaron su pasión y acordaron buscar el momento en que pudieran sorprender a Susana a solas.

[[daniel-13-15]]
^15^ Mientras estaban esperando la ocasión favorable, un día entró Susana en el jardín como los días precedentes, acompañada solamente de dos jóvenes doncellas, y como hacía calor quiso bañarse en el jardín.

[[daniel-13-16]]
^16^ No había allí nadie, excepto los dos ancianos que, escondidos, estaban al acecho.

[[daniel-13-17]]
^17^ Dijo ella a las doncellas: «Traedme aceite y perfume, y cerrad las puertas del jardín, para que pueda bañarme».

[[daniel-13-18]]
^18^ Ellas obedecieron, cerraron las puertas del jardín y salieron por la puerta lateral para traer lo que Susana había pedido; no sabían que los ancianos estaban escondidos.

[[daniel-13-19]]
^19^ En cuanto salieron las doncellas, los dos ancianos se levantaron, fueron corriendo donde ella,

[[daniel-13-20]]
^20^ y le dijeron: «Las puertas del jardín están cerradas y nadie nos ve. Nosotros te deseamos; consiente, pues, y entrégate a nosotros.

[[daniel-13-21]]
^21^ Si no, daremos testimonio contra ti diciendo que estaba contigo un joven y que por eso habías despachado a tus doncellas».

[[daniel-13-22]]
^22^ Susana gimió: «¡Ay, qué aprieto me estrecha por todas partes! Si hago esto, es la muerte para mí; si no lo hago, no escaparé de vosotros.

[[daniel-13-23]]
^23^ Pero es mejor para mí caer en vuestras manos sin haberlo hecho que pecar delante del Señor».

[[daniel-13-24]]
^24^ Y Susana se puso a gritar a grandes voces. Los dos ancianos gritaron también contra ella,

[[daniel-13-25]]
^25^ y uno de ellos corrió a abrir las puertas del jardín.

[[daniel-13-26]]
^26^ Al oír estos gritos en el jardín, los domésticos se precipitaron por la puerta lateral para ver qué ocurría,

[[daniel-13-27]]
^27^ y cuando los ancianos contaron su historia, los criados se sintieron muy confundidos, porque jamás se había dicho una cosa semejante de Susana.

[[daniel-13-28]]
^28^ A la mañana siguiente, cuando el pueblo se reunió en casa de Joaquín, su marido, llegaron allá los dos ancianos, llenos de pensamientos inicuos contra Susana para hacerla morir.

[[daniel-13-29]]
^29^ Y dijeron en presencia del pueblo: «Mandad a buscar a Susana, hija de Jilquías, la mujer de Joaquín». Mandaron a buscarla,

[[daniel-13-30]]
^30^ y ella compareció acompañada de sus padres, de sus hijos y de todos sus parientes.

[[daniel-13-31]]
^31^ Susana era muy delicada y de hermoso aspecto.

[[daniel-13-32]]
^32^ Tenía puesto el velo, pero aquellos miserables ordenaron que se le quitase el velo para saciarse de su belleza.

[[daniel-13-33]]
^33^ Todos los suyos lloraban, y también todos los que la veían.

[[daniel-13-34]]
^34^ Los dos ancianos, levantándose en medio del pueblo, pusieron sus manos sobre su cabeza.

[[daniel-13-35]]
^35^ Ella, llorando, levantó los ojos al cielo, porque su corazón tenía puesta su confianza en Dios.

[[daniel-13-36]]
^36^ Los ancianos dijeron: «Mientras nosotros nos paseábamos solos por el jardín, entró ésta con dos doncellas. Cerró las puertas y luego despachó a las doncellas.

[[daniel-13-37]]
^37^ Entonces se acercó a ella un joven que estaba escondido y se acostó con ella.

[[daniel-13-38]]
^38^ Nosotros, que estábamos en un rincón del jardín, al ver esta iniquidad, fuimos corriendo donde ellos.

[[daniel-13-39]]
^39^ Los sorprendimos juntos, pero a él no pudimos atraparle porque era más fuerte que nosotros, y abriendo la puerta se escapó.

[[daniel-13-40]]
^40^ Pero a ésta la agarramos y le preguntamos quién era aquel joven.

[[daniel-13-41]]
^41^ No quiso revelárnoslo. De todo esto nosotros somos testigos». La asamblea les creyó como ancianos y jueces del pueblo que eran. Y la condenaron a muerte.

[[daniel-13-42]]
^42^ Entonces Susana gritó fuertemente: «Oh Dios eterno, que conoces los secretos, que todo lo conoces antes que suceda,

[[daniel-13-43]]
^43^ tú sabes que éstos han levantado contra mí falso testimonio. Y ahora voy a morir, sin haber hecho nada de lo que su maldad ha tramado contra mí».

[[daniel-13-44]]
^44^ El Señor escuchó su voz

[[daniel-13-45]]
^45^ y, cuando era llevada a la muerte, suscitó el santo espíritu de un jovencito llamado Daniel,

[[daniel-13-46]]
^46^ que se puso a gritar: «¡Yo estoy limpio de la sangre de esta mujer!»

[[daniel-13-47]]
^47^ Todo el pueblo se volvió hacia él y dijo: «¿Qué significa eso que has dicho?»

[[daniel-13-48]]
^48^ El, de pie en medio de ellos, respondió: «¿Tan necios sois, hijos de Israel, para condenar sin investigación y sin evidencia a una hija de Israel?

[[daniel-13-49]]
^49^ ¡Volved al tribunal, porque es falso el testimonio que éstos han levantado contra ella!»

[[daniel-13-50]]
^50^ Todo el pueblo se apresuró a volver allá, y los ancianos dijeron a Daniel: «Ven a sentarte en medio de nosotros y dinos lo que piensas, ya que Dios te ha dado la dignidad de la ancianidad».

[[daniel-13-51]]
^51^ Daniel les dijo entonces: «Separadlos lejos el uno del otro, y yo les interrogaré».

[[daniel-13-52]]
^52^ Una vez separados, Daniel llamó a uno de ellos y le dijo: «Envejecido en la iniquidad, ahora han llegado al colmo los delitos de tu vida pasada,

[[daniel-13-53]]
^53^ dictador de sentencias injustas, que condenabas a los inocentes y absolvías a los culpables, siendo así que el Señor dice: “No matarás al inocente y al justo.”

[[daniel-13-54]]
^54^ Conque, si la viste, dinos bajo qué árbol los viste juntos». Respondió él: «Bajo una acacia».

[[daniel-13-55]]
^55^ «En verdad - dijo Daniel - contra tu propia cabeza has mentido, pues ya el ángel de Dios ha recibido de él la sentencia y viene a partirte por el medio».

[[daniel-13-56]]
^56^ Retirado éste, mandó traer al otro y le dijo: «¡Raza de Canaán, que no de Judá; la hermosura te ha descarriado y el deseo ha pervertido tu corazón!

[[daniel-13-57]]
^57^ Así tratabais a las hijas de Israel, y ellas, por miedo, se entregaban a vosotros. Pero una hija de Judá no ha podido soportar vuestra iniquidad.

[[daniel-13-58]]
^58^ Ahora pues, dime: ¿Bajo qué árbol los sorprendiste juntos?» El respondió: «Bajo una encina».

[[daniel-13-59]]
^59^ En verdad, dijo Daniel, tú también has mentido contra tu propia cabeza: ya está el ángel del Señor esperando, espada en mano, para partirte por el medio, a fin de acabar con vosotros».

[[daniel-13-60]]
^60^ Entonces la asamblea entera clamó a grandes voces, bendiciendo a Dios que salva a los que esperan en él.

[[daniel-13-61]]
^61^ Luego se levantaron contra los dos ancianos, a quienes, por su propia boca, había convencido Daniel de falso testimonio

[[daniel-13-62]]
^62^ y, para cumplir la ley de Moisés, les aplicaron la misma pena que ellos habían querido infligir a su prójimo: les dieron muerte, y aquel día se salvó una sangre inocente.

[[daniel-13-63]]
^63^ Jilquías y su mujer dieron gracias a Dios por su hija Susana, así como Joaquín su marido y todos sus parientes, por el hecho de que nada indigno se había encontrado en ella.

[[daniel-13-64]]
^64^ Y desde aquel día en adelante Daniel fue grande a los ojos del pueblo.
[[daniel-14]]
== Capítulo 14

[[daniel-14-1]]
^1^ El rey Astiages fue a reunirse con sus padres, y le sucedió Ciro el Persa.

[[daniel-14-2]]
^2^ Daniel era comensal del rey y más honrado que ningún otro de sus amigos.

[[daniel-14-3]]
^3^ Tenían los babilonios un ídolo, llamado Bel, con el que se gastaban cada día doce artabas de flor de harina, cuarenta ovejas y seis medidas de vino.

[[daniel-14-4]]
^4^ El rey también le veneraba y todos los días iba a adorarle. Daniel, en cambio, adoraba a su Dios.

[[daniel-14-5]]
^5^ El rey le dijo: «¿Por qué no adoras a Bel?» El respondió: «Porque yo no venero a ídolos hechos por mano humana, sino solamente al Dios vivo que hizo el cielo y la tierra y que tiene poder sobre toda carne».

[[daniel-14-6]]
^6^ Díjole el rey: ¿Crees que Bel no es un dios vivo? ¿No ves todo lo que come y bebe a diario?»

[[daniel-14-7]]
^7^ Daniel se echó a reír: «Oh rey, no te engañes - dijo -, por dentro es de arcilla y por fuera de bronce, y eso no ha comido ni bebido jamás».

[[daniel-14-8]]
^8^ Entonces el rey, montando en cólera, mandó llamar a sus sacerdotes y les dijo: «Si no me decís quién es el que come este dispendio, moriréis; pero si demostráis que el que lo come es Bel, morirá Daniel por haber blasfemado contra Bel».

[[daniel-14-9]]
^9^ Daniel dijo al rey: «¡Hágase según tu palabra!» Eran setenta los sacerdotes de Bel, sin contar las mujeres y los hijos.

[[daniel-14-10]]
^10^ El rey se dirigió, pues, con Daniel al templo de Bel,

[[daniel-14-11]]
^11^ y los sacerdotes de Bel le dijeron: «Mira, nosotros vamos a salir de aquí; tú, oh rey, manda poner la comida y el vino mezclado; luego cierra la puerta y séllada con tu anillo; si mañana por la mañana, cuando vuelvas, no encuentras que Bel se lo ha comido todo, moriremos nosotros; en caso contrario, morirá Daniel que nos ha calumniado».

[[daniel-14-12]]
^12^ Estaban ellos tranquilos, porque se habían hecho una entrada secreta debajo de la mesa y por allí entraban normalmente a llevarse las ofrendas.

[[daniel-14-13]]
^13^ En cuanto salieron y el rey depositó la comida ante Bel,

[[daniel-14-14]]
^14^ Daniel mandó a sus criados que trajeran ceniza y la esparcieran por todo el suelo del templo, sin más testigo que el rey. Luego salieron, cerraron la puerta, la sellaron con el anillo real, y se fueron.

[[daniel-14-15]]
^15^ Los sacerdotes vinieron por la noche, como de costumbre, con sus mujeres y sus hijos, y se lo comieron y bebieron todo.

[[daniel-14-16]]
^16^ El rey se levantó muy temprano y Daniel con él.

[[daniel-14-17]]
^17^ El rey le preguntó: «Daniel, ¿están intactos los sellos?» - «Intactos, oh rey», respondió él.

[[daniel-14-18]]
^18^ Nada más abierta la puerta, el rey echó una mirada a la mesa y gritó en alta voz: «¡Grande eres, Bel, y no hay en ti engaño alguno!»

[[daniel-14-19]]
^19^ Daniel se echó a reír y, deteniendo al rey para que no entrara más adentro, le dijo: «Mira, mira al suelo, y repara de quién son esas huellas».

[[daniel-14-20]]
^20^ - «Veo huellas de hombres, de mujeres y de niños», dijo el rey;

[[daniel-14-21]]
^21^ y, montando en cólera, mandó detener a los sacerdotes con sus mujeres y sus hijos. Ellos le mostraron entonces la puerta secreta por la que entraban a consumir lo que había sobre la mesa.

[[daniel-14-22]]
^22^ Y el rey mandó matarlos y entregó a Bel en manos de Daniel, el cual lo destruyó, así como su templo.

[[daniel-14-23]]
^23^ Habían también una gran serpiente a la que los babilonios veneraban.

[[daniel-14-24]]
^24^ El rey dijo a Daniel: «¿Vas a decir también que ésta es de bronce? Mira, está viva y come y bebe: no puedes decir que no es un dios vivo; así que adórale».

[[daniel-14-25]]
^25^ Daniel respondió: «Yo adoro sólo al Señor mi Dios; él es el Dios vivo. Mas tú, oh rey, dame permiso y yo mataré a esta serpiente sin espada ni estaca».

[[daniel-14-26]]
^26^ Dijo el rey: «Te lo doy».

[[daniel-14-27]]
^27^ Daniel tomó entonces pez, grasa y pelos, lo coció todo junto e hizo con ello unas bolitas que echó en las fauces de la serpiente; la serpiente las tragó y reventó. Y dijo Daniel: «¡Mirad qué es lo que veneráis!»

[[daniel-14-28]]
^28^ Al enterarse los babilonios, se enfurecieron mucho; se amotinaron contra el rey y dijeron: «El rey se ha hecho judío: ha destruido a Bel, ha matado a la serpiente, y a los sacerdotes los ha asesinado».

[[daniel-14-29]]
^29^ Fueron, pues, a decir al rey: «Entréganos a Daniel; si no, te mataremos a ti y a toda tu casa».

[[daniel-14-30]]
^30^ Ante esta gran violencia, el rey se vio obligado a entregarles a Daniel.

[[daniel-14-31]]
^31^ Ellos le echaron en el foso de los leones, donde estuvo seis días.

[[daniel-14-32]]
^32^ Había en el foso siete leones a los que se les daba diariamente dos cadáveres y dos carneros; entonces no se les dio nada, para que devoraran a Daniel.

[[daniel-14-33]]
^33^ Estaba a la sazón en Judea el profeta Habacuc: acababa de preparar un cocido y de desmenuzar pan en un plato, y se dirigía al campo a llevárselo a los segadores.

[[daniel-14-34]]
^34^ El ángel del Señor dijo a Habacuc: «Lleva esa comida que tienes a Babilonia, a Daniel que está en el foso de los leones».

[[daniel-14-35]]
^35^ «Señor - dijo Habacuc - no he visto jamás Babilonia ni conozco ese foso».

[[daniel-14-36]]
^36^ Entonces el ángel del Señor le agarró por la cabeza y, llevándole por los cabellos, le puso en Babilonia, encima del foso, con la rapidez de su soplo.

[[daniel-14-37]]
^37^ Habacuc gritó: «Daniel, Daniel, toma la comida que el Señor te ha enviado».

[[daniel-14-38]]
^38^ Y dijo Daniel; «Te has acordado de mí, Dios mío, y no has abandonado a los que te aman».

[[daniel-14-39]]
^39^ Y Daniel se levantó y se puso a comer, mientras el ángel de Dios volvía a llevar al instante a Habacuc a su lugar.

[[daniel-14-40]]
^40^ El día séptimo, vino el rey a llorar a Daniel; se acercó al foso, miró, y he aquí que Daniel estaba allí sentado.

[[daniel-14-41]]
^41^ Entonces exclamó: «Grande eres, Señor, Dios de Daniel, y no hay otro Dios fuera de ti».

[[daniel-14-42]]
^42^ Luego mandó sacarle y echar allá a aquellos que habían querido perderle, los cuales fueron al instante devorados en su presencia.
