[[hosea]]
= Oseas

[[hosea-1]]
== Capítulo 1

[[hosea-1-1]]
^1^ Palabra de Yahveh que fue dirigida a Oseas, hijo de Beerí, en tiempo de Ozías, Jotam, Ajaz y Ezequías, reyes de Judá, y en tiempo de Jeroboam, hijo de Joás, rey de Israel.

[[hosea-1-2]]
^2^ Comienzo de lo que habla Yahveh por Oseas. Dijo Yahveh a Oseas: «Ve, tómate una mujer dada a la prostitución e hijos de prostitución, porque la tierra se está prostituyendo enteramente, apartándose de Yahveh».

[[hosea-1-3]]
^3^ Fue él y tomó a Gómer, hija de Dibláyim, la cual concibió y le dio a luz un hijo.

[[hosea-1-4]]
^4^ Yahveh le dijo: «Ponle el nombre de Yizreel, porque dentro de poco visitaré yo la casa de Jehú por la sangre derramada en Yizreel, y pondré fin al reinado de la casa de Israel.

[[hosea-1-5]]
^5^ Aquel día romperé el arco de Israel en el valle de Yizreel».

[[hosea-1-6]]
^6^ Concibió ella de nuevo y dio a luz una hija. Y Yahveh dijo a Oseas: «Ponle el nombre de “Nocompadecida”, porque yo no me compadeceré más de la casa de Israel, soportándoles todavía.

[[hosea-1-7]]
^7^ (Pero de la casa de Judá me compadeceré y los salvaré por Yahveh su Dios. No los salvaré con arco ni espada ni guerra, ni con caballos ni jinetes.)»

[[hosea-1-8]]
^8^ Después de destetar a «No-compadecida», concibió otra vez y dio a luz un hijo.

[[hosea-1-9]]
^9^ Y dijo Yahveh: «Ponle el nombre de “No-mi-pueblo”, porque vosotros no sois mi pueblo ni yo soy para vosotros El-Que-Soy».
[[hosea-2]]
== Capítulo 2

[[hosea-2-1]]
^1^ El número de los hijos de Israel será como la arena del mar, que no se mide ni se cuenta. Y en el lugar mismo donde se les decía «No-mi-pueblo», se les dirá: «Hijos-de-Dios-vivo».

[[hosea-2-2]]
^2^ Se juntarán los hijos de Judá y los hijos de Israel en uno, se pondrán un solo jefe, y desbordarán de la tierra, porque será grande el día de Yizreel.

[[hosea-2-3]]
^3^ Decid a vuestros hermanos: «Mi pueblo», y a vuestras hermanas: «Compadecida».

[[hosea-2-4]]
^4^ ¡Pleitead con vuestra madre, pleitead, porque ella ya no es mi mujer, y yo no soy su marido! ¡Que quite de su rostro sus prostituciones y de entre sus pechos sus adulterios;

[[hosea-2-5]]
^5^ no sea que yo la desnude toda entera, y la deje como el día en que nació, la ponga hecha un desierto, la reduzca a tierra árida, y la haga morir de sed!

[[hosea-2-6]]
^6^ Ni de sus hijos me compadeceré, porque son hijos de prostitución.

[[hosea-2-7]]
^7^ Pues su madre se ha prostituido, se ha deshonrado la que los concibió, cuando decía: «Me iré detrás de mis amantes, los que me dan mi pan y mi agua, mi lana y mi lino, mi aceite y mis bebidas».

[[hosea-2-8]]
^8^ Por eso, yo cercaré su camino con espinos, la cercaré con seto y no encontrará más sus senderos;

[[hosea-2-9]]
^9^ perseguirá a sus amantes y no los alcanzará, los buscará y no los hallará. Entonces dirá: «Voy a volver a mi primer marido, que entonces me iba mejor que ahora».

[[hosea-2-10]]
^10^ No había conocido ella que era yo quien le daba el trigo, el mosto y el aceite virgen, ¡la plata yo se la multiplicaba, y el oro lo empleaban en Baal!

[[hosea-2-11]]
^11^ Por eso volveré a tomar mi trigo a su tiempo y mi mosto a su estación, retiraré mi lana y mi lino que habían de cubrir su desnudez.

[[hosea-2-12]]
^12^ Y ahora descubriré su vergüenza a los ojos de sus amantes, y nadie la librará de mi mano.

[[hosea-2-13]]
^13^ Haré cesar todo su regocijo, sus fiestas, sus novilunios, sus sábados, y todas sus solemnidades.

[[hosea-2-14]]
^14^ Arrasaré su viñedo y su higuera, de los que decía: «Ellos son mi salario, que me han dado mis amantes»; en matorral los convertiré, y la bestia del campo los devorará.

[[hosea-2-15]]
^15^ La visitaré por los días de los Baales, cuando les quemaba incienso, cuando se adornaba con su anillo y su collar y se iba detrás de sus amantes, olvidándose de mí, - oráculo de Yahveh.

[[hosea-2-16]]
^16^ Por eso yo voy a seducirla; la llevaré al desierto y hablaré a su corazón.

[[hosea-2-17]]
^17^ Allí le daré sus viñas, el valle de Akor lo haré puerta de esperanza; y ella responderá allí como en los días de su juventud, como el día en que subía del país de Egipto.

[[hosea-2-18]]
^18^ Y sucederá aquel día - oráculo de Yahveh - que ella me llamará: «Marido mío», y no me llamará más: «Baal mío».

[[hosea-2-19]]
^19^ Yo quitaré de su boca los nombres de los Baales, y no se mentarán más por su nombre.

[[hosea-2-20]]
^20^ Haré en su favor un pacto el día aquel con la bestia del campo, con el ave del cielo, con el reptil del suelo; arco, espada y guerra los quebraré lejos de esta tierra, y haré que ellos reposen en seguro.

[[hosea-2-21]]
^21^ Yo te desposaré conmigo para siempre; te desposaré conmigo en justicia y en derecho en amor y en compasión,

[[hosea-2-22]]
^22^ te desposaré conmigo en fidelidad, y tú conocerás a Yahveh.

[[hosea-2-23]]
^23^ Y sucederá aquel día que yo responderé - oráculo de Yahveh - responderé a los cielos, y ellos responderán a la tierra;

[[hosea-2-24]]
^24^ la tierra responderá al trigo, al mosto y al aceite virgen, y ellos responderán a Yizreel.

[[hosea-2-25]]
^25^ Yo la sembraré para mí en esta tierra, me compadeceré de «Nocompadecida», y diré a «Nomipueblo»: Tú «Mi pueblo», y él dirá: «¡Mi Dios!»
[[hosea-3]]
== Capítulo 3

[[hosea-3-1]]
^1^ Yahveh me dijo: «Ve otra vez, ama a una mujer que ama a otro y comete adulterio, como ama Yahveh a los hijos de Israel, mientras ellos se vuelven a otros dioses y gustan de las tortas de uva».

[[hosea-3-2]]
^2^ Yo me la compré por quince siclos de plata y carga y media de cebada.

[[hosea-3-3]]
^3^ Y le dije: «Durante muchos días te me quedarás quieta sin prostituirte ni ser de ningún hombre, y yo haré lo mismo contigo».

[[hosea-3-4]]
^4^ Porque durante muchos días se quedarán los hijos de Israel sin rey ni príncipe, sin sacrificios ni estela, sin efod ni terafim.

[[hosea-3-5]]
^5^ Después volverán los hijos de Israel; buscarán a Yahveh su Dios y a David, su rey, y acudirán con temor a Yahveh y a sus bienes en los días venidores.
[[hosea-4]]
== Capítulo 4

[[hosea-4-1]]
^1^ Escuchad la palabra de Yahveh, hijos de Israel, que tiene pleito Yahveh con los habitantes de esta tierra, pues no hay ya fidelidad ni amor, ni conocimiento de Dios en esta tierra;

[[hosea-4-2]]
^2^ sino perjurio y mentira, asesinato y robo, adulterio y violencia, sangre que sucede a sangre.

[[hosea-4-3]]
^3^ Por eso, la tierra está en duelo, y se marchita cuanto en ella habita, con las bestias del campo y las aves del cielo; y hasta los peces del mar desaparecen.

[[hosea-4-4]]
^4^ ¡Pero nadie pleitee ni reprenda nadie, pues sólo contigo, sacerdote, es mi pleito!

[[hosea-4-5]]
^5^ En pleno día tropezarás tú, también el profeta tropezará contigo en la noche, y yo haré perecer a tu madre.

[[hosea-4-6]]
^6^ Perece mi pueblo por falta de conocimiento. Ya que tú has rechazado el conocimiento, yo te rechazaré de mi sacerdocio; ya que tú has olvidado la Ley de tu Dios, también yo me olvidaré de tus hijos.

[[hosea-4-7]]
^7^ Todos, cuantos son, han pecado contra mí, han cambiado su Gloria por la Ignominia.

[[hosea-4-8]]
^8^ Del pecado de mi pueblo comen y hacia su culpa llevan su avidez.

[[hosea-4-9]]
^9^ Mas será del sacerdote lo que sea del pueblo: yo le visitaré por su conducta y sus obras le devolveré.

[[hosea-4-10]]
^10^ Comerán, pero no se saciarán, se prostituirán, pero no proliferarán, porque han abandonado a Yahveh para dedicarse

[[hosea-4-11]]
^11^ a la prostitución. El vino y el mosto arrebatan el seso.

[[hosea-4-12]]
^12^ Mi pueblo consulta a su madero, y su palo le adoctrina, porque un espíritu de prostitución le extravía, y se protituyen sacudiéndose de su Dios.

[[hosea-4-13]]
^13^ En las cimas de los montes sacrifican, en las colinas queman incienso, bajo la encina, el chopo o el terebinto, ¡porque es buena su sombra! Por eso, si se prostituyen vuestras hijas y vuestras nueras cometen adulterio,

[[hosea-4-14]]
^14^ no visitaré yo a vuestras hijas porque se prostituyan ni a vuestras nueras porque cometan adulterio, pues que ellos también se retiran con esas prostitutas y sacrifican con las consagradas a la prostitución; ¡y el pueblo, insensato, se pierde!

[[hosea-4-15]]
^15^ Si tú, Israel, te prostituyes, que no se haga culpable Judá. ¡No vayáis a Guilgal, No subáis a Bet Aven, no juréis «por vida de Yahveh»!

[[hosea-4-16]]
^16^ Ya que Israel se ha embravecido cual vaca brava, ¿los va a apacentar ahora Yahveh como a un cordero en ancho prado?

[[hosea-4-17]]
^17^ Efraím se ha apegado a sus ídolos, ¡déjale!

[[hosea-4-18]]
^18^ En saliendo de beber se prostituyen más y más, prefieren a su Prez la Ignominia.

[[hosea-4-19]]
^19^ El viento los cerrará entre sus alas, y se avergonzarán de sus sacrificios.
[[hosea-5]]
== Capítulo 5

[[hosea-5-1]]
^1^ Escuchad esto, sacerdotes, estad atentos, casa de Israel, casa real, prestad oído, porque el juicio es cosa vuestra; pero vosotros habéis sido un lazo en Mispá, y una red tendida en el Tabor.

[[hosea-5-2]]
^2^ Han ahondado la fosa de Sittim, mas yo seré castigo para todos ellos.

[[hosea-5-3]]
^3^ Yo conozco a Efraím, e Israel no se me oculta. Sí, tú te has prostituido, Efraím, e Israel se ha contaminado,

[[hosea-5-4]]
^4^ No les permiten sus obras volver a su Dios, pues un espíritu de prostitución hay dentro de ellos, y no conocen a Yahveh.

[[hosea-5-5]]
^5^ El orgullo de Israel testifica contra él; Israel y Efraím tropiezan por sus culpas, y también Judá tropieza con ellos.

[[hosea-5-6]]
^6^ Con su ganado menor y mayor irán en busca de Yahveh, pero no lo encontrarán: ¡se ha retirado de ellos!

[[hosea-5-7]]
^7^ Han sido infieles a Yahveh, han engrendado hijos bastardos; pues ahora los va a devorar el novilunio juntamente con sus campos.

[[hosea-5-8]]
^8^ Tocad el cuerno en Guibeá, la trompeta en Ramá, dad la alarma en Bet Aven, ¡detrás de ti, Benjamín!

[[hosea-5-9]]
^9^ Efraím será una desolación el día del castigo; en las tribus de Israel hago saber cosa segura.

[[hosea-5-10]]
^10^ Los príncipes de Judá son como los que desplazan los linderos, sobre ellos voy a derramar como agua mi furor.

[[hosea-5-11]]
^11^ Está oprimido Efraím, quebrantado el juicio, porque se complace en ir tras la Vanidad.

[[hosea-5-12]]
^12^ Pues yo he de ser como polilla para Efraím, como carcoma para la casa de Judá.

[[hosea-5-13]]
^13^ Efraím ha visto su dolencia y Judá su llaga. Efraím entonces ha sido a Asiria, y Judá ha mandado mensaje al gran rey; pero éste no podrá sanaros ni curar vuestra llaga.

[[hosea-5-14]]
^14^ Porque yo soy como un león para Efraím, como un leoncillo para la casa de Judá. Yo, yo mismo desgarraré y me iré, arrebataré y no habrá quien salve.

[[hosea-5-15]]
^15^ Voy a volverme a mi lugar, hasta que hayan expiado y busquen mi rostro. En su angustia me buscarán.
[[hosea-6]]
== Capítulo 6

[[hosea-6-1]]
^1^ «Venid, volvamos a Yahveh, pues él ha desgarrado y él nos curará, él ha herido y él nos vendará.

[[hosea-6-2]]
^2^ Dentro de dos días nos dará la vida, al tercer día nos hará resurgir y en su presencia viviremos.

[[hosea-6-3]]
^3^ Conozcamos, corramos al conocimiento de Yahveh: cierta como la aurora es su salida; vendrá a nosotros como la lluvia temprana, como la lluvia tardía que riega la tierra».

[[hosea-6-4]]
^4^ ¿Qué he de hacer contigo, Efraím? ¿Qué he de hacer contigo, Judá? ¡Vuestro amor es como nube mañanera, como rocío matinal, que pasa!

[[hosea-6-5]]
^5^ Por eso les he hecho trizas por los profetas, los he matado por las palabras de mi boca, y mi juicio surgirá como la luz.

[[hosea-6-6]]
^6^ Porque yo quiero amor, no sacrificio, conocimiento de Dios, más que holocaustos.

[[hosea-6-7]]
^7^ Pero ellos en Adam han violado la alianza, allí me han sido infieles.

[[hosea-6-8]]
^8^ Galaad es ciudad de malhechores, llena de huellas de sangre.

[[hosea-6-9]]
^9^ Como emboscada de bandidos es la pandilla de sacerdotes: asesinan por el camino de Siquem, y cometen infamia.

[[hosea-6-10]]
^10^ Cosa horrible he visto en Betel: allí se prostituye Efraím y se contamina Israel.

[[hosea-6-11]]
^11^ También para ti, Judá, hay preparada una cosecha, cuando yo cambie la suerte de mi pueblo.
[[hosea-7]]
== Capítulo 7

[[hosea-7-1]]
^1^ Cuando yo quiero sanar a Israel, se descubre la culpa de Efraím y las maldades de Samaria; porque practican la mentira, y mientras el ladrón entra dentro se despliega la pandilla afuera.

[[hosea-7-2]]
^2^ Y no se dicen en su corazón que yo me acuerdo de toda su maldad. Ahora les envuelven sus obras, ante mi rostro están.

[[hosea-7-3]]
^3^ Con su maldad recrean al rey, con sus mentiras a los príncipes.

[[hosea-7-4]]
^4^ Todos ellos, adúlteros, son como un horno ardiente, que el panadero deja de atizar desde que amasa la pasta hasta que fermenta.

[[hosea-7-5]]
^5^ En el día de nuestro rey los príncipes enferman por el ardor del vino, ¡y aquél tiende la mano a chocarreros!

[[hosea-7-6]]
^6^ Cuando acechan, su corazón es como un horno en sus intrigas: toda la noche duerme el panadero, y a la mañana él quema con fuego llameante.

[[hosea-7-7]]
^7^ Todos están calientes como un horno, y devoran a sus propios jueces. Todos sus reyes han caído, y ninguno entre ellos clama a mí.

[[hosea-7-8]]
^8^ Efraím se mezcla con los pueblos, Efraím es una torta a la que no se ha dado vuelta.

[[hosea-7-9]]
^9^ Extranjeros devoran su fuerza, ¡y él no lo sabe! Ya las canas blanquean en él, ¡y él no lo sabe!

[[hosea-7-10]]
^10^ El orgullo de Israel testifica contra él, pero no se vuelven a Yahveh su Dios, con todo esto, no le buscan.

[[hosea-7-11]]
^11^ Efraím es cual ingenua paloma, sin cordura; llaman a Egipto, acuden a Asiria.

[[hosea-7-12]]
^12^ Dondequiera que vayan, yo echaré mi red sobre ellos, como ave del cielo los haré caer y los visitaré por su maldad.

[[hosea-7-13]]
^13^ ¡Ay de ellos, que de mí se han alejado! ¡Ruina sobre ellos por haberse rebelado contra mí! Yo los rescataría, pero ellos dicen contra mí mentiras.

[[hosea-7-14]]
^14^ Y no claman a mí de corazón cuando gimen en sus lechos; por el trigo y el mosto se hacen incisiones se rebelan contra mí.

[[hosea-7-15]]
^15^ Yo fortalecí su brazo, ¡y ellos contra mí maquinan el mal!

[[hosea-7-16]]
^16^ Se vuelven a lo que no es nada, son como un arco engañoso. Caerán a espada sus príncipes, por la iracundia de su lengua: ¡tal será su escarnio en el país de Egipto!
[[hosea-8]]
== Capítulo 8

[[hosea-8-1]]
^1^ ¡Emboca la trompeta! Como un águila cae el mal sobre la casa de Yahveh; porque han quebrantado mi alianza y han sido rebeldes a mi Ley.

[[hosea-8-2]]
^2^ Ellos me gritan: «¡Dios mío, los de Israel te conocemos!»

[[hosea-8-3]]
^3^ Pero Israel ha rechazado el bien: ¡el enemigo le perseguirá!

[[hosea-8-4]]
^4^ Han puesto reyes sin contar conmigo, han puesto príncipes sin saberlo yo. Con su plata y su oro se han hecho ídolos, ¡para ser encarcelados!

[[hosea-8-5]]
^5^ ¡Tu becerro repele, Samaria! Mi cólera se ha inflamado contra ellos: ¿hasta cuándo no podrán purificarse?

[[hosea-8-6]]
^6^ Porque viene de Israel, un artesano ha hecho eso, y eso no es Dios. Sí, quedará hecho trizas el becerro de Samaria.

[[hosea-8-7]]
^7^ Pues que viento siembran, segarán tempestad: tallo que no tendrá espiga, que no dará harina; y si la da, extranjeros la tragarán.

[[hosea-8-8]]
^8^ ¡Tragado ha sido Israel! Están ahora entre las naciones como un objeto que nadie quiere.

[[hosea-8-9]]
^9^ Porque han subido a Asiria, ese onagro solitario; Efraím se ha comprado amores;

[[hosea-8-10]]
^10^ aunque los compre entre las naciones, yo los voy a reunir ahora y pronto sufrirán bajo la carga del rey de príncipes.

[[hosea-8-11]]
^11^ Efraím ha multiplicado los altares para pecar, sólo para pecar le han servido los altares.

[[hosea-8-12]]
^12^ Aunque yo escriba para él las excelencias de mi ley, por cosa extraña se las considera.

[[hosea-8-13]]
^13^ ¡Ya pueden ofrecer sacrificios en mi honor, y comerse la carne! Yahveh no los acepta; ahora recordará sus culpas y visitará sus pecados: ellos volverán a Egipto.

[[hosea-8-14]]
^14^ Olvida Israel a su Hacedor, edifica palacios; Judá multiplica las ciudades fuertes. Pero yo prenderé fuego a sus ciudades, que devorará sus alcázares.
[[hosea-9]]
== Capítulo 9

[[hosea-9-1]]
^1^ No te regocijes, Israel, no jubiles como los pueblos, pues te has prostituido, lejos de tu Dios, y amas ese salario sobre todas las eras de grano.

[[hosea-9-2]]
^2^ Ni la era ni el lagar los alimentarán, y el mosto los dejará corridos.

[[hosea-9-3]]
^3^ No habitarán ya en la tierra de Yahveh: Efraím volverá a Egipto, y en Asiria comerán viandas impuras.

[[hosea-9-4]]
^4^ No harán a Yahveh libaciones de vino, ni sus sacrificios le serán gratos: cual pan de duelo será para ellos, cuantos lo coman se harán impuros; pues su pan será para ellos solos, no entrará en la Casa de Yahveh.

[[hosea-9-5]]
^5^ ¿Qué haréis el día de solemnidad, el día de la fiesta de Yahveh?

[[hosea-9-6]]
^6^ Vedlos que han escapado de la devastación: Egipto los recogerá, Menfis los sepultará; sus tesoros de plata, la ortiga los heredará, la zarza llenará sus tiendas.

[[hosea-9-7]]
^7^ Han llegado los días de la visita, han llegado los días de la retribución. ¡Lo sabrá Israel! - «¡El profeta es un necio, un loco el hombre del espíritu!» - Por la grandeza de tu culpa, grande será la hostilidad.

[[hosea-9-8]]
^8^ Vigila a Efraím, con mi Dios, el profeta: lazos se le tienden en todos sus caminos, hostilidad en la Casa de su Dios.

[[hosea-9-9]]
^9^ Han llegado al fondo de la corrupción, como en los días de Guibeá; él recordará sus culpas y visitará sus pecados.

[[hosea-9-10]]
^10^ Como uvas en desierto encontré yo a Israel, como breva de higuera en sus primicias vi a vuestros padres. Pero al llegar ellos a Baal Peor se consagraron a la Infamia, y se hicieron abominables como el objeto de su amor.

[[hosea-9-11]]
^11^ A Efraím, como un pájaro, se le vuela su gloria, desde el nacimiento, desde el seno, desde la concepción.

[[hosea-9-12]]
^12^ Y aunque críen a sus hijos, yo les privaré de ellos antes que se hagan hombres: y ¡ay de ellos también cuando yo los abandone!

[[hosea-9-13]]
^13^ Efraím, tal lo he visto, era como Tiro plantada en la pradera, pero Efraím tendrá que sacar sus hijos al verdugo.

[[hosea-9-14]]
^14^ Dales, Yahveh..., ¿qué les darás? ¡Dales seno que aborte y pechos secos!

[[hosea-9-15]]
^15^ Toda su maldad apareció en Guilgal, sí, allí les cobré odio. Por la maldad de sus acciones, de mi Casa los expulsaré; ya no he de amarlos más: rebeldes son todos sus príncipes.

[[hosea-9-16]]
^16^ Efraím ha sido herido, su raíz está seca, ya no darán fruto. Aunque den a luz, yo haré morir el tesoro de su seno.

[[hosea-9-17]]
^17^ Mi Dios los rechazará porque no le han escuchado, y andarán errantes entre las naciones.
[[hosea-10]]
== Capítulo 10

[[hosea-10-1]]
^1^ Vid frondosa era Israel produciendo fruto a su aire: cuanto más aumentaba su fruto, más aumentaba los altares; cuanto mejor era su tierra, mejores hacía las estelas.

[[hosea-10-2]]
^2^ Su corazón es doble, mas ahora van a expiar; él romperá sus altares, demolerá sus estelas.

[[hosea-10-3]]
^3^ Entonces dirán: «No tenemos rey, porque no hemos temido a Yahveh, y el rey, ¿qué haría por nosotros?

[[hosea-10-4]]
^4^ Pronuncian palabras, juramentos vanos, conclusión de alianzas, y el juicio florece como hierba venenosa en los surcos del campo.

[[hosea-10-5]]
^5^ Por el becerro de Bet Aven tiemblan los habitantes de Samaria; sí, por él hace duelo su pueblo, por él sus sacerdotes: ¡que exulten por su gloria, porque ha emigrado lejos de él!

[[hosea-10-6]]
^6^ El también será llevado a Asiria, como ofrenda para el gran rey. Efraím recogerá vergüenza, e Israel quedará corrida de su plan.

[[hosea-10-7]]
^7^ ¡Se ha acabado Samaria! Su rey es como espuma sobre la haz del agua.

[[hosea-10-8]]
^8^ Serán destruidos los altos de Aven, el pecado de Israel. Espinas y zarzas treparán por sus altares. Dirán entonces a los montes: «¡Cubridnos!» y a las colinas: «¡Caed sobre nosotros!»

[[hosea-10-9]]
^9^ Desde los días de Guibeá, has pecado, Israel, ¡allí se han plantado! ¿No los alcanzará en Guibeá la guerra, a los hijos de la injusticia?

[[hosea-10-10]]
^10^ Voy a venir a visitarlos, y se aliarán pueblos contra ellos, cuando sean visitados por su doble culpa.

[[hosea-10-11]]
^11^ Efraím era una novilla domesticada, que gustaba de la trilla; yo pasé el yugo sobre su hermoso cuello; uncí el carro a Efraím, Judá arraba, Jacob rastrillaba.

[[hosea-10-12]]
^12^ Sembraos simiente de justicia, recoged cosecha de amor, desbarbechad lo que es barbecho; ya es tiempo de buscar a Yahveh, hasta que venga a lloveros justicia.

[[hosea-10-13]]
^13^ Habéis arado maldad, injusticia habéis segado, habéis comido fruto de mentira. Por haber confiado en tus carros, en la multitud de tus valientes,

[[hosea-10-14]]
^14^ tumulto de guerra se alzará en tu pueblo, y todas tus fortalezas serán devastadas, como Salmán devastó a Bet Arbel el día de la batalla, cuando la madre fue estrellada sobre sus hijos.

[[hosea-10-15]]
^15^ Eso ha hecho con vosotros Betel por vuestra redoblada maldad. ¡A la aurora desaparecerá el rey de Israel!
[[hosea-11]]
== Capítulo 11

[[hosea-11-1]]
^1^ Cuando Israel era niño, yo le amé, y de Egipto llamé a mi hijo.

[[hosea-11-2]]
^2^ Cuanto más los llamaba, más se alejaban de mí: a los Baales sacrificaban, y a los ídolos ofrecían incienso.

[[hosea-11-3]]
^3^ Yo enseñé a Efraím a caminar, tomándole por los brazos, pero ellos no conocieron que yo cuidaba de ellos.

[[hosea-11-4]]
^4^ Con cuerdas humanas los atraía, con lazos de amor, y era para ellos como los que alzan a un niño contra su mejilla, me inclinaba hacia él y le daba de comer.

[[hosea-11-5]]
^5^ Volverá al país de Egipto, y Asur será su rey, porque se han negado a convertirse.

[[hosea-11-6]]
^6^ Hará estragos la espada en sus ciudades, aniquilará sus cerrojos y devorará, por sus perversos planes.

[[hosea-11-7]]
^7^ Mi pueblo tiene querencia a su infidelidad; cuando a lo alto se les llama, ni uno hay que se levante.

[[hosea-11-8]]
^8^ ¿Cómo voy a dejarte, Efraím, cómo entregarte, Israel? ¿Voy a dejarte como a Admá, y hacerte semejante a Seboyim? Mi corazón está en mí trastornado, y a la vez se estremecen mis entrañas.

[[hosea-11-9]]
^9^ No daré curso al ardor de mi cólera, no volveré a destruir a Efraím, porque soy Dios, no hombre; en medio de ti yo soy el Santo, y no vendré con ira.

[[hosea-11-10]]
^10^ En pos de Yahveh marcharán, él rugirá como un león; y cuando ruja él, los hijos vendrán azorados de occidente,

[[hosea-11-11]]
^11^ azorados vendrán de Egipto, como un pájaro, como paloma desde el país de Asiria; y yo les asentaré en sus casas - oráculo de Yahveh -.
[[hosea-12]]
== Capítulo 12

[[hosea-12-1]]
^1^ Efraím me ha rodeado de mentira, de engaño la casa de Israel. (Pero Judá todavía está con Dios, y sigue fiel al Santo.)

[[hosea-12-2]]
^2^ Efraím se apacienta de viento, anda tras el solano todo el día; mentira y pillaje multiplica, hacen alianza con Asiria y llevan aceite a Egipto.

[[hosea-12-3]]
^3^ Yahveh tiene pleito con Judá, va a visitar a Jacob, según su conducta, según sus obras le devolverá.

[[hosea-12-4]]
^4^ En el seno materno suplantó a su hermano, y de mayor luchó con Dios.

[[hosea-12-5]]
^5^ Luchó con el ángel y le pudo, lloró y le imploró gracia. En Betel le encontró y allí habló con nosotros.

[[hosea-12-6]]
^6^ Sí, Yahveh Dios Sebaot, Yahveh es su renombre.

[[hosea-12-7]]
^7^ Y tú volverás, gracias a tu Dios: observa amor y derecho, y espera en tu Dios siempre.

[[hosea-12-8]]
^8^ Canaán tiene en su mano balanzas tramposas, es amigo de explotar.

[[hosea-12-9]]
^9^ Y Efraím dice: «Sí, me he enriquecido, me ha fraguado una fortuna». ¡Ninguna de sus ganancias se hallará, por el pecado de que se ha hecho culpable!

[[hosea-12-10]]
^10^ Yo soy Yahveh, tu Dios, desde el país de Egipto: aún te haré morar en tiendas como en los días del Encuentro;

[[hosea-12-11]]
^11^ hablaré a los profetas, multiplicaré las visiones, y por medio de los profetas hablaré en parábolas.

[[hosea-12-12]]
^12^ Si Galaad es iniquidad, ellos no son más que mentira. En Guilgal sacrifican toros; por eso sus altares serán como escombros sobre los surcos de los campos.

[[hosea-12-13]]
^13^ Huyó Jacob a la campiña de Aram, sirvió Israel por una mujer, por una mujer guardó rebaños.

[[hosea-12-14]]
^14^ Por un profeta subió Yahveh a Israel de Egipto, y por un profeta fue guardado.

[[hosea-12-15]]
^15^ Efraím le ha irritado amargamente: él dejará su sangre sobre él, su Señor le pagará su agravio.
[[hosea-13]]
== Capítulo 13

[[hosea-13-1]]
^1^ Cuando hablaba Efraím, cundía el terror, se había impuesto en Israel, pero se hizo culpable con Baal y murió.

[[hosea-13-2]]
^2^ Y todavía continúan pecando: se han hecho imágenes fundidas, con su plata, ídolos de su invención: ¡obra de artesanos todo ello! ¡Con ellos hablan los que sacrifican hombres que envían besos a becerros!

[[hosea-13-3]]
^3^ Por eso serán como nube mañanera, como rocío matinal que pasa, como paja aventada de la era, como humo por la ventana.

[[hosea-13-4]]
^4^ Pero yo soy Yahveh, tu Dios, desde el país de Egipto. No conoces otro Dios fuera de mí, ni hay más salvador que yo.

[[hosea-13-5]]
^5^ Yo te conocí en el desierto, en la tierra ardorosa.

[[hosea-13-6]]
^6^ Cuando estaban en su pasto se saciaron, se saciaron y se engrió su corazón, por eso se olvidaron de mí.

[[hosea-13-7]]
^7^ Pues yo seré para ellos cual león, como leopardo en el camino acecharé.

[[hosea-13-8]]
^8^ Caeré sobre ellos como osa privada de sus cachorros, desgarraré las telas de su corazón, los devoraré allí mismo cual leona, la bestia del campo los despedazará.

[[hosea-13-9]]
^9^ Tu destrucción ha sido, Israel, porque sólo en mí estaba tu socorro.

[[hosea-13-10]]
^10^ ¿Dónde está, pues, tu rey, para que te salve, y en todas tus ciudades tus jueces? aquellos de quienes tú decías: «Dame rey y príncipes».

[[hosea-13-11]]
^11^ Rey en mi cólera te doy, y te lo quito en mi furor.

[[hosea-13-12]]
^12^ Encerrada está la culpa de Efraím, bien guardado su pecado.

[[hosea-13-13]]
^13^ Dolores de parturienta le asaltan, pero él es un hijo necio que no se presenta a tiempo por donde rompen los hijos.

[[hosea-13-14]]
^14^ ¿De la garra del seol los libraré, de la muerte los rescataré? ¿Dónde están, muerte, tus pestes, dónde tu contagio, seol? La compasión está oculta a mis ojos.

[[hosea-13-15]]
^15^ Aunque Efraím dé fruto entre sus hermanos, el solano llegará, el viento de Yahveh subirá del desierto, para que se seque su manantial, y se agote su fuente; él arrebatará el tesoro de todos los objetos preciosos.
[[hosea-14]]
== Capítulo 14

[[hosea-14-1]]
^1^ Rea de castigo es Samaria, porque se rebeló contra su Dios. A espada caerán, serán sus niños estrellados, y reventadas sus mujeres encinta.

[[hosea-14-2]]
^2^ Vuelve, Israel, a Yahveh tu Dios, pues has tropezado por tus culpas.

[[hosea-14-3]]
^3^ Tomad con vosotros palabras, y volved a Yahveh. Decidle: «Quita toda culpa; toma lo que es bueno; y en vez de novillos te ofreceremos nuestros labios.

[[hosea-14-4]]
^4^ Asiria no nos salvará, no montaremos ya a caballo, y no diremos más “Dios nuestro” a la obra de nuestros manos, oh tú, en quien halla compasión el huérfano».

[[hosea-14-5]]
^5^ - Yo sanaré su infidelidad, los amaré graciosamente; pues mi cólera se ha apartado de él,

[[hosea-14-6]]
^6^ seré como rocío para Israel: él florecerá como el lirio, y hundirá sus raíces como el Líbano.

[[hosea-14-7]]
^7^ Sus ramas se desplegarán, como el del olivo será su esplendor, y su fragancia como la del Líbano.

[[hosea-14-8]]
^8^ Volverán a sentarse a mi sombra; harán crecer el trigo, florecerán como la vid, su renombre será como el del vino del Líbano.

[[hosea-14-9]]
^9^ Efraím... ¿qué tiene aún con los ídolos? Yo le atiendo y le miro. Yo soy como un ciprés siempre verde, y gracias a mí se te halla fruto.

[[hosea-14-10]]
^10^ ¿Quién es sabio para entender estas cosas, inteligente para conocerlas?: Que rectos son los caminos de Yahveh, por ellos caminan los justos, mas los rebeldes en ellos tropiezan.
