[[joel]]
= Joel

[[joel-1]]
== Capítulo 1

[[joel-1-1]]
^1^ Palabra de Yahveh que fue dirigida a Joel, hijo de Petuel.

[[joel-1-2]]
^2^ ¡Oíd esto, ancianos, prestad oído, habitantes todos de la tierra! ¿Sucedió algo semejante en vuestros días, o en los días de vuestros padres?

[[joel-1-3]]
^3^ Contádselo a vuestros hijos, y vuestros hijos a sus hijos, y sus hijos a la otra generación.

[[joel-1-4]]
^4^ Lo que dejó la oruga lo devoró la langosta, lo que dejó la langosta lo devoró el pulgón, lo que dejó el pulgón lo devoró el saltón.

[[joel-1-5]]
^5^ ¡Despertad, borrachos, y llorad, gemid todos los bebedores de vino, por el licor que se os ha quitado de la boca!

[[joel-1-6]]
^6^ Porque una nación ha subido contra mi tierra, fuerte e innumerable: sus dientes son dientes de león, y tienen muelas de leona.

[[joel-1-7]]
^7^ En desolación ha dejado mi viña, destrozada mi higuera: la ha pelado del todo y derribado, y sus ramas han quedado blancas.

[[joel-1-8]]
^8^ ¡Suspira tú como virgen ceñida de sayal por el esposo de su juventud!

[[joel-1-9]]
^9^ Oblación y libación han sido arrancadas de la Casa de Yahveh. En duelo están los sacerdotes, los ministros de Yahveh.

[[joel-1-10]]
^10^ El campo ha sido arrasado, en duelo está el suelo, porque el grano ha sido arrasado, ha faltado el mosto, y el aceite virgen se ha agotado.

[[joel-1-11]]
^11^ ¡Consternaos, labradores, gemid, viñadores, por el trigo y la cebada, porque se ha perdido la cosecha del campo!

[[joel-1-12]]
^12^ Se ha secado la viña, se ha amustiado la higuera, granado, palmera, manzano, todos los árboles del campo están secos. ¡Sí, se ha secado la alegría de entre los hijos de hombre!

[[joel-1-13]]
^13^ ¡Ceñíos y plañid, sacerdotes, gemid, ministros del altar; venid, pasad la noche en sayal, ministros de mi Dios, porque a la Casa de vuestro Dios se le ha negado oblación y libación!

[[joel-1-14]]
^14^ Promulgad un ayuno, llamad a concejo, reuníos, ancianos, y vosotros todos, habitantes de la tierra, en la Casa de Yahveh, vuestro Dios, y clamad a Yahveh:

[[joel-1-15]]
^15^ «¡Ay, el Día, que está cerca el Día de Yahveh, ya llega como devastación de Sadday!»

[[joel-1-16]]
^16^ ¿No ha sido arrancada la comida de delante de nuestros ojos, y de la Casa de nuestro Dios la alegría y el júbilo?

[[joel-1-17]]
^17^ Se han podrido los granos bajo los terrones; los graneros han sido devastados, derruidos los silos, porque falta el grano.

[[joel-1-18]]
^18^ ¡Cómo muge el ganado, cómo vagan sin rumbo los rebaños de vacas, porque no hay pastor para ellos! ¡Hasta los rebaños de ovejas tienen que expiar!

[[joel-1-19]]
^19^ A ti clamo, Yahveh, porque el fuego ha devorado los pastizales del desierto, la llama ha abrasado todos los árboles del campo.

[[joel-1-20]]
^20^ Hasta las bestias del campo jadean tras de ti, porque están secas las corrientes de agua, y el fuego ha devorado los pastizales del desierto.
[[joel-2]]
== Capítulo 2

[[joel-2-1]]
^1^ ¡Tocad el cuerno en Sión, clamad en mi monte santo! ¡Tiemblen todos los habitantes del país, porque llega el Día de Yahveh, porque está cerca!

[[joel-2-2]]
^2^ ¡Día de tinieblas y de oscuridad, día de nublado y densa niebla! Como la aurora sobre los montes se despliega un pueblo numeroso y fuerte, como jamás hubo otro, ni lo habrá después de él en años de generación en generación.

[[joel-2-3]]
^3^ Delante de él devora el fuego, detrás de él la llama abrasa. Como un jardín de Edén era delante de él la tierra, detrás de él, un desierto desolado. ¡No hay escape ante él!

[[joel-2-4]]
^4^ Aspecto de corceles es su aspecto, como jinetes, así corren.

[[joel-2-5]]
^5^ Como estrépito de carros, por las cimas de los montes saltan, como el crepitar de la llama de fuego que devora hojarasca; ¡como un pueblo poderoso en orden de batalla!

[[joel-2-6]]
^6^ Ante él se estremecen los pueblos, todos los rostros mudan de color.

[[joel-2-7]]
^7^ Corren como bravos, como guerreros escalan las murallas; cada uno va por su camino, y no intercambian su ruta.

[[joel-2-8]]
^8^ Nadie tropieza con su vecino, van cada cual por su calzada; a través de los dardos arremeten sin romper la formación.

[[joel-2-9]]
^9^ Sobre la ciudad se precipitan, corren por la muralla, hasta las casas suben, a través de las ventanas entran como ladrones.

[[joel-2-10]]
^10^ ¡Ante él tiembla la tierra, se estremecen los cielos, el sol y la luna se oscurecen, y las estrellas retraen su fulgor!

[[joel-2-11]]
^11^ Ya da Yahveh la voz delante de su ejército, porque sus batallones son inmensos, porque es fuerte el ejecutor de su palabra, porque es grande el Día de Yahveh, y muy terrible: ¿quién lo soportará?

[[joel-2-12]]
^12^ «Mas ahora todavía - oráculo de Yahveh - volved a mí de todo corazón, con ayuno, con llantos, con lamentos».

[[joel-2-13]]
^13^ Desgarrad vuestro corazón y no vuestros vestidos, volved a Yahveh vuestro Dios, porque él es clemente y compasivo, tardo a la cólera, rico en amor, y se ablanda ante la desgracia.

[[joel-2-14]]
^14^ ¡Quién sabe si volverá y se ablandará, y dejará tras sí una bendición, oblación y libación a Yahveh vuestro Dios!

[[joel-2-15]]
^15^ ¡Tocad el cuerno en Sión, promulgad un ayuno, llamad a concejo,

[[joel-2-16]]
^16^ congregad al pueblo, convocad la asamblea, reunid a los ancianos, congregad a los pequeños y a los niños de pecho! Deje el recién casado su alcoba y la recién casada su tálamo.

[[joel-2-17]]
^17^ Entre el vestíbulo y el altar lloren los sacerdotes, ministros de Yahveh, y digan: «¡Perdona, Yahveh, a tu pueblo, y no entregues tu heredad al oprobio a la irrisión de las naciones! ¿Por qué se ha de decir entre los pueblos: ¿Dónde está su Dios?»

[[joel-2-18]]
^18^ Y Yahveh se llenó de celo por su tierra, y tuvo piedad de su pueblo.

[[joel-2-19]]
^19^ Respondió Yahveh y dijo a su pueblo: «He aquí que yo os envío grano, mosto y aceite virgen: os hartaréis de ello, y no os entregaré más al oprobio de las naciones.

[[joel-2-20]]
^20^ Al que viene del Norte le alejaré de vosotros, y le echaré hacia una tierra de aridez y desolación: su vanguardia hacia el mar oriental, hacia el mar occidental su retaguardia. Y subirá su hedor, y subirá su fetidez». (¡Porque él hace grandezas!)

[[joel-2-21]]
^21^ No temas, suelo, jubila y regocíjate, porque Yahveh hace grandezas.

[[joel-2-22]]
^22^ No temáis, bestias del campo, porque ya reverdecen los pastizales del desierto, los árboles producen su fruto, la higuera y la vid dan su riqueza.

[[joel-2-23]]
^23^ ¡Hijos de Sión, jubilad, alegraos en Yahveh vuestro Dios! Porque él os da la lluvia de otoño, con justa medida, y hace caer para vosotros aguacero de otoño y primavera como antaño.

[[joel-2-24]]
^24^ Las eras se llenarán de trigo puro, de mosto y aceite virgen los lagares rebosarán.

[[joel-2-25]]
^25^ «Yo os compensaré de los años en que os devoraron la langosta y el pulgón, el saltón y la oruga, mi gran ejército, que contra vosotros envié».

[[joel-2-26]]
^26^ Comeréis en abundancia hasta hartaros, y alabaréis el nombre de Yahveh vuestro Dios, que hizo con vosotros maravillas. (¡Mi pueblo no será confundido jamás!)

[[joel-2-27]]
^27^ «Y sabréis que en medio de Israel estoy yo, ¡yo, Yahveh, vuestro Dios, y no hay otro! ¡Y mi pueblo no será confundido jamás!»
[[joel-3]]
== Capítulo 3

[[joel-3-1]]
^1^ «Sucederá después de esto que yo derramaré mi Espíritu en toda carne. Vuestros hijos y vuestras hijas profetizarán, vuestros ancianos soñarán sueños, y vuestros jóvenes verán visiones.

[[joel-3-2]]
^2^ Hasta en los siervos y las siervas derramaré mi Espíritu en aquellos días.

[[joel-3-3]]
^3^ Y realizaré prodigios en el cielo y en la tierra, sangre, fuego, columnas de humo».

[[joel-3-4]]
^4^ El sol se cambiará en tinieblas y la luna en sangre, ante la venida del Día de Yahveh, grande y terrible.

[[joel-3-5]]
^5^ Y sucederá que todo el que invoque el nombre de Yahveh será salvo, porque en el monte Sión y en Jerusalén habrá supervivencia, como ha dicho Yahveh, y entre los supervivientes estarán los que llame Yahveh.
[[joel-4]]
== Capítulo 4

[[joel-4-1]]
^1^ «Porque he aquí que en aquellos días, en el tiempo aquel, cuando yo cambie la suerte de Judá y Jerusalén,

[[joel-4-2]]
^2^ congregaré a todas las naciones y las haré bajar al Valle de Josafat: allí entraré en juicio con ellas, acerca de mi pueblo y mi heredad, Israel. Porque lo dispersaron entre las naciones, y mi tierra se repartieron.

[[joel-4-3]]
^3^ Y echaron suertes sobre mi pueblo, cambiaron el niño por la prostituta, y a la niña la vendieron por vino para beber».

[[joel-4-4]]
^4^ «Y vosotros también, ¿qué sois para mí, Tiro y Sidón, y distritos todos de Filistea? ¿Queréis exigir paga de mí? Mas, si queréis cobrar de mí, ¡bien pronto he de volver sobre vuestra cabeza vuestra paga!

[[joel-4-5]]
^5^ Vosotros que arrebatasteis mi plata y mi oro, que llevasteis a vuestros templos mis mejores alhajas,

[[joel-4-6]]
^6^ y a los hijos de Judá y Jerusalén los vendisteis a los hijos de Yaván, para alejarlos de su término.

[[joel-4-7]]
^7^ He aquí que yo los voy a reclamar del lugar donde los vendisteis, y volveré sobre vuestra cabeza vuestra paga:

[[joel-4-8]]
^8^ venderé vuestros hijos y vuestras hijas en manos de los hijos de Judá, y ellos los venderán a los sabeos, a una nación lejana, ¡porque ha hablado Yahveh!»

[[joel-4-9]]
^9^ Publicad esto entre las naciones: ¡Proclamad la guerra, incitad a los bravos! ¡Que avancen y suban todos los hombres de guerra!

[[joel-4-10]]
^10^ Forjad espadas de vuestros azadones y lanzad de vuestras podaderas; y diga el débil: «¡Soy un bravo!»

[[joel-4-11]]
^11^ ¡Daos prisa, venid, naciones todas circundantes, y congregaos allá! (¡Haz bajar, Yahveh, a tus bravos!)

[[joel-4-12]]
^12^ «¡Despiértense y suban las naciones al Valle de Josafat! Que allí me sentaré yo para juzgar a todas las naciones circundantes.

[[joel-4-13]]
^13^ Meted la hoz, porque la mies está madura; venid, pisad, que el lagar está lleno, y las cavas rebosan, tan grande es su maldad».

[[joel-4-14]]
^14^ ¡Multitudes y multitudes en el Valle de la Decisión! Porque está cerca el Día de Yahveh, en el Valle de la Decisión.

[[joel-4-15]]
^15^ El sol y la luna se oscurecen, las estrellas retraen su fulgor.

[[joel-4-16]]
^16^ Ruge Yahveh desde Sión, desde Jerusalén da su voz: ¡el cielo y la tierra se estremecen! Mas Yahveh será un refugio para su pueblo, una fortaleza para los hijos de Israel.

[[joel-4-17]]
^17^ «Sabréis entonces que yo soy Yahveh vuestro Dios, que habito en Sión, mi monte santo. Santa será Jerusalén, y los extranjeros no pasarán más por ella».

[[joel-4-18]]
^18^ Sucederá aquel día que los montes destilarán vino y las colinas fluirán leche; por todas las torrenteras de Judá fluirán las aguas; y una fuente manará de la Casa de Yahveh que regará el valle de las Acacias.

[[joel-4-19]]
^19^ Egipto quedará hecho una desolación, Edom un desierto desolado, por su violencia contra los hijos de Judá, por haber derramado sangre inocente en su tierra.

[[joel-4-20]]
^20^ Pero Judá será habitada para siempre, y Jerusalén de edad en edad.

[[joel-4-21]]
^21^ «Yo vengaré su sangre, no la dejaré impune», y Yahveh morará en Sión.
