[[obadiah]]
= Abdías

[[obadiah-1]]
== Capítulo 1

[[obadiah-1-1]]
^1^ Visión de Abdías. Así dice el Señor Yahveh a Edom: Una nueva he oído de parte de Yahveh, un mensajero ha sido enviado entre las naciones: «¡En pie, levantémonos contra él en guerra!»

[[obadiah-1-2]]
^2^ Mira, yo te he hecho pequeño entre las naciones, bien despreciable eres.

[[obadiah-1-3]]
^3^ La soberbia de tu corazón te ha engañado, tú que habitas en las hendiduras de la roca, que pones en la altura tu morada, y dices en tu corazón: «¿Quién me hará bajar a tierra?»

[[obadiah-1-4]]
^4^ Aunque te encumbres como él águila, y pongas tu nido en las estrellas, de allí te haré bajar yo - oráculo de Yahveh.

[[obadiah-1-5]]
^5^ Si vinieran ladrones donde ti o salteadores por la noche, ¿no te robarían lo que les bastase? Si vinieran a ti vendimiadores, ¿no dejarían rebuscos? ¡Cómo has sido arrasado!

[[obadiah-1-6]]
^6^ ¡Cómo ha sido registrado Esaú, escudriñados sus escondrijos!

[[obadiah-1-7]]
^7^ Te han rechazado hasta la frontera todos los que eran tus aliados, te han engañado, te han podido los que contigo en paz estaban. Los que comían tu pan te ponen debajo un lazo: «¡Ya no hay en él inteligencia!»

[[obadiah-1-8]]
^8^ ¿Es que el día aquel - oráculo de Yahveh - no suprimiré yo de Edom los sabios, y la inteligencia de la montaña de Esaú?

[[obadiah-1-9]]
^9^ Y tendrán miedo tus bravos, Temán, para que sea extirpado todo hombre de la montaña de Esaú. Por la matanza,

[[obadiah-1-10]]
^10^ por la violencia contra Jacob tu hermano, te cubrirá la vergüenza, y serás extirpado para siempre.

[[obadiah-1-11]]
^11^ El día que te quedaste a un lado, cuando extranjeros llevaban su ejército cautivo, cuando entraban extraños por sus puertas, y sobre Jerusalén echaban suertes, tú eras como uno de ellos.

[[obadiah-1-12]]
^12^ ¡No mires con placer el día de tu hermano, el día de su desgracia, no te alegres de los hijos de Judá, en el día de su ruina, no dilates tu boca en el día de su angustia!

[[obadiah-1-13]]
^13^ ¡No entres por la puerta de mi pueblo en el día de su infortunio, no mires con placer también tú su desgracia en el día de su infortunio, no lleves tu mano a su riqueza, en el día de su infortunio!

[[obadiah-1-14]]
^14^ ¡No te apostes en las encrucijadas, para exterminar a sus fugitivos, no entregues a sus supervivientes en el día de la angustia!

[[obadiah-1-15]]
^15^ Porque está cerca el Día de Yahveh para todas las naciones. Como tú has hecho, se te hará: sobre tu cabeza recaerá tu merecido.

[[obadiah-1-16]]
^16^ ¡Sí, como vosotros bebisteis sobre mi santo monte, beberán sin cesar todas las naciones, beberán y se relamerán, y serán luego como si no hubiesen sido!

[[obadiah-1-17]]
^17^ Pero en el monte Sión habrá supervivencia - será lugar santo - y la casa de Jacob recobrará sus posesiones.

[[obadiah-1-18]]
^18^ Y será fuego la casa de Jacob, la casa de José una llama, estopa la casa de Esaú. Los quemarán y los devorarán, no habrá un evadido de la casa de Esaú: ¡ha hablado Yahveh!

[[obadiah-1-19]]
^19^ Los del Négueb poseerán la montaña de Esaú, los de la Tierra Baja el país de los filisteos, poseerán la campiña de Efraím y la campiña de Samaria, y los de Benjamín poseerán Galaad.

[[obadiah-1-20]]
^20^ Los deportados, este ejército de los hijos de Israel, poseerán Canaán hasta Sarepta, y los deportados de Jerusalén, que están en Sefarad, poseerán las ciudades del Négueb.

[[obadiah-1-21]]
^21^ Y subirán victoriosos al monte Sión, para juzgar a la montaña de Esaú. ¡Y la realeza será de Yahveh!
