[[jonah]]
= Jonás

[[jonah-1]]
== Capítulo 1

[[jonah-1-1]]
^1^ La palabra de Yahveh fue dirigida a Jonás, hijo de Amittay, en estos términos:

[[jonah-1-2]]
^2^ «Levántate, vete a Nínive, la gran ciudad, y proclama contra ella que su maldad ha subido hasta mí».

[[jonah-1-3]]
^3^ Jonás se levantó para huir a Tarsis, lejos de Yahveh, y bajó a Joppe, donde encontró un barco que salía para Tarsis: pagó su pasaje y se embarcó para ir con ellos a Tarsis, lejos de Yahveh.

[[jonah-1-4]]
^4^ Pero Yahveh desencadenó un gran viento sobre el mar, y hubo en el mar una borrasca tan violenta que el barco amenazaba romperse.

[[jonah-1-5]]
^5^ Los marineros tuvieron miedo y se pusieron a invocar cada uno a su dios; luego echaron al mar la carga del barco para aligerarlo. Jonás, mientras tanto, había bajado al fondo del barco, se había acostado y dormía profundamente.

[[jonah-1-6]]
^6^ El jefe de la tripulación se acercó a él y le dijo: «¿Qué haces aquí dormido? ¡Levántate e invoca a tu Dios! Quizás Dios se preocupe de nosotros y no perezcamos».

[[jonah-1-7]]
^7^ Luego se dijeron unos a otros: «Ea, echemos a suertes para saber por culpa de quién nos ha venido este mal». Echaron a suertes, y la suerte cayó en Jonás.

[[jonah-1-8]]
^8^ Entonces le dijeron: «Anda, indícanos tú, por quien nos ha venido este mal, cuál es tu oficio y de dónde vienes, cuál es tu país y de qué pueblo eres».

[[jonah-1-9]]
^9^ Les respondió: «Soy hebreo y temo a Yahveh, Dios del cielo, que hizo el mar y la tierra».

[[jonah-1-10]]
^10^ Aquellos hombres temieron mucho y le dijeron: «¿Por qué has hecho esto?» Pues supieron los hombres que iba huyendo lejos de Yahveh por lo que él había manifestado.

[[jonah-1-11]]
^11^ Y le preguntaron: «¿Qué hemos de hacer contigo para que el mar se nos calme?» Pues el mar seguía encrespándose.

[[jonah-1-12]]
^12^ Les respondió: «Agarradme y tiradme al mar, y el mar se os calmará, pues sé que es por mi culpa por lo que os ha sobrevenido esta gran borrasca».

[[jonah-1-13]]
^13^ Los hombres se pusieron a remar con ánimo de alcanzar la costa, pero no pudieron, porque el mar seguía encrespándose en torno a ellos.

[[jonah-1-14]]
^14^ Entonces clamaron a Yahveh, diciendo: «¡Ah, Yahveh, no nos hagas perecer a causa de este hombre, ni pongas sobre nosotros sangre inocente, ya que tú, Yahveh, has obrado conforme a tu beneplácito!»

[[jonah-1-15]]
^15^ Y, agarrando a Jonás, le tiraron al mar; y el mar calmó su furia.

[[jonah-1-16]]
^16^ Y aquellos hombres temieron mucho a Yahveh; ofrecieron un sacrificio a Yahveh y le hicieron votos.
[[jonah-2]]
== Capítulo 2

[[jonah-2-1]]
^1^ Dispuso Yahveh un gran pez que se tragase a Jonás, y Jonás estuvo en el vientre del pez tres días y tres noches.

[[jonah-2-2]]
^2^ Jonás oró a Yahveh su Dios desde el vientre del pez.

[[jonah-2-3]]
^3^ Dijo: Desde mi angustia clamé a Yahveh y él me respondió; desde el seno del seol grité, y tú oíste mi voz.

[[jonah-2-4]]
^4^ Me habías arrojado en lo más hondo, en el corazón del mar, una corriente me cercaba: todas tus olas y tus crestas pasaban sobre mí.

[[jonah-2-5]]
^5^ Yo dije: ¡Arrojado estoy de delante de tus ojos! ¿Cómo volveré a contemplar tu santo Templo?

[[jonah-2-6]]
^6^ Me envolvían las aguas hasta el alma, me cercaba el abismo, un alga se enredaba a mi cabeza.

[[jonah-2-7]]
^7^ A las raíces de los montes descendí, a un país que echó sus cerrojos tras de mí para siempre, mas de la fosa tú sacaste mi vida, Yahveh, Dios mío.

[[jonah-2-8]]
^8^ Cuando mi alma en mí desfallecía me acordé de Yahveh, y mi oración llegó hasta ti, hasta tu santo Templo.

[[jonah-2-9]]
^9^ Los que veneran vanos ídolos su propia gracia abandonan.

[[jonah-2-10]]
^10^ Mas yo con voz de acción de gracias te ofreceré sacrificios, los votos que hice cumpliré. ¡De Yahveh la salvación!

[[jonah-2-11]]
^11^ Y Yahveh dio orden al pez, que vomitó a Jonás en tierra.
[[jonah-3]]
== Capítulo 3

[[jonah-3-1]]
^1^ Por segunda vez fue dirigida la palabra de Yahveh a Jonás en estos términos:

[[jonah-3-2]]
^2^ «Levántate, vete a Nínive, la gran ciudad y proclama el mensaje que yo te diga».

[[jonah-3-3]]
^3^ Jonás se levantó y fue a Nínive conforme a la palabra de Yahveh. Nínive era una ciudad grandísima, de un recorrido de tres días.

[[jonah-3-4]]
^4^ Jonás comenzó a adentrarse en la ciudad, e hizo un día de camino proclamando: «Dentro de cuarenta días Nínive será destruida».

[[jonah-3-5]]
^5^ Los ninivitas creyeron en Dios: ordenaron un ayuno y se vistieron de sayal desde el mayor al menor.

[[jonah-3-6]]
^6^ La palabra llegó hasta el rey de Nínive, que se levantó de su trono, se quitó su manto, se cubrió de sayal y se sentó en la ceniza.

[[jonah-3-7]]
^7^ Luego mandó pregonar y decir en Nínive: «Por mandato del rey y de sus grandes, que hombres y bestias, ganado mayor y menor, no prueben bocado ni pasten ni beban agua.

[[jonah-3-8]]
^8^ Que se cubran de sayal y clamen a Dios con fuerza; que cada uno se convierta de su mala conducta y de la violencia que hay en sus manos.

[[jonah-3-9]]
^9^ ¡Quién sabe! Quizás vuelva Dios y se arrepienta, se vuelva del ardor de su cólera, y no perezcamos».

[[jonah-3-10]]
^10^ Vio Dios lo que hacían, cómo se convirtieron de su mala conducta, y se arrepintió Dios del mal que había determinado hacerles, y no lo hizo.
[[jonah-4]]
== Capítulo 4

[[jonah-4-1]]
^1^ Jonás, se disgustó mucho por esto y se irritó;

[[jonah-4-2]]
^2^ y oró a Yahveh diciendo: «¡Ah, Yahveh!, ¿no es esto lo que yo decía cuando estaba todavía en mi tierra? Fue por eso por lo que me apresuré a huir a Tarsis. Porque bien sabía yo que tú eres un Dios clemente y misericordioso, tardo a la cólera y rico en amor, que se arrepiente del mal.

[[jonah-4-3]]
^3^ Y ahora, Yahveh, te suplico que me quites la vida, porque mejor me es la muerte que la vida».

[[jonah-4-4]]
^4^ Mas Yahveh dijo: «¿Te parece bien irritarte?»

[[jonah-4-5]]
^5^ Salió Jonás de la ciudad y se sentó al oriente de la ciudad; allí se hizo una cabaña bajo la cual se sentó a la sombra, hasta ver qué sucedía en la ciudad.

[[jonah-4-6]]
^6^ Entonces Yahveh Dios dispuso una planta de ricino que creciese por encima de Jonás para dar sombra a su cabeza y librarle así de su mal. Jonás se puso muy contento por aquel ricino.

[[jonah-4-7]]
^7^ Pero al día siguiente, al rayar el alba, Yahveh mandó a un gusano, y el gusano picó al ricino, que se secó.

[[jonah-4-8]]
^8^ Y al salir el sol, mandó Dios un sofocante viento solano. El sol hirió la cabeza de Jonás, y éste se desvaneció; se deseó la muerte y dijo: «¡Mejor me es la muerte que la vida!»

[[jonah-4-9]]
^9^ Entonces Dios dijo a Jonás: «¿Te parece bien irritarte por ese ricino?» Respondió: «¡Sí, me parece bien irritarme hasta la muerte!»

[[jonah-4-10]]
^10^ Y Yahveh dijo: «Tu tienes lástima de un ricino por el que nada te fatigaste, que no hiciste tú crecer, que en el término de una noche fue y en el término de una noche feneció.

[[jonah-4-11]]
^11^ ¿Y no voy a tener lástima yo de Nínive, la gran ciudad, en la que hay más de ciento veinte mil personas que no distinguen su derecha de su izquierda, y una gran cantidad de animales?»
