[[zephaniah]]
= Sofonías

[[zephaniah-1]]
== Capítulo 1

[[zephaniah-1-1]]
^1^ Palabra de Yahveh que fue dirigida a Sofonías, hijo de Kusí, hijo de Guedalías, hijo de Amarías, hijo de Ezequías, en tiempo de Josías, hijo de Amón, rey de Judá.

[[zephaniah-1-2]]
^2^ ¡Voy a aventarlo todo de la haz de la tierra!, oráculo de Yahveh.

[[zephaniah-1-3]]
^3^ Aventaré hombres y bestias, aventaré aves del cielo y peces del mar, haré tropezar a los impíos; extirparé a los hombres de sobre la haz de la tierra, oráculo de Yahveh.

[[zephaniah-1-4]]
^4^ Extenderé mi mano contra Judá, y contra todos los habitantes de Jerusalén, y extirparé de este lugar lo que queda de Baal, el nombre de los ministros con los sacerdotes,

[[zephaniah-1-5]]
^5^ los que se postran en los terrados ante el ejército del cielo, los que se postran ante Yahveh y juran por Milkom,

[[zephaniah-1-6]]
^6^ los que se apartan del seguimiento de Yahveh, los que no buscan a Yahveh ni le consultan.

[[zephaniah-1-7]]
^7^ ¡Silencio ante el Señor Yahveh, porque el Día de Yahveh está cerca! Sí, Yahveh ha preparado un sacrificio, ha consagrado a sus invitados.

[[zephaniah-1-8]]
^8^ Sucederá en el día del sacrificio de Yahveh que yo visitaré a los príncipes, a los hijos del rey, y a todos los que visten vestido extranjero.

[[zephaniah-1-9]]
^9^ Visitaré aquel día a todos los que saltan por encima del umbral, los que llenan la Casa de su Señor de violencia y de fraude.

[[zephaniah-1-10]]
^10^ Habrá aquel día - oráculo de Yahveh - gritos de auxilio desde la puerta de los Peces, aullidos desde la ciudad nueva, estruendo enorme desde las colinas.

[[zephaniah-1-11]]
^11^ ¡Ululad, habitantes del Mortero, pues ha sido aniquilado todo el pueblo de Canaán, exterminados todos los que pesan plata!

[[zephaniah-1-12]]
^12^ Sucederá en el tiempo aquel que yo escrutaré a Jerusalén con lámparas, y visitaré a los hombres que se apelmazan en sus heces, los que dicen en su corazón: «¡Ni bien ni mal hace Yahveh!»

[[zephaniah-1-13]]
^13^ Será dada al saqueo su riqueza, sus casas a la devastación; casas contruyeron, mas no las habitarán, plantaron viñas, mas no beberán su vino.

[[zephaniah-1-14]]
^14^ ¡Cercano está el gran Día de Yahveh, cercano, a toda prisa viene! ¡Amargo el ruido del día de Yahveh, dará gritos entonces hasta el bravo!

[[zephaniah-1-15]]
^15^ Día de ira el día aquel, día de angustia y de aprieto, día de devastación y desolación, día de tinieblas y de oscuridad, día de nublado y densa niebla,

[[zephaniah-1-16]]
^16^ día de trompeta y de clamor, contra las ciudades fortificadas y las torres de los ángulos.

[[zephaniah-1-17]]
^17^ Yo pondré a los hombres en aprieto, y ellos como ciegos andarán, (porque pecaron contra Yahveh); su sangre será derramada como polvo, y su carne como excremento.

[[zephaniah-1-18]]
^18^ Ni su plata ni su oro podrán salvarlos en el Día de la ira de Yahveh, cuando por el fuego de su celo la tierra entera sea devorada; pues él hará exterminio, ¡y terrorífico!, de todos los habitantes de la tierra.
[[zephaniah-2]]
== Capítulo 2

[[zephaniah-2-1]]
^1^ Reuníos, congregaos, gente sin vergüenza,

[[zephaniah-2-2]]
^2^ antes que seáis aventados como el tamo que en un día pasa, antes que caiga sobre vosotros el ardor de la cólera de Yahveh, (antes que caiga sobre vosotros el Día de la cólera de Yahveh).

[[zephaniah-2-3]]
^3^ Buscad a Yahveh, vosotros todos, humildes de la tierra, que cumplís sus normas; buscad la justicia, buscad la humildad; quizá encontréis cobijo el Día de la cólera de Yahveh.

[[zephaniah-2-4]]
^4^ Pues Gaza quedará en desamparo, y Ascalón en desolación, a Asdod se la expulsará en pleno mediodía, y Ecrón será arrancada de raíz.

[[zephaniah-2-5]]
^5^ ¡Ay de los habitantes de la liga del mar, la nación de los kereteos! Palabra de Yahveh contra vosotros: «Canaán, tierra de los filisteos, te destruiré, te dejaré sin habitantes;

[[zephaniah-2-6]]
^6^ quedará la liga del mar convertida en pastizales, en pradera de pastores, en apriscos de ovejas».

[[zephaniah-2-7]]
^7^ Y será la liga del mar para el Resto de la casa de Judá: allí llevarán a pacer, en las casas de Ascalón reposarán a la tarde, cuando los visite Yahveh su Dios, y los vuelva de su cautiverio.

[[zephaniah-2-8]]
^8^ He oído los insultos de Moab y los denuestos de los hijos de Ammón, cuando insultaron a mi pueblo, y se engrandecieron a costa de su territorio.

[[zephaniah-2-9]]
^9^ Por eso, ¡por mi vida - oráculo de Yahveh Sebaot, Dios de Israel - que Moab quedará como Sodoma, y los habitantes de Ammón como Gomorra: cardizal, mina de sal, desolación para siempre! El Resto de mi pueblo los saqueará, lo que quede de mi nación los heredará.

[[zephaniah-2-10]]
^10^ Este será el precio de su orgullo, por haber insultado, por haberse engrandecido a costa del pueblo de Yahveh Sebaot.

[[zephaniah-2-11]]
^11^ Terrible será Yahveh contra ellos, cuando enerve a todos los dioses de la tierra, y se postren ante él, cada una en su lugar, todas las islas de las naciones.

[[zephaniah-2-12]]
^12^ También vosotros, etíopes: «Víctimas de mi espada serán ellos».

[[zephaniah-2-13]]
^13^ El extenderá su mano contra el norte, destruirá a Asur, y dejará a Nínive en desolación, árida como el desierto.

[[zephaniah-2-14]]
^14^ Se tumbarán en medio de ella los rebaños, toda suerte de animales: hasta el pelícano, hasta el erizo, pasarán la noche entre sus capiteles. El búho cantará en la ventana, y el cuervo en el umbral, porque el cedro fue arrancado.

[[zephaniah-2-15]]
^15^ Tal será la ciudad alegre que reposaba en seguridad, la que decía en su corazón: «¡Yo, y nadie más!» ¡Cómo ha quedado en desolación, en guarida de animales! Todo el que pasa junto a ella silba y menea su mano.
[[zephaniah-3]]
== Capítulo 3

[[zephaniah-3-1]]
^1^ ¡Ay de la rebelde, la manchada, la ciudad opresora!

[[zephaniah-3-2]]
^2^ No ha escuchado la voz, no ha aceptado la corrección; en Yahveh no ha puesto su confianza, a su Dios no se ha acercado.

[[zephaniah-3-3]]
^3^ Sus príncipes, en medio de ella, son leones rugientes, sus jueces, lobos de la tarde, que no dejan un hueso para la mañana.

[[zephaniah-3-4]]
^4^ Sus profetas, fanfarrones, hombres traicioneros, sus sacerdotes profanan lo que es santo y violan la Ley.

[[zephaniah-3-5]]
^5^ Yahveh es justo en medio de ella, no comete injusticia; cada mañana pronuncia su juicio, no falta nunca al alba; (pero el inicuo no conoce la vergüenza).

[[zephaniah-3-6]]
^6^ Yo he exterminado a las naciones, sus almenas han sido derruidas, he dejado desiertas sus calles, sin un transeúnte; han sido arrasadas sus ciudades, no queda hombre ni habitante.

[[zephaniah-3-7]]
^7^ Y me dije: «Al menos tú me temerás, aceptarás la corrección; no puede quitarse de sus ojos todo aquello con que yo la he visitado». Pero ellos han madrugado a corromper todas sus acciones.

[[zephaniah-3-8]]
^8^ Por eso, esperadme - oráculo de Yahveh - el día en que me levante como testigo, porque he decidido reunir a las naciones, congregar a los reinos, para derramar sobre vosotros mi enojo, todo el ardor de mi cólera. (Porque por el fuego de mi celo la tierra entera será devorada).

[[zephaniah-3-9]]
^9^ Yo entonces volveré puro el labio de los pueblos, para que invoquen todos el nombre de Yahveh, y le sirvan bajo un mismo yugo.

[[zephaniah-3-10]]
^10^ Desde allende los ríos de Etiopía, mis suplicantes, mi Dispersión, me traerán mi ofrenda.

[[zephaniah-3-11]]
^11^ Aquel día no tendrás ya que avergonzarte de todos los delitos que cometiste contra mí, porque entonces quitaré yo de tu seno a tus alegres orgullosos, y no volverás a engreírte en mi santo monte.

[[zephaniah-3-12]]
^12^ Yo dejaré en medio de ti un pueblo humilde y pobre, y en el nombre de Yahveh se cobijará

[[zephaniah-3-13]]
^13^ el Resto de Israel. No cometerán más injusticia, no dirán mentiras, y no más se encontrará en su boca lengua embustera. Se apacentarán y reposarán, sin que nadie los turbe.

[[zephaniah-3-14]]
^14^ ¡Lanza gritos de gozo, hija de Sión, lanza clamores, Israel, alégrate y exulta de todo corazón, hija de Jerusalén!

[[zephaniah-3-15]]
^15^ Ha retirado Yahveh las sentencias contra ti, ha alejado a tu enemigo. ¡Yahveh, Rey de Israel, está en medio de ti, no temerás ya ningún mal!

[[zephaniah-3-16]]
^16^ Aquel día se dirá a Jerusalén: ¡No tengas miedo, Sión, no desmayen tus manos!

[[zephaniah-3-17]]
^17^ Yahveh tu Dios está en medio de ti, ¡un poderoso salvador! El exulta de gozo por ti, te renueva por su amor; danza por ti con gritos de júbilo,

[[zephaniah-3-18]]
^18^ como en los días de fiesta. Yo quitaré de tu lado la desgracia, el oprobio que pesa sobre ti.

[[zephaniah-3-19]]
^19^ He aquí que yo haré exterminio de todos tus opresores, en el tiempo aquel; y salvaré a la coja y recogeré a la descarriada, y haré que tengan alabanza y renombre en todos los países donde fueron confundidas.

[[zephaniah-3-20]]
^20^ En aquel tiempo os haré venir, en aquel tiempo os congregaré. Entonces os daré renombre y alabanza entre todos los pueblos de la tierra, cuando yo vuelva a vuestros cautivos a vuestros propios ojos, dice Yahveh.
