[[zechariah]]
= Zacarías

[[zechariah-1]]
== Capítulo 1

[[zechariah-1-1]]
^1^ En el octavo mes del año segundo de Darío fue dirigida la palabra de Yahveh al profeta Zacarías (hijo de Berekías), hijo de Iddó, en estos términos:

[[zechariah-1-2]]
^2^ «Yahveh se ha irritado mucho contra vuestros padres».

[[zechariah-1-3]]
^3^ Les dirás: «Así dice Yahveh Sebaot: Volveos a mí - oráculo de Yahveh Sebaot - y yo me volveré a vosotros, dice Yahveh Sebaot.

[[zechariah-1-4]]
^4^ No seáis como vuestros padres, a quienes los antiguos profetas gritaban así: “¡Volveos de vuestros malos caminos y de vuestras malas obras!” Pero ellos no escucharon ni me hicieron caso - oráculo de Yahveh -.

[[zechariah-1-5]]
^5^ Vuestros padres ¿dónde están? Y los profetas ¿van a vivir por siempre?

[[zechariah-1-6]]
^6^ Sin embargo, mis palabras y preceptos que yo había prescrito a mis siervos los profetas ¿no alcanzaron a vuestros padres? Por eso se volvieron ellos y dijeron: “Como Yahveh Sebaot había decidido tratarnos, según nuestros caminos y nuestras obras, así nos ha tratado”».

[[zechariah-1-7]]
^7^ El día veinticuatro del undécimo mes (que es el mes de Sebat), el año segundo de Darío, fue dirigida la palabra de Yahveh al profeta Zacarías (hijo de (Berekías), hijo de Iddó, en estos términos:

[[zechariah-1-8]]
^8^ He tenido una visión esta noche. Era un hombre que montaba un caballo rojo; estaba de pie entre los mirtos que hay en la hondonada; detrás de él, caballos rojos, alazanes y blancos.

[[zechariah-1-9]]
^9^ Yo dije: «¿Quiénes son éstos, señor mío?» El ángel que hablaba conmigo me dijo: «Yo te enseñaré quiénes son éstos».

[[zechariah-1-10]]
^10^ Y el hombre que estaba entre los mirtos intervino y dijo: «Estos son los que ha enviado Yahveh a recorrer la tierra».

[[zechariah-1-11]]
^11^ Entonces ellos se dirigieron al ángel de Yahveh que estaba entre los mirtos y dijeron: «Hemos recorrido la tierra y hemos visto que toda la tierra vive en paz».

[[zechariah-1-12]]
^12^ Tomó la palabra el ángel de Yahveh y dijo: «Oh Yahveh Sebaot, ¿hasta cuándo seguirás sin apiadarte de Jerusalén y de las ciudades de Judá, contra las cuales estás irritado desde hace setenta años?»

[[zechariah-1-13]]
^13^ Yahveh respondió al ángel que hablaba conmigo palabras buenas, palabras de consuelo.

[[zechariah-1-14]]
^14^ Y el ángel que hablaba conmigo me dijo: «Clama y di: Así dice Yahveh Sebaot: Celoso estoy por Jerusalén y por Sión con gran celo,

[[zechariah-1-15]]
^15^ y con gran irritación irritado contra las naciones que se sienten seguras, y que, cuando yo estaba poco irritado, contribuyeron al mal.

[[zechariah-1-16]]
^16^ Por eso, así dice Yahveh: A Jerusalén me vuelvo con piedad: en ella será reedificada mi Casa - oráculo de Yahveh Sebaot - y el cordel será tendido sobre Jerusalén.

[[zechariah-1-17]]
^17^ Clama también y di: Así dice Yahveh Sebaot: Aún han de rebosar mis ciudades de bienes; aún consolará Yahveh a Sión y aún elegirá a Jerusalén».
[[zechariah-2]]
== Capítulo 2

[[zechariah-2-1]]
^1^ Alcé luego mis ojos y tuve una visión: Eran cuatro cuernos.

[[zechariah-2-2]]
^2^ Y dije al ángel que hablaba conmigo: «¿Qué son éstos?» Me dijo: «Son los cuernos que dispersaron a Judá (a Israel) y a Jerusalén».

[[zechariah-2-3]]
^3^ Yahveh me hizo ver después cuatro herreros.

[[zechariah-2-4]]
^4^ Y dije: «¿Qué vienen a hacer éstos?» El habló y dijo: «(Aquellos son los cuernos que dispersaron a Judá, hasta que nadie osó levantar cabeza.) Y éstos han venido a espantarlos (a abatir los cuernos de las naciones que alzaron el cuerno contra la tierra de Judá para dispersarla)».

[[zechariah-2-5]]
^5^ Alcé los ojos y tuve una visión: Era un hombre con una cuerda de medir en la mano.

[[zechariah-2-6]]
^6^ Le dije: «¿A dónde vas?» Me dijo: «A medir a Jerusalén, a ver cuánta es su anchura y cuánta su longitud».

[[zechariah-2-7]]
^7^ En esto, salió el ángel que hablaba conmigo, y otro ángel salió a su encuentro

[[zechariah-2-8]]
^8^ y le dijo: «Corre, habla a ese joven y dile: Como las ciudades abiertas será habitada Jerusalén, debido a la multitud de hombres y ganados que habrá dentro de ella.

[[zechariah-2-9]]
^9^ Y yo seré para ella - oráculo de Yahveh - muralla de fuego en torno, y dentro de ella seré gloria».

[[zechariah-2-10]]
^10^ ¡Hala, hala, huid del país del Norte - oráculo de Yahveh, - ya que a los cuatro vientos del cielo os esparcí yo! - oráculo de Yahveh -

[[zechariah-2-11]]
^11^ ¡Hala, sálvate, Sión, tú que moras en Babilonia!

[[zechariah-2-12]]
^12^ Pues así dice Yahveh Sebaot que tras la gloria me ha enviado a las naciones que os despojaron: «El que os toca a vosotros a la niña de mi ojo toca».

[[zechariah-2-13]]
^13^ He aquí que yo alzo mi mano contra ellas, y serán despojo de sus mismos esclavos. Sabréis así que Yahveh Sebaot me ha enviado.

[[zechariah-2-14]]
^14^ Grita de gozo y regocíjate, hija de Sión, pues he aquí que yo vengo a morar dentro de ti, oráculo de Yahveh.

[[zechariah-2-15]]
^15^ Muchas naciones se unirán a Yahveh aquel día: serán para mí un pueblo, y yo moraré en medio de ti. Sabrás así que Yahveh Sebaot me ha enviado a ti.

[[zechariah-2-16]]
^16^ Poseerá Yahveh a Judá, porción suya en la Tierra Santa, y elegirá de nuevo a Jerusalén.

[[zechariah-2-17]]
^17^ ¡Silencio, toda carne, delante de Yahveh, porque él se despierta de su santa Morada!
[[zechariah-3]]
== Capítulo 3

[[zechariah-3-1]]
^1^ Me hizo ver después al sumo sacerdote Josué, que estaba ante el ángel de Yahveh; a su derecha estaba el Satán para acusarle.

[[zechariah-3-2]]
^2^ Dijo el ángel de Yahveh al Satán: «¡Yahveh te reprima, Satán, reprímate Yahveh, el que ha elegido a Jerusalén! ¿No es éste un tizón sacado del fuego?»

[[zechariah-3-3]]
^3^ Estaba Josué vestido de ropas sucias, en pie delante del ángel.

[[zechariah-3-4]]
^4^ Tomó éste la palabra y habló así a los que estaban delante de él: «¡Quitadle esas ropas sucias y ponedle vestiduras de fiesta; le dijo: «Mira, yo he pasado por alto tu culpa».

[[zechariah-3-5]]
^5^ Y colocad en su cabeza una tiara limpia!» Se le vistió de vestiduras de fiesta y se le colocó en la cabeza la tiara limpia. El ángel de Yahveh que seguía en pie.

[[zechariah-3-6]]
^6^ Luego el ángel de Yahveh advirtió a Josué diciendo:

[[zechariah-3-7]]
^7^ «Así dice Yahveh Sebaot: Si andas por mis caminos y guardas mis prescripciones, tú gobernarás mi Casa, y tú mismo guardarás mis atrios: yo te daré plaza entre estos que están aquí».

[[zechariah-3-8]]
^8^ Escucha, pues, Josué, sumo sacerdote, tú y tus compañeros que se sientan en tu presencia - pues son hombres de presagio -: He aquí que yo voy a traer a mi siervo «Germen».

[[zechariah-3-9]]
^9^ Y he aquí la piedra que yo pongo delante de Josué; en esta única piedra hay siete ojos; yo mismo grabaré su inscripción - oráculo de Yahveh Sebaot - y quitaré la culpa de esta tierra en un solo día.

[[zechariah-3-10]]
^10^ Aquel día - oráculo de Yahveh Sebaot - os invitaréis unos a otros bajo la parra y bajo la higuera.
[[zechariah-4]]
== Capítulo 4

[[zechariah-4-1]]
^1^ Volvió el ángel que hablaba conmigo y me despertó como a un hombre que es despertado de su sueño.

[[zechariah-4-2]]
^2^ Y me dijo: «¿Qué ves?» Dije: «Veo un candelabro todo de oro, con una ampolla en su vértice: tiene siete lámparas y siete boquillas para las siete lámparas que lleva encima.

[[zechariah-4-3]]
^3^ Hay también dos olivos junto a él, uno a su derecha y el otro a su izquierda».

[[zechariah-4-4]]
^4^ Proseguí y dije al ángel que hablaba conmigo: «¿Qué es esto, señor mío?»

[[zechariah-4-5]]
^5^ Me respondió el ángel que hablaba conmigo y me dijo: «¿No sabes qué es esto?» Dije: «No, mi señor».

[[zechariah-4-6]]
^6^ Prosiguió él y me habló así: Esta es la palabra de Yahveh a Zorobabel. No por el valor ni por la fuerza, sino sólo por mi Espíritu - dice Yahveh Sebaot -.

[[zechariah-4-7]]
^7^ ¿Quién eres tú, gran monte? Ante Zorobabel serás una explanada, y él extraerá la piedra de remate, a los gritos de «¡Bravo, bravo por ella!».

[[zechariah-4-8]]
^8^ Me fue dirigida la palabra de Yahveh en estos términos:

[[zechariah-4-9]]
^9^ Las manos de Zorobabel echaron el cimiento a esta Casa y sus manos la acabarán; (sabréis así que Yahveh Sebaot me ha enviado a vosotros).

[[zechariah-4-10]]
^10^ ¿Quién menospreció el día de los modestos comienzos? ¡Se alegrará al ver la plomada en la mano de Zorobabel! «Esos siete son los ojos de Yahveh: ellos recorren toda la tierra».

[[zechariah-4-11]]
^11^ Entonces tomé la palabra y le dije: «¿Qué son esos dos olivos a derecha e izquierda del candelabro?»

[[zechariah-4-12]]
^12^ (Añadí de nuevo y le dije: «¿Qué son las dos ramas de olivo que por los dos tubos de oro vierten de sí aceite dorado?»)

[[zechariah-4-13]]
^13^ El me habló y dijo: «¿No sabes qué es esto?» Dije: «No, mi señor».

[[zechariah-4-14]]
^14^ Y él me dijo: «Estos son los dos Ungidos que están en pie junto al Señor de toda la tierra».
[[zechariah-5]]
== Capítulo 5

[[zechariah-5-1]]
^1^ Volví a alzar los ojos y tuve una visión: Era un rollo volando.

[[zechariah-5-2]]
^2^ Y me dijo el ángel: «¿Qué ves?» Respondí: «Veo un rollo volando, de veinte codos de largo y veinte de ancho».

[[zechariah-5-3]]
^3^ Me dijo: «Eso es la Maldición que sale sobre la haz de toda esta tierra. Pues todo ladrón será, según ella, echado de aquí, y todo el que jura será, según ella, echado de aquí.

[[zechariah-5-4]]
^4^ Yo la he hecho salir - oráculo de Yahveh Sebaot - para que entre en casa del ladrón y en casa del que jura por mi nombre en falso, para que se aloje en medio de su casa y la consuma, con su maderamen y sus piedras».

[[zechariah-5-5]]
^5^ Salió el ángel que hablaba conmigo y me dijo: «Alza ahora tus ojos y mira qué es eso que sale».

[[zechariah-5-6]]
^6^ Yo dije: «¿Qué es?» Dijo: «Es la medida que sale». Y añadió: «Esta es la culpa de ellos en todo el país».

[[zechariah-5-7]]
^7^ En esto, se levantó la tapa de plomo y había una Mujer sentada en medio de la medida.

[[zechariah-5-8]]
^8^ Dijo él: «Esta es la Maldad». La echó dentro de la medida y volvió a poner la tapa de plomo en su boca.

[[zechariah-5-9]]
^9^ Alcé luego los ojos y tuve una visión: Dos mujeres aparecieron, con viento en sus alas, porque tenían alas como de cigüeña. Y levantaron la medida entre la tierra y el cielo.

[[zechariah-5-10]]
^10^ Dije entonces al ángel que hablaba conmigo: «¿A dónde llevan ésas la medida?»

[[zechariah-5-11]]
^11^ Me respondió: «Van a edificarle una casa en el país de Senaar, y cuando esté a punto será colocada allí sobre su base».
[[zechariah-6]]
== Capítulo 6

[[zechariah-6-1]]
^1^ Alcé otra vez los ojos y tuve una visión: Eran cuatro carros que salían de entre dos montes; y los montes eran montes de bronce.

[[zechariah-6-2]]
^2^ En el primer carro había caballos rojos, en el segundo carro caballos negros,

[[zechariah-6-3]]
^3^ en el tercer carro caballos blancos, y en el cuarto carro caballos tordos.

[[zechariah-6-4]]
^4^ Tomé la palabra y dije al ángel que hablaba conmigo: «¿Qué son éstos, señor mío?»

[[zechariah-6-5]]
^5^ El ángel respondió y me dijo: «Son los cuatro vientos del cielo que salen después de presentarse ante el Señor de toda la tierra.

[[zechariah-6-6]]
^6^ Donde están los caballos negros, salen hacía el país del norte; los blancos salen detrás de ellos y los tordos salen hacía el país del sur».

[[zechariah-6-7]]
^7^ Briosos salían, impacientes por recorrer la tierra. Les dijo: «Id, recorred la tierra». Y recorrieron la tierra.

[[zechariah-6-8]]
^8^ Y a mí me gritó y me habló así: «Mira, los que salen hacia el país del norte van a aplacar mi espíritu en el país del norte».

[[zechariah-6-9]]
^9^ La palabra de Yahveh me fue dirigida en estos términos:

[[zechariah-6-10]]
^10^ «Haz una colecta entre los deportados: Jelday, Tobías y Yedaías; vienes aquel día y entras en la casa de Josías, hijo de Sefanías, a donde han llegado de Babilonia,

[[zechariah-6-11]]
^11^ tomas la plata y el oro, haces una corona, la pones en la cabeza del sumo sacerdote Josué, hijo de Yehosadaq,

[[zechariah-6-12]]
^12^ y le hablas de esta manera: Así dice Yahveh Sebaot: He aquí un hombre cuyo nombre es Germen: debajo de él habrá germinación (y él edificará el Templo de Yahveh).

[[zechariah-6-13]]
^13^ El edificará el Templo de Yahveh; él llevará las insignias reales, se sentará y dominará en su trono; habrá un sacerdote a su derecha, y consejo de paz habrá entre ellos dos.

[[zechariah-6-14]]
^14^ Será la corona para Jelday, Tobías y Yedaías, y para el hijo de Sefanías, un memorial de gracia en el Templo de Yahveh.

[[zechariah-6-15]]
^15^ Y los que están lejos vendrán y reedificarán el Templo de Yahveh. Sabréis entonces que Yahveh Sebaot me ha enviado a vosotros. Así será si de verdad escucháis la voz de Yahveh vuestro Dios».
[[zechariah-7]]
== Capítulo 7

[[zechariah-7-1]]
^1^ El año cuarto del rey Darío, la palabra de Yahveh fue dirigida a Zacarías, el día cuatro del noveno mes, el mes de Kisléu.

[[zechariah-7-2]]
^2^ Betel había enviado a Sar Eser y a Réguem Mélek, con su gente, a ablandar el rostro de Yahveh,

[[zechariah-7-3]]
^3^ y a decir a los sacerdotes de la Casa de Yahveh Sebaot y a los profetas: «¿Deberé llorar en el quinto mes haciendo abstinencia como lo he hecho durante tantos años?»

[[zechariah-7-4]]
^4^ Me fue dirigida la palabra de Yahveh en estos términos:

[[zechariah-7-5]]
^5^ Habla a todo el pueblo de la tierra y a los sacerdotes y di: «Cuando habéis ayunado y plañido, en el quinto y séptimo mes, y esto durante setenta años, ¿habéis ayunado de verdad por mí?

[[zechariah-7-6]]
^6^ Y cuando coméis y bebéis, ¿no sois vosotros los que coméis y bebéis?

[[zechariah-7-7]]
^7^ ¿No conocéis las palabras que Yahveh proclamó por ministerio de los antiguos profetas, cuando Jerusalén vivía en paz, con sus ciudades de alrededor, y estaban habitados el Négueb y la Tierra Baja?

[[zechariah-7-8]]
^8^ (La palabra de Yahveh fue dirigida a Zacarías en estos términos:

[[zechariah-7-9]]
^9^ Así dijo Yahveh Sebaot): Juicio fiel juzgad, y amor y compasión practicad cada cual con su hermano.

[[zechariah-7-10]]
^10^ No oprimáis a la viuda, al huérfano, al forastero, ni al pobre; y no maquinéis mal uno contra otro en vuestro corazón.

[[zechariah-7-11]]
^11^ Para ellos no quisieron hacer caso; hombro rebelde presentaron y endurecieron sus oídos para no escuchar;

[[zechariah-7-12]]
^12^ su corazón hicieron de diamante para no oír la Ley y las palabras que Yahveh Sebaot había dirigido por su espíritu, por ministerio de los antiguos profetas. Hubo entonces gran enojo de Yahveh Sebaot.

[[zechariah-7-13]]
^13^ Y sucedió que, como él había clamado y ellos no habían escuchado, así ellos clamaban y yo no les escuchaba, dice Yahveh Sebaot.

[[zechariah-7-14]]
^14^ Sino que los dispersé entre todas las naciones que no conocían, y la tierra quedó devastada detrás de ellos: ya nadie iba ni venía. Y así convirtieron una tierra de delicias en desolación».
[[zechariah-8]]
== Capítulo 8

[[zechariah-8-1]]
^1^ Fue dirigida la palabra de Yahveh en estos términos:

[[zechariah-8-2]]
^2^ Así dice Yahveh Sebaot: Con gran celo he celado a Sión, con gran ira la he celado.

[[zechariah-8-3]]
^3^ Así dice Yahveh: Me he vuelto a Sión, y en medio de Jerusalén habito. Jerusalén se llamará Ciudad-de-Fidelidad, y el monte de Yahveh Sebaot, Monte-de-Santidad.

[[zechariah-8-4]]
^4^ Así dice Yahveh Sebaot: Aún se sentarán viejos y viejas en las plazas de Jerusalén, cada cual con su bastón en la mano, por ser muchos sus días;

[[zechariah-8-5]]
^5^ las plazas de la ciudad se llenarán de muchachos y muchachas en sus plazas jugando.

[[zechariah-8-6]]
^6^ Así dice Yahveh Sebaot: Si ello parece imposible a los ojos del Resto de este pueblo, en aquellos días, ¿también a mis ojos va a ser imposible?, oráculo de Yahveh Sebaot.

[[zechariah-8-7]]
^7^ Así dice Yahveh Sebaot: He aquí que yo salvo a mi pueblo del país del oriente y del país donde se pone el sol;

[[zechariah-8-8]]
^8^ voy a traerlos para que moren en medio de Jerusalén. Y serán mi pueblo y yo seré su Dios con fidelidad y con justicia.

[[zechariah-8-9]]
^9^ Así dice Yahveh Sebaot: Reafírmense vuestras manos, vosotros que oís en estos días esas palabras de la boca de los profetas, desde el día en que se echaron los cimientos de la Casa de Yahveh Sebaot, para la reconstrucción del Templo.

[[zechariah-8-10]]
^10^ Porque hasta estos días no había paga para los hombres ni paga para el ganado; paz ninguna había, a causa del enemigo, para el que salía y entraba, y yo había dado rienda suelta a todos los hombres unos contra otros.

[[zechariah-8-11]]
^11^ Pero ahora ya no soy yo para el Resto de este pueblo como en días pasados, oráculo de Yahveh Sebaot.

[[zechariah-8-12]]
^12^ Porque hay simiente de paz: la vid dará su fruto, la tierra dará su producto y los cielos darán su rocío; yo daré en posesión al Resto de este pueblo todas estas cosas.

[[zechariah-8-13]]
^13^ Y sucederá que así como habéis sido maldición entre las naciones, casa de Judá y casa de Israel, así os salvaré yo, y seréis bendición; ¡no tengáis miedo, y que se reafirmen vuestras manos!

[[zechariah-8-14]]
^14^ Pues así dice Yahveh Sebaot: Como yo había decidido haceros mal, cuando me irritaron vuestros padres - dice Yahveh Sebaot - y no me arrepentí de ello,

[[zechariah-8-15]]
^15^ así en cambio he decidido en estos días hacer bien a Jerusalén y a la casa de Judá: ¡no temáis!

[[zechariah-8-16]]
^16^ He aquí las cosas que debéis hacer: Decid verdad unos a otros; juicio de paz juzgad en vuestras puertas;

[[zechariah-8-17]]
^17^ mal unos contra otros no meditéis en vuestro corazón, y juramento falso no améis, porque todas estas cosas las odio yo, oráculo de Yahveh.

[[zechariah-8-18]]
^18^ La palabra de Yahveh me fue dirigida en estos términos:

[[zechariah-8-19]]
^19^ «Así dice Yahveh Sebaot: El ayuno del cuarto mes, el ayuno del quinto, el ayuno del séptimo y el ayuno del décimo se convertirán para la casa de Judá en regocijo, alegría y faustas solemnidades. Amad, pues, la verdad y la paz».

[[zechariah-8-20]]
^20^ Así dice Yahveh Sebaot: Todavía habrá pueblos que vengan, y habitantes de grandes ciudades.

[[zechariah-8-21]]
^21^ Y los habitantes de una ciudad irán a la otra diciendo: «Ea, vamos a ablandar el rostro de Yahveh y a buscar a Yahveh Sebaot: ¡yo también voy!»

[[zechariah-8-22]]
^22^ Y vendrán pueblos numerosos y naciones poderosas a buscar a Yahveh Sebaot en Jerusalén, y a ablandar el rostro de Yahveh.

[[zechariah-8-23]]
^23^ Así dice Yahveh Sebaot: En aquellos días, diez hombres de todas las lenguas de las naciones asirán por la orla del manto a un judío diciendo: «Queremos ir con vosotros, porque hemos oído decir que Dios está con vosotros».
[[zechariah-9]]
== Capítulo 9

[[zechariah-9-1]]
^1^ Oráculo. La palabra de Yahveh, en el país de Jadrak y en Damasco, su reposo; porque de Yahveh es la fuente de Aram, como todas las tribus de Israel;

[[zechariah-9-2]]
^2^ y también Jamat que está en su frontera, (Tiro) y Sidón, la que es tan sabia.

[[zechariah-9-3]]
^3^ Se ha construido Tiro una fortaleza, ha amontonado plata como polvo y oro como barro de las calles.

[[zechariah-9-4]]
^4^ He aquí que el Señor va a apoderarse de ello: hundirá en el mar su poderío, y ella misma será devorada por el fuego.

[[zechariah-9-5]]
^5^ Ascalón lo verá y temerá, Gaza también, y se retorcerá de dolor y Ecrón, pues su esperanza ha fracasado; desaparecerá de Gaza el rey, Ascalón no será ya habitada,

[[zechariah-9-6]]
^6^ y un bastardo habitará en Asdod. Yo truncaré el orgullo de los filisteos;

[[zechariah-9-7]]
^7^ quitaré su sangre de su boca, y sus abominaciones de sus dientes. Quedará él también como resto para nuestro Dios, será como un familiar en Judá, y Ecrón será como el jebuseo.

[[zechariah-9-8]]
^8^ Yo acamparé junto a mi Casa como guardia contra quien va y quien viene; y no pasará más opresor sobre ellos, porque ahora miro yo con mis ojos.

[[zechariah-9-9]]
^9^ ¡Exulta sin freno, hija de Sión, grita de alegría, hija de Jerusalén! He aquí que viene a ti tu rey: justo él y victorioso, humilde y montado en un asno, en un pollino, cría de asna.

[[zechariah-9-10]]
^10^ El suprimirá los cuernos de Efraím y los caballos de Jerusalén; será suprimido el arco de combate, y él proclamará la paz a las naciones. Su dominio irá de mar a mar y desde el Río hasta los confines de la tierra.

[[zechariah-9-11]]
^11^ En cuanto a ti, por la sangre de tu alianza, yo soltaré a tus cautivos de la fosa en la que no hay agua.

[[zechariah-9-12]]
^12^ Volved a la fortaleza, cautivos de la esperanza; hoy mismo, yo lo anuncio, el doble te he de devolver.

[[zechariah-9-13]]
^13^ Porque he entesado para mí a Judá, el arco he cargado con Efraím. Voy a incitar a tus hijos, Sión, contra tus hijos, Yaván, y te haré como espada de un bravo.

[[zechariah-9-14]]
^14^ Yahveh aparecerá sobre ellos, y saldrá como relámpago su flecha; (el Señor) Yahveh tocará el cuerno y avanzará en los torbellinos del sur.

[[zechariah-9-15]]
^15^ Yahveh Sebaot los escudará; y devorarán y pisotearán las piedras de la honda, beberán la sangre como vino, y se llenarán como copa de aspersiones, como los cuernos del altar.

[[zechariah-9-16]]
^16^ Los salvará Yahveh su Dios el día aquel, como rebaño de su pueblo, porque serán piedras de diadema refulgentes sobre su suelo.

[[zechariah-9-17]]
^17^ ¡Qué espléndido será, qué hermoso! El trigo hará florecer a los mancebos y el mosto a las doncellas.
[[zechariah-10]]
== Capítulo 10

[[zechariah-10-1]]
^1^ Pedid a Yahveh la lluvia en tiempo de primavera. Yahveh, el que hace las nubes de tormenta, lluvia copiosa les dará, hierba en su campo a cada uno.

[[zechariah-10-2]]
^2^ Porque los terafim predicen falsedad y los adivinos ven mentira, porque sueños de ilusión predicen y con cosa vana quieren consolar, por eso emigran ellos como ovejas, abatidos porque no hay pastor.

[[zechariah-10-3]]
^3^ Contra los pastores arde mi cólera y a los machos cabríos visitaré. Cuando Yahveh Sebaot visite a su rebaño, la Casa de Judá, hará de ellos como su caballo de honor en el combate.

[[zechariah-10-4]]
^4^ De él saldrá el Angulo, de él la Clavija, de él el Arco de combate, de él todos los Caudillos. Juntos

[[zechariah-10-5]]
^5^ serán como bravos que pisarán el barro de las calles en el combate; combatirán, porque Yahveh está con ellos, y serán confundidos los que montan caballos.

[[zechariah-10-6]]
^6^ Yo haré fuerte la casa de Judá y victoriosa la casa de José; los recobraré porque me apiado de ellos, y serán como si yo no los hubiera desechado, pues yo soy Yahveh su Dios, y los atenderé.

[[zechariah-10-7]]
^7^ Como bravos serán los de Efraím, estará alegre su corazón como de vino; sus hijos lo verán y se alegrarán, exultará en Yahveh su corazón.

[[zechariah-10-8]]
^8^ Yo les silbaré para reunirlos, pues los he rescatado, y serán tan numerosos como eran.

[[zechariah-10-9]]
^9^ Yo los sembré entre los pueblos, mas en lejanas tierras se acordarán de mí, criarán a sus hijos y retornarán.

[[zechariah-10-10]]
^10^ Los haré volver del país de Egipto, de Asur los recogeré, y los conduciré al país de Galaad y al Líbano, donde no habrá bastante para ellos.

[[zechariah-10-11]]
^11^ Atravesarán el mar de la angustia, (él herirá en el mar las ondas), y quedarán secas todas las honduras del Nilo. Será abatido el orgullo de Asur, y el cetro de Egipto llegará a su fin.

[[zechariah-10-12]]
^12^ Yo los haré fuertes en Yahveh, y en su Nombre marcharán, oráculo de Yahveh.
[[zechariah-11]]
== Capítulo 11

[[zechariah-11-1]]
^1^ Abre tus puertas, Líbano, y el fuego devore tus cedros.

[[zechariah-11-2]]
^2^ Gime, ciprés, porque ha caído el cedro, porque los majestuosos han sido arrasados. Gemid, encinas de Basán, porque ha sido abatida la selva impenetrable.

[[zechariah-11-3]]
^3^ Se oye gemido de pastores, porque ha sido arrasado su esplendor, se oye rugido de leones, porque ha sido arrasada la gloria del Jordán.

[[zechariah-11-4]]
^4^ Así dice Yahveh mi Dios: Apacienta las ovejas de matadero,

[[zechariah-11-5]]
^5^ esas que sus compradores matan impunemente, mientras sus vendedores dicen: «¡Bendito sea Yahveh; ya soy rico!», y a las que no perdonan los pastores.

[[zechariah-11-6]]
^6^ Pues yo no perdonaré más a los habitantes de esta tierra, oráculo de Yahveh; mas he aquí que voy a entregar a los hombres, a cada uno en manos de su vecino y en manos de su rey; ellos aplastarán la tierra y yo no los libraré de sus manos.

[[zechariah-11-7]]
^7^ Apacenté, pues, las ovejas de matadero destinadas a los tratantes de ovejas, y me procuré dos cayados: a uno lo llamé «Gracia» y al otro «Vínculo». Me puse a apacentar las ovejas,

[[zechariah-11-8]]
^8^ y me deshice de los tres pastores en un mes. Pero mi alma se impacientó con ellos y su alma también se hastió de mí.

[[zechariah-11-9]]
^9^ Entonces dije: «¡No os apacentaré más; la que tenga que morir, que muera, la que tenga que desaparecer, que desaparezca, y las que queden, que se coman unas a otras!»

[[zechariah-11-10]]
^10^ Tomé luego mi cayado «Gracia» y lo partí, para romper la alianza que Yahveh había concluido con todos los pueblos.

[[zechariah-11-11]]
^11^ Quedó roto aquel día, y los tratantes de ovejas que me observaban supieron que era una palabra de Yahveh.

[[zechariah-11-12]]
^12^ Yo les dije: «Si os parece bien, dadme mi jornal; sino, dejadlo». Ellos pesaron mi jornal: treinta siclos de plata.

[[zechariah-11-13]]
^13^ Yahveh me dijo: «¡Echalo al tesoro, esa lindeza de precio en que me han apreciado!» Tomé, pues, los treinta siclos de plata y los eché en la Casa de Yahveh, en el tesoro.

[[zechariah-11-14]]
^14^ Después partí mi segundo cayado «Vínculo», para romper la fraternidad entre Judá e Israel.

[[zechariah-11-15]]
^15^ Yahveh me dijo entonces: «Toma todavía el hato de un pastor necio.

[[zechariah-11-16]]
^16^ Pues he aquí que yo voy a suscitar en esta tierra un pastor que no hará caso de la oveja perdida, ni buscará a la extraviada, ni curará a la herida, ni se ocupará de la sana, sino que comerá la carne de la cebada, y hasta las uñas les arrancará.

[[zechariah-11-17]]
^17^ ¡Ay del pastor inútil que abandona las ovejas! ¡Espada sobre su brazo y sobre su ojo derecho; que su brazo se seque del todo, y del todo se oscurezca su ojo!»
[[zechariah-12]]
== Capítulo 12

[[zechariah-12-1]]
^1^ Oráculo. Palabra de Yahveh sobre Israel. Oráculo de Yahveh, el que despliega los cielos, funda la tierra y forma el espíritu del hombre en su interior.

[[zechariah-12-2]]
^2^ He aquí que yo hago de Jerusalén una copa de vértigo para todos los pueblos del contorno (durante el asedio contra Jerusalén). (*Zacarías 12:2-b) (y también sobre Judá).

[[zechariah-12-3]]
^3^ Aquel día haré yo de Jerusalén una piedra de levantamiento para todos los pueblos: todos los que la levanten se desgarrarán completamente. Y contra ella se congregarán todas las naciones de la tierra.

[[zechariah-12-4]]
^4^ Aquel día - oráculo de Yahveh - heriré de aturdimiento a todo caballo, y a su caballero, de locura. Y a todos los pueblos heriré de ceguera. (Mas sobre la casa de Judá abriré mis ojos.)

[[zechariah-12-5]]
^5^ Entonces dirán en su corazón los jefes de Judá: «La fuerza de los habitantes de Jerusalén está en Yahveh Sebaot su Dios».

[[zechariah-12-6]]
^6^ Aquel día haré de los jefes de Judá como un brasero con fuego de leña, como una antorcha con fuego de gavillas; y devorarán a derecha e izquierda a todos los pueblos del contorno, mientras que Jerusalén será de nuevo habitada en su lugar.

[[zechariah-12-7]]
^7^ Salvará Yahveh en primer lugar a las tiendas de Judá, para que el prestigio de la casa de David y el prestigio de los habitantes de Jerusalén no se crezca sobre Judá.

[[zechariah-12-8]]
^8^ Aquel día protegerá Yahveh a los habitantes de Jerusalén: el más flaco entre ellos será aquel día como David, y la casa de David será como Dios, como un ángel de Yahveh, al frente de ellos.

[[zechariah-12-9]]
^9^ Aquel día me dispondré a destruir a todas las naciones que vengan contra Jerusalén;

[[zechariah-12-10]]
^10^ derramaré sobre la casa de David y sobre los habitantes de Jerusalén un espíritu de gracia y de oración; y mirarán hacia mí. En cuanto a aquél a quien traspasaron, harán lamentación por él como lamentación por hijo único, y le llorarán amargamente como se llora amargamente a un primogénito.

[[zechariah-12-11]]
^11^ Aquel día será grande la lamentación en Jerusalén, como la lamentación de Hadad Rimmón en la llanura de Meguiddó.

[[zechariah-12-12]]
^12^ Y se lamentará el país, cada familia aparte: la familia de la casa de David aparte y sus mujeres aparte; la familia de la casa de Natán aparte y sus mujeres aparte;

[[zechariah-12-13]]
^13^ la familia de la casa de Leví aparte; y sus mujeres aparte; la familia de la casa de Semeí aparte y sus mujeres aparte;

[[zechariah-12-14]]
^14^ todas las demás familias, cada familia aparte y sus mujeres aparte.
[[zechariah-13]]
== Capítulo 13

[[zechariah-13-1]]
^1^ Aquel día habrá una fuente abierta para la casa de David y para los habitantes de Jerusalén, para lavar el pecado y la impureza.

[[zechariah-13-2]]
^2^ Aquel día - oráculo de Yahveh Sebaot - extirparé yo de esta tierra los nombres de los ídolos y no se volverá a mentarlos; igualmente a los profetas y el espíritu de impureza los quitaré de esta tierra.

[[zechariah-13-3]]
^3^ Y, si todavía alguien se pone a profetizar, le dirán su padre y su madre que le engendraron: «¡No has de vivir tú, que dices mentiras en nombre de Yahveh!» Y su padre y su madre que le engendraron le traspasarán mientras esté profetizando.

[[zechariah-13-4]]
^4^ Aquel día se avergonzarán los profetas, cada cual de su visión, cuando profeticen, y no se vestirán el manto de pelo con ánimos de mentir,

[[zechariah-13-5]]
^5^ sino que dirán cada uno: «¡Yo no soy profeta; soy un campesino, pues la tierra es mi ocupación desde mi juventud!»

[[zechariah-13-6]]
^6^ Y si alguien le dice: «¿Y esas heridas que hay entre tus manos?», responderá: «Las he recibido en casa de mis amigos».

[[zechariah-13-7]]
^7^ ¡Despierta, espada, contra mi pastor, y contra el hombre de mi compañía!, oráculo de Yahveh Sebaot. ¡Hiere al pastor, que se dispersen las ovejas, y yo tornaré mi mano contra los pequeños!

[[zechariah-13-8]]
^8^ Y sucederá en toda esta tierra - oráculo de Yahveh - que dos tercios serán en ella exterminados (perecerán) y el otro tercio quedará en ella.

[[zechariah-13-9]]
^9^ Yo meteré en el fuego este tercio: los purgaré como se purga la plata y los probaré como se prueba el oro. Invocará él mi nombre y yo le responderé; diré: «¡El es mi pueblo!» y él dirá: «¡Yahveh es mi Dios!»
[[zechariah-14]]
== Capítulo 14

[[zechariah-14-1]]
^1^ He aquí que viene el Día de Yahveh en que serán repartidos tus despojos en medio de ti.

[[zechariah-14-2]]
^2^ Yo reuniré a todas las naciones en batalla contra Jerusalén. Será tomada la ciudad, las casas serán saqueadas y violadas las mujeres. La mitad de la ciudad partirá al cautiverio, pero el Resto del pueblo no será extirpado de la ciudad.

[[zechariah-14-3]]
^3^ Saldrá entonces Yahveh y combatirá contra esas naciones como el día en que él combate, el día de la batalla.

[[zechariah-14-4]]
^4^ Se plantarán sus pies aquel día en el monte de los Olivos que está enfrente de Jerusalén, al oriente, y el monte de los Olivos se hendirá por el medio de oriente a occidente haciéndose un enorme valle: la mitad del monte se retirará al norte y la otra mitad al sur.

[[zechariah-14-5]]
^5^ Y huiréis al valle de mis montes, porque el valle de los montes llegará hasta Yasol; huiréis como huisteis a causa del terremoto en los días de Ozías, rey de Judá. Y vendrá Yahveh mi Dios y todos los santos con él.

[[zechariah-14-6]]
^6^ Aquel día no habrá ya luz, sino frío y hielo.

[[zechariah-14-7]]
^7^ Un día único será - conocido sólo de Yahveh -: no habrá día y luego noche, sino que a la hora de la tarde habrá luz.

[[zechariah-14-8]]
^8^ Sucederá aquel día que saldrán de Jerusalén aguas vivas, mitad hacia el mar oriental, mitad hacia el mar occidental: las habrá tanto en verano como en invierno.

[[zechariah-14-9]]
^9^ Y será Yahveh rey sobre toda la tierra: ¡el día aquel será único Yahveh y único su nombre!

[[zechariah-14-10]]
^10^ Toda esta tierra se tornará llanura, desde Gueba hasta Rimmón, al sur de Jerusalén. Y ésta, encumbrada, será habitada en su lugar, desde la Puerta de Benjamín hasta el emplazamiento de la antigua Puerta, es decir, hasta la Puerta de los Angulos, y desde la torre de Jananel hasta los Lagares del rey.

[[zechariah-14-11]]
^11^ Se habitará en ella y no habrá más anatema: ¡Jerusalén será habitada en seguridad!

[[zechariah-14-12]]
^12^ Y ésta será la plaga con que herirá Yahveh a todos los pueblos que hayan hecho la guerra a Jerusalén: pudrirá su carne estando ellos todavía en pie, sus ojos se pudrirán en sus cuencas, y su lengua se pudrirá en su boca.

[[zechariah-14-13]]
^13^ Y cundirá aquel día entre ellos un inmenso pánico de Yahveh: agarrará cada uno la mano de su prójimo y levantarán la mano unos contra otros.

[[zechariah-14-14]]
^14^ También Judá combatirá en Jerusalén. Y serán reunidas las riquezas de todas las naciones de alrededor: oro, plata y vestidos en cantidad inmensa.

[[zechariah-14-15]]
^15^ Semejante será la plaga de los caballos, mulos, camellos y asnos, y de todo el ganado que haya en aquellos campamentos: ¡una plaga como ésa!

[[zechariah-14-16]]
^16^ Y todos los supervivientes de todas las naciones que hayan venido contra Jerusalén subirán de año en año a postrarse ante el Rey Yahveh Sebaot y a celebrar la fiesta de las Tiendas.

[[zechariah-14-17]]
^17^ Y para aquella familia de la tierra que no suba a Jerusalén a postrarse ante el Rey Yahveh Sebaot no habrá lluvia.

[[zechariah-14-18]]
^18^ Si la familia de Egipto no sube ni viene, caerá sobre ella la plaga con que Yahveh herirá a las naciones que no suban a celebrar la fiesta de las Tiendas.

[[zechariah-14-19]]
^19^ Tal será el castigo de Egipto y el castigo de todas las naciones que no suban a celebrar la fiesta de las Tiendas.

[[zechariah-14-20]]
^20^ Aquel día se hallará en los cascabeles de los caballos: «Consagrado a Yahveh», y serán las ollas en la Casa de Yahveh como copas de aspersión delante del altar.

[[zechariah-14-21]]
^21^ Y toda olla, en Jerusalén y Judá, estará consagrada a Yahveh Sebaot; todos los que quieran sacrificar vendrán a tomar de ellas, y en ellas cocerán; y no habrá más comerciante en la Casa de Yahveh Sebaot el día aquel.
