[[matthew]]
= Mateo

[[matthew-1]]
== Capítulo 1

[[matthew-1-1]]
^1^ Libro de la generación de Jesucristo, hijo de David, hijo de Abraham:

[[matthew-1-2]]
^2^ Abraham engendró a Isaac, Isaac engendró a Jacob, Jacob engendró a Judá y a sus hermanos,

[[matthew-1-3]]
^3^ Judá engrendró, de Tamar, a Fares y a Zara, Fares engendró a Esrom, Esrom engendró a Aram,

[[matthew-1-4]]
^4^ Aram engendró a Aminadab, Aminadab engrendró a Naassón, Naassón engendró a Salmón,

[[matthew-1-5]]
^5^ Salmón engendró, de Rajab, a Booz, Booz engendró, de Rut, a Obed, Obed engendró a Jesé,

[[matthew-1-6]]
^6^ Jesé engendró al rey David. David engendró, de la que fue mujer de Urías, a Salomón,

[[matthew-1-7]]
^7^ Salomón engendró a Roboam, Roboam engendró a Abiá, Abiá engendró a Asaf,

[[matthew-1-8]]
^8^ Asaf engendró a Josafat, Josafat engendró a Joram, Joram engendró a Ozías,

[[matthew-1-9]]
^9^ Ozías engendró a Joatam, Joatam engendró a Acaz, Acaz engendró a Ezequías,

[[matthew-1-10]]
^10^ Ezequías engendró a Manasés, Manasés engendró a Amón, Amón engendró a Josías,

[[matthew-1-11]]
^11^ Josías engendró a Jeconías y a sus hermanos, cuando la deportación a Babilonia.

[[matthew-1-12]]
^12^ Después de la deportación a Babilonia, Jeconías engendró a Salatiel, Salatiel engendró a Zorobabel,

[[matthew-1-13]]
^13^ Zorobabel engendró a Abiud, Abiud engendró a Eliakim, Eliakim engendró a Azor,

[[matthew-1-14]]
^14^ Azor engendró a Sadoq, Sadoq engendró a Aquim, Aquim engendró a Eliud,

[[matthew-1-15]]
^15^ Eliud engendró a Eleazar, Eleazar engendró a Mattán, Mattán engendró a Jacob,

[[matthew-1-16]]
^16^ y Jacob engendró a José, el esposo de María, de la que nació Jesús, llamado Cristo.

[[matthew-1-17]]
^17^ Así que el total de las generaciones son: desde Abraham hasta David, catorce generaciones; desde David hasta la deportación a Babilonia, catorce generaciones; desde la deportación a Babilonia hasta Cristo, catorce generaciones.

[[matthew-1-18]]
^18^ La generación de Jesucristo fue de esta manera: Su madre, María, estaba desposada con José y, antes de empezar a estar juntos ellos, se encontró encinta por obra del Espíritu Santo.

[[matthew-1-19]]
^19^ Su marido José, como era justo y no quería ponerla en evidencia, resolvió repudiarla en secreto.

[[matthew-1-20]]
^20^ Así lo tenía planeado, cuando el Angel del Señor se le apareció en sueños y le dijo: «José, hijo de David, no temas tomar contigo a María tu mujer porque lo engendrado en ella es del Espíritu Santo.

[[matthew-1-21]]
^21^ Dará a luz un hijo, y tú le pondrás por nombre Jesús, porque él salvará a su pueblo de sus pecados».

[[matthew-1-22]]
^22^ Todo esto sucedió para que se cumpliese el oráculo del Señor por medio del profeta:

[[matthew-1-23]]
^23^ Ved que la virgen concebirá y dará a luz un hijo, y le pondrán por nombre Emmanuel, que traducido significa: «Dios con nosotros».

[[matthew-1-24]]
^24^ Despertado José del sueño, hizo como el Angel del Señor le había mandado, y tomó consigo a su mujer.

[[matthew-1-25]]
^25^ Y no la conocía hasta que ella dio a luz un hijo, y le puso por nombre Jesús.

[[matthew-2]]
== Capítulo 2

[[matthew-2-1]]
^1^ Nacido Jesús en Belén de Judea, en tiempo del rey Herodes, unos magos que venían del Oriente se presentaron en Jerusalén,

[[matthew-2-2]]
^2^ diciendo: «¿Dónde está el Rey de los judíos que ha nacido? Pues vimos su estrella en el Oriente y hemos venido a adorarle».

[[matthew-2-3]]
^3^ En oyéndolo, el rey Herodes se sobresaltó y con él toda Jerusalén.

[[matthew-2-4]]
^4^ Convocó a todos los sumos sacerdotes y escribas del pueblo, y por ellos se estuvo informando del lugar donde había de nacer el Cristo.

[[matthew-2-5]]
^5^ Ellos le dijeron: «En Belén de Judea, porque así está escrito por medio del profeta:

[[matthew-2-6]]
^6^ Y tú, Belén, tierra de Judá, no eres, no, la menor entre los principales clanes de Judá; porque de ti saldrá un caudillo que apacentará a mi pueblo Israel».

[[matthew-2-7]]
^7^ Entonces Herodes llamó aparte a los magos y por sus datos precisó el tiempo de la aparición de la estrella.

[[matthew-2-8]]
^8^ Después, enviándolos a Belén, les dijo: «Id e indagad cuidadosamente sobre ese niño; y cuando le encontréis, comunicádmelo, para ir también yo a adorarle».

[[matthew-2-9]]
^9^ Ellos, después de oír al rey, se pusieron en camino, y he aquí que la estrella que habían visto en el Oriente iba delante de ellos, hasta que llegó y se detuvo encima del lugar donde estaba el niño.

[[matthew-2-10]]
^10^ Al ver la estrella se llenaron de inmensa alegría.

[[matthew-2-11]]
^11^ Entraron en la casa; vieron al niño con María su madre y, postrándose, le adoraron; abrieron luego sus cofres y le ofrecieron dones de oro, incienso y mirra.

[[matthew-2-12]]
^12^ Y, avisados en sueños que no volvieran donde Herodes, se retiraron a su país por otro camino.

[[matthew-2-13]]
^13^ Después que ellos se retiraron, el Angel del Señor se apareció en sueños a José y le dijo: «Levántate, toma contigo al niño y a su madre y huye a Egipto; y estate allí hasta que yo te diga. Porque Herodes va a buscar al niño para matarle».

[[matthew-2-14]]
^14^ El se levantó, tomó de noche al niño y a su madre, y se retiró a Egipto;

[[matthew-2-15]]
^15^ y estuvo allí hasta la muerte de Herodes; para que se cumpliera el oráculo del Señor por medio del profeta: De Egipto llamé a mi hijo.

[[matthew-2-16]]
^16^ Entonces Herodes, al ver que había sido burlado por los magos, se enfureció terriblemente y envió a matar a todos los niños de Belén y de toda su comarca, de dos años para abajo, según el tiempo que había precisado por los magos.

[[matthew-2-17]]
^17^ Entonces se cumplió el oráculo del profeta Jeremías:

[[matthew-2-18]]
^18^ Un clamor se ha oído en Ramá, mucho llanto y lamento: es Raquel que llora a sus hijos, y no quiere consolarse, porque ya no existen.

[[matthew-2-19]]
^19^ Muerto Herodes, el Angel del Señor se apareció en sueños a José en Egipto y le dijo:

[[matthew-2-20]]
^20^ «Levántate, toma contigo al niño y a su madre, y ponte en camino de la tierra de Israel; pues ya han muerto los que buscaban la vida del niño».

[[matthew-2-21]]
^21^ El se levantó, tomó consigo al niño y a su madre, y entró en tierra de Israel.

[[matthew-2-22]]
^22^ Pero al enterarse de que Arquelao reinaba en Judea en lugar de su padre Herodes, tuvo miedo de ir allí; y avisado en sueños, se retiró a la región de Galilea,

[[matthew-2-23]]
^23^ y fue a vivir en una ciudad llamada Nazaret; para que se cumpliese el oráculo de los profetas: Será llamado Nazoreo.

[[matthew-3]]
== Capítulo 3

[[matthew-3-1]]
^1^ Por aquellos días aparece Juan el Bautista, proclamando en el desierto de Judea:

[[matthew-3-2]]
^2^ «Convertíos porque ha llegado el Reino de los Cielos».

[[matthew-3-3]]
^3^ Este es aquél de quien habla el profeta Isaías cuando dice: Voz del que clama en el desierto: Preparad el camino del Señor, enderezad sus sendas.

[[matthew-3-4]]
^4^ Tenía Juan su vestido hecho de pelos de camello, con un cinturón de cuero a sus lomos, y su comida eran langostas y miel silvestre.

[[matthew-3-5]]
^5^ Acudía entonces a él Jerusalén, toda Judea y toda la región del Jordán,

[[matthew-3-6]]
^6^ y eran bautizados por él en el río Jordán, confesando sus pecados.

[[matthew-3-7]]
^7^ Pero viendo él venir muchos fariseos y saduceos al bautismo, les dijo: «Raza de víboras, ¿quién os ha enseñado a huir de la ira inminente?

[[matthew-3-8]]
^8^ Dad, pues, fruto digno de conversión,

[[matthew-3-9]]
^9^ y no creáis que basta con decir en vuestro interior: “Tenemos por padre a Abraham”; porque os digo que puede Dios de estas piedras dar hijos a Abraham.

[[matthew-3-10]]
^10^ Ya está el hacha puesta a la raíz de los árboles; y todo árbol que no dé buen fruto será cortado y arrojado al fuego.

[[matthew-3-11]]
^11^ Yo os bautizo en agua para conversión; pero aquel que viene detrás de mí es más fuerte que yo, y no soy digno de llevarle las sandalias. El os bautizará en Espíritu Santo y fuego.

[[matthew-3-12]]
^12^ En su mano tiene el bieldo y va a limpiar su era: recogerá su trigo en el granero, pero la paja la quemará con fuego que no se apaga».

[[matthew-3-13]]
^13^ Entonces aparece Jesús, que viene de Galilea al Jordán donde Juan, para ser bautizado por él.

[[matthew-3-14]]
^14^ Pero Juan trataba de impedírselo diciendo: «Soy yo el que necesita ser bautizado por ti, ¿y tú vienes a mí?»

[[matthew-3-15]]
^15^ Jesús le respondió: «Déjame ahora, pues conviene que así cumplamos toda justicia». Entonces le dejó.

[[matthew-3-16]]
^16^ Bautizado Jesús, salió luego del agua; y en esto se abrieron los cielos y vio al Espíritu de Dios que bajaba en forma de paloma y venía sobre él.

[[matthew-3-17]]
^17^ Y una voz que salía de los cielos decía: «Este es mi Hijo amado, en quien me complazco».

[[matthew-4]]
== Capítulo 4

[[matthew-4-1]]
^1^ Entonces Jesús fue llevado por el Espíritu al desierto para ser tentado por el diablo.

[[matthew-4-2]]
^2^ Y después de hacer un ayuno de cuarenta días y cuarenta noches, al fin sintió hambre.

[[matthew-4-3]]
^3^ Y acercándose el tentador, le dijo: «Si eres Hijo de Dios, di que estas piedras se conviertan en panes».

[[matthew-4-4]]
^4^ Mas él respondió: «Está escrito: No sólo de pan vive el hombre, sino de toda palabra que sale de la boca de Dios».

[[matthew-4-5]]
^5^ Entonces el diablo le lleva consigo a la Ciudad Santa, le pone sobre el alero del Templo,

[[matthew-4-6]]
^6^ y le dice: «Si eres Hijo de Dios, tírate abajo, porque está escrito: A sus ángeles te encomendará, y en sus manos te llevarán, para que no tropiece tu pie en piedra alguna».

[[matthew-4-7]]
^7^ Jesús le dijo: «También está escrito: No tentarás al Señor tu Dios».

[[matthew-4-8]]
^8^ Todavía le lleva consigo el diablo a un monte muy alto, le muestra todos los reinos del mundo y su gloria,

[[matthew-4-9]]
^9^ y le dice: «Todo esto te daré si postrándote me adoras».

[[matthew-4-10]]
^10^ Dícele entonces Jesús: «Apártate, Satanás, porque está escrito: Al Señor tu Dios adorarás, y sólo a él darás culto».

[[matthew-4-11]]
^11^ Entonces el diablo le deja. Y he aquí que se acercaron unos ángeles y le servían.

[[matthew-4-12]]
^12^ Cuando oyó que Juan había sido entregado, se retiró a Galilea.

[[matthew-4-13]]
^13^ Y dejando Nazará, vino a residir en Cafarnaúm junto al mar, en el término de Zabulón y Neftalí;

[[matthew-4-14]]
^14^ para que se cumpliera el oráculo del profeta Isaías:

[[matthew-4-15]]
^15^ ¡Tierra de Zabulón, tierra de Neftalí, camino del mar, allende el Jordán, Galilea de los gentiles!

[[matthew-4-16]]
^16^ El pueblo que habitaba en tinieblas ha visto una gran luz; a los que habitaban en paraje de sombras de muerte una luz les ha amanecido.

[[matthew-4-17]]
^17^ Desde entonces comenzó Jesús a predicar y decir: «Convertíos, porque el Reino de los Cielos ha llegado».

[[matthew-4-18]]
^18^ Caminando por la ribera del mar de Galilea vio a dos hermanos, Simón, llamado Pedro, y su hermano Andrés, echando la red en el mar, pues eran pescadores,

[[matthew-4-19]]
^19^ y les dice: «Venid conmigo, y os haré pescadores de hombres».

[[matthew-4-20]]
^20^ Y ellos al instante, dejando las redes, le siguieron.

[[matthew-4-21]]
^21^ Caminando adelante, vio a otros dos hermanos, Santiago el de Zebedeo y su hermano Juan, que estaban en la barca con su padre Zebedeo arreglando sus redes; y los llamó.

[[matthew-4-22]]
^22^ Y ellos al instante, dejando la barca y a su padre, le siguieron.

[[matthew-4-23]]
^23^ Recorría Jesús toda Galilea, enseñando en sus sinagogas, proclamando la Buena Nueva del Reino y curando toda enfermedad y toda dolencia en el pueblo.

[[matthew-4-24]]
^24^ Su fama llegó a toda Siria; y le trajeron todos los que se encontraban mal con enfermedades y sufrimientos diversos, endemoniados, lunáticos y paralíticos, y los curó.

[[matthew-4-25]]
^25^ Y le siguió una gran muchedumbre de Galilea, Decápolis, Jerusalén y Judea, y del otro lado del Jordán.

[[matthew-5]]
== Capítulo 5

[[matthew-5-1]]
^1^ Viendo la muchedumbre, subió al monte, se sentó, y sus discípulos se le acercaron.

[[matthew-5-2]]
^2^ Y tomando la palabra, les enseñaba diciendo:

[[matthew-5-3]]
^3^ «Bienaventurados los pobres de espíritu, porque de ellos es el Reino de los Cielos.

[[matthew-5-4]]
^4^ Bienaventurados los mansos, porque ellos posseerán en herencia la tierra.

[[matthew-5-5]]
^5^ Bienaventurados los que lloran, porque ellos serán consolados.

[[matthew-5-6]]
^6^ Bienaventurados los que tienen hambre y sed de la justicia, porque ellos serán saciados.

[[matthew-5-7]]
^7^ Bienaventurados los misericordiosos, porque ellos alcanzarán misericordia.

[[matthew-5-8]]
^8^ Bienaventurados los limpios de corazón, porque ellos verán a Dios.

[[matthew-5-9]]
^9^ Bienaventurados los que trabajan por la paz, porque ellos serán llamados hijos de Dios.

[[matthew-5-10]]
^10^ Bienaventurados los perseguidos por causa de la justicia, porque de ellos es el Reino de los Cielos.

[[matthew-5-11]]
^11^ Bienaventurados seréis cuando os injurien, y os persigan y digan con mentira toda clase de mal contra vosotros por mi causa.

[[matthew-5-12]]
^12^ Alegraos y regocijaos, porque vuestra recompensa será grande en los cielos; pues de la misma manera persiguieron a los profetas anteriores a vosotros.

[[matthew-5-13]]
^13^ «Vosotros sois la sal de la tierra. Mas si la sal se desvirtúa, ¿con qué se la salará? Ya no sirve para nada más que para ser tirada afuera y pisoteada por los hombres.

[[matthew-5-14]]
^14^ «Vosotros sois la luz del mundo. No puede ocultarse una ciudad situada en la cima de un monte.

[[matthew-5-15]]
^15^ Ni tampoco se enciende una lámpara y la ponen debajo del celemín, sino sobre el candelero, para que alumbre a todos los que están en la casa.

[[matthew-5-16]]
^16^ Brille así vuestra luz delante de los hombres, para que vean vuestras buenas obras y glorifiquen a vuestro Padre que está en los cielos.

[[matthew-5-17]]
^17^ «No penséis que he venido a abolir la Ley y los Profetas. No he venido a abolir, sino a dar cumplimiento.

[[matthew-5-18]]
^18^ Sí, os lo aseguro: el cielo y la tierra pasarán antes que pase una i o una tilde de la Ley sin que todo suceda.

[[matthew-5-19]]
^19^ Por tanto, el que traspase uno de estos mandamientos más pequeños y así lo enseñe a los hombres, será el más pequeño en el Reino de los Cielos; en cambio, el que los observe y los enseñe, ése será grande en el Reino de los Cielos.

[[matthew-5-20]]
^20^ «Porque os digo que, si vuestra justicia no es mayor que la de los escribas y fariseos, no entraréis en el Reino de los Cielos.

[[matthew-5-21]]
^21^ «Habéis oído que se dijo a los antepasados: No matarás; y aquel que mate será reo ante el tribunal.

[[matthew-5-22]]
^22^ Pues yo os digo: Todo aquel que se encolerice contra su hermano, será reo ante el tribunal; pero el que llame a su hermano “imbécil”, será reo ante el Sanedrín; y el que le llame “renegado”, será reo de la gehenna de fuego.

[[matthew-5-23]]
^23^ Si, pues, al presentar tu ofrenda en el altar te acuerdas entonces de que un hermano tuyo tiene algo contra ti,

[[matthew-5-24]]
^24^ deja tu ofrenda allí, delante del altar, y vete primero a reconciliarte con tu hermano; luego vuelves y presentas tu ofrenda.

[[matthew-5-25]]
^25^ Ponte enseguida a buenas con tu adversario mientras vas con él por el camino; no sea que tu adversario te entregue al juez y el juez al guardia, y te metan en la cárcel.

[[matthew-5-26]]
^26^ Yo te aseguro: no saldrás de allí hasta que no hayas pagado el último céntimo.

[[matthew-5-27]]
^27^ «Habéis oído que se dijo: No cometerás adulterio.

[[matthew-5-28]]
^28^ Pues yo os digo: Todo el que mira a una mujer deseándola, ya cometió adulterio con ella en su corazón.

[[matthew-5-29]]
^29^ Si, pues, tu ojo derecho te es ocasión de pecado, sácatelo y arrójalo de ti; más te conviene que se pierda uno de tus miembros, que no que todo tu cuerpo sea arrojado a la gehenna.

[[matthew-5-30]]
^30^ Y si tu mano derecha te es ocasión de pecado, córtatela y arrójala de ti; más te conviene que se pierda uno de tus miembros, que no que todo tu cuerpo vaya a la gehenna.

[[matthew-5-31]]
^31^ «También se dijo: El que repudie a su mujer, que le dé acta de divorcio.

[[matthew-5-32]]
^32^ Pues yo os digo: Todo el que repudia a su mujer, excepto el caso de fornicación, la hace ser adúltera; y el que se case con una repudiada, comete adulterio.

[[matthew-5-33]]
^33^ «Habéis oído también que se dijo a los antepasados: No perjurarás, sino que cumplirás al Señor tus juramentos.

[[matthew-5-34]]
^34^ Pues yo digo que no juréis en modo alguno: ni por el Cielo =, porque es el trono de Dios,

[[matthew-5-35]]
^35^ ni por la Tierra, porque es el escabel de sus pies; ni por Jerusalén, porque es la ciudad del gran rey.

[[matthew-5-36]]
^36^ Ni tampoco jures por tu cabeza, porque ni a uno solo de tus cabellos puedes hacerlo blanco o negro.

[[matthew-5-37]]
^37^ Sea vuestro lenguaje: “Sí, sí”; “no, no”: que lo que pasa de aquí viene del Maligno.

[[matthew-5-38]]
^38^ «Habéis oído que se dijo: Ojo por ojo y diente por diente.

[[matthew-5-39]]
^39^ Pues yo os digo: no resistáis al mal; antes bien, al que te abofetee en la mejilla derecha ofrécele también la otra:

[[matthew-5-40]]
^40^ al que quiera pleitear contigo para quitarte la túnica déjale también el manto;

[[matthew-5-41]]
^41^ y al que te obligue a andar una milla vete con él dos.

[[matthew-5-42]]
^42^ A quien te pida da, y al que desee que le prestes algo no le vuelvas la espalda.

[[matthew-5-43]]
^43^ «Habéis oído que se dijo: Amarás a tu prójimo y odiarás a tu enemigo.

[[matthew-5-44]]
^44^ Pues yo os digo: Amad a vuestros enemigos y rogad por los que os persigan,

[[matthew-5-45]]
^45^ para que seáis hijos de vuestro Padre celestial, que hace salir su sol sobre malos y buenos, y llover sobre justos e injustos.

[[matthew-5-46]]
^46^ Porque si amáis a los que os aman, ¿qué recompensa vais a tener? ¿No hacen eso mismo también los publicanos?

[[matthew-5-47]]
^47^ Y si no saludáis más que a vuestros hermanos, ¿qué hacéis de particular? ¿No hacen eso mismo también los gentiles?

[[matthew-5-48]]
^48^ Vosotros, pues, sed perfectos como es perfecto vuestro Padre celestial.

[[matthew-6]]
== Capítulo 6

[[matthew-6-1]]
^1^ «Cuidad de no practicar vuestra justicia delante de los hombres para ser vistos por ellos; de lo contrario no tendréis recompensa de vuestro Padre celestial.

[[matthew-6-2]]
^2^ Por tanto, cuando hagas limosna, no lo vayas trompeteando por delante como hacen los hipócritas en las sinagogas y por las calles, con el fin de ser honrados por los hombres; en verdad os digo que ya reciben su paga.

[[matthew-6-3]]
^3^ Tú, en cambio, cuando hagas limosna, que no sepa tu mano izquierda lo que hace tu derecha;

[[matthew-6-4]]
^4^ así tu limosna quedará en secreto; y tu Padre, que ve en lo secreto, te recompensará.

[[matthew-6-5]]
^5^ «Y cuando oréis, no seáis como los hipócritas, que gustan de orar en las sinagogas y en las esquinas de las plazas bien plantados para ser vistos de los hombres; en verdad os digo que ya reciben su paga.

[[matthew-6-6]]
^6^ Tú, en cambio, cuando vayas a orar, entra en tu aposento y, después de cerrar la puerta, ora a tu Padre, que está allí, en lo secreto; y tu Padre, que ve en lo secreto, te recompensará.

[[matthew-6-7]]
^7^ Y al orar, no charléis mucho, como los gentiles, que se figuran que por su palabrería van a ser escuchados.

[[matthew-6-8]]
^8^ No seáis como ellos, porque vuestro Padre sabe lo que necesitáis antes de pedírselo.

[[matthew-6-9]]
^9^ «Vosotros, pues, orad así: Padre nuestro que estás en los cielos, santificado sea tu Nombre;

[[matthew-6-10]]
^10^ venga tu Reino; hágase tu Voluntad así en la tierra como en el cielo.

[[matthew-6-11]]
^11^ Nuestro pan cotidiano dánosle hoy;

[[matthew-6-12]]
^12^ y perdónanos nuestras deudas, así como nosotros hemos perdonado a nuestros deudores;

[[matthew-6-13]]
^13^ y no nos dejes caer en tentación, mas líbranos del mal.

[[matthew-6-14]]
^14^ «Que si vosotros perdonáis a los hombres sus ofensas, os perdonará también a vosotros vuestro Padre celestial;

[[matthew-6-15]]
^15^ pero si no perdonáis a los hombres, tampoco vuestro Padre perdonará vuestras ofensas.

[[matthew-6-16]]
^16^ «Cuando ayunéis, no pongáis cara triste, como los hipócritas, que desfiguran su rostro para que los hombres vean que ayunan; en verdad os digo que ya reciben su paga.

[[matthew-6-17]]
^17^ Tú, en cambio, cuando ayunes, perfuma tu cabeza y lava tu rostro,

[[matthew-6-18]]
^18^ para que tu ayuno sea visto, no por los hombres, sino por tu Padre que está allí, en lo secreto; y tu Padre, que ve en lo secreto, te recompensará.

[[matthew-6-19]]
^19^ «No os amontonéis tesoros en la tierra, donde hay polilla y herrumbre que corroen, y ladrones que socavan y roban.

[[matthew-6-20]]
^20^ Amontonaos más bien tesoros en el cielo, donde no hay polilla ni herrumbre que corroan, ni ladrones que socaven y roben.

[[matthew-6-21]]
^21^ Porque donde esté tu tesoro, allí estará también tu corazón.

[[matthew-6-22]]
^22^ «La lámpara del cuerpo es el ojo. Si tu ojo está sano, todo tu cuerpo estará luminoso;

[[matthew-6-23]]
^23^ pero si tu ojo está malo, todo tu cuerpo estará a oscuras. Y, si la luz que hay en ti es oscuridad, ¡qué oscuridad habrá!

[[matthew-6-24]]
^24^ Nadie puede servir a dos señores; porque aborrecerá a uno y amará al otro; o bien se entregará a uno y despreciará al otro. No podéis servir a Dios y al Dinero.

[[matthew-6-25]]
^25^ «Por eso os digo: No andéis preocupados por vuestra vida, qué comeréis, ni por vuestro cuerpo, con qué os vestiréis. ¿No vale más la vida que el alimento, y el cuerpo más que el vestido?

[[matthew-6-26]]
^26^ Mirad las aves del cielo: no siembran, ni cosechan, ni recogen en graneros; y vuestro Padre celestial las alimenta. ¿No valéis vosotros más que ellas?

[[matthew-6-27]]
^27^ Por lo demás, ¿quién de vosotros puede, por más que se preocupe, añadir un solo codo a la medida de su vida?

[[matthew-6-28]]
^28^ Y del vestido, ¿por qué preocuparos? Observad los lirios del campo, cómo crecen; no se fatigan, ni hilan.

[[matthew-6-29]]
^29^ Pero yo os digo que ni Salomón, en toda su gloria, se vistió como uno de ellos.

[[matthew-6-30]]
^30^ Pues si a la hierba del campo, que hoy es y mañana se echa al horno, Dios así la viste, ¿no lo hará mucho más con vosotros, hombres de poca fe?

[[matthew-6-31]]
^31^ No andéis, pues, preocupados diciendo: ¿Qué vamos a comer?, ¿qué vamos a beber?, ¿con qué vamos a vestirnos?

[[matthew-6-32]]
^32^ Que por todas esas cosas se afanan los gentiles; pues ya sabe vuestro Padre celestial que tenéis necesidad de todo eso.

[[matthew-6-33]]
^33^ Buscad primero su Reino y su justicia, y todas esas cosas se os darán por añadidura.

[[matthew-6-34]]
^34^ Así que no os preocupéis del mañana: el mañana se preocupará de sí mismo. Cada día tiene bastante con su propio mal.

[[matthew-7]]
== Capítulo 7

[[matthew-7-1]]
^1^ «No juzguéis, para que no seáis juzgados.

[[matthew-7-2]]
^2^ Porque con el juicio con que juzguéis seréis juzgados, y con la medida con que midáis se os medirá.

[[matthew-7-3]]
^3^ ¿Cómo es que miras la brizna que hay en el ojo de tu hermano, y no reparas en la viga que hay en tu ojo?

[[matthew-7-4]]
^4^ ¿O cómo vas a decir a tu hermano: “Deja que te saque la brizna del ojo”, teniendo la viga en el tuyo?

[[matthew-7-5]]
^5^ Hipócrita, saca primero la viga de tu ojo, y entonces podrás ver para sacar la brizna del ojo de tu hermano.

[[matthew-7-6]]
^6^ «No deis a los perros lo que es santo, ni echéis vuestras perlas delante de los puercos, no sea que las pisoteen con sus patas, y después, volviéndose, os despedacen.

[[matthew-7-7]]
^7^ «Pedid y se os dará; buscad y hallaréis; llamad y se os abrirá.

[[matthew-7-8]]
^8^ Porque todo el que pide recibe; el que busca, halla; y al llama, se le abrirá.

[[matthew-7-9]]
^9^ ¿O hay acaso alguno entre vosotros que al hijo que le pide pan le dé una piedra;

[[matthew-7-10]]
^10^ o si le pide un pez, le dé una culebra?

[[matthew-7-11]]
^11^ Si, pues, vosotros, siendo malos, sabéis dar cosas buenas a vuestros hijos, ¡cuánto más vuestro Padre que está en los cielos dará cosas buenas a los que se las pidan!

[[matthew-7-12]]
^12^ «Por tanto, todo cuanto queráis que os hagan los hombres, hacédselo también vosotros a ellos; porque ésta es la Ley y los Profetas.

[[matthew-7-13]]
^13^ «Entrad por la entrada estrecha; porque ancha es la entrada y espacioso el camino que lleva a la perdición, y son muchos los que entran por ella;

[[matthew-7-14]]
^14^ mas ¡qué estrecha la entrada y qué angosto el camino que lleva a la Vida!; y poco son los que lo encuentran.

[[matthew-7-15]]
^15^ «Guardaos de los falsos profetas, que vienen a vosotros con disfraces de ovejas, pero por dentro son lobos rapaces.

[[matthew-7-16]]
^16^ Por sus frutos los conoceréis. ¿Acaso se recogen uvas de los espinos o higos de los abrojos?

[[matthew-7-17]]
^17^ Así, todo árbol bueno da frutos buenos, pero el árbol malo da frutos malos.

[[matthew-7-18]]
^18^ Un árbol bueno no puede producir frutos malos, ni un árbol malo producir frutos buenos.

[[matthew-7-19]]
^19^ Todo árbol que no da buen fruto, es cortado y arrojado al fuego.

[[matthew-7-20]]
^20^ Así que por sus frutos los reconoceréis.

[[matthew-7-21]]
^21^ «No todo el que me diga: “Señor, Señor, entrará en el Reino de los Cielos, sino el que haga la voluntad de mi Padre celestial.

[[matthew-7-22]]
^22^ Muchos me dirán aquel Día: “Señor, Señor, ¿no profetizamos en tu nombre, y en tu nombre expulsamos demonios, y en tu nombre hicimos muchos milagros?”

[[matthew-7-23]]
^23^ Y entonces les declararé: “¡Jamás os conocí; apartaos de mí, agentes de iniquidad!”

[[matthew-7-24]]
^24^ «Así pues, todo el que oiga estas palabras mías y las ponga en práctica, será como el hombre prudente que edificó su casa sobre roca:

[[matthew-7-25]]
^25^ cayó la lluvia, vinieron los torrentes, soplaron los vientos, y embistieron contra aquella casa; pero ella no cayó, porque estaba cimentada sobre roca.

[[matthew-7-26]]
^26^ Y todo el que oiga estas palabras mías y no las ponga en práctica, será como el hombre insensato que edificó su casa sobre arena:

[[matthew-7-27]]
^27^ cayó la lluvia, vinieron los torrentes, soplaron los vientos, irrumpieron contra aquella casa y cayó, y fue grande su ruina».

[[matthew-7-28]]
^28^ Y sucedió que cuando acabó Jesús estos discursos, la gente quedaba asombrada de su doctrina;

[[matthew-7-29]]
^29^ porque les enseñaba como quien tiene autoridad, y no como sus escribas.

[[matthew-8]]
== Capítulo 8

[[matthew-8-1]]
^1^ Cuando bajó del monte, fue siguiéndole una gran muchedumbre.

[[matthew-8-2]]
^2^ En esto, un leproso se acercó y se postró ante él, diciendo: «Señor, si quieres puedes limpiarme».

[[matthew-8-3]]
^3^ El extendió la mano, le tocó y dijo: «Quiero, queda limpio». Y al instante quedó limpio de su lepra.

[[matthew-8-4]]
^4^ Y Jesús le dice: «Mira, no se los digas a nadie, sino vete, muéstrate al sacerdote y presenta la ofrenda que prescribió Moisés, para que les sirva de testimonio.

[[matthew-8-5]]
^5^ Al entrar en Cafarnaúm, se le acercó un centurión y le rogó

[[matthew-8-6]]
^6^ diciendo: «Señor, mi criado yace en casa paralítico con terribles sufrimientos».

[[matthew-8-7]]
^7^ Dícele Jesús: «Yo iré a curarle».

[[matthew-8-8]]
^8^ Replicó el centurión: «Señor, no soy digno de que entres bajo mi techo; basta que lo digas de palabra y mi criado quedará sano.

[[matthew-8-9]]
^9^ Porque también yo, que soy un subalterno, tengo soldados a mis órdenes, y digo a éste: “Vete”, y va; y a otro: “Ven”, y viene; y a mi siervo: “Haz esto”, y lo hace».

[[matthew-8-10]]
^10^ Al oír esto Jesús quedó admirado y dijo a los que le seguían: «Os aseguro que en Israel no he encontrado en nadie una fe tan grande.

[[matthew-8-11]]
^11^ Y os digo que vendrán muchos de oriente y occidente y se pondrán a la mesa con Abraham, Isaac y Jacob en el reino de los Cielos,

[[matthew-8-12]]
^12^ mientras que los hijos del Reino serán echados a las tinieblas de fuera; allí será el llanto y el rechinar de dientes».

[[matthew-8-13]]
^13^ Y dijo Jesús al centurión: «Anda; que te suceda como has creído». Y en aquella hora sanó el criado.

[[matthew-8-14]]
^14^ Al llegar Jesús a casa de Pedro, vio a la suegra de éste en cama, con fiebre.

[[matthew-8-15]]
^15^ Le tocó la mano y la fiebre la dejó; y se levantó y se puso a servirle.

[[matthew-8-16]]
^16^ Al atardecer, le trajeron muchos endemoniados; él expulsó a los espíritus con una palabra, y curó a todos los enfermos,

[[matthew-8-17]]
^17^ para que se cumpliera el oráculo del profeta Isaías: El tomó nuestras flaquezas y cargó con nuestras enfermedades.

[[matthew-8-18]]
^18^ Viéndose Jesús rodeado de la muchedumbre, mandó pasar a la otra orilla.

[[matthew-8-19]]
^19^ Y un escriba se acercó y le dijo: «Maestro, te seguiré adondequiera que vayas».

[[matthew-8-20]]
^20^ Dícele Jesús: «Las zorras tienen guaridas, y las aves del cielo nidos; pero el Hijo del hombre no tiene donde reclinar la cabeza».

[[matthew-8-21]]
^21^ Otro de los discípulos le dijo: «Señor, déjame ir primero a enterrar a mi padre».

[[matthew-8-22]]
^22^ Dícele Jesús: «Sígueme, y deja que los muertos entierren a sus muertos».

[[matthew-8-23]]
^23^ Subió a la barca y sus discípulos le siguieron.

[[matthew-8-24]]
^24^ De pronto se levantó en el mar una tempestad tan grande que la barca quedaba tapada por las olas; pero él estaba dormido.

[[matthew-8-25]]
^25^ Acercándose ellos le despertaron diciendo: «¡Señor, sálvanos, que perecemos!»

[[matthew-8-26]]
^26^ Díceles: «¿Por qué tenéis miedo, hombres de poca fe?» Entonces se levantó, increpó a los vientos y al mar, y sobrevino una gran bonanza.

[[matthew-8-27]]
^27^ Y aquellos hombres, maravillados, decían: «¿Quién es éste, que hasta los vientos y el mar le obedecen?»

[[matthew-8-28]]
^28^ Al llegar a la otra orilla, a la región de los gadarenos, vinieron a su encuentro dos endemoniados que salían de los sepulcros, y tan furiosos que nadie era capaz de pasar por aquel camino.

[[matthew-8-29]]
^29^ Y se pusieron a gritar: «¿Qué tenemos nosotros contigo, Hijo de Dios? ¿Has venido aquí para atormentarnos antes de tiempo?»

[[matthew-8-30]]
^30^ Había allí a cierta distancia una gran piara de puercos paciendo.

[[matthew-8-31]]
^31^ Y le suplicaban los demonios: «Si nos echas, mándanos a esa piara de puercos».

[[matthew-8-32]]
^32^ El les dijo: «Id». Saliendo ellos, se fueron a los puercos, y de pronto toda la piara se arrojó al mar precipicio abajo, y perecieron en las aguas.

[[matthew-8-33]]
^33^ Los porqueros huyeron, y al llegar a la ciudad lo contaron todo y también lo de los endemoniados.

[[matthew-8-34]]
^34^ Y he aquí que toda la ciudad salió al encuentro de Jesús y, en viéndole, le rogaron que se retirase de su término.

[[matthew-9]]
== Capítulo 9

[[matthew-9-1]]
^1^ Subiendo a la barca, pasó a la otra orilla y vino a su ciudad.

[[matthew-9-2]]
^2^ En esto le trajeron un paralítico postrado en una camilla. Viendo Jesús la fe de ellos, dijo al paralítico: «¡ Animo!, hijo, tus pecados te son perdonados».

[[matthew-9-3]]
^3^ Pero he aquí que algunos escribas dijeron para sí: «Este está blasfemando».

[[matthew-9-4]]
^4^ Jesús, conociendo sus pensamientos, dijo: «¿Por qué pensáis mal en vuestros corazones? ¿Qué es más fácil, decir: “Tus pecados te son perdonados”, o decir:

[[matthew-9-5]]
^5^ “Levántate y anda”?

[[matthew-9-6]]
^6^ Pues para que sepáis que el Hijo del hombre tiene en la tierra poder de perdonar pecados - dice entonces al paralítico -: “Levántate, toma tu camilla y vete a tu casa”».

[[matthew-9-7]]
^7^ El se levantó y se fue a su casa.

[[matthew-9-8]]
^8^ Y al ver esto, la gente temió y glorificó a Dios, que había dado tal poder a los hombres.

[[matthew-9-9]]
^9^ Cuando se iba de allí, al pasar vio Jesús a un hombre llamado Mateo, sentado en el despacho de impuestos, y le dice: «Sígueme». El se levantó y le siguió.

[[matthew-9-10]]
^10^ Y sucedió que estando él a la mesa en casa de Mateo, vinieron muchos publicanos y pecadores, y estaban a la mesa con Jesús y sus discípulos.

[[matthew-9-11]]
^11^ Al verlo los fariseos decían a los discípulos: «¿Por qué come vuestro maestro con los publicanos y pecadores?»

[[matthew-9-12]]
^12^ Mas él, al oírlo, dijo: «No necesitan médico los que están fuertes sino los que están mal.

[[matthew-9-13]]
^13^ Id, pues, a aprender qué significa aquello de: Misericordia quiero, que no sacrificio. Porque no he venido a llamar a justos, sino a pecadores».

[[matthew-9-14]]
^14^ Entonces se le acercan los discípulos de Juan y le dicen: «¿Por qué nosotros y los fariseos ayunamos, y tus discípulos no ayunan?»

[[matthew-9-15]]
^15^ Jesús les dijo: «Pueden acaso los invitados a la boda ponerse tristes mientras el novio está con ellos? Días vendrán en que les será arrebatado el novio; entonces ayunarán.

[[matthew-9-16]]
^16^ Nadie echa un remiendo de paño sin tundir en un vestido viejo, porque lo añadido tira del vestido, y se produce un desgarrón peor.

[[matthew-9-17]]
^17^ Ni tampoco se echa vino nuevo en pellejos viejos; pues de otro modo, los pellejos revientan, el vino se derrama, y los pellejos se echan a perder; sino que el vino nuevo se echa en pellejos nuevos, y así ambos se conservan».

[[matthew-9-18]]
^18^ Así les estaba hablando, cuando se acercó un magistrado y se postró ante él diciendo: «Mi hija acaba de morir, pero ven, impón tu mano sobre ella y vivirá».

[[matthew-9-19]]
^19^ Jesús se levantó y le siguió junto con sus discípulos.

[[matthew-9-20]]
^20^ En esto, una mujer que padecía flujo de sangre desde hacía doce años se acercó por detrás y tocó la orla de su manto.

[[matthew-9-21]]
^21^ Pues se decía para sí: «Con sólo tocar su manto, me salvaré».

[[matthew-9-22]]
^22^ Jesús se volvió, y al verla le dijo: «¡Animo!, hija, tu fe te ha salvado». Y se salvó la mujer desde aquel momento.

[[matthew-9-23]]
^23^ Al llegar Jesús a casa del magistrado y ver a los flautistas y la gente alborotando,

[[matthew-9-24]]
^24^ decía: «¡Retiraos! La muchacha no ha muerto; está dormida». Y se burlaban de él.

[[matthew-9-25]]
^25^ Mas, echada fuera la gente, entró él, la tomó de la mano, y la muchacha se levantó.

[[matthew-9-26]]
^26^ Y la noticia del suceso se divulgó por toda aquella comarca.

[[matthew-9-27]]
^27^ Cuando Jesús se iba de allí, al pasar le siguieron dos ciegos gritando: «¡Ten piedad de nosotros, Hijo de David!»

[[matthew-9-28]]
^28^ Y al llegar a casa, se le acercaron los ciegos, y Jesús les dice: «¿Creéis que puedo hacer eso?» Dícenle: «Sí, Señor».

[[matthew-9-29]]
^29^ Entonces les tocó los ojos diciendo: «Hágase en vosotros según vuestra fe».

[[matthew-9-30]]
^30^ Y se abrieron sus ojos. Jesús les ordenó severamente: «¡Mirad que nadie lo sepa!»

[[matthew-9-31]]
^31^ Pero ellos, en cuanto salieron, divulgaron su fama por toda aquella comarca.

[[matthew-9-32]]
^32^ Salían ellos todavía, cuando le presentaron un mudo endemoniado.

[[matthew-9-33]]
^33^ Y expulsado el demonio, rompió a hablar el mudo. Y la gente, admirada, decía: «Jamás se vio cosa igual en Israel».

[[matthew-9-34]]
^34^ Pero los fariseos decían: «Por el Príncipe de los demonios expulsa a los demonios».

[[matthew-9-35]]
^35^ Jesús recorría todas las ciudades y aldeas, enseñando en sus sinagogas, proclamando la Buena Nueva del Reino y sanando todo enfermedad y toda dolencia.

[[matthew-9-36]]
^36^ Y al ver a la muchedumbre, sintió compasión de ella, porque estaban vejados y abatidos como ovejas que no tienen pastor.

[[matthew-9-37]]
^37^ Entonces dice a sus discípulos: «La mies es mucha y los obreros pocos.

[[matthew-9-38]]
^38^ Rogad, pues, al Dueño de la mies que envíe obreros a su mies».

[[matthew-10]]
== Capítulo 10

[[matthew-10-1]]
^1^ Y llamando a sus doce discípulos, les dio poder sobre los espíritus inmundos para expulsarlos, y para curar toda enfermedad y toda dolencia.

[[matthew-10-2]]
^2^ Los nombres de los doce Apóstoles son éstos: primero Simón, llamado Pedro, y su hermano Andrés; Santiago el de Zebedeo y su hermano Juan;

[[matthew-10-3]]
^3^ Felipe y Bartolomé; Tomás y Mateo el publicano; Santiago el de Alfeo y Tadeo;

[[matthew-10-4]]
^4^ Simón el Cananeo y Judas el Iscariote, el mismo que le entregó.

[[matthew-10-5]]
^5^ A estos doce envió Jesús, después de darles estas instrucciones: «No toméis camino de gentiles ni entréis en ciudad de samaritanos;

[[matthew-10-6]]
^6^ dirigíos más bien a las ovejas perdidas de la casa de Israel.

[[matthew-10-7]]
^7^ Id proclamando que el Reino de los Cielos está cerca.

[[matthew-10-8]]
^8^ Curad enfermos, resucitad muertos, purificad leprosos, expulsad demonios. Gratis lo recibisteis; dadlo gratis.

[[matthew-10-9]]
^9^ No os procuréis oro, ni plata, ni calderilla en vuestras fajas;

[[matthew-10-10]]
^10^ ni alforja para el camino, ni dos túnicas, ni sandalias, ni bastón; porque el obrero merece su sustento.

[[matthew-10-11]]
^11^ «En la ciudad o pueblo en que entréis, informaos de quién hay en él digno, y quedaos allí hasta que salgáis.

[[matthew-10-12]]
^12^ Al entrar en la casa, saludadla.

[[matthew-10-13]]
^13^ Si la casa es digna, llegue a ella vuestra paz; mas si no es digna, vuestra paz se vuelva a vosotros.

[[matthew-10-14]]
^14^ Y si no se os recibe ni se escuchan vuestras palabras, salid de la casa o de la ciudad aquella sacudiendo el polvo de vuestros pies.

[[matthew-10-15]]
^15^ Yo os aseguro: el día del Juicio habrá menos rigor para la tierra de Sodoma y Gomorra que para aquella ciudad.

[[matthew-10-16]]
^16^ «Mirad que yo os envío como ovejas en medio de lobos. Sed, pues, prudentes como las serpientes, y sencillos como las palomas.

[[matthew-10-17]]
^17^ Guardaos de los hombres, porque os entregarán a los tribunales y os azotarán en sus sinagogas;

[[matthew-10-18]]
^18^ y por mi causa seréis llevados ante gobernadores y reyes, para que deis testimonio ante ellos y ante los gentiles.

[[matthew-10-19]]
^19^ Mas cuando os entreguen, no os preocupéis de cómo o qué vais a hablar. Lo que tengáis que hablar se os comunicará en aquel momento.

[[matthew-10-20]]
^20^ Porque no seréis vosotros los que hablaréis, sino el Espíritu de vuestro Padre el que hablará en vosotros.

[[matthew-10-21]]
^21^ «Entregará a la muerte hermano a hermano y padre a hijo; se levantarán hijos contra padres y los matarán.

[[matthew-10-22]]
^22^ Y seréis odiados de todos por causa de mi nombre; pero el que persevere hasta el fin, ése se salvará.

[[matthew-10-23]]
^23^ «Cuando os persigan en una ciudad huid a otra, y si también en ésta os persiguen, marchaos a otra. Yo os aseguro: no acabaréis de recorrer las ciudades de Israel antes que venga el Hijo del hombre.

[[matthew-10-24]]
^24^ «No está el discípulo por encima del maestro, ni el siervo por encima de su amo.

[[matthew-10-25]]
^25^ Ya le basta al discípulo ser como su maestro, y al siervo como su amo. Si al dueño de la casa le han llamado Beelzebul, ¡cuánto más a sus domésticos!

[[matthew-10-26]]
^26^ «No les tengáis miedo. Pues no hay nada encubierto que no haya de ser descubierto, ni oculto que no haya de saberse.

[[matthew-10-27]]
^27^ Lo que yo os digo en la oscuridad, decidlo vosotros a la luz; y lo que oís al oído, proclamadlo desde los terrados.

[[matthew-10-28]]
^28^ «Y no temáis a los que matan el cuerpo, pero no pueden matar el alma; temed más bien a Aquel que puede llevar a la perdición alma y cuerpo en la gehenna.

[[matthew-10-29]]
^29^ ¿No se venden dos pajarillos por un as? Pues bien, ni uno de ellos caerá en tierra sin el consentimiento de vuestro Padre.

[[matthew-10-30]]
^30^ En cuanto a vosotros, hasta los cabellos de vuestra cabeza están todos contados.

[[matthew-10-31]]
^31^ No temáis, pues; vosotros valéis más que muchos pajarillos.

[[matthew-10-32]]
^32^ «Por todo aquel que se declare por mí ante los hombres, yo también me declararé por él ante mi Padre que está en los cielos;

[[matthew-10-33]]
^33^ pero a quien me niegue ante los hombres, le negaré yo también ante mi Padre que está en los cielos.

[[matthew-10-34]]
^34^ «No penséis que he venido a traer paz a la tierra. No he venido a traer paz, sino espada.

[[matthew-10-35]]
^35^ Sí, he venido a enfrentar al hombre con su padre, a la hija con su madre, a la nuera con su suegra;

[[matthew-10-36]]
^36^ y enemigos de cada cual serán los que conviven con él.

[[matthew-10-37]]
^37^ «El que ama a su padre o a su madre más que a mí, no es digno de mí; el que ama a su hijo o a su hija más que a mí, no es digno de mí.

[[matthew-10-38]]
^38^ El que no toma su cruz y me sigue detrás no es digno de mí.

[[matthew-10-39]]
^39^ El que encuentre su vida, la perderá; y el que pierda su vida por mí, la encontrará.

[[matthew-10-40]]
^40^ «Quien a vosotros recibe, a mí me recibe, y quien me recibe a mí, recibe a Aquel que me ha enviado.

[[matthew-10-41]]
^41^ «Quien reciba a un profeta por ser profeta, recompensa de profeta recibirá, y quien reciba a un justo por ser justo, recompensa de justo recibirá.

[[matthew-10-42]]
^42^ «Y todo aquel que dé de beber tan sólo un vaso de agua fresca a uno de estos pequeños, por ser discípulo, os aseguro que no perderá su recompensa».

[[matthew-11]]
== Capítulo 11

[[matthew-11-1]]
^1^ Y sucedió que, cuando acabó Jesús de dar instrucciones a sus doce discípulos, partió de allí para enseñar y predicar en sus ciudades.

[[matthew-11-2]]
^2^ Juan, que en la cárcel había oído hablar de las obras de Cristo, envió a sus discípulos a decirle:

[[matthew-11-3]]
^3^ «¿Eres tú el que ha de venir, o debemos esperar a otro?»

[[matthew-11-4]]
^4^ Jesús les respondió: «Id y contad a Juan lo que oís y veis:

[[matthew-11-5]]
^5^ los ciegos ven y los cojos andan, los leprosos quedan limpios y los sordos oyen, los muertos resucitan y se anuncia a los pobres la Buena Nueva;

[[matthew-11-6]]
^6^ ¡y dichoso aquel que no halle escándalo en mí!»

[[matthew-11-7]]
^7^ Cuando éstos se marchaban, se puso Jesús a hablar de Juan a la gente: «¿Qué salisteis a ver en el desierto? ¿Una caña agitada por el viento?

[[matthew-11-8]]
^8^ ¿Qué salisteis a ver, si no? ¿Un hombre elegantemente vestido? ¡No! Los que visten con elegancia están en los palacios de los reyes.

[[matthew-11-9]]
^9^ Entonces ¿a qué salisteis? ¿A ver un profeta? Sí, os digo, y más que un profeta.

[[matthew-11-10]]
^10^ Este es de quien está escrito: He aquí que yo envío mi mensajero delante de ti, que preparará por delante tu camino.

[[matthew-11-11]]
^11^ «En verdad os digo que no ha surgido entre los nacidos de mujer uno mayor que Juan el Bautista; sin embargo, el más pequeño en el Reino de los Cielos es mayor que él.

[[matthew-11-12]]
^12^ Desde los días de Juan el Bautista hasta ahora, el Reino de los Cielos sufre violencia, y los violentos lo arrebatan.

[[matthew-11-13]]
^13^ Pues todos los profetas, lo mismo que la Ley, hasta Juan profetizaron.

[[matthew-11-14]]
^14^ Y, si queréis admitirlo, él es Elías, el que iba a venir.

[[matthew-11-15]]
^15^ El que tenga oídos, que oiga.

[[matthew-11-16]]
^16^ «¿Pero, con quién compararé a esta generación? Se parece a los chiquillos que, sentados en las plazas, se gritan unos a otros diciendo:

[[matthew-11-17]]
^17^ “Os hemos tocado la flauta, y no habéis bailado, os hemos entonado endechas, y no os habéis lamentado.”

[[matthew-11-18]]
^18^ Porque vino Juan, que ni comía ni bebía, y dicen: “Demonio tiene.”

[[matthew-11-19]]
^19^ Vino el Hijo del hombre, que come y bebe, y dicen: “Ahí tenéis un comilón y un borracho, amigo de publicanos y pecadores.” Y la Sabiduría se ha acreditado por sus obras».

[[matthew-11-20]]
^20^ Entonces se puso a maldecir a las ciudades en las que se habían realizado la mayoría de sus milagros, porque no se habían convertido:

[[matthew-11-21]]
^21^ «¡Ay de ti, Corazín! ¡Ay de ti, Betsaida! Porque si en Tiro y en Sidón se hubieran hecho los milagros que se han hecho en vosotras, tiempo ha que en sayal y ceniza se habrían convertido.

[[matthew-11-22]]
^22^ Por eso os digo que el día del Juicio habrá menos rigor para Tiro y Sidón que para vosotras.

[[matthew-11-23]]
^23^ Y tú, Cafarnaúm, ¿hasta el cielo te vas a encumbrar? ¡Hasta el Hades te hundirás! Porque si en Sodoma se hubieran hecho los milagros que se han hecho en ti, aún subsistiría el día de hoy.

[[matthew-11-24]]
^24^ Por eso os digo que el día del Juicio habrá menos rigor para la tierra de Sodoma que para ti».

[[matthew-11-25]]
^25^ En aquel tiempo, tomando Jesús la palabra, dijo: «Yo te bendigo, Padre, Señor del cielo y de la tierra, porque has ocultado estas cosas a sabios e inteligentes, y se las has revelado a pequeños.

[[matthew-11-26]]
^26^ Sí, Padre, pues tal ha sido tu beneplácito.

[[matthew-11-27]]
^27^ Todo me ha sido entregado por mi Padre, y nadie conoce bien al Hijo sino el Padre, ni al Padre le conoce bien nadie sino el Hijo, y aquel a quien el Hijo se lo quiera revelar.

[[matthew-11-28]]
^28^ «Venid a mí todos los que estáis fatigados y sobrecargados, y yo os daré descanso.

[[matthew-11-29]]
^29^ Tomad sobre vosotros mi yugo, y aprended de mí, que soy manso y humilde de corazón; y hallaréis descanso para vuestras almas.

[[matthew-11-30]]
^30^ Porque mi yugo es suave y mi carga ligera».

[[matthew-12]]
== Capítulo 12

[[matthew-12-1]]
^1^ En aquel tiempo cruzaba Jesús un sábado por los sembrados. Y sus discípulos sintieron hambre y se pusieron a arrancar espigas y a comerlas.

[[matthew-12-2]]
^2^ Al verlo los fariseos, le dijeron: «Mira, tus discípulos hacen lo que no es lícito hacer en sábado».

[[matthew-12-3]]
^3^ Pero él les dijo: «¿No habéis leído lo que hizo David cuando sintió hambre él y los que le acompañaban,

[[matthew-12-4]]
^4^ cómo entró en la Casa de Dios y comieron los panes de la Presencia, que no le era lícito comer a él, ni a sus compañeros, sino sólo a los sacerdotes?

[[matthew-12-5]]
^5^ ¿Tampoco habéis leído en la Ley que en día de sábado los sacerdotes, en el Templo, quebrantan el sábado sin incurrir en culpa?

[[matthew-12-6]]
^6^ Pues yo os digo que hay aquí algo mayor que el Templo.

[[matthew-12-7]]
^7^ Si hubieseis comprendido lo que significa aquello de: Misericordia quiero, que no sacrificio, no condenaríais a los que no tienen culpa.

[[matthew-12-8]]
^8^ Porque el Hijo del hombre es señor del sábado».

[[matthew-12-9]]
^9^ Pasó de allí y se fue a la sinagoga de ellos.

[[matthew-12-10]]
^10^ Había allí un hombre que tenía una mano seca. Y le preguntaron si era lícito curar en sábado, para poder acusarle.

[[matthew-12-11]]
^11^ El les dijo: «¿Quién de vosotros que tenga una sola oveja, si ésta cae en un hoyo en sábado, no la agarra y la saca?

[[matthew-12-12]]
^12^ Pues, ¡cuánto más vale un hombre que una oveja! Por tanto, es lícito hacer bien en sábado».

[[matthew-12-13]]
^13^ Entonces dice al hombre: «Extiende tu mano». El la extendió, y quedó restablecida, sana como la otra.

[[matthew-12-14]]
^14^ Pero los fariseos, en cuanto salieron, se confabularon contra él para ver cómo eliminarle.

[[matthew-12-15]]
^15^ Jesús, al saberlo, se retiró de allí. Le siguieron muchos y los curó a todos.

[[matthew-12-16]]
^16^ Y les mandó enérgicamente que no le descubrieran;

[[matthew-12-17]]
^17^ para que se cumpliera el oráculo del profeta Isaías:

[[matthew-12-18]]
^18^ He aquí mi Siervo, a quien elegí, mi Amado, en quien mi alma se complace. Pondré mi Espíritu sobre él, y anunciará el juicio a las naciones.

[[matthew-12-19]]
^19^ No disputará ni gritará, ni oirá nadie en las plazas su voz.

[[matthew-12-20]]
^20^ La caña cascada no la quebrará, ni apagará la mecha humeante, hasta que lleve a la victoria el juicio:

[[matthew-12-21]]
^21^ en su nombre pondrán las naciones su esperanza.

[[matthew-12-22]]
^22^ Entonces le fue presentado un endemoniado ciego y mudo. Y le curó, de suerte que el mudo hablaba y veía.

[[matthew-12-23]]
^23^ Y toda la gente atónita decía: «¿No será éste el Hijo de David?»

[[matthew-12-24]]
^24^ Mas los fariseos, al oírlo, dijeron: «Este no expulsa los demonios más que por Beelzebul, Príncipe de los demonios».

[[matthew-12-25]]
^25^ El, conociendo sus pensamientos, les dijo: «Todo reino dividido contra sí mismo queda asolado, y toda ciudad o casa dividida contra sí misma no podrá subsistir.

[[matthew-12-26]]
^26^ Si Satanás expulsa a Satanás, contra sí mismo está dividido: ¿cómo, pues, va a subsistir su reino?

[[matthew-12-27]]
^27^ Y si yo expulso los demonios por Beelzebul, ¿por quién los expulsan vuestros hijos? Por eso, ellos serán vuestros jueces.

[[matthew-12-28]]
^28^ Pero si por el Espíritu de Dios expulso yo los demonios, es que ha llegado a vosotros el Reino de Dios.

[[matthew-12-29]]
^29^ «O, ¿cómo puede uno entrar en la casa del fuerte y saquear su ajuar, si no ata primero al fuerte? Entonces podrá saquear su casa.

[[matthew-12-30]]
^30^ «El que no está conmigo, está contra mí, y el que no recoge conmigo, desparrama.

[[matthew-12-31]]
^31^ «Por eso os digo: Todo pecado y blasfemia se perdonará a los hombres, pero la blasfemia contra el Espíritu no será perdonada.

[[matthew-12-32]]
^32^ Y al que diga una palabra contra el Hijo del hombre, se le perdonará; pero al que la diga contra el Espíritu Santo, no se le perdonará ni en este mundo ni en el otro.

[[matthew-12-33]]
^33^ «Suponed un árbol bueno, y su fruto será bueno; suponed un árbol malo, y su fruto será malo; porque por el fruto se conoce el árbol.

[[matthew-12-34]]
^34^ Raza de víboras, ¿cómo podéis vosotros hablar cosas buenas siendo malos? Porque de lo que rebosa el corazón habla la boca.

[[matthew-12-35]]
^35^ El hombre bueno, del buen tesoro saca cosas buenas y el hombre malo, del tesoro malo saca cosas malas.

[[matthew-12-36]]
^36^ Os digo que de toda palabra ociosa que hablen los hombres darán cuenta en el día del Juicio.

[[matthew-12-37]]
^37^ Porque por tus palabras serás declarado justo y por tus palabras serás condenado».

[[matthew-12-38]]
^38^ Entonces le interpelaron algunos escribas y fariseos: «Maestro, queremos ver una señal hecha por ti».

[[matthew-12-39]]
^39^ Mas él les respondió: «¡Generación malvada y adúltera! Una señal pide, y no se le dará otra señal que la señal del profeta Jonás.

[[matthew-12-40]]
^40^ Porque de la misma manera que Jonás estuvo en el vientre del cetáceo tres días y tres noches, así también el Hijo del hombre estará en el seno de la tierra tres días y tres noches.

[[matthew-12-41]]
^41^ Los ninivitas se levantarán en el Juicio con esta generación y la condenarán; porque ellos se convirtieron por la predicación de Jonás, y aquí hay algo más que Jonás.

[[matthew-12-42]]
^42^ La reina del Mediodía se levantará en el Juicio con esta generación y la condenará; porque ella vino de los confines de la tierra a oír la sabiduría de Salomón, y aquí hay algo más que Salomón.

[[matthew-12-43]]
^43^ «Cuando el espíritu inmundo sale del hombre, anda vagando por lugares áridos en busca de reposo, pero no lo encuentra.

[[matthew-12-44]]
^44^ Entonces dice: “Me volveré a mi casa, de donde salí.” Y al llegar la encuentra desocupada, barrida y en orden.

[[matthew-12-45]]
^45^ Entonces va y toma consigo otros siete espíritus peores que él; entran y se instalan allí, y el final de aquel hombre viene a ser peor que el principio. Así le sucederá también a esta generación malvada».

[[matthew-12-46]]
^46^ Todavía estaba hablando a la muchedumbre, cuando su madre y sus hermanos se presentaron fuera y trataban de hablar con él.

[[matthew-12-47]]
^47^ Alguien le dijo: «¡Oye! ahí fuera están tu madre y tus hermanos que desean hablarte».

[[matthew-12-48]]
^48^ Pero él respondió al que se lo decía: «¿Quién es mi madre y quiénes son mis hermanos?»

[[matthew-12-49]]
^49^ Y, extendiendo su mano hacia sus discípulos, dijo: «Estos son mi madre y mis hermanos.

[[matthew-12-50]]
^50^ Pues todo el que cumpla la voluntad de mi Padre celestial, ése es mi hermano, mi hermana y mi madre».

[[matthew-13]]
== Capítulo 13

[[matthew-13-1]]
^1^ Aquel día, salió Jesús de casa y se sentó a orillas del mar.

[[matthew-13-2]]
^2^ Y se reunió tanta gente junto a él, que hubo de subir a sentarse en una barca, y toda la gente quedaba en la ribera.

[[matthew-13-3]]
^3^ Y les habló muchas cosas en parábolas. Decía: «Una vez salió un sembrador a sembrar.

[[matthew-13-4]]
^4^ Y al sembrar, unas semillas cayeron a lo largo del camino; vinieron las aves y se las comieron.

[[matthew-13-5]]
^5^ Otras cayeron en pedregal, donde no tenían mucha tierra, y brotaron enseguida por no tener hondura de tierra;

[[matthew-13-6]]
^6^ pero en cuanto salió el sol se agostaron y, por no tener raíz, se secaron.

[[matthew-13-7]]
^7^ Otras cayeron entre abrojos; crecieron los abrojos y las ahogaron.

[[matthew-13-8]]
^8^ Otras cayeron en tierra buena y dieron fruto, una ciento, otra sesenta, otra treinta.

[[matthew-13-9]]
^9^ El que tenga oídos, que oiga».

[[matthew-13-10]]
^10^ Y acercándose los discípulos le dijeron: «¿Por qué les hablas en parábolas?»

[[matthew-13-11]]
^11^ El les respondió: «Es que a vosotros se os ha dado el conocer los misterios del Reino de los Cielos, pero a ellos no.

[[matthew-13-12]]
^12^ Porque a quien tiene se le dará y le sobrará; pero a quien no tiene, aun lo que tiene se le quitará.

[[matthew-13-13]]
^13^ Por eso les hablo en parábolas, porque viendo no ven, y oyendo no oyen ni entienden.

[[matthew-13-14]]
^14^ En ellos se cumple la profecía de Isaías: Oír, oiréis, pero no entenderéis, mirar, miraréis, pero no veréis.

[[matthew-13-15]]
^15^ Porque se ha embotado el corazón de este pueblo, han hecho duros sus oídos, y sus ojos han cerrado; no sea que vean con sus ojos, con sus oídos oigan, con su corazón entiendan y se conviertan, y yo los sane.

[[matthew-13-16]]
^16^ «¡Pero dichosos vuestros ojos, porque ven, y vuestros oídos, porque oyen!

[[matthew-13-17]]
^17^ Pues os aseguro que muchos profetas y justos desearon ver lo que vosotros veis, pero no lo vieron, y oír lo que vosotros oís, pero no lo oyeron.

[[matthew-13-18]]
^18^ «Vosotros, pues, escuchad la parábola del sembrador.

[[matthew-13-19]]
^19^ Sucede a todo el que oye la Palabra del Reino y no la comprende, que viene el Maligno y arrebata lo sembrado en su corazón: éste es el que fue sembrado a lo largo del camino.

[[matthew-13-20]]
^20^ El que fue sembrado en pedregal, es el que oye la Palabra, y al punto la recibe con alegría;

[[matthew-13-21]]
^21^ pero no tiene raíz en sí mismo, sino que es inconstante y, cuando se presenta una tribulación o persecución por causa de la Palabra, sucumba enseguida.

[[matthew-13-22]]
^22^ El que fue sembrado entre los abrojos, es el que oye la Palabra, pero los preocupaciones del mundo y la seducción de las riquezas ahogan la Palabra, y queda sin fruto.

[[matthew-13-23]]
^23^ Pero el que fue sembrado en tierra buena, es el que oye la Palabra y la comprende: éste sí que da fruto y produce, uno ciento, otro sesenta, otro treinta».

[[matthew-13-24]]
^24^ Otra parábola les propuso, diciendo: «El Reino de los Cielos es semejante a un hombre que sembró buena semilla en su campo.

[[matthew-13-25]]
^25^ Pero, mientras su gente dormía, vino su enemigo, sembró encima cizaña entre el trigo, y se fue.

[[matthew-13-26]]
^26^ Cuando brotó la hierba y produjo fruto, apareció entonces también la cizaña.

[[matthew-13-27]]
^27^ Los siervos del amo se acercaron a decirle: “Señor, ¿no sembraste semilla buena en tu campo? ¿Cómo es que tiene cizaña?”

[[matthew-13-28]]
^28^ El les contestó: “Algún enemigo ha hecho esto.” Dícenle los siervos: “¿Quieres, pues, que vayamos a recogerla?”

[[matthew-13-29]]
^29^ Díceles: “No, no sea que, al recoger la cizaña, arranquéis a la vez el trigo.

[[matthew-13-30]]
^30^ Dejad que ambos crezcan juntos hasta la siega. Y al tiempo de la siega, diré a los segadores: Recoged primero la cizaña y atadla en gavillas para quemarla, y el trigo recogedlo en mi granero.”»

[[matthew-13-31]]
^31^ Otra parábola les propuso: «El Reino de los Cielos es semejante a un grano de mostaza que tomó un hombre y lo sembró en su campo.

[[matthew-13-32]]
^32^ Es ciertamente más pequeña que cualquier semilla, pero cuando crece es mayor que las hortalizas, y se hace árbol, hasta el punto de que las aves del cielo vienen y anidan en sus ramas».

[[matthew-13-33]]
^33^ Les dijo otra parábola: «El Reino de los Cielos es semejante a la levadura que tomó una mujer y la metió en tres medidas de harina, hasta que fermentó todo».

[[matthew-13-34]]
^34^ Todo esto dijo Jesús en parábolas a la gente, y nada les hablaba sin parábolas,

[[matthew-13-35]]
^35^ para que se cumpliese el oráculo del profeta: Abriré en parábolas mi boca, publicaré lo que estaba oculto desde la creación del mundo.

[[matthew-13-36]]
^36^ Entonces despidió a la multitud y se fue a casa. Y se le acercaron sus discípulos diciendo: «Explícanos la parábola de la cizaña del campo».

[[matthew-13-37]]
^37^ El respondió: «El que siembra la buena semilla es el Hijo del hombre;

[[matthew-13-38]]
^38^ el campo es el mundo; la buena semilla son los hijos del Reino; la cizaña son los hijos del Maligno;

[[matthew-13-39]]
^39^ el enemigo que la sembró es el Diablo; la siega es el fin del mundo, y los segadores son los ángeles.

[[matthew-13-40]]
^40^ De la misma manera, pues, que se recoge la cizaña y se la quema en el fuego, así será al fin del mundo.

[[matthew-13-41]]
^41^ El Hijo del hombre enviará a sus ángeles, que recogerán de su Reino todos los escándalos y a los obradores de iniquidad,

[[matthew-13-42]]
^42^ y los arrojarán en el horno de fuego; allí será el llanto y el rechinar de dientes.

[[matthew-13-43]]
^43^ Entonces los justos brillarán como el sol en el Reino de su Padre. El que tenga oídos, que oiga.

[[matthew-13-44]]
^44^ «El Reino de los Cielos es semejante a un tesoro escondido en un campo que, al encontrarlo un hombre, vuelve a esconderlo y, por la alegría que le da, va, vende todo lo que tiene y compra el campo aquel».

[[matthew-13-45]]
^45^ «También es semejante el Reino de los Cielos a un mercader que anda buscando perlas finas,

[[matthew-13-46]]
^46^ y que, al encontrar una perla de gran valor, va, vende todo lo que tiene y la compra.

[[matthew-13-47]]
^47^ «También es semejante el Reino de los Cielos a una red que se echa en el mar y recoge peces de todas clases;

[[matthew-13-48]]
^48^ y cuando está llena, la sacan a la orilla, se sientan, y recogen en cestos los buenos y tiran los malos.

[[matthew-13-49]]
^49^ Así sucederá al fin del mundo: saldrán los ángeles, separarán a los malos de entre los justos

[[matthew-13-50]]
^50^ y los echarán en el horno de fuego; allí será el llanto y el rechinar de dientes.

[[matthew-13-51]]
^51^ «¿Habéis entendido todo esto?» Dícenle: «Sí».

[[matthew-13-52]]
^52^ Y él les dijo: «Así, todo escriba que se ha hecho discípulo del Reino de los Cielos es semejante al dueño de una casa que saca de sus arcas lo nuevo y lo viejo».

[[matthew-13-53]]
^53^ Y sucedió que, cuando acabó Jesús estas parábolas, partió de allí.

[[matthew-13-54]]
^54^ Viniendo a su patria, les enseñaba en su sinagoga, de tal manera que decían maravillados: «¿De dónde le viene a éste esa sabiduría y esos milagros?

[[matthew-13-55]]
^55^ ¿No es éste el hijo del carpintero? ¿No se llama su madre María, y sus hermanos Santiago, José, Simón y Judas?

[[matthew-13-56]]
^56^ Y sus hermanas, ¿no están todas entre nosotros? Entonces, ¿de dónde le viene todo esto?»

[[matthew-13-57]]
^57^ Y se escandalizaban a causa de él. Mas Jesús les dijo: «Un profeta sólo en su patria y en su casa carece de prestigio».

[[matthew-13-58]]
^58^ Y no hizo allí muchos milagros, a causa de su falta de fe.

[[matthew-14]]
== Capítulo 14

[[matthew-14-1]]
^1^ En aquel tiempo se enteró el tetrarca Herodes de la fama de Jesús,

[[matthew-14-2]]
^2^ y dijo a sus criados: «Ese es Juan el Bautista; él ha resucitado de entre los muertos, y por eso actúan en él fuerzas milagrosas».

[[matthew-14-3]]
^3^ Es que Herodes había prendido a Juan, le había encadenado y puesto en la cárcel, por causa de Herodías, la mujer de su hermano Filipo.

[[matthew-14-4]]
^4^ Porque Juan le decía: «No te es lícito tenerla».

[[matthew-14-5]]
^5^ Y aunque quería matarle, temió a la gente, porque le tenían por profeta.

[[matthew-14-6]]
^6^ Mas llegado el cumpleaños de Herodes, la hija de Herodías danzó en medio de todos gustando tanto a Herodes,

[[matthew-14-7]]
^7^ que éste le prometió bajo juramento darle lo que pidiese.

[[matthew-14-8]]
^8^ Ella, instigada por su madre, «dame aquí, dijo, en una bandeja, la cabeza de Juan el Bautista».

[[matthew-14-9]]
^9^ Entristecióse el rey, pero, a causa del juramento y de los comensales, ordenó que se le diese,

[[matthew-14-10]]
^10^ y envió a decapitar a Juan en la cárcel.

[[matthew-14-11]]
^11^ Su cabeza fue traída en una bandeja y entregada a la muchacha, la cual se la llevó a su madre.

[[matthew-14-12]]
^12^ Llegando después sus discípulos, recogieron el cadáver y lo sepultaron; y fueron a informar a Jesús.

[[matthew-14-13]]
^13^ Al oírlo Jesús, se retiró de allí en una barca, aparte, a un lugar solitario. En cuanto lo supieron las gentes, salieron tras él viniendo a pie de las ciudades.

[[matthew-14-14]]
^14^ Al desembarcar, vio mucha gente, sintió compasión de ellos y curó a sus enfermos.

[[matthew-14-15]]
^15^ Al atardecer se le acercaron los discíplulos diciendo: «El lugar está deshabitado, y la hora es ya pasada. Despide, pues, a la gente, para que vayan a los pueblos y se compren comida».

[[matthew-14-16]]
^16^ Mas Jesús les dijo: «No tienen por qué marcharse; dadles vosotros de comer».

[[matthew-14-17]]
^17^ Dícenle ellos: «No tenemos aquí más que cinco panes y dos peces».

[[matthew-14-18]]
^18^ El dijo: «Traédmelos acá».

[[matthew-14-19]]
^19^ Y ordenó a la gente reclinarse sobre la hierba; tomó luego los cinco panes y los dos peces, y levantando los ojos al cielo, pronunció la bendición y, partiendo los panes, se los dio a los discípulos y los discípulos a la gente.

[[matthew-14-20]]
^20^ Comieron todos y se saciaron, y recogieron de los trozos sobrantes doce canastos llenos.

[[matthew-14-21]]
^21^ Y los que habían comido eran unos 5.000 hombres, sin contar mujeres y niños.

[[matthew-14-22]]
^22^ Inmediatamente obligó a los discípulos a subir a la barca y a ir por delante de él a la otra orilla, mientras él despedía a la gente.

[[matthew-14-23]]
^23^ Después de despedir a la gente, subió al monte a solas para orar; al atardecer estaba solo allí.

[[matthew-14-24]]
^24^ La barca se hallaba ya distante de la tierra muchos estadios, zarandeada por las olas, pues el viento era contrario.

[[matthew-14-25]]
^25^ Y a la cuarta vigilia de la noche vino él hacia ellos, caminando sobre el mar.

[[matthew-14-26]]
^26^ Los discípulos, viéndole caminar sobre el mar, se turbaron y decían: «Es un fantasma», y de miedo se pusieron a gritar.

[[matthew-14-27]]
^27^ Pero al instante les habló Jesús diciendo: «¡Animo!, que soy yo; no temáis».

[[matthew-14-28]]
^28^ Pedro le respondió: «Señor, si eres tú, mándame ir donde ti sobre las aguas».

[[matthew-14-29]]
^29^ «¡Ven!», le dijo. Bajó Pedro de la barca y se puso a caminar sobre las aguas, yendo hacia Jesús.

[[matthew-14-30]]
^30^ Pero, viendo la violencia del viento, le entró miedo y, como comenzara a hundirse, gritó: «¡Señor, sálvame!»

[[matthew-14-31]]
^31^ Al punto Jesús, tendiendo la mano, le agarró y le dice: «Hombre de poca fe, ¿por qué dudaste?»

[[matthew-14-32]]
^32^ Subieron a la barca y amainó el viento.

[[matthew-14-33]]
^33^ Y los que estaban en la barca se postraron ante él diciendo: «Verdaderamente eres Hijo de Dios».

[[matthew-14-34]]
^34^ Terminada la travesía, llegaron a tierra en Genesaret.

[[matthew-14-35]]
^35^ Los hombres de aquel lugar, apenas le reconocieron, pregonaron la noticia por toda aquella comarca y le presentaron todos los enfermos.

[[matthew-14-36]]
^36^ Le pedían que tocaran siquiera la orla de su manto; y cuantos la tocaron quedaron salvados.

[[matthew-15]]
== Capítulo 15

[[matthew-15-1]]
^1^ Entonces se acercan a Jesús algunos fariseos y escribas venidos de Jerusalén, y le dicen:

[[matthew-15-2]]
^2^ «¿Por qué tus discípulos traspasan la tradición de los antepasados?; pues no se lavan las manos a la hora de comer».

[[matthew-15-3]]
^3^ El les respondió: «Y vosotros, ¿por qué traspasáis el mandamiento de Dios por vuestra tradición?

[[matthew-15-4]]
^4^ Porque Dios dijo: Honra a tu padre y a tu madre, y: El que maldiga a su padre o a su madre, sea castigado con la muerte.

[[matthew-15-5]]
^5^ Pero vosotros decís: El que diga a su padre o a su madre: “Lo que de mí podrías recibir como ayuda es ofrenda”,

[[matthew-15-6]]
^6^ ése no tendrá que honrar a su padre y a su madre. Así habéis anulado la Palabra de Dios por vuestra tradición.

[[matthew-15-7]]
^7^ Hipócritas, bien profetizó de vosotros Isaías cuando dijo:

[[matthew-15-8]]
^8^ Este pueblo me honra con los labios, pero su corazón está lejos de mí.

[[matthew-15-9]]
^9^ En vano me rinden culto, ya que enseñan doctrinas que son preceptos de hombres».

[[matthew-15-10]]
^10^ Luego llamó a la gente y les dijo: «Oíd y entended.

[[matthew-15-11]]
^11^ No es lo que entra en la boca lo que contamina al hombre; sino lo que sale de la boca, eso es lo que contamina al hombre».

[[matthew-15-12]]
^12^ Entonces se acercan los discípulos y le dicen: «¿Sabes que los fariseos se han escandalizado al oír tu palabra?»

[[matthew-15-13]]
^13^ El les respondió: «Toda planta que no haya plantado mi Padre celestial será arrancada de raíz.

[[matthew-15-14]]
^14^ Dejadlos: son ciegos que guían a ciegos. Y si un ciego guía a otro ciego, los dos caerán en el hoyo».

[[matthew-15-15]]
^15^ Tomando Pedro la palabra, le dijo: «Explícanos la parábola».

[[matthew-15-16]]
^16^ El dijo: «¿También vosotros estáis todavía sin inteligencia?

[[matthew-15-17]]
^17^ ¿No comprendéis que todo lo que entra en la boca pasa al vientre y luego se echa al excusado?

[[matthew-15-18]]
^18^ En cambio lo que sale de la boca viene de dentro del corazón, y eso es lo que contamina al hombre.

[[matthew-15-19]]
^19^ Porque del corazón salen las intenciones malas, asesinatos, adulterios, fornicaciones, robos, falsos testimonios, injurias.

[[matthew-15-20]]
^20^ Eso es lo que contamina al hombre; que el comer sin lavarse las manos no contamina al hombre».

[[matthew-15-21]]
^21^ Saliendo de allí Jesús se retiró hacia la región de Tiro y de Sidón.

[[matthew-15-22]]
^22^ En esto, una mujer cananea, que había salido de aquel territorio, gritaba diciendo: «¡Ten piedad de mí, Señor, hijo de David! Mi hija está malamente endemoniada».

[[matthew-15-23]]
^23^ Pero él no le respondió palabra. Sus discípulos, acercándose, le rogaban: «Concédeselo, que viene gritando detrás de nosotros».

[[matthew-15-24]]
^24^ Respondió él: «No he sido enviado más que a las ovejas perdidas de la casa de Israel».

[[matthew-15-25]]
^25^ Ella, no obstante, vino a postrarse ante él y le dijo: «¡Señor, socórreme!»

[[matthew-15-26]]
^26^ El respondió: «No está bien tomar el pan de los hijos y echárselo a los perritos».

[[matthew-15-27]]
^27^ «Sí, Señor - repuso ella -, pero también los perritos comen de las migajas que caen de la mesa de sus amos».

[[matthew-15-28]]
^28^ Entonces Jesús le respondió: «Mujer, grande es tu fe; que te suceda como deseas». Y desde aquel momento quedó curada su hija.

[[matthew-15-29]]
^29^ Pasando de allí Jesús vino junto al mar de Galilea; subió al monte y se sentó allí.

[[matthew-15-30]]
^30^ Y se le acercó mucha gente trayendo consigo cojos, lisiados, ciegos, mudos y otros muchos; los pusieron a sus pies, y él los curó.

[[matthew-15-31]]
^31^ De suerte que la gente quedó maravillada al ver que los mudos hablaban, los lisiados quedaban curados, los cojos caminaban y los ciegos veían; y glorificaron al Dios de Israel.

[[matthew-15-32]]
^32^ Jesús llamó a sus discípulos y les dijo: «Siento compasión de la gente, porque hace ya tres días que permanecen conmigo y no tienen qué comer. Y no quiero despedirlos en ayunas, no sea que desfallezcan en el camino».

[[matthew-15-33]]
^33^ Le dicen los discípulos: «¿Cómo hacernos en un desierto con pan suficiente para saciar a una multitud tan grande?»

[[matthew-15-34]]
^34^ Díceles Jesús: «¿Cuántos panes tenéis?» Ellos dijeron: «Siete, y unos pocos pececillos».

[[matthew-15-35]]
^35^ El mandó a la gente acomodarse en el suelo.

[[matthew-15-36]]
^36^ Tomó luego los siete panes y los peces y, dando gracias, los partió e iba dándolos a los discípulos, y los discípulos a la gente.

[[matthew-15-37]]
^37^ Comieron todos y se saciaron, y de los trozos sobrantes recogieron siete espuertas llenas.

[[matthew-15-38]]
^38^ Y los que habían comido eran 4.000 hombres, sin contar mujeres y niños.

[[matthew-15-39]]
^39^ Despidiendo luego a la muchedumbre, subió a la barca, y se fue al término de Magadán.

[[matthew-16]]
== Capítulo 16

[[matthew-16-1]]
^1^ Se acercaron los fariseos y saduceos y, para ponerle a prueba, le pidieron que les mostrase una señal del cielo.

[[matthew-16-2]]
^2^ Mas él les respondió: «Al atardecer decís: “Va a hacer buen tiempo, porque el cielo tiene un rojo de fuego”,

[[matthew-16-3]]
^3^ y a la mañana: “Hoy habrá tormenta, porque el cielo tiene un rojo sombrío.” ¡Conque sabéis discernir el aspecto del cielo y no podéis discernir las señales de los tiempos!

[[matthew-16-4]]
^4^ ¡Generación malvada y adúltera! Una señal pide y no se le dará otra señal que la señal de Jonás». Y dejándolos, se fue.

[[matthew-16-5]]
^5^ Los discípulos, al pasar a la otra orilla, se habían olvidado de tomar panes.

[[matthew-16-6]]
^6^ Jesús les dijo: «Abrid los ojos y guardaos de la levadura de los fariseos y saduceos».

[[matthew-16-7]]
^7^ Ellos hablaban entre sí diciendo: «Es que no hemos traído panes».

[[matthew-16-8]]
^8^ Mas Jesús, dándose cuenta, dijo: «Hombres de poca fe, ¿por qué estáis hablando entre vosotros de que no tenéis panes?

[[matthew-16-9]]
^9^ ¿Aún no comprendéis, ni os acordáis de los cinco panes de los 5.000 hombres, y cuántos canastos recogisteis?

[[matthew-16-10]]
^10^ ¿Ni de los siete panes de los 4.000, y cuántas espuertas recogisteis?

[[matthew-16-11]]
^11^ ¿Cómo no entendéis que no me refería a los panes? Guardaos, sí, de la levadura de los fariseos y saduceos».

[[matthew-16-12]]
^12^ Entonces comprendieron que no había querido decir que se guardasen de la levadura de los panes, sino de la doctrina de los fariseos y saduceos.

[[matthew-16-13]]
^13^ Llegado Jesús a la región de Cesarea de Filipo, hizo esta pregunta a sus discípulos: «¿Quién dicen los hombres que es el Hijo del hombre?»

[[matthew-16-14]]
^14^ Ellos dijeron: «Unos, que Juan el Bautista; otros, que Elías, otros, que Jeremías o uno de los profetas».

[[matthew-16-15]]
^15^ Díceles él: «Y vosotros ¿quién decís que soy yo?»

[[matthew-16-16]]
^16^ Simón Pedro contestó: «Tú eres el Cristo, el Hijo de Dios vivo».

[[matthew-16-17]]
^17^ Replicando Jesús le dijo: «Bienaventurado eres Simón, hijo de Jonás, porque no te ha revelado esto la carne ni la sangre, sino mi Padre que está en los cielos.

[[matthew-16-18]]
^18^ Y yo a mi vez te digo que tú eres Pedro, y sobre esta piedra edificaré mi Iglesia, y las puertas del Hades no prevalecerán contra ella.

[[matthew-16-19]]
^19^ A ti te daré las llaves del Reino de los Cielos; y lo que ates en la tierra quedará atado en los cielos, y lo que desates en la tierra quedará desatado en los cielos».

[[matthew-16-20]]
^20^ Entonces mandó a sus discípulos que no dijesen a nadie que él era el Cristo.

[[matthew-16-21]]
^21^ Desde entonces comenzó Jesús a manifestar a sus discípulos que él debía ir a Jerusalén y sufrir mucho de parte de los ancianos, los sumos sacerdotes y los escribas, y ser matado y resucitar al tercer día.

[[matthew-16-22]]
^22^ Tomándole aparte Pedro, se puso a reprenderle diciendo: «¡Lejos de ti, Señor! ¡De ningún modo te sucederá eso!»

[[matthew-16-23]]
^23^ Pero él, volviéndose, dijo a Pedro: «¡Quítate de mi vista, Satanás! ¡Escándalo eres para mí, porque tus pensamientos no son los de Dios, sino los de los hombres!

[[matthew-16-24]]
^24^ Entonces dijo Jesús a sus discípulos: «Si alguno quiere venir en pos de mí, niéguese a sí mismo, tome su cruz y sígame.

[[matthew-16-25]]
^25^ Porque quien quiera salvar su vida, la perderá, pero quien pierda su vida por mí, la encontrará.

[[matthew-16-26]]
^26^ Pues ¿de qué le servirá al hombre ganar el mundo entero, si arruina su vida? O ¿qué puede dar el hombre a cambio de su vida?

[[matthew-16-27]]
^27^ «Porque el Hijo del hombre ha de venir en la gloria de su Padre, con sus ángeles, y entonces pagará a cada uno según su conducta.

[[matthew-16-28]]
^28^ Yo os aseguro: entre los aquí presentes hay algunos que no gustarán la muerte hasta que vean al Hijo del hombre venir en su Reino».

[[matthew-17]]
== Capítulo 17

[[matthew-17-1]]
^1^ Seis días después, toma Jesús consigo a Pedro, a Santiago y a su hermano Juan, y los lleva aparte, a un monte alto.

[[matthew-17-2]]
^2^ Y se transfiguró delante de ellos: su rostro se puso brillante como el sol y sus vestidos se volvieron blancos como la luz.

[[matthew-17-3]]
^3^ En esto, se les aparecieron Moisés y Elías que conversaban con él.

[[matthew-17-4]]
^4^ Tomando Pedro la palabra, dijo a Jesús: «Señor, bueno es estarnos aquí. Si quieres, haré aquí tres tiendas, una para ti, otra para Moisés y otra para Elías».

[[matthew-17-5]]
^5^ Todavía estaba hablando, cuando una nube luminosa los cubrió con su sombra y de la nube salía una voz que decía: «Este es mi Hijo amado, en quien me complazco; escuchadle».

[[matthew-17-6]]
^6^ Al oír esto los discípulos cayeron rostro en tierra llenos de miedo.

[[matthew-17-7]]
^7^ Mas Jesús, acercándose a ellos, los tocó y dijo: «Levantaos, no tengáis miedo».

[[matthew-17-8]]
^8^ Ellos alzaron sus ojos y ya no vieron a nadie más que a Jesús solo.

[[matthew-17-9]]
^9^ Y cuando bajaban del monte, Jesús les ordenó: «No contéis a nadie la visión hasta que el Hijo del hombre haya resucitado de entre los muertos».

[[matthew-17-10]]
^10^ Sus discípulos le preguntaron: «¿Por qué, pues, dicen los escribas que Elías debe venir primero?»

[[matthew-17-11]]
^11^ Respondió él: «Ciertamente, Elías ha de venir a restaurarlo todo.

[[matthew-17-12]]
^12^ Os digo, sin embargo: Elías vino ya, pero no le reconocieron sino que hicieron con él cuanto quisieron. Así también el Hijo del hombre tendrá que padecer de parte de ellos».

[[matthew-17-13]]
^13^ Entonces los discípulos comprendieron que se refería a Juan el Bautista.

[[matthew-17-14]]
^14^ Cuando llegaron donde la gente, se acercó a él un hombre que, arrodillándose ante él,

[[matthew-17-15]]
^15^ le dijo: «Señor, ten piedad de mi hijo, porque es lunático y está mal; pues muchas veces cae en el fuego y muchas en el agua.

[[matthew-17-16]]
^16^ Se lo he presentado a tus discípulos, pero ellos no han podido curarle».

[[matthew-17-17]]
^17^ Jesús respondió: «¡Oh generación incrédula y perversa! ¿Hasta cuándo estaré con vosotros? ¿Hasta cuándo habré de soportaros? ¡Traédmelo acá!

[[matthew-17-18]]
^18^ Jesús le increpó y el demonio salió de él; y quedó sano el niño desde aquel momento.

[[matthew-17-19]]
^19^ Entonces los discípulos se acercaron a Jesús, en privado, y le dijeron: «¿Por qué nosotros no pudimos expulsarle?

[[matthew-17-20]]
^20^ Díceles: «Por vuestra poca fe. Porque yo os aseguro: si tenéis fe como un grano de mostaza, diréis a este monte: “Desplázate de aquí allá”, y se desplazará, y nada os será imposible».

[[matthew-17-22]]
^22^ Yendo un día juntos por Galilea, les dijo Jesús: «El Hijo del hombre va a ser entregado en manos de los hombres;

[[matthew-17-23]]
^23^ le matarán, y al tercer día resucitará». Y se entristecieron mucho.

[[matthew-17-24]]
^24^ Cuando entraron en Cafarnaúm, se acercaron a Pedro los que cobraban el didracma y le dijeron: «¿No paga vuestro Maestro el didracma?»

[[matthew-17-25]]
^25^ Dice él: «Sí». Y cuando llegó a casa, se anticipó Jesús a decirle: «¿Qué te parece, Simón?; los reyes de la tierra, ¿de quién cobran tasas o tributo, de sus hijos o de los extraños?»

[[matthew-17-26]]
^26^ Al contestar él: «De los extraños», Jesús le dijo: «Por tanto, libres están los hijos.

[[matthew-17-27]]
^27^ Sin embargo, para que no les sirvamos de escándalo, vete al mar, echa el anzuelo, y el primer pez que salga, cógelo, ábrele la boca y encontrarás un estáter. Tómalo y dáselo por mí y por ti».

[[matthew-18]]
== Capítulo 18

[[matthew-18-1]]
^1^ En aquel momento se acercaron a Jesús los discípulos y le dijeron: «¿Quién es, pues, el mayor en el Reino de los Cielos?»

[[matthew-18-2]]
^2^ El llamó a un niño, le puso en medio de ellos

[[matthew-18-3]]
^3^ y dijo: «Yo os aseguro: si no cambiáis y os hacéis como los niños, no entraréis en el Reino de los Cielos.

[[matthew-18-4]]
^4^ Así pues, quien se haga pequeño como este niño, ése es el mayor en el Reino de los Cielos.

[[matthew-18-5]]
^5^ «Y el que reciba a un niño como éste en mi nombre, a mí me recibe.

[[matthew-18-6]]
^6^ Pero al que escandalice a uno de estos pequeños que creen en mí, más le vale que le cuelguen al cuello una de esas piedras de molino que mueven los asnos, y le hundan en lo profundo del mar.

[[matthew-18-7]]
^7^ ¡Ay del mundo por los escándalos! Es forzoso, ciertamente, que vengan escándalos, pero ¡ay de aquel hombre por quien el escándalo viene!

[[matthew-18-8]]
^8^ «Si, pues, tu mano o tu pie te es ocasión de pecado, córtatelo y arrójalo de ti; más te vale entrar en la Vida manco o cojo que, con las dos manos o los dos pies, ser arrojado en el fuego eterno.

[[matthew-18-9]]
^9^ Y si tu ojo te es ocasión de pecado, sácatelo y arrójalo de ti; más te vale entrar en la Vida con un solo ojo que, con los dos ojos, ser arrojado a la gehenna del fuego.

[[matthew-18-10]]
^10^ «Guardaos de menospreciar a uno de estos pequeños; porque yo os digo que sus ángeles, en los cielos, ven continuamente el rostro de mi Padre que está en los cielos.

[[matthew-18-12]]
^12^ ¿Qué os parece? Si un hombre tiene cien ovejas y se le descarría una de ellas, ¿no dejará en los montes las noventa y nueve, para ir en busca de la descarriada?

[[matthew-18-13]]
^13^ Y si llega a encontrarla, os digo de verdad que tiene más alegría por ella que por las 99 no descarriadas.

[[matthew-18-14]]
^14^ De la misma manera, no es voluntad de vuestro Padre celestial que se pierda uno solo de estos pequeños.

[[matthew-18-15]]
^15^ «Si tu hermano llega a pecar, vete y repréndele, a solas tú con él. Si te escucha, habrás ganado a tu hermano.

[[matthew-18-16]]
^16^ Si no te escucha, toma todavía contigo uno o dos, para que todo asunto quede zanjado por la palabra de dos o tres testigos.

[[matthew-18-17]]
^17^ Si les desoye a ellos, díselo a la comunidad. Y si hasta a la comunidad desoye, sea para ti como el gentil y el publicano.

[[matthew-18-18]]
^18^ «Yo os aseguro: todo lo que atéis en la tierra quedará atado en el cielo, y todo lo que desatéis en la tierra quedará desatado en el cielo.

[[matthew-18-19]]
^19^ «Os aseguro también que si dos de vosotros se ponen de acuerdo en la tierra para pedir algo, sea lo que fuere, lo conseguirán de mi Padre que está en los cielos.

[[matthew-18-20]]
^20^ Porque donde están dos o tres reunidos en mi nombre, allí estoy yo en medio de ellos».

[[matthew-18-21]]
^21^ Pedro se acercó entonces y le dijo: «Señor, ¿cuántas veces tengo que perdonar las ofensas que me haga mi hermano? ¿Hasta siete veces?»

[[matthew-18-22]]
^22^ Dícele Jesús: «No te digo hasta siete veces, sino hasta setenta veces siete».

[[matthew-18-23]]
^23^ «Por eso el Reino de los Cielos es semejante a un rey que quiso ajustar cuentas con sus siervos.

[[matthew-18-24]]
^24^ Al empezar a ajustarlas, le fue presentado uno que le debía 10.000 talentos.

[[matthew-18-25]]
^25^ Como no tenía con qué pagar, ordenó el señor que fuese vendido él, su mujer y sus hijos y todo cuanto tenía, y que se le pagase.

[[matthew-18-26]]
^26^ Entonces el siervo se echó a sus pies, y postrado le decía: “Ten paciencia conmigo, que todo te lo pagaré.”

[[matthew-18-27]]
^27^ Movido a compasión el señor de aquel siervo, le dejó en libertad y le perdonó la deuda.

[[matthew-18-28]]
^28^ Al salir de allí aquel siervo se encontró con uno de sus compañeros, que le debía cien denarios; le agarró y, ahogándole, le decía: “Paga lo que debes.”

[[matthew-18-29]]
^29^ Su compañero, cayendo a sus pies, le suplicaba: “Ten paciencia conmigo, que ya te pagaré.”

[[matthew-18-30]]
^30^ Pero él no quiso, sino que fue y le echó en la cárcel, hasta que pagase lo que debía.

[[matthew-18-31]]
^31^ Al ver sus compañeros lo ocurrido, se entristecieron mucho, y fueron a contar a su señor todo lo sucedido.

[[matthew-18-32]]
^32^ Su señor entonces le mandó llamar y le dijo: “Siervo malvado, yo te perdoné a ti toda aquella deuda porque me lo suplicaste.

[[matthew-18-33]]
^33^ ¿No debías tú también compadecerte de tu compañero, del mismo modo que yo me compadecí de ti?”

[[matthew-18-34]]
^34^ Y encolerizado su señor, le entregó a los verdugos hasta que pagase todo lo que le debía.

[[matthew-18-35]]
^35^ Esto mismo hará con vosotros mi Padre celestial, si no perdonáis de corazón cada uno a vuestro hermano».

[[matthew-19]]
== Capítulo 19

[[matthew-19-1]]
^1^ Y sucedió que, cuando acabó Jesús estos discursos, partió de Galilea y fue a la región de Judea, al otro lado del Jordán.

[[matthew-19-2]]
^2^ Le siguió mucha gente, y los curó allí.

[[matthew-19-3]]
^3^ Y se le acercaron unos fariseos que, para ponerle a prueba, le dijeron: «¿Puede uno repudiar a su mujer por un motivo cualquiera?»

[[matthew-19-4]]
^4^ El respondió: «¿No habéis leído que el Creador, desde el comienzo, los hizo varón y hembra,

[[matthew-19-5]]
^5^ y que dijo: Por eso dejará el hombre a su padre y a su madre y se unirá a su mujer, y los dos se harán una sola carne?

[[matthew-19-6]]
^6^ De manera que ya no son dos, sino una sola carne. Pues bien, lo que Dios unió no lo separe el hombre».

[[matthew-19-7]]
^7^ Dícenle: «Pues ¿por qué Moisés prescribió dar acta de divorcio y repudiarla?»

[[matthew-19-8]]
^8^ Díceles: «Moisés, teniendo en cuenta la dureza de vuestro corazón, os permitió repudiar a vuestras mujeres; pero al principio no fue así.

[[matthew-19-9]]
^9^ Ahora bien, os digo que quien repudie a su mujer - no por fornicación - y se case con otra, comete adulterio».

[[matthew-19-10]]
^10^ Dícenle sus discípulos: «Si tal es la condición del hombre respecto de su mujer, no trae cuenta casarse».

[[matthew-19-11]]
^11^ Pero él les dijo: «No todos entienden este lenguaje, sino aquellos a quienes se les ha concedido.

[[matthew-19-12]]
^12^ Porque hay eunucos que nacieron así del seno materno, y hay eunucos que se hicieron tales a sí mismos por el Reino de los Cielos. Quien pueda entender, que entienda».

[[matthew-19-13]]
^13^ Entonces le fueron presentados unos niños para que les impusiera las manos y orase; pero los discípulos les reñían.

[[matthew-19-14]]
^14^ Mas Jesús les dijo: «Dejad que los niños vengan a mí, y no se lo impidáis porque de los que son como éstos es el Reino de los Cielos».

[[matthew-19-15]]
^15^ Y, después de imponerles las manos, se fue de allí.

[[matthew-19-16]]
^16^ En esto se le acercó uno y le dijo: «Maestro, ¿qué he de hacer de bueno para conseguir vida eterna?»

[[matthew-19-17]]
^17^ El le dijo: «¿Por qué me preguntas acerca de lo bueno? Uno solo es el Bueno. Mas si quieres entrar en la vida, guarda los mandamientos».

[[matthew-19-18]]
^18^ «¿Cuáles?» - le dice él. Y Jesús dijo: «No matarás, no cometerás adulterio, no robarás, no levantarás falso testimonio,

[[matthew-19-19]]
^19^ honra a tu padre y a tu madre, y amarás a tu prójimo como a ti mismo».

[[matthew-19-20]]
^20^ Dícele el joven: «Todo eso lo he guardado; ¿qué más me falta?»

[[matthew-19-21]]
^21^ Jesús le dijo: «Si quieres ser perfecto, anda, vende lo que tienes y dáselo a los pobres, y tendrás un tesoro en los cielos; luego ven, y sígueme».

[[matthew-19-22]]
^22^ Al oír estas palabras, el joven se marchó entristecido, porque tenía muchos bienes.

[[matthew-19-23]]
^23^ Entonces Jesús dijo a sus discípulos: «Yo os aseguro que un rico difícilmente entrará en el Reino de los Cielos.

[[matthew-19-24]]
^24^ Os lo repito, es más fácil que un camello entre por el ojo de una aguja, que el que un rico entre en el Reino de los Cielos».

[[matthew-19-25]]
^25^ Al oír esto, los discípulos, llenos de asombro, decían: «Entonces, ¿quién se podrá salvar?»

[[matthew-19-26]]
^26^ Jesús, mirándolos fijamente, dijo: «Para los hombres eso es imposible, mas para Dios todo es posible».

[[matthew-19-27]]
^27^ Entonces Pedro, tomando la palabra, le dijo: «Ya lo ves, nosotros lo hemos dejado todo y te hemos seguido; ¿qué recibiremos, pues?»

[[matthew-19-28]]
^28^ Jesús les dijo: «Yo os aseguro que vosotros que me habéis seguido, en la regeneración, cuando el Hijo del hombre se siente en su trono de gloria, os sentaréis también vosotros en doce tronos, para juzgar a las doce tribus de Israel.

[[matthew-19-29]]
^29^ Y todo aquel que haya dejado casas, hermanos, hermanas, padre, madre, hijos o hacienda por mi nombre, recibirá el ciento por uno y heredará vida eterna.

[[matthew-19-30]]
^30^ «Pero muchos primeros serán últimos y muchos últimos, primeros».

[[matthew-20]]
== Capítulo 20

[[matthew-20-1]]
^1^ «En efecto, el Reino de los Cielos es semejante a un propietario que salió a primera hora de la mañana a contratar obreros para su viña.

[[matthew-20-2]]
^2^ Habiéndose ajustado con los obreros en un denario al día, los envió a su viña.

[[matthew-20-3]]
^3^ Salió luego hacia la hora tercia y al ver a otros que estaban en la plaza parados,

[[matthew-20-4]]
^4^ les dijo: “Id también vosotros a mi viña, y os daré lo que sea justo.”

[[matthew-20-5]]
^5^ Y ellos fueron. Volvió a salir a la hora sexta y a la nona e hizo lo mismo.

[[matthew-20-6]]
^6^ Todavía salió a eso de la hora undécima y, al encontar a otros que estaban allí, les dice: “¿Por qué estáis aquí todo el día parados?”

[[matthew-20-7]]
^7^ Dícenle: “Es que nadie nos ha contratado.” Díceles: “Id también vosotros a la viña.”

[[matthew-20-8]]
^8^ Al atardecer, dice el dueño de la viña a su administrador: “Llama a los obreros y págales el jornal, empezando por los últimos hasta los primeros.”

[[matthew-20-9]]
^9^ Vinieron, pues, los de la hora undécima y cobraron un denario cada uno.

[[matthew-20-10]]
^10^ Al venir los primeros pensaron que cobrarían más, pero ellos también cobraron un denario cada uno.

[[matthew-20-11]]
^11^ Y al cobrarlo, murmuraban contra el propietario,

[[matthew-20-12]]
^12^ diciendo: “Estos últimos no han trabajado más que una hora, y les pagas como a nosotros, que hemos aguantado el peso del día y el calor.”

[[matthew-20-13]]
^13^ Pero él contestó a uno de ellos: “Amigo, no te hago ninguna injusticia. ¿No te ajustaste conmigo en un denario?

[[matthew-20-14]]
^14^ Pues toma lo tuyo y vete. Por mi parte, quiero dar a este último lo mismo que a ti.

[[matthew-20-15]]
^15^ ¿Es que no puedo hacer con lo mío lo que quiero? ¿O va a ser tu ojo malo porque yo soy bueno?”.

[[matthew-20-16]]
^16^ Así, los últimos serán primeros y los primeros, últimos».

[[matthew-20-17]]
^17^ Cuando iba subiendo Jesús a Jerusalén, tomó aparte a los Doce, y les dijo por el camino:

[[matthew-20-18]]
^18^ «Mirad que subimos a Jerusalén, y el Hijo del hombre será entregado a los sumos sacerdotes y escribas; le condenarán a muerte

[[matthew-20-19]]
^19^ y le entregarán a los gentiles, para burlarse de él, azotarle y crucificarle, y al tercer día resucitará.

[[matthew-20-20]]
^20^ Entonces se le acercó la madre de los hijos de Zebedeo con sus hijos, y se postró como para pedirle algo.

[[matthew-20-21]]
^21^ El le dijo: «¿Qué quieres?» Dícele ella: «Manda que estos dos hijos míos se sienten, uno a tu derecha y otro a tu izquierda, en tu Reino».

[[matthew-20-22]]
^22^ Replicó Jesús: «No sabéis lo que pedís. ¿Podéis beber la copa que yo voy a beber?» Dícenle: «Sí, podemos».

[[matthew-20-23]]
^23^ Díceles: «Mi copa, sí la beberéis; pero sentarse a mi derecha o mi izquierda no es cosa mía el concederlo, sino que es para quienes está preparado por mi Padre.

[[matthew-20-24]]
^24^ Al oír esto los otros diez, se indignaron contra los dos hermanos.

[[matthew-20-25]]
^25^ Mas Jesús los llamó y dijo: «Sabéis que los jefes de las naciones las dominan como señores absolutos, y los grandes las oprimen con su poder.

[[matthew-20-26]]
^26^ No ha de ser así entre vosotros, sino que el que quiera llegar a ser grande entre vosotros, será vuestro servidor,

[[matthew-20-27]]
^27^ y el que quiera ser el primero entre vosotros, será vuestro esclavo;

[[matthew-20-28]]
^28^ de la misma manera que el Hijo del hombre no ha venido a ser servido, sino a servir y a dar su vida como rescate por muchos».

[[matthew-20-29]]
^29^ Cuando salían de Jericó, le siguió una gran muchedumbre.

[[matthew-20-30]]
^30^ En esto, dos ciegos que estaban sentados junto al camino, al enterarse que Jesús pasaba, se pusieron a gritar: «¡Señor, ten compasión de nosotros, Hijo de David!»

[[matthew-20-31]]
^31^ La gente les increpó para que se callaran, pero ellos gritaron más fuerte: «¡Señor, ten compasión de nosotros, Hijo de David!»

[[matthew-20-32]]
^32^ Entonces Jesús se detuvo, los llamó y dijo: «¿Qué queréis que os haga?»

[[matthew-20-33]]
^33^ Dícenle: «¡Señor, que se abran nuestros ojos!»

[[matthew-20-34]]
^34^ Movido a compasión Jesús tocó sus ojos, y al instante recobraron la vista; y le siguieron.

[[matthew-21]]
== Capítulo 21

[[matthew-21-1]]
^1^ Cuando se aproximaron a Jerusalén, al llegar a Betfagé, junto al monte de los Olivos, entonces envió Jesús a dos discípulos,

[[matthew-21-2]]
^2^ diciéndoles: «Id al pueblo que está enfrente de vosotros, y enseguida encontraréis un asna atada y un pollino con ella; desatadlos y traédmelos.

[[matthew-21-3]]
^3^ Y si alguien os dice algo, diréis: El Señor los necesita, pero enseguida los devolverá».

[[matthew-21-4]]
^4^ Esto sucedió para que se cumpliese el oráculo del profeta:

[[matthew-21-5]]
^5^ Decid a la hija de Sión: He aquí que tu Rey viene a ti, manso y montado en un asna y un pollino, hijo de animal de yugo.

[[matthew-21-6]]
^6^ Fueron, pues, los discípulos e hicieron como Jesús les había encargado:

[[matthew-21-7]]
^7^ trajeron el asna y el pollino. Luego pusieron sobre ellos sus mantos, y él se sentó encima.

[[matthew-21-8]]
^8^ La gente, muy numerosa, extendió sus mantos por el camino; otros cortaban ramas de los árboles y las tendían por el camino.

[[matthew-21-9]]
^9^ Y la gente que iba delante y detrás de él gritaba: «¡Hosanna al Hijo de David! ¡Bendito el que viene en nombre del Señor! ¡Hosanna en las alturas!»

[[matthew-21-10]]
^10^ Y al entrar él en Jerusalén, toda la ciudad se conmovió. «¿Quién es éste?» decían.

[[matthew-21-11]]
^11^ Y la gente decía: «Este es el profeta Jesús, de Nazaret de Galilea».

[[matthew-21-12]]
^12^ Entró Jesús en el Templo y echó fuera a todos los que vendían y compraban en el Templo; volcó las mesas de los cambistas y los puestos de los vendedores de palomas.

[[matthew-21-13]]
^13^ Y les dijo: «Está escrito: Mi Casa será llamada Casa de oración. ¡Pero vosotros estáis haciendo de ella una cueva de bandidos!»

[[matthew-21-14]]
^14^ También en el Templo se acercaron a él algunos ciegos y cojos, y los curó.

[[matthew-21-15]]
^15^ Mas los sumos sacerdotes y los escribas, al ver los milagros que había hecho y a los niños que gritaban en el Templo: «¡Hosanna al Hijo de David!», se indignaron

[[matthew-21-16]]
^16^ y le dijeron: «¿Oyes lo que dicen éstos?» «Sí - les dice Jesús -. ¿No habéis leído nunca que De la boca de los niños y de los que aún maman te preparaste alabanza?»

[[matthew-21-17]]
^17^ Y dejándolos, salió fuera de la ciudad, a Betania, donde pasó la noche.

[[matthew-21-18]]
^18^ Al amanecer, cuando volvía a la ciudad, sintió hambre;

[[matthew-21-19]]
^19^ y viendo una higuera junto al camino, se acercó a ella, pero no encontró en ella más que hojas. Entonces le dice: «¡Que nunca jamás brote fruto de ti!» Y al momento se secó la higuera.

[[matthew-21-20]]
^20^ Al verlo los discípulos se maravillaron y decían: «¿Cómo al momento quedó seca la higuera?»

[[matthew-21-21]]
^21^ Jesús les respondió: «Yo os aseguro: si tenéis fe y no vaciláis, no sólo haréis lo de la higuera, sino que si aun decís a este monte: “Quítate y arrójate al mar”, así se hará.

[[matthew-21-22]]
^22^ Y todo cuanto pidáis con fe en la oración, lo recibiréis».

[[matthew-21-23]]
^23^ Llegado al Templo, mientras enseñaba se le acercaron los sumos sacerdotes y los ancianos del pueblo diciendo: «¿Con qué autoridad haces esto? ¿Y quién te ha dado tal autoridad?»

[[matthew-21-24]]
^24^ Jesús les respondió: «También yo os voy a preguntar una cosa; si me contestáis a ella, yo os diré a mi vez con qué autoridad hago esto.

[[matthew-21-25]]
^25^ El bautismo de Juan, ¿de dónde era?, ¿del cielo o de los hombres?» Ellos discurrían entre sí: «Si decimos: “Del cielo”, nos dirá: “Entonces ¿por qué no le creísteis?”

[[matthew-21-26]]
^26^ Y si decimos: “De los hombres”, tenemos miedo a la gente, pues todos tienen a Juan por profeta».

[[matthew-21-27]]
^27^ Respondieron, pues, a Jesús: «No sabemos». Y él les replicó asimismo: «Tampoco yo os digo con qué autoridad hago esto».

[[matthew-21-28]]
^28^ «Pero ¿qué os parece? Un hombre tenía dos hijos. Llegándose al primero, le dijo: “Hijo, vete hoy a trabajar en la viña.”

[[matthew-21-29]]
^29^ Y él respondió: “No quiero”, pero después se arrepintió y fue.

[[matthew-21-30]]
^30^ Llegándose al segundo, le dijo lo mismo. Y él respondió: “Voy, Señor”, y no fue.

[[matthew-21-31]]
^31^ ¿Cuál de los dos hizo la voluntad del padre?» - «El primero» - le dicen. Díceles Jesús: «En verdad os digo que los publicanos y las rameras llegan antes que vosotros al Reino de Dios.

[[matthew-21-32]]
^32^ Porque vino Juan a vosotros por camino de justicia, y no creísteis en él, mientras que los publicanos y las rameras creyeron en él. Y vosotros, ni viéndolo, os arrepentisteis después, para creer en él.

[[matthew-21-33]]
^33^ «Escuchad otra parábola. Era un propietario que plantó una viña, la rodeó de una cerca, cavó en ella un lagar y edificó una torre; la arrendó a unos labradores y se ausentó.

[[matthew-21-34]]
^34^ Cuando llegó el tiempo de los frutos, envió sus siervos a los labradores para recibir sus frutos.

[[matthew-21-35]]
^35^ Pero los labradores agarraron a los siervos, y a uno le golpearon, a otro le mataron, a otro le apedrearon.

[[matthew-21-36]]
^36^ De nuevo envió otros siervos en mayor número que los primeros; pero los trataron de la misma manera.

[[matthew-21-37]]
^37^ Finalmente les envió a su hijo, diciendo: “A mi hijo le respetarán.”

[[matthew-21-38]]
^38^ Pero los labradores, al ver al hijo, se dijeron entre sí: “Este es el heredero. Vamos, matémosle y quedémonos con su herencia.”

[[matthew-21-39]]
^39^ Y agarrándole, le echaron fuera de la viña y le mataron.

[[matthew-21-40]]
^40^ Cuando venga, pues, el dueño de la viña, ¿qué hará con aquellos labradores?»

[[matthew-21-41]]
^41^ Dícenle: «A esos miserables les dará una muerte miserable arrendará la viña a otros labradores, que le paguen los frutos a su tiempo».

[[matthew-21-42]]
^42^ Y Jesús les dice: «¿No habéis leído nunca en las Escrituras: La piedra que los constructores desecharon, en piedra angular se ha convertido; fue el Señor quien hizo esto y es maravilloso a nuestros ojos?

[[matthew-21-43]]
^43^ Por eso os digo: Se os quitará el Reino de Dios para dárselo a un pueblo que rinda sus frutos».

[[matthew-21-45]]
^45^ Los sumos sacerdotes y los fariseos, al oír sus parábolas, comprendieron que estaba refiriéndose a ellos.

[[matthew-21-46]]
^46^ Y trataban de detenerle, pero tuvieron miedo a la gente porque le tenían por profeta.

[[matthew-22]]
== Capítulo 22

[[matthew-22-1]]
^1^ Tomando Jesús de nuevo la palabra les habló en parábolas, diciendo:

[[matthew-22-2]]
^2^ «El Reino de los Cielos es semejante a un rey que celebró el banquete de bodas de su hijo.

[[matthew-22-3]]
^3^ Envió sus siervos a llamar a los invitados a la boda, pero no quisieron venir.

[[matthew-22-4]]
^4^ Envió todavía otros siervos, con este encargo: Decid a los invitados: “Mirad, mi banquete está preparado, se han matado ya mis novillos y animales cebados, y todo está a punto; venid a la boda.”

[[matthew-22-5]]
^5^ Pero ellos, sin hacer caso, se fueron el uno a su campo, el otro a su negocio;

[[matthew-22-6]]
^6^ y los demás agarraron a los siervos, los escarnecieron y los mataron.

[[matthew-22-7]]
^7^ Se airó el rey y, enviando sus tropas, dio muerte a aquellos homicidas y prendió fuego a su ciudad.

[[matthew-22-8]]
^8^ Entonces dice a sus siervos: “La boda está preparada, pero los invitados no eran dignos.

[[matthew-22-9]]
^9^ Id, pues, a los cruces de los caminos y, a cuantos encontréis, invitadlos a la boda.”

[[matthew-22-10]]
^10^ Los siervos salieron a los caminos, reunieron a todos los que encontraron, malos y buenos, y la sala de bodas se llenó de comensales.

[[matthew-22-11]]
^11^ «Entró el rey a ver a los comensales, y al notar que había allí uno que no tenía traje de boda,

[[matthew-22-12]]
^12^ le dice: “Amigo, ¿cómo has entrado aquí sin traje de boda?” El se quedó callado.

[[matthew-22-13]]
^13^ Entonces el rey dijo a los sirvientes: “Atadle de pies y manos, y echadle a las tinieblas de fuera; allí será el llanto y el rechinar de dientes.”

[[matthew-22-14]]
^14^ Porque muchos son llamados, mas pocos escogidos».

[[matthew-22-15]]
^15^ Entonces los fariseos se fueron y celebraron consejo sobre la forma de sorprenderle en alguna palabra.

[[matthew-22-16]]
^16^ Y le envían sus discípulos, junto con los herodianos, a decirle: «Maestro, sabemos que eres veraz y que enseñas el camino de Dios con franqueza y que no te importa por nadie, porque no miras la condición de las personas.

[[matthew-22-17]]
^17^ Dinos, pues, qué te parece, ¿es lícito pagar tributo al César o no?»

[[matthew-22-18]]
^18^ Mas Jesús, conociendo su malicia, dijo: «Hipócritas, ¿por qué me tentáis?

[[matthew-22-19]]
^19^ Mostradme la moneda del tributo». Ellos le presentaron un denario.

[[matthew-22-20]]
^20^ Y les dice: «¿De quién es esta imagen y la inscripción?»

[[matthew-22-21]]
^21^ Dícenle: «Del César». Entonces les dice: «Pues lo del César devolvédselo al César, y lo de Dios a Dios».

[[matthew-22-22]]
^22^ Al oír esto, quedaron maravillados, y dejándole, se fueron.

[[matthew-22-23]]
^23^ Aquel día se le acercaron unos saduceos, esos que niegan que haya resurrección, y le preguntaron:

[[matthew-22-24]]
^24^ «Maestro, Moisés dijo: Si alguien muere sin tener hijos, su hermano se casará con la mujer de aquél para dar descendencia a su hermano.

[[matthew-22-25]]
^25^ Ahora bien, había entre nosotros siete hermanos. El primero se casó y murió; y, no teniendo descendencia, dejó su mujer a su hermano.

[[matthew-22-26]]
^26^ Sucedió lo mismo con el segundo, y con el tercero, hasta los siete.

[[matthew-22-27]]
^27^ Después de todos murió la mujer.

[[matthew-22-28]]
^28^ En la resurrección, pues, ¿de cuál de los siete será mujer? Porque todos la tuvieron».

[[matthew-22-29]]
^29^ Jesús les respondió: «Estáis en un error, por no entender las Escrituras ni el poder de Dios.

[[matthew-22-30]]
^30^ Pues en la resurrección, ni ellos tomarán mujer ni ellas marido, sino que serán como ángeles en el cielo.

[[matthew-22-31]]
^31^ Y en cuanto a la resurrección de los muertos, ¿no habéis leído aquellas palabras de Dios cuando os dice:

[[matthew-22-32]]
^32^ Yo soy el Dios de Abraham, el Dios de Isaac y el Dios de Jacob? No es un Dios de muertos, sino de vivos».

[[matthew-22-33]]
^33^ Al oír esto, la gente se maravillaba de su doctrina.

[[matthew-22-34]]
^34^ Mas los fariseos, al enterarse de que había tapado la boca a los saduceos, se reunieron en grupo,

[[matthew-22-35]]
^35^ y uno de ellos le preguntó con ánimo de ponerle a prueba:

[[matthew-22-36]]
^36^ «Maestro, ¿cuál es el mandamiento mayor de la Ley?»

[[matthew-22-37]]
^37^ El le dijo: «Amarás al Señor, tu Dios, con todo tu corazón, con toda tu alma y con toda tu mente.

[[matthew-22-38]]
^38^ Este es el mayor y el primer mandamiento.

[[matthew-22-39]]
^39^ El segundo es semejante a éste: Amarás a tu prójimo como a ti mismo.

[[matthew-22-40]]
^40^ De estos dos mandamientos penden toda la Ley y los Profetas».

[[matthew-22-41]]
^41^ Estando reunidos los fariseos, les propuso Jesús esta cuestión:

[[matthew-22-42]]
^42^ «¿Qué pensáis acerca del Cristo? ¿De quién es hijo?» Dícenle: «De David».

[[matthew-22-43]]
^43^ Díceles: «Pues ¿cómo David, movido por el Espíritu, le llama Señor, cuando dice:

[[matthew-22-44]]
^44^ Dijo el Señor a mi Señor: Siéntate a mi diestra hasta que ponga a tus enemigos debajo de tus pies?

[[matthew-22-45]]
^45^ Si, pues, David le llama Señor, ¿cómo puede ser hijo suyo?»

[[matthew-22-46]]
^46^ Nadie era capaz de contestarle nada; y desde ese día ninguno se atrevió ya a hacerle más preguntas.

[[matthew-23]]
== Capítulo 23

[[matthew-23-1]]
^1^ Entonces Jesús se dirigió a la gente y a sus discípulos

[[matthew-23-2]]
^2^ y les dijo: «En la cátedra de Moisés se han sentado los escribas y los fariseos.

[[matthew-23-3]]
^3^ Haced, pues, y observad todo lo que os digan; pero no imitéis su conducta, porque dicen y no hacen.

[[matthew-23-4]]
^4^ Atan cargas pesadas y las echan a las espaldas de la gente, pero ellos ni con el dedo quieren moverlas.

[[matthew-23-5]]
^5^ Todas sus obras las hacen para ser vistos por los hombres; se hacen bien anchas las filacterias y bien largas las orlas del manto;

[[matthew-23-6]]
^6^ quieren el primer puesto en los banquetes y los primeros asientos en las sinagogas,

[[matthew-23-7]]
^7^ que se les salude en las plazas y que la gente les llame “Rabbí”.

[[matthew-23-8]]
^8^ «Vosotros, en cambio, no os dejéis llamar “Rabbí”, porque uno solo es vuestro Maestro; y vosotros sois todos hermanos.

[[matthew-23-9]]
^9^ Ni llaméis a nadie “Padre” vuestro en la tierra, porque uno solo es vuestro Padre: el del cielo.

[[matthew-23-10]]
^10^ Ni tampoco os dejéis llamar “Directores”, porque uno solo es vuestro Director: el Cristo.

[[matthew-23-11]]
^11^ El mayor entre vosotros será vuestro servidor.

[[matthew-23-12]]
^12^ Pues el que se ensalce, será humillado; y el que se humille, será ensalzado.

[[matthew-23-13]]
^13^ «¡Ay de vosotros, escribas y fariseos hipócritas, que cerráis a los hombres el Reino de los Cielos! Vosotros ciertamente no entráis; y a los que están entrando no les dejáis entrar.

[[matthew-23-15]]
^15^ «¡Ay de vosotros, escribas y fariseos hipócritas, que recorréis mar y tierra para hacer un prosélito, y, cuando llega a serlo, le hacéis hijo de condenación el doble que vosotros!

[[matthew-23-16]]
^16^ «¡Ay de vosotros, guías ciegos, que decís: “Si uno jura por el Santuario, eso no es nada; mas si jura por el oro del Santuario, queda obligado!”

[[matthew-23-17]]
^17^ ¡Insensatos y ciegos! ¿Qué es más importante, el oro, o el Santuario que hace sagrado el oro?

[[matthew-23-18]]
^18^ Y también: “Si uno jura por el altar, eso no es nada; mas si jura por la ofrenda que está sobre él, queda obligado.”

[[matthew-23-19]]
^19^ ¡Ciegos! ¿Qué es más importante, la ofrenda, o el altar que hace sagrada la ofrenda?

[[matthew-23-20]]
^20^ Quien jura, pues, por el altar, jura por él y por todo lo que está sobre él.

[[matthew-23-21]]
^21^ Quien jura por el Santuario, jura por él y por Aquel que lo habita.

[[matthew-23-22]]
^22^ Y quien jura por el cielo, jura por el trono de Dios y por Aquel que está sentado en él.

[[matthew-23-23]]
^23^ «¡Ay de vosotros, escribas y fariseos hipócritas, que pagáis el diezmo de la menta, del aneto y del comino, y descuidáis lo más importante de la Ley: la justicia, la misericordia y la fe! Esto es lo que había que practicar, aunque sin descuidar aquello.

[[matthew-23-24]]
^24^ ¡Guías ciegos, que coláis el mosquito y os tragáis el camello!

[[matthew-23-25]]
^25^ «¡Ay de vosotros, escribas y fariseos hipócritas, que purificáis por fuera la copa y el plato, mientras por dentro están llenos de rapiña e intemperancia!

[[matthew-23-26]]
^26^ ¡Fariseo ciego, purifica primero por dentro la copa, para que también por fuera quede pura!

[[matthew-23-27]]
^27^ «¡Ay de vosotros, escribas y fariseos hipócritas, pues sois semejantes a sepulcros blanqueados, que por fuera parecen bonitos, pero por dentro están llenos de huesos de muertos y de toda inmundicia!

[[matthew-23-28]]
^28^ Así también vosotros, por fuera aparecéis justos ante los hombres, pero por dentro estáis llenos de hipocresía y de iniquidad.

[[matthew-23-29]]
^29^ «¡Ay de vosotros, escribas y fariseos hipócritas, porque edificáis los sepulcros de los profetas y adornáis los monumentos de los justos,

[[matthew-23-30]]
^30^ y decís: “Si nosotros hubiéramos vivido en el tiempo de nuestros padres, no habríamos tenido parte con ellos en la sangre de los profetas!”

[[matthew-23-31]]
^31^ Con lo cual atestiguáis contra vosotros mismos que sois hijos de los que mataron a los profetas.

[[matthew-23-32]]
^32^ ¡Colmad también vosotros la medida de vuestros padres!

[[matthew-23-33]]
^33^ «¡Serpientes, raza de víboras! ¿Cómo vais a escapar a la condenación de la gehenna?

[[matthew-23-34]]
^34^ Por eso, he aquí que yo envío a vosotros profetas, sabios y escribas: a unos los mataréis y los crucificaréis, a otros los azotaréis en vuestras sinagogas y los perseguiréis de ciudad en ciudad,

[[matthew-23-35]]
^35^ para que caiga sobre vosotros toda la sangre inocente derramada sobre la tierra, desde la sangre del inocente Abel hasta la sangre de Zacarías, hijo de Baraquías, a quien matasteis entre el Santuario y el altar.

[[matthew-23-36]]
^36^ Yo os aseguro: todo esto recaerá sobre esta generación.

[[matthew-23-37]]
^37^ «¡Jerusalén, Jerusalén, la que mata a los profetas y apedrea a los que le son enviados! ¡Cuántas veces he querido reunir a tus hijos, como una gallina reúne a sus pollos bajo las alas, y no habéis querido!

[[matthew-23-38]]
^38^ Pues bien, se os va a dejar desierta vuestra casa.

[[matthew-23-39]]
^39^ Porque os digo que ya no me volveréis a ver hasta que digáis: ¡Bendito el que viene en nombre del Señor!»

[[matthew-24]]
== Capítulo 24

[[matthew-24-1]]
^1^ Salió Jesús del Templo y, cuando se iba, se le acercaron sus discípulos para mostrarle las construcciones del Templo.

[[matthew-24-2]]
^2^ Pero él les respondió: «¿Veis todo esto? Yo os aseguro no quedará aquí piedra sobre piedra que no sea derruida».

[[matthew-24-3]]
^3^ Estando luego sentado en el monte de los Olivos, se acercaron a él en privado sus discípulos, y le dijeron: «Dinos cuándo sucederá eso, y cuál será la señal de tu venida y del fin del mundo».

[[matthew-24-4]]
^4^ Jesús les respondió: «Mirad que no os engañe nadie.

[[matthew-24-5]]
^5^ Porque vendrán muchos usurpando mi nombre y diciendo: “Yo soy el Cristo”, y engañarán a muchos.

[[matthew-24-6]]
^6^ Oiréis también hablar de guerras y rumores de guerras. ¡Cuidado, no os alarméis! Porque eso es necesario que suceda, pero no es todavía el fin.

[[matthew-24-7]]
^7^ Pues se levantará nación contra nación y reino contra reino, y habrá en diversos lugares hambre y terremotos.

[[matthew-24-8]]
^8^ Todo esto será el comienzo de los dolores de alumbramiento.

[[matthew-24-9]]
^9^ «Entonces os entregarán a la tortura y os matarán, y seréis odiados de todas las naciones por causa de mi nombre.

[[matthew-24-10]]
^10^ Muchos se escandalizarán entonces y se traicionarán y odiarán mutuamente.

[[matthew-24-11]]
^11^ Surgirán muchos falsos profetas, que engañarán a muchos.

[[matthew-24-12]]
^12^ Y al crecer cada vez más la iniquidad, la caridad de la mayoría se enfriará.

[[matthew-24-13]]
^13^ Pero el que persevere hasta el fin, ése se salvará.

[[matthew-24-14]]
^14^ «Se proclamará esta Buena Nueva del Reino en el mundo entero, para dar testimonio a todas las naciones. Y entonces vendrá el fin.

[[matthew-24-15]]
^15^ «Cuando veáis, pues, la abominación de la desolación, anunciada por el profeta Daniel, erigida en el Lugar Santo (el que lea, que entienda),

[[matthew-24-16]]
^16^ entonces, los que estén en Judea, huyan a los montes;

[[matthew-24-17]]
^17^ el que esté en el terrado, no baje a recoger las cosas de su casa;

[[matthew-24-18]]
^18^ y el que esté en el campo, no regrese en busca de su manto.

[[matthew-24-19]]
^19^ ¡Ay de las que estén encinta o criando en aquellos días!

[[matthew-24-20]]
^20^ Orad para que vuestra huida no suceda en invierno ni en día de sábado.

[[matthew-24-21]]
^21^ Porque habrá entonces una gran tribulación, cual no la hubo desde el principio del mundo hasta el presente ni volverá a haberla.

[[matthew-24-22]]
^22^ Y si aquellos días no se abreviasen, no se salvaría nadie; pero en atención a los elegidos se abreviarán aquellos días.

[[matthew-24-23]]
^23^ «Entonces, si alguno os dice: “Mirad, el Cristo está aquí o allí, no lo creáis.

[[matthew-24-24]]
^24^ Porque surgirán falsos cristos y falsos profetas, que harán grandes señales y prodigios, capaces de engañar, si fuera posible, a los mismos elegidos.

[[matthew-24-25]]
^25^ ¡Mirad que os lo he predicho!

[[matthew-24-26]]
^26^ «Así que si os dicen: “Está en el desierto”, no salgáis; “Está en los aposentos”, no lo creáis.

[[matthew-24-27]]
^27^ Porque como el relámpago sale por oriente y brilla hasta occidente, así será la venida del Hijo del hombre.

[[matthew-24-28]]
^28^ Donde esté el cadáver, allí se juntarán los buitres.

[[matthew-24-29]]
^29^ «Inmediatamente después de la tribulación de aquellos días, el sol se oscurecerá, la luna no dará su resplandor, las estrellas caerán del cielo, y las fuerzas de los cielos serán sacudidas.

[[matthew-24-30]]
^30^ Entonces aparecerá en el cielo la señal del Hijo del hombre; y entonces se golpearán el pecho todas las razas de la tierra y verán al Hijo del hombre venir sobre las nubes del cielo con gran poder y gloria.

[[matthew-24-31]]
^31^ El enviará a sus ángeles con sonora trompeta, y reunirán de los cuatro vientos a sus elegidos, desde un extremo de los cielos hasta el otro.

[[matthew-24-32]]
^32^ «De la higuera aprended esta parábola: cuando ya sus ramas están tiernas y brotan las hojas, sabéis que el verano está cerca.

[[matthew-24-33]]
^33^ Así también vosotros, cuando veáis todo esto, sabed que El está cerca, a las puertas.

[[matthew-24-34]]
^34^ Yo os aseguro que no pasará esta generación hasta que todo esto suceda.

[[matthew-24-35]]
^35^ El cielo y la tierra pasarán, pero mis palabras no pasarán.

[[matthew-24-36]]
^36^ Mas de aquel día y hora, nadie sabe nada, ni los ángeles de los cielos, ni el Hijo, sino sólo el Padre.

[[matthew-24-37]]
^37^ «Como en los días de Noé, así será la venida del Hijo del hombre.

[[matthew-24-38]]
^38^ Porque como en los días que precedieron al diluvio, comían, bebían, tomaban mujer o marido, hasta el día en que entró Noé en el arca,

[[matthew-24-39]]
^39^ y no se dieron cuenta hasta que vino el diluvio y los arrastró a todos, así será también la venida del Hijo del hombre.

[[matthew-24-40]]
^40^ Entonces, estarán dos en el campo: uno es tomado, el otro dejado;

[[matthew-24-41]]
^41^ dos mujeres moliendo en el molino: una es tomada, la otra dejada.

[[matthew-24-42]]
^42^ «Velad, pues, porque no sabéis qué día vendrá vuestro Señor.

[[matthew-24-43]]
^43^ Entendedlo bien: si el dueño de casa supiese a qué hora de la noche iba a venir el ladrón, estaría en vela y no permitiría que le horadasen su casa.

[[matthew-24-44]]
^44^ Por eso, también vosotros estad preparados, porque en el momento que no penséis, vendrá el Hijo del hombre.

[[matthew-24-45]]
^45^ «¿Quién es, pues, el siervo fiel y prudente, a quien el señor puso al frente de su servidumbre para darles la comida a su tiempo?

[[matthew-24-46]]
^46^ Dichoso aquel siervo a quien su señor, al llegar, encuentre haciéndolo así.

[[matthew-24-47]]
^47^ Yo os aseguro que le pondrá al frente de toda su hacienda.

[[matthew-24-48]]
^48^ Pero si el mal siervo aquel se dice en su corazón: “Mi señor tarda”,

[[matthew-24-49]]
^49^ y se pone a golpear a sus compañeros y come y bebe con los borrachos,

[[matthew-24-50]]
^50^ vendrá el señor de aquel siervo el día que no espera y en el momento que no sabe,

[[matthew-24-51]]
^51^ le separará y le señalará su suerte entre los hipócritas; allí será el llanto y el rechinar de dientes.

[[matthew-25]]
== Capítulo 25

[[matthew-25-1]]
^1^ «Entonces el Reino de los Cielos será semejante a diez vírgenes, que, con su lámpara en la mano, salieron al encuentro del novio.

[[matthew-25-2]]
^2^ Cinco de ellas eran necias, y cinco prudentes.

[[matthew-25-3]]
^3^ Las necias, en efecto, al tomar sus lámparas, no se proveyeron de aceite;

[[matthew-25-4]]
^4^ las prudentes, en cambio, junto con sus lámparas tomaron aceite en las alcuzas.

[[matthew-25-5]]
^5^ Como el novio tardara, se adormilaron todas y se durmieron.

[[matthew-25-6]]
^6^ Mas a media noche se oyó un grito: “¡Ya está aquí el novio! ¡Salid a su encuentro!”

[[matthew-25-7]]
^7^ Entonces todas aquellas vírgenes se levantaron y arreglaron sus lámparas.

[[matthew-25-8]]
^8^ Y las necias dijeron a las prudentes: “Dadnos de vuestro aceite, que nuestras lámparas se apagan.”

[[matthew-25-9]]
^9^ Pero las prudentes replicaron: “No, no sea que no alcance para nosotras y para vosotras; es mejor que vayáis donde los vendedores y os lo compréis.”

[[matthew-25-10]]
^10^ Mientras iban a comprarlo, llegó el novio, y las que estaban preparadas entraron con él al banquete de boda, y se cerró la puerta.

[[matthew-25-11]]
^11^ Más tarde llegaron las otras vírgenes diciendo: “¡Señor, señor, ábrenos!”

[[matthew-25-12]]
^12^ Pero él respondió: “En verdad os digo que no os conozco.”

[[matthew-25-13]]
^13^ Velad, pues, porque no sabéis ni el día ni la hora.

[[matthew-25-14]]
^14^ «Es también como un hombre que, al ausentarse, llamó a sus siervos y les encomendó su hacienda:

[[matthew-25-15]]
^15^ a uno dio cinco talentos, a otro dos y a otro uno, a cada cual según su capacidad; y se ausentó.

[[matthew-25-16]]
^16^ Enseguida, el que había recibido cinco talentos se puso a negociar con ellos y ganó otros cinco.

[[matthew-25-17]]
^17^ Igualmente el que había recibido dos ganó otros dos.

[[matthew-25-18]]
^18^ En cambio el que había recibido uno se fue, cavó un hoyo en tierra y escondió el dinero de su señor.

[[matthew-25-19]]
^19^ Al cabo de mucho tiempo, vuelve el señor de aquellos siervos y ajusta cuentas con ellos.

[[matthew-25-20]]
^20^ Llegándose el que había recibido cinco talentos, presentó otros cinco, diciendo: “Señor, cinco talentos me entregaste; aquí tienes otros cinco que he ganado.”

[[matthew-25-21]]
^21^ Su señor le dijo: “¡Bien, siervo bueno y fiel!; en lo poco has sido fiel, al frente de lo mucho te pondré; entra en el gozo de tu señor.”

[[matthew-25-22]]
^22^ Llegándose también el de los dos talentos dijo: “Señor, dos talentos me entregaste; aquí tienes otros dos que he ganado.”

[[matthew-25-23]]
^23^ Su señor le dijo: “¡Bien, siervo bueno y fiel!; en lo poco has sido fiel, al frente de lo mucho te pondré; entra en el gozo de tu señor.”

[[matthew-25-24]]
^24^ Llegándose también el que había recibido un talento dijo: “Señor, sé que eres un hombre duro, que cosechas donde no sembraste y recoges donde no esparciste.

[[matthew-25-25]]
^25^ Por eso me dio miedo, y fui y escondí en tierra tu talento. Mira, aquí tienes lo que es tuyo.”

[[matthew-25-26]]
^26^ Mas su señor le respondió: “Siervo malo y perezoso, sabías que yo cosecho donde no sembré y recojo donde no esparcí;

[[matthew-25-27]]
^27^ debías, pues, haber entregado mi dinero a los banqueros, y así, al volver yo, habría cobrado lo mío con los intereses.

[[matthew-25-28]]
^28^ Quitadle, por tanto, su talento y dádselo al que tiene los diez talentos.

[[matthew-25-29]]
^29^ Porque a todo el que tiene, se le dará y le sobrará; pero al que no tiene, aun lo que tiene se le quitará.

[[matthew-25-30]]
^30^ Y a ese siervo inútil, echadle a las tinieblas de fuera. Allí será el llanto y el rechinar de dientes.”

[[matthew-25-31]]
^31^ «Cuando el Hijo del hombre venga en su gloria acompañado de todos sus ángeles, entonces se sentará en su trono de gloria.

[[matthew-25-32]]
^32^ Serán congregadas delante de él todas las naciones, y él separará a los unos de los otros, como el pastor separa las ovejas de los cabritos.

[[matthew-25-33]]
^33^ Pondrá las ovejas a su derecha, y los cabritos a su izquierda.

[[matthew-25-34]]
^34^ Entonces dirá el Rey a los de su derecha: “Venid, benditos de mi Padre, recibid la herencia del Reino preparado para vosotros desde la creación del mundo.

[[matthew-25-35]]
^35^ Porque tuve hambre, y me disteis de comer; tuve sed, y me disteis de beber; era forastero, y me acogisteis;

[[matthew-25-36]]
^36^ estaba desnudo, y me vestisteis; enfermo, y me visitasteis; en la cárcel, y vinisteis a verme.”

[[matthew-25-37]]
^37^ Entonces los justos le responderán: “Señor, ¿cuándo te vimos hambriento, y te dimos de comer; o sediento, y te dimos de beber?

[[matthew-25-38]]
^38^ ¿Cuándo te vimos forastero, y te acogimos; o desnudo, y te vestimos?

[[matthew-25-39]]
^39^ ¿Cuándo te vimos enfermo o en la cárcel, y fuimos a verte?”

[[matthew-25-40]]
^40^ Y el Rey les dirá: “En verdad os digo que cuanto hicisteis a unos de estos hermanos míos más pequeños, a mí me lo hicisteis.”

[[matthew-25-41]]
^41^ Entonces dirá también a los de su izquierda: “Apartaos de mí, malditos, al fuego eterno preparado para el Diablo y sus ángeles.

[[matthew-25-42]]
^42^ Porque tuve hambre, y no me disteis de comer; tuve sed, y no me disteis de beber;

[[matthew-25-43]]
^43^ era forastero, y no me acogisteis; estaba desnudo, y no me vestisteis; enfermo y en la cárcel, y no me visitasteis.”

[[matthew-25-44]]
^44^ Entonces dirán también éstos: “Señor, ¿cuándo te vimos hambriento o sediento o forastero o desnudo o enfermo o en la cárcel, y no te asistimos?”

[[matthew-25-45]]
^45^ Y él entonces les responderá: “En verdad os digo que cuanto dejasteis de hacer con uno de estos más pequeños, también conmigo dejasteis de hacerlo.”

[[matthew-25-46]]
^46^ E irán éstos a un castigo eterno, y los justos a una vida eterna».

[[matthew-26]]
== Capítulo 26

[[matthew-26-1]]
^1^ Y sucedió que, cuando acabó Jesús todos estos discursos, dijo a sus discípulos:

[[matthew-26-2]]
^2^ «Ya sabéis que dentro de dos días es la Pascua; y el Hijo del hombre va a ser entregado para ser crucificado».

[[matthew-26-3]]
^3^ Entonces los sumos sacerdotes y los ancianos del pueblo se reunieron en el palacio del Sumo Sacerdote, llamado Caifás;

[[matthew-26-4]]
^4^ y resolvieron prender a Jesús con engaño y darle muerte.

[[matthew-26-5]]
^5^ Decían sin embargo: «Durante la fiesta no, para que no haya alboroto en el pueblo».

[[matthew-26-6]]
^6^ Hallándose Jesús en Betania, en casa de Simón el leproso,

[[matthew-26-7]]
^7^ se acercó a él una mujer que traía un frasco de alabastro, con perfume muy caro, y lo derramó sobre su cabeza mientras estaba a la mesa.

[[matthew-26-8]]
^8^ Al ver esto los discípulos se indignaron y dijeron: «¿Para qué este despilfarro?

[[matthew-26-9]]
^9^ Se podía haber vendido a buen precio y habérselo dado a los pobres».

[[matthew-26-10]]
^10^ Mas Jesús, dándose cuenta, les dijo: «¿Por qué molestáis a esta mujer? Pues una “obra buena” ha hecho conmigo.

[[matthew-26-11]]
^11^ Porque pobres tendréis siempre con vosotros, pero a mí no me tendréis siempre.

[[matthew-26-12]]
^12^ Y al derramar ella este ungüento sobre mi cuerpo, en vista de mi sepultura lo ha hecho.

[[matthew-26-13]]
^13^ Yo os aseguro: dondequiera que se proclame esta Buena Nueva, en el mundo entero, se hablará también de lo que ésta ha hecho para memoria suya».

[[matthew-26-14]]
^14^ Entonces uno de los Doce, llamado Judas Iscariote, fue donde los sumos sacerdotes,

[[matthew-26-15]]
^15^ y les dijo: «¿Qué queréis darme, y yo os lo entregaré?» Ellos le asignaron treinta monedas de plata.

[[matthew-26-16]]
^16^ Y desde ese momento andaba buscando una oportunidad para entregarle.

[[matthew-26-17]]
^17^ El primer día de los Azimos, los discípulos se acercaron a Jesús y le dijeron: «¿Dónde quieres que te hagamos los preparativos para comer el cordero de Pascua?»

[[matthew-26-18]]
^18^ El les dijo: «Id a la ciudad, a casa de fulano, y decidle: “El Maestro dice: Mi tiempo está cerca; en tu casa voy a celebrar la Pascua con mis discípulos.”»

[[matthew-26-19]]
^19^ Los discípulos hicieron lo que Jesús les había mandado, y prepararon la Pascua.

[[matthew-26-20]]
^20^ Al atardecer, se puso a la mesa con los Doce.

[[matthew-26-21]]
^21^ Y mientras comían, dijo: «Yo os aseguro que uno de vosotros me entregará».

[[matthew-26-22]]
^22^ Muy entristecidos, se pusieron a decirle uno por uno: «¿Acaso soy yo, Señor?»

[[matthew-26-23]]
^23^ El respondió: «El que ha mojado conmigo la mano en el plato, ése me entregará.

[[matthew-26-24]]
^24^ El Hijo del hombre se va, como está escrito de él, pero ¡ay de aquel por quien el Hijo del hombre es entregado! ¡Más le valdría a ese hombre no haber nacido!»

[[matthew-26-25]]
^25^ Entonces preguntó Judas, el que iba a entregarle: «¿Soy yo acaso, Rabbí?» Dícele: «Sí, tú lo has dicho».

[[matthew-26-26]]
^26^ Mientras estaban comiendo, tomó Jesús pan y lo bendijo, lo partió y, dándoselo a sus discípulos, dijo: «Tomad, comed, éste es mi cuerpo».

[[matthew-26-27]]
^27^ Tomó luego una copa y, dadas las gracias, se la dio diciendo: «Bebed de ella todos,

[[matthew-26-28]]
^28^ porque ésta es mi sangre de la Alianza, que es derramada por muchos para perdón de los pecados.

[[matthew-26-29]]
^29^ Y os digo que desde ahora no beberé de este producto de la vid hasta el día aquel en que lo beba con vosotros, nuevo, en el Reino de mi Padre».

[[matthew-26-30]]
^30^ Y cantados los himnos, salieron hacia el monte de los Olivos.

[[matthew-26-31]]
^31^ Entonces les dice Jesús: «Todos vosotros vais a escandalizaros de mí esta noche, porque está escrito: Heriré al pastor y se dispersarán las ovejas del rebaño.

[[matthew-26-32]]
^32^ Mas después de mi resurrección, iré delante de vosotros a Galilea».

[[matthew-26-33]]
^33^ Pedro intervino y le dijo: «Aunque todos se escandalicen de ti, yo nunca me escandalizaré».

[[matthew-26-34]]
^34^ Jesús le dijo: «Yo te aseguro: esta misma noche, antes que el gallo cante, me habrás negado tres veces».

[[matthew-26-35]]
^35^ Dícele Pedro: «Aunque tenga que morir contigo, yo no te negaré». Y lo mismo dijeron también todos los discípulos.

[[matthew-26-36]]
^36^ Entonces va Jesús con ellos a una propiedad llamada Getsemaní, y dice a los discípulos: «Sentaos aquí, mientras voy allá a orar».

[[matthew-26-37]]
^37^ Y tomando consigo a Pedro y a los dos hijos de Zebedeo, comenzó a sentir tristeza y angustia.

[[matthew-26-38]]
^38^ Entonces les dice: «Mi alma está triste hasta el punto de morir; quedaos aquí y velad conmigo».

[[matthew-26-39]]
^39^ Y adelantándose un poco, cayó rostro en tierra, y suplicaba así: «Padre mío, si es posible, que pase de mí esta copa, pero no sea como yo quiero, sino como quieras tú».

[[matthew-26-40]]
^40^ Viene entonces donde los discípulos y los encuentra dormidos; y dice a Pedro: «¿Conque no habéis podido velar una hora conmigo?

[[matthew-26-41]]
^41^ Velad y orad, para que no caigáis en tentación; que el espíritu está pronto, pero la carne es débil».

[[matthew-26-42]]
^42^ Y alejándose de nuevo, por segunda vez oró así: «Padre mío, si esta copa no puede pasar sin que yo la beba, hágase tu voluntad».

[[matthew-26-43]]
^43^ Volvió otra vez y los encontró dormidos, pues sus ojos estaban cargados.

[[matthew-26-44]]
^44^ Los dejó y se fue a orar por tercera vez, repitiendo las mismas palabras.

[[matthew-26-45]]
^45^ Viene entonces donde los discípulos y les dice: «Ahora ya podéis dormir y descansar. Mirad, ha llegado la hora en que el Hijo del hombre va a ser entregado en manos de pecadores.

[[matthew-26-46]]
^46^ ¡Levantaos!, ¡vámonos! Mirad que el que me va a entregar está cerca».

[[matthew-26-47]]
^47^ Todavía estaba hablando, cuando llegó Judas, uno de los Doce, acompañado de un grupo numeroso con espadas y palos, de parte de los sumos sacerdotes y los ancianos del pueblo.

[[matthew-26-48]]
^48^ El que le iba a entregar les había dado esta señal: «Aquel a quien yo dé un beso, ése es; prendedle».

[[matthew-26-49]]
^49^ Y al instante se acercó a Jesús y le dijo: «¡Salve, Rabbí!», y le dio un beso.

[[matthew-26-50]]
^50^ Jesús le dijo: «Amigo, ¡a lo que estás aquí!» Entonces aquéllos se acercaron, echaron mano a Jesús y le prendieron.

[[matthew-26-51]]
^51^ En esto, uno de los que estaban con Jesús echó mano a su espada, la sacó e, hiriendo al siervo del Sumo Sacerdote, le llevó la oreja.

[[matthew-26-52]]
^52^ Dícele entonces Jesús: «Vuelve tu espada a su sitio, porque todos los que empuñen espada, a espada perecerán.

[[matthew-26-53]]
^53^ ¿O piensas que no puedo yo rogar a mi Padre, que pondría al punto a mi disposición más de doce legiones de ángeles?

[[matthew-26-54]]
^54^ Mas, ¿cómo se cumplirían las Escrituras de que así debe suceder?»

[[matthew-26-55]]
^55^ En aquel momento dijo Jesús a la gente: «¿Como contra un salteador habéis salido a prenderme con espadas y palos? Todos los días me sentaba en el Templo para enseñar, y no me detuvisteis.

[[matthew-26-56]]
^56^ Pero todo esto ha sucedido para que se cumplan las Escrituras de los profetas». Entonces los discípulos le abandonaron todos y huyeron.

[[matthew-26-57]]
^57^ Los que prendieron a Jesús le llevaron ante el Sumo Sacerdote Caifás, donde se habían reunido los escribas y los ancianos.

[[matthew-26-58]]
^58^ Pedro le iba siguiendo de lejos hasta el palacio del Sumo Sacerdote; y, entrando dentro, se sentó con los criados para ver el final.

[[matthew-26-59]]
^59^ Los sumos sacerdotes y el Sanedrín entero andaban buscando un falso testimonio contra Jesús con ánimo de darle muerte,

[[matthew-26-60]]
^60^ y no lo encontraron, a pesar de que se presentaron muchos falsos testigos. Al fin se presentaron dos,

[[matthew-26-61]]
^61^ que dijeron: «Este dijo: Yo puedo destruir el Santuario de Dios, y en tres días edificarlo».

[[matthew-26-62]]
^62^ Entonces, se levantó el Sumo Sacerdote y le dijo: «¿No respondes nada? ¿Qué es lo que éstos atestiguan contra ti?»

[[matthew-26-63]]
^63^ Pero Jesús seguía callado. El Sumo Sacerdote le dijo: «Yo te conjuro por Dios vivo que nos digas si tú eres el Cristo, el Hijo de Dios».

[[matthew-26-64]]
^64^ Dícele Jesús: «Sí, tú lo has dicho. Y yo os declaro que a partir de ahora veréis al hijo del hombre sentado a la diestra del Poder y venir sobre las nubes del cielo».

[[matthew-26-65]]
^65^ Entonces el Sumo Sacerdote rasgó sus vestidos y dijo: «¡Ha blasfemado! ¿Qué necesidad tenemos ya de testigos? Acabáis de oír la blasfemia.

[[matthew-26-66]]
^66^ ¿Qué os parece?» Respondieron ellos diciendo: «Es reo de muerte».

[[matthew-26-67]]
^67^ Entonces se pusieron a escupirle en la cara y a abofetearle; y otros a golpearle,

[[matthew-26-68]]
^68^ diciendo: «Adivínanos, Cristo. ¿Quién es el que te ha pegado?»

[[matthew-26-69]]
^69^ Pedro, entretanto, estaba sentado fuera en el patio; y una criada se acercó a él y le dijo: «También tú estabas con Jesús el Galileo».

[[matthew-26-70]]
^70^ Pero él lo negó delante de todos: «No sé qué dices».

[[matthew-26-71]]
^71^ Cuando salía al portal, le vio otra criada y dijo a los que estaban allí: «Este estaba con Jesús el Nazoreo».

[[matthew-26-72]]
^72^ Y de nuevo lo negó con juramento: «¡Yo no conozco a ese hombre!»

[[matthew-26-73]]
^73^ Poco después se acercaron los que estaban allí y dijeron a Pedro: «¡Ciertamente, tú también eres de ellos, pues además tu misma habla te descubre!»

[[matthew-26-74]]
^74^ Entonces él se puso a echar imprecaciones y a jurar: «¡Yo no conozco a ese hombre!» Inmediatamente cantó un gallo.

[[matthew-26-75]]
^75^ Y Pedro se acordó de aquello que le había dicho Jesús: «Antes que el gallo cante, me habrás negado tres veces». Y, saliendo fuera, rompió a llorar amargamente.

[[matthew-27]]
== Capítulo 27

[[matthew-27-1]]
^1^ Llegada la mañana, todos los sumos sacerdotes y los ancianos del pueblo celebraron consejo contra Jesús para darle muerte.

[[matthew-27-2]]
^2^ Y después de atarle, le llevaron y le entregaron al procurador Pilato.

[[matthew-27-3]]
^3^ Entonces Judas, el que le entregó, viendo que había sido condenado, fue acosado por el remordimiento, y devolvió las treinta monedas de plata a los sumos sacerdotes y a los ancianos,

[[matthew-27-4]]
^4^ diciendo: «Pequé entregando sangre inocente». Ellos dijeron: «A nosotros, ¿qué? Tú verás».

[[matthew-27-5]]
^5^ El tiró las monedas en el Santuario; después se retiró y fue y se ahorcó.

[[matthew-27-6]]
^6^ Los sumos sacerdotes recogieron las monedas y dijeron: «No es lícito echarlas en el tesoro de las ofrendas, porque son precio de sangre».

[[matthew-27-7]]
^7^ Y después de deliberar, compraron con ellas el Campo del Alfarero como lugar de sepultura para los forasteros.

[[matthew-27-8]]
^8^ Por esta razón ese campo se llamó «Campo de Sangre», hasta hoy.

[[matthew-27-9]]
^9^ Entonces se cumplió el oráculo del profeta Jeremías: «Y tomaron las treinta monedas de plata, cantidad en que fue apreciado aquel a quien pusieron precio algunos hijos de Israel,

[[matthew-27-10]]
^10^ y las dieron por el Campo del Alfarero, según lo que me ordenó el Señor».

[[matthew-27-11]]
^11^ Jesús compareció ante el procurador, y el procurador le preguntó: «¿Eres tú el Rey de los judíos?» Respondió Jesús: «Sí, tú lo dices».

[[matthew-27-12]]
^12^ Y, mientras los sumos sacerdotes y los ancianos le acusaban, no respondió nada.

[[matthew-27-13]]
^13^ Entonces le dice Pilato: «¿No oyes de cuántas cosas te acusan?»

[[matthew-27-14]]
^14^ Pero él a nada respondió, de suerte que el procurador estaba muy sorprendido.

[[matthew-27-15]]
^15^ Cada Fiesta, el procurador solía conceder al pueblo la libertad de un preso, el que quisieran.

[[matthew-27-16]]
^16^ Tenían a la sazón un preso famoso, llamado Barrabás.

[[matthew-27-17]]
^17^ Y cuando ellos estaban reunidos, les dijo Pilato: «¿A quién queréis que os suelte, a Barrabás o a Jesús, el llamado Cristo?»,

[[matthew-27-18]]
^18^ pues sabía que le habían entregado por envidia.

[[matthew-27-19]]
^19^ Mientras él estaba sentado en el tribunal, le mandó a decir su mujer: «No te metas con ese justo, porque hoy he sufrido mucho en sueños por su causa».

[[matthew-27-20]]
^20^ Pero los sumos sacerdotes y los ancianos lograron persuadir a la gente que pidiese la libertad de Barrabás y la muerte de Jesús.

[[matthew-27-21]]
^21^ Y cuando el procurador les dijo: «¿A cuál de los dos queréis que os suelte?», respondieron: «¡A Barrabás!»

[[matthew-27-22]]
^22^ Díceles Pilato: «Y ¿qué voy a hacer con Jesús, el llamado Cristo?» Y todos a una: «¡Sea crucificado!» -

[[matthew-27-23]]
^23^ «Pero ¿qué mal ha hecho?», preguntó Pilato. Mas ellos seguían gritando con más fuerza: «¡Sea crucificado!»

[[matthew-27-24]]
^24^ Entonces Pilato, viendo que nada adelantaba, sino que más bien se promovía tumulto, tomó agua y se lavó las manos delante de la gente diciendo: «Inocente soy de la sangre de este justo. Vosotros veréis».

[[matthew-27-25]]
^25^ Y todo el pueblo respondió: «¡Su sangre sobre nosotros y sobre nuestros hijos!»

[[matthew-27-26]]
^26^ Entonces, les soltó a Barrabás; y a Jesús, después de azotarle, se lo entregó para que fuera crucificado.

[[matthew-27-27]]
^27^ Entonces los soldados del procurador llevaron consigo a Jesús al pretorio y reunieron alrededor de él a toda la cohorte.

[[matthew-27-28]]
^28^ Le desnudaron y le echaron encima un manto de púrpura;

[[matthew-27-29]]
^29^ y, trenzando una corona de espinas, se la pusieron sobre su cabeza, y en su mano derecha una caña; y doblando la rodilla delante de él, le hacían burla diciendo: «¡Salve, Rey de los judíos!»;

[[matthew-27-30]]
^30^ y después de escupirle, cogieron la caña y le golpeaban en la cabeza.

[[matthew-27-31]]
^31^ Cuando se hubieron burlado de él, le quitaron el manto, le pusieron sus ropas y le llevaron a crucificarle.

[[matthew-27-32]]
^32^ Al salir, encontraron a un hombre de Cirene llamado Simón, y le obligaron a llevar su cruz.

[[matthew-27-33]]
^33^ Llegados a un lugar llamado Gólgota, esto es, «Calvario»,

[[matthew-27-34]]
^34^ le dieron a beber vino mezclado con hiel; pero él, después de probarlo, no quiso beberlo.

[[matthew-27-35]]
^35^ Una vez que le crucificaron, se repartieron sus vestidos, echando a suertes.

[[matthew-27-36]]
^36^ Y se quedaron sentados allí para custodiarle.

[[matthew-27-37]]
^37^ Sobre su cabeza pusieron, por escrito, la causa de su condena: «Este es Jesús, el Rey de los judíos».

[[matthew-27-38]]
^38^ Y al mismo tiempo que a él crucifican a dos salteadores, uno a la derecha y otro a la izquierda.

[[matthew-27-39]]
^39^ Los que pasaban por allí le insultaban, meneando la cabeza y diciendo:

[[matthew-27-40]]
^40^ «Tú que destruyes el Santuario y en tres días lo levantas, ¡sálvate a ti mismo, si eres Hijo de Dios, y baja de la cruz!»

[[matthew-27-41]]
^41^ Igualmente los sumos sacerdotes junto con los escribas y los ancianos se burlaban de él diciendo:

[[matthew-27-42]]
^42^ «A otros salvó y a sí mismo no puede salvarse. Rey de Israel es: que baje ahora de la cruz, y creeremos en él.

[[matthew-27-43]]
^43^ Ha puesto su confianza en Dios; que le salve ahora, si es que de verdad le quiere; ya que dijo: “Soy Hijo de Dios.”»

[[matthew-27-44]]
^44^ De la misma manera le injuriaban también los salteadores crucificados con él.

[[matthew-27-45]]
^45^ Desde la hora sexta hubo oscuridad sobre toda la tierra hasta la hora nona.

[[matthew-27-46]]
^46^ Y alrededor de la hora nona clamó Jesús con fuerte voz: «¡Elí, Elí! ¿lemá sabactaní?», esto es: «¡Dios mío, Dios mío! ¿por qué me has abandonado?»

[[matthew-27-47]]
^47^ Al oírlo algunos de los que estaban allí decían: «A Elías llama éste».

[[matthew-27-48]]
^48^ Y enseguida uno de ellos fue corriendo a tomar una esponja, la empapó en vinagre y, sujetándola a una caña, le ofrecía de beber.

[[matthew-27-49]]
^49^ Pero los otros dijeron: «Deja, vamos a ver si viene Elías a salvarle».

[[matthew-27-50]]
^50^ Pero Jesús, dando de nuevo un fuerte grito, exhaló el espíritu.

[[matthew-27-51]]
^51^ En esto, el velo del Santuario se rasgó en dos, de arriba abajo; tembló la tierra y las rocas se hendieron.

[[matthew-27-52]]
^52^ Se abrieron los sepulcros, y muchos cuerpos de santos difuntos resucitaron.

[[matthew-27-53]]
^53^ Y, saliendo de los sepulcros después de la resurrección de él, entraron en la Ciudad Santa y se aparecieron a muchos.

[[matthew-27-54]]
^54^ Por su parte, el centurión y los que con él estaban guardando a Jesús, al ver el terremoto y lo que pasaba, se llenaron de miedo y dijeron: «Verdaderamente éste era Hijo de Dios».

[[matthew-27-55]]
^55^ Había allí muchas mujeres mirando desde lejos, aquellas que habían seguido a Jesús desde Galilea para servirle.

[[matthew-27-56]]
^56^ Entre ellas estaban María Magdalena, María la madre de Santiago y de José, y la madre de los hijos de Zebedeo.

[[matthew-27-57]]
^57^ Al atardecer, vino un hombre rico de Arimatea, llamado José, que se había hecho también discípulo de Jesús.

[[matthew-27-58]]
^58^ Se presentó a Pilato y pidió el cuerpo de Jesús. Entonces Pilato dio orden de que se le entregase.

[[matthew-27-59]]
^59^ José tomó el cuerpo, lo envolvió en una sábana limpia

[[matthew-27-60]]
^60^ y lo puso en su sepulcro nuevo que había hecho excavar en la roca; luego, hizo rodar una gran piedra hasta la entrada del sepulcro y se fue.

[[matthew-27-61]]
^61^ Estaban allí María Magdalena y la otra María, sentadas frente al sepulcro.

[[matthew-27-62]]
^62^ Al otro día, el siguiente a la Preparación, los sumos sacerdotes y los fariseos se reunieron ante Pilato

[[matthew-27-63]]
^63^ y le dijeron: «Señor, recordamos que ese impostor dijo cuando aún vivía: “A los tres días resucitaré.”

[[matthew-27-64]]
^64^ Manda, pues, que quede asegurado el sepulcro hasta el tercer día, no sea que vengan sus discípulos, lo roben y digan luego al pueblo: “Resucitó de entre los muertos”, y la última impostura sea peor que la primera».

[[matthew-27-65]]
^65^ Pilato les dijo: «Tenéis una guardia. Id, aseguradlo como sabéis».

[[matthew-27-66]]
^66^ Ellos fueron y aseguraron el sepulcro, sellando la piedra y poniendo la guardia.

[[matthew-28]]
== Capítulo 28

[[matthew-28-1]]
^1^ Pasado el sábado, al alborear el primer día de la semana, María Magdalena y la otra María fueron a ver el sepulcro.

[[matthew-28-2]]
^2^ De pronto se produjo un gran terremoto, pues el Angel del Señor bajó del cielo y, acercándose, hizo rodar la piedra y se sentó encima de ella.

[[matthew-28-3]]
^3^ Su aspecto era como el relámpago y su vestido blanco como la nieve.

[[matthew-28-4]]
^4^ Los guardias, atemorizados ante él, se pusieron a temblar y se quedaron como muertos.

[[matthew-28-5]]
^5^ El Angel se dirigió a las mujeres y les dijo: «Vosotras no temáis, pues sé que buscáis a Jesús, el Crucificado;

[[matthew-28-6]]
^6^ no está aquí, ha resucitado, como lo había dicho. Venid, ved el lugar donde estaba.

[[matthew-28-7]]
^7^ Y ahora id enseguida a decir a sus discípulos: “Ha resucitado de entre los muertos e irá delante de vosotros a Galilea; allí le veréis.” Ya os lo he dicho».

[[matthew-28-8]]
^8^ Ellas partieron a toda prisa del sepulcro, con miedo y gran gozo, y corrieron a dar la noticia a sus discípulos.

[[matthew-28-9]]
^9^ En esto, Jesús les salió al encuentro y les dijo: «¡Dios os guarde!» Y ellas, acercándose, se asieron de sus pies y le adoraron.

[[matthew-28-10]]
^10^ Entonces les dice Jesús: «No temáis. Id, avisad a mis hermanos que vayan a Galilea; allí me verán».

[[matthew-28-11]]
^11^ Mientras ellas iban, algunos de la guardia fueron a la ciudad a contar a los sumos sacerdotes todo lo que había pasado.

[[matthew-28-12]]
^12^ Estos, reunidos con los ancianos, celebraron consejo y dieron una buena suma de dinero a los soldados,

[[matthew-28-13]]
^13^ advirtiéndoles: «Decid: “Sus discípulos vinieron de noche y le robaron mientras nosotros dormíamos.”

[[matthew-28-14]]
^14^ Y si la cosa llega a oídos del procurador, nosotros le convenceremos y os evitaremos complicaciones».

[[matthew-28-15]]
^15^ Ellos tomaron el dinero y procedieron según las instrucciones recibidas. Y se corrió esa versión entre los judíos, hasta el día de hoy.

[[matthew-28-16]]
^16^ Por su parte, los once discípulos marcharon a Galilea, al monte que Jesús les había indicado.

[[matthew-28-17]]
^17^ Y al verle le adoraron; algunos sin embargo dudaron.

[[matthew-28-18]]
^18^ Jesús se acercó a ellos y les habló así: «Me ha sido dado todo poder en el cielo y en la tierra.

[[matthew-28-19]]
^19^ Id, pues, y haced discípulos a todas las gentes bautizándolas en el nombre del Padre y del Hijo y del Espíritu Santo,

[[matthew-28-20]]
^20^ y enseñándoles a guardar todo lo que yo os he mandado. Y he aquí que yo estoy con vosotros todos los días hasta el fin del mundo».
