[[mark]]
= Marcos

[[mark-1]]
== Capítulo 1

[[mark-1-1]]
^1^ Comienzo del Evangelio de Jesucristo, Hijo de Dios.

[[mark-1-2]]
^2^ Conforme está escrito en Isaías el profeta: Mira, envío mi mensajero delante de ti, el que ha de preparar tu camino.

[[mark-1-3]]
^3^ Voz del que clama en el desierto: Preparad el camino del Señor, enderezad sus sendas,

[[mark-1-4]]
^4^ apareció Juan bautizando en el desierto, proclamando un bautismo de conversión para perdón de los pecados.

[[mark-1-5]]
^5^ Acudía a él gente de toda la región de Judea y todos los de Jerusalén, y eran bautizados por él en el río Jordán, confesando sus pecados.

[[mark-1-6]]
^6^ Juan llevaba un vestido de pie de camello; y se alimentaba de langostas y miel silvestre.

[[mark-1-7]]
^7^ Y proclamaba: «Detrás de mí viene el que es más fuerte que yo; y no soy digno de desatarle, inclinándome, la correa de sus sandalias.

[[mark-1-8]]
^8^ Yo os he bautizado con agua, pero él os bautizará con Espíritu Santo».

[[mark-1-9]]
^9^ Y sucedió que por aquellos días vino Jesús desde Nazaret de Galilea, y fue bautizado por Juan en el Jordán.

[[mark-1-10]]
^10^ En cuanto salió del agua vio que los cielos se rasgaban y que el Espíritu, en forma de paloma, bajaba a él.

[[mark-1-11]]
^11^ Y se oyó una voz que venía de los cielos: «Tú eres mi Hijo amado, en ti me complazco».

[[mark-1-12]]
^12^ A continuación, el Espíritu le empuja al desierto,

[[mark-1-13]]
^13^ y permaneció en el desierto cuarenta días, siendo tentado por Satanás. Estaba entre los animales del campo y los ángeles le servían.

[[mark-1-14]]
^14^ Después que Juan fue entregado, marchó Jesús a Galilea; y proclamaba la Buena Nueva de Dios:

[[mark-1-15]]
^15^ «El tiempo se ha cumplido y el Reino de Dios está cerca; convertíos y creed en la Buena Nueva».

[[mark-1-16]]
^16^ Bordeando el mar de Galilea, vio a Simón y Andrés, el hermano de Simón, largando las redes en el mar, pues eran pescadores.

[[mark-1-17]]
^17^ Jesús les dijo: «Venid conmigo, y os haré llegar a ser pescadores de hombres».

[[mark-1-18]]
^18^ Al instante, dejando las redes, le siguieron.

[[mark-1-19]]
^19^ Caminando un poco más adelante, vio a Santiago, el de Zebedeo, y a su hermano Juan; estaban también en la barca arreglando las redes;

[[mark-1-20]]
^20^ y al instante los llamó. Y ellos, dejando a su padre Zebedeo en la barca con los jornaleros, se fueron tras él.

[[mark-1-21]]
^21^ Llegan a Cafarnaúm. Al llegar el sábado entró en la sinagoga y se puso a enseñar.

[[mark-1-22]]
^22^ Y quedaban asombrados de su doctrina, porque les enseñaba como quien tiene autoridad, y no como los escribas.

[[mark-1-23]]
^23^ Había precisamente en su sinagoga un hombre poseído por un espíritu inmundo, que se puso a gritar:

[[mark-1-24]]
^24^ «¿Qué tenemos nosotros contigo, Jesús de Nazaret? ¿Has venido a destruirnos? Sé quién eres tú: el Santo de Dios».

[[mark-1-25]]
^25^ Jesús, entonces, le conminó diciendo: «Cállate y sal de él».

[[mark-1-26]]
^26^ Y agitándole violentamente el espíritu inmundo, dio un fuerte grito y salió de él.

[[mark-1-27]]
^27^ Todos quedaron pasmados de tal manera que se preguntaban unos a otros: «¿Qué es esto? ¡Una doctrina nueva, expuesta con autoridad! Manda hasta a los espíritus inmundos y le obedecen».

[[mark-1-28]]
^28^ Bien pronto su fama se extendió por todas partes, en toda la región de Galilea.

[[mark-1-29]]
^29^ Cuando salió de la sinagoga se fue con Santiago y Juan a casa de Simón y Andrés.

[[mark-1-30]]
^30^ La suegra de Simón estaba en cama con fiebre; y le hablan de ella.

[[mark-1-31]]
^31^ Se acercó y, tomándola de la mano, la levantó. La fiebre la dejó y ella se puso a servirles.

[[mark-1-32]]
^32^ Al atardecer, a la puesta del sol, le trajeron todos los enfermos y endemoniados;

[[mark-1-33]]
^33^ la ciudad entera estaba agolpada a la puerta.

[[mark-1-34]]
^34^ Jesús curó a muchos que se encontraban mal de diversas enfermedades y expulsó muchos demonios. Y no dejaba hablar a los demonios, pues le conocían.

[[mark-1-35]]
^35^ De madrugada, cuando todavía estaba muy oscuro, se levantó, salió y fue a un lugar solitario y allí se puso a hacer oración.

[[mark-1-36]]
^36^ Simón y sus compañeros fueron en su busca;

[[mark-1-37]]
^37^ al encontrarle, le dicen: «Todos te buscan».

[[mark-1-38]]
^38^ El les dice: «Vayamos a otra parte, a los pueblos vecinos, para que también allí predique; pues para eso he salido».

[[mark-1-39]]
^39^ Y recorrió toda Galilea, predicando en sus sinagogas y expulsando los demonios.

[[mark-1-40]]
^40^ Se le acerca un leproso suplicándole y, puesto de rodillas, le dice: «Si quieres, puedes limpiarme».

[[mark-1-41]]
^41^ Compadecido de él, extendió su mano, le tocó y le dijo: «Quiero; queda limpio».

[[mark-1-42]]
^42^ Y al instante, le desapareció la lepra y quedó limpio.

[[mark-1-43]]
^43^ Le despidió al instante prohibiéndole severamente:

[[mark-1-44]]
^44^ «Mira, no digas nada a nadie, sino vete, muéstrate al sacerdote y haz por tu purificación la ofrenda que prescribió Moisés para que les sirva de testimonio».

[[mark-1-45]]
^45^ Pero él, así que se fue, se puso a pregonar con entusiasmo y a divulgar la noticia, de modo que ya no podía Jesús presentarse en público en ninguna ciudad, sino que se quedaba a las afueras, en lugares solitarios. Y acudían a él de todas partes.
[[mark-2]]
== Capítulo 2

[[mark-2-1]]
^1^ Entró de nuevo en Cafarnaúm; al poco tiempo había corrido la voz de que estaba en casa.

[[mark-2-2]]
^2^ Se agolparon tantos que ni siquiera ante la puerta había ya sitio, y él les anunciaba la Palabra.

[[mark-2-3]]
^3^ Y le vienen a traer a un paralítico llevado entre cuatro.

[[mark-2-4]]
^4^ Al no poder presentárselo a causa de la multitud, abrieron el techo encima de donde él estaba y, a través de la abertura que hicieron, descolgaron la camilla donde yacía el paralítico.

[[mark-2-5]]
^5^ Viendo Jesús la fe de ellos, dice al paralítico: «Hijo, tus pecados te son perdonados».

[[mark-2-6]]
^6^ Estaban allí sentados algunos escribas que pensaban en sus corazones:

[[mark-2-7]]
^7^ «¿Por qué éste habla así? Está blasfemando. ¿Quién puede perdonar pecados, sino Dios sólo?»

[[mark-2-8]]
^8^ Pero, al instante, conociendo Jesús en su espíritu lo que ellos pensaban en su interior, les dice: «¿Por qué pensáis así en vuestros corazones?

[[mark-2-9]]
^9^ ¿Qué es más fácil, decir al paralítico: “Tus pecados te son perdonados”, o decir: “Levántate, toma tu camilla y anda?”

[[mark-2-10]]
^10^ Pues para que sepáis que el Hijo del hombre tiene en la tierra poder de perdonar pecados - dice al paralítico -:

[[mark-2-11]]
^11^ “A ti te digo, levántate, toma tu camilla y vete a tu casa.”»

[[mark-2-12]]
^12^ Se levantó y, al instante, tomando la camilla, salió a la vista de todos, de modo que quedaban todos asombrados y glorificaban a Dios, diciendo: «Jamás vimos cosa parecida».

[[mark-2-13]]
^13^ Salió de nuevo por la orilla del mar, toda la gente acudía a él, y él les enseñaba.

[[mark-2-14]]
^14^ Al pasar, vio a Leví, el de Alfeo, sentado en el despacho de impuestos, y le dice: «Sígueme». El se levantó y le siguió.

[[mark-2-15]]
^15^ Y sucedió que estando él a la mesa en casa de Leví, muchos publicanos y pecadores estaban a la mesa con Jesús y sus discípulos, pues eran muchos los que le seguían.

[[mark-2-16]]
^16^ Al ver los escribas de los fariseos que comía con los pecadores y publicanos, decían a los discípulos: «¿Qué? ¿Es que come con los publicanos y pecadores?»

[[mark-2-17]]
^17^ Al oír esto Jesús, les dice: «No necesitan médico los que están fuertes, sino los que están mal; no he venido a llamar a justos, sino a pecadores».

[[mark-2-18]]
^18^ Como los discípulos de Juan y los fariseos estaban ayunando, vienen y le dicen: «¿Por qué mientras los discípulos de Juan y los discípulos de los fariseos ayunan, tus discípulos no ayunan?»

[[mark-2-19]]
^19^ Jesús les dijo: «¿Pueden acaso ayunar los invitados a la boda mientras el novio está con ellos? Mientras tengan consigo al novio no pueden ayunar.

[[mark-2-20]]
^20^ Días vendrán en que les será arrebatado el novio; entonces ayunarán, en aquel día.

[[mark-2-21]]
^21^ Nadie cose un remiendo de paño sin tundir en un vestido viejo, pues de otro modo, lo añadido tira de él, el paño nuevo del viejo, y se produce un desgarrón peor.

[[mark-2-22]]
^22^ Nadie echa tampoco vino nuevo en pellejos viejos; de otro modo, el vino reventaría los pellejos y se echaría a perder tanto el vino como los pellejos: sino que el vino nuevo, en pellejos nuevos.

[[mark-2-23]]
^23^ Y sucedió que un sábado, cruzaba Jesús por los sembrados, y sus discípulos empezaron a abrir camino arrancando espigas.

[[mark-2-24]]
^24^ Decíanle los fariseos: «Mira ¿por qué hacen en sábado lo que no es lícito?»

[[mark-2-25]]
^25^ El les dice: «¿Nunca habéis leído lo que hizo David cuando tuvo necesidad, y él y los que le acompañaban sintieron hambre,

[[mark-2-26]]
^26^ cómo entró en la Casa de Dios, en tiempos del Sumo Sacerdote Abiatar, y comió los panes de la presencia, que sólo a los sacerdotes es lícito comer, y dio también a los que estaban con él?»

[[mark-2-27]]
^27^ Y les dijo: «El sábado ha sido instituido para el hombre y no el hombre para el sábado.

[[mark-2-28]]
^28^ De suerte que el Hijo del hombre también es señor del sábado».
[[mark-3]]
== Capítulo 3

[[mark-3-1]]
^1^ Entró de nuevo en la sinagoga, y había allí un hombre que tenía la mano paralizada.

[[mark-3-2]]
^2^ Estaban al acecho a ver si le curaba en sábado para poder acusarle.

[[mark-3-3]]
^3^ Dice al hombre que tenía la mano seca: «Levántate ahí en medio».

[[mark-3-4]]
^4^ Y les dice: «¿Es lícito en sábado hacer el bien en vez del mal, salvar una vida en vez de destruirla?» Pero ellos callaban.

[[mark-3-5]]
^5^ Entonces, mirándoles con ira, apenado por la dureza de su corazón, dice al hombre: «Extiende la mano». El la extendió y quedó restablecida su mano.

[[mark-3-6]]
^6^ En cuanto salieron los fariseos, se confabularon con los herodianos contra él para ver cómo eliminarle.

[[mark-3-7]]
^7^ Jesús se retiró con sus discípulos hacia el mar, y le siguió una gran muchedumbre de Galilea. También de Judea,

[[mark-3-8]]
^8^ de Jerusalén, de Idumea, del otro lado del Jordán, de los alrededores de Tiro y Sidón, una gran muchedumbre, al oír lo que hacía, acudió a él.

[[mark-3-9]]
^9^ Entonces, a causa de la multitud, dijo a sus discípulos que le prepararan una pequeña barca, para que no le aplastaran.

[[mark-3-10]]
^10^ Pues curó a muchos, de suerte que cuantos padecían dolencias se le echaban encima para tocarle.

[[mark-3-11]]
^11^ Y los espíritus inmundos, al verle, se arrojaban a sus pies y gritaban: «Tú eres el Hijo de Dios».

[[mark-3-12]]
^12^ Pero él les mandaba enérgicamente que no le descubrieran.

[[mark-3-13]]
^13^ Subió al monte y llamó a los que él quiso; y vinieron donde él.

[[mark-3-14]]
^14^ Instituyó Doce, para que estuvieran con él, y para enviarlos a predicar

[[mark-3-15]]
^15^ con poder de expulsar los demonios.

[[mark-3-16]]
^16^ Instituyó a los Doce y puso a Simón el nombre de Pedro;

[[mark-3-17]]
^17^ a Santiago el de Zebedeo y a Juan, el hermano de Santiago, a quienes puso por nombre Boanerges, es decir, hijos del trueno;

[[mark-3-18]]
^18^ a Andrés, Felipe, Bartolomé, Mateo, Tomás, Santiago el de Alfeo, Tadeo, Simón el Cananeo

[[mark-3-19]]
^19^ y Judas Iscariote, el mismo que le entregó.

[[mark-3-20]]
^20^ Vuelve a casa. Se aglomera otra vez la muchedumbre de modo que no podían comer.

[[mark-3-21]]
^21^ Se enteraron sus parientes y fueron a hacerse cargo de él, pues decían: «Está fuera de sí».

[[mark-3-22]]
^22^ Los escribas que habían bajado de Jerusalén decían: «Está poseído por Beelzebul» y «por el príncipe de los demonios expulsa los demonios».

[[mark-3-23]]
^23^ El, llamándoles junto a sí, les decía en parábolas: «¿Cómo puede Satanás expulsar a Satanás?

[[mark-3-24]]
^24^ Si un reino está dividido contra sí mismo, ese reino no puede subsistir.

[[mark-3-25]]
^25^ Si una casa está dividida contra sí misma, esa casa no podrá subsistir.

[[mark-3-26]]
^26^ Y si Satanás se ha alzado contra sí mismo y está dividido, no puede subsistir, pues ha llegado su fin.

[[mark-3-27]]
^27^ Pero nadie puede entrar en la casa del fuerte y saquear su ajuar, si no ata primero al fuerte; entonces podrá saquear su casa.

[[mark-3-28]]
^28^ Yo os aseguro que se perdonará todo a los hijos de los hombres, los pecados y las blasfemias, por muchas que éstas sean.

[[mark-3-29]]
^29^ Pero el que blasfeme contra el Espíritu Santo, no tendrá perdón nunca, antes bien, será reo de pecado eterno».

[[mark-3-30]]
^30^ Es que decían: «Está poseído por un espíritu inmundo».

[[mark-3-31]]
^31^ Llegan su madre y sus hermanos, y quedándose fuera, le envían a llamar.

[[mark-3-32]]
^32^ Estaba mucha gente sentada a su alrededor. Le dicen: «¡Oye!, tu madre, tus hermanos y tus hermanas están fuera y te buscan».

[[mark-3-33]]
^33^ El les responde: «¿Quién es mi madre y mis hermanos?»

[[mark-3-34]]
^34^ Y mirando en torno a los que estaban sentados en corro, a su alrededor, dice: «Estos son mi madre y mis hermanos.

[[mark-3-35]]
^35^ Quien cumpla la voluntad de Dios, ése es mi hermano, mi hermana y mi madre».
[[mark-4]]
== Capítulo 4

[[mark-4-1]]
^1^ Y otra vez se puso a enseñar a orillas del mar. Y se reunió tanta gente junto a él que hubo de subir a una barca y, ya en el mar, se sentó; toda la gente estaba en tierra a la orilla del mar.

[[mark-4-2]]
^2^ Les enseñaba muchas cosas por medio de parábolas. Les decía en su instrucción:

[[mark-4-3]]
^3^ «Escuchad. Una vez salió un sembrador a sembrar.

[[mark-4-4]]
^4^ Y sucedió que, al sembrar, una parte cayó a lo largo del camino; vinieron las aves y se la comieron.

[[mark-4-5]]
^5^ Otra parte cayó en terreno pedregoso, donde no tenía mucha tierra, y brotó en seguida por no tener hondura de tierra;

[[mark-4-6]]
^6^ pero cuando salió el sol se agostó y, por no tener raíz, se secó.

[[mark-4-7]]
^7^ Otra parte cayó entre abrojos; crecieron los abrojos y la ahogaron, y no dio fruto.

[[mark-4-8]]
^8^ Otras partes cayeron en tierra buena y, creciendo y desarrollándose, dieron fruto; unas produjeron treinta, otras sesenta, otras ciento».

[[mark-4-9]]
^9^ Y decía: «Quien tenga oídos para oír, que oiga».

[[mark-4-10]]
^10^ Cuando quedó a solas, los que le seguían a una con los Doce le preguntaban sobre las parábolas.

[[mark-4-11]]
^11^ El les dijo: «A vosotros se os ha dado el misterio del Reino de Dios, pero a los que están fuera todo se les presenta en parábolas,

[[mark-4-12]]
^12^ para que por mucho que miren no vean, por mucho que oigan no entiendan, no sea que se conviertan y se les perdone».

[[mark-4-13]]
^13^ Y les dice: «¿No entendéis esta parábola? ¿Cómo, entonces, comprenderéis todas las parábolas?

[[mark-4-14]]
^14^ El sembrador siembra la Palabra.

[[mark-4-15]]
^15^ Los que están a lo largo del camino donde se siembra la Palabra son aquellos que, en cuanto la oyen, viene Satanás y se lleva la Palabra sembrada en ellos.

[[mark-4-16]]
^16^ De igual modo, los sembrados en terreno pedregoso son los que, al oír la Palabra, al punto la reciben con alegría,

[[mark-4-17]]
^17^ pero no tienen raíz en sí mismos, sino que son inconstantes; y en cuanto se presenta una tribulación o persecución por causa de la Palabra, sucumben en seguida.

[[mark-4-18]]
^18^ Y otros son los sembrados entre los abrojos; son los que han oído la Palabra,

[[mark-4-19]]
^19^ pero las preocupaciones del mundo, la seducción de las riquezas y las demás concupiscencias les invaden y ahogan la Palabra, y queda sin fruto.

[[mark-4-20]]
^20^ Y los sembrados en tierra buena son aquellos que oyen la Palabra, la acogen y dan fruto, unos treinta, otros sesenta, otros ciento».

[[mark-4-21]]
^21^ Les decía también: «¿Acaso se trae la lámpara para ponerla debajo del celemín o debajo del lecho? ¿No es para ponerla sobre el candelero?

[[mark-4-22]]
^22^ Pues nada hay oculto si no es para que sea manifestado; nada ha sucedido en secreto, sino para que venga a ser descubierto.

[[mark-4-23]]
^23^ Quien tenga oídos para oír, que oiga».

[[mark-4-24]]
^24^ Les decía también: «Atended a lo que escucháis. Con la medida con que midáis, se os medirá y aun con creces.

[[mark-4-25]]
^25^ Porque al que tiene se le dará, y al que no tiene, aun lo que tiene se le quitará».

[[mark-4-26]]
^26^ También decía: «El Reino de Dios es como un hombre que echa el grano en la tierra;

[[mark-4-27]]
^27^ duerma o se levante, de noche o de día, el grano brota y crece, sin que él sepa cómo.

[[mark-4-28]]
^28^ La tierra da el fruto por sí misma; primero hierba, luego espiga, después trigo abundante en la espiga.

[[mark-4-29]]
^29^ Y cuando el fruto lo admite, en seguida se le mete la hoz, porque ha llegado la siega».

[[mark-4-30]]
^30^ Decía también: «¿Con qué compararemos el Reino de Dios o con qué parábola lo expondremos?

[[mark-4-31]]
^31^ Es como un grano de mostaza que, cuando se siembra en la tierra, es más pequeña que cualquier semilla que se siembra en la tierra;

[[mark-4-32]]
^32^ pero una vez sembrada, crece y se hace mayor que todas las hortalizas y echa ramas tan grandes que las aves del cielo anidan a su sombra».

[[mark-4-33]]
^33^ Y les anunciaba la Palabra con muchas parábolas como éstas, según podían entenderle;

[[mark-4-34]]
^34^ no les hablaba sin parábolas; pero a sus propios discípulos se lo explicaba todo en privado.

[[mark-4-35]]
^35^ Este día, al atardecer, les dice: «Pasemos a la otra orilla».

[[mark-4-36]]
^36^ Despiden a la gente y le llevan en la barca, como estaba; e iban otras barcas con él.

[[mark-4-37]]
^37^ En esto, se levantó una fuerte borrasca y las olas irrumpían en la barca, de suerte que ya se anegaba la barca.

[[mark-4-38]]
^38^ El estaba en popa, durmiendo sobre un cabezal. Le despiertan y le dicen: «Maestro, ¿no te importa que perezcamos?»

[[mark-4-39]]
^39^ El, habiéndose despertado, increpó al viento y dijo al mar: «¡Calla, enmudece!» El viento se calmó y sobrevino una gran bonanza.

[[mark-4-40]]
^40^ Y les dijo: «¿Por qué estáis con tanto miedo? ¿Cómo no tenéis fe?»

[[mark-4-41]]
^41^ Ellos se llenaron de gran temor y se decían unos a otros: «Pues ¿quién es éste que hasta el viento y el mar le obedecen?»
[[mark-5]]
== Capítulo 5

[[mark-5-1]]
^1^ Y llegaron al otro lado del mar, a la región de los gerasenos.

[[mark-5-2]]
^2^ Apenas saltó de la barca, vino a su encuentro, de entre los sepulcros, un hombre con espíritu inmundo

[[mark-5-3]]
^3^ que moraba en los sepulcros y a quien nadie podía ya tenerle atado ni siquiera con cadenas,

[[mark-5-4]]
^4^ pues muchas veces le habían atado con grillos y cadenas, pero él había roto las cadenas y destrozado los grillos, y nadie podía dominarle.

[[mark-5-5]]
^5^ Y siempre, noche y día, andaba entre los sepulcros y por los montes, dando gritos e hiriéndose con piedras.

[[mark-5-6]]
^6^ Al ver de lejos a Jesús, corrió y se postró ante él

[[mark-5-7]]
^7^ y gritó con gran voz: «¿Qué tengo yo contigo, Jesús, Hijo de Dios Altísimo? Te conjuro por Dios que no me atormentes».

[[mark-5-8]]
^8^ Es que él le había dicho: «Espíritu inmundo, sal de este hombre».

[[mark-5-9]]
^9^ Y le preguntó: «¿Cuál es tu nombre?» Le contesta: «Mi nombre es Legión, porque somos muchos».

[[mark-5-10]]
^10^ Y le suplicaba con insistencia que no los echara fuera de la región.

[[mark-5-11]]
^11^ Había allí una gran piara de puercos que pacían al pie del monte;

[[mark-5-12]]
^12^ y le suplicaron: «Envíanos a los puercos para que entremos en ellos».

[[mark-5-13]]
^13^ Y se lo permitió. Entonces los espíritus inmundos salieron y entraron en los puercos, y la piara - unos 2.0000 se arrojó al mar de lo alto del precipicio y se fueron ahogando en el mar.

[[mark-5-14]]
^14^ Los porqueros huyeron y lo contaron por la ciudad y por las aldeas; y salió la gente a ver qué era lo que había ocurrido.

[[mark-5-15]]
^15^ Llegan donde Jesús y ven al endemoniado, al que había tenido la Legión, sentado, vestido y en su sano juicio, y se llenaron de temor.

[[mark-5-16]]
^16^ Los que lo habían visto les contaron lo ocurrido al endemoniado y lo de los puercos.

[[mark-5-17]]
^17^ Entonces comenzaron a rogarle que se alejara de su término.

[[mark-5-18]]
^18^ Y al subir a la barca, el que había estado endemoniado le pedía estar con él.

[[mark-5-19]]
^19^ Pero no se lo concedió, sino que le dijo: «Vete a tu casa, donde los tuyos, y cuéntales lo que el Señor ha hecho contigo y que ha tenido compasión de ti».

[[mark-5-20]]
^20^ El se fue y empezó a proclamar por la Decápolis todo lo que Jesús había hecho con él, y todos quedaban maravillados.

[[mark-5-21]]
^21^ Jesús pasó de nuevo en la barca a la otra orilla y se aglomeró junto a él mucha gente; él estaba a la orilla del mar.

[[mark-5-22]]
^22^ Llega uno de los jefes de la sinagoga, llamado Jairo, y al verle, cae a sus pies,

[[mark-5-23]]
^23^ y le suplica con insistencia diciendo: «Mi hija está a punto de morir; ven, impón tus manos sobre ella, para que se salve y viva».

[[mark-5-24]]
^24^ Y se fue con él. Le seguía un gran gentío que le oprimía.

[[mark-5-25]]
^25^ Entonces, una mujer que padecía flujo de sangre desde hacía doce años,

[[mark-5-26]]
^26^ y que había sufrido mucho con muchos médicos y había gastado todos sus bienes sin provecho alguno, antes bien, yendo a peor,

[[mark-5-27]]
^27^ habiendo oído lo que se decía de Jesús, se acercó por detrás entre la gente y tocó su manto.

[[mark-5-28]]
^28^ Pues decía: «Si logro tocar aunque sólo sea sus vestidos, me salvaré».

[[mark-5-29]]
^29^ Inmediatamente se le secó la fuente de sangre y sintió en su cuerpo que quedaba sana del mal.

[[mark-5-30]]
^30^ Al instante, Jesús, dándose cuenta de la fuerza que había salido de él, se volvió entre la gente y decía: «¿Quién me ha tocado los vestidos?»

[[mark-5-31]]
^31^ Sus discípulos le contestaron: «Estás viendo que la gente te oprime y preguntas: “¿Quién me ha tocado?”»

[[mark-5-32]]
^32^ Pero él miraba a su alrededor para descubrir a la que lo había hecho.

[[mark-5-33]]
^33^ Entonces, la mujer, viendo lo que le había sucedido, se acercó atemorizada y temblorosa, se postró ante él y le contó toda la verdad.

[[mark-5-34]]
^34^ El le dijo: «Hija, tu fe te ha salvado; vete en paz y queda curada de tu enfermedad».

[[mark-5-35]]
^35^ Mientras estaba hablando llegan de la casa del jefe de la sinagoga unos dicendo: «Tu hija ha muerto; ¿a qué molestar ya al Maestro?»

[[mark-5-36]]
^36^ Jesús que oyó lo que habían dicho, dice al jefe de la sinagoga: «No temas; solamente ten fe».

[[mark-5-37]]
^37^ Y no permitió que nadie le acompañara, a no ser Pedro, Santiago y Juan, el hermano de Santiago.

[[mark-5-38]]
^38^ Llegan a la casa del jefe de la sinagoga y observa el alboroto, unos que lloraban y otros que daban grandes alaridos.

[[mark-5-39]]
^39^ Entra y les dice: «¿Por qué alborotáis y lloráis? La niña no ha muerto; está dormida».

[[mark-5-40]]
^40^ Y se burlaban de él. Pero él después de echar fuera a todos, toma consigo al padre de la niña, a la madre y a los suyos, y entra donde estaba la niña.

[[mark-5-41]]
^41^ Y tomando la mano de la niña, le dice: «Talitá kum», que quiere decir: «Muchacha, a ti te digo, levántate».

[[mark-5-42]]
^42^ La muchacha se levantó al instante y se puso a andar, pues tenía doce años. Quedaron fuera de sí, llenos de estupor.

[[mark-5-43]]
^43^ Y les insistió mucho en que nadie lo supiera; y les dijo que le dieran a ella de comer.
[[mark-6]]
== Capítulo 6

[[mark-6-1]]
^1^ Salió de allí y vino a su patria, y sus discípulos le siguen.

[[mark-6-2]]
^2^ Cuando llegó el sábado se puso a enseñar en la sinagoga. La multitud, al oírle, quedaba maravillada, y decía: «¿De dónde le viene esto? y ¿qué sabiduría es ésta que le ha sido dada? ¿Y esos milagros hechos por sus manos?

[[mark-6-3]]
^3^ ¿No es éste el carpintero, el hijo de María y hermano de Santiago, Joset, Judas y Simón? ¿Y no están sus hermanas aquí entre nosotros?» Y se escandalizaban a causa de él.

[[mark-6-4]]
^4^ Jesús les dijo: «Un profeta sólo en su patria, entre sus parientes y en su casa carece de prestigio».

[[mark-6-5]]
^5^ Y no podía hacer allí ningún milagro, a excepción de unos pocos enfermos a quienes curó imponiéndoles las manos.

[[mark-6-6]]
^6^ Y se maravilló de su falta de fe. Y recorría los pueblos del contorno enseñando.

[[mark-6-7]]
^7^ Y llama a los Doce y comenzó a enviarlos de dos en dos, dándoles poder sobre los espíritus inmundos.

[[mark-6-8]]
^8^ Les ordenó que nada tomasen para el camino, fuera de un bastón: ni pan, ni alforja, ni calderilla en la faja;

[[mark-6-9]]
^9^ sino: «Calzados con sandalias y no vistáis dos túnicas».

[[mark-6-10]]
^10^ Y les dijo: «Cuando entréis en una casa, quedaos en ella hasta marchar de allí.

[[mark-6-11]]
^11^ Si algún lugar no os recibe y no os escuchan, marchaos de allí sacudiendo el polvo de la planta de vuestros pies, en testimonio contra ellos».

[[mark-6-12]]
^12^ Y, yéndose de allí, predicaron que se convirtieran;

[[mark-6-13]]
^13^ expulsaban a muchos demonios, y ungían con aceite a muchos enfermos y los curaban.

[[mark-6-14]]
^14^ Se enteró el rey Herodes, pues su nombre se había hecho célebre. Algunos decían: «Juan el Bautista ha resucitado de entre los muertos y por eso actúan en él fuerzas milagrosas».

[[mark-6-15]]
^15^ Otros decían: «Es Elías»; otros: «Es un profeta como los demás profetas».

[[mark-6-16]]
^16^ Al enterarse Herodes, dijo: «Aquel Juan, a quien yo decapité, ése ha resucitado».

[[mark-6-17]]
^17^ Es que Herodes era el que había enviado a prender a Juan y le había encadenado en la cárcel por causa de Herodías, la mujer de su hermano Filipo, con quien Herodes se había casado.

[[mark-6-18]]
^18^ Porque Juan decía a Herodes: «No te está permitido tener la mujer de tu hermano».

[[mark-6-19]]
^19^ Herodías le aborrecía y quería matarle, pero no podía,

[[mark-6-20]]
^20^ pues Herodes temía a Juan, sabiendo que era hombre justo y santo, y le protegía; y al oírle, quedaba muy perplejo, y le escuchaba con gusto.

[[mark-6-21]]
^21^ Y llegó el día oportuno, cuando Herodes, en su cumpleaños, dio un banquete a sus magnates, a los tribunos y a los principales de Galilea.

[[mark-6-22]]
^22^ Entró la hija de la misma Herodías, danzó, y gustó mucho a Herodes y a los comensales. El rey, entonces, dijo a la muchacha: «Pídeme lo que quieras y te lo daré».

[[mark-6-23]]
^23^ Y le juró: «Te daré lo que me pidas, hasta la mitad de mi reino».

[[mark-6-24]]
^24^ Salió la muchacha y preguntó a su madre: «¿Qué voy a pedir?» Y ella le dijo: «La cabeza de Juan el Bautista».

[[mark-6-25]]
^25^ Entrando al punto apresuradamente adonde estaba el rey, le pidió: «Quiero que ahora mismo me des, en una bandeja, la cabeza de Juan el Bautista».

[[mark-6-26]]
^26^ El rey se llenó de tristeza, pero no quiso desairarla a causa del juramento y de los comensales.

[[mark-6-27]]
^27^ Y al instante mandó el rey a uno de su guardia, con orden de traerle la cabeza de Juan. Se fue y le decapitó en la cárcel

[[mark-6-28]]
^28^ y trajo su cabeza en una bandeja, y se la dio a la muchacha, y la muchacha se la dio a su madre.

[[mark-6-29]]
^29^ Al enterarse sus discípulos, vinieron a recoger el cadáver y le dieron sepultura.

[[mark-6-30]]
^30^ Los apóstoles se reunieron con Jesús y le contaron todo lo que habían hecho y lo que habían enseñado.

[[mark-6-31]]
^31^ El, entonces, les dice: «Venid también vosotros aparte, a un lugar solitario, para descansar un poco». Pues los que iban y venían eran muchos, y no les quedaba tiempo ni para comer.

[[mark-6-32]]
^32^ Y se fueron en la barca, aparte, a un lugar solitario.

[[mark-6-33]]
^33^ Pero les vieron marcharse y muchos cayeron en cuenta; y fueron allá corriendo, a pie, de todas las ciudades y llegaron antes que ellos.

[[mark-6-34]]
^34^ Y al desembarcar, vio mucha gente, sintió compasión de ellos, pues estaban como ovejas que no tienen pastor, y se puso a enseñarles muchas cosas.

[[mark-6-35]]
^35^ Era ya una hora muy avanzada cuando se le acercaron sus discípulos y le dijeron: «El lugar está deshabitado y ya es hora avanzada.

[[mark-6-36]]
^36^ Despídelos para que vayan a las aldeas y pueblos del contorno a comprarse de comer».

[[mark-6-37]]
^37^ El les contestó: «Dadles vosotros de comer». Ellos le dicen: «¿Vamos nosotros a comprar doscientos denarios de pan para darles de comer?»

[[mark-6-38]]
^38^ El les dice: «¿Cuántos panes tenéis? Id a ver». Después de haberse cerciorado, le dicen: «Cinco, y dos peces».

[[mark-6-39]]
^39^ Entonces les mandó que se acomodaran todos por grupos sobre la verde hierba.

[[mark-6-40]]
^40^ Y se acomodaron por grupos de cien y de cincuenta.

[[mark-6-41]]
^41^ Y tomando los cinco panes y los dos peces, y levantando los ojos al cielo, pronunció la bendición, partió los panes y los iba dando a los discípulos para que se los fueran sirviendo. También repartió entre todos los dos peces.

[[mark-6-42]]
^42^ Comieron todos y se saciaron.

[[mark-6-43]]
^43^ Y recogieron las sobras, doce canastos llenos y también lo de los peces.

[[mark-6-44]]
^44^ Los que comieron los panes fueron 5.000 hombres.

[[mark-6-45]]
^45^ Inmediatamente obligó a sus discípulos a subir a la barca y a ir por delante hacia Betsaida, mientras él despedía a la gente.

[[mark-6-46]]
^46^ Después de despedirse de ellos, se fue al monte a orar.

[[mark-6-47]]
^47^ Al atardecer, estaba la barca en medio del mar y él, solo, en tierra.

[[mark-6-48]]
^48^ Viendo que ellos se fatigaban remando, pues el viento les era contrario, a eso de la cuarta vigilia de la noche viene hacia ellos caminando sobre el mar y quería pasarles de largo.

[[mark-6-49]]
^49^ Pero ellos viéndole caminar sobre el mar, creyeron que era un fantasma y se pusieron a gritar,

[[mark-6-50]]
^50^ pues todos le habían visto y estaban turbados. Pero él, al instante, les habló, diciéndoles: «¡Animo!, que soy yo, no temáis».

[[mark-6-51]]
^51^ Subió entonces donde ellos a la barca, y amainó el viento, y quedaron en su interior completamente estupefactos,

[[mark-6-52]]
^52^ pues no habían entendido lo de los panes, sino que su mente estaba embotada.

[[mark-6-53]]
^53^ Terminada la travesía, llegaron a tierra en Genesaret y atracaron.

[[mark-6-54]]
^54^ Apenas desembarcaron, le reconocieron en seguida,

[[mark-6-55]]
^55^ recorrieron toda aquella región y comenzaron a traer a los enfermos en camillas adonde oían que él estaba.

[[mark-6-56]]
^56^ Y dondequiera que entraba, en pueblos, ciudades o aldeas, colocaban a los enfermos en las plazas y le pedían que tocaran siquiera la orla de su manto; y cuantos la tocaron quedaban salvados.
[[mark-7]]
== Capítulo 7

[[mark-7-1]]
^1^ Se reúnen junto a él los fariseos, así como algunos escribas venidos de Jerusalén.

[[mark-7-2]]
^2^ Y al ver que algunos de sus discípulos comían con manos impuras, es decir no lavadas,

[[mark-7-3]]
^3^ - es que los fariseos y todos los judíos no comen sin haberse lavado las manos hasta el codo, aferrados a la tradición de los antiguos,

[[mark-7-4]]
^4^ y al volver de la plaza, si no se bañan, no comen; y hay otras muchas cosas que observan por tradición, como la purificación de copas, jarros y bandejas -.

[[mark-7-5]]
^5^ Por ello, los fariseos y los escribas le preguntan: «¿Por qué tus discípulos no viven conforme a la tradición de los antepasados, sino que comen con manos impuras?»

[[mark-7-6]]
^6^ El les dijo: «Bien profetizó Isaías de vosotros, hipócritas, según está escrito: Este pueblo me honra con los labios, pero su corazón está lejos de mí.

[[mark-7-7]]
^7^ En vano me rinden culto, ya que enseñan doctrinas que son preceptos de hombres.

[[mark-7-8]]
^8^ Dejando el precepto de Dios, os aferráis a la tradición de los hombres».

[[mark-7-9]]
^9^ Les decía también: «¡Qué bien violáis el mandamiento de Dios, para conservar vuestra tradición!

[[mark-7-10]]
^10^ Porque Moisés dijo: Honra a tu padre y a tu madre y: el que maldiga a su padre o a su madre, sea castigado con la muerte. Pero vosotros decís:

[[mark-7-11]]
^11^ Si uno dice a su padre o a su madre: “Lo que de mí podrías recibir como ayuda lo declaro Korbán - es decir: ofrenda -”,

[[mark-7-12]]
^12^ ya no le dejáis hacer nada por su padre y por su madre,

[[mark-7-13]]
^13^ anulando así la Palabra de Dios por vuestra tradición que os habéis transmitido; y hacéis muchas cosas semejantes a éstas».

[[mark-7-14]]
^14^ Llamó otra vez a la gente y les dijo: «Oídme todos y entended.

[[mark-7-15]]
^15^ Nada hay fuera del hombre que, entrando en él, pueda contaminarle; sino lo que sale del hombre, eso es lo que contamina al hombre.

[[mark-7-16]]
^16^ Quien tenga oídos para oír, que oiga».

[[mark-7-17]]
^17^ Y cuando, apartándose de la gente, entró en casa, sus discípulos le preguntaban sobre la parábola.

[[mark-7-18]]
^18^ El les dijo: «¿Conque también vosotros estáis sin inteligencia? ¿No comprendéis que todo lo que de fuera entra en el hombre no puede contaminarle,

[[mark-7-19]]
^19^ pues no entra en su corazón, sino en el vientre y va a parar al excusado?» - así declaraba puros todos los alimentos -.

[[mark-7-20]]
^20^ Y decía: «Lo que sale del hombre, eso es lo que contamina al hombre.

[[mark-7-21]]
^21^ Porque de dentro, del corazón de los hombres, salen las intenciones malas: fornicaciones, robos, asesinatos,

[[mark-7-22]]
^22^ adulterios, avaricias, maldades, fraude, libertinaje, envidia, injuria, insolencia, insensatez.

[[mark-7-23]]
^23^ Todas estas perversidades salen de dentro y contaminan al hombre».

[[mark-7-24]]
^24^ Y partiendo de allí, se fue a la región de Tiro, y entrando en una casa quería que nadie lo supiese, pero no logró pasar inadvertido,

[[mark-7-25]]
^25^ sino que, en seguida, habiendo oído hablar de él una mujer, cuya hija estaba poseída de un espíritu inmundo, vino y se postró a sus pies.

[[mark-7-26]]
^26^ Esta mujer era pagana, sirofenicia de nacimiento, y le rogaba que expulsara de su hija al demonio.

[[mark-7-27]]
^27^ El le decía: «Espera que primero se sacien los hijos, pues no está bien tomar el pan de los hijos y echárselo a los perritos».

[[mark-7-28]]
^28^ Pero ella le respondió: «Sí, Señor; que también los perritos comen bajo la mesa migajas de los niños».

[[mark-7-29]]
^29^ El, entonces, le dijo: «Por lo que has dicho, vete; el demonio ha salido de tu hija».

[[mark-7-30]]
^30^ Volvió a su casa y encontró que la niña estaba echada en la cama y que el demonio se había ido.

[[mark-7-31]]
^31^ Se marchó de la región de Tiro y vino de nuevo, por Sidón, al mar de Galilea, atravesando la Decápolis.

[[mark-7-32]]
^32^ Le presentan un sordo que, además, hablaba con dificultad, y le ruegan imponga la mano sobre él.

[[mark-7-33]]
^33^ El, apartándole de la gente, a solas, le metió sus dedos en los oídos y con su saliva le tocó la lengua.

[[mark-7-34]]
^34^ Y, levantando los ojos al cielo, dio un gemido, y le dijo: «Effatá», que quiere decir: «¡Abrete!»

[[mark-7-35]]
^35^ Se abrieron sus oídos y, al instante, se soltó la atadura de su lengua y hablaba correctamente.

[[mark-7-36]]
^36^ Jesús les mandó que a nadie se lo contaran. Pero cuanto más se lo prohibía, tanto más ellos lo publicaban.

[[mark-7-37]]
^37^ Y se maravillaban sobremanera y decían «Todo lo ha hecho bien; hace oír a los sordos y hablar a los mudos».
[[mark-8]]
== Capítulo 8

[[mark-8-1]]
^1^ Por aquellos días, habiendo de nuevo mucha gente y no teniendo qué comer, llama Jesús a sus discípulos y les dice:

[[mark-8-2]]
^2^ «Siento compasión de esta gente, porque hace ya tres días que permanecen conmigo y no tienen qué comer.

[[mark-8-3]]
^3^ Si los despido en ayunas a sus casas, desfallecerán en el camino, y algunos de ellos han venido de lejos».

[[mark-8-4]]
^4^ Sus discípulos le respondieron: «¿Cómo podrá alguien saciar de pan a éstos aquí en el desierto?»

[[mark-8-5]]
^5^ El les preguntaba: «¿Cuántos panes tenéis?» Ellos le respondieron: «Siete».

[[mark-8-6]]
^6^ Entonces él mandó a la gente acomodarse sobre la tierra y, tomando los siete panes y dando gracias, los partió e iba dándolos a sus discípulos para que los sirvieran, y ellos los sirvieron a la gente.

[[mark-8-7]]
^7^ Tenían también unos pocos pececillos. Y, pronunciando la bendición sobre ellos, mandó que también los sirvieran.

[[mark-8-8]]
^8^ Comieron y se saciaron, y recogieron de los trozos sobrantes siete espuertas.

[[mark-8-9]]
^9^ Fueron unos 4.000; y Jesús los despidió.

[[mark-8-10]]
^10^ Subió a continuación a la barca con sus discípulos y se fue a la región de Dalmanutá.

[[mark-8-11]]
^11^ Y salieron los fariseos y comenzaron a discutir con él, pidiéndole una señal del cielo, con el fin de ponerle a prueba.

[[mark-8-12]]
^12^ Dando un profundo gemido desde lo íntimo de su ser, dice: «¿Por qué esta generación pide una señal? Yo os aseguro: no se dará, a esta generación ninguna señal».

[[mark-8-13]]
^13^ Y, dejándolos, se embarcó de nuevo, y se fue a la orilla opuesta.

[[mark-8-14]]
^14^ Se habían olvidado de tomar panes, y no llevaban consigo en la barca más que un pan.

[[mark-8-15]]
^15^ El les hacía esta advertencia: «Abrid los ojos y guardaos de la levadura de los fariseos y de la levadura de Herodes».

[[mark-8-16]]
^16^ Ellos hablaban entre sí que no tenían panes.

[[mark-8-17]]
^17^ Dándose cuenta, les dice: «¿Por qué estáis hablando de que no tenéis panes? ¿Aún no comprendéis ni entendéis? ¿Es que tenéis la mente embotada?

[[mark-8-18]]
^18^ ¿Teniendo ojos no véis y teniendo oídos no oís? ¿No os acordáis de

[[mark-8-19]]
^19^ cuando partí los cinco panes para los 5.000? ¿Cuántos canastos llenos de trozos recogisteis?» «Doce», le dicen.

[[mark-8-20]]
^20^ «Y cuando partí los siete entre los 4.000, ¿cuántas espuertas llenas de trozos recogisteis?» Le dicen: «Siete».

[[mark-8-21]]
^21^ Y continuó: «¿Aún no entendéis?»

[[mark-8-22]]
^22^ Llegan a Betsaida. Le presentan un ciego y le suplican que le toque.

[[mark-8-23]]
^23^ Tomando al ciego de la mano, le sacó fuera del pueblo, y habiéndole puesto saliva en los ojos, le impuso las manos y le preguntaba: «¿Ves algo?»

[[mark-8-24]]
^24^ El, alzando la vista, dijo: «Veo a los hombres, pues los veo como árboles, pero que andan».

[[mark-8-25]]
^25^ Después, le volvió a poner las manos en los ojos y comenzó a ver perfectamente y quedó curado, de suerte que veía de lejos claramente todas las cosas.

[[mark-8-26]]
^26^ Y le envió a su casa, diciéndole: «Ni siquiera entres en el pueblo».

[[mark-8-27]]
^27^ Salió Jesús con sus discípulos hacia los pueblos de Cesarea de Filipo, y por el camino hizo esta pregunta a sus discípulos: «¿Quién dicen los hombres que soy yo?»

[[mark-8-28]]
^28^ Ellos le dijeron: «Unos, que Juan el Bautista; otros, que Elías; otros, que uno de los profetas».

[[mark-8-29]]
^29^ Y él les preguntaba: «Y vosotros, ¿quién decís que soy yo?» Pedro le contesta: «Tú eres el Cristo».

[[mark-8-30]]
^30^ Y les mandó enérgicamente que a nadie hablaran acerca de él.

[[mark-8-31]]
^31^ Y comenzó a enseñarles que el Hijo del hombre debía sufrir mucho y ser reprobado por los ancianos, los sumos sacerdotes y los escribas, ser matado y resucitar a los tres días.

[[mark-8-32]]
^32^ Hablaba de esto abiertamente. Tomándole aparte, Pedro, se puso a reprenderle.

[[mark-8-33]]
^33^ Pero él, volviéndose y mirando a sus discípulos, reprendió a Pedro, diciéndole: «¡Quítate de mi vista, Satanás! porque tus pensamientos no son los de Dios, sino los de los hombres».

[[mark-8-34]]
^34^ Llamando a la gente a la vez que a sus discípulos, les dijo: «Si alguno quiere venir en pos de mí, niéguese a sí mismo, tome su cruz y sígame.

[[mark-8-35]]
^35^ Porque quien quiera salvar su vida, la perderá; pero quien pierda su vida por mí y por el Evangelio, la salvará.

[[mark-8-36]]
^36^ Pues ¿de qué le sirve al hombre ganar el mundo entero si arruina su vida?

[[mark-8-37]]
^37^ Pues ¿qué puede dar el hombre a cambio de su vida?

[[mark-8-38]]
^38^ Porque quien se avergüence de mí y de mis palabras en esta generación adúltera y pecadora, también el Hijo del hombre se avergonzará de él cuando venga en la gloria de su Padre con los santos ángeles».
[[mark-9]]
== Capítulo 9

[[mark-9-1]]
^1^ Les decía también: «Yo os aseguro que entre los aquí presentes hay algunos que no gustarán la muerte hasta que vean venir con poder el Reino de Dios».

[[mark-9-2]]
^2^ Seis días después, toma Jesús consigo a Pedro, Santiago y Juan, y los lleva, a ellos solos, aparte, a un monte alto. Y se transfiguró delante de ellos,

[[mark-9-3]]
^3^ y sus vestidos se volvieron resplandecientes, muy blancos, tanto que ningún batanero en la tierra sería capaz de blanquearlos de ese modo.

[[mark-9-4]]
^4^ Se les aparecieron Elías y Moisés, y conversaban con Jesús.

[[mark-9-5]]
^5^ Toma la palabra Pedro y dice a Jesús: «Rabbí, bueno es estarnos aquí. Vamos a hacer tres tiendas, una para ti, otra para Moisés y otra para Elías»;

[[mark-9-6]]
^6^ - pues no sabía qué responder ya que estaban atemorizados -.

[[mark-9-7]]
^7^ Entonces se formó una nube que les cubrió con su sombra, y vino una voz desde la nube: «Este es mi Hijo amado, escuchadle».

[[mark-9-8]]
^8^ Y de pronto, mirando en derredor, ya no vieron a nadie más que a Jesús solo con ellos.

[[mark-9-9]]
^9^ Y cuando bajaban del monte les ordenó que a nadie contasen lo que habían visto hasta que el Hijo del hombre resucitara de entre los muertos.

[[mark-9-10]]
^10^ Ellos observaron esta recomendación, discutiendo entre sí qué era eso de «resucitar de entre los muertos».

[[mark-9-11]]
^11^ Y le preguntaban: «¿Por qué dicen los escribas que Elías debe venir primero?»

[[mark-9-12]]
^12^ El les contestó: «Elías vendrá primero y restablecerá todo; mas, ¿cómo está escrito del Hijo del hombre que sufrirá mucho y que será despreciado?

[[mark-9-13]]
^13^ Pues bien, yo os digo: Elías ha venido ya y han hecho con él cuanto han querido, según estaba escrito de él».

[[mark-9-14]]
^14^ Al llegar donde los discípulos, vio a mucha gente que les rodeaba y a unos escribas que discutían con ellos.

[[mark-9-15]]
^15^ Toda la gente, al verle, quedó sorprendida y corrieron a saludarle.

[[mark-9-16]]
^16^ El les preguntó: «¿De qué discutís con ellos?»

[[mark-9-17]]
^17^ Uno de entre la gente le respondió: «Maestro, te he traído a mi hijo que tiene un espíritu mudo

[[mark-9-18]]
^18^ y, dondequiera que se apodera de él, le derriba, le hace echar espurnarajos, rechinar de dientes y le deja rígido. He dicho a tus discípulos que lo expulsaran, pero no han podido».

[[mark-9-19]]
^19^ El les responde: «¡Oh generación incrédula! ¿Hasta cuándo estaré con vosotros? ¿Hasta cuándo habré de soportaros? ¡Traédmelo!»

[[mark-9-20]]
^20^ Y se lo trajeron. Apenas el espíritu vio a Jesús, agitó violentamente al muchacho y, cayendo en tierra, se revolcaba echando espumarajos.

[[mark-9-21]]
^21^ Entonces él preguntó a su padre: «¿Cuánto tiempo hace que le viene sucediendo esto?» Le dijo: «Desde niño.

[[mark-9-22]]
^22^ Y muchas veces le ha arrojado al fuego y al agua para acabar con él; pero, si algo puedes, ayúdanos, compadécete de nosotros».

[[mark-9-23]]
^23^ Jesús le dijo: «¡Qué es eso de si puedes! ¡Todo es posible para quien cree!»

[[mark-9-24]]
^24^ Al instante, gritó el padre del muchacho: «¡Creo, ayuda a mi poca fe!»

[[mark-9-25]]
^25^ Viendo Jesús que se agolpaba la gente, increpó al espíritu inmundo, diciéndole: «Espíritu sordo y mudo, yo te lo mando: sal de él y no entres más en él».

[[mark-9-26]]
^26^ Y el espíritu salió dando gritos y agitándole con violencia. El muchacho quedó como muerto, hasta el punto de que muchos decían que había muerto.

[[mark-9-27]]
^27^ Pero Jesús, tomándole de la mano, le levantó y él se puso en pie.

[[mark-9-28]]
^28^ Cuando Jesús entró en casa, le preguntaban en privado sus discípulos: «¿Por qué nosotros no pudimos expulsarle?»

[[mark-9-29]]
^29^ Les dijo: «Esta clase con nada puede ser arrojada sino con la oración».

[[mark-9-30]]
^30^ Y saliendo de allí, iban caminando por Galilea; él no quería que se supiera,

[[mark-9-31]]
^31^ porque iba enseñando a sus discípulos. Les decía: «El Hijo del hombre será entregado en manos de los hombres; le matarán y a los tres días de haber muerto resucitará».

[[mark-9-32]]
^32^ Pero ellos no entendían lo que les decía y temían preguntarle.

[[mark-9-33]]
^33^ Llegaron a Cafarnaúm, y una vez en casa, les preguntaba: «¿De qué discutíais por el camino?»

[[mark-9-34]]
^34^ Ellos callaron, pues por el camino habían discutido entre sí quién era el mayor.

[[mark-9-35]]
^35^ Entonces se sentó, llamó a los Doce, y les dijo: «Si uno quiere ser el primero, sea el último de todos y el servidor de todos».

[[mark-9-36]]
^36^ Y tomando un niño, le puso en medio de ellos, le estrechó entre sus brazos y les dijo:

[[mark-9-37]]
^37^ «El que reciba a un niño como éste en mi nombre, a mí me recibe; y el que me reciba a mí, no me recibe a mí sino a Aquel que me ha enviado».

[[mark-9-38]]
^38^ Juan le dijo: «Maestro, hemos visto a uno que expulsaba demonios en tu nombre y no viene con nosotros y tratamos de impedírselo porque no venía con nosotros».

[[mark-9-39]]
^39^ Pero Jesús dijo: «No se lo impidáis, pues no hay nadie que obre un milagro invocando mi nombre y que luego sea capaz de hablar mal de mí.

[[mark-9-40]]
^40^ Pues el que no está contra nosotros, está por nosotros».

[[mark-9-41]]
^41^ «Todo aquel que os dé de beber un vaso de agua por el hecho de que sois de Cristo, os aseguro que no perderá su recompensa».

[[mark-9-42]]
^42^ «Y al que escandalice a uno de estos pequeños que creen, mejor le es que le pongan al cuello una de esas piedras de molino que mueven los asnos y que le echen al mar.

[[mark-9-43]]
^43^ Y si tu mano te es ocasión de pecado, córtatela. Más vale que entres manco en la Vida que, con las dos manos, ir a la gehenna, al fuego que no se apaga.

[[mark-9-45]]
^45^ Y si tu pie te es ocasión de pecado, córtatelo. Más vale que entres cojo en la Vida que, con los dos pies, ser arrojado a la gehenna.

[[mark-9-47]]
^47^ Y si tu ojo te es ocasión de pecado, sácatelo. Más vale que entres con un solo ojo en el Reino de Dios que, con los dos ojos, ser arrojado a la gehenna,

[[mark-9-48]]
^48^ donde su gusano no muere y el fuego no se apaga;

[[mark-9-49]]
^49^ pues todos han de ser salados con fuego.

[[mark-9-50]]
^50^ Buena es la sal; mas si la sal se vuelve insípida, ¿con qué la sazonaréis? Tened sal en vosotros y tened paz unos con otros».
[[mark-10]]
== Capítulo 10

[[mark-10-1]]
^1^ Y levantándose de allí va a la región de Judea, y al otro lado del Jordán, y de nuevo vino la gente donde él y, como acostumbraba, les enseñaba.

[[mark-10-2]]
^2^ Se acercaron unos fariseos que, para ponerle a prueba, preguntaban: «¿Puede el marido repudiar a la mujer?»

[[mark-10-3]]
^3^ El les respondió: ¿Qué os prescribió Moisés?»

[[mark-10-4]]
^4^ Ellos le dijeron: «Moisés permitió escribir el acta de divorcio y repudiarla».

[[mark-10-5]]
^5^ Jesús les dijo: «Teniendo en cuenta la dureza de vuestro corazón escribió para vosotros este precepto.

[[mark-10-6]]
^6^ Pero desde el comienzo de la creación, El los hizo varón y hembra.

[[mark-10-7]]
^7^ Por eso dejará el hombre a su padre y a su madre,

[[mark-10-8]]
^8^ y los dos se harán una sola carne. De manera que ya no son dos, sino una sola carne.

[[mark-10-9]]
^9^ Pues bien, lo que Dios unió, no lo separe el hombre».

[[mark-10-10]]
^10^ Y ya en casa, los discípulos le volvían a preguntar sobre esto.

[[mark-10-11]]
^11^ El les dijo: «Quien repudie a su mujer y se case con otra, comete adulterio contra aquélla;

[[mark-10-12]]
^12^ y si ella repudia a su marido y se casa con otro, comete adulterio».

[[mark-10-13]]
^13^ Le presentaban unos niños para que los tocara; pero los discípulos les reñían.

[[mark-10-14]]
^14^ Mas Jesús, al ver esto, se enfadó y les dijo: «Dejad que los niños vengan a mí, no se lo impidáis, porque de los que son como éstos es el Reino de Dios.

[[mark-10-15]]
^15^ Yo os aseguro: el que no reciba el Reino de Dios como niño, no entrará en él».

[[mark-10-16]]
^16^ Y abrazaba a los niños, y los bendecía poniendo las manos sobre ellos.

[[mark-10-17]]
^17^ Se ponía ya en camino cuando uno corrió a su encuentro y arodillándose ante él, le preguntó: «Maestro bueno, ¿ qué he de hacer para tener en herencia vida eterna?»

[[mark-10-18]]
^18^ Jesús le dijo: «¿Por qué me llamas bueno? Nadie es bueno sino sólo Dios.

[[mark-10-19]]
^19^ Ya sabes los mandamientos: No mates, no cometas adulterio, no robes, no levantes falso testimonio, no seas injusto, honra a tu padre y a tu madre».

[[mark-10-20]]
^20^ El, entonces, le dijo: «Maestro, todo eso lo he guardado desde mi juventud».

[[mark-10-21]]
^21^ Jesús, fijando en él su mirada, le amó y le dijo: «Una cosa te falta: anda, cuanto tienes véndelo y dáselo a los pobres y tendrás un tesoro en el cielo; luego, ven y sígueme».

[[mark-10-22]]
^22^ Pero él, abatido por estas palabras, se marchó entristecido, porque tenía muchos bienes.

[[mark-10-23]]
^23^ Jesús, mirando a su alrededor, dice a sus discípulos: «¡Qué difícil es que los que tienen riquezas entren en el Reino de Dios!»

[[mark-10-24]]
^24^ Los discípulos quedaron sorprendidos al oírle estas palabras. Mas Jesús, tomando de nuevo la palabra, les dijo: «¡Hijos, qué difícil es entrar en el Reino de Dios!

[[mark-10-25]]
^25^ Es más fácil que un camello pase por el ojo de la aguja, que el que un rico entre en el Reino de Dios».

[[mark-10-26]]
^26^ Pero ellos se asombraban aún más y se decían unos a otros: «Y ¿quién se podrá salvar?»

[[mark-10-27]]
^27^ Jesús, mirándolos fijamente, dice: «Para los hombres, imposible; pero no para Dios, porque todo es posible para Dios».

[[mark-10-28]]
^28^ Pedro se puso a decirle: «Ya lo ves, nosotros lo hemos dejado todo y te hemos seguido».

[[mark-10-29]]
^29^ Jesús dijo: «Yo os aseguro: nadie que haya dejado casa, hermanos, hermanas, madre, padre, hijos o hacienda por mí y por el Evangelio,

[[mark-10-30]]
^30^ quedará sin recibir el ciento por uno: ahora al presente, casas, hermnanos, hermanas, madres, hijos y hacienda, con persecuciones; y en el mundo venidero, vida eterna.

[[mark-10-31]]
^31^ Pero muchos primeros serán últimos y los últimos, primeros».

[[mark-10-32]]
^32^ Iban de camino subiendo a Jerusalén, y Jesús marchaba delante de ellos; ellos estaban sorprendidos y los que le seguían tenían miedo. Tomó otra vez a los Doce y comenzó a decirles lo que le iba a suceder:

[[mark-10-33]]
^33^ «Mirad que subimos a Jerusalén, y el Hijo del hombre será entregado a los sumos sacerdotes y a los escribas; le condenarán a muerte y le entregarán a los gentiles,

[[mark-10-34]]
^34^ y se burlarán de él, le escupirán, le azotarán y le matarán, y a los tres días resucitará».

[[mark-10-35]]
^35^ Se acercan a él Santiago y Juan, los hijos de Zebedeo, y le dicen: «Maestro, queremos, nos concedas lo que te pidamos».

[[mark-10-36]]
^36^ El les dijo: «¿Qué queréis que os conceda?»

[[mark-10-37]]
^37^ Ellos le respondieron: «Concédenos que nos sentemos en tu gloria, uno a tu derecha y otro a tu izquierda».

[[mark-10-38]]
^38^ Jesús les dijo: «No sabéis lo que pedís. ¿Podéis beber la copa que yo voy a beber, o ser bautizados con el bautismo con que yo voy a ser bautizado?»

[[mark-10-39]]
^39^ Ellos le dijeron: «Sí, podemos». Jesús les dijo: «La copa que yo voy a beber, sí la beberéis y también seréis bautizados con el bautismo conque yo voy a ser bautizado;

[[mark-10-40]]
^40^ pero, sentarse a mi derecha o a mi izquierda no es cosa mía el concederlo, sino que es para quienes está preparado».

[[mark-10-41]]
^41^ Al oír esto los otros diez, empezaron a indignarse contra Santiago y Juan.

[[mark-10-42]]
^42^ Jesús, llamándoles, les dice: «Sabéis que los que son tenidos como jefes de las naciones, las dominan como señores absolutos y sus grandes las oprimen con su poder.

[[mark-10-43]]
^43^ Pero no ha de ser así entre vosotros, sino que el que quiera llegar a ser grande entre vosotros, será vuestro servidor,

[[mark-10-44]]
^44^ y el que quiera ser el primero entre vosotros, será esclavo de todos,

[[mark-10-45]]
^45^ que tampoco el Hijo del hombre ha venido a ser servido, sino a servir y a dar su vida como rescate por muchos».

[[mark-10-46]]
^46^ Llegan a Jericó. Y cuando salía de Jericó, acompañado de sus discípulos y de una gran muchedumbre, el hijo de Timeo (Bartimeo), un mendigo ciego, estaba sentado junto al camino.

[[mark-10-47]]
^47^ Al enterarse de que era Jesús de Nazaret, se puso a gritar: «¡Hijo de David, Jesús, ten compasión de mí!»

[[mark-10-48]]
^48^ Muchos le increpaban para que se callara. Pero él gritaba mucho más: «¡Hijo de David, ten compasión de mí!»

[[mark-10-49]]
^49^ Jesús se detuvo y dijo: «Llamadle». Llaman al ciego, diciéndole: «¡Animo, levántate! Te llama».

[[mark-10-50]]
^50^ Y él, arrojando su manto, dio un brinco y vino donde Jesús.

[[mark-10-51]]
^51^ Jesús, dirigiéndose a él, le dijo: «¿Qué quieres que te haga?» El ciego le dijo: «Rabbuní, ¡que vea!»

[[mark-10-52]]
^52^ Jesús le dijo: «Vete, tu fe te ha salvado». Y al instante, recobró la vista y le seguía por el camino.
[[mark-11]]
== Capítulo 11

[[mark-11-1]]
^1^ Cuando se aproximaban a Jerusalén, cerca ya de Betfagé y Betania, al pie del monte de los Olivos, envía a dos de sus discípulos,

[[mark-11-2]]
^2^ diciéndoles: «Id al pueblo que está enfrente de vosotros, y no bien entréis en él, encontraréis un pollino atado, sobre el que no ha montado todavía ningún hombre. Desatadlo y traedlo.

[[mark-11-3]]
^3^ Y si alguien os dice: “¿Por qué hacéis eso?”, decid: “El Señor lo necesita, y que lo devolverá en seguida”».

[[mark-11-4]]
^4^ Fueron y encontraron el pollino atado junto a una puerta, fuera, en la calle, y lo desataron.

[[mark-11-5]]
^5^ Algunos de los que estaban allí les dijeron: «¿Qué hacéis desatando el pollino?»

[[mark-11-6]]
^6^ Ellos les contestaron según les había dicho Jesús, y les dejaron.

[[mark-11-7]]
^7^ Traen el pollino donde Jesús, echaron encima sus mantos y se sentó sobre él.

[[mark-11-8]]
^8^ Muchos extendieron sus mantos por el camino; otros, follaje cortado de los campos.

[[mark-11-9]]
^9^ Los que iban delante y los que le seguían, gritaban: «¡Hosanna! ¡Bendito el que viene en nombre del Señor!

[[mark-11-10]]
^10^ ¡Bendito el reino que viene, de nuestro padre David! ¡Hosanna en las alturas!»

[[mark-11-11]]
^11^ Y entró en Jerusalén, en el Templo, y después de observar todo a su alrededor, siendo ya tarde, salió con los Doce para Betania.

[[mark-11-12]]
^12^ Al día siguiente, saliendo ellos de Betania, sintió hambre.

[[mark-11-13]]
^13^ Y viendo de lejos una higuera con hojas, fue a ver si encontraba algo en ella; acercándose a ella, no encontró más que hojas; es que no era tiempo de higos.

[[mark-11-14]]
^14^ Entonces le dijo: «¡Que nunca jamás coma nadie fruto de ti!» Y sus discípulos oían esto.

[[mark-11-15]]
^15^ Llegan a Jerusalén; y entrando en el Templo, comenzó a echar fuera a los que vendían y a los que compraban en el Templo; volcó las mesas de los cambistas y los puestos de los vendedores de palomas

[[mark-11-16]]
^16^ y no permitía que nadie transportase cosas por el Templo.

[[mark-11-17]]
^17^ Y les enseñaba, diciéndoles: «¿No está escrito: Mi Casa será llamada Casa de oración para todas las gentes? ¡Pero vosotros la tenéis hecha una cueva de bandidos!»

[[mark-11-18]]
^18^ Se enteraron de esto los sumos sacerdotes y los escribas y buscaban cómo podrían matarle; porque le tenían miedo, pues toda la gente estaba asombrada de su doctrina.

[[mark-11-19]]
^19^ Y al atardecer, salía fuera de la ciudad.

[[mark-11-20]]
^20^ Al pasar muy de mañana, vieron la higuera, que estaba seca hasta la raíz.

[[mark-11-21]]
^21^ Pedro, recordándolo, le dice: «¡Rabbí, mira!, la higuera que maldijiste está seca».

[[mark-11-22]]
^22^ Jesús les respondió: «Tened fe en Dios.

[[mark-11-23]]
^23^ Yo os aseguro que quien diga a este monte: “Quítate y arrójate al mar” y no vacile en su corazón sino que crea que va a suceder lo que dice, lo obtendrá.

[[mark-11-24]]
^24^ Por eso os digo: todo cuanto pidáis en la oración, creed que ya lo habéis recibido y lo obtendréis.

[[mark-11-25]]
^25^ Y cuando os pongáis de pie para orar, perdonad, si tenéis algo contra alguno, para que también vuestro Padre, que está en los cielos, os perdone vuestras ofensas».

[[mark-11-27]]
^27^ Vuelven a Jerusalén y, mientras paseaba por el Templo, se le acercan los sumos sacerdotes, los escribas y los ancianos,

[[mark-11-28]]
^28^ y le decían: «¿Con qué autoridad haces esto?, o ¿quién te ha dado tal autoridad para hacerlo?»

[[mark-11-29]]
^29^ Jesús les dijo: «Os voy a preguntar una cosa. Respondedme y os diré con qué autoridad hago esto.

[[mark-11-30]]
^30^ El bautismo de Juan, ¿era del cielo o de los hombres? Respondedme».

[[mark-11-31]]
^31^ Ellos discurrían entre sí: «Si decimos: “Del cielo”, dirá: “Entonces, ¿por qué no le creísteis?”

[[mark-11-32]]
^32^ Pero ¿vamos a decir: “De los hombres?”» Tenían miedo a la gente; pues todos tenían a Juan por un verdadero profeta.

[[mark-11-33]]
^33^ Responden, pues, a Jesús: «No sabemos». Jesús entonces les dice: «Tampoco yo os digo con qué autoridad hago esto».
[[mark-12]]
== Capítulo 12

[[mark-12-1]]
^1^ Y se puso a hablarles en parábolas: «Un hombre plantó una viña, la rodeó de una cerca, cavó un lagar y edificó una torre; la arrendó a unos labradores, y se ausentó.

[[mark-12-2]]
^2^ Envió un siervo a los labradores a su debido tiempo para recibir de ellos una parte de los frutos de la viña.

[[mark-12-3]]
^3^ Ellos le agarraron, le golpearon y le despacharon con las manos vacías.

[[mark-12-4]]
^4^ De nuevo les envió a otro siervo; también a éste le descalabraron y le insultaron.

[[mark-12-5]]
^5^ Y envió a otro y a éste le mataron; y también a otros muchos, hiriendo a unos, matando a otros.

[[mark-12-6]]
^6^ Todavía le quedaba un hijo querido; les envió a éste, el último, diciendo: “A mi hijo le respetarán”.

[[mark-12-7]]
^7^ Pero aquellos labradores dijeron entre sí: “Este es el heredero. Vamos, matémosle, y será nuestra la herencia.”

[[mark-12-8]]
^8^ Le agarraron, le mataron y le echaron fuera de la viña.

[[mark-12-9]]
^9^ ¿Qué hará el dueño de la viña? Vendrá y dará muerte a los labradores y entregará la viña a otros.

[[mark-12-10]]
^10^ ¿No habéis leído esta Escritura: La piedra que los constructores desecharon, en piedra angular se ha convertido;

[[mark-12-11]]
^11^ fue el Señor quien hizo esto y es maravilloso a nuestros ojos?»

[[mark-12-12]]
^12^ Trataban de detenerle - pero tuvieron miedo a la gente - porque habían comprendido que la parábola la había dicho por ellos. Y dejándole, se fueron.

[[mark-12-13]]
^13^ Y envían donde él algunos fariseos y herodianos, para cazarle en alguna palabra.

[[mark-12-14]]
^14^ Vienen y le dicen: «Maestro, sabemos que eres veraz y que no te importa por nadie, porque no miras la condición de las personas, sino que enseñas con franqueza el camino de Dios: ¿Es lícito pagar tributo al César o no? ¿Pagamos o dejamos de pagar?»

[[mark-12-15]]
^15^ Mas él, dándose cuenta de su hipocresía, les dijo: «¿Por qué me tentáis? Traedme un denario, que lo vea».

[[mark-12-16]]
^16^ Se lo trajeron y les dice: «¿De quién es esta imagen y la inscripción?» Ellos le dijeron: «Del César».

[[mark-12-17]]
^17^ Jesús les dijo: «Lo del César, devolvédselo al César, y lo de Dios, a Dios». Y se maravillaban de él.

[[mark-12-18]]
^18^ Se le acercan unos saduceos, esos que niegan que haya resurrección, y le preguntaban:

[[mark-12-19]]
^19^ «Maestro, Moisés nos dejó escrito que si muere el hermano de alguno y deja mujer y no deja hijos, que su hermano tome a la mujer para dar descendencia a su hermano.

[[mark-12-20]]
^20^ Eran siete hermanos: el primero tomó mujer, pero murió sin dejar descendencia;

[[mark-12-21]]
^21^ también el segundo la tomó y murió sin dejar descendencia; y el tercero lo mismo.

[[mark-12-22]]
^22^ Ninguno de los siete dejó descendencia. Después de todos, murió también la mujer.

[[mark-12-23]]
^23^ En la resurrección, cuando resuciten, ¿de cuál de ellos será mujer? Porque los siete la tuvieron por mujer».

[[mark-12-24]]
^24^ Jesús les contestó: «¿No estáis en un error precisamente por esto, por no entender las Escrituras ni el poder de Dios?

[[mark-12-25]]
^25^ Pues cuando resuciten de entre los muertos, ni ellos tomarán mujer ni ellas marido, sino que serán como ángeles en los cielos.

[[mark-12-26]]
^26^ Y acerca de que los muertos resucitan, ¿no habéis leído en el libro de Moisés, en lo de la zarza, cómo Dios le dijo: Yo soy el Dios de Abraham, el Dios de Isaac y el Dios de Jacob?

[[mark-12-27]]
^27^ No es un Dios de muertos, sino de vivos. Estáis en un gran error».

[[mark-12-28]]
^28^ Acercóse uno de los escribas que les había oído y, viendo que les había respondido muy bien, le preguntó: «¿Cuál es el primero de todos los mandamientos?»

[[mark-12-29]]
^29^ Jesús le contestó: «El primero es: Escucha, Israel: El Señor, nuestro Dios, es el único Señor,

[[mark-12-30]]
^30^ y amarás al Señor, tu Dios, con todo tu corazón, con toda tu alma, con toda tu mente y con todas tus fuerzas.

[[mark-12-31]]
^31^ El segundo es: Amarás a tu prójimo como a ti mismo. No existe otro mandamiento mayor que éstos».

[[mark-12-32]]
^32^ Le dijo el escriba: «Muy bien, Maestro; tienes razón al decir que El es único y que no hay otro fuera de El,

[[mark-12-33]]
^33^ y amarle con todo el corazón, con toda la inteligencia y con todas las fuerzas, y amar al prójimo como a si mismo vale más que todos los holocaustos y sacrificios».

[[mark-12-34]]
^34^ Y Jesús, viendo que le había contestado con sensatez, le dijo: «No estás lejos del Reino de Dios». Y nadie más se atrevía ya a hacerle preguntas.

[[mark-12-35]]
^35^ Jesús, tomando la palabra, decía mientras enseñaba en el Templo: «¿Cómo dicen los escribas que el Cristo es hijo de David?

[[mark-12-36]]
^36^ David mismo dijo, movido por el Espíritu Santo: Dijo el Señor a mi Señor: Siéntate a mi diestra hasta que ponga a tus enemigos debajo de tus pies.

[[mark-12-37]]
^37^ El mismo David le llama Señor; ¿cómo entonces puede ser hijo suyo?» La muchedumbre le oía con agrado.

[[mark-12-38]]
^38^ Decía también en su instrucción: «Guardaos de los escribas, que gustan pasear con amplio ropaje, ser saludados en las plazas,

[[mark-12-39]]
^39^ ocupar los primeros asientos en las sinagogas y los primeros puestos en los banquetes;

[[mark-12-40]]
^40^ y que devoran la hacienda de las viudas so capa de largas oraciones. Esos tendrán una sentencia más rigurosa.

[[mark-12-41]]
^41^ Jesús se sentó frente al arca del Tesoro y miraba cómo echaba la gente monedas en el arca del Tesoro: muchos ricos echaban mucho.

[[mark-12-42]]
^42^ Llegó también una viuda pobre y echó dos moneditas, o sea, una cuarta parte del as.

[[mark-12-43]]
^43^ Entonces, llamando a sus discípulos, les dijo: «Os digo de verdad que esta viuda pobre ha echado más que todos los que echan en el arca del Tesoro.

[[mark-12-44]]
^44^ Pues todos han echado de los que les sobraba, ésta, en cambio, ha echado de lo que necesitaba todo cuanto poseía, todo lo que tenía para vivir.
[[mark-13]]
== Capítulo 13

[[mark-13-1]]
^1^ Al salir del Templo, le dice uno de sus discípulos: «Maestro, mira qué piedras y qué construcciones».

[[mark-13-2]]
^2^ Jesús le dijo: «¿Ves estas grandiosas construcciones? No quedará piedra sobre piedra que no sea derruida».

[[mark-13-3]]
^3^ Estando luego sentado en el monte de los Olivos, frente al Templo, le preguntaron en privado Pedro, Santiago, Juan y Andrés:

[[mark-13-4]]
^4^ «Dinos cuándo sucederá eso, y cuál será la señal de que todas estas cosas están para cumplirse».

[[mark-13-5]]
^5^ Jesús empezó a decirles: «Mirad que no os engañe nadie.

[[mark-13-6]]
^6^ Vendrán muchos usurpando mi nombre y diciendo: “Yo soy”, y engañarán a muchos.

[[mark-13-7]]
^7^ Cuando oigáis hablar de guerras y de rumores de guerras, no os alarméis; porque eso es necesario que suceda, pero no es todavía el fin.

[[mark-13-8]]
^8^ Pues se levantará nación contra nación y reino contra reino. Habrá terremotos en diversos lugares, habrá hambre: esto será el comienzo de los dolores de alumbramiento.

[[mark-13-9]]
^9^ «Pero vosotros mirad por vosotros mismos; os entregarán a los tribunales, seréis azotados en las sinagogas y compareceréis ante gobernadores y reyes por mi causa, para que deis testimonio ante ellos.

[[mark-13-10]]
^10^ Y es preciso que antes sea proclamada la Buena Nueva a todas las naciones.

[[mark-13-11]]
^11^ «Y cuando os lleven para entregaros, no os preocupéis de qué vais a hablar; sino hablad lo que se os comunique en aquel momento. Porque no seréis vosotros los que hablaréis, sino el Espíritu Santo.

[[mark-13-12]]
^12^ Y entregará a la muerte hermano a hermano y padre a hijo; se levantarán hijos contra padres y los matarán.

[[mark-13-13]]
^13^ Y seréis odiados de todos por causa de mi nombre; pero el que persevere hasta el fin, ése se salvará.

[[mark-13-14]]
^14^ «Pero cuando veáis la abominación de la desolación erigida donde no debe (el que lea, que entienda), entonces, los que estén en Judea, huyan a los montes;

[[mark-13-15]]
^15^ el que esté en el terrado, no baje ni entre a recoger algo de su casa,

[[mark-13-16]]
^16^ y el que esté por el campo, no regrese en busca de su manto.

[[mark-13-17]]
^17^ ¡Ay de las que estén encinta o criando en aquellos días!

[[mark-13-18]]
^18^ Orad para que no suceda en invierno.

[[mark-13-19]]
^19^ Porque aquellos días habrá una tribulación cual no la hubo desde el principio de la creación, que hizo Dios, hasta el presente, ni la volverá a haber.

[[mark-13-20]]
^20^ Y si el Señor no abreviase aquellos días, no se salvaría nadie, pero en atención a los elegidos que él escogió, ha abreviado los días.

[[mark-13-21]]
^21^ Entonces, si alguno os dice: “Mirad, el Cristo aquí” “Miradlo allí”, no lo creáis.

[[mark-13-22]]
^22^ Pues surgirán falsos cristos y falsos profetas y realizarán señales y prodigios con el propósito de engañar, si fuera posible, a los elegidos.

[[mark-13-23]]
^23^ Vosotros, pues, estad sobre aviso; mirad que os lo he predicho todo.

[[mark-13-24]]
^24^ «Mas por esos días, después de aquella tribulación, el sol se oscurecerá, la luna no dará su resplandor,

[[mark-13-25]]
^25^ las estrellas irán cayendo del cielo, y las fuerzas que están en los cielos serán sacudidas.

[[mark-13-26]]
^26^ Y entonces verán al Hijo del hombre que viene entre nubes con gran poder y gloria;

[[mark-13-27]]
^27^ entonces enviará a los ángeles y reunirá de los cuatro vientos a sus elegidos, desde el extremo de la tierra hasta el extremo del cielo.

[[mark-13-28]]
^28^ «De la higuera aprended esta parábola: cuando ya sus ramas están tiernas y brotan las hojas, sabéis que el verano está cerca.

[[mark-13-29]]
^29^ Así también vosotros, cuando veáis que sucede esto, sabed que El está cerca, a las puertas.

[[mark-13-30]]
^30^ Yo os aseguro que no pasará esta generación hasta que todo esto suceda.

[[mark-13-31]]
^31^ El cielo y la tierra pasarán, pero mis palabras no pasarán.

[[mark-13-32]]
^32^ Mas de aquel día y hora, nadie sabe nada, ni los ángeles en el cielo, ni el Hijo, sino sólo el Padre.

[[mark-13-33]]
^33^ «Estad atentos y vigilad, porque ignoráis cuándo será el momento.

[[mark-13-34]]
^34^ Al igual que un hombre que se ausenta: deja su casa, da atribuciones a sus siervos, a cada uno su trabajo, y ordena al portero que vele;

[[mark-13-35]]
^35^ velad, por tanto, ya que no sabéis cuándo viene el dueño de la casa, si al atardecer, o a media noche, o al cantar del gallo, o de madrugada.

[[mark-13-36]]
^36^ No sea que llegue de improviso y os encuentre dormidos.

[[mark-13-37]]
^37^ Lo que a vosotros digo, a todos lo digo: ¡Velad!»
[[mark-14]]
== Capítulo 14

[[mark-14-1]]
^1^ Faltaban dos días para la Pascua y los Azimos. Los sumos sacerdotes y los escribas buscaban cómo prenderle con engaño y matarle.

[[mark-14-2]]
^2^ Pues decían: «Durante la fiesta no, no sea que haya alboroto del pueblo».

[[mark-14-3]]
^3^ Estando él en Betania, en casa de Simón el leproso, recostado a la mesa, vino una mujer que traía un frasco de alabastro con perfume puro de nardo, de mucho precio; quebró el frasco y lo derramó sobre su cabeza.

[[mark-14-4]]
^4^ Había algunos que se decían entre sí indignados: «¿Para qué este despilfarro de perfume?

[[mark-14-5]]
^5^ Se podía haber vendido este perfume por más de trescientos denarios y habérselo dado a los pobres». Y refunfuñaban contra ella.

[[mark-14-6]]
^6^ Mas Jesús dijo: «Dejadla. ¿Por qué la molestáis? Ha hecho una obra buena en mí.

[[mark-14-7]]
^7^ Porque pobres tendréis siempre con vosotros y podréis hacerles bien cuando queráis; pero a mí no me tendréis siempre.

[[mark-14-8]]
^8^ Ha hecho lo que ha podido. Se ha anticipado a embalsamar mi cuerpo para la sepultura.

[[mark-14-9]]
^9^ Yo os aseguro: dondequiera que se proclame la Buena Nueva, en el mundo entero, se hablará también de lo que ésta ha hecho para memoria suya».

[[mark-14-10]]
^10^ Entonces, Judas Iscariote, uno de los Doce, se fue donde los sumos sacerdotes para entregárselo.

[[mark-14-11]]
^11^ Al oírlo ellos, se alegraron y prometieron darle dinero. Y él andaba buscando cómo le entregaría en momento oportuno.

[[mark-14-12]]
^12^ El primer día de los Azimos, cuando se sacrificaba el cordero pascual, le dicen sus discípulos: «¿Dónde quieres que vayamos a hacer los preparativos para que comas el cordero de Pascua?»

[[mark-14-13]]
^13^ Entonces, envía a dos de sus discípulos y les dice: «Id a la ciudad; os saldrá al encuentro un hombre llevando un cántaro de agua; seguidle

[[mark-14-14]]
^14^ y allí donde entre, decid al dueño de la casa: “El Maestro dice: ¿Dónde está mi sala, donde pueda comer la Pascua con mis discípulos?”

[[mark-14-15]]
^15^ El os enseñará en el piso superior una sala grande, ya dispuesta y preparada; haced allí los preparativos para nosotros».

[[mark-14-16]]
^16^ Los discípulos salieron, llegaron a la ciudad, lo encontraron tal como les había dicho, y prepararon la Pascua.

[[mark-14-17]]
^17^ Y al atardecer, llega él con los Doce.

[[mark-14-18]]
^18^ Y mientras comían recostados, Jesús dijo: «Yo os aseguro que uno de vosotros me entregará, el que come conmigo».

[[mark-14-19]]
^19^ Ellos empezaron a entristecerse y a decirle uno tras otro: «¿Acaso soy yo?»

[[mark-14-20]]
^20^ El les dijo: «Uno de los Doce que moja conmigo en el mismo plato.

[[mark-14-21]]
^21^ Porque el Hijo del hombre se va, como está escrito de él, pero ¡ay de aquel por quien el Hijo del hombre es entregado! ¡Más le valdría a ese hombre no haber nacido!»

[[mark-14-22]]
^22^ Y mientras estaban comiendo, tomó pan, lo bendijo, lo partió y se lo dio y dijo: «Tomad, este es mi cuerpo».

[[mark-14-23]]
^23^ Tomó luego una copa y, dadas las gracias, se la dio, y bebieron todos de ella.

[[mark-14-24]]
^24^ Y les dijo: «Esta es mi sangre de la Alianza, que es derramada por muchos.

[[mark-14-25]]
^25^ Yo os aseguro que ya no beberé del producto de la vid hasta el día en que lo beba nuevo en el Reino de Dios».

[[mark-14-26]]
^26^ Y cantados los himnos, salieron hacia el monte de los Olivos.

[[mark-14-27]]
^27^ Jesús les dice: «Todos os vais a escandalizar, ya que está escrito: Heriré al pastor y se dispersarán las ovejas.

[[mark-14-28]]
^28^ Pero después de mi resurrección, iré delante de vosotros a Galilea».

[[mark-14-29]]
^29^ Pedro le dijo: «Aunque todos se escandalicen, yo no».

[[mark-14-30]]
^30^ Jesús le dice: «Yo te aseguro: hoy, esta misma noche, antes que el gallo cante dos veces, tú me habrás negado tres».

[[mark-14-31]]
^31^ Pero él insistía: «Aunque tenga que morir contigo, yo no te negaré». Lo mismo decían también todos.

[[mark-14-32]]
^32^ Van a una propiedad, cuyo nombre es Getsemaní, y dice a sus discípulos: «Sentaos aquí, mientras yo hago oración».

[[mark-14-33]]
^33^ Toma consigo a Pedro, Santiago y Juan, y comenzó a sentir pavor y angustia.

[[mark-14-34]]
^34^ Y les dice: «Mi alma está triste hasta el punto de morir; quedaos aquí y velad».

[[mark-14-35]]
^35^ Y adelantándose un poco, caía en tierra y suplicaba que a ser posible pasara de él aquella hora.

[[mark-14-36]]
^36^ Y decía: «¡Abbá, Padre!; todo es posible para ti; aparta de mí esta copa; pero no sea lo que yo quiero, sino lo que quieras tú».

[[mark-14-37]]
^37^ Viene entonces y los encuentra dormidos; y dice a Pedro: «Simón, ¿duermes?, ¿ni una hora has podido velar?

[[mark-14-38]]
^38^ Velad y orad, para que no caigáis en tentación; que el espíritu está pronto, pero la carne es débil».

[[mark-14-39]]
^39^ Y alejándose de nuevo, oró diciendo las mismas palabras.

[[mark-14-40]]
^40^ Volvió otra vez y los encontró dormidos, pues sus ojos estaban cargados; ellos no sabían qué contestarle.

[[mark-14-41]]
^41^ Viene por tercera vez y les dice: «Ahora ya podéis dormir y descansar. Basta ya. Llegó la hora. Mirad que el Hijo del hombre va a ser entregado en manos de los pecadores.

[[mark-14-42]]
^42^ ¡Levantaos! ¡vámonos! Mirad, el que me va a entregar está cerca».

[[mark-14-43]]
^43^ Todavía estaba hablando, cuando de pronto se presenta Judas, uno de los Doce, acompañado de un grupo con espadas y palos, de parte de los sumos sacerdotes, de los escribas y de los ancianos.

[[mark-14-44]]
^44^ El que le iba a entregar les había dado esta contraseña: «Aquel a quien yo dé un beso, ése es, prendedle y llevadle con cautela».

[[mark-14-45]]
^45^ Nada más llegar, se acerca a él y le dice: «Rabbí», y le dio un beso.

[[mark-14-46]]
^46^ Ellos le echaron mano y le prendieron.

[[mark-14-47]]
^47^ Uno de los presentes, sacando la espada, hirió al siervo del Sumo Sacerdote, y le llevó la oreja.

[[mark-14-48]]
^48^ Y tomando la palabra Jesús, les dijo: «¿Como contra un salteador habéis salido a prenderme con espadas y palos?

[[mark-14-49]]
^49^ Todos los días estaba junto a vosotros enseñando en el Templo, y no me detuvisteis. Pero es para que se cumplan las Escrituras».

[[mark-14-50]]
^50^ Y abandonándole huyeron todos.

[[mark-14-51]]
^51^ Un joven le seguía cubierto sólo de un lienzo; y le detienen.

[[mark-14-52]]
^52^ Pero él, dejando el lienzo, se escapó desnudo.

[[mark-14-53]]
^53^ Llevaron a Jesús ante el Sumo Sacerdote, y se reúnen todos los sumos sacerdotes, los ancianos y los escribas.

[[mark-14-54]]
^54^ También Pedro le siguió de lejos, hasta dentro del palacio del Sumo Sacerdote, y estaba sentado con los criados, calentándose al fuego.

[[mark-14-55]]
^55^ Los sumos sacerdotes y el Sanedrín entero andaban buscando contra Jesús un testimonio para darle muerte; pero no lo encontraban.

[[mark-14-56]]
^56^ Pues muchos daban falso testimonio contra él, pero los testimonios no coincidían.

[[mark-14-57]]
^57^ Algunos, levantándose, dieron contra él este falso testimonio:

[[mark-14-58]]
^58^ «Nosotros le oímos decir: Yo destruiré este Santuario hecho por hombres y en tres días edificaré otro no hecho por hombres».

[[mark-14-59]]
^59^ Y tampoco en este caso coincidía su testimonio.

[[mark-14-60]]
^60^ Entonces, se levantó el Sumo Sacerdote y poniéndose en medio, preguntó a Jesús: «¿No respondes nada? ¿Qué es lo que éstos atestiguan contra ti?»

[[mark-14-61]]
^61^ Pero él seguía callado y no respondía nada. El Sumo Sacerdote le preguntó de nuevo: «¿Eres tú el Cristo, el Hijo del Bendito?»

[[mark-14-62]]
^62^ Y dijo Jesús: «Sí, yo soy, y veréis al Hijo del hombre sentado a la diestra del Poder y venir entre las nubes del cielo».

[[mark-14-63]]
^63^ El Sumo Sacerdote se rasga las túnicas y dice: «¿Qué necesidad tenemos ya de testigos?

[[mark-14-64]]
^64^ Habéis oído la blasfemia. ¿Qué os parece?» Todos juzgaron que era reo de muerte.

[[mark-14-65]]
^65^ Algunos se pusieron a escupirle, le cubrían la cara y le daban bofetadas, mientras le decían: «Adivina», y los criados le recibieron a golpes.

[[mark-14-66]]
^66^ Estando Pedro abajo en el patio, llega una de las criadas del Sumo Sacerdote

[[mark-14-67]]
^67^ y al ver a Pedro calentándose, le mira atentamente y le dice: «También tú estabas con Jesús de Nazaret».

[[mark-14-68]]
^68^ Pero él lo negó: «Ni sé ni entiendo qué dices», y salió afuera, al portal, y cantó un gallo.

[[mark-14-69]]
^69^ Le vio la criada y otra vez se puso a decir a los que estaban allí: «Este es uno de ellos».

[[mark-14-70]]
^70^ Pero él lo negaba de nuevo. Poco después, los que estaban allí volvieron a decir a Pedro: «Ciertamente eres de ellos pues además eres galileo».

[[mark-14-71]]
^71^ Pero él, se puso a echar imprecaciones y a jurar: «¡Yo no conozco a ese hombre de quien habláis!»

[[mark-14-72]]
^72^ Inmediatamente cantó un gallo por segunda vez. Y Pedro recordó lo que le había dicho Jesús: «Antes que el gallo cante dos veces, me habrás negado tres». Y rompió a llorar.
[[mark-15]]
== Capítulo 15

[[mark-15-1]]
^1^ Pronto, al amanecer, prepararon una reunión los sumos sacerdotes con los ancianos, los escribas y todo el Sanedrín y, después de haber atado a Jesús, le llevaron y le entregaron a Pilato.

[[mark-15-2]]
^2^ Pilato le preguntaba: «¿Eres tú el Rey de los judíos?» El le respondió: «Sí, tú lo dices».

[[mark-15-3]]
^3^ Los sumos sacerdotes le acusaban de muchas cosas.

[[mark-15-4]]
^4^ Pilato volvió a preguntarle: «¿No contestas nada? Mira de cuántas cosas te acusan».

[[mark-15-5]]
^5^ Pero Jesús no respondió ya nada, de suerte que Pilato estaba sorprendido.

[[mark-15-6]]
^6^ Cada Fiesta les concedía la libertad de un preso, el que pidieran.

[[mark-15-7]]
^7^ Había uno, llamado Barrabás, que estaba encarcelado con aquellos sediciosos que en el motín habían cometido un asesinato.

[[mark-15-8]]
^8^ Subió la gente y se puso a pedir lo que les solía conceder.

[[mark-15-9]]
^9^ Pilato les contestó: «¿Queréis que os suelte al Rey de los judíos?»

[[mark-15-10]]
^10^ (Pues se daba cuenta de que los sumos sacerdotes le habían entregado por envidia.)

[[mark-15-11]]
^11^ Pero los sumos sacerdotes incitaron a la gente a que dijeran que les soltase más bien a Barrabás.

[[mark-15-12]]
^12^ Pero Pilato les decía otra vez: «Y ¿qué voy a hacer con el que llamáis el Rey de los judíos?»

[[mark-15-13]]
^13^ La gente volvió a gritar: «¡Crucifícale!»

[[mark-15-14]]
^14^ Pilato les decía: «Pero ¿qué mal ha hecho?» Pero ellos gritaron con más fuerza: «Crucifícale!»

[[mark-15-15]]
^15^ Pilato, entonces, queriendo complacer a la gente, les soltó a Barrabás y entregó a Jesús, después de azotarle, para que fuera crucificado.

[[mark-15-16]]
^16^ Los soldados le llevaron dentro del palacio, es decir, al pretorio y llaman a toda la cohorte.

[[mark-15-17]]
^17^ Le visten de púrpura y, trenzando una corona de espinas, se la ciñen.

[[mark-15-18]]
^18^ Y se pusieron a saludarle: «¡Salve, Rey de los judíos!»

[[mark-15-19]]
^19^ Y le golpeaban en la cabeza con una caña, le escupían y, doblando las rodillas, se postraban ante él.

[[mark-15-20]]
^20^ Cuando se hubieron burlado de él, le quitaron la púrpura, le pusieron sus ropas y le sacan fuera para crucificarle.

[[mark-15-21]]
^21^ Y obligaron a uno que pasaba, a Simón de Cirene, que volvía del campo, el padre de Alejandro y de Rufo, a que llevara su cruz.

[[mark-15-22]]
^22^ Le conducen al lugar del Gólgota, que quiere decir: Calvario.

[[mark-15-23]]
^23^ Le daban vino con mirra, pero él no lo tomó.

[[mark-15-24]]
^24^ Le crucifican y se reparten sus vestidos, echando a suertes a ver qué se llevaba cada uno.

[[mark-15-25]]
^25^ Era la hora tercia cuando le crucificaron.

[[mark-15-26]]
^26^ Y estaba puesta la inscripción de la causa de su condena: «El Rey de los judíos».

[[mark-15-27]]
^27^ Con él crucificaron a dos salteadores, uno a su derecha y otro a su izquierda.

[[mark-15-29]]
^29^ Y los que pasaban por allí le insultaban, meneando la cabeza y diciendo: «¡Eh, tú!, que destruyes el Santuario y lo levantas en tres días,

[[mark-15-30]]
^30^ ¡sálvate a ti mismo bajando de la cruz!»

[[mark-15-31]]
^31^ Igualmente los sumos sacerdotes se burlaban entre ellos junto con los escribas diciendo: «A otros salvó y a sí mismo no puede salvarse.

[[mark-15-32]]
^32^ ¡El Cristo, el Rey de Israel!, que baje ahora de la cruz, para que lo veamos y creamos». También le injuriaban los que con él estaban crucificados.

[[mark-15-33]]
^33^ Llegada la hora sexta, hubo oscuridad sobre toda la tierra hasta la hora nona.

[[mark-15-34]]
^34^ A la hora nona gritó Jesús con fuerte voz: «Eloí, Eloí, ¿lema sabactaní?», - que quiere decir - «¡Dios mío, Dios mío! ¿por qué me has abandonado?»

[[mark-15-35]]
^35^ Al oír esto algunos de los presentes decían: «Mira, llama a Elías».

[[mark-15-36]]
^36^ Entonces uno fue corriendo a empapar una esponja en vinagre y, sujetándola a una caña, le ofrecía de beber, diciendo: «Dejad, vamos a ver si viene Elías a descolgarle».

[[mark-15-37]]
^37^ Pero Jesús lanzando un fuerte grito, expiró.

[[mark-15-38]]
^38^ Y el velo del Santuario se rasgó en dos, de arriba abajo.

[[mark-15-39]]
^39^ Al ver el centurión, que estaba frente a él, que había expirado de esa manera, dijo: «Verdaderamente este hombre era Hijo de Dios».

[[mark-15-40]]
^40^ Había también unas mujeres mirando desde lejos, entre ellas, María Magdalena, María la madre de Santiago el menor y de Joset, y Salomé,

[[mark-15-41]]
^41^ que le seguían y le servían cuando estaba en Galilea, y otras muchas que habían subido con él a Jerusalén.

[[mark-15-42]]
^42^ Y ya al atardecer, como era la Preparación, es decir, la víspera del sábado,

[[mark-15-43]]
^43^ vino José de Arimatea, miembro respetable del Consejo, que esperaba también el Reino de Dios, y tuvo la valentía de entrar donde Pilato y pedirle el cuerpo de Jesús.

[[mark-15-44]]
^44^ Se extraño Pilato de que ya estuviese muerto y, llamando al centurión, le preguntó si había muerto hacía tiempo.

[[mark-15-45]]
^45^ Informado por el centurión, concedió el cuerpo a José,

[[mark-15-46]]
^46^ quien, comprando una sábana, lo descolgó de la cruz, lo envolvió en la sábana y lo puso en un sepulcro que estaba excavado en roca; luego, hizo rodar una piedra sobre la entrada del sepulcro.

[[mark-15-47]]
^47^ María Magdalena y María la de Joset se fijaban dónde era puesto.
[[mark-16]]
== Capítulo 16

[[mark-16-1]]
^1^ Pasado el sábado, María Magdalena, María la de Santiago y Salomé compraron aromas para ir a embalsamarle.

[[mark-16-2]]
^2^ Y muy de madrugada, el primer día de la semana, a la salida del sol, van al sepulcro.

[[mark-16-3]]
^3^ Se decían unas otras: «¿Quién nos retirará la piedra de la puerta del sepulcro?»

[[mark-16-4]]
^4^ Y levantando los ojos ven que la piedra estaba ya retirada; y eso que era muy grande.

[[mark-16-5]]
^5^ Y entrando en el sepulcro vieron a un joven sentado en el lado derecho, vestido con una túnica blanca, y se asustaron.

[[mark-16-6]]
^6^ Pero él les dice: «No os asustéis. Buscáis a Jesús de Nazaret, el Crucificado; ha resucitado, no está aquí. Ved el lugar donde le pusieron.

[[mark-16-7]]
^7^ Pero id a decir a sus discípulos y a Pedro que irá delante de vosotros a Galilea; allí le veréis, como os dijo».

[[mark-16-8]]
^8^ Ellas salieron huyendo del sepulcro, pues un gran temblor y espanto se había apoderado de ellas, y no dijeron nada a nadie porque tenían miedo...

[[mark-16-9]]
^9^ Jesús resucitó en la madrugada, el primer día de la semana, y se apareció primero a María Magdalena, de la que había echado siete demonios.

[[mark-16-10]]
^10^ Ella fue a comunicar la noticia a los que habían vivido con él, que estaban tristes y llorosos.

[[mark-16-11]]
^11^ Ellos, al oír que vivía y que había sido visto por ella, no creyeron.

[[mark-16-12]]
^12^ Después de esto, se apareció, bajo otra figura, a dos de ellos cuando iban de camino a una aldea.

[[mark-16-13]]
^13^ Ellos volvieron a comunicárselo a los demás; pero tampoco creyeron a éstos.

[[mark-16-14]]
^14^ Por último, estando a la mesa los once discípulos, se les apareció y les echó en cara su incredulidad y su dureza de corazón, por no haber creído a quienes le habían visto resucitado.

[[mark-16-15]]
^15^ Y les dijo: «Id por todo el mundo y proclamad la Buena Nueva a toda la creación.

[[mark-16-16]]
^16^ El que crea y sea bautizado, se salvará; el que no crea, se condenará.

[[mark-16-17]]
^17^ Estas son las señales que acompañarán a los que crean: en mi nombre expulsarán demonios, hablarán en lenguas nuevas,

[[mark-16-18]]
^18^ agarrarán serpientes en sus manos y aunque beban veneno no les hará daño; impondrán las manos sobre los enfermos y se pondrán bien».

[[mark-16-19]]
^19^ Con esto, el Señor Jesús, después de hablarles, fue elevado al cielo y se sentó a la diestra de Dios.

[[mark-16-20]]
^20^ Ellos salieron a predicar por todas partes, colaborando el Señor con ellos y confirmando la Palabra con las señales que la acompañaban.
