[[luke]]
= Lucas

[[luke-1]]
== Capítulo 1

[[luke-1-1]]
^1^ Puesto que muchos han intentado narrar ordenadamente las cosas que se han verificado entre nosotros,

[[luke-1-2]]
^2^ tal como nos las han transmitido los que desde el principio fueron testigos oculares y servidores de la Palabra,

[[luke-1-3]]
^3^ he decidido yo también, después de haber investigado diligentemente todo desde los orígenes, escribírtelo por su orden, ilustre Teófilo,

[[luke-1-4]]
^4^ para que conozcas la solidez de las enseñanzas que has recibido.

[[luke-1-5]]
^5^ Hubo en los días de Herodes, rey de Judea, un sacerdote, llamado Zacarías, del grupo de Abías, casado con una mujer descendiente de Aarón, que se llamaba Isabel;

[[luke-1-6]]
^6^ los dos eran justos ante Dios, y caminaban sin tacha en todos los mandamientos y preceptos del Señor.

[[luke-1-7]]
^7^ No tenían hijos, porque Isabel era estéril, y los dos de avanzada edad.

[[luke-1-8]]
^8^ Sucedió que, mientras oficiaba delante de Dios, en el turno de su grupo,

[[luke-1-9]]
^9^ le tocó en suerte, según el uso del servicio sacerdotal, entrar en el Santuario del Señor para quemar el incienso.

[[luke-1-10]]
^10^ Toda la multitud del pueblo estaba fuera en oración, a la hora del incienso.

[[luke-1-11]]
^11^ Se le apareció el Angel del Señor, de pie, a la derecha del altar del incienso.

[[luke-1-12]]
^12^ Al verle Zacarías, se turbó, y el temor se apoderó de él.

[[luke-1-13]]
^13^ El ángel le dijo: «No temas, Zacarías, porque tu petición ha sido escuchada; Isabel, tu mujer, te dará a luz un hijo, a quien pondrás por nombre Juan;

[[luke-1-14]]
^14^ será para ti gozo y alegría, y muchos se gozarán en su nacimiento,

[[luke-1-15]]
^15^ porque será grande ante el Señor; no beberá vino ni licor; estará lleno de Espíritu Santo ya desde el seno de su madre,

[[luke-1-16]]
^16^ y a muchos de los hijos de Israel, les convertirá al Señor su Dios,

[[luke-1-17]]
^17^ e irá delante de él con el espíritu y el poder de Elías, para hacer volver los corazones de los padres a los hijos, y a los rebeldes a la prudencia de los justos, para preparar al Señor un pueblo bien dispuesto».

[[luke-1-18]]
^18^ Zacarías dijo al ángel: «¿En qué lo conoceré? Porque yo soy viejo y mi mujer avanzada en edad».

[[luke-1-19]]
^19^ El ángel le respondió: «Yo soy Gabriel, el que está delante de Dios, y he sido enviado para hablarte y anunciarte esta buena nueva.

[[luke-1-20]]
^20^ Mira, te vas a quedar mudo y no podrás hablar hasta el día en que sucedan estas cosas, porque no diste crédito a mis palabras, las cuales se cumplirán a su tiempo».

[[luke-1-21]]
^21^ El pueblo estaba esperando a Zacarías y se extrañaban de su demora en el Santuario.

[[luke-1-22]]
^22^ Cuando salió, no podía hablarles, y comprendieron que había tenido una visión en el Santuario; les hablabla por señas, y permaneció mudo.

[[luke-1-23]]
^23^ Y sucedió que cuando se cumplieron los días de su servicio, se fue a su casa.

[[luke-1-24]]
^24^ Días después, concibió su mujer Isabel; y se mantuvo oculta durante cinco meses

[[luke-1-25]]
^25^ diciendo: «Esto es lo que ha hecho por mí el Señor en los días en que se dignó quitar mi oprobio entre los hombres».

[[luke-1-26]]
^26^ Al sexto mes fue enviado por Dios el ángel Gabriel a una ciudad de Galilea, llamada Nazaret,

[[luke-1-27]]
^27^ a una virgen desposada con un hombre llamado José, de la casa de David; el nombre de la virgen era María.

[[luke-1-28]]
^28^ Y entrando, le dijo: «Alégrate, llena de gracia, el Señor está contigo».

[[luke-1-29]]
^29^ Ella se conturbó por estas palabras, y discurría qué significaría aquel saludo.

[[luke-1-30]]
^30^ El ángel le dijo: «No temas, María, porque has hallado gracia delante de Dios;

[[luke-1-31]]
^31^ vas a concebir en el seno y vas a dar a luz un hijo, a quien pondrás por nombre Jesús.

[[luke-1-32]]
^32^ El será grande y será llamado Hijo del Altísimo, y el Señor Dios le dará el trono de David, su padre;

[[luke-1-33]]
^33^ reinará sobre la casa de Jacob por los siglos y su reino no tendrá fin».

[[luke-1-34]]
^34^ María respondió al ángel: «¿Cómo será esto, puesto que no conozco varón?»

[[luke-1-35]]
^35^ El ángel le respondió: «El Espíritu Santo vendrá sobre ti y el poder del Altísimo te cubrirá con su sombra; por eso el que ha de nacer será santo y será llamado Hijo de Dios.

[[luke-1-36]]
^36^ Mira, también Isabel, tu pariente, ha concebido un hijo en su vejez, y este es ya el sexto mes de aquella que llamaban estéril,

[[luke-1-37]]
^37^ porque ninguna cosa es imposible para Dios».

[[luke-1-38]]
^38^ Dijo María: «He aquí la esclava del Señor; hágase en mí según tu palabra». Y el ángel dejándola se fue.

[[luke-1-39]]
^39^ En aquellos días, se levantó María y se fue con prontitud a la región montañosa, a una ciudad de Judá;

[[luke-1-40]]
^40^ entró en casa de Zacarías y saludó a Isabel.

[[luke-1-41]]
^41^ Y sucedió que, en cuanto oyó Isabel el saludo de María, saltó de gozo el niño en su seno, e Isabel quedó llena de Espíritu Santo;

[[luke-1-42]]
^42^ y exclamando con gran voz, dijo: «Bendita tú entre las mujeres y bendito el fruto de tu seno;

[[luke-1-43]]
^43^ y ¿de dónde a mí que la madre de mi Señor venga a mí?

[[luke-1-44]]
^44^ Porque, apenas llegó a mis oídos la voz de tu saludo, saltó de gozo el niño en mi seno.

[[luke-1-45]]
^45^ ¡Feliz la que ha creído que se cumplirían las cosas que le fueron dichas de parte del Señor!»

[[luke-1-46]]
^46^ Y dijo María: «Engrandece mi alma al Señor

[[luke-1-47]]
^47^ y mi espíritu se alegra en Dios mi salvador

[[luke-1-48]]
^48^ porque ha puesto los ojos en la humildad de su esclava, por eso desde ahora todas las generaciones me llamarán bienaventurada,

[[luke-1-49]]
^49^ porque ha hecho en mi favor maravillas el Poderoso, Santo es su nombre

[[luke-1-50]]
^50^ y su misericordia alcanza de generación en generación a los que le temen.

[[luke-1-51]]
^51^ Desplegó la fuerza de su brazo, dispersó a los que son soberbios en su propio corazón.

[[luke-1-52]]
^52^ Derribó a los potentados de sus tronos y exaltó a los humildes.

[[luke-1-53]]
^53^ A los hambrientos colmó de bienes y despidió a los ricos sin nada.

[[luke-1-54]]
^54^ Acogió a Israel, su siervo, acordándose de la misericordia

[[luke-1-55]]
^55^ - como había anunciado a nuestros padres - en favor de Abraham y de su linaje por los siglos».

[[luke-1-56]]
^56^ María permanceció con ella unos tres meses, y se volvió a su casa.

[[luke-1-57]]
^57^ Se le cumplió a Isabel el tiempo de dar a luz, y tuvo un hijo.

[[luke-1-58]]
^58^ Oyeron sus vecinos y parientes que el Señor le había hecho gran misericordia, y se congratulaban con ella.

[[luke-1-59]]
^59^ Y sucedió que al octavo día fueron a circuncidar al niño, y querían ponerle el nombre de su padre, Zacarías,

[[luke-1-60]]
^60^ pero su madre, tomando la palabra, dijo: «No; se ha de llamar Juan».

[[luke-1-61]]
^61^ Le decían: «No hay nadie en tu parentela que tenga ese nombre».

[[luke-1-62]]
^62^ Y preguntaban por señas a su padre cómo quería que se le llamase.

[[luke-1-63]]
^63^ El pidió una tablilla y escribió: «Juan es su nombre». Y todos quedaron admirados.

[[luke-1-64]]
^64^ Y al punto se abrió su boca y su lengua, y hablaba bendiciendo a Dios.

[[luke-1-65]]
^65^ Invadió el temor a todos sus vecinos, y en toda la montaña de Judea se comentaban todas estas cosas;

[[luke-1-66]]
^66^ todos los que las oían las grababan en su corazón, diciendo: «Pues ¿qué será este niño?» Porque, en efecto, la mano del Señor estaba con él.

[[luke-1-67]]
^67^ Zacarías, su padre, quedó lleno de Espíritu Santo, y profetizó diciendo:

[[luke-1-68]]
^68^ «Bendito el Señor Dios de Israel porque ha visitado y redimido a su pueblo.

[[luke-1-69]]
^69^ y nos ha suscitado una fuerza salvadora en la casa de David, su siervo,

[[luke-1-70]]
^70^ como había prometido desde tiempos antiguos, por boca de sus santos profetas,

[[luke-1-71]]
^71^ que nos salvaría de nuestros enemigos y de las manos de todos los que nos odiaban

[[luke-1-72]]
^72^ haciendo misericordia a nuestros padres y recordando su santa alianza

[[luke-1-73]]
^73^ y el juramento que juró a Abraham nuestro padre, de concedernos

[[luke-1-74]]
^74^ que, libres de manos enemigas, podamos servirle sin temor

[[luke-1-75]]
^75^ en santidad y justicia delante de él todos nuestros días.

[[luke-1-76]]
^76^ Y tú, niño, serás llamado profeta del Altísimo, pues irás delante del Señor para preparar sus caminos

[[luke-1-77]]
^77^ y dar a su pueblo conocimiento de salvación por el perdón de sus pecados,

[[luke-1-78]]
^78^ por las entrañas de misericordia de nuestro Dios, que harán que nos visite una Luz de la altura,

[[luke-1-79]]
^79^ a fin de iluminar a los que habitan en tinieblas y sombras de muerte y guiar nuestros pasos por el camino de la paz».

[[luke-1-80]]
^80^ El niño crecía y su espíritu se fortalecía; vivió en los desiertos hasta el día de su manifestación a Israel.
[[luke-2]]
== Capítulo 2

[[luke-2-1]]
^1^ Sucedió que por aquellos días salió un edicto de César Augusto ordenando que se empadronase todo el mundo.

[[luke-2-2]]
^2^ Este primer empadronamiento tuvo lugar siendo gobernador de Siria Cirino.

[[luke-2-3]]
^3^ Iban todos a empadronarse, cada uno a su ciudad.

[[luke-2-4]]
^4^ Subió también José desde Galilea, de la ciudad de Nazaret, a Judea, a la ciudad de David, que se llama Belén, por ser él de la casa y familia de David,

[[luke-2-5]]
^5^ para empadronarse con María, su esposa, que estaba encinta.

[[luke-2-6]]
^6^ Y sucedió que, mientras ellos estaban allí, se le cumplieron los días del alumbramiento,

[[luke-2-7]]
^7^ y dio a luz a su hijo primogénito, le envolvió en pañales y le acostó en un pesebre, porque no tenían sitio en el alojamiento.

[[luke-2-8]]
^8^ Había en la misma comarca unos pastores, que dormían al raso y vigilaban por turno durante la noche su rebaño.

[[luke-2-9]]
^9^ Se les presentó el Angel del Señor, y la gloria del Señor los envolvió en su luz; y se llenaron de temor.

[[luke-2-10]]
^10^ El ángel les dijo: «No temáis, pues os anuncio una gran alegría, que lo será para todo el pueblo:

[[luke-2-11]]
^11^ os ha nacido hoy, en la ciudad de David, un salvador, que es el Cristo Señor;

[[luke-2-12]]
^12^ y esto os servirá de señal: encontraréis un niño envuelto en pañales y acostado en un pesebre».

[[luke-2-13]]
^13^ Y de pronto se juntó con el ángel una multitud del ejército celestial, que alababa a Dios, diciendo:

[[luke-2-14]]
^14^ «Gloria a Dios en las alturas y en la tierra paz a los hombres en quienes él se complace».

[[luke-2-15]]
^15^ Y sucedió que cuando los ángeles, dejándoles, se fueron al cielo, los pastores se decían unos a otros: «Vayamos, pues, hasta Belén y veamos lo que ha sucedido y el Señor nos ha manifestado».

[[luke-2-16]]
^16^ Y fueron a toda prisa, y encontraron a María y a José, y al niño acostado en el pesebre.

[[luke-2-17]]
^17^ Al verlo, dieron a conocer lo que les habían dicho acerca de aquel niño;

[[luke-2-18]]
^18^ y todos los que lo oyeron se maravillaban de lo que los pastores les decían.

[[luke-2-19]]
^19^ María, por su parte, guardaba todas estas cosas, y las meditaba en su corazón.

[[luke-2-20]]
^20^ Los pastores se volvieron glorificando y alabando a Dios por todo lo que habían oído y visto, conforme a lo que se les había dicho.

[[luke-2-21]]
^21^ Cuando se cumplieron los ocho días para circuncidarle, se le dio el nombre de Jesús, el que le dio el ángel antes de ser concebido en el seno.

[[luke-2-22]]
^22^ Cuando se cumplieron los días de la purificación de ellos, según la Ley de Moisés, llevaron a Jesús a Jerusalén para presentarle al Señor,

[[luke-2-23]]
^23^ como está escrito en la Ley del Señor: Todo varón primogénito será consagrado al Señor

[[luke-2-24]]
^24^ y para ofrecer en sacrificio un par de tórtolas o dos pichones, conforme a lo que se dice en la Ley del Señor.

[[luke-2-25]]
^25^ Y he aquí que había en Jerusalén un hombre llamado Simeón; este hombre era justo y piadoso, y esperaba la consolación de Israel; y estaba en él el Espíritu Santo.

[[luke-2-26]]
^26^ Le había sido revelado por el Espíritu Santo que no vería la muerte antes de haber visto al Cristo del Señor.

[[luke-2-27]]
^27^ Movido por el Espíritu, vino al Templo; y cuando los padres introdujeron al niño Jesús, para cumplir lo que la Ley prescribía sobre él,

[[luke-2-28]]
^28^ le tomó en brazos y bendijo a Dios diciendo:

[[luke-2-29]]
^29^ «Ahora, Señor, puedes, según tu palabra, dejar que tu siervo se vaya en paz;

[[luke-2-30]]
^30^ porque han visto mis ojos tu salvación,

[[luke-2-31]]
^31^ la que has preparado a la vista de todos los pueblos,

[[luke-2-32]]
^32^ luz para iluminar a los gentiles y gloria de tu pueblo Israel».

[[luke-2-33]]
^33^ Su padre y su madre estaban admirados de lo que se decía de él.

[[luke-2-34]]
^34^ Simeón les bendijo y dijo a María, su madre: «Este está puesto para caída y elevación de muchos en Israel, y para ser señal de contradicción -

[[luke-2-35]]
^35^ ¡y a ti misma una espada te atravesará el alma! - a fin de que queden al descubierto las intenciones de muchos corazones».

[[luke-2-36]]
^36^ Había también una profetisa, Ana, hija de Fanuel, de la tribu de Aser, de edad avanzada; después de casarse había vivido siete años con su marido,

[[luke-2-37]]
^37^ y permaneció viuda hasta los ochenta y cuatro años; no se apartaba del Templo, sirviendo a Dios noche y día en ayunos y oraciones.

[[luke-2-38]]
^38^ Como se presentase en aquella misma hora, alababa a Dios y hablaba del niño a todos los que esperaban la redención de Jerusalén.

[[luke-2-39]]
^39^ Así que cumplieron todas las cosas según la Ley del Señor, volvieron a Galilea, a su ciudad de Nazaret.

[[luke-2-40]]
^40^ El niño crecía y se fortalecía, llenándose de sabiduría; y la gracia de Dios estaba sobre él.

[[luke-2-41]]
^41^ Sus padres iban todos los años a Jerusalén a la fiesta de la Pascua.

[[luke-2-42]]
^42^ Cuando tuvo doce años, subieron ellos como de costumbre a la fiesta

[[luke-2-43]]
^43^ y, al volverse, pasados los días, el niño Jesús se quedó en Jerusalén, sin saberlo su padres.

[[luke-2-44]]
^44^ Pero creyendo que estaría en la caravana, hicieron un día de camino, y le buscaban entre los parientes y conocidos;

[[luke-2-45]]
^45^ pero al no encontrarle, se volvieron a Jerusalén en su busca.

[[luke-2-46]]
^46^ Y sucedió que, al cabo de tres días, le encontraron en el Templo sentado en medio de los maestros, escuchándoles y preguntándoles;

[[luke-2-47]]
^47^ todos los que le oían, estaban estupefactos por su inteligencia y sus respuestas.

[[luke-2-48]]
^48^ Cuando le vieron, quedaron sorprendidos, y su madre le dijo: «Hijo, ¿por qué nos has hecho esto? Mira, tu padre y yo, angustiados, te andábamos buscando».

[[luke-2-49]]
^49^ El les dijo: «Y ¿por qué me buscabais? ¿No sabíais que yo debía estar en la casa de mi Padre?»

[[luke-2-50]]
^50^ Pero ellos no comprendieron la respuesta que les dio.

[[luke-2-51]]
^51^ Bajó con ellos y vino a Nazaret, y vivía sujeto a ellos. Su madre conservaba cuidadosamente todas las cosas en su corazón.

[[luke-2-52]]
^52^ Jesús progresaba en sabiduría, en estatura y en gracia ante Dios y ante los hombres.
[[luke-3]]
== Capítulo 3

[[luke-3-1]]
^1^ En el año quince del imperio de Tiberio César, siendo Poncio Pilato procurador de Judea, y Herodes tetrarca de Galilea; Filipo, su hermano, tetrarca de Iturea y de Traconítida, y Lisanias tetrarca de Abilene;

[[luke-3-2]]
^2^ en el pontificado de Anás y Caifás, fue dirigida la palabra de Dios a Juan, hijo de Zacarías, en el desierto.

[[luke-3-3]]
^3^ Y se fue por toda la región del Jordán proclamando un bautismo de conversión para perdón de los pecados,

[[luke-3-4]]
^4^ como está escrito en el libro de los oráculos del profeta Isaías: Voz del que clama en el desierto: Preparad el camino del Señor, enderezad sus sendas;

[[luke-3-5]]
^5^ todo barranco será rellenado, todo monte y colina será rebajado, lo tortuoso se hará recto y las asperezas serán caminos llanos.

[[luke-3-6]]
^6^ Y todos verán la salvación de Dios.

[[luke-3-7]]
^7^ Decía, pues, a la gente que acudía para ser bautizada por él: «Raza de víboras, ¿quién os ha enseñado a huir de la ira inminente?

[[luke-3-8]]
^8^ Dad, pues, frutos dignos de conversión, y no andéis diciendo en vuestro interior: “Tenemos por padre a Abraham”; porque os digo que puede Dios de estas piedras dar hijos a Abraham.

[[luke-3-9]]
^9^ Y ya está el hacha puesta a la raíz de los árboles; y todo árbol que no dé buen fruto será cortado y arrojado al fuego».

[[luke-3-10]]
^10^ La gente le preguntaba: «Pues ¿qué debemos hacer?»

[[luke-3-11]]
^11^ Y él les respondía: «El que tenga dos túnicas, que las reparta con el que no tiene; el que tenga para comer, que haga lo mismo».

[[luke-3-12]]
^12^ Vinieron también publicanos a bautizarse, y le dijeron: «Maestro, ¿qué debemos hacer?»

[[luke-3-13]]
^13^ El les dijo: «No exijáis más de lo que os está fijado».

[[luke-3-14]]
^14^ Preguntáronle también unos soldados: «Y nosotros ¿qué debemos hacer?» El les dijo: «No hagáis extorsión a nadie, no hagáis denuncias falsas, y contentaos con vuestra soldada».

[[luke-3-15]]
^15^ Como el pueblo estaba a la espera, andaban todos pensando en sus corazones acerca de Juan, si no sería él el Cristo;

[[luke-3-16]]
^16^ respondió Juan a todos, diciendo: «Yo os bautizo con agua; pero viene el que es más fuerte que yo, y no soy digno de desatarle la correa de sus sandalias. El os bautizará en Espíritu Santo y fuego.

[[luke-3-17]]
^17^ En su mano tiene el bieldo para limpiar su era y recoger el trigo en su granero; pero la paja la quemará con fuego que no se apaga».

[[luke-3-18]]
^18^ Y, con otras muchas exhortaciones, anunciaba al pueblo la Buena Nueva.

[[luke-3-19]]
^19^ Pero Herodes, el tetrarca, reprendido por él a causa de Herodías, la mujer de su hermano, y a causa de todas las malas acciones que había hecho,

[[luke-3-20]]
^20^ añadió a todas ellas la de encerrar a Juan en la cárcel.

[[luke-3-21]]
^21^ Sucedió que cuando todo el pueblo estaba bautizándose, bautizado también Jesús y puesto en oración, se abrió el cielo,

[[luke-3-22]]
^22^ y bajó sobre él el Espíritu Santo en forma corporal, como una paloma; y vino una voz del cielo: «Tú eres mi hijo; yo hoy te he engendrado».

[[luke-3-23]]
^23^ Tenía Jesús, al comenzar, unos treinta años, y era según se creía hijo de José, hijo de Helí,

[[luke-3-24]]
^24^ hijo de Mattat, hijo de Leví, hijo de Melkí, hijo de Jannái, hijo de José,

[[luke-3-25]]
^25^ hijo de Mattatías, hijo de Amós, hijo de Naúm, hijo de Eslí, hijo de Nangay,

[[luke-3-26]]
^26^ hijo de Maaz, hijo de Mattatías, hijo de Semeín, hijo de Josec, hijo de Jodá,

[[luke-3-27]]
^27^ hijo de Joanán, hijo de Resá, hijo de Zorobabel, hijo de Salatiel, hijo de Nerí,

[[luke-3-28]]
^28^ hijo de Melkí, hijo de Addí, hijo de Cosam, hijo de Elmadam, hijo de Er,

[[luke-3-29]]
^29^ hijo de Jesús, hijo de Eliezer, hijo de Jorim, hijo de Mattat, hijo de Leví,

[[luke-3-30]]
^30^ hijo de Simeón, hijo de Judá, hijo de José, hijo de Jonam, hijo de Eliaquim,

[[luke-3-31]]
^31^ hijo de Meleá, hijo de Menná, hijo de Mattatá, hijo de Natán, hijo de David,

[[luke-3-32]]
^32^ hijo de Jesé, hijo de Obed, hijo de Booz, hijo de Sala, hijo de Naassón,

[[luke-3-33]]
^33^ hijo de Aminadab, hijo de Admín, hijo de Arní, hijo de Esrom, hijo de Fares, hijo de Judá,

[[luke-3-34]]
^34^ hijo de Jacob, hijo de Isaac, hijo de Abraham, hijo de Tara, hijo de Najor,

[[luke-3-35]]
^35^ hijo de Serug, hijo de Ragáu, hijo de Fálek, hijo de Eber, hijo de Sala,

[[luke-3-36]]
^36^ hijo de Cainam, hijo de Arfaxad, hijo de Sem, hijo de Noé, hijo de Lámek,

[[luke-3-37]]
^37^ hijo de Matusalén, hijo de Henoc, hijo de Járet, hijo de Maleleel, hijo de Cainam,

[[luke-3-38]]
^38^ hijo de Enós, hijo de Set, hijo de Adam, hijo de Dios.
[[luke-4]]
== Capítulo 4

[[luke-4-1]]
^1^ Jesús, lleno de Espíritu Santo, se volvió del Jordán, y era conducido por el Espíritu en el desierto,

[[luke-4-2]]
^2^ durante cuarenta días, tentado por el diablo. No comió nada en aquellos días y, al cabo de ellos, sintió hambre.

[[luke-4-3]]
^3^ Entonces el diablo le dijo: «Si eres Hijo de Dios, di a esta piedra que se convierta en pan».

[[luke-4-4]]
^4^ Jesús le respondió: «Esta escrito: No sólo de pan vive el hombre».

[[luke-4-5]]
^5^ Llevándole a una altura le mostró en un instante todos los reinos de la tierra;

[[luke-4-6]]
^6^ y le dijo el diablo: «Te daré todo el poder y la gloria de estos reinos, porque a mí me ha sido entregada, y se la doy a quien quiero.

[[luke-4-7]]
^7^ Si, pues, me adoras, toda será tuya».

[[luke-4-8]]
^8^ Jesús le respondió: «Esta escrito: Adorarás al Señor tu Dios y sólo a él darás culto».

[[luke-4-9]]
^9^ Le llevó a Jerusalén, y le puso sobre el alero del Templo, y le dijo: «Si eres Hijo de Dios, tírate de aquí abajo;

[[luke-4-10]]
^10^ porque está escrito: A sus ángeles te encomendará para que te guarden.

[[luke-4-11]]
^11^ Y: En sus manos te llevarán para que no tropiece tu pie en piedra alguna».

[[luke-4-12]]
^12^ Jesús le respondió: «Está dicho: No tentarás al Señor tu Dios».

[[luke-4-13]]
^13^ Acabada toda tentación, el diablo se alejó de él hasta un tiempo oportuno.

[[luke-4-14]]
^14^ Jesús volvió a Galilea por la fuerza del Espíritu, y su fama se extendió por toda la región.

[[luke-4-15]]
^15^ El iba enseñando en sus sinagogas, alabado por todos.

[[luke-4-16]]
^16^ Vino a Nazará, donde se había criado y, según su costumbre, entró en la sinagoga el día de sábado, y se levantó para hacer la lectura.

[[luke-4-17]]
^17^ Le entregaron el volumen del profeta Isaías y desenrollando el volumen, halló el pasaje donde estaba escrito:

[[luke-4-18]]
^18^ El Espíritu del Señor sobre mí, porque me ha ungido para anunciar a los pobres la Buena Nueva, me ha enviado a proclamar la liberación a los cautivos y la vista a los ciegos, para dar la libertad a los oprimidos

[[luke-4-19]]
^19^ y proclamar un año de gracia del Señor.

[[luke-4-20]]
^20^ Enrollando el volumen lo devolvió al ministro, y se sentó. En la sinagoga todos los ojos estaban fijos en él.

[[luke-4-21]]
^21^ Comenzó, pues, a decirles: «Esta Escritura, que acabáis de oír, se ha cumplido hoy».

[[luke-4-22]]
^22^ Y todos daban testimonio de él y estaban admirados de las palabras llenas de gracia que salían de su boca. Y decían: «¿No es éste el hijo de José?»

[[luke-4-23]]
^23^ El les dijo: «Seguramente me vais a decir el refrán: Médico, cúrate a ti mismo. Todo lo que hemos oído que ha sucedido en Cafarnaúm, hazlo también aquí en tu patria».

[[luke-4-24]]
^24^ Y añadió: «En verdad os digo que ningún profeta es bien recibido en su patria».

[[luke-4-25]]
^25^ «Os digo de verdad: Muchas viudas había en Israel en los días de Elías, cuando se cerró el cielo por tres años y seis meses, y hubo gran hambre en todo el país;

[[luke-4-26]]
^26^ y a ninguna de ellas fue enviado Elías, sino a una mujer viuda de Sarepta de Sidón.

[[luke-4-27]]
^27^ Y muchos leprosos había en Israel en tiempos del profeta Eliseo, y ninguno de ellos fue purificado sino Naamán, el sirio».

[[luke-4-28]]
^28^ Oyendo estas cosas, todos los de la sinagoga se llenaron de ira;

[[luke-4-29]]
^29^ y, levantándose, le arrojaron fuera de la ciudad, y le llevaron a una altura escarpada del monte sobre el cual estaba edificada su ciudad, para despeñarle.

[[luke-4-30]]
^30^ Pero él, pasando por medio de ellos, se marchó.

[[luke-4-31]]
^31^ Bajó a Cafarnaúm, ciudad de Galilea, y los sábados les enseñaba.

[[luke-4-32]]
^32^ Quedaban asombrados de su doctrina, porque hablaba con autoridad.

[[luke-4-33]]
^33^ Había en la sinagoga un hombre que tenía el espíritu de un demonio inmundo, y se puso a gritar a grandes voces:

[[luke-4-34]]
^34^ «¡Ah! ¿Qué tenemos nosotros contigo, Jesús de Nazaret? ¿Has venido a destruirnos? Sé quién eres tú: el Santo de Dios».

[[luke-4-35]]
^35^ Jesús entonces le conminó diciendo: «Cállate, y sal de él». Y el demonio, arrojándole en medio, salió de él sin hacerle ningún daño.

[[luke-4-36]]
^36^ Quedaron todos pasmados, y se decían unos a otros: «¡Qué palabra ésta! Manda con autoridad y poder a los espíritus inmundos y salen».

[[luke-4-37]]
^37^ Y su fama se extendió por todos los lugares de la región.

[[luke-4-38]]
^38^ Saliendo de la sinagoga, entró en la casa de Simón. La suegra de Simón estaba con mucha fiebre, y le rogaron por ella.

[[luke-4-39]]
^39^ Inclinándose sobre ella, conminó a la fiebre, y la fiebre la dejó; ella, levantándose al punto, se puso a servirles.

[[luke-4-40]]
^40^ A la puesta del sol, todos cuantos tenían enfermos de diversas dolencias se los llevaban; y, poniendo él las manos sobre cada uno de ellos, los curaba.

[[luke-4-41]]
^41^ Salían también demonios de muchos, gritando y diciendo: «Tú eres el Hijo de Dios». Pero él, conminaba y no les permitía hablar, porque sabían que él era el Cristo.

[[luke-4-42]]
^42^ Al hacerse de día, salió y se fue a un lugar solitario. La gente le andaba buscando y, llegando donde él, trataban de retenerle para que no les dejara.

[[luke-4-43]]
^43^ Pero él les dijo: «También a otras ciudades tengo que anunciar la Buena Nueva del Reino de Dios, porque a esto he sido enviado».

[[luke-4-44]]
^44^ E iba predicando por las sinagogas de Judea.
[[luke-5]]
== Capítulo 5

[[luke-5-1]]
^1^ Estaba él a la orilla del lago Genesaret y la gente se agolpaba sobre él para oír la Palabra de Dios,

[[luke-5-2]]
^2^ cuando vio dos barcas que estaban a la orilla del lago. Los pescadores habían bajado de ellas, y lavaban las redes.

[[luke-5-3]]
^3^ Subiendo a una de las barcas, que era de Simón, le rogó que se alejara un poco de tierra; y, sentándose, enseñaba desde la barca a la muchedumbre.

[[luke-5-4]]
^4^ Cuando acabó de hablar, dijo a Simón: «Boga mar adentro, y echad vuestras redes para pescar».

[[luke-5-5]]
^5^ Simón le respondió: «Maestro, hemos estado bregando toda la noche y no hemos pescado nada; pero, en tu palabra, echaré las redes».

[[luke-5-6]]
^6^ Y, haciéndolo así, pescaron gran cantidad de peces, de modo que las redes amenazaban romperse.

[[luke-5-7]]
^7^ Hicieron señas a los compañeros de la otra barca para que vinieran en su ayuda. Vinieron, pues, y llenaron tanto las dos barcas que casi se hundían.

[[luke-5-8]]
^8^ Al verlo Simón Pedro, cayó a las rodillas de Jesús, diciendo: «Aléjate de mí, Señor, que soy un hombre pecador».

[[luke-5-9]]
^9^ Pues el asombro se había apoderado de él y de cuantos con él estaban, a causa de los peces que habían pescado.

[[luke-5-10]]
^10^ Y lo mismo de Santiago y Juan, hijos de Zebedeo, que eran compañeros de Simón. Jesús dijo a Simón: «No temas. Desde ahora serás pescador de hombres».

[[luke-5-11]]
^11^ Llevaron a tierra las barcas y, dejándolo todo, le siguieron.

[[luke-5-12]]
^12^ Y sucedió que, estando en una ciudad, se presentó un hombre cubierto de lepra que, al ver a Jesús, se echó rostro en tierra, y le rogó diciendo: «Señor, si quieres, puedes limpiarme».

[[luke-5-13]]
^13^ El extendió la mano, le tocó, y dijo: «Quiero, queda limpio». Y al instante le desapareció la lepra.

[[luke-5-14]]
^14^ Y él le ordenó que no se lo dijera a nadie. Y añadió: «Vete, muéstrate al sacerdote y haz la ofrenda por tu purificación como prescribió Moisés para que les sirva de testimonio».

[[luke-5-15]]
^15^ Su fama se extendía cada vez más y una numerosa multitud afluía para oírle y ser curados de sus enfermedades.

[[luke-5-16]]
^16^ Pero él se retiraba a los lugares solitarios, donde oraba.

[[luke-5-17]]
^17^ Un día que estaba enseñando, había sentados algunos fariseos y doctores de la ley que habían venido de todos los pueblos de Galilea y Judea, y de Jerusalén. El poder del Señor le hacía obrar curaciones.

[[luke-5-18]]
^18^ En esto, unos hombres trajeron en una camilla a un paralítico y trataban de introducirle, para ponerle delante de él.

[[luke-5-19]]
^19^ Pero no encontrando por dónde meterle, a causa de la multitud, subieron al terrado, le bajaron con la camilla a través de las tejas, y le pusieron en medio, delante de Jesús.

[[luke-5-20]]
^20^ Viendo Jesús la fe de ellos, dijo: «Hombre, tus pecados te quedan perdonados».

[[luke-5-21]]
^21^ Los escribas y fariseos empezaron a pensar: «¿Quién es éste, que dice blasfemias? ¿Quién puede perdonar pecados sino sólo Dios?»

[[luke-5-22]]
^22^ Conociendo Jesús sus pensamientos, les dijo: «¿Qué estáis pensando en vuestros corazones?

[[luke-5-23]]
^23^ ¿Qué es más fácil, decir: “Tus pecados te quedan perdonados”, o decir: “Levántate y anda”?

[[luke-5-24]]
^24^ Pues para que sepáis que el Hijo del hombre tiene en la tierra poder de perdonar pecados, - dijo al paralítico -: “A ti te digo, levántate, toma tu camilla y vete a tu casa”».

[[luke-5-25]]
^25^ Y al instante, levantándose delante de ellos, tomó la camilla en que yacía y se fue a su casa, glorificando a Dios.

[[luke-5-26]]
^26^ El asombro se apoderó de todos, y glorificaban a Dios. Y llenos de temor, decían: «Hoy hemos visto cosas increíbles».

[[luke-5-27]]
^27^ Después de esto, salió y vio a un publicano llamado Leví, sentado en el despacho de impuestos, y le dijo: «Sígueme».

[[luke-5-28]]
^28^ El, dejándolo todo, se levantó y le siguió.

[[luke-5-29]]
^29^ Leví le ofreció en su casa un gran banquete. Había un gran número de publicanos, y de otros que estaban a la mesa con ellos.

[[luke-5-30]]
^30^ Los fariseos y sus escribas murmuraban diciendo a los discípulos: «¿Por qué coméis y bebéis con los publicanos y pecadores?»

[[luke-5-31]]
^31^ Les respondió Jesús: «No necesitan médico los que están sanos, sino los que están mal.

[[luke-5-32]]
^32^ No he venido a llamar a conversión a justos, sino a pecadores».

[[luke-5-33]]
^33^ Ellos le dijeron: «Los discípulos de Juan ayunan frecuentemente y recitan oraciones, igual que los de los fariseos, pero los tuyos comen y beben».

[[luke-5-34]]
^34^ Jesús les dijo: «¿Podéis acaso hacer ayunar a los invitados a la boda mientras el novio está con ellos?

[[luke-5-35]]
^35^ Días vendrán en que les será arrebatado el novio; entonces ayunarán en aquellos días».

[[luke-5-36]]
^36^ Les dijo también una parábola: «Nadie rompe un vestido nuevo para echar un remiendo a uno viejo; de otro modo, desgarraría el nuevo, y al viejo no le iría el remiendo del nuevo.

[[luke-5-37]]
^37^ «Nadie echa tampoco vino nuevo en pellejos viejos; de otro modo, el vino nuevo reventaría los pellejos, el vino se derramaría, y los pellejos se echarían a perder;

[[luke-5-38]]
^38^ sino que el vino nuevo debe echarse en pellejos nuevos.

[[luke-5-39]]
^39^ Nadie, después de beber el vino añejo, quiere del nuevo porque dice: «El añejo es el bueno».
[[luke-6]]
== Capítulo 6

[[luke-6-1]]
^1^ Sucedió que cruzaba en sábado por unos sembrados; sus discípulos arrancaban y comían espigas desgranándolas con las manos.

[[luke-6-2]]
^2^ Algunos de los fariseos dijeron: «¿Por qué hacéis lo que no es lícito en sábado?»

[[luke-6-3]]
^3^ Y Jesús les respondió: «¿Ni siquiera habéis leído lo que hizo David, cuando sintió hambre él y los que le acompañaban,

[[luke-6-4]]
^4^ cómo entró en la Casa de Dios, y tomando los panes de la presencia, que no es lícito comer sino sólo a los sacerdotes, comió él y dio a los que le acompañaban?»

[[luke-6-5]]
^5^ Y les dijo: «El Hijo del hombre es señor del sábado».

[[luke-6-6]]
^6^ Sucedió que entró Jesús otro sábado en la sinagoga y se puso a enseñar. Había allí un hombre que tenía la mano derecha seca.

[[luke-6-7]]
^7^ Estaban al acecho los escribas y fariseos por si curaba en sábado, para encontrar de qué acusarle.

[[luke-6-8]]
^8^ Pero él, conociendo sus pensamientos, dijo al hombre que tenía la mano seca: «Levántate y ponte ahí en medio». El, levantándose, se puso allí.

[[luke-6-9]]
^9^ Entonces Jesús les dijo: «Yo os pregunto si en sábado es lícito hacer el bien en vez de hacer el mal, salvar una vida en vez de destruirla».

[[luke-6-10]]
^10^ Y mirando a todos ellos, le dijo: «Extiende tu mano». El lo hizo, y quedó restablecida su mano.

[[luke-6-11]]
^11^ Ellos se ofuscaron, y deliberaban entre sí qué harían a Jesús.

[[luke-6-12]]
^12^ Sucedió que por aquellos días se fue él al monte a orar, y se pasó la noche en la oración de Dios.

[[luke-6-13]]
^13^ Cuando se hizo de día, llamó a sus discípulos, y eligió doce de entre ellos, a los que llamó también apóstoles.

[[luke-6-14]]
^14^ A Simón, a quien llamó Pedro, y a su hermano Andrés; a Santiago y Juan, a Felipe y Bartolomé,

[[luke-6-15]]
^15^ a Mateo y Tomás, a Santiago de Alfeo y Simón, llamado Zelotes;

[[luke-6-16]]
^16^ a Judas de Santiago, y a Judas Iscariote, que llegó a ser un traidor.

[[luke-6-17]]
^17^ Bajando con ellos se detuvo en un paraje llano; había una gran multitud de discípulos suyos y gran muchedumbre del pueblo, de toda Judea, de Jerusalén y de la región costera de Tiro y Sidón,

[[luke-6-18]]
^18^ que habían venido para oírle y ser curados de sus enfermedades. Y los que eran molestados por espíritus inmundos quedaban curados.

[[luke-6-19]]
^19^ Toda la gente procuraba tocarle, porque salía de él una fuerza que sanaba a todos.

[[luke-6-20]]
^20^ Y él, alzando los ojos hacia sus discípulos, decía: «Bienaventurados los pobres, porque vuestro es el Reino de Dios.

[[luke-6-21]]
^21^ Bienaventurados los que tenéis hambre ahora, porque seréis saciados. Bienaventurados los que lloráis ahora, porque reiréis.

[[luke-6-22]]
^22^ Bienaventurados seréis cuando los hombres os odien, cuando os expulsen, os injurien y proscriban vuestro nombre como malo, por causa del Hijo del hombre.

[[luke-6-23]]
^23^ Alegraos ese día y saltad de gozo, que vuestra recompensa será grande en el cielo. Pues de ese modo trataban sus padres a los profetas.

[[luke-6-24]]
^24^ «Pero ¡ay de vosotros, los ricos!, porque habéis recibido vuestro consuelo.

[[luke-6-25]]
^25^ ¡Ay de vosotros, los que ahora estáis hartos!, porque tendréis hambre. ¡Ay de los que reís ahora!, porque tendréis aflicción y llanto.

[[luke-6-26]]
^26^ ¡Ay cuando todos los hombres hablen bien de vosotros!, pues de ese modo trataban sus padres a los falsos profetas.

[[luke-6-27]]
^27^ «Pero yo os digo a los que me escucháis: Amad a vuestros enemigos, haced bien a los que os odien,

[[luke-6-28]]
^28^ bendecid a los que os maldigan, rogad por los que os difamen.

[[luke-6-29]]
^29^ Al que te hiera en una mejilla, preséntale también la otra; y al que te quite el manto, no le niegues la túnica.

[[luke-6-30]]
^30^ A todo el que te pida, da, y al que tome lo tuyo, no se lo reclames.

[[luke-6-31]]
^31^ Y lo que queráis que os hagan los hombres, hacédselo vosotros igualmente.

[[luke-6-32]]
^32^ Si amáis a los que os aman, ¿qué mérito tenéis? Pues también los pecadores aman a los que les aman.

[[luke-6-33]]
^33^ Si hacéis bien a los que os lo hacen a vosotros, ¿qué mérito tenéis? ¡También los pecadores hacen otro tanto!

[[luke-6-34]]
^34^ Si prestáis a aquellos de quienes esperáis recibir, ¿qué mérito tenéis? También los pecadores prestan a los pecadores para recibir lo correspondiente.

[[luke-6-35]]
^35^ Más bien, amad a vuestros enemigos; haced el bien, y prestad sin esperar nada a cambio; y vuestra recompensa será grande, y seréis hijos del Altísimo, porque él es bueno con los ingratos y los perversos.

[[luke-6-36]]
^36^ «Sed compasivos, como vuestro Padre es compasivo.

[[luke-6-37]]
^37^ No juzguéis y no seréis juzgados, no condenéis y no seréis condenados; perdonad y seréis perdonados.

[[luke-6-38]]
^38^ Dad y se os dará; una medida buena, apretada, remecida, rebosante pondrán en el halda de vuestros vestidos. Porque con la medida con que midáis se os medirá».

[[luke-6-39]]
^39^ Les añadió una parábola: «¿Podrá un ciego guiar a otro ciego? ¿No caerán los dos en el hoyo?

[[luke-6-40]]
^40^ No está el discípulo por encima del maestro. Todo el que esté bien formado, será como su maestro.

[[luke-6-41]]
^41^ ¿Cómo es que miras la brizna que hay en el ojo de tu hermano, y no reparas en la viga que hay en tu propio ojo?

[[luke-6-42]]
^42^ ¿Cómo puedes decir a tu hermano: “Hermano, deja que saque la brizna que hay en tu ojo”, no viendo tú mismo la viga que hay en el tuyo? Hipócrita, saca primero la viga de tu ojo, y entonces podrás ver para sacar la brizna que hay en el ojo de tu hermano.

[[luke-6-43]]
^43^ «Porque no hay árbol bueno que dé fruto malo y, a la inversa, no hay árbol malo que dé fruto bueno.

[[luke-6-44]]
^44^ Cada árbol se conoce por su fruto. No se recogen higos de los espinos, ni de la zarza se vendimian uvas.

[[luke-6-45]]
^45^ El hombre bueno, del buen tesoro del corazón saca lo bueno, y el malo, del malo saca lo malo. Porque de lo que rebosa el corazón habla su boca.

[[luke-6-46]]
^46^ «¿Por qué me llamáis: “Señor, Señor”, y no hacéis lo que digo?

[[luke-6-47]]
^47^ «Todo el que venga a mí y oiga mis palabras y las ponga en práctica, os voy a mostrar a quién es semejante:

[[luke-6-48]]
^48^ Es semejante a un hombre que, al edificar una casa, cavó profundamente y puso los cimientos sobre roca. Al sobrevenir una inundación, rompió el torrente contra aquella casa, pero no pudo destruirla por estar bien edificada.

[[luke-6-49]]
^49^ Pero el que haya oído y no haya puesto en práctica, es semejante a un hombre que edificó una casa sobre tierra, sin cimientos, contra la que rompió el torrente y al instante se desplomó y fue grande la ruina de aquella casa».
[[luke-7]]
== Capítulo 7

[[luke-7-1]]
^1^ Cuando hubo acabado de dirigir todas estas palabras al pueblo, entró en Cafarnaúm.

[[luke-7-2]]
^2^ Se encontraba mal y a punto de morir un siervo de un centurión, muy querido de éste.

[[luke-7-3]]
^3^ Habiendo oído hablar de Jesús, envió donde él unos ancianos de los judíos, para rogarle que viniera y salvara a su siervo.

[[luke-7-4]]
^4^ Estos, llegando donde Jesús, le suplicaban insistentemente diciendo: «Merece que se lo concedas,

[[luke-7-5]]
^5^ porque ama a nuestro pueblo, y él mismo nos ha edificado la sinagoga».

[[luke-7-6]]
^6^ Iba Jesús con ellos y, estando ya no lejos de la casa, envió el centurión a unos amigos a decirle: «Señor, no te molestes, porque no soy digno de que entres bajo mi techo,

[[luke-7-7]]
^7^ por eso ni siquiera me consideré digno de salir a tu encuentro. Mándalo de palabra, y quede sano mi criado.

[[luke-7-8]]
^8^ Porque también yo, que soy un subalterno, tengo soldados a mis órdenes, y digo a éste: “Vete”, y va; y a otro: “Ven”, y viene; y a mi siervo: “Haz esto”, y lo hace».

[[luke-7-9]]
^9^ Al oír esto Jesús, quedó admirado de él, y volviéndose dijo a la muchedumbre que le seguía: «Os digo que ni en Israel he encontrado una fe tan grande».

[[luke-7-10]]
^10^ Cuando los enviados volvieron a la casa, hallaron al siervo sano.

[[luke-7-11]]
^11^ Y sucedió que a continuación se fue a una ciudad llamada Naím, e iban con él sus discípulos y una gran muchedumbre.

[[luke-7-12]]
^12^ Cuando se acercaba a la puerta de la ciuadad, sacaban a enterrar a un muerto, hijo único de su madre, que era viuda, a la que acompañaba mucha gente de la ciudad.

[[luke-7-13]]
^13^ Al verla el Señor, tuvo compasión de ella, y le dijo: «No llores».

[[luke-7-14]]
^14^ Y, acercándose, tocó el féretro. Los que lo llevaban se pararon, y él dijo: «Joven, a ti te digo: Levántate».

[[luke-7-15]]
^15^ El muerto se incorporó y se puso a hablar, y él se lo dio a su madre.

[[luke-7-16]]
^16^ El temor se apoderó de todos, y glorificaban a Dios, diciendo: «Un gran profeta se ha levantado entre nosotros», y «Dios ha visitado a su pueblo».

[[luke-7-17]]
^17^ Y lo que se decía de él, se propagó por toda Judea y por toda la región circunvecina.

[[luke-7-18]]
^18^ Sus discípulos llevaron a Juan todas estas noticias. Entonces él, llamando a dos de ellos,

[[luke-7-19]]
^19^ los envió a decir al Señor: «¿Eres tú el que ha de venir, o debemos esperar a otro?»

[[luke-7-20]]
^20^ Llegando donde él aquellos hombres, dijeron: «Juan el Bautista nos ha enviado a decirte: ¿Eres tú el que ha de venir o debemos esperar a otro?»

[[luke-7-21]]
^21^ En aquel momento curó a muchos de sus enfermedades y dolencias, y de malos espíritus, y dio vista a muchos ciegos.

[[luke-7-22]]
^22^ Y les respondió: «Id y contad a Juan lo que habéis visto y oído: Los ciegos ven, los cojos andan, los leprosos quedan limpios, los sordos oyen, los muertos resucitan, se anuncia a los pobres la Buena Nueva;

[[luke-7-23]]
^23^ ¡y dichoso aquel que no halle escándalo en mí!»

[[luke-7-24]]
^24^ Cuando los mensajeros de Juan se alejaron, se puso a hablar de Juan a la gente: «¿Qué salisteis a ver en el desierto? ¿Una caña agitada por el viento?

[[luke-7-25]]
^25^ ¿Qué salisteis a ver, si no? ¿Un hombre elegantemente vestido? ¡No! Los que visten magníficamente y viven con molicie están en los palacios.

[[luke-7-26]]
^26^ Entonces, ¿qué salisteis a ver? ¿Un profeta? Sí, os digo, y más que un profeta.

[[luke-7-27]]
^27^ Este es de quien está escrito: He aquí que envío mi mensajero delante de ti, que preparará por delante tu camino.

[[luke-7-28]]
^28^ «Os digo: Entre los nacidos de mujer no hay ninguno mayor que Juan; sin embargo el más pequeño en el Reino de Dios es mayor que él.

[[luke-7-29]]
^29^ Todo el pueblo que le escuchó, incluso los publicanos, reconocieron la justicia de Dios, haciéndose bautizar con el bautismo de Juan.

[[luke-7-30]]
^30^ Pero los fariseos y los legistas, al no aceptar el bautismo de él, frustraron el plan de Dios sobre ellos.

[[luke-7-31]]
^31^ «¿Con quién, pues, compararé a los hombres de esta generacíon? Y ¿a quién se parecen?

[[luke-7-32]]
^32^ Se parecen a los chiquillos que están sentados en la plaza y se gritan unos a otros diciendo: “Os hemos tocado la flauta, y no habéis bailado, os hemos entonando endechas, y no habéis llorado.”

[[luke-7-33]]
^33^ «Porque ha venido Juan el Bautista, que no comía pan ni bebía vino, y decís: “Demonio tiene.”

[[luke-7-34]]
^34^ Ha venido el Hijo del hombre, que come y bebe, y decís: “Ahí tenéis un comilón y un borracho, amigo de publicanos y pecadores.”

[[luke-7-35]]
^35^ Y la Sabiduría se ha acreditado por todos sus hijos».

[[luke-7-36]]
^36^ Un fariseo le rogó que comiera con él, y, entrando en la casa del fariseo, se puso a la mesa.

[[luke-7-37]]
^37^ Había en la ciudad una mujer pecadora pública, quien al saber que estaba comiendo en casa del fariseo, llevó un frasco de alabastro de perfume,

[[luke-7-38]]
^38^ y poniéndose detrás, a los pies de él, comenzó a llorar, y con sus lágrimas le mojaba los pies y con los cabellos de su cabeza se los secaba; besaba sus pies y los ungía con el perfume.

[[luke-7-39]]
^39^ Al verlo el fariseo que le había invitado, se decía para sí: «Si éste fuera profeta, sabría quién y qué clase de mujer es la que le está tocando, pues es una pecadora».

[[luke-7-40]]
^40^ Jesús le respondió: «Simón, tengo algo que decirte». El dijo: «Di, maestro».

[[luke-7-41]]
^41^ Un acreedor tenía dos deudores: uno debía quinientos denarios y el otro cincuenta.

[[luke-7-42]]
^42^ Como no tenían para pagarle, perdonó a los dos. ¿Quién de ellos le amará más?»

[[luke-7-43]]
^43^ Respondió Simón: «Supongo que aquel a quien perdonó más». El le dijo: «Has juzgado bien»,

[[luke-7-44]]
^44^ y volviéndose hacia la mujer, dijo a Simón: «¿Ves a esta mujer? Entré en tu casa y no me diste agua para los pies. Ella, en cambio, ha mojado mis pies con lágrimas, y los ha secado con sus cabellos.

[[luke-7-45]]
^45^ No me diste el beso. Ella, desde que entró, no ha dejado de besarme los pies.

[[luke-7-46]]
^46^ No ungiste mi cabeza con aceite. Ella ha ungido mis pies con perfume.

[[luke-7-47]]
^47^ Por eso te digo que quedan perdonados sus muchos pecados, porque ha mostrado mucho amor. A quien poco se le perdona, poco amor muestra».

[[luke-7-48]]
^48^ Y le dijo a ella: «Tus pecados quedan perdonados».

[[luke-7-49]]
^49^ Los comensales empezaron a decirse para sí: «¿Quién es éste que hasta perdona los pecados?»

[[luke-7-50]]
^50^ Pero él dijo a la mujer: «Tu fe te ha salvado. Vete en paz».
[[luke-8]]
== Capítulo 8

[[luke-8-1]]
^1^ Y sucedió a continuación que iba por ciudades y pueblos, proclamando y anunciando la Buena Nueva del Reino de Dios; le acompañaban los Doce,

[[luke-8-2]]
^2^ y algunas mujeres que habían sido curadas de espíritus malignos y enfermedades: María, llamada Magdalena, de la que habían salido siete demonios,

[[luke-8-3]]
^3^ Juana, mujer de Cusa, un administrador de Herodes, Susana y otras muchas que les servían con sus bienes.

[[luke-8-4]]
^4^ Habiéndose congregado mucha gente, y viniendo a él de todas las ciudades, dijo en parábola:

[[luke-8-5]]
^5^ «Salió un sembrador a sembrar su simiente; y al sembrar, una parte cayó a lo largo del camino, fue pisada, y las aves del cielo se la comieron;

[[luke-8-6]]
^6^ otra cayó sobre piedra, y después de brotar, se secó, por no tener humedad;

[[luke-8-7]]
^7^ otra cayó en medio de abrojos, y creciendo con ella los abrojos, la ahogaron.

[[luke-8-8]]
^8^ Y otra cayó en tierra buena, y creciendo dio fruto centuplicado». Dicho esto, exclamó: «El que tenga oídos para oír, que oiga».

[[luke-8-9]]
^9^ Le preguntaban sus discípulos qué significaba esta parábola,

[[luke-8-10]]
^10^ y él dijo: «A vosotros se os ha dado el conocer los misterios del Reino de Dios; a los demás sólo en parábolas, para que viendo, no vean y, oyendo, no entiendan.

[[luke-8-11]]
^11^ «La parábola quiere decir esto: La simiente es la Palabra de Dios.

[[luke-8-12]]
^12^ Los de a lo largo del camino, son los que han oído; después viene el diablo y se lleva de su corazón la Palabra, no sea que crean y se salven.

[[luke-8-13]]
^13^ Los de sobre piedra son los que, al oír la Palabra, la reciben con alegría; pero éstos no tienen raíz; creen por algún tiempo, pero a la hora de la prueba desisten.

[[luke-8-14]]
^14^ Lo que cayó entre los abrojos, son los que han oído, pero a lo largo de su caminar son ahogados por las preocupaciones, las riquezas y los placeres de la vida, y no llegan a madurez.

[[luke-8-15]]
^15^ Lo que en buena tierra, son los que, después de haber oído, conservan la Palabra con corazón bueno y recto, y dan fruto con perseverancia.

[[luke-8-16]]
^16^ «Nadie enciende una lámpara y la cubre con una vasija, o la pone debajo de un lecho, sino que la pone sobre un candelero, para que los que entren vean la luz.

[[luke-8-17]]
^17^ Pues nada hay oculto que no quede manifiesto, y nada secreto que no venga a ser conocido y descubierto.

[[luke-8-18]]
^18^ Mirad, pues, cómo oís; porque al que tenga, se le dará; y al que no tenga, aun lo que crea tener se le quitará».

[[luke-8-19]]
^19^ Se presentaron donde él su madre y sus hermanos, pero no podían llegar hasta él a causa de la gente.

[[luke-8-20]]
^20^ Le anunciaron: «Tu madre y tus hermanos están ahí fuera y quieren verte».

[[luke-8-21]]
^21^ Pero él les respondió: «Mi madre y mis hermanos son aquellos que oyen la Palabra de Dios y la cumplen».

[[luke-8-22]]
^22^ Sucedió que cierto día subió a una barca con sus discípulos, y les dijo: «Pasemos a la otra orilla del lago». Y se hicieron a la mar.

[[luke-8-23]]
^23^ Mientras ellos navegaban, se durmió. Se abatió sobre el lago una borrasca; se inundaba la barca y estaban en peligro.

[[luke-8-24]]
^24^ Entonces, acercándose, le despertaron, diciendo: «¡Maestro, Maestro, que perecemos!» El, habiéndose despertado, increpó al viento y al oleaje, que amainaron, y sobrevino la bonanza.

[[luke-8-25]]
^25^ Entonces les dijo: «¿Dónde está vuestra fe?» Ellos, llenos de temor, se decían entre sí maravillados: «Pues ¿quién es éste, que impera a los vientos y al agua, y le obedecen?»

[[luke-8-26]]
^26^ Arribaron a la región de los gerasenos, que está frente a Galilea.

[[luke-8-27]]
^27^ Al saltar a tierra, vino de la ciudad a su encuentro un hombre, poseído por los demonios, y que hacía mucho tiempo que no llevaba vestido, ni moraba en una casa, sino en los sepulcros.

[[luke-8-28]]
^28^ Al ver a Jesús, cayó ante él, gritando con gran voz: «¿Qué tengo yo contigo, Jesús, Hijo de Dios Altísimo? Te suplico que no me atormentes».

[[luke-8-29]]
^29^ Es que él había mandado al espíritu inmundo que saliera de aquel hombre; pues en muchas ocasiones se apoderaba de él; le sujetaban con cadenas y grillos para custodiarle, pero rompiendo las ligaduras era empujado por el demonio al desierto.

[[luke-8-30]]
^30^ Jesús le preguntó: «¿Cuál es tu nombre? «El contestó: «Legión»; porque habían entrado en él muchos demonios.

[[luke-8-31]]
^31^ Y le suplicaban que no les mandara irse al abismo.

[[luke-8-32]]
^32^ Había allí una gran piara de puercos que pacían en el monte; y le suplicaron que les permitiera entrar en ellos; y se lo permitió.

[[luke-8-33]]
^33^ Salieron los demonios de aquel hombre y entraron en los puercos; y la piara se arrojó al lago de lo alto del precipicio, y se ahogó.

[[luke-8-34]]
^34^ Viendo los porqueros lo que había pasado, huyeron y lo contaron por la ciudad y por las aldeas.

[[luke-8-35]]
^35^ Salieron, pues, a ver lo que había occurido y, llegando donde Jesús, encontraron al hombre del que habían salido los demonios, sentado, vestido y en su sano juicio, a los pies de Jesús; y se llenaron de temor.

[[luke-8-36]]
^36^ Los que lo habían visto, les contaron cómo había sido salvado el endemoniado.

[[luke-8-37]]
^37^ Entonces toda la gente del país de los gerasenos le rogaron que se alejara de ellos, porque estaban poseídos de gran temor. El, subiendo a la barca, regresó.

[[luke-8-38]]
^38^ El hombre de quien habían salido los demonios, le pedía estar con él; pero le despidió, diciendo:

[[luke-8-39]]
^39^ «Vuelve a tu casa y cuenta todo lo que Dios ha hecho contigo». Y fue por toda la ciudad proclamando todo lo que Jesús había hecho con él.

[[luke-8-40]]
^40^ Cuando regresó Jesús, le recibió la muchedumbre, pues todos le estaban esperando.

[[luke-8-41]]
^41^ Y he aquí que llegó un hombre, llamado Jairo, que era jefe de la sinagoga, y cayendo a los pies de Jesús, le suplicaba entrara en su casa,

[[luke-8-42]]
^42^ porque tenía una sola hija, de unos doce años, que estaba muriéndose. Mientras iba, las gentes le ahogaban.

[[luke-8-43]]
^43^ Entonces, una mujer que padecía flujo de sangre desde hacía doce años, y que no había podido ser curada por nadie,

[[luke-8-44]]
^44^ se acercó por detrás y tocó la orla de su manto, y al punto se le paró el flujo de sangre.

[[luke-8-45]]
^45^ Jesús dijo: «¿Quién me ha tocado?» Como todos negasen, dijo Pedro: «Maestro, las gentes te aprietan y te oprimen».

[[luke-8-46]]
^46^ Pero Jesús dijo: «Alguien me ha tocado, porque he sentido que una fuerza ha salido de mí».

[[luke-8-47]]
^47^ Viéndose descubierta la mujer, se acercó temblorosa, y postrándose ante él, contó delante de todo el pueblo por qué razón le había tocado, y cómo al punto había sido curada.

[[luke-8-48]]
^48^ El le dijo: «Hija, tu fe te ha salvado; vete en paz».

[[luke-8-49]]
^49^ Estaba todavía hablando, cuando uno de casa del jefe de la sinagoga llega diciendo: «Tu hija está muerta. No molestes ya al Maestro».

[[luke-8-50]]
^50^ Jesús, que lo oyó, le dijo: «No temas; solamente ten fe y se salvará».

[[luke-8-51]]
^51^ Al llegar a la casa, no permitió entrar con él más que a Pedro, Juan y Santiago, al padre y a la madre de la niña.

[[luke-8-52]]
^52^ Todos la lloraban y se lamentaban, pero él dijo: «No lloréis, no ha muerto; está dormida».

[[luke-8-53]]
^53^ Y se burlaban de él, pues sabían que estaba muerta.

[[luke-8-54]]
^54^ El, tomándola de la mano, dijo en voz alta: «Niña, levántate».

[[luke-8-55]]
^55^ Retornó el espíritu a ella, y al punto se levantó; y él mandó que le dieran a ella de comer.

[[luke-8-56]]
^56^ Sus padres quedaron estupefactos, y él les ordenó que a nadie dijeran lo que había pasado.
[[luke-9]]
== Capítulo 9

[[luke-9-1]]
^1^ Convocando a los Doce, les dio autoridad y poder sobre todos los demonios, y para curar enfermedades;

[[luke-9-2]]
^2^ y los envió a proclamar el Reino de Dios y a curar.

[[luke-9-3]]
^3^ Y les dijo: «No toméis nada para el camino, ni bastón, ni alforja, ni pan, ni plata; ni tengáis dos túnicas cada uno.

[[luke-9-4]]
^4^ Cuando entréis en una casa, quedaos en ella hasta que os marchéis de allí.

[[luke-9-5]]
^5^ En cuanto a los que no os reciban, saliendo de aquella ciudad, sacudid el polvo de vuestros pies en testimonio contra ellos».

[[luke-9-6]]
^6^ Saliendo, pues, recorrían los pueblos, anunciando la Buena Nueva y curando por todas partes.

[[luke-9-7]]
^7^ Se enteró el tetrarca Herodes de todo lo que pasaba, y estaba perplejo; porque unos decían que Juan había resucitado de entre los muertos;

[[luke-9-8]]
^8^ otros, que Elías se había aparecido; y otros, que uno de los antiguos profetas había resucitado.

[[luke-9-9]]
^9^ Herodes dijo: «A Juan, le decapité yo. ¿Quién es, pues, éste de quien oigo tales cosas?» Y buscaba verle.

[[luke-9-10]]
^10^ Cuando los apóstoles regresaron, le contaron cuanto habían hecho. Y él, tomándolos consigo, se retiró aparte, hacia una ciudad llamada Bestsaida.

[[luke-9-11]]
^11^ Pero las gentes lo supieron, y le siguieron; y él, acogiéndolas, les hablabla acerca del Reino de Dios, y curaba a los que tenían necesidad de ser curados.

[[luke-9-12]]
^12^ Pero el día había comenzado a declinar, y acercándose los Doce, le dijeron: «Despide a la gente para que vayan a los pueblos y aldeas del contorno y busquen alojamiento y comida, porque aquí estamos en un lugar deshabitado».

[[luke-9-13]]
^13^ El les dijo: «Dadles vosotros de comer». Pero ellos respondieron: «No tenemos más que cinco panes y dos peces; a no ser que vayamos nosotros a comprar alimentos para toda esta gente».

[[luke-9-14]]
^14^ Pues había como 5.000 hombres. El dijo a sus discípulos: «Haced que se acomoden por grupos de unos cincuenta».

[[luke-9-15]]
^15^ Lo hicieron así, e hicieron acomodarse a todos.

[[luke-9-16]]
^16^ Tomó entonces los cinco panes y los dos peces, y levantando los ojos al cielo, pronunció sobre ellos la bendición y los partió, y los iba dando a los discípulos para que los fueran sirviendo a la gente.

[[luke-9-17]]
^17^ Comieron todos hasta saciarse. Se recogieron los trozos que les habían sobrado: doce canastos.

[[luke-9-18]]
^18^ Y sucedió que mientras él estaba orando a solas, se hallaban con él los discípulos y él les preguntó: «¿Quién dice la gente que soy yo?»

[[luke-9-19]]
^19^ Ellos respondieron: «Unos, que Juan el Bautista; otros, que Elías; otros, que un profeta de los antiguos había resucitado».

[[luke-9-20]]
^20^ Les dijo: «Y vosotros, ¿quién decís que soy yo?» Pedro le contestó: «El Cristo de Dios».

[[luke-9-21]]
^21^ Pero les mandó enérgicamente que no dijeran esto a nadie.

[[luke-9-22]]
^22^ Dijo: «El Hijo del hombre debe sufrir mucho, y ser reprobado por los ancianos, los sumos sacerdotes y los escribas, ser matado y resucitar al tercer día».

[[luke-9-23]]
^23^ Decía a todos: «Si alguno quiere venir en pos de mí, niéguese a sí mismo, tome su cruz cada día, y sígame.

[[luke-9-24]]
^24^ Porque quien quiera salvar su vida, la perderá; pero quien pierda su vida por mí, ése la salvará.

[[luke-9-25]]
^25^ Pues, ¿de qué le sirve al hombre haber ganado el mundo entero, si él mismo se pierde o se arruina?

[[luke-9-26]]
^26^ Porque quien se avergüence de mí y de mis palabras, de ése se avergonzará el Hijo del hombre, cuando venga en su gloria, en la de su Padre y en la de los santos ángeles.

[[luke-9-27]]
^27^ «Pues de verdad os digo que hay algunos, entre los aquí presentes, que no gustarán la muerte hasta que vean el Reino de Dios».

[[luke-9-28]]
^28^ Sucedió que unos ocho días después de estas palabras, tomó consigo a Pedro, Juan y Santiago, y subió al monte a orar.

[[luke-9-29]]
^29^ Y sucedió que, mientras oraba, el aspecto de su rostro se mudó, y sus vestidos eran de una blancura fulgurante,

[[luke-9-30]]
^30^ y he aquí que conversaban con él dos hombres, que eran Moisés y Elías;

[[luke-9-31]]
^31^ los cuales aparecían en gloria, y hablaban de su partida, que iba a cumplir en Jerusalén.

[[luke-9-32]]
^32^ Pedro y sus compañeros estaban cargados de sueño, pero permanecían despiertos, y vieron su gloria y a los dos hombres que estaban con él.

[[luke-9-33]]
^33^ Y sucedió que, al separarse ellos de él, dijo Pedro a Jesús: «Maestro, bueno es estarnos aquí. Vamos a hacer tres tiendas, una para ti, otra para Moisés y otra para Elías», sin saber lo que decía.

[[luke-9-34]]
^34^ Estaba diciendo estas cosas cuando se formó una nube y los cubrió con su sombra; y al entrar en la nube, se llenaron de temor.

[[luke-9-35]]
^35^ Y vino una voz desde la nube, que decía: «Este es mi Hijo, mi Elegido; escuchadle».

[[luke-9-36]]
^36^ Y cuando la voz hubo sonado, se encontró Jesús solo. Ellos callaron y, por aquellos días, no dijeron a nadie nada de lo que habían visto.

[[luke-9-37]]
^37^ Sucedió que al día siguiente, cuando bajaron del monte, le salió al encuentro mucha gente.

[[luke-9-38]]
^38^ En esto, un hombre de entre la gente empezó a gritar: «Maestro, te suplico que mires a mi hijo, porque es el único que tengo,

[[luke-9-39]]
^39^ y he aquí que un espíritu se apodera de él y de pronto empieza a dar gritos, le hace retorcerse echando espuma, y difícilmente se aparta de él, dejándole quebrantado.

[[luke-9-40]]
^40^ He pedido a tus discípulos que lo expulsaran, pero no han podido».

[[luke-9-41]]
^41^ Respondió Jesús: «¡Oh generación incrédula y perversa! ¿Hasta cuándo estaré con vosotros y habré de soportaros? ¡Trae acá a tu hijo!»

[[luke-9-42]]
^42^ Cuando se acercaba, el demonio le arrojó por tierra y le agitó violentamente; pero Jesús increpó al espíritu inmundo, curó al niño y lo devolvió a su padre;

[[luke-9-43]]
^43^ y todos quedaron atónitos ante la grandeza de Dios. Estando todos maravillados por todas las cosas que hacía, dijo a sus discípulos:

[[luke-9-44]]
^44^ «Poned en vuestros oídos estas palabras: el Hijo del hombre va a ser entregado en manos de los hombres».

[[luke-9-45]]
^45^ Pero ellos no entendían lo que les decía; les estaba velado de modo que no lo comprendían y temían preguntarle acerca de este asunto.

[[luke-9-46]]
^46^ Se suscitó una discusión entre ellos sobre quién de ellos sería el mayor.

[[luke-9-47]]
^47^ Conociendo Jesús lo que pensaban en su corazón, tomó a un niño, le puso a su lado,

[[luke-9-48]]
^48^ y les dijo: «El que reciba a este niño en mi nombre, a mí me recibe; y el que me reciba a mí, recibe a Aquel que me ha enviado; pues el más pequeño de entre vosotros, ése es mayor».

[[luke-9-49]]
^49^ Tomando Juan la palabra, dijo: «Maestro, hemos visto a uno que expulsaba demonios en tu nombre, y tratamos de impedírselo, porque no viene con nosotros».

[[luke-9-50]]
^50^ Pero Jesús le dijo: «No se lo impidáis, pues el que no está contra vosotros, está por vosotros».

[[luke-9-51]]
^51^ Sucedió que como se iban cumpliendo los días de su asunción, él se afirmó en su voluntad de ir a Jerusalén,

[[luke-9-52]]
^52^ y envió mensajeros delante de sí, que fueron y entraron en un pueblo de samaritanos para prepararle posada;

[[luke-9-53]]
^53^ pero no le recibieron porque tenía intención de ir a Jerusalén.

[[luke-9-54]]
^54^ Al verlo sus discípulos Santiago y Juan, dijeron: «Señor, ¿quieres que digamos que baje fuego del cielo y los consuma?»

[[luke-9-55]]
^55^ Pero volviéndose, les reprendió;

[[luke-9-56]]
^56^ y se fueron a otro pueblo.

[[luke-9-57]]
^57^ Mientras iban caminando, uno le dijo: «Te seguiré adondequiera que vayas».

[[luke-9-58]]
^58^ Jesús le dijo: «Las zorras tienen guaridas, y las aves del cielo nidos; pero el Hijo del hombre no tiene donde reclinar la cabeza».

[[luke-9-59]]
^59^ A otro dijo: «Sígueme». El respondió: «Déjame ir primero a enterrar a mi padre».

[[luke-9-60]]
^60^ Le respondió: «Deja que los muertos entierren a sus muertos; tú vete a anunciar el Reino de Dios».

[[luke-9-61]]
^61^ También otro le dijo: «Te seguiré, Señor; pero déjame antes despedirme de los de mi casa».

[[luke-9-62]]
^62^ Le dijo Jesús: «Nadie que pone la mano en el arado y mira hacia atrás es apto para el Reino de Dios».
[[luke-10]]
== Capítulo 10

[[luke-10-1]]
^1^ Después de esto, designó el Señor a otros 72, y los envió de dos en dos delante de sí, a todas las ciudades y sitios a donde él había de ir.

[[luke-10-2]]
^2^ Y les dijo: «La mies es mucha, y los obreros pocos. Rogad, pues, al Dueño de la mies que envíe obreros a su mies.

[[luke-10-3]]
^3^ Id; mirad que os envío como corderos en medio de lobos.

[[luke-10-4]]
^4^ No llevéis bolsa, ni alforja, ni sandalias. Y no saludéis a nadie en el camino.

[[luke-10-5]]
^5^ En la casa en que entréis, decid primero: “Paz a esta casa.”

[[luke-10-6]]
^6^ Y si hubiere allí un hijo de paz, vuestra paz reposará sobre él; si no, se volverá a vosotros.

[[luke-10-7]]
^7^ Permaneced en la misma casa, comiendo y bebiendo lo que tengan, porque el obrero merece su salario. No vayáis de casa en casa.

[[luke-10-8]]
^8^ En la ciudad en que entréis y os reciban, comed lo que os pongan;

[[luke-10-9]]
^9^ curad los enfermos que haya en ella, y decidles: “El Reino de Dios está cerca de vosotros.”

[[luke-10-10]]
^10^ En la ciudad en que entréis y no os reciban, salid a sus plazas y decid:

[[luke-10-11]]
^11^ “Hasta el polvo de vuestra ciuadad que se nos ha pegado a los pies, os lo sacudimos. Pero sabed, con todo, que el Reino de Dios está cerca.”

[[luke-10-12]]
^12^ Os digo que en aquel Día habrá menos rigor para Sodoma que para aquella ciudad.

[[luke-10-13]]
^13^ «¡Ay de ti, Corazin! ¡Ay de ti, Betsaida! Porque si en Tiro y en Sidón se hubieran hecho los milagros que se han hecho en vosotras, tiempo ha que, sentados con sayal y ceniza, se habrían convertido.

[[luke-10-14]]
^14^ Por eso, en el Juicio habrá menos rigor para Tiro y Sidón que para vosotras.

[[luke-10-15]]
^15^ Y tú, Cafarnaúm, ¿hasta el cielo te vas a encumbrar? ¡Hasta el Hades te hundirás!

[[luke-10-16]]
^16^ «Quien a vosotros os escucha, a mí me escucha; y quien a vosotros os rechaza, a mí me rechaza; y quien me rechaza a mí, rechaza al que me ha enviado».

[[luke-10-17]]
^17^ Regresaron los 72 alegres, diciendo: «Señor, hasta los demonios se nos someten en tu nombre».

[[luke-10-18]]
^18^ El les dijo: «Yo veía a Satanás caer del cielo como un rayo.

[[luke-10-19]]
^19^ Mirad, os he dado el poder de pisar sobre serpientes y escorpiones, y sobre todo poder del enemigo, y nada os podrá hacer daño;

[[luke-10-20]]
^20^ pero no os alegréis de que los espíritus se os sometan; alegraos de que vuestros nombres estén escritos en los cielos».

[[luke-10-21]]
^21^ En aquel momento, se llenó de gozo Jesús en el Espíritu Santo, y dijo: «Yo te bendigo, Padre, Señor del cielo y de la tierra, porque has ocultado estas cosas a sabios e inteligentes, y se las has revelado a pequeños. Sí, Padre, pues tal ha sido tu beneplácito.

[[luke-10-22]]
^22^ Todo me ha sido entregado por mi Padre, y nadie conoce quién es el Hijo sino el Padre; y quién es el Padre sino el Hijo, y aquel a quien el Hijo se lo quiera revelar».

[[luke-10-23]]
^23^ Volviéndose a los discípulos, les dijo aparte: «¡Dichosos los ojos que ven lo que veis!

[[luke-10-24]]
^24^ Porque os digo que muchos profetas y reyes quisieron ver lo que vosotros veis, pero no lo vieron, y oír lo que vosotros oís, pero no lo oyeron».

[[luke-10-25]]
^25^ Se levantó un legista, y dijo para ponerle a prueba: «Maestro, ¿que he de hacer para tener en herencia vida eterna?»

[[luke-10-26]]
^26^ El le dijo: «¿Qué está escrito en la Ley? ¿Cómo lees?»

[[luke-10-27]]
^27^ Respondió: «Amarás al Señor tu Dios con todo tu corazón, con toda tu alma, con todas tus fuerzas y con toda tu mente; y a tu prójimo como a ti mismo».

[[luke-10-28]]
^28^ Díjole entonces: «Bien has respondido. Haz eso y vivirás».

[[luke-10-29]]
^29^ Pero él, queriendo justificarse, dijo a Jesús: «Y ¿quién es mi prójimo?»

[[luke-10-30]]
^30^ Jesús respondió: «Bajaba un hombre de Jerusalén a Jericó, y cayó en manos de salteadores, que, después de despojarle y golpearle, se fueron dejándole medio muerto.

[[luke-10-31]]
^31^ Casualmente, bajaba por aquel camino un sacerdote y, al verle, dio un rodeo.

[[luke-10-32]]
^32^ De igual modo, un levita que pasaba por aquel sitio le vio y dio un rodeo.

[[luke-10-33]]
^33^ Pero un samaritano que iba de camino llegó junto a él, y al verle tuvo compasión;

[[luke-10-34]]
^34^ y, acercándose, vendó sus heridas, echando en ellas aceite y vino; y montándole sobre su propia cabalgadura, le llevó a una posada y cuidó de él.

[[luke-10-35]]
^35^ Al día siguiente, sacando dos denarios, se los dio al posadero y dijo: “Cuida de él y, si gastas algo más, te lo pagaré cuando vuelva.”

[[luke-10-36]]
^36^ ¿Quién de estos tres te parece que fue prójimo del que cayó en manos de los salteadores?»

[[luke-10-37]]
^37^ El dijo: «El que practicó la misericordia con él». Díjole Jesús: «Vete y haz tú lo mismo».

[[luke-10-38]]
^38^ Yendo ellos de camino, entró en un pueblo; y una mujer, llamada Marta, le recibió en su casa.

[[luke-10-39]]
^39^ Tenía ella una hermana llamada María, que, sentada a los pies del Señor, escuchaba su Palabra,

[[luke-10-40]]
^40^ mientras Marta estaba atareada en muchos quehaceres. Acercándose, pues, dijo: «Señor, ¿no te importa que mi hermana me deje sola en el trabajo? Dile, pues, que me ayude».

[[luke-10-41]]
^41^ Le respondió el Señor: «Marta, Marta, te preocupas y te agitas por muchas cosas;

[[luke-10-42]]
^42^ y hay necesidad de pocas, o mejor, de una sola. María ha elegido la parte buena, que no le será quitada».
[[luke-11]]
== Capítulo 11

[[luke-11-1]]
^1^ Y sucedió que, estando él orando en cierto lugar, cuando terminó, le dijo uno de sus discípulos: «Señor, ensénanos a orar, como enseñó Juan a sus discípulos».

[[luke-11-2]]
^2^ El les dijo: «Cuando oréis, decid: Padre, santificado sea tu Nombre, venga tu Reino,

[[luke-11-3]]
^3^ danos cada día nuestro pan cotidiano,

[[luke-11-4]]
^4^ y perdónanos nuestros pecados porque también nosotros perdonamos a todo el que nos debe, y no nos dejes caer en tentación».

[[luke-11-5]]
^5^ Les dijo también: «Si uno de vosotros tiene un amigo y, acudiendo a él a medianoche, le dice: “Amigo, préstame tres panes,

[[luke-11-6]]
^6^ porque ha llegado de viaje a mi casa un amigo mío y no tengo qué ofrecerle”,

[[luke-11-7]]
^7^ y aquél, desde dentro, le responde: “No me molestes; la puerta ya está cerrada, y mis hijos y yo estamos acostados; no puedo levantarme a dártelos”,

[[luke-11-8]]
^8^ os aseguro, que si no se levanta a dárselos por ser su amigo, al menos se levantará por su importunidad, y le dará cuanto necesite».

[[luke-11-9]]
^9^ Yo os digo: «Pedid y se os dará; buscad y hallaréis; llamad y se os abrirá.

[[luke-11-10]]
^10^ Porque todo el que pide, recibe; el que busca, halla; y al que llama, se le abrirá.

[[luke-11-11]]
^11^ ¿Qué padre hay entre vosotros que, si su hijo le pide un pez, en lugar de un pez le da una culebra;

[[luke-11-12]]
^12^ o, si pide un huevo, le da un escorpión?

[[luke-11-13]]
^13^ Si, pues, vosotros, siendo malos, sabéis dar cosas buenas a vuestros hijos, ¡cuánto más el Padre del cielo dará el Espíritu Santo a los que se lo pidan!»

[[luke-11-14]]
^14^ Estaba expulsando un demonio que era mudo; sucedió que, cuando salió el demonio, rompió a hablar el mudo, y las gentes se admiraron.

[[luke-11-15]]
^15^ Pero algunos de ellos dijeron: «Por Beelzebul, Príncipe de los demonios, expulsa los demonios».

[[luke-11-16]]
^16^ Otros, para ponerle a prueba, le pedían una señal del cielo.

[[luke-11-17]]
^17^ Pero él, conociendo sus pensamientos, les dijo: «Todo reino dividido contra sí mismo queda asolado, y casa contra casa, cae.

[[luke-11-18]]
^18^ Si, pues, también Satanás está dividido contra sí mismo, ¿cómo va a subsistir su reino?.. porque decís que yo expulso los demonios por Beelzebul.

[[luke-11-19]]
^19^ Si yo expulso los demonios por Beelzebul, ¿por quién los expulsan vuestros hijos? Por eso, ellos serán vuestros jueces.

[[luke-11-20]]
^20^ Pero si por el dedo de Dios expulso yo los demonios, es que ha llegado a vosotros el Reino de Dios.

[[luke-11-21]]
^21^ Cuando uno fuerte y bien armado custodia su palacio, sus bienes están en seguro;

[[luke-11-22]]
^22^ pero si llega uno más fuerte que él y le vence, le quita las armas en las que estaba confiado y reparte sus despojos».

[[luke-11-23]]
^23^ «El que no está conmigo, está contra mí, y el que no recoge conmigo, desparrama.

[[luke-11-24]]
^24^ «Cuando el espíritu inmundo sale del hombre, anda vagando por lugares áridos, en busca de reposo; y, al no encontrarlo, dice: “Me volveré a mi casa, de donde salí.”

[[luke-11-25]]
^25^ Y al llegar la encuentra barrida y en orden.

[[luke-11-26]]
^26^ Entonces va y toma otros siete espíritus peores que él; entran y se instalan allí, y el final de aquel hombre viene a ser peor que el principio».

[[luke-11-27]]
^27^ Sucedió que, estando él diciendo estas cosas, alzó la voz una mujer de entre la gente, y dijo: «¡Dichoso el seno que te llevó y los pechos que te criaron!»

[[luke-11-28]]
^28^ Pero él dijo: «Dichosos más bien los que oyen la Palabra de Dios y la guardan».

[[luke-11-29]]
^29^ Habiéndose reunido la gente, comenzó a decir: «Esta generación es una generación malvada; pide una señal, y no se le dará otra señal que la señal de Jonás.

[[luke-11-30]]
^30^ Porque, así como Jonás fue señal para los ninivitas, así lo será el Hijo del hombre para esta generación.

[[luke-11-31]]
^31^ La reina del Mediodía se levantará en el Juicio con los hombres de esta generación y los condenará: porque ella vino de los confines de la tierra a oír la sabiduría de Salomón, y aquí hay algo más que Salomón.

[[luke-11-32]]
^32^ Los ninivitas se levantarán en el Juicio con esta generación y la condenarán; porque ellos se convirtieron por la predicación de Jonás, y aquí hay algo más que Jonás.

[[luke-11-33]]
^33^ «Nadie enciende una lámpara y la pone en sitio oculto, ni bajo el celemín, sino sobre el candelero, para que los que entren vean el resplandor.

[[luke-11-34]]
^34^ La lámpara de tu cuerpo es tu ojo. Cuando tu ojo está sano, también todo tu cuerpo está luminoso; pero cuando está malo, también tu cuerpo está a oscuras.

[[luke-11-35]]
^35^ Mira, pues, que la luz que hay en ti no sea oscuridad.

[[luke-11-36]]
^36^ Si, pues, tu cuerpo está enteramente luminoso, no teniendo parte alguna oscura, estará tan enteramente luminoso, como cuando la lámpara te ilumina con su fulgor».

[[luke-11-37]]
^37^ Mientras hablaba, un fariseo le rogó que fuera a comer con él; entrando, pues, se puso a la mesa.

[[luke-11-38]]
^38^ Pero el fariseo se quedó admirado viendo que había omitido las abluciones antes de comer.

[[luke-11-39]]
^39^ Pero el Señor le dijo: «¡Bien! Vosotros, los fariseos, purificáis por fuera la copa y el plato, mientras por dentro estáis llenos de rapiña y maldad.

[[luke-11-40]]
^40^ ¡Insensatos! el que hizo el exterior, ¿no hizo también el interior?

[[luke-11-41]]
^41^ Dad más bien en limosna lo que tenéis, y así todas las cosas serán puras para vosotros.

[[luke-11-42]]
^42^ Pero, ¡ay de vosotros, los fariseos, que pagáis el diezmo de la menta, de la ruda y de toda hortaliza, y dejáis a un lado la justicia y el amor a Dios! Esto es lo que había que practicar aunque sin omitir aquello.

[[luke-11-43]]
^43^ ¡Ay de vosotros, los fariseos, que amáis el primer asiento en las sinagogas y que se os salude en las plazas!

[[luke-11-44]]
^44^ ¡Ay de vosotros, pues sois como los sepulcros que no se ven, sobre los que andan los hombres sin saberlo!»

[[luke-11-45]]
^45^ Uno de los legistas le respondió: «¡Maestro, diciendo estas cosas, también nos injurias a nosotros!»

[[luke-11-46]]
^46^ Pero él dijo: «¡Ay también de vosotros, los legistas, que imponéis a los hombres cargas intolerables, y vosotros no las tocáis ni con uno de vuestros dedos!

[[luke-11-47]]
^47^ «¡Ay de vosotros, porque edificáis los sepulcros de los profetas que vuestros padres mataron!

[[luke-11-48]]
^48^ Por tanto, sois testigos y estáis de acuerdo con las obras de vuestros padres; porque ellos los mataron y vosotros edificáis.

[[luke-11-49]]
^49^ «Por eso dijo la Sabiduría de Dios: Les enviaré profetas y apóstoles, y a algunos los matarán y perseguirán,

[[luke-11-50]]
^50^ para que se pidan cuentas a esta generación de la sangre de todos los profetas derramada desde la creación del mundo,

[[luke-11-51]]
^51^ desde la sangre de Abel hasta la sangre de Zacarías, el que pereció entre el altar y el Santuario. Sí, os aseguro que se pedirán cuentas a esta generación.

[[luke-11-52]]
^52^ «¡Ay de vosotros, los legistas, que os habéis llevado la llave de la ciencia! No entrasteis vosotros, y a los que están entrando se lo habéis impedido».

[[luke-11-53]]
^53^ Y cuando salió de allí, comenzaron los escribas y fariseos a acosarle implacablemente y hacerle hablar de muchas cosas,

[[luke-11-54]]
^54^ buscando, con insidias, cazar alguna palabra de su boca.
[[luke-12]]
== Capítulo 12

[[luke-12-1]]
^1^ En esto, habiéndose reunido miles y miles de personas, hasta pisarse unos a otros, se puso a decir primeramente a sus discípulos: «Guardaos de la levadura de los fariseos, que es la hipocresía.

[[luke-12-2]]
^2^ Nada hay encubierto que no haya de ser descubierto ni oculto que no haya de saberse.

[[luke-12-3]]
^3^ Porque cuanto dijisteis en la oscuridad, será oído a la luz, y lo que hablasteis al oído en las habitaciones privadas, será proclamado desde los terrados.

[[luke-12-4]]
^4^ «Os digo a vosotros, amigos míos: No temáis a los que matan el cuerpo, y después de esto no pueden hacer más.

[[luke-12-5]]
^5^ Os mostraré a quién debéis temer: temed a Aquel que, después de matar, tiene poder para arrojar a la gehenna; sí, os repito: temed a ése.

[[luke-12-6]]
^6^ «¿No se venden cinco pajarillos por dos ases? Pues bien, ni uno de ellos está olvidado ante Dios.

[[luke-12-7]]
^7^ Hasta los cabellos de vuestra cabeza están todos contados. No temáis; valéis más que muchos pajarillos.

[[luke-12-8]]
^8^ «Yo os digo: Por todo el que se declare por mí ante los hombres, también el Hijo del hombre se declarará por él ante los ángeles de Dios.

[[luke-12-9]]
^9^ Pero el que me niegue delante de los hombres, será negado delante de los ángeles de Dios.

[[luke-12-10]]
^10^ «A todo el que diga una palabra contra el Hijo del hombre, se le perdonará; pero al que blasfeme contra el Espíritu Santo, no se le perdonará.

[[luke-12-11]]
^11^ Cuando os lleven a las sinagogas, ante los magistrados y las autoridades, no os preocupéis de cómo o con qué os defenderéis, o qué diréis,

[[luke-12-12]]
^12^ porque el Espíritu Santo os enseñará en aquel mismo momento lo que conviene decir».

[[luke-12-13]]
^13^ Uno de la gente le dijo: «Maestro, di a mi hermano que reparta la herencia conmigo».

[[luke-12-14]]
^14^ El le respondió: «¡Hombre! ¿quién me ha constituido juez o repartidor entre vosotros?»

[[luke-12-15]]
^15^ Y les dijo: «Mirad y guardaos de toda codicia, porque, aun en la abundancia, la vida de uno no está asegurada por sus bienes».

[[luke-12-16]]
^16^ Les dijo una parábola: «Los campos de cierto hombre rico dieron mucho fruto;

[[luke-12-17]]
^17^ y pensaba entre sí, diciendo: “¿Qué haré, pues no tengo donde reunir mi cosecha?”

[[luke-12-18]]
^18^ Y dijo: “Voy a hacer esto: Voy a demoler mis graneros, y edificaré otros más grandes y reuniré allí todo mi trigo y mis bienes,

[[luke-12-19]]
^19^ y diré a mi alma: Alma, tienes muchos bienes en reserva para muchos años. Descansa, come, bebe, banquetea.”

[[luke-12-20]]
^20^ Pero Dios le dijo: “¡Necio! Esta misma noche te reclamarán el alma; las cosas que preparaste, ¿para quién serán?”

[[luke-12-21]]
^21^ Así es el que atesora riquezas para sí, y no se enriquece en orden a Dios».

[[luke-12-22]]
^22^ Dijo a sus discípulos: «Por eso os digo: No andéis preocupados por vuestra vida, qué comeréis, ni por vuestro cuerpo, con qué os vestiréis:

[[luke-12-23]]
^23^ porque la vida vale más que el alimento, y el cuerpo más que el vestido;

[[luke-12-24]]
^24^ fijaos en los cuervos: ni siembran, ni cosechan; no tienen bodega ni granero, y Dios los alimenta. ¡Cuánto más valéis vosotros que las aves!

[[luke-12-25]]
^25^ Por lo demás, ¿quién de vosotros puede, por más que se preocupe, añadir un codo a la medida de su vida?

[[luke-12-26]]
^26^ Si, pues, no sois capaces ni de lo más pequeño, ¿por qué preocuparos de lo demás?

[[luke-12-27]]
^27^ Fijaos en los lirios, cómo ni hilan ni tejen. Pero yo os digo que ni Salomón en toda su gloria se vistió como uno de ellos.

[[luke-12-28]]
^28^ Pues si a la hierba que hoy está en el campo y mañana se echa al horno, Dios así la viste ¡cuánto más a vosotros, hombres de poca fe!

[[luke-12-29]]
^29^ Así pues, vosotros no andéis buscando qué comer ni qué beber, y no estéis inquietos.

[[luke-12-30]]
^30^ Que por todas esas cosas se afanan los gentiles del mundo; y ya sabe vuestro Padre que tenéis la necesidad de eso.

[[luke-12-31]]
^31^ Buscad más bien su Reino, y esas cosas se os darán por añadidura.

[[luke-12-32]]
^32^ «No temas, pequeño rebaño, porque a vuestro Padre le ha parecido bien daros a vosotros el Reino.

[[luke-12-33]]
^33^ «Vended vuestros bienes y dad limosna. Haceos bolsas que no se deterioran, un tesoro inagotable en los cielos, donde no llega el ladrón, ni la polilla;

[[luke-12-34]]
^34^ porque donde esté vuestro tesoro, allí estará también vuestro corazón.

[[luke-12-35]]
^35^ «Estén ceñidos vuestros lomos y las lámparas encendidas,

[[luke-12-36]]
^36^ y sed como hombres que esperan a que su señor vuelva de la boda, para que, en cuanto llegue y llame, al instante le abran.

[[luke-12-37]]
^37^ Dichosos los siervos, que el señor al venir encuentre despiertos: yo os aseguro que se ceñirá, los hará ponerse a la mesa y, yendo de uno a otro, les servirá.

[[luke-12-38]]
^38^ Que venga en la segunda vigilia o en la tercera, si los encuentra así, ¡dichosos de ellos!

[[luke-12-39]]
^39^ Entendedlo bien: si el dueño de casa supiese a qué hora iba a venir el ladrón, no dejaría que le horadasen su casa.

[[luke-12-40]]
^40^ También vosotros estad preparados, porque en el momento que no penséis, vendrá el Hijo del hombre».

[[luke-12-41]]
^41^ Dijo Pedro: «Señor, ¿dices esta parábola para nosotros o para todos?»

[[luke-12-42]]
^42^ Respondió el Señor: «¿Quién es, pues, el administrador fiel y prudente a quien el señor pondrá al frente de su servidumbre para darles a su tiempo su ración conveniente?

[[luke-12-43]]
^43^ Dichoso aquel siervo a quien su señor, al llegar, encuentre haciéndolo así.

[[luke-12-44]]
^44^ De verdad os digo que le pondrá al frente de toda su hacienda.

[[luke-12-45]]
^45^ Pero si aquel siervo se dice en su corazón: “Mi señor tarda en venir”, y se pone a golpear a los criados y a las criadas, a comer y a beber y a emborracharse,

[[luke-12-46]]
^46^ vendrá el señor de aquel siervo el día que no espera y en el momento que no sabe, le separará y le señalará su suerte entre los infieles.

[[luke-12-47]]
^47^ «Aquel siervo que, conociendo la voluntad de su señor, no ha preparado nada ni ha obrado conforme a su voluntad, recibirá muchos azotes;

[[luke-12-48]]
^48^ el que no la conoce y hace cosas dignas de azotes, recibirá pocos; a quien se le dio mucho, se le reclamará mucho; y a quien se confió mucho, se le pedirá más.

[[luke-12-49]]
^49^ «He venido a arrojar un fuego sobre la tierra y ¡cuánto desearía que ya estuviera encendido!

[[luke-12-50]]
^50^ Con un bautismo tengo que ser bautizado y ¡qué angustiado estoy hasta que se cumpla!

[[luke-12-51]]
^51^ «¿Creéis que estoy aquí para dar paz a la tierra? No, os lo aseguro, sino división.

[[luke-12-52]]
^52^ Porque desde ahora habrá cinco en una casa y estarán divididos; tres contra dos, y dos contra tres;

[[luke-12-53]]
^53^ estarán divididos el padre contra el hijo y el hijo contra el padre; la madre contra la hija y la hija contra la madre; la suegra contra la nuera y la nuera contra la suegra».

[[luke-12-54]]
^54^ Decía también a la gente: «Cuando veis una nube que se levanta en el occidente, al momento decís: “Va a llover”, y así sucede.

[[luke-12-55]]
^55^ Y cuando sopla el sur, decís: “Viene bochorno”, y así sucede.

[[luke-12-56]]
^56^ ¡Hipócritas! Sabéis explorar el aspecto de la tierra y del cielo, ¿cómo no exploráis, pues, este tiempo?

[[luke-12-57]]
^57^ «¿Por qué no juzgáis por vosotros mismos lo que es justo?

[[luke-12-58]]
^58^ Cuando vayas con tu adversario al magistrado, procura en el camino arreglarte con él, no sea que te arrastre ante el juez, y el juez te entregue al alguacil y el alguacil te meta en la cárcel.

[[luke-12-59]]
^59^ Te digo que no saldrás de allí hasta que no hayas pagado el último céntimo.
[[luke-13]]
== Capítulo 13

[[luke-13-1]]
^1^ En aquel mismo momento llegaron algunos que le contaron lo de los galileos, cuya sangre había mezclado Pilato con la de sus sacrificios.

[[luke-13-2]]
^2^ Les respondió Jesús: «¿Pensáis que esos galileos eran más pecadores que todos los demás galileos, porque han padecido estas cosas?

[[luke-13-3]]
^3^ No, os lo aseguro; y si no os convertís, todos pereceréis del mismo modo.

[[luke-13-4]]
^4^ O aquellos dieciocho sobre los que se desplomó la torre de Siloé matándolos, ¿pensáis que eran más culpables que los demás hombres que habitaban en Jerusalén?

[[luke-13-5]]
^5^ No, os lo aseguro; y si no os convertís, todos pereceréis del mismo modo».

[[luke-13-6]]
^6^ Les dijo esta parábola: «Un hombre tenía plantada una higuera en su viña, y fue a buscar fruto en ella y no lo encontró.

[[luke-13-7]]
^7^ Dijo entonces al viñador: “Ya hace tres años que vengo a buscar fruto en esta higuera, y no lo encuentro; córtala; ¿para qué va a cansar la tierra?”

[[luke-13-8]]
^8^ Pero él le respondió: “Señor, déjala por este año todavía y mientras tanto cavaré a su alrededor y echaré abono,

[[luke-13-9]]
^9^ por si da fruto en adelante; y si no da, la cortas.”»

[[luke-13-10]]
^10^ Estaba un sábado enseñando en una sinagoga,

[[luke-13-11]]
^11^ y había una mujer a la que un espíritu tenía enferma hacía dieciocho años; estaba encorvada, y no podía en modo alguno enderezarse.

[[luke-13-12]]
^12^ Al verla Jesús, la llamó y le dijo: «Mujer, quedas libre de tu enfermedad».

[[luke-13-13]]
^13^ Y le impuso las manos. Y al instante se enderezó, y glorificaba a Dios.

[[luke-13-14]]
^14^ Pero el jefe de la sinagoga, indignado de que Jesús hubiese hecho una curación en sábado, decía a la gente: «Hay seis días en que se puede trabajar; venid, pues, esos días a curaros, y no en día de sábado».

[[luke-13-15]]
^15^ Replicóle el Señor: «¡Hipócritas! ¿No desatáis del pesebre todos vosotros en sábado a vuestro buey o vuestro asno para llevarlos a abrevar?

[[luke-13-16]]
^16^ Y a ésta, que es hija de Abraham, a la que ató Satanás hace ya dieciocho años, ¿no estaba bien desatarla de esta ligadura en día de sábado?»

[[luke-13-17]]
^17^ Y cuando decía estas cosas, sus adversarios quedaban confundidos, mientras que toda la gente se alegraba con las maravillas que hacía.

[[luke-13-18]]
^18^ Decía, pues: «¿A qué es semejante el Reino de Dios? ¿A qué lo compararé?

[[luke-13-19]]
^19^ Es semejante a un grano de mostaza, que tomó un hombre y lo puso en su jardín, y creció hasta hacerse árbol, y las aves del cielo anidaron en sus ramas».

[[luke-13-20]]
^20^ Dijo también: «¿A qué compararé el Reino de Dios?

[[luke-13-21]]
^21^ Es semejante a la levadura que tomó una mujer y la metió en tres medidas de harina, hasta que fermentó todo».

[[luke-13-22]]
^22^ Atravesaba ciudades y pueblos enseñando, mientras caminaba hacia Jerusalén.

[[luke-13-23]]
^23^ Uno le dijo: «Señor, ¿son pocos los que se salvan?» El les dijo:

[[luke-13-24]]
^24^ «Luchad por entrar por la puerta estrecha, porque, os digo, muchos pretenderán entrar y no podrán.

[[luke-13-25]]
^25^ «Cuando el dueño de la casa se levante y cierre la puerta, os pondréis los que estéis fuera a llamar a la puerta, diciendo: “¡Señor, ábrenos!” Y os responderá: “No sé de dónde sois.”

[[luke-13-26]]
^26^ Entonces empezaréis a decir: “Hemos comido y bebido contigo, y has enseñado en nuestras plazas”;

[[luke-13-27]]
^27^ y os volverá a decir: “No sé de dónde sois. ¡Retiraos de mí, todos los agentes de injusticia!”

[[luke-13-28]]
^28^ «Allí será el llanto y el rechinar de dientes, cuando veáis a Abraham, Isaac y Jacob y a todos los profetas en el Reino de Dios, mientras a vosotros os echan fuera.

[[luke-13-29]]
^29^ Y vendrán de oriente y occidente, del norte y del sur, y se pondrán a la mesa en el Reino de Dios.

[[luke-13-30]]
^30^ «Y hay últimos que serán primeros, y hay primeros que serán últimos».

[[luke-13-31]]
^31^ En aquel mismo momento se acercaron algunos fariseos, y le dijeron: «Sal y vete de aquí, porque Herodes quiere matarte».

[[luke-13-32]]
^32^ Y él les dijo: «Id a decir a ese zorro: Yo expulso demonios y llevo a cabo curaciones hoy y mañana, y al tercer día soy consumado.

[[luke-13-33]]
^33^ Pero conviene que hoy y mañana y pasado siga adelante, porque no cabe que un profeta perezca fuera de Jerusalén.

[[luke-13-34]]
^34^ «¡Jerusalén, Jerusalén!, la que mata a los profetas y apedrea a los que le son enviados. ¡Cuántas veces he querido reunir a tus hijos, como una gallina su nidada bajo las alas, y no habéis querido!

[[luke-13-35]]
^35^ Pues bien, se os va a dejar vuestra casa. Os digo que no me volveréis a ver hasta que llegue el día en que digáis: ¡Bendito el que viene en nombre del Señor!»
[[luke-14]]
== Capítulo 14

[[luke-14-1]]
^1^ Y sucedió que, habiendo ido en sábado a casa de uno de los jefes de los fariseos para comer, ellos le estaban observando.

[[luke-14-2]]
^2^ Había allí, delante de él, un hombre hidrópico.

[[luke-14-3]]
^3^ Entonces preguntó Jesús a los legistas y a los fariseos: «¿Es lícito curar en sábado, o no?»

[[luke-14-4]]
^4^ Pero ellos se callaron. Entonces le tomó, le curó, y le despidió.

[[luke-14-5]]
^5^ Y a ellos les dijo: «¿A quién de vosotros se le cae un hijo o un buey a un pozo en día de sábado y no lo saca al momento?»

[[luke-14-6]]
^6^ Y no pudieron replicar a esto.

[[luke-14-7]]
^7^ Notando cómo los invitados elegían los primeros puestos, les dijo una parábola:

[[luke-14-8]]
^8^ «Cuando seas convidado por alguien a una boda, no te pongas en el primer puesto, no sea que haya sido convidado por él otro más distinguido que tú,

[[luke-14-9]]
^9^ y viniendo el que os convidó a ti y a él, te diga: “Deja el sitio a éste”, y entonces vayas a ocupar avergonzado el último puesto.

[[luke-14-10]]
^10^ Al contrario, cuando seas convidado, vete a sentarte en el último puesto, de manera que, cuando venga el que te convidó, te diga: “Amigo, sube más arriba.” Y esto será un honor para ti delante de todos los que estén contigo a la mesa.

[[luke-14-11]]
^11^ Porque todo el que se ensalce, será humillado; y el que se humille, será ensalzado».

[[luke-14-12]]
^12^ Dijo también al que le había invitado: «Cuando des una comida o una cena, no llames a tus amigos, ni a tus hermanos, ni a tus parientes, ni a tus vecinos ricos; no sea que ellos te inviten a su vez, y tengas ya tu recompensa.

[[luke-14-13]]
^13^ Cuando des un banquete, llama a los pobres, a los lisiados, a los cojos, a los ciegos;

[[luke-14-14]]
^14^ y serás dichoso, porque no te pueden corresponder, pues se te recompensará en la resurrección de los justos».

[[luke-14-15]]
^15^ Habiendo oído esto, uno de los comensales le dijo: «¡Dichoso el que pueda comer en el Reino de Dios!»

[[luke-14-16]]
^16^ El le respondió: «Un hombre dio una gran cena y convidó a muchos;

[[luke-14-17]]
^17^ a la hora de la cena envió a su siervo a decir a los invitados: “Venid, que ya está todo preparado.”

[[luke-14-18]]
^18^ Pero todos a una empezaron a excusarse. El primero le dijo: “He comprado un campo y tengo que ir a verlo; te ruego me dispenses.”

[[luke-14-19]]
^19^ Y otro dijo: “He comprado cinco yuntas de bueyes y voy a probarlas; te ruego me dispenses.”

[[luke-14-20]]
^20^ Otro dijo: “Me he casado, y por eso no puedo ir.”

[[luke-14-21]]
^21^ «Regresó el siervo y se lo contó a su señor. Entonces, airado el dueño de la casa, dijo a su siervo: “Sal en seguida a las plazas y calles de la ciudad, y haz entrar aquí a los pobres y lisiados, y ciegos y cojos.”

[[luke-14-22]]
^22^ Dijo el siervo: “Señor, se ha hecho lo que mandaste, y todavía hay sitio.”

[[luke-14-23]]
^23^ Dijo el señor al siervo: “Sal a los caminos y cercas, y obliga a entrar hasta que se llene mi casa.”

[[luke-14-24]]
^24^ Porque os digo que ninguno de aquellos invitados probará mi cena».

[[luke-14-25]]
^25^ Caminaba con él mucha gente, y volviéndose les dijo:

[[luke-14-26]]
^26^ «Si alguno viene donde mí y no odia a su padre, a su madre, a su mujer, a sus hijos, a sus hermanos, a sus hermanas y hasta su propia vida, no puede ser discípulo mío.

[[luke-14-27]]
^27^ El que no lleve su cruz y venga en pos de mí, no puede ser discípulo mío.

[[luke-14-28]]
^28^ «Porque ¿quién de vosotros, que quiere edificar una torre, no se sienta primero a calcular los gastos, y ver si tiene para acabarla?

[[luke-14-29]]
^29^ No sea que, habiendo puesto los cimientos y no pudiendo terminar, todos los que lo vean se pongan a burlarse de él, diciendo:

[[luke-14-30]]
^30^ “Este comenzó a edificar y no pudo terminar.”

[[luke-14-31]]
^31^ O ¿qué rey, que sale a enfrentarse contra otro rey, no se sienta antes y delibera si con 10.000 puede salir al paso del que viene contra él con 20.000?

[[luke-14-32]]
^32^ Y si no, cuando está todavía lejos, envía una embajada para pedir condiciones de paz.

[[luke-14-33]]
^33^ Pues, de igual manera, cualquiera de vosotros que no renuncie a todos sus bienes, no puede ser discípulo mío.

[[luke-14-34]]
^34^ «Buena es la sal; mas si también la sal se desvirtúa, ¿con qué se la sazonará?

[[luke-14-35]]
^35^ No es útil ni para la tierra ni para el estercolero; la tiran afuera. El que tenga oídos para oír, que oiga».
[[luke-15]]
== Capítulo 15

[[luke-15-1]]
^1^ Todos los publicanos y los pecadores se acercaban a él para oírle,

[[luke-15-2]]
^2^ y los fariseos y los escribas murmuraban, diciendo: «Este acoge a los pecadores y come con ellos».

[[luke-15-3]]
^3^ Entonces les dijo esta parábola.

[[luke-15-4]]
^4^ «¿Quién de vosotros que tiene cien ovejas, si pierde una de ellas, no deja las 99 en el desierto, y va a buscar la que se perdió hasta que la encuentra?

[[luke-15-5]]
^5^ Y cuando la encuentra, la pone contento sobre sus hombros;

[[luke-15-6]]
^6^ y llegando a casa, convoca a los amigos y vecinos, y les dice: “Alegraos conmigo, porque he hallado la oveja que se me había perdido.”

[[luke-15-7]]
^7^ Os digo que, de igual modo, habrá más alegría en el cielo por un solo pecador que se convierta que por 99 justos que no tengan necesidad de conversión.

[[luke-15-8]]
^8^ «O, ¿qué mujer que tiene diez dracmas, si pierde una, no enciende una lámpara y barre la casa y busca cuidadosamente hasta que la encuentra?

[[luke-15-9]]
^9^ Y cuando la encuentra, convoca a las amigas y vecinas, y dice: “Alegraos conmigo, porque he hallado la dracma que había perdido.”

[[luke-15-10]]
^10^ Del mismo modo, os digo, se produce alegría ante los ángeles de Dios por un solo pecador que se convierta».

[[luke-15-11]]
^11^ Dijo: «Un hombre tenía dos hijos;

[[luke-15-12]]
^12^ y el menor de ellos dijo al padre: “Padre, dame la parte de la hacienda que me corresponde.” Y él les repartió la hacienda.

[[luke-15-13]]
^13^ Pocos días después el hijo menor lo reunió todo y se marchó a un país lejano donde malgastó su hacienda viviendo como un libertino.

[[luke-15-14]]
^14^ «Cuando hubo gastado todo, sobrevino un hambre extrema en aquel país, y comenzó a pasar necesidad.

[[luke-15-15]]
^15^ Entonces, fue y se ajustó con uno de los ciudadanos de aquel país, que le envió a sus fincas a apacentar puercos.

[[luke-15-16]]
^16^ Y deseaba llenar su vientre con las algarrobas que comían los puercos, pero nadie se las daba.

[[luke-15-17]]
^17^ Y entrando en sí mismo, dijo: “¡Cuántos jornaleros de mi padre tienen pan en abundancia, mientras que yo aquí me muero de hambre!

[[luke-15-18]]
^18^ Me levantaré, iré a mi padre y le diré: Padre, pequé contra el cielo y ante ti.

[[luke-15-19]]
^19^ Ya no merezco ser llamado hijo tuyo, trátame como a uno de tus jornaleros.”

[[luke-15-20]]
^20^ Y, levantándose, partió hacia su padre. «Estando él todavía lejos, le vió su padre y, conmovido, corrió, se echó a su cuello y le besó efusivamente.

[[luke-15-21]]
^21^ El hijo le dijo: “Padre, pequé contra el cielo y ante ti; ya no merezco ser llamado hijo tuyo.”

[[luke-15-22]]
^22^ Pero el padre dijo a sus siervos: “Traed aprisa el mejor vestido y vestidle, ponedle un anillo en su mano y unas sandalias en los pies.

[[luke-15-23]]
^23^ Traed el novillo cebado, matadlo, y comamos y celebremos una fiesta,

[[luke-15-24]]
^24^ porque este hijo mío estaba muerto y ha vuelto a la vida; estaba perdido y ha sido hallado.” Y comenzaron la fiesta.

[[luke-15-25]]
^25^ «Su hijo mayor estaba en el campo y, al volver, cuando se acercó a la casa, oyó la música y las danzas;

[[luke-15-26]]
^26^ y llamando a uno de los criados, le preguntó qué era aquello.

[[luke-15-27]]
^27^ El le dijo: “Ha vuelto tu hermano y tu padre ha matado el novillo cebado, porque le ha recobrado sano.”

[[luke-15-28]]
^28^ El se irritó y no quería entrar. Salió su padre, y le suplicaba.

[[luke-15-29]]
^29^ Pero él replicó a su padre: “Hace tantos años que te sirvo, y jamás dejé de cumplir una orden tuya, pero nunca me has dado un cabrito para tener una fiesta con mis amigos;

[[luke-15-30]]
^30^ y ¡ahora que ha venido ese hijo tuyo, que ha devorado tu hacienda con prostitutas, has matado para él el novillo cebado!”

[[luke-15-31]]
^31^ «Pero él le dijo: “Hijo, tú siempre estás conmigo, y todo lo mío es tuyo;

[[luke-15-32]]
^32^ pero convenía celebrar una fiesta y alegrarse, porque este hermano tuyo estaba muerto, y ha vuelto a la vida; estaba perdido, y ha sido hallado.”»
[[luke-16]]
== Capítulo 16

[[luke-16-1]]
^1^ Decía también a sus discípulos: «Era un hombre rico que tenía un administrador a quien acusaron ante él de malbaratar su hacienda;

[[luke-16-2]]
^2^ le llamó y le dijo: “¿Qué oigo decir de ti? Dame cuenta de tu administración, porque ya no podrás seguir administrando.”

[[luke-16-3]]
^3^ Se dijo a sí mismo el administrador: “¿Qué haré, pues mi señor me quita la administración? Cavar, no puedo; mendigar, me da vergüenza.

[[luke-16-4]]
^4^ Ya sé lo que voy a hacer, para que cuando sea removido de la administración me reciban en sus casas.”

[[luke-16-5]]
^5^ «Y convocando uno por uno a los deudores de su señor, dijo al primero: “¿Cuánto debes a mi señor?”

[[luke-16-6]]
^6^ Respondió: “Cien medidas de aceite.” El le dijo: “Toma tu recibo, siéntate en seguida y escribe cincuenta.”

[[luke-16-7]]
^7^ Después dijo a otro: “Tú, ¿cuánto debes?” Contestó: “Cien cargas de trigo.” Dícele: “Toma tu recibo y escribe ochenta.”

[[luke-16-8]]
^8^ «El señor alabó al administrador injusto porque había obrado astutamente, pues los hijos de este mundo son más astutos con los de su generación que los hijos de la luz.

[[luke-16-9]]
^9^ «Yo os digo: Haceos amigos con el Dinero injusto, para que, cuando llegue a faltar, os reciban en las eternas moradas.

[[luke-16-10]]
^10^ El que es fiel en lo mínimo, lo es también en lo mucho; y el que es injusto en lo mínimo, también lo es en lo mucho.

[[luke-16-11]]
^11^ Si, pues, no fuisteis fieles en el Dinero injusto, ¿quién os confiará lo verdadero?

[[luke-16-12]]
^12^ Y si no fuisteis fieles con lo ajeno, ¿quién os dará lo vuestro?

[[luke-16-13]]
^13^ «Ningún criado puede servir a dos señores, porque aborrecerá a uno y amará al otro; o bien se entregará a uno y despreciará al otro. No podéis servir a Dios y al Dinero».

[[luke-16-14]]
^14^ Estaban oyendo todas estas cosas los fariseos, que eran amigos del dinero, y se burlaban de él.

[[luke-16-15]]
^15^ Y les dijo: «Vosotros sois los que os la dais de justos delante de los hombres, pero Dios conoce vuestros corazones; porque lo que es estimable para los hombres, es abominable ante Dios.

[[luke-16-16]]
^16^ «La Ley y los profetas llegan hasta Juan; desde ahí comienza a anunciarse la Buena Nueva del Reino de Dios, y todos se esfuerzan con violencia por entrar en él.

[[luke-16-17]]
^17^ «Más fácil es que el cielo y la tierra pasen, que no que caiga un ápice de la Ley.

[[luke-16-18]]
^18^ «Todo el que repudia a su mujer y se casa con otra, comete adulterio; y el que se casa con una repudiada por su marido, comete adulterio.

[[luke-16-19]]
^19^ «Era un hombre rico que vestía de púrpura y lino, y celebraba todos los días espléndidas fiestas.

[[luke-16-20]]
^20^ Y uno pobre, llamado Lázaro, que, echado junto a su portal, cubierto de llagas,

[[luke-16-21]]
^21^ deseaba hartarse de lo que caía de la mesa del rico... pero hasta los perros venían y le lamían las llagas.

[[luke-16-22]]
^22^ Sucedió, pues, que murió el pobre y fue llevado por los ángeles al seno de Abraham. Murió también el rico y fue sepultado.

[[luke-16-23]]
^23^ «Estando en el Hades entre tormentos, levantó los ojos y vio a lo lejos a Abraham, y a Lázaro en su seno.

[[luke-16-24]]
^24^ Y, gritando, dijo: “Padre Abraham, ten compasión de mí y envía a Lázaro a que moje en agua la punta de su dedo y refresque mi lengua, porque estoy atormentado en esta llama.”

[[luke-16-25]]
^25^ Pero Abraham le dijo: “Hijo, recuerda que recibiste tus bienes durante tu vida y Lázaro, al contrario, sus males; ahora, pues, él es aquí consolado y tú atormentado.

[[luke-16-26]]
^26^ Y además, entre nosotros y vosotros se interpone un gran abismo, de modo que los que quieran pasar de aquí a vosotros, no puedan; ni de ahí puedan pasar donde nosotros.”

[[luke-16-27]]
^27^ «Replicó: “Con todo, te ruego, padre, que le envíes a la casa de mi padre,

[[luke-16-28]]
^28^ porque tengo cinco hermanos, para que les dé testimonio, y no vengan también ellos a este lugar de tormento.”

[[luke-16-29]]
^29^ Díjole Abraham: “Tienen a Moisés y a los profetas; que les oigan.”

[[luke-16-30]]
^30^ El dijo: “No, padre Abraham; sino que si alguno de entre los muertos va donde ellos, se convertirán.”

[[luke-16-31]]
^31^ Le contestó: “Si no oyen a Moisés y a los profetas, tampoco se convencerán, aunque un muerto resucite.”»
[[luke-17]]
== Capítulo 17

[[luke-17-1]]
^1^ Dijo a sus discípulos: «Es imposible que no vengan escándalos; pero, ¡ay de aquel por quien vienen!

[[luke-17-2]]
^2^ Más le vale que le pongan al cuello una piedra de molino y sea arrojado al mar, que escandalizar a uno de estos pequeños.

[[luke-17-3]]
^3^ Cuidaos de vosotros mismos. «Si tu hermano peca, repréndele; y si se arrepiente, perdónale.

[[luke-17-4]]
^4^ Y si peca contra ti siete veces al día, y siete veces se vuelve a ti, diciendo: “Me arrepiento”, le perdonarás».

[[luke-17-5]]
^5^ Dijeron los apóstoles al Señor; «Auméntanos la fe».

[[luke-17-6]]
^6^ El Señor dijo: «Si tuvierais fe como un grano de mostaza, habríais dicho a este sicómoro: “Arráncate y plántate en el mar”, y os habría obedecido».

[[luke-17-7]]
^7^ «¿Quién de vosotros tiene un siervo arando o pastoreando y, cuando regresa del campo, le dice: “Pasa al momento y ponte a la mesa?”

[[luke-17-8]]
^8^ ¿No le dirá más bien: “Prepárame algo para cenar, y cíñete para servirme hasta que haya comido y bebido, y después comerás y beberás tú?”

[[luke-17-9]]
^9^ ¿Acaso tiene que agradecer al siervo porque hizo lo que le fue mandado?

[[luke-17-10]]
^10^ De igual modo vosotros, cuando hayáis hecho todo lo que os fue mandado, decid: Somos siervos inútiles; hemos hecho lo que debíamos hacer».

[[luke-17-11]]
^11^ Y sucedió que, de camino a Jerusalén, pasaba por los confines entre Samaría y Galilea,

[[luke-17-12]]
^12^ y, al entrar en un pueblo, salieron a su encuentro diez hombres leprosos, que se pararon a distancia

[[luke-17-13]]
^13^ y, levantando la voz, dijeron: «¡Jesús, Maestro, ten compasión de nosotros!»

[[luke-17-14]]
^14^ Al verlos, les dijo: «Id y presentaos a los sacerdotes». Y sucedió que, mientras iban, quedaron limpios.

[[luke-17-15]]
^15^ Uno de ellos, viéndose curado, se volvió glorificando a Dios en alta voz;

[[luke-17-16]]
^16^ y postrándose rostro en tierra a los pies de Jesús, le daba gracias; y éste era un samaritano.

[[luke-17-17]]
^17^ Tomó la palabra Jesús y dijo: «¿No quedaron limpios los diez? Los otros nueve, ¿dónde están?

[[luke-17-18]]
^18^ ¿No ha habido quien volviera a dar gloria a Dios sino este extranjero?»

[[luke-17-19]]
^19^ Y le dijo: «Levántate y vete; tu fe te ha salvado».

[[luke-17-20]]
^20^ Habiéndole preguntado los fariseos cuándo llegaría el Reino de Dios, les respondió: «El Reino de Dios viene sin dejarse sentir.

[[luke-17-21]]
^21^ Y no dirán: “Vedlo aquí o allá”, porque el Reino de Dios ya está entre vosotros».

[[luke-17-22]]
^22^ Dijo a sus discípulos: «Días vendrán en que desearéis ver uno solo de los días del Hijo del hombre, y no lo veréis.

[[luke-17-23]]
^23^ Y os dirán: “Vedlo aquí, vedlo allá.” No vayáis, ni corráis detrás.

[[luke-17-24]]
^24^ Porque, como relámpago fulgurante que brilla de un extremo a otro del cielo, así será el Hijo del hombre en su Día.

[[luke-17-25]]
^25^ Pero, antes, le es preciso padecer mucho y ser reprobado por esta generación.

[[luke-17-26]]
^26^ «Como sucedió en los días de Noé, así será también en los días del Hijo del hombre.

[[luke-17-27]]
^27^ Comían, bebían, tomaban mujer o marido, hasta el día en que entró Noé en el arca; vino el diluvio y los hizo perecer a todos.

[[luke-17-28]]
^28^ Lo mismo, como sucedió en los días de Lot: comían, bebían, compraban, vendían, plantaban, construían;

[[luke-17-29]]
^29^ pero el día que salió Lot de Sodoma, Dios hizo llover fuego y azufre del cielo y los hizo perecer a todos.

[[luke-17-30]]
^30^ Lo mismo sucederá el Día en que el Hijo del hombre se manifieste.

[[luke-17-31]]
^31^ «Aquel Día, el que esté en el terrado y tenga sus enseres en casa, no baje a recogerlos; y de igual modo, el que esté en el campo, no se vuelva atrás.

[[luke-17-32]]
^32^ Acordaos de la mujer de Lot.

[[luke-17-33]]
^33^ Quien intente guardar su vida, la perderá; y quien la pierda, la conservará.

[[luke-17-34]]
^34^ Yo os lo digo: aquella noche estarán dos en un mismo lecho: uno será tomado y el otro dejado;

[[luke-17-35]]
^35^ habrá dos mujeres moliendo juntas: una será tomada y la otra dejada».

[[luke-17-36]]
^36^ Y le dijeron: «¿Dónde, Señor?» El les respondió: «Donde esté el cuerpo, allí también se reunirán los buitres».
[[luke-18]]
== Capítulo 18

[[luke-18-1]]
^1^ Les decía una parábola para inculcarles que era preciso orar siempre sin desfallecer.

[[luke-18-2]]
^2^ «Había un juez en una ciudad, que ni temía a Dios ni respetaba a los hombres.

[[luke-18-3]]
^3^ Había en aquella ciudad una viuda que, acudiendo a él, le dijo: “¡Hazme justicia contra mi adversario!”

[[luke-18-4]]
^4^ Durante mucho tiempo no quiso, pero después se dijo a sí mismo: “Aunque no temo a Dios ni respeto a los hombres,

[[luke-18-5]]
^5^ como esta viuda me causa molestias, le voy a hacer justicia para que no venga continuamente a importunarme.”»

[[luke-18-6]]
^6^ Dijo, pues, el Señor: «Oíd lo que dice el juez injusto;

[[luke-18-7]]
^7^ y Dios, ¿no hará justicia a sus elegidos, que están clamando a él día y noche, y les hace esperar?

[[luke-18-8]]
^8^ Os digo que les hará justicia pronto. Pero, cuando el Hijo del hombre venga, ¿encontrará la fe sobre la tierra?»

[[luke-18-9]]
^9^ Dijo también a algunos que se tenían por justos y despreciaban a los demás, esta parábola:

[[luke-18-10]]
^10^ «Dos hombres subieron al templo a orar; uno fariseo, otro publicano.

[[luke-18-11]]
^11^ El fariseo, de pie, oraba en su interior de esta manera: “¡Oh Dios! Te doy gracias porque no soy como los demás hombres, rapaces, injustos, adúlteros, ni tampoco como este publicano.

[[luke-18-12]]
^12^ Ayuno dos veces por semana, doy el diezmo de todas mis ganancias.”

[[luke-18-13]]
^13^ En cambio el publicano, manteniéndose a distancia, no se atrevía ni a alzar los ojos al cielo, sino que se golpeaba el pecho, diciendo: “¡Oh Dios! ¡Ten compasión de mí, que soy pecador!”

[[luke-18-14]]
^14^ Os digo que éste bajó a su casa justificado y aquél no. Porque todo el que se ensalce, será humillado; y el que se humille, será ensalzado».

[[luke-18-15]]
^15^ Le presentaban también los niños pequeños para que los tocara, y al verlo los discípulos, les reñían.

[[luke-18-16]]
^16^ Mas Jesús llamó a los niños, diciendo: «Dejad que los niños vengan a mí y no se lo impidáis; porque de los que son como éstos es el Reino de Dios.

[[luke-18-17]]
^17^ Yo os aseguro: el que no reciba el Reino de Dios como niño, no entrará en él».

[[luke-18-18]]
^18^ Uno de los principales le preguntó: «Maestro bueno, ¿qué he de hacer para tener en herencia vida eterna?»

[[luke-18-19]]
^19^ Le dijo Jesús: «¿Por qué me llamas bueno? Nadie es bueno sino sólo Dios.

[[luke-18-20]]
^20^ Ya sabes los mandamientos: No cometas adulterio, no mates, no robes, no levantes falso testimonio, honra a tu padre y a tu madre».

[[luke-18-21]]
^21^ El dijo: «Todo eso lo he guardado desde mi juventud».

[[luke-18-22]]
^22^ Oyendo esto Jesús, le dijo: «Aún te falta una cosa. Todo cuanto tienes véndelo y repártelo entre los pobres, y tendrás un tesoro en los cielos; luego, ven y sígueme».

[[luke-18-23]]
^23^ Al oír esto, se puso muy triste, porque era muy rico.

[[luke-18-24]]
^24^ Viéndole Jesús, dijo: «¡Qué difícil es que los que tienen riquezas entren en el Reino de Dios!

[[luke-18-25]]
^25^ Es más fácil que un camello entre por el ojo de una aguja, que el que un rico entre en el Reino de Dios».

[[luke-18-26]]
^26^ Los que lo oyeron, dijeron: «¿Y quién se podrá salvar?»

[[luke-18-27]]
^27^ Respondió: «Lo imposible para los hombres, es posible para Dios».

[[luke-18-28]]
^28^ Dijo entonces Pedro: «Ya lo ves, nosotros hemos dejado nuestras cosas y te hemos seguido».

[[luke-18-29]]
^29^ El les dijo: «Yo os aseguro que nadie que haya dejado casa, mujer, hermanos, padres o hijos por el Reino de Dios,

[[luke-18-30]]
^30^ quedará sin recibir mucho más al presente y, en el mundo venidero, vida eterna».

[[luke-18-31]]
^31^ Tomando consigo a los Doce, les dijo: «Mirad que subimos a Jerusalén, y se cumplirá todo lo que los profetas escribieron para el Hijo del hombre;

[[luke-18-32]]
^32^ pues será entregado a los gentiles, y será objeto de burlas, insultado y escupido;

[[luke-18-33]]
^33^ y después de azotarle le matarán, y al tercer día resucitará».

[[luke-18-34]]
^34^ Ellos nada de esto comprendieron; estas palabras les quedaban ocultas y no entendían lo que decía.

[[luke-18-35]]
^35^ Sucedió que, al acercarse él a Jericó, estaba un ciego sentado junto al camino pidiendo limosna;

[[luke-18-36]]
^36^ al oír que pasaba gente, preguntó qué era aquello.

[[luke-18-37]]
^37^ Le informaron que pasaba Jesús el Nazoreo

[[luke-18-38]]
^38^ y empezó a gritar, diciendo: «¡Jesús, Hijo de David, ten compasión de mí!»

[[luke-18-39]]
^39^ Los que iban delante le increpaban para que se callara, pero él gritaba mucho más: «¡Hijo de David, ten compasión de mí!»

[[luke-18-40]]
^40^ Jesús se detuvo, y mandó que se lo trajeran y, cuando se hubo acercado, le preguntó:

[[luke-18-41]]
^41^ «¿Qué quieres que te haga?» El dijo: «¡Señor, que vea!»

[[luke-18-42]]
^42^ Jesús le dijo: «Ve. Tu fe te ha salvado».

[[luke-18-43]]
^43^ Y al instante recobró la vista, y le seguía glorificando a Dios. Y todo el pueblo, al verlo, alabó a Dios.
[[luke-19]]
== Capítulo 19

[[luke-19-1]]
^1^ Habiendo entrado en Jericó, atravesaba la ciudad.

[[luke-19-2]]
^2^ Había un hombre llamado Zaqueo, que era jefe de publicanos, y rico.

[[luke-19-3]]
^3^ Trataba de ver quién era Jesús, pero no podía a causa de la gente, porque era de pequeña estatura.

[[luke-19-4]]
^4^ Se adelantó corriendo y se subió a un sicómoro para verle, pues iba a pasar por allí.

[[luke-19-5]]
^5^ Y cuando Jesús llegó a aquel sitio, alzando la vista, le dijo: «Zaqueo, baja pronto; porque conviene que hoy me quede yo en tu casa».

[[luke-19-6]]
^6^ Se apresuró a bajar y le recibió con alegría.

[[luke-19-7]]
^7^ Al verlo, todos murmuraban diciendo: «Ha ido a hospedarse a casa de un hombre pecador».

[[luke-19-8]]
^8^ Zaqueo, puesto en pie, dijo al Señor: «Daré, Señor, la mitad de mis bienes a los pobres; y si en algo defraudé a alguien, le devolveré el cuádruplo».

[[luke-19-9]]
^9^ Jesús le dijo: «Hoy ha llegado la salvación a esta casa, porque también éste es hijo de Abraham,

[[luke-19-10]]
^10^ pues el Hijo del hombre ha venido a buscar y salvar lo que estaba perdido».

[[luke-19-11]]
^11^ Estando la gente escuchando estas cosas, añadió una parábola, pues estaba él cerca de Jerusalén, y creían ellos que el Reino de Dios aparecería de un momento a otro.

[[luke-19-12]]
^12^ Dijo pues: «Un hombre noble marchó a un país lejano, para recibir la investidura real y volverse.

[[luke-19-13]]
^13^ Habiendo llamado a diez siervos suyos, les dio diez minas y les dijo: “Negociad hasta que vuelva.”

[[luke-19-14]]
^14^ Pero sus ciudadanos le odiaban y enviaron detrás de él una embajada que dijese: “No queremos que ése reine sobre nosotros.”

[[luke-19-15]]
^15^ «Y sucedió que, cuando regresó, después de recibir la investidura real, mandó llamar a aquellos siervos suyos, a los que había dado el dinero, para saber lo que había ganado cada uno.

[[luke-19-16]]
^16^ Se presentó el primero y dijo: “Señor, tu mina ha producido diez minas.”

[[luke-19-17]]
^17^ Le respondió: “¡Muy bien, siervo bueno!; ya que has sido fiel en lo mínimo, toma el gobierno de diez ciudades.”

[[luke-19-18]]
^18^ Vino el segundo y dijo: “Tu mina, Señor, ha producido cinco minas.”

[[luke-19-19]]
^19^ Dijo a éste: “Ponte tú también al mando de cinco ciudades.”

[[luke-19-20]]
^20^ «Vino el otro y dijo: “Señor, aquí tienes tu mina, que he tenido guardada en un lienzo;

[[luke-19-21]]
^21^ pues tenía miedo de tí, que eres un hombre severo; que tomas lo que no pusiste, y cosechas lo que no sembraste.”

[[luke-19-22]]
^22^ Dícele: “Por tu propia boca te juzgo, siervo malo; sabías que yo soy un hombre severo, que tomo lo que no puse y cosecho lo que no sembré;

[[luke-19-23]]
^23^ pues ¿por qué no colocaste mi dinero en el banco? Y así, al volver yo, lo habría cobrado con los intereses.”

[[luke-19-24]]
^24^ Y dijo a los presentes: “Quitadle la mina y dádsela al que tiene las diez minas.”

[[luke-19-25]]
^25^ Dijéronle: “Señor, tiene ya diez minas.”

[[luke-19-26]]
^26^ - “Os digo que a todo el que tiene, se le dará; pero al que no tiene, aun lo que tiene se le quitará.”

[[luke-19-27]]
^27^ «“Pero a aquellos enemigos míos, los que no quisieron que yo reinara sobre ellos, traedlos aquí y matadlos delante de mí.”»

[[luke-19-28]]
^28^ Y habiendo dicho esto, marchaba por delante subiendo a Jerusalén.

[[luke-19-29]]
^29^ Y sucedió que, al aproximarse a Betfagé y Betania, al pie del monte llamado de los Olivos, envió a dos de sus discípulos,

[[luke-19-30]]
^30^ diciendo: «Id al pueblo que está enfrente y, entrando en él, encontraréis un pollino atado, sobre el que no ha montado todavía ningún hombre; desatadlo y traedlo.

[[luke-19-31]]
^31^ Y si alguien os pregunta: “¿Por qué lo desatáis?”, diréis esto: “Porque el Señor lo necesita.”»

[[luke-19-32]]
^32^ Fueron, pues, los enviados y lo encontraron como les había dicho.

[[luke-19-33]]
^33^ Cuando desataban el pollino, les dijeron los dueños: «¿Por qué desatáis el pollino?»

[[luke-19-34]]
^34^ Ellos les contestaron: «Porque el Señor lo necesita».

[[luke-19-35]]
^35^ Y lo trajeron donde Jesús; y echando sus mantos sobre el pollino, hicieron montar a Jesús.

[[luke-19-36]]
^36^ Mientras él avanzaba, extendían sus mantos por el camino.

[[luke-19-37]]
^37^ Cerca ya de la bajada del monte de los Olivos, toda la multitud de los discípulos, llenos de alegría, se pusieron a alabar a Dios a grandes voces, por todos los milagros que habían visto.

[[luke-19-38]]
^38^ Decían: «Bendito el Rey que viene en nombre del Señor! Paz en el cielo y gloria en las alturas».

[[luke-19-39]]
^39^ Algunos de los fariseos, que estaban entre la gente, le dijeron: «Maestro, reprende a tus discípulos».

[[luke-19-40]]
^40^ Respondió: «Os digo que si éstos callan gritarán las piedras».

[[luke-19-41]]
^41^ Al acercarse y ver la ciudad, lloró por ella,

[[luke-19-42]]
^42^ diciendo: «¡Si también tú conocieras en este día el mensaje de paz! Pero ahora ha quedado oculto a tus ojos.

[[luke-19-43]]
^43^ Porque vendrán días sobre ti, en que tus enemigos te rodearán de empalizadas, te cercarán y te apretarán por todas partes,

[[luke-19-44]]
^44^ y te estrellarán contra el suelo a ti y a tus hijos que estén dentro de ti, y no dejarán en ti piedra sobre piedra, porque no has conocido el tiempo de tu visita».

[[luke-19-45]]
^45^ Entrando en el Templo, comenzó a echar fuera a los que vendían,

[[luke-19-46]]
^46^ diciéndoles: «Está escrito: Mi Casa será Casa de oración. ¡Pero vosotros la habéis hecho una cueva de bandidos!»

[[luke-19-47]]
^47^ Enseñaba todos los días en el Templo. Por su parte, los sumos sacerdotes, los escribas y también los notables del pueblo buscaban matarle,

[[luke-19-48]]
^48^ pero no encontraban qué podrían hacer, porque todo el pueblo le oía pendiente de sus labios.
[[luke-20]]
== Capítulo 20

[[luke-20-1]]
^1^ Y sucedió que un día enseñaba al pueblo en el Templo y anunciaba la Buena Nueva; se acercaron los sumos sacerdotes y los escribas junto con los ancianos,

[[luke-20-2]]
^2^ y le preguntaron: «Dinos: ¿Con qué autoridad haces esto, o quién es el que te ha dado tal autoridad?»

[[luke-20-3]]
^3^ El les respondió: «También yo os voy a preguntar una cosa. Decidme:

[[luke-20-4]]
^4^ El bautismo de Juan, ¿era del cielo o de los hombres?»

[[luke-20-5]]
^5^ Ellos discurrían entre sí: «Si decimos: “Del cielo”, dirá: “¿Por qué no le creísteis?”

[[luke-20-6]]
^6^ Pero si decimos: “De los hombres”, todo el pueblo nos apedreará, pues están convencidos de que Juan era un profeta».

[[luke-20-7]]
^7^ Respondieron, pues, que no sabían de dónde era.

[[luke-20-8]]
^8^ Jesús entonces les dijo: «Tampoco yo os digo con qué autoridad hago esto».

[[luke-20-9]]
^9^ Se puso a decir al pueblo esta parábola: «Un hombre plantó una viña y la arrendó a unos labradores, y se ausentó por mucho tiempo.

[[luke-20-10]]
^10^ «A su debido tiempo, envió un siervo a los labradores, para que le diesen parte del fruto de la viña. Pero los labradores, después de golpearle, le despacharon con las manos vacías.

[[luke-20-11]]
^11^ Volvió a enviar otro siervo, pero ellos, después de golpearle e insultarle, le despacharon con las manos vacías.

[[luke-20-12]]
^12^ Tornó a enviar un tercero, pero ellos, después de herirle, le echaron.

[[luke-20-13]]
^13^ Dijo, pues, el dueño de la viña: “¿Qué haré? Voy a enviar a mi hijo querido; tal vez le respeten.”

[[luke-20-14]]
^14^ Pero los labradores, al verle, se dijeron entre sí: “Este es el heredero; matémosle, para que la herencia sea nuestra.”

[[luke-20-15]]
^15^ Y, echándole fuera de la viña, le mataron. «¿Qué hará, pues, con ellos el dueño de la viña?

[[luke-20-16]]
^16^ Vendrá y dará muerte a estos labradores, y entregará la viña a otros». Al oír esto, dijeron: «De ninguna manera».

[[luke-20-17]]
^17^ Pero él clavando en ellos la mirada, dijo: «Pues, ¿qué es lo que está escrito: La piedra que los constructores desecharon en piedra angular se ha convertido?

[[luke-20-18]]
^18^ Todo el que caiga sobre esta piedra, se destrozará, y a aquel sobre quien ella caiga, le aplastará».

[[luke-20-19]]
^19^ Los escribas y los sumos sacerdotes trataron de echarle mano en aquel mismo momento - pero tuvieron miedo al pueblo - porque habían comprendido que aquella parábola la había dicho por ellos.

[[luke-20-20]]
^20^ Quedándose ellos al acecho, le enviaron unos espías, que fingieran ser justos, para sorprenderle en alguna palabra y poderle entregar al poder y autoridad del procurador.

[[luke-20-21]]
^21^ Y le preguntaron: «Maestro, sabemos que hablas y enseñas con rectitud, y que no tienes en cuenta la condición de las personas, sino que enseñas con franqueza el camino de Dios:

[[luke-20-22]]
^22^ ¿Nos es lícito pagar tributo al César o no?»

[[luke-20-23]]
^23^ Pero él, habiendo conocido su astucia, les dijo:

[[luke-20-24]]
^24^ «Mostradme un denario. ¿De quién lleva la imagen y la inscripción?» Ellos dijeron: «Del César».

[[luke-20-25]]
^25^ El les dijo: «Pues bien, lo del César devolvédselo al César, y lo de Dios a Dios».

[[luke-20-26]]
^26^ No pudieron sorprenderle en ninguna palabra ante el pueblo y, maravillados por su respuesta, se callaron.

[[luke-20-27]]
^27^ Acercándose algunos de los saduceos, esos que sostienen que no hay resurrección, le preguntaron:

[[luke-20-28]]
^28^ «Maestro, Moisés nos dejó escrito que si muere el hermano de alguno, que estaba casado y no tenía hijos, que su hermano tome a la mujer para dar descendencia a su hermano.

[[luke-20-29]]
^29^ Eran siete hermanos; habiendo tomado mujer el primero, murió sin hijos;

[[luke-20-30]]
^30^ y la tomó el segundo,

[[luke-20-31]]
^31^ luego el tercero; del mismo modo los siete murieron también sin dejar hijos.

[[luke-20-32]]
^32^ Finalmente, también murió la mujer.

[[luke-20-33]]
^33^ Esta, pues, ¿de cuál de ellos será mujer en la resurrección? Porque los siete la tuvieron por mujer».

[[luke-20-34]]
^34^ Jesús les dijo: «Los hijos de este mundo toman mujer o marido;

[[luke-20-35]]
^35^ pero los que alcancen a ser dignos de tener parte en aquel mundo y en la resurrección de entre los muertos, ni ellos tomarán mujer ni ellas marido,

[[luke-20-36]]
^36^ ni pueden ya morir, porque son como ángeles, y son hijos de Dios, siendo hijos de la resurrección.

[[luke-20-37]]
^37^ Y que los muertos resucitan lo ha indicado también Moisés en lo de la zarza, cuando llama al Señor el Dios de Abraham, el Dios de Isaac y el Dios de Jacob.

[[luke-20-38]]
^38^ No es un Dios de muertos, sino de vivos, porque para él todos viven».

[[luke-20-39]]
^39^ Algunos de los escribas le dijeron: «Maestro, has hablado bien».

[[luke-20-40]]
^40^ Pues ya no se atrevían a preguntarle nada.

[[luke-20-41]]
^41^ Les preguntó: «¿Cómo dicen que el Cristo es hijo de David?

[[luke-20-42]]
^42^ Porque David mismo dice en el libro de los Salmos: Dijo el Señor a mi Señor: Siéntate a mi diestra

[[luke-20-43]]
^43^ hasta que ponga a tus enemigos por escabel de tus pies.

[[luke-20-44]]
^44^ David, pues, le llama Señor; ¿cómo entonces puede ser hijo suyo?»

[[luke-20-45]]
^45^ Estando todo el pueblo oyendo, dijo a los discípulos:

[[luke-20-46]]
^46^ «Guardaos de los escribas, que gustan pasear con amplio ropaje y quieren ser saludados en las plazas, ocupar los primeros asientos en las sinagogas, y los primeros puestos en los banquetes;

[[luke-20-47]]
^47^ y que devoran la hacienda de las viudas so capa de largas oraciones. Esos tendrán una sentencia más rigurosa».
[[luke-21]]
== Capítulo 21

[[luke-21-1]]
^1^ Alzando la mirada, vió a unos ricos que echaban sus donativos en el arca del Tesoro;

[[luke-21-2]]
^2^ vio también a una viuda pobre que echaba allí dos moneditas,

[[luke-21-3]]
^3^ y dijo: «De verdad os digo que esta viuda pobre ha echado más que todos.

[[luke-21-4]]
^4^ Porque todos éstos han echado como donativo de lo que les sobraba, ésta en cambio ha echado de lo que necesitaba, todo cuanto tenía para vivir».

[[luke-21-5]]
^5^ Como dijeran algunos, acerca del Templo, que estaba adornado de bellas piedras y ofrendas votivas, él dijo:

[[luke-21-6]]
^6^ «Esto que veis, llegarán días en que no quedará piedra sobre piedra que no sea derruida».

[[luke-21-7]]
^7^ Le preguntaron: «Maestro, ¿cuándo sucederá eso? Y ¿cuál será la señal de que todas estas cosas están para ocurrir?»

[[luke-21-8]]
^8^ El dijo: «Mirad, no os dejéis engañar. Porque vendrán muchos usurpando mi nombre y diciendo: “Yo soy” y “el tiempo está cerca”. No les sigáis.

[[luke-21-9]]
^9^ Cuando oigáis hablar de guerras y revoluciones, no os aterréis; porque es necesario que sucedan primero estas cosas, pero el fin no es inmediato».

[[luke-21-10]]
^10^ Entonces les dijo: «Se levantará nación contra nación y reino contra reino.

[[luke-21-11]]
^11^ Habrá grandes terremotos, peste y hambre en diversos lugares, habrá cosas espantosas, y grandes señales del cielo.

[[luke-21-12]]
^12^ «Pero, antes de todo esto, os echarán mano y os perseguirán, entregándoos a las sinagogas y cárceles y llevándoos ante reyes y gobernadores por mi nombre;

[[luke-21-13]]
^13^ esto os sucederá para que deis testimonio.

[[luke-21-14]]
^14^ Proponed, pues, en vuestro corazón no preparar la defensa,

[[luke-21-15]]
^15^ porque yo os daré una elocuencia y una sabiduría a la que no podrán resistir ni contradecir todos vuestros adversarios.

[[luke-21-16]]
^16^ Seréis entregados por padres, hermanos, parientes y amigos, y matarán a algunos de vosotros,

[[luke-21-17]]
^17^ y seréis odiados de todos por causa de mi nombre.

[[luke-21-18]]
^18^ Pero no perecerá ni un cabello de vuestra cabeza.

[[luke-21-19]]
^19^ Con vuestra perseverancia salvaréis vuestras almas.

[[luke-21-20]]
^20^ «Cuando veáis a Jerusalén cercada por ejércitos, sabed entonces que se acerca su desolación.

[[luke-21-21]]
^21^ Entonces, los que estén en Judea, huyan a los montes; y los que estén en medio de la ciudad, que se alejen; y los que estén en los campos, que no entren en ella;

[[luke-21-22]]
^22^ porque éstos son días de venganza, y se cumplirá todo cuanto está escrito.

[[luke-21-23]]
^23^ ¡Ay de las que estén encinta o criando en aquellos días! «Habrá, en efecto, una gran calamidad sobre la tierra, y Cólera contra este pueblo;

[[luke-21-24]]
^24^ y caerán a filo de espada, y serán llevados cautivos a todas las naciones, y Jerusalén será pisoteada por los gentiles, hasta que se cumpla el tiempo de los gentiles.

[[luke-21-25]]
^25^ «Habrá señales en el sol, en la luna y en las estrellas; y en la tierra, angustia de las gentes, perplejas por el estruendo del mar y de las olas,

[[luke-21-26]]
^26^ muriéndose los hombres de terror y de ansiedad por las cosas que vendrán sobre el mundo; porque las fuerzas de los cielos serán sacudidas.

[[luke-21-27]]
^27^ Y entonces verán venir al Hijo del hombre en una nube con gran poder y gloria.

[[luke-21-28]]
^28^ Cuando empiecen a suceder estas cosas, cobrad ánimo y levantad la cabeza porque se acerca vuestra liberación».

[[luke-21-29]]
^29^ Les añadió una parábola: «Mirad la higuera y todos los árboles.

[[luke-21-30]]
^30^ Cuando ya echan brotes, al verlos, sabéis que el verano está ya cerca.

[[luke-21-31]]
^31^ Así también vosotros, cuando veáis que sucede esto, sabed que el Reino de Dios está cerca.

[[luke-21-32]]
^32^ Yo os aseguro que no pasará esta generación hasta que todo esto suceda.

[[luke-21-33]]
^33^ El cielo y la tierra pasarán, pero mis palabras no pasarán.

[[luke-21-34]]
^34^ «Guardaos de que no se hagan pesados vuestros corazones por el libertinaje, por la embriaguez y por las preocupacines de la vida, y venga aquel Día de improviso sobre vosotros,

[[luke-21-35]]
^35^ como un lazo; porque vendrá sobre todos los que habitan toda la faz de la tierra.

[[luke-21-36]]
^36^ Estad en vela, pues, orando en todo tiempo para que tengáis fuerza y escapéis a todo lo que está para venir, y podáis estar en pie delante del Hijo del hombre».

[[luke-21-37]]
^37^ Por el día enseñaba en el Templo y salía a pasar la noche en el monte llamado de los Olivos.

[[luke-21-38]]
^38^ Y todo el pueblo madrugaba para ir donde él y escucharle en el Templo.
[[luke-22]]
== Capítulo 22

[[luke-22-1]]
^1^ Se acercaba la fiesta de los Azimos, llamada Pascua.

[[luke-22-2]]
^2^ Los sumos sacerdotes y los escribas buscaban cómo hacerle desaparecer, pues temían al pueblo.

[[luke-22-3]]
^3^ Entonces Satanás entró en Judas, llamado Iscariote, que era del número de los Doce;

[[luke-22-4]]
^4^ y se fue a tratar con los sumos sacerdotes y los jefes de la guardia del modo de entregárselo.

[[luke-22-5]]
^5^ Ellos se alegraron y quedaron con él en darle dinero.

[[luke-22-6]]
^6^ El aceptó y andaba buscando una oportunidad para entregarle sin que la gente lo advirtiera.

[[luke-22-7]]
^7^ Llegó el día de los Azimos, en el que se había de sacrificar el cordero de Pascua;

[[luke-22-8]]
^8^ y envió a Pedro y a Juan, diciendo: «Id y preparadnos la Pascua para que la comamos».

[[luke-22-9]]
^9^ Ellos le dijeron: «¿Dónde quieres que la preparemos?»

[[luke-22-10]]
^10^ Les dijo: «Cuando entréis en la ciudad, os saldrá al paso un hombre llevando un cántaro de agua; seguidle hasta la casa en que entre,

[[luke-22-11]]
^11^ y diréis al dueño de la casa: “El Maestro te dice: ¿Dónde está la sala donde pueda comer la Pascua con mis discípulos?”

[[luke-22-12]]
^12^ El os enseñará en el piso superior una sala grande, ya dispuesta; haced allí los preparativos».

[[luke-22-13]]
^13^ Fueron y lo encontraron tal como les había dicho, y prepararon la Pascua.

[[luke-22-14]]
^14^ Cuando llegó la hora, se puso a la mesa con los apóstoles;

[[luke-22-15]]
^15^ y les dijo: «Con ansia he deseado comer esta Pascua con vosotros antes de padecer;

[[luke-22-16]]
^16^ porque os digo que ya no la comeré más hasta que halle su cumplimiento en el Reino de Dios».

[[luke-22-17]]
^17^ Y recibiendo una copa, dadas las gracias, dijo: «Tomad esto y repartidlo entre vosotros;

[[luke-22-18]]
^18^ porque os digo que, a partir de este momento, no beberé del producto de la vid hasta que llegue el Reino de Dios».

[[luke-22-19]]
^19^ Tomó luego pan, y, dadas las gracias, lo partió y se lo dio diciendo: Este es mi cuerpo que es entregado por vosotros; haced esto en recuerdo mío».

[[luke-22-20]]
^20^ De igual modo, después de cenar, la copa, diciendo: «Esta copa es la Nueva Alianza en mi sangre, que es derramada por vosotros.

[[luke-22-21]]
^21^ «Pero la mano del que me entrega está aquí conmigo sobre la mesa.

[[luke-22-22]]
^22^ Porque el Hijo del hombre se marcha según está determinado. Pero, ¡ay de aquel por quien es entregado!»

[[luke-22-23]]
^23^ Entonces se pusieron a discutir entre sí quién de ellos sería el que iba a hacer aquello.

[[luke-22-24]]
^24^ Entre ellos hubo también un altercado sobre quién de ellos parecía ser el mayor.

[[luke-22-25]]
^25^ El les dijo: «Los reyes de las naciones las dominan como señores absolutos, y los que ejercen el poder sobre ellas se hacen llamar Bienhechores;

[[luke-22-26]]
^26^ pero no así vosotros, sino que el mayor entre vosotros sea como el más joven y el que gobierna como el que sirve.

[[luke-22-27]]
^27^ Porque, ¿quién es mayor, el que está a la mesa o el que sirve? ¿No es el que está a la mesa? Pues yo estoy en medio de vosotros como el que sirve.

[[luke-22-28]]
^28^ «Vosotros sois los que habéis perseverado conmigo en mis pruebas;

[[luke-22-29]]
^29^ yo, por mi parte, dispongo un Reino para vosotros, como mi Padre lo dispuso para mí,

[[luke-22-30]]
^30^ para que comáis y bebáis a mi mesa en mi Reino y os sentéis sobre tronos para juzgar a las doce tribus de Israel.

[[luke-22-31]]
^31^ «¡Simón, Simón! Mira que Satanás ha solicitado el poder cribaros como trigo;

[[luke-22-32]]
^32^ pero yo he rogado por ti, para que tu fe no desfallezca. Y tú, cuando hayas vuelto, confirma a tus hermanos».

[[luke-22-33]]
^33^ El dijo: «Señor, estoy dispuesto a ir contigo hasta la cárcel y la muerte».

[[luke-22-34]]
^34^ Pero él dijo: «Te digo, Pedro: No cantará hoy el gallo antes que hayas negado tres veces que me conoces».

[[luke-22-35]]
^35^ Y les dijo: «Cuando os envié sin bolsa, sin alforja y sin sandalias, ¿os faltó algo?» Ellos dijeron: «Nada».

[[luke-22-36]]
^36^ Les dijo: «Pues ahora, el que tenga bolsa que la tome y lo mismo alforja, y el que no tenga que venda su manto y compre una espada;

[[luke-22-37]]
^37^ porque os digo que es necesario que se cumpla en mí esto que está escrito: “Ha sido contado entre los malhechores.” Porque lo mío toca a su fin».

[[luke-22-38]]
^38^ Ellos dijeron: «Señor, aquí hay dos espadas». El les dijo: «Basta».

[[luke-22-39]]
^39^ Salió y, como de costumbre, fue al monte de los Olivos, y los discípulos le siguieron.

[[luke-22-40]]
^40^ Llegado al lugar les dijo: «Pedid que no caigáis en tentación».

[[luke-22-41]]
^41^ Y se apartó de ellos como un tiro de piedra, y puesto de rodillas oraba

[[luke-22-42]]
^42^ diciendo: «Padre, si quieres, aparta de mí esta copa; pero no se haga mi voluntad, sino la tuya».

[[luke-22-43]]
^43^ Entonces, se le apareció un ángel venido del cielo que le confortaba.

[[luke-22-44]]
^44^ Y sumido en agonía, insistía más en su oración. Su sudor se hizo como gotas espesas de sangre que caían en tierra.

[[luke-22-45]]
^45^ Levantándose de la oración, vino donde los discípulos y los encontró dormidos por la tristeza;

[[luke-22-46]]
^46^ y les dijo: «¿Cómo es que estáis dormidos? Levantaos y orad para que no caigáis en tentación».

[[luke-22-47]]
^47^ Todavía estaba hablando, cuando se presentó un grupo; el llamado Judas, uno de los Doce, iba el primero, y se acercó a Jesús para darle un beso.

[[luke-22-48]]
^48^ Jesús le dijo: «¡Judas, con un beso entregas al Hijo del hombre!»

[[luke-22-49]]
^49^ Viendo los que estaban con él lo que iba a suceder, dijeron: «Señor, ¿herimos a espada?»

[[luke-22-50]]
^50^ y uno de ellos hirió al siervo del Sumo Sacerdote y le llevó la oreja derecha.

[[luke-22-51]]
^51^ Pero Jesús dijo: «¡Dejad! ¡Basta ya!» Y tocando la oreja le curó.

[[luke-22-52]]
^52^ Dijo Jesús a los sumos sacerdotes, jefes de la guardia del Templo y ancianos que habían venido contra él: «¿Como contra un salteador habéis salido con espadas y palos?

[[luke-22-53]]
^53^ Estando yo todos los días en el Templo con vosotros, no me pusisteis las manos encima; pero esta es vuestra hora y el poder de las tinieblas».

[[luke-22-54]]
^54^ Entonces le prendieron, se lo llevaron y le hicieron entrar en la casa del Sumo Sacerdote; Pedro le iba siguiendo de lejos.

[[luke-22-55]]
^55^ Habían encendido una hoguera en medio del patio y estaban sentados alrededor; Pedro se sentó entre ellos.

[[luke-22-56]]
^56^ Una criada, al verle sentado junto a la lumbre, se le quedó mirando y dijo: «Este también estaba con él».

[[luke-22-57]]
^57^ Pero él lo negó: «¡Mujer, no le conozco!»

[[luke-22-58]]
^58^ Poco después, otro, viéndole, dijo: «Tú también eres uno de ellos». Pedro dijo: «Hombre, no lo soy!»

[[luke-22-59]]
^59^ Pasada como una hora, otro aseguraba: «Cierto que éste también estaba con él, pues además es galileo».

[[luke-22-60]]
^60^ Le dijo Pedro: «¡Hombre, no sé de qué hablas!» Y en aquel momento, estando aún hablando, cantó un gallo,

[[luke-22-61]]
^61^ y el Señor se volvió y miró a Pedro, y recordó Pedro las palabras del Señor, cuando le dijo: «Antes que cante hoy el gallo, me habrás negado tres veces».

[[luke-22-62]]
^62^ Y, saliendo fuera, rompió a llorar amargamente.

[[luke-22-63]]
^63^ Los hombres que le tenían preso se burlaban de él y le golpeaban;

[[luke-22-64]]
^64^ y cubriéndole con un velo le preguntaban: «¡Adivina! ¿Quién es el que te ha pegado?»

[[luke-22-65]]
^65^ Y le insultaban diciéndole otras muchas cosas.

[[luke-22-66]]
^66^ En cuanto se hizo de día, se reunió el Consejo de Ancianos del pueblo, sumos sacerdotes y escribas, le hiceron venir a su Sanedrín

[[luke-22-67]]
^67^ y le dijeron: «Si tú eres el Cristo, dínoslo». El respondió: «Si os lo digo, no me creeréis.

[[luke-22-68]]
^68^ Si os pregunto, no me responderéis.

[[luke-22-69]]
^69^ De ahora en adelante, el Hijo del hombre estará sentado a la diestra del poder de Dios».

[[luke-22-70]]
^70^ Dijeron todos: «Entonces, ¿tú eres el Hijo de Dios?» El les dijo: «Vosotros lo decís: Yo soy».

[[luke-22-71]]
^71^ Dijeron ellos: «¿Qué necesidad tenemos ya de testigos, pues nosotros mismos lo hemos oído de su propia boca?»
[[luke-23]]
== Capítulo 23

[[luke-23-1]]
^1^ Y levantándose todos ellos, le llevaron ante Pilato.

[[luke-23-2]]
^2^ Comenzaron a acusarle diciendo: «Hemos encontrado a éste alborotando a nuestro pueblo, prohibiendo pagar tributos al César y diciendo que él es Cristo Rey».

[[luke-23-3]]
^3^ Pilato le preguntó: «¿Eres tú el Rey de los judíos?» El le respondió: «Sí, tú lo dices».

[[luke-23-4]]
^4^ Pilato dijo a los sumos sacerdotes y a la gente: «Ningún delito encuentro en este hombre».

[[luke-23-5]]
^5^ Pero ellos insistían diciendo: «Solivianta al pueblo, enseñando por toda Judea, desde Galilea, donde comenzó, hasta aquí».

[[luke-23-6]]
^6^ Al oír esto, Pilato preguntó si aquel hombre era galileo.

[[luke-23-7]]
^7^ Y, al saber que era de la jurisdicción de Herodes, le remitió a Herodes, que por aquellos días estaba también en Jerusalén.

[[luke-23-8]]
^8^ Cuando Herodes vio a Jesús se alegró mucho, pues hacía largo tiempo que deseaba verle, por las cosas que oía de él, y esperaba presenciar alguna señal que él hiciera.

[[luke-23-9]]
^9^ Le preguntó con mucha palabrería, pero él no respondió nada.

[[luke-23-10]]
^10^ Estaban allí los sumos sacerdotes y los escribas acusándole con insistencia.

[[luke-23-11]]
^11^ Pero Herodes, con su guardia, después de despreciarle y burlarse de él, le puso un espléndido vestido y le remitió a Pilato.

[[luke-23-12]]
^12^ Aquel día Herodes y Pilato se hicieron amigos, pues antes estaban enemistados.

[[luke-23-13]]
^13^ Pilato convocó a los sumos sacerdotes, a los magistrados y al pueblo

[[luke-23-14]]
^14^ y les dijo: «Me habéis traído a este hombre como alborotador del pueblo, pero yo le he interrogado delante de vosotros y no he hallado en este hombre ninguno de los delitos de que le acusáis.

[[luke-23-15]]
^15^ Ni tampoco Herodes, porque nos lo ha remitido. Nada ha hecho, pues, que merezca la muerte.

[[luke-23-16]]
^16^ Así que le castigaré y le soltaré».

[[luke-23-18]]
^18^ Toda la muchedumbre se puso a gritar a una: «¡Fuera ése, suéltanos a Barrabás!»

[[luke-23-19]]
^19^ Este había sido encarcelado por un motín que hubo en la ciudad y por asesinato.

[[luke-23-20]]
^20^ Pilato les habló de nuevo, intentando librar a Jesús,

[[luke-23-21]]
^21^ pero ellos seguían gritando: «¡Crucifícale, crucifícale!»

[[luke-23-22]]
^22^ Por tercera vez les dijo: «Pero ¿qué mal ha hecho éste? No encuentro en él ningún delito que merezca la muerte; así que le castigaré y le soltaré».

[[luke-23-23]]
^23^ Pero ellos insistían pidiendo a grandes voces que fuera crucificado y sus gritos eran cada vez más fuertes.

[[luke-23-24]]
^24^ Pilato sentenció que se cumpliera su demanda.

[[luke-23-25]]
^25^ Soltó, pues, al que habían pedido, el que estaba en la cárcel por motín y asesinato, y a Jesús se lo entregó a su voluntad.

[[luke-23-26]]
^26^ Cuando le llevaban, echaron mano de un cierto Simón de Cirene, que venía del campo, y le cargaron la cruz para que la llevará detrás de Jesús.

[[luke-23-27]]
^27^ Le seguía una gran multitud del pueblo y mujeres que se dolían y se lamentaban por él.

[[luke-23-28]]
^28^ Jesús, volviéndose a ellas, dijo: «Hijas de Jerusalén, no lloréis por mí; llorad más bien por vosotras y por vuestros hijos.

[[luke-23-29]]
^29^ Porque llegarán días en que se dirá: ¡Dichosas las estériles, las entrañas que no engendraron y los pechos que no criaron!

[[luke-23-30]]
^30^ Entonces se pondrán a decir a los montes: ¡Caed sobre nosotros! Y a las colinas: ¡Cubridnos!

[[luke-23-31]]
^31^ Porque si en el leño verde hacen esto, en el seco ¿qué se hará?»

[[luke-23-32]]
^32^ Llevaban además otros dos malhechores para ejecutarlos con él.

[[luke-23-33]]
^33^ Llegados al lugar llamado Calvario, le crucificaron allí a él y a los malhechores, uno a la derecha y otro a la izquierda.

[[luke-23-34]]
^34^ Jesús decía: «Padre, perdónales, porque no saben lo que hacen». Se repartieron sus vestidos, echando a suertes.

[[luke-23-35]]
^35^ Estaba el pueblo mirando; los magistrados hacían muecas diciendo: «A otros salvó; que se salve a sí mismo si él es el Cristo de Dios, el Elegido».

[[luke-23-36]]
^36^ También los soldados se burlaban de él y, acercándose, le ofrecían vinagre

[[luke-23-37]]
^37^ y le decían: «Si tú eres el Rey de los judíos, ¡sálvate!»

[[luke-23-38]]
^38^ Había encima de él una inscripción: «Este es el Rey de los judíos».

[[luke-23-39]]
^39^ Uno de los malhechores colgados le insultaba: «¿No eres tú el Cristo? Pues ¡sálvate a ti y a nosotros!»

[[luke-23-40]]
^40^ Pero el otro le respondió diciendo: «¿Es que no temes a Dios, tú que sufres la misma condena?

[[luke-23-41]]
^41^ Y nosotros con razón, porque nos lo hemos merecido con nuestros hechos; en cambio, éste nada malo ha hecho».

[[luke-23-42]]
^42^ Y decía: «Jesús, acuérdate de mí cuando vengas con tu Reino».

[[luke-23-43]]
^43^ Jesús le dijo: «Yo te aseguro: hoy estarás conmigo en el Paraíso».

[[luke-23-44]]
^44^ Era ya cerca de la hora sexta cuando, al eclipsarse el sol, hubo oscuridad sobre toda la tierra hasta la hora nona.

[[luke-23-45]]
^45^ El velo del Santuario se rasgó por medio

[[luke-23-46]]
^46^ y Jesús, dando un fuerte grito, dijo: «Padre, en tus manos pongo mi espíritu» y, dicho esto, expiró.

[[luke-23-47]]
^47^ Al ver el centurión lo sucedido, glorificaba a Dios diciendo: «Ciertamente este hombre era justo».

[[luke-23-48]]
^48^ Y todas las gentes que habían acudido a aquel espectáculo, al ver lo que pasaba, se volvieron golpeándose el pecho.

[[luke-23-49]]
^49^ Estaban a distancia, viendo estas cosas, todos sus conocidos y las mujeres que le habían seguido desde Galilea.

[[luke-23-50]]
^50^ Había un hombre llamado José, miembro del Consejo, hombre bueno y justo,

[[luke-23-51]]
^51^ que no había asentido al consejo y proceder de los demás. Era de Arimatea, ciudad de Judea, y esperaba el Reino de Dios.

[[luke-23-52]]
^52^ Se presentó a Pilato y le pidió el cuerpo de Jesús

[[luke-23-53]]
^53^ y, después de descolgarle, le envolvió en una sábana y le puso en un sepulcro excavado en la roca en el que nadie había sido puesto todavía.

[[luke-23-54]]
^54^ Era el día de la Preparación, y apuntaba el sábado.

[[luke-23-55]]
^55^ Las mujeres que habían venido con él desde Galilea, fueron detrás y vieron el sepulcro y cómo era colocado su cuerpo,

[[luke-23-56]]
^56^ Y regresando, prepararon aromas y mirra. Y el sábado descansaron según el precepto.
[[luke-24]]
== Capítulo 24

[[luke-24-1]]
^1^ El primer día de la semana, muy de mañana, fueron al sepulcro llevando los aromas que habían preparado.

[[luke-24-2]]
^2^ Pero encontraron que la piedra había sido retirada del sepulcro,

[[luke-24-3]]
^3^ y entraron, pero no hallaron el cuerpo del Señor Jesús.

[[luke-24-4]]
^4^ No sabían que pensar de esto, cuando se presentaron ante ellas dos hombres con vestidos resplandecientes.

[[luke-24-5]]
^5^ Como ellas temiesen e inclinasen el rostro a tierra, les dijeron: «¿Por qué buscáis entre los muertos al que está vivo?

[[luke-24-6]]
^6^ No está aquí, ha resucitado. Recordad cómo os habló cuando estaba todavía en Galilea, diciendo:

[[luke-24-7]]
^7^ “Es necesario que el Hijo del hombre sea entregado en manos de los pecadores y sea crucificado, y al tercer día resucite. “»

[[luke-24-8]]
^8^ Y ellas recordaron sus palabras.

[[luke-24-9]]
^9^ Regresando del sepulcro, anunciaron todas estas cosas a los Once y a todos los demás.

[[luke-24-10]]
^10^ Las que decían estas cosas a los apóstoles eran María Magdalena, Juana y María la de Santiago y las demás que estaban con ellas.

[[luke-24-11]]
^11^ Pero todas estas palabras les parecían como desatinos y no les creían.

[[luke-24-12]]
^12^ Pedro se levantó y corrió al sepulcro. Se inclinó, pero sólo vio las vendas y se volvió a su casa, asombrado por lo sucedido.

[[luke-24-13]]
^13^ Aquel mismo día iban dos de ellos a un pueblo llamado Emaús, que distaba sesenta estadios de Jerusalén,

[[luke-24-14]]
^14^ y conversaban entre sí sobre todo lo que había pasado.

[[luke-24-15]]
^15^ Y sucedió que, mientras ellos conversaban y discutían, el mismo Jesús se acercó y siguió con ellos;

[[luke-24-16]]
^16^ pero sus ojos estaban retenidos para que no le conocieran.

[[luke-24-17]]
^17^ El les dijo: «¿De qué discutís entre vosotros mientras vais andando?» Ellos se pararon con aire entristecido.

[[luke-24-18]]
^18^ Uno de ellos llamado Cleofás le respondió: «¿Eres tú el único residente en Jerusalén que no sabe las cosas que estos días han pasado en ella?»

[[luke-24-19]]
^19^ El les dijo: «¿Qué cosas?» Ellos le dijeron: «Lo de Jesús el Nazoreo, que fue un profeta poderoso en obras y palabras delante de Dios y de todo el pueblo;

[[luke-24-20]]
^20^ cómo nuestros sumos sacerdotes y magistrados le condenaron a muerte y le crucificaron.

[[luke-24-21]]
^21^ Nosotros esperábamos que sería él el que iba a librar a Israel; pero, con todas estas cosas, llevamos ya tres días desde que esto pasó.

[[luke-24-22]]
^22^ El caso es que algunas mujeres de las nuestras nos han sobresaltado, porque fueron de madrugada al sepulcro,

[[luke-24-23]]
^23^ y, al no hallar su cuerpo, vinieron diciendo que hasta habían visto una aparición de ángeles, que decían que él vivía.

[[luke-24-24]]
^24^ Fueron también algunos de los nuestros al sepulcro y lo hallaron tal como las mujeres habían dicho, pero a él no le vieron».

[[luke-24-25]]
^25^ El les dijo: «¡Oh insensatos y tardos de corazón para creer todo lo que dijeron los profetas!

[[luke-24-26]]
^26^ ¿No era necesario que el Cristo padeciera eso y entrara así en su gloria?»

[[luke-24-27]]
^27^ Y, empezando por Moisés y continuando por todos los profetas, les explicó lo que había sobre él en todas las Escrituras.

[[luke-24-28]]
^28^ Al acercarse al pueblo a donde iban, él hizo ademán de seguir adelante.

[[luke-24-29]]
^29^ Pero ellos le forzaron diciéndole: «Quédate con nosotros, porque atardece y el día ya ha declinado». Y entró a quedarse con ellos.

[[luke-24-30]]
^30^ Y sucedió que, cuando se puso a la mesa con ellos, tomó el pan, pronunció la bendición, lo partió y se lo iba dando.

[[luke-24-31]]
^31^ Entonces se les abrieron los ojos y le reconocieron, pero él desapareció de su lado.

[[luke-24-32]]
^32^ Se dijeron uno a otro: «¿No estaba ardiendo nuestro corazón dentro de nosotros cuando nos hablaba en el camino y nos explicaba las Escrituras?»

[[luke-24-33]]
^33^ Y, levantándose al momento, se volvieron a Jerusalén y encontraron reunidos a los Once y a los que estaban con ellos,

[[luke-24-34]]
^34^ que decían: «¡Es verdad! ¡El Señor ha resucitado y se ha aparecido a Simón!»

[[luke-24-35]]
^35^ Ellos, por su parte, contaron lo que había pasado en el camino y cómo le habían conocido en la fracción del pan.

[[luke-24-36]]
^36^ Estaban hablando de estas cosas, cuando él se presentó en medio de ellos y les dijo: «La paz con vosotros».

[[luke-24-37]]
^37^ Sobresaltados y asustados, creían ver un espíritu.

[[luke-24-38]]
^38^ Pero él les dijo: «¿Por qué os turbáis, y por qué se suscitan dudas en vuestro corazón?

[[luke-24-39]]
^39^ Mirad mis manos y mis pies; soy yo mismo. Palpadme y ved que un espíritu no tiene carne y huesos como véis que yo tengo».

[[luke-24-40]]
^40^ Y, diciendo esto, los mostró las manos y los pies.

[[luke-24-41]]
^41^ Como ellos no acabasen de creerlo a causa de la alegría y estuviesen asombrados, les dijo: «¿Tenéis aquí algo de comer?»

[[luke-24-42]]
^42^ Ellos le ofrecieron parte de un pez asado.

[[luke-24-43]]
^43^ Lo tomó y comió delante de ellos.

[[luke-24-44]]
^44^ Después les dijo: «Estas son aquellas palabras mías que os hablé cuando todavía estaba con vosotros: “Es necesario que se cumpla todo lo que está escrito en la Ley de Moisés, en los Profetas y en los Salmos acerca de mí.”»

[[luke-24-45]]
^45^ Y, entonces, abrió sus inteligencias para que comprendieran las Escrituras,

[[luke-24-46]]
^46^ y les dijo: «Así está escrito que el Cristo padeciera y resucitara de entre los muertos al tercer día

[[luke-24-47]]
^47^ y se predicara en su nombre la conversión para perdón de los pecados a todas las naciones, empezando desde Jerusalén.

[[luke-24-48]]
^48^ Vosotros sois testigos de estas cosas.

[[luke-24-49]]
^49^ «Mirad, y voy a enviar sobre vosotros la Promesa de mi Padre. Por vuestra parte permaneced en la ciudad hasta que seáis revestidos de poder desde lo alto».

[[luke-24-50]]
^50^ Los sacó hasta cerca de Betania y, alzando sus manos, los bendijo.

[[luke-24-51]]
^51^ Y sucedió que, mientras los bendecía, se separó de ellos y fue llevado al cielo.

[[luke-24-52]]
^52^ Ellos, después de postrarse ante él, se volvieron a Jerusalén con gran gozo,

[[luke-24-53]]
^53^ y estaban siempre en el Templo bendiciendo a Dios.
