[[john]]
= Juan

[[john-1]]
== Capítulo 1

[[john-1-1]]
^1^ En el principio existía la Palabra y la Palabra estaba con Dios, y la Palabra era Dios.

[[john-1-2]]
^2^ Ella estaba en el principio con Dios.

[[john-1-3]]
^3^ Todo se hizo por ella y sin ella no se hizo nada de cuanto existe.

[[john-1-4]]
^4^ En ella estaba la vida y la vida era la luz de los hombres,

[[john-1-5]]
^5^ y la luz brilla en las tinieblas, y las tinieblas no la vencieron.

[[john-1-6]]
^6^ Hubo un hombre, enviado por Dios: se llamaba Juan.

[[john-1-7]]
^7^ Este vino para un testimonio, para dar testimonio de la luz, para que todos creyeran por él.

[[john-1-8]]
^8^ No era él la luz, sino quien debía dar testimonio de la luz.

[[john-1-9]]
^9^ La Palabra era la luz verdadera que ilumina a todo hombre que viene a este mundo.

[[john-1-10]]
^10^ En el mundo estaba, y el mundo fue hecho por ella, y el mundo no la conoció.

[[john-1-11]]
^11^ Vino a su casa, y los suyos no la recibieron.

[[john-1-12]]
^12^ Pero a todos los que la recibieron les dio poder de hacerse hijos de Dios, a los que creen en su nombre;

[[john-1-13]]
^13^ la cual no nació de sangre, ni de deseo de hombre, sino que nació de Dios.

[[john-1-14]]
^14^ Y la Palabra se hizo carne, y puso su Morada entre nosotros, y hemos contemplado su gloria, gloria que recibe del Padre como Hijo único, lleno de gracia y de verdad.

[[john-1-15]]
^15^ Juan da testimonio de él y clama: «Este era del que yo dije: El que viene detrás de mí se ha puesto delante de mí, porque existía antes que yo».

[[john-1-16]]
^16^ Pues de su plenitud hemos recibido todos, y gracia por gracia.

[[john-1-17]]
^17^ Porque la Ley fue dada por medio de Moisés; la gracia y la verdad nos han llegado por Jesucristo.

[[john-1-18]]
^18^ A Dios nadie le ha visto jamás: el Hijo único, que está en el seno del Padre, él lo ha contado.

[[john-1-19]]
^19^ Y este fue el testimonio de Juan, cuando los judíos enviaron donde él desde Jerusalén sacerdotes y levitas a preguntarle: «¿Quién eres tú?»

[[john-1-20]]
^20^ El confesó, y no negó; confesó: «Yo no soy el Cristo».

[[john-1-21]]
^21^ Y le preguntaron: «¿Qué, pues? ¿Eres tú Elías?» El dijo: «No lo soy». - «¿Eres tú el profeta?» Respondió: «No».

[[john-1-22]]
^22^ Entonces le dijeron: «¿Quién eres, pues, para que demos respuesta a los que nos han enviado? ¿Qué dices de ti mismo?»

[[john-1-23]]
^23^ Dijo él: «Yo soy voz del que clama en el desierto: Rectificad el camino del Señor, como dijo el profeta Isaías».

[[john-1-24]]
^24^ Los enviados eran fariseos.

[[john-1-25]]
^25^ Y le preguntaron: «¿Por qué, pues, bautizas, si no eres tú el Cristo ni Elías ni el profeta?»

[[john-1-26]]
^26^ Juan les respondió: «Yo bautizo con agua, pero en medio de vosotros está uno a quien no conocéis,

[[john-1-27]]
^27^ que viene detrás de mí, a quien yo no soy digno de desatarle la correa de su sandalia».

[[john-1-28]]
^28^ Esto ocurrió en Betania, al otro lado del Jordán, donde estaba Juan bautizando.

[[john-1-29]]
^29^ Al día siguiente ve a Jesús venir hacia él y dice: «He ahí el Cordero de Dios, que quita el pecado del mundo.

[[john-1-30]]
^30^ Este es por quien yo dije: Detrás de mí viene un hombre, que se ha puesto delante de mí, porque existía antes que yo.

[[john-1-31]]
^31^ Y yo no le conocía, pero he venido a bautizar en agua para que él sea manifestado a Israel».

[[john-1-32]]
^32^ Y Juan dio testimonio diciendo: «He visto al Espíritu que bajaba como una paloma del cielo y se quedaba sobre él.

[[john-1-33]]
^33^ Y yo no le conocía pero el que me envió a bautizar con agua, me dijo: “Aquel sobre quien veas que baja el Espíritu y se queda sobre él, ése es el que bautiza con Espíritu Santo.”

[[john-1-34]]
^34^ Y yo le he visto y doy testimonio de que éste es el Elegido de Dios».

[[john-1-35]]
^35^ Al día siguiente, Juan se encontraba de nuevo allí con dos de sus discípulos.

[[john-1-36]]
^36^ Fijándose en Jesús que pasaba, dice: «He ahí el Cordero de Dios».

[[john-1-37]]
^37^ Los dos discípulos le oyeron hablar así y siguieron a Jesús.

[[john-1-38]]
^38^ Jesús se volvió, y al ver que le seguían les dice: «¿Qué buscáis?» Ellos le respondieron: «Rabbí - que quiere decir, “Maestro” - ¿dónde vives?»

[[john-1-39]]
^39^ Les respondió: «Venid y lo veréis». Fueron, pues, vieron dónde vivía y se quedaron con él aquel día. Era más o menos la hora décima.

[[john-1-40]]
^40^ Andrés, el hermano de Simón Pedro, era uno de los dos que habían oído a Juan y habían seguido a Jesús.

[[john-1-41]]
^41^ Este se encuentra primeramente con su hermano Simón y le dice: «Hemos encontrado al Mesías» - que quiere decir, Cristo.

[[john-1-42]]
^42^ Y le llevó donde Jesús. Jesús, fijando su mirada en él, le dijo: «Tú eres Simón, el hijo de Juan; tú te llamarás Cefas» - que quiere decir, “Piedra”.

[[john-1-43]]
^43^ Al día siguiente, Jesús quiso partir para Galilea. Se encuentra con Felipe y le dice: «Sígueme».

[[john-1-44]]
^44^ Felipe era de Bestsaida, de la ciudad de Andrés y Pedro.

[[john-1-45]]
^45^ Felipe se encuentra con Natanael y le dice: «Ese del que escribió Moisés en la Ley, y también los profetas, lo hemos encontrado: Jesús el hijo de José, el de Nazaret».

[[john-1-46]]
^46^ Le respondió Natanael: «¿De Nazaret puede haber cosa buena?» Le dice Felipe: «Ven y lo verás».

[[john-1-47]]
^47^ Vio Jesús que se acercaba Natanael y dijo de él: «Ahí tenéis a un israelita de verdad, en quien no hay engaño».

[[john-1-48]]
^48^ Le dice Natanael: «¿De qué me conoces?» Le respondió Jesús: «Antes de que Felipe te llamara, cuando estabas debajo de la higuera, te vi».

[[john-1-49]]
^49^ Le respondió Natanael: «Rabbí, tú eres el Hijo de Dios, tú eres el Rey de Israel».

[[john-1-50]]
^50^ Jesús le contestó: «¿Por haberte dicho que te vi debajo de la higuera, crees? Has de ver cosas mayores».

[[john-1-51]]
^51^ Y le añadió: «En verdad, en verdad os digo: veréis el cielo abierto y a los ángeles de Dios subir y bajar sobre el Hijo del hombre».
[[john-2]]
== Capítulo 2

[[john-2-1]]
^1^ Tres días después se celebraba una boda en Caná de Galilea y estaba allí la madre de Jesús.

[[john-2-2]]
^2^ Fue invitado también a la boda Jesús con sus discípulos.

[[john-2-3]]
^3^ Y, como faltara vino, porque se había acabado el vino de la boda, le dice a Jesús su madre: «No tienen vino».

[[john-2-4]]
^4^ Jesús le responde: «¿Qué tengo yo contigo, mujer? Todavía no ha llegado mi hora».

[[john-2-5]]
^5^ Dice su madre a los sirvientes: «Haced lo que él os diga».

[[john-2-6]]
^6^ Había allí seis tinajas de piedra, puestas para las purificaciones de los judíos, de dos o tres medidas cada una.

[[john-2-7]]
^7^ Les dice Jesús: «Llenad las tinajas de agua». Y las llenaron hasta arriba.

[[john-2-8]]
^8^ «Sacadlo ahora, les dice, y llevadlo al maestresala». Ellos lo llevaron.

[[john-2-9]]
^9^ Cuando el maestresala probó el agua convertida en vino, como ignoraba de dónde era (los sirvientes, los que habían sacado el agua, sí que lo sabían), llama el maestresala al novio

[[john-2-10]]
^10^ y le dice: «Todos sirven primero el vino bueno y cuando ya están bebidos, el inferior. Pero tú has guardado el vino bueno hasta ahora».

[[john-2-11]]
^11^ Así, en Caná de Galilea, dio Jesús comienzo a sus señales. Y manifestó su gloria, y creyeron en él sus discípulos.

[[john-2-12]]
^12^ Después bajó a Cafarnaúm con su madre y sus hermanos y sus discípulos, pero no se quedaron allí muchos días.

[[john-2-13]]
^13^ Se acercaba la Pascua de los judíos y Jesús subió a Jerusalén.

[[john-2-14]]
^14^ Y encontró en el Templo a los vendedores de bueyes, ovejas y palomas, y a los cambistas en sus puestos.

[[john-2-15]]
^15^ Haciendo un látigo con cuerdas, echó a todos fuera del Templo, con las ovejas y los bueyes; desparramó el dinero de los cambistas y les volcó las mesas;

[[john-2-16]]
^16^ y dijo a los que vendían palomas: «Quitad esto de aquí. No hagáis de la Casa de mi Padre una casa de mercado».

[[john-2-17]]
^17^ Sus discípulos se acordaron de que estaba escrito: El celo por tu Casa me devorará.

[[john-2-18]]
^18^ Los judíos entonces le replicaron diciéndole: «Qué señal nos muestras para obrar así?»

[[john-2-19]]
^19^ Jesús les respondió: «Destruid este Santuario y en tres días lo levantaré».

[[john-2-20]]
^20^ Los judíos le contestaron: «Cuarenta y seis años se han tardado en construir este Santuario, ¿y tú lo vas a levantar en tres días?»

[[john-2-21]]
^21^ Pero él hablaba del Santuario de su cuerpo.

[[john-2-22]]
^22^ Cuando resucitó, pues, de entre los muertos, se acordaron sus discípulos de que había dicho eso, y creyeron en la Escritura y en las palabras que había dicho Jesús.

[[john-2-23]]
^23^ Mientras estuvo en Jerusalén, por la fiesta de la Pascua, creyeron muchos en su nombre al ver las señales que realizaba.

[[john-2-24]]
^24^ Pero Jesús no se confiaba a ellos porque los conocía a todos

[[john-2-25]]
^25^ y no tenía necesidad de que se le diera testimonio acerca de los hombres, pues él conocía lo que hay en el hombre.
[[john-3]]
== Capítulo 3

[[john-3-1]]
^1^ Había entre los fariseos un hombre llamado Nicodemo, magistrado judío.

[[john-3-2]]
^2^ Fue éste donde Jesús de noche y le dijo: «Rabbí, sabemos que has venido de Dios como maestro, porque nadie puede realizar las señales que tú realizas si Dios no está con él».

[[john-3-3]]
^3^ Jesús le respondió: «En verdad, en verdad te digo: el que no nazca de lo alto no puede ver el Reino de Dios».

[[john-3-4]]
^4^ Dícele Nicodemo: «¿Cómo puede uno nacer siendo ya viejo? ¿Puede acaso entrar otra vez en el seno de su madre y nacer?»

[[john-3-5]]
^5^ Respondió Jesús: «En verdad, en verdad te digo: el que no nazca de agua y de Espíritu no puede entrar en el Reino de Dios.

[[john-3-6]]
^6^ Lo nacido de la carne, es carne; lo nacido del Espíritu, es espíritu.

[[john-3-7]]
^7^ No te asombres de que te haya dicho: Tenéis que nacer de lo alto.

[[john-3-8]]
^8^ El viento sopla donde quiere, y oyes su voz, pero no sabes de dónde viene ni a dónde va. Así es todo el que nace del Espíritu».

[[john-3-9]]
^9^ Respondió Nicodemo: «¿Cómo puede ser eso?»

[[john-3-10]]
^10^ Jesús le respondió: «Tú eres maestro en Israel y ¿no sabes estas cosas?

[[john-3-11]]
^11^ «En verdad, en verdad te digo: nosotros hablamos de lo que sabemos y damos testimonio de lo que hemos visto, pero vosotros no aceptáis nuestro testimonio.

[[john-3-12]]
^12^ Si al deciros cosas de la tierra, no creéis, ¿cómo vais a creer si os digo cosas del cielo?

[[john-3-13]]
^13^ Nadie ha subido al cielo sino el que bajó del cielo, el Hijo del hombre.

[[john-3-14]]
^14^ Y como Moisés levantó la serpiente en el desierto, así tiene que ser levantado el Hijo del hombre,

[[john-3-15]]
^15^ para que todo el que crea tenga por él vida eterna.

[[john-3-16]]
^16^ Porque tanto amó Dios al mundo que dio a su Hijo único, para que todo el que crea en él no perezca, sino que tenga vida eterna.

[[john-3-17]]
^17^ Porque Dios no ha enviado a su Hijo al mundo para juzgar al mundo, sino para que el mundo se salve por él.

[[john-3-18]]
^18^ El que creee en él, no es juzgado; pero el que no cree, ya está juzgado, porque no ha creído en el Nombre del Hijo único de Dios.

[[john-3-19]]
^19^ Y el juicio está en que vino la luz al mundo, y los hombres amaron más las tinieblas que la luz, porque sus obras eran malas.

[[john-3-20]]
^20^ Pues todo el que obra el mal aborrece la luz y no va a la luz, para que no sean censuradas sus obras.

[[john-3-21]]
^21^ Pero el que obra la verdad, va a la luz, para que quede de manifiesto que sus obras están hechas según Dios».

[[john-3-22]]
^22^ Después de esto, se fue Jesús con sus discípulos al país de Judea; y allí se estaba con ellos y bautizaba.

[[john-3-23]]
^23^ Juan también estaba bautizando en Ainón, cerca de Salim, porque había allí mucha agua, y la gente acudía y se bautizaba.

[[john-3-24]]
^24^ Pues todavía Juan no había sido metido en la cárcel.

[[john-3-25]]
^25^ Se suscitó una discusión entre los discípulos de Juan y un judío acerca de la purificación.

[[john-3-26]]
^26^ Fueron, pues, donde Juan y le dijeron: «Rabbí, el que estaba contigo al otro lado del Jordán, aquel de quien diste testimonio, mira, está bautizando y todos se van a él».

[[john-3-27]]
^27^ Juan respondió: «Nadie puede recibir nada si no se le ha dado del cielo.

[[john-3-28]]
^28^ Vosotros mismos me sois testigos de que dije: “Yo no soy el Cristo, sino que he sido enviado delante de él.”

[[john-3-29]]
^29^ El que tiene a la novia es el novio; pero el amigo del novio, el que asiste y le oye, se alegra mucho con la voz del novio. Esta es, pues, mi alegría, que ha alcanzado su plenitud.

[[john-3-30]]
^30^ Es preciso que él crezca y que yo disminuya.

[[john-3-31]]
^31^ El que viene de arriba está por encima de todos: el que es de la tierra, es de la tierra y habla de la tierra. El que viene del cielo,

[[john-3-32]]
^32^ da testimonio de lo que ha visto y oído, y su testimonio nadie lo acepta.

[[john-3-33]]
^33^ El que acepta su testimonio certifica que Dios es veraz.

[[john-3-34]]
^34^ Porque aquel a quien Dios ha enviado habla las palabras de Dios, porque da el Espíritu sin medida.

[[john-3-35]]
^35^ El Padre ama al Hijo y ha puesto todo en su mano.

[[john-3-36]]
^36^ El que cree en el Hijo tiene vida eterna; el que rehúsa creer en el Hijo, no verá la vida, sino que la cólera de Dios permanece sobre él».
[[john-4]]
== Capítulo 4

[[john-4-1]]
^1^ Cuando Jesús se enteró de que había llegado a oídos de los fariseos que él hacía más discípulos y bautizaba más que Juan -

[[john-4-2]]
^2^ aunque no era Jesús mismo el que bautizaba, sino sus discípulos -,

[[john-4-3]]
^3^ abandonó Judea y volvió a Galilea.

[[john-4-4]]
^4^ Tenía que pasar por Samaria.

[[john-4-5]]
^5^ Llega, pues, a una ciudad de Samaria llamada Sicar, cerca de la heredad que Jacob dio a su hijo José.

[[john-4-6]]
^6^ Allí estaba el pozo de Jacob. Jesús, como se había fatigado del camino, estaba sentado junto al pozo. Era alrededor de la hora sexta.

[[john-4-7]]
^7^ Llega una mujer de Samaria a sacar agua. Jesús le dice: «Dame de beber».

[[john-4-8]]
^8^ Pues sus discípulos se habían ido a la ciudad a comprar comida. Le dice a la mujer samaritana:

[[john-4-9]]
^9^ «¿Cómo tú, siendo judío, me pides de beber a mí, que soy una mujer samaritana?» (Porque los judíos no se tratan con los samaritanos.)

[[john-4-10]]
^10^ Jesús le respondió: «Si conocieras el don de Dios, y quién es el que te dice: “Dame de beber”, tú le habrías pedido a él, y él te habría dado agua viva».

[[john-4-11]]
^11^ Le dice la mujer: «Señor, no tienes con qué sacarla, y el pozo es hondo; ¿de dónde, pues, tienes esa agua viva?

[[john-4-12]]
^12^ ¿Es que tú eres más que nuestro padre Jacob, que nos dio el pozo, y de él bebieron él y sus hijos y sus ganados?»

[[john-4-13]]
^13^ Jesús le respondió: «Todo el que beba de esta agua, volverá a tener sed;

[[john-4-14]]
^14^ pero el que beba del agua que yo le dé, no tendrá sed jamás, sino que el agua que yo le dé se convertirá en él en fuente de agua que brota para vida eterna».

[[john-4-15]]
^15^ Le dice la mujer: «Señor, dame de esa agua, para que no tenga más sed y no tenga que venir aquí a sacarla».

[[john-4-16]]
^16^ El le dice: «Vete, llama a tu marido y vuelve acá».

[[john-4-17]]
^17^ Respondió la mujer: «No tengo marido». Jesús le dice: «Bien has dicho que no tienes marido,

[[john-4-18]]
^18^ porque has tenido cinco maridos y el que ahora tienes no es marido tuyo; en eso has dicho la verdad».

[[john-4-19]]
^19^ Le dice la mujer: «Señor, veo que eres un profeta.

[[john-4-20]]
^20^ Nuestros padres adoraron en este monte y vosotros decís que en Jerusalén es el lugar donde se debe adorar».

[[john-4-21]]
^21^ Jesús le dice: «Créeme, mujer, que llega la hora en que, ni en este monte, ni en Jerusalén adoraréis al Padre.

[[john-4-22]]
^22^ Vosotros adoráis lo que no conocéis; nosotros adoramos lo que conocemos, porque la salvación viene de los judíos.

[[john-4-23]]
^23^ Pero llega la hora (ya estamos en ella) en que los adoradores verdaderos adorarán al Padre en espíritu y en verdad, porque así quiere el Padre que sean los que le adoren.

[[john-4-24]]
^24^ Dios es espíritu, y los que adoran, deben adorar en espíritu y verdad».

[[john-4-25]]
^25^ Le dice la mujer: «Sé que va a venir el Mesías, el llamado Cristo. Cuando venga, nos lo explicará todo».

[[john-4-26]]
^26^ Jesús le dice: «Yo soy, el que te está hablando».

[[john-4-27]]
^27^ En esto llegaron sus discípulos y se sorprendían de que hablara con una mujer. Pero nadie le dijo: «¿Qué quieres?» o «¿Qué hablas con ella?»

[[john-4-28]]
^28^ La mujer, dejando su cántaro, corrió a la ciudad y dijo a la gente:

[[john-4-29]]
^29^ «Venid a ver a un hombre que me ha dicho todo lo que he hecho. ¿No será el Cristo?»

[[john-4-30]]
^30^ Salieron de la ciudad e iban donde él.

[[john-4-31]]
^31^ Entretanto, los discípulos le insistían diciendo: «Rabbí, come».

[[john-4-32]]
^32^ Pero él les dijo: «Yo tengo para comer un alimento que vosotros no sabéis».

[[john-4-33]]
^33^ Los discípulos se decían unos a otros: «¿Le habrá traído alguien de comer?»

[[john-4-34]]
^34^ Les dice Jesús: «Mi alimento es hacer la voluntad del que me ha enviado y llevar a cabo su obra.

[[john-4-35]]
^35^ ¿No decís vosotros: Cuatro meses más y llega la siega? Pues bien, yo os digo: Alzad vuestros ojos y ved los campos, que blanquean ya para la siega. Ya

[[john-4-36]]
^36^ el segador recibe el salario, y recoge fruto para vida eterna, de modo que el sembrador se alegra igual que el segador.

[[john-4-37]]
^37^ Porque en esto resulta verdadero el refrán de que uno es el sembrador y otro el segador:

[[john-4-38]]
^38^ yo os he enviado a segar donde vosotros no os habéis fatigado. Otros se fatigaron y vosotros os aprovecháis de su fatiga».

[[john-4-39]]
^39^ Muchos samaritanos de aquella ciudad creyeron en él por las palabras de la mujer que atestiguaba: «Me ha dicho todo lo que he hecho».

[[john-4-40]]
^40^ Cuando llegaron donde él los samaritanos, le rogaron que se quedara con ellos. Y se quedó allí dos días.

[[john-4-41]]
^41^ Y fueron muchos más los que creyeron por sus palabras,

[[john-4-42]]
^42^ y decían a la mujer: «Ya no creemos por tus palabras; que nosotros mismos hemos oído y sabemos que éste es verdaderamente el Salvador del mundo».

[[john-4-43]]
^43^ Pasados los dos días, partió de allí para Galilea.

[[john-4-44]]
^44^ Pues Jesús mismo había afirmado que un profeta no goza de estima en su patria.

[[john-4-45]]
^45^ Cuando llegó, pues, a Galilea, los galileos le hicieron un buen recibimiento, porque habían visto todo lo que había hecho en Jerusalén durante la fiesta, pues también ellos habían ido a la fiesta.

[[john-4-46]]
^46^ Volvió, pues, a Caná de Galilea, donde había convertido el agua en vino. Había un funcionario real, cuyo hijo estaba enfermo en Cafarnaúm.

[[john-4-47]]
^47^ Cuando se enteró de que Jesús había venido de Judea a Galilea, fue donde él y le rogaba que bajase a curar a su hijo, porque se iba a morir.

[[john-4-48]]
^48^ Entonces Jesús le dijo: «Si no veis señales y prodigios, no creéis».

[[john-4-49]]
^49^ Le dice el funcionario: «Señor, baja antes que se muera mi hijo».

[[john-4-50]]
^50^ Jesús le dice: «Vete, que tu hijo vive». Creyó el hombre en la palabra que Jesús le había dicho y se puso en camino.

[[john-4-51]]
^51^ Cuando bajaba, le salieron al encuentro sus siervos, y le dijeron que su hijo vivía.

[[john-4-52]]
^52^ El les preguntó entonces la hora en que se había sentido mejor. Ellos le dijeron: «Ayer a la hora séptima le dejó la fiebre».

[[john-4-53]]
^53^ El padre comprobó que era la misma hora en que le había dicho Jesús: «Tu hijo vive», y creyó él y toda su familia.

[[john-4-54]]
^54^ Esta nueva señal, la segunda, la realizó Jesús cuando volvió de Judea a Galilea.
[[john-5]]
== Capítulo 5

[[john-5-1]]
^1^ Después de esto, hubo una fiesta de los judíos, y Jesús subió a Jerusalén.

[[john-5-2]]
^2^ Hay en Jerusalén, junto a la Probática, una piscina que se llama en hebreo Betesda, que tiene cinco pórticos.

[[john-5-3]]
^3^ En ellos yacía una multitud de enfermos, ciegos, cojos, paralíticos, esperando la agitación del agua.

[[john-5-4]]
^4^ Porque el Angel del Señor bajaba de tiempo en tiempo a la piscina y agitaba el agua; y el primero que se metía después de la agitación del agua, quedaba curado de cualquier mal que tuviera.

[[john-5-5]]
^5^ Había allí un hombre que llevaba treinta y ocho años enfermo.

[[john-5-6]]
^6^ Jesús, viéndole tendido y sabiendo que llevaba ya mucho tiempo, le dice: «¿Quieres curarte?»

[[john-5-7]]
^7^ Le respondió el enfermo: «Señor, no tengo a nadie que me meta en la piscina cuando se agita el agua; y mientras yo voy, otro baja antes que yo».

[[john-5-8]]
^8^ Jesús le dice: «Levántate, toma tu camilla y anda».

[[john-5-9]]
^9^ Y al instante el hombre quedó curado, tomó su camilla y se puso a andar. Pero era sábado aquel día.

[[john-5-10]]
^10^ Por eso los judíos decían al que había sido curado: «Es sábado y no te está permitido llevar la camilla».

[[john-5-11]]
^11^ El le respondió: «El que me ha curado me ha dicho: Toma tu camilla y anda».

[[john-5-12]]
^12^ Ellos le preguntaron: «¿Quién es el hombre que te ha dicho: Tómala y anda?»

[[john-5-13]]
^13^ Pero el curado no sabía quién era, pues Jesús había desaparecido porque había mucha gente en aquel lugar.

[[john-5-14]]
^14^ Más tarde Jesús le encuentra en el Templo y le dice: «Mira, estás curado; no peques más, para que no te suceda algo peor».

[[john-5-15]]
^15^ El hombre se fue a decir a los judíos que era Jesús el que lo había curado.

[[john-5-16]]
^16^ Por eso los judíos perseguían a Jesús, porque hacía estas cosas en sábado.

[[john-5-17]]
^17^ Pero Jesús les replicó: «Mi Padre trabaja hasta ahora, y yo también trabajo».

[[john-5-18]]
^18^ Por eso los judíos trataban con mayor empeño de matarle, porque no sólo quebrantaba el sábado, sino que llamaba a Dios su propio Padre, haciéndose a sí mismo igual a Dios.

[[john-5-19]]
^19^ Jesús, pues, tomando la palabra, les decía: «En verdad, en verdad os digo: el Hijo no puede hacer nada por su cuenta, sino lo que ve hacer al Padre: lo que hace él, eso también lo hace igualmente el Hijo.

[[john-5-20]]
^20^ Porque el Padre quiere al Hijo y le muestra todo lo que él hace. Y le mostrará obras aún mayores que estas, para que os asombréis.

[[john-5-21]]
^21^ Porque, como el Padre resucita a los muertos y les da la vida, así también el Hijo da la vida a los que quiere.

[[john-5-22]]
^22^ Porque el Padre no juzga a nadie; sino que todo juicio lo ha entregado al Hijo,

[[john-5-23]]
^23^ para que todos honren al Hijo como honran al Padre. El que no honra al Hijo no honra al Padre que lo ha enviado.

[[john-5-24]]
^24^ En verdad, en verdad os digo: el que escucha mi Palabra y cree en el que me ha enviado, tiene vida eterna y no incurre en juicio, sino que ha pasado de la muerte a la vida.

[[john-5-25]]
^25^ En verdad, en verdad os digo: llega la hora (ya estamos en ella), en que los muertos oirán la voz del Hijo de Dios, y los que la oigan vivirán.

[[john-5-26]]
^26^ Porque, como el Padre tiene vida en sí mismo, así también le ha dado al Hijo tener vida en sí mismo,

[[john-5-27]]
^27^ y le ha dado poder para juzgar, porque es Hijo del hombre.

[[john-5-28]]
^28^ No os extrañéis de esto: llega la hora en que todos los que estén en los sepulcros oirán su voz

[[john-5-29]]
^29^ y saldrán los que hayan hecho el bien para una resurrección de vida, y los que hayan hecho el mal, para una resurrección de juicio.

[[john-5-30]]
^30^ Y no puedo hacer nada por mi cuenta: juzgo según lo que oigo; y mi juicio es justo, porque no busco mi voluntad, sino la voluntad del que me ha enviado.

[[john-5-31]]
^31^ «Si yo diera testimonio de mí mismo, mi testimonio no sería válido.

[[john-5-32]]
^32^ Otro es el que da testimonio de mí, y yo sé que es válido el testimonio que da de mí.

[[john-5-33]]
^33^ Vosotros mandasteis enviados donde Juan, y él dio testimonio de la verdad.

[[john-5-34]]
^34^ No es que yo busque testimonio de un hombre, sino que digo esto para que os salvéis.

[[john-5-35]]
^35^ El era la lámpara que arde y alumbra y vosotros quisisteis recrearos una hora con su luz.

[[john-5-36]]
^36^ Pero yo tengo un testimonio mayor que el de Juan; porque las obras que el Padre me ha encomendado llevar a cabo, las mismas obras que realizo, dan testimonio de mí, de que el Padre me ha enviado.

[[john-5-37]]
^37^ Y el Padre, que me ha enviado, es el que ha dado testimonio de mí. Vosotros no habéis oído nunca su voz, ni habéis visto nunca su rostro,

[[john-5-38]]
^38^ ni habita su palabra en vosotros, porque no creéis al que El ha enviado.

[[john-5-39]]
^39^ «Vosotros investigáis las escrituras, ya que creéis tener en ellas vida eterna; ellas son las que dan testimonio de mí;

[[john-5-40]]
^40^ y vosotros no queréis venir a mí para tener vida.

[[john-5-41]]
^41^ La gloria no la recibo de los hombres.

[[john-5-42]]
^42^ Pero yo os conozco: no tenéis en vosotros el amor de Dios.

[[john-5-43]]
^43^ Yo he venido en nombre de mi Padre, y no me recibís; si otro viene en su propio nombre, a ése le recibiréis.

[[john-5-44]]
^44^ ¿Cómo podéis creer vosotros, que aceptáis gloria unos de otros, y no buscáis la gloria que viene del único Dios?

[[john-5-45]]
^45^ No penséis que os voy a acusar yo delante del Padre. Vuestro acusador es Moisés, en quién habéis puesto vuestra esperanza.

[[john-5-46]]
^46^ Porque, si creyerais a Moisés, me creeríais a mí, porque él escribió de mí.

[[john-5-47]]
^47^ Pero si no creéis en sus escritos, cómo vais a creer en mis palabras?»
[[john-6]]
== Capítulo 6

[[john-6-1]]
^1^ Después de esto, se fue Jesús a la otra ribera del mar de Galilea, el de Tiberíades,

[[john-6-2]]
^2^ y mucha gente le seguía porque veían las señales que realizaba en los enfermos.

[[john-6-3]]
^3^ Subió Jesús al monte y se sentó allí en compañía de sus discípulos.

[[john-6-4]]
^4^ Estaba próxima la Pascua, la fiesta de los judíos.

[[john-6-5]]
^5^ Al levantar Jesús los ojos y ver que venía hacia él mucha gente, dice a Felipe: «¿Donde vamos a comprar panes para que coman éstos?»

[[john-6-6]]
^6^ Se lo decía para probarle, porque él sabía lo que iba a hacer.

[[john-6-7]]
^7^ Felipe le contestó: «Doscientos denarios de pan no bastan para que cada uno tome un poco».

[[john-6-8]]
^8^ Le dice uno de sus discípulos, Andrés, el hermano de Simón Pedro:

[[john-6-9]]
^9^ «Aquí hay un muchacho que tiene cinco panes de cebada y dos peces; pero ¿qué es eso para tantos?»

[[john-6-10]]
^10^ Dijo Jesús: «Haced que se recueste la gente». Había en el lugar mucha hierba. Se recostaron, pues, los hombres en número de unos 5.000.

[[john-6-11]]
^11^ Tomó entonces Jesús los panes y, después de dar gracias, los repartió entre los que estaban recostados y lo mismo los peces, todo lo que quisieron.

[[john-6-12]]
^12^ Cuando se saciaron, dice a sus discípulos: «Recoged los trozos sobrantes para que nada se pierda».

[[john-6-13]]
^13^ Los recogieron, pues, y llenaron doce canastos con los trozos de los cinco panes de cebada que sobraron a los que habían comido.

[[john-6-14]]
^14^ Al ver la gente la señal que había realizado, decía: «Este es verdaderamente el profeta que iba a venir al mundo».

[[john-6-15]]
^15^ Dándose cuenta Jesús de que intentaban venir a tomarle por la fuerza para hacerle rey, huyó de nuevo al monte él solo.

[[john-6-16]]
^16^ Al atardecer, bajaron sus discípulos a la orilla del mar,

[[john-6-17]]
^17^ y subiendo a una barca, se dirigían al otro lado del mar, a Cafarnaúm. Había ya oscurecido, y Jesús todavía no había venido donde ellos;

[[john-6-18]]
^18^ soplaba un fuerte viento y el mar comenzó a encresparse.

[[john-6-19]]
^19^ Cuando habían remado unos veinticinco o treinta estadios, ven a Jesús que caminaba sobre el mar y se acercaba a la barca, y tuvieron miedo.

[[john-6-20]]
^20^ Pero él les dijo: «Soy yo. No temáis».

[[john-6-21]]
^21^ Quisieron recogerle en la barca, pero en seguida la barca tocó tierra en el lugar a donde se dirigían.

[[john-6-22]]
^22^ Al día siguiente, la gente que se había quedado al otro lado del mar, vio que allí no había más que una barca y que Jesús no había montado en la barca con sus discípulos, sino que los discípulos se habían marchado solos.

[[john-6-23]]
^23^ Pero llegaron barcas de Tiberíades cerca del lugar donde habían comido pan.

[[john-6-24]]
^24^ Cuando la gente vio que Jesús no estaba allí, ni tampoco sus discípulos, subieron a las barcas y fueron a Cafarnaúm, en busca de Jesús.

[[john-6-25]]
^25^ Al encontrarle a la orilla del mar, le dijeron: «Rabbí, ¿cuándo has llegado aquí?»

[[john-6-26]]
^26^ Jesús les respondió: «En verdad, en verdad os digo: vosotros me buscáis, no porque habéis visto señales, sino porque habéis comido de los panes y os habéis saciado.

[[john-6-27]]
^27^ Obrad, no por el alimento perecedero, sino por el alimento que permanece para vida eterna, el que os dará el Hijo del hombre, porque a éste es a quien el Padre, Dios, ha marcado con su sello».

[[john-6-28]]
^28^ Ellos le dijeron: «¿Qué hemos de hacer para obrar las obras de Dios?»

[[john-6-29]]
^29^ Jesús les respondió: «La obra de Dios es que creáis en quien él ha enviado».

[[john-6-30]]
^30^ Ellos entonces le dijeron: «¿Qué señal haces para que viéndola creamos en ti? ¿Qué obra realizas?

[[john-6-31]]
^31^ Nuestros padres comieron el maná en el desierto, según está escrito: Pan del cielo les dio a comer».

[[john-6-32]]
^32^ Jesús les respondió: «En verdad, en verdad os digo: No fue Moisés quien os dio el pan del cielo; es mi Padre el que os da el verdadero pan del cielo;

[[john-6-33]]
^33^ porque el pan de Dios es el que baja del cielo y da la vida al mundo».

[[john-6-34]]
^34^ Entonces le dijeron: «Señor, danos siempre de ese pan».

[[john-6-35]]
^35^ Les dijo Jesús: «Yo soy el pan de la vida. El que venga a mí, no tendrá hambre, y el que crea en mí, no tendrá nunca sed.

[[john-6-36]]
^36^ Pero ya os lo he dicho: Me habéis visto y no creéis.

[[john-6-37]]
^37^ Todo lo que me dé el Padre vendrá a mí, y al que venga a mí no lo echaré fuera;

[[john-6-38]]
^38^ porque he bajado del cielo, no para hacer mi voluntad, sino la voluntad del que me ha enviado.

[[john-6-39]]
^39^ Y esta es la voluntad del que me ha enviado; que no pierda nada de lo que él me ha dado, sino que lo resucite el último día.

[[john-6-40]]
^40^ Porque esta es la voluntad de mi Padre: que todo el que vea al Hijo y crea en él, tenga vida eterna y que yo le resucite el último día».

[[john-6-41]]
^41^ Los judíos murmuraban de él, porque había dicho: «Yo soy el pan que ha bajado del cielo».

[[john-6-42]]
^42^ Y decían: «¿No es éste Jesús, hijo de José, cuyo padre y madre conocemos? ¿Cómo puede decir ahora: He bajado del cielo?»

[[john-6-43]]
^43^ Jesús les respondió: «No murmuréis entre vosotros.

[[john-6-44]]
^44^ «Nadie puede venir a mí, si el Padre que me ha enviado no lo atrae; y yo le resucitaré el último día.

[[john-6-45]]
^45^ Está escrito en los profetas: Serán todos enseñados por Dios. Todo el que escucha al Padre y aprende, viene a mí.

[[john-6-46]]
^46^ No es que alguien haya visto al Padre; sino aquel que ha venido de Dios, ése ha visto al Padre.

[[john-6-47]]
^47^ En verdad, en verdad os digo: el que cree, tiene vida eterna.

[[john-6-48]]
^48^ Yo soy el pan de la vida.

[[john-6-49]]
^49^ Vuestros padres comieron el maná en el desierto y murieron;

[[john-6-50]]
^50^ este es el pan que baja del cielo, para que quien lo coma no muera.

[[john-6-51]]
^51^ Yo soy el pan vivo, bajado del cielo. Si uno come de este pan, vivirá para siempre; y el pan que yo le voy a dar, es mi carne por la vida del mundo».

[[john-6-52]]
^52^ Discutían entre sí los judíos y decían: «¿Cómo puede éste darnos a comer su carne?»

[[john-6-53]]
^53^ Jesús les dijo: «En verdad, en verdad os digo: si no coméis la carne del Hijo del hombre, y no bebéis su sangre, no tenéis vida en vosotros.

[[john-6-54]]
^54^ El que come mi carne y bebe mi sangre, tiene vida eterna, y yo le resucitaré el último día.

[[john-6-55]]
^55^ Porque mi carne es verdadera comida y mi sangre verdadera bebida.

[[john-6-56]]
^56^ El que come mi carne y bebe mi sangre, permanece en mí, y yo en él.

[[john-6-57]]
^57^ Lo mismo que el Padre, que vive, me ha enviado y yo vivo por el Padre, también el que me coma vivirá por mí.

[[john-6-58]]
^58^ Este es el pan bajado del cielo; no como el que comieron vuestros padres, y murieron; el que coma este pan vivirá para siempre».

[[john-6-59]]
^59^ Esto lo dijo enseñando en la sinagoga, en Cafarnaúm.

[[john-6-60]]
^60^ Muchos de sus discípulos, al oírle, dijeron: «Es duro este lenguaje. ¿Quién puede escucharlo?»

[[john-6-61]]
^61^ Pero sabiendo Jesús en su interior que sus discípulos murmuraban por esto, les dijo: «¿Esto os escandaliza?

[[john-6-62]]
^62^ ¿Y cuando veáis al Hijo del hombre subir adonde estaba antes?...

[[john-6-63]]
^63^ «El espíritu es el que da vida; la carne no sirve para nada. Las palabras que os he dicho son espíritu y son vida.

[[john-6-64]]
^64^ «Pero hay entre vosotros algunos que no creen». Porque Jesús sabía desde el principio quiénes eran los que no creían y quién era el que lo iba a entregar.

[[john-6-65]]
^65^ Y decía: «Por esto os he dicho que nadie puede venir a mí si no se lo concede el Padre».

[[john-6-66]]
^66^ Desde entonces muchos de sus discípulos se volvieron atrás y ya no andaban con él.

[[john-6-67]]
^67^ Jesús dijo entonces a los Doce: «¿También vosotros queréis marcharos?»

[[john-6-68]]
^68^ Le respondió Simón Pedro: «Señor, ¿donde quién vamos a ir? Tú tienes palabras de vida eterna,

[[john-6-69]]
^69^ y nosotros creemos y sabemos que tú eres el Santo de Dios».

[[john-6-70]]
^70^ Jesús les respondió: «¿No os he elegido yo a vosotros, los Doce? Y uno de vosotros es un diablo».

[[john-6-71]]
^71^ Hablaba de Judas, hijo de Simón Iscariote, porque éste le iba a entregar, uno de los Doce.
[[john-7]]
== Capítulo 7

[[john-7-1]]
^1^ Después de esto, Jesús andaba por Galilea, y no podía andar por Judea, porque los judíos buscaban matarle.

[[john-7-2]]
^2^ Pero se acercaba la fiesta judía de las Tiendas.

[[john-7-3]]
^3^ Y le dijeron sus hermanos: «Sal de aquí y vete a Judea, para que también tus discípulos vean las obras que haces,

[[john-7-4]]
^4^ pues nadie actúa en secreto cuando quiere ser conocido. Si haces estas cosas, muéstrate al mundo».

[[john-7-5]]
^5^ Es que ni siquiera sus hermanos creían en él.

[[john-7-6]]
^6^ Entonces les dice Jesús: «Todavía no ha llegado mi tiempo, en cambio vuestro tiempo siempre está a mano.

[[john-7-7]]
^7^ El mundo no puede odiaros; a mí sí me aborrece, porque doy testimonio de que sus obras son perversas.

[[john-7-8]]
^8^ Subid vosotros a la fiesta; yo no subo a esta fiesta porque aún no se ha cumplido mi tiempo».

[[john-7-9]]
^9^ Dicho esto, se quedó en Galilea.

[[john-7-10]]
^10^ Pero después que sus hermanos subieron a la fiesta, entonces él también subió no manifiestamente, sino de incógnito.

[[john-7-11]]
^11^ Los judíos, durante la fiesta, andaban buscándole y decían: «¿Dónde está ése?»

[[john-7-12]]
^12^ Entre la gente había muchos comentarios acerca de él. Unos decían: «Es bueno». Otros decían: «No, sino que engaña al pueblo».

[[john-7-13]]
^13^ Pero nadie hablaba de él abiertamente por miedo a los judíos.

[[john-7-14]]
^14^ Mediada ya la fiesta, subió Jesús al Templo y se puso a enseñar.

[[john-7-15]]
^15^ Los judíos, asombrados, decían: «¿Cómo entiende de letras sin haber estudiado?»

[[john-7-16]]
^16^ Jesús les respondió: «Mi doctrina no es mía, sino del que me ha enviado.

[[john-7-17]]
^17^ Si alguno quiere cumplir su voluntad, verá si mi doctrina es de Dios o hablo yo por mi cuenta.

[[john-7-18]]
^18^ El que habla por su cuenta, busca su propia gloria; pero el que busca la gloria del que le ha enviado, ese es veraz; y no hay impostura en él.

[[john-7-19]]
^19^ ¿No es Moisés el que os dio la Ley? Y ninguno de vosotros cumple la Ley. ¿Por qué queréis matarme?»

[[john-7-20]]
^20^ Respondió la gente: «Tienes un demonio. ¿Quién quiere matarte?»

[[john-7-21]]
^21^ Jesús les respondió: «Una sola obra he hecho y todos os maravilláis.

[[john-7-22]]
^22^ Moisés os dio la circuncisión (no que provenga de Moisés, sino de los patriarcas) y vosotros circuncidáis a uno en sábado.

[[john-7-23]]
^23^ Si se circuncida a un hombre en sábado, para no quebrantar la Ley de Moisés, ¿os irritáis contra mí porque he curado a un hombre entero en sábado?

[[john-7-24]]
^24^ No juzguéis según la apariencia. Juzgad con juicio justo».

[[john-7-25]]
^25^ Decían algunos de los de Jerusalén: «¿No es a ése a quien quieren matar?

[[john-7-26]]
^26^ Mirad cómo habla con toda libertad y no le dicen nada. ¿Habrán reconocido de veras las autoridades que este es el Cristo?

[[john-7-27]]
^27^ Pero éste sabemos de dónde es, mientras que, cuando venga el Cristo, nadie sabrá de dónde es».

[[john-7-28]]
^28^ Gritó, pues, Jesús, enseñando en el Templo y diciendo: «Me conocéis a mí y sabéis de dónde soy. Pero yo no he venido por mi cuenta; sino que verdaderamente me envía el que me envía; pero vosotros no le conocéis.

[[john-7-29]]
^29^ Yo le conozco, porque vengo de él y él es el que me ha enviado».

[[john-7-30]]
^30^ Querían, pues, detenerle, pero nadie le echó mano, porque todavía no había llegado su hora.

[[john-7-31]]
^31^ Y muchos entre la gente creyeron en él y decían: «Cuando venga el Cristo, ¿hará más señales que las que ha hecho éste?»

[[john-7-32]]
^32^ Se enteraron los fariseos que la gente hacía estos comentarios acerca de él y enviaron guardias para detenerle.

[[john-7-33]]
^33^ Entonces él dijo: «Todavía un poco de tiempo estaré con vosotros, y me voy al que me ha enviado.

[[john-7-34]]
^34^ Me buscaréis y no me encontraréis; y adonde yo esté, vosotros no podéis venir».

[[john-7-35]]
^35^ Se decían entre sí los judíos: «¿A dónde se irá éste que nosotros no le podamos encontrar? ¿Se irá a los que viven dispersos entre los griegos para enseñar a los griegos?

[[john-7-36]]
^36^ ¿Qué es eso que ha dicho: “Me buscaréis y no me encontraréis”, y “adonde yo esté, vosotros no podéis venir”?»

[[john-7-37]]
^37^ El último día de la fiesta, el más solemne, Jesús puesto en pie, gritó: «Si alguno tiene sed, venga a mí, y beba

[[john-7-38]]
^38^ el que crea en mí», como dice la Escritura: De su seno correrán ríos de agua viva.

[[john-7-39]]
^39^ Esto lo deciá refiriéndose al Espíritu que iban a recibir los que creyeran en él. Porque aún no había Espíritu, pues todavía Jesús no había sido glorificado.

[[john-7-40]]
^40^ Muchos entre la gente, que le habían oído estas palabras, decían: «Este es verdaderamente el profeta».

[[john-7-41]]
^41^ Otros decían: «Este es el Cristo». Pero otros replicaban: «¿Acaso va a venir de Galilea el Cristo?

[[john-7-42]]
^42^ ¿No dice la Escritura que el Cristo vendrá de la descendencia de David y de Belén, el pueblo de donde era David?»

[[john-7-43]]
^43^ Se originó, pues, una disensión entre la gente por causa de él.

[[john-7-44]]
^44^ Algunos de ellos querían detenerle, pero nadie le echó mano.

[[john-7-45]]
^45^ Los guardias volvieron donde los sumos sacerdotes y los fariseos. Estos les dijeron: «¿Por qué no le habéis traído?»

[[john-7-46]]
^46^ Respondieron los guardias: «Jamás un hombre ha hablado como habla ese hombre».

[[john-7-47]]
^47^ Los fariseos les respondieron: «¿Vosotros también os habéis dejado embaucar?

[[john-7-48]]
^48^ ¿Acaso ha creído en él algún magistrado o algún fariseo?

[[john-7-49]]
^49^ Pero esa gente que no conoce la Ley son unos malditos».

[[john-7-50]]
^50^ Les dice Nicodemo, que era uno de ellos, el que había ido anteriormente donde Jesús:

[[john-7-51]]
^51^ «¿Acaso nuestra Ley juzga a un hombre sin haberle antes oído y sin saber lo que hace?»

[[john-7-52]]
^52^ Ellos le respondieron: «¿También tú eres de Galilea? Indaga y verás que de Galilea no sale ningún profeta».

[[john-7-53]]
^53^ Y se volvieron cada uno a su casa.
[[john-8]]
== Capítulo 8

[[john-8-1]]
^1^ Mas Jesús se fue al monte de los Olivos.

[[john-8-2]]
^2^ Pero de madrugada se presentó otra vez en el Templo, y todo el pueblo acudía a él. Entonces se sentó y se puso a enseñarles.

[[john-8-3]]
^3^ Los escribas y fariseos le llevan una mujer sorprendida en adulterio, la ponen en medio

[[john-8-4]]
^4^ y le dicen: «Maestro, esta mujer ha sido sorprendida en flagrante adulterio.

[[john-8-5]]
^5^ Moisés nos mandó en la Ley apedrear a estas mujeres. ¿Tú qué dices?»

[[john-8-6]]
^6^ Esto lo decían para tentarle, para tener de qué acuasarle. Pero Jesús, inclinándose, se puso a escribir con el dedo en la tierra.

[[john-8-7]]
^7^ Pero, como ellos insistían en preguntarle, se incorporó y les dijo: «Aquel de vosotros que esté sin pecado, que le arroje la primera piedra».

[[john-8-8]]
^8^ E inclinándose de nuevo, escribía en la tierra.

[[john-8-9]]
^9^ Ellos, al oír estas palabras, se iban retirando uno tras otro, comenzando por los más viejos; y se quedó solo Jesús con la mujer, que seguía en medio.

[[john-8-10]]
^10^ Incorporándose Jesús le dijo: «Mujer, ¿dónde están? ¿Nadie te ha condenado?»

[[john-8-11]]
^11^ Ella respondió: «Nadie, Señor». Jesús le dijo: «Tampoco yo te condeno. Vete, y en adelante no peques más».

[[john-8-12]]
^12^ Jesús les habló otra vez diciendo: «Yo soy la luz del mundo; el que me siga no caminará en la oscuridad, sino que tendrá la luz de la vida».

[[john-8-13]]
^13^ Los fariseos le dijeron: «Tú das testimonio de ti mismo: tu testimonio no vale».

[[john-8-14]]
^14^ Jesús les respondió: «Aunque yo dé testimonio de mí mismo, mi testimonio vale, porque sé de dónde he venido y a dónde voy; pero vosotros no sabéis de dónde vengo ni a dónde voy.

[[john-8-15]]
^15^ Vosotros juzgáis según la carne; yo no juzgo a nadie;

[[john-8-16]]
^16^ y si juzgo, mi juicio es verdadero, porque no estoy yo solo, sino yo y el que me ha enviado.

[[john-8-17]]
^17^ Y en vuestra Ley está escrito que el testimonio de dos personas es válido.

[[john-8-18]]
^18^ Yo soy el que doy testimonio de mí mismo y también el que me ha enviado, el Padre, da testimonio de mí».

[[john-8-19]]
^19^ Entonces le decían: «¿Dónde está tu Padre?» Respondió Jesús: «No me conocéis ni a mí ni a mi Padre; si me conocierais a mí, conoceríais también a mi Padre».

[[john-8-20]]
^20^ Estas palabras las pronunció en el Tesoro, mientras enseñaba en el Templo. Y nadie le prendió, porque aún no había llegado su hora.

[[john-8-21]]
^21^ Jesús les dijo otra vez: «Yo me voy y vosotros me buscaréis, y moriréis en vuestro pecado. Adonde yo voy, vosotros no podéis ir».

[[john-8-22]]
^22^ Los judíos se decían: «¿Es que se va a suicidar, pues dice: “Adonde yo voy, vosotros no podéis ir?»

[[john-8-23]]
^23^ El les decía: «Vosotros sois de abajo, yo soy de arriba. Vosotros sois de este mundo, yo no soy de este mundo.

[[john-8-24]]
^24^ Ya os he dicho que moriréis en vuestros pecados, porque si no creéis que Yo Soy, moriréis en vuestros pecados».

[[john-8-25]]
^25^ Entonces le decían: «¿Quién eres tú?» Jesús les respondió: «Desde el principio, lo que os estoy diciendo.

[[john-8-26]]
^26^ Mucho podría hablar de vosotros y juzgar pero el que me ha enviado es veraz, y lo que le he oído a él es lo que hablo al mundo».

[[john-8-27]]
^27^ No comprendieron que les hablaba del Padre.

[[john-8-28]]
^28^ Les dijo, pues, Jesús: «Cuando hayáis levantado al Hijo del hombre, entonces sabréis que Yo Soy, y que no hago nada por mi propia cuenta; sino que, lo que el Padre me ha enseñado, eso es lo que hablo.

[[john-8-29]]
^29^ Y el que me ha enviado está conmigo: no me ha dejado solo, porque yo hago siempre lo que le agrada a él».

[[john-8-30]]
^30^ Al hablar así, muchos creyeron en él.

[[john-8-31]]
^31^ Decía, pues, Jesús a los judíos que habían creído en él: «Si os mantenéis en mi Palabra, seréis verdaderamente mis discípulos,

[[john-8-32]]
^32^ y conoceréis la verdad y la verdad os hará libres».

[[john-8-33]]
^33^ Ellos le respondieron: «Nosotros somos descendencia de Abraham y nunca hemos sido esclavos de nadie. ¿Cómo dices tú: Os haréis libres?»

[[john-8-34]]
^34^ Jesús les respondió: «En verdad, en verdad os digo: todo el que comete pecado es un esclavo.

[[john-8-35]]
^35^ Y el esclavo no se queda en casa para siempre; mientras el hijo se queda para siempre.

[[john-8-36]]
^36^ Si, pues, el Hijo os da la libertad, seréis realmente libres.

[[john-8-37]]
^37^ Ya sé que sois descendencia de Abraham; pero tratáis de matarme, porque mi Palabra no prende en vosotros.

[[john-8-38]]
^38^ Yo hablo lo que he visto donde mi Padre; y vosotros hacéis lo que habéis oído donde vuestro padre».

[[john-8-39]]
^39^ Ellos le respondieron: «Nuestro padre es Abraham». Jesús les dice: «Si sois hijos de Abraham, haced las obras de Abraham.

[[john-8-40]]
^40^ Pero tratáis de matarme, a mí que os he dicho la verdad que oí de Dios. Eso no lo hizo Abraham.

[[john-8-41]]
^41^ Vosotros hacéis las obras de vuestro padre». Ellos le dijeron: «Nosotros no hemos nacido de la prostitución; no tenemos más padre que a Dios».

[[john-8-42]]
^42^ Jesús les respondió: «Si Dios fuera vuestro Padre, me amaríais a mí, porque yo he salido y vengo de Dios; no he venido por mi cuenta, sino que él me ha enviado.

[[john-8-43]]
^43^ ¿Por qué no reconocéis mi lenguaje? Porque no podéis escuchar mi Palabra.

[[john-8-44]]
^44^ Vosotros sois de vuestro padre el diablo y queréis cumplir los deseos de vuestro padre. Este era homicida desde el principio, y no se mantuvo en la verdad, porque no hay verdad en él; cuando dice la mentira, dice lo que le sale de dentro, porque es mentiroso y padre de la mentira.

[[john-8-45]]
^45^ Pero a mí, como os digo la verdad, no me creéis.

[[john-8-46]]
^46^ ¿Quién de vosotros puede probar que soy pecador? Si digo la verdad, ¿por qué no me creéis?

[[john-8-47]]
^47^ El que es de Dios, escucha las palabras de Dios; vosotros no las escucháis, porque no sois de Dios».

[[john-8-48]]
^48^ Los judíos le respondieron: «¿No decimos, con razón, que eres samaritano y que tienes un demonio?»

[[john-8-49]]
^49^ Respondió Jesús: «Yo no tengo un demonio; sino que honro a mi Padre, y vosotros me deshonráis a mí.

[[john-8-50]]
^50^ Pero yo no busco mi gloria; ya hay quien la busca y juzga.

[[john-8-51]]
^51^ En verdad, en verdad os digo: si alguno guarda mi Palabra, no verá la muerte jamás».

[[john-8-52]]
^52^ Le dijeron los judíos: «Ahora estamos seguros de que tienes un demonio. Abraham murió, y también los profetas; y tú dices: “Si alguno guarda mi Palabra, no probará la muerte jamás.”

[[john-8-53]]
^53^ ¿Eres tú acaso más grande que nuestro padre Abraham, que murió? También los profetas murieron. ¿Por quién te tienes a ti mismo?»

[[john-8-54]]
^54^ Jesús respondió: «Si yo me glorificara a mí mismo, mi gloria no valdría nada; es mi Padre quien me glorifica, de quien vosotros decís: “El es nuestro Dios”,

[[john-8-55]]
^55^ y sin embargo no le conocéis, yo sí que le conozco, y si dijera que no le conozco, sería un mentiroso como vosotros. Pero yo le conozco, y guardo su Palabra.

[[john-8-56]]
^56^ Vuestro padre Abraham se regocijó pensando en ver mi Día; lo vio y se alegró».

[[john-8-57]]
^57^ Entonces los judíos le dijeron: «¿Aún no tienes cincuenta años y has visto a Abraham?»

[[john-8-58]]
^58^ Jesús les respondió: «En verdad, en verdad os digo: antes de que Abraham existiera, Yo Soy».

[[john-8-59]]
^59^ Entonces tomaron piedras para tirárselas; pero Jesús se ocultó y salió del Templo.
[[john-9]]
== Capítulo 9

[[john-9-1]]
^1^ Vio, al pasar, a un hombre ciego de nacimiento.

[[john-9-2]]
^2^ Y le preguntaron sus discípulos: «Rabbí, ¿quién pecó, él o sus padres, para que haya nacido ciego?»

[[john-9-3]]
^3^ Respondió Jesús: «Ni él pecó ni sus padres; es para que se manifiesten en él las obras de Dios.

[[john-9-4]]
^4^ Tenemos que trabajar en las obras del que me ha enviado mientras es de día; llega la noche, cuando nadie puede trabajar.

[[john-9-5]]
^5^ Mientras estoy en el mundo, soy luz del mundo».

[[john-9-6]]
^6^ Dicho esto, escupió en tierra, hizo barro con la saliva, y untó con el barro los ojos del ciego

[[john-9-7]]
^7^ y le dijo: «Vete, lávate en la piscina de Siloé» (que quiere decir Enviado). El fue, se lavó y volvió ya viendo.

[[john-9-8]]
^8^ Los vecinos y los que solían verle antes, pues era mendigo, decían: «¿No es éste el que se sentaba para mendigar?»

[[john-9-9]]
^9^ Unos decían: «Es él». «No, decían otros, sino que es uno que se le parece». Pero él decía: «Soy yo».

[[john-9-10]]
^10^ Le dijeron entonces: «¿Cómo, pues, se te han abierto los ojos?»

[[john-9-11]]
^11^ El respondió: «Ese hombre que se llama Jesús, hizo barro, me untó los ojos y me dijo: “Vete a Siloé y lávate.” Yo fui, me lavé y vi».

[[john-9-12]]
^12^ Ellos le dijeron: «¿Dónde está ése?» El respondió: «No lo sé».

[[john-9-13]]
^13^ Lo llevan donde los fariseos al que antes era ciego.

[[john-9-14]]
^14^ Pero era sábado el día en que Jesús hizo barro y le abrió los ojos.

[[john-9-15]]
^15^ Los fariseos a su vez le preguntaron cómo había recobrado la vista. El les dijo: «Me puso barro sobre los ojos, me lavé y veo».

[[john-9-16]]
^16^ Algunos fariseos decían: «Este hombre no viene de Dios, porque no guarda el sábado». Otros decían: «Pero, ¿cómo puede un pecador realizar semejantes señales?» Y había disensión entre ellos.

[[john-9-17]]
^17^ Entonces le dicen otra vez al ciego: «¿Y tú qué dices de él, ya que te ha abierto los ojos?» El respondió: «Que es un profeta».

[[john-9-18]]
^18^ No creyeron los judíos que aquel hombre hubiera sido ciego, hasta que llamaron a los padres del que había recobrado la vista

[[john-9-19]]
^19^ y les preguntaron: «¿Es éste vuestro hijo, el que decís que nació ciego? ¿Cómo, pues, ve ahora?»

[[john-9-20]]
^20^ Sus padres respondieron: «Nosotros sabemos que este es nuestro hijo y que nació ciego.

[[john-9-21]]
^21^ Pero, cómo ve ahora, no lo sabemos; ni quién le ha abierto los ojos, eso nosotros no lo sabemos. Preguntadle; edad tiene; puede hablar de sí mismo».

[[john-9-22]]
^22^ Sus padres decían esto por miedo por los judíos, pues los judíos se habían puesto ya de acuerdo en que, si alguno le reconocía como Cristo, quedara excluido de la sinagoga.

[[john-9-23]]
^23^ Por eso dijeron sus padres: «Edad tiene; preguntádselo a él».

[[john-9-24]]
^24^ Le llamaron por segunda vez al hombre que había sido ciego y le dijeron: «Da gloria a Dios. Nosotros sabemos que ese hombre es un pecador».

[[john-9-25]]
^25^ Les respondió: «Si es un pecador, no lo sé. Sólo sé una cosa: que era ciego y ahora veo».

[[john-9-26]]
^26^ Le dijeron entonces: «¿Qué hizo contigo? ¿Cómo te abrió los ojos?»

[[john-9-27]]
^27^ El replicó: «Os lo he dicho ya, y no me habéis escuchado. ¿Por qué queréis oírlo otra vez? ¿Es qué queréis también vosotros haceros discípulos suyos?»

[[john-9-28]]
^28^ Ellos le llenaron de injurias y le dijeron: «Tú eres discípulo de ese hombre; nosotros somos discípulos de Moisés.

[[john-9-29]]
^29^ Nosotros sabemos que a Moisés le habló Dios; pero ése no sabemos de dónde es».

[[john-9-30]]
^30^ El hombre les respondió: «Eso es lo extraño: que vosotros no sepáis de dónde es y que me haya abierto a mí los ojos.

[[john-9-31]]
^31^ Sabemos que Dios no escucha a los pecadores; mas, si uno es religioso y cumple su voluntad, a ése le escucha.

[[john-9-32]]
^32^ Jamás se ha oído decir que alguien haya abierto los ojos de un ciego de nacimiento.

[[john-9-33]]
^33^ Si éste no viniera de Dios, no podría hacer nada».

[[john-9-34]]
^34^ Ellos le respondieron: «Has nacido todo entero en pecado ¿y nos da lecciones a nosotros?» Y le echaron fuera.

[[john-9-35]]
^35^ Jesús se enteró de que le habían echado fuera y, encontrándose con él, le dijo: «¿Tú crees en el Hijo del hombre?»

[[john-9-36]]
^36^ El respondió: «¿Y quién es, Señor, para que crea en él?»

[[john-9-37]]
^37^ Jesús le dijo: «Le has visto; el que está hablando contigo, ése es».

[[john-9-38]]
^38^ El entonces dijo: «Creo, Señor». Y se postró ante él.

[[john-9-39]]
^39^ Y dijo Jesús: «Para un juicio he venido a este mundo: para que los que no ven, vean; y los que ven, se vuelvan ciegos».

[[john-9-40]]
^40^ Algunos fariseos que estaban con él oyeron esto y le dijeron: «Es que también nosotros somos ciegos?»

[[john-9-41]]
^41^ Jesús les respondió: Si fuerais ciegos, no tendríais pecado; pero, como decís: “Vemos” vuestro pecado permanece».
[[john-10]]
== Capítulo 10

[[john-10-1]]
^1^ «En verdad, en verdad os digo: el que no entra por la puerta en el redil de las ovejas, sino que escala por otro lado, ése es un ladrón y un salteador;

[[john-10-2]]
^2^ pero el que entra por la puerta es pastor de las ovejas.

[[john-10-3]]
^3^ A éste le abre el portero, y las ovejas escuchan su voz; y a sus ovejas las llama una por una y las saca fuera.

[[john-10-4]]
^4^ Cuando ha sacado todas las suyas, va delante de ellas, y las ovejas le siguen, porque conocen su voz.

[[john-10-5]]
^5^ Pero no seguirán a un extraño, sino que huirán de él, porque no conocen la voz de los extraños».

[[john-10-6]]
^6^ Jesús les dijo esta parábola, pero ellos no comprendieron lo que les hablaba.

[[john-10-7]]
^7^ Entonces Jesús les dijo de nuevo: «En verdad, en verdad os digo: yo soy la puerta de las ovejas.

[[john-10-8]]
^8^ Todos los que han venido delante de mí son ladrones y salteadores; pero las ovejas no les escucharon.

[[john-10-9]]
^9^ Yo soy la puerta; si uno entra por mí, estará a salvo; entrará y saldrá y encontrará pasto.

[[john-10-10]]
^10^ El ladrón no viene más que a robar, matar y destruir. Yo he venido para que tengan vida y la tengan en abundancia.

[[john-10-11]]
^11^ Yo soy el buen pastor. El buen pastor da su vida por las ovejas.

[[john-10-12]]
^12^ Pero el asalariado, que no es pastor, a quien no pertenecen las ovejas, ve venir al lobo, abandona las ovejas y huye, y el lobo hace presa en ellas y las dispersa,

[[john-10-13]]
^13^ porque es asalariado y no le importan nada las ovejas.

[[john-10-14]]
^14^ Yo soy el buen pastor; y conozco mis ovejas y las mías me conocen a mí,

[[john-10-15]]
^15^ como me conoce el Padre y yo conozco a mi Padre y doy mi vida por las ovejas.

[[john-10-16]]
^16^ También tengo otras ovejas, que no son de este redil; también a ésas las tengo que conducir y escucharán mi voz; y habrá un solo rebaño, un solo pastor.

[[john-10-17]]
^17^ Por eso me ama el Padre, porque doy mi vida, para recobrarla de nuevo.

[[john-10-18]]
^18^ Nadie me la quita; yo la doy voluntariamente. Tengo poder para darla y poder para recobrarla de nuevo; esa es la orden que he recibido de mi Padre».

[[john-10-19]]
^19^ Se produjo otra vez una disensión entre los judíos por estas palabras.

[[john-10-20]]
^20^ Muchos de ellos decían: «Tiene un demonio y está loco. ¿Por qué le escucháis?»

[[john-10-21]]
^21^ Pero otros decían: «Esas palabras no son de un endemoniado. ¿Puede acaso un demonio abrir los ojos de los ciegos?»

[[john-10-22]]
^22^ Se celebró por entonces en Jerusalén la fiesta de la Dedicación. Era invierno.

[[john-10-23]]
^23^ Jesús se paseaba por el Templo, en el pórtico de Salomón.

[[john-10-24]]
^24^ Le rodearon los judíos, y le decían: «¿Hasta cuándo vas tenernos en vilo? Si tú eres el Cristo, dínoslo abiertamente».

[[john-10-25]]
^25^ Jesús les respondió: «Ya os lo he dicho, pero no me creéis. Las obras que hago en nombre de mi Padre son las que dan testimonio de mí;

[[john-10-26]]
^26^ pero vosotros no creéis porque no sois de mis ovejas.

[[john-10-27]]
^27^ Mis ovejas escuchan mi voz; yo las conozco y ellas mi siguen.

[[john-10-28]]
^28^ Yo les doy vida eterna y no perecerán jamás, y nadie las arrebatará de mi mano.

[[john-10-29]]
^29^ El Padre, que me las ha dado, es más grande que todos, y nadie puede arrebatar nada de la mano del Padre.

[[john-10-30]]
^30^ Yo y el Padre somos uno».

[[john-10-31]]
^31^ Los judíos trajeron otra vez piedras para apedrearle.

[[john-10-32]]
^32^ Jesús les dijo: «Muchas obras buenas que vienen del Padre os he mostrado. ¿Por cuál de esas obras queréis apedrearme?»

[[john-10-33]]
^33^ Le respondieron los judíos: «No queremos apedrearte por ninguna obra buena, sino por una blasfemia y porque tú, siendo hombre, te haces a ti mismo Dios».

[[john-10-34]]
^34^ Jesús les respondió: «¿No está escrito en vuestra Ley: Yo he dicho: dioses sois?

[[john-10-35]]
^35^ Si llama dioses a aquellos a quienes se dirigió la Palabra de Dios - y no puede fallar la Escritura -

[[john-10-36]]
^36^ a aquel a quien el Padre ha santificado y enviado al mundo, ¿cómo le decís que blasfema por haber dicho: “Yo soy Hijo de Dios”?

[[john-10-37]]
^37^ Si no hago las obras de mi Padre, no me creáis;

[[john-10-38]]
^38^ pero si las hago, aunque a mí no me creáis, creed por las obras, y así sabréis y conoceréis que el Padre está en mí y yo en el Padre».

[[john-10-39]]
^39^ Querían de nuevo prenderle, pero se les escapó de las manos.

[[john-10-40]]
^40^ Se marchó de nuevo al otro lado del Jordán, al lugar donde Juan había estado antes bautizando, y se quedó allí.

[[john-10-41]]
^41^ Muchos fueron donde él y decían: «Juan no realizó ninguna señal, pero todo lo que dijo Juan de éste, era verdad».

[[john-10-42]]
^42^ Y muchos allí creyeron en él.
[[john-11]]
== Capítulo 11

[[john-11-1]]
^1^ Había un cierto enfermo, Lázaro, de Betania, pueblo de María y de su hermana Marta.

[[john-11-2]]
^2^ María era la que ungió al Señor con perfumes y le secó los pies con sus cabellos; su hermano Lázaro era el enfermo.

[[john-11-3]]
^3^ Las hermanas enviaron a decir a Jesús: «Señor, aquel a quien tú quieres, está enfermo».

[[john-11-4]]
^4^ Al oírlo Jesús, dijo: «Esta enfermedad no es de muerte, es para la gloria de Dios, para que el Hijo de Dios sea glorificado por ella».

[[john-11-5]]
^5^ Jesús amaba a Marta, a su hermana y a Lázaro.

[[john-11-6]]
^6^ Cuando se enteró de que estaba enfermo, permaneció dos días más en el lugar donde se encontraba.

[[john-11-7]]
^7^ Al cabo de ellos, dice a sus discípulos: «Volvamos de nuevo a Judea».

[[john-11-8]]
^8^ Le dicen los discípulos: «Rabbí, con que hace poco los judíos querían apedrearte, ¿y vuelves allí?»

[[john-11-9]]
^9^ Jesús respondió: «¿No son doce las horas del día? Si uno anda de día, no tropieza, porque ve la luz de este mundo;

[[john-11-10]]
^10^ pero si uno anda de noche, tropieza, porque no está la luz en él».

[[john-11-11]]
^11^ Dijo esto y añadió: «Nuestro amigo Lázaro duerme; pero voy a despertarle».

[[john-11-12]]
^12^ Le dijeron sus discípulos: «Señor, si duerme, se curará».

[[john-11-13]]
^13^ Jesús lo había dicho de su muerte, pero ellos creyeron que hablaba del descanso del sueño.

[[john-11-14]]
^14^ Entonces Jesús les dijo abiertamente: «Lázaro ha muerto,

[[john-11-15]]
^15^ y me alegro por vosotros de no haber estado allí, para que creáis. Pero vayamos donde él».

[[john-11-16]]
^16^ Entonces Tomás, llamado el Mellizo, dijo a los otros discípulos: «Vayamos también nosotros a morir con él».

[[john-11-17]]
^17^ Cuando llegó Jesús, se encontró con que Lázaro llevaba ya cuatro días en el sepulcro.

[[john-11-18]]
^18^ Betania estaba cerca de Jerusalén como a unos quince estadios,

[[john-11-19]]
^19^ y muchos judíos habían venido a casa de Marta y María para consolarlas por su hermano.

[[john-11-20]]
^20^ Cuando Marta supo que había venido Jesús, le salió al encuentro, mientras María permanecía en casa.

[[john-11-21]]
^21^ Dijo Marta a Jesús: «Señor, si hubieras estado aquí, no habría muerto mi hermano.

[[john-11-22]]
^22^ Pero aun ahora yo sé que cuanto pidas a Dios, Dios te lo concederá».

[[john-11-23]]
^23^ Le dice Jesús: «Tu hermano resucitará».

[[john-11-24]]
^24^ Le respondió Marta: «Ya sé que resucitará en la resurrección, el último día».

[[john-11-25]]
^25^ Jesús le respondió: «Yo soy la resurrección El que cree en mí, aunque muera, vivirá;

[[john-11-26]]
^26^ y todo el que vive y cree en mí, no morirá jamás. ¿Crees esto?»

[[john-11-27]]
^27^ Le dice ella: «Sí, Señor, yo creo que tú eres el Cristo, el Hijo de Dios, el que iba a venir al mundo».

[[john-11-28]]
^28^ Dicho esto, fue a llamar a su hermana María y le dijo al oído: «El Maestro está ahí y te llama».

[[john-11-29]]
^29^ Ella, en cuanto lo oyó, se levantó rapidamente, y se fue donde él.

[[john-11-30]]
^30^ Jesús todavía no había llegado al pueblo; sino que seguía en el lugar donde Marta lo había encontrado.

[[john-11-31]]
^31^ Los judíos que estaban con María en casa consolándola, al ver que se levantaba rápidamente y salía, la siguieron pensando que iba al sepulcro para llorar allí.

[[john-11-32]]
^32^ Cuando María llegó donde estaba Jesús, al verle, cayó a sus pies y le dijo: «Señor, si hubieras estado aquí, mi hermano no habría muerto».

[[john-11-33]]
^33^ Viéndola llorar Jesús y que también lloraban los judíos que la acompañaban, se conmovió interiormente, se turbó

[[john-11-34]]
^34^ y dijo: «¿Dónde lo habéis puesto?» Le responden: «Señor, ven y lo verás».

[[john-11-35]]
^35^ Jesús se echó a llorar.

[[john-11-36]]
^36^ Los judíos entonces decían: «Mirad cómo le quería».

[[john-11-37]]
^37^ Pero algunos de ellos dijeron: «Este, que abrió los ojos del ciego, ¿no podía haber hecho que éste no muriera?»

[[john-11-38]]
^38^ Entonces Jesús se conmovió de nuevo en su interior y fue al sepulcro. Era una cueva, y tenía puesta encima una piedra.

[[john-11-39]]
^39^ Dice Jesús: «Quitad la piedra». Le responde Marta, la hermana del muerto: «Señor, ya huele; es el cuarto día».

[[john-11-40]]
^40^ Le dice Jesús: «¿No te he dicho que, si crees, verás la gloria de Dios?»

[[john-11-41]]
^41^ Quitaron, pues, la piedra. Entonces Jesús levantó los ojos a lo alto y dijo: «Padre, te doy gracias por haberme escuchado.

[[john-11-42]]
^42^ Ya sabía yo que tú siempre me escuchas; pero lo he dicho por estos que me rodean, para que crean que tú me has enviado».

[[john-11-43]]
^43^ Dicho esto, gritó con fuerte voz: «¡Lázaro, sal fuera!»

[[john-11-44]]
^44^ Y salió el muerto, atado de pies y manos con vendas y envuelto el rostro en un sudario. Jesús les dice: «Desatadlo y dejadle andar».

[[john-11-45]]
^45^ Muchos de los judíos que habían venido a casa de María, viendo lo que había hecho, creyeron en él.

[[john-11-46]]
^46^ Pero algunos de ellos fueron donde los fariseos y les contaron lo que había hecho Jesús.

[[john-11-47]]
^47^ Entonces los sumos sacerdotes y los fariseos convocaron consejo y decían: «¿Qué hacemos? Porque este hombre realiza muchas señales.

[[john-11-48]]
^48^ Si le dejamos que siga así, todos creerán en él y vendrán los romanos y destruirán nuestro Lugar Santo y nuestra nación».

[[john-11-49]]
^49^ Pero uno de ellos, Caifás, que era el Sumo Sacerdote de aquel año, les dijo: «Vosotros no sabéis nada,

[[john-11-50]]
^50^ ni caéis en la cuenta que os conviene que muera uno solo por el pueblo y no perezca toda la nación».

[[john-11-51]]
^51^ Esto no lo dijo por su propia cuenta, sino que, como era Sumo Sacerdote aquel año, profetizó que Jesús iba a morir por la nación

[[john-11-52]]
^52^ - y no sólo por la nación, sino también para reunir en uno a los hijos de Dios que estaban dispersos.

[[john-11-53]]
^53^ Desde este día, decidieron darle muerte.

[[john-11-54]]
^54^ Por eso Jesús no andaba ya en público entre los judíos, sino que se retiró de allí a la región cercana al desierto, a una ciudada llamada Efraím, y allí residía con sus discípulos.

[[john-11-55]]
^55^ Estaba cerca la Pascua de los judíos, y muchos del país habían subido a Jerusalén, antes de la Pascua para purificarse.

[[john-11-56]]
^56^ Buscaban a Jesús y se decían unos a otros estando en el Templo: «¿Qué os parece? ¿Que no vendrá a la fiesta?»

[[john-11-57]]
^57^ Los sumos sacerdotes y los fariseos habían dado órdenes de que, si alguno sabía dónde estaba, lo notificara para detenerle.
[[john-12]]
== Capítulo 12

[[john-12-1]]
^1^ Seis días antes de la Pascua, Jesús se fue a Betania, donde estaba Lázaro, a quien Jesús había resucitado de entre los muertos.

[[john-12-2]]
^2^ Le dieron allí una cena. Marta servía y Lázaro era uno de los que estaban con él a la mesa.

[[john-12-3]]
^3^ Entonces María, tomando una libra de perfume de nardo puro, muy caro, ungió los pies de Jesús y los secó con sus cabellos. Y la casa se llenó del olor del perfume.

[[john-12-4]]
^4^ Dice Judas Iscariote, uno de los discípulos, el que lo había de entregar:

[[john-12-5]]
^5^ «¿Por qué no se ha vendido este perfume por trescientos denarios y se ha dado a los pobres?»

[[john-12-6]]
^6^ Pero no decía esto porque le preocuparan los pobres, sino porque era ladrón, y como tenía la bolsa, se llevaba lo que echaban en ella.

[[john-12-7]]
^7^ Jesús dijo: «Déjala, que lo guarde para el día de mi sepultura.

[[john-12-8]]
^8^ Porque pobres siempre tendréis con vosotros; pero a mí no siempre tendréis».

[[john-12-9]]
^9^ Gran número de judíos supieron que Jesús estaba allí y fueron, no sólo por Jesús, sino también por ver a Lázaro, a quien había resucitado de entre los muertos.

[[john-12-10]]
^10^ Los sumos sacerdotes decidieron dar muerte también a Lázaro,

[[john-12-11]]
^11^ porque a causa de él muchos judíos se les iban y creían en Jesús.

[[john-12-12]]
^12^ Al día siguiente, al enterarse la numerosa muchedumbre que había llegado para la fiesta, de que Jesús se dirigía a Jerusalén,

[[john-12-13]]
^13^ tomaron ramas de palmera y salieron a su encuentro gritando: «¡ Hosanna! ¡Bendito el que viene en nombre del Señor, y el Rey de Israel!»

[[john-12-14]]
^14^ Jesús, habiendo encontrado un borriquillo, se montó en él, según está escrito:

[[john-12-15]]
^15^ No temas, hija de Sión; mira que viene tu Rey montado en un pollino de asna.

[[john-12-16]]
^16^ Esto no lo comprendieron sus discípulos de momento; pero cuando Jesús fue glorificado, cayeron en la cuenta de que esto estaba escrito sobre él, y que era lo que le habían hecho.

[[john-12-17]]
^17^ La gente que estaba con él cuando llamó a Lázaro de la tumba y le resucitó de entre los muertos, daba testimonio.

[[john-12-18]]
^18^ Por eso también salió la gente a su encuentro, porque habían oído que él había realizado aquella señal.

[[john-12-19]]
^19^ Entonces los fariseos se dijeron entre sí: «¿Veis cómo no adelantáis nada?, todo el mundo se ha ido tras él».

[[john-12-20]]
^20^ Había algunos griegos de los que subían a adorar en la fiesta.

[[john-12-21]]
^21^ Estos se dirigieron a Felipe, el de Betsaida de Galilea, y le rogaron: «Señor, queremos ver a Jesús».

[[john-12-22]]
^22^ Felipe fue a decírselo a Andrés; Andrés y Felipe fueron a decírselo a Jesús.

[[john-12-23]]
^23^ Jesús les respondió: «Ha llegado la hora de que sea glorificado el Hijo de hombre.

[[john-12-24]]
^24^ En verdad, en verdad os digo: si el grano de trigo no cae en tierra y muere, queda él solo; pero si muere, da mucho fruto.

[[john-12-25]]
^25^ El que ama su vida, la pierde; y el que odia su vida en este mundo, la guardará para una vida eterna.

[[john-12-26]]
^26^ Si alguno me sirve, que me siga, y donde yo esté, allí estará también mi servidor. Si alguno me sirve, el Padre le honrará.

[[john-12-27]]
^27^ Ahora mi alma está turbada. Y ¿que voy a decir? ¡Padre, líbrame de esta hora! Pero ¡si he llegado a esta hora para esto!

[[john-12-28]]
^28^ Padre, glorifica tu Nombre». Vino entonces una voz del cielo: «Le he glorificado y de nuevo le glorificaré».

[[john-12-29]]
^29^ La gente que estaba allí y lo oyó decía que había sido un trueno. Otros decían: «Le ha hablado un ángel».

[[john-12-30]]
^30^ Jesús respondió: «No ha venido esta voz por mí, sino por vosotros.

[[john-12-31]]
^31^ Ahora es el juicio de este mundo; ahora el Príncipe de este mundo será echado fuera.

[[john-12-32]]
^32^ Y yo cuando sea levando de la tierra, atraeré a todos hacia mí».

[[john-12-33]]
^33^ Decía esto para significar de qué muerte iba a morir.

[[john-12-34]]
^34^ La gente le respondió: «Nosotros sabemos por la Ley que el Cristo permanece para siempre. ¿Cómo dices tú que es preciso que el Hijo del hombre sea levantado? ¿Quién es ese Hijo del hombre?»

[[john-12-35]]
^35^ Jesús les dijo: «Todavía, por un poco de tiempo, está la luz entre vosotros. Caminad mientras tenéis la luz, para que no os sorprendan las tinieblas; el que camina en tinieblas, no sabe a dónde va.

[[john-12-36]]
^36^ Mientras tenéis la luz, creed en la luz, para que seáis hijos de luz». Dicho esto, se marchó Jesús y se ocultó de ellos.

[[john-12-37]]
^37^ Aunque había realizado tan grandes señales delante de ellos, no creían en él;

[[john-12-38]]
^38^ para que se cumpliera el oráculo pronunciado por el profeta Isaías: Señor, ¿quién dio crédito a nuestras palabras? Y el brazo del Señor, ¿a quién se le reveló?

[[john-12-39]]
^39^ No podían creer, porque también había dicho Isaías:

[[john-12-40]]
^40^ Ha cegado sus ojos, ha endurecido su corazón; para que no vean con los ojos, ni comprendan con su corazón, ni se conviertan, ni yo los sane.

[[john-12-41]]
^41^ Isaías dijo esto porque vio su gloria y habló de él.

[[john-12-42]]
^42^ Sin embargo, aun entre los magistrados, muchos creyeron en él; pero, por los fariseos, no lo confesaban, para no ser excluidos de la sinagoga,

[[john-12-43]]
^43^ porque prefirieron la gloria de los hombres a la gloria de Dios.

[[john-12-44]]
^44^ Jesús gritó y dijo: «El que cree en mí, no cree en mí, sino en aquel que me ha enviado;

[[john-12-45]]
^45^ y el que me ve a mí, ve a aquel que me ha enviado.

[[john-12-46]]
^46^ Yo, la luz, he venido al mundo para que todo el que crea en mí no siga en las tinieblas.

[[john-12-47]]
^47^ Si alguno oye mis palabras y no las guarda, yo no le juzgo, porque no he venido para juzgar al mundo, sino para salvar al mundo.

[[john-12-48]]
^48^ El que me rechaza y no recibe mis palabras, ya tiene quien le juzgue: la Palabra que yo he hablado, ésa le juzgará el último día;

[[john-12-49]]
^49^ porque yo no he hablado por mi cuenta, sino que el Padre que me ha enviado me ha mandado lo que tengo que decir y hablar,

[[john-12-50]]
^50^ y yo sé que su mandato es vida eterna. Por eso, lo que yo hablo lo hablo como el Padre me lo ha dicho a mí».
[[john-13]]
== Capítulo 13

[[john-13-1]]
^1^ Antes de la fiesta de la Pascua, sabiendo Jesús que había llegado su hora de pasar de este mundo al Padre, habiendo amado a los suyos que estaban en el mundo, los amó hasta el extremo.

[[john-13-2]]
^2^ Durante la cena, cuando ya el diablo había puesto en el corazón a Judas Iscariote, hijo de Simón, el propósito de entregarle,

[[john-13-3]]
^3^ sabiendo que el Padre le había puesto todo en sus manos y que había salido de Dios y a Dios volvía,

[[john-13-4]]
^4^ se levanta de la mesa, se quita sus vestidos y, tomando una toalla, se la ciñó.

[[john-13-5]]
^5^ Luego echa agua en un lebrillo y se puso a lavar los pies de los discípulos y a secárselos con la toalla con que estaba ceñido.

[[john-13-6]]
^6^ Llega a Simón Pedro; éste le dice: «Señor, ¿tú lavarme a mí los pies?»

[[john-13-7]]
^7^ Jesús le respondió: «Lo que yo hago, tú no lo entiendes ahora: lo comprenderás más tarde».

[[john-13-8]]
^8^ Le dice Pedro: «No me lavarás los pies jamás». Jesús le respondió: «Si no te lavo, no tienes parte conmigo».

[[john-13-9]]
^9^ Le dice Simón Pedro: «Señor, no sólo los pies, sino hasta las manos y la cabeza».

[[john-13-10]]
^10^ Jesús le dice: «El que se ha bañado, no necesita lavarse; está del todo limpio. Y vosotros estáis limpios, aunque no todos».

[[john-13-11]]
^11^ Sabía quién le iba a entregar, y por eso dijo: «No estáis limpios todos».

[[john-13-12]]
^12^ Después que les lavó los pies, tomó sus vestidos, volvió a la mesa, y les dijo: «¿Comprendéis lo que he hecho con vosotros?

[[john-13-13]]
^13^ Vosotros me llamáis “el Maestro” y “el Señor”, y decís bien, porque lo soy.

[[john-13-14]]
^14^ Pues si yo, el Señor y el Maestro, os he lavado los pies, vosotros también debéis lavaros los pies unos a otros.

[[john-13-15]]
^15^ Porque os he dado ejemplo, para que también vosotros hagáis como yo he hecho con vosotros.

[[john-13-16]]
^16^ «En verdad, en verdad os digo: no es más el siervo que su amo, ni el enviado más que el que le envía.

[[john-13-17]]
^17^ «Sabiendo esto, dichosos seréis si lo cumplís.

[[john-13-18]]
^18^ No me refiero a todos vosotros; yo conozco a los que he elegido; pero tiene que cumplirse la Escritura: El que come mi pan ha alzado contra mí su talón.

[[john-13-19]]
^19^ «Os lo digo desde ahora, antes de que suceda, para que, cuando suceda, creáis que Yo Soy.

[[john-13-20]]
^20^ En verdad, en verdad os digo: quien acoja al que yo envíe me acoge a mí, y quien me acoja a mí, acoge a Aquel que me ha enviado».

[[john-13-21]]
^21^ Cuando dijo estas palabras, Jesús se turbó en su interior y declaró: «En verdad, en verdad os digo que uno de vosotros me entregará».

[[john-13-22]]
^22^ Los discípulos se miraban unos a otros, sin saber de quién hablaba.

[[john-13-23]]
^23^ Uno de sus discípulos, el que Jesús amaba, estaba a la mesa al lado de Jesús.

[[john-13-24]]
^24^ Simón Pedro le hace una seña y le dice: «Pregúntale de quién está hablando».

[[john-13-25]]
^25^ El, recostándose sobre el pecho de Jesús, le dice: «Señor, ¿quién es?»

[[john-13-26]]
^26^ Le responde Jesús: «Es aquel a quien dé el bocado que voy a mojar». Y, mojando el bocado, le toma y se lo da a Judas, hijo de Simón Iscariote.

[[john-13-27]]
^27^ Y entonces, tras el bocado, entró en él Satanás. Jesús le dice: «Lo que vas a hacer, hazlo pronto».

[[john-13-28]]
^28^ Pero ninguno de los comensales entendió por qué se lo decía.

[[john-13-29]]
^29^ Como Judas tenía la bolsa, algunos pensaban que Jesús quería decirle: «Compra lo que nos hace falta para la fiesta», o que diera algo a los pobres.

[[john-13-30]]
^30^ En cuanto tomó Judas el bocado, salió. Era de noche.

[[john-13-31]]
^31^ Cuando salió, dice Jesús: «Ahora ha sido glorificado el Hijo del hombre y Dios ha sido glorificado en él.

[[john-13-32]]
^32^ Si Dios ha sido glorificado en él, Dios también le glorificará en sí mismo y le glorificará pronto».

[[john-13-33]]
^33^ «Hijos míos, ya poco tiempo voy a estar con vosotros. Vosotros me buscaréis, y, lo mismo que les dije a los judíos, que adonde yo voy, vosotros no podéis venir, os digo también ahora a vosotros.

[[john-13-34]]
^34^ Os doy un mandamiento nuevo: que os améis los unos a los otros. Que, como yo os he amado, así os améis también vosotros los unos a los otros.

[[john-13-35]]
^35^ En esto conocerán todos que sois discípulos míos: si os tenéis amor los unos a los otros».

[[john-13-36]]
^36^ Simón Pedro le dice: «Señor, ¿a dónde vas?» Jesús le respondió: «Adonde yo voy no puedes seguirme ahora; me seguirás más tarde».

[[john-13-37]]
^37^ Pedro le dice: «¿Por qué no puedo seguirte ahora? Yo daré mi vida por ti».

[[john-13-38]]
^38^ Le responde Jesús: «¿Que darás tu vida por mí? En verdad, en verdad te digo: no cantará el gallo antes que tú me hayas negado tres veces».
[[john-14]]
== Capítulo 14

[[john-14-1]]
^1^ «No se turbe vuestro corazón. Creéis en Dios: creed también en mí.

[[john-14-2]]
^2^ En la casa de mi Padre hay muchas mansiones; si no, os lo habría dicho; porque voy a prepararos un lugar.

[[john-14-3]]
^3^ Y cuando haya ido y os haya preparado un lugar, volveré y os tomaré conmigo, para que donde esté yo estéis también vosotros.

[[john-14-4]]
^4^ Y adonde yo voy sabéis el camino».

[[john-14-5]]
^5^ Le dice Tomás: «Señor, no sabemos a dónde vas, ¿cómo podemos saber el camino?»

[[john-14-6]]
^6^ Le dice Jesús: «Yo soy el Camino, la Verdad y la Vida. Nadie va al Padre sino por mí.

[[john-14-7]]
^7^ Si me conocéis a mí, conoceréis también a mi Padre; desde ahora lo conocéis y lo habéis visto».

[[john-14-8]]
^8^ Le dice Felipe: «Señor, muéstranos al Padre y nos basta».

[[john-14-9]]
^9^ Le dice Jesús: «¿Tanto tiempo hace que estoy con vosotros y no me conoces Felipe? El que me ha visto a mí, ha visto al Padre. ¿Cómo dices tú: “Muéstranos al Padre”?

[[john-14-10]]
^10^ ¿No crees que yo estoy en el Padre y el Padre está en mí? Las palabras que os digo, no las digo por mi cuenta; el Padre que permanece en mí es el que realiza las obras.

[[john-14-11]]
^11^ Creedme: yo estoy en el Padre y el Padre está en mí. Al menos, creedlo por las obras.

[[john-14-12]]
^12^ En verdad, en verdad os digo: el que crea en mí, hará él también las obras que yo hago, y hará mayores aún, porque yo voy al Padre.

[[john-14-13]]
^13^ Y todo lo que pidáis en mi nombre, yo lo haré, para que el Padre sea glorificado en el Hijo.

[[john-14-14]]
^14^ Si me pedís algo en mi nombre, yo lo haré.

[[john-14-15]]
^15^ Si me amáis, guardaréis mis mandamientos;

[[john-14-16]]
^16^ y yo pediré al Padre y os dará otro Paráclito, para que esté con vosotros para siempre,

[[john-14-17]]
^17^ el Espíritu de la verdad, a quien el mundo no puede recibir, porque no le ve ni le conoce. Pero vosotros le conocéis, porque mora con vosotros.

[[john-14-18]]
^18^ No os dejaré huérfanos: volveré a vosotros.

[[john-14-19]]
^19^ Dentro de poco el mundo ya no me verá, pero vosotros si me veréis, porque yo vivo y también vosotros viviréis.

[[john-14-20]]
^20^ Aquel día comprenderéis que yo estoy en mi Padre y vosotros en mí y yo en vosotros.

[[john-14-21]]
^21^ El que tiene mis mandamientos y los guarda, ése es el que me ama; y el que me ame, será amado de mi Padre; y yo le amaré y me manifestaré a él».

[[john-14-22]]
^22^ Le dice Judas - no el Iscariote -: «Señor, ¿qué pasa para que te vayas a manifestar a nosotros y no al mundo?»

[[john-14-23]]
^23^ Jesús le respondió: «Si alguno me ama, guardará mi Palabra, y mi Padre le amará, y vendremos a él, y haremos morada en él.

[[john-14-24]]
^24^ El que no me ama no guarda mis palabras. Y la palabra que escucháis no es mía, sino del Padre que me ha enviado.

[[john-14-25]]
^25^ Os he dicho estas cosas estando entre vosotros.

[[john-14-26]]
^26^ Pero el Paráclito, el Espíritu Santo, que el Padre enviará en mi nombre, os lo enseñará todo y os recordará todo lo que yo os he dicho.

[[john-14-27]]
^27^ Os dejo la paz, mi paz os doy; no os la doy como la da el mundo. No se turbe vuestro corazón ni se acobarde.

[[john-14-28]]
^28^ Habéis oído que os he dicho: “Me voy y volveré a vosotros.” Si me amarais, os alegraríais de que me fuera al Padre, porque el Padre es más grande que yo.

[[john-14-29]]
^29^ Y os lo digo ahora, antes de que suceda, para que cuando suceda creáis.

[[john-14-30]]
^30^ Ya no hablaré muchas cosas con vosotros, porque llega el Príncipe de este mundo. En mí no tiene ningún poder;

[[john-14-31]]
^31^ pero ha de saber el mundo que amo al Padre y que obro según el Padre me ha ordenado. Levantaos. Vámonos de aquí».
[[john-15]]
== Capítulo 15

[[john-15-1]]
^1^ «Yo soy la vid verdadera, y mi Padre es el viñador.

[[john-15-2]]
^2^ Todo sarmiento que en mí no da fruto, lo corta, y todo el que da fruto, lo limpia, para que dé más fruto.

[[john-15-3]]
^3^ Vosotros estáis ya limpios gracias a la Palabra que os he anunciado.

[[john-15-4]]
^4^ Permaneced en mí, como yo en vosotros. Lo mismo que el sarmiento no puede dar fruto por sí mismo, si no permanece en la vid; así tampoco vosotros si no permanecéis en mí.

[[john-15-5]]
^5^ Yo soy la vid; vosotros los sarmientos. El que permanece en mí y yo en él, ése da mucho fruto; porque separados de mí no podéis hacer nada.

[[john-15-6]]
^6^ Si alguno no permanece en mí, es arrojado fuera, como el sarmiento, y se seca; luego los recogen, los echan al fuego y arden.

[[john-15-7]]
^7^ Si permanecéis en mí, y mis palabras permanecen en vosotros, pedid lo que queráis y lo conseguiréis.

[[john-15-8]]
^8^ La gloria de mi Padre está en que deis mucho fruto, y seáis mis discípulos.

[[john-15-9]]
^9^ Como el Padre me amó, yo también os he amado a vosotros; permaneced en mi amor.

[[john-15-10]]
^10^ Si guardáis mis mandamientos, permaneceréis en mi amor, como yo he guardado los mandamientos de mi Padre, y permanezco en su amor.

[[john-15-11]]
^11^ Os he dicho esto, para que mi gozo esté en vosotros, y vuestro gozo sea colmado.

[[john-15-12]]
^12^ Este es el mandamiento mío: que os améis los unos a los otros como yo os he amado.

[[john-15-13]]
^13^ Nadie tiene mayor amor que el que da su vida por sus amigos.

[[john-15-14]]
^14^ Vosotros sois mis amigos, si hacéis lo que yo os mando.

[[john-15-15]]
^15^ No os llamo ya siervos, porque el siervo no sabe lo que hace su amo; a vosotros os he llamado amigos, porque todo lo que he oído a mi Padre os lo he dado a conocer.

[[john-15-16]]
^16^ No me habéis elegido vosotros a mí, sino que yo os he elegido a vosotros, y os he destinado para que vayáis y deis fruto, y que vuestro fruto permanezca; de modo que todo lo que pidáis al Padre en mi nombre os lo conceda.

[[john-15-17]]
^17^ Lo que os mando es que os améis los unos a los otros».

[[john-15-18]]
^18^ «Si el mundo os odia, sabed que a mí me ha odiado antes que a vosotros.

[[john-15-19]]
^19^ Su fuerais del mundo, el mundo amaría lo suyo; pero, como no sois del mundo, porque yo al elegiros os he sacado del mundo, por eso os odia el mundo.

[[john-15-20]]
^20^ Acordaos de la palabra que os he dicho: El siervo no es más que su señor. Si a mí me han perseguido, también os perseguirán a vosotros; si han guardado mi Palabra, también la vuestra guardarán.

[[john-15-21]]
^21^ Pero todo esto os lo harán por causa de mi nombre, porque no conocen al que me ha enviado.

[[john-15-22]]
^22^ Si yo no hubiera venido y no les hubiera hablado, no tendrían pecado; pero ahora no tienen excusa de su pecado.

[[john-15-23]]
^23^ El que me odia, odia también a mi Padre.

[[john-15-24]]
^24^ Si no hubiera hecho entre ellos obras que no ha hecho ningún otro, no tendrían pecado; pero ahora las han visto, y nos odian a mí y a mi Padre.

[[john-15-25]]
^25^ Pero es para que se cumpla lo que está escrito en su Ley: Me han odiado sin motivo.

[[john-15-26]]
^26^ Cuando venga el Paráclito, que yo os enviaré de junto al Padre, el Espíritu de la verdad, que procede del Padre, él dará testimonio de mí.

[[john-15-27]]
^27^ Pero también vosotros daréis testimonio, porque estáis conmigo desde el principio.
[[john-16]]
== Capítulo 16

[[john-16-1]]
^1^ Os he dicho esto para que no os escandalicéis.

[[john-16-2]]
^2^ Os expulsarán de las sinagogas. E incluso llegará la hora en que todo el que os mate piense que da culto a Dios.

[[john-16-3]]
^3^ Y esto lo harán porque no han conocido ni al Padre ni a mí.

[[john-16-4]]
^4^ Os he dicho esto para que, cuando llegue la hora, os acordéis de que ya os lo había dicho. «No os dije esto desde el principio porque estaba yo con vosotros.

[[john-16-5]]
^5^ Pero ahora me voy a Aquel que me ha enviado, y ninguno de vosotros me pregunta: “¿Dónde vas?”

[[john-16-6]]
^6^ Sino que por haberos dicho esto vuestros corazones se han llenado de tristeza.

[[john-16-7]]
^7^ Pero yo os digo la verdad: Os conviene que yo me vaya; porque si no me voy, no vendrá a vosotros el Paráclito; pero si me voy, os lo enviaré:

[[john-16-8]]
^8^ y cuando él venga, convencerá al mundo en lo referente al pecado, en lo referente a la justicia y en lo referente al juicio;

[[john-16-9]]
^9^ en lo referente al pecado, porque no creen en mí;

[[john-16-10]]
^10^ en lo referente a la justicia porque me voy al Padre, y ya no me veréis;

[[john-16-11]]
^11^ en lo referente al juicio, porque el Príncipe de este mundo está juzgado.

[[john-16-12]]
^12^ Mucho tengo todavía que deciros, pero ahora no podéis con ello.

[[john-16-13]]
^13^ Cuando venga él, el Espíritu de la verdad, os guiará hasta la verdad completa; pues no hablará por su cuenta, sino que hablará lo que oiga, y os anunciará lo que ha de venir.

[[john-16-14]]
^14^ El me dará gloria, porque recibirá de lo mío y os lo anunciará a vosotros.

[[john-16-15]]
^15^ Todo lo que tiene el Padre es mío. Por eso he dicho: Recibirá de lo mío y os lo anunciará a vosotros.

[[john-16-16]]
^16^ «Dentro de poco ya no me veréis, y dentro de otro poco me volveréis a ver».

[[john-16-17]]
^17^ Entonces algunos de sus discípulos comentaron entre sí: «¿Qué es eso que nos dice: “Dentro de poco ya no me veréis y dentro de otro poco me volveréis a ver” y “Me voy al Padre”?»

[[john-16-18]]
^18^ Y decían: «¿Qué es ese “poco”? No sabemos lo que quiere decir».

[[john-16-19]]
^19^ Se dio cuenta Jesús de que querían preguntarle y les dijo: «¿Andáis preguntándoos acerca de lo que he dicho: “Dentro de poco no me veréis y dentro de otro poco me volveréis a ver?”

[[john-16-20]]
^20^ «En verdad, en verdad os digo que lloraréis y os lamentaréis, y el mundo se alegrará. Estaréis tristes, pero vuestra tristeza se convertirá en gozo.

[[john-16-21]]
^21^ La mujer, cuando va a dar a luz, está triste, porque le ha llegado su hora; pero cuando ha dado a luz al niño, ya no se acuerda del aprieto por el gozo de que ha nacido un hombre en el mundo.

[[john-16-22]]
^22^ También vosotros estáis tristes ahora, pero volveré a veros y se alegrará vuestro corazón y vuestra alegría nadie os la podrá quitar.

[[john-16-23]]
^23^ Aquel día no me preguntaréis nada. En verdad, en verdad os digo: lo que pidáis al Padre os lo dará en mi nombre.

[[john-16-24]]
^24^ Hasta ahora nada le habéis pedido en mi nombre. Pedid y recibiréis, para que vuestro gozo sea colmado.

[[john-16-25]]
^25^ Os he dicho todo esto en parábolas. Se acerca la hora en que ya no os hablaré en parábolas, sino que con toda claridad os hablaré acerca del Padre.

[[john-16-26]]
^26^ Aquel día pediréis en mi nombre y no os digo que yo rogaré al Padre por vosotros,

[[john-16-27]]
^27^ pues el Padre mismo os quiere, porque me queréis a mí y creéis que salí de Dios.

[[john-16-28]]
^28^ Salí del Padre y he venido al mundo. Ahora dejo otra vez el mundo y voy al Padre».

[[john-16-29]]
^29^ Le dicen sus discípulos: «Ahora sí que hablas claro, y no dices ninguna parábola.

[[john-16-30]]
^30^ Sabemos ahora que lo sabes todo y no necesitas que nadie te pregunte. Por esto creemos que has salido de Dios».

[[john-16-31]]
^31^ Jesús les respondió: «¿Ahora creéis?

[[john-16-32]]
^32^ Mirad que llega la hora (y ha llegado ya) en que os dispersaréis cada uno por vuestro lado y me dejaréis solo. Pero no estoy solo, porque el Padre está conmigo.

[[john-16-33]]
^33^ Os he dicho estas cosas para que tengáis paz en mí. En el mundo tendréis tribulación. Pero ¡ánimo!: yo he vencido al mundo».
[[john-17]]
== Capítulo 17

[[john-17-1]]
^1^ Así habló Jesús, y alzando los ojos al cielo, dijo: «Padre, ha llegado la hora; glorifica a tu Hijo, para que tu Hijo te glorifique a ti.

[[john-17-2]]
^2^ Y que según el poder que le has dado sobre toda carne, dé también vida eterna a todos los que tú le has dado.

[[john-17-3]]
^3^ Esta es la vida eterna: que te conozcan a ti, el único Dios verdadero, y al que tú has enviado, Jesucristo.

[[john-17-4]]
^4^ Yo te he glorificado en la tierra, llevando a cabo la obra que me encomendaste realizar.

[[john-17-5]]
^5^ Ahora, Padre, glorifícame tú, junto a ti, con la gloria que tenía a tu lado antes que el mundo fuese.

[[john-17-6]]
^6^ He manifestado tu Nombre a los hombres que tú me has dado tomándolos del mundo. Tuyos eran y tú me los has dado; y han guardado tu Palabra.

[[john-17-7]]
^7^ Ahora ya saben que todo lo que me has dado viene de ti;

[[john-17-8]]
^8^ porque las palabras que tú me diste se las he dado a ellos, y ellos las han aceptado y han reconocido verdaderamente que vengo de ti, y han creído que tú me has enviado.

[[john-17-9]]
^9^ Por ellos ruego; no ruego por el mundo, sino por los que tú me has dado, porque son tuyos;

[[john-17-10]]
^10^ y todo lo mío es tuyo y todo lo tuyo es mío; y yo he sido glorificado en ellos.

[[john-17-11]]
^11^ Yo ya no estoy en el mundo, pero ellos sí están en el mundo, y yo voy a ti. Padre santo, cuida en tu nombre a los que me has dado, para que sean uno como nosotros.

[[john-17-12]]
^12^ Cuando estaba yo con ellos, yo cuidaba en tu nombre a los que me habías dado. He velado por ellos y ninguno se ha perdido, salvo el hijo de perdición, para que se cumpliera la Escritura.

[[john-17-13]]
^13^ Pero ahora voy a ti, y digo estas cosas en el mundo para que tengan en sí mismos mi alegría colmada.

[[john-17-14]]
^14^ Yo les he dado tu Palabra, y el mundo los ha odiado, porque no son del mundo, como yo no soy del mundo.

[[john-17-15]]
^15^ No te pido que los retires del mundo, sino que los guardes del Maligno.

[[john-17-16]]
^16^ Ellos no son del mundo, como yo no soy del mundo.

[[john-17-17]]
^17^ Santifícalos en la verdad: tu Palabra es verdad.

[[john-17-18]]
^18^ Como tú me has enviado al mundo, yo también los he enviado al mundo.

[[john-17-19]]
^19^ Y por ellos me santifico a mí mismo, para que ellos también sean santificados en la verdad.

[[john-17-20]]
^20^ No ruego sólo por éstos, sino también por aquellos que, por medio de su palabra, creerán en mí,

[[john-17-21]]
^21^ para que todos sean uno. Como tú, Padre, en mí y yo en ti, que ellos también sean uno en nosotros, para que el mundo crea que tú me has enviado.

[[john-17-22]]
^22^ Yo les he dado la gloria que tú me diste, para que sean uno como nosotros somos uno:

[[john-17-23]]
^23^ yo en ellos y tú en mí, para que sean perfectamente uno, y el mundo conozca que tú me has enviado y que los has amado a ellos como me has amado a mí.

[[john-17-24]]
^24^ Padre, los que tú me has dado, quiero que donde yo esté estén también conmigo, para que contemplan mi gloria, la que ma has dado, porque me has amado antes de la creación del mundo.

[[john-17-25]]
^25^ Padre justo, el mundo no te ha conocido, pero yo te he conocido y éstos han conocido que tú me has enviado.

[[john-17-26]]
^26^ Yo les he dado a conocer tu Nombre y se lo seguiré dando a conocer, para que el amor con que tú me has amado esté en ellos y yo en ellos».
[[john-18]]
== Capítulo 18

[[john-18-1]]
^1^ Dicho esto, pasó Jesús con sus discípulos al otro lado del torrente Cedrón, donde había un huerto, en el que entraron él y sus discípulos.

[[john-18-2]]
^2^ Pero también Judas, el que le entregaba, conocía el sitio, porque Jesús se había reunido allí muchas veces con sus discípulos.

[[john-18-3]]
^3^ Judas, pues, llega allí con la cohorte y los guardias enviados por los sumos sacerdotes y fariseos, con linternas, antorchas y armas.

[[john-18-4]]
^4^ Jesús, que sabía todo lo que le iba a suceder, se adelanta y les pregunta: «¿A quién buscáis?»

[[john-18-5]]
^5^ Le contestaron: «A Jesús el Nazareno». Díceles: «Yo soy». Judas, el que le entregaba, estaba también con ellos.

[[john-18-6]]
^6^ Cuando les dijo: «Yo soy», retrocedieron y cayeron en tierra.

[[john-18-7]]
^7^ Les preguntó de nuevo: «¿A quién buscáis?» Le contestaron: «A Jesús el Nazareno».

[[john-18-8]]
^8^ Respondió Jesús: «Ya os he dicho que yo soy; así que si me buscáis a mí, dejad marchar a éstos».

[[john-18-9]]
^9^ Así se cumpliría lo que había dicho: «De los que me has dado, no he perdido a ninguno».

[[john-18-10]]
^10^ Entonces Simón Pedro, que llevaba una espada, la sacó e hirió al siervo del Sumo Sacerdote, y le cortó la oreja derecha. El siervo se llamaba Malco.

[[john-18-11]]
^11^ Jesús dijo a Pedro: «Vuelve la espada a la vaina. La copa que me ha dado el Padre, ¿no la voy a beber?»

[[john-18-12]]
^12^ Entonces la cohorte, el tribuno y los guardias de los judíos prendieron a Jesús, le ataron

[[john-18-13]]
^13^ y le llevaron primero a casa de Anás, pues era suero de Caifás, el Sumo Sacerdote de aquel año.

[[john-18-14]]
^14^ Caifás era el que aconsejó a los judíos que convenía que muriera un solo hombre por el pueblo.

[[john-18-15]]
^15^ Seguían a Jesús Simón Pedro y otro discípulo. Este discípulo era conocido del Sumo Sacerdote y entró con Jesús en el atrio del Sumo Sacerdote,

[[john-18-16]]
^16^ mientras Pedro se quedaba fuera, junto a la puerta. Entonces salió el otro discípulo, el conocido del Sumo Sacerdote, habló a la portera e hizo pasar a Pedro.

[[john-18-17]]
^17^ La muchacha portera dice a Pedro: «¿No eres tú también de los discípulos de ese hombre?» Dice él: «No lo soy».

[[john-18-18]]
^18^ Los siervos y los guardias tenían unas brasas encendidas porque hacía frío, y se calentaban. También Pedro estaba con ellos calentándose.

[[john-18-19]]
^19^ El Sumo Sacerdote interrogó a Jesús sobre sus discípulos y su doctrina.

[[john-18-20]]
^20^ Jesús le respondió: «He hablado abiertamente ante todo el mundo; he enseñado siempre en la sinagoga y en el Templo, donde se reúnen todos los judíos, y no he hablado nada a ocultas.

[[john-18-21]]
^21^ ¿Por qué me preguntas? Pregunta a los que me han oído lo que les he hablado; ellos saben lo que he dicho».

[[john-18-22]]
^22^ Apenas dijo esto, uno de los guardias que allí estaba, dio una bofetada a Jesús, diciendo: «¿Así contestas al Sumo Sacerdote?»

[[john-18-23]]
^23^ Jesús le respondió: «Si he hablado mal, declara lo que está mal; pero si he hablado bien, ¿por qué me pegas?»

[[john-18-24]]
^24^ Anás entonces le envió atado al Sumo Sacerdote Caifás.

[[john-18-25]]
^25^ Estaba allí Simón Pedro calentándose y le dijeron: «¿No eres tú también de sus discípulos?» El lo negó diciendo: «No lo soy».

[[john-18-26]]
^26^ Uno de los siervos del Sumo Sacerdote, pariente de aquel a quien Pedro había cortado la oreja, le dice: «¿No te vi yo en el huerto con él?»

[[john-18-27]]
^27^ Pedró volvió a negar, y al instante cantó un gallo.

[[john-18-28]]
^28^ De la casa de Caifás llevan a Jesús al pretorio. Era de madrugada. Ellos no entraron en el pretorio para no contaminarse y poder así comer la Pascua.

[[john-18-29]]
^29^ Salió entonces Pilato fuera donde ellos y dijo: «¿Qué acusación traéis contra este hombre?»

[[john-18-30]]
^30^ Ellos le respondieron: «Si éste no fuera un malhechor, no te lo habríamos entregado».

[[john-18-31]]
^31^ Pilato replicó: «Tomadle vosotros y juzgadle según vuestra Ley». Los judíos replicaron: «Nosotros no podemos dar muerte a nadie».

[[john-18-32]]
^32^ Así se cumpliría lo que había dicho Jesús cuando indicó de qué muerte iba a morir.

[[john-18-33]]
^33^ Entonces Pilato entró de nuevo al pretorio y llamó a Jesús y le dijo: «¿Eres tú el Rey de los judíos?»

[[john-18-34]]
^34^ Respondió Jesús: «¿Dices eso por tu cuenta, o es que otros te lo han dicho de mí?»

[[john-18-35]]
^35^ Pilato respondió: «¿Es que yo soy judío? Tu pueblo y los sumos sacerdotes te han entregado a mí. ¿Qué has hecho?»

[[john-18-36]]
^36^ Respondió Jesús: «Mi Reino no es de este mundo. Si mi Reino fuese de este mundo, mi gente habría combatido para que no fuese entregado a los judíos: pero mi Reino no es de aquí».

[[john-18-37]]
^37^ Entonces Pilato le dijo: «¿Luego tú eres Rey?» Respondió Jesús: «Sí, como dices, soy Rey. Yo para esto he nacido y para est he venido al mundo: para dar testimonio de la verdad. Todo el que es de la verdad, escucha mi voz».

[[john-18-38]]
^38^ Le dice Pilato: «¿Qué es la verdad?» Y, dicho esto, volvió a salir donde los judíos y les dijo: «Yo no encuentro ningún delito en él.

[[john-18-39]]
^39^ Pero es costumbre entre vosotros que os ponga en libertad a uno por la Pascua. ¿Queréis, pues, que os ponga en libertad al Rey de los judíos?»

[[john-18-40]]
^40^ Ellos volvieron a gritar diciendo: «¡A ése, no; a Barrabás!» Barrabás era un salteador.
[[john-19]]
== Capítulo 19

[[john-19-1]]
^1^ Pilato entonces tomó a Jesús y mandó azotarle.

[[john-19-2]]
^2^ Los soldados trenzaron una corona de espinas, se la pusieron en la cabeza y le vistieron un manto de púrpura;

[[john-19-3]]
^3^ y, acercándose a él, le decían: «Salve, Rey de los judíos». Y le daban bofetadas.

[[john-19-4]]
^4^ Volvió a salir Pilato y les dijo: «Mirad, os lo traigo fuera para que sepáis que no encuentro ningún delito en él».

[[john-19-5]]
^5^ Salió entonces Jesús fuera llevando la corona de espinas y el manto de púrpura. Díceles Pilato: «Aquí tenéis al hombre».

[[john-19-6]]
^6^ Cuando lo vieron los sumos sacerdotes y los guardias, gritaron: «¡Crucifícalo, crucifícalo!» Les dice Pilato: «Tomadlo vosotros y crucificadle, porque yo ningún delito encuentro en él».

[[john-19-7]]
^7^ Los judíos le replicaron: «Nosotros tenemos una Ley y según esa Ley debe morir, porque se tiene por Hijo de Dios».

[[john-19-8]]
^8^ Cuando oyó Pilato estas palabras, se atemorizó aún más.

[[john-19-9]]
^9^ Volvió a entrar en el pretorio y dijo a Jesús: «¿De dónde eres tú?» Pero Jesús no le dio respuesta.

[[john-19-10]]
^10^ Dícele Pilato: «¿A mí no me hablas? ¿No sabes que tengo poder para soltarte y poder para crucificarte?»

[[john-19-11]]
^11^ Respondió Jesús: «No tendrías contra mí ningún poder, si no se te hubiera dado de arriba; por eso, el que me ha entregado a ti tiene mayor pecado».

[[john-19-12]]
^12^ Desde entonces Pilato trataba de librarle. Pero los judíos gritaron: «Si sueltas a ése, no eres amigo del César; todo el que se hace rey se enfrenta al César».

[[john-19-13]]
^13^ Al oír Pilato estas palabras, hizo salir a Jesús y se sentó en el tribunal, en el lugar llamado Enlosado, en hebreo Gabbatá.

[[john-19-14]]
^14^ Era el día de la Preparación de la Pascua, hacia la hora sexta. Dice Pilato a los judíos: «Aquí tenéis a vuestro Rey».

[[john-19-15]]
^15^ Ellos gritaron: «¡Fuera, fuera! ¡Crucifícale!» Les dice Pilato: «¿A vuestro Rey voy a crucificar?» Replicaron los sumos sacerdotes: «No tenemos más rey que el César».

[[john-19-16]]
^16^ Entonces se lo entregó para que fuera crucificado. Tomaron, pues, a Jesús,

[[john-19-17]]
^17^ y él cargando con su cruz, salió hacia el lugar llamado Calvario, que en hebreo se llama Gólgota,

[[john-19-18]]
^18^ y allí le crucificaron y con él a otros dos, uno a cada lado, y Jesús en medio.

[[john-19-19]]
^19^ Pilato redactó también una inscripción y la puso sobre la cruz. Lo escrito era: «Jesús el Nazareno, el Rey de los judíos».

[[john-19-20]]
^20^ Esta inscripción la leyeron muchos judíos, porque el lugar donde había sido crucificado Jesús estaba cerca de la ciudad; y estaba escrita en hebreo, latín y griego.

[[john-19-21]]
^21^ Los sumos sacerdotes de los judíos dijeron a Pilato: «No escribas: “El Rey de los judíos”, sino: “Este ha dicho: Yo soy Rey de los judíos”».

[[john-19-22]]
^22^ Pilato respondió: «Lo que he escrito, lo he escrito».

[[john-19-23]]
^23^ Los soldados, después que crucificaron a Jesús, tomaron sus vestidos, con los que hicieron cuatro lotes, un lote para cada soldado, y la túnica. La túnica era sin costura, tejida de una pieza de arriba abajo.

[[john-19-24]]
^24^ Por eso se dijeron: «No la rompamos; sino echemos a suertes a ver a quién le toca». Para que se cumpliera la Escritura: Se han repartido mis vestidos, han echado a suertes mi túnica. Y esto es lo que hicieron los soldados.

[[john-19-25]]
^25^ Junto a la cruz de Jesús estaban su madre y la hermana de su madre, María, mujer de Clopás, y María Magdalena.

[[john-19-26]]
^26^ Jesús, viendo a su madre y junto a ella al discípulo a quien amaba, dice a su madre: «Mujer, ahí tienes a tu hijo».

[[john-19-27]]
^27^ Luego dice al discípulo: «Ahí tienes a tu madre». Y desde aquella hora el discípulo la acogió en su casa.

[[john-19-28]]
^28^ Después de esto, sabiendo Jesús que ya todo estaba cumplido, para que se cumpliera la Escritura, dice: «Tengo sed».

[[john-19-29]]
^29^ Había allí una vasija llena de vinagre. Sujetaron a una rama de hisopo una esponja empapada en vinagre y se la acercaron a la boca.

[[john-19-30]]
^30^ Cuando tomó Jesús el vinagre, dijo: «Todo está cumplido». E inclinando la cabeza entregó el espíritu.

[[john-19-31]]
^31^ Los judíos, como era el día de la Preparación, para que no quedasen los cuerpos en la cruz el sábado - porque aquel sábado era muy solemne - rogaron a Pilato que les quebraran las piernas y los retiraran.

[[john-19-32]]
^32^ Fueron, pues, los soldados y quebraron las piernas del primero y del otro crucificado con él.

[[john-19-33]]
^33^ Pero al llegar a Jesús, como lo vieron ya muerto, no le quebraron las piernas,

[[john-19-34]]
^34^ sino que uno de los soldados le atravesó el costado con una lanza y al instante salió sangre y agua.

[[john-19-35]]
^35^ El que lo vio lo atestigua y su testimonio es válido, y él sabe que dice la verdad, para que también vosotros creáis.

[[john-19-36]]
^36^ Y todo esto sucedió para que se cumpliera la Escritura: No se le quebrará hueso alguno.

[[john-19-37]]
^37^ Y también otra Escritura dice: Mirarán al que traspasaron.

[[john-19-38]]
^38^ Después de esto, José de Arimatea, que era discípulo de Jesús, aunque en secreto por miedo a los judíos, pidió a Pilato autorización para retirar el cuerpo de Jesús. Pilato se lo concedió. Fueron, pues, y retiraron su cuerpo.

[[john-19-39]]
^39^ Fue también Nicodemo - aquel que anteriormente había ido a verle de noche - con una mezcla de mirra y áloe de unas cien libras.

[[john-19-40]]
^40^ Tomaron el cuerpo de Jesús y lo envolvieron en vendas con los aromas, conforme a la costumbre judía de sepultar.

[[john-19-41]]
^41^ En el lugar donde había sido crucificado había un huerto, y en el huerto un sepulcro nuevo, en el que nadie todavía había sido depositado.

[[john-19-42]]
^42^ Allí, pues, porque era el día de la Preparación de los judíos y el sepulcro estaba cerca, pusieron a Jesús.
[[john-20]]
== Capítulo 20

[[john-20-1]]
^1^ El primer día de la semana va María Magdalena de madrugada al sepulcro cuando todavía estaba oscuro, y ve la piedra quitada del sepulcro.

[[john-20-2]]
^2^ Echa a correr y llega donde Simón Pedro y donde el otro discípulo a quien Jesús quería y les dice: «Se han llevado del sepulcro al Señor, y no sabemos dónde le han puesto».

[[john-20-3]]
^3^ Salieron Pedro y el otro discípulo, y se encaminaron al sepulcro.

[[john-20-4]]
^4^ Corrían los dos juntos, pero el otro discípulo corrió por delante más rápido que Pedro, y llegó primero al sepulcro.

[[john-20-5]]
^5^ Se inclinó y vio las vendas en el suelo; pero no entró.

[[john-20-6]]
^6^ Llega también Simón Pedro siguiéndole, entra en el sepulcro y ve las vendas en el suelo,

[[john-20-7]]
^7^ y el sudario que cubrió su cabeza, no junto a las vendas, sino plegado en un lugar aparte.

[[john-20-8]]
^8^ Entonces entró también el otro discípulo, el que había llegado el primero al sepulcro; vio y creyó,

[[john-20-9]]
^9^ pues hasta entonces no habían comprendido que según la Escritura Jesús debía resucitar de entre los muertos.

[[john-20-10]]
^10^ Los discípulos, entonces, volvieron a casa.

[[john-20-11]]
^11^ Estaba María junto al sepulcro fuera llorando. Y mientras lloraba se inclinó hacia el sepulcro,

[[john-20-12]]
^12^ y ve dos ángeles de blanco, sentados donde había estado el cuerpo de Jesús, uno a la cabecera y otro a los pies.

[[john-20-13]]
^13^ Dícenle ellos: «Mujer, ¿por qué lloras?» Ella les respondió: «Porque se han llevado a mi Señor, y no sé dónde le han puesto».

[[john-20-14]]
^14^ Dicho esto, se volvió y vio a Jesús, de pie, pero no sabía que era Jesús.

[[john-20-15]]
^15^ Le dice Jesús: «Mujer, ¿por qué lloras? ¿A quién buscas?» Ella, pensando que era el encargado del huerto, le dice: «Señor, si tú lo has llevado, dime dónde lo has puesto, y yo me lo llevaré».

[[john-20-16]]
^16^ Jesús le dice: «María». Ella se vuelve y le dice en hebreo: «Rabbuní» - que quiere decir: «Maestro» -.

[[john-20-17]]
^17^ Dícele Jesús: «No me toques, que todavía no he subido al Padre. Pero vete donde mis hermanos y diles: Subo a mi Padre y vuestro Padre, a mi Dios y vuestro Dios».

[[john-20-18]]
^18^ Fue María Magdalena y dijo a los discípulos que había visto al Señor y que había dicho estas palabras.

[[john-20-19]]
^19^ Al atardecer de aquel día, el primero de la semana, estando cerradas, por miedo a los judíos, las puertas del lugar donde se encontraban los discípulos, se presentó Jesús en medio de ellos y les dijo: «La paz con vosotros».

[[john-20-20]]
^20^ Dicho esto, les mostró las manos y el costado. Los discípulos se alegraron de ver al Señor.

[[john-20-21]]
^21^ Jesús les dijo otra vez: «La paz con vosotros. Como el Padre me envió, también yo os envío».

[[john-20-22]]
^22^ Dicho esto, sopló sobre ellos y les dijo: «Recibid el Espíritu Santo.

[[john-20-23]]
^23^ A quienes perdonéis los pecados, les quedan perdonados; a quienes se los retengáis, les quedan retenidos».

[[john-20-24]]
^24^ Tomás, uno de los Doce, llamado el Mellizo, no estaba con ellos cuando vino Jesús. Los otros discípulos le decían: «Hemos visto al Señor».

[[john-20-25]]
^25^ Pero él les contestó: «Si no veo en sus manos la señal de los clavos y no meto mi dedo en el agujero de los clavos y no meto mi mano en su costado, no creeré».

[[john-20-26]]
^26^ Ocho días después, estaban otra vez sus discípulos dentro y Tomás con ellos. Se presentó Jesús en medio estando las puertas cerradas, y dijo: «La paz con vosotros».

[[john-20-27]]
^27^ Luego dice a Tomás: «Acerca aquí tu dedo y mira mis manos; trae tu mano y métela en mi costado, y no seas incrédulo sino creyente».

[[john-20-28]]
^28^ Tomás le contestó: «Señor mío y Dios mío».

[[john-20-29]]
^29^ Dícele Jesús: «Porque me has visto has creído. Dichosos los que no han visto y han creído».

[[john-20-30]]
^30^ Jesús realizó en presencia de los discípulos otras muchas señales que no están escritas en este libro.

[[john-20-31]]
^31^ Estas han sido escritas para que creáis que Jesús es el Cristo, el Hijo de Dios, y para que creyendo tengáis vida en su nombre.
[[john-21]]
== Capítulo 21

[[john-21-1]]
^1^ Después de esto, se manifestó Jesús otra vez a los discípulos a orillas del mar de Tiberíades. Se manifestó de esta manera.

[[john-21-2]]
^2^ Estaban juntos Simón Pedro, Tomás, llamado el Mellizo, Natanael, el de Caná de Galilea, los de Zebedeo y otros dos de sus discípulos.

[[john-21-3]]
^3^ Simón Pedro les dice: «Voy a pescar». Le contestan ellos: «También nosotros vamos contigo». Fueron y subieron a la barca, pero aquella noche no pescaron nada.

[[john-21-4]]
^4^ Cuando ya amaneció, estaba Jesús en la orilla; pero los discípulos no sabían que era Jesús.

[[john-21-5]]
^5^ Díceles Jesús: «Muchachos, ¿no tenéis pescado?» Le contestaron: «No».

[[john-21-6]]
^6^ El les dijo: «Echad la red a la derecha de la barca y encontraréis». La echaron, pues, y ya no podían arrastrarla por la abundancia de peces.

[[john-21-7]]
^7^ El discípulo a quien Jesús amaba dice entonces a Pedro: «Es el Señor», se puso el vestido - pues estaba desnudo - y se lanzó al mar.

[[john-21-8]]
^8^ Los demás discípulos vinieron en la barca, arrastrando la red con los peces; pues no distaban mucho de tierra, sino unos doscientos codos.

[[john-21-9]]
^9^ Nada más saltar a tierra, ven preparadas unas brasas y un pez sobre ellas y pan.

[[john-21-10]]
^10^ Díceles Jesús: «Traed algunos de los peces que acabáis de pescar».

[[john-21-11]]
^11^ Subió Simón Pedro y sacó la red a tierra, llena de peces grandes: ciento cincuenta y tres. Y, aun siendo tantos, no se rompió la red.

[[john-21-12]]
^12^ Jesús les dice: «Venid y comed». Ninguno de los discípulos se atrevía a preguntarle: «¿Quién eres tú?», sabiendo que era el Señor.

[[john-21-13]]
^13^ Viene entonces Jesús, toma el pan y se lo da; y de igual modo el pez.

[[john-21-14]]
^14^ Esta fue ya la tercera vez que Jesús se manifestó a los discípulos después de resucitar de entre los muertos.

[[john-21-15]]
^15^ Después de haber comido, dice Jesús a Simón Pedro: «Simón de Juan, ¿me amas más que éstos?» Le dice él: «Sí, Señor, tú sabes que te quiero». Le dice Jesús: «Apacienta mis corderos».

[[john-21-16]]
^16^ Vuelve a decirle por segunda vez: «Simón de Juan, ¿me amas?» Le dice él: «Sí, Señor, tú sabes que te quiero». Le dice Jesús: «Apacienta mis ovejas».

[[john-21-17]]
^17^ Le dice por tercera vez: «Simón de Juan, ¿me quieres?» Se entristeció Pedro de que le preguntase por tercera vez: «¿Me quieres?» y le dijo: «Señor, tú lo sabes todo; tú sabes que te quiero». Le dice Jesús: «Apacienta mis ovejas.

[[john-21-18]]
^18^ «En verdad, en verdad te digo: cuando eras joven, tú mismo te ceñías, e ibas adonde querías; pero cuando llegues a viejo, extenderás tus manos y otro te ceñirá y te llevará adonde tú no quieras».

[[john-21-19]]
^19^ Con esto indicaba la clase de muerte con que iba a glorificar a Dios. Dicho esto, añadió: «Sígueme».

[[john-21-20]]
^20^ Pedro se vuelve y ve siguiéndoles detrás, al discípulo a quién Jesús amaba, que además durante la cena se había recostado en su pecho y le había dicho: «Señor, ¿quién es el que te va a entregar?»

[[john-21-21]]
^21^ Viéndole Pedro, dice a Jesús: «Señor, y éste, ¿qué?»

[[john-21-22]]
^22^ Jesús le respondió: «Si quiero que se quede hasta que yo venga, ¿qué te importa? Tú, sígueme».

[[john-21-23]]
^23^ Corrió, pues, entre los hermanos la voz de que este discípulo no moriría. Pero Jesús no había dicho a Pedro: «No morirá», sino: «Si quiero que se quede hasta que yo venga».

[[john-21-24]]
^24^ Este es el discípulo que da testimonio de estas cosas y que las ha escrito, y nosotros sabemos que su testimonio es verdadero.

[[john-21-25]]
^25^ Hay además otras muchas cosas que hizo Jesús. Si se escribieran una por una, pienso que ni todo el mundo bastaría para contener los libros que se escribieran.
