[[acts]]
= Hechos

[[acts-1]]
== Capítulo 1

[[acts-1-1]]
^1^ El primer libro lo escribí, Teófilo, sobre todo lo que Jesús hizo y enseñó desde un principio

[[acts-1-2]]
^2^ hasta el día en que, después de haber dado instrucciones por medio del Espíritu Santo a los apóstoles que había elegido, fue llevado al cielo.

[[acts-1-3]]
^3^ A estos mismos, después de su pasión, se les presentó dándoles muchas pruebas de que vivía, apareciéndoseles durante cuarenta días y hablándoles acerca de lo referente al Reino de Dios.

[[acts-1-4]]
^4^ Mientras estaba comiendo con ellos, les mandó que no se ausentasen de Jerusalén, sino que aguardasen la Promesa del Padre, «que oísteis de mí:

[[acts-1-5]]
^5^ Que Juan bautizó con agua, pero vosotros seréis bautizados en el Espíritu Santo dentro de pocos días».

[[acts-1-6]]
^6^ Los que estaban reunidos le preguntaron: «Señor, ¿es en este momento cuando vas a restablecer el Reino de Israel?»

[[acts-1-7]]
^7^ El les contestó: «A vosotros no os toca conocer el tiempo y el momento que ha fijado el Padre con su autoridad,

[[acts-1-8]]
^8^ sino que recibiréis la fuerza del Espíritu Santo, que vendrá sobre vosotros, y seréis mis testigos en Jerusalén, en toda Judea y Samaria, y hasta los confines de la tierra».

[[acts-1-9]]
^9^ Y dicho esto, fue levantado en presencia de ellos, y una nube le ocultó a sus ojos.

[[acts-1-10]]
^10^ Estando ellos mirando fijamente al cielo mientras se iba, se les aparecieron dos hombres vestidos de blanco

[[acts-1-11]]
^11^ que les dijeron: «Galileos, ¿qué hacéis ahí mirando al cielo? Este que os ha sido llevado, este mismo Jesús, vendrá así tal como le habéis visto subir al cielo».

[[acts-1-12]]
^12^ Entonces se volvieron a Jerusalén desde el monte llamado de los Olivos, que dista poco de Jerusalén, el espacio de un camino sabático.

[[acts-1-13]]
^13^ Y cuando llegaron subieron a la estancia superior, donde vivían, Pedro, Juan, Santiago y Andrés; Felipe y Tomás; Bartolomé y Mateo; Santiago de Alfeo, Simón el Zelotes y Judas de Santiago.

[[acts-1-14]]
^14^ Todos ellos perseveraban en la oración, con un mismo espíritu en compañía de algunas mujeres, de María, la madre de Jesús, y de sus hermanos.

[[acts-1-15]]
^15^ Uno de aquellos días Pedro se puso en pie en medio de los hermanos - el número de los reunidos era de unos ciento veinte - y les dijo:

[[acts-1-16]]
^16^ «Hermanos, era preciso que se cumpliera la Escritura en la que el Espíritu Santo, por boca de David, había hablado ya acerca de Judas, el que fue guía de los que prendieron a Jesús.

[[acts-1-17]]
^17^ Porque él era uno de los nuestros y obtuvo un puesto en este ministerio.

[[acts-1-18]]
^18^ Este, pues, compró un campo con el precio de su iniquidad, y cayendo de cabeza, se reventó por medio y se derramaron todas sus entrañas. -

[[acts-1-19]]
^19^ Y esto fue conocido por todos los habitantes de Jerusalén de forma que el campo se llamó en su lengua Haqueldamá, es decir: “Campo de Sangre” -

[[acts-1-20]]
^20^ Pues en el libro de los Salmos está escrito: Quede su majada desierta, y no haya quien habite en ella. Y también: Que otro reciba su cargo.

[[acts-1-21]]
^21^ «Conviene, pues, que de entre los hombres que anduvieron con nosotros todo el tiempo que el Señor Jesús convivió con nosotros,

[[acts-1-22]]
^22^ a partir del bautismo de Juan hasta el día en que nos fue llevado, uno de ellos sea constituido testigo con nosotros de su resurrección».

[[acts-1-23]]
^23^ Presentaron a dos: a José, llamado Barsabás, por sobrenombre Justo, y a Matías.

[[acts-1-24]]
^24^ Entonces oraron así: «Tú, Señor, que conoces los corazones de todos, muéstranos a cuál de estos dos has elegido,

[[acts-1-25]]
^25^ para ocupar en el ministerio del apostolado el puesto del que Judas desertó para irse adonde le correspondía».

[[acts-1-26]]
^26^ Echaron suertes y la suerte cayó sobre Matías, que fue agregado al número de los doce apóstoles.
[[acts-2]]
== Capítulo 2

[[acts-2-1]]
^1^ Al llegar el día de Pentecostés, estaban todos reunidos en un mismo lugar.

[[acts-2-2]]
^2^ De repente vino del cielo un ruido como el de una ráfaga de viento impetuoso, que llenó toda la casa en la que se encontraban.

[[acts-2-3]]
^3^ Se les aparecieron unas lenguas como de fuego que se repartieron y se posaron sobre cada uno de ellos;

[[acts-2-4]]
^4^ quedaron todos llenos del Espíritu Santo y se pusieron a hablar en otras lenguas, según el Espíritu les concedía expresarse.

[[acts-2-5]]
^5^ Había en Jerusalén hombres piadosos, que allí residían, venidos de todas las naciones que hay bajo el cielo.

[[acts-2-6]]
^6^ Al producirse aquel ruido la gente se congregó y se llenó de estupor al oírles hablar cada uno en su propia lengua.

[[acts-2-7]]
^7^ Estupefactos y admirados decían: «¿Es que no son galileos todos estos que están hablando?

[[acts-2-8]]
^8^ Pues ¿cómo cada uno de nosotros les oímos en nuestra propia lengua nativa?

[[acts-2-9]]
^9^ Partos, medos y elamitas; habitantes de Mesopotamia, Judea, Capadocia, el Ponto, Asia,

[[acts-2-10]]
^10^ Frigia, Panfilia, Egipto, la parte de Libia fronteriza con Cirene, forasteros romanos,

[[acts-2-11]]
^11^ judíos y prosélitos, cretenses y árabes, todos les oímos hablar en nuestra lengua las maravillas de Dios».

[[acts-2-12]]
^12^ Todos estaban estupefactos y perplejos y se decían unos a otros: «¿Qué significa esto?»

[[acts-2-13]]
^13^ Otros en cambio decían riéndose: «¡Están llenos de mosto!»

[[acts-2-14]]
^14^ Entonces Pedro, presentándose con los Once, levantó su voz y les dijo: «Judíos y habitantes todos de Jerusalén: Que os quede esto bien claro y prestad atención a mis palabras:

[[acts-2-15]]
^15^ No están éstos borrachos, como vosotros suponéis, pues es la hora tercia del día,

[[acts-2-16]]
^16^ sino que es lo que dijo el profeta:

[[acts-2-17]]
^17^ Sucederá en los últimos días, dice Dios: Derramaré mi Espíritu sobre toda carne, y profetizarán vuestros hijos y vuestras hijas; vuestros jóvenes verán visiones y vuestros ancianos soñarán sueños.

[[acts-2-18]]
^18^ Y yo sobre mis siervos y sobre mis siervas derramaré mi Espíritu.

[[acts-2-19]]
^19^ Haré prodigios arriba en el cielo y señales abajo en la tierra.

[[acts-2-20]]
^20^ El sol se convertirá en tinieblas, y la luna en sangre, antes de que llegue el Día grande del Señor.

[[acts-2-21]]
^21^ Y todo el que invoque el nombre del Señor se salvará.

[[acts-2-22]]
^22^ «Israelitas, escuchad estas palabras: A Jesús, el Nazoreo, hombre acreditado por Dios entre vosotros con milagros, prodigios y señales que Dios hizo por su medio entre vosotros, como vosotros mismos sabéis,

[[acts-2-23]]
^23^ a éste, que fue entregado según el determinado designio y previo conocimiento de Dios, vosotros le matasteis clavándole en la cruz por mano de los impíos;

[[acts-2-24]]
^24^ a éste, pues, Dios le resucitó librándole de los dolores del Hades, pues no era posible que quedase bajo su dominio;

[[acts-2-25]]
^25^ porque dice de él David: Veía constantemente al Señor delante de mí, puesto que está a mi derecha, para que no vacile.

[[acts-2-26]]
^26^ Por eso se ha alegrado mi corazón y se ha alborozado mi lengua, y hasta mi carne reposará en la esperanza

[[acts-2-27]]
^27^ de que no abandonarás mi alma en el Hades ni permitirás que tu santo experimente la corrupción.

[[acts-2-28]]
^28^ Me has hecho conocer caminos de vida, me llenarás de gozo con tu rostro.

[[acts-2-29]]
^29^ «Hermanos, permitidme que os diga con toda libertad cómo el patriarca David murió y fue sepultado y su tumba permanece entre nosotros hasta el presente.

[[acts-2-30]]
^30^ Pero como él era profeta y sabía que Dios le había asegurado con juramento que se sentaría en su trono un descendiente de su sangre,

[[acts-2-31]]
^31^ vio a lo lejos y habló de la resurrección de Cristo, que ni fue abandonado en el Hades ni su carne experimentó la corrupción.

[[acts-2-32]]
^32^ A este Jesús Dios le resucitó; de lo cual todos nosotros somos testigos.

[[acts-2-33]]
^33^ Y exaltado por la diestra de Dios, ha recibido del Padre el Espíritu Santo prometido y ha derramado lo que vosotros veis y oís.

[[acts-2-34]]
^34^ Pues David no subió a los cielos y sin embargo dice: Dijo el Señor a mi Señor: Siéntate a mi diestra

[[acts-2-35]]
^35^ hasta que ponga a tus enemigos por escabel de tus pies.

[[acts-2-36]]
^36^ «Sepa, pues, con certeza toda la casa de Israel que Dios ha constituido Señor y Cristo a este Jesús a quien vosotros habéis crucificado».

[[acts-2-37]]
^37^ Al oír esto, dijeron con el corazón compungido a Pedro y a los demás apóstoles: «¿Qué hemos de hacer, hermanos?»

[[acts-2-38]]
^38^ Pedro les contestó: «Convertíos y que cada uno de vosotros se haga bautizar en el nombre de Jesucristo, para remisión de vuestros pecados; y recibiréis el don del Espíritu Santo;

[[acts-2-39]]
^39^ pues la Promesa es para vosotros y para vuestros hijos, y para todos los que están lejos, para cuantos llame el Señor Dios nuestro».

[[acts-2-40]]
^40^ Con otras muchas palabras les conjuraba y les exhortaba: «Salvaos de esta generación perversa».

[[acts-2-41]]
^41^ Los que acogieron su Palabra fueron bautizados. Aquel día se les unieron unas 3.000 almas.

[[acts-2-42]]
^42^ Acudían asiduamente a la enseñanza de los apóstoles, a la comunión, a la fracción del pan y a las oraciones.

[[acts-2-43]]
^43^ El temor se apoderaba de todos, pues los apóstoles realizaban muchos prodigios y señales.

[[acts-2-44]]
^44^ Todos los creyentes vivían unidos y tenían todo en común;

[[acts-2-45]]
^45^ vendían sus posesiones y sus bienes y repartían el precio entre todos, según la necesidad de cada uno.

[[acts-2-46]]
^46^ Acudían al Templo todos los días con perseverancia y con un mismo espíritu, partían el pan por las casas y tomaban el alimento con alegría y sencillez de corazón.

[[acts-2-47]]
^47^ Alababan a Dios y gozaban de la simpatía de todo el pueblo. El Señor agregaba cada día a la comunidad a los que se habían de salvar.
[[acts-3]]
== Capítulo 3

[[acts-3-1]]
^1^ Pedro y Juan subían al Templo para la oración de la hora nona.

[[acts-3-2]]
^2^ Había un hombre, tullido desde su nacimiento, al que llevaban y ponían todos los días junto a la puerta del Templo llamada Hermosa para que pidiera limosna a los que entraban en el Templo.

[[acts-3-3]]
^3^ Este, al ver a Pedro y a Juan que iban a entrar en el Templo, les pidió una limosna.

[[acts-3-4]]
^4^ Pedro fijó en él la mirada juntamente con Juan, y le dijo: «Míranos».

[[acts-3-5]]
^5^ El les miraba con fijeza esperando recibir algo de ellos.

[[acts-3-6]]
^6^ Pedro le dijo: «No tengo plata ni oro; pero lo que tengo, te doy: en nombre de Jesucristo, el Nazoreo, ponte a andar».

[[acts-3-7]]
^7^ Y tomándole de la mano derecha le levantó. Al instante cobraron fuerza sus pies y tobillos,

[[acts-3-8]]
^8^ y de un salto se puso en pie y andaba. Entró con ellos en el Templo andando, saltando y alabando a Dios.

[[acts-3-9]]
^9^ Todo el pueblo le vio cómo andaba y alababa a Dios;

[[acts-3-10]]
^10^ le reconocían, pues él era el que pedía limosma sentado junto a la puerta Hermosa del Templo. Y se quedaron llenos de estupor y asombro por lo que había sucedido.

[[acts-3-11]]
^11^ Como él no soltaba a Pedro y a Juan, todo el pueblo, presa de estupor, corrió donde ellos al pórtico llamado de Salomón.

[[acts-3-12]]
^12^ Pedro, al ver esto, se dirigió al pueblo: «Israelitas, ¿por qué os admiráis de esto, o por qué nos miráis fijamente, como si por nuestro poder o piedad hubiéramos hecho caminar a éste?

[[acts-3-13]]
^13^ El Dios de Abraham, de Isaac y de Jacob, el Dios de nuestros padres, ha glorificado a su siervo Jesús, a quien vosotros entregasteis y de quien renegasteis ante Pilato, cuando éste estaba resuelto a ponerle en libertad.

[[acts-3-14]]
^14^ Vosotros renegasteis del Santo y del Justo, y pedisteis que se os hiciera gracia de un asesino,

[[acts-3-15]]
^15^ y matasteis al Jefe que lleva a la Vida. Pero Dios le resucitó de entre los muertos, y nosotros somos testigos de ello.

[[acts-3-16]]
^16^ Y por la fe en su nombre, este mismo nombre ha restablecido a éste que vosotros veis y conocéis; es, pues, la fe dada por su medio la que le ha restablecido totalmente ante todos vosotros.

[[acts-3-17]]
^17^ «Ya sé yo, hermanos, que obrasteis por ignorancia, lo mismo que vuestros jefes.

[[acts-3-18]]
^18^ Pero Dios dio cumplimiento de este modo a lo que había anunciado por boca de todos los profetas: que su Cristo padecería.

[[acts-3-19]]
^19^ Arrepentíos, pues, y convertíos, para que vuestros pecados sean borrados,

[[acts-3-20]]
^20^ a fin de que del Señor venga el tiempo de la consolación y envíe al Cristo que os había sido destinado, a Jesús,

[[acts-3-21]]
^21^ a quien debe retener el cielo hasta el tiempo de la restauración universal, de que Dios habló por boca de sus santos profetas.

[[acts-3-22]]
^22^ Moisés efectivamente dijo: El Señor Dios os suscitará un profeta como yo de entre vuestros hermanos; escuchadle todo cuanto os diga.

[[acts-3-23]]
^23^ Todo el que no escuche a ese profeta, sea exterminado del pueblo.

[[acts-3-24]]
^24^ Y todos los profetas que desde Samuel y sus sucesores han hablado, anunciaron también estos días.

[[acts-3-25]]
^25^ «Vosotros sois los hijos de los profetas y de la alianza que Dios estableció con vuestros padres al decir a Abraham: En tu descendencia serán bendecidas todas las familias de la tierra.

[[acts-3-26]]
^26^ Para vosotros en primer lugar ha resucitado Dios a su Siervo y le ha enviado para bendeciros, apartándoos a cada uno de vuestras iniquidades».
[[acts-4]]
== Capítulo 4

[[acts-4-1]]
^1^ Estaban hablando al pueblo, cuando se les presentaron los sacerdotes, el jefe de la guardia del Templo y los saduceos,

[[acts-4-2]]
^2^ molestos porque enseñaban al pueblo y anunciaban en la persona de Jesús la resurrección de los muertos.

[[acts-4-3]]
^3^ Les echaron mano y les pusieron bajo custodia hasta el día siguiente, pues había caído ya la tarde.

[[acts-4-4]]
^4^ Sin embargo, muchos de los que oyeron la Palabra creyeron; y el número de hombres llegó a unos 5.000.

[[acts-4-5]]
^5^ Al día siguiente se reunieron en Jerusalén sus jefes, ancianos y escribas,

[[acts-4-6]]
^6^ el Sumo Sacerdote Anás, Caifás, Jonatán, Alejandro y cuantos eran de la estirpe de sumos sacerdotes.

[[acts-4-7]]
^7^ Les pusieron en medio y les preguntaban: «¿Con qué poder o en nombre de quién habéis hecho vosotros eso?»

[[acts-4-8]]
^8^ Entonces Pedro, lleno del Espíritu Santo, les dijo: «Jefes del pueblo y ancianos,

[[acts-4-9]]
^9^ puesto que con motivo de la obra realizada en un enfermo somos hoy interrogados por quién ha sido éste curado,

[[acts-4-10]]
^10^ sabed todos vosotros y todo el pueblo de Israel que ha sido por el nombre de Jesucristo, el Nazoreo, a quien vosotros crucificasteis y a quien Dios resucitó de entre los muertos; por su nombre y no por ningún otro se presenta éste aquí sano delante de vosotros.

[[acts-4-11]]
^11^ El es la piedra que vosotros, los constructores, habéis despreciado y que se ha convertido en piedra angular.

[[acts-4-12]]
^12^ Porque no hay bajo el cielo otro nombre dado a los hombres por el que nosotros debamos salvarnos».

[[acts-4-13]]
^13^ Viendo la valentía de Pedro y Juan, y sabiendo que eran hombres sin instrucción ni cultura, estaban maravillados. Reconocían, por una parte, que habían estado con Jesús;

[[acts-4-14]]
^14^ y al mismo tiempo veían de pie, junto a ellos, al hombre que había sido curado; de modo que no podían replicar.

[[acts-4-15]]
^15^ Les mandaron salir fuera del Sanedrín y deliberaban entre ellos.

[[acts-4-16]]
^16^ Decían: «¿Qué haremos con estos hombres? Es evidente para todos los habitantes de Jerusalén, que ellos han realizado una señal manifiesta, y no podemos negarlo.

[[acts-4-17]]
^17^ Pero a fin de que esto no se divulgue más entre el pueblo, amenacémosles para que no hablen ya más a nadie en este nombre».

[[acts-4-18]]
^18^ Les llamaron y les mandaron que de ninguna manera hablasen o enseñasen en el nombre de Jesús.

[[acts-4-19]]
^19^ Mas Pedro y Juan les contestaron: «Juzgad si es justo delante de Dios obedeceros a vosotros más que a Dios.

[[acts-4-20]]
^20^ No podemos nosotros dejar de hablar de lo que hemos visto y oído».

[[acts-4-21]]
^21^ Ellos, después de haberles amenazado de nuevo, les soltaron, no hallando manera de castigarles, a causa del pueblo, porque todos glorificaban a Dios por lo que había occurrido,

[[acts-4-22]]
^22^ pues el hombre en quien se había realizado esta señal de curación tenía más de cuarenta años.

[[acts-4-23]]
^23^ Una vez libres, vinieron a los suyos y les contaron todo lo que les habían dicho los sumos sacerdotes y ancianos.

[[acts-4-24]]
^24^ Al oírlo, todos a una elevaron su voz a Dios y dijeron: «Señor, tú que hiciste el cielo y la tierra, el mar y todo lo que hay en ellos,

[[acts-4-25]]
^25^ tú que has dicho por el Espíritu Santo, por boca de nuestro padre David, tu siervo: ¿A qué esta agitación de las naciones, estos vanos proyectos de los pueblos?

[[acts-4-26]]
^26^ Se han presentado los reyes de la tierra y los magistrados se han aliado contra el Señor y contra su Ungido.

[[acts-4-27]]
^27^ «Porque verdaderamente en esta ciudad se han aliado Herodes y Poncio Pilato con las naciones y los pueblos de Israel contra tu santo siervo Jesús, a quien has ungido,

[[acts-4-28]]
^28^ para realizar lo que en tu poder y en tu sabiduría habías predeterminado que sucediera.

[[acts-4-29]]
^29^ Y ahora, Señor, ten en cuenta sus amenazas y concede a tus siervos que puedan predicar tu Palabra con toda valentía,

[[acts-4-30]]
^30^ extendiendo tu mano para realizar curaciones, señales y prodigios por el nombre de tu santo siervo Jesús».

[[acts-4-31]]
^31^ Acabada su oración, retembló el lugar donde estaban reunidos, y todos quedaron llenos del Espíritu Santo y predicaban la Palabra de Dios con valentía.

[[acts-4-32]]
^32^ La multitud de los creyentes no tenía sino un solo corazón y una sola alma. Nadie llamaba suyos a sus bienes, sino que todo era en común entre ellos.

[[acts-4-33]]
^33^ Los apóstoles daban testimonio con gran poder de la resurrección del Señor Jesús. Y gozaban todos de gran simpatía.

[[acts-4-34]]
^34^ No había entre ellos ningún necesitado, porque todos los que poseían campos o casas los vendían, traían el importe de la venta,

[[acts-4-35]]
^35^ y lo ponían a los pies de los apóstoles, y se repartía a cada uno según su necesidad.

[[acts-4-36]]
^36^ José, llamado por los apóstoles Bernabé (que significa: «hijo de la exhortación»), levita y originario de Chipre,

[[acts-4-37]]
^37^ tenía un campo; lo vendió, trajo el dinero y lo puso a los pies de los apóstoles.
[[acts-5]]
== Capítulo 5

[[acts-5-1]]
^1^ Un hombre llamado Ananías, de acuerdo con su mujer Safira, vendió una propiedad,

[[acts-5-2]]
^2^ y se quedó con una parte del precio, sabiéndolo también su mujer; la otra parte la trajo y la puso a los pies de los apóstoles.

[[acts-5-3]]
^3^ Pedro le dijo: «Ananías, ¿cómo es que Satanás llenó tu corazón para mentir al Espíritu Santo, y quedarte con parte del precio del campo?

[[acts-5-4]]
^4^ ¿Es que mientras lo tenías no era tuyo, y una vez vendido no podías disponer del precio? ¿Por qué determinaste en tu corazón hacer esto? Nos has mentido a los hombres, sino a Dios».

[[acts-5-5]]
^5^ Al oír Ananías estas palabras, cayó y expiró. Y un gran temor se apoderó de cuantos lo oyeron.

[[acts-5-6]]
^6^ Se levantaron los jóvenes, le amortajaron y le llevaron a enterrar.

[[acts-5-7]]
^7^ Unas tres horas más tarde entró su mujer que ignoraba lo que había pasado.

[[acts-5-8]]
^8^ Pedro le preguntó: «Dime, ¿habéis vendido en tanto el campo?» Ella respondió: «Sí, en eso».

[[acts-5-9]]
^9^ Y Pedro le replicó: «¿Cómo os habéis puesto de acuerdo para poner a prueba al Espíritu del Señor? Mira, aquí a la puerta están los pies de los que han enterrado a tu marido; ellos te llevarán a ti».

[[acts-5-10]]
^10^ Al instante ella cayó a sus pies y expiró. Entrando los jóvenes, la hallaron muerta, y la llevaron a enterrar junto a su marido.

[[acts-5-11]]
^11^ Un gran temor se apoderó de toda la Iglesia y de todos cuantos oyeron esto.

[[acts-5-12]]
^12^ Por mano de los apóstoles se realizaban muchas señales y prodigios en el pueblo... Y solían estar todos con un mismo espíritu en el pórtico de Salomón,

[[acts-5-13]]
^13^ pero nadie de los otros se atrevía a juntarse a ellos, aunque el pueblo hablaba de ellos con elogio.

[[acts-5-14]]
^14^ Los creyentes cada vez en mayor número se adherían al Señor, una multitud de hombres y mujeres.

[[acts-5-15]]
^15^ ... hasta tal punto que incluso sacaban los enfermos a las plazas y los colocaban en lechos y camillas, para que, al pasar Pedro, siquiera su sombra cubriese a alguno de ellos.

[[acts-5-16]]
^16^ También acudía la multitud de las ciudades vecinas a Jerusalén trayendo enfermos y atormentados por espíritus inmundos; y todos eran curados.

[[acts-5-17]]
^17^ Entonces se levantó el Sumo Sacerdote, y todos los suyos, los de la secta de los saduceos, y llenos de envidia,

[[acts-5-18]]
^18^ echaron mano a los apóstoles y les metieron en la cárcel pública.

[[acts-5-19]]
^19^ Pero el Angel del Señor, por la noche, abrió las puertas de la prisión, les sacó y les dijo:

[[acts-5-20]]
^20^ «Id, presentaos en el Templo y decid al pueblo todo lo referente a esta Vida».

[[acts-5-21]]
^21^ Obedecieron, y al amanecer entraron en el Templo y se pusieron a enseñar. Llegó el Sumo Sacerdote con los suyos, convocaron el Sanedrín y todo el Senado de los hijos de Israel, y enviaron a buscarlos a la cárcel.

[[acts-5-22]]
^22^ Cuando llegaron allí los alguaciles, no los encontraron en la prisión; y volvieron a darles cuenta

[[acts-5-23]]
^23^ y les dijeron: «Hemos hallado la cárcel cuidadosamente cerrada y los guardias firmes ante las puertas; pero cuando abrimos, no encontramos a nadie dentro».

[[acts-5-24]]
^24^ Cuando oyeron esto, tanto el jefe de la guardia del Templo como los sumos sacerdotes se preguntaban perplejos qué podía significar aquello.

[[acts-5-25]]
^25^ Se presentó entonces uno que les dijo: «Mirad, los hombres que pusisteis en prisión están en el Templo y enseñan al pueblo».

[[acts-5-26]]
^26^ Entonces el jefe de la guardia marchó con los alguaciles y les trajo, pero sin violencia, porque tenían miedo de que el pueblo les apedrease.

[[acts-5-27]]
^27^ Les trajeron, pues, y les presentaron en el Sanedrín. El Sumo Sacerdote les interrogó

[[acts-5-28]]
^28^ y les dijo: «Os prohibimos severamente enseñar en ese nombre, y sin embargo vosotros habéis llenado Jerusalén con vuestra doctrina y queréis hacer recaer sobre nosotros la sangre de ese hombre».

[[acts-5-29]]
^29^ Pedro y los apóstoles contestarón: «Hay que obedecer a Dios antes que a los hombres.

[[acts-5-30]]
^30^ El Dios de nuestros padres resucitó a Jesús a quien vosotros disteis muerte colgándole de un madero.

[[acts-5-31]]
^31^ A éste le ha exaltado Dios con su diestra como Jefe y Salvador, para conceder a Israel la conversión y el perdón de los pecados.

[[acts-5-32]]
^32^ Nosotros somos testigos de estas cosas, y también el Espíritu Santo que ha dado Dios a los que le obedecen».

[[acts-5-33]]
^33^ Ellos, al oír esto, se consumían de rabia y trataban de matarlos.

[[acts-5-34]]
^34^ Entonces un fariseo llamado Gamaliel, doctor de la ley, con prestigio ante todo el pueblo, se levantó en el Sanedrín. Mandó que se hiciera salir un momento a aquellos hombres,

[[acts-5-35]]
^35^ y les dijo: «Israelitas, mirad bien lo que vais a hacer con estos hombres.

[[acts-5-36]]
^36^ Porque hace algún tiempo se levantó Teudas, que pretendía ser alguien y que reunió a su alrededor unos cuatrocientos hombres; fue muerto y todos los que le seguían se disgregaron y quedaron en nada.

[[acts-5-37]]
^37^ Después de éste, en los días del empadronamiento, se levantó Judas el Galileo, que arrastró al pueblo en pos de sí; también éste pereció y todos los que le habían seguido se dispersaron.

[[acts-5-38]]
^38^ Os digo, pues, ahora: desentendeos de estos hombres y dejadlos. Porque si esta idea o esta obra es de los hombres, se destruirá;

[[acts-5-39]]
^39^ pero si es de Dios, no conseguiréis destruirles. No sea que os encontréis luchando contra Dios». Y aceptaron su parecer.

[[acts-5-40]]
^40^ Entonces llamaron a los apóstoles; y, después de haberles azotado, les intimaron que no hablasen en nombre de Jesús. Y les dejaron libres.

[[acts-5-41]]
^41^ Ellos marcharon de la presencia del Sanedrín contentos por haber sido considerados dignos de sufrir ultrajes por el Nombre.

[[acts-5-42]]
^42^ Y no cesaban de enseñar y de anunciar la Buena Nueva de Cristo Jesús cada día en el Templo y por las casas.
[[acts-6]]
== Capítulo 6

[[acts-6-1]]
^1^ Por aquellos días, al multiplicarse los discípulos, hubo quejas de los helenistas contra los hebreos, porque sus viudas eran desatendidas en la asistencia cotidiana.

[[acts-6-2]]
^2^ Los Doce convocaron la asamblea de los discípulos y dijeron: «No parece bien que nosotros abandonemos la Palabra de Dios por servir a las mesas.

[[acts-6-3]]
^3^ Por tanto, hermanos, buscad de entre vosotros a siete hombres, de buena fama, llenos de Espíritu y de sabiduría, y los pondremos al frente de este cargo;

[[acts-6-4]]
^4^ mientras que nosotros nos dedicaremos a la oración y al ministerio de la Palabra».

[[acts-6-5]]
^5^ Pareció bien la propuesta a toda la asamblea y escogieron a Esteban, hombre lleno de fe y de Espíritu Santo, a Felipe, a Prócoro, a Nicanor, a Timón, a Pármenas y a Nicolás, prosélito de Antioquía;

[[acts-6-6]]
^6^ los presentaron a los apóstoles y, habiendo hecho oración, les impusieron las manos.

[[acts-6-7]]
^7^ La Palabra de Dios iba creciendo; en Jerusalén se multiplicó considerablemente el número de los discípulos, y multitud de sacerdotes iban aceptando la fe.

[[acts-6-8]]
^8^ Esteban, lleno de gracia y de poder, realizaba entre el pueblo grandes prodigios y señales.

[[acts-6-9]]
^9^ Se levantaron unos de la sinagoga llamada de los Libertos, cirenenses y alejandrinos, y otros de Cilicia y Asia, y se pusieron a disputar con Esteban;

[[acts-6-10]]
^10^ pero no podían resistir a la sabiduría y al Espíritu con que hablaba.

[[acts-6-11]]
^11^ Entonces sobornaron a unos hombres para que dijeran: «Nosotros hemos oído a éste pronunciar palabras blasfemas contra Moisés y contra Dios».

[[acts-6-12]]
^12^ De esta forma amotinaron al pueblo, a los ancianos y escribas; vinieron de improviso, le prendieron y le condujeron al Sanedrín.

[[acts-6-13]]
^13^ Presentaron entonces testigos falsos que declararon: «Este hombre no para de hablar en contra del Lugar Santo y de la Ley;

[[acts-6-14]]
^14^ pues le hemos oído decir que Jesús, ese Nazoreo, destruiría este Lugar y cambiaría las costumbres que Moisés nos ha transmitido».

[[acts-6-15]]
^15^ Fijando en él la mirada todos los que estaban sentados en el Sanedrín, vieron su rostro como el rostro de un ángel.
[[acts-7]]
== Capítulo 7

[[acts-7-1]]
^1^ El Sumo Sacerdote preguntó: «¿Es así?»

[[acts-7-2]]
^2^ El respondió: «Hermanos y padres, escuchad. El Dios de la gloria se apareció a nuestro padre Abraham cuando estaba en Mesopotamia, antes de que se estableciese en Jarán

[[acts-7-3]]
^3^ y le dijo: Sal de tu tierra y de tu parentela y vete a la tierra que yo te muestre.

[[acts-7-4]]
^4^ Entonces salió de la tierra de los caldeos y se estableció en Jarán. Y después de morir su padre, Dios le hizo emigrar de allí a esta tierra que vosotros habitáis ahora.

[[acts-7-5]]
^5^ Y no le dio en ella en heredad ni la medida de la planta del pie; sino que prometió dársela en posesión a él y a su descendencia después de él, aunque no tenía ningún hijo.

[[acts-7-6]]
^6^ Dios habló así: Tus descendientes residirán como forasteros en tierra extraña y les esclavizarán y les maltratarán durante cuatrocientos años.

[[acts-7-7]]
^7^ Pero yo juzgaré - dijo Dios - a la nación a la que sirvan como esclavos, y después saldrán y me darán culto en este mismo lugar.

[[acts-7-8]]
^8^ Le dio, además, la alianza de la circuncisión; y así, al engendrar a Isaac, Abraham le circuncidó el octavo día, y lo mismo Isaac a Jacob, y Jacob a los doce patriarcas.

[[acts-7-9]]
^9^ «Los patriarcas, envidiosos de José, le vendieron con destino a Egipto. Pero Dios estaba con él

[[acts-7-10]]
^10^ y le libró de todas sus tribulaciones y le dio gracia y sabiduría ante Faraón, rey de Egipto, quien le nombró gobernador de Egipto y de toda su casa.

[[acts-7-11]]
^11^ Sobrevino entonces en todo Egipto y Canaán hambre y gran tribulación; nuestros padres no encontraban víveres.

[[acts-7-12]]
^12^ Pero al oír Jacob que había trigo en Egipto, envió a nuestros padres una primera vez;

[[acts-7-13]]
^13^ la segunda vez José se dio a conocer a sus hermanos y conoció Faraón el linaje de José.

[[acts-7-14]]
^14^ José envió a buscar a su padre Jacob y a toda su parentela que se componía de 75 personas.

[[acts-7-15]]
^15^ Jacob bajó a Egipto donde murió él y también nuestros padres;

[[acts-7-16]]
^16^ y fueron trasladados a Siquem y depositados en el sepulcro que había comprado Abraham a precio de plata a los hijos de Jamor, padre de Siquem.

[[acts-7-17]]
^17^ «Conforme se iba acercando el tiempo de la promesa que Dios había hecho a Abraham, creció el pueblo y se multiplicó en Egipto,

[[acts-7-18]]
^18^ hasta que se alzó un nuevo rey en Egipto que no se acordó de José.

[[acts-7-19]]
^19^ Obrando astutamente contra nuestro linaje, este rey maltrató a nuestros padres hasta obligarles a exponer sus niños, para que no vivieran.

[[acts-7-20]]
^20^ En esta coyuntura nació Moisés, que era hermoso a los ojos de Dios. Durante tres meses fue criado en la casa de su padre;

[[acts-7-21]]
^21^ después fue expuesto y le recogió la hija de Faraón, quien le crió como hijo suyo.

[[acts-7-22]]
^22^ Moisés fue educado en toda la sabiduría de los egipcios y fue poderoso en sus palabras y en sus obras.

[[acts-7-23]]
^23^ «Cuando cumplió la edad de cuarenta años, se le ocurrió la idea de visitar a sus hermanos, los hijos de Israel.

[[acts-7-24]]
^24^ Y al ver que uno de ellos era maltratado, tomó su defensa y vengó al oprimido matando al egipcio.

[[acts-7-25]]
^25^ Pensaba él que sus hermanos comprenderían que Dios les daría la salvación por su mano; pero ellos no lo comprendieron.

[[acts-7-26]]
^26^ Al día siguiente se les presentó mientras estaban peleándose y trataba de ponerles en paz diciendo: “Amigos, que sois hermanos, ¿por qué os maltratáis uno a otro?”

[[acts-7-27]]
^27^ Pero el que maltrataba a su compañero le rechazó diciendo: “¿Quién te ha nombrado jefe y juez sobre nosotros?

[[acts-7-28]]
^28^ ¿Es que quieres matarme a mí como mataste ayer al egipcio? =“

[[acts-7-29]]
^29^ Al oír esto Moisés huyó y vivió como forastero en la tierra de Madián, donde tuvo dos hijos.

[[acts-7-30]]
^30^ «Al cabo de cuarenta años se le apareció un ángel en el desierto del monte Sinaí, sobre la llama de una zarza ardiendo.

[[acts-7-31]]
^31^ Moisés se maravilló al ver la visión, y al acercarse a mirarla, se dejó oír la voz del Señor:

[[acts-7-32]]
^32^ “Yo soy el Dios de tus padres, el Dios de Abraham, de Isaac y de Jacob.” Moisés temblaba y no se atrevía a mirar.

[[acts-7-33]]
^33^ El Señor le dijo: “Quítate las sandalias de los pies, pues el lugar donde estás es tierra santa.

[[acts-7-34]]
^34^ Bien vista tengo la opresión de mi pueblo que está en Egipto y he oído sus gemidos y he bajado a librarles. Y ahora ven, que te enviaré a Egipto.”

[[acts-7-35]]
^35^ «A este Moisés, de quien renegaron diciéndole: ¿quién te ha nombrado jefe y juez?, a éste envió Dios como jefe y redentor por mano del ángel que se le apareció en la zarza.

[[acts-7-36]]
^36^ Este les sacó, realizando prodigios y señales en la tierra de Egipto, en el mar Rojo y en el desierto durante cuarenta años.

[[acts-7-37]]
^37^ Este es el Moisés que dijo a los israelitas: Dios os suscitará un profeta como yo de entre vuestros hermanos.

[[acts-7-38]]
^38^ Este es el que, en la asamblea del desierto, estuvo con el ángel que le hablaba en el monte Sinaí, y con nuestros padres; el que recibió palabras de vida para comunicárnoslas;

[[acts-7-39]]
^39^ este es aquel a quien no quisieron obedecer nuestros padres, sino que le rechazaron para volver su corazón hacia Egipto,

[[acts-7-40]]
^40^ y dijeron a Aarón: “Haznos dioses que vayan delante de nosotros; porque este Moisés que nos sacó de la tierra de Egipto no sabemos qué ha sido de él.”

[[acts-7-41]]
^41^ E hicieron aquellos días un becerro y ofrecieron un sacrificio al ídolo e hicieron una fiesta a las obras de sus manos.

[[acts-7-42]]
^42^ Entonces Dios se apartó de ellos y los entregó al culto del ejército del cielo, como está escrito en el libro de los Profetas: ¿Es que me ofrecisteis víctimas y sacrificios durante cuarenta años en el desierto, casa de Israel?

[[acts-7-43]]
^43^ Os llevasteis la tienda de Moloc y la estrella del dios Refán, las imágenes que hicisteis para adorarlas; pues yo os llevaré más allá de Babilonia.

[[acts-7-44]]
^44^ «Nuestros padres tenían en el desierto la Tienda del Testimonio, como mandó el que dijo a Moisés que la hiciera según el modelo que había visto.

[[acts-7-45]]
^45^ Nuestros padres que les sucedieron la recibieron y la introdujeron bajo el mando de Josué en el país ocupado por los gentiles, a los que Dios expulsó delante de nuestros padres, hasta los días de David,

[[acts-7-46]]
^46^ que halló gracia ante Dios y pidió encontrar una Morada para la casa de Jacob.

[[acts-7-47]]
^47^ Pero fue Salomón el que le edificó Casa,

[[acts-7-48]]
^48^ aunque el Altísimo no habita en casas hechas por mano de hombre como dice el profeta:

[[acts-7-49]]
^49^ El cielo es mi trono y la tierra el escabel de mis pies. Dice el Señor: ¿Qué Casa me edificaréis? O ¿cuál será el lugar de mi descanso?

[[acts-7-50]]
^50^ ¿Es que no ha hecho mi mano todas estas cosas?

[[acts-7-51]]
^51^ «¡Duros de cerviz, incircuncisos de corazón y de oídos! ¡Vosotros siempre resistís al Espíritu Santo! ¡Como vuestros padres, así vosotros!

[[acts-7-52]]
^52^ ¿A qué profeta no persiguieron vuestros padres? Ellos mataron a los que anunciaban de antemano la venida del Justo, de aquel a quien vosotros ahora habéis traicionado y asesinado;

[[acts-7-53]]
^53^ vosotros que recibisteis la Ley por mediación de ángeles y no la habéis guardado».

[[acts-7-54]]
^54^ Al oír esto, sus corazones se consumían de rabia y rechinaban sus dientes contra él.

[[acts-7-55]]
^55^ Pero él, lleno del Espíritu Santo, miró fijamente al cielo y vio la gloria de Dios y a Jesús que estaba en pie a la diestra de Dios;

[[acts-7-56]]
^56^ y dijo: «Estoy viendo los cielos abiertos y al Hijo del hombre que está en pie a la diestra de Dios».

[[acts-7-57]]
^57^ Entonces, gritando fuertemente, se taparon sus oídos y se precipitaron todos a una sobre él;

[[acts-7-58]]
^58^ le echaron fuera de la ciudad y empezaron a apedrearle. Los testigos pusieron sus vestidos a los pies de un joven llamado Saulo.

[[acts-7-59]]
^59^ Mientras le apedreaban, Esteban hacía esta invocación: «Señor Jesús, recibe mi espíritu».

[[acts-7-60]]
^60^ Después dobló las rodillas y dijo con fuerte voz: «Señor, no les tengas en cuenta este pecado». Y diciendo esto, se durmió.
[[acts-8]]
== Capítulo 8

[[acts-8-1]]
^1^ Saulo aprobaba su muerte. Aquel día se desató una gran persecución contra la Iglesia de Jerusalén. Todos, a excepción de los apóstoles, se dispersaron por las regiones de Judea y Samaria.

[[acts-8-2]]
^2^ Unos hombres piadosos sepultaron a Esteban e hicieron gran duelo por él.

[[acts-8-3]]
^3^ Entretanto Saulo hacía estragos en la Iglesia; entraba por las casas, se llevaba por la fuerza hombres y mujeres, y los metía en la cárcel.

[[acts-8-4]]
^4^ Los que se habían dispersado iban por todas partes anunciando la Buena Nueva de la Palabra.

[[acts-8-5]]
^5^ Felipe bajó a una ciudad de Samaria y les predicaba a Cristo.

[[acts-8-6]]
^6^ La gente escuchaba con atención y con un mismo espíritu lo que decía Felipe, porque le oían y veían las señales que realizaba;

[[acts-8-7]]
^7^ pues de muchos posesos salían los espíritus inmundos dando grandes voces, y muchos paralíticos y cojos quedaron curados.

[[acts-8-8]]
^8^ Y hubo una gran alegría en aquella ciudad.

[[acts-8-9]]
^9^ En la ciudad había ya de tiempo atrás un hombre llamado Simón que practicaba la magia y tenía atónito al pueblo de Samaria y decía que él era algo grande.

[[acts-8-10]]
^10^ Y todos, desde el menor hasta el mayor, le prestaban atención y decían: «Este es la Potencia de Dios llamada la Grande».

[[acts-8-11]]
^11^ Le prestaban atención porque les había tenido atónitos por mucho tiempo con sus artes mágicas.

[[acts-8-12]]
^12^ Pero cuando creyeron a Felipe que anunciaba la Buena Nueva del Reino de Dios y el nombre de Jesucristo, empezaron a bautizarse hombres y mujeres.

[[acts-8-13]]
^13^ Hasta el mismo Simón creyó y, una vez bautizado, no se apartaba de Felipe; y estaba atónito al ver las señales y grandes milagros que se realizaban.

[[acts-8-14]]
^14^ Al enterarse los apóstoles que estaban en Jerusalén de que Samaria había aceptado la Palabra de Dios, les enviaron a Pedro y a Juan.

[[acts-8-15]]
^15^ Estos bajaron y oraron por ellos para que recibieran el Espíritu Santo;

[[acts-8-16]]
^16^ pues todavía no había descendido sobre ninguno de ellos; únicamente habían sido bautizados en el nombre del Señor Jesús.

[[acts-8-17]]
^17^ Entonces les imponían las manos y recibían el Espíritu Santo.

[[acts-8-18]]
^18^ Al ver Simón que mediante la imposición de las manos de los apóstoles se daba el Espíritu, les ofreció dinero diciendo:

[[acts-8-19]]
^19^ «Dadme a mí también este poder para que reciba el Espíritu Santo aquel a quien yo impoga las manos».

[[acts-8-20]]
^20^ Pedro le contestó: «Vaya tu dinero a la perdición y tú con él; pues has pensado que el don de Dios se compra con dinero.

[[acts-8-21]]
^21^ En este asunto no tienes tú parte ni herencia, pues tu corazón no es recto delante de Dios.

[[acts-8-22]]
^22^ Arrepiéntete, pues, de esa tu maldad y ruega al Señor, a ver si se te perdona ese pensamiento de tu corazón;

[[acts-8-23]]
^23^ porque veo que tú estás en hiel de amargura y en ataduras de iniquidad».

[[acts-8-24]]
^24^ Simón respondió: «Rogad vosotros al Señor por mí, para que no venga sobre mí ninguna de esas cosas que habéis dicho».

[[acts-8-25]]
^25^ Ellos, después de haber dado testimonio y haber predicado la Palabra del Señor, se volvieron a Jerusalén evangelizando muchos pueblos samaritanos.

[[acts-8-26]]
^26^ El Angel del Señor habló a Felipe diciendo: «Levántate y marcha hacia el mediodía por el camino que baja de Jerusalén a Gaza. Es desierto».

[[acts-8-27]]
^27^ Se levantó y partió. Y he aquí que un etíope eunuco, alto funcionario de Candace, reina de los etíopes, que estaba a cargo de todos sus tesoros, y había venido a adorar en Jerusalén,

[[acts-8-28]]
^28^ regresaba sentado en su carro, leyendo al profeta Isaías.

[[acts-8-29]]
^29^ El Espíritu dijo a Felipe: «Acércate y ponte junto a ese carro».

[[acts-8-30]]
^30^ Felipe corrió hasta él y le oyó leer al profeta Isaías; y le dijo: «¿Entiendes lo que vas leyendo?»

[[acts-8-31]]
^31^ El contestó: «¿Cómo lo puedo entender si nadie me hace de guía?» Y rogó a Felipe que subiese y se sentase con él.

[[acts-8-32]]
^32^ El pasaje de la Escritura que iba leyendo era éste: «Fue llevado como una oveja al matadero; y como cordero, mudo delante del que lo trasquila, así él no abre la boca.

[[acts-8-33]]
^33^ En su humillación le fue negada la justicia; ¿quién podrá contar su descendencia? Porque su vida fue arrancada de la tierra».

[[acts-8-34]]
^34^ El eunuco preguntó a Felipe: «Te ruego me digas de quién dice esto el profeta: ¿de sí mismo o de otro?»

[[acts-8-35]]
^35^ Felipe entonces, partiendo de este texto de la Escritura, se puso a anunciarle la Buena Nueva de Jesús.

[[acts-8-36]]
^36^ Siguiendo el camino llegaron a un sitio donde había agua. El eunuco dijo: «Aquí hay agua; ¿qué impide que yo sea bautizado?»

[[acts-8-38]]
^38^ Y mandó detener el carro. Bajaron ambos al agua, Felipe y el eunuco; y lo bautizó,

[[acts-8-39]]
^39^ y en saliendo del agua, el Espíritu del Señor arrebató a Felipe y ya no le vio más el eunuco, que siguió gozoso su camino.

[[acts-8-40]]
^40^ Felipe se encontró en Azoto y recorría evangelizando todas las ciudades hasta llegar a Cesarea.
[[acts-9]]
== Capítulo 9

[[acts-9-1]]
^1^ Entretanto Saulo, respirando todavía amenazas y muertes contra los discípulos del Señor, se presentó al Sumo Sacerdote,

[[acts-9-2]]
^2^ y le pidió cartas para las sinagogas de Damasco, para que si encontraba algunos seguidores del Camino, hombres o mujeres, los pudiera llevar atados a Jerusalén.

[[acts-9-3]]
^3^ Sucedió que, yendo de camino, cuando estaba cerca de Damasco, de repente le rodeó una luz venida del cielo,

[[acts-9-4]]
^4^ cayó en tierra y oyó una voz que le decía: «Saúl, Saúl, ¿por qué me persigues?»

[[acts-9-5]]
^5^ El respondió: «¿Quién eres, Señor?» Y él: «Yo soy Jesús, a quien tú persigues.

[[acts-9-6]]
^6^ Pero levántate, entra en la ciudad y se te dirá lo que debes hacer».

[[acts-9-7]]
^7^ Los hombres que iban con él se habían detenido mudos de espanto; oían la voz, pero no veían a nadie.

[[acts-9-8]]
^8^ Saulo se levantó del suelo, y, aunque tenía los ojos abiertos, no veía nada. Le llevaron de la mano y le hicieron entrar en Damasco.

[[acts-9-9]]
^9^ Pasó tres días sin ver, sin comer y sin beber.

[[acts-9-10]]
^10^ Había en Damasco un discípulo llamado Ananías. El Señor le dijo en una visión: «Ananías». El respondió: «Aquí estoy, Señor».

[[acts-9-11]]
^11^ Y el Señor: «Levántate y vete a la calle Recta y pregunta en casa de Judas por uno de Tarso llamado Saulo; mira, está en oración

[[acts-9-12]]
^12^ y ha visto que un hombre llamado Ananías entraba y le imponía las manos para devolverle la vista».

[[acts-9-13]]
^13^ Respondió Ananías: «Señor, he oído a muchos hablar de ese hombre y de los muchos males que ha causado a tus santos en Jerusalén

[[acts-9-14]]
^14^ y que está aquí con poderes de los sumos sacerdotes para apresar a todos los que invocan tu nombre».

[[acts-9-15]]
^15^ El Señor le contestó: «Vete, pues éste me es un instrumento de elección que lleve mi nombre ante los gentiles, los reyes y los hijos de Israel.

[[acts-9-16]]
^16^ Yo le mostraré todo lo que tendrá que padecer por mi nombre».

[[acts-9-17]]
^17^ Fue Ananías, entró en la casa, le impuso las manos y le dijo: «Saúl, hermano, me ha enviado a ti el Señor Jesús, el que se te apareció en el camino por donde venías, para que recobres la vista y seas lleno del Espíritu Santo».

[[acts-9-18]]
^18^ Al instante cayeron de sus ojos unas como escamas, y recobró la vista; se levantó y fue bautizado.

[[acts-9-19]]
^19^ Tomó alimento y recobró las fuerzas. Estuvo algunos días con los discípulos de Damasco,

[[acts-9-20]]
^20^ y en seguida se puso a predicar a Jesús en las sinagogas: que él era el Hijo de Dios.

[[acts-9-21]]
^21^ Todos los que le oían quedaban atónitos y decían: «¿No es éste el que en Jerusalén perseguía encarnizadamente a los que invocaban ese nombre, y no ha venido aquí con el objeto de llevárselos atados a los sumos sacerdotes?»

[[acts-9-22]]
^22^ Pero Saulo se crecía y confundía a los judíos que vivían en Damasco demostrándoles que aquél era el Cristo.

[[acts-9-23]]
^23^ Al cabo de bastante tiempo los judíos tomaron la decisión de matarle.

[[acts-9-24]]
^24^ Pero Saulo tuvo conocimiento de su determinación. Hasta las puertas estaban guardadas día y noche para poderle matar.

[[acts-9-25]]
^25^ Pero los discípulos le tomaron y le descolgaron de noche por la muralla dentro de una espuerta.

[[acts-9-26]]
^26^ Llegó a Jerusalén e intentaba juntarse con los discípulos; pero todos le tenían miedo, no creyendo que fuese discípulo.

[[acts-9-27]]
^27^ Entonces Bernabé le tomó y le presentó a los apóstoles y les contó cómo había visto al Señor en el camino y que le había hablado y cómo había predicado con valentía en Damasco en el nombre de Jesús.

[[acts-9-28]]
^28^ Andaba con ellos por Jerusalén, predicando valientemente en el nombre del Señor.

[[acts-9-29]]
^29^ Hablaba también y discutía con los helenistas; pero éstos intentaban matarle.

[[acts-9-30]]
^30^ Los hermanos, al saberlo, le llevaron a Cesarea y le hicieron marchar a Tarso.

[[acts-9-31]]
^31^ Las Iglesias por entonces gozaban de paz en toda Judea, Galilea y Samaria; se edificaban y progresaban en el temor del Señor y estaban llenas de la consolación del Espíritu Santo.

[[acts-9-32]]
^32^ Pedro, que andaba recorriendo todos los lugares, bajó también a visitar a los santos que habitaban en Lida.

[[acts-9-33]]
^33^ Encontró allí a un hombre llamado Eneas, tendido en una camilla desde hacía ocho años, pues estaba paralítico.

[[acts-9-34]]
^34^ Pedro le dijo: «Eneas, Jesucristo te cura; levántate y arregla tu lecho». Y al instante se levantó.

[[acts-9-35]]
^35^ Todos los habitantes de Lida y Sarón le vieron, y se convirtieron al Señor.

[[acts-9-36]]
^36^ Había en Joppe una discípula llamada Tabitá, que quiere decir Dorcás. Era rica en buenas obras y en limosnas que hacía.

[[acts-9-37]]
^37^ Por aquellos días enfermó y murió. La lavaron y la pusieron en la estancia superior.

[[acts-9-38]]
^38^ Lida está cerca de Joppe, y los discípulos, al enterarse que Pedro estaba allí, enviaron dos hombres con este ruego: «No tardes en venir a nosotros».

[[acts-9-39]]
^39^ Pedro partió inmediatamente con ellos. Así que llegó le hicieron subir a la estancia superior y se le presentaron todas las viudas llorando y mostrando las túnicas y los mantos que Dorcás hacía mientras estuvo con ellas.

[[acts-9-40]]
^40^ Pedro hizo salir a todos, se puso de rodillas y oró; después se volvió al cadáver y dijo: «Tabitá, levántate». Ella abrió sus ojos y al ver a Pedro se incorporó.

[[acts-9-41]]
^41^ Pedro le dio la mano y la levantó. Llamó a los santos y a las viudas y se la presentó viva.

[[acts-9-42]]
^42^ Esto se supo por todo Joppe y muchos creyeron en el Señor.

[[acts-9-43]]
^43^ Pedro permaneció en Joppe bastante tiempo en casa de un tal Simón, curtidor.
[[acts-10]]
== Capítulo 10

[[acts-10-1]]
^1^ Había en Cesarea un hombre, llamado Cornelio, centurión de la cohorte Itálica,

[[acts-10-2]]
^2^ piadoso y temeroso de Dios, como toda su familia, daba muchas limosnas al pueblo y continuamente oraba a Dios.

[[acts-10-3]]
^3^ Vio claramente en visión, hacia la hora nona del día, que el Angel de Dios entraba en su casa y le decía: «Cornelio».

[[acts-10-4]]
^4^ El le miró fijamente y lleno de espanto dijo: «¿Qué pasa, señor?» Le respondió: «Tus oraciones y tus limosnas han subido como memorial ante la presencia de Dios.

[[acts-10-5]]
^5^ Ahora envía hombres a Joppe y haz venir a un tal Simón, a quien llaman Pedro.

[[acts-10-6]]
^6^ Este se hospeda en casa de un tal Simón, curtidor, que tiene la casa junto al mar».

[[acts-10-7]]
^7^ Apenas se fue el ángel que le hablaba, llamó a dos criados y a un soldado piadoso, de entre sus asistentes,

[[acts-10-8]]
^8^ les contó todo y los envió a Joppe.

[[acts-10-9]]
^9^ Al día siguiente, mientras ellos iban de camino y se acercaban a la ciudad, subió Pedro al terrado, sobre la hora sexta, para hacer oración.

[[acts-10-10]]
^10^ Sintió hambre y quiso comer. Mientras se lo preparaban le sobrevino un éxtasis,

[[acts-10-11]]
^11^ y vio los cielos abiertos y que bajaba hacia la tierra una cosa así como un gran lienzo, atado por las cuatro puntas.

[[acts-10-12]]
^12^ Dentro de él había toda suerte de cuadrúpedos, reptiles de la tierra y aves del cielo.

[[acts-10-13]]
^13^ Y una voz le dijo: «Levántate, Pedro, sacrifica y come».

[[acts-10-14]]
^14^ Pedro contestó: «De ninguna manera, Señor; jamás he comido nada profano e impuro».

[[acts-10-15]]
^15^ La voz le dijo por segunda vez: «Lo que Dios ha purificado no lo llames tú profano».

[[acts-10-16]]
^16^ Esto se repitió tres veces, e inmediatamente la cosa aquella fue elevada hacia el cielo.

[[acts-10-17]]
^17^ Estaba Pedro perplejo pensando qué podría significar la visión que había visto, cuando los hombres enviados por Cornelio, después de preguntar por la casa de Simón, se presentaron en la puerta;

[[acts-10-18]]
^18^ llamaron y preguntaron si se hospedaba allí Simón, llamado Pedro.

[[acts-10-19]]
^19^ Estando Pedro pensando en la visión, le dijo el Espíritu: «Ahí tienes unos hombres que te buscan.

[[acts-10-20]]
^20^ Baja, pues, al momento y vete con ellos sin vacilar, pues yo los he enviado».

[[acts-10-21]]
^21^ Pedro bajó donde ellos y les dijo: «Yo soy el que buscáis; ¿por qué motivo habéis venido?»

[[acts-10-22]]
^22^ Ellos respondieron: «El centurión Cornelio, hombre justo y temeroso de Dios, reconocido como tal por el testimonio de toda la nación judía, ha recibido de un ángel santo el aviso de hacerte venir a su casa y de escuchar lo que tú digas».

[[acts-10-23]]
^23^ Entonces les invitó a entrar y les dio hospedaje. Al día siguiente se levantó y se fue con ellos; le acompañaron algunos hermanos de Joppe.

[[acts-10-24]]
^24^ Al siguiente día entró en Cesarea. Cornelio los estaba esperando. Había reunido a sus parientes y a los amigos íntimos.

[[acts-10-25]]
^25^ Cuando Pedro entraba salió Cornelio a su encuentro y cayó postrado a sus pies.

[[acts-10-26]]
^26^ Pedro le levantó diciéndole: «Levántate, que también yo soy un hombre».

[[acts-10-27]]
^27^ Y conversando con él entró y encontró a muchos reunidos.

[[acts-10-28]]
^28^ Y les dijo: «Vosotros sabéis que no le está permitido a un judío juntarse con un extranjero ni entrar en su casa; pero a mí me ha mostrado Dios que no hay que llamar profano o impuro a ningún hombre.

[[acts-10-29]]
^29^ Por eso al ser llamado he venido sin dudar. Os pregunto, pues, por qué motivo me habéis enviado a llamar».

[[acts-10-30]]
^30^ Cornelio contestó: «Hace cuatro días, a esta misma hora, estaba yo haciendo la oración de nona en mi casa, y de pronto se presentó delante de mí un varón con vestidos resplandecientes,

[[acts-10-31]]
^31^ y me dijo: “Cornelio, tu oración ha sido oída y se han recordado tus limosnas ante Dios;

[[acts-10-32]]
^32^ envía, pues, a Joppe y haz llamar a Simón, llamado Pedro, que se hospeda en casa de Simón el curtidor, junto al mar.”

[[acts-10-33]]
^33^ Al instante mandé enviados donde ti, y tú has hecho bien en venir. Ahora, pues, todos nosotros, en la presencia de Dios, estamos dispuestos para escuchar todo lo que te ha sido ordenado por el Señor».

[[acts-10-34]]
^34^ Entonces Pedro tomó la palabra y dijo: «Verdaderamente comprendo que Dios no hace acepción de personas,

[[acts-10-35]]
^35^ sino que en cualquier nación el que le teme y practica la justicia le es grato.

[[acts-10-36]]
^36^ «El ha enviado su Palabra a los hijos de Israel, anunciándoles la Buena Nueva de la paz por medio de Jesucristo que es el Señor de todos.

[[acts-10-37]]
^37^ Vosotros sabéis lo sucedido en toda Judea, comenzando por Galilea, después que Juan predicó el bautismo;

[[acts-10-38]]
^38^ cómo Dios a Jesús de Nazaret le ungió con el Espíritu Santo y con poder, y cómo él pasó haciendo el bien y curando a todos los oprimidos por el Diablo, porque Dios estaba con él;

[[acts-10-39]]
^39^ y nosotros somos testigos de todo lo que hizo en la región de los judíos y en Jerusalén; a quien llegaron a matar colgándole de un madero;

[[acts-10-40]]
^40^ a éste, Dios le resucitó al tercer día y le concedió la gracia de aparecerse,

[[acts-10-41]]
^41^ no a todo el pueblo, sino a los testigos que Dios había escogido de antemano, a nosotros que comimos y bebimos con él después que resucitó de entre los muertos.

[[acts-10-42]]
^42^ Y nos mandó que predicásemos al Pueblo, y que diésemos testimonio de que él está constituido por Dios juez de vivos y muertos.

[[acts-10-43]]
^43^ De éste todos los profetas dan testimonio de que todo el que cree en él alcanza, por su nombre, el perdón de los pecados».

[[acts-10-44]]
^44^ Estaba Pedro diciendo estas cosas cuando el Espíritu Santo cayó sobre todos los que escuchaban la Palabra.

[[acts-10-45]]
^45^ Y los fieles circuncisos que habían venido con Pedro quedaron atónitos al ver que el don del Espíritu Santo había sido derramado también sobre los gentiles,

[[acts-10-46]]
^46^ pues les oían hablar en lenguas y glorificar a Dios. Entonces Pedro dijo:

[[acts-10-47]]
^47^ «¿Acaso puede alguno negar el agua del bautismo a éstos que han recibido el Espíritu Santo como nosotros?»

[[acts-10-48]]
^48^ Y mandó que fueran bautizados en el nombre de Jesucristo. Entonces le pidieron que se quedase algunos días.
[[acts-11]]
== Capítulo 11

[[acts-11-1]]
^1^ Los apóstoles y los hermanos que había por Judea oyeron que también los gentiles habían aceptado la Palabra de Dios;

[[acts-11-2]]
^2^ así que cuando Pedro subió a Jerusalén, los de la circuncisión se lo reprochaban,

[[acts-11-3]]
^3^ diciéndole: «Has entrado en casa de incircuncisos y has comido con ellos».

[[acts-11-4]]
^4^ Pedro entonces se puso a explicarles punto por punto diciendo:

[[acts-11-5]]
^5^ «Estaba yo en oración en la ciudad de Joppe y en éxtasis vi una visión: una cosa así como un lienzo, atado por las cuatro puntas, que bajaba del cielo y llegó hasta mí.

[[acts-11-6]]
^6^ Lo miré atentamente y vi en él los cuadrúpedos de la tierra, las bestias, los reptiles, y las aves del cielo.

[[acts-11-7]]
^7^ Oí también una voz que me decía: “Pedro, levántate, sacrifica y come.”

[[acts-11-8]]
^8^ Y respondí: “De ninguna manera, Señor; pues jamás entró en mi boca nada profano ni impuro.”

[[acts-11-9]]
^9^ Me dijo por segunda vez la voz venida del cielo: “Lo que Dios ha purificado no lo llames tú profano.”

[[acts-11-10]]
^10^ Esto se repitió hasta tres veces; y al fin fue retirado todo de nuevo al cielo.

[[acts-11-11]]
^11^ «En aquel momento se presentaron tres hombres en la casa donde nosotros estábamos, enviados a mí desde Cesarea.

[[acts-11-12]]
^12^ El Espíritu me dijo que fuera con ellos sin dudar. Fueron también conmigo estos seis hermanos, y entramos en la casa de aquel hombre.

[[acts-11-13]]
^13^ El nos contó cómo había visto un ángel que se presentó en su casa y le dijo: “Manda a buscar en Joppe a Simón, llamado Pedro,

[[acts-11-14]]
^14^ quien te dirá palabras que traerán la salvación para ti y para toda tu casa.”

[[acts-11-15]]
^15^ «Había empezado yo a hablar cuando cayó sobre ellos el Espíritu Santo, como al principio había caído sobre nosotros.

[[acts-11-16]]
^16^ Me acordé entonces de aquellas palabras que dijo el Señor: Juan bautizó con agua, pero vosotros seréis bautizados con el Espíritu Santo.

[[acts-11-17]]
^17^ Por tanto, si Dios les ha concedido el mismo don que a nosotros, por haber creído en el Señor Jesucristo, ¿quién era yo para poner obstáculos a Dios?»

[[acts-11-18]]
^18^ Al oír esto se tranquilizaron y glorificaron a Dios diciendo: «Así pues, también a los gentiles les ha dado Dios la conversión que lleva a la vida».

[[acts-11-19]]
^19^ Los que se habían dispersado cuando la tribulación originada a la muerte de Esteban, llegaron en su recorrido hasta Fenicia, Chipre y Antioquía, sin predicar la Palabra a nadie más que a los judíos.

[[acts-11-20]]
^20^ Pero había entre ellos algunos chipriotas y cirenenses que, venidos a Antioquía, hablaban también a los griegos y les anunciaban la Buena Nueva del Señor Jesús.

[[acts-11-21]]
^21^ La mano del Señor estaba con ellos, y un crecido número recibió la fe y se convirtió al Señor.

[[acts-11-22]]
^22^ La noticia de esto llegó a oídos de la Iglesia de Jerusalén y enviaron a Bernabé a Antioquía.

[[acts-11-23]]
^23^ Cuando llegó y vio la gracia de Dios se alegró y exhortaba a todos a permanecer, con corazón firme, unidos al Señor,

[[acts-11-24]]
^24^ porque era un hombre bueno, lleno de Espíritu Santo y de fe. Y una considerable multitud se agregó al Señor.

[[acts-11-25]]
^25^ Partió para Tarso en busca de Saulo,

[[acts-11-26]]
^26^ y en cuanto le encontró, le llevó a Antioquía. Estuvieron juntos durante un año entero en la Iglesia y adoctrinaron a una gran muchedumbre. En Antioquía fue donde, por primera vez, los discípulos recibieron el nombre de «cristianos».

[[acts-11-27]]
^27^ Por aquellos días bajaron unos profetas de Jerusalén a Antioquía.

[[acts-11-28]]
^28^ Uno de ellos, llamado Agabo, movido por el Espíritu, se levantó y profetizó que vendría una gran hambre sobre toda la tierrra, la que hubo en tiempo de Claudio.

[[acts-11-29]]
^29^ Los discípulos determinaron enviar algunos recursos, según las posibilidades de cada uno, para los hermanos que vivían en Judea.

[[acts-11-30]]
^30^ Así lo hicieron y se los enviaron a los presbíteros por medio de Bernabé y de Saulo.
[[acts-12]]
== Capítulo 12

[[acts-12-1]]
^1^ Por aquel tiempo el rey Herodes echó mano a algunos de la Iglesia para maltratarlos.

[[acts-12-2]]
^2^ Hizo morir por la espada a Santiago, el hermano de Juan.

[[acts-12-3]]
^3^ Al ver que esto les gustaba a los judíos, llegó también a prender a Pedro. Eran los días de los Azimos.

[[acts-12-4]]
^4^ Le apresó, pues, le encarceló y le confió a cuatro escuadras de cuatro soldados para que le custodiasen, con la intención de presentarle delante del pueblo después de la Pascua.

[[acts-12-5]]
^5^ Así pues, Pedro estaba custodiado en la cárcel, mientras la Iglesia oraba insistentemente por él a Dios.

[[acts-12-6]]
^6^ Cuando ya Herodes le iba a presentar, aquella misma noche estaba Pedro durmiendo entre dos soldados, atado con dos cadenas; también había ante la puerta unos centinelas custodiando la cárcel.

[[acts-12-7]]
^7^ De pronto se presentó el Angel del Señor y la celda se llenó de luz. Le dio el ángel a Pedro en el costado, le despertó y le dijo: «Levántate aprisa». Y cayeron las cadenas de sus manos.

[[acts-12-8]]
^8^ Le dijo el ángel: «Cíñete y cálzate las sandalias». Así lo hizo. Añadió: «Ponte el manto y sígueme».

[[acts-12-9]]
^9^ Y salió siguiéndole. No acababa de darse cuenta de que era verdad cuanto hacía el ángel, sino que se figuraba ver una visión.

[[acts-12-10]]
^10^ Pasaron la primera y segunda guardia y llegaron a la puerta de hierro que daba a la ciudad. Esta se les abrió por sí misma. Salieron y anduvieron hasta el final de una calle. Y de pronto el ángel le dejó.

[[acts-12-11]]
^11^ Pedro volvió en sí y dijo: «Ahora me doy cuenta realmente de que el Señor ha enviado su ángel y me ha arrancado de las manos de Herodes y de todo lo que esperaba el pueblo de los judíos».

[[acts-12-12]]
^12^ Consciente de su situación, marchó a casa de María, madre de Juan, por sobrenombre Marcos, donde se hallaban muchos reunidos en oración.

[[acts-12-13]]
^13^ Llamó él a la puerta y salió a abrirle una sirvienta llamada Rode;

[[acts-12-14]]
^14^ quien, al reconocer la voz de Pedro, de pura alegría no abrió la puerta, sino que entró corriendo a anunciar que Pedro estaba a la puerta.

[[acts-12-15]]
^15^ Ellos le dijeron: «Estás loca». Pero ella continuaba afirmando que era verdad. Entonces ellos dijeron: «Será su ángel».

[[acts-12-16]]
^16^ Pedro entretanto seguía llamando. Al abrirle, le vieron, y quedaron atónitos.

[[acts-12-17]]
^17^ El les hizo señas con la mano para que callasen y les contó cómo el Señor le había sacado de la prisión. Y añadió: «Comunicad esto a Santiago y a los hermanos». Salió y marchó a otro lugar.

[[acts-12-18]]
^18^ Cuando vino el día hubo un alboroto no pequeño entre los soldados, sobre qué habría sido de Pedro.

[[acts-12-19]]
^19^ Herodes le hizo buscar y al no encontrarle, procesó a los guardias y mandó ejecutarlos. Después bajó de Judea a Cesarea y se quedó allí.

[[acts-12-20]]
^20^ Estaba Herodes fuertemente irritado con los de Tiro y Sidón. Estos, de común acuerdo, se le presentaron y habiéndose ganado a Blasto, camarlengo del rey, solicitaban hacer las paces, pues su país se abastecía del país del rey.

[[acts-12-21]]
^21^ El día señalado, Herodes, regiamente vestido y sentado en la tribuna, les arengaba.

[[acts-12-22]]
^22^ Entonces el pueblo se puso a aclamarle: «¡Es un dios el que habla, no un hombre!»

[[acts-12-23]]
^23^ Pero inmediatamente le hirió el Angel del Señor porque no había dado la gloria a Dios; y convertido en pasto de gusanos, expiró.

[[acts-12-24]]
^24^ Entretanto la Palabra de Dios crecía y se multiplicaba.

[[acts-12-25]]
^25^ Bernabé y Saulo volvieron, una vez cumplido su ministerio en Jerusalén, trayéndose consigo a Juan, por sobrenombre Marcos.
[[acts-13]]
== Capítulo 13

[[acts-13-1]]
^1^ Había en la Iglesia fundada en Antioquía profetas y maestros: Bernabé, Simeón llamado Níger, Lucio el cirenense, Manahén, hermano de leche del tetrarca Herodes, y Saulo.

[[acts-13-2]]
^2^ Mientras estaban celebrando el culto del Señor y ayunando, dijo el Espíritu Santo: «Separadme ya a Bernabé y a Saulo para la obra a la que los he llamado».

[[acts-13-3]]
^3^ Entonces, después de haber ayunado y orado, les impusieron las manos y les enviaron.

[[acts-13-4]]
^4^ Ellos, pues, enviados por el Espíritu Santo, bajaron a Seleucia y de allí navegaron hasta Chipre.

[[acts-13-5]]
^5^ Llegados a Salamina anunciaban la Palabra de Dios en las sinagogas de los judíos. Tenían también a Juan que les ayudaba.

[[acts-13-6]]
^6^ Habiendo atravesado toda la isla hasta Pafos, encontraron a un mago, un falso profeta judío, llamado Bar Jesús,

[[acts-13-7]]
^7^ que estaba con el procónsul Sergio Paulo, hombre prudente. Este hizo llamar a Bernabé y Saulo, deseoso de escuchar la Palabra de Dios.

[[acts-13-8]]
^8^ Pero se les oponía el mago Elimas - pues eso quiere decir su nombre - intentando apartar al procónsul de la fe.

[[acts-13-9]]
^9^ Entonces Saulo, también llamado Pablo, lleno de Espíritu Santo, mirándole fijamente,

[[acts-13-10]]
^10^ le dijo: «Tú, repleto de todo engaño y de toda maldad, hijo del Diablo, enemigo de toda justicia, ¿no acabarás ya de torcer los rectos caminos del Señor?

[[acts-13-11]]
^11^ Pues ahora, mira la mano del Señor sobre ti. Te quedarás ciego y no verás el sol hasta un tiempo determinado». Al instante cayeron sobre él oscuridad y tinieblas y daba vueltas buscando quien le llevase de la mano.

[[acts-13-12]]
^12^ Entonces, viendo lo ocurrido, el procónsul creyó, impresionado por la doctrina del Señor.

[[acts-13-13]]
^13^ Pablo y sus compañeros se hicieron a la mar en Pafos y llegaron a Perge de Panfilia. Pero Juan se separó de ellos y se volvió a Jerusalén,

[[acts-13-14]]
^14^ mientras que ellos, partiendo de Perge, llegaron a Antioquía de Pisidia. El sábado entraron en la sinagoga y tomaron asiento.

[[acts-13-15]]
^15^ Después de la lectura de la Ley y los Profetas, los jefes de la sinagoga les mandaron a decir: «Hermanos, si tenéis alguna palabra de exhortación para el pueblo, hablad».

[[acts-13-16]]
^16^ Pablo se levantó, hizo señal con la mano y dijo: «Israelitas y cuantos teméis a Dios, escuchad:

[[acts-13-17]]
^17^ El Dios de este pueblo, Israel, eligió a nuestros padres, engrandeció al pueblo durante su destierro en la tierra de Egipto y los sacó con su brazo extendido.

[[acts-13-18]]
^18^ Y durante unos cuarenta años los rodeó de cuidados en el desierto;

[[acts-13-19]]
^19^ después, habiendo exterminado siete naciones en la tierra de Canaán, les dio en herencia su tierra,

[[acts-13-20]]
^20^ por unos 450 años. Después de esto les dio jueces hasta el profeta Samuel.

[[acts-13-21]]
^21^ Luego pidieron un rey, y Dios les dio a Saúl, hijo de Cis, de la tribu de Benjamín, durante cuarenta años.

[[acts-13-22]]
^22^ Depuso a éste y les suscitó por rey a David, de quien precisamente dio este testimonio: He encontrado a David, el hijo de Jesé, un hombre según mi corazón, que realizará todo lo que yo quiera.

[[acts-13-23]]
^23^ De la descendencia de éste, Dios, según la Promesa, ha suscitado para Israel un Salvador, Jesús.

[[acts-13-24]]
^24^ Juan predicó como precursor, ante su venida, un bautismo de conversión a todo el pueblo de Israel.

[[acts-13-25]]
^25^ Al final de su carrera, Juan decía: “Yo no soy el que vosotros os pensáis, sino mirad que viene detrás de mí aquel a quien no soy digno de desatar las sandalias de los pies.”

[[acts-13-26]]
^26^ «Hermanos, hijos de la raza de Abraham, y cuantos entre vosotros temen a Dios: a vosotros ha sido enviada esta Palabra de salvación.

[[acts-13-27]]
^27^ Los habitantes de Jerusalén y sus jefes cumplieron, sin saberlo, las Escrituras de los profetas que se leen cada sábado;

[[acts-13-28]]
^28^ y sin hallar en él ningún motivo de muerte pidieron a Pilato que le hiciera morir.

[[acts-13-29]]
^29^ Y cuando hubieron cumplido todo lo que referente a él estaba escrito, le bajaron del madero, y le pusieron en el sepulcro.

[[acts-13-30]]
^30^ Pero Dios le resucitó de entre los muertos.

[[acts-13-31]]
^31^ El se apareció durante muchos días a los que habían subido con él de Galilea a Jerusalén y que ahora son testigos suyos ante el pueblo.

[[acts-13-32]]
^32^ «También nosotros os anunciamos la Buena Nueva de que la Promesa hecha a los padres

[[acts-13-33]]
^33^ Dios la ha cumplido en nosotros, los hijos, al resucitar a Jesús, como está escrito en los salmos: Hijo mío eres tú; yo te he engendrado hoy.

[[acts-13-34]]
^34^ Y que le resucitó de entre los muertos para nunca más volver a la corrupción, lo tiene declarado: Os daré las cosas santas de David, las verdaderas.

[[acts-13-35]]
^35^ Por eso dice también en otro lugar: No permitirás que tu santo experimente la corrupción.

[[acts-13-36]]
^36^ Ahora bien, David, después de haber servido en sus días a los designios de Dios, murió, se reunió con sus padres y experimentó la corrupción.

[[acts-13-37]]
^37^ En cambio aquel a quien Dios resucitó, no experimentó la corrupción.

[[acts-13-38]]
^38^ «Tened, pues, entendido, hermanos, que por medio de éste os es anunciado el perdón de los pecados; y la total justificación que no pudisteis obtener por la Ley de Moisés

[[acts-13-39]]
^39^ la obtiene por él todo el que cree.

[[acts-13-40]]
^40^ Cuidad, pues, de que no sobrevenga lo que dijeron los Profetas:

[[acts-13-41]]
^41^ Mirad, los que despreciáis, asombraos y desapareced, porque en vuestros días yo voy a realizar una obra, que no creeréis aunque os la cuenten».

[[acts-13-42]]
^42^ Al salir les rogaban que les hablasen sobre estas cosas el siguiente sábado.

[[acts-13-43]]
^43^ Disuelta la reunión, muchos judíos y prosélitos que adoraban a Dios siguieron a Pablo y a Bernabé; éstos conversaban con ellos y les persuadían a perseverar fieles a la gracia de Dios.

[[acts-13-44]]
^44^ El sábado siguiente se congregó casi toda la ciudad para escuchar la Palabra de Dios.

[[acts-13-45]]
^45^ Los judíos, al ver a la multitud, se llenaron de envidia y contradecían con blasfemias cuanto Pablo decía.

[[acts-13-46]]
^46^ Entonces dijeron con valentía Pablo y Bernabé: «Era necesario anunciaros a vosotros en primer lugar la Palabra de Dios; pero ya que la rechazáis y vosotros mismos no os juzgáis dignos de la vida eterna, mirad que nos volvemos a los gentiles.

[[acts-13-47]]
^47^ Pues así nos lo ordenó el Señor: Te he puesto como la luz de los gentiles, para que lleves la salvación hasta el fin de la tierra».

[[acts-13-48]]
^48^ Al oír esto los gentiles se alegraron y se pusieron a glorificar la Palabra del Señor; y creyeron cuantos estaban destinados a una vida eterna.

[[acts-13-49]]
^49^ Y la Palabra del Señor se difundía por toda la región.

[[acts-13-50]]
^50^ Pero los judíos incitaron a mujeres distinguidas que adoraban a Dios, y a los principales de la ciudad; promovieron una persecución contra Pablo y Bernabé y les echaron de su territorio.

[[acts-13-51]]
^51^ Estos sacudieron contra ellos el polvo de sus pies y se fueron a Iconio.

[[acts-13-52]]
^52^ Los discípulos quedaron llenos de gozo y del Espíritu Santo.
[[acts-14]]
== Capítulo 14

[[acts-14-1]]
^1^ En Iconio, entraron del mismo modo en la sinagoga de los judíos y hablaron de tal manera que gran multitud de judíos y griegos abrazaron la fe.

[[acts-14-2]]
^2^ Pero los judíos que no habían creído excitaron y envenenaron los ánimos de los gentiles contra los hermanos.

[[acts-14-3]]
^3^ Con todo se detuvieron allí bastante tiempo, hablando con valentía del Señor que les concedía obrar por sus manos señales y prodigios, dando así testimonio de la predicación de su gracia.

[[acts-14-4]]
^4^ La gente de la ciudad se dividió: unos a favor de los judíos y otros a favor de los apóstoles.

[[acts-14-5]]
^5^ Como se alzasen judíos y gentiles con sus jefes para ultrajarles y apedrearles,

[[acts-14-6]]
^6^ al saberlo, huyeron a las ciudades de Licaonia, a Listra y Derbe y sus alrededores.

[[acts-14-7]]
^7^ Y allí se pusieron a anunciar la Buena Nueva.

[[acts-14-8]]
^8^ Había allí, sentado, un hombre tullido de pies, cojo de nacimiento y que nunca había andado.

[[acts-14-9]]
^9^ Este escuchaba a Pablo que hablaba. Pablo fijó en él su mirada y viendo que tenía fe para ser curado,

[[acts-14-10]]
^10^ le dijo con fuerte voz: «Ponte derecho sobre tus pies». Y él dio un salto y se puso a caminar.

[[acts-14-11]]
^11^ La gente, al ver lo que Pablo había hecho, empezó a gritar en licaonio: «Los dioses han bajado hasta nosotros en figura de hombres».

[[acts-14-12]]
^12^ A Bernabé le llamaban Zeus y a Pablo, Hermes, porque era quien dirigía la palabra.

[[acts-14-13]]
^13^ El sacerdote del templo de Zeus que hay a la entrada de la ciudad, trajo toros y guirnaldas delante de las puertas y a una con la gente se disponía a sacrificar.

[[acts-14-14]]
^14^ Al oírlo los apóstoles Bernabé y Pablo, rasgaron sus vestidos y se lanzaron en medio de la gente gritando:

[[acts-14-15]]
^15^ «Amigos, ¿por qué hacéis esto? Nosotros somos también hombres, de igual condición que vosotros, que os predicamos que abandonéis estas cosas vanas y os volváis al Dios vivo que hizo el cielo, la tierra, el mar y cuanto en ellos hay,

[[acts-14-16]]
^16^ y que en las generaciones pasadas permitió que todas las naciones siguieran sus propios caminos;

[[acts-14-17]]
^17^ si bien no dejó de dar testimonio de sí mismo, derramando bienes, enviándoos desde el cielo lluvias y estaciones fructíferas, llenando vuestros corazones de sustento y alegría..».

[[acts-14-18]]
^18^ Con estas palabras pudieron impedir a duras penas que la gente les ofreciera un sacrificio.

[[acts-14-19]]
^19^ Vinieron entonces de Antioquía e Iconio algunos judíos y, habiendo persuadido a la gente, lapidaron a Pablo y le arrastraron fuera de la ciudad, dándole por muerto.

[[acts-14-20]]
^20^ Pero él se levantó y, rodeado de los discípulos, entró en la ciudad. Al día siguiente marchó con Bernabé a Derbe.

[[acts-14-21]]
^21^ Habiendo evangelizado aquella ciudad y conseguido bastantes discípulos, se volvieron a Listra, Iconio y Antioquía,

[[acts-14-22]]
^22^ confortando los ánimos de los discípulos, exhortándoles a perseverar en la fe y diciéndoles: «Es necesario que pasemos por muchas tribulaciones para entrar en el Reino de Dios».

[[acts-14-23]]
^23^ Designaron presbíteros en cada Iglesia y después de hacer oración con ayunos, los encomendaron al Señor en quien habían creído.

[[acts-14-24]]
^24^ Atravesaron Pisidia y llegaron a Panfilia;

[[acts-14-25]]
^25^ predicaron en Perge la Palabra y bajaron a Atalía.

[[acts-14-26]]
^26^ Allí se embarcaron para Antioquía, de donde habían partido encomendados a la gracia de Dios para la obra que habían realizado.

[[acts-14-27]]
^27^ A su llegada reunieron a la Iglesia y se pusieron a contar todo cuanto Dios había hecho juntamente con ellos y cómo había abierto a los gentiles la puerta de la fe.

[[acts-14-28]]
^28^ Y permanecieron no poco tiempo con los discípulos.
[[acts-15]]
== Capítulo 15

[[acts-15-1]]
^1^ Bajaron algunos de Judea que enseñaban a los hermanos: «Si no os circuncidáis conforme a la costumbre mosaica, no podéis salvaros».

[[acts-15-2]]
^2^ Se produjo con esto una agitación y una discusión no pequeña de Pablo y Bernabé contra ellos; y decidieron que Pablo y Bernabé y algunos de ellos subieran a Jerusalén, donde los apóstoles y presbíteros, para tratar esta cuestión.

[[acts-15-3]]
^3^ Ellos, pues, enviados por la Iglesia, atravesaron Fenicia y Samaria, contando la conversión de los gentiles y produciendo gran alegría en todos los hermanos.

[[acts-15-4]]
^4^ Llegados a Jerusalén fueron recibidos por la Iglesia y por los apóstoles y presbíteros, y contaron cuanto Dios había hecho juntamente con ellos.

[[acts-15-5]]
^5^ Pero algunos de la secta de los fariseos, que habían abrazado la fe, se levantaron para decir que era necesario circuncidar a los gentiles y mandarles guardar la Ley de Moisés.

[[acts-15-6]]
^6^ Se reunieron entonces los apóstoles y presbíteros para tratar este asunto.

[[acts-15-7]]
^7^ Después de una larga discusión, Pedro se levantó y les dijo: «Hermanos, vosotros sabéis que ya desde los primeros días me eligió Dios entre vosotros para que por mi boca oyesen los gentiles la Palabra de la Buena Nueva y creyeran.

[[acts-15-8]]
^8^ Y Dios, conocedor de los corazones, dio testimonio en su favor comunicándoles el Espíritu Santo como a nosotros;

[[acts-15-9]]
^9^ y no hizo distinción alguna entre ellos y nosotros, pues purificó sus corazones con la fe.

[[acts-15-10]]
^10^ ¿Por qué, pues, ahora tentáis a Dios queriendo poner sobre el cuello de los discípulos un yugo que ni nuestros padres ni nosotros pudimos sobrellevar?

[[acts-15-11]]
^11^ Nosotros creemos más bien que nos salvamos por la gracia del Señor Jesús, del mismo modo que ellos».

[[acts-15-12]]
^12^ Toda la asamblea calló y escucharon a Bernabé y a Pablo contar todas las señales y prodigios que Dios había realizado por medio de ellos entre los gentiles.

[[acts-15-13]]
^13^ Cuando terminaron de hablar, tomó Santiago la palabra y dijo: «Hermanos, escuchadme.

[[acts-15-14]]
^14^ Simeón ha referido cómo Dios ya al principio intervino para procurarse entre los gentiles un pueblo para su Nombre.

[[acts-15-15]]
^15^ Con esto concuerdan los oráculos de los Profetas, según está escrito:

[[acts-15-16]]
^16^ «Después de esto volveré y reconstruiré la tienda de David que está caída; reconstruiré sus ruinas, y la volveré a levantar.

[[acts-15-17]]
^17^ Para que el resto de los hombres busque al Señor, y todas las naciones que han sido consagradas a mi nombre, dice el Señor que hace

[[acts-15-18]]
^18^ que estas cosas sean conocidas desde la eternidad.

[[acts-15-19]]
^19^ «Por esto opino yo que no se debe molestar a los gentiles que se conviertan a Dios,

[[acts-15-20]]
^20^ sino escribirles que se abstengan de lo que ha sido contaminado por los ídolos, de la impureza, de los animales estrangulados y de la sangre.

[[acts-15-21]]
^21^ Porque desde tiempos antiguos Moisés tiene en cada ciudad sus predicadores y es leído cada sábado en las sinagogas».

[[acts-15-22]]
^22^ Entonces decidieron los apóstoles y presbíteros, de acuerdo con toda la Iglesia, elegir de entre ellos algunos hombres y enviarles a Antioquía con Pablo y Bernabé; y estos fueron Judas, llamado Barsabás, y Silas, que eran dirigentes entre los hermanos.

[[acts-15-23]]
^23^ Por su medio les enviaron esta carta: «Los apóstoles y los presbíteros hermanos, saludan a los hermanos venidos de la gentilidad que están en Antioquía, en Siria y en Cilicia.

[[acts-15-24]]
^24^ Habiendo sabido que algunos de entre nosotros, sin mandato nuestro, os han perturbado con sus palabras, trastornando vuestros ánimos,

[[acts-15-25]]
^25^ hemos decidido de común acuerdo elegir algunos hombres y enviarlos donde vosotros, juntamente con nuestros queridos Bernabé y Pablo,

[[acts-15-26]]
^26^ que son hombres que han entregado su vida a la causa de nuestro Señor Jesucristo.

[[acts-15-27]]
^27^ Enviamos, pues, a Judas y Silas, quienes os expondrán esto mismo de viva voz:

[[acts-15-28]]
^28^ Que hemos decidido el Espíritu Santo y nosotros no imponeros más cargas que éstas indispensables:

[[acts-15-29]]
^29^ abstenerse de lo sacrificado a los ídolos, de la sangre, de los animales estrangulados y de la impureza. Haréis bien en guardaros de estas cosas. Adiós».

[[acts-15-30]]
^30^ Ellos, después de despedirse, bajaron a Antioquía, reunieron la asamblea y entregaron la carta.

[[acts-15-31]]
^31^ La leyeron y se gozaron al recibir aquel aliento.

[[acts-15-32]]
^32^ Judas y Silas, que eran también profetas, exhortaron con un largo discurso a los hermanos y les confortaron.

[[acts-15-33]]
^33^ Pasado algún tiempo, fueron despedidos en paz por los hermanos para volver a los que los habían enviado.

[[acts-15-35]]
^35^ Pablo y Bernabé se quedaron en Antioquía enseñando y anunciando, en compañía de otros muchos, la Buena Nueva, la palabra del Señor.

[[acts-15-36]]
^36^ Al cabo de algunos días dijo Pablo a Bernabé: «Volvamos ya a ver cómo les va a los hermanos en todas aquellas ciudades en que anunciamos la palabra del Señor».

[[acts-15-37]]
^37^ Bernabé quería llevar también con ellos a Juan, llamado Marcos.

[[acts-15-38]]
^38^ Pablo, en cambio, pensaba que no debían llevar consigo al que se había separado de ellos en Panfilia y no les había acompañado en la obra.

[[acts-15-39]]
^39^ Se produjo entonces una tirantez tal que acabaron por separarse el uno del otro: Bernabé tomó consigo a Marcos y se embarcó rumbo a Chipre;

[[acts-15-40]]
^40^ por su parte Pablo eligió por compañero a Silas y partió, encomendado por los hermanos a la gracia de Dios.

[[acts-15-41]]
^41^ Recorrió Siria y Cilicia consolidando las Iglesias».
[[acts-16]]
== Capítulo 16

[[acts-16-1]]
^1^ Llegó también a Derbe y Listra. Había allí un discípulo llamado Timoteo, hijo de una mujer judía creyente y de padre griego.

[[acts-16-2]]
^2^ Los hermanos de Listra e Iconio daban de él un buen testimonio.

[[acts-16-3]]
^3^ Pablo quiso que se viniera con él. Le tomó y le circuncidó a causa de los judíos que había por aquellos lugares, pues todos sabían que su padre era griego.

[[acts-16-4]]
^4^ Conforme iban pasando por las ciudades, les iban entregando, para que las observasen, las decisiones tomadas por los apóstoles y presbíteros en Jerusalén.

[[acts-16-5]]
^5^ Las Iglesias, pues, se afianzaban en la fe y crecían en número de día en día.

[[acts-16-6]]
^6^ Atravesaron Frigia y la región de Galacia, pues el Espíritu Santo les había impedido predicar la Palabra en Asia.

[[acts-16-7]]
^7^ Estando ya cerca de Misia, intentaron dirigirse a Bitinia, pero no se lo consintió el Espíritu de Jesús.

[[acts-16-8]]
^8^ Atravesaron, pues, Misia y bajaron a Tróada.

[[acts-16-9]]
^9^ Por la noche Pablo tuvo una visión: Un macedonio estaba de pie suplicándole: «Pasa a Macedonia y ayúdanos».

[[acts-16-10]]
^10^ En cuanto tuvo la visión, inmediatamente intentamos pasar a Macedonia, persuadidos de que Dios nos había llamado para evangelizarles.

[[acts-16-11]]
^11^ Nos embarcamos en Tróada y fuimos derechos a Samotracia, y al día siguiente a Neápolis;

[[acts-16-12]]
^12^ de allí pasamos a Filipos, que es una de las principales ciudades de la demarcación de Macedonia, y colonia. En esta ciudad nos detuvimos algunos días.

[[acts-16-13]]
^13^ El sábado salimos fuera de la puerta, a la orilla de un río, donde suponíamos que habría un sitio para orar. Nos sentamos y empezamos a hablar a las mujeres que habían concurrido.

[[acts-16-14]]
^14^ Una de ellas, llamada Lidia, vendedora de púrpura, natural de la ciudad de Tiatira, y que adoraba a Dios, nos escuchaba. El Señor le abrió el corazón para que se adhiriese a las palabras de Pablo.

[[acts-16-15]]
^15^ Cuando ella y los de su casa recibieron el bautismo, suplicó: «Si juzgáis que soy fiel al Señor, venid y quedaos en mi casa». Y nos obligó a ir.

[[acts-16-16]]
^16^ Sucedió que al ir nosotros al lugar de oración, nos vino al encuentro una muchacha esclava poseída de un espíritu adivino, que pronunciando oráculos producía mucho dinero a sus amos.

[[acts-16-17]]
^17^ Nos seguía a Pablo y a nosotros gritando: «Estos hombres son siervos del Dios Altísimo, que os anuncian un camino de salvación».

[[acts-16-18]]
^18^ Venía haciendo esto durante muchos días. Cansado Pablo, se volvió y dijo al espíritu: «En nombre de Jesucristo te mando que salgas de ella». Y en el mismo instante salió.

[[acts-16-19]]
^19^ Al ver sus amos que se les había ido su esperanza de ganancia, prendieron a Pablo y a Silas y los arrastraron hasta el ágora, ante los magistrados;

[[acts-16-20]]
^20^ los presentaron a los pretores y dijeron: «Estos hombres alborotan nuestra ciudad; son judíos

[[acts-16-21]]
^21^ y predican unas costumbres que nosotros, por ser romanos, no podemos aceptar ni practicar».

[[acts-16-22]]
^22^ La gente se amotinó contra ellos; los pretores les hicieron arrancar los vestidos y mandaron azotarles con varas.

[[acts-16-23]]
^23^ Después de haberles dado muchos azotes, los echaron a la cárcel y mandaron al carcelero que los guardase con todo cuidado.

[[acts-16-24]]
^24^ Este, al recibir tal orden, los metió en el calabozo interior y sujetó sus pies en el cepo.

[[acts-16-25]]
^25^ Hacia la media noche Pablo y Silas estaban en oración cantando himnos a Dios; los presos les escuchaban.

[[acts-16-26]]
^26^ De repente se produjo un terremoto tan fuerte que los mismos cimientos de la cárcel se conmovieron. Al momento quedaron abiertas todas las puertas y se soltaron las cadenas de todos.

[[acts-16-27]]
^27^ Despertó el carcelero y al ver las puertas de la cárcel abiertas, sacó la espada e iba a matarse, creyendo que los presos habían huido.

[[acts-16-28]]
^28^ Pero Pablo le gritó: «No te hagas ningún mal, que estamos todos aquí».

[[acts-16-29]]
^29^ El carcelero pidió luz, entró de un salto y tembloroso se arrojó a los pies de Pablo y Silas,

[[acts-16-30]]
^30^ los sacó fuera y les dijo: «Señores, ¿qué tengo que hacer para salvarme?»

[[acts-16-31]]
^31^ Le respondieron: «Ten fe en el Señor Jesús y te salvarás tú y tu casa».

[[acts-16-32]]
^32^ Y le anunciaron la Palabra del Señor a él y a todos los de su casa.

[[acts-16-33]]
^33^ En aquella misma hora de la noche el carcelero los tomó consigo y les lavó las heridas; inmediatamente recibió el bautismo él y todos los suyos.

[[acts-16-34]]
^34^ Les hizo entonces subir a su casa, les preparó la mesa y se alegró con toda su familia por haber creído en Dios.

[[acts-16-35]]
^35^ Llegado el día, los pretores enviaron a los lictores a decir al carcelero: «Pon en libertad a esos hombres».

[[acts-16-36]]
^36^ El carcelero transmitió estas palabras a Pablo: «Los pretores han enviado a decir que os suelte. Ahora, pues, salid y marchad».

[[acts-16-37]]
^37^ Pero Pablo les contestó: «Después de habernos azotado públicamente sin habernos juzgado, a pesar de ser nosotros ciudadanos romanos, nos echaron a la cárcel; ¿y ahora quieren mandarnos de aquí a escondidas? Eso no; que vengan ellos a sacarnos».

[[acts-16-38]]
^38^ Los lictores transmitieron estas palabras a los pretores. Les entró miedo al oír que eran romanos.

[[acts-16-39]]
^39^ Vinieron y les rogaron que saliesen de la ciudad.

[[acts-16-40]]
^40^ Al salir de la cárcel se fueron a casa de Lidia, volvieron a ver a los hermanos, los animaron y se marcharon.
[[acts-17]]
== Capítulo 17

[[acts-17-1]]
^1^ Atravesando Anfípolis y Apolonia llegaron a Tesalónica, donde los judíos tenían una sinagoga.

[[acts-17-2]]
^2^ Pablo, según su costumbre, se dirigió a ellos y durante tres sábados discutió con ellos basándose en las Escrituras,

[[acts-17-3]]
^3^ explicándolas y probando que Cristo tenía que padecer y resucitar de entre los muertos y que «este Cristo es Jesús, a quien yo os anuncio».

[[acts-17-4]]
^4^ Algunos de ellos se convencieron y se unieron a Pablo y Silas así como una gran multitud de los que adoraban a Dios y de griegos y no pocas de las mujeres principales.

[[acts-17-5]]
^5^ Pero los judíos, llenos de envidia, reunieron a gente maleante de la calle, armaron tumultos y alborotaron la ciudad. Se presentaron en casa de Jasón buscándolos para llevarlos ante el pueblo.

[[acts-17-6]]
^6^ Al no encontrarlos, arrastraron a Jasón y a algunos hermanos ante los magistrados de la ciudad gritando: «Esos que han revolucionado todo el mundo se han presentado también aquí,

[[acts-17-7]]
^7^ y Jasón les ha hospedado. Además todos ellos van contra los decretos del César y afirman que hay otro rey, Jesús».

[[acts-17-8]]
^8^ Al oír esto, el pueblo y los magistrados de la ciudad se alborotaron.

[[acts-17-9]]
^9^ Pero después de recibir una fianza de Jasón y de los demás, les dejaron ir.

[[acts-17-10]]
^10^ Inmediatamente, por la noche, los hermanos enviaron hacia Berea a Pablo y Silas. Ellos, al llegar allí, se fueron a la sinagoga de los judíos.

[[acts-17-11]]
^11^ Estos eran de un natural mejor que los de Tesalónica, y aceptaron la palabra de todo corazón. Diariamente examinaban las Escrituras para ver si las cosas eran así.

[[acts-17-12]]
^12^ Creyeron, pues, muchos de ellos y, entre los griegos, mujeres distinguidas y no pocos hombres.

[[acts-17-13]]
^13^ Pero cuando los judíos de Tesalónica se enteraron de que también en Berea había predicado Pablo la Palabra de Dios, fueron también allá, y agitaron y alborotaron a la gente.

[[acts-17-14]]
^14^ Los hermanos entonces hicieron marchar a toda prisa a Pablo hasta el mar; Silas y Timoteo se quedaron allí.

[[acts-17-15]]
^15^ Los que conducían a Pablo le llevaron hasta Atenas y se volvieron con una orden para Timoteo y Silas de que fueran donde él lo antes posible.

[[acts-17-16]]
^16^ Mientras Pablo les esperaba en Atenas, estaba interiormente indignado al ver la ciudad llena de ídolos.

[[acts-17-17]]
^17^ Discutía en la sinagoga con los judíos y con los que adoraban a Dios; y diariamente en el ágora con los que por allí se encontraban.

[[acts-17-18]]
^18^ Trababan también conversación con él algunos filósofos epicúreos y estoicos. Unos decían: «¿Qué querrá decir este charlatán?» Y otros: «Parece ser un predicador de divinidades extranjeras». Porque anunciaba a Jesús y la resurrección.

[[acts-17-19]]
^19^ Le tomaron y le llevaron al Areópago; y le dijeron: «¿Podemos saber cuál es esa nueva doctrina que tú expones?

[[acts-17-20]]
^20^ Pues te oímos decir cosas extrañas y querríamos saber qué es lo que significan».

[[acts-17-21]]
^21^ Todos los atenienses y los forasteros que allí residían en ninguna otra cosa pasaban el tiempo sino en decir u oír la última novedad.

[[acts-17-22]]
^22^ Pablo, de pie en medio del Areópago, dijo: «Atenienses, veo que vosotros sois, por todos los conceptos, los más respetuosos de la divinidad.

[[acts-17-23]]
^23^ Pues al pasar y contemplar vuestros monumentos sagrados, he encontrado también un altar en el que estaba grabada esta inscripción: «Al Dios desconocido». Pues bien, lo que adoráis sin conocer, eso os vengo yo a anunciar.

[[acts-17-24]]
^24^ «El Dios que hizo el mundo y todo lo que hay en él, que es Señor del cielo y de la tierra, no habita en santuarios fabricados por manos humanas,

[[acts-17-25]]
^25^ ni es servido por manos humanas, como si de algo estuviera necesitado, el que a todos da la vida, el aliento y todas las cosas.

[[acts-17-26]]
^26^ El creó, de un solo principio, todo el linaje humano, para que habitase sobre toda la faz de la tierra fijando los tiempos determinados y los límites del lugar donde habían de habitar,

[[acts-17-27]]
^27^ con el fin de que buscasen la divinidad, para ver si a tientas la buscaban y la hallaban; por más que no se encuentra lejos de cada uno de nosotros;

[[acts-17-28]]
^28^ pues en él vivimos, nos movemos y existimos, como han dicho algunos de vosotros: “Porque somos también de su linaje.”

[[acts-17-29]]
^29^ «Si somos, pues, del linaje de Dios, no debemos pensar que la divinidad sea algo semejante al oro, la plata o la piedra, modelados por el arte y el ingenio humano.

[[acts-17-30]]
^30^ «Dios, pues, pasando por alto los tiempos de la ignorancia, anuncia ahora a los hombres que todos y en todas partes deben convertirse,

[[acts-17-31]]
^31^ porque ha fijado el día en que va a juzgar al mundo según justicia, por el hombre que ha destinado, dando a todos una garantía al resucitarlo de entre los muertos».

[[acts-17-32]]
^32^ Al oír la resurrección de los muertos, unos se burlaron y otros dijeron: «Sobre esto ya te oiremos otra vez».

[[acts-17-33]]
^33^ Así salió Pablo de en medio de ellos.

[[acts-17-34]]
^34^ Pero algunos hombres se adhirieron a él y creyeron, entre ellos Dionisio Areopagita, una mujer llamada Damaris y algunos otros con ellos.
[[acts-18]]
== Capítulo 18

[[acts-18-1]]
^1^ Después de esto marchó de Atenas y llegó a Corinto.

[[acts-18-2]]
^2^ Se encontró con un judío llamado Aquila, originario del Ponto, que acababa de llegar de Italia, y con su mujer Priscila, por haber decretado Claudio que todos los judíos saliesen de Roma; se llegó a ellos

[[acts-18-3]]
^3^ y como era del mismo oficio, se quedó a vivir y a trabajar con ellos. El oficio de ellos era fabricar tiendas.

[[acts-18-4]]
^4^ Cada sábado en la sinagoga discutía, y se esforzaba por convencer a judíos y griegos.

[[acts-18-5]]
^5^ Cuando llegaron de Macedonia Silas y Timoteo, Pablo se dedicó enteramente a la Palabra, dando testimonio ante los judíos de que el Cristo era Jesús.

[[acts-18-6]]
^6^ Como ellos se opusiesen y profiriesen blasfemias, sacudió sus vestidos y les dijo: «Vuestra sangre recaiga sobre vuestra cabeza; yo soy inocente y desde ahora me dirigiré a los gentiles».

[[acts-18-7]]
^7^ Entonces se retiró de allí y entró en casa de un tal Justo, que adoraba a Dios, cuya casa estaba contigua a la sinagoga.

[[acts-18-8]]
^8^ Crispo, el jefe de la sinagoga, creyó en el Señor con toda su casa; y otros muchos corintios al oír a Pablo creyeron y recibieron el bautismo.

[[acts-18-9]]
^9^ El Señor dijo a Pablo durante la noche en una visión: «No tengas miedo, sigue hablando y no calles;

[[acts-18-10]]
^10^ porque yo estoy contigo y nadie te pondrá la mano encima para hacerte mal, pues tengo yo un pueblo numeroso en esta ciudad».

[[acts-18-11]]
^11^ Y permaneció allí un año y seis meses, enseñando entre ellos la Palabra de Dios.

[[acts-18-12]]
^12^ Siendo Galión procónsul de Acaya se echaron los judíos de común acuerdo sobre Pablo y le condujeron ante el tribunal

[[acts-18-13]]
^13^ diciendo: «Este persuade a la gente para que adore a Dios de una manera contraria a la Ley».

[[acts-18-14]]
^14^ Iba Pablo a abrir la boca cuando Galión dijo a los judíos: «Si se tratara de algún crimen o mala acción, yo os escucharía, judíos, con calma, como es razón.

[[acts-18-15]]
^15^ Pero como se trata de discusiones sobre palabras y nombres y cosas de vuestra Ley, allá vosotros. Yo no quiero ser juez en estos asuntos».

[[acts-18-16]]
^16^ Y los echó del tribunal.

[[acts-18-17]]
^17^ Entonces todos ellos agarraron a Sóstenes, el jefe de la sinagoga, y se pusieron a golpearlo ante el tribunal sin que a Galión le diera esto ningún cuidado.

[[acts-18-18]]
^18^ Pablo se quedó allí todavía bastantes días; después se despidió de los hermanos y se embarcó rumbo a Siria; con él iban Priscila y Aquila. En Cencreas se había cortado el pelo porque tenía hecho un voto.

[[acts-18-19]]
^19^ Arribaron a Efeso y allí se separó de ellos. Entró en la sinagoga y se puso a discutir con los judíos.

[[acts-18-20]]
^20^ Le rogaron que se quedase allí más tiempo, pero no accedió,

[[acts-18-21]]
^21^ sino que se despidió diciéndoles: «Volveré a vosotros otra vez, si Dios quiere». Y embarcándose marchó de Efeso.

[[acts-18-22]]
^22^ Desembarcó en Cesarea, subió a saludar a la Iglesia y después bajó a Antioquía.

[[acts-18-23]]
^23^ Después de pasar allí algún tiempo marchó a recorrer una tras otra las regiones de Galacia y Frigia para fortalecer a todos los discípulos.

[[acts-18-24]]
^24^ Un judío, llamado Apolo, originario de Alejandría, hombre elocuente, que dominaba las Escrituras, llegó a Efeso.

[[acts-18-25]]
^25^ Había sido instruido en el Camino del Señor y con fervor de espíritu hablaba y enseñaba con todo esmero lo referente a Jesús, aunque solamente conocía el bautismo de Juan.

[[acts-18-26]]
^26^ Este, pues, comenzó a hablar con valentía en la sinagoga. Al oírle Aquila y Priscila, le tomaron consigo y le expusieron más exactamente el Camino.

[[acts-18-27]]
^27^ Queriendo él pasar a Acaya, los hermanos le animaron a ello y escribieron a los discípulos para que le recibieran. Una vez allí fue de gran provecho, con el auxilio de la gracia, a los que habían creído;

[[acts-18-28]]
^28^ pues refutaba vigorosamente en público a los judíos, demostrando por las Escrituras que el Cristo era Jesús.
[[acts-19]]
== Capítulo 19

[[acts-19-1]]
^1^ Mientras Apolo estaba en Corinto, Pablo atravesó las regiones altas y llegó a Efeso donde encontró algunos discípulos;

[[acts-19-2]]
^2^ les preguntó: «¿Recibisteis el Espíritu Santo cuando abrazasteis la fe?» Ellos contestaron: «Pero si nosotros no hemos oído decir siquiera que exista el Espíritu Santo».

[[acts-19-3]]
^3^ El replicó: «¿Pues qué bautismo habéis recibido?» - «El bautismo de Juan», respondieron.

[[acts-19-4]]
^4^ Pablo añadió: «Juan bautizó con un bautismo de conversión, diciendo al pueblo que creyesen en el que había de venir después de él, o sea en Jesús».

[[acts-19-5]]
^5^ Cuando oyeron esto, fueron bautizados en el nombre del Señor Jesús.

[[acts-19-6]]
^6^ Y, habiéndoles Pablo impuesto las manos, vino sobre ellos el Espíritu Santo y se pusieron a hablar en lenguas y a profetizar.

[[acts-19-7]]
^7^ Eran en total unos doce hombres.

[[acts-19-8]]
^8^ Entró en la sinagoga y durante tres meses hablaba con valentía, discutiendo acerca del Reino de Dios e intentando convencerles.

[[acts-19-9]]
^9^ Pero como algunos, obstinados e incrédulos, hablaban mal del Camino ante la gente, rompió con ellos y formó grupo aparte con los discípulos; y diariamente les hablaba en la escuela de Tirano.

[[acts-19-10]]
^10^ Esto duró dos años, de forma que pudieron oír la Palabra del Señor todos los habitantes de Asia, tanto judíos como griegos.

[[acts-19-11]]
^11^ Dios obraba por medio de Pablo milagros no comunes,

[[acts-19-12]]
^12^ de forma que bastaba aplicar a los enfermos los pañuelos o mandiles que había usado y se alejaban de ellos las enfermedades y salían los espíritus malos.

[[acts-19-13]]
^13^ Algunos exorcistas judíos ambulantes intentaron también invocar el nombre del Señor Jesús sobre los que tenían espíritus malos, y decían: «Os conjuro por Jesús a quien predica Pablo».

[[acts-19-14]]
^14^ Eran siete hijos de un tal Esceva, sumo sacerdote judío, los que hacían esto.

[[acts-19-15]]
^15^ Pero el espíritu malo les respondió: «A Jesús le conozco y sé quién es Pablo; pero vosotros, ¿quiénes sois?»

[[acts-19-16]]
^16^ Y arrojándose sobre ellos el hombre poseído del mal espíritu, dominó a unos y otros y pudo con ellos de forma que tuvieron que huir de aquella casa desnudos y cubiertos de heridas.

[[acts-19-17]]
^17^ Llegaron a enterarse de esto todos los habitantes de Efeso, tanto judíos como griegos. El temor se apoderó de todos ellos y fue glorificado el nombre del Señor Jesús.

[[acts-19-18]]
^18^ Muchos de los que habían creído venían a confesar y declarar sus prácticas.

[[acts-19-19]]
^19^ Bastantes de los que habían practicado la magia reunieron los libros y los quemaron delante de todos. Calcularon el precio de los libros y hallaron que subía a 50.000 monedas de plata.

[[acts-19-20]]
^20^ De esta forma la Palabra del Señor crecía y se robustecía poderosamente.

[[acts-19-21]]
^21^ Después de estos sucesos, Pablo tomó la decisión de ir a Jerusalén pasando por Macedonia y Acaya. Y decía: «Después de estar allí he de visitar también Roma».

[[acts-19-22]]
^22^ Envió a Macedonia a dos de sus auxiliares, Timoteo y Erasto, mientras él se quedaba algún tiempo en Asia.

[[acts-19-23]]
^23^ Por entonces se produjo un tumulto no pequeño con motivo del Camino.

[[acts-19-24]]
^24^ Cierto platero, llamado Demetrio, que labraba en plata templetes de Artemisa y proporcionaba no pocas ganancias a los artífices,

[[acts-19-25]]
^25^ reunió a éstos y también a los obreros de este ramo y les dijo: «Compañeros, vosotros sabéis que a esta industria debemos el bienestar;

[[acts-19-26]]
^26^ pero estáis viendo y oyendo decir que no solamente en Efeso, sino en casi toda el Asia, ese Pablo persuade y aparta a mucha gente, diciendo que no son dioses los que se fabrican con las manos.

[[acts-19-27]]
^27^ Y esto no solamente trae el peligro de que nuestra profesión caiga en descrédito, sino también de que el templo de la gran diosa Artemisa sea tenido en nada y venga a ser despojada de su grandeza aquella a quien adora toda el Asia y toda la tierra».

[[acts-19-28]]
^28^ Al oír esto, llenos de furor se pusieron a gritar: «¡Grande es la Artemisa de los efesios!»

[[acts-19-29]]
^29^ La ciudad se llenó de confusión. Todos a una se precipitaron en el teatro arrastrando consigo a Gayo y a Aristarco, macedonios, compañeros de viaje de Pablo.

[[acts-19-30]]
^30^ Pablo quiso entrar y presentarse al pueblo, pero se lo impidieron los discípulos.

[[acts-19-31]]
^31^ Incluso algunos asiarcas, que eran amigos suyos, le enviaron a rogar que no se arriesgase a ir al teatro.

[[acts-19-32]]
^32^ Unos girtaban una cosa y otros otra. Había gran confusión en la asamblea y la mayoría no sabía por qué se habían reunido.

[[acts-19-33]]
^33^ Algunos de entre la gente aleccionaron a Alejandro a quien los judíos habían empujado hacia delante. Alejandro pidió silencio con la mano y quería dar explicaciones al pueblo.

[[acts-19-34]]
^34^ Pero al conocer que era judío, todos a una voz se pusieron a gritar durante casi dos horas: «¡Grande es la Artemisa de los efesios!»

[[acts-19-35]]
^35^ Cuando el magistrado logró calmar a la gente, dijo: «Efesios, ¿quién hay que no sepa que la ciudad de los efesios es la guardiana del templo de la gran Artemisa y de su estatua caída del cielo?

[[acts-19-36]]
^36^ Siendo, pues, esto indiscutible, conviene que os calméis y no hagáis nada inconsideradamente.

[[acts-19-37]]
^37^ Habéis traído acá a estos hombres que no son sacrílegos ni blasfeman contra nuestra diosa.

[[acts-19-38]]
^38^ Si Demetrio y los artífices que le acompañan tienen quejas contra alguno, audiencias y procónsules hay; que presenten sus reclamaciones.

[[acts-19-39]]
^39^ Y si tenéis algún otro asunto, se resolverá en la asamblea legal.

[[acts-19-40]]
^40^ Porque, además, corremos peligro de ser acusados de sedición por lo de hoy, no existiendo motivo alguno que nos permita justificar este tumulto». Dicho esto disolvió la asamblea.
[[acts-20]]
== Capítulo 20

[[acts-20-1]]
^1^ Cuando hubo cesado el tumulto, Pablo mandó llamar a los discípulos, los animó, se despidió de ellos y salió camino de Macedonia.

[[acts-20-2]]
^2^ Recorrió aquellas regiones y exhortó a los fieles con largos discursos; después marchó a Grecia.

[[acts-20-3]]
^3^ Pasó allí tres meses. Los judíos tramaron una conjuración contra él cuando estaba a punto de embarcarse para Siria; entonces él tomó la determinación de volver por Macedonia.

[[acts-20-4]]
^4^ Le acompañaban Sópatros, hijo de Pirro, de Berea; Aristarco y Segundo, de Tesalónica; Gayo, de Doberes, y Timoteo; Tíquico y Trófimo, de Asia.

[[acts-20-5]]
^5^ Estos se adelantaron y nos esperaron en Tróada.

[[acts-20-6]]
^6^ Nosotros, después de los días de los Azimos, nos embarcamos en Filipos y al cabo de cinco días nos unimos a ellos en Tróada donde pasamos siete días.

[[acts-20-7]]
^7^ El primer día de la semana, estando nosotros reunidos para la fracción del pan, Pablo, que debía marchar al día siguiente, conversaba con ellos y alargó la charla hasta la media noche.

[[acts-20-8]]
^8^ Había abundantes lámparas en la estancia superior donde estábamos reunidos.

[[acts-20-9]]
^9^ Un joven, llamado Eutico, estaba sentado en el borde de la ventana; un profundo sueño le iba dominando a medida que Pablo alargaba su discurso. Vencido por el sueño se cayó del piso tercero abajo. Lo levantaron ya cadáver.

[[acts-20-10]]
^10^ Bajó Pablo, se echó sobre él y tomándole en sus brazos dijo: «No os inquietéis, pues su alma está en él».

[[acts-20-11]]
^11^ Subió luego; partió el pan y comió; después platicó largo tiempo, hasta el amanecer. Entonces se marchó.

[[acts-20-12]]
^12^ Trajeron al muchacho vivo y se consolaron no poco.

[[acts-20-13]]
^13^ Nosotros nos adelantamos a tomar la nave y partimos hacia Asso, donde habíamos de recoger a Pablo; así lo había él determinado; él iría por tierra.

[[acts-20-14]]
^14^ Cuando nos alcanzó en Asso, le tomamos a bordo y llegamos a Mitilene.

[[acts-20-15]]
^15^ Al día siguiente nos hicimos a la mar y llegamos a la altura de Quíos; al otro día atracamos en Samos y, después de hacer escala en Trogilión, llegamos al día siguiente a Mileto.

[[acts-20-16]]
^16^ Pablo había resuelto pasar de largo por Efeso, para no perder tiempo en Asia. Se daba prisa, porque quería estar, si le era posible, el día de Pentecostés en Jerusalén.

[[acts-20-17]]
^17^ Desde Mileto envió a llamar a los presbíteros de la Iglesia de Efeso.

[[acts-20-18]]
^18^ Cuando llegaron donde él, les dijo: «Vosotros sabéis cómo me comporté siempre con vosotros, desde el primer día que entré en Asia,

[[acts-20-19]]
^19^ sirviendo al Señor con toda humildad y lágrimas y con las pruebas que me vinieron por las asechanzas de los judíos;

[[acts-20-20]]
^20^ cómo no me acobardé cuando en algo podía seros útil; os predicaba y enseñaba en público y por las casas,

[[acts-20-21]]
^21^ dando testimonio tanto a judíos como a griegos para que se convirtieran a Dios y creyeran en nuestro Señor Jesús.

[[acts-20-22]]
^22^ «Mirad que ahora yo, encadenado en el espíritu, me dirijo a Jerusalén, sin saber lo que allí me sucederá;

[[acts-20-23]]
^23^ solamente sé que en cada ciudad el Espíritu Santo me testifica que me aguardan prisiones y tribulaciones.

[[acts-20-24]]
^24^ Pero yo no considero mi vida digna de estima, con tal que termine mi carrera y cumpla el ministerio que he recibido del Señor Jesús, de dar testimonio del Evangelio de la gracia de Dios.

[[acts-20-25]]
^25^ «Y ahora yo sé que ya no volveréis a ver mi rostro ninguno de vosotros, entre quienes pasé predicando el Reino.

[[acts-20-26]]
^26^ Por esto os testifico en el día de hoy que yo estoy limpio de la sangre de todos,

[[acts-20-27]]
^27^ pues no me acobardé de anunciaros todo el designio de Dios.

[[acts-20-28]]
^28^ «Tened cuidado de vosotros y de toda la grey, en medio de la cual os ha puesto el Espíritu Santo como vigilantes para pastorear la Iglesia de Dios, que él se adquirió con la sangre de su propio hijo.

[[acts-20-29]]
^29^ «Yo sé que, después de mi partida, se introducirán entre vosotros lobos crueles que no perdonarán al rebaño;

[[acts-20-30]]
^30^ y también que de entre vosotros mismos se levantarán hombres que hablarán cosas perversas, para arrastrar a los discípulos detrás de sí.

[[acts-20-31]]
^31^ Por tanto, vigilad y acordaos que durante tres años no he cesado de amonestaros día y noche con lágrimas a cada uno de vosotros.

[[acts-20-32]]
^32^ «Ahora os encomiendo a Dios y a la Palabra de su gracia, que tiene poder para construir el edificio y daros la herencia con todos los santificados.

[[acts-20-33]]
^33^ «Yo de nadie codicié plata, oro o vestidos.

[[acts-20-34]]
^34^ Vosotros sabéis que estas manos proveyeron a mis necesidades y a las de mis compañeros.

[[acts-20-35]]
^35^ En todo os he enseñado que es así, trabajando, como se debe socorrer a los débiles y que hay que tener presentes las palabras del Señor Jesús, que dijo: Mayor felicidad hay en dar que en recibir».

[[acts-20-36]]
^36^ Dicho esto se puso de rodillas y oro con todos ellos.

[[acts-20-37]]
^37^ Rompieron entonces todos a llorar y arrojándose al cuello de Pablo, le besaban,

[[acts-20-38]]
^38^ afligidos sobre todo por lo que había dicho: que ya no volverían a ver su rostro. Y fueron acompañandole hasta la nave.
[[acts-21]]
== Capítulo 21

[[acts-21-1]]
^1^ Despidiéndonos de ellos nos hicimos a la mar y navegamos derechamente hasta llegar a Cos; al día siguiente, hasta Rodas, y de allí hasta Pátara.

[[acts-21-2]]
^2^ Encontramos una nave que partía para Fenicia; nos embarcamos y partimos.

[[acts-21-3]]
^3^ Avistamos Chipre y, dejándola a la izquierda, íbamos navegando rumbo a Siria; arribamos a Tiro, pues allí la nave debía dejar su cargamento.

[[acts-21-4]]
^4^ Habiendo encontrado a los discípulos nos quedamos allí siete días. Ellos, iluminados por el Espíritu, decían a Pablo que no subiese a Jerusalén.

[[acts-21-5]]
^5^ Cuando se nos pasaron aquellos días, salimos y nos pusimos en camino. Todos nos acompañaron con sus mujeres e hijos, hasta las afueras de la ciudad. En la playa nos pusimos de rodillas y oramos;

[[acts-21-6]]
^6^ nos despedimos unos de otros y subimos a la nave; ellos se volvieron a sus casas.

[[acts-21-7]]
^7^ Nosotros, terminando la travesía, fuimos de Tiro a Tolemaida; saludamos a los hermanos y nos quedamos un día con ellos.

[[acts-21-8]]
^8^ Al siguiente partimos y llegamos a Cesarea; entramos en casa de Felipe, el evangelista, que era uno de los Siete, y nos hospedamos en su casa.

[[acts-21-9]]
^9^ Tenía éste cuatro hijas vírgenes que profetizaban.

[[acts-21-10]]
^10^ Nos detuvimos allí bastantes días; bajó entre tanto de Judea un profeta llamado Agabo;

[[acts-21-11]]
^11^ se acercó a nosotros, tomó el cinturón de Pablo, se ató sus pies y sus manos y dijo: «Esto dice el Espíritu Santo: Así atarán los judíos en Jerusalén al hombre de quien es este cinturón. Y le entregarán en manos de los gentiles».

[[acts-21-12]]
^12^ Al oír esto nosotros y los de aquel lugar le rogamos que no subiera a Jerusalén.

[[acts-21-13]]
^13^ Entonces Pablo contestó: «¿Por qué habéis de llorar y destrozarme el corazón? Pues yo estoy dispuesto no sólo a ser atado, sino a morir también en Jerusalén por el nombre del Señor Jesús».

[[acts-21-14]]
^14^ Como no se dejaba convencer, dejamos de insistir y dijimos: «Hágase la voluntad del Señor».

[[acts-21-15]]
^15^ Transcurridos estos días y hechos los preparativos de viaje, subimos a Jerusalén.

[[acts-21-16]]
^16^ Venían con nosotros algunos discípulos de Cesarea, que nos llevaron a casa de cierto Mnasón, de Chipre, antiguo discípulo, donde nos habíamos de hospedar.

[[acts-21-17]]
^17^ Llegados a Jerusalén, los hermanos nos recibieron con alegría.

[[acts-21-18]]
^18^ Al día siguiente Pablo, con todos nosotros, fue a casa de Santiago; se reunieron también todos los presbíteros.

[[acts-21-19]]
^19^ Les saludó y les fue exponiendo una a una todas las cosas que Dios había obrado entre los gentiles por su ministerio.

[[acts-21-20]]
^20^ Ellos, al oírle, glorificaban a Dios. Entonces le dijeron: «Ya ves, hermano, cuántos miles y miles de judíos han abrazado la fe, y todos son celosos partidarios de la Ley.

[[acts-21-21]]
^21^ Y han oído decir de ti que enseñas a todos los judíos que viven entre los gentiles que se aparten de Moisés, diciéndoles que no circunciden a sus hijos ni observen las tradiciones.

[[acts-21-22]]
^22^ ¿Qué hacer, pues? Porque va a reunirse la muchedumbre al enterarse de tu venida.

[[acts-21-23]]
^23^ Haz, pues, lo que te vamos a decir: Hay entre nosotros cuatro hombres que tienen un voto que cumplir.

[[acts-21-24]]
^24^ Tómalos y purifícate con ellos; y paga tú por ellos, para que se rapen la cabeza; así todos entenderán que no hay nada de lo que ellos han oído decir de ti; sino que tú también te portas como un cumplidor de la Ley.

[[acts-21-25]]
^25^ En cuanto a los gentiles que han abrazado la fe, ya les escribimos nosotros nuestra decisión: Abstenerse de lo sacrificado a los ídolos, de la sangre, de animal estrangulado y de la impureza».

[[acts-21-26]]
^26^ Entonces Pablo tomó al día siguiente a los hombres, y habiéndose purificado con ellos, entró en el Templo para declarar el cumplimiento del plazo de los días de la purificación cuando se había de presentar la ofrenda por cada uno de ellos.

[[acts-21-27]]
^27^ Cuando estaban ya para cumplirse los siete días, los judíos venidos de Asia le vieron en el Templo, revolvieron a todo el pueblo, le echaron mano

[[acts-21-28]]
^28^ y se pusieron a gritar: «¡Auxilio, hombres de Israel! Este es el hombre que va enseñando a todos por todas partes contra el pueblo, contra la Ley y contra este Lugar; y hasta ha llegado a introducir a unos griegos en el Templo, profanando este Lugar Santo».

[[acts-21-29]]
^29^ Pues habían visto anteriormente con él en la ciudad a Trofimo, de Efeso, a quien creían que Pablo había introducido en el Templo.

[[acts-21-30]]
^30^ Toda la ciudad se alborotó y la gente concurrió de todas partes. Se apoderaron de Pablo y lo arrastraron fuera del Templo; inmediatamente cerraron las puertas.

[[acts-21-31]]
^31^ Intentaban darle muerte, cuando subieron a decir al tribuno de la cohorte: «Toda Jerusalén está revuelta».

[[acts-21-32]]
^32^ Inmediatamente tomó consigo soldados y centuriones y bajó corriendo hacia ellos; y ellos al ver al tribuno y a los soldados, dejaron de golpear a Pablo.

[[acts-21-33]]
^33^ Entonces el tribuno se acercó, le prendió y mandó que le atasen con dos cadenas; y empezó a preguntar quién era y qué había hecho.

[[acts-21-34]]
^34^ Pero entre la gente unos gritaban una cosa y otros otra. Como no pudiese sacar nada en claro a causa del alboroto, mandó que le llevasen al cuartel.

[[acts-21-35]]
^35^ Cuando llegó a las escaleras, tuvo que ser llevado a hombros por los soldados a causa de la violencia de la gente;

[[acts-21-36]]
^36^ pues toda la multitud le iba siguiendo y gritando: «¡Mátale!»

[[acts-21-37]]
^37^ Cuando iban ya a meterle en el cuartel, Pablo dijo al tribuno: «¿Me permites decirte una palabra?» El le contestó: «Pero, ¿sabes griego?

[[acts-21-38]]
^38^ ¿No eres tú entonces el egipcio que estos últimos días ha amotinado y llevado al desierto a los 4.000 terroristas?»

[[acts-21-39]]
^39^ Pablo dijo: «Yo soy un judío, de Tarso, ciudadano de una ciudad no oscura de Cilicia. Te ruego que me permitas hablar al pueblo».

[[acts-21-40]]
^40^ Se lo permitió. Pablo, de pie sobre las escaleras, pidió con la mano silencio al pueblo. Y haciéndose un gran silencio, les dirigió la palabra en lengua hebrea.
[[acts-22]]
== Capítulo 22

[[acts-22-1]]
^1^ «Hermanos y padres, escuchad la defensa que ahora hago ante vosotros».

[[acts-22-2]]
^2^ Al oír que les hablaba en lengua hebrea guardaron más profundo silencio. Y dijo:

[[acts-22-3]]
^3^ «Yo soy judío, nacido en Tarso de Cilicia, pero educado en esta ciudad, instruido a los pies de Gamaliel en la exacta observancia de la Ley de nuestros padres; estaba lleno de celo por Dios, como lo estáis todos vosotros el día de hoy.

[[acts-22-4]]
^4^ Yo perseguí a muerte a este Camino, encadenando y arrojando a la cárcel a hombres y mujeres,

[[acts-22-5]]
^5^ como puede atestiguármelo el Sumo Sacerdote y todo el Consejo de ancianos. De ellos recibí también cartas para los hermanos de Damasco y me puse en camino con intención de traer también encadenados a Jerusalén a todos los que allí había, para que fueran castigados.

[[acts-22-6]]
^6^ «Pero yendo de camino, estando ya cerca de Damasco, hacia el mediodía, me envolvió de repente una gran luz venida del cielo;

[[acts-22-7]]
^7^ caí al suelo y oí una voz que me decía: “Saúl, Saúl, ¿por qué me persigues?”

[[acts-22-8]]
^8^ Yo respondí: “¿Quién eres, Señor?” Y él a mí: “Yo soy Jesús Nazoreo, a quien tú persigues.”

[[acts-22-9]]
^9^ Los que estaban vieron la luz, pero no oyeron la voz del que me hablaba.

[[acts-22-10]]
^10^ Yo dije: “¿Qué he de hacer, Señor?” Y el Señor me respondió: “Levántate y vete a Damasco; allí se te dirá todo lo que está establecido que hagas.”

[[acts-22-11]]
^11^ Como yo no veía, a causa del resplandor de aquella luz, conducido de la mano por mis compañeros llegué a Damasco.

[[acts-22-12]]
^12^ «Un tal Ananías, hombre piadoso según la Ley, bien acreditado por todos los judíos que habitaban allí,

[[acts-22-13]]
^13^ vino a verme, y presentándose ante mí me dijo: “Saúl, hermano, recobra la vista.” Y en aquel momento le pude ver.

[[acts-22-14]]
^14^ El me dijo: “El Dios de nuestros padres te ha destinado para que conozcas su voluntad, veas al Justo y escuches la voz de sus labios,

[[acts-22-15]]
^15^ pues le has de ser testigo ante todos los hombres de lo que has visto y oído.

[[acts-22-16]]
^16^ Y ahora, ¿qué esperas? Levántate, recibe el bautismo y lava tus pecados invocando su nombre.”

[[acts-22-17]]
^17^ «Habiendo vuelto a Jerusalén y estando en oración en el Templo, caí en éxtasis;

[[acts-22-18]]
^18^ y le vi a él que me decía: “Date prisa y marcha inmediatamente de Jerusalén, pues no recibirán tu testimonio acerca de mí.”

[[acts-22-19]]
^19^ Yo respondí: “Señor, ellos saben que yo andaba por las sinagogas encarcelando y azotando a los que creían en ti;

[[acts-22-20]]
^20^ y cuando se derramó la sangre de tu testigo Esteban, yo también me hallaba presente, y estaba de acuerdo con los que le mataban y guardaba sus vestidos.”

[[acts-22-21]]
^21^ Y me dijo: “Marcha, porque yo te enviaré lejos, a los gentiles”».

[[acts-22-22]]
^22^ Le estuvieron escuchando hasta estas palabras y entonces alzaron sus voces diciendo: «¡Quita a ése de la tierra!; ¡no es justo que viva!»

[[acts-22-23]]
^23^ Vociferaban, agitaban sus vestidos y arrojaban polvo al aire.

[[acts-22-24]]
^24^ El tribuno mandó llevarlo dentro del cuartel y dijo que lo sometieran a los azotes para averiguar por qué motivo gritaban así contra él.

[[acts-22-25]]
^25^ Cuando le tenían estirado con las correas, dijo Pablo al centurión que estaba allí: «¿Os es lícito azotar a un ciudadano romano sin haberle juzgado?»

[[acts-22-26]]
^26^ Al oír esto el centurión fue donde el tribuno y le dijo: «¿Qué vas a hacer? Este hombre es ciudadano romano».

[[acts-22-27]]
^27^ Acudió el tribuno y le preguntó: «Dime, ¿eres ciudadano romano?» - «Sí», respondió.

[[acts-22-28]]
^28^ - «Yo, dijo el tribuno, conseguí esta ciudadanía por una fuerte suma». - «Pues yo, contestó Pablo, la tengo por nacimiento».

[[acts-22-29]]
^29^ Al momento se retiraron los que iban a darle tormento. El tribuno temió al darse cuenta que le había encadenado siendo ciudadano romano.

[[acts-22-30]]
^30^ Al día siguiente, queriendo averiguar con certeza de qué le acusaban los judíos, le sacó de la cárcel y mandó que se reunieran los sumos sacerdotes y todo el Sanedrín; hizo bajar a Pablo y le puso ante ellos.
[[acts-23]]
== Capítulo 23

[[acts-23-1]]
^1^ Pablo miró fijamente al Sanedrín y dijo: «Hermanos, yo me he portado con entera buena conciencia ante Dios, hasta este día».

[[acts-23-2]]
^2^ Pero el Sumo Sacerdote Ananías mandó a los que le asistían que le golpeasen en la boca.

[[acts-23-3]]
^3^ Entonces Pablo le dijo: «¡Dios te golpeará a ti, pared blanqueada! ¿Tú te sientas para juzgarme conforme la Ley y mandas, violando la Ley, que me golpeen?»

[[acts-23-4]]
^4^ Pero los que estaban a su lado le dijeron: «¿Insultas al Sumo Sacerdote de Dios?»

[[acts-23-5]]
^5^ Pablo contestó: «No sabía, hermanos, que fuera el Sumo Sacerdote; pues está escrito: No injuriarás al jefe de tu pueblo».

[[acts-23-6]]
^6^ Pablo, dándose cuenta de que una parte eran saduceos y la otra fariseos, gritó en medio del Sanedrín: «Hermanos, yo soy fariseo, hijo de fariseos; por esperar la resurrección de los muertos se me juzga».

[[acts-23-7]]
^7^ Al decir él esto, se produjo un altercado entre fariseos y saduceos y la asamblea se dividió.

[[acts-23-8]]
^8^ Porque los saduceos dicen que no hay resurrección, ni ángel, ni espíritu; mientras que los fariseos profesan todo eso.

[[acts-23-9]]
^9^ Se levantó, pues, un gran griterío. Se pusieron en pie algunos escribas del partido de los fariseos y se oponían diciendo: «Nosotros no hallamos nada malo en este hombre. ¿Y si acaso le habló algún espíritu o un ángel?»

[[acts-23-10]]
^10^ Como el altercado iba creciendo, temió el tribuno que Pablo fuese despedazado por ellos y mandó a la tropa que bajase, que le arrancase de entre ellos y le llevase al cuartel.

[[acts-23-11]]
^11^ A la noche siguiente se le apareció el Señor y le dijo: «¡Animo!, pues como has dado testimonio de mí en Jerusalén, así debes darlo también en Roma».

[[acts-23-12]]
^12^ Al amanecer, los judíos se confabularon y se comprometieron bajo anatema a no comer ni beber hasta que hubieran matado a Pablo.

[[acts-23-13]]
^13^ Eran más de cuarenta los comprometidos en esta conjuración.

[[acts-23-14]]
^14^ Estos, pues, se presentaron a los sumos sacerdotes y a los ancianos y le dijeron: «Bajo anatema nos hemos comprometido a no probar cosa alguna hasta que no hayamos dado muerte a Pablo.

[[acts-23-15]]
^15^ Vosotros por vuestra parte, de acuerdo con el Sanedrín, indicad al tribuno que os lo baje donde vosotros, como si quisierais examinar más a fondo su caso; nosotros estamos dispuestos a matarle antes de que llegue».

[[acts-23-16]]
^16^ El hijo de la hermana de Pablo se enteró de la celada. Se presentó en el cuartel, entró y se lo contó a Pablo.

[[acts-23-17]]
^17^ Pablo llamó a uno de los centuriones y le dijo: «Lleva a este joven donde el tribuno, pues tiene algo que contarle».

[[acts-23-18]]
^18^ El tomó y le presentó al tribuno diciéndole: «Pablo, el preso, me llamó y me rogó que te trajese este joven que tiene algo que decirte».

[[acts-23-19]]
^19^ El tribuno le tomó de la mano, le llevó aparte y le preguntó: «¿Qué es lo que tienes que contarme?»

[[acts-23-20]]
^20^ - «Los judíos, contestó, se han concertado para pedirte que mañana bajes a Pablo al Sanedrín con el pretexto de hacer una indagación más a fondo sobre él.

[[acts-23-21]]
^21^ Pero tú no les hagas caso, pues le preparan una celada más de cuarenta hombres de entre ellos, que se han comprometido bajo anatema a no comer ni beber hasta haberle dado muerte; y ahora están preparados, esperando tu asentimiento».

[[acts-23-22]]
^22^ El tribuno despidió al muchacho dándole esta recomendación: «No digas a nadie que me has denunciado estas cosas».

[[acts-23-23]]
^23^ Después llamó a dos centuriones y les dijo: «Tened preparados para la tercera hora de la noche doscientos soldados, para ir a Cesarea, setenta de caballería y doscientos lanceros.

[[acts-23-24]]
^24^ Preparad también cabalgaduras para que monte Pablo; y llevadlo a salvo al procurador Félix».

[[acts-23-25]]
^25^ Y escribió una carta en estos términos:

[[acts-23-26]]
^26^ «Claudio Lisias saluda al excelentísimo procurador Félix».

[[acts-23-27]]
^27^ Este hombre había sido apresado por los judíos y estaban a punto de matarlo cuando, al saber que era romano, acudí yo con la tropa y le libré de sus manos.

[[acts-23-28]]
^28^ Queriendo averiguar el crimen de que le acusaban, le bajé a su Sanedrín.

[[acts-23-29]]
^29^ Y hallé que le acusaban sobre cuestiones de su Ley, pero que no tenía ningún cargo digno de muerte o de prisión.

[[acts-23-30]]
^30^ Pero habiéndome llegado el aviso de que se preparaba una celada contra este hombre, al punto te lo he mandado y he informado además a sus acusadores que formulen sus quejas contra él ante ti».

[[acts-23-31]]
^31^ Los soldados, conforme a lo que se les había ordenado, tomaron a Pablo y lo condujeron de noche a Antipátrida;

[[acts-23-32]]
^32^ a la mañana siguiente dejaron que los de caballería se fueran con él y ellos se volvieron al cuartel.

[[acts-23-33]]
^33^ Al llegar aquéllos a Cesarea, entregaron la carta al procurador y le presentaron también a Pablo.

[[acts-23-34]]
^34^ Habiéndola leído, preguntó de qué provincia era y, al saber que era de Cilicia, le dijo:

[[acts-23-35]]
^35^ «Te oiré cuando estén también presentes tus acusadores». Y mandó custodiarle en el pretorio de Herodes.
[[acts-24]]
== Capítulo 24

[[acts-24-1]]
^1^ Cinco días después bajó el Sumo Sacerdote Ananías con algunos ancianos y un tal Tértulo, abogado, y presentaron ante el procurador acusación contra Pablo.

[[acts-24-2]]
^2^ Citado Pablo, Tértulo dio principio a la acusación diciendo: «Gracias a ti gozamos de mucha paz y las mejoras realizadas por tu providencia en beneficio de esta nación,

[[acts-24-3]]
^3^ en todo y siempre las reconocemos, excelentísimo Félix, con todo agradecimiento.

[[acts-24-4]]
^4^ Pero para no molestarte más, te ruego que nos escuches un momento con tu característica clemencia.

[[acts-24-5]]
^5^ Hemos encontrado esta peste de hombre que provoca altercados entre los judíos de toda la tierra y que es el jefe principal de la secta de los nazoreos.

[[acts-24-6]]
^6^ Ha intentado además profanar el Templo, pero nosotros le apresamos.

[[acts-24-8]]
^8^ Interrogándole, podrás tú llegar a conocer a fondo todas estas cosas de que le acusamos».

[[acts-24-9]]
^9^ Los judíos le apoyaron, afirmando que las cosas eran así.

[[acts-24-10]]
^10^ Entonces el procurador concedió la palabra a Pablo y éste respondió: «Yo sé que desde hace muchos años vienes juzgando a esta nación; por eso con toda confianza voy a exponer mi defensa.

[[acts-24-11]]
^11^ Tú mismo lo puedes comprobar: No hace más de doce días que yo subí a Jerusalén en peregrinación.

[[acts-24-12]]
^12^ Y ni en el Templo, ni en las sinagogas ni por la ciudad me han encontrado discutiendo con nadie ni alborotando a la gente.

[[acts-24-13]]
^13^ Ni pueden tampoco probarte las cosas de que ahora me acusan.

[[acts-24-14]]
^14^ «En cambio te confieso que según el Camino, que ellos llaman secta, doy culto al Dios de mis padres, creo en todo lo que se encuentra en la Ley y está escrito en los Profetas

[[acts-24-15]]
^15^ y tengo en Dios la misma esperanza que éstos tienen, de que habrá una resurrección, tanto de los justos como de los pecadores.

[[acts-24-16]]
^16^ Por eso yo también me esfuerzo por tener constantemente una conciencia limpia ante Dios y ante los hombres.

[[acts-24-17]]
^17^ «Al cabo de muchos años he venido a traer limosnas a los de mi nación y a presentar ofrendas.

[[acts-24-18]]
^18^ Y me encontraron realizando estas ofrendas en el Templo después de haberme purificado, y no entre tumulto de gente.

[[acts-24-19]]
^19^ Y fueron algunos judíos de Asia... - que son los que debieran presentarse ante ti y acusarme si es que tienen algo contra mí;

[[acts-24-20]]
^20^ o si no, que digan estos mismos qué crimen hallaron en mí cuando comparecí ante el Sanedrín,

[[acts-24-21]]
^21^ a no ser este solo grito que yo lancé estando en medio de ellos: “Yo soy juzgado hoy por vosotros a causa de la resurrección de los muertos».

[[acts-24-22]]
^22^ Félix, que estaba bien informado en lo referente al Camino, les dio largas diciendo: «Cuando baje el tribuno Lisias decidiré vuestro asunto».

[[acts-24-23]]
^23^ Y ordenó al centurión que custodiase a Pablo, que le dejase tener alguna libertad y que no impidiese a ninguno de los suyos el asistirle.

[[acts-24-24]]
^24^ Después de unos días vino Félix con su esposa Drusila, que era judía; mandó traer a Pablo y le estuvo escuchando acerca de la fe en Cristo Jesús.

[[acts-24-25]]
^25^ Y al hablarle Pablo de la justicia, del dominio propio y del juicio futuro, Félix, aterrorizado, le interrumpió: «Por ahora puedes marcharte; cuando encuentre oportunidad te haré llamar».

[[acts-24-26]]
^26^ Esperaba al mismo tiempo Félix que Pablo le diese dinero; por eso frecuentemente le mandaba a buscar y conversaba con él.

[[acts-24-27]]
^27^ Pasados dos años Félix recibió como sucesor a Porcio Festo; y queriendo congraciarse con los judíos, dejó a Pablo prisionero.
[[acts-25]]
== Capítulo 25

[[acts-25-1]]
^1^ Tres días después de haber llegado a la provincia, subió Festo de Cesarea a Jerusalén.

[[acts-25-2]]
^2^ Los sumos sacerdotes y los principales de los judíos le presentaron acusación contra Pablo e insistentemente

[[acts-25-3]]
^3^ le pedían una gracia contra él, que le hiciera trasladar a Jerusalén, mientras preparaban una celada para matarle en el camino.

[[acts-25-4]]
^4^ Pero Festo les contestó que Pablo debía estar custodiado en Cesarea, y que él mismo estaba para marchar allá inmediatamente.

[[acts-25-5]]
^5^ «Que bajen conmigo, les dijo, los que entre vosotros tienen autoridad y si este hombre es culpable en algo, formulen acusación contra él».

[[acts-25-6]]
^6^ Después de pasar entre ellos no más de ocho o diez días, bajó a Cesarea y al día siguiente se sentó en el tribunal y mandó traer a Pablo.

[[acts-25-7]]
^7^ Así que éste se presentó le rodearon los judíos que habían bajado de Jerusalén, presentando contra él muchas y graves acusaciones, que no podían probar.

[[acts-25-8]]
^8^ Pablo se defendía diciendo: «Yo no he cometido falta alguna ni contra la Ley de los judíos ni contra el Templo ni contra el César».

[[acts-25-9]]
^9^ Pero Festo, queriendo congraciarse con los judíos, preguntó a Pablo: «¿Quieres subir a Jerusalén y ser allí juzgado de estas cosas en mi presencia?»

[[acts-25-10]]
^10^ Pablo contestó: «Estoy ante el tribunal del César, que es donde debo ser juzgado. A los judíos no les he hecho ningún mal, como tú muy bien sabes.

[[acts-25-11]]
^11^ Si, pues, soy reo de algún delito o he cometido algún crimen que merezca la muerte, no rehúso morir; pero si en eso de que éstos me acusan no hay ningún fundamento, nadie puede entregarme a ellos; apelo al César».

[[acts-25-12]]
^12^ Entonces Festo deliberó con el Consejo y respondió: «Has apelado al César, al César irás».

[[acts-25-13]]
^13^ Pasados algunos días, el rey Agripa y Berenice vinieron a Cesarea y fueron a saludar a Festo.

[[acts-25-14]]
^14^ Como pasaran allí bastantes días, Festo expuso al rey el caso de Pablo: «Hay aquí un hombre, le dijo, que Félix dejó prisionero.

[[acts-25-15]]
^15^ Estando yo en Jerusalén presentaron contra él acusación los sumos sacerdotes y los ancianos de los judíos, pidiendo contra él sentencia condenatoria.

[[acts-25-16]]
^16^ Yo les respondí que no es costumbre de los romanos entregar a un hombre antes de que el acusado tenga ante sí a los acusadores y se le dé la posibilidad de defenderse de la acusación.

[[acts-25-17]]
^17^ Ellos vinieron aquí juntamente conmigo, y sin dilación me senté al día siguiente en el tribunal y mandé traer al hombre.

[[acts-25-18]]
^18^ Los acusadores comparecieron ante él, pero no presentaron ninguna acusación de los crímenes que yo sospechaba;

[[acts-25-19]]
^19^ solamente tenían contra él unas discusiones sobre su propia religión y sobre un tal Jesús, ya muerto, de quien Pablo afirma que vive.

[[acts-25-20]]
^20^ Yo estaba perplejo sobre estas cuestiones y le propuse si quería ir a Jerusalén y ser allí juzgado de estas cosas.

[[acts-25-21]]
^21^ Pero como Pablo interpuso apelación de que su caso se reservase a la decisión del Augusto, mandé que se le custodiara hasta remitirle al César».

[[acts-25-22]]
^22^ Agripa dijo a Festo: «Querría yo también oír a ese hombre». - «Mañana, dijo, le oirás».

[[acts-25-23]]
^23^ Al día siguiente vinieron Agripa y Berenice con gran ostentación y entraron en la sala de audiencia, junto con los tribunos y los personajes de más categoría de la ciudad. A una orden de Festo, trajeron a Pablo.

[[acts-25-24]]
^24^ Festo dijo: «Rey Agripa y todos los aquí presentes; aquí veis a este hombre, contra quien toda la multitud de los judíos vinieron donde mí tanto en Jerusalén como aquí, gritando que no debía vivir ya más.

[[acts-25-25]]
^25^ Yo comprendí que no había hecho nada digno de muerte; pero como él ha apelado al Augusto, he decidido enviarle.

[[acts-25-26]]
^26^ No sé en concreto qué escribir al Señor sobre él; por eso le he presentado ante vosotros, y sobre todo ante ti, rey Agripa, para saber, después del interrogatorio, lo que he de escribir.

[[acts-25-27]]
^27^ Pues me parece absurdo enviar un preso sin indicar las acusaciones formuladas contra él».
[[acts-26]]
== Capítulo 26

[[acts-26-1]]
^1^ Agripa dijo a Pablo: «Se te permite hablar en tu favor». Entonces Pablo extendió su mano y empezó su defensa:

[[acts-26-2]]
^2^ «Me considero feliz, rey Agripa, al tener que defenderme hoy ante ti de todas las cosas de que me acusan los judíos,

[[acts-26-3]]
^3^ principalmente porque tú conoces todas las costumbres y cuestiones de los judíos. Por eso te pido que me escuches pacientemente.

[[acts-26-4]]
^4^ «Todos los judíos conocen mi vida desde mi juventud, desde cuando estuve en el seno de mi nación, en Jerusalén.

[[acts-26-5]]
^5^ Ellos me conocen de mucho tiempo atrás y si quieren pueden testificar que yo he vivido como fariseo conforme a la secta más estricta de nuestra religión.

[[acts-26-6]]
^6^ Y si ahora estoy aquí procesado es por la esperanza que tengo en la Promesa hecha por Dios a nuestros padres,

[[acts-26-7]]
^7^ cuyo cumplimiento están esperando nuestras doce tribus en el culto que asiduamente, noche y día, rinden a Dios. Por esta esperanza, oh rey, soy acusado por los judíos.

[[acts-26-8]]
^8^ ¿Por qué tenéis vosotros por increíble que Dios resucite a los muertos?

[[acts-26-9]]
^9^ «Yo, pues, me había creído obligado a combatir con todos los medios el nombre de Jesús, el Nazoreo.

[[acts-26-10]]
^10^ Así lo hice en Jerusalén y, con poderes recibidos de los sumos sacerdotes, yo mismo encerré a muchos santos en las cárceles; y cuando se les condenaba a muerte, yo contribuía con mi voto.

[[acts-26-11]]
^11^ Frecuentemente recorría todas las sinagogas y a fuerza de castigos les obligaba a blasfemar y, rebosando furor contra ellos, los perseguía hasta en las ciudades extranjeras.

[[acts-26-12]]
^12^ «En este empeño iba hacia Damasco con plenos poderes y comisión de los sumos sacerdotes;

[[acts-26-13]]
^13^ y al medio día, yendo de camino vi, oh rey, una luz venida del cielo, más resplandeciente que el sol, que me envolvió a mí y a mis compañeros en su resplandor.

[[acts-26-14]]
^14^ Caímos todos a tierra y yo oí una voz que me decía en lengua hebrea: “Saúl, Saúl, ¿por qué me persigues? Te es duro dar coces contra el aguijón.”

[[acts-26-15]]
^15^ Yo respondí: “¿Quién eres, Señor?” Y me dijo el Señor: “Yo soy Jesús a quien tú persigues.

[[acts-26-16]]
^16^ Pero levántate, y ponte en pie; pues me he aparecido a ti para constituirte servidor y testigo tanto de las cosas que de mí has visto como de las que te manifestaré.

[[acts-26-17]]
^17^ Yo te libraré de tu pueblo y de los gentiles, a los cuales yo te envío,

[[acts-26-18]]
^18^ para que les abras los ojos; para que se conviertan de las tinieblas a la luz, y del poder de Satanás a Dios; y para que reciban el perdón de los pecados y una parte en la herencia entre los santificados, mediante la fe en mí.”

[[acts-26-19]]
^19^ «Así pues, rey Agripa, no fui desobediente a la visión celestial,

[[acts-26-20]]
^20^ sino que primero a los habitantes de Damasco, después a los de Jerusalén y por todo el país de Judea y también a los gentiles he predicado que se convirtieran y que se volvieran a Dios haciendo obras dignas de conversión.

[[acts-26-21]]
^21^ Por esto los judíos, habiéndome prendido en el Templo, intentaban darme muerte.

[[acts-26-22]]
^22^ Con el auxilio de Dios hasta el presente me he mantenido firme dando testimonio a pequeños y grandes sin decir cosa que esté fuera de lo que los profetas y el mismo Moisés dijeron que había de suceder:

[[acts-26-23]]
^23^ que el Cristo había de padecer y que, después de resucitar el primero de entre los muertos, anunciaría la luz al pueblo y a los gentiles».

[[acts-26-24]]
^24^ Mientras estaba él diciendo esto en su defensa, Festo le interrumpió gritándole: «Estás loco, Pablo; las muchas letras te hacen perder la cabeza».

[[acts-26-25]]
^25^ Pablo contestó: «No estoy loco, excelentísimo Festo, sino que hablo cosas verdaderas y sensatas.

[[acts-26-26]]
^26^ Bien enterado está de estas cosas el rey, ante quien hablo con confianza; no creo que se le oculte nada, pues no han pasado en un rincón.

[[acts-26-27]]
^27^ ¿Crees, rey Agripa, a los profetas? Yo sé que crees».

[[acts-26-28]]
^28^ Agripa contestó a Pablo: «Por poco, con tus argumentos, haces de mí un cristiano».

[[acts-26-29]]
^29^ Y Pablo replicó: «Quiera Dios que por poco o por mucho, no solamente tú, sino todos los que me escuchan hoy, llegaran a ser tales como yo soy, a excepción de estas cadenas».

[[acts-26-30]]
^30^ El rey, el procurador, Berenice y los que con ellos estaban sentados se levantaron,

[[acts-26-31]]
^31^ y mientras se retiraban iban diciéndose unos a otros: «Este hombre no ha hecho nada digno de muerte o de prisión».

[[acts-26-32]]
^32^ Agripa dijo a Festo: «Podía ser puesto en libertad este hombre si no hubiera apelado al César».
[[acts-27]]
== Capítulo 27

[[acts-27-1]]
^1^ Cuando se decidió que nos embarcásemos rumbo a Italia, fueron confiados Pablo y algunos otros prisioneros a un centurión de la cohorte Augusta, llamado Julio.

[[acts-27-2]]
^2^ Subimos a una nave de Adramitio, que iba a partir hacia las costas de Asia, y nos hicimos a la mar. Estaba con nosotros Aristarco, macedonio de Tesalónica.

[[acts-27-3]]
^3^ Al otro día arribamos a Sidón. Julio se portó humanamente con Pablo y le permitió ir a ver a sus amigos y ser atendido por ellos.

[[acts-27-4]]
^4^ Partimos de allí y navegamos al abrigo de las costas de Chipre, porque los vientos eran contrarios.

[[acts-27-5]]
^5^ Atravesamos los mares de Cilicia y Panfilia y llegamos al cabo de quince días a Mira de Licia.

[[acts-27-6]]
^6^ Allí encontró el centurión una nave alejandrina que navegaba a Italia, y nos hizo subir a bordo.

[[acts-27-7]]
^7^ Durante muchos días la navegación fue lenta y a duras penas llegamos a la altura de Gnido. Como el viento no nos dejaba entrar en puerto, navegamos al abrigo de Creta por la parte de Salmone;

[[acts-27-8]]
^8^ y costeándola con dificultad, llegamos a un lugar llamado Puertos Buenos, cerca del cual se encuentra la ciudad de Lasea.

[[acts-27-9]]
^9^ Había transcurrido bastante tiempo y la navegación era peligrosa, pues incluso había ya pasado el Ayuno. Pablo les advertía:

[[acts-27-10]]
^10^ «Amigos, veo que la navegación va a traer gran peligro y grave daño no sólo para el cargamento y la nave, sino también para nuestras propias personas».

[[acts-27-11]]
^11^ Pero el centurión daba más crédito al piloto y al patrón que no a las palabras de Pablo.

[[acts-27-12]]
^12^ Como el puerto no era a propósito para invernar, la mayoría decidió hacerse a la mar desde allí, por si era posible llegar a Fénica, un puerto de Creta que mira al suroeste y al noroeste, y pasar allí el invierno.

[[acts-27-13]]
^13^ Soplaba ligeramente entonces el viento del sur y creyeron que podían poner en práctica su propósito; levaron anclas y fueron costeando Creta de cerca.

[[acts-27-14]]
^14^ Pero no mucho después se desencadenó un viento huracanado procedente de la isla, llamado Euroaquilón.

[[acts-27-15]]
^15^ La nave fue arrastrada y, no pudiendo hacer frente al viento, nos abandonamos a la deriva .

[[acts-27-16]]
^16^ Navegando a sotavento de una isleta llamada Cauda, pudimos con mucha dificultad hacernos con el bote.

[[acts-27-17]]
^17^ Una vez izado el bote se emplearon los cables de refuerzo, ciñendo el casco por debajo; y por miedo a chocar contra la Sirte, se echó el ancla flotante. Así se iba a la deriva.

[[acts-27-18]]
^18^ Y como el temporal seguía sacudiéndonos furiosamente, al día siguiente aligeraron la nave.

[[acts-27-19]]
^19^ Y al tercer día con sus propias manos arrojaron al mar el aparejo de la nave.

[[acts-27-20]]
^20^ Durante muchos días no apareció el sol ni las estrellas; teníamos sobre nosotros una tempestad no pequeña; toda esperanza de salvarnos iba desapareciendo.

[[acts-27-21]]
^21^ Hacía ya días que no habíamos comido; entonces Pablo se puso en medio de ellos y les dijo: «Amigos, más hubiera valido que me hubierais escuchado y no haberos hecho a la mar desde Creta; os hubierais ahorrado este peligro y esta pérdida.

[[acts-27-22]]
^22^ Pero ahora os recomiendo que tengáis buen ánimo; ninguna de vuestras vidas se perderá; solamente la nave.

[[acts-27-23]]
^23^ Pues esta noche se me ha presentado un ángel del Dios a quien pertenezco y a quien doy culto,

[[acts-27-24]]
^24^ y me ha dicho: “No temas, Pablo; tienes que comparecer ante el César; y mira, Dios te ha concedido la vida de todos los que navegan contigo.”

[[acts-27-25]]
^25^ Por tanto, amigos, ¡ánimo! Yo tengo fe en Dios de que sucederá tal como se me ha dicho.

[[acts-27-26]]
^26^ Iremos a dar en alguna isla».

[[acts-27-27]]
^27^ Era ya la décima cuarta noche que íbamos a la deriva por el Adriático, cuando hacia la media noche presintieron los marineros la proximidad de tierra.

[[acts-27-28]]
^28^ Sondearon y hallaron veinte brazas; un poco más lejos sondearon de nuevo y hallaron quince brazas.

[[acts-27-29]]
^29^ Temerosos de que fuésemos a chocar contra algunos escollos, echaron cuatro anclas desde la popa y esperaban ansiosamente que se hiciese de día.

[[acts-27-30]]
^30^ Los marineros intentaban escapar de la nave, y estaban ya arriando el bote con el pretexto de echar los cables de las anclas de proa.

[[acts-27-31]]
^31^ Pero Pablo dijo al centurión y a los soldados: «Si no se quedan éstos en la nave, vosotros no os podréis salvar».

[[acts-27-32]]
^32^ Entonces los soldados cortaron las amarras del bote y lo dejaron caer.

[[acts-27-33]]
^33^ Mientras esperaban que se hiciera de día, Pablo aconsejaba a todos que tomasen alimento diciendo: «Hace ya catorce días que, en continua expectación, estáis en ayunas, sin haber comido nada.

[[acts-27-34]]
^34^ Por eso os aconsejo que toméis alimento, pues os conviene para vuestra propia salvación; que ninguno de vosotros perderá ni un solo cabello de su cabeza».

[[acts-27-35]]
^35^ Diciendo esto, tomó pan, dio gracias a Dios en presencia de todos, lo partió y se puso a comer.

[[acts-27-36]]
^36^ Entonces todos los demás se animaron y tomaron también alimento.

[[acts-27-37]]
^37^ Estábamos en total en la nave 276 personas.

[[acts-27-38]]
^38^ Una vez satisfechos, aligeraron la nave arrojando el trigo al mar.

[[acts-27-39]]
^39^ Cuando vino el día, los marineros no reconocían la tierra; solamente podían divisar una ensenada con su playa; y resolvieron lanzar la nave hacia ella, si fuera posible.

[[acts-27-40]]
^40^ Soltaron las anclas que dejaron caer al mar; aflojaron al mismo tiempo las ataduras de los timones; depués izaron al viento la vela artimón y pusieron rumbo a la playa.

[[acts-27-41]]
^41^ Pero tropezaron contra un lugar con mar por ambos lados, y encallaron allí la nave; la proa clavada, quedó inmóvil; en cambio la popa, sacudida violentamente, se iba deshaciendo.

[[acts-27-42]]
^42^ Los soldados entonces resolvieron matar a los presos, no fuera que alguno se escapase a nado;

[[acts-27-43]]
^43^ pero el centurión, que quería salvar a Pablo, se opuso a su designio y dio orden de que los que supieran nadar se arrojasen los primeros al agua y ganasen la orilla;

[[acts-27-44]]
^44^ y los demás saliesen unos sobre tablones, otros sobre los despojos de la nave. De esta forma todos llegamos a tierra sanos y salvos.
[[acts-28]]
== Capítulo 28

[[acts-28-1]]
^1^ Una vez a salvo, supimos que la isla se llamaba Malta.

[[acts-28-2]]
^2^ Los nativos nos mostraron una humanidad poco común; encendieron una hoguera a causa de la lluvía que caía y del frío, y nos acogieron a todos.

[[acts-28-3]]
^3^ Pablo había reunido una brazada de ramas secas; al ponerla sobre la hoguera, una víbora que salía huyendo del calor, hizo presa en su mano.

[[acts-28-4]]
^4^ Los nativos, cuando vieron el animal colgado de su mano, se dijeron unos a otros: «Este hombre es seguramente un asesino; ha escapado del mar, pero la justicia divina no le deja vivir».

[[acts-28-5]]
^5^ Pero él sacudió el animal sobre el fuego y no sufrió daño alguno.

[[acts-28-6]]
^6^ Ellos estaban esperando que se hincharía o que caería muerto de repente; pero después de esperar largo tiempo y viendo que no le ocurría nada anormal, cambiaron de parecer y empezaron a decir que era un dios.

[[acts-28-7]]
^7^ En las cercanías de aquel lugar tenía unas propiedades el principal de la isla llamado Publio, quien nos recibió y nos dio amablemente hospedaje durante tres días.

[[acts-28-8]]
^8^ Precisamente el padre de Publio se hallaba en cama atacado de fiebres y disentería. Pablo entró a verle, hizo oración, le impuso las manos y le curó.

[[acts-28-9]]
^9^ Después de este suceso los otros enfermos de la isla acudieron y fueron curados.

[[acts-28-10]]
^10^ Tuvieron para con nosotros toda suerte de consideraciones y a nuestra partida nos proveyeron de lo necesario.

[[acts-28-11]]
^11^ Transcurridos tres meses nos hicimos a la mar en una nave alejandrina que había invernado en la isla y llevaba por enseña los Dióscuros.

[[acts-28-12]]
^12^ Arribamos a Siracusa y permanecimos allí tres días.

[[acts-28-13]]
^13^ Desde allí, costeando, llegamos a Regio. Al día siguiente se levantó el viento del sur, y al cabo de dos días llegamos a Pozzuoli.

[[acts-28-14]]
^14^ Encontramos allí hermanos y tuvimos el consuelo de permanecer con ellos siete días. Y así llegamos a Roma.

[[acts-28-15]]
^15^ Los hermanos, informados de nuestra llegada, salieron a nuestro encuentro hasta el Foro Apio y Tres Tabernas. Pablo, al verlos, dio gracias a Dios y cobró ánimos.

[[acts-28-16]]
^16^ Cuando entramos en Roma se le permitió a Pablo permanecer en casa particular con un soldado que le custodiara.

[[acts-28-17]]
^17^ Tres días después convocó a los principales judíos. Una vez reunidos, les dijo: «Hermanos, yo, sin haber hecho nada contra el pueblo ni contra las costumbres de los padres, fui apresado en Jerusalén y entregado en manos de los romanos,

[[acts-28-18]]
^18^ que, después de haberme interrogado, querían dejarme en libertad porque no había en mí ningún motivo de muerte.

[[acts-28-19]]
^19^ Pero como los judíos se oponían, me vi forzado a apelar al César, sin pretender con eso acusar a los de mi nación.

[[acts-28-20]]
^20^ Por este motivo os llamé para veros y hablaros, pues precisamente por la esperanza de Israel llevo yo estas cadenas».

[[acts-28-21]]
^21^ Ellos le respondieron: «Nosotros no hemos recibido de Judea ninguna carta que nos hable de ti, ni ninguno de los hermanos llegados aquí nos ha referido o hablado nada malo de ti.

[[acts-28-22]]
^22^ Pero deseamos oír de ti mismo lo que piensas, pues lo que de esa secta sabemos es que en todas partes se la contradice».

[[acts-28-23]]
^23^ Le señalaron un día y vinieron en mayor número adonde se hospedaba. El les iba exponiendo el Reino de Dios, dando testimonio e intentando persuadirles acerca de Jesús, basándose en la Ley de Moisés y en los Profetas, desde la mañana hasta la tarde.

[[acts-28-24]]
^24^ Unos creían por sus palabras y otros en cambio permanecían incrédulos.

[[acts-28-25]]
^25^ Cuando, en desacuerdo entre sí mismos, ya se marchaban, Pablo dijo esta sola cosa: «Con razón habló el Espíritu Santo a vuestros padres por medio del profeta Isaías:

[[acts-28-26]]
^26^ Ve a encontrar a este pueblo y dile: Escucharéis bien, pero no entenderéis, miraréis bien, pero no veréis.

[[acts-28-27]]
^27^ Porque se ha embotado el corazón de este pueblo, han hecho duros sus oídos, y sus ojos han cerrado; no sea que vean con sus ojos, y con sus oídos oigan, y con su corazón entiendan y se conviertan, y yo los cure.

[[acts-28-28]]
^28^ «Sabed, pues, que esta salvación de Dios ha sido enviada a los gentiles; ellos sí que la oirán».

[[acts-28-30]]
^30^ Pablo permaneció dos años enteros en una casa que había alquilado y recibía a todos los que acudían a él;

[[acts-28-31]]
^31^ predicaba el Reino de Dios y enseñaba lo referente al Señor Jesucristo con toda valentía, sin estorbo alguno.
