[[romans]]
= Romanos

[[romans-1]]
== Capítulo 1

[[romans-1-1]]
^1^ Pablo, siervo de Cristo Jesús, apóstol por vocación, escogido para el Evangelio de Dios,

[[romans-1-2]]
^2^ que había ya prometido por medio de sus profetas en las Escrituras Sagradas,

[[romans-1-3]]
^3^ acerca de su Hijo, nacido del linaje de David según la carne,

[[romans-1-4]]
^4^ constituido Hijo de Dios con poder, según el Espíritu de santidad, por su resurrección de entre los muertos, Jesucristo Señor nuestro,

[[romans-1-5]]
^5^ por quien recibimos la gracia y el apostolado, para predicar la obediencia de la fe a gloria de su nombre entre todos los gentiles,

[[romans-1-6]]
^6^ entre los cuales os contáis también vosotros, llamados de Jesucristo,

[[romans-1-7]]
^7^ a todos los amados de Dios que estáis en Roma, santos por vocación, a vosotros gracia y paz, de parte de Dios nuestro Padre y del Señor Jesucristo.

[[romans-1-8]]
^8^ Ante todo, doy gracias a mi Dios por medio de Jesucristo, por todos vosotros, pues vuestra fe es alabada en todo el mundo.

[[romans-1-9]]
^9^ Porque Dios, a quien venero en mi espíritu predicando el Evangelio de su Hijo, me es testigo de cuán incesantemente me acuerdo de vosotros,

[[romans-1-10]]
^10^ rogandole siempre en mis oraciones, si es de su voluntad, encuentre por fin algún día ocasión favorable de llegarme hasta vosotros,

[[romans-1-11]]
^11^ pues ansío veros, a fin de comunicaros algún don espiritual que os fortalezca,

[[romans-1-12]]
^12^ o más bien, para sentir entre vosotros el mutuo consuelo de la común fe: la vuestra y la mía.

[[romans-1-13]]
^13^ Pues no quiero que ignoréis, hermanos, las muchas veces que me propuse ir a vosotros - pero hasta el presente me he visto impedido - con la intención de recoger también entre vosotros algún fruto, al igual que entre los demás gentiles.

[[romans-1-14]]
^14^ Me debo a los griegos y a los barbaros; a los sabios y a los ignorantes:

[[romans-1-15]]
^15^ de ahí mi ansia por llevaros el Evangelio también a vosotros, habitantes de Roma.

[[romans-1-16]]
^16^ Pues no me avergüenzo del Evangelio, que es una fuerza de Dios para la salvación de todo el que cree: del judío primeramente y también del griego.

[[romans-1-17]]
^17^ Porque en él se revela la justicia de Dios, de fe en fe, como dice la Escritura: El justo vivirá por la fe.

[[romans-1-18]]
^18^ En efecto, la cólera de Dios se revela desde el cielo contra toda impiedad e injusticia de los hombres que aprisionan la verdad en la injusticia;

[[romans-1-19]]
^19^ pues lo que de Dios se puede conocer, está en ellos manifiesto: Dios se lo manifestó.

[[romans-1-20]]
^20^ Porque lo invisible de Dios, desde la creación del mundo, se deja ver a la inteligencia a través de sus obras: su poder eterno y su divinidad, de forma que son inexcusables;

[[romans-1-21]]
^21^ porque, habiendo conocido a Dios, no le glorificaron como a Dios ni le dieron gracias, antes bien se ofuscaron en sus razonamientos y su insensato corazón se entenebreció:

[[romans-1-22]]
^22^ jactándose de sabios se volvieron estúpidos,

[[romans-1-23]]
^23^ y cambiaron la gloria del Dios incorruptible por una representación en forma de hombre corruptible, de aves, de cuadrúpedos, de reptiles.

[[romans-1-24]]
^24^ Por eso Dios los entregó a las apetencias de su corazón hasta una impureza tal que deshonraron entre sí sus cuerpos;

[[romans-1-25]]
^25^ a ellos que cambiaron la verdad de Dios por la mentira, y adoraron y sirvieron a la criatura en vez del Creador, que es bendito por los siglos. Amén.

[[romans-1-26]]
^26^ Por eso los entregó Dios a pasiones infames; pues sus mujeres invirtieron las relaciones naturales por otras contra la naturaleza;

[[romans-1-27]]
^27^ igualmente los hombres, abandonando el uso natural de la mujer, se abrasaron en deseos los unos por los otros, cometiendo la infamia de hombre con hombre, recibiendo en sí mismos el pago merecido de su extravío.

[[romans-1-28]]
^28^ Y como no tuvieron a bien guardar el verdadero conocimiento de Dios, entrególos Dios a su mente insensata, para que hicieran lo que no conviene:

[[romans-1-29]]
^29^ llenos de toda injusticia, perversidad, codicia, maldad, henchidos de envidia, de homicidio, de contienda, de engaño, de malignidad, chismosos,

[[romans-1-30]]
^30^ detractores, enemigos de Dios, ultrajadores, altaneros, fanfarrones, ingeniosos para el mal, rebeldes a sus padres,

[[romans-1-31]]
^31^ insensatos, desleales, desamorados, despiadados,

[[romans-1-32]]
^32^ los cuales, aunque conocedores del veredicto de Dios que declara dignos de muerte a los que tales cosas practican, no solamente las practican, sino que aprueban a los que las cometen.
[[romans-2]]
== Capítulo 2

[[romans-2-1]]
^1^ Por eso, no tienes excusa quienquiera que seas, tú que juzgas, pues juzgando a otros, a ti mismo te condenas, ya que obras esas mismas cosas tú que juzgas,

[[romans-2-2]]
^2^ y sabemos que el juicio de Dios es según verdad contra los que obran semejantes cosas.

[[romans-2-3]]
^3^ Y ¿te figuras, tú que juzgas a los que cometen tales cosas y las cometes tú mismo, que escaparás al juicio de Dios?

[[romans-2-4]]
^4^ O ¿desprecias, tal vez, sus riquezas de bondad, de paciencia y de longanimidad, sin reconocer que esa bondad de Dios te impulsa a la conversión?

[[romans-2-5]]
^5^ Por la dureza y la impenitencia de tu corazón vas atesorando contra ti cólera para el día de la cólera y de la revelación del justo juicio de Dios,

[[romans-2-6]]
^6^ el cual dará a cada cual según sus obras:

[[romans-2-7]]
^7^ a los que, por la perseverancia en el bien busquen gloria, honor e inmortalidad: vida eterna;

[[romans-2-8]]
^8^ mas a los rebeldes, indóciles a la verdad y dóciles a la injusticia: cólera e indignación.

[[romans-2-9]]
^9^ Tribulación y angustia sobre toda alma humana que obre el mal: del judío primeramente y también del griego;

[[romans-2-10]]
^10^ en cambio, gloria, honor y paz a todo el que obre el bien; al judío primeramente y también al griego;

[[romans-2-11]]
^11^ que no hay acepción de personas en Dios.

[[romans-2-12]]
^12^ Pues cuantos sin ley pecaron, sin ley también perecerán; y cuantos pecaron bajo la ley, por la ley serán juzgados;

[[romans-2-13]]
^13^ que no son justos delante de Dios los que oyen la ley, sino los que la cumplen: ésos serán justificados.

[[romans-2-14]]
^14^ En efecto, cuando los gentiles, que no tienen ley, cumplen naturalmente las prescripciones de la ley, sin tener ley, para sí mismos son ley;

[[romans-2-15]]
^15^ como quienes muestran tener la realidad de esa ley escrita en su corazón, atestiguándolo su conciencia, y los juicios contrapuestos de condenación o alabanza...

[[romans-2-16]]
^16^ en el día en que Dios juzgará las acciones secretas de los hombres, según mi Evangelio, por Cristo Jesús.

[[romans-2-17]]
^17^ Pero si tú, que te dices judío y descansas en la ley; que te glorías en Dios;

[[romans-2-18]]
^18^ que conoces su voluntad; que disciernes lo mejor, amaestrado por la ley,

[[romans-2-19]]
^19^ y te jactas de ser guía de ciegos, luz de los que andan en tinieblas,

[[romans-2-20]]
^20^ educador de ignorantes, maestro de niños, porque posees en la ley la expresión misma de la ciencia y de la verdad...

[[romans-2-21]]
^21^ pues bien, tú que instruyes a los otros ¡a ti mismo no te instruyes! Predicas: ¡no robar!, y ¡robas!

[[romans-2-22]]
^22^ Prohíbes el adulterio, y ¡adulteras! Aborreces los ídolos, y ¡saqueas sus templos!

[[romans-2-23]]
^23^ Tú que te glorías en la ley, transgrediéndola deshonras a Dios.

[[romans-2-24]]
^24^ Porque, como dice la Escritura, el nombre de Dios, por vuestra causa, es blasfemado entre las naciones.

[[romans-2-25]]
^25^ Pues la circuncisión, en verdad, es útil si cumples la ley; pero si eres un trangresor de la ley, tu circuncisión se vuelve incircuncisión.

[[romans-2-26]]
^26^ Mas si el incircunciso guarda las prescripciones de la ley ¿no se tendra su incircuncisión como circuncisión?

[[romans-2-27]]
^27^ Y el que, siendo físicamente incircunciso, cumple la ley, te juzgará a ti, que con la letra y la circuncisión eres transgresor de la ley.

[[romans-2-28]]
^28^ Pues no está en el exterior el ser judío, ni es circuncisión la externa, la de la carne.

[[romans-2-29]]
^29^ El verdadero judío lo es en el interior, y la verdadera circuncisión, la del corazón, según el espíritu y no según la letra. Ese es quien recibe de Dios la gloria y no de los hombres.
[[romans-3]]
== Capítulo 3

[[romans-3-1]]
^1^ ¿Cuál es, pues, la ventaja del judío? ¿Cuál la utilidad de la circuncisión?

[[romans-3-2]]
^2^ Grande, de todas maneras. Ante todo, a ellos les fueron confiados los oráculos de Dios.

[[romans-3-3]]
^3^ Pues ¿qué? Si algunos de ellos fueron infieles ¿frustrará, por ventura, su infidelidad la fidelidad de Dios?

[[romans-3-4]]
^4^ ¡De ningún modo! Dios tiene que ser veraz y todo hombre mentiroso, como dice la Escritura: Para que seas justificado en tus palabras y triunfes al ser juzgado.

[[romans-3-5]]
^5^ Pero si nuestra injusticia realza la justicia de Dios, ¿qué diremos? ¿Será acaso injusto Dios al descargar su cólera? (Hablo en términos humanos.)

[[romans-3-6]]
^6^ ¡De ningún modo! Si no, ¿cómo juzgará Dios al mundo?

[[romans-3-7]]
^7^ Pero si con mi mentira sale ganando la verdad de Dios para gloria suya ¿por qué razón soy también yo todavía juzgado como pecador?

[[romans-3-8]]
^8^ Y ¿por qué no hacer el mal para que venga el bien, como algunos calumniosamente nos acusan que decimos? Esos tales tienen merecida su condenación.

[[romans-3-9]]
^9^ Entonces ¿qué? ¿Llevamos ventaja? ¡De ningún modo!

[[romans-3-10]]
^10^ Pues ya demostramos que tanto judíos como griegos están bajo el pecado, como dice la Escritura: No hay quien sea justo, ni siquiera uno solo.

[[romans-3-11]]
^11^ No hay un sensato, no hay quien busque a Dios.

[[romans-3-12]]
^12^ Todos se desviaron, a una se corrompieron; no hay quien obre el bien, no hay siquiera uno.

[[romans-3-13]]
^13^ Sepulcro abierto es su garganta, con su lengua urden engaños. Veneno de áspides bajo sus labios;

[[romans-3-14]]
^14^ maldición y amargura rebosa su boca.

[[romans-3-15]]
^15^ Ligeros sus pies para derramar sangre;

[[romans-3-16]]
^16^ ruina y miseria son sus caminos.

[[romans-3-17]]
^17^ El camino de la paz no lo conocieron,

[[romans-3-18]]
^18^ no hay temor de Dios ante sus ojos.

[[romans-3-19]]
^19^ Ahora bien, sabemos que cuanto dice la ley lo dice para los que están bajo la ley, para que toda boca enmudezca y el mundo entero se reconozca reo ante Dios,

[[romans-3-20]]
^20^ ya que nadie será justificado ante él por las obras de la ley, pues la ley no da sino el conocimiento del pecado.

[[romans-3-21]]
^21^ Pero ahora, independientemente de la ley, la justicia de Dios se ha manifestado, atestiguada por la ley y los profetas,

[[romans-3-22]]
^22^ justicia de Dios por la fe en Jesucristo, para todos los que creen - pues no hay diferencia alguna;

[[romans-3-23]]
^23^ todos pecaron y están privados de la gloria de Dios -

[[romans-3-24]]
^24^ y son justificados por el don de su gracia, en virtud de la redención realizada en Cristo Jesús,

[[romans-3-25]]
^25^ a quien exhibió Dios como instrumento de propiciación por su propia sangre, mediante la fe, para mostrar su justicia, habiendo pasado por alto los pecados cometidos anteriormente,

[[romans-3-26]]
^26^ en el tiempo de la paciencia de Dios; en orden a mostrar su justicia en el tiempo presente, para ser él justo y justificador del que cree en Jesús.

[[romans-3-27]]
^27^ ¿Dónde está, entonces, el derecho a gloriarse? Queda eliminado.!? Por qué ley? ¿Por la de las obras? No. Por la ley de la fe.

[[romans-3-28]]
^28^ Porque pensamos que el hombre es justificado por la fe, sin las obras de la ley.

[[romans-3-29]]
^29^ ¿Acaso Dios lo es únicamente de los judíos y no también de los gentiles? ¡Sí, por cierto!, también de los gentiles;

[[romans-3-30]]
^30^ porque no hay más que un solo Dios, que justificará a los circuncisos en virtud de la fe y a los incircuncisos por medio de la fe.

[[romans-3-31]]
^31^ Entonces ¿por la fe privamos a la ley de su valor? ¡De ningún modo! Más bien, la consolidamos.
[[romans-4]]
== Capítulo 4

[[romans-4-1]]
^1^ ¿Qué diremos, pues, de Abraham, nuestro padre según la carne?

[[romans-4-2]]
^2^ Si Abraham obtuvo la justicia por las obras, tiene de qué gloriarse, mas no delante de Dios.

[[romans-4-3]]
^3^ En efecto, ¿qué dice la Escritura? Creyó Abraham en Dios y le fue reputado como justicia.

[[romans-4-4]]
^4^ Al que trabaja no se le cuenta el salario como favor sino como deuda;

[[romans-4-5]]
^5^ en cambio, al que, sin trabajar, cree en aquel que justifica al impío, su fe se le reputa como justicia.

[[romans-4-6]]
^6^ Como también David proclama bienaventurado al hombre a quien Dios imputa la justicia independientemente de las obras:

[[romans-4-7]]
^7^ Bienaventurados aquellos cuyas maldades fueron perdonadas, y cubiertos sus pecados.

[[romans-4-8]]
^8^ Dichoso el hombre a quien el Señor no imputa culpa alguna.

[[romans-4-9]]
^9^ Entonces, ¿esta dicha recae sólo sobre los circuncisos o también sobre los incircuncisos? Decimos, en efecto, que la fe de Abraham le fue reputada como justicia.

[[romans-4-10]]
^10^ Y ¿cómo le fue reputada? ¿siendo él circunciso o antes de serlo? No siendo circunciso sino antes;

[[romans-4-11]]
^11^ y recibió la señal de la circuncisión como sello de la justicia de la fe que poseía siendo incircunciso. Así se convertía en padre de todos los creyentes incircuncisos, a fin de que la justicia les fuera igualmente imputada;

[[romans-4-12]]
^12^ y en padre también de los circuncisos que no se contentan con la circuncisión, sino que siguen además las huellas de la fe que tuvo nuestro padre Abraham antes de la circuncisión.

[[romans-4-13]]
^13^ En efecto, no por la ley, sino por la justicia de la fe fue hecha a Abraham y su posteridad la promesa de ser heredero del mundo.

[[romans-4-14]]
^14^ Porque si son herederos los de la ley, la fe carece de objeto, y la promesa queda abolida;

[[romans-4-15]]
^15^ porque la ley produce la cólera; por el contrario, donde no hay ley, no hay transgresión.

[[romans-4-16]]
^16^ Por eso depende de la fe, para ser favor gratuito, a fin de que la Promesa quede asegurada para toda la posteridad, no tan sólo para los de la ley, sino también para los de la fe de Abraham, padre de todos nosotros,

[[romans-4-17]]
^17^ como dice la Escritura: Te he constituido padre de muchas naciones: padre nuestro delante de Aquel a quien creyó, de Dios que da la vida a los muertos y llama a las cosas que no son para que sean.

[[romans-4-18]]
^18^ El cual, esperando contra toda esperanza, creyó y fue hecho padre de muchas naciones según le había sido dicho: Así será tu posteridad.

[[romans-4-19]]
^19^ No vaciló en su fe al considerar su cuerpo ya sin vigor - tenía unos cien años - y el seno de Sara, igualmente estéril.

[[romans-4-20]]
^20^ Por el contrario, ante la promesa divina, no cedió a la duda con incredulidad; más bien, fortalecido en su fe, dio gloria a Dios,

[[romans-4-21]]
^21^ con el pleno convencimiento de que poderoso es Dios para cumplir lo prometido.

[[romans-4-22]]
^22^ Por eso le fue reputado como justicia.

[[romans-4-23]]
^23^ Y la Escritura no dice solamente por él que le fue reputado, sino también por nosotros,

[[romans-4-24]]
^24^ a quienes ha de ser imputada la fe, a nosotros que creemos en Aquel que resucitó de entre los muertos a Jesús Señor nuestro,

[[romans-4-25]]
^25^ quien fue entregado por nuestros pecados, y fue resucitado para nuestra justificación.
[[romans-5]]
== Capítulo 5

[[romans-5-1]]
^1^ Habiendo, pues, recibido de la fe nuestra justificación, estamos en paz con Dios, por nuestro Señor Jesucristo,

[[romans-5-2]]
^2^ por quien hemos obtenido también, mediante la fe, el acceso a esta gracia en la cual nos hallamos, y nos gloriamos en la esperanza de la gloria de Dios.

[[romans-5-3]]
^3^ Más aún; nos gloriamos hasta en las tribulaciones, sabiendo que la tribulación engendra la paciencia;

[[romans-5-4]]
^4^ la paciencia, virtud probada; la virtud probada, esperanza,

[[romans-5-5]]
^5^ y la esperanza no falla, porque el amor de Dios ha sido derramado en nuestros corazones por el Espíritu Santo que nos ha sido dado.

[[romans-5-6]]
^6^ En efecto, cuando todavía estábamos sin fuerzas, en el tiempo señalado, Cristo murió por los impíos; -

[[romans-5-7]]
^7^ en verdad, apenas habrá quien muera por un justo; por un hombre de bien tal vez se atrevería uno a morir -;

[[romans-5-8]]
^8^ mas la prueba de que Dios nos ama es que Cristo, siendo nosotros todavía pecadores, murió por nosotros.

[[romans-5-9]]
^9^ ¡Con cuánta más razón, pues, justificados ahora por su sangre, seremos por él salvos de la cólera!

[[romans-5-10]]
^10^ Si cuando éramos enemigos, fuimos reconciliados con Dios por la muerte de su Hijo, ¡con cuánta más razón, estando ya reconciliados, seremos salvos por su vida!

[[romans-5-11]]
^11^ Y no solamente eso, sino que también nos gloriamos en Dios, por nuestro Señor Jesucristo, por quien hemos obtenido ahora la reconciliación.

[[romans-5-12]]
^12^ Por tanto, como por un solo hombre entró el pecado en el mundo y por el pecado la muerte y así la muerte alcanzó a todos los hombres, por cuanto todos pecaron;

[[romans-5-13]]
^13^ - porque, hasta la ley, había pecado en el mundo, pero el pecado no se imputa no habiendo ley;

[[romans-5-14]]
^14^ con todo, reinó la muerte desde Adán hasta Moisés aun sobre aquellos que no pecaron con una transgresión semejante a la de Adán, el cual es figura del que había de venir...

[[romans-5-15]]
^15^ Pero con el don no sucede como con el delito. Si por el delito de uno solo murieron todos ¡cuánto más la gracia de Dios y el don otorgado por la gracia de un solo hombre Jesucristo, se han desbordado sobre todos!

[[romans-5-16]]
^16^ Y no sucede con el don como con las consecuencias del pecado de uno solo; porque la sentencia, partiendo de uno solo, lleva a la condenación, mas la obra de la gracia, partiendo de muchos delitos, se resuelve en justificación.

[[romans-5-17]]
^17^ En efecto, si por el delito de uno solo reinó la muerte por un solo hombre ¡con cuánta más razón los que reciben en abundancia la gracia y el don de la justicia, reinarán en la vida por un solo, por Jesucristo!

[[romans-5-18]]
^18^ Así pues, como el delito de uno solo atrajo sobre todos los hombres la condenación, así también la obra de justicia de uno solo procura toda la justificación que da la vida.

[[romans-5-19]]
^19^ En efecto, así como por la desobediencia de un solo hombre, todos fueron constituidos pecadores, así también por la obediencia de uno solo todos serán constituidos justos.

[[romans-5-20]]
^20^ La ley, en verdad, intervino para que abundara el delito; pero donde abundó el pecado, sobreabundó la gracia;

[[romans-5-21]]
^21^ así, la mismo que el pecado reinó en la muerte, así también reinaría la gracia en virtud de la justicia para vida eterna por Jesucristo nuestro Señor.
[[romans-6]]
== Capítulo 6

[[romans-6-1]]
^1^ ¿Qué diremos, pues? ¿Que debemos permanecer en el pecado para que la gracia se multiplique? ¡De ningún modo!

[[romans-6-2]]
^2^ Los que hemos muerto al pecado ¿cómo seguir viviendo en él?

[[romans-6-3]]
^3^ ¿O es que ignoráis que cuantos fuimos bautizados en Cristo Jesús, fuimos bautizados en su muerte?

[[romans-6-4]]
^4^ Fuimos, pues, con él sepultados por el bautismo en la muerte, a fin de que, al igual que Cristo fue resucitado de entre los muertos por medio de la gloria del Padre, así también nosotros vivamos una vida nueva.

[[romans-6-5]]
^5^ Porque si hemos hecho una misma cosa con él por una muerte semejante a la suya, también lo seremos por una resurrección semejante;

[[romans-6-6]]
^6^ sabiendo que nuestro hombre viejo fue crucificado con él, a fin de que fuera destruido este cuerpo de pecado y cesáramos de ser esclavos del pecado.

[[romans-6-7]]
^7^ Pues el que está muerto, queda librado del pecado.

[[romans-6-8]]
^8^ Y si hemos muerto con Cristo, creemos que también viviremos con él,

[[romans-6-9]]
^9^ sabiendo que Cristo, una vez resucitado de entre los muertos, ya no muere más, y que la muerte no tiene ya señorío sobre él.

[[romans-6-10]]
^10^ Su muerte fue un morir al pecado, de una vez para siempre; mas su vida, es un vivir para Dios.

[[romans-6-11]]
^11^ Así también vosotros, consideraos como muertos al pecado y vivos para Dios en Cristo Jesús.

[[romans-6-12]]
^12^ No reine, pues, el pecado en vuestro cuerpo mortal de modo que obedezcáis a sus apetencias.

[[romans-6-13]]
^13^ Ni hagáis ya de vuestros miembros armas de injusticia al servicio del pecado; sino más bien ofreceos vosotros mismos a Dios como muertos retornados a la vida; y vuestros miembros, como armas de justicia al servicio de Dios.

[[romans-6-14]]
^14^ Pues el pecado no dominará ya sobre vosotros, ya que no estáis bajo la ley sino bajo la gracia.

[[romans-6-15]]
^15^ Pues ¿qué? ¿Pecaremos porque no estamos bajo la ley sino bajo la gracia? ¡De ningún modo!

[[romans-6-16]]
^16^ ¿No sabéis que al ofreceros a alguno como esclavos para obedecerle, os hacéis esclavos de aquel a quien obedecéis: bien del pecado, para la muerte, bien de obediencia, para la justicia?

[[romans-6-17]]
^17^ Pero gracias a Dios, vosotros, que erais esclavos del pecado, habéis obedecido de corazón a aquel modelo de doctrina al que fuisteis entregados,

[[romans-6-18]]
^18^ y liberados del pecado, os habéis hecho esclavos de la justicia. -

[[romans-6-19]]
^19^ Hablo en términos humanos, en atención a vuestra flaqueza natural -. Pues si en otros tiempos ofrecisteis vuestros miembros como esclavos a la impureza y al desorden hasta desordenaros, ofrecedlos igualmente ahora a la justicia para la santidad.

[[romans-6-20]]
^20^ Pues cuando erais esclavos del pecado, erais libres respecto de la justicia.

[[romans-6-21]]
^21^ ¿Qué frutos cosechasteis entonces de aquellas cosas que al presente os avergüenzan? Pues su fin es la muerte.

[[romans-6-22]]
^22^ Pero al presente, libres del pecado y esclavos de Dios, fructificáis para la santidad; y el fin, la vida eterna.

[[romans-6-23]]
^23^ Pues el salario del pecado es la muerte; pero el don gratuito de Dios, la vida eterna en Cristo Jesús Señor nuestro.
[[romans-7]]
== Capítulo 7

[[romans-7-1]]
^1^ ¿O es que ignoráis, hermanos, - hablo a quienes entienden de leyes - que la ley no domina sobre el hombre sino mientras vive?

[[romans-7-2]]
^2^ Así, la mujer casada está ligada por la ley a su marido mientras éste vive; mas, una vez muerto el marido, se ve libre de la ley del marido.

[[romans-7-3]]
^3^ Por eso, mientras vive el marido, será llamada adultera si se une a otro hombre; pero si muere el marido, queda libre de la ley, de forma que no es adultera si se casa con otro.

[[romans-7-4]]
^4^ Así pues, hermanos míos, también vosotros quedasteis muertos respecto de la ley por el cuerpo de Cristo, para pertenecer a otro: a aquel que fue resucitado de entre los muertos, a fin de que fructificáramos para Dios.

[[romans-7-5]]
^5^ Porque, cuando estábamos en la carne, las pasiones pecaminosas, excitadas por la ley, obraban en nuestros miembros, a fin de que produjéramos frutos de muerte.

[[romans-7-6]]
^6^ Mas, al presente, hemos quedado emancipados de la ley, muertos a aquello que nos tenía aprisionados, de modo que sirvamos con un espíritu nuevo y no con la letra vieja.

[[romans-7-7]]
^7^ ¿Qué decir, entonces? ¿Que la ley es pecado? ¡De ningún modo! Sin embargo yo no conocí el pecado sino por la ley. De suerte que yo hubiera ignorado la concupiscencia si la ley no dijera: ¡No te des a la concupiscencia!

[[romans-7-8]]
^8^ Mas el pecado, tomando ocasión por medio del precepto, suscitó en mi toda suerte de concupiscencias; pues sin ley el pecado estaba muerto.

[[romans-7-9]]
^9^ ¡Ah! ¡Vivía yo un tiempo sin ley!, pero en cuanto sobrevino el precepto, revivió el pecado,

[[romans-7-10]]
^10^ y yo morí; y resultó que el precepto, dado para vida, me fue para muerte.

[[romans-7-11]]
^11^ Porque el pecado, tomando ocasión por medio del precepto, me sedujo, y por él, me mató.

[[romans-7-12]]
^12^ Así que, la ley es santa, y santo el precepto, y justo y bueno.

[[romans-7-13]]
^13^ Luego ¿se habrá convertido lo bueno en muerte para mí? ¡De ningún modo! Sino que el pecado, para aparecer como tal, se sirvió de una cosa buena, para procurarme la muerte, a fin de que el pecado ejerciera todo su poder de pecado por medio del precepto.

[[romans-7-14]]
^14^ Sabemos, en efecto, que la ley es espiritual, mas yo soy de carne, vendido al poder del pecado.

[[romans-7-15]]
^15^ Realmente, mi proceder no lo comprendo; pues no hago lo que quiero, sino que hago lo que aborrezco.

[[romans-7-16]]
^16^ Y, si hago lo que no quiero, estoy de acuerdo con la Ley en que es buena;

[[romans-7-17]]
^17^ en realidad, ya no soy yo quien obra, sino el pecado que habita en mí.

[[romans-7-18]]
^18^ Pues bien sé yo que nada bueno habita en mí, es decir, en mi carne; en efecto, querer el bien lo tengo a mi alcance, mas no el realizarlo,

[[romans-7-19]]
^19^ puesto que no hago el bien que quiero, sino que obro el mal que no quiero.

[[romans-7-20]]
^20^ Y, si hago lo que no quiero, no soy yo quien lo obra, sino el pecado que habita en mí.

[[romans-7-21]]
^21^ Descubro, pues, esta ley: aun queriendo hacer el bien, es el mal el que se me presenta.

[[romans-7-22]]
^22^ Pues me complazco en la ley de Dios según el hombre interior,

[[romans-7-23]]
^23^ pero advierto otra ley en mis miembros que lucha contra la ley de mi razón y me esclaviza a la ley del pecado que está en mis miembros.

[[romans-7-24]]
^24^ ¡Pobre de mí! ¿Quién me librará de este cuerpo que me lleva a la muerte?

[[romans-7-25]]
^25^ ¡Gracias sean dadas a Dios por Jesucristo nuestro Señor! Así pues, soy yo mismo quien con la razón sirve a la ley de Dios, mas con la carne, a la ley del pecado.
[[romans-8]]
== Capítulo 8

[[romans-8-1]]
^1^ Por consiguiente, ninguna condenación pesa ya sobre los que están en Cristo Jesús.

[[romans-8-2]]
^2^ Porque la ley del espíritu que da la vida en Cristo Jesús te liberó de la ley del pecado y de la muerte.

[[romans-8-3]]
^3^ Pues lo que era imposible a la ley, reducida a la impotencia por la carne, Dios, habiendo enviado a su propio Hijo en una carne semejante a la del pecado, y en orden al pecado, condenó el pecado en la carne,

[[romans-8-4]]
^4^ a fin de que la justicia de la ley se cumpliera en nosotros que seguimos una conducta, no según la carne, sino según el espíritu.

[[romans-8-5]]
^5^ Efectivamente, los que viven según la carne, desean lo carnal; mas los que viven según el espíritu, lo espiritual.

[[romans-8-6]]
^6^ Pues las tendencias de la carne son muerte; mas las del espíritu, vida y paz,

[[romans-8-7]]
^7^ ya que las tendencias de la carne llevan al odio a Dios: no se someten a la ley de Dios, ni siquiera pueden;

[[romans-8-8]]
^8^ así, los que están en la carne, no pueden agradar a Dios.

[[romans-8-9]]
^9^ Mas vosotros no estáis en la carne, sino en el espíritu, ya que el Espíritu de Dios habita en vosotros. El que no tiene el Espíritu de Cristo, no le pertenece;

[[romans-8-10]]
^10^ mas si Cristo está en vosotros, aunque el cuerpo haya muerto ya a causa del pecado, el espíritu es vida a causa de la justicia.

[[romans-8-11]]
^11^ Y si el Espíritu de Aquel que resucitó a Jesús de entre los muertos habita en vosotros, Aquel que resucitó a Cristo de entre los muertos dará también la vida a vuestros cuerpos mortales por su Espíritu que habita en vosotros.

[[romans-8-12]]
^12^ Así que, hermanos míos, no somos deudores de la carne para vivir según la carne,

[[romans-8-13]]
^13^ pues, si vivís según la carne, moriréis. Pero si con el Espíritu hacéis morir las obras del cuerpo, viviréis.

[[romans-8-14]]
^14^ En efecto, todos los que son guiados por el Espíritu de Dios son hijos de Dios.

[[romans-8-15]]
^15^ Pues no recibisteis un espíritu de esclavos para recaer en el temor; antes bien, recibisteis un espíritu de hijos adoptivos que nos hace exclamar: ¡Abbá, Padre!

[[romans-8-16]]
^16^ El Espíritu mismo se une a nuestro espíritu para dar testimonio de que somos hijos de Dios.

[[romans-8-17]]
^17^ Y, si hijos, también herederos: herederos de Dios y coherederos de Cristo, ya que sufrimos con él, para ser también con él glorificados.

[[romans-8-18]]
^18^ Porque estimo que los sufrimientos del tiempo presente no son comparables con la gloria que se ha de manifestar en nosotros.

[[romans-8-19]]
^19^ Pues la ansiosa espera de la creación desea vivamente la revelación de los hijos de Dios.

[[romans-8-20]]
^20^ La creación, en efecto, fue sometida a la vanidad, no espontaneamente, sino por aquel que la sometió, en la esperanza

[[romans-8-21]]
^21^ de ser liberada de la servidumbre de la corrupción para participar en la gloriosa libertad de los hijos de Dios.

[[romans-8-22]]
^22^ Pues sabemos que la creación entera gime hasta el presente y sufre dolores de parto.

[[romans-8-23]]
^23^ Y no sólo ella; también nosotros, que poseemos las primicias del Espíritu, nosotros mismos gemimos en nuestro interior anhelando el rescate de nuestro cuerpo.

[[romans-8-24]]
^24^ Porque nuestra salvación es en esperanza; y una esperanza que se ve, no es esperanza, pues ¿cómo es posible esperar una cosa que se ve?

[[romans-8-25]]
^25^ Pero esperar lo que no vemos, es aguardar con paciencia.

[[romans-8-26]]
^26^ Y de igual manera, el Espíritu viene en ayuda de nuestra flaqueza. Pues nosotros no sabemos cómo pedir para orar como conviene; mas el Espíritu mismo intercede por nosotros con gemidos inefables,

[[romans-8-27]]
^27^ y el que escruta los corazones conoce cuál es la aspiración del Espíritu, y que su intercesión a favor de los santos es según Dios.

[[romans-8-28]]
^28^ Por lo demas, sabemos que en todas las cosas interviene Dios para bien de los que le aman; de aquellos que han sido llamados según su designio.

[[romans-8-29]]
^29^ Pues a los que de antemano conoció, también los predestinó a reproducir la imagen de su Hijo, para que fuera él el primogenito entre muchos hermanos;

[[romans-8-30]]
^30^ y a los que predestinó, a ésos también los justificó; a los que justificó, a ésos también los glorificó.

[[romans-8-31]]
^31^ Ante esto ¿qué diremos? Si Dios está por nosotros ¿quién contra nosotros?

[[romans-8-32]]
^32^ El que no perdonó ni a su propio Hijo, antes bien le entregó por todos nosotros, ¿cómo no nos dará con él graciosamente todas las cosas?

[[romans-8-33]]
^33^ ¿Quién acusará a los elegidos de Dios? Dios es quien justifica.

[[romans-8-34]]
^34^ ¿Quién condenará? ¿Acaso Cristo Jesús, el que murió; más aún el que resucitó, el que está a la diestra de Dios, y que intercede por nosotros?

[[romans-8-35]]
^35^ ¿Quién nos separará del amor de Cristo? ¿La tribulación?, ¿la angustia?, ¿la persecución?, ¿el hambre?, ¿la desnudez?, ¿los peligros?, ¿la espada?,

[[romans-8-36]]
^36^ como dice la Escritura: Por tu causa somos muertos todo el día; tratados como ovejas destinadas al matadero.

[[romans-8-37]]
^37^ Pero en todo esto salimos vencedores gracias a aquel que nos amó.

[[romans-8-38]]
^38^ Pues estoy seguro de que ni la muerte ni la vida ni los ángeles ni los principados ni lo presente ni lo futuro ni las potestades

[[romans-8-39]]
^39^ ni la altura ni la profundidad ni otra criatura alguna podrá separarnos del amor de Dios manifestado en Cristo Jesús Señor nuestro.
[[romans-9]]
== Capítulo 9

[[romans-9-1]]
^1^ Digo la verdad en Cristo, no miento, - mi conciencia me lo atestigua en el Espíritu Santo -,

[[romans-9-2]]
^2^ siento una gran tristeza y un dolor incesante en el corazón.

[[romans-9-3]]
^3^ Pues desearía ser yo mismo anatema, separado de Cristo, por mis hermanos, los de mi raza según la carne,

[[romans-9-4]]
^4^ - los israelitas -, de los cuales es la adopción filial, la gloria, las alianzas, la legislación, el culto, las promesas,

[[romans-9-5]]
^5^ y los patriarcas; de los cuales también procede Cristo según la carne, el cual está por encima de todas las cosas, Dios bendito por los siglos. Amén.

[[romans-9-6]]
^6^ No es que haya fallado la palabra de Dios. Pues no todos los descendientes de Israel son Israel.

[[romans-9-7]]
^7^ Ni por ser descendientes de Abraham, son todos hijos. Sino que «por Isaac llevará tu nombre una descendencia»;

[[romans-9-8]]
^8^ es decir: no son hijos de Dios los hijos según la carne, sino que los hijos de la promesa se cuentan como descendencia.

[[romans-9-9]]
^9^ Porque éstas son las palabras de la promesa: «Por este tiempo volveré; y Sara tendrá un hijo».

[[romans-9-10]]
^10^ Y más aún; también Rebeca concibió de un solo hombre, nuestro padre Isaac;

[[romans-9-11]]
^11^ ahora bien, antes de haber nacido, y cuando no habian hecho ni bien ni mal - para que se mantuviese la libertad de la elección divina,

[[romans-9-12]]
^12^ que depende no de las obras sino del que llama - le fue dicho a Rebeca: El mayor servirá al menor,

[[romans-9-13]]
^13^ como dice la Escritura: Amé a Jacob y odié a Esaú.

[[romans-9-14]]
^14^ ¿Qué diremos, pues? ¿Que hay injusticia en Dios? ¡De ningún modo!

[[romans-9-15]]
^15^ Pues dice él a Moisés: Seré misericordioso con quien lo sea: me apiadaré de quien me apiade.

[[romans-9-16]]
^16^ Por tanto, no se trata de querer o de correr, sino de que Dios tenga misericordia.

[[romans-9-17]]
^17^ Pues dice la Escritura a Faraón: Te he suscitado precisamente para mostrar en ti mi poder, y para que mi nombre sea conocido en toda la tierra.

[[romans-9-18]]
^18^ Así pues, usa de misericordia con quien quiere, y endurece a quien quiere.

[[romans-9-19]]
^19^ Pero me dirás: Entonces ¿de qué se enoja? Pues ¿quién puede resistir a su voluntad?

[[romans-9-20]]
^20^ ¡Oh hombre! Pero ¿quién eres tú para pedir cuentas a Dios? ¿Acaso la pieza de barro dirá a quien la modeló: “por qué me hiciste así”?

[[romans-9-21]]
^21^ O ¿es que el alfarero no es dueño de hacer de una misma masa unas vasijas para usos nobles y otras para usos despreciables?

[[romans-9-22]]
^22^ Pues bien, si Dios, queriendo manifestar su cólera y dar a conocer su poder, soportó con gran paciencia objetos de cólera preparados para la perdición,

[[romans-9-23]]
^23^ a fin de dar a conocer la riqueza de su gloria con los objetos de misericordia que de antemano había preparado para gloria:

[[romans-9-24]]
^24^ con nosotros, que hemos sido llamados no sólo de entre los judíos sino también de entre los gentiles...

[[romans-9-25]]
^25^ Como dice también en Oseas: Llamaré pueblo mío al que no es mi pueblo: y amada mía a la que no es mi amada.

[[romans-9-26]]
^26^ Y en el lugar mismo en que se les dijo: No sois mi pueblo, serán llamados: Hijos de Dios vivo.

[[romans-9-27]]
^27^ Isaías también clama en favor de Israel: Aunque los hijos de Israel fueran numerosos como las arenas del mar, sólo el resto será salvo.

[[romans-9-28]]
^28^ Porque pronta y perfectamente cumplirá el Señor su palabra sobre la tierra.

[[romans-9-29]]
^29^ Y como predijo Isaías: Si el Señor de los ejércitos no nos dejara una descendencia, como Sodoma hubiéramos venido a ser, y semejantes a Gomorra.

[[romans-9-30]]
^30^ ¿Qué diremos, pues? Que los gentiles, que no buscaban la justicia, han hallado la justicia - la justicia de la fe -

[[romans-9-31]]
^31^ mientras Israel, buscando una ley de justicia, no llegó a cumplir la ley.

[[romans-9-32]]
^32^ ¿Por qué? Porque la buscaba no en la fe sino en las obras. Tropezaron contra la piedra de tropiezo,

[[romans-9-33]]
^33^ como dice la Escritura: He aquí que pongo en Sión piedra de tropiezo y roca de escándalo; mas el que crea en él, no será confundido.
[[romans-10]]
== Capítulo 10

[[romans-10-1]]
^1^ Hermanos, el anhelo de mi corazón y mi oración a Dios en favor de ellos es que se salven.

[[romans-10-2]]
^2^ Testifico en su favor que tienen celo de Dios, pero no conforme a un pleno conocimiento.

[[romans-10-3]]
^3^ Pues desconociendo la justicia de Dios y empeñándose en establecer la suya propia, no se sometieron a la justicia de Dios.

[[romans-10-4]]
^4^ Porque el fin de la ley es Cristo, para justificación de todo creyente.

[[romans-10-5]]
^5^ En efecto, Moisés escribe acerca de la justicia que nace de la ley: Quien la cumpla, vivirá por ella.

[[romans-10-6]]
^6^ Mas la justicia que viene de la fe dice así: No digas en tu corazón ¿quién subirá al cielo?, es decir: para hacer bajar a Cristo;

[[romans-10-7]]
^7^ o bien: ¿quién bajará al abismo?, es decir: para hacer subir a Cristo de entre los muertos.

[[romans-10-8]]
^8^ Entonces, ¿qué dice? Cerca de ti está la palabra: en tu boca y en tu corazón, es decir, la palabra de la fe que nosotros proclamamos.

[[romans-10-9]]
^9^ Porque, si confiesas con tu boca que Jesús es Señor y crees en tu corazón que Dios le resucitó de entre los muertos, serás salvo.

[[romans-10-10]]
^10^ Pues con el corazón se cree para conseguir la justicia, y con la boca se confiesa para conseguir la salvación.

[[romans-10-11]]
^11^ Porque dice la Escritura: Todo el que crea en él no será confundido.

[[romans-10-12]]
^12^ Que no hay distinción entre judío y griego, pues uno mismo es el Señor de todos, rico para todos los que le invocan.

[[romans-10-13]]
^13^ Pues todo el que invoque el nombre del Señor se salvará.

[[romans-10-14]]
^14^ Pero ¿cómo invocarán a aquel en quien no han creído? ¿Cómo creerán en aquel a quien no han oído? ¿Cómo oirán sin que se les predique?

[[romans-10-15]]
^15^ Y ¿cómo predicarán si no son enviados? Como dice la Escritura: ¡Cuán hermosos los pies de los que anuncian el bien!

[[romans-10-16]]
^16^ Pero no todos obedecieron a la Buena Nueva. Porque Isaías dice: ¡Señor!, ¿quién ha creído a nuestra predicación?

[[romans-10-17]]
^17^ Por tanto, la fe viene de la predicación, y la predicación, por la Palabra de Cristo.

[[romans-10-18]]
^18^ Y pregunto yo: ¿Es que no han oído? ¡Cierto que sí! Por toda la tierra se ha difundido su voz y hasta los confines de la tierra sus palabras.

[[romans-10-19]]
^19^ Pero pregunto: ¿Es que Israel no comprendió? Moisés es el primero en decir: Os volveré celosos de una que no es nación; contra una nación estúpida os enfureceré.

[[romans-10-20]]
^20^ Isaías, a su vez, se atreve a decir: Fui hallado de quienes no me buscaban; me manifesté a quienes no preguntaban por mi.

[[romans-10-21]]
^21^ Mas a Israel dice: Todo el día extendí mis manos hacia un pueblo incrédulo y rebelde.
[[romans-11]]
== Capítulo 11

[[romans-11-1]]
^1^ Y pregunto yo: ¿Es que ha rechazado Dios a su pueblo? ¡De ningún modo! ¡Que también yo soy israelita, del linaje de Abraham, de la tribu de Benjamín!

[[romans-11-2]]
^2^ Dios no ha rechazado a su pueblo, en quien de antemano puso sus ojos. ¿O es que ignoráis lo que dice la Escritura acerca de Elías, cómo se queja ante Dios contra Israel?

[[romans-11-3]]
^3^ ¡Señor!, han dado muerte a tus profetas; han derribado tus altares; y he quedado yo solo y acechan contra mi vida.

[[romans-11-4]]
^4^ Y ¿qué le responde el oráculo divino? Me he reservado 7.000 hombres que no han doblado la rodilla ante Baal.

[[romans-11-5]]
^5^ Pues bien, del mismo modo, también en el tiempo presente subsiste un resto elegido por gracia.

[[romans-11-6]]
^6^ Y, si es por gracia, ya no lo es por las obras; de otro modo, la gracia no sería ya gracia.

[[romans-11-7]]
^7^ Entonces, ¿qué? Que Israel no consiguió lo que buscaba; mientras lo consiguieron los elegidos. Los demás se endurecieron,

[[romans-11-8]]
^8^ como dice la Escritura: Dioles Dios un esp1ritu de embotamiento: ojos para no ver y oídos para no oír, hasta el día de hoy.

[[romans-11-9]]
^9^ David también dice: Conviértase su mesa en trampa y lazo, en piedra de tropiezo y justo pago,

[[romans-11-10]]
^10^ oscurézcanse sus ojos para no ver; agobia sus espaldas sin cesar.

[[romans-11-11]]
^11^ Y pregunto yo: ¿Es que han tropezado para quedar caídos? ¡De ningún modo! Sino que su caída ha traído la salvación a los gentiles, para llenarlos de celos.

[[romans-11-12]]
^12^ Y, si su caída ha sido una riqueza para el mundo, y su mengua, riqueza para los gentiles ¡qué no será su plenitud!

[[romans-11-13]]
^13^ Os digo, pues, a vosotros, los gentiles: Por ser yo verdaderamente apóstol de los gentiles, hago honor a mi ministerio,

[[romans-11-14]]
^14^ pero es con la esperanza de despertar celos en los de mi raza y salvar a alguno de ellos.

[[romans-11-15]]
^15^ Porque si su reprobación ha sido la reconciliación del mundo ¿qué será su readmisión sino una resurrección de entre los muertos?

[[romans-11-16]]
^16^ Y si las primicias son santas, también la masa; y si la raíz es santa también las ramas.

[[romans-11-17]]
^17^ Que si algunas ramas fueron desgajadas, mientras tú - olivo silvestre - fuiste injertado entre ellas, hecho participe con ellas de la raíz y de la savia del olivo,

[[romans-11-18]]
^18^ no te engrías contra las ramas. Y si te engríes, sábete que no eres tú quien sostiene la raíz, sino la raíz que te sostiene.

[[romans-11-19]]
^19^ Pero dirás: Las ramas fueron desgajadas para que yo fuera injertado.

[[romans-11-20]]
^20^ ¡Muy bien! Por su incredulidad fueron desgajadas, mientras tú, por la fe te mantienes. ¡No te engrías!; más bien, teme.

[[romans-11-21]]
^21^ Que si Dios no perdonó a las ramas naturales, no sea que tampoco a ti te perdone.

[[romans-11-22]]
^22^ Así pues, considera la bondad y la severidad de Dios: severidad con los que cayeron, bondad contigo, si es que te mantienes en la bondad; que si no, también tú serás desgajado.

[[romans-11-23]]
^23^ En cuanto a ellos, si no se obstinan en la incredulidad, serán injertados; que poderoso es Dios para injertarlos de nuevo.

[[romans-11-24]]
^24^ Porque si tú fuiste cortado del olivo silvestre que eras por naturaleza, para ser injertado contra tu natural en un olivo cultivado, ¡con cuánta más razón ellos, según su naturaleza, serán injertados en su propio olivo!

[[romans-11-25]]
^25^ Pues no quiero que ignoréis, hermanos, este misterio, no sea que presumáis de sabios: el endurecimiento parcial que sobrevino a Israel durará hasta que entre la totalidad de los gentiles,

[[romans-11-26]]
^26^ y así, todo Israel será salvo, como dice la Escritura: Vendrá de Sión el Libertador; alejará de Jacob las impiedades.

[[romans-11-27]]
^27^ Y esta será mi Alianza con ellos, cuando haya borrado sus pecados.

[[romans-11-28]]
^28^ En cuanto al Evangelio, son enemigos para vuestro bien; pero en cuanto a la elección amados en atención a sus padres.

[[romans-11-29]]
^29^ Que los dones y la vocación de Dios son irrevocables.

[[romans-11-30]]
^30^ En efecto, así como vosotros fuisteis en otro tiempo rebeldes contra Dios, mas al presente habéis conseguido misericordia a causa de su rebeldía,

[[romans-11-31]]
^31^ así también, ellos al presente se han rebelado con ocasión de la misericordia otorgada a vosotros, a fin de que también ellos consigan ahora misericordia.

[[romans-11-32]]
^32^ Pues Dios encerró a todos los hombres en la rebeldía para usar con todos ellos de misericordia.

[[romans-11-33]]
^33^ ¡Oh abismo de la riqueza, de la sabiduría y de la ciencia de Dios! ¡Cuán insondables son sus designios e inescrutables sus caminos!

[[romans-11-34]]
^34^ En efecto, ¿quién conoció el pensamiento de Señor? O ¿quién fue su consejero? O ¿quién le dio primero que tenga derecho a la recompensa?

[[romans-11-35]]
^35^ Porque de él, por él y para él son todas las cosas. ¡A él la gloria por los siglos! Amén.
[[romans-12]]
== Capítulo 12

[[romans-12-1]]
^1^ Os exhorto, pues, hermanos, por la misericordia de Dios, que ofrezcáis vuestros cuerpos como una víctima viva, santa, agradable a Dios: tal será vuestro culto espiritual.

[[romans-12-2]]
^2^ Y no os acomodéis al mundo presente, antes bien transformaos mediante la renovación de vuestra mente, de forma que podáis distinguir cuál es la voluntad de Dios: lo bueno, lo agradable, lo perfecto.

[[romans-12-3]]
^3^ En virtud de la gracia que me fue dada, os digo a todos y a cada uno de vosotros: No os estiméis en más de lo que conviene; tened más bien una sobria estima según la medida de la fe que otorgó Dios a cada cual.

[[romans-12-4]]
^4^ Pues, así como nuestro cuerpo, en su unidad, posee muchos miembros, y no desempeñan todos los miembros la misma función,

[[romans-12-5]]
^5^ así también nosotros, siendo muchos, no formamos más que un solo cuerpo en Cristo, siendo cada uno por su parte los unos miembros de los otros.

[[romans-12-6]]
^6^ Pero teniendo dones diferentes, según la gracia que nos ha sido dada, si es el don de profecía, ejerzámoslo en la medida de nuestra fe;

[[romans-12-7]]
^7^ si es el ministerio, en el ministerio; la enseñanza, enseñando;

[[romans-12-8]]
^8^ la exhortación, exhortando. El que da, con sencillez; el que preside, con solicitud; el que ejerce la misericordia, con jovialidad.

[[romans-12-9]]
^9^ Vuestra caridad sea sin fingimiento; detestando el mal, adhiriéndoos al bien;

[[romans-12-10]]
^10^ amándoos cordialmente los unos a los otros; estimando en más cada uno a los otros;

[[romans-12-11]]
^11^ con un celo sin negligencia; con esp1ritu fervoroso; sirviendo al Señor;

[[romans-12-12]]
^12^ con la alegría de la esperanza; constantes en la tribulación; perseverantes en la oración;

[[romans-12-13]]
^13^ compartiendo las necesitades de los santos; practicando la hospitalidad.

[[romans-12-14]]
^14^ Bendecid a los que os persiguen, no maldigáis.

[[romans-12-15]]
^15^ Alegraos con los que se alegran; llorad con los que lloran.

[[romans-12-16]]
^16^ Tened un mismo sentir los unos para con los otros; sin complaceros en la altivez; atraídos más bien por lo humilde; no os complazcáis en vuestra propia sabiduria.

[[romans-12-17]]
^17^ Sin devolver a nadie mal por mal; procurando el bien ante todos los hobres:

[[romans-12-18]]
^18^ en lo posible, y en cuanto de vosotros dependa, en paz con todos los hombres;

[[romans-12-19]]
^19^ no tomando la justicia por cuenta vuestra, queridos míos, dejad lugar a la Cólera, pues dice la Escritura: Mía es la venganza: yo daré el pago merecido, dice el Señor.

[[romans-12-20]]
^20^ Antes al contrario: si tu enemigo tiene hambre, dale de comer; y si tiene sed, dale de beber; haciéndolo así, amontonarás ascuas sobre su cabeza.

[[romans-12-21]]
^21^ No te dejes vencer por el mal; antes bien, vence al mal con el bien.
[[romans-13]]
== Capítulo 13

[[romans-13-1]]
^1^ Sométanse todos a las autoridades constituidas, pues no hay autoridad que no provenga de Dios, y las que existen, por Dios han sido constituidas.

[[romans-13-2]]
^2^ De modo que, quien se opone a la autoridad, se rebela contra el orden divino, y los rebeldes se atraerán sobre sí mismos la condenación.

[[romans-13-3]]
^3^ En efecto, los magistrados no son de temer cuando se obra el bien, sino cuando se obra el mal. ¿Quieres no temer la autoridad? Obra el bien, y obtiendrás de ella elogios,

[[romans-13-4]]
^4^ pues es para ti un servidor de Dios para el bien. Pero, si obras el mal, teme: pues no en vano lleva espada: pues es un servidor de Dios para hacer justicia y castigar al que obra el mal.

[[romans-13-5]]
^5^ Por tanto, es preciso someterse, no sólo por temor al castigo, sino también en conciencia.

[[romans-13-6]]
^6^ Por eso precisamente pagáis los impuestos, porque son funcionarios de Dios, ocupados asiduamente en ese oficio.

[[romans-13-7]]
^7^ Dad a cada cual lo que se debe: a quien impuestos, impuestos; a quien tributo, tributo; a quien respeto, respeto; a quien honor, honor.

[[romans-13-8]]
^8^ Con nadie tengáis otra deuda que la del mutuo amor. Pues el que ama al prójimo, ha cumplido la ley.

[[romans-13-9]]
^9^ En efecto, lo de: No adulterarás, no matarás, no robarás, no codiciarás y todos los demás preceptos, se resumen en esta fórmula: Amarás a tu prójimo como a ti mismo.

[[romans-13-10]]
^10^ La caridad no hace mal al prójimo. La caridad es, por tanto, la ley en su plenitud.

[[romans-13-11]]
^11^ Y esto, teniendo en cuenta el momento en que vivimos. Porque es ya hora de levantaros del sueño; que la salvación está más cerca de nosotros que cuando abrazamos la fe.

[[romans-13-12]]
^12^ La noche está avanzada. El día se avecina. Despojémonos, pues, de las obras de las tinieblas y revistámonos de las armas de la luz.

[[romans-13-13]]
^13^ Como en pleno día, procedamos con decoro: nada de comilonas y borracheras; nada de lujurias y desenfrenos; nada de rivalidades y envidias.

[[romans-13-14]]
^14^ Revestíos más bien del Señor Jesucristo y no os preocupéis de la carne para satisfacer sus concupiscencias.
[[romans-14]]
== Capítulo 14

[[romans-14-1]]
^1^ Acoged bien al que es débil en la fe, sin discutir opiniones.

[[romans-14-2]]
^2^ Uno cree poder comer de todo, mientras el débil no come más que verduras.

[[romans-14-3]]
^3^ El que come, no desprecie al que no come; y el que no come, tampoco juzgue al que come, pues Dios le ha acogido.

[[romans-14-4]]
^4^ ¿Quién eres tú para juzgar al criado ajeno? Que se mantenga en pie o caiga sólo interesa a su amo; pero quedará en pie, pues poderoso es el Señor para sostenerlo.

[[romans-14-5]]
^5^ Este da preferencia a un día sobre todo; aquél los considera todos iguales. ¡Aténgase cada cual a su conciencia!

[[romans-14-6]]
^6^ El que se preocupa por los días, lo hace por el Señor; el que come, lo hace por el Señor, pues da gracias a Dios: y el que no come, lo hace por el Señor, y da gracias a Dios.

[[romans-14-7]]
^7^ Porque ninguno de nosotros vive para sí mismo; como tampoco muere nadie para sí mismo.

[[romans-14-8]]
^8^ Si vivimos, para el Señor vivimos; y si morimos, para el Señor morimos. Así que, ya vivamos ya muramos, del Señor somos.

[[romans-14-9]]
^9^ Porque Cristo murió y volvió a la vida para eso, para ser Señor de muertos y vivos.

[[romans-14-10]]
^10^ Pero tú ¿por qué juzgas a tu hermano? Y tú ¿por qué desprecias a tu hermano? En efecto, todos hemos de comparecer ante el tribunal de Dios,

[[romans-14-11]]
^11^ pues dice la Escritura: ¡Por mi vida!, dice el Señor, que toda rodilla se doblará ante mí, y toda lengua bendecirá a Dios.

[[romans-14-12]]
^12^ Así pues, cada uno de vosotros dará cuenta de sí mismo a Dios.

[[romans-14-13]]
^13^ Dejemos, por tanto, de juzgarnos los unos a los otros: juzgad más bien que no se debe poner tropiezo o escándalo al hermano. -

[[romans-14-14]]
^14^ Bien sé, y estoy persuadido de ello en el Señor Jesús, que nada hay de suyo impuro; a no ser para el que juzga que algo es impuro, para ése si lo hay -.

[[romans-14-15]]
^15^ Ahora bien, si por un alimento tu hermano se entristece, tú no procedes ya según la caridad. ¡Que por tu comida no destruyas a aquel por quien murió Cristo!

[[romans-14-16]]
^16^ Por tanto, no expongáis a la maledicencia vuestro privilegio.

[[romans-14-17]]
^17^ Que el Reino de Dios no es comida ni bebida, sino justicia y paz y gozo en el Espíritu Santo.

[[romans-14-18]]
^18^ Toda vez que quien así sirve a Cristo, se hace grato a Dios y aprobado por los hombres.

[[romans-14-19]]
^19^ Procuremos, por tanto, lo que fomente la paz y la mutua edificación.

[[romans-14-20]]
^20^ No vayas a destruir la obra de Dios por un alimento. Todo es puro, ciertamente, pero es malo comer dando escándalo.

[[romans-14-21]]
^21^ Lo bueno es no comer carne, ni beber vino, ni hacer cosa que sea para tu hermano ocasión de caída, tropiezo o debilidad.

[[romans-14-22]]
^22^ La fe que tú tienes, guárdala para ti delante de Dios. ¡Dichoso aquel que no se juzga culpable a sí mismo al decidirse!

[[romans-14-23]]
^23^ Pero el que come dudando, se condena, porque no obra conforme a la fe; pues todo lo que no procede de la buena fe es pecado.
[[romans-15]]
== Capítulo 15

[[romans-15-1]]
^1^ Nosotros, los fuertes, debemos sobrellevar las flaquezas de los débiles y no buscar nuestro propio agrado.

[[romans-15-2]]
^2^ Que cada uno de nosotros trate de agradar a su prójimo para el bien, buscando su edificación;

[[romans-15-3]]
^3^ pues tampoco Cristo buscó su propio agrado, antes bien, como dice la Escritura: Los ultrajes de los que te ultrajaron cayeron sobre mi.

[[romans-15-4]]
^4^ En efecto todo cuanto fue escrito en el pasado, se escribió para enseñanza nuestra, para que con la paciencia y el consuelo que dan las Escrituras mantengamos la esperanza.

[[romans-15-5]]
^5^ Y el Dios de la paciencia y del consuelo os conceda tener los unos para con los otros los mismos sentimientos, según Cristo Jesús,

[[romans-15-6]]
^6^ para que unánimes, a una voz, glorifiquéis al Dios y Padre de nuestro Señor Jesucristo.

[[romans-15-7]]
^7^ Por tanto, acogeos mutuamente como os acogio Cristo para gloria de Dios.

[[romans-15-8]]
^8^ Pues afirmo que Cristo se puso al servicio de los circuncisos a favor de la veracidad de Dios, para dar cumplimiento a las promesas hechas a los patriarcas,

[[romans-15-9]]
^9^ y para que los gentiles glorificasen a Dios por su misericordia, como dice la Escritura: Por eso te bendeciré entre los gentiles y ensalzaré tu nombre.

[[romans-15-10]]
^10^ Y en otro lugar: Gentiles, regocijaos juntamente con su pueblo;

[[romans-15-11]]
^11^ y de nuevo: Alabad, gentiles todos, al Señor y cántenle himnos todos los pueblos.

[[romans-15-12]]
^12^ Y a su vez Isaías dice: Aparecerá el retoño de Jesé, el que se levanta para imperar sobre los gentiles. En él pondrán los gentiles su esperanza.

[[romans-15-13]]
^13^ El Dios de la esperanza os colme de todo gozo y paz en vuestra fe, hasta rebosar de esperanza por la fuerza del Espíritu Santo.

[[romans-15-14]]
^14^ Por mi parte estoy persuadido, hermanos míos, en lo que a vosotros toca, de que también vosotros estáis llenos de buenas disposiciones, henchidos de todo conocimiento y capacitados también para amonestaros mutuamente.

[[romans-15-15]]
^15^ Sin embargo, en algunos pasajes os he escrito con cierto atrevimiento, como para reavivar vuestros recuerdos, en virtud de la gracia que me ha sido otorgada por Dios,

[[romans-15-16]]
^16^ de ser para los gentiles ministro de Cristo Jesús, ejerciendo el sagrado oficio del Evangelio de Dios, para que la oblación de los gentiles sea agradable, santificada por el Espíritu Santo.

[[romans-15-17]]
^17^ Tengo, pues, de qué gloriarme en Cristo Jesús en lo referente al servicio de Dios.

[[romans-15-18]]
^18^ Pues no me atreveré a hablar de cosa alguna que Cristo no haya realizado por medio de mi para conseguir la obediencia de los gentiles, de palabra y de obra,

[[romans-15-19]]
^19^ en virtud de señales y prodigios, en virtud del Espíritu de Dios, tanto que desde Jerusalén y en todas direcciones hasta el Ilírico he dado cumplimiento al Evangelio de Cristo;

[[romans-15-20]]
^20^ teniendo así, como punto de honra, no anunciar el Evangelio sino allí donde el nombre de Cristo no era aún conocido, para no construir sobre cimientos ya puestos por otros,

[[romans-15-21]]
^21^ antes bien, como dice la Escritura: Los que ningún anuncio recibieron de él, le verán, y los que nada oyeron, comprenderán.

[[romans-15-22]]
^22^ Esa era la razón por la cual siempre me veía impedido de llegar hasta vosotros.

[[romans-15-23]]
^23^ Mas ahora, no teniendo ya campo de acción en estas regiones, y deseando vivamente desde hace muchos años ir donde vosotros,

[[romans-15-24]]
^24^ cuando me dirija a España... Pues espero veros al pasar, y ser encaminado por vosotros hacia allá, después de haber disfrutado un poco de vuestra compañía.

[[romans-15-25]]
^25^ Mas, por ahora, voy a Jerusalén para el servicio de los santos,

[[romans-15-26]]
^26^ pues Macedonia y Acaya tuvieron a bien hacer una colecta en favor de los pobres de entre los santos de Jerusalén.

[[romans-15-27]]
^27^ Lo tuvieron a bien, y debían hacérselo; pues si los gentiles han participado en sus bienes espirituales, ellos a su vez deben servirles con sus bienes temporales.

[[romans-15-28]]
^28^ Así que, una vez terminado este asunto, y entregado oficialmente el fruto de la colecta, partiré para España, pasando por vosotros.

[[romans-15-29]]
^29^ Y bien sé que, al ir a vosotros, lo haré con la plenitud de las bendiciones de Cristo.

[[romans-15-30]]
^30^ Pero os suplico, hermanos, por nuestro Señor Jesucristo y por el amor del Espíritu Santo, que luchéis juntamente conmigo en vuestras oraciones rogando a Dios por mí,

[[romans-15-31]]
^31^ para que me vea libre de los incredulos de Judea, y el socorro que llevo a Jerusalén sea bien recibido por los santos;

[[romans-15-32]]
^32^ y pueda también llegar con alegría a vosotros por la voluntad de Dios, y disfrutar de algún reposo entre vosotros.

[[romans-15-33]]
^33^ El Dios de la paz sea con todos vosotros. Amén.
[[romans-16]]
== Capítulo 16

[[romans-16-1]]
^1^ Os recomiendo a Febe, nuestra hermana, diaconisa de la Iglesia de Cencreas.

[[romans-16-2]]
^2^ Recibidla en el Señor de una manera digna de los santos, y asistidla en cualquier cosa que necesite de vosotros, pues ella ha sido protectora de muchos, incluso de mí mismo.

[[romans-16-3]]
^3^ Saludad a Prisca y Aquila, colaboradores míos en Cristo Jesús.

[[romans-16-4]]
^4^ Ellos expusieron sus cabezas para salvarme. Y no soy solo en agradecérselo, sino también todas las Iglesias de la gentilidad;

[[romans-16-5]]
^5^ saludad también a la Iglesia que se reúne en su casa. Saludad a mi querido Epéneto, primicias del Asia para Cristo.

[[romans-16-6]]
^6^ Saludad a María, que se ha afanado mucho por vosotros.

[[romans-16-7]]
^7^ Saludad a Andrónico y Junia, mis parientes y compañeros de prisión, ilustres entre los apóstoles, que llegaron a Cristo antes que yo.

[[romans-16-8]]
^8^ Saludad a Ampliato, mi amado en el Señor.

[[romans-16-9]]
^9^ Saludad a Urbano, colaborador nuestro en Cristo; y a mi querido Estaquio.

[[romans-16-10]]
^10^ Saludad a Apeles, que ha dado buenas pruebas de sí en Cristo. Saludad a los de la casa de Aristóbulo.

[[romans-16-11]]
^11^ Saludad a mi pariente Herodión. Saludad a los de la casa de Narciso, en el Señor.

[[romans-16-12]]
^12^ Saludad a Trifena y a Trifosa, que se han fatigado en el Señor. Saludad a la amada Pérside, que trabajó mucho en el Señor.

[[romans-16-13]]
^13^ Saludad a Rufo, el escogido del Señor; y a su madre, que lo es también mía.

[[romans-16-14]]
^14^ Saludad a Asíncrito y Flegonta, a Hermes, a Patrobas, a Hermas y a los hermanos que están con ellos.

[[romans-16-15]]
^15^ Saludad a Filólogo y a Julia, a Nereo y a su hermana, lo mismo que a Olimpas y a todos los santos que están con ellos.

[[romans-16-16]]
^16^ Saludaos los unos a los otros con el beso santo. Todas las Iglesias de Cristo os saludan.

[[romans-16-17]]
^17^ Os ruego, hermanos, que os guardéis de los que suscitan divisiones y escándalos contra la doctrina que habéis aprendido; apartaos de ellos,

[[romans-16-18]]
^18^ pues esos tales no sirven a nuestro Señor Jesucristo, sino a su propio vientre, y, por medio de suaves palabras y lisonjas, seducen los corazones de los sencillos.

[[romans-16-19]]
^19^ Vuestra obediencia se ha divulgado por todas partes; por lo cual, me alegro de vosotros. Pero quiero que seáis ingeniosos para el bien e inocentes para el mal.

[[romans-16-20]]
^20^ Y el Dios de la paz aplastará bien pronto a Satanás bajo vuestros pies. La gracia de nuestro Señor Jesucristo sea con vosotros.

[[romans-16-21]]
^21^ Os saluda Timoteo, mi colaborador, lo mismo que Lucio, Jasón y Sosípatro, mis parientes.

[[romans-16-22]]
^22^ Os saludo en el Señor yo, Tercio, que he escrito esta carta.

[[romans-16-23]]
^23^ Os saluda Gayo, huésped mío y de toda la Iglesia.

[[romans-16-25]]
^25^ Os saluda Erasto, cuestor de la ciudad, y Cuarto, nuestro hermano. A Aquel que puede consolidaros conforme al Evangelio mío y la predicación de Jesucristo: revelación de un Misterio mantenido en secreto durante siglos eternos,

[[romans-16-26]]
^26^ pero manifestado al presente, por la Escrituras que lo predicen, por disposición del Dios eterno, dado a conocer a todos los gentiles para obediencia de la fe,

[[romans-16-27]]
^27^ a Dios, el único sabio, por Jesucristo, ¡a él la gloria por los siglos de los siglos! Amén.
