[[galatians]]
= Gálatas

[[galatians-1]]
== Capítulo 1

[[galatians-1-1]]
^1^ Pablo, apóstol, no de parte de los hombres ni por mediación de hombre alguno, sino por Jesucristo y Dios Padre, que le resucitó de entre los muertos,

[[galatians-1-2]]
^2^ y todos los hermanos que conmigo están, a las Iglesias de Galacia.

[[galatians-1-3]]
^3^ Gracia a vosotros y paz de parte de Dios, nuestro Padre, y del Señor Jesucristo,

[[galatians-1-4]]
^4^ que se entregó a sí mismo por nuestros pecados, para librarnos de este mundo perverso, según la voluntad de nuestro Dios y Padre,

[[galatians-1-5]]
^5^ a quien sea la gloria por los siglos de los siglos. Amén.

[[galatians-1-6]]
^6^ Me maravillo de que abandonando al que os llamó por la gracia de Cristo, os paséis tan pronto a otro evangelio

[[galatians-1-7]]
^7^ - no que haya otro, sino que hay algunos que os perturban y quieren deformar el Evangelio de Cristo -.

[[galatians-1-8]]
^8^ Pero aun cuando nosotros mismos o un ángel del cielo os anunciara un evangelio distinto del que os hemos anunciado, ¡sea anatema!

[[galatians-1-9]]
^9^ Como lo tenemos dicho, también ahora lo repito: Si alguno os anuncia un evangelio distinto del que habéis recibido, ¡sea anatema!

[[galatians-1-10]]
^10^ Porque ¿busco yo ahora el favor de los hombres o el de Dios? ¿O es que intento agradar a los hombres? Si todavía tratara de agradar a los hombres, ya no sería siervo de Cristo.

[[galatians-1-11]]
^11^ Porque os hago saber, hermanos, que el Evangelio anunciado por mí, no es de orden humano,

[[galatians-1-12]]
^12^ pues yo no lo recibí ni aprendí de hombre alguno, sino por revelación de Jesucristo.

[[galatians-1-13]]
^13^ Pues ya estáis enterados de mi conducta anterior en el Judaísmo, cuán encarnizadamente perseguía a la Iglesia de Dios y la devastaba,

[[galatians-1-14]]
^14^ y cómo sobrepasaba en el Judaísmo a muchos de mis compatriotas contemporáneos, superándoles en el celo por las tradiciones de mis padres.

[[galatians-1-15]]
^15^ Mas, cuando Aquel que me separó desde el seno de mi madre y me llamó por su gracia, tuvo a bien

[[galatians-1-16]]
^16^ revelar en mí a su Hijo, para que le anunciase entre los gentiles, al punto, sin pedir consejo ni a la carne ni a la sangre,

[[galatians-1-17]]
^17^ sin subir a Jerusalén donde los apóstoles anteriores a mí, me fui a Arabia, de donde nuevamente volví a Damasco.

[[galatians-1-18]]
^18^ Luego, de allí a tres años, subí a Jerusalén para conocer a Cefas y permanecí quince días en su compañía.

[[galatians-1-19]]
^19^ Y no vi a ningún otro apóstol, y sí a Santiago, el hermano del Señor.

[[galatians-1-20]]
^20^ Y en lo que os escribo, Dios me es testigo de que no miento.

[[galatians-1-21]]
^21^ Luego me fui a las regiones de Siria y Cilicia;

[[galatians-1-22]]
^22^ pero personalmente no me conocían las Iglesias de Judea que están en Cristo.

[[galatians-1-23]]
^23^ Solamente habían oído decir: «El que antes nos perseguía ahora anuncia la buena nueva de la fe que entonces quería destruir».

[[galatians-1-24]]
^24^ Y glorificaban a Dios a causa de mí.
[[galatians-2]]
== Capítulo 2

[[galatians-2-1]]
^1^ Luego, al cabo de catorce años, subí nuevamente a Jerusalén con Bernabé, llevando conmigo también a Tito.

[[galatians-2-2]]
^2^ Subí movido por una revelación y les expuse el Evangelio que proclamo entre los gentiles - tomando aparte a los notables - para saber si corría o había corrido en vano.

[[galatians-2-3]]
^3^ Pues bien, ni siquiera Tito que estaba conmigo, con ser griego, fue obligado a circuncidarse.

[[galatians-2-4]]
^4^ Pero, a causa de los intrusos, los falsos hermanos que solapadamente se infiltraron para espiar la libertad que tenemos en Cristo Jesús, con el fin de reducirnos a esclavitud,

[[galatians-2-5]]
^5^ a quienes ni por un instante cedimos, sometiéndonos, a fin de salvaguardar para vosotros la verdad del Evangelio...

[[galatians-2-6]]
^6^ Y de parte de los que eran tenidos por notables - ¡qué me importa lo que fuesen!: en Dios no hay acepción de personas - en todo caso, los notables nada nuevo me impusieron.

[[galatians-2-7]]
^7^ Antes al contrario, viendo que me había sido confiada la evangelización de los incircuncisos, al igual que a Pedro la de los circuncisos,

[[galatians-2-8]]
^8^ - pues el que actuó en Pedro para hacer de él un apóstol de los circuncisos, actuó también en mí para hacerme apóstol de los gentiles -

[[galatians-2-9]]
^9^ y reconociendo la gracia que me había sido concedida, Santiago, Cefas y Juan, que eran considerados como columnas, nos tendieron la mano en señal de comunión a mí y a Bernabé: nosotros nos iríamos a los gentiles y ellos a los circuncisos;

[[galatians-2-10]]
^10^ sólo que nosotros debíamos tener presentes a los pobres, cosa que he procurado cumplir con todo esmero.

[[galatians-2-11]]
^11^ Mas, cuando vino Cefas a Antioquía, me enfrenté con él cara a cara, porque era digno de reprensión.

[[galatians-2-12]]
^12^ Pues antes que llegaran algunos del grupo de Santiago, comía en compañía de los gentiles; pero una vez que aquéllos llegaron, se le vio recatarse y separarse por temor de los circuncisos.

[[galatians-2-13]]
^13^ Y los demás judíos le imitaron en su simulación, hasta el punto de que el mismo Bernabé se vio arrastrado por la simulación de ellos.

[[galatians-2-14]]
^14^ Pero en cuanto vi que no procedían con rectitud, según la verdad del Evangelio, dije a Cefas en presencia de todos: «Si tú, siendo judío, vives como gentil y no como judío, ¿cómo fuerzas a los gentiles a judaizar?»

[[galatians-2-15]]
^15^ Nosotros somos judíos de nacimiento y no gentiles pecadores; a pesar de todo,

[[galatians-2-16]]
^16^ conscientes de que el hombre no se justifica por las obras de la ley sino sólo por la fe en Jesucristo, también nosotros hemos creído en Cristo Jesús a fin de conseguir la justificación por la fe en Cristo, y no por las obras de la ley, pues por las obras de la ley nadie será justificado.

[[galatians-2-17]]
^17^ Ahora bien, si buscando nuestra justificación en Cristo, resulta que también nosotros somos pecadores, ¿estará Cristo al servicio del pecado? ¡De ningún modo!

[[galatians-2-18]]
^18^ Pues si vuelvo a edificar lo que una vez destruí, a mí mismo me declaro transgresor.

[[galatians-2-19]]
^19^ En efecto, yo por la ley he muerto a la ley, a fin de vivir para Dios: con Cristo estoy crucificado:

[[galatians-2-20]]
^20^ y no vivo yo, sino que es Cristo quien vive en mí; la vida que vivo al presente en la carne, la vivo en la fe del Hijo de Dios que me amó y se entregó a sí mismo por mí.

[[galatians-2-21]]
^21^ No tengo por inútil la gracia de Dios, pues si por la ley se obtuviera la justificación, entonces hubiese muerto Cristo en vano.
[[galatians-3]]
== Capítulo 3

[[galatians-3-1]]
^1^ ¡Oh insensatos gálatas! ¿Quién os fascinó a vosotros, a cuyos ojos fue presentado Jesucristo crucificado?

[[galatians-3-2]]
^2^ Quiero saber de vosotros una sola cosa: ¿recibisteis el Espíritu por las obras de la ley o por la fe en la predicación?

[[galatians-3-3]]
^3^ ¿Tan insensatos sois? Comenzando por espíritu, ¿termináis ahora en carne?

[[galatians-3-4]]
^4^ ¿Habéis pasado en vano por tales experiencias? ¡Pues bien en vano sería!

[[galatians-3-5]]
^5^ El que os otorga, pues, el Espíritu y obra milagros entre vosotros, ¿lo hace porque observáis la ley o porque tenéis fe en la predicación?

[[galatians-3-6]]
^6^ Así Abraham creyó en Dios y le fue reputado como justicia.

[[galatians-3-7]]
^7^ Tened, pues, entendido que los que viven de la fe, ésos son los hijos de Abraham.

[[galatians-3-8]]
^8^ La Escritura, previendo que Dios justificaría a los gentiles por la fe, anunció con antelación a Abraham esta buena nueva: En ti serán bendecidas todas las naciones.

[[galatians-3-9]]
^9^ Así pues, los que viven de la fe son bendecidos con Abraham el creyente.

[[galatians-3-10]]
^10^ Porque todos los que viven de las obras de la ley incurren en maldición. Pues dice la Escritura: Maldito todo el que no se mantenga en la práctica de todos los preceptos escritos en el libro de la Ley.

[[galatians-3-11]]
^11^ - Y que la ley no justifica a nadie ante Dios es cosa evidente, pues el justo vivirá por la fe;

[[galatians-3-12]]
^12^ pero la ley no procede de la fe, sino que quien practique sus preceptos, vivirá por ellos -

[[galatians-3-13]]
^13^ Cristo nos rescató de la maldición de la ley, haciéndose él mismo maldición por nosotros, pues dice la Escritura: Maldito todo el que está colgado de un madero,

[[galatians-3-14]]
^14^ a fin de que llegara a los gentiles, en Cristo Jesús, la bendición de Abraham, y por la fe recibiéramos el Espíritu de la Promesa.

[[galatians-3-15]]
^15^ Hermanos, voy a explicarme al modo humano: aun entre los hombres, nadie anula ni añade nada a un testamento hecho en regla.

[[galatians-3-16]]
^16^ Pues bien, las promesas fueron dirigidas a Abraham y a su descendencia. No dice: «y a los descendientes», como si fueran muchos, sino a uno solo, a tu descendencia, es decir, a Cristo.

[[galatians-3-17]]
^17^ Y digo yo: Un testamento ya hecho por Dios en debida forma, no puede ser anulado por la ley, que llega 430 años más tarde, de tal modo que la promesa quede anulada.

[[galatians-3-18]]
^18^ Pues si la herencia dependiera de la ley, ya no procedería de la promesa, y sin embargo, Dios otorgó a Abraham su favor en forma de promesa.

[[galatians-3-19]]
^19^ Entonces, ¿para qué la ley? Fue añadida en razón de las transgresiones hasta que llegase la descendencia, a quien iba destinada la promesa, ley que fue promulgada por los ángeles y con la intervención de un mediador.

[[galatians-3-20]]
^20^ Ahora bien, cuando hay uno solo no hay mediador, y Dios es uno solo.

[[galatians-3-21]]
^21^ Según eso, ¿la ley se opone a las promesas de Dios? ¡De ningún modo! Si de hecho se nos hubiera otorgado una ley capaz de vivificar, en ese caso la justicia vendría realmente de la ley.

[[galatians-3-22]]
^22^ Pero, de hecho, la Escritura encerró todo bajo el pecado, a fin de que la Promesa fuera otorgada a los creyentes mediante la fe en Jesucristo.

[[galatians-3-23]]
^23^ Y así, antes de que llegara la fe, estábamos encerrados bajo la vigilancia de la ley, en espera de la fe que debía manifestarse.

[[galatians-3-24]]
^24^ De manera que la ley ha sido nuestro pedagogo hasta Cristo, para ser justificados por la fe.

[[galatians-3-25]]
^25^ Mas, una vez llegada la fe, ya no estamos bajo el pedagogo.

[[galatians-3-26]]
^26^ Pues todos sois hijos de Dios por la fe en Cristo Jesús.

[[galatians-3-27]]
^27^ En efecto, todos los bautizados en Cristo os habéis revestido de Cristo:

[[galatians-3-28]]
^28^ ya no hay judío ni griego; ni esclavo ni libre; ni hombre ni mujer, ya que todos vosotros sois uno en Cristo Jesús.

[[galatians-3-29]]
^29^ Y si sois de Cristo, ya sois descendencia de Abraham, herederos según la Promesa.
[[galatians-4]]
== Capítulo 4

[[galatians-4-1]]
^1^ Pues yo digo: Mientras el heredero es menor de edad, en nada se diferencia de un esclavo, con ser dueño de todo;

[[galatians-4-2]]
^2^ sino que está bajo tutores y administradores hasta el tiempo fijado por el padre.

[[galatians-4-3]]
^3^ De igual manera, también nosotros, cuando éramos menores de edad, vivíamos como esclavos bajo los elementos del mundo.

[[galatians-4-4]]
^4^ Pero, al llegar la plenitud de los tiempos, envió Dios a su Hijo, nacido de mujer, nacido bajo la ley,

[[galatians-4-5]]
^5^ para rescatar a los que se hallaban bajo la ley, y para que recibiéramos la filiación adoptiva.

[[galatians-4-6]]
^6^ La prueba de que sois hijos es que Dios ha enviado a nuestros corazones el Espíritu de su Hijo que clama: ¡Abbá, Padre!

[[galatians-4-7]]
^7^ De modo que ya no eres esclavo, sino hijo; y si hijo, también heredero por voluntad de Dios.

[[galatians-4-8]]
^8^ Pero en otro tiempo, cuando no conocíais a Dios, servíais a los que en realidad no son dioses.

[[galatians-4-9]]
^9^ Mas, ahora que habéis conocido a Dios, o mejor, que él os ha conocido, ¿cómo retornáis a esos elementos sin fuerza ni valor, a los cuales queréis volver a servir de nuevo?

[[galatians-4-10]]
^10^ Andáis observando los días, los meses, las estaciones, los años.

[[galatians-4-11]]
^11^ Me hacéis temer no haya sido en vano todo mi afán por vosotros.

[[galatians-4-12]]
^12^ Os ruego que os hagáis como yo, pues yo me hice como vosotros. Ningún agravio me hicisteis.

[[galatians-4-13]]
^13^ Pero bien sabéis que una enfermedad me dio ocasión para evangelizaros por primera vez;

[[galatians-4-14]]
^14^ y, no obstante la prueba que suponía para vosotros mi cuerpo, no me mostrasteis desprecio ni repulsa, sino que me recibisteis como a un ángel de Dios: como a Cristo Jesús.

[[galatians-4-15]]
^15^ ¿Dónde están ahora los parabienes que os dabais? Pues yo mismo puedo atestiguaros que os hubierais arrancado los ojos, de haber sido posible, para dármelos.

[[galatians-4-16]]
^16^ ¿Es que me he vuelto enemigo vuestro diciéndoos la verdad?

[[galatians-4-17]]
^17^ El celo que ésos muestran por vosotros no es bueno; quieren alejaros de mí para que mostréis celo por ellos.

[[galatians-4-18]]
^18^ Bien está procurarse el celo de otros para el bien, siempre, y no sólo cuando yo estoy entre vosotros,

[[galatians-4-19]]
^19^ ¡hijos míos!, por quienes sufro de nuevo dolores de parto, hasta ver a Cristo formado en vosotros.

[[galatians-4-20]]
^20^ Quisiera hallarme ahora en medio de vosotros para poder acomodar el tono de mi voz, pues no sé cómo habérmelas con vosotros.

[[galatians-4-21]]
^21^ Decidme vosotros, los que queréis estar sometidos a la ley: ¿No oís la ley?.

[[galatians-4-22]]
^22^ Pues dice la Escritura que Abraham tuvo dos hijos: uno de la esclava y otro de la libre.

[[galatians-4-23]]
^23^ Pero el de la esclava nació según la naturaleza; el de la libre, en virtud de la Promesa.

[[galatians-4-24]]
^24^ Hay en ello una alegoría: estas mujeres representan dos alianzas; la primera, la del monte Sinaí, madre de los esclavos, es Agar,

[[galatians-4-25]]
^25^ (pues el monte Sinaí está en Arabia) y corresponde a la Jerusalén actual, que es esclava, y lo mismo sus hijos.

[[galatians-4-26]]
^26^ Pero la Jerusalén de arriba es libre; ésa es nuestra madre,

[[galatians-4-27]]
^27^ pues dice la Escritura: Regocíjate estéril, la que no das hijos; rompe en gritos de júbilo, la que no conoces los dolores de parto, que más son los hijos de la abandonada que los de la casada.

[[galatians-4-28]]
^28^ Y vosotros, hermanos, a la manera de Isaac, sois hijos de la Promesa.

[[galatians-4-29]]
^29^ Pero, así como entonces el nacido según la naturaleza perseguía al nacido según el espíritu, así también ahora.

[[galatians-4-30]]
^30^ Pero ¿qué dice la Escritura? Despide a la esclava y a su hijo, pues no ha de heredar el hijo de la esclava juntamente con el hijo de la libre.

[[galatians-4-31]]
^31^ Así que, hermanos, no somos hijos de la esclava, sino de la libre.
[[galatians-5]]
== Capítulo 5

[[galatians-5-1]]
^1^ Para ser libres nos libertó Cristo. Manteneos, pues, firmes y no os dejéis oprimir nuevamente bajo el yugo de la esclavitud.

[[galatians-5-2]]
^2^ Soy yo, Pablo, quien os lo dice: Si os dejáis circuncidar, Cristo no os aprovechará nada.

[[galatians-5-3]]
^3^ De nuevo declaro a todo hombre que se circuncida que queda obligado a practicar toda la ley.

[[galatians-5-4]]
^4^ Habéis roto con Cristo todos cuantos buscáis la justicia en la ley. Os habéis apartado de la gracia.

[[galatians-5-5]]
^5^ Pues a nosotros nos mueve el Espíritu a aguardar por la fe los bienes esperados por la justicia.

[[galatians-5-6]]
^6^ Porque en Cristo Jesús ni la circuncisión ni la incircuncisión tienen valor, sino solamente la fe que actúa por la caridad.

[[galatians-5-7]]
^7^ Comenzasteis bien vuestra carrera, ¿quién os puso obstáculo para no seguir a la verdad?

[[galatians-5-8]]
^8^ Semejante persuasión no proviene de Aquel que os llama.

[[galatians-5-9]]
^9^ Un poco de levadura fermenta toda la masa.

[[galatians-5-10]]
^10^ Por mi parte, confío en el Señor que vosotros no pensaréis de otra manera; pero el que os perturba llevará su castigo, quienquiera que sea.

[[galatians-5-11]]
^11^ En cuanto a mí, hermanos, si aún predico la circuncisión, ¿por qué soy todavía perseguido? ¡Pues se acabó ya el escándalo de la cruz!

[[galatians-5-12]]
^12^ ¡Ojalá que se mutilaran los que os perturban!

[[galatians-5-13]]
^13^ Porque, hermanos, habéis sido llamados a la libertad; sólo que no toméis de esa libertad pretexto para la carne; antes al contrario, servíos por amor los unos a los otros.

[[galatians-5-14]]
^14^ Pues toda la ley alcanza su plenitud en este solo precepto: Amarás a tu prójimo como a ti mismo.

[[galatians-5-15]]
^15^ Pero si os mordéis y os devoráis mutuamente, ¡mirad no vayáis mutuamente a destruiros!

[[galatians-5-16]]
^16^ Por mi parte os digo: Si vivís según el Espíritu, no daréis satisfacción a las apetencias de la carne.

[[galatians-5-17]]
^17^ Pues la carne tiene apetencias contrarias al espíritu, y el espíritu contrarias a la carne, como que son entre sí antagónicos, de forma que no hacéis lo que quisierais.

[[galatians-5-18]]
^18^ Pero, si sois conducidos por el Espíritu, no estáis bajo la ley.

[[galatians-5-19]]
^19^ Ahora bien, las obras de la carne son conocidas: fornicación, impureza, libertinaje,

[[galatians-5-20]]
^20^ idolatría, hechicería, odios, discordia, celos, iras, rencillas, divisiones, disensiones,

[[galatians-5-21]]
^21^ envidias, embriagueces, orgías y cosas semejantes, sobre las cuales os prevengo, como ya os previne, que quienes hacen tales cosas no heredarán el Reino de Dios.

[[galatians-5-22]]
^22^ En cambio el fruto del Espíritu es amor, alegría, paz, paciencia, afabilidad, bondad, fidelidad,

[[galatians-5-23]]
^23^ mansedumbre, dominio de sí; contra tales cosas no hay ley.

[[galatians-5-24]]
^24^ Pues los que son de Cristo Jesús, han crucificado la carne con sus pasiones y sus apetencias.

[[galatians-5-25]]
^25^ Si vivimos según el Espíritu, obremos también según el Espíritu.

[[galatians-5-26]]
^26^ No busquemos la gloria vana provocándonos los unos a los otros y envidiándonos mutuamente.
[[galatians-6]]
== Capítulo 6

[[galatians-6-1]]
^1^ Hermanos, aun cuando alguno incurra en alguna falta, vosotros, los espirituales, corregidle con espíritu de mansedumbre, y cuídate de ti mismo, pues también tú puedes ser tentado.

[[galatians-6-2]]
^2^ Ayudaos mutuamente a llevar vuestras cargas y cumplid así la ley de Cristo.

[[galatians-6-3]]
^3^ Porque si alguno se imagina ser algo, no siendo nada, se engaña a sí mismo.

[[galatians-6-4]]
^4^ Examine cada cual su propia conducta y entonces tendrá en sí solo, y no en otros, motivo para glorificarse,

[[galatians-6-5]]
^5^ pues cada uno tiene que llevar su propia carga.

[[galatians-6-6]]
^6^ Que el discípulo haga partícipe en toda suerte de bienes al que le instruye en la Palabra.

[[galatians-6-7]]
^7^ No os engañéis; de Dios nadie se burla. Pues lo que uno siembre, eso cosechará:

[[galatians-6-8]]
^8^ el que siembre en su carne, de la carne cosechará corrupción; el que siembre en el espíritu, del espíritu cosechará vida eterna.

[[galatians-6-9]]
^9^ No nos cansemos de obrar el bien; que a su tiempo nos vendrá la cosecha si no desfallecemos.

[[galatians-6-10]]
^10^ Así que, mientras tengamos oportunidad, hagamos el bien a todos, pero especialmente a nuestros hermanos en la fe.

[[galatians-6-11]]
^11^ Mirad con qué letras tan grandes os escribo de mi propio puño.

[[galatians-6-12]]
^12^ Los que quieren ser bien vistos en lo humano, ésos os fuerzan a circuncidaros, con el único fin de evitar la persecución por la cruz de Cristo.

[[galatians-6-13]]
^13^ Pues ni siquiera esos mismos que se circuncidan cumplen la ley; sólo desean veros circuncidados para gloriarse en vuestra carne.

[[galatians-6-14]]
^14^ En cuanto a mí ¡Dios me libre gloriarme si nos es en la cruz de nuestro Señor Jesucristo, por la cual el mundo es para mí un crucificado y yo un crucificado para el mundo!

[[galatians-6-15]]
^15^ Porque nada cuenta ni la circuncisión, ni la incircuncisión, sino la creación nueva.

[[galatians-6-16]]
^16^ Y para todos los que se sometan a esta regla, paz y misericordia, lo mismo que para el Israel de Dios.

[[galatians-6-17]]
^17^ En adelante nadie me moleste, pues llevo sobre mi cuerpo las señales de Jesús.

[[galatians-6-18]]
^18^ Hermanos, que la gracia de nuestro Señor Jesucristo sea con vuestro espíritu. Amén.
