[[ephesians]]
= Efesios

[[ephesians-1]]
== Capítulo 1

[[ephesians-1-1]]
^1^ Pablo, apóstol de Cristo Jesús por voluntad de Dios, a los santos y fieles en Cristo Jesús.

[[ephesians-1-2]]
^2^ Gracia a vosotros y paz de parte de Dios, nuestro Padre, y del Señor Jesucristo.

[[ephesians-1-3]]
^3^ Bendito sea el Dios y Padre de nuestro Señor Jesucristo, que nos ha bendecido con toda clase de bendiciones espirituales, en los cielos, en Cristo;

[[ephesians-1-4]]
^4^ por cuanto nos ha elegido en él antes de la fundación del mundo, para ser santos e inmaculados en su presencia, en el amor;

[[ephesians-1-5]]
^5^ eligiéndonos de antemano para ser sus hijos adoptivos por medio de Jesucristo, según el beneplácito de su voluntad,

[[ephesians-1-6]]
^6^ para alabanza de la gloria de su gracia con la que nos agració en el Amado.

[[ephesians-1-7]]
^7^ En él tenemos por medio de su sangre la redención, el perdón de los delitos, según la riqueza de su gracia

[[ephesians-1-8]]
^8^ que ha prodigado sobre nosotros en toda sabiduría e inteligencia,

[[ephesians-1-9]]
^9^ dándonos a conocer el Misterio de su voluntad según el benévolo designio que en él se propuso de antemano,

[[ephesians-1-10]]
^10^ para realizarlo en la plenitud de los tiempos: hacer que todo tenga a Cristo por Cabeza, lo que está en los cielos y lo que está en la tierra.

[[ephesians-1-11]]
^11^ A él, por quien entramos en herencia, elegidos de antemano según el previo designio del que realiza todo conforme a la decisión de su voluntad,

[[ephesians-1-12]]
^12^ para ser nosotros alabanza de su gloria, los que ya antes esperábamos en Cristo.

[[ephesians-1-13]]
^13^ En él también vosotros, tras haber oído la Palabra de la verdad, el Evangelio de vuestra salvación, y creído también en él, fuisteis sellados con el Espíritu Santo de la Promesa,

[[ephesians-1-14]]
^14^ que es prenda de nuestra herencia, para redención del Pueblo de su posesión, para alabanza de su gloria.

[[ephesians-1-15]]
^15^ Por eso, también yo, al tener noticia de vuestra fe en el Señor Jesús y de vuestra caridad para con todos los santos,

[[ephesians-1-16]]
^16^ no ceso de dar gracias por vosotros recordándoos en mis oraciones,

[[ephesians-1-17]]
^17^ para que el Dios de nuestro Señor Jesucristo, el Padre de la gloria, os conceda espíritu de sabiduría y de revelación para conocerle perfectamente;

[[ephesians-1-18]]
^18^ iluminando los ojos de vuestro corazón para que conozcáis cuál es la esperanza a que habéis sido llamados por él; cuál la riqueza de la gloria otorgada por él en herencia a los santos,

[[ephesians-1-19]]
^19^ y cuál la soberana grandeza de su poder para con nosotros, los creyentes, conforme a la eficacia de su fuerza poderosa,

[[ephesians-1-20]]
^20^ que desplegó en Cristo, resucitándole de entre los muertos y sentándole a su diestra en los cielos,

[[ephesians-1-21]]
^21^ por encima de todo Principado, Potestad, Virtud, Dominación y de todo cuanto tiene nombre no sólo en este mundo sino también en el venidero.

[[ephesians-1-22]]
^22^ Bajo sus pies sometió todas la cosas y le constituyó Cabeza suprema de la Iglesia,

[[ephesians-1-23]]
^23^ que es su Cuerpo, la Plenitud del que lo llena todo en todo.
[[ephesians-2]]
== Capítulo 2

[[ephesians-2-1]]
^1^ Y a vosotros que estabais muertos en vuestros delitos y pecados,

[[ephesians-2-2]]
^2^ en los cuales vivisteis en otro tiempo según el proceder de este mundo, según el Príncipe del imperio del aire, el Espíritu que actúa en los rebeldes...

[[ephesians-2-3]]
^3^ entre ellos vivíamos también todos nosotros en otro tiempo en medio de las concupiscencias de nuestra carne, siguiendo las apetencias de la carne y de los malos pensamientos, destinados por naturaleza, como los demás, a la Cólera...

[[ephesians-2-4]]
^4^ Pero Dios, rico en misericordia, por el grande amor con que nos amo,

[[ephesians-2-5]]
^5^ estando muertos a causa de nuestros delitos, nos vivificó juntamente con Cristo - por gracia habéis sido salvados -

[[ephesians-2-6]]
^6^ y con él nos resucitó y nos hizo sentar en los cielos en Cristo Jesús,

[[ephesians-2-7]]
^7^ a fin de mostrar en los siglos venideros la sobreabundante riqueza de su gracia, por su bondad para con nosotros en Cristo Jesús.

[[ephesians-2-8]]
^8^ Pues habéis sido salvados por la gracia mediante la fe; y esto no viene de vosotros, sino que es un don de Dios;

[[ephesians-2-9]]
^9^ tampoco viene de las obras, para que nadie se gloríe.

[[ephesians-2-10]]
^10^ En efecto, hechura suya somos: creados en Cristo Jesús, en orden a las buenas obras que de antemano dispuso Dios que practicáramos.

[[ephesians-2-11]]
^11^ Así que, recordad cómo en otro tiempo vosotros, los gentiles según la carne, llamados incircuncisos por la que se llama circuncisión - por una operación practicada en la carne -,

[[ephesians-2-12]]
^12^ estabais a la sazón lejos de Cristo, excluidos de la ciudadanía de Israel y extraños a las alianzas de la Promesa, sin esperanza y sin Dios en el mundo.

[[ephesians-2-13]]
^13^ Mas ahora, en Cristo Jesús, vosotros, los que en otro tiempo estabais lejos, habéis llegado a estar cerca por la sangre de Cristo.

[[ephesians-2-14]]
^14^ Porque él es nuestra paz: el que de los dos pueblos hizo uno, derribando el muro que los separaba, la enemistad,

[[ephesians-2-15]]
^15^ anulando en su carne la Ley de los mandamientos con sus preceptos, para crear en sí mismo, de los dos, un solo Hombre Nuevo, haciendo la paz,

[[ephesians-2-16]]
^16^ y reconciliar con Dios a ambos en un solo Cuerpo, por medio de la cruz, dando en sí mismo muerte a la Enemistad.

[[ephesians-2-17]]
^17^ Vino a anunciar la paz: paz a vosotros que estabais lejos, y paz a los que estaban cerca.

[[ephesians-2-18]]
^18^ Pues por él, unos y otros tenemos libre acceso al Padre en un mismo Espíritu.

[[ephesians-2-19]]
^19^ Así pues, ya no sois extraños ni forasteros, sino conciudadanos de los santos y familiares de Dios,

[[ephesians-2-20]]
^20^ edificados sobre el cimiento de los apóstoles y profetas, siendo la piedra angular Cristo mismo,

[[ephesians-2-21]]
^21^ en quien toda edificación bien trabada se eleva hasta formar un templo santo en el Señor,

[[ephesians-2-22]]
^22^ en quien también vosotros estáis siendo juntamente edificados, hasta ser morada de Dios en el Espíritu.
[[ephesians-3]]
== Capítulo 3

[[ephesians-3-1]]
^1^ Por lo cual yo, Pablo, el prisionero de Cristo por vosotros los gentiles...

[[ephesians-3-2]]
^2^ si es que conocéis la misión de la gracia que Dios me concedió en orden a vosotros:

[[ephesians-3-3]]
^3^ cómo me fue comunicado por una revelación el conocimiento del Misterio, tal como brevemente acabo de exponeros.

[[ephesians-3-4]]
^4^ Según esto, leyéndolo podéis entender mi conocimiento del Misterio de Cristo;

[[ephesians-3-5]]
^5^ Misterio que en generaciones pasadas no fue dado a conocer a los hombres, como ha sido ahora revelado a sus santos apóstoles y profetas por el Espíritu:

[[ephesians-3-6]]
^6^ que los gentiles sois coherederos, miembros del mismo Cuerpo y partícipes de la misma Promesa en Cristo Jesús por medio del Evangelio,

[[ephesians-3-7]]
^7^ del cual he llegado a ser ministro, conforme al don de la gracia de Dios a mí concedida por la fuerza de su poder.

[[ephesians-3-8]]
^8^ A mí, el menor de todos los santos, me fue concedida esta gracia: la de anunciar a los gentiles la inescrutable riqueza de Cristo,

[[ephesians-3-9]]
^9^ y esclarecer cómo se ha dispensado el Misterio escondido desde siglos en Dios, Creador de todas las cosas,

[[ephesians-3-10]]
^10^ para que la multiforme sabiduría de Dios sea ahora manifestada a los Principados y a las Potestades en los cielos, mediante la Iglesia,

[[ephesians-3-11]]
^11^ conforme al previo designio eterno que realizó en Cristo Jesús, Señor nuestro,

[[ephesians-3-12]]
^12^ quien, mediante la fe en él, nos da valor para llegarnos confiadamente a Dios.

[[ephesians-3-13]]
^13^ Por lo cual os ruego no os desaniméis a causa de las tribulaciones que por vosotros padezco, pues ellas son vuestra gloria.

[[ephesians-3-14]]
^14^ Por eso doblo mis rodillas ante el Padre,

[[ephesians-3-15]]
^15^ de quien toma nombre toda familia en el cielo y en la tierra,

[[ephesians-3-16]]
^16^ para que os conceda, según la riqueza de su gloria, que seáis fortalecidos por la acción de su Espíritu en el hombre interior,

[[ephesians-3-17]]
^17^ que Cristo habite por la fe en vuestros corazones, para que, arraigados y cimentados en el amor,

[[ephesians-3-18]]
^18^ podáis comprender con todos los santos cuál es la anchura y la longitud, la altura y la profundidad,

[[ephesians-3-19]]
^19^ y conocer el amor de Cristo, que excede a todo conocimiento, para que os vayáis llenando hasta la total Plenitud de Dios.

[[ephesians-3-20]]
^20^ A Aquel que tiene poder para realizar todas las cosas incomparablemente mejor de lo que podemos pedir o pensar, conforme al poder que actúa en nosotros,

[[ephesians-3-21]]
^21^ a él la gloria en la Iglesia y en Cristo Jesús por todas las generaciones y todos los tiempos. Amén.
[[ephesians-4]]
== Capítulo 4

[[ephesians-4-1]]
^1^ Os exhorto, pues, yo, preso por el Señor, a que viváis de una manera digna de la vocación con que habéis sido llamados,

[[ephesians-4-2]]
^2^ con toda humildad, mansedumbre y paciencia, soportándoos unos a otros por amor,

[[ephesians-4-3]]
^3^ poniendo empeño en conservar la unidad del Espíritu con el vínculo de la paz.

[[ephesians-4-4]]
^4^ Un solo Cuerpo y un solo Espíritu, como una es la esperanza a que habéis sido llamados.

[[ephesians-4-5]]
^5^ Un solo Señor, una sola fe, un solo bautismo,

[[ephesians-4-6]]
^6^ un solo Dios y Padre de todos, que está sobre todos, por todos y en todos.

[[ephesians-4-7]]
^7^ A cada uno de nosotros le ha sido concedido el favor divino a la medida de los dones de Cristo.

[[ephesians-4-8]]
^8^ Por eso dice: Subiendo a la altura, llevó cautivos y dio dones a los hombres.

[[ephesians-4-9]]
^9^ ¿Qué quiere decir «subió» sino que también bajó a las regiones inferiores de la tierra?

[[ephesians-4-10]]
^10^ Este que bajó es el mismo que subió por encima de todos los cielos, para llenarlo todo.

[[ephesians-4-11]]
^11^ El mismo «dio» a unos el ser apóstoles; a otros, profetas; a otros, evangelizadores; a otros, pastores y maestros,

[[ephesians-4-12]]
^12^ para el recto ordenamiento de los santos en orden a las funciones del ministerio, para edificación del Cuerpo de Cristo,

[[ephesians-4-13]]
^13^ hasta que llegemos todos a la unidad de la fe y del conocimiento pleno del Hijo de Dios, al estado de hombre perfecto, a la madurez de la plenitud de Cristo.

[[ephesians-4-14]]
^14^ Para que no seamos ya niños, llevados a la deriva y zarandeados por cualquier viento de doctrina, a merced de la malicia humana y de la astucia que conduce engañosamente al error,

[[ephesians-4-15]]
^15^ antes bien, siendo sinceros en el amor, crezcamos en todo hasta Aquel que es la Cabeza, Cristo,

[[ephesians-4-16]]
^16^ de quien todo el Cuerpo recibe trabazón y cohesión por medio de toda clase de junturas que llevan la nutrición según la actividad propia de cada una de las partes, realizando así el crecimiento del cuerpo para su edificación en el amor.

[[ephesians-4-17]]
^17^ Os digo, pues, esto y os conjuro en el Señor, que no viváis ya como viven los gentiles, según la vaciedad de su mente,

[[ephesians-4-18]]
^18^ sumergido su pensamiento en las tinieblas y excluidos de la vida de Dios por la ignorancia que hay en ellos, por la dureza de su cabeza

[[ephesians-4-19]]
^19^ los cuales, habiendo perdido el sentido moral, se entregaron al libertinaje, hasta practicar con desenfreno toda suerte de impurezas.

[[ephesians-4-20]]
^20^ Pero no es éste el Cristo que vosotros habéis aprendido,

[[ephesians-4-21]]
^21^ si es que habéis oído hablar de él y en él habéis sido enseñados conforme a la verdad de Jesús

[[ephesians-4-22]]
^22^ a despojaros, en cuanto a vuestra vida anterior, del hombre viejo que se corrompe siguiendo la seducción de las concupiscencias,

[[ephesians-4-23]]
^23^ a renovar el espíritu de vuestra mente,

[[ephesians-4-24]]
^24^ y a revestiros del Hombre Nuevo, creado según Dios, en la justicia y santidad de la verdad.

[[ephesians-4-25]]
^25^ Por tanto, desechando la mentira, hablad con verdad cada cual con su prójimo, pues somos miembros los unos de los otros.

[[ephesians-4-26]]
^26^ Si os airáis, no pequéis; no se ponga el sol mientras estéis airados,

[[ephesians-4-27]]
^27^ ni deis ocasión al Diablo.

[[ephesians-4-28]]
^28^ El que robaba, que ya no robe, sino que trabaje con sus manos, haciendo algo útil para que pueda hacer partícipe al que se halle en necesidad.

[[ephesians-4-29]]
^29^ No salga de vuestra boca palabra dañosa, sino la que sea conveniente para edificar según la necesidad y hacer el bien a los que os escuchen.

[[ephesians-4-30]]
^30^ No entristezcáis al Espíritu Santo de Dios, con el que fuisteis sellados para el día de la redención.

[[ephesians-4-31]]
^31^ Toda acritud, ira, cólera, gritos, maledicencia y cualquier clase de maldad, desaparezca de entre vosotros.

[[ephesians-4-32]]
^32^ Sed más bien buenos entre vosotros, entrañables, perdonándoos mutuamente como os perdonó Dios en Cristo.
[[ephesians-5]]
== Capítulo 5

[[ephesians-5-1]]
^1^ Sed, pues, imitadores de Dios, como hijos queridos,

[[ephesians-5-2]]
^2^ y vivid en el amor como Cristo os amó y se entregó por nosotros como oblación y víctima de suave aroma.

[[ephesians-5-3]]
^3^ La fornicación, y toda impureza o codicia, ni siquiera se mencione entre vosotros, como conviene a los santos.

[[ephesians-5-4]]
^4^ Lo mismo de la grosería, las necedades o las chocarrerías, cosas que no están bien; sino más bien, acciones de gracias.

[[ephesians-5-5]]
^5^ Porque tened entendido que ningún fornicario o impuro o codicioso - que es ser idólatra - participará en la herencia del Reino de Cristo y de Dios.

[[ephesians-5-6]]
^6^ Que nadie os engañe con vanas razones, pues por eso viene le cólera de Dios sobre los rebeldes.

[[ephesians-5-7]]
^7^ No tengáis parte con ellos.

[[ephesians-5-8]]
^8^ Porque en otro tiempo fuisteis tinieblas; mas ahora sois luz en el Señor. Vivid como hijos de la luz;

[[ephesians-5-9]]
^9^ pues el fruto de la luz consiste en toda bondad, justicia y verdad.

[[ephesians-5-10]]
^10^ Examinad qué es lo que agrada al Señor,

[[ephesians-5-11]]
^11^ y no participéis en las obras infructuosas de las tinieblas, antes bien, denunciadlas.

[[ephesians-5-12]]
^12^ Cierto que ya sólo el mencionar las cosas que hacen ocultamente da vergüenza;

[[ephesians-5-13]]
^13^ pero, al ser denunciadas, se manifiestan a la luz.

[[ephesians-5-14]]
^14^ Pues todo lo que queda manifiesto es luz. Por eso se dice: Despierta tú que duermes, y levántate de entre los muertos, y te iluminará Cristo.

[[ephesians-5-15]]
^15^ Así pues, mirad atentamente cómo vivís; que no sea como imprudentes, sino como prudentes;

[[ephesians-5-16]]
^16^ aprovechando bien el tiempo presente, porque los días son malos.

[[ephesians-5-17]]
^17^ Por tanto, no seáis insensatos, sino comprended cuál es la voluntad de Señor.

[[ephesians-5-18]]
^18^ No os embriaguéis con vino, que es causa de libertinaje; llenaos más bien del Espíritu.

[[ephesians-5-19]]
^19^ Recitad entre vosotros salmos, himnos y cánticos inspirados; cantad y salmodiad en vuestro corazón al Señor,

[[ephesians-5-20]]
^20^ dando gracias continuamente y por todo a Dios Padre, en nombre de nuestro Señor Jesucristo.

[[ephesians-5-21]]
^21^ Sed sumisos los unos a los otros en el temor de Cristo.

[[ephesians-5-22]]
^22^ Las mujeres a sus maridos, como al Señor,

[[ephesians-5-23]]
^23^ porque el marido es cabeza de la mujer, como Cristo es Cabeza de la Iglesia, el salvador del Cuerpo.

[[ephesians-5-24]]
^24^ Así como la Iglesia está sumisa a Cristo, así también las mujeres deben estarlo a sus maridos en todo.

[[ephesians-5-25]]
^25^ Maridos, amad a vuestras mujeres como Cristo amó a la Iglesia y se entregó a sí mismo por ella,

[[ephesians-5-26]]
^26^ para santificarla, purificándola mediante el baño del agua, en virtud de la palabra,

[[ephesians-5-27]]
^27^ y presentársela resplandeciente a sí mismo; sin que tenga mancha ni arruga ni cosa parecida, sino que sea santa e inmaculada.

[[ephesians-5-28]]
^28^ Así deben amar los maridos a sus mujeres como a sus propios cuerpos. El que ama a su mujer se ama a sí mismo.

[[ephesians-5-29]]
^29^ Porque nadie aborreció jamás su propia carne; antes bien, la alimenta y la cuida con cariño, lo mismo que Cristo a la Iglesia,

[[ephesians-5-30]]
^30^ pues somos miembros de su Cuerpo.

[[ephesians-5-31]]
^31^ Por eso dejará el hombre a su padre y a su madre y se unirá a su mujer, y los dos se harán una sola carne.

[[ephesians-5-32]]
^32^ Gran misterio es éste, lo digo respecto a Cristo y la Iglesia.

[[ephesians-5-33]]
^33^ En todo caso, en cuanto a vosotros, que cada uno ame a su mujer como a sí mismo; y la mujer, que respete al marido.
[[ephesians-6]]
== Capítulo 6

[[ephesians-6-1]]
^1^ Hijos, obedeced a vuestros padres en el Señor; porque esto es justo.

[[ephesians-6-2]]
^2^ Honra a tu padre y a tu madre, tal es el primer mandamiento que lleva consigo una promesa:

[[ephesians-6-3]]
^3^ Para que seas feliz y se prolongue tu vida sobre la tierra.

[[ephesians-6-4]]
^4^ Padres, no exasperéis a vuestros hijos, sino formadlos más bien mediante la instrucción y la corrección según el Señor.

[[ephesians-6-5]]
^5^ Esclavos, obedeced a vuestros amos de este mundo con respeto y temor, con sencillez de corazón, como a Cristo,

[[ephesians-6-6]]
^6^ no por ser vistos, como quien busca agradar a los hombres, sino como esclavos de Cristo que cumplen de corazón la voluntad de Dios;

[[ephesians-6-7]]
^7^ de buena gana, como quien sirve al Señor y no a los hombres;

[[ephesians-6-8]]
^8^ conscientes de que cada cual será recompemsado por el Señor según el bien que hiciere: sea esclavo, sea libre.

[[ephesians-6-9]]
^9^ Amos, obrad de la misma manera con ellos, dejando las amenazas; teniendo presente que está en los cielos el Amo vuestro y de ellos, y que en él no hay acepción de personas.

[[ephesians-6-10]]
^10^ Por lo demás, fortaleceos en el Señor y en la fuerza de su poder.

[[ephesians-6-11]]
^11^ Revestíos de las armas de Dios para poder resistir a las acechanzas del Diablo.

[[ephesians-6-12]]
^12^ Porque nuestra lucha no es contra la carne y la sangre, sino contra los Principados, contra las Potestades, contra los Dominadores de este mundo tenebroso, contra los Espíritus del Mal que están en las alturas.

[[ephesians-6-13]]
^13^ Por eso, tomad las armas de Dios, para que podáis resistir en el día malo, y después de haber vencido todo, manteneros firmes.

[[ephesians-6-14]]
^14^ ¡En pie!, pues; ceñida vuestra cintura con la Verdad y revestidos de la Justicia como coraza,

[[ephesians-6-15]]
^15^ calzados los pies con el Celo por el Evangelio de la paz,

[[ephesians-6-16]]
^16^ embrazando siempre el escudo de la Fe, para que podáis apagar con él todos los encendidos dardos del Maligno.

[[ephesians-6-17]]
^17^ Tomad, también, el yelmo de la salvación y la la espada del Espíritu, que es la Palabra de Dios;

[[ephesians-6-18]]
^18^ siempre en oración y súplica, orando en toda ocasión en el Espíritu, velando juntos con perseverancia e intercediendo por todos los santos,

[[ephesians-6-19]]
^19^ y también por mí, para que me sea dada la Palabra al abrir mi boca y pueda dar a conocer con valentía el Misterio del Evangelio,

[[ephesians-6-20]]
^20^ del cual soy embajador entre cadenas, y pueda hablar de él valientemente como conviene.

[[ephesians-6-21]]
^21^ Para que también vosotros sepáis cómo me va y qué hago, os informará de todo Tíquico, el hermano querido y fiel ministro en el Señor,

[[ephesians-6-22]]
^22^ a quien envío donde vosotros expresamente para que sepáis de nosotros y consuele vuestros corazones.

[[ephesians-6-23]]
^23^ Paz a los hermanos, y caridad con fe de parte de Dios Padre y del Señor Jesucristo.

[[ephesians-6-24]]
^24^ La gracia sea con todos los que aman a nuestro Señor Jesucristo en la vida incorruptible.
