[[colossians]]
= Colosenses

[[colossians-1]]
== Capítulo 1

[[colossians-1-1]]
^1^ Pablo, apóstol de Cristo Jesús por voluntad de Dios, y Timoteo el hermano,

[[colossians-1-2]]
^2^ a los santos de Colosas, hermanos fieles en Cristo. Gracia a vosotros y paz de parte de Dios, nuestro Padre.

[[colossians-1-3]]
^3^ Damos gracias sin cesar a Dios, Padre de nuestro Señor Jesucristo, por vosotros en nuestras oraciones,

[[colossians-1-4]]
^4^ al tener noticia de vuestra fe en Cristo Jesús y de la caridad que tenéis con todos los santos,

[[colossians-1-5]]
^5^ a causa de la esperanza que os está reservada en los cielos y acerca de la cual fuisteis ya instruidos por la Palabra de la verdad, el Evangelio,

[[colossians-1-6]]
^6^ que llegó hasta vosotros, y fructifica y crece entre vosotros lo mismo que en todo el mundo, desde el día en que oísteis y conocisteis la gracia de Dios en la verdad:

[[colossians-1-7]]
^7^ tal como os la enseñó Epafras, nuestro querido consiervo y fiel ministro de Cristo, en lugar nuestro,

[[colossians-1-8]]
^8^ el cual nos informó también de vuestro amor en el Espíritu.

[[colossians-1-9]]
^9^ Por eso, tampoco nosotros dejamos de rogar por vosotros desde el día que lo oímos, y de pedir que lleguéis al pleno conocimiento de su voluntad con toda sabiduría e inteligencia espiritual,

[[colossians-1-10]]
^10^ para que viváis de una manera digna del Señor, agradándole en todo, fructificando en toda obra buena y creciendo en el conocimiento de Dios;

[[colossians-1-11]]
^11^ confortados con toda fortaleza por el poder de su gloria, para toda constancia en el sufrimiento y paciencia; dando con alegría

[[colossians-1-12]]
^12^ gracias al Padre que os ha hecho aptos para participar en la herencia de los santos en la luz.

[[colossians-1-13]]
^13^ El nos libró del poder de las tinieblas y nos trasladó al Reino del Hijo de su amor,

[[colossians-1-14]]
^14^ en quien tenemos la redención: el perdón de los pecados.

[[colossians-1-15]]
^15^ El es Imagen de Dios invisible, Primogénito de toda la creación,

[[colossians-1-16]]
^16^ porque en él fueron creadas todas las cosas, en los cielos y en la tierra, las visibles y las invisibles, los Tronos, las Dominaciones, los Principados, las Potestades: todo fue creado por él y para él,

[[colossians-1-17]]
^17^ él existe con anterioridad a todo, y todo tiene en él su consistencia.

[[colossians-1-18]]
^18^ El es también la Cabeza del Cuerpo, de la Iglesia: El es el Principio, el Primogénito de entre los muertos, para que sea él el primero en todo,

[[colossians-1-19]]
^19^ pues Dios tuvo a bien hacer residir en él toda la Plenitud,

[[colossians-1-20]]
^20^ y reconciliar por él y para él todas las cosas, pacificando, mediante la sangre de su cruz, lo que hay en la tierra y en los cielos.

[[colossians-1-21]]
^21^ Y a vosotros, que en otro tiempo fuisteis extraños y enemigos, por vuestros pensamientos y malas obras,

[[colossians-1-22]]
^22^ os ha reconciliado ahora, por medio de la muerte en su cuerpo de carne, para presentaros santos, inmaculados e irreprensibles delante de El;

[[colossians-1-23]]
^23^ con tal que permanezcáis sólidamente cimentados en la fe, firmes e inconmovibles en la esperanza del Evangelio que oísteis, que ha sido proclamado a toda criatura bajo el cielo y del que yo, Pablo, he llegado a ser ministro.

[[colossians-1-24]]
^24^ Ahora me alegro por los padecimientos que soporto por vosotros, y completo en mi carne lo que falta a las tribulaciones de Cristo, en favor de su Cuerpo, que es la Iglesia,

[[colossians-1-25]]
^25^ de la cual he llegado a ser ministro, conforme a la misión que Dios me concedió en orden a vosotros para dar cumplimiento a la Palabra de Dios,

[[colossians-1-26]]
^26^ al Misterio escondido desde siglos y generaciones, y manifestado ahora a sus santos,

[[colossians-1-27]]
^27^ a quienes Dios quiso dar a conocer cuál es la riqueza de la gloria de este misterio entre los gentiles, que es Cristo entre vosotros, la esperanza de la gloria,

[[colossians-1-28]]
^28^ al cual nosotros anunciamos, amonestando e instruyendo a todos los hombres con toda sabiduría, a fin de presentarlos a todos perfectos en Cristo.

[[colossians-1-29]]
^29^ Por esto precisamente me afano, luchando con la fuerza de Cristo que actúa poderosamente en mí.
[[colossians-2]]
== Capítulo 2

[[colossians-2-1]]
^1^ Quiero que sepáis qué dura lucha estoy sosteniendo por vosotros y por los de Laodicea, y por todos los que no me han visto personalmente,

[[colossians-2-2]]
^2^ para que sus corazones reciban ánimo y, unidos íntimamente en el amor, alcancen en toda su riqueza la plena inteligencia y perfecto conocimiento del Misterio de Dios,

[[colossians-2-3]]
^3^ en el cual están ocultos todos los tesoros de la sabiduría y de la ciencia.

[[colossians-2-4]]
^4^ Os digo esto para que nadie os seduzca con discursos capciosos.

[[colossians-2-5]]
^5^ Pues, si bien estoy corporalmente ausente, en espíritu me hallo con vosotros, alegrándome de ver vuestra armonía y la firmeza de vuestra fe en Cristo.

[[colossians-2-6]]
^6^ Vivid, pues, según Cristo Jesús, el Señor, tal como le habéis recibido;

[[colossians-2-7]]
^7^ enraizados y edificados en él; apoyados en la fe, tal como se os enseñó, rebosando en acción de gracias.

[[colossians-2-8]]
^8^ Mirad que nadie os esclavice mediante la vana falacia de una filosofía, fundada en tradiciones humanas, según los elementos del mundo y no según Cristo.

[[colossians-2-9]]
^9^ Porque en él reside toda la Plenitud de la Divinidad corporalmente,

[[colossians-2-10]]
^10^ y vosotros alcanzáis la plenitud en él, que es la Cabeza de todo Principado y de toda Potestad;

[[colossians-2-11]]
^11^ en él también fuisteis circuncidados con la circuncisión no quirúrgica, sino mediante el despojo de vuestro cuerpo mortal, por la circuncisión en Cristo.

[[colossians-2-12]]
^12^ Sepultados con él en el bautismo, con él también habéis resucitado por la fe en la acción de Dios, que resucitó de entre los muertos.

[[colossians-2-13]]
^13^ Y a vosotros, que estabais muertos en vuestros delitos y en vuestra carne incircuncisa, os vivificó juntamente con él y nos perdonó todos nuestros delitos.

[[colossians-2-14]]
^14^ Canceló la nota de cargo que había contra nosotros, la de las prescripciones con sus cláusulas desfavorables, y la suprimió clavándola en la cruz.

[[colossians-2-15]]
^15^ Y, una vez despojados los Principados y las Postestades, los exhibió públicamente, incorporándolos a su cortejo triunfal.

[[colossians-2-16]]
^16^ Por tanto, que nadie os critique por cuestiones de comida o bebida, o a propósito de fiestas, de novilunios o sábados.

[[colossians-2-17]]
^17^ Todo esto es sombra de lo venidero; pero la realidad es el cuerpo de Cristo.

[[colossians-2-18]]
^18^ Que nadie os prive del premio a causa del gusto por ruines prácticas, del culto de los ángeles, obesionado por lo que vio, vanamente hinchado por su mente carnal,

[[colossians-2-19]]
^19^ en lugar de mantenerse unido a la Cabeza, de la cual todo el Cuerpo, por medio de junturas y ligamentos, recibe nutrición y cohesión, para realizar su crecimiento en Dios.

[[colossians-2-20]]
^20^ Una vez que habéis muerto con Cristo a los elementos del mundo ¿por qué sujertaros, como si aún vivierais en el mundo, a preceptos como

[[colossians-2-21]]
^21^ «no tomes», «no gustes», «no toques»,

[[colossians-2-22]]
^22^ cosas todas destinadas a perecer con el uso y debidas a preceptos y doctrinas puramente humanos?

[[colossians-2-23]]
^23^ Tales cosas tienen una apariencia de sabiduría por su piedad afectada, sus mortificaciones y su rigor con el cuerpo; pero sin valor alguno contra la insolencia de la carne.
[[colossians-3]]
== Capítulo 3

[[colossians-3-1]]
^1^ Así pues, si habéis resucitado con Cristo, buscad las cosas de arriba, donde está Cristo sentado a la diestra de Dios.

[[colossians-3-2]]
^2^ Aspirad a las cosas de arriba, no a las de la tierra.

[[colossians-3-3]]
^3^ Porque habéis muerto, y vuestra vida está oculta con Cristo en Dios.

[[colossians-3-4]]
^4^ Cuando aparezca Cristo, vida vuestra, entonces también vosotros apareceréis gloriosos con él.

[[colossians-3-5]]
^5^ Por tanto, mortificad vuestros miembros terrenos: fornicación, impureza, pasiones, malos deseos y la codicia, que es una idolatría,

[[colossians-3-6]]
^6^ todo lo cual atrae la cólera de Dios sobre los rebeldes,

[[colossians-3-7]]
^7^ y que también vosotros practicasteis en otro tiempo, cuando vivíais entre ellas.

[[colossians-3-8]]
^8^ Mas ahora, desechad también vosotros todo esto: cólera, ira, maldad, maledicencia y palabras groseras, lejos de vuestra boca.

[[colossians-3-9]]
^9^ No os mintáis unos a otros. Despojaos del hombre viejo con sus obras,

[[colossians-3-10]]
^10^ y revestíos del hombre nuevo, que se va renovando hasta alcanzar un conocimiento pefecto, según la imagen de su Creador,

[[colossians-3-11]]
^11^ donde no hay griego y judío; circuncisión e incircuncisión; bárbaro, escita, esclavo, libre, sino que Cristo es todo y en todos.

[[colossians-3-12]]
^12^ Revestíos, pues, como elegidos de Dios, santos y amados, de entrañas de misericordia, de bondad, humildad, mansedumbre, paciencia,

[[colossians-3-13]]
^13^ soportándoos unos a otros y perdonándoos mutuamente, si alguno tiene queja contra otro. Como el Señor os perdonó, perdonaos también vosotros.

[[colossians-3-14]]
^14^ Y por encima de todo esto, revestíos del amor, que es el vínculo de la perfección.

[[colossians-3-15]]
^15^ Y que la paz de Cristo presida vuestros corazones, pues a ella habéis sido llamados formando un solo Cuerpo. Y sed agradecidos.

[[colossians-3-17]]
^17^ y todo cuanto hagáis, de palabra y de boca, hacedlo todo en el nombre del Señor Jesús, dando gracias por su medio a Dios Padre.

[[colossians-3-18]]
^18^ Mujeres, sed sumisas a vuestros maridos, como conviene en el Señor.

[[colossians-3-19]]
^19^ Maridos, amad a vuestras mujeres, y no seáis ásperos con ellas.

[[colossians-3-20]]
^20^ Hijos, obedeced en todo a vuestros padres, porque esto es grato a Dios en el Señor.

[[colossians-3-21]]
^21^ Padres, no exasperéis a vuestros hijos, no sea que se vuelvan apocados.

[[colossians-3-22]]
^22^ Esclavos, obedeced en todo a vuestros amos de este mundo, no porque os vean, como quien busca agradar a los hombres; sino con sencillez de corazón, en el temor del Señor.

[[colossians-3-23]]
^23^ Todo cuanto hagáis, hacedlo de corazón, como para el Señor y no para los hombres,

[[colossians-3-24]]
^24^ conscientes de que el Señor os dará la herencia en recompensa. El Amo a quien servís es Cristo.

[[colossians-3-25]]
^25^ El que obre la injusticia, recibirá conforme a esa injusticia; que no hay acepción de personas.
[[colossians-4]]
== Capítulo 4

[[colossians-4-1]]
^1^ Amos, dad a vuestros esclavos lo que es justo y equitativo, teniendo presente que también vosotros tenéis un Amo en el cielo.

[[colossians-4-2]]
^2^ Sed perseverantes en la oración, velando en ella con acción de gracias;

[[colossians-4-3]]
^3^ orad al mismo tiempo también por nosotros para que Dios nos abra una puerta a la Palabra, y podamos anunciar el Misterio de Cristo, por cuya causa estoy yo encarcelado,

[[colossians-4-4]]
^4^ para darlo a conocer anunciándolo como debo hacerlo.

[[colossians-4-5]]
^5^ Portaos prudentemente con los de fuera, aprovechando bien el tiempo presente.

[[colossians-4-6]]
^6^ Que vuestra conversación sea siempre amena, sazonada con sal, sabiendo responder a cada cual como conviene.

[[colossians-4-7]]
^7^ En cuanto a mí, de todo os informará Tíquico, el hermano querido, fiel ministro y consiervo en el Señor,

[[colossians-4-8]]
^8^ a quien os envío expresamente para que sepáis de nosotros y consuele vuestros corazones.

[[colossians-4-9]]
^9^ Y con él a Onésimo, el hermano fiel y querido compatriota vuestro. Ellos os informarán de todo cuanto aquí sucede.

[[colossians-4-10]]
^10^ Os saludan Aristarco, mi compañero de cautiverio, y Marcos, primo de Bernabé, acerca del cual recibisteis ya instrucciones. Si va a vosotros, dadle buena acogida.

[[colossians-4-11]]
^11^ Os saluda también Jesús, llamado Justo; son los únicos de la circuncisión que colaboran conmigo por el Reino de Dios y que han sido para mí un consuelo.

[[colossians-4-12]]
^12^ Os saluda Epafras, vuestro compatriota, siervo de Cristo Jesús, que se esfuerza siempre a favor vuestro en sus oraciones, para que os mantengáis perfectos cumplidores de toda voluntad divina.

[[colossians-4-13]]
^13^ Yo soy testigo de lo mucho que se afana por vosotros, por los de Laodicea y por los de Hierápolis.

[[colossians-4-14]]
^14^ Os saluda Lucas, el médico querido, y Demas.

[[colossians-4-15]]
^15^ Saludad a los hermanos de Laodicea, a Ninfas y la Iglesia de su casa.

[[colossians-4-16]]
^16^ Una vez que hayáis leído esta carta entre vosotros, procurad que sea también leída en la Iglesia de Laodicea. Y por vuestra parte leed vosotros la que os venga de Laodicea.

[[colossians-4-17]]
^17^ Decid a Arquipo: «Considera el ministerio que recibiste en el Señor, para que lo cumplas».

[[colossians-4-18]]
^18^ El saludo va de mi mano, Pablo. Acordaos de mis cadenas. La gracia sea con vosotros.
