[[first-thessalonians]]
= Primera carta a los Tesalonicenses

[[first-thessalonians-1]]
== Capítulo 1

[[first-thessalonians-1-1]]
^1^ Pablo, Silvano y Timoteo a la Iglesia de los Tesalonicenses, en Dios Padre y en el Señor Jesucristo. A vosotros gracia y paz.

[[first-thessalonians-1-2]]
^2^ En todo momento damos gracia a Dios por todos vosotros, recordándoos sin cesar en nuestras oraciones.

[[first-thessalonians-1-3]]
^3^ Tenemos presente ante nuestro Dios y Padre la obra de vuestra fe, los trabajos de vuestra caridad, y la tenacidad de vuestra esperanza en Jesucristo nuestro Señor.

[[first-thessalonians-1-4]]
^4^ Conocemos, hermanos queridos de Dios, vuestra elección;

[[first-thessalonians-1-5]]
^5^ ya que os fue predicado nuestro Evangelio no sólo con palabras sino también con poder y con el Espíritu Santo, con plena persuasión. Sabéis cómo nos portamos entre vosotros en atención a vosotros.

[[first-thessalonians-1-6]]
^6^ Por vuestra parte, os hicisteis imitadores nuestros y del Señor, abrazando la Palabra con gozo del Espíritu Santo en medio de muchas tribulaciones.

[[first-thessalonians-1-7]]
^7^ De esta manera os habéis convertido en modelo para todos los creyentes de Macedonia y de Acaya.

[[first-thessalonians-1-8]]
^8^ Partiendo de vosotros, en efecto, ha resonado la Palabra del Señor y vuestra fe en Dios se ha difundido no sólo en Macedonia y en Acaya, sino por todas partes, de manera que nada nos queda por decir.

[[first-thessalonians-1-9]]
^9^ Ellos mismos cuentan de nosotros cuál fue nuestra entrada a vosotros, y cómo os convertisteis a Dios, tras haber abandonado los ídolos, para servir a Dios vivo y verdadero,

[[first-thessalonians-1-10]]
^10^ y esperar así a su Hijo Jesús que ha de venir de los cielos, a quien resucitó de entre los muertos y que nos salva de la Cólera venidera.
[[first-thessalonians-2]]
== Capítulo 2

[[first-thessalonians-2-1]]
^1^ Bien sabéis vosotros, hermanos, que nuestra ida a vosotros no fue estéril,

[[first-thessalonians-2-2]]
^2^ sino que, después de haber padecido sufrimientos e injurias en Filipos, como sabéis, confiados en nuestro Dios, tuvimos la valentía de predicaros el Evangelio de Dios entre frequentes luchas.

[[first-thessalonians-2-3]]
^3^ Nuestra exhortación no procede del error, ni de la impureza ni con engaño,

[[first-thessalonians-2-4]]
^4^ sino que así como hemos sido juzgados aptos por Dios para confiarnos el Evangelio, así lo predicamos, no buscando agradar a los hombres, sino a Dios que examina nuestros corazones.

[[first-thessalonians-2-5]]
^5^ Nunca nos presentamos, bien lo sabéis, con palabras aduladoras, ni con pretextos de codicia, Dios es testigo,

[[first-thessalonians-2-6]]
^6^ ni buscando gloria humana, ni de vosotros ni de nadie.

[[first-thessalonians-2-7]]
^7^ Aunque pudimos imponer nuestra autoridad por ser apóstoles de Cristo, nos mostramos amables con vosotros, como una madre cuida con cariño de sus hijos.

[[first-thessalonians-2-8]]
^8^ De esta manera, amándoos a vosotros, queríamos daros no sólo el Evangelio de Dios, sino incluso nuestro propio ser, porque habíais llegado a sernos muy queridos.

[[first-thessalonians-2-9]]
^9^ Pues recordáis, hermanos, nuestros trabajos y fatigas. Trabajando día y noche, para no ser gravosos a ninguno de vosotros, os proclamamos el Evangelio de Dios.

[[first-thessalonians-2-10]]
^10^ Vosotros sois testigos, y Dios también, de cuán santa, justa e irreprochablemente nos comportamos con vosotros, los creyentes.

[[first-thessalonians-2-11]]
^11^ Como un padre a sus hijos, lo sabéis bien, a cada uno de vosotros

[[first-thessalonians-2-12]]
^12^ os exhortábamos y alentábamos, conjurándoos a que vivieseis de una manera digna de Dios, que os ha llamado a su Reino y gloria.

[[first-thessalonians-2-13]]
^13^ De ahí que también por nuestra parte no cesemos de dar gracias a Dios porque, al recibir la Palabra de Dios que os predicamos, la acogisteis, no como palabra de hombre, sino cual es en verdad, como Palabra de Dios, que permanece operante en vosotros, los creyentes.

[[first-thessalonians-2-14]]
^14^ Porque vosotros, hermanos, habéis seguido el ejemplo de las Iglesias de Dios que están en Judea, en Cristo Jesús, pues también vosotros habéis sufrido de vuestros compatriotas las mismas cosas que ellos de parte de los judíos;

[[first-thessalonians-2-15]]
^15^ éstos son los que dieron muerte al Señor y a los profetas y los que nos han perseguido a nosotros; no agradan a Dios y son enemigos de todos los hombres,

[[first-thessalonians-2-16]]
^16^ impidiéndonos predicar a los gentiles para que se salven; así van colmando constantemente la medida de sus pecados; pero la Cólera irrumpe sobre ellos con vehemencia.

[[first-thessalonians-2-17]]
^17^ Mas nosotros, hermanos, separados de vosotros por breve tiempo - físicamente, mas no con el corazón - ansiábamos con ardiente deseo ver vuestro rostro.

[[first-thessalonians-2-18]]
^18^ Por eso quisimos ir a vosotros - yo mismo, Pablo, lo intenté una y otra vez - pero Satanás nos lo impidió.

[[first-thessalonians-2-19]]
^19^ Pues ¿cuál es nuestra esperanza, nuestro gozo, la corona de la que nos sentiremos orgullosos, ante nuestro Señor Jesús en su Venida, sino vosotros?

[[first-thessalonians-2-20]]
^20^ Sí, vosotros sois nuestra gloria y nuestro gozo.
[[first-thessalonians-3]]
== Capítulo 3

[[first-thessalonians-3-1]]
^1^ Por lo cual, no pudiendo soportar más, decidimos quedarnos solos en Atenas

[[first-thessalonians-3-2]]
^2^ y os enviamos a Timoteo, hermano nuestro y colaborador de Dios en el Evangelio de Cristo, para afianzaros y daros ánimos en vuestra fe,

[[first-thessalonians-3-3]]
^3^ para que nadie vacile en esas tribulaciones. Bien sabéis que este es nuestro destino:

[[first-thessalonians-3-4]]
^4^ ya cuando estábamos con vosotros os predecíamos que íbamos a sufrir tribulaciones, y es lo que ha sucedido, como sabéis.

[[first-thessalonians-3-5]]
^5^ Por lo cual también yo, no pudiendo soportar ya más, le envié para tener noticias de vuestra fe, no fuera que el Tentador os hubiera tentado y que nuestro trabajo quedara reducido a nada.

[[first-thessalonians-3-6]]
^6^ Nos acaba de llegar de ahí Timoteo y nos ha traído buenas noticias de vuestra fe y vuestra caridad; y dice que conserváis siempre buen recuerdo de nosotros y que deseáis vernos, así como nosotros a vosotros.

[[first-thessalonians-3-7]]
^7^ Así pues, hermanos, hemos recibido de vosotros un gran consuelo, motivado por vuestra fe, en medio de todas nuestras congojas y tribulaciones.

[[first-thessalonians-3-8]]
^8^ Ahora sí que vivimos, pues permanecéis firmes en el Señor.

[[first-thessalonians-3-9]]
^9^ Y ¿cómo podremos agradecer a Dios por vosotros, por todo el gozo que, por causa vuestra, experimentamos ante nuestro Dios?

[[first-thessalonians-3-10]]
^10^ Noche y día le pedimos insistentemente poder ver vuestro rostro y completar lo que falta a vuestra fe.

[[first-thessalonians-3-11]]
^11^ Que Dios mismo, nuestro Padre y nuestro Señor Jesús orienten nuestros pasos hacia vosotros.

[[first-thessalonians-3-12]]
^12^ En cuanto a vosotros, que el Señor os haga progresar y sobreabundar en el amor de unos con otros, y en el amor para con todos, como es nuestro amor para con vosotros,

[[first-thessalonians-3-13]]
^13^ para que se consoliden vuestros corazones con santidad irreprochable ante Dios, nuestro Padre, en la Venida de nuestro Señor Jesucristo, con todos sus santos.
[[first-thessalonians-4]]
== Capítulo 4

[[first-thessalonians-4-1]]
^1^ Por lo demás, hermanos, os rogamos y exhortamos en el Señor Jesús a que viváis como conviene que viváis para agradar a Dios, según aprendisteis de nosotros, y a que progreséis más.

[[first-thessalonians-4-2]]
^2^ Sabéis, en efecto, las instrucciones que os dimos de parte del Señor Jesús.

[[first-thessalonians-4-3]]
^3^ Porque esta es la voluntad de Dios: vuestra santificación; que os alejéis de la fornicación,

[[first-thessalonians-4-4]]
^4^ que cada uno de vosotros sepa poseer su cuerpo con santidad y honor,

[[first-thessalonians-4-5]]
^5^ y no dominado por la pasión, como hacen los gentiles que no conocen a Dios.

[[first-thessalonians-4-6]]
^6^ Que nadie falte a su hermano ni se aproveche de él en este punto, pues el Señor se vengará de todo esto, como os lo dijimos ya y lo atestiguamos,

[[first-thessalonians-4-7]]
^7^ pues no nos llamó Dios a la impureza, sino a la santidad.

[[first-thessalonians-4-8]]
^8^ Así pues, el que esto deprecia, no desprecia a un hombre, sino a Dios, que os hace don de su Espíritu Santo.

[[first-thessalonians-4-9]]
^9^ En cuanto al amor mutuo, no necesitáis que os escriba, ya que vosotros habéis sido instruidos por Dios para amaros mutuamente.

[[first-thessalonians-4-10]]
^10^ Y lo practicáis bien con los hermanos de toda Macedonia. Pero os exhortamos, hermanos, a que continuéis practicándolo más y más,

[[first-thessalonians-4-11]]
^11^ y a que ambicionéis vivir en tranquilidad, ocupándoos en vuestros asuntos, y trabajando con vuestras manos, como os lo tenemos ordenado,

[[first-thessalonians-4-12]]
^12^ a fin de que viváis dignamente ante los de fuera, y no necesitéis de nadie.

[[first-thessalonians-4-13]]
^13^ Hermanos, no queremos que estéis en la ignorancia respecto de los muertos, para que no os entristezcáis como los demás, que no tienen esperanza.

[[first-thessalonians-4-14]]
^14^ Porque si creemos que Jesús murió y que resucitó, de la misma manera Dios llevará consigo a quienes murieron en Jesús.

[[first-thessalonians-4-15]]
^15^ Os decimos eso como Palabra des Señor: Nosotros, los que vivamos, los que quedemos hasta la Venida del Señor no nos adelantaremos a los que murieron.

[[first-thessalonians-4-16]]
^16^ El Señor mismo, a la orden dada por la voz de un arcángel y por la trompeta de Dios, bajará del cielo, y los que murieron en Cristo resucitarán en primer lugar.

[[first-thessalonians-4-17]]
^17^ Después nosotros, los que vivamos, los que quedemos, seremos arrebatados en nubes, junto con ellos, al encuentro del Señor en los aires. Y así estaremos siempre con el Señor.

[[first-thessalonians-4-18]]
^18^ Consolaos, pues, mutuamente con estas palabras.
[[first-thessalonians-5]]
== Capítulo 5

[[first-thessalonians-5-1]]
^1^ En lo que se refiere al tiempo y al momento, hermanos, no tenéis necesidad que os escriba.

[[first-thessalonians-5-2]]
^2^ Vosotros mismos sabéis perfectamente que el Día del Señor ha de venir como un ladrón en la noche.

[[first-thessalonians-5-3]]
^3^ Cuando digan: «Paz y seguridad», entonces mismo, de repente, vendrá sobre ellos la ruina, como los dolores de parto a la que está encinta; y no escaparán.

[[first-thessalonians-5-4]]
^4^ Pero vosotros, hermanos, no vivís en la oscuridad, para que ese Día os sorprenda como ladrón,

[[first-thessalonians-5-5]]
^5^ pues todos vosotros sois hijos de la luz e hijos del día. Nosotros no somos de la noche ni de las tinieblas.

[[first-thessalonians-5-6]]
^6^ Así pues, no durmamos como los demás, sino velemos y seamos sobrios.

[[first-thessalonians-5-7]]
^7^ Pues los que duermen, de noche duermen, y los que se embriagan, de noche se embriagan.

[[first-thessalonians-5-8]]
^8^ Nosotros, por el contrario, que somos del día, seamos sobrios; revistamos la coraza de la fe y de la caridad, con el yelmo de la esperanza de salvación.

[[first-thessalonians-5-9]]
^9^ Dios no nos ha destinado para la cólera, sino para obtener la salvación por nuestro Señor Jesucristo,

[[first-thessalonians-5-10]]
^10^ que murió por nosotros, para que, velando o durmiendo, vivamos juntos con él.

[[first-thessalonians-5-11]]
^11^ Por esto, confortaos mutuamente y edificaos los unos a los otros, como ya lo hacéis.

[[first-thessalonians-5-12]]
^12^ Os pedimos, hermanos, que tengáis en consideración a los que trabajan entre vosotros, os presiden en el Señor y os amonestan.

[[first-thessalonians-5-13]]
^13^ Tenedles en la mayor estima con amor por su labor. Vivid en paz unos con otros.

[[first-thessalonians-5-14]]
^14^ Os exhortamos, asimismo, hermanos, a que amonestéis a los que viven desconcertados, animéis a los pusilánimes, sostengáis a los débiles y seáis pacientes con todos.

[[first-thessalonians-5-15]]
^15^ Mirad que nadie devuelva a otro mal por mal, antes bien, procurad siempre el bien mutuo y el de todos.

[[first-thessalonians-5-16]]
^16^ Estad siempre alegres.

[[first-thessalonians-5-17]]
^17^ Orad constantemente.

[[first-thessalonians-5-18]]
^18^ En todo dad gracias, pues esto es lo que Dios, en Cristo Jesús, quiere de vosotros.

[[first-thessalonians-5-19]]
^19^ No extingáis el Espíritu;

[[first-thessalonians-5-20]]
^20^ no despreciéis las profecías;

[[first-thessalonians-5-21]]
^21^ examinadlo todo y quedaos con lo bueno.

[[first-thessalonians-5-22]]
^22^ Absteneos de todo género de mal.

[[first-thessalonians-5-23]]
^23^ Que El, el Dios de la paz, os santifique plenamente, y que todo vuestro ser, el espíritu, el alma y el cuerpo, se conserve sin mancha hasta la Venida de nuestro Señor Jesucristo.

[[first-thessalonians-5-24]]
^24^ Fiel es el que os llama y es él quien lo hará.

[[first-thessalonians-5-25]]
^25^ Hermanos, orad también por nosotros.

[[first-thessalonians-5-26]]
^26^ Saludad a todos los hermanos con el beso santo.

[[first-thessalonians-5-27]]
^27^ Os conjuro por el Señor que esta carta sea leída a todos los hermanos.

[[first-thessalonians-5-28]]
^28^ La gracia de nuestro Señor Jesucristo sea con vosotros.
