[[second-thessalonians]]
= Segunda carta a los Tesalonicenses

[[second-thessalonians-1]]
== Capítulo 1

[[second-thessalonians-1-1]]
^1^ Pablo, Silvano y Timoteo a la Iglesia de los Tesalonicenses, en Dios nuestro Padre y en el Señor Jesucristo.

[[second-thessalonians-1-2]]
^2^ Gracia a vosotros y paz de parte de Dios Padre y del Señor Jesucristo.

[[second-thessalonians-1-3]]
^3^ Tenemos que dar en todo tiempo gracias a Dios por vosotros, hermanos, como es justo, porque vuestra fe está progresando mucho y se acrecienta la mutua caridad de todos y cada uno de vosotros,

[[second-thessalonians-1-4]]
^4^ hasta tal punto que nosotros mismos nos gloriamos de vosotros en las Iglesias de Dios por la tenacidad y la fe en todas las persecuciones y tribulaciones que estáis pasando.

[[second-thessalonians-1-5]]
^5^ Esto es señal del justo juicio de Dios, en el que seréis declarados dignos del Reino de Dios, por cuya causa padecéis.

[[second-thessalonians-1-6]]
^6^ Porque es propio de la justicia de Dios el pagar con tribulación a los que os atribulan,

[[second-thessalonians-1-7]]
^7^ y a vosotros, los atribulados, con el descanso junto con nosotros, cuando el Señor Jesús se revele desde el cielo con sus poderosos ángeles,

[[second-thessalonians-1-8]]
^8^ en medio de una llama de fuego, y tome venganza de los que no conocen a Dios y de los que que no obedecen al Evangelio de nuestro Señor Jesús.

[[second-thessalonians-1-9]]
^9^ Estos sufrirán la pena de una ruina eterna, alejados de la presencia del Señor y de la gloria de su poder,

[[second-thessalonians-1-10]]
^10^ cuando venga en aquel Día a ser glorificado en sus santos y admirado en todos los que hayan creído - pues nuestro testimonio ha sido creído por vosotros.

[[second-thessalonians-1-11]]
^11^ Con este objeto rogamos en todo tiempo por vosotros: que nuestro Dios os haga dignos de la vocación y lleve a término con su poder todo vuestro deseo de hacer el bien y la actividad de la fe,

[[second-thessalonians-1-12]]
^12^ para que así el nombre de nuestro Señor Jesús sea glorificado en vosotros, y vosotros en él, según la gracia de nuestro Dios y del Señor Jesucristo.
[[second-thessalonians-2]]
== Capítulo 2

[[second-thessalonians-2-1]]
^1^ Por lo que respecta a la Venida de nuestro Señor Jesucristo y a nuestra reunión con él, os rogamos, hermanos,

[[second-thessalonians-2-2]]
^2^ que no os dejéis alterar tan fácilmente en vuestro ánimo, ni os alarméis por alguna manifestación del Espíritu, por algunas palabras o por alguna carta presentada como nuestra, que os haga suponer que está inminente el Día del Señor.

[[second-thessalonians-2-3]]
^3^ Que nadie os engañe de ninguna manera. Primero tiene que venir la apostasía y manifestarse el Hombre impío, el Hijo de perdición,

[[second-thessalonians-2-4]]
^4^ el Adversario que se eleva sobre todo lo que que lleva el nombre de Dios o es objeto de culto, hasta el extremo de sentarse él mismo en el Santuario de Dios y proclamar que él mismo es Dios.

[[second-thessalonians-2-5]]
^5^ ¿No os acordáis que ya os dije esto cuando estuve entre vosotros?

[[second-thessalonians-2-6]]
^6^ Vosotros sabéis qué es lo que ahora le retiene, para que se manifieste en su momento oportuno.

[[second-thessalonians-2-7]]
^7^ Porque el ministerio de la impiedad ya está actuando. Tan sólo con que sea quitado de en medio el que ahora le retiene,

[[second-thessalonians-2-8]]
^8^ entonces se manifestará el Impío, a quien el Señor destruirá con el soplo de su boca, y aniquilará con la Manifestación de su Venida.

[[second-thessalonians-2-9]]
^9^ La venida del Impío estará señalada por el influjo de Satanás, con toda clase de milagros, señales, prodigios engañosos,

[[second-thessalonians-2-10]]
^10^ y todo tipo de maldades que seducirán a los que se han de condenar por no haber aceptado el amor de la verdad que les hubiera salvado.

[[second-thessalonians-2-11]]
^11^ Por eso Dios les envía un poder seductor que les hace creer en la mentira,

[[second-thessalonians-2-12]]
^12^ para que sean condenados todos cuantos no creyeron en la verdad y prefirieron la iniquidad.

[[second-thessalonians-2-13]]
^13^ Nosotros, en cambio, debemos dar gracias en todo tiempo a Dios por vosotros, hermanos, amados del Señor, porque Dios os ha escogido desde el principio para la salvación mediante la acción santificadora del Espíritu y la fe en la verdad.

[[second-thessalonians-2-14]]
^14^ Para esto os ha llamado por medio de nuestro Evangelio, para que consigáis la gloria de nuestro Señor Jesucristo.

[[second-thessalonians-2-15]]
^15^ Así pues, hermanos, manteneos firmes y conservad las tradiciones que habéis aprendido de nosotros, de viva voz o por carta.

[[second-thessalonians-2-16]]
^16^ Que el mismo Señor nuestro Jesucristo y Dios, nuestro Padre, que nos ha amado y que nos ha dado gratuitamente una consolación eterna y una esperanza dichosa,

[[second-thessalonians-2-17]]
^17^ consuele vuestros corazones y los afiance en toda obra y palabra buena.
[[second-thessalonians-3]]
== Capítulo 3

[[second-thessalonians-3-1]]
^1^ Finalmente, hermanos, orad por nosotros para que la Palabra del Señor siga propagándose y adquiriendo gloria, como entre vosotros,

[[second-thessalonians-3-2]]
^2^ y para que nos veamos libres de los hombres perversos y malignos; porque la fe no es de todos.

[[second-thessalonians-3-3]]
^3^ Fiel es el Señor; él os afianzará y os guardará del Maligno.

[[second-thessalonians-3-4]]
^4^ En cuanto a vosotros tenemos plena confianza en el Señor de que cumplís y cumpliréis cuanto os mandamos.

[[second-thessalonians-3-5]]
^5^ Que el Señor guíe vuestros corazones hacia el amor de Dios y la tenacidad de Cristo.

[[second-thessalonians-3-6]]
^6^ Hermanos, os mandamos en nombre del Señor Jesucristo que os apartéis de todo hermano que viva desordenadamente y no según la tradición que de nosotros recibisteis.

[[second-thessalonians-3-7]]
^7^ Ya sabéis vosotros cómo debéis imitarnos, pues estando entre vosotros no vivimos desordenadamente,

[[second-thessalonians-3-8]]
^8^ ni comimos de balde el pan de nadie, sino que día y noche con fatiga y cansancio trabajamos para no ser una carga a ninguno de vosotros.

[[second-thessalonians-3-9]]
^9^ No porque no tengamos derecho, sino por daros en nosotros un modelo que imitar.

[[second-thessalonians-3-10]]
^10^ Además, cuando estábamos entre vosotros os mandábamos esto: Si alguno no quiere trabajar, que tampoco coma.

[[second-thessalonians-3-11]]
^11^ Porque nos hemos enterado que hay entre vosotros algunos que viven desordenadamente, sin trabajar nada, pero metiéndose en todo.

[[second-thessalonians-3-12]]
^12^ A ésos les mandamos y les exhortamos en el Señor Jesucristo a que trabajen con sosiego para comer su propio pan.

[[second-thessalonians-3-13]]
^13^ Vosotros, hermanos, no os canséis de hacer el bien.

[[second-thessalonians-3-14]]
^14^ Si alguno no obedece a lo que os decimos en esta carta, a ése señaladle y no tratéis con él, para que se avergüence.

[[second-thessalonians-3-15]]
^15^ Pero no lo miréis como a enemigo, sino amonestadle como a hermano.

[[second-thessalonians-3-16]]
^16^ Que El, el Señor de la paz, os conceda la paz siempre y en todos los órdenes. El Señor sea con todos vosotros.

[[second-thessalonians-3-17]]
^17^ El saludo va de mi mano, Pablo. Esta es la firma en todas mis cartas; así escribo.

[[second-thessalonians-3-18]]
^18^ La gracia de nuestro Señor Jesucristo sea con todos vosotros.
