[[titus]]
= Tito

[[titus-1]]
== Capítulo 1

[[titus-1-1]]
^1^ Pablo, siervo de Dios, apóstol de Jesucristo para llevar a los escogidos de Dios a la fe y al pleno conocimiento de la verdad que es conforme a la piedad,

[[titus-1-2]]
^2^ con la esperanza de vida eterna, prometida desde toda la eternidad por Dios que no miente,

[[titus-1-3]]
^3^ y que en el tiempo oportuno ha manifestado su Palabra por la predicación a mí encomendada según el mandato de Dios nuestro Salvador,

[[titus-1-4]]
^4^ a Tito, verdadero hijo según la fe común. Gracia y paz de parte de Dios Padre y de Cristo Jesús, nuestro Salvador.

[[titus-1-5]]
^5^ El motivo de haberte dejado en Creta, fue para que acabaras de organizar lo que faltaba y establecieras presbíteros en cada ciudad, como yo te ordené.

[[titus-1-6]]
^6^ El candidato debe ser irreprochable, casado una sola vez, cuyos hijos sean creyentes, no tachados de libertinaje ni de rebeldía.

[[titus-1-7]]
^7^ Porque el epíscopo, como administrador de Dios, debe ser irreprochable; no arrogante, no colérico, no bebedor, no violento, no dado a negocios sucios;

[[titus-1-8]]
^8^ sino hospitalario, amigo del bien, sensato, justo, piadoso, dueño de sí.

[[titus-1-9]]
^9^ Que esté adherido a la palabra fiel, conforme a la enseñanza, para que sea capaz de exhortar con la sana doctrina y refutar a los que contradicen.

[[titus-1-10]]
^10^ Porque hay muchos rebeldes, vanos habladores y embaucadores, sobre todo entre los de la circuncisión,

[[titus-1-11]]
^11^ a quienes es menester tapar la boca; hombres que trastornan familias enteras, enseñando por torpe ganancia lo que no deben.

[[titus-1-12]]
^12^ Uno de ellos, profeta suyo, dijo: «Los cretenses son siempre mentirosos, malas bestias, vientres perezosos».

[[titus-1-13]]
^13^ Este testimonio es verdadero. Por tanto repréndeles severamente, a fin de que conserven sana la fe,

[[titus-1-14]]
^14^ y no den oídos a fábulas judaicas, ni a mandamientos de hombres que se apartan de la verdad.

[[titus-1-15]]
^15^ Para los limpios todo es limpio; mas para los contaminados e incrédulos nada hay limpio, pues su mente y conciencia están contaminadas.

[[titus-1-16]]
^16^ Profesan conocer a Dios, mas con sus obras le niegan; son abominables y rebeldes e incapaces de toda obra buena.
[[titus-2]]
== Capítulo 2

[[titus-2-1]]
^1^ Mas tú enseña lo que es conforme a la sana doctrina;

[[titus-2-2]]
^2^ que los ancianos sean sobrios, dignos, sensatos, sanos en la fe, en la caridad, en la paciencia, en el sufrimiento;

[[titus-2-3]]
^3^ que las ancianas asimismo sean en su porte cual conviene a los santos: no calumniadoras ni esclavas de mucho vino, maestras del bien,

[[titus-2-4]]
^4^ para que enseñen a las jóvenes a ser amantes de sus maridos y de sus hijos,

[[titus-2-5]]
^5^ a ser sensatas, castas, hacendosas, bondadosas, sumisas a sus maridos, para que no sea injuriada la Palabra de Dios.

[[titus-2-6]]
^6^ Exhorta igualmente a los jóvenes para que sean sensatos en todo.

[[titus-2-7]]
^7^ Muéstrate dechado de buenas obras: pureza de doctrina, dignidad,

[[titus-2-8]]
^8^ palabra sana, intachable, para que el adversario se avergüence, no teniendo nada malo que decir de nosotros.

[[titus-2-9]]
^9^ Que los esclavos estén sometidos en todo a sus dueños, sean complacientes y no les contradigan;

[[titus-2-10]]
^10^ que no les defrauden, antes bien muestren una fidelidad perfecta para honrar en todo la doctrina de Dios nuestro Salvador.

[[titus-2-11]]
^11^ Porque se ha manifestado la gracia salvadora de Dios a todos los hombres,

[[titus-2-12]]
^12^ que nos enseña a que, renunciando a la impiedad y a las pasiones mundanas, vivamos con sensatez, justicia y piedad en el siglo presente,

[[titus-2-13]]
^13^ aguardando la feliz esperanza y la Manifestación de la gloria del gran Dios y Salvador nuestro Jesucristo;

[[titus-2-14]]
^14^ el cual se entregó por nosotros a fin de rescatarnos de toda iniquidad y purificar para sí un pueblo que fuese suyo, fervoroso en buenas obras.

[[titus-2-15]]
^15^ Así has de enseñar, exhortar y reprender con toda autoridad. Que nadie te desprecie.
[[titus-3]]
== Capítulo 3

[[titus-3-1]]
^1^ Amonéstales que vivan sumisos a los magistrados y a las autoridades, que les obedezcan y estén prontos para toda obra buena;

[[titus-3-2]]
^2^ que no injurien a nadie, que no sean pendencieros sino apacibles, mostrando una perfecta mansedumbre con todos los hombres.

[[titus-3-3]]
^3^ Pues también nosotros fuimos en algún tiempo insensatos, desobedientes, descarriados, esclavos de toda suerte de pasiones y placeres, viviendo en malicia y envidia, aborrecibles y aborreciéndonos unos a otros.

[[titus-3-4]]
^4^ Mas cuando se manifestó la bondad de Dios nuestro Salvador y su amor a los hombres,

[[titus-3-5]]
^5^ él nos salvó, no por obras de justicia que hubiésemos hecho nosotros, sino según su misericordia, por medio del baño de regeneración y de renovación del Espíritu Santo,

[[titus-3-6]]
^6^ que derramó sobre nosotros con largueza por medio de Jesucristo nuestro Salvador,

[[titus-3-7]]
^7^ para que, justificados por su gracia, fuésemos constituidos herederos, en esperanza, de vida eterna.

[[titus-3-8]]
^8^ Es cierta esta afirmación, y quiero que en esto te mantengas firme, para que los que creen en Dios traten de sobresalir en la práctica de las buenas obras. Esto es bueno y provechoso para los hombres.

[[titus-3-9]]
^9^ Evita discusiones necias, genealogías, contiendas y disputas sobre la Ley, porque son inútiles y vanas.

[[titus-3-10]]
^10^ Al sectario, después de una y otra amonestación, rehúyele;

[[titus-3-11]]
^11^ ya sabes que ése está pervertido y peca, condenado por su propia sentencia.

[[titus-3-12]]
^12^ Cuando te envíe a Artemas o a Tíquico, date prisa en venir donde mí a Nicópolis, porque he pensado pasar allí el invierno.

[[titus-3-13]]
^13^ Cuida de proveer de todo lo necesario para el viaje a Zenas, el perito en la Ley, y a Apolo, de modo que nada les falte.

[[titus-3-14]]
^14^ Que aprendan también los nuestros a sobresalir en la práctica de las buenas obras, atendiendo a las necesidades urgentes, para que no sean unos inútiles.

[[titus-3-15]]
^15^ Te saludan todos los que están conmigo. Saluda a los que nos aman en la fe. La gracia sea con todos vosotros.
