[[philemon]]
= Filemón

[[philemon-1]]
== Capítulo 1

[[philemon-1-1]]
^1^ Pablo, preso de Cristo Jesús, y Timoteo, el hermano, a nuestro querido amigo y colaborador Filemón,

[[philemon-1-2]]
^2^ a la hermana Apfia, a nuestro compañero de armas, Arquipo, y a la Iglesia de tu casa.

[[philemon-1-3]]
^3^ Gracia y paz a vosotros de parte de Dios, nuestro Padre, y del Señor Jesucristo.

[[philemon-1-4]]
^4^ Doy gracias sin cesar a mi Dios, recordándote en mis oraciones,

[[philemon-1-5]]
^5^ pues tengo noticia de tu caridad y de tu fe para con el Señor Jesús y para bien de todos los santos,

[[philemon-1-6]]
^6^ a fin de que tu participación en la fe se haga eficiente mediante el conocimiento perfecto de todo el bien que hay en nosotros en orden a Cristo.

[[philemon-1-7]]
^7^ Pues tuve gran alegría y consuelo a causa de tu caridad, por el alivio que los corazones de los santos han recibido de ti, hermano.

[[philemon-1-8]]
^8^ Por lo cual, aunque tengo en Cristo bastante libertad para mandarte lo que conviene,

[[philemon-1-9]]
^9^ prefiero más bien rogarte en nombre de la caridad, yo, este Pablo ya anciano, y además ahora preso de Cristo Jesús.

[[philemon-1-10]]
^10^ Te ruego en favor de mi hijo, a quien engendré entre cadenas, Onésimo,

[[philemon-1-11]]
^11^ que en otro tiempo te fue inútil, pero ahora muy útil para ti y para mí.

[[philemon-1-12]]
^12^ Te lo devuelvo, a éste, mi propio corazón.

[[philemon-1-13]]
^13^ Yo querría retenerle conmigo, para que me sirviera en tu lugar, en estas cadenas por el Evangelio;

[[philemon-1-14]]
^14^ mas, sin consultarte, no he querido hacer nada, para que esta buena acción tuya no fuera forzada sino voluntaria.

[[philemon-1-15]]
^15^ Pues tal vez fue alejado de ti por algún tiempo, precisamente para que lo recuperaras para siempre,

[[philemon-1-16]]
^16^ y no como esclavo, sino como algo mejor que un esclavo, como un hermano querido, que, siéndolo mucho para mí, ¡cuánto más lo será para ti, no sólo como amo, sino también en el Señor!.

[[philemon-1-17]]
^17^ Por tanto, si me tienes como algo unido a ti, acógele como a mí mismo.

[[philemon-1-18]]
^18^ Y si en algo te perjudicó, o algo te debe, ponlo a mi cuenta.

[[philemon-1-19]]
^19^ Yo mismo, Pablo, lo firmo con mi puño; yo te lo pagaré... Por no recordarte deudas para conmigo, pues tú mismo te me debes.

[[philemon-1-20]]
^20^ Sí, hermano, hazme este favor en el Señor. ¡Alivia mi corazón en Cristo!

[[philemon-1-21]]
^21^ Te escribo confiado en tu docilidad, seguro de que harás más de lo que te pido.

[[philemon-1-22]]
^22^ Y al mismo tiempo, prepárame hospedaje; pues espero que por vuestras oraciones se os concederá la gracia de mi presencia.

[[philemon-1-23]]
^23^ Te saludan Epafras, mi compañero de cautiverio en Cristo Jesús,

[[philemon-1-24]]
^24^ Marcos, Aristarco, Demas y Lucas, mis colaboradores.

[[philemon-1-25]]
^25^ Que la gracia del Señor Jesucristo sea con vuestro espíritu.
