[[hebrews]]
= Hebreos

[[hebrews-1]]
== Capítulo 1

[[hebrews-1-1]]
^1^ Muchas veces y de muchos modos habló Dios en el pasado a nuestros Padres por medio de los Profetas;

[[hebrews-1-2]]
^2^ en estos últimos tiempos nos ha hablado por medio del Hijo a quien instituyó heredero de todo, por quien también hizo los mundos;

[[hebrews-1-3]]
^3^ el cual, siendo resplandor de su gloria e impronta de su sustancia, y el que sostiene todo con su palabra poderosa, después de llevar a cabo la purificación de los pecados, se sentó a la diestra de la Majestad en las alturas,

[[hebrews-1-4]]
^4^ con una superioridad sobre los ángeles tanto mayor cuanto más les supera en el nombre que ha heredado.

[[hebrews-1-5]]
^5^ En efecto, ¿a qué ángel dijo alguna vez: Hijo mío eres tú; yo te he engendrado hoy; y también: Yo seré para él Padre, y él será para mi Hijo?

[[hebrews-1-6]]
^6^ Y nuevamente al introducir a su Primogénito en el mundo dice: Y adórenle todos los ángeles de Dios.

[[hebrews-1-7]]
^7^ Y de los ángeles dice: El que hace a sus ángeles vientos, y a sus servidores llamas de fuego.

[[hebrews-1-8]]
^8^ Pero del Hijo: Tu trono, ¡oh Dios!, por los siglos de los siglos; y: El cetro de tu realeza, cetro de equidad.

[[hebrews-1-9]]
^9^ Amaste la justicia y aborreciste la iniquidad; por eso te ungió, ¡oh Dios!, tu Dios con óleo de alegría con preferencia a tus compañeros.

[[hebrews-1-10]]
^10^ Y también: Tú al comienzo, ¡oh Señor!, pusiste los cimientos de la tierra, y obras de tu mano son los cielos.

[[hebrews-1-11]]
^11^ Ellos perecerán, mas tú permaneces; todos como un vestido envejecerán;

[[hebrews-1-12]]
^12^ como un manto los enrollarás, como un vestido, y serán cambiados. Pero tú eres el mismo y tus años no tendrán fin.

[[hebrews-1-13]]
^13^ Y ¿a qué ángel dijo alguna vez: Siéntate a mi diestra, hasta que ponga a tus enemigos por escabel de tus pies?

[[hebrews-1-14]]
^14^ ¿Es que no son todos ellos espíritus servidores con la misión de asistir a los que han de heredar la salvación?
[[hebrews-2]]
== Capítulo 2

[[hebrews-2-1]]
^1^ Por tanto, es preciso que prestemos mayor atención a lo que hemos oído, para que no nos extraviemos.

[[hebrews-2-2]]
^2^ Pues si la palabra promulgada por medio de los ángeles obtuvo tal firmeza que toda transgresión y desobediencia recibió justa retribución,

[[hebrews-2-3]]
^3^ ¿cómo saldremos absueltos nosotros si descuidamos tan gran salvación? La cual comenzó a ser anunciada por el Señor, y nos fue luego confirmada por quienes la oyeron,

[[hebrews-2-4]]
^4^ testificando también Dios con señales y prodigios, con toda suerte de milagros y dones del Espíritu Santo repartidos según su voluntad.

[[hebrews-2-5]]
^5^ En efecto, Dios no sometió a los ángeles el mundo venidero del cual estamos hablando.

[[hebrews-2-6]]
^6^ Pues atestiguó alguien en algún lugar: ¿Qué es el hombre, que te acuerdas de él? ¿O el hijo del hombre, que de él te preocupas?

[[hebrews-2-7]]
^7^ Le hiciste por un poco inferior a los ángeles; de gloria y honor le coronaste.

[[hebrews-2-8]]
^8^ Todo lo sometiste debajo de sus pies. Al someterle todo, nada dejó que no le estuviera sometido. Mas al presente, no vemos todavía que le esté sometido todo.

[[hebrews-2-9]]
^9^ Y a aquel que fue hecho inferior a los ángeles por un poco, a Jesús, le vemos coronado de gloria y honor por haber padecido la muerte, pues por la gracia de Dios gustó la muerte para bien de todos.

[[hebrews-2-10]]
^10^ Convenía, en verdad, que Aquel por quien es todo y para quien es todo, llevara muchos hijos a la gloria, perfeccionando mediante el sufrimiento al que iba a guiarlos a la salvación.

[[hebrews-2-11]]
^11^ Pues tanto el santificador como los santificados tienen todos el mismo origen. Por eso no se avergüenza de llamarles hermanos

[[hebrews-2-12]]
^12^ cando dice: Anunciaré tu nombre a mis hermanos; en medio de la asamblea te cantaré himnos. Y también:

[[hebrews-2-13]]
^13^ Pondré en él mi confianza. Y nuevamente: Henos aquí, a mí y a los hijos que Dios me dio.

[[hebrews-2-14]]
^14^ Por tanto, así como los hijos participan de la sangre y de la carne, así también participó él de las mismas, para aniquilar mediante la muerte al señor de la muerte, es decir, al Diablo,

[[hebrews-2-15]]
^15^ y libertar a cuantos, por temor a la muerte, estaban de por vida sometidos a esclavitud.

[[hebrews-2-16]]
^16^ Porque, ciertamente, no se ocupa de los ángeles, sino de la descendencia de Abraham.

[[hebrews-2-17]]
^17^ Por eso tuvo que asemejarse en todo a sus hermanos, para ser misericordioso y Sumo Sacerdote fiel en lo que toca a Dios, en orden a expiar los pecados del pueblo.

[[hebrews-2-18]]
^18^ Pues, habiendo sido probado en el sufrimiento, puede ayudar a los que se ven probados.
[[hebrews-3]]
== Capítulo 3

[[hebrews-3-1]]
^1^ Por tanto, hermanos santos, partícipes de una vocación celestial, considerad al apóstol y Sumo Sacerdote de nuestra fe, a Jesús,

[[hebrews-3-2]]
^2^ que es fiel al que le instituyó, como lo fue también Moisés en toda su casa.

[[hebrews-3-3]]
^3^ Pues ha sido juzgado digno de una gloria en tanto superior a la de Moisés, en cuanto la dignidad del constructor de la casa supera a la casa misma.

[[hebrews-3-4]]
^4^ Porque toda casa tiene su constructor; mas el constructor del universo es Dios.

[[hebrews-3-5]]
^5^ Ciertamente, Moisés fue fiel en toda su casa, como servidor, para atestiguar cuanto había de anunciarse,

[[hebrews-3-6]]
^6^ pero Cristo lo fue como hijo, al frente de su propia casa, que somos nosotros, si es que mantenemos la entereza y la gozosa satisfacción de la esperanza.

[[hebrews-3-7]]
^7^ Por eso, como dice el Espíritu Santo: Si oís hoy su voz,

[[hebrews-3-8]]
^8^ no endurezcáis vuestros corazones como en la Querella, el día de la provocación en el desierto,

[[hebrews-3-9]]
^9^ donde me provocaron vuestros padres y me pusieron a prueba, aun después de haber visto mis obras

[[hebrews-3-10]]
^10^ durante cuarenta años. Por eso me irrité contra esa generación y dije: Andan siempre errados en su corazón; no conocieron mis caminos.

[[hebrews-3-11]]
^11^ Por eso juré en mi cólera: ¡No entrarán en mi descanso!

[[hebrews-3-12]]
^12^ ¡Mirad, hermanos!, que no haya en ninguno de vosotros un corazón maleado por la incredulidad que le haga apostatar de Dios vivo;

[[hebrews-3-13]]
^13^ antes bien, exhortaos mutuamente cada día mientras dure este hoy, para que ninguno de vosotros se endurezca seducido por el pecado.

[[hebrews-3-14]]
^14^ Pues hemos venido a ser partícipes de Cristo, a condición de que mantengamos firme hasta el fin la segura confianza del principio.

[[hebrews-3-15]]
^15^ Al decir: Si oís hoy su voz, no endurezcáis vuestros corazones como en la Querella,

[[hebrews-3-16]]
^16^ ¿quiénes son los que, habiéndole oído, le movieron querella? ¿Es que no fueron todos los que salieron de Egipto por medio de Moisés?

[[hebrews-3-17]]
^17^ Y ¿contra quiénes se irritó durante cuarenta años? ¿No fue acaso contra los que pecaron, cuyos cadáveres cayeron en el desierto?

[[hebrews-3-18]]
^18^ Y ¿a quiénes juró que no entrarían en su descanso sino a los que desobedecieron?

[[hebrews-3-19]]
^19^ Así, vemos que no pudieron entrar a causa de su incredulidad.
[[hebrews-4]]
== Capítulo 4

[[hebrews-4-1]]
^1^ Temamos, pues; no sea que, permaneciendo aún en vigor la promesa de entrar en su descanso, alguno de vosotros parezca llegar rezagado.

[[hebrews-4-2]]
^2^ También nosotros hemos recibido una buena nueva, lo mismo que ellos. Pero la palabra que oyeron no aprovechó nada a aquellos que no estaban unidos por la fe a los que escucharon.

[[hebrews-4-3]]
^3^ De hecho, hemos entrado en el descanso los que hemos creído, según está dicho: Por eso juré en mi cólera: ¡No entrarán en mi descanso! Y eso que las obras de Dios estaban terminadas desde la creación del mundo,

[[hebrews-4-4]]
^4^ pues en algún lugar dice acerca del día séptimo: Y descansó Dios el día séptimo de todas sus obras.

[[hebrews-4-5]]
^5^ Y también en el pasaje citado: ¡No entrarán en mi descanso!

[[hebrews-4-6]]
^6^ Por tanto, quedando en claro que algunos han de entrar en él, y que los primeros en recibir la buena nueva no entraron a causa de su desobediencia,

[[hebrews-4-7]]
^7^ vuelve a señalar un día, hoy, diciendo por David al cabo de tanto tiempo, como queda dicho: Si oís hoy su voz, no endurezcáis vuestros corazones...

[[hebrews-4-8]]
^8^ Porque si Josué les hubiera proporcionado el descanso, no habría hablado Dios más tarde, de otro día.

[[hebrews-4-9]]
^9^ Por tanto es claro que queda un descanso sabático para el pueblo de Dios.

[[hebrews-4-10]]
^10^ Pues quien entra en su descanso, también él descansa de sus trabajos, al igual que Dios de los suyos.

[[hebrews-4-11]]
^11^ Esforcémonos, pues, por entrar en ese descanso, para que nadie caiga imitando aquella desobediencia.

[[hebrews-4-12]]
^12^ Ciertamente, es viva la Palabra de Dios y eficaz, y más cortante que espada alguna de dos filos. Penetra hasta las fronteras entre el alma y el espíritu, hasta las junturas y médulas; y escruta los sentimientos y pensamientos del corazón.

[[hebrews-4-13]]
^13^ No hay para ella criatura invisible: todo está desnudo y patente a los ojos de Aquel a quien hemos de dar cuenta.

[[hebrews-4-14]]
^14^ Teniendo, pues, tal Sumo Sacerdote que penetró los cielos - Jesús, el Hijo de Dios - mantengamos firmes la fe que profesamos.

[[hebrews-4-15]]
^15^ Pues no tenemos un Sumo Sacerdote que no pueda compadecerse de nuestras flaquezas, sino probado en todo igual que nosotros, excepto en el pecado.

[[hebrews-4-16]]
^16^ Acerquémonos, por tanto, confiadamente al trono de gracia, a fin de alcanzar misericordia y hallar gracia para una ayuda oportuna.
[[hebrews-5]]
== Capítulo 5

[[hebrews-5-1]]
^1^ Porque todo Sumo Sacerdote es tomado de entre los hombres y está puesto en favor de los hombres en lo que se refiere a Dios para ofrecer dones y sacrificios por los pecados;

[[hebrews-5-2]]
^2^ y puede sentir compasión hacia los ignorantes y extraviados, por estar también él envuelto en flaqueza.

[[hebrews-5-3]]
^3^ Y a causa de esa misma flaqueza debe ofrecer por los pecados propios igual que por los del pueblo.

[[hebrews-5-4]]
^4^ Y nadie se arroga tal dignidad, sino el llamado por Dios, lo mismo que Aarón.

[[hebrews-5-5]]
^5^ De igual modo, tampoco Cristo se apropió la gloria del Sumo Sacerdocio, sino que la tuvo de quien le dijo: Hijo mío eres tú; yo te he engendrado hoy.

[[hebrews-5-6]]
^6^ Como también dice en otro lugar: Tú eres sacerdote para siempre, a semejanza de Melquisedec.

[[hebrews-5-7]]
^7^ El cual, habiendo ofrecido en los días de su vida mortal ruegos y súplicas con poderoso clamor y lágrimas al que podía salvarle de la muerte, fue escuchado por su actitud reverente,

[[hebrews-5-8]]
^8^ y aun siendo Hijo, con lo que padeció experimentó la obediencia;

[[hebrews-5-9]]
^9^ y llegado a la perfección, se convirtió en causa de salvación eterna para todos los que le obedecen,

[[hebrews-5-10]]
^10^ proclamado por Dios Sumo Sacerdote a semejanza de Melquisedec.

[[hebrews-5-11]]
^11^ Sobre este particular tenemos muchas cosas que decir, aunque difíciles de explicar, porque os habéis hecho tardos de entendimiento.

[[hebrews-5-12]]
^12^ Pues debiendo ser ya maestros en razón del tiempo, volvéis a tener necesidad de ser instruidos en los primeros rudimentos de los oráculos divinos, y os habéis hecho tales que tenéis necesidad de leche en lugar de manjar sólido.

[[hebrews-5-13]]
^13^ Pues todo el que se nutre de leche desconoce la doctrina de la justicia, porque es niño.

[[hebrews-5-14]]
^14^ En cambio, el manjar sólido es de adultos; de aquellos que, por costumbre, tienen las facultades ejercitadas en el discernimiento del bien y del mal.
[[hebrews-6]]
== Capítulo 6

[[hebrews-6-1]]
^1^ Por eso, dejando aparte la enseñanza elemental acerca de Cristo, elevémonos a lo perfecto, sin reiterar los temas fundamentales del arrepentimiento de las obras muertas y de la fe en Dios;

[[hebrews-6-2]]
^2^ de la instrucción sobre los bautismos y de la imposición de las manos; de la resurrección de los muertos y del juicio eterno.

[[hebrews-6-3]]
^3^ Y así procederemos con el favor de Dios.

[[hebrews-6-4]]
^4^ Porque es imposible que cuantos fueron una vez iluminados, gustaron el don celestial y fueron hechos partícipes del Espíritu Santo,

[[hebrews-6-5]]
^5^ saborearon las buenas nuevas de Dios y los prodigios del mundo futuro,

[[hebrews-6-6]]
^6^ y a pesar de todo cayeron, se renueven otra vez mediante la penitencia, pues crucifican por su parte de nuevo al Hijo de Dios y le exponen a pública infamia.

[[hebrews-6-7]]
^7^ Porque la tierra que recibe frecuentes lluvias y produce buena vegetación para los que la cultivan participa de la bendición de Dios.

[[hebrews-6-8]]
^8^ Por lo contrario, la que produce espinas y abrojos es desechada, y cerca está de la maldición, y terminará por ser quemada.

[[hebrews-6-9]]
^9^ Pero de vosotros, queridos, aunque hablemos así, esperamos cosas mejores y conducentes a la salvación.

[[hebrews-6-10]]
^10^ Porque no es injusto Dios para olvidarse de vuestra labor y del amor que habéis mostrado hacia su nombre, con los servicios que habéis prestado y prestáis a los santos.

[[hebrews-6-11]]
^11^ Deseamos, no obstante, que cada uno de vosotros manifieste hasta el fin la misma diligencia para la plena realización de la esperanza,

[[hebrews-6-12]]
^12^ de forma que no os hagáis indolentes, sino más bien imitadores de aquellos que, mediante la fe y la perseverancia, heredan las promesas.

[[hebrews-6-13]]
^13^ Cuando Dios hizo la Promesa a Abraham, no teniendo a otro mayor por quien jurar, juró por sí mismo

[[hebrews-6-14]]
^14^ diciendo: ¡Sí!, te colmaré de bendiciones y te acrecentaré en gran manera.

[[hebrews-6-15]]
^15^ Y perseverando de esta manera, alcanzó la Promesa.

[[hebrews-6-16]]
^16^ Pues los hombres juran por uno superior y entre ellos el juramento es la garantía que pone fin a todo litigio.

[[hebrews-6-17]]
^17^ Por eso Dios, queriendo mostrar más plenamente a los herederos de la Promesa la inmutabilidad de su decisión, interpuso el juramento,

[[hebrews-6-18]]
^18^ para que, mediante dos cosas inmutables por las cuales es imposible que Dios mienta, nos veamos más poderosamente animados los que buscamos un refugio asiéndonos a la esperanza propuesta,

[[hebrews-6-19]]
^19^ que nosotros tenemos como segura y sólida ancla de nuestra alma, y que penetra hasta más allá del velo,

[[hebrews-6-20]]
^20^ adonde entró por nosotros como precursor Jesús, hecho, a semejanza de Melquisedec, Sumo Sacerdote para siempre.
[[hebrews-7]]
== Capítulo 7

[[hebrews-7-1]]
^1^ En efecto, este Melquisedec, rey de Salem, sacerdote de Dios Altísimo, que salió al encuentro de Abraham cuando regresaba de la derrota de los reyes, y le bendijo,

[[hebrews-7-2]]
^2^ al cual dio Abraham el diezmo de todo, y cuyo nombre significa, en primer lugar, «rey de justicia» y, además, rey de Salem, es decir, «rey de paz»,

[[hebrews-7-3]]
^3^ sin padre, ni madre, ni genealogía, sin comienzo de días, ni fin de vida, asemejado al Hijo de Dios, permanece sacerdote para siempre.

[[hebrews-7-4]]
^4^ Mirad ahora cuán grande es éste, a quien el mismo Patriarca Abraham dio el diezmo de entre lo mejor del botín.

[[hebrews-7-5]]
^5^ Es cierto que los hijos de Leví que reciben el sacerdocio tienen orden según la Ley de percibir el diezmo del pueblo, es decir, de sus hermanos, aunque también proceden éstos de la estirpe de Abraham;

[[hebrews-7-6]]
^6^ mas aquél, sin pertenecer a su genealogía, recibió el diezmo de Abraham, y bendijo al que tenía las promesas.

[[hebrews-7-7]]
^7^ Pues bien, es incuestionable que el inferior recibe la bendición del superior.

[[hebrews-7-8]]
^8^ Y aquí, ciertamente, reciben el diezmo hombres mortales; pero allí, uno de quien se asegura que vive.

[[hebrews-7-9]]
^9^ Y, en cierto modo, hasta el mismo Leví, que percibe los diezmos, los pagó por medio de Abraham,

[[hebrews-7-10]]
^10^ pues ya estaba en las entrañas de su padre cuando Melquisedec le salió al encuentro.

[[hebrews-7-11]]
^11^ Pues bien, si la perfección estuviera en poder del sacerdocio levítico - pues sobre él descansa la Ley dada al pueblo -, ¿qué necesidad había ya de que surgiera otro sacerdote a semejanza de Melquisedec, y no «a semejanza de Aaron»?

[[hebrews-7-12]]
^12^ Porque, cambiado el sacerdocio, necesariamente se cambia la Ley.

[[hebrews-7-13]]
^13^ Pues aquel de quien se dicen estas cosas, pertenecía a otra tribu, de la cual nadie sirvió al altar.

[[hebrews-7-14]]
^14^ Y es bien manifiesto que nuestro Señor procedía de Judá, y a esa tribu para nada se refirió Moisés al hablar del sacerdocio.

[[hebrews-7-15]]
^15^ Todo esto es mucho más evidente aún si surge otro sacerdote a semejanza de Melquisedec,

[[hebrews-7-16]]
^16^ que lo sea, no por ley de prescripción carnal, sino según la fuerza de una vida indestructible.

[[hebrews-7-17]]
^17^ De hecho, está atestiguado: Tú eres sacerdote para siempre, a semejanza de Melquisedec.

[[hebrews-7-18]]
^18^ De este modo queda abrogada la ordenación precedente, por razón de su ineficacia e inutilidad,

[[hebrews-7-19]]
^19^ ya que la Ley no llevó nada a la perfección, pues no era más que introducción a una esperanza mejor, por la cual nos acercamos a Dios.

[[hebrews-7-20]]
^20^ Y por cuanto no fue sin juramento - pues los otros fueron hechos sacerdotes sin juramento,

[[hebrews-7-21]]
^21^ mientras éste lo fue bajo juramento por Aquel que le dijo: «Juró el Señor y no se arrepentirá: Tú eres sacerdote para siempre» -

[[hebrews-7-22]]
^22^ por eso, de una mejor Alianza resultó fiador Jesús.

[[hebrews-7-23]]
^23^ Además, aquellos sacerdotes fueron muchos, porque la muerte les impedía perdurar.

[[hebrews-7-24]]
^24^ Pero éste posee un sacerdocio perpetuo porque permanece para siempre.

[[hebrews-7-25]]
^25^ De ahí que pueda también salvar perfectamente a los que por él se llegan a Dios, ya que está siempre vivo para interceder en su favor.

[[hebrews-7-26]]
^26^ Así es el Sumo Sacerdote que nos convenía: santo, inocente, incontaminado, apartado de los pecadores, encumbrado por encima de los cielos,

[[hebrews-7-27]]
^27^ que no tiene necesidad de ofrecer sacrificios cada día, primero por sus pecados propios como aquellos Sumos Sacerdotes, luego por los del pueblo: y esto lo realizó de una vez para siempre, ofreciéndose a sí mismo.

[[hebrews-7-28]]
^28^ Es que la Ley instituye Sumos Sacerdotes a hombres frágiles: pero la palabra del juramento, posterior a la Ley, hace el Hijo perfecto para siempre.
[[hebrews-8]]
== Capítulo 8

[[hebrews-8-1]]
^1^ Este es el punto capital de cuanto venimos diciendo, que tenemos un Sumo Sacerdote tal, que se sentó a la diestra del trono de la Majestad en los cielos,

[[hebrews-8-2]]
^2^ al servicio del santuario y de la Tienda verdadera, erigida por el Señor, no por un hombre.

[[hebrews-8-3]]
^3^ Porque todo Sumo Sacerdote está instituido para ofrecer dones y sacrificios: de ahí que necesariamente también él tuviera que ofrecer algo.

[[hebrews-8-4]]
^4^ Pues si estuviera en la tierra, ni siquiera sería sacerdote, habiendo ya quienes ofrezcan dones según la Ley.

[[hebrews-8-5]]
^5^ Estos dan culto en lo que es sombra y figura de realidades celestiales, según le fue revelado a Moisés al emprender la construcción de la Tienda. Pues dice: Mira, harás todo conforme al modelo que te ha sido mostrado en el monte.

[[hebrews-8-6]]
^6^ Mas ahora ha obtenido él un ministerio tanto mejor cuanto es Mediador de una mejor Alianza, como fundada en promesas mejores.

[[hebrews-8-7]]
^7^ Pues si aquella primera fuera irreprochable, no habría lugar para una segunda.

[[hebrews-8-8]]
^8^ Porque les dice en tono de reproche: He aquí que días vienen, dice el Señor, y concertaré con la casa de Israel y con la casa de Judá una nueva Alianza,

[[hebrews-8-9]]
^9^ no como la Alianza que hice con sus padres el día en que los tomé de la mano para sacarlos de la tierra de Egipto. Como ellos no permanecieron fieles a mi Alianza, también yo me desentendí de ellos, dice el Señor.

[[hebrews-8-10]]
^10^ Esta es la Alianza que pactaré con la casa de Israel después de aquellos días, dice el Señor: Pondré mis leyes en su mente, en sus corazones las grabaré; y yo seré su Dios y ellos serán mi pueblo.

[[hebrews-8-11]]
^11^ Y no habrá de instruir cada cual a su conciudadano ni cada uno a su hermano diciendo: «¡Conoce al Señor!», pues todos me conocerán, desde el menor hasta el mayor de ellos.

[[hebrews-8-12]]
^12^ Porque me apiadaré de sus iniquidades y de sus pecados no me acordaré ya.

[[hebrews-8-13]]
^13^ Al decir nueva, declaró anticuada la primera; y lo anticuado y viejo está a punto de cesar.
[[hebrews-9]]
== Capítulo 9

[[hebrews-9-1]]
^1^ También la primera Alianza tenía sus ritos litúrgicos y su santuario terreno.

[[hebrews-9-2]]
^2^ Porque se preparó la parte anterior de la Tienda, donde se hallaban el candelabro y la mesa con los panes de la presencia, que se llama Santo.

[[hebrews-9-3]]
^3^ Detrás del segundo velo se hallaba la parte de la Tienda llamada Santo de los Santos,

[[hebrews-9-4]]
^4^ que contenía el altar de oro para el incienso, el arca de la Alianza - completamente cubierta de oro - y en ella, la urna de oro con el maná, la vara de Aarón que retoño y las tablas de la Alianza.

[[hebrews-9-5]]
^5^ Encima del arca, los querubines de gloria que cubrían con su sombra el propiciatorio. Mas no es éste el momento de hablar de todo ello en detalle.

[[hebrews-9-6]]
^6^ Preparadas así estas cosas, los sacerdotes entran siempre en la primera parte de la Tienda para desempeñar las funciones del culto.

[[hebrews-9-7]]
^7^ Pero en la segunda parte entra una vez al año, y solo, el Sumo Sacerdote, y no sin sangre que ofrecer por sí mismo y por los pecados del pueblo.

[[hebrews-9-8]]
^8^ De esa manera daba a entender el Espíritu Santo que aún no estaba abierto el camino del santuario mientras subsistiera la primera Tienda.

[[hebrews-9-9]]
^9^ Todo ello es una figura del tiempo presente, en cuanto que allí se ofrecen dones y sacrificios incapaces de perfeccionar en su conciencia al adorador,

[[hebrews-9-10]]
^10^ y sólo son prescripciones carnales, que versan sobre comidas y bebidas y sobre abluciones de todo género, impuestas hasta el tiempo de la reforma.

[[hebrews-9-11]]
^11^ Pero presentóse Cristo como Sumo Sacerdote de los bienes futuros, a través de una Tienda mayor y más perfecta, no fabricada por mano de hombre, es decir, no de este mundo.

[[hebrews-9-12]]
^12^ Y penetró en el santuario una vez para siempre, no con sangre de machos cabríos ni de novillos, sino con su propia sangre, consiguiendo una redención eterna.

[[hebrews-9-13]]
^13^ Pues si la sangre de machos cabríos y de toros y la ceniza de vaca santifica con su aspersión a los contaminados, en orden a la purificación de la carne,

[[hebrews-9-14]]
^14^ ¡cuánto más la sangre de Cristo, que por el Espíritu Eterno se ofreció a sí mismo sin tacha a Dios, purificará de las obras muertas nuestra conciencia para rendir culto a Dios vivo!

[[hebrews-9-15]]
^15^ Por eso es mediador de una nueva Alianza; para que, interviniendo su muerte para remisión de las transgresiones de la primera Alianza, los que han sido llamados reciban la herencia eterna prometida.

[[hebrews-9-16]]
^16^ Pues donde hay testamento se requiere que conste la muerte del testador,

[[hebrews-9-17]]
^17^ ya que el testamento es válido en caso de defunción, no teniendo valor en vida del testador.

[[hebrews-9-18]]
^18^ Así tampoco la primera Alianza se inauguró sin sangre.

[[hebrews-9-19]]
^19^ Pues Moisés, después de haber leído a todo el pueblo todos los preceptos según la Ley, tomó la sangre de los novillos y machos cabríos con agua, lana escarlata e hisopo, y roció el libro mismo y a todo el pueblo

[[hebrews-9-20]]
^20^ diciendo: Esta es la sangre de la Alianza que Dios ha ordenado para vosotros.

[[hebrews-9-21]]
^21^ Igualmente roció con sangre la Tienda y todos los objetos del culto;

[[hebrews-9-22]]
^22^ pues según la Ley, casi todas las cosas han de ser purificadas con sangre, y sin efusión de sangre no hay remisión.

[[hebrews-9-23]]
^23^ En consecuencia, es necesario, por una parte, que las figuras de las realidades celestiales sean purificadas de esa manera; por otra parte, que también lo sean las realidades celestiales, pero con víctimas más excelentes que aquéllas.

[[hebrews-9-24]]
^24^ Pues no penetró Cristo en un santuario hecho por mano de hombre, en una reproducción del verdadero, sino en el mismo cielo, para presentarse ahora ante el acatamiento de Dios en favor nuestro,

[[hebrews-9-25]]
^25^ y no para ofrecerse a sí mismo repetidas veces al modo como el Sumo Sacerdote entra cada año en el santuario con sangre ajena.

[[hebrews-9-26]]
^26^ Para ello habría tenido que sufrir muchas veces desde la creación del mundo. Sino que se ha manifestado ahora una sola vez, en la plenitud de los tiempos, para la destrucción del pecado mediante su sacrificio.

[[hebrews-9-27]]
^27^ Y del mismo modo que está establecido que los hombres mueran una sola vez, y luego el juicio,

[[hebrews-9-28]]
^28^ así también Cristo, después de haberse ofrecido una sola vez para quitar los pecados de la multitud, se aparecerá por segunda vez sin relación ya con el pecado a los que le esperan para su salvación.
[[hebrews-10]]
== Capítulo 10

[[hebrews-10-1]]
^1^ No conteniendo, en efecto, la Ley más que una sombra de los bienes futuros, no la realidad de las cosas, no puede nunca, mediante unos mismos sacrificios que se ofrecen sin cesar año tras año, dar la perfección a los que se acercan.

[[hebrews-10-2]]
^2^ De otro modo, ¿no habrían cesado de ofrecerlos, al no tener ya conciencia de pecado los que ofrecen ese culto, una vez purificados?

[[hebrews-10-3]]
^3^ Al contrario, con ellos se renueva cada año el recuerdo de los pecados,

[[hebrews-10-4]]
^4^ pues es imposible que sangre de toros y machos cabríos borre pecados.

[[hebrews-10-5]]
^5^ Por eso, al entrar en este mundo, dice: Sacrificio y oblación no quisiste; pero me has formado un cuerpo.

[[hebrews-10-6]]
^6^ Holocaustos y sacrificios por el pecado no te agradaron.

[[hebrews-10-7]]
^7^ Entonces dije: ¡He aquí que vengo - pues de mí está escrito en el rollo del libro - a hacer, oh Dios, tu voluntad!

[[hebrews-10-8]]
^8^ Dice primero: Sacrificios y oblaciones y holocaustos y sacrificios por el pecado no los quisiste ni te agradaron - cosas todas ofrecidas conforme a la Ley -

[[hebrews-10-9]]
^9^ entonces - añade -: He aquí que vengo a hacer tu voluntad. Abroga lo primero para establecer el segundo.

[[hebrews-10-10]]
^10^ Y en virtud de esta voluntad somos santificados, merced a la oblación de una vez para siempre del cuerpo de Jesucristo.

[[hebrews-10-11]]
^11^ Y, ciertamente, todo sacerdote está en pie, día tras día, oficiando y ofreciendo reiteradamente los mismos sacrificios, que nunca pueden borrar pecados.

[[hebrews-10-12]]
^12^ El, por el contrario, habiendo ofrecido por los pecados un solo sacrificio, se sentó a la diestra de Dios para siempre,

[[hebrews-10-13]]
^13^ esperando desde entonces hasta que sus enemigos sean puestos por escabel de sus pies.

[[hebrews-10-14]]
^14^ En efecto, mediante una sola oblación ha llevado a la perfección para siempre a los santificados.

[[hebrews-10-15]]
^15^ También el Espíritu Santo nos da testimonio de ello. Porque, después de haber dicho:

[[hebrews-10-16]]
^16^ Esta es la Alianza que pactaré con ellos después de aquellos días, dice el Señor: Pondré mis leyes en sus corazones, y en su mente las grabaré,

[[hebrews-10-17]]
^17^ añade: Y de sus pecados e iniquidades no me acordaré ya.

[[hebrews-10-18]]
^18^ Ahora bien, donde hay remisión de estas cosas, ya no hay más oblación por el pecado.

[[hebrews-10-19]]
^19^ Teniendo, pues, hermanos, plena seguridad para entrar en el santuario en virtud de la sangre de Jesús,

[[hebrews-10-20]]
^20^ por este camino nuevo y vivo, inaugurado por él para nosotros, a través del velo, es decir, de su propia carne,

[[hebrews-10-21]]
^21^ y con un Sumo Sacerdote al frente de la casa de Dios,

[[hebrews-10-22]]
^22^ acerquémonos con sincero corazón , en plenitud de fe, purificados los corazones de conciencia mala y lavados los cuerpos con agua pura.

[[hebrews-10-23]]
^23^ Mantengamos firme la confesión de la esperanza, pues fiel es el autor de la Promesa.

[[hebrews-10-24]]
^24^ Fijémonos los unos en los otros para estímulo de la caridad y las buenas obras,

[[hebrews-10-25]]
^25^ sin abandonar vuestra propia asamblea, como algunos acostumbran hacerlo, antes bien, animándoos: tanto más, cuanto que veis que se acerca ya el Día.

[[hebrews-10-26]]
^26^ Porque si voluntariamente pecamos después de haber recibido el pleno conocimiento de la verdad, ya no queda sacrificio por los pecados,

[[hebrews-10-27]]
^27^ sino la terrible espera del juicio y la furia del fuego pronto a devorar a los rebeldes.

[[hebrews-10-28]]
^28^ Si alguno viola la Ley de Moisés es condenado a muerte sin compasión, por la declaración de dos o tres testigos.

[[hebrews-10-29]]
^29^ ¿Cuánto más grave castigo pensáis que merecerá el que pisoteó al Hijo de Dios, y tuvo como profana la sangre de la Alianza que le santificó, y ultrajó al Espíritu de la gracia?

[[hebrews-10-30]]
^30^ Pues conocemos al que dijo: Mía es la venganza; yo daré lo merecido. Y también: El Señor juzgará a su pueblo.

[[hebrews-10-31]]
^31^ ¡Es tremendo caer en la manos de Dios vivo!

[[hebrews-10-32]]
^32^ Traed a la memoria los días pasados, en que después de ser iluminados, hubisteis de soportar un duro y doloroso combate,

[[hebrews-10-33]]
^33^ unas veces expuestos públicamente a ultrajes y tribulaciones; otras, haciéndoos solidarios de los que así eran tratados.

[[hebrews-10-34]]
^34^ Pues compartisteis los sufrimientos de los encarcelados; y os dejasteis despojar con alegría de vuestros bienes, conscientes de que poseíais una riqueza mejor y más duradera.

[[hebrews-10-35]]
^35^ No perdáis ahora vuestra confianza, que lleva consigo una gran recompensa.

[[hebrews-10-36]]
^36^ Necesitáis paciencia en el sufrimiento para cumplir la voluntad de Dios y conseguir así lo prometido.

[[hebrews-10-37]]
^37^ Pues todavía un poco, muy poco tiempo; y el que ha de venir vendrá sin tardanza.

[[hebrews-10-38]]
^38^ Mi justo vivirá por la fe; mas si es cobarde, mi alma no se complacerá en él.

[[hebrews-10-39]]
^39^ Pero nosotros no somos cobardes para perdición, sino creyentes para salvación del alma.
[[hebrews-11]]
== Capítulo 11

[[hebrews-11-1]]
^1^ La fe es garantía de lo que se espera; la prueba de las realidades que no se ven.

[[hebrews-11-2]]
^2^ Por ella fueron alabados nuestros mayores.

[[hebrews-11-3]]
^3^ Por la fe, sabemos que el universo fue formado por la palabra de Dios, de manera que lo que se ve resultase de lo que no aparece.

[[hebrews-11-4]]
^4^ Por la fe, ofreció Abel a Dios un sacrificio más excelente que Caín, por ella fue declarado justo, con la aprobación que dio Dios a sus ofrendas; y por ella, aun muerto, habla todavía.

[[hebrews-11-5]]
^5^ Por la fe, Henoc fue trasladado, de modo que no vio la muerte y no se le halló, porque le trasladó Dios. Porque antes de contar su traslado, la Escritura da en su favor testimonio de haber agradado a Dios.

[[hebrews-11-6]]
^6^ Ahora bien, sin fe es imposible agradarle, pues el que se acerca a Dios ha de creer que existe y que recompensa a los que le buscan.

[[hebrews-11-7]]
^7^ Por la fe, Noé, advertido por Dios de lo que aún no se veía, con religioso temor construyó un arca para salvar a su familia; por la fe, condenó al mundo y llegó a ser heredero de la justicia según la fe.

[[hebrews-11-8]]
^8^ Por la fe, Abraham, al ser llamado por Dios, obedeció y salió para el lugar que había de recibir en herencia, y salió sin saber a dónde iba.

[[hebrews-11-9]]
^9^ Por la fe, peregrinó por la Tierra Prometida como en tierra extraña, habitando en tiendas, lo mismo que Isaac y Jacob, coherederos de las mismas promesas.

[[hebrews-11-10]]
^10^ Pues esperaba la ciudad asentada sobre cimientos, cuyo arquitecto y constructor es Dios.

[[hebrews-11-11]]
^11^ Por la fe, también Sara recibió, aun fuera de la edad apropiada, vigor para ser madre, pues tuvo como digno de fe al que se lo prometía.

[[hebrews-11-12]]
^12^ Por lo cual también de uno solo y ya gastado nacieron hijos, numerosos como las estrellas del cielo, incontables como las arenas de las orillas del mar.

[[hebrews-11-13]]
^13^ En la fe murieron todos ellos, sin haber conseguido el objeto de las promesas: viéndolas y saludándolas desde lejos y confesándose extraños y forasteros sobre la tierra.

[[hebrews-11-14]]
^14^ Los que tal dicen, claramente dan a entender que van en busca de una patria;

[[hebrews-11-15]]
^15^ pues si hubiesen pensado en la tierra de la que habían salido, habrían tenido ocasión de retornar a ella.

[[hebrews-11-16]]
^16^ Más bien aspiran a una mejor, a la celestial. Por eso Dios no se avergüenza de ellos, de ser llamado Dios suyo, pues les tiene preparada una ciudad...

[[hebrews-11-17]]
^17^ Por la fe, Abraham, sometido a la prueba, presentó a Isaac como ofrenda, y el que había recibido las promesas, ofrecía a su unigénito,

[[hebrews-11-18]]
^18^ respecto del cual se le había dicho: Por Isaac tendrás descendencia.

[[hebrews-11-19]]
^19^ Pensaba que poderoso era Dios aun para resucitar de entre los muertos. Por eso lo recobró para que Isaac fuera también figura.

[[hebrews-11-20]]
^20^ Por la fe, bendijo Isaac a Jacob y Esaú en orden al futuro.

[[hebrews-11-21]]
^21^ Por la fe, Jacob, moribundo, bendijo a cada uno de los hijos de José, y se inclinó apoyado en la cabeza de su bastón.

[[hebrews-11-22]]
^22^ Por la fe, José, moribundo, evocó el éxodo de los hijos de Israel, y dio órdenes respecto de sus huesos.

[[hebrews-11-23]]
^23^ Por la fe, Moisés, recién nacido, fue durante tres meses ocultado por sus padres, pues vieron que el niño era hermoso y no temieron el edicto del rey.

[[hebrews-11-24]]
^24^ Por la fe, Moisés, ya adulto, rehusó ser llamado hijo de una hija de Faraón,

[[hebrews-11-25]]
^25^ prefiriendo ser maltratado con el pueblo de Dios a disfrutar el efímero goce del pecado,

[[hebrews-11-26]]
^26^ estimando como riqueza mayor que los tesoros de Egipto el oprobio de Cristo, porque tenía los ojos puestos en la recompensa.

[[hebrews-11-27]]
^27^ Por la fe, salió de Egipto sin temer la ira del rey; se mantuvo firme como si viera al invisible.

[[hebrews-11-28]]
^28^ Por la fe, celebró la Pascua e hizo la aspersión de sangre para que el Exterminador no tocase a los primogénitos de Israel.

[[hebrews-11-29]]
^29^ Por la fe, atravesaron el mar Rojo como por una tierra seca; mientras que los egipcios intentando lo mismo, fueron tragados.

[[hebrews-11-30]]
^30^ Por la fe, se derrumbaron los muros de Jericó, después de ser rodeados durante siete días.

[[hebrews-11-31]]
^31^ Por la fe, la ramera Rajab no pereció con los incrédulos, por haber acogido amistosamente a los exploradores.

[[hebrews-11-32]]
^32^ Y ¿a qué continuar? Pues me faltaría el tiempo si hubiera de hablar sobre Gedeón, Barac, Sansón, Jefté, David, Samuel y los profetas.

[[hebrews-11-33]]
^33^ Estos, por la fe, sometieron reinos, hicieron justicia, alcanzaron las promesas, cerraron la boca a los leones;

[[hebrews-11-34]]
^34^ apagaron la violencia del fuego, escaparon del filo de la espada, curaron de sus infermedades, fueron valientes en la guerra, rechazando ejércitos extranjeros;

[[hebrews-11-35]]
^35^ las mujeres recobraban resucitados a sus muertos. Unos fueron torturados, rehusando la liberación por conseguir una resurrección mejor;

[[hebrews-11-36]]
^36^ otros soportaron burlas y azotes, y hasta cadenas y prisiones;

[[hebrews-11-37]]
^37^ apedreados, torturados, aserrados, muertos a espada; anduvieron errantes cubiertos de pieles de oveja y de cabras; faltos de todo; oprimidos y maltratados,

[[hebrews-11-38]]
^38^ ¡hombres de los que no era digno el mundo!, errantes por desiertos y montañas, por cavernas y antros de la tierra.

[[hebrews-11-39]]
^39^ Y todos ellos, aunque alabados por su fe, no consiguieron el objeto de las promesas.

[[hebrews-11-40]]
^40^ Dios tenía ya dispuesto algo mejor para nosotros, de modo que no llegaran ellos sin nosotros a la perfección.
[[hebrews-12]]
== Capítulo 12

[[hebrews-12-1]]
^1^ Por tanto, también nosotros, teniendo en torno nuestro tan gran nube de testigos, sacudamos todo lastre y el pecado que nos asedia, y corramos con fortaleza la prueba que se nos propone,

[[hebrews-12-2]]
^2^ fijos los ojos en Jesús, el que inicia y consuma la fe, el cual, en lugar del gozo que se le proponía, soportó la cruz sin miedo a la ignominia y está sentado a la diestra del trono de Dios.

[[hebrews-12-3]]
^3^ Fijaos en aquel que soportó tal contradicción de parte de los pecadores, para que no desfallezcáis faltos de ánimo.

[[hebrews-12-4]]
^4^ No habéis resistido todavía hasta llegar a la sangre en vuestra lucha contra el pecado.

[[hebrews-12-5]]
^5^ Habéis echado en olvido la exhortación que como a hijos se os dirije: Hijo mío, no menosprecies la corrección del Señor; ni te desanimes al ser reprendido por él.

[[hebrews-12-6]]
^6^ Pues a quien ama el Señor, le corrige; y azota a todos los hijos que acoge.

[[hebrews-12-7]]
^7^ Sufrís para corrección vuestra. Como a hijos os trata Dios, y ¿qué hijo hay a quien su padre no corrige?

[[hebrews-12-8]]
^8^ Mas si quedáis sin corrección, cosa que todos reciben, señal de que sois bastardos y no hijos.

[[hebrews-12-9]]
^9^ Además, teníamos a nuestros padres según la carne, que nos corregían, y les respetábamos. ¿No nos someteremos mejor al Padre de los espíritus para vivir?

[[hebrews-12-10]]
^10^ ¡Eso que ellos nos corregían según sus luces y para poco tiempo!; mas él, para provecho nuestro, en orden a hacernos partícipes de su santidad.

[[hebrews-12-11]]
^11^ Cierto que ninguna corrección es de momento agradable, sino penosa; pero luego produce fruto apacible de justicia a los ejercitados en ella.

[[hebrews-12-12]]
^12^ Por tanto, levantad las manos caídas y las rodillas entumecidas

[[hebrews-12-13]]
^13^ y enderezad para vuestros pies los caminos tortuosos, para que el cojo no se descoyunte, sino que más bien se cure.

[[hebrews-12-14]]
^14^ Procurad la paz con todos y la santidad, sin la cual nadie verá al Señor.

[[hebrews-12-15]]
^15^ Poned cuidado en que nadie se vea privado de la gracia de Dios; en que ninguna raíz amarga retoñe ni os turbe y por ella llegue a inficionarse la comunidad.

[[hebrews-12-16]]
^16^ Que no haya ningún fornicario o impío como Esaú, que por una comida vendió su primogenitura.

[[hebrews-12-17]]
^17^ Ya sabéis cómo luego quiso heredar la bendición; pero fue rechazado y no logró un cambio de parecer, aunque lo procuró con lágrimas.

[[hebrews-12-18]]
^18^ No os habéis acercado a una realidad sensible: fuego ardiente, oscuridad, tinieblas, huracán,

[[hebrews-12-19]]
^19^ sonido de trompeta y a un ruido de palabras tal, que suplicaron los que lo oyeron no se les hablara más.

[[hebrews-12-20]]
^20^ Es que no podían soportar esta orden: El que toque el monte, aunque sea un animal, será lapidado.

[[hebrews-12-21]]
^21^ Tan terrible era el espectáculo, que el mismo Moisés dijo: Espantado estoy y temblando.

[[hebrews-12-22]]
^22^ Vosotros, en cambio, os habéis acercado al monte Sión, a la ciudad de Dios vivo, la Jerusalén celestial, y a miríadas de ángeles, reunión solemne

[[hebrews-12-23]]
^23^ y asamblea de los primogénitos inscritos en los cielos, y a Dios, juez universal, y a los espíritus de los justos llegados ya a su consumación,

[[hebrews-12-24]]
^24^ y a Jesús, mediador de una nueva Alianza, y a la aspersión purificadora de una sangre que habla mejor que la de Abel.

[[hebrews-12-25]]
^25^ Guardaos de rechazar al que os habla; pues si los que rechazaron al que promulgaba los oráculos desde la tierra no escaparon al castigo, mucho menos nosotros, si volvemos la espalda al que nos habla desde el cielo.

[[hebrews-12-26]]
^26^ Su voz conmovió entonces la tierra. Mas ahora hace esta promesa: Una vez más haré yo que se estremezca no sólo la tierra, sino también el cielo.

[[hebrews-12-27]]
^27^ Estas palabras, una vez más, quieren decir que las cosas conmovidas se cambiarán, ya que son realidades creadas, a fin de que permanezcan las inconmovibles.

[[hebrews-12-28]]
^28^ Por eso, nosotros que recibimos un reino inconmovible, hemos de mantener la gracia y, mediante ella, ofrecer a Dios un culto que le sea grato, con religiosa piedad y reverencia,

[[hebrews-12-29]]
^29^ pues nuestro Dios es fuego devorador.
[[hebrews-13]]
== Capítulo 13

[[hebrews-13-1]]
^1^ Permaneced en el amor fraterno.

[[hebrews-13-2]]
^2^ No os olvidéis de la hospitalidad; gracias a ella hospedaron algunos, sin saberlo, a ángeles.

[[hebrews-13-3]]
^3^ Acordaos de los presos, como si estuvierais con ellos encarcelados, y de los maltratados, pensando que también vosotros tenéis un cuerpo.

[[hebrews-13-4]]
^4^ Tened todos en gran honor el matrimonio, y el lecho conyugal sea inmaculado; que a los fornicarios y adúlteros los juzgará Dios.

[[hebrews-13-5]]
^5^ Sea vuestra conducta sin avaricia; contentos con lo que tenéis, pues él ha dicho: No te dejaré ni te abandonaré;

[[hebrews-13-6]]
^6^ de modo que podamos decir confiados: El Señor es mi ayuda; no temeré. ¿Qué puede hacerme el hombre?

[[hebrews-13-7]]
^7^ Acordaos de vuestros dirigentes, que os anunciaron la Palabra de Dios y, considerando el final de su vida, imitad su fe.

[[hebrews-13-8]]
^8^ Ayer como hoy, Jesucristo es el mismo, y lo será siempre.

[[hebrews-13-9]]
^9^ No os dejéis seducir por doctrinas varias y extrañas. Mejor es fortalecer el corazón con la gracia que con alimentos que nada aprovecharon a los que siguieron ese camino.

[[hebrews-13-10]]
^10^ Tenemos nosotros un altar del cual no tienen derecho a comer los que dan culto en la Tienda.

[[hebrews-13-11]]
^11^ Los cuerpos de los animales, cuya sangre lleva el Sumo Sacerdote al santuario para la expiación del pecado, son quemados fuera del campamento.

[[hebrews-13-12]]
^12^ Por eso, también Jesús, para santificar al pueblo con su sangre, padeció fuera de la puerta.

[[hebrews-13-13]]
^13^ Así pues, salgamos donde él fuera del campamento, cargando con su oprobio;

[[hebrews-13-14]]
^14^ que no tenemos aquí ciudad permanente, sino que andamos buscando la del futuro.

[[hebrews-13-15]]
^15^ Ofrezcamos sin cesar, por medio de él, a Dios un sacrificio de alabanza, es decir, el fruto de los labios que celebran su nombre.

[[hebrews-13-16]]
^16^ No os olvidéis de hacer el bien y de ayudaros mutuamente; ésos son los sacrificios que agradan a Dios.

[[hebrews-13-17]]
^17^ Obedeced a vuestros dirigentes y someteos a ellos, pues velan sobre vuestras almas como quienes han de dar cuenta de ellas, para que lo hagan con alegría y no lamentándose, cosa que no os traería ventaja alguna.

[[hebrews-13-18]]
^18^ Rogad por nosotros, pues estamos seguros de tener recta conciencia, deseosos de proceder en todo con rectitud.

[[hebrews-13-19]]
^19^ Con la mayor insistencia os pido que lo hagáis, para que muy pronto os sea yo devuelto.

[[hebrews-13-20]]
^20^ Y el Dios de la paz que suscitó de entre los muertos a nuestro Señor Jesús, el gran Pastor de la ovejas en virtud de la sangre de una Alianza eterna,

[[hebrews-13-21]]
^21^ os disponga con toda clase de bienes para cumplir su voluntad, realizando él en nosotros lo que es agradable a sus ojos, por mediación de Jesucristo, a quien sea la gloria por los siglos de los siglos. Amén.

[[hebrews-13-22]]
^22^ Os ruego, hermanos, que aceptéis estas palabras de exhortación, pues os he escrito brevemente.

[[hebrews-13-23]]
^23^ Sabed que nuestro hermano Timoteo ha sido liberado. Si viene pronto, iré con él a veros.

[[hebrews-13-24]]
^24^ Saludad a todos vuestros dirigentes y a todos los santos. Os saludan los de Italia.

[[hebrews-13-25]]
^25^ La gracia sea con vosotros.
