[[james]]
= Santiago

[[james-1]]
== Capítulo 1

[[james-1-1]]
^1^ Santiago, siervo de Dios y del Señor Jesucristo, saluda a las doce tribus de la Dispersión.

[[james-1-2]]
^2^ Considerad como un gran gozo, hermanos míos, el estar rodeados por toda clase de pruebas,

[[james-1-3]]
^3^ sabiendo que la calidad probada de vuestra fe produce la paciencia en el sufrimiento;

[[james-1-4]]
^4^ pero la paciencia ha de ir acompañada de obras perfectas para que seáis perfectos e íntegros sin que dejéis nada que desear.

[[james-1-5]]
^5^ Si alguno de vosotros está a falta de sabiduría, que la pida a Dios, que da a todos generosamente y sin echarlo en cara, y se la dará.

[[james-1-6]]
^6^ Pero que la pida con fe, sin vacilar; porque el que vacila es semejante al oleaje del mar, movido por el viento y llevado de una a otra parte.

[[james-1-7]]
^7^ Que no piense recibir cosa alguna del Señor un hombre como éste,

[[james-1-8]]
^8^ un hombre irresoluto e inconstante en todos sus caminos.

[[james-1-9]]
^9^ El hermano de condición humilde gloríese en su exaltación;

[[james-1-10]]
^10^ y el rico, en su humillación, porque pasará como flor de hierba:

[[james-1-11]]
^11^ sale el sol con fuerza y seca la hierba y su flor cae y se pierde su hermosa apariencia; así también el rico se marchitará en sus caminos.

[[james-1-12]]
^12^ ¡Feliz el hombre que soporta la prueba! Superada la prueba, recibirá la corona de la vida que ha prometido el Señor a los que le aman.

[[james-1-13]]
^13^ Ninguno, cuando sea probado, diga: «Es Dios quien me prueba»; porque Dios ni es probado por el mal ni prueba a nadie.

[[james-1-14]]
^14^ Sino que cada uno es probado por su propia concupiscencia que le arrastra y le seduce.

[[james-1-15]]
^15^ Después la concupiscencia, cuando ha concebido, da a luz el pecado; y el pecado, una vez consumado, engendra la muerte.

[[james-1-16]]
^16^ No os engañéis, hermanos míos queridos:

[[james-1-17]]
^17^ toda dádiva buena y todo don perfecto viene de lo alto, desciende del Padre de las luces, en quien no hay cambio ni sombra de rotación.

[[james-1-18]]
^18^ Nos engendró por su propia voluntad, con Palabra de verdad, para que fuésemos como las primicias de sus criaturas.

[[james-1-19]]
^19^ Tenedlo presente, hermanos míos queridos: Que cada uno sea diligente para escuchar y tardo para hablar, tardo para la ira.

[[james-1-20]]
^20^ Porque la ira del hombre no obra la justicia de Dios.

[[james-1-21]]
^21^ Por eso, desechad toda inmundicia y abundancia de mal y recibid con docilidad la Palabra sembrada en vosotros, que es capaz de salvar vuestras almas.

[[james-1-22]]
^22^ Poned por obra la Palabra y no os contentéis sólo con oírla, engañándoos a vosotros mismos.

[[james-1-23]]
^23^ Porque si alguno se contenta con oír la Palabra sin ponerla por obra, ése se parece al que contempla su imagen en un espejo:

[[james-1-24]]
^24^ se contempla, pero, en yéndose, se olvida de cómo es.

[[james-1-25]]
^25^ En cambio el que considera atentamente la Ley perfecta de la libertad y se mantiene firme, no como oyente olvidadizo sino como cumplidor de ella, ése, practicándola, será feliz.

[[james-1-26]]
^26^ Si alguno se cree religioso, pero no pone freno a su lengua, sino que engaña a su propio corazón, su religión es vana.

[[james-1-27]]
^27^ La religión pura e intachable ante Dios Padre es ésta: visitar a los huérfanos y a las viudas en su tribulación y conservarse incontaminado del mundo.
[[james-2]]
== Capítulo 2

[[james-2-1]]
^1^ Hermanos míos, no entre la acepción de personas en la fe que tenéis en nuestro Señor Jesucristo glorificado.

[[james-2-2]]
^2^ Supongamos que entra en vuestra asamblea un hombre con un anillo de oro y un vestido espléndido; y entra también un pobre con un vestido sucio;

[[james-2-3]]
^3^ y que dirigís vuestra mirada al que lleva el vestido espléndido y le decís: «Tú, siéntate aquí, en un buen lugar»; y en cambio al pobre le decís: «Tú, quédate ahí de pie», o «Siéntate a mis pies».

[[james-2-4]]
^4^ ¿No sería esto hacer distinciones entre vosotros y ser jueces con criterios malos?

[[james-2-5]]
^5^ Escuchad, hermanos míos queridos: ¿Acaso no ha escogido Dios a los pobres según el mundo como ricos en la fe y herederos del Reino que prometió a los que le aman?

[[james-2-6]]
^6^ ¡En cambio vosotros habéis menospreciado al pobre! ¿No son acaso los ricos los que os oprimen y os arrastran a los tribunales?

[[james-2-7]]
^7^ ¿No son ellos los que blasfeman el hermoso Nombre que ha sido invocado sobre vosotros?

[[james-2-8]]
^8^ Si cumplís plenamente la Ley regia según la Escritura: Amarás a tu prójimo como a ti mismo, obráis bien;

[[james-2-9]]
^9^ pero si tenéis acepción de personas, cometéis pecado y quedáis convictos de transgresión por la Ley.

[[james-2-10]]
^10^ Porque quien observa toda la Ley, pero falta en un solo precepto, se hace reo de todos.

[[james-2-11]]
^11^ Pues el que dijo: No adulteres, dijo también: No mates. Si no adulteras, pero matas, eres transgresor de la Ley.

[[james-2-12]]
^12^ Hablad y obrad tal como corresponde a los que han de ser juzgados por la Ley de la libertad.

[[james-2-13]]
^13^ Porque tendrá un juicio sin misericordia el que no tuvo misericordia; pero la misericordia se siente superior al juicio.

[[james-2-14]]
^14^ ¿De qué sirve, hermanos míos, que alguien diga: «Tengo fe», si no tiene obras? ¿Acaso podrá salvarle la fe?

[[james-2-15]]
^15^ Si un hermano o una hermana están desnudos y carecen del sustento diario,

[[james-2-16]]
^16^ y alguno de vosotros les dice: «Idos en paz, calentaos y hartaos», pero no les dais lo necesario para el cuerpo, ¿de qué sirve?

[[james-2-17]]
^17^ Así también la fe, si no tiene obras, está realmente muerta.

[[james-2-18]]
^18^ Y al contrario, alguno podrá decir: «¿Tú tienes fe?; pues yo tengo obras. Pruébame tu fe sin obras y yo te probaré por las obras mi fe.

[[james-2-19]]
^19^ ¿Tú crees que hay un solo Dios? Haces bien. También los demonios lo creen y tiemblan.

[[james-2-20]]
^20^ ¿Quieres saber tú, insensato, que la fe sin obras es estéril?

[[james-2-21]]
^21^ Abraham nuestro padre ¿no alcanzó la justificación por las obras cuando ofreció a su hijo Isaac sobre el altar?

[[james-2-22]]
^22^ ¿Ves cómo la fe cooperaba con sus obras y, por las obras, la fe alcanzó su perfección?

[[james-2-23]]
^23^ Y alcanzó pleno cumplimiento la Escritura que dice: Creyó Abraham en Dios y le fue reputado como justicia y fue llamado amigo de Dios».

[[james-2-24]]
^24^ Ya veis cómo el hombre es justificado por las obras y no por la fe solamente.

[[james-2-25]]
^25^ Del mismo modo Rajab, la prostituta, ¿no quedó justificada por las obras dando hospedaje a los mensajeros y haciéndoles marchar por otro camino?

[[james-2-26]]
^26^ Porque así como el cuerpo sin espíritu está muerto, así también la fe sin obras está muerta.
[[james-3]]
== Capítulo 3

[[james-3-1]]
^1^ No os hagáis maestros muchos de vosotros, hermanos míos, sabiendo que nosotros tendremos un juicio más servero,

[[james-3-2]]
^2^ pues todos caemos muchas veces. Si alguno no cae hablando, es un hombre perfecto, capaz de poner freno a todo su cuerpo.

[[james-3-3]]
^3^ Si ponemos a los caballos frenos en la boca para que nos obedezcan, dirigimos así todo su cuerpo.

[[james-3-4]]
^4^ Mirad también las naves: aunque sean grandes y vientos impetuosos las empujen, son dirigidas por un pequeño timón adonde la voluntad del piloto quiere.

[[james-3-5]]
^5^ Así también la lengua es un miembro pequeño y puede gloriarse de grandes cosas. Mirad qué pequeño fuego abrasa un bosque tan grande.

[[james-3-6]]
^6^ Y la lengua es fuego, es un mundo de iniquidad; la lengua, que es uno de nuestros miembros, contamina todo el cuerpo y, encendida por la gehenna, prende fuego a la rueda de la vida desde sus comienzos.

[[james-3-7]]
^7^ Toda clase de fieras, aves, reptiles y animales marinos pueden ser domados y de hecho han sido domados por el hombre;

[[james-3-8]]
^8^ en cambio ningún hombre ha podido domar la lengua; es un mal turbulento; está llena de veneno mortífero.

[[james-3-9]]
^9^ Con ella bendecimos al Señor y Padre, y con ella maldecimos a los hombres, hechos a imagen de Dios;

[[james-3-10]]
^10^ de una misma boca proceden la bendición y la maldición. Esto, hermanos míos, no debe ser así.

[[james-3-11]]
^11^ ¿Acaso la fuente mana por el mismo caño agua dulce y amarga?

[[james-3-12]]
^12^ ¿Acaso, hermanos míos, puede la higuera producir aceitunas y la vid higos? Tampoco el agua salada puede producir agua dulce.

[[james-3-13]]
^13^ ¿Hay entre vosotros quien tenga sabiduría o experiencia? Que muestre por su buena conducta las obras hechas con la dulzura de la sabiduría.

[[james-3-14]]
^14^ Pero si tenéis en vuestro corazón amarga envidia y espíritu de contienda, no os jactéis ni mintáis contra la verdad.

[[james-3-15]]
^15^ Tal sabiduría no desciende de lo alto, sino que es terrena, natural, demoníaca.

[[james-3-16]]
^16^ Pues donde existen envidias y espíritu de contienda, allí hay desconcierto y toda clase de maldad.

[[james-3-17]]
^17^ En cambio la sabiduría que viene de lo alto es, en primer lugar, pura, además pacífica, complaciente, dócil, llena de compasión y buenos frutos, imparcial, sin hipocresía.

[[james-3-18]]
^18^ Frutos de justicia se siembran en la paz para los que procuran la paz.
[[james-4]]
== Capítulo 4

[[james-4-1]]
^1^ ¿De dónde proceden las guerras y las contiendas entre vosotros? ¿No es de vuestras pasiones que luchan en vuestros miembros?

[[james-4-2]]
^2^ ¿Codiciáis y no poseéis? Matáis. ¿Envidiáis y no podéis conseguir? Combatís y hacéis la guerra. No tenéis porque no pedís.

[[james-4-3]]
^3^ Pedís y no recibís porque pedís mal, con la intención de malgastarlo en vuestras pasiones.

[[james-4-4]]
^4^ ¡Adúlteros!, ¿no sabéis que la amistad con el mundo es enemistad con Dios? Cualquiera, pues, que desee ser amigo del mundo se constituye en enemigo de Dios.

[[james-4-5]]
^5^ ¿Pensáis que la Escritura dice en vano: Tiene deseos ardientes el espíritu que él ha hecho habitar en nosotros?

[[james-4-6]]
^6^ Más aún, da una gracia mayor; por eso dice: Dios resiste a los soberbios y da su gracia a los humildes.

[[james-4-7]]
^7^ Someteos, pues, a Dios; resistid al Diablo y él huirá de vosotros.

[[james-4-8]]
^8^ Acercaos a Dios y él se acercará a vosotros. Purificaos, pecadores, las manos; limpiad los corazones, hombres irresolutos.

[[james-4-9]]
^9^ Lamentad vuestra miseria, entristeceos y llorad. Que vuestra risa se cambie en llanto y vuestra alegría en tristeza.

[[james-4-10]]
^10^ Humillaos ante el Señor y él os ensalzará.

[[james-4-11]]
^11^ No habléis mal unos de otros, hermanos. El que habla mal de un hermano o juzga a su hermano, habla mal de la Ley y juzga a la Ley; y si juzgas a la Ley, ya no eres un cumplidor de la Ley, sino un juez.

[[james-4-12]]
^12^ Uno solo es el legislador y juez, que puede salvar o perder. En cambio tú, ¿quién eres para juzgar al prójimo?

[[james-4-13]]
^13^ Ahora bien, vosotros los que decís: «Hoy o mañana iremos a tal ciudad, pasaremos allí el año, negociaremos y ganaremos»;

[[james-4-14]]
^14^ vosotros que no sabéis qué será de vuestra vida el día de mañana... ¡Sois vapor que aparece un momento y después desaparece!

[[james-4-15]]
^15^ En lugar de decir: «Si el Señor quiere, viviremos y haremos esto o aquello».

[[james-4-16]]
^16^ Pero ahora os jactáis en vuestra fanfarronería. Toda jactancia de este tipo es mala.

[[james-4-17]]
^17^ Aquel, pues, que sabe hacer el bien y no lo hace, comete pecado.
[[james-5]]
== Capítulo 5

[[james-5-1]]
^1^ Ahora bien, vosotros, ricos, llorad y dad alaridos por las desgracias que están para caer sobre vosotros.

[[james-5-2]]
^2^ Vuestra riqueza está podrida y vuestros vestidos están apolillados;

[[james-5-3]]
^3^ vuestro oro y vuestra plata están tomados de herrumbre y su herrumbre será testimonio contra vosotros y devorará vuestras carnes como fuego. Habéis acumulado riquezas en estos días que son los últimos.

[[james-5-4]]
^4^ Mirad; el salario que no habéis pagado a los obreros que segaron vuestros campos está gritando; y los gritos de los segadores han llegado a los oídos del Señor de los ejércitos.

[[james-5-5]]
^5^ Habéis vivido sobre la tierra regaladamente y os habéis entregado a los placeres; habéis hartado vuestros corazones en el día de la matanza.

[[james-5-6]]
^6^ Condenasteis y matasteis al justo; él no os resiste.

[[james-5-7]]
^7^ Tened, pues, paciencia, hermanos, hasta la Venida del Señor. Mirad: el labrador espera el fruto precioso de la tierra aguardándolo con paciencia hasta recibir las lluvias tempranas y tardías.

[[james-5-8]]
^8^ Tened también vosotros paciencia; fortaleced vuestros corazones porque la Venida del Señor está cerca.

[[james-5-9]]
^9^ No os quejéis, hermanos, unos de otros para no ser juzgados; mirad que el Juez está ya a las puertas.

[[james-5-10]]
^10^ Tomad, hermanos, como modelo de sufrimiento y de paciencia a los profetas, que hablaron en nombre del Señor.

[[james-5-11]]
^11^ Mirad cómo proclamamos felices a los que sufrieron con paciencia. Habéis oído la paciencia de Job en el sufrimiento y sabéis el final que el Señor le dio; porque el Señor es compasivo y misericordioso.

[[james-5-12]]
^12^ Ante todo, hermanos, no juréis ni por el cielo ni por la tierra, ni por ningún otra cosa. Que vuestro sí sea sí, y el no, no; para no incurrir en juicio.

[[james-5-13]]
^13^ ¿Sufre alguno entre vosotros? Que ore. ¿Está alguno alegre? Que cante salmos.

[[james-5-14]]
^14^ ¿Está enfermo alguno entre vosotros? Llame a los presbíteros de la Iglesia, que oren sobre él y le unjan con óleo en el nombre del Señor.

[[james-5-15]]
^15^ Y la oración de la fe salvará al enfermo, y el Señor hará que se levante, y si hubiera cometido pecados, le serán perdonados.

[[james-5-16]]
^16^ Confesaos, pues, mutuamente vuestros pecados y orad los unos por los otros, para que seáis curados. La oración ferviente del justo tiene mucho poder.

[[james-5-17]]
^17^ Elías era un hombre de igual condición que nosotros; oró insistentemente para que no lloviese, y no llovió sobre la tierra durante tres años y seis meses.

[[james-5-18]]
^18^ Después oró de nuevo y el cielo dio lluvia y la tierra produjo su fruto.

[[james-5-19]]
^19^ Si alguno de vosotros, hermanos míos, se desvía de la verdad y otro le convierte,

[[james-5-20]]
^20^ sepa que el que convierte a un pecador de su camino desviado, salvará su alma de la muerte y cubrirá multitud de pecados.
