[[second-peter]]
= Segunda carta de San Pedro

[[second-peter-1]]
== Capítulo 1

[[second-peter-1-1]]
^1^ Simeón Pedro, siervo y apóstol de Jesucristo, a los que por la justicia de nuestro Dios y Salvador Jesucristo les ha cabido en suerte una fe tan preciosa como la nuestra.

[[second-peter-1-2]]
^2^ A vosotros, gracia y paz abundantes por el conocimiento de nuestro Señor.

[[second-peter-1-3]]
^3^ Pues su divino poder nos ha concedido cuanto se refiere a la vida y a la piedad, mediante el conocimiento perfecto del que nos ha llamado por su propia gloria y virtud,

[[second-peter-1-4]]
^4^ por medio de las cuales nos han sido concedidas las preciosas y sublimes promesas, para que por ellas os hicierais partícipes de la naturaleza divina, huyendo de la corrupción que hay en el mundo por la concupiscencia.

[[second-peter-1-5]]
^5^ Por esta misma razón, poned el mayor empeño en añadir a vuestra fe la virtud, a la virtud el conocimiento,

[[second-peter-1-6]]
^6^ al conocimiento la templanza, a la templanza la tenacidad, a la tenacidad la piedad,

[[second-peter-1-7]]
^7^ a la piedad el amor fraterno, al amor fraterno la caridad.

[[second-peter-1-8]]
^8^ Pues si tenéis estas cosas y las tenéis en abundancia, no os dejarán inactivos ni estériles para el conocimiento perfecto de nuestro Señor Jesucristo.

[[second-peter-1-9]]
^9^ Quien no las tenga es ciego y corto de vista; ha echado al olvido la purificación de sus pecados pasados.

[[second-peter-1-10]]
^10^ Por tanto, hermanos, poned el mayor empeño en afianzar vuestra vocación y vuestra elección. Obrando así nunca caeréis.

[[second-peter-1-11]]
^11^ Pues así se os dará amplia entrada en el Reino eterno de nuestro Señor y Salvador Jesucristo.

[[second-peter-1-12]]
^12^ Por esto, estaré siempre recordándoos estas cosas, aunque ya las sepáis y estéis firmes en la verdad que poseéis.

[[second-peter-1-13]]
^13^ Me parece justo, mientras me encuentro en esta tienda, estimularos con el recuerdo,

[[second-peter-1-14]]
^14^ sabiendo que pronto tendré que dejar mi tienda, según me lo ha manifestado nuestro Señor Jesucristo.

[[second-peter-1-15]]
^15^ Pero pondré empeño en que, en todo monento, después de mi partida, podáis recordar estas cosas.

[[second-peter-1-16]]
^16^ Os hemos dado a conocer el poder y la Venida de nuestro Señor Jesucristo, no siguiendo fábulas ingeniosas, sino después de haber visto con nuestros propios ojos su majestad.

[[second-peter-1-17]]
^17^ Porque recibió de Dios Padre honor y gloria, cuando la sublime Gloria le dirigió esta voz: «Este es mi Hijo muy amado en quien me complazco».

[[second-peter-1-18]]
^18^ Nosotros mismos escuchamos esta voz, venida del cielo, estando con él en el monte santo.

[[second-peter-1-19]]
^19^ Y así se nos hace más firme la palabra de los profetas, a la cual hacéis bien en prestar atención, como a lámpara que luce en lugar oscuro, hasta que despunte el día y se levante en vuestros corazones el lucero de la mañana.

[[second-peter-1-20]]
^20^ Pero, ante todo, tened presente que ninguna profecía de la Escritura puede interpretarse por cuenta propia;

[[second-peter-1-21]]
^21^ porque nunca profecía alguna ha venido por voluntad humana, sino que hombres movidos por el Espíritu Santo, han hablado de parte de Dios.
[[second-peter-2]]
== Capítulo 2

[[second-peter-2-1]]
^1^ Hubo también en el pueblo falsos profetas, como habrá entre vosotros falsos maestros que introducirán herejías perniciosas y que, negando al Dueño que los adquirió, atraerán sobre sí una rápida destrucción.

[[second-peter-2-2]]
^2^ Muchos seguirán su libertinaje y, por causa de ellos, el Camino de la verdad será difamado.

[[second-peter-2-3]]
^3^ Traficarán con vosotros por codicia, con palabras artificiosas; desde hace tiempo su condenación no está ociosa, ni su perdición dormida.

[[second-peter-2-4]]
^4^ Pues si Dios no perdonó a los Angeles que pecaron, sino que, precipitándolos en los abismos tenebrosos del Tártaro, los entregó para ser custodiados hasta el Juicio;

[[second-peter-2-5]]
^5^ si no perdonó al antiguo mundo, aunque preservó a Noé, heraldo de la justicia, y a otros siete, cuando hizo venir el diluvio sobre un mundo de impíos;

[[second-peter-2-6]]
^6^ si condenó a la destrucción las ciudades de Sodoma y Gomorra, reduciéndolas a cenizas, poniéndolas como ejemplo para los que en el futuro vivirían impíamente;

[[second-peter-2-7]]
^7^ y si libró a Lot, el justo, oprimido por la conducta licenciosa de aquellos hombres disolutos

[[second-peter-2-8]]
^8^ - pues este justo, que vivía en medio de ellos, torturaba día tras día su alma justa por las obras inicuas que veía y oía -

[[second-peter-2-9]]
^9^ es porque el Señor sabe librar de las pruebas a los piadosos y guardar a los impíos para castigarles en el día del Juicio,

[[second-peter-2-10]]
^10^ sobre todo a los que andan tras la carne con apetencias impuras y desprecian al Señorío. Atrevidos y arrogantes, no temen insultar a las Glorias,

[[second-peter-2-11]]
^11^ cuando los Angeles, que son superiores en fuerza y en poder, no pronuncian juicio injurioso contra ellas en presencia del Señor.

[[second-peter-2-12]]
^12^ Pero éstos, como animales irracionales, destinados por naturaleza a ser cazados y muertos, que injurian lo que ignoran, con muerte de animales morirán,

[[second-peter-2-13]]
^13^ sufriendo daño en pago del daño que hicieron. Tienen por felicidad el placer de un día; hombres manchados e infames, que se entregan de lleno a los placeres mientras banquetean con vosotros.

[[second-peter-2-14]]
^14^ Tienen los ojos llenos de adulterio, que no se sacian de pecado, seducen a las almas débiles, tienen el corazón ejercitado en la codicia, ¡hijos de maldición!

[[second-peter-2-15]]
^15^ Abandonando el camino recto, se desviaron y siguieron el camino de Balaam, hijo de Bosor, que amó un salario de iniquidad,

[[second-peter-2-16]]
^16^ pero fue reprendido por su mala acción. Un mudo jumento, hablando con voz humana, impidió la insensatez del profeta.

[[second-peter-2-17]]
^17^ Estos son fuentes secas y nubes llevadas por el huracán, a quienes está reservada la oscuridad de las tinieblas.

[[second-peter-2-18]]
^18^ Hablando palabras altisonantes, pero vacías, seducen con las pasiones de la carne y el libertinaje a los que acaban de alejarse de los que viven en el error.

[[second-peter-2-19]]
^19^ Les prometen libertad, mientras que ellos son esclavos de la corrupción, pues uno queda esclavo de aquel que le vence.

[[second-peter-2-20]]
^20^ Porque si, después de haberse alejado de la impureza del mundo por el conocimiento de nuestro Señor y Salvador Jesucristo, se enredan nuevamente en ella y son vencidos, su postrera situación resulta peor que la primera.

[[second-peter-2-21]]
^21^ Pues más les hubiera valido no haber conocido el camino de la justicia que, una vez conocido, volverse atrás del santo precepto que le fue transmitido.

[[second-peter-2-22]]
^22^ Les ha sucedido lo de aquel proverbio tan cierto: «el perro vuelve a su vómito» y «la puerca lavada, a revolcarse en el cieno».
[[second-peter-3]]
== Capítulo 3

[[second-peter-3-1]]
^1^ Esta es ya, queridos, la segunda carta que os escribo; en ambas, con lo que os recuerdo, despierto en vosotros el recto criterio.

[[second-peter-3-2]]
^2^ Acordaos de las predicciones de los santos profetas y del mandamiento de vuestros apóstoles que es el mismo del Señor y Salvador.

[[second-peter-3-3]]
^3^ Sabed ante todo que en los últimos días vendrán hombres llenos de sarcasmo, guiados por sus propias pasiones,

[[second-peter-3-4]]
^4^ que dirán en son de burla: «¿Dónde queda la promesa de su Venida? Pues desde que murieron los Padres, todo sigue como al principio de la creación».

[[second-peter-3-5]]
^5^ Porque ignoran intencionadamente que hace tiempo existieron unos cielos y también una tierra surgida del agua y establecida entre las aguas por la Palabra de Dios,

[[second-peter-3-6]]
^6^ y que, por esto, el mundo de entonces pereció inundado por las aguas del diluvio,

[[second-peter-3-7]]
^7^ y que los cielos y la tierra presentes, por esa misma Palabra, están reservados para el fuego y guardados hasta el día del Juicio y de la destrucción de los impíos.

[[second-peter-3-8]]
^8^ Mas una cosa no podéis ignorar, queridos: que ante el Señor un día es como mil años y, mil años, como un día.

[[second-peter-3-9]]
^9^ No se retrasa el Señor en el cumplimiento de la promesa, como algunos lo suponen, sino que usa de paciencia con vosotros, no queriendo que algunos perezcan, sino que todos lleguen a la conversión.

[[second-peter-3-10]]
^10^ El Día del Señor llegará como un ladrón; en aquel día, los cielos, con ruido ensordecedor, se desharán; los elementos, abrasados, se disolverán, y la tierra y cuanto ella encierra se consumirá.

[[second-peter-3-11]]
^11^ Puesto que todas estas cosas han de disolverse así, ¿cómo conviene que seáis en vuestra santa conducta y en la piedad,

[[second-peter-3-12]]
^12^ esperando y acelerando la venida del Día de Dios, en el que los cielos, en llamas, se disolverán, y los elementos, abrasados, se fundirán?

[[second-peter-3-13]]
^13^ Pero esperamos, según nos lo tiene prometido, nuevos cielos y nueva tierra, en lo que habite la justicia.

[[second-peter-3-14]]
^14^ Por lo tanto, queridos, en espera de estos acontecimientos, esforzaos por ser hallados en paz ante él, sin mancilla y sin tacha.

[[second-peter-3-15]]
^15^ La paciencia de nuestro Señor juzgadla como salvación, como os lo escribió también Pablo, nuestro querido hermano, según la sabiduría que le fue otorgada.

[[second-peter-3-16]]
^16^ Lo escribe también en todas las cartas cuando habla en ellas de esto. Aunque hay en ellas cosas difíciles de entender, que los ignorantes y los débiles interpretan torcidamente - como también las demás Escrituras - para su propia perdición.

[[second-peter-3-17]]
^17^ Vosotros, pues, queridos, estando ya advertidos, vivid alerta, no sea que, arrastrados por el error de esos disolutos, os veáis derribados de vuestra firme postura.

[[second-peter-3-18]]
^18^ Creced, pues, en la gracia y en el conocimiento de nuestro Señor y Salvador, Jesucristo. A él la gloria ahora y hasta el día de la eternidad. Amén.
