[[second-john]]
= Segunda carta de San Juan

[[second-john-1]]
== Capítulo 1

[[second-john-1-1]]
^1^ El Presbítero a la Señora elegida y a sus hijos, a quienes amo según la verdad - no sólo yo, sino también cuantos conocen la Verdad -

[[second-john-1-2]]
^2^ a causa de la verdad que permanece en nosotros y que estará con nosotros para siempre.

[[second-john-1-3]]
^3^ La gracia, la misericordia y la paz de parte de Dios Padre y de Jesucristo, el Hijo del Padre, estarán con nosotros según la verdad y el amor.

[[second-john-1-4]]
^4^ Me alegré mucho al encontrar entre tus hijos quienes viven según la verdad, conforme al mandamiento que recibimos del Padre.

[[second-john-1-5]]
^5^ Y ahora te ruego, Señora - y no es que te escriba un mandamiento nuevo, sino el que tenemos desde el comienzo - que nos amemos unos a otros.

[[second-john-1-6]]
^6^ Y en esto consiste el amor: en que vivamos conforme a sus mandamientos. Este es el mandamiento, como lo habéis oído desde el comienzo: que viváis en el amor.

[[second-john-1-7]]
^7^ Muchos seductores han salido al mundo, que no confiesan que Jesucristo ha venido en carne. Ese es el Seductor y el Anticristo.

[[second-john-1-8]]
^8^ Cuidad de vosotros, para que no perdáis el fruto de nuestro trabajo, sino que recibáis abundante recompensa.

[[second-john-1-9]]
^9^ Todo el que se excede y no permanece en la doctrina de Cristo, no posee a Dios. El que permanece en la doctrina, ése posee al Padre y al Hijo.

[[second-john-1-10]]
^10^ Si alguno viene a vosotros y no es portador de esta doctrina, no le recibáis en casa ni le saludéis,

[[second-john-1-11]]
^11^ pues el que le saluda se hace solidario de sus malas obras.

[[second-john-1-12]]
^12^ Aunque tengo mucho que escribiros, prefiero no hacerlo con papel y tinta, sino que espero ir a veros y hablaros de viva voz, para que nuestro gozo sea completo.

[[second-john-1-13]]
^13^ Te saludan los hijos de tu hermana Elegida.
