[[third-john]]
= Tercera carta de San Juan

[[third-john-1]]
== Capítulo 1

[[third-john-1-1]]
^1^ El Presbítero al querido Gayo a quien amo según la verdad.

[[third-john-1-2]]
^2^ Pido, querido, en mis oraciones que vayas bien en todo como va bien tu alma y que goces de salud.

[[third-john-1-3]]
^3^ Grande fue mi alegría al llegar los hermanos y dar testimonio de tu verdad, puesto que vives según la verdad.

[[third-john-1-4]]
^4^ No experimento alegría mayor que oír que mis hijos viven según la verdad.

[[third-john-1-5]]
^5^ Querido, te portas fielmente en tu conducta para con los hermanos, y eso que son forasteros.

[[third-john-1-6]]
^6^ Ellos han dado testimonio de tu amor en presencia de la Iglesia. Harás bien en proveerles para su viaje de manera digna de Dios.

[[third-john-1-7]]
^7^ Pues por el Nombre salieron sin recibir nada de los gentiles.

[[third-john-1-8]]
^8^ Por eso debemos acoger a tales personas, para ser colaboradores en la obra de la Verdad.

[[third-john-1-9]]
^9^ He escrito alguna cosa a la Iglesia; pero Diótrefes, ese que ambiciona el primer puesto entre ellos, no nos recibe.

[[third-john-1-10]]
^10^ Por eso, cuando vaya, le recordaré las cosas que está haciendo, criticándonos con palabras llenas de malicia; y como si no fuera bastante, tampoco recibe a los hermanos, impide a los que desean hacerlo y los expulsa de la Iglesia.

[[third-john-1-11]]
^11^ Querido, no imites lo malo, sino lo bueno. El que obra el bien es de Dios; el que obra el mal no ha visto a Dios.

[[third-john-1-12]]
^12^ Todos, y hasta la misma Verdad, dan testimonio de Demetrio. También nosotros damos testimonio y sabes que nuestro testimonio es verdadero.

[[third-john-1-13]]
^13^ Tengo mucho que escribirte, pero no quiero hacerlo con tinta y pluma.

[[third-john-1-14]]
^14^ Espero verte pronto y hablaremos de viva voz.

[[third-john-1-15]]
^15^ La paz sea contigo. Los amigos te saludan. Saluda a los amigos, a cada uno en particular.
