[[catechesi-tradendae-introduction]]
= INTRODUCCIÓN

:fn-1: footnote:[Cf. Mt 28, 19 s.]
:fn-2: footnote:[Cf. 1 Jn 1, 1.]
:fn-3: footnote:[Cf. Jn 20, 31.]
:fn-4: footnote:[Cf. AAS 63 (1971), pp. 758-764.]
:fn-5: footnote:[Cf. n. 44; cf. también los nn. 45-48; 54: AAS 68 (1976), pp. 34-35; 35-38; 43.]
:fn-6: footnote:[Se sabe que, según el Motu proprio Apostolica Sollicitudo del 15 septiembre 1965 (AAS 57 [1965], pp. 775-780), el Sínodo de los Obispos puede reunirse en Asamblea general, en Asamblea extraordinaria o en Asamblea especial. En la presente Exhortación Apostólica, las palabras «Sínodo» o «Padres Sinodales», o «Aula Sinodal», se referirán siempre, a no ser que se diga lo contrario, a la IV Asamblea general del Sínodo de los Obispos, tenida en Roma en octubre de 1977, sobre la catequesis.]
:fn-7: footnote:[Cf. Synodus Episcoporum: De catechesi hoc nostro tempore tradenda praesertim pueris atque iuvenibus, Ad Populum Dei Nuntius, e Civitate Vaticana, 28.X.1977; cf. « L'Osservatore Romano » (30 octubre 1977), pp. 3-4.]
:fn-8: footnote:[Cf. AAS 69 (1977), p. 633.]

[[catechesi-tradendae-1]]
== La última consigna de Cristo

^1^ La catequesis ha sido siempre considerada por la Iglesia como una de sus tareas primordiales, ya que Cristo resucitado, antes de volver al Padre, dio a los Apóstoles esta última consigna: hacer discípulos a todas las gentes, enseñándoles a observar todo lo que Él había mandado{fn-1}. Él les confiaba de este modo la misión y el poder de anunciar a los hombres lo que ellos mismos habían oído, visto con sus ojos, contemplado y palpado con sus manos, acerca del Verbo de vida{fn-2}. Al mismo tiempo les confiaba la misión y el poder de explicar con autoridad lo que Él les había enseñado, sus palabras y sus actos, sus signos y sus mandamientos. Y les daba el Espíritu para cumplir esta misión.

Muy pronto se llamó catequesis al conjunto de esfuerzos realizados por la Iglesia para hacer discípulos, para ayudar a los hombres a creer que Jesús es el Hijo de Dios, a fin de que, mediante la fe, ellos tengan la vida en su nombre{fn-3}, para educarlos e instruirlos en esta vida y construir así el Cuerpo de Cristo. La Iglesia no ha dejado de dedicar sus energías a esa tarea.

[[catechesi-tradendae-2]]
== Solicitud del Papa Pablo VI

^2^ Los últimos Papas le han reservado un puesto de relieve en su solicitud pastoral. Mi venerado Predecesor Pablo VI sirvió a la catequesis de la Iglesia de manera especialmente ejemplar con sus gestos, su predicación, su interpretación autorizada del Concilio Vaticano II —que él consideraba como la gran catequesis de los tiempos modernos— con su vida entera. Él aprobó, el 18 de marzo de 1971, el «Directorio general de la catequesis», preparado por la S. Congregación para el Clero, un Directorio que queda como un documento básico para orientar y estimular la renovación catequética en toda la Iglesia. Él instituyó la Comisión internacional de Catequesis, en el año 1975. Él definió magistralmente el papel y el significado de la catequesis en la vida y en la misión de la Iglesia, cuando se dirigió a los participantes en el Primer Congreso Internacional de Catequesis, el 25 de septiembre de 1971{fn-4}, y se detuvo explícitamente sobre este tema en la Exhortación Apostólica Evangelii Nuntiandi{fn-5}. Él quiso que la catequesis, especialmente la que se dirige a los niños y a los jóvenes, fuese el tema de la IV Asamblea general del Sínodo de los Obispos{fn-6}, celebrada durante el mes de octubre de 1977, en la que yo mismo tuve el gozo de participar.

[[catechesi-tradendae-3]]
== Un Sínodo fructuoso

^3^ Al concluir el Sínodo, los Padres entregaron al Papa una documentación muy rica, que comprendía las diversas intervenciones tenidas durante la Asamblea, las conclusiones de los grupos de trabajo, el Mensaje que con su consentimiento habían dirigido al pueblo de Dios{fn-7}, y sobre todo la serie imponente de «Proposiciones» en las que ellos expresaban su parecer acerca de muchos aspectos de la catequesis en el momento actual.

Este Sínodo ha trabajado en una atmósfera excepcional de acción de gracias y de esperanza. Ha visto en la renovación catequética un don precioso del Espíritu Santo a la Iglesia de hoy, un don al que por doquier las comunidades cristianas, a todos los niveles, responden con una generosidad y entrega creadora que suscitan admiración. El necesario discernimiento podía así realizarse partiendo de una base viva y podía contar en el pueblo de Dios con una gran disponibilidad a la gracia del Señor y a las directrices del Magisterio.

[[catechesi-tradendae-4]]
== Sentido de esta Exhortación

^4^ En este mismo clima de fe y esperanza os dirijo hoy, Venerables Hermanos, amados hijos e hijas, esta Exhortación Apostólica. En un tema tan amplio, ella no tratará sino de algunos aspectos más actuales y decisivos, para corroborar los frutos del Sínodo. Ella vuelve a tomar en consideración, sustancialmente, las reflexiones que el Papa Pablo VI había preparado, utilizando ampliamente los documentos dejados por el Sínodo. El Papa Juan Pablo I —cuyo celo y cualidades de catequista tanto asombro nos han causado— las había recogido y se disponía a publicarlas en el momento en que inesperadamente fue llamado por Dios. A todos nosotros él nos ha dado el ejemplo de una catequesis fundada en lo esencial y a la vez popular, hecha de gestos y palabras sencillas, capaces de llegar a los corazones. Yo asumo pues la herencia de estos dos Pontífices, para responder a la petición de los Obispos, formulada expresamente al final de la IV Asamblea general del Sínodo y acogida por el Papa Pablo VI en su discurso de clausura{fn-8}. Lo hago también para cumplir uno de los deberes principales de mi oficio apostólico. La catequesis ha sido siempre una preocupación central en mi ministerio de sacerdote y de obispo.

Deseo ardientemente que esta Exhortación Apostólica, dirigida a toda la Iglesia, refuerce la solidez de la fe y de la vida cristiana, dé un nuevo vigor a las iniciativas emprendidas, estimule la creatividad —con la vigilancia debida— y contribuya a difundir en la comunidad cristiana la alegría de llevar al mundo el misterio de Cristo.
