[[catechesi-tradendae-part-1]]
= I - TENEMOS UN SOLO MAESTRO: JESUCRISTO

:fn-9: footnote:[Jn 1, 14.]
:fn-10: footnote:[Jn 14, 6.]
:fn-11: footnote:[Ef 3, 9. 18s.]
:fn-12: footnote:[Cf. Jn 14, 6.]
:fn-13: footnote:[Jn 7, 16. Este es un tema preferido por el cuarto Evangelio: cf, Jn 3, 34; 8, 28; 12, 49 s; 14, 24; 17, 8. 14.]
:fn-14: footnote:[1 Co 11, 23: la palabra «transmitir», empleada aquí por san Pablo, ha sido repetida a menudo en la Exhort. Ap. Evangelii nuntiandi para describir la acción evangelizadora de la Iglesia; por ejemplo nn, 4, 15, 78, 79.]
:fn-15: footnote:[Act 1, 1.]
:fn-16: footnote:[Mt 26, 55; cf. Jn 18, 20.]
:fn-17: footnote:[Mc 10, 1.]
:fn-18: footnote:[Mc 1, 22; cf. también Mt 5, 2; 11, 1; 13, 54; 22, 16; Mc 2, 13; 4, 1; 6, 2. 6; Lc 5, 3. 17; Jn 7, 14; 8, 2; etc.]
:fn-19: footnote:[Lc 23, 5.]
:fn-20: footnote:[Aproximadamente en unos cincuenta pasajes de los cuatro Evangelios, este título, heredado por toda la Tradición judía pero adornado aquí de un significado nuevo que el mismo Cristo trata a menudo de iluminar, es atribuido a Jesús.]
:fn-21: footnote:[Cf., entre otros, Mt 8, 19; Mc 4, 38; 9, 38; 10, 35; 13, 1; Jn 11, 28.]
:fn-22: footnote:[Mt 12, 38.]
:fn-23: footnote:[Lc 10, 25; cf. Mt 22, 16.]
:fn-24: footnote:[Jn 13, 13 s.; cf. también Mt 10, 25; 26, 18 y paralelos.]
:fn-25: footnote:[Mt 23, 8. Ignacio de Antioquía recoge esta afirmación y la comenta así: «Nosotros hemos recibido la fe, por esto nosotros nos mantenemos a fin de ser reconocidos como discípulos de Jesucristo, nuestro único Maestro» (Epistula ad Magnesios, IX, 1: Funk 1, 239).]
:fn-26: footnote:[Jn 3, 2.]
:fn-27: footnote:[La representación de Cristo en actitud de enseñar aparece ya en las catacumbas romanas. Está usada profusamente en los mosaicos del arte romano-bizantino de los siglos III y IV. Constituirá un motivo artístico predominante en las imágines de las grandes catedrales románicas y góticas de la edad media.]

[[catechesi-tradendae-5]]
== En comunión con la persona de Cristo

^5^ La IV Asamblea general del Sínodo de los Obispos ha insistido mucho en el cristocentrismo de toda catequesis auténtica. Podemos señalar aquí los dos significados de la palabra que ni se oponen ni se excluyen, sino que más bien se relacionan y se complementan.

Hay que subrayar, en primer lugar, que en el centro de la catequesis encontramos esencialmente una Persona, la de Jesús de Nazaret, «Unigénito del Padre, lleno de gracia y de verdad»{fn-9}, que ha sufrido y ha muerto por nosotros y que ahora, resucitado, vive para siempre con nosotros. Jesús es «el Camino, la Verdad y la Vida»{fn-10}, y la vida cristiana consiste en seguir a Cristo, en la «sequela Christi».

El objeto esencial y primordial de la catequesis es, empleando una expresión muy familiar a San Pablo y a la teología contemporánea, «el Misterio de Cristo». Catequizar es, en cierto modo, llevar a uno a escrutar ese Misterio en toda su dimensión: «Iluminar a todos acerca de la dispensación del misterio... comprender, en unión con todos los santos, cuál es la anchura, la largura, la altura y la profundidad y conocer la caridad de Cristo, que supera toda ciencia, para que seáis llenos de toda la plenitud de Dios»{fn-11}. Se trata por lo tanto de descubrir en la Persona de Cristo el designio eterno de Dios que se realiza en Él. Se trata de procurar comprender el significado de los gestos y de las palabras de Cristo, los signos realizados por Él mismo, pues ellos encierran y manifiestan a la vez su Misterio. En este sentido, el fin definitivo de la catequesis es poner a uno no sólo en contacto sino en comunión, en intimidad con Jesucristo: sólo Él puede conducirnos al amor del Padre en el Espíritu y hacernos partícipes de la vida de la Santísima Trinidad.

[[catechesi-tradendae-6]]
== Transmitir la doctrina de Cristo

^6^ En la catequesis, el cristocentrismo significa también que, a través de ella se transmite no la propia doctrina o la de otro maestro, sino la enseñanza de Jesucristo, la Verdad que Él comunica o, más exactamente, la Verdad que Él es{fn-12}. Así pues hay que decir que en la catequesis lo que se enseña es a Cristo, el Verbo encarnado e Hijo de Dios y todo lo demás en referencia a Él; el único que enseña es Cristo, y cualquier otro lo hace en la medida en que es portavoz suyo, permitiendo que Cristo enseñe por su boca. La constante preocupación de todo catequista, cualquiera que sea su responsabilidad en la Iglesia, debe ser la de comunicar, a través de su enseñanza y su comportamiento, la doctrina y la vida de Jesús. No tratará de fijar en sí mismo, en sus opiniones y actitudes personales, la atención y la adhesión de aquel a quien catequiza; no tratará de inculcar sus opiniones y opciones personales como si éstas expresaran la doctrina y las lecciones de vida de Cristo. Todo catequista debería poder aplicarse a sí mismo la misteriosa frase de Jesús: «Mi doctrina no es mía, sino del que me ha enviado»{fn-13}. Es lo que hace san Pablo al tratar una cuestión de primordial importancia: «Yo he recibido del Señor lo que os he transmitido»{fn-14}. ¡Qué contacto asiduo con la Palabra de Dios transmitida por el Magisterio de la Iglesia, qué familiaridad profunda con Cristo y con el Padre, qué espíritu de oración, qué despego de sí mismo ha de tener el catequista para poder decir: «Mi doctrina no es mía»!

[[catechesi-tradendae-7]]
== Cristo que enseña

^7^ Esta doctrina no es un cúmulo de verdades abstractas, es la comunicación del Misterio vivo de Dios. La calidad de Aquel que enseña en el Evangelio y la naturaleza de su enseñanza superan en todo a las de los «maestros» en Israel, merced a la unión única existente entre lo que Él dice, hace y lo que es. Es evidente que los Evangelios indican claramente los momentos en que Jesús enseña, «Jesús hizo y enseñó»{fn-15}: en estos dos verbos que introducen al libro de los Hechos, san Lucas une y distingue a la vez dos dimensiones en la misión de Cristo.

Jesús enseñó. Este es el testimonio que Él da de sí mismo: «Todos los días me sentaba en el Templo a enseñar» {fn-16}. Esta es la observación llena de admiración que hacen los evangelistas, maravillados de verlo enseñando en todo tiempo y lugar, y de una forma y con una autoridad desconocidas hasta entonces: «De nuevo se fueron reuniendo junto a Él las multitudes y de nuevo, según su costumbre, les enseñaba»{fn-17}; «y se asombraban de su enseñanza, pues enseñaba como quien tiene autoridad»{fn-18}. Eso mismo hacen notar sus enemigos, aunque sólo sea para acusarlo y buscar un pretexto para condenarlo. «Subleva al pueblo, enseñando por toda Judea, desde Galilea, donde empezó, hasta aquí»{fn-19}.

[[catechesi-tradendae-8]]
== El único «Maestro»

^8^ El que enseña así merece a título único el nombre de Maestro. ¡Cuántas veces se le da este título de maestro a lo largo de todo el Nuevo Testamento y especialmente en los Evangelios!{fn-20}. Son evidentemente los Doce, los otros discípulos y las muchedumbres que lo escuchan quienes le llaman «Maestro» con acento a la vez de admiración, de confianza y de ternura{fn-21}. Incluso los Fariseos y los Saduceos, los Doctores de la Ley y los Judíos en general, no le rehúsan esta denominación: «Maestro, quisiéramos ver una señal tuya»{fn-22}; «Maestro, ¿qué tengo que hacer de bueno para alcanzar la vida eterna?»{fn-23}. Pero sobre todo Jesús mismo se llama Maestro en ocasiones particularmente solemnes y muy significativas: «Vosotros me llamáis Maestro y Señor, y decís bien, porque de verdad lo soy»{fn-24}; y proclama la singularidad, el carácter único de su condición de Maestro: «Uno solo es vuestro Maestro»{fn-25}: Cristo. Se comprende que, a lo largo de dos mil años, en todas las lenguas de la tierra, hombres de toda condición, raza y nación, le hayan dado con veneración este título repitiendo a su manera la exclamación de Nicodemo: «has venido como Maestro de parte de Dios»{fn-26}.

Esta imagen de Cristo que enseña, a la vez majestuosa y familiar, impresionante y tranquilizadora, imagen trazada por la pluma de los evangelistas y evocada después, con frecuencia, por la iconografía desde la época paleocristiana{fn-27}, —¡tan atractiva es!— deseo ahora evocarla en el umbral de estas reflexiones sobre la catequesis en el mundo actual.

[[catechesi-tradendae-9]]
== Enseñando con toda su vida

^9^ No olvido, haciendo esto, que la majestad de Cristo que enseña, la coherencia y la fuerza persuasiva únicas de su enseñanza, no se explican sino porque sus palabras, sus parábolas y razonamientos no pueden separarse nunca de su vida y de su mismo ser. En este sentido, la vida entera de Cristo fue una continua enseñanza: su silencio, sus milagros, sus gestos, su oración, su amor al hombre, su predilección por los pequeños y los pobres, la aceptación del sacrificio total en la cruz por la salvación del mundo, su resurrección son la actuación de su palabra y el cumplimiento de la revelación. De suerte que para los cristianos el Crucifijo es una de las imágenes más sublimes y populares de Jesús que enseña.

Estas consideraciones, que están en línea con las grandes tradiciones de la Iglesia, reafirman en nosotros el fervor hacia Cristo, el Maestro que revela a Dios a los hombres y al hombre a sí mismo; el Maestro que salva, santifica y guía, que está vivo, que habla, exige, que conmueve, que endereza, juzga, perdona, camina diariamente con nosotros en la historia; el Maestro que viene y que vendrá en la gloria.

Solamente en íntima comunión con Él, los catequistas encontrarán luz y fuerza para una renovación auténtica y deseable de la catequesis.