[[catechesi-tradendae-part-2]]
= II - UNA EXPERIENCIA TAN ANTIGUA COMO LA IGLESIA

[[catechesi-tradendae-10]]
== La Misión de los Apóstoles

^10^ La imagen de Cristo que enseña se había impreso en la mente de los Doce y de los primeros discípulos, y la consigna «Id y haced discípulos a todas las gentes»[28] orientó toda su vida. San Juan da testimonio de ello en su Evangelio, cuando refiere las palabras de Jesús: «Ya no os llamo siervos, porque el siervo no sabe lo que hace su señor; pero os digo amigos, porque todo lo que oí de mi Padre os lo he dado a conocer»[29]. No son ellos los que han escogido seguir a Jesús, sino que es Jesús quien los ha elegido, quien los ha guardado y establecido, ya antes de su Pascua, para que ellos vayan y den fruto y para que su fruto permanezca[30]. Por ello después de la resurrección, les confió formalmente la misión de hacer discípulos a todas las gentes.

Hay que subrayar, en primer lugar, que en el centro de la catequesis encontramos esencialmente una Persona, la de Jesús de Nazaret, «Unigénito del Padre, lleno de gracia y de verdad», que ha sufrido y ha muerto por nosotros y que ahora, resucitado, vive para siempre con nosotros. Jesús es «el Camino, la Verdad y la Vida», y la vida cristiana consiste en seguir a Cristo, en la «sequela Christi».

El objeto esencial y primordial de la catequesis es, empleando una expresión muy familiar a San Pablo y a la teología contemporánea, «el Misterio de Cristo». Catequizar es, en cierto modo, llevar a uno a escrutar ese Misterio en toda su dimensión: «Iluminar a todos acerca de la dispensación del misterio... comprender, en unión con todos los santos, cuál es la anchura, la largura, la altura y la profundidad y conocer la caridad de Cristo, que supera toda ciencia, para que seáis llenos de toda la plenitud de Dios». Se trata por lo tanto de descubrir en la Persona de Cristo el designio eterno de Dios que se realiza en Él. Se trata de procurar comprender el significado de los gestos y de las palabras de Cristo, los signos realizados por Él mismo, pues ellos encierran y manifiestan a la vez su Misterio. En este sentido, el fin definitivo de la catequesis es poner a uno no sólo en contacto sino en comunión, en intimidad con Jesucristo: sólo Él puede conducirnos al amor del Padre en el Espíritu y hacernos partícipes de la vida de la Santísima Trinidad.

[[catechesi-tradendae-11]]
== La catequesis en la época apostólica

^11^ Los Apóstoles no tardan en compartir con los demás el ministerio del apostolado[35]. Transmiten a sus sucesores la misión de enseñar. Ellos la confían también a los diáconos desde su institución: Esteban, «lleno de gracia y de poder», no cesa de enseñar, movido por la sabiduría del Espíritu[36]. Los Apóstoles asocian en su tarea de enseñar a «otros» discípulos[37]; e incluso simples cristianos dispersados por la persecución, iban por todas partes predicando la palabra[38]. San Pablo es el heraldo por antonomasia de este anuncio, desde Antioquía hasta Roma, donde la última imagen que tenemos de él según el libro de los Hechos, es la de un hombre «que enseña con toda libertad lo tocante al Señor Jesucristo»[39]. Sus numerosas cartas amplían y profundizan su enseñanza. Asimismo las cartas de Pedro, de Juan, de Santiago y de Judas son otros tantos testimonios de la catequesis de la era apostólica.

Los Evangelios que, antes de ser escritos, fueron la expresión de una enseñanza oral transmitida a las comunidades cristianas, tienen más o menos una estructura catequética. ¿No ha sido llamado el relato de San Mateo evangelio del catequista y el de San Marcos, evangelio del catecúmeno?

[[catechesi-tradendae-12]]
== En los Padres de la Iglesia

^12^ La Iglesia continúa esta misión de enseñar de los Apóstoles y de sus primeros colaboradores. Haciéndose día a día discípula del Señor, con razón se la ha llamado «Madre y Maestra»[40]. Desde Clemente Romano hasta Orígenes[41], en la edad postapostólica ven la luz obras notables. Más tarde se registra un hecho impresionante: Obispos y Pastores, los de mayor prestigio, sobre todo en los siglos tercero y cuarto, consideran como una parte importante de su ministerio episcopal enseñar de palabra o escribir tratados catequéticos. Es la época de Cirilo de Jerusalén y de Juan Crisóstomo, de Ambrosio y de Agustín, en la que brotan de la pluma de tantos Padres de la Iglesia obras que siguen siendo modelos para nosotros.

No es posible evocar aquí, ni siquiera brevemente, la catequesis que ha mantenido la difusión y el camino de la Iglesia en los diversos períodos de la historia, en todos los continentes y en los contextos sociales y culturales más diversos. Ciertamente las dificultades no han faltado nunca. Mas la Palabra del Señor ha realizado su misión a través de los siglos, se ha difundido y ha sido glorificada, como indica el Apóstol Pablo[42].

[[catechesi-tradendae-13]]
== En los Concilios y en la actividad misionera

^13^ El ministerio de la catequesis saca siempre nuevas energías de los Concilios. A este respecto el Concilio de Trento constituye un ejemplo que se ha de subrayar: en sus constituciones y decretos dio prioridad a la catequesis; dio lugar al «catecismo romano» que lleva además su nombre y constituye una obra de primer orden, resumen de la doctrina cristiana y de la teología tradicional para uso de los sacerdotes; promovió en la Iglesia una organización notable de la catequesis; despertó en los clérigos la conciencia de sus deberes con relación a la enseñanza catequética; y, merced al trabajo de santos teólogos como san Carlos Borromeo, san Roberto Belarmino o san Pedro Canisio, dio origen a catecismos, verdaderos modelos para aquel tiempo. ¡Ojalá suscite el Concilio Vaticano II un impulso y una obra semejante en nuestros días!

Las misiones constituyen también un terreno privilegiado para la práctica de la catequesis. Así, desde hace casi dos mil años, el Pueblo de Dios no ha cesado de educarse en la fe, según formas adaptadas a las distintas situaciones de los creyentes y a las múltiples coyunturas eclesiales.

La catequesis está íntimamente unida a toda la vida de la Iglesia. No sólo la extensión geográfica y el incremento numérico sino también, y más todavía, el crecimiento interior de la Iglesia, su correspondencia con el designio de Dios, dependen esencialmente de ella. De entre las experiencias de la historia de la Iglesia que acabamos de recordar, muchas lecciones —entre tantas otras— merecen ser puestas de relieve.

[[catechesi-tradendae-14]]
== La catequesis: derecho y deber de la Iglesia

^14^ Es evidente, ante todo, que la catequesis ha sido siempre para la Iglesia un deber sagrado y un derecho imprescriptible. Por una parte, es sin duda un deber que tiene su origen en un mandato del Señor e incumbe sobre todo a los que en la Nueva Alianza reciben la llamada al ministerio de Pastores. Por otra parte, puede hablarse igualmente de derecho: desde el punto de vista teológico, todo bautizado por el hecho mismo de su bautismo, tiene el derecho de recibir de la Iglesia una enseñanza y una formación que le permitan iniciar una vida verdaderamente cristiana; en la perspectiva de los derechos del hombre, toda persona humana tiene derecho a buscar la verdad religiosa y de adherirse plenamente a ella, libre de «toda coacción por parte tanto de los individuos como de los grupos sociales y de cualquier poder humano que sea, de suerte que, en esta materia, a nadie se fuerce a actuar contra su conciencia o se le impida actuar ... de acuerdo con ella»[43].

Por ello la actividad catequética debe poder ejercerse en circunstancias favorables de tiempo y lugar, debe tener acceso a los medios de comunicación social, a adecuados instrumentos de trabajo, sin discriminación para con los padres, los catequizados o los catequistas. Actualmente es cierto que ese derecho es reconocido cada vez más, al menos a nivel de grandes principios, como testimonian declaraciones o convenios internacionales, en los que —cualesquiera que sean sus límites— se puede reconocer la voz de la conciencia de gran parte de los hombres de hoy[44]. Pero numerosos Estados violan este derecho, hasta tal punto que dar, hacer dar la catequesis o recibirla, llega a ser un delito susceptible de sanción. En unión con los Padres del Sínodo elevo enérgicamente la voz contra toda discriminación en el ámbito de la catequesis, a la vez que dirijo una apremiante llamada a los responsables para que acaben del todo esas constricciones que gravan sobre la libertad humana en general y sobre la libertad religiosa en particular.

[[catechesi-tradendae-15]]
== Tarea prioritaria

^15^ La segunda lección se refiere al lugar mismo de la catequesis en los proyectos pastorales de la Iglesia. Cuanto más capaz sea, a escala local o universal, de dar la prioridad a la catequesis —por encima de otras obras e iniciativas cuyos resultados podrían ser mas espectaculares—, tanto más la Iglesia encontrará en la catequesis una consolidación de su vida interna como comunidad de creyentes y de su actividad externa como misionera. En este final del siglo XX, Dios y los acontecimientos, que son otras tantas llamadas de su parte, invitan a la Iglesia a renovar su confianza en la acción catequética como en una tarea absolutamente primordial de su misión. Es invitada a consagrar a la catequesis sus mejores recursos en hombres y en energías, sin ahorrar esfuerzos, fatigas y medios materiales, para organizarla mejor y formar personal capacitado. En ello no hay un mero cálculo humano, sino una actitud de fe. Y una actitud de fe se dirige siempre a la fidelidad a Dios, que nunca deja de responder.

[[catechesi-tradendae-16]]
== Responsabilidad común y diferenciada

^16^ Tercera lección: la catequesis ha sido siempre, y seguirá siendo, una obra de la que la Iglesia entera debe sentirse y querer ser responsable. Pero sus miembros tienen responsabilidades diferentes, derivadas de la misión de cada uno. Los Pastores, precisamente en virtud de su oficio, tienen, a distintos niveles, la más alta responsabilidad en la promoción, orientación y coordinación de la catequesis. El Papa, por su parte, tiene una profunda conciencia de la responsabilidad primaria que le compete en este campo: encuentra en él motivos de preocupación pastoral, pero sobre todo de alegría y de esperanza. Los sacerdotes, religiosos y religiosas tienen ahí un campo privilegiado para su apostolado. A otro nivel, los padres de familia tienen una responsabilidad singular. Los maestros, los diversos ministros de la Iglesia, los catequistas y, por otra parte, los responsables de los medios de comunicación social, todos ellos tienen, en grado diverso, responsabilidades muy precisas en esta formación de la conciencia del creyente, formación importante para la vida de la Iglesia, y que repercute en la vida de la sociedad misma. Uno de los mejores frutos de la Asamblea general del Sínodo dedicado por entero a la catequesis sería despertar, en toda la Iglesia y en cada uno de sus sectores, una conciencia viva y operante de esta responsabilidad diferenciada pero común.

[[catechesi-tradendae-17]]
== Responsabilidad común y diferenciada

^17^ Finalmente la catequesis tiene necesidad de renovarse continuamente en un cierto alargamiento de su concepto mismo, en sus métodos, en la búsqueda de un lenguaje adaptado, en el empleo de nuevos medios de transmisión del mensaje Esta renovación no siempre tiene igual valor, y los Padres del Sínodo han reconocido con realismo, junto a un progreso innegable en la vitalidad de la actividad catequética y a iniciativas prometedoras, las limitaciones o incluso las «deficiencias» de lo que se ha realizado hasta el presente[45]. Estos límites son particularmente graves cuando ponen en peligro la integridad del contenido. El «Mensaje al pueblo de Dios» subrayó justamente que, para la catequesis, «la repetición rutinaria, que se opone a todo cambio, por una parte, y la improvisación irreflexiva que afronta con ligereza los problemas, por la otra, son igualmente peligrosas»[46]. La repetición rutinaria lleva al estancamiento, al letargo y, en definitiva, a la parálisis. La improvisación irreflexiva engendra desconcierto en los catequizados y en sus padres, cuando se trata de los niños, causa desviaciones de todo tipo, rupturas y finalmente la ruina total de la unidad. Es necesario que la Iglesia dé prueba hoy —come supo hacerlo en otras épocas de su historia— de sabiduría, de valentía y de fidelidad evangélicas, buscando y abriendo caminos y perspectivas nuevas para la enseñanza catequética.
