[[catechesi-tradendae-part-4]]
= IV - TODA LA BUENA NUEVA BROTA DE LA FUENTE

:fn-57: footnote:[Const. dogm. sobre la divina Revelación Dei Verbum, nn. 10 y 24: AAS 58 (1966), pp. 822 y 828 s.; cf. también S. Congregación para el Clero, Directorium Catechisticum Generale, n. 45 (AAS 64 [1972], p. 124), que sitúa bien las fuentes principales o complementarias de la catequesis.]
:fn-58: footnote:[Cf. Ordo initiationis christianae adultorum, nn. 25-26; 183-187.]
:fn-59: footnote:[Cf. AAS 60 (1968), pp. 436-445. Al lado de estas grandes profesiones de fe del Magisterio, se pueden ver profesiones de fe populares, arraigadas en la cultura cristiana tradicional de ciertos países; cf. lo que yo decía a los jóvenes en Gniezno, 3 junio 1979, a propósito del canto-mensaje «Bogurodzica»: «No es solamente un canto: es también una profesión de fe, un símbolo del Credo polaco, es una catequesis y también un documento de tradición cristiana. Las principales verdades de fe y los principios de la moral están contenidos en él. No es solamente un objeto histórico. Es el documento de la vida. Se le ha llamado también el catecismo polaco»: cf. AAS 71 (1979), p. 754.]
:fn-60: footnote:[N. 25: AAS 68 (1976), p. 23.]
:fn-61: footnote:[Ibid., principalmente nn. 26-39: l. c., pp. 23-25; los «elementos principales del mensaje cristiano» están expuestos de manera más sistemática todavía en el Directorium Catechisticum Generale, nn. 47-69 (AAS 64 [1972], pp. 125-141) en el cual se encuentra también la norma del contenido doctrinal esencial de la catequesis.]
:fn-62: footnote:[Se podrá consultar también el capítulo del Directorium Catechisticum Generale sobre este punto, nn. 37-46 (l.c., pp. 120-125).]
:fn-63: footnote:[Rom 1, 19.]
:fn-64: footnote:[Act 17, 23]
:fn-65: footnote:[Cf. Ef 3, 3.]
:fn-66: footnote:[Cf. Ef 2, 18]
:fn-67: footnote:[Act 20, 28.]
:fn-68: footnote:[Conc. Ecum. Vat. II, Const. past. sobre la Iglesia en el mundo actual Gaudium et spes, n. 39: AAS 58 (1966), pp. 1056 s.]
:fn-69: footnote:[Rom 6, 4.]
:fn-70: footnote:[2 Co 5, 17.]
:fn-71: footnote:[Cf. ibid.]
:fn-72: footnote:[Rom 6, 23.]
:fn-73: footnote:[Cf. Pablo VI, Exhort. Ap. Evangelii nuntiandi, nn. 30-38: AAS 68 (1976), pp. 25-30.]
:fn-74: footnote:[Cf. Catecismo mayor, V parte, cap. 6, nn. 965-966.]
:fn-75: footnote:[Cf. Flp 2, 17.]
:fn-76: footnote:[Rom 10, 8.]
:fn-77: footnote:[Flp 3, 8]
:fn-78: footnote:[Ef 4, 20 s.]
:fn-79: footnote:[Cf. 2 Tes 2, 7.]
:fn-80: footnote:[Jn 6, 69; cf. Act 5, 20; 7, 38.]
:fn-81: footnote:[Act 2, 28, citando el Sal 1a, 11.]
:fn-82: footnote:[Cf. todo el decreto sobre el ecumenismo Unitatis Redintegratio: AAS 57 (1965), pp. 90-112.]
:fn-83: footnote:[Cf. ibid., n. 5: l.c., p. 96; cf. también Conc. Ecum. Vat. II, Decr. sobre la actividad misionera de la Iglesia Ad Gentes, n. 15: AAS 58 (1966), pp. 963-965; S. Congregación para el Clero, Directorium Catechisticum Generale, n. 27: AAS 64 (1972), p. 115.]
:fn-84: footnote:[Cf. Conc. Ecum. Vat. II, Decr. sobre el ecumenismo Unitatis Redintegratio, nn. 3-4: AAS 57 (1965), pp. 92-96.]
:fn-85: footnote:[Ibid., n 3: l. c., p. 93.]
:fn-86: footnote:[Cf. Ibid.; cf. también Const. dogm. sobre la Iglesia Lumen gentium, n 15: AAS 57 (1965), p. 19.]

[[catechesi-tradendae-26]]
== El contenido del Mensaje

^26^ Siendo la catequesis un momento o un aspecto de la evangelización, su contenido no puede ser otro que el de toda la evangelización: el mismo mensaje —Buena Nueva de salvación— oído una y mil veces y aceptado de corazón, se profundiza incesantemente en la catequesis mediante la reflexión y el estudio sistemático; mediante una toma de conciencia, que cada vez compromete más, de sus repercusiones en la vida personal de cada uno; mediante su inserción en el conjunto orgánico y armonioso que es la existencia cristiana en la sociedad y en el mundo.

[[catechesi-tradendae-27]]
== La fuente

^27^ La catequesis extraerá siempre su contenido de la fuente viva de la Palabra de Dios, transmitida mediante la Tradición y la Escritura, dado que «la Tradición y la Escritura constituyen el depósito sagrado de la Palabra de Dios, confiado a la Iglesia», como ha recordado el Concilio Vaticano II al desear que «el ministerio de la palabra, que incluye la predicación pastoral, la catequesis, toda la instrucción cristiana... reciba de la palabra de la Escritura alimento saludable y por ella dé frutos de santidad»{fn-57}.

Hablar de la Tradición y de la Escritura como fuentes de la catequesis es subrayar que ésta ha de estar totalmente impregnada por el pensamiento, el espíritu y actitudes bíblicas y evangélicas a través de un contacto asiduo con los textos mismos; es también recordar que la catequesis será tanto más rica y eficaz cuanto más lea los textos con la inteligencia y el corazón de la Iglesia y cuanto más se inspire en la reflexión y en la vida dos veces milenaria de la Iglesia.

La enseñanza, la liturgia y la vida de la Iglesia surgen de esta fuente y conducen a ella, bajo la dirección de los Pastores y concretamente del Magisterio doctrinal que el Señor les ha confiado.

[[catechesi-tradendae-28]]
== El Credo: expresión doctrinal privilegiada

^28^ Una expresión privilegiada de la herencia viva que ellos han recibido en custodia, se encuentra en el Credo o, más concretamente, en los Símbolos que, en momentos cruciales, recogieron en síntesis felices la fe de la Iglesia. Durante siglos, un elemento importante de la catequesis era precisamente la «traditio Symboli» (o transmisión del compendio de la fe), seguida de la entrega de la oración dominical. Este rito expresivo ha vuelto a ser introducido en nuestros días en la iniciación de los catecúmenos{fn-58}. ¿No habría que encontrar una utilización más concretamente adaptada, para señalar esta etapa, la más importante entre todas, en que un nuevo discípulo de Jesucristo acepta con plena lucidez y valentía el contenido de lo que más adelante va a profundizar con seriedad?

Mi predecesor Pablo VI, en el «Credo del Pueblo de Dios» proclamado al cumplirse el XIX centenario del martirio de los Apóstoles Pedro y Pablo, quiso reunir los elementos esenciales de la fe católica, sobre todo los que ofrecían mayor dificultad o estaban en peligro de ser ignorados{fn-59}. Es una referencia segura para el contenido de la catequesis.

[[catechesi-tradendae-29]]
== Elementos a no olvidar

^29^ El mismo Sumo Pontífice ha recordado, en el capítulo tercero de su Exhortación Apostólica Evangelii nuntiandi, «el contenido esencial, la substancia viva» de la evangelización{fn-60}. Es necesario para la catequesis misma tener presente cada uno de los elementos y la síntesis viva en que ellos han sido integrados{fn-61}.

Me contentaré por consiguiente con ofrecer aquí alguna simple alusión{fn-62}. Todos ven, por ejemplo, la importancia de hacer entender al niño, al adolescente, al que progresa en la fe, «lo que puede conocerse de Dios»{fn-63}; de poderles decir, en cierto sentido: «Lo que sin conocer veneráis, eso es lo que yo os anuncio»{fn-64}; de exponerles brevemente{fn-65} el misterio del Verbo de Dios hecho hombre y que realiza la salvación del hombre por su Pascua, es decir, a través de su muerte y su resurrección, pero también con su predicación, con los signos que realiza, con los sacramentos de su presencia permanente en medio de nosotros. Los Padres del Sínodo estuvieron bien inspirados cuando pidieron que se evite reducir a Cristo a su sola humanidad y su mensaje a una dimensión meramente terrestre, y que se le reconociera más bien como el Hijo de Dios, el mediador que nos da libre acceso al Padre en el Espíritu{fn-66}.

¡Cuán importante es exponer a la inteligencia y al corazón, a la luz de la fe, ese sacramento de su presencia que es el Misterio de la Iglesia, asamblea de hombres pecadores, pero, al mismo tiempo, santificados y que constituyen la familia de Dios reunida por el Señor bajo la dirección de aquellos a quienes «el Espíritu Santo... constituyó vigilantes para apacentar la Iglesia de Dios»!{fn-67}.

Es importante explicar que la historia de los hombres, con sus aspectos de gracia y de pecado, de grandeza y de miseria, es asumida por Dios en su Hijo Jesucristo y «ofrece ya algún bosquejo del siglo futuro»{fn-68}. Es importante, finalmente, revelar sin ambages las exigencias, hechas de renuncia mas también de gozo, de lo que el Apóstol Pablo gustaba llamar «vida nueva»{fn-69}, «creación nueva»{fn-70}., ser o existir en Cristo{fn-71}, «vida eterna en Cristo Jesús»{fn-72}, y que no es más que la vida en el mundo, pero una vida según las bienaventuranzas y destinada a prolongarse y a transfigurarse en el más allá.

De ahí la importancia que tienen en la catequesis las exigencias morales personales correspondientes al Evangelio y las actitudes cristianas ante la vida y ante el mundo, ya sean heroicas, ya las más sencillas: nosotros las llamamos virtudes cristianas o virtudes evangélicas. De ahí también el cuidado que tendrá la catequesis de no omitir, sino iluminar como es debido, en su esfuerzo de educación en la fe, realidades como la acción del hombre por su liberación integral{fn-73}, la búsqueda de una sociedad más solidaria y fraterna, las luchas por la justicia y la construcción de la paz.

Por lo demás no se ha de creer que esta dimensión de la catequesis es absolutamente nueva. Ya en la época patrística, san Ambrosio y san Juan Crisóstomo, por no mencionar a otros, destacaron las consecuencias sociales de las exigencias evangélicas y, más cerca de nosotros, el catecismo de san Pío X citaba explícitamente, entre los pecados que claman venganza ante Dios, el hecho de oprimir a los pobres, así como el defraudar a los trabajadores en su justo salario{fn-74}. Especialmente desde la Rerum novarum, la preocupación social está activamente presente en la enseñanza catequética de los papas y de los obispos. Muchos Padres del Sínodo han pedido con legítima insistencia que el rico patrimonio de la enseñanza social de la Iglesia encuentre su puesto, bajo formas apropiadas, en la formación catequética común de los fieles.

[[catechesi-tradendae-30]]
== Integridad del contenido

^30^ A propósito del contenido de la catequesis, hay que poner de relieve, en nuestros días, tres puntos importantes.

El primero se refiere a la integridad de dicho contenido. A fin de que la oblación de su fe{fn-75} sea perfecta, el que se hace discípulo de Cristo tiene derecho a recibir la «palabra de la fe»{fn-76} no mutilada, falsificada o disminuida, sino completa e integral, en todo su rigor y su vigor. Traicionar en algo la integridad del mensaje es vaciar peligrosamente la catequesis misma y comprometer los frutos que de ella tienen derecho a esperar Cristo y la comunidad eclesial. No es ciertamente casual el hecho de que una cierta totalidad caracterice el mandato final de Jesús en el evangelio de Mateo: «Me ha sido dado todo poder... Haced discípulos a todas las gentes... enseñándoles a guardar todo... yo estoy siempre con vosotros». Por eso, cuando un hombre, presintiendo «la superioridad del conocimiento de Cristo Jesús»{fn-77}, descubierto por la fe, abrigue el deseo, aún inconsciente, de conocerle más y mejor, mediante «una predicación y enseñanza conforme a la verdad que hay en Jesús»{fn-78}, ningún pretexto es válido para negarle parte alguna de ese conocimiento. ¿Qué catequesis sería aquella en la que no hubiera lugar para la creación del hombre y su pecado, para el plan redentor de nuestro Dios y su larga y amorosa preparación y realización, para la Encarnación del Hijo de Dios, para María —la Inmaculada, la Madre de Dios, siempre Virgen, elevada en cuerpo y alma a la gloria celestial— y su función en el misterio de la salvación, para el misterio de la iniquidad operante en nuestras vidas{fn-79} y la virtud de Dios que nos libera, para la necesidad de la penitencia y de la ascesis, para los gestos sacramentales y litúrgicos, para la realidad de la presencia eucarística, para la participación en la vida divina aquí en la tierra y en el más allá, etc.? Asimismo, a ningún verdadero catequista le es lícito hacer por cuenta propia una selección en el depósito de la fe, entre lo que estima importante y lo que estima menos importante o para enseñar lo uno y rechazar lo otro.

[[catechesi-tradendae-31]]
== Con métodos pedagógicos adaptados

^31^ De ahí esta segunda observación: es posible que en la situación actual de la catequesis, razones de método o de pedagogía aconsejen organizar la comunicación de las riquezas del contenido de la catequesis de un modo más bien que de otro. Por lo demás, la integridad no dispensa del equilibrio ni del carácter orgánico y jerarquizado, gracias a los cuales se dará a las verdades que se enseñan, a las normas que se transmiten y a los caminos de la vida cristiana que se indican, la importancia respectiva que les corresponden. También puede suceder que determinado lenguaje se demuestre preferible para transmitir este contenido a determinada persona o grupo de personas. La elección sería válida en la medida en que no dependa de teorías o prejuicios más o menos subjetivos y marcados por una cierta ideología, sino que esté inspirada por el humilde afán de ajustarse mejor a un contenido que debe permanecer intacto. El método y el lenguaje utilizados deben seguir siendo verdaderamente instrumentos para comunicar la totalidad y no una parte de las «palabras de vida eterna»{fn-80} o del «camino de la vida»{fn-81}.

[[catechesi-tradendae-32]]
== Dimensión ecuménica de la catequesis

^32^ El gran movimiento, inspirado ciertamente por el Espíritu de Jesús, que, desde hace un cierto número de años, lleva a la Iglesia católica a buscar con otras Iglesias o confesiones cristianas el restablecimiento de la perfecta unidad querida por el Señor, me induce a hablar del carácter ecuménico de la catequesis. Este movimiento cobró todo su relieve en el Concilio Vaticano II{fn-82}, y, a partir del Concilio, ha conocido en la Iglesia una importancia, concretada en una serie impresionante de hechos y de iniciativas, conocidas por todos.

La catequesis no puede permanecer ajena a esta dimensión ecuménica cuando todos los fieles, según su propia capacidad y su situación en la Iglesia, son llamados a tomar parte en el movimiento hacia la unidad{fn-83}.

La catequesis tendrá una dimensión ecuménica si, sin renunciar a enseñar que la plenitud de las verdades reveladas y de los medios de salvación instituidos por Cristo se halla en la Iglesia Católica{fn-84}, lo hace, sin embargo, respetando sinceramente, de palabra y de obra, a las comunidades eclesiales que no están en perfecta comunión con esta misma Iglesia.

En este contexto, es muy importante hacer una presentación correcta y leal de las demás Iglesias y comunidades eclesiales de las que el Espíritu de Cristo no rehúsa servirse como medio de salvación; por otra parte «los elementos o bienes que conjuntamente edifican y dan vida a la propia Iglesia, pueden encontrarse algunos, más aún, muchísimos y muy valiosos, fuera del recinto visible de la Iglesia católica»{fn-85}. Además esta presentación ayudará a los católicos por un lado a profundizar su propia fe y por otra a conocer mejor y estimar a los demás hermanos cristianos, facilitando así la búsqueda común del camino hacia la plena unidad en toda la verdad. Ella debería además ayudar a los no católicos a conocer mejor y a apreciar a la Iglesia católica y su convicción de ser el «auxilio general de salvación».

La catequesis tendrá una dimensión ecuménica si, además, suscita y alimenta un verdadero deseo de unidad; más todavía, si inspira esfuerzos sinceros —incluido el esfuerzo por purificarse en la humildad y el fervor del Espíritu con el fin de despejar los caminos— no con miras a un irenismo fácil, hecho de omisiones y de concesiones en el plano doctrinal, sino con miras a la unidad perfecta, cuando el Señor quiera y por las vías que Él quiera.

Finalmente, la catequesis será ecuménica si se esfuerza por preparar a los niños y a los jóvenes, así como a los adultos católicos, a vivir en contacto con los no católicos, viviendo su identidad católica dentro del respecto a la fe de los otros.

[[catechesi-tradendae-33]]
== Colaboración ecuménica en el ámbito de la catequesis

^33^ En situaciones de pluralismo religioso, los Obispos pueden juzgar oportunas, o aun necesarias, ciertas experiencias de colaboración en el campo de la catequesis entre católicos y otros cristianos, como complemento de la catequesis habitual que, de todos modos, los católicos deben recibir. Tales experiencias encuentran su fundamento teológico en los elementos comunes a todos los cristianos{fn-86}. Pero la comunión de fe entre los católicos y los demás cristianos no es completa ni perfecta; más aún existen, en determinados casos, profundas divergencias. En consecuencia, esta colaboración ecuménica es por su naturaleza limitada: no debe significar jamás una «reducción» al mínimo común. Además, la catequesis no consiste únicamente en enseñar la doctrina, sino en iniciar a toda la vida cristiana, haciendo participar plenamente en los sacramentos de la Iglesia. De ahí la necesidad, donde se da una experiencia de colaboración ecuménica en el terreno de la catequesis, de vigilar para que la formación de los católicos esté bien asegurada en la Iglesia católica en lo concerniente a la doctrina y a la vida cristiana.

Durante el Sínodo, cierto número de Obispos señaló casos —cada vez más frecuentes, decían— en los que las autoridades civiles u otras circunstancias imponen, en las escuelas de algunos países, una enseñanza de la religión cristiana —con sus manuales, horas de clase, etc.— común a católicos y no católicos. Sería superfluo decir que no se trata de una verdadera catequesis. Esta enseñanza tiene además una importancia ecuménica cuando se presenta con lealtad la doctrina cristiana. En los casos en que las circunstancias impusieran esta enseñanza, es importante que sea asegurada de otra manera, con el mayor esmero, una catequesis específicamente católica.

[[catechesi-tradendae-34]]
== Problema de manuales comunes a diversas religiones

^34^ Hay que añadir aquí otra observación que se sitúa en la misma dirección aunque bajo óptica distinta. Sucede a veces que las escuelas estatales ponen libros a disposición de los alumnos, en los que las religiones, incluida la católica, son presentadas a título cultural histórico, moral y literario. Una presentación objetiva de los hechos históricos, de las diferentes religiones y confesiones cristianas puede contribuir a una mejor comprensión recíproca. En tal caso se hará todo lo posible para que la presentación sea verdaderamente objetiva, al resguardo de sistemas ideológicos y políticos o de pretendidos prejuicios científicos que deformarían su verdadero sentido. De todos modos, estos manuales no deben considerarse como obras catequéticas: les falta para ello el testimonio de creyentes que exponen la fe a otros creyentes, y una comprensión de los misterios cristianos y de lo específicamente católico, todo ello sacado de lo profundo de la fe.
