[[catechesi-tradendae-part-5]]
= V - TODOS TIENEN NECESIDAD DE LA CATEQUESIS

[[catechesi-tradendae-35]]
== La importancia de los niños y de los jóvenes

^35^ El tema señalado por mi Predecesor, Pablo VI, para la IV Asamblea general del Sínodo de los Obispos versaba sobre «la catequesis en nuestro tiempo con especial atención a los niños y a los jóvenes». El ascenso de los jóvenes constituye sin duda el hecho más rico de esperanza y al mismo tiempo de inquietud para una buena parte del mundo actual. En algunos países, sobre todo los del Tercer Mundo, más de la mitad de la población está por debajo de los veinticinco o treinta años. Ello significa que millones y millones de niños y de jóvenes se preparan para su futuro de adultos. Y no es sólo el factor numérico: acontecimientos recientes, y la misma crónica diaria, nos dicen que esta multitud innumerable de jóvenes, aunque esté dominada aquí y allí por la incertidumbre y el miedo, o seducida por la evasión en la droga y la indiferencia, incluso tentada por el nihilismo y la violencia, constituye sin embargo en su mayor parte la gran fuerza que, entre muchos riesgos, se propone construir la civilización del futuro.

Ahora bien, en nuestra solicitud pastoral nos preguntamos: ¿Cómo revelar a esa multitud de niños y jóvenes a Jesucristo, Dios hecho hombre? ¿Cómo revelarlo no simplemente en el deslumbramiento de un primer encuentro fugaz, sino a través del conocimiento cada día más hondo y más luminoso de su persona, de su mensaje, del Plan de Dios que él quiso revelar, del llamamiento que dirige a cada uno, del Reino que quiere inaugurar en este mundo con el «pequeño rebaño»[87] de quienes creen en él, y que no estará completo más que en la eternidad? ¿Cómo dar a conocer el sentido, el alcance, las exigencias fundamentales, la ley del amor, las promesas, las esperanzas de ese Reino?

Habría que hacer muchas observaciones sobre las características propias que adopta la catequesis en las diferentes etapas de la vida.

[[catechesi-tradendae-36]]
== Párvulos

^36^ Un momento con frecuencia destacado es aquel en que el niño pequeño recibe de sus padres y del ambiente familiar los primeros rudimentos de la catequesis, que acaso no serán sino una sencilla revelación del Padre celeste, bueno y providente, al cual aprende a dirigir su corazón. Las brevísimas oraciones que el niño aprenderá a balbucir serán el principio de un diálogo cariñoso con ese Dios oculto, cuya Palabra comenzará a escuchar después. Ante los padres cristianos nunca insistiríamos demasiado en esta iniciación precoz, mediante la cual son integradas las facultades del niño en una relación vital con Dios: obra capital que exige gran amor y profundo respeto al niño, el cual tiene derecho a una presentación sencilla y verdadera de la fe cristiana.

[[catechesi-tradendae-37]]
== Niños

^37^ Pronto llegará, en la escuela y en la iglesia, en la parroquia o en la asistencia espiritual recibida en el colegio católico o en el instituto estatal, a la vez que la apertura a un círculo social más amplio, el momento de una catequesis destinada a introducir al niño de manera orgánica en la vida de la Iglesia, incluida también una preparación inmediata a la celebración de los sacramentos: catequesis didáctica, pero encaminada a dar testimonio de la fe; catequesis inicial, mas no fragmentaria, puesto que deberá revelar, si bien de manera elemental, todos los principales misterios de la fe y su repercusión en la vida moral y religiosa del niño; catequesis que da sentido a los sacramentos, pero a la vez recibe de los sacramentos vividos una dimensión vital que le impide quedarse en meramente doctrinal, y comunica al niño la alegría de ser testimonio de Cristo en su ambiente de vida.

[[catechesi-tradendae-38]]
== Adolescentes

^38^ Luego vienen la pubertad y la adolescencia, con las grandezas y los riesgos que presenta esa edad. Es el momento del descubrimiento de sí mismo y del propio mundo interior, el momento de los proyectos generosos, momento en que brota el sentimiento del amor, así como los impulsos biológicos de la sexualidad, del deseo de estar juntos; momento de una alegría particularmente intensa, relacionada con el embriagador descubrimiento de la vida. Pero también es a menudo la edad de los interrogantes más profundos, de búsquedas angustiosas, incluso frustrantes, de desconfianza de los demás y de peligrosos repliegues sobre sí mismo; a veces también la edad de los primeros fracasos y de las primeras amarguras. La catequesis no puede ignorar esos aspectos fácilmente cambiantes de un período tan delicado de la vida. Podrá ser decisiva una catequesis capaz de conducir al adolescente a una revisión de su propia vida y al diálogo, una catequesis que no ignore sus grandes temas, —la donación de sí mismo, la fe, el amor y su mediación que es la sexualidad—. La revelación de Jesucristo como amigo, como guía y como modelo, admirable y sin embargo imitable; la revelación de su mensaje que da respuesta a las cuestiones fundamentales; la revelación del Plan de amor de Cristo Salvador como encarnación del único amor verdadero y de la única posibilidad de unir a los hombres, todo eso podrá constituir la base de una auténtica educación en la fe. Y sobre todo los misterios de la pasión y de la muerte de Jesús, a los que san Pablo atribuye el mérito de su gloriosa resurrección, podrán decir muchas cosas a la conciencia y al corazón del adolescente y arrojar luz sobre sus primeros sufrimientos y los del mundo que va descubriendo.

[[catechesi-tradendae-39]]
== Jóvenes

^39^ Con la edad de la juventud llega la hora de las primeras decisiones. Ayudado tal vez por los miembros de su familia y por los amigos, mas a pesar de todo solo consigo mismo y con su conciencia moral, el joven, cada vez más a menudo y de modo más determinante, deberá asumir su destino. Bien y mal, gracia y pecado, vida y muerte, se enfrentarán cada vez más en su interior como categorías morales, pero también y sobre todo como opciones fundamentales que habrá de efectuar o rehusar con lucidez y sentido de responsabilidad. Es evidente que una catequesis que denuncie el egoísmo en nombre de la generosidad, que exponga sin simplismos ni esquematismos ilusorios el sentido cristiano del trabajo, del bien común, de la justicia y de la caridad, una catequesis sobre la paz entre las naciones, sobre la promoción de la dignidad humana, del desarrollo, de la liberación tal como las presentan documentos recientes de la Iglesia[88], completará felizmente en los espíritus de los jóvenes una buena catequesis de las realidades propiamente religiosas, que nunca ha de ser desatendida. La catequesis cobra entonces una importancia considerable, porque es el momento en que el evangelio podrá ser presentado, entendido y aceptado como capaz de dar sentido a la vida y, por consiguiente, de inspirar actitudes de otro modo inexplicables: renuncia, desprendimiento, mansedumbre, justicia, compromiso, reconciliación, sentido de lo Absoluto y de lo invisible, etc., rasgos todos ellos que permitirán identificar entre sus compañeros a este joven como discípulo de Jesucristo.

La catequesis prepara así para los grandes compromisos cristianos de la vida adulta. En lo que se refiere por ejemplo a las vocaciones para la vida sacerdotal y religiosa, es cosa cierta que muchas de ellas han nacido en el curso de una catequesis bien llevada a lo largo de la infancia y de la adolescencia.

Desde la infancia hasta el umbral de la madurez, la catequesis se convierte, pues, en una escuela permanente de la fe y sigue de este modo las grandes etapas de la vida como faro que ilumina la ruta del niño, del adolescente y del joven.

[[catechesi-tradendae-40]]
== Adaptación de la catequesis a los jóvenes

^40^ Es consolador comprobar que, durante la IV Asamblea general del Sínodo y a lo largo de estos años que lo han seguido, la Iglesia ha compartido ampliamente esta preocupación: ¿Cómo impartir la catequesis a los niños y a los jóvenes? ¡Quiera Dios que la atención así despertada perdure mucho tiempo en la conciencia de la Iglesia! En ese sentido, el Sínodo ha sido precioso para la Iglesia entera, al esforzarse por delinear con la mayor precisión posible el rostro complejo de la juventud actual; al mostrar que esta juventud emplea un lenguaje al que es preciso saber traducir, con paciencia y buen sentido, sin traicionarlo, el mensaje de Jesucristo; al demostrar que, a despecho de las apariencias, esta juventud tiene, aunque sea confusamente, no sólo la disponibilidad y la apertura, sino también verdadero deseo de conocer a «Jesús, llamado Cristo»[89]; al revelar, finalmente, que la obra de la catequesis, si se quiere llevar a cabo con rigor y seriedad, es hoy día más ardua y fatigosa que nunca a causa de los obstáculos y dificultades de toda índole con que topa, pero también es más reconfortante que nunca a causa de la hondura de las respuestas que recibe por parte de los niños y de los jóvenes. Ahí hay un tesoro con el que la Iglesia puede y debe contar en los años venideros.

Algunas categorías de jóvenes destinatarios de la catequesis, dada su situación peculiar, postulan también una atención especial.

[[catechesi-tradendae-41]]
== Minusválidos

^41^ Se trata ante todo de los niños y de los jóvenes física o mentalmente minusválidos. Estos tienen derecho a conocer como los demás coetáneos el «misterio de la fe». Al ser mayores las dificultades que encuentran, son más meritorios los esfuerzos de ellos y de sus educadores. Es motivo de alegría comprobar que organizaciones católicas especialmente consagradas a los jóvenes minusválidos tuvieron a bien aportar al Sínodo su experiencia en la materia, y sacaron del Sínodo el deseo renovado de afrontar mejor este importante problema. Merecen ser vivamente alentadas en esta tarea.

[[catechesi-tradendae-42]]
== Jóvenes sin apoyo religioso

^42^ Mi pensamiento se dirige después a los niños y a los jóvenes, cada vez más numerosos, nacidos y educados en un hogar no cristiano, o al menos no practicante, pero deseosos de conocer la fe cristiana. Se les deberá asegurar una catequesis adecuada para que puedan creer en la fe y vivirla progresivamente, a pesar de la falta de apoyo, acaso a pesar de la oposición que encuentren en su familia y en su ambiente.

[[catechesi-tradendae-43]]
== Adultos

^43^ Continuando la serie de destinatarios de la catequesis, no puedo menos de poner de relieve ahora una de las preocupaciones más constantes de los Padres del Sínodo, impuesta con vigor y con urgencia por las experiencias que se están dando en el mundo entero: se trata del problema central de la catequesis de los adultos. Esta es la forma principal de la catequesis porque está dirigida a las personas que tienen las mayores responsabilidades y la capacidad de vivir el mensaje cristiano bajo su forma plenamente desarrollada[90]. La comunidad cristiana no podría hacer una catequesis permanente sin la participación directa y experimentada de los adultos, bien sean ellos destinatarios o promotores de la actividad catequética. El mundo en que los jóvenes están llamados a vivir y dar testimonio de la fe que la catequesis quiere ahondar y afianzar, está gobernado por los adultos: la fe de éstos debería igualmente ser iluminada, estimulada o renovada sin cesar con el fin de penetrar las realidades temporales de las que ellos son responsables. Así pues, para que sea eficaz, la catequesis ha de ser permanente y sería ciertamente vana si se detuviera precisamente en el umbral de la edad madura puesto que, si bien ciertamente de otra forma, se revela no menos necesaria para los adultos.

[[catechesi-tradendae-44]]
== Cuasi catecúmenos

^44^ Entre estos adultos que tienen necesidad de la catequesis, nuestra preocupación pastoral y misionera se dirige a los que, nacidos y educados en regiones todavía no cristianizadas, no han podido profundizar la doctrina cristiana que un día las circunstancias de la vida les hicieron encontrar; a los que en su infancia recibieron una catequesis proporcionada a esa edad, pero que luego se alejaron de toda práctica religiosa y se encuentran en la edad madura con conocimientos religiosos más bien infantiles; a los que se resienten de una catequesis sin duda precoz, pero mal orientada o mal asimilada; a los que, aun habiendo nacido en países cristianos, incluso dentro de un cuadro sociológicamente cristiano, nunca fueron educados en su fe y, en cuanto adultos, son verdaderos catecúmenos.

[[catechesi-tradendae-45]]
== Catequesis diversificadas y complementarias

^45^ Así pues, los adultos de cualquier edad, incluidas las personas de edad avanzada —que merecen atención especial dada su experiencia y sus problemas— son destinatarios de la catequesis igual que los niños, los adolescentes y los jóvenes. Habría que hablar también de los emigrantes, de las personas marginadas por la evolución moderna, de las que viven en las barriadas de las grandes metrópolis, a menudo desprovistas de iglesias, de locales y de estructuras adecuadas. Por todos ellos quiero formular votos a fin de que se multipliquen las iniciativas encaminadas a su formación cristiana con los instrumentos apropiados (medios audio-visuales, publicaciones, mesas redondas, conferencias), de suerte que muchos adultos puedan suplir las insuficiencias o deficiencias de la catequesis, o completar armoniosamente, a un nivel más elevado, la que recibieron en la infancia, o incluso enriquecerse en este campo hasta el punto de poder ayudar más seriamente a los demás.

Con todo, es importante que la catequesis de los niños y de los jóvenes, la catequesis permanente y la catequesis de adultos no sean compartimientos estancos e incomunicados. Más importante aún es que no haya ruptura entre ellas. Al contrario, es menester propiciar su perfecta complementariedad: los adultos tienen mucho que dar a los jóvenes y a los niños en materia de catequesis, pero también pueden recibir mucho de ellos para el crecimiento de su vida cristiana.

Hay que repetirlo: en la Iglesia de Jesucristo nadie debería sentirse dispensado de recibir la catequesis; pensamos incluso en los jóvenes seminaristas y religiosos, y en todos los que están destinados a la tarea de pastores y catequistas, los cuales desempeñarán mucho mejor ese ministerio si saben formarse humildemente en la escuela de la Iglesia, la gran catequista y a la vez la gran catequizada.
