[[catechesi-tradendae-part-6]]
= VI - MÉTODOS Y MEDIOS DE LA CATEQUESIS

[[catechesi-tradendae-46]]
== Medios de comunicación social

^46^ Desde la enseñanza oral de los Apóstoles a las cartas que circulaban entre las Iglesias y hasta los medios más modernos, la catequesis no ha cesado de buscar los métodos y los medios más apropiados a su misión, con la participación activa de las comunidades, bajo impulso de los Pastores Este esfuerzo debe continuar.

Me vienen espontáneamente al pensamiento las grandes posibilidades que ofrecen los medios de comunicación social y los medios de comunicación de grupos: televisión, radio, prensa, discos, cintas grabadas, todo lo audio-visual. Los esfuerzos realizados en estos campos son de tal alcance que pueden alimentar las más grandes esperanzas. La experiencia demuestra, por ejemplo, la resonancia de una enseñanza radiofónica o televisiva, cuando sabe unir una apreciable expresión estética con una rigurosa fidelidad al Magisterio. La Iglesia tiene hoy muchas ocasiones de tratar estos problemas —incluidas las jornadas de los medios de comunicación social—, sin que sea necesario extenderse aquí sobre ello no obstante su capital importancia.

[[catechesi-tradendae-47]]
== Múltiples lugares, momentos o reuniones por valorizar

^47^ Pienso asimismo en diversos momentos de gran importancia en que la catequesis encuentra cabalmente su puesto: por ejemplo, las peregrinaciones diocesanas, regionales o nacionales, que son más provechosas si están centradas en un tema escogido con acierto a partir de la vida de Cristo, de la Virgen y de los Santos; las misiones tradicionales, tantas veces abandonadas con excesiva prisa, y que son insustituibles para una renovación periódica y vigorosa de la vida cristiana —hay que reanudarlas y remozarlas—; los círculos bíblicos, que deben ir más allá de la exégesis para hacer vivir la Palabra de Dios; las reuniones de las comunidades eclesiales de base, en la medida en que se atengan a los criterios expuestos en la Exhortación Apostólica Evangelii nuntiandi[91]. Quiero recordar también los grupos de jóvenes que en ciertas regiones, con denominaciones y fisonomías distintas —mas con el mismo fin de dar a conocer a Jesucristo y de vivir el Evangelio—, se multiplican y florecen como en una primavera muy reconfortante para la Iglesia: grupos de acción católica, grupos caritativos, grupos de oración, grupos de reflexión cristiana, etc. Estos grupos suscitan grandes esperanzas para la Iglesia del mañana. Pero en el nombre de Jesús conjuro a los jóvenes que los forman, a sus responsables y a los sacerdotes que les consagran lo mejor de su ministerio: no permitáis por nada del mundo que en estos grupos, ocasiones privilegiadas de encuentro, ricos en tantos valores de amistad y solidaridad juveniles, de alegría y de entusiasmo, de reflexión sobre los hechos y las cosas, falte un verdadero estudio de la doctrina cristiana. En ese caso se expondrían —y el peligro, por desgracia, se ha verificado sobradamente— a decepcionar a sus miembros y a la Iglesia misma.

El esfuerzo catequético, posible en estos lugares y en otros muchos, tiene tantas más probabilidades de ser acogido y de dar sus frutos, cuanto más se respete su naturaleza propia. Con una inserción apropiada, conseguirá esa diversidad y complementariedad de contactos que le permite desarrollar toda la riqueza de su concepto, mediante la triple dimensión de palabra, de memoria y de testimonio —de doctrina, de celebración y de compromiso en la vida— que el mensaje del Sínodo al Pueblo de Dios ha puesto en evidencia[92].

[[catechesi-tradendae-48]]
== Homilía

^48^ Esta observación vale mas aún para la catequesis que se hace dentro del cuadro litúrgico y concretamente en la asamblea litúrgica: respetando lo específico y el ritmo propio de este cuadro, la homilía vuelve a recorrer el itinerario de fe propuesto por la catequesis y lo conduce a su perfeccionamiento natural; al mismo tiempo impulsa a los discípulos del Señor a emprender cada día su itinerario espiritual en la verdad, la adoración y la acción de gracias. En este sentido se puede decir que la pedagogía catequética encuentra, a su vez, su fuente y su plenitud en la eucaristía dentro del horizonte completo del año litúrgico. La predicación centrada en los textos bíblicos, debe facilitar entonces, a su manera, el que los fieles se familiaricen con el conjunto de los misterios de la fe y de las normas de la vida cristiana. Hay que prestar una gran atención a la homilía: ni demasiado larga, ni demasiado breve, siempre cuidadosamente preparada, sustanciosa y adecuada, y reservada a los ministros autorizados. Esta homilía debe tener su puesto en toda eucaristía dominical o festiva, y también en la celebración de los bautismos, de las liturgias penitenciales, de los matrimonios, de los funerales. Es éste uno de los beneficios de la renovada liturgia.

[[catechesi-tradendae-49]]
== Publicaciones catequéticas

^49^ En medio de este conjunto de vías y de medios —toda actividad de la Iglesia tiene una dimensión catequética— las obras de catecismo, lejos de perder su importancia esencial, adquieren nuevo relieve. Uno de los aspectos más interesantes del florecimiento actual de la catequesis consiste en la renovación y multiplicación de los libros catequéticos que en la Iglesia se ha verificado un poco por doquier. Han visto la luz obras numerosas y muy logradas, y constituyen una verdadera riqueza al servicio de la enseñanza catequética. Pero hay que reconocer igualmente, con honradez y humildad, que esta floración y esta riqueza han llevado consigo ensayos y publicaciones equívocas y perjudiciales para los jóvenes y para la vida de la Iglesia. Bastante a menudo, aquí y allá, con el fin de encontrar el lenguaje más apto o de estar al día en lo que atañe a los métodos pedagógicos, ciertas obras catequéticas desorientan a los jóvenes y aun a los adultos, ya por la omisión, consciente o inconsciente, de elementos esenciales a la fe de la Iglesia, ya por la excesiva importancia dada a determinados temas con detrimento de los demás, ya sobre todo por una visión global harto horizontalista, no conforme con la enseñanza del Magisterio de la Iglesia.

No basta, por tanto, que se multipliquen las obras catequéticas. Para que respondan a su finalidad, son indispensables algunas condiciones:

- que conecten con la vida concreta de la generación a la que se dirigen, teniendo bien presentes sus inquietudes y sus interrogantes, sus luchas y sus esperanzas;
- que se esfuercen por encontrar el lenguaje que entiende esa generación;
- que se propongan decir todo el mensaje de Cristo y de su Iglesia, sin pasar por alto ni deformar nada, exponiéndolo todo según un eje y una estructura que hagan resaltar lo esencial;
- que tiendan realmente a producir en sus usuarios un conocimiento mayor de los misterios de Cristo en orden a una verdadera conversión y a una vida más conforme con el querer de Dios.

[[catechesi-tradendae-50]]
== Catecismos

^50^ Todos los que asumen la pesada tarea de preparar estos instrumentos catequéticos, y con mayor razón el texto de los catecismos, no pueden hacerlo sin la aprobación de los Pastores que tienen autoridad para darla, ni sin inspirarse lo más posible en el Directorio general de Catequesis que sigue siendo norma de referencia[93].

A este respecto, no puedo menos de animar fervientemente a las Conferencias episcopales del mundo entero: que emprendan, con paciencia pero también con firme resolución, el imponente trabajo a realizar de acuerdo con la Sede Apostólica, para lograr catecismos fieles a los contenidos esenciales de la Revelación y puestos al día en lo que se refiere al método, capaces de educar en una fe robusta a las generaciones cristianas de los tiempos nuevos.

Esta breve mención a los medios y a las vías de la catequesis contemporánea no agota la riqueza de las proposiciones elaboradas por los Padres del Sínodo. Es reconfortante pensar que en cada país se realiza actualmente una preciosa colaboración para una renovación más orgánica y más segura de estos aspectos de la catequesis. ¿Cómo es posible dudar de que la Iglesia pueda encontrar personas competentes y medios adaptados para responder, con la gracia de Dios, a las exigencias complejas de la comunicación con los hombres de nuestro tiempo?
