:fn-94: footnote:[AAS 71 (1979), p. 607.]
:fn-95: footnote:[Cf. Rom 16, 25; Ef 3, 5.]
:fn-96: footnote:[Cf. 1 Co 1, 17.]
:fn-97: footnote:[Cf. 2 Tim 1, 14.]
:fn-98: footnote:[Cf. Jn 1, 16; Ef 1, 10.]

[[catechesi-tradendae-part-7]]
= VII - CÓMO DAR LA CATEQUESIS

[[catechesi-tradendae-51]]
== Diversidad de métodos

^51^ La edad y el desarrollo intelectual de los cristianos, su grado de madurez eclesial y espiritual y muchas otras circunstancias personales postulan que la catequesis adopte métodos muy diversos para alcanzar su finalidad específica: la educación en la fe. Esta variedad es requerida también, en un plano más general, por el medio socio-cultural en que la Iglesia lleva a cabo su obra catequética.

La variedad en los métodos es un signo de vida y una riqueza. Así lo han considerado los Padres de la IV Asamblea general del Sínodo, llamando la atención sobre las condiciones indispensables para que sea útil y no perjudique a la unidad de la enseñanza de la única fe.

[[catechesi-tradendae-52]]
== Al servicio de la Revelación y de la conversión

^52^ La primera cuestión de orden general que se presenta concierne el riesgo y la tentación de mezclar indebidamente la enseñanza catequética con perspectivas ideológicas, abierta o larvadamente, sobre todo de índole político-social, o con opciones políticas personales. Cuando estas perspectivas predominan sobre el mensaje central que se ha de transmitir, hasta oscurecerlo y relegarlo a un plano secundario, incluso hasta utilizarlo para sus fines, entonces la catequesis queda desvirtuada en sus raíces. E1 Sínodo ha insistido con razón en la necesidad de que la catequesis se mantenga por encima de las tendencias unilaterales divergentes —de evitar las «dicotomías»— aun en el campo de las interpretaciones teológicas dadas a tales cuestiones. La pauta que ha de procurar seguir es la Revelación, tal como la transmite el Magisterio universal de la Iglesia en su forma solemne u ordinaria. Esta Revelación es la de un Dios creador y redentor, cuyo Hijo, habiendo venido entre los hombres hecho carne, no sólo entra en la historia personal de cada hombre, sino también en la historia humana, convirtiéndose en su centro. Esta es, por tanto, la Revelación de un cambio radical del hombre y del universo, de todo lo que forma el tejido de la existencia humana, bajo la influencia de la Buena Nueva de Jesucristo. Una catequesis así entendida supera todo moralismo formalista, aun cuando incluya una verdadera moral cristiana. Supera principalmente todo mesianismo temporal, social o político. Apunta a alcanzar el fondo del hombre.

[[catechesi-tradendae-53]]
== Encarnación del mensaje en las culturas

^53^ Abordo ahora una segunda cuestión. Como decía recientemente a los miembros de la Comisión bíblica, «el término "aculturación" o "inculturación", además de ser un hermoso neologismo, expresa muy bien uno de los componentes del gran misterio de la Encarnación»{fn-94}. De la catequesis como de la evangelización en general, podemos decir que está llamada a llevar la fuerza del evangelio al corazón de la cultura y de las culturas. Para ello, la catequesis procurará conocer estas culturas y sus componentes esenciales; aprenderá sus expresiones más significativas, respetará sus valores y riquezas propias. Sólo así se podrá proponer a tales culturas el conocimiento del misterio oculto{fn-95} y ayudarles a hacer surgir de su propia tradición viva expresiones originales de vida, de celebración y de pensamiento cristianos. Se recordará a menudo dos cosas:

- por una parte, el Mensaje evangélico no se puede pura y simplemente aislarlo de la cultura en la que está inserto desde el principio (el mundo bíblico y, más concretamente, el medio cultural en el que vivió Jesús de Nazaret); ni tampoco, sin graves pérdidas, podrá ser aislado de las culturas en las que ya se ha expresado a lo largo de los siglos; dicho Mensaje no surge de manera espontánea en ningún «humus» cultural; se transmite siempre a través de un diálogo apostólico que está inevitablemente inserto en un cierto diálogo de culturas;
- por otra parte, la fuerza del Evangelio es en todas partes transformadora y regeneradora. Cuando penetra una cultura ¿quién puede sorprenderse de que cambien en ella no pocos elementos? No habría catequesis si fuese el Evangelio el que hubiera de cambiar en contacto con las culturas.

En ese caso ocurría sencillamente lo que san Pablo llama, con una expresión muy fuerte, «reducir a nada la cruz de Cristo»{fn-96}.

Otra cosa sería tomar como punto de arranque, con prudencia y discernimiento, elementos —religiosos o de otra índole— que forman parte del patrimonio cultural de un grupo humano para ayudar a las personas a entender mejor la integridad del misterio cristiano. Los catequistas auténticos saben que la catequesis «se encarna» en las diferentes culturas y ambientes: baste pensar en la diversidad tan grande de los pueblos, en los jóvenes de nuestro tiempo, en las circunstancias variadísimas en que hoy día se encuentran las gentes; pero no aceptan que la catequesis se empobrezca por abdicación o reducción de su mensaje, por adaptaciones, aun de lenguaje, que comprometan el «buen depósito» de la fe{fn-97}, o por concesiones en materia de fe o de moral; están convencidos de que la verdadera catequesis acaba por enriquecer a esas culturas, ayudándolas a superar los puntos deficientes o incluso inhumanos que hay en ellas y comunicando a sus valores legítimos la plenitud de Cristo{fn-98}.

[[catechesi-tradendae-54]]
== Aportación de las devociones populares

^54^ Otra cuestión de método concierne a la valorización, mediante la enseñanza catequética, de los elementos válidos de la piedad popular. Pienso en las devociones que en ciertas regiones practica el pueblo fiel con un fervor y una rectitud de intención conmovedores, aun cuando en muchos aspectos haya que purificar, o incluso rectificar, la fe en que se apoyan. Pienso en ciertas oraciones fáciles de entender y que tantas gentes sencillas gustan de repetir. Pienso en ciertos actos de piedad practicados con deseo sincero de hacer penitencia o de agradar al Señor. En la mayor parte de esas oraciones o de esas prácticas, junto a elementos que se han de eliminar, hay otros que, bien utilizados, podrían servir muy bien para avanzar en el conocimiento del misterio de Cristo o de su mensaje: el amor y la misericordia de Dios, la Encarnación de Cristo, su cruz redentora y su resurrección, la acción del Espíritu en cada cristiano y en la Iglesia, el misterio del más allá, la práctica de las virtudes evangélicas, la presencia del cristiano en el mundo, etc. Y ¿por qué motivo íbamos a tener que utilizar elementos no cristianos —incluso anticristianos— rehusando apoyarnos en elementos que, aun necesitando revisión y rectificación, tienen algo cristiano en su raíz?

[[catechesi-tradendae-55]]
== Memorización

^55^ La última cuestión metodológica que conviene al menos subrayar —más de una vez se hizo alusión a ella en el Sínodo— es la memorización. Los comienzos de la catequesis cristiana, que coincidieron con una civilización eminentemente oral, recurrieron muy ampliamente a la memorización. Y la catequesis ha conocido una larga tradición de aprendizaje por la memoria de las principales verdades. Todos sabemos que este método puede presentar ciertos inconvenientes: no es el menor el de prestarse a una asimilación insuficiente, a veces casi nula, reduciéndose todo el saber a fórmulas que se repiten sin haber calado en ellas. Estos inconvenientes, unidos a las características diversas de nuestra civilización, han llevado aquí o allí a la supresión casi total —definitiva, por desgracia, según algunos— de la memorización en la catequesis. Y sin embargo, con ocasión de la IV Asamblea general del Sínodo, se han hecho oír voces muy autorizadas para reequilibrar con buen criterio la parte de la reflexión y de la espontaneidad, del diálogo y del silencio, de los trabajos escritos y de la memoria. Por otra parte, determinadas culturas tienen en gran aprecio la memorización.

¿Por qué, mientras en la enseñanza profana de ciertos países se elevan críticas cada vez más numerosas contra las lamentables consecuencias que se siguen del menosprecio de esa facultad humana que es la memoria, por qué no tratar de revalorizarla en la catequesis de manera inteligente y aún original, tanto más cuanto la celebración o «memoria» de los grandes acontecimientos de la historia de la salvación exige que se tenga un conocimiento preciso? Una cierta memorización de las palabras de Jesús, de pasajes bíblicos importantes, de los diez mandamientos, de fórmulas de profesión de fe, de textos litúrgicos, de algunas oraciones esenciales, de nociones-clave de la doctrina..., lejos de ser contraria a la dignidad de los jóvenes cristianos, o de constituir un obstáculo para el diálogo personal con el Señor, es una verdadera necesidad, como lo han recordado con vigor los Padres sinodales. Hay que ser realistas. Estas flores, por así decir, de la fe y de la piedad no brotan en los espacios desérticos de una catequesis sin memoria. Lo esencial es que esos textos memorizados sean interiorizados y entendidos progresivamente en su profundidad, para que sean fuente de vida cristiana personal y comunitaria.

La pluralidad de métodos en la catequesis contemporánea puede ser signo de vitalidad y de ingeniosidad. En todo caso, conviene que el método escogido se refiera en fin de cuentas a una ley fundamental para toda la vida de la Iglesia: la fidelidad a Dios y la fidelidad al hombre, en una misma actitud de amor.
