:fn-99: footnote:[Cf. Enc. Redemptor Hominis, nn. 15-16: AAS 71 (1979), pp, 286-295.]
:fn-100: footnote:[Cf. Mt 5, 13-16.]
:fn-101: footnote:[Cf. Pablo VI, Enc. Ecclesiam suam, III parte: AAS 56 (1964), pp. 637-659.]
:fn-102: footnote:[Cf. Heb 11, 27.]
:fn-103: footnote:[1 Co 13, 12.]
:fn-104: footnote:[Cf. 1 Tim 6, 16.]
:fn-105: footnote:[Heb 11, 1.]
:fn-106: footnote:[Cf. Mt 2, 1 ss.]
:fn-107: footnote:[Blas Pascal, El misterio de Jesús: Pensamientos, n. 553.]
:fn-108: footnote:[Pablo VI, Sollemnis Professio Fidei, n. 4: AAS 60 (1968), P. 434.]
:fn-109: footnote:[Pablo VI, Exhort. Ap. Quinque iam Anni: AAS 63 (1971), P. 99.]
:fn-110: footnote:[Cf. 1 Tim 1, 3 ss.; 4, 1 ss.; 2 Tim 2, 14 ss.; 4, 1-5; Tit 1, 10-12; cf. también Exhort. Ap. Evangelii nuntiandi, n. 78: AAS 68 (1976), p. 70.]
:fn-111: footnote:[Enc. Redemptor Hominis, n. 10: AAS 71 (1979), p. 274.]

[[catechesi-tradendae-part-8]]
= VIII - LA ALEGRÍA DE LA FE EN UN MUNDO DIFÍCIL

[[catechesi-tradendae-56]]
== Afirmar la identidad cristiana...

^56^ Vivimos en un mundo difícil donde la angustia de ver que las mejores realizaciones del hombre se le escapan y se vuelven contra él{fn-99}, crea un clima de incertidumbre. Es en este mundo donde la catequesis debe ayudar a los cristianos a ser, para su gozo y para el servicio de todos, «luz» y «sal»{fn-100}. Ello exige que la catequesis les dé firmeza en su propia identidad y que se sobreponga sin cesar a las vacilaciones, incertidumbres y desazones del ambiente. Entre otras muchas dificultades, que son otros tantos desafíos para la fe, pongo de relieve algunas para ayudar a la catequesis a superarlas.

[[catechesi-tradendae-57]]
== ... en un mundo indiferente ...

^57^ Se hablaba mucho, hace algunos años, de un mundo secularizado, de una era postcristiana. La moda pasa... Pero permanece una realidad profunda. Los cristianos de hoy deben ser formados para vivir en un mundo que ampliamente ignora a Dios o que, en materia religiosa, en lugar de un diálogo exigente y fraterno, estimulante para todos, cae muy a menudo en un indiferentismo nivelador, cuando no se queda en una actitud menospreciativa de «suspicacia» en nombre de sus progresos en materia de «explicaciones» científicas. Para «entrar» en este mundo, para ofrecer a todos un «diálogo de salvación»{fn-101} donde cada uno se siente respetado en su dignidad fundamental, la de buscador de Dios, tenemos necesidad de una catequesis que enseñe a los jóvenes y a los adultos de nuestras comunidades a permanecer lúcidos y coherentes en su fe, a afirmar serenamente su identidad cristiana y católica, a «ver lo invisible»{fn-102} y a adherirse de tal manera al absoluto de Dios que puedan dar testimonio de Él en una civilización materialista que lo niega.

[[catechesi-tradendae-58]]
== ... con la pedagogía original de la fe

^58^ La originalidad irreductible de la identidad cristiana tiene como corolario y condición una pedagogía no menos original de la fe. Entre las numerosas y prestigiosas ciencias del hombre que han progresado enormemente en nuestros días, la pedagogía es ciertamente una de las más importantes. Las conquistas de las otras ciencias —biología, psicología, sociología— le ofrecen aportaciones preciosas. La ciencia de la educación y el arte de enseñar son objeto de continuos replanteamientos con miras a una mejor adaptación o a una mayor eficacia, con resultados por lo demás desiguales.

Pues bien, también hay una pedagogía de la fe y nunca se ponderará bastante lo que ésta puede hacer en favor de la catequesis. En efecto, es cosa normal adaptar, en beneficio de la educación en la fe, las técnicas perfeccionadas y comprobadas de la educación en general. Sin embargo es importante tener en cuenta en todo momento la originalidad fundamental de la fe. Cuando se habla de pedagogía de la fe, no se trata de transmitir un saber humano, aun el más elevado; se trata de comunicar en su integridad la Revelación de Dios. Ahora bien, Dios mismo, a lo largo de toda la historia sagrada y principalmente en el Evangelio, se sirvió de una pedagogía que debe seguir siendo el modelo de la pedagogía de la fe. En catequesis, una técnica tiene valor en la medida en que se pone al servicio de la fe que se ha de transmitir y educar, en caso contrario, no vale.

[[catechesi-tradendae-59]]
== Lenguaje adaptado al servicio del Credo

^59^ Un problema, próximo al anterior es el del lenguaje. Todos saben la candente actualidad de este tema. ¿No es paradójico constatar también que los estudios contemporáneos, en el campo de la comunicación, de la semántica y de la ciencia de los símbolos, por ejemplo, dan una importancia notable al lenguaje; mas, por otra parte, el lenguaje es utilizado abusivamente hoy al servicio de la mistificación ideológica, de la masificación del pensamiento y de la reducción del hombre al estado de objeto?

Todo eso influye notablemente en el campo de la catequesis. En efecto, ésta tiene el deber imperioso de encontrar el lenguaje adaptado a los niños y a los jóvenes de nuestro tiempo en general, y a otras muchas categorías de personas: lenguaje de los estudiantes, de los intelectuales, de los hombres de ciencia; lenguaje de los analfabetos o de las personas de cultura primitiva; lenguaje de los minusválidos, etc. San Agustín se encontró ya con ese problema y contribuyó a resolverlo para su época con su famosa obra De catechizandis rudibus. Tanto en catequesis como en teología, el tema del lenguaje es sin duda alguna primordial. Pero no está de más recordarlo aquí: la catequesis no puede aceptar ningún lenguaje que, bajo el pretexto que sea, aun supuestamente científico, tenga como resultado desvirtuar el contenido del Credo. Tampoco es admisible un lenguaje que engañe o seduzca. Al contrario, la ley suprema es que los grandes progresos realizados en el campo de la ciencia del lenguaje han de poder ser utilizados por la catequesis para que ésta pueda «decir» o «comunicar» más fácilmente al niño, al adolescente, a los jóvenes y a los adultos de hoy todo su contenido doctrinal sin deformación.

[[catechesi-tradendae-60]]
== Búsqueda y certeza de la fe

^60^ Un desafío muy sutil viene algunas veces del modo mismo de entender la fe. Ciertas escuelas filosóficas contemporáneas, que parecen ejercer gran influencia en algunas corrientes teológicas y, a través de ellas, en la práctica pastoral, acentúan de buen grado, que la actitud humana fundamental es la de una búsqueda sin fin, una búsqueda que no alcanza nunca su objeto. En teología, este modo de ver las cosas afirmará muy categóricamente que la fe no es una certeza sino un interrogante, no es una claridad sino un salto en la oscuridad.

Estas corrientes de pensamiento, no cabe duda, tienen la ventaja de recordarnos que la fe dice relación a cosas que no se poseen todavía, puesto que se las espera, que todavía no se ven más que «en un espejo y obscuramente»{fn-103}, y que Dios habita una luz inaccesible{fn-104}. Nos ayudan a no hacer de la fe cristiana una actitud de instalado, sino una marcha hacia adelante, como la de Abrahán. Con mayor razón conviene evitar el presentar como ciertas las cosas que no lo son.

Con todo, no hay que caer en el extremo opuesto, como sucede con demasiada frecuencia. La misma carta a los Hebreos dice que «la fe es la garantía de las cosas que se esperan, la prueba de las realidades que no se ven»{fn-105} Si no tenemos la plena posesión, tenemos una garantía y una prueba. En la educación de los niños, de los adolescentes y de los jóvenes, no les demos un concepto totalmente negativo de la fe —como un no-saber absoluto, una especie de ceguera, un mundo de tinieblas—, antes bien, sepamos mostrarles que la búsqueda humilde y valiente del creyente, lejos de partir de la nada, de meras ilusiones, de opiniones falibles y de incertidumbres, se funda en la Palabra de Dios que ni se engaña ni engaña, y se construye sin cesar sobre la roca inamovible de esa Palabra. Es la búsqueda de los Magos a merced de una estrella{fn-106}, búsqueda a propósito de la cual Pascal, recogiendo un pensamiento de san Agustín escribía en términos muy profundos: «No me buscarías si no me hubieras encontrado»{fn-107}.

Finalidad de la catequesis es también dar a los jóvenes catecúmenos aquellas certezas, sencillas pero sólidas, que les ayuden a buscar, cada vez más y mejor, el conocimiento del Señor.

[[catechesi-tradendae-61]]
== Catequesis y teología

^61^ En este contexto, me parece importante que se comprenda bien la correlación existente entre catequesis y teología.

Esta correlación es evidentemente profunda y vital para quien comprende la misión irreemplazable de la teología al servicio de la fe. Nada tiene de extraño que toda conmoción en el campo de la teología provoque repercusiones igualmente en el terreno de la catequesis. Ahora bien, en este inmediato post-concilio, la Iglesia vive un momento importante pero arriesgado de investigación teológica. Y lo mismo habría que decir de la hermenéutica en exégesis.

Padres Sinodales provenientes de todos los continentes han abordado la cuestión con un lenguaje muy neto: han hablado de un «equilibrio inestable» que amenaza con pasar de la teología a la catequesis, y han señalado la necesidad de atajar este mal. El Papa Pablo VI había abordado personalmente el problema, con términos no menos netos, en la introducción a su solemne Profesión de Fe{fn-108} y en la Exhortación Apostólica que conmemoró el V aniversario de la clausura del Concilio Vaticano II{fn-109}.

Conviene insistir nuevamente en este punto. Conscientes de la influencia que sus investigaciones y afirmaciones ejercen en la enseñanza catequética, los teólogos y los exegetas tienen el deber de estar muy atentos para no hacer pasar por verdades ciertas lo que, por el contrario, pertenece al ámbito de las cuestiones opinables o discutidas entre expertos. Los catequistas tendrán a su vez el buen criterio de recoger en el campo de la investigación teológica lo que pueda iluminar su propia reflexión y su enseñanza, acudiendo como los teólogos a las verdaderas fuentes, a la luz del Magisterio. Se abstendrán de turbar el espíritu de los niños y de los jóvenes, en esa etapa de su catequesis, con teorías extrañas, problemas fútiles o discusiones estériles, muchas veces fustigadas por san Pablo en sus cartas pastorales{fn-110}.

El don más precioso que la Iglesia puede ofrecer al mundo de hoy, desorientado e inquieto, es el formar unos cristianos firmes en lo esencial y humildemente felices en su fe. La catequesis les enseñará esto y desde el principio sacará su provecho: «El hombre que quiere comprenderse hasta el fondo a sí mismo —no solamente según criterios y medidas del propio ser inmediatos, parciales, a veces superficiales e incluso aparentes— debe, con su inquietud, incertidumbre e incluso con su debilidad y pecaminosidad, con su vida y con su muerte acercarse a Cristo. Debe, por decirlo así, entrar en Él con todo su ser, debe "apropiarse" y asimilar toda la realidad de la Encarnación y de la Redención para encontrarse a sí mismo»{fn-111}.