:fn-112: footnote:[Cf. De catechizandis rudibus: PL 40, 310-347.]
:fn-113: footnote:[Cf. Decr. sobre el oficio pastoral de los Obispos Christus Dominus, n. 14: AAS 58 ( 1966), p. 679.]
:fn-114: footnote:[Decr. sobre el ministerio y vida de los presbíteros Presbyterorum Ordinis, n. 6: AAS 58 (1966), p. 999.]
:fn-115: footnote:[Lam 4, 4.]
:fn-116: footnote:[Ef 4, 5 s.]
:fn-117: footnote:[Cf. Conc. Ecum. Vat. II, Const. sobre la sagrada liturgia Sacrosanctum Concilium, nn. 35, 52: AAS 56 (1964), pp. 109, 114; cf. también Institutio generalis Missalis Romani promulgada por decreto de la S. Congregación de Ritos el 6 abril 1969, n. 33, y lo que se ha dicho más arriba en el cap. VI sobre la homilía.]
:fn-118: footnote:[Desde la alta edad media, los Concilios provinciales insistían sobre la responsabilidad de los padres en materia de educación de la fe: cf. VI Concilio de Arlés (a. 813), can. 19; Concilio de Maguncia (a. 813), cann. 45-47; VI Concilio de París (a. 829), libro I, cap. 7: Mansi, Sacrorum Conciliorum nova et amplissima collectio, XIV, 62, 74, 542. Entre los documentos más recientes del Magisterio, conviene citar la Enc. Divini illius Magistri de Pío XI, 31 diciembre 1929: AAS 22 (1930), pp. 49-86; muchos discursos y mensajes de Pío XII; y sobre todo los textos del Concilio Vaticano II: Const. dogm. sobre la Iglesia Lumen gentium, nn. 11, 35:AAS 57 (1965), pp. 15, 40, Decr. sobre el apostolado de los seglares Apostolicam Actuositatem, nn. 11, 30: AAS 58 (1966), pp. 847-860, Const. past. sobre la Iglesia en el mundo actual Gaudium et spes, n. 52: AAS 58 (1966), p. 1073; y especialmente la Decl. sobre la educación cristiana de la juventud Gravissimum Educationis, n. 3: AAS 58 (1966), p. 731.]
:fn-119: footnote:[Cf. Conc. Ecum. Vat. II, Decl. sobre la educación cristiana de la juventud Gravissimum Educationis, n. 3: AAS 58 (1966), p. 731.]
:fn-120: footnote:[Conc. Ecum. Vat. II, Const dogm. sobre la Iglesia Lumen gentium, n. 11:AAS 57 (1965), p. 16; cf. Decr. sobre el apostolado de los seglares Apostolicam Actuositatem, n. 11: AAS 58 (1966), p 848.]
:fn-121: footnote:[Exhort. Ap. Evangelii nuntiandi, n. 77: AAS 68 (1967),]

[[catechesi-tradendae-part-9]]
= IX - LA TAREA NOS CONCIERNE A TODOS

[[catechesi-tradendae-62]]
== Aliento a todos los responsables

^62^ Ahora, Hermanos e Hijos queridísimos, quisiera que mis palabras, concebidas como una grave y ardiente exhortación de mi ministerio de Pastor de la Iglesia universal, enardecieran vuestros corazones a la manera de las cartas de san Pablo a sus compañeros de Evangelio Tito y Timoteo, a la manera de san Agustín cuando escribía al diácono Deogracias, desalentado sobre el gozo de catequizar{fn-112}. ¡Sí, quiero sembrar pródigamente en el corazón de todos los responsables, tan numerosos y diversos, de la enseñanza religiosa y del adiestramiento en la vida según el Evangelio, el valor, la esperanza y el entusiasmo!

[[catechesi-tradendae-63]]
== Obispos

^63^ Me dirijo ante todo a vosotros, mis Hermanos Obispos: el Concilio Vaticano II ya os recordó explícitamente vuestra tarea en el campo catequético{fn-113}, y los Padres de la IV Asamblea general del Sínodo lo subrayaron expresamente.

En el campo de la catequesis tenéis vosotros, queridísimos Hermanos, una misión particular en vuestras Iglesias: en ellas sois los primeros responsables de la catequesis, los catequistas por excelencia. Lleváis también con el Papa en el espíritu de la colegialidad episcopal, el peso de la catequesis en la Iglesia entera. Permitid, pues que os hable con el corazón en la mano.

Sé que el ministerio episcopal que tenéis encomendado es cada día más complejo y abrumador. Os requieren mil compromisos, desde la formación de nuevos sacerdotes, a la presencia activa en medio de las comunidades de fieles, desde la celebración viva y digna del culto y de los sacramentos, a la solicitud por la promoción humana y por la defensa de los derechos del hombre. Pues bien, ¡que la solicitud por promover una catequesis activa y eficaz no ceda en nada a cualquier otra preocupación. Esta solicitud os llevará a transmitir personalmente a vuestros fieles la doctrina de vida. Pero debe llevaros también a haceros cargo en vuestras diócesis, en conformidad con los planes de la Conferencia episcopal a la que pertenecéis, de la alta dirección de la catequesis, rodeándoos de colaboradores competentes y dignos de confianza. Vuestro cometido principal consistirá en suscitar y mantener en vuestras Iglesias una verdadera mística de la catequesis, pero una mística que se encarne en una organización adecuada y eficaz, haciendo uso de las personas, de los medios e instrumentos, así como de los recursos necesarios. Tened la seguridad de que, si funciona bien la catequesis en las Iglesias locales, todo el resto resulta más fácil. Por lo demás —¿hace falta decíroslo?— vuestro celo os impondrá eventualmente la tarea ingrata de denunciar desviaciones y corregir errores, pero con mucha mayor frecuencia os deparará el gozo y el consuelo de proclamar la sana doctrina y de ver cómo florecen vuestras Iglesias gracias a la catequesis impartida como quiere el Señor.

[[catechesi-tradendae-64]]
== Sacerdotes

^64^ En cuanto a vosotros, sacerdotes, aquí tenéis un campo en el que sois los colaboradores inmediatos de vuestros Obispos. El Concilio os ha llamado «educadores de la fe»{fn-114}: ¿Cómo serlo más cabalmente que dedicando lo mejor de vuestros esfuerzos al crecimiento de vuestras comunidades en la fe? Lo mismo si tenéis un cargo parroquial que si sois capellanes en una escuela, instituto o universidad, si sois responsables de la pastoral a cualquier nivel o animadores de pequeñas o grandes comunidades, pero sobre todo de grupos de jóvenes, la Iglesia espera de vosotros que no dejéis nada por hacer con miras a una obra catequética bien estructurada y bien orientada. Los diáconos y demás ministros que pueda haber en torno vuestro son vuestros cooperadores natos. Todos los creyentes tienen derecho a la catequesis; todos los pastores tienen el deber de impartirla. A las autoridades civiles pediremos siempre que respeten la libertad de la enseñanza catequética; a vosotros, ministros de Jesucristo, os suplico con todas mis fuerzas: no permitáis que, por una cierta falta de celo, como consecuencia de alguna idea inoportuna, preconcebida, los fieles se queden sin catequesis. Que no se pueda decir: «los pequeñuelos piden pan y no hay quien se lo parta»{fn-115}.

[[catechesi-tradendae-65]]
== Religiosos y religiosas

^65^ Muchas familias religiosas masculinas y femeninas nacieron para la educación cristiana de los niños y de los jóvenes, principalmente los más abandonados. En el decurso de la historia, los religiosos y las religiosas se han encontrado muy comprometidos en la actividad catequética de la Iglesia, llevando a cabo un trabajo particularmente idóneo y eficaz. En un momento en que se quiere intensificar los vínculos entre los religiosos y los pastores y, en consecuencia, la presencia activa de las comunidades religiosas y de sus miembros en los proyectos pastorales de las Iglesias locales, os exhorto de todo corazón a vosotros, que en virtud de la consagración religiosa debéis estar aún más disponibles para servir a la Iglesia, a prepararos lo mejor posible para la tarea catequética, según las distintas vocaciones de vuestros institutos y las misiones que os han sido confiadas, llevando a todas partes esta preocupación. ¡Que las comunidades dediquen el máximo de sus capacidades y de sus posibilidades a la obra específica de la catequesis!

[[catechesi-tradendae-66]]
== Catequistas laicos ...

^66^ En nombre de toda la Iglesia quiero dar las gracias a vosotros, catequistas parroquiales, hombres y, en mayor número aún, mujeres, que en todo el mundo os habéis consagrado a la educación religiosa de numerosas generaciones de niños. Vuestra actividad, con frecuencia humilde y oculta, mas ejercida siempre con celo ardiente y generoso, es una forma eminente de apostolado seglar, particularmente importante allí donde, por distintas razones, los niños y los jóvenes no reciben en sus hogares una formación religiosa conveniente. En efecto, ¿cuántos de nosotros hemos recibido de personas como vosotros las primeras nociones de catecismo y la preparación para el sacramento de la reconciliación, para la primera comunión y para la confirmación? La IV Asamblea general del Sínodo no os ha olvidado. Con ella os animo a proseguir vuestra colaboración en la vida de la Iglesia.

Pero el título de «catequista» se aplica por excelencia a los catequistas de tierras de misión. Habiendo nacido en familias ya cristianas o habiéndose convertido un día al cristianismo e instruidos por los misioneros o por otros catequistas, consagran luego su vida, durante largos años, a catequizar a los niños y adultos de sus países. Sin ellos no se habrían edificado Iglesias hoy día florecientes. Me alegro de los esfuerzos realizados por la S. Congregación para la Evangelización de los Pueblos con miras a perfeccionar cada vez más la formación de esos catequistas. Evoco con reconocimiento la memoria de aquellos a quienes el Señor llamó ya a Sí. Pido la intercesión de aquellos a quienes mis predecesores elevaron a la gloria de los altares. Aliento de todo corazón a los que ahora están entregados a esa obra. Deseo que otros muchos los releven y que su número se acreciente en favor de una obra tan necesaria para la misión.

[[catechesi-tradendae-67]]
== ... en parroquia ...

^67^ Quiero evocar ahora el marco concreto en que actúan habitualmente todos estos catequistas, volviendo todavía de manera más sintética sobre los «lugares» de la catequesis, algunos de los cuales han sido ya evocados en el capítulo VI: parroquia, familia, escuela y movimiento.

Aunque es verdad que se puede catequizar en todas partes, quiero subrayar —conforme al deseo de muchísimos Obispos— que la comunidad parroquial debe seguir siendo la animadora de la catequesis y su lugar privilegiado. Ciertamente, en muchos países, la parroquia ha sido como sacudida por el fenómeno de la urbanización. Algunos quizás han aceptado demasiado fácilmente que la parroquia sea considerada como sobrepasada, si no destinada a la desaparición en beneficio de pequeñas comunidades más adaptadas y más eficaces. Quiérase o no, la parroquia sigue siendo una referencia importante para el pueblo cristiano, incluso para los no practicantes. El realismo y la cordura piden pues continuar dando a la parroquia, si es necesario, estructuras más adecuadas y sobre todo un nuevo impulso gracias a la integración creciente de miembros cualificados, responsables y generosos. Dicho esto, y teniendo en cuenta la necesaria diversidad de lugares de catequesis, en la misma parroquia, en las familias que acogen a niños o adolescentes, en las capellanías de las escuelas estatales, en las instituciones escolares católicas, en los movimientos de apostolado que conservan unos tiempos catequéticos, en centros abiertos a todos los jóvenes, en fines de semana de formación espiritual, etc., es muy conveniente que todos estos canales catequéticos converjan realmente hacia una misma confesión de fe, hacia una misma pertenencia a la Iglesia, hacia unos compromisos en la sociedad vividos en el mismo espíritu evangélico: «... un solo Señor, una sola fe, un solo bautismo, un solo Dios y Padre...»{fn-116}.Por esto, toda parroquia importante y toda agrupación de parroquias numéricamente más reducidas tienen el grave deber de formar responsables totalmente entregados a la animación catequética —sacerdotes, religiosos, religiosas y seglares—, de prever el equipamiento necesario para una catequesis bajo todos sus aspectos, de multiplicar y adaptar los lugares de catequesis en la medida que sea posible y útil, de velar por la cualidad de la formación religiosa y por la integración de distintos grupos en el cuerpo eclesial.

En una palabra, sin monopolizar y sin uniformar, la parroquia sigue siendo, como he dicho, el lugar privilegiado de la catequesis. Ella debe encontrar su vocación, el ser una casa de familia, fraternal y acogedora, donde los bautizados y los confirmados toman conciencia de ser pueblo de Dios. Allí, el pan de la buena doctrina y el pan de la Eucaristía son repartidos en abundancia en el marco de un solo acto de culto{fn-117}; desde allí son enviados cada día a su misión apostólica en todas las obras de la vida del mundo.

[[catechesi-tradendae-68]]
== ... en familia ...

^68^ La acción catequética de la familia tiene un carácter peculiar y en cierto sentido insustituible, subrayado con razón por la Iglesia, especialmente por el Concilio Vaticano II{fn-118}. Esta educación en la fe, impartida por los padres —que debe comenzar desde la más tierna edad de los niños{fn-119}— se realiza ya cuando los miembros de la familia se ayudan unos a otros a crecer en la fe por medio de su testimonio de vida cristiana, a menudo silencioso, mas perseverante a lo largo de una existencia cotidiana vivida según el Evangelio. Será más señalada cuando, al ritmo de los acontecimientos familiares —tales como la recepción de los sacramentos, la celebración de grandes fiestas litúrgicas, el nacimiento de un hijo o la ocasión de un luto— se procura explicitar en familia el contenido cristiano o religioso de esos acontecimientos. Pero es importante ir más allá: los padres cristianos han de esforzarse en seguir y reanudar en el ámbito familiar la formación más metódica recibida en otro tiempo. El hecho de que estas verdades sobre las principales cuestiones de la fe de la vida cristiana sean así transmitidas en un ambiente familiar impregnado de amor y respeto permitirá muchas veces que deje en los niños una huella de manera decisiva y para toda la vida. Los mismos padres aprovechen el esfuerzo que esto les impone, porque en un diálogo catequético de este tipo cada uno recibe y da.

La catequesis familiar precede, pues, acompaña y enriquece toda otra forma de catequesis. Además, en los lugares donde una legislación antirreligiosa pretende incluso impedir la educación en la fe, o donde ha cundido la incredulidad o ha penetrado el secularismo hasta el punto de resultar prácticamente imposible una verdadera creencia religiosa, la iglesia doméstica{fn-120} es el único ámbito donde los niños y los jóvenes pueden recibir una auténtica catequesis. Nunca se esforzarán bastante los padres cristianos por prepararse a este ministerio de catequistas de sus propios hijos y por ejercerlo con celo infatigable. Y es preciso alentar igualmente a las personas o instituciones que, por medio de contactos personales, encuentros o reuniones y toda suerte de medios pedagógicos, ayudan a los padres a cumplir su cometido: el servicio que prestan a la catequesis es inestimable.

[[catechesi-tradendae-69]]
== ... en la escuela ...

^69^ Al lado de la familia y en colaboración con ella, la escuela ofrece a la catequesis posibilidades no desdeñables. En los países, cada vez más escasos por desgracia, donde es posible dar dentro del marco escolar una educación en la fe, la Iglesia tiene el deber de hacerlo lo mejor posible. Esto se refiere, ante todo, a la escuela católica: ¿Seguiría mereciendo este nombre si, aun brillando por su alto nivel de enseñanza en las materias profanas, hubiera motivo justificado para reprocharle su negligencia o desviación en la educación propiamente religiosa? ¡Y no se diga que ésta se dará siempre implícitamente o de manera indirecta! El carácter propio y la razón profunda de la escuela católica, el motivo por el cual deberían preferirla los padres católicos, es precisamente la calidad de la enseñanza religiosa integrada en la educación de los alumnos. Si es verdad que las instituciones católicas deben respetar la libertad de conciencia, es decir, evitar cargar sobre ella desde fuera, por presiones físicas o morales, especialmente en lo que concierne a los actos religiosos de los adolescentes, no lo es menos que tienen el grave deber de ofrecer una formación religiosa adaptada a las situaciones con frecuencia diversas de los alumnos, y también hacerles comprender que la llamada de Dios a servirle en espíritu y en verdad, según los mandamientos de Dios y los preceptos de la Iglesia, sin constreñir al hombre, no lo obliga menos en conciencia.

Pero me refiero también a la escuela no confesional y a la estatal. Expreso el deseo ardiente de que, respondiendo a un derecho claro de la persona humana y de las familias y en el respeto de la libertad religiosa de todos, sea posible a todos los alumnos católicos el progresar en su formación espiritual con la ayuda de una enseñanza religiosa que dependa de la Iglesia, pero que, según los países, pueda ser ofrecida a la escuela o en el ámbito de la escuela, o más aún en el marco de un acuerdo con los poderes públicos sobre los programas escolares, si la catequesis tiene lugar solamente en la parroquia o en otro centro pastoral. En efecto, donde hay dificultades objetivas, por ejemplo cuando los alumnos son de religiones distintas, conviene ordenar los horarios escolares de cara a permitir a los católicos que profundicen su fe y su experiencia religiosa, con unos educadores cualificados, sacerdotes o laicos.

Ciertamente, muchos elementos vitales además de la escuela contribuyen a influenciar la mentalidad de los jóvenes: asuetos, medio social, medio laboral. Pero los que han realizado estudios están fuertemente señalados por ellos, iniciados a unos valores culturales o morales aprendidos en el clima de la institución de enseñanza, interpelados por múltiples ideas recibidas en la escuela: conviene que la catequesis tenga muy en cuenta esta escolarización para alcanzar verdaderamente los demás elementos del saber y de la educación, a fin de que el Evangelio impregne la mentalidad de los alumnos en el terreno de su formación y que la armonización de su cultura se logre a la luz de la fe. Aliento pues a los sacerdotes, religiosos, religiosas y seglares que se ocupan de ayudar a estos alumnos en el plano de la fe. Por lo demás, es el momento de declarar aquí mi firme convicción de que el respeto demostrado a la fe católica de los jóvenes, incluso facilitando su educación, arraigo, consolidación, libre profesión y práctica, honraría ciertamente a todo Gobierno, cualquiera que sea el sistema en que se basa o la ideología en que se inspira.

[[catechesi-tradendae-70]]
== ... en los movimientos

^70^ Reciban finalmente mi palabra de aliento las asociaciones, movimientos y agrupaciones de fieles que se dedican a la práctica de la piedad, al apostolado, a la caridad y a la asistencia, a la presencia cristiana en las realidades temporales. Todos ellos alcanzarán tanto mejor sus objetivos propios y servirán tanto mejor a la Iglesia, cuanto más importante sea el espacio que dediquen, en su organización interna y en su método de acción, a una seria formación religiosa de sus miembros. En este sentido, toda asociación de fieles en la Iglesia debe ser, por definición, educadora de la fe. Así aparece más ostensiblemente la parte que corresponde hoy a los seglares en la catequesis, siempre bajo la dirección pastoral de sus Obispos, como, por otra parte, han subrayado en varias ocasiones las Proposiciones formuladas por el Sínodo.

[[catechesi-tradendae-71]]
== Institutos de formación

^71^ Esta contribución de los seglares, por la cual hemos de estar reconocidos al Señor, constituye al mismo tiempo un reto a nuestra responsabilidad de Pastores. En efecto, esos catequistas seglares deben recibir una formación esmerada para lo que es, si no un ministerio formalmente instituido, si al menos una función de altísimo relieve en la Iglesia. Ahora bien, esa formación nos invita a organizar Centros e Institutos idóneos, sobre los que los Obispos mantendrán una atención constante. Es un campo en el que una colaboración diocesana, interdiocesana e incluso nacional se revela fecunda y fructuosa. Aquí, igualmente, es donde podrá manifestar su mayor eficacia la ayuda material ofrecida por las Iglesias más acomodadas a sus hermanas más pobres. En efecto, ¿es que puede una Iglesia hacer en favor de otra algo mejor que ayudarla a crecer por sí misma como Iglesia?

A todos los que trabajan generosamente al servicio del Evangelio y a quienes he expresado aquí mis vivos alientos, quisiera recordar una consigna muy querida a mi venerado predecesor Pablo VI: «Evangelizadores: nosotros debemos ofrecer... la imagen... de hombres adultos en la fe, capaces de encontrarse más allá de las tensiones reales gracias a la búsqueda común, sincera y desinteresada de la verdad. Sí, la suerte de la evangelización está ciertamente vinculada al testimonio de unidad dado por la Iglesia. He aquí una fuente de responsabilidad, pero también de consuelo»{fn-121}.