[[catechesi-tradendae-part-9]]
= CONCLUSIÓN

[[catechesi-tradendae-72]]
== El Espíritu Santo, Maestro interior

^72^ Al final de esta Exhortación Apostólica, la mirada se vuelve hacia Aquél que es el principio inspirador de toda la obra catequética y de los que la realizan: el Espíritu del Padre y del Hijo: el Espíritu Santo.

Al exponer la misión que tendría este Espíritu en la Iglesia, Cristo utiliza estas palabras significativas: «El os lo enseñará y os traerá a la memoria todo lo que yo os he dicho»[122], y añade: «Cuando viniere Aquél, el Espíritu de verdad, os guiará hacia la verdad completa ..., os comunicará las cosas venideras»[123].

El Espíritu es, pues, prometido a la Iglesia y a cada fiel como un Maestro interior que, en la intimidad de la conciencia y del corazón, hace comprender lo que se había entendido pero que no se había sido capaz de captar plenamente. «El Espíritu Santo desde ahora instruye a los fieles —decía a este respecto san Agustín— según la capacidad espiritual de cada uno. Y él enciende en sus corazones un deseo más vivo en la medida en la que cada uno progresa en esta caridad que le hace amar lo que ya conocía y desear lo que todavía no conocía»[124].

Además, misión del Espíritu es también transformar a los discípulos en testigos de Cristo: «Él dará testimonio de mí y vosotros daréis también testimonio»[125].

Más aún. Para san Pablo, que sintetiza en este punto una teología latente en todo el Nuevo Testamento, la vida según el Espíritu[126], es todo el «ser cristiano», toda la vida cristiana, la vida nueva de los hijos de Dios. Sólo el Espíritu nos permite llamar a Dios: «Abba, Padre»[127]. Sin el Espíritu no podemos decir: «Jesús es el Señor»[128]. Del Espíritu proceden todos los carismas que edifican la Iglesia, comunidad de cristianos[129]. En este sentido san Pablo da a cada discípulo de Cristo esta consigna: «Llenaos del Espíritu»[130]. San Agustín es muy explícito: «El hecho de creer y de obrar bien son nuestros como consecuencia de la libre elección de nuestra voluntad, y sin embargo uno y otro son un don que viene del Espíritu de fe y de caridad»[131].

La catequesis, que es crecimiento en la fe y maduración de la vida cristiana hacia la plenitud, es por consiguiente una obra del Espíritu Santo, obra que sólo Él puede suscitar y alimentar en la Iglesia.

Esta constatación, sacada de la lectura de los textos citados más arriba y de otros muchos pasajes del Nuevo Testamento, nos lleva a dos convicciones.

Ante todo está claro que la Iglesia, cuando ejerce su misión catequética —como también cada cristiano que la ejerce en la Iglesia y en nombre de la Iglesia— debe ser muy consciente de que actúa como instrumento vivo y dócil del Espíritu Santo. Invocar constantemente este Espíritu, estar en comunión con Él, esforzarse en conocer sus auténticas inspiraciones debe ser la actitud de la Iglesia docente y de todo catequista.

Además, es necesario que el deseo profundo de comprender mejor la acción del Espíritu y de entregarse más a él —dado que «nosotros vivimos en la Iglesia un momento privilegiado del Espíritu», como observaba mi Predecesor Pablo VI en su Exhortación Apostólica Evangelii nuntiandi[132]— provoca un despertar catequético. En efecto, la «renovación en el Espíritu» será auténtica y tendrá una verdadera fecundidad en la Iglesia, no tanto en la medida en que suscite carismas extraordinarios, cuanto si conduce al mayor número posible de fieles, en su vida cotidiana, a un esfuerzo humilde, paciente, y perseverante para conocer siempre mejor el misterio de Cristo y dar testimonio de Él.

Yo invoco ahora sobre la Iglesia catequizadora este Espíritu del Padre y del Hijo, y le suplicamos que renueve en esta Iglesia el dinamismo catequético.

[[catechesi-tradendae-73]]
== María, madre y modelo de discípulo

^73^ Que la Virgen de Pentecostés nos lo obtenga con su intercesión. Por una vocación singular, ella vio a su Hijo Jesús «crecer en sabiduría, edad y gracia»[133]. En su regazo y luego escuchándola, a lo largo de la vida oculta en Nazaret, este Hijo, que era el Unigénito del Padre, lleno de gracia y de verdad, ha sido formado por ella en el conocimiento humano de las Escrituras y de la historia del designio de Dios sobre su Pueblo, en la adoración al Padre[134]. Por otra parte, ella ha sido la primera de sus discípulos: primera en el tiempo, pues ya al encontrarle en el Templo, recibe de su Hijo adolescente unas lecciones que conserva en su corazón[135]; la primera, sobre todo, porque nadie ha sido enseñado por Dios[136] con tanta profundidad. «Madre y a la vez discípula», decía de ella san Agustín añadiendo atrevidamente que esto fue para ella más importante que lo otro[137]. No sin razón en el Aula Sinodal se dijo de María que es «un catecismo viviente», «madre y modelo de los catequistas».

Quiera, pues, la presencia del Espíritu Santo, por intercesión de María, conceder a la Iglesia un impulso creciente en la obra catequética que le es esencial. Entonces la Iglesia realizará con eficacia, en esta hora de gracia, la misión inalienable y universal recibida de su Maestro: «Id, pues; enseñad a todas las gentes»[138].

Dado en Roma, junto a San Pedro, el día 16 de octubre del año 1979, segundo de mi pontificado.

[.text-center]
JOHANNES PAULUS II