:fn-1: footnote:[Cf. Lk 22:32.]
:fn-2: footnote:[2 Cor 11:28.]
:fn-3: footnote:[Cf. Second Vatican Ecumenical Council, Decree on the Church's Missionary Activity Ad Gentes, 1: AAS 58 (1966), p. 947.]
:fn-4: footnote:[Cf. Eph 4:24, 2:15; Col 3:10; Gal 3:27; Rom 13:114; 2 Cor 5:17.]
:fn-5: footnote:[2 Cor 5:20.]
:fn-6: footnote:[Cf. Paul VI, Address for the closing of the Third General Assembly of the Synod of Bishops (26 October 1974): AAS 66 (19740, PP. 634-635, 637.]
:fn-7: footnote:[Paul VI, Address to the College of Cardinals (22 June 1973): AAS 65 (1973), p. 383.]
:fn-8: footnote:[2 Cor 11:28.]
:fn-9: footnote:[1 Tim 5:17.]
:fn-10: footnote:[2 Tim 2:15.]
:fn-11: footnote:[Cf. 1 Cor 2:5.]

[[evangelii-nuntiandi-introduction]]
= INTRODUCTION

--
Venerable brothers and dear sons and daughters: +
health and the apostolic blessing.
--

[[evangelii-nuntiandi-1]]
--
1&#46; There is no doubt that the effort to proclaim the Gospel to the people of today, who are buoyed up by hope but at the same time often oppressed by fear and distress, is a service rendered to the Christian community and also to the whole of humanity.

For this reason the duty of confirming the brethren - a duty which with the office of being the Successor of Peter{fn-1} we have received from the Lord, and which is for us a "daily preoccupation,"{fn-2} a program of life and action, and a fundamental commitment of our Pontificate - seems to us all the more noble and necessary when it is a matter of encouraging our brethren in their mission as evangelizers, in order that, in this time of uncertainty and confusion, they may accomplish this task with ever increasing love, zeal and joy.
--

[[evangelii-nuntiandi-2]]
--
2&#46; This is precisely what we wish to do here, at the end of this Holy Year during which the Church, "striving to proclaim the Gospel to all people,"{fn-3} has had the single aim of fulfilling her duty of being the messenger of the Good News of Jesus Christ - the Good News proclaimed through two fundamental commands: "Put on the new self"{fn-4} and "Be reconciled to God."{fn-5}

We wish to do so on this tenth anniversary of the closing of the Second Vatican Council, the objectives of which are definitively summed up in this single one: to make the Church of the twentieth century ever better fitted for proclaiming the Gospel to the people of the twentieth century

We wish to do so one year after the Third General Assembly of the Synod of Bishops, which as is well known, was devoted to evangelization; and we do so all the more willingly because it has been asked of us by the Synod Fathers themselves. In fact, at the end of that memorable Assembly, the Fathers decided to remit to the Pastor of the universal Church, with great trust and simplicity, the fruits of all their labors, stating that they awaited from him a fresh forward impulse, capable of creating within a Church still more firmly rooted in the undying power and strength of Pentecost a new period of evangelization.{fn-6}
--

[[evangelii-nuntiandi-3]]
3&#46; We have stressed the importance of this theme of evangelization on many occasions, well before the Synod took place. On June 22, 1973, we said to the Sacred College of Cardinals: "The conditions of the society in which we live oblige all of us therefore to revise methods, to seek by every means to study how we can bring the Christian message to modern man. For it is only in the Christian message that modern man can find the answer to his questions and the energy for his commitment of human solidarity."{fn-7} And we added that in order to give a valid answer to the demands of the Council which call for our attention, it is absolutely necessary for us to take into account a heritage of faith that the Church has the duty of preserving in its untouchable purity, and of presenting it to the people of our time, in a way that is as understandable and persuasive as possible.

[[evangelii-nuntiandi-4]]
--
4&#46; This fidelity both to a message whose servants we are and to the people to whom we must transmit it living and intact is the central axis of evangelization. It poses three burning questions, which the 1974 Synod kept constantly in mind:

- In our day, what has happened to that hidden energy of the Good News, which is able to have a powerful effect on man's conscience?

- To what extent and in what way is that evangelical force capable of really transforming the people of this century?

- What methods should be followed in order that the power of the Gospel may have its effect?

Basically, these inquiries make explicit the fundamental question that the Church is asking herself today and which may be expressed in the following terms: after the Council and thanks to the Council, which was a time given her by God, at this turning-point of history, does the Church or does she not find herself better equipped to proclaim the Gospel and to put it into people's hearts with conviction, freedom of spirit and effectiveness?
--

[[evangelii-nuntiandi-5]]
--
5&#46; We can all see the urgency of giving a loyal, humble and courageous answer to this question, and of acting accordingly.

In our "anxiety for all the Churches,"{fn-8} we would like to help our brethren and sons and daughters to reply to these inquiries. Our words come from the wealth of the Synod and are meant to be a meditation on evangelization. May they succeed in inviting the whole People of God assembled in the Church to make the same meditation; and may they give a fresh impulse to everyone, especially those "who are assiduous in preaching and teaching,"{fn-9} so that each one of them may follow "a straight course in the message of the truth,"{fn-10} and may work as a preacher of the Gospel and acquit himself perfectly of his ministry.

Such an exhortation seems to us to be of capital importance, for the presentation of the Gospel message is not an optional contribution for the Church. It is the duty incumbent on her by the command of the Lord Jesus, so that people can believe and be saved. This message is indeed necessary. It is unique. It cannot be replaced. It does not permit either indifference, syncretism or accommodation. It is a question of people's salvation. It is the beauty of the Revelation that it represents. It brings with it a wisdom that is not of this world. It is able to stir up by itself faith - faith that rests on the power of God.{fn-11} It is truth. It merits having the apostle consecrate to it all his time and all his energies, and to sacrifice for it, if necessary, his own life.
--