:fn-12: footnote:[Lk 4:43.]
:fn-13: footnote:[Ibid.]
:fn-14: footnote:[Lk 4:18; cf. Is 61:1.]
:fn-15: footnote:[Cf. Mk 1:1; Rom 1:1-3.]
:fn-16: footnote:[Cf. Mt 6:33.]
:fn-17: footnote:[Cf. Mt 5:3-12.]
:fn-18: footnote:[Cf. Mt 5-7.]
:fn-19: footnote:[Cf. Mt 10.]
:fn-20: footnote:[Cf. Mt 13.]
:fn-21: footnote:[Mt 18.]
:fn-22: footnote:[Cf. Mt 24-25.]
:fn-23: footnote:[Cf. Mt. 24:36; Acts 1:7; 1 Thess 5:1-2.]
:fn-24: footnote:[Cf. Mt 11:12; Lk 16:16.]
:fn-25: footnote:[Cf. Mt 4:17.]
:fn-26: footnote:[Mk 1:27.]
:fn-27: footnote:[Lk 4:22.]
:fn-28: footnote:[Jn 7:46.]
:fn-29: footnote:[Lk 4:43.]
:fn-30: footnote:[Jn 11:52.]
:fn-31: footnote:[Cf. Second Vatican Ecumenical Council, Dogmatic Constitution on Divine Revelation Dei Verbum, 4: AAS 58 (1966), pp. 818-819.32. 1 Pt 2:9.]
:fn-33: footnote:[Cf. Acts 2:11.]
:fn-34: footnote:[Lk 4:43.]
:fn-35: footnote:[1 Cor 9:16.]
:fn-36: footnote:["Declaration of the Synod Fathers", 4: L'Osservatore Romano (27 October 1974), p. 6.]
:fn-37: footnote:[Mt 28:19.]
:fn-38: footnote:[Acts 2:41, 47.]
:fn-39: footnote:[Cf. Second Vatican Ecumenical Council, Dogmatic Constitution on the Church Lumen Gentium, 8: AAS 57 (1965), p. 11; Decree on the Church's Missionary Activity Ad Gentes, 5: AAS 58 (1966), pp 951-952.]
:fn-40: footnote:[Cf. Acts 2:42-46; 4:32-35; 5:12-16.]
:fn-41: footnote:[Cf. Acts 2:11; 1 Pt 2:9.]
:fn-42: footnote:[Cf. Decree on the Church's Missionary Activity Ad Gentes, 5, 11-12: AAS 58 (1966), pp. 951-952, 959-961.]
:fn-43: footnote:[Cf. 2 Cor 4:5; Saint Augustine Sermo XLVI, De Pastoribus: ccl XLI, pp. 529-530.]
:fn-44: footnote:[Lk 10:16; cf. Saint Cyprian, De Unitate Ecclesiae, 14: PL 4, 527; Saint Augustine, Enarrat. 88, Sermo, 2, 14: PL 37, 1140; Saint John Chrysostom, Hom. de capto Eutropio, 6: PG 52, 462.]
:fn-45: footnote:[Eph 5:25.]

[[evangelii-nuntiandi-part-1]]
= I

[[evangelii-nuntiandi-6]]
--
6&#46; The witness that the Lord gives of Himself and that Saint Luke gathered together in his Gospel - "I must proclaim the Good News of the kingdom of God"{fn-12} - without doubt has enormous consequences, for it sums up the whole mission of Jesus: "That is what I was sent to do."{fn-13} These words take on their full significance if one links them with the previous verses, in which Christ has just applied to Himself the words of the prophet Isaiah: "The Spirit of the Lord has been given to me, for he has anointed me. He has sent me to bring the good news to the poor."{fn-14}

Going from town to town, preaching to the poorest - and frequently the most receptive - the joyful news of the fulfillment of the promises and of the Covenant offered by God is the mission for which Jesus declares that He is sent by the Father. And all the aspects of His mystery - the Incarnation itself, His miracles, His teaching, the gathering together of the disciples, the sending out of the Twelve, the cross and the resurrection, the permanence of His presence in the midst of His own - were components of His evangelizing activity.
--

[[evangelii-nuntiandi-7]]
--
7&#46; During the Synod, the bishops very frequently referred to this truth: Jesus Himself, the Good News of God,{fn-15} was the very first and the greatest evangelizer; He was so through and through: to perfection and to the point of the sacrifice of His earthly life.

To evangelize: what meaning did this imperative have for Christ? It is certainly not easy to express in a complete synthesis the meaning, the content and the modes of evangelization as Jesus conceived it and put it into practice. In any case the attempt to make such a synthesis will never end. Let it suffice for us to recall a few essential aspects.
--
[[evangelii-nuntiandi-8]]
8&#46; As an evangelizer, Christ first of all proclaims a kingdom, the kingdom of God; and this is so important that, by comparison, everything else becomes "the rest," which is "given in addition."{fn-16} Only the kingdom therefore is absolute and it makes everything else relative. The Lord will delight in describing in many ways the happiness of belonging to this kingdom (a paradoxical happiness which is made up of things that the world rejects),{fn-17} the demands of the kingdom and its Magna Charta,{fn-18} the heralds of the kingdom,{fn-19} its mysteries,{fn-20} its children,{fn-21} the vigilance and fidelity demanded of whoever awaits its definitive coming.{fn-22}

[[evangelii-nuntiandi-9]]
9&#46; As the kernel and center of His Good News, Christ proclaims salvation, this great gift of God which is liberation from everything that oppresses man but which is above all liberation from sin and the Evil One, in the joy of knowing God and being known by Him, of seeing Him, and of being given over to Him. All of this is begun during the life of Christ and definitively accomplished by His death and resurrection. But it must be patiently carried on during the course of history, in order to be realized fully on the day of the final coming of Christ, whose date is known to no one except the Father.{fn-23}

[[evangelii-nuntiandi-10]]
10&#46; This kingdom and this salvation, which are the key words of Jesus Christ's evangelization, are available to every human being as grace and mercy, and yet at the same time each individual must gain them by force - they belong to the violent, says the Lord,{fn-24} through toil and suffering, through a life lived according to the Gospel, through abnegation and the cross, through the spirit of the beatitudes. But above all each individual gains them through a total interior renewal which the Gospel calls metanoia; it is a radical conversion, a profound change of mind and heart.{fn-25}

[[evangelii-nuntiandi-11]]
11&#46; Christ accomplished this proclamation of the kingdom of God through the untiring preaching of a word which, it will be said, has no equal elsewhere: "Here is a teaching that is new, and with authority behind it."{fn-26} "And he won the approval of all, and they were astonished by the gracious words that came from his lips.{fn-27} There has never been anybody who has spoken like him."{fn-28} His words reveal the secret of God, His plan and His promise, and thereby change the heart of man and his destiny.

[[evangelii-nuntiandi-12]]
12&#46; But Christ also carries out this proclamation by innumerable signs, which amaze the crowds and at the same time draw them to Him in order to see Him, listen to Him and allow themselves to be transformed by Him: the sick are cured, water is changed into wine, bread is multiplied, the dead come back to life. And among all these signs there is the one to which He attaches great importance: the humble and the poor are evangelized, become His disciples and gather together "in His name" in the great community of those who believe in Him. For this Jesus who declared, "I must preach the Good News of the Kingdom of God"{fn-29} is the same Jesus of whom John the Evangelist said that He had come and was to die "to gather together in unity the scattered children of God."{fn-30} Thus He accomplishes His revelation, completing it and confirming it by the entire revelation that He makes of Himself, by words and deeds, by signs and miracles, and more especially by His death, by His resurrection and by the sending of the Spirit of Truth.{fn-31}

[[evangelii-nuntiandi-13]]
13&#46; Those who sincerely accept the Good News, through the power of this acceptance and of shared faith therefore gather together in Jesus' name in order to seek together the kingdom, build it up and live it. They make up a community which is in its turn evangelizing. The command to the Twelve to go out and proclaim the Good News is also valid for all Christians, though in a different way. It is precisely for this reason that Peter calls Christians "a people set apart to sing the praises of God,"{fn-32} those marvelous things that each one was able to hear in his own language.{fn-33} Moreover, the Good News of the kingdom which is coming and which has begun is meant for all people of all times. Those who have received the Good News and who have been gathered by it into the community of salvation can and must communicate and spread it.

[[evangelii-nuntiandi-14]]
14&#46; The Church knows this. She has a vivid awareness of the fact that the Savior's words, "I must proclaim the Good News of the kingdom of God,"{fn-34} apply in all truth to herself: She willingly adds with St. Paul: "Not that I boast of preaching the gospel, since it is a duty that has been laid on me; I should be punished if I did not preach it"{fn-35} It is with joy and consolation that at the end of the great Assembly of 1974 we heard these illuminating words: "We wish to confirm once more that the task of evangelizing all people constitutes the essential mission of the Church."{fn-36} It is a task and mission which the vast and profound changes of present-day society make all the more urgent. Evangelizing is in fact the grace and vocation proper to the Church, her deepest identity. She exists in order to evangelize, that is to say, in order to preach and teach, to be the channel of the gift of grace, to reconcile sinners with God, and to perpetuate Christ's sacrifice in the Mass, which is the memorial of His death and glorious resurrection.

[[evangelii-nuntiandi-15]]
--
15&#46; Anyone who rereads in the New Testament the origins of the Church, follows her history step by step and watches her live and act, sees that she is linked to evangelization in her most intimate being:

-&nbsp;The Church is born of the evangelizing activity of Jesus and the Twelve. She is the normal, desired, most immediate and most visible fruit of this activity: "Go, therefore, make disciples of all the nations."{fn-37} Now, "they accepted what he said and were baptized. That very day about three thousand were added to their number.... Day by day the Lord added to their community those destined to be saved."{fn-38} - Having been born consequently out of being sent, the Church in her turn is sent by Jesus. The Church remains in the world when the Lord of glory returns to the Father. She remains as a sign - simultaneously obscure and luminous - of a new presence of Jesus, of His departure and of His permanent presence. She prolongs and continues Him. And it is above all His mission and His condition of being an evangelizer that she is called upon to continue.{fn-39} For the Christian community is never closed in upon itself. The intimate life of this community - the life of listening to the Word and the apostles' teaching, charity lived in a fraternal way, the sharing of bread{fn-40} this intimate life only acquires its full meaning when it becomes a witness, when it evokes admiration and conversion, and when it becomes the preaching and proclamation of the Good News. Thus it is the whole Church that receives the mission to evangelize, and the work of each individual member is important for the whole.

-&nbsp;The Church is an evangelizer, but she begins by being evangelized herself. She is the community of believers, the community of hope lived and communicated, the community of brotherly love, and she needs to listen unceasingly to what she must believe, to her reasons for hoping, to the new commandment of love. She is the People of God immersed in the world, and often tempted by idols, and she always needs to hear the proclamation of the "mighty works of God"{fn-41} which converted her to the Lord; she always needs to be called together afresh by Him and reunited. In brief, this means that she has a constant need of being evangelized, if she wishes to retain freshness, vigor and strength in order to proclaim the Gospel. The Second Vatican Council recalled{fn-42} and the 1974 Synod vigorously took up again this theme of the Church which is evangelized by constant conversion and renewal, in order to evangelize the world with credibility.

-&nbsp;The Church is the depositary of the Good News to be proclaimed. The promises of the New Alliance in Jesus Christ, the teaching of the Lord and the apostles, the Word of life, the sources of grace and of God's loving kindness, the path of salvation - all these things have been entrusted to her. It is the content of the Gospel, and therefore of evangelization, that she preserves as a precious living heritage, not in order to keep it hidden but to communicate it.

-&nbsp;Having been sent and evangelized, the Church herself sends out evangelizers. She puts on their lips the saving Word, she explains to them the message of which she herself is the depositary, she gives them the mandate which she herself has received and she sends them out to preach. To preach not their own selves or their personal ideas,{fn-43} but a Gospel of which neither she nor they are the absolute masters and owners, to dispose of it as they wish, but a Gospel of which they are the ministers, in order to pass it on with complete fidelity.
--

[[evangelii-nuntiandi-16]]
--
16&#46; There is thus a profound link between Christ, the Church and evangelization. During the period of the Church that we are living in, it is she who has the task of evangelizing. This mandate is not accomplished without her, and still less against her.

It is certainly fitting to recall this fact at a moment like the present one when it happens that not without sorrow we can hear people - whom we wish to believe are well-intentioned but who are certainly misguided in their attitude - continually claiming to love Christ but without the Church, to listen to Christ but not the Church, to belong to Christ but outside the Church. The absurdity of this dichotomy is clearly evident in this phrase of the Gospel: "Anyone who rejects you rejects me."{fn-44} And how can one wish to love Christ without loving the Church, if the finest witness to Christ is that of St. Paul: "Christ loved the Church and sacrificed himself for her"?{fn-45}
--
