:fn-46: footnote:[Rev. 21:5; cf. 2 Cor 5:17; Gal 6:15.]
:fn-47: footnote:[Cf. Rom 6:4.]
:fn-48: footnote:[Cf. Eph 4:24-25; Col 3:9-10.]
:fn-49: footnote:[Cf. Rom 1:16; 1 Cor 1:18, 2:4.]
:fn-50: footnote:[Cf. 53: AAS 58 (1966), p. 1075.]
:fn-51: footnote:[Cf. Tertullian Apologeticum, 39: CCL, I, PP. 150-153; Minucius Felix, Octavius 9 and 31: CSLP, Turin 1963, pp. 11-13, 47-48.]
:fn-52: footnote:[1 Pt 3:15.]
:fn-53: footnote:[Cf. Second Vatican Ecumenical Council, Dogmatic Constitution on the Church Lumen Gentium, 1, 9, 48; AAS 57 (1965), pp. 5, 12-14, 53-54; Pastoral Constitution on the Church in the Modern World Gaudium et Spes, 42, 45, AAS 58 (1966), pp. 1060-1061, 1065-1066; Decree on the Church's Missionary Activity Ad Gentes, 1, 5: AAS 58 (1966), pp. 947, 951-952.]
:fn-54: footnote:[Cf. Rom 1:16; 1 Cor 1:18.]

[[evangelii-nuntiandi-part-2]]
= II

[[evangelii-nuntiandi-17]]
--
17&#46; In the Church's evangelizing activity there are of course certain elements and aspects to be specially insisted on. Some of them are so important that there will be a tendency simply to identify them with evangelization. Thus it has been possible to define evangelization in terms of proclaiming Christ to those who do not know Him, of preaching, of catechesis, of conferring Baptism and the other sacraments.

Any partial and fragmentary definition which attempts to render the reality of evangelization in all its richness, complexity and dynamism does so only at the risk of impoverishing it and even of distorting it. It is impossible to grasp the concept of evangelization unless one tries to keep in view all its essential elements.

These elements were strongly emphasized at the last Synod, and are still the subject of frequent study, as a result of the Synod's work. We rejoice in the fact that these elements basically follow the lines of those transmitted to us by the Second Vatican Council, especially in "Lumen gentium," "Gaudium et spes" and "Ad gentes."
--

[[evangelii-nuntiandi-18]]
18&#46; For the Church, evangelizing means bringing the Good News into all the strata of humanity, and through its influence transforming humanity from within and making it new: "Now I am making the whole of creation new."{fn-46} But there is no new humanity if there are not first of all new persons renewed by Baptism{fn-47} and by lives lived according to the Gospel.{fn-48} The purpose of evangelization is therefore precisely this interior change, and if it had to be expressed in one sentence the best way of stating it would be to say that the Church evangelizes when she seeks to convert,{fn-49} solely through the divine power of the message she proclaims, both the personal and collective consciences of people, the activities in which they engage, and the lives and concrete milieu which are theirs.

[[evangelii-nuntiandi-19]]
19&#46; Strata of humanity which are transformed: for the Church it is a question not only of preaching the Gospel in ever wider geographic areas or to ever greater numbers of people, but also of affecting and as it were upsetting, through the power of the Gospel, mankind's criteria of judgment, determining values, points of interest, lines of thought, sources of inspiration and models of life, which are in contrast with the Word of God and the plan of salvation.

[[evangelii-nuntiandi-20]]
--
20&#46; All this could he expressed in the following words: what matters is to evangelize man's culture and cultures (not in a purely decorative way, as it were, by applying a thin veneer, but in a vital way, in depth and right to their very roots), in the wide and rich sense which these terms have in Gaudium et spes,{fn-50} always taking the person as one's starting-point and always coming back to the relationships of people among themselves and with God.

The Gospel, and therefore evangelization, are certainly not identical with culture, and they are independent in regard to all cultures. Nevertheless, the kingdom which the Gospel proclaims is lived by men who are profoundly linked to a culture, and the building up of the kingdom cannot avoid borrowing the elements of human culture or cultures. Though independent of cultures, the Gospel and evangelization are not necessarily incompatible with them; rather they are capable of permeating them all without becoming subject to any one of them.

The split between the Gospel and culture is without a doubt the drama of our time, just as it was of other times. Therefore every effort must be made to ensure a full evangelization of culture, or more correctly of cultures. They have to be regenerated by an encounter with the Gospel. But this encounter will not take place if the Gospel is not proclaimed.
--

[[evangelii-nuntiandi-21]]
--
21&#46; Above all the Gospel must be proclaimed by witness. Take a Christian or a handful of Christians who, in the midst of their own community, show their capacity for understanding and acceptance, their sharing of life and destiny with other people, their solidarity with the efforts of all for whatever is noble and good. Let us suppose that, in addition, they radiate in an altogether simple and unaffected way their faith in values that go beyond current values, and their hope in something that is not seen and that one would not dare to imagine. Through this wordless witness these Christians stir up irresistible questions in the hearts of those who see how they live: Why are they like this? Why do they live in this way? What or who is it that inspires them? Why are they in our midst? Such a witness is already a silent proclamation of the Good News and a very powerful and effective one. Here we have an initial act of evangelization. The above questions will ask, whether they are people to whom Christ has never been proclaimed, or baptized people who do not practice, or people who live as nominal Christians but according to principles that are in no way Christian, or people who are seeking, and not without suffering, something or someone whom they sense but cannot name. Other questions will arise, deeper and more demanding ones, questions evoked by this witness which involves presence, sharing, solidarity, and which is an essential element, and generally the first one, in evangelization."{fn-51}

All Christians are called to this witness, and in this way they can be real evangelizers. We are thinking especially of the responsibility incumbent on immigrants in the country that receives them.
--

[[evangelii-nuntiandi-22]]
22&#46; Nevertheless this always remains insufficient, because even the finest witness will prove ineffective in the long run if it is not explained, justified - what Peter called always having "your answer ready for people who ask you the reason for the hope that you all have"{fn-52} - and made explicit by a clear and unequivocal proclamation of the Lord Jesus. The Good News proclaimed by the witness of life sooner or later has to be proclaimed by the word of life. There is no true evangelization if the name, the teaching, the life, the promises, the kingdom and the mystery of Jesus of Nazareth, the Son of God are not proclaimed. The history of the Church, from the discourse of Peter on the morning of Pentecost onwards, has been intermingled and identified with the history of this proclamation. At every new phase of human history, the Church, constantly gripped by the desire to evangelize, has but one preoccupation: whom to send to proclaim the mystery of Jesus? In what way is this mystery to be proclaimed? How can one ensure that it will resound and reach all those who should hear it? This proclamation - kerygma, preaching or catechesis - occupies such an important place in evangelization that it has often become synonymous with it; and yet it is only one aspect of evangelization.

[[evangelii-nuntiandi-23]]
23&#46; In fact the proclamation only reaches full development when it is listened to, accepted and assimilated, and when it arouses a genuine adherence in the one who has thus received it. An adherence to the truths which the Lord in His mercy has revealed; still more, an adherence to a program of life - a life henceforth transformed - which He proposes. In a word, adherence to the kingdom, that is to say, to the "new world," to the new state of things, to the new manner of being, of living, of living in community, which the Gospel inaugurates. Such an adherence, which cannot remain abstract and unincarnated, reveals itself concretely by a visible entry into a community of believers. Thus those whose life has been transformed enter a community which is itself a sign of transformation, a sign of newness of life: it is the Church, the visible sacrament of salvation.{fn-53} Our entry into the ecclesial community will in its turn be expressed through many other signs which prolong and unfold the sign of the Church. In the dynamism of evangelization, a person who accepts the Church as the Word which saves{fn-54} normally translates it into the following sacramental acts: adherence to the Church, and acceptance of the sacraments, which manifest and support this adherence through the grace which they confer.

[[evangelii-nuntiandi-24]]
--
24&#46; Finally, the person who has been evangelized goes on to evangelize others. Here lies the test of truth, the touchstone of evangelization: it is unthinkable that a person should accept the Word and give himself to the kingdom without becoming a person who bears witness to it and proclaims it in his turn.

To complete these considerations on the meaning of evangelization, a final observation must be made, one which we consider will help to clarify the reflections that follow.

Evangelization, as we have said, is a complex process made up of varied elements: the renewal of humanity, witness, explicit proclamation, inner adherence, entry into the community, acceptance of signs, apostolic initiative. These elements may appear to be contradictory, indeed mutually exclusive. In fact they are complementary and mutually enriching. Each one must always be seen in relationship with the others. The value of the last Synod was to have constantly invited us to relate these elements rather than to place them in opposition one to the other, in order to reach a full understanding of the Church's evangelizing activity.

It is this global vision which we now wish to outline, by examining the content of evangelization and the methods of evangelizing and by clarifying to whom the Gospel message is addressed and who today is responsible for it.
--
