:fn-55: footnote:[Cf. Acts 17:22-23.]
:fn-56: footnote:[1 Jn 3:1; cf. Rom 8:14-17.]
:fn-57: footnote:[Cf. Eph 2:8; Rom 1:16. Cf. Sacred Congregation for the Doctrine of the Faith, Declaratio ad fidem tuendam in mysteria Incarnationis et SS. Trinitatis e quibusdam recentibus erroribus (21 February 1972): AAS 64 (1972), pp. 237-241.]
:fn-58: footnote:[Cf. 1 Jn 3:2; Rom 8:29; Phil 3: 20-21. Cf. Second Vatican Ecumenical Council, Dogmatic Constitution on the Church Lumen Gentium 48-51: AAS 57 (1965), pp. 53-58.]
:fn-59: footnote:[Cf. Sacred Congregation for the Doctrine of the Faith, Declaratio circa Catholicam Doctrinam de Ecclesia contra nonnullos errores hodiernos tuendam (24 June 1973): AAS 65 (1973), pp. 396-408.]
:fn-60: footnote:[Cf. Second Vatican Ecumenical Council, Pastoral Constitution on the Church in the Modern World Gaudium et Spes, 47-52: AAS 58 (1966): pp. 1067-1074; Paul VI, Encyclical Letter Humanae Vitae: AAS 60 (1968), pp. 481-503.]
:fn-61: footnote:[Paul VI, Address for the opening of the Third General Assembly of the Synod of Bishops (27 September 1974): AAS 66 (1974), p. 562.]
:fn-62: footnote:[Ibid.]
:fn-63: footnote:[Paul VI Address to the Campesinos of Colombia (23 August 1968): AAS 60 (1968), p. 623.]
:fn-64: footnote:[Paul VI, Address for the Day of Development at Bogota (23 August 1968): AAS 60 (1968), p. 627; Cf. Saint Augustine, Epistola 229, 2: PL 33, 1020.]
:fn-65: footnote:[Paul VI, Address for the closing of the Third General Assembly of the Synod of Bishops (26 October 1974); AAS 66 (1974), p. 637.]
:fn-66: footnote:[Address given on 15 October 1975: L'Osservatore Romano (17 October 1975).]

[[evangelii-nuntiandi-part-3]]
= III

[[evangelii-nuntiandi-25]]
25&#46; In the message which the Church proclaims there are certainly many secondary elements. Their presentation depends greatly on changing circumstances. They themselves also change. But there is the essential content, the living substance, which cannot be modified or ignored without seriously diluting the nature of evangelization itself.

[[evangelii-nuntiandi-26]]
26&#46; It is not superfluous to recall the following points: to evangelize is first of all to bear witness, in a simple and direct way, to God revealed by Jesus Christ, in the Holy Spirit, to bear witness that in His Son God has loved the world - that in His Incarnate Word He has given being to all things and has called men to eternal life. Perhaps this attestation of God will be for many people the unknown God{fn-55} whom they adore without giving Him a name, or whom they seek by a secret call of the heart when they experience the emptiness of all idols. But it is fully evangelizing in manifesting the fact that for man the Creator is not an anonymous and remote power; He is the Father: "...that we should be called children of God; and so we are."{fn-56} And thus we are one another's brothers and sisters in God.

[[evangelii-nuntiandi-27]]
27&#46; Evangelization will also always contain - as the foundation, center, and at the same time, summit of its dynamism - a clear proclamation that, in Jesus Christ, the Son of God made man, who died and rose from the dead, salvation is offered to all men, as a gift of God's grace and mercy.{fn-57} And not an immanent salvation, meeting material or even spiritual needs, restricted to the framework of temporal existence and completely identified with temporal desires, hopes, affairs and struggles, but a salvation which exceeds all these limits in order to reach fulfillment in a communion with the one and only divine Absolute: a transcendent and eschatological salvation, which indeed has its beginning in this life but which is fulfilled in eternity.

[[evangelii-nuntiandi-28]]
28&#46; Consequently evangelization cannot but include the prophetic proclamation of a hereafter, man's profound and definitive calling, in both continuity and discontinuity with the present situation: beyond time and history, beyond the transient reality of this world, and beyond the things of this world, of which a hidden dimension will one day be revealed - beyond man himself, whose true destiny is not restricted to his temporal aspect but will be revealed in the future life.{fn-58} Evangelization therefore also includes the preaching of hope in the promises made by God in the new Covenant in Jesus Christ; the preaching of God's love for us and of our love for God; the preaching of brotherly love for all men - the capacity of giving and forgiving, of self-denial, of helping one's brother and sister - which, springing from the love of God, is the kernel of the Gospel; the preaching of the mystery of evil and of the active search for good. The preaching likewise - and this is always urgent - of the search for God Himself through prayer which is principally that of adoration and thanksgiving, but also through communion with the visible sign of the encounter with God which is the Church of Jesus Christ; and this communion in its turn is expressed by the application of those other signs of Christ living and acting in the Church which are the sacraments. To live the sacraments in this way, bringing their celebration to a true fullness, is not, as some would claim, to impede or to accept a distortion of evangelization: it is rather to complete it. For in its totality, evangelization - over and above the preaching of a message - consists in the implantation of the Church, which does not exist without the driving force which is the sacramental life culminating in the Eucharist.{fn-59}

[[evangelii-nuntiandi-29]]
29&#46; But evangelization would not be complete if it did not take account of the unceasing interplay of the Gospel and of man's concrete life, both personal and social. This is why evangelization involves an explicit message, adapted to the different situations constantly being realized, about the rights and duties of every human being, about family life without which personal growth and development is hardly possible,{fn-60} about life in society, about international life, peace, justice and development- a message especially energetic today about liberation.

[[evangelii-nuntiandi-30]]
30&#46; It is well known in what terms numerous bishops from all the continents spoke of this at the last Synod, especially the bishops from the Third World, with a pastoral accent resonant with the voice of the millions of sons and daughters of the Church who make up those peoples. Peoples, as we know, engaged with all their energy in the effort and struggle to overcome everything which condemns them to remain on the margin of life: famine, chronic disease, illiteracy, poverty, injustices in international relations and especially in commercial exchanges, situations of economic and cultural neo-colonialism sometimes as cruel as the old political colonialism. The Church, as the bishops repeated, has the duty to proclaim the liberation of millions of human beings, many of whom are her own children- the duty of assisting the birth of this liberation, of giving witness to it, of ensuring that it is complete. This is not foreign to evangelization.

[[evangelii-nuntiandi-31]]
--
31&#46; Between evangelization and human advancement- development and liberation- there are in fact profound links. These include links of an anthropological order, because the man who is to be evangelized is not an abstract being but is subject to social and economic questions. They also include links in the theological order, since one cannot dissociate the plan of creation from the plan of Redemption. The latter plan touches the very concrete situations of injustice to be combated and of justice to be restored. They include links of the eminently evangelical order, which is that of charity: how in fact can one proclaim the new commandment without promoting in justice and in peace the true, authentic advancement of man? We ourself have taken care to point this out, by recalling that it is impossible to accept "that in evangelization one could or should ignore the importance of the problems so much discussed today, concerning justice, liberation, development and peace in the world. This would be to forget the lesson which comes to us from the Gospel concerning love of our neighbor who is suffering and in need."{fn-61}

The same voices which during the Synod touched on this burning theme with zeal, intelligence and courage have, to our great joy, furnished the enlightening principles for a proper understanding of the importance and profound meaning of liberation, such as it was proclaimed and achieved by Jesus of Nazareth and such as it is preached by the Church.
--

[[evangelii-nuntiandi-32]]
32&#46; We must not ignore the fact that many, even generous Christians who are sensitive to the dramatic questions involved in the problem of liberation, in their wish to commit the Church to the liberation effort are frequently tempted to reduce her mission to the dimensions of a simply temporal project. They would reduce her aims to a man-centered goal; the salvation of which she is the messenger would be reduced to material well-being. Her activity, forgetful of all spiritual and religious preoccupation, would become initiatives of the political or social order. But if this were so, the Church would lose her fundamental meaning. Her message of liberation would no longer have any originality and would easily be open to monopolization and manipulation by ideological systems and political parties. She would have no more authority to proclaim freedom as in the name of God. This is why we have wished to emphasize, in the same address at the opening of the Synod, "the need to restate clearly the specifically religious finality of evangelization. This latter would lose its reason for existence if it were to diverge from the religious axis that guides it: the kingdom of God, before anything else, in its fully theological meaning...."{fn-62}

[[evangelii-nuntiandi-33]]
--
33&#46; With regard to the liberation which evangelization proclaims and strives to put into practice one should rather say this:

-&nbsp;it cannot be contained in the simple and restricted dimension of economics, politics, social or cultural life; it must envisage the whole man, in all his aspects, right up to and including his openness to the absolute, even the divine Absolute;

-&nbsp;it is therefore attached to a view of man which it can never sacrifice to the needs of any strategy, practice or short-term efficiency.
--

[[evangelii-nuntiandi-34]]
34&#46; Hence, when preaching liberation and associating herself with those who are working and suffering for it, the Church is certainly not willing to restrict her mission only to the religious field and dissociate herself from man's temporal problems. Nevertheless she reaffirms the primacy of her spiritual vocation and refuses to replace the proclamation of the kingdom by the proclamation of forms of human liberation- she even states that her contribution to liberation is incomplete if she neglects to proclaim salvation in Jesus Christ.

[[evangelii-nuntiandi-35]]
--
35&#46; The Church links human liberation and salvation in Jesus Christ, but she never identifies them, because she knows through revelation, historical experience and the reflection of faith that not every notion of liberation is necessarily consistent and compatible with an evangelical vision of man, of things and of events; she knows too that in order that God's kingdom should come it is not enough to establish liberation and to create well-being and development.

And what is more, the Church has the firm conviction that all temporal liberation, all political liberation- even if it endeavors to find its justification in such or such a page of the Old or New Testament, even if it claims for its ideological postulates and its norms of action theological data and conclusions, even if it pretends to be today's theology- carries within itself the germ of its own negation and fails to reach the ideal that it proposes for itself whenever its profound motives are not those of justice in charity, whenever its zeal lacks a truly spiritual dimension and whenever its final goal is not salvation and happiness in God.
--

[[evangelii-nuntiandi-36]]
36&#46; The Church considers it to be undoubtedly important to build up structures which are more human, more just, more respectful of the rights of the person and less oppressive and less enslaving, but she is conscious that the best structures and the most idealized systems soon become inhuman if the inhuman inclinations of the human heart are not made wholesome, if those who live in these structures or who rule them do not undergo a conversion of heart and of outlook.

[[evangelii-nuntiandi-37]]
37&#46; The Church cannot accept violence, especially the force of arms- which is uncontrollable once it is let loose- and indiscriminate death as the path to liberation, because she knows that violence always provokes violence and irresistibly engenders new forms of oppression and enslavement which are often harder to bear than those from which they claimed to bring freedom. We said this clearly during our journey in Colombia: "We exhort you not to place your trust in violence and revolution: that is contrary to the Christian spirit, and it can also delay instead of advancing that social uplifting to which you lawfully aspire."{fn-63} "We must say and reaffirm that violence is not in accord with the Gospel, that it is not Christian; and that sudden or violent changes of structures would be deceitful, ineffective of themselves, and certainly not in conformity with the dignity of the people."{fn-64}

[[evangelii-nuntiandi-38]]
--
38&#46; Having said this, we rejoice that the Church is becoming ever more conscious of the proper manner and strictly evangelical means that she possesses in order to collaborate in the liberation of many. And what is she doing? She is trying more and more to encourage large numbers of Christians to devote themselves to the liberation of men. She is providing these Christian "liberators" with the inspiration of faith, the motivation of fraternal love, a social teaching which the true Christian cannot ignore and which he must make the foundation of his wisdom and of his experience in order to translate it concretely into forms of action, participation and commitment. All this must characterize the spirit of a committed Christian, without confusion with tactical attitudes or with the service of a political system. The Church strives always to insert the Christian struggle for liberation into the universal plan of salvation which she herself proclaims.

What we have just recalled comes out more than once in the Synod debates. In fact we devoted to this theme a few clarifying words in our address to the Fathers at the end of the assembly.{fn-65}

It is to be hoped that all these considerations will help to remove the ambiguity which the word "liberation" very often takes on in ideologies, political systems or groups. The liberation which evangelization proclaims and prepares is the one which Christ Himself announced and gave to man by His sacrifice.
--

[[evangelii-nuntiandi-39]]
39&#46; The necessity of ensuring fundamental human rights cannot be separated from this just liberation which is bound up with evangelization and which endeavors to secure structures safeguarding human freedoms. Among these fundamental human rights, religious liberty occupies a place of primary importance. We recently spoke of the relevance of this matter, emphasizing "how many Christians still today, because they are Christians, because they are Catholics, live oppressed by systematic persecution! The drama of fidelity to Christ and of the freedom of religion continues, even if it is disguised by categorical declarations in favor of the rights of the person and of life in society!"{fn-66}
