:fn-67: footnote:[Pope Paul VI, Address to the Members of the Consilium de Laicis (2 October 1974): AAS 66 (1974), p. 568.]
:fn-68: footnote:[Cf. 1 Pt 3:1.]
:fn-69: footnote:[Rom 10:14, 17.]
:fn-70: footnote:[Cf. 1 Cor 2:1-5.]
:fn-71: footnote:[Rom 10:17.]
:fn-72: footnote:[Cf. Mt 10:27; Lk 12:3.]

[[evangelii-nuntiandi-part-4]]
= IV

[[evangelii-nuntiandi-40]]
--
40&#46; The obvious importance of the content of evangelization must not overshadow the importance of the ways and means.

This question of "how to evangelize" is permanently relevant, because the methods of evangelizing vary according to the different circumstances of time, place and culture, and because they thereby present a certain challenge to our capacity for discovery and adaptation.

On us particularly, the pastors of the Church, rests the responsibility for reshaping with boldness and wisdom, but in complete fidelity to the content of evangelization, the means that are most suitable and effective for communicating the Gospel message to the men and women of our times.

Let it suffice, in this meditation, to mention a number of methods which, for one reason or another, have a fundamental importance.
--

[[evangelii-nuntiandi-41]]
41&#46; Without repeating everything that we have already mentioned, it is appropriate first of all to emphasize the following point: for the Church, the first means of evangelization is the witness of an authentically Christian life, given over to God in a communion that nothing should destroy and at the same time given to one's neighbor with limitless zeal. As we said recently to a group of lay people, "Modern man listens more willingly to witnesses than to teachers, and if he does listen to teachers, it is because they are witnesses."{fn-67} St. Peter expressed this well when he held up the example of a reverent and chaste life that wins over even without a word those who refuse to obey the word.{fn-68} It is therefore primarily by her conduct and by her life that the Church will evangelize the world, in other words, by her living witness of fidelity to the Lord Jesus- the witness of poverty and detachment, of freedom in the face of the powers of this world, in short, the witness of sanctity.

[[evangelii-nuntiandi-42]]
--
42&#46; Secondly, it is not superfluous to emphasize the importance and necessity of preaching. "And how are they to believe in him of whom they have never heard? And how are they to hear without a preacher?... So faith comes from what is heard and what is heard comes by the preaching of Christ."{fn-69} This law once laid down by the Apostle Paul maintains its full force today.

Preaching, the verbal proclamation of a message, is indeed always indispensable. We are well aware that modern man is sated by talk; he is obviously often tired of listening and, what is worse, impervious to words. We are also aware that many psychologists and sociologists express the view that modern man has passed beyond the civilization of the word, which is now ineffective and useless, and that today he lives in the civilization of the image. These facts should certainly impel us to employ, for the purpose of transmitting the Gospel message, the modern means which this civilization has produced. Very positive efforts have in fact already been made in this sphere. We cannot but praise them and encourage their further development. The fatigue produced these days by so much empty talk and the relevance of many other forms of communication must not however diminish the permanent power of the word, or cause a loss of confidence in it. The word remains ever relevant, especially when it is the bearer of the power of God.{fn-70} This is why St. Paul's axiom, "Faith comes from what is heard,"{fn-71} also retains its relevance: it is the Word that is heard which leads to belief.
--

[[evangelii-nuntiandi-43]]
--
43&#46; This evangelizing preaching takes on many forms, and zeal will inspire the reshaping of them almost indefinitely. In fact there are innumerable events in life and human situations which offer the opportunity for a discreet but incisive statement of what the Lord has to say in this or that particular circumstance. It suffices to have true spiritual sensitivity for reading God's message in events. But at a time when the liturgy renewed by the Council has given greatly increased value to the Liturgy of the Word, it would be a mistake not to see in the homily an important and very adaptable instrument of evangelization. Of course it is necessary to know and put to good use the exigencies and the possibilities of the homily, so that it can acquire all its pastoral effectiveness. But above all it is necessary to be convinced of this and to devote oneself to it with love. This preaching, inserted in a unique way into the Eucharistic celebration, from which it receives special force and vigor, certainly has a particular role in evangelization, to the extent that it expresses the profound faith of the sacred minister and is impregnated with love. The faithful assembled as a Paschal Church, celebrating the feast of the Lord present in their midst, expect much from this preaching, and will greatly benefit from it provided that it is simple, clear, direct, well-adapted, profoundly dependent on Gospel teaching and faithful to the magisterium, animated by a balanced apostolic ardor coming from its own characteristic nature, full of hope, fostering belief, and productive of peace and unity. Many parochial or other communities live and are held together thanks to the Sunday homily, when it possesses these qualities.

Let us add that, thanks to the same liturgical renewal, the Eucharistic celebration is not the only appropriate moment for the homily. The homily has a place and must not be neglected in the celebration of all the sacraments, at paraliturgies, and in assemblies of the faithful. It will always be a privileged occasion for communicating the Word of the Lord.
--

[[evangelii-nuntiandi-44]]
44&#46; A means of evangelization that must not be neglected is that of catechetical instruction. The intelligence, especially that of children and young people, needs to learn through systematic religious instruction the fundamental teachings, the living content of the truth which God has wished to convey to us and which the Church has sought to express in an ever richer fashion during the course of her long history. No one will deny that this instruction must be given to form patterns of Christian living and not to remain only notional. Truly the effort for evangelization will profit greatly- at the level of catechetical instruction given at church, in the schools, where this is possible, and in every case in Christian homes- if those giving catechetical instruction have suitable texts, updated with wisdom and competence, under the authority of the bishops. The methods must be adapted to the age, culture and aptitude of the persons concerned, they must seek always to fix in the memory, intelligence and heart the essential truths that must impregnate all of life. It is necessary above all to prepare good instructors- parochial catechists, teachers, parents- who are desirous of perfecting themselves in this superior art, which is indispensable and requires religious instruction. Moreover, without neglecting in any way the training of children, one sees that present conditions render ever more urgent catechetical instruction, under the form of the catechumenate, for innumerable young people and adults who, touched by grace, discover little by little the face of Christ and feel the need of giving themselves to Him.

[[evangelii-nuntiandi-45]]
--
45&#46; Our century is characterized by the mass media or means of social communication, and the first proclamation, catechesis or the further deepening of faith cannot do without these means, as we have already emphasized.

When they are put at the service of the Gospel, they are capable of increasing almost indefinitely the area in which the Word of God is heard; they enable the Good News to reach millions of people. The Church would feel guilty before the Lord if she did not utilize these powerful means that human skill is daily rendering more perfect. It is through them that she proclaims "from the housetops"{fn-72} the message of which she is the depositary. In them she finds a modern and effective version of the pulpit. Thanks to them she succeeds in speaking to the multitudes.

Nevertheless the use of the means of social communication for evangelization presents a challenge: through them the evangelical message should reach vast numbers of people, but with the capacity of piercing the conscience of each individual, of implanting itself in his heart as though he were the only person being addressed, with all his most individual and personal qualities, and evoke an entirely personal adherence and commitment.
--

[[evangelii-nuntiandi-46]]
46&#46; For this reason, side by side with the collective proclamation of the Gospel, the other form of transmission, the person-to-person one, remains valid and important. The Lord often used it (for example, with Nicodemus, Zacchaeus, the Samaritan woman, Simon the Pharisee), and so did the apostles. In the long run, is there any other way of handing on the Gospel than by transmitting to another person one's personal experience of faith? It must not happen that the pressing need to proclaim the Good News to the multitudes should cause us to forget this form of proclamation whereby an individual's personal conscience is reached and touched by an entirely unique word that he receives from someone else. We can never sufficiently praise those priests who through the sacrament of Penance or through pastoral dialogue show their readiness to guide people in the ways of the Gospel, to support them in their efforts, to raise them up if they have fallen, and always to assist them with discernment and availability.

[[evangelii-nuntiandi-47]]
--
47&#46; Yet, one can never sufficiently stress the fact that evangelization does not consist only of the preaching and teaching of a doctrine. For evangelization must touch life: the natural life to which it gives a new meaning, thanks to the evangelical perspectives that it reveals; and the supernatural life, which is not the negation but the purification and elevation of the natural life.

This supernatural life finds its living expression in the seven sacraments and in the admirable radiation of grace and holiness which they possess.

Evangelization thus exercises its full capacity when it achieves the most intimate relationship, or better still, a permanent and unbroken intercommunication, between the Word and the sacraments. In a certain sense it is a mistake to make a contrast between evangelization and sacramentalization, as is sometimes done. It is indeed true that a certain way of administering the sacraments, without the solid support of catechesis regarding these same sacraments and a global catechesis, could end up by depriving them of their effectiveness to a great extent. The role of evangelization is precisely to educate people in the faith in such a way as to lead each individual Christian to live the sacraments as true sacraments of faith- and not to receive them passively or reluctantly.
--

[[evangelii-nuntiandi-48]]
--
48&#46; Here we touch upon an aspect of evangelization which cannot leave us insensitive. We wish to speak about what today is often called popular religiosity.

One finds among the people particular expressions of the search for God and for faith, both in the regions where the Church has been established for centuries and where she is in the course of becoming established. These expressions were for a long time regarded as less pure and were sometimes despised, but today they are almost everywhere being rediscovered. During the last Synod the bishops studied their significance with remarkable pastoral realism and zeal.

Popular religiosity, of course, certainly has its limits. It is often subject to penetration by many distortions of religion and even superstitions. It frequently remains at the level of forms of worship not involving a true acceptance by faith. It can even lead to the creation of sects and endanger the true ecclesial community.

But if it is well oriented, above all by a pedagogy of evangelization, it is rich in values. It manifests a thirst for God which only the simple and poor can know. It makes people capable of generosity and sacrifice even to the point of heroism, when it is a question of manifesting belief. It involves an acute awareness of profound attributes of God: fatherhood, providence, loving and constant presence. It engenders interior attitudes rarely observed to the same degree elsewhere: patience, the sense of the cross in daily life, detachment, openness to others, devotion. By reason of these aspects, we readily call it "popular piety," that is, religion of the people, rather than religiosity.

Pastoral charity must dictate to all those whom the Lord has placed as leaders of the ecclesial communities the proper attitude in regard to this reality, which is at the same time so rich and so vulnerable. Above all one must be sensitive to it, know how to perceive its interior dimensions and undeniable values, be ready to help it to overcome its risks of deviation. When it is well oriented, this popular religiosity call be more and more for multitudes of our people a true encounter with God in Jesus Christ.
--
