:fn-73: footnote:[Mk 16:15.]
:fn-74: footnote:[Cf. Saint Justin, I Apol. 46, 1-4: PG 6, II Apol. 7 (8) 1-4; 10, 1-3; 13, 3-4; Florilegium Patristicum II, Bonn 1911, pp. 81, 125, 129, 133; Clement of Alexandria, Stromata I, 19, 91; 94; S. Ch. pp. 117-118; 119-110; Cf. Second Vatican Ecumenical Council, Decree on the Church's Missionary Activity Ad Gentes, 11: AAS 58 (1966), p. 960; cf. Second Vatican Ecumenical Council, Dogmatic Constitution on the Church Lumen Gentium, 17: AAS 57 (1965), p 20.]
:fn-76: footnote:[Cf. Eph 3:8.]
:fn-77: footnote:[Cf. Henri de Lubac, Le drame de l'humanisme athee, ed. Spes, Paris, 1945.]
:fn-78: footnote:[Cf. Pastoral Constitution on the Church in the Modern World Gaudium et Spes, 59: AAS 58 (1966), p. 1080.]
:fn-79: footnote:[1 Tim 2:4.]
:fn-80: footnote:[Mt 9:36; 15:32.]

[[evangelii-nuntiandi-part-5]]
= V

[[evangelii-nuntiandi-49]]
--
49&#46; Jesus' last words in St. Mark's Gospel confer on the evangelization which the Lord entrusts to His apostles a limitless universality: "Go out to the whole world; proclaim the Good News to all creation."{fn-73}

The Twelve and the first generation of Christians understood well the lesson of this text and other similar ones; they made them into a program of action. Even persecution, by scattering the apostles, helped to spread the Word and to establish the Church in ever more distant regions. The admission of Paul to the rank of the apostles and his charism as the preacher to the pagans (the non Jews) of Jesus' Coming underlined this universality still more.
--

[[evangelii-nuntiandi-50]]
--
50&#46; In the course of twenty centuries of history, the generations of Christians have periodically faced various obstacles to this universal mission. On the one hand, on the part of the evangelizers themselves, there has been the temptation for various reasons to narrow down the field of their missionary activity. On the other hand, there has been the often humanly insurmountable resistance of the people being addressed by the evangelizer. Furthermore, we must note with sadness that the evangelizing work of the Church is strongly opposed, if not prevented, by certain public powers Even in our own day it happens that preachers of God's Word are deprived of their rights, persecuted, threatened or eliminated solely for preaching Jesus Christ and His Gospel. But we are confident that despite these painful trials the activity of these apostles will never meet final failure in any part of the world.

Despite such adversities, the Church constantly renews her deepest inspiration, that which comes to her directly from the Lord: To the whole world! To all creation! Right to the ends of the earth! She did this once more at the last Synod, as an appeal not to imprison the proclamation of the Gospel by limiting it to one sector of mankind or to one class of people or to a single type of civilization. Some examples are revealing.
--

[[evangelii-nuntiandi-51]]
--
51&#46; To reveal Jesus Christ and His Gospel to those who do not know them has been, ever since the morning of Pentecost, the fundamental program which the Church has taken on as received from her Founder. The whole of the New Testament, and in a special way the Acts of the Apostles, bears witness to a privileged and in a sense exemplary moment of this missionary effort which will subsequently leave its mark on the whole history of the Church.

She carries out this first proclamation of Jesus Christ by a complex and diversified activity which is sometimes termed "pre-evangelization" but which is already evangelization in a true sense, although at its initial and still incomplete stage. An almost indefinite range of means can be used for this purpose: explicit preaching, of course, but also art, the scientific approach, philosophical research and legitimate recourse to the sentiments of the human heart.
--

[[evangelii-nuntiandi-52]]
52&#46; This first proclamation is addressed especially to those who have never heard the Good News of Jesus, or to children. But, as a result of the frequent situations of dechristianization in our day, it also proves equally necessary for innumerable people who have been baptized but who live quite outside Christian life, for simple people who have a certain faith but an imperfect knowledge of the foundations of that faith, for intellectuals who feel the need to know Jesus Christ in a light different from the instruction they received as children, and for many others.

[[evangelii-nuntiandi-53]]
--
53&#46; This first proclamation is also addressed to the immense sections of mankind who practice non-Christian religions. The Church respects and esteems these non Christian religions because they are the living expression of the soul of vast groups of people. They carry within them the echo of thousands of years of searching for God, a quest which is incomplete but often made with great sincerity and righteousness of heart. They possess an impressive patrimony of deeply religious texts. They have taught generations of people how to pray. They are all impregnated with innumerable "seeds of the Word"{fn-74} and can constitute a true "preparation for the Gospel,"{fn-75} to quote a felicitous term used by the Second Vatican Council and borrowed from Eusebius of Caesarea.

Such a situation certainly raises complex and delicate questions that must be studied in the light of Christian Tradition and the Church's magisterium, in order to offer to the missionaries of today and of tomorrow new horizons in their contacts with non-Christian religions. We wish to point out, above all today, that neither respect and esteem for these religions nor the complexity of the questions raised is an invitation to the Church to withhold from these non-Christians the proclamation of Jesus Christ. On the contrary the Church holds that these multitudes have the right to know the riches of the mystery of Christ{fn-76} - riches in which we believe that the whole of humanity can find, in unsuspected fullness, everything that it is gropingly searching for concerning God, man and his destiny, life and death, and truth. Even in the face of natural religious expressions most worthy of esteem, the Church finds support in the fact that the religion of Jesus, which she proclaims through evangelization, objectively places man in relation with the plan of God, with His living presence and with His action; she thus causes an encounter with the mystery of divine paternity that bends over towards humanity. In other words, our religion effectively establishes with God an authentic and living relationship which the other religions do not succeed in doing, even though they have, as it were, their arms stretched out towards heaven.

This is why the Church keeps her missionary spirit alive, and even wishes to intensify it in the moment of history in which we are living. She feels responsible before entire peoples. She has no rest so long as she has not done her best to proclaim the Good News of Jesus the Savior. She is always preparing new generations of apostles. Let us state this fact with joy at a time when there are not lacking those who think and even say that ardor and the apostolic spirit are exhausted, and that the time of the missions is now past. The Synod has replied that the missionary proclamation never ceases and that the Church will always be striving for the fulfillment of this proclamation.
--

[[evangelii-nuntiandi-54]]
--
54&#46; Nevertheless the Church does not feel dispensed from paving unflagging attention also to those who have received the faith and who have been in contact with the Gospel often for generations. Thus she seeks to deepen, consolidate, nourish and make ever more mature the faith of those who are already called the faithful or believers, in order that they may be so still more.

This faith is nearly always today exposed to secularism, even to militant atheism. It is a faith exposed to trials and threats, and even more, a faith besieged and actively opposed. It runs the risk of perishing from suffocation or starvation if it is not fed and sustained each day. To evangelize must therefore very often be to give this necessary food and sustenance to the faith of believers, especially through a catechesis full of Gospel vitality and in a language suited to people and circumstances.

The Church also has a lively solicitude for the Christians who are not in full communion with her. While preparing with them the unity willed by Christ, and precisely in order to realize unity in truth, she has the consciousness that she would be gravely lacking in her duty if she did not give witness before them of the fullness of the revelation whose deposit she guards.
--

[[evangelii-nuntiandi-55]]
--
55&#46; Also significant is the preoccupation of the last Synod in regard to two spheres which are very different from one another but which at the same time are very close by reason of the challenge which they make to evangelization, each in its own way.

The first sphere is the one which can be called the increase of unbelief in the modern world. The Synod endeavored to describe this modern world: how many currents of thought, values and countervalues, latent aspirations or seeds of destruction, old convictions which disappear and new convictions which arise are covered by this generic name!

From the spiritual point of view, the modern world seems to he forever immersed in what a modern author has termed "the drama of atheistic humanism."{fn-77}

On the one hand one is forced to note in the very heart of this contemporary world the phenomenon which is becoming almost its most striking characteristic: secularism. We are not speaking of secularization, which is the effort, in itself just and legitimate and in no way incompatible with faith or religion, to discover in creation, in each thing or each happening in the universe, the laws which regulate them with a certain autonomy, but with the inner conviction that the Creator has placed these laws there. The last Council has in this sense affirmed the legitimate autonomy of culture and particularly of the sciences.{fn-78} Here we are thinking of a true secularism: a concept of the world according to which the latter is self-explanatory, without any need for recourse to God, who thus becomes superfluous and an encumbrance. This sort of secularism, in order to recognize the power of man, therefore ends up by doing without God and even by denying Him.

New forms of atheism seem to flow from it: a man centered atheism, no longer abstract and metaphysical but pragmatic, systematic and militant. Hand in hand with this atheistic secularism, we are daily faced, under the most diverse forms, with a consumer society, the pursuit of pleasure set up as the supreme value, a desire for power and domination, and discrimination of every kind: the inhuman tendencies of this "humanism."

In this same modern world, on the other hand, and this is a paradox, one cannot deny the existence of real steppingstones to Christianity, and of evangelical values at least in the form of a sense of emptiness or nostalgia. It would not be an exaggeration to say that there exists a powerful and tragic appeal to be evangelized.
--

[[evangelii-nuntiandi-56]]
--
56&#46; The second sphere is that of those who do not practice. Today there is a very large number of baptized people who for the most part have not formally renounced their Baptism but who are entirely indifferent to it and not living in accordance with it. The phenomenon of the non practicing is a very ancient one in the history of Christianity; it is the result of a natural weakness, a profound inconsistency which we unfortunately bear deep within us. Today however it shows certain new characteristics. It is often the result of the uprooting typical of our time. It also springs from the fact that Christians live in close proximity with non-believers and constantly experience the effects of unbelief. Furthermore, the non-practicing Christians of today, more so than those of previous periods, seek to explain and justify their position in the name of an interior religion, of personal independence or authenticity.

Thus we have atheists and unbelievers on the one side and those who do not practice on the other, and both groups put up a considerable resistance to evangelization. The resistance of the former takes the form of a certain refusal and an inability to grasp the new order of things, the new meaning of the world, of life and of history; such is not possible if one does not start from a divine absolute. The resistance of the second group takes the form of inertia and the slightly hostile attitude of the person who feels that he is one of the family, who claims to know it all and to have tried it all and who no longer believes it.

Atheistic secularism and the absence of religious practice are found among adults and among the young, among the leaders of society and among the ordinary people, at all levels of education, and in both the old Churches and the young ones. The Church's evangelizing action cannot ignore these two worlds, nor must it come to a standstill when faced with them; it must constantly seek the proper means and language for presenting, or representing, to them God's revelation and faith in Jesus Christ.
--

[[evangelii-nuntiandi-57]]
--
57&#46; Like Christ during the time of His preaching, like the Twelve on the morning of Pentecost, the Church too sees before her an immense multitude of people who need the Gospel and have a right to it, for God "wants everyone to be saved and reach full knowledge of the truth."{fn-79}

The Church is deeply aware of her duty to preach salvation to all. Knowing that the Gospel message is not reserved to a small group of the initiated, the privileged or the elect, but is destined for everyone, she shares Christ's anguish at the sight of the wandering and exhausted crowds, "like sheep without a shepherd" and she often repeats His words: ''I feel sorry for all these people."{fn-80} But the Church is also conscious of the fact that, if the preaching of the Gospel is to be effective, she must address her message to the heart of the multitudes, to communities of the faithful whose action can and must reach others.
--

[[evangelii-nuntiandi-58]]
--
58&#46; The last Synod devoted considerable attention to these "small communities," or communautes de base, because they are often talked about in the Church today. What are they, and why should they be the special beneficiaries of evangelization and at the same time evangelizers themselves?

According to the various statements heard in the Synod, such communities flourish more or less throughout the Church. They differ greatly among themselves both within the same region and even more so from one region to another.

In some regions they appear and develop, almost without exception, within the Church, having solidarity with her life, being nourished by her teaching and united with her pastors. In these cases, they spring from the need to live the Church's life more intensely, or from the desire and quest for a more human dimension such as larger ecclesial communities can only offer with difficulty, especially in the big modern cities which lend themselves both to life in the mass and to anonymity. Such communities call quite simply be in their own way an extension on the spiritual and religious level- worship, deepening of faith, fraternal charity, prayer, contact with pastors-  of the small sociological community such as the village, etc. Or again their aim may be to bring together, for the purpose of listening to and meditating on the Word, for the sacraments and the bond of the agape, groups of people who are linked by age, culture, civil state or social situation: married couples, young people, professional people, etc.; people who already happen to be united in the struggle for justice, brotherly aid to the poor, human advancement. In still other cases they bring Christians together in places where the shortage of priests does not favor the normal life of a parish community. This is all presupposed within communities constituted by the Church, especially individual Churches and parishes.

In other regions, on the other hand, communautes de base come together in a spirit of bitter criticism of the Church, which they are quick to stigmatize as "institutional" and to which they set themselves Up in opposition as charismatic communities, free from structures and inspired only by the Gospel. Thus their obvious characteristic is an attitude of fault-finding and of rejection with regard to the Church's outward manifestations: her hierarchy, her signs. They are radically opposed to the Church. By following these lines their main inspiration very quickly becomes ideological, and it rarely happens that they do not quickly fall victim to some political option or current of thought, and then to a system, even a party, with all the attendant risks of becoming its instrument.

The difference is already notable: the communities which by their spirit of opposition cut themselves off from the Church, and whose unity they wound, can well be called communautes de base, but in this case it is a strictly sociological name. They could not, without a misuse of terms, be called ecclesial communautes de base, even if while being hostile to the hierarchy, they claim to remain within the unity of the Church. This name belongs to the other groups, those which come together within the Church in order to unite themselves to the Church and to cause the Church to grow.

These latter communities will be a place of evangelization, for the benefit of the bigger communities, especially the individual Churches. And, as we said at the end of the last Synod, they will be a hope for the universal Church to the extent:

-&nbsp;that they seek their nourishment in the Word of God and do not allow themselves to be ensnared by political polarization or fashionable ideologies, which are ready to exploit their immense human potential;

-&nbsp;that they avoid the ever present temptation of systematic protest and a hypercritical attitude, under the pretext of authenticity and a spirit of collaboration;

-&nbsp;that they remain firmly attached to the local Church in which they are inserted, and to the universal Church, thus avoiding the very real danger of becoming isolated within themselves, then of believing themselves to be the only authentic Church of Christ, and hence of condemning the other ecclesial communities;

-&nbsp;that they maintain a sincere communion with the pastors whom the Lord gives to His Church, and with the magisterium which the Spirit of Christ has entrusted to these pastors;

-&nbsp;that they never look on themselves as the sole beneficiaries or sole agents of evangelization- or even the only depositaries of the Gospel- but, being aware that the Church is much more vast and diversified, accept the fact that this Church becomes incarnate in other ways than through themselves;

-&nbsp;that they constantly grow in missionary consciousness, fervor, commitment and zeal;

-&nbsp;that they show themselves to be universal in all things and never sectarian.

On these conditions, which are certainly demanding but also uplifting, the ecclesial communautes de base will correspond to their most fundamental vocation: as hearers of the Gospel which is proclaimed to them and privileged beneficiaries of evangelization, they will soon become proclaimers of the Gospel themselves.
--