:fn-81: footnote:[Rom 10:15.]
:fn-82: footnote:[Declaration on Religious Liberty Dignitatis Humanae, 13: AAS 58 (1966), p 939; cf. Dogmatic Constitution on the Church Lumen Gentium, 5: AAS 57 (1965) pp. 7-8; Decree on the Church's Missionary Activity Ad Gentes, 1: AAS 58 (1966), p. 947.]
:fn-83: footnote:[Decree on the Church's Missionary Activity Ad Gentes, 35: AAS 58 (1966), p. 983.]
:fn-84: footnote:[Saint Augustine, Enarratio in Ps 44:23: CCL XXXVIII, p. 510; cf Decree on the Church's Missionary Activity Ad Gentes, 1: AAS 58 (1966), p. 947.]
:fn-85: footnote:[Saint Gregory the Great, Homil. in Evangelia 19, 1: PL 76, 1154.]
:fn-86: footnote:[Acta 1:8; cf. Didache 9, 1: Fund Patres Apostolici, 1, 22.]
:fn-87: footnote:[Mt 28:20.]
:fn-88: footnote:[Cf. Mt 13:32.]
:fn-89: footnote:[Cf. Mt 13:47.]
:fn-90: footnote:[Cf. Jn 21:11.]
:fn-91: footnote:[Cf. Jn 10:1-16.]
:fn-92: footnote:[Cf. Second Vatican Ecumenical Council, Constitution on the Sacred Liturgy Sacrosanctum Concilium 37-38: AAS 56 (1964), p. 110; cf. also the liturgical books and other documents subsequently issued by the Holy See for the putting into practice of the liturgical reform desired by the same Council.]
:fn-93: footnote:[Paul VI, Address for the closing of the Third General Assembly of the Synod of Bishops (26 October 1974): AAS 66 (1974), p. 636.]
:fn-94: footnote:[Cf. Jn 15:16; Mk 3:13-19; Lk 6:13-16.]
:fn-95: footnote:[Cf. Acts 1:21-22.]
:fn-96: footnote:[Cf. Mk 3:14.]
:fn-97: footnote:[Cf. Mk 3:14-15; Lk 9:2.]
:fn-98: footnote:[Acts 4:8; cf. 2:14; 3:12.]
:fn-99: footnote:[Cf. St. Leo the Great, Sermo 69, 3; Sermo 70, 1-3; Sermo 94, 3; Sermo 95 2: S.C. 200, pp. 50-52; 58-66; 258-260; 268.]
:fn-100: footnote:[Cf. First Ecumenical Council of Lyons, Constitution Ad apostolicae dignitaties: Conciliorum Oecumenicorum Decreta, ed. Istituto per le Scienze Religiose, Bologna 1973, p. 278; Ecumenical Council of Vienne, Constitution Ad providam Christi, ed. cit., p. 343; Fifth Lateran Ecumenical Council, Constitution In apostolici culminis, ed. cit., p. 608; Constitution Postquam ad universalis, ed. cit., p. 614; Constitution Divina disponente clementia, ed. cit., p. 638.]
:fn-101: footnote:[Decree on the Church's Missionary Activity Ad Gentes, 38: AAS 58 (1966), p. 985.]
:fn-102: footnote:[Second Vatican Ecumenical Council, Dogmatic Constitution on the Church Lumen Gentium, 22: AAS 57 (1965), p. 26.]
:fn-103: footnote:[Cf. Second Vatican Ecumenical Council, Dogmatic Constitution on the Church Lumen Gentium, 10, 37; AAS 57 1965), pp. 14, 43; Decree on the Church's Missionary Activity Ad Gentes, 39: AAS 58 (1966), p. 986; Decree on the Ministry and Life of Priests Presbyterorum Ordinis, 2, 12, 13: AAS 58 (1966), pp. 992, 1010, 1011.]
:fn-104: footnote:[Cf. 1 Thess 2:9.]
:fn-105: footnote:[Cf. 1 Pt 5:4.]
:fn-106: footnote:[Dogmatic Constitution on the Church Lumen Gentium, 11: AAS 57 (1965), p. 16; Decree on the Apostolate of the Laity Apostolicam Actuositatem, 11, AAS 58 (1966), p. 848; Saint John Chrysostom, In Genesim Serm. VI, 2; VII, 1: PG 54, 607-68.]

[[evangelii-nuntiandi-part-6]]
= VI

[[evangelii-nuntiandi-59]]
--
59&#46; If people proclaim in the world the Gospel of salvation, they do so by the command of, in the name of and with the grace of Christ the Savior. "They will never have a preacher unless one is sent,"{fn-81} wrote he who was without doubt one of the greatest evangelizers. No one can do it without having been sent.

But who then has the mission of evangelizing?

The Second Vatican Council gave a clear reply to this question: it is upon the Church that "there rests, by divine mandate, the duty of going out into the whole world and preaching the gospel to every creature."{fn-82} And in another text: "...the whole Church is missionary, and the work of evangelization is a basic duty of the People of God."{fn-83}

We have already mentioned this intimate connection between the Church and evangelization. While the Church is proclaiming the kingdom of God and building it up, she is establishing herself in the midst of the world as the sign and instrument of this kingdom which is and which is to come. The Council repeats the following expression of St. Augustine on the missionary activity of the Twelve: "They preached the word of truth and brought forth Churches."{fn-84}
--

[[evangelii-nuntiandi-60]]
--
60&#46; The observation that the Church has been sent out and given a mandate to evangelize the world should awaken in us two convictions.

The first is this: evangelization is for no one an individual and isolated act; it is one that is deeply ecclesial. When the most obscure preacher, catechist or pastor in the most distant land preaches the Gospel, gathers his little community together or administers a sacrament, even alone, he is carrying out an ecclesial act, and his action is certainly attached to the evangelizing activity of the whole Church by institutional relationships, but also by profound invisible links in the order of grace. This presupposes that he acts not in virtue of a mission which he attributes to himself or by a personal inspiration, but in union with the mission of the Church and in her name.

From this flows the second conviction: if each individual evangelizes in the name of the Church, who herself does so by virtue of a mandate from the Lord, no evangelizer is the absolute master of his evangelizing action, with a discretionary power to carry it out in accordance with individualistic criteria and perspectives; he acts in communion with the Church and her pastors.

We have remarked that the Church is entirely and completely evangelizing. This means that, in the whole world and in each part of the world where she is present, the Church feels responsible for the task of spreading the Gospel.
--

[[evangelii-nuntiandi-61]]
--
61&#46; Brothers and sons and daughters, at this stage of our reflection, we wish to pause with you at a question which is particularly important at the present time. In the celebration of the liturgy, in their witness before judges and executioners and in their apologetical texts, the first Christians readily expressed their deep faith in the Church by describing her as being spread throughout the universe. They were fully conscious of belonging to a large community which neither space nor time can limit: From the just Abel right to the last of the elect,{fn-85} "indeed to the ends of the earth,{fn-86} "to the end of time."{fn-87}

This is how the Lord wanted His Church to be: universal, a great tree whose branches shelter the birds of the air,{fn-88} a net which catches fish of every kind{fn-89} or which Peter drew in filled with one hundred and fifty-three big fish,{fn-90} a flock which a single shepherd pastures.{fn-91} A universal Church without boundaries or frontiers except, alas, those of the heart and mind of sinful man.
--

[[evangelii-nuntiandi-62]]
--
62&#46; Nevertheless this universal Church is in practice incarnate in the individual Churches made up of such or such an actual part of mankind, speaking such and such a language, heirs of a cultural patrimony, of a vision of the world, of an historical past, of a particular human substratum. Receptivity to the wealth of the individual Church corresponds to a special sensitivity of modern man.

Let us be very careful not to conceive of the universal Church as the sum, or, if one can say so, the more or less anomalous federation of essentially different individual Churches. In the mind of the Lord the Church is universal by vocation and mission, but when she puts down her roots in a variety of cultural, social and human terrains, she takes on different external expressions and appearances in each part of the world.

Thus each individual Church that would voluntarily cut itself off from the universal Church would lose its relationship to God's plan and would be impoverished in its ecclesial dimension. But, at the same time, a Church toto orbe diffusa would become an abstraction if she did not take body and life precisely through the individual Churches. Only continual attention to these two poles of the Church will enable us to perceive the richness of this relationship between the universal Church and the individual Churches.
--

[[evangelii-nuntiandi-63]]
--
63&#46; The individual Churches, intimately built up not only of people but also of aspirations, of riches and limitations, of ways of praying, of loving, of looking at life and the world, which distinguish this or that human gathering, have the task of assimilating the essence of the Gospel message and of transposing it, without the slightest betrayal of its essential truth, into the language that these particular people understand, then of proclaiming it in this language.

The transposition has to be done with the discernment, seriousness, respect and competence which the matter calls for in the field of liturgical expression,{fn-92} and in the areas of catechesis, theological formulation, secondary ecclesial structures, and ministries. And the word "language" should be understood here less in the semantic or literary sense than in the sense which one may call anthropological and cultural.

The question is undoubtedly a delicate one. Evangelization loses much of its force and effectiveness if it does not take into consideration the actual people to whom it is addresses, if it does not use their language, their signs and symbols, if it does not answer the questions they ask, and if it does not have an impact on their concrete life. But on the other hand, evangelization risks losing its power and disappearing altogether if one empties or adulterates its content under the pretext of translating it; if, in other words, one sacrifices this reality and destroys the unity without which there is no universality, out of a wish to adapt a universal reality to a local situation. Now, only a Church which preserves the awareness of her universality and shows that she is in fact universal is capable of having a message which can be heard by all, regardless of regional frontiers.

Legitimate attention to individual Churches cannot fail to enrich the Church. Such attention is indispensable and urgent. It responds to the very deep aspirations of peoples and human communities to find their own identity ever more clearly.
--

[[evangelii-nuntiandi-64]]
--
64&#46; But this enrichment requires that the individual Churches should keep their profound openness towards the universal Church. It is quite remarkable, moreover, that the most simple Christians, the ones who are most faithful to the Gospel and most open to the true meaning of the Church, have a completely spontaneous sensitivity to this universal dimension. They instinctively and very strongly feel the need for it, they easily recognize themselves in such a dimension. They feel with it and suffer very deeply within themselves when, in the name of theories which they do not understand, they are forced to accept a Church deprived of this universality, a regionalist Church, with no horizon.

As history in fact shows, whenever an individual Church has cut itself off from the universal Church and from its living and visible center- sometimes with the best of intentions, with theological, sociological, political or pastoral arguments, or even in the desire for a certain freedom of movement or action- it has escaped only with great difficulty (if indeed it has escaped) from two equally serious dangers. The first danger is that of a withering isolationism, and then, before long, of a crumbling away, with each of its cells breaking away from it just as it itself has broken away from the central nucleus. The second danger is that of losing its freedom when, being cut off from the center and from the other Churches which gave it strength and energy, it finds itself all alone and a prey to the most varied forces of slavery and exploitation.

The more an individual Church is attached to the universal Church by solid bonds of communion, in charity and loyalty, in receptiveness to the Magisterium of Peter, in the unity of the lex orandi which is also the lex credendi, in the desire for unity with all the other Churches which make up the whole- the more such a Church will be capable of translating the treasure of faith into the legitimate variety of expressions of the profession of faith, of prayer and worship, of Christian life and conduct and of the spiritual influence on the people among which it dwells. The more will it also be truly evangelizing, that is to say, capable of drawing upon the universal patrimony in order to enable its own people to profit from it, and capable too of communicating to the universal Church the experience and the life of this people, for the benefit of all.
--

[[evangelii-nuntiandi-65]]
65&#46; It was precisely in this sense that at the end of the last Synod we spoke clear words full of paternal affection, insisting on the role of Peter's Successor as a visible, living and dynamic principle of the unity between the Churches and thus of the universality of the one Church.{fn-93} We also insisted on the grave responsibility incumbent upon us, but which we share with our Brothers in the Episcopate, of preserving unaltered the content of the Catholic faith which the Lord entrusted to the apostles. While being translated into all expressions, this content must be neither impaired nor mutilated. While being clothed with the outward forms proper to each people, and made explicit by theological expression which takes account of differing cultural, social and even racial milieu, it must remain the content of the Catholic faith just exactly as the ecclesial magisterium has received it and transmits it.

[[evangelii-nuntiandi-66]]
--
66&#46; The whole Church therefore is called upon to evangelize, and yet within her we have different evangelizing tasks to accomplish. This diversity of services in the unity of the same mission makes up the richness and beauty of evangelization. We shall briefly recall these tasks.

First, we would point out in the pages of the Gospel the insistence with which the Lord entrusts to the apostles the task of proclaiming the Word. He chose them,{fn-94} trained them during several years of intimate company,{fn-95} constituted{fn-96} and sent them out{fn-97} as authorized witnesses and teachers of the message of salvation. And the Twelve in their turn sent out their successors who, in the apostolic line, continue to preach the Good News.
--

[[evangelii-nuntiandi-67]]
--
67&#46; The Successor of Peter is thus, by the will of Christ, entrusted with the preeminent ministry of teaching the revealed truth. The New Testament often shows Peter "filled with the Holy Spirit" speaking in the name of all."{fn-98} It is precisely for this reason that St. Leo the Great describes him as he who has merited the primacy of the apostolate.''{fn-99} This is also why the voice of the Church shows the Pope "at the highest point- in apice, in specula- of the apostolate."{fn-100} The Second Vatican Council wished to reaffirm this when it declared that "Christ's mandate to preach the Gospel to every creature (cf. Mk. 16:15) primarily and immediately concerns the bishops with Peter and under Peter."{fn-101}

The full, supreme and universal power"{fn-102} which Christ gives to His Vicar for the pastoral government of His Church is this especially exercised by the Pope in the activity of preaching and causing to be preached the Good News of salvation.
--

[[evangelii-nuntiandi-68]]
--
68&#46; In union with the Successor of Peter, the bishops, who are successors of the apostles, receive through the power of their episcopal ordination the authority to teach the revealed truth in the Church. They are teachers of the faith.

Associated with the bishops in the ministry of evangelization and responsible by a special title are those who through priestly ordination "act in the person of Christ."{fn-103} They are educators of the People of God in the faith and preachers, while at the same time being ministers of the Eucharist and of the other sacraments.

We pastors are therefore invited to take note of this duty, more than any other members of the Church. What identifies our priestly service, gives a profound unity to the thousand and one tasks which claim our attention day by day and throughout our lives, and confers a distinct character on our activities, is this aim, ever present in all our action: to proclaim the Gospel of God.{fn-104}

A mark of our identity which no doubts ought to encroach upon and no objection eclipse is this: as pastors, we have been chosen by the mercy of the Supreme Pastor,{fn-105} in spite of our inadequacy, to proclaim with authority the Word of God, to assemble the scattered People of God, to teed this People with the signs of the action of Christ which are the sacraments, to set this People on the road to salvation, to maintain it in that unity of which we are, at different levels, active and living instruments, and unceasingly to keep this community gathered around Christ faithful to its deepest vocation. And when we do all these things, within our human limits and by the grace of God, it is a work of evangelization that we are carrying out. This includes ourself as Pastor of the universal Church, our brother bishops at the head of the individual Churches, priests and deacons united with their bishops and whose assistants they are, by a communion which has its source in the sacrament of Orders and in the charity of the Church.
--

[[evangelii-nuntiandi-69]]
--
69&#46; Religious, for their part, find in their consecrated life a privileged means of effective evangelization. At the deepest level of their being they are caught Up in the dynamism of the Church's life, which is thirsty for the divine Absolute and called to holiness. It is to this holiness that they bear witness. They embody the Church in her desire to give herself completely to the radical demands of the beatitudes. By their lives they are a sign of total availability to God, the Church and the brethren.

As such they have a special importance in the context of the witness which, as we have said, is of prime importance in evangelization. At the same time as being a challenge to the world and to the Church herself, this silent witness of poverty and abnegation, of purity and sincerity, of self-sacrifice in obedience, can become an eloquent witness capable of touching also non-Christians who have good will and are sensitive to certain values.

In this perspective one perceives the role played in evangelization by religious men and women consecrated to prayer, silence, penance and sacrifice. Other religious, in great numbers, give themselves directly to the proclamation of Christ. Their missionary activity depends clearly on the hierarchy and must be coordinated with the pastoral plan which the latter adopts. But who does not see the immense contribution that these religious have brought and continue to bring to evangelization? Thanks to their consecration they are eminently willing and free to leave everything and to go and proclaim the Gospel even to the ends of the earth. They are enterprising and their apostolate is often marked by an originality, by a genius that demands admiration. They are generous: often they are found at the outposts of the mission, and they take the greatest of risks for their health and their very lives. Truly the Church owes them much.
--

[[evangelii-nuntiandi-70]]
--
70&#46; Lay people, whose particular vocation places them in the midst of the world and in charge of the most varied temporal tasks, must for this very reason exercise a very special form of evangelization.

Their primary and immediate task is not to establish and develop the ecclesial community- this is the specific role of the pastors- but to put to use every Christian and evangelical possibility latent but already present and active in the affairs of the world. Their own field of evangelizing activity is the vast and complicated world of politics, society and economics, but also the world of culture, of the sciences and the arts, of international life, of the mass media. It also includes other realities which are open to evangelization, such as human love, the family, the education of children and adolescents, professional work, suffering. The more Gospel-inspired lay people there are engaged in these realities, clearly involved in them, competent to promote them and conscious that they must exercise to the full their Christian powers which are often buried and suffocated, the more these realities will be at the service of the kingdom of God and therefore of salvation in Jesus Christ, without in any way losing or sacrificing their human content but rather pointing to a transcendent dimension which is often disregarded.
--

[[evangelii-nuntiandi-71]]
--
71&#46; One cannot fail to stress the evangelizing action of the family in the evangelizing apostolate of the laity.

At different moments in the Church's history and also in the Second Vatican Council, the family has well deserved the beautiful name of "domestic Church."{fn-106} This means that there should be found in every Christian family the various aspects of the entire Church. Furthermore, the family, like the Church, ought to be a place where the Gospel is transmitted and from which the Gospel radiates.

In a family which is conscious of this mission, all the members evangelize and are evangelized. The parents not only communicate the Gospel to their children, but from their children they can themselves receive the same Gospel as deeply lived by them.

And such a family becomes the evangelizer of many other families, and of the neighborhood of which it forms part. Families resulting from a mixed marriage also have the duty of proclaiming Christ to the children in the fullness of the consequences of a common Baptism; they have moreover the difficult task of becoming builders of unity.
--

[[evangelii-nuntiandi-72]]
72&#46; Circumstances invite us to make special mention of the young. Their increasing number and growing presence in society and likewise the problems assailing them should awaken in every one the desire to offer them with zeal and intelligence the Gospel ideal as something to be known and lived. And on the other hand, young people who are well trained in faith and prayer must become more and more the apostles of youth. The Church counts greatly on their contribution, and we ourself have often manifested our full confidence in them.

[[evangelii-nuntiandi-73]]
--
73&#46; Hence the active presence of the laity in the temporal realities takes on all its importance. One cannot, however, neglect or forget the other dimension: the laity can also feel themselves called, or be called, to work with their pastors in the service of the ecclesial community for its growth and life, by exercising a great variety of ministries according to the grace and charisms which the Lord is pleased to give them.

We cannot but experience a great inner joy when we see so many pastors, religious and lay people, fired with their mission to evangelize, seeking ever more suitable ways of proclaiming the Gospel effectively. We encourage the openness which the Church is showing today in this direction and with this solicitude. It is an openness to meditation first of all, and then to ecclesial ministries capable of renewing and strengthening the evangelizing vigor of the Church.

It is certain that, side by side with the ordained ministries, whereby certain people are appointed pastors and consecrate themselves in a special way to the service of the community, the Church recognizes the place of non-ordained ministries which are able to offer a particular service to the Church.

A glance at the origins of the Church is very illuminating, and gives the benefit of an early experience in the matter of ministries. It was an experience which was all the more valuable in that it enabled the Church to consolidate herself and to grow and spread. Attention to the sources however has to be complemented by attention to the present needs of mankind and of the Church. To drink at these ever inspiring sources without sacrificing anything of their values, and at the same time to know how to adapt oneself to the demands and needs of today- these are the criteria which will make it possible to seek wisely and to discover the ministries which the Church needs and which many of her members will gladly embrace for the sake of ensuring greater vitality in the ecclesial community. These ministries will have a real pastoral value to the extent that they are established with absolute respect for unity and adhering to the directives of the pastors, who are the ones who are responsible for the Church's unity and the builders thereof.

These ministries, apparently new but closely tied up with the Church's living experience down the centuries - such as catechists, directors of prayer and chant, Christians devoted to the service of God's Word or to assisting their brethren in need, the heads of small communities, or other persons charged with the responsibility of apostolic movements- these ministries are valuable for the establishment, life, and growth of the Church, and for her capacity to influence her surroundings and to reach those who are remote from her. We owe also our special esteem to all the lay people who accept to consecrate a part of their time, their energies, and sometimes their entire lives, to the service of the missions.

A serious preparation is needed for all workers for evangelization. Such preparation is all the more necessary for those who devote themselves to the ministry of the Word. Being animated by the conviction, ceaselessly deepened, of the greatness and riches of the Word of God, those who have the mission of transmitting it must give the maximum attention to the dignity, precision and adaptation of their language. Everyone knows that the art of speaking takes on today a very great importance. How would preachers and catechists be able to neglect this?

We earnestly desire that in each individual Church the bishops should be vigilant concerning the adequate formation of all the ministers of the Word. This serious preparation will increase in them the indispensable assurance and also the enthusiasm to proclaim today Jesus Christ.
--
