:fn-107: footnote:[Mt. 3:17.]
:fn-108: footnote:[Mt. 4:1.]
:fn-109: footnote:[Lk 4:14.]
:fn-110: footnote:[Lk 4:O[18], 21; cf. Is 61:1.]
:fn-111: footnote:[Jn 20:22.]
:fn-112: footnote:[Acts 2:17.]
:fn-113: footnote:[Cf. Acts 4:8.]
:fn-114: footnote:[Cf. Acts 9:17.]
:fn-115: footnote:[Cf. Acts 6:5, 10; 7:55.]
:fn-116: footnote:[Acts 10:44.]
:fn-117: footnote:[Acts 9:31.]
:fn-118: footnote:[Cf. Second Vatican Ecumenical Council, Decree on the Church's Missionary Activity Ad Gentes, 4:AAS 58 (1966), pp. 950-951.]
:fn-119: footnote:[Jn 17:21.]
:fn-120: footnote:[Cf. Acts 20:28.]
:fn-121: footnote:[Cf. Decree on the Ministry and Life of Priests Presbyterorum Ordinis, 13: AAS 58 (1966), p. 1011.]
:fn-122: footnote:[Cf. Heb 11:27.]
:fn-123: footnote:[Decree on the Church's Missionary Activity Ad Gentes, 6: AAS 58 (1966), pp. 954-955; cf. Decree on Ecumenism Unitatis Redintegratio, 1: AAS 57 (1965), pp. 90-91.]
:fn-124: footnote:[Bull Apostolorum Limina, VII: AAS 66 (1974), p. 305.]
:fn-125: footnote:[Rom 5:5.]
:fn-126: footnote:[Cf. Jn 8:32.]
:fn-127: footnote:[1 Thess 2:8; cf. Phil 1:8.]
:fn-128: footnote:[Cf. 1 Thess 2:7-11; 1 Cor 4:15; Gal 4:19.]
:fn-129: footnote:[Cf. 1 Cor 8:9-13; Rom 14:15.]
:fn-130: footnote:[Cf. Rom 12:11.]
:fn-131: footnote:[Cf. Second Vatican Council, Declaration on Religious Liberty Dignitaties Humanae, 4: AAS 58 (1966), p. 933.]
:fn-132: footnote:[Cf. Ibid., 9-14: Loc. Cit., pp. 935-940.]
:fn-133: footnote:[Cf. Second Vatican Ecumenical Council, Decree on the Church's Missionary Activity Ad Gentes, 7: AAS 58 (1966), p. 955.]
:fn-134: footnote:[Cf. Rom 1:16.]

[[evangelii-nuntiandi-part-7]]
= VII

[[evangelii-nuntiandi-74]]
--
74&#46; We would not wish to end this encounter with our beloved brethren and sons and daughters without a pressing appeal concerning the interior attitudes which must animate those who work for evangelization.

In the name of the Lord Jesus Christ, and in the name of the Apostles Peter and Paul, we wish to exhort all those who, thanks to the charisms of the Holy Spirit and to the mandate of the Church, are true evangelizers to be worthy of this vocation, to exercise it without the reticence of doubt or fear, and not to neglect the conditions that will make this evangelization not only possible but also active and fruitful. These, among many others, are the fundamental conditions which we consider it important to emphasize.
--

[[evangelii-nuntiandi-75]]
--
75&#46; Evangelization will never be possible without the action of the Holy Spirit. The Spirit descends on Jesus of Nazareth at the moment of His baptism when the voice of the Father- "This is my beloved Son with whom I am well pleased"{fn-107}- manifests in an external way the election of Jesus and His mission. Jesus is "led by the Spirit" to experience in the desert the decisive combat and the supreme test before beginning this mission.{fn-108} It is "in the power of the Spirit"{fn-109} that He returns to Galilee and begins His preaching at Nazareth, applying to Himself the passage of Isaiah: "The Spirit of the Lord is upon me." And He proclaims: "Today this Scripture has been fulfilled."{fn-110} To the disciples whom He was about to send forth He says, breathing on them, "Receive the Holy Spirit."{fn-111}

In fact, it is only after the coming of the Holy Spirit on the day of Pentecost that the apostles depart to all the ends of the earth in order to begin the great work of the Church's evangelization. Peter explains this event as the fulfillment of the prophecy of Joel: "I will pour out my spirit."{fn-112} Peter is filled with the Holy Spirit so that he can speak to the people about Jesus, the Son of God.{fn-113} Paul too is filled with the Holy Spirit{fn-114} before dedicating himself to his apostolic ministry, as is Stephen when he is chosen for the ministry of service and later on for the witness of blood.{fn-115} The Spirit, who causes Peter, Paul and the Twelve to speak, and who inspires the words that they are to utter, also comes down "on those who heard the word."{fn-116}

It is in the "consolation of the Holy Spirit" that the Church increases.{fn-117} The Holy Spirit is the soul of the Church. It is He who explains to the faithful the deep meaning of the teaching of Jesus and of His mystery. It is the Holy Spirit who, today just as at the beginning of the Church, acts in every evangelizer who allows himself to be possessed and led by Him. The Holy Spirit places on his lips the words which he could not find by himself, and at the same time the Holy Spirit predisposes the soul of the hearer to be open and receptive to the Good News and to the kingdom being proclaimed.

Techniques of evangelization are good, but even the most advanced ones could not replace the gentle action of the Spirit. The most perfect preparation of the evangelizer has no effect without the Holy Spirit. Without the Holy Spirit the most convincing dialectic has no power over the heart of man. Without Him the most highly developed schemas resting on a sociological or psychological basis are quickly seen to be quite valueless.

We live in the Church at a privileged moment of the Spirit. Everywhere people are trying to know Him better, as the Scripture reveals Him. They are happy to place themselves under His inspiration. They are gathering about Him; they want to let themselves be led by Him. Now if the Spirit of God has a preeminent place in the whole life of the Church, it is in her evangelizing mission that He is most active. It is not by chance that the great inauguration of evangelization took place on the morning of Pentecost, under the inspiration of the Spirit.

It must be said that the Holy Spirit is the principal agent of evangelization: it is He who impels each individual to proclaim the Gospel, and it is He who in the depths of consciences causes the word of salvation to be accepted and understood.{fn-118} But it can equally be said that He is the goal of evangelization: He alone stirs up the new creation, the new humanity of which evangelization is to be the result, with that unity in variety which evangelization wishes to achieve within the Christian community. Through the Holy Spirit the Gospel penetrates to the heart of the world, for it is He who causes people to discern the signs of the times- signs willed by God- which evangelization reveals and puts to use within history.

The Bishops' Synod of 1974, which insisted strongly on the place of the Holy Spirit in evangelization, also expressed the desire that pastors and theologians- and we would also say the faithful marked by the seal of the Spirit by Baptism- should study more thoroughly the nature and manner of the Holy Spirit's action in evangelization today. This is our desire too, and we exhort all evangelizers, whoever they may be, to pray without ceasing to the Holy Spirit with faith and fervor and to let themselves prudently be guided by Him as the decisive inspirer of their plans, their initiatives and their evangelizing activity.
--

[[evangelii-nuntiandi-76]]
--
76&#46; Let us now consider the very persons of the evangelizers.

It is often said nowadays that the present century thirsts for authenticity. Especially in regard to young people it is said that they have a horror of the artificial or false and that they are searching above all for truth and honesty.

These "signs of the times" should find us vigilant. Either tacitly or aloud- but always forcefully- we are being asked: Do you really believe what you are proclaiming? Do you live what you believe? Do you really preach what you live? The witness of life has become more than ever an essential condition for real effectiveness in preaching. Precisely because of this we are, to a certain extent, responsible for the progress of the Gospel that we proclaim.

"What is the state of the Church ten years after the Council?" we asked at the beginning of this meditation. Is she firmly established in the midst of the world and yet free and independent enough to call for the world's attention? Does she testify to solidarity with people and at the same time to the divine Absolute? Is she more ardent in contemplation and adoration and more zealous in missionary, charitable and liberating action? Is she ever more committed to the effort to search for the restoration of the complete unity of Christians, a unity that makes more effective the common witness, "so that the world may believe"{fn-119} We are all responsible for the answers that could be given to these questions.

We therefore address our exhortation to our brethren in the Episcopate, placed by the Holy Spirit to govern the Church.{fn-120} We exhort the priests and deacons, the bishops' collaborators in assembling the People of God and in animating spiritually the local communities. We exhort the religious, witnesses of a Church called to holiness and hence themselves invited to a life that bears testimony to the beatitudes of the Gospel. We exhort the laity: Christian families, youth, adults, all those who exercise a trade or profession, leaders, without forgetting the poor who are often rich in faith and hope- all lay people who are conscious of their evangelizing role in the service of their Church or in the midst of society and the world. We say to all of them: our evangelizing zeal must spring from true holiness of life, and, as the Second Vatican Council suggests, preaching must in its turn make the preacher grow in holiness, which is nourished by prayer and above all by love for the Eucharist.{fn-121}

The world which, paradoxically, despite innumerable signs of the denial of God, is nevertheless searching for Him in unexpected ways and painfully experiencing the need of Him- the world is calling for evangelizers to speak to it of a God whom the evangelists themselves should know and be familiar with as if they could see the invisible.{fn-122} The world calls for and expects from us simplicity of life, the spirit of prayer, charity towards all, especially towards the lowly and the poor, obedience and humility, detachment and self-sacrifice. Without this mark of holiness, our word will have difficulty in touching the heart of modern man. It risks being vain and sterile.
--

[[evangelii-nuntiandi-77]]
--
77&#46; The power of evangelization will find itself considerably diminished if those who proclaim the Gospel are divided among themselves in all sorts of ways. Is this not perhaps one of the great sicknesses of evangelization today? Indeed, if the Gospel that we proclaim is seen to be rent by doctrinal disputes, ideological polarizations or mutual condemnations among Christians, at the mercy of the latter's differing views on Christ and the Church and even because of their different concepts of society and human institutions, how can those to whom we address our preaching fail to be disturbed, disoriented, even scandalized?

The Lord's spiritual testament tells us that unity among His followers is not only the proof that we are His but also the proof that He is sent by the Father. It is the test of the credibility of Christians and of Christ Himself. As evangelizers, we must offer Christ's faithful not the image of people divided and separated by unedifying quarrels, but the image of people who are mature in faith and capable of finding a meeting-point beyond the real tensions, thanks to a shared, sincere and disinterested search for truth. Yes, the destiny of evangelization is certainly bound up with the witness of unity given by the Church. This is a source of responsibility and also of comfort.

At this point we wish to emphasize the sign of unity among all Christians as the way and instrument of evangelization. The division among Christians is a serious reality which impedes the very work of Christ. The Second Vatican Council states clearly and emphatically that this division "damages the most holy cause of preaching the Gospel to all men, and it impedes many from embracing the faith."{fn-123} For this reason, in proclaiming the Holy Year we considered it necessary to recall to all the faithful of the Catholic world that "before all men can be brought together and restored to the grace of God our Father, communion must be reestablished between those who by faith have acknowledged and accepted Jesus Christ as the Lord of mercy who sets men free and unites them in the Spirit of love and truth."{fn-124}

And it is with a strong feeling of Christian hope that look to the efforts being made in the Christian world for this restoration of the full unity willed by Christ. St. Paul assures us that "hope does not disappoint us."{fn-125} While we still work to obtain full unity from the Lord, we wish to see prayer intensified. Moreover we make our own the desire of the Fathers of the Third General Assembly of the Synod of Bishops, for a collaboration marked by greater commitment with the Christian brethren with whom we are not yet united in perfect unity, taking as a basis the foundation of Baptism and the patrimony of faith which is common to us. By doing this we can already give a greater common witness to Christ before the world in the very work of evangelization. Christ's command urges us to do this; the duty of preaching and of giving witness to the Gospel requires this.
--

[[evangelii-nuntiandi-78]]
--
78&#46; The Gospel entrusted to us is also the word of truth. A truth which liberates{fn-126} and which alone gives peace of heart is what people are looking for when we proclaim the Good News to them. The truth about God, about man and his mysterious destiny, about the world; the difficult truth that we seek in the Word of God and of which, we repeat, we are neither the masters nor the owners, but the depositaries, the heralds and the servants.

Every evangelizer is expected to have a reverence for truth, especially since the truth that he studies and communicates is none other than revealed truth and hence, more than any other, a sharing in the first truth which is God Himself. The preacher of the Gospel will therefore be a person who even at the price of personal renunciation and suffering always seeks the truth that he must transmit to others. He never betrays or hides truth out of a desire to please men, in order to astonish or to shock, nor for the sake of originality or a desire to make an impression. He does not refuse truth. He does not obscure revealed truth by being too idle to search for it, or for the sake of his own comfort, or out of fear. He does not neglect to study it. He serves it generously, without making it serve him.

We are the pastors of the faithful people, and our pastoral service impels us to preserve, defend, and to communicate the truth regardless of the sacrifices that this involves. So many eminent and holy pastors have left us the example of this love of truth. In many cases it was an heroic love. The God of truth expects us to be the vigilant defenders and devoted preachers of truth.

Men of learning- whether you be theologians, exegetes or historians- the work of evangelization needs your tireless work of research, and also care and tact in transmitting the truth to which your studies lead you but which is always greater than the heart of man, being the very truth of God.

Parents and teachers, your task- and the many conflicts of the present day do not make it an easy one- is to help your children and your students to discover truth, including religious and spiritual truth.
--

[[evangelii-nuntiandi-79]]
--
79&#46; The work of evangelization presupposes in the evangelizer an ever increasing love for those whom he is evangelizing. That model evangelizer, the Apostle Paul, wrote these words to the Thessalonians, and they are a program for us all: "With such yearning love we chose to impart to you not only the gospel of God but our very selves, so dear had you become to us."{fn-127} What is this love? It is much more than that of a teacher; it is the love of a father; and again, it is the love of a mother.{fn-128} It is this love that the Lord expects from every preacher of the Gospel, from every builder of the Church. A sign of love will be the concern to give the truth and to bring people into unity. Another sign of love will be a devotion to the proclamation of Jesus Christ, without reservation or turning back. Let us add some other signs of this love.

The first is respect for the religious and spiritual situation of those being evangelized. Respect for their tempo and pace; no one has the right to force them excessively. Respect for their conscience and convictions, which are not to be treated in a harsh manner.

Another sign of this love is concern not to wound the other person, especially if he or she is weak in faith,{fn-129} with statements that may be clear for those who are already initiated but which for the faithful can be a source of bewilderment and scandal, like a wound in the soul.

Yet another sign of love will be the effort to transmit to Christians not doubts and uncertainties born of an erudition poorly assimilated but certainties that are solid because they are anchored in the Word of God. The faithful need these certainties for their Christian life; they have a right to them, as children of God who abandon themselves entirely into His arms and to the exigencies of love.
--

[[evangelii-nuntiandi-80]]
--
80&#46; Our appeal here is inspired by the fervor of the greatest preachers and evangelizers, whose lives were devoted to the apostolate. Among these we are glad to point out those whom we have proposed to the veneration of the faithful during the course of the Holy Year. They have known how to overcome many obstacles to evangelization.

Such obstacles are also present today, and we shall limit ourself to mentioning the lack of fervor. It is all the more serious because it comes from within. It is manifested in fatigue, disenchantment, compromise, lack of interest and above all lack of joy and hope. We exhort all those who have the task of evangelizing, by whatever title and at whatever level, always to nourish spiritual fervor{fn-130}

This fervor demands first of all that we should know how to put aside the excuses which would impede evangelization. The most insidious of these excuses are certainly the ones which people claim to find support for in such and such a teaching of the Council.

Thus one too frequently hears it said, in various terms, that to impose a truth, be it that of the Gospel, or to impose a way, be it that of salvation, cannot but be a violation of religious liberty. Besides, it is added, why proclaim the Gospel when the whole world is saved by uprightness of heart? We know likewise that the world and history are filled with "seeds of the Word"; is it not therefore an illusion to claim to bring the Gospel where it already exists in the seeds that the Lord Himself has sown?

Anyone who takes the trouble to study in the Council's documents the questions upon which these excuses draw too superficially will find quite a different view.

It would certainly be an error to impose something on the consciences of our brethren. But to propose to their consciences the truth of the Gospel and salvation in Jesus Christ, with complete clarity and with a total respect for the free options which it presents- "without coercion, or dishonorable or unworthy pressure"{fn-131}- far from being an attack on religious liberty is fully to respect that liberty, which is offered the choice of a way that even non-believers consider noble and uplifting. Is it then a crime against others' freedom to proclaim with joy a Good News which one has come to know through the Lord's mercy?{fn-132} And why should only falsehood and error, debasement and pornography have the right to be put before people and often unfortunately imposed on them by the destructive propaganda of the mass media, by the tolerance of legislation, the timidity of the good and the impudence of the wicked? The respectful presentation of Christ and His kingdom is more than the evangelizer's right; it is his duty. It is likewise the right of his fellow men to receive from him the proclamation of the Good News of salvation. God can accomplish this salvation in whomsoever He wishes by ways which He alone knows.{fn-133} And yet, if His Son came, it was precisely in order to reveal to us, by His word and by His life, the ordinary paths of salvation. And He has commanded us to transmit this revelation to others with His own authority. It would be useful if every Christian and every evangelizer were to pray about the following thought: men can gain salvation also in other ways, by God's mercy, even though we do not preach the Gospel to them; but as for us, can we gain salvation if through negligence or fear or shame- what St. Paul called "blushing for the Gospel"{fn-134} - or as a result of false ideas we fail to preach it? For that would be to betray the call of God, who wishes the seed to bear fruit through the voice of the ministers of the Gospel; and it will depend on us whether this grows into trees and produces its full fruit.

Let us therefore preserve our fervor of spirit. Let us preserve the delightful and comforting joy of evangelizing, even when it is in tears that we must sow. May it mean for us- as it did for John the Baptist, for Peter and Paul, for the other apostles and for a multitude of splendid evangelizers all through the Church's history- an interior enthusiasm that nobody and nothing can quench. May it be the great joy of our consecrated lives. And may the world of our time, which is searching, sometimes with anguish, sometimes with hope, be enabled to receive the Good News not from evangelizers who are dejected, discouraged, impatient or anxious, but from ministers of the Gospel whose lives glow with fervor, who have first received the joy of Christ, and who are willing to risk their lives so that the kingdom may be proclaimed and the Church established in the midst of the world.
--
