:fn-135: footnote:[Phil 1:3-4, 7-8.]

[[evangelii-nuntiandi-conclusion]]
= CONCLUSION

[[evangelii-nuntiandi-81]]
--
81&#46; This then, brothers and sons and daughters, is our heartfelt plea. It echoes the voice of our brethren assembled for the Third General Assembly of the Synod of Bishops. This is the task we have wished to give you at the close of a Holy Year which has enabled us to see better than ever the needs and the appeals of a multitude of brethren, both Christians and non-Christians, who await from the Church the Word of salvation.

May the light of the Holy Year, which has shone in the local Churches and in Rome for millions of consciences reconciled with God, continue to shine in the same way after the Jubilee through a program of pastoral action with evangelization as its basic feature, for these years which mark the eve of a new century, the eve also of the third millennium of Christianity.
--

[[evangelii-nuntiandi-82]]
--
82&#46; This is the desire that we rejoice to entrust to the hands and the heart of the Immaculate Blessed Virgin Mary, on this day which is especially consecrated to her and which is also the tenth anniversary of the close of the Second Vatican Council. On the morning of Pentecost she watched over with her prayer the beginning of evangelization prompted by the Holy Spirit: may she be the Star of the evangelization ever renewed which the Church, docile to her Lord's command, must promote and accomplish, especially in these times which are difficult but full of hope!

In the name of Christ we bless you, your communities, your families, all those who are dear to you, in the words which Paul addressed to the Philippians: "I give thanks to my God every time I think of you- which is constantly, in every prayer I utter- rejoicing, as I plead on your behalf, at the way you have all continually helped to promote the gospel.... I hold all of you dear- you who...are sharers of my gracious lot...to defend the solid grounds on which the gospel rests. God himself can testify how much I long for each of you with the affection of Christ Jesus!"{fn-135}
--

Given in Rome, at Saint Peter's, on the Solemnity of the Immaculate Conception of the Blessed Virgin Mary, December 8, 1975, the thirteenth year of our Pontificate.

[.text-center]
PAULUS PP. VI
