[[mark]]
= The Gospel of Mark
:short: Mark

[[mark-1]]
== Chapter 1

[[mark-1-1]]
^1^ The beginning of the Gospel of Jesus Christ, the Son of God.

[[mark-1-2]]
^2^ As it has been written by the prophet Isaiah: “Behold, I send my Angel before your face, who shall prepare your way before you.

[[mark-1-3]]
^3^ The voice of one crying out in the desert: Prepare the way of the Lord; make straight his paths.”

[[mark-1-4]]
^4^ John was in the desert, baptizing and preaching a baptism of repentance, as a remission of sins.

[[mark-1-5]]
^5^ And there went out to him all the region of Judea and all those of Jerusalem, and they were baptized by him in the river Jordan, confessing their sins.

[[mark-1-6]]
^6^ And John was clothed with camel’s hair and with a leather belt around his waist. And he ate locusts and wild honey.

[[mark-1-7]]
^7^ And he preached, saying: “One stronger than me comes after me. I am not worthy to reach down and loosen the laces of his shoes.

[[mark-1-8]]
^8^ I have baptized you with water. Yet truly, he will baptize you with the Holy Spirit.”

[[mark-1-9]]
^9^ And it happened that, in those days, Jesus arrived from Nazareth of Galilee. And he was baptized by John in the Jordan.

[[mark-1-10]]
^10^ And immediately, upon ascending from the water, he saw the heavens opened and the Spirit, like a dove, descending, and remaining with him.

[[mark-1-11]]
^11^ And there was a voice from heaven: “You are my beloved Son; in you I am well pleased.”

[[mark-1-12]]
^12^ And immediately the Spirit prompted him into the desert.

[[mark-1-13]]
^13^ And he was in the desert for forty days and forty nights. And he was tempted by Satan. And he was with the wild animals, and the Angels ministered to him.

[[mark-1-14]]
^14^ Then, after John was handed over, Jesus went into Galilee, preaching the Gospel of the kingdom of God,

[[mark-1-15]]
^15^ and saying: “For the time has been fulfilled and the kingdom of God has drawn near. Repent and believe in the Gospel.”

[[mark-1-16]]
^16^ And passing by the shore of the Sea of Galilee, he saw Simon and his brother Andrew, casting nets into the sea, for they were fishermen.

[[mark-1-17]]
^17^ And Jesus said to them, “Come after me, and I will make you fishers of men.”

[[mark-1-18]]
^18^ And at once abandoning their nets, they followed him.

[[mark-1-19]]
^19^ And continuing on a little ways from there, he saw James of Zebedee and his brother John, and they were mending their nets in a boat.

[[mark-1-20]]
^20^ And immediately he called them. And leaving behind their father Zebedee in the boat with his hired hands, they followed him.

[[mark-1-21]]
^21^ And they entered into Capernaum. And entering into the synagogue promptly on the Sabbaths, he taught them.

[[mark-1-22]]
^22^ And they were astonished over his doctrine. For he was teaching them as one who has authority, and not like the scribes.

[[mark-1-23]]
^23^ And in their synagogue, there was a man with an unclean spirit; and he cried out,

[[mark-1-24]]
^24^ saying: “What are we to you, Jesus of Nazareth? Have you come to destroy us? I know who you are: the Holy One of God.”

[[mark-1-25]]
^25^ And Jesus admonished him, saying, “Be silent, and depart from the man.”

[[mark-1-26]]
^26^ And the unclean spirit, convulsing him and crying out with a loud voice, departed from him.

[[mark-1-27]]
^27^ And they were all so amazed that they inquired among themselves, saying: “What is this? And what is this new doctrine? For with authority he commands even the unclean spirits, and they obey him.”

[[mark-1-28]]
^28^ And his fame went out quickly, throughout the entire region of Galilee.

[[mark-1-29]]
^29^ And soon after departing from the synagogue, they went into the house of Simon and Andrew, with James and John.

[[mark-1-30]]
^30^ But the mother-in-law of Simon lay ill with a fever. And at once they told him about her.

[[mark-1-31]]
^31^ And drawing near to her, he raised her up, taking her by the hand. And immediately the fever left her, and she ministered to them.

[[mark-1-32]]
^32^ Then, when evening arrived, after the sun had set, they brought to him all who had maladies and those who had demons.

[[mark-1-33]]
^33^ And the entire city was gathered together at the door.

[[mark-1-34]]
^34^ And he healed many who were troubled with various illnesses. And he cast out many demons, but he would not permit them to speak, because they knew him.

[[mark-1-35]]
^35^ And rising up very early, departing, he went out to a deserted place, and there he prayed.

[[mark-1-36]]
^36^ And Simon, and those who were with him, followed after him.

[[mark-1-37]]
^37^ And when they had found him, they said to him, “For everyone is seeking you.”

[[mark-1-38]]
^38^ And he said to them: “Let us go into the neighboring towns and cities, so that I may preach there also. Indeed, it was for this reason that I came.”

[[mark-1-39]]
^39^ And he was preaching in their synagogues and throughout all of Galilee, and casting out demons.

[[mark-1-40]]
^40^ And a leper came to him, begging him. And kneeling down, he said to him, “If you are willing, you are able to cleanse me.”

[[mark-1-41]]
^41^ Then Jesus, taking pity on him, reached out his hand. And touching him, he said to him: “I am willing. Be cleansed.”

[[mark-1-42]]
^42^ And after he had spoken, immediately the leprosy departed from him, and he was cleansed.

[[mark-1-43]]
^43^ And he admonished him, and he promptly sent him away.

[[mark-1-44]]
^44^ And he said to him: “See to it that you tell no one. But go and show yourself to the high priest, and offer for your cleansing that which Moses instructed, as a testimony for them.”

[[mark-1-45]]
^45^ But having departed, he began to preach and to disseminate the word, so that he was no longer able to openly enter a city, but had to remain outside, in deserted places. And they were gathered to him from every direction.


[[mark-2]]
== Chapter 2

[[mark-2-1]]
^1^ And after some days, he again entered into Capernaum.

[[mark-2-2]]
^2^ And it was heard that he was in the house. And so many gathered that there was no room left, not even at the door. And he spoke the word to them.

[[mark-2-3]]
^3^ And they came to him, bringing a paralytic, who was being carried by four men.

[[mark-2-4]]
^4^ And when they were not able to present him to him because of the crowd, they uncovered the roof where he was. And opening it, they lowered down the stretcher on which the paralytic was lying.

[[mark-2-5]]
^5^ Then, when Jesus had seen their faith, he said to the paralytic, “Son, your sins are forgiven you.”

[[mark-2-6]]
^6^ But some of the scribes were sitting in that place and thinking in their hearts:

[[mark-2-7]]
^7^ “Why is this man speaking in this way? He is blaspheming. Who can forgive sins, but God alone?”

[[mark-2-8]]
^8^ At once, Jesus, realizing in his spirit that they were thinking this within themselves, said to them: “Why are you thinking these things in your hearts?

[[mark-2-9]]
^9^ Which is easier, to say to the paralytic, ‘Your sins are forgiven you,’ or to say, ‘Rise up, take up your stretcher, and walk?’

[[mark-2-10]]
^10^ But so that you may know that the Son of man has authority on earth to forgive sins,” he said to the paralytic:

[[mark-2-11]]
^11^ “I say to you: Rise up, take up your stretcher, and go into your house.”

[[mark-2-12]]
^12^ And immediately he got up, and lifting up his stretcher, he went away in the sight of them all, so that they all wondered. And they honored God, by saying, “We have never seen anything like this.”

[[mark-2-13]]
^13^ And he departed again to the sea. And the entire crowd came to him, and he taught them.

[[mark-2-14]]
^14^ And as he was passing by, he saw Levi of Alphaeus, sitting at the customs office. And he said to him, “Follow me.” And rising up, he followed him.

[[mark-2-15]]
^15^ And it happened that, as he sat at table in his house, many tax collectors and sinners sat at table together with Jesus and his disciples. For those who followed him were many.

[[mark-2-16]]
^16^ And the scribes and the Pharisees, seeing that he ate with tax collectors and sinners, said to his disciples, “Why does your Teacher eat and drink with tax collectors and sinners?”

[[mark-2-17]]
^17^ Jesus, having heard this, said to them: “The healthy have no need of a doctor, but those who have maladies do. For I came not to call the just, but sinners.”

[[mark-2-18]]
^18^ And the disciples of John, and the Pharisees, were fasting. And they arrived and said to him, “Why do the disciples of John and of the Pharisees fast, but your disciples do not fast?”

[[mark-2-19]]
^19^ And Jesus said to them: “How can the sons of the wedding fast while the groom is still with them? During whatever time they have the groom with them, they are not able to fast.

[[mark-2-20]]
^20^ But the days will arrive when the groom will be taken away from them, and then they shall fast, in those days.

[[mark-2-21]]
^21^ No one sews a patch of new cloth onto an old garment. Otherwise, the new addition pulls away from the old, and the tear becomes worse.

[[mark-2-22]]
^22^ And no one puts new wine into old wineskins. Otherwise, the wine will burst the wineskins, and the wine will pour out, and the wineskins will be lost. Instead, new wine must be put into new wineskins.”

[[mark-2-23]]
^23^ And again, while the Lord was walking through the ripe grain on the Sabbath, his disciples, as they advanced, began to separate the ears of grains.

[[mark-2-24]]
^24^ But the Pharisees said to him, “Behold, why are they doing what is not lawful on the Sabbaths?”

[[mark-2-25]]
^25^ And he said to them: “Have you never read what David did, when he had need and was hungry, both he and those who were with him?

[[mark-2-26]]
^26^ How he went into the house of God, under the high priest Abiathar, and ate the bread of the Presence, which it was not lawful to eat, except for the priests, and how he gave it to those who were with him?”

[[mark-2-27]]
^27^ And he said to them: “The Sabbath was made for man, and not man for the Sabbath.

[[mark-2-28]]
^28^ And so, the Son of man is Lord, even of the Sabbath.”


[[mark-3]]
== Chapter 3

[[mark-3-1]]
^1^ And again, he entered into the synagogue. And there was a man there who had a withered hand.

[[mark-3-2]]
^2^ And they observed him, to see if he would cure on the Sabbaths, so that they might accuse him.

[[mark-3-3]]
^3^ And he said to the man who had the withered hand, “Stand up in the middle.”

[[mark-3-4]]
^4^ And he said to them: “Is it lawful to do good on the Sabbaths, or to do evil, to give health to a life, or to destroy?” But they remained silent.

[[mark-3-5]]
^5^ And looking around at them with anger, being very saddened over the blindness of their hearts, he said to the man, “Extend your hand.” And he extended it, and his hand was restored to him.

[[mark-3-6]]
^6^ Then the Pharisees, going out, immediately took counsel with the Herodians against him, as to how they might destroy him.

[[mark-3-7]]
^7^ But Jesus withdrew with his disciples to the sea. And a great crowd followed him from Galilee and Judea,

[[mark-3-8]]
^8^ and from Jerusalem, and from Idumea and across the Jordan. And those around Tyre and Sidon, upon hearing what he was doing, came to him in a great multitude.

[[mark-3-9]]
^9^ And he told his disciples that a small boat would be useful to him, because of the crowd, lest they press upon him.

[[mark-3-10]]
^10^ For he healed so many, that as many of them as had wounds would rush toward him in order to touch him.

[[mark-3-11]]
^11^ And the unclean spirits, when they saw him, fell prostrate before him. And they cried out, saying,

[[mark-3-12]]
^12^ “You are the Son of God.” And he strongly admonished them, lest they make him known.

[[mark-3-13]]
^13^ And ascending onto a mountain, he called to himself those whom he willed, and they came to him.

[[mark-3-14]]
^14^ And he acted so that the twelve would be with him, and so that he might send them out to preach.

[[mark-3-15]]
^15^ And he gave them authority to cure infirmities, and to cast out demons:

[[mark-3-16]]
^16^ and he imposed on Simon the name Peter;

[[mark-3-17]]
^17^ and also he imposed on James of Zebedee, and John the brother of James, the name ‘Boanerges,’ that is, ‘Sons of Thunder;’

[[mark-3-18]]
^18^ and Andrew, and Philip, and Bartholomew, and Matthew, and Thomas, and James of Alphaeus, and Thaddeus, and Simon the Canaanite,

[[mark-3-19]]
^19^ and Judas Iscariot, who also betrayed him.

[[mark-3-20]]
^20^ And they went to a house, and the crowd gathered together again, so much so that they were not even able to eat bread.

[[mark-3-21]]
^21^ And when his own had heard of it, they went out to take hold of him. For they said: “Because he has gone mad.”

[[mark-3-22]]
^22^ And the scribes who had descended from Jerusalem said, “Because he has Beelzebub, and because by the prince of demons does he cast out demons.”

[[mark-3-23]]
^23^ And having called them together, he spoke to them in parables: “How can Satan cast out Satan?

[[mark-3-24]]
^24^ For if a kingdom is divided against itself, that kingdom is not able to stand.

[[mark-3-25]]
^25^ And if a house is divided against itself, that house is not able to stand.

[[mark-3-26]]
^26^ And if Satan has risen up against himself, he would be divided, and he would not be able to stand; instead he reaches the end.

[[mark-3-27]]
^27^ No one is able to plunder the goods of a strong man, having entered into the house, unless he first binds the strong man, and then he shall plunder his house.

[[mark-3-28]]
^28^ Amen I say to you, that all sins will be forgiven the sons of men, and the blasphemies by which they will have blasphemed.

[[mark-3-29]]
^29^ But he who will have blasphemed against the Holy Spirit shall not have forgiveness in eternity; instead he shall be guilty of an eternal offense.”

[[mark-3-30]]
^30^ For they said: “He has an unclean spirit.”

[[mark-3-31]]
^31^ And his mother and brothers arrived. And standing outside, they sent to him, calling him.

[[mark-3-32]]
^32^ And the crowd was sitting around him. And they said to him, “Behold, your mother and your brothers are outside, seeking you.”

[[mark-3-33]]
^33^ And responding to them, he said, “Who is my mother and my brothers?”

[[mark-3-34]]
^34^ And looking around at those who were sitting all around him, he said: “Behold, my mother and my brothers.

[[mark-3-35]]
^35^ For whoever has done the will of God, the same is my brother, and my sister and mother.”


[[mark-4]]
== Chapter 4

[[mark-4-1]]
^1^ And again, he began to teach by the sea. And a great crowd was gathered to him, so much so that, climbing into a boat, he was seated on the sea. And the entire crowd was on the land along the sea.

[[mark-4-2]]
^2^ And he taught them many things in parables, and he said to them, in his doctrine:

[[mark-4-3]]
^3^ “Listen. Behold, the sower went out to sow.

[[mark-4-4]]
^4^ And while he was sowing, some fell along the way, and the birds of the air came and ate it.

[[mark-4-5]]
^5^ Yet truly, others fell upon stony ground, where it did not have much soil. And it rose up quickly, because it had no depth of soil.

[[mark-4-6]]
^6^ And when the sun was risen, it was scorched. And because it had no root, it withered away.

[[mark-4-7]]
^7^ And some fell among thorns. And the thorns grew up and suffocated it, and it did not produce fruit.

[[mark-4-8]]
^8^ And some fell on good soil. And it brought forth fruit that grew up, and increased, and yielded: some thirty, some sixty, and some one hundred.”

[[mark-4-9]]
^9^ And he said, “Whoever has ears to hear, let him hear.”

[[mark-4-10]]
^10^ And when he was alone, the twelve, who were with him, questioned him about the parable.

[[mark-4-11]]
^11^ And he said to them: “To you, it has been given to know the mystery of the kingdom of God. But to those who are outside, everything is presented in parables:

[[mark-4-12]]
^12^ ‘so that, seeing, they may see, and not perceive; and hearing, they may hear, and not understand; lest at any time they may be converted, and their sins would be forgiven them.’ ”

[[mark-4-13]]
^13^ And he said to them: “Do you not understand this parable? And so, how will you understand all the parables?

[[mark-4-14]]
^14^ He who sows, sows the word.

[[mark-4-15]]
^15^ Now there are those who are along the way, where the word is sown. And when they have heard it, Satan quickly comes and takes away the word, which was sown in their hearts.

[[mark-4-16]]
^16^ And similarly, there are those who were sown upon stony ground. These, when they have heard the word, immediately accept it with gladness.

[[mark-4-17]]
^17^ But they have no root in themselves, and so they are for a limited time. And when next tribulation and persecution arises because of the word, they quickly fall away.

[[mark-4-18]]
^18^ And there are others who are sown among thorns. These are those who hear the word,

[[mark-4-19]]
^19^ but worldly tasks, and the deception of riches, and desires about other things enter in and suffocate the word, and it is effectively without fruit.

[[mark-4-20]]
^20^ And there are those who are sown upon good soil, who hear the word and accept it; and these bear fruit: some thirty, some sixty, and some one hundred.”

[[mark-4-21]]
^21^ And he said to them: “Would someone enter with a lamp in order to place it under a basket or under a bed? Would it not be placed upon a lampstand?

[[mark-4-22]]
^22^ For there is nothing hidden that will not be revealed. Neither was anything done in secret, except that it may be made public.

[[mark-4-23]]
^23^ If anyone has ears to hear, let him hear.”

[[mark-4-24]]
^24^ And he said to them: “Consider what you hear. With whatever measure you have measured out, it shall be measured back to you, and more shall be added to you.

[[mark-4-25]]
^25^ For whoever has, to him it shall be given. And whoever has not, from him even what he has shall be taken away.”

[[mark-4-26]]
^26^ And he said: “The kingdom of God is like this: it is as if a man were to cast seed on the land.

[[mark-4-27]]
^27^ And he sleeps and he arises, night and day. And the seed germinates and grows, though he does not know it.

[[mark-4-28]]
^28^ For the earth bears fruit readily: first the plant, then the ear, next the full grain in the ear.

[[mark-4-29]]
^29^ And when the fruit has been produced, immediately he sends out the sickle, because the harvest has arrived.”

[[mark-4-30]]
^30^ And he said: “To what should we compare the kingdom of God? Or to what parable should we compare it?

[[mark-4-31]]
^31^ It is like a grain of mustard seed which, when it has been sown in the earth, is less than all the seeds which are in the earth.

[[mark-4-32]]
^32^ And when it is sown, it grows up and becomes greater than all the plants, and it produces great branches, so much so that the birds of the air are able to live under its shadow.”

[[mark-4-33]]
^33^ And with many such parables he spoke the word to them, as much as they were able to hear.

[[mark-4-34]]
^34^ But he did not speak to them without a parable. Yet separately, he explained all things to his disciples.

[[mark-4-35]]
^35^ And on that day, when evening had arrived, he said to them, “Let us cross over.”

[[mark-4-36]]
^36^ And dismissing the crowd, they brought him, so that he was in one boat, and other boats were with him.

[[mark-4-37]]
^37^ And a great wind storm occurred, and the waves broke over the boat, so that the boat was being filled.

[[mark-4-38]]
^38^ And he was in the stern of the boat, sleeping on a pillow. And they woke him and said to him, “Teacher, does it not concern you that we are perishing?”

[[mark-4-39]]
^39^ And rising up, he rebuked the wind, and he said to the sea: “Silence. Be stilled.” And the wind ceased. And a great tranquility occurred.

[[mark-4-40]]
^40^ And he said to them: “Why are you afraid? Do you still lack faith?” And they were struck with a great fear. And they said to one another, “Who do you think this is, that both wind and sea obey him?”


[[mark-5]]
== Chapter 5

[[mark-5-1]]
^1^ And they went across the strait of the sea into the region of the Gerasenes.

[[mark-5-2]]
^2^ And as he was departing from the boat, he was immediately met, from among the tombs, by a man with an unclean spirit,

[[mark-5-3]]
^3^ who had his dwelling place with the tombs; neither had anyone been able to bind him, even with chains.

[[mark-5-4]]
^4^ For having been bound often with shackles and chains, he had broken the chains and smashed the shackles; and no one had been able to tame him.

[[mark-5-5]]
^5^ And he was always, day and night, among the tombs, or in the mountains, crying out and cutting himself with stones.

[[mark-5-6]]
^6^ And seeing Jesus from afar, he ran and adored him.

[[mark-5-7]]
^7^ And crying out with a loud voice, he said: “What am I to you, Jesus, the Son of the Most High God? I beseech you by God, that you not torment me.”

[[mark-5-8]]
^8^ For he said to him, “Depart from the man, you unclean spirit.”

[[mark-5-9]]
^9^ And he questioned him: “What is your name?” And he said to him, “My name is Legion, for we are many.”

[[mark-5-10]]
^10^ And he entreated him greatly, so that he would not expel him from the region.

[[mark-5-11]]
^11^ And in that place, near the mountain, there was a great herd of swine, feeding.

[[mark-5-12]]
^12^ And the spirits entreated him, saying: “Send us into the swine, so that we may enter into them.”

[[mark-5-13]]
^13^ And Jesus promptly gave them permission. And the unclean spirits, departing, entered into the swine. And the herd of about two thousand rushed down with great force into the sea, and they were drowned in the sea.

[[mark-5-14]]
^14^ Then those who pastured them fled, and they reported it in the city and in the countryside. And they all went out to see what was happening.

[[mark-5-15]]
^15^ And they came to Jesus. And they saw the man who had been troubled by the demon, sitting, clothed and with a sane mind, and they were afraid.

[[mark-5-16]]
^16^ And those who had seen it explained to them how he had dealt with the man who had the demon, and about the swine.

[[mark-5-17]]
^17^ And they began to petition him, so that he would withdraw from their borders.

[[mark-5-18]]
^18^ And as he was climbing into the boat, the man who had been troubled by the demons began to beg him, so that he might be with him.

[[mark-5-19]]
^19^ And he did not permit him, but he said to him, “Go to your own people, in your own house, and announce to them how great are the things that the Lord has done for you, and how he has taken pity on you.”

[[mark-5-20]]
^20^ And he went away and began to preach in the Ten Cities, how great were the things that Jesus had done for him. And everyone wondered.

[[mark-5-21]]
^21^ And when Jesus had crossed in the boat, over the strait again, a great crowd came together before him. And he was near the sea.

[[mark-5-22]]
^22^ And one of the rulers of the synagogue, named Jairus, approached. And seeing him, he fell prostrate at his feet.

[[mark-5-23]]
^23^ And he beseeched him greatly, saying: “For my daughter is near the end. Come and lay your hand on her, so that she may be healthy and may live.”

[[mark-5-24]]
^24^ And he went with him. And a great crowd followed him, and they pressed upon him.

[[mark-5-25]]
^25^ And there was a woman who had a flow of blood for twelve years.

[[mark-5-26]]
^26^ And she had endured much from several physicians, and she had spent everything she owned with no benefit at all, but instead she became worse.

[[mark-5-27]]
^27^ Then, when she had heard of Jesus, she approached through the crowd behind him, and she touched his garment.

[[mark-5-28]]
^28^ For she said: “Because if I touch even his garment, I will be saved.”

[[mark-5-29]]
^29^ And immediately, the source of her bleeding was dried up, and she sensed in her body that she had been healed from the wound.

[[mark-5-30]]
^30^ And immediately Jesus, realizing within himself that power that had gone out from him, turning to the crowd, said, “Who touched my garments?”

[[mark-5-31]]
^31^ And his disciples said to him, “You see that the crowd presses around you, and yet you say, ‘Who touched me?’ ”

[[mark-5-32]]
^32^ And he looked around to see the woman who had done this.

[[mark-5-33]]
^33^ Yet truly, the woman, in fear and trembling, knowing what had happened within her, went and fell prostrate before him, and she told him the whole truth.

[[mark-5-34]]
^34^ And he said to her: “Daughter, your faith has saved you. Go in peace, and be healed from your wound.”

[[mark-5-35]]
^35^ While he was still speaking, they arrived from the ruler of the synagogue, saying: “Your daughter is dead. Why trouble the Teacher any further?”

[[mark-5-36]]
^36^ But Jesus, having heard the word that was spoken, said to the ruler of the synagogue: “Do not be afraid. You need only believe.”

[[mark-5-37]]
^37^ And he would not permit anyone to follow him, except Peter, and James, and John the brother of James.

[[mark-5-38]]
^38^ And they went to the house of the ruler of the synagogue. And he saw a tumult, and weeping, and much wailing.

[[mark-5-39]]
^39^ And entering, he said to them: “Why are you disturbed and weeping? The girl is not dead, but is asleep.”

[[mark-5-40]]
^40^ And they derided him. Yet truly, having put them all out, he took the father and mother of the girl, and those who were with him, and he entered to where the girl was lying.

[[mark-5-41]]
^41^ And taking the girl by the hand, he said to her, “Talitha koumi,” which means, “Little girl, (I say to you) arise.”

[[mark-5-42]]
^42^ And immediately the young girl rose up and walked. Now she was twelve years old. And they were suddenly struck with a great astonishment.

[[mark-5-43]]
^43^ And he instructed them sternly, so that no one would know about it. And he told them to give her something to eat.


[[mark-6]]
== Chapter 6

[[mark-6-1]]
^1^ And departing from there, he went away to his own country; and his disciples followed him.

[[mark-6-2]]
^2^ And when the Sabbath arrived, he began to teach in the synagogue. And many, upon hearing him, were amazed at his doctrine, saying: “Where did this one get all these things?” and, “What is this wisdom, which has been given to him?” and, “Such powerful deeds, which are wrought by his hands!”

[[mark-6-3]]
^3^ “Is this not the carpenter, the son of Mary, the brother of James, and Joseph, and Jude, and Simon? Are not his sisters also here with us?” And they took great offense at him.

[[mark-6-4]]
^4^ And Jesus said to them, “A prophet is not without honor, except in his own country, and in his own house, and among his own kindred.”

[[mark-6-5]]
^5^ And he was not able to perform any miracles there, except that he cured a few of the infirm by laying his hands on them.

[[mark-6-6]]
^6^ And he wondered, because of their unbelief, and he traveled around in the villages, teaching.

[[mark-6-7]]
^7^ And he called the twelve. And he began to send them out in twos, and he gave them authority over unclean spirits.

[[mark-6-8]]
^8^ And he instructed them not to take anything for the journey, except a staff: no traveling bag, no bread, and no money belt,

[[mark-6-9]]
^9^ but to wear sandals, and not to wear two tunics.

[[mark-6-10]]
^10^ And he said to them: “Whenever you have entered into a house, stay there until you depart from that place.

[[mark-6-11]]
^11^ And whoever will neither receive you, nor listen to you, as you go away from there, shake off the dust from your feet as a testimony against them.”

[[mark-6-12]]
^12^ And going out, they were preaching, so that people would repent.

[[mark-6-13]]
^13^ And they cast out many demons, and they anointed many of the sick with oil and healed them.

[[mark-6-14]]
^14^ And king Herod heard of it, (for his name had become well-known) and he said: “John the Baptist has risen again from the dead, and because of this, miracles are at work in him.”

[[mark-6-15]]
^15^ But others were saying, “Because it is Elijah.” Still others were saying, “Because he is a prophet, like one of the prophets.”

[[mark-6-16]]
^16^ When Herod had heard it, he said, “John whom I beheaded, the same has risen again from the dead.”

[[mark-6-17]]
^17^ For Herod himself had sent to capture John, and had chained him in prison, because of Herodias, the wife of his brother Philip; for he had married her.

[[mark-6-18]]
^18^ For John was saying to Herod, “It is not lawful for you to have your brother’s wife.”

[[mark-6-19]]
^19^ Now Herodias was devising treachery against him; and she wanted to kill him, but she was unable.

[[mark-6-20]]
^20^ For Herod was apprehensive of John, knowing him to be a just and holy man, and so he guarded him. And he heard that he was accomplishing many things, and so he listened to him willingly.

[[mark-6-21]]
^21^ And when an opportune time had arrived, Herod held a feast on his birthday, with the leaders, and the tribunes, and the first rulers of Galilee.

[[mark-6-22]]
^22^ And when the daughter of the same Herodias had entered, and danced, and pleased Herod, along with those who were at table with him, the king said to the girl, “Request from me whatever you want, and I will give it to you.”

[[mark-6-23]]
^23^ And he swore to her, “Anything that you request, I will give to you, even up to half my kingdom.”

[[mark-6-24]]
^24^ And when she had gone out, she said to her mother, “What shall I request?” But her mother said, “The head of John the Baptist.”

[[mark-6-25]]
^25^ And immediately, when she had entered with haste to the king, she petitioned him, saying: “I want you to give me at once the head of John the Baptist on a platter.”

[[mark-6-26]]
^26^ And the king was greatly saddened. But because of his oath, and because of those who were sitting with him at table, he was not willing to disappoint her.

[[mark-6-27]]
^27^ So, having sent an executioner, he instructed that his head be brought on a platter.

[[mark-6-28]]
^28^ And he beheaded him in prison, and he brought his head on a platter. And he gave it to the girl, and the girl gave it her mother.

[[mark-6-29]]
^29^ When his disciples heard about it, they came and took his body, and they placed it in a tomb.

[[mark-6-30]]
^30^ And the Apostles, returning to Jesus, reported to him everything that they had done and taught.

[[mark-6-31]]
^31^ And he said to them, “Go out alone, into a deserted place, and rest for a little while.” For there were so many who were coming and going, that they did not even have time to eat.

[[mark-6-32]]
^32^ And climbing into a boat, they went away to a deserted place alone.

[[mark-6-33]]
^33^ And they saw them going away, and many knew about it. And together they ran by foot from all the cities, and they arrived before them.

[[mark-6-34]]
^34^ And Jesus, going out, saw a great multitude. And he took pity on them, because they were like sheep without a shepherd, and he began to teach them many things.

[[mark-6-35]]
^35^ And when many hours had now passed, his disciples drew near to him, saying: “This is a deserted place, and the hour is now late.

[[mark-6-36]]
^36^ Send them away, so that by going out to nearby villages and towns, they might buy provisions for themselves to eat.”

[[mark-6-37]]
^37^ And responding, he said to them, “Give them something to eat yourselves.” And they said to him, “Let us go out and buy bread for two hundred denarii, and then we will give them something to eat.”

[[mark-6-38]]
^38^ And he said to them: “How many loaves do you have? Go and see.” And when they had found out, they said, “Five, and two fish.”

[[mark-6-39]]
^39^ And he instructed them to make them all sit down in groups on the green grass.

[[mark-6-40]]
^40^ And they sat down in divisions by hundreds and by fifties.

[[mark-6-41]]
^41^ And having received the five loaves and the two fish, gazing up to heaven, he blessed and broke the bread, and he gave it to his disciples to set before them. And the two fish he divided among them all.

[[mark-6-42]]
^42^ And they all ate and were satisfied.

[[mark-6-43]]
^43^ And they brought together the remainder: twelve baskets full of fragments and of fish.

[[mark-6-44]]
^44^ Now those who ate were five thousand men.

[[mark-6-45]]
^45^ And without delay he urged his disciples to climb into the boat, so that they might precede him across the sea to Bethsaida, while he dismissed the people.

[[mark-6-46]]
^46^ And when he had dismissed them, he went to the mountain to pray.

[[mark-6-47]]
^47^ And when it was late, the boat was in the midst of the sea, and he was alone on the land.

[[mark-6-48]]
^48^ And seeing them struggling to row, (for the wind was against them,) and about the fourth watch of the night, he came to them, walking upon the sea. And he intended to pass by them.

[[mark-6-49]]
^49^ But when they saw him walking upon the sea, they thought it was an apparition, and they cried out.

[[mark-6-50]]
^50^ For they all saw him, and they were very disturbed. And immediately he spoke with them, and he said to them: “Be strengthened in faith. It is I. Do not be afraid.”

[[mark-6-51]]
^51^ And he climbed into the boat with them, and the wind ceased. And they became even more astonished within themselves.

[[mark-6-52]]
^52^ For they did not understand about the bread. For their heart had been blinded.

[[mark-6-53]]
^53^ And when they had crossed over, they arrived in the land of Genesaret, and they reached the shore.

[[mark-6-54]]
^54^ And when they had disembarked from the boat, the people immediately recognized him.

[[mark-6-55]]
^55^ And running throughout that entire region, they began to carry on beds those who had maladies, to where they heard that he would be.

[[mark-6-56]]
^56^ And in whichever place he entered, in towns or villages or cities, they placed the infirm in the main streets, and they pleaded with him that they might touch even the hem of his garment. And as many as touched him were made healthy.


[[mark-7]]
== Chapter 7

[[mark-7-1]]
^1^ And the Pharisees and some of the scribes, arriving from Jerusalem, gathered together before him.

[[mark-7-2]]
^2^ And when they had seen certain ones from his disciples eating bread with common hands, that is, with unwashed hands, they disparaged them.

[[mark-7-3]]
^3^ For the Pharisees, and all the Jews, do not eat without repeatedly washing their hands, holding to the tradition of the elders.

[[mark-7-4]]
^4^ And when returning from the market, unless they wash, they do not eat. And there are many other things which have been handed down to them to observe: the washings of cups, and pitchers, and bronze containers, and beds.

[[mark-7-5]]
^5^ And so the Pharisees and the scribes questioned him: “Why do your disciples not walk according to the tradition of the elders, but they eat bread with common hands?”

[[mark-7-6]]
^6^ But in response, he said to them: “So well did Isaiah prophesy about you hypocrites, just as it has been written: ‘This people honors me with their lips, but their heart is far from me.

[[mark-7-7]]
^7^ And in vain do they worship me, teaching the doctrines and precepts of men.’

[[mark-7-8]]
^8^ For abandoning the commandment of God, you hold to the tradition of men, to the washing of pitchers and cups. And you do many other things similar to these.”

[[mark-7-9]]
^9^ And he said to them: “You effectively nullify the precept of God, so that you may observe your own tradition.

[[mark-7-10]]
^10^ For Moses said: ‘Honor your father and your mother,’ and, ‘Whoever will have cursed father or mother, let him die a death.’

[[mark-7-11]]
^11^ But you say, ‘If a man will have said to his father or mother: Korban, (which is a gift) whatever is from me will be to your benefit,’

[[mark-7-12]]
^12^ then you do not release him to do anything for his father or mother,

[[mark-7-13]]
^13^ rescinding the word of God through your tradition, which you have handed down. And you do many other similar things in this way.”

[[mark-7-14]]
^14^ And again, calling the crowd to him, he said to them: “Listen to me, all of you, and understand.

[[mark-7-15]]
^15^ There is nothing from outside a man which, by entering into him, is able to defile him. But the things which proceed from a man, these are what pollute a man.

[[mark-7-16]]
^16^ Whoever has ears to hear, let him hear.”

[[mark-7-17]]
^17^ And when he had entered into the house, away from the crowd, his disciples questioned him about the parable.

[[mark-7-18]]
^18^ And he said to them: “So, are you also without prudence? Do you not understand that everything entering to a man from outside is not able to pollute him?

[[mark-7-19]]
^19^ For it does not enter into his heart, but into the gut, and it exits into the sewer, purging all foods.”

[[mark-7-20]]
^20^ “But,” he said “the things which go out from a man, these pollute a man.

[[mark-7-21]]
^21^ For from within, from the heart of men, proceed evil thoughts, adulteries, fornications, murders,

[[mark-7-22]]
^22^ thefts, avarice, wickedness, deceitfulness, homosexuality, an evil eye, blasphemy, self-exaltation, foolishness.

[[mark-7-23]]
^23^ All these evils proceed from within and pollute a man.”

[[mark-7-24]]
^24^ And rising up, he went from there to the area of Tyre and Sidon. And entering into a house, he intended no one to know about it, but he was not able to remain hidden.

[[mark-7-25]]
^25^ For a woman whose daughter had an unclean spirit, as soon as she heard about him, entered and fell prostrate at his feet.

[[mark-7-26]]
^26^ For the woman was a Gentile, by birth a Syro-Phoenician. And she petitioned him, so that he would cast the demon from her daughter.

[[mark-7-27]]
^27^ And he said to her: “First allow the sons to have their fill. For it is not good to take away the bread of the sons and throw it to the dogs.”

[[mark-7-28]]
^28^ But she responded by saying to him: “Certainly, Lord. Yet the young dogs also eat, under the table, from the crumbs of the children.”

[[mark-7-29]]
^29^ And he said to her, “Because of this saying, go; the demon has gone out of your daughter.”

[[mark-7-30]]
^30^ And when she had gone to her house, she found the girl lying on the bed; and the demon had gone away.

[[mark-7-31]]
^31^ And again, departing from the borders of Tyre, he went by way of Sidon to the sea of Galilee, through the midst of the area of the Ten Cities.

[[mark-7-32]]
^32^ And they brought someone who was deaf and mute to him. And they begged him, so that he would lay his hand upon him.

[[mark-7-33]]
^33^ And taking him away from the crowd, he put his fingers into his ears; and spitting, he touched his tongue.

[[mark-7-34]]
^34^ And gazing up to heaven, he groaned and said to him: “Ephphatha,” which is, “Be opened.”

[[mark-7-35]]
^35^ And immediately his ears were opened, and the impediment of his tongue was released, and he spoke correctly.

[[mark-7-36]]
^36^ And he instructed them not to tell anyone. But as much as he instructed them, so much more did they preach about it.

[[mark-7-37]]
^37^ And so much more did they wonder, saying: “He has done all things well. He has caused both the deaf to hear and the mute to speak.”


[[mark-8]]
== Chapter 8

[[mark-8-1]]
^1^ In those days, again, when there was a great crowd, and they did not have anything to eat, calling together his disciples, he said to them:

[[mark-8-2]]
^2^ “I have compassion for the multitude, because, behold, they have persevered with me now for three days, and they do not have anything to eat.

[[mark-8-3]]
^3^ And if I were to send them away fasting to their home, they might faint on the way.” For some of them came from far away.

[[mark-8-4]]
^4^ And his disciples answered him, “From where would anyone be able to obtain enough bread for them in the wilderness?”

[[mark-8-5]]
^5^ And he questioned them, “How many loaves do you have?” And they said, “Seven.”

[[mark-8-6]]
^6^ And he instructed the crowd to sit down to eat on the ground. And taking the seven loaves, giving thanks, he broke and gave it to his disciples in order to place before them. And they placed these before the crowd.

[[mark-8-7]]
^7^ And they had a few small fish. And he blessed them, and he ordered them to be placed before them.

[[mark-8-8]]
^8^ And they ate and were satisfied. And they took up what had been leftover from the fragments: seven baskets.

[[mark-8-9]]
^9^ And those who ate were about four thousand. And he dismissed them.

[[mark-8-10]]
^10^ And promptly climbing into a boat with his disciples, he went into the parts of Dalmanutha.

[[mark-8-11]]
^11^ And the Pharisees went out and began to contend with him, seeking from him a sign from heaven, testing him.

[[mark-8-12]]
^12^ And sighing deeply in spirit, he said: “Why does this generation seek a sign? Amen, I say to you, if only a sign will be given to this generation!”

[[mark-8-13]]
^13^ And sending them away, he climbed into the boat again, and he went away across the sea.

[[mark-8-14]]
^14^ And they forgot to take bread. And they did not have any with them in the boat, except one loaf.

[[mark-8-15]]
^15^ And he instructed them, saying: “Consider and beware of the leaven of the Pharisees and of the leaven of Herod.”

[[mark-8-16]]
^16^ And they discussed this with one another, saying, “For we have no bread.”

[[mark-8-17]]
^17^ And Jesus, knowing this, said to them: “Why do you consider that it is because you have no bread? Do you not yet know or understand? Do you still have blindness in your heart?

[[mark-8-18]]
^18^ Having eyes, do you not see? And having ears, do you not hear? Do you not remember,

[[mark-8-19]]
^19^ when I broke the five loaves among the five thousand, how many baskets full of fragments you took up?” They said to him, “Twelve.”

[[mark-8-20]]
^20^ “And when the seven loaves were among the four thousand, how many baskets of fragments did you take up?” And they said to him, “Seven.”

[[mark-8-21]]
^21^ And he said to them, “How is it that you do not yet understand?”

[[mark-8-22]]
^22^ And they went to Bethsaida. And they brought a blind man to him. And they petitioned him, so that he would touch him.

[[mark-8-23]]
^23^ And taking the blind man by the hand, he led him beyond the village. And putting spit on his eyes, laying his hands on him, he asked him if he could see anything.

[[mark-8-24]]
^24^ And looking up, he said, “I see men but they are like walking trees.”

[[mark-8-25]]
^25^ Next he placed his hands again over his eyes, and he began to see. And he was restored, so that he could see everything clearly.

[[mark-8-26]]
^26^ And he sent him to his house, saying, “Go into your own house, and if you enter into the town, tell no one.”

[[mark-8-27]]
^27^ And Jesus departed with his disciples into the towns of Caesarea Philippi. And on the way, he questioned his disciples, saying to them, “Who do men say that I am?”

[[mark-8-28]]
^28^ And they answered him by saying: “John the Baptist, others Elijah, still others perhaps one of the prophets.”

[[mark-8-29]]
^29^ Then he said to them, “Yet truly, who do you say that I am?” Peter responded by saying to him, “You are the Christ.”

[[mark-8-30]]
^30^ And he admonished them, not to tell anyone about him.

[[mark-8-31]]
^31^ And he began to teach them that the Son of man must suffer many things, and be rejected by the elders, and by the high priests, and the scribes, and be killed, and after three days rise again.

[[mark-8-32]]
^32^ And he spoke the word openly. And Peter, taking him aside, began to correct him.

[[mark-8-33]]
^33^ And turning away and looking at his disciples, he admonished Peter, saying, “Get behind me, Satan, for you do not prefer the things that are of God, but the things that are of men.”

[[mark-8-34]]
^34^ And calling together the crowd with his disciples, he said to them, “If anyone chooses to follow me, let him deny himself, and take up his cross, and follow me.

[[mark-8-35]]
^35^ For whoever will have chosen to save his life, will lose it. But whoever will have lost his life, for my sake and for the Gospel, shall save it.

[[mark-8-36]]
^36^ For how does it benefit a man, if he gains the whole world, and yet causes harm to his soul?

[[mark-8-37]]
^37^ Or, what will a man give in exchange for his soul?

[[mark-8-38]]
^38^ For whoever has been ashamed of me and of my words, among this adulterous and sinful generation, the Son of man also will be ashamed of him, when he will arrive in the glory of his Father, with the holy Angels.”

[[mark-8-39]]
^39^ And he said to them, “Amen I say to you, that there are some among those standing here who shall not taste death until they see the kingdom of God arriving in power.”


[[mark-9]]
== Chapter 9

[[mark-9-1]]
^1^ And after six days, Jesus took with him Peter, and James, and John; and he led them separately to a lofty mountain alone; and he was transfigured before them.

[[mark-9-2]]
^2^ And his vestments became radiant and exceedingly white like snow, with such a brilliance as no fuller on earth is able to achieve.

[[mark-9-3]]
^3^ And there appeared to them Elijah with Moses; and they were speaking with Jesus.

[[mark-9-4]]
^4^ And in response, Peter said to Jesus: “Master, it is good for us to be here. And so let us make three tabernacles, one for you, and one for Moses, and one for Elijah.”

[[mark-9-5]]
^5^ For he did not know what he was saying. For they were overwhelmed by fear.

[[mark-9-6]]
^6^ And there was a cloud overshadowing them. And a voice came from the cloud, saying: “This is my most beloved Son. Listen to him.”

[[mark-9-7]]
^7^ And immediately, looking around, they no longer saw anyone, except Jesus alone with them.

[[mark-9-8]]
^8^ And as they were descending from the mountain, he instructed them not to relate to anyone what they had seen, until after the Son of man will have risen again from the dead.

[[mark-9-9]]
^9^ And they kept the word to themselves, arguing about what “after he will have risen from the dead” might mean.

[[mark-9-10]]
^10^ And they questioned him, saying: “Then why do the Pharisees and the scribes say that Elijah must arrive first?”

[[mark-9-11]]
^11^ And in response, he said to them: “Elijah, when he will arrive first, shall restore all things. And in the manner that it has been written about the Son of man, so must he suffer many things and be condemned.

[[mark-9-12]]
^12^ But I say to you, that Elijah also has arrived, (and they have done to him whatever they wanted) just as it has been written about him.”

[[mark-9-13]]
^13^ And approaching his disciples, he saw a great crowd surrounding them, and the scribes were arguing with them.

[[mark-9-14]]
^14^ And soon all the people, seeing Jesus, were astonished and struck with fear, and hurrying to him, they greeted him.

[[mark-9-15]]
^15^ And he questioned them, “What are you arguing about among yourselves?”

[[mark-9-16]]
^16^ And one from the crowd responded by saying: “Teacher, I have brought to you my son, who has a mute spirit.

[[mark-9-17]]
^17^ And whenever it takes hold of him, it throws him down, and he foams and gnashes with his teeth, and he becomes unconscious. And I asked your disciples to cast him out, and they could not.”

[[mark-9-18]]
^18^ And answering them, he said: “O unbelieving generation, how long must I be with you? How long shall I endure you? Bring him to me.”

[[mark-9-19]]
^19^ And they brought him. And when he had seen him, immediately the spirit disturbed him. And having been thrown to the ground, he rolled around foaming.

[[mark-9-20]]
^20^ And he questioned his father, “How long has this been happening to him?” But he said: “From infancy.

[[mark-9-21]]
^21^ And often it casts him into fire or into water, in order to destroy him. But if you are able to do anything, help us and take pity on us.”

[[mark-9-22]]
^22^ But Jesus said to him, “If you are able to believe: all things are possible to one who believes.”

[[mark-9-23]]
^23^ And immediately the father of the boy, crying out with tears, said: “I do believe, Lord. Help my unbelief.”

[[mark-9-24]]
^24^ And when Jesus saw the crowd rushing together, he admonished the unclean spirit, saying to him, “Deaf and mute spirit, I command you, leave him; and do not enter into him anymore.”

[[mark-9-25]]
^25^ And crying out, and convulsing him greatly, he departed from him. And he became like one who is dead, so much so that many said, “He is dead.”

[[mark-9-26]]
^26^ But Jesus, taking him by the hand, lifted him up. And he arose.

[[mark-9-27]]
^27^ And when he had entered into the house, his disciples questioned him privately, “Why were we unable to cast him out?”

[[mark-9-28]]
^28^ And he said to them, “This kind is able to be expelled by nothing other than prayer and fasting.”

[[mark-9-29]]
^29^ And setting out from there, they passed through Galilee. And he intended that no one know about it.

[[mark-9-30]]
^30^ Then he taught his disciples, and he said to them, “For the Son of man shall be delivered into the hands of men, and they will kill him, and having been killed, on the third day he will rise again.”

[[mark-9-31]]
^31^ But they did not understand the word. And they were afraid to question him.

[[mark-9-32]]
^32^ And they went to Capernaum. And when they were in the house, he questioned them, “What did you discuss on the way?”

[[mark-9-33]]
^33^ But they were silent. For indeed, on the way, they had disputed among themselves as to which of them was greater.

[[mark-9-34]]
^34^ And sitting down, he called the twelve, and he said to them, “If anyone wants to be first, he shall be the last of all and the minister of all.”

[[mark-9-35]]
^35^ And taking a child, he set him in their midst. And when he had embraced him, he said to them:

[[mark-9-36]]
^36^ “Whoever receives one such child in my name, receives me. And whoever receives me, receives not me, but him who sent me.”

[[mark-9-37]]
^37^ John responded to him by saying, “Teacher, we saw someone casting out demons in your name; he does not follow us, and so we prohibited him.”

[[mark-9-38]]
^38^ But Jesus said: “Do not prohibit him. For there is no one who can act with virtue in my name and soon speak evil about me.

[[mark-9-39]]
^39^ For whoever is not against you is for you.

[[mark-9-40]]
^40^ For whoever, in my name, will give you a cup of water to drink, because you belong to Christ: Amen I say to you, he shall not lose his reward.

[[mark-9-41]]
^41^ And whoever will have scandalized one of these little ones who believe in me: it would be better for him if a great millstone were placed around his neck and he were thrown into the sea.

[[mark-9-42]]
^42^ And if your hand causes you to sin, cut it off: it is better for you to enter into life disabled, than having two hands to go into Hell, into the unquenchable fire,

[[mark-9-43]]
^43^ where their worm does not die, and the fire is not extinguished.

[[mark-9-44]]
^44^ But if your foot causes you to sin, chop it off: it is better for you to enter into eternal life lame, than having two feet to be cast into the Hell of unquenchable fire,

[[mark-9-45]]
^45^ where their worm does not die, and the fire is not extinguished.

[[mark-9-46]]
^46^ But if your eye causes you to sin, pluck it out: it is better for you to enter into the kingdom of God with one eye, than having two eyes to be cast into the Hell of fire,

[[mark-9-47]]
^47^ where their worm does not die, and the fire is not extinguished.

[[mark-9-48]]
^48^ For all shall be salted with fire, and every victim shall be salted with salt.

[[mark-9-49]]
^49^ Salt is good: but if the salt has become bland, with what will you season it? Have salt in yourselves, and have peace among yourselves.”


[[mark-10]]
== Chapter 10

[[mark-10-1]]
^1^ And rising up, he went from there into the area of Judea beyond the Jordan. And again, the crowd came together before him. And just as he was accustomed to do, again he taught them.

[[mark-10-2]]
^2^ And approaching, the Pharisees questioned him, testing him: “Is it lawful for a man to dismiss his wife?”

[[mark-10-3]]
^3^ But in response, he said to them, “What did Moses instruct you?”

[[mark-10-4]]
^4^ And they said, “Moses gave permission to write a bill of divorce and to dismiss her.”

[[mark-10-5]]
^5^ But Jesus responded by saying: “It was due to the hardness of your heart that he wrote that precept for you.

[[mark-10-6]]
^6^ But from the beginning of creation, God made them male and female.

[[mark-10-7]]
^7^ Because of this, a man shall leave behind his father and mother, and he shall cling to his wife.

[[mark-10-8]]
^8^ And these two shall be one in flesh. And so, they are now, not two, but one flesh.

[[mark-10-9]]
^9^ Therefore, what God has joined together, let no man separate.”

[[mark-10-10]]
^10^ And again, in the house, his disciples questioned him about the same thing.

[[mark-10-11]]
^11^ And he said to them: “Whoever dismisses his wife, and marries another, commits adultery against her.

[[mark-10-12]]
^12^ And if a wife dismisses her husband, and is married to another, she commits adultery.”

[[mark-10-13]]
^13^ And they brought to him the little children, so that he might touch them. But the disciples admonished those who brought them.

[[mark-10-14]]
^14^ But when Jesus saw this, he took offense, and he said to them: “Allow the little ones to come to me, and do not prohibit them. For of such as these is the kingdom of God.

[[mark-10-15]]
^15^ Amen I say to you, whoever will not accept the kingdom of God like a little child, will not enter into it.”

[[mark-10-16]]
^16^ And embracing them, and laying his hands upon them, he blessed them.

[[mark-10-17]]
^17^ And when he had departed on the way, a certain one, running up and kneeling before him, asked him, “Good Teacher, what shall I do, so that I may secure eternal life?”

[[mark-10-18]]
^18^ But Jesus said to him, “Why call me good? No one is good except the one God.

[[mark-10-19]]
^19^ You know the precepts: “Do not commit adultery. Do not kill. Do not steal. Do not speak false testimony. Do not deceive. Honor your father and mother.”

[[mark-10-20]]
^20^ But in response, he said to him, “Teacher, all these I have observed from my youth.”

[[mark-10-21]]
^21^ Then Jesus, gazing at him, loved him, and he said to him: “One thing is lacking to you. Go, sell whatever you have, and give to the poor, and then you will have treasure in heaven. And come, follow me.”

[[mark-10-22]]
^22^ But he went away grieving, having been greatly saddened by the word. For he had many possessions.

[[mark-10-23]]
^23^ And Jesus, looking around, said to his disciples, “How difficult it is for those who have riches to enter into the kingdom of God!”

[[mark-10-24]]
^24^ And the disciples were astonished at his words. But Jesus, answering again, said to them: “Little sons, how difficult it is for those who trust in money to enter into the kingdom of God!

[[mark-10-25]]
^25^ It is easier for a camel to pass through the eye of a needle, than for the rich to enter into the kingdom of God.”

[[mark-10-26]]
^26^ And they wondered even more, saying among themselves, “Who, then, can be saved?”

[[mark-10-27]]
^27^ And Jesus, gazing at them, said: “With men it is impossible; but not with God. For with God all things are possible.”

[[mark-10-28]]
^28^ And Peter began to say to him, “Behold, we have left all things and have followed you.”

[[mark-10-29]]
^29^ In response, Jesus said: “Amen I say to you, There is no one who has left behind house, or brothers, or sisters, or father, or mother, or children, or land, for my sake and for the Gospel,

[[mark-10-30]]
^30^ who will not receive one hundred times as much, now in this time: houses, and brothers, and sisters, and mothers, and children, and land, with persecutions, and in the future age eternal life.

[[mark-10-31]]
^31^ But many of the first shall be last, and the last shall be first.”

[[mark-10-32]]
^32^ Now they were on the way ascending to Jerusalem. And Jesus went ahead of them, and they were astonished. And those following him were afraid. And again, taking aside the twelve, he began to tell them what was about to happen to him.

[[mark-10-33]]
^33^ “For behold, we are going up to Jerusalem, and the Son of man will be handed over to the leaders of the priests, and to the scribes, and the elders. And they will condemn him to death, and they will hand him over to the Gentiles.

[[mark-10-34]]
^34^ And they will mock him, and spit on him, and scourge him, and put him to death. And on the third day, he will rise again.”

[[mark-10-35]]
^35^ And James and John, the sons of Zebedee, drew near to him, saying, “Teacher, we wish that whatever we will ask, you would do for us.”

[[mark-10-36]]
^36^ But he said to them, “What do you want me to do for you?”

[[mark-10-37]]
^37^ And they said, “Grant to us that we may sit, one at your right and the other at your left, in your glory.”

[[mark-10-38]]
^38^ But Jesus said to them: “You do not know what you are asking. Are you able to drink from the chalice from which I drink, or to be baptized with the baptism with which I am to be baptized?”

[[mark-10-39]]
^39^ But they said to him, “We can.” Then Jesus said to them: “Indeed, you shall drink from the chalice, from which I drink; and you shall be baptized with the baptism, with which I am to be baptized.

[[mark-10-40]]
^40^ But to sit at my right, or at my left, is not mine to give to you, but it is for those for whom it has been prepared.”

[[mark-10-41]]
^41^ And the ten, upon hearing this, began to be indignant toward James and John.

[[mark-10-42]]
^42^ But Jesus, calling them, said to them: “You know that those who seem to be leaders among the Gentiles dominate them, and their leaders exercise authority over them.

[[mark-10-43]]
^43^ But it is not to be this way among you. Instead, whoever would become greater shall be your minister;

[[mark-10-44]]
^44^ and whoever will be first among you shall be the servant of all.

[[mark-10-45]]
^45^ So, too, the Son of man has not come so that they would minister to him, but so that he would minister and would give his life as a redemption for many.”

[[mark-10-46]]
^46^ And they went to Jericho. And as he was setting out from Jericho with his disciples and a very numerous multitude, Bartimaeus, the son of Timaeus, a blind man, sat begging beside the way.

[[mark-10-47]]
^47^ And when he had heard that it was Jesus of Nazareth, he began to cry out and to say, “Jesus, Son of David, take pity on me.”

[[mark-10-48]]
^48^ And many admonished him to be quiet. But he cried out all the more, “Son of David, take pity on me.”

[[mark-10-49]]
^49^ And Jesus, standing still, instructed him to be called. And they called the blind man, saying to him: “Be at peace. Arise. He is calling you.”

[[mark-10-50]]
^50^ And casting aside his garment, he leapt up and went to him.

[[mark-10-51]]
^51^ And in response, Jesus said to him, “What do you want, that I should do for you?” And the blind man said to him, “Master, that I may see.”

[[mark-10-52]]
^52^ Then Jesus said to him, “Go, your faith has made you whole.” And immediately he saw, and he followed him on the way.


[[mark-11]]
== Chapter 11

[[mark-11-1]]
^1^ And as they were approaching Jerusalem and Bethania, toward the mount of Olives, he sent two of his disciples,

[[mark-11-2]]
^2^ and he said to them: “Go into the village that is opposite you, and immediately upon entering there, you will find a colt tied, on which no man has yet sat. Release him and bring him.

[[mark-11-3]]
^3^ And if anyone will say to you: ‘What are you doing?’ Say that the Lord has need of him. And he will immediately send him here.”

[[mark-11-4]]
^4^ And going out, they found the colt tied before the outer gate, at the meeting of two ways. And they untied him.

[[mark-11-5]]
^5^ And some of those who were standing there said to them, “What are you doing by releasing the colt?”

[[mark-11-6]]
^6^ And they spoke to them just as Jesus had instructed them. And they permitted them.

[[mark-11-7]]
^7^ And they led the colt to Jesus. And they placed their garments on it; and he sat upon it.

[[mark-11-8]]
^8^ Then many spread their garments along the way; but others cut down leafy branches from trees and scattered them on the way.

[[mark-11-9]]
^9^ And those who went ahead, and those who followed, cried out saying: “Hosanna! Blessed is he who has arrived in the name of the Lord.

[[mark-11-10]]
^10^ Blessed is the advent of the kingdom of our father David. Hosanna in the highest!”

[[mark-11-11]]
^11^ And he entered into Jerusalem, into the temple. And having looked around at everything, since it was now the evening hour, he went out to Bethania with the twelve.

[[mark-11-12]]
^12^ And the next day, as they were departing from Bethania, he was hungry.

[[mark-11-13]]
^13^ And when he had seen a fig tree with leaves in the distance, he went to it, in case he might find something on it. And when he had gone to it, he found nothing but leaves. For it was not the season for figs.

[[mark-11-14]]
^14^ And in response, he said to it, “From now on and forever, may no one eat fruit from you again!” And his disciples heard this.

[[mark-11-15]]
^15^ And they went to Jerusalem. And when he had entered into the temple, he began to cast out the sellers and the buyers in the temple. And he overturned the tables of the moneychangers and the chairs of the vendors of doves.

[[mark-11-16]]
^16^ And he would not permit anyone to carry goods through the temple.

[[mark-11-17]]
^17^ And he taught them, saying: “Is it not written: ‘For my house shall be called the house of prayer for all nations?’ But you have made it into a den of robbers.”

[[mark-11-18]]
^18^ And when the leaders of the priests, and the scribes, had heard this, they sought a means by which they might destroy him. For they feared him, because the entire multitude was in admiration over his doctrine.

[[mark-11-19]]
^19^ And when evening had arrived, he departed from the city.

[[mark-11-20]]
^20^ And when they passed by in the morning, they saw that the fig tree had dried up from the roots.

[[mark-11-21]]
^21^ And Peter, remembering, said to him, “Master, behold, the fig tree that you cursed has withered.”

[[mark-11-22]]
^22^ And in response, Jesus said to them: “Have the faith of God.

[[mark-11-23]]
^23^ Amen I say to you, that whoever will say to this mountain, ‘Be taken up and cast into the sea,’ and who will not have hesitated in his heart, but will have believed: then whatever he has said be done, it shall be done for him.

[[mark-11-24]]
^24^ For this reason, I say to you, all things whatsoever that you ask for when praying: believe that you will receive them, and they will happen for you.

[[mark-11-25]]
^25^ And when you stand to pray, if you hold anything against anyone, forgive them, so that your Father, who is in heaven, may also forgive you your sins.

[[mark-11-26]]
^26^ But if you will not forgive, neither will your Father, who is in heaven, forgive you your sins.”

[[mark-11-27]]
^27^ And they went again to Jerusalem. And when he was walking in the temple, the leaders of the priests, and the scribes, and the elders approached him.

[[mark-11-28]]
^28^ And they said to him: “By what authority do you do these things? And who has given you this authority, so that you would do these things?”

[[mark-11-29]]
^29^ But in response, Jesus said to them: “I also will ask you one word, and if you answer me, I will tell you by what authority I do these things.

[[mark-11-30]]
^30^ The baptism of John: was it from heaven or from men? Answer me.”

[[mark-11-31]]
^31^ But they discussed it among themselves, saying: “If we say, ‘From heaven,’ he will say, ‘Then why did you not believe him?’

[[mark-11-32]]
^32^ If we say, ‘From men,’ we fear the people. For they all hold that John was a true prophet.”

[[mark-11-33]]
^33^ And answering, they said to Jesus, “We do not know.” And in response, Jesus said to them, “Neither will I tell you by what authority I do these things.”


[[mark-12]]
== Chapter 12

[[mark-12-1]]
^1^ And he began to speak to them in parables: “A man dug a vineyard, and surrounded it with a hedge, and dug a pit, and built a tower, and he loaned it out to farmers, and he set out on a long journey.

[[mark-12-2]]
^2^ And in time, he sent a servant to the farmers, in order to receive some of the fruit of the vineyard from the farmers.

[[mark-12-3]]
^3^ But they, having apprehended him, beat him and sent him away empty.

[[mark-12-4]]
^4^ And again, he sent another servant to them. And they wounded him on the head, and they treated him with contempt.

[[mark-12-5]]
^5^ And again, he sent another, and him they killed, and many others: some they beat, but others they killed.

[[mark-12-6]]
^6^ Therefore, having still one son, most dear to him, he sent him also to them, at the very end, saying, ‘For they will reverence my son.’

[[mark-12-7]]
^7^ But the settlers said one to another: ‘This is the heir. Come, let us kill him. And then the inheritance will be ours.’

[[mark-12-8]]
^8^ And apprehending him, they killed him. And they cast him out of the vineyard.

[[mark-12-9]]
^9^ Therefore, what will the lord of the vineyard do?” “He will come and destroy the settlers. And he will give the vineyard to others.”

[[mark-12-10]]
^10^ “And so, have you not read this scripture?: ‘The stone which the builders have rejected, the same has been made the head of the corner.

[[mark-12-11]]
^11^ By the Lord has this been done, and it is wondrous in our eyes.’ ”

[[mark-12-12]]
^12^ And they sought to take hold of him, but they feared the crowd. For they knew that he had spoken this parable about them. And leaving him behind, they went away.

[[mark-12-13]]
^13^ And they sent some of the Pharisees and Herodians to him, so that they might trap him with words.

[[mark-12-14]]
^14^ And these, arriving, said to him: “Teacher, we know that you are truthful and that you do not favor anyone; for you do not consider the appearance of men, but you teach the way of God in truth. Is it lawful to give the tribute to Caesar, or should we not give it?”

[[mark-12-15]]
^15^ And knowing their skill in deception, he said to them: “Why do you test me? Bring me a denarius, so that I may see it.”

[[mark-12-16]]
^16^ And they brought it to him. And he said to them, “Whose image and inscription is this?” They said to him, “Caesar’s.”

[[mark-12-17]]
^17^ So in response, Jesus said to them, “Then render to Caesar, the things that are of Caesar; and to God, the things that are of God.” And they wondered over him.

[[mark-12-18]]
^18^ And the Sadducees, who say there is no resurrection, approached him. And they questioned him, saying:

[[mark-12-19]]
^19^ “Teacher, Moses wrote for us that if any man’s brother will have died and left behind a wife, and not have left behind sons, his brother should take his wife to himself and should raise up offspring for his brother.

[[mark-12-20]]
^20^ So then, there were seven brothers. And the first took a wife, and he died without leaving behind offspring.

[[mark-12-21]]
^21^ And the second took her, and he died. And neither did he leave behind offspring. And the third acted similarly.

[[mark-12-22]]
^22^ And in like manner, each of the seven received her and did not leave behind offspring. Last of all, the woman also died.

[[mark-12-23]]
^23^ Therefore, in the resurrection, when they will rise again, to which of them will she be a wife? For each of the seven had her as wife.”

[[mark-12-24]]
^24^ And Jesus responded by saying to them: “But have you not gone astray, by knowing neither the scriptures, nor the power of God?

[[mark-12-25]]
^25^ For when they will be resurrected from the dead, they shall neither marry, nor be given in marriage, but they are like the Angels in heaven.

[[mark-12-26]]
^26^ But concerning the dead who rise again, have you not read in the book of Moses, how God spoke to him from the bush, saying: ‘I am the God of Abraham, and the God of Isaac, and the God of Jacob?’

[[mark-12-27]]
^27^ He is not the God of the dead, but of the living. Therefore, you have gone far astray.”

[[mark-12-28]]
^28^ And one of the scribes, who had heard them arguing, drew near to him. And seeing that he had answered them well, he questioned him as to which was the first commandment of all.

[[mark-12-29]]
^29^ And Jesus answered him: “For the first commandment of all is this: ‘Listen, O Israel. The Lord your God is one God.

[[mark-12-30]]
^30^ And you shall love the Lord your God from your whole heart, and from your whole soul, and from your whole mind, and from your whole strength. This is the first commandment.’

[[mark-12-31]]
^31^ But the second is similar to it: ‘You shall love your neighbor as yourself.’ There is no other commandment greater than these.”

[[mark-12-32]]
^32^ And the scribe said to him: Well said, Teacher. You have spoken the truth that there is one God, and there is no other beside him;

[[mark-12-33]]
^33^ and that he should be loved from the whole heart, and from the whole understanding, and from the whole soul, and from the whole strength. And to love one’s neighbor as one’s self is greater than all holocausts and sacrifices.”

[[mark-12-34]]
^34^ And Jesus, seeing that he had responded wisely, said to him, “You are not far from the kingdom of God.” And after that, no one dared to question him.

[[mark-12-35]]
^35^ And while teaching in the temple, Jesus said in answer: “How is it that the scribes say that the Christ is the son of David?

[[mark-12-36]]
^36^ For David himself said in the Holy Spirit: ‘The Lord said to my Lord: Sit at my right hand, until I set your enemies as your footstool.’

[[mark-12-37]]
^37^ Therefore, David himself calls him Lord, and so how can he be his son?” And a great multitude listened to him willingly.

[[mark-12-38]]
^38^ And he said to them in his doctrine: “Beware of the scribes, who prefer to walk in long robes and to be greeted in the marketplace,

[[mark-12-39]]
^39^ and to sit in the first chairs in the synagogues, and to have the first seats at feasts,

[[mark-12-40]]
^40^ who devour the houses of widows under the pretense of long prayers. These shall receive the more extensive judgment.”

[[mark-12-41]]
^41^ And Jesus, sitting opposite the offertory box, considered the way in which the crowd cast coins into the offertory, and that many of the wealthy cast in a great deal.

[[mark-12-42]]
^42^ But when one poor widow had arrived, she put in two small coins, which is a quarter.

[[mark-12-43]]
^43^ And calling together his disciples, he said to them: “Amen I say to you, that this poor widow has put in more than all those who contributed to the offertory.

[[mark-12-44]]
^44^ For they all gave from their abundance, yet truly, she gave from her scarcity, even all that she had, her entire living.”


[[mark-13]]
== Chapter 13

[[mark-13-1]]
^1^ And as he was departing from the temple, one of his disciples said to him, “Teacher, observe these fine stones and fine structures.”

[[mark-13-2]]
^2^ And in response, Jesus said to him: “Do you see all these great buildings? There shall not be left stone upon stone, which is not torn down.”

[[mark-13-3]]
^3^ And as he sat at the Mount of Olives, opposite the temple, Peter, and James, and John, and Andrew questioned him privately.

[[mark-13-4]]
^4^ “Tell us, when will these things be, and what will be the sign when all these things will begin to be fulfilled?”

[[mark-13-5]]
^5^ And Jesus, answering, began to say to them: “See to it that no one leads you astray.

[[mark-13-6]]
^6^ For many will come in my name, saying, ‘For I am he,’ and they will lead many astray.

[[mark-13-7]]
^7^ But when you will have heard of wars and rumors of wars, you should not be afraid. For these things must be, but the end is not so soon.

[[mark-13-8]]
^8^ For nation will rise up against nation, and kingdom over kingdom, and there shall be earthquakes in various places, and famines. These are but the beginning of the sorrows.

[[mark-13-9]]
^9^ But see to yourselves. For they will hand you over to councils, and in the synagogues you will be beaten, and you shall stand before governors and kings because of me, as a testimony for them.

[[mark-13-10]]
^10^ And the Gospel must first be preached to all nations.

[[mark-13-11]]
^11^ And when they have seized you and handed you over, do not consider in advance what to say. But whatever will be given you in that hour, say that. For you will not be speaking, but the Holy Spirit.

[[mark-13-12]]
^12^ Then brother will betray brother to death, and the father, a son; and children will rise up against their parents and will bring about their death.

[[mark-13-13]]
^13^ And you will be hated by all for the sake of my name. But whoever will have persevered unto the end, the same will be saved.

[[mark-13-14]]
^14^ Then, when you have seen the abomination of desolation, standing where it ought not to be, let the reader understand: then let those who are in Judea flee to the mountains.

[[mark-13-15]]
^15^ And let whoever is on the rooftop not descend to the house, nor enter so as to take anything from the house.

[[mark-13-16]]
^16^ And let whoever may be in the field not return to take his garment.

[[mark-13-17]]
^17^ But woe to those who are pregnant or nursing in those days.

[[mark-13-18]]
^18^ Truly, pray that these things may not happen in winter.

[[mark-13-19]]
^19^ For those days shall have such tribulations as have not been since the beginning of the creation that God founded, even until now, and shall not be.

[[mark-13-20]]
^20^ And unless the Lord had shortened the days, no flesh would be saved. But, for the sake of the elect, whom he has chosen, he has shortened the days.

[[mark-13-21]]
^21^ And then, if anyone will have said to you: ‘Behold, here is the Christ. Behold, in that place.’ Do not believe it.

[[mark-13-22]]
^22^ For false Christs and false prophets will rise up, and they will present signs and wonders, so as to lead astray, if it were possible, even the elect.

[[mark-13-23]]
^23^ Therefore, you must take heed. Behold, I have foretold all to you.

[[mark-13-24]]
^24^ But in those days, after that tribulation, the sun will be darkened, and the moon will not give her splendor.

[[mark-13-25]]
^25^ And the stars of heaven will be falling down, and the powers that are in heaven will be moved.

[[mark-13-26]]
^26^ And then they shall see the Son of man arriving on the clouds, with great power and glory.

[[mark-13-27]]
^27^ And then he will send his Angels, and gather together his elect, from the four winds, from the limits of the earth, to the limits of heaven.

[[mark-13-28]]
^28^ Now from the fig tree discern a parable. When its branch becomes tender and the foliage has been formed, you know that summer is very near.

[[mark-13-29]]
^29^ So also, when you will have seen these things happen, know that it is very near, even at the doors.

[[mark-13-30]]
^30^ Amen I say to you, that this lineage shall not pass away, until all these things have happened.

[[mark-13-31]]
^31^ Heaven and earth shall pass away, but my word shall not pass away.

[[mark-13-32]]
^32^ But concerning that day or hour, no one knows, neither the Angels in heaven, nor the Son, but only the Father.

[[mark-13-33]]
^33^ Take heed, be vigilant, and pray. For you do not know when the time may be.

[[mark-13-34]]
^34^ It is like a man who, setting out on a sojourn, left behind his house, and gave his servants authority over every work, and instructed the doorkeeper to stand watch.

[[mark-13-35]]
^35^ Therefore, be vigilant, for you do not know when the lord of the house may arrive: in the evening, or in the middle of the night, or at first light, or in the morning.

[[mark-13-36]]
^36^ Otherwise, when he will have arrived unexpectedly, he may find you sleeping.

[[mark-13-37]]
^37^ But what I say to you, I say to all: Be vigilant.”


[[mark-14]]
== Chapter 14

[[mark-14-1]]
^1^ Now the feast of Passover and of Unleavened Bread was two days away. And the leaders of the priests, and the scribes, were seeking a means by which they might deceitfully seize him and kill him.

[[mark-14-2]]
^2^ But they said, “Not on the feast day, lest perhaps there may be a tumult among the people.”

[[mark-14-3]]
^3^ And when he was in Bethania, in the house of Simon the leper, and was reclining to eat, a woman arrived having an alabaster container of ointment, of precious spikenard. And breaking open the alabaster container, she poured it over his head.

[[mark-14-4]]
^4^ But there were some who became indignant within themselves and who were saying: “What is the reason for this waste of the ointment?

[[mark-14-5]]
^5^ For this ointment could have been sold for more than three hundred denarii and been given to the poor.” And they murmured against her.

[[mark-14-6]]
^6^ But Jesus said: “Permit her. What is the reason that you trouble her? She has done a good deed for me.

[[mark-14-7]]
^7^ For the poor, you have with you always. And whenever you wish, you are able to do good to them. But you do not have me always.

[[mark-14-8]]
^8^ But she has done what she could. She has arrived in advance to anoint my body for burial.

[[mark-14-9]]
^9^ Amen I say to you, wherever this Gospel shall be preached throughout the entire world, the things she has done also shall be told, in memory of her.”

[[mark-14-10]]
^10^ And Judas Iscariot, one of the twelve, went away, to the leaders of the priests, in order to betray him to them.

[[mark-14-11]]
^11^ And they, upon hearing it, were gladdened. And they promised him that they would give him money. And he sought an opportune means by which he might betray him.

[[mark-14-12]]
^12^ And on the first day of Unleavened Bread, when they immolate the Passover, the disciples said to him, “Where do you want us to go and prepare for you to eat the Passover?”

[[mark-14-13]]
^13^ And he sent two of his disciples, and he said to them: “Go into the city. And you will meet a man carrying a pitcher of water; follow him.

[[mark-14-14]]
^14^ And wherever he will have entered, say to the owner of the house, ‘The Teacher says: Where is my dining room, where I may eat the Passover with my disciples?’

[[mark-14-15]]
^15^ And he will show you a large cenacle, fully furnished. And there, you shall prepare it for us.”

[[mark-14-16]]
^16^ And his disciples departed and went into the city. And they found it just as he had told them. And they prepared the Passover.

[[mark-14-17]]
^17^ Then, when evening came, he arrived with the twelve.

[[mark-14-18]]
^18^ And while reclining and eating with them at table, Jesus said, “Amen I say to you, that one of you, who eats with me, will betray me.”

[[mark-14-19]]
^19^ But they began to be sorrowful and to say to him, one at a time: “Is it I?”

[[mark-14-20]]
^20^ And he said to them: “It is one of the twelve, who dips his hand with me in the dish.

[[mark-14-21]]
^21^ And indeed, the Son of man goes, just as it has been written of him. But woe to that man by whom the Son of man will be betrayed. It would be better for that man if he had never been born.”

[[mark-14-22]]
^22^ And while eating with them, Jesus took bread. And blessing it, he broke it and gave it to them, and he said: “Take. This is my body.”

[[mark-14-23]]
^23^ And having taken the chalice, giving thanks, he gave it to them. And they all drank from it.

[[mark-14-24]]
^24^ And he said to them: “This is my blood of the new covenant, which shall be shed for many.

[[mark-14-25]]
^25^ Amen I say to you, that I will no longer drink from this fruit of the vine, until that day when I will drink it new in the kingdom of God.”

[[mark-14-26]]
^26^ And having sung a hymn, they went out to the Mount of Olives.

[[mark-14-27]]
^27^ And Jesus said to them: “You will all fall away from me in this night. For it has been written: ‘I will strike the shepherd, and the sheep will be scattered.’

[[mark-14-28]]
^28^ But after I have risen again, I will go before you to Galilee.”

[[mark-14-29]]
^29^ Then Peter said to him, “Even if all will have fallen away from you, yet I will not.”

[[mark-14-30]]
^30^ And Jesus said to him, “Amen I say to you, that this day, in this night, before the rooster has uttered its voice twice, you will deny me three times.”

[[mark-14-31]]
^31^ But he spoke further, “Even if I must die along with you, I will not deny you.” And they all spoke similarly also.

[[mark-14-32]]
^32^ And they went to a country estate, by the name of Gethsemani. And he said to his disciples, “Sit here, while I pray.”

[[mark-14-33]]
^33^ And he took Peter, and James, and John with him. And he began to be afraid and wearied.

[[mark-14-34]]
^34^ And he said to them: “My soul is sorrowful, even unto death. Remain here and be vigilant.”

[[mark-14-35]]
^35^ And when he had proceeded on a little ways, he fell prostrate on the ground. And he prayed that, if it were possible, the hour might pass away from him.

[[mark-14-36]]
^36^ And he said: “Abba, Father, all things are possible to you. Take this chalice from me. But let it be, not as I will, but as you will.”

[[mark-14-37]]
^37^ And he went and found them sleeping. And he said to Peter: “Simon, are you sleeping? Were you not able to be vigilant for one hour?

[[mark-14-38]]
^38^ Watch and pray, so that you may not enter into temptation. The spirit indeed is willing, but the flesh is weak.”

[[mark-14-39]]
^39^ And going away again, he prayed, saying the same words.

[[mark-14-40]]
^40^ And upon returning, he found them sleeping yet again, (for their eyes were heavy) and they did not know how to respond to him.

[[mark-14-41]]
^41^ And he arrived for the third time, and he said to them: “Sleep now, and take rest. It is enough. The hour has arrived. Behold, the Son of man will be betrayed into the hands of sinners.

[[mark-14-42]]
^42^ Rise up, let us go. Behold, he who will betray me is near.”

[[mark-14-43]]
^43^ And while he was still speaking, Judas Iscariot, one of the twelve, arrived, and with him was a large crowd with swords and clubs, sent from the leaders of the priests, and the scribes, and the elders.

[[mark-14-44]]
^44^ Now his betrayer had given them a sign, saying: “He whom I shall kiss, it is he. Take hold of him, and lead him away cautiously.”

[[mark-14-45]]
^45^ And when he had arrived, immediately drawing near to him, he said: “Hail, Master!” And he kissed him.

[[mark-14-46]]
^46^ But they laid hands on him and held him.

[[mark-14-47]]
^47^ Then a certain one of those standing near, drawing a sword, struck a servant of the high priest and cut off his ear.

[[mark-14-48]]
^48^ And in response, Jesus said to them: “Have you set out to apprehend me, just as if to a robber, with swords and clubs?

[[mark-14-49]]
^49^ Daily, I was with you in the temple teaching, and you did not take hold of me. But in this way, the scriptures are fulfilled.”

[[mark-14-50]]
^50^ Then his disciples, leaving him behind, all fled away.

[[mark-14-51]]
^51^ Now a certain young man followed him, having nothing but a fine linen cloth over himself. And they took hold of him.

[[mark-14-52]]
^52^ But he, rejecting the fine linen cloth, escaped from them naked.

[[mark-14-53]]
^53^ And they led Jesus to the high priest. And all the priests and the scribes and the elders came together.

[[mark-14-54]]
^54^ But Peter followed him from a distance, even into the court of the high priest. And he sat with the servants at the fire and warmed himself.

[[mark-14-55]]
^55^ Yet truly, the leaders of the priests and the entire council sought testimony against Jesus, so that they might deliver him to death, and they found none.

[[mark-14-56]]
^56^ For many spoke false testimony against him, but their testimony did not agree.

[[mark-14-57]]
^57^ And certain ones, rising up, bore false witness against him, saying:

[[mark-14-58]]
^58^ “For we heard him say, ‘I will destroy this temple, made with hands, and within three days I will build another, not made with hands.’ ”

[[mark-14-59]]
^59^ And their testimony did not agree.

[[mark-14-60]]
^60^ And the high priest, rising up in their midst, questioned Jesus, saying, “Do you have nothing to say in answer to the things that are brought against you by these ones?”

[[mark-14-61]]
^61^ But he was silent and gave no answer. Again, the high priest questioned him, and he said to him, “Are you the Christ, the Son of the Blessed God?”

[[mark-14-62]]
^62^ Then Jesus said to him: “I am. And you shall see the Son of man sitting at the right hand of the power of God and arriving with the clouds of heaven.”

[[mark-14-63]]
^63^ Then the high priest, rending his garments, said: “Why do we still require witnesses?

[[mark-14-64]]
^64^ You have heard the blasphemy. How does it seem to you?” And they all condemned him, as guilty unto death.

[[mark-14-65]]
^65^ And some began to spit on him, and to cover his face and to strike him with fists, and to say to him, “Prophesy.” And the servants struck him with the palms their hands.

[[mark-14-66]]
^66^ And while Peter was in the court below, one of the maidservants of the high priest arrived.

[[mark-14-67]]
^67^ And when she had seen Peter warming himself, she stared at him, and she said: “You also were with Jesus of Nazareth.”

[[mark-14-68]]
^68^ But he denied it, saying, “I neither know nor understand what you saying.” And he went outside, in front of the court; and a rooster crowed.

[[mark-14-69]]
^69^ Then again, when a maidservant had seen him, she began to say to the bystanders, “For this is one of them.”

[[mark-14-70]]
^70^ But he denied it again. And after a little while, again those standing near said to Peter: “In truth, you are one of them. For you, too, are a Galilean.”

[[mark-14-71]]
^71^ Then he began to curse and to swear, saying, “For I do not know this man, about whom you are speaking.”

[[mark-14-72]]
^72^ And immediately the rooster crowed again. And Peter remembered the word that Jesus had said to him, “Before the rooster crows twice, you will deny me three times.” And he began to weep.


[[mark-15]]
== Chapter 15

[[mark-15-1]]
^1^ And immediately in the morning, after the leaders of the priests had taken counsel with the elders and the scribes and the entire council, binding Jesus, they led him away and delivered him to Pilate.

[[mark-15-2]]
^2^ And Pilate questioned him, “You are the king of the Jews?” But in response, he said to him, “You are saying it.”

[[mark-15-3]]
^3^ And the leaders of the priests accused him in many things.

[[mark-15-4]]
^4^ Then Pilate again questioned him, saying: “Do you not have any response? See how greatly they accuse you.”

[[mark-15-5]]
^5^ But Jesus continued to give no response, so that Pilate wondered.

[[mark-15-6]]
^6^ Now on the feast day, he was accustomed to release to them one of the prisoners, whomever they requested.

[[mark-15-7]]
^7^ But there was one called Barabbas, who had committed murder in the sedition, who was confined with those of the sedition.

[[mark-15-8]]
^8^ And when the crowd had ascended, they began to petition him to do as he always did for them.

[[mark-15-9]]
^9^ But Pilate answered them and said, “Do you want me to release to you the king of the Jews?”

[[mark-15-10]]
^10^ For he knew that it was out of envy that the leaders of the priests had betrayed him.

[[mark-15-11]]
^11^ Then the chief priests incited the crowd, so that he would release Barabbas to them instead.

[[mark-15-12]]
^12^ But Pilate, responding again, said to them: “Then what do you want me to do with the king of the Jews?”

[[mark-15-13]]
^13^ But again they cried out, “Crucify him.”

[[mark-15-14]]
^14^ Yet truly, Pilate said to them: “Why? What evil has he done?” But they cried out all the more, “Crucify him.”

[[mark-15-15]]
^15^ Then Pilate, wishing to satisfy the people, released Barabbas to them, and he delivered Jesus, having severely scourged him, to be crucified.

[[mark-15-16]]
^16^ Then the soldiers led him away to the court of the praetorium. And they called together the entire cohort.

[[mark-15-17]]
^17^ And they clothed him with purple. And platting a crown of thorns, they placed it on him.

[[mark-15-18]]
^18^ And they began to salute him: “Hail, king of the Jews.”

[[mark-15-19]]
^19^ And they struck his head with a reed, and they spit on him. And kneeling down, they reverenced him.

[[mark-15-20]]
^20^ And after they had mocked him, they stripped him of the purple, and they clothed him in his own garments. And they led him away, so that they might crucify him.

[[mark-15-21]]
^21^ And they compelled a certain passerby, Simon the Cyrenian, who was arriving from the countryside, the father of Alexander and Rufus, to take up his cross.

[[mark-15-22]]
^22^ And they led him through to the place called Golgotha, which means, ‘the Place of Calvary.’

[[mark-15-23]]
^23^ And they gave him wine with myrrh to drink. But he did not accept it.

[[mark-15-24]]
^24^ And while crucifying him, they divided his garments, casting lots over them, to see who would take what.

[[mark-15-25]]
^25^ Now it was the third hour. And they crucified him.

[[mark-15-26]]
^26^ And the title of his case was written as: THE KING OF THE JEWS.

[[mark-15-27]]
^27^ And with him they crucified two robbers: one at his right, and the other at his left.

[[mark-15-28]]
^28^ And the scripture was fulfilled, which says: “And with the iniquitous he was reputed.”

[[mark-15-29]]
^29^ And the passersby blasphemed him, shaking their heads and saying, “Ah, you who would destroy the temple of God, and in three days rebuild it,

[[mark-15-30]]
^30^ save yourself by descending from the cross.”

[[mark-15-31]]
^31^ And similarly the leaders of the priests, mocking him with the scribes, said to one another: “He saved others. He is not able to save himself.

[[mark-15-32]]
^32^ Let the Christ, the king of Israel, descend now from the cross, so that we may see and believe.” Those who were crucified with him also insulted him.

[[mark-15-33]]
^33^ And when the sixth hour arrived, a darkness occurred over the entire earth, until the ninth hour.

[[mark-15-34]]
^34^ And at the ninth hour, Jesus cried out with a loud voice, saying, “Eloi, Eloi, lamma sabacthani?” which means, “My God, My God, why have you forsaken me?”

[[mark-15-35]]
^35^ And some of those standing near, upon hearing this, said, “Behold, he is calling Elijah.”

[[mark-15-36]]
^36^ Then one of them, running and filling a sponge with vinegar, and placing it around a reed, gave it to him to drink, saying: “Wait. Let us see if Elijah will come to take him down.”

[[mark-15-37]]
^37^ Then Jesus, having emitted a loud cry, expired.

[[mark-15-38]]
^38^ And the veil of the temple was torn in two, from the top to the bottom.

[[mark-15-39]]
^39^ Then the centurion who stood opposite him, seeing that he had expired while crying out in this way, said: “Truly, this man was the Son of God.”

[[mark-15-40]]
^40^ Now there were also women watching from a distance, among whom were Mary Magdalene, and Mary the mother of James the younger and of Joseph, and Salome,

[[mark-15-41]]
^41^ (and while he was in Galilee, they followed him and ministered to him) and many other women, who had ascended along with him to Jerusalem.

[[mark-15-42]]
^42^ And when evening had now arrived (because it was the Preparation Day, which is before the Sabbath)

[[mark-15-43]]
^43^ there arrived Joseph of Arimathea, a noble council member, who himself was also awaiting the kingdom of God. And he boldly entered to Pilate and petitioned for the body of Jesus.

[[mark-15-44]]
^44^ But Pilate wondered if he had already died. And summoning a centurion, he questioned him as to whether he was already dead.

[[mark-15-45]]
^45^ And when he had been informed by the centurion, he gave the body to Joseph.

[[mark-15-46]]
^46^ Then Joseph, having bought a fine linen cloth, and taking him down, wrapped him in the fine linen and laid him in a sepulcher, which was hewn from a rock. And he rolled a stone to the entrance of the tomb.

[[mark-15-47]]
^47^ Now Mary Magdalene and Mary the mother of Joseph observed where he was laid.


[[mark-16]]
== Chapter 16

[[mark-16-1]]
^1^ And when the Sabbath had passed, Mary Magdalene, and Mary the mother of James, and Salome bought aromatic spices, so that when they arrived they could anoint Jesus.

[[mark-16-2]]
^2^ And very early in the morning, on the first of the Sabbaths, they went to the tomb, the sun having now risen.

[[mark-16-3]]
^3^ And they said to one another, “Who will roll back the stone for us, away from the entrance of the tomb?”

[[mark-16-4]]
^4^ And looking, they saw that the stone was rolled back. For certainly it was very large.

[[mark-16-5]]
^5^ And upon entering the tomb, they saw a young man sitting on the right side, covered with a white robe, and they were astonished.

[[mark-16-6]]
^6^ And he said to them, “Do not become frightened. You are seeking Jesus of Nazareth, the Crucified One. He has risen. He is not here. Behold, the place where they laid him.

[[mark-16-7]]
^7^ But go, tell his disciples and Peter that he is going before you into Galilee. There you shall see him, just as he told you.”

[[mark-16-8]]
^8^ But they, going out, fled from the tomb. For trembling and fear had overwhelmed them. And they said nothing to anyone. For they were afraid.

[[mark-16-9]]
^9^ But he, rising early on the first Sabbath, appeared first to Mary Magdalene, from whom he had cast out seven demons.

[[mark-16-10]]
^10^ She went and announced it to those who had been with him, while they were mourning and weeping.

[[mark-16-11]]
^11^ And they, upon hearing that he was alive and that he had been seen by her, did not believe it.

[[mark-16-12]]
^12^ But after these events, he was shown in another likeness to two of them walking, as they were going out to the countryside.

[[mark-16-13]]
^13^ And they, returning, reported it to the others; neither did they believe them.

[[mark-16-14]]
^14^ Finally, he appeared to the eleven, as they sat at table. And he rebuked them for their incredulity and hardness of heart, because they did not believe those who had seen that he had risen again.

[[mark-16-15]]
^15^ And he said to them: “Go forth to the whole world and preach the Gospel to every creature.

[[mark-16-16]]
^16^ Whoever will have believed and been baptized will be saved. Yet truly, whoever will not have believed will be condemned.

[[mark-16-17]]
^17^ Now these signs will accompany those who believe. In my name, they shall cast out demons. They will speak in new languages.

[[mark-16-18]]
^18^ They will take up serpents, and, if they drink anything deadly, it will not harm them. They shall lay their hands upon the sick, and they will be well.”

[[mark-16-19]]
^19^ And indeed, the Lord Jesus, after he had spoken to them, was taken up into heaven, and he sits at the right hand of God.

[[mark-16-20]]
^20^ Then they, setting out, preached everywhere, with the Lord cooperating and confirming the word by the accompanying signs.
