[[luke]]
= The Gospel of Luke
:short: Luke

[[luke-1]]
== Chapter 1

[[luke-1-1]]
^1^ Since, indeed, many have attempted to set in order a narrative of the things that have been completed among us,

[[luke-1-2]]
^2^ just as they have been handed on to those of us who from the beginning saw the same and were ministers of the word,

[[luke-1-3]]
^3^ so it seemed good to me also, having diligently followed everything from the beginning, to write to you, in an orderly manner, most excellent Theophilus,

[[luke-1-4]]
^4^ so that you might know the truthfulness of those words by which you have been instructed.

[[luke-1-5]]
^5^ There was, in the days of Herod, king of Judea, a certain priest named Zechariah, of the section of Abijah, and his wife was of the daughters of Aaron, and her name was Elizabeth.

[[luke-1-6]]
^6^ Now they were both just before God, progressing in all of the commandments and the justifications of the Lord without blame.

[[luke-1-7]]
^7^ And they had no child, because Elizabeth was barren, and they both had become advanced in years.

[[luke-1-8]]
^8^ Then it happened that, when he was exercising the priesthood before God, in the order of his section,

[[luke-1-9]]
^9^ according to the custom of the priesthood, the lot fell so that he would offer incense, entering into the temple of the Lord.

[[luke-1-10]]
^10^ And the entire multitude of the people was praying outside, at the hour of incense.

[[luke-1-11]]
^11^ Then there appeared to him an Angel of the Lord, standing at the right of the altar of incense.

[[luke-1-12]]
^12^ And upon seeing him, Zechariah was disturbed, and fear fell over him.

[[luke-1-13]]
^13^ But the Angel said to him: “Do not be afraid, Zechariah, for your prayer has been heard, and your wife Elizabeth shall bear a son to you. And you shall call his name John.

[[luke-1-14]]
^14^ And there will be joy and exultation for you, and many will rejoice in his nativity.

[[luke-1-15]]
^15^ For he will be great in the sight of the Lord, and he will not drink wine or strong drink, and he will be filled with the Holy Spirit, even from his mother’s womb.

[[luke-1-16]]
^16^ And he will convert many of the sons of Israel to the Lord their God.

[[luke-1-17]]
^17^ And he will go before him with the spirit and power of Elijah, so that he may turn the hearts of the fathers to the sons, and the incredulous to the prudence of the just, so as to prepare for the Lord a completed people.”

[[luke-1-18]]
^18^ And Zechariah said to the Angel: “How may I know this? For I am elderly, and my wife is advanced in years.”

[[luke-1-19]]
^19^ And in response, the Angel said to him: “I am Gabriel, who stands before God, and I have been sent to speak to you, and to proclaim these things to you.

[[luke-1-20]]
^20^ And behold, you will be silent and unable to speak, until the day on which these things shall be, because you have not believed my words, which will be fulfilled in their time.”

[[luke-1-21]]
^21^ And the people were waiting for Zechariah. And they wondered why he was being delayed in the temple.

[[luke-1-22]]
^22^ Then, when he came out, he was unable to speak to them. And they realized that he had seen a vision in the temple. And he was making signs to them, but he remained mute.

[[luke-1-23]]
^23^ And it happened that, after the days of his office were completed, he went away to his house.

[[luke-1-24]]
^24^ Then, after those days, his wife Elizabeth conceived, and she hid herself for five months, saying:

[[luke-1-25]]
^25^ “For the Lord did this for me, at the time when he decided to take away my reproach among men.”

[[luke-1-26]]
^26^ Then, in the sixth month, the Angel Gabriel was sent by God, to a city of Galilee named Nazareth,

[[luke-1-27]]
^27^ to a virgin betrothed to a man whose name was Joseph, of the house of David; and the name of the virgin was Mary.

[[luke-1-28]]
^28^ And upon entering, the Angel said to her: “Hail, full of grace. The Lord is with you. Blessed are you among women.”

[[luke-1-29]]
^29^ And when she had heard this, she was disturbed by his words, and she considered what kind of greeting this might be.

[[luke-1-30]]
^30^ And the Angel said to her: “Do not be afraid, Mary, for you have found grace with God.

[[luke-1-31]]
^31^ Behold, you shall conceive in your womb, and you shall bear a son, and you shall call his name: JESUS.

[[luke-1-32]]
^32^ He will be great, and he will be called the Son of the Most High, and the Lord God will give him the throne of David his father. And he will reign in the house of Jacob for eternity.

[[luke-1-33]]
^33^ And his kingdom shall have no end.”

[[luke-1-34]]
^34^ Then Mary said to the Angel, “How shall this be done, since I do not know man?”

[[luke-1-35]]
^35^ And in response, the Angel said to her: “The Holy Spirit will pass over you, and the power of the Most High will overshadow you. And because of this also, the Holy One who will be born of you shall be called the Son of God.

[[luke-1-36]]
^36^ And behold, your cousin Elizabeth has herself also conceived a son, in her old age. And this is the sixth month for her who is called barren.

[[luke-1-37]]
^37^ For no word will be impossible with God.”

[[luke-1-38]]
^38^ Then Mary said: “Behold, I am the handmaid of the Lord. Let it be done to me according to your word.” And the Angel departed from her.

[[luke-1-39]]
^39^ And in those days, Mary, rising up, traveled quickly into the hill country, to a city of Judah.

[[luke-1-40]]
^40^ And she entered into the house of Zechariah, and she greeted Elizabeth.

[[luke-1-41]]
^41^ And it happened that, as Elizabeth heard the greeting of Mary, the infant leaped in her womb, and Elizabeth was filled with the Holy Spirit.

[[luke-1-42]]
^42^ And she cried out with a loud voice and said: “Blessed are you among women, and blessed is the fruit of your womb.

[[luke-1-43]]
^43^ And how does this concern me, so that the mother of my Lord would come to me?

[[luke-1-44]]
^44^ For behold, as the voice of your greeting came to my ears, the infant in my womb leaped for joy.

[[luke-1-45]]
^45^ And blessed are you who believed, for the things that were spoken to you by the Lord shall be accomplished.”

[[luke-1-46]]
^46^ And Mary said: “My soul magnifies the Lord.

[[luke-1-47]]
^47^ And my spirit leaps for joy in God my Savior.

[[luke-1-48]]
^48^ For he has looked with favor on the humility of his handmaid. For behold, from this time, all generations shall call me blessed.

[[luke-1-49]]
^49^ For he who is great has done great things for me, and holy is his name.

[[luke-1-50]]
^50^ And his mercy is from generation to generations for those who fear him.

[[luke-1-51]]
^51^ He has accomplished powerful deeds with his arm. He has scattered the arrogant in the intentions of their heart.

[[luke-1-52]]
^52^ He has deposed the powerful from their seat, and he has exalted the humble.

[[luke-1-53]]
^53^ He has filled the hungry with good things, and the rich he has sent away empty.

[[luke-1-54]]
^54^ He has taken up his servant Israel, mindful of his mercy,

[[luke-1-55]]
^55^ just as he spoke to our fathers: to Abraham and to his offspring forever.”

[[luke-1-56]]
^56^ Then Mary stayed with her for about three months. And she returned to her own house.

[[luke-1-57]]
^57^ Now the time for Elizabeth to give birth arrived, and she brought forth a son.

[[luke-1-58]]
^58^ And her neighbors and relatives heard that the Lord had magnified his mercy with her, and so they congratulated her.

[[luke-1-59]]
^59^ And it happened that, on the eighth day, they arrived to circumcise the boy, and they called him by his father’s name, Zechariah.

[[luke-1-60]]
^60^ And in response, his mother said: “Not so. Instead, he shall be called John.”

[[luke-1-61]]
^61^ And they said to her, “But there is no one among your relatives who is called by that name.”

[[luke-1-62]]
^62^ Then they made signs to his father, as to what he wanted him to be called.

[[luke-1-63]]
^63^ And requesting a writing tablet, he wrote, saying: “His name is John.” And they all wondered.

[[luke-1-64]]
^64^ Then, at once, his mouth was opened, and his tongue loosened, and he spoke, blessing God.

[[luke-1-65]]
^65^ And fear fell upon all of their neighbors. And all these words were made known throughout all the hill country of Judea.

[[luke-1-66]]
^66^ And all those who heard it stored it up in their heart, saying: “What do you think this boy will be?” And indeed, the hand of the Lord was with him.

[[luke-1-67]]
^67^ And his father Zechariah was filled with the Holy Spirit. And he prophesied, saying:

[[luke-1-68]]
^68^ “Blessed is the Lord God of Israel. For he has visited and has wrought the redemption of his people.

[[luke-1-69]]
^69^ And he has raised up a horn of salvation for us, in the house of David his servant,

[[luke-1-70]]
^70^ just as he spoke by the mouth of his holy Prophets, who are from ages past:

[[luke-1-71]]
^71^ salvation from our enemies, and from the hand of all those who hate us,

[[luke-1-72]]
^72^ to accomplish mercy with our fathers, and to call to mind his holy testament,

[[luke-1-73]]
^73^ the oath, which he swore to Abraham, our father, that he would grant to us,

[[luke-1-74]]
^74^ so that, having been freed from the hand of our enemies, we may serve him without fear,

[[luke-1-75]]
^75^ in holiness and in justice before him, throughout all our days.

[[luke-1-76]]
^76^ And you, child, shall be called the prophet of the Most High. For you will go before the face of the Lord: to prepare his ways,

[[luke-1-77]]
^77^ to give knowledge of salvation to his people for the remission of their sins,

[[luke-1-78]]
^78^ through the heart of the mercy of our God, by which, descending from on high, he has visited us,

[[luke-1-79]]
^79^ to illuminate those who sit in darkness and in the shadow of death, and to direct our feet in the way of peace.”

[[luke-1-80]]
^80^ And the child grew, and he was strengthened in spirit. And he was in the wilderness, until the day of his manifestation to Israel.


[[luke-2]]
== Chapter 2

[[luke-2-1]]
^1^ And it happened in those days that a decree went out from Caesar Augustus, so that the whole world would be enrolled.

[[luke-2-2]]
^2^ This was the first enrollment; it was made by the ruler of Syria, Quirinius.

[[luke-2-3]]
^3^ And all went to be declared, each one to his own city.

[[luke-2-4]]
^4^ Then Joseph also ascended from Galilee, from the city of Nazareth, into Judea, to the city of David, which is called Bethlehem, because he was of the house and family of David,

[[luke-2-5]]
^5^ in order to be declared, with Mary his espoused wife, who was with child.

[[luke-2-6]]
^6^ Then it happened that, while they were there, the days were completed, so that she would give birth.

[[luke-2-7]]
^7^ And she brought forth her firstborn son. And she wrapped him in swaddling clothes and laid him in a manger, because there was no room for them at the inn.

[[luke-2-8]]
^8^ And there were shepherds in the same region, being vigilant and keeping watch in the night over their flock.

[[luke-2-9]]
^9^ And behold, an Angel of the Lord stood near them, and the brightness of God shone around them, and they were struck with a great fear.

[[luke-2-10]]
^10^ And the Angel said to them: “Do not be afraid. For, behold, I proclaim to you a great joy, which will be for all the people.

[[luke-2-11]]
^11^ For today a Savior has been born for you in the city of David: he is Christ the Lord.

[[luke-2-12]]
^12^ And this will be a sign for you: you will find the infant wrapped in swaddling clothes and lying in a manger.”

[[luke-2-13]]
^13^ And suddenly there was with the Angel a multitude of the celestial army, praising God and saying,

[[luke-2-14]]
^14^ “Glory to God in the highest, and on earth peace to men of good will.”

[[luke-2-15]]
^15^ And it happened that, when the Angels had departed from them into heaven, the shepherds said to one another, “Let us cross over to Bethlehem and see this word, which has happened, which the Lord has revealed to us.”

[[luke-2-16]]
^16^ And they went quickly. And they found Mary and Joseph; and the infant was lying in a manger.

[[luke-2-17]]
^17^ Then, upon seeing this, they understood the word that had been spoken to them about this boy.

[[luke-2-18]]
^18^ And all who heard it were amazed by this, and by those things which were told to them by the shepherds.

[[luke-2-19]]
^19^ But Mary kept all these words, pondering them in her heart.

[[luke-2-20]]
^20^ And the shepherds returned, glorifying and praising God for all the things that they had heard and seen, just as it was told to them.

[[luke-2-21]]
^21^ And after eight days were ended, so that the boy would be circumcised, his name was called JESUS, just as he was called by the Angel before he was conceived in the womb.

[[luke-2-22]]
^22^ And after the days of her purification were fulfilled, according to the law of Moses, they brought him to Jerusalem, in order to present him to the Lord,

[[luke-2-23]]
^23^ just as it is written in the law of the Lord, “For every male opening the womb shall be called holy to the Lord,”

[[luke-2-24]]
^24^ and in order to offer a sacrifice, according to what is said in the law of the Lord, “a pair of turtledoves or two young pigeons.”

[[luke-2-25]]
^25^ And behold, there was a man in Jerusalem, whose name was Simeon, and this man was just and God-fearing, awaiting the consolation of Israel. And the Holy Spirit was with him.

[[luke-2-26]]
^26^ And he had received an answer from the Holy Spirit: that he would not see his own death before he had seen the Christ of the Lord.

[[luke-2-27]]
^27^ And he went with the Spirit to the temple. And when the child Jesus was brought in by his parents, in order to act on his behalf according to the custom of the law,

[[luke-2-28]]
^28^ he also took him up, into his arms, and he blessed God and said:

[[luke-2-29]]
^29^ “Now you may dismiss your servant in peace, O Lord, according to your word.

[[luke-2-30]]
^30^ For my eyes have seen your salvation,

[[luke-2-31]]
^31^ which you have prepared before the face of all peoples:

[[luke-2-32]]
^32^ the light of revelation to the nations and the glory of your people Israel.”

[[luke-2-33]]
^33^ And his father and mother were wondering over these things, which were spoken about him.

[[luke-2-34]]
^34^ And Simeon blessed them, and he said to his mother Mary: “Behold, this one has been set for the ruin and for the resurrection of many in Israel, and as a sign which will be contradicted.

[[luke-2-35]]
^35^ And a sword will pass through your own soul, so that the thoughts of many hearts may be revealed.”

[[luke-2-36]]
^36^ And there was a prophetess, Anna, a daughter of Phanuel, from the tribe of Asher. She was very advanced in years, and she had lived with her husband for seven years from her virginity.

[[luke-2-37]]
^37^ And then she was a widow, even to her eighty-fourth year. And without departing from the temple, she was a servant to fasting and prayer, night and day.

[[luke-2-38]]
^38^ And entering at the same hour, she confessed to the Lord. And she spoke about him to all who were awaiting the redemption of Israel.

[[luke-2-39]]
^39^ And after they had performed all things according to the law of the Lord, they returned to Galilee, to their city, Nazareth.

[[luke-2-40]]
^40^ Now the child grew, and he was strengthened with the fullness of wisdom. And the grace of God was in him.

[[luke-2-41]]
^41^ And his parents went every year to Jerusalem, at the time of the solemnity of Passover.

[[luke-2-42]]
^42^ And when he had become twelve years old, they ascended to Jerusalem, according to the custom of the feast day.

[[luke-2-43]]
^43^ And having completed the days, when they returned, the boy Jesus remained in Jerusalem. And his parents did not realize this.

[[luke-2-44]]
^44^ But, supposing that he was in the company, they went a day’s journey, seeking him among their relatives and acquaintances.

[[luke-2-45]]
^45^ And not finding him, they returned to Jerusalem, seeking him.

[[luke-2-46]]
^46^ And it happened that, after three days, they found him in the temple, sitting in the midst of the doctors, listening to them and questioning them.

[[luke-2-47]]
^47^ But all who listened to him were astonished over his prudence and his responses.

[[luke-2-48]]
^48^ And upon seeing him, they wondered. And his mother said to him: “Son, why have you acted this way toward us? Behold, your father and I were seeking you in sorrow.”

[[luke-2-49]]
^49^ And he said to them: “How is it that you were seeking me? For did you not know that it is necessary for me to be in these things which are of my Father?”

[[luke-2-50]]
^50^ And they did not understand the word that he spoke to them.

[[luke-2-51]]
^51^ And he descended with them and went to Nazareth. And he was subordinate to them. And his mother kept all these words in her heart.

[[luke-2-52]]
^52^ And Jesus advanced in wisdom, and in age, and in grace, with God and men.


[[luke-3]]
== Chapter 3

[[luke-3-1]]
^1^ Then, in the fifteenth year of the reign of Tiberius Caesar, Pontius Pilate being procurator of Judea, and Herod tetrarch of Galilee, and his brother Philip tetrarch of Ituraea and of the region of Trachonitis, and Lysanias tetrarch of Abilene,

[[luke-3-2]]
^2^ under the high priests Annas and Caiaphas: the word of the Lord came to John, the son of Zechariah, in the wilderness.

[[luke-3-3]]
^3^ And he went into the entire region of the Jordan, preaching a baptism of repentance for the remission of sins,

[[luke-3-4]]
^4^ just as it has been written in the book of the sermons of the prophet Isaiah: “The voice of one crying out in the wilderness: Prepare the way of the Lord. Make straight his paths.

[[luke-3-5]]
^5^ Every valley shall be filled, and every mountain and hill shall be brought low. And what is crooked shall be made straight. And the rough paths shall be made into level ways.

[[luke-3-6]]
^6^ And all flesh shall see the salvation of God.”

[[luke-3-7]]
^7^ Therefore, he said to the crowd that went out in order to be baptized by him: “You progeny of vipers! Who told you to flee from the approaching wrath?

[[luke-3-8]]
^8^ So then, produce fruits worthy of repentance. And do not begin to say, ‘We have Abraham as our father.’ For I tell you that God has the power to raise up sons to Abraham from these stones.

[[luke-3-9]]
^9^ For even now the axe has been placed at the root of the trees. Therefore, every tree that does not produce good fruit shall be cut down and cast into the fire.”

[[luke-3-10]]
^10^ And the crowed was questioning him, saying, “What then should we do?”

[[luke-3-11]]
^11^ But in response, he said to them: “Whoever has two coats, let him give to those who do not have. And whoever has food, let him act similarly.”

[[luke-3-12]]
^12^ Now the tax collectors also came to be baptized, and they said to him, “Teacher, what should we do?”

[[luke-3-13]]
^13^ But he said to them, “You should do nothing more than what has been appointed to you.”

[[luke-3-14]]
^14^ Then the soldiers also questioned him, saying, “And what should we do?” And he said to them: “You should strike no one, and you should not make false accusations. And be content with your pay.”

[[luke-3-15]]
^15^ Now all were thinking about John in their hearts, and the people were supposing that perhaps he might be the Christ.

[[luke-3-16]]
^16^ John responded by saying to everyone: “Indeed, I baptize you with water. But there will arrive one stronger than me, the laces of whose shoes I am not worthy to loosen. He will baptize you in the Holy Spirit, and with fire.

[[luke-3-17]]
^17^ His winnowing fan is in his hand. And he will purify his threshing floor. And he will gather the wheat into the barn. But the chaff he will burn with unquenchable fire.”

[[luke-3-18]]
^18^ Indeed, he also proclaimed many other things, exhorting the people.

[[luke-3-19]]
^19^ But Herod the tetrarch, when he was corrected by him concerning Herodias, his brother’s wife, and concerning all the evils that Herod had done,

[[luke-3-20]]
^20^ added this also, above all else: that he confined John to prison.

[[luke-3-21]]
^21^ Now it happened that, when all the people were being baptized, Jesus was baptized; and as he was praying, heaven was opened.

[[luke-3-22]]
^22^ And the Holy Spirit, in a corporal appearance like a dove, descended upon him. And a voice came from heaven: “You are my beloved Son. In you, I am well pleased.”

[[luke-3-23]]
^23^ And Jesus himself was beginning to be about thirty years old, being (as it was supposed) the son of Joseph, who was of Heli, who was of Matthat,

[[luke-3-24]]
^24^ who was of Levi, who was of Melchi, who was of Jannai, who was of Joseph,

[[luke-3-25]]
^25^ who was of Mattathias, who was of Amos, who was of Nahum, who was of Esli, who was of Naggai,

[[luke-3-26]]
^26^ who was of Maath, who was of Mattathias, who was of Semein, who was of Josech, who was of Joda,

[[luke-3-27]]
^27^ who was of Joanan, who was of Rhesa, who was of Zerubbabel, who was of Shealtiel, who was of Neri,

[[luke-3-28]]
^28^ who was of Melchi, who was of Addi, who was of Cosam, who was of Elmadam, who was of Er,

[[luke-3-29]]
^29^ who was of Joshua, who was of Eliezer, who was of Jorim, who was of Matthat, who was of Levi,

[[luke-3-30]]
^30^ who was of Simeon, who was of Judah, who was of Joseph, who was of Jonam, who was of Eliakim,

[[luke-3-31]]
^31^ who was of Melea, who was of Menna, who was of Mattatha, who was of Nathan, who was of David,

[[luke-3-32]]
^32^ who was of Jesse, who was of Obed, who was of Boaz, who was of Salmon, who was of Nahshon,

[[luke-3-33]]
^33^ who was of Amminadab, who was of Aram, who was of Hezron, who was of Perez, who was of Judah,

[[luke-3-34]]
^34^ who was of Jacob, who was of Isaac, who was of Abraham, who was of Terah, who was of Nahor,

[[luke-3-35]]
^35^ who was of Serug, who was of Reu, who was of Peleg, who was of Eber, who was of Shelah,

[[luke-3-36]]
^36^ who was of Cainan, who was of Arphaxad, who was of Shem, who was of Noah, who was of Lamech,

[[luke-3-37]]
^37^ who was of Methuselah, who was of Enoch, who was of Jared, who was of Mahalalel, who was of Cainan,

[[luke-3-38]]
^38^ who was of Enos, who was of Seth, who was of Adam, who was of God.


[[luke-4]]
== Chapter 4

[[luke-4-1]]
^1^ And Jesus, filled with the Holy Spirit, returned from the Jordan. And he was urged by the Spirit into the wilderness

[[luke-4-2]]
^2^ for forty days, and he was tested by the devil. And he ate nothing in those days. And when they were completed, he was hungry.

[[luke-4-3]]
^3^ Then the devil said to him, “If you are the Son of God, speak to this stone, so that it may be made into bread.”

[[luke-4-4]]
^4^ And Jesus answered him, “It is written: ‘Man shall not live by bread alone, but by every word of God.’ ”

[[luke-4-5]]
^5^ And the devil led him onto a high mountain, and he showed him all the kingdoms of the world in a moment of time,

[[luke-4-6]]
^6^ and he said to him: “To you, I will give all this power, and its glory. For they have been handed over to me, and I give them to whomever I wish.

[[luke-4-7]]
^7^ Therefore, if you will worship before me, all will be yours.”

[[luke-4-8]]
^8^ And in response, Jesus said to him: “It is written: ‘You shall worship the Lord your God, and you shall serve him alone.’ ”

[[luke-4-9]]
^9^ And he brought him to Jerusalem, and he set him on the parapet of the temple, and he said to him: “If you are the Son of God, cast yourself down from here.

[[luke-4-10]]
^10^ For it is written that he has given his Angels charge over you, so that they may guard you,

[[luke-4-11]]
^11^ and so that they may take you into their hands, lest perhaps you may hurt your foot against a stone.”

[[luke-4-12]]
^12^ And in response, Jesus said to him, “It is said: ‘You shall not tempt the Lord your God.’ ”

[[luke-4-13]]
^13^ And when all the temptation was completed, the devil withdrew from him, until a time.

[[luke-4-14]]
^14^ And Jesus returned, in the power of the Spirit, into Galilee. And his fame spread throughout the entire region.

[[luke-4-15]]
^15^ And he taught in their synagogues, and he was magnified by everyone.

[[luke-4-16]]
^16^ And he went to Nazareth, where he had been raised. And he entered into the synagogue, according to his custom, on the Sabbath day. And he rose up to read.

[[luke-4-17]]
^17^ And the book of the prophet Isaiah was handed to him. And as he unrolled the book, he found the place where it was written:

[[luke-4-18]]
^18^ “The Spirit of the Lord is upon me; because of this, he has anointed me. He has sent me to evangelize the poor, to heal the contrite of heart,

[[luke-4-19]]
^19^ to preach forgiveness to captives and sight to the blind, to release the broken into forgiveness, to preach the acceptable year of the Lord and the day of retribution.”

[[luke-4-20]]
^20^ And when he had rolled up the book, he returned it to the minister, and he sat down. And the eyes of everyone in the synagogue were fixed on him.

[[luke-4-21]]
^21^ Then he began to say to them, “On this day, this scripture has been fulfilled in your hearing.”

[[luke-4-22]]
^22^ And everyone gave testimony to him. And they wondered at the words of grace that proceeded from his mouth. And they said, “Is this not the son of Joseph?”

[[luke-4-23]]
^23^ And he said to them: “Certainly, you will recite to me this saying, ‘Physician, heal yourself.’ The many great things that we have heard were done in Capernaum, do here also in your own country.”

[[luke-4-24]]
^24^ Then he said: “Amen I say to you, that no prophet is accepted in his own country.

[[luke-4-25]]
^25^ In truth, I say to you, there were many widows in the days of Elijah in Israel, when the heavens were closed for three years and six months, when a great famine had occurred throughout the entire land.

[[luke-4-26]]
^26^ And to none of these was Elijah sent, except to Zarephath of Sidon, to a woman who was a widow.

[[luke-4-27]]
^27^ And there were many lepers in Israel under the prophet Elisha. And none of these was cleansed, except Naaman the Syrian.”

[[luke-4-28]]
^28^ And all those in the synagogue, upon hearing these things, were filled with anger.

[[luke-4-29]]
^29^ And they rose up and drove him beyond the city. And they brought him all the way to the edge of the mount, upon which their city had been built, so that they might throw him down violently.

[[luke-4-30]]
^30^ But passing through their midst, he went away.

[[luke-4-31]]
^31^ And he descended to Capernaum, a city of Galilee. And there he taught them on the Sabbaths.

[[luke-4-32]]
^32^ And they were astonished at his doctrine, for his word was spoken with authority.

[[luke-4-33]]
^33^ And in the synagogue, there was a man who had an unclean demon, and he cried out with a loud voice,

[[luke-4-34]]
^34^ saying: “Let us alone. What are we to you, Jesus of Nazareth? Have you come to destroy us? I know you who you are: the Holy One of God.”

[[luke-4-35]]
^35^ And Jesus rebuked him, saying, “Be silent and depart from him.” And when the demon had thrown him into their midst, he departed from him, and he no longer harmed him.

[[luke-4-36]]
^36^ And fear fell over them all. And they discussed this among themselves, saying: “What is this word? For with authority and power he commands the unclean spirits, and they depart.”

[[luke-4-37]]
^37^ And his fame spread to every place in the region.

[[luke-4-38]]
^38^ Then Jesus, rising up from the synagogue, entered into the house of Simon. Now Simon’s mother-in-law was in the grip of a severe fever. And they petitioned him on her behalf.

[[luke-4-39]]
^39^ And standing over her, he commanded the fever, and it left her. And promptly rising up, she ministered to them.

[[luke-4-40]]
^40^ Then, when the sun had set, all those who had anyone afflicted with various diseases brought them to him. Then, laying his hands on each one of them, he cured them.

[[luke-4-41]]
^41^ Now demons departed from many of them, crying out and saying, “You are the son of God.” And rebuking them, he would not permit them to speak. For they knew him to be the Christ.

[[luke-4-42]]
^42^ Then, when it was daytime, going out, he went to a deserted place. And the crowds sought him, and they went all the way to him. And they detained him, so that he would not depart from them.

[[luke-4-43]]
^43^ And he said to them, “I must also preach the kingdom of God to other cities, because it was for this reason that I was sent.”

[[luke-4-44]]
^44^ And he was preaching in the synagogues of Galilee.


[[luke-5]]
== Chapter 5

[[luke-5-1]]
^1^ Now it happened that, when the crowds pressed toward him, so that they might hear the word of God, he was standing beside the lake of Genesaret.

[[luke-5-2]]
^2^ And he saw two boats standing beside the lake. But the fishermen had climbed down, and they were washing their nets.

[[luke-5-3]]
^3^ And so, climbing into one of the boats, which belonged to Simon, he asked him to draw back a little from the land. And sitting down, he taught the crowds from the boat.

[[luke-5-4]]
^4^ Then, when he had ceased speaking, he said to Simon, “Lead us into deep water, and release your nets for a catch.”

[[luke-5-5]]
^5^ And in response, Simon said to him: “Teacher, working throughout the night, we caught nothing. But on your word, I will release the net.”

[[luke-5-6]]
^6^ And when they had done this, they enclosed such a copious multitude of fish that their net was rupturing.

[[luke-5-7]]
^7^ And they signaled to their associates, who were in the other boat, so that they would come and help them. And they came and filled both boats, so that they were nearly submerged.

[[luke-5-8]]
^8^ But when Simon Peter had seen this, he fell down at the knees of Jesus, saying, “Depart from me, Lord, for I am a sinful man.”

[[luke-5-9]]
^9^ For astonishment had enveloped him, and all who were with him, at the catch of fish that they had taken.

[[luke-5-10]]
^10^ Now the same was true of James and John, the sons of Zebedee, who were associates of Simon. And Jesus said to Simon: “Do not be afraid. From now on, you will be catching men.”

[[luke-5-11]]
^11^ And having led their boats to land, leaving behind everything, they followed him.

[[luke-5-12]]
^12^ And it happened that, while he was in a certain city, behold, there was a man full of leprosy who, upon seeing Jesus and falling to his face, petitioned him, saying: “Lord, if you are willing, you are able to cleanse me.”

[[luke-5-13]]
^13^ And extending his hand, he touched him, saying: “I am willing. Be cleansed.” And at once, the leprosy departed from him.

[[luke-5-14]]
^14^ And he instructed him that he should tell no one, “But go, show yourself to the priest, and make the offering for your cleansing, just as Moses has commanded, as a testimony for them.”

[[luke-5-15]]
^15^ Yet word of him traveled around all the more. And great crowds came together, so that they might listen and be cured by him from their infirmities.

[[luke-5-16]]
^16^ And he withdrew into the desert and prayed.

[[luke-5-17]]
^17^ And it happened, on a certain day, that he again sat down, teaching. And there were Pharisees and doctors of the law sitting nearby, who had come from every town of Galilee and Judea and Jerusalem. And the power of the Lord was present, to heal them.

[[luke-5-18]]
^18^ And behold, some men were carrying in the bed of a man who was paralyzed. And they sought a way to bring him in, and to place him before him.

[[luke-5-19]]
^19^ And not finding a way by which they might bring him in, because of the crowd, they climbed up to the roof, and they let him down through the roof tiles with his bed, into their midst, in front of Jesus.

[[luke-5-20]]
^20^ And when he saw his faith, he said, “Man, your sins are forgiven you.”

[[luke-5-21]]
^21^ And the scribes and Pharisees began to think, saying: “Who is this, who is speaking blasphemies? Who is able to forgive sins, except God alone?”

[[luke-5-22]]
^22^ But when Jesus realized their thoughts, responding, he said to them: “What are you thinking in your hearts?

[[luke-5-23]]
^23^ Which is easier to say: ‘Your sins are forgiven you,’ or to say, ‘Rise up and walk?’

[[luke-5-24]]
^24^ But so that you may know that the Son of man has authority on earth to forgive sins,” he said to the paralytic, “I say to you to: Rise up, take up your bed, and go into your house.”

[[luke-5-25]]
^25^ And at once, rising up in their sight, he took up the bed on which he was lying, and he went away to his own house, magnifying God.

[[luke-5-26]]
^26^ And astonishment took hold of everyone, and they were magnifying God. And they were filled with fear, saying: “For we have seen miracles today.”

[[luke-5-27]]
^27^ And after these things, he went out, and he saw a tax collector named Levi, sitting at the customs office. And he said to him, “Follow me.”

[[luke-5-28]]
^28^ And leaving behind everything, rising up, he followed him.

[[luke-5-29]]
^29^ And Levi made a great feast for him in his own house. And there was a large crowd of tax collectors and others, who were sitting at table with them.

[[luke-5-30]]
^30^ But the Pharisees and scribes were murmuring, saying to his disciples, “Why do you eat and drink with tax collectors and sinners?”

[[luke-5-31]]
^31^ And responding, Jesus said to them: “It is not those who are well who need a doctor, but those who have maladies.

[[luke-5-32]]
^32^ I have not come to call the just, but sinners to repentance.”

[[luke-5-33]]
^33^ But they said to him, “Why do the disciples of John fast frequently, and make supplications, and those of the Pharisees act similarly, while yours eat and drink?”

[[luke-5-34]]
^34^ And he said to them: “How can you cause the sons of the groom to fast, while the groom is still with them?

[[luke-5-35]]
^35^ But the days will come when the groom will be taken away from them, and then they will fast, in those days.”

[[luke-5-36]]
^36^ Then he also made a comparison for them: “For no one sews a patch from a new garment onto an old garment. Otherwise, he both disrupts the new one, and the patch from the new one does not join together with the old one.

[[luke-5-37]]
^37^ And no one puts new wine into old wineskins. Otherwise, the new wine ruptures the wineskins, and it will be poured out, and the wineskins will be lost.

[[luke-5-38]]
^38^ Instead, the new wine is put into new wineskins, and both are preserved.

[[luke-5-39]]
^39^ And no one who is drinking the old, soon wishes for the new. For he says, ‘The old is better.’ ”


[[luke-6]]
== Chapter 6

[[luke-6-1]]
^1^ Now it happened that, on the second first Sabbath, as he passed through the grain field, his disciples were separating the ears of grain and eating them, by rubbing them in their hands.

[[luke-6-2]]
^2^ Then certain Pharisees said to them, “Why are you doing what is not lawful on the Sabbaths?”

[[luke-6-3]]
^3^ And responding to them, Jesus said: “Have you not read this, what David did when he was hungry, and those who were with him?

[[luke-6-4]]
^4^ How he entered into the house of God, and took the bread of the Presence, and ate it, and gave it to those who were with him, though it is not lawful for anyone to eat it, except the priests alone?”

[[luke-6-5]]
^5^ And he said to them, “For the Son of man is Lord, even of the Sabbath.”

[[luke-6-6]]
^6^ And it happened that, on another Sabbath, he entered into the synagogue, and he taught. And there was a man there, and his right hand was withered.

[[luke-6-7]]
^7^ And the scribes and Pharisees observed whether he would heal on the Sabbath, so that they might thereby find an accusation against him.

[[luke-6-8]]
^8^ Yet truly, he knew their thoughts, and so he said to the man who had the withered hand, “Rise up and stand in the middle.” And rising up, he stood still.

[[luke-6-9]]
^9^ Then Jesus said to them: “I ask you if it is lawful on the Sabbaths to do good, or to do evil? To give health to a life, or to destroy it?”

[[luke-6-10]]
^10^ And looking around at everyone, he said to the man, “Extend your hand.” And he extended it. And his hand was restored.

[[luke-6-11]]
^11^ Then they were filled with madness, and they discussed with one another, what, in particular, they might do about Jesus.

[[luke-6-12]]
^12^ And it happened that, in those days, he went out to a mountain to pray. And he was in the prayer of God throughout the night.

[[luke-6-13]]
^13^ And when daylight had arrived, he called his disciples. And he chose twelve out of them (whom he also named Apostles):

[[luke-6-14]]
^14^ Simon, whom he surnamed Peter, and Andrew his brother, James and John, Philip and Bartholomew,

[[luke-6-15]]
^15^ Matthew and Thomas, James of Alphaeus, and Simon who is called the Zealot,

[[luke-6-16]]
^16^ and Jude of James, and Judas Iscariot, who was a traitor.

[[luke-6-17]]
^17^ And descending with them, he stood in a level place with a multitude of his disciples, and a copious multitude of people from all of Judea and Jerusalem and the seacoast, and Tyre and Sidon,

[[luke-6-18]]
^18^ who had come so that they might listen to him and be healed of their diseases. And those who were troubled by unclean spirits were cured.

[[luke-6-19]]
^19^ And the entire crowd was trying to touch him, because power went out from him and healed all.

[[luke-6-20]]
^20^ And lifting up his eyes to his disciples, he said: “Blessed are you poor, for yours is the kingdom of God.

[[luke-6-21]]
^21^ Blessed are you who are hungry now, for you shall be satisfied. Blessed are you who are weeping now, for you shall laugh.

[[luke-6-22]]
^22^ Blessed shall you be when men will have hated you, and when they will have separated you and reproached you, and thrown out your name as if evil, because of the Son of man.

[[luke-6-23]]
^23^ Be glad in that day and exult. For behold, your reward is great in heaven. For these same things their fathers did to the prophets.

[[luke-6-24]]
^24^ Yet truly, woe to you who are wealthy, for you have your consolation.

[[luke-6-25]]
^25^ Woe to you who are satisfied, for you will be hungry. Woe to you who laugh now, for you will mourn and weep.

[[luke-6-26]]
^26^ Woe to you when men will have blessed you. For these same things their fathers did to the false prophets.

[[luke-6-27]]
^27^ But I say to you who are listening: Love your enemies. Do good to those who hate you.

[[luke-6-28]]
^28^ Bless those who curse you, and pray for those who slander you.

[[luke-6-29]]
^29^ And to him who strikes you on the cheek, offer the other also. And from him who takes away your coat, do not withhold even your tunic.

[[luke-6-30]]
^30^ But distribute to all who ask of you. And do not ask again of him who takes away what is yours.

[[luke-6-31]]
^31^ And exactly as you would want people to treat you, treat them also the same.

[[luke-6-32]]
^32^ And if you love those who love you, what credit is due to you? For even sinners love those who love them.

[[luke-6-33]]
^33^ And if you will do good to those who do good to you, what credit is due to you? Indeed, even sinners behave this way.

[[luke-6-34]]
^34^ And if you will loan to those from whom you hope to receive, what credit is due to you? For even sinners lend to sinners, in order to receive the same in return.

[[luke-6-35]]
^35^ So truly, love your enemies. Do good, and lend, hoping for nothing in return. And then your reward will be great, and you will be sons of the Most High, for he himself is kind to the ungrateful and to the wicked.

[[luke-6-36]]
^36^ Therefore, be merciful, just as your Father is also merciful.

[[luke-6-37]]
^37^ Do not judge, and you will not be judged. Do not condemn, and you will not be condemned. Forgive, and you will be forgiven.

[[luke-6-38]]
^38^ Give, and it will be given to you: a good measure, pressed down and shaken together and overflowing, they will place upon your lap. Certainly, the same measure that you use to measure out, will be used to measure back to you again.”

[[luke-6-39]]
^39^ Now he told them another comparison: “How can the blind lead the blind? Would they not both fall into a pit?

[[luke-6-40]]
^40^ The disciple is not above his teacher. But each one will be perfected, if he is like his teacher.

[[luke-6-41]]
^41^ And why do you see the straw that is in your brother’s eye, while the log that is in your own eye, you do not consider?

[[luke-6-42]]
^42^ Or how can you say to your brother, ‘Brother, allow me to remove the straw from your eye,’ while you yourself do not see the log in your own eye? Hypocrite, first remove the log from your own eye, and then will you see clearly, so that you may lead out the straw from your brother’s eye.

[[luke-6-43]]
^43^ For there is no good tree which produces bad fruit, nor does an evil tree produce good fruit.

[[luke-6-44]]
^44^ For each and every tree is known by its fruit. For they do not gather figs from thorns, nor do they gather the grape from the bramble bush.

[[luke-6-45]]
^45^ A good man, from the good storehouse of his heart, offers what is good. And an evil man, from the evil storehouse, offers what is evil. For out of the abundance of the heart, the mouth speaks.

[[luke-6-46]]
^46^ But why do you call me, ‘Lord, Lord,’ and not do what I say?

[[luke-6-47]]
^47^ Anyone who comes to me, and listens to my words, and does them: I will reveal to you what he is like.

[[luke-6-48]]
^48^ He is like a man building a house, who has dug deep and has laid the foundation upon the rock. Then, when the floodwaters came, the river was rushing against that house, and it was not able to move it. For it was founded upon the rock.

[[luke-6-49]]
^49^ But whoever hears and does not do: he is like a man building his house upon the soil, without a foundation. The river rushed against it, and it soon fell down, and the ruin of that house was great.”


[[luke-7]]
== Chapter 7

[[luke-7-1]]
^1^ And when he had completed all his words in the hearing of the people, he entered Capernaum.

[[luke-7-2]]
^2^ Now the servant of a certain centurion was dying, due to an illness. And he was very dear to him.

[[luke-7-3]]
^3^ And when he had heard about Jesus, he sent elders of the Jews to him, petitioning him, so that he would come and heal his servant.

[[luke-7-4]]
^4^ And when they had come to Jesus, they petitioned him anxiously, saying to him: “He is worthy that you should provide this to him.

[[luke-7-5]]
^5^ For he loves our nation, and he has built a synagogue for us.”

[[luke-7-6]]
^6^ Then Jesus went with them. And when he was now not far from the house, the centurion sent friends to him, saying: “Lord, do not trouble yourself. For I am not worthy that you should enter under my roof.

[[luke-7-7]]
^7^ Because of this, I also did not consider myself worthy to come to you. But say the word, and my servant shall be healed.

[[luke-7-8]]
^8^ For I also am a man placed under authority, having soldiers under me. And I say to one, ‘Go,’ and he goes; and to another, ‘Come,’ and he comes; and to my servant, ‘Do this,’ and he does it.”

[[luke-7-9]]
^9^ And upon hearing this, Jesus was amazed. And turning to the multitude following him, he said, “Amen I say to you, not even in Israel have I found such great faith.”

[[luke-7-10]]
^10^ And those who had been sent, upon returning to the house, found that the servant, who had been sick, was now healthy.

[[luke-7-11]]
^11^ And it happened afterwards that he went to a city, which is called Nain. And his disciples, and an abundant crowd, went with him.

[[luke-7-12]]
^12^ Then, when he had drawn near to the gate of the city, behold, a deceased person was being carried out, the only son of his mother, and she was a widow. And a large crowd from the city was with her.

[[luke-7-13]]
^13^ And when the Lord had seen her, being moved by mercy over her, he said to her, “Do not weep.”

[[luke-7-14]]
^14^ And he drew near and touched the coffin. Then those who carried it stood still. And he said, “Young man, I say to you, arise.”

[[luke-7-15]]
^15^ And the dead youth sat up and began to speak. And he gave him to his mother.

[[luke-7-16]]
^16^ Then fear fell over all of them. And they magnified God, saying: “For a great prophet has risen up among us,” and, “For God has visited his people.”

[[luke-7-17]]
^17^ And this word about him went out to all of Judea and to the entire surrounding region.

[[luke-7-18]]
^18^ And the disciples of John reported to him concerning all these things.

[[luke-7-19]]
^19^ And John called two of his disciples, and he sent them to Jesus, saying, “Are you he who is to come, or should we wait for another?”

[[luke-7-20]]
^20^ But when the men had come to him, they said: “John the Baptist has sent us to you, saying: ‘Are you he who is to come, or should we wait for another?’ ”

[[luke-7-21]]
^21^ Now in that same hour, he cured many of their diseases and wounds and evil spirits; and to many of the blind, he gave sight.

[[luke-7-22]]
^22^ And responding, he said to them: “Go and report to John what you have heard and seen: that the blind see, the lame walk, the lepers are cleansed, the deaf hear, the dead rise again, the poor are evangelized.

[[luke-7-23]]
^23^ And blessed is anyone who has not taken offense at me.”

[[luke-7-24]]
^24^ And when the messengers of John had withdrawn, he began to speak about John to the crowds. “What did you go out to the desert to see? A reed shaken by the wind?

[[luke-7-25]]
^25^ Then what did you go out to see? A man clothed in soft garments? Behold, those who are in costly apparel and finery are in the houses of kings.

[[luke-7-26]]
^26^ Then what did you go out to see? A prophet? Certainly, I tell you, and more than a prophet.

[[luke-7-27]]
^27^ This is he of whom it is written: “Behold, I send my Angel before your face, who shall prepare your way before you.”

[[luke-7-28]]
^28^ For I say to you, among those born of women, no one is greater than the prophet John the Baptist. But he who is least in the kingdom of God is greater than he.”

[[luke-7-29]]
^29^ And upon hearing this, all the people and the tax collectors justified God, by being baptized with the baptism of John.

[[luke-7-30]]
^30^ But the Pharisees and the experts in the law despised the counsel of God concerning themselves, by not being baptized by him.

[[luke-7-31]]
^31^ Then the Lord said: “Therefore, to what shall I compare the men of this generation? And to what are they similar?

[[luke-7-32]]
^32^ They are like children sitting in the marketplace, talking with one another, and saying: ‘We sang to you, and you did not dance. We lamented, and you did not weep.’

[[luke-7-33]]
^33^ For John the Baptist came, neither eating bread nor drinking wine, and you say, ‘He has a demon.’

[[luke-7-34]]
^34^ The Son of man came, eating and drinking, and you say, ‘Behold, a voracious man and a drinker of wine, a friend of tax collectors and of sinners.’

[[luke-7-35]]
^35^ But wisdom is justified by all her children.”

[[luke-7-36]]
^36^ Then certain Pharisees petitioned him, so that they might eat with him. And he went into the house of the Pharisee, and he reclined at table.

[[luke-7-37]]
^37^ And behold, a woman who was in the city, a sinner, found out that he was reclining at table in the house of the Pharisee, so she brought an alabaster container of ointment.

[[luke-7-38]]
^38^ And standing behind him, beside his feet, she began to wash his feet with tears, and she wiped them with the hair of her head, and she kissed his feet, and she anointed them with ointment.

[[luke-7-39]]
^39^ Then the Pharisee, who had invited him, upon seeing this, spoke within himself, saying, “This man, if he were a prophet, would certainly know who and what kind of woman is this, who is touching him: that she is a sinner.”

[[luke-7-40]]
^40^ And in response, Jesus said to him, “Simon, I have something to say to you.” So he said, “Speak, Teacher.”

[[luke-7-41]]
^41^ “A certain creditor had two debtors: one owed five hundred denarii, and the other fifty.

[[luke-7-42]]
^42^ And since they did not have the ability to repay him, he forgave them both. So then, which of them loves him more?”

[[luke-7-43]]
^43^ In response, Simon said, “I suppose that it is he to whom he forgave the most.” And he said to him, “You have judged correctly.”

[[luke-7-44]]
^44^ And turning to the woman, he said to Simon: “Do you see this woman? I entered into your house. You gave me no water for my feet. But she has washed my feet with tears, and has wiped them with her hair.

[[luke-7-45]]
^45^ You gave no kiss to me. But she, from the time that she entered, has not ceased to kiss my feet.

[[luke-7-46]]
^46^ You did not anoint my head with oil. But she has anointed my feet with ointment.

[[luke-7-47]]
^47^ Because of this, I tell you: many sins are forgiven her, because she has loved much. But he who is forgiven less, loves less.”

[[luke-7-48]]
^48^ Then he said to her, “Your sins are forgiven you.”

[[luke-7-49]]
^49^ And those who sat at table with him began to say within themselves, “Who is this, who even forgives sins?”

[[luke-7-50]]
^50^ Then he said to the woman: “Your faith has brought you salvation. Go in peace.”


[[luke-8]]
== Chapter 8

[[luke-8-1]]
^1^ And it happened afterwards that he was making a journey through the cities and towns, preaching and evangelizing the kingdom of God. And the twelve were with him,

[[luke-8-2]]
^2^ along with certain women who had been healed of evil spirits and infirmities: Mary, who is called Magdalene, from whom seven demons had departed,

[[luke-8-3]]
^3^ and Joanna, the wife of Chuza, Herod’s steward, and Susanna, and many other women, who were ministering to him from their resources.

[[luke-8-4]]
^4^ Then, when a very numerous crowd was gathering together and hurrying from the cities to him, he spoke using a comparison:

[[luke-8-5]]
^5^ “The sower went out to sow his seed. And as he sowed, some fell beside the way; and it was trampled and the birds of the air devoured it.

[[luke-8-6]]
^6^ And some fell upon rock; and having sprung up, it withered away, because it had no moisture.

[[luke-8-7]]
^7^ And some fell among thorns; and the thorns, rising up with it, suffocated it.

[[luke-8-8]]
^8^ And some fell upon good soil; and having sprung up, it produced fruit one hundredfold.” As he said these things, he cried out, “Whoever has ears to hear, let him hear.”

[[luke-8-9]]
^9^ Then his disciples questioned him as to what this parable might mean.

[[luke-8-10]]
^10^ And he said to them: “To you it has been given to know the mystery of the kingdom of God. But to the rest, it is in parables, so that: seeing, they may not perceive, and hearing, they may not understand.

[[luke-8-11]]
^11^ Now the parable is this: The seed is the word of God.

[[luke-8-12]]
^12^ And those beside the way are those who hear it, but then the devil comes and takes the word from their heart, lest by believing it they may be saved.

[[luke-8-13]]
^13^ Now those upon rock are those who, when they hear it, accept the word with joy, but these have no roots. So they believe for a time, but in a time of testing, they fall away.

[[luke-8-14]]
^14^ And those which fell among thorns are those who have heard it, but as they go along, they are suffocated by the concerns and riches and pleasures of this life, and so they do not yield fruit.

[[luke-8-15]]
^15^ But those which were on good soil are those who, upon hearing the word with a good and noble heart, retain it, and they bring forth fruit in patience.

[[luke-8-16]]
^16^ Now no one, lighting a candle, covers it with a container, or sets it under a bed. Instead, he places it on a lampstand, so that those who enter may see the light.

[[luke-8-17]]
^17^ For there is nothing secret, which will not be made clear, nor is there anything hidden, which will not be known and be brought into plain sight.

[[luke-8-18]]
^18^ Therefore, take care how you listen. For whoever has, it will be given to him; and whoever does not have, even what he thinks he has will be taken away from him.”

[[luke-8-19]]
^19^ Then his mother and brothers came to him; but they were not able to go to him because of the crowd.

[[luke-8-20]]
^20^ And it was reported to him, “Your mother and your brothers are standing outside, wanting to see you.”

[[luke-8-21]]
^21^ And in response, he said to them, “My mother and my brothers are those who hear the word of God and do it.”

[[luke-8-22]]
^22^ Now it happened, on a certain day, that he climbed into a little boat with his disciples. And he said to them, “Let us make a crossing over the lake.” And they embarked.

[[luke-8-23]]
^23^ And as they were sailing, he slept. And a windstorm descended over the lake. And they were taking on water and were in danger.

[[luke-8-24]]
^24^ Then, drawing near, they awakened him, saying, “Teacher, we are perishing.” But as he rose up, he rebuked the wind and the raging water, and they ceased. And a tranquility occurred.

[[luke-8-25]]
^25^ Then he said to them, “Where is your faith?” And they, being afraid, were amazed, saying to one another, “Who do you think this is, so that he commands both wind and sea, and they obey him?”

[[luke-8-26]]
^26^ And they sailed to the region of the Gerasenes, which is opposite Galilee.

[[luke-8-27]]
^27^ And when he had gone out to the land, a certain man met him, who had now had a demon for a long time. And he did not wear clothes, nor did he stay in a house, but among the sepulchers.

[[luke-8-28]]
^28^ And when he saw Jesus, he fell down before him. And crying out in a loud voice, he said: “What is there between me and you, Jesus, Son of the Most High God? I beg you not to torture me.”

[[luke-8-29]]
^29^ For he was ordering the unclean spirit to depart from the man. For on many occasions, it would seize him, and he was bound with chains and held by fetters. But breaking the chains, he was driven by the demon into deserted places.

[[luke-8-30]]
^30^ Then Jesus questioned him, saying, “What is your name?” And he said, “Legion,” because many demons had entered into him.

[[luke-8-31]]
^31^ And they petitioned him not to order them to go into the abyss.

[[luke-8-32]]
^32^ And in that place, there was a herd of many swine, pasturing on the mountain. And they petitioned him to permit them to enter into them. And he permitted them.

[[luke-8-33]]
^33^ Therefore, the demons departed from the man, and they entered into the swine. And the herd rushed violently down a precipice into the lake, and they were drowned.

[[luke-8-34]]
^34^ And when those who were pasturing them had seen this, they fled and reported it in the city and the villages.

[[luke-8-35]]
^35^ Then they went out to see what was happening, and they came to Jesus. And they found the man, from whom the demons had departed, sitting at his feet, clothed as well as in a sane mind, and they were afraid.

[[luke-8-36]]
^36^ Then those who had seen this also reported to them how he had been healed from the legion.

[[luke-8-37]]
^37^ And the entire multitude from the region of the Gerasenes pleaded with him to depart from them. For they were seized by a great fear. Then, climbing into the boat, he went back again.

[[luke-8-38]]
^38^ And the man from whom the demons had departed pleaded with him, so that he might be with him. But Jesus sent him away, saying,

[[luke-8-39]]
^39^ “Return to your house and explain to them what great things God has done for you.” And he traveled through the entire city, preaching about the great things that Jesus had done for him.

[[luke-8-40]]
^40^ Now it happened that, when Jesus had returned, the crowd received him. For they were all waiting for him.

[[luke-8-41]]
^41^ And behold, a man came, whose name was Jairus, and he was a leader of the synagogue. And he fell down at the feet of Jesus, asking him to enter into his house.

[[luke-8-42]]
^42^ For he had an only daughter, nearly twelve years old, and she was dying. And it happened that, as he was going there, he was hemmed in by the crowd.

[[luke-8-43]]
^43^ And there was a certain woman, with a flow of blood for twelve years, who had paid out all her substance on physicians, and she was unable to be cured by any of them.

[[luke-8-44]]
^44^ She approached him from behind, and she touched the hem of his garment. And at once the flow of her blood stopped.

[[luke-8-45]]
^45^ And Jesus said, “Who is it that touched me?” But as everyone was denying it, Peter, and those who were with him, said: “Teacher, the crowd hems you in and presses upon you, and yet you say, ‘Who touched me?’ ”

[[luke-8-46]]
^46^ And Jesus said: “Someone has touched me. For I know that power has gone out from me.”

[[luke-8-47]]
^47^ Then the woman, upon seeing that she was not hidden, came forward, trembling, and she fell down before his feet. And she declared before all the people the reason that she had touched him, and how she had been immediately healed.

[[luke-8-48]]
^48^ But he said to her: “Daughter, your faith has saved you. Go in peace.”

[[luke-8-49]]
^49^ While he was still speaking, someone came to the ruler of the synagogue, saying to him: “Your daughter is dead. Do not trouble him.”

[[luke-8-50]]
^50^ Then Jesus, upon hearing this word, replied to the father of the girl: “Do not be afraid. Only believe, and she will be saved.”

[[luke-8-51]]
^51^ And when he had arrived at the house, he would not permit anyone to enter with him, except Peter and James and John, and the father and mother of the girl.

[[luke-8-52]]
^52^ Now all were weeping and mourning for her. But he said: “Do not weep. The girl is not dead, but only sleeping.”

[[luke-8-53]]
^53^ And they derided him, knowing that she had died.

[[luke-8-54]]
^54^ But he, taking her by the hand, cried out, saying, “Little girl, arise.”

[[luke-8-55]]
^55^ And her spirit returned, and she immediately rose up. And he ordered them to give her something to eat.

[[luke-8-56]]
^56^ And her parents were stupefied. And he instructed them not to tell anyone what had happened.


[[luke-9]]
== Chapter 9

[[luke-9-1]]
^1^ Then calling together the twelve Apostles, he gave them power and authority over all demons and to cure diseases.

[[luke-9-2]]
^2^ And he sent them to preach the kingdom of God and to heal the infirm.

[[luke-9-3]]
^3^ And he said to them: “You should take nothing for the journey, neither staff, nor traveling bag, nor bread, nor money; and you should not have two tunics.

[[luke-9-4]]
^4^ And into whatever house you shall enter, lodge there, and do not move away from there.

[[luke-9-5]]
^5^ And whoever will not have received you, upon departing from that city, shake off even the dust on your feet, as a testimony against them.”

[[luke-9-6]]
^6^ And going forth, they traveled around, through the towns, evangelizing and curing everywhere.

[[luke-9-7]]
^7^ Now Herod the tetrarch heard about all the things that were being done by him, but he doubted, because it was said

[[luke-9-8]]
^8^ by some, “For John has risen from the dead,” yet truly, by others, “For Elijah has appeared,” and by still others, “For one of the prophets from of old has risen again.”

[[luke-9-9]]
^9^ And Herod said: “I beheaded John. So then, who is this, about whom I hear such things?” And he sought to see him.

[[luke-9-10]]
^10^ And when the Apostles returned, they explained to him all the things that they had done. And taking them with him, he withdrew to a deserted place apart, which belongs to Bethsaida.

[[luke-9-11]]
^11^ But when the crowd had realized this, they followed him. And he received them and spoke to them about the kingdom of God. And those who were in need of cures, he healed.

[[luke-9-12]]
^12^ Then the day began to decline. And drawing near, the twelve said to him: “Dismiss the crowds, so that, by going into the surrounding towns and villages, they may separate and find food. For we are here in a deserted place.”

[[luke-9-13]]
^13^ But he said to them, “You give them something to eat.” And they said, “There is with us no more than five loaves and two fish, unless perhaps we are to go and buy food for this entire multitude.”

[[luke-9-14]]
^14^ Now there were about five thousand men. So he said to his disciples, “Have them recline to eat in groups of fifty.”

[[luke-9-15]]
^15^ And they did so. And they caused them all to recline to eat.

[[luke-9-16]]
^16^ Then, taking the five loaves and the two fish, he gazed up to heaven, and he blessed and broke and distributed them to his disciples, in order to set them before the crowd.

[[luke-9-17]]
^17^ And they all ate and were satisfied. And twelve baskets of fragments were taken up, which were left over from them.

[[luke-9-18]]
^18^ And it happened that, when he was praying alone, his disciples also were with him, and he questioned them, saying: “Who do the multitudes say that I am?”

[[luke-9-19]]
^19^ But they answered by saying: “John the Baptist. But some say Elijah. Yet truly, others say that one of the prophets from before has risen again.”

[[luke-9-20]]
^20^ Then he said to them, “But who do you say that I am?” In response, Simon Peter said, “The Christ of God.”

[[luke-9-21]]
^21^ But speaking sharply to them, he instructed them not to tell this to anyone,

[[luke-9-22]]
^22^ saying, “For the Son of man must suffer many things, and be rejected by the elders and the leaders of the priests and the scribes, and be killed, and on the third day rise again.”

[[luke-9-23]]
^23^ Then he said to everyone: “If anyone is willing to come after me: let him deny himself, and take up his cross every day, and follow me.

[[luke-9-24]]
^24^ For whoever will have saved his life, will lose it. Yet whoever will have lost his life for my sake, will save it.

[[luke-9-25]]
^25^ For how does it benefit a man, if he were to gain the whole world, yet lose himself, or cause himself harm?

[[luke-9-26]]
^26^ For whoever will be ashamed of me and of my words: of him the Son of man will be ashamed, when he will have arrived in his majesty and that of his Father and of the holy Angels.

[[luke-9-27]]
^27^ And yet, I tell you a truth: There are some standing here who shall not taste death, until they see the kingdom of God.”

[[luke-9-28]]
^28^ And it happened that, about eight days after these words, he took Peter and James and John, and he ascended onto a mountain, so that he might pray.

[[luke-9-29]]
^29^ And while he was praying, the appearance of his countenance was altered, and his vestment became white and shining.

[[luke-9-30]]
^30^ And behold, two men were talking with him. And these were Moses and Elijah, appearing in majesty.

[[luke-9-31]]
^31^ And they spoke of his departure, which he would accomplish at Jerusalem.

[[luke-9-32]]
^32^ Yet truly, Peter and those who were with him were weighed down by sleep. And becoming alert, they saw his majesty and the two men who were standing with him.

[[luke-9-33]]
^33^ And it happened that, as these were departing from him, Peter said to Jesus: “Teacher, it is good for us to be here. And so, let us make three tabernacles: one for you, and one for Moses, and one for Elijah.” For he did not know what he was saying.

[[luke-9-34]]
^34^ Then, as he was saying these things, a cloud came and overshadowed them. And as these were entering into the cloud, they were afraid.

[[luke-9-35]]
^35^ And a voice came from the cloud, saying: “This is my beloved Son. Listen to him.”

[[luke-9-36]]
^36^ And while the voice was being uttered, Jesus was found to be alone. And they were silent and told no one, in those days, any of these things, which they had seen.

[[luke-9-37]]
^37^ But it happened on the following day that, as they were descending from the mountain, a great crowd met him.

[[luke-9-38]]
^38^ And behold, a man from the crowd cried out, saying, “Teacher, I beg you, look kindly on my son, for he is my only son.

[[luke-9-39]]
^39^ And behold, a spirit takes hold of him, and he suddenly cries out, and it throws him down and convulses him, so that he foams. And though it tears him apart, it leaves him only with difficulty.

[[luke-9-40]]
^40^ And I asked your disciples to cast him out, and they were unable.”

[[luke-9-41]]
^41^ And in response, Jesus said: “O unfaithful and perverse generation! How long will I be with you and endure you? Bring your son here.”

[[luke-9-42]]
^42^ And as he was approaching him, the demon threw him down and convulsed him.

[[luke-9-43]]
^43^ And Jesus rebuked the unclean spirit, and he healed the boy, and he restored him to his father.

[[luke-9-44]]
^44^ And all were astonished at the greatness of God. And as everyone was wondering over all that he was doing, he said to his disciples: “You must set these words in your hearts. For it shall be that the Son of man will be delivered into the hands of men.”

[[luke-9-45]]
^45^ But they did not understand this word, and it was concealed from them, so that they did not perceive it. And they were afraid to question him about this word.

[[luke-9-46]]
^46^ Now an idea entered into them, as to which of them was greater.

[[luke-9-47]]
^47^ But Jesus, perceiving the thoughts of their hearts, took a child and stood him beside him.

[[luke-9-48]]
^48^ And he said to them: “Whoever will receive this child in my name, receives me; and whoever receives me, receives him who sent me. For whoever is the lesser among you all, the same is greater.”

[[luke-9-49]]
^49^ And responding, John said: “Teacher, we saw a certain one casting out demons in your name. And we prohibited him, for he does not follow with us.”

[[luke-9-50]]
^50^ And Jesus said to him: “Do not prohibit him. For whoever is not against you, is for you.”

[[luke-9-51]]
^51^ Now it happened that, while the days of his dissipation were being completed, he steadfastly set his face to go to Jerusalem.

[[luke-9-52]]
^52^ And he sent messengers before his face. And going on, they entered into a city of the Samaritans, to prepare for him.

[[luke-9-53]]
^53^ And they would not receive him, because his face was going toward Jerusalem.

[[luke-9-54]]
^54^ And when his disciples, James and John, had seen this, they said, “Lord, do you want us to call for fire to descend from heaven and consume them?”

[[luke-9-55]]
^55^ And turning, he rebuked them, saying: “Do you not know of whose spirit you are?

[[luke-9-56]]
^56^ The Son of man came, not to destroy lives, but to save them.” And they went into another town.

[[luke-9-57]]
^57^ And it happened that, as they were walking along the way, someone said to him, “I will follow you, wherever you will go.”

[[luke-9-58]]
^58^ Jesus said to him: “Foxes have dens, and the birds of the air have nests. But the Son of man has nowhere to lay his head.”

[[luke-9-59]]
^59^ Then he said to another, “Follow me.” But he said, “Lord, permit me first to go and bury my father.”

[[luke-9-60]]
^60^ And Jesus said to him: “Let the dead bury their dead. But you go and announce the kingdom of God.”

[[luke-9-61]]
^61^ And another said: “I will follow you, Lord. But permit me first to explain this to those of my house.”

[[luke-9-62]]
^62^ Jesus said to him, “No one who puts his hand to the plow, and then looks back, is fit for the kingdom of God.”


[[luke-10]]
== Chapter 10

[[luke-10-1]]
^1^ Then, after these things, the Lord also designated another seventy-two. And he sent them in pairs before his face, into every city and place where he was to arrive.

[[luke-10-2]]
^2^ And he said to them: “Certainly the harvest is great, but the workers are few. Therefore, ask the Lord of the harvest to send workers into his harvest.

[[luke-10-3]]
^3^ Go forth. Behold, I send you out like lambs among wolves.

[[luke-10-4]]
^4^ Do not choose to carry a purse, nor provisions, nor shoes; and you shall greet no one along the way.

[[luke-10-5]]
^5^ Into whatever house you will have entered, first say, ‘Peace to this house.’

[[luke-10-6]]
^6^ And if a son of peace is there, your peace will rest upon him. But if not, it will return to you.

[[luke-10-7]]
^7^ And remain in the same house, eating and drinking the things that are with them. For the worker is worthy of his pay. Do not choose to pass from house to house.

[[luke-10-8]]
^8^ And into whatever city you have entered and they have received you, eat what they set before you.

[[luke-10-9]]
^9^ And cure the sick who are in that place, and proclaim to them, ‘The kingdom of God has drawn near to you.’

[[luke-10-10]]
^10^ But into whatever city you have entered and they have not received you, going out into its main streets, say:

[[luke-10-11]]
^11^ ‘Even the dust which clings to us from your city, we wipe away against you. Yet know this: the kingdom of God has drawn near.’

[[luke-10-12]]
^12^ I say to you, that in that day, Sodom will be forgiven more than that city will be.

[[luke-10-13]]
^13^ Woe to you, Chorazin! Woe to you, Bethsaida! For if the miracles that have been wrought in you, had been wrought in Tyre and Sidon, they would have repented long ago, sitting in haircloth and ashes.

[[luke-10-14]]
^14^ Yet truly, Tyre and Sidon will be forgiven more in the judgment than you will be.

[[luke-10-15]]
^15^ And as for you, Capernaum, who would be exalted even up to Heaven: you shall be submerged into Hell.

[[luke-10-16]]
^16^ Whoever hears you, hears me. And whoever despises you, despises me. And whoever despises me, despises him who sent me.”

[[luke-10-17]]
^17^ Then the seventy-two returned with gladness, saying, “Lord, even the demons are subject to us, in your name.”

[[luke-10-18]]
^18^ And he said to them: “I was watching as Satan fell like lightning from heaven.

[[luke-10-19]]
^19^ Behold, I have given you authority to tread upon serpents and scorpions, and upon all the powers of the enemy, and nothing shall hurt you.

[[luke-10-20]]
^20^ Yet truly, do not choose to rejoice in this, that the spirits are subject to you; but rejoice that your names are written in heaven.”

[[luke-10-21]]
^21^ In the same hour, he exulted in the Holy Spirit, and he said: “I confess to you, Father, Lord of heaven and earth, because you have hidden these things from the wise and the prudent, and have revealed them to little ones. It is so, Father, because this way was pleasing before you.

[[luke-10-22]]
^22^ All things have been delivered to me by my Father. And no one knows who the Son is, except the Father, and who the Father is, except the Son, and those to whom the Son has chosen to reveal him.”

[[luke-10-23]]
^23^ And turning to his disciples, he said: “Blessed are the eyes that see what you see.

[[luke-10-24]]
^24^ For I say to you, that many prophets and kings wanted to see the things that you see, and they did not see them, and to hear the things that you hear, and they did not hear them.”

[[luke-10-25]]
^25^ And behold, a certain expert in the law rose up, testing him and saying, “Teacher, what must I do to possess eternal life?”

[[luke-10-26]]
^26^ But he said to him: “What is written in the law? How do you read it?”

[[luke-10-27]]
^27^ In response, he said: “You shall love the Lord your God from your whole heart, and from your whole soul, and from all your strength, and from all your mind, and your neighbor as yourself.”

[[luke-10-28]]
^28^ And he said to him: “You have answered correctly. Do this, and you will live.”

[[luke-10-29]]
^29^ But since he wanted to justify himself, he said to Jesus, “And who is my neighbor?”

[[luke-10-30]]
^30^ Then Jesus, taking this up, said: “A certain man descended from Jerusalem to Jericho, and he happened upon robbers, who now also plundered him. And inflicting him with wounds, they went away, leaving him behind, half-alive.

[[luke-10-31]]
^31^ And it happened that a certain priest was descending along the same way. And seeing him, he passed by.

[[luke-10-32]]
^32^ And similarly a Levite, when he was near the place, also saw him, and he passed by.

[[luke-10-33]]
^33^ But a certain Samaritan, being on a journey, came near him. And seeing him, he was moved by mercy.

[[luke-10-34]]
^34^ And approaching him, he bound up his wounds, pouring oil and wine on them. And setting him on his pack animal, he brought him to an inn, and he took care of him.

[[luke-10-35]]
^35^ And the next day, he took out two denarii, and he gave them to the proprietor, and he said: ‘Take care of him. And whatever extra you will have spent, I will repay to you at my return.’

[[luke-10-36]]
^36^ Which of these three, does it seem to you, was a neighbor to him who fell among the robbers?”

[[luke-10-37]]
^37^ Then he said, “The one who acted with mercy toward him.” And Jesus said to him, “Go, and act similarly.”

[[luke-10-38]]
^38^ Now it happened that, while they were traveling, he entered into a certain town. And a certain woman, named Martha, received him into her home.

[[luke-10-39]]
^39^ And she had a sister, named Mary, who, while sitting beside the Lord’s feet, was listening to his word.

[[luke-10-40]]
^40^ Now Martha was continually busying herself with serving. And she stood still and said: “Lord, is it not a concern to you that my sister has left me to serve alone? Therefore, speak to her, so that she may help me.”

[[luke-10-41]]
^41^ And the Lord responded by saying to her: “Martha, Martha, you are anxious and troubled over many things.

[[luke-10-42]]
^42^ And yet only one thing is necessary. Mary has chosen the best portion, and it shall not be taken away from her.”


[[luke-11]]
== Chapter 11

[[luke-11-1]]
^1^ And it happened that, while he was in a certain place praying, when he ceased, one of his disciples said to him, “Lord, teach us to pray, as John also taught his disciples.”

[[luke-11-2]]
^2^ And he said to them: “When you are praying, say: Father, may your name be kept holy. May your kingdom come.

[[luke-11-3]]
^3^ Give us this day our daily bread.

[[luke-11-4]]
^4^ And forgive us our sins, since we also forgive all who are indebted to us. And lead us not into temptation.”

[[luke-11-5]]
^5^ And he said to them: “Which of you will have a friend and will go to him in the middle of the night, and will say to him: ‘Friend, lend me three loaves,

[[luke-11-6]]
^6^ because a friend of mine has arrived from a journey to me, and I do not have anything to set before him.’

[[luke-11-7]]
^7^ And from within, he would answer by saying: ‘Do not disturb me. The door is closed now, and my children and I are in bed. I cannot get up and give it to you.’

[[luke-11-8]]
^8^ Yet if he will persevere in knocking, I tell you that, even though he would not get up and give it to him because he is a friend, yet due to his continued insistence, he will get up and give him whatever he needs.

[[luke-11-9]]
^9^ And so I say to you: Ask, and it shall be given to you. Seek, and you shall find. Knock, and it shall be opened to you.

[[luke-11-10]]
^10^ For everyone who asks, receives. And whoever seeks, finds. And whoever knocks, it shall be opened to him.

[[luke-11-11]]
^11^ So then, who among you, if he asks his father for bread, he would give him a stone? Or if he asks for a fish, he would give him a serpent, instead of a fish?

[[luke-11-12]]
^12^ Or if he will ask for an egg, he would offer to him a scorpion?

[[luke-11-13]]
^13^ Therefore, if you, being evil, know how to give good things to your sons, how much more will your Father give, from heaven, a spirit of goodness to those who ask him?”

[[luke-11-14]]
^14^ And he was casting out a demon, and the man was mute. But when he had cast out the demon, the mute man spoke, and so the crowds were amazed.

[[luke-11-15]]
^15^ But some of them said, “It is by Beelzebub, the leader of demons, that he casts out demons.”

[[luke-11-16]]
^16^ And others, testing him, required a sign from heaven of him.

[[luke-11-17]]
^17^ But when he perceived their thoughts, he said to them: “Every kingdom divided against itself will become desolate, and house will fall upon house.

[[luke-11-18]]
^18^ So then, if Satan is also divided against himself, how will his kingdom stand? For you say that it is by Beelzebub that I cast out demons.

[[luke-11-19]]
^19^ But if I cast out demons by Beelzebub, by whom do your own sons cast them out? Therefore, they shall be your judges.

[[luke-11-20]]
^20^ Moreover, if it is by the finger of God that I cast out demons, then certainly the kingdom of God has overtaken you.

[[luke-11-21]]
^21^ When a strong armed man guards his entrance, the things that he possesses are at peace.

[[luke-11-22]]
^22^ But if a stronger one, overwhelming him, has defeated him, he will take away all his weapons, in which he trusted, and he will distribute his spoils.

[[luke-11-23]]
^23^ Whoever is not with me, is against me. And whoever does not gather with me, scatters.

[[luke-11-24]]
^24^ When an unclean spirit has departed from a man, he walks through waterless places, seeking rest. And not finding any, he says: ‘I will return to my house, from which I departed.’

[[luke-11-25]]
^25^ And when he has arrived, he finds it swept clean and decorated.

[[luke-11-26]]
^26^ Then he goes, and he takes in seven other spirits with him, more wicked than himself, and they enter and live there. And so, the end of that man is made worse than the beginning.”

[[luke-11-27]]
^27^ And it happened that, when he was saying these things, a certain woman from the crowd, lifting up her voice, said to him, “Blessed is the womb that bore you and the breasts that nursed you.”

[[luke-11-28]]
^28^ Then he said, “Yes, but moreover: blessed are those who hear the word of God and keep it.”

[[luke-11-29]]
^29^ Then, as the crowds were quickly gathering, he began to say: “This generation is a wicked generation: it seeks a sign. But no sign will be given to it, except the sign of the prophet Jonah.

[[luke-11-30]]
^30^ For just as Jonah was a sign to the Ninevites, so also will the Son of man be to this generation.

[[luke-11-31]]
^31^ The queen of the South will rise up, at the judgment, with the men of this generation, and she will condemn them. For she came from the ends of the earth to hear the wisdom of Solomon. And behold, more than Solomon is here.

[[luke-11-32]]
^32^ The men of Nineveh will rise up, at the judgment, with this generation, and they will condemn it. For at the preaching of Jonah, they repented. And behold, more than Jonah is here.

[[luke-11-33]]
^33^ No one lights a candle and places it in hiding, nor under a bushel basket, but upon a lampstand, so that those who enter may see the light.

[[luke-11-34]]
^34^ Your eye is the light of your body. If your eye is wholesome, your entire body will be filled with light. But if it is wicked, then even your body will be darkened.

[[luke-11-35]]
^35^ Therefore, take care, lest the light that is within you become darkness.

[[luke-11-36]]
^36^ So then, if your entire body becomes filled with light, not having any part in darkness, then it will be entirely light, and, like a shining lamp, it will illuminate you.”

[[luke-11-37]]
^37^ And as he was speaking, a certain Pharisee asked him to eat with him. And going inside, he sat down to eat.

[[luke-11-38]]
^38^ But the Pharisee began to say, thinking within himself: “Why might it be that he has not washed before eating?”

[[luke-11-39]]
^39^ And the Lord said to him: “You Pharisees today clean what is outside the cup and the plate, but what is inside of you is full of plunder and iniquity.

[[luke-11-40]]
^40^ Fools! Did not he who made what is outside, indeed also make what is inside?

[[luke-11-41]]
^41^ Yet truly, give what is above as alms, and behold, all things are clean for you.

[[luke-11-42]]
^42^ But woe to you, Pharisees! For you tithe mint and rue and every herb, but you ignore judgment and the charity of God. But these things you ought to have done, without omitting the others.

[[luke-11-43]]
^43^ Woe to you, Pharisees! For you love the first seats in the synagogues, and greetings in the marketplace.

[[luke-11-44]]
^44^ Woe to you! For you are like graves that are not noticeable, so that men walk over them without realizing it.”

[[luke-11-45]]
^45^ Then one of the experts in the law, in response, said to him, “Teacher, in saying these things, you bring an insult against us as well.”

[[luke-11-46]]
^46^ So he said: “And woe to you experts in the law! For you weigh men down with burdens which they are not able to bear, but you yourselves do not touch the weight with even one of your fingers.

[[luke-11-47]]
^47^ Woe to you, who build the tombs of the prophets, while it is your fathers who killed them!

[[luke-11-48]]
^48^ Clearly, you are testifying that you consent to the actions of your fathers, because even though they killed them, you build their sepulchers.

[[luke-11-49]]
^49^ Because of this also, the wisdom of God said: I will send to them Prophets and Apostles, and some of these they will kill or persecute,

[[luke-11-50]]
^50^ so that the blood of all the Prophets, which has been shed since the foundation of the world, may be charged against this generation:

[[luke-11-51]]
^51^ from the blood of Abel, even to the blood of Zachariah, who perished between the altar and the sanctuary. So I say to you: it will be required of this generation!

[[luke-11-52]]
^52^ Woe to you, experts in the law! For you have taken away the key of knowledge. You yourselves do not enter, and those who were entering, you would have prohibited.”

[[luke-11-53]]
^53^ Then, while he was saying these things to them, the Pharisees and the experts in the law began to insist strongly that he restrain his mouth about many things.

[[luke-11-54]]
^54^ And waiting to ambush him, they sought something from his mouth that they might seize upon, in order to accuse him.


[[luke-12]]
== Chapter 12

[[luke-12-1]]
^1^ Then, as great crowds were standing so close that they were stepping on one another, he began to say to his disciples: “Beware of the leaven of the Pharisees, which is hypocrisy.

[[luke-12-2]]
^2^ For there is nothing covered, which will not be revealed, nor anything hidden, which will not be known.

[[luke-12-3]]
^3^ For the things that you have spoken in darkness will be declared in the light. And what you have said in the ear in bedrooms will be proclaimed from the housetops.

[[luke-12-4]]
^4^ So I say to you, my friends: Do not be fearful of those who kill the body, and afterwards have no more that they can do.

[[luke-12-5]]
^5^ But I will reveal to you whom you should fear. Fear him who, after he will have killed, has the power to cast into Hell. So I say to you: Fear him.

[[luke-12-6]]
^6^ Are not five sparrows sold for two small coins? And yet not one of these is forgotten in the sight of God.

[[luke-12-7]]
^7^ But even the very hairs of your head have all been numbered. Therefore, do not be afraid. You are worth more than many sparrows.

[[luke-12-8]]
^8^ But I say to you: Everyone who will have confessed me before men, the Son of man will also confess him before the Angels of God.

[[luke-12-9]]
^9^ But everyone who will have denied me before men, he will be denied before the Angels of God.

[[luke-12-10]]
^10^ And everyone who speaks a word against the Son of man, it will be forgiven of him. But of him who will have blasphemed against the Holy Spirit, it will not be forgiven.

[[luke-12-11]]
^11^ And when they will lead you to the synagogues, and to magistrates and authorities, do not choose to be worried about how or what you will answer, or about what you might say.

[[luke-12-12]]
^12^ For the Holy Spirit will teach you, in the same hour, what you must say.”

[[luke-12-13]]
^13^ And someone from the crowd said to him, “Teacher, tell my brother to share the inheritance with me.”

[[luke-12-14]]
^14^ But he said to him, “Man, who has appointed me as judge or arbitrator over you?”

[[luke-12-15]]
^15^ So he said to them: “Be cautious and wary of all avarice. For a person’s life is not found in the abundance of the things that he possesses.”

[[luke-12-16]]
^16^ Then he spoke to them using a comparison, saying: “The fertile land of a certain wealthy man produced crops.

[[luke-12-17]]
^17^ And he thought within himself, saying: ‘What should I do? For I have nowhere to gather together my crops.’

[[luke-12-18]]
^18^ And he said: ‘This is what I will do. I will tear down my barns and build larger ones. And into these, I will gather all the things that have been grown for me, as well as my goods.

[[luke-12-19]]
^19^ And I will say to my soul: Soul, you have many goods, stored up for many years. Relax, eat, drink, and be cheerful.’

[[luke-12-20]]
^20^ But God said to him: ‘Foolish one, this very night they require your soul of you. To whom, then, will those things belong, which you have prepared?’

[[luke-12-21]]
^21^ So it is with him who stores up for himself, and is not wealthy with God.”

[[luke-12-22]]
^22^ And he said to his disciples: “And so I say to you: Do not choose to be anxious about your life, as to what you may eat, nor about your body, as to what you will wear.

[[luke-12-23]]
^23^ Life is more than food, and the body is more than clothing.

[[luke-12-24]]
^24^ Consider the ravens. For they neither sow nor reap; there is no storehouse or barn for them. And yet God pastures them. How much more are you, compared to them?

[[luke-12-25]]
^25^ But which of you, by thinking, is able to add one cubit to his stature?

[[luke-12-26]]
^26^ Therefore, if you are not capable, in what is so little, why be anxious about the rest?

[[luke-12-27]]
^27^ Consider the lilies, how they grow. They neither work nor weave. But I say to you, not even Solomon, in all his glory, was clothed like one of these.

[[luke-12-28]]
^28^ Therefore, if God so clothes the grass, which is in the field today and thrown into the furnace tomorrow, how much more you, O little in faith?

[[luke-12-29]]
^29^ And so, do not choose to inquire as to what you will eat, or what you will drink. And do not choose to be lifted up on high.

[[luke-12-30]]
^30^ For all these things are sought by the Gentiles of the world. And your Father knows that you have need of these things.

[[luke-12-31]]
^31^ Yet truly, seek first the kingdom of God, and his justice, and all these things shall be added to you.

[[luke-12-32]]
^32^ Do not be afraid, little flock; for it has pleased your Father to give you the kingdom.

[[luke-12-33]]
^33^ Sell what you possess, and give alms. Make for yourselves purses that will not wear out, a treasure that will not fall short, in heaven, where no thief approaches, and no moth corrupts.

[[luke-12-34]]
^34^ For where your treasure is, there will your heart be also.

[[luke-12-35]]
^35^ Let your waists be girded, and let lamps be burning in your hands.

[[luke-12-36]]
^36^ And let you yourselves be like men awaiting their lord, when he will return from the wedding; so that, when he arrives and knocks, they may open to him promptly.

[[luke-12-37]]
^37^ Blessed are those servants whom the Lord, when he returns, will find being vigilant. Amen I say to you, that he will gird himself and have them sit down to eat, while he, continuing on, will minister to them.

[[luke-12-38]]
^38^ And if he will return in the second watch, or if in the third watch, and if he will find them to be so: then blessed are those servants.

[[luke-12-39]]
^39^ But know this: that if the father of the family knew at what hour the thief would arrive, he would certainly stand watch, and he would not permit his house to be broken into.

[[luke-12-40]]
^40^ You also must be prepared. For the Son of man will return at an hour that you will not realize.”

[[luke-12-41]]
^41^ Then Peter said to him, “Lord, are you telling this parable to us, or also to everyone?”

[[luke-12-42]]
^42^ So the Lord said: “Who do you think is the faithful and prudent steward, whom his Lord has appointed over his family, in order to give them their measure of wheat in due time?

[[luke-12-43]]
^43^ Blessed is that servant if, when his Lord will return, he will find him acting in this manner.

[[luke-12-44]]
^44^ Truly I say to you, that he will appoint him over all that he possesses.

[[luke-12-45]]
^45^ But if that servant will have said in his heart, ‘My Lord has made a delay in his return,’ and if he has begun to strike the men and women servants, and to eat and drink, and to be inebriated,

[[luke-12-46]]
^46^ then the Lord of that servant will return on a day which he hoped not, and at an hour which he knew not. And he will separate him, and he will place his portion with that of the unfaithful.

[[luke-12-47]]
^47^ And that servant, who knew the will of his Lord, and who did not prepare and did not act according to his will, will be beaten many times over.

[[luke-12-48]]
^48^ Yet he who did not know, and who acted in a way that deserves a beating, will be beaten fewer times. So then, of all to whom much has been given, much will be required. And of those to whom much has been entrusted, even more will be asked.

[[luke-12-49]]
^49^ I have come to cast a fire upon the earth. And what should I desire, except that it may be kindled?

[[luke-12-50]]
^50^ And I have a baptism, with which I am to be baptized. And how I am constrained, even until it may be accomplished!

[[luke-12-51]]
^51^ Do you think that I have come to give peace to the earth? No, I tell you, but division.

[[luke-12-52]]
^52^ For from this time on, there will be five in one house: divided as three against two, and as two against three.

[[luke-12-53]]
^53^ A father will be divided against a son, and a son against his father; a mother against a daughter and a daughter against a mother; a mother-in-law against her daughter-in-law, and a daughter-in-law against her mother-in-law.”

[[luke-12-54]]
^54^ And he also said to the crowds: “When you see a cloud rising from the setting of the sun, immediately you say, ‘A rain cloud is coming.’ And so it does.

[[luke-12-55]]
^55^ And when a south wind is blowing, you say, ‘It will be hot.’ And so it is.

[[luke-12-56]]
^56^ You hypocrites! You discern the face of the heavens, and of the earth, yet how is it that you do not discern this time?

[[luke-12-57]]
^57^ And why do you not, even among yourselves, judge what is just?

[[luke-12-58]]
^58^ So, when you are going with your adversary to the ruler, while you are on the way, make an effort to be freed from him, lest perhaps he may lead you to the judge, and the judge may deliver you to the officer, and the officer may cast you into prison.

[[luke-12-59]]
^59^ I tell you, you will not depart from there, until you have paid the very last coin.”


[[luke-13]]
== Chapter 13

[[luke-13-1]]
^1^ And there were present, at that very time, some who were reporting about the Galileans, whose blood Pilate mixed with their sacrifices.

[[luke-13-2]]
^2^ And responding, he said to them: “Do you think that these Galileans must have sinned more than all other Galileans, because they suffered so much?

[[luke-13-3]]
^3^ No, I tell you. But unless you repent, you will all perish similarly.

[[luke-13-4]]
^4^ And those eighteen upon whom the tower of Siloam fell and killed them, do you think that they also were greater transgressors than all the men living in Jerusalem?

[[luke-13-5]]
^5^ No, I tell you. But if you do not repent, you will all perish similarly.”

[[luke-13-6]]
^6^ And he also told this parable: “A certain man had a fig tree, which was planted in his vineyard. And he came seeking fruit on it, but found none.

[[luke-13-7]]
^7^ Then he said to the cultivator of the vineyard: ‘Behold, for these three years I came seeking fruit on this fig tree, and I have found none. Therefore, cut it down. For why should it even occupy the land?’

[[luke-13-8]]
^8^ But in response, he said to him: ‘Lord, let it be for this year also, during which time I will dig around it and add fertilizer.

[[luke-13-9]]
^9^ And, indeed, it should bear fruit. But if not, in the future, you shall cut it down.’ ”

[[luke-13-10]]
^10^ Now he was teaching in their synagogue on the Sabbaths.

[[luke-13-11]]
^11^ And behold, there was a woman who had a spirit of infirmity for eighteen years. And she was bent over; and she was unable to look upwards at all.

[[luke-13-12]]
^12^ And when Jesus saw her, he called her to himself, and he said to her, “Woman, you are released from your infirmity.”

[[luke-13-13]]
^13^ And he laid his hands upon her, and immediately she was straightened, and she glorified God.

[[luke-13-14]]
^14^ Then, as a result, the ruler of the synagogue became angry that Jesus had cured on the Sabbath, and he said to the crowd: “There are six days on which you ought to work. Therefore, come and be cured on those, and not on the day of the Sabbath.”

[[luke-13-15]]
^15^ Then the Lord said to him in response: “You hypocrites! Does not each one of you, on the Sabbath, release his ox or donkey from the stall, and lead it to water?

[[luke-13-16]]
^16^ So then, should not this daughter of Abraham, whom Satan has bound for lo these eighteen years, be released from this restraint on the day of the Sabbath?”

[[luke-13-17]]
^17^ And as he was saying these things, all his adversaries were ashamed. And all the people rejoiced in everything that was being done gloriously by him.

[[luke-13-18]]
^18^ And so he said: “To what is the kingdom of God similar, and to what figure shall I compare it?

[[luke-13-19]]
^19^ It is like a grain of mustard seed, which a man took and cast into his garden. And it grew, and it became a great tree, and the birds of the air rested in its branches.”

[[luke-13-20]]
^20^ And again, he said: “To what figure shall I compare the kingdom of God?

[[luke-13-21]]
^21^ It is like leaven, which a woman took and hid in three measures of fine wheat flour, until it was entirely leavened.”

[[luke-13-22]]
^22^ And he was traveling through the cities and towns, teaching and making his way to Jerusalem.

[[luke-13-23]]
^23^ And someone said to him, “Lord, are they few who are saved?” But he said to them:

[[luke-13-24]]
^24^ “Strive to enter through the narrow gate. For many, I tell you, will seek to enter and not be able.

[[luke-13-25]]
^25^ Then, when the father of the family will have entered and shut the door, you will begin to stand outside and to knock at the door, saying, ‘Lord, open to us.’ And in response, he will say to you, ‘I do not know where you are from.’

[[luke-13-26]]
^26^ Then you will begin to say, ‘We ate and drank in your presence, and you taught in our streets.’

[[luke-13-27]]
^27^ And he will say to you: ‘I do not know where you are from. Depart from me, all you workers of iniquity!’

[[luke-13-28]]
^28^ In that place, there will be weeping and gnashing of teeth, when you see Abraham, and Isaac, and Jacob, and all the prophets, in the kingdom of God, yet you yourselves are expelled outside.

[[luke-13-29]]
^29^ And they will arrive from the East, and the West, and the North, and the South; and they will recline at table in the kingdom of God.

[[luke-13-30]]
^30^ And behold, those who are last will be first, and those who are first will be last.”

[[luke-13-31]]
^31^ On the same day, some of the Pharisees approached, saying to him: “Depart, and go away from here. For Herod wishes to kill you.”

[[luke-13-32]]
^32^ And he said to them: “Go and tell that fox: ‘Behold, I cast out demons and accomplish healings, today and tomorrow. And on the third day I reach the end.’

[[luke-13-33]]
^33^ Yet truly, it is necessary for me to walk today and tomorrow and the following day. For it does not fall to a prophet to perish beyond Jerusalem.

[[luke-13-34]]
^34^ Jerusalem, Jerusalem! You kill the prophets, and you stone those who are sent to you. Daily, I wanted to gather together your children, in the manner of a bird with her nest under her wings, but you were not willing!

[[luke-13-35]]
^35^ Behold, your house will be left desolate for you. But I say to you, that you shall not see me, until it happens that you say: ‘Blessed is he who has arrived in the name of the Lord.’ ”


[[luke-14]]
== Chapter 14

[[luke-14-1]]
^1^ And it happened that, when Jesus entered the house of a certain leader of the Pharisees on the Sabbath to eat bread, they were observing him.

[[luke-14-2]]
^2^ And behold, a certain man before him was afflicted with edema.

[[luke-14-3]]
^3^ And responding, Jesus spoke to the experts in the law and to the Pharisees, saying, “Is it lawful to cure on the Sabbath?”

[[luke-14-4]]
^4^ But they kept silent. Yet truly, taking hold of him, he healed him and sent him away.

[[luke-14-5]]
^5^ And responding to them, he said, “Which of you will have a donkey or an ox fall into a pit, and will not promptly pull him out, on the day of the Sabbath?”

[[luke-14-6]]
^6^ And they were unable to respond to him about these things.

[[luke-14-7]]
^7^ Then he also told a parable, to those who were invited, noticing how they chose the first seats at the table, saying to them:

[[luke-14-8]]
^8^ “When you are invited to a wedding, do not sit down in the first place, lest perhaps someone more honored than yourself may have been invited by him.

[[luke-14-9]]
^9^ And then he who called both you and him, approaching, may say to you, ‘Give this place to him.’ And then you would begin, with shame, to take the last place.

[[luke-14-10]]
^10^ But when you are invited, go, sit down in the lowest place, so that, when he who invited you arrives, he may say to you, ‘Friend, go up higher.’ Then you will have glory in the sight of those who sit at table together with you.

[[luke-14-11]]
^11^ For everyone who exalts himself shall be humbled, and whoever humbles himself shall be exalted.”

[[luke-14-12]]
^12^ Then he also said to the one who had invited him: “When you prepare a lunch or dinner, do not choose to call your friends, or your brothers, or your relatives, or your wealthy neighbors, lest perhaps they might then invite you in return and repayment would made to you.

[[luke-14-13]]
^13^ But when you prepare a feast, call the poor, the disabled, the lame, and the blind.

[[luke-14-14]]
^14^ And you will be blessed because they do not have a way to repay you. So then, your recompense will be in the resurrection of the just.”

[[luke-14-15]]
^15^ When someone sitting at table with him had heard these things, he said to him, “Blessed is he who will eat bread in the kingdom of God.”

[[luke-14-16]]
^16^ So he said to him: “A certain man prepared a great feast, and he invited many.

[[luke-14-17]]
^17^ And he sent his servant, at the hour of the feast, to tell the invited to come; for now everything was ready.

[[luke-14-18]]
^18^ And at once they all began to make excuses. The first said to him: ‘I bought a farm, and I need to go out and see it. I ask you to excuse me.’

[[luke-14-19]]
^19^ And another said: ‘I bought five yoke of oxen, and I am going to examine them. I ask you to excuse me.’

[[luke-14-20]]
^20^ And another said, ‘I have taken a wife, and therefore I am not able to go.’

[[luke-14-21]]
^21^ And returning, the servant reported these things to his lord. Then the father of the family, becoming angry, said to his servant: ‘Go out quickly into the streets and neighborhoods of the city. And lead here the poor, and the disabled, and the blind, and the lame.’

[[luke-14-22]]
^22^ And the servant said: ‘It has been done, just as you ordered, lord, and there is still room.’

[[luke-14-23]]
^23^ And the lord said to the servant: ‘Go out to the highways and hedges, and compel them to enter, so that my house may be filled.

[[luke-14-24]]
^24^ For I tell you, that none of those men who were invited will taste of my feast.’ ”

[[luke-14-25]]
^25^ Now great crowds traveled with him. And turning around, he said to them:

[[luke-14-26]]
^26^ “If anyone comes to me, and does not hate his father, and mother, and wife, and children, and brothers, and sisters, and yes, even his own life, he is not able to be my disciple.

[[luke-14-27]]
^27^ And whoever does not bear his cross and come after me, is not able to be my disciple.

[[luke-14-28]]
^28^ For who among you, wanting to build a tower, would not first sit down and determine the costs that are required, to see if he has the means to complete it?

[[luke-14-29]]
^29^ Otherwise, after he will have laid the foundation and not been able to finish it, everyone who sees it may begin to mock him,

[[luke-14-30]]
^30^ saying: ‘This man began to build what he was not able to finish.’

[[luke-14-31]]
^31^ Or, what king, advancing to engage in war against another king, would not first sit down and consider whether he may be able, with ten thousand, to meet one who comes against him with twenty thousand?

[[luke-14-32]]
^32^ If not, then while the other is still far away, sending a delegation, he would ask him for terms of peace.

[[luke-14-33]]
^33^ Therefore, every one of you who does not renounce all that he possesses is not able to be my disciple.

[[luke-14-34]]
^34^ Salt is good. But if the salt has lost its flavor, with what will it be seasoned?

[[luke-14-35]]
^35^ It is useful neither in soil, nor in manure, so instead, it shall be thrown away. Whoever has ears to hear, let him hear.”


[[luke-15]]
== Chapter 15

[[luke-15-1]]
^1^ Now tax collectors and sinners were drawing near to him, so that they might listen to him.

[[luke-15-2]]
^2^ And the Pharisees and the scribes murmured, saying, “This one accepts sinners and eats with them.”

[[luke-15-3]]
^3^ And he told this parable to them, saying:

[[luke-15-4]]
^4^ “What man among you, who has one hundred sheep, and if he will have lost one of them, would not leave the ninety-nine in the desert and go after the one whom he had lost, until he finds it?

[[luke-15-5]]
^5^ And when he has found it, he places it on his shoulders, rejoicing.

[[luke-15-6]]
^6^ And returning home, he calls together his friends and neighbors, saying to them: ‘Congratulate me! For I have found my sheep, which had been lost.’

[[luke-15-7]]
^7^ I say to you, that there will be so much more joy in heaven over one sinner repenting, than over the ninety-nine just, who do not need to repent.

[[luke-15-8]]
^8^ Or what woman, having ten drachmas, if she will have lost one drachma, would not light a candle, and sweep the house, and diligently search until she finds it?

[[luke-15-9]]
^9^ And when she has found it, she calls together her friends and neighbors, saying: ‘Rejoice with me! For I have found the drachma, which I had lost.’

[[luke-15-10]]
^10^ So I say to you, there will be joy before the Angels of God over even one sinner who is repentant.”

[[luke-15-11]]
^11^ And he said: “A certain man had two sons.

[[luke-15-12]]
^12^ And the younger of them said to the father, ‘Father, give me the portion of your estate which would go to me.’ And he divided the estate between them.

[[luke-15-13]]
^13^ And after not many days, the younger son, gathering it all together, set out on a long journey to a distant region. And there, he dissipated his substance, living in luxury.

[[luke-15-14]]
^14^ And after he had consumed it all, a great famine occurred in that region, and he began to be in need.

[[luke-15-15]]
^15^ And he went and attached himself to one of the citizens of that region. And he sent him to his farm, in order to feed the swine.

[[luke-15-16]]
^16^ And he wanted to fill his belly with the scraps that the swine ate. But no one would give it to him.

[[luke-15-17]]
^17^ And returning to his senses, he said: ‘How many hired hands in my father’s house have abundant bread, while I perish here in famine!

[[luke-15-18]]
^18^ I shall rise up and go to my father, and I will say to him: Father, I have sinned against heaven and before you.

[[luke-15-19]]
^19^ I am not worthy to be called your son. Make me one of your hired hands.’

[[luke-15-20]]
^20^ And rising up, he went to his father. But while he was still at a distance, his father saw him, and he was moved with compassion, and running to him, he fell upon his neck and kissed him.

[[luke-15-21]]
^21^ And the son said to him: ‘Father, I have sinned against heaven and before you. Now I am not worthy to be called your son.’

[[luke-15-22]]
^22^ But the father said to his servants: ‘Quickly! Bring out the best robe, and clothe him with it. And put a ring on his hand and shoes on his feet.

[[luke-15-23]]
^23^ And bring the fatted calf here, and kill it. And let us eat and hold a feast.

[[luke-15-24]]
^24^ For this son of mine was dead, and has revived; he was lost, and is found.’ And they began to feast.

[[luke-15-25]]
^25^ But his elder son was in the field. And when he returned and drew near to the house, he heard music and dancing.

[[luke-15-26]]
^26^ And he called one of the servants, and he questioned him as to what these things meant.

[[luke-15-27]]
^27^ And he said to him: ‘Your brother has returned, and your father has killed the fatted calf, because he has received him safely.’

[[luke-15-28]]
^28^ Then he became indignant, and he was unwilling to enter. Therefore, his father, going out, began to plead with him.

[[luke-15-29]]
^29^ And in response, he said to his father: ‘Behold, I have been serving you for so many years. And I have never transgressed your commandment. And yet, you have never given me even a young goat, so that I might feast with my friends.

[[luke-15-30]]
^30^ Yet after this son of yours returned, who has devoured his substance with loose women, you have killed the fatted calf for him.’

[[luke-15-31]]
^31^ But he said to him: ‘Son, you are with me always, and all that I have is yours.

[[luke-15-32]]
^32^ But it was necessary to feast and to rejoice. For this brother of yours was dead, and has revived; he was lost, and is found.’ ”


[[luke-16]]
== Chapter 16

[[luke-16-1]]
^1^ And he also said to his disciples: “A certain man was wealthy, and he had a steward of his estate. And this man was accused to him of having dissipated his goods.

[[luke-16-2]]
^2^ And he called him and said to him: ‘What is this that I hear about you? Give an account of your stewardship. For you can no longer be my steward.’

[[luke-16-3]]
^3^ And the steward said within himself: ‘What shall I do? For my lord is taking the stewardship away from me. I am not strong enough to dig. I am too ashamed to beg.

[[luke-16-4]]
^4^ I know what I will do so that, when I have been removed from the stewardship, they may receive me into their houses.’

[[luke-16-5]]
^5^ And so, calling together each one of his lord’s debtors, he said to the first, ‘How much do you owe my lord?’

[[luke-16-6]]
^6^ So he said, ‘One hundred jars of oil.’ And he said to him, ‘Take your invoice, and quickly, sit down and write fifty.’

[[luke-16-7]]
^7^ Next, he said to another, ‘In truth, how much do you owe?’ And he said, ‘One hundred measures of wheat.’ He said to him, ‘Take your record books, and write eighty.’

[[luke-16-8]]
^8^ And the lord praised the iniquitous steward, in that he had acted prudently. For the sons of this age are more prudent with their generation than are the sons of light.

[[luke-16-9]]
^9^ And so I say to you, make friends for yourself using iniquitous mammon, so that, when you will have passed away, they may receive you into the eternal tabernacles.

[[luke-16-10]]
^10^ Whoever is faithful in what is least, is also faithful in what is greater. And whoever is unjust in what is small, is also unjust in what is greater.

[[luke-16-11]]
^11^ So then, if you have not been faithful with iniquitous mammon, who will trust you with what is true?

[[luke-16-12]]
^12^ And if you have not been faithful with what belongs to another, who will give you what is yours?

[[luke-16-13]]
^13^ No servant is able to serve two lords. For either he will hate the one and love the other, or he will cling to the one and despise the other. You cannot serve God and mammon.”

[[luke-16-14]]
^14^ But the Pharisees, who were greedy, were listening to all these things. And they ridiculed him.

[[luke-16-15]]
^15^ And he said to them: “You are the ones who justify yourselves in the sight of men. But God knows your hearts. For what is lifted up by men is an abomination in the sight of God.

[[luke-16-16]]
^16^ The law and the prophets were until John. Since then, the kingdom of God is being evangelized, and everyone acts with violence toward it.

[[luke-16-17]]
^17^ But it is easier for heaven and earth to pass away, than for one dot of the law to fall away.

[[luke-16-18]]
^18^ Everyone who divorces his wife and marries another commits adultery. And whoever marries her who has been divorced by her husband commits adultery.

[[luke-16-19]]
^19^ A certain man was wealthy, and he was clothed in purple and in fine linen. And he feasted splendidly every day.

[[luke-16-20]]
^20^ And there was a certain beggar, named Lazarus, who lay at his gate, covered with sores,

[[luke-16-21]]
^21^ wanting to be filled with the crumbs which were falling from the wealthy man’s table. But no one gave it to him. And even the dogs came and licked his sores.

[[luke-16-22]]
^22^ Then it happened that the beggar died, and he was carried by the Angels into the bosom of Abraham. Now the wealthy man also died, and he was entombed in Hell.

[[luke-16-23]]
^23^ Then lifting up his eyes, while he was in torments, he saw Abraham far away, and Lazarus in his bosom.

[[luke-16-24]]
^24^ And crying out, he said: ‘Father Abraham, take pity on me and send Lazarus, so that he may dip the tip of his finger in water to refresh my tongue. For I am tortured in this fire.’

[[luke-16-25]]
^25^ And Abraham said to him: ‘Son, recall that you received good things in your life, and in comparison, Lazarus received bad things. But now he is consoled, and truly you are tormented.

[[luke-16-26]]
^26^ And besides all this, between us and you a great chasm has been established, so that those who might want to cross from here to you are not able, nor can someone cross from there to here.’

[[luke-16-27]]
^27^ And he said: ‘Then, father, I beg you to send him to my father’s house, for I have five brothers,

[[luke-16-28]]
^28^ so that he may testify to them, lest they also come into this place of torments.’

[[luke-16-29]]
^29^ And Abraham said to him: ‘They have Moses and the prophets. Let them listen to them.’

[[luke-16-30]]
^30^ So he said: ‘No, father Abraham. But if someone were to go to them from the dead, they would repent.’

[[luke-16-31]]
^31^ But he said to him: ‘If they will not listen to Moses and the prophets, neither will they believe even if someone has resurrected from the dead.’ ”


[[luke-17]]
== Chapter 17

[[luke-17-1]]
^1^ And he said to his disciples: “It is impossible for scandals not to occur. But woe to him through whom they come!

[[luke-17-2]]
^2^ It would be better for him if a millstone were placed around his neck and he were thrown into the sea, than to lead astray one of these little ones.

[[luke-17-3]]
^3^ Be attentive to yourselves. If your brother has sinned against you, correct him. And if he has repented, forgive him.

[[luke-17-4]]
^4^ And if he has sinned against you seven times a day, and seven times a day has turned back to you, saying, ‘I am sorry,’ then forgive him.”

[[luke-17-5]]
^5^ And the Apostles said to the Lord, “Increase our faith.”

[[luke-17-6]]
^6^ But the Lord said: “If you have faith like a grain of mustard seed, you may say to this mulberry tree, ‘Be uprooted, and be transplanted into the sea.’ And it would obey you.

[[luke-17-7]]
^7^ But which of you, having a servant plowing or feeding cattle, would say to him, as he was returning from the field, ‘Come in immediately; sit down to eat,’

[[luke-17-8]]
^8^ and would not say to him: ‘Prepare my dinner; gird yourself and minister to me, while I eat and drink; and after these things, you shall eat and drink?’

[[luke-17-9]]
^9^ Would he be grateful to that servant, for doing what he commanded him to do?

[[luke-17-10]]
^10^ I think not. So too, when you have done all these things that have been taught to you, you should say: ‘We are useless servants. We have done what we should have done.’ ”

[[luke-17-11]]
^11^ And it happened that, while he was traveling to Jerusalem, he passed through the midst of Samaria and Galilee.

[[luke-17-12]]
^12^ And as he was entering a certain town, ten leprous men met him, and they stood at a distance.

[[luke-17-13]]
^13^ And they lifted up their voice, saying, “Jesus, Teacher, take pity on us.”

[[luke-17-14]]
^14^ And when he saw them, he said, “Go, show yourselves to the priests.” And it happened that, as they were going, they were cleansed.

[[luke-17-15]]
^15^ And one of them, when he saw that he was cleansed, returned, magnifying God with a loud voice.

[[luke-17-16]]
^16^ And he fell face down before his feet, giving thanks. And this one was a Samaritan.

[[luke-17-17]]
^17^ And in response, Jesus said: “Were not ten made clean? And so where are the nine?

[[luke-17-18]]
^18^ Was no one found who would return and give glory to God, except this foreigner?”

[[luke-17-19]]
^19^ And he said to him: “Rise up, go forth. For your faith has saved you.”

[[luke-17-20]]
^20^ Then he was questioned by the Pharisees: “When does the kingdom of God arrive?” And in response, he said to them: “The kingdom of God arrives unobserved.

[[luke-17-21]]
^21^ And so, they will not say, ‘Behold, it is here,’ or ‘Behold, it is there.’ For behold, the kingdom of God is within you.”

[[luke-17-22]]
^22^ And he said to his disciples: “The time will come when you will desire to see one day of the Son of man, and you will not see it.

[[luke-17-23]]
^23^ And they will say to you, ‘Behold, he is here,’ and ‘Behold, he is there.’ Do not choose to go out, and do not follow them.

[[luke-17-24]]
^24^ For just as lightning flashes from under heaven and shines to whatever is under heaven, so also will the Son of man be in his day.

[[luke-17-25]]
^25^ But first he must suffer many things and be rejected by this generation.

[[luke-17-26]]
^26^ And just as it happened in the days of Noah, so also will it be in the days of the Son of man.

[[luke-17-27]]
^27^ They were eating and drinking; they were taking wives and being given in marriage, even until the day that Noah entered the ark. And the flood came and destroyed them all.

[[luke-17-28]]
^28^ It shall be similar to what happened in the days of Lot. They were eating and drinking; they were buying and selling; they were planting and building.

[[luke-17-29]]
^29^ Then, on the day that Lot departed from Sodom, it rained fire and brimstone from heaven, and it destroyed them all.

[[luke-17-30]]
^30^ According to these things, so shall it be in the day when the Son of man will be revealed.

[[luke-17-31]]
^31^ In that hour, whoever will be on the rooftop, with his goods in the house, let him not descend to take them. And whoever will be in the field, similarly, let him not turn back.

[[luke-17-32]]
^32^ Remember Lot’s wife.

[[luke-17-33]]
^33^ Whoever has sought to save his life, will lose it; and whoever has lost it, will bring it back to life.

[[luke-17-34]]
^34^ I say to you, in that night, there will be two in one bed. One will be taken up, and the other will be left behind.

[[luke-17-35]]
^35^ Two will be at the grindstone together. One will be taken up, and the other will be left behind. Two will be in the field. One will be taken up, and the other will be left behind.”

[[luke-17-36]]
^36^ Responding, they said to him, “Where, Lord?”

[[luke-17-37]]
^37^ And he said to them, “Wherever the body will be, in that place also, the eagles shall be gathered together.”


[[luke-18]]
== Chapter 18

[[luke-18-1]]
^1^ Now he also told them a parable, that we should continually pray and not cease,

[[luke-18-2]]
^2^ saying: “There was a certain judge in a certain city, who did not fear God and did not respect man.

[[luke-18-3]]
^3^ But there was a certain widow in that city, and she went to him, saying, ‘Vindicate me from my adversary.’

[[luke-18-4]]
^4^ And he refused to do so for a long time. But afterwards, he said within himself: ‘Even though I do not fear God, nor respect man,

[[luke-18-5]]
^5^ yet because this widow is pestering me, I will vindicate her, lest by returning, she may, in the end, wear me out.’ ”

[[luke-18-6]]
^6^ Then the Lord said: “Listen to what the unjust judge said.

[[luke-18-7]]
^7^ So then, will not God grant the vindication of his elect, who cry out to him day and night? Or will he continue to endure them?

[[luke-18-8]]
^8^ I tell you that he will quickly bring vindication to them. Yet truly, when the Son of man returns, do you think that he will find faith on earth?”

[[luke-18-9]]
^9^ Now about certain persons who consider themselves to be just, while disdaining others, he told also this parable:

[[luke-18-10]]
^10^ “Two men ascended to the temple, in order to pray. One was a Pharisee, and the other was a tax collector.

[[luke-18-11]]
^11^ Standing, the Pharisee prayed within himself in this way: ‘O God, I give thanks to you that I am not like the rest of men: robbers, unjust, adulterers, even as this tax collector chooses to be.

[[luke-18-12]]
^12^ I fast twice between Sabbaths. I give tithes from all that I possess.’

[[luke-18-13]]
^13^ And the tax collector, standing at a distance, was not willing to even lift up his eyes to heaven. But he struck his chest, saying: ‘O God, be merciful to me, a sinner.’

[[luke-18-14]]
^14^ I say to you, this one descended to his house justified, but not the other. For everyone who exalts himself will be humbled; and whoever humbles himself will be exalted.”

[[luke-18-15]]
^15^ And they were bringing little children to him, so that he might touch them. And when the disciples saw this, they rebuked them.

[[luke-18-16]]
^16^ But Jesus, calling them together, said: “Allow the children to come to me, and do not be an obstacle to them. For of such is the kingdom of God.

[[luke-18-17]]
^17^ Amen, I say to you, whoever will not accept the kingdom of God like a child, will not enter into it.”

[[luke-18-18]]
^18^ And a certain leader questioned him, saying: “Good teacher, what should I do to possess eternal life?”

[[luke-18-19]]
^19^ Then Jesus said to him: “Why do you call me good? No one is good except God alone.

[[luke-18-20]]
^20^ You know the commandments: You shall not kill. You shall not commit adultery. You shall not steal. You shall not give false testimony. Honor your father and mother.”

[[luke-18-21]]
^21^ And he said, “I have kept all these things from my youth.”

[[luke-18-22]]
^22^ And when Jesus heard this, he said to him: “One thing is still lacking for you. Sell all the things that you have, and give to the poor. And then you will have treasure in heaven. And come, follow me.”

[[luke-18-23]]
^23^ When he heard this, he became very sorrowful. For he was very rich.

[[luke-18-24]]
^24^ Then Jesus, seeing him brought to sorrow, said: “How difficult it is for those who have money to enter into the kingdom of God!

[[luke-18-25]]
^25^ For it is easier for a camel to pass through the eye of a needle, than for a wealthy man to enter into the kingdom of God.”

[[luke-18-26]]
^26^ And those who were listening to this said, “Then who is able to be saved?”

[[luke-18-27]]
^27^ He said to them, “Things that are impossible with men are possible with God.”

[[luke-18-28]]
^28^ And Peter said, “Behold, we have left everything, and we have followed you.”

[[luke-18-29]]
^29^ And he said to them: “Amen, I say to you, there is no one who has left behind home, or parents, or brothers, or a wife, or children, for the sake of the kingdom of God,

[[luke-18-30]]
^30^ who will not receive much more in this time, and in the age to come eternal life.”

[[luke-18-31]]
^31^ Then Jesus took the twelve aside, and he said to them: “Behold, we are ascending to Jerusalem, and everything shall be completed which was written by the prophets about the Son of man.

[[luke-18-32]]
^32^ For he will be handed over to the Gentiles, and he will be mocked and scourged and spit upon.

[[luke-18-33]]
^33^ And after they have scourged him, they will kill him. And on the third day, he will rise again.”

[[luke-18-34]]
^34^ But they understood none of these things. For this word was concealed from them, and they did not understand the things that were said.

[[luke-18-35]]
^35^ Now it happened that, as he was approaching Jericho, a certain blind man was sitting beside the way, begging.

[[luke-18-36]]
^36^ And when he heard the multitude passing by, he asked what this was.

[[luke-18-37]]
^37^ And they told him that Jesus of Nazareth was passing by.

[[luke-18-38]]
^38^ And he cried out, saying, “Jesus, Son of David, take pity on me!”

[[luke-18-39]]
^39^ And those who were passing by rebuked him, so that he would be silent. Yet truly, he cried out all the more, “Son of David, take pity on me!”

[[luke-18-40]]
^40^ Then Jesus, standing still, ordered him to be brought to him. And when he had drawn near, he questioned him,

[[luke-18-41]]
^41^ saying, “What do you want, that I might do for you?” So he said, “Lord, that I may see.”

[[luke-18-42]]
^42^ And Jesus said to him: “Look around. Your faith has saved you.”

[[luke-18-43]]
^43^ And immediately he saw. And he followed him, magnifying God. And all the people, when they saw this, gave praise to God.


[[luke-19]]
== Chapter 19

[[luke-19-1]]
^1^ And having entered, he walked through Jericho.

[[luke-19-2]]
^2^ And behold, there was a man named Zacchaeus. And he was the leader of the tax collectors, and he was wealthy.

[[luke-19-3]]
^3^ And he sought to see Jesus, to see who he was. But he was unable to do so, because of the crowd, for he was small in stature.

[[luke-19-4]]
^4^ And running ahead, he climbed up a sycamore tree, so that he might see him. For he was to pass near there.

[[luke-19-5]]
^5^ And when he had arrived at the place, Jesus looked up and saw him, and he said to him: “Zacchaeus, hurry down. For today, I should lodge in your house.”

[[luke-19-6]]
^6^ And hurrying, he came down, and he received him joyfully.

[[luke-19-7]]
^7^ And when they all saw this, they murmured, saying that he had turned aside to a sinful man.

[[luke-19-8]]
^8^ But Zacchaeus, standing still, said to the Lord: “Behold, Lord, one half of my goods I give to the poor. And if I have cheated anyone in any matter, I will repay him fourfold.”

[[luke-19-9]]
^9^ Jesus said to him: “Today, salvation has come to this house; because of this, he too is a son of Abraham.

[[luke-19-10]]
^10^ For the Son of man has come to seek and to save what had been lost.”

[[luke-19-11]]
^11^ As they were listening to these things, continuing on, he spoke a parable, because he was nearing Jerusalem, and because they guessed that the kingdom of God might be manifested without delay.

[[luke-19-12]]
^12^ Therefore, he said: “A certain man of nobility traveled to a far away region, to receive for himself a kingdom, and to return.

[[luke-19-13]]
^13^ And calling his ten servants, he gave them ten pounds, and he said to them: ‘Do business until I return.’

[[luke-19-14]]
^14^ But his citizens hated him. And so they sent a delegation after him, saying, ‘We do not want this one to reign over us.’

[[luke-19-15]]
^15^ And it happened that he returned, having received the kingdom. And he ordered the servants, to whom he had given the money, to be called so that he would know how much each one had earned by doing business.

[[luke-19-16]]
^16^ Now the first approached, saying: ‘Lord, your one pound has earned ten pounds.’

[[luke-19-17]]
^17^ And he said to him: ‘Well done, good servant. Since you have been faithful in a small matter, you will hold authority over ten cities.’

[[luke-19-18]]
^18^ And the second came, saying: ‘Lord, your one pound has earned five pounds.’

[[luke-19-19]]
^19^ And he said to him, ‘And so, you shall be over five cities.’

[[luke-19-20]]
^20^ And another approached, saying: ‘Lord, behold your one pound, which I kept stored in a cloth.

[[luke-19-21]]
^21^ For I feared you, because you are an austere man. You take up what you did not lay down, and you reap what you did not sow.’

[[luke-19-22]]
^22^ He said to him: ‘By your own mouth, do I judge you, O wicked servant. You knew that I am an austere man, taking up what I did not lay down, and reaping what I did not sow.

[[luke-19-23]]
^23^ And so, why did you not give my money to the bank, so that, upon my return, I might have withdrawn it with interest?’

[[luke-19-24]]
^24^ And he said to the bystanders, ‘Take the pound away from him, and give it to him who has ten pounds.’

[[luke-19-25]]
^25^ And they said to him, ‘Lord, he has ten pounds.’

[[luke-19-26]]
^26^ So then, I say to you, that to all who have, it shall be given, and he will have in abundance. And from him who does not have, even what he has will be taken from him.

[[luke-19-27]]
^27^ ‘Yet truly, as for those enemies of mine, who did not want me to reign over them, bring them here, and put them to death before me.’ ”

[[luke-19-28]]
^28^ And having said these things, he went ahead, ascending to Jerusalem.

[[luke-19-29]]
^29^ And it happened that, when he had drawn near to Bethphage and Bethania, to the mount which is called Olivet, he sent two of his disciples,

[[luke-19-30]]
^30^ saying: “Go into the town which is opposite you. Upon entering it, you will find the colt of a donkey, tied, on which no man has ever sat. Untie it, and lead it here.

[[luke-19-31]]
^31^ And if anyone will ask you, ‘Why are you untying it?’ you shall say this to him: ‘Because the Lord has requested its service.’ ”

[[luke-19-32]]
^32^ And those who were sent went out, and they found the colt standing, just as he told them.

[[luke-19-33]]
^33^ Then, as they were untying the colt, its owners said to them, “Why are you untying the colt?”

[[luke-19-34]]
^34^ So they said, “Because the Lord has need of it.”

[[luke-19-35]]
^35^ And they led it to Jesus. And casting their garments on the colt, they helped Jesus onto it.

[[luke-19-36]]
^36^ Then, as he was traveling, they were laying down their garments along the way.

[[luke-19-37]]
^37^ And when he was now drawing near to the descent of Mount Olivet, the entire crowd of his disciples began to praise God joyfully, with a loud voice, over all the powerful works which they had seen,

[[luke-19-38]]
^38^ saying: “Blessed is the king who has arrived in the name of the Lord! Peace in heaven and glory on high!”

[[luke-19-39]]
^39^ And certain Pharisees within the crowd said to him, “Teacher, rebuke your disciples.”

[[luke-19-40]]
^40^ And he said to them, “I tell you, that if these will keep silent, the stones themselves will cry out.”

[[luke-19-41]]
^41^ And when he drew near, seeing the city, he wept over it, saying:

[[luke-19-42]]
^42^ “If only you had known, indeed even in this your day, which things are for your peace. But now they are hidden from your eyes.

[[luke-19-43]]
^43^ For the days will overtake you. And your enemies will encircle you with a valley. And they will surround you and hem you in on every side.

[[luke-19-44]]
^44^ And they will knock you down to the ground, with your sons who are in you. And they will not leave stone upon stone within you, because you did not recognize the time of your visitation.”

[[luke-19-45]]
^45^ And entering into the temple, he began to cast out those who sold in it, and those who bought,

[[luke-19-46]]
^46^ saying to them: “It is written: ‘My house is a house of prayer.’ But you have made it into a den of robbers.”

[[luke-19-47]]
^47^ And he was teaching in the temple daily. And the leaders of the priests, and the scribes, and the leaders of the people were seeking to destroy him.

[[luke-19-48]]
^48^ But they could not find what to do to him. For all the people were listening to him attentively.


[[luke-20]]
== Chapter 20

[[luke-20-1]]
^1^ And it happened that, on one of the days when he was teaching the people in the temple and preaching the Gospel, the leaders of the priests, and the scribes, gathered together with the elders,

[[luke-20-2]]
^2^ and they spoke to him, saying: “Tell us, by what authority do you do these things? Or, who is it that has given you this authority?”

[[luke-20-3]]
^3^ And in response, Jesus said to them: “I will also question you about one word. Respond to me:

[[luke-20-4]]
^4^ The baptism of John, was it from heaven, or of men?”

[[luke-20-5]]
^5^ So they discussed it among themselves, saying: “If we say, ‘From heaven,’ he will say, ‘Then why did you not believe him?’

[[luke-20-6]]
^6^ But if we say, ‘Of men,’ the whole people will stone us. For they are certain that John was a prophet.”

[[luke-20-7]]
^7^ And so they responded that they did not know where it was from.

[[luke-20-8]]
^8^ And Jesus said to them, “Neither will I tell you by what authority I do these things.”

[[luke-20-9]]
^9^ Then he began to tell the people this parable: “A man planted a vineyard, and he loaned it to settlers, and he was on a sojourn for a long time.

[[luke-20-10]]
^10^ And in due time, he sent a servant to the farmers, so that they would give to him from the fruit of the vineyard. And they beat him and drove him away, empty-handed.

[[luke-20-11]]
^11^ And he continued to send another servant. But beating him and treating him with contempt, they likewise sent him away, empty-handed.

[[luke-20-12]]
^12^ And he continued to send a third. And wounding him also, they drove him away.

[[luke-20-13]]
^13^ Then the lord of the vineyard said: ‘What shall I do? I will send my beloved son. Perhaps when they have seen him, they will respect him.’

[[luke-20-14]]
^14^ And when the settlers had seen him, they discussed it among themselves, saying: ‘This one is the heir. Let us kill him, so that the inheritance will be ours.’

[[luke-20-15]]
^15^ And forcing him outside of the vineyard, they killed him. What, then, will the lord of the vineyard do to them?”

[[luke-20-16]]
^16^ “He will come and destroy those settlers, and he will give the vineyard to others.” And upon hearing this, they said to him, “Let it not be.”

[[luke-20-17]]
^17^ Then, gazing at them, he said: “Then what does this mean, which is written: ‘The stone which the builders have rejected, the same has become the head of the corner?’

[[luke-20-18]]
^18^ Everyone who falls on that stone will be shattered. And anyone upon whom it falls will be crushed.”

[[luke-20-19]]
^19^ And the leaders of the priests, and the scribes, were seeking to lay hands on him in that same hour, but they feared the people. For they realized that he had spoken this parable about them.

[[luke-20-20]]
^20^ And being attentive, they sent traitors, who would pretend that they were just, so that they might catch him in his words and then hand him over to the power and authority of the procurator.

[[luke-20-21]]
^21^ And they questioned him, saying: “Teacher, we know that you speak and teach correctly, and that you do not consider anyone’s status, but you teach the way of God in truth.

[[luke-20-22]]
^22^ Is it lawful for us to pay the tribute to Caesar, or not?”

[[luke-20-23]]
^23^ But realizing their deceitfulness, he said to them: “Why do you test me?

[[luke-20-24]]
^24^ Show me a denarius. Whose image and inscription does it have?” In response, they said to him, “Caesar’s.”

[[luke-20-25]]
^25^ And so, he said to them: “Then repay the things that are Caesar’s, to Caesar, and the things that are God’s, to God.”

[[luke-20-26]]
^26^ And they were not able to contradict his word before the people. And being amazed at his answer, they were silent.

[[luke-20-27]]
^27^ Now some of the Sadducees, who deny that there is a resurrection, approached him. And they questioned him,

[[luke-20-28]]
^28^ saying: “Teacher, Moses wrote for us: If any man’s brother will have died, having a wife, and if he does not have any children, then his brother should take her as his wife, and he should raise up offspring for his brother.

[[luke-20-29]]
^29^ And so there were seven brothers. And the first took a wife, and he died without sons.

[[luke-20-30]]
^30^ And the next one married her, and he also died without a son.

[[luke-20-31]]
^31^ And the third married her, and similarly all seven, and none of them left behind any offspring, and they each died.

[[luke-20-32]]
^32^ Last of all, the woman also died.

[[luke-20-33]]
^33^ In the resurrection, then, whose wife will she be? For certainly all seven had her as a wife.”

[[luke-20-34]]
^34^ And so, Jesus said to them: “The children of this age marry and are given in marriage.

[[luke-20-35]]
^35^ Yet truly, those who shall be held worthy of that age, and of the resurrection from the dead, will neither be married, nor take wives.

[[luke-20-36]]
^36^ For they can no longer die. For they are equal to the Angels, and they are children of God, since they are children of the resurrection.

[[luke-20-37]]
^37^ For in truth, the dead do rise again, as Moses also showed beside the bush, when he called the Lord: ‘The God of Abraham, and the God of Isaac, and the God of Jacob.’

[[luke-20-38]]
^38^ And so he is not the God of the dead, but of the living. For all are alive to him.”

[[luke-20-39]]
^39^ Then some of the scribes, in response, said to him, “Teacher, you have spoken well.”

[[luke-20-40]]
^40^ And they no longer dared to question him about anything.

[[luke-20-41]]
^41^ But he said to them: “How can they say that the Christ is the son of David?

[[luke-20-42]]
^42^ Even David himself says, in the book of Psalms: ‘The Lord said to my Lord, sit at my right hand,

[[luke-20-43]]
^43^ until I set your enemies as your footstool.’

[[luke-20-44]]
^44^ Therefore, David calls him Lord. So how can he be his son?”

[[luke-20-45]]
^45^ Now in the hearing of all the people, he said to his disciples:

[[luke-20-46]]
^46^ “Be cautious of the scribes, who choose to walk in long robes, and who love greetings in the marketplace, and the first chairs in the synagogues, and the first places at table during feasts,

[[luke-20-47]]
^47^ who devour the houses of widows, feigning long prayers. These will receive the greater damnation.”


[[luke-21]]
== Chapter 21

[[luke-21-1]]
^1^ And looking around, he saw the wealthy putting their donations into the offertory.

[[luke-21-2]]
^2^ Then he also saw a certain widow, a pauper, putting in two small brass coins.

[[luke-21-3]]
^3^ And he said: “Truly, I say to you, that this poor widow has put in more than all the others.

[[luke-21-4]]
^4^ For all these, out of their abundance, have added to the gifts for God. But she, out of what she needed, has put in all that she had to live on.”

[[luke-21-5]]
^5^ And when some of them were saying, about the temple, that it was adorned with excellent stones and gifts, he said,

[[luke-21-6]]
^6^ “These things that you see, the days will arrive when there will not be left behind stone upon stone, which is not thrown down.”

[[luke-21-7]]
^7^ Then they questioned him, saying: “Teacher, when will these things be? And what will be the sign when these things will happen?”

[[luke-21-8]]
^8^ And he said: “Be cautious, lest you be seduced. For many will come in my name, saying: ‘For I am he,’ and, ‘The time has drawn near.’ And so, do not choose to go after them.

[[luke-21-9]]
^9^ And when you will have heard of battles and seditions, do not be terrified. These things must happen first. But the end is not so soon.”

[[luke-21-10]]
^10^ Then he said to them: “People will rise up against people, and kingdom against kingdom.

[[luke-21-11]]
^11^ And there will be great earthquakes in various places, and pestilences, and famines, and terrors from heaven; and there will be great signs.

[[luke-21-12]]
^12^ But before all these things, they will lay their hands on you and persecute you, handing you over to synagogues and into custody, dragging you before kings and governors, because of my name.

[[luke-21-13]]
^13^ And this will be an opportunity for you to give testimony.

[[luke-21-14]]
^14^ Therefore, set this in your hearts: that you should not consider in advance how you might respond.

[[luke-21-15]]
^15^ For I will give to you a mouth and wisdom, which all your adversaries will not be able to resist or contradict.

[[luke-21-16]]
^16^ And you will be handed over by your parents, and brothers, and relatives, and friends. And they will bring about the death of some of you.

[[luke-21-17]]
^17^ And you will be hated by all because of my name.

[[luke-21-18]]
^18^ And yet, not a hair of your head will perish.

[[luke-21-19]]
^19^ By your patience, you shall possess your souls.

[[luke-21-20]]
^20^ Then, when you will have seen Jerusalem encircled by an army, know then that its desolation has drawn near.

[[luke-21-21]]
^21^ Then let those who are in Judea flee to the mountains, and those who are in its midst withdraw, and those who are in the countryside not enter into it.

[[luke-21-22]]
^22^ For these are the days of retribution, so that all things may be fulfilled, which have been written.

[[luke-21-23]]
^23^ Then woe to those who are pregnant or nursing in those days. For there will be great distress upon the land and great wrath upon this people.

[[luke-21-24]]
^24^ And they will fall by the edge of the sword. And they will be led away as captives into all nations. And Jerusalem will be trampled by the Gentiles, until the times of the nations are fulfilled.

[[luke-21-25]]
^25^ And there will be signs in the sun and the moon and the stars. And there will be, on earth, distress among the Gentiles, out of confusion at the roaring of the sea and of the waves:

[[luke-21-26]]
^26^ men withering away out of fear and out of apprehension over the things that will overwhelm the whole world. For the powers of the heavens will be moved.

[[luke-21-27]]
^27^ And then they will see the Son of man coming on a cloud, with great power and majesty.

[[luke-21-28]]
^28^ But when these things begin to happen, lift up your heads and look around you, because your redemption draws near.”

[[luke-21-29]]
^29^ And he told them a comparison: “Take notice of the fig tree and of all the trees.

[[luke-21-30]]
^30^ When presently they produce fruit from themselves, you know that summer is near.

[[luke-21-31]]
^31^ So you also, when you will have seen these things happen, know that the kingdom of God is near.

[[luke-21-32]]
^32^ Amen I say to you, this lineage shall not pass away, until all these things happen.

[[luke-21-33]]
^33^ Heaven and earth shall pass away. But my words shall not pass away.

[[luke-21-34]]
^34^ But be attentive to yourselves, lest perhaps your hearts may be weighed down by self-indulgence and inebriation and the cares of this life. And then that day may overwhelm you suddenly.

[[luke-21-35]]
^35^ For like a snare it will overwhelm all those who sit upon the face of the entire earth.

[[luke-21-36]]
^36^ And so, be vigilant, praying at all times, so that you may be held worthy to escape from all these things, which are in the future, and to stand before the Son of man.”

[[luke-21-37]]
^37^ Now in the daytime, he was teaching in the temple. But truly, departing in the evening, he lodged on the mount that is called Olivet.

[[luke-21-38]]
^38^ And all the people arrived in the morning to listen to him in the temple.


[[luke-22]]
== Chapter 22

[[luke-22-1]]
^1^ Now the days of the Feast of Unleavened Bread, which is called Passover, were approaching.

[[luke-22-2]]
^2^ And the leaders of the priests, and the scribes, were seeking a way to execute Jesus. Yet truly, they were afraid of the people.

[[luke-22-3]]
^3^ Then Satan entered into Judas, who was surnamed Iscariot, one of the twelve.

[[luke-22-4]]
^4^ And he went out and was speaking with the leaders of the priests, and the magistrates, as to how he might hand him over to them.

[[luke-22-5]]
^5^ And they were glad, and so they made an agreement to give him money.

[[luke-22-6]]
^6^ And he made a promise. And he was seeking an opportunity to hand him over, apart from the crowds.

[[luke-22-7]]
^7^ Then the day of Unleavened Bread arrived, on which it was necessary to kill the Pascal lamb.

[[luke-22-8]]
^8^ And he sent Peter and John, saying, “Go out, and prepare the Passover for us, so that we may eat.”

[[luke-22-9]]
^9^ But they said, “Where do you want us to prepare it?”

[[luke-22-10]]
^10^ And he said to them: “Behold, as you are entering into the city, a certain man will meet you, carrying a pitcher of water. Follow him to the house into which he enters.

[[luke-22-11]]
^11^ And you shall say to the father of the household: ‘The Teacher says to you: Where is the guestroom, where I may eat the Passover with my disciples?’

[[luke-22-12]]
^12^ And he will show you a large cenacle, fully furnished. And so, prepare it there.”

[[luke-22-13]]
^13^ And going out, they found it to be just as he had told them. And they prepared the Passover.

[[luke-22-14]]
^14^ And when the hour had arrived, he sat down at table, and the twelve Apostles with him.

[[luke-22-15]]
^15^ And he said to them: “With longing have I desired to eat this Passover with you, before I suffer.

[[luke-22-16]]
^16^ For I say to you, that from this time, I will not eat it, until it is fulfilled in the kingdom of God.”

[[luke-22-17]]
^17^ And having taken the chalice, he gave thanks, and he said: “Take this and share it among yourselves.

[[luke-22-18]]
^18^ For I say to you, that I will not drink from the fruit of the vine, until the kingdom of God arrives.”

[[luke-22-19]]
^19^ And taking bread, he gave thanks and broke it and gave it to them, saying: “This is my body, which is given for you. Do this as a commemoration of me.”

[[luke-22-20]]
^20^ Similarly also, he took the chalice, after he had eaten the meal, saying: “This chalice is the new covenant in my blood, which will be shed for you.

[[luke-22-21]]
^21^ But in truth, behold, the hand of my betrayer is with me at table.

[[luke-22-22]]
^22^ And indeed, the Son of man goes according to what has been determined. And yet, woe to that man by whom he will be betrayed.”

[[luke-22-23]]
^23^ And they began to inquire among themselves, as to which of them might do this.

[[luke-22-24]]
^24^ Now there was also a contention among them, as to which of them seemed to be the greater.

[[luke-22-25]]
^25^ And he said to them: “The kings of the Gentiles dominate them; and those who hold authority over them are called beneficent.

[[luke-22-26]]
^26^ But it must not be so with you. Instead, whoever is greater among you, let him become the lesser. And whoever is the leader, let him become the server.

[[luke-22-27]]
^27^ For who is greater: he who sits at table, or he who serves? Is not he who sits at table? Yet I am in your midst as one who serves.

[[luke-22-28]]
^28^ But you are those who have remained with me during my trials.

[[luke-22-29]]
^29^ And I dispose to you, just as my Father has disposed to me, a kingdom,

[[luke-22-30]]
^30^ so that you may eat and drink at my table in my kingdom, and so that you may sit upon thrones, judging the twelve tribes of Israel.”

[[luke-22-31]]
^31^ And the Lord said: “Simon, Simon! Behold, Satan has asked for you, so that he may sift you like wheat.

[[luke-22-32]]
^32^ But I have prayed for you, so that your faith may not fail, and so that you, once converted, may confirm your brothers.”

[[luke-22-33]]
^33^ And he said to him, “Lord, I am prepared to go with you, even to prison and to death.”

[[luke-22-34]]
^34^ And he said, “I say to you, Peter, the rooster will not crow this day, until you have three times denied that you know me.” And he said to them,

[[luke-22-35]]
^35^ “When I sent you without money or provisions or shoes, did you lack anything?”

[[luke-22-36]]
^36^ And they said, “Nothing.” Then he said to them: “But now, let whoever has money take it, and likewise with provisions. And whoever does not have these, let him sell his coat and buy a sword.

[[luke-22-37]]
^37^ For I say to you, that what has been written must still be fulfilled in me: ‘And he was esteemed with the wicked.’ Yet even these things about me have an end.”

[[luke-22-38]]
^38^ So they said, “Lord, behold, there are two swords here.” But he said to them, “It is sufficient.”

[[luke-22-39]]
^39^ And departing, he went out, according to his custom, to the Mount of Olives. And his disciples also followed him.

[[luke-22-40]]
^40^ And when he had arrived at the place, he said to them: “Pray, lest you enter into temptation.”

[[luke-22-41]]
^41^ And he was separated from them by about a stone’s throw. And kneeling down, he prayed,

[[luke-22-42]]
^42^ saying: “Father, if you are willing, take this chalice away from me. Yet truly, let not my will, but yours, be done.”

[[luke-22-43]]
^43^ Then an Angel appeared to him from heaven, strengthening him. And being in agony, he prayed more intensely;

[[luke-22-44]]
^44^ and so his sweat became like drops of blood, running down to the ground.

[[luke-22-45]]
^45^ And when he had risen up from prayer and had gone to his disciples, he found them sleeping out of sorrow.

[[luke-22-46]]
^46^ And he said to them: “Why are you sleeping? Rise up, pray, lest you enter into temptation.”

[[luke-22-47]]
^47^ While he was still speaking, behold, a crowd arrived. And he who is called Judas, one of the twelve, went ahead of them and approached Jesus, in order to kiss him.

[[luke-22-48]]
^48^ And Jesus said to him, “Judas, do you betray the Son of man with a kiss?”

[[luke-22-49]]
^49^ Then those who were around him, realizing what was about to happen, said to him: “Lord, shall we strike with the sword?”

[[luke-22-50]]
^50^ And one of them struck the servant of the high priest and cut off his right ear.

[[luke-22-51]]
^51^ But in response, Jesus said, “Permit even this.” And when he had touched his ear, he healed him.

[[luke-22-52]]
^52^ Then Jesus said to the leaders of the priests, and the magistrates of the temple, and the elders, who had come to him: “Have you gone out, as if against a thief, with swords and clubs?

[[luke-22-53]]
^53^ When I was with you each day in the temple, you did not extend your hands against me. But this is your hour and that of the power of darkness.”

[[luke-22-54]]
^54^ And apprehending him, they led him to the house of the high priest. Yet truly, Peter followed at a distance.

[[luke-22-55]]
^55^ Now as they were sitting around a fire, which had been kindled in the middle of the atrium, Peter was in their midst.

[[luke-22-56]]
^56^ And when a certain woman servant had seen him sitting in its light, and had looked at him intently, she said, “This one was also with him.”

[[luke-22-57]]
^57^ But he denied him by saying, “Woman, I do not know him.”

[[luke-22-58]]
^58^ And after a little while, another one, seeing him, said, “You also are one of them.” Yet Peter said, “O man, I am not.”

[[luke-22-59]]
^59^ And after the interval of about one hour had passed, someone else affirmed it, saying: “Truly, this one also was with him. For he is also a Galilean.”

[[luke-22-60]]
^60^ And Peter said: “Man, I do not know what you are saying.” And at once, while he was still speaking, the rooster crowed.

[[luke-22-61]]
^61^ And the Lord turned around and looked at Peter. And Peter remembered the word of the Lord that he had said: “For before the rooster crows, you will deny me three times.”

[[luke-22-62]]
^62^ And going out, Peter wept bitterly.

[[luke-22-63]]
^63^ And the men who were holding him ridiculed him and beat him.

[[luke-22-64]]
^64^ And they blindfolded him and repeatedly struck his face. And they questioned him, saying: “Prophesy! Who is it that struck you?”

[[luke-22-65]]
^65^ And blaspheming in many other ways, they spoke against him.

[[luke-22-66]]
^66^ And when it was daytime, the elders of the people, and the leaders of the priests, and the scribes convened. And they led him into their council, saying, “If you are the Christ, tell us.”

[[luke-22-67]]
^67^ And he said to them: “If I tell you, you will not believe me.

[[luke-22-68]]
^68^ And if I also question you, you will not answer me. Neither will you release me.

[[luke-22-69]]
^69^ But from this time, the Son of man will be sitting at the right hand of the power of God.”

[[luke-22-70]]
^70^ Then they all said, “So you are the Son of God?” And he said. “You are saying that I am.”

[[luke-22-71]]
^71^ And they said: “Why do we still require testimony? For we have heard it ourselves, from his own mouth.”


[[luke-23]]
== Chapter 23

[[luke-23-1]]
^1^ And the entire multitude of them, rising up, led him to Pilate.

[[luke-23-2]]
^2^ Then they began to accuse him, saying, “We found this one subverting our nation, and prohibiting giving tribute to Caesar, and saying that he is Christ the king.”

[[luke-23-3]]
^3^ And Pilate questioned him, saying: “You are the king of the Jews?” But in response, he said: “You are saying it.”

[[luke-23-4]]
^4^ Then Pilate said to the leaders of the priests and to the crowds, “I find no case against this man.”

[[luke-23-5]]
^5^ But they continued more intensely, saying: “He has stirred up the people, teaching throughout all of Judea, beginning from Galilee, even to this place.”

[[luke-23-6]]
^6^ But Pilate, upon hearing Galilee, asked if the man were of Galilee.

[[luke-23-7]]
^7^ And when he realized that he was under Herod’s jurisdiction, he sent him away to Herod, who was himself also at Jerusalem in those days.

[[luke-23-8]]
^8^ Then Herod, upon seeing Jesus, was very glad. For he had been wanting to see him for a long time, because he had heard so many things about him, and he was hoping to see some kind of sign wrought by him.

[[luke-23-9]]
^9^ Then he questioned him with many words. But he gave him no response at all.

[[luke-23-10]]
^10^ And the leaders of the priests, and the scribes, stood firm in persistently accusing him.

[[luke-23-11]]
^11^ Then Herod, with his soldiers, scorned him. And he ridiculed him, clothing him in a white garment. And he sent him back to Pilate.

[[luke-23-12]]
^12^ And Herod and Pilate became friends on that day. For previously they were enemies to one another.

[[luke-23-13]]
^13^ And Pilate, calling together the leaders of the priests, and the magistrates, and the people,

[[luke-23-14]]
^14^ said to them: “You have brought before me this man, as one who disturbs the people. And behold, having questioned him before you, I find no case against this man, in those things about which you accuse him.

[[luke-23-15]]
^15^ And neither did Herod. For I sent you all to him, and behold, nothing deserving of death was recorded about him.

[[luke-23-16]]
^16^ Therefore, I will chastise him and release him.”

[[luke-23-17]]
^17^ Now he was required to release one person for them on the feast day.

[[luke-23-18]]
^18^ But the entire crowd exclaimed together, saying: “Take this one, and release to us Barabbas!”

[[luke-23-19]]
^19^ Now he had been cast into prison because of a certain sedition that occurred in the city and for murder.

[[luke-23-20]]
^20^ Then Pilate spoke to them again, wanting to release Jesus.

[[luke-23-21]]
^21^ But they shouted in response, saying: “Crucify him! Crucify him!”

[[luke-23-22]]
^22^ Then he said to them a third time: “Why? What evil has he done? I find no case against him for death. Therefore, I will chastise him and release him.”

[[luke-23-23]]
^23^ But they persisted, with loud voices, in demanding that he be crucified. And their voices increased in intensity.

[[luke-23-24]]
^24^ And so Pilate issued a judgment granting their petition.

[[luke-23-25]]
^25^ Then he released for them the one who had been cast into prison for murder and sedition, whom they were requesting. Yet truly, Jesus he handed over to their will.

[[luke-23-26]]
^26^ And as they were leading him away, they apprehended a certain one, Simon of Cyrene, as he was returning from the countryside. And they imposed the cross on him to carry after Jesus.

[[luke-23-27]]
^27^ Then a great crowd of people followed him, with women who were mourning and lamenting him.

[[luke-23-28]]
^28^ But Jesus, turning to them, said: “Daughters of Jerusalem, do not weep over me. Instead, weep over yourselves and over your children.

[[luke-23-29]]
^29^ For behold, the days will arrive in which they will say, ‘Blessed are the barren, and the wombs that have not borne, and the breasts that have not nursed.’

[[luke-23-30]]
^30^ Then they will begin to say to the mountains, ‘Fall over us,’ and to the hills, ‘Cover us.’

[[luke-23-31]]
^31^ For if they do these things with green wood, what will be done with the dry?”

[[luke-23-32]]
^32^ Now they also led out two other criminals with him, in order to execute them.

[[luke-23-33]]
^33^ And when they arrived at the place that is called Calvary, they crucified him there, with the robbers, one to the right and the other to the left.

[[luke-23-34]]
^34^ Then Jesus said, “Father, forgive them. For they know not what they do.” And truly, dividing his garments, they cast lots.

[[luke-23-35]]
^35^ And people were standing near, watching. And the leaders among them derided him, saying: “He saved others. Let him save himself, if this one is the Christ, the elect of God.”

[[luke-23-36]]
^36^ And the soldiers also ridiculed him, approaching him and offering him vinegar,

[[luke-23-37]]
^37^ and saying, “If you are the king of the Jews, save yourself.”

[[luke-23-38]]
^38^ Now there was also an inscription written over him in letters of Greek, and Latin, and Hebrew: THIS IS THE KING OF THE JEWS.

[[luke-23-39]]
^39^ And one of those robbers who were hanging blasphemed him, saying, “If you are the Christ, save yourself and us.”

[[luke-23-40]]
^40^ But the other responded by rebuking him, saying: “Do you have no fear of God, since you are under the same condemnation?

[[luke-23-41]]
^41^ And indeed, it is just for us. For we are receiving what our deeds deserve. But truly, this one has done nothing wrong.”

[[luke-23-42]]
^42^ And he said to Jesus, “Lord, remember me when you come into your kingdom.”

[[luke-23-43]]
^43^ And Jesus said to him, “Amen I say to you, this day you shall be with me in Paradise.”

[[luke-23-44]]
^44^ Now it was nearly the sixth hour, and a darkness occurred over the entire earth, until the ninth hour.

[[luke-23-45]]
^45^ And the sun was obscured. And the veil of the temple was torn down the middle.

[[luke-23-46]]
^46^ And Jesus, crying out with a loud voice, said: “Father, into your hands I commend my spirit.” And upon saying this, he expired.

[[luke-23-47]]
^47^ Now, the centurion, seeing what had happened, glorified God, saying, “Truly, this man was the Just One.”

[[luke-23-48]]
^48^ And the entire crowd of those who came together to see this spectacle also saw what had happened, and they returned, striking their breasts.

[[luke-23-49]]
^49^ Now all those who knew him, and the women who had followed him from Galilee, were standing at a distance, watching these things.

[[luke-23-50]]
^50^ And behold, there was a man named Joseph, who was a councilman, a good and just man,

[[luke-23-51]]
^51^ (for he had not consented to their decision or their actions). He was from Arimathea, a city of Judea. And he was himself also anticipating the kingdom of God.

[[luke-23-52]]
^52^ This man approached Pilate and petitioned for the body of Jesus.

[[luke-23-53]]
^53^ And taking him down, he wrapped him in a fine linen cloth, and he placed him in a tomb hewn from rock, in which no one had ever been placed.

[[luke-23-54]]
^54^ And it was the day of Preparation, and the Sabbath was drawing near.

[[luke-23-55]]
^55^ Now the women who had come with him from Galilee, by following, saw the tomb and the manner in which his body was placed.

[[luke-23-56]]
^56^ And upon returning, they prepared aromatic spices and ointments. But on the Sabbath, indeed, they rested, according to the commandment.


[[luke-24]]
== Chapter 24

[[luke-24-1]]
^1^ Then, on the first Sabbath, at very first light, they went to the tomb, carrying the aromatic spices that they had prepared.

[[luke-24-2]]
^2^ And they found the stone rolled back from the tomb.

[[luke-24-3]]
^3^ And upon entering, they did not find the body of the Lord Jesus.

[[luke-24-4]]
^4^ And it happened that, while their minds were still confused about this, behold, two men stood beside them, in shining apparel.

[[luke-24-5]]
^5^ Then, since they were afraid and were turning their faces toward the ground, these two said to them: “Why do you seek the living with the dead?

[[luke-24-6]]
^6^ He is not here, for he has risen. Recall how he spoke to you, when he was still in Galilee,

[[luke-24-7]]
^7^ saying: ‘For the Son of man must be delivered into the hands of sinful men, and be crucified, and on the third day rise again.’ ”

[[luke-24-8]]
^8^ And they called to mind his words.

[[luke-24-9]]
^9^ And returning from the tomb, they reported all these things to the eleven, and to all the others.

[[luke-24-10]]
^10^ Now it was Mary Magdalene, and Joanna, and Mary of James, and the other women who were with them, who told these things to the Apostles.

[[luke-24-11]]
^11^ But these words seemed to them a delusion. And so they did not believe them.

[[luke-24-12]]
^12^ But Peter, rising up, ran to the tomb. And stooping down, he saw the linen cloths positioned alone, and he went away wondering to himself about what had happened.

[[luke-24-13]]
^13^ And behold, two of them went out, on the same day, to a town named Emmaus, which was the distance of sixty stadia from Jerusalem.

[[luke-24-14]]
^14^ And they spoke to one another about all of these things that had occurred.

[[luke-24-15]]
^15^ And it happened that, while they were speculating and questioning within themselves, Jesus himself, drawing near, traveled with them.

[[luke-24-16]]
^16^ But their eyes were restrained, so that they would not recognize him.

[[luke-24-17]]
^17^ And he said to them, “What are these words, which you are discussing with one another, as you walk and are sad?”

[[luke-24-18]]
^18^ And one of them, whose name was Cleopas, responded by saying to him, “Are you the only one visiting Jerusalem who does not know the things that have happened there in these days?”

[[luke-24-19]]
^19^ And he said to them, “What things?” And they said, “About Jesus of Nazareth, who was a noble prophet, powerful in works and in words, before God and all the people.

[[luke-24-20]]
^20^ And how our high priests and leaders handed him over to be condemned to death. And they crucified him.

[[luke-24-21]]
^21^ But we were hoping that he would be the Redeemer of Israel. And now, on top of all this, today is the third day since these things have happened.

[[luke-24-22]]
^22^ Then, too, certain women from among us terrified us. For before daytime, they were at the tomb,

[[luke-24-23]]
^23^ and, having not found his body, they returned, saying that they had even seen a vision of Angels, who said that he is alive.

[[luke-24-24]]
^24^ And some of us went out to the tomb. And they found it just as the women had said. But truly, they did not find him.”

[[luke-24-25]]
^25^ And he said to them: “How foolish and reluctant in heart you are, to believe everything that has been spoken by the Prophets!

[[luke-24-26]]
^26^ Was not the Christ required to suffer these things, and so enter into his glory?”

[[luke-24-27]]
^27^ And beginning from Moses and all the Prophets, he interpreted for them, in all the Scriptures, the things that were about him.

[[luke-24-28]]
^28^ And they drew near to the town where they were going. And he conducted himself so as to go on further.

[[luke-24-29]]
^29^ But they were insistent with him, saying, “Remain with us, because it is toward evening and now daylight is declining.” And so he entered with them.

[[luke-24-30]]
^30^ And it happened that, while he was at table with them, he took bread, and he blessed and broke it, and he extended it to them.

[[luke-24-31]]
^31^ And their eyes were opened, and they recognized him. And he vanished from their eyes.

[[luke-24-32]]
^32^ And they said to one another, “Was not our heart burning within us, while he was speaking on the way, and when he opened the Scriptures to us?”

[[luke-24-33]]
^33^ And rising up at that same hour, they returned to Jerusalem. And they found the eleven gathered together, and those who were with them,

[[luke-24-34]]
^34^ saying: “In truth, the Lord has risen, and he has appeared to Simon.”

[[luke-24-35]]
^35^ And they explained the things that were done on the way, and how they had recognized him at the breaking of the bread.

[[luke-24-36]]
^36^ Then, while they were talking about these things, Jesus stood in their midst, And he said to them: “Peace be with you. It is I. Do not be afraid.”

[[luke-24-37]]
^37^ Yet truly, they were very disturbed and terrified, supposing that they saw a spirit.

[[luke-24-38]]
^38^ And he said to them: “Why are you disturbed, and why do these thoughts rise up in your hearts?

[[luke-24-39]]
^39^ See my hands and feet, that it is I myself. Look and touch. For a spirit does not have flesh and bones, as you see that I have.”

[[luke-24-40]]
^40^ And when he had said this, he showed them his hands and feet.

[[luke-24-41]]
^41^ Then, while they were still in disbelief and in wonder out of joy, he said, “Do you have anything here to eat?”

[[luke-24-42]]
^42^ And they offered him a piece of roasted fish and a honeycomb.

[[luke-24-43]]
^43^ And when he had eaten these in their sight, taking up what was left, he gave it to them.

[[luke-24-44]]
^44^ And he said to them: “These are the words that I spoke to you when I was still with you, because all things must be fulfilled which are written in the law of Moses, and in the Prophets, and in the Psalms about me.”

[[luke-24-45]]
^45^ Then he opened their mind, so that they might understand the Scriptures.

[[luke-24-46]]
^46^ And he said to them: “For so it is written, and so it was necessary, for the Christ to suffer and to rise up from the dead on the third day,

[[luke-24-47]]
^47^ and, in his name, for repentance and the remission of sins to be preached, among all the nations, beginning at Jerusalem.

[[luke-24-48]]
^48^ And you are witnesses of these things.

[[luke-24-49]]
^49^ And I am sending the Promise of my Father upon you. But you must stay in the city, until such time as you are clothed with power from on high.”

[[luke-24-50]]
^50^ Then he led them out as far as Bethania. And lifting up his hands, he blessed them.

[[luke-24-51]]
^51^ And it happened that, while he was blessing them, he withdrew from them, and he was carried up into heaven.

[[luke-24-52]]
^52^ And worshiping, they returned to Jerusalem with great joy.

[[luke-24-53]]
^53^ And they were always in the temple, praising and blessing God. Amen.
