[[john]]
= The Gospel of John
:short: John

[[john-1]]
== Chapter 1

[[john-1-1]]
^1^ In the beginning was the Word, and the Word was with God, and God was the Word.

[[john-1-2]]
^2^ He was with God in the beginning.

[[john-1-3]]
^3^ All things were made through Him, and nothing that was made was made without Him.

[[john-1-4]]
^4^ Life was in Him, and Life was the light of men.

[[john-1-5]]
^5^ And the light shines in the darkness, and the darkness did not comprehend it.

[[john-1-6]]
^6^ There was a man sent by God, whose name was John.

[[john-1-7]]
^7^ He arrived as a witness to offer testimony about the Light, so that all would believe through him.

[[john-1-8]]
^8^ He was not the Light, but he was to offer testimony about the Light.

[[john-1-9]]
^9^ The true Light, which illuminates every man, was coming into this world.

[[john-1-10]]
^10^ He was in the world, and the world was made through him, and the world did not recognize him.

[[john-1-11]]
^11^ He went to his own, and his own did not accept him.

[[john-1-12]]
^12^ Yet whoever did accept him, those who believed in his name, he gave them the power to become the sons of God.

[[john-1-13]]
^13^ These are born, not of blood, nor of the will of flesh, nor of the will of man, but of God.

[[john-1-14]]
^14^ And the Word became flesh, and he lived among us, and we saw his glory, glory like that of an only-begotten Son from the Father, full of grace and truth.

[[john-1-15]]
^15^ John offers testimony about him, and he cries out, saying: “This is the one about whom I said: ‘He who is to come after me, has been placed ahead of me, because he existed before me.’ ”

[[john-1-16]]
^16^ And from his fullness, we all have received, even grace for grace.

[[john-1-17]]
^17^ For the law was given through Moses, but grace and truth came through Jesus Christ.

[[john-1-18]]
^18^ No one ever saw God; the only-begotten Son, who is in the bosom of the Father, he himself has described him.

[[john-1-19]]
^19^ And this is the testimony of John, when the Jews sent priests and Levites from Jerusalem to him, so that they might ask him, “Who are you?”

[[john-1-20]]
^20^ And he confessed it and did not deny it; and what he confessed was: “I am not the Christ.”

[[john-1-21]]
^21^ And they questioned him: “Then what are you? Are you Elijah?” And he said, “I am not.” “Are you the Prophet?” And he answered, “No.”

[[john-1-22]]
^22^ Therefore, they said to him: “Who are you, so that we may give an answer to those who sent us? What do you say about yourself?”

[[john-1-23]]
^23^ He said, “I am a voice crying out in the desert, ‘Make straight the way of the Lord,’ just as the prophet Isaiah said.”

[[john-1-24]]
^24^ And some of those who had been sent were from among the Pharisees.

[[john-1-25]]
^25^ And they questioned him and said to him, “Then why do you baptize, if you are not the Christ, and not Elijah, and not the Prophet?”

[[john-1-26]]
^26^ John answered them by saying: “I baptize with water. But in your midst stands one, whom you do not know.

[[john-1-27]]
^27^ The same is he who is to come after me, who has been placed ahead of me, the laces of whose shoes I am not worthy to loosen.”

[[john-1-28]]
^28^ These things happened in Bethania, across the Jordan, where John was baptizing.

[[john-1-29]]
^29^ On the next day, John saw Jesus coming toward him, and so he said: “Behold, the Lamb of God. Behold, he who takes away the sin of the world.

[[john-1-30]]
^30^ This is the one about whom I said, ‘After me arrives a man, who has been placed ahead of me, because he existed before me.’

[[john-1-31]]
^31^ And I did not know him. Yet it is for this reason that I come baptizing with water: so that he may be made manifest in Israel.”

[[john-1-32]]
^32^ And John offered testimony, saying: “For I saw the Spirit descending from heaven like a dove; and he remained upon him.

[[john-1-33]]
^33^ And I did not know him. But he who sent me to baptize with water said to me: ‘He over whom you will see the Spirit descending and remaining upon him, this is the one who baptizes with the Holy Spirit.’

[[john-1-34]]
^34^ And I saw, and I gave testimony: that this one is the Son of God.”

[[john-1-35]]
^35^ The next day again, John was standing with two of his disciples.

[[john-1-36]]
^36^ And catching sight of Jesus walking, he said, “Behold, the Lamb of God.”

[[john-1-37]]
^37^ And two disciples were listening to him speaking. And they followed Jesus.

[[john-1-38]]
^38^ Then Jesus, turning around and seeing them following him, said to them, “What are you seeking?” And they said to him, “Rabbi (which means in translation, Teacher), where do you live?”

[[john-1-39]]
^39^ He said to them, “Come and see.” They went and saw where he was staying, and they stayed with him that day. Now it was about the tenth hour.

[[john-1-40]]
^40^ And Andrew, the brother of Simon Peter, was one of the two who had heard about him from John and had followed him.

[[john-1-41]]
^41^ First, he found his brother Simon, and he said to him, “We have found the Messiah,” (which is translated as the Christ).

[[john-1-42]]
^42^ And he led him to Jesus. And Jesus, gazing at him, said: “You are Simon, son of Jonah. You shall be called Cephas,” (which is translated as Peter).

[[john-1-43]]
^43^ On the next day, he wanted to go into Galilee, and he found Philip. And Jesus said to him, “Follow me.”

[[john-1-44]]
^44^ Now Philip was from Bethsaida, the city of Andrew and Peter.

[[john-1-45]]
^45^ Philip found Nathanael, and he said to him, “We have found the one about whom Moses wrote in the Law and the Prophets: Jesus, the son of Joseph, from Nazareth.”

[[john-1-46]]
^46^ And Nathanael said to him, “Can anything good be from Nazareth?” Philip said to him, “Come and see.”

[[john-1-47]]
^47^ Jesus saw Nathanael coming toward him, and he said about him, “Behold, an Israelite in whom truly there is no deceit.”

[[john-1-48]]
^48^ Nathanael said to him, “From where do you know me?” Jesus responded and said to him, “Before Philip called you, when you were under the fig tree, I saw you.”

[[john-1-49]]
^49^ Nathanael answered him and said: “Rabbi, you are the Son of God. You are the King of Israel.”

[[john-1-50]]
^50^ Jesus responded and said to him: “Because I told you that I saw you under the fig tree, you believe. Greater things than these, you will see.”

[[john-1-51]]
^51^ And he said to him, “Amen, amen, I say to you, you will see heaven opened, and the Angels of God ascending and descending over the Son of man.”


[[john-2]]
== Chapter 2

[[john-2-1]]
^1^ And on the third day, a wedding was held in Cana of Galilee, and the mother of Jesus was there.

[[john-2-2]]
^2^ Now Jesus was also invited to the wedding, with his disciples.

[[john-2-3]]
^3^ And when the wine was failing, the mother of Jesus said to him, “They have no wine.”

[[john-2-4]]
^4^ And Jesus said to her: “What is that to me and to you, woman? My hour has not yet arrived.”

[[john-2-5]]
^5^ His mother said to the servants, “Do whatever he tells you.”

[[john-2-6]]
^6^ Now in that place, there were six stone water jars, for the purification ritual of the Jews, containing two or three measures each.

[[john-2-7]]
^7^ Jesus said to them, “Fill the water jars with water.” And they filled them to the very top.

[[john-2-8]]
^8^ And Jesus said to them, “Now draw from it, and carry it to the chief steward of the feast.” And they took it to him.

[[john-2-9]]
^9^ Then, when the chief steward had tasted the water made into wine, since he did not know where it was from, for only the servants who had drawn the water knew, the chief steward called the groom,

[[john-2-10]]
^10^ and he said to him: “Every man offers the good wine first, and then, when they have become inebriated, he offers what is worse. But you have kept the good wine until now.”

[[john-2-11]]
^11^ This was the beginning of the signs that Jesus accomplished in Cana of Galilee, and it manifested his glory, and his disciples believed in him.

[[john-2-12]]
^12^ After this, he descended to Capernaum, with his mother and his brothers and his disciples, but they did not remain there for many days.

[[john-2-13]]
^13^ And the Passover of the Jews was near, and so Jesus ascended to Jerusalem.

[[john-2-14]]
^14^ And he found, sitting in the temple, sellers of oxen and sheep and doves, and the moneychangers.

[[john-2-15]]
^15^ And when he had made something like a whip out of little cords, he drove them all out of the temple, including the sheep and the oxen. And he poured out the brass coins of the moneychangers, and he overturned their tables.

[[john-2-16]]
^16^ And to those who were selling doves, he said: “Take these things out of here, and do not make my Father’s house into a house of commerce.”

[[john-2-17]]
^17^ And truly, his disciples were reminded that it is written: “Zeal for your house consumes me.”

[[john-2-18]]
^18^ Then the Jews responded and said to him, “What sign can you show to us, that you may do these things?”

[[john-2-19]]
^19^ Jesus responded and said to them, “Destroy this temple, and in three days I will raise it up.”

[[john-2-20]]
^20^ Then the Jews said, “This temple has been built up over forty-six years, and you will raise it up in three days?”

[[john-2-21]]
^21^ Yet he was speaking about the Temple of his body.

[[john-2-22]]
^22^ Therefore, when he had resurrected from the dead, his disciples were reminded that he had said this, and they believed in the Scriptures and in the word that Jesus had spoken.

[[john-2-23]]
^23^ Now while he was at Jerusalem during the Passover, on the day of the feast, many trusted in his name, seeing his signs that he was accomplishing.

[[john-2-24]]
^24^ But Jesus did not trust himself to them, because he himself had knowledge of all persons,

[[john-2-25]]
^25^ and because he had no need of anyone to offer testimony about a man. For he knew what was within a man.


[[john-3]]
== Chapter 3

[[john-3-1]]
^1^ Now there was a man among the Pharisees, named Nicodemus, a leader of the Jews.

[[john-3-2]]
^2^ He went to Jesus at night, and he said to him: “Rabbi, we know that you have arrived as a teacher from God. For no one would be able to accomplish these signs, which you accomplish, unless God were with him.”

[[john-3-3]]
^3^ Jesus responded and said to him, “Amen, amen, I say to you, unless one has been reborn anew, he is not able to see the kingdom of God.”

[[john-3-4]]
^4^ Nicodemus said to him: “How could a man be born when he is old? Surely, he cannot enter a second time into his mother’s womb to be reborn?”

[[john-3-5]]
^5^ Jesus responded: “Amen, amen, I say to you, unless one has been reborn by water and the Holy Spirit, he is not able to enter into the kingdom of God.

[[john-3-6]]
^6^ What is born of the flesh is flesh, and what is born of the Spirit is spirit.

[[john-3-7]]
^7^ You should not be amazed that I said to you: You must be born anew.

[[john-3-8]]
^8^ The Spirit inspires where he wills. And you hear his voice, but you do not know where he comes from, or where he is going. So it is with all who are born of the Spirit.”

[[john-3-9]]
^9^ Nicodemus responded and said to him, “How are these things able to be accomplished?”

[[john-3-10]]
^10^ Jesus responded and said to him: “You are a teacher in Israel, and you are ignorant of these things?

[[john-3-11]]
^11^ Amen, amen, I say to you, that we speak about what we know, and we testify about what we have seen. But you do not accept our testimony.

[[john-3-12]]
^12^ If I have spoken to you about earthly things, and you have not believed, then how will you believe, if I will speak to you about heavenly things?

[[john-3-13]]
^13^ And no one has ascended to heaven, except the one who descended from heaven: the Son of man who is in heaven.

[[john-3-14]]
^14^ And just as Moses lifted up the serpent in the desert, so also must the Son of man be lifted up,

[[john-3-15]]
^15^ so that whoever believes in him may not perish, but may have eternal life.

[[john-3-16]]
^16^ For God so loved the world that he gave his only-begotten Son, so that all who believe in him may not perish, but may have eternal life.

[[john-3-17]]
^17^ For God did not send his Son into the world, in order to judge the world, but in order that the world may be saved through him.

[[john-3-18]]
^18^ Whoever believes in him is not judged. But whoever does not believe is already judged, because he does not believe in the name of the only-begotten Son of God.

[[john-3-19]]
^19^ And this is the judgment: that the Light has come into the world, and men loved darkness more than light. For their works were evil.

[[john-3-20]]
^20^ For everyone who does evil hates the Light and does not go toward the Light, so that his works may not be corrected.

[[john-3-21]]
^21^ But whoever acts in truth goes toward the Light, so that his works may be manifested, because they have been accomplished in God.”

[[john-3-22]]
^22^ After these things, Jesus and his disciples went into the land of Judea. And he was living there with them and baptizing.

[[john-3-23]]
^23^ Now John was also baptizing, at Aenon near Salim, because there was much water in that place. And they were arriving and being baptized.

[[john-3-24]]
^24^ For John had not yet been cast into prison.

[[john-3-25]]
^25^ Then a dispute occurred between the disciples of John and the Jews, about purification.

[[john-3-26]]
^26^ And they went to John and said to him: “Rabbi, the one who was with you across the Jordan, about whom you offered testimony: behold, he is baptizing and everyone is going to him.”

[[john-3-27]]
^27^ John responded and said: “A man is not able to receive anything, unless it has been given to him from heaven.

[[john-3-28]]
^28^ You yourselves offer testimony for me that I said, ‘I am not the Christ,’ but that I have been sent before him.

[[john-3-29]]
^29^ He who holds the bride is the groom. But the friend of the groom, who stands and listens to Him, rejoices joyfully at the voice of the groom. And so, this, my joy, has been fulfilled.

[[john-3-30]]
^30^ He must increase, while I must decrease.

[[john-3-31]]
^31^ He who comes from above, is above everything. He who is from below, is of the earth, and he speaks about the earth. He who comes from heaven is above everything.

[[john-3-32]]
^32^ And what he has seen and heard, about this he testifies. And no one accepts his testimony.

[[john-3-33]]
^33^ Whoever has accepted his testimony has certified that God is truthful.

[[john-3-34]]
^34^ For he whom God has sent speaks the words of God. For God does not give the Spirit by measure.

[[john-3-35]]
^35^ The Father loves the Son, and he has given everything into his hand.

[[john-3-36]]
^36^ Whoever believes in the Son has eternal life. But whoever is unbelieving toward the Son shall not see life; instead the wrath of God remains upon him.”


[[john-4]]
== Chapter 4

[[john-4-1]]
^1^ And so, when Jesus realized that the Pharisees had heard that Jesus made more disciples and baptized more than John,

[[john-4-2]]
^2^ (though Jesus himself was not baptizing, but only his disciples)

[[john-4-3]]
^3^ he left behind Judea, and he traveled again to Galilee.

[[john-4-4]]
^4^ Now he needed to cross through Samaria.

[[john-4-5]]
^5^ Therefore, he went into a city of Samaria which is called Sychar, near the estate which Jacob gave to his son Joseph.

[[john-4-6]]
^6^ And Jacob’s well was there. And so Jesus, being tired from the journey, was sitting in a certain way on the well. It was about the sixth hour.

[[john-4-7]]
^7^ A woman of Samaria arrived to draw water. Jesus said to her, “Give me to drink.”

[[john-4-8]]
^8^ For his disciples had gone into the city in order to buy food.

[[john-4-9]]
^9^ And so, that Samaritan woman said to him, “How is it that you, being a Jew, are requesting a drink from me, though I am a Samaritan woman?” For the Jews do not associate with the Samaritans.

[[john-4-10]]
^10^ Jesus responded and said to her: “If you knew the gift of God, and who it is who is saying to you, ‘Give me to drink,’ perhaps you would have made a request of him, and he would have given you living water.”

[[john-4-11]]
^11^ The woman said to him: “Lord, you do not have anything with which to draw water, and the well is deep. From where, then, do you have living water?

[[john-4-12]]
^12^ Surely, you are not greater than our father Jacob, who gave us the well and who drank from it, with his sons and his cattle?”

[[john-4-13]]
^13^ Jesus responded and said to her: “All who drink from this water will thirst again. But whoever shall drink from the water that I will give to him will not thirst for eternity.

[[john-4-14]]
^14^ Instead, the water that I will give to him will become in him a fountain of water, springing up into eternal life.”

[[john-4-15]]
^15^ The woman said to him, “Lord, give me this water, so that I may not thirst and may not come here to draw water.”

[[john-4-16]]
^16^ Jesus said to her, “Go, call your husband, and return here.”

[[john-4-17]]
^17^ The woman responded and said, “I have no husband.” Jesus said to her: “You have spoken well, in saying, ‘I have no husband.’

[[john-4-18]]
^18^ For you have had five husbands, but he whom you have now is not your husband. You have spoken this in truth.”

[[john-4-19]]
^19^ The woman said to him: “Lord, I see that you are a Prophet.

[[john-4-20]]
^20^ Our fathers worshipped on this mountain, but you say that Jerusalem is the place where one ought to worship.”

[[john-4-21]]
^21^ Jesus said to her: “Woman, believe me, the hour is coming when you shall worship the Father, neither on this mountain, nor in Jerusalem.

[[john-4-22]]
^22^ You worship what you do not know; we worship what we do know. For salvation is from the Jews.

[[john-4-23]]
^23^ But the hour is coming, and it is now, when true worshippers shall worship the Father in spirit and in truth. For the Father also seeks such persons who may worship him.

[[john-4-24]]
^24^ God is Spirit. And so, those who worship him must worship in spirit and in truth.”

[[john-4-25]]
^25^ The woman said to him: “I know that the Messiah is coming (who is called the Christ). And then, when he will have arrived, he will announce everything to us.”

[[john-4-26]]
^26^ Jesus said to her: “I am he, the one who is speaking with you.”

[[john-4-27]]
^27^ And then his disciples arrived. And they wondered that he was speaking with the woman. Yet no one said: “What are you seeking?” or, “Why are you talking with her?”

[[john-4-28]]
^28^ And so the woman left behind her water jar and went into the city. And she said to the men there:

[[john-4-29]]
^29^ “Come and see a man who has told me all the things that I have done. Is he not the Christ?”

[[john-4-30]]
^30^ Therefore, they went out of the city and came to him.

[[john-4-31]]
^31^ Meanwhile, the disciples petitioned him, saying, “Rabbi, eat.”

[[john-4-32]]
^32^ But he said to them, “I have food to eat which you do not know.”

[[john-4-33]]
^33^ Therefore, the disciples said to one another, “Could someone have brought him something to eat?”

[[john-4-34]]
^34^ Jesus said to them: “My food is to do the will of the One who sent me, so that I may perfect his work.

[[john-4-35]]
^35^ Do you not say, ‘There are still four months, and then the harvest arrives?’ Behold, I say to you: Lift up your eyes and look at the countryside; for it is already ripe for the harvest.

[[john-4-36]]
^36^ For he who reaps, receives wages and gathers fruit unto eternal life, so that both he who sows and he who reaps may rejoice together.

[[john-4-37]]
^37^ For in this the word is true: that it is one who sows, and it is another who reaps.

[[john-4-38]]
^38^ I have sent you to reap that for which you did not labor. Others have labored, and you have entered into their labors.”

[[john-4-39]]
^39^ Now many of the Samaritans from that city believed in him, because of the word of the woman who was offering testimony: “For he told me all the things that I have done.”

[[john-4-40]]
^40^ Therefore, when the Samaritans had come to him, they petitioned him to lodge there. And he lodged there for two days.

[[john-4-41]]
^41^ And many more believed in him, because of his own word.

[[john-4-42]]
^42^ And they said to the woman: “Now we believe, not because of your speech, but because we ourselves have heard him, and so we know that he is truly the Savior of the world.”

[[john-4-43]]
^43^ Then, after two days, he departed from there, and he traveled into Galilee.

[[john-4-44]]
^44^ For Jesus himself offered testimony that a Prophet has no honor in his own country.

[[john-4-45]]
^45^ And so, when he had arrived in Galilee, the Galileans received him, because they had seen all that he had done at Jerusalem, in the day of the feast. For they also went to the feast day.

[[john-4-46]]
^46^ Then he went again into Cana of Galilee, where he made water into wine. And there was a certain ruler, whose son was sick at Capernaum.

[[john-4-47]]
^47^ Since he had heard that Jesus came to Galilee from Judea, he sent to him and begged him to come down and heal his son. For he was beginning to die.

[[john-4-48]]
^48^ Therefore, Jesus said to him, “Unless you have seen signs and wonders, you do not believe.”

[[john-4-49]]
^49^ The ruler said to him, “Lord, come down before my son dies.”

[[john-4-50]]
^50^ Jesus said to him, “Go, your son lives.” The man believed the word that Jesus spoke to him, and so he went away.

[[john-4-51]]
^51^ Then, as he was going down, his servants met him. And they reported to him, saying that his son was alive.

[[john-4-52]]
^52^ Therefore, he asked them at which hour he had become better. And they said to him, “Yesterday, at the seventh hour, the fever left him.”

[[john-4-53]]
^53^ Then the father realized that it was at the same hour that Jesus said to him, “Your son lives.” And both he and his entire household believed.

[[john-4-54]]
^54^ This next sign was the second that Jesus accomplished, after he had arrived in Galilee from Judea.


[[john-5]]
== Chapter 5

[[john-5-1]]
^1^ After these things, there was a feast day of the Jews, and so Jesus ascended to Jerusalem.

[[john-5-2]]
^2^ Now at Jerusalem is the Pool of Evidence, which in Hebrew is known as the Place of Mercy; it has five porticos.

[[john-5-3]]
^3^ Along these lay a great multitude of the sick, the blind, the lame, and the withered, waiting for the movement of the water.

[[john-5-4]]
^4^ Now at times an Angel of the Lord would descend into the pool, and so the water was moved. And whoever descended first into the pool, after the motion of the water, he was healed of whatever infirmity held him.

[[john-5-5]]
^5^ And there was a certain man in that place, having been in his infirmity for thirty-eight years.

[[john-5-6]]
^6^ Then, when Jesus had seen him reclining, and when he realized that he had been afflicted for a long time, he said to him, “Do you want to be healed?”

[[john-5-7]]
^7^ The invalid answered him: “Lord, I do not have any man to put me in the pool, when the water has been stirred. For as I am going, another descends ahead of me.”

[[john-5-8]]
^8^ Jesus said to him, “Rise, take up your stretcher, and walk.”

[[john-5-9]]
^9^ And immediately the man was healed. And he took up his stretcher and walked. Now this day was the Sabbath.

[[john-5-10]]
^10^ Therefore, the Jews said to the one who had been healed: “It is the Sabbath. It is not lawful for you to take up your stretcher.”

[[john-5-11]]
^11^ He answered them, “The one who healed me, he said to me, ‘Take up your stretcher and walk.’ ”

[[john-5-12]]
^12^ Therefore, they questioned him, “Who is that man, who said to you, ‘Take up your bed and walk?’ ”

[[john-5-13]]
^13^ But the one who had been given health did not know who it was. For Jesus had turned aside from the crowd gathered in that place.

[[john-5-14]]
^14^ Afterwards, Jesus found him in the temple, and he said to him: “Behold, you have been healed. Do not choose to sin further, otherwise something worse may happen to you.”

[[john-5-15]]
^15^ This man went away, and he reported to the Jews that it was Jesus who had given him health.

[[john-5-16]]
^16^ Because of this, the Jews were persecuting Jesus, for he was doing these things on the Sabbath.

[[john-5-17]]
^17^ But Jesus answered them, “Even now, my Father is working, and I am working.”

[[john-5-18]]
^18^ And so, because of this, the Jews were seeking to kill him even more so. For not only did he break the Sabbath, but he even said that God was his Father, making himself equal to God.

[[john-5-19]]
^19^ Then Jesus responded and said to them: “Amen, amen, I say to you, the Son is not able to do anything of himself, but only what he has seen the Father doing. For whatever he does, even this does the Son do, similarly.

[[john-5-20]]
^20^ For the Father loves the Son, and he shows him all that he himself does. And greater works than these will he show him, so much so that you shall wonder.

[[john-5-21]]
^21^ For just as the Father raises the dead and gives life, so also does the Son give life to whomever he wills.

[[john-5-22]]
^22^ For the Father does not judge anyone. But he has given all judgment to the Son,

[[john-5-23]]
^23^ so that all may honor the Son, just as they honor the Father. Whoever does not honor the Son, does not honor the Father who sent him.

[[john-5-24]]
^24^ Amen, amen, I say to you, that whoever hears my word, and believes in him who sent me, has eternal life, and he does not go into judgment, but instead he crosses from death into life.

[[john-5-25]]
^25^ Amen, amen, I say to you, that the hour is coming, and it is now, when the dead shall hear the voice of the Son of God; and those who hear it shall live.

[[john-5-26]]
^26^ For just as the Father has life in himself, so also has he granted to the Son to have life in himself.

[[john-5-27]]
^27^ And he has given him the authority to accomplish judgment. For he is the Son of man.

[[john-5-28]]
^28^ Do not be amazed at this. For the hour is coming in which all who are in the grave shall hear the voice of the Son of God.

[[john-5-29]]
^29^ And those who have done good shall go forth to the resurrection of life. Yet truly, those who have done evil shall go to the resurrection of judgment.

[[john-5-30]]
^30^ I am not able to do anything of myself. As I hear, so do I judge. And my judgment is just. For I do not seek my own will, but the will of him who sent me.

[[john-5-31]]
^31^ If I offer testimony about myself, my testimony is not true.

[[john-5-32]]
^32^ There is another who offers testimony about me, and I know that the testimony which he offers about me is true.

[[john-5-33]]
^33^ You sent to John, and he offered testimony to the truth.

[[john-5-34]]
^34^ But I do not accept testimony from man. Instead, I say these things, so that you may be saved.

[[john-5-35]]
^35^ He was a burning and shining light. So you were willing, at the time, to exult in his light.

[[john-5-36]]
^36^ But I hold a greater testimony than that of John. For the works which the Father has given to me, so that I may complete them, these works themselves that I do, offer testimony about me: that the Father has sent me.

[[john-5-37]]
^37^ And the Father who has sent me has himself offered testimony about me. And you have never heard his voice, nor have you beheld his appearance.

[[john-5-38]]
^38^ And you do not have his word abiding in you. For the one whom he sent, the same you would not believe.

[[john-5-39]]
^39^ Study the Scriptures. For you think that in them you have eternal life. And yet they also offer testimony about me.

[[john-5-40]]
^40^ And you are not willing to come to me, so that you may have life.

[[john-5-41]]
^41^ I do not accept glory from men.

[[john-5-42]]
^42^ But I know you, that you do not have the love of God within you.

[[john-5-43]]
^43^ I have come in the name of my Father, and you do not accept me. If another will arrive in his own name, him you will accept.

[[john-5-44]]
^44^ How are you able to believe, you who accept glory from one another and yet do not seek the glory that is from God alone?

[[john-5-45]]
^45^ Do not consider that I might accuse you with the Father. There is one who accuses you, Moses, in whom you hope.

[[john-5-46]]
^46^ For if you were believing in Moses, perhaps you would believe in me also. For he wrote about me.

[[john-5-47]]
^47^ But if you do not believe by his writings, how will you believe by my words?”


[[john-6]]
== Chapter 6

[[john-6-1]]
^1^ After these things, Jesus traveled across the sea of Galilee, which is the Sea of Tiberias.

[[john-6-2]]
^2^ And a great multitude was following him, for they saw the signs that he was accomplishing toward those who were infirm.

[[john-6-3]]
^3^ Therefore, Jesus went onto a mountain, and he sat down there with his disciples.

[[john-6-4]]
^4^ Now the Passover, the feast day of the Jews, was near.

[[john-6-5]]
^5^ And so, when Jesus had lifted up his eyes and had seen that a very great multitude came to him, he said to Philip, “From where should we buy bread, so that these may eat?”

[[john-6-6]]
^6^ But he said this to test him. For he himself knew what he would do.

[[john-6-7]]
^7^ Philip answered him, “Two hundred denarii of bread would not be sufficient for each of them to receive even a little.”

[[john-6-8]]
^8^ One of his disciples, Andrew, the brother of Simon Peter, said to him:

[[john-6-9]]
^9^ “There is a certain boy here, who has five barley loaves and two fish. But what are these among so many?”

[[john-6-10]]
^10^ Then Jesus said, “Have the men sit down to eat.” Now, there was much grass in that place. And so the men, in number about five thousand, sat down to eat.

[[john-6-11]]
^11^ Therefore, Jesus took the bread, and when he had given thanks, he distributed it to those who were sitting down to eat; similarly also, from the fish, as much as they wanted.

[[john-6-12]]
^12^ Then, when they were filled, he said to his disciples, “Gather the fragments that are left over, lest they be lost.”

[[john-6-13]]
^13^ And so they gathered, and they filled twelve baskets with the fragments of the five barley loaves, which were left over from those who had eaten.

[[john-6-14]]
^14^ Therefore, those men, when they had seen that Jesus had accomplished a sign, they said, “Truly, this one is the Prophet who is to come into the world.”

[[john-6-15]]
^15^ And so, when he realized that they were going to come and take him away and make him king, Jesus fled back to the mountain, by himself alone.

[[john-6-16]]
^16^ Then, when evening arrived, his disciples descended to the sea.

[[john-6-17]]
^17^ And when they had climbed into a boat, they went across the sea to Capernaum. And darkness had now arrived, and Jesus had not returned to them.

[[john-6-18]]
^18^ Then the sea was stirred up by a great wind that was blowing.

[[john-6-19]]
^19^ And so, when they had rowed about twenty-five or thirty stadia, they saw Jesus walking on the sea, and drawing near to the boat, and they were afraid.

[[john-6-20]]
^20^ But he said to them: “It is I. Do not be afraid.”

[[john-6-21]]
^21^ Therefore, they were willing to receive him into the boat. But immediately the boat was at the land to which they were going.

[[john-6-22]]
^22^ On the next day, the crowd which was standing across the sea saw that there were no other small boats in that place, except one, and that Jesus had not entered into the boat with his disciples, but that his disciples had departed alone.

[[john-6-23]]
^23^ Yet truly, other boats came over from Tiberias, next to the place where they had eaten the bread after the Lord gave thanks.

[[john-6-24]]
^24^ Therefore, when the crowd had seen that Jesus was not there, nor his disciples, they climbed into the small boats, and they went to Capernaum, seeking Jesus.

[[john-6-25]]
^25^ And when they had found him across the sea, they said to him, “Rabbi, when did you come here?”

[[john-6-26]]
^26^ Jesus answered them and said: “Amen, amen, I say to you, you seek me, not because you have seen signs, but because you have eaten from the bread and were satisfied.

[[john-6-27]]
^27^ Do not work for food that perishes, but for that which endures to eternal life, which the Son of man will give to you. For God the Father has sealed him.”

[[john-6-28]]
^28^ Therefore, they said to him, “What should we do, so that we may labor in the works of God?”

[[john-6-29]]
^29^ Jesus responded and said to them, “This is the work of God, that you believe in him whom he sent.”

[[john-6-30]]
^30^ And so they said to him: “Then what sign will you do, so that we may see it and believe in you? What will you work?

[[john-6-31]]
^31^ Our fathers ate manna in the desert, just as it has been written, ‘He gave them bread from heaven to eat.’ ”

[[john-6-32]]
^32^ Therefore, Jesus said to them: “Amen, amen, I say to you, Moses did not give you bread from heaven, but my Father gives you the true bread from heaven.

[[john-6-33]]
^33^ For the bread of God is he who descends from heaven and gives life to the world.”

[[john-6-34]]
^34^ And so they said to him, “Lord, give us this bread always.”

[[john-6-35]]
^35^ Then Jesus said to them: “I am the bread of life. Whoever comes to me shall not hunger, and whoever believes in me shall never thirst.

[[john-6-36]]
^36^ But I say to you, that even though you have seen me, you do not believe.

[[john-6-37]]
^37^ All that the Father gives to me shall come to me. And whoever comes to me, I will not cast out.

[[john-6-38]]
^38^ For I descended from heaven, not to do my own will, but the will of him who sent me.

[[john-6-39]]
^39^ Yet this is the will of the Father who sent me: that I should lose nothing out of all that he has given to me, but that I should raise them up on the last day.

[[john-6-40]]
^40^ So then, this is the will of my Father who sent me: that everyone who sees the Son and believes in him may have eternal life, and I will raise him up on the last day.”

[[john-6-41]]
^41^ Therefore, the Jews murmured about him, because he had said: “I am the living bread, who descended from heaven.”

[[john-6-42]]
^42^ And they said: “Is this not Jesus, the son of Joseph, whose father and mother we know? Then how can he say: ‘For I descended from heaven?’ ”

[[john-6-43]]
^43^ And so Jesus responded and said to them: “Do not choose to murmur among yourselves.

[[john-6-44]]
^44^ No one is able to come to me, unless the Father, who has sent me, has drawn him. And I will raise him up on the last day.

[[john-6-45]]
^45^ It has been written in the Prophets: ‘And they shall all be taught by God.’ Everyone who has listened and learned from the Father comes to me.

[[john-6-46]]
^46^ Not that anyone has seen the Father, except he who is from God; this one has seen the Father.

[[john-6-47]]
^47^ Amen, amen, I say to you, whoever believes in me has eternal life.

[[john-6-48]]
^48^ I am the bread of life.

[[john-6-49]]
^49^ Your fathers ate manna in the desert, and they died.

[[john-6-50]]
^50^ This is the bread which descends from heaven, so that if anyone will eat from it, he may not die.

[[john-6-51]]
^51^ I am the living bread, who descended from heaven.

[[john-6-52]]
^52^ If anyone eats from this bread, he shall live in eternity. And the bread that I will give is my flesh, for the life of the world.”

[[john-6-53]]
^53^ Therefore, the Jews debated among themselves, saying, “How can this man give us his flesh to eat?”

[[john-6-54]]
^54^ And so, Jesus said to them: “Amen, amen, I say to you, unless you eat the flesh of the Son of man and drink his blood, you will not have life in you.

[[john-6-55]]
^55^ Whoever eats my flesh and drinks my blood has eternal life, and I will raise him up on the last day.

[[john-6-56]]
^56^ For my flesh is true food, and my blood is true drink.

[[john-6-57]]
^57^ Whoever eats my flesh and drinks my blood abides in me, and I in him.

[[john-6-58]]
^58^ Just as the living Father has sent me and I live because of the Father, so also whoever eats me, the same shall live because of me.

[[john-6-59]]
^59^ This is the bread that descends from heaven. It is not like the manna that your fathers ate, for they died. Whoever eats this bread shall live forever.”

[[john-6-60]]
^60^ He said these things when he was teaching in the synagogue at Capernaum.

[[john-6-61]]
^61^ Therefore, many of his disciples, upon hearing this, said: “This saying is difficult,” and, “Who is able to listen to it?”

[[john-6-62]]
^62^ But Jesus, knowing within himself that his disciples were murmuring about this, said to them: “Does this offend you?

[[john-6-63]]
^63^ Then what if you were to see the Son of man ascending to where he was before?

[[john-6-64]]
^64^ It is the Spirit who gives life. The flesh does not offer anything of benefit. The words that I have spoken to you are spirit and life.

[[john-6-65]]
^65^ But there are some among you who do not believe.” For Jesus knew from the beginning who were unbelieving and which one would betray him.

[[john-6-66]]
^66^ And so he said, “For this reason, I said to you that no one is able to come to me, unless it has been given to him by my Father.”

[[john-6-67]]
^67^ After this, many of his disciples went back, and they no longer walked with him.

[[john-6-68]]
^68^ Therefore, Jesus said to the twelve, “Do you also want to go away?”

[[john-6-69]]
^69^ Then Simon Peter answered him: “Lord, to whom would we go? You have the words of eternal life.

[[john-6-70]]
^70^ And we have believed, and we recognize that you are the Christ, the Son of God.”

[[john-6-71]]
^71^ Jesus answered them: “Have I not chosen you twelve? And yet one among you is a devil.”

[[john-6-72]]
^72^ Now he was speaking about Judas Iscariot, the son of Simon. For this one, even though he was one of the twelve, was about to betray him.


[[john-7]]
== Chapter 7

[[john-7-1]]
^1^ Then, after these things, Jesus was walking in Galilee. For he was not willing to walk in Judea, because the Jews were seeking to kill him.

[[john-7-2]]
^2^ Now the feast day of the Jews, the Feast of Tabernacles, was near.

[[john-7-3]]
^3^ And his brothers said to him: “Move away from here and go into Judea, so that your disciples there may also see your works that you do.

[[john-7-4]]
^4^ Of course, no one does anything in secret, but he himself seeks to be in the public view. Since you do these things, manifest yourself to the world.”

[[john-7-5]]
^5^ For neither did his brothers believe in him.

[[john-7-6]]
^6^ Therefore, Jesus said to them: “My time has not yet come; but your time is always at hand.

[[john-7-7]]
^7^ The world cannot hate you. But it hates me, because I offer testimony about it, that its works are evil.

[[john-7-8]]
^8^ You may go up to this feast day. But I am not going up to this feast day, because my time has not yet been fulfilled.”

[[john-7-9]]
^9^ When he had said these things, he himself remained in Galilee.

[[john-7-10]]
^10^ But after his brothers went up, then he also went up to the feast day, not openly, but as if in secret.

[[john-7-11]]
^11^ Therefore, the Jews were seeking him on the feast day, and they were saying, “Where is he?”

[[john-7-12]]
^12^ And there was much murmuring in the crowd concerning him. For certain ones were saying, “He is good.” But others were saying, “No, for he seduces the crowds.”

[[john-7-13]]
^13^ Yet no one was speaking openly about him, out of fear of the Jews.

[[john-7-14]]
^14^ Then, about the middle of the feast, Jesus ascended into the temple, and he was teaching.

[[john-7-15]]
^15^ And the Jews wondered, saying: “How does this one know letters, though he has not been taught?”

[[john-7-16]]
^16^ Jesus responded to them and said: “My doctrine is not of me, but of him who sent me.

[[john-7-17]]
^17^ If anyone has chosen to do his will, then he will realize, about the doctrine, whether it is from God, or whether I am speaking from myself.

[[john-7-18]]
^18^ Whoever speaks from himself seeks his own glory. But whoever seeks the glory of him who sent him, this one is true, and injustice is not in him.

[[john-7-19]]
^19^ Did not Moses give you the law? And yet not one among you keeps the law!

[[john-7-20]]
^20^ Why are you seeking to kill me?” The crowd responded and said: “You must have a demon. Who is seeking to kill you?”

[[john-7-21]]
^21^ Jesus responded and said to them: “One work have I done, and you all wonder.

[[john-7-22]]
^22^ For Moses gave you circumcision, (not that it is of Moses, but of the fathers) and on the Sabbath you circumcise a man.

[[john-7-23]]
^23^ If a man can receive circumcision on the Sabbath, so that the law of Moses may not be broken, why are you indignant toward me, because I have made a man whole on the Sabbath?

[[john-7-24]]
^24^ Do not judge according to appearances, but instead judge a just judgment.”

[[john-7-25]]
^25^ Therefore, some of those from Jerusalem said: “Is he not the one whom they are seeking to kill?

[[john-7-26]]
^26^ And behold, he is speaking openly, and they say nothing to him. Could the leaders have decided that it is true this one is the Christ?

[[john-7-27]]
^27^ But we know him and where he is from. And when the Christ has arrived, no one will know where he is from.”

[[john-7-28]]
^28^ Therefore, Jesus cried out in the temple, teaching and saying: “You know me, and you also know where I am from. And I have not arrived of myself, but he who sent me is true, and him you do not know.

[[john-7-29]]
^29^ I know him. For I am from him, and he has sent me.”

[[john-7-30]]
^30^ Therefore, they were seeking to apprehend him, and yet no one laid hands on him, because his hour had not yet come.

[[john-7-31]]
^31^ But many among the crowd believed in him, and they were saying, “When the Christ arrives, will he perform more signs than this man does?”

[[john-7-32]]
^32^ The Pharisees heard the crowd murmuring these things about him. And the leaders and the Pharisees sent attendants to apprehend him.

[[john-7-33]]
^33^ Therefore, Jesus said to them: “For a brief time, I am still with you, and then I am going to him who sent me.

[[john-7-34]]
^34^ You shall seek me, and you will not find me. And where I am, you are not able to go.”

[[john-7-35]]
^35^ And so the Jews said among themselves: “Where is this place to which he will go, such that we will not find him? Will he go to those dispersed among the Gentiles and teach the Gentiles?

[[john-7-36]]
^36^ What is this word that he spoke, ‘You will seek me and you will not find me; and where I am, you are not able to go?’ ”

[[john-7-37]]
^37^ Then, on the last great day of the feast, Jesus was standing and crying out, saying: “If anyone thirsts, let him come to me and drink:

[[john-7-38]]
^38^ whoever believes in me, just as Scripture says, ‘From his chest shall flow rivers of living water.’ ”

[[john-7-39]]
^39^ Now he said this about the Spirit, which those who believe in him would soon be receiving. For the Spirit had not yet been given, because Jesus had not yet been glorified.

[[john-7-40]]
^40^ Therefore, some from that crowd, when they had heard these words of his, were saying, “This one truly is the Prophet.”

[[john-7-41]]
^41^ Others were saying, “He is the Christ.” Yet certain ones were saying: “Does the Christ come from Galilee?

[[john-7-42]]
^42^ Does Scripture not say that the Christ comes from the offspring of David and from Bethlehem, the town where David was?”

[[john-7-43]]
^43^ And so there arose a dissension among the multitude because of him.

[[john-7-44]]
^44^ Now certain ones among them wanted to apprehend him, but no one laid hands upon him.

[[john-7-45]]
^45^ Therefore, the attendants went to the high priests and the Pharisees. And they said to them, “Why have you not brought him?”

[[john-7-46]]
^46^ The attendants responded, “Never has a man spoken like this man.”

[[john-7-47]]
^47^ And so the Pharisees answered them: “Have you also been seduced?

[[john-7-48]]
^48^ Have any of the leaders believed in him, or any of the Pharisees?

[[john-7-49]]
^49^ But this crowd, which does not know the law, they are accursed.”

[[john-7-50]]
^50^ Nicodemus, the one who came to him by night and who was one of them, said to them,

[[john-7-51]]
^51^ “Does our law judge a man, unless it has first heard him and has known what he has done?”

[[john-7-52]]
^52^ They responded and said to him: “Are you also a Galilean? Study the Scriptures, and see that a prophet does not arise from Galilee.”

[[john-7-53]]
^53^ And each one returned to his own house.


[[john-8]]
== Chapter 8

[[john-8-1]]
^1^ But Jesus continued on to the Mount of Olives.

[[john-8-2]]
^2^ And early in the morning, he went again to the temple; and all the people came to him. And sitting down, he taught them.

[[john-8-3]]
^3^ Now the scribes and Pharisees brought forward a woman caught in adultery, and they stood her in front of them.

[[john-8-4]]
^4^ And they said to him: “Teacher, this woman was just now caught in adultery.

[[john-8-5]]
^5^ And in the law, Moses commanded us to stone such a one. Therefore, what do you say?”

[[john-8-6]]
^6^ But they were saying this to test him, so that they might be able to accuse him. Then Jesus bent down and wrote with his finger on the earth.

[[john-8-7]]
^7^ And then, when they persevered in questioning him, he stood upright and said to them, “Let whoever is without sin among you be the first to cast a stone at her.”

[[john-8-8]]
^8^ And bending down again, he wrote on the earth.

[[john-8-9]]
^9^ But upon hearing this, they went away, one by one, beginning with the eldest. And Jesus alone remained, with the woman standing in front of him.

[[john-8-10]]
^10^ Then Jesus, raising himself up, said to her: “Woman, where are those who accused you? Has no one condemned you?”

[[john-8-11]]
^11^ And she said, “No one, Lord.” Then Jesus said: “Neither will I condemn you. Go, and now do not choose to sin anymore.”

[[john-8-12]]
^12^ Then Jesus spoke to them again, saying: “I am the light of the world. Whoever follows me does not walk in darkness, but shall have the light of life.”

[[john-8-13]]
^13^ And so the Pharisees said to him, “You offer testimony about yourself; your testimony is not true.”

[[john-8-14]]
^14^ Jesus responded and said to them: “Even though I offer testimony about myself, my testimony is true, for I know where I came from and where I am going.

[[john-8-15]]
^15^ You judge according to the flesh. I do not judge anyone.

[[john-8-16]]
^16^ And when I do judge, my judgment is true. For I am not alone, but it is I and he who sent me: the Father.

[[john-8-17]]
^17^ And it is written in your law that the testimony of two men is true.

[[john-8-18]]
^18^ I am one who offers testimony about myself, and the Father who sent me offers testimony about me.”

[[john-8-19]]
^19^ Therefore, they said to him, “Where is your Father?” Jesus answered: “You know neither me, nor my Father. If you did know me, perhaps you would know my Father also.”

[[john-8-20]]
^20^ Jesus spoke these words at the treasury, while teaching in the temple. And no one apprehended him, because his hour had not yet come.

[[john-8-21]]
^21^ Therefore, Jesus again spoke to them: “I am going, and you shall seek me. And you will die in your sin. Where I am going, you are not able to go.”

[[john-8-22]]
^22^ And so the Jews said, “Is he going to kill himself, for he said: ‘Where I am going, you are not able to go?’ ”

[[john-8-23]]
^23^ And he said to them: “You are from below. I am from above. You are of this world. I am not of this world.

[[john-8-24]]
^24^ Therefore, I said to you, that you will die in your sins. For if you will not believe that I am, you will die in your sin.”

[[john-8-25]]
^25^ And so they said to him, “Who are you?” Jesus said to them: “The Beginning, who is also speaking to you.

[[john-8-26]]
^26^ I have much to say about you and to judge. But he who sent me is true. And what I have heard from him, this I speak within the world.”

[[john-8-27]]
^27^ And they did not realize that he was calling God his Father.

[[john-8-28]]
^28^ And so Jesus said to them: “When you will have lifted up the Son of man, then you shall realize that I am, and that I do nothing of myself, but just as the Father has taught me, so do I speak.

[[john-8-29]]
^29^ And he who sent me is with me, and he has not abandoned me alone. For I always do what is pleasing to him.”

[[john-8-30]]
^30^ As he was speaking these things, many believed in him.

[[john-8-31]]
^31^ Therefore, Jesus said to those Jews who believed in him: “If you will abide in my word, you will truly be my disciples.

[[john-8-32]]
^32^ And you shall know the truth, and the truth shall set you free.”

[[john-8-33]]
^33^ They answered him: “We are the offspring of Abraham, and we have never been a slave to anyone. How can you say, ‘You shall be set free?’ ”

[[john-8-34]]
^34^ Jesus answered them: “Amen, amen, I say to you, that everyone who commits sin is a slave of sin.

[[john-8-35]]
^35^ Now the slave does not abide in the house for eternity. Yet the Son does abide in eternity.

[[john-8-36]]
^36^ Therefore, if the Son has set you free, then you will truly be free.

[[john-8-37]]
^37^ I know that you are sons of Abraham. But you are seeking to kill me, because my word has not taken hold in you.

[[john-8-38]]
^38^ I speak what I have seen with my Father. And you do what you have seen with your father.”

[[john-8-39]]
^39^ They responded and said to him, “Abraham is our father.” Jesus said to them: “If you are the sons of Abraham, then do the works of Abraham.

[[john-8-40]]
^40^ But now you are seeking to kill me, a man who has spoken the truth to you, which I have heard from God. This is not what Abraham did.

[[john-8-41]]
^41^ You do the works of your father.” Therefore, they said to him: “We were not born out of fornication. We have one father: God.”

[[john-8-42]]
^42^ Then Jesus said to them: “If God were your father, certainly you would love me. For I proceeded and came from God. For I did not come from myself, but he sent me.

[[john-8-43]]
^43^ Why do you not recognize my speech? It is because you are not able to hear my word.

[[john-8-44]]
^44^ You are of your father, the devil. And you will carry out the desires of your father. He was a murderer from the beginning. And he did not stand in the truth, because the truth is not in him. When he speaks a lie, he speaks it from his own self. For he is a liar, and the father of lies.

[[john-8-45]]
^45^ But if I speak the truth, you do not believe me.

[[john-8-46]]
^46^ Which of you can convict me of sin? If I speak the truth to you, why do you not believe me?

[[john-8-47]]
^47^ Whoever is of God, hears the words of God. For this reason, you do not hear them: because you are not of God.”

[[john-8-48]]
^48^ Therefore, the Jews responded and said to him, “Are we not correct in saying that you are a Samaritan, and that you have a demon?”

[[john-8-49]]
^49^ Jesus responded: “I do not have a demon. But I honor my Father, and you have dishonored me.

[[john-8-50]]
^50^ But I am not seeking my own glory. There is One who seeks and judges.

[[john-8-51]]
^51^ Amen, amen, I say to you, if anyone will have kept my word, he will not see death for eternity.”

[[john-8-52]]
^52^ Therefore, the Jews said: “Now we know that you have a demon. Abraham is dead, and the Prophets; and yet you say, ‘If anyone will have kept my word, he shall not taste death for eternity.’

[[john-8-53]]
^53^ Are you greater than our father Abraham, who is dead? And the prophets are dead. So who do you make yourself to be?”

[[john-8-54]]
^54^ Jesus responded: “If I glorify myself, my glory is nothing. It is my Father who glorifies me. And you say about him that he is your God.

[[john-8-55]]
^55^ And yet you have not known him. But I know him. And if I were to say that I do not know him, then I would be like you, a liar. But I know him, and I keep his word.

[[john-8-56]]
^56^ Abraham, your father, rejoiced that he might see my day; he saw it and was glad.”

[[john-8-57]]
^57^ And so the Jews said to him, “You have not yet reached fifty years, and you have seen Abraham?”

[[john-8-58]]
^58^ Jesus said to them, “Amen, amen, I say to you, before Abraham was made, I am.”

[[john-8-59]]
^59^ Therefore, they took up stones to cast at him. But Jesus hid himself, and he departed from the temple.


[[john-9]]
== Chapter 9

[[john-9-1]]
^1^ And Jesus, while passing by, saw a man blind from birth.

[[john-9-2]]
^2^ And his disciples asked him, “Rabbi, who sinned, this man or his parents, that he would be born blind?”

[[john-9-3]]
^3^ Jesus responded: “Neither this man nor his parents sinned, but it was so that the works of God would be made manifest in him.

[[john-9-4]]
^4^ I must work the works of him who sent me, while it is day: the night is coming, when no one is able to work.

[[john-9-5]]
^5^ As long as I am in the world, I am the light of the world.”

[[john-9-6]]
^6^ When he had said these things, he spat on the ground, and he made clay from the spittle, and he smeared the clay over his eyes.

[[john-9-7]]
^7^ And he said to him: “Go, wash in the pool of Siloam” (which is translated as: one who has been sent). Therefore, he went away and washed, and he returned, seeing.

[[john-9-8]]
^8^ And so the bystanders and those who had seen him before, when he was a beggar, said, “Is this not the one who was sitting and begging?” Some said, “This is he.”

[[john-9-9]]
^9^ But others said, “Certainly not, but he is similar to him.” Yet truly, he himself said, “I am he.”

[[john-9-10]]
^10^ Therefore, they said to him, “How were your eyes opened?”

[[john-9-11]]
^11^ He responded: “That man who is called Jesus made clay, and he anointed my eyes and said to me, ‘Go to the pool of Siloam and wash.’ And I went, and I washed, and I see.”

[[john-9-12]]
^12^ And they said to him, “Where is he?” He said, “I do not know.”

[[john-9-13]]
^13^ They brought the one who had been blind to the Pharisees.

[[john-9-14]]
^14^ Now it was the Sabbath, when Jesus made the clay and opened his eyes.

[[john-9-15]]
^15^ Therefore, again the Pharisees questioned him as to how he had seen. And he said to them, “He placed clay over my eyes, and I washed, and I see.”

[[john-9-16]]
^16^ And so certain Pharisees said: “This man, who does not keep the Sabbath, is not from God.” But others said, “How could a sinful man accomplish these signs?” And there was a schism among them.

[[john-9-17]]
^17^ Therefore, they spoke again to the blind man, “What do you say about him who opened your eyes?” Then he said, “He is a Prophet.”

[[john-9-18]]
^18^ Therefore, the Jews did not believe, about him, that he had been blind and had seen, until they called the parents of him who had seen.

[[john-9-19]]
^19^ And they questioned them, saying: “Is this your son, whom you say was born blind? Then how is it that he now sees?”

[[john-9-20]]
^20^ His parents responded to them and said: “We know that this is our son and that he was born blind.

[[john-9-21]]
^21^ But how it is that he now sees, we do not know. And who opened his eyes, we do not know. Ask him. He is old enough. Let him speak for himself.”

[[john-9-22]]
^22^ His parents said these things because they were afraid of the Jews. For the Jews had already conspired, so that if anyone were to confess him to be the Christ, he would be expelled from the synagogue.

[[john-9-23]]
^23^ It was for this reason that his parents said: “He is old enough. Ask him.”

[[john-9-24]]
^24^ Therefore, they again called the man who had been blind, and they said to him: “Give glory to God. We know that this man is a sinner.”

[[john-9-25]]
^25^ And so he said to them: “If he is a sinner, I do not know it. One thing I do know, that although I was blind, now I see.”

[[john-9-26]]
^26^ Then they said to him: “What did he do to you? How did he open your eyes?”

[[john-9-27]]
^27^ He answered them: “I have already told you, and you heard it. Why do you want to hear it again? Do you also want to become his disciples?”

[[john-9-28]]
^28^ Therefore, they cursed him and said: “You be his disciple. But we are disciples of Moses.

[[john-9-29]]
^29^ We know that God spoke to Moses. But this man, we do not know where he is from.”

[[john-9-30]]
^30^ The man responded and said to them: “Now in this is a wonder: that you do not know where he is from, and yet he has opened my eyes.

[[john-9-31]]
^31^ And we know that God does not hear sinners. But if anyone is a worshipper of God and does his will, then he heeds him.

[[john-9-32]]
^32^ From ancient times, it has not been heard that anyone has opened the eyes of someone born blind.

[[john-9-33]]
^33^ Unless this man were of God, he would not be able to do any such thing.”

[[john-9-34]]
^34^ They responded and said to him, “You were born entirely in sins, and you would teach us?” And they cast him out.

[[john-9-35]]
^35^ Jesus heard that they had cast him out. And when he had found him, he said to him, “Do you believe in the Son of God?”

[[john-9-36]]
^36^ He responded and said, “Who is he, Lord, so that I may believe in him?”

[[john-9-37]]
^37^ And Jesus said to him, “You have both seen him, and he is the one who is speaking with you.”

[[john-9-38]]
^38^ And he said, “I believe, Lord.” And falling prostrate, he worshipped him.

[[john-9-39]]
^39^ And Jesus said, “I came into this world in judgment, so that those who do not see, may see; and so that those who see, may become blind.”

[[john-9-40]]
^40^ And certain Pharisees, who were with him, heard this, and they said to him, “Are we also blind?”

[[john-9-41]]
^41^ Jesus said to them: “If you were blind, you would not have sin. Yet now you say, ‘We see.’ So your sin persists.”


[[john-10]]
== Chapter 10

[[john-10-1]]
^1^ “Amen, amen, I say to you, he who does not enter through the door into the fold of the sheep, but climbs up by another way, he is a thief and a robber.

[[john-10-2]]
^2^ But he who enters through the door is the shepherd of the sheep.

[[john-10-3]]
^3^ To him the doorkeeper opens, and the sheep hear his voice, and he calls his own sheep by name, and he leads them out.

[[john-10-4]]
^4^ And when he has sent out his sheep, he goes before them, and the sheep follow him, because they know his voice.

[[john-10-5]]
^5^ But they do not follow a stranger; instead they flee from him, because they do not know the voice of strangers.”

[[john-10-6]]
^6^ Jesus spoke this proverb to them. But they did not understand what he was saying to them.

[[john-10-7]]
^7^ Therefore, Jesus spoke to them again: “Amen, amen, I say to you, that I am the door of the sheep.

[[john-10-8]]
^8^ All others, as many as have come, are thieves and robbers, and the sheep did not listen to them.

[[john-10-9]]
^9^ I am the door. If anyone has entered through me, he will be saved. And he shall go in and go out, and he shall find pastures.

[[john-10-10]]
^10^ The thief does not come, except so that he may steal and slaughter and destroy. I have come so that they may have life, and have it more abundantly.

[[john-10-11]]
^11^ I am the good Shepherd. The good Shepherd gives his life for his sheep.

[[john-10-12]]
^12^ But the hired hand, and whoever is not a shepherd, to whom the sheep do not belong, he sees the wolf approaching, and he departs from the sheep and flees. And the wolf ravages and scatters the sheep.

[[john-10-13]]
^13^ And the hired hand flees, because he is a hired hand and there is no concern for the sheep within him.

[[john-10-14]]
^14^ I am the good Shepherd, and I know my own, and my own know me,

[[john-10-15]]
^15^ just as the Father knows me, and I know the Father. And I lay down my life for my sheep.

[[john-10-16]]
^16^ And I have other sheep that are not of this fold, and I must lead them. They shall hear my voice, and there shall be one sheepfold and one shepherd.

[[john-10-17]]
^17^ For this reason, the Father loves me: because I lay down my life, so that I may take it up again.

[[john-10-18]]
^18^ No one takes it away from me. Instead, I lay it down of my own accord. And I have the power to lay it down. And I have the power to take it up again. This is the commandment that I have received from my Father.”

[[john-10-19]]
^19^ A dissension occurred again among the Jews because of these words.

[[john-10-20]]
^20^ Then many of them were saying: “He has a demon or he is insane. Why do you listen him?”

[[john-10-21]]
^21^ Others were saying: “These are not the words of someone who has a demon. How would a demon be able to open the eyes of the blind?”

[[john-10-22]]
^22^ Now it was the Feast of the Dedication at Jerusalem, and it was winter.

[[john-10-23]]
^23^ And Jesus was walking in the temple, in the portico of Solomon.

[[john-10-24]]
^24^ And so the Jews surrounded him and said to him: “How long will you hold our souls in suspense? If you are the Christ, tell us plainly.”

[[john-10-25]]
^25^ Jesus answered them: “I speak to you, and you do not believe. The works that I do in the name of my Father, these offer testimony about me.

[[john-10-26]]
^26^ But you do not believe, because you are not of my sheep.

[[john-10-27]]
^27^ My sheep hear my voice. And I know them, and they follow me.

[[john-10-28]]
^28^ And I give them eternal life, and they shall not perish, for eternity. And no one shall seize them from my hand.

[[john-10-29]]
^29^ What my Father gave to me is greater than all, and no one is able to seize from the hand of my Father.

[[john-10-30]]
^30^ I and the Father are one.”

[[john-10-31]]
^31^ Therefore, the Jews took up stones, in order to stone him.

[[john-10-32]]
^32^ Jesus answered them: “I have shown you many good works from my Father. For which of those works do you stone me?”

[[john-10-33]]
^33^ The Jews answered him: “We do not stone you for a good work, but for blasphemy and because, though you are a man, you make yourself God.”

[[john-10-34]]
^34^ Jesus responded to them: “Is it not written in your law, ‘I said: you are gods?’

[[john-10-35]]
^35^ If he called those to whom the word of God was given gods, and Scripture cannot be broken,

[[john-10-36]]
^36^ why do you say, about him whom the Father has sanctified and sent into the world, ‘You have blasphemed,’ because I said, ‘I am the Son of God?’

[[john-10-37]]
^37^ If I do not do the works of my Father, do not believe in me.

[[john-10-38]]
^38^ But if I do them, even if you are not willing to believe in me, believe the works, so that you may know and believe that the Father is in me, and I am in the Father.”

[[john-10-39]]
^39^ Therefore, they sought to apprehend him, but he escaped from their hands.

[[john-10-40]]
^40^ And he went again across the Jordan, to that place where John first was baptizing. And he lodged there.

[[john-10-41]]
^41^ And many went out to him. And they were saying: “Indeed, John accomplished no signs.

[[john-10-42]]
^42^ But all things whatsoever that John said about this man were true.” And many believed in him.


[[john-11]]
== Chapter 11

[[john-11-1]]
^1^ Now there was a certain sick man, Lazarus of Bethania, from the town of Mary and her sister Martha.

[[john-11-2]]
^2^ And Mary was the one who anointed the Lord with ointment and wiped his feet with her hair; her brother Lazarus was sick.

[[john-11-3]]
^3^ Therefore, his sisters sent to him, saying: “Lord, behold, he whom you love is sick.”

[[john-11-4]]
^4^ Then, upon hearing this, Jesus said to them: “This sickness is not unto death, but for the glory of God, so that the Son of God may be glorified by it.”

[[john-11-5]]
^5^ Now Jesus loved Martha, and her sister Mary, and Lazarus.

[[john-11-6]]
^6^ Even so, after he heard that he was sick, he then still remained in the same place for two days.

[[john-11-7]]
^7^ Then, after these things, he said to his disciples, “Let us go into Judea again.”

[[john-11-8]]
^8^ The disciples said to him: “Rabbi, the Jews are even now seeking to stone you. And would you go there again?”

[[john-11-9]]
^9^ Jesus responded: “Are there not twelve hours in the day? If anyone walks in the daylight, he does not stumble, because he sees the light of this world.

[[john-11-10]]
^10^ But if he walks in the nighttime, he stumbles, because the light is not in him.”

[[john-11-11]]
^11^ He said these things, and after this, he said to them: “Lazarus our friend is sleeping. But I am going, so that I may awaken him from sleep.”

[[john-11-12]]
^12^ And so his disciples said, “Lord, if he is sleeping, he shall be healthy.”

[[john-11-13]]
^13^ But Jesus had spoken about his death. Yet they thought that he spoke about the repose of sleep.

[[john-11-14]]
^14^ Therefore, Jesus then said to them plainly, “Lazarus has died.

[[john-11-15]]
^15^ And I am glad for your sake that I was not there, so that you may believe. But let us go to him.”

[[john-11-16]]
^16^ And then Thomas, who is called the Twin, said to his fellow disciples, “Let us go, too, so that we may die with him.”

[[john-11-17]]
^17^ And so Jesus went. And he found that he had already been in the tomb for four days.

[[john-11-18]]
^18^ (Now Bethania was near Jerusalem, about fifteen stadia.)

[[john-11-19]]
^19^ And many of the Jews had come to Martha and Mary, so as to console them over their brother.

[[john-11-20]]
^20^ Therefore, Martha, when she heard that Jesus was arriving, went out to meet him. But Mary was sitting at home.

[[john-11-21]]
^21^ And then Martha said to Jesus: “Lord, if you had been here, my brother would not have died.

[[john-11-22]]
^22^ But even now, I know that whatever you will request from God, God will give to you.”

[[john-11-23]]
^23^ Jesus said to her, “Your brother shall rise again.”

[[john-11-24]]
^24^ Martha said to him, “I know that he shall rise again, at the resurrection on the last day.”

[[john-11-25]]
^25^ Jesus said to her: “I am the Resurrection and the Life. Whoever believes in me, even though he has died, he shall live.

[[john-11-26]]
^26^ And everyone who lives and believes in me shall not die for eternity. Do you believe this?”

[[john-11-27]]
^27^ She said to him: “Certainly, Lord. I have believed that you are the Christ, the Son of the living God, who has come into this world.”

[[john-11-28]]
^28^ And when she had said these things, she went and called her sister Mary quietly, saying, “The Teacher is here, and he is calling you.”

[[john-11-29]]
^29^ When she heard this, she rose up quickly and went to him.

[[john-11-30]]
^30^ For Jesus had not yet arrived in the town. But he was still at that place where Martha had met him.

[[john-11-31]]
^31^ Therefore, the Jews who were with her in the house and who were consoling her, when they had seen that Mary rose up quickly and went out, they followed her, saying, “She is going to the tomb, so that she may weep there.”

[[john-11-32]]
^32^ Therefore, when Mary had arrived to where Jesus was, seeing him, she fell down at his feet, and she said to him. “Lord, if you had been here, my brother would not have died.”

[[john-11-33]]
^33^ And then, when Jesus saw her weeping, and the Jews who had arrived with her weeping, he groaned in spirit and became troubled.

[[john-11-34]]
^34^ And he said, “Where have you laid him?” They said to him, “Lord, come and see.”

[[john-11-35]]
^35^ And Jesus wept.

[[john-11-36]]
^36^ Therefore, the Jews said, “See how much he loved him!”

[[john-11-37]]
^37^ But some of them said, “Would not he who opened the eyes of one born blind have been able to cause this man not to die?”

[[john-11-38]]
^38^ Therefore, Jesus, again groaning from within himself, went to the tomb. Now it was a cave, and a stone had been placed over it.

[[john-11-39]]
^39^ Jesus said, “Take away the stone.” Martha, the sister of him who had died, said to him, “Lord, by now it will smell, for this is the fourth day.”

[[john-11-40]]
^40^ Jesus said to her, “Did I not say to you that if you believe, you shall see the glory of God?”

[[john-11-41]]
^41^ Therefore, they took away the stone. Then, lifting up his eyes, Jesus said: “Father, I give thanks to you because you have heard me.

[[john-11-42]]
^42^ And I know that you always hear me, but I have said this for the sake of the people who are standing nearby, so that they may believe that you have sent me.”

[[john-11-43]]
^43^ When he had said these things, he cried in a loud voice, “Lazarus, come out.”

[[john-11-44]]
^44^ And immediately, he who had been dead went forth, bound at the feet and hands with winding bands. And his face was bound with a separate cloth. Jesus said to them, “Release him and let him go.”

[[john-11-45]]
^45^ Therefore, many of the Jews, who had come to Mary and Martha, and who had seen the things that Jesus did, believed in him.

[[john-11-46]]
^46^ But certain ones among them went to the Pharisees and told them the things that Jesus had done.

[[john-11-47]]
^47^ And so, the high priests and the Pharisees gathered a council, and they were saying: “What can we do? For this man accomplishes many signs.

[[john-11-48]]
^48^ If we leave him alone, in this way all will believe in him. And then the Romans will come and take away our place and our nation.”

[[john-11-49]]
^49^ Then one of them, named Caiaphas, since he was the high priest that year, said to them: “You do not understand anything.

[[john-11-50]]
^50^ Nor do you realize that it is expedient for you that one man should die for the people, and that the entire nation should not perish.”

[[john-11-51]]
^51^ Yet he did not say this from himself, but since he was the high priest that year, he prophesied that Jesus would die for the nation.

[[john-11-52]]
^52^ And not only for the nation, but in order to gather together as one the children of God who have been dispersed.

[[john-11-53]]
^53^ Therefore, from that day, they planned to put him to death.

[[john-11-54]]
^54^ And so, Jesus no longer walked in public with the Jews. But he went into a region near the desert, to a city which is called Ephraim. And he lodged there with his disciples.

[[john-11-55]]
^55^ Now the Passover of the Jews was near. And many from the countryside ascended to Jerusalem before the Passover, so that they might sanctify themselves.

[[john-11-56]]
^56^ Therefore, they were seeking Jesus. And they conferred with one another, while standing in the temple: “What do you think? Will he come to the feast day?”

[[john-11-57]]
^57^ And the high priests and Pharisees had given an order, so that if anyone would know where he may be, he should reveal it, so that they might apprehend him.


[[john-12]]
== Chapter 12

[[john-12-1]]
^1^ Then six days before the Passover, Jesus went to Bethania, where Lazarus had died, whom Jesus raised up.

[[john-12-2]]
^2^ And they made a dinner for him there. And Martha was ministering. And truly, Lazarus was one of those who were sitting at table with him.

[[john-12-3]]
^3^ And then Mary took twelve ounces of pure spikenard ointment, very precious, and she anointed the feet of Jesus, and she wiped his feet with her hair. And the house was filled with the fragrance of the ointment.

[[john-12-4]]
^4^ Then one of his disciples, Judas Iscariot, who was soon to betray him, said,

[[john-12-5]]
^5^ “Why was this ointment not sold for three hundred denarii and given to the needy?”

[[john-12-6]]
^6^ Now he said this, not out of concern for the needy, but because he was a thief and, since he held the purse, he used to carry what was put into it.

[[john-12-7]]
^7^ But Jesus said: “Permit her, so that she may keep it against the day of my burial.

[[john-12-8]]
^8^ For the poor, you have with you always. But me, you do always not have.”

[[john-12-9]]
^9^ Now a great multitude of the Jews knew that he was in that place, and so they came, not so much because of Jesus, but so that they might see Lazarus, whom he had raised from the dead.

[[john-12-10]]
^10^ And the leaders of the priests planned to put Lazarus to death also.

[[john-12-11]]
^11^ For many of the Jews, because of him, were going away and were believing in Jesus.

[[john-12-12]]
^12^ Then, on the next day, the great crowd that had come to the feast day, when they had heard that Jesus was coming to Jerusalem,

[[john-12-13]]
^13^ took branches of palm trees, and they went ahead to meet him. And they were crying out: “Hosanna! Blessed is he who arrives in the name of the Lord, the king of Israel!”

[[john-12-14]]
^14^ And Jesus found a small donkey, and he sat upon it, just as it is written:

[[john-12-15]]
^15^ “Do not be afraid, daughter of Zion. Behold, your king arrives, sitting on the colt of a donkey.”

[[john-12-16]]
^16^ At first, his disciples did not realize these things. But when Jesus was glorified, then they remembered that these things were written about him, and that these things happened to him.

[[john-12-17]]
^17^ And so the crowd that had been with him, when he called Lazarus from the tomb and raised him from the dead, offered testimony.

[[john-12-18]]
^18^ Because of this, too, the crowd went out to meet him. For they heard that he had accomplished this sign.

[[john-12-19]]
^19^ Therefore, the Pharisees said among themselves: “Do you see that we are accomplishing nothing? Behold, the entire world has gone after him.”

[[john-12-20]]
^20^ Now there were certain Gentiles among those who went up so that they might worship on the feast day.

[[john-12-21]]
^21^ Therefore, these approached Philip, who was from Bethsaida of Galilee, and they petitioned him, saying: “Sir, we want to see Jesus.”

[[john-12-22]]
^22^ Philip went and told Andrew. Next, Andrew and Philip told Jesus.

[[john-12-23]]
^23^ But Jesus answered them by saying: “The hour arrives when the Son of man shall be glorified.

[[john-12-24]]
^24^ Amen, amen, I say to you, unless the grain of wheat falls to the ground and dies,

[[john-12-25]]
^25^ it remains alone. But if it dies, it yields much fruit. Whoever loves his life, will lose it. And whoever hates his life in this world, preserves it unto eternal life.

[[john-12-26]]
^26^ If anyone serves me, let him follow me. And where I am, there too my minister shall be. If anyone has served me, my Father will honor him.

[[john-12-27]]
^27^ Now my soul is troubled. And what should I say? Father, save me from this hour? But it is for this reason that I came to this hour.

[[john-12-28]]
^28^ Father, glorify your name!” And then a voice came from heaven, “I have glorified it, and I will glorify it again.”

[[john-12-29]]
^29^ Therefore, the crowd, which was standing near and had heard it, said that it was like thunder. Others were saying, “An Angel was speaking with him.”

[[john-12-30]]
^30^ Jesus responded and said: “This voice came, not for my sake, but for your sakes.

[[john-12-31]]
^31^ Now is the judgment of the world. Now will the prince of this world be cast out.

[[john-12-32]]
^32^ And when I have been lifted up from the earth, I will draw all things to myself.”

[[john-12-33]]
^33^ (Now he said this, signifying what kind of death he would die.)

[[john-12-34]]
^34^ The crowd answered him: “We have heard, from the law, that the Christ remains forever. And so how can you say, ‘The Son of man must be lifted up?’ Who is this Son of man?”

[[john-12-35]]
^35^ Therefore, Jesus said to them: “For a brief time, the Light is among you. Walk while you have the Light, so that the darkness may not overtake you. But whoever walks in darkness does not know where is he going.

[[john-12-36]]
^36^ While you have the Light, believe in the Light, so that you may be sons of the Light.” Jesus spoke these things, and then he went away and hid himself from them.

[[john-12-37]]
^37^ And although he had done such great signs in their presence, they did not believe in him,

[[john-12-38]]
^38^ so that the word of the prophet Isaiah might be fulfilled, which says: “Lord, who has believed in our hearing? And to whom has the arm of the Lord been revealed?”

[[john-12-39]]
^39^ Because of this, they were not able to believe, for Isaiah said again:

[[john-12-40]]
^40^ “He has blinded their eyes, and hardened their heart, so that they may not see with their eyes, and understand with their heart, and be converted: and then I would heal them.”

[[john-12-41]]
^41^ These things Isaiah said, when he saw his glory and was speaking about him.

[[john-12-42]]
^42^ Yet truly, many of the leaders also believed in him. But because of the Pharisees, they did not confess him, so that they would not be cast out of the synagogue.

[[john-12-43]]
^43^ For they loved the glory of men more than the glory of God.

[[john-12-44]]
^44^ But Jesus cried out and said: “Whoever believes in me, does not believe in me, but in him who sent me.

[[john-12-45]]
^45^ And whoever sees me, sees him who sent me.

[[john-12-46]]
^46^ I have arrived as a light to the world, so that all who believe in me might not remain in darkness.

[[john-12-47]]
^47^ And if anyone has heard my words and not kept them, I do not judge him. For I did not come so that I may judge the world, but so that I may save the world.

[[john-12-48]]
^48^ Whoever despises me and does not accept my words has one who judges him. The word that I have spoken, the same shall judge him on the last day.

[[john-12-49]]
^49^ For I am not speaking from myself, but from the Father who sent me. He gave a commandment to me as to what I should say and how I should speak.

[[john-12-50]]
^50^ And I know that his commandment is eternal life. Therefore, the things that I speak, just as the Father has said to me, so also do I speak.”


[[john-13]]
== Chapter 13

[[john-13-1]]
^1^ Before the feast day of the Passover, Jesus knew that the hour was approaching when he would pass from this world to the Father. And since he had always loved his own who were in the world, he loved them unto the end.

[[john-13-2]]
^2^ And when the meal had taken place, when the devil had now put it into the heart of Judas Iscariot, the son of Simon, to betray him,

[[john-13-3]]
^3^ knowing that the Father had given all things into his hands and that he came from God and was going to God,

[[john-13-4]]
^4^ he rose up from the meal, and he set aside his vestments, and when he had received a towel, he wrapped it around himself.

[[john-13-5]]
^5^ Next he put water into a shallow bowl, and he began to wash the feet of the disciples and to wipe them with the towel with which he was wrapped.

[[john-13-6]]
^6^ And then he came to Simon Peter. And Peter said to him, “Lord, would you wash my feet?”

[[john-13-7]]
^7^ Jesus responded and said to him: “What I am doing, you do not now understand. But you shall understand it afterward.”

[[john-13-8]]
^8^ Peter said to him, “You shall never wash my feet!” Jesus answered him, “If I do not wash you, you will have no place with me.”

[[john-13-9]]
^9^ Simon Peter said to him, “Then Lord, not only my feet, but also my hands and my head!”

[[john-13-10]]
^10^ Jesus said to him: “He who is washed need only wash his feet, and then he will be entirely clean. And you are clean, but not all.”

[[john-13-11]]
^11^ For he knew which one would betray him. For this reason, he said, “You are not all clean.”

[[john-13-12]]
^12^ And so, after he washed their feet and received his vestments, when he had sat down at table again, he said to them: “Do you know what I have done for you?

[[john-13-13]]
^13^ You call me Teacher and Lord, and you speak well: for so I am.

[[john-13-14]]
^14^ Therefore, if I, your Lord and Teacher, have washed your feet, you also ought to wash the feet of one another.

[[john-13-15]]
^15^ For I have given you an example, so that just as I have done for you, so also should you do.

[[john-13-16]]
^16^ Amen, amen, I say to you, the servant is not greater than his Lord, and the apostle is not greater than he who sent him.

[[john-13-17]]
^17^ If you understand this, you shall be blessed if you will do it.

[[john-13-18]]
^18^ I am not speaking about all of you. I know those whom I have chosen. But this is so that the Scripture may be fulfilled, ‘He who eats bread with me shall lift up his heel against me.’

[[john-13-19]]
^19^ And I tell you this now, before it happens, so that when it has happened, you may believe that I am.

[[john-13-20]]
^20^ Amen, amen, I say to you, whoever receives anyone whom I send, receives me. And whoever receives me, receives him who sent me.”

[[john-13-21]]
^21^ When Jesus had said these things, he was troubled in spirit. And he bore witness by saying: “Amen, amen, I say to you, that one among you shall betray me.”

[[john-13-22]]
^22^ Therefore, the disciples looked around at one another, uncertain about whom he spoke.

[[john-13-23]]
^23^ And leaning against the bosom of Jesus was one of his disciples, the one whom Jesus loved.

[[john-13-24]]
^24^ Therefore, Simon Peter motioned to this one and said to him, “Who is it that he is speaking about?”

[[john-13-25]]
^25^ And so, leaning against the chest of Jesus, he said to him, “Lord, who is it?”

[[john-13-26]]
^26^ Jesus responded, “It is he to whom I shall extend the dipped bread.” And when he had dipped the bread, he gave it to Judas Iscariot, son of Simon.

[[john-13-27]]
^27^ And after the morsel, Satan entered into him. And Jesus said to him, “What you are going to do, do quickly.”

[[john-13-28]]
^28^ Now none of those sitting at table knew why he had said this to him.

[[john-13-29]]
^29^ For some were thinking that, because Judas held the purse, that Jesus had told him, “Buy those things which are needed by us for the feast day,” or that he might give something to the needy.

[[john-13-30]]
^30^ Therefore, having accepted the morsel, he went out immediately. And it was night.

[[john-13-31]]
^31^ Then, when he had gone out, Jesus said: “Now the Son of man has been glorified, and God has been glorified in him.

[[john-13-32]]
^32^ If God has been glorified in him, then God will also glorify him in himself, and he will glorify him without delay.

[[john-13-33]]
^33^ Little sons, for a brief while, I am with you. You shall seek me, and just as I said to the Jews, ‘Where I am going, you are not able to go,’ so also I say to you now.

[[john-13-34]]
^34^ I give you a new commandment: Love one another. Just as I have loved you, so also must you love one another.

[[john-13-35]]
^35^ By this, all shall recognize that you are my disciples: if you will have love for one another.”

[[john-13-36]]
^36^ Simon Peter said to him, “Lord, where are you going?” Jesus responded: “Where I am going, you are not able to follow me now. But you shall follow afterward.”

[[john-13-37]]
^37^ Peter said to him: “Why am I unable to follow you now? I will lay down my life for you!”

[[john-13-38]]
^38^ Jesus answered him: “You will lay down your life for me? Amen, amen, I say to you, the rooster will not crow, until you deny me three times.”


[[john-14]]
== Chapter 14

[[john-14-1]]
^1^ “Do not let your heart be troubled. You believe in God. Believe in me also.

[[john-14-2]]
^2^ In my Father’s house, there are many dwelling places. If there were not, I would have told you. For I go to prepare a place for you.

[[john-14-3]]
^3^ And if I go and prepare a place for you, I will return again, and then I will take you to myself, so that where I am, you also may be.

[[john-14-4]]
^4^ And you know where I am going. And you know the way.”

[[john-14-5]]
^5^ Thomas said to him, “Lord, we do not know where you are going, so how can we know the way?”

[[john-14-6]]
^6^ Jesus said to him: “I am the Way, and the Truth, and the Life. No one comes to the Father, except through me.

[[john-14-7]]
^7^ If you had known me, certainly you would also have known my Father. And from now on, you shall know him, and you have seen him.”

[[john-14-8]]
^8^ Philip said to him, “Lord, reveal the Father to us, and it is enough for us.”

[[john-14-9]]
^9^ Jesus said to him: “Have I been with you for so long, and you have not known me? Philip, whoever sees me, also sees the Father. How can you say, ‘Reveal the Father to us?’

[[john-14-10]]
^10^ Do you not believe that I am in the Father and the Father is in me? The words that I am speaking to you, I do not speak from myself. But the Father abiding in me, he does these works.

[[john-14-11]]
^11^ Do you not believe that I am in the Father and the Father is in me?

[[john-14-12]]
^12^ Or else, believe because of these same works. Amen, amen, I say to you, whoever believes in me shall also do the works that I do. And greater things than these shall he do, for I go to the Father.

[[john-14-13]]
^13^ And whatever you shall ask the Father in my name, that I will do, so that the Father may be glorified in the Son.

[[john-14-14]]
^14^ If you shall ask anything of me in my name, that I will do.

[[john-14-15]]
^15^ If you love me, keep my commandments.

[[john-14-16]]
^16^ And I will ask the Father, and he will give another Advocate to you, so that he may abide with you for eternity:

[[john-14-17]]
^17^ the Spirit of Truth, whom the world is not able to accept, because it neither perceives him nor knows him. But you shall know him. For he will remain with you, and he will be in you.

[[john-14-18]]
^18^ I will not leave you orphans. I will return to you.

[[john-14-19]]
^19^ Yet a little while and the world will not see me any longer. But you will see me. For I live, and you shall live.

[[john-14-20]]
^20^ In that day, you shall know that I am in my Father, and you are in me, and I am in you.

[[john-14-21]]
^21^ Whoever holds to my commandments and keeps them: it is he who loves me. And whoever loves me shall be loved by my Father. And I will love him, and I will manifest myself to him.”

[[john-14-22]]
^22^ Judas, not the Iscariot, said to him: “Lord, how does it happen that you will manifest yourself to us and not to the world?”

[[john-14-23]]
^23^ Jesus responded and said to him: “If anyone loves me, he shall keep my word. And my Father will love him, and we will come to him, and we will make our dwelling place with him.

[[john-14-24]]
^24^ Whoever does not love me, does not keep not my words. And the word that you have heard is not of me, but it is of the Father who sent me.

[[john-14-25]]
^25^ These things I have spoken to you, while abiding with you.

[[john-14-26]]
^26^ But the Advocate, the Holy Spirit, whom the Father will send in my name, will teach you all things and will suggest to you everything whatsoever that I have said to you.

[[john-14-27]]
^27^ Peace I leave for you; my Peace I give to you. Not in the way that the world gives, do I give to you. Do not let your heart be troubled, and let it not fear.

[[john-14-28]]
^28^ You have heard that I said to you: I am going away, and I am returning to you. If you loved me, certainly you would be gladdened, because I am going to the Father. For the Father is greater than I.

[[john-14-29]]
^29^ And now I have told you this, before it happens, so that, when it will happen, you may believe.

[[john-14-30]]
^30^ I will not now speak at length with you. For the prince of this world is coming, but he does not have anything in me.

[[john-14-31]]
^31^ Yet this is so that the world may know that I love the Father, and that I am acting according to the commandment that the Father has given to me. Rise up, let us go from here.”


[[john-15]]
== Chapter 15

[[john-15-1]]
^1^ “I am the true vine, and my Father is the vinedresser.

[[john-15-2]]
^2^ Every branch in me that does not bear fruit, he will take away. And each one that does bear fruit, he will cleanse, so that it may bring forth more fruit.

[[john-15-3]]
^3^ You are clean now, because of the word that I have spoken to you.

[[john-15-4]]
^4^ Abide in me, and I in you. Just as the branch is not able to bear fruit of itself, unless it abides in the vine, so also are you unable, unless you abide in me.

[[john-15-5]]
^5^ I am the vine; you are the branches. Whoever abides in me, and I in him, bears much fruit. For without me, you are able to do nothing.

[[john-15-6]]
^6^ If anyone does not abide in me, he will be cast away, like a branch, and he will wither, and they will gather him and cast him into the fire, and he burns.

[[john-15-7]]
^7^ If you abide in me, and my words abide in you, then you may ask for whatever you will, and it shall be done for you.

[[john-15-8]]
^8^ In this, my Father is glorified: that you should bring forth very much fruit and become my disciples.

[[john-15-9]]
^9^ As the Father has loved me, so I have loved you. Abide in my love.

[[john-15-10]]
^10^ If you keep my precepts, you shall abide in my love, just as I also have kept my Father’s precepts and I abide in his love.

[[john-15-11]]
^11^ These things I have spoken to you, so that my joy may be in you, and your joy may be fulfilled.

[[john-15-12]]
^12^ This is my precept: that you love one another, just as I have loved you.

[[john-15-13]]
^13^ No one has a greater love than this: that he lay down his life for his friends.

[[john-15-14]]
^14^ You are my friends, if you do what I instruct you.

[[john-15-15]]
^15^ I will no longer call you servants, for the servant does not know what his Lord is doing. But I have called you friends, because everything whatsoever that I have heard from my Father, I have made known to you.

[[john-15-16]]
^16^ You have not chosen me, but I have chosen you. And I have appointed you, so that you may go forth and bear fruit, and so that your fruit may last. Then whatever you have asked of the Father in my name, he shall give to you.

[[john-15-17]]
^17^ This I command you: that you love one another.

[[john-15-18]]
^18^ If the world hates you, know that it has hated me before you.

[[john-15-19]]
^19^ If you had been of the world, the world would love what is its own. Yet truly, you are not of the world, but I have chosen you out of the world; because of this, the world hates you.

[[john-15-20]]
^20^ Remember my saying that I told you: The servant is not greater than his Lord. If they have persecuted me, they will persecute you also. If they have kept my word, they will keep yours also.

[[john-15-21]]
^21^ But all these things they will do to you because of my name, for they do not know him who sent me.

[[john-15-22]]
^22^ If I had not come and had not spoken to them, they would not have sin. But now they have no excuse for their sin.

[[john-15-23]]
^23^ Whoever hates me, hates my Father also.

[[john-15-24]]
^24^ If I had not accomplished among them works that no other person has accomplished, they would not have sin. But now they have both seen me, and they have hated me and my Father.

[[john-15-25]]
^25^ But this is so that the word may be fulfilled which was written in their law: ‘For they hated me without cause.’

[[john-15-26]]
^26^ But when the Advocate has arrived, whom I will send to you from the Father, the Spirit of truth who proceeds from the Father, he will offer testimony about me.

[[john-15-27]]
^27^ And you shall offer testimony, because you are with me from the beginning.”


[[john-16]]
== Chapter 16

[[john-16-1]]
^1^ “These things I have spoken to you, so that you would not stumble.

[[john-16-2]]
^2^ They will put you out of the synagogues. But the hour is coming when everyone who puts you to death will consider that he is offering an excellent service to God.

[[john-16-3]]
^3^ And they will do these things to you because they have not known the Father, nor me.

[[john-16-4]]
^4^ But these things I have spoken to you, so that, when the hour for these things will have arrived, you may remember that I told you.

[[john-16-5]]
^5^ But I did not tell you these things from the beginning, because I was with you. And now I am going to him who sent me. And no one among you has asked me, ‘Where are you going?’

[[john-16-6]]
^6^ But because I have spoken these things to you, sorrow has filled your heart.

[[john-16-7]]
^7^ But I tell you the truth: it is expedient for you that I am going. For if I do not go, the Advocate will not come to you. But when I will have gone away, I will send him to you.

[[john-16-8]]
^8^ And when he has arrived, he will argue against the world, about sin and about justice and about judgment:

[[john-16-9]]
^9^ about sin, indeed, because they have not believed in me;

[[john-16-10]]
^10^ about justice, truly, because I am going to the Father, and you will not see me any longer;

[[john-16-11]]
^11^ about judgment, then, because the prince of this world has already been judged.

[[john-16-12]]
^12^ I still have many things to say to you, but you are not able to bear them now.

[[john-16-13]]
^13^ But when the Spirit of truth has arrived, he will teach the whole truth to you. For he will not be speaking from himself. Instead, whatever he will hear, he will speak. And he will announce to you the things that are to come.

[[john-16-14]]
^14^ He shall glorify me. For he will receive from what is mine, and he will announce it to you.

[[john-16-15]]
^15^ All things whatsoever that the Father has are mine. For this reason, I said that he will receive from what is mine and that he will announce it to you.

[[john-16-16]]
^16^ A little while, and then you will not see me. And again a little while, and you will see me. For I am going to the Father.”

[[john-16-17]]
^17^ Then some of his disciples said to one another: “What is this, that he is saying to us: ‘A little while, and you will not see me,’ and ‘Again a little while, and you will see me,’ and, ‘For I am going to the Father?’ ”

[[john-16-18]]
^18^ And they said: “What is this, that he is saying, ‘A little while?’ We do not understand what he is saying.”

[[john-16-19]]
^19^ But Jesus realized that they wanted to question him, and so he said to them: “Are you inquiring among yourselves about this, that I said: ‘A little while, and you will not see me, and again a little while, and you will see me?’

[[john-16-20]]
^20^ Amen, amen, I say to you, that you shall mourn and weep, but the world will rejoice. And you shall be greatly saddened, yet your sorrow shall be turned into joy.

[[john-16-21]]
^21^ A woman, when she is giving birth, has sorrow, because her hour has arrived. But when she has given birth to the child, then she no longer remembers the difficulties, because of the joy: for a man has been born into the world.

[[john-16-22]]
^22^ Therefore, you also, indeed, have sorrow now. But I will see you again, and your heart shall rejoice. And no one will take away your joy from you.

[[john-16-23]]
^23^ And, in that day, you will not petition me for anything. Amen, amen, I say to you, if you ask the Father for anything in my name, he will give it to you.

[[john-16-24]]
^24^ Until now, you have not requested anything in my name. Ask, and you shall receive, so that your joy may be full.

[[john-16-25]]
^25^ I have spoken these things to you in proverbs. The hour is coming when I will no longer speak to you in proverbs; instead, I will announce to you plainly from the Father.

[[john-16-26]]
^26^ In that day, you shall ask in my name, and I do not say to you that I will ask the Father for you.

[[john-16-27]]
^27^ For the Father himself loves you, because you have loved me, and because you have believed that I went forth from God.

[[john-16-28]]
^28^ I went forth from the Father, and I have come into the world. Next I am leaving the world, and I am going to the Father.”

[[john-16-29]]
^29^ His disciples said to him: “Behold, now you are speaking plainly and not reciting a proverb.

[[john-16-30]]
^30^ Now we know that you know all things, and that you have no need for anyone to question you. By this, we believe that you went forth from God.”

[[john-16-31]]
^31^ Jesus answered them: “Do you believe now?

[[john-16-32]]
^32^ Behold, the hour is coming, and it has now arrived, when you will be scattered, each one on his own, and you will leave me behind, alone. And yet I am not alone, for the Father is with me.

[[john-16-33]]
^33^ These things I have spoken to you, so that you may have peace in me. In the world, you will have difficulties. But have confidence: I have overcome the world.”


[[john-17]]
== Chapter 17

[[john-17-1]]
^1^ Jesus said these things, and then, lifting up his eyes toward heaven, he said: “Father, the hour has arrived: glorify your Son, so that your Son may glorify you,

[[john-17-2]]
^2^ just as you have given authority over all flesh to him, so that he may give eternal life to all those whom you have given to him.

[[john-17-3]]
^3^ And this is eternal life: that they may know you, the only true God, and Jesus Christ, whom you have sent.

[[john-17-4]]
^4^ I have glorified you on earth. I have completed the work that you gave me to accomplish.

[[john-17-5]]
^5^ And now Father, glorify me within yourself, with the glory that I had with you before the world ever was.

[[john-17-6]]
^6^ I have manifested your name to the men whom you have given to me from the world. They were yours, and you gave them to me. And they have kept your word.

[[john-17-7]]
^7^ Now they realize that all the things that you have given me are from you.

[[john-17-8]]
^8^ For I have given them the words that you gave to me. And they have accepted these words, and they have truly understood that I went forth from you, and they have believed that you sent me.

[[john-17-9]]
^9^ I pray for them. I do not pray for the world, but for those whom you have given to me. For they are yours.

[[john-17-10]]
^10^ And all that is mine is yours, and all that is yours is mine, and I am glorified in this.

[[john-17-11]]
^11^ And though I am not in the world, these are in the world, and I am coming to you. Father most holy, preserve them in your name, those whom you have given to me, so that they may be one, even as we are one.

[[john-17-12]]
^12^ While I was with them, I preserved them in your name. I have guarded those whom you have given to me, and not one of them is lost, except the son of perdition, so that the Scripture may be fulfilled.

[[john-17-13]]
^13^ And now I am coming to you. But I am speaking these things in the world, so that they may have the fullness of my joy within themselves.

[[john-17-14]]
^14^ I have given them your word, and the world has hated them. For they are not of the world, just as I, too, am not of the world.

[[john-17-15]]
^15^ I am not praying that you would take them out of the world, but that you would preserve them from evil.

[[john-17-16]]
^16^ They are not of the world, just as I also am not of the world.

[[john-17-17]]
^17^ Sanctify them in truth. Your word is truth.

[[john-17-18]]
^18^ Just as you have sent me into the world, I also have sent them into the world.

[[john-17-19]]
^19^ And it is for them that I sanctify myself, so that they, too, may be sanctified in truth.

[[john-17-20]]
^20^ But I am not praying for them only, but also for those who through their word shall believe in me.

[[john-17-21]]
^21^ So may they all be one. Just as you, Father, are in me, and I am in you, so also may they be one in us: so that the world may believe that you have sent me.

[[john-17-22]]
^22^ And the glory that you have given to me, I have given to them, so that they may be one, just as we also are one.

[[john-17-23]]
^23^ I am in them, and you are in me. So may they be perfected as one. And may the world know that you have sent me and that you have loved them, just as you have also loved me.

[[john-17-24]]
^24^ Father, I will that where I am, those whom you have given to me may also be with me, so that they may see my glory which you have given to me. For you loved me before the founding of the world.

[[john-17-25]]
^25^ Father most just, the world has not known you. But I have known you. And these have known that you sent me.

[[john-17-26]]
^26^ And I have made known your name to them, and I will make it known, so that the love in which you have loved me may be in them, and so that I may be in them.”


[[john-18]]
== Chapter 18

[[john-18-1]]
^1^ When Jesus had said these things, he departed with his disciples across the Torrent of Kidron, where there was a garden, into which he entered with his disciples.

[[john-18-2]]
^2^ But Judas, who betrayed him, also knew the place, for Jesus had frequently met with his disciples there.

[[john-18-3]]
^3^ Then Judas, when he had received a cohort from both the high priests and the attendants of the Pharisees, approached the place with lanterns and torches and weapons.

[[john-18-4]]
^4^ And so Jesus, knowing all that was about to happen to him, advanced and said to them, “Who are you seeking?”

[[john-18-5]]
^5^ They answered him, “Jesus the Nazarene.” Jesus said to them, “I am he.” Now Judas, who betrayed him, was also standing with them.

[[john-18-6]]
^6^ Then, when he said to them, “I am he,” they moved back and fell to the ground.

[[john-18-7]]
^7^ Then again he questioned them: “Who are you seeking?” And they said, “Jesus the Nazarene.”

[[john-18-8]]
^8^ Jesus responded: “I told you that I am he. Therefore, if you are seeking me, permit these others to go away.”

[[john-18-9]]
^9^ This was so that the word might be fulfilled, which he said, “Of those whom you have given to me, I have not lost any of them.”

[[john-18-10]]
^10^ Then Simon Peter, having a sword, drew it, and he struck the servant of the high priest, and he cut off his right ear. Now the name of the servant was Malchus.

[[john-18-11]]
^11^ Therefore, Jesus said to Peter: “Set your sword into the scabbard. Should I not drink the chalice which my Father has given to me?”

[[john-18-12]]
^12^ Then the cohort, and the tribune, and the attendants of the Jews apprehended Jesus and bound him.

[[john-18-13]]
^13^ And they led him away, first to Annas, for he was the father-in-law of Caiaphas, who was the high priest that year.

[[john-18-14]]
^14^ Now Caiaphas was the one who had given counsel to the Jews that it was expedient for one man to die for the people.

[[john-18-15]]
^15^ And Simon Peter was following Jesus with another disciple. And that disciple was known to the high priest, and so he entered with Jesus into the court of the high priest.

[[john-18-16]]
^16^ But Peter was standing outside at the entrance. Therefore, the other disciple, who was known to the high priest, went out and spoke to the woman who was the doorkeeper, and he led in Peter.

[[john-18-17]]
^17^ Therefore, the woman servant keeping the door said to Peter, “Are you not also among the disciples of this man?” He said, “I am not.”

[[john-18-18]]
^18^ Now the servants and attendants were standing before burning coals, for it was cold, and they were warming themselves. And Peter was standing with them also, warming himself.

[[john-18-19]]
^19^ Then the high priest questioned Jesus about his disciples and about his doctrine.

[[john-18-20]]
^20^ Jesus responded to him: “I have spoken openly to the world. I have always taught in the synagogue and in the temple, where all the Jews meet. And I have said nothing in secret.

[[john-18-21]]
^21^ Why do you question me? Question those who heard what I said to them. Behold, they know these things that I have said.”

[[john-18-22]]
^22^ Then, when he had said this, one of the attendants standing nearby struck Jesus, saying: “Is this the way you answer the high priest?”

[[john-18-23]]
^23^ Jesus answered him: “If I have spoken wrongly, offer testimony about the wrong. But if I have spoken correctly, then why do you strike me?”

[[john-18-24]]
^24^ And Annas sent him bound to Caiaphas, the high priest.

[[john-18-25]]
^25^ Now Simon Peter was standing and warming himself. Then they said to him, “Are you not also one of his disciples?” He denied it and said, “I am not.”

[[john-18-26]]
^26^ One of the servants of the high priest (a relative of him whose ear Peter had cut off) said to him, “Did I not see you in the garden with him?”

[[john-18-27]]
^27^ Therefore, again, Peter denied it. And immediately the rooster crowed.

[[john-18-28]]
^28^ Then they led Jesus from Caiaphas into the praetorium. Now it was morning, and so they did not enter into the praetorium, so that they would not be defiled, but might eat the Passover.

[[john-18-29]]
^29^ Therefore, Pilate went outside to them, and he said, “What accusation are you bringing against this man?”

[[john-18-30]]
^30^ They responded and said to him, “If he were not an evil-doer, we would not have handed him over to you.”

[[john-18-31]]
^31^ Therefore, Pilate said to them, “Take him yourselves and judge him according to your own law.” Then the Jews said to him, “It is not lawful for us to execute anyone.”

[[john-18-32]]
^32^ This was so that the word of Jesus would be fulfilled, which he spoke signifying what kind of death he would die.

[[john-18-33]]
^33^ Then Pilate entered the praetorium again, and he called Jesus and said to him, “You are the king of the Jews?”

[[john-18-34]]
^34^ Jesus responded, “Are you saying this of yourself, or have others spoken to you about me?”

[[john-18-35]]
^35^ Pilate responded: “Am I a Jew? Your own nation and the high priests have handed you over to me. What have you done?”

[[john-18-36]]
^36^ Jesus responded: “My kingdom is not of this world. If my kingdom were of this world, my ministers would certainly strive so that I would not be handed over to the Jews. But my kingdom is not now from here.”

[[john-18-37]]
^37^ And so Pilate said to him, “You are a king, then?” Jesus answered, “You are saying that I am a king. For this I was born, and for this I came into the world: so that I may offer testimony to the truth. Everyone who is of the truth hears my voice.”

[[john-18-38]]
^38^ Pilate said to him, “What is truth?” And when he had said this, he went out again to the Jews, and he said to them, “I find no case against him.

[[john-18-39]]
^39^ But you have a custom, that I should release someone to you at the Passover. Therefore, do you want me to release to you the king of the Jews?”

[[john-18-40]]
^40^ Then they all cried out repeatedly, saying: “Not this one, but Barabbas.” Now Barabbas was a robber.


[[john-19]]
== Chapter 19

[[john-19-1]]
^1^ Therefore, Pilate then took Jesus into custody and scourged him.

[[john-19-2]]
^2^ And the soldiers, plaiting a crown of thorns, imposed it on his head. And they put a purple garment around him.

[[john-19-3]]
^3^ And they were approaching him and saying, “Hail, king of the Jews!” And they struck him repeatedly.

[[john-19-4]]
^4^ Then Pilate went outside again, and he said to them: “Behold, I am bringing him out to you, so that you may realize that I find no case against him.”

[[john-19-5]]
^5^ (Then Jesus went out, bearing the crown of thorns and the purple garment.) And he said to them, “Behold the man.”

[[john-19-6]]
^6^ Therefore, when the high priests and the attendants had seen him, they cried out, saying: “Crucify him! Crucify him!” Pilate said to them: “Take him yourselves and crucify him. For I find no case against him.”

[[john-19-7]]
^7^ The Jews answered him, “We have a law, and according to the law, he ought to die, for he has made himself the Son of God.”

[[john-19-8]]
^8^ Therefore, when Pilate had heard this word, he was more fearful.

[[john-19-9]]
^9^ And he entered into the praetorium again. And he said to Jesus. “Where are you from?” But Jesus gave him no response.

[[john-19-10]]
^10^ Therefore, Pilate said to him: “Will you not speak to me? Do you not know that I have authority to crucify you, and I have authority to release you?”

[[john-19-11]]
^11^ Jesus responded, “You would not have any authority over me, unless it were given to you from above. For this reason, he who has handed me over to you has the greater sin.”

[[john-19-12]]
^12^ And from then on, Pilate was seeking to release him. But the Jews were crying out, saying: “If you release this man, you are no friend of Caesar. For anyone who makes himself a king contradicts Caesar.”

[[john-19-13]]
^13^ Now when Pilate had heard these words, he brought Jesus outside, and he sat down in the seat of judgment, in a place which is called the Pavement, but in Hebrew, it is called the Elevation.

[[john-19-14]]
^14^ Now it was the preparation day of the Passover, about the sixth hour. And he said to the Jews, “Behold your king.”

[[john-19-15]]
^15^ But they were crying out: “Take him away! Take him away! Crucify him!” Pilate said to them, “Shall I crucify your king?” The high priests responded, “We have no king except Caesar.”

[[john-19-16]]
^16^ Therefore, he then handed him over to them to be crucified. And they took Jesus and led him away.

[[john-19-17]]
^17^ And carrying his own cross, he went forth to the place which is called Calvary, but in Hebrew it is called the Place of the Skull.

[[john-19-18]]
^18^ There they crucified him, and with him two others, one on each side, with Jesus in the middle.

[[john-19-19]]
^19^ Then Pilate also wrote a title, and he set it above the cross. And it was written: JESUS THE NAZARENE, KING OF THE JEWS.

[[john-19-20]]
^20^ Therefore, many of the Jews read this title, for the place where Jesus was crucified was close to the city. And it was written in Hebrew, in Greek, and in Latin.

[[john-19-21]]
^21^ Then the high priests of the Jews said to Pilate: Do not write, ‘King of the Jews,’ but that he said, ‘I am King of the Jews.’

[[john-19-22]]
^22^ Pilate responded, “What I have written, I have written.”

[[john-19-23]]
^23^ Then the soldiers, when they had crucified him, took his garments, and they made four parts, one part to each soldier, and the tunic. But the tunic was seamless, woven from above throughout the whole.

[[john-19-24]]
^24^ Then they said to one another, “Let us not cut it, but instead let us cast lots over it, to see whose it will be.” This was so that the Scripture would be fulfilled, saying: “They have distributed my garments among themselves, and for my vesture they have cast lots.” And indeed, the soldiers did these things.

[[john-19-25]]
^25^ And standing beside the cross of Jesus were his mother, and his mother’s sister, and Mary of Cleophas, and Mary Magdalene.

[[john-19-26]]
^26^ Therefore, when Jesus had seen his mother and the disciple whom he loved standing near, he said to his mother, “Woman, behold your son.”

[[john-19-27]]
^27^ Next, he said to the disciple, “Behold your mother.” And from that hour, the disciple accepted her as his own.

[[john-19-28]]
^28^ After this, Jesus knew that all had been accomplished, so in order that the Scripture might be completed, he said, “I thirst.”

[[john-19-29]]
^29^ And there was a container placed there, full of vinegar. Then, placing a sponge full of vinegar around hyssop, they brought it to his mouth.

[[john-19-30]]
^30^ Then Jesus, when he had received the vinegar, said: “It is consummated.” And bowing down his head, he surrendered his spirit.

[[john-19-31]]
^31^ Then the Jews, because it was the preparation day, so that the bodies would not remain upon the cross on the Sabbath (for that Sabbath was a great day), they petitioned Pilate in order that their legs might be broken, and they might be taken away.

[[john-19-32]]
^32^ Therefore, the soldiers approached, and, indeed, they broke the legs of the first one, and of the other who was crucified with him.

[[john-19-33]]
^33^ But after they had approached Jesus, when they saw that he was already dead, they did not break his legs.

[[john-19-34]]
^34^ Instead, one of the soldiers opened his side with a lance, and immediately there went out blood and water.

[[john-19-35]]
^35^ And he who saw this has offered testimony, and his testimony is true. And he knows that he speaks the truth, so that you also may believe.

[[john-19-36]]
^36^ For these things happened so that the Scripture would be fulfilled: “You shall not break a bone of him.”

[[john-19-37]]
^37^ And again, another Scripture says: “They shall look upon him, whom they have pierced.”

[[john-19-38]]
^38^ Then, after these things, Joseph from Arimathea, (because he was a disciple of Jesus, but a secret one for fear of the Jews) petitioned Pilate so that he might take away the body of Jesus. And Pilate gave permission. Therefore, he went and took away the body of Jesus.

[[john-19-39]]
^39^ Now Nicodemus also arrived, (who had gone to Jesus at first by night) bringing a mixture of myrrh and aloe, weighing about seventy pounds.

[[john-19-40]]
^40^ Therefore, they took the body of Jesus, and they bound it with linen cloths and the aromatic spices, just as it is the manner of the Jews to bury.

[[john-19-41]]
^41^ Now in the place where he was crucified there was a garden, and in the garden there was a new tomb, in which no one had yet been laid.

[[john-19-42]]
^42^ Therefore, because of the preparation day of the Jews, since the tomb was nearby, they placed Jesus there.


[[john-20]]
== Chapter 20

[[john-20-1]]
^1^ Then on the first Sabbath, Mary Magdalene went to the tomb early, while it was still dark, and she saw that the stone had been rolled away from the tomb.

[[john-20-2]]
^2^ Therefore, she ran and went to Simon Peter, and to the other disciple, whom Jesus loved, and she said to them, “They have taken the Lord away from the tomb, and we do not know where they have laid him.”

[[john-20-3]]
^3^ Therefore, Peter departed with the other disciple, and they went to the tomb.

[[john-20-4]]
^4^ Now they both ran together, but the other disciple ran more quickly, ahead of Peter, and so he arrived at the tomb first.

[[john-20-5]]
^5^ And when he bowed down, he saw the linen cloths lying there, but he did not yet enter.

[[john-20-6]]
^6^ Then Simon Peter arrived, following him, and he entered the tomb, and he saw the linen cloths lying there,

[[john-20-7]]
^7^ and the separate cloth which had been over his head, not placed with the linen cloths, but in a separate place, wrapped up by itself.

[[john-20-8]]
^8^ Then the other disciple, who had arrived first at the tomb, also entered. And he saw and believed.

[[john-20-9]]
^9^ For as yet they did not understand the Scripture, that it was necessary for him to rise again from the dead.

[[john-20-10]]
^10^ Then the disciples went away again, each by himself.

[[john-20-11]]
^11^ But Mary was standing outside the tomb, weeping. Then, while she was weeping, she bowed down and gazed into the tomb.

[[john-20-12]]
^12^ And she saw two Angels in white, sitting where the body of Jesus had been placed, one at the head, and one at the feet.

[[john-20-13]]
^13^ They said to her, “Woman, why are you weeping?” She said to them, “Because they have taken away my Lord, and I do not know where they have placed him.”

[[john-20-14]]
^14^ When she had said this, she turned around and saw Jesus standing there, but she did not know that it was Jesus.

[[john-20-15]]
^15^ Jesus said to her: “Woman, why are you weeping? Who are you seeking?” Considering that it was the gardener, she said to him, “Sir, if you have moved him, tell me where you have placed him, and I will take him away.”

[[john-20-16]]
^16^ Jesus said to her, “Mary!” And turning, she said to him, “Rabboni!” (which means, Teacher).

[[john-20-17]]
^17^ Jesus said to her: “Do not touch me. For I have not yet ascended to my Father. But go to my brothers and tell them: ‘I am ascending to my Father and to your Father, to my God and to your God.’ ”

[[john-20-18]]
^18^ Mary Magdalene went, announcing to the disciples, “I have seen the Lord, and these are the things that he said to me.”

[[john-20-19]]
^19^ Then, when it was late on the same day, on the first of the Sabbaths, and the doors were closed where the disciples were gathered, for fear of the Jews, Jesus came and stood in their midst, and he said to them: “Peace to you.”

[[john-20-20]]
^20^ And when he had said this, he showed them his hands and side. And the disciples were gladdened when they saw the Lord.

[[john-20-21]]
^21^ Therefore, he said to them again: “Peace to you. As the Father has sent me, so I send you.”

[[john-20-22]]
^22^ When he had said this, he breathed on them. And he said to them: “Receive the Holy Spirit.

[[john-20-23]]
^23^ Those whose sins you shall forgive, they are forgiven them, and those whose sins you shall retain, they are retained.”

[[john-20-24]]
^24^ Now Thomas, one of the twelve, who is called the Twin, was not with them when Jesus arrived.

[[john-20-25]]
^25^ Therefore, the other disciples said to him, “We have seen the Lord.” But he said to them, “Unless I will see in his hands the mark of the nails and place my finger into the place of the nails, and place my hand into his side, I will not believe.”

[[john-20-26]]
^26^ And after eight days, again his disciples were within, and Thomas was with them. Jesus arrived, though the doors had been closed, and he stood in their midst and said, “Peace to you.”

[[john-20-27]]
^27^ Next, he said to Thomas: “Look at my hands, and place your finger here; and bring your hand close, and place it at my side. And do not choose to be unbelieving, but faithful.”

[[john-20-28]]
^28^ Thomas responded and said to him, “My Lord and my God.”

[[john-20-29]]
^29^ Jesus said to him: “You have seen me, Thomas, so you have believed. Blessed are those who have not seen and yet have believed.”

[[john-20-30]]
^30^ Jesus also accomplished many other signs in the sight of his disciples. These have not been written in this book.

[[john-20-31]]
^31^ But these things have been written, so that you may believe that Jesus is the Christ, the Son of God, and so that, in believing, you may have life in his name.


[[john-21]]
== Chapter 21

[[john-21-1]]
^1^ After this, Jesus manifested himself again to the disciples at the Sea of Tiberias. And he manifested himself in this way.

[[john-21-2]]
^2^ These were together: Simon Peter and Thomas, who is called the Twin, and Nathanael, who was from Cana of Galilee, and the sons of Zebedee, and two others of his disciples.

[[john-21-3]]
^3^ Simon Peter said to them, “I am going fishing.” They said to him, “And we are going with you.” And they went and climbed into the ship. And in that night, they caught nothing.

[[john-21-4]]
^4^ But when morning arrived, Jesus stood on the shore. Yet the disciples did not realize that it was Jesus.

[[john-21-5]]
^5^ Then Jesus said to them, “Children, do you have any food?” They answered him, “No.”

[[john-21-6]]
^6^ He said to them, “Cast the net to the right side of the ship, and you will find some.” Therefore, they cast it out, and then they were not able to draw it in, because of the multitude of fish.

[[john-21-7]]
^7^ Therefore, the disciple whom Jesus loved said to Peter, “It is the Lord.” Simon Peter, when he had heard that it was the Lord, wrapped his tunic around himself, (for he was naked) and he cast himself into the sea.

[[john-21-8]]
^8^ Then the other disciples arrived in a boat, (for they were not far from the land, only about two hundred cubits) dragging the net with the fish.

[[john-21-9]]
^9^ Then, when they climbed down to the land they saw burning coals prepared, and fish already placed above them, and bread.

[[john-21-10]]
^10^ Jesus said to them, “Bring some of the fish that you have just now caught.”

[[john-21-11]]
^11^ Simon Peter climbed up and drew in the net to land: full of large fish, one hundred and fifty-three of them. And although there were so many, the net was not torn.

[[john-21-12]]
^12^ Jesus said to them, “Approach and dine.” And not one of them sitting down to eat dared to ask him, “Who are you?” For they knew that it was the Lord.

[[john-21-13]]
^13^ And Jesus approached, and he took bread, and he gave it to them, and similarly with the fish.

[[john-21-14]]
^14^ This was now the third time that Jesus was manifested to his disciples, after he had resurrected from the dead.

[[john-21-15]]
^15^ Then, when they had dined, Jesus said to Simon Peter, “Simon, son of John, do you love me more than these?” He said to him, “Yes, Lord, you know that I love you.” He said to him, “Feed my lambs.”

[[john-21-16]]
^16^ He said to him again: “Simon, son of John, do you love me?” He said to him, “Yes, Lord, you know that I love you.” He said to him, “Feed my lambs.”

[[john-21-17]]
^17^ He said to him a third time, “Simon, son of John, do you love me?” Peter was very grieved that he had asked him a third time, “Do you love me?” And so he said to him: “Lord, you know all things. You know that I love you.” He said to him, “Feed my sheep.

[[john-21-18]]
^18^ Amen, amen, I say to you, when you were younger, you girded yourself and walked wherever you wanted. But when you are older, you will extend your hands, and another shall gird you and lead you where you do not want to go.”

[[john-21-19]]
^19^ Now he said this to signify by what kind of death he would glorify God. And when he had said this, he said to him, “Follow me.”

[[john-21-20]]
^20^ Peter, turning around, saw the disciple whom Jesus loved following, the one who also had leaned on his chest at supper and said, “Lord, who is it who shall betray you?”

[[john-21-21]]
^21^ Therefore, when Peter had seen him, he said to Jesus, “Lord, but what about this one?”

[[john-21-22]]
^22^ Jesus said to him: “If I want him to remain until I return, what is that to you? You follow me.”

[[john-21-23]]
^23^ Therefore, the saying went out among the brothers that this disciple would not die. But Jesus did not say to him that he would not die, but only, “If I want him to remain until I return, what is that to you?”

[[john-21-24]]
^24^ This is the same disciple who offers testimony about these things, and who has written these things. And we know that his testimony is true.

[[john-21-25]]
^25^ Now there are also many other things that Jesus did, which, if each of these were written down, the world itself, I suppose, would not be able to contain the books that would be written.
