[[ephesians]]
= The Letter to the Ephesians
:short: Ephesians

[[ephesians-1]]
== Chapter 1

[[ephesians-1-1]]
^1^ Paul, an Apostle of Jesus Christ through the will of God, to all the saints who are at Ephesus and to the faithful in Christ Jesus.

[[ephesians-1-2]]
^2^ Grace and peace to you from God the Father, and from the Lord Jesus Christ.

[[ephesians-1-3]]
^3^ Blessed be the God and Father of our Lord Jesus Christ, who has blessed us with every spiritual blessing in the heavens, in Christ,

[[ephesians-1-4]]
^4^ just as he chose us in him before the foundation of the world, so that we would be holy and immaculate in his sight, in charity.

[[ephesians-1-5]]
^5^ He has predestined us to adoption as sons, through Jesus Christ, in himself, according to the purpose of his will,

[[ephesians-1-6]]
^6^ for the praise of the glory of his grace, with which he has gifted us in his beloved Son.

[[ephesians-1-7]]
^7^ In him, we have redemption through his blood: the remission of sins in accord with the riches of his grace,

[[ephesians-1-8]]
^8^ which is superabundant in us, with all wisdom and prudence.

[[ephesians-1-9]]
^9^ So does he make known to us the mystery of his will, which he has set forth in Christ, in a manner well-pleasing to him,

[[ephesians-1-10]]
^10^ in the dispensation of the fullness of time, so as to renew in Christ everything that exists through him in heaven and on earth.

[[ephesians-1-11]]
^11^ In him, we too are called to our portion, having been predestined in accord with the plan of the One who accomplishes all things by the counsel of his will.

[[ephesians-1-12]]
^12^ So may we be, to the praise of his glory, we who have hoped beforehand in Christ.

[[ephesians-1-13]]
^13^ In him, you also, after you heard and believed the Word of truth, which is the Gospel of your salvation, were sealed with the Holy Spirit of the Promise.

[[ephesians-1-14]]
^14^ He is the pledge of our inheritance, unto the acquisition of redemption, to the praise of his glory.

[[ephesians-1-15]]
^15^ Because of this, and hearing of your faith that is in the Lord Jesus, and of your love toward all the saints,

[[ephesians-1-16]]
^16^ I have not ceased giving thanks for you, calling you to mind in my prayers,

[[ephesians-1-17]]
^17^ so that the God of our Lord Jesus Christ, the Father of glory, may give a spirit of wisdom and of revelation to you, in knowledge of him.

[[ephesians-1-18]]
^18^ May the eyes of your heart be illuminated, so that you may know what is the hope of his calling, and the wealth of the glory of his inheritance with the saints,

[[ephesians-1-19]]
^19^ and the preeminent magnitude of his virtue toward us, toward we who believe in accord with the work of his powerful virtue,

[[ephesians-1-20]]
^20^ which he wrought in Christ, raising him from the dead and establishing him at his right hand in the heavens,

[[ephesians-1-21]]
^21^ above every principality and power and virtue and dominion, and above every name that is given, not only in this age, but even in the future age.

[[ephesians-1-22]]
^22^ And he has subjected all things under his feet, and he has made him the head over the entire Church,

[[ephesians-1-23]]
^23^ which is his body and which is the fullness of him who accomplishes everything in everyone.


[[ephesians-2]]
== Chapter 2

[[ephesians-2-1]]
^1^ And you were once dead in your sins and offenses,

[[ephesians-2-2]]
^2^ in which you walked in times past, according to the age of this world, according to the prince of the power of this sky, the spirit who now works in the sons of distrust.

[[ephesians-2-3]]
^3^ And we too were all conversant in these things, in times past, by the desires of our flesh, acting according to the will of the flesh and according to our own thoughts. And so we were, by nature, sons of wrath, even like the others.

[[ephesians-2-4]]
^4^ Yet still, God, who is rich in mercy, for the sake of his exceedingly great charity with which he loved us,

[[ephesians-2-5]]
^5^ even when we were dead in our sins, has enlivened us together in Christ, by whose grace you have been saved.

[[ephesians-2-6]]
^6^ And he has raised us up together, and he has caused us to sit down together in the heavens, in Christ Jesus,

[[ephesians-2-7]]
^7^ so that he may display, in the ages soon to arrive, the abundant wealth of his grace, by his goodness toward us in Christ Jesus.

[[ephesians-2-8]]
^8^ For by grace, you have been saved through faith. And this is not of yourselves, for it is a gift of God.

[[ephesians-2-9]]
^9^ And this is not of works, so that no one may glory.

[[ephesians-2-10]]
^10^ For we are his handiwork, created in Christ Jesus for the good works which God has prepared and in which we should walk.

[[ephesians-2-11]]
^11^ Because of this, be mindful that, in times past, you were Gentiles in the flesh, and that you were called uncircumcised by those who are called circumcised in the flesh, something done by man,

[[ephesians-2-12]]
^12^ and that you were, in that time, without Christ, being foreign to the way of life of Israel, being visitors to the testament, having no hope of the promise, and being without God in this world.

[[ephesians-2-13]]
^13^ But now, in Christ Jesus, you, who were in times past far away, have been brought near by the blood of Christ.

[[ephesians-2-14]]
^14^ For he is our peace. He made the two into one, by dissolving the intermediate wall of separation, of opposition, by his flesh,

[[ephesians-2-15]]
^15^ emptying the law of commandments by decree, so that he might join these two, in himself, into one new man, making peace

[[ephesians-2-16]]
^16^ and reconciling both to God, in one body, through the cross, destroying this opposition in himself.

[[ephesians-2-17]]
^17^ And upon arriving, he evangelized peace to you who were far away, and peace to those who were near.

[[ephesians-2-18]]
^18^ For by him, we both have access, in the one Spirit, to the Father.

[[ephesians-2-19]]
^19^ Now, therefore, you are no longer visitors and new arrivals. Instead, you are citizens among the saints in the household of God,

[[ephesians-2-20]]
^20^ having been built upon the foundation of the Apostles and of the Prophets, with Jesus Christ himself as the preeminent cornerstone.

[[ephesians-2-21]]
^21^ In him, all that has been built is framed together, rising up into a holy temple in the Lord.

[[ephesians-2-22]]
^22^ In him, you also have been built together into a habitation of God in the Spirit.


[[ephesians-3]]
== Chapter 3

[[ephesians-3-1]]
^1^ By reason of this grace, I, Paul, am a prisoner of Jesus Christ, for the sake of you Gentiles.

[[ephesians-3-2]]
^2^ Now certainly, you have heard of the dispensation of the grace of God, which has been given to me among you:

[[ephesians-3-3]]
^3^ that, by means of revelation, the mystery was made known to me, just as I have written above in a few words.

[[ephesians-3-4]]
^4^ Yet, by reading this closely, you might be able to understand my prudence in the mystery of Christ.

[[ephesians-3-5]]
^5^ In other generations, this was unknown to the sons of men, even as it has now been revealed to his holy Apostles and Prophets in the Spirit,

[[ephesians-3-6]]
^6^ so that the Gentiles would be co-heirs, and of the same body, and partners together, by his promise in Christ Jesus, through the Gospel.

[[ephesians-3-7]]
^7^ Of this Gospel, I have been made a minister, according to the gift of the grace of God, which has been given to me by means of the operation of his virtue.

[[ephesians-3-8]]
^8^ Although I am the least of all the saints, I have been given this grace: to evangelize among the Gentiles the unsearchable riches of Christ,

[[ephesians-3-9]]
^9^ and to enlighten everyone concerning the dispensation of the mystery, hidden before the ages in God who created all things,

[[ephesians-3-10]]
^10^ so that the manifold wisdom of God may become well-known to the principalities and powers in the heavens, through the Church,

[[ephesians-3-11]]
^11^ according to that timeless purpose, which he has formed in Christ Jesus our Lord.

[[ephesians-3-12]]
^12^ In him we trust, and so we approach with confidence, through his faith.

[[ephesians-3-13]]
^13^ Because of this, I ask you not to be weakened by my tribulations on your behalf; for this is your glory.

[[ephesians-3-14]]
^14^ By reason of this grace, I bend my knees to the Father of our Lord Jesus Christ,

[[ephesians-3-15]]
^15^ from whom all paternity in heaven and on earth takes its name.

[[ephesians-3-16]]
^16^ And I ask him to grant to you to be strengthened in virtue by his Spirit, in accord with the wealth of his glory, in the inner man,

[[ephesians-3-17]]
^17^ so that Christ may live in your hearts through a faith rooted in, and founded on, charity.

[[ephesians-3-18]]
^18^ So may you be able to embrace, with all the saints, what is the width and length and height and depth

[[ephesians-3-19]]
^19^ of the charity of Christ, and even be able to know that which surpasses all knowledge, so that you may be filled with all the fullness of God.

[[ephesians-3-20]]
^20^ Now to him who is able to do all things, more abundantly than we could ever ask or understand, by means of the virtue which is at work in us:

[[ephesians-3-21]]
^21^ to him be glory, in the Church and in Christ Jesus, throughout every generation, forever and ever. Amen.


[[ephesians-4]]
== Chapter 4

[[ephesians-4-1]]
^1^ And so, as a prisoner in the Lord, I beg you to walk in a manner worthy of the vocation to which you have been called:

[[ephesians-4-2]]
^2^ with all humility and meekness, with patience, supporting one another in charity.

[[ephesians-4-3]]
^3^ Be anxious to preserve the unity of the Spirit within the bonds of peace.

[[ephesians-4-4]]
^4^ One body and one Spirit: to this you have been called by the one hope of your calling:

[[ephesians-4-5]]
^5^ one Lord, one faith, one baptism,

[[ephesians-4-6]]
^6^ one God and Father of all, who is over all, and through all, and in us all.

[[ephesians-4-7]]
^7^ Yet to each one of us there has been given grace according to the measure allotted by Christ.

[[ephesians-4-8]]
^8^ Because of this, he says: “Ascending on high, he took captivity itself captive; he gave gifts to men.”

[[ephesians-4-9]]
^9^ Now that he has ascended, what is left except for him also to descend, first to the lower parts of the earth?

[[ephesians-4-10]]
^10^ He who descended is the same one who also ascended above all the heavens, so that he might fulfill everything.

[[ephesians-4-11]]
^11^ And the same one granted that some would be Apostles, and some Prophets, yet truly others evangelists, and others pastors and teachers,

[[ephesians-4-12]]
^12^ for the sake of the perfection of the saints, by the work of the ministry, in the edification of the body of Christ,

[[ephesians-4-13]]
^13^ until we all meet in the unity of faith and in the knowledge of the Son of God, as a perfect man, in the measure of the age of the fullness of Christ.

[[ephesians-4-14]]
^14^ So may we then no longer be little children, disturbed and carried about by every wind of doctrine, by the wickedness of men, and by the craftiness which deceives unto error.

[[ephesians-4-15]]
^15^ Instead, acting according to truth in charity, we should increase in everything, in him who is the head, Christ himself.

[[ephesians-4-16]]
^16^ For in him, the whole body is joined closely together, by every underlying joint, through the function allotted to each part, bringing improvement to the body, toward its edification in charity.

[[ephesians-4-17]]
^17^ And so, I say this, and I testify in the Lord: that from now on you should walk, not as the Gentiles also walk, in the vanity of their mind,

[[ephesians-4-18]]
^18^ having their intellect obscured, being alienated from the life of God, through the ignorance that is within them, because of the blindness of their hearts.

[[ephesians-4-19]]
^19^ Such as these, despairing, have given themselves over to sexual immorality, carrying out every impurity with rapacity.

[[ephesians-4-20]]
^20^ But this is not what you have learned in Christ.

[[ephesians-4-21]]
^21^ For certainly, you have listened to him, and you have been instructed in him, according to the truth that is in Jesus:

[[ephesians-4-22]]
^22^ to set aside your earlier behavior, the former man, who was corrupted, by means of desire, unto error,

[[ephesians-4-23]]
^23^ and so be renewed in the spirit of your mind,

[[ephesians-4-24]]
^24^ and so put on the new man, who, in accord with God, is created in justice and in the holiness of truth.

[[ephesians-4-25]]
^25^ Because of this, setting aside lying, speak the truth, each one with his neighbor. For we are all part of one another.

[[ephesians-4-26]]
^26^ “Be angry, but do not be willing to sin.” Do not let the sun set over your anger.

[[ephesians-4-27]]
^27^ Provide no place for the devil.

[[ephesians-4-28]]
^28^ Whoever was stealing, let him now not steal, but rather let him labor, working with his hands, doing what is good, so that he may have something to distribute to those who suffer need.

[[ephesians-4-29]]
^29^ Let no evil words proceed from your mouth, but only what is good, toward the edification of faith, so as to bestow grace upon those who listen.

[[ephesians-4-30]]
^30^ And do not be willing to grieve the Holy Spirit of God, in whom you have been sealed, unto the day of redemption.

[[ephesians-4-31]]
^31^ Let all bitterness and anger and indignation and outcry and blasphemy be taken away from you, along with all malice.

[[ephesians-4-32]]
^32^ And be kind and merciful to one another, forgiving one another, just as God has forgiven you in Christ.


[[ephesians-5]]
== Chapter 5

[[ephesians-5-1]]
^1^ Therefore, as most beloved sons, be imitators of God.

[[ephesians-5-2]]
^2^ And walk in love, just as Christ also loved us and delivered himself for us, as an oblation and a sacrifice to God, with a fragrance of sweetness.

[[ephesians-5-3]]
^3^ But let not any kind of fornication, or impurity, or rapacity so much as be named among you, just as is worthy of the saints,

[[ephesians-5-4]]
^4^ nor any indecent, or foolish, or abusive talk, for this is without purpose; but instead, give thanks.

[[ephesians-5-5]]
^5^ For know and understand this: no one who is a fornicator, or lustful, or rapacious (for these are a kind of service to idols) holds an inheritance in the kingdom of Christ and of God.

[[ephesians-5-6]]
^6^ Let no one seduce you with empty words. For because of these things, the wrath of God was sent upon the sons of unbelief.

[[ephesians-5-7]]
^7^ Therefore, do not choose to become participants with them.

[[ephesians-5-8]]
^8^ For you were darkness, in times past, but now you are light, in the Lord. So then, walk as sons of the light.

[[ephesians-5-9]]
^9^ For the fruit of the light is in all goodness and justice and truth,

[[ephesians-5-10]]
^10^ affirming what is well-pleasing to God.

[[ephesians-5-11]]
^11^ And so, have no fellowship with the unfruitful works of darkness, but instead, refute them.

[[ephesians-5-12]]
^12^ For the things that are done by them in secret are shameful, even to mention.

[[ephesians-5-13]]
^13^ But all things that are disputed are made manifest by the light. For all that is made manifest is light.

[[ephesians-5-14]]
^14^ Because of this, it is said: “You who are sleeping: awaken, and rise up from the dead, and so shall the Christ enlighten you.”

[[ephesians-5-15]]
^15^ And so, brothers, see to it that you walk cautiously, not like the foolish,

[[ephesians-5-16]]
^16^ but like the wise: atoning for this age, because this is an evil time.

[[ephesians-5-17]]
^17^ For this reason, do not choose to be imprudent. Instead, understand what is the will of God.

[[ephesians-5-18]]
^18^ And do not choose to be inebriated by wine, for this is self-indulgence. Instead, be filled with the Holy Spirit,

[[ephesians-5-19]]
^19^ speaking among yourselves in psalms and hymns and spiritual canticles, singing and reciting psalms to the Lord in your hearts,

[[ephesians-5-20]]
^20^ giving thanks always for everything, in the name of our Lord Jesus Christ, to God the Father.

[[ephesians-5-21]]
^21^ Be subject to one another in the fear of Christ.

[[ephesians-5-22]]
^22^ Wives should be submissive to their husbands, as to the Lord.

[[ephesians-5-23]]
^23^ For the husband is the head of the wife, just as Christ is the head of the Church. He is the Savior of his body.

[[ephesians-5-24]]
^24^ Therefore, just as the Church is subject to Christ, so also should wives be subject to their husbands in all things.

[[ephesians-5-25]]
^25^ Husbands, love your wives, just as Christ also loved the Church and handed himself over for her,

[[ephesians-5-26]]
^26^ so that he might sanctify her, washing her clean by water and the Word of life,

[[ephesians-5-27]]
^27^ so that he might offer her to himself as a glorious Church, not having any spot or wrinkle or any such thing, so that she would be holy and immaculate.

[[ephesians-5-28]]
^28^ So, too, husbands should love their wives as their own bodies. He who loves his wife loves himself.

[[ephesians-5-29]]
^29^ For no man has ever hated his own flesh, but instead he nourishes and cherishes it, as Christ also does to the Church.

[[ephesians-5-30]]
^30^ For we are a part of his body, of his flesh and of his bones.

[[ephesians-5-31]]
^31^ “For this reason, a man shall leave behind his father and mother, and he shall cling to his wife; and the two shall be as one flesh.”

[[ephesians-5-32]]
^32^ This is a great Sacrament. And I am speaking in Christ and in the Church.

[[ephesians-5-33]]
^33^ Yet truly, each and every one of you should love his wife as himself. And a wife should fear her husband.


[[ephesians-6]]
== Chapter 6

[[ephesians-6-1]]
^1^ Children, obey your parents in the Lord, for this is just.

[[ephesians-6-2]]
^2^ Honor your father and your mother. This is the first commandment with a promise:

[[ephesians-6-3]]
^3^ so that it may be well with you, and so that you may have a long life upon the earth.

[[ephesians-6-4]]
^4^ And you, fathers, do not provoke your children to anger, but educate them with the discipline and correction of the Lord.

[[ephesians-6-5]]
^5^ Servants, be obedient to your lords according to the flesh, with fear and trembling, in the simplicity of your heart, as to Christ.

[[ephesians-6-6]]
^6^ Do not serve only when seen, as if to please men, but act as servants of Christ, doing the will of God from the heart.

[[ephesians-6-7]]
^7^ Serve with good will, as to the Lord, and not to men.

[[ephesians-6-8]]
^8^ For you know that whatever good each one will do, the same will he receive from the Lord, whether he is servant or free.

[[ephesians-6-9]]
^9^ And you, lords, act similarly toward them, setting aside threats, knowing that the Lord of both you and them is in heaven. For with him there is no favoritism toward anyone.

[[ephesians-6-10]]
^10^ Concerning the rest, brothers, be strengthened in the Lord, by the power of his virtue.

[[ephesians-6-11]]
^11^ Be clothed in the armor of God, so that you may be able to stand against the treachery of the devil.

[[ephesians-6-12]]
^12^ For our struggle is not against flesh and blood, but against principalities and powers, against the directors of this world of darkness, against the spirits of wickedness in high places.

[[ephesians-6-13]]
^13^ Because of this, take up the armor of God, so that you may be able to withstand the evil day and remain perfect in all things.

[[ephesians-6-14]]
^14^ Therefore, stand firm, having been girded about your waist with truth, and having been clothed with the breastplate of justice,

[[ephesians-6-15]]
^15^ and having feet which have been shod by the preparation of the Gospel of peace.

[[ephesians-6-16]]
^16^ In all things, take up the shield of faith, with which you may be able to extinguish all the fiery darts of the most wicked one.

[[ephesians-6-17]]
^17^ And take up the helmet of salvation and the sword of the Spirit (which is the Word of God).

[[ephesians-6-18]]
^18^ Through every kind of prayer and supplication, pray at all times in spirit, and so be vigilant with every kind of earnest supplication, for all the saints,

[[ephesians-6-19]]
^19^ and also for me, so that words may be given to me, as I open my mouth with faith to make known the mystery of the Gospel,

[[ephesians-6-20]]
^20^ in such a manner that I may dare to speak exactly as I ought to speak. For I act as an ambassador in chains for the Gospel.

[[ephesians-6-21]]
^21^ Now, so that you also may know the things that concern me and what I am doing, Tychicus, a most beloved brother and a faithful minister in the Lord, will make known everything to you.

[[ephesians-6-22]]
^22^ I have sent him to you for this very reason, so that you may know the things that concern us, and so that he may console your hearts.

[[ephesians-6-23]]
^23^ Peace to the brothers, and charity with faith, from God the Father and the Lord Jesus Christ.

[[ephesians-6-24]]
^24^ May grace be with all those who love our Lord Jesus Christ, unto incorruption. Amen.
