[[philippians]]
= The Letter to the Philippians
:short: Philippians

[[philippians-1]]
== Chapter 1

[[philippians-1-1]]
^1^ Paul and Timothy, servants of Jesus Christ, to all the saints in Christ Jesus who are at Philippi, with the bishops and deacons.

[[philippians-1-2]]
^2^ Grace and peace to you, from God our Father and from the Lord Jesus Christ.

[[philippians-1-3]]
^3^ I give thanks to my God, with every remembrance of you,

[[philippians-1-4]]
^4^ always, in all my prayers, making supplication for all of you with joy,

[[philippians-1-5]]
^5^ because of your communion in the Gospel of Christ, from the first day even until now.

[[philippians-1-6]]
^6^ I am confident of this very thing: that he who has begun this good work in you will perfect it, unto the day of Christ Jesus.

[[philippians-1-7]]
^7^ So then, it is right for me to feel this way about all of you, because I hold you in my heart, and because, in my chains and in the defense and confirmation of the Gospel, you all are partakers of my joy.

[[philippians-1-8]]
^8^ For God is my witness how, within the heart of Jesus Christ, I long for all of you.

[[philippians-1-9]]
^9^ And this I pray: that your charity may abound more and more, with knowledge and with all understanding,

[[philippians-1-10]]
^10^ so that you may be confirmed in what is better, in order that you may be sincere and without offense on the day of Christ:

[[philippians-1-11]]
^11^ filled with the fruit of justice, through Jesus Christ, in the glory and praise of God.

[[philippians-1-12]]
^12^ Now, brothers, I want you to know that the things concerning me happened for the advancement of the Gospel,

[[philippians-1-13]]
^13^ in such a way that my chains have become manifest in Christ in every place of judgment and in all other such places.

[[philippians-1-14]]
^14^ And many from among the brothers in the Lord, becoming confident through my chains, are now much bolder in speaking the Word of God without fear.

[[philippians-1-15]]
^15^ Certainly, some do so even because of envy and contention; and others, too, do so because of a good will to preach Christ.

[[philippians-1-16]]
^16^ Some act out of charity, knowing that I have been appointed for the defense of the Gospel.

[[philippians-1-17]]
^17^ But others, out of contention, announce Christ insincerely, claiming that their difficulties lift them up to my chains.

[[philippians-1-18]]
^18^ But what does it matter? As long as, by every means, whether under pretext or in truthfulness, Christ is announced. And about this, I rejoice, and moreover, I will continue to rejoice.

[[philippians-1-19]]
^19^ For I know that this will bring me to salvation, through your prayers and under the ministration of the Spirit of Jesus Christ,

[[philippians-1-20]]
^20^ by means of my own expectation and hope. For in nothing shall I be confounded. Instead, with all confidence, now just as always, Christ shall be magnified in my body, whether by life or by death.

[[philippians-1-21]]
^21^ For to me, to live is Christ, and to die is gain.

[[philippians-1-22]]
^22^ And while I live in the flesh, for me, there is the fruit of works. But I do not know which I would choose.

[[philippians-1-23]]
^23^ For I am constrained between the two: having a desire to be dissolved and to be with Christ, which is the far better thing,

[[philippians-1-24]]
^24^ but then to remain in the flesh is necessary for your sake.

[[philippians-1-25]]
^25^ And having this confidence, I know that I shall remain and that I shall continue to remain with all of you, for your advancement and for your joy in the faith,

[[philippians-1-26]]
^26^ so that your rejoicing may abound in Christ Jesus for me, through my return to you again.

[[philippians-1-27]]
^27^ Only let your behavior be worthy of the Gospel of Christ, so that, whether I return and see you, or whether, being absent, I hear about you, still you may stand firm with one spirit, with one mind, laboring together for the faith of the Gospel.

[[philippians-1-28]]
^28^ And in nothing be terrified by the adversaries. For what is to them an occasion of perdition, is to you an occasion of salvation, and this is from God.

[[philippians-1-29]]
^29^ For this has been given to you on behalf of Christ, not only so that you may believe in him, but even so that you may suffer with him,

[[philippians-1-30]]
^30^ engaging in the same struggle, of a kind which you also have seen in me, and which you now have heard from me.


[[philippians-2]]
== Chapter 2

[[philippians-2-1]]
^1^ Therefore, if there is any consolation in Christ, any solace of charity, any fellowship of the Spirit, any feelings of commiseration:

[[philippians-2-2]]
^2^ complete my joy by having the same understanding, holding to the same charity, being of one mind, with the same sentiment.

[[philippians-2-3]]
^3^ Let nothing be done by contention, nor in vain glory. Instead, in humility, let each of you esteem others to be better than himself.

[[philippians-2-4]]
^4^ Let each of you not consider anything to be your own, but rather to belong to others.

[[philippians-2-5]]
^5^ For this understanding in you was also in Christ Jesus:

[[philippians-2-6]]
^6^ who, though he was in the form of God, did not consider equality with God something to be seized.

[[philippians-2-7]]
^7^ Instead, he emptied himself, taking the form of a servant, being made in the likeness of men, and accepting the state of a man.

[[philippians-2-8]]
^8^ He humbled himself, becoming obedient even unto death, even the death of the Cross.

[[philippians-2-9]]
^9^ Because of this, God has also exalted him and has given him a name which is above every name,

[[philippians-2-10]]
^10^ so that, at the name of Jesus, every knee would bend, of those in heaven, of those on earth, and of those in hell,

[[philippians-2-11]]
^11^ and so that every tongue would confess that the Lord Jesus Christ is in the glory of God the Father.

[[philippians-2-12]]
^12^ And so, my most beloved, just as you have always obeyed, not only in my presence, but even more so now in my absence: work toward your salvation with fear and trembling.

[[philippians-2-13]]
^13^ For it is God who works in you, both so as to choose, and so as to act, in accord with his good will.

[[philippians-2-14]]
^14^ And do everything without murmuring or hesitation.

[[philippians-2-15]]
^15^ So may you be without blame, simple sons of God, without reproof, in the midst of a depraved and perverse nation, among whom you shine like lights in the world,

[[philippians-2-16]]
^16^ holding to the Word of Life, until my glory in the day of Christ. For I have not run in vain, nor have I labored in vain.

[[philippians-2-17]]
^17^ Moreover, if I am to be immolated because of the sacrifice and service of your faith, I rejoice and give thanks with all of you.

[[philippians-2-18]]
^18^ And over this same thing, you also should rejoice and give thanks, together with me.

[[philippians-2-19]]
^19^ Now I hope in the Lord Jesus to send Timothy to you soon, in order that I may be encouraged, when I know the things concerning you.

[[philippians-2-20]]
^20^ For I have no one else with such an agreeable mind, who, with sincere affection, is solicitous for you.

[[philippians-2-21]]
^21^ For they all seek the things that are of themselves, not the things that are of Jesus Christ.

[[philippians-2-22]]
^22^ So know this evidence of him: that like a son with a father, so has he served with me in the Gospel.

[[philippians-2-23]]
^23^ Therefore, I hope to send him to you immediately, as soon as I see what will happen concerning me.

[[philippians-2-24]]
^24^ But I trust in the Lord that I myself will also return to you soon.

[[philippians-2-25]]
^25^ Now I have considered it necessary to send to you Epaphroditus, my brother, and co-worker, and fellow soldier, and an attendant to my needs, but your Apostle.

[[philippians-2-26]]
^26^ For certainly, he has desired all of you, and he was saddened because you had heard that he was sick.

[[philippians-2-27]]
^27^ For he was sick, even unto death, but God took pity on him, and not only on him, but truly on myself also, so that I would not have sorrow upon sorrow.

[[philippians-2-28]]
^28^ Therefore, I sent him more readily, in order that, by seeing him again, you may rejoice, and I may be without sorrow.

[[philippians-2-29]]
^29^ And so, receive him with every joy in the Lord, and treat all those like him with honor.

[[philippians-2-30]]
^30^ For he was brought close even to death, for the sake of the work of Christ, handing over his own life, so that he might fulfill what was lacking from you concerning my service.


[[philippians-3]]
== Chapter 3

[[philippians-3-1]]
^1^ Concerning other things, my brothers, rejoice in the Lord. It is certainly not tiresome for me to write the same things to you, but for you, it is necessary.

[[philippians-3-2]]
^2^ Beware of dogs; beware of those who work evil; beware of those who are divisive.

[[philippians-3-3]]
^3^ For we are the circumcised, we who serve God in the Spirit and who glory in Christ Jesus, having no confidence in the flesh.

[[philippians-3-4]]
^4^ Nevertheless, I might have confidence also in the flesh, for if anyone else seems to have confidence in the flesh, more so do I.

[[philippians-3-5]]
^5^ For I was circumcised on the eighth day, of the stock of Israel, from the tribe of Benjamin, a Hebrew among Hebrews. According to the law, I was a Pharisee;

[[philippians-3-6]]
^6^ according to zeal, I persecuted the Church of God; according to the justice that is in the law, I lived without blame.

[[philippians-3-7]]
^7^ But the things which had been to my gain, the same have I considered a loss, for the sake of Christ.

[[philippians-3-8]]
^8^ Yet truly, I consider everything to be a loss, because of the preeminent knowledge of Jesus Christ, my Lord, for whose sake I have suffered the loss of everything, considering it all to be like dung, so that I may gain Christ,

[[philippians-3-9]]
^9^ and so that you may be found in him, not having my justice, which is of the law, but that which is of the faith of Christ Jesus, the justice within faith, which is of God.

[[philippians-3-10]]
^10^ So shall I know him, and the power of his resurrection, and the fellowship of his Passion, having been fashioned according to his death,

[[philippians-3-11]]
^11^ if, by some means, I might attain to the resurrection which is from the dead.

[[philippians-3-12]]
^12^ It is not as though I have already received this, or were already perfect. But rather I pursue, so that by some means I might attain, that in which I have already been attained by Christ Jesus.

[[philippians-3-13]]
^13^ Brothers, I do not consider that I have already attained this. Instead, I do one thing: forgetting those things that are behind, and extending myself toward those things that are ahead,

[[philippians-3-14]]
^14^ I pursue the destination, the prize of the heavenly calling of God in Christ Jesus.

[[philippians-3-15]]
^15^ Therefore, as many of us as are being perfected, let us agree about this. And if in anything you disagree, God will reveal this to you also.

[[philippians-3-16]]
^16^ Yet truly, whatever point we reach, let us be of the same mind, and let us remain in the same rule.

[[philippians-3-17]]
^17^ Be imitators of me, brothers, and observe those who are walking similarly, just as you have seen by our example.

[[philippians-3-18]]
^18^ For many persons, about whom I have often told you (and now tell you, weeping,) are walking as enemies of the cross of Christ.

[[philippians-3-19]]
^19^ Their end is destruction; their god is their belly; and their glory is in their shame: for they are immersed in earthly things.

[[philippians-3-20]]
^20^ But our way of life is in heaven. And from heaven, too, we await the Savior, our Lord Jesus Christ,

[[philippians-3-21]]
^21^ who will transform the body of our lowliness, according to the form of the body of his glory, by means of that power by which he is even able to subject all things to himself.


[[philippians-4]]
== Chapter 4

[[philippians-4-1]]
^1^ And so, my most beloved and most desired brothers, my joy and my crown: stand firm in this way, in the Lord, most beloved.

[[philippians-4-2]]
^2^ I ask Euodia, and I beg Syntyche, to have the same understanding in the Lord.

[[philippians-4-3]]
^3^ And I also ask you, as my genuine companion, to assist those women who have labored with me in the Gospel, with Clement and the rest of my assistants, whose names are in the Book of Life.

[[philippians-4-4]]
^4^ Rejoice in the Lord always. Again, I say, rejoice.

[[philippians-4-5]]
^5^ Let your modesty be known to all men. The Lord is near.

[[philippians-4-6]]
^6^ Be anxious about nothing. But in all things, with prayer and supplication, with acts of thanksgiving, let your petitions be made known to God.

[[philippians-4-7]]
^7^ And so shall the peace of God, which exceeds all understanding, guard your hearts and minds in Christ Jesus.

[[philippians-4-8]]
^8^ Concerning the rest, brothers, whatever is true, whatever is chaste, whatever is just, whatever is holy, whatever is worthy to be loved, whatever is of good repute, if there is any virtue, if there is any praiseworthy discipline: meditate on these.

[[philippians-4-9]]
^9^ All the things that you have learned and accepted and heard and seen in me, do these. And so shall the God of peace be with you.

[[philippians-4-10]]
^10^ Now I rejoice in the Lord exceedingly, because finally, after some time, your feelings for me have flourished again, just as you formerly felt. For you had been preoccupied.

[[philippians-4-11]]
^11^ I am not saying this as if out of need. For I have learned that, in whatever state I am, it is sufficient.

[[philippians-4-12]]
^12^ I know how to be humbled, and I know how to abound. I am prepared for anything, anywhere: either to be full or to be hungry, either to have abundance or to endure scarcity.

[[philippians-4-13]]
^13^ Everything is possible in him who has strengthened me.

[[philippians-4-14]]
^14^ Yet truly, you have done well by sharing in my tribulation.

[[philippians-4-15]]
^15^ But you also know, O Philippians, that at the beginning of the Gospel, when I set out from Macedonia, not a single church shared with me in the plan of giving and receiving, except you alone.

[[philippians-4-16]]
^16^ For you even sent to Thessalonica, once, and then a second time, for what was useful to me.

[[philippians-4-17]]
^17^ It is not that I am seeking a gift. Instead, I seek the fruit that abounds to your benefit.

[[philippians-4-18]]
^18^ But I have everything in abundance. I have been filled up, having received from Epaphroditus the things that you sent; this is an odor of sweetness, an acceptable sacrifice, pleasing to God.

[[philippians-4-19]]
^19^ And may my God fulfill all your desires, according to his riches in glory in Christ Jesus.

[[philippians-4-20]]
^20^ And to God our Father be glory forever and ever. Amen.

[[philippians-4-21]]
^21^ Greet every saint in Christ Jesus.

[[philippians-4-22]]
^22^ The brothers who are with me greet you. All the saints greet you, but especially those who are of Caesar’s household.

[[philippians-4-23]]
^23^ May the grace of our Lord Jesus Christ be with your spirit. Amen.
