[[colossians]]
= The Letter to the Colossians
:short: Colossians

[[colossians-1]]
== Chapter 1

[[colossians-1-1]]
^1^ Paul, an Apostle of Jesus Christ by the will of God, and Timothy, a brother,

[[colossians-1-2]]
^2^ to the saints and faithful brothers in Christ Jesus who are at Colossae.

[[colossians-1-3]]
^3^ Grace and peace to you, from God our Father and from the Lord Jesus Christ. We give thanks to God, the Father of our Lord Jesus Christ, praying for you always.

[[colossians-1-4]]
^4^ For we have heard of your faith in Christ Jesus, and of the love that you have toward all the saints,

[[colossians-1-5]]
^5^ because of the hope that has been stored up for you in heaven, which you have heard through the Word of Truth in the Gospel.

[[colossians-1-6]]
^6^ This has reached you, just as it is present in the whole world, where it grows and bears fruit, as it has also done in you, since the day when you first heard and knew the grace of God in truth,

[[colossians-1-7]]
^7^ just as you learned it from Epaphras, our most beloved fellow servant, who is for you a faithful minister of Christ Jesus.

[[colossians-1-8]]
^8^ And he has also manifested to us your love in the Spirit.

[[colossians-1-9]]
^9^ Then, too, from the day when we first heard it, we have not ceased praying for you and requesting that you be filled with the knowledge of his will, with all wisdom and spiritual understanding,

[[colossians-1-10]]
^10^ so that you may walk in a manner worthy of God, being pleasing in all things, being fruitful in every good work, and increasing in the knowledge of God,

[[colossians-1-11]]
^11^ being strengthened in every virtue, in accord with the power of his glory, with all patience and longsuffering, with joy,

[[colossians-1-12]]
^12^ giving thanks to God the Father, who has made us worthy to have a share in the portion of the saints, in the light.

[[colossians-1-13]]
^13^ For he has rescued us from the power of darkness, and he has transferred us into the kingdom of the Son of his love,

[[colossians-1-14]]
^14^ in whom we have redemption through his blood, the remission of sins.

[[colossians-1-15]]
^15^ He is the image of the invisible God, the first-born of every creature.

[[colossians-1-16]]
^16^ For in him was created everything in heaven and on earth, visible and invisible, whether thrones, or dominations, or principalities, or powers. All things were created through him and in him.

[[colossians-1-17]]
^17^ And he is before all, and in him all things continue.

[[colossians-1-18]]
^18^ And he is the head of his body, the Church. He is the beginning, the first-born from the dead, so that in all things he may hold primacy.

[[colossians-1-19]]
^19^ For the Father is well-pleased that all fullness reside in him,

[[colossians-1-20]]
^20^ and that, through him, all things be reconciled to himself, making peace through the blood of his cross, for the things that are on earth, as well as the things that are in heaven.

[[colossians-1-21]]
^21^ And you, though you had been, in times past, understood to be foreigners and enemies, with works of evil,

[[colossians-1-22]]
^22^ yet now he has reconciled you, by his body of flesh, through death, so as to offer you, holy and immaculate and blameless, before him.

[[colossians-1-23]]
^23^ So then, continue in the faith: well-founded and steadfast and immovable, by the hope of the Gospel that you have heard, which has been preached throughout all creation under heaven, the Gospel of which I, Paul, have become a minister.

[[colossians-1-24]]
^24^ For now I rejoice in my passion on your behalf, and I complete in my flesh the things that are lacking in the Passion of Christ, for the sake of his body, which is the Church.

[[colossians-1-25]]
^25^ For I have become a minister of the Church, according to the dispensation of God that has been given to me among you, so that I may fulfill the Word of God,

[[colossians-1-26]]
^26^ the mystery which had remained hidden to past ages and generations, but which now is manifested to his saints.

[[colossians-1-27]]
^27^ To them, God willed to make known the riches of the glory of this mystery among the Gentiles, which is Christ and the hope of his glory within you.

[[colossians-1-28]]
^28^ We are announcing him, correcting every man and teaching every man, with all wisdom, so that we may offer every man perfect in Christ Jesus.

[[colossians-1-29]]
^29^ In him, too, I labor, striving according to his action within me, which he works in virtue.


[[colossians-2]]
== Chapter 2

[[colossians-2-1]]
^1^ For I want you to know the kind of solicitude that I have for you, and for those who are at Laodicea, as well as for those who have not seen my face in the flesh.

[[colossians-2-2]]
^2^ May their hearts be consoled and instructed in charity, with all the riches of a plenitude of understanding, with knowledge of the mystery of God the Father and of Christ Jesus.

[[colossians-2-3]]
^3^ For in him are hidden all treasures of wisdom and knowledge.

[[colossians-2-4]]
^4^ Now I say this, so that no one may deceive you with grandiose words.

[[colossians-2-5]]
^5^ For though I may be absent in body, yet I am with you in spirit. And I rejoice as I gaze upon your order and its foundation, which is in Christ, your faith.

[[colossians-2-6]]
^6^ Therefore, just as you have received the Lord Jesus Christ, walk in him.

[[colossians-2-7]]
^7^ Be rooted and continually built up in Christ. And be confirmed in the faith, just as you have also learned it, increasing in him with acts of thanksgiving.

[[colossians-2-8]]
^8^ See to it that no one deceives you through philosophy and empty falsehoods, as found in the traditions of men, in accord with the influences of the world, and not in accord with Christ.

[[colossians-2-9]]
^9^ For in him, all the fullness of the Divine Nature dwells bodily.

[[colossians-2-10]]
^10^ And in him, you have been filled; for he is the head of all principality and power.

[[colossians-2-11]]
^11^ In him also, you have been circumcised with a circumcision not made by hand, not by the despoiling of the body of flesh, but by the circumcision of Christ.

[[colossians-2-12]]
^12^ You have been buried with him in baptism. In him also, you have risen again through faith, by the work of God, who raised him up from the dead.

[[colossians-2-13]]
^13^ And when you were dead in your transgressions and in the uncircumcision of your flesh, he enlivened you, together with him, forgiving you of all transgressions,

[[colossians-2-14]]
^14^ and wiping away the handwriting of the decree which was against us, which was contrary to us. And he has taken this away from your midst, affixing it to the Cross.

[[colossians-2-15]]
^15^ And so, despoiling principalities and powers, he has led them away confidently and openly, triumphing over them in himself.

[[colossians-2-16]]
^16^ Therefore, let no one judge you as concerns food or drink, or a particular feast day, or feast days of new moons, or of Sabbaths.

[[colossians-2-17]]
^17^ For these are a shadow of the future, but the body is of Christ.

[[colossians-2-18]]
^18^ Let no one seduce you, preferring base things and a religion of Angels, walking according to what he has not seen, being vainly inflated by the sensations of his flesh,

[[colossians-2-19]]
^19^ and not holding up the head, with which the whole body, by its underlying joints and ligaments, is joined together and grows with an increase that is of God.

[[colossians-2-20]]
^20^ So then, if you have died with Christ to the influences of this world, why do you still make decisions as if you were living in the world?

[[colossians-2-21]]
^21^ Do not touch, do not taste, do not handle these things,

[[colossians-2-22]]
^22^ which all lead to destruction by their very use, in accord with the precepts and doctrines of men.

[[colossians-2-23]]
^23^ Such ideas have at least an intention to attain to wisdom, but through superstition and debasement, not sparing the body, and they are without any honor in satiating the flesh.


[[colossians-3]]
== Chapter 3

[[colossians-3-1]]
^1^ Therefore, if you have risen together with Christ, seek the things that are above, where Christ is seated at the right hand of God.

[[colossians-3-2]]
^2^ Consider the things that are above, not the things that are upon the earth.

[[colossians-3-3]]
^3^ For you have died, and so your life is hidden with Christ in God.

[[colossians-3-4]]
^4^ When Christ, your life, appears, then you also will appear with him in glory.

[[colossians-3-5]]
^5^ Therefore, mortify your body, while it is upon the earth. For because of fornication, impurity, lust, evil desires, and avarice, which are a kind of service to idols,

[[colossians-3-6]]
^6^ the wrath of God has overwhelmed the sons of unbelief.

[[colossians-3-7]]
^7^ You, too, walked in these things, in times past, when you were living among them.

[[colossians-3-8]]
^8^ But now you must set aside all these things: anger, indignation, malice, blasphemy, and indecent speech from your mouth.

[[colossians-3-9]]
^9^ Do not lie to one another. Strip yourselves of the old man, with his deeds,

[[colossians-3-10]]
^10^ and clothe yourself with the new man, who has been renewed by knowledge, in accord with the image of the One who created him,

[[colossians-3-11]]
^11^ where there is neither Gentile nor Jew, circumcision nor uncircumcision, Barbarian nor Scythian, servant nor free. Instead, Christ is everything, in everyone.

[[colossians-3-12]]
^12^ Therefore, clothe yourselves like the elect of God: holy and beloved, with hearts of mercy, kindness, humility, modesty, and patience.

[[colossians-3-13]]
^13^ Support one another, and, if anyone has a complaint against another, forgive one another. For just as the Lord has forgiven you, so also must you do.

[[colossians-3-14]]
^14^ And above all these things have charity, which is the bond of perfection.

[[colossians-3-15]]
^15^ And let the peace of Christ lift up your hearts. For in this peace, you have been called, as one body. And be thankful.

[[colossians-3-16]]
^16^ Let the word of Christ live in you in abundance, with all wisdom, teaching and correcting one another, with psalms, hymns, and spiritual canticles, singing to God with the grace in your hearts.

[[colossians-3-17]]
^17^ Let everything whatsoever that you do, whether in word or in deed, be done all in the name of the Lord Jesus Christ, giving thanks to God the Father through him.

[[colossians-3-18]]
^18^ Wives, be submissive to your husbands, as is proper in the Lord.

[[colossians-3-19]]
^19^ Husbands, love your wives, and do not be bitter toward them.

[[colossians-3-20]]
^20^ Children, obey your parents in all things. For this is well-pleasing to the Lord.

[[colossians-3-21]]
^21^ Fathers, do not provoke your children to indignation, lest they lose heart.

[[colossians-3-22]]
^22^ Servants, obey, in all things, your lords according to the flesh, not serving only when seen, as if to please men, but serving in simplicity of heart, fearing God.

[[colossians-3-23]]
^23^ Whatever you do, do it from the heart, as for the Lord, and not for men.

[[colossians-3-24]]
^24^ For you know that you will receive from the Lord the repayment of an inheritance. Serve Christ the Lord.

[[colossians-3-25]]
^25^ For whoever causes injury shall be repaid for what he has wrongfully done. And there no favoritism with God.


[[colossians-4]]
== Chapter 4

[[colossians-4-1]]
^1^ You masters, supply your servants with what is just and equitable, knowing that you, too, have a Master in heaven.

[[colossians-4-2]]
^2^ Pursue prayer. Be watchful in prayer with acts of thanksgiving.

[[colossians-4-3]]
^3^ Pray together, for us also, so that God may open a door of speech to us, so as to speak the mystery of Christ, (because of which, even now, I am in chains)

[[colossians-4-4]]
^4^ so that I may manifest it in the manner that I ought to speak.

[[colossians-4-5]]
^5^ Walk in wisdom toward those who are outside, redeeming this age.

[[colossians-4-6]]
^6^ Let your speech be ever graceful, seasoned with salt, so that you may know how you ought to respond to each person.

[[colossians-4-7]]
^7^ As for the things that concern me, Tychicus, a most beloved brother and faithful minister and fellow servant in the Lord, will make everything known to you.

[[colossians-4-8]]
^8^ I have sent him to you for this very purpose, so that he may know the things that concern you, and may console your hearts,

[[colossians-4-9]]
^9^ with Onesimus, a most beloved and faithful brother, who is from among you. They shall make known to you everything that is happening here.

[[colossians-4-10]]
^10^ Aristarchus, my fellow prisoner, greets you, as does Mark, the near cousin of Barnabas, about whom you have received instructions, (if he comes to you, receive him)

[[colossians-4-11]]
^11^ and Jesus, who is called Justus, and those who are of the circumcision. These alone are my assistants, unto the kingdom of God; they have been a consolation to me.

[[colossians-4-12]]
^12^ Epaphras greets you, who is from among you, a servant of Christ Jesus, ever solicitous for you in prayer, so that you may stand, perfect and complete, in the entire will of God.

[[colossians-4-13]]
^13^ For I offer testimony to him, that he has labored greatly for you, and for those who are at Laodicea, and for those at Hierapolis.

[[colossians-4-14]]
^14^ Luke, a most beloved physician, greets you, as does Demas.

[[colossians-4-15]]
^15^ Greet the brothers who are at Laodicea, and Nymphas, and those who are at his house, a church.

[[colossians-4-16]]
^16^ And when this epistle has been read among you, cause it to be read also in the church of the Laodiceans, and you should read that which is from the Laodiceans.

[[colossians-4-17]]
^17^ And tell Archippus: “See to the ministry that you have received in the Lord, in order to fulfill it.”

[[colossians-4-18]]
^18^ The greeting of Paul by my own hand. Remember my chains. May grace be with you. Amen.
