[[first-thessalonians]]
= The First Letter to the Thessalonians
:short: 1st Thessalonians

[[first-thessalonians-1]]
== Chapter 1

[[first-thessalonians-1-1]]
^1^ Paul and Sylvanus and Timothy, to the church of the Thessalonians, in God the Father and the Lord Jesus Christ.

[[first-thessalonians-1-2]]
^2^ Grace and peace to you. We give thanks to God always for all of you, keeping the memory of you in our prayers without ceasing,

[[first-thessalonians-1-3]]
^3^ remembering your work of faith, and hardship, and charity, and enduring hope, in our Lord Jesus Christ, before God our Father.

[[first-thessalonians-1-4]]
^4^ For we know, brothers, beloved of God, of your election.

[[first-thessalonians-1-5]]
^5^ For our Gospel has not been among you in word alone, but also in virtue, and in the Holy Spirit, and with a great fullness, in the same manner as you know we have acted among you for your sake.

[[first-thessalonians-1-6]]
^6^ And so, you became imitators of us and of the Lord, accepting the Word in the midst of great tribulation, but with the joy of the Holy Spirit.

[[first-thessalonians-1-7]]
^7^ So have you become a pattern for all who believe in Macedonia and in Achaia.

[[first-thessalonians-1-8]]
^8^ For from you, the Word of the Lord was spread, not only in Macedonia and in Achaia, but also in every place. Your faith, which is toward God, has advanced so much so that we do not need to speak to you about anything.

[[first-thessalonians-1-9]]
^9^ For others are reporting among us of the kind of acceptance we had among you, and how you were converted from idols to God, to the service of the living and true God,

[[first-thessalonians-1-10]]
^10^ and to the expectation of his Son from heaven (whom he raised up from the dead), Jesus, who has rescued us from the approaching wrath.


[[first-thessalonians-2]]
== Chapter 2

[[first-thessalonians-2-1]]
^1^ For you yourselves know, brothers, that our acceptance among you was not empty.

[[first-thessalonians-2-2]]
^2^ Instead, having previously suffered and been treated shamefully, as you know, at Philippi, we had confidence in our God, so as to speak the Gospel of God to you with much solicitude.

[[first-thessalonians-2-3]]
^3^ For our exhortation was not in error, nor from impurity, nor with deception.

[[first-thessalonians-2-4]]
^4^ But, just as we have been tested by God, so that the Gospel would be entrusted to us, so also did we speak, not so as to please men, but rather to please God, who tests our hearts.

[[first-thessalonians-2-5]]
^5^ And neither did we, at any time, become flattering in speech, as you know, nor did we seek an opportunity for avarice, as God is witness.

[[first-thessalonians-2-6]]
^6^ Nor did we seek the glory of men, neither from you, nor from others.

[[first-thessalonians-2-7]]
^7^ And although we could have been a burden to you, as Apostles of Christ, instead we became like little ones in your midst, like a nurse cherishing her children.

[[first-thessalonians-2-8]]
^8^ So desirous were we for you that we were willing to hand over to you, not only the Gospel of God, but even our own souls. For you have become most beloved to us.

[[first-thessalonians-2-9]]
^9^ For you remember, brothers, our hardship and weariness. We preached the Gospel of God among you, working night and day, so that we would not be burdensome to any of you.

[[first-thessalonians-2-10]]
^10^ You are witnesses, as is God, of how holy and just and blameless we were with you who have believed.

[[first-thessalonians-2-11]]
^11^ And you know the manner, with each one of you, like a father with his sons,

[[first-thessalonians-2-12]]
^12^ in which we were pleading with you and consoling you, bearing witness, so that you would walk in a manner worthy of God, who has called you into his kingdom and glory.

[[first-thessalonians-2-13]]
^13^ For this reason also, we give thanks to God without ceasing: because, when you had accepted from us the Word of the hearing of God, you accepted it not as the word of men, but (as it truly is) as the Word of God, who is working in you who have believed.

[[first-thessalonians-2-14]]
^14^ For you, brothers, have become imitators of the churches of God which are at Judea, in Christ Jesus. For you, too, have suffered the same things from your fellow countrymen as they have suffered from the Jews,

[[first-thessalonians-2-15]]
^15^ who also killed both the Lord Jesus, and the Prophets, and who have persecuted us. But they do not please God, and so they are adversaries to all men.

[[first-thessalonians-2-16]]
^16^ They prohibit us to speak to the Gentiles, so that they may be saved, and thus do they continually add to their own sins. But the wrath of God will overtake them in the very end.

[[first-thessalonians-2-17]]
^17^ And we, brothers, having been deprived of you for a short time, in sight, but not in heart, have hurried all the more to see your face, with a great desire.

[[first-thessalonians-2-18]]
^18^ For we wanted to come to you, (indeed, I, Paul, attempted to do so once, and then again,) but Satan impeded us.

[[first-thessalonians-2-19]]
^19^ For what is our hope, and our joy, and our crown of glory? Is it not you, before our Lord Jesus Christ at his return?

[[first-thessalonians-2-20]]
^20^ For you are our glory and our joy.


[[first-thessalonians-3]]
== Chapter 3

[[first-thessalonians-3-1]]
^1^ Because of this, willing to wait no longer, it was pleasing to us to remain at Athens, alone.

[[first-thessalonians-3-2]]
^2^ And we sent Timothy, our brother and a minister of God in the Gospel of Christ, to confirm you and to exhort you, on behalf of your faith,

[[first-thessalonians-3-3]]
^3^ so that no one would be disturbed during these tribulations. For you yourselves know that we have been appointed to this.

[[first-thessalonians-3-4]]
^4^ For even while we were with you, we predicted to you that we would suffer tribulations, even as it has happened, and as you know.

[[first-thessalonians-3-5]]
^5^ For this reason also, I was not willing to wait any longer, and I sent to find out about your faith, lest perhaps he who tempts may have tempted you, and our labor might have been in vain.

[[first-thessalonians-3-6]]
^6^ But then, when Timothy arrived to us from you, he reported to us your faith and charity, and that you keep a good remembrance of us always, desiring to see us, just as we likewise desire to see you.

[[first-thessalonians-3-7]]
^7^ As a result, we were consoled in you, brothers, in the midst of all our difficulties and tribulations, through your faith.

[[first-thessalonians-3-8]]
^8^ For we now live so that you may stand firm in the Lord.

[[first-thessalonians-3-9]]
^9^ For what thanks would we be able to repay to God because of you, for all the joy with which we rejoice over you before our God?

[[first-thessalonians-3-10]]
^10^ For night and day, ever more abundantly, we are praying that we may see your face, and that we may complete those things that are lacking in your faith.

[[first-thessalonians-3-11]]
^11^ But may God our Father himself, and our Lord Jesus Christ, direct our way to you.

[[first-thessalonians-3-12]]
^12^ And may the Lord multiply you, and make you abound in your charity toward one another and toward all, just as we also do toward you,

[[first-thessalonians-3-13]]
^13^ in order to confirm your hearts without blame, in sanctity, before God our Father, unto the return of our Lord Jesus Christ, with all his saints. Amen.


[[first-thessalonians-4]]
== Chapter 4

[[first-thessalonians-4-1]]
^1^ Therefore, concerning other things, brothers, we ask and beg you, in the Lord Jesus, that, just as you have received from us the way in which you ought to walk and to please God, so also may you walk, in order that you may abound all the more.

[[first-thessalonians-4-2]]
^2^ For you know what precepts I have given to you through the Lord Jesus.

[[first-thessalonians-4-3]]
^3^ For this is the will of God, your sanctification: that you should abstain from fornication,

[[first-thessalonians-4-4]]
^4^ that each one of you should know how to possess his vessel in sanctification and honor,

[[first-thessalonians-4-5]]
^5^ not in passions of lust, like the Gentiles who do not know God,

[[first-thessalonians-4-6]]
^6^ and that no one should overwhelm or circumvent his brother in business. For the Lord is the vindicator of all these things, just as we have preached and testified to you.

[[first-thessalonians-4-7]]
^7^ For God has not called us to impurity, but to sanctification.

[[first-thessalonians-4-8]]
^8^ And so, whoever despises these teachings, does not despise man, but God, who has even provided his Holy Spirit within us.

[[first-thessalonians-4-9]]
^9^ But concerning the charity of brotherhood, we have no need to write to you. For you yourselves have learned from God that you should love one another.

[[first-thessalonians-4-10]]
^10^ For indeed, you act in this way with all the brothers in all of Macedonia. But we petition you, brothers, so that you may abound all the more,

[[first-thessalonians-4-11]]
^11^ to choose work that allows you to be tranquil, and to carry out your business and to do your work with your own hands, just as we have instructed you,

[[first-thessalonians-4-12]]
^12^ and to walk honestly with those who are outside, and to desire nothing belonging to another.

[[first-thessalonians-4-13]]
^13^ And we do not want you to be ignorant, brothers, concerning those who are sleeping, so as not to be sorrowful, like these others who do not have hope.

[[first-thessalonians-4-14]]
^14^ For if we believe that Jesus has died and risen again, so also will God bring back with Jesus those who sleep in him.

[[first-thessalonians-4-15]]
^15^ For we say this to you, in the Word of the Lord: that we who are alive, who remain until the return of the Lord, will not precede those who have fallen asleep.

[[first-thessalonians-4-16]]
^16^ For the Lord himself, with a command and with the voice of an Archangel and with a trumpet of God, shall descend from heaven. And the dead, who are in Christ, shall rise up first.

[[first-thessalonians-4-17]]
^17^ Next, we who are alive, who are remaining, shall be taken up quickly together with them into the clouds to meet Christ in the air. And in this way, we shall be with the Lord always.

[[first-thessalonians-4-18]]
^18^ Therefore, console one another with these words.


[[first-thessalonians-5]]
== Chapter 5

[[first-thessalonians-5-1]]
^1^ But concerning dates and times, brothers, you do not need us to write to you.

[[first-thessalonians-5-2]]
^2^ For you yourselves thoroughly understand that the day of the Lord shall arrive much like a thief in the night.

[[first-thessalonians-5-3]]
^3^ For when they will say, “Peace and security!” then destruction will suddenly overwhelm them, like the labor pains of a woman with child, and they will not escape.

[[first-thessalonians-5-4]]
^4^ But you, brothers, are not in darkness, so that you would be overtaken by that day as by a thief.

[[first-thessalonians-5-5]]
^5^ For all of you are sons of light and sons of daytime; we are not of nighttime, nor of darkness.

[[first-thessalonians-5-6]]
^6^ Therefore, let us not sleep, as the rest do. Instead, we should be vigilant and sober.

[[first-thessalonians-5-7]]
^7^ For those who sleep, sleep in the night; and those who are inebriated, are inebriated in the night.

[[first-thessalonians-5-8]]
^8^ But we, who are of the daylight, should be sober, being clothed with the breastplate of faith and of charity and having, as a helmet, the hope of salvation.

[[first-thessalonians-5-9]]
^9^ For God has not appointed us for wrath, but for the acquisition of salvation through our Lord Jesus Christ,

[[first-thessalonians-5-10]]
^10^ who died for us, so that, whether we watch, or whether we sleep, we may live in union with him.

[[first-thessalonians-5-11]]
^11^ Because of this, console one another and build up one another, just as you are doing.

[[first-thessalonians-5-12]]
^12^ And we ask you, brothers, to recognize those who labor among you, and who preside over you in the Lord, and who admonish you,

[[first-thessalonians-5-13]]
^13^ so that you may consider them with an abundance of charity, for the sake of their work. Be at peace with them.

[[first-thessalonians-5-14]]
^14^ And we ask you, brothers: correct the disruptive, console the weak-minded, support the sick, be patient with everyone.

[[first-thessalonians-5-15]]
^15^ See to it that no one repays evil for evil to anyone. Instead, always pursue whatever is good, with one another and with all.

[[first-thessalonians-5-16]]
^16^ Rejoice always.

[[first-thessalonians-5-17]]
^17^ Pray without ceasing.

[[first-thessalonians-5-18]]
^18^ Give thanks in everything. For this is the will of God in Christ Jesus for all of you.

[[first-thessalonians-5-19]]
^19^ Do not choose to extinguish the Spirit.

[[first-thessalonians-5-20]]
^20^ Do not spurn prophecies.

[[first-thessalonians-5-21]]
^21^ But test all things. Hold on to whatever is good.

[[first-thessalonians-5-22]]
^22^ Abstain from every kind of evil.

[[first-thessalonians-5-23]]
^23^ And may the God of peace himself sanctify you through all things, so that your whole spirit and soul and body may be preserved without blame unto the return of our Lord Jesus Christ.

[[first-thessalonians-5-24]]
^24^ He who has called you is faithful. He shall act even now.

[[first-thessalonians-5-25]]
^25^ Brothers, pray for us.

[[first-thessalonians-5-26]]
^26^ Greet all the brothers with a holy kiss.

[[first-thessalonians-5-27]]
^27^ I bind you, through the Lord, that this epistle is to be read to all the holy brothers.

[[first-thessalonians-5-28]]
^28^ May the grace of our Lord Jesus Christ be with you. Amen.

