[[second-thessalonians]]
= The Second Letter to the Thessalonians
:short: 2nd Thessalonians

[[second-thessalonians-1]]
== Chapter 1

[[second-thessalonians-1-1]]
^1^ Paul and Sylvanus and Timothy, to the church of the Thessalonians, in God our Father and the Lord Jesus Christ.

[[second-thessalonians-1-2]]
^2^ Grace and peace to you, from God our Father and from the Lord Jesus Christ.

[[second-thessalonians-1-3]]
^3^ We ought to give thanks always to God for you, brothers, in a fitting manner, because your faith is increasing greatly, and because the charity of each of you toward one another is abundant,

[[second-thessalonians-1-4]]
^4^ so much so that we ourselves even glory in you among the churches of God, because of your patience and faith in all of your persecutions and tribulations that you endure,

[[second-thessalonians-1-5]]
^5^ which are a sign of the just judgment of God, so that you may be held worthy of the kingdom of God, for which you also suffer.

[[second-thessalonians-1-6]]
^6^ For certainly, it is just for God to repay trouble to those who trouble you,

[[second-thessalonians-1-7]]
^7^ and to repay you, who are being troubled, with a repose with us, when the Lord Jesus is revealed from heaven with the Angels of his virtue,

[[second-thessalonians-1-8]]
^8^ granting vindication, by a flame of fire, against those who do not know God and who are not obedient to the Gospel of our Lord Jesus Christ.

[[second-thessalonians-1-9]]
^9^ These shall be given the eternal punishment of destruction, apart from the face of the Lord and apart from the glory of his virtue,

[[second-thessalonians-1-10]]
^10^ when he arrives to be glorified in his saints, and to become a wonder in all those who have believed, in that day, because our testimony has been believed by you.

[[second-thessalonians-1-11]]
^11^ Because of this, too, we pray always for you, so that our God may make you worthy of his calling and may complete every act of his goodness, as well as his work of faith in virtue,

[[second-thessalonians-1-12]]
^12^ in order that the name of our Lord Jesus may be glorified in you, and you in him, in accord with the grace of our God and of the Lord Jesus Christ.


[[second-thessalonians-2]]
== Chapter 2

[[second-thessalonians-2-1]]
^1^ But we ask you, brothers, concerning the advent of our Lord Jesus Christ and of our gathering to him,

[[second-thessalonians-2-2]]
^2^ that you not be readily disturbed or terrified in your minds, by any spirit, or word, or epistle, supposedly sent from us, claiming that the day of the Lord is close by.

[[second-thessalonians-2-3]]
^3^ Let no one deceive you in any way. For this cannot be, unless the apostasy will have arrived first, and the man of sin will have been revealed, the son of perdition,

[[second-thessalonians-2-4]]
^4^ who is an adversary to, and who is lifted up above, all that is called God or that is worshipped, so much so that he sits in the temple of God, presenting himself as if he were God.

[[second-thessalonians-2-5]]
^5^ Do you not recall that, when I was still with you, I told you these things?

[[second-thessalonians-2-6]]
^6^ And now you know what it is that holds him back, so that he may be revealed in his own time.

[[second-thessalonians-2-7]]
^7^ For the mystery of iniquity is already at work. And only one now holds back, and will continue to hold back, until he is taken from our midst.

[[second-thessalonians-2-8]]
^8^ And then that iniquitous one shall be revealed, the one whom the Lord Jesus shall bring to ruin with the spirit of his mouth, and shall destroy at the brightness of his return:

[[second-thessalonians-2-9]]
^9^ him whose advent is accompanied by the works of Satan, with every kind of power and signs and false miracles,

[[second-thessalonians-2-10]]
^10^ and with every seduction of iniquity, toward those who are perishing because they have not accepted the love of truth, so that they may be saved. For this reason, God will send to them works of deception, so that they may believe in lies,

[[second-thessalonians-2-11]]
^11^ in order that all those who have not believed in the truth, but who have consented to iniquity, may be judged.

[[second-thessalonians-2-12]]
^12^ Yet we must always give thanks to God for you, brothers, beloved of God, because God has chosen you as first-fruits for salvation, by the sanctification of the Spirit and by faith in the truth.

[[second-thessalonians-2-13]]
^13^ He has also called you into truth through our Gospel, unto the acquisition of the glory of our Lord Jesus Christ.

[[second-thessalonians-2-14]]
^14^ And so, brothers, stand firm, and hold to the traditions that you have learned, whether by word or by our epistle.

[[second-thessalonians-2-15]]
^15^ So may our Lord Jesus Christ himself, and God our Father, who has loved us and who has given us an everlasting consolation and good hope in grace,

[[second-thessalonians-2-16]]
^16^ exhort your hearts and confirm you in every good word and deed.


[[second-thessalonians-3]]
== Chapter 3

[[second-thessalonians-3-1]]
^1^ Concerning other things, brothers, pray for us, so that the Word of God may advance and be glorified, just as it is among you,

[[second-thessalonians-3-2]]
^2^ and so that we may be freed from pertinacious and evil men. For not everyone is faithful.

[[second-thessalonians-3-3]]
^3^ But God is faithful. He will strengthen you, and he will guard you from evil.

[[second-thessalonians-3-4]]
^4^ And we have confidence about you in the Lord, that you are doing, and will continue to do, just as we have instructed.

[[second-thessalonians-3-5]]
^5^ And may the Lord direct your hearts, in the charity of God and with the patience of Christ.

[[second-thessalonians-3-6]]
^6^ But we strongly caution you, brothers, in the name of our Lord Jesus Christ, to draw yourselves away from every brother who is walking in disorder and not according to the tradition that they received from us.

[[second-thessalonians-3-7]]
^7^ For you yourselves know the manner in which you ought to imitate us. For we were not disorderly among you.

[[second-thessalonians-3-8]]
^8^ Nor did we eat bread from anyone for free, but rather, we worked night and day, in hardship and weariness, so as not to be burdensome to you.

[[second-thessalonians-3-9]]
^9^ It was not as if we had no authority, but this was so that we might present ourselves as an example to you, in order to imitate us.

[[second-thessalonians-3-10]]
^10^ Then, too, while we were with you, we insisted on this to you: that if anyone was not willing to work, neither should he eat.

[[second-thessalonians-3-11]]
^11^ For we have heard that there are some among you who act disruptively, not working at all, but eagerly meddling.

[[second-thessalonians-3-12]]
^12^ Now we charge those who act in this way, and we beg them in the Lord Jesus Christ, that they work in silence and eat their own bread.

[[second-thessalonians-3-13]]
^13^ And you, brothers, do not grow weak in doing good.

[[second-thessalonians-3-14]]
^14^ But if anyone does not obey our word by this epistle, take note of him and do not keep company with him, so that he may be ashamed.

[[second-thessalonians-3-15]]
^15^ But do not be willing to consider him as an enemy; instead, correct him as a brother.

[[second-thessalonians-3-16]]
^16^ Then may the Lord of peace himself give you an everlasting peace, in every place. May the Lord be with all of you.

[[second-thessalonians-3-17]]
^17^ The greeting of Paul with my own hand, which is the seal in every epistle. So do I write.

[[second-thessalonians-3-18]]
^18^ May the grace of our Lord Jesus Christ be with you all. Amen.
