[[second-timothy]]
= The Second Letter to Timothy
:short: 2nd Timothy

[[second-timothy-1]]
== Chapter 1

[[second-timothy-1-1]]
^1^ Paul, an Apostle of Jesus Christ through the will of God, in accord with the promise of the life which is in Christ Jesus,

[[second-timothy-1-2]]
^2^ to Timothy, most beloved son. Grace, mercy, peace, from God the Father and from Christ Jesus our Lord.

[[second-timothy-1-3]]
^3^ I give thanks to God, whom I serve, as my forefathers did, with a pure conscience. For without ceasing I hold the remembrance of you in my prayers, night and day,

[[second-timothy-1-4]]
^4^ desiring to see you, recalling your tears so as to be filled with joy,

[[second-timothy-1-5]]
^5^ calling to mind the same faith, which is in you unfeigned, which also first dwelt in your grandmother, Lois, and in your mother, Eunice, and also, I am certain, in you.

[[second-timothy-1-6]]
^6^ Because of this, I admonish you to revive the grace of God, which is in you by the imposition of my hands.

[[second-timothy-1-7]]
^7^ For God has not given us a spirit of fear, but of virtue, and of love, and of self-restraint.

[[second-timothy-1-8]]
^8^ And so, do not be ashamed of the testimony of our Lord, nor of me, his prisoner. Instead, collaborate with the Gospel in accord with the virtue of God,

[[second-timothy-1-9]]
^9^ who has freed us and has called us to his holy vocation, not according to our works, but according to his own purpose and grace, which was given to us in Christ Jesus, before the ages of time.

[[second-timothy-1-10]]
^10^ And this has now been made manifest by the illumination of our Savior Jesus Christ, who certainly has destroyed death, and who has also illuminated life and incorruption through the Gospel.

[[second-timothy-1-11]]
^11^ Of this Gospel, I have been appointed a preacher, and an Apostle, and a teacher of the Gentiles.

[[second-timothy-1-12]]
^12^ For this reason, I also suffer these things. But I am not confounded. For I know in whom I have believed, and I am certain that he has the power to preserve what was entrusted to me, unto that day.

[[second-timothy-1-13]]
^13^ Hold to the kind of sound words that you have heard from me in the faith and love which is in Christ Jesus.

[[second-timothy-1-14]]
^14^ Guard the good entrusted to you through the Holy Spirit, who lives within us.

[[second-timothy-1-15]]
^15^ Know this: that all those who are in Asia have turned away from me, among whom are Phigellus and Hermogenes.

[[second-timothy-1-16]]
^16^ May the Lord have mercy on the house of Onesiphorus, because he has often refreshed me, and he has not been ashamed of my chains.

[[second-timothy-1-17]]
^17^ Instead, when he had arrived in Rome, he anxiously sought me and found me.

[[second-timothy-1-18]]
^18^ May the Lord grant to him to obtain mercy from the Lord in that day. And you know well in how many ways he has ministered to me at Ephesus.


[[second-timothy-2]]
== Chapter 2

[[second-timothy-2-1]]
^1^ And as for you, my son, be strengthened by the grace which is in Christ Jesus,

[[second-timothy-2-2]]
^2^ and by the things which you have heard from me through many witnesses. These things encourage faithful men, who shall then be suitable to teach others also.

[[second-timothy-2-3]]
^3^ Labor like a good soldier of Christ Jesus.

[[second-timothy-2-4]]
^4^ No man, acting as a soldier for God, entangles himself in worldly matters, so that he may be pleasing to him for whom he has proven himself.

[[second-timothy-2-5]]
^5^ Then, too, whoever strives in a competition is not crowned, unless he has competed lawfully.

[[second-timothy-2-6]]
^6^ The farmer who labors ought to be the first to share in the produce.

[[second-timothy-2-7]]
^7^ Understand what I am saying. For the Lord will give you understanding in all things.

[[second-timothy-2-8]]
^8^ Be mindful that the Lord Jesus Christ, who is the offspring of David, has risen again from the dead, according to my Gospel.

[[second-timothy-2-9]]
^9^ I labor in this Gospel, even while chained like an evildoer. But the Word of God is not bound.

[[second-timothy-2-10]]
^10^ I endure all things for this reason: for the sake of the elect, so that they, too, may obtain the salvation which is in Christ Jesus, with heavenly glory.

[[second-timothy-2-11]]
^11^ It is a faithful saying: that if we have died with him, we will also live with him.

[[second-timothy-2-12]]
^12^ If we suffer, we will also reign with him. If we deny him, he will also deny us.

[[second-timothy-2-13]]
^13^ If we are unfaithful, he remains faithful: he is not able to deny himself.

[[second-timothy-2-14]]
^14^ Insist on these things, testifying before the Lord. Do not be contentious about words, for this is useful for nothing but the subversion of listeners.

[[second-timothy-2-15]]
^15^ Be solicitous in the task of presenting yourself before God as a proven and unashamed worker who has handled the Word of Truth correctly.

[[second-timothy-2-16]]
^16^ But avoid profane or empty talk. For these things advance one greatly in impiety.

[[second-timothy-2-17]]
^17^ And their word spreads like a cancer: among these are Hymenaeus and Philetus,

[[second-timothy-2-18]]
^18^ who have fallen away from the truth by saying that the resurrection is already complete. And so they have subverted the faith of certain persons.

[[second-timothy-2-19]]
^19^ But the firm foundation of God remains standing, having this seal: the Lord knows those who are his own, and all who know the name of the Lord depart from iniquity.

[[second-timothy-2-20]]
^20^ But, in a large house, there are not only vessels of gold and of silver, but also those of wood and of clay; and certainly some are held in honor, but others in dishonor.

[[second-timothy-2-21]]
^21^ If anyone, then, will have cleansed himself from these things, he shall be a vessel held in honor, sanctified and useful to the Lord, prepared for every good work.

[[second-timothy-2-22]]
^22^ So then, flee from the desires of your youth, yet truly, pursue justice, faith, hope, charity, and peace, along with those who call upon the Lord from a pure heart.

[[second-timothy-2-23]]
^23^ But avoid foolish and undisciplined questions, for you know that these produce strife.

[[second-timothy-2-24]]
^24^ For the servant of the Lord must not be contentious, but instead he must be meek toward everyone, teachable, patient,

[[second-timothy-2-25]]
^25^ correcting with self-restraint those who resist the truth. For at any time God may give them repentance, so as to recognize the truth,

[[second-timothy-2-26]]
^26^ and then they may recover from the snares of the devil, by whom they are held captive at his will.


[[second-timothy-3]]
== Chapter 3

[[second-timothy-3-1]]
^1^ And know this: that in the last days perilous times will press near.

[[second-timothy-3-2]]
^2^ Men will be lovers of themselves, greedy, self-exalting, arrogant, blasphemers, disobedient to parents, ungrateful, wicked,

[[second-timothy-3-3]]
^3^ without affection, without peace, false accusers, unchaste, cruel, without kindness,

[[second-timothy-3-4]]
^4^ traitorous, reckless, self-important, loving pleasure more than God,

[[second-timothy-3-5]]
^5^ even having the appearance of piety while rejecting its virtue. And so, avoid them.

[[second-timothy-3-6]]
^6^ For among these are ones who penetrate houses and lead away, like captives, foolish women burdened with sins, who are led away by means of various desires,

[[second-timothy-3-7]]
^7^ always learning, yet never achieving knowledge of the truth.

[[second-timothy-3-8]]
^8^ And in the same manner that Jannes and Jambres resisted Moses, so also will these resist the truth, men corrupted in mind, reprobates from the faith.

[[second-timothy-3-9]]
^9^ But they will not advance beyond a certain point. For the folly of the latter shall be made manifest to all, just as that of the former.

[[second-timothy-3-10]]
^10^ But you have fully comprehended my doctrine, instruction, purpose, faith, longsuffering, love, patience,

[[second-timothy-3-11]]
^11^ persecutions, afflictions; such things as happened to me at Antioch, at Iconium, and at Lystra; how I endured persecutions, and how the Lord rescued me from everything.

[[second-timothy-3-12]]
^12^ And all those who willingly live the piety in Christ Jesus will suffer persecution.

[[second-timothy-3-13]]
^13^ But evil men and deceivers will advance in evil, erring and sending into error.

[[second-timothy-3-14]]
^14^ Yet truly, you should remain in those things which you have learned and which have been entrusted to you. For you know from whom you have learned them.

[[second-timothy-3-15]]
^15^ And, from your infancy, you have known the Sacred Scriptures, which are able to instruct you toward salvation, through the faith which is in Christ Jesus.

[[second-timothy-3-16]]
^16^ All Scripture, having been divinely inspired, is useful for teaching, for reproof, for correction, and for instruction in justice,

[[second-timothy-3-17]]
^17^ so that the man of God may be perfect, having been trained for every good work.


[[second-timothy-4]]
== Chapter 4

[[second-timothy-4-1]]
^1^ I testify before God, and before Jesus Christ, who shall judge the living and the dead through his return and his kingdom:

[[second-timothy-4-2]]
^2^ that you should preach the word urgently, in season and out of season: reprove, entreat, rebuke, with all patience and doctrine.

[[second-timothy-4-3]]
^3^ For there shall be a time when they will not endure sound doctrine, but instead, according to their own desires, they will gather to themselves teachers, with itching ears,

[[second-timothy-4-4]]
^4^ and certainly, they will turn their hearing away from the truth, and they will be turned toward fables.

[[second-timothy-4-5]]
^5^ But as for you, truly, be vigilant, laboring in all things. Do the work of an Evangelist, fulfilling your ministry. Show self-restraint.

[[second-timothy-4-6]]
^6^ For I am already being worn away, and the time of my dissolution presses close.

[[second-timothy-4-7]]
^7^ I have fought the good fight. I have completed the course. I have preserved the faith.

[[second-timothy-4-8]]
^8^ As for the remainder, a crown of justice has been reserved for me, one which the Lord, the just judge, will render to me in that day, and not only to me, but also to those who look forward to his return. Hurry to return to me soon.

[[second-timothy-4-9]]
^9^ For Demas has abandoned me, out of love for this age, and he has departed for Thessalonica.

[[second-timothy-4-10]]
^10^ Crescens has gone to Galatia; Titus to Dalmatia.

[[second-timothy-4-11]]
^11^ Luke alone is with me. Take Mark and bring him with you; for he is useful to me in the ministry.

[[second-timothy-4-12]]
^12^ But Tychicus I have sent to Ephesus.

[[second-timothy-4-13]]
^13^ When you return, bring with you the supplies that I left with Carpus at Troas, and the books, but especially the parchments.

[[second-timothy-4-14]]
^14^ Alexander the coppersmith has shown me much evil; the Lord will repay him according to his works.

[[second-timothy-4-15]]
^15^ And you should also avoid him; for he has strongly resisted our words.

[[second-timothy-4-16]]
^16^ At my first defense, no one stood by me, but everyone abandoned me. May it not be counted against them!

[[second-timothy-4-17]]
^17^ But the Lord stood with me and strengthened me, so that through me the preaching would be accomplished, and so that all the Gentiles would hear. And I was freed from the mouth of the lion.

[[second-timothy-4-18]]
^18^ The Lord has freed me from every evil work, and he will accomplish salvation by his heavenly kingdom. To him be glory forever and ever. Amen.

[[second-timothy-4-19]]
^19^ Greet Prisca, and Aquila, and the household of Onesiphorus.

[[second-timothy-4-20]]
^20^ Erastus remained at Corinth. And Trophimus I left sick at Miletus.

[[second-timothy-4-21]]
^21^ Hurry to arrive before winter. Eubulus, and Pudens, and Linus, and Claudia, and all the brothers greet you.

[[second-timothy-4-22]]
^22^ May the Lord Jesus Christ be with your spirit. May grace be with you. Amen.
