[[philemon]]
= The Letter to Philemon
:short: Philemon

[[philemon-1]]
== Chapter 1

[[philemon-1-1]]
^1^ Paul, a prisoner of Christ Jesus, and Timothy, a brother, to Philemon, our beloved fellow laborer,

[[philemon-1-2]]
^2^ and to Apphia, most beloved sister, and to Archippus, our fellow soldier, and to the church which is in your house.

[[philemon-1-3]]
^3^ Grace and peace to you, from God our Father and from the Lord Jesus Christ.

[[philemon-1-4]]
^4^ I give thanks to my God, always keeping remembrance of you in my prayers,

[[philemon-1-5]]
^5^ (for I am hearing of your charity and faith, which you have in the Lord Jesus and with all the saints)

[[philemon-1-6]]
^6^ so that the participation of your faith may become evident by the recognition of every good work which is in you in Christ Jesus.

[[philemon-1-7]]
^7^ For I have found great joy and consolation in your charity, because the hearts of the saints have been refreshed by you, brother.

[[philemon-1-8]]
^8^ Because of this, I have enough confidence in Christ Jesus to command you concerning certain things,

[[philemon-1-9]]
^9^ but I beg you instead, for the sake of charity, since you are so much like Paul: an old man and now also a prisoner of Jesus Christ.

[[philemon-1-10]]
^10^ I beg you, on behalf of my son, whom I have begotten in my chains, Onesimus.

[[philemon-1-11]]
^11^ In times past, he was useless to you, but now he is useful both to me and to you.

[[philemon-1-12]]
^12^ So I have sent him back to you. And may you receive him like my own heart.

[[philemon-1-13]]
^13^ I myself wanted to retain him with me, so that he might minister to me, on your behalf, while I am in the chains of the Gospel.

[[philemon-1-14]]
^14^ But I was willing to do nothing without your counsel, so as not to make use of your good deed as if out of necessity, but only willingly.

[[philemon-1-15]]
^15^ So perhaps, then, he departed from you for a time, so that you might receive him again for eternity,

[[philemon-1-16]]
^16^ no longer as a servant, but, in place of a servant, a most beloved brother, especially to me: but how much more to you, both in the flesh and in the Lord!

[[philemon-1-17]]
^17^ Therefore, if you hold me to be a companion, receive him as you would me.

[[philemon-1-18]]
^18^ But if he has harmed you in any way, or if he is in your debt, charge it to me.

[[philemon-1-19]]
^19^ I, Paul, have written this with my own hand: I will repay. And I need not tell you, that you are also in debt yourself, to me.

[[philemon-1-20]]
^20^ So it is, brother. May I delight with you in the Lord! Refresh my heart in Christ.

[[philemon-1-21]]
^21^ I have written to you, trusting in your obedience, knowing, too, that you will do even more than what I say.

[[philemon-1-22]]
^22^ But also, at once, prepare a lodging for me. For I am hoping, through your prayers, to present myself to you.

[[philemon-1-23]]
^23^ Greet Epaphras, my fellow captive in Christ Jesus,

[[philemon-1-24]]
^24^ and Mark, Aristarchus, Demas, and Luke, my helpers.

[[philemon-1-25]]
^25^ May the grace of our Lord Jesus Christ be with your spirit. Amen.
