[[james]]
= The Letter of James
:short: James

[[james-1]]
== Chapter 1

[[james-1-1]]
^1^ James, servant of God and of our Lord Jesus Christ, to the twelve tribes of the dispersion, greetings.

[[james-1-2]]
^2^ My brothers, when you have fallen into various trials, consider everything a joy,

[[james-1-3]]
^3^ knowing that the proving of your faith exercises patience,

[[james-1-4]]
^4^ and patience brings a work to perfection, so that you may be perfect and whole, deficient in nothing.

[[james-1-5]]
^5^ But if anyone among you is in need of wisdom, let him petition God, who gives abundantly to all without reproach, and it shall be given to him.

[[james-1-6]]
^6^ But he should ask with faith, doubting nothing. For he who doubts is like a wave on the ocean, which is moved about by the wind and carried away;

[[james-1-7]]
^7^ then a man should not consider that he would receive anything from the Lord.

[[james-1-8]]
^8^ For a man who is of two minds is inconstant in all his ways.

[[james-1-9]]
^9^ Now a humble brother should glory in his exaltation,

[[james-1-10]]
^10^ and a rich one, in his humiliation, for he will pass away like the flower of the grass.

[[james-1-11]]
^11^ For the sun has risen with a scorching heat, and has dried the grass, and its flower has fallen off, and the appearance of its beauty has perished. So also will the rich one wither away, according to his paths.

[[james-1-12]]
^12^ Blessed is the man who suffers temptation. For when he has been proven, he shall receive the crown of life which God has promised to those who love him.

[[james-1-13]]
^13^ No one should say, when he is tempted, that he was tempted by God. For God does not entice toward evils, and he himself tempts no one.

[[james-1-14]]
^14^ Yet truly, each one is tempted by his own desires, having been enticed and drawn away.

[[james-1-15]]
^15^ Thereafter, when desire has conceived, it gives birth to sin. Yet truly sin, when it has been consummated, produces death.

[[james-1-16]]
^16^ And so, do not choose to go astray, my most beloved brothers.

[[james-1-17]]
^17^ Every excellent gift and every perfect gift is from above, descending from the Father of lights, with whom there is no change, nor any shadow of alteration.

[[james-1-18]]
^18^ For by his own will he produced us through the Word of truth, so that we might be a kind of beginning among his creatures.

[[james-1-19]]
^19^ You know this, my most beloved brothers. So let every man be quick to listen, but slow to speak and slow to anger.

[[james-1-20]]
^20^ For the anger of man does not accomplish the justice of God.

[[james-1-21]]
^21^ Because of this, having cast away all uncleanness and an abundance of malice, receive with meekness the newly-grafted Word, which is able to save your souls.

[[james-1-22]]
^22^ So be doers of the Word, and not listeners only, deceiving yourselves.

[[james-1-23]]
^23^ For if anyone is a listener of the Word, but not also a doer, he is comparable to a man gazing into a mirror upon the face that he was born with;

[[james-1-24]]
^24^ and after considering himself, he went away and promptly forgot what he had seen.

[[james-1-25]]
^25^ But he who gazes upon the perfect law of liberty, and who remains in it, is not a forgetful hearer, but instead a doer of the work. He shall be blessed in what he does.

[[james-1-26]]
^26^ But if anyone considers himself to be religious, but he does not restrain his tongue, but instead seduces his own heart: such a one’s religion is vanity.

[[james-1-27]]
^27^ This is religion, clean and undefiled before God the Father: to visit orphans and widows in their tribulations, and to keep yourself immaculate, apart from this age.


[[james-2]]
== Chapter 2

[[james-2-1]]
^1^ My brothers, within the glorious faith of our Lord Jesus Christ, do not choose to show favoritism toward persons.

[[james-2-2]]
^2^ For if a man has entered your assembly having a gold ring and splendid apparel, and if a poor man has also entered, in dirty clothing,

[[james-2-3]]
^3^ and if you are then attentive to the one who is clothed in excellent apparel, so that you say to him, “You may sit in this good place,” but you say to the poor man, “You stand over there,” or, “Sit below my footstool,”

[[james-2-4]]
^4^ are you not judging within yourselves, and have you not become judges with unjust thoughts?

[[james-2-5]]
^5^ My most beloved brothers, listen. Has not God chosen the poor in this world to be rich in faith and heirs of the kingdom that God has promised to those who love him?

[[james-2-6]]
^6^ But you have dishonored the poor. Are not the rich the ones who oppress you through power? And are not they the ones who drag you to judgment?

[[james-2-7]]
^7^ Are not they the ones who blaspheme the good name which has been invoked over you?

[[james-2-8]]
^8^ So if you perfect the regal law, according to the Scriptures, “You shall love your neighbor as yourself,” then you do well.

[[james-2-9]]
^9^ But if you show favoritism to persons, then you commit a sin, having been convicted again by the law as transgressors.

[[james-2-10]]
^10^ Now whoever has observed the whole law, yet who offends in one matter, has become guilty of all.

[[james-2-11]]
^11^ For he who said, “You shall not commit adultery,” also said, “You shall not kill.” So if you do not commit adultery, but you kill, you have become a transgressor of the law.

[[james-2-12]]
^12^ So speak and act just as you are beginning to be judged, by the law of liberty.

[[james-2-13]]
^13^ For judgment is without mercy toward him who has not shown mercy. But mercy exalts itself above judgment.

[[james-2-14]]
^14^ My brothers, what benefit is there if someone claims to have faith, but he does not have works? How would faith be able to save him?

[[james-2-15]]
^15^ So if a brother or sister is naked and daily in need of food,

[[james-2-16]]
^16^ and if anyone of you were to say to them: “Go in peace, keep warm and nourished,” and yet not give them the things that are necessary for the body, of what benefit is this?

[[james-2-17]]
^17^ Thus even faith, if it does not have works, is dead, in and of itself.

[[james-2-18]]
^18^ Now someone may say: “You have faith, and I have works.” Show me your faith without works! But I will show you my faith by means of works.

[[james-2-19]]
^19^ You believe that there is one God. You do well. But the demons also believe, and they tremble greatly.

[[james-2-20]]
^20^ So then, are you willing to understand, O foolish man, that faith without works is dead?

[[james-2-21]]
^21^ Was not our father Abraham justified by means of works, by offering his son Isaac upon the altar?

[[james-2-22]]
^22^ Do you see that faith was cooperating with his works, and that by means of works faith was brought to fulfillment?

[[james-2-23]]
^23^ And so the Scripture was fulfilled which says: “Abraham believed God, and it was reputed to him unto justice.” And so he was called the friend of God.

[[james-2-24]]
^24^ Do you see that a man is justified by means of works, and not by faith alone?

[[james-2-25]]
^25^ Similarly also, Rahab, the harlot, was she not justified by works, by receiving the messengers and sending them out through another way?

[[james-2-26]]
^26^ For just as the body without the spirit is dead, so also faith without works is dead.


[[james-3]]
== Chapter 3

[[james-3-1]]
^1^ My brothers, not many of you should choose to become teachers, knowing that you shall receive a stricter judgment.

[[james-3-2]]
^2^ For we all offend in many ways. If anyone does not offend in word, he is a perfect man. And he is then able, as if with a bridle, to lead the whole body around.

[[james-3-3]]
^3^ For so we put bridles into the mouths of horses, in order to submit them to our will, and so we turn their whole body around.

[[james-3-4]]
^4^ Consider also the ships, which, though they are great and may be driven by strong winds, yet they are turned around with a small rudder, to be directed to wherever the strength of the pilot might will.

[[james-3-5]]
^5^ So also the tongue certainly is a small part, but it moves great things. Consider that a small fire can set ablaze a great forest.

[[james-3-6]]
^6^ And so the tongue is like a fire, comprising all iniquity. The tongue, stationed in the midst of our body, can defile the entire body and inflame the wheel of our nativity, setting a fire from Hell.

[[james-3-7]]
^7^ For the nature of all beasts and birds and serpents and others is ruled over, and has been ruled over, by human nature.

[[james-3-8]]
^8^ But no man is able to rule over the tongue, a restless evil, full of deadly poison.

[[james-3-9]]
^9^ By it we bless God the Father, and by it we speak evil of men, who have been made in the likeness of God.

[[james-3-10]]
^10^ From the same mouth proceeds blessing and cursing. My brothers, these things ought not to be so!

[[james-3-11]]
^11^ Does a fountain emit, out of the same opening, both sweet and bitter water?

[[james-3-12]]
^12^ My brothers, can the fig tree yield grapes? Or the vine, figs? Then neither is salt water able to produce fresh water.

[[james-3-13]]
^13^ Who is wise and well-taught among you? Let him show, by means of good conversation, his work in the meekness of wisdom.

[[james-3-14]]
^14^ But if you hold a bitter zeal, and if there is contention in your hearts, then do not boast and do not be liars against the truth.

[[james-3-15]]
^15^ For this is not wisdom, descending from above, but rather it is earthly, beastly, and diabolical.

[[james-3-16]]
^16^ For wherever envy and contention is, there too is inconstancy and every depraved work.

[[james-3-17]]
^17^ But within the wisdom that is from above, certainly, chastity is first, and next peacefulness, meekness, openness, consenting to what is good, a plenitude of mercy and good fruits, not judging, without falseness.

[[james-3-18]]
^18^ And so the fruit of justice is sown in peace by those who make peace.


[[james-4]]
== Chapter 4

[[james-4-1]]
^1^ Where do wars and contentions among you come from? Is it not from this: from your own desires, which battle within your members?

[[james-4-2]]
^2^ You desire, and you do not have. You envy and you kill, and you are unable to obtain. You argue and you fight, and you do not have, because you do not ask.

[[james-4-3]]
^3^ You ask and you do not receive, because you ask badly, so that you may use it toward your own desires.

[[james-4-4]]
^4^ You adulterers! Do you not know that the friendship of this world is hostile to God? Therefore, whoever has chosen to be a friend of this world has been made into an enemy of God.

[[james-4-5]]
^5^ Or do you think that Scripture says in vain: “The spirit which lives within you desires unto envy?”

[[james-4-6]]
^6^ But he gives a greater grace. Therefore he says: “God resists the arrogant, but he gives grace to the humble.”

[[james-4-7]]
^7^ Therefore, be subject to God. But resist the devil, and he will flee from you.

[[james-4-8]]
^8^ Draw near to God, and he will draw near to you. Cleanse your hands, you sinners! And purify your hearts, you duplicitous souls!

[[james-4-9]]
^9^ Be afflicted: mourn and weep. Let your laughter be turned into mourning, and your gladness into sorrow.

[[james-4-10]]
^10^ Be humbled in the sight of the Lord, and he will exalt you.

[[james-4-11]]
^11^ Brothers, do not choose to slander one another. Whoever slanders his brother, or whoever judges his brother, slanders the law and judges the law. But if you judge the law, you are not a doer of the law, but a judge.

[[james-4-12]]
^12^ There is one lawgiver and one judge. He is able to destroy, and he is able to set free.

[[james-4-13]]
^13^ But who are you to judge your neighbor? Consider this, you who say, “Today or tomorrow we will go into that city, and certainly we will spend a year there, and we will do business, and we will make our profit,”

[[james-4-14]]
^14^ consider that you do not know what will be tomorrow.

[[james-4-15]]
^15^ For what is your life? It is a mist that appears for a brief time, and afterwards will vanish away. So what you ought to say is: “If the Lord wills,” or, “If we live,” we will do this or that.

[[james-4-16]]
^16^ But now you exult in your arrogance. All such exultation is wicked.

[[james-4-17]]
^17^ Therefore, he who knows that he ought to do a good thing, and does not do it, for him it is a sin.


[[james-5]]
== Chapter 5

[[james-5-1]]
^1^ Act now, you who are wealthy! Weep and wail in your miseries, which will soon come upon you!

[[james-5-2]]
^2^ Your riches have been corrupted, and your garments have been eaten by moths.

[[james-5-3]]
^3^ Your gold and silver have rusted, and their rust will be a testimony against you, and it will eat away at your flesh like fire. You have stored up wrath for yourselves unto the last days.

[[james-5-4]]
^4^ Consider the pay of the workers who reaped your fields: it has been misappropriated by you; it cries out. And their cry has entered into the ears of the Lord of hosts.

[[james-5-5]]
^5^ You have feasted upon the earth, and you have nourished your hearts with luxuries, unto the day of slaughter.

[[james-5-6]]
^6^ You led away and killed the Just One, and he did not resist you.

[[james-5-7]]
^7^ Therefore, be patient, brothers, until the advent of the Lord. Consider that the farmer anticipates the precious fruit of the earth, waiting patiently, until he receives the early and the late rains.

[[james-5-8]]
^8^ Therefore, you too should be patient and should strengthen your hearts. For the advent of the Lord draws near.

[[james-5-9]]
^9^ Brothers, do not complain against one another, so that you may not be judged. Behold, the judge stands before the door.

[[james-5-10]]
^10^ My brothers, consider the Prophets, who spoke in the name of the Lord, as an example of departing from evil, of labor, and of patience.

[[james-5-11]]
^11^ Consider that we beatify those who have endured. You have heard of the patient suffering of Job. And you have seen the end of the Lord, that the Lord is merciful and compassionate.

[[james-5-12]]
^12^ But before all things, my brothers, do not choose to swear, neither by heaven, nor by the earth, nor in any other oath. But let your word ‘Yes’ be yes, and your word ‘No’ be no, so that you may not fall under judgment.

[[james-5-13]]
^13^ Is any of you sad? Let him pray. Is he even-tempered? Let him sing psalms.

[[james-5-14]]
^14^ Is anyone ill among you? Let him bring in the priests of the Church, and let them pray over him, anointing him with oil in the name of the Lord.

[[james-5-15]]
^15^ And a prayer of faith will save the infirm, and the Lord will alleviate him. And if he has sins, these will be forgiven him.

[[james-5-16]]
^16^ Therefore, confess your sins to one another, and pray for one another, so that you may be saved. For the unremitting prayer of a just person prevails over many things.

[[james-5-17]]
^17^ Elijah was a mortal man like us, and in prayer he prayed that it would not rain upon the earth. And it did not rain for three years and six months.

[[james-5-18]]
^18^ And he prayed again. And the heavens gave rain, and the earth brought forth her fruit.

[[james-5-19]]
^19^ My brothers, if anyone of you strays from the truth, and if someone converts him,

[[james-5-20]]
^20^ he ought to know that whoever causes a sinner to be converted from the error of his ways will save his soul from death and will cover a multitude of sins.
