[[first-john]]
= The First Letter of John
:short: 1st John

[[first-john-1]]
== Chapter 1

[[first-john-1-1]]
^1^ He who was from the beginning, whom we have heard, whom we have seen with our eyes, upon whom we have gazed, and whom our hands have certainly touched: He is the Word of Life.

[[first-john-1-2]]
^2^ And that Life has been made manifest. And we have seen, and we testify, and we announce to you: the Eternal Life, who was with the Father, and who appeared to us.

[[first-john-1-3]]
^3^ He whom we have seen and heard, we announce to you, so that you, too, may have fellowship with us, and so that our fellowship may be with the Father and with his Son Jesus Christ.

[[first-john-1-4]]
^4^ And this we write to you, so that you may rejoice, and so that your joy may be full.

[[first-john-1-5]]
^5^ And this is the announcement which we have heard from him, and which we announce to you: that God is light, and in him there is no darkness.

[[first-john-1-6]]
^6^ If we claim that we have fellowship with him, and yet we walk in darkness, then we are lying and not telling the truth.

[[first-john-1-7]]
^7^ But if we walk in the light, just as he also is in the light, then we have fellowship with one another, and the blood of Jesus Christ, his Son, cleanses us from all sin.

[[first-john-1-8]]
^8^ If we claim that we have no sin, then we are deceiving ourselves and the truth is not in us.

[[first-john-1-9]]
^9^ If we confess our sins, then he is faithful and just, so as to forgive us our sins and to cleanse us from all iniquity.

[[first-john-1-10]]
^10^ If we claim that we have not sinned, then we make him a liar, and his Word is not in us.


[[first-john-2]]
== Chapter 2

[[first-john-2-1]]
^1^ My little sons, this I write to you, so that you may not sin. But if anyone has sinned, we have an Advocate with the Father, Jesus Christ, the Just One.

[[first-john-2-2]]
^2^ And he is the propitiation for our sins. And not only for our sins, but also for those of the whole world.

[[first-john-2-3]]
^3^ And we can be sure that we have known him by this: if we observe his commandments.

[[first-john-2-4]]
^4^ Whoever claims that he knows him, and yet does not keep his commandments, is a liar, and the truth is not in him.

[[first-john-2-5]]
^5^ But whoever keeps his word, truly in him the charity of God is perfected. And by this we know that we are in him.

[[first-john-2-6]]
^6^ Whoever declares himself to remain in him, ought to walk just as he himself walked.

[[first-john-2-7]]
^7^ Most beloved, I am not writing to you a new commandment, but the old commandment, which you had from the beginning. The old commandment is the Word, which you have heard.

[[first-john-2-8]]
^8^ Then too, I am writing to you a new commandment, which is the Truth in him and in you. For the darkness has passed away, and the true Light is now shining.

[[first-john-2-9]]
^9^ Whoever declares himself to be in the light, and yet hates his brother, is in the darkness even now.

[[first-john-2-10]]
^10^ Whoever loves his brother abides in the light, and there is no cause of offense in him.

[[first-john-2-11]]
^11^ But whoever hates his brother is in the darkness, and in darkness he walks, and he does not know where he is going. For the darkness has blinded his eyes.

[[first-john-2-12]]
^12^ I am writing to you, little sons, because your sins are forgiven for the sake of his name.

[[first-john-2-13]]
^13^ I am writing to you, fathers, because you have known him who is from the beginning. I am writing to you, adolescents, because you have overcome the evil one.

[[first-john-2-14]]
^14^ I am writing to you, little children, because you have known the Father. I am writing to you, young men, because you are strong, and the Word of God abides in you, and you have overcome the evil one.

[[first-john-2-15]]
^15^ Do not choose to love the world, nor the things that are in the world. If anyone loves the world, the charity of the Father is not in him.

[[first-john-2-16]]
^16^ For all that is in the world is the desire of the flesh, and the desire of the eyes, and the arrogance of a life which is not of the Father, but is of the world.

[[first-john-2-17]]
^17^ And the world is passing away, with its desire. But whoever does the will of God abides unto eternity.

[[first-john-2-18]]
^18^ Little sons, it is the last hour. And, as you have heard that the Antichrist is coming, so now many antichrists have arrived. By this, we know that it is the last hour.

[[first-john-2-19]]
^19^ They went out from among us, but they were not of us. For, if they had been of us, certainly they would have remained with us. But in this way, it is made manifest that none of them are of us.

[[first-john-2-20]]
^20^ Yet you have the anointing of the Holy One, and you know everything.

[[first-john-2-21]]
^21^ I have not written to you as to ones who are ignorant of the truth, but as to ones who know the truth. For no lie is of the truth.

[[first-john-2-22]]
^22^ Who is a liar, other than he who denies that Jesus is the Christ? This one is the Antichrist, who denies the Father and the Son.

[[first-john-2-23]]
^23^ No one who denies the Son also has the Father. Whoever confesses the Son, also has the Father.

[[first-john-2-24]]
^24^ As for you, let what you have heard from the beginning remain in you. If what you have heard from the beginning remains in you, then you, too, shall abide in the Son and in the Father.

[[first-john-2-25]]
^25^ And this is the Promise, which he himself has promised to us: Eternal Life.

[[first-john-2-26]]
^26^ I have written these things to you, because of those who would seduce you.

[[first-john-2-27]]
^27^ But as for you, let the Anointing that you have received from him abide in you. And so, you have no need of anyone to teach you. For his Anointing teaches you about everything, and it is the truth, and it is not a lie. And just as his Anointing has taught you, abide in him.

[[first-john-2-28]]
^28^ And now, little sons, abide in him, so that when he appears, we may have faith, and we may not be confounded by him at his advent.

[[first-john-2-29]]
^29^ If you know that he is just, then know, too, that all who do what is just are born of him.


[[first-john-3]]
== Chapter 3

[[first-john-3-1]]
^1^ See what kind of love the Father has given to us, that we would be called, and would become, the sons of God. Because of this, the world does not know us, for it did not know him.

[[first-john-3-2]]
^2^ Most beloved, we are now the sons of God. But what we shall be then has not yet appeared. We know that when he does appear, we shall be like him, for we shall see him as he is.

[[first-john-3-3]]
^3^ And everyone who holds this hope in him, keeps himself holy, just as he also is holy.

[[first-john-3-4]]
^4^ Everyone who commits a sin, also commits iniquity. For sin is iniquity.

[[first-john-3-5]]
^5^ And you know that he appeared in order that he might take away our sins. For in him there is no sin.

[[first-john-3-6]]
^6^ Everyone who abides in him does not sin. For whoever sins has not seen him, and has not known him.

[[first-john-3-7]]
^7^ Little sons, let no one deceive you. Whoever does justice is just, even as he also is just.

[[first-john-3-8]]
^8^ Whoever commits sin is of the devil. For the devil sins from the beginning. For this reason, the Son of God appeared, so that he might eradicate the works of the devil.

[[first-john-3-9]]
^9^ All those who have been born of God do not commit sin. For the offspring of God abides in them, and he is not able to sin, because he was born of God.

[[first-john-3-10]]
^10^ In this way, the sons of God are made manifest, and also the sons of the devil. Everyone who is not just, is not of God, as also anyone who does not love his brother.

[[first-john-3-11]]
^11^ For this is the announcement that you heard from the beginning: that you should love one another.

[[first-john-3-12]]
^12^ Do not be like Cain, who was of the evil one, and who killed his brother. And why did he kill him? Because his own works were wicked, but his brother’s works were just.

[[first-john-3-13]]
^13^ If the world hates you, brothers, do not be surprised.

[[first-john-3-14]]
^14^ We know that we have passed from death to life. For we love as brothers. Whoever does not love, abides in death.

[[first-john-3-15]]
^15^ Everyone who hates his brother is a murderer. And you know that no murderer has eternal life abiding within him.

[[first-john-3-16]]
^16^ We know the love of God in this way: because he laid down his life for us. And so, we must lay down our lives for our brothers.

[[first-john-3-17]]
^17^ Whoever possesses the goods of this world, and sees his brother to be in need, and yet closes his heart to him: in what way does the love of God abide in him?

[[first-john-3-18]]
^18^ My little sons, let us not love in words only, but in works and in truth.

[[first-john-3-19]]
^19^ In this way, we will know that we are of the truth, and we will commend our hearts in his sight.

[[first-john-3-20]]
^20^ For even if our heart reproaches us, God is greater than our heart, and he knows all things.

[[first-john-3-21]]
^21^ Most beloved, if our heart does not reproach us, we can have confidence toward God;

[[first-john-3-22]]
^22^ and whatever we shall request of him, we shall receive from him. For we keep his commandments, and we do the things that are pleasing in his sight.

[[first-john-3-23]]
^23^ And this is his commandment: that we should believe in the name of his Son, Jesus Christ, and love one another, just as he has commanded us.

[[first-john-3-24]]
^24^ And those who keep his commandments abide in him, and he in them. And we know that he abides in us by this: by the Spirit, whom he has given to us.


[[first-john-4]]
== Chapter 4

[[first-john-4-1]]
^1^ Most beloved, do not be willing to believe every spirit, but test the spirits to see if they are of God. For many false prophets have gone out into the world.

[[first-john-4-2]]
^2^ The Spirit of God may be known in this way. Every spirit who confesses that Jesus Christ has arrived in the flesh is of God;

[[first-john-4-3]]
^3^ and every spirit who contradicts Jesus is not of God. And this one is the Antichrist, the one that you have heard is coming, and even now he is in the world.

[[first-john-4-4]]
^4^ Little sons, you are of God, and so you have overcome him. For he who is in you is greater than he who is in the world.

[[first-john-4-5]]
^5^ They are of the world. Therefore, they speak about the world, and the world listens to them.

[[first-john-4-6]]
^6^ We are of God. Whoever knows God, listens to us. Whoever is not of God, does not listen to us. In this way, we know the Spirit of truth from the spirit of error.

[[first-john-4-7]]
^7^ Most beloved, let us love one another. For love is of God. And everyone who loves is born of God and knows God.

[[first-john-4-8]]
^8^ Whoever does not love, does not know God. For God is love.

[[first-john-4-9]]
^9^ The love of God was made apparent to us in this way: that God sent his only-begotten Son into the world, so that we might live through him.

[[first-john-4-10]]
^10^ In this is love: not as if we had loved God, but that he first loved us, and so he sent his Son as a propitiation for our sins.

[[first-john-4-11]]
^11^ Most beloved, if God has so loved us, we also ought to love one another.

[[first-john-4-12]]
^12^ No one has ever seen God. But if we love one another, God abides in us, and his love is perfected in us.

[[first-john-4-13]]
^13^ In this way, we know that we abide in him, and he in us: because he has given to us from his Spirit.

[[first-john-4-14]]
^14^ And we have seen, and we testify, that the Father has sent his Son to be the Savior of the world.

[[first-john-4-15]]
^15^ Whoever has confessed that Jesus is the Son of God, God abides in him, and he in God.

[[first-john-4-16]]
^16^ And we have known and believed the love that God has for us. God is love. And he who abides in love, abides in God, and God in him.

[[first-john-4-17]]
^17^ In this way, the love of God is perfected with us, so that we may have confidence on the day of judgment. For as he is, so also are we, in this world.

[[first-john-4-18]]
^18^ Fear is not in love. Instead, perfect love casts out fear, for fear pertains to punishment. And whoever fears is not perfected in love.

[[first-john-4-19]]
^19^ Therefore, let us love God, for God first loved us.

[[first-john-4-20]]
^20^ If anyone says that he loves God, but hates his brother, then he is a liar. For he who does not love his brother, whom he does see, in what way can he love God, whom he does not see?

[[first-john-4-21]]
^21^ And this is the commandment that we have from God, that he who loves God must also love his brother.


[[first-john-5]]
== Chapter 5

[[first-john-5-1]]
^1^ Everyone who believes that Jesus is the Christ, is born of God. And everyone who loves God, who provides that birth, also loves him who has been born of God.

[[first-john-5-2]]
^2^ In this way, we know that we love those born of God: when we love God and do his commandments.

[[first-john-5-3]]
^3^ For this is the love of God: that we keep his commandments. And his commandments are not heavy.

[[first-john-5-4]]
^4^ For all that is born of God overcomes the world. And this is the victory that overcomes the world: our faith.

[[first-john-5-5]]
^5^ Who is it that overcomes the world? Only he who believes that Jesus is the Son of God!

[[first-john-5-6]]
^6^ This is the One who came by water and blood: Jesus Christ. Not by water only, but by water and blood. And the Spirit is the One who testifies that the Christ is the Truth.

[[first-john-5-7]]
^7^ For there are Three who give testimony in heaven: the Father, the Word, and the Holy Spirit. And these Three are One.

[[first-john-5-8]]
^8^ And there are three who give testimony on earth: the Spirit, and the water, and the blood. And these three are one.

[[first-john-5-9]]
^9^ If we accept the testimony of men, then the testimony of God is greater. For this is the testimony of God, which is greater: that he has testified about his Son.

[[first-john-5-10]]
^10^ Whoever believes in the Son of God, holds the testimony of God within himself. Whoever does not believe in the Son, makes him a liar, because he does not believe in the testimony which God has testified about his Son.

[[first-john-5-11]]
^11^ And this is the testimony which God has given to us: Eternal Life. And this Life is in his Son.

[[first-john-5-12]]
^12^ Whoever has the Son, has Life. Whoever does not have the Son, does not have Life.

[[first-john-5-13]]
^13^ I am writing this to you, so that you may know that you have Eternal Life: you who believe in the name of the Son of God.

[[first-john-5-14]]
^14^ And this is the confidence which we have toward God: that no matter what we shall request, in accord with his will, he hears us.

[[first-john-5-15]]
^15^ And we know that he hears us, no matter what we request; so we know that we can obtain the things that we request of him.

[[first-john-5-16]]
^16^ Anyone who realizes that his brother has sinned, with a sin that is not unto death, let him pray, and life shall be given to him who has sinned not unto death. There is a sin which is unto death. I am not saying that anyone should ask on behalf of that sin.

[[first-john-5-17]]
^17^ All that is iniquity is sin. But there is a sin unto death.

[[first-john-5-18]]
^18^ We know that everyone who is born of God does not sin. Instead, rebirth in God preserves him, and the evil one cannot touch him.

[[first-john-5-19]]
^19^ We know that we are of God, and that the entire world is established in wickedness.

[[first-john-5-20]]
^20^ And we know that the Son of God has arrived, and that he has given us understanding, so that we may know the true God, and so that we may remain in his true Son. This is the true God, and this is Eternal Life.

[[first-john-5-21]]
^21^ Little sons, keep yourselves from false worship. Amen.

