[[numbers]]
= The Book of Numbers
:short: Numbers

[[numbers-1]]
== Chapter 1

[[numbers-1-1]]
^1^ And the Lord spoke to Moses in the desert of Sinai, in the tabernacle of the covenant, on the first day of the second month, in the year after their departure from Egypt, saying:

[[numbers-1-2]]
^2^ “Take a total of the entire assembly of the sons of Israel, by their families and houses, and the names of each one, of whomever is of the male sex,

[[numbers-1-3]]
^3^ from twenty years and above, of all the able-bodied men out of Israel, and you shall number them by their companies, you and Aaron.

[[numbers-1-4]]
^4^ And there shall be with you the leaders of the tribes, as well as of the houses, in their kinships,

[[numbers-1-5]]
^5^ the names of whom are these: of Ruben, Elizur the son of Shedeur;

[[numbers-1-6]]
^6^ of Simeon, Shelumiel the son of Zurishaddai;

[[numbers-1-7]]
^7^ of Judah, Nahshon the son of Amminadab;

[[numbers-1-8]]
^8^ of Issachar, Nathanael the son of Zuar;

[[numbers-1-9]]
^9^ of Zebulon, Eliab the son of Helon.

[[numbers-1-10]]
^10^ And from the sons of Joseph: of Ephraim, Elishama the son of Ammihud; of Manasseh, Gamaliel the son of Pedahzur;

[[numbers-1-11]]
^11^ of Benjamin, Abidan the son of Gideoni;

[[numbers-1-12]]
^12^ of Dan, Ahiezer the son of Ammishaddai;

[[numbers-1-13]]
^13^ of Asher, Pagiel the son of Ochran;

[[numbers-1-14]]
^14^ of Gad, Eliasaph the son of Reuel;

[[numbers-1-15]]
^15^ of Naphtali, Ahira the son of Enan.”

[[numbers-1-16]]
^16^ These are the very noble leaders of the multitude, by their tribes and kinships, and the heads of the army of Israel.

[[numbers-1-17]]
^17^ Moses and Aaron took these, with all the multitude of the common people,

[[numbers-1-18]]
^18^ and they gathered them together on the first day of the second month, taking a census of them by kinships, and houses, and families, and heads, and the names of each one from twenty years and above,

[[numbers-1-19]]
^19^ just as the Lord had instructed Moses. And they were numbered in the desert of Sinai.

[[numbers-1-20]]
^20^ Of Ruben, the firstborn of Israel, by their generations and families and houses, and the names of each head, of all who were of the male sex, from twenty years and above, capable of going to war,

[[numbers-1-21]]
^21^ there were forty-six thousand five hundred.

[[numbers-1-22]]
^22^ Of the sons of Simeon, by their generations and families, and the houses of their kinships, having been counted by the names and heads of each one, of all who were of the male sex, from twenty years and above, capable of going to war,

[[numbers-1-23]]
^23^ there were fifty-nine thousand three hundred.

[[numbers-1-24]]
^24^ Of the sons of Gad, by their generations and families, and the houses of their kinships, having been counted by the names of each one, from twenty years and above, of all who could go forth to war,

[[numbers-1-25]]
^25^ there were forty-five thousand six hundred fifty.

[[numbers-1-26]]
^26^ Of the sons of Judah, by their generations and families, and the houses of their kinships, by the names of each one, from twenty years and above, of all who were able to go forth to war,

[[numbers-1-27]]
^27^ there were counted seventy-four thousand six hundred.

[[numbers-1-28]]
^28^ Of the sons of Issachar, by their generations and families, and the houses of their kinships, by the names of each one, from twenty years and above, of all who could go forth to war,

[[numbers-1-29]]
^29^ there were counted fifty-four thousand four hundred.

[[numbers-1-30]]
^30^ Of the sons of Zebulon, by their generations and families, and the houses of their kinships, having been counted by the names of each one, from twenty years and above, of all who were able to go forth to war,

[[numbers-1-31]]
^31^ there were fifty-seven thousand four hundred.

[[numbers-1-32]]
^32^ From the sons of Joseph, of the sons of Ephraim, by their generations and families, and the houses of their kinships, having been counted by the names of each one, from twenty years and above, of all who were able to go forth to war,

[[numbers-1-33]]
^33^ there were forty thousand five hundred.

[[numbers-1-34]]
^34^ Furthermore, of the sons of Manasseh, by their generations and families, and the houses of their kinships, having been counted by the names of each one, from twenty years and above, of all who were able to go forth to war,

[[numbers-1-35]]
^35^ there were thirty-two thousand two hundred.

[[numbers-1-36]]
^36^ Of the sons of Benjamin, by their generations and families, and the houses of their kinships, having been counted by the names of each one, from twenty years and above, of all who were able to go forth to war,

[[numbers-1-37]]
^37^ there were thirty-five thousand four hundred.

[[numbers-1-38]]
^38^ Of the sons of Dan, by their generations and families, and the houses of their kinships, having been counted by the names of each one, from twenty years and above, of all who were able to go forth to war,

[[numbers-1-39]]
^39^ there were sixty-two thousand seven hundred.

[[numbers-1-40]]
^40^ Of the sons of Asher, by their generations and families, and the houses of their kinships, having been counted by the names of each one, from twenty years and above, of all who were able to go forth to war,

[[numbers-1-41]]
^41^ there were forty thousand and one thousand five hundred.

[[numbers-1-42]]
^42^ Of the sons of Naphtali, by their generations and families, and the houses of their kinships, having been counted by the names of each one, from twenty years and above, of all who were able to go forth to war,

[[numbers-1-43]]
^43^ there were fifty-three thousand four hundred.

[[numbers-1-44]]
^44^ These are the ones who were numbered by Moses and Aaron and the twelve leaders of Israel, each one by the houses of their kinships.

[[numbers-1-45]]
^45^ And the entire number of the sons of Israel by their houses and families, from twenty years and above, who were able to go forth to war, were

[[numbers-1-46]]
^46^ six hundred three thousand five hundred fifty men.

[[numbers-1-47]]
^47^ But the Levites in the tribes of their families were not numbered with them.

[[numbers-1-48]]
^48^ And the Lord spoke to Moses, saying:

[[numbers-1-49]]
^49^ “Do not number the tribe of Levi, neither shall you take a total of them with the sons of Israel.

[[numbers-1-50]]
^50^ But appoint them over the tabernacle of the testimony, and all its vessels, and whatever pertains to the ceremonies. They shall carry the tabernacle and all its articles. And they shall be for the ministry, and they shall encamp all around the tabernacle.

[[numbers-1-51]]
^51^ When you would depart, the Levites shall take down the tabernacle. When you are to make camp, they shall set it up. Any outsider who will approach it shall be killed.

[[numbers-1-52]]
^52^ Now the sons of Israel shall make camp, each one by his companies and bands, as well as his army.

[[numbers-1-53]]
^53^ Moreover, the Levites shall fix their tents all around the tabernacle, lest there be an indignation over the multitude of the sons of Israel. And they shall stand watch as guardians over the tabernacle of the testimony.”

[[numbers-1-54]]
^54^ Therefore, the sons of Israel acted according to everything that the Lord had instructed Moses.


[[numbers-2]]
== Chapter 2

[[numbers-2-1]]
^1^ And the Lord spoke to Moses and Aaron, saying:

[[numbers-2-2]]
^2^ “Each one shall make camp, by their troops, as well as by their insignia and standards, and by the houses of their kinships, all around the tabernacle of the covenant.”

[[numbers-2-3]]
^3^ To the east, Judah shall fix his tents, by the companies of his army. And the leader of his sons shall be Nahshon the son of Amminadab.

[[numbers-2-4]]
^4^ And the entire total of the fighting men from his stock was seventy-four thousand six hundred.

[[numbers-2-5]]
^5^ Beside him, those of the tribe of Issachar were encamped, whose leader was Nathanael the son of Zuar.

[[numbers-2-6]]
^6^ And the entire number of his fighting men was fifty-four thousand four hundred.

[[numbers-2-7]]
^7^ In the tribe of Zebulon, the leader was Eliab the son of Helon.

[[numbers-2-8]]
^8^ All the army of fighting men from his stock were fifty-seven thousand four hundred.

[[numbers-2-9]]
^9^ All who were numbered in the camp of Judah were one hundred eighty-six thousand four hundred. And these, by their companies, shall go forth first.

[[numbers-2-10]]
^10^ In the camp of the sons of Ruben, toward the south side, the leader shall be Elizur the son of Shedeur.

[[numbers-2-11]]
^11^ And the entire army of his fighting men, who were numbered, were forty-six thousand five hundred.

[[numbers-2-12]]
^12^ Beside him, those of the tribe of Simeon were encamped, whose leader was Shelumiel the son of Zurishaddai.

[[numbers-2-13]]
^13^ And the entire army of his fighting men, who were numbered, were fifty-nine thousand three hundred.

[[numbers-2-14]]
^14^ In the tribe of Gad, the leader was Eliasaph the son of Reuel.

[[numbers-2-15]]
^15^ And the entire army of his fighting men, who were numbered, were forty-five thousand six hundred fifty.

[[numbers-2-16]]
^16^ All who were counted in the camp of Ruben were one hundred fifty thousand and one thousand four hundred fifty, by their companies. These shall advance in the second place.

[[numbers-2-17]]
^17^ But the tabernacle of the testimony shall be lifted up by the officers of the Levites and their companies. In the manner in which it is set up, so also shall it be taken down. Each one shall advance according to their places and ranks.

[[numbers-2-18]]
^18^ On the west side, there shall be the camp of the sons of Ephraim, whose leader was Elishama the son of Ammihud.

[[numbers-2-19]]
^19^ The entire army of his fighting men, who were numbered, were forty thousand five hundred.

[[numbers-2-20]]
^20^ And with them was the tribe of the sons of Manasseh, whose leader was Gamaliel the son of Pedahzur.

[[numbers-2-21]]
^21^ And the entire army of his fighting men, who were numbered, were thirty-two thousand two hundred.

[[numbers-2-22]]
^22^ In the tribe of the sons of Benjamin, the leader was Abidan the son of Gideoni.

[[numbers-2-23]]
^23^ And the entire army of his fighting men, who were counted, were thirty-five thousand four hundred.

[[numbers-2-24]]
^24^ All who were numbered in the camp of Ephraim were one hundred eight thousand one hundred, by their companies. These shall advance third.

[[numbers-2-25]]
^25^ Toward the north side, the sons of Dan were encamped, whose leader was Ahiezer the son of Ammishaddai.

[[numbers-2-26]]
^26^ The entire army of his fighting men, who were numbered, were sixty-two thousand seven hundred.

[[numbers-2-27]]
^27^ Beside him, those of the tribe of Asher fixed their tents, whose leader was Pagiel the son of Ochran.

[[numbers-2-28]]
^28^ The entire army of his fighting men, who were numbered, were forty thousand and one thousand five hundred.

[[numbers-2-29]]
^29^ From the tribe of the sons of Naphtali, the leader was Ahira the son of Enan.

[[numbers-2-30]]
^30^ The entire army of his fighting men were fifty-three thousand four hundred.

[[numbers-2-31]]
^31^ All who were numbered in the camp of Dan were one hundred fifty-seven thousand six hundred; and these shall advance at the very end.

[[numbers-2-32]]
^32^ This is the number of the sons of Israel, of their army divided by the houses of their kinships and their companies: six hundred three thousand five hundred fifty.

[[numbers-2-33]]
^33^ But the Levites were not numbered among the sons of Israel. For so the Lord had instructed Moses.

[[numbers-2-34]]
^34^ And the sons of Israel acted according to all the things that the Lord had commanded. They were encamped by their companies, and they advanced by the families and houses of their fathers.


[[numbers-3]]
== Chapter 3

[[numbers-3-1]]
^1^ These are the generations of Aaron and Moses, in the day when the Lord spoke to Moses on mount Sinai.

[[numbers-3-2]]
^2^ And these are the names of the sons of Aaron: his firstborn Nadab, then Abihu, and Eleazar, and Ithamar.

[[numbers-3-3]]
^3^ These are the names of the sons of Aaron, the priests who were anointed and whose hands were filled and consecrated in order to exercise the priesthood.

[[numbers-3-4]]
^4^ For Nadab and Abihu died without children, when they offered, in the sight of the Lord, a strange fire, in the desert of Sinai. And so, Eleazar and Ithamar exercised the priesthood in the sight of Aaron, their father.

[[numbers-3-5]]
^5^ And the Lord spoke to Moses, saying:

[[numbers-3-6]]
^6^ “Bring forward the tribe of Levi, and cause them to stand in the sight of Aaron the priest, in order to minister to him. And let them keep watch outside,

[[numbers-3-7]]
^7^ and let them observe whatever pertains to the ritual for the multitude, in front of the tabernacle of the testimony,

[[numbers-3-8]]
^8^ and let them take care of the vessels of the tabernacle, serving in its ministry.

[[numbers-3-9]]
^9^ And you shall give the Levites as a gift to Aaron and his sons; for they have been delivered to them by the sons of Israel.

[[numbers-3-10]]
^10^ But you shall appoint Aaron and his sons over the service of the priesthood. The outsider who approaches to minister shall be put to death.”

[[numbers-3-11]]
^11^ And the Lord spoke to Moses, saying:

[[numbers-3-12]]
^12^ “I have taken the Levites from the sons of Israel. For the Levites, and all the firstborn who open the womb among the sons of Israel, shall be mine.

[[numbers-3-13]]
^13^ For every firstborn is mine. From the time that I struck the firstborn in the land of Egypt, I have sanctified for myself whatever is born first in Israel. From man, even to beast, they are mine. I am the Lord.”

[[numbers-3-14]]
^14^ And the Lord spoke to Moses in the desert of Sinai, saying:

[[numbers-3-15]]
^15^ “Number the sons of Levi by the houses of their fathers and their families, every male from one month and above.”

[[numbers-3-16]]
^16^ Moses numbered them, just as the Lord had instructed,

[[numbers-3-17]]
^17^ and there were found the sons of Levi by their names: Gershon and Kohath and Merari.

[[numbers-3-18]]
^18^ The sons of Gershon: Libni and Shimei.

[[numbers-3-19]]
^19^ The sons of Kohath: Amram, and Izhar, Hebron and Uzziel.

[[numbers-3-20]]
^20^ The sons of Merari: Mahli and Mushi.

[[numbers-3-21]]
^21^ From Gershon were two families: the Libnites, and the Shimeites.

[[numbers-3-22]]
^22^ The people of these were numbered, of the male sex, from one month and above: seven thousand five hundred.

[[numbers-3-23]]
^23^ These shall encamp behind the tabernacle, toward the west,

[[numbers-3-24]]
^24^ under the leader Eliasaph the son of Lael.

[[numbers-3-25]]
^25^ And they shall keep watch over the tabernacle of the covenant:

[[numbers-3-26]]
^26^ the tabernacle itself, and its covering; the tent that is drawn before the doors of the covering of the covenant; and the curtains of the atrium; likewise, the tent that is suspended at the entrance of the atrium of the tabernacle; and whatever pertains to the ritual of the altar; the cords of the tabernacle and all its implements.

[[numbers-3-27]]
^27^ The kinship of Kohath includes the peoples of the Amramites and Izharites and Hebronites and Uzzielites. These are the families of the Kohathites, having been counted by their names,

[[numbers-3-28]]
^28^ all those of the male gender, from one month and above: eight thousand six hundred. They shall keep watch over the Sanctuary,

[[numbers-3-29]]
^29^ and they shall encamp toward the south side.

[[numbers-3-30]]
^30^ And their leader shall be Elisaphan the son of Uzziel.

[[numbers-3-31]]
^31^ And they shall take care of the ark, and the table and the lampstand, the altars and the vessels of the Sanctuary, by which they minister, and the veil, and all the articles of this kind.

[[numbers-3-32]]
^32^ But the leader of the leaders of the Levites, Eleazar the son of Aaron the priest, shall be over those who watch over the care of the Sanctuary.

[[numbers-3-33]]
^33^ And truly, from Merari are the peoples of the Mahlites and Mushites, having been counted by their names,

[[numbers-3-34]]
^34^ all those of the male gender, from one month and above: six thousand two hundred.

[[numbers-3-35]]
^35^ Their leader is Suriel the son of Abihaiel. They shall make camp on the north side.

[[numbers-3-36]]
^36^ Under their care shall be the panels of the tabernacle, and the bars, and the columns with their bases, and all the things which pertain to service of this kind,

[[numbers-3-37]]
^37^ and the columns of the surrounding atrium with their bases, and the tent pegs with their cords.

[[numbers-3-38]]
^38^ Moses and Aaron, with their sons, shall make camp before the tabernacle of the covenant, that is, on the east side, holding the custody of the Sanctuary in the midst of the sons of Israel. Whatever foreigner approaches it shall die.

[[numbers-3-39]]
^39^ All the Levites, whom Moses and Aaron numbered by their families according to the precept of the Lord, of the male gender, from one month and above, were twenty-two thousand.

[[numbers-3-40]]
^40^ And the Lord said to Moses: “Number the firstborn of the male sex from the sons of Israel, from one month and above, and you shall take their total.

[[numbers-3-41]]
^41^ And you shall bring the Levites to me, in place of all the firstborn of the sons of Israel, and you shall bring their cattle to me, in place of all the firstborn of the cattle of the sons of Israel. I am the Lord.”

[[numbers-3-42]]
^42^ Moses took a census, just as the Lord had instructed, of the firstborn of the sons of Israel.

[[numbers-3-43]]
^43^ And the males by their names, from one month and above, were twenty-two thousand two hundred seventy-three.

[[numbers-3-44]]
^44^ And the Lord spoke to Moses, saying:

[[numbers-3-45]]
^45^ “Take the Levites, in place of the firstborn of the sons of Israel, and the cattle of the Levites, in place of their cattle, and so the Levites shall be mine. I am the Lord.

[[numbers-3-46]]
^46^ But for the price of the two hundred and seventy-three, which exceed the number of the Levites compared to the number of firstborn of the sons of Israel,

[[numbers-3-47]]
^47^ you shall take five shekels for each head, by the measure of the Sanctuary. A shekel has twenty obols.

[[numbers-3-48]]
^48^ And you shall give the money to Aaron and his sons as the price of those that are in excess.”

[[numbers-3-49]]
^49^ Therefore, Moses took the money for those that were in excess, and whom they had redeemed from the Levites

[[numbers-3-50]]
^50^ in place of the firstborn of the sons of Israel: one thousand three hundred sixty-five shekels, according to the weight of the Sanctuary.

[[numbers-3-51]]
^51^ And he gave it to Aaron and his sons, according to the word by which the Lord had instructed him.


[[numbers-4]]
== Chapter 4

[[numbers-4-1]]
^1^ And the Lord spoke to Moses and Aaron, saying:

[[numbers-4-2]]
^2^ “Take a total of the sons of Kohath from the midst of the Levites, by their houses and families,

[[numbers-4-3]]
^3^ from thirty years and above, even to the fiftieth year, of all who enter so as to stand and minister in the tabernacle of the covenant.

[[numbers-4-4]]
^4^ This is the service of the sons of Kohath: the tabernacle of the covenant and the Holy of holies.

[[numbers-4-5]]
^5^ Aaron and his sons shall enter, when the camp is going to move, and they shall take down the veil, which hangs before the entrance, and they shall wrap the ark of the testimony in it,

[[numbers-4-6]]
^6^ and they shall cover it further with a veil of violet skins, and they shall extend over it a cloth made entirely of hyacinth, and they shall draw in the bars.

[[numbers-4-7]]
^7^ Likewise, they shall wrap the table of the presence in a cloth of hyacinth, and they shall place with it the censers and little mortars, the cups and bowls for pouring out libations; the bread shall be always on it.

[[numbers-4-8]]
^8^ And they shall extend over it a cloth of scarlet, which they shall further cover with a veil of violet skins, and they shall draw in the bars.

[[numbers-4-9]]
^9^ They shall take also a cloth of hyacinth, with which they shall cover the lampstand with the lamps, and its tongs, and the candle snuffers, and all the vessels of oil, which are necessary for the preparation of the lamps.

[[numbers-4-10]]
^10^ And over all this they shall place a covering of violet skins, and they shall draw in the bars.

[[numbers-4-11]]
^11^ And certainly they shall wrap the golden altar in a hyacinth garment, and they shall extend over it a covering of violet skins, and they shall draw in the bars.

[[numbers-4-12]]
^12^ All the vessels with which they minister in the Sanctuary they shall wrap in a cloth of hyacinth, and they shall extend over it a covering of violet skins, and they shall draw in the bars.

[[numbers-4-13]]
^13^ Moreover, they shall cleanse the altar of ashes, and they shall wrap it in a purple garment,

[[numbers-4-14]]
^14^ and they shall place it with all the vessels which they use in its ministry, that is, receptacles for fire, small hooks as well as forks, larger hooks and shovels. They shall cover all the vessels of the altar together with a veil of violet skins, and they shall draw in the bars.

[[numbers-4-15]]
^15^ And when Aaron and his sons have wrapped the Sanctuary and its vessels at the dismantling of the camp, then the sons of Kohath shall enter, so as to carry what has been wrapped. And they shall not touch the vessels of the Sanctuary, lest they die. These are the burdens of the sons of Kohath concerning the tabernacle of the covenant.

[[numbers-4-16]]
^16^ Over them shall be Eleazar, the son of Aaron the priest, to whom belongs the care of the oil to prepare the lamps, and the incense compound, and the sacrifice, which is offered continually, and the oil of unction, and whatever pertains to the service of the tabernacle, and all the vessels that are in the Sanctuary.”

[[numbers-4-17]]
^17^ And the Lord spoke to Moses and Aaron, saying:

[[numbers-4-18]]
^18^ “Do not be willing to lose the people of Kohath from the midst of the Levites.

[[numbers-4-19]]
^19^ But do this for them, so that they may live, and so that they may not die by touching the Holies of holies. Aaron and his sons shall enter, and they shall assign the work of each one, and they shall determine what each one ought to carry.

[[numbers-4-20]]
^20^ Let no others, out of curiosity, see the things that are in the Sanctuary before they are wrapped, otherwise they shall die.”

[[numbers-4-21]]
^21^ And the Lord spoke to Moses, saying:

[[numbers-4-22]]
^22^ “Now also take a total of the sons of Gershon, by their houses and families and kinships,

[[numbers-4-23]]
^23^ from thirty years and above, even to fifty years. Number all those who enter and minister in the tabernacle of the covenant.

[[numbers-4-24]]
^24^ This is the duty of the family of the Gershonites:

[[numbers-4-25]]
^25^ to carry the curtains of the tabernacle, and the roof of the covenant, the other covering, and the veil over everything, and the violet tent, which hangs at the entrance of the tabernacle of the covenant,

[[numbers-4-26]]
^26^ the curtains of the atrium, and the veil at the entrance, which is before tabernacle. Everything that pertains to the altar, the cords, and the vessels of the ministry

[[numbers-4-27]]
^27^ the sons of Gershon shall carry, under the orders of Aaron and his sons. And so shall each one know to which burden he ought to surrender.

[[numbers-4-28]]
^28^ This is the service of the family of the Gershonites, in the tabernacle of the covenant, and they shall be under the hand of Ithamar, the son of Aaron the priest.

[[numbers-4-29]]
^29^ Likewise, you shall take a census of the sons of Merari, by the families and houses of their fathers,

[[numbers-4-30]]
^30^ from thirty years and above, even to fifty years, of all who enter to the office of their ministry and to the service of the covenant of the testimony.

[[numbers-4-31]]
^31^ These are their burdens: They shall carry the panels of the tabernacle and its bars, the columns and their bases,

[[numbers-4-32]]
^32^ also the columns surrounding the atrium, with their bases and tent pegs and cords. They shall accept by number all the vessels and articles, and so shall they carry them.

[[numbers-4-33]]
^33^ This is the office of the family of the Merarites, and their ministry for the tabernacle of the covenant. And they shall be under the hand of Ithamar, the son of Aaron the priest.”

[[numbers-4-34]]
^34^ Therefore, Moses and Aaron, and the leaders of the assembly, took a census of the sons of Kohath, by the kinships and houses of their fathers,

[[numbers-4-35]]
^35^ from thirty years and above, even to the fiftieth year, of all who enter to the ministry of the tabernacle of the covenant.

[[numbers-4-36]]
^36^ And there were found two thousand seven hundred fifty.

[[numbers-4-37]]
^37^ This is the number of the people of Kohath, who enter the tabernacle of the covenant. These Moses and Aaron numbered according to the word of the Lord by the hand of Moses.

[[numbers-4-38]]
^38^ The sons of Gershon also were numbered by the kinships and houses of their fathers,

[[numbers-4-39]]
^39^ from thirty years and above, even to the fiftieth year, all who enter so as to minister in the tabernacle of the covenant.

[[numbers-4-40]]
^40^ And there were found two thousand six hundred thirty.

[[numbers-4-41]]
^41^ This is the people of the Gershonites, whom Moses and Aaron numbered according to the word of the Lord.

[[numbers-4-42]]
^42^ The sons of Merari also were numbered by the kinships and houses of their fathers,

[[numbers-4-43]]
^43^ from thirty years and above, even to the fiftieth year, all who enter to fulfill the rituals of the tabernacle of the covenant.

[[numbers-4-44]]
^44^ And there were found three thousand two hundred.

[[numbers-4-45]]
^45^ This is the number of the sons of Merari, whom Moses and Aaron counted according to the command of the Lord by the hand of Moses.

[[numbers-4-46]]
^46^ All who were counted from the Levites, and whom, by name, Moses and Aaron, and the leaders of Israel, counted by the kinships and houses of their fathers,

[[numbers-4-47]]
^47^ from thirty years and above, until the fiftieth year, entering for the ministry of the tabernacle and carrying the burdens,

[[numbers-4-48]]
^48^ were together eight thousand five hundred eighty.

[[numbers-4-49]]
^49^ Moses took a census of them, according to the word of the Lord, each one according to their office and their burdens, just as the Lord had instructed him.


[[numbers-5]]
== Chapter 5

[[numbers-5-1]]
^1^ And the Lord spoke to Moses, saying:

[[numbers-5-2]]
^2^ “Instruct the sons of Israel to cast out of the camp every leper, and those who have a flow of seed, and those who have been polluted because of the dead;

[[numbers-5-3]]
^3^ cast out of the camp both male and female, lest they contaminate it while I am dwelling with you.”

[[numbers-5-4]]
^4^ And the sons of Israel did so, and they cast them out, beyond the camp, just as the Lord had spoken to Moses.

[[numbers-5-5]]
^5^ And the Lord spoke to Moses, saying:

[[numbers-5-6]]
^6^ “Say to the sons of Israel: A man or a woman, when they have done anything out of all the sins that often befall men, or if, by negligence, they have transgressed the commandment of the Lord, and so have committed an offense,

[[numbers-5-7]]
^7^ they shall confess their sin, and they shall restore the principle itself, plus a fifth part above it, to any against whom they have sinned.

[[numbers-5-8]]
^8^ But if there would be no one to receive it, they shall give it to the Lord, and it shall be for the priest, except for the ram, which is offered for expiation, in order to be a pleasing victim.

[[numbers-5-9]]
^9^ Likewise, all the first-fruits, which the sons of Israel offer, belong to the priest,

[[numbers-5-10]]
^10^ with whatever is offered by each one at the Sanctuary, and which is delivered into the hands of the priest; it shall be his.”

[[numbers-5-11]]
^11^ And the Lord spoke to Moses, saying:

[[numbers-5-12]]
^12^ “Speak to the sons of Israel, and you shall say to them: The man whose wife will have gone astray, and, disdaining her husband,

[[numbers-5-13]]
^13^ will have slept with another man, and if her husband cannot discover it, but the adultery is secret, and if it cannot be proved by witnesses, because she was not caught in the shameful act,

[[numbers-5-14]]
^14^ if the spirit of jealousy stirs up the husband against his wife, who either has been polluted or is being assailed with a false suspicion,

[[numbers-5-15]]
^15^ he shall bring her to the priest, and he shall offer an oblation for her, a tenth part of native barley meal. He shall not pour oil over it, nor shall he place frankincense on it, because it is a sacrifice for jealousy, or an oblation investigating adultery.

[[numbers-5-16]]
^16^ Therefore, the priest shall offer it, and he shall set it in the sight of the Lord.

[[numbers-5-17]]
^17^ And he shall take up holy water in an earthen vessel, and he shall cast a little earth from the pavement of the tabernacle into it.

[[numbers-5-18]]
^18^ And while the woman stands before the Lord, he shall uncover her head, and he shall place over her hands the sacrifice of recollection and oblation of jealousy. But he shall take hold of the most bitter waters, in which he has gathered curses with loathing.

[[numbers-5-19]]
^19^ And he shall bind her by an oath, and he shall say: ‘If another man has not slept with you, and if you have not been polluted by forsaking the bed of your husband, these most bitter waters, into which I have gathered curses, shall not harm you.

[[numbers-5-20]]
^20^ But if you have turned away from your husband, and also have been defiled, and have lain together with another man,

[[numbers-5-21]]
^21^ these curses shall be thrown upon you: May the Lord turn you into a curse and an example among all his people. May he cause your thigh to rot, and may your abdomen swell up and burst out.

[[numbers-5-22]]
^22^ May the cursed waters enter into your stomach, and may your womb swell and your thigh rot.’ And the woman shall respond: ‘Amen, amen.’

[[numbers-5-23]]
^23^ And the priest shall write these curses in a little book, and then he shall erase them with the very bitter waters, into which he had gathered the curses,

[[numbers-5-24]]
^24^ and he shall give it to her to drink. And when she has emptied it,

[[numbers-5-25]]
^25^ the priest shall take from her hand the sacrifice of jealousy, and he shall elevate it before the Lord, and he shall impose it upon the altar. Yet only after he first

[[numbers-5-26]]
^26^ takes a handful of the sacrifice from that which is offered, and burns it upon the altar, and then he may give the most bitter waters to the woman as a drink.

[[numbers-5-27]]
^27^ And when she drinks it, if she has been defiled, and, having despised her husband, is guilty of adultery, the curse shall pass through her, and as her belly swells up, her thigh shall decay, and the woman shall become a curse and an example to all the people.

[[numbers-5-28]]
^28^ But if she has not been defiled, she shall be unharmed and she shall bear children.

[[numbers-5-29]]
^29^ This is the law for jealousy. If a woman has turned aside from her husband, and if she has been polluted,

[[numbers-5-30]]
^30^ and if the husband, being stirred up by the spirit of jealousy, has brought her before the sight of the Lord, and the priest has acted toward her according to all that has been written:

[[numbers-5-31]]
^31^ then the husband shall be without guilt, and she shall bear her iniquity.”


[[numbers-6]]
== Chapter 6

[[numbers-6-1]]
^1^ And the Lord spoke to Moses, saying:

[[numbers-6-2]]
^2^ “Speak to the sons of Israel, and you shall say to them: A man or a woman, when they have made a vow so that they may be sanctified, and when they are willing to consecrate themselves to the Lord,

[[numbers-6-3]]
^3^ shall abstain from wine and from anything which is able to inebriate. They shall not drink vinegar made from wine or from any other drink, nor anything pressed from the grape. They shall not eat grapes, neither fresh nor dried.

[[numbers-6-4]]
^4^ During all the days that they are consecrated to the Lord by vow, they shall not eat whatever may be from the vineyard, from raisins, even to grape seeds.

[[numbers-6-5]]
^5^ During all the time of his separation, no razor shall pass over his head, even until the completion of the day when he is consecrated to the Lord. He shall be holy, letting the hair of his head grow long.

[[numbers-6-6]]
^6^ During all the time of his consecration, he shall not enter because of a death,

[[numbers-6-7]]
^7^ nor shall he contaminate himself, even over the funeral of his father, or his mother, or his brother, or his sister. For the consecration of his God is upon his head.

[[numbers-6-8]]
^8^ During all the days of his separation, he shall be holy to the Lord.

[[numbers-6-9]]
^9^ But if anyone will have died unexpectedly before him, the head of his consecration shall be polluted, and he shall shave it in that very place, on the same day of his purification, and again on the seventh day.

[[numbers-6-10]]
^10^ Then, on the eighth day, he shall offer two turtledoves or two young pigeons, to the priest at the entrance to the covenant of the testimony.

[[numbers-6-11]]
^11^ And the priest shall effect one for sin, and the other as a holocaust, and he shall pray for him, because he has sinned on account of the dead. And he shall sanctify his head on that day.

[[numbers-6-12]]
^12^ And he shall consecrate to the Lord the days of his separation, offering a one-year-old lamb for sin, yet in such a manner that the former days will be made null and void, because his sanctification was polluted.

[[numbers-6-13]]
^13^ This is the law of consecration. When the days that he had decreed by vow have been completed, he shall bring him to the door of the tabernacle of the covenant,

[[numbers-6-14]]
^14^ and he shall offer his oblation to the Lord: an immaculate one-year-old male lamb as a holocaust, and an immaculate one-year-old female lamb for sin, and an immaculate ram, a peace-offering victim,

[[numbers-6-15]]
^15^ also, a basket of unleavened bread, which has been sprinkled with oil, and cakes without leaven, anointed with oil, as well as the libations of each one.

[[numbers-6-16]]
^16^ And the priest shall offer them before the Lord, and he shall perform both the sin offering and the holocaust.

[[numbers-6-17]]
^17^ Yet truly, the ram he shall immolate as a peace-offering victim to the Lord, offering at the same time the basket of unleavened bread, and the libations which are required by custom.

[[numbers-6-18]]
^18^ Then the Nazarite shall be shaved of the long hair of his consecration, before the door of the tabernacle of the covenant. And he shall take his hair, and he shall place it upon the fire, which is under the sacrifice of the peace offerings.

[[numbers-6-19]]
^19^ And he shall take the cooked shoulder of the ram, and one twist of bread without leaven from the basket, and one unleavened cake, and he shall deliver them into the hands of the Nazarite, after his head has been shaven.

[[numbers-6-20]]
^20^ And receiving them again from him, he shall elevate them in the sight of the Lord. And having been sanctified, these shall be for the priest, as also the breast, which was ordered to be separated, and the leg. After this, the Nazarite is able to drink wine.

[[numbers-6-21]]
^21^ This is the law of the Nazarite, when he has vowed his oblation to the Lord in the time of his consecration, aside from those things which his hand shall find. According to what he had vowed in his mind, so shall he do, to the perfection of his sanctification.”

[[numbers-6-22]]
^22^ And the Lord spoke to Moses, saying:

[[numbers-6-23]]
^23^ “Say to Aaron and his sons: Thus shall you bless the sons of Israel, and you shall say to them:

[[numbers-6-24]]
^24^ ‘May the Lord bless you and keep you.

[[numbers-6-25]]
^25^ May the Lord reveal his face to you and take pity on you.

[[numbers-6-26]]
^26^ May the Lord turn his countenance toward you and grant peace to you.’

[[numbers-6-27]]
^27^ And they shall invoke my name over the sons of Israel, and I will bless them.”


[[numbers-7]]
== Chapter 7

[[numbers-7-1]]
^1^ Now it happened in the day when Moses completed the tabernacle, and he set it up, and he anointed and sanctified it with all of its vessels, and similarly the altar and all of its vessels,

[[numbers-7-2]]
^2^ that the leaders of Israel and the heads of the families, who were in each tribe and who were in charge of those who had been numbered, offered

[[numbers-7-3]]
^3^ their gifts in the sight of the Lord: six covered wagons with twelve oxen. Two leaders offered one wagon, and each offered one ox, and they offered these in the sight of the tabernacle.

[[numbers-7-4]]
^4^ Then the Lord said to Moses:

[[numbers-7-5]]
^5^ “Receive these things from them, in order to serve in the ministry of the tabernacle, and you shall deliver them to the Levites, according to the order of their ministry.”

[[numbers-7-6]]
^6^ And so Moses, having received the wagons and the oxen, delivered them to the Levites.

[[numbers-7-7]]
^7^ Two wagons and four oxen he gave to the sons of Gershon, according to what they needed.

[[numbers-7-8]]
^8^ The other four wagons and eight oxen he gave to the sons of Merari, according to their offices and service, under the hand of Ithamar, the son of Aaron the priest.

[[numbers-7-9]]
^9^ But to the sons of Kohath he gave no wagons or oxen, because they serve in the Sanctuary and they carry their burdens on their shoulders.

[[numbers-7-10]]
^10^ Therefore, the leaders offered, at the dedication of the altar on the day when it was anointed, their oblation before the altar.

[[numbers-7-11]]
^11^ And the Lord said to Moses: “Let each of the leaders, on each of the days, offer their gifts for the dedication of the altar.”

[[numbers-7-12]]
^12^ On the first day, Nahshon, the son of Amminadab of the tribe of Judah, offered his oblation.

[[numbers-7-13]]
^13^ And in it were these: a silver dish weighing one hundred thirty shekels, a silver bowl having seventy shekels, according to the weight of the Sanctuary, and both were filled with fine wheat flour sprinkled with oil as a sacrifice,

[[numbers-7-14]]
^14^ a little mortar made from ten shekels of gold, filled with incense,

[[numbers-7-15]]
^15^ an ox from the herd, and a ram, and a one-year-old lamb as a holocaust,

[[numbers-7-16]]
^16^ and a he-goat for sin;

[[numbers-7-17]]
^17^ and for the sacrifice of peace offerings: two oxen, five rams, five he-goats, and five one-year-old lambs. This was the oblation of Nahshon, the son of Amminadab.

[[numbers-7-18]]
^18^ On the second day, Nathanael, the son of Zuar, the leader of the tribe of Issachar, offered:

[[numbers-7-19]]
^19^ a silver dish weighing one hundred thirty shekels, a silver bowl having seventy shekels, according to the weight of the Sanctuary, and both were filled with fine wheat flour sprinkled with oil as a sacrifice,

[[numbers-7-20]]
^20^ a little mortar of gold having ten shekels, filled with incense,

[[numbers-7-21]]
^21^ an ox from the herd, and a ram, and one-year-old lamb as a holocaust,

[[numbers-7-22]]
^22^ and a he-goat for sin;

[[numbers-7-23]]
^23^ and for the sacrifice of peace offerings: two oxen, five rams, five he-goats, and five one-year-old lambs. This was the oblation of Nathanael, the son of Zuar.

[[numbers-7-24]]
^24^ On the third day, the leader of the sons of Zebulon, Eliab the son of Helon,

[[numbers-7-25]]
^25^ offered a silver dish weighing one hundred thirty shekels, a silver bowl having seventy shekels, by the weight of the Sanctuary, and both were filled with fine wheat flour sprinkled with oil as a sacrifice,

[[numbers-7-26]]
^26^ a little mortar of gold weighing ten shekels, filled with incense,

[[numbers-7-27]]
^27^ an ox from the herd, and a ram, and one-year-old lamb as a holocaust,

[[numbers-7-28]]
^28^ and a he-goat for sin;

[[numbers-7-29]]
^29^ and for the sacrifice of peace offerings: two oxen, five rams, five he-goats, and five one-year-old lambs. This is the oblation of Eliab the son of Helon.

[[numbers-7-30]]
^30^ On the fourth day, the leader of the sons of Ruben, Elizur the son of Shedeur,

[[numbers-7-31]]
^31^ offered a silver dish weighing one hundred thirty shekels, a silver bowl having seventy shekels, by the weight of the Sanctuary, and both were filled with fine wheat flour sprinkled with oil as a sacrifice,

[[numbers-7-32]]
^32^ a little mortar of gold weighing ten shekels, filled with incense,

[[numbers-7-33]]
^33^ an ox from the herd, and a ram, and a one-year-old lamb as a holocaust,

[[numbers-7-34]]
^34^ and a he-goat for sin;

[[numbers-7-35]]
^35^ and for victims of peace offerings: two oxen, five rams, five he-goats, and five one-year-old lambs. This was the oblation of Elizur, the son of Shedeur.

[[numbers-7-36]]
^36^ On the fifth day, the leader of the sons of Simeon, Shelumiel the son of Zurishaddai,

[[numbers-7-37]]
^37^ offered a silver dish weighing one hundred thirty shekels, a silver bowl having seventy shekels, by the weight of the Sanctuary, and both were filled with fine wheat flour sprinkled with oil as a sacrifice,

[[numbers-7-38]]
^38^ a little mortar of gold weighing ten shekels, filled with incense,

[[numbers-7-39]]
^39^ an ox from the herd, and a ram, and a one-year-old lamb as a holocaust,

[[numbers-7-40]]
^40^ and a he-goat for sin;

[[numbers-7-41]]
^41^ and for victims of peace offerings: two oxen, five rams, five he-goats, and five one-year-old lambs. This was the oblation of Shelumiel, the son of Zurishaddai.

[[numbers-7-42]]
^42^ On the sixth day, the leader of the sons of Gad, Eliasaph the son of Reuel,

[[numbers-7-43]]
^43^ offered a silver dish weighing one hundred thirty shekels, a silver bowl having seventy shekels, by the weight of the Sanctuary, and both were filled with fine wheat flour sprinkled with oil as a sacrifice,

[[numbers-7-44]]
^44^ a little mortar of gold weighing ten shekels, filled with incense,

[[numbers-7-45]]
^45^ an ox from the herd, and a ram, and one-year-old lamb as a holocaust,

[[numbers-7-46]]
^46^ and a he-goat for sin;

[[numbers-7-47]]
^47^ and for victims of peace offerings: two oxen, five rams, five he-goats, and five one-year-old lambs. This was the oblation of Eliasaph, the son of Reuel.

[[numbers-7-48]]
^48^ On the seventh day, the leader of the sons of Ephraim, Elishama the son of Ammihud,

[[numbers-7-49]]
^49^ offered a silver dish weighing one hundred thirty shekels, a silver bowl having seventy shekels, by the weight of the Sanctuary, and both were filled with fine wheat flour sprinkled with oil as a sacrifice,

[[numbers-7-50]]
^50^ a little mortar of gold weighing ten shekels, filled with incense,

[[numbers-7-51]]
^51^ an ox from the herd, and a ram, and one-year-old lamb as a holocaust,

[[numbers-7-52]]
^52^ and a he-goat for sin;

[[numbers-7-53]]
^53^ and for victims of peace offerings: two oxen, five rams, five he-goats, and five one-year-old lambs. This was the oblation of Elishama, the son of Ammihud.

[[numbers-7-54]]
^54^ On the eighth day, the leader of the sons of Manasseh, Gamaliel the son of Pedahzur,

[[numbers-7-55]]
^55^ offered a silver dish weighing one hundred thirty shekels, a silver bowl having seventy shekels, by the weight of the Sanctuary, and both were filled with fine wheat flour sprinkled with oil as a sacrifice,

[[numbers-7-56]]
^56^ a little mortar of gold weighing ten shekels, filled with incense,

[[numbers-7-57]]
^57^ an ox from the herd, and a ram, and a one-year-old lamb as a holocaust,

[[numbers-7-58]]
^58^ and a he-goat for sin;

[[numbers-7-59]]
^59^ and for victims of peace offerings: two oxen, five rams, five he-goats, and five one-year-old lambs. This was the oblation of Gamaliel, the son of Pedahzur.

[[numbers-7-60]]
^60^ On the ninth day, the leader of the sons of Benjamin, Abidan the son of Gideoni,

[[numbers-7-61]]
^61^ offered a silver dish weighing one hundred thirty shekels, a silver bowl having seventy shekels, by the weight of the Sanctuary, and both were filled with fine wheat flour sprinkled with oil as a sacrifice,

[[numbers-7-62]]
^62^ a little mortar of gold weighing ten shekels, filled with incense,

[[numbers-7-63]]
^63^ an ox from the herd, and a ram, and a one-year-old lamb as a holocaust,

[[numbers-7-64]]
^64^ and a he-goat for sin;

[[numbers-7-65]]
^65^ and for victims of peace offerings: two oxen, five rams, five he-goats, and five one-year-old lambs. This was the oblation of Abidan, the son of Gideoni.

[[numbers-7-66]]
^66^ On the tenth day, the leaders of the sons of Dan, Ahiezer the son of Ammishaddai,

[[numbers-7-67]]
^67^ offered a silver dish weighing one hundred thirty shekels, a silver bowl having seventy shekels, by the weight of the Sanctuary, and both were filled with fine wheat flour sprinkled with oil as a sacrifice,

[[numbers-7-68]]
^68^ a little mortar of gold weighing ten shekels, filled with incense,

[[numbers-7-69]]
^69^ an ox from the herd, and a ram, and a one-year-old lamb as a holocaust,

[[numbers-7-70]]
^70^ and a he-goat for sin;

[[numbers-7-71]]
^71^ and for victims of peace offerings: two oxen, five rams, five he-goats, and five one-year-old lambs. This was the oblation of Ahiezer, the son of Ammishaddai.

[[numbers-7-72]]
^72^ On the eleventh day, the leader of the sons of Asher, Pagiel the son of Ochran,

[[numbers-7-73]]
^73^ offered a silver dish weighing one hundred thirty shekels, a silver bowl having seventy shekels, by the weight of the Sanctuary, and both were filled with fine wheat flour sprinkled with oil as a sacrifice,

[[numbers-7-74]]
^74^ a little mortar of gold weighing ten shekels, filled with incense,

[[numbers-7-75]]
^75^ an ox from the herd, and a ram, and a one-year-old lamb as a holocaust,

[[numbers-7-76]]
^76^ and a he-goat for sin;

[[numbers-7-77]]
^77^ and for victims of peace offerings: two oxen, five rams, five he-goats, and five one-year-old lambs. This was the oblation of Pagiel, the son of Ochran.

[[numbers-7-78]]
^78^ On the twelfth day, the leader of the sons of Naphtali, Ahira the son of Enan,

[[numbers-7-79]]
^79^ offered a silver dish weighing one hundred thirty shekels, a silver bowl having seventy shekels, by the weight of the Sanctuary, and both were filled with fine wheat flour sprinkled with oil as a sacrifice,

[[numbers-7-80]]
^80^ a little mortar of gold weighing ten shekels, filled with incense,

[[numbers-7-81]]
^81^ an ox from the herd, and a ram, and a one-year-old lamb as a holocaust,

[[numbers-7-82]]
^82^ and a he-goat for sin;

[[numbers-7-83]]
^83^ and for victims of peace offerings: two oxen, five rams, five he-goats, and five one-year-old lambs. This was the oblation of Ahira, the son of Enan.

[[numbers-7-84]]
^84^ These were the oblations from the leaders of Israel for the dedication of the altar on the day when it was consecrated: twelve dishes of silver, twelve bowls of silver, twelve little mortars of gold,

[[numbers-7-85]]
^85^ such that each dish had one hundred thirty shekels of silver, and each bowl had seventy shekels, that is, putting all of the vessels from silver together, two thousand four hundred shekels, by the weight of the Sanctuary,

[[numbers-7-86]]
^86^ and twelve little mortars of gold, filled with incense, weighing ten shekels by the weight of the Sanctuary, that is, all together one hundred twenty shekels of gold,

[[numbers-7-87]]
^87^ and twelve oxen from the herd as a holocaust, twelve rams, twelve one-year-old lambs, with their libations, and twelve he-goats for sin;

[[numbers-7-88]]
^88^ and for victims of peace offerings: twenty-four oxen, sixty rams, sixty he-goats, and sixty one-year-old lambs. These were the oblations for the dedication of the altar, when it was anointed.

[[numbers-7-89]]
^89^ And when Moses entered into the tabernacle of the covenant, to consult the oracle, he heard the voice of One speaking to him from the propitiatory, which is over the ark of the testimony between the two cherubim, and there he also spoke to him.


[[numbers-8]]
== Chapter 8

[[numbers-8-1]]
^1^ And the Lord spoke to Moses, saying:

[[numbers-8-2]]
^2^ “Speak to Aaron, and you shall say to him: When you place the seven lamps, let the lampstand be set up on the south side. Therefore, give this instruction: that the lamps should look out from the region opposite the north, toward the table of the bread of the presence; they shall give light opposite that area, toward the area that the lampstand faces.”

[[numbers-8-3]]
^3^ And Aaron did so, and he placed the lamps on the lampstand, just as the Lord had instructed Moses.

[[numbers-8-4]]
^4^ Now this was the workmanship of the lampstand: it was of ductile gold, both the main shaft and all that originated from both sides of the branches. According to the example that the Lord revealed to Moses, so did he make the lampstand.

[[numbers-8-5]]
^5^ And the Lord spoke to Moses, saying:

[[numbers-8-6]]
^6^ “Take the Levites from the midst of the sons of Israel, and you shall purify them

[[numbers-8-7]]
^7^ according to this ritual: Let them be sprinkled with the water of illumination, and let them shave off all the hairs of their body. And when they have washed their garments and have been cleansed,

[[numbers-8-8]]
^8^ they shall take an ox from the herd, with its libation of fine wheat flour sprinkled with oil; then you shall receive another ox from the herd for sin.

[[numbers-8-9]]
^9^ And you shall bring forward the Levites before the tabernacle of the covenant, calling together all the multitude of the sons of Israel.

[[numbers-8-10]]
^10^ And when the Levites are before the Lord, the sons of Israel shall place their hands upon them.

[[numbers-8-11]]
^11^ And Aaron shall offer the Levites as a gift in the sight of the Lord, from the sons of Israel, so that they may serve in his ministry.

[[numbers-8-12]]
^12^ Likewise, the Levites shall place their hands upon the heads of the oxen; you shall make use of one of these for sin, and the other as a holocaust to the Lord, so that you may intercede for them.

[[numbers-8-13]]
^13^ And you shall set the Levites in the sight of Aaron and his sons, and you shall consecrate those being offered to the Lord,

[[numbers-8-14]]
^14^ and you shall separate them from the midst of the sons of Israel, so that they may be for me.

[[numbers-8-15]]
^15^ And after this, they shall enter the tabernacle of the covenant, in order to serve me. And so shall you purify and consecrate them as an oblation to the Lord. For they were given to me as a gift from the sons of Israel.

[[numbers-8-16]]
^16^ I have accepted them in place of the firstborn which open every womb in Israel.

[[numbers-8-17]]
^17^ For all the firstborn of the sons of Israel, as much from men as from beasts, are mine. From the day when I struck down all the firstborn in the land of Egypt, I have sanctified them to myself.

[[numbers-8-18]]
^18^ And I have taken the Levites in place of all the firstborn of the sons of Israel.

[[numbers-8-19]]
^19^ And I have delivered them as a gift to Aaron and his sons, from the midst of the people, in order to serve me, for Israel, in the tabernacle of the covenant, and in order to pray for them, lest there be a scourge among the people, if they were to dare to approach to my Sanctuary.”

[[numbers-8-20]]
^20^ And Moses and Aaron, and all the multitude of the sons of Israel, accomplished all that the Lord had commanded Moses concerning the Levites.

[[numbers-8-21]]
^21^ And they were purified, and they washed their garments. And Aaron lifted them up in the sight of the Lord, and he prayed for them,

[[numbers-8-22]]
^22^ so that, having been purified, they might enter to their duties in the tabernacle of the covenant before Aaron and his sons. Just as the Lord had instructed Moses about the Levites, so was it done.

[[numbers-8-23]]
^23^ And the Lord spoke to Moses, saying:

[[numbers-8-24]]
^24^ “This is the law of the Levites: From twenty-five years and above, they shall enter to minister in the tabernacle of the covenant.

[[numbers-8-25]]
^25^ And when they will have completed the fiftieth year of age, they shall cease to serve.

[[numbers-8-26]]
^26^ And they shall be the ministers of their brothers in the tabernacle of the covenant, in order to care for the things that have been commended to them, but not to perform the works themselves. So shall you assign the Levites in their duties.”


[[numbers-9]]
== Chapter 9

[[numbers-9-1]]
^1^ The Lord spoke to Moses in the desert of Sinai, in the second year after they departed from the land of Egypt, in the first month, saying:

[[numbers-9-2]]
^2^ “Let the sons of Israel observe the Passover at its proper time,

[[numbers-9-3]]
^3^ on the fourteenth day of this month, in the evening, according to all of its ceremonies and justifications.”

[[numbers-9-4]]
^4^ And Moses instructed the sons of Israel, so that they would observe the Passover.

[[numbers-9-5]]
^5^ And they observed it at its proper time: on the fourteenth day of the month, in the evening, at mount Sinai. The sons of Israel acted according to all the things that the Lord had commanded Moses.

[[numbers-9-6]]
^6^ But behold, certain ones, who were not able to observe the Passover on that day, being unclean because of the life of a man, approaching Moses and Aaron,

[[numbers-9-7]]
^7^ said to them: “We are unclean because of the life of a man. Why have we been cheated, in that we are not permitted to offer, at its proper time, the oblation to the Lord among the sons of Israel?”

[[numbers-9-8]]
^8^ And Moses responded to them: “Remain, so that I may consult the Lord, as to what he will rule about you.”

[[numbers-9-9]]
^9^ And the Lord spoke to Moses, saying:

[[numbers-9-10]]
^10^ “Say to the sons of Israel: The man who becomes unclean because of a life, or if he is on a distant journey within your nation, let him observe the Passover to the Lord.

[[numbers-9-11]]
^11^ In the second month, on the fourteenth day of the month, in the evening, they shall eat it with unleavened bread and wild lettuce.

[[numbers-9-12]]
^12^ They shall not leave behind any of it until morning, and they shall not break a bone of it; they shall observe all the rituals of the Passover.

[[numbers-9-13]]
^13^ But if any man was both clean, and not on a journey, and yet he did not observe the Passover, that soul shall be exterminated from among his people, because he did not offer the sacrifice to the Lord in its time. He shall bear his sin.

[[numbers-9-14]]
^14^ Likewise, the sojourner and the newcomer, if they are among you, shall observe the Passover to the Lord according to its ceremonies and justifications. The same precept shall be with you, as much for the newcomer as for the native.”

[[numbers-9-15]]
^15^ And so, on the day when the tabernacle was raised, a cloud covered it. But over the tabernacle, from evening until morning, there was, as it seemed, the appearance of fire.

[[numbers-9-16]]
^16^ This was so continually: throughout the day a cloud covered it, and throughout the night, the appearance of fire.

[[numbers-9-17]]
^17^ And when the cloud that was protecting the tabernacle had been taken up, then the sons of Israel advanced forward, and in the place where the cloud had remained standing, there they made camp.

[[numbers-9-18]]
^18^ Upon the order of the Lord they advanced, and upon his order they fixed the tabernacle. All the days during which the cloud was standing over the tabernacle, they remained in the same place.

[[numbers-9-19]]
^19^ And if it happened that it remained for a long time over it, the sons of Israel kept the night watches of the Lord, and they did not advance,

[[numbers-9-20]]
^20^ during as many days as the cloud remained over the tabernacle. At the command of the Lord they raised their tents, and at his command they took them down.

[[numbers-9-21]]
^21^ If the cloud remained from evening until morning, and immediately, at first light, it left the tabernacle, they set out. And if it withdrew after a day and a night, they dismantled their tents.

[[numbers-9-22]]
^22^ Yet truly, whether it remained over the tabernacle for two days, or one month, or a longer time, the sons of Israel remained in the same place, and they did not set out. Then, as soon as it withdrew, they moved the camp.

[[numbers-9-23]]
^23^ By the word of the Lord they fixed their tents, and by his word they advanced. And they kept the night watches of the Lord, according to his command by the hand of Moses.


[[numbers-10]]
== Chapter 10

[[numbers-10-1]]
^1^ And the Lord spoke to Moses, saying:

[[numbers-10-2]]
^2^ “Make for yourself two trumpets of ductile silver, with which you may be able to call together the multitude when the camp is to be moved.

[[numbers-10-3]]
^3^ And when you sound the trumpets, all the multitude shall gather to you at the door of the tabernacle of the covenant.

[[numbers-10-4]]
^4^ If you sound it only once, the leaders and the heads of the multitude of Israel shall come to you.

[[numbers-10-5]]
^5^ But if the sound of the trumpets is prolonged, but with interruptions, those who are toward the east side shall move the camp first.

[[numbers-10-6]]
^6^ Then, at the second sounding of the trumpet with the same cadence, those who live toward the south shall take up their tents. And the remainder shall act in like manner, when the trumpets shall reverberate for a departure.

[[numbers-10-7]]
^7^ But when the people are to be gathered together, the sound of the trumpets shall be simple, and the sounds shall not be separated.

[[numbers-10-8]]
^8^ Now it is the sons of Aaron the priest who shall sound the trumpets. And this shall be an everlasting ordinance, in your generations.

[[numbers-10-9]]
^9^ If you go forth to war from your land, against the enemies who set out against you, you shall sound the trumpets repeatedly, and there shall be a remembrance of you before the Lord your God, so that you may be rescued from the hands of your enemies.

[[numbers-10-10]]
^10^ If at any time you will have a banquet, and on feast days, and on the first days of the months, you shall sound the trumpets over the holocausts and the peace-offering victims, so that they may be for you as a remembrance by your God. I am the Lord your God.”

[[numbers-10-11]]
^11^ In the second year, in the second month, on the twentieth day of the month, the cloud was lifted up from the tabernacle of the covenant.

[[numbers-10-12]]
^12^ And the sons of Israel set out by their companies from the desert of Sinai, and the cloud rested in the wilderness of Paran.

[[numbers-10-13]]
^13^ And the first to move their camp, according to the command of the Lord by the hand of Moses,

[[numbers-10-14]]
^14^ were the sons of Judah by their companies, whose leader was Nahshon the son of Amminadab.

[[numbers-10-15]]
^15^ In the tribe of the sons of Issachar, the leader was Nathanael the son of Zuar.

[[numbers-10-16]]
^16^ In the tribe of Zebulon, the leader was Eliab the son of Helon.

[[numbers-10-17]]
^17^ And the tabernacle was taken down, because the sons of Gershon and Merari, who carry it, were departing.

[[numbers-10-18]]
^18^ And the sons of Ruben also set out, by their companies and ranks, whose leader was Elizur the son of Shedeur.

[[numbers-10-19]]
^19^ And in the tribe of Simeon, the leader was Shelumiel the son of Zurishaddai.

[[numbers-10-20]]
^20^ And in the tribe of Gad, the leader was Eliasaph the son of Reuel.

[[numbers-10-21]]
^21^ Then the Kohathites also set out, carrying the Sanctuary. The tabernacle was carried, all the while, until they arrived at the place for setting it up.

[[numbers-10-22]]
^22^ The sons of Ephraim also moved their camp by their companies, and the leader of their army was Elishama the son of Ammihud.

[[numbers-10-23]]
^23^ And in the tribe of the sons of Manasseh, the leader was Gamaliel the son of Pedahzur.

[[numbers-10-24]]
^24^ And in the tribe of Benjamin, the leader was Abidan the son of Gideoni.

[[numbers-10-25]]
^25^ The last of all the camp to set out were the sons of Dan by their companies, and the leader of their army was Ahiezer the son of Ammishaddai.

[[numbers-10-26]]
^26^ And in the tribe of the sons of Asher, the leader was Pagiel the son of Ochran.

[[numbers-10-27]]
^27^ And in the tribe of the sons of Naphtali, the leader was Ahira the son of Enan.

[[numbers-10-28]]
^28^ These were the camps and departures of the sons of Israel by their companies, when they went forth.

[[numbers-10-29]]
^29^ And Moses said to Hobab the son of Raguel the Midianite, his kinsman: “We are setting out to the place which the Lord will give to us. Come with us, so that we may do good to you. For the Lord has promised good things to Israel.”

[[numbers-10-30]]
^30^ And he answered him, “I will not go with you, but I will return to my own land, in which I was born.”

[[numbers-10-31]]
^31^ And he said: “Do not choose to leave us. For you know in which places in the desert we ought to make camp, and so you shall be our guide.

[[numbers-10-32]]
^32^ And if you come with us, whatever will be best among the riches which the Lord will deliver to us, we will give to you.”

[[numbers-10-33]]
^33^ Therefore, they set out from the Mountain of the Lord on a journey of three days. And the ark of the covenant of the Lord preceded them, for three days, in order to provide a place for the camp.

[[numbers-10-34]]
^34^ Likewise, the cloud of the Lord was over them, throughout the day, while they proceeded.

[[numbers-10-35]]
^35^ And when the ark was lifted up, Moses said, “Rise up, O Lord, and let your enemies be scattered, and let those who hate you flee from your face.”

[[numbers-10-36]]
^36^ And when it was set down, he said: “Return, O Lord, to the multitude of the army of Israel.”


[[numbers-11]]
== Chapter 11

[[numbers-11-1]]
^1^ Meanwhile, there arose a murmur among the people against the Lord, as if they were grief-stricken because of their labors. And when the Lord had heard it, he was angry. And when the fire of the Lord was enflamed against them, it devoured those who were at the extreme end of the camp.

[[numbers-11-2]]
^2^ And when the people had cried out to Moses, Moses prayed to the Lord, and the fire was consumed.

[[numbers-11-3]]
^3^ And he called the name of that place, ‘The Burning,’ because the fire of the Lord had burned against them.

[[numbers-11-4]]
^4^ So then, the mix of common people, who had ascended with them, were enflamed with desire, and sitting and weeping, with the sons of Israel joining them, they said, “Who will give us flesh to eat?

[[numbers-11-5]]
^5^ We remember the fish that we ate freely in Egypt; we call to mind the cucumbers, and melons, and leeks, and onions, and garlic.

[[numbers-11-6]]
^6^ Our life is dry; our eyes look out to see nothing but manna.”

[[numbers-11-7]]
^7^ Now the manna was like coriander seed, but with the color of bdellium.

[[numbers-11-8]]
^8^ And the people wandered about, gathering it, and they crushed it with a millstone, or ground it with a mortar; then they boiled it in a pot, and made biscuits out of it, with a taste like bread made with oil.

[[numbers-11-9]]
^9^ And when the dew descended in the night over the camp, the manna descended together with it.

[[numbers-11-10]]
^10^ And so, Moses heard the people weeping by their families, each one at the door of his tent. And the fury of the Lord was greatly enflamed. And to Moses also the matter seemed intolerable.

[[numbers-11-11]]
^11^ And so he said to the Lord: “Why have you afflicted your servant? Why do I not find favor before you? And why have you imposed the weight of this entire people upon me?

[[numbers-11-12]]
^12^ Could I have conceived this entire multitude, or have given birth to them, so that you might say to me: Carry them in your bosom, as a nursemaid usually carries a little infant, and bring them into the land, about which you have sworn to their fathers?

[[numbers-11-13]]
^13^ From where would I obtain the flesh to give to so great a multitude? They weep against me, saying, ‘Give us flesh, so that we may eat.’

[[numbers-11-14]]
^14^ I alone am unable to sustain this entire people, because it is too heavy for me.

[[numbers-11-15]]
^15^ But if it seems to you otherwise, I beg you to put me to death, and so may I find grace in your eyes, lest I be afflicted with such evils.”

[[numbers-11-16]]
^16^ And the Lord said to Moses: “Gather to me seventy men from the elders of Israel, whom you know to be elders, as well as teachers, of the people. And you shall lead them to the door of the tabernacle of the covenant, and you shall cause them to stand there with you,

[[numbers-11-17]]
^17^ so that I may descend and speak to you. And I will take from your spirit, and I will deliver it to them, so that, with you, they may sustain the burden of the people, and so that you will not be weighed down alone.

[[numbers-11-18]]
^18^ You shall also say to the people: Be sanctified. Tomorrow you will eat flesh. For I have heard you say: ‘Who will give us flesh to eat? It was well with us in Egypt.’ So then, may the Lord give you flesh. And you will eat,

[[numbers-11-19]]
^19^ not for one day, nor for two, nor for five, nor for ten, nor even for twenty,

[[numbers-11-20]]
^20^ but for up to a month of days, until it exits from your nostrils, and until it turns into nausea for you, because you have slipped away from the Lord, who is in your midst, and because you have wept before him, saying: ‘Why did we go forth out of Egypt?’ ”

[[numbers-11-21]]
^21^ And Moses said: “There are six hundred thousand footmen of this people, and yet you say, ‘I will give them flesh to eat for a whole month.’

[[numbers-11-22]]
^22^ Could a multitude of sheep and oxen be slain, so that there would be enough food? Or will the fishes of the sea be gathered together, in order to satisfy them?”

[[numbers-11-23]]
^23^ And the Lord answered him: “Can the hand of the Lord be ineffective? Soon now, you shall see whether my word will be fulfilled in this work.”

[[numbers-11-24]]
^24^ And so, Moses went and explained the words of the Lord to the people. Gathering together seventy men from the elders of Israel, he caused them to stand around the tabernacle.

[[numbers-11-25]]
^25^ And the Lord descended in a cloud, and he spoke to him, taking from the Spirit which was in Moses, and giving to the seventy men. And when the Spirit had rested in them, they prophesied; nor did they cease afterwards.

[[numbers-11-26]]
^26^ Now there had remained in the camp two of the men, of whom one was called Eldad, and the other Medad, upon whom the Spirit rested; for they also had been enrolled, but they did not go forth to the tabernacle.

[[numbers-11-27]]
^27^ And when they were prophesying in the camp, a boy ran and reported to Moses, saying: “Eldad and Medad prophesy in the camp.”

[[numbers-11-28]]
^28^ Promptly, Joshua the son of Nun, the minister of Moses and chosen from many, said: “My lord Moses, prohibit them.”

[[numbers-11-29]]
^29^ But he said, “Why are you jealous on my behalf? Who decides that any of the people may prophesy and that God may give to them his Spirit?”

[[numbers-11-30]]
^30^ And Moses returned, with those greater by birth of Israel, into the camp.

[[numbers-11-31]]
^31^ Then a wind, going out from the Lord and moving forcefully across the sea, brought quails and cast them into the camp, across a distance of one day’s journey, in every part of the camp all around, and they flew in the air two cubits high above the ground.

[[numbers-11-32]]
^32^ Therefore, the people, rising up, gathered quails all that day and night, and the next day; he who did least well gathered ten homers. And they dried them throughout the camp.

[[numbers-11-33]]
^33^ The flesh was still between their teeth, neither had this kind of food ceased, and behold, the fury of the Lord was provoked against the people, and he struck them with an exceedingly great scourge.

[[numbers-11-34]]
^34^ And that place was called, ‘The Graves of Lust.’ For there, they buried the people who had desired. Then, departing from the Graves of Lust, they arrived in Hazeroth, and they stayed there.


[[numbers-12]]
== Chapter 12

[[numbers-12-1]]
^1^ And Miriam and Aaron spoke against Moses, because of his wife, an Ethiopian,

[[numbers-12-2]]
^2^ and they said: “Has the Lord spoken only through Moses? Has he not also spoken similarly to us?” And when the Lord had heard this,

[[numbers-12-3]]
^3^ (for Moses was a man exceedingly meek, beyond all the men who were living upon the earth)

[[numbers-12-4]]
^4^ immediately he spoke to him, and to Aaron and Miriam, “Go out, you three only, to the tabernacle of the covenant.” And when they had gone out,

[[numbers-12-5]]
^5^ the Lord descended in a column of cloud, and he stood at the entrance of the tabernacle, calling to Aaron and Miriam. And when they had advanced,

[[numbers-12-6]]
^6^ he said to them: “Listen to my words. If there will be among you a prophet of the Lord, I will appear to him in a vision, or I will speak to him through a dream.

[[numbers-12-7]]
^7^ But it is not so with my servant Moses, who is the most faithful in all my house.

[[numbers-12-8]]
^8^ For I speak with him mouth to mouth, and plainly. And not through enigmas and figures does he perceive the Lord. Therefore, why were you not afraid to disparage my servant Moses?”

[[numbers-12-9]]
^9^ And being angry against them, he went away.

[[numbers-12-10]]
^10^ Likewise, the cloud which was over the tabernacle withdrew. And behold, Miriam appeared to be white with a leprosy, like snow. And when Aaron had looked upon her, and he had seen the spreading of the leprosy,

[[numbers-12-11]]
^11^ he said to Moses: “I beg you, my lord, not to impose upon us this sin, which we have committed foolishly.

[[numbers-12-12]]
^12^ Do not let this one be like one who is dead, or like an abortion that has been cast from the womb of her mother. Behold, half of her flesh is already consumed by leprosy.”

[[numbers-12-13]]
^13^ And Moses cried out to the Lord, saying, “O God, I beg you: heal her.”

[[numbers-12-14]]
^14^ And the Lord answered him: “If her father had spit on her face, should she not have been filled with shame for at least seven days? Let her be separated, outside the camp, for seven days, and after that, she will be called back.”

[[numbers-12-15]]
^15^ And so Miriam was excluded from the camp for seven days. And the people did not move from that place, until Miriam was called back.


[[numbers-13]]
== Chapter 13

[[numbers-13-1]]
^1^ And the people set out from Hazeroth, and they pitched their tents in the desert of Paran.

[[numbers-13-2]]
^2^ And there, the Lord spoke to Moses, saying:

[[numbers-13-3]]
^3^ “Send men, who may examine the land of Canaan, which I will give to the sons of Israel, one from the rulers of each tribe.”

[[numbers-13-4]]
^4^ Moses did what the Lord had commanded, sending, from the desert of Paran, leading men, whose names are these:

[[numbers-13-5]]
^5^ from the tribe of Ruben, Shammua the son of Zaccur;

[[numbers-13-6]]
^6^ from the tribe of Simeon, Shaphat the son of Hori;

[[numbers-13-7]]
^7^ from the tribe of Judah, Caleb the son of Jephunneh;

[[numbers-13-8]]
^8^ from the tribe of Issachar, Igal the son of Joseph;

[[numbers-13-9]]
^9^ from the tribe of Ephraim, Hosea the son of Nun;

[[numbers-13-10]]
^10^ from the tribe of Benjamin, Palti the son of Raphu;

[[numbers-13-11]]
^11^ from the tribe of Zebulon, Gaddiel the son of Sodi;

[[numbers-13-12]]
^12^ from the tribe of Joseph, of the scepter of Manasseh, Gaddi the son of Susi;

[[numbers-13-13]]
^13^ from the tribe of Dan, Ammiel the son of Gemalli;

[[numbers-13-14]]
^14^ from the tribe of Asher, Sethur the son of Michael;

[[numbers-13-15]]
^15^ from the tribe of Naphtali, Nahbi the son of Vophsi;

[[numbers-13-16]]
^16^ from the tribe of Gad, Guel the son of Machi.

[[numbers-13-17]]
^17^ These are the names of the men, whom Moses sent to examine the land. And he called Hosea, the son of Nun, Joshua.

[[numbers-13-18]]
^18^ And so, Moses sent them to examine the land of Canaan, and he said to them: “Ascend by the south side. And when you arrive at the mountains,

[[numbers-13-19]]
^19^ consider the land, as to what kind it may be, and the people, who are its inhabitants, whether they may be strong or weak, whether they may be few in number or many,

[[numbers-13-20]]
^20^ and the land itself, whether it is good or bad, what kind of cities, walled or without walls,

[[numbers-13-21]]
^21^ the soil, rich or barren, forested or without trees. Be strong, and bring us some of the fruits of the land.” Now it was the time when the first ripe grapes were ready to be eaten.

[[numbers-13-22]]
^22^ And when they had ascended, they explored the land from the desert of Sin, all the way to Rehob, as one enters into Hamath.

[[numbers-13-23]]
^23^ And they ascended by the south side. And they arrived at Hebron, where there were Ahiman and Shishai and Talmai, the sons of Anak. For Hebron was founded seven years before Tanis, the city of Egypt.

[[numbers-13-24]]
^24^ And continuing on as far as the Torrent of the Cluster of Grapes, they cut off a vine with its grapes, which two men carried on a board. Likewise, they took from the pomegranates and the figs of that place,

[[numbers-13-25]]
^25^ which was called Nehel Eshcol, that is, the Torrent of the Cluster of Grapes, because the sons of Israel had carried a cluster of grapes from there.

[[numbers-13-26]]
^26^ And those exploring the land returned after forty days, having circulated through the entire region.

[[numbers-13-27]]
^27^ And they went to Moses and Aaron, and to the entire assembly of the sons of Israel in the desert of Paran, which is in Kadesh. And speaking to them, and to the entire multitude, they showed them the fruits of the land.

[[numbers-13-28]]
^28^ And they explained, saying: “We went into the land, to which you sent us, which, it is true, flows with milk and honey, as one can know by these fruits.

[[numbers-13-29]]
^29^ But it has very strong occupants, and the cities are great and also walled. We saw the race of Anak there.

[[numbers-13-30]]
^30^ Amalek lives in the south. The Hethite, and the Jebusite, and the Amorite live in the mountains. And truly, the Canaanite stays near the sea and around the streams of the Jordan.”

[[numbers-13-31]]
^31^ During these events, Caleb, to restrain the murmuring of the people who rose up against Moses, said, “Let us ascend and possess the land, for we will be able to obtain it.”

[[numbers-13-32]]
^32^ Yet truly, the others, who had been with him, were saying, “By no means are we able to ascend to this people, because they are stronger than we are.”

[[numbers-13-33]]
^33^ And before the sons of Israel they disparaged the land, which they had inspected, saying: “The land, which we viewed, devours its inhabitants. The people, upon whom we gazed, were of lofty stature.

[[numbers-13-34]]
^34^ There, we saw some monsters among the sons of Anak, of the race of giants; by comparison with them, we seemed like locusts.”


[[numbers-14]]
== Chapter 14

[[numbers-14-1]]
^1^ And so, crying out, the entire crowd wept throughout that night.

[[numbers-14-2]]
^2^ And all the sons of Israel were murmuring against Moses and Aaron, saying:

[[numbers-14-3]]
^3^ “If only we had died in Egypt,” and, “If only we would perish in this vast wilderness,” and, “May the Lord not lead us into this land, lest we fall by the sword, and our wives, as well as our children, be led away as captives. Is it not better to return to Egypt?”

[[numbers-14-4]]
^4^ And they said to one another, “Let us appoint our leader, and so return to Egypt.”

[[numbers-14-5]]
^5^ And when Moses and Aaron heard this, they fell prone on the ground in the sight of the multitude of the sons of Israel.

[[numbers-14-6]]
^6^ Yet truly, Joshua the son of Nun, and Caleb the son of Jephunneh, who themselves had also viewed the land, tore their garments,

[[numbers-14-7]]
^7^ and they said to the entire multitude of the sons of Israel: “The land that we circled through is very good.

[[numbers-14-8]]
^8^ If the Lord will be gracious to us, he will lead us into it, and he will give us the land flowing with milk and honey.

[[numbers-14-9]]
^9^ Do not choose to be rebellious against the Lord. And do not fear the people of this land, for, like bread, so are we able to devour them. All protection has withdrawn from them. The Lord is with us. Do not be afraid.”

[[numbers-14-10]]
^10^ And when the entire multitude cried out, and they wanted to crush them with stones, the glory of the Lord appeared, over the roof of the covenant, to all the sons of Israel.

[[numbers-14-11]]
^11^ And the Lord said to Moses: “How long will this people disparage me? How long will they refuse to believe me, despite all the signs that I have wrought before them?

[[numbers-14-12]]
^12^ Therefore, I will strike them with a pestilence, and so I will consume them. But you I will make the ruler over a great nation, and one which is mightier than this one.”

[[numbers-14-13]]
^13^ And Moses said to the Lord: “But then the Egyptians, from whose midst you led out this people,

[[numbers-14-14]]
^14^ and the inhabitants of this land, who have heard that you, O Lord, are among this people, and that you are seen face to face, and that your cloud protects them, and that you go before them with a column of cloud by day, and a column of fire by night,

[[numbers-14-15]]
^15^ may hear that you have killed so great a multitude, as if they were one man, and they may say:

[[numbers-14-16]]
^16^ ‘He was not able to lead the people into the land about which he had sworn. Therefore, he slew them in the wilderness.’

[[numbers-14-17]]
^17^ Therefore, may the strength of the Lord be magnified, just as you swore, saying:

[[numbers-14-18]]
^18^ ‘The Lord is patient and full of mercy, taking away iniquity and wickedness, and forsaking no one who is harmless. He visits the sins of the fathers upon the sons, to the third and fourth generation.’

[[numbers-14-19]]
^19^ Forgive, I beg you, the sins of this people, according to the greatness of your mercy, just as you have been gracious to them in their journey from Egypt to this place.”

[[numbers-14-20]]
^20^ And the Lord said: “I have forgiven them according to your word.

[[numbers-14-21]]
^21^ Also, as I live, the entire world shall be filled with the glory of the Lord.

[[numbers-14-22]]
^22^ And yet, all the men who have seen my majesty, and the signs that I have wrought in Egypt and in the wilderness, and who have tested me ten times already, and yet have not obeyed my voice,

[[numbers-14-23]]
^23^ these shall not see the land, about which I swore to their fathers, neither shall any of those who detracted me gaze upon it.

[[numbers-14-24]]
^24^ My servant Caleb, who, being full of another spirit, has followed me, I will lead into this land, through which he has wandered, and his offspring shall possess it.

[[numbers-14-25]]
^25^ For the Amalekites and the Canaanites live in the valleys. Tomorrow, move the camp and return into the wilderness, by the way of the Red Sea.”

[[numbers-14-26]]
^26^ And the Lord spoke to Moses and Aaron, saying:

[[numbers-14-27]]
^27^ “How long will this very wicked multitude murmur against me? I have heard the complaints of the sons of Israel.

[[numbers-14-28]]
^28^ Therefore, say to them: As I live, says the Lord, as you spoke in my hearing, so will I do to you.

[[numbers-14-29]]
^29^ In the wilderness, here shall your carcasses lie. All you who were numbered from twenty years and above, and who have murmured against me,

[[numbers-14-30]]
^30^ you shall not enter into the land, over which I lifted up my hand to cause you to live there, except Caleb the son of Jephunneh, and Joshua the son of Nun.

[[numbers-14-31]]
^31^ But your little ones, about whom you said that they would be a prey to the enemies, I will lead them in, so that they may see the land that has displeased you.

[[numbers-14-32]]
^32^ Your carcasses shall lie in the wilderness.

[[numbers-14-33]]
^33^ Your sons shall wander in the desert for forty years, and they shall bear your fornication, until the carcasses of their fathers are consumed in the desert.

[[numbers-14-34]]
^34^ According to the number of the forty days, during which you examined the land, one year shall be charged for each day. And so, for forty years you shall take back your iniquities, and you shall know my retribution.

[[numbers-14-35]]
^35^ For just as I have spoken, so shall I do, to this entire most wicked multitude, which has risen up together against me. In the wilderness, here shall it fade away and die.”

[[numbers-14-36]]
^36^ Therefore, all the men, whom Moses had sent to contemplate the land, and who, having returned, had caused the entire multitude to murmur against him, disparaging the land as if it were evil,

[[numbers-14-37]]
^37^ suffered death and were struck down in the sight of the Lord.

[[numbers-14-38]]
^38^ But only Joshua the son of Nun, and Caleb the son of Jephunneh remained alive, out of all those who had journeyed to examine the land.

[[numbers-14-39]]
^39^ And Moses spoke all these words to all the sons of Israel, and the people mourned exceedingly.

[[numbers-14-40]]
^40^ And behold, rising up at first light, they climbed to the top of the mountain, and they said, “We are prepared to ascend to the place, about which the Lord has spoken, for we have sinned.”

[[numbers-14-41]]
^41^ And Moses said to them: “Why do you transgress the word of the Lord, merely because it will not result in prosperity for you?

[[numbers-14-42]]
^42^ Do not ascend, for the Lord is not with you, lest you be overthrown before your enemies.

[[numbers-14-43]]
^43^ The Amalekite and the Canaanite are before you, by whose sword you shall be ruined, for you were not willing to consent to the Lord, and so the Lord is not with you.”

[[numbers-14-44]]
^44^ But they, having been darkened, ascended to the top of the mountain. But the ark of the testament of the Lord, and Moses, did not withdraw from the camp.

[[numbers-14-45]]
^45^ And the Amalekites descended, along with those Canaanites who were living in the mountains. And so, striking and cutting them down, they pursued them all the way to Hormah.


[[numbers-15]]
== Chapter 15

[[numbers-15-1]]
^1^ The Lord spoke to Moses, saying:

[[numbers-15-2]]
^2^ “Speak to the sons of Israel, and you shall say to them: When you will have entered into the land of your habitation, which I will give you,

[[numbers-15-3]]
^3^ and you make an offering to the Lord, as a holocaust or as a victim, paying your vows, or as a voluntary offering of gifts, or in your solemnities, burning a sweet odor to the Lord, whether from the oxen or from the sheep:

[[numbers-15-4]]
^4^ whoever immolates the victim shall offer a sacrifice of fine wheat flour, the tenth part of an ephah, sprinkled with oil, which shall have the measure of the fourth part of a hin,

[[numbers-15-5]]
^5^ and he shall give the same measure of wine, poured out as libations, whether as a holocaust or as a victim.

[[numbers-15-6]]
^6^ With each lamb and each ram, there shall be a sacrifice of fine wheat flour, of two tenths, which shall be sprinkled with one third part of a hin of oil.

[[numbers-15-7]]
^7^ And he shall offer the same measure, one third part of wine, for the libation, as a sweet odor to the Lord.

[[numbers-15-8]]
^8^ Yet truly, when you will offer, from the oxen, a holocaust or a victim, in order to fulfill your vow or for peace-offering victims,

[[numbers-15-9]]
^9^ you shall give, for each ox, three tenths of fine wheat flour, sprinkled with oil, which has the measure of one half of one hin,

[[numbers-15-10]]
^10^ and the wine, poured out as libations, shall be of the same measure, as an oblation of most sweet odor to the Lord.

[[numbers-15-11]]
^11^ So shall you do

[[numbers-15-12]]
^12^ for each ox, and ram, and lamb, and young goat.

[[numbers-15-13]]
^13^ Both natives and sojourners

[[numbers-15-14]]
^14^ shall offer sacrifices by the same rituals.

[[numbers-15-15]]
^15^ There shall be one precept and one judgment, as much for yourselves as for newcomers to the land.”

[[numbers-15-16]]
^16^ And the Lord spoke to Moses, saying:

[[numbers-15-17]]
^17^ “Speak to the sons of Israel, and you shall say to them:

[[numbers-15-18]]
^18^ When you will arrive in the land which I will give to you,

[[numbers-15-19]]
^19^ and when you will eat from the bread of that region, you shall separate the first-fruits to the Lord

[[numbers-15-20]]
^20^ from the foods that you eat. Just as you separate the first-fruits of your threshing floors,

[[numbers-15-21]]
^21^ so also shall you give the first-fruits of your cooked grains to the Lord.

[[numbers-15-22]]
^22^ And if, through ignorance, you neglect any of these things, which the Lord has spoken to Moses,

[[numbers-15-23]]
^23^ and which he has commanded through him for you, from the day that he began to command and thereafter,

[[numbers-15-24]]
^24^ and if the multitude will have forgotten to do it, then they shall offer a calf from the herd, a holocaust as a most sweet odor to the Lord, and its sacrifice and libations, just as the ceremonies ask, and a he-goat for sin.

[[numbers-15-25]]
^25^ And the priest shall pray for the entire multitude of the sons of Israel, and it shall be forgiven them, because they did not sin willfully. Nevertheless, they shall offer incense to the Lord for themselves, and for sin, as well as for their error.

[[numbers-15-26]]
^26^ And it shall be forgiven all the people of the sons of Israel, as well as the newcomers who sojourn among them, for it is the culpability of all the people through neglect.

[[numbers-15-27]]
^27^ But if one soul will have sinned by not knowing, he shall offer a one-year-old she-goat for his sin.

[[numbers-15-28]]
^28^ And the priest shall pray for him, because he sinned unknowingly before the Lord. And he shall obtain pardon for him, and it will be forgiven him.

[[numbers-15-29]]
^29^ One law shall be for all who sin by ignorance, as much for natives as for newcomers.

[[numbers-15-30]]
^30^ Yet truly, the soul who commits any of these acts through arrogance, whether he is a citizen or a sojourner, because he has rebelled against the Lord, shall perish from among his people.

[[numbers-15-31]]
^31^ For he has despised the word of the Lord, and he has nullified his precept. For this reason, he shall be destroyed, and he shall bear his iniquity.”

[[numbers-15-32]]
^32^ And it happened that, when the sons of Israel were in the wilderness, and they had found a man collecting wood on the day of the Sabbath,

[[numbers-15-33]]
^33^ they brought him to Moses and Aaron, and to the whole multitude.

[[numbers-15-34]]
^34^ And they enclosed him in a prison, not knowing what they should do with him.

[[numbers-15-35]]
^35^ And the Lord said to Moses, “Let that man be put to death; let the entire crowd crush him with stones, outside the camp.”

[[numbers-15-36]]
^36^ And when they had led him out, they overwhelmed him with stones, and he died, just as the Lord had instructed.

[[numbers-15-37]]
^37^ The Lord also said to Moses:

[[numbers-15-38]]
^38^ “Speak to the sons of Israel, and you shall tell them to make for themselves hems at the corners of their cloaks, placing in them ribbons of hyacinth,

[[numbers-15-39]]
^39^ so that, when they see these, they may remember all the commandments of the Lord, and they may not follow their own thoughts and eyes, fornicating in various ways,

[[numbers-15-40]]
^40^ but instead, they, being more mindful of the precepts of the Lord, may do them and may be holy to their God.

[[numbers-15-41]]
^41^ I am the Lord your God, who led you away from the land of Egypt, so that I may be your God.”


[[numbers-16]]
== Chapter 16

[[numbers-16-1]]
^1^ Then, behold, Korah the son of Izhar, the son of Kohath, the son of Levi, with Dathan and Abiram, the sons of Eliab, and also On the son of Peleth, of the sons of Ruben,

[[numbers-16-2]]
^2^ rose up against Moses, with two hundred fifty others of the sons of Israel, leading men of the assembly, and who, at the time of a council, would be called by name.

[[numbers-16-3]]
^3^ And when they had stood against Moses and Aaron, they said: “Let it be sufficient for you that the entire multitude is of holy ones, and that the Lord is among them. Why do you elevate yourselves above the people of the Lord?”

[[numbers-16-4]]
^4^ When Moses had heard this, he fell prone on his face.

[[numbers-16-5]]
^5^ And speaking to Korah, and to the entire multitude, he said: “In the morning, the Lord will cause it to be known who belongs to him, and which holy ones he will join to himself. And whomever he will choose, they shall be close to him.

[[numbers-16-6]]
^6^ Therefore, do this: Each one of you, Korah and all your associates, take your censer,

[[numbers-16-7]]
^7^ and drawing fire into it tomorrow, place incense upon it before the Lord. And whomever he will choose, the same shall be holy. You sons of Levi have been raised up greatly.”

[[numbers-16-8]]
^8^ And he said again to Korah: “Listen, sons of Levi.

[[numbers-16-9]]
^9^ Is it a small thing to you, that the God of Israel has separated you from all the people, and has joined you to himself, so that you would serve him in the rituals of the tabernacle, and stand before gatherings of the people, and minister to him?

[[numbers-16-10]]
^10^ Was the reason that he caused you and all your brothers, the sons of Levi, to approach him, so that you would even claim for yourselves the priesthood too,

[[numbers-16-11]]
^11^ and so that your entire group would stand against the Lord? For what is Aaron that you should murmur against him?”

[[numbers-16-12]]
^12^ Therefore, Moses sent to call for Dathan and Abiram, the sons of Eliab, who responded: “We will not come.

[[numbers-16-13]]
^13^ Is it a small matter to you, that you have led us away from a land that was flowing with milk and honey, so as to kill us in the desert, unless you could also be a ruler over us?

[[numbers-16-14]]
^14^ You have led us, it is true, to a land that flows with streams of milk and honey, and you have given us possession of fields and vineyards. But will you also tear out our eyes? We will not come.”

[[numbers-16-15]]
^15^ And Moses, being very angry, said to the Lord: “Do not look with favor on their sacrifices. You know that I have not accepted from them, at any time, so much as a young donkey, nor have I afflicted any of them.”

[[numbers-16-16]]
^16^ And he said to Korah: “You and your congregation, stand alone before the Lord, and apart from Aaron, tomorrow.

[[numbers-16-17]]
^17^ Let each one of you take censers, and place incense in them, offering to the Lord two hundred fifty censers. Let Aaron also hold his censer.”

[[numbers-16-18]]
^18^ When they had done this, Moses and Aaron stood up,

[[numbers-16-19]]
^19^ and, having crowded the entire multitude close to them at the door of the tabernacle, the glory of the Lord appeared to them all.

[[numbers-16-20]]
^20^ And the Lord, speaking to Moses and Aaron, said:

[[numbers-16-21]]
^21^ “Separate yourselves from the midst of this congregation, so that I may suddenly destroy them.”

[[numbers-16-22]]
^22^ But they fell prone on their faces, and they said, “O most strong One, the God of the spirits of all flesh, should your anger rage against all, for the sin of one?”

[[numbers-16-23]]
^23^ And the Lord said to Moses:

[[numbers-16-24]]
^24^ “Instruct the entire people to separate from the tents of Korah, and Dathan, and Abiram.”

[[numbers-16-25]]
^25^ And Moses rose up and went to Dathan and Abiram. And the elders of Israel followed him,

[[numbers-16-26]]
^26^ and he said to the crowd, “Withdraw from the tabernacles of these impious men, and touch nothing which pertains to them, lest you become involved in their sins.”

[[numbers-16-27]]
^27^ And when they had withdrawn from their tents all around, Dathan and Abiram came out and stood at the entrance of their pavilions, with their wives and children, and with all their associates.

[[numbers-16-28]]
^28^ And Moses said: “By this shall you know that the Lord has sent me to do all that you discern, and that I have not brought these things out of my own heart:

[[numbers-16-29]]
^29^ If these men pass away by the common death of men, or if they will be visited by a scourge, of a kind by which others are often visited, then the Lord did not send me.

[[numbers-16-30]]
^30^ But if the Lord accomplishes something new, so that the earth opens its mouth and swallows them whole, along with everything that belongs to them, and they descend alive into the underworld, then you shall know that they have blasphemed the Lord.”

[[numbers-16-31]]
^31^ Therefore, as soon as he had ceased to speak, the earth broke open under their feet.

[[numbers-16-32]]
^32^ And opening its mouth, it devoured them with their tabernacles and their entire substance.

[[numbers-16-33]]
^33^ And they descended alive, the ground closing around them, into the underworld, and they perished from the midst of the multitude.

[[numbers-16-34]]
^34^ Yet truly, all of Israel, which was standing all around, took flight at the clamor of those who were perishing, saying, “Lest perhaps the earth may swallow us whole also.”

[[numbers-16-35]]
^35^ Then, too, a fire, going forth from the Lord, put to death the two hundred fifty men who were offering the incense.

[[numbers-16-36]]
^36^ And the Lord spoke to Moses, saying:

[[numbers-16-37]]
^37^ “Instruct Eleazar, the son of Aaron the priest, to take up the censers which lie in the burning, and to scatter the fire to one side and another, because they were sanctified

[[numbers-16-38]]
^38^ in the deaths of these sinners. And let him form them into plates, and affix them to the altar, because incense had been offered in them to the Lord, and they were sanctified, and so that the sons of Israel may discern in them a sign and a memorial.”

[[numbers-16-39]]
^39^ Therefore, Eleazar the priest took the bronze censers, by which those whom the burning devoured had made an offering, and he formed them into plates, affixing them to the altar,

[[numbers-16-40]]
^40^ so that the sons of Israel would have, thereafter, something to admonish them, lest any stranger, or anyone who is not of the offspring of Aaron, might approach to offer incense to the Lord, and lest he endure what happened to Korah, and to all his congregation, when the Lord spoke to Moses.

[[numbers-16-41]]
^41^ Then, the following day, the entire multitude of the sons of Israel murmured against Moses and Aaron, saying: “You have put to death the people of the Lord.”

[[numbers-16-42]]
^42^ And when there arose a sedition, and the tumult increased,

[[numbers-16-43]]
^43^ Moses and Aaron fled to the tabernacle of the covenant. But after they had entered it, the cloud covered it, and the glory of the Lord appeared.

[[numbers-16-44]]
^44^ And the Lord said to Moses:

[[numbers-16-45]]
^45^ “Withdraw from the midst of this multitude, and I will destroy them immediately.” And while they were lying on the ground,

[[numbers-16-46]]
^46^ Moses said to Aaron: “Take the censer, and draw fire into it from the altar; place incense upon it, and continue on, quickly, to the people, to pray for them. For already wrath has gone forth from the Lord, and the scourge rages.”

[[numbers-16-47]]
^47^ When Aaron had done this, and he had run into the midst of the multitude, which the burning fire was now destroying, he offered the incense.

[[numbers-16-48]]
^48^ And standing between the dead and the living, he prayed for the people, and the scourge ceased.

[[numbers-16-49]]
^49^ But the number of those who were struck down was fourteen thousand men, and seven hundred, aside from those who had perished in the sedition of Korah.

[[numbers-16-50]]
^50^ And Aaron returned to Moses at the door of the tabernacle of the covenant, after the destruction quieted.


[[numbers-17]]
== Chapter 17

[[numbers-17-1]]
^1^ And the Lord spoke to Moses, saying:

[[numbers-17-2]]
^2^ “Speak to the sons of Israel, and receive from each of them a rod by their kinships, from all the leaders of the tribes, twelve rods, and write the name of each one on his rod.

[[numbers-17-3]]
^3^ But the name of Aaron shall be for the tribe of Levi, and one rod separately shall contain all their families.

[[numbers-17-4]]
^4^ And you shall place these in the tabernacle of the covenant before the testimony, where I will speak to you.

[[numbers-17-5]]
^5^ Whomever of these I will choose, his rod will germinate, and so shall I restrain the complaints of the sons of Israel before me, by which they murmur against you.”

[[numbers-17-6]]
^6^ And Moses spoke to the sons of Israel. And all the leaders gave him rods, one for each tribe. And there were twelve rods, aside from the rod of Aaron.

[[numbers-17-7]]
^7^ And when Moses had placed these before the Lord, in the tabernacle of the testimony,

[[numbers-17-8]]
^8^ returning on the following day, he found that the rod of Aaron for the house of Levi, had germinated, and that the swelling buds had opened into flowers, which, spreading their petals, were formed into those of an almond tree.

[[numbers-17-9]]
^9^ Therefore, Moses brought out all the rods, from the sight of the Lord, to all the sons of Israel. And they saw, and each one received their rods.

[[numbers-17-10]]
^10^ And the Lord said to Moses: “Carry back the rod of Aaron into the tabernacle of the testimony, so that it may be kept there as a sign of the rebellion of the sons of Israel, and so that their complaints may be quieted before me, lest they die.”

[[numbers-17-11]]
^11^ And Moses did just as the Lord had instructed.

[[numbers-17-12]]
^12^ Then the sons of Israel said to Moses: “Behold, we have been consumed; we have been ruined.

[[numbers-17-13]]
^13^ Whoever approaches to the tabernacle of the Lord dies. Will we all be wiped away, even to total annihilation?”


[[numbers-18]]
== Chapter 18

[[numbers-18-1]]
^1^ And the Lord said to Aaron: “You, and your sons, and the house of your father with you, shall carry the iniquity of the Sanctuary. And you and your sons together shall bear the sins of your priesthood.

[[numbers-18-2]]
^2^ But take to yourselves also your brothers from the tribe of Levi, and the scepter of your father, and may they be prepared, and may they minister to you. Then you and your sons shall minister in the tabernacle of the testimony.

[[numbers-18-3]]
^3^ And the Levites shall stand watch by your precepts, and for all the works of the tabernacle; yet in such a manner that they shall not approach the vessels of the Sanctuary and of the altar, lest both they die, and you perish, at the same time.

[[numbers-18-4]]
^4^ But they may be with you, and they may watch over the care of the tabernacle and all its ceremonies. A foreigner shall not be mixed with you.

[[numbers-18-5]]
^5^ Watch over the care of the Sanctuary, and over the ministry of the altar, lest an indignation may rise over the sons of Israel.

[[numbers-18-6]]
^6^ I have given your brothers, the Levites, to you from the midst of the sons of Israel, and I have delivered them as a gift to the Lord, in order to serve in the ministries of his tabernacle.

[[numbers-18-7]]
^7^ But as for you and your sons: guard the priesthood. For all that pertains to the service of the altar and of what is beyond the veil shall be exercised by the priests. If any outsider will approach, he shall be killed.”

[[numbers-18-8]]
^8^ And the Lord said to Aaron: “Behold, I have given you custody of my first-fruits. Everything that is sanctified by the sons of Israel I have delivered to you and your sons, for the office of the priesthood, by everlasting ordinances.

[[numbers-18-9]]
^9^ Therefore, you shall receive these, from the things that are sanctified and offered to the Lord. Every offering, and sacrifice, and whatever is repaid to me, on behalf of sin and also for offenses, and which becomes the Holy of holies, shall be for you and for your sons.

[[numbers-18-10]]
^10^ You shall eat it in the Sanctuary. Only the males shall eat from it, because it has been consecrated for you.

[[numbers-18-11]]
^11^ But the first-fruits, which the sons of Israel shall vow and offer, I have given to you, and to your sons, as well as to your daughters, by a perpetual right. Whoever is clean in your house shall eat them.

[[numbers-18-12]]
^12^ All the innermost of the oil, and of the wine, and of the grain, whatever first-fruits they offer to the Lord, I have given to you.

[[numbers-18-13]]
^13^ All the first of the crops, which the soil produces and which are carried to the Lord, shall fall to your use. Whoever is clean in your house shall eat them.

[[numbers-18-14]]
^14^ All that the sons of Israel shall repay by vow shall be yours.

[[numbers-18-15]]
^15^ Whatever goes out first from the womb, of all flesh, which they offer to the Lord, whether from men or from cattle, shall be your right; yet only in so far as, for the firstborn of man, you shall accept a price. And every animal that is unclean you shall cause to be redeemed.

[[numbers-18-16]]
^16^ And its redemption shall be, after one month, five shekels of silver, by the weight of the Sanctuary. A shekel has twenty obols.

[[numbers-18-17]]
^17^ But the firstborn of a cow, or of a sheep, or of a goat, you shall not cause to be redeemed, because they have been sanctified to the Lord. Thus, their blood you shall pour out upon the altar, and their fat you shall burn as a most sweet odor to the Lord.

[[numbers-18-18]]
^18^ Yet truly, the flesh shall fall to your use, just as the consecrated breast and the right shoulder shall be yours.

[[numbers-18-19]]
^19^ All the first-fruits of the Sanctuary, which the sons of Israel offer to the Lord, I have given to you and to your sons as well as to your daughters, as a perpetual right. It is an everlasting covenant of salt before the Lord, for you and for your sons.”

[[numbers-18-20]]
^20^ And the Lord said to Aaron: “In their land, you shall possess nothing; neither shall you have a portion among them. I am your portion and your inheritance in the midst of the sons of Israel.

[[numbers-18-21]]
^21^ But I have given, to the sons of Levi, all the tithes of Israel as a possession, for the ministry by which they serve me in the tabernacle of the covenant,

[[numbers-18-22]]
^22^ so that the sons of Israel may no longer approach to the tabernacle, nor commit deadly sin.

[[numbers-18-23]]
^23^ Only the sons of Levi may serve me in the tabernacle and may carry the sins of the people. It shall be an everlasting ordinance in your generations. They shall possess nothing else;

[[numbers-18-24]]
^24^ being content with the oblation of tithes, which I have separated for their uses and necessities.”

[[numbers-18-25]]
^25^ And the Lord spoke to Moses, saying:

[[numbers-18-26]]
^26^ “Instruct the Levites, and also declare to them: When you will receive, from the sons of Israel, the tithes, which I have given to you, offer their first-fruits to the Lord, that is, the tenth part of a tenth,

[[numbers-18-27]]
^27^ so that it may be accounted to you as an oblation of the first-fruits, as much from the threshing floors as from the oil and wine presses.

[[numbers-18-28]]
^28^ And offer the first-fruits of everything, from which you receive tithes, to the Lord, and give them to Aaron the priest.

[[numbers-18-29]]
^29^ Everything which you shall offer from the tithes, and which you shall separate as gifts to the Lord, shall be the finest and most select.

[[numbers-18-30]]
^30^ And you shall say to them: ‘If you offer the noble and the better of the tithes, it shall be accounted to you as if you had given from the first-fruits of the threshing floor and of the oil and wine presses.’

[[numbers-18-31]]
^31^ And you shall eat these in all your places, both you and your families, because it is your price for the ministry, by which you serve in the tabernacle of the testimony.

[[numbers-18-32]]
^32^ And you shall not sin in this way: by reserving the excellent and fat things for yourselves, lest you pollute the oblations of the sons of Israel, and lest you die.”


[[numbers-19]]
== Chapter 19

[[numbers-19-1]]
^1^ And the Lord spoke to Moses and Aaron, saying:

[[numbers-19-2]]
^2^ “This is the ritual that the Lord has appointed for a victim. Instruct the sons of Israel, so that they may bring to you a red cow of full maturity, in which there is no blemish, and which has not carried a yoke.

[[numbers-19-3]]
^3^ And you shall deliver it to Eleazar the priest, who, having led it out beyond the camp, shall immolate it in the sight of all.

[[numbers-19-4]]
^4^ And dipping his finger in its blood, he shall sprinkle it seven times, opposite the door of the tabernacle.

[[numbers-19-5]]
^5^ And he shall burn it, while all are watching, delivering into the flame, not only its skin and flesh, but also the blood and dung.

[[numbers-19-6]]
^6^ Likewise, cedar wood, and hyssop, and twice-dyed scarlet he shall cast into the flame, by which the cow is consumed.

[[numbers-19-7]]
^7^ And then finally, having washed his garments and his body, he shall enter into the camp, and he shall be deeply stained until evening.

[[numbers-19-8]]
^8^ Then he also who had burned it shall wash his garments and his body, and he shall be unclean until evening.

[[numbers-19-9]]
^9^ Then a clean man shall gather the ashes of the cow, and he shall pour them out beyond the camp, in a very pure place, so that they may be preserved for the multitude of the sons of Israel, and for the water of aspersion, because the cow was burned for sin.

[[numbers-19-10]]
^10^ And when he who had carried the ashes of the cow will have washed his garments, he shall be unclean until evening. The sons of Israel, and the newcomers who live among them, shall have this as a holy and perpetual right.

[[numbers-19-11]]
^11^ Whoever touches the corpse of a man, and is, because of this, unclean for seven days,

[[numbers-19-12]]
^12^ shall be sprinkled from this water on the third and seventh days, and so shall he be cleansed. But if he was not sprinkled on the third day, he is not able to be cleansed on the seventh.

[[numbers-19-13]]
^13^ Anyone who will have touched the dead body of a human life, and who has not been sprinkled with this mixture, pollutes the tabernacle of the Lord, and he shall perish out of Israel. For not having been sprinkled with the water of expiation, he shall be unclean, and his filth shall remain upon him.

[[numbers-19-14]]
^14^ This is the law of a man who dies in a tent. All who enter into his tent, and all the vessels which are there, shall be polluted for seven days.

[[numbers-19-15]]
^15^ The vessel that has no cover or binding over it shall be unclean.

[[numbers-19-16]]
^16^ If anyone in the field will have touched the corpse of a man, who was killed or who died on his own, or his bone, or his grave, he shall be unclean for seven days.

[[numbers-19-17]]
^17^ And they shall take some of the ashes from the burning and the sin offering, and they shall pour living waters over them into a vessel.

[[numbers-19-18]]
^18^ And into it a man who is clean shall dip hyssop, and he shall sprinkle from it the entire tent, and all its articles, and the men who were polluted by means of contact.

[[numbers-19-19]]
^19^ And so, in this manner, what is clean shall purify what is unclean, on the third and seventh days. And having been expiated on the seventh day, he shall wash both himself and his garments, and he shall be unclean until evening.

[[numbers-19-20]]
^20^ If anyone has not been expiated by this ritual, his soul shall perish from the midst of the Church. For he has polluted the Sanctuary of the Lord, and he has not been sprinkled with purifying waters.

[[numbers-19-21]]
^21^ This precept shall be an everlasting ordinance. Likewise, the one who has sprinkled the waters shall wash his garments. All who will have touched the waters of expiation shall be unclean until evening.

[[numbers-19-22]]
^22^ Whatever has been touched by something unclean will itself be made unclean. And the soul who touches any of these things shall become unclean until evening.”


[[numbers-20]]
== Chapter 20

[[numbers-20-1]]
^1^ And the sons of Israel, and the entire multitude, went into the desert of Sin, in the first month. And the people stayed at Kadesh. And Miriam died there, and she was buried in the same place.

[[numbers-20-2]]
^2^ And when the people were in need of water, they came together against Moses and Aaron.

[[numbers-20-3]]
^3^ And as it turned into sedition, they said: “If only we had perished among our brothers in the sight of the Lord.

[[numbers-20-4]]
^4^ Why have you led away the Church of the Lord, into the wilderness, so that both we and our cattle would die?

[[numbers-20-5]]
^5^ Why did you cause us to ascend from Egypt, and why have you led us into this most wretched place, which is not able to be sown, which does not produce figs, or vines, or pomegranates, and which, moreover, does not even have water to drink?”

[[numbers-20-6]]
^6^ And Moses and Aaron, dismissing the multitude, entered the tabernacle of the covenant, and they fell prone on the ground, and they cried out to the Lord, and they said: “O Lord God, listen to the outcry of this people, and open for them, from your storehouse, a fountain of living water, so that, being satisfied, their murmuring may cease.” And the glory of the Lord appeared over them.

[[numbers-20-7]]
^7^ And the Lord spoke to Moses, saying:

[[numbers-20-8]]
^8^ “Take the rod, and gather the people, you and your brother Aaron, and speak to the rock before them, and it shall bestow waters. And when you have brought forth water from the rock, the entire multitude and their cattle shall drink.”

[[numbers-20-9]]
^9^ Therefore, Moses took the rod, which was in the sight of the Lord, just as he had instructed him.

[[numbers-20-10]]
^10^ And having gathered the multitude before the rock, he said to them: “Listen, you who are rebellious and unbelieving. Would we be able to cast out water from this rock?”

[[numbers-20-11]]
^11^ And when Moses had lifted up his hand, striking the stone twice with the rod, very great waters went forth, so much so that the people and their cattle were able to drink.

[[numbers-20-12]]
^12^ And the Lord said to Moses and Aaron, “Because you did not believe me, so as to sanctify me before the sons of Israel, you shall not lead this people into the land, which I will give to them.”

[[numbers-20-13]]
^13^ This is the Water of Contradiction, where the sons of Israel were quarreling against the Lord, and he was sanctified in them.

[[numbers-20-14]]
^14^ Meanwhile, Moses sent messengers from Kadesh to the king of Edom. They said: “Your brother Israel says this: You know of all the hardships which have overtaken us,

[[numbers-20-15]]
^15^ how our fathers descended into Egypt, and we lived there for a long time, and the Egyptians afflicted both us and our fathers,

[[numbers-20-16]]
^16^ and how we cried out to the Lord, and he heeded us and sent an Angel, who led us away from Egypt. Behold, we are situated in the city of Kadesh, which is at the extremity of your borders.

[[numbers-20-17]]
^17^ And we beg you to permit us to cross through your land. We will not go through the fields, nor through the vineyards; we will not drink the waters of your wells, but we will travel by the public ways, neither turning aside to the right, nor to the left, until we have passed your borders.”

[[numbers-20-18]]
^18^ Edom responded to them: “You shall not cross through me, otherwise, I will meet you armed.”

[[numbers-20-19]]
^19^ And the sons of Israel said: “We will travel by the well-trodden path. And if we or our cattle drink from your waters, we will give you what is just. There shall be no difficulty in the price, only let us cross through quickly.”

[[numbers-20-20]]
^20^ But he answered, “You shall not cross.” And immediately he went out to meet them with a countless multitude and a strong hand;

[[numbers-20-21]]
^21^ neither was he willing to agree to their petition to concede passage through his borders. For this reason, Israel diverted away from him.

[[numbers-20-22]]
^22^ And when they had moved the camp from Kadesh, they arrived at mount Hor, which is at the borders of the land of Edom,

[[numbers-20-23]]
^23^ where the Lord spoke to Moses:

[[numbers-20-24]]
^24^ “Let Aaron,” he said, “go to his people. For he shall not enter into the land which I have given to the sons of Israel, because he did not believe my mouth at the Waters of Contradiction.

[[numbers-20-25]]
^25^ Take Aaron, and his son with him, and lead them on to mount Hor.

[[numbers-20-26]]
^26^ And when you have stripped the father of his vestments, you shall put them on Eleazar, his son. Aaron shall be gathered and shall die there.”

[[numbers-20-27]]
^27^ Moses did just as the Lord had instructed. And they ascended mount Hor, in the sight of the entire multitude.

[[numbers-20-28]]
^28^ And when he had despoiled Aaron of his vestments, he clothed his son Eleazar with them.

[[numbers-20-29]]
^29^ And when Aaron had died at the top of the mountain, Moses came down with Eleazar.

[[numbers-20-30]]
^30^ And the entire multitude, seeing that Aaron lay dead, wept over him for thirty days, throughout all their families.


[[numbers-21]]
== Chapter 21

[[numbers-21-1]]
^1^ And when king Arad the Canaanite, who was living toward the south, had heard this, namely, that Israel had arrived by the way of spies, he fought against them. And proving to be the victor, he led away prey from them.

[[numbers-21-2]]
^2^ But Israel, obliging himself by a vow to the Lord, said: “If you deliver this people into my hand, I will wipe away their cities.”

[[numbers-21-3]]
^3^ And the Lord heard the prayers of Israel, and he delivered the Canaanite, whom they put to death, overthrowing his cities. And they called the name of that place Hormah, that is, Anathema.

[[numbers-21-4]]
^4^ Then they set out from mount Hor, by the way that leads to the Red Sea, to circle around the land of Edom. And the people began to tire of their journey and hardships.

[[numbers-21-5]]
^5^ And speaking against God and Moses, they said: “Why did you lead us away from Egypt, so as to die in the wilderness? Bread is lacking; there are no waters. Our soul is now nauseous over this very light food.”

[[numbers-21-6]]
^6^ For this reason, the Lord sent fiery serpents among the people, which wounded or killed many of them.

[[numbers-21-7]]
^7^ And so they went to Moses, and they said: “We have sinned, because we have spoken against the Lord and against you. Pray, so that he may take away these serpents from us.” And Moses prayed for the people.

[[numbers-21-8]]
^8^ And the Lord said to him: “Make a bronze serpent, and place it as a sign. Whoever, having been struck, gazes upon it, shall live.”

[[numbers-21-9]]
^9^ Therefore, Moses made a bronze serpent, and he placed it as a sign. When those who had been struck gazed upon it, they were healed.

[[numbers-21-10]]
^10^ And the sons of Israel, setting out, made camp at Oboth.

[[numbers-21-11]]
^11^ Having departed from there, they pitched their tents at Iye-abarim, in the wilderness, which looks out toward Moab, opposite the eastern region.

[[numbers-21-12]]
^12^ And moving from there, they arrived at the Torrent of Zared.

[[numbers-21-13]]
^13^ Having left that place behind, they then made camp opposite Arnon, which is in the desert, and which juts out at the borders of the Amorite. For certainly Arnon is at the limit of Moab, dividing the Moabites and the Amorites.

[[numbers-21-14]]
^14^ About this place, it is said in the book of the wars of the Lord: “As he did at the Red Sea, so will he do at the Torrents of Arnon.”

[[numbers-21-15]]
^15^ The stones of the torrents were bent, so that they might rest in Ar and lie back within the borders of the Moabites.

[[numbers-21-16]]
^16^ Beyond that place appeared a well, about which the Lord said to Moses: “Gather the people together, and I will give them water.”

[[numbers-21-17]]
^17^ Then Israel sang this verse: “Let the well rise up.” They sang:

[[numbers-21-18]]
^18^ “The well, the leaders dug it, and the commanders of the multitude prepared it, at the direction of the lawgiver, and with their staffs.”

[[numbers-21-19]]
^19^ They went from the wilderness to Mattanah, from Mattanah to Nahaliel, from Nahaliel to Bamoth,

[[numbers-21-20]]
^20^ from Bamoth, a valley in the region of Moab, to the top of Pisgah, which looks out opposite the desert.

[[numbers-21-21]]
^21^ Then Israel sent messengers to Sihon, the king of the Amorites, saying:

[[numbers-21-22]]
^22^ “I beg you to permit me to cross through your land. We will not turn aside into the fields or the vineyards. We will not drink waters from the wells. We will travel by the royal way, until we have passed your borders.”

[[numbers-21-23]]
^23^ And he was not willing to allow Israel to cross through his borders. But instead, gathering an army, he went out to meet them in the desert, and he arrived at Jahaz and fought against them.

[[numbers-21-24]]
^24^ And he was struck down by them with the edge of the sword, and they possessed his land from Arnon, even to Jabbok and the sons of Ammon. For the borders of the Ammonites were held by a strong fortress.

[[numbers-21-25]]
^25^ Therefore, Israel took all his cities and lived in the cities of the Amorite, namely, in Heshbon and its villages.

[[numbers-21-26]]
^26^ Heshbon was the city of Sihon, the king of the Amorites, who fought against the king of Moab. And he took all the land, which had been under his sovereignty, as far as Arnon.

[[numbers-21-27]]
^27^ About this, it is said in the proverb: “Enter into Heshbon. Let the city of Sihon be established and built.

[[numbers-21-28]]
^28^ A fire has gone forth from Heshbon, a flame from the town of Sihon, and it has devoured Ar of the Moabites, and the inhabitants of the heights of Arnon.

[[numbers-21-29]]
^29^ Woe to you, Moab! You are perishing, O people of Chemosh. He gave flight to his sons, and he gave the daughters into captivity, to the king of the Amorites, Sihon.

[[numbers-21-30]]
^30^ Their yoke has been scattered from Heshbon even to Dibon. They have passed through, wearily, into Nophah, and as far as Medeba.”

[[numbers-21-31]]
^31^ And so Israel lived in the land of the Amorite.

[[numbers-21-32]]
^32^ And Moses sent some to explore Jazer. These captured its villages and possessed its inhabitants.

[[numbers-21-33]]
^33^ And they turned themselves and ascended, along the way of Bashan. And Og, the king of Bashan, met them with all his people, to fight at Edrei.

[[numbers-21-34]]
^34^ And the Lord said to Moses: “Do not be afraid of him. For I have delivered him, and all his people, as well as his land, into your hand. And you shall do to him just as you did to Sihon, the king of the Amorites, the inhabitant of Heshbon.”

[[numbers-21-35]]
^35^ Therefore, they struck him down also, with his sons, and all his people, even to utter destruction, and they possessed his land.


[[numbers-22]]
== Chapter 22

[[numbers-22-1]]
^1^ And they set out and made camp in the plains of Moab, across the Jordan, where Jericho is situated.

[[numbers-22-2]]
^2^ Then Balak, the son of Zippor, seeing all that Israel had done to the Amorite,

[[numbers-22-3]]
^3^ and that the Moabites had great fear of him, and that they were not able to bear his assault,

[[numbers-22-4]]
^4^ said to those greater by birth of Midian: “So will this people wipe away all those who are dwelling within our borders, in the same way that the ox is accustomed to tear out grass, all the way to the roots.” At that time, he was king of Moab.

[[numbers-22-5]]
^5^ Therefore, he sent messengers to Balaam, the son of Beor, a seer who lived above the river of the land of the sons of Ammon, to call him, and to say: “Behold, a people has gone forth from Egypt, which has covered the face of the earth. They are encamped opposite me.

[[numbers-22-6]]
^6^ Therefore, come and curse this people, for they are stronger than I am. If only, in some way, I might be able to strike them and to drive them from my land. For I know that he whom you bless shall be blessed, and he whom you curse shall be cursed.”

[[numbers-22-7]]
^7^ And the elders of Moab, and those greater by birth of Midian, continued on, holding the price of divination in their hands. And when they had come to Balaam, and had explained to him all the words of Balak,

[[numbers-22-8]]
^8^ he responded, “Remain for this night, and I will answer with whatever the Lord will say to me.” And while they stayed with Balaam, God came and said to him,

[[numbers-22-9]]
^9^ “What do these men want with you?”

[[numbers-22-10]]
^10^ He responded, “Balak, the son of Zippor, the king of the Moabites has sent to me,

[[numbers-22-11]]
^11^ saying: ‘Behold, a people, which has gone forth from Egypt, has covered the face of the earth. Come and curse them, so that, in some way, I may be able to fight them and drive them away.’ ”

[[numbers-22-12]]
^12^ And God said to Balaam, “Do not go with them, and do not curse the people, for they are blessed.”

[[numbers-22-13]]
^13^ And he, rising up in the morning, said to the leaders, “Go into your own land, for the Lord has prohibited me from going with you.”

[[numbers-22-14]]
^14^ Returning, the leaders said to Balak, “Balaam was not willing to come with us.”

[[numbers-22-15]]
^15^ Again, he sent many more persons, and these were more noble than those he had sent before.

[[numbers-22-16]]
^16^ And when these had come to Balaam, they said: “So says Balak, the son of Zippor. Do not hesitate to come to me.

[[numbers-22-17]]
^17^ For I am ready to honor you, and whatever you would want, I shall give to you. Come and curse this people.”

[[numbers-22-18]]
^18^ Balaam responded: “Even if Balak were to give to me his own house, filled with silver and gold, I still would not be able to change the word of the Lord my God, neither to say more, nor to say less.

[[numbers-22-19]]
^19^ I beg you to remain for this night also, so that I may know what the Lord will answer me again.”

[[numbers-22-20]]
^20^ Therefore, God came to Balaam in the night, and said to him: “If these men have arrived to call you, then rise up and go with them; yet only in so far as you shall do what I will command you.”

[[numbers-22-21]]
^21^ Balaam rose up in the morning, and saddling his donkey, he set out with them.

[[numbers-22-22]]
^22^ And God was angry. And an Angel of the Lord stood in the way opposite Balaam, who was sitting on the donkey, and he had two servants with him.

[[numbers-22-23]]
^23^ The donkey, discerning that the Angel was standing in the way with a drawn sword, turned herself from the road and went through a field. And when Balaam beat her and intended to return her to the path,

[[numbers-22-24]]
^24^ the Angel stood in a narrow place between the two walls, with which the vineyards were enclosed.

[[numbers-22-25]]
^25^ And the donkey, seeing this, drew herself close to the wall and scraped the foot of the rider. So he beat her again.

[[numbers-22-26]]
^26^ And, nevertheless, the Angel passing on to a narrow place, where one would not be able to deviate either to the right or to the left, stood to meet him.

[[numbers-22-27]]
^27^ And when the donkey had seen the Angel standing there, she fell under the feet of the rider, who, being angry, struck her sides more vehemently with a club.

[[numbers-22-28]]
^28^ And the Lord opened the mouth of the donkey, and she said: “What have I done to you? Why do strike you me, behold now, for the third time?”

[[numbers-22-29]]
^29^ Balaam responded, “Because you have deserved it, and you have mistreated me. If only I had a sword, so that I might pierce you.”

[[numbers-22-30]]
^30^ The donkey said: “Am not I your animal, on which you have always been accustomed to sit, even until this present day? Tell me, when did I ever do the same thing to you.” But he said, “Never.”

[[numbers-22-31]]
^31^ Immediately, the Lord opened the eyes of Balaam, and he saw the Angel standing in the way with a drawn sword, and he reverenced him prone on the ground.

[[numbers-22-32]]
^32^ And the Angel said to him: “Why did you beat your donkey three times? I have come to be an adversary to you, because your way is perverse and contrary to me.

[[numbers-22-33]]
^33^ And unless the donkey had turned aside from the way, allowing a place for my opposition, I would have killed you, and she would have lived.”

[[numbers-22-34]]
^34^ Balaam said: “I have sinned, not knowing that you stood against me. And now, if it displeases you for me to continue on, I will return.”

[[numbers-22-35]]
^35^ The Angel said, “Go with them, but be careful not to speak anything other than what I shall instruct you.” And so, he went with the leaders.

[[numbers-22-36]]
^36^ And when Balak had heard it, he went out to meet him in a town of the Moabites, which is situated at the furthest borders of Arnon.

[[numbers-22-37]]
^37^ And he said to Balaam: “I sent messengers to call you. Why did you not come to me immediately? Was it because I am not able to pay the cost for your arrival?”

[[numbers-22-38]]
^38^ He answered him: “Behold, here I am. Am I able to speak anything other than what God will put into my mouth?”

[[numbers-22-39]]
^39^ Therefore, they continued on together, and they arrived at a city, which was at the furthest borders of his kingdom.

[[numbers-22-40]]
^40^ And after Balak had killed oxen and sheep, he sent the gifts to Balaam, and to the leaders who were with him.

[[numbers-22-41]]
^41^ Then, when morning arrived, he led him to the heights of Baal, and he gazed upon the most distant portions of the population.


[[numbers-23]]
== Chapter 23

[[numbers-23-1]]
^1^ And Balaam said to Balak, “Build seven altars here for me, and prepare as many calves, and the same number of rams.”

[[numbers-23-2]]
^2^ And when he had acted according to the words of Balaam, they placed a calf and a ram together on each altar.

[[numbers-23-3]]
^3^ And Balaam said to Balak: “Stand for a little while next to your holocaust, until I go, to see if perhaps the Lord will meet with me. And whatever he will command, I shall speak to you.”

[[numbers-23-4]]
^4^ And after he had quickly departed, God met with him. And Balaam, speaking to him, said: “I have set up seven altars, and I have placed a calf and a ram on each.”

[[numbers-23-5]]
^5^ Then the Lord placed the word in his mouth, and he said: “Return to Balak, and you shall say this.”

[[numbers-23-6]]
^6^ Returning, he found Balak standing next to his holocaust, with all the leaders of the Moabites.

[[numbers-23-7]]
^7^ And taking up his parable, he said: “Balak, king of the Moabites, has led me from Aram, from the mountains of the east. ‘Come forth,’ he said, ‘and curse Jacob. Hurry and condemn Israel.’

[[numbers-23-8]]
^8^ How shall I curse him, whom God has not cursed? For what reason would I condemn him, whom the Lord does not condemn?

[[numbers-23-9]]
^9^ I will look upon him from the tops of the stones, and I will consider him from the hills. This people shall dwell alone, and they shall not be counted among the nations.

[[numbers-23-10]]
^10^ Who can number the dust that is Jacob, and who can know the number of the stock of Israel? May my soul die a just death, and may my end be like theirs.”

[[numbers-23-11]]
^11^ And Balak said to Balaam: “What is this that you are doing? I called for you, in order to curse my enemies, and to the contrary, you bless them.”

[[numbers-23-12]]
^12^ He answered him, “How can I say anything other than what the Lord orders?”

[[numbers-23-13]]
^13^ Therefore, Balak said: “Come with me to another place, from where you may see a portion of Israel, though you cannot see them all. Curse them from there.”

[[numbers-23-14]]
^14^ And when he had led him to a lofty place, on the top of mount Pisgah, Balaam built seven altars, and placing upon each a calf and a ram,

[[numbers-23-15]]
^15^ he said to Balak, “Stand here next to your holocaust, while I continue on to meet him.”

[[numbers-23-16]]
^16^ And when the Lord had met him, and had put the word in his mouth, he said, “Return to Balak, and you shall say this to him.”

[[numbers-23-17]]
^17^ Returning, he found him standing next to his holocaust, and the leaders of the Moabites were with him. And Balak said to him, “What has the Lord spoken?”

[[numbers-23-18]]
^18^ But, taking up his parable, he said: “Stand, Balak, and pay attention. Listen, you son of Zippor.

[[numbers-23-19]]
^19^ God is not like a man, so that he would lie, nor is he like a son of man, so that he would be changed. Therefore, having spoken, will he not act? Has he ever spoken, and not fulfilled?

[[numbers-23-20]]
^20^ I was led here to bless, and I have no strength to hinder the blessing.

[[numbers-23-21]]
^21^ There is no idol in Jacob; neither is there a false image to be seen in Israel. The Lord his God is with him, and the resound of royal victory is in him.

[[numbers-23-22]]
^22^ God has led him away from Egypt; his strength is like that of the rhinoceros.

[[numbers-23-23]]
^23^ There is no soothsaying in Jacob, nor any divination in Israel. In their times, it shall be told to Jacob and to Israel what God has wrought.

[[numbers-23-24]]
^24^ Behold, the people will rise up like a lioness, and lie down like a lion. But they will not lie down until they devour the prey and drink the blood of the slain.”

[[numbers-23-25]]
^25^ And Balak said to Balaam, “Neither curse him, nor bless him.”

[[numbers-23-26]]
^26^ And he said, “Have I not told you that whatever God would command of me, I would do?”

[[numbers-23-27]]
^27^ And Balak said to him: “Come and I will lead you to another place. If perhaps it may please God, then you may curse them from there.”

[[numbers-23-28]]
^28^ And when he had led him on to the top of mount Peor, which looks out toward the wilderness,

[[numbers-23-29]]
^29^ Balaam said to him, “Build seven altars here for me, and prepare as many calves, and the same number of rams.”

[[numbers-23-30]]
^30^ Balak did as Balaam had said, and he placed on each altar a calf and a ram.


[[numbers-24]]
== Chapter 24

[[numbers-24-1]]
^1^ And when Balaam had seen that it was pleasing to the Lord that he should bless Israel, he by no means went out as he had gone before, to seek divination. But directing his face opposite the desert,

[[numbers-24-2]]
^2^ and lifting up his eyes, he saw Israel dwelling in tents by their tribes. And with the Spirit of God rushing into him,

[[numbers-24-3]]
^3^ taking up his parable, he said: “Balaam, the son of Beor, the man whose eye has been obstructed,

[[numbers-24-4]]
^4^ the hearer of the sermon of God, he who has gazed upon a vision of the Almighty, he who falls down and so his eyes are opened, has declared:

[[numbers-24-5]]
^5^ ‘How beautiful are your tabernacles, O Jacob, and your tents, O Israel!

[[numbers-24-6]]
^6^ They are like forested valleys, like gardens irrigated next to rivers, like tabernacles which the Lord has fixed, like cedars close to waters.

[[numbers-24-7]]
^7^ Water shall flow from his jar, and his offspring shall be amid many waters, because Agag, his king, shall be taken, and his kingdom shall be removed.

[[numbers-24-8]]
^8^ Away from Egypt, God has led him, whose strength is like the rhinoceros. They shall devour the nations that are his enemies, and break their bones, and pierce them with arrows.

[[numbers-24-9]]
^9^ Lying down, he has slept like a lion, and like a lioness, whom no one would dare to awaken. He who blesses you, shall himself also be blessed. He who curses you, shall be considered cursed.”

[[numbers-24-10]]
^10^ And Balak, being angry against Balaam, clapped his hands together and said: “I called you to curse my enemies, and, to the contrary, you have blessed them three times.

[[numbers-24-11]]
^11^ Return to your place. I had decided, indeed, to honor you greatly, but the Lord has deprived you of the designated honor.”

[[numbers-24-12]]
^12^ Balaam responded to Balak: “Did I not say to your messengers, whom you sent to me:

[[numbers-24-13]]
^13^ Even if Balak would give me his house, filled with silver and gold, I still could not go away from the word of the Lord my God, so as to offer anything, either good or evil, from my own heart; but whatever the Lord will speak, this, too, I shall speak.

[[numbers-24-14]]
^14^ Yet truly, as I continue on to my own people, I will give you counsel as to what this people shall do to your people in the end times.”

[[numbers-24-15]]
^15^ Therefore, taking up his parable, he again spoke: “Balaam the son of Beor, the man whose eye has been obstructed,

[[numbers-24-16]]
^16^ the hearer of the sermon of God, he who knows the doctrine of the Most High, and who sees the visions of the Almighty, who, falling down, has his eyes opened, has declared:

[[numbers-24-17]]
^17^ I shall see him, but not presently. I shall gaze upon him, but not soon. A star shall rise out of Jacob, and a rod shall spring up from Israel. And he shall strike down the commanders of Moab, and he shall devastate all the sons of Seth.

[[numbers-24-18]]
^18^ And he shall possess Idumea; the inheritance of Seir shall fall to their enemies. Yet truly, Israel shall act with strength.

[[numbers-24-19]]
^19^ From Jacob will be he who shall be ruler. And he shall perish the remnants of the city.”

[[numbers-24-20]]
^20^ And when he saw Amalek, taking up his parable, he said: “Amalek, first among the Gentiles, whose very end shall be perdition.”

[[numbers-24-21]]
^21^ Likewise, he saw the Kainites, and taking up his parable, he said: “Robust, indeed, is your habitation. But though you will set your nest in a rock,

[[numbers-24-22]]
^22^ and you will be elect among the stock of Kain, how long will you be able to remain? For Assur shall take you captive.”

[[numbers-24-23]]
^23^ And taking up his parable once more he said: “Alas! Who will be able to survive, when God will do these things?

[[numbers-24-24]]
^24^ They shall arrive in Greek warships from Italy. They shall overcome the Assyrians, and they shall devastate the Hebrews, and yet, at the very end, even they themselves shall perish.”

[[numbers-24-25]]
^25^ And Balaam rose up, and he returned to his place. Likewise, Balak went back, along the way by which he had arrived.


[[numbers-25]]
== Chapter 25

[[numbers-25-1]]
^1^ Now Israel, at that time, dwelt in Shittim, and the people were fornicating with the daughters of Moab,

[[numbers-25-2]]
^2^ who called them to their sacrifices. And they ate, and they adored their gods.

[[numbers-25-3]]
^3^ And Israel was initiated into Baal of Peor. And so the Lord, being angry,

[[numbers-25-4]]
^4^ said to Moses, “Take all the leaders of the people, and hang them on gallows against the sun, so that my fury may be averted from Israel.”

[[numbers-25-5]]
^5^ And Moses said to the judges of Israel, “Let each one kill his neighbors, who have been initiated into Baal of Peor.”

[[numbers-25-6]]
^6^ And behold, one of the sons of Israel entered, in the sight of his brothers, to a prostitute of Midian, within view of Moses and of all the crowd of the sons of Israel, who were weeping before the door of the tabernacle.

[[numbers-25-7]]
^7^ And when Phinehas the son of Eleazar, the son of Aaron the priest, had seen it, he rose up from the midst of the multitude, and, seizing a dagger,

[[numbers-25-8]]
^8^ he entered after the Israelite man, into the brothel, and he pierced both of them at the same time, specifically, the man and the woman at the location of their genitals. And the scourge ceased from among the sons of Israel.

[[numbers-25-9]]
^9^ And there were slain twenty-four thousand men.

[[numbers-25-10]]
^10^ And the Lord said to Moses:

[[numbers-25-11]]
^11^ “Phinehas the son of Eleazar, the son of Aaron the priest, has averted my wrath from the sons of Israel. For he was moved against them by my zeal, so that I myself, in my zeal, might not wipe away the sons of Israel.

[[numbers-25-12]]
^12^ Because of this, say to him: Behold, I give to him the peace of my covenant.

[[numbers-25-13]]
^13^ And the covenant of the everlasting priesthood shall be as much for him as for his offspring. For he was zealous on behalf of his God, and he has made expiation for the wickedness of the sons of Israel.”

[[numbers-25-14]]
^14^ Now the name of the Israelite man, who was killed with the Midianite woman, was Zimri the son of Salu, a leader from the kinship and tribe of Simeon.

[[numbers-25-15]]
^15^ Moreover, the Midianite woman, who was put to death together with him, was called Cozbi the daughter of Zur, a most noble leader among the Midianites.

[[numbers-25-16]]
^16^ And the Lord spoke to Moses, saying:

[[numbers-25-17]]
^17^ “Let the Midianites perceive you as enemies, and strike them down,

[[numbers-25-18]]
^18^ for they, too, have behaved with hostility against you, and they have deceived you insidiously by means of the idol Peor, and by Cozbi, the daughter of a commander of Midian, their sister, who was struck down in the day of the scourge because of the sacrilege of Peor.”


[[numbers-26]]
== Chapter 26

[[numbers-26-1]]
^1^ After the blood of the guilty was shed, the Lord said to Moses, and to Eleazar the son of Aaron the priest:

[[numbers-26-2]]
^2^ “Number the entire sum of the sons of Israel, from twenty years and above, by their houses and kinships, all who are able to go forth to war.”

[[numbers-26-3]]
^3^ And so, Moses and Eleazar the priest, who were in the plains of Moab, above the Jordan, opposite Jericho, spoke to those who were

[[numbers-26-4]]
^4^ from twenty years and above, just as the Lord had commanded. And this is their number:

[[numbers-26-5]]
^5^ Ruben, the firstborn of Israel; his son, Hanoch, from whom is the family of the Hanochites; and Pallu, from whom is the family of the Palluites;

[[numbers-26-6]]
^6^ and Hezron, from whom is the family of the Hezronites; and Carmi, from whom is the family of the Carmites.

[[numbers-26-7]]
^7^ These are the families of the stock of Ruben, whose number was found to be forty-three thousand and seven hundred thirty.

[[numbers-26-8]]
^8^ The son of Phallu: Eliab;

[[numbers-26-9]]
^9^ his sons, Nemuel and Dathan and Abiram. These are Dathan and Abiram, the leaders of the people, who rose up against Moses and Aaron in the sedition at Korah, when they rebelled against the Lord.

[[numbers-26-10]]
^10^ And the earth, opening its mouth, devoured Korah, with many others dying, when the fire burned two hundred fifty men. And a great miracle was wrought,

[[numbers-26-11]]
^11^ so that, when Korah perished, his sons did not perish.

[[numbers-26-12]]
^12^ The sons of Simeon, by their kinships: Nemuel, from him is the family of the Nemuelites; Jamin, from him is the family of the Jaminites; Jachin, from him is the family of the Jachinites;

[[numbers-26-13]]
^13^ Sohar, from him is the family of the Soharites; Shaul, from him is the family of the Shaulites.

[[numbers-26-14]]
^14^ These are the families of the stock of Simeon, whose entire number was twenty-two thousand two hundred.

[[numbers-26-15]]
^15^ The sons of Gad, by their kinships: Zephon, from him is the family of the Zephonites; Haggi, from him is the family of the Haggites; Shuni, from him is the family of the Shunites;

[[numbers-26-16]]
^16^ Ozni, from him is the family of the Oznites; Eri, from him is the family of the Erites;

[[numbers-26-17]]
^17^ Arod, from him is the family of the Arodites; Areli, from him is the family of the Arelites.

[[numbers-26-18]]
^18^ These are the families of Gad, whose entire number was forty thousand five hundred.

[[numbers-26-19]]
^19^ The sons of Judah: Er and Onan, who both died in the land of Canaan.

[[numbers-26-20]]
^20^ And these were the sons of Judah, by their kinships: Shelah, from whom is the family of the Shelahites; Perez, from whom is the family of the Perezites; Zerah, from whom is the family of the Zerahites.

[[numbers-26-21]]
^21^ Moreover, the sons of Phares were: Hezron, from whom is the family of the Hezronites; and Hamul, from whom is the family of the Hamulites.

[[numbers-26-22]]
^22^ These are the families of Judah, whose entire number was seventy-six thousand five hundred.

[[numbers-26-23]]
^23^ The sons of Issachar, by their kinships: Tola from whom is the family of the Tolaites; Puvah, from whom is the family of the Puvahites;

[[numbers-26-24]]
^24^ Jashub, from whom is the family of the Jashubites; Shimron, from whom is the family of the Shimronites.

[[numbers-26-25]]
^25^ These are the kinships of Issachar, whose number was sixty-four thousand three hundred.

[[numbers-26-26]]
^26^ The sons of Zebulon by their kinships: Sered, from whom is the family of the Seredites; Elon, from whom is the family of the Elonites; Jahleel, from whom is the family of the Jahleelites.

[[numbers-26-27]]
^27^ These are the kinships of Zebulun, whose number was sixty thousand five hundred.

[[numbers-26-28]]
^28^ The sons of Joseph by their kinships: Manasseh and Ephraim.

[[numbers-26-29]]
^29^ From Manasseh was born Machir, from whom is the family of the Machirites. Machir conceived Gilead, from whom is the family of the Gileadites.

[[numbers-26-30]]
^30^ Gilead had sons: Jezer, from whom is the family of the Jezerites; and Helek, from whom is the family of the Helekites;

[[numbers-26-31]]
^31^ and Asriel, from whom is the family of the Asrielites; and Shechem, from whom is the family of the Shechemites;

[[numbers-26-32]]
^32^ and Shemida, from whom is the family of the Shemidaites; and Hepher, from whom is the family of the Hepherites.

[[numbers-26-33]]
^33^ Now Hepher was the father of Zelophehad, who had no sons, but only daughters, whose names are these: Mahlah, and Noa, and Hoglah, and Milcah, and Tirzah.

[[numbers-26-34]]
^34^ These are the families of Manasseh, and their number was fifty-two thousand seven hundred.

[[numbers-26-35]]
^35^ Now the sons of Ephraim by their kinships were these: Shuthelah, from whom is the family of the Shuthelahites; Becher, from whom is the family of the Becherites; Tahan, from whom is the family of the Tahanites.

[[numbers-26-36]]
^36^ Furthermore, the son of Shuthelah was Eran, from whom is the family of the Eranites.

[[numbers-26-37]]
^37^ These are the kinships of the sons of Ephraim, whose number was thirty-two thousand five hundred.

[[numbers-26-38]]
^38^ These are the sons of Joseph by their families: the sons of Benjamin in their kinships: Bela, from whom is the family of the Belaites; Ashbel, from whom is the family of the Ashbelites; Ahiram, from whom is the family of the Ahiramites;

[[numbers-26-39]]
^39^ Shupham, from whom is the family of the Shuphamites; Hupham, from whom is the family of the Huphamites.

[[numbers-26-40]]
^40^ The sons of Bela: Arad and Naaman. From Arad, the family of the Aradites; from Naaman, the family of the Naamanites.

[[numbers-26-41]]
^41^ These are the sons of Benjamin by their kinships, whose number was forty-five thousand six hundred.

[[numbers-26-42]]
^42^ The sons of Dan by their kinships: Shuham, from whom is the family of the Shuhamites. These are the kinships of Dan by their families.

[[numbers-26-43]]
^43^ All these were Shuhamites, whose number was sixty-four thousand four hundred.

[[numbers-26-44]]
^44^ The sons of Asher by their kinships: Imnah, from whom is the family of the Imnahites; Ishvi, from whom is the family of the Ishvites; Beriah, from whom is the family of the Beriahites.

[[numbers-26-45]]
^45^ The sons of Beriah: Heber, from whom is the family of the Heberites; and Malchiel, from whom is the family of the Malchielites.

[[numbers-26-46]]
^46^ Now the name of the daughter of Asher was Serah.

[[numbers-26-47]]
^47^ These are the kinships of the sons of Asher, and their number was fifty-three thousand four hundred.

[[numbers-26-48]]
^48^ The sons of Naphtali by their kinships: Jahzeel, from whom is the family of the Jahzeelites; Guni, from whom is the family of the Gunites;

[[numbers-26-49]]
^49^ Jezer, from whom is the family of the Jezerites; Shillem, from whom is the family of the Shillemites.

[[numbers-26-50]]
^50^ These are the kinships of the sons of Naphtali by their families, whose number was forty-five thousand four hundred.

[[numbers-26-51]]
^51^ This is the sum of the sons of Israel, who were counted: six hundred thousand and one thousand seven hundred thirty.

[[numbers-26-52]]
^52^ And the Lord spoke to Moses, saying:

[[numbers-26-53]]
^53^ “The land shall be divided to these, as their possessions, according to the number of their names.

[[numbers-26-54]]
^54^ To the greater number you shall give a greater portion, and to the lesser number, a lesser portion. To each one, just as they have now been counted, a possession shall be delivered.

[[numbers-26-55]]
^55^ Yet only in so far as the land is divided by lot to a tribe and to families.

[[numbers-26-56]]
^56^ Whatever the lot will happen to be, it shall be accepted, either by the greater, or by the lesser.

[[numbers-26-57]]
^57^ Likewise, this is the number of the sons of Levi by their families: Gershon, from whom is the family of the Gershonites; Kohath, from whom is the family of the Kohathites; Merari, from whom is the family of the Merarites.

[[numbers-26-58]]
^58^ These are the families of Levi: The family of Libni, the family of Hebroni, the family of Mahli, the family of Mushi, the family of Korah. Yet truly, Kohath conceived Amram,

[[numbers-26-59]]
^59^ who had a wife, Jochebed, the daughter of Levi, who was born to him in Egypt. She bore, to her husband Amram: sons, Aaron and Moses, as well as their sister, Miriam.

[[numbers-26-60]]
^60^ From Aaron were born Nadab and Abihu, and Eleazar and Ithamar.

[[numbers-26-61]]
^61^ Of these, Nadab and Abihu died, when they had offered strange fire before the Lord.

[[numbers-26-62]]
^62^ And these were all who were numbered: twenty-three thousand of the male gender, from one month and above. For they were not counted among the sons of Israel, neither was a possession given to them with the others.

[[numbers-26-63]]
^63^ This is the number of the sons of Israel, who were enrolled by Moses and by Eleazar the priest, in the plains of Moab, above the Jordan, opposite Jericho.

[[numbers-26-64]]
^64^ Among these, not one of them was numbered before, by Moses and Aaron in the desert of Sinai.

[[numbers-26-65]]
^65^ For the Lord had foretold that all would die in the wilderness. And not one of them remained, except Caleb the son of Jephunneh, and Joshua the son of Nun.


[[numbers-27]]
== Chapter 27

[[numbers-27-1]]
^1^ Then there approached the daughters of Zelophehad, the son of Hepher, the son of Gilead, the son of Machir, the son of Manasseh, who was the son of Joseph: and their names are Mahlah, and Noa, and Hoglah, and Milcah, and Tirzah.

[[numbers-27-2]]
^2^ And they stood before Moses and Eleazar the priest, and all the leaders of the people, at the door of the tabernacle of the covenant, and they said:

[[numbers-27-3]]
^3^ “Our father died in the desert, and was not with the sedition, which was stirred up against the Lord under Korah, but he died in his own sin; he had no male sons. Why is his name taken away from his family, because he had no son? Give us a possession among the kinsmen of our father.”

[[numbers-27-4]]
^4^ And Moses referred their case to the judgment of the Lord.

[[numbers-27-5]]
^5^ And the Lord said to him:

[[numbers-27-6]]
^6^ “The daughters of Zelophehad are asking for something just. So give them a possession among the kinsmen of their father, and let them succeed him in his inheritance.

[[numbers-27-7]]
^7^ And to the sons of Israel, you shall speak these things:

[[numbers-27-8]]
^8^ When a man dies without a son, his inheritance shall be transferred to his daughter.

[[numbers-27-9]]
^9^ If he has no daughter, his brothers shall succeed him.

[[numbers-27-10]]
^10^ But if there were also no brothers, you shall give the inheritance to the brothers of his father.

[[numbers-27-11]]
^11^ But if he has no paternal uncles, the inheritance shall be given to those who are closest to him. And this shall be, for the sons of Israel, consecrated as a perpetual law, just as the Lord has instructed Moses.”

[[numbers-27-12]]
^12^ The Lord also said to Moses: “Ascend onto this mountain, Abarim, and contemplate from there the land, which I will give to the sons of Israel.

[[numbers-27-13]]
^13^ And when you have seen it, you shall then go to your people, just as your brother Aaron went.

[[numbers-27-14]]
^14^ For you offended me in the desert of Sin at the Contradiction of the multitude; neither were you willing to sanctify me in their sight over the waters. These are the Waters of Contradiction at Kadesh in the desert of Sin.”

[[numbers-27-15]]
^15^ Moses answered him:

[[numbers-27-16]]
^16^ “May the Lord, the God of the spirits of all flesh, provide a man, who may be over this multitude,

[[numbers-27-17]]
^17^ and who may be able to exit and enter before them, and who may lead them out or lead them in: lest the people of the Lord be like sheep without a shepherd.”

[[numbers-27-18]]
^18^ And the Lord said to him: “Take Joshua, the son of Nun, a man in whom the Spirit is, and place your hand upon him.

[[numbers-27-19]]
^19^ And he shall stand before Eleazar the priest and the entire multitude.

[[numbers-27-20]]
^20^ And you shall give him the precepts in the sight of all, and a portion of your glory, so that the entire congregation of the sons of Israel may listen to him.

[[numbers-27-21]]
^21^ On his behalf, if anything is to be done, Eleazar the priest shall consult the Lord. He, and all the sons of Israel with him, and the rest of the multitude, shall go out and enter in at his word.”

[[numbers-27-22]]
^22^ Moses did just as the Lord had instructed. And when he had brought Joshua, he set him before Eleazar the priest, and before the entire gathering of the people.

[[numbers-27-23]]
^23^ And imposing his hands upon his head, he repeated all that the Lord had commanded.


[[numbers-28]]
== Chapter 28

[[numbers-28-1]]
^1^ The Lord also said to Moses:

[[numbers-28-2]]
^2^ “Instruct the sons of Israel, and you shall say to them: Offer my oblation and bread, and the incense of most sweet odor, at their proper times.

[[numbers-28-3]]
^3^ These are the sacrifices which you must offer: Two immaculate one-year-old lambs each day as a perpetual holocaust.

[[numbers-28-4]]
^4^ You shall offer one in morning, and the other in the evening,

[[numbers-28-5]]
^5^ and the tenth part of an ephah of fine wheat flour, which has been sprinkled with the purest oil, and which has the measure of the fourth part of a hin.

[[numbers-28-6]]
^6^ It is the continual holocaust which you offered at mount Sinai as a most sweet odor of incense to the Lord.

[[numbers-28-7]]
^7^ And you shall offer a libation of wine, of the fourth part of a hin for each lamb, in the Sanctuary of the Lord.

[[numbers-28-8]]
^8^ And you shall offer the other lamb similarly, in the evening, according to all the rites of the morning sacrifice and its libations, as an oblation of most sweet odor to the Lord.

[[numbers-28-9]]
^9^ Then, on the Sabbath day, you shall offer two immaculate one-year-old lambs, and two tenths of fine wheat flour sprinkled with oil, as sacrifice, as well as the libations

[[numbers-28-10]]
^10^ that are usually poured out on each Sabbath as a perpetual holocaust.

[[numbers-28-11]]
^11^ Then, on the first day of the month, you shall offer a holocaust to the Lord: two calves from the herd, one ram, seven immaculate one-year-old lambs,

[[numbers-28-12]]
^12^ and three tenths of fine wheat flour sprinkled with oil, as sacrifice, for each calf, and two tenths of fine wheat flour sprinkled with oil, for each ram,

[[numbers-28-13]]
^13^ and one tenth of fine wheat flour with oil, as a sacrifice, for each lamb. It is a holocaust of most sweet odor and also an incense to the Lord.

[[numbers-28-14]]
^14^ Now these shall be the libations of wine, which are to be poured out for each victim: one half portion of a hin for each calf, one third for a ram, and one fourth for a lamb. This shall be the holocaust for all the months, as they succeed one another in the turning of the year.

[[numbers-28-15]]
^15^ Likewise, a he-goat shall be offered to the Lord for sin, with the perpetual holocaust and its libations.

[[numbers-28-16]]
^16^ Then, in the first month, the fourteenth day of the month shall be the Passover of the Lord.

[[numbers-28-17]]
^17^ And the fifteenth day shall be a solemnity. For seven days, they shall eat unleavened bread.

[[numbers-28-18]]
^18^ And the first day of these days shall be venerable and holy; you shall not do any servile work in it.

[[numbers-28-19]]
^19^ And you shall offer the incense of a holocaust to the Lord, two calves from the herd, one ram, seven immaculate one-year-old lambs;

[[numbers-28-20]]
^20^ and with each sacrifice, from fine wheat flour which has been sprinkled with oil, three tenths for each calf, and two tenths for each ram,

[[numbers-28-21]]
^21^ and one tenth for each lamb, that is, for the seven lambs;

[[numbers-28-22]]
^22^ and one he-goat for sin, as an expiation for you,

[[numbers-28-23]]
^23^ aside from the morning holocaust, which you shall always offer.

[[numbers-28-24]]
^24^ You shall do this on each day of the seven days, as fuel for the fire, and as a most sweet odor to the Lord, which shall rise up from the holocaust and from each of the libations.

[[numbers-28-25]]
^25^ Likewise, the seventh day shall be very honored and holy for you. Any servile work, you shall not do in it.

[[numbers-28-26]]
^26^ And also the day of the first-fruits, after the weeks have been fulfilled, when you shall offer new fruits to the Lord, shall be venerable and holy. You shall not do any servile work in it.

[[numbers-28-27]]
^27^ And you shall offer a holocaust as a most sweet odor to the Lord: two calves from the herd, one ram, and seven immaculate one-year-old lambs,

[[numbers-28-28]]
^28^ and also, as their sacrifices, fine wheat flour sprinkled with oil, three tenths for each calf, two for each ram,

[[numbers-28-29]]
^29^ one tenth for each lamb, which all together are seven lambs; likewise, a he-goat,

[[numbers-28-30]]
^30^ which is slain for expiation, aside from the perpetual holocaust and its libations.

[[numbers-28-31]]
^31^ You shall offer only what is immaculate, with their libations.”


[[numbers-29]]
== Chapter 29

[[numbers-29-1]]
^1^ “Now the first day of the seventh month also shall be venerable and holy to you. In it, you shall not do any servile work, because it is the day of the sounding of the trumpets.

[[numbers-29-2]]
^2^ And you shall offer a holocaust, as a most sweet odor to the Lord: one calf from the herd, one ram, and seven immaculate one-year-old lambs;

[[numbers-29-3]]
^3^ and, as their sacrifices, fine wheat flour sprinkled with oil: three tenths for each calf, two tenths for a ram,

[[numbers-29-4]]
^4^ one tenth for a lamb, which all together are seven lambs;

[[numbers-29-5]]
^5^ and a he-goat for sin, which is offered as an expiation for the people,

[[numbers-29-6]]
^6^ aside from the holocaust of the first day of the month with its sacrifices, and the perpetual holocaust with the usual libations. By these same ceremonies, you shall offer incense as a most sweet odor to the Lord.

[[numbers-29-7]]
^7^ Likewise, the tenth day of this seventh month shall be for you holy and venerable, and you shall afflict your souls. You shall do no servile work in it.

[[numbers-29-8]]
^8^ And you shall offer a holocaust to the Lord, as a most sweet odor: one calf from the herd, one ram, seven immaculate one-year-old lambs;

[[numbers-29-9]]
^9^ and for their sacrifices, fine wheat flour sprinkled with oil: three tenths for each calf, two tenths for a ram,

[[numbers-29-10]]
^10^ one tenth for each lamb, which are all together seven lambs;

[[numbers-29-11]]
^11^ and a he-goat for sin, apart from those things which are usually offered for offenses as an expiation, and as a perpetual holocaust, with their sacrifice and libations.

[[numbers-29-12]]
^12^ Yet truly, on the fifteenth day of the seventh month, which shall be for you holy and venerable, you shall not do any servile work in it, but you shall celebrate a solemnity to the Lord for seven days.

[[numbers-29-13]]
^13^ And you shall offer a holocaust, as a most sweet odor to the Lord: thirteen calves from the herd, two rams, fourteen immaculate one-year-old lambs;

[[numbers-29-14]]
^14^ and as their libations, fine wheat flour sprinkled with oil: three tenths for each calf, which is all together thirteen calves, and two tenths for each ram, that is, all together two rams,

[[numbers-29-15]]
^15^ and one tenth for each lamb, which is all together fourteen lambs;

[[numbers-29-16]]
^16^ and a he-goat for sin, apart from the perpetual holocaust, and the sacrifice and its libation.

[[numbers-29-17]]
^17^ On the next day, you shall offer twelve calves from the herd, two rams, and fourteen immaculate one-year-old lambs.

[[numbers-29-18]]
^18^ And the sacrifices and libations for each of the calves and the rams and the lambs, you shall celebrate according to the rite,

[[numbers-29-19]]
^19^ with a he-goat for sin, apart from the perpetual holocaust, and the sacrifice and its libation.

[[numbers-29-20]]
^20^ On the third day, you shall offer eleven calves, two rams, and fourteen immaculate one-year-old lambs.

[[numbers-29-21]]
^21^ And the sacrifices and libations for each of the calves and the rams and the lambs, you shall celebrate according to the rite,

[[numbers-29-22]]
^22^ with a he-goat for sin, apart from the perpetual holocaust, and the sacrifice and its libation.

[[numbers-29-23]]
^23^ On the fourth day, you shall offer ten calves, two rams, and fourteen immaculate one-year-old lambs.

[[numbers-29-24]]
^24^ And the sacrifices and the libations for each of the calves and the rams and the lambs, you shall celebrate according to the rite,

[[numbers-29-25]]
^25^ with a he-goat for sin, apart from the perpetual holocaust, and its sacrifice and libation.

[[numbers-29-26]]
^26^ On the fifth day, you shall offer nine calves, two rams, and fourteen immaculate one-year-old lambs.

[[numbers-29-27]]
^27^ And the sacrifices and libations for each of the calves and the rams and the lambs, you shall celebrate according to the rite,

[[numbers-29-28]]
^28^ with a he-goat for sin, apart from the perpetual holocaust, and its sacrifice and libation.

[[numbers-29-29]]
^29^ On the sixth day, you shall offer eight calves, two rams, and fourteen immaculate one-year-old lambs.

[[numbers-29-30]]
^30^ And the sacrifices and libations for each of the calves and the rams and the lambs, you shall celebrate according to the rite,

[[numbers-29-31]]
^31^ with a he-goat for sin, apart from the perpetual holocaust, and its sacrifice and libation.

[[numbers-29-32]]
^32^ On the seventh day, you shall offer seven calves, and two rams, and fourteen immaculate one-year-old lambs.

[[numbers-29-33]]
^33^ And the sacrifices and libations for each of the calves and the rams and the lambs, you shall celebrate according to the rite,

[[numbers-29-34]]
^34^ with a he-goat for sin, apart from the perpetual holocaust, and its sacrifice and libation.

[[numbers-29-35]]
^35^ On the eighth day, which is most honored, you shall not do any servile work,

[[numbers-29-36]]
^36^ offering a holocaust as a most sweet odor to the Lord: one calf, one ram, and seven immaculate one-year-old lambs.

[[numbers-29-37]]
^37^ And the sacrifices and libations for each of the calves and the rams and the lambs, you shall celebrate according to the rite,

[[numbers-29-38]]
^38^ with a he-goat for sin, apart from the perpetual holocaust, and its sacrifice and libation.

[[numbers-29-39]]
^39^ These things you shall offer to the Lord in your solemnities, aside from the vowed and voluntary oblations, as a holocaust, as a sacrifice, as a libation, or as peace-offering victims.”


[[numbers-30]]
== Chapter 30

[[numbers-30-1]]
^1^ And Moses explained to the sons of Israel all that the Lord had commanded him.

[[numbers-30-2]]
^2^ And he said to the leaders of the tribes of the sons of Israel: “This is the word, which the Lord has instructed:

[[numbers-30-3]]
^3^ If any man makes a vow to the Lord, or binds himself by an oath, he shall not make his word null and void, but all that he has promised, he shall fulfill.

[[numbers-30-4]]
^4^ If a woman, who is in her father’s house, vows anything, or binds herself by an oath, and she is still in a state of childhood, if her father knew of the vow which she has promised or of the oath by which she has obligated her soul, and he kept silent, she shall be liable to the vow:

[[numbers-30-5]]
^5^ whatever she has promised or swore, she shall complete in deed.

[[numbers-30-6]]
^6^ But if her father, as soon as he had heard it, had contradicted it, both her vows and her oaths shall be nullified, neither shall she be held liable to the promise, because her father had contradicted it.

[[numbers-30-7]]
^7^ If she has a husband, and she has vowed anything, then, once the word has gone out of her mouth, she will have obligated her soul by an oath.

[[numbers-30-8]]
^8^ On the day that her husband will hear of it, and yet not contradict it, she shall be liable to the vow, and she shall repay whatever she has promised.

[[numbers-30-9]]
^9^ But if, as soon as he hears it, he contradicts it, then he will have caused her promises, and the words by which she had bound her soul, to be null and void. The Lord will be favorable to her.

[[numbers-30-10]]
^10^ Widows and divorced women shall repay whatever they have vowed.

[[numbers-30-11]]
^11^ If a wife in the house of her husband has bound herself by a vow or an oath,

[[numbers-30-12]]
^12^ if her husband heard it and remained silent, and he did not contradict the promise, she shall repay what she had promised.

[[numbers-30-13]]
^13^ But if he promptly contradicts it, she shall not be held liable to the promise. For her husband has contradicted it. And the Lord will be favorable to her.

[[numbers-30-14]]
^14^ If she has vowed or bound herself by oath, in order to afflict her soul by fasting, or by abstaining from other things, it shall be for the arbitration of her husband, as to whether or not she may do it.

[[numbers-30-15]]
^15^ But if the husband, upon hearing it, remains silent, and he delays judgment until another day, whatever she had vowed or promised, she shall repay, because when he first heard it, he remained silent.

[[numbers-30-16]]
^16^ And if he contradicted it only sometime after he had known about it, he shall bear his iniquity.”

[[numbers-30-17]]
^17^ These are the laws which the Lord has appointed to Moses, between a husband and a wife, between a father and a daughter, who is still in the state of childhood or who remains in her father’s house.


[[numbers-31]]
== Chapter 31

[[numbers-31-1]]
^1^ And the Lord spoke to Moses, saying:

[[numbers-31-2]]
^2^ “First, avenge the sons of Israel from the Midianites, and then you shall be gathered to your people.”

[[numbers-31-3]]
^3^ And immediately Moses said: “Arm the men among you for a battle, so that they may be able to fulfill the retribution of the Lord on the Midianites.

[[numbers-31-4]]
^4^ Let one thousand men be chosen from each tribe of Israel, who shall be sent to war.”

[[numbers-31-5]]
^5^ And they gave one thousand from each tribe, that is, twelve thousand foot soldiers for battle.

[[numbers-31-6]]
^6^ And Moses sent them with Phinehas, the son of Eleazar the priest; also, he delivered to him the holy vessels, and the trumpets to sound.

[[numbers-31-7]]
^7^ And when they had fought against the Midianites and had prevailed, they killed all the men.

[[numbers-31-8]]
^8^ And they put to death by the sword their kings: Evi, and Rekem, and Zur, and Hur, and Reba, the five leaders of the nation, and also Balaam the son of Beor.

[[numbers-31-9]]
^9^ And they seized their women and little ones, and all their cattle, and all their goods; whatever they were able to have, they despoiled.

[[numbers-31-10]]
^10^ Both their cities and their villages, as well as their fortresses, they burned.

[[numbers-31-11]]
^11^ And they carried away prey from everything that they had seized, both of men and of beasts.

[[numbers-31-12]]
^12^ And they led these to Moses and Eleazar the priest, and to all the multitude of the sons of Israel. But the remainder of the articles they carried to the camp on the plains of Moab, next to the Jordan, opposite Jericho.

[[numbers-31-13]]
^13^ Then Moses, and Eleazar the priest, and all the leaders of the assembly went out to meet them beyond the camp.

[[numbers-31-14]]
^14^ And Moses, being angry with the leaders of the army, and the tribunes, and the centurions, who had arrived from the battle,

[[numbers-31-15]]
^15^ said: “Why have you spared the females?

[[numbers-31-16]]
^16^ Are not these the ones who deceived the sons of Israel at the suggestion of Balaam, and who caused you betray the Lord by the sin of Peor, because of which the people also were struck down?

[[numbers-31-17]]
^17^ Therefore, put to death all of them: whatever is of the male sex, even among the little ones, and cut the throats of those women who have known men by sexual relations.

[[numbers-31-18]]
^18^ But the young girls, and all female virgins, reserve for yourselves.

[[numbers-31-19]]
^19^ And remain beyond the camp for seven days. Whoever has killed a man, or who has touched one that was killed, shall be purified on the third day and on the seventh day.

[[numbers-31-20]]
^20^ And all of the spoils, whether it is a garment, or a vessel, or another useful thing, made from the pelts or hair of goats, or from wood, shall be expiated.”

[[numbers-31-21]]
^21^ Likewise, Eleazar the priest spoke in this manner to the men of the army who had fought: “This is the precept of the law, which the Lord has commanded Moses:

[[numbers-31-22]]
^22^ Gold, and silver, and brass, and iron, and lead, and tin,

[[numbers-31-23]]
^23^ and all that may be able to pass through fire, shall be purified by fire. But whatever is not able to sustain fire shall be sanctified with the waters of expiation.

[[numbers-31-24]]
^24^ And you shall wash your garments on the seventh day, and, after having been purified, you shall enter the camp.”

[[numbers-31-25]]
^25^ And the Lord also said to Moses:

[[numbers-31-26]]
^26^ “Take the sum of those things which were captured, from man even to beast, you and Eleazar the priest, and the leaders of the common people.

[[numbers-31-27]]
^27^ And you shall divide the prey equally, among those who went out to war and fought, and among the remainder of the multitude.

[[numbers-31-28]]
^28^ And you shall separate a portion for the Lord from the portion of those who fought and were in the battle: one soul out of five hundred, as much from humans, as from oxen and donkeys and sheep.

[[numbers-31-29]]
^29^ And you shall give it to Eleazar the priest, because these are the first-fruits of the Lord.

[[numbers-31-30]]
^30^ Likewise, from the half of the portion belonging to the sons of Israel, you shall receive the fiftieth head of humans, and of oxen, and donkeys, and sheep, and of all living things, and you shall give these to the Levites who stand watch over the care of the tabernacle of the Lord.”

[[numbers-31-31]]
^31^ And Moses and Eleazar did just as the Lord had instructed.

[[numbers-31-32]]
^32^ Now the prey which the army had seized was six hundred seventy-five thousand sheep,

[[numbers-31-33]]
^33^ seventy-two thousand oxen,

[[numbers-31-34]]
^34^ sixty-one thousand donkeys,

[[numbers-31-35]]
^35^ and thirty-two thousand human lives, of the female sex, who had not known men.

[[numbers-31-36]]
^36^ And one half of the portion was given to those who had been in the battle: three hundred thirty-seven thousand five hundred sheep.

[[numbers-31-37]]
^37^ From these, for the portion of the Lord, there were accounted: six hundred seventy-five sheep;

[[numbers-31-38]]
^38^ and from the thirty-six thousand oxen, seventy-two oxen;

[[numbers-31-39]]
^39^ from the thirty thousand five hundred donkeys, sixty-one donkeys.

[[numbers-31-40]]
^40^ From the sixteen thousand human souls, there fell to the portion of the Lord thirty-two souls.

[[numbers-31-41]]
^41^ And Moses delivered the number of the first-fruits of the Lord to Eleazar the priest, just as had been commanded of him,

[[numbers-31-42]]
^42^ from the one half portion belonging to the sons of Israel, which he had separated from the portion of those who had been in the battle.

[[numbers-31-43]]
^43^ Yet truly, from the one half portion which fell to the remainder of the multitude, that is, from the three hundred thirty-seven thousand five hundred sheep,

[[numbers-31-44]]
^44^ and from the thirty-six thousand oxen,

[[numbers-31-45]]
^45^ and from the thirty thousand five hundred donkeys,

[[numbers-31-46]]
^46^ and from the sixteen thousand persons,

[[numbers-31-47]]
^47^ Moses took the fiftieth head, and gave it to the Levites who stand watch at the tabernacle of the Lord, just as the Lord had instructed.

[[numbers-31-48]]
^48^ And when the leaders of the army, and the tribunes, and the centurions had approached Moses, they said:

[[numbers-31-49]]
^49^ “We, your servants, have taken a census of the number of the fighting men, whom we had under our hand, and indeed not one was lacking.

[[numbers-31-50]]
^50^ For this reason, we offer as gifts to the Lord whatever gold each one was able to find amid the spoils, in anklets and arm bands, rings and bracelets, and little chains, so that you may intercede for us to the Lord.”

[[numbers-31-51]]
^51^ And Moses and Eleazar the priest received all the gold in its various kinds,

[[numbers-31-52]]
^52^ weighing sixteen thousand seven hundred fifty shekels, from the tribunes and the centurions.

[[numbers-31-53]]
^53^ For whatever each one had taken away in the spoils was his own.

[[numbers-31-54]]
^54^ And having been accepted, they took it into the tabernacle of the testimony, as a memorial of the sons of Israel before the Lord.


[[numbers-32]]
== Chapter 32

[[numbers-32-1]]
^1^ Now the sons of Ruben and of Gad had many herds, and their substance in cattle was inestimable. And when they had seen that the lands of Jazer and Gilead were suitable for feeding animals,

[[numbers-32-2]]
^2^ they went to Moses, and to Eleazar the priest and the leaders of the multitude, and they said:

[[numbers-32-3]]
^3^ “Ataroth, and Dibon, and Jazer, and Nimrah, Heshbon, and Elealeh, and Sebam, and Nebo, and Beon,

[[numbers-32-4]]
^4^ the land, which the Lord has struck in the sight of the sons of Israel, is a very fertile region for pasturing animals. And we, your servants, have very many cattle.

[[numbers-32-5]]
^5^ And so we beseech you, if we have found favor before you, that you give it to us, your subjects, as a possession, and that you not cause us cross the Jordan.”

[[numbers-32-6]]
^6^ And Moses answered them: “Should your brothers go to battle, while you sit here?

[[numbers-32-7]]
^7^ Why do you subvert the minds of the sons of Israel, so that they might not dare to cross into the place which the Lord will give to them?

[[numbers-32-8]]
^8^ Did not your fathers act in the same way, when I sent them from Kadesh-Barnea to explore the land?

[[numbers-32-9]]
^9^ And when they had gone all the way to the Valley of the Cluster of Grapes, having viewed the entire region, they subverted the hearts of the sons of Israel, so that they would not enter into the parts that the Lord gave to them.

[[numbers-32-10]]
^10^ And being angry, the Lord swore an oath, saying:

[[numbers-32-11]]
^11^ ‘These men, who ascended out of Egypt, from twenty years and above, will not see the land, which I have promised under an oath to Abraham, Isaac, and Jacob. For they were not willing to follow me,

[[numbers-32-12]]
^12^ except Caleb, the son of Jephunneh the Kenizzite, and Joshua the son of Nun; these have fulfilled my will.’

[[numbers-32-13]]
^13^ And the Lord, being angry against Israel, led them in a course through the desert for forty years, until the entire generation, which had done evil in his sight, was consumed.

[[numbers-32-14]]
^14^ And behold,” he said, “you have risen up in the place of your fathers, the offshoots and the nurslings of sinful men, in order to augment the fury of the Lord against Israel.

[[numbers-32-15]]
^15^ But if you are not willing to follow him, he will leave the people behind in the wilderness, and you will have been the cause of all our deaths.”

[[numbers-32-16]]
^16^ But approaching closer, they said: “We will manufacture sheep pens and cattle stalls, as well as fortified cities, for our little ones.

[[numbers-32-17]]
^17^ But we ourselves will continue on, armed and girded for battle, before the sons of Israel, until we lead them to their places. Our little ones, and whatever we may be able to have, shall be in walled cities, because of the treachery of the inhabitants.

[[numbers-32-18]]
^18^ We will not return to our houses, even until the sons of Israel may possess their inheritance.

[[numbers-32-19]]
^19^ Neither will we seek anything across the Jordan, because we already have our possession on its eastern side.”

[[numbers-32-20]]
^20^ And Moses said to them: “If you accomplish what you have promised, you may go out, equipped for battle, before the Lord.

[[numbers-32-21]]
^21^ And let every fighting man cross over the Jordan, until the Lord overthrows his enemies,

[[numbers-32-22]]
^22^ and all the land is subjected to him. Then you will be guiltless with the Lord and with Israel, and you will obtain the regions which you desire before the Lord.

[[numbers-32-23]]
^23^ But if you do not do what you have said, no one could doubt that you will have sinned against God. And know this: your sin shall overtake you.

[[numbers-32-24]]
^24^ Therefore, build cities for your little ones, and pens and stables for your sheep and cattle; and fulfill what you have promised.”

[[numbers-32-25]]
^25^ And the sons of Gad and of Ruben said to Moses: “We are your servants, we shall do what you, our ruler, orders.

[[numbers-32-26]]
^26^ We will leave behind our little ones, and our wives, and the sheep and cattle, in the cities of Gilead.

[[numbers-32-27]]
^27^ And we, your servants, all well-equipped, will go forth to battle, just as you, our ruler, has spoken.”

[[numbers-32-28]]
^28^ Therefore, Moses instructed Eleazar the priest, and Joshua the son of Nun, and the princes of the families throughout the tribes of Israel, and he said to them:

[[numbers-32-29]]
^29^ “If the sons of Gad and the sons of Ruben cross over the Jordan with you, all armed for war before the Lord, and if the land becomes subject to you, give them Gilead as a possession.

[[numbers-32-30]]
^30^ But if they are not willing to cross with you, armed, into the land of Canaan, then let them receive places among you for their dwellings.”

[[numbers-32-31]]
^31^ And the sons of Gad and the sons of Ruben responded: “Just as the Lord has spoken to his servants, so shall we do.

[[numbers-32-32]]
^32^ We will go forth, armed, before the Lord into the land of Canaan; and we acknowledge that we have already received our possession across the Jordan.”

[[numbers-32-33]]
^33^ And so, Moses gave to the sons of Gad and of Ruben, and to half the tribe of Manasseh, the son of Joseph, the kingdom of Sihon, king of the Amorites, and the kingdom of Og, king of Bashan, and their land with its surrounding cities.

[[numbers-32-34]]
^34^ Therefore, the sons of Gad built up Dibon, and Ataroth, and Aroer,

[[numbers-32-35]]
^35^ and Atroth and Shophan, and Jazer, and Jogbehah,

[[numbers-32-36]]
^36^ and Beth-Nimrah, and Beth-Haran, as fortified cities with pens for their cattle.

[[numbers-32-37]]
^37^ Yet truly, the sons of Ruben built up Heshbon, and Elealeh, and Kiriathaim,

[[numbers-32-38]]
^38^ and Nebo, and Baal-meon (their names having been changed) and Sibmah, appointing names for the cities which they had built.

[[numbers-32-39]]
^39^ Moreover, the sons of Machir, the son of Manasseh, continued on within Gilead, and they devastated it, putting to death its inhabitant, the Amorite.

[[numbers-32-40]]
^40^ Therefore, Moses gave the land of Gilead to Machir, the son of Manasseh, and he lived in it.

[[numbers-32-41]]
^41^ But Jair, the son of Manasseh, went out and occupied its villages, which he called Havoth Jair, that is, the Villages of Jair.

[[numbers-32-42]]
^42^ Likewise, Nobah went forth and captured Kenath with its villages. And he called it by his own name, Nobah.


[[numbers-33]]
== Chapter 33

[[numbers-33-1]]
^1^ These are the lodging places of the sons of Israel, who departed from Egypt by their companies under the hand of Moses and Aaron,

[[numbers-33-2]]
^2^ which Moses wrote down according to the places of the encampments, which they changed upon the order of the Lord.

[[numbers-33-3]]
^3^ Thus the sons of Israel set out from Rameses in the first month, on the fifteenth day of the first month, on the day after the Passover, with an exalted hand, being seen by all the Egyptians.

[[numbers-33-4]]
^4^ And these were burying their firstborn, whom the Lord had struck down (for so, too, did he carry out retribution against their gods).

[[numbers-33-5]]
^5^ And they made camp at Soccoth.

[[numbers-33-6]]
^6^ And from Soccoth they went to Etham, which is at the furthest limits of the wilderness.

[[numbers-33-7]]
^7^ Departing from there, they arrived opposite Pi-hahiroth, which looks out toward Baal-zephon, and they were encamped before Migdol.

[[numbers-33-8]]
^8^ And setting out from Pi-hahiroth, they crossed through the middle of the Sea into the wilderness. And having walked for three days through the desert of Etham, they made camp at Marah.

[[numbers-33-9]]
^9^ And setting out from Marah, they arrived at Elim, where there were twelve fountains of water and seventy palm trees. And they set up camp there.

[[numbers-33-10]]
^10^ But departing from there also, they fixed their tents above the Red Sea. And setting out from the Red Sea,

[[numbers-33-11]]
^11^ they were encamped in the desert of Sin.

[[numbers-33-12]]
^12^ Departing from there, they went to Dophkah.

[[numbers-33-13]]
^13^ And setting out from Dophkah, they made camp at Alush.

[[numbers-33-14]]
^14^ And departing from Alush, they fixed their tents at Rephidim, where the people lacked water to drink.

[[numbers-33-15]]
^15^ And setting out from Rephidim, they camped in the desert of Sinai.

[[numbers-33-16]]
^16^ But departing also from the wilderness of the Sinai, they arrived at the Graves of Lust.

[[numbers-33-17]]
^17^ And setting out from the Graves of Lust, they were encamped at Hazeroth.

[[numbers-33-18]]
^18^ And from Hazeroth, they went to Rithmah.

[[numbers-33-19]]
^19^ And setting out from Rithmah, they made camp at Rimmon-perez.

[[numbers-33-20]]
^20^ And departing from there, they arrived at Libnah.

[[numbers-33-21]]
^21^ From Libnah, they made camp at Rissah.

[[numbers-33-22]]
^22^ And departing from Rissah, they went to Kehelathah.

[[numbers-33-23]]
^23^ Setting out from there, they were encamped at mount Shepher.

[[numbers-33-24]]
^24^ Departing from mount Shepher, they went to Haradah.

[[numbers-33-25]]
^25^ Continuing on from there, they made camp at Makheloth.

[[numbers-33-26]]
^26^ And setting out from Makheloth, they went to Tahath.

[[numbers-33-27]]
^27^ From Tahath, they made camp at Terah.

[[numbers-33-28]]
^28^ Departing from there, they pitched their tents at Mithkah.

[[numbers-33-29]]
^29^ And from Mithkah, they were encamped at Hashmonah.

[[numbers-33-30]]
^30^ And setting out from Hashmonah, they went to Moseroth.

[[numbers-33-31]]
^31^ And from Moseroth, they made camp at Bene-jaakan.

[[numbers-33-32]]
^32^ And setting out from Bene-jaakan, they went to mount Gidgad.

[[numbers-33-33]]
^33^ Setting out from there, they were encamped at Jotbathah.

[[numbers-33-34]]
^34^ And from Jotbathah, they went to Abronah.

[[numbers-33-35]]
^35^ And departing from Abronah, they made camp at Eziongeber.

[[numbers-33-36]]
^36^ Setting out from there, they went into the desert of Sin, which is Kadesh.

[[numbers-33-37]]
^37^ And departing from Kadesh, they encamped at mount Hor, at the furthermost limits of the land of Edom.

[[numbers-33-38]]
^38^ And Aaron the priest ascended onto mount Hor, by the order of the Lord. And there he died, in the fortieth year of the departure of the sons of Israel from Egypt, in the fifth month, on the first day of the month,

[[numbers-33-39]]
^39^ when he was one hundred twenty-three years old.

[[numbers-33-40]]
^40^ And king Arad the Canaanite, who lived toward the south, heard that the sons of Israel had arrived in the land of Canaan.

[[numbers-33-41]]
^41^ And setting out from mount Hor, they made camp at Zalmonah.

[[numbers-33-42]]
^42^ Departing from there, they went to Punon.

[[numbers-33-43]]
^43^ And setting out from Punon, they were encamped at Oboth.

[[numbers-33-44]]
^44^ And from Oboth, they went to Iye-abarim, which is at the borders of the Moabites.

[[numbers-33-45]]
^45^ And setting out from Iye-abarim, they fixed their tents at Dibon-gad.

[[numbers-33-46]]
^46^ Departing from there, they made camp at Almon-diblathaim.

[[numbers-33-47]]
^47^ And departing from Almon-diblathaim, they went to the mountains of Abarim, opposite Nebo.

[[numbers-33-48]]
^48^ And setting out from the mountains of Abarim, they crossed over to the plains of Moab, above the Jordan, opposite Jericho.

[[numbers-33-49]]
^49^ And they made camp there, from Beth-jeshimoth all the way to Abel-shittim, in the level places of the Moabites,

[[numbers-33-50]]
^50^ where the Lord said to Moses:

[[numbers-33-51]]
^51^ “Instruct the sons of Israel, and say to them: When you will have crossed over the Jordan, entering into the land of Canaan,

[[numbers-33-52]]
^52^ destroy all the inhabitants of that land. Break their monuments, and shatter their statues, and lay waste to every exalted thing,

[[numbers-33-53]]
^53^ cleansing the land and living in it. For I have given it you as a possession,

[[numbers-33-54]]
^54^ which you shall divide among you by lot. To the greater number you shall give more, and to the lesser number, less. To each one, just as the lot shall fall, so shall the inheritance be distributed. The possession shall be divided by the tribes and families.

[[numbers-33-55]]
^55^ But if you are not willing to put to death the inhabitants of the land, those who remain shall be to you like spikes in your eyes and lances in your sides, and they shall be adversaries to you in the land of your habitation.

[[numbers-33-56]]
^56^ And whatever I had decided to do to them, I will do to you.”


[[numbers-34]]
== Chapter 34

[[numbers-34-1]]
^1^ And the Lord spoke to Moses, saying:

[[numbers-34-2]]
^2^ “Instruct the sons of Israel, and you shall say to them: When you will have entered into the land of Canaan, and it has fallen into your possession by lot, it shall be bound by these limits:

[[numbers-34-3]]
^3^ The southern part shall begin from the wilderness of Sin, which is next to Edom, and it shall have the Sea of Salt as a limit to the east.

[[numbers-34-4]]
^4^ It shall circle on the south side along the ascent of the Scorpion, by this way crossing into Senna, and passing through, from the south, as far as Kadesh-barnea, from which its confines shall go out to the town called Adar, and extend even to Azmon.

[[numbers-34-5]]
^5^ And its limits shall go around from Azmon to the Torrent of Egypt, and shall end at the shore of the Great Sea.

[[numbers-34-6]]
^6^ Then the western region shall begin from the Great Sea, and the same shall be its end.

[[numbers-34-7]]
^7^ Furthermore, toward the northern region, its limits shall begin from the Great Sea, passing through even to the highest mountain.

[[numbers-34-8]]
^8^ From there, it limits shall advance into Hamath, as far as the limits of Zedad.

[[numbers-34-9]]
^9^ And its confines shall go all the way to Ziphron, and to the village of Enan. These shall be the limits on the northern side.

[[numbers-34-10]]
^10^ From there, its limits shall be measured, facing the east side, from the village of Enan as far as Shepham.

[[numbers-34-11]]
^11^ And from Shepham, the boundaries shall descend into Riblah, opposite the fountain of Daphnis. From there, the boundaries shall pass through, opposite the east, to the Sea of Chinnereth,

[[numbers-34-12]]
^12^ and shall extend as far as the Jordan, and, at the furthest extent, shall be enclosed by the Sea of Salt. You shall have this land, with its borders all around.”

[[numbers-34-13]]
^13^ And Moses instructed the sons of Israel, saying: “This shall be the land which you shall possess by lot, and which the Lord has ordered to be given to the nine tribes, and to the half tribe.

[[numbers-34-14]]
^14^ For the tribe of the sons of Ruben, by their families, and the tribe of the sons of Gad, according to the number of their kinships, and also one half of the tribe of Manasseh,

[[numbers-34-15]]
^15^ that is, two and a half tribes, have received their portion across the Jordan, opposite Jericho, toward the eastern side.”

[[numbers-34-16]]
^16^ And the Lord said to Moses:

[[numbers-34-17]]
^17^ “These are the names of the men, who shall divide the land for you: Eleazar the priest, and Joshua the son of Nun,

[[numbers-34-18]]
^18^ and one leader from each tribe,

[[numbers-34-19]]
^19^ whose names are these: from the tribe of Judah, Caleb the son of Jephunneh;

[[numbers-34-20]]
^20^ from the tribe of Simeon, Samuel the son of Ammihud;

[[numbers-34-21]]
^21^ from the tribe of Benjamin, Elidad the son of Chislon;

[[numbers-34-22]]
^22^ from the tribe of the sons of Dan, Bukki the son of Jogli;

[[numbers-34-23]]
^23^ of the sons of Joseph, from the tribe of Manasseh, Hanniel the son of Ephod;

[[numbers-34-24]]
^24^ from the tribe of Ephraim, Kemuel the son of Shiphtan;

[[numbers-34-25]]
^25^ from the tribe of Zebulon, Elizaphan the son of Parnach;

[[numbers-34-26]]
^26^ from the tribe of Issachar, Paltiel the leader, the son of Azzan;

[[numbers-34-27]]
^27^ from the tribe of Asher, Ahihud the son of Shelomi;

[[numbers-34-28]]
^28^ from the tribe of Naphtali, Pedahel the son of Ammihud.”

[[numbers-34-29]]
^29^ These are the ones that the Lord has ordered to divide the land of Canaan to the sons of Israel.


[[numbers-35]]
== Chapter 35

[[numbers-35-1]]
^1^ And the Lord also spoke these things to Moses in the plains of Moab, above the Jordan, opposite Jericho:

[[numbers-35-2]]
^2^ “Instruct the sons of Israel, so that they may give to the Levites, from their possessions,

[[numbers-35-3]]
^3^ cities as dwelling places, with their surrounding suburbs, so that they may lodge in the towns, and so that the suburbs may be for cattle and beasts of burden.

[[numbers-35-4]]
^4^ The suburbs shall extend from the outer walls of the cities, all around, for the space of one thousand steps.

[[numbers-35-5]]
^5^ Facing the east, there shall be two thousand cubits, and facing the south, similarly, there shall be two thousand cubits. Toward the sea, also, which looks out toward the west, there shall be the same measure, and the northern region shall be bounded by equal limits. And the cities shall be in the center, and the suburbs shall be outside.

[[numbers-35-6]]
^6^ Now, from the towns which you shall give to the Levites, six shall be separated for the assistance of fugitives, so that he who has shed blood may flee to them. And, aside from these, there shall be forty-two other towns,

[[numbers-35-7]]
^7^ that is, all together forty-eight with their suburbs.

[[numbers-35-8]]
^8^ And concerning these cities, which shall be given from the possessions of the sons of Israel: from those who have more, more shall be taken, and from those who have less, less shall be taken. Each shall give towns to the Levites according to the measure of their inheritance.”

[[numbers-35-9]]
^9^ The Lord said to Moses:

[[numbers-35-10]]
^10^ “Speak to the sons of Israel, and you shall say to them: When you will have crossed the Jordan into the land of Canaan,

[[numbers-35-11]]
^11^ discern which cities ought to be for the protection of fugitives who have shed blood unwillingly.

[[numbers-35-12]]
^12^ And when a fugitive is in these, the kinsman of the deceased shall not be able to kill him, until he stands in the sight of the multitude and his case is judged.

[[numbers-35-13]]
^13^ Then, among those cities which are separated for relief to fugitives,

[[numbers-35-14]]
^14^ three shall be across the Jordan, and three in the land of Canaan,

[[numbers-35-15]]
^15^ as much for the sons of Israel as for newcomers and sojourners, so that anyone who has shed blood unwillingly may flee to these places.

[[numbers-35-16]]
^16^ If anyone will have struck someone with iron, and he who was struck will have died, then he shall be guilty of homicide, and he himself shall die.

[[numbers-35-17]]
^17^ If he will have thrown a stone, and he who has been struck lies dead, then he shall be punished similarly.

[[numbers-35-18]]
^18^ If he who has been struck with wood passes away, he shall be avenged by the blood of the one who struck him.

[[numbers-35-19]]
^19^ The close relative of the deceased shall put to death the murderer; as soon as he apprehends him, he shall put him to death.

[[numbers-35-20]]
^20^ If, out of hatred, anyone assaults a man, or throws anything at him with ill intent,

[[numbers-35-21]]
^21^ or, while being his enemy, strikes him with his hand, and so he has died, the attacker shall be guilty of murder. The kinsman of the deceased, as soon as he finds him, shall cut his throat.

[[numbers-35-22]]
^22^ But if by chance, and without hatred

[[numbers-35-23]]
^23^ or animosity, he will have done any of these things,

[[numbers-35-24]]
^24^ and this has been proven in the hearing of the people, and the questions have been aired, between the one who struck and the close relative,

[[numbers-35-25]]
^25^ then the innocent one shall be freed from the hand of the revenger, and he shall be returned by this judgment into the city to which he had fled, and he shall stay there until the high priest, who has been anointed with the holy oil, dies.

[[numbers-35-26]]
^26^ If the one who has killed has been found beyond the limits of the cities which have been assigned to the exiled,

[[numbers-35-27]]
^27^ and he has been struck by him who is avenging blood, he who killed him shall not be harmed.

[[numbers-35-28]]
^28^ For the fugitive ought to have resided in the city, until the death of the high priest. Then, after he is dead, the one who has killed shall be returned to his own land.

[[numbers-35-29]]
^29^ These things shall be a perpetual ordinance in all your habitations.

[[numbers-35-30]]
^30^ The punishment of a murderer shall be based upon testimony; but no one shall be condemned upon the testimony of only one person.

[[numbers-35-31]]
^31^ You shall not accept money from him who is guilty of blood, and he shall be put to death promptly.

[[numbers-35-32]]
^32^ Exiles and fugitives, prior to the death of the high priest, are by no means able to be returned to their own cities.

[[numbers-35-33]]
^33^ Do not pollute the land of your habitation, so as to stain it with the blood of the innocent; neither is it able to be expiated in any way other than by the blood of him who has shed the blood of another.

[[numbers-35-34]]
^34^ And so shall your possession be cleansed, while I myself am abiding with you. For I am the Lord, who lives among the sons of Israel.”


[[numbers-36]]
== Chapter 36

[[numbers-36-1]]
^1^ Then the leaders of the families of Gilead, the son of Machir, the son of Manasseh, from the stock of the sons of Joseph, approached and spoke to Moses before the leaders of Israel, and they said:

[[numbers-36-2]]
^2^ “The Lord has instructed you, our ruler, so that you would divide the land by lot to the sons of Israel, and so that you would give to the daughters of Zelophehad, our brother, the possession owed to their father.

[[numbers-36-3]]
^3^ But if men of another tribe receive them as wives, their possession will follow them, and having been transferred to another tribe, there will be a reduction in our inheritance.

[[numbers-36-4]]
^4^ And so it may be that, when the Jubilee of remission, that is, the fiftieth year, has arrived, the distribution by lots shall be confounded, and the possession of the one shall be transferred to others.”

[[numbers-36-5]]
^5^ Moses answered the sons of Israel, and, at the instruction of the Lord, he said: “The tribe of the sons of Joseph has spoken correctly.

[[numbers-36-6]]
^6^ And so, this is the law which has been promulgated by the Lord about the daughters of Zelophehad: Let them marry whomever they may wish, but only among the men of their own tribe,

[[numbers-36-7]]
^7^ lest the possession of the sons of Israel become commingled, from tribe to tribe. For all men shall take wives from their own tribe and kinship;

[[numbers-36-8]]
^8^ and all women shall take husbands from their same tribe, so that the inheritance may remain within the families,

[[numbers-36-9]]
^9^ and so that the tribes may not be mingled together, but may remain such as they were separated by the Lord.”

[[numbers-36-10]]
^10^ And the daughters of Zelophehad acted according to what was ordered.

[[numbers-36-11]]
^11^ And Mahlah, and Tirzah, and Hoglah, and Milcah, and Noa were wed to the sons of their paternal uncle,

[[numbers-36-12]]
^12^ from the family of Manasseh, who was a son of Joseph. And the possession which had been distributed to them remained in the tribe and family of their father.

[[numbers-36-13]]
^13^ These are the commandments and judgments which the Lord ordered by the hand of Moses to the sons of Israel, in the plains of Moab, above the Jordan, opposite Jericho.
