[[first-chronicles]]
= The First Book of Chronicles
:short: 1st Chronicles

[[first-chronicles-1]]
== Chapter 1

[[first-chronicles-1-1]]
^1^ Adam, Seth, Enos,

[[first-chronicles-1-2]]
^2^ Cainan, Mahalalel, Jared,

[[first-chronicles-1-3]]
^3^ Enoch, Methuselah, Lamech,

[[first-chronicles-1-4]]
^4^ Noah, Shem, Ham, and Japheth.

[[first-chronicles-1-5]]
^5^ The sons of Japheth: Gomer, and Magog, and Madai, and Javan, Tubal, Meshech, Tiras.

[[first-chronicles-1-6]]
^6^ And the sons of Gomer: Ashkenaz, and Riphath, and Togarmah.

[[first-chronicles-1-7]]
^7^ And the sons of Javan: Elishah and Tarshish, Kittim and Rodanim.

[[first-chronicles-1-8]]
^8^ The sons of Ham: Cush, and Mizraim, and Put, and Canaan.

[[first-chronicles-1-9]]
^9^ And the sons of Cush: Seba, and Havilah, Sabtah, and Raamah, and Sabteca. And the sons of Raamah: Sheba and Dadan.

[[first-chronicles-1-10]]
^10^ Then Cush conceived Nimrod, and he began to be powerful upon the earth.

[[first-chronicles-1-11]]
^11^ Truly, Mizraim conceived Ludim, and Anamim, and Lehabim, and Naphtuhim,

[[first-chronicles-1-12]]
^12^ as well as Pathrusim and Casluhim: from these the Philistines and the Caphtorim went forth.

[[first-chronicles-1-13]]
^13^ Truly, Canaan conceived Sidon, his firstborn, as well as the Hittite,

[[first-chronicles-1-14]]
^14^ and the Jebusite, and the Amorite, and the Girgashite,

[[first-chronicles-1-15]]
^15^ and the Hivite, and the Arkite, and the Sinite,

[[first-chronicles-1-16]]
^16^ and also the Arvadian, and the Samarite, and the Hamathite.

[[first-chronicles-1-17]]
^17^ The sons of Shem: Elam, and Asshur, and Arphaxad, and Lud, and Aram, and Uz, and Hul, and Gether, and Meshech.

[[first-chronicles-1-18]]
^18^ Then Arphaxad conceived Shelah, who also himself conceived Eber.

[[first-chronicles-1-19]]
^19^ And to Eber were born two sons. The name of one was Peleg, because in his days the earth was divided. And the name of his brother was Joktan.

[[first-chronicles-1-20]]
^20^ Then Joktan conceived Almodad, and Sheleph, and Hazarmaveth, and Jerah,

[[first-chronicles-1-21]]
^21^ as well as Hadoram, and Uzal, and Diklah,

[[first-chronicles-1-22]]
^22^ and then Obal, and Abimael, and Sheba, indeed

[[first-chronicles-1-23]]
^23^ also Ophir, and Havilah, and Jobab. All these are the sons of Joktan.

[[first-chronicles-1-24]]
^24^ Shem, Arphaxad, Shelah,

[[first-chronicles-1-25]]
^25^ Eber, Peleg, Reu,

[[first-chronicles-1-26]]
^26^ Serug, Nahor, Terah,

[[first-chronicles-1-27]]
^27^ Abram, the same is Abraham.

[[first-chronicles-1-28]]
^28^ And the sons of Abraham: Isaac and Ishmael.

[[first-chronicles-1-29]]
^29^ And these are their generations: the firstborn of Ishmael, Nebaioth, and then Kedar, and Adbeel, and Mibsam,

[[first-chronicles-1-30]]
^30^ and Mishma, and Dumah, Massa, Hadad, and Tema,

[[first-chronicles-1-31]]
^31^ Jetur, Naphish, Kedemah. These are the sons of Ishmael.

[[first-chronicles-1-32]]
^32^ And the sons of Keturah, the concubine of Abraham, whom she conceived: Zimran, Jokshan, Medan, Midian, Ishbak, and Shuah. And the sons of Jokshan: Sheba and Dedan. And the sons of Dedan: Asshurim, and Letushim, and Leummim.

[[first-chronicles-1-33]]
^33^ And the sons of Midian: Ephah, and Epher, and Hanoch, and Abida, and Eldaah. All these are the sons of Keturah.

[[first-chronicles-1-34]]
^34^ Now Abraham conceived Isaac, whose sons were Esau and Israel.

[[first-chronicles-1-35]]
^35^ The sons of Esau: Eliphaz, Reuel, Jeush, Jalam, and Korah.

[[first-chronicles-1-36]]
^36^ The sons of Eliphaz: Teman, Omar, Zepho, Gatam, Kenez, and by Timna, Amalek.

[[first-chronicles-1-37]]
^37^ The sons of Reuel: Nahath, Zerah, Shammah, Mizzah.

[[first-chronicles-1-38]]
^38^ The sons of Seir: Lotan, Shobal, Zibeon, Anah, Dishon, Ezer, Dishan.

[[first-chronicles-1-39]]
^39^ The sons of Lotan: Hori, Heman. Now the sister of Lotan was Timna.

[[first-chronicles-1-40]]
^40^ The sons of Shobal: Alian, and Manahath, and Ebal, Shephi, and Onam. The sons of Zibeon: Aiah and Anah. The sons of Anah: Dishon.

[[first-chronicles-1-41]]
^41^ The sons of Dishon: Hamran, and Esheban, and Ithran, and Cheran.

[[first-chronicles-1-42]]
^42^ The sons of Ezer: Bilhan, and Zaavan, and Akan. The sons of Dishan: Uz and Aran.

[[first-chronicles-1-43]]
^43^ Now these are the kings who reigned in the land of Edom, before there was a king over the sons of Israel: Bela, the son of Beor; and the name of his city was Dinhabah.

[[first-chronicles-1-44]]
^44^ Then Bela died, and Jobab, the son of Zerah, from Bozrah, reigned in his place.

[[first-chronicles-1-45]]
^45^ And when Jobab also had died, Husham, from the land of the Temanites, reigned in his place.

[[first-chronicles-1-46]]
^46^ Then Husham also passed away, and Hadad, the son of Bedad, reigned in his place. And he struck the Midianites in the land of Moab. The name of his city was Avith.

[[first-chronicles-1-47]]
^47^ And when Hadad also had died, Samlah from Masrekah reigned in his place.

[[first-chronicles-1-48]]
^48^ Then Samlah also died, and Shaul from Rehoboth, which is situated beside a river, reigned in his place.

[[first-chronicles-1-49]]
^49^ Shaul also having died, Baal-hanan, the son of Achbor, reigned in his place.

[[first-chronicles-1-50]]
^50^ Then he too died, and Hadar reigned in his place. And the name of his city was Pau. And his wife was called Mehetabel, the daughter of Matred, the daughter of Mezahab.

[[first-chronicles-1-51]]
^51^ And Hadar having died, there began to be commanders in Edom in place of kings: commander Thamna, commander Alvah, commander Jetheth,

[[first-chronicles-1-52]]
^52^ commander Oholibamah, commander Elah, commander Pinon,

[[first-chronicles-1-53]]
^53^ commander Kanez, commander Teman, commander Mibzar,

[[first-chronicles-1-54]]
^54^ commander Magdiel, commander Iram. These are the commanders of Edom.


[[first-chronicles-2]]
== Chapter 2

[[first-chronicles-2-1]]
^1^ And the sons of Israel: Reuben, Simeon, Levi, Judah, Issachar, and Zebulun,

[[first-chronicles-2-2]]
^2^ Dan, Joseph, Benjamin, Naphtali, Gad, and Asher.

[[first-chronicles-2-3]]
^3^ The sons of Judah: Er, Onan, and Shelah. These three were born to him from the daughter of Shua, the Canaanite. But Er, the firstborn of Judah, was evil in the sight of the Lord, and so he killed him.

[[first-chronicles-2-4]]
^4^ Now Tamar, his daughter-in-law, bore to him Perez and Zerah. Therefore, all the sons of Judah were five.

[[first-chronicles-2-5]]
^5^ And the sons of Perez: Hezron and Hamul.

[[first-chronicles-2-6]]
^6^ Also, the sons of Zerah: Zimri, and Ethan, and Heman, as well as Calcol and Dara, five altogether.

[[first-chronicles-2-7]]
^7^ The sons of Carmi: Achar, who disturbed Israel and sinned by the theft of what was anathema.

[[first-chronicles-2-8]]
^8^ The sons of Ethan: Azariah.

[[first-chronicles-2-9]]
^9^ And the sons of Hezron who were born to him: Jerahmeel, and Ram, and Chelubai.

[[first-chronicles-2-10]]
^10^ Then Ram conceived Amminadab. And Amminadab conceived Nahshon, a leader of the sons of Judah.

[[first-chronicles-2-11]]
^11^ Also, Nahshon conceived Salma, from whom Boaz rose up.

[[first-chronicles-2-12]]
^12^ Truly, Boaz conceived Obed, who also himself conceived Jesse.

[[first-chronicles-2-13]]
^13^ Now Jesse conceived the firstborn Eliab, the second Abinadab, the third Shammah,

[[first-chronicles-2-14]]
^14^ the fourth Nethanel, the fifth Raddai,

[[first-chronicles-2-15]]
^15^ the sixth Ozem, the seventh David.

[[first-chronicles-2-16]]
^16^ Their sisters were Zeruiah and Abigail. The sons of Zeruiah: Abishai, Joab, and Asahel, three.

[[first-chronicles-2-17]]
^17^ And Abigail conceived Amasa, whose father was Jether, the Ishmaelite.

[[first-chronicles-2-18]]
^18^ Truly, Caleb, the son of Hezron, took a wife named Azubah, of whom he conceived Jerioth. And her sons were Jesher, and Shobab, and Ardon.

[[first-chronicles-2-19]]
^19^ And when Azubah had died, Caleb took as wife Ephratha, who bore to him Hur.

[[first-chronicles-2-20]]
^20^ Now Hur conceived Uri. And Uri conceived Bezalel.

[[first-chronicles-2-21]]
^21^ And afterwards, Hezron entered to the daughter of Machir, father of Gilead. And he took her when he was sixty years old. And she bore to him Segub.

[[first-chronicles-2-22]]
^22^ And then Segub conceived Jair, and he possessed twenty-three cities in the land of Gilead.

[[first-chronicles-2-23]]
^23^ And he seized Geshur and Aram, towns of Jair, and Kenath and its villages, sixty cities. All these were sons of Machir, father of Gilead.

[[first-chronicles-2-24]]
^24^ Then, when Hezron had died, Caleb entered to Ephratha. Also, Hezron had as wife Abia, who bore to him Ashhur, the father of Tekoa.

[[first-chronicles-2-25]]
^25^ Now sons were born to Jerahmeel, the firstborn of Hezron: Ram, his firstborn, and Bunah, and Oren, and Ozem, and Ahijah.

[[first-chronicles-2-26]]
^26^ Jerahmeel also married another wife, named Atarah, who was the mother of Onam.

[[first-chronicles-2-27]]
^27^ Then too, the sons of Ram, the firstborn of Jerahmeel, were Maaz, Jamin, and Eker.

[[first-chronicles-2-28]]
^28^ And Onam had sons: Shammai and Jada. And the sons of Shammai: Nadab and Abishur.

[[first-chronicles-2-29]]
^29^ Truly, the name of the wife of Abishur was Abihail, who bore to him Ahban and Molid.

[[first-chronicles-2-30]]
^30^ Now the sons of Nadab were Seled and Appaim. And Seled died without children.

[[first-chronicles-2-31]]
^31^ Truly, the son of Appaim was Ishi. And Ishi conceived Sheshan. Then Sheshan conceived Ahlai.

[[first-chronicles-2-32]]
^32^ But the sons of Jada, the brother of Shammai, were Jether and Jonathan. Then Jether also died without children.

[[first-chronicles-2-33]]
^33^ And Jonathan conceived Peleth and Zaza. These were the sons of Jerahmeel.

[[first-chronicles-2-34]]
^34^ Now Sheshan did not have sons, but only daughters, and an Egyptian servant named Jarha.

[[first-chronicles-2-35]]
^35^ And so he gave to him his daughter as wife, who bore to him Attai.

[[first-chronicles-2-36]]
^36^ Then Attai conceived Nathan, and Nathan conceived Zabad.

[[first-chronicles-2-37]]
^37^ Also, Zabad conceived Ephlal, and Ephlal conceived Obed.

[[first-chronicles-2-38]]
^38^ Obed conceived Jehu; Jehu conceived Azariah.

[[first-chronicles-2-39]]
^39^ Azariah conceived Helez, and Helez conceived Eleasah.

[[first-chronicles-2-40]]
^40^ Eleasah conceived Sismai; Sismai conceived Shallum.

[[first-chronicles-2-41]]
^41^ Shallum conceived Jekamiah; then Jekamiah conceived Elishama.

[[first-chronicles-2-42]]
^42^ And the sons of Caleb, the brother of Jerahmeel, were Mesha, his firstborn, who was the father of Ziph, and the sons of Mesha, the father of Hebron.

[[first-chronicles-2-43]]
^43^ Now the sons of Hebron were Korah, and Tapuah, and Rekem, and Shema.

[[first-chronicles-2-44]]
^44^ Then Shema conceived Raham, the father of Jorkeam. And Rekem conceived Shammai.

[[first-chronicles-2-45]]
^45^ The son of Shammai was Maon, and Maon was the father of Bethzur.

[[first-chronicles-2-46]]
^46^ Now Ephah, the concubine of Caleb, bore Haran, and Moza, and Gazez. And Haran conceived Gazez.

[[first-chronicles-2-47]]
^47^ And the sons of Jahdai: Regem, and Jotham, and Geshan, and Pelet, and Ephah, and Shaaph.

[[first-chronicles-2-48]]
^48^ And Maacah, the concubine of Caleb, bore Sheber and Tirhanah.

[[first-chronicles-2-49]]
^49^ Then Shaaph, the father of Madmannah, conceived Sheva, the father of Machbenah, and the father of Gibea. Truly, the daughter of Caleb was Achsah.

[[first-chronicles-2-50]]
^50^ These were the sons of Caleb, the son of Hur, the firstborn of Ephratha: Shobal, the father of Kiriath-jearim;

[[first-chronicles-2-51]]
^51^ Salma, the father of Bethlehem; Hareph, the father of Bethgader.

[[first-chronicles-2-52]]
^52^ Now there were sons for Shobal, the father of Kiriath-jearim, who saw half the places of rest.

[[first-chronicles-2-53]]
^53^ And from the kindred of Kiriath-jearim: the Ithrites, and the Puthites, and the Shumathites, and the Mishraites. From these, the Zorathites and the Eshtaolites went forth.

[[first-chronicles-2-54]]
^54^ The sons of Salma: Bethlehem, and the Netophathites, the crowns of the house of Joab, and half the places of rest of the Zorathites,

[[first-chronicles-2-55]]
^55^ as well as the families of the scribes living in Jabesh, those singing and making music, and those dwelling in tents. These are the Kenites, who went forth from Calor, the father of the house of Rechab.


[[first-chronicles-3]]
== Chapter 3

[[first-chronicles-3-1]]
^1^ Truly, David had these sons, who were born to him in Hebron: the firstborn Amnon, of Ahinoam the Jezreelite; the second Daniel, from Abigail the Carmelite;

[[first-chronicles-3-2]]
^2^ the third Absalom, the son of Maacah, daughter of Talmai, king of Geshur; the fourth Adonijah, the son of Haggith;

[[first-chronicles-3-3]]
^3^ the fifth Shephatiah, of Abital; the sixth Ithream, from his wife Eglah.

[[first-chronicles-3-4]]
^4^ Therefore, six were born to him in Hebron, where he reigned for seven years and six months. Then he reigned for thirty-three years in Jerusalem.

[[first-chronicles-3-5]]
^5^ Now in Jerusalem, sons were born to him: Shammua, and Sobab, and Nathan, and Solomon, these four from Bathsheba, the daughter of Ammiel;

[[first-chronicles-3-6]]
^6^ also Ibhar and Elishama,

[[first-chronicles-3-7]]
^7^ and Eliphelet, and Nogah, and Nepheg, and Japhia,

[[first-chronicles-3-8]]
^8^ indeed also Elishama, and Eliada, and Eliphelet, nine.

[[first-chronicles-3-9]]
^9^ All these were sons of David, aside from the sons of the concubines. And they had a sister, Tamar.

[[first-chronicles-3-10]]
^10^ Now the son of Solomon was Rehoboam, from whom Abijah conceived a son, Asa. And from him, there was born Jehoshaphat,

[[first-chronicles-3-11]]
^11^ the father of Jehoram. And Jehoram conceived Ahaziah, from whom there was born Jehoash.

[[first-chronicles-3-12]]
^12^ And his son, Amaziah, conceived Azariah. Then Jotham, the son of Azariah,

[[first-chronicles-3-13]]
^13^ conceived Ahaz, the father of Hezekiah, from whom was born Manasseh.

[[first-chronicles-3-14]]
^14^ Then too, Manasseh conceived Amon, the father of Josiah.

[[first-chronicles-3-15]]
^15^ Now the sons of Josiah were these: the firstborn Johanan, the second Jehoiakim, the third Zedekiah, the fourth Shallum.

[[first-chronicles-3-16]]
^16^ From Jehoiakim was born Jeconiah and Zedekiah.

[[first-chronicles-3-17]]
^17^ The sons of Jeconiah the captive were: Shealtiel,

[[first-chronicles-3-18]]
^18^ Malchiram, Pedaiah, Shenazzar, and Jekamiah, Hoshama, and Nedabiah.

[[first-chronicles-3-19]]
^19^ From Pedaiah, there rose up Zerubbabel and Shimei. Zerubbabel conceived Meshullam, Hananiah, and their sister Shelomith,

[[first-chronicles-3-20]]
^20^ as well as Hashubah, and Ohel, and Berechiah, and Hasadiah, Jushab-hesed, five.

[[first-chronicles-3-21]]
^21^ Now the son of Hananiah was Pelatiah, the father of Jeshaiah, whose son was Rephaiah. And his son was Arnan, from whom was born Obadiah, whose son was Shecaniah.

[[first-chronicles-3-22]]
^22^ The son of Shecaniah was Shemaiah, whose sons were these: Hattush, and Igal, and Bariah, and Neariah, and Shaphat, six in number.

[[first-chronicles-3-23]]
^23^ The sons of Neariah: Elioenai, and Hizkiaj, and Azrikam, three.

[[first-chronicles-3-24]]
^24^ The sons of Elioenai: Hodaviah, and Eliashib, and Pelaiah, and Akkub, and Johanan, and Delaiah, and Anani, seven.


[[first-chronicles-4]]
== Chapter 4

[[first-chronicles-4-1]]
^1^ The sons of Judah: Perez, Hezron, and Carmi, and Hur, and Shobal.

[[first-chronicles-4-2]]
^2^ Truly, Reaiah, the son of Shobal, conceived Jahath; from him were born Ahumai and Lahad. These are the kindred of the Zorathites.

[[first-chronicles-4-3]]
^3^ And this is the stock of Etam: Jezreel, and Ishma, and Idbash. And the name of their sister was Hazzelelponi.

[[first-chronicles-4-4]]
^4^ Now Penuel was the father of Gedor, and Ezer was the father of Hushah. These are the sons of Hur, the firstborn of Ephratha, the father of Bethlehem.

[[first-chronicles-4-5]]
^5^ Truly, for Ashhur, the father of Tekoa, there were two wives: Helah and Naarah.

[[first-chronicles-4-6]]
^6^ And Naarah bore to him: Ahuzzam, and Hepher, and Temeni, and Haahashtari. These are the sons of Naarah.

[[first-chronicles-4-7]]
^7^ And the sons of Helah were Zereth, Izhar, and Ethnan.

[[first-chronicles-4-8]]
^8^ Now Koz conceived Anub, and Zobebah, and the kindred of Aharhel, the son of Harum.

[[first-chronicles-4-9]]
^9^ But Jabez was renowned, more so than his brothers, and his mother called his name Jabez, saying, “For I bore him in sorrow.”

[[first-chronicles-4-10]]
^10^ Truly, Jabez called upon the God of Israel, saying, “If only, when blessing, you will bless me, and will broaden my borders, and your hand will be with me, and you will cause me not to be oppressed by evil.” And God granted to him the things for which he prayed.

[[first-chronicles-4-11]]
^11^ Now Chelub, the brother of Shuhah, conceived Mehir, who was the father of Eshton.

[[first-chronicles-4-12]]
^12^ Then Eshton conceived Bethrapha, and Paseah, and Tehinnah, the father of the city of Nahash. These are the men of Recah.

[[first-chronicles-4-13]]
^13^ Now the sons of Kenaz were Othniel and Seraiah. And the sons of Othniel were Hathath and Meonothai.

[[first-chronicles-4-14]]
^14^ Meonothai conceived Ophrah, but Seraiah conceived Joab, the father of the Valley of Artisans. For indeed, there were artisans there.

[[first-chronicles-4-15]]
^15^ Truly, the sons of Chelub, the son of Jephunneh, were Iru, and Elah, and Naam. And the sons of Elah: Kenaz.

[[first-chronicles-4-16]]
^16^ Also, the sons of Jehallelel: Ziph and Ziphah, Tiria and Asarel.

[[first-chronicles-4-17]]
^17^ And the sons of Ezrah: Jether, and Mered, and Epher, and Jalon; and he conceived Miriam, and Shammai, and Ishbah, the father of Eshtemoa.

[[first-chronicles-4-18]]
^18^ And then his wife, Judaia, bore Jered, the father of Gedor, and Heber, the father of Soco, and Jekuthiel, the father of Zanoah. Now there were sons of Bithiah, the daughter of Pharaoh, whom Mered married,

[[first-chronicles-4-19]]
^19^ and sons of his wife Hodiah, the sister of Naham, the father of Keilah the Garmite, and of Eshtemoa, who was from Maacathi.

[[first-chronicles-4-20]]
^20^ And the sons of Shimon: Amnon, and Rinnah, son of Hanan, and Tilon. And the sons of Ishi: Zoheth and Benzoheth.

[[first-chronicles-4-21]]
^21^ The sons of Shelah, the son of Judah: Er, the father of Lecah, and Laadah, the father of Mareshah, and the kindred of the house of the workers of fine linen in the house of the oath,

[[first-chronicles-4-22]]
^22^ and he who caused the sun to stand still, and the men of Lying, and Secure, and Burning, who were leaders in Moab, and who returned into Lehem. Now these words are ancient.

[[first-chronicles-4-23]]
^23^ These are the potters living in the Plantations and in the Hedges, with a king in his works, and they were dwelling there.

[[first-chronicles-4-24]]
^24^ The sons of Simeon: Nemuel and Jamin, Jarib, Zerah, Shaul;

[[first-chronicles-4-25]]
^25^ Shallum his son, Mibsam his son, Mishma his son.

[[first-chronicles-4-26]]
^26^ The sons of Mishma: Hammuel his son, Zaccur his son, Shimei his son.

[[first-chronicles-4-27]]
^27^ The sons of Shimei were sixteen, and there were six daughters. But his brothers did not have many sons, and the entire kindred was not equal to the sum of the sons of Judah.

[[first-chronicles-4-28]]
^28^ Now they lived in Beersheba, and Moladah, and Hazarshual,

[[first-chronicles-4-29]]
^29^ and in Bilhah, and in Ezem, and in Tolad,

[[first-chronicles-4-30]]
^30^ and in Bethuel, and in Hormah, and in Ziklag,

[[first-chronicles-4-31]]
^31^ and in Beth-marcaboth, and in Hazarsusim, and in Bethbiri, and in Shaaraim. These were their cities until king David.

[[first-chronicles-4-32]]
^32^ And their towns were Etam, and Ain, Rimmon, and Tochen, and Ashan, five cities,

[[first-chronicles-4-33]]
^33^ with all their villages, on every side of these cities, as far as Baal. This is their habitation and the distribution of the settlements.

[[first-chronicles-4-34]]
^34^ And there were Meshobab and Jamlech, and Joshah, the son of Amaziah,

[[first-chronicles-4-35]]
^35^ and Joel, and Jehu, the son of Joshibiah, the son of Seraiah, the son of Asiel,

[[first-chronicles-4-36]]
^36^ and Elioenai, and Jaakobah, and Jeshohaiah, and Asaiah, and Adiel, and Jesimiel, and Benaiah,

[[first-chronicles-4-37]]
^37^ as well as Ziza, the son of Shiphi, the son of Allon, the son of Jedaiah, the son of Shimri, the son of Shemaiah.

[[first-chronicles-4-38]]
^38^ These were the names of the leaders in their kindred. And they were multiplied greatly within the houses of their marriages.

[[first-chronicles-4-39]]
^39^ And they set out, so that they might enter into Gedor, as far as the eastern valley, and so that they might seek pastures for their flocks.

[[first-chronicles-4-40]]
^40^ And they found fat and very good pastures, and a very wide and quiet and fruitful land, in which some from the stock of Ham had lived before.

[[first-chronicles-4-41]]
^41^ So then, those whose names have been written above, went forth in the days of Hezekiah, the king of Judah. And they struck down the inhabitants who had been found there with their dwellings. And they wiped them out, even to the present day. And they lived in place of them, because they found very fat pastures there.

[[first-chronicles-4-42]]
^42^ Also, some of the sons of Simeon, five hundred men, went away to mount Seir, having as leaders Pelatiah and Neariah and Rephaiah and Uzziel, the sons of Ishi.

[[first-chronicles-4-43]]
^43^ And they struck down the remnant of the Amalekites, those who had been able to escape, and they lived there in place of them, even to this day.


[[first-chronicles-5]]
== Chapter 5

[[first-chronicles-5-1]]
^1^ Also, there were the sons of Reuben, the firstborn of Israel. For indeed, he was his firstborn, but when he had violated the bed of his father, his right as firstborn was given to the sons of Joseph, the son of Israel, and he was not reputed as firstborn.

[[first-chronicles-5-2]]
^2^ Moreover, Judah, who was strongest among his brothers, from his stock leaders sprung up, but the right of firstborn was reputed to Joseph.

[[first-chronicles-5-3]]
^3^ So then, the sons of Reuben, the firstborn of Israel, were Hanoch and Pallu, Hezron and Carmi.

[[first-chronicles-5-4]]
^4^ The sons of Joel: Shemaiah his son, Gog his son, Shimei his son,

[[first-chronicles-5-5]]
^5^ Micah his son, Reaiah his son, Baal his son,

[[first-chronicles-5-6]]
^6^ Beerah his son, whom Tilgath-pilneser, the king of the Assyrians, led away captive, and he was a leader in the tribe of Reuben.

[[first-chronicles-5-7]]
^7^ Now his brothers and all his kindred, when they were being numbered according to their families, had as leaders Jeiel and Zechariah.

[[first-chronicles-5-8]]
^8^ Now Bela, the son of Azaz, the son of Shema, the son of Joel, lived in Aroer, as far as Nebo and Baalmeon.

[[first-chronicles-5-9]]
^9^ And he lived toward the eastern region, as far as the entrance to the wilderness and the river Euphrates. For indeed, they possessed a great number of cattle in the land of Gilead.

[[first-chronicles-5-10]]
^10^ Then, in the days of Saul, they battled against the Hagarites and put them to death. And they lived in place of them, in their dwellings, throughout the entire region that looks to the east of Gilead.

[[first-chronicles-5-11]]
^11^ Truly, the sons of Gad lived in the opposite region from them, in the land of Bashan, as far as Salecah:

[[first-chronicles-5-12]]
^12^ Joel the head, and Shapham the second, then Janai and Shaphat, in Bashan.

[[first-chronicles-5-13]]
^13^ Truly, their brothers, according to the houses of their kindred, were: Michael, and Meshullam, and Sheba, and Jorai, and Jacan, and Zia, and Eber, seven.

[[first-chronicles-5-14]]
^14^ These were the sons of Abihail, the son of Huri, the son of Jaroah, the son of Gilead, the son of Michael, the son of Jeshishai, the son of Jahdo, the son of Buz,

[[first-chronicles-5-15]]
^15^ along with their brothers, the sons of Abdiel, the son of Guni, the leader of the house, in their families,

[[first-chronicles-5-16]]
^16^ And they lived in Gilead, and in Bashan and its towns, and in all the suburbs of Sharon, as far as the borders.

[[first-chronicles-5-17]]
^17^ All these were numbered in the days of Jotham, the king of Judah, and in the days of Jeroboam, the king of Israel:

[[first-chronicles-5-18]]
^18^ the sons of Reuben, and of Gad, and the one half tribe of Manasseh, men of war, carrying shields and swords, and bending the bow, and trained for battle, forty-four thousand and seven hundred sixty, advancing to the fight.

[[first-chronicles-5-19]]
^19^ They struggled against the Hagarites, yet truly the Jetureans, and Naphish, and Nodab offered assistance to them.

[[first-chronicles-5-20]]
^20^ And the Hagarites were delivered into their hands, and all who were with them. For they called upon God while they did battle. And he heeded them, because they had trusted in him.

[[first-chronicles-5-21]]
^21^ And they seized all that they possessed, of camels fifty thousand, and of sheep two hundred fifty thousand, and of donkeys two thousand, and of men one hundred thousand lives.

[[first-chronicles-5-22]]
^22^ And many fell down wounded. For it was a war of the Lord. And they lived in place of them, until the transmigration.

[[first-chronicles-5-23]]
^23^ Also, the sons of the one half tribe of Manasseh possessed the land, from the parts of Bashan as far as Baal, Hermon, and Sanir, and Mount Hermon. For certainly, their number was immense.

[[first-chronicles-5-24]]
^24^ And these were leaders of the house of their kindred: Epher, and Ishi, and Eliel, and Azriel, and Jeremiah, and Hodaviah, and Jahdiel, very valiant and powerful men, and renowned leaders in their families.

[[first-chronicles-5-25]]
^25^ But they abandoned the God of their fathers, and they fornicated after the gods of the peoples of the land, whom God took away before them.

[[first-chronicles-5-26]]
^26^ And so the God of Israel stirred up the spirit of Pul, the king of the Assyrians, and the spirit of Tilgath-pilneser, the king of Assur. And he took away Reuben, and Gad, and the one half tribe of Manasseh. And he led them to Halah, and to Habor, and to Hara, and to the river of Gozan, even to this day.


[[first-chronicles-6]]
== Chapter 6

[[first-chronicles-6-1]]
^1^ The sons of Levi: Gershom, Kohath, and Merari.

[[first-chronicles-6-2]]
^2^ The sons of Kohath: Amram, Izhar, Hebron, and Uzziel.

[[first-chronicles-6-3]]
^3^ The sons of Amram: Aaron, Moses, and Miriam. The sons of Aaron: Nadab and Abihu, Eleazar and Ithamar.

[[first-chronicles-6-4]]
^4^ Eleazar conceived Phinehas, and Phinehas conceived Abishua.

[[first-chronicles-6-5]]
^5^ Truly, Abishua conceived Bukki, and Bukki conceived Uzzi.

[[first-chronicles-6-6]]
^6^ Uzzi conceived Zerahiah, and Zerahiah conceived Meraioth.

[[first-chronicles-6-7]]
^7^ Then Meraioth conceived Amariah, and Amariah conceived Ahitub.

[[first-chronicles-6-8]]
^8^ Ahitub conceived Zadok, and Zadok conceived Ahimaaz.

[[first-chronicles-6-9]]
^9^ Ahimaaz conceived Azariah; Azariah conceived Johanan.

[[first-chronicles-6-10]]
^10^ Johanan conceived Azariah. He is the one who executed the priestly office in the house that Solomon built in Jerusalem.

[[first-chronicles-6-11]]
^11^ Now Azariah conceived Amariah, and Amariah conceived Ahitub.

[[first-chronicles-6-12]]
^12^ Ahitub conceived Zadok, and Zadok conceived Shallum.

[[first-chronicles-6-13]]
^13^ Shallum conceived Hilkiah, and Hilkiah conceived Azariah.

[[first-chronicles-6-14]]
^14^ Azariah conceived Seraiah, and Seraiah conceived Jehozadak.

[[first-chronicles-6-15]]
^15^ Now Jehozadak departed, when the Lord took away Judah and Jerusalem, by the hands of Nebuchadnezzar.

[[first-chronicles-6-16]]
^16^ So the sons of Levi were Gershom, Kohath, and Merari.

[[first-chronicles-6-17]]
^17^ And these are the names of the sons of Gershom: Libni and Shimei.

[[first-chronicles-6-18]]
^18^ The sons of Kohath: Amram, and Izhar, and Hebron, and Uzziel.

[[first-chronicles-6-19]]
^19^ The sons of Merari: Mahli and Mushi. And so these are the kindred of Levi, according to their families.

[[first-chronicles-6-20]]
^20^ Of Gershom: Libni his son, Jahath his son, Zimmah his son,

[[first-chronicles-6-21]]
^21^ Joah his son, Iddo his son, Zerah his son, Jeatherai his son.

[[first-chronicles-6-22]]
^22^ The sons of Kohath: Amminadab his son, Korah his son, Assir his son,

[[first-chronicles-6-23]]
^23^ Elkanah his son, Ebiasaph his son, Assir his son,

[[first-chronicles-6-24]]
^24^ Tahath his son, Uriel his son, Uzziah his son, Shaul his son.

[[first-chronicles-6-25]]
^25^ The sons of Elkanah: Amasai and Ahimoth

[[first-chronicles-6-26]]
^26^ and Elkanah. The sons of Elkanah: Zophai his son, Nahath his son,

[[first-chronicles-6-27]]
^27^ Eliab his son, Jeroham his son, Elkanah his son.

[[first-chronicles-6-28]]
^28^ The sons of Samuel: Vasseni the firstborn, and Abijah.

[[first-chronicles-6-29]]
^29^ Now the sons of Merari were: Mahli, Libni his son, Shimei his son, Uzzah his son,

[[first-chronicles-6-30]]
^30^ Shimea his son, Haggiah his son, Asaiah his son.

[[first-chronicles-6-31]]
^31^ These are the ones whom David appointed over the singing men in the house of the Lord, in the place where the ark was located.

[[first-chronicles-6-32]]
^32^ And they ministered before the tabernacle of the testimony with singing, until Solomon built the house of the Lord in Jerusalem. And they would stand according to their order in the ministry.

[[first-chronicles-6-33]]
^33^ Truly, these are the ones who were assisting, with their sons, from the sons of Kohath: the singer Heman, the son of Joel, the son of Samuel,

[[first-chronicles-6-34]]
^34^ the son of Elkanah, the son of Jeroham, the son of Eliel, the son of Toah,

[[first-chronicles-6-35]]
^35^ the son of Zuph, the son of Elkanah, the son of Mahath, the son of Amasai,

[[first-chronicles-6-36]]
^36^ the son of Elkanah, the son of Joel, the son of Azariah, the son of Zephaniah,

[[first-chronicles-6-37]]
^37^ the son of Tahath, the son of Assir, the son of Ebiasaph, the son of Korah,

[[first-chronicles-6-38]]
^38^ the son of Izhar, the son of Kohath, the son of Levi, the son of Israel.

[[first-chronicles-6-39]]
^39^ And there was also his brother, Asaph, who was standing at his right, Asaph, the son of Berechiah, the son of Shimea,

[[first-chronicles-6-40]]
^40^ the son of Michael, the son of Baaseiah, the son of Malchijah,

[[first-chronicles-6-41]]
^41^ the son of Ethni, the son of Zerah, the son of Adaiah,

[[first-chronicles-6-42]]
^42^ the son of Ethan, the son of Zimmah, the son of Shimei,

[[first-chronicles-6-43]]
^43^ the son of Jahath, the son of Gershom, the son of Levi.

[[first-chronicles-6-44]]
^44^ Now the sons of Merari, their brothers, were on the left: Ethan, the son of Kishi, the son of Abdi, the son of Malluch,

[[first-chronicles-6-45]]
^45^ the son of Hashabiah, the son of Amaziah, the son of Hilkiah,

[[first-chronicles-6-46]]
^46^ the son of Amzi, the son of Boni, the son of Shemer,

[[first-chronicles-6-47]]
^47^ the son of Mahli, the son of Mushi, the son of Merari, the son of Levi.

[[first-chronicles-6-48]]
^48^ There were also their brothers, Levites who were appointed for every ministry of the tabernacle of the house of the Lord.

[[first-chronicles-6-49]]
^49^ Truly, Aaron and his sons were burning offerings upon the altar of holocausts and upon the altar of incense, for the entire work of the Holy of Holies, and to pray on behalf of Israel, in accord with all the things that Moses, the servant of God, had instructed.

[[first-chronicles-6-50]]
^50^ Now these are the sons of Aaron: Eleazar his son, Phinehas his son, Abishua his son,

[[first-chronicles-6-51]]
^51^ Bukki his son, Uzzi his son, Zerahiah his son,

[[first-chronicles-6-52]]
^52^ Meraioth his son, Amariah his son, Ahitub his son,

[[first-chronicles-6-53]]
^53^ Zadok his son, Ahimaaz his son.

[[first-chronicles-6-54]]
^54^ And these are their habitations according to the villages and confines, specifically of the sons of Aaron, according to the kindred of the Kohathites. For it fell to them by lot.

[[first-chronicles-6-55]]
^55^ And so, they gave Hebron, in the land of Judah, and its suburbs all around, to them,

[[first-chronicles-6-56]]
^56^ but they gave the fields of the city, and the villages, to Caleb, the son of Jephunneh.

[[first-chronicles-6-57]]
^57^ Then, to the sons of Aaron, they gave the cities of refuge: Hebron, and Libnah with its suburbs,

[[first-chronicles-6-58]]
^58^ also Jattir and Eshtemoa with their suburbs, then also Hilen and Debir with their suburbs,

[[first-chronicles-6-59]]
^59^ as well as Ashan and Beth-shemesh with their suburbs.

[[first-chronicles-6-60]]
^60^ And from the tribe of Benjamin: Geba with its suburbs, and Alemeth with its suburbs, as well as Anathoth with its suburbs. All the cities throughout their kindred were thirteen.

[[first-chronicles-6-61]]
^61^ Now to the sons of Kohath, those remaining from their kindred, they gave ten cities, from the one half tribe of Manasseh, as a possession;

[[first-chronicles-6-62]]
^62^ and to the sons of Gershom, according to their families, from the tribe of Issachar, and from the tribe of Asher, and from the tribe of Naphtali, and from the tribe Manasseh in Bashan: thirteen cities.

[[first-chronicles-6-63]]
^63^ Then to the sons of Merari, according to their families, from the tribe of Reuben, and from the tribe of Gad, and from the tribe of Zebulun, they gave by lot twelve cities.

[[first-chronicles-6-64]]
^64^ Also, the sons of Israel gave, to the Levites, cities and their suburbs,

[[first-chronicles-6-65]]
^65^ and they gave them by lot, out of the tribe of the sons of Judah, and out of the tribe of the sons of Simeon, and out of the tribe of the sons of Benjamin, these cities, which they called by their names.

[[first-chronicles-6-66]]
^66^ And for those who were from the kindred of the sons of Kohath, the cities with their borders were from the tribe of Ephraim.

[[first-chronicles-6-67]]
^67^ Then they gave to them the cities of refuge: Shechem with its suburbs on mount Ephraim, and Gezer with its suburbs,

[[first-chronicles-6-68]]
^68^ as well as Jokmeam with its suburbs, and Beth-horon similarly,

[[first-chronicles-6-69]]
^69^ and indeed Hilen with its suburbs, and Gath Rimmon in the same manner.

[[first-chronicles-6-70]]
^70^ Then too, out of the one half tribe of Manasseh: Aner and its suburbs, Bileam and its suburbs; these in particular went to those who were remaining from the kindred of the sons of Kohath.

[[first-chronicles-6-71]]
^71^ And to the sons of Gershom, from the kindred of the one half tribe of Manasseh: Golan, in Bashan, and its suburbs, and Ashtaroth with its suburbs;

[[first-chronicles-6-72]]
^72^ from the tribe of Issachar: Kedesh and its suburbs, and Daberath with its suburbs,

[[first-chronicles-6-73]]
^73^ as well as Ramoth and its suburbs, and Anem with its suburbs;

[[first-chronicles-6-74]]
^74^ truly, from the tribe of Asher: Mashal with its suburbs, and Abdon similarly;

[[first-chronicles-6-75]]
^75^ as well as Hukkok and its suburbs, and Rehob with its suburbs;

[[first-chronicles-6-76]]
^76^ moreover, from the tribe of Naphtali: Kedesh in Galilee and its suburbs, Hammon with its suburbs, and Kiriathaim and its suburbs.

[[first-chronicles-6-77]]
^77^ Then to the remaining sons of Merari, from the tribe of Zebulun: Rimmono and its suburbs, and Tabor with its suburbs;

[[first-chronicles-6-78]]
^78^ and also, across the Jordan opposite Jericho, facing the east of the Jordan, from the tribe of Reuben: Bezer in the wilderness with its suburbs, and Jahzah with its suburbs;

[[first-chronicles-6-79]]
^79^ as well as Kedemoth and its suburbs, and Mephaath with its suburbs;

[[first-chronicles-6-80]]
^80^ indeed also, from the tribe of Gad: Ramoth in Gilead and its suburbs, and Mahanaim with its suburbs;

[[first-chronicles-6-81]]
^81^ then too, Heshbon with its suburbs, and Jazer with its suburbs.


[[first-chronicles-7]]
== Chapter 7

[[first-chronicles-7-1]]
^1^ Now the sons of Issachar were Tola and Puah, Jashub and Shimron, four.

[[first-chronicles-7-2]]
^2^ The sons of Tola: Uzzi, and Rephaiah, and Jeriel, and Jahmai, and Ibsam, and Shemuel, leaders according to the houses of their kindred. From the stock of Tola, there were numbered, in the days of David, twenty-two thousand six hundred very strong men.

[[first-chronicles-7-3]]
^3^ The sons of Uzzi: Izrahiah, from whom were born: Michael, and Obadiah, and Joel, and Isshiah; all five were leaders.

[[first-chronicles-7-4]]
^4^ And with them, by their families and peoples, there were thirty-six thousand very strong men, girded for battle. And they had many wives and children.

[[first-chronicles-7-5]]
^5^ Also, their brothers, throughout all the kindred of Issachar, were numbered as eighty-seven thousand, very fit for battle.

[[first-chronicles-7-6]]
^6^ The sons of Benjamin: Bela, and Becher, and Jediael, three.

[[first-chronicles-7-7]]
^7^ The sons of Bela: Ezbon, and Uzzi, and Uzziel, and Jerimoth and Iri, five leaders of families, also very fit for battle; and their number was twenty-two thousand thirty-four.

[[first-chronicles-7-8]]
^8^ Now the sons of Becher: Zemirah, and Joash, and Eliezer, and Elioenai, and Omri, and Jeremoth, and Abijah, and Anathoth, and Alemeth: all these were sons of Becher.

[[first-chronicles-7-9]]
^9^ And they were numbered according to their families, by the leaders of their kindred, very strong in warfare, twenty thousand and two hundred.

[[first-chronicles-7-10]]
^10^ And the sons of Jediael: Bilhan, and the sons of Bilhan: Jeush, and Benjamin, and Ehud, and Chenaanah, and Zethan, and Tarshish, and Ahishahar.

[[first-chronicles-7-11]]
^11^ All these were sons of Jediael, the leaders of their kindred, very strong men, seventeen thousand and two hundred, going forth to battle.

[[first-chronicles-7-12]]
^12^ Also, Shuppim and Huppim, the sons of Ir; and Hushim, sons of Aher.

[[first-chronicles-7-13]]
^13^ Then the sons of Naphtali: Jahziel, and Guni, and Jezer, and Shallum, sons of Bilhah.

[[first-chronicles-7-14]]
^14^ Also, the son of Manasseh: Asriel. And his concubine, a Syrian, bore Machir, the father of Gilead.

[[first-chronicles-7-15]]
^15^ Now Machir took wives for his sons, Huppim and Shuppim. And he had a sister named Maacah; but the name of the second was Zelophehad, and daughters were born to Zelophehad.

[[first-chronicles-7-16]]
^16^ And Maacah, the wife of Machir, bore a son, and she called his name Peresh. And the name of his brother was Sheresh. And his sons were Ulam and Rakem.

[[first-chronicles-7-17]]
^17^ Then the son of Ulam: Bedan. These are the sons of Gilead, the son of Machir, the son of Manasseh.

[[first-chronicles-7-18]]
^18^ And his sister, Regina, bore Ishhod, and Abiezer, and Mahlah.

[[first-chronicles-7-19]]
^19^ Now the sons of Shemida were Ahian, and Shechem, and Likhi and Aniam.

[[first-chronicles-7-20]]
^20^ And the sons of Ephraim: Shuthelah, Bered his son, Tahath his son, Eleadah his son, Tahath his son, whose son was Zabad,

[[first-chronicles-7-21]]
^21^ and his son was Shuthelah, and his son was Ezer, and also Elead. But the men indigenous to Gath killed them, because they had descended to invade their possessions.

[[first-chronicles-7-22]]
^22^ And so their father, Ephraim, mourned for many days; and his brothers arrived, so that they might console him.

[[first-chronicles-7-23]]
^23^ And he entered to his wife; she conceived and bore a son. And he called his name Beriah, because he rose up during a time of evil for his house.

[[first-chronicles-7-24]]
^24^ Now his daughter was Sheerah, who built lower and upper Beth-horon, and also Uzzen-sheerah.

[[first-chronicles-7-25]]
^25^ And Rephah was his son, and Resheph, and Telah, from whom was born Tahan,

[[first-chronicles-7-26]]
^26^ who conceived Ladan. And his son was Ammihud, who conceived Elishama,

[[first-chronicles-7-27]]
^27^ from whom was born Nun, who had Joshua as a son.

[[first-chronicles-7-28]]
^28^ Now their possessions and habitations were: Bethel with her daughters, and toward the east, Naaran, and toward the western region, Gezer and her daughters, as well as Shechem with her daughters, as far as Ayyah with her daughters;

[[first-chronicles-7-29]]
^29^ also, beside the sons of Manasseh, Bethshean and her daughters, Taanach and her daughters, Megiddo and her daughters, Dor and her daughters. In these places, there lived the sons of Joseph, the son of Israel.

[[first-chronicles-7-30]]
^30^ The sons of Asher: Imnah, and Ishvah, and Ishvi, and Beriah, and Serah their sister.

[[first-chronicles-7-31]]
^31^ And the sons of Beriah: Heber, and Malchiel, the same is the father of Birzaith.

[[first-chronicles-7-32]]
^32^ Now Heber conceived Japhlet, and Shomer, and Hotham, and their sister Shua.

[[first-chronicles-7-33]]
^33^ The sons of Japhlet: Pasach, and Bimhal, and Ashvath; these are the sons of Japhlet.

[[first-chronicles-7-34]]
^34^ Then the sons of Shomer: Ahi, and Rohgah, and Jehubbah, and Aram.

[[first-chronicles-7-35]]
^35^ And the sons of Helem, his brother: Zophah, and Imna, and Shelesh, and Amal.

[[first-chronicles-7-36]]
^36^ The sons of Zophah: Suah, Harnepher, and Shual, and Beri, and Imrah,

[[first-chronicles-7-37]]
^37^ Bezer, and Hod, and Shamma, and Shilshah, and Ithran, and Beera.

[[first-chronicles-7-38]]
^38^ The sons of Jether: Jephunneh, and Pispa, and Ara.

[[first-chronicles-7-39]]
^39^ Then the sons of Ulla: Arah, and Hanniel, and Rizia.

[[first-chronicles-7-40]]
^40^ All these were sons of Asher, the leaders of families, elect and very strong rulers among rulers. And the number of those who were of an age that was fit for warfare was twenty-six thousand.


[[first-chronicles-8]]
== Chapter 8

[[first-chronicles-8-1]]
^1^ Now Benjamin conceived Bela as his firstborn, Ashbel the second, Aharah the third,

[[first-chronicles-8-2]]
^2^ Nohah the fourth, and Rapha the fifth.

[[first-chronicles-8-3]]
^3^ And the sons of Bela were: Addar, and Gera, and Abihud,

[[first-chronicles-8-4]]
^4^ as well as Abishua, and Naaman, and Ahoah,

[[first-chronicles-8-5]]
^5^ then also Gera, and Shephuphan, and Huram.

[[first-chronicles-8-6]]
^6^ These are the sons of Ehud, leaders of the kindred living in Geba, who were moved away to Manahath.

[[first-chronicles-8-7]]
^7^ And Naaman, and Ahijah, and Gera, he also moved them away; and he conceived Uzza and Ahihud.

[[first-chronicles-8-8]]
^8^ Then Shaharaim conceived, in the region of Moab, after he sent away Hushim and Baara, his wives;

[[first-chronicles-8-9]]
^9^ and so, of his wife Hodesh, he conceived Jobab, and Zibia, and Mesha, and Malcam,

[[first-chronicles-8-10]]
^10^ and also Jeuz and Sachia, and Mirmah. These were his sons, the leaders of their families.

[[first-chronicles-8-11]]
^11^ Truly, of Hushim he conceived Abitub and Elpaal.

[[first-chronicles-8-12]]
^12^ And the sons of Elpaal were Eber, and Misham, and Shemed, who built Ono and Lod and its daughters.

[[first-chronicles-8-13]]
^13^ Now Beriah and Shema were leaders of their families living in Aijalon; these put to flight the inhabitants of Gath.

[[first-chronicles-8-14]]
^14^ And Ahio, and Shashak, and Jeremoth,

[[first-chronicles-8-15]]
^15^ and Zebadiah, and Arad, and Eder,

[[first-chronicles-8-16]]
^16^ as well as Michael, and Ishpah, and Joha, were the sons of Beriah.

[[first-chronicles-8-17]]
^17^ Then Zebadiah, and Meshullam, and Hizki, and Heber,

[[first-chronicles-8-18]]
^18^ and Ishmerai, and Izliah, and Jobab were the sons of Elpaal.

[[first-chronicles-8-19]]
^19^ Then Jakim, and Zichri, and Zabdi,

[[first-chronicles-8-20]]
^20^ and Elienai, and Zillethai, and Eliel,

[[first-chronicles-8-21]]
^21^ and Adaiah, and Beraiah, and Shimrath were the sons of Shimei.

[[first-chronicles-8-22]]
^22^ Then Ishpan, and Eber, and Eliel,

[[first-chronicles-8-23]]
^23^ and Abdon, and Zichri, and Hanan,

[[first-chronicles-8-24]]
^24^ and Hananiah, and Elam, and Anthothijah,

[[first-chronicles-8-25]]
^25^ and Iphdeiah, and Penuel were the sons of Shashak.

[[first-chronicles-8-26]]
^26^ Then Shamsherai, and Shehariah and Athaliah,

[[first-chronicles-8-27]]
^27^ and Jaareshiah, and Elijah, and Zichri were the sons of Jeroham.

[[first-chronicles-8-28]]
^28^ These were the patriarchs and leaders of the families who were living in Jerusalem.

[[first-chronicles-8-29]]
^29^ Now in Gibeon, there lived Jeiel, the father of Gibeon; and the name of his wife was Maacah,

[[first-chronicles-8-30]]
^30^ and his firstborn son was Abdon, and then Zur, and Kish, and Baal, and Nadab,

[[first-chronicles-8-31]]
^31^ and Gedor, and Ahio, and Zecher, and Mikloth.

[[first-chronicles-8-32]]
^32^ And Mikloth conceived Shimeah. And they lived opposite their brothers in Jerusalem, with their brothers.

[[first-chronicles-8-33]]
^33^ Now Ner conceived Kish, and Kish conceived Saul. Then Saul conceived Jonathan, and Malchishua, and Abinadab, and Eshbaal.

[[first-chronicles-8-34]]
^34^ And the son of Jonathan was Meribbaal; and Meribbaal conceived Micah.

[[first-chronicles-8-35]]
^35^ The sons of Micah were Pithon, and Melech, and Tarea, and Ahaz.

[[first-chronicles-8-36]]
^36^ And Ahaz conceived Jehoaddah. And Jehoaddah conceived Alemeth, and Azmaveth, and Zimri. And Zimri conceived Moza.

[[first-chronicles-8-37]]
^37^ And Moza conceived Binea, whose son was Raphah, of whom was born Eleasah, who conceived Azel.

[[first-chronicles-8-38]]
^38^ Now there were six sons for Azel, whose names were Azrikam, Bocheru, Ishmael, Sheariah, Obadiah, and Hanan. All these were the sons of Azel.

[[first-chronicles-8-39]]
^39^ Then the sons of Eshek, his brother, were Ulam the firstborn, and Jeush the second, and Eliphelet the third.

[[first-chronicles-8-40]]
^40^ And the sons of Ulam were very robust men, drawing the bow with great strength. And they had many sons and grandsons, even to one hundred fifty. All these were sons of Benjamin.


[[first-chronicles-9]]
== Chapter 9

[[first-chronicles-9-1]]
^1^ And so, all of Israel was numbered. And the sum of them was written in the book of the kings of Israel and of Judah. And they were taken away to Babylon because of their transgression.

[[first-chronicles-9-2]]
^2^ Now the first who lived in their possessions and in their cities were Israel, and the priests, and the Levites, and the temple servants.

[[first-chronicles-9-3]]
^3^ Staying in Jerusalem were some from the sons of Judah, and from the sons of Benjamin, and also from the sons of Ephraim and of Manasseh:

[[first-chronicles-9-4]]
^4^ Uthai, the son of Ammihud, the son of Omri, the son of Imri, the son of Bani, from the sons of Perez, the son of Judah.

[[first-chronicles-9-5]]
^5^ And from Shiloni: Asaiah the firstborn, and his sons.

[[first-chronicles-9-6]]
^6^ Then from the sons of Zerah: Jeuel, and their brothers, six hundred ninety.

[[first-chronicles-9-7]]
^7^ And from the sons of Benjamin: Sallu, the son of Meshullam, the son of Hodaviah, the son of Hassenuah;

[[first-chronicles-9-8]]
^8^ and Ibneiah, the son of Jeroham; and Elah, the son of Uzzi, the son of Michri; and Meshullam, the son of Shephatiah, the son of Reuel, the son of Ibnijah;

[[first-chronicles-9-9]]
^9^ and their brothers according to their families, nine hundred fifty-six. All these were leaders of their kindred, according to the houses of their fathers.

[[first-chronicles-9-10]]
^10^ And from the priests: Jedaiah, Jehoiarib, and Jachin;

[[first-chronicles-9-11]]
^11^ and also Azariah, the son of Hilkiah, the son of Meshullam, the son of Zadok, the son of Meraioth, the son of Ahitub, the high priest of the house of God;

[[first-chronicles-9-12]]
^12^ then Adaiah, the son of Jeroham, the son of Pashhur, the son of Malchijah; and Maasai, the son of Adiel, the son of Jahzerah, the son of Meshullam, the son of Meshillemith, the son of Immer;

[[first-chronicles-9-13]]
^13^ and also their brothers, leaders according to their families, one thousand seven hundred sixty, very strong experienced men, for the work of the ministry in the house of God.

[[first-chronicles-9-14]]
^14^ Then from the Levites: Shemaiah, the son of Hasshub, the son of Azrikam, the son of Hashabiah, of the sons of Merari;

[[first-chronicles-9-15]]
^15^ and also Bakbakkar the carpenter; and Galal; and Mattaniah, the son of Mica, the son of Zichri, the son of Asaph;

[[first-chronicles-9-16]]
^16^ and Obadiah, the son of Shemaiah, the son of Galal, the son of Jeduthun; and Berechiah, the son of Asa, the son of Elkanah, who lived at the entrance to Netophah.

[[first-chronicles-9-17]]
^17^ Now the gatekeepers were Shallum, and Akkub, and Talmon, and Ahiman; and their brother Shallum was the leader.

[[first-chronicles-9-18]]
^18^ For until that time, at the gate of the king to the east, the sons of Levi served in their turns.

[[first-chronicles-9-19]]
^19^ Truly, Shallum, the son of Kore, the son of Ebiasaph, the son of Korah, with his brothers and his father’s house, these Korahites, were over the works of the ministry of keeping the vestibules of the tabernacle. And their families, in turns, were keepers of the entrance to the camp of the Lord.

[[first-chronicles-9-20]]
^20^ Now Phinehas, the son of Eleazar, was their ruler before the Lord.

[[first-chronicles-9-21]]
^21^ But Zechariah, the son of Meshelemiah, was the keeper of the gate of the tabernacle of the testimony.

[[first-chronicles-9-22]]
^22^ All these, chosen as porters for the gates, were two hundred twelve. And they were recorded in their own towns, those whom David, and the seer Samuel, appointed, in their faith,

[[first-chronicles-9-23]]
^23^ as with them, so also with their sons, at the gates of the house of the Lord and the tabernacle, by their turns.

[[first-chronicles-9-24]]
^24^ At the four directions, there were gatekeepers, that is, at the east, and at the west, and at the north, and at the south.

[[first-chronicles-9-25]]
^25^ Now their brothers were staying in the villages, and they arrived on their Sabbaths, from time to time.

[[first-chronicles-9-26]]
^26^ To these four Levites were entrusted the entire number of the gatekeepers, and they were over the chambers and storehouses of the house of the Lord.

[[first-chronicles-9-27]]
^27^ And they remained in their watches, on all sides of the temple of the Lord, so that, when the time had arrived, they might open the gates in the morning.

[[first-chronicles-9-28]]
^28^ Some from their kindred were also over the vessels of the ministry. For the vessels were both carried in and carried out according to number.

[[first-chronicles-9-29]]
^29^ Some of them also were entrusted with the equipment of the sanctuary; they were in charge of the fine wheat flour, and the wine, and the oil, and the frankincense, and the aromatics.

[[first-chronicles-9-30]]
^30^ Now the sons of the priests composed the ointments from the aromatics.

[[first-chronicles-9-31]]
^31^ And Mattithiah, a Levite, the firstborn of Shallum the Korahite, was in charge of those things that were cooked in a frying pan.

[[first-chronicles-9-32]]
^32^ Now some of the sons of Kohath, their brothers, were over the bread of the presence, so that they might continually prepare it new for each Sabbath.

[[first-chronicles-9-33]]
^33^ These are the leaders of the singing men, according to the families of the Levites, who were dwelling in the chambers, so that they might carry out their ministry continually, day and night.

[[first-chronicles-9-34]]
^34^ The heads of the Levites, leaders according to their families, abode in Jerusalem.

[[first-chronicles-9-35]]
^35^ Now in Gibeon, there lived Jeiel, the father of Gibeon, and the name of his wife was Maacah.

[[first-chronicles-9-36]]
^36^ His firstborn son was Abdon, and then Zur, and Kish, and Baal, and Ner, and Nadab,

[[first-chronicles-9-37]]
^37^ as well as Gedor, and Ahio, and Zechariah, and Mikloth.

[[first-chronicles-9-38]]
^38^ Then Mikloth conceived Shimeam. These lived opposite their brothers in Jerusalem, with their brothers.

[[first-chronicles-9-39]]
^39^ Now Ner conceived Kish, and Kish conceived Saul. And Saul conceived Jonathan, and Malchishua, and Abinadab, and Eshbaal.

[[first-chronicles-9-40]]
^40^ And the son of Jonathan was Meribbaal. And Meribbaal conceived Micah.

[[first-chronicles-9-41]]
^41^ Now the sons of Micah were Pithon, and Melech, and Tahrea, and Ahaz.

[[first-chronicles-9-42]]
^42^ And Ahaz conceived Jarah. And Jarah conceived Alemeth, and Azmaveth, and Zimri. Then Zimri conceived Moza.

[[first-chronicles-9-43]]
^43^ Truly, Moza conceived Binea, whose son, Rephaiah, conceived Eleasah, from of whom was born Azel.

[[first-chronicles-9-44]]
^44^ Now Azel had six sons, whose names are: Azrikam, Bocheru, Ishmael, Sheariah, Obadiah, Hanan. These are the sons of Azel.


[[first-chronicles-10]]
== Chapter 10

[[first-chronicles-10-1]]
^1^ Now the Philistines were fighting against Israel, and the men of Israel fled from the Philistines, and they fell down wounded on mount Gilboa.

[[first-chronicles-10-2]]
^2^ And when the Philistines had drawn near, pursuing Saul and his sons, they struck down Jonathan, and Abinadab, and Malchishua, the sons of Saul.

[[first-chronicles-10-3]]
^3^ And the battle grew heavy against Saul. And the archers found him, and they wounded him with arrows.

[[first-chronicles-10-4]]
^4^ And Saul said to his armor bearer: “Unsheathe your sword and kill me. Otherwise, these uncircumcised men may arrive and mock me.” But his armor bearer was not willing, having been struck with fear. And so, Saul took hold of his sword, and he fell upon it.

[[first-chronicles-10-5]]
^5^ And when his armor bearer had seen this, specifically, that Saul was dead, he now fell on his sword also, and he died.

[[first-chronicles-10-6]]
^6^ Therefore, Saul died, and his three sons passed away, and his entire house fell, together.

[[first-chronicles-10-7]]
^7^ And when the men of Israel who were living in the plains had seen this, they fled. And since Saul and his sons were dead, they abandoned their cities and were dispersed, here and there. And the Philistines arrived and lived among them.

[[first-chronicles-10-8]]
^8^ Then, on the next day, when the Philistines were taking away the spoils of the slain, they found Saul and his sons, lying on mount Gilboa.

[[first-chronicles-10-9]]
^9^ And when they had despoiled him, and had cut off his head, and had stripped his armor, they sent these things into their land, so that they would be carried around and displayed in the temples of the idols and to the people.

[[first-chronicles-10-10]]
^10^ But his armor they consecrated in the shrine of their god, and his head they affixed in the temple of Dagon.

[[first-chronicles-10-11]]
^11^ When the men of Jabesh Gilead had heard this, specifically, all that the Philistines had done concerning Saul,

[[first-chronicles-10-12]]
^12^ each one of the valiant men rose up, and they took the bodies of Saul and of his sons. And they brought them to Jabesh. And they buried their bones under the oak that was in Jabesh. And they fasted for seven days.

[[first-chronicles-10-13]]
^13^ Thus did Saul die for his iniquities, because he betrayed the commandment of the Lord which he had instructed, and did not keep it. And moreover, he even consulted a woman diviner;

[[first-chronicles-10-14]]
^14^ for he did not trust in the Lord. Because of this, he caused his death, and he transferred his kingdom to David, the son of Jesse.


[[first-chronicles-11]]
== Chapter 11

[[first-chronicles-11-1]]
^1^ Then all of Israel was gathered to David at Hebron, saying: “We are your bone and your flesh.

[[first-chronicles-11-2]]
^2^ Also, yesterday and the day before, when Saul still reigned, you were the one who led out and brought in Israel. For the Lord your God said to you: ‘You shall pasture my people Israel, and you shall be the leader over them.’ ”

[[first-chronicles-11-3]]
^3^ Therefore, all those greater by birth of Israel went to the king at Hebron. And David formed a pact with them before the Lord. And they anointed him king over Israel, in accord with the word of the Lord, which he spoke by the hand of Samuel.

[[first-chronicles-11-4]]
^4^ Then David and all of Israel went to Jerusalem. The same is Jebus, where the Jebusites, the inhabitants of the land, were.

[[first-chronicles-11-5]]
^5^ And those who were living in Jebus said to David: “You shall not enter here.” But David seized the stronghold of Zion, which is the city of David.

[[first-chronicles-11-6]]
^6^ And he said, “Whoever shall strike the Jebusites first, shall be ruler and commander.” And so Joab, the son of Zeruiah, ascended first, and he was made the leader.

[[first-chronicles-11-7]]
^7^ Then David lived in the stronghold, and for this reason it was called the City of David.

[[first-chronicles-11-8]]
^8^ And he built up the city all around, from Millo even to every side. But Joab built the rest of the city.

[[first-chronicles-11-9]]
^9^ And David continued advancing and increasing, and the Lord of hosts was with him.

[[first-chronicles-11-10]]
^10^ These are the leaders of the strong men of David, who assisted him, so that he would become king over all of Israel, in accord with the word of the Lord, which he spoke to Israel.

[[first-chronicles-11-11]]
^11^ And this is the number of the robust of David: Jashobeam, the son of a Hachmonite, leader among the thirty. He lifted up his spear over three hundred, who were wounded at one time.

[[first-chronicles-11-12]]
^12^ And after him, there was Eleazar, the son of his uncle, an Ahohite, who was among the three powerful ones.

[[first-chronicles-11-13]]
^13^ He was with David in Pasdammim, when the Philistines were gathered to that place for battle. Now the field of that region was full of barley, but the people had fled from the face of the Philistines.

[[first-chronicles-11-14]]
^14^ These men stood in the midst of the field, and they defended it. And when they had struck down the Philistines, the Lord gave a great salvation to his people.

[[first-chronicles-11-15]]
^15^ Then three from the thirty leaders descended to the rock where David was, to the cave of Adullam, when the Philistines had made camp in the Valley of the Rephaim.

[[first-chronicles-11-16]]
^16^ Now David was in a stronghold, and a garrison of the Philistines was in Bethlehem.

[[first-chronicles-11-17]]
^17^ And then David desired and said, “O if only someone would give me water from the well of Bethlehem, which is at the gate!”

[[first-chronicles-11-18]]
^18^ Therefore, these three broke through to the midst of the camp of the Philistines, and they drew water from the well of Bethlehem, which was at the gate. And they took it to David, so that he might drink. But he was not willing; and instead, he offered it as a libation to the Lord,

[[first-chronicles-11-19]]
^19^ saying: “Far be it from me, that I would do this in the sight of my God, and that I would drink the blood of these men. For at the peril of their own lives, they brought the water to me.” And for this reason, he was not willing to drink. The three most powerful accomplished these things.

[[first-chronicles-11-20]]
^20^ Also, Abishai, the brother of Joab, was the leader of the three, and he lifted up his spear against three hundred, who were wounded. And he was most renowned among the three,

[[first-chronicles-11-21]]
^21^ and he was famous among the second three and their leader. Yet truly, he did not reach as far as the first three.

[[first-chronicles-11-22]]
^22^ Benaiah, the son of Jehoiada, from Kabzeel, was a very mature man, who had accomplished many deeds. He struck down the two lions of God from Moab. And he descended and killed a lion in the middle of a pit, in the time of snow.

[[first-chronicles-11-23]]
^23^ And he struck down an Egyptian man, whose stature was five cubits, and who had a spear like a weaver’s beam. And yet he descended to him with a staff. And he seized the spear that he was holding in his hand. And he killed him with his own spear.

[[first-chronicles-11-24]]
^24^ These things were done by Benaiah, the son of Jehoiada, who was most renowned among the three robust ones,

[[first-chronicles-11-25]]
^25^ the first among the thirty. Yet truly, he did not reach as far as the three. Then David placed him beside his ear.

[[first-chronicles-11-26]]
^26^ Moreover, the strongest men of the army were Asahel, the brother of Joab; and Elhanan, the son of his uncle, from Bethlehem;

[[first-chronicles-11-27]]
^27^ Shammoth, a Harorite; Helez, a Pelonite;

[[first-chronicles-11-28]]
^28^ Ira, the son of Ikkesh, a Tekoite; Abiezer, an Anathothite;

[[first-chronicles-11-29]]
^29^ Sibbecai, a Hushathite; Ilai, an Ahohite;

[[first-chronicles-11-30]]
^30^ Maharai, a Netophathite; Heled, the son of Baanah, a Netophathite;

[[first-chronicles-11-31]]
^31^ Ithai, the son of Ribai, from Gibeah, of the sons of Benjamin; Benaiah, a Pirathonite;

[[first-chronicles-11-32]]
^32^ Hurai, from the torrent Gaash; Abiel, an Arbathite; Azmaveth, a Baharumite; Eliahba, a Shaalbonite.

[[first-chronicles-11-33]]
^33^ The sons of Hashem, a Gizonite: Jonathan, the son of Shagee, a Hararite;

[[first-chronicles-11-34]]
^34^ Ahiam, the son of Sachar, a Hararite;

[[first-chronicles-11-35]]
^35^ Eliphal, the son of Ur;

[[first-chronicles-11-36]]
^36^ Hepher, a Mecherathite; Ahijah, a Pelonite;

[[first-chronicles-11-37]]
^37^ Hezro, a Carmelite; Naharai, the son of Ezbai;

[[first-chronicles-11-38]]
^38^ Joel, the brother of Nathan; Mibhar, the son of Hagri;

[[first-chronicles-11-39]]
^39^ Zelek, an Ammonite; Naarai, a Beerothite, the armor bearer of Joab, the son of Zeruiah;

[[first-chronicles-11-40]]
^40^ Ira, an Ithrite; Gareb, an Ithrite;

[[first-chronicles-11-41]]
^41^ Uriah, a Hittite; Zabad, the son of Ahlai;

[[first-chronicles-11-42]]
^42^ Adina, the son of Shiza, a Reubenite, the leader of the Reubenites, and thirty who were with him;

[[first-chronicles-11-43]]
^43^ Hanan, the son of Maacah; and Joshaphat, a Mithnite;

[[first-chronicles-11-44]]
^44^ Uzzia, an Ashterathite; Shama and Jeiel, the sons of Hotham, an Aroerite;

[[first-chronicles-11-45]]
^45^ Jediael, the son of Shimri; and Joha, his brother, a Tizite;

[[first-chronicles-11-46]]
^46^ Eliel, a Mahavite; and Jeribai and Joshaviah, the sons of Elnaam; and Ithmah, a Moabite; Eliel, and Obed, and Jaasiel from Mezobaite.


[[first-chronicles-12]]
== Chapter 12

[[first-chronicles-12-1]]
^1^ Also, these went to David at Ziklag, while he was still fleeing from Saul, the son of Kish. And they were very strong and distinguished fighters,

[[first-chronicles-12-2]]
^2^ bending the bow, and using either hand in casting stones with slings, and shooting arrows. From the brothers of Saul, out of Benjamin:

[[first-chronicles-12-3]]
^3^ the leader was Ahiezer, with Joash, sons of Shemaah from Gibeah, and Jeziel and Pelet, sons of Azmaveth, and Beracah and Jehu, from Anathoth.

[[first-chronicles-12-4]]
^4^ Also, there was Ishmaiah, from Gibeon, the strongest among the thirty and over the thirty; Jeremiah, and Jahaziel, and Johanan, and Jozabad, from Gederah;

[[first-chronicles-12-5]]
^5^ and Eluzai, and Jerimoth, and Bealiah, and Shemariah, and Shephatiah, the Haruphites;

[[first-chronicles-12-6]]
^6^ Elkanah, and Isshiah, and Azarel, and Joezer, and Jashobeam, from Carehim;

[[first-chronicles-12-7]]
^7^ and also Joelah and Zebadiah, sons of Jeroham, from Gedor.

[[first-chronicles-12-8]]
^8^ Then too, from Gad, there went over to David, when he was hiding in the desert, very robust men, who were excellent fighters, taking hold of shield and spear; their faces were like the faces of a lion, and they were swift like the roe deer upon the mountains.

[[first-chronicles-12-9]]
^9^ Ezer was the leader, Obadiah the second, Eliab the third,

[[first-chronicles-12-10]]
^10^ Mishmannah the fourth, Jeremiah the fifth,

[[first-chronicles-12-11]]
^11^ Attai the sixth, Eliel the seventh,

[[first-chronicles-12-12]]
^12^ Johanan the eighth, Elzabad the ninth,

[[first-chronicles-12-13]]
^13^ Jeremiah the tenth, Machbannai the eleventh.

[[first-chronicles-12-14]]
^14^ These were from the sons of Gad, leaders of the army. The least was in charge of one hundred soldiers, and the greatest was in charge of one thousand.

[[first-chronicles-12-15]]
^15^ These are the ones who crossed over the Jordan in the first month, when it is accustomed to overflow its banks. And they put to flight all those who were staying in the valleys, to the eastern region and to the west.

[[first-chronicles-12-16]]
^16^ Then some from Benjamin and from Judah also arrived at the stronghold where David was staying.

[[first-chronicles-12-17]]
^17^ And David went out to meet them, and he said: “If you have arrived peacefully, so as to be a help to me, may my heart be joined to you; but if to betray me to my adversaries, though I have no iniquity in my hands, may the God of our fathers see and judge.”

[[first-chronicles-12-18]]
^18^ Truly, the Spirit clothed Amasai, the leader among the thirty, and he said: “O David, we are yours! O son of Jesse, we are for you! Peace, peace to you, and peace to your helpers. For your God helps you.” Therefore, David received them, and he appointed them as leaders of troops.

[[first-chronicles-12-19]]
^19^ Moreover, some from Manasseh crossed over to David, when he went forth with the Philistines against Saul, so that he might fight. But he did not fight with them. For the leaders of the Philistines, taking counsel, sent him back, saying, “To the peril of our own heads, he will return to his lord, Saul.”

[[first-chronicles-12-20]]
^20^ And so, when he returned to Ziklag, some fled over to him from Manasseh: Adnah, and Jozabad, and Jediael, and Michael, and Adnah, and Jozabad, and Elihu, and Zillethai, leaders of thousands in Manasseh.

[[first-chronicles-12-21]]
^21^ These offered assistance to David against the robbers. For all were very strong men, and they became leaders in the army.

[[first-chronicles-12-22]]
^22^ Then, too, some came to David throughout each day, in order to help him, until they became a great number, like the army of God.

[[first-chronicles-12-23]]
^23^ Now this is the number of the leaders of the army who went to David when he was at Hebron, so that they might transfer the kingdom of Saul to him, in accord with the word of the Lord:

[[first-chronicles-12-24]]
^24^ the sons of Judah, carrying shield and spear, six thousand eight hundred, equipped for battle;

[[first-chronicles-12-25]]
^25^ from the sons of Simeon, very strong men for the fight, seven thousand one hundred;

[[first-chronicles-12-26]]
^26^ from the sons of Levi, four thousand six hundred;

[[first-chronicles-12-27]]
^27^ as well as Jehoiada, a leader from the stock of Aaron, and with him three thousand seven hundred;

[[first-chronicles-12-28]]
^28^ and then Zadok, a youth of distinguished qualities, and the house of his father, twenty-two leaders;

[[first-chronicles-12-29]]
^29^ and from the sons of Benjamin, brothers of Saul, three thousand, for still a great part of them were following the house of Saul.

[[first-chronicles-12-30]]
^30^ Then from the sons of Ephraim, there were twenty thousand eight hundred, very strong and robust men, renowned among their kindred.

[[first-chronicles-12-31]]
^31^ And out of the one half tribe of Manasseh, eighteen thousand, each by their names, went forth so that they might appoint David as king.

[[first-chronicles-12-32]]
^32^ Also, from the sons of Issachar, there were learned men, who knew each of the times, in order to anticipate what Israel ought to do, two hundred leaders. And all the remainder of the tribe were following their counsel.

[[first-chronicles-12-33]]
^33^ Then, from Zebulun, there were those who went forth to battle, and who were standing in a battle line, prepared with the weapons of warfare; these fifty thousand arrived to assist, without duplicity of heart.

[[first-chronicles-12-34]]
^34^ And from Naphtali, there were one thousand leaders; and with them were thirty-seven thousand, prepared with shield and spear.

[[first-chronicles-12-35]]
^35^ And then from Dan, there were twenty-eight thousand six hundred, ready for battle.

[[first-chronicles-12-36]]
^36^ And from Asher, there were forty thousand, going forth to fight, and summoned to the battle line.

[[first-chronicles-12-37]]
^37^ Then, across the Jordan, there were, from the sons of Reuben, and from Gad, and from the one half tribe of Manasseh, one hundred twenty thousand, prepared with the weapons of warfare.

[[first-chronicles-12-38]]
^38^ All these men of war, equipped for the fight, went with a perfect heart to Hebron, so that they might appoint David as king over all of Israel. Then, too, all the remainder of Israel were of one heart, so that they might make David king.

[[first-chronicles-12-39]]
^39^ And they were in that place with David for three days, eating and drinking. For their brothers had made preparations for them.

[[first-chronicles-12-40]]
^40^ Moreover, those who were near to them, even as far as Issachar, and Zebulun, and Naphtali, were bringing, on donkeys and camels and mules and oxen, bread for their provisions, with grain, dried figs, dried grapes, wine, oil, and oxen and sheep, with all abundance. For indeed, there was joy in Israel.


[[first-chronicles-13]]
== Chapter 13

[[first-chronicles-13-1]]
^1^ Then David took counsel with the tribunes, and the centurions, and all the leaders.

[[first-chronicles-13-2]]
^2^ And he said to the entire assembly of Israel: “If it pleases you, and if the words that I speak come from the Lord our God, let us send to the remainder of our brothers, in all the regions of Israel, and to the priests and Levites who live in the suburbs of the cities, so that they may gather to us.

[[first-chronicles-13-3]]
^3^ And let us bring back the ark of our God to us. For we did not seek it during the days of Saul.”

[[first-chronicles-13-4]]
^4^ And the entire multitude responded that it should be done. For the word had pleased all the people.

[[first-chronicles-13-5]]
^5^ Therefore, David gathered all of Israel, from Shihor of Egypt even to the entrance of Hamath, so as to bring the ark of God from Kiriath-jearim.

[[first-chronicles-13-6]]
^6^ And David ascended with all the men of Israel to the hill of Kiriath-jearim, which is in Judah, so that he might bring from there the ark of the Lord God, sitting upon the Cherubim, where his name is invoked.

[[first-chronicles-13-7]]
^7^ And they placed the ark of God upon a new cart from the house of Abinadab. Then Uzzah and his brother drove the cart.

[[first-chronicles-13-8]]
^8^ Now David and all of Israel were playing before God, with all of their ability, in songs, and with harps, and psalteries, and timbrels, and cymbals, and trumpets.

[[first-chronicles-13-9]]
^9^ And when they had arrived at the threshing floor of Chidon, Uzzah reached out his hand, so that he might support the ark. For indeed, the ox being wanton had caused it to incline a little.

[[first-chronicles-13-10]]
^10^ And so the Lord became angry against Uzzah. And he struck him down because he had touched the ark. And he died there before the Lord.

[[first-chronicles-13-11]]
^11^ And David was greatly saddened because the Lord had divided Uzzah. And he called that place ‘the Division of Uzzah,’ even to the present day.

[[first-chronicles-13-12]]
^12^ And then he feared God, at that time, saying: “How will I be able to bring in the ark of God to myself?”

[[first-chronicles-13-13]]
^13^ And for this reason, he did not bring it to himself, that is, into the City of David. Instead, he turned aside to the house of Obededom, the Gittite.

[[first-chronicles-13-14]]
^14^ Therefore, the ark of God dwelt in the house of Obededom for three months. And the Lord blessed his house and all that he had.


[[first-chronicles-14]]
== Chapter 14

[[first-chronicles-14-1]]
^1^ Also, Hiram, the king of Tyre, sent messengers to David, and cedar wood, and artisans of walls and of wood, so that they might build a house for him.

[[first-chronicles-14-2]]
^2^ And David realized that the Lord had confirmed him as king over Israel, and that his kingdom had been lifted up over his people Israel.

[[first-chronicles-14-3]]
^3^ Also, David took other wives in Jerusalem. And he conceived sons and daughters.

[[first-chronicles-14-4]]
^4^ And these are the names of those who were born to him in Jerusalem: Shammua and Shobab, Nathan and Solomon,

[[first-chronicles-14-5]]
^5^ Ibhar, and Elishua, and Elpelet,

[[first-chronicles-14-6]]
^6^ as well as Nogah, and Nepheg, and Japhia,

[[first-chronicles-14-7]]
^7^ Elishama, and Beeliada, and Eliphelet.

[[first-chronicles-14-8]]
^8^ Then, hearing that David had been anointed as king over all of Israel, all the Philistines ascended so that they might seek him. But when David had heard of it, he went out to meet them.

[[first-chronicles-14-9]]
^9^ Now the Philistines, arriving, spread out in the Valley of the Rephaim.

[[first-chronicles-14-10]]
^10^ And so David consulted the Lord, saying, “Shall I ascend to the Philistines, and will you deliver them into my hand?” And the Lord said to him, “Ascend, and I will deliver them into your hand.”

[[first-chronicles-14-11]]
^11^ And when they had ascended to Baal-perazim, David struck them there, and he said: “God has divided my enemies by my hand, just as waters are divided.” And therefore the name of that place was called Baal-perazim.

[[first-chronicles-14-12]]
^12^ And they left behind their gods in that place, and so David ordered them to be burned.

[[first-chronicles-14-13]]
^13^ And then, at another time, the Philistines invaded, and they spread out in the valley.

[[first-chronicles-14-14]]
^14^ And again, David consulted God. And God said to him: “You shall not ascend after them. Draw away from them. And you shall come against them opposite the balsam trees.

[[first-chronicles-14-15]]
^15^ And when you hear a sound approaching in the tops of the balsam trees, then you shall go forth to war. For God has gone forth before you, so that he may strike down the army of the Philistines.”

[[first-chronicles-14-16]]
^16^ Therefore, David did just as God had instructed him. And he struck down the army of the Philistines, from Gibeon as far as Gazera.

[[first-chronicles-14-17]]
^17^ And the name of David became well-known in all the regions. And the Lord placed the fear of him over all the nations.


[[first-chronicles-15]]
== Chapter 15

[[first-chronicles-15-1]]
^1^ Also, he made houses for himself in the City of David. And built a place for the ark of God, and he set up a tent for it.

[[first-chronicles-15-2]]
^2^ Then David said: “It is illicit for anyone to carry the ark of God except the Levites, whom the Lord chose to carry it and to minister to himself, even unto eternity.”

[[first-chronicles-15-3]]
^3^ And he gathered all of Israel in Jerusalem, so that the ark of God might be brought into its place, which he had prepared for it.

[[first-chronicles-15-4]]
^4^ Certainly, there were both the sons of Aaron and the Levites:

[[first-chronicles-15-5]]
^5^ From the sons of Kohath, Uriel was the leader, and his brothers were one hundred twenty.

[[first-chronicles-15-6]]
^6^ From the sons of Merari: Asaiah was the leader, and his brothers were two hundred twenty.

[[first-chronicles-15-7]]
^7^ From the sons of Gershom: Joel was the leader, and his brothers were one hundred thirty.

[[first-chronicles-15-8]]
^8^ From the sons of Elizaphan: Shemaiah was the leader, and his brothers were two hundred.

[[first-chronicles-15-9]]
^9^ From the sons of Hebron: Eliel was the leader, and his brothers were eighty.

[[first-chronicles-15-10]]
^10^ From the sons of Uzziel: Amminadab was the leader, and his brothers were one hundred twelve.

[[first-chronicles-15-11]]
^11^ And David summoned the priests, Zadok and Abiathar, and the Levites: Uriel, Asaiah, Joel, Shemaiah, Eliel, and Amminadab.

[[first-chronicles-15-12]]
^12^ And he said to them: “You who are the leaders of the Levitical families, be sanctified with your brothers, and bring the ark of the Lord God of Israel to the place that has been prepared for it.

[[first-chronicles-15-13]]
^13^ Otherwise, as it was before, when the Lord struck us because you were not present, so also it might be now, if we do what is illicit.”

[[first-chronicles-15-14]]
^14^ Therefore, the priests and the Levites were sanctified, so that they might carry the ark of the Lord God of Israel.

[[first-chronicles-15-15]]
^15^ And the sons of Levi took the ark of God, just as Moses had instructed, in accord with the word of the Lord, upon their shoulders by the bars.

[[first-chronicles-15-16]]
^16^ And David spoke to the leaders of the Levites, so that they might appoint, from their brothers, singers with musical instruments, specifically, psalteries, and harps, and cymbals, so that a joyful noise might resound on high.

[[first-chronicles-15-17]]
^17^ And they appointed from the Levites: Heman, the son of Joel; and from his brothers, Asaph, the son of Berechiah; and truly, from their brothers, the sons of Merari: Ethan, the son of Kushaiah.

[[first-chronicles-15-18]]
^18^ And with them were their brothers in the second rank: Zechariah, and Ben, and Jaaziel, and Shemiramoth, and Jahiel, and Unni, and Eliab, and Benaiah, and Maaseiah, and Mattithiah, and Eliphelehu, and Mikneiah, and Obededom, and Jeiel, who were gatekeepers.

[[first-chronicles-15-19]]
^19^ Now the singers, Heman, Asaph, and Ethan, were sounding out with cymbals of brass.

[[first-chronicles-15-20]]
^20^ And Zechariah, and Aziel, and Shemiramoth, and Jehiel, and Unni, and Eliab, and Maaseiah, and Benaiah were singing mysteries with the psalteries.

[[first-chronicles-15-21]]
^21^ Then Mattithiah, and Eliphelehu, and Mikneiah and Obededom, and Jeiel and Azaziah were singing a song of victory with the harps, for the octave.

[[first-chronicles-15-22]]
^22^ Now Chenaniah, the leader of the Levites, was foremost over the prophecies, in order to mark out in advance the melodies. For indeed, he was very skillful.

[[first-chronicles-15-23]]
^23^ And Berechiah and Elkanah were porters of the ark.

[[first-chronicles-15-24]]
^24^ And the priests, Shebaniah, and Joshaphat, and Nethanel, and Amasai, and Zechariah, and Benaiah, and Eliezer, were sounding the trumpets before the ark of God. And Obededom and Jehiah were porters of the ark.

[[first-chronicles-15-25]]
^25^ Therefore, David, and all those greater by birth of Israel, and the tribunes, went to carry the ark of the covenant of the Lord from the house of Obededom with rejoicing.

[[first-chronicles-15-26]]
^26^ And when God had assisted the Levites, who were carrying the ark of the covenant of the Lord, they immolated seven bulls and seven rams.

[[first-chronicles-15-27]]
^27^ Now David was clothed with a robe of fine linen, as were all the Levites who were carrying the ark, and the singers, and Chenaniah, the leader of the prophecy among the singers. But David was also clothed with a linen ephod.

[[first-chronicles-15-28]]
^28^ And all of Israel were leading back the ark of the covenant of the Lord with jubilation, sounding out with the noise of horns, and trumpets, and cymbals, and psalteries, and harps.

[[first-chronicles-15-29]]
^29^ And when the ark of the covenant of the Lord had arrived in the City of David, Michal, the daughter of Saul, gazing through a window, saw king David dancing and playing, and she despised him in her heart.


[[first-chronicles-16]]
== Chapter 16

[[first-chronicles-16-1]]
^1^ And so they took the ark of God, and they set it in the midst of the tabernacle, which David had pitched for it. And they offered holocausts and peace offerings before God.

[[first-chronicles-16-2]]
^2^ And when David had completed offering holocausts and peace offerings, he blessed the people in the name of the Lord.

[[first-chronicles-16-3]]
^3^ And he divided to every single one, from men even to women, a twist of bread, and a piece of roasted beef, and fine wheat flour fried with oil.

[[first-chronicles-16-4]]
^4^ And he appointed some from the Levites who would minister before the ark of the Lord, and commemorate his works, and glorify and praise the Lord, the God of Israel.

[[first-chronicles-16-5]]
^5^ Asaph was the leader, and second to him was Zechariah. In addition, there were Jeiel, and Shemiramoth, and Jehiel, and Mattithiah, and Eliab, and Benaiah, and Obededom. And Jeiel was over the instruments of the psaltery and the harps. But Asaph sounded out with the cymbals.

[[first-chronicles-16-6]]
^6^ Truly, the priests, Benaiah and Jahaziel, were to sound the trumpet continually before the ark of the covenant of the Lord.

[[first-chronicles-16-7]]
^7^ In that day, David made Asaph the leader, in order to confess to the Lord with his brothers:

[[first-chronicles-16-8]]
^8^ “Confess to the Lord, and invoke his name. Make known his endeavors among the peoples.

[[first-chronicles-16-9]]
^9^ Sing to him, and sing psalms to him, and describe all his miracles.

[[first-chronicles-16-10]]
^10^ Praise his holy name! Let the heart of those who seek the Lord rejoice!

[[first-chronicles-16-11]]
^11^ Seek the Lord and his virtue. Seek his face always.

[[first-chronicles-16-12]]
^12^ Remember his miracles, which he has accomplished, his signs, and the judgments of his mouth.

[[first-chronicles-16-13]]
^13^ O offspring of Israel, his servants! O sons of Jacob, his elect!

[[first-chronicles-16-14]]
^14^ He is the Lord our God. His judgments are throughout all the earth.

[[first-chronicles-16-15]]
^15^ Remember forever his covenant, the word that he instructed unto a thousand generations,

[[first-chronicles-16-16]]
^16^ the covenant that he formed with Abraham, and his oath with Isaac.

[[first-chronicles-16-17]]
^17^ And he appointed the same to Jacob as a precept, and to Israel as an everlasting pact,

[[first-chronicles-16-18]]
^18^ saying: ‘To you, I will give the land of Canaan, the lot of your inheritance.’

[[first-chronicles-16-19]]
^19^ At that time, they were small in number, they were few and were settlers there.

[[first-chronicles-16-20]]
^20^ And they passed through, from nation to nation, and from one kingdom to another people.

[[first-chronicles-16-21]]
^21^ He did not permit anyone to falsely accuse them. Instead, he reproved kings on their behalf:

[[first-chronicles-16-22]]
^22^ ‘Do not touch my Christ. And do not malign my prophets.’

[[first-chronicles-16-23]]
^23^ Sing to the Lord, all the earth! Announce his salvation, from day to day.

[[first-chronicles-16-24]]
^24^ Describe his glory among the Gentiles, his miracles among all the peoples.

[[first-chronicles-16-25]]
^25^ For the Lord is great and exceedingly praiseworthy. And he is terrible, above all gods.

[[first-chronicles-16-26]]
^26^ For all the gods of the peoples are idols. But the Lord made the heavens.

[[first-chronicles-16-27]]
^27^ Confession and magnificence are before him. Strength and gladness are in his place.

[[first-chronicles-16-28]]
^28^ Bring to the Lord, O families of the peoples, bring to the Lord glory and dominion.

[[first-chronicles-16-29]]
^29^ Give glory to the Lord, to his name. Lift up sacrifice, and approach before his sight. And adore the Lord in holy attire.

[[first-chronicles-16-30]]
^30^ Let all the earth be moved before his face. For he founded the globe immoveable.

[[first-chronicles-16-31]]
^31^ Let the heavens rejoice, and let the earth exult. And let them say among the nations, ‘The Lord has reigned.’

[[first-chronicles-16-32]]
^32^ Let the sea roar, with all its plenitude. Let the fields exult, with all that is in them.

[[first-chronicles-16-33]]
^33^ Then the trees of the forest will give praise before the Lord. For he comes to judge the earth.

[[first-chronicles-16-34]]
^34^ Confess to the Lord, for he is good. For his mercy is eternal.

[[first-chronicles-16-35]]
^35^ And say: ‘Save us, O God our savior! And gather us together, and rescue us from the nations, so that we may confess to your holy name, and may exult in your songs.

[[first-chronicles-16-36]]
^36^ Blessed be the Lord, the God of Israel, from eternity to eternity.’ And let all the people say, ‘Amen,’ and let them sing a hymn to the Lord.”

[[first-chronicles-16-37]]
^37^ And so, there before the ark of the covenant of the Lord, he left Asaph and his brothers, so that they might minister in the sight of the ark continually, throughout each day, and in their turns.

[[first-chronicles-16-38]]
^38^ Now Obededom and his brothers were sixty-eight. And he appointed Obededom, the son of Jeduthun, and Hosah to be porters.

[[first-chronicles-16-39]]
^39^ But Zadok the priest, and his brothers the priests, were before the tabernacle of the Lord in the high place, which was in Gibeon,

[[first-chronicles-16-40]]
^40^ so that they could offer holocausts to the Lord upon the altar of holocausts continually, morning and evening, according to all that was written in the law of the Lord, which he instructed to Israel.

[[first-chronicles-16-41]]
^41^ And after him, Heman, and Jeduthun, and the remainder of the elect, each one by his name, were appointed to confess to the Lord: “For his mercy endures forever.”

[[first-chronicles-16-42]]
^42^ Also Heman and Jeduthun sounded the trumpet, and they played upon the cymbals, and upon every kind of musical instrument, in order to sing praises to God. But the sons of Jeduthun he made to be porters.

[[first-chronicles-16-43]]
^43^ And all the people returned to their houses, and David also, so that he might bless his own house too.


[[first-chronicles-17]]
== Chapter 17

[[first-chronicles-17-1]]
^1^ Now when David was living in his house, he said to the prophet Nathan: “Behold, I live in a house of cedar. But the ark of the covenant of the Lord is under tent skins.”

[[first-chronicles-17-2]]
^2^ And Nathan said to David: “Do all that is in your heart. For God is with you.”

[[first-chronicles-17-3]]
^3^ And yet, that night the word of God came to Nathan, saying:

[[first-chronicles-17-4]]
^4^ “Go, and speak to my servant David: Thus says the Lord: You shall not build a house for me as a dwelling place.

[[first-chronicles-17-5]]
^5^ For I have not stayed in a house from the time when I led out Israel, even to this day. Instead, I have been continually changing places, in a tabernacle and tent,

[[first-chronicles-17-6]]
^6^ dwelling with all of Israel. When did I ever speak to any one at all, among the judges of Israel whom I placed in charge so that they might pasture my people, saying: ‘Why have you not built a house of cedar for me?’

[[first-chronicles-17-7]]
^7^ And so, now you shall say this to my servant David: Thus says the Lord of hosts: I took you when you were following the flock in the pastures, so that you would be the leader of my people Israel.

[[first-chronicles-17-8]]
^8^ And I have been with you wherever you have gone. And I have slain all your enemies before you, and I have made a name for you like one of the great ones who are celebrated upon the earth.

[[first-chronicles-17-9]]
^9^ And I have given a place to my people Israel. They shall be planted, and they shall live in it, and they shall no longer be moved. Neither shall the sons of iniquity wear them away, as in the beginning,

[[first-chronicles-17-10]]
^10^ from the days when I gave judges to my people Israel, and I humbled all your enemies. Therefore, I announce to you that the Lord will build a house for you.

[[first-chronicles-17-11]]
^11^ And when you will have completed your days, so that you go to your fathers, I will raise up your offspring after you, who shall be from your sons. And I will establish his kingdom.

[[first-chronicles-17-12]]
^12^ He shall build a house for me, and I will make firm his throne, even unto eternity.

[[first-chronicles-17-13]]
^13^ I will be a father to him, and he shall be a son to me. And I will not take away my mercy from him, as I took it away from the one who was before you.

[[first-chronicles-17-14]]
^14^ And I will station him in my house and in my kingdom, even forever. And his throne will be very firm, in perpetuity.”

[[first-chronicles-17-15]]
^15^ According to all these words, and according to this entire vision, so did Nathan speak to David.

[[first-chronicles-17-16]]
^16^ And when king David had departed, and had sat down before the Lord, he said: “Who am I, O Lord God, and what is my house, that you would grant such things to me?

[[first-chronicles-17-17]]
^17^ But even this has seemed little in your sight, and therefore you have also spoken about the house of your servant even for the future. And you have made me a spectacle above all men, O Lord God.

[[first-chronicles-17-18]]
^18^ What more can David add, since you have so glorified your servant, and have known him?

[[first-chronicles-17-19]]
^19^ O Lord, because of your servant, in accord with your own heart, you have brought about all this magnificence, and you have willed all these great things to be known.

[[first-chronicles-17-20]]
^20^ O Lord, there is no one like you. And there is no other God apart from you, out of all whom we have heard about with our ears.

[[first-chronicles-17-21]]
^21^ For what other single nation upon earth is like your people Israel, to whom God reached out, so that he might free them, and might make a people for himself, and by his greatness and terribleness cast out the nations before the face of those whom he had freed from Egypt?

[[first-chronicles-17-22]]
^22^ And you have set your people Israel to be your people, even unto eternity. And you, O Lord, have become their God.

[[first-chronicles-17-23]]
^23^ Now therefore, O Lord, let the word that you have spoken to your servant, and over his house, be confirmed in perpetuity, and do just as you have spoken.

[[first-chronicles-17-24]]
^24^ And may your name remain and be magnified even for all time. And let it be said: ‘The Lord of hosts is the God of Israel. And the house of his servant David remains forever before him.’

[[first-chronicles-17-25]]
^25^ For you, O Lord my God, have revealed to the ear of your servant that you will build a house for him. And therefore your servant has found faith so that he might pray before you.

[[first-chronicles-17-26]]
^26^ Now then, O Lord, you are God. And you have spoken to your servant such great benefits.

[[first-chronicles-17-27]]
^27^ And you have begun to bless the house of your servant, so that it may be always before you. For since it is you who is blessing, O Lord, it shall be blessed forever.”


[[first-chronicles-18]]
== Chapter 18

[[first-chronicles-18-1]]
^1^ Now after these things, it happened that David struck the Philistines, and he humbled them, and he took Gath and her daughters from the hand of the Philistines.

[[first-chronicles-18-2]]
^2^ And he struck Moab. And the Moabites became the servants of David, offering gifts to him.

[[first-chronicles-18-3]]
^3^ In that time, David also struck Hadadezer, the king of Zobah, in the region of Hamath, when he went forth so that he might extend his dominion as far as the river Euphrates.

[[first-chronicles-18-4]]
^4^ Then David seized one thousand of his four-horse chariots, and seven thousand horsemen, and twenty thousand men on foot. And he hamstrung all the chariot horses, except for one hundred four-horse chariots, which he reserved for himself.

[[first-chronicles-18-5]]
^5^ Then the Syrians of Damascus also arrived, so that they might offer assistance to Hadadezer, the king of Zobah. And so, David then struck of them twenty-two thousand men.

[[first-chronicles-18-6]]
^6^ And he stationed soldiers in Damascus, so that Syria also would serve him, and would offer gifts. And the Lord assisted him in all the things to which he went forth.

[[first-chronicles-18-7]]
^7^ Also, David took the golden quivers, which the servants of Hadadezer had, and he brought them to Jerusalem.

[[first-chronicles-18-8]]
^8^ In addition, from Tibhath and Cun, cities of Hadadezer, he brought very much brass, from which Solomon made the sea of brass, and the pillars, and the vessels of brass.

[[first-chronicles-18-9]]
^9^ Now when Toi, the king of Hamath, had heard this, specifically that David had struck the entire army of Hadadezer, the king of Zobah,

[[first-chronicles-18-10]]
^10^ he sent his son Hadoram to king David so that he might petition peace from him, and so that he might congratulate him that he had struck and defeated Hadadezer. For indeed, Toi was an adversary to Hadadezer.

[[first-chronicles-18-11]]
^11^ Moreover, all the vessels of gold and silver and brass king David consecrated to the Lord, with the silver and gold that he had taken from all the nations, as much from Idumea, and Moab, and the sons of Ammon, as from the Philistines and Amalek.

[[first-chronicles-18-12]]
^12^ Truly, Abishai, the son of Zeruiah, struck eighteen thousand of the Edomites in the Valley of the Salt Pits.

[[first-chronicles-18-13]]
^13^ And he stationed a garrison in Edom, so that Idumea would serve David. And the Lord saved David in all the things to which he went forth.

[[first-chronicles-18-14]]
^14^ Therefore, David reigned over all of Israel, and he executed judgment and justice among all his people.

[[first-chronicles-18-15]]
^15^ Now Joab, the son of Zeruiah, was over the army, and Jehoshaphat, the son of Ahilud, was the keeper of records.

[[first-chronicles-18-16]]
^16^ And Zadok, the son of Ahitub, and Ahimelech, the son of Abiathar, were the priests. And Shavsha was the scribe.

[[first-chronicles-18-17]]
^17^ Also, Benaiah, the son of Jehoiada, was over the legions of the Cherethites and Pelethites. But the sons of David were first at the hand of the king.


[[first-chronicles-19]]
== Chapter 19

[[first-chronicles-19-1]]
^1^ Now it happened that Nahash, the king of the sons of Ammon, died, and his son reigned in his place.

[[first-chronicles-19-2]]
^2^ And David said: “I will act with mercy toward Hanun, the son of Nahash. For his father was gracious to me.” And so David sent messengers to console him over the death of his father. But when they had reached the land of the sons of Ammon, so that they might console Hanun,

[[first-chronicles-19-3]]
^3^ the leaders of the sons of Ammon said to Hanun: “Do you think that perhaps David has sent them to console you in order to honor your father? Have you not noticed that his servants came to you so that they might explore, and investigate, and examine your land?”

[[first-chronicles-19-4]]
^4^ And so Hanun shaved the heads and beards of the servants of David, and he cut away their tunics from the buttocks to the feet, and he sent them away.

[[first-chronicles-19-5]]
^5^ And when they had gone, and had sent word to David, (for they had suffered a great disgrace,) he sent to meet them, and he instructed them that they should remain at Jericho until their beards grew, and then they should return.

[[first-chronicles-19-6]]
^6^ Then, when the sons of Ammon realized that they had committed an injury against David, both Hanun and the rest of the people sent one thousand talents of silver, so that they might hire for themselves chariots and horsemen from Mesopotamia, and from Syrian Maacah, and from Zobah.

[[first-chronicles-19-7]]
^7^ And they hired thirty-two thousand chariots, and the king of Maacah with his people. When these had arrived, they made camp in the region opposite Medeba. Also, the sons of Ammon, gathering from their cities, went to war.

[[first-chronicles-19-8]]
^8^ And when David had heard this, he sent Joab and the entire army of strong men.

[[first-chronicles-19-9]]
^9^ And the sons of Ammon, going out, set up a battle line before the gate of the city. But the kings who had come to their aid stood separately in the field.

[[first-chronicles-19-10]]
^10^ And so Joab, understanding the war to be set facing him and behind his back, chose the strongest men from all of Israel, and he went out against the Syrians.

[[first-chronicles-19-11]]
^11^ But the remaining portion of the people he placed under the hand of his brother Abishai. And they went out against the sons of Ammon.

[[first-chronicles-19-12]]
^12^ And he said: “If the Syrians prevail over me, then you shall be a help to me. But if the sons of Ammon prevail over you, I will be a safeguard for you.

[[first-chronicles-19-13]]
^13^ Be strengthened, and let us act manfully on behalf of our people, and on behalf of the cities of our God. And the Lord will do what is good in his own sight.”

[[first-chronicles-19-14]]
^14^ Therefore, Joab, and the people who were with him, went out to battle against the Syrians. And he put them to flight.

[[first-chronicles-19-15]]
^15^ Then the sons of Ammon, seeing that the Syrians had fled, also themselves fled from Abishai, his brother, and they entered into the city. And now Joab returned to Jerusalem.

[[first-chronicles-19-16]]
^16^ But the Syrians, seeing that they had fallen before Israel, sent messengers, and they brought the Syrians who were across the river. And Shophach, the leader of the military of Hadadezer, was their commander.

[[first-chronicles-19-17]]
^17^ When this had been reported to David, he gathered together all of Israel, and he crossed the Jordan. And he rushed toward them. And he set up a battle line facing them. And they fought against him.

[[first-chronicles-19-18]]
^18^ But the Syrians fled from Israel. And David killed of the Syrians seven thousand chariots, and forty thousand men on foot, and Shophach, the leader of the army.

[[first-chronicles-19-19]]
^19^ Then the servants of Hadadezer, seeing themselves to be overwhelmed by Israel, crossed over to David, and they served him. And Syria was no longer willing to offer aid to the sons of Ammon.


[[first-chronicles-20]]
== Chapter 20

[[first-chronicles-20-1]]
^1^ Now it happened that, after the course of a year, in the time when kings usually go forth to war, Joab gathered an army with experienced soldiers, and he laid waste to the land of the sons of Ammon. And he continued on and besieged Rabbah. But David was staying in Jerusalem when Joab struck Rabbah and destroyed it.

[[first-chronicles-20-2]]
^2^ Then David took the crown of Milcom from his head, and he found in it the weight of one talent of gold, and very precious gems. And he made for himself a diadem from it. Also, he took the best spoils of the city, which were very many.

[[first-chronicles-20-3]]
^3^ Then he led away the people who were in it. And he caused plows, and sleds, and iron chariots to go over them, so much so that they were cut apart and crushed. So did David treat all the cities of the sons of Ammon. And he returned with all his people to Jerusalem.

[[first-chronicles-20-4]]
^4^ After these things, a war was begun at Gezer against the Philistines, in which Sibbecai the Hushathite struck Sippai from the race of the Rephaim, and he humbled them.

[[first-chronicles-20-5]]
^5^ Also, another war was undertaken against the Philistines, in which Adeodatus, a son of the forest, a Bethlehemite, struck the brother of Goliath the Gittite, the wood of whose spear was like a weaver’s beam.

[[first-chronicles-20-6]]
^6^ Then too, another war occurred in Gath, in which there was a very tall man, having six digits, that is, all together twenty-four. This man too was born from the stock of the Rephaim.

[[first-chronicles-20-7]]
^7^ He blasphemed Israel. And Jonathan, the son of Shimea, the brother of David, struck him down. These were the sons of the Rephaim in Gath, who fell by the hand of David and his servants.


[[first-chronicles-21]]
== Chapter 21

[[first-chronicles-21-1]]
^1^ Now Satan rose up against Israel, and he incited David so that he would number Israel.

[[first-chronicles-21-2]]
^2^ And David said to Joab and to the leaders of the people: “Go, and number Israel, from Beersheba even to Dan. And bring me the number, so that I may know it.”

[[first-chronicles-21-3]]
^3^ And Joab responded: “May the Lord increase his people a hundred times more than they are. But, my lord the king, are they not all your servants? Why would my lord seek this thing, which may be imputed as a sin to Israel?”

[[first-chronicles-21-4]]
^4^ But the word of the king prevailed instead. And Joab went away, and he traveled around, through all of Israel. And he returned to Jerusalem.

[[first-chronicles-21-5]]
^5^ And he gave to David the number of those whom he had surveyed. And the entire number of Israel was found to be one million and one hundred thousand men who could draw the sword; but from Judah, there were four hundred and seventy thousand men of war.

[[first-chronicles-21-6]]
^6^ But Levi and Benjamin he did not number. For Joab executed the orders of the king unwillingly.

[[first-chronicles-21-7]]
^7^ Then God was displeased with what had been ordered, and so he struck Israel.

[[first-chronicles-21-8]]
^8^ And David said to God: “I have sinned exceedingly in doing this. I beg you take away the iniquity of your servant. For I have acted unwisely.”

[[first-chronicles-21-9]]
^9^ And the Lord spoke to Gad, the seer of David, saying:

[[first-chronicles-21-10]]
^10^ “Go, and speak to David, and tell him: Thus says the Lord: I give to you the option of three things. Choose the one that you will want, and I will do it to you.”

[[first-chronicles-21-11]]
^11^ And when Gad had gone to David, he said to him: “Thus says the Lord: Choose what you will want:

[[first-chronicles-21-12]]
^12^ Either three years of famine, or three months for you to flee from your enemies, unable to escape from their sword, or three days for the sword of the Lord and a pestilence to turn within the land, with the Angel of the Lord killing in every part of Israel. Now therefore, see what I should respond to him who sent me.”

[[first-chronicles-21-13]]
^13^ And David said to Gad: “There are difficulties pressing upon me from every side. But it is better for me to fall into the hands of the Lord, for his mercies are many, than into the hands of men.”

[[first-chronicles-21-14]]
^14^ Therefore, the Lord sent a pestilence upon Israel. And there fell from Israel seventy thousand men.

[[first-chronicles-21-15]]
^15^ Also, he sent an Angel to Jerusalem, so that he might strike it. And while he was striking, the Lord saw and took pity over the magnitude of the harm. And he commanded the Angel who was striking: “It is enough. Now let your hand cease.” And the Angel of the Lord was standing beside the threshing floor of Ornan the Jebusite.

[[first-chronicles-21-16]]
^16^ And David, lifting up his eyes, saw the Angel of the Lord, standing between heaven and earth with a drawn sword in his hand, turned toward Jerusalem. And both he and those greater by birth, being clothed in haircloth, fell prone upon the ground.

[[first-chronicles-21-17]]
^17^ And David said to God: “Am I not the one who ordered that the people be numbered? It is I who sinned; it is I who did evil. This flock, what does it deserve? O Lord my God, I beg you to let your hand be turned against me and against the house of my father. But let not your people be struck down.”

[[first-chronicles-21-18]]
^18^ Then the Angel of the Lord instructed Gad to tell David that he should ascend and build an altar to the Lord God on the threshing floor of Ornan the Jebusite.

[[first-chronicles-21-19]]
^19^ Therefore, David ascended, in accord with the word of Gad, which he had spoken to him in the name of the Lord.

[[first-chronicles-21-20]]
^20^ Now when Ornan had looked up and seen the Angel, he and his four sons hid themselves. For at that time, he was threshing wheat upon the floor.

[[first-chronicles-21-21]]
^21^ Then, as David was approaching Ornan, Ornan saw him, and he went out from the threshing floor to meet him. And he reverenced him prone on the ground.

[[first-chronicles-21-22]]
^22^ And David said to him: “Give this place of your threshing floor to me, so that I may build an altar to the Lord upon it. And you shall accept from me as much money as it is worth, so that the plague may cease from the people.”

[[first-chronicles-21-23]]
^23^ But Ornan said to David: “Take it, and may my lord the king do whatever pleases him. Moreover, I give the oxen also as a holocaust, and the plow for wood, and the wheat for a sacrifice. I will offer all freely.”

[[first-chronicles-21-24]]
^24^ And king David said to him: “By no means shall it be so. Instead, I will give money to you, as much as it is worth. For I must not take it from you, and thereby offer to the Lord holocausts that cost nothing.”

[[first-chronicles-21-25]]
^25^ Therefore, David gave Ornan, for the place, the very just weight of six hundred shekels of gold.

[[first-chronicles-21-26]]
^26^ And he built an altar to the Lord there. And he offered holocausts and peace offerings, and he called upon the Lord. And he heeded him by sending fire from heaven upon the altar of the holocaust.

[[first-chronicles-21-27]]
^27^ And the Lord instructed the Angel, and he turned his sword back into its sheath.

[[first-chronicles-21-28]]
^28^ Then, seeing that the Lord had heeded him at the threshing floor of Ornan the Jebusite, David immediately immolated victims there.

[[first-chronicles-21-29]]
^29^ But the tabernacle of the Lord, which Moses had made in the desert, and the altar of holocausts, were at that time on the high place of Gibeon.

[[first-chronicles-21-30]]
^30^ And David was unable to go to the altar, so that he might pray to God there. For he had been struck with an exceedingly great fear, seeing the sword of the Angel of the Lord.


[[first-chronicles-22]]
== Chapter 22

[[first-chronicles-22-1]]
^1^ And David said, “This is the house of God, and this is the altar for the holocaust of Israel.”

[[first-chronicles-22-2]]
^2^ And he instructed them to gather all the new converts from the land of Israel. And from these he appointed stoneworkers, to hew stones and to polish them, so that he might build the house of God.

[[first-chronicles-22-3]]
^3^ Also, David prepared very much iron to use for the nails of the gates, and for the seams and joints, as well as an immeasurable weight of brass.

[[first-chronicles-22-4]]
^4^ Also, the cedar trees, which the Sidonians and Tyrians had transported to David, were not able to be counted.

[[first-chronicles-22-5]]
^5^ And David said: “My son Solomon is a young and tender boy. But the house that I desire to be built to the Lord ought to be so great that it is renowned in every region. Therefore, I will prepare what will be necessary for him.” And for this reason, before his death, he prepared all the expenses.

[[first-chronicles-22-6]]
^6^ And he called for Solomon, his son. And he instructed him to build a house to the Lord, the God of Israel.

[[first-chronicles-22-7]]
^7^ And David said to Solomon: “My son, it was my will that I build a house to the name of the Lord my God.

[[first-chronicles-22-8]]
^8^ But the word of the Lord came to me, saying: ‘You have shed much blood, and you have battled in many wars. You are not able to build a house to my name, so great was the shedding of blood before me.

[[first-chronicles-22-9]]
^9^ The son who shall be born to you will be a very quiet man. For I will cause him to have rest from all his enemies on every side. And for this reason, he shall be called Peaceful. And I will grant peace and tranquility to Israel during all his days.

[[first-chronicles-22-10]]
^10^ He shall build a house to my name. And he shall be a son to me, and I will be a father to him. And I will establish the throne of his kingdom over Israel unto eternity.’

[[first-chronicles-22-11]]
^11^ Now then, my son, may the Lord be with you, and may you prosper and build a house to the Lord your God, just as he has spoken concerning you.

[[first-chronicles-22-12]]
^12^ Also, may the Lord give you prudence and understanding, so that you may be able to rule Israel and to guard the law of the Lord your God.

[[first-chronicles-22-13]]
^13^ For then you will be able to advance, if you keep the commandments and judgments that the Lord instructed Moses to teach to Israel. Be strengthened and act manfully. You should not fear, and you should not dread.

[[first-chronicles-22-14]]
^14^ Behold, in my poverty I have prepared the expenses for the house of the Lord: one hundred thousand talents of gold, and one million of talents of silver. Yet truly, there is no measuring the brass and the iron. For their magnitude is beyond numbering. And I have prepared the timber and the stones for the entire project.

[[first-chronicles-22-15]]
^15^ Also, you have very many artisans: stoneworkers, and builders of walls, and craftsmen of wood, and those most prudent in doing the work of every art,

[[first-chronicles-22-16]]
^16^ with gold and silver, and with brass and iron, of which there is no number. Therefore, rise up and act. And the Lord will be with you.”

[[first-chronicles-22-17]]
^17^ Also, David instructed all the leaders of Israel, so that they would assist his son Solomon,

[[first-chronicles-22-18]]
^18^ saying: “You discern that the Lord your God is with you, and that he has given you rest on all sides, and that he has delivered all your enemies into your hands, and that the land has been subdued before the Lord and before his people.

[[first-chronicles-22-19]]
^19^ Therefore, offer your hearts and your souls, so that you seek the Lord your God. And rise up and build a sanctuary to the Lord God, so that the ark of the covenant of the Lord, and the vessels consecrated to the Lord, may be brought into the house that is built to the name of the Lord.”


[[first-chronicles-23]]
== Chapter 23

[[first-chronicles-23-1]]
^1^ Then David, being old and full of days, appointed his son Solomon as king over Israel.

[[first-chronicles-23-2]]
^2^ And he gathered together all the leaders of Israel, with the priests as well as the Levites.

[[first-chronicles-23-3]]
^3^ And the Levites were numbered from the age of thirty years and upward. And there were found thirty-eight thousand men.

[[first-chronicles-23-4]]
^4^ Of these, twenty-four thousand were chosen and distributed to the ministry of the house of the Lord. Then six thousand were overseers and judges.

[[first-chronicles-23-5]]
^5^ Moreover, four thousand were porters. And the same number were the singers of psalms to the Lord, with the musical instruments which he had made for the music.

[[first-chronicles-23-6]]
^6^ And David distributed them into courses according to the sons of Levi, specifically, Gershom, and Kohath, and Merari.

[[first-chronicles-23-7]]
^7^ The sons of Gershom: Ladan and Shimei.

[[first-chronicles-23-8]]
^8^ The sons of Ladan: the leader Jahiel, and Zetham, and Joel, three.

[[first-chronicles-23-9]]
^9^ The sons of Shimei: Shelomoth, and Haziel, and Haran, three. These were the leaders of the families of Ladan.

[[first-chronicles-23-10]]
^10^ Then the sons of Shimei: Jahath, and Zizah, and Jeush, and Beriah. These were the sons of Shimei, four.

[[first-chronicles-23-11]]
^11^ Now Jahath was first, Zizah second, but Jeush and Beriah did not have many sons, and for this reason they were reckoned as one family and one house.

[[first-chronicles-23-12]]
^12^ The sons of Kohath: Amram and Izhar, Hebron and Uzziel, four.

[[first-chronicles-23-13]]
^13^ The sons of Amram: Aaron and Moses. Now Aaron was separated so that he might minister in the Holy of Holies, he and his sons forever, and so that he might burn incense to the Lord, according to his rite, and so that he might bless his name in perpetuity.

[[first-chronicles-23-14]]
^14^ The sons of Moses, the man of God, were also numbered in the tribe of Levi.

[[first-chronicles-23-15]]
^15^ The sons of Moses: Gershom and Eliezer.

[[first-chronicles-23-16]]
^16^ The sons of Gershom: Shebuel the first.

[[first-chronicles-23-17]]
^17^ Now the sons of Eliezer were Rehabiah the first. And there were no other sons for Eliezer. But the sons of Rehabiah were multiplied exceedingly.

[[first-chronicles-23-18]]
^18^ The sons of Izhar: Shelomith the first.

[[first-chronicles-23-19]]
^19^ The sons of Hebron: Jeriah the first, Amariah the second, Jahaziel the third, Jekameam the fourth.

[[first-chronicles-23-20]]
^20^ The sons of Uzziel: Micah the first, Isshiah the second.

[[first-chronicles-23-21]]
^21^ The sons of Merari: Mahli and Mushi. The sons of Mahli: Eleazar and Kish.

[[first-chronicles-23-22]]
^22^ Then Eleazar died, and had no sons, but only daughters. And so the sons of Kish, their brothers, married them.

[[first-chronicles-23-23]]
^23^ The sons of Mushi: Mahli, and Eder, and Jeremoth, three.

[[first-chronicles-23-24]]
^24^ These are the sons of Levi, in their kindred and families, leaders in turns, and the number of each of the heads who were doing the works of the ministry of the house of the Lord, from twenty years of age and upward.

[[first-chronicles-23-25]]
^25^ For David said: “The Lord, the God of Israel, has given rest to his people, and a habitation in Jerusalem even unto eternity.

[[first-chronicles-23-26]]
^26^ Neither shall it be the office of the Levites any more to carry the tabernacle with all its equipment for use in the ministry.”

[[first-chronicles-23-27]]
^27^ Also, according to the last precepts of David, the sons of Levi shall be counted by number from twenty years of age and upward.

[[first-chronicles-23-28]]
^28^ And they shall be under the hand of the sons of Aaron, in the care of the house of the Lord, in the vestibule, and in the chambers, and in the place of purification, and in the sanctuary, and in all the works of the ministry of the temple of the Lord.

[[first-chronicles-23-29]]
^29^ But the priests shall be over the bread of the presence, and the sacrifice of fine wheat flour, and the unleavened cakes, and the frying pan, and the roasting, and over every weight and measure.

[[first-chronicles-23-30]]
^30^ Yet truly, the Levites shall stand to confess and to sing to the Lord, in the morning, and similarly in the evening,

[[first-chronicles-23-31]]
^31^ as much in the oblation of the holocausts of the Lord, as in the Sabbaths and new moons and other solemnities, according to the number and ceremonies for each and every matter, perpetually before the Lord.

[[first-chronicles-23-32]]
^32^ And let them keep the observances of the tabernacle of the covenant, and the rituals of the sanctuary, and the observance of the sons of Aaron, their brothers, so that they may minister in the house of the Lord.


[[first-chronicles-24]]
== Chapter 24

[[first-chronicles-24-1]]
^1^ Now these were the divisions of the sons of Aaron. The sons of Aaron: Nadab, and Abihu, and Eleazar, and Ithamar.

[[first-chronicles-24-2]]
^2^ But Nadab and Abihu died before their father, and without children. And so Eleazar and Ithamar exercised the priestly office.

[[first-chronicles-24-3]]
^3^ And David distributed them, that is, Zadok of the sons of Eleazar, and Ahimelech of the sons of Ithamar, according to their courses and ministry.

[[first-chronicles-24-4]]
^4^ And there were found many more of the sons of Eleazar among the leading men, than of the sons of Ithamar. Therefore, he divided them so that there were, of the sons of Eleazar, sixteen leaders by their families, and of the sons of Ithamar eight by their families and houses.

[[first-chronicles-24-5]]
^5^ Then he divided among them, in both families, by lot. For there were leaders of the sanctuary and leaders of God, as much from the sons of Eleazar as from the sons of Ithamar.

[[first-chronicles-24-6]]
^6^ And the scribe Shemaiah, the son of Nethanel, a Levite, wrote these down before the king and the leaders, with Zadok, the priest, and Ahimelech, the son of Abiathar, and also the leaders of the priestly and Levitical families. And there was one house, which was preeminent over the others, that of Eleazar; and there was another house, which had the others under it, that of Ithamar.

[[first-chronicles-24-7]]
^7^ Now the first lot went forth to Jehoiarib, the second to Jedaiah,

[[first-chronicles-24-8]]
^8^ the third to Harim, the fourth to Seorim,

[[first-chronicles-24-9]]
^9^ the fifth to Malchijah, the sixth to Mijamin,

[[first-chronicles-24-10]]
^10^ the seventh to Hakkoz, the eighth to Abijah,

[[first-chronicles-24-11]]
^11^ the ninth to Jeshua, the tenth to Shecaniah,

[[first-chronicles-24-12]]
^12^ the eleventh to Eliashib, the twelfth to Jakim,

[[first-chronicles-24-13]]
^13^ the thirteenth to Huppah, the fourteenth to Jeshebeab,

[[first-chronicles-24-14]]
^14^ the fifteenth to Bilgah, the sixteenth to Immer,

[[first-chronicles-24-15]]
^15^ the seventeenth to Hezir, the eighteenth to Happizzez,

[[first-chronicles-24-16]]
^16^ the nineteenth to Pethahiah, the twentieth to Jehezkel,

[[first-chronicles-24-17]]
^17^ the twenty-first to Jachin, the twenty-second to Gamul,

[[first-chronicles-24-18]]
^18^ the twenty-third to Delaiah, the twenty-fourth to Maaziah.

[[first-chronicles-24-19]]
^19^ These were their courses according to their ministries, so that they would enter into the house of the Lord in accord with their practice, under the hand of Aaron, their father, just as the Lord, the God of Israel, had instructed.

[[first-chronicles-24-20]]
^20^ Now of the sons of Levi who were remaining, there were Shubael, from the sons of Amram, and Jehdeiah, from the sons of Shubael.

[[first-chronicles-24-21]]
^21^ Also, there were Isshiah, the leader from the sons of Rehabiah,

[[first-chronicles-24-22]]
^22^ and truly Shelomoth, the son of Izhar, and Jahath, the son of Shelomoth,

[[first-chronicles-24-23]]
^23^ and his son, Jeriah the first, Amariah the second, Jahaziel the third, Jekameam the fourth.

[[first-chronicles-24-24]]
^24^ The son of Uzziel was Micah. The son of Micah was Shamir.

[[first-chronicles-24-25]]
^25^ The brother of Micah was Isshiah. And the son of Isshiah was Zechariah.

[[first-chronicles-24-26]]
^26^ The sons of Merari were Mahli and Mushi. The son of Uzziah was Beno.

[[first-chronicles-24-27]]
^27^ Also, the son of Merari: Uzziah, and Shoham, and Zaccur, and Hebri.

[[first-chronicles-24-28]]
^28^ In addition, the son of Mahli was Eleazar, who had no children.

[[first-chronicles-24-29]]
^29^ Truly, the son of Kish was Jerahmeel.

[[first-chronicles-24-30]]
^30^ The sons of Mushi were Mahli, Eder, and Jerimoth. These were the sons of Levi according to the houses of their families.

[[first-chronicles-24-31]]
^31^ And they also cast lots concerning their brothers, the sons of Aaron, before David the king, and Zadok, and Ahimelech, and the leaders of the priestly and Levitical families, as much concerning the elder as the younger. The lot divided all things equitably.


[[first-chronicles-25]]
== Chapter 25

[[first-chronicles-25-1]]
^1^ Then David and the magistrates of the army set apart, for the ministry, the sons of Asaph, and of Heman, and of Jeduthun, who were to prophesy with harps and psalteries and cymbals, in accord with their number, having been dedicated to their appointed office.

[[first-chronicles-25-2]]
^2^ From the sons of Asaph: Zaccur, and Joseph, and Nethaniah, and Asharelah, the sons of Asaph, under the hand of Asaph, prophesying beside the king.

[[first-chronicles-25-3]]
^3^ Then of Jeduthun, the sons of Jeduthun: Gedaliah, Zeri, Jeshaiah, and Hashabiah, and Mattithiah, six, under the hand of their father Jeduthun, who was prophesying with stringed instruments, while confessing and praising the Lord.

[[first-chronicles-25-4]]
^4^ Also, of Heman, the sons of Heman: Bukkiah, Mattaniah, Uzziel, Shebuel, and Jerimoth, Hananiah, Hanani, Eliathah, Giddalti, and Romamtiezer, and Joshbekashah, Mallothi, Hothir, Mahazioth.

[[first-chronicles-25-5]]
^5^ All these were the sons of Heman, the seer of the king in the words of God, in order to lift up the horn. And God gave to Heman fourteen sons and three daughters.

[[first-chronicles-25-6]]
^6^ All these, under their father’s hand, were distributed in order to sing in the temple of the Lord, with cymbals and psalteries and harps, in the ministry of the house of the Lord beside the king, specifically, Asaph, and Jeduthun, and Heman.

[[first-chronicles-25-7]]
^7^ Now the number of these, with their brothers, who were instructing in the song of the Lord, all the teachers, were two hundred eighty-eight.

[[first-chronicles-25-8]]
^8^ And they cast lots in their turns, the elder equally with the younger, the learned together with the unlearned.

[[first-chronicles-25-9]]
^9^ And the first lot went forth to Joseph, who was of Asaph; the second went forth to Gedaliah, to him and his sons and his brothers, twelve.

[[first-chronicles-25-10]]
^10^ The third went to Zaccur, to his sons and brothers, twelve.

[[first-chronicles-25-11]]
^11^ The fourth went to Izri, to his sons and brothers, twelve.

[[first-chronicles-25-12]]
^12^ The fifth went to Nethaniah, to his sons and brothers, twelve.

[[first-chronicles-25-13]]
^13^ The sixth went to Bukkiah, to his sons and brothers, twelve.

[[first-chronicles-25-14]]
^14^ The seventh went to Jesharelah, to his sons and brothers, twelve.

[[first-chronicles-25-15]]
^15^ The eighth went to Jeshaiah, to his sons and brothers, twelve.

[[first-chronicles-25-16]]
^16^ The ninth went to Mattaniah, to his sons and brothers, twelve.

[[first-chronicles-25-17]]
^17^ The tenth went to Shimei, to his sons and brothers, twelve.

[[first-chronicles-25-18]]
^18^ The eleventh went to Azarel, to his sons and brothers, twelve.

[[first-chronicles-25-19]]
^19^ The twelfth went to Hashabiah, to his sons and brothers, twelve.

[[first-chronicles-25-20]]
^20^ The thirteenth went to Shubael, to his sons and brothers, twelve.

[[first-chronicles-25-21]]
^21^ The fourteenth went to Mattithiah, to his sons and brothers, twelve.

[[first-chronicles-25-22]]
^22^ The fifteenth went to Jeremoth, to his sons and brothers, twelve.

[[first-chronicles-25-23]]
^23^ The sixteenth went to Hananiah, to his sons and brothers, twelve.

[[first-chronicles-25-24]]
^24^ The seventeenth went to Joshbekashah, to his sons and brothers, twelve.

[[first-chronicles-25-25]]
^25^ The eighteenth went to Hanani, to his sons and brothers, twelve.

[[first-chronicles-25-26]]
^26^ The nineteenth went to Mallothi, to his sons and his brothers, twelve.

[[first-chronicles-25-27]]
^27^ The twentieth went to Eliathah, to his sons and brothers, twelve.

[[first-chronicles-25-28]]
^28^ The twenty-first went to Hothir, to his sons and brothers, twelve.

[[first-chronicles-25-29]]
^29^ The twenty-second went to Giddalti, to his sons and brothers, twelve.

[[first-chronicles-25-30]]
^30^ The twenty-third went to Mahazioth, to his sons and brothers, twelve.

[[first-chronicles-25-31]]
^31^ The twenty-fourth went to Romamtiezer, to his sons and brothers, twelve.


[[first-chronicles-26]]
== Chapter 26

[[first-chronicles-26-1]]
^1^ Now the divisions of the porters were, from the Korahites: Meshelemiah, the son of Kore, of the sons of Asaph.

[[first-chronicles-26-2]]
^2^ The sons of Meshelemiah: Zechariah the firstborn, Jediael the second, Zebadiah the third, Jathniel the fourth,

[[first-chronicles-26-3]]
^3^ Elam the fifth, Jehohanan the sixth, Eliehoenai the seventh.

[[first-chronicles-26-4]]
^4^ Then the sons of Obededom: Shemaiah the firstborn, Jehozabad the second, Joah the third, Sachar the fourth, Nethanel the fifth,

[[first-chronicles-26-5]]
^5^ Ammiel the sixth, Issachar the seventh, Peullethai the eighth. For the Lord had blessed him.

[[first-chronicles-26-6]]
^6^ Now to his son Shemaiah, there were born sons, rulers of their families. For they were very strong men.

[[first-chronicles-26-7]]
^7^ Then the sons of Shemaiah were Othni, and Rephael, and Obed, Elzabad and his brothers, very strong men, as well as Elihu and Semachiah.

[[first-chronicles-26-8]]
^8^ All these were from the sons of Obededom: they and their sons and brothers, very fit for the ministry, sixty-two from Obededom.

[[first-chronicles-26-9]]
^9^ Then there were the sons of Meshelemiah and their brothers, very robust men, eighteen.

[[first-chronicles-26-10]]
^10^ Now, from Hosah, that is, from the sons of Merari: Shimri the leader, for he had not had a firstborn son, and so, because of this, his father had appointed him as the leader,

[[first-chronicles-26-11]]
^11^ Hilkiah the second, Tebaliah the third, Zechariah the fourth. All these, the sons and brothers of Hosah, were thirteen.

[[first-chronicles-26-12]]
^12^ These were distributed as porters, so that the leaders of the posts, as well as their brothers, were ministering continually in the house of the Lord.

[[first-chronicles-26-13]]
^13^ Then they cast lots equally, for both the small and the great, by their families, concerning each one of the gates.

[[first-chronicles-26-14]]
^14^ And the lot of the east fell out to Shelemiah. But to his son Zechariah, a very prudent and learned man, the northern section was obtained by lot.

[[first-chronicles-26-15]]
^15^ Truly, Obededom and his sons obtained that to the south, in the part of the house where the council of elders was.

[[first-chronicles-26-16]]
^16^ Shuppim and Hosah obtained that toward the west, beside the gate that leads to the way of the ascent, one post facing the other.

[[first-chronicles-26-17]]
^17^ Truly, toward the east there were six Levites, and toward the north there were four per day, and then toward the south similarly there were four each day. And where the council was, there were two and two.

[[first-chronicles-26-18]]
^18^ Also, in the cells of the porters toward the west, there were four along the way, and two at every cell.

[[first-chronicles-26-19]]
^19^ These are the divisions of the porters of the sons of Kohath and of Merari.

[[first-chronicles-26-20]]
^20^ Now Ahijah was over the treasuries of the house of God, and the holy vessels.

[[first-chronicles-26-21]]
^21^ The sons of Ladan, sons of Gershon: from Ladan, leaders of the families of Ladan and of Gershon: Jehieli.

[[first-chronicles-26-22]]
^22^ The sons of Jehieli: Zetham and Joel; his brothers were over the treasuries of the house of the Lord,

[[first-chronicles-26-23]]
^23^ with the Amramites, and Izharites, and Hebronites, and Uzzielites.

[[first-chronicles-26-24]]
^24^ Now, Shebuel, the son of Gershom, the son of Moses, was in the first place over the treasuries,

[[first-chronicles-26-25]]
^25^ along with his brothers, Eliezer, and his son Rehabiah, and his son Jeshaiah, and his son Joram, and also his son Zichri, and his son Shelomoth.

[[first-chronicles-26-26]]
^26^ The same Shelomoth and his brothers were over the treasuries of the holy things, which king David sanctified, with the leaders of the families, and the tribunes, and the centurions, and the commanders of the army.

[[first-chronicles-26-27]]
^27^ These things were from the wars and from the best spoils of the battles, which they had consecrated for the repair and the furnishing of the temple of the Lord.

[[first-chronicles-26-28]]
^28^ Now all these things were sanctified by Samuel, the seer, and by Saul, the son of Kish, and by Abner, the son of Ner, and by Joab, the son of Zeruiah. All those who had sanctified these were under the hand of Shelomoth and his brothers.

[[first-chronicles-26-29]]
^29^ Yet truly, Chenaniah and his sons were over the Izharites, for the exterior works concerning Israel, in order to teach and to judge them.

[[first-chronicles-26-30]]
^30^ Now from the Hebronites, Hashabiah and his brothers, one thousand seven hundred very strong men, were in charge of Israel across the Jordan toward the west, in all the works of the Lord, and in the ministry of the king.

[[first-chronicles-26-31]]
^31^ And the leader of the Hebronites was Jerijah, according to their families and kindred. In the fortieth year of the reign of David, they were numbered, and there were found very strong men in Jazer Gilead.

[[first-chronicles-26-32]]
^32^ And his brothers of a mature age were two thousand seven hundred leaders of families. Then king David placed them in charge of the Reubenites, and the Gadites, and the one half tribe of Manasseh, in all of the ministries of God and of the king.


[[first-chronicles-27]]
== Chapter 27

[[first-chronicles-27-1]]
^1^ Now the sons of Israel, according to their number, the leaders of the families, the tribunes, and the centurions, and the chiefs, who were ministering to the king by their companies, entering and departing in each month of the year as they were in charge, were twenty-four thousand.

[[first-chronicles-27-2]]
^2^ Jashobeam, the son of Zabdiel, was in charge of the first company in the first month; and under him were twenty-four thousand.

[[first-chronicles-27-3]]
^3^ He was from the sons of Perez, and he was the leader of all the other leaders in the army, in the first month.

[[first-chronicles-27-4]]
^4^ The company of the second month had Dodai, an Ahohite; and after him there was another, named Mikloth, who ruled over a portion of the army of the twenty-four thousand.

[[first-chronicles-27-5]]
^5^ Also, the commander of the third company, in the third month, was Benaiah, the son of Jehoiada the priest; and in his division there were twenty-four thousand.

[[first-chronicles-27-6]]
^6^ The same is the Benaiah who was strongest among the thirty, and was above the thirty. But his son, Ammizabad, was in charge of his company.

[[first-chronicles-27-7]]
^7^ The fourth, for the fourth month, was Asahel, the brother of Joab, and his son Zebadiah after him; and in his company there were twenty-four thousand.

[[first-chronicles-27-8]]
^8^ The fifth leader, for the fifth month, was Shamhuth, an Izrahite; and in his company there were twenty-four thousand.

[[first-chronicles-27-9]]
^9^ The sixth, for the sixth month, was Ira, the son of Ikkesh, a Tekoite; and in his company there were twenty-four thousand.

[[first-chronicles-27-10]]
^10^ The seventh, for the seventh month, was Helez, a Pelonite from the sons of Ephraim; and in his company there were twenty-four thousand.

[[first-chronicles-27-11]]
^11^ The eighth, for the eighth month, was Sibbecai, a Hushathite from the stock of the Zerahites; and in his company there were twenty-four thousand.

[[first-chronicles-27-12]]
^12^ The ninth, for the ninth month, was Abiezer, an Anathothite from the sons of Benjamin; and in his company there were twenty-four thousand.

[[first-chronicles-27-13]]
^13^ The tenth, for the tenth month, was Maharai, and he was a Netophathite from the stock of the Zerahites; and in his company there were twenty-four thousand.

[[first-chronicles-27-14]]
^14^ The eleventh, for the eleventh month, was Benaiah, a Pirathonite from the sons of Ephraim; and in his company there were twenty-four thousand.

[[first-chronicles-27-15]]
^15^ The twelfth, for the twelfth month, was Heldai, a Netophathite from the stock of Othniel; and in his company there were twenty-four thousand.

[[first-chronicles-27-16]]
^16^ Now those who were first over the tribes of Israel were these: over the Reubenites, Eliezer, the son of Zichri, was the ruler; over the Simeonites, Shephatiah, the son of Maacah, was the ruler;

[[first-chronicles-27-17]]
^17^ over the Levites, Hashabiah, the son of Kemuel; over the Aaronites, Zadok;

[[first-chronicles-27-18]]
^18^ over Judah, Elihu, the brother of David; over Issachar, Omri, the son of Michael;

[[first-chronicles-27-19]]
^19^ over the Zebulunites, Ishmaiah, the son of Obadiah; over the Naphtalites, Jeremoth, the son of Azriel;

[[first-chronicles-27-20]]
^20^ over the sons of Ephraim, Hoshea, the son of Azaziah; over the one half tribe of Manasseh, Joel, the son of Pedaiah;

[[first-chronicles-27-21]]
^21^ and over the one half tribe of Manasseh in Gilead, Iddo, the son of Zechariah; then over Benjamin, Jaasiel, the son of Abner;

[[first-chronicles-27-22]]
^22^ yet truly, Azarel, the son of Jeroham, was over Dan. These were the leaders of the sons of Israel.

[[first-chronicles-27-23]]
^23^ But David was not willing to number them from twenty years old and under. For the Lord had said that he would multiply Israel like the stars of heaven.

[[first-chronicles-27-24]]
^24^ Joab, the son of Zeruiah, had begun to number, but he did not finish. For because of this, wrath had fallen upon Israel. And therefore the number of those who had been counted was not related in the official records of king David.

[[first-chronicles-27-25]]
^25^ Now over the storerooms of the king was Azmaveth, the son of Adiel. But Jonathan, the son of Uzziah, was over those storerooms that were in the cities, and in the villages, and in the towers.

[[first-chronicles-27-26]]
^26^ And over the farmlands and the farmers, those who worked the ground, was Ezri, the son of Chelub.

[[first-chronicles-27-27]]
^27^ And over the cultivators of vineyards was Shimei, a Ramathite; then over the wine cellars was Zabdi, an Aphonite.

[[first-chronicles-27-28]]
^28^ Now over the olive groves and the fig groves, which were in the plains, was Baal-hanan, a Gederite; and over the oil cellars was Joash.

[[first-chronicles-27-29]]
^29^ Now over the herds that were pastured in Sharon, Shitrai, a Sharonite, was in the first place; and over the oxen in the valleys, there was Shaphat, the son of Adlai.

[[first-chronicles-27-30]]
^30^ Truly, over the camels was Obil, an Ishmaelite; and over the donkeys was Jehdeiah, a Meronothite.

[[first-chronicles-27-31]]
^31^ And over the sheep was Jaziz, a Hagarene. All these were leaders over the substance of king David.

[[first-chronicles-27-32]]
^32^ Now Jonathan, the uncle of David, was a counselor, a prudent and scholarly man; he and Jehiel, the son of Hachmoni, were with the sons of the king.

[[first-chronicles-27-33]]
^33^ Now Ahithophel was the counselor of the king; and Hushai, the Archite, was the king’s friend.

[[first-chronicles-27-34]]
^34^ After Ahithophel was Jehoiada, the son of Benaiah, and Abiathar. But the leader of the army of the king was Joab.


[[first-chronicles-28]]
== Chapter 28

[[first-chronicles-28-1]]
^1^ And so David called together all the leaders of Israel, the rulers of the tribes, and those in charge of the companies, who were ministering to the king, and also the tribunes and centurions, and those in charge of the substance and possessions of the king, and his sons, with the eunuchs and the powerful and those most experienced in the army, at Jerusalem.

[[first-chronicles-28-2]]
^2^ And when the king had risen up and was standing, he said: “Listen to me, my brothers and my people. I thought that I would build a house, in which the ark of the covenant of the Lord, the footstool of our God, might rest. And so I prepared everything for its building.

[[first-chronicles-28-3]]
^3^ But God said to me: ‘You shall not build a house to my name, because you are a man of war, and have shed blood.’

[[first-chronicles-28-4]]
^4^ Now the Lord God of Israel chose me, out of the entire house of my father, so that I would be king over Israel forever. For from Judah he chose leaders; then from the house of Judah he chose the house of my father; and from the sons of my father, it pleased him to choose me as king over all of Israel.

[[first-chronicles-28-5]]
^5^ Then too, among my sons (for the Lord has given me many sons) he chose Solomon my son, so that he would sit upon the throne of the kingdom of the Lord, over Israel.

[[first-chronicles-28-6]]
^6^ And he said to me: ‘Solomon your son shall build my house and my courts. For I have chosen him to be to me as a son, and I will be to him as a father.

[[first-chronicles-28-7]]
^7^ And I will make firm his kingdom, even unto eternity, if he will persevere in doing my precepts and judgments, as also today.’

[[first-chronicles-28-8]]
^8^ Now therefore, before the entire assembly of Israel, in the hearing of our God, keep and seek all the commandments of the Lord our God, so that you may possess the good land, and may bequeath it to your sons after you, even forever.

[[first-chronicles-28-9]]
^9^ And as for you, my son Solomon, know the God of your father, and serve him with a perfect heart and a willing mind. For the Lord searches all hearts, and understands the thoughts of all minds. If you seek him, you will find him. But if you abandon him, he will cast you aside for eternity.

[[first-chronicles-28-10]]
^10^ Now therefore, since the Lord has chosen you, so that you would build the house of the Sanctuary, be strengthened and accomplish it.”

[[first-chronicles-28-11]]
^11^ Then David gave to his son Solomon a description of the portico, and the temple, and the storerooms, and the upper floor, and the innermost rooms, and the house of propitiation,

[[first-chronicles-28-12]]
^12^ and indeed also of all the courts that he had planned, and the outer rooms on all sides, for the treasuries of the house of the Lord, and for the treasuries of the holy things,

[[first-chronicles-28-13]]
^13^ and for the divisions of the priests and the Levites: concerning all the works of the house of the Lord and all the items in the ministry of the temple of the Lord.

[[first-chronicles-28-14]]
^14^ There was gold by weight for every vessel of the ministry, and also silver by weight for the diversity of vessels and equipment.

[[first-chronicles-28-15]]
^15^ Then too, he distributed gold for the lampstands and their lamps, according to the measure of each of the lampstands with their lamps. Similarly also, he distributed silver by weight for the silver lampstands with their lamps, according to the diversity of their measure.

[[first-chronicles-28-16]]
^16^ Also, he gave gold for the tables of the presence, according to the diversity of the tables; similarly too, he gave silver for the other tables of silver.

[[first-chronicles-28-17]]
^17^ Also, he distributed from the purest gold for the small hooks and the bowls and the censors, as well as for the little lions of gold, in accord with the precise measure of the weight, for lion after lion. Similarly too, for the lions of silver, he set aside a different weight of silver.

[[first-chronicles-28-18]]
^18^ Then, for the altar on which the incense was burned, he gave the purest gold. And from the same he made the likeness of the chariot of the Cherubim, with extended wings, which is veiling the ark of the covenant of the Lord.

[[first-chronicles-28-19]]
^19^ “All these things,” he said, “came to me written by the hand of the Lord, so that I would understand all the works of the pattern.”

[[first-chronicles-28-20]]
^20^ David also said to his son Solomon: “Act manfully, and be strengthened, and carry it out. You should not be afraid, and you should not be dismayed. For the Lord my God will be with you, and he will not send you away, nor will he abandon you, until you have perfected the entire work of the ministry of the house of the Lord.

[[first-chronicles-28-21]]
^21^ Behold, the divisions of the priests and the Levites, for every ministry of the house of the Lord, are standing before you. And they have been prepared, and so they know, both the leaders and the people, how to carry out all your precepts.”


[[first-chronicles-29]]
== Chapter 29

[[first-chronicles-29-1]]
^1^ And king David spoke to the entire assembly: “My son Solomon, the one God has chosen, is still a tender boy. And yet the work is great, for a habitation is being prepared, not for man, but for God.

[[first-chronicles-29-2]]
^2^ Now with all my ability, I have prepared the expenses for the house of my God: gold for items of gold, and silver for those of silver, brass for those of brass, iron for those of iron, and wood for those of wood, and stones of onyx, and stones like alabaster, and stones of diverse colors, and every kind of precious stone, and marble from Paros in great abundance.

[[first-chronicles-29-3]]
^3^ And in addition to these things that I have offered into the house of my God, I give, from my own belongings, gold and silver for the temple of my God, aside from those things that I have prepared for the holy shrine:

[[first-chronicles-29-4]]
^4^ three thousand talents of gold, from the gold of Ophir, and seven thousand talents of highly-refined silver, for the gilding of the walls of the temple;

[[first-chronicles-29-5]]
^5^ and gold for wherever there is need of gold, and silver for wherever there is need of silver, for the works to be done by the hands of the artisans. And if anyone freely offers, let him fill his hand this day, and let him offer whatever he wishes to the Lord.”

[[first-chronicles-29-6]]
^6^ And so the leaders of the families, and the nobles of the tribes of Israel, as well as the tribunes and the centurions and the overseers of the king’s possessions, promised

[[first-chronicles-29-7]]
^7^ and gave, for the works of the house of the Lord, five thousand talents and ten thousand pieces of gold, ten thousand talents of silver, and eighteen thousand talents of brass, and also one hundred thousand talents of iron.

[[first-chronicles-29-8]]
^8^ And whoever found precious stones among their belongings gave them to the treasuries of the house of the Lord, by the hand of Jehiel the Gershonite.

[[first-chronicles-29-9]]
^9^ And the people rejoiced, since they were promising their votive offerings willingly. For they were offering these to the Lord with all their heart. And king David also rejoiced with great gladness.

[[first-chronicles-29-10]]
^10^ And he blessed the Lord before the entire multitude, and he said: “Blessed are you, O Lord God of Israel, our Father from eternity to eternity.

[[first-chronicles-29-11]]
^11^ Yours, O Lord, is magnificence and power and glory, and also victory; and to you is praise. For all the things that are in heaven and on earth are yours. Yours is the kingdom, O Lord, and you are above all rulers.

[[first-chronicles-29-12]]
^12^ Yours is wealth, and yours is glory. You have dominion over all things. In your hand is virtue and power. In your hand is greatness and authority over all things.

[[first-chronicles-29-13]]
^13^ Now therefore, we confess to you, our God, and we praise your famous name.

[[first-chronicles-29-14]]
^14^ Who am I, and what is my people, that we should be able to promise all these things to you? All is yours. And so the things that we received from your hand, we have given to you.

[[first-chronicles-29-15]]
^15^ For we are sojourners and new arrivals before you, as all our fathers were. Our days upon the earth are like a shadow, and there is no delay.

[[first-chronicles-29-16]]
^16^ O Lord our God, all this abundance, which we have prepared so that a house may be built to your holy name, is from your hand, and all things are yours.

[[first-chronicles-29-17]]
^17^ I know, my God, that you test hearts, and that you love simplicity. Therefore, in the simplicity of my heart, I also have offered all these things joyfully. And I have seen, with immense gladness, your people, who have been found here, offering their donations to you.

[[first-chronicles-29-18]]
^18^ O Lord, the God of our fathers Abraham and Isaac and Israel, preserve unto eternity this desire of their heart, and let this purpose remain forever, for the worship of you.

[[first-chronicles-29-19]]
^19^ Also, I give to my son Solomon a perfect heart, so that he may keep your commandments, your testimonies, and your ceremonies, and so that he may accomplish all things, and may build the temple, for which I have prepared the expenses.”

[[first-chronicles-29-20]]
^20^ Then David instructed the entire assembly: “Bless the Lord our God.” And the entire assembly blessed the Lord, the God of their fathers. And they bowed themselves, and they adored God, and next they reverenced the king.

[[first-chronicles-29-21]]
^21^ And they immolated victims to the Lord. And they offered holocausts on the following day: one thousand bulls, one thousand rams, one thousand lambs, with their libations and with every ritual, very abundantly, for all of Israel.

[[first-chronicles-29-22]]
^22^ And they ate and drank before the Lord on that day, with great rejoicing. And they anointed Solomon, the son of David, a second time. And they anointed him to the Lord as the ruler, and Zadok as the high priest.

[[first-chronicles-29-23]]
^23^ And Solomon sat upon the throne of the Lord as king, in place of his father David, and it pleased everyone. And all of Israel obeyed him.

[[first-chronicles-29-24]]
^24^ Moreover, all the leaders, and the powerful, and all the sons of king David pledged with their hand, and they became subject to king Solomon.

[[first-chronicles-29-25]]
^25^ Then the Lord magnified Solomon over all of Israel. And he gave to him a glorious reign, of a kind such as no one has had before him, as king of Israel.

[[first-chronicles-29-26]]
^26^ Now David, the son of Jesse, reigned over all of Israel.

[[first-chronicles-29-27]]
^27^ And the days during which he reigned over Israel were forty years. He reigned seven years in Hebron, and thirty-three years in Jerusalem.

[[first-chronicles-29-28]]
^28^ And he died at a good old age, full of days and wealth and glory. And his son Solomon reigned in his place.

[[first-chronicles-29-29]]
^29^ Now the acts of king David, from the first to the last, have been written in the book of Samuel the seer, and in the book of Nathan the prophet, and in the book of Gad the seer,

[[first-chronicles-29-30]]
^30^ concerning his entire reign and strength, and the times that passed under him, both in Israel and in all the kingdoms of the lands.
