[[tobit]]
= Tobit

[[tobit-1]]
== Chapter 1

[[tobit-1-1]]
^1^ Tobit was from the tribe and city of Naphtali (which is in the upper parts of Galilee above Asher, after the way, which leads to the west, that has on its left the city of Sephet).

[[tobit-1-2]]
^2^ Although he had been taken captive in the days of Shalmaneser, the king of the Assyrians, even in such a situation as captivity, he did not desert the way of truth.

[[tobit-1-3]]
^3^ So then, every day, all that he was able to obtain, he bestowed on his fellow captive brothers, who were from his kindred.

[[tobit-1-4]]
^4^ And, when he was among the youngest of any in the tribe of Naphtali, he showed not so much as any childish behavior in his work.

[[tobit-1-5]]
^5^ And then, when all went to the golden calves which Jeroboam, king of Israel, had made, he alone fled from the company of them all.

[[tobit-1-6]]
^6^ Yet he continued on to Jerusalem, to the temple of the Lord, and there he adored the Lord God of Israel, offering faithfully all his first-fruits and his tithes.

[[tobit-1-7]]
^7^ So then, in the third year, he administered all his tithes to new converts and to new arrivals.

[[tobit-1-8]]
^8^ These and similar such things, even as a boy, he observed according to the law of God.

[[tobit-1-9]]
^9^ Truly, when he had become a man, he received as wife Anna of his own tribe, and he conceived a son by her, to whom he assigned his own name.

[[tobit-1-10]]
^10^ From his infancy, he taught him to fear God and to abstain from all sin.

[[tobit-1-11]]
^11^ Therefore, when, during the captivity, he had arrived with his wife and son at the city of Nineveh, with all his tribe,

[[tobit-1-12]]
^12^ (even though they all ate from the foods of the Gentiles,) he guarded his soul and never was contaminated with their foods.

[[tobit-1-13]]
^13^ And because he was mindful of the Lord with his whole heart, God gave him favor in the sight of Shalmaneser the king.

[[tobit-1-14]]
^14^ And he gave him the power to go wherever he would want, having the freedom to do whatever he wished.

[[tobit-1-15]]
^15^ Therefore, he continued on to all who were in captivity, and he gave them helpful advice.

[[tobit-1-16]]
^16^ But when he had arrived at Rages, a city of the Medes, he had ten talents of silver, from that which he had been given in honor by the king.

[[tobit-1-17]]
^17^ And when, in the midst of the great tumult of his kindred, he saw the destitution of Gabael, who was from his tribe, he loaned him, under a written agreement, the aforementioned weight of silver.

[[tobit-1-18]]
^18^ In truth, after a long time, Shalmaneser the king died, while Sennacherib his son reigned in his place, and he held a hatred for the sons of Israel.

[[tobit-1-19]]
^19^ Every day, Tobit traveled through all his own people, and he consoled them, and he distributed to each one as much as he could from his resources.

[[tobit-1-20]]
^20^ He nourished the hungry, and he supplied clothes to the naked, and he showed concern for the burial of the dead and of the slain.

[[tobit-1-21]]
^21^ And then, when king Sennacherib had returned from Judea, fleeing the scourge which God had caused all around him because of his blasphemy, and, being angry, he was slaughtering many from the sons of Israel, Tobit buried their bodies.

[[tobit-1-22]]
^22^ And when it was reported to the king, he ordered him to be slain, and he took away all his belongings.

[[tobit-1-23]]
^23^ In truth, Tobit, fleeing with nothing but his son and his wife, was able to remain hidden because many loved him.

[[tobit-1-24]]
^24^ In truth, after forty-five days, the king was slain by his own sons,

[[tobit-1-25]]
^25^ and Tobit was able to return to his house, and all his resources were restored to him.


[[tobit-2]]
== Chapter 2

[[tobit-2-1]]
^1^ In truth, after this, when there was a feast day of the Lord, and a good dinner had been prepared in the house of Tobit,

[[tobit-2-2]]
^2^ he said to his son: “Go, and bring some others who fear God from our tribe to feast with us.”

[[tobit-2-3]]
^3^ And after he had gone, returning, he reported to him that one of the sons of Israel, with his throat cut, was lying in the street. And immediately, he leapt from his place reclining at table, left behind his dinner, and went forth with fasting to the body.

[[tobit-2-4]]
^4^ And taking it up, he carried it in secret to his house, so that, after the sun had set, he might bury him cautiously.

[[tobit-2-5]]
^5^ And after he had hidden the body, he chewed his bread with mourning and fear,

[[tobit-2-6]]
^6^ remembering the word that the Lord spoke through the prophet Amos: “Your feast days shall be turned into lamentation and mourning.”

[[tobit-2-7]]
^7^ Truly, when the sun had set, he went out, and he buried him.

[[tobit-2-8]]
^8^ Yet all his neighbors argued with him, saying: “Now, an order was given to execute you because of this matter, and you barely escaped a death sentence, and again you are burying the dead?”

[[tobit-2-9]]
^9^ But Tobit, fearing God more than the king, stole away the bodies of the slain and concealed them in his house, and in the middle of the night, he buried them.

[[tobit-2-10]]
^10^ But it happened one day, being tired from burying the dead, he came into his house, and he threw himself down next to the wall, and he slept.

[[tobit-2-11]]
^11^ And, as he was sleeping, warm droppings from a swallow’s nest fell upon his eyes, and he was made blind.

[[tobit-2-12]]
^12^ And so the Lord permitted this trial to befall him, in order that an example might be given to posterity of his patience, which is even like that of holy Job.

[[tobit-2-13]]
^13^ For, even from his infancy, he had always feared God and kept his commandments, so he was not discouraged before God because of the scourge of blindness that had befallen him.

[[tobit-2-14]]
^14^ But he remained immoveable in the fear of God, giving thanks to God all the days of his life.

[[tobit-2-15]]
^15^ For just as kings have mocked blessed Job, so also his relatives and acquaintances ridiculed his life, saying:

[[tobit-2-16]]
^16^ “Where is your hope, on behalf of which you gave alms and buried the dead?”

[[tobit-2-17]]
^17^ In truth, Tobit corrected them, saying: “Do not speak in this way,

[[tobit-2-18]]
^18^ for we are the sons of the holy ones, and we look forward to that life which God will give to those who never change in their faith before him.”

[[tobit-2-19]]
^19^ In truth, his wife Anna went out to weaving work daily, and she brought back the provisions that she was able to obtain by the labor of her hands.

[[tobit-2-20]]
^20^ Whereupon it happened that, having received a young goat, she brought it home.

[[tobit-2-21]]
^21^ When her husband heard the sound of its bleating, he said, “Look, so that it might not be stolen, return it to its owners, for it is not lawful for us either to eat, or to touch, anything stolen.”

[[tobit-2-22]]
^22^ At this, his wife, being angry, answered, “Clearly, your hope has become vanity, and the manner of your almsgiving has become apparent.”

[[tobit-2-23]]
^23^ And with these and other similar such words, she reproached him.


[[tobit-3]]
== Chapter 3

[[tobit-3-1]]
^1^ Then Tobit sighed, and he began to pray with tears,

[[tobit-3-2]]
^2^ saying, “O Lord, you are just and all your judgments are just, and all your ways are mercy, and truth, and judgment.

[[tobit-3-3]]
^3^ And now, O Lord, remember me, and do not take vengeance for my sins, and do not call to mind my offenses, nor those of my parents.

[[tobit-3-4]]
^4^ For we have not obeyed your precepts, and so we have been handed over to plundering and to captivity, and to death, and to mockery, and as a disgrace before all the nations, among which you have dispersed us.

[[tobit-3-5]]
^5^ And now, O Lord, great are your judgments. For we have not acted according to your precepts, and we have not walked sincerely before you.

[[tobit-3-6]]
^6^ And now, O Lord, do with me according to your will, and order my spirit to be received in peace. For it is more expedient for me to die, than to live.”

[[tobit-3-7]]
^7^ And so, on the same day, it happened that Sarah, the daughter of Raguel, in Rages, a city of the Medes, also heard a reproach from one of her father’s servant maids.

[[tobit-3-8]]
^8^ For she had been given to seven husbands, and a demon named Asmodeus had killed them, as soon as they had approached her.

[[tobit-3-9]]
^9^ Therefore, when she corrected the maid for her fault, she answered her, saying, “May we never see son or daughter from you upon the earth, you murderess of your husbands.

[[tobit-3-10]]
^10^ Would you also kill me, just as you have already killed seven husbands?” At these words, she proceeded to an upper room of her house. And for three days and three nights, she did not eat or drink.

[[tobit-3-11]]
^11^ But, continuing in prayer with tears, she beseeched God, so that he would liberate her from this reproach.

[[tobit-3-12]]
^12^ And it happened on the third day, while she was completing her prayer, blessing the Lord,

[[tobit-3-13]]
^13^ that she said: “Blessed is your name, O God of our fathers, who, though you had been angry, will show mercy. And in time of tribulation, you dismiss the sins of those who call upon you.

[[tobit-3-14]]
^14^ To you, O Lord, I turn my face; to you, I direct my eyes.

[[tobit-3-15]]
^15^ I beg you, O Lord, that you may absolve me from the chains of this reproach, or at least take me away from the earth.

[[tobit-3-16]]
^16^ You know, O Lord, that I have never coveted a husband, and I have preserved my soul clean from all impure desire.

[[tobit-3-17]]
^17^ I have never mingled myself with those who play. And I have not presented myself as a participant with those who walk with levity.

[[tobit-3-18]]
^18^ But I consented to accept a husband, in your fear, not in my lust.

[[tobit-3-19]]
^19^ And, either I was unworthy of them, or they perhaps were not worthy of me. For perhaps you have preserved me for another husband.

[[tobit-3-20]]
^20^ For your counsel is not within the ability of man.

[[tobit-3-21]]
^21^ But all who worship you are certain of this: that one’s life, if it should be tested, shall be crowned, and if it should be in tribulation, shall be delivered, and if it should be corrected, shall be permitted to approach your mercy.

[[tobit-3-22]]
^22^ For you are not delighted with our perdition. For, after a storm, you create tranquility, and after tears and weeping, you pour out exultation.

[[tobit-3-23]]
^23^ May your name, O God of Israel, be blessed forever.”

[[tobit-3-24]]
^24^ At that time, the prayers of them both were heard in the sight of the glory of the most high God.

[[tobit-3-25]]
^25^ And the holy Angel of the Lord, Raphael, was sent to care for both of them, whose prayers were recited at the same time in the sight of the Lord.


[[tobit-4]]
== Chapter 4

[[tobit-4-1]]
^1^ Therefore, when Tobit considered that his prayer was heard, so that he might be able to die, he called his son Tobias to him.

[[tobit-4-2]]
^2^ And he said to him: “My son, hear the words of my mouth, and set them, like a foundation, in your heart.

[[tobit-4-3]]
^3^ When God will receive my soul, bury my body. And you shall honor your mother, all the days of her life.

[[tobit-4-4]]
^4^ For you are obliged to be mindful of what great perils she suffered because of you in her womb.

[[tobit-4-5]]
^5^ But when she too will have completed the time of her life, bury her near me.

[[tobit-4-6]]
^6^ Yet, for all the days of your life, have God in your mind. And be careful that you never consent to sin, nor overlook the precepts of the Lord our God.

[[tobit-4-7]]
^7^ Give alms from your substance, and do not turn away your face from any pauper. For so it shall be that neither will the face of the Lord be turned away from you.

[[tobit-4-8]]
^8^ In whatever way that you are able, so shall you be merciful.

[[tobit-4-9]]
^9^ If you have much, distribute abundantly. If you have little, nevertheless strive to bestow a little freely.

[[tobit-4-10]]
^10^ For you store up for yourself a good reward for the day of necessity.

[[tobit-4-11]]
^11^ For almsgiving liberates from every sin and from death, and it will not suffer the soul to go into darkness.

[[tobit-4-12]]
^12^ Almsgiving will be a great act of faith before the most high God, for all those who practice it.

[[tobit-4-13]]
^13^ Take care to keep yourself, my son, from all fornication, and, except for your wife, never permit yourself to know such an offense.

[[tobit-4-14]]
^14^ Never permit arrogance to rule in your mind or in your words. For in it, all perdition had its beginning.

[[tobit-4-15]]
^15^ And whoever has done any kind of work for you, immediately pay him his wages, and do not let the wages of your hired hand remain with you at all.

[[tobit-4-16]]
^16^ Whatever you would hate to have done to you by another, see that you never do so to another.

[[tobit-4-17]]
^17^ Eat your bread with the hungry and the needy, and cover the naked with your own garments.

[[tobit-4-18]]
^18^ Set out your bread and your wine at the burial of a just man, and do not eat and drink from it with sinners.

[[tobit-4-19]]
^19^ Always seek the counsel of a wise man.

[[tobit-4-20]]
^20^ Bless God at all times. And petition him that he direct your ways and that all your counsels may remain in him.

[[tobit-4-21]]
^21^ And now, I reveal to you, my son, that I lent ten talents of silver, while you were still a young child, to Gabael, in Rages, a city of the Medes, and I have his written agreement with me.

[[tobit-4-22]]
^22^ And so, inquire how you may travel to him and receive from him the aforementioned weight of silver, and return to him the written agreement.

[[tobit-4-23]]
^23^ Do not be afraid, my son. We do indeed lead a poor life, but we will have many good things: if we fear God, and withdraw from all sin, and do what is good.”


[[tobit-5]]
== Chapter 5

[[tobit-5-1]]
^1^ Then Tobias responded to his father, and he said: “I will do everything just as you have instructed me, father.

[[tobit-5-2]]
^2^ But I do not know how to obtain this money. He does not know me, and I do not know him. What proof shall I give to him? And I do not know any part of the way, which leads to that place.”

[[tobit-5-3]]
^3^ Then his father answered him, and he said: “Indeed, I have a written agreement about that in my possession, which, when you show it to him, he will immediately repay it.

[[tobit-5-4]]
^4^ But go out now, and inquire after some faithful man, who would go with you to keep you safe in return for his wages, so that you may receive it while I am still alive.”

[[tobit-5-5]]
^5^ Then Tobias, departing, found a splendid young man, standing girded and seemingly ready for travel.

[[tobit-5-6]]
^6^ And not knowing that he was an Angel of God, he greeted him, and he said, “Where are you from, good young man?”

[[tobit-5-7]]
^7^ And so he answered, “From the sons of Israel.” And Tobias said to him, “Do you know the way that leads to the region of the Medes?”

[[tobit-5-8]]
^8^ And he answered: “I know it. And I have frequently walked through all its paths, and I stayed with Gabael, our brother, who lives in Rages, a city of the Medes, which is situated at the mount of Ecbatana.”

[[tobit-5-9]]
^9^ Tobias said to him, “I implore you, wait here for me, until I tell these same things to my father.”

[[tobit-5-10]]
^10^ Then Tobias, entering, revealed all these things to his father. Upon which, his father, in admiration, asked that he would enter to him.

[[tobit-5-11]]
^11^ And so, entering, he greeted him, and he said, “May gladness be always with you.”

[[tobit-5-12]]
^12^ And Tobit said, “What kind of gladness will be for me, since I sit in darkness and do not see the light of heaven?”

[[tobit-5-13]]
^13^ And the young man said to him, “Be steadfast in soul. Your cure from God is near.”

[[tobit-5-14]]
^14^ And so Tobit said to him, “Are you able to lead my son to Gabael in Rages, a city of the Medes? And when you return, I will pay you your wages.”

[[tobit-5-15]]
^15^ And the Angel said to him, “I will lead him, and I will bring him back to you.”

[[tobit-5-16]]
^16^ And Tobit responded to him, “I ask you to tell me: which family or which tribe are you from?”

[[tobit-5-17]]
^17^ And Raphael the Angel said, “Do you seek the family of the one you hire, or else the hired hand himself, to go with your son?

[[tobit-5-18]]
^18^ But, lest perhaps I cause you to worry: I am Azariah, the son of Hananiah the great.”

[[tobit-5-19]]
^19^ And Tobit responded, “You are from a great family. But I ask you, do not be angry that I wanted to know your family.”

[[tobit-5-20]]
^20^ But the Angel said to him, “I will lead your son safely, and I will bring him back safely to you.”

[[tobit-5-21]]
^21^ And so Tobit, answering, said, “May you walk well, and may God be with you on your journey, and may his Angel accompany you.”

[[tobit-5-22]]
^22^ Then, when all things were ready which were to be carried on their journey, Tobias said farewell to his father, and to his mother, and the two of them walked together.

[[tobit-5-23]]
^23^ And when they had set out, his mother began to weep, and to say: “You have taken the staff of our old age, and you have sent him away from us.

[[tobit-5-24]]
^24^ I wish that the money, for which you sent him, had never been.

[[tobit-5-25]]
^25^ For our poverty has been sufficient for us, so that we might count it as riches that we saw our son.”

[[tobit-5-26]]
^26^ And Tobit said to her: “Do not weep. Our son will arrive safely, and he will return safely to us, and your eyes shall see him.

[[tobit-5-27]]
^27^ For I believe that the good Angel of God accompanies him and that he orders all things well which occur around him, such that he will be returned to us with gladness.”

[[tobit-5-28]]
^28^ At these words, his mother ceased weeping, and she was silent.


[[tobit-6]]
== Chapter 6

[[tobit-6-1]]
^1^ And so Tobias continued on, and the dog was following him, and he stayed at the first stopping point, near the river Tigris.

[[tobit-6-2]]
^2^ And he went out to wash his feet, and behold, an immense fish came out to devour him.

[[tobit-6-3]]
^3^ And Tobias, being frightened of it, cried out with a loud voice, saying, “Sir, it is attacking me!”

[[tobit-6-4]]
^4^ And the Angel said to him, “Catch it by the gills, and draw it to you.” And when he had done so, he pulled it onto dry land, and it began to thrash before his feet.

[[tobit-6-5]]
^5^ Then the Angel said to him: “Disembowel this fish, and put aside his heart, and his gall, and his liver for yourself. For these things are necessary as useful medicines.”

[[tobit-6-6]]
^6^ And when he had done so, he roasted its flesh, and they took it with them on the way. The rest they salted, so that it might be sufficient for them, until they would arrive at Rages, a city of the Medes.

[[tobit-6-7]]
^7^ Then Tobias questioned the Angel, and he said to him, “I implore you, brother Azariah, to tell me what remedies these things hold, which you have told me to retain from the fish?”

[[tobit-6-8]]
^8^ And the Angel, answering, said to him: “If you put a little piece of its heart on burning coals, its smoke will drive away all kinds of demons, whether from a man or from a woman, so that they will no longer approach them.

[[tobit-6-9]]
^9^ And the gall is useful for anointing the eyes, in which there may be a white speck, and they will be cured.”

[[tobit-6-10]]
^10^ And Tobias said to him, “Where do you prefer that we stay?”

[[tobit-6-11]]
^11^ And the Angel, responding, said: “Here is one named Raguel, a man closely related to you from your tribe, and he has a daughter named Sarah, but he has no other male or female, except her.

[[tobit-6-12]]
^12^ All his livelihood is dependent upon you, and you ought to take her to yourself in marriage.

[[tobit-6-13]]
^13^ Therefore, ask for her from her father, and he will give her to you as wife.”

[[tobit-6-14]]
^14^ Then Tobias responded, and he said: “I hear that she has been given to seven husbands, and they passed away. But I have even heard this: that a demon killed them.

[[tobit-6-15]]
^15^ Therefore, I am afraid, lest this may happen to me also. And since I am the only child of my parents, I might send their old age with sorrow to the grave.”

[[tobit-6-16]]
^16^ Then the Angel Raphael said to him: “Listen to me, and I will reveal to you who they are, over whom the demon can prevail.

[[tobit-6-17]]
^17^ For example, those who receive marriage in such manner as to exclude God from themselves and from their mind, and in such a manner as to empty themselves to their lust, like the horse and mule, which have no understanding, over them the demon has power.

[[tobit-6-18]]
^18^ But you, when you will have accepted her, enter the bedroom and for three days keep yourself continent from her, and empty yourself to nothing other than prayers with her.

[[tobit-6-19]]
^19^ Moreover, on that night, burn the liver of the fish like incense, and the demon will be put to flight.

[[tobit-6-20]]
^20^ In truth, on the second night, you will become ready to receive a physical union like that of the holy Patriarchs.

[[tobit-6-21]]
^21^ And then, on the third night, you will obtain a blessing, so that healthy children may be procreated from you both.

[[tobit-6-22]]
^22^ And so, the third night having been accomplished, you will receive the virgin with the fear of the Lord, led more by love of children than by physical desire, so that, as the offspring of Abraham, you will then obtain a blessing in children.


[[tobit-7]]
== Chapter 7

[[tobit-7-1]]
^1^ And so they went to Raguel, and Raguel received them with gladness.

[[tobit-7-2]]
^2^ And Raguel, gazing upon Tobias, said to Anna his wife, “How much like my cousin is this young man!”

[[tobit-7-3]]
^3^ And when he had spoken this, he said, “Which of our brethren are you from, young men?”

[[tobit-7-4]]
^4^ But they said, “We are from the tribe of Naphtali, from the captivity of Nineveh.”

[[tobit-7-5]]
^5^ And Raguel said to them, “Do you know my brother Tobit?” They said to him, “We know him.”

[[tobit-7-6]]
^6^ And since he was saying many good things about him, the Angel said to Raguel, “The Tobit about whom you inquire is the father of this young man.”

[[tobit-7-7]]
^7^ And Raguel threw himself towards him and kissed him with tears and weeping upon his neck, saying, “May a blessing be upon you, my son, because you are the son of a good and most noble man.”

[[tobit-7-8]]
^8^ And his wife Anna, and their daughter Sarah, were weeping.

[[tobit-7-9]]
^9^ And so, after they had spoken, Raguel instructed a sheep to be killed, and a feast to be prepared. And when he exhorted them to recline for dinner,

[[tobit-7-10]]
^10^ Tobias said, “Here, today, I will not eat or drink, unless you first confirm my petition, and promise to give Sarah your daughter to me.”

[[tobit-7-11]]
^11^ When Raguel heard this word, he became afraid, knowing what had befallen those seven men, who had approached her. And he began to fear, lest it might happen to him also in the same way. And, since he wavered and gave no further response to the petition,

[[tobit-7-12]]
^12^ the Angel said to him: “Do not be afraid to give her to this one, because this one fears God. He is obliged to be joined to your daughter. Because of this, no other one could have her.”

[[tobit-7-13]]
^13^ Then Raguel said: “I do not doubt that God has admitted my prayers and tears before his sight.

[[tobit-7-14]]
^14^ And I believe, therefore, that he has caused you to come to me, so that this one might be joined in marriage to one of her own kindred, according to the law of Moses. And now, do not continue to doubt that I will give her to you.”

[[tobit-7-15]]
^15^ And taking the right hand of his daughter, he gave it into the right hand of Tobias, saying, “May the God of Abraham, and the God of Isaac, and the God of Jacob be with you. And may he join you together in marriage and fulfill his blessing in you.”

[[tobit-7-16]]
^16^ And taking paper, they made a written record of the marriage.

[[tobit-7-17]]
^17^ And after this, they feasted, blessing God.

[[tobit-7-18]]
^18^ And Raguel called his wife Anna to him, and he instructed her to prepare another bedroom.

[[tobit-7-19]]
^19^ And she brought her daughter Sarah into it, and she was weeping.

[[tobit-7-20]]
^20^ And she said to her, “Be steadfast in spirit, my daughter. May the Lord of heaven give you gladness in place of the grief that you have had to endure.”


[[tobit-8]]
== Chapter 8

[[tobit-8-1]]
^1^ In truth, after they had dined, they introduced the young man to her.

[[tobit-8-2]]
^2^ And so, Tobias, remembering the word of the Angel, took part of the liver from his bag, and he placed it over the live coals.

[[tobit-8-3]]
^3^ Then the Angel Raphael caught the demon, and bound him in the desert of upper Egypt.

[[tobit-8-4]]
^4^ Then Tobias exhorted the virgin, and he said to her: “Sarah, get up and let us pray to God this day, and tomorrow, and the following day. For, during these three nights, we are being joined to God. And then, when the third night has passed, we ourselves will be joined together.

[[tobit-8-5]]
^5^ For certainly, we are the children of the saints, and we must not be joined together in such a manner as the heathens, who are ignorant of God.”

[[tobit-8-6]]
^6^ And so, rising up together, they both prayed earnestly, at the same time, that health might be given to them.

[[tobit-8-7]]
^7^ And Tobias said: “Lord, the God of our fathers, may the heavens and the earth bless you, and the sea, and the fountains, and the rivers, and all your creatures that are in them.

[[tobit-8-8]]
^8^ You formed Adam from the mud of the earth, and you gave Eve to him as a helper.

[[tobit-8-9]]
^9^ And now, O Lord, you know that I take my sister in conjugal union, not by reason of worldly pleasure, but solely for the love of posterity, in which your name may be blessed forever and ever.”

[[tobit-8-10]]
^10^ Sarah likewise said, “Be merciful to us, O Lord, be merciful to us. And let us both grow old together in health.”

[[tobit-8-11]]
^11^ And it happened, about the time of the rooster’s crowing, that Raguel ordered his servants to be summoned, and they went out with him together to dig a grave.

[[tobit-8-12]]
^12^ For he said, “Lest perhaps, in the same way, it may have happened to him, as it did also to the other seven men who approached her.”

[[tobit-8-13]]
^13^ And when they had prepared the pit, Raguel returned to his wife, and he said to her,

[[tobit-8-14]]
^14^ “Send one of your maids, and let her see if he is dead, so that I may bury him before the dawn of day.”

[[tobit-8-15]]
^15^ And so, she sent one of her maidservants, who entered the bedroom and discovered them safe and unharmed, sleeping both together.

[[tobit-8-16]]
^16^ And returning, she reported the good news. And they blessed the Lord: Raguel, especially, and his wife Anna.

[[tobit-8-17]]
^17^ And they said: “We bless you, Lord God of Israel, because it has not happened in the way that we thought it might.

[[tobit-8-18]]
^18^ For you have acted in your mercy toward us, and you have excluded from us the enemy who pursued us.

[[tobit-8-19]]
^19^ Moreover, you have had compassion on two only children. Make them, O Lord, able to bless you more fully and to offer you a sacrifice of your praise and of their health, so that all peoples everywhere may know that you alone are God in all the earth.”

[[tobit-8-20]]
^20^ And immediately Raguel instructed his servants to refill the pit, which they had made, before daylight.

[[tobit-8-21]]
^21^ And then he told his wife to make ready a feast, and to prepare all the provisions that are necessary for those who undertake a journey.

[[tobit-8-22]]
^22^ Likewise, he caused two fat cows and four rams to be killed, and a banquet to be prepared for all his neighbors and every one of his friends.

[[tobit-8-23]]
^23^ And Raguel pleaded with Tobias to delay with him for two weeks.

[[tobit-8-24]]
^24^ Moreover, of all the things that Raguel possessed, he gave one half part to Tobias, and he made a writing, so that the half that remained should also pass into the ownership of Tobias, after their deaths.


[[tobit-9]]
== Chapter 9

[[tobit-9-1]]
^1^ Then Tobias called the Angel to him, whom he indeed considered to be a man, and he said to him: “Brother Azariah, I implore you to listen to my words:

[[tobit-9-2]]
^2^ If I should give myself to be your servant, I would not be equally worthy of your providence.

[[tobit-9-3]]
^3^ Even so, I beg you to take with you beasts or even servants, and to go to Gabael in Rages, the city of the Medes, and restore to him his handwritten note, and receive from him the money, and petition him to come to my wedding celebration.

[[tobit-9-4]]
^4^ For you know that my father numbers the days. And if I delay one day more, his soul will be afflicted.

[[tobit-9-5]]
^5^ And surely you see how Raguel has obtained my oath, an oath that I am not able to spurn.”

[[tobit-9-6]]
^6^ Then Raphael borrowed four of the servants of Raguel, and two camels, and he traveled to Rages, the city of the Medes. And upon finding Gabael, he gave him his handwritten note, and he received from him all the money.

[[tobit-9-7]]
^7^ And he revealed to him, concerning Tobias the son of Tobit, all that had been done. And he made him come with him to the wedding celebration.

[[tobit-9-8]]
^8^ And when he had entered into the house of Raguel, he discovered Tobias reclining at table. And leaping up, they kissed each other. And Gabael wept, and he blessed God.

[[tobit-9-9]]
^9^ And he said: “May the God of Israel bless you, for you are the son of a man most noble and just, fearing God and performing almsgiving.

[[tobit-9-10]]
^10^ And may a blessing be spoken over your wife and over your parents.

[[tobit-9-11]]
^11^ And may you see your sons, and the sons of your sons, even to the third and fourth generation. And may your offspring be blessed by the God of Israel, who reigns forever and ever.”

[[tobit-9-12]]
^12^ And when all had said, “Amen,” they approached the feast. But they also celebrated the marriage feast with the fear of the Lord.


[[tobit-10]]
== Chapter 10

[[tobit-10-1]]
^1^ In truth, when Tobias was delayed because of the marriage celebration, his father Tobit was worried, saying: “Why do you think my son is delayed, or why has he been detained there?

[[tobit-10-2]]
^2^ Do you think that Gabael has died, and that no one will repay him the money?”

[[tobit-10-3]]
^3^ And so he began to be exceedingly sad, both he and his wife Anna with him. And they both began to weep together, because their son did not at least return to them on the appointed day.

[[tobit-10-4]]
^4^ But his mother wept inconsolable tears, and also said: “Woe, woe to me, O my son. Why did we send you to journey far away, you: the light of our eyes, the staff of our old age, the solace of our life, the hope of our posterity?

[[tobit-10-5]]
^5^ Having all things together as one in you, we ought not to have dismissed you from us.”

[[tobit-10-6]]
^6^ And Tobit was saying to her: “Be calm, and do not be troubled. Our son is safe. That man, with whom we sent him, is faithful enough.”

[[tobit-10-7]]
^7^ Yet she was by no means able to be consoled. But, leaping up every day, she looked all round, and traveled around all the ways, by which there seemed any hope that he might return, so that she might possibly see him coming from afar.

[[tobit-10-8]]
^8^ In truth, Raguel said to his son-in-law, “Remain here, and I will send a message of your health to your father Tobit.”

[[tobit-10-9]]
^9^ And Tobias said to him, “I know that my father and my mother have now counted the days, and their spirit must be tortured within them.”

[[tobit-10-10]]
^10^ And when Raguel had repeatedly petitioned Tobias, and he was by no means willing to listen to him, he delivered Sarah to him, and half of all his substance: with men and women servants, with sheep, camels, and cows, and with much money. And he dismissed him away, in safety and gladness, from him,

[[tobit-10-11]]
^11^ saying: “May the holy Angel of the Lord be with your journey, and may he lead you through unharmed, and may you discover that all is right concerning your parents, and may my eyes see your sons before I die.”

[[tobit-10-12]]
^12^ And the parents, taking hold of their daughter, kissed her and let her go:

[[tobit-10-13]]
^13^ admonishing her to honor her father-in-law, to love her husband, to guide the family, to govern the household, and to behave irreproachably herself.


[[tobit-11]]
== Chapter 11

[[tobit-11-1]]
^1^ And as they were returning, they came through to Haran, which is in the middle of the journey, opposite Nineveh, on the eleventh day.

[[tobit-11-2]]
^2^ And the Angel said: “Brother Tobias, you know how you left behind your father.

[[tobit-11-3]]
^3^ And so, if it pleases you, let us go on ahead, and let the family follow after us with a slower step, together with your bride, and with the animals.”

[[tobit-11-4]]
^4^ And since it pleased him to go on in this way, Raphael said to Tobias, “Take with you from the gall of the fish, for it will be necessary.” And so, Tobias took from its gall, and he went ahead.

[[tobit-11-5]]
^5^ But Anna sat beside the way every day, on the top of a hill, from where she would be able to see for a long distance.

[[tobit-11-6]]
^6^ And while she was watching for his arrival from that place, she looked far off, and soon she realized that her son was approaching. And running, she reported it to her husband, saying: “Behold, your son arrives.”

[[tobit-11-7]]
^7^ And Raphael said to Tobias: “As soon as you enter into your house, immediately adore the Lord your God. And, giving thanks to him, approach your father, and kiss him.

[[tobit-11-8]]
^8^ And immediately anoint his eyes from this gall of the fish, which you carry with you. For you should know that his eyes will soon be opened, and your father will see the light of heaven, and he will rejoice at the sight of you.”

[[tobit-11-9]]
^9^ Then the dog, which had been with them in the way, ran ahead, and, arriving like a messenger, he showed his joy by fawning and wagging his tail.

[[tobit-11-10]]
^10^ And rising up, his blind father began to run, stumbling with his feet. And giving his hand to a servant, he ran on to meet his son.

[[tobit-11-11]]
^11^ And receiving him, he kissed him, as did his wife, and they both began to weep for joy.

[[tobit-11-12]]
^12^ And when they had adored God and had given thanks, they sat down together.

[[tobit-11-13]]
^13^ Then Tobias, taking from the gall of the fish, anointed his father’s eyes.

[[tobit-11-14]]
^14^ And about half an hour passed, and then a white film began to come out of his eyes, like the membrane of an egg.

[[tobit-11-15]]
^15^ So, taking hold of it, Tobias pulled it away from his eyes, and immediately he received his sight.

[[tobit-11-16]]
^16^ And they glorified God: Tobit especially, and his wife, and all those who knew him.

[[tobit-11-17]]
^17^ And Tobit said, “I bless you, O Lord God of Israel, because you have chastised me, and you have saved me, and behold, I see my son Tobias.”

[[tobit-11-18]]
^18^ And then, after seven days, Sarah, the wife of his son, and all the family arrived safely, along with the sheep, and the camels, and much money from his wife, but also with that money which he had received from Gabael.

[[tobit-11-19]]
^19^ And he explained to his parents all the benefits from God, which he had produced all around him, by means of the man who had led him.

[[tobit-11-20]]
^20^ And then Ahikar and Nadab arrived, the maternal first cousins of Tobias, rejoicing for Tobias, and congratulating with him for all the good things that God had revealed all around him.

[[tobit-11-21]]
^21^ And for seven days they feasted, and all were rejoicing with great joy.


[[tobit-12]]
== Chapter 12

[[tobit-12-1]]
^1^ Then Tobit called his son to him, and he said to him, “What are we able to give to this holy man, who accompanied you?”

[[tobit-12-2]]
^2^ Tobias, answering, said to his father: “Father, what wages shall we give him? And what could be worthy of his benefits?

[[tobit-12-3]]
^3^ He led me and he brought me back safely. He received the money from Gabael. He caused me to have my wife. And he confined the demon away from her. He caused joy to her parents. Myself, he rescued from being devoured by the fish. As for you, he also caused you to see the light of heaven. And so, we have been filled with all good things through him. What could we possibly give to him that would be worthy of these things?

[[tobit-12-4]]
^4^ But I implore you, my father, to ask him if he would perhaps deign to take for himself half of all the things that have been brought.”

[[tobit-12-5]]
^5^ And calling him, the father especially, and the son, they took him aside. And they began to petition him, so that he would deign to accept ownership of one half part of all things that they had brought.

[[tobit-12-6]]
^6^ Then he said to them privately: “Bless the God of heaven, and confess to him in the sight of all who live, for he has acted in his mercy toward you.

[[tobit-12-7]]
^7^ For it is good to conceal the secret of a king, just as it is also honorable to reveal and to confess the works of God.

[[tobit-12-8]]
^8^ Prayer with fasting is good, and almsgiving is better than hiding away gold in storage.

[[tobit-12-9]]
^9^ For almsgiving delivers from death, and the same is what purges sins and makes one able to find mercy and everlasting life.

[[tobit-12-10]]
^10^ But those who commit sin and iniquity are enemies to their own soul.

[[tobit-12-11]]
^11^ Therefore, I reveal the truth to you, and I will not hide the explanation from you.

[[tobit-12-12]]
^12^ When you prayed with tears, and buried the dead, and left behind your dinner, and hid the dead by day in your house, and buried them by night: I offered your prayer to the Lord.

[[tobit-12-13]]
^13^ And because you were acceptable to God, it was necessary for you to be tested by trials.

[[tobit-12-14]]
^14^ And now, the Lord has sent me to cure you, and to free Sarah, your son’s wife, from the demon.

[[tobit-12-15]]
^15^ For I am the Angel Raphael, one of seven, who stand before the Lord.”

[[tobit-12-16]]
^16^ And when they had heard these things, they were troubled, and being seized with fear, they fell upon the ground on their face.

[[tobit-12-17]]
^17^ And the Angel said to them: “Peace be to you. Fear not.

[[tobit-12-18]]
^18^ For when I was with you, I was there by the will of God. Bless him, and sing to him.

[[tobit-12-19]]
^19^ Indeed, I seemed to eat and drink with you, but I make use of an invisible food and drink, which cannot be seen by men.

[[tobit-12-20]]
^20^ Therefore, it is time that I return to him who sent me. But as for you, bless God, and describe all his wonders.”

[[tobit-12-21]]
^21^ And when he had said these things, he was taken from their sight, and they were not able to see him any longer.

[[tobit-12-22]]
^22^ Then, lying prostrate for three hours upon their face, they blessed God. And rising up, they described all his wonders.


[[tobit-13]]
== Chapter 13

[[tobit-13-1]]
^1^ And so, the elder Tobit, opening his mouth, blessed the Lord, and he said: “O Lord, you are great in eternity and your kingdom is with all ages.

[[tobit-13-2]]
^2^ For you scourge, and you save. You lead down to the grave, and you bring up again. And there is no one who can escape from your hand.

[[tobit-13-3]]
^3^ Confess to the Lord, O sons of Israel, and praise him in the sight of the nations.

[[tobit-13-4]]
^4^ For, indeed, he has dispersed you among the Gentiles, who are ignorant of him, that you may proclaim his wonders, and that you may cause them to know that there is no other almighty God, except him.

[[tobit-13-5]]
^5^ He has chastised us because of our iniquities, and he will save us because of his mercy.

[[tobit-13-6]]
^6^ Therefore, look upon what he has done for us, and, with fear and trembling, confess to him. And extol the King of all ages with your works.

[[tobit-13-7]]
^7^ But as for me, I will confess him in the land of my captivity. For he has revealed his majesty within a sinful nation.

[[tobit-13-8]]
^8^ And so, be converted, you sinners, and do justice in the presence of God, believing that he will act in his mercy toward you.

[[tobit-13-9]]
^9^ But I and my soul will rejoice in him.

[[tobit-13-10]]
^10^ Bless the Lord, all you his elect. Keep days of rejoicing, and confess to him.

[[tobit-13-11]]
^11^ O Jerusalem, the city of God, the Lord has chastised you for the works of your hands.

[[tobit-13-12]]
^12^ Confess to the Lord with your good things, and bless the God of all ages, so that he may rebuild his tabernacle in you, and he may recall all the captives to you, and you may be glad in all ages and forever.

[[tobit-13-13]]
^13^ You will shine with a splendid light, and all the ends of the earth will adore by you.

[[tobit-13-14]]
^14^ Nations from far away will come to you, bringing gifts. And in you, they shall adore the Lord, and they will hold your land in sanctification.

[[tobit-13-15]]
^15^ For they will invoke the Great Name in you.

[[tobit-13-16]]
^16^ Those who despise you will be cursed, and all those who blaspheme by you will be condemned, and those who build you up will be blessed.

[[tobit-13-17]]
^17^ But you will rejoice in your sons, because they will all be blessed, and they will be gathered together for the Lord.

[[tobit-13-18]]
^18^ Blessed are all those who love you and who rejoice in your peace.

[[tobit-13-19]]
^19^ Bless the Lord, O my soul, for the Lord our God has freed Jerusalem, his city, from every one of her tribulations.

[[tobit-13-20]]
^20^ Happy will I be, if any of my offspring will be left to see the brightness of Jerusalem.

[[tobit-13-21]]
^21^ The gates of Jerusalem will be built from sapphire and emerald, and all its walls will be surrounded with precious stones.

[[tobit-13-22]]
^22^ All its streets will be paved with stones, white and clean. And ‘Alleluia’ will be sung throughout its neighborhoods.

[[tobit-13-23]]
^23^ Blessed be the Lord, who has exalted it, and may he reign over it, forever and ever. Amen.”


[[tobit-14]]
== Chapter 14

[[tobit-14-1]]
^1^ And the sermon of Tobit was completed. And after Tobit received his sight, he lived forty-two years, and he saw the sons of his grandchildren.

[[tobit-14-2]]
^2^ And so, having completed one hundred and two years, he was buried honorably at Nineveh.

[[tobit-14-3]]
^3^ For he was fifty-six years old, when he lost the light of his eyes, and he was sixty years old, when he truly received it again.

[[tobit-14-4]]
^4^ And, in truth, the remainder of his life was in gladness. And so, with the good accomplishment of the fear of God, he departed in peace.

[[tobit-14-5]]
^5^ But, in the hour of his death, he called to himself his son Tobias, along with his sons, the seven youths who were his grandsons, and he said to them:

[[tobit-14-6]]
^6^ “Nineveh will pass away soon. For the word of the Lord goes forward, and our brothers, who have been dispersed away from the land of Israel, shall return to it.

[[tobit-14-7]]
^7^ Thus its deserted land will be entirely filled again. And the house of God, which was burned like incense within it, will be rebuilt again. And all those who fear God will return there.

[[tobit-14-8]]
^8^ And the Gentiles will relinquish their idols, and they will enter into Jerusalem, and they will dwell in it.

[[tobit-14-9]]
^9^ And all the kings of the earth will rejoice in it, adoring the King of Israel.

[[tobit-14-10]]
^10^ Therefore, my sons, listen to your father. Serve the Lord in truth, and seek to do the things that please him.

[[tobit-14-11]]
^11^ And command your sons, so that they may accomplish justice and almsgiving, and so that they may be mindful of God and may bless him at all times, in truth and with all their strength.

[[tobit-14-12]]
^12^ And now, sons, listen to me, and do not remain here. But, on whatever day you will bury your mother near me in one sepulcher, from that time, direct your steps to leave this place.

[[tobit-14-13]]
^13^ For I see that its iniquity will bring about its end.”

[[tobit-14-14]]
^14^ And it happened that, after the death of his mother, Tobias withdrew from Nineveh, with his wife, and sons, and sons of sons, and he was returned to his father-in-law.

[[tobit-14-15]]
^15^ And he found them unharmed in a good old age. And he took care of them, and he closed their eyes. And all the inheritance of the house of Raguel passed to him. And he saw the sons of his sons to the fifth generation.

[[tobit-14-16]]
^16^ And, having completed ninety-nine years in the fear of the Lord, with joy, they buried him.

[[tobit-14-17]]
^17^ But all his family and all his lineage continued with a good life and in holy conversation, so that they were acceptable both to God and to men, as well as to everyone who dwelt in the land.
