[[first-maccabees]]
= The First Book of Maccabees

[[first-maccabees-1]]
== Chapter 1

[[first-maccabees-1-1]]
^1^ And it happened afterwards that Alexander, the son of Philip the Macedonian, who first reigned in Greece having come from the land of Kittim, struck Darius the king of the Persians and the Medes.

[[first-maccabees-1-2]]
^2^ He appointed many battles, and he took hold of all the fortifications, and he executed the kings of the earth.

[[first-maccabees-1-3]]
^3^ And he passed through even to the ends of the earth. And he received the spoils of many nations. And the earth was silenced in his sight.

[[first-maccabees-1-4]]
^4^ And he gathered together power, and an exceedingly strong army. And he was exalted, and his heart was lifted up.

[[first-maccabees-1-5]]
^5^ And he captured the regions of nations and of sovereign leaders, and they became tributaries to him.

[[first-maccabees-1-6]]
^6^ And after these things, he fell down on his bed, and he knew that he would die.

[[first-maccabees-1-7]]
^7^ And he called his servants, nobles who were raised with him from his youth. And he divided his kingdom to them, while he was still alive.

[[first-maccabees-1-8]]
^8^ And Alexander reigned twelve years, and then he died.

[[first-maccabees-1-9]]
^9^ And his servants obtained his kingdom, each one in his place.

[[first-maccabees-1-10]]
^10^ And they all put diadems on themselves after his death, and their sons after them, for many years; and evils were multiplied on the earth.

[[first-maccabees-1-11]]
^11^ And there went forth from among them a sinful root, Antiochus the illustrious, the son of king Antiochus, who had been a hostage at Rome. And he reigned in the one hundred and thirty-seventh year of the kingdom of the Greeks.

[[first-maccabees-1-12]]
^12^ In those days, there went forth from Israel sons of iniquity, and they persuaded many, saying: “Let us go and negotiate a covenant with the Gentiles that are all around us. For since we have withdrawn from them, many evils have found us.”

[[first-maccabees-1-13]]
^13^ And the word seemed good in their eyes.

[[first-maccabees-1-14]]
^14^ And some of the people determined to do this, and they went to the king. And he gave them the power to act according to the justice of the Gentiles.

[[first-maccabees-1-15]]
^15^ And they built a sports arena in Jerusalem, according to the laws of the Nations.

[[first-maccabees-1-16]]
^16^ And they made themselves uncircumcised, and they withdrew from the holy covenant, and they were joined to the nations, and they were sold into evil-doing.

[[first-maccabees-1-17]]
^17^ And the kingdom was ready in the sight of Antiochus, and he began to reign over the land of Egypt, so that he might reign over two kingdoms.

[[first-maccabees-1-18]]
^18^ And he entered into Egypt with an oppressive multitude, with swift chariots, and elephants, and horsemen, and a great abundance of ships.

[[first-maccabees-1-19]]
^19^ And he appointed a war against Ptolemy, the king of Egypt, and Ptolemy was filled with dread before his face, and he fled, and many fell down wounded.

[[first-maccabees-1-20]]
^20^ And he took hold of the fortified cities in the land of Egypt, and he received the spoils of the land of Egypt.

[[first-maccabees-1-21]]
^21^ And Antiochus turned back, after he struck Egypt, in the one hundred and forty-third year, and he ascended against Israel.

[[first-maccabees-1-22]]
^22^ And he ascended to Jerusalem, with an oppressive multitude.

[[first-maccabees-1-23]]
^23^ And he entered into the sanctuary with arrogance, and he took the golden altar, and the lampstand of light, and all the vessels, and the table for the bread of the Presence, and the vessels of libation, and the vials, and the little mortars of gold, and the veil, and the crowns, and the golden ornament, which was at the face of the temple. And he crushed them all.

[[first-maccabees-1-24]]
^24^ And he took the silver and gold, and the precious vessels, and he took the hidden treasures, which he found. And having taken all these things away, he departed into his own land.

[[first-maccabees-1-25]]
^25^ And he caused a massacre of men, and he was speaking with great arrogance.

[[first-maccabees-1-26]]
^26^ And there was great wailing in Israel and in all of their places.

[[first-maccabees-1-27]]
^27^ And the leaders and elders mourned, and the virgins and young men became weak, and the splendor of the women was changed.

[[first-maccabees-1-28]]
^28^ Every bridegroom took up lamentation, and those who sat in the marriage bed mourned.

[[first-maccabees-1-29]]
^29^ And the land shook on behalf of the inhabitants in it, and the entire house of Jacob was clothed with confusion.

[[first-maccabees-1-30]]
^30^ And after two years of days, the king sent the prince of his tributes to the cities of Judah, and he came to Jerusalem with a great crowd.

[[first-maccabees-1-31]]
^31^ And he spoke peaceful words to them, in deceitfulness; and they believed him.

[[first-maccabees-1-32]]
^32^ And he rushed upon the city suddenly, and he struck it with a great scourging, and he destroyed many of the people of Israel.

[[first-maccabees-1-33]]
^33^ And he took the spoils of the city, and he burned it with fire, and he destroyed its houses and the walls around it.

[[first-maccabees-1-34]]
^34^ And they led away the women as captives, and they possessed the children and the cattle.

[[first-maccabees-1-35]]
^35^ And they built up the city of David with a great and strong wall, and with strong towers, and it became a stronghold for them.

[[first-maccabees-1-36]]
^36^ And they set up in that place a sinful people, wicked men, and together they grew strong in it. And they stored up weapons and provisions. And they gathered together the spoils of Jerusalem,

[[first-maccabees-1-37]]
^37^ and deposited them in that place. And they became a great snare.

[[first-maccabees-1-38]]
^38^ And this became a place of ambush against the sanctuary and a diabolical evil in Israel.

[[first-maccabees-1-39]]
^39^ And they poured out innocent blood around the sanctuary, and they contaminated the sanctuary.

[[first-maccabees-1-40]]
^40^ And the inhabitants of Jerusalem fled because of them, and the city became the dwelling place of outsiders, and she became a stranger to her own offspring, and her own children abandoned her.

[[first-maccabees-1-41]]
^41^ Her sanctuary was desolate, like a place of solitude, her feast days were turned into mourning, her Sabbaths into disgrace, her honors into nothing.

[[first-maccabees-1-42]]
^42^ Her shame was multiplied according to her glory, and her loftiness was turned into lamentation.

[[first-maccabees-1-43]]
^43^ And king Antiochus wrote to all his kingdom, that all the people must be one, and that each one should relinquish his own law.

[[first-maccabees-1-44]]
^44^ And all Gentiles consented, according to the word of king Antiochus.

[[first-maccabees-1-45]]
^45^ And many out of Israel consented to his servitude, and they sacrificed to idols, and they polluted the Sabbath.

[[first-maccabees-1-46]]
^46^ And the king sent letters, by the hand of messengers, to Jerusalem and to all the cities of Judah: that they should follow the law of the Nations of the earth,

[[first-maccabees-1-47]]
^47^ and that they should prohibit holocausts and sacrifices and atonements to be made in the temple of God,

[[first-maccabees-1-48]]
^48^ and that they should prohibit the celebration of the Sabbath and the solemn days.

[[first-maccabees-1-49]]
^49^ And he ordered the holy places to be defiled, along with the holy people of Israel.

[[first-maccabees-1-50]]
^50^ And he ordered altars to be built, and temples, and idols, and he ordered the immolation of the flesh of swine and of unclean cattle,

[[first-maccabees-1-51]]
^51^ and that they should leave their sons uncircumcised, and defile their souls with all that is unclean, and with abominations, so that they would forget the law and would alter all the justifications of God,

[[first-maccabees-1-52]]
^52^ and that whoever would not act according to the word of king Antiochus should be put to death.

[[first-maccabees-1-53]]
^53^ According to all these words, he wrote to all his kingdom. And he appointed leaders over the people, who would compel them to do these things.

[[first-maccabees-1-54]]
^54^ And these ordered the cities of Judah to sacrifice.

[[first-maccabees-1-55]]
^55^ And many from the people, who had abandoned the law of the Lord, were gathered together by them. And they committed evils upon the land.

[[first-maccabees-1-56]]
^56^ And they drove the people of Israel into hiding and into the secret places of fugitives.

[[first-maccabees-1-57]]
^57^ On the fifteenth day of the month of Kislev, in the one hundred and forty-fifth year, king Antiochus set up the abominable idol of desolation on the altar of God, and they built altars throughout all the surrounding cities of Judah.

[[first-maccabees-1-58]]
^58^ And they burned frankincense, and they sacrificed before the doors of houses and in the streets.

[[first-maccabees-1-59]]
^59^ And they cut up the books of the law of God and destroyed them with fire.

[[first-maccabees-1-60]]
^60^ And all those who were found with the books of the testament of the Lord, and whoever observed the law of the Lord, they butchered, according to the edict of the king.

[[first-maccabees-1-61]]
^61^ By their power, they did these things to the people of Israel, as they were discovered in the cities, month after month.

[[first-maccabees-1-62]]
^62^ And on the twenty-fifth day of the month, they sacrificed on that altar which was opposite the high altar.

[[first-maccabees-1-63]]
^63^ And the women who circumcised their sons were butchered, according to the order of king Antiochus.

[[first-maccabees-1-64]]
^64^ And they suspended the children by their necks in all their houses, and those who had circumcised them, they butchered.

[[first-maccabees-1-65]]
^65^ And many of the people of Israel decided within themselves that they would not eat unclean things. And they chose to die, rather than to be defiled with unclean foods.

[[first-maccabees-1-66]]
^66^ And they were not willing to infringe upon the holy law of God, and they were butchered.

[[first-maccabees-1-67]]
^67^ And there was a very great wrath upon the people.


[[first-maccabees-2]]
== Chapter 2

[[first-maccabees-2-1]]
^1^ In those days, there rose up Mattathias, the son of John, the son of Simeon, a priest of the sons of Joarib from Jerusalem, and he settled on the mountain of Modin.

[[first-maccabees-2-2]]
^2^ And he had five sons: John, who was surnamed Gaddi,

[[first-maccabees-2-3]]
^3^ and Simon, who was surnamed Thassi,

[[first-maccabees-2-4]]
^4^ and Judas, who was called Maccabeus,

[[first-maccabees-2-5]]
^5^ and Eleazar, who was surnamed Avaran, and Jonathan, who was surnamed Apphus.

[[first-maccabees-2-6]]
^6^ These saw the evils that were done among the people of Judah and in Jerusalem.

[[first-maccabees-2-7]]
^7^ And Mattathias said: “Woe to me, for why was I born to see the grief of my people and the grief of the holy city, and to sit there, while it is given into the hands of the enemies?

[[first-maccabees-2-8]]
^8^ The holy places have fallen into the hands of outsiders. Her temple is like a man without honor.

[[first-maccabees-2-9]]
^9^ The vessels of her glory have been taken away captive. Her old men have been butchered in the streets, and her young men have fallen by the sword of the enemies.

[[first-maccabees-2-10]]
^10^ What nation has not inherited her kingdom and taken from her spoils?

[[first-maccabees-2-11]]
^11^ All her beauty has been taken away. She who was free, has become a slave.

[[first-maccabees-2-12]]
^12^ And behold, our sanctuary, and our beauty, and our splendor has been desolated, and the Gentiles have defiled them.

[[first-maccabees-2-13]]
^13^ Therefore, what is it to us that we still live?”

[[first-maccabees-2-14]]
^14^ And Mattathias and his sons tore their garments, and they covered themselves with haircloth, and they lamented greatly.

[[first-maccabees-2-15]]
^15^ And those who had been sent from king Antiochus came to that place, to compel those who fled into the city of Modin to immolate, and to burn frankincense, and to depart from the law of God.

[[first-maccabees-2-16]]
^16^ And many of the people of Israel consented and came to them. But Mattathias and his sons stood firm.

[[first-maccabees-2-17]]
^17^ And those who had been sent from Antiochus, responding, said to Mattathias: “You are a ruler, and very splendid and great in this city, and you are adorned with sons and brothers.

[[first-maccabees-2-18]]
^18^ Therefore, approach first, and carryout the order of the king, as all the nations have done, and the men of Judah, and those who remained in Jerusalem. And you and your sons will be among the friends of the king, and enriched with gold and silver and many gifts.”

[[first-maccabees-2-19]]
^19^ And Mattathias responded, and he said with a loud voice: “Even if all nations obey king Antiochus, so that each one departs from the service of the law of his fathers and consents to his commandments,

[[first-maccabees-2-20]]
^20^ I and my sons and my brothers will obey the law of our fathers.

[[first-maccabees-2-21]]
^21^ May God be forgiving to us. It is not useful for us to abandon the law and the justices of God.

[[first-maccabees-2-22]]
^22^ We will not listen to the words of king Antiochus, nor will we sacrifice, transgressing the commandments of our law, so as to set out on another way.”

[[first-maccabees-2-23]]
^23^ And, as he ceased speaking these words, a certain Jew approached in the sight of all to sacrifice to the idols upon the altar in the city of Modin, according to the order of the king.

[[first-maccabees-2-24]]
^24^ And Mattathias saw, and he grieved, and his temperament trembled, and his fury was enkindled according to the judgment of the law, and leaping up, he slaughtered him on the altar.

[[first-maccabees-2-25]]
^25^ Moreover, the man whom king Antiochus had sent, who compelled them to immolate, he killed at the same time, and he destroyed the altar,

[[first-maccabees-2-26]]
^26^ and he was zealous for the law, just as Phinehas did to Zimri, the son of Salomi.

[[first-maccabees-2-27]]
^27^ And Mattathias exclaimed with a loud voice in the city, saying, “All who hold zeal for the law, maintaining the covenant, let them follow me.”

[[first-maccabees-2-28]]
^28^ And he and his sons fled to the mountains, and they left behind whatever they had in the city.

[[first-maccabees-2-29]]
^29^ Then many who sought judgment and justice went down into the desert.

[[first-maccabees-2-30]]
^30^ And they camped there, with their sons, and their wives, and their herds, because evils had overwhelmed them.

[[first-maccabees-2-31]]
^31^ And it was reported to the king’s men, and to the army that was in Jerusalem, in the city of David, that certain men, who had cast aside the commandment of the king, had departed into the hidden places in the desert, and that many had followed after them.

[[first-maccabees-2-32]]
^32^ And immediately, they went out to them, and they arranged a battle against them, on the day of the Sabbath.

[[first-maccabees-2-33]]
^33^ And they said to them: “And now, do you still resist? Go out and act according to the word of king Antiochus, and you will live.”

[[first-maccabees-2-34]]
^34^ And they said, “We will not go out, and we will not do the king’s word, so as to profane the day of the Sabbath.”

[[first-maccabees-2-35]]
^35^ And they rushed against them in battle.

[[first-maccabees-2-36]]
^36^ But they did not respond, nor did they cast a stone at them, nor did they barricade the hidden places,

[[first-maccabees-2-37]]
^37^ for they said, “Let us all die in our simplicity. And heaven and earth will testify for us, that you destroyed us unjustly.”

[[first-maccabees-2-38]]
^38^ So they carried out a battle on the Sabbath. And they were put to death, with their wives, and their sons, and their cattle, even to the number of a thousand souls of men.

[[first-maccabees-2-39]]
^39^ And Mattathias and his friends heard of it, and they held a very great lamentation for them.

[[first-maccabees-2-40]]
^40^ And every man said to his neighbor, “If we all do just as our brothers have done, and if we do not fight against the Gentiles for the sake of our lives and our justifications, then they will quickly eradicate us from the earth.”

[[first-maccabees-2-41]]
^41^ And they decided, on that day, saying: “Every man, who will come against us in warfare on the day of the Sabbath, we will fight against him. And we will not all die, like our brothers who were put to death in the hidden places.”

[[first-maccabees-2-42]]
^42^ Then there was assembled before them the synagogue of the Hasideans, strong men from Israel, each one with a will for the law.

[[first-maccabees-2-43]]
^43^ And all those who fled from the evils added themselves to them, and they became a firmament to them.

[[first-maccabees-2-44]]
^44^ And they gathered together an army, and they struck down the sinners in their wrath and the wicked men in their indignation. And the others fled to the nations, so as to escape.

[[first-maccabees-2-45]]
^45^ And Mattathias and his friends traveled around, and they destroyed the altars.

[[first-maccabees-2-46]]
^46^ And they circumcised all the uncircumcised boys, whom they found within the limits of Israel, and they acted with fortitude.

[[first-maccabees-2-47]]
^47^ And they pursued the sons of arrogance, and the work was prosperous in their hands.

[[first-maccabees-2-48]]
^48^ And they obtained the law from the hands of the Gentiles, and from the hands of the kings. And they did not surrender the horn to the sinner.

[[first-maccabees-2-49]]
^49^ Then the days drew near when Mattathias would die, and he said to his sons: “Now arrogance and chastisement have been strengthened, and it is a time of overturning and of the wrath of indignation.

[[first-maccabees-2-50]]
^50^ Now therefore, O sons, be imitators of the law, and give your lives for the sake of the covenant of your fathers.

[[first-maccabees-2-51]]
^51^ And call to mind the works of the fathers, which they have done in their generations. And you will receive great glory and an eternal name.

[[first-maccabees-2-52]]
^52^ Was not Abraham found to be faithful in temptation, and so it was accounted to him as justice?

[[first-maccabees-2-53]]
^53^ Joseph, in the time of his anguish, kept the commandment, and he was made ruler of Egypt.

[[first-maccabees-2-54]]
^54^ Phinehas our father, being zealous in the zeal of God, received the covenant of an eternal priesthood.

[[first-maccabees-2-55]]
^55^ Jesus, since he fulfilled the word, was made a commander in Israel.

[[first-maccabees-2-56]]
^56^ Caleb, since he testified in the assembly, received an inheritance.

[[first-maccabees-2-57]]
^57^ David, in his mercy, obtained the throne of a kingdom for all generations.

[[first-maccabees-2-58]]
^58^ Elijah, since he was zealous with a zeal for the law, was received into heaven.

[[first-maccabees-2-59]]
^59^ Hananiah and Azariah and Mishael, by believing, were delivered from the flame.

[[first-maccabees-2-60]]
^60^ Daniel, in his simplicity, was delivered from the mouth of the lions.

[[first-maccabees-2-61]]
^61^ And so, consider that, through generation after generation of all those who trusted in him, none have failed in strength.

[[first-maccabees-2-62]]
^62^ And fear not the words of a sinful man, for his glory is dung and worms.

[[first-maccabees-2-63]]
^63^ Today he is extolled, and tomorrow he will not be found, because he has returned into his earth and his thinking has perished.

[[first-maccabees-2-64]]
^64^ Therefore, you sons, be strengthened and act manfully in the law. For by it, you shall become glorious.

[[first-maccabees-2-65]]
^65^ And behold, I know that your brother Simon is a man of counsel. Heed him always, and he will be a father to you.

[[first-maccabees-2-66]]
^66^ And Judas Maccabeus, who has been strong and resourceful from his youth, let him be the leader of your militia, and he will manage the war of the people.

[[first-maccabees-2-67]]
^67^ And you shall add to yourselves all who observe the law, and you shall claim the vindication of your people.

[[first-maccabees-2-68]]
^68^ Render to the Gentiles their retribution, and pay attention to the precepts of the law.”

[[first-maccabees-2-69]]
^69^ And he blessed them, and he was added to his fathers.

[[first-maccabees-2-70]]
^70^ And he passed away in the one hundred and forty-sixth year, and he was buried by his sons in the sepulchers of his fathers, in Modin, and all Israel mourned for him with a great mourning.


[[first-maccabees-3]]
== Chapter 3

[[first-maccabees-3-1]]
^1^ And his son Judas, who was called Maccabeus, rose up in his place.

[[first-maccabees-3-2]]
^2^ And all his brothers assisted him, along with all those who had joined themselves to his father. And they fought the battle of Israel with rejoicing.

[[first-maccabees-3-3]]
^3^ And he expanded the glory of his people, and he clothed himself with a breastplate like a giant, and he surrounded himself his weapons of war in battles, and he protected the camp with his sword.

[[first-maccabees-3-4]]
^4^ In his actions, he became like a lion, and like a young lion roaring in the hunt.

[[first-maccabees-3-5]]
^5^ And he pursued the wicked and tracked them down. And those who disturbed his people, he burned with fire.

[[first-maccabees-3-6]]
^6^ And his enemies were repelled by the fear of him, and all the workers of iniquity were troubled. And salvation was well-directed in his hand.

[[first-maccabees-3-7]]
^7^ And he provoked many kings, and he gave joy to Jacob by his works, and his memory will be a blessing for all generations.

[[first-maccabees-3-8]]
^8^ And he traveled through the cities of Judah, and he destroyed the impious out of them, and he turned wrath away from Israel.

[[first-maccabees-3-9]]
^9^ And he was renowned, even to the utmost part of the earth, and he gathered together those who were perishing.

[[first-maccabees-3-10]]
^10^ And so Apollonius gathered together the Gentiles, with a numerous and great army from Samaria, to make war against Israel.

[[first-maccabees-3-11]]
^11^ And Judas knew about it, and he went forth to meet him. And he struck him and killed him. And many fell down wounded, and the rest fled away.

[[first-maccabees-3-12]]
^12^ And he took away their spoils. And Judas took possession of the sword of Apollonius, and he fought with it during all his days.

[[first-maccabees-3-13]]
^13^ And Seron, the leader of the army of Syria, heard that Judas had gathered together a company of the faithful and an assembly with him.

[[first-maccabees-3-14]]
^14^ And he said, “I will make a name for myself, and I will be glorified in the kingdom, and I will defeat Judas in warfare, and those who are with him, who have spurned the word of the king.”

[[first-maccabees-3-15]]
^15^ And he prepared himself. And the camp of the impious went up with him, with strong auxiliaries, so as to act with vengeance upon the sons of Israel.

[[first-maccabees-3-16]]
^16^ And they approached even as far as Bethhoron. And Judas went forth to meet him, with a few men.

[[first-maccabees-3-17]]
^17^ But when they saw the army coming to meet them, they said to Judas, “How will we few be able to fight against so great and so strong a multitude, even though we are weakened by fasting today?”

[[first-maccabees-3-18]]
^18^ And Judas said: “It is easy for many to be enclosed in the hands of a few, for there is no difference in the sight of the God of heaven to liberate by means of many, or by means of few.

[[first-maccabees-3-19]]
^19^ For victory in warfare is not in the multitude of the army, but in the strength from heaven.

[[first-maccabees-3-20]]
^20^ They come to us with a contemptuous multitude and with arrogance, in order to destroy us, with our wives and our sons, and to despoil us.

[[first-maccabees-3-21]]
^21^ In truth, we will fight on behalf of our souls and our laws.

[[first-maccabees-3-22]]
^22^ And the Lord himself will crush them before our face. But as for you, do not fear them.”

[[first-maccabees-3-23]]
^23^ And as soon as he had ceased speaking, he attacked them suddenly. And Seron and his army were crushed in his sight.

[[first-maccabees-3-24]]
^24^ And he pursued him from the descent of Bethhoron, even to the plains. And eight hundred of their men were cut down, but the rest fled into the land of the Philistines.

[[first-maccabees-3-25]]
^25^ And the fear and dread of Judas, as well as his brothers, fell upon all the nations around them.

[[first-maccabees-3-26]]
^26^ And his name reached even to the king, and all the nations told stories of the battles of Judas.

[[first-maccabees-3-27]]
^27^ But when king Antiochus heard these accounts, he was angry to his very soul. And he sent and gathered together forces from his entire kingdom, a very strong army.

[[first-maccabees-3-28]]
^28^ And he opened his treasury, and he gave out stipends to the army for a year. And he commanded them to make ready for all things.

[[first-maccabees-3-29]]
^29^ And he saw that the money from his treasures had failed, and that the tributes of the country were small, because of the dissension and the scourging that he had caused on earth in order to take away the legitimate laws, which had been since the first days.

[[first-maccabees-3-30]]
^30^ And he feared, lest he not have enough the second time as the first, for expenses and gifts, which he had given before with a liberal hand. For his excesses were more than the kings who had been before him.

[[first-maccabees-3-31]]
^31^ And he was alarmed to his very soul, and he intended to go into Persia, and to take tributes from the regions, and to gather together much money.

[[first-maccabees-3-32]]
^32^ And he left behind Lysias, a nobleman of royal family, to preside over the kingdom from the river Euphrates, even to the river of Egypt,

[[first-maccabees-3-33]]
^33^ and to raise his son, Antiochus, until he would return.

[[first-maccabees-3-34]]
^34^ And he handed over to him half of the army, and the elephants. And he commanded him concerning all that he wanted, and concerning the inhabitants of Judea and Jerusalem:

[[first-maccabees-3-35]]
^35^ so that he would send an army against them to crush and to root out the virtue of Israel and the remnant of Jerusalem, and to take away the memory of them from that place,

[[first-maccabees-3-36]]
^36^ and so that he would establish dwelling places for the sons of foreigners in all their parts, and would distribute their land by lot.

[[first-maccabees-3-37]]
^37^ And so, the king took the remaining part of the army, and he went forth from Antioch, the city of his kingdom, in the one hundred and forty-seventh year. And he crossed over the river Euphrates, and he traveled through the upper regions.

[[first-maccabees-3-38]]
^38^ Then Lysias chose Ptolemy, the son of Dorymenes, and Nicanor and Gorgias, powerful men from among the king’s friends.

[[first-maccabees-3-39]]
^39^ And he sent them with forty thousand men, and seven thousand horsemen, to enter into the land of Judah, and to destroy it, according to the word of the king.

[[first-maccabees-3-40]]
^40^ And so, they proceeded with all their power, and they arrived and took a position near Emmaus, in the land of the plains.

[[first-maccabees-3-41]]
^41^ And the merchants of the regions heard of their name. And they took very much silver, and gold, and servants, and they came into the camp to take the sons of Israel into servitude. And armies from Syria and from the lands of foreigners were added to them.

[[first-maccabees-3-42]]
^42^ And Judas and his brothers saw that evils were being multiplied, and that armies had been positioned near their borders. And they knew the words of the king, which ordered the people to be put to death and to be utterly consumed.

[[first-maccabees-3-43]]
^43^ And they said, each one to his neighbor, “Let us relieve the dejection of our people, and let us fight on behalf of our people and our sacred places.”

[[first-maccabees-3-44]]
^44^ And an assembly was gathered together, so that they would be prepared for battle, and so that they could pray and ask for mercy and compassion.

[[first-maccabees-3-45]]
^45^ Now Jerusalem was not inhabited, but was like a desert. There was no one who entered or exited from among her children. And the sanctuary was trampled upon, and the sons of foreigners were in the stronghold. This place was the habitation of the Gentiles. And delight was taken away from Jacob, and the music of flute and harp ceased in that place.

[[first-maccabees-3-46]]
^46^ And they gathered together and came to Mizpah, opposite Jerusalem. For a place of prayer was in Mizpah, in the former Israel.

[[first-maccabees-3-47]]
^47^ And they fasted on that day, and they clothed themselves with haircloth, and they placed ashes on their heads, and they tore their garments.

[[first-maccabees-3-48]]
^48^ And they laid open the books of the law, in which the Gentiles searched for the likeness of their idols.

[[first-maccabees-3-49]]
^49^ And they brought the priestly ornaments, and the first fruits and tithes, and they roused the Nazirites, who had fulfilled their days.

[[first-maccabees-3-50]]
^50^ And they cried out with a loud voice toward heaven, saying: “What shall we do with these, and where shall we take them?

[[first-maccabees-3-51]]
^51^ For your holy things have been trampled and defiled, and your priests have been in mourning and in humiliation.

[[first-maccabees-3-52]]
^52^ And behold, the Nations gather together against us, to destroy us. You know what they intend against us.

[[first-maccabees-3-53]]
^53^ How shall we be able to stand before their face, unless you, O God, assist us?”

[[first-maccabees-3-54]]
^54^ Then they sounded the trumpets with a loud call.

[[first-maccabees-3-55]]
^55^ And after this, Judas appointed commanders over the people: over thousands, and over hundreds, and over fifties, and over tens.

[[first-maccabees-3-56]]
^56^ And he said to those who were building houses, or who had betrothed wives, who were planting vineyards, or who were terribly afraid, that they should return, each one to his own house, according to the law.

[[first-maccabees-3-57]]
^57^ So they moved the camp, and relocated to the south of Emmaus.

[[first-maccabees-3-58]]
^58^ And Judas said: “Gird yourselves, and be sons of power, and be ready in the morning, so that you may fight against these nations that have assembled against us, so as to destroy us and our sacred things.

[[first-maccabees-3-59]]
^59^ For it is better for us to die in battle, than to see evils come to our nation and to the sacred places.

[[first-maccabees-3-60]]
^60^ Nevertheless, as it shall be willed in heaven, so let it be.”


[[first-maccabees-4]]
== Chapter 4

[[first-maccabees-4-1]]
^1^ Then Gorgias took five thousand men and a thousand chosen horsemen, and they moved out of the camp by night,

[[first-maccabees-4-2]]
^2^ so that they might set upon the camp of the Jews and strike them suddenly. And the sons who were from the stronghold were their guides.

[[first-maccabees-4-3]]
^3^ And Judas heard of it, and he rose up, with his powerful men, to strike the force from the king’s army that was in Emmaus.

[[first-maccabees-4-4]]
^4^ For the army was still dispersed from the camp.

[[first-maccabees-4-5]]
^5^ And Gorgias came by night, into the camp of Judas, and found no one, and he sought them in the mountains. For he said, “These men flee from us.”

[[first-maccabees-4-6]]
^6^ And when it had become day, Judas appeared in the plain with only three thousand men, who had neither armor nor swords.

[[first-maccabees-4-7]]
^7^ And they saw the strength of the camp of the Gentiles, and the men in armor, and the horsemen surrounding them, and that these were trained to fight.

[[first-maccabees-4-8]]
^8^ And Judas said to the men who were with him: “Do not be afraid of their multitude, and do not dread their attack.

[[first-maccabees-4-9]]
^9^ Remember in what way salvation came to our fathers in the Red Sea, when Pharaoh pursued them with a great army.

[[first-maccabees-4-10]]
^10^ And now, let us cry out to heaven, and the Lord will have mercy on us, and he will remember the covenant of our fathers, and he will crush this army before our face this day.

[[first-maccabees-4-11]]
^11^ And all nations shall know that there is One who redeems and frees Israel.”

[[first-maccabees-4-12]]
^12^ And the foreigners lifted up their eyes, and they saw them coming against them.

[[first-maccabees-4-13]]
^13^ And they went out of the camp into battle, and those who were with Judas sounded the trumpet.

[[first-maccabees-4-14]]
^14^ And they came together. And the Gentiles were crushed, and they fled into the plains.

[[first-maccabees-4-15]]
^15^ But the last of them all fell by the sword, and they pursued them even to Gazara, and even to the plains of Idumea, and Azotus, and Jamnia. And there fell from them as many as three thousand men.

[[first-maccabees-4-16]]
^16^ And Judas returned, with his army following him.

[[first-maccabees-4-17]]
^17^ And he said to the people: “Do not desire the spoils; for there is war before us.

[[first-maccabees-4-18]]
^18^ And Gorgias and his army are near us on the mountain. But stand firm now against our enemies, and fight against them, and you shall take the spoils afterwards, securely.”

[[first-maccabees-4-19]]
^19^ And while Judas was speaking these words, behold, a certain part of them appeared, looking out from the mountain.

[[first-maccabees-4-20]]
^20^ And Gorgias saw that his men were put to flight, and that they had set fire to the camp. For the smoke that he saw declared what had happened.

[[first-maccabees-4-21]]
^21^ When they had seen this, they became very afraid, seeing at the same time both Judas and his army in the plains prepared to do battle.

[[first-maccabees-4-22]]
^22^ So they all fled away into the encampment of the foreigners.

[[first-maccabees-4-23]]
^23^ And Judas returned to take the spoils of the camp, and they obtained much gold and silver, and hyacinth, and purple of the sea, and great riches.

[[first-maccabees-4-24]]
^24^ And returning, they sang a canticle, and they blessed God in heaven, because he is good, because his mercy is with every generation.

[[first-maccabees-4-25]]
^25^ And so, a great salvation occurred in Israel in that day.

[[first-maccabees-4-26]]
^26^ But those among the foreigners who escaped went and reported to Lysias all that had happened.

[[first-maccabees-4-27]]
^27^ And when he heard these things, he was discouraged, being alarmed to his very soul. For things had not occurred in Israel according to his wishes, nor as the king had commanded.

[[first-maccabees-4-28]]
^28^ And, in the following year, Lysias gathered together sixty thousand chosen men and five thousand horsemen, so that he might defeat them in warfare.

[[first-maccabees-4-29]]
^29^ And they came into Judea, and they positioned their camp in Bethzur, and Judas met them with ten thousand men.

[[first-maccabees-4-30]]
^30^ And they saw the strength of the army, and so he prayed, and he said: “Blessed are you, Savior of Israel, who crushed the assault of the powerful by the hand of your servant David, and who delivered up the camp of the foreigners into the hand of Jonathan, the son of Saul, and his armor bearer.

[[first-maccabees-4-31]]
^31^ Enclose this army in the hand of your people Israel, and let them be confounded in their soldiers and their horsemen.

[[first-maccabees-4-32]]
^32^ Strike them with dread, and melt away the boldness of their strength, and let them shudder in their grief.

[[first-maccabees-4-33]]
^33^ Cast them down with the sword of those who love you, and let all who know your name praise you with hymns.”

[[first-maccabees-4-34]]
^34^ And they went forth to battle, and there fell from the army of Lysias five thousand men.

[[first-maccabees-4-35]]
^35^ But Lysias, seeing their flight and the boldness of the Jews, and that they were prepared either to live or to die with fortitude, went to Antioch and chose soldiers, so that they might come back to Judea with greater numbers.

[[first-maccabees-4-36]]
^36^ Then Judas and his brothers said: “Behold, our enemies have been crushed. Let us go up now to cleanse and renew the holy places.”

[[first-maccabees-4-37]]
^37^ And all the army gathered together, and they ascended to Mount Zion.

[[first-maccabees-4-38]]
^38^ And they saw the sanctuary deserted, and the altar profaned, and the gates burned, and weeds growing up in the courts, as in a forest or as on the mountains, and the adjoining chambers demolished.

[[first-maccabees-4-39]]
^39^ And they rent their garments, and they made a great wailing, and they placed ashes on their heads.

[[first-maccabees-4-40]]
^40^ And they fell to the ground on their faces, and they sounded the trumpets of alarm, and they cried out toward heaven.

[[first-maccabees-4-41]]
^41^ Then Judas numbered men to fight against those who were in the stronghold, until they had cleansed the holy places.

[[first-maccabees-4-42]]
^42^ And he chose priests without blemish, whose will held to the law of God.

[[first-maccabees-4-43]]
^43^ And they cleansed the holy places, and they took away the stones of defilement to an unclean place.

[[first-maccabees-4-44]]
^44^ And he considered the altar of holocausts, which had been profaned, as to what he should do with it.

[[first-maccabees-4-45]]
^45^ And a good counsel fell upon them, to destroy it, lest it might become a reproach to them, because the Gentiles had defiled it; so they demolished it.

[[first-maccabees-4-46]]
^46^ And they stored the stones in the mountain house, in a fitting place, until there should come a prophet, who would provide an answer about these.

[[first-maccabees-4-47]]
^47^ Then they took whole stones, according to the law, and they built a new altar, according to that which was before.

[[first-maccabees-4-48]]
^48^ And they rebuilt the holy places and the things that were in the inner parts of the temple, and they sanctified the temple and the courts.

[[first-maccabees-4-49]]
^49^ And they made new holy vessels, and they brought the lampstand, and the altar of incense, and the table into the temple.

[[first-maccabees-4-50]]
^50^ And they placed incense on the altar, and they lit the lamps, which were on the lampstand, and they gave light in the temple.

[[first-maccabees-4-51]]
^51^ And they placed the bread on the table, and they hung up the veils, and they completed all the works which they had begun.

[[first-maccabees-4-52]]
^52^ And they arose before the morning, on the twenty-fifth day of the ninth month, (which is the month of Kislev) in the one hundred and forty-eighth year.

[[first-maccabees-4-53]]
^53^ And they offered sacrifice, according to the law, on the new altar of holocausts that they made.

[[first-maccabees-4-54]]
^54^ According to the time and according to the day, on which the Gentiles had contaminated it, on the same day, it was renewed with canticles, and lutes, and lyres, and cymbals.

[[first-maccabees-4-55]]
^55^ And all the people fell upon their faces, and they adored, and they blessed, toward heaven, him that had prospered them.

[[first-maccabees-4-56]]
^56^ And they kept the dedication of the altar for eight days, and they offered holocausts with joy, and sacrifices of salvation and praise.

[[first-maccabees-4-57]]
^57^ And they adorned the face of the temple with crowns of gold and small shields. And they dedicated the gates and the adjoining chambers, and they set up doors on them.

[[first-maccabees-4-58]]
^58^ And there was very great rejoicing among the people, and the disgrace of the Gentiles was averted.

[[first-maccabees-4-59]]
^59^ And Judas, and his brothers, and all the assembly of Israel decreed that the day of the dedication of the altar must be kept in its time, from year to year, for eight days, from the twenty-fifth day of the month of Kislev, with joy and gladness.

[[first-maccabees-4-60]]
^60^ And they built up, at that time, Mount Zion, with high walls and strong towers all around, lest the Gentiles should at any time come and trample upon it, as they did before.

[[first-maccabees-4-61]]
^61^ And he stationed a garrison there, to keep it, and he fortified it, in order to guard Bethzur, so that the people might have a fortification opposite the face of Idumea.


[[first-maccabees-5]]
== Chapter 5

[[first-maccabees-5-1]]
^1^ And it happened that, when the surrounding nations heard that the altar and the sanctuary had been rebuilt as before, they were very angry.

[[first-maccabees-5-2]]
^2^ And they intended to destroy the people of Jacob that were among them, and they began to kill some of the people, and to persecute them.

[[first-maccabees-5-3]]
^3^ Then Judas defeated in warfare the sons of Esau in Idumea, and those who were in Akrabattene, because they besieged the Israelites, and he struck them with a great scourging.

[[first-maccabees-5-4]]
^4^ And he remembered the malice of the sons of Baean, who were a snare and a scandal to the people, lying in ambush for them in the way.

[[first-maccabees-5-5]]
^5^ And they were trapped by him in the towers, and he took up a position near them, and he anathematized them, and he burned their towers with fire, along with all who were in them.

[[first-maccabees-5-6]]
^6^ Then he crossed over to the sons of Ammon, and he found a strong hand, and an abundant people, and Timothy was their commander.

[[first-maccabees-5-7]]
^7^ And he engaged in many battles with them, and they were crushed in their sight, and he struck them down.

[[first-maccabees-5-8]]
^8^ And he seized the city of Jazer, and her sister cities, and he returned to Judea.

[[first-maccabees-5-9]]
^9^ And the Gentiles, who were in Gilead, gathered together against the Israelites, who were within their borders, to take them away, and so they fled into the fortress of Dathema.

[[first-maccabees-5-10]]
^10^ And they sent letters to Judas and his brothers, saying: “The Gentiles all around have been gathering together against us to carry us away.

[[first-maccabees-5-11]]
^11^ And they are preparing to come and occupy the fortress into which we have fled. And Timothy is the commander of their army.

[[first-maccabees-5-12]]
^12^ Now, therefore, come and rescue us from their hands, for many of us have fallen.

[[first-maccabees-5-13]]
^13^ And all our brothers, who were in the places of Tob, have been put to death. And they have led away as captives their wives, and their children, and their spoils. And they have slain nearly a thousand men in that place.”

[[first-maccabees-5-14]]
^14^ And while they were still reading these letters, behold, there arrived from Galilee other messengers, with torn garments, who announced according to these words:

[[first-maccabees-5-15]]
^15^ saying that those of Ptolemais and Tyre and Sidon have assembled against them, “and all of Galilee has been filled with foreigners, in order to consume us.”

[[first-maccabees-5-16]]
^16^ So then, when Judas and the people heard these words, a great assembly came together, to consider what they should do for their brothers who were in trouble and were being assailed by them.

[[first-maccabees-5-17]]
^17^ And Judas said to Simon his brother: “Choose men for yourself, and go, and free your brothers in Galilee. But I and my brother Jonathan, will go into the country of Gilead.”

[[first-maccabees-5-18]]
^18^ And he left behind Joseph, son of Zachariah, and Azariah, as commanders of the people, with the remainder of the army, in Judea, to guard it.

[[first-maccabees-5-19]]
^19^ And he instructed them, saying, “Take charge of this people, but do not go to war against the Gentiles, until we return.”

[[first-maccabees-5-20]]
^20^ Now three thousand men were divided to Simon, to go into Galilee, but eight thousand were divided to Judas, to go into the land of Gilead.

[[first-maccabees-5-21]]
^21^ And Simon went into Galilee, and he engaged in many battles with the Gentiles, and the Gentiles were crushed before his face, and he pursued them even to the gates of Ptolemais.

[[first-maccabees-5-22]]
^22^ And there fell of the Gentiles nearly three thousand men, and he took their spoils.

[[first-maccabees-5-23]]
^23^ And he took with him those who were in Galilee and in Arbatta, with their wives and children, and all that was theirs, and he led them into Judea with great rejoicing.

[[first-maccabees-5-24]]
^24^ And Judas Maccabeus, and Jonathan his brother, crossed over the Jordan, and they traveled three days’ journey through the desert.

[[first-maccabees-5-25]]
^25^ And the Nabateans met them, and they accepted them peacefully, and they described to them all that had happened to their brothers in the land of Gilead,

[[first-maccabees-5-26]]
^26^ and that many of them were trapped in Bozrah, and Bosor, and Alema, and in Chaspho, and Maked, and Carnaim. All these are large and fortified cities.

[[first-maccabees-5-27]]
^27^ Moreover, they were held in their grasp in the other cities of Gilead, and they had arranged to move their army, on the next day, to these cities, and to seize them, and to destroy them all in one day.

[[first-maccabees-5-28]]
^28^ Then Judas and his army unexpectedly turned their path into the desert, to Bosor, and they occupied the city. And he killed every male by the edge of the sword, and took all their spoils, and burned it with fire.

[[first-maccabees-5-29]]
^29^ And they arose from there by night, and they went forth all the way to the fortress.

[[first-maccabees-5-30]]
^30^ And it happened that, at first light, when they lifted up their eyes, behold, there was a multitude of people, which could not be numbered, bringing ladders and machines, in order to seize the fortress, and to assault them.

[[first-maccabees-5-31]]
^31^ And Judas saw that the fight had begun, and the cry of the battle went up to heaven like a trumpet, and a great cry went out of the city.

[[first-maccabees-5-32]]
^32^ And he said to his army, “Fight today on behalf of your brothers.”

[[first-maccabees-5-33]]
^33^ And he came, with three companies behind them, and they sounded the trumpets, and they cried out in prayer.

[[first-maccabees-5-34]]
^34^ And the camp of Timothy knew that it was Maccabeus, and they took flight before his face. And they struck them with a great scourging. And there fell from them in that day nearly eight thousand men.

[[first-maccabees-5-35]]
^35^ And Judas diverted to Mizpah, and he fought and seized it. And he killed all of its males, and he took its spoils, and he burned it with fire.

[[first-maccabees-5-36]]
^36^ From there, he continued on, and he seized Chaspho, and Maked, and Bosor, and the rest of the cities of Gilead.

[[first-maccabees-5-37]]
^37^ But after these events, Timothy gathered together another army, and he positioned his camp opposite Raphon, across the torrent.

[[first-maccabees-5-38]]
^38^ And Judas sent men to catch sight of the army. And they reported back to him, saying: “All the nations that surround us have assembled before him, with an exceedingly great army.

[[first-maccabees-5-39]]
^39^ And they have brought the Arabians as auxiliaries to them, and they have set up camp across the torrent, in preparation to come against you in battle.” And Judas went to meet them.

[[first-maccabees-5-40]]
^40^ And Timothy said to the leaders of his army: “When Judas and his army approach, close to the torrent of water, if he crosses over to us first, we will not be able to withstand him. For he will be able to prevail against us.

[[first-maccabees-5-41]]
^41^ If, truly, he is afraid to cross over, and so he sets up camp across the river, we will cross over to them, and we will prevail against him.”

[[first-maccabees-5-42]]
^42^ But when Judas approached, close to the torrent of water, he stationed the scribes of the people near the torrent, and he commanded them, saying, “Permit no man to stay behind, but let all come into the battle.”

[[first-maccabees-5-43]]
^43^ And he crossed over to them first, and all the people after him. And all the Gentiles were crushed before their face, and they threw away their weapons, and they fled to the temple that was in Carnaim.

[[first-maccabees-5-44]]
^44^ And he occupied that city, and he burned the temple with fire, along with all the things that were in it. And Carnaim was subdued, and it could not stand against the face of Judas.

[[first-maccabees-5-45]]
^45^ And Judas gathered together all the Israelites who were in the land of Gilead, from the least even to the greatest, with their wives and children, and a very great army, to come into the land of Judah.

[[first-maccabees-5-46]]
^46^ And they came as far as Ephron. And this was a great city, positioned at the entrance, strongly fortified, and there was no way to go around it on the right or on the left, but the path was through the midst of it.

[[first-maccabees-5-47]]
^47^ And those who were in the city shut themselves in and barricaded the gates with stones. And so Judas sent to them with words of peace,

[[first-maccabees-5-48]]
^48^ saying, “Let us cross through your land, to go into our own land, and no one will harm you; we will only cross through on foot.” But they were not willing to open to them.

[[first-maccabees-5-49]]
^49^ Then Judas instructed a proclamation to be made in the camp, that they would engage them, each one from the place where he was.

[[first-maccabees-5-50]]
^50^ And the men of the army drew close. And he assaulted that city all day and all night. And the city was delivered into his hand.

[[first-maccabees-5-51]]
^51^ And they destroyed every male with the edge of the sword, and he eradicated the city, and he took its spoils, and he crossed through the entire city, over those who had been slain.

[[first-maccabees-5-52]]
^52^ Then they crossed over the Jordan to the great plain that is opposite the face of Bethshan.

[[first-maccabees-5-53]]
^53^ And Judas was gathering the stragglers and exhorting the people, throughout the entire way, until they came into the land of Judah.

[[first-maccabees-5-54]]
^54^ And they ascended to mount Zion with joy and gladness, and they offered holocausts, because not one of them had fallen, until they had returned in peace.

[[first-maccabees-5-55]]
^55^ Now in the days that Judas and Jonathan were in the land of Gilead, and Simon his brother was in Galilee against the face of Ptolemais:

[[first-maccabees-5-56]]
^56^ Joseph, the son of Zachariah, and Azariah, the leader of the army, heard good things about the battles that were fought.

[[first-maccabees-5-57]]
^57^ And he said, “Let us also make a name for ourselves, and let us go to fight against the Gentiles that are all around us.”

[[first-maccabees-5-58]]
^58^ And he gave orders to those who were in his army, and they went out towards Jamnia.

[[first-maccabees-5-59]]
^59^ And Gorgias and his men exited the city, to meet them in the fight.

[[first-maccabees-5-60]]
^60^ And Joseph and Azariah were forced to flee, even to the borders of Judea. And there fell on that day, from the people of Israel, up to two thousand men, and it was a great defeat for the people.

[[first-maccabees-5-61]]
^61^ For they did not listen to Judas and his brothers, supposing that they should act boldly.

[[first-maccabees-5-62]]
^62^ But these were not of the offspring of those men by whom salvation was brought to Israel.

[[first-maccabees-5-63]]
^63^ And the men of Judah were magnified greatly in the sight of all Israel and of all the nations where their name was heard.

[[first-maccabees-5-64]]
^64^ And the people gathered to them with favorable acclamations.

[[first-maccabees-5-65]]
^65^ And so Judas and his brothers went out and assailed the sons of Esau, in the land that is toward the south, and he struck Hebron and her sister cities, and he burned its walls and the towers all around it with fire.

[[first-maccabees-5-66]]
^66^ And he moved his camp to go into the land of the foreigners, and he traveled through Samaria.

[[first-maccabees-5-67]]
^67^ In that day, some priests fell in battle. Since they desired to act boldly, they went out, without counsel, into the battle.

[[first-maccabees-5-68]]
^68^ And Judas turned aside to Azotus, into the land of the foreigners, and he destroyed their altars, and he burned the statues of their gods with fire. And he seized the spoils of the cities, and he returned to the land of Judah.


[[first-maccabees-6]]
== Chapter 6

[[first-maccabees-6-1]]
^1^ And king Antiochus was traveling through the upper regions, and he heard that the city of Elymais in Persia was very noble and abundant in silver and gold,

[[first-maccabees-6-2]]
^2^ and that the temple in it was very opulent, and that there were, in that place, coverings of gold, and breastplates and shields, which Alexander, the son of Philip, king of Macedonia, who reigned first in Greece, had left behind.

[[first-maccabees-6-3]]
^3^ So he came and sought to seize the city and to pillage it. And he was not able, because this plan became known to those who were in the city.

[[first-maccabees-6-4]]
^4^ And they rose up in battle, and he fled away from there, and he departed with great sadness, and he returned into Babylon.

[[first-maccabees-6-5]]
^5^ And someone arrived to report to him in Persia, that those who were in the land of Judah were forced to flee the camp,

[[first-maccabees-6-6]]
^6^ and that Lysias went forth with a particularly strong army, and he was forced to flee before the face of the Jews, and that they were strengthened by the weapons, and resources, and many spoils which they seized from the camps they demolished,

[[first-maccabees-6-7]]
^7^ and that they had destroyed the abomination, which he had established on the altar that was in Jerusalem, and that the sanctuary, just as before, had been encircled with high walls, along with Bethzur, his city.

[[first-maccabees-6-8]]
^8^ And it happened that, when the king heard these words, he was terrified and very moved. And he fell down on his bed, and he fell into feebleness out of grief. For it had not happened to him as he had intended.

[[first-maccabees-6-9]]
^9^ And he was in that place through many days. For a great grief was renewed in him, and he concluded that he would die.

[[first-maccabees-6-10]]
^10^ And he called all his friends, and he said to them: “Sleep has withdrawn from my eyes, and I am declining, and my heart has collapsed out of anxiety.

[[first-maccabees-6-11]]
^11^ And I said in my heart: How much trouble has come to me, and what floods of sorrow there are, where I am now! I used to be cheerful and beloved in my power!

[[first-maccabees-6-12]]
^12^ Truly, now, I remember the evils that I did in Jerusalem, from which place I also took away all the spoils of gold and silver that were in it, and I sent to carry away the inhabitants of Judah without cause.

[[first-maccabees-6-13]]
^13^ Therefore, I know that it is because of this that these evils have found me. And behold, I perish with great sorrow in a foreign land.”

[[first-maccabees-6-14]]
^14^ Then he called Philip, one of his friends, and he placed him first over all his kingdom.

[[first-maccabees-6-15]]
^15^ And he gave him the diadem, and his robe, and his ring, so that he would guide Antiochus, his son, and raise him, and so that he would reign.

[[first-maccabees-6-16]]
^16^ And king Antiochus died there, in the one hundred and forty-ninth year.

[[first-maccabees-6-17]]
^17^ And Lysias knew that the king was dead, and he appointed Antiochus, his son, to reign, whom he had raised from adolescence. And he called his name Eupator.

[[first-maccabees-6-18]]
^18^ And those who were in the stronghold had enclosed the Israelites by surrounding the holy places. And they continually sought to do evil to them and to support the Gentiles.

[[first-maccabees-6-19]]
^19^ And Judas intended to disperse them. And he called together all the people, in order to besiege them.

[[first-maccabees-6-20]]
^20^ And they came together and besieged them in the one hundred and fiftieth year, and they made catapults and other machines.

[[first-maccabees-6-21]]
^21^ And certain ones of these, who were besieged, escaped. And some of the impious out of Israel joined themselves to them.

[[first-maccabees-6-22]]
^22^ And they went to the king, and they said: “How long will you not act with judgment and vindicate our brothers?

[[first-maccabees-6-23]]
^23^ We resolved to serve your father, and to walk according to his precepts, and to obey his edicts.

[[first-maccabees-6-24]]
^24^ And because of this, the sons of our people have alienated themselves from us, and they have put to death as many of us as they could find, and they have torn apart our inheritances.

[[first-maccabees-6-25]]
^25^ And they have not extended their hand against us only, but also against all within our borders.

[[first-maccabees-6-26]]
^26^ And behold, this day they have taken a position near the stronghold of Jerusalem to occupy it, and they have fortified the stronghold of Bethzur.

[[first-maccabees-6-27]]
^27^ And, unless you quickly act to prevent them, they will do greater things than these, and you will not be able to subdue them.”

[[first-maccabees-6-28]]
^28^ And the king was angry when he heard this. And he called together all his friends, and the leaders of his army, and those who were over the horsemen.

[[first-maccabees-6-29]]
^29^ But there even came to him mercenary armies from other kingdoms and from the islands of the sea.

[[first-maccabees-6-30]]
^30^ And the number of his army was one hundred thousand footmen, and twenty thousand horsemen, and thirty-two elephants trained for battle.

[[first-maccabees-6-31]]
^31^ And they traveled through Idumea, and they took a position near Bethzur. And they fought for many days, and they made machines of war. But they came out and burnt them with fire, and they fought manfully.

[[first-maccabees-6-32]]
^32^ And Judas departed from the stronghold, and he moved the camp to Bethzechariah, opposite the camp of the king.

[[first-maccabees-6-33]]
^33^ And the king rose up, before it was light, and he forced his troops to march toward the way of Bethzechariah. And the armies prepared themselves for battle, and they sounded the trumpets.

[[first-maccabees-6-34]]
^34^ And they showed the elephants the blood of grapes and mulberries, to provoke them to fight.

[[first-maccabees-6-35]]
^35^ And they divided the beasts by the legions, and there stood by every elephant a thousand men, with shields joined together and with brass helmets on their heads. And five hundred well-ordered horsemen were chosen for every beast.

[[first-maccabees-6-36]]
^36^ These were ready beforehand, and wherever the beast was, they were there; and whenever it moved, they moved, and they did not depart from it.

[[first-maccabees-6-37]]
^37^ Moreover, upon them there were strong wooden turrets, watching over every beast, with machines upon them, and on them were thirty-two valiant men, who fought from above, and an Indian to rule each beast.

[[first-maccabees-6-38]]
^38^ And the rest of the horsemen, he stationed here and there, in two parts, with trumpets to stir up the army and to urge on those who were slow to move within its legions.

[[first-maccabees-6-39]]
^39^ And so, when the sun reflected off the shields of gold and of brass, the mountains were resplendent from them, and they glowed like lamps of fire.

[[first-maccabees-6-40]]
^40^ And part of the king’s army was divided to the high mountains, and the other part to the low places. And they went forth with order and caution.

[[first-maccabees-6-41]]
^41^ And all the inhabitants of the land were shaken at the voice of their multitude, and at the advance of the company, and at the clash of the armor. For the army was very great and strong.

[[first-maccabees-6-42]]
^42^ And Judas and his army drew near for battle. And there fell of the king’s army six hundred men.

[[first-maccabees-6-43]]
^43^ And Eleazar, the son of Saura, saw one of the beasts shielded with the king’s shield, and it was higher than the other beasts. So it seemed to him that the king must be on it.

[[first-maccabees-6-44]]
^44^ And he gave himself for the freedom of his people, and to obtain for himself a name in eternity.

[[first-maccabees-6-45]]
^45^ And he ran up to it boldly in the midst of the legion, killing on the right and on the left, and they fell down before him on this side and that.

[[first-maccabees-6-46]]
^46^ And he went between the feet of the elephant, and put himself under it, and he killed it. And it fell to the ground upon him, and he died there.

[[first-maccabees-6-47]]
^47^ And, seeing the strength of the king and the forcefulness of his army, they turned themselves away from them.

[[first-maccabees-6-48]]
^48^ But the king’s camp went up against them in Jerusalem. And the king’s camp took up a position near Judea and Mount Zion.

[[first-maccabees-6-49]]
^49^ And he made peace with those who were in Bethzur. And they went out of the city, because they had no provisions in their confinement, for it was the Sabbath of the land.

[[first-maccabees-6-50]]
^50^ And the king captured Bethzur, and he stationed a garrison there to keep it.

[[first-maccabees-6-51]]
^51^ And he turned his camp against the place of sanctification for many days. And he stationed there catapults and other machines: machines to cast fire, and windlasses to cast stones and darts, and small catapults to cast arrows and metal.

[[first-maccabees-6-52]]
^52^ But they also made machines against their machines, and they fought for many days.

[[first-maccabees-6-53]]
^53^ But there were no foods in the city, because it was the seventh year. And those who had remained in Judea were from the Gentiles, so they consumed all that they had left from what had been stored up.

[[first-maccabees-6-54]]
^54^ And there remained in the holy places a few men, for the famine had prevailed over them. And they were scattered, each one to his own place.

[[first-maccabees-6-55]]
^55^ Then Lysias heard that Philip, whom king Antiochus had appointed, when he was still alive, to raise his son, Antiochus, and to reign,

[[first-maccabees-6-56]]
^56^ had returned from Persia and Media, with the army that went with him, and that he sought to take upon himself the affairs of the kingdom.

[[first-maccabees-6-57]]
^57^ He hurried to go and to say to the king and the commanders of the army: “We are weakened every day, and our food is limited, and the place that we besiege is strong, and it is incumbent upon us to put the kingdom in order.

[[first-maccabees-6-58]]
^58^ And so now, let us bestow a pledge to these men, and make peace with them and with all their nation.

[[first-maccabees-6-59]]
^59^ And let us establish for them that they may walk according to their own laws, just as before. For, because of their laws, which we despised, they have become angry and have done all these things.”

[[first-maccabees-6-60]]
^60^ And the idea was pleasing in the sight of the king and the leaders. And he sent to them to make peace. And they accepted it.

[[first-maccabees-6-61]]
^61^ And the king and the leaders swore to them. And they went out of the stronghold.

[[first-maccabees-6-62]]
^62^ Then the king entered into Mount Zion, and saw the fortifications of the place, and so he abruptly broke the oath that he had sworn, and he commanded the surrounding wall to be destroyed.

[[first-maccabees-6-63]]
^63^ And he departed in haste and returned to Antioch, where he found Philip ruling the city. And he fought against him and occupied the city.


[[first-maccabees-7]]
== Chapter 7

[[first-maccabees-7-1]]
^1^ In the one hundred and fifty-first year, Demetrius, the son of Seleucus, departed from the city of Rome, and he went up with a few men to a maritime city, and he reigned there.

[[first-maccabees-7-2]]
^2^ And it happened that, as he entered into the house of the kingdom of his fathers, the army captured Antiochus and Lysias, to bring them to him.

[[first-maccabees-7-3]]
^3^ And the matter became known to him, and he said, “Do not show me their face.”

[[first-maccabees-7-4]]
^4^ And so the army killed them. And Demetrius sat upon the throne of his kingdom.

[[first-maccabees-7-5]]
^5^ And there came to him iniquitous and impious men from Israel. And Alcimus was their leader, who wanted to be made a priest.

[[first-maccabees-7-6]]
^6^ And they accused the people to the king, saying: “Judas and his brothers have destroyed all your friends, and he has scattered us from our land.

[[first-maccabees-7-7]]
^7^ Now, therefore, send a man, whom you trust, and let him go and see all the destruction he has done to us and to the regions of the king. And let him punish all his friends and their helpers.”

[[first-maccabees-7-8]]
^8^ And so the king chose, from among his friends, Bacchides, who ruled across the great river in the kingdom, and who was faithful to the king. And he sent him

[[first-maccabees-7-9]]
^9^ to see the destruction that Judas had done. Moreover, he appointed the wicked Alcimus to the priesthood, and he commanded him to take revenge on the sons of Israel.

[[first-maccabees-7-10]]
^10^ And they rose up and came forth with a great army into the land of Judah. And they sent messengers, who spoke to Judas and his brothers with words of peace, in deceitfulness.

[[first-maccabees-7-11]]
^11^ But they did not heed their words, for they saw that they arrived with a great army.

[[first-maccabees-7-12]]
^12^ Then there assembled to Alcimus and Bacchides, a congregation of scribes, to seek just terms.

[[first-maccabees-7-13]]
^13^ And first, the Hasideans, who were among the sons of Israel, also sought peace from them.

[[first-maccabees-7-14]]
^14^ For they said, “A man who is a priest from the offspring of Aaron has arrived; he will not deceive us.”

[[first-maccabees-7-15]]
^15^ And he spoke to them peaceful words, and he swore to them, saying, “We will not carry out any evil against you or your friends.”

[[first-maccabees-7-16]]
^16^ And they believed him. And he captured sixty of their men and killed them in one day, according to the word that is written:

[[first-maccabees-7-17]]
^17^ The flesh of your saints, and their blood, they have poured out all around Jerusalem, and there was no one who would bury them.

[[first-maccabees-7-18]]
^18^ Then fear and trembling hovered over all the people. For they said: “There is no truth or judgment among them. For they have transgressed the agreement and the oath that they swore.”

[[first-maccabees-7-19]]
^19^ And Bacchides moved the camp from Jerusalem, and he took up a position at Bethzaith. And he sent and captured many of those who had fled from him, and some of the people he killed in sacrifice, and he threw them into a great pit.

[[first-maccabees-7-20]]
^20^ Then he committed the country to Alcimus, and he left behind troops with him to assist him. And so Bacchides went away to the king.

[[first-maccabees-7-21]]
^21^ And Alcimus did what he pleased by means of his leadership of the priesthood.

[[first-maccabees-7-22]]
^22^ And all those who disturbed the people assembled before him, and they obtained the land of Judah, and they caused a great scourging in Israel.

[[first-maccabees-7-23]]
^23^ And Judas saw all the evils that Alcimus, and those who were with him, did to the sons of Israel, even more than the Gentiles did.

[[first-maccabees-7-24]]
^24^ And he went out into all the parts surrounding Judea, and he took vengeance on the men who had rebelled, and they ceased to go forth into the region any longer.

[[first-maccabees-7-25]]
^25^ But Alcimus saw that Judas, and those who were with him, prevailed. And he knew that he was not able to withstand them. And so he returned to the king, and he accused them of many crimes.

[[first-maccabees-7-26]]
^26^ And the king sent Nicanor, one of his principal noblemen, who was a cultivator of hostility against Israel. And he commanded him to overthrow the people.

[[first-maccabees-7-27]]
^27^ And Nicanor came to Jerusalem with a great army, and he sent to Judas and his brothers words of peace, with deceitfulness,

[[first-maccabees-7-28]]
^28^ saying: “Let there be no fighting between me and you. I will come with a few men, to see your faces with peace.”

[[first-maccabees-7-29]]
^29^ And he came to Judas, and they greeted one another in turns, peaceably. And the enemies were prepared to abduct Judas.

[[first-maccabees-7-30]]
^30^ And the plan became known to Judas, that he came to him with deceit. And so he became very afraid of him, and he was no longer willing to see his face.

[[first-maccabees-7-31]]
^31^ And Nicanor knew that his plan had been exposed, and he went out to meet Judas in battle near Capharsalama.

[[first-maccabees-7-32]]
^32^ And there fell of the army of Nicanor nearly five thousand men, and they fled into the city of David.

[[first-maccabees-7-33]]
^33^ And after these events, Nicanor ascended to mount Zion. And some of the priests of the people went out to greet him in peace, and to show him the holocausts that were offered for the king.

[[first-maccabees-7-34]]
^34^ But he mocked and despised them, and he defiled them. And he spoke arrogantly,

[[first-maccabees-7-35]]
^35^ and he swore with anger, saying, “Unless Judas and his army have been delivered into my hands, when I return in peace, I will burn this house.” And he went out with great anger.

[[first-maccabees-7-36]]
^36^ And the priests went in and stood before the face of the altar and the temple. And weeping, they said:

[[first-maccabees-7-37]]
^37^ “You, O Lord, have chosen this house so that your name may be invoked in it, so that it may be a house of prayer and supplication for your people.

[[first-maccabees-7-38]]
^38^ Accomplish vindication with this man and his army, and let them fall by the sword. Remember their blasphemies, and do not allow them to continue.”

[[first-maccabees-7-39]]
^39^ Then Nicanor departed from Jerusalem, and he positioned his camp near Bethhoron, and an army of Syria met him there.

[[first-maccabees-7-40]]
^40^ And Judas took a position in Adasa with three thousand men. And Judas prayed, and he said:

[[first-maccabees-7-41]]
^41^ “O Lord, when those who were sent by king Sennacherib blasphemed against you, an angel went out and struck one hundred and eighty-five thousand of them.

[[first-maccabees-7-42]]
^42^ Just so, crush this army in our sight today, and so let the others know that he has spoken evil against your sanctuary. And judge him according to his wickedness.”

[[first-maccabees-7-43]]
^43^ And the armies were sent into battle together on the thirteenth day of the month of Adar. And the camp of Nicanor was crushed, and he himself was among the first slain in the battle.

[[first-maccabees-7-44]]
^44^ So then, when his army saw that Nicanor had fallen, they threw away their weapons and fled.

[[first-maccabees-7-45]]
^45^ And they pursued them for one day’s journey from Adasa, even until one comes into Gazara, and they sounded the trumpets after them with signals.

[[first-maccabees-7-46]]
^46^ And they went forth from all of the towns all around Judea. And they herded them with the horns, and they turned back again to them, and they were all felled with the sword, and there was not so much as one of them left behind.

[[first-maccabees-7-47]]
^47^ And they took their spoils like a prey, and they cut off the head of Nicanor, and his right hand, which he had extended arrogantly, and they brought it, and hung it up opposite Jerusalem.

[[first-maccabees-7-48]]
^48^ And the people rejoiced exceedingly, and they spent that day in great joy.

[[first-maccabees-7-49]]
^49^ And he established that this day should be kept every year, on the thirteenth day of the month of Adar.

[[first-maccabees-7-50]]
^50^ And the land of Judah was quieted for a brief time.


[[first-maccabees-8]]
== Chapter 8

[[first-maccabees-8-1]]
^1^ And Judas heard of the fame of the Romans, that they are powerful and strong, and that they willingly agree to all things that are asked of them; and that, whoever was agreeable to them, they established a friendship with them, and so they are powerful and resourceful.

[[first-maccabees-8-2]]
^2^ And they heard of their battles, and the successful works that they had accomplished in Galatia, how they had subdued them and brought them under tribute,

[[first-maccabees-8-3]]
^3^ and what great things they had accomplished in the region of Spain, and that they had driven under their power the mines of silver and gold which are there, and that they had obtained possession of the entire place by their counsel and patience,

[[first-maccabees-8-4]]
^4^ and that they had overcome places that were very far from them, and kings, who came against them from the ends of the earth, and had crushed them and struck them with a great scourging, while the rest pay tribute to them every year,

[[first-maccabees-8-5]]
^5^ and that they had defeated in battle Philip, and Perses the king of the Ceteans, and the others who had taken up arms against them, and had crushed them in warfare and subdued them,

[[first-maccabees-8-6]]
^6^ and how Antiochus, the great king of Asia, who brought a fight against them, having one hundred and twenty elephants, with horsemen, and swift chariots, and a very great army, was crushed by them,

[[first-maccabees-8-7]]
^7^ and how they had captured him alive and had decreed to him that both he and those who would reign after him would pay a great tribute, and that he should provide hostages bound to an agreement,

[[first-maccabees-8-8]]
^8^ and that regions from the Indians, and from the Medes, and from the Lydians, from among their best regions, with those whom they had taken from them, they gave to king Eumenes.

[[first-maccabees-8-9]]
^9^ And those who were in Greece wanted to go out and defeat them, but they became aware of this plan.

[[first-maccabees-8-10]]
^10^ And so they sent one general to them, and he fought against them, and many of them fell, and they led into captivity their wives, and their sons, and they despoiled them and took possession of their land, and they destroyed their walls and drove them into servitude, even to this day.

[[first-maccabees-8-11]]
^11^ And the remaining kingdoms and islands, which at any time had resisted them, they destroyed and drove under their power.

[[first-maccabees-8-12]]
^12^ But with their friends, and with those who remained at peace with them, they maintained friendship and conquered kingdoms: those that were near, and those that were far off. For all those who heard of their name were afraid of them.

[[first-maccabees-8-13]]
^13^ In fact, whomever they wanted to help become ruler, these reigned, but whomever they wanted, they deposed from the kingdom. And they were greatly exalted.

[[first-maccabees-8-14]]
^14^ And of all these, none wore a diadem or was clothed in purple, to be magnified in this.

[[first-maccabees-8-15]]
^15^ And also, they had made themselves a senate house, and they consulted daily with three hundred and twenty men, continually acting as a counsel for the multitude, so that they would do the things that were right.

[[first-maccabees-8-16]]
^16^ And they commit their government to one man each year, to rule over their entire land, and they all obey this one, and there is no envy or jealousy among them.

[[first-maccabees-8-17]]
^17^ And so Judas chose Eupolemus, the son of John, the son of Jacob, and Jason, the son of Eleazar, and he sent them to Rome to make an agreement of friendship and an alliance with them,

[[first-maccabees-8-18]]
^18^ and so that they would take away from them the yoke of the Grecians, for they saw that they oppressed the kingdom of Israel with servitude.

[[first-maccabees-8-19]]
^19^ And they went to Rome, a very long journey, and they entered the senate house, and they said,

[[first-maccabees-8-20]]
^20^ “Judas Maccabeus, and his brothers, and the people of the Jews, have sent us to you to establish with you an alliance and peace, and so that we may be registered among your associates and friends.”

[[first-maccabees-8-21]]
^21^ And the word was pleasing in their sight.

[[first-maccabees-8-22]]
^22^ And this is a copy of the writing, which they rewrote on tablets of brass and sent to Jerusalem, so that it would be with them in that place as a memorial of the peace and alliance:

[[first-maccabees-8-23]]
^23^ “May all be well with the Romans and with the nation of the Jews, at sea and on land, forever, and may sword and enemy be far away from them.

[[first-maccabees-8-24]]
^24^ But if a war is instituted against the Romans first, or against any of their allies in all their dominions,

[[first-maccabees-8-25]]
^25^ the nation of the Jews will bring help to them, just as the situation shall direct, whole-heartedly.

[[first-maccabees-8-26]]
^26^ And those who do battle, they need not provide with supplies of wheat, or arms, or money, or ships, just as it seems good to the Romans, and they shall obey their orders, while taking nothing from them.

[[first-maccabees-8-27]]
^27^ But in like manner also, if war will have fallen upon the nation of the Jews first, the Romans shall help them willingly, just as the situation permits them.

[[first-maccabees-8-28]]
^28^ And those who give assistance will not be provided with wheat, or arms, or money, or ships, just as it seems good to the Romans. And they shall obey their orders without deceit.

[[first-maccabees-8-29]]
^29^ According to these words, the Romans have made an agreement with the people of the Jews.

[[first-maccabees-8-30]]
^30^ And, if after these words, one or another would want to add anything to, or take anything from these, they may do as they propose. And whatever they add or take away, it shall be ratified.

[[first-maccabees-8-31]]
^31^ Moreover, concerning the evils that king Demetrius did to them, we have written to him, saying, ‘Why have you made your yoke heavy upon our friends and allies, the Jews?

[[first-maccabees-8-32]]
^32^ If, therefore, they come again to us against you, we will render judgment for them, and we will make war against you by sea and by land.’ ”


[[first-maccabees-9]]
== Chapter 9

[[first-maccabees-9-1]]
^1^ Meanwhile, when Demetrius heard that Nicanor and his army had fallen in battle, he again positioned Bacchides and Alcimus in Judea, and the right horn of his army with them.

[[first-maccabees-9-2]]
^2^ And they traveled by the way that leads to Gilgal, and they set up camp in Mesaloth, which is in Arbela. And they occupied it, and they destroyed the lives of many men.

[[first-maccabees-9-3]]
^3^ In the first month of the one hundred and fifty-second year, they positioned the army near Jerusalem.

[[first-maccabees-9-4]]
^4^ And they rose up and went to Berea, with twenty thousand men and two thousand horsemen.

[[first-maccabees-9-5]]
^5^ Now Judas had stationed his camp in Elasa, and three thousand chosen men were with him.

[[first-maccabees-9-6]]
^6^ And they saw the multitude of the army, that they were many, and they became very afraid. And many withdrew themselves from the camp, and there remained of them no more than eight hundred men.

[[first-maccabees-9-7]]
^7^ And Judas saw that his army had slipped away and that the battle pressed upon him, and his heart was shattered, because he did not have time to gather them together, and he was very discouraged.

[[first-maccabees-9-8]]
^8^ And so, he said to those who were remaining, “Let us rise up and go against our enemies, perhaps we may be able to fight against them.”

[[first-maccabees-9-9]]
^9^ But they dissuaded him, saying: “We will not be able, but let us try to save our lives and return to our brothers, and then we will fight against them. For we are but few.”

[[first-maccabees-9-10]]
^10^ And Judas said: “Far be it from us, to do this thing, so as to flee away from them. But if our time has drawn near, let us die with virtue, on behalf of our brothers, and let us not inflict guilt upon our glory.”

[[first-maccabees-9-11]]
^11^ And the army moved from the camp, and they stood to meet them. And the horsemen were divided into two parts, and the stone-slingers and archers went before the army, and the first ones were all powerful men, experienced in combat.

[[first-maccabees-9-12]]
^12^ Moreover, Bacchides was with the right horn, and the legion drew near on both sides, and they sounded the trumpets.

[[first-maccabees-9-13]]
^13^ But those also who were from the side of Judas, these also now cried out, and the earth shook at the noise of the armies. And the battle was joined from morning, even until evening.

[[first-maccabees-9-14]]
^14^ And Judas saw that the stronger part of the army of Bacchides was on the right side, and all the steadfast in heart came together with him.

[[first-maccabees-9-15]]
^15^ And the right part was crushed by them, and he pursued them even to Mount Azotus.

[[first-maccabees-9-16]]
^16^ And those who were with the left horn saw that the right horn was crushed, and so they followed after Judas, and those who were with him, at their back.

[[first-maccabees-9-17]]
^17^ And the battle was hard fought, and there fell many wounded from one side and the other.

[[first-maccabees-9-18]]
^18^ And Judas fell, and the others fled away.

[[first-maccabees-9-19]]
^19^ And Jonathan and Simon carried Judas, their brother, and they buried him in the sepulcher of their fathers, in the city of Modin.

[[first-maccabees-9-20]]
^20^ And all the people of Israel wept for him with a great wailing, and they mourned him for many days.

[[first-maccabees-9-21]]
^21^ And they said, “Such a powerful man has fallen, who accomplished the salvation of the people of Israel!”

[[first-maccabees-9-22]]
^22^ But the rest of the words, about the wars of Judas, and the virtuous acts that he did, and his magnitude, have not been written. For they were very many.

[[first-maccabees-9-23]]
^23^ And it happened that, after the death of Judas, the iniquitous began to emerge in all the parts of Israel, and they began to encourage all those who worked iniquity.

[[first-maccabees-9-24]]
^24^ In those days, there occurred a very great famine, and the entire region handed itself over to Bacchides.

[[first-maccabees-9-25]]
^25^ And Bacchides chose impious men, and he appointed them as rulers of the region.

[[first-maccabees-9-26]]
^26^ And they sought out and persecuted the friends of Judas, and they led them to Bacchides, and he took vengeance on them and abused them.

[[first-maccabees-9-27]]
^27^ And there occurred a great tribulation in Israel, such as had never been, since the day that there was no prophet seen in Israel.

[[first-maccabees-9-28]]
^28^ And all the friends of Judas gathered together, and they said to Jonathan:

[[first-maccabees-9-29]]
^29^ “Since your brother Judas has fallen away, there is not a man like him to go forth against our enemies, against Bacchides and those who are the enemies of our nation.

[[first-maccabees-9-30]]
^30^ And so now, we have chosen you in his place, on this day, to be our leader and commander in order to wage our wars.”

[[first-maccabees-9-31]]
^31^ And so, at that time, Jonathan took upon himself the leadership, and he rose up in the place of Judas, his brother.

[[first-maccabees-9-32]]
^32^ And Bacchides knew of it, and he sought to kill him.

[[first-maccabees-9-33]]
^33^ And Jonathan and his brother Simon knew of this, and so did all who were with them. And they fled into the desert of Tekoa, and they settled by the water of lake Asphar.

[[first-maccabees-9-34]]
^34^ And Bacchides knew of it, and on the day of the Sabbath, he himself arrived, with all his army, across the Jordan.

[[first-maccabees-9-35]]
^35^ And Jonathan sent his brother, a commander of the people, to ask the Nabateans, his friends, to lend them their equipment, which was abundant.

[[first-maccabees-9-36]]
^36^ And the sons of Jambri went forth from Medeba, and they captured John, and all that he had, and they went away in possession of these.

[[first-maccabees-9-37]]
^37^ After these events, it was reported to Jonathan and his brother Simon that the sons of Jambri were having a great marriage celebration, and that they would be leading the bride, a daughter of one of the great leaders of Canaan, out of Medeba with great fanfare.

[[first-maccabees-9-38]]
^38^ And they remembered the blood of John, their brother. And they went up and hid themselves under the cover of the mountain.

[[first-maccabees-9-39]]
^39^ And they lifted up their eyes and saw. And behold, a tumult and a well-prepared multitude. And the bridegroom proceeded, with his friends and his brothers, to meet them with timbrels, and musical instruments, and many weapons.

[[first-maccabees-9-40]]
^40^ And they rose up against them out of ambush, and they killed them, and there fell many wounded, and the remainder fled into the mountains, and they took all their spoils.

[[first-maccabees-9-41]]
^41^ And the marriage celebration was turned into mourning, and the voice of their musical instruments into lamentation.

[[first-maccabees-9-42]]
^42^ And they took revenge for the blood of their brother, and they returned to the bank of the Jordan.

[[first-maccabees-9-43]]
^43^ And Bacchides heard about this, and he came on the day of the Sabbath all the way to the coast of the Jordan, with a great force.

[[first-maccabees-9-44]]
^44^ And Jonathan said to his own: “Let us rise up and fight against our enemies. For it is not today, as it was yesterday, or the day before.

[[first-maccabees-9-45]]
^45^ For behold, the war is before us, and truly, with the water of the Jordan here and there, and the banks, and the marshes, and the woods: there is no place for us to turn aside.

[[first-maccabees-9-46]]
^46^ Therefore, cry out now to heaven so that you may be freed from the hand of your enemies.” And they joined together in warfare.

[[first-maccabees-9-47]]
^47^ And Jonathan extended his hand to strike Bacchides, but he turned away from him in retreat.

[[first-maccabees-9-48]]
^48^ And Jonathan, and those who were with him, leaped forward into the Jordan, and they swam across the Jordan to them.

[[first-maccabees-9-49]]
^49^ And there fell from the side of Bacchides on that day one thousand men. And they returned to Jerusalem.

[[first-maccabees-9-50]]
^50^ And they built fortified cities in Judea: the fortification that was in Jericho, and in Emmaus, and in Bethhoron, and in Bethel, and Timnath, and Pharathon, and Tephon, with high walls, and gates, and bars.

[[first-maccabees-9-51]]
^51^ And he stationed garrisons in them, so that those in Israel became trained in warfare.

[[first-maccabees-9-52]]
^52^ And he fortified the city of Bethzur, and of Gazara, and the stronghold, and he stationed auxiliaries in them, with supplies of rations.

[[first-maccabees-9-53]]
^53^ And he took the sons of the leaders of the region for hostages, and put them in the stronghold in Jerusalem under guard.

[[first-maccabees-9-54]]
^54^ Now in the second month of the one hundred and fifty-third year, Alcimus instructed that the walls of the inner court of the sanctuary be destroyed, and that the works of the prophets be destroyed. And he began to destroy them.

[[first-maccabees-9-55]]
^55^ At that time, Alcimus was struck, and his works were hindered, and his mouth was closed shut, and he was weakened with paralysis, so that he was no longer able speak a word, nor to give orders concerning his house.

[[first-maccabees-9-56]]
^56^ And Alcimus died at that time, in great torment.

[[first-maccabees-9-57]]
^57^ And Bacchides saw that Alcimus was dead. And he returned to the king. And the land was quiet for two years.

[[first-maccabees-9-58]]
^58^ And all the iniquitous considered together, saying, “Behold, Jonathan, and those who are with him, live in quietude and confidence. Now, therefore, let us bring forth Bacchides, and he will capture them all, in one night.”

[[first-maccabees-9-59]]
^59^ So they went and gave counsel to him.

[[first-maccabees-9-60]]
^60^ And he rose up, so as to advance with a great army. And he secretly sent letters to his associates who were in Judea, to seize Jonathan and those who were with him. But they were not able, for their plan became known to them.

[[first-maccabees-9-61]]
^61^ And he apprehended, from the men of the region, those who were the leaders of this malice, fifty men. And he killed them.

[[first-maccabees-9-62]]
^62^ And Jonathan, and Simon, and those who were with him, withdrew into Bethbasi, which is in the desert. And he repaired its breaches, and they fortified it.

[[first-maccabees-9-63]]
^63^ And Bacchides knew about it, and he gathered together all his multitude. And he reported it to those who were from Judea.

[[first-maccabees-9-64]]
^64^ And he came and made camp above Bethbasi, and he fought against it for many days, and he made machines of war.

[[first-maccabees-9-65]]
^65^ But Jonathan left behind his brother Simon in the city, and he went out into the country, and he approached with a number of men,

[[first-maccabees-9-66]]
^66^ and he struck Odomera and his brothers, and the sons of Phasiron, in their tents. And he began to slaughter and to increase in forces.

[[first-maccabees-9-67]]
^67^ In truth, Simon, and those who were with him, went forth from the city and burned the machines of war,

[[first-maccabees-9-68]]
^68^ and they fought against Bacchides, and he was crushed by them. And they afflicted him greatly, because his counsel and his meetings were in vain.

[[first-maccabees-9-69]]
^69^ And he was angry with the men of iniquity who had given him counsel to come into their region, and he killed many of them. But he decided to depart with the remainder into their country.

[[first-maccabees-9-70]]
^70^ And Jonathan knew of it, and he sent ambassadors to him to arrange a peace with him, and to restore the captives to him.

[[first-maccabees-9-71]]
^71^ And he accepted it willingly, and he acted according to his words, and he swore that he would do him no evil all the days of his life.

[[first-maccabees-9-72]]
^72^ And he restored to him the captives which he previously had been given from the land of Judah. And he turned back and went away into his own land, and he no longer drew near, in order to enter into their borders.

[[first-maccabees-9-73]]
^73^ And so the sword ceased from Israel. And Jonathan lived in Michmash, and, in that place, Jonathan began to judge the people, and he destroyed the impious out of Israel.


[[first-maccabees-10]]
== Chapter 10

[[first-maccabees-10-1]]
^1^ And in the one hundred and sixtieth year, Alexander, the son of Antiochus, who was surnamed the illustrious, came up and occupied Ptolemais, and they received him, and he reigned there.

[[first-maccabees-10-2]]
^2^ And king Demetrius heard of it, and he gathered together an exceedingly great army, and he went forth to meet him in battle.

[[first-maccabees-10-3]]
^3^ And Demetrius sent a letter to Jonathan, with peaceful words, to magnify him.

[[first-maccabees-10-4]]
^4^ For he said, “Let us first make a peace with him, before he makes one with Alexander against us.

[[first-maccabees-10-5]]
^5^ For he will remember all the evils that we have done to him, and to his brother, and to his nation.”

[[first-maccabees-10-6]]
^6^ And he gave him the authority to gather together an army, and to fabricate weapons, so that he would be his associate. And the hostages who were in the stronghold, he ordered to be handed over to him.

[[first-maccabees-10-7]]
^7^ And Jonathan came to Jerusalem, and he read the letters in the hearing of all the people and of those who were in the stronghold.

[[first-maccabees-10-8]]
^8^ And they were struck with a great fear, because they heard that the king gave him the authority to gather together an army.

[[first-maccabees-10-9]]
^9^ And the hostages were handed over to Jonathan, and he restored them to their parents.

[[first-maccabees-10-10]]
^10^ And Jonathan lived in Jerusalem, and he began to rebuild and repair the city.

[[first-maccabees-10-11]]
^11^ And he told those doing the work to build up the walls, and mount Zion, all around, with square stones, as a fortification. And they did so.

[[first-maccabees-10-12]]
^12^ Then the foreigners, who were in the fortifications that Bacchides had built, fled away.

[[first-maccabees-10-13]]
^13^ And each one abandoned his place and departed into his own land.

[[first-maccabees-10-14]]
^14^ Only in Bethzur did there remain some others of these, who had forsaken the law and the precepts of God. For this was a refuge for them.

[[first-maccabees-10-15]]
^15^ And king Alexander heard of the promises that Demetrius promised to Jonathan. And they described the battles to him, and the virtuous deeds that he and his brothers had done, and the hardships that they had endured.

[[first-maccabees-10-16]]
^16^ And he said: “Would we ever find another such man? And so now, let us make him our friend and our associate.”

[[first-maccabees-10-17]]
^17^ And so, he wrote a letter, and he sent it to him, according to these words, saying:

[[first-maccabees-10-18]]
^18^ “King Alexander to his brother, Jonathan: greetings.

[[first-maccabees-10-19]]
^19^ We have heard of you, that you are a man of power and strength, and that you are fit to be our friend.

[[first-maccabees-10-20]]
^20^ And so now, on this day, we appoint that you be high priest of your people, and that you be called the king’s friend, (and he sent him a purple robe, and a crown of gold,) and that you be of one mind with us in our affairs, and that you keep friendship with us.”

[[first-maccabees-10-21]]
^21^ Then Jonathan clothed himself with the holy vestment, in the seventh month, in the one hundred and sixtieth year, on the solemn day of the Feast of Tabernacles. And he gathered together an army, and he made an abundance of weapons.

[[first-maccabees-10-22]]
^22^ And Demetrius heard these words, and he was exceedingly sorrowful, and he said:

[[first-maccabees-10-23]]
^23^ “What have we done in this, that Alexander has gone before us to obtain the friendship of the Jews to strengthen himself?

[[first-maccabees-10-24]]
^24^ I also will write to them words of petition, and offer positions of rank and gifts, so that they may act in assistance to me.”

[[first-maccabees-10-25]]
^25^ And he wrote to them in these words: “King Demetrius to the nation of the Jews: greetings.

[[first-maccabees-10-26]]
^26^ Since you have kept the peace with us, and have remained in our friendship, and have not made agreements with our enemies, we have heard of this, and we are glad.

[[first-maccabees-10-27]]
^27^ And so now, persevere still to remain faithful to us, and we will reward you with good things for what you have done for us.

[[first-maccabees-10-28]]
^28^ And we will repay you for your many expenses, and we will give you gifts.

[[first-maccabees-10-29]]
^29^ And now, I release you, and all the Jews, from tributes, and I grant to you the payments of salt, and I send back the crowns and the thirds of the seed.

[[first-maccabees-10-30]]
^30^ And the one half portion of the fruit from the trees, which is my share, I relinquish to you from this day and hereafter, so that it shall not be taken from the land of Judah, nor from the three cities that have been added to it from Samaria and Galilee, from this day and for all time.

[[first-maccabees-10-31]]
^31^ And let Jerusalem be holy and free within its borders, and let the tenths and tributes be for itself.

[[first-maccabees-10-32]]
^32^ And I even return authority over the stronghold, which is in Jerusalem, and I give it to the high priest, in order to appoint in it any such men as he will choose, who will guard it.

[[first-maccabees-10-33]]
^33^ And every soul of the Jews who were taken captive from the land of Judah in all my kingdom, I set at liberty without charge, so that they are all released from tributes, even of their cattle.

[[first-maccabees-10-34]]
^34^ And all the days of solemnities, and the Sabbaths, and the new moons, and the decreed days, and the three days before the solemn day, and three days after the solemn day, shall all be days of immunity and remission for all the Jews who are in my kingdom.

[[first-maccabees-10-35]]
^35^ And no one will have the authority to do anything, or to incite any plots, against any of them, in all cases.

[[first-maccabees-10-36]]
^36^ And let there be enrolled from the Jews, into the army of the king, up to thirty thousand men. And allowances shall be given to them, just as is due to all the king’s army. And some of them shall be appointed to be in the fortresses of the great king.

[[first-maccabees-10-37]]
^37^ And some of them shall be set over the affairs of the kingdom, those who act with faith, and let the leaders be from them, and let them walk by their own laws, just as the king has commanded in the land of Judah.

[[first-maccabees-10-38]]
^38^ And the three cities that have been added to Judea from the region of Samaria, let them be counted with Judea, so that they may be united as one, and so that they may obey no other authority, except the high priest.

[[first-maccabees-10-39]]
^39^ Ptolemais and its confines, I give as a free gift to the holy places that are in Jerusalem, for the necessary expenses of the holy things.

[[first-maccabees-10-40]]
^40^ And I give, every year, fifteen thousand shekels of silver from the allotment of the king, from what belongs to me.

[[first-maccabees-10-41]]
^41^ And all that has been left over, which those who were set over the affairs in prior years have not paid: from this time, they will give it to the works of the house.

[[first-maccabees-10-42]]
^42^ And beyond this, they shall receive five thousand shekels of silver from the allotment of the holy places each year, and this will belong to the priests who perform the ministry.

[[first-maccabees-10-43]]
^43^ And whoever will flee into the temple that is in Jerusalem, or in any of its parts, being liable before the king in any matter, let them be released, and all that is theirs in my kingdom, let them have it freely.

[[first-maccabees-10-44]]
^44^ And as to the works of rebuilding and repairing the holy places, the expenses shall be given from the king’s revenues.

[[first-maccabees-10-45]]
^45^ And as to the raising of the walls of Jerusalem and the fortifications all around it, the expenses shall be given from the king’s revenues, as also for the building of the walls in Judea.”

[[first-maccabees-10-46]]
^46^ So when Jonathan and the people heard these words, they did not believe or accept them, because they remembered the great malice that he had done in Israel, for he had troubled them greatly.

[[first-maccabees-10-47]]
^47^ And so they were pleased with Alexander, because he had been to them a leader with words of peace, and they were of assistance to him every day.

[[first-maccabees-10-48]]
^48^ And so king Alexander gathered together a great army, and he moved his camp against Demetrius.

[[first-maccabees-10-49]]
^49^ And the two kings joined together in battle, and the army of Demetrius fled away, and Alexander followed after him, and he closed in on them.

[[first-maccabees-10-50]]
^50^ And the battle was hard fought, until the sun went down. And Demetrius was slain on that day.

[[first-maccabees-10-51]]
^51^ And Alexander sent ambassadors to Ptolemy, the king of Egypt, according to these words, saying:

[[first-maccabees-10-52]]
^52^ “Know that I have returned to my kingdom, and I am seated upon the throne of my fathers, and I have obtained the leadership, and I have crushed Demetrius, and I have taken possession of our country,

[[first-maccabees-10-53]]
^53^ and I have joined battle with him, and both he and his camp have been crushed by us, and we are seated on the throne of his kingdom.

[[first-maccabees-10-54]]
^54^ And now, let us establish a friendship with one with another. And give me your daughter as a wife, and I will be your son-in-law, and I will give gifts that are worthy of you, to both you and her.”

[[first-maccabees-10-55]]
^55^ And king Ptolemy responded by saying: “Happy is the day on which you were returned to the land of your fathers, and you sat on the throne of their kingdom.

[[first-maccabees-10-56]]
^56^ And now, I will do for you as you have written. But meet with me at Ptolemais, so that we may see one another, and so that I may espouse her to you, just as you have said.”

[[first-maccabees-10-57]]
^57^ And so Ptolemy departed from Egypt, both he and his daughter Cleopatra, and he arrived at Ptolemais in the one hundred and sixty-second year.

[[first-maccabees-10-58]]
^58^ And king Alexander met him, and he gave him Cleopatra, his daughter. And he celebrated her marriage at Ptolemais with great glory, just as befits kings.

[[first-maccabees-10-59]]
^59^ And king Alexander wrote to Jonathan, that he should come to meet him.

[[first-maccabees-10-60]]
^60^ And he went forth with glory to Ptolemais, and he met the two kings there, and he gave them much silver, and gold, and gifts. And he found favor in their sight.

[[first-maccabees-10-61]]
^61^ And some of the pestilent men of Israel, men of iniquity, came together against him, interrupting with objections against him. And the king did not attend to them.

[[first-maccabees-10-62]]
^62^ And he ordered that Jonathan’s garments be taken away from him, and that he be clothed in purple. And they did so. And the king arranged for him to sit with him.

[[first-maccabees-10-63]]
^63^ And he said to his princes, “Go out with him into the midst of the city, and make a proclamation, so that no one may raise objections against him in any matter, and so that no one may bother him for any reason.”

[[first-maccabees-10-64]]
^64^ And so it happened that, when his accusers saw his glory being proclaimed, and him clothed in purple, they all fled away.

[[first-maccabees-10-65]]
^65^ And the king magnified him, and he enrolled him among his foremost friends, and he gave him a position as governor and as a participant in his dominion.

[[first-maccabees-10-66]]
^66^ And Jonathan returned to Jerusalem with peace and joy.

[[first-maccabees-10-67]]
^67^ In the one hundred and sixty-fifth year, Demetrius, the son of Demetrius, came from Crete into the land of his fathers.

[[first-maccabees-10-68]]
^68^ And king Alexander heard of it, and he was very sorrowful, and he returned to Antioch.

[[first-maccabees-10-69]]
^69^ And king Demetrius appointed Apollonius as his general, who was in charge of Coelesyria. And he gathered together a great army, and he drew near to Jamnia. And he sent to Jonathan, the high priest,

[[first-maccabees-10-70]]
^70^ saying: “You alone resist us, and so I have been brought to derision and disgrace, because you exercise your power against us in the mountains.

[[first-maccabees-10-71]]
^71^ Now, therefore, if you trust in your forces, descend to us in the plains, and there let us contest one another. For the power of war is with me.

[[first-maccabees-10-72]]
^72^ Inquire, and learn who I am, and the others, who are auxiliaries to me, who also say that your feet cannot stand before our face, for your fathers have twice been put to flight in their own land.

[[first-maccabees-10-73]]
^73^ And now, how will you be able to withstand the horsemen, and so great an army in the plains, where there is no stone, or rock, or place to flee?”

[[first-maccabees-10-74]]
^74^ But when Jonathan heard the words of Apollonius, he was moved in his soul. And he chose ten thousand men, and he departed from Jerusalem, and Simon, his brother, met him to help him.

[[first-maccabees-10-75]]
^75^ And they positioned their tents near Joppa, but they excluded him from the city, because a garrison from Apollonius was in Joppa. And so, he attacked it.

[[first-maccabees-10-76]]
^76^ And those who were in the city, being terrified, opened to him. And so Jonathan obtained Joppa.

[[first-maccabees-10-77]]
^77^ And Apollonius heard of it, and he moved three thousand horsemen, and a great army.

[[first-maccabees-10-78]]
^78^ And he went toward Azotus, like one making a journey, but he suddenly departed into the plains, because he had a great number of horsemen, and he trusted in them. And Jonathan followed after him to Azotus, and they joined together in battle.

[[first-maccabees-10-79]]
^79^ And Apollonius secretly left behind them in the camp a thousand horsemen.

[[first-maccabees-10-80]]
^80^ And Jonathan realized that there was an ambush behind him, and they surrounded his camp, and they cast darts at the people from morning until evening.

[[first-maccabees-10-81]]
^81^ But the people stood firm, just as Jonathan had instructed them, and their horses suffered hardships.

[[first-maccabees-10-82]]
^82^ Then Simon drew forth his army, and he sent them against the legion. For the horsemen were wearied. And they were crushed by him, and they fled.

[[first-maccabees-10-83]]
^83^ And those who were scattered throughout the plains fled to Azotus, and they entered into Bethdagon, so that, by their idol in that place, they might save themselves.

[[first-maccabees-10-84]]
^84^ But Jonathan set fire to Azotus and to the cities that were all around it, and he captured their spoils and the temple of Dagon. And he burned with fire all those who had fled into it.

[[first-maccabees-10-85]]
^85^ And so it was that those who fell by the sword, with those who were burned, were nearly eight thousand men.

[[first-maccabees-10-86]]
^86^ And Jonathan, removed his encampment from there, and he took up a position against Askalon. And they went out of the city to meet him with great glory.

[[first-maccabees-10-87]]
^87^ And Jonathan returned to Jerusalem with his own, having many spoils.

[[first-maccabees-10-88]]
^88^ And it happened that, when king Alexander heard these words, he added still more glory to Jonathan.

[[first-maccabees-10-89]]
^89^ And he sent him a clasp of gold, as is customary to be given to those who are of royal lineage. And he gave him Ekron, and all its borders, as a possession.


[[first-maccabees-11]]
== Chapter 11

[[first-maccabees-11-1]]
^1^ And the king of Egypt gathered together an army, like the sand that is along the shore of the sea, and many ships. And he sought to obtain the kingdom of Alexander by deceit, and to add it to his own kingdom.

[[first-maccabees-11-2]]
^2^ And he departed into Syria with words of peace, and they opened the cities to him, and they were meeting with him. For king Alexander had commanded them to go out to meet him, because he was his father-in-law.

[[first-maccabees-11-3]]
^3^ But when Ptolemy entered a city, he placed garrisons of soldiers in each of the cities.

[[first-maccabees-11-4]]
^4^ And when he drew near to Azotus, they revealed to him that the temple of Dagon had been burned with fire, and Azotus and its suburbs had been demolished, and bodies had been abandoned, and that, for those who had been cut to pieces in the war, they had made a tomb along the way.

[[first-maccabees-11-5]]
^5^ And they told the king that Jonathan had done these things, so as to make him hated. But the king remained silent.

[[first-maccabees-11-6]]
^6^ And Jonathan went to meet the king at Joppa with glory, and they greeted one another, and they stayed there.

[[first-maccabees-11-7]]
^7^ And Jonathan went with the king as far as the river, which is called Eleutherus. And he returned to Jerusalem.

[[first-maccabees-11-8]]
^8^ But king Ptolemy obtained the dominion of the coastal cities, as far as Seleucia, and he devised evil plans against Alexander.

[[first-maccabees-11-9]]
^9^ And he sent ambassadors to Demetrius, saying: “Come, let us compose a pact between us, and I will give you my daughter, whom Alexander had, and you will reign in the kingdom of your father.

[[first-maccabees-11-10]]
^10^ For I regret that I have given him my daughter. For he has sought to kill me.”

[[first-maccabees-11-11]]
^11^ And he slandered him, because he coveted his kingdom.

[[first-maccabees-11-12]]
^12^ And he took away his daughter, and he gave her to Demetrius, and he alienated himself from Alexander, and his hostilities were made manifest.

[[first-maccabees-11-13]]
^13^ And Ptolemy entered Antioch, and he placed two diadems upon his head, that of Egypt, and that of Asia.

[[first-maccabees-11-14]]
^14^ Now king Alexander was in Cilicia at that time, because the people of those places were rebelling.

[[first-maccabees-11-15]]
^15^ And when Alexander heard of it, he came against him in warfare. And king Ptolemy led forth his army, and he met him with a strong hand, and he put him to flight.

[[first-maccabees-11-16]]
^16^ And Alexander fled into Arabia, so as to be protected there. And king Ptolemy was exalted.

[[first-maccabees-11-17]]
^17^ And Zabdiel the Arab took off the head of Alexander, and he sent it to Ptolemy.

[[first-maccabees-11-18]]
^18^ And king Ptolemy died on the third day, and those who were in the strongholds were destroyed by those who were in the camp.

[[first-maccabees-11-19]]
^19^ And Demetrius reigned in the one hundred and sixty-seventh year.

[[first-maccabees-11-20]]
^20^ In those days, Jonathan gathered together those who were in Judea, in order to fight against the stronghold that was in Jerusalem. And they made many machines of war against it.

[[first-maccabees-11-21]]
^21^ And so, certain men of iniquity, who hated their own people, went forth to king Demetrius, and they reported to him that Jonathan was besieging the stronghold.

[[first-maccabees-11-22]]
^22^ And when he heard it, he became angry. And immediately he came to Ptolemais, and he wrote to Jonathan that he should not besiege the stronghold, but that he should meet with him promptly, for a discussion.

[[first-maccabees-11-23]]
^23^ But when Jonathan heard this, he ordered them to besiege it. And he chose some from the elders of Israel and from the priests, and he put himself in danger.

[[first-maccabees-11-24]]
^24^ And he took gold, and silver, and vestments, and many other presents, and he went to the king at Ptolemais, and he found favor in his sight.

[[first-maccabees-11-25]]
^25^ And some of the iniquitous from his nation came forward with objections against him.

[[first-maccabees-11-26]]
^26^ And the king treated him just as those who were before him had treated him. And he exalted him in the sight of all his friends.

[[first-maccabees-11-27]]
^27^ And he confirmed him in the high priesthood and in all the other honors that he held before, and he made him the leader of his friends.

[[first-maccabees-11-28]]
^28^ And Jonathan requested of the king that he would make Judea free from tribute, along with the three districts, and Samaria, and its confines. And he promised him three hundred talents.

[[first-maccabees-11-29]]
^29^ And the king consented. And he wrote letters to Jonathan about all these things, continuing in this way:

[[first-maccabees-11-30]]
^30^ “King Demetrius to his brother Jonathan, and to the nation of the Jews: greetings.

[[first-maccabees-11-31]]
^31^ We are sending you a copy of the letter that we wrote to Lasthenes, our parent, about you, so that you will know.

[[first-maccabees-11-32]]
^32^ ‘King Demetrius to Lasthenes, his parent: greetings.

[[first-maccabees-11-33]]
^33^ We have determined to do good to the people of the Jews, who are our friends and who keep to what is just with us, because of their good will, which they hold toward us.

[[first-maccabees-11-34]]
^34^ Therefore, we have assigned to them all the parts of Judea, and the three cities, Lydda and Ramatha, which were added to Judea from Samaria, and all their confines, to be set apart for all those sacrificing in Jerusalem, in place of that which the king previously received from them each year, and in place of the fruits of the land and of the fruit trees.

[[first-maccabees-11-35]]
^35^ And, as for the rest of that which pertains to us from tithes and tributes, from this time forward, we release them from these, as well as from the drying areas of salt and the crowns that were presented to us.

[[first-maccabees-11-36]]
^36^ All these, we concede to them, and nothing of these shall be revoked, from this time forward and for all time.

[[first-maccabees-11-37]]
^37^ Now, therefore, take care to make a copy of these things, and let it be given to Jonathan and set upon the holy mountain, in an honorable place.’ ”

[[first-maccabees-11-38]]
^38^ And king Demetrius, seeing that the land was quieted in his sight and that nothing resisted him, sent all his forces away, each one to his own place, except the foreign army, which he had drawn together from the islands of the nations. And so all the troops of his fathers were hostile to him.

[[first-maccabees-11-39]]
^39^ But there was a certain one, Trypho, who was previously on Alexander’s side. And he saw that all the army murmured against Demetrius, and so he went to Imalkue the Arab, who raised Antiochus, the son of Alexander.

[[first-maccabees-11-40]]
^40^ And he persuaded him to deliver him to him, so that he would reign in his father’s place. And he reported to him what Demetrius had done, and that his army was hostile to him. And he remained there for many days.

[[first-maccabees-11-41]]
^41^ And Jonathan sent to king Demetrius, so that he would cast out those who were in the stronghold in Jerusalem and those who were with the garrisons, because they fought against Israel.

[[first-maccabees-11-42]]
^42^ And Demetrius sent to Jonathan, saying: “I will not only do this for you and your people, but I will elevate your glory and your nation, when opportunity shall serve.

[[first-maccabees-11-43]]
^43^ Now, therefore, you will do well if you send men as auxiliaries to me. For all my army has withdrawn from me.”

[[first-maccabees-11-44]]
^44^ And Jonathan sent three thousand strong men to him at Antioch. And they came to the king, and the king was delighted at their arrival.

[[first-maccabees-11-45]]
^45^ And those who were of the city gathered together, one hundred and twenty thousand men, and they wanted to execute the king.

[[first-maccabees-11-46]]
^46^ And the king fled into the royal court. And those who were of the city, occupied the passageways of the city, and they began to fight.

[[first-maccabees-11-47]]
^47^ And the king called the Jews to his assistance. And they came together before him at the same time, and then they all dispersed themselves throughout the city.

[[first-maccabees-11-48]]
^48^ And they killed, in that day, one hundred thousand men, and they set fire to the city, and they seized many spoils in that day, and they freed the king.

[[first-maccabees-11-49]]
^49^ And those who were of the city saw that the Jews had taken the city, just as they wanted, and they were weakened in their resolve, and they cried out to the king with supplication, saying,

[[first-maccabees-11-50]]
^50^ “Grant us a pledge, and let the Jews cease from assailing us and the city.”

[[first-maccabees-11-51]]
^51^ And they threw down their arms, and they made peace. And the Jews were glorified in the sight of the king and in the sight of all who were in his realm. And they became renowned in the kingdom, and they returned to Jerusalem, holding many spoils.

[[first-maccabees-11-52]]
^52^ And so king Demetrius sat on the throne of his kingdom. And the land was quieted in his sight.

[[first-maccabees-11-53]]
^53^ And he falsified everything whatsoever that he had said. And he alienated himself from Jonathan, and he did not repay him according to the benefits that he had received in tribute from him. And he vexed him greatly.

[[first-maccabees-11-54]]
^54^ But after this, Trypho returned, and with him was Antiochus, the adolescent boy, and he reigned, and he put a diadem on himself.

[[first-maccabees-11-55]]
^55^ And there assembled before him all the troops, which Demetrius had dispersed, and they fought against him. And he turned his back and fled.

[[first-maccabees-11-56]]
^56^ And Trypho took the elephants, and he obtained Antioch.

[[first-maccabees-11-57]]
^57^ And young Antiochus wrote to Jonathan, saying: “I confirm you in the priesthood, and I appoint you over the four cities, so as to be among the king’s friends.”

[[first-maccabees-11-58]]
^58^ And he sent him vessels of gold for his ministry, and he gave him the authority to drink from gold, and to be clothed in purple, and to have a golden clasp.

[[first-maccabees-11-59]]
^59^ And he appointed his brother Simon as governor, from the borders of Tyre, all the way to the borders of Egypt.

[[first-maccabees-11-60]]
^60^ Then Jonathan went out, and he passed through the cities across the river. And all the armies of Syria were gathered together in assistance to him, and he came to Askalon, and those from the city met him honorably.

[[first-maccabees-11-61]]
^61^ And he went from there to Gaza. And those who were in Gaza closed themselves in. And so he besieged it, and he burned all that was around the city, and he plundered it.

[[first-maccabees-11-62]]
^62^ And those of Gaza petitioned Jonathan, and he pledged to them with his right hand, and he accepted their sons as hostages and sent them to Jerusalem. And he traveled through the country, as far as Damascus.

[[first-maccabees-11-63]]
^63^ And Jonathan heard that the leaders of Demetrius were acting treacherously at Kadesh, which is in Galilee, with a great army, intending to remove him from the affairs of the kingdom.

[[first-maccabees-11-64]]
^64^ And he went to meet them. But he left his brother Simon behind in the countryside.

[[first-maccabees-11-65]]
^65^ And Simon took a position against Bethzur, and he assailed it for many days, and he closed them in.

[[first-maccabees-11-66]]
^66^ And they asked him to accept a pledge, and he granted this to them. And he cast them out of there, and he seized the city, and he placed a garrison in it.

[[first-maccabees-11-67]]
^67^ And Jonathan and his camp took a position by the water of Gennesaret, and, before first light, they were standing watch in the plains of Hazor.

[[first-maccabees-11-68]]
^68^ And behold, an army of foreigners met him in the plains. And they set up an ambush against him in the mountains. But he met them from the opposite direction.

[[first-maccabees-11-69]]
^69^ Yet those lying in ambush then rose up from their places and joined them in combat.

[[first-maccabees-11-70]]
^70^ And all those who were from Jonathan’s side fled, and not one of them was left, except Mattathias, the son of Absalom, and Judas, the son of Chalphi, the leader of military training.

[[first-maccabees-11-71]]
^71^ And so Jonathan tore his garments, and he placed dirt on his head, and he prayed.

[[first-maccabees-11-72]]
^72^ And Jonathan turned back toward them in battle, and he put them to flight, and they fought.

[[first-maccabees-11-73]]
^73^ And when those from his side, who had fled, saw this, they returned to him, and with him they all pursued them, even to Kadesh, to their camp, and they even passed beyond there.

[[first-maccabees-11-74]]
^74^ And there fell from the foreigners on that day three thousand men. And Jonathan returned to Jerusalem.


[[first-maccabees-12]]
== Chapter 12

[[first-maccabees-12-1]]
^1^ And Jonathan saw that time was on his side, and he chose men, and he sent them to Rome, to confirm and renew the peace agreement with them.

[[first-maccabees-12-2]]
^2^ And he sent letters to the Spartans, and to other places, according to the same form.

[[first-maccabees-12-3]]
^3^ And they went to Rome and entered into the senate house, and they said, “Jonathan, the high priest, and the nation of the Jews, have sent us to renew the peace and alliance, as it was before.”

[[first-maccabees-12-4]]
^4^ And they gave letters to them, to those in each place, so that they would lead them into the land of Judah with peace.

[[first-maccabees-12-5]]
^5^ And this is a copy of the letters that Jonathan wrote to the Spartans:

[[first-maccabees-12-6]]
^6^ “Jonathan, the high priest, and the elders of the people, and the priests, and the rest of the people of the Jews, to the Spartans, their brothers: greetings.

[[first-maccabees-12-7]]
^7^ Now, some time ago, letters were sent to Onias, the high priest from Arius, who reigned then among you, so that you would be our brothers, just as the copy that is written below states.

[[first-maccabees-12-8]]
^8^ And Onias received the man whom you had sent with honor. And he received the letters, in which was conveyed the alliance and peace treaty.

[[first-maccabees-12-9]]
^9^ We, though, have no need of these things, having for our solace the sacred books, which are in our hands.

[[first-maccabees-12-10]]
^10^ We prefer to send to you, so as to renew the brotherhood and friendship, lest we should, in effect, become a stranger to you, for much time has passed since you sent to us.

[[first-maccabees-12-11]]
^11^ Therefore, we will remember you, at all times without ceasing, in our solemnities and other days, when it is fitting, in the sacrifices that we offer, and in our observances, just as it is fitting and right to remember brothers.

[[first-maccabees-12-12]]
^12^ And so, we rejoice at your glory.

[[first-maccabees-12-13]]
^13^ But many tribulations and many wars have surrounded us, and the kings who are around us have fought against us.

[[first-maccabees-12-14]]
^14^ But we are not willing to trouble you, nor the rest of our allies and friends, about these battles.

[[first-maccabees-12-15]]
^15^ For we have assistance from heaven, and we have been delivered, and our enemies have been humbled.

[[first-maccabees-12-16]]
^16^ And so, we have chosen Numenius, the son of Antiochus, and Antipater, the son of Jason, and we have sent them to the Romans, to renew the former peace treaty and alliance with them.

[[first-maccabees-12-17]]
^17^ And so, we have commanded them to also come to you, and to greet you, and to deliver our letters to you, about the renewal of our brotherhood.

[[first-maccabees-12-18]]
^18^ And now, you would do well to respond to us about these things.”

[[first-maccabees-12-19]]
^19^ And this is a copy of the letters that he sent to Onias:

[[first-maccabees-12-20]]
^20^ “Arius, king of the Spartans, to Onias, the great priest: greetings.

[[first-maccabees-12-21]]
^21^ It is found in scripture, about the Spartans and the Jews, that they are brothers, and that they are of the family of Abraham.

[[first-maccabees-12-22]]
^22^ And since we know these things, you would do well to write to us about your peace.

[[first-maccabees-12-23]]
^23^ But we also have written back to you that our cattle and our possessions are yours, and yours are ours. And so, we have commanded that these things should be announced to you.”

[[first-maccabees-12-24]]
^24^ And Jonathan heard that the leaders from Demetrius had returned again with a greater army than before, so as to fight against him.

[[first-maccabees-12-25]]
^25^ And so, he departed from Jerusalem, and he met them in the region of Hamath. For he did not give them time to enter into his own region.

[[first-maccabees-12-26]]
^26^ And he sent spies into their camp, and, returning, they reported that they planned to come upon them in the night.

[[first-maccabees-12-27]]
^27^ And when the sun had set, Jonathan instructed his men to stand watch, and to be in arms, ready to fight, all night long, and he stationed guards around the camp.

[[first-maccabees-12-28]]
^28^ And the adversaries heard that Jonathan was prepared, with his own, for warfare. And they were struck with fear and dread in their heart. And they kindled fires in their camp.

[[first-maccabees-12-29]]
^29^ But Jonathan, and those who were with him, did not know about it until morning. For they saw the lights burning.

[[first-maccabees-12-30]]
^30^ And Jonathan pursued them, but did not overtake them. For they had crossed the river Eleutherus.

[[first-maccabees-12-31]]
^31^ And Jonathan diverted toward the Arabians, who are called Zabadeans. And he struck them and took their spoils.

[[first-maccabees-12-32]]
^32^ And he regrouped and came to Damascus, and he passed through all that region.

[[first-maccabees-12-33]]
^33^ But Simon went forth and came as far as Askalon, and the nearby fortresses, but he turned aside to Joppa and occupied it,

[[first-maccabees-12-34]]
^34^ (for he had heard that they intended to hand over the fortress that was on the side of Demetrius) and he stationed a guard there to keep it.

[[first-maccabees-12-35]]
^35^ And Jonathan returned, and he called together the elders of the people, and he decided with them to build fortresses in Judea,

[[first-maccabees-12-36]]
^36^ and to build up the walls in Jerusalem, and to raise a great height between the stronghold and the city, in order to separate it from the city, so that it would stand alone and would have neither buying, nor selling there.

[[first-maccabees-12-37]]
^37^ And they came together to build up the city. And the wall that was over the brook, toward the rising of the sun, was fallen. And he repaired that which is called Chaphenatha.

[[first-maccabees-12-38]]
^38^ And Simon rebuilt Adida in Shephelah, and he fortified it, and he set up gates and bars.

[[first-maccabees-12-39]]
^39^ And so, when Trypho had decided to reign over Asia, and to assume the diadem, and to extend his hand against king Antiochus,

[[first-maccabees-12-40]]
^40^ he was afraid, lest Jonathan might not permit him, but might fight against him. So he sought to seize him and to kill him. And he rose up and went to Bethshan.

[[first-maccabees-12-41]]
^41^ And Jonathan went out to meet him with forty thousand men chosen for battle, and he came to Bethshan.

[[first-maccabees-12-42]]
^42^ And when Trypho saw that Jonathan came with a great army to extend his hand against him, he was afraid.

[[first-maccabees-12-43]]
^43^ And so he received him with honor, and he commended him to all his friends, and he gave him gifts. And he instructed his troops to obey him, just as himself.

[[first-maccabees-12-44]]
^44^ And he said to Jonathan: “Why have you troubled all the people, when there is no war between us?

[[first-maccabees-12-45]]
^45^ And now, send them back to their houses, but choose for yourself a few men, who may remain with you, and come with me to Ptolemais, and I will deliver it to you, and the rest of the fortresses, and the army, and all who are in charge of governing, and I will turn and go away. For this is the reason that I came.”

[[first-maccabees-12-46]]
^46^ And Jonathan believed him, and he did as he said. And he sent away his army, and they departed into the land of Judah.

[[first-maccabees-12-47]]
^47^ But he retained with him three thousand men, of whom he sent two thousand into Galilee, and one thousand came with him.

[[first-maccabees-12-48]]
^48^ But when Jonathan entered into Ptolemais, those of Ptolemais closed the gates of the city, and they captured him. And all those who entered with him, they executed with the sword.

[[first-maccabees-12-49]]
^49^ And Trypho sent an army and horsemen into Galilee, and into the great plain, to destroy all the associates of Jonathan.

[[first-maccabees-12-50]]
^50^ But, when they had thought that Jonathan had been captured and slain, along with all who were with him, they encouraged one another, and they went out prepared for battle.

[[first-maccabees-12-51]]
^51^ Then those who had pursued them, seeing that they stood for their lives, were turned back.

[[first-maccabees-12-52]]
^52^ And so, they all came into the land of Judah with peace. And they bewailed Jonathan, and those who had been with him, exceedingly. And Israel mourned with great lamentation.

[[first-maccabees-12-53]]
^53^ Then all the nations that were all around them sought to crush them. For they said:

[[first-maccabees-12-54]]
^54^ “They have no leader or helper. Now therefore, let us fight against them and take away the memory of them from among men.”


[[first-maccabees-13]]
== Chapter 13

[[first-maccabees-13-1]]
^1^ And Simon heard that Trypho had gathered together an immense army to come to the land of Judah and to lay waste to it.

[[first-maccabees-13-2]]
^2^ Seeing that the people were fearful and trembling, he went up to Jerusalem, and he gathered together the people.

[[first-maccabees-13-3]]
^3^ And exhorting them, he said: “You know what great battles I, and my brothers, and the house of my father, have fought for the laws and for the holy places, and the anguish that we have seen.

[[first-maccabees-13-4]]
^4^ As a result of these things, all my brothers have perished for the sake of Israel, and I have been left alone.

[[first-maccabees-13-5]]
^5^ And now, it is not necessary for me to spare my life in any time of tribulation. For I am not better than my brothers.

[[first-maccabees-13-6]]
^6^ And so, I will vindicate my people and the sanctuary, and likewise our children and wives. For all the Gentiles have gathered together to crush us, solely out of malice.”

[[first-maccabees-13-7]]
^7^ And the spirit of the people was immediately enkindled, when they heard these words.

[[first-maccabees-13-8]]
^8^ And they responded with a loud voice, saying: “You are our leader in place of Judas and of Jonathan, your brother.

[[first-maccabees-13-9]]
^9^ Fight our battles, and we will do whatever you tell us to do.”

[[first-maccabees-13-10]]
^10^ And so, gathering together all the men of war, he accelerated the completion of all the walls of Jerusalem, and he fortified it all around.

[[first-maccabees-13-11]]
^11^ And he sent Jonathan, the son of Absalom, and with him a new army, into Joppa, and he cast out those who were in it, and he himself remained there.

[[first-maccabees-13-12]]
^12^ And Trypho moved from Ptolemais, with a great army, to come into the land of Judah, and Jonathan was with him in custody.

[[first-maccabees-13-13]]
^13^ But Simon took up a position at Addus, opposite the face of the plains.

[[first-maccabees-13-14]]
^14^ And when Trypho realized that Simon rose up in the place of his brother, Jonathan, and that he would be joining in battle with him, he sent messengers to him,

[[first-maccabees-13-15]]
^15^ saying: “We have detained your brother, Jonathan, because of the money that he owed to the king’s account, because of the matters for which he was responsible.

[[first-maccabees-13-16]]
^16^ And now, send a hundred talents of silver, and two of his sons for hostages, so that when he is dismissed, he may not flee from us. And then we will release him.”

[[first-maccabees-13-17]]
^17^ And Simon knew that he was speaking deceitfully to him. Yet he ordered the money and the boys to be given, lest he should bring upon himself a great hostility from the people of Israel, who might have said,

[[first-maccabees-13-18]]
^18^ “It is because he did not send the money and the boys that he perished.”

[[first-maccabees-13-19]]
^19^ So he sent the boys and one hundred talents. And he was lying and did not dismiss Jonathan.

[[first-maccabees-13-20]]
^20^ And after this, Trypho came into the country, to crush it. And they circled around by the way that leads to Adora. And Simon and his camp marched into every place, wherever they went.

[[first-maccabees-13-21]]
^21^ But those who were in the stronghold sent messengers to Trypho, so that he would hurry to come through the desert, and to send them provisions.

[[first-maccabees-13-22]]
^22^ And Trypho prepared all his horsemen to arrive on that night. But there was a very great snowfall, and he did not come into Gilead.

[[first-maccabees-13-23]]
^23^ And when he approached toward Baskama, he killed Jonathan and his sons there.

[[first-maccabees-13-24]]
^24^ And Trypho turned back and went into his own land.

[[first-maccabees-13-25]]
^25^ And Simon sent and took the bones of Jonathan, his brother, and he buried them in Modin, the city of his fathers.

[[first-maccabees-13-26]]
^26^ And all Israel bewailed him with great lamentation. And they mourned him for many days.

[[first-maccabees-13-27]]
^27^ And Simon built, over the sepulcher of his father and of his brothers, a building, lofty to see, of polished stone, front and back.

[[first-maccabees-13-28]]
^28^ And he set up seven pyramids, one against another, for his father, and his mother, and his four brothers.

[[first-maccabees-13-29]]
^29^ And around these he placed great columns; and upon the columns, weapons, as a continual memorial; and beside the weapons, carvings of ships, which might be seen by all those who sail the sea.

[[first-maccabees-13-30]]
^30^ This is the sepulcher that he made in Modin, even to this day.

[[first-maccabees-13-31]]
^31^ But Trypho, when he was on a journey with the young king, Antiochus, killed him by deceit.

[[first-maccabees-13-32]]
^32^ And he reigned in his place, and he put on the diadem of Asia, and he caused great scourges upon the land.

[[first-maccabees-13-33]]
^33^ And Simon built up the strongholds of Judea, fortifying them with high towers, and great walls, and gates and bars. And he placed provisions in the fortresses.

[[first-maccabees-13-34]]
^34^ And Simon chose men, and he sent to king Demetrius, so that he would grant a remission to the region, for all that Trypho did was to carry out plundering.

[[first-maccabees-13-35]]
^35^ And king Demetrius responded to this word, and he wrote a letter in this manner:

[[first-maccabees-13-36]]
^36^ “King Demetrius to Simon, the high priest and friend of kings, and to the elders, and to the people of the Jews: greetings.

[[first-maccabees-13-37]]
^37^ The golden crown and the bahem that you sent, we have received. And we are prepared to make a great peace with you, and to write to the officers of the king to remit to you the things that we have released.

[[first-maccabees-13-38]]
^38^ For whatever we have established remains in force for you. The strongholds that you have built, let them be yours.

[[first-maccabees-13-39]]
^39^ Likewise, any oversight or fault, even to this day, we forgive it, along with the crown that you owed. And if anything else was taxed in Jerusalem, now let it not be taxed.

[[first-maccabees-13-40]]
^40^ And if any of you is fit to be enrolled among our own, let them be enrolled. And let there be peace between us.”

[[first-maccabees-13-41]]
^41^ In the one hundred and seventieth year, the yoke of the Gentiles was taken away from Israel.

[[first-maccabees-13-42]]
^42^ And the people of Israel began to write in the tablets and the public records, in the first year under Simon: high priest, great commander, and leader of the Jews.

[[first-maccabees-13-43]]
^43^ In those days, Simon took up a position at Gaza, and he encamped around it, and he made machines of war, and he applied them to the city, and he struck one tower and captured it.

[[first-maccabees-13-44]]
^44^ And those who were within the machine broke forth into the city. And a great commotion occurred in the city.

[[first-maccabees-13-45]]
^45^ And those who were in the city ascended upon the wall, with their wives and children, having torn their tunics. And they cried out with a loud voice, asking Simon to grant them a pledge.

[[first-maccabees-13-46]]
^46^ And they said, “Do not repay us according to our malice, but according to your mercy.”

[[first-maccabees-13-47]]
^47^ And weeping, Simon did not destroy them. Yet he cast them out of the city, and he cleansed the buildings, in which there had been idols. And then he entered into it with hymns, blessing the Lord.

[[first-maccabees-13-48]]
^48^ And, having cast out of it all uncleanness, he placed in it men who would observe the law. And he fortified it and made it his dwelling place.

[[first-maccabees-13-49]]
^49^ But those who were in the stronghold of Jerusalem were prohibited from going out and entering the region, and from buying and selling. And they were very hungry, and many of them perished through famine.

[[first-maccabees-13-50]]
^50^ And they cried out to Simon, that they might receive a pledge, and he granted it to them. And he cast them out of there, and he cleansed the stronghold from contaminations.

[[first-maccabees-13-51]]
^51^ And they entered into it on the twenty-third day of the second month, in the one hundred and seventy-first year, with thanksgiving, and palm branches, and lyres, and cymbals, and psalteries, and hymns, and canticles, because a great enemy had been crushed out of Israel.

[[first-maccabees-13-52]]
^52^ And he established that these days should be kept every year with rejoicing.

[[first-maccabees-13-53]]
^53^ And he fortified the mountain of the temple, which was near the stronghold, and he lived there himself, along with those who were with him.

[[first-maccabees-13-54]]
^54^ And Simon saw that John, his son, was a valiant man in battle. And so he appointed him as commander of all the forces. And he lived in Gazara.


[[first-maccabees-14]]
== Chapter 14

[[first-maccabees-14-1]]
^1^ In the one hundred and seventy-second year, king Demetrius gathered together his army, and he went into Media to obtain auxiliaries to fight against Trypho.

[[first-maccabees-14-2]]
^2^ And Arsaces, the king of Persia and Media, heard that Demetrius entered his confines, and so he sent one of his princes to capture him alive and to bring him to him.

[[first-maccabees-14-3]]
^3^ And he went out and struck the camp of Demetrius. And captured him and brought him to Arsaces, and he placed him under guard.

[[first-maccabees-14-4]]
^4^ And the entire land of Judah was quiet during all the days of Simon, and he sought what was good for his people. And his power and his glory pleased them through all his days.

[[first-maccabees-14-5]]
^5^ And, with all his glory, he accepted Joppa as a port, and he made it an entrance to the islands of the sea.

[[first-maccabees-14-6]]
^6^ And he enlarged the boundaries of his nation, and he controlled the countryside.

[[first-maccabees-14-7]]
^7^ And he gathered together many captives, and he was the ruler of Gazara and Bethzur, and the stronghold. And he took uncleanness away from it, and there was no one who could withstand him.

[[first-maccabees-14-8]]
^8^ And each one cultivated his land in peace, and the land of Judah produced its fruits, and the trees of the fields their fruit.

[[first-maccabees-14-9]]
^9^ All the elders sat in the streets, and they discussed what was good for the country, and the youths clothed themselves in glory and in the robes of war.

[[first-maccabees-14-10]]
^10^ And he gave tributes of provisions to the cities, and he decreed that they would have equipment for fortification, so that the fame of his glory was renowned, even to the ends of the earth.

[[first-maccabees-14-11]]
^11^ He caused there to be peace over the land, and Israel was rejoicing with great joy.

[[first-maccabees-14-12]]
^12^ And each one sat under his vine and under his fig tree. And there was no one who would terrify them.

[[first-maccabees-14-13]]
^13^ There was nothing left of those who might fight against them in the land; kings had been crushed in those days.

[[first-maccabees-14-14]]
^14^ And he confirmed all the humble of his people, and he sought the law, and he took away every iniquity and evil.

[[first-maccabees-14-15]]
^15^ He glorified the sanctuary, and he multiplied the vessels of the holy places.

[[first-maccabees-14-16]]
^16^ And it was heard at Rome, and even in Sparta, that Jonathan had passed away. And they were very sorrowful.

[[first-maccabees-14-17]]
^17^ But when they heard that Simon, his brother, had been made high priest in his place, and that he obtained the entire country and the cities in it,

[[first-maccabees-14-18]]
^18^ they wrote to him on tablets of brass, so as to renew the friendship and alliance, which they had made with Judas and with Jonathan, his brothers.

[[first-maccabees-14-19]]
^19^ And they were read in the sight of the assembly at Jerusalem. And this is a copy of the letters that the Spartans sent:

[[first-maccabees-14-20]]
^20^ “The leaders and the cities of the Spartans, to Simon, the great priest, and to the elders, and the priests, and the rest of the people of the Jews, their brothers: greetings.

[[first-maccabees-14-21]]
^21^ The ambassadors who were sent to our people have reported to us of your glory, and honor, and rejoicing. And we were glad at their arrival.

[[first-maccabees-14-22]]
^22^ And we wrote down what was said by them in the councils of the people, as follows: ‘Numenius, the son of Antiochus, and Antipater, the son of Jason, ambassadors of the Jews, came to us to renew the former friendship with us.

[[first-maccabees-14-23]]
^23^ And it pleased the people to receive the men gloriously, and to place a copy of their words in a section of the public books, so as to be a memorial for the people of the Spartans. Furthermore, we have written a copy of them to Simon, the great priest.’ ”

[[first-maccabees-14-24]]
^24^ But after this, Simon sent Numenius to Rome, in possession of a great shield of gold, weighing over a thousand pounds, to confirm the association with them.

[[first-maccabees-14-25]]
^25^ But when the people of Rome had heard these words, they said: “With what deeds of thanksgiving shall we repay Simon and his sons?

[[first-maccabees-14-26]]
^26^ For he has vindicated his brothers, and he has fought off the enemies of Israel from them.” And so, they decreed him free, and they registered it on tablets of brass and placed it in an inscription on mount Zion.

[[first-maccabees-14-27]]
^27^ And this is a copy of the writing: “On the eighteenth day of the month Elul, in the one hundred and seventy-second year, the third year under Simon, the great priest at Asaramel,

[[first-maccabees-14-28]]
^28^ in a great convocation of the priests, and the people, and the leaders of the nation, and the elders of the country, these things were noted: ‘Now there have often been battles in our country.

[[first-maccabees-14-29]]
^29^ And Simon, the son of Mattathias, of the sons of Jarib, and his brothers, have put themselves in danger, and have withstood the enemies of their nation, so as to establish their holy places and the law. And they have glorified their people with great glory.

[[first-maccabees-14-30]]
^30^ And Jonathan gathered together his nation, and he was made their great priest, and he was laid to rest among his people.

[[first-maccabees-14-31]]
^31^ And their enemies wanted to trample and lay waste to their country, and to extend their hands against their holy places.

[[first-maccabees-14-32]]
^32^ Then Simon resisted, and he fought for his nation, and he requested much money, and he armed the valiant men of his nation and gave them wages.

[[first-maccabees-14-33]]
^33^ And he fortified the cities of Judea and Bethzur, which are along the borders of Judea, where the weaponry of the enemies was before. And he placed a garrison of Jewish men there.

[[first-maccabees-14-34]]
^34^ And he fortified Joppa, which is by the sea, and Gazara, which is on the border of Azotus, where the enemies stayed before, and he placed Jews there. And he positioned with them whatever was fitting for their preparations.

[[first-maccabees-14-35]]
^35^ And the people saw the acts of Simon, and the glory that he intended to bring to his nation, and they made him their commander and first priest, because he had done all these things, and because of the justice and faith that he maintained for his nation, and because he sought to exalt his people by all means.

[[first-maccabees-14-36]]
^36^ And in his days, there was prosperity by his hands, so that the Gentiles were taken away from their country, and also those who were in the city of David, in Jerusalem, in the stronghold, from which they went out and contaminated all the places that were around the sanctuary, and from which they brought a great scourging against chastity.

[[first-maccabees-14-37]]
^37^ And he placed in it Jewish men, as a means of protection for the region and the city, and he raised the walls of Jerusalem.

[[first-maccabees-14-38]]
^38^ And king Demetrius confirmed him in the high priesthood.

[[first-maccabees-14-39]]
^39^ According to these things, he made him his friend, and he glorified him with great glory.

[[first-maccabees-14-40]]
^40^ For he heard that the Romans had called the Jews their friends, and associates, and brothers, and that they received the ambassadors of Simon with glory,

[[first-maccabees-14-41]]
^41^ and that the Jews and their priests had consented that he should be their governor and high priest unceasingly, until there should arise a faithful prophet,

[[first-maccabees-14-42]]
^42^ and that he should be the commander over them, and that he should take care of the sanctuary, and that he should appoint foremen over their works, and over the country, and over the weapons, and over the strongholds,

[[first-maccabees-14-43]]
^43^ and that he should take care of the holy places, and that he should be obeyed by all, and that all the records in the country should be recorded in his name, and that he should be clothed in purple and gold,

[[first-maccabees-14-44]]
^44^ and that it should not be lawful for any of the people or the priests to make void any of these things, nor to contradict things that are said by him, nor to call together an assembly in the country without him, nor to be clothed in purple, nor to use a clasp of gold.

[[first-maccabees-14-45]]
^45^ And whoever will do otherwise, or who will make void any of these things, shall be guilty.

[[first-maccabees-14-46]]
^46^ And it pleased all the people to appoint Simon, and to act according to these words.

[[first-maccabees-14-47]]
^47^ And Simon accepted it, and he was pleased to perform the office of the high priesthood, and to be the commander and leader of the people of the Jews, and of the priests, and to be foremost over them all.

[[first-maccabees-14-48]]
^48^ And they asked that this writing be placed on tablets of brass, and be placed within the precinct of the sanctuary in a celebrated place,

[[first-maccabees-14-49]]
^49^ and that a copy of these be placed in the treasury, so that Simon and his sons may have it.’ “


[[first-maccabees-15]]
== Chapter 15

[[first-maccabees-15-1]]
^1^ And king Antiochus, the son of Demetrius, sent letters from the islands of the sea to Simon, the priest and leader of the nation of the Jews, and to all the people.

[[first-maccabees-15-2]]
^2^ And these continued in this way: “King Antiochus to Simon, the great priest, and to the people of the Jews: greetings.

[[first-maccabees-15-3]]
^3^ Since certain pestilent persons have obtained the kingdom of our fathers, it is my will, then, to vindicate the kingdom and to restore it, just as it was before. And so, I have chosen a great army, and I have built ships of war.

[[first-maccabees-15-4]]
^4^ Furthermore, I intend to pass through the region, so that I may take revenge on those who have corrupted our country and who have desolated many cities in my kingdom.

[[first-maccabees-15-5]]
^5^ Now, therefore, I confirm to you all the oblations that all the kings before me have remitted to you, and whatever other gifts they remitted to you.

[[first-maccabees-15-6]]
^6^ And I permit you to make a striking of your own coins for your country.

[[first-maccabees-15-7]]
^7^ Moreover, let Jerusalem be holy and free. And all the weapons that have been made, and the fortresses that you have constructed, or that you hold, let them remain with you.

[[first-maccabees-15-8]]
^8^ And all that is owed to the king, and what should belong to the king in the future, from this time and for all time, is remitted to you.

[[first-maccabees-15-9]]
^9^ Yet, when we have obtained our kingdom, we will glorify you, and your nation, and the temple with great glory, so much so that your glory shall be made manifest in all the earth.”

[[first-maccabees-15-10]]
^10^ In the one hundred and seventy-fourth year, Antiochus went into the land of his fathers, and all the armies came over to him, so that few were left with Trypho.

[[first-maccabees-15-11]]
^11^ And king Antiochus followed him as he fled along the sea coast and came to Dora.

[[first-maccabees-15-12]]
^12^ For he knew that evils had gathered together upon him, and that his troops had forsaken him.

[[first-maccabees-15-13]]
^13^ And Antiochus took up a position above Dora, with one hundred and twenty thousand men of warfare and eight thousand horsemen.

[[first-maccabees-15-14]]
^14^ And he encircled the city, and the ships drew near by sea. And they assailed the city by land and by sea, and they permitted no one to go in or out.

[[first-maccabees-15-15]]
^15^ But Numenius, and those who had been with him, came from the city of Rome, having letters written to the kings and the regions, in which was contained these things:

[[first-maccabees-15-16]]
^16^ “Lucius, consul of the Romans, to king Ptolemy: greetings.

[[first-maccabees-15-17]]
^17^ The ambassadors of the Jews, our friends, came to us, to renew the former friendship and alliance, having been sent from Simon, the leader of the priests and the people of the Jews.

[[first-maccabees-15-18]]
^18^ And they also brought a shield of gold of over a thousand pounds.

[[first-maccabees-15-19]]
^19^ And so, it was pleasing to us to write to the kings and the regions, that they should do no harm to them, nor fight against them, and their cities, and their regions, and that they should bear no assistance to those fighting against them.

[[first-maccabees-15-20]]
^20^ And it seemed good to us to receive the shield from them.

[[first-maccabees-15-21]]
^21^ If, therefore, those who are pestilent have taken refuge with you from their region, hand them over to Simon, the leader of the priests, so that he may give a verdict to them according to their law.”

[[first-maccabees-15-22]]
^22^ These same things were written to king Demetrius, and to Attalus, and to Ariarathes, and to Arsaces,

[[first-maccabees-15-23]]
^23^ and to all the regions, and to Lampsacus and to the Spartans, and to Delos, and Myndos, and Sicyon, and Caria, and Samos, and Pamphylia, and Lycia, and Halicarnassus, and Cos, and Side, and Aradus, and Rhodes, and Phaselis, and Gortyna, and Gnidus, and Cyprus, and Cyrene.

[[first-maccabees-15-24]]
^24^ Moreover, they wrote a copy of these things to Simon, the leader of the priests and the people of the Jews.

[[first-maccabees-15-25]]
^25^ But king Antiochus positioned his camp near Dora a second time, moving his hand against it continually, and making machines of war. And he enclosed Trypho, lest he escape.

[[first-maccabees-15-26]]
^26^ And Simon sent two thousand chosen men to him as auxiliaries, and silver, and gold, and an abundance of equipment.

[[first-maccabees-15-27]]
^27^ And he was not willing to receive them, but he broke all of the pact that he made with him before, and he alienated himself from him.

[[first-maccabees-15-28]]
^28^ And he sent to him Athenobius, one of his friends, to deal with him, saying: “You hold Joppa and Gazara, and the stronghold that is in Jerusalem, which are cities of my kingdom.

[[first-maccabees-15-29]]
^29^ You have desolated their parts, and you have caused a great scourging in the land, and you have become ruler throughout many places in my kingdom.

[[first-maccabees-15-30]]
^30^ Now, therefore, hand over the cities that you occupy, and the tributes of the places where you have become ruler beyond the borders of Judea.

[[first-maccabees-15-31]]
^31^ But if not, give me for them five hundred talents of silver, and for the destruction that you have caused, and for the tributes of the cities, another five hundred talents. But if not, we will come and fight against you.”

[[first-maccabees-15-32]]
^32^ So Athenobius, the friend of the king, came to Jerusalem and saw the glory of Simon, and his splendor in gold and silver, and his abundance of equipment, and he was astonished. And he repeated the words of the king to him.

[[first-maccabees-15-33]]
^33^ And Simon responded to him, and he said to him: “We have not taken foreign land, nor do we hold anything foreign, but we hold the inheritance of our fathers, which was for some time unjustly possessed by our enemies.

[[first-maccabees-15-34]]
^34^ In truth, since we have the opportunity, we claim the inheritance of our fathers.

[[first-maccabees-15-35]]
^35^ And as to Joppa and Gazara, which you demand, they brought a great scourging on the people and our country. For these, we will give one hundred talents.” And Athenobius did not respond a word to him.

[[first-maccabees-15-36]]
^36^ But, returning with anger to the king, he reported to him these words, and the glory of Simon, and all that he had seen. And the king became angry with a great anger.

[[first-maccabees-15-37]]
^37^ But Trypho fled by ship to Orthosia.

[[first-maccabees-15-38]]
^38^ And the king appointed Cendebeus as commander of the seacoast, and he gave him an army of foot soldiers and horsemen.

[[first-maccabees-15-39]]
^39^ And he commanded him to move with his camp against the face of Judea. And he commanded him to build up Kedron, and to barricade the gates of the city, and to make war against the people. But the king pursued Trypho.

[[first-maccabees-15-40]]
^40^ And Cendebeus passed through to Jamnia, and he began to provoke the populace, and to trample Judea, and to take the people captive, and to execute, and to build up Kedron.

[[first-maccabees-15-41]]
^41^ And he stationed horsemen and an army there, so that they could go out and travel through the ways of Judea, as the king appointed him to do.


[[first-maccabees-16]]
== Chapter 16

[[first-maccabees-16-1]]
^1^ And so, John came up from Gazara, and he reported to Simon, his father, what Cendebeus had done against their people.

[[first-maccabees-16-2]]
^2^ And Simon called his two eldest sons, Judas and John, and he said to them: “I and my brothers, and my father’s house, have fought against the enemies of Israel from our youth, even to this day. And this work has prospered in our hands, so that we have delivered Israel several times.

[[first-maccabees-16-3]]
^3^ And now that I am old, you must act in place of me and my brothers, and go out to fight for our nation. Truly, may the help of heaven be with you.”

[[first-maccabees-16-4]]
^4^ Then he chose from the region twenty thousand men of warfare, and horsemen; and they started out toward Cendebeus. And they rested in Modin.

[[first-maccabees-16-5]]
^5^ And they rose up in the morning and went out into the plains. And behold, an abundant army of foot soldiers and horsemen was there to meet them, and there was a river flowing between them.

[[first-maccabees-16-6]]
^6^ And he and his people moved their camp opposite their face, and he saw the trepidation of the people to cross over the river, and so he crossed over first. And seeing him, the men also crossed after him.

[[first-maccabees-16-7]]
^7^ And he divided the people and the horsemen into the midst of the foot soldiers. But the horsemen of the adversary were exceedingly numerous.

[[first-maccabees-16-8]]
^8^ And they sounded the holy trumpets. And Cendebeus and his army were turned back. And many of them fell wounded. But the rest fled into the fortress.

[[first-maccabees-16-9]]
^9^ Then Judas, the brother of John, was wounded. But John pursued them, until he came to Kedron, which he had built.

[[first-maccabees-16-10]]
^10^ And they fled all the way to the towers that were in the fields of Azotus, and he burnt them with fire. And there fell of them two thousand men, and he returned to Judea in peace.

[[first-maccabees-16-11]]
^11^ Now Ptolemy, the son of Abubus, was appointed commander over the plain of Jericho, and he held much silver and gold.

[[first-maccabees-16-12]]
^12^ For he was the son-in-law of the high priest.

[[first-maccabees-16-13]]
^13^ And his heart was exalted, and he wanted to obtain the region, and he devised treachery against Simon and his sons, so as to destroy them.

[[first-maccabees-16-14]]
^14^ Now when Simon was traveling through the cities that were in the region of Judea, and acting with concern for them, he went down to Jericho, he and Mattathias and Judas, his sons, in the one hundred and seventy-seventh year, in the eleventh month; this is the month of Shevat.

[[first-maccabees-16-15]]
^15^ And the son of Abubus received them, with deceitfulness, into a little fortress, which is called Dok, that he had built. And he made them a great feast, and he hid men there.

[[first-maccabees-16-16]]
^16^ And when Simon and his sons became inebriated, Ptolemy and his men rose up, and took their weapons, and entered into the gathering. And they killed him, and his two sons, and some of his servants.

[[first-maccabees-16-17]]
^17^ And he committed a great treachery in Israel, and he repaid good with evil.

[[first-maccabees-16-18]]
^18^ And Ptolemy wrote about these things, and he sent to the king, so that he would send him an army to assist him, and he could deliver to him the region, and their cities and tributes.

[[first-maccabees-16-19]]
^19^ And he sent others to Gazara to destroy John. And he sent letters to the tribunes to come to him, and he would give them silver, and gold, and gifts.

[[first-maccabees-16-20]]
^20^ And he sent others to occupy Jerusalem and the mountain of the temple.

[[first-maccabees-16-21]]
^21^ Now a certain one, running ahead, reported to John in Gazara, that his father and his brothers perished, and that “he sent to kill you also.”

[[first-maccabees-16-22]]
^22^ But when he heard it, he was very afraid, and he apprehended the men who came to destroy him, and he killed them. For he knew that they sought to destroy him.

[[first-maccabees-16-23]]
^23^ And the rest of the stories about John, and his wars, and the virtuous deeds that he performed with fortitude, and the building of the walls that he raised, and the things that he did,

[[first-maccabees-16-24]]
^24^ behold, these have been written in the book of the days of his priesthood, from the time that he became high priest, after his father.
