[[job]]
= Job

[[job-1]]
== Chapter 1

[[job-1-1]]
^1^ There was a man in the land of Uz named Job, and he was a simple and honest man, fearing God and withdrawing from evil.

[[job-1-2]]
^2^ And there had been born to him seven sons and three daughters.

[[job-1-3]]
^3^ And his possession was seven thousand sheep, and three thousand camels, along with five hundred pairs of oxen and five hundred she-donkeys, and also a very large family. And this man was great among all the people of the east.

[[job-1-4]]
^4^ And his sons went and made a feast by houses, each one on his day. And sending, they called their three sisters to eat and drink with them.

[[job-1-5]]
^5^ And when the days of their feasting had been completed, Job sent to them and sanctified them, and, getting up at dawn, he offered holocausts for each one. For he said, “Perhaps my sons have sinned and have not praised God in their hearts.” So Job did all the days.

[[job-1-6]]
^6^ But on a certain day, when the sons of God came to attend in the presence of the Lord, Satan also arrived among them.

[[job-1-7]]
^7^ The Lord said to him, “Where do you come from?” Answering, he said, “I have circled the land, and walked around in it.”

[[job-1-8]]
^8^ And the Lord said to him, “Have you not considered my servant, Job? For there is no one like him in the land, a simple and honest man, fearing God and withdrawing from evil.”

[[job-1-9]]
^9^ Answering him, Satan said, “Does Job fear God to no purpose?

[[job-1-10]]
^10^ Have you not fortified him, as well as his house and every one of his belongings around him, blessed the works of his hands, and his possession has increased in the land?

[[job-1-11]]
^11^ But extend your hand a little, and touch all that he possesses, and see if he still praises you to your face.”

[[job-1-12]]
^12^ Therefore, the Lord said to Satan, “Behold, everything that he has is in your hand, only do not extend your hand against him.” And Satan departed from the face of the Lord.

[[job-1-13]]
^13^ So, on a certain day, when his sons and daughters were eating and drinking wine, in the house of their first-born brother,

[[job-1-14]]
^14^ a messenger came to Job, who said, “The oxen were plowing, and the donkeys were grazing beside them,

[[job-1-15]]
^15^ and the Sabeans rushed in and carried away everything, and they struck the servants with the sword; and I alone evaded them to tell you.”

[[job-1-16]]
^16^ And while he was still speaking, another arrived, and he said, “The fire of God fell from heaven, and, having struck the sheep and the servants, it consumed them; and I alone escaped to tell you.”

[[job-1-17]]
^17^ And while he also was still speaking, another arrived, and he said, “The Chaldeans organized three attacks, and advanced on the camels and took them; and not only that, but they have struck the servants with the sword; and I alone fled to tell you.”

[[job-1-18]]
^18^ He was still speaking, and behold, another entered, and he said, “Your sons and daughters were feasting and drinking wine in the house of their first-born brother,

[[job-1-19]]
^19^ when suddenly a severe wind rushed forth from a region of the desert and shook the four corners of the house, which collapsed and crushed your children, and they are dead; and I alone escaped to tell you.”

[[job-1-20]]
^20^ Then Job got up and tore his garments, and, having shaved his head, he collapsed on the ground, and worshipped,

[[job-1-21]]
^21^ and he said, “Naked I departed from my mother’s womb, and naked I shall return. The Lord gave, and the Lord has taken away. Just as it pleased the Lord, so has it been done. Blessed be the name of the Lord.”

[[job-1-22]]
^22^ In all this, Job did not sin by his lips, nor did he speak any foolish thing against God.


[[job-2]]
== Chapter 2

[[job-2-1]]
^1^ But it happened that, on a certain day, when the sons of God had arrived and they stood before the Lord, Satan likewise arrived among them, and he stood in his sight.

[[job-2-2]]
^2^ So the Lord said to Satan, “Where do you come from?” Answering, he said, “I have circled the land, and walked around in it.”

[[job-2-3]]
^3^ And the Lord said to Satan, “Have you not considered my servant, Job, that there is no one like him in the land, a simple and honest man, fearing God and withdrawing from evil, and still retaining his innocence? Yet you have stirred me against him, so that I would afflict him to no purpose.”

[[job-2-4]]
^4^ Answering him, Satan said, “Skin for skin; and everything that a man has, he will give for his life.

[[job-2-5]]
^5^ Yet send your hand and touch his bone and his flesh, and then you will see whether or not he blesses you to your face.”

[[job-2-6]]
^6^ Therefore, the Lord said to Satan, “Behold, he is in your hand, but even so, spare his life.”

[[job-2-7]]
^7^ And so, Satan departed from the face of the Lord and he struck Job with a very serious ulcer from the sole of the foot all the way to the crown of his head.

[[job-2-8]]
^8^ So he took a shard of earthenware and scraped the discharge, while sitting on a heap of refuse.

[[job-2-9]]
^9^ But his wife said to him, “Do you still continue in your simplicity? Bless God and die.”

[[job-2-10]]
^10^ He said to her, “You have spoken like one of the foolish wives. If we accepted good things from the hand of God, why should we not accept bad things?” In all this, Job did not sin with his lips.

[[job-2-11]]
^11^ And so, three friends of Job, hearing about all the evil that had befallen him, arrived, each one from his own place, Eliphaz the Themanite, and Baldad the Suhite, and Zophar the Naamathite. For they had agreed to come together to visit and console him.

[[job-2-12]]
^12^ And when they had raised up their eyes from a distance, they did not recognize him, and, crying out, they wept, and, tearing their garments, they scattered dust over their heads into the sky.

[[job-2-13]]
^13^ And they sat with him on the ground for seven days and seven nights, and no one spoke a word to him, for they saw that his sorrow was very great.


[[job-3]]
== Chapter 3

[[job-3-1]]
^1^ After this, Job opened his mouth and cursed his day,

[[job-3-2]]
^2^ and this is what he said:

[[job-3-3]]
^3^ May the day perish on which I was born, and the night, in which it was said, “A man has been conceived.”

[[job-3-4]]
^4^ May that day be turned into darkness, may God not seek it from above, and may light not illuminate it.

[[job-3-5]]
^5^ Let darkness and the shadow of death obscure it, let a fog overtake it, and let it be enveloped in bitterness.

[[job-3-6]]
^6^ Let a whirlwind of darkness take hold of that night, let it not be counted in the days of the year, nor numbered in the months.

[[job-3-7]]
^7^ May that night be alone and unworthy of praise.

[[job-3-8]]
^8^ May they curse it, who curse the day, who are prepared to awaken a leviathan.

[[job-3-9]]
^9^ Let the stars be concealed with its darkness. Let it expect light, and not see it, nor the rising of the dawn in the East.

[[job-3-10]]
^10^ For it did not close the doors of the womb that bore me, nor take away evils from my eyes.

[[job-3-11]]
^11^ Why did I not die in the womb? Having left the womb, why did I not immediately perish?

[[job-3-12]]
^12^ Why was I received upon the knees? Why was I suckled at the breasts?

[[job-3-13]]
^13^ For by now, I should have been sleeping silently, and taking rest in my sleep

[[job-3-14]]
^14^ with the kings and consuls of the earth, who build themselves solitudes,

[[job-3-15]]
^15^ either with princes, who possess gold and fill their houses with silver,

[[job-3-16]]
^16^ or, like a hidden miscarriage, I should not have continued, just like those who, being conceived, have not seen the light.

[[job-3-17]]
^17^ There the impious cease from rebellion, and there the wearied in strength take rest.

[[job-3-18]]
^18^ And at such times, having been bound together without difficulty, they have not heard the voice of the bailiff.

[[job-3-19]]
^19^ The small and great are there, and the servant is free from his master.

[[job-3-20]]
^20^ Why is light given to the miserable, and life to those who are in bitterness of soul,

[[job-3-21]]
^21^ who expect death, and it does not arrive, like those who dig for treasure

[[job-3-22]]
^22^ and who rejoice greatly when they have found the grave,

[[job-3-23]]
^23^ to a man whose way is hidden and whom God has surrounded with darkness?

[[job-3-24]]
^24^ Before I eat, I sigh; and like overflowing waters, so is my howl,

[[job-3-25]]
^25^ for the terror that I feared has happened to me, and so has the dread befallen me.

[[job-3-26]]
^26^ Have I not remained hidden? Have I not kept silence? Have I not remained calm? Yet indignation has overcome me.


[[job-4]]
== Chapter 4

[[job-4-1]]
^1^ But Eliphaz the Themanite, answering, said:

[[job-4-2]]
^2^ If we start to speak to you, perhaps you will take it badly, but who can hold back the words he has conceived?

[[job-4-3]]
^3^ Behold, you have taught many, and you have strengthened weary hands.

[[job-4-4]]
^4^ Your words have reassured the wavering, and you have fortified the trembling knees.

[[job-4-5]]
^5^ But now the scourge has overcome you, and you falter. It has touched you, and you are disturbed.

[[job-4-6]]
^6^ Where is your reverence, your fortitude, your patience, and the perfection of your ways?

[[job-4-7]]
^7^ Consider this, I beg you: who ever perished being innocent? Or when have the righteous been destroyed?

[[job-4-8]]
^8^ In fact, I have instead seen those who work iniquity and who sow resentments, reap them,

[[job-4-9]]
^9^ perishing by the breath of God, and being consumed by the wrath of his spirit.

[[job-4-10]]
^10^ The roaring of the lion, and the voice of the lioness, and the teeth of young lions have been worn away.

[[job-4-11]]
^11^ The tiger has perished because it does not have prey, and the young lions have been scattered.

[[job-4-12]]
^12^ Furthermore, a word was spoken to me in secret, and, as if by theft, my ears received the pulse of its whisper.

[[job-4-13]]
^13^ In the horror of a vision by night, when men are accustomed to be overtaken by a deep sleep,

[[job-4-14]]
^14^ fear and trembling seized me and all my bones were terrified.

[[job-4-15]]
^15^ And when a spirit passed before me, the hair on my body stood up.

[[job-4-16]]
^16^ There appeared an image before my eyes, someone whose face I did not recognize, and I heard a voice like a gentle breeze.

[[job-4-17]]
^17^ Should man be justified in relation to God, or will a man be more pure than his Maker?

[[job-4-18]]
^18^ Behold, those who serve him are not steadfast, and in his angels he finds imperfection.

[[job-4-19]]
^19^ How much more will those who live in houses of clay, which have an earthly foundation, be consumed like the moth?

[[job-4-20]]
^20^ From morning all the way to evening, they will be cut down, and because no one understands, they will be destroyed without ceasing.

[[job-4-21]]
^21^ But those who are left behind will be taken away from them; they will die, and not in wisdom.


[[job-5]]
== Chapter 5

[[job-5-1]]
^1^ Therefore call, if there are any who will respond to you, and turn to one or another of the saints.

[[job-5-2]]
^2^ Truly, anger condemns the foolish to death, and envy kills the petty.

[[job-5-3]]
^3^ I have seen a fool with a strong root, and I have cursed his excellence without hesitation.

[[job-5-4]]
^4^ His sons will be far from prosperity and will be crushed at the gate, and there will be none who can rescue them.

[[job-5-5]]
^5^ Their harvest, the starving will eat. The armed man will rob him, and the thirsty will drink his resources.

[[job-5-6]]
^6^ Nothing on earth occurs without a reason, and sorrow does not rise from the earth.

[[job-5-7]]
^7^ Man is born to labor, and the bird to fly.

[[job-5-8]]
^8^ Therefore, because of this, I will beg the Lord, and place my eloquence before God.

[[job-5-9]]
^9^ He does great and unfathomable and miraculous things without number.

[[job-5-10]]
^10^ He gives rain over the face of the earth and irrigates all things with the waters.

[[job-5-11]]
^11^ He places the humble on high and encourages the grieving towards health.

[[job-5-12]]
^12^ He dispels the thoughts of the spiteful, lest their hands be able to complete what they had begun.

[[job-5-13]]
^13^ He catches the wise in their cleverness and dissipates the counsel of the perverse.

[[job-5-14]]
^14^ They will encounter darkness in the daytime, and they will grope at midday just as in the night.

[[job-5-15]]
^15^ Thereafter, he will act to save the needy from the sword of their mouth, and the poor from the hand of the violent.

[[job-5-16]]
^16^ And there will be hope for those in need, for iniquity will diminish its speech.

[[job-5-17]]
^17^ Blessed is the man whom God corrects; therefore, do not reject the chastisement of the Lord.

[[job-5-18]]
^18^ For he wounds and he cures; he strikes and his hands will heal.

[[job-5-19]]
^19^ He will deliver you into six tribulations, and in the seventh, evil will not touch you.

[[job-5-20]]
^20^ During famine, he will rescue you from death, and during war, from the hand of the sword.

[[job-5-21]]
^21^ You will be hidden from the scourge of the tongue, and you will not fear calamity when it arrives.

[[job-5-22]]
^22^ In desolation and in famine, you will laugh, and you will not dread the beasts of the earth.

[[job-5-23]]
^23^ For you are in harmony with the stones of the land, and the beasts of the earth will make peace with you.

[[job-5-24]]
^24^ And you will know that your home has peace, and, concerning your appearance, you will not sin.

[[job-5-25]]
^25^ Likewise, you will know that your offspring will be manifold and your progeny will be like the grass of the earth.

[[job-5-26]]
^26^ You will enter the grave with abundance, just as a crop of wheat is gathered in its time.

[[job-5-27]]
^27^ Behold, this is just as we have found it, which you have heard; walk it through your mind.


[[job-6]]
== Chapter 6

[[job-6-1]]
^1^ But Job, responding, said:

[[job-6-2]]
^2^ I wish that my sins, for which I deserve wrath, and the calamity that I endure, were weighed out on a balance.

[[job-6-3]]
^3^ Compared to the sand of the sea, they would appear heavier, and so my words are full of sorrow.

[[job-6-4]]
^4^ For the arrows of the Lord are in me, my spirit drinks of their indignation, and the terrors of the Lord are soldiers against me.

[[job-6-5]]
^5^ Will the wild ass bray when he has grass? Or will the ox bellow when he stands before a full manger?

[[job-6-6]]
^6^ Or can one eat bland food, which is not seasoned with salt? Or can anyone taste that which, if tasted, causes death?

[[job-6-7]]
^7^ The things that my soul was unwilling to touch before, now, because of anguish, are my foods.

[[job-6-8]]
^8^ Who will grant that my petition may arrive and that God may bestow on me what I expect,

[[job-6-9]]
^9^ and that he who, at first, had crushed me, will let loose his hand and cut me down?

[[job-6-10]]
^10^ And may this be my consolation, that in afflicting me with sorrow, although he might not be lenient with me, I still do not contradict the words of the Holy One.

[[job-6-11]]
^11^ For what is my strength, that I may continue? Or what is my goal, so that I may act patiently?

[[job-6-12]]
^12^ My strength is not the strength of stones, nor is my flesh made of bronze.

[[job-6-13]]
^13^ Behold, there is no help for me in myself, and my loved ones also have withdrawn from me.

[[job-6-14]]
^14^ He who takes away mercy from his friend, abandons the fear of the Lord.

[[job-6-15]]
^15^ My brethren have disregarded me, like a torrent that passes swiftly through the steep valleys.

[[job-6-16]]
^16^ Those who fear frost, snow will rush over them.

[[job-6-17]]
^17^ At that time, when they are scattered, they will perish, and when it becomes hot, they will be freed from their place.

[[job-6-18]]
^18^ The paths of their steps are entangled; they will walk in vain and will perish.

[[job-6-19]]
^19^ Consider the paths of Thema, the ways of Saba, and wait a little while.

[[job-6-20]]
^20^ They have been thrown into confusion, just as I had hoped; they have even come to me and are overwhelmed with shame.

[[job-6-21]]
^21^ Now you have arrived, and merely by seeing my affliction, you are afraid.

[[job-6-22]]
^22^ Did I say: “Bring to me and give to me from your necessities?”

[[job-6-23]]
^23^ or, “Free me from the hand of the enemy and rescue me from the hand of the strong?”

[[job-6-24]]
^24^ Teach me, and I will be silent, and if by chance I have been ignorant of anything, instruct me.

[[job-6-25]]
^25^ Why have you diminished the words of truth, when there is none of you who is able to offer proof against me?

[[job-6-26]]
^26^ You prepare speeches as so much noise, and you offer words into the wind.

[[job-6-27]]
^27^ You encroach upon the orphan, and you strive to undermine your friend.

[[job-6-28]]
^28^ Such is true, so finish what you have begun. Listen closely, and see if I lie.

[[job-6-29]]
^29^ Respond, I beg you, without contention, and, speaking what is just, pass judgment.

[[job-6-30]]
^30^ And you will not find iniquity on my tongue, nor will foolishness resound in my throat.


[[job-7]]
== Chapter 7

[[job-7-1]]
^1^ The life of a man on the earth is a battle, and his days are like the days of a hired hand.

[[job-7-2]]
^2^ Just as a servant desires the shade, and just as the hired hand looks forward to the end of his work,

[[job-7-3]]
^3^ so also have I had empty months and have counted my burdensome nights.

[[job-7-4]]
^4^ If I lie down to sleep, I will say, “When will I rise?” And next I will hope for the evening and will be filled with sorrows even until darkness.

[[job-7-5]]
^5^ My flesh is clothed with particles of rottenness and filth; my skin is dried up and tightened.

[[job-7-6]]
^6^ My days have passed by more quickly than threads are cut by a weaver, and they have been consumed without any hope.

[[job-7-7]]
^7^ Remember that my life is wind, and my eye will not return to see good things.

[[job-7-8]]
^8^ Neither will the sight of man gaze upon me; your eyes are upon me, and I will not endure.

[[job-7-9]]
^9^ Just as a cloud is consumed and passes away, so he who descends to hell will not ascend.

[[job-7-10]]
^10^ He will not return again to his house, nor will his own place know him any longer.

[[job-7-11]]
^11^ And because of this, I will not restrain my mouth. I will speak in the affliction of my spirit. I will converse from the bitterness of my soul.

[[job-7-12]]
^12^ Am I an ocean or a whale, that you have encircled me in a prison?

[[job-7-13]]
^13^ If I say, “My bed will comfort me, and I will find rest, speaking with myself on my blanket,”

[[job-7-14]]
^14^ then you will frighten me with dreams, and strike dread through visions,

[[job-7-15]]
^15^ so that, because of these things, my soul would choose hanging, and my bones, death.

[[job-7-16]]
^16^ I despair; by no means will I live any longer. Spare me, for my days are nothing.

[[job-7-17]]
^17^ What is man, that you should praise him? Or why do you place your heart near him?

[[job-7-18]]
^18^ You visit him at dawn, and you test him unexpectedly.

[[job-7-19]]
^19^ How long will you not spare me, nor release me to ingest my saliva?

[[job-7-20]]
^20^ I have sinned; what should I do for you, O keeper of men? Why have you set me against you, so that I have become burdensome even to myself?

[[job-7-21]]
^21^ Why do you not steal away my sin, and why do you not sweep away my iniquity? Behold, now I will sleep in the dust, and if you seek me in the morning, I will not remain.


[[job-8]]
== Chapter 8

[[job-8-1]]
^1^ But Baldad the Suhite, responding, said:

[[job-8-2]]
^2^ How long will you speak this way, so that the words of your mouth are like a changeable wind?

[[job-8-3]]
^3^ Does God supplant judgment, or does the Almighty subvert that which is just?

[[job-8-4]]
^4^ And if now your children have sinned against him, and he has dismissed them into the power of their iniquity,

[[job-8-5]]
^5^ even so, you should arise early to God, so as to beseech the Almighty.

[[job-8-6]]
^6^ If you approach with purity and honesty, he will quickly be attentive to you, and a peaceful life will repay your righteousness,

[[job-8-7]]
^7^ so much so that, if your former things were small, your latter things would be multiplied greatly.

[[job-8-8]]
^8^ For inquire of the earliest generation, and investigate diligently the history of the fathers,

[[job-8-9]]
^9^ (of course, we are but of yesterday and are ignorant that our days on earth are like a shadow,)

[[job-8-10]]
^10^ and they will teach you; they will speak with you and will offer you the eloquence of their hearts.

[[job-8-11]]
^11^ Can the marsh plant live without moisture? Or can sedges grow without water?

[[job-8-12]]
^12^ When it is still in flower, and has not been pulled up by hand, it withers before all other plants.

[[job-8-13]]
^13^ Just so are the ways of all who forget God, and the hope of the hypocrite will perish.

[[job-8-14]]
^14^ His frenzy will not please him, and his faith will be like a spider’s web.

[[job-8-15]]
^15^ He will lean on his house, and it will not stand; he will prop it up, but it will not rise.

[[job-8-16]]
^16^ He seems to have moisture before the sun arrives; and at sunrise, his sprout shoots forth.

[[job-8-17]]
^17^ His roots will crowd together over a heap of stones, and among the stones he will remain.

[[job-8-18]]
^18^ If someone is devoured right beside him, he will deny him and will say: “I do not know you.”

[[job-8-19]]
^19^ For this is the benefit of his way, that others in turn may spring up from the earth.

[[job-8-20]]
^20^ God will not discard the simple, nor will he extend his hand to the spiteful,

[[job-8-21]]
^21^ even until your mouth is filled with laughter and your lips with rejoicing.

[[job-8-22]]
^22^ Those who hate you, will be clothed with confusion, and the tabernacle of the impious will not continue.


[[job-9]]
== Chapter 9

[[job-9-1]]
^1^ And Job, responding, said:

[[job-9-2]]
^2^ Truly, I know that it is so, and that man cannot be justified compared with God.

[[job-9-3]]
^3^ If he chooses to contend with him, he is not able to respond to him once out of a thousand times.

[[job-9-4]]
^4^ He is understanding in heart and mighty in strength; who has resisted him and yet had peace?

[[job-9-5]]
^5^ He has moved mountains, and those whom he overthrew in his fury did not know it.

[[job-9-6]]
^6^ He shakes the earth out of its place and its pillars tremble.

[[job-9-7]]
^7^ He commands the sun and it does not rise, and he closes the stars as if under a seal.

[[job-9-8]]
^8^ He alone extends the heavens, and he walks upon the waves of the sea.

[[job-9-9]]
^9^ He fashions Arcturus, and Orion, and Hyades, and the interior of the south.

[[job-9-10]]
^10^ He accomplishes great and incomprehensible and miraculous things, which cannot be numbered.

[[job-9-11]]
^11^ If he approaches me, I will not see him; if he departs, I will not understand.

[[job-9-12]]
^12^ If he suddenly should question, who will answer him? Or who can say, “Why did you do so?”

[[job-9-13]]
^13^ God, whose wrath no one is able to resist, and under whom they bend who carry the world,

[[job-9-14]]
^14^ what am I then, that I should answer him and exchange words with him?

[[job-9-15]]
^15^ And if I now have any justice, I will not respond, but will beseech my judge.

[[job-9-16]]
^16^ And if he should listen to me when I call, I would not believe that he had heard my voice.

[[job-9-17]]
^17^ For he will crush me in a whirlwind and multiply my wounds, even without cause.

[[job-9-18]]
^18^ He does not permit my spirit to rest, and he fills me with bitterness.

[[job-9-19]]
^19^ If strength is sought, he is most strong; if equity in judgment, no one would dare to give testimony for me.

[[job-9-20]]
^20^ If I wanted to justify myself, my own mouth will condemn me; if I would reveal my innocence, he would prove me depraved.

[[job-9-21]]
^21^ And if I now became simple, my soul would be ignorant even of this, and my life would weary me.

[[job-9-22]]
^22^ There is one thing that I have said: both the innocent and the impious he consumes.

[[job-9-23]]
^23^ If he scourges, let him kill all at once, and not laugh at the punishment of the innocent.

[[job-9-24]]
^24^ Since the earth has been given into the hand of the impious, he covers the face of its judges; for if it is not him, then who is it?

[[job-9-25]]
^25^ My days have been swifter than a messenger; they have fled and have not seen goodness.

[[job-9-26]]
^26^ They have passed by like ships carrying fruits, just like an eagle flying to food.

[[job-9-27]]
^27^ If I say: “By no means will I speak this way.” I change my face and I am tortured with sorrow.

[[job-9-28]]
^28^ I have dreaded all my works, knowing that you did not spare the offender.

[[job-9-29]]
^29^ Yet, if I am also just as impious, why have I labored in vain?

[[job-9-30]]
^30^ If I had been washed with snow-like waters, and my hands were shining like the cleanest thing,

[[job-9-31]]
^31^ yet you would plunge me in filth, and my own garments would abhor me.

[[job-9-32]]
^32^ For even I would not answer a man who were like myself, nor one who could be heard with me equally in judgment.

[[job-9-33]]
^33^ There is no one who could both prevail in argument and in placing his hand between the two.

[[job-9-34]]
^34^ Let him take his staff away from me, and let not the fear of him terrify me.

[[job-9-35]]
^35^ I will speak and I will not fear him, for in fearfulness I am not able to respond.


[[job-10]]
== Chapter 10

[[job-10-1]]
^1^ My soul is weary of my life. I will release my words against myself. I will speak in the bitterness of my soul.

[[job-10-2]]
^2^ I will say to God: Do not be willing to condemn me. Reveal to me why you judge me this way.

[[job-10-3]]
^3^ Does it seem good to you, if you find fault with me and oppress me, the work of your own hands, and assist the counsel of the impious?

[[job-10-4]]
^4^ Do you have bodily eyes? Or, just as man sees, will you see?

[[job-10-5]]
^5^ Are your days just like the days of man, and are your years as the times of humans,

[[job-10-6]]
^6^ so that you would inquire about my iniquity and examine my sin?

[[job-10-7]]
^7^ And you know that I have done nothing impious, yet there is no one who can deliver from your hand.

[[job-10-8]]
^8^ Your hands have made me and formed me all around, and, in this way, do you suddenly throw me away?

[[job-10-9]]
^9^ Remember, I ask you, that you have fashioned me like clay, and you will reduce me to dust.

[[job-10-10]]
^10^ Have you not extracted me like milk and curdled me like cheese?

[[job-10-11]]
^11^ You have clothed me with skin and flesh. You have put me together with bones and nerves.

[[job-10-12]]
^12^ You have assigned to me life and mercy, and your visitation has preserved my spirit.

[[job-10-13]]
^13^ Though you may conceal this in your heart, yet I know that you remember everything.

[[job-10-14]]
^14^ If I have sinned, and you have spared me for an hour, why do you not endure me to be clean from my iniquity?

[[job-10-15]]
^15^ And if I should be impious, woe to me, and if I should be just, I will not lift up my head, being drenched with affliction and misery.

[[job-10-16]]
^16^ And because of pride, you will seize me like a lioness, and having returned, you torment me to an extraordinary degree.

[[job-10-17]]
^17^ You renew your testimony against me, and you multiply your wrath against me, and these punishments make war within me.

[[job-10-18]]
^18^ Why did you lead me out of the womb? If only I had been consumed, so that no eye would ever see me!

[[job-10-19]]
^19^ I should have been as if I had not been: transferred from the womb to the tomb.

[[job-10-20]]
^20^ Will not my few days be completed soon? Release me, therefore, so that I may lament my sorrows a little,

[[job-10-21]]
^21^ before I depart and return no more to a land that is dark and covered with the fog of death,

[[job-10-22]]
^22^ a land of misery and darkness, where the shadow of death, and nothing else but everlasting horror, dwells.


[[job-11]]
== Chapter 11

[[job-11-1]]
^1^ But Zophar the Naamathite, responding, said:

[[job-11-2]]
^2^ Will he who speaks much, not also listen? Or will a talkative man be justified?

[[job-11-3]]
^3^ Will men be silent only for you? And when you have mocked others, will no one refute you?

[[job-11-4]]
^4^ For you said: “My word is pure, and I am clean in your sight.”

[[job-11-5]]
^5^ Yet I wish that God would speak with you, and would open his lips to you,

[[job-11-6]]
^6^ so that he might reveal to you the secrets of wisdom, and how intricate his law is, and that you would understand how much less he requires of you than your iniquity deserves.

[[job-11-7]]
^7^ By chance, will you comprehend the footsteps of God and reach all the way to the perfection of the Almighty?

[[job-11-8]]
^8^ He is higher than heaven, and what will you do? He is deeper than hell, but how will you know?

[[job-11-9]]
^9^ His measure is longer than the earth and wider than the sea.

[[job-11-10]]
^10^ If he overturns all things, or packs them together, who will contradict him?

[[job-11-11]]
^11^ For he knows the vanity of men, and when he sees iniquity, does he not evaluate it?

[[job-11-12]]
^12^ A vain man is lifted up in arrogance, and he thinks that he is born free like a wild ass’s colt.

[[job-11-13]]
^13^ But you have fortified your heart and extended your hands to him.

[[job-11-14]]
^14^ If you would send away from you the iniquity that is in your hand, and not let injustice remain in your tabernacle,

[[job-11-15]]
^15^ then you would be able to lift up your face without blemish, and you would be steadfast and unafraid.

[[job-11-16]]
^16^ Misery, likewise, you would forget, or would remember only like waters that have passed by.

[[job-11-17]]
^17^ And brightness, like that of midday, will rise upon you until evening, and when you would think yourself consumed, you will rise up like the morning star.

[[job-11-18]]
^18^ And, when hope has been set before you, you will have faith, and, when buried, you will sleep secure.

[[job-11-19]]
^19^ You will rest, and there will be nothing to make you afraid, and many will make requests before your face.

[[job-11-20]]
^20^ But the eyes of the impious will fade away, and the path to escape will perish before them, for the abomination of the soul is their hope.


[[job-12]]
== Chapter 12

[[job-12-1]]
^1^ Then Job, answering, said:

[[job-12-2]]
^2^ Are you, therefore, alone among men, and will wisdom die with you?

[[job-12-3]]
^3^ And I have a heart just as you also do, and I am not inferior to you. For who is ignorant of these things, which you know?

[[job-12-4]]
^4^ He who is mocked by his friends as I am, will call upon God, and he will listen to him because it is the sincerity of the just that is being mocked.

[[job-12-5]]
^5^ The lamp that is despised in the thoughts of the rich is ready for the appointed time.

[[job-12-6]]
^6^ The tabernacles of robbers are numerous, and they provoke God boldly; whereas, it is he who has given all things into their hands.

[[job-12-7]]
^7^ In truth, ask the mules, and they will teach you, and the birds of the sky, and they will reveal to you.

[[job-12-8]]
^8^ Speak with the earth, and it will respond to you, and the fish of the sea will explain.

[[job-12-9]]
^9^ Who is ignorant that the hand of the Lord has made all these things?

[[job-12-10]]
^10^ In his hand is the soul of all the living and the spirit of all the flesh of mankind.

[[job-12-11]]
^11^ Does not the ear perceive words, and the palate, when eating, perceive flavor?

[[job-12-12]]
^12^ In old age is wisdom, and in length of days is prudence.

[[job-12-13]]
^13^ With him is wisdom and strength, he has counsel and understanding.

[[job-12-14]]
^14^ If he tears down, there is no one who can build up; if he encloses a man, there is no one who can open.

[[job-12-15]]
^15^ If he restrains the waters, everything will dry up; and if he sends them forth, they will subdue the land.

[[job-12-16]]
^16^ With him is strength and wisdom; he knows both the deceiver and he who is deceived.

[[job-12-17]]
^17^ He leads advisors to a foolish end and judges to stupidity.

[[job-12-18]]
^18^ He removes the belt of kings and encircles their waist with a rope.

[[job-12-19]]
^19^ He leads away priests in dishonor and displaces nobles,

[[job-12-20]]
^20^ altering the lips of those who speak the truth and sweeping away the teaching of the aged.

[[job-12-21]]
^21^ He pours disdain upon the leaders, relieving those who had been oppressed.

[[job-12-22]]
^22^ He reveals the depths of the darkness, and he brings the shadow of death into the light.

[[job-12-23]]
^23^ He multiplies peoples, and destroys them, and, having been overthrown, he restores them anew.

[[job-12-24]]
^24^ He transforms the heart of the leaders of the people on earth, and misleads those who in vain advance upon the inviolable.

[[job-12-25]]
^25^ They will grope as in the darkness, not the light, and he will make them stagger like drunkards.


[[job-13]]
== Chapter 13

[[job-13-1]]
^1^ Behold, my eye has seen all these things, and my ear has heard, and I have understood each one.

[[job-13-2]]
^2^ In conformity with your knowledge, I also know. I am not inferior to you.

[[job-13-3]]
^3^ Yet I speak this way to the Almighty, and I desire to argue with God,

[[job-13-4]]
^4^ having first shown that you fabricate lies and cultivate perverse teachings.

[[job-13-5]]
^5^ And I wish that you would remain silent, so that you would be counted among the wise.

[[job-13-6]]
^6^ Therefore, listen to my correction, and pay attention to the judgment of my lips.

[[job-13-7]]
^7^ Does God require your lie, so that you would speak deceitfully for him?

[[job-13-8]]
^8^ Have you taken his place, and do you struggle to give judgment in favor of God?

[[job-13-9]]
^9^ Or, will it please him, from whom nothing can be concealed? Or, will he be deceived, like a man, by your deceitfulness?

[[job-13-10]]
^10^ He will accuse you because in secret you have preempted his presence.

[[job-13-11]]
^11^ As soon as he moves himself, he will disturb you, and his dread will fall over you.

[[job-13-12]]
^12^ Your remembrance will be compared to ashes, and your necks will be reduced to clay.

[[job-13-13]]
^13^ Be silent for a little while, so that I may speak whatever my mind suggests to me.

[[job-13-14]]
^14^ Why do I wound my flesh with my teeth, and carry my soul in my hands?

[[job-13-15]]
^15^ And now, if he would kill me, I will hope in him; in this, truly, I will correct my ways in his sight.

[[job-13-16]]
^16^ And he will be my savior, for no hypocrite at all will approach in his sight.

[[job-13-17]]
^17^ Listen to my words, and perceive an enigma with your ears.

[[job-13-18]]
^18^ If I will be judged, I know that I will be found to be just.

[[job-13-19]]
^19^ Who is it that will go to judgment with me? Let him approach. Why should I be consumed in silence?

[[job-13-20]]
^20^ Do not do such things to me twice, and then I will not hide from your face.

[[job-13-21]]
^21^ Take your hand far away from me, and do not let your dread terrify me.

[[job-13-22]]
^22^ Call me, and I will answer you, or else I will speak, and you can answer me.

[[job-13-23]]
^23^ How many iniquities and sins do I have? Reveal my crimes and offenses to me.

[[job-13-24]]
^24^ Why do you conceal your face and consider me to be your enemy?

[[job-13-25]]
^25^ Against a leaf, which is carried away by the wind, you reveal your power, and you pursue dry straw.

[[job-13-26]]
^26^ For you write bitter things against me, and you want to consume me for the sins of my youth.

[[job-13-27]]
^27^ You have put my feet on a tether, and you have observed all my paths, and you have considered the steps of my feet.

[[job-13-28]]
^28^ I will be left to decay like something rotten and like a garment that is being eaten by moths.


[[job-14]]
== Chapter 14

[[job-14-1]]
^1^ Man, born of woman, living for a short time, is filled with many miseries.

[[job-14-2]]
^2^ He comes forth like a flower, and is crushed, and he flees, as if a shadow, and never remains in the same state.

[[job-14-3]]
^3^ And do you consider it fitting to look down with your eyes on someone in this way and to lead him into judgment with you?

[[job-14-4]]
^4^ Who can make him clean who is conceived of unclean seed? Are you not the only one who can?

[[job-14-5]]
^5^ The days of man are short, and the number of his months is with you; you have determined his limits, which cannot be surpassed.

[[job-14-6]]
^6^ Withdraw a little from him, so that he may rest, until his awaited day arrives, like that of the hired hand.

[[job-14-7]]
^7^ A tree has hope: if it has been cut, it turns green again, and its branches spring forth.

[[job-14-8]]
^8^ If its roots grow old in the earth, and its trunk passes into dust,

[[job-14-9]]
^9^ at the scent of water, it will sprout and bring forth leaves, as when it had first been planted.

[[job-14-10]]
^10^ Truly, when a man dies, and has been left unprotected, and has decayed, I ask you where is he?

[[job-14-11]]
^11^ It is as if the waters had receded from the sea and an emptied river had dried up;

[[job-14-12]]
^12^ just so, when a man is fallen asleep, he will not rise again, until the heavens are worn away; he will not awaken, nor rise from his sleep.

[[job-14-13]]
^13^ Who will grant this to me, that you will protect me in the underworld, and hide me until your fury passes by, and establish a time for me, in which you will remember me?

[[job-14-14]]
^14^ Do you suppose that a dead man will live again? On each of the days in which I now battle, I wait until my transformation occurs.

[[job-14-15]]
^15^ You will call me and I will answer you; to the work of your hands, you will extend your right hand.

[[job-14-16]]
^16^ Indeed, you have numbered my steps, but you have been lenient with my sins.

[[job-14-17]]
^17^ You have sealed up my offenses, as if in a purse, but you have cured my iniquity.

[[job-14-18]]
^18^ A falling mountain flows away, and a stone is transferred from its place.

[[job-14-19]]
^19^ Waters wear away stones, and with a flood the land is reduced little by little; and similarly, you will destroy man.

[[job-14-20]]
^20^ You have strengthened him for a little while, so that he may cross over into eternity. You will change his face and send him forth.

[[job-14-21]]
^21^ Whether his sons have been noble or ignoble, he will not understand.

[[job-14-22]]
^22^ And in this way his body, while he yet lives, will have grief, and his soul will mourn over himself.


[[job-15]]
== Chapter 15

[[job-15-1]]
^1^ But Eliphaz the Themanite, answering, said:

[[job-15-2]]
^2^ Will a wise man answer as if he were speaking wind, and will he fill his stomach with fire?

[[job-15-3]]
^3^ You rebuke with words he who is not equal to you, and you speak what is not expedient for you,

[[job-15-4]]
^4^ to such an extent that, within yourself, you have expelled reverence and have taken away prayers from the presence of God.

[[job-15-5]]
^5^ For your iniquity has mislead your mouth, and you imitate the tongue of blasphemers.

[[job-15-6]]
^6^ Your own mouth will condemn you, not I; and your own lips will answer you.

[[job-15-7]]
^7^ Are you the first man who was born, or were you formed before the hills?

[[job-15-8]]
^8^ Have you heard the intentions of God, and will his wisdom be inferior to you?

[[job-15-9]]
^9^ What do you know, about which we are ignorant? What do you understand that we do not know?

[[job-15-10]]
^10^ There are with us both aged and ancient men, even more senior than your fathers.

[[job-15-11]]
^11^ Is it so important that God should console you? But your own depraved words prevent this.

[[job-15-12]]
^12^ Why does your heart exalt you, and why do you gaze with your eyes, as if thinking great things?

[[job-15-13]]
^13^ Why does your spirit stir against God, so as to utter such speeches from your mouth?

[[job-15-14]]
^14^ What is man that he should be immaculate, and that he should appear just, having been born of woman?

[[job-15-15]]
^15^ Behold, among his holy ones not one is immutable, and even the heavens are not pure in his sight.

[[job-15-16]]
^16^ How much more abominable and useless is the man who drinks as if from the water of iniquity?

[[job-15-17]]
^17^ I will reveal to you, so listen to me; and I will explain to you what I have seen.

[[job-15-18]]
^18^ The wise acknowledge, and they do not leave behind, their fathers,

[[job-15-19]]
^19^ to whom alone the earth has been given, and no stranger passed among them.

[[job-15-20]]
^20^ The impious is arrogant for all his days, and the number of the years of his tyranny is uncertain.

[[job-15-21]]
^21^ The sound of terror is always in his ears; and when there is peace, he always suspects treason.

[[job-15-22]]
^22^ He does not believe that it is possible for him to be turned from darkness into the light, for he sees around him the sword on every side.

[[job-15-23]]
^23^ When he moves himself to seek bread, he knows that the day of darkness has been prepared for his hand.

[[job-15-24]]
^24^ Tribulation will terrify him, and anguish will prevail over him, like a king who is being prepared to go to battle.

[[job-15-25]]
^25^ For he has extended his hand against God, and he has strengthened himself against the Almighty.

[[job-15-26]]
^26^ He has rushed against him with his throat exposed, and he has been armed with a fat neck.

[[job-15-27]]
^27^ Thickness has covered his face, and lard hangs down from his sides.

[[job-15-28]]
^28^ He has lived in desolate cities and deserted houses, which have been turned into tombs.

[[job-15-29]]
^29^ He will not be enriched, nor will his basic necessities endure, nor will he establish his root in the earth.

[[job-15-30]]
^30^ He will not withdraw from the darkness; the flame will burn up his branches, and he will be defeated by the breath of his own mouth.

[[job-15-31]]
^31^ He will not believe, being vainly deceived by error, that he could be redeemed at any price.

[[job-15-32]]
^32^ Before his time is completed, he will pass into ruin and his hands will wither away.

[[job-15-33]]
^33^ He will be wounded like a grapevine, when its cluster is in first flower, and like an olive tree that casts off its flower.

[[job-15-34]]
^34^ For the congregation of the hypocrites is fruitless, and fire will devour the tabernacles of those who love to accept money.

[[job-15-35]]
^35^ He has conceived sorrow, and he has brought forth iniquity, and his womb prepares deceit.


[[job-16]]
== Chapter 16

[[job-16-1]]
^1^ Then Job, answering, said:

[[job-16-2]]
^2^ I have often heard such things; you are all aggravating comforters.

[[job-16-3]]
^3^ Will there be no end to windy words? Or is it at all a burden to you, if you speak?

[[job-16-4]]
^4^ I, too, can speak like you; and I also wish that your soul favored my soul.

[[job-16-5]]
^5^ I would also comfort you with speeches and would wag my head over you.

[[job-16-6]]
^6^ I would strengthen you with my mouth, and would move my lips, as if being lenient to you.

[[job-16-7]]
^7^ But what can I do? When I am speaking, my grief will not be quiet; and if I am quiet, it will not withdraw from me.

[[job-16-8]]
^8^ But now my grief has crushed me, and all my limbs have been reduced to nothing.

[[job-16-9]]
^9^ My wrinkles bear witness against me, and a liar rises up against my face, contradicting me.

[[job-16-10]]
^10^ He has gathered together his fury towards me, and, threatening me, he has roared against me with his teeth; my enemy has beheld me with terrible eyes.

[[job-16-11]]
^11^ They have opened their mouths against me, and, reproaching me, they have struck me on the cheek; they are nourished by my sufferings.

[[job-16-12]]
^12^ God has confined me with the immoral, and he has delivered me into the hands of the impious.

[[job-16-13]]
^13^ I, who once was wealthy, am now crushed. He has grabbed me by my neck; he has broken me and has placed me before him as a sign.

[[job-16-14]]
^14^ He has surrounded me with his lances. He has severely wounded my lower back, he has not been lenient, and he has poured out my organs upon the earth.

[[job-16-15]]
^15^ He has cut me with wound after wound. He has rushed upon me like a giant.

[[job-16-16]]
^16^ I have sewn sackcloth over my skin, and I have covered my body with ashes.

[[job-16-17]]
^17^ My face is swollen from weeping, and my eyelids have dimmed my vision.

[[job-16-18]]
^18^ These things I have endured without iniquity in my hand, while I held pure prayers before God.

[[job-16-19]]
^19^ O earth, do not conceal my blood, nor let my outcry find a hiding place in you.

[[job-16-20]]
^20^ For behold, my witness is in heaven, and my confidante is on high.

[[job-16-21]]
^21^ My friends are full of words; my eye rains tears upon God.

[[job-16-22]]
^22^ And I wish that a man might be so judged before God, just as the son of man is judged with his assistant!

[[job-16-23]]
^23^ For behold, a few years pass by, and I am walking a path by which I will not return.


[[job-17]]
== Chapter 17

[[job-17-1]]
^1^ My spirit will be wasted, my days will be shortened, and only the grave will be left for me.

[[job-17-2]]
^2^ I have not sinned, yet my eye remains in bitterness.

[[job-17-3]]
^3^ Free me, O Lord, and set me beside you, and let the hand of anyone you wish fight against me.

[[job-17-4]]
^4^ You have set their heart far from discipline; therefore, they will not be praised.

[[job-17-5]]
^5^ He promises prey to his companions, but the eyes of his sons will grow faint.

[[job-17-6]]
^6^ He has posted me like a proverb to the people, and I am an example in their presence.

[[job-17-7]]
^7^ My eyesight has been clouded by indignation, and my limbs have been reduced, as if to nothing.

[[job-17-8]]
^8^ The just will be astounded over this, and the innocent will be stirred up against the hypocrite.

[[job-17-9]]
^9^ And the just will cling to his way, and clean hands will increase strength.

[[job-17-10]]
^10^ Therefore, be converted, all of you, and approach, for I do not find in you any wisdom.

[[job-17-11]]
^11^ My days have passed away; my thoughts have been scattered, tormenting my heart.

[[job-17-12]]
^12^ They have turned night into day, and I hope for light again after the darkness.

[[job-17-13]]
^13^ If I should wait, the underworld is my house, and in darkness I have spread out my bed.

[[job-17-14]]
^14^ I have said to decay and to worms: “You are my father, my mother, and my sister.”

[[job-17-15]]
^15^ Therefore, where is my expectation now, and who is it that considers my patience?

[[job-17-16]]
^16^ Everything of mine will descend into the deepest underworld; do you think that, in that place at least, there will be rest for me?


[[job-18]]
== Chapter 18

[[job-18-1]]
^1^ But Baldad the Suhite responded by saying:

[[job-18-2]]
^2^ How long will you throw around words? Understand first, and then let us speak.

[[job-18-3]]
^3^ Why have we been treated like mules, as if we were unworthy before you?

[[job-18-4]]
^4^ You, who ruins your own soul in your fury, will the earth be forsaken because of you, and will the cliffs be moved from their place?

[[job-18-5]]
^5^ Will not the light of the impious be put out, and the flame of his fire refuse to shine?

[[job-18-6]]
^6^ Light will become darkness in his tabernacle, and the lamp that is over him will be extinguished.

[[job-18-7]]
^7^ His strong steps will be constrained, and his own counsel will cast him down uncontrollably.

[[job-18-8]]
^8^ For he has caused his own feet to go into a net, and he has walked into its web.

[[job-18-9]]
^9^ His heel will be held in a snare, and thirst will rage against him.

[[job-18-10]]
^10^ A trap has been hidden for him in the earth, and a decoy, along his path.

[[job-18-11]]
^11^ Horrifying things will terrify him everywhere and will entangle his feet.

[[job-18-12]]
^12^ Let his strength be diminished by famine, and let starvation invade his ribs.

[[job-18-13]]
^13^ Let it devour the beauty of his skin; let the ancient death consume his arms.

[[job-18-14]]
^14^ Let his confidence be torn away from his tabernacle, and let ruin trample over him like a king.

[[job-18-15]]
^15^ Let the companions of he who is not, dwell in his tabernacle; let brimstone rain down upon his tabernacle.

[[job-18-16]]
^16^ Let his roots be dried up from beneath him, and his harvest be crushed from above.

[[job-18-17]]
^17^ Let the memory of him perish from the earth, and let not his name be celebrated in the streets.

[[job-18-18]]
^18^ He will expel him from light into darkness, and he will remove him from the world.

[[job-18-19]]
^19^ Neither his offspring, nor his descendants, will exist among his people, nor will there be any remnants in his country.

[[job-18-20]]
^20^ The last will be astonished at his day, and the first will be overcome with horror.

[[job-18-21]]
^21^ And so, these are the tabernacles of the sinful, and this the place of he who does not know God.


[[job-19]]
== Chapter 19

[[job-19-1]]
^1^ But Job answered by saying:

[[job-19-2]]
^2^ How long will you afflict my soul and wear me down with words?

[[job-19-3]]
^3^ So, ten times you confound me and are not ashamed to oppress me.

[[job-19-4]]
^4^ Now, of course, if I have been ignorant, my ignorance will be with me.

[[job-19-5]]
^5^ But you have risen up against me, and you accuse me to my disgrace.

[[job-19-6]]
^6^ At least now you should understand that God has not afflicted me with a balanced judgment, though he has encompassed me with his scourges.

[[job-19-7]]
^7^ Behold, I will cry out, enduring violence, and no one will hear. I will announce loudly, but there is no one who may judge.

[[job-19-8]]
^8^ He has hemmed in my path, and I cannot pass; he has added darkness to my difficult path.

[[job-19-9]]
^9^ He has plundered me of my glory, and he has stolen the crown from my head.

[[job-19-10]]
^10^ He has destroyed me on every side, and I am lost, and, like an uprooted tree, he has taken away my hope.

[[job-19-11]]
^11^ His fury has raged against me, and in this way he has treated me like his enemy.

[[job-19-12]]
^12^ His troops have gathered together, and they have made their way to me, and they have besieged my tabernacle all around.

[[job-19-13]]
^13^ He has put my brothers far from me, and my friends have withdrawn from me like strangers.

[[job-19-14]]
^14^ My kinsmen have forsaken me, and those who knew me, have forgotten me.

[[job-19-15]]
^15^ The inhabitants of my house and my maidservants treat me just as if I were a stranger, and I have been like a sojourner in their eyes.

[[job-19-16]]
^16^ I called my servant, and he did not respond; I pleaded with him with my own mouth.

[[job-19-17]]
^17^ My wife has shuddered at my breath, and I have begged the sons of my loins.

[[job-19-18]]
^18^ Even the foolish have looked down on me, and, when I withdrew from them, they spoke ill of me.

[[job-19-19]]
^19^ Those who were sometimes my counselors, treat me like an abomination; and he whom I valued the most has turned against me.

[[job-19-20]]
^20^ Since my flesh has been consumed, my bone adheres to my skin, and only my lips have been left around my teeth.

[[job-19-21]]
^21^ Have mercy on me, have compassion on me, at least you my friends, because the hand of the Lord has touched me.

[[job-19-22]]
^22^ Why do you pursue me just as God does, and satiate yourselves with my flesh?

[[job-19-23]]
^23^ Who will grant to me that my words may be written down? Who will grant to me that they may be inscribed in a book,

[[job-19-24]]
^24^ with an iron pen and a plate of lead, or else be carved in stone?

[[job-19-25]]
^25^ For I know that my Redeemer lives, and on the last day I will rise out of the earth.

[[job-19-26]]
^26^ And I will be enveloped again with my skin, and in my flesh I will see my God.

[[job-19-27]]
^27^ It is he whom I myself will see, and he whom my eyes will behold, and no other. This, my hope, has taken rest in my bosom.

[[job-19-28]]
^28^ Why then do you now say: “Let us pursue him, and let us find a basis to speak against him?”

[[job-19-29]]
^29^ So then, flee from the face of the sword, for the sword is the avenger of iniquities; but know this: there is to be a judgment.


[[job-20]]
== Chapter 20

[[job-20-1]]
^1^ Then Zophar the Naamathite answered by saying:

[[job-20-2]]
^2^ In response, various thoughts succeed one another in me, and my mind moves quickly through different ideas.

[[job-20-3]]
^3^ The teaching you use to admonish me, I will hear, and the spirit of my understanding will respond for me.

[[job-20-4]]
^4^ This, I know, is from the beginning, from the time that man was set over the earth:

[[job-20-5]]
^5^ that the praise of the impious shall be short, and the joy of the hypocrite lasts only a moment.

[[job-20-6]]
^6^ If his pride ascends even towards the heavens, and his head touches the clouds,

[[job-20-7]]
^7^ in the end, he will be destroyed like a trash heap, and those who had seen him will say: “Where is he?”

[[job-20-8]]
^8^ Like a dream that flies away, he will not be found; he will pass away like a nightmare.

[[job-20-9]]
^9^ The eyes that had seen him, will not see him; no longer will his own place admire him.

[[job-20-10]]
^10^ His sons will be worn away by poverty, and his own hands will deliver his grief to him.

[[job-20-11]]
^11^ His bones will be filled with the vices of his youth, and they will sleep with him in the dust.

[[job-20-12]]
^12^ For, when evil will be sweet in his mouth, he will hide it under his tongue.

[[job-20-13]]
^13^ He will permit it, and not abandon it, and he will conceal it in his throat.

[[job-20-14]]
^14^ His bread in his belly will be turned into the venom of snakes within him.

[[job-20-15]]
^15^ The riches that he devours, he will vomit up, and from his stomach God will draw them out.

[[job-20-16]]
^16^ He will suck the head of snakes, and the tongue of the viper will kill him.

[[job-20-17]]
^17^ (May he never see the streams of the river, the torrents of honey and butter.)

[[job-20-18]]
^18^ He will be repaid for all he has done, yet he will not be consumed; according to the multitude of his schemes, so also will he suffer.

[[job-20-19]]
^19^ For, having broken in, he stripped the poor. He has quickly stolen away a house he did not build.

[[job-20-20]]
^20^ And yet his stomach will not be satisfied, and when he has the things he desires, he will not be able to possess them.

[[job-20-21]]
^21^ Nothing remained of his portion, and, because of this, nothing will continue of his kind.

[[job-20-22]]
^22^ When he will be satisfied, he will be constrained; he will seethe, and all anguish will fall upon him.

[[job-20-23]]
^23^ May his stomach be filled, so that God may send forth the fury of his wrath to him and may rain down his battle upon him.

[[job-20-24]]
^24^ He will flee from weapons of iron, and he will fall in an arc of brass,

[[job-20-25]]
^25^ which had been drawn and had issued forth from its sheath, glittering in its bitterness: the horrible ones will go forth and approach over him.

[[job-20-26]]
^26^ All darkness has been hidden in his secrecy. A fire that has not been set will devour him; he will be thrown down and forsaken in his tabernacle.

[[job-20-27]]
^27^ The heavens will reveal his sinfulness, and the earth will rise up against him.

[[job-20-28]]
^28^ The offspring of his house will be exposed; he will be pulled down in the day of God’s wrath.

[[job-20-29]]
^29^ This is the portion of a wicked man from God, and the inheritance of his words from the Lord.


[[job-21]]
== Chapter 21

[[job-21-1]]
^1^ Then Job responded by saying:

[[job-21-2]]
^2^ I beseech you to hear my words and to do penance.

[[job-21-3]]
^3^ Permit me, and I will speak, and afterwards, if you see fit, you can laugh at my words.

[[job-21-4]]
^4^ Is my dispute against man, so that I would have no reason to be discouraged?

[[job-21-5]]
^5^ Listen to me and be astonished, and place a finger over your mouth.

[[job-21-6]]
^6^ As for me, when I think it over, I am afraid, and trembling convulses my body.

[[job-21-7]]
^7^ Why then do the impious live, having been lifted up and strengthened with riches?

[[job-21-8]]
^8^ They see their offspring continue before them: a commotion of close relatives and of children’s children in their sight.

[[job-21-9]]
^9^ Their houses have been secure and peaceable, and there is no staff of God over them.

[[job-21-10]]
^10^ Their cattle have conceived and have not miscarried; their cow has given birth and is not deprived of her newborn.

[[job-21-11]]
^11^ Their little ones go out like a flock, and their children jump around playfully.

[[job-21-12]]
^12^ They take up the timbrel and the lyre, and they rejoice at the sound of the organ.

[[job-21-13]]
^13^ Their days are prolonged in wealth, yet, in an instant, they descend into hell.

[[job-21-14]]
^14^ Who has said to God, “Depart from us, for we do not want the knowledge of your ways.

[[job-21-15]]
^15^ Who is the Almighty that we should serve him? And how is it helpful to us if we pray to him?”

[[job-21-16]]
^16^ It is true that their good things are not in their power. May the counsel of the impious be far from me!

[[job-21-17]]
^17^ How often will the lamp of the wicked be extinguished, and a deluge overtake them, and how often will he distribute the afflictions of his wrath?

[[job-21-18]]
^18^ They will be like chaff before the face of the wind, and like ashes that the whirlwind scatters.

[[job-21-19]]
^19^ God will preserve the grief of the father for his sons, and, when he repays, then he will understand.

[[job-21-20]]
^20^ His eyes will see his own destruction, and he will drink from the wrath of the Almighty.

[[job-21-21]]
^21^ For what does he care what happens to his house after him, or if the number of its months are reduced by half?

[[job-21-22]]
^22^ Can anyone teach holy knowledge to God, who judges the exalted?

[[job-21-23]]
^23^ This one dies strong and healthy, rich and happy.

[[job-21-24]]
^24^ His gut is full of fat and his bones are moistened with marrow.

[[job-21-25]]
^25^ In truth, another dies in bitterness of soul, without any resources.

[[job-21-26]]
^26^ And yet they will sleep together in the dust, and worms will cover them.

[[job-21-27]]
^27^ Surely, I know your thoughts and your sinful judgments against me.

[[job-21-28]]
^28^ For you say, “Where is the house of the ruler, and where are the tabernacles of the impious?”

[[job-21-29]]
^29^ Ask any passerby whom you wish, and you will realize that he understands these same things:

[[job-21-30]]
^30^ that the evil-doer is reserved for the day of destruction, and he will be led to the day of wrath.

[[job-21-31]]
^31^ Who will reprove his way to his face, and who will repay him for what he has done?

[[job-21-32]]
^32^ He will be led to the tomb, and he will remain awake in the chaos of the dead.

[[job-21-33]]
^33^ He has been found acceptable to the banks of the River of Lamentation, and he will draw any man towards him, and there are countless before him.

[[job-21-34]]
^34^ Therefore, how long will you console me in vain, when your answer is shown to be repugnant to truth?


[[job-22]]
== Chapter 22

[[job-22-1]]
^1^ Then Eliphaz the Themanite responded by saying:

[[job-22-2]]
^2^ Can man be compared with God, even if he were perfect in knowledge?

[[job-22-3]]
^3^ What advantage is it to God, if you were just? Or what do you provide for him, if your way should be immaculate?

[[job-22-4]]
^4^ Will he reprove you and take you to judgment for being afraid,

[[job-22-5]]
^5^ and not because of your many evil deeds and your infinite unfairness?

[[job-22-6]]
^6^ For you have taken away the collateral of your brothers without cause, and stripped them naked of their clothing.

[[job-22-7]]
^7^ You have not given water to the weary; you have taken bread away from the hungry.

[[job-22-8]]
^8^ By the strength of your arm, you took possession of the land, and you retain it by being the strongest.

[[job-22-9]]
^9^ You have sent widows away empty, and you have crushed the shoulders of orphans.

[[job-22-10]]
^10^ Because of this, you are surrounded by traps, and unexpected fears will disturb you.

[[job-22-11]]
^11^ And did you think that you would not see darkness and that you were not to be overwhelmed by the onrush of overflowing waters?

[[job-22-12]]
^12^ Have you not considered that God is higher than the heavens and is lifted above the height of the stars?

[[job-22-13]]
^13^ And you say: “Well, what does God know?” and, “He judges, as if through a fog,”

[[job-22-14]]
^14^ and, “The clouds are his hiding-place,” and, “He does not examine us closely,” and, “He makes his rounds at the limits of the heavens.”

[[job-22-15]]
^15^ Do you not want to tend the path of the ages, which wicked men have spurned?

[[job-22-16]]
^16^ These were taken away before their time, and a flood overthrew their foundation.

[[job-22-17]]
^17^ They said to God, “Withdraw from us,” and they treated the Almighty as if he could do nothing,

[[job-22-18]]
^18^ though he had filled their houses with good things. May their way of thinking be far from me.

[[job-22-19]]
^19^ The just will see and will rejoice, and the innocent will mock them.

[[job-22-20]]
^20^ Has not their haughtiness been cut down, and has not fire devoured the remnants of them?

[[job-22-21]]
^21^ So, repose yourself with him and be at peace, and, in this way, you will have the best fruits.

[[job-22-22]]
^22^ Accept the law from his mouth, and place his words in your heart.

[[job-22-23]]
^23^ If you will return to the Almighty, you will be rebuilt, and you will put sinfulness far from your tabernacle.

[[job-22-24]]
^24^ He will give you stone in place of dirt, and torrents of gold in place of stone.

[[job-22-25]]
^25^ And the Almighty will be against your enemies, and silver will be gathered together for you.

[[job-22-26]]
^26^ Then will you flock together in delight over the Almighty, and you will lift up your face to God.

[[job-22-27]]
^27^ You will plead with him, and he will listen to you, and you will pay your vows.

[[job-22-28]]
^28^ You will decide on something, and it will come to you, and the light will shine in your ways.

[[job-22-29]]
^29^ For he who had been humbled, will be in glory; and he who will lower his eyes, will be the one saved.

[[job-22-30]]
^30^ The innocent will be saved, and he will be saved with purity in his hands.


[[job-23]]
== Chapter 23

[[job-23-1]]
^1^ Then Job answered by saying:

[[job-23-2]]
^2^ Now again my conversation is in bitterness, and the force of my scourging weighs more heavily on me because of my mourning.

[[job-23-3]]
^3^ Who will grant me that I might know and find him, and that I may approach even to his throne?

[[job-23-4]]
^4^ I would place judgment before his eye, and my mouth would fill with criticism,

[[job-23-5]]
^5^ so that I may know the words that he will answer me and understand what he will say to me.

[[job-23-6]]
^6^ I do not want him to contend with me with much strength, nor to overwhelm me with the bulk of his greatness.

[[job-23-7]]
^7^ Let him show fairness in response to me, and let my judgment reach to victory.

[[job-23-8]]
^8^ If I go to the east, he does not appear; if I go to the west, I will not understand him.

[[job-23-9]]
^9^ If I turn to the left, what can I do? I will not take hold of him. If I turn myself to the right, I will not see him.

[[job-23-10]]
^10^ Truly, he knows my way and has tested me like gold that passes through fire.

[[job-23-11]]
^11^ My feet have been following his footsteps; I have kept to his way and have not strayed from it.

[[job-23-12]]
^12^ I have not withdrawn from the commands of his lips, and the words of his mouth I have hidden in my sinews.

[[job-23-13]]
^13^ For he is alone, and no one is able to disturb his intention; and whatever his spirit wills, that he accomplishes.

[[job-23-14]]
^14^ And when he fulfills his will in me, many other similar ones will also be present with him.

[[job-23-15]]
^15^ And, for this reason, I have been troubled at his presence, and, when I consider him, I am approached by fear.

[[job-23-16]]
^16^ God has weakened my heart, and the Almighty has confused me.

[[job-23-17]]
^17^ Yet I have not perished because of the threatening darkness, nor has gloom covered my face.


[[job-24]]
== Chapter 24

[[job-24-1]]
^1^ The times are not hidden from the Almighty; even those who know him, do not know his days.

[[job-24-2]]
^2^ Some have crossed the boundaries, plundered the flocks, and given them pasture.

[[job-24-3]]
^3^ They have driven away the donkey of orphans, and have taken the cow from the widow as collateral.

[[job-24-4]]
^4^ They have undermined the way of the poor, and have pressed together the meek of the earth.

[[job-24-5]]
^5^ Others, like wild asses in the desert, go forth to their work; by watching for prey, they obtain bread for their children.

[[job-24-6]]
^6^ They reap a field that is not their own, and they harvest a vineyard that they have taken by force.

[[job-24-7]]
^7^ They send men away naked, having taken the clothing of those who have no covering in the cold;

[[job-24-8]]
^8^ these are wet with the mountain rain, and, having no covering, they embrace the rocks.

[[job-24-9]]
^9^ They have used violence to deprive orphans, and they have robbed the poor common people.

[[job-24-10]]
^10^ From the naked and those who do not have enough clothing, and from the hungry, they have taken away sheaves of grain.

[[job-24-11]]
^11^ They take their midday rest among the stockpiles of those who, though they have trodden the winepresses, suffer thirst.

[[job-24-12]]
^12^ In the cities, they caused the men to groan and the spirit of the wounded to cry out, and so God does not allow this to go unpunished.

[[job-24-13]]
^13^ They have been rebellious against the light; they have not known his ways, nor have they returned by his paths.

[[job-24-14]]
^14^ The killer of men rises at first light; he executes the destitute and the poor, but, in truth, he is like a thief in the night.

[[job-24-15]]
^15^ The eye of the adulterer waits for darkness, saying, “No eye will see me,” and he covers his face.

[[job-24-16]]
^16^ He passes through houses in the nighttime, just as they had agreed among themselves in the daytime; and they are ignorant of the light.

[[job-24-17]]
^17^ If sunrise should suddenly appear, it is treated by them like the shadow of death; and they walk in darkness, as if in light.

[[job-24-18]]
^18^ He is nimble on the surface of water. His place on land is to be accursed. May he not walk by way of the vineyards.

[[job-24-19]]
^19^ May he cross from the snowy waters to excessive heat, and his sin, all the way to hell.

[[job-24-20]]
^20^ Let mercy forget him. His charm is worms. Let him not be remembered, but instead be broken like an unfruitful tree.

[[job-24-21]]
^21^ For he has fed on the barren, who does not bear fruit, and he has not done good to the widow.

[[job-24-22]]
^22^ He has pulled down the strong by his strength, and, when he stands up, he will not have trust in his life.

[[job-24-23]]
^23^ God has given him a place for repentance, and he abuses it with arrogance, but his eyes are upon his ways.

[[job-24-24]]
^24^ They are lifted up for a little while, but they will not continue, and they will be brought low, just like all things, and they will be taken away, and, like the tops of the ears of grain, they will be crushed.

[[job-24-25]]
^25^ But, if this is not so, who is able to prove to me that I have lied and to place my words before God?


[[job-25]]
== Chapter 25

[[job-25-1]]
^1^ Then Baldad the Suhite answered by saying:

[[job-25-2]]
^2^ Power and terror are with him that makes a pact with those in high places.

[[job-25-3]]
^3^ Is there any limit to the number of his soldiers or to the number of those over whom his light rises?

[[job-25-4]]
^4^ Is it right for man to compare himself to God, or to appear pure though he is born of woman?

[[job-25-5]]
^5^ Behold, even the moon is not radiant, and the stars are not pure, in his sight.

[[job-25-6]]
^6^ Is man much more than rottenness and the son of man much more than worms?


[[job-26]]
== Chapter 26

[[job-26-1]]
^1^ Then Job responded by saying:

[[job-26-2]]
^2^ Whose assistant are you? Is he weak-minded? And do you sustain the arm of him that is not strong?

[[job-26-3]]
^3^ To whom have you given advice? Perhaps it is to him that has no wisdom or prudence that you have revealed your many ideas.

[[job-26-4]]
^4^ Who is it that you wanted to teach? Was it not him that created the breath of life?

[[job-26-5]]
^5^ Behold, giant things groan under the waters, and they dwell with them.

[[job-26-6]]
^6^ The underworld is naked before him, and there is no covering for perdition.

[[job-26-7]]
^7^ He stretched out the North over emptiness, and he suspended the land over nothing.

[[job-26-8]]
^8^ He secures the waters in his clouds, so that they do not burst forth downward all at once.

[[job-26-9]]
^9^ He holds back the face of his throne, and he stretches his cloud over it.

[[job-26-10]]
^10^ He has set limits around the waters, until light and darkness shall reach their limit.

[[job-26-11]]
^11^ The pillars of heaven tremble and are frightened at his nod.

[[job-26-12]]
^12^ By his strength, the seas suddenly gather together, and his foresight has struck the arrogant.

[[job-26-13]]
^13^ His spirit has adorned the heavens, and his birthing hand has brought forth the winding serpent.

[[job-26-14]]
^14^ Behold, these things have been said about his ways in part, and, since we barely have heard a small drop of his word, who will be able to gaze upon the thunder of his greatness?


[[job-27]]
== Chapter 27

[[job-27-1]]
^1^ Job also added to this, using figures of speech, and he said:

[[job-27-2]]
^2^ As God lives, who has taken away my judgment, and the Almighty, who has led my soul to bitterness,

[[job-27-3]]
^3^ as long as my breath remains in me and the breath of God remains in my nostrils,

[[job-27-4]]
^4^ my lips will not speak iniquity, nor will my tongue devise lies.

[[job-27-5]]
^5^ Far be it from me that I should judge you to be right, for, until I expire, I will not withdraw from my innocence.

[[job-27-6]]
^6^ I will not forsake my justification, which I have just begun to grasp, for my heart does not find blame for me in my whole life.

[[job-27-7]]
^7^ Let the impious be as my enemy, and the sinful, as my adversary.

[[job-27-8]]
^8^ For what hope is there for the hypocrite, if he greedily plunders and God does not free his soul?

[[job-27-9]]
^9^ Will God pay attention to his cry, when anguish overcomes him?

[[job-27-10]]
^10^ Or will he take delight in the Almighty and call upon God at all times?

[[job-27-11]]
^11^ I will teach you through the hand of God, what the Almighty holds, and I will not conceal it.

[[job-27-12]]
^12^ Behold, you know all this, and so why do you speak vain things without a reason?

[[job-27-13]]
^13^ This is the portion of the impious man with God, and the inheritance of the violent, which they will receive from the Almighty.

[[job-27-14]]
^14^ If his sons should happen to increase, they will be for the sword, and his grandsons will not be satisfied with bread.

[[job-27-15]]
^15^ Whatever will remain of him will be buried in the ruins, and his widows will not weep.

[[job-27-16]]
^16^ If he will amass silver as if it were dirt and fabricate garments as if they were clay,

[[job-27-17]]
^17^ then yes, he will gather, but the just will be clothed with it and the innocent will divide the silver.

[[job-27-18]]
^18^ He has built his house like a moth, and he has made a makeshift shelter like a sentry.

[[job-27-19]]
^19^ When he falls asleep, the rich man will leave him with nothing; he will open his eyes and find nothing.

[[job-27-20]]
^20^ Destitution will surround him like water; a storm will overwhelm him in the night.

[[job-27-21]]
^21^ A burning wind will pick him up and carry him away, and, like a whirlwind, it will rush him from his place.

[[job-27-22]]
^22^ And it will hurl over him and will not spare him; fleeing from its power, he will go into exile.

[[job-27-23]]
^23^ He will clasp his hands over himself, and he will hiss at himself, while considering his situation.


[[job-28]]
== Chapter 28

[[job-28-1]]
^1^ Silver has its fissures where it is first found, and gold has a place where it is melted.

[[job-28-2]]
^2^ Iron is taken from the earth, and ore, unbound by heat, is turned into brass.

[[job-28-3]]
^3^ He has established a time for darkness, and he has settled on an end for all things, as well as for the stone that is in the gloom and shadow of death.

[[job-28-4]]
^4^ The burning separates a pilgrim people from those who have been forgotten by the feet of the destitute man and from the unapproachable.

[[job-28-5]]
^5^ The land, where bread appeared in its place, has been destroyed by fire.

[[job-28-6]]
^6^ Its stones are embedded with sapphires, and its soil, with gold.

[[job-28-7]]
^7^ The bird does not know its path, nor has the eye of the vulture beheld it.

[[job-28-8]]
^8^ The sons of merchants have not walked there, nor has the lioness traveled through it.

[[job-28-9]]
^9^ He has stretched out his hand to the rocks; he has overturned the foundations of the mountains.

[[job-28-10]]
^10^ He has cut rivers through the rocks, and his eye has seen all precious things.

[[job-28-11]]
^11^ The depths of rivers he has also examined, and he has brought hidden things into the light.

[[job-28-12]]
^12^ But, in truth, where is wisdom to be found, and where is the place of understanding?

[[job-28-13]]
^13^ Man does not know its price, nor is it found in the land of those who live in sweetness.

[[job-28-14]]
^14^ The abyss declares, “It is not in me.” And the sea says, “It is not with me.”

[[job-28-15]]
^15^ The finest gold will not be paid for it, nor will silver be weighed in exchange for it.

[[job-28-16]]
^16^ It will not be compared with the dyed colors of India, nor with the very costly stone sardonyx, nor with the sapphire.

[[job-28-17]]
^17^ Neither gold nor crystal will be its equal; neither will vessels of gold be fitted for it.

[[job-28-18]]
^18^ The exalted and the eminent will not be remembered in comparison with it. Yet wisdom is drawn out of concealment.

[[job-28-19]]
^19^ The topaz of Ethiopia will not be equal to it, nor will it be compared to the purest dyes.

[[job-28-20]]
^20^ So then, where does wisdom begin, and where is the place of understanding?

[[job-28-21]]
^21^ It has been hidden from the eyes of all living things, just as the birds of the heavens escape notice.

[[job-28-22]]
^22^ Perdition and death have said, “With our ears, we have heard its fame.”

[[job-28-23]]
^23^ God understands its way, and he knows its location.

[[job-28-24]]
^24^ For he beholds the limits of the world, and he looks upon all things that are under heaven.

[[job-28-25]]
^25^ He created a counterweight for the winds, and he suspended the waters to measure them.

[[job-28-26]]
^26^ At that time, he gave a law to the rain and a path to the resounding storms.

[[job-28-27]]
^27^ Then he saw and explained it, and he made ready and examined it.

[[job-28-28]]
^28^ And he said to man, “Behold the fear of the Lord. Such is wisdom. And to withdraw from evil, this is understanding.”


[[job-29]]
== Chapter 29

[[job-29-1]]
^1^ Job also added to this, using figures of speech, and he said:

[[job-29-2]]
^2^ Who will grant to me that I might be as I was in former months, according to the days when God kept watch over me?

[[job-29-3]]
^3^ At that time, his lamp shined over my head, and by his light, I walked through the darkness.

[[job-29-4]]
^4^ I was then just as in the days of my youth, when God was privately in my tabernacle.

[[job-29-5]]
^5^ At that time, the Almighty was with me and my children surrounded me.

[[job-29-6]]
^6^ Then, I washed my feet with butter, and a boulder poured out rivers of oil for me.

[[job-29-7]]
^7^ When I went to the gate of the city, or to the main street, they prepared a chair for me.

[[job-29-8]]
^8^ The youths saw me and hid themselves, and the elders, rising up, remained standing.

[[job-29-9]]
^9^ The leaders stopped talking, and they placed a finder over their mouth.

[[job-29-10]]
^10^ The commanders subdued their voice, and their tongue adhered to their throat.

[[job-29-11]]
^11^ The ear that heard me, blessed me, and the eye that saw me, gave testimony for me.

[[job-29-12]]
^12^ This was because I had freed the poor, who cried out, and the orphan, who had no helper.

[[job-29-13]]
^13^ The blessing of him who would have been destroyed came upon me, and I consoled the heart of the widow.

[[job-29-14]]
^14^ I put on justice, and I clothed myself with my judgment, like a robe and a diadem.

[[job-29-15]]
^15^ I was an eye for the blind and a foot for the lame.

[[job-29-16]]
^16^ I was the father of the poor; and if I lacked knowledge about any case, I investigated very diligently.

[[job-29-17]]
^17^ I crushed the jaws of the impious, and I took away prey from his teeth.

[[job-29-18]]
^18^ And I said, “I will die in my little nest, and like a palm tree, I will multiply my days.

[[job-29-19]]
^19^ My root has been spread beside the waters, and the dew will remain with my harvest.

[[job-29-20]]
^20^ My glory will always be restored, and my bow will be restored to my hand.”

[[job-29-21]]
^21^ Those who heard me, expected vindication, and they listened closely in silence to my counsel.

[[job-29-22]]
^22^ To my words, they dared to add nothing, and my eloquence poured over them.

[[job-29-23]]
^23^ They waited for me as for rain, and they opened their mouth as for belated rains.

[[job-29-24]]
^24^ If I had ever laughed at them, they would not have believed it, and the light of my face was not cast down towards the ground.

[[job-29-25]]
^25^ If I wished to go to them, I sat down first, and, though I sat like a king surrounded by an army, yet I was a comforter to those who mourned.


[[job-30]]
== Chapter 30

[[job-30-1]]
^1^ But now, those younger in years scorn me, whose fathers I would not have seen fit to place with the dogs of my flock,

[[job-30-2]]
^2^ the strength of whose hands was nothing to me, and they were considered unworthy of life itself.

[[job-30-3]]
^3^ They were barren from poverty and hunger; they gnawed in solitude, layered with misfortune and misery.

[[job-30-4]]
^4^ And they chewed grass and the bark from trees, and the root of junipers was their food.

[[job-30-5]]
^5^ They took these things from the steep valleys, and when they discovered one of these things, they rushed to the others with a cry.

[[job-30-6]]
^6^ They lived in the parched desert and in caves underground or above the rocks.

[[job-30-7]]
^7^ They rejoiced among these kinds of things, and they considered it delightful to be under thorns.

[[job-30-8]]
^8^ These are the sons of foolish and base men, not even paying any attention to the land.

[[job-30-9]]
^9^ Now I become their song, and I have been made into their proverb.

[[job-30-10]]
^10^ They loathe me, and so they flee far from me, and they are not reluctant to spit in my face.

[[job-30-11]]
^11^ For he has opened his quiver and has afflicted me, and he has placed a bridle in my mouth.

[[job-30-12]]
^12^ Immediately, upon rising, my calamities rise up to the right. They have overturned my feet and have pressed me down along their way like waves.

[[job-30-13]]
^13^ They have diverted my journeys; they have waited to ambush me, and they have prevailed, and there was no one who might bring help.

[[job-30-14]]
^14^ They have rushed upon me, as when a wall is broken or a gate opened, and they have been pulled down into my miseries.

[[job-30-15]]
^15^ I have been reduced to nothing. You have taken away my desire like a wind, and my health has passed by like a cloud.

[[job-30-16]]
^16^ But now my soul withers within myself, and the days of affliction take hold of me.

[[job-30-17]]
^17^ At night, my bone is pierced with sorrows, and those who feed on me, do not sleep.

[[job-30-18]]
^18^ By the sheer number of them my clothing is worn away, and they have closed in on me like the collar of my coat.

[[job-30-19]]
^19^ I have been treated like dirt, and I have been turned into embers and ashes.

[[job-30-20]]
^20^ I cry to you, and you do not heed me. I stand up, and you do not look back at me.

[[job-30-21]]
^21^ You have changed me into hardness, and, with the hardness of your hand, you oppose me.

[[job-30-22]]
^22^ You have lifted me up, and, placing me as if on the wind, you have thrown me down powerfully.

[[job-30-23]]
^23^ I know that you will hand me over to death, where a home has been established for all the living.

[[job-30-24]]
^24^ Truly, then, you do not extend your hand in order to consume them, and if they fall down, you will save them.

[[job-30-25]]
^25^ Once, I wept over him who was afflicted, and my soul had compassion on the poor.

[[job-30-26]]
^26^ I expected good things, but evil things have come to me. I stood ready for light, yet darkness burst forth.

[[job-30-27]]
^27^ My insides have seethed, without any rest, for the days of affliction have prevented it.

[[job-30-28]]
^28^ I went forth mourning, without anger, and rising up, I cried out in confusion.

[[job-30-29]]
^29^ I was the brother of snakes, and the companion of ostriches.

[[job-30-30]]
^30^ My skin has become blackened over me, and my bones have dried up because of the heat.

[[job-30-31]]
^31^ My harp has been turned into mourning, and my pipes have been turned into a voice of weeping.


[[job-31]]
== Chapter 31

[[job-31-1]]
^1^ I reached an agreement with my eyes, that I would not so much as think about a virgin.

[[job-31-2]]
^2^ For what portion should God from above hold for me, and what inheritance should the Almighty from on high keep?

[[job-31-3]]
^3^ Is not destruction held for the wicked and repudiation kept for those who work injustice?

[[job-31-4]]
^4^ Does he not examine my ways and number all my steps?

[[job-31-5]]
^5^ If I have walked in vanity, or if my foot has hurried towards deceitfulness,

[[job-31-6]]
^6^ let him weigh me in a just balance, and let God know my simplicity.

[[job-31-7]]
^7^ If my steps have turned aside from the way, or if my heart has followed my eyes, or if a blemish has clung to my hands,

[[job-31-8]]
^8^ then may I sow, and let another consume, and let my offspring be eradicated.

[[job-31-9]]
^9^ If my heart has been deceived over a woman, or if I have waited in ambush at my friend’s door,

[[job-31-10]]
^10^ then let my wife be the harlot of another, and let other men lean over her.

[[job-31-11]]
^11^ For this is a crime and a very great injustice.

[[job-31-12]]
^12^ It is a fire devouring all the way to perdition, and it roots out all that springs forth.

[[job-31-13]]
^13^ If I have despised being subject to judgment with my servant or my maid, when they had any complaint against me,

[[job-31-14]]
^14^ then what will I do when God rises to judge, and, when he inquires, how will I respond to him?

[[job-31-15]]
^15^ Is not he who created me in the womb, also he who labored to make him? And did not one and the same form me in the womb?

[[job-31-16]]
^16^ If I have denied the poor what they wanted and have made the eyes of the widow wait;

[[job-31-17]]
^17^ if I have eaten my morsel of food alone, while orphans have not eaten from it;

[[job-31-18]]
^18^ (for from my infancy mercy grew with me, and it came out with me from my mother’s womb;)

[[job-31-19]]
^19^ if I have looked down on him who was perishing because he had no clothing and the poor without any covering,

[[job-31-20]]
^20^ if his sides have not blessed me, and if he were not warmed with the fleece of my sheep;

[[job-31-21]]
^21^ if I have lifted up my hand over an orphan, even when it might seem to me that I have the advantage over him at the gate;

[[job-31-22]]
^22^ then may my shoulder fall from its joint, and may my arm, with all its bones, be broken.

[[job-31-23]]
^23^ For I have always feared God, like waves flowing over me, whose weight I was unable to bear.

[[job-31-24]]
^24^ If I have considered gold to be my strength, or if I have called purified gold ‘my Trust;’

[[job-31-25]]
^25^ if I have rejoiced over my great success, and over the many things my hand has obtained;

[[job-31-26]]
^26^ if I gazed upon the sun when it shined and the moon advancing brightly,

[[job-31-27]]
^27^ so that my heart rejoiced in secret and I kissed my hand with my mouth,

[[job-31-28]]
^28^ which is a very great iniquity and a denial against the most high God;

[[job-31-29]]
^29^ if I have been glad at the ruin of him who hated me and have exulted that evil found him,

[[job-31-30]]
^30^ for I have not been given my throat to sin by asking for a curse on his soul;

[[job-31-31]]
^31^ if the men around my tabernacle have not said: “He might give us some of his food, so that we will be filled,”

[[job-31-32]]
^32^ for the foreigner did not remain at the door, my door was open to the traveler;

[[job-31-33]]
^33^ if, as man does, I have hidden my sin and have concealed my iniquity in my bosom;

[[job-31-34]]
^34^ if I became frightened by an excessive crowd, and the disrespect of close relatives alarmed me, so that I would much rather have remained silent or have gone out the door;

[[job-31-35]]
^35^ then, would he grant me a hearing, so that the Almighty would listen to my desire, and he who judges would himself write a book,

[[job-31-36]]
^36^ which I would then carry on my shoulder and wrap around me like a crown?

[[job-31-37]]
^37^ With each of my steps, I would pronounce and offer it, as if to a prince.

[[job-31-38]]
^38^ So, if my land cries out against me, and if its furrows weep with it,

[[job-31-39]]
^39^ if I have used its fruits for nothing but money and have afflicted the souls of its tillers,

[[job-31-40]]
^40^ then, may thistles spring forth for me instead of grain, and thorns instead of barley. (This ended the words of Job.)


[[job-32]]
== Chapter 32

[[job-32-1]]
^1^ But these three men ceased to answer Job, because he considered himself justified.

[[job-32-2]]
^2^ And Eliu the son of Barachel the Buzite, of the kindred of Ram, was angry and indignant. But he was angry against Job because he described himself to be just in the presence of God.

[[job-32-3]]
^3^ Moreover, he was indignant with his friends because they had not found a reasonable response, except in so far as they condemned Job.

[[job-32-4]]
^4^ Therefore, Eliu waited while Job was talking, for these were his elders that were speaking.

[[job-32-5]]
^5^ But when he saw that these three were not able to respond, he was extremely angry.

[[job-32-6]]
^6^ And so Eliu the son of Barachel the Buzite responded by saying: I am younger in years, and you are more ancient; therefore, I kept my head low, for I was afraid to reveal to you my opinion.

[[job-32-7]]
^7^ For I had hoped that greater age would speak, and that a multitude of years would teach wisdom.

[[job-32-8]]
^8^ But I see now that there is only breath in men, and that it is the inspiration of the Almighty that gives understanding.

[[job-32-9]]
^9^ The wise are not the aged, nor do the elders understand judgment.

[[job-32-10]]
^10^ Therefore, I will speak. Listen to me, and so I will show you my wisdom.

[[job-32-11]]
^11^ For I have endured your words; I have paid attention to your deliberations, while you were being argumentative with words.

[[job-32-12]]
^12^ And as long as I supposed that you were saying something, I considered; but now I see that there is none of you that is able to argue with Job and to respond to his words.

[[job-32-13]]
^13^ So that you will not say, “We have found wisdom,” God has thrown him down, not man.

[[job-32-14]]
^14^ He has said nothing to me, and I will not respond to him according to your words.

[[job-32-15]]
^15^ Then they were filled with dread, and so they no longer responded, and they withdrew from their speechmaking.

[[job-32-16]]
^16^ Therefore, because I have waited and they have not been speaking, for they stood firm and did not respond at all,

[[job-32-17]]
^17^ I also will answer in my turn, and I will reveal my knowledge.

[[job-32-18]]
^18^ For I am full of words, and the feeling in my gut inspires me.

[[job-32-19]]
^19^ Yes, my stomach is like fermenting wine without a vent, which bursts the new containers.

[[job-32-20]]
^20^ I should speak, but I will also breathe a little; I will open my lips, and I will answer.

[[job-32-21]]
^21^ I will not esteem the reputation of a man, and I will not equate God with man.

[[job-32-22]]
^22^ For I do not know how long I will continue, and whether, after a while, my Maker might take me away.


[[job-33]]
== Chapter 33

[[job-33-1]]
^1^ Therefore, hear my speeches, Job, and listen to all my words.

[[job-33-2]]
^2^ Behold, I have opened my mouth; let my tongue speak along with my throat.

[[job-33-3]]
^3^ My words are from my simple heart, and my lips will speak a pure judgment.

[[job-33-4]]
^4^ The Spirit of God made me, and the breath of the Almighty gave me life.

[[job-33-5]]
^5^ If you can, answer me, and oppose me to my face.

[[job-33-6]]
^6^ Behold, God has made me, just as he also has made you, and I, likewise, have been formed of the same clay.

[[job-33-7]]
^7^ So, truly, do not let my wonders terrify you, and do not let my eloquence be burdensome to you.

[[job-33-8]]
^8^ For you have spoken in my hearing, and I have heard the voice of your words, saying:

[[job-33-9]]
^9^ “I am clean and without sin; I am immaculate, and there is no iniquity in me.

[[job-33-10]]
^10^ Yet he has discovered blame in me, and so he has treated me like his enemy.

[[job-33-11]]
^11^ He has put my feet in fetters; he has kept watch over all my ways.”

[[job-33-12]]
^12^ Therefore, it is for this reason that you have not been justified. For I tell you that God is greater than man.

[[job-33-13]]
^13^ Do you contend against him because he has not responded to all of your words?

[[job-33-14]]
^14^ God speaks once, and he does not repeat the same thing a second time.

[[job-33-15]]
^15^ Through a dream in a vision of the night, when a deep sleep falls over men, and they are sleeping in their beds,

[[job-33-16]]
^16^ then, he opens the ears of men, and, educating them, he teaches discipline,

[[job-33-17]]
^17^ so that he may divert a man from the things that he is doing, and may free him from pride,

[[job-33-18]]
^18^ rescuing his soul from corruption and his life from passing away by the sword.

[[job-33-19]]
^19^ Likewise, he rebukes by sorrow in bed, and he causes all of his bones to become weak.

[[job-33-20]]
^20^ Bread becomes abominable to him in his life, and, to his soul, the meat which before he desired.

[[job-33-21]]
^21^ His body will waste away, and his bones, which had been covered, will be revealed.

[[job-33-22]]
^22^ His soul has approached corruption, and his life has drawn near to what is deadly.

[[job-33-23]]
^23^ If there were an angel speaking for him, one among thousands, to declare the fairness of the man,

[[job-33-24]]
^24^ he will have mercy on him, and he will say, “Free him, so that he will not descend to destruction. I have found a reason to be favorable to him.

[[job-33-25]]
^25^ His body is consumed by suffering. Let him return to the days of his youth.”

[[job-33-26]]
^26^ He will beg pardon from God, and he will be soothing to him; and he will look upon his face in jubilation, and he will restore his justice to man.

[[job-33-27]]
^27^ He will consider mankind, and he will say: “I have sinned and truly I have offended, yet I was not treated as I deserved.”

[[job-33-28]]
^28^ He has freed his soul from continuing into destruction, so that, in living, it may see the light.

[[job-33-29]]
^29^ Behold, all these things God works three times within each one,

[[job-33-30]]
^30^ so that he may revive their souls from corruption and enlighten them with the light of life.

[[job-33-31]]
^31^ Pay attention Job, and listen to me; and remain silent, while I speak.

[[job-33-32]]
^32^ Yet, if you have anything to say, answer me and speak, for I want you to be treated justly.

[[job-33-33]]
^33^ But if you do not have anything to say, then listen to me. Be quiet and I will teach you wisdom.


[[job-34]]
== Chapter 34

[[job-34-1]]
^1^ After proclaiming these things, Eliu now had this to say:

[[job-34-2]]
^2^ May the wise hear my words, and may the educated listen to me.

[[job-34-3]]
^3^ For the ear examines words, and the mouth discerns foods by the taste.

[[job-34-4]]
^4^ Let us choose judgment for ourselves, and let us consider among ourselves what is best.

[[job-34-5]]
^5^ For Job has said: “I am just, yet God has subverted my judgment.

[[job-34-6]]
^6^ For, within my judgment, there is a lie: my vehement barbs are without any sin.”

[[job-34-7]]
^7^ What man is there that is like Job, who drinks up derision as if it were water,

[[job-34-8]]
^8^ who accompanies those who work iniquity, and who walks with impious men?

[[job-34-9]]
^9^ For he has said, “Man will not please God, even if he should travel with him.”

[[job-34-10]]
^10^ Therefore, prudent men, hear me: impiety is far from God, and iniquity is far from the Almighty.

[[job-34-11]]
^11^ For he will restore to man his works, and according to the ways of each, he will repay them.

[[job-34-12]]
^12^ For truly, God will not condemn in vain, nor will the Almighty repudiate judgment.

[[job-34-13]]
^13^ What other is established over the earth? Or whom has he placed over the world, which he made?

[[job-34-14]]
^14^ But, if he directs his heart towards him, he will draw his spirit and breath to himself.

[[job-34-15]]
^15^ All flesh will fail together, and man will return to ashes.

[[job-34-16]]
^16^ Therefore, if you have understanding, hear what is said, and heed the sound of my eloquence.

[[job-34-17]]
^17^ Is he that does not love judgment able to be corrected? And how can you so greatly condemn him who is just?

[[job-34-18]]
^18^ He says to the king, “You are an apostate.” He calls commanders impious.

[[job-34-19]]
^19^ He does not accept the reputation of leaders; nor does he recognize the tyrant as he contends against the poor. For all are the work of his hands.

[[job-34-20]]
^20^ They will die suddenly, and the people will be troubled in the middle of the night, but they will pass through it, and the violent will be taken away without a hand.

[[job-34-21]]
^21^ For his eyes are upon the ways of men, and he examines all of their steps.

[[job-34-22]]
^22^ There is no darkness and no shadow of death, where those who work iniquity may be hidden.

[[job-34-23]]
^23^ For it is no longer within the power of man to enter into judgment with God.

[[job-34-24]]
^24^ He will break into many innumerable pieces, and he will cause others to stand up in their place.

[[job-34-25]]
^25^ For he knows their works, and, as a result, he will bring the night, and they will be crushed.

[[job-34-26]]
^26^ Just as the impious do, he has struck them in a place where they can be seen.

[[job-34-27]]
^27^ They, as if with great diligence, have withdrawn from him, and they refused to understand all his ways,

[[job-34-28]]
^28^ so that they caused the outcry of the needy to reach him, and he heard the voice of the poor.

[[job-34-29]]
^29^ For, when he grants peace, who is there that can condemn? When he hides his face, who is there that can contemplate him, either among the nations, or among all men?

[[job-34-30]]
^30^ He causes a hypocritical man to reign because of the sins of the people.

[[job-34-31]]
^31^ Therefore, since I have been speaking about God, I will not prevent you from doing the same.

[[job-34-32]]
^32^ If I have erred, you may teach me; if I have spoken unfairly, I will add no more.

[[job-34-33]]
^33^ Does God require this of you because it is displeasing to you? For you were the first to speak, and not I. But if you know something better, speak.

[[job-34-34]]
^34^ Let men of understanding speak to me, and let a wise man listen to me.

[[job-34-35]]
^35^ But Job has been speaking foolishly, and his words contain unsound teaching.

[[job-34-36]]
^36^ My father, let Job be tested even to the end; may you not retreat from a man of iniquity.

[[job-34-37]]
^37^ For he adds blasphemy on top of his sins; nevertheless, let him be constrained to be among us, and then let him provoke God to judgment with his speeches.


[[job-35]]
== Chapter 35

[[job-35-1]]
^1^ After this, Eliu again spoke in this way:

[[job-35-2]]
^2^ Does it seem right to you in your thoughts, that you should say, “I am more just than God?”

[[job-35-3]]
^3^ For you said, “Having done what is right does not please you,” and, “How will it benefit you, if I sin?”

[[job-35-4]]
^4^ And so, I will respond to your words, and to your friends who are with you.

[[job-35-5]]
^5^ Look up towards heaven and consider; also, think about the sky, which is higher than you.

[[job-35-6]]
^6^ If you sin, how will it hurt him? And if your iniquities are multiplied, what will you do against him?

[[job-35-7]]
^7^ Furthermore, if you act justly, what will you give him, or what will he receive from your hand?

[[job-35-8]]
^8^ Your impiety may hurt a man who is like you, though your justice may help the son of the man.

[[job-35-9]]
^9^ Because of the multitude of false accusers, they will cry out; and they will lament because of the strong arm of the tyrants.

[[job-35-10]]
^10^ Yet he has not said: “Where is God, who made me, who has given songs in the night,

[[job-35-11]]
^11^ who teaches us in addition to the beasts of the earth, and who educates us along with the birds of the air?”

[[job-35-12]]
^12^ There they will cry, and he will not heed them, because of the arrogance of the wicked.

[[job-35-13]]
^13^ Therefore, God does not hear in vain, and the Almighty will look into each and every case.

[[job-35-14]]
^14^ And so, when you say, “He does not examine,” be judged before him, but wait for him.

[[job-35-15]]
^15^ For, at the present time, he does not bring forth his fury, nor does he punish sin exceedingly.

[[job-35-16]]
^16^ Therefore, Job has opened his mouth in vain and has multiplied words without knowledge.


[[job-36]]
== Chapter 36

[[job-36-1]]
^1^ Continuing in a similar manner, Eliu had this to say:

[[job-36-2]]
^2^ Bear with me for a little while and I will show you; for I have still more to say in favor of God.

[[job-36-3]]
^3^ I will review my knowledge from the beginning, and I will prove my Maker to be just.

[[job-36-4]]
^4^ For truly my words are without any falsehood and perfect knowledge will be proven to you.

[[job-36-5]]
^5^ God does not abandon the powerful, for he himself is also powerful.

[[job-36-6]]
^6^ But he does not save the impious, though he grants judgment to the poor.

[[job-36-7]]
^7^ He will not take his eyes away from the just, and he continually establishes kings on their throne, and they are exalted.

[[job-36-8]]
^8^ And, if they are in captivity, or are bound with the chains of poverty,

[[job-36-9]]
^9^ he will reveal to them their works, as well as their sinfulness, in that they were violent.

[[job-36-10]]
^10^ Likewise, he will open their ears to his correction, and he will speak to them, so that they may return from iniquity.

[[job-36-11]]
^11^ If they listen and obey, they will fill their days with goodness and complete their years in glory.

[[job-36-12]]
^12^ But if they will not listen, they will pass away by the sword and will be consumed by foolishness.

[[job-36-13]]
^13^ The false and the crafty provoke the wrath of God, yet they do not cry out to him when they are chained.

[[job-36-14]]
^14^ Their soul will die in a storm, and their life, among the unmanly.

[[job-36-15]]
^15^ He will rescue the poor from his anguish, and he will open his ear during tribulation.

[[job-36-16]]
^16^ Therefore, he will save you from the narrow mouth very widely, even though it has no foundation under it. Moreover, your respite at table will be full of fatness.

[[job-36-17]]
^17^ Your case has been judged like that of the impious; you will withdraw your plea and your judgment.

[[job-36-18]]
^18^ Therefore, do not let anger overwhelm you so that you oppress another; neither should you allow a multitude of gifts to influence you.

[[job-36-19]]
^19^ Lay down your greatness without distress, and put aside all of your power with courage.

[[job-36-20]]
^20^ Do not prolong the night, even if people rise on their behalf.

[[job-36-21]]
^21^ Be careful that you do not turn to iniquity; for, after your misery, you have begun to follow this.

[[job-36-22]]
^22^ Behold, God is exalted in his strength, and there is no one like him among the law-givers.

[[job-36-23]]
^23^ Who is able to investigate his ways? And who can say, “You have done iniquity,” to him?

[[job-36-24]]
^24^ Remember that you are ignorant of his work, yet men have sung its praises.

[[job-36-25]]
^25^ All men consider him; and each one ponders from a distance.

[[job-36-26]]
^26^ Behold, God is great, defeating our knowledge; the number of his years is inestimable.

[[job-36-27]]
^27^ He carries away the drops of rain, and he sends forth showers like a raging whirlpool;

[[job-36-28]]
^28^ they flow from the clouds that are woven above everything.

[[job-36-29]]
^29^ If he wills it, he extends the clouds as his tent

[[job-36-30]]
^30^ and shines with his light from above; likewise, he covers the oceans within his tent.

[[job-36-31]]
^31^ For he judges the people by these things, and he gives food to a multitude of mortals.

[[job-36-32]]
^32^ Within his hands, he hides the light, and he commands it to come forth again.

[[job-36-33]]
^33^ He announces it to his friend, for it is his possession and he is able to reach out to it.


[[job-37]]
== Chapter 37

[[job-37-1]]
^1^ At this, my heart became frightened, and it has been moved from its place.

[[job-37-2]]
^2^ Pay close attention to the alarm of his voice and to the sound that proceeds from his mouth.

[[job-37-3]]
^3^ He beholds everything under the heavens, and his light reaches beyond the ends of the earth.

[[job-37-4]]
^4^ After this, a noise will sound; he will thunder with the voice of his greatness, and it will not be tracked down, yet his voice will be obeyed.

[[job-37-5]]
^5^ God will thunder with his voice miraculously, for he performs great and unsearchable things.

[[job-37-6]]
^6^ He commands the snow to descend on earth, and the winter rains, and the shower of his strength.

[[job-37-7]]
^7^ He signs the hand of all men, so that each one may know his works.

[[job-37-8]]
^8^ The beast will enter his hiding-place, and he will remain in his cave.

[[job-37-9]]
^9^ From the interior, a storm will come forth, and a cold winter from the north.

[[job-37-10]]
^10^ As God breathes out, frost forms, and the waters are poured forth very widely again.

[[job-37-11]]
^11^ Crops desire clouds, and the clouds scatter their light.

[[job-37-12]]
^12^ It shines all around, wherever the will of him that governs them will lead, to anywhere he will command, over the whole face of the earth,

[[job-37-13]]
^13^ whether in one tribe, or in his own region, or in whatever place of his mercy that he will order them to be found.

[[job-37-14]]
^14^ Listen to these things, Job. Stand up and consider the wonders of God.

[[job-37-15]]
^15^ Do you know when God ordered the rains, so as to show the light of his clouds?

[[job-37-16]]
^16^ Do you know the great paths of the clouds, and the perfect sciences?

[[job-37-17]]
^17^ Are not your garments hot, when the south wind blows across the land?

[[job-37-18]]
^18^ Perhaps you have made the heavens with him, which are very solid, as if they had been cast from brass.

[[job-37-19]]
^19^ Reveal to us what we should say to him, for, of course, we are wrapped in darkness.

[[job-37-20]]
^20^ Who will explain to him the things that I am saying? Even while a man is still speaking, he will be devoured.

[[job-37-21]]
^21^ Although they do not see the light, the air will be thickened suddenly into clouds, and the wind, passing by, will drive them away.

[[job-37-22]]
^22^ Riches arrive from the north, and fearful praise reaches out to God.

[[job-37-23]]
^23^ We are not worthy to be able to find him. Great in strength, great in judgment, great in justice: he is indescribable.

[[job-37-24]]
^24^ Therefore, men will fear him, and all those who seem to themselves to be wise, will not dare to contemplate him.


[[job-38]]
== Chapter 38

[[job-38-1]]
^1^ But the Lord, responding to Job from a whirlwind, said:

[[job-38-2]]
^2^ Who is this that wraps sentences in unskilled words?

[[job-38-3]]
^3^ Gird your waist like a man. I will question you, and you must answer me.

[[job-38-4]]
^4^ Where were you, when I set the foundations of the earth? Tell me, if you have understanding.

[[job-38-5]]
^5^ Who set its measurements, if you know, or who stretched a line over it?

[[job-38-6]]
^6^ Upon what have its bases been grounded, and who set forth its cornerstone,

[[job-38-7]]
^7^ when the morning stars praised me together, and all the sons of God made a joyful noise?

[[job-38-8]]
^8^ Who enclosed the sea with doors, when it broke forth as if issuing from the womb,

[[job-38-9]]
^9^ when I stationed a cloud as its garment and wrapped it in a mist as if swaddling an infant?

[[job-38-10]]
^10^ I encircled it with my limits, and I positioned its bars and doors.

[[job-38-11]]
^11^ And I said: “This far you will approach, and you will proceed no further, and here you will break your swelling waves.”

[[job-38-12]]
^12^ Did you, after your birth, command the birth of the sun and show the sunrise its place?

[[job-38-13]]
^13^ And did you hold the extremities of the earth, shaking them, and have you shaken the impious out of it?

[[job-38-14]]
^14^ The seal will be restored like clay, and it will remain in place like a garment.

[[job-38-15]]
^15^ From the impious, the light will be taken away, and the exalted arm will be broken.

[[job-38-16]]
^16^ Have you entered the depths of the sea, and have you taken a walk in the uttermost parts of the abyss?

[[job-38-17]]
^17^ Have the gates of death been opened to you, and have you seen the doors of darkness?

[[job-38-18]]
^18^ Have you considered the breadth of the earth? If you know all things, reveal them to me.

[[job-38-19]]
^19^ Which is the way that holds the light, and which is the place of darkness?

[[job-38-20]]
^20^ In this way, you might lead each thing to its final place, and understand the paths of its house.

[[job-38-21]]
^21^ So then, did you know when you were to be born? And did you know the number of your days?

[[job-38-22]]
^22^ Have you been admitted into the storehouses of the snows, and have you gazed upon the stockpile of the brimstone,

[[job-38-23]]
^23^ which I have prepared for the time of the enemy, for the day of the battle and the war?

[[job-38-24]]
^24^ In what way is the light scattered, and the heat distributed, over the earth?

[[job-38-25]]
^25^ Who gave a course to the rainstorms, and a path to the resounding thunder,

[[job-38-26]]
^26^ so that it would rain on the earth far from man, in the wilderness where no mortal lingers,

[[job-38-27]]
^27^ so that it would fill impassable and desolate places, and would bring forth green plants?

[[job-38-28]]
^28^ Who is the father of rain, or who conceived the drops of dew?

[[job-38-29]]
^29^ From whose womb did the ice proceed, and who created the frost from the air?

[[job-38-30]]
^30^ The waters are hardened to become like stone, and the surface of the abyss freezes over.

[[job-38-31]]
^31^ Will you have the strength to join together the sparkling stars of the Pleiades, or are you able to disperse the circling of Arcturus?

[[job-38-32]]
^32^ Can you bring forth the morning star, in its time, and make the evening star rise over the sons of the earth?

[[job-38-33]]
^33^ Do you know the order of heaven, and can you explain its rules here on the earth?

[[job-38-34]]
^34^ Can you lift up your voice to the clouds, so that an onslaught of waters will cover you?

[[job-38-35]]
^35^ Can you send forth lightning bolts, and will they go, and on returning, say to you: “Here we are?”

[[job-38-36]]
^36^ Who placed discernment in the guts of man, or who gave the rooster intelligence?

[[job-38-37]]
^37^ Who can describe the rules of the heavens, or who can put to rest the harmony of heaven?

[[job-38-38]]
^38^ When was the dust cast to become the earth, and when were its clods fastened together?

[[job-38-39]]
^39^ Will you seize prey for the lioness, and will you sustain the lives of her young,

[[job-38-40]]
^40^ as they rest in their dens or lie in wait in pits?

[[job-38-41]]
^41^ Who provides the raven with its meal, when her chicks cry out to God, as they wander around because they have no food?


[[job-39]]
== Chapter 39

[[job-39-1]]
^1^ Do you know at what time the wild goats have given birth among the rocks, or do you observe the deer when they go into labor?

[[job-39-2]]
^2^ Have you numbered the months since their conception, and do you know at what time they gave birth?

[[job-39-3]]
^3^ They bend themselves for their offspring, and they give birth, and they emit roars.

[[job-39-4]]
^4^ Their young are weaned and go out to feed; they depart and do not return to them.

[[job-39-5]]
^5^ Who has set the wild ass free, and who has released his bonds?

[[job-39-6]]
^6^ I have given a house in solitude to him, and his tabernacle is in the salted land.

[[job-39-7]]
^7^ He despises the crowded city; he does not pay attention to the bellow of the tax collector.

[[job-39-8]]
^8^ He looks around the mountains of his pasture, and he searches everywhere for green plants.

[[job-39-9]]
^9^ Will the rhinoceros be willing to serve you, and will he remain in your stall?

[[job-39-10]]
^10^ Can you detain the rhinoceros with your harness to plough for you, and will he loosen the soil of the furrows behind you?

[[job-39-11]]
^11^ Will you put your faith in his great strength, and delegate your labors to him?

[[job-39-12]]
^12^ Will you trust him to return to you the seed, and to gather it on your drying floor?

[[job-39-13]]
^13^ The wing of the ostrich is like the wings of the heron, and of the hawk.

[[job-39-14]]
^14^ When she leaves eggs behind in the earth, will you perhaps warm them in the dust?

[[job-39-15]]
^15^ She forgets that feet may trample them, or that the beasts of the field may shatter them.

[[job-39-16]]
^16^ She is hardened against her young, as if they were not hers; she has labored in vain, with no fear compelling her.

[[job-39-17]]
^17^ For God has deprived her of wisdom; neither has he given her understanding.

[[job-39-18]]
^18^ Yet, when the time is right, she raises her wings on high; she ridicules the horse and his rider.

[[job-39-19]]
^19^ Will you supply strength to the horse, or envelope his throat with neighing?

[[job-39-20]]
^20^ Will you alarm him as the locusts do? His panic is revealed by the display of his nostrils.

[[job-39-21]]
^21^ He digs at the earth with his hoof; he jumps around boldly; he advances to meet armed men.

[[job-39-22]]
^22^ He despises fear; he does not turn away from the sword.

[[job-39-23]]
^23^ Above him, the quiver rattles, the spear and the shield shake.

[[job-39-24]]
^24^ Seething and raging, he drinks up the earth; neither does he pause when the blast of the trumpet sounds.

[[job-39-25]]
^25^ When he hears the bugle, he says, “Ha!” He smells the battle from a distance, the exhortation of the officers, and the battle cry of the soldiers.

[[job-39-26]]
^26^ Does the hawk grow feathers by means of your wisdom, spreading her wings towards the south?

[[job-39-27]]
^27^ Will the eagle lift herself up at your command and make her nest in steep places?

[[job-39-28]]
^28^ She dwells among the rocks, and she lingers among broken boulders and inaccessible cliffs.

[[job-39-29]]
^29^ From there, she looks for food, and her eyes catch sight of it from far away.

[[job-39-30]]
^30^ Her young will drink blood, and wherever the carcass will be, she is there immediately.

[[job-39-31]]
^31^ And the Lord continued, and he said to Job:

[[job-39-32]]
^32^ Will he who contends with God be so easily silenced? Certainly, he who argues with God must also respond to him.

[[job-39-33]]
^33^ Then Job answered the Lord, saying:

[[job-39-34]]
^34^ What could I possibly answer, since I have been speaking thoughtlessly? I will place my hand over my mouth.

[[job-39-35]]
^35^ One thing I have spoken, which I wish I had not said; and another, to which I will add no more.


[[job-40]]
== Chapter 40

[[job-40-1]]
^1^ But the Lord, answering Job out of the whirlwind, said:

[[job-40-2]]
^2^ Gird your waist like a man. I will question you, and you must answer me.

[[job-40-3]]
^3^ Will you make my judgment null and void; and will you condemn me so that you may be justified?

[[job-40-4]]
^4^ And do you have an arm like God, or a voice like thunder?

[[job-40-5]]
^5^ Envelop yourself with splendor, and raise yourself up on high, and be glorious, and put on splendid garments.

[[job-40-6]]
^6^ Scatter the arrogant with your wrath, and, when you see all the arrogant, humble them.

[[job-40-7]]
^7^ Look down upon each of the arrogant and confound them, and crush the impious in their place.

[[job-40-8]]
^8^ Hide them in the dust together and plunge their faces into the pit.

[[job-40-9]]
^9^ Then I will confess that your right hand is able to save you.

[[job-40-10]]
^10^ Behold, the behemoth, whom I created along with you, eats hay like an ox.

[[job-40-11]]
^11^ His strength is in his lower back, and his power is in the center of his abdomen.

[[job-40-12]]
^12^ He draws up his tail like a cedar; the sinews of his thighs have been drawn together.

[[job-40-13]]
^13^ His bones are like pipes of brass; his cartilage is like plates of iron.

[[job-40-14]]
^14^ He is the beginning of the ways of God, who made him; he will use him as his sword.

[[job-40-15]]
^15^ The mountains bring forth grass for him; all the beasts of the field will play there.

[[job-40-16]]
^16^ He sleeps in the shadows, under the cover of branches, and in moist places.

[[job-40-17]]
^17^ The shadows cover his shadow; the willows of the brook will encircle him.

[[job-40-18]]
^18^ Behold, he will drink a river and not be amazed, and he has confidence that the Jordan could flow into his mouth.

[[job-40-19]]
^19^ He will seize him through his eyes, as if with a hook, and he will bore through his nostrils, as if with stakes.

[[job-40-20]]
^20^ Can you draw out the leviathan with a hook, and can you bind his tongue with a cord?

[[job-40-21]]
^21^ Can you place a ring in his nose, or bore through his jaw with an arm band?

[[job-40-22]]
^22^ Will he offer many prayers to you, or speak to you quietly?

[[job-40-23]]
^23^ Will he form a covenant with you, and will you accept him as a servant forever?

[[job-40-24]]
^24^ Will you play with him as with a bird, or tether him for your handmaids?

[[job-40-25]]
^25^ Will your friends cut him into pieces, will dealers distribute him?

[[job-40-26]]
^26^ Will you fill up bags with his hide, and let his head be used as a home for fishes?

[[job-40-27]]
^27^ Place your hand upon him; remember the battle and speak no more.

[[job-40-28]]
^28^ Behold, his hope will fail him, and in the sight of all, he will be thrown down.


[[job-41]]
== Chapter 41

[[job-41-1]]
^1^ I will not rouse him, as the cruel would do, for who is able to withstand my countenance?

[[job-41-2]]
^2^ Who has given to me beforehand, so that I should repay him? All things that are under heaven are mine.

[[job-41-3]]
^3^ I will not spare him, nor his powerful words and counterfeit attempts at supplication.

[[job-41-4]]
^4^ Who can reveal the beauty of his garment? And who can enter the middle of his mouth?

[[job-41-5]]
^5^ Who can open the doors of his face? I gave fear to the circle of his teeth.

[[job-41-6]]
^6^ His body is like shields fused together, like dense scales pressed over one another.

[[job-41-7]]
^7^ One is joined to another, and not even air can pass between them.

[[job-41-8]]
^8^ They adhere to one another, and they hold themselves in place and will not be separated.

[[job-41-9]]
^9^ His sneezing has the brilliance of fire, and his eyes are like the eyelids of the morning.

[[job-41-10]]
^10^ Lamps proceed from his mouth, like torches of fire burning brightly.

[[job-41-11]]
^11^ Smoke passes out of his nostrils, like a pot that is heated and boiling.

[[job-41-12]]
^12^ His breath causes coal to burn, and a flame comes forth from his mouth.

[[job-41-13]]
^13^ Strength dwells in his neck, and destitution goes before his presence.

[[job-41-14]]
^14^ The parts of his body work in harmony together. He will send lightning bolts against him, and they will not be carried to another place.

[[job-41-15]]
^15^ His heart will be as hard as a stone and as dense as a blacksmith’s anvil.

[[job-41-16]]
^16^ When he will be raised up, the angels will be afraid, and, because they are terrified, they will purify themselves.

[[job-41-17]]
^17^ When a sword catches up with him, it will not be able to settle in, nor a spear, nor a breastplate.

[[job-41-18]]
^18^ For he will consider iron as if it were chaff, and brass as if it were rotten wood.

[[job-41-19]]
^19^ The archer will not cause him to flee; the stones of the sling have been turned into stubble for him.

[[job-41-20]]
^20^ He will treat the hammer as if it were stubble, and he will ridicule those who brandish the spear.

[[job-41-21]]
^21^ The beams of the sun will be under him, and he will dispense gold to them as if it were clay.

[[job-41-22]]
^22^ He will make the depths of the sea boil like a pot, and he will set it to bubble just as ointments do.

[[job-41-23]]
^23^ A path will shine after him; he will esteem the abyss as if it were weakening with age.

[[job-41-24]]
^24^ There is no power on the earth that is being compared to him, who has been made so that he fears no one.

[[job-41-25]]
^25^ He sees every prominent thing; he is king over all the sons of arrogance.


[[job-42]]
== Chapter 42

[[job-42-1]]
^1^ Then Job, responding to the Lord, said:

[[job-42-2]]
^2^ I know that you are able to do all things, and that no thoughts are hidden from you.

[[job-42-3]]
^3^ So, who is it that would disguise a lack of knowledge as counsel? Therefore, I have been speaking foolishly, about things whose measure exceeds my knowledge.

[[job-42-4]]
^4^ Listen, and I will speak. I will question you, and you may answer me.

[[job-42-5]]
^5^ By paying attention with the ear, I have heard you, but now my eye sees you.

[[job-42-6]]
^6^ Therefore, I find myself reprehensible, and I will do penance in embers and ashes.

[[job-42-7]]
^7^ But after the Lord had finished speaking these words to Job, he said to Eliphaz the Themanite: My wrath has been kindled against you, and against your two friends, because you have not been speaking correctly in my eyes, as my servant Job has done.

[[job-42-8]]
^8^ Therefore, have seven bulls and seven rams brought to you, and go to my servant Job, and offer these as a holocaust for yourselves. But also, my servant Job will pray for you; I will accept his face, so that foolishness will not be imputed to you. For you have not been speaking correctly about me, as my servant Job has done.

[[job-42-9]]
^9^ So Eliphaz the Themanite, and Baldad the Suhite, and Zophar the Naamathite departed, and they did just as the Lord had spoken to them, and the Lord accepted the face of Job.

[[job-42-10]]
^10^ Likewise, the Lord was moved by the repentance of Job, when he prayed for his friends. And the Lord gave to Job twice as much as he had before.

[[job-42-11]]
^11^ Yet all his brethren came to him, and all his sisters, and everyone who had known him before, and they ate bread with him in his house. They also shook their heads over him and comforted him, because of all the bad things that God had inflicted on him. And each one of them gave him one female sheep, and one earring of gold.

[[job-42-12]]
^12^ And the Lord blessed the latter end of Job even more than his beginning. And he had fourteen thousand sheep, and six thousand camels, and a thousand pairs of oxen, and a thousand she-donkeys.

[[job-42-13]]
^13^ And he had seven sons and three daughters.

[[job-42-14]]
^14^ And he called the name of one, Daylight, and the name of the second, Cinnamon, and the name of the third, Horn of Cosmetics.

[[job-42-15]]
^15^ And, in the whole world, there were not found women so beautiful as the daughters of Job. And so their father gave them an inheritance along with their brothers.

[[job-42-16]]
^16^ But Job lived long after these events, for a hundred and forty years, and he saw his children, and his children’s children, all the way to the fourth generation, and he died an old man and full of days.
