[[proverbs]]
= The Book of Proverbs
:short: Proverbs

[[proverbs-1]]
== Chapter 1

[[proverbs-1-1]]
^1^ The parables of Solomon, son of David, king of Israel,

[[proverbs-1-2]]
^2^ in order to know wisdom and discipline,

[[proverbs-1-3]]
^3^ to understand words of prudence, and to accept the instruction of doctrine, justice and judgment, and equity,

[[proverbs-1-4]]
^4^ so as to give discernment to little ones, knowledge and understanding to adolescents.

[[proverbs-1-5]]
^5^ By listening, the wise shall become wiser and the intelligent shall possess governments.

[[proverbs-1-6]]
^6^ He shall turn his soul to a parable and to its interpretation, to the words of the wise and their enigmas.

[[proverbs-1-7]]
^7^ The fear of the Lord is the beginning of wisdom. The foolish despise wisdom as well as doctrine.

[[proverbs-1-8]]
^8^ Listen, my son, to the discipline of your father, and forsake not the law of your mother,

[[proverbs-1-9]]
^9^ so that grace may be added to your head and a collar to your neck.

[[proverbs-1-10]]
^10^ My son, if sinners should entice you, do not consent to them.

[[proverbs-1-11]]
^11^ If they should say: “Come with us. We will lie in wait for blood. We will lay traps against the innocent, without cause.

[[proverbs-1-12]]
^12^ Let us swallow him alive, like Hell, and whole, like one descending into the pit.

[[proverbs-1-13]]
^13^ We will discover every precious substance. We will fill our houses with spoils.

[[proverbs-1-14]]
^14^ Cast your lot with us. One purse will be for us all.”

[[proverbs-1-15]]
^15^ My son, do not walk with them. Preclude your feet from their paths.

[[proverbs-1-16]]
^16^ For their feet rush to evil, and they hurry to shed blood.

[[proverbs-1-17]]
^17^ But a net is thrown in vain before the eyes of those who have wings.

[[proverbs-1-18]]
^18^ Likewise, they lie in ambush against their own blood, and they undertake deceits against their own souls.

[[proverbs-1-19]]
^19^ Thus, the ways of all those who are greedy seize the souls of those who possess.

[[proverbs-1-20]]
^20^ Wisdom forewarns far and wide; she bestows her voice in the streets.

[[proverbs-1-21]]
^21^ She cries out at the head of crowds; at the entrance of the gates of the city, she offers her words, saying:

[[proverbs-1-22]]
^22^ “Little ones, how long will you choose to be childish, and how long will the foolish desire what is harmful to themselves, and how long will the imprudent hate knowledge?

[[proverbs-1-23]]
^23^ Be converted by my correction. Lo, I will offer my spirit to you, and I will reveal my words to you.

[[proverbs-1-24]]
^24^ For I called, and you refused. I extended my hand, and there was no one who watched.

[[proverbs-1-25]]
^25^ You have despised all my counsels, and you have neglected my rebukes.

[[proverbs-1-26]]
^26^ Similarly, I will ridicule you at your demise, and I will mock you, when that which you feared shall overcome you.

[[proverbs-1-27]]
^27^ When sudden calamity rushes upon you, and your demise advances like a tempest, when tribulation and anguish overcome you,

[[proverbs-1-28]]
^28^ then they will call to me, and I will not heed, they will arise in the morning, and not find me.

[[proverbs-1-29]]
^29^ For they held hatred for discipline, and they would not accept the fear of the Lord;

[[proverbs-1-30]]
^30^ they would not consent to my counsel, but they detracted from all of my corrections.

[[proverbs-1-31]]
^31^ Therefore, they shall eat the fruit of their way, and they shall have their fill of their own counsels.

[[proverbs-1-32]]
^32^ The loathing of the little ones shall destroy them, and the prosperity of the foolish shall perish them.

[[proverbs-1-33]]
^33^ But whoever will listen to me shall rest without terror, and shall have full enjoyment of abundance, without fear of evils.”


[[proverbs-2]]
== Chapter 2

[[proverbs-2-1]]
^1^ My son, if you would accept my words, and conceal my commandments within you,

[[proverbs-2-2]]
^2^ so that your ears may listen to wisdom, then bend your heart in order to know prudence.

[[proverbs-2-3]]
^3^ For if you would call upon wisdom and bend your heart to prudence,

[[proverbs-2-4]]
^4^ if you will seek her like money, and dig for her as if for treasure,

[[proverbs-2-5]]
^5^ then you will understand the fear of the Lord, and you will discover the knowledge of God.

[[proverbs-2-6]]
^6^ For the Lord bestows wisdom, and out of his mouth, prudence and knowledge.

[[proverbs-2-7]]
^7^ He will preserve the salvation of the righteous, and he will protect those who walk in simplicity:

[[proverbs-2-8]]
^8^ serving the paths of justice, and guarding the ways of sanctity.

[[proverbs-2-9]]
^9^ Then you shall understand justice and judgment, and equity, and every good path.

[[proverbs-2-10]]
^10^ If wisdom is to enter into your heart, and if knowledge is to become pleasing to your soul,

[[proverbs-2-11]]
^11^ then counsel must guard you, and prudence must serve you,

[[proverbs-2-12]]
^12^ so that you may be rescued from the evil way, and from the man who speaks perversities,

[[proverbs-2-13]]
^13^ from those who leave the straight path to walk in dark ways,

[[proverbs-2-14]]
^14^ who rejoice when they have done evil, and who exult in the most wicked things.

[[proverbs-2-15]]
^15^ Their ways are perverse, and their steps are infamous.

[[proverbs-2-16]]
^16^ So may you be rescued from the foreign woman, and from the outsider, who softens her speech,

[[proverbs-2-17]]
^17^ and who leaves behind the Guide of her youth,

[[proverbs-2-18]]
^18^ and who has forgotten the covenant of her God. For her household inclines toward death, and her paths toward Hell.

[[proverbs-2-19]]
^19^ All those who enter to her will not return again, nor will they take hold of the paths of life.

[[proverbs-2-20]]
^20^ So may you walk in the good way, and keep to the difficult paths of the just.

[[proverbs-2-21]]
^21^ For those who are upright shall live upon the earth, and the simple shall continue upon it.

[[proverbs-2-22]]
^22^ Yet truly, the impious shall perish from the earth, and those who act unjustly shall be taken away from it.


[[proverbs-3]]
== Chapter 3

[[proverbs-3-1]]
^1^ My son, do not forget my law, but let your heart guard my precepts.

[[proverbs-3-2]]
^2^ For they shall set before you length of days, and years of life, and peace.

[[proverbs-3-3]]
^3^ Let not mercy and truth abandon you: encircle them around your throat, and inscribe them on the tablets of your heart.

[[proverbs-3-4]]
^4^ And so shall you discover grace and good discipline, in the sight of God and men.

[[proverbs-3-5]]
^5^ Have confidence in the Lord with all your heart, and do not depend upon your own prudence.

[[proverbs-3-6]]
^6^ In all your ways, consider him, and he himself will direct your steps.

[[proverbs-3-7]]
^7^ Do not seem wise to yourself. Fear God, and withdraw from evil.

[[proverbs-3-8]]
^8^ Certainly, it shall be health to your navel, and refreshment to your bones.

[[proverbs-3-9]]
^9^ Honor the Lord with your substance, and give to him from the first of all your fruits,

[[proverbs-3-10]]
^10^ and then your storehouses will be filled with abundance, and your presses shall overflow with wine.

[[proverbs-3-11]]
^11^ My son, do not discard the discipline of the Lord, and do not fall away when you are corrected by him.

[[proverbs-3-12]]
^12^ For whomever the Lord loves, he corrects, and just as a father does with a son, he wins him over.

[[proverbs-3-13]]
^13^ Blessed is the man who finds wisdom and who advances to prudence.

[[proverbs-3-14]]
^14^ Her acquisition is better than trading in silver, and her fruit is better than the first and purest gold.

[[proverbs-3-15]]
^15^ She is more precious than all riches, and all that can be desired cannot prevail in comparison to her.

[[proverbs-3-16]]
^16^ Length of days is at her right hand, and at her left hand is wealth and glory.

[[proverbs-3-17]]
^17^ Her ways are beautiful ways, and all her paths are peaceful.

[[proverbs-3-18]]
^18^ She is a tree of life to those who overtake her, and he who shall take hold of her is blessed.

[[proverbs-3-19]]
^19^ The Lord founded the earth on wisdom. He secured the heavens with prudence.

[[proverbs-3-20]]
^20^ By his wisdom, the abyss erupted and the clouds increased with dew.

[[proverbs-3-21]]
^21^ My son, let not these things move away from your eyes. Preserve law as well as counsel.

[[proverbs-3-22]]
^22^ And so shall there be life in your soul and grace in your voice.

[[proverbs-3-23]]
^23^ Then you shall walk confidently in your way, and your feet will not stumble.

[[proverbs-3-24]]
^24^ When you slumber, you shall not fear. When you rest, your sleep also will be sweet.

[[proverbs-3-25]]
^25^ Do not fear unexpected terror, nor the power of the impious falling upon you.

[[proverbs-3-26]]
^26^ For the Lord will be at your side, and he will guard your feet, so that you may not be seized.

[[proverbs-3-27]]
^27^ Do not prevent him who is able from doing good. When you are able, do good yourself too.

[[proverbs-3-28]]
^28^ Do not say to your friend: “Go away, and then return. Tomorrow I will give to you.” When you are able to do so, give in the present.

[[proverbs-3-29]]
^29^ Do not undertake evil against your friend, even though he has trust in you.

[[proverbs-3-30]]
^30^ Do not contend against a man without cause, even though he has done no evil to you.

[[proverbs-3-31]]
^31^ Do not rival an unjust man, and do not imitate his ways.

[[proverbs-3-32]]
^32^ For everyone who ridicules is an abomination to the Lord, and his communication is for the simple.

[[proverbs-3-33]]
^33^ Destitution in the house of the impious is from the Lord. But the habitations of the just shall be blessed.

[[proverbs-3-34]]
^34^ He will ridicule those who ridicule, but he will bestow grace upon the mild.

[[proverbs-3-35]]
^35^ The wise will possess glory. The exaltation of the foolish is disgraceful.


[[proverbs-4]]
== Chapter 4

[[proverbs-4-1]]
^1^ Listen, sons, to the discipline of a father, and pay attention, so that you may know prudence.

[[proverbs-4-2]]
^2^ I will bestow upon you a good gift. Do not relinquish my law.

[[proverbs-4-3]]
^3^ For I, too, was the son of my father, tender and an only son in the sight of my mother.

[[proverbs-4-4]]
^4^ And he taught me, and he also said: “Let your heart accept my words. Keep my precepts, and you shall live.

[[proverbs-4-5]]
^5^ Obtain wisdom, obtain prudence. May you neither forget, nor turn away from, the words of my mouth.

[[proverbs-4-6]]
^6^ Do not send her away, and she will guard you. Love her, and she will preserve you.

[[proverbs-4-7]]
^7^ The beginning of wisdom is to obtain wisdom, and, with all that you possess, to acquire prudence.

[[proverbs-4-8]]
^8^ Grasp her, and she will exalt you. You will be glorified by her, when you have embraced her.

[[proverbs-4-9]]
^9^ She will bestow upon your head an increase in graces, and she will protect you with a noble crown.

[[proverbs-4-10]]
^10^ Listen, my son, and accept my words, so that years of life may be multiplied for you.

[[proverbs-4-11]]
^11^ I will demonstrate to you the way of wisdom. I will lead you along the paths of equity.

[[proverbs-4-12]]
^12^ When you have entered by these, your steps will not be constrained, and when running, you will have no obstacle.

[[proverbs-4-13]]
^13^ Take hold of discipline. Do not dismiss it. Guard it, for it is your life.

[[proverbs-4-14]]
^14^ Do not delight in the paths of the impious, nor permit the way of evil-doers to please you.

[[proverbs-4-15]]
^15^ Take flight from it. Do not pass close to it. Turn away and abandon it.

[[proverbs-4-16]]
^16^ For they do not sleep, unless they have done evil. And their sleep is quickly taken away from them, unless they have overthrown.

[[proverbs-4-17]]
^17^ They eat the bread of impiety, and they drink the wine of iniquity.

[[proverbs-4-18]]
^18^ But the path of the just is like a shining light: it advances and increases, even to the day of completion.

[[proverbs-4-19]]
^19^ The way of the impious is darkened. They do not know where they may fall.

[[proverbs-4-20]]
^20^ My son, pay attention to my sermons, and incline your ear to my eloquent words.

[[proverbs-4-21]]
^21^ Let them not recede from your eyes. Keep them in the midst of your heart.

[[proverbs-4-22]]
^22^ For they are life to those who find them and health to all that is flesh.

[[proverbs-4-23]]
^23^ Preserve your heart with all watchfulness, for life proceeds from this.

[[proverbs-4-24]]
^24^ Remove from yourself a corrupt mouth, and let detracting lips be far from you.

[[proverbs-4-25]]
^25^ Let your eyes look straight ahead, and let your eyelids precede your steps.

[[proverbs-4-26]]
^26^ Direct the path of your feet, and all your ways shall be secure.

[[proverbs-4-27]]
^27^ Turn aside, neither to the right, nor to the left; yet turn your foot away from evil. For the Lord knows the ways that are on the right, and truly, those that are on the left are perverse. But he himself will make your courses straight. Then your journey will advance in peace.


[[proverbs-5]]
== Chapter 5

[[proverbs-5-1]]
^1^ My son, pay attention to my wisdom, and incline your ear to my prudence,

[[proverbs-5-2]]
^2^ so that you may guard your thinking, and so that your lips may preserve discipline. Do not pay attention to the deceit of a woman.

[[proverbs-5-3]]
^3^ For the lips of a loose woman are like a dripping honeycomb, and her voice is smoother than oil.

[[proverbs-5-4]]
^4^ But in the end, she is as bitter as wormwood, and as sharp as a two-edged sword.

[[proverbs-5-5]]
^5^ Her feet descend into death, and her steps reach even to Hell.

[[proverbs-5-6]]
^6^ They do not walk along the path of life; her steps are wandering and untraceable.

[[proverbs-5-7]]
^7^ Therefore, my son, listen to me now, and do not withdraw from the words of my mouth.

[[proverbs-5-8]]
^8^ Make your way at a distance from her, and do not approach the doors of her house.

[[proverbs-5-9]]
^9^ Do not give your honor to foreigners, and your years to the cruel.

[[proverbs-5-10]]
^10^ Otherwise, outsiders may be filled with your strength, and your labors may be in a foreign house,

[[proverbs-5-11]]
^11^ and you may mourn in the end, when you will have consumed your flesh and your body. And so you may say:

[[proverbs-5-12]]
^12^ “Why have I detested discipline, and why has my heart not been quieted by correction?

[[proverbs-5-13]]
^13^ And why have I not listened to the voice of those who guided me? And why has my ear not inclined to my teachers?

[[proverbs-5-14]]
^14^ I have almost been with all evil in the midst of the church and of the assembly.”

[[proverbs-5-15]]
^15^ Drink water from your own cistern and from the springs of your own well.

[[proverbs-5-16]]
^16^ Let your fountains be diverted far and wide, and divide your waters in the streets.

[[proverbs-5-17]]
^17^ Hold them for yourself alone, and do not let strangers be partakers with you.

[[proverbs-5-18]]
^18^ Let your spring be blessed, and rejoice with the wife of your youth:

[[proverbs-5-19]]
^19^ a beloved doe and most pleasing fawn. Let her breasts inebriate you at all times. Be delighted continually by her love.

[[proverbs-5-20]]
^20^ Why are you seduced, my son, by a strange woman, and why are you kept warm by the bosom of another?

[[proverbs-5-21]]
^21^ The Lord beholds the ways of man, and he considers all his steps.

[[proverbs-5-22]]
^22^ His own iniquities take hold of the impious, and he is bound by the cords of his own sins.

[[proverbs-5-23]]
^23^ He shall die, for he has not held to discipline. And by the multitude of his foolishness, he shall be deceived.


[[proverbs-6]]
== Chapter 6

[[proverbs-6-1]]
^1^ My son, if you have taken a pledge on behalf of your friend, then you have bound your hand to an outsider,

[[proverbs-6-2]]
^2^ then you are ensnared by the words of your own mouth, and taken captive by your own words.

[[proverbs-6-3]]
^3^ Therefore, my son, do what I say, and free yourself, for you have fallen into the hand of your neighbor. Run, hurry, awaken your friend.

[[proverbs-6-4]]
^4^ Do not grant sleep to your eyes, nor let your eyelids slumber.

[[proverbs-6-5]]
^5^ Rescue yourself like a gazelle from the hand, and like a bird from the hand of the fowler.

[[proverbs-6-6]]
^6^ Go to the ant, you lazy one, and consider her ways, and so learn wisdom.

[[proverbs-6-7]]
^7^ For though she has no ruler, nor instructor, nor leader,

[[proverbs-6-8]]
^8^ she provides meals for herself in the summer, and she gathers at the harvest what she may eat.

[[proverbs-6-9]]
^9^ How long will you slumber, you lazy one? When will you rise up from your sleep?

[[proverbs-6-10]]
^10^ You will sleep a little, you will slumber a little, you will fold your hands a little to sleep,

[[proverbs-6-11]]
^11^ and then destitution will meet with you, like a traveler, and poverty, like an armed man. Yet truly, if you would be diligent, then your harvest will arrive like a fountain, and destitution will flee far from you.

[[proverbs-6-12]]
^12^ An apostate man, a harmful man, walks with a perverse mouth;

[[proverbs-6-13]]
^13^ he winks with the eyes, touches with the foot, speaks with the finger.

[[proverbs-6-14]]
^14^ With a depraved heart he devises evil, and at all times he sows conflict.

[[proverbs-6-15]]
^15^ To this one, his perdition will arrive promptly, and he shall be crushed suddenly: he will no longer have any remedy.

[[proverbs-6-16]]
^16^ Six things there are that the Lord hates, and the seventh, his soul detests:

[[proverbs-6-17]]
^17^ haughty eyes, a lying tongue, hands that shed innocent blood,

[[proverbs-6-18]]
^18^ a heart that devises the most wicked thoughts, feet running swiftly unto evil,

[[proverbs-6-19]]
^19^ a deceitful witness bringing forth lies, and he who sows discord among brothers.

[[proverbs-6-20]]
^20^ My son, preserve the precepts of your father, and do not dismiss the law of your mother.

[[proverbs-6-21]]
^21^ Bind them to your heart unceasingly, and encircle them around your throat.

[[proverbs-6-22]]
^22^ When you walk, let them keep step with you. When you sleep, let them guard you. And when you keep watch, speak with them.

[[proverbs-6-23]]
^23^ For commandment is a lamp, and law is a light, and the reproofs of discipline are the way of life.

[[proverbs-6-24]]
^24^ So may they guard you from an evil woman, and from the flattering tongue of the outsider.

[[proverbs-6-25]]
^25^ Let not your heart desire her beauty; do not be captivated by her winks.

[[proverbs-6-26]]
^26^ For the price of a prostitute is only one loaf. Yet the woman seizes the precious soul of a man.

[[proverbs-6-27]]
^27^ Would a man be able to conceal fire in his bosom, so that his garments would not burn?

[[proverbs-6-28]]
^28^ Or could he walk over burning coals, so that his feet would not be burned?

[[proverbs-6-29]]
^29^ So also, he who enters to the wife of his neighbor shall not be clean when he touches her.

[[proverbs-6-30]]
^30^ Not so great is the fault when someone has stolen. For he steals so as to satisfy a hungry soul.

[[proverbs-6-31]]
^31^ Also, if he is apprehended, he shall repay sevenfold and hand over all the substance of his house.

[[proverbs-6-32]]
^32^ But whoever is an adulterer, because of the emptiness of his heart, will destroy his own soul.

[[proverbs-6-33]]
^33^ He gathers shame and dishonor to himself, and his disgrace will not be wiped away.

[[proverbs-6-34]]
^34^ For the jealousy and fury of the husband will not spare him on the day of vindication,

[[proverbs-6-35]]
^35^ nor will he agree to the pleadings of anyone, nor will he accept, as repayment, a multitude of gifts.


[[proverbs-7]]
== Chapter 7

[[proverbs-7-1]]
^1^ My son, guard my words and conceal my precepts within you.

[[proverbs-7-2]]
^2^ Son, preserve my commandments, and you shall live. And keep my law as the pupil of your eye.

[[proverbs-7-3]]
^3^ Bind it with your fingers; write it on the tablets of your heart.

[[proverbs-7-4]]
^4^ Say to wisdom, “You are my sister,” and call prudence your friend.

[[proverbs-7-5]]
^5^ So may she guard you from the woman who is an outsider, and from the stranger who sweetens her words.

[[proverbs-7-6]]
^6^ For I gaze from the window of my house, through the lattice,

[[proverbs-7-7]]
^7^ and I see little ones. I consider a frenzied youth,

[[proverbs-7-8]]
^8^ who crosses the street at the corner and close to the way of that house.

[[proverbs-7-9]]
^9^ He steps into shadows, as day becomes evening, into the darkness and gloom of the night.

[[proverbs-7-10]]
^10^ And behold, a woman meets him, dressed like a harlot, prepared to captivate souls: chattering and rambling,

[[proverbs-7-11]]
^11^ unwilling to bear silence, unable to keep her feet at home,

[[proverbs-7-12]]
^12^ now outside, now in the streets, now lying in ambush near the corners.

[[proverbs-7-13]]
^13^ And overtaking the youth, she kisses him, and with a provocative face, she flatters him, saying:

[[proverbs-7-14]]
^14^ “I vowed sacrifices for well-being. Today I have repaid my vows.

[[proverbs-7-15]]
^15^ Because of this, I have gone out to meet you, desiring to see you, and I have found you.

[[proverbs-7-16]]
^16^ I have woven my bed with cords. I have strewn it with embroidered tapestries from Egypt.

[[proverbs-7-17]]
^17^ I have sprinkled my bed with myrrh, aloe, and cinnamon.

[[proverbs-7-18]]
^18^ Come, let us be inebriated in abundance, and let us delight in the embraces of desire, until the day begins to dawn.

[[proverbs-7-19]]
^19^ For my husband is not in his house. He has gone away on a very long journey.

[[proverbs-7-20]]
^20^ He took with him a bag of money. He will return to his house on the day of the full moon.”

[[proverbs-7-21]]
^21^ She enmeshed him with many words, and she drew him forward with the flattery of her lips.

[[proverbs-7-22]]
^22^ Immediately, he follows her, like an ox being led to the sacrifice, and like a lamb acting lasciviously, and not knowing that he is being drawn foolishly into chains,

[[proverbs-7-23]]
^23^ until the arrow pierces his liver. It is just as if a bird were to hurry into the snare. And he does not know that his actions endanger his own soul.

[[proverbs-7-24]]
^24^ Therefore, my son, hear me now, and attend to the words of my mouth.

[[proverbs-7-25]]
^25^ Do not let your mind be pulled into her ways. And do not be deceived by her paths.

[[proverbs-7-26]]
^26^ For she has tossed aside many wounded, and some of those who were very strong have been slain by her.

[[proverbs-7-27]]
^27^ Her household is the way to Hell, reaching even to the inner places of death.


[[proverbs-8]]
== Chapter 8

[[proverbs-8-1]]
^1^ Does not wisdom call out, and prudence bestow her voice?

[[proverbs-8-2]]
^2^ At the summits and the tops of exalted places, standing above the ways, in the midst of the paths,

[[proverbs-8-3]]
^3^ beside the gates of the city, at the very doors, she speaks, saying:

[[proverbs-8-4]]
^4^ “O men, to you I call out, and my voice is to the sons of men.

[[proverbs-8-5]]
^5^ O little ones, understand discernment. And you who are unwise, turn your souls.

[[proverbs-8-6]]
^6^ Listen, for I will speak about great things, and my lips will be opened, so as to foretell what is right.

[[proverbs-8-7]]
^7^ My throat shall practice truth, and my lips shall detest the impious.

[[proverbs-8-8]]
^8^ All my words are just. There is no depravity in them, and no perversity.

[[proverbs-8-9]]
^9^ They are upright to those who understand, and equitable to those who discover knowledge.

[[proverbs-8-10]]
^10^ Accept my discipline, and not money. Choose the doctrine that is greater than gold.

[[proverbs-8-11]]
^11^ For wisdom is better than all that is most precious, and everything that is desirable cannot compare to her.

[[proverbs-8-12]]
^12^ I, wisdom, dwell in counsel, and I am inside learned thoughts.

[[proverbs-8-13]]
^13^ The fear of the Lord hates evil. I detest arrogance, and pride, and every wicked way, and a mouth with a double tongue.

[[proverbs-8-14]]
^14^ Counsel is mine, and equity. Prudence is mine. Strength is mine.

[[proverbs-8-15]]
^15^ Through me, kings reign and legislators decree just conditions.

[[proverbs-8-16]]
^16^ Through me, princes rule and the powerful decree justice.

[[proverbs-8-17]]
^17^ I love those who love me. And those who stand watch for me until morning shall discover me.

[[proverbs-8-18]]
^18^ With me, are wealth and glory, superb riches and justice.

[[proverbs-8-19]]
^19^ For my fruit is better than gold and precious stones, and my progeny better than choice silver.

[[proverbs-8-20]]
^20^ I walk in the way of justice, in the midst of the paths of judgment,

[[proverbs-8-21]]
^21^ so that I may enrich those who love me, and thus complete their treasures.

[[proverbs-8-22]]
^22^ The Lord possessed me in the beginning of his ways, before he made anything, from the beginning.

[[proverbs-8-23]]
^23^ I was ordained from eternity, and out of antiquity, before the earth was formed.

[[proverbs-8-24]]
^24^ The abyss did not yet exist, and I was already conceived; neither had the fountains of waters yet erupted.

[[proverbs-8-25]]
^25^ The mountains, with their great mass, had not yet been established. Before the hills, I was brought forth.

[[proverbs-8-26]]
^26^ Still he had not made the earth, and the rivers, and the poles of the globe of the earth.

[[proverbs-8-27]]
^27^ I was already present: when he prepared the heavens; when, with a certain law and a circuit, he fortified the abyss;

[[proverbs-8-28]]
^28^ when he made firm the sky above, and set free the fountains of waters;

[[proverbs-8-29]]
^29^ when he encompassed the sea within its limits, and laid down a law for the waters, lest they transgress their limits; when he weighed the foundations of the earth.

[[proverbs-8-30]]
^30^ I was with him in composing all things. And I was delighted, throughout every day, by playing in his sight at all times,

[[proverbs-8-31]]
^31^ playing in globe of the earth. And my delight was to be with the sons of men.

[[proverbs-8-32]]
^32^ Therefore, sons, hear me now. Blessed are those who preserve my ways.

[[proverbs-8-33]]
^33^ Listen to discipline, and become wise, and do not be willing to cast it aside.

[[proverbs-8-34]]
^34^ Blessed is the man who listens to me, and who stands watch at my gates every day, and who observes at the posts of my doors.

[[proverbs-8-35]]
^35^ He who finds me, finds life, and he will draw salvation from the Lord.

[[proverbs-8-36]]
^36^ But he who sins against me will wound his own soul. All who hate me love death.”


[[proverbs-9]]
== Chapter 9

[[proverbs-9-1]]
^1^ Wisdom has built a house for herself. She has hewn seven columns.

[[proverbs-9-2]]
^2^ She has immolated her victims. She has mixed her wine and set forth her table.

[[proverbs-9-3]]
^3^ She has sent her maids to call out to the tower and to the fortified walls of the city,

[[proverbs-9-4]]
^4^ “If anyone is little, let him come to me.” And to the unwise, she has said:

[[proverbs-9-5]]
^5^ “Approach. Eat my bread, and drink the wine that I have mixed for you.

[[proverbs-9-6]]
^6^ Leave behind childishness. And live and walk by the ways of prudence.”

[[proverbs-9-7]]
^7^ Whoever teaches a mocker causes injury to himself. And whoever argues with the impious produces a blemish on himself.

[[proverbs-9-8]]
^8^ Do not be willing to argue with a mocker, lest he hate you. Dispute with the wise, and he will love you.

[[proverbs-9-9]]
^9^ Present an opportunity to the wise, and wisdom shall be added to him. Teach the just, and he will hurry to receive it.

[[proverbs-9-10]]
^10^ The fear of the Lord is the beginning of wisdom, and knowledge of holiness is prudence.

[[proverbs-9-11]]
^11^ For by me, your days will be multiplied and years of life will be added to you.

[[proverbs-9-12]]
^12^ If you would be wise, you will be so for yourself. But if you would be one who ridicules, you alone shall carry the evil.

[[proverbs-9-13]]
^13^ A foolish and loud woman, who is full of enticements and who knows nothing at all,

[[proverbs-9-14]]
^14^ sat at the entrance of her house on a seat, in a high place of the city,

[[proverbs-9-15]]
^15^ so as to call to those who were passing by the way and continuing on their journey:

[[proverbs-9-16]]
^16^ “Whoever is little, let him turn aside to me.” And to the frenzied, she said,

[[proverbs-9-17]]
^17^ “Stolen waters are more soothing, and secret bread is more pleasant.”

[[proverbs-9-18]]
^18^ And he did not know that giants are there, and that her companions are in the depths of Hell.


[[proverbs-10]]
== Chapter 10

[[proverbs-10-1]]
^1^ A wise son gladdens the father. Yet truly, a foolish son is the grief of his mother.

[[proverbs-10-2]]
^2^ Treasures of impiety will profit nothing. Truly, justice shall liberate from death.

[[proverbs-10-3]]
^3^ The Lord will not afflict with famine the soul of the just, and he will overthrow the treacheries of the impious.

[[proverbs-10-4]]
^4^ The neglectful hand has wrought destitution. But the hand of the steadfast prepares riches. He who advances by lies, this one feeds on the wind. For he is the same as one who runs after flying birds.

[[proverbs-10-5]]
^5^ He who gathers the harvest is a wise son. But he who snores in warm weather is a son of confusion.

[[proverbs-10-6]]
^6^ The blessing of the Lord is on the head of the just. But iniquity covers the mouth of the impious.

[[proverbs-10-7]]
^7^ The remembrance of the just is with praises. And the name of the impious shall decay.

[[proverbs-10-8]]
^8^ The wise of heart accept precepts. The foolish are cut down by the lips.

[[proverbs-10-9]]
^9^ He who walks in simplicity walks in confidence. But he who corrupts his ways shall be discovered.

[[proverbs-10-10]]
^10^ He who winks with the eye gives sorrow. And the foolish in lips shall be beaten.

[[proverbs-10-11]]
^11^ The mouth of the just is a vein of life. And the mouth of the impious covers iniquity.

[[proverbs-10-12]]
^12^ Hatred rises up from disputes. And charity covers all offenses.

[[proverbs-10-13]]
^13^ In the lips of the wise, wisdom is discovered. And a rod is for the back of one who lacks heart.

[[proverbs-10-14]]
^14^ The wise store away knowledge. But the mouth of the foolish is a neighbor to confusion.

[[proverbs-10-15]]
^15^ The substance of the rich is the city of his strength. The fear of the poor is their destitution.

[[proverbs-10-16]]
^16^ The work of the just is unto life. But the fruit of the impious is unto sin.

[[proverbs-10-17]]
^17^ The way of life is for those who observe discipline. But whoever abandons correction wanders astray.

[[proverbs-10-18]]
^18^ Lying lips conceal hatred; whoever brings forth contempt is unwise.

[[proverbs-10-19]]
^19^ In a multitude of speaking, sin will not be lacking. But whoever tempers his lips is most prudent.

[[proverbs-10-20]]
^20^ The tongue of the just is choice silver. But the heart of the impious is exchanged for nothing.

[[proverbs-10-21]]
^21^ The lips of the just instruct many. But those who are unlearned shall die in destitution of heart.

[[proverbs-10-22]]
^22^ The blessing of the Lord causes riches. Affliction will not be a companion to them.

[[proverbs-10-23]]
^23^ The foolish work wickedness as if in jest. But wisdom is prudence to a man.

[[proverbs-10-24]]
^24^ What the impious fear will overwhelm them. The just shall be given their desire.

[[proverbs-10-25]]
^25^ Like a passing tempest, so the impious one will be no more. But the just one is like an everlasting foundation.

[[proverbs-10-26]]
^26^ Like vinegar to the teeth, and smoke to the eyes, so is a lazy one to those who sent him.

[[proverbs-10-27]]
^27^ The fear of the Lord adds days. And the years of the impious will be shortened.

[[proverbs-10-28]]
^28^ The expectation of the just is rejoicing. But the hope of the impious will perish.

[[proverbs-10-29]]
^29^ The strength of the simple is the way of the Lord, and it is fear to those who work evil.

[[proverbs-10-30]]
^30^ The just in eternity shall not be moved. But the impious will not live upon the earth.

[[proverbs-10-31]]
^31^ The mouth of the just shall bring forth wisdom. The tongue of the depraved will perish.

[[proverbs-10-32]]
^32^ The lips of the just consider what is acceptable. And the mouth of the impious considers perversities.


[[proverbs-11]]
== Chapter 11

[[proverbs-11-1]]
^1^ A deceitful scale is an abomination with the Lord, and a fair weighing is his will.

[[proverbs-11-2]]
^2^ Wherever arrogance may be, there too is insult. But wherever humility is, there too is wisdom.

[[proverbs-11-3]]
^3^ The simplicity of the just shall direct them, and the rebellion of the perverse will devastate them.

[[proverbs-11-4]]
^4^ Wealth will not profit in the day of vengeance. But justice shall liberate from death.

[[proverbs-11-5]]
^5^ The justice of the simple shall direct his way. And the impious will fall in his impiety.

[[proverbs-11-6]]
^6^ The justice of the upright shall free them. And the iniquitous will be seized by their own treachery.

[[proverbs-11-7]]
^7^ When the impious man is dead, there will no longer be any hope. And the expectation of the anxious will perish.

[[proverbs-11-8]]
^8^ The just one is freed from anguish. And the impious one will be handed over instead of him.

[[proverbs-11-9]]
^9^ The pretender deceives his friend by mouth. But the just shall be freed by knowledge.

[[proverbs-11-10]]
^10^ In the good of the just, the city shall exult. And in the perdition of the impious, there shall be praise.

[[proverbs-11-11]]
^11^ By the blessing of the just, the city shall be exalted. And by the mouth of the impious, it will be subverted.

[[proverbs-11-12]]
^12^ Whoever despises his friend is destitute in heart. But the prudent man will remain silent.

[[proverbs-11-13]]
^13^ Whoever walks dishonestly reveals secrets. But whoever is of a faithful soul conceals what is confided by a friend.

[[proverbs-11-14]]
^14^ Where there is no governor, the people shall fall. But where there is much counsel, well-being shall be.

[[proverbs-11-15]]
^15^ He will be afflicted with evil, who provides a guarantee for an outsider. But whoever is wary of traps shall be secure.

[[proverbs-11-16]]
^16^ A gracious woman shall discover glory. And the robust will have wealth.

[[proverbs-11-17]]
^17^ A merciful man benefits his own soul. But whoever is cruel casts out even his close relatives.

[[proverbs-11-18]]
^18^ The impious does work with inconstancy. But for the sower of justice, there is the reward of faithfulness.

[[proverbs-11-19]]
^19^ Clemency prepares life. And the pursuit of evils prepares death.

[[proverbs-11-20]]
^20^ A depraved heart is abominable to the Lord. And his will is with those who walk in simplicity.

[[proverbs-11-21]]
^21^ Hand in hand, the evil shall not be innocent. But the offspring of the just shall be saved.

[[proverbs-11-22]]
^22^ A beautiful and senseless woman is like a gold ring in the snout of a swine.

[[proverbs-11-23]]
^23^ The desire of the just is entirely good. The anticipation of the impious is fury.

[[proverbs-11-24]]
^24^ Some distribute their own goods, and they become wealthier. Others seize what is not their own, and they are always in need.

[[proverbs-11-25]]
^25^ The soul that blesses shall be made fat. And whoever inebriates will likewise be inebriated himself.

[[proverbs-11-26]]
^26^ Whoever hides away grain shall be cursed among the people. But a blessing is upon the head of those who sell it.

[[proverbs-11-27]]
^27^ He does well to rise early, who seeks what is good. But whoever is a seeker of evils shall be oppressed by them.

[[proverbs-11-28]]
^28^ Whoever trusts in his riches will fall. But the just shall spring up like a green leaf.

[[proverbs-11-29]]
^29^ Whoever troubles his own house will possess the winds. And whoever is foolish will serve the wise.

[[proverbs-11-30]]
^30^ The fruit of the just one is the tree of life. And whoever receives souls is wise.

[[proverbs-11-31]]
^31^ If the just are repaid upon the earth, how much more the impious and the sinner!


[[proverbs-12]]
== Chapter 12

[[proverbs-12-1]]
^1^ Whoever loves discipline loves knowledge. But whoever hates correction is unwise.

[[proverbs-12-2]]
^2^ Whoever is good shall draw grace from the Lord. But whoever trusts in his own thoughts acts impiously.

[[proverbs-12-3]]
^3^ Man will not be made strong from impiety. And the root of the just shall not be moved.

[[proverbs-12-4]]
^4^ A diligent woman is a crown to her husband. And she who acts with confusion as to which things are worthy is decay to his bones.

[[proverbs-12-5]]
^5^ The thoughts of the just are judgments. And the counsels of the impious are dishonest.

[[proverbs-12-6]]
^6^ The words of the impious lie in wait for blood. The mouth of the just shall free them.

[[proverbs-12-7]]
^7^ Turn from the impious, and they will not be. But the house of the just shall stand firm.

[[proverbs-12-8]]
^8^ A man will be known by his doctrine. But whoever is vain and heartless will suffer contempt.

[[proverbs-12-9]]
^9^ Better is a pauper who has what he needs, than someone glorious and in need of bread.

[[proverbs-12-10]]
^10^ The just one knows the lives of his beasts. But the inner most parts of the impious are cruel.

[[proverbs-12-11]]
^11^ Whoever works his land shall be satisfied with bread. But whoever continually pursues leisure is most foolish. Whoever is soothed by lingering over wine leaves behind contempt in his strongholds.

[[proverbs-12-12]]
^12^ The desire of the impious is the fortification of what is most wicked. But the root of the just shall prosper.

[[proverbs-12-13]]
^13^ For the sins of the lips draw ruin to the evil. But the just shall escape from distress.

[[proverbs-12-14]]
^14^ By the fruit of his own mouth, each one shall be filled with good things, and according to the works of his own hands, it will be distributed to him.

[[proverbs-12-15]]
^15^ The way of the foolish is right in his own eyes. But whoever is wise listens to counsels.

[[proverbs-12-16]]
^16^ The senseless immediately reveals his anger. But whoever ignores injuries is clever.

[[proverbs-12-17]]
^17^ He is a sign of justice, who speaks what he knows. But whoever deceives is a dishonest witness.

[[proverbs-12-18]]
^18^ He who makes promises is also jabbed, as if with a sword, in conscience. But the tongue of the wise is reasonable.

[[proverbs-12-19]]
^19^ The lips of truth shall be steadfast forever. But a hasty witness readies a lying tongue.

[[proverbs-12-20]]
^20^ Deceit is in the heart of those who devise evils. But gladness follows those who take up counsels of peace.

[[proverbs-12-21]]
^21^ Whatever may befall the just, it will not discourage him. But the impious will be filled with disasters.

[[proverbs-12-22]]
^22^ Lying lips are an abomination to the Lord. But whoever acts faithfully pleases him.

[[proverbs-12-23]]
^23^ A resourceful man conceals knowledge. And the heart of the unwise provokes foolishness.

[[proverbs-12-24]]
^24^ The hand of the strong will rule. But anyone who is neglectful will pay tribute.

[[proverbs-12-25]]
^25^ Grief in the heart of a man humbles him. And with a good word he shall be made glad.

[[proverbs-12-26]]
^26^ He who ignores a loss for the sake of a friend is just. But the way of the impious will deceive them.

[[proverbs-12-27]]
^27^ The dishonest will not discover gain. But the substance of a man will be like precious gold.

[[proverbs-12-28]]
^28^ In the path of justice, there is life. But the devious way leads to death.


[[proverbs-13]]
== Chapter 13

[[proverbs-13-1]]
^1^ A wise son is the doctrine of his father. But he who ridicules does not listen when he is reproved.

[[proverbs-13-2]]
^2^ From the fruit of his own mouth, a man shall be satisfied with good things. But the soul of betrayers is iniquity.

[[proverbs-13-3]]
^3^ Whoever guards his mouth guards his soul. But whoever gives no consideration to his speech shall experience misfortunes.

[[proverbs-13-4]]
^4^ The lazy one is willing and then not willing. But the soul of he who labors shall be made fat.

[[proverbs-13-5]]
^5^ The just shall detest a lying word. But the impious confound and will be confounded.

[[proverbs-13-6]]
^6^ Justice guards the way of the innocent. But impiety undermines the sinner.

[[proverbs-13-7]]
^7^ One is like the rich, though he has nothing. And another is like the poor, though he has many riches.

[[proverbs-13-8]]
^8^ The redemption of a man’s life is his riches. But he who is poor cannot tolerate correction.

[[proverbs-13-9]]
^9^ The light of the just enriches. But the lamp of the impious will be extinguished.

[[proverbs-13-10]]
^10^ Among the arrogant, there are always conflicts. But those who do everything with counsel are ruled by wisdom.

[[proverbs-13-11]]
^11^ Substance obtained in haste will be diminished. But what is collected by hand, little by little, shall be multiplied.

[[proverbs-13-12]]
^12^ Hope, when it is delayed, afflicts the soul. The arrival of the desired is a tree of life.

[[proverbs-13-13]]
^13^ Whoever denounces something obligates himself for the future. But whoever fears a lesson shall turn away in peace. Deceitful souls wander into sins. The just are merciful and compassionate.

[[proverbs-13-14]]
^14^ The law of the wise is a fountain of life, so that he may turn aside from the ruin of death.

[[proverbs-13-15]]
^15^ Good doctrine bestows grace. In the way of the contemptuous, there is a chasm.

[[proverbs-13-16]]
^16^ The discerning do everything with counsel. But whoever is senseless discloses his stupidity.

[[proverbs-13-17]]
^17^ The messenger of the impious will fall into evil. But a faithful ambassador shall prosper.

[[proverbs-13-18]]
^18^ Destitution and disgrace are for those who abandon discipline. But whoever agrees with a reproof shall be glorified.

[[proverbs-13-19]]
^19^ The desired, when perfected, shall delight the soul. The foolish detest those who flee from evils.

[[proverbs-13-20]]
^20^ Whoever keeps step with the wise shall be wise. A friend of the foolish will become like them.

[[proverbs-13-21]]
^21^ Evil pursues sinners. And good things shall be distributed to the just.

[[proverbs-13-22]]
^22^ The good leave behind heirs: children and grandchildren. And the substance of the sinner is preserved for the just.

[[proverbs-13-23]]
^23^ Much nourishment is in the fallow land of the fathers. But for others, it is gathered without judgment.

[[proverbs-13-24]]
^24^ He who spares the rod hates his son. But he who loves him urgently instructs him.

[[proverbs-13-25]]
^25^ The just eats and fills his soul. But the belly of the impious is never satisfied.


[[proverbs-14]]
== Chapter 14

[[proverbs-14-1]]
^1^ A wise woman builds up her household. But a foolish one will pull down with her own hands what has been built up.

[[proverbs-14-2]]
^2^ One who walks on a virtuous journey, and who fears God, is despised by him who advances along a disreputable way.

[[proverbs-14-3]]
^3^ In the mouth of the foolish, there is a rod of arrogance. But the lips of the wise guard them.

[[proverbs-14-4]]
^4^ Where there are no oxen, the feeding trough is empty. But where there are many crops, there the strength of the ox is manifest.

[[proverbs-14-5]]
^5^ A faithful witness will not lie. But a deceitful witness offers a lie.

[[proverbs-14-6]]
^6^ A mocker seeks wisdom and does not find it. The doctrine of the prudent is accessible.

[[proverbs-14-7]]
^7^ Go against a foolish man, and he does not acknowledge lips of prudence.

[[proverbs-14-8]]
^8^ The wisdom of a discerning man is to understand his way. And the imprudence of the foolish is to be wandering astray.

[[proverbs-14-9]]
^9^ The foolish will speak mockingly of sin. But grace lingers among the just.

[[proverbs-14-10]]
^10^ The heart that knows the bitterness of its own soul, in its gladness the outsider shall not meddle.

[[proverbs-14-11]]
^11^ The house of the impious will be wiped away. Yet truly, the tabernacles of the just shall spring forth.

[[proverbs-14-12]]
^12^ There is a way which seems just to a man, but its conclusion leads to death.

[[proverbs-14-13]]
^13^ Laughter shall be mingled with sorrow, and mourning occupies the limits of joy.

[[proverbs-14-14]]
^14^ The foolish will be filled up by his own ways. And the good man shall be above him.

[[proverbs-14-15]]
^15^ The innocent trust every word. The astute one considers his own steps. Nothing good will be for the deceitful son. But the wise servant shall act prosperously and his way will be set in order.

[[proverbs-14-16]]
^16^ The wise fear, and so turn away from evil. The foolish leap ahead with confidence.

[[proverbs-14-17]]
^17^ The impatient will work foolishness. And a resourceful man is hated.

[[proverbs-14-18]]
^18^ The childish will possess foolishness, and the discerning will anticipate knowledge.

[[proverbs-14-19]]
^19^ The evil will fall down before the good. And the impious will fall down before the gates of the just.

[[proverbs-14-20]]
^20^ The pauper will be hated, even by his own neighbor. Yet truly, the friends of the wealthy are many.

[[proverbs-14-21]]
^21^ Whoever despises his neighbor, sins. But whoever pities the poor shall be blessed. Whoever trusts in the Lord loves mercy.

[[proverbs-14-22]]
^22^ They wander astray who work evil. But mercy and truth prepare good things.

[[proverbs-14-23]]
^23^ In every work, there shall be abundance. But where there are many words, there is often need.

[[proverbs-14-24]]
^24^ The crown of the wise is their wealth. The senselessness of the foolish is imprudence.

[[proverbs-14-25]]
^25^ A faithful witness frees souls. And the chameleon utters lies.

[[proverbs-14-26]]
^26^ In the fear of the Lord is the faithfulness of strength, and there shall be hope for his sons.

[[proverbs-14-27]]
^27^ The fear of the Lord is a fountain of life, so as to turn aside from the ruin of death.

[[proverbs-14-28]]
^28^ In a multitude of people, there is dignity for the king. And in a paucity of people, there is disgrace for the prince.

[[proverbs-14-29]]
^29^ Whoever is patient is governed by much prudence. But whoever is impatient exalts his foolishness.

[[proverbs-14-30]]
^30^ The well-being of the heart is life for the flesh. But envy is decay for the bones.

[[proverbs-14-31]]
^31^ Whoever slanders the indigent argues against his Maker. But he who has compassion on the poor honors his Maker.

[[proverbs-14-32]]
^32^ The impious will be expelled in his malice. But the just finds hope even in his own death.

[[proverbs-14-33]]
^33^ In the heart of the prudent, wisdom finds rest. And so shall he instruct all the uneducated.

[[proverbs-14-34]]
^34^ Justice elevates a nation. But sin makes the peoples miserable.

[[proverbs-14-35]]
^35^ An intelligent minister is acceptable to the king. Whoever is useless shall bear his wrath.


[[proverbs-15]]
== Chapter 15

[[proverbs-15-1]]
^1^ A mild response shatters anger. But a harsh word stirs up fury.

[[proverbs-15-2]]
^2^ The tongue of the wise adorns knowledge. But the mouth of the senseless gushes with foolishness.

[[proverbs-15-3]]
^3^ In every place, the eyes of the Lord consider good and evil.

[[proverbs-15-4]]
^4^ A peaceful tongue is a tree of life. But that which is immoderate will crush the spirit.

[[proverbs-15-5]]
^5^ A fool laughs at the discipline of his father. But whoever preserves rebukes will become astute. In abundant justice, there is very great virtue. But the intentions of the impious will be eradicated.

[[proverbs-15-6]]
^6^ The house of the just has very great strength. And in the fruits of the impious, there is disorder.

[[proverbs-15-7]]
^7^ The lips of the wise shall disseminate knowledge. The heart of the foolish will be dissimilar.

[[proverbs-15-8]]
^8^ The sacrifices of the impious are abominable to the Lord. The vows of the just are appeasing.

[[proverbs-15-9]]
^9^ The way of the impious is an abomination to the Lord. Whoever pursues justice is loved by him.

[[proverbs-15-10]]
^10^ Doctrine is evil to those who abandon the way of life. Whoever hates correction shall die.

[[proverbs-15-11]]
^11^ Hell and perdition are in the sight of the Lord. How much more the hearts of the sons of men!

[[proverbs-15-12]]
^12^ He who corrupts himself does not love the one who afflicts him, nor will he step toward the wise.

[[proverbs-15-13]]
^13^ A rejoicing heart gladdens the face. But by the grief of the soul, the spirit is cast down.

[[proverbs-15-14]]
^14^ The heart of the wise seeks doctrine. And the mouth of the foolish feeds on ignorance.

[[proverbs-15-15]]
^15^ All the days of the poor are evil. A secure mind is like a continual feast.

[[proverbs-15-16]]
^16^ Better is a little with the fear of the Lord, than great treasures and dissatisfaction.

[[proverbs-15-17]]
^17^ It is better to be called to vegetables with charity, than to a fatted calf with hatred.

[[proverbs-15-18]]
^18^ A short-tempered man provokes conflicts. Whoever is patient tempers those who are stirred up.

[[proverbs-15-19]]
^19^ The way of the slothful is like a hedge of thorns. The way of the just is without offense.

[[proverbs-15-20]]
^20^ A wise son gladdens the father. But the foolish man despises his mother.

[[proverbs-15-21]]
^21^ Folly is gladness to the foolish. And the prudent man sets his own steps in order.

[[proverbs-15-22]]
^22^ Intentions dissipate where there is no counsel. Yet truly, they are confirmed where there are many counselors.

[[proverbs-15-23]]
^23^ A man rejoices in the verdict of his own mouth. And a word at the right time is best.

[[proverbs-15-24]]
^24^ The path of life is for the wise above, so that he may turn away from the end of Hell.

[[proverbs-15-25]]
^25^ The Lord will demolish the house of the arrogant. And He will make firm the borders of the widow.

[[proverbs-15-26]]
^26^ Evil intentions are an abomination to the Lord. And pure conversation, most beautiful, shall be confirmed by him.

[[proverbs-15-27]]
^27^ Whoever pursues avarice disturbs his own house. But whoever hates bribes shall live. Through mercy and faith, sins are purged. But through the fear of the Lord, each one turns aside from evil.

[[proverbs-15-28]]
^28^ The mind of the just meditates on obedience. The mouth of the impious overflows with evils.

[[proverbs-15-29]]
^29^ The Lord is distant from the impious. And he will heed the prayers of the just.

[[proverbs-15-30]]
^30^ The light of the eyes rejoices the soul. A good reputation fattens the bones.

[[proverbs-15-31]]
^31^ The ear that listens to the reproofs of life shall abide in the midst of the wise.

[[proverbs-15-32]]
^32^ Whoever rejects discipline despises his own soul. But whoever agrees to correction is a possessor of the heart.

[[proverbs-15-33]]
^33^ The fear of the Lord is the discipline of wisdom. And humility precedes glory.


[[proverbs-16]]
== Chapter 16

[[proverbs-16-1]]
^1^ It is for man to prepare the soul, and for the Lord to govern the tongue.

[[proverbs-16-2]]
^2^ All the ways of a man are open to his eyes; the Lord is the one who weighs spirits.

[[proverbs-16-3]]
^3^ Open your works to the Lord, and your intentions will be set in order.

[[proverbs-16-4]]
^4^ The Lord has wrought all things because of himself. Likewise the impious is for the evil day.

[[proverbs-16-5]]
^5^ All the arrogant are an abomination to the Lord. Even if hand will be joined to hand, he is not innocent. The beginning of a good way is to do justice. And this is more acceptable with God than to immolate sacrifices.

[[proverbs-16-6]]
^6^ By mercy and truth, iniquity is redeemed. And by the fear of the Lord, one turns away from evil.

[[proverbs-16-7]]
^7^ When the ways of man will please the Lord, he will convert even his enemies to peace.

[[proverbs-16-8]]
^8^ Better is a little with justice, than many fruits with iniquity.

[[proverbs-16-9]]
^9^ The heart of man disposes his way. But it is for Lord to direct his steps.

[[proverbs-16-10]]
^10^ Foreknowledge is in the lips of the king. His mouth shall not err in judgment.

[[proverbs-16-11]]
^11^ Weights and scales are judgments of the Lord. And all the stones in the bag are his work.

[[proverbs-16-12]]
^12^ Those who act impiously are abominable to the king. For the throne is made firm by justice.

[[proverbs-16-13]]
^13^ Just lips are the will of kings. He who speaks honestly shall be loved.

[[proverbs-16-14]]
^14^ The indignation of a king is a herald of death. And the wise man will appease it.

[[proverbs-16-15]]
^15^ In the cheerfulness of the king’s countenance, there is life. And his clemency is like belated rain.

[[proverbs-16-16]]
^16^ Possess wisdom, for it is better than gold. And acquire prudence, for it is more precious than silver.

[[proverbs-16-17]]
^17^ The path of the just turns away from evils. He who guards his soul preserves his way.

[[proverbs-16-18]]
^18^ Arrogance precedes destruction. And the spirit is exalted before a fall.

[[proverbs-16-19]]
^19^ It is better to be humbled with the meek, than to divide spoils with the arrogant.

[[proverbs-16-20]]
^20^ The learned in word shall find good things. And whoever hopes in the Lord is blessed.

[[proverbs-16-21]]
^21^ Whoever is wise in heart shall be called prudent. And whoever is sweet in eloquence shall attain to what is greater.

[[proverbs-16-22]]
^22^ Learning is a fountain of life to one who possesses it. The doctrine of the foolish is senseless.

[[proverbs-16-23]]
^23^ The heart of the wise shall instruct his mouth and add grace to his lips.

[[proverbs-16-24]]
^24^ Careful words are a honeycomb: sweet to the soul and healthful to the bones.

[[proverbs-16-25]]
^25^ There is a way which seems right to a man, and its end result leads to death.

[[proverbs-16-26]]
^26^ The soul of the laborer labors for himself, because his mouth has driven him to it.

[[proverbs-16-27]]
^27^ The impious man digs up evil, and in his lips is a burning fire.

[[proverbs-16-28]]
^28^ A perverse man stirs up lawsuits. And one who is verbose divides leaders.

[[proverbs-16-29]]
^29^ A man of iniquity entices his friend, and he leads him along a way that is not good.

[[proverbs-16-30]]
^30^ Whoever, with astonished eyes, thinks up depravities, biting his lips, accomplishes evil.

[[proverbs-16-31]]
^31^ Old age is a crown of dignity, when it is found in the ways of justice.

[[proverbs-16-32]]
^32^ A patient man is better than a strong one. And whoever rules his soul is better than one who assaults cities.

[[proverbs-16-33]]
^33^ Lots are cast into the lap, but they are tempered by the Lord.


[[proverbs-17]]
== Chapter 17

[[proverbs-17-1]]
^1^ A dry morsel with gladness is better than a house full of sacrifices along with conflict.

[[proverbs-17-2]]
^2^ A wise servant shall rule over foolish sons, and he will divide the inheritance among brothers.

[[proverbs-17-3]]
^3^ Just as silver is tested by fire, and gold is tested in the furnace, so also does the Lord test hearts.

[[proverbs-17-4]]
^4^ The evil obey an unjust tongue. And the false are submissive to lying lips.

[[proverbs-17-5]]
^5^ Whoever despises the poor rebukes his Maker. And whoever rejoices in the ruin of another will not go unpunished.

[[proverbs-17-6]]
^6^ Sons of sons are the crown of old age. And the glory of sons is their fathers.

[[proverbs-17-7]]
^7^ Well-chosen words are not fitting for the foolish, nor are lying lips fitting for a leader.

[[proverbs-17-8]]
^8^ The expectation of those who stand ready is a most pleasing jewel. Whichever way he turns himself, he understands prudently.

[[proverbs-17-9]]
^9^ Whoever conceals an offense seeks friendships. Whoever repeats the words of another separates allies.

[[proverbs-17-10]]
^10^ A correction benefits more with a wise man, than a hundred stripes with a fool.

[[proverbs-17-11]]
^11^ The evil one continually seeks conflicts. But a cruel Angel shall be sent against him.

[[proverbs-17-12]]
^12^ It is more expedient to meet a bear robbed of her young, than the foolish trusting in his own folly.

[[proverbs-17-13]]
^13^ Whoever repays evil for good, evil shall not withdraw from his house.

[[proverbs-17-14]]
^14^ Whoever releases the water is the head of the conflict. And just before he suffers contempt, he abandons judgment.

[[proverbs-17-15]]
^15^ Those who justify the impious, and those who condemn the just, both are abominable with God.

[[proverbs-17-16]]
^16^ What does it profit the foolish to have riches, when he is not able to buy wisdom? Whoever makes his house high seeks ruin. And whoever shuns learning shall fall into evils.

[[proverbs-17-17]]
^17^ Whoever is a friend loves at all times. And a brother is proved by distress.

[[proverbs-17-18]]
^18^ A foolish man will clap his hands, when he makes a pledge for his friend.

[[proverbs-17-19]]
^19^ Whoever dwells on discord loves disputes. And whoever exalts his door seeks ruin.

[[proverbs-17-20]]
^20^ Whoever is of a perverse heart shall not find good. And whoever turns his tongue shall fall into evil.

[[proverbs-17-21]]
^21^ A foolish one is born into his own disgrace. But his father will not rejoice in one who is senseless.

[[proverbs-17-22]]
^22^ A joyful soul makes a lifetime flourish. A gloomy spirit dries out the bones.

[[proverbs-17-23]]
^23^ The impious receives gifts from the bosom, so that he may pervert the paths of judgment.

[[proverbs-17-24]]
^24^ Prudence shines from the face of the wise. The eyes of the foolish are on the ends of the earth.

[[proverbs-17-25]]
^25^ A foolish son is the anger of the father and the grief of the mother who conceived him.

[[proverbs-17-26]]
^26^ It is not good to inflict damage on the just, nor to strike the leader who judges uprightly.

[[proverbs-17-27]]
^27^ Whoever moderates his words is learned and prudent. And a man of learning has a precious spirit.

[[proverbs-17-28]]
^28^ If he would remain silent, even the foolish would be considered wise, and if he closes his lips, intelligent.


[[proverbs-18]]
== Chapter 18

[[proverbs-18-1]]
^1^ Whoever has a will to withdraw from a friend, seeks occasions; he shall be reproached at all times.

[[proverbs-18-2]]
^2^ The foolish do not accept words of prudence, unless you say what is already turning in his heart.

[[proverbs-18-3]]
^3^ The impious, when he has arrived within the depths of sin, thinks little of it. But ill repute and disgrace follow him.

[[proverbs-18-4]]
^4^ Words from the mouth of a man are deep waters. And the fountain of wisdom is a torrent overflowing.

[[proverbs-18-5]]
^5^ It is not good to accept the character of the impious, so as to turn away from true judgment.

[[proverbs-18-6]]
^6^ The lips of the foolish meddle in disputes. And his mouth provokes conflicts.

[[proverbs-18-7]]
^7^ The mouth of the foolish is his destruction, and his own lips are the ruin of his soul.

[[proverbs-18-8]]
^8^ The words of the double-tongued seem simple. And they reach even to the interior of the gut. Fear casts down the lazy, but the souls of the effeminate shall go hungry.

[[proverbs-18-9]]
^9^ Whoever is dissolute and slack in his work is the brother of him who wastes his own works.

[[proverbs-18-10]]
^10^ The name of the Lord is a very strong tower. The just one rushes to it, and he shall be exalted.

[[proverbs-18-11]]
^11^ The substance of the wealthy is the city of his strength, and it is like a strong wall encircling him.

[[proverbs-18-12]]
^12^ The heart of a man is exalted before it is crushed and humbled before it is glorified.

[[proverbs-18-13]]
^13^ Whoever responds before he listens, demonstrates himself to be foolish and deserving of confusion.

[[proverbs-18-14]]
^14^ The spirit of a man sustains his weakness. Yet who can sustain a spirit that is easily angered?

[[proverbs-18-15]]
^15^ A prudent heart shall possess knowledge. And the ear of the wise seeks doctrine.

[[proverbs-18-16]]
^16^ A man’s gift expands his way and makes space for him before leaders.

[[proverbs-18-17]]
^17^ The just is the first accuser of himself; his friend arrives and shall investigate him.

[[proverbs-18-18]]
^18^ Casting a lot suppresses contentions and passes judgment, even among the powerful.

[[proverbs-18-19]]
^19^ A brother who is helped by a brother is like a reinforced city, and judgments are like the bars of cities.

[[proverbs-18-20]]
^20^ From the fruit of a man’s mouth shall his belly be filled. And the harvest of his own lips shall satisfy him.

[[proverbs-18-21]]
^21^ Death and life are in the power of the tongue. Whoever values it shall eat from its fruits.

[[proverbs-18-22]]
^22^ He who has found a good wife has found goodness, and he shall draw contentment from the Lord. He who expels a good wife expels goodness. But he who holds on to an adulteress is foolish and impious.

[[proverbs-18-23]]
^23^ The poor will speak with supplications. And the rich will express themselves roughly.

[[proverbs-18-24]]
^24^ A man amiable to society shall be more friendly than a brother.


[[proverbs-19]]
== Chapter 19

[[proverbs-19-1]]
^1^ Better is the poor who walks in his simplicity, than the rich who twists his lips and is unwise.

[[proverbs-19-2]]
^2^ Where there is no knowledge of the soul, there is no good. And whoever hurries with his feet will stumble.

[[proverbs-19-3]]
^3^ The foolishness of a man undermines his steps. And then he seethes in his soul against God.

[[proverbs-19-4]]
^4^ Riches add many friends. But from the pauper, even those whom he had become separated.

[[proverbs-19-5]]
^5^ A false witness shall not go unpunished. And whoever speaks lies will not escape.

[[proverbs-19-6]]
^6^ Many honor the character of one who is powerful, and there are friends for a giver of gifts.

[[proverbs-19-7]]
^7^ The brothers of the poor man hate him. Moreover, even his friends have withdrawn far from him. Whoever pursues only words shall have nothing.

[[proverbs-19-8]]
^8^ But whoever possesses reason loves his own soul. And one who guards prudence shall discover good things.

[[proverbs-19-9]]
^9^ A false witness shall not go unpunished. And whoever speaks lies will perish.

[[proverbs-19-10]]
^10^ Fine things are not fitting for the foolish, nor is it fitting for a servant to rule over princes.

[[proverbs-19-11]]
^11^ The doctrine of a man is known through patience. And his glory is to pass beyond iniquities.

[[proverbs-19-12]]
^12^ Like the roaring of a lion, so also is the wrath of a king. And his cheerfulness is like the dew upon the grass.

[[proverbs-19-13]]
^13^ A foolish son is the grief of his father. And an argumentative wife is like a roof that is continually leaking.

[[proverbs-19-14]]
^14^ A house and its riches are given by parents. But a prudent wife is particularly from the Lord.

[[proverbs-19-15]]
^15^ Laziness sends one into a deep sleep, and a dissolute soul will go hungry.

[[proverbs-19-16]]
^16^ Whoever guards a commandment guards his own soul. But whoever neglects his own way will die.

[[proverbs-19-17]]
^17^ Whoever is merciful to the poor lends to the Lord. And he will repay him for his efforts.

[[proverbs-19-18]]
^18^ Teach your son; do not despair. But do not set your soul toward putting him to death.

[[proverbs-19-19]]
^19^ Whoever is impatient will sustain damage. And when it has been taken away, he will set up another.

[[proverbs-19-20]]
^20^ Listen to counsel and take up discipline, so that you may be wise in your latter days.

[[proverbs-19-21]]
^21^ There are many intentions in the heart of a man. But the will of the Lord shall stand firm.

[[proverbs-19-22]]
^22^ An indigent man is merciful. And a pauper is better than a deceitful man.

[[proverbs-19-23]]
^23^ The fear of the Lord is unto life. And he shall linger in plentitude, without being visited by disaster.

[[proverbs-19-24]]
^24^ The lazy conceals his hand under his arm, and he will not so much as bring it to his mouth.

[[proverbs-19-25]]
^25^ When the pestilent are scourged, the foolish will become wiser. But if you chastise the wise, he will understand discipline.

[[proverbs-19-26]]
^26^ Whoever afflicts his father and flees from his mother is disreputable and unhappy.

[[proverbs-19-27]]
^27^ Son, do not cease listening to doctrine, and do not be ignorant of the sermons of knowledge.

[[proverbs-19-28]]
^28^ An unjust witness ridicules judgment. And the mouth of the impious devours iniquity.

[[proverbs-19-29]]
^29^ Judgments are prepared for those who ridicule. And striking hammers are prepared for the bodies of the foolish.


[[proverbs-20]]
== Chapter 20

[[proverbs-20-1]]
^1^ It is a luxurious thing, wine, and inebriation is tumultuous. Anyone who is delighted by this will not be wise.

[[proverbs-20-2]]
^2^ Just like the roaring of a lion, so also is the dread of a king. Whoever provokes him sins in his own soul.

[[proverbs-20-3]]
^3^ Honor is for the man who separates himself from contentions. But all the foolish meddle in altercations.

[[proverbs-20-4]]
^4^ Because of the cold, the lazy one was not willing to plough. Therefore, in the summer, he will beg, and it will not be given to him.

[[proverbs-20-5]]
^5^ Counsel in the heart of a man is like deep waters. But a wise man will draw it out.

[[proverbs-20-6]]
^6^ Many men are called merciful. But who will find a faithful man?

[[proverbs-20-7]]
^7^ The just who walks in his simplicity shall leave behind him blessed sons.

[[proverbs-20-8]]
^8^ The king who sits on the throne of judgment scatters all evil with his gaze.

[[proverbs-20-9]]
^9^ Who is able to say: “My heart is clean. I am pure from sin?”

[[proverbs-20-10]]
^10^ Diverse weights, diverse measures: both are abominable with God.

[[proverbs-20-11]]
^11^ A child may be understood by his interests: whether his works may be clean and upright.

[[proverbs-20-12]]
^12^ The hearing ear and the seeing eye: the Lord has made them both.

[[proverbs-20-13]]
^13^ Do not love sleep, lest deprivation oppress you. Open your eyes and be satisfied with bread.

[[proverbs-20-14]]
^14^ “It is bad, it is bad,” says every buyer; and when he has withdrawn, then he will boast.

[[proverbs-20-15]]
^15^ There is gold, and there are a multitude of jewels. But lips of knowledge are a precious vessel.

[[proverbs-20-16]]
^16^ Take away the vestments of him who stands up to vouch for a stranger, and take a pledge from him instead of from outsiders.

[[proverbs-20-17]]
^17^ The bread of lies is sweet to a man. But afterwards, his mouth will be filled with pebbles.

[[proverbs-20-18]]
^18^ Plans are strengthened by counsels. And wars are to be handled by governments.

[[proverbs-20-19]]
^19^ Do not become involved with him who reveals mysteries, and who walks deceitfully, and who enlarges his lips.

[[proverbs-20-20]]
^20^ Whoever curses his father and mother, his lamp will be extinguished in the midst of darkness.

[[proverbs-20-21]]
^21^ When an inheritance is obtained hastily in the beginning, in the end it will be without a blessing.

[[proverbs-20-22]]
^22^ Do not say, “I will repay evil.” Wait for the Lord, and he will free you.

[[proverbs-20-23]]
^23^ Diverse weights are an abomination with the Lord. A deceitful balance is not good.

[[proverbs-20-24]]
^24^ The steps of men are directed by the Lord. But who is the man able to understand his own way?

[[proverbs-20-25]]
^25^ It is ruin for a man to devour what is holy, or, after making vows, to retract them.

[[proverbs-20-26]]
^26^ A wise king scatters the impious and bends an archway over them.

[[proverbs-20-27]]
^27^ The spirit of a man is a lamp to the Lord, which investigates all the secrets of the inner self.

[[proverbs-20-28]]
^28^ Mercy and truth guard the king, and his throne is strengthened by clemency.

[[proverbs-20-29]]
^29^ The joy of youths is their strength. And the dignity of old men is their grey hairs.

[[proverbs-20-30]]
^30^ The bruise of a wound, as well as scourges, shall wipe away evils in the more secret places of the inner self.


[[proverbs-21]]
== Chapter 21

[[proverbs-21-1]]
^1^ Just as with the dividing of the waters, so also is the heart of the king in the hand of the Lord. He shall bend it whichever way he wills.

[[proverbs-21-2]]
^2^ Every way of a man seems right to himself. But the Lord weighs hearts.

[[proverbs-21-3]]
^3^ To do mercy and judgment is more pleasing to the Lord than sacrifices.

[[proverbs-21-4]]
^4^ To lift up the eyes is to enlarge the heart. The lamp of the impious is sin.

[[proverbs-21-5]]
^5^ The intentions of the robust continually bring forth abundance. But all the lazy are continually in need.

[[proverbs-21-6]]
^6^ Whoever gathers treasures by a lying tongue is vain and heartless. And he will stumble into the snares of death.

[[proverbs-21-7]]
^7^ The robberies of the impious will drag them down, because they were not willing to do judgment.

[[proverbs-21-8]]
^8^ The perverse way of a man is foreign. But whoever is pure: his work is upright.

[[proverbs-21-9]]
^9^ It is better to sit in a corner of the attic, than with a contentious woman and in a shared house.

[[proverbs-21-10]]
^10^ The soul of the impious desires evil; he will not take pity on his neighbor.

[[proverbs-21-11]]
^11^ When the pestilent is punished, a little one will become wiser. And if he pursues what is wise, he will receive knowledge.

[[proverbs-21-12]]
^12^ The just thinks carefully about the house of the impious, so that he may draw the impious away from evil.

[[proverbs-21-13]]
^13^ Whoever blocks his ears to the outcry of the poor shall also cry out himself, and he will not be heeded.

[[proverbs-21-14]]
^14^ A surprise gift extinguishes anger. And a gift concealed in the bosom extinguishes the greatest indignation.

[[proverbs-21-15]]
^15^ It is gladness for the just to do judgment; and it is dread for those who work iniquity.

[[proverbs-21-16]]
^16^ A man who wanders astray from the way of doctrine will linger in the company of the giants.

[[proverbs-21-17]]
^17^ Whoever loves a feast will be in deprivation. Whoever loves wine and fatness will not be enriched.

[[proverbs-21-18]]
^18^ The impious is given over instead of the just, and the iniquitous is given over in place of the upright.

[[proverbs-21-19]]
^19^ It is better to live in a deserted land, than with a quarrelsome and emotional woman.

[[proverbs-21-20]]
^20^ There is desirable treasure, as well as oil, in the habitations of the just. And the imprudent man will waste it.

[[proverbs-21-21]]
^21^ Whoever follows justice and mercy shall discover life, justice, and glory.

[[proverbs-21-22]]
^22^ The wise has ascended the city of the strong, and he has torn down the bulwark of its confidence.

[[proverbs-21-23]]
^23^ Whoever guards his mouth and his tongue guards his soul from anguish.

[[proverbs-21-24]]
^24^ A proud and arrogant one is also called ignorant, if he, in anger, acts according to pride.

[[proverbs-21-25]]
^25^ Desires kill the lazy, for his hands are not willing to work at all.

[[proverbs-21-26]]
^26^ He covets and desires all day long. But whoever is just shall distribute and shall not cease.

[[proverbs-21-27]]
^27^ The sacrifices of the impious are abominable, because they are offered out of wickedness.

[[proverbs-21-28]]
^28^ A lying witness will perish. An obedient man shall speak of victory.

[[proverbs-21-29]]
^29^ The impious man insolently hardens his face. But whoever is upright corrects his own way.

[[proverbs-21-30]]
^30^ There is no wisdom, there is no prudence, there is no counsel, which is against the Lord.

[[proverbs-21-31]]
^31^ The horse is prepared for the day of battle. But the Lord bestows salvation.


[[proverbs-22]]
== Chapter 22

[[proverbs-22-1]]
^1^ A good name is better than many riches. And good esteem is above silver and gold.

[[proverbs-22-2]]
^2^ The rich and poor have met one another. The Lord is the maker of them both.

[[proverbs-22-3]]
^3^ The clever saw evil and hid himself. The innocent continued on and was afflicted with damage.

[[proverbs-22-4]]
^4^ The end of moderation is the fear of the Lord, riches and glory and life.

[[proverbs-22-5]]
^5^ Weapons and swords are on the way of the perverse. But he who guards his own soul withdraws far from them.

[[proverbs-22-6]]
^6^ The proverb is: A youth is close to his way; even when he is old, he will not withdraw from it.

[[proverbs-22-7]]
^7^ The rich rule over the poor. And the borrower is servant to the lender.

[[proverbs-22-8]]
^8^ Whoever sows iniquity will reap evils, and by the rod of his own wrath he will be consumed.

[[proverbs-22-9]]
^9^ Whoever is inclined to mercy shall be blessed, for from his bread he has given to the poor. Whoever gives gifts will acquire victory and honor. But he carries away the soul of the receiver.

[[proverbs-22-10]]
^10^ Cast out the one who ridicules, and conflict will go out with him, and accusations and insults will cease.

[[proverbs-22-11]]
^11^ Whoever loves cleanness of heart, because of the grace of his lips, will have the king as his friend.

[[proverbs-22-12]]
^12^ The eyes of the Lord watch over knowledge. And the words of the iniquitous are supplanted.

[[proverbs-22-13]]
^13^ The lazy one says: “There is a lion outside. I might be slain in the midst of the streets.”

[[proverbs-22-14]]
^14^ The mouth of a foreign woman is a deep pit; the Lord was angry with him who will fall into it.

[[proverbs-22-15]]
^15^ Foolishness has been bound to the heart of a child, and a rod of discipline shall cause it to flee.

[[proverbs-22-16]]
^16^ Whoever slanders the poor, so as to augment his own riches, will give it away to one who is richer, and will be in need.

[[proverbs-22-17]]
^17^ Incline your ear, and listen to the words of the wise. Then apply your heart to my doctrine.

[[proverbs-22-18]]
^18^ It shall be beautiful to you, if you preserve it in your inner self, and it shall overflow from your lips,

[[proverbs-22-19]]
^19^ so that your confidence may be in the Lord. Therefore, I also have revealed it to you this day.

[[proverbs-22-20]]
^20^ Behold, I have written it for you in three ways, and with meditations and knowledge,

[[proverbs-22-21]]
^21^ so that I might reveal to you, firmly and with words of truth, in order to respond about these things to those who sent you.

[[proverbs-22-22]]
^22^ Do not act with violence toward the pauper because he is poor. And do not weary the needy at the gate.

[[proverbs-22-23]]
^23^ For the Lord will judge his case, and he will pierce those who have pierced his soul.

[[proverbs-22-24]]
^24^ Do not be willing to be a friend to an angry man, and do not walk with a furious man,

[[proverbs-22-25]]
^25^ lest perhaps you learn his ways, and take up a stumbling block to your soul.

[[proverbs-22-26]]
^26^ Do not be willing to be with those who certify with their hands, and who offer themselves as a guarantee against debts.

[[proverbs-22-27]]
^27^ For if you do not have the means to restore, what reason should there be for him to take the covering from your bed?

[[proverbs-22-28]]
^28^ Do not cross beyond the ancient limits that your fathers have set.

[[proverbs-22-29]]
^29^ Have you seen a man swift in his work? He shall stand in the sight of kings, and not before those who are disreputable.


[[proverbs-23]]
== Chapter 23

[[proverbs-23-1]]
^1^ When you sit down to eat with a leader, pay close attention to what has been set before your face,

[[proverbs-23-2]]
^2^ and put a knife to your throat, if, in such a way, you could hold your soul in your own power.

[[proverbs-23-3]]
^3^ Do not desire his foods, in which is the bread of deceit.

[[proverbs-23-4]]
^4^ Do not be willing to labor so that you may be enriched. But set limits by your prudence.

[[proverbs-23-5]]
^5^ Do not raise your eyes toward wealth that you are not able to have. For they will make themselves wings, like those of an eagle, and they will fly in the sky.

[[proverbs-23-6]]
^6^ Do not eat with an envious man, and do not desire his foods.

[[proverbs-23-7]]
^7^ For, like a seer and an interpreter of dreams, he presumes what he does not know. “Eat and drink,” he will say to you; and his mind is not with you.

[[proverbs-23-8]]
^8^ The foods that you had eaten, you will vomit up. And you will lose the beauty in your words.

[[proverbs-23-9]]
^9^ Do not speak into the ears of the unwise. They will despise the doctrine of your eloquence.

[[proverbs-23-10]]
^10^ Do not touch the boundaries of little ones, and do not enter into the field of the fatherless.

[[proverbs-23-11]]
^11^ For their close relative is strong, and he will judge their case against you.

[[proverbs-23-12]]
^12^ Let your heart enter into doctrine, and let your ears enter into words of knowledge.

[[proverbs-23-13]]
^13^ Do not be willing to take away discipline from a child. For if you strike him with the rod, he will not die.

[[proverbs-23-14]]
^14^ You will strike him with the rod, and so shall you deliver his soul from Hell.

[[proverbs-23-15]]
^15^ My son, if your soul will become wise, my heart will be glad with you.

[[proverbs-23-16]]
^16^ And my temperament will exult, when your lips will have spoken what is upright.

[[proverbs-23-17]]
^17^ Let not your heart compete with sinners. But be in the fear of the Lord all day long.

[[proverbs-23-18]]
^18^ For you will have hope in the end, and your expectation will not be taken away.

[[proverbs-23-19]]
^19^ Listen, my son, and be wise, and direct your soul along the way.

[[proverbs-23-20]]
^20^ Do not be willing to be in the feasts of great drinkers, nor in the carousings of those who gather to feed on flesh.

[[proverbs-23-21]]
^21^ For those who waste time drinking, and who surrender themselves to symbols, will be consumed. And those who sleep will be clothed in rags.

[[proverbs-23-22]]
^22^ Listen to your father, who conceived you. And do not despise your mother, when she is old.

[[proverbs-23-23]]
^23^ Purchase truth, and do not sell wisdom, or doctrine, or understanding.

[[proverbs-23-24]]
^24^ The father of the just exults in gladness; he who has conceived the wise will rejoice in him.

[[proverbs-23-25]]
^25^ Let your father and your mother be joyful, and may she who conceived you exult.

[[proverbs-23-26]]
^26^ My son, offer me your heart, and let your eyes keep to my ways.

[[proverbs-23-27]]
^27^ For a loose woman is a deep pit, and a foreign woman is a constricted well.

[[proverbs-23-28]]
^28^ She lies in wait along the way like a robber. And the incautious one whom she sees, she will put to death.

[[proverbs-23-29]]
^29^ Who has woe? Whose father has woe? Who has quarrels? Who falls into pits? Who has wounds without cause? Who has watery eyes?

[[proverbs-23-30]]
^30^ Is it not those who linger over wine, and who strive to be drinking from their cups?

[[proverbs-23-31]]
^31^ Do not gaze into the wine when it turns gold, when its color shines in the glass. It enters pleasantly,

[[proverbs-23-32]]
^32^ but in the end, it will bite like a snake, and it will spread poison like a king of snakes.

[[proverbs-23-33]]
^33^ Your eyes will see women who are outsiders, and your heart will utter perversities.

[[proverbs-23-34]]
^34^ And you will be like someone sleeping in the middle of the sea, and like a pilot, fast asleep, who has lost his hold on the helm.

[[proverbs-23-35]]
^35^ And you will say: “They have beaten me, but I did not feel pain. They have dragged me, and I did not realize it. When will I awaken and find more wine?”


[[proverbs-24]]
== Chapter 24

[[proverbs-24-1]]
^1^ Do not imitate evil men, nor desire to be among them.

[[proverbs-24-2]]
^2^ For their mind meditates on robberies, and their lips speak deceptions.

[[proverbs-24-3]]
^3^ By wisdom shall a house be built, and by prudence shall it be strengthened.

[[proverbs-24-4]]
^4^ By doctrine, the storerooms shall be filled with every substance that is precious and most beautiful.

[[proverbs-24-5]]
^5^ A wise man is strong, and a well-taught man is robust and valiant.

[[proverbs-24-6]]
^6^ For war is undertaken in an orderly manner, and safety shall be where there are many counsels.

[[proverbs-24-7]]
^7^ Wisdom is beyond the foolish; at the gate he will not open his mouth.

[[proverbs-24-8]]
^8^ Whoever intends to do evil shall be called foolish.

[[proverbs-24-9]]
^9^ The intention of the foolish is sin. And the detractor is an abomination among men.

[[proverbs-24-10]]
^10^ If you despair, being weary in the day of anguish, your strength will be diminished.

[[proverbs-24-11]]
^11^ Rescue those who are led away to death. And do not cease from delivering those who are dragged away to a violent death.

[[proverbs-24-12]]
^12^ If you would say: “I do not have sufficient strength.” He who inspects the heart, the same one understands, and nothing slips past the one who preserves your soul. And he shall repay a man according to his works.

[[proverbs-24-13]]
^13^ My son, eat honey, because it is good, and the honeycomb, because it is so sweet to your throat.

[[proverbs-24-14]]
^14^ So, too, is the doctrine of wisdom to your soul. When you have found it, you will have hope in the end, and your hope shall not perish.

[[proverbs-24-15]]
^15^ Do not lie in wait, and do not seek impiety in the house of the just, nor spoil his rest.

[[proverbs-24-16]]
^16^ For the just one will fall seven times, and he shall rise again. But the impious will fall into evil.

[[proverbs-24-17]]
^17^ When your enemy will fall, do not be glad, and do not let your heart exult in his ruin,

[[proverbs-24-18]]
^18^ lest perhaps the Lord see, and it displease him, and he may take away his wrath from him.

[[proverbs-24-19]]
^19^ Do not contend with the most wicked, and do not be a rival to the impious.

[[proverbs-24-20]]
^20^ For the evil hold no hope in the future, and the lamp of the impious will be extinguished.

[[proverbs-24-21]]
^21^ My son, fear the Lord, as well as the king. And do not mingle with detractors.

[[proverbs-24-22]]
^22^ For their perdition shall rise up suddenly. And who knows what ruin will be for each of them?

[[proverbs-24-23]]
^23^ Likewise, these things are for the wise. It is not good to base judgment on knowledge of character.

[[proverbs-24-24]]
^24^ Those who say to the impious, “You are just,” shall be cursed by the people, and the tribes shall detest them.

[[proverbs-24-25]]
^25^ Those who argue against the impious shall be praised, and a blessing shall come upon them.

[[proverbs-24-26]]
^26^ He shall kiss the lips, who responds with upright words.

[[proverbs-24-27]]
^27^ Prepare your outdoor work, and diligently cultivate your field, so that afterward, you may build your house.

[[proverbs-24-28]]
^28^ Do not be a witness without cause against your neighbor. And do not mislead anyone with your lips.

[[proverbs-24-29]]
^29^ Do not say, “I will do to him as he has done to me.” I will repay each one according to his work.

[[proverbs-24-30]]
^30^ I passed by the field of a lazy man, and by the vineyard of a foolish man,

[[proverbs-24-31]]
^31^ and behold, it was entirely filled with nettles, and thorns had covered its surface, and the stonewall was destroyed.

[[proverbs-24-32]]
^32^ When I had seen this, I laid it up in my heart, and by this example, I received discipline.

[[proverbs-24-33]]
^33^ You will sleep a little,” I said. “You will slumber briefly. You will fold your hands a little, so as to rest.

[[proverbs-24-34]]
^34^ And destitution will overtake you like a runner, and begging will overtake you like an armed man.”


[[proverbs-25]]
== Chapter 25

[[proverbs-25-1]]
^1^ These, too, are parables of Solomon, which the men of Hezekiah, king of Judah, transferred.

[[proverbs-25-2]]
^2^ It is to the glory of God to conceal a word, and it is to the glory of kings to investigate speech.

[[proverbs-25-3]]
^3^ Heaven above, and earth below, and the heart of kings are each unsearchable.

[[proverbs-25-4]]
^4^ Take away the tarnish from silver, and a most pure vessel will go forth.

[[proverbs-25-5]]
^5^ Take away impiety from the face of the king, and his throne shall be made firm by justice.

[[proverbs-25-6]]
^6^ Do not appear glorious before the king, and do not stand in the place of the great.

[[proverbs-25-7]]
^7^ For it is better that it should be said to you, “Ascend to here,” than that you should be humbled before the prince.

[[proverbs-25-8]]
^8^ The things that your eyes have seen, do not offer hastily in a quarrel, lest afterward you may not be able to make amends, when you have dishonored your friend.

[[proverbs-25-9]]
^9^ Argue your case with your friend, and do not reveal the secret to an outsider,

[[proverbs-25-10]]
^10^ lest perhaps he may insult you, when he has heard it, and he might not cease to reproach you. Grace and friendship free a man; preserve these for yourself, lest you fall under reproach.

[[proverbs-25-11]]
^11^ Whoever speaks a word at an opportune time is like apples of gold on beds of silver.

[[proverbs-25-12]]
^12^ Whoever reproves the wise and obedient ear is like an earring of gold with a shining pearl.

[[proverbs-25-13]]
^13^ Just like the cold of snow in a time of harvest, so also is a faithful messenger to him who sent him: he causes his soul to rest.

[[proverbs-25-14]]
^14^ A man who boasts and does not fulfill his promises is like clouds and wind, when rain does not follow.

[[proverbs-25-15]]
^15^ By patience, a leader shall be appeased, and a soft tongue shall break hardness.

[[proverbs-25-16]]
^16^ You have discovered honey; eat what is sufficient for you, lest perhaps, being filled up, you may vomit it.

[[proverbs-25-17]]
^17^ Withdraw your feet from the house of your neighbor, lest, when he has had his fill, he may hate you.

[[proverbs-25-18]]
^18^ A man who speaks false testimony against his neighbor is like a dart and a sword and a sharp arrow.

[[proverbs-25-19]]
^19^ Whoever sets his hopes on the unfaithful in a day of anguish is like a rotten tooth and weary foot,

[[proverbs-25-20]]
^20^ and like one who loosens his garment in cold weather. Whoever sings verses to a wicked heart is like vinegar on baking soda. Just like a moth to a garment, and a worm to wood, so too does the sadness of a man do harm to the heart.

[[proverbs-25-21]]
^21^ If your enemy is hungry, feed him. If he is thirsty, give him water to drink.

[[proverbs-25-22]]
^22^ For you will gather hot coals upon his head, and the Lord will repay you.

[[proverbs-25-23]]
^23^ The north wind brings forth the rain, and a sorrowful face brings forth a detracting tongue.

[[proverbs-25-24]]
^24^ It is better to sit in a corner of the attic, than with an argumentative woman and in a shared house.

[[proverbs-25-25]]
^25^ Like cold water to a thirsty soul, so too are good reports from a far away land.

[[proverbs-25-26]]
^26^ The just falling down before the impious is like a fountain stirred up by feet and like a corrupted spring.

[[proverbs-25-27]]
^27^ Just as whoever eats too much honey, it is not good for him, so also whoever is an investigator of what is majestic will be overwhelmed by glory.

[[proverbs-25-28]]
^28^ Just like a city lying in the open and without surrounding walls, so also is a man who is unable to restrain his own spirit in speaking.


[[proverbs-26]]
== Chapter 26

[[proverbs-26-1]]
^1^ In the manner of snow in the summer, and rain at the harvest, so also is glory unfit for the foolish.

[[proverbs-26-2]]
^2^ Like a bird flying away to another place, and like a sparrow that hurries away freely, so also a curse uttered against someone without cause will pass away.

[[proverbs-26-3]]
^3^ A whip is for a horse, and a muzzle is for donkey, and a rod is for the back of the imprudent.

[[proverbs-26-4]]
^4^ Do not respond to the foolish according to his folly, lest you become like him.

[[proverbs-26-5]]
^5^ Respond to the foolish according to his folly, lest he imagine himself to be wise.

[[proverbs-26-6]]
^6^ Whoever sends words by a foolish messenger has lame feet and drinks iniquity.

[[proverbs-26-7]]
^7^ In the manner of a lame man who has beautiful legs to no purpose, so also is a parable unfit for the mouth of the foolish.

[[proverbs-26-8]]
^8^ Just like one who casts a stone into the pile of Mercury, so also is he who gives honor to the foolish.

[[proverbs-26-9]]
^9^ In the manner of a thorn, if it were to spring up from the hand of a drunkard, so also is a parable in the mouth of the foolish.

[[proverbs-26-10]]
^10^ Judgment determines cases. And whoever imposes silence on the foolish mitigates anger.

[[proverbs-26-11]]
^11^ Like a dog that returns to his vomit, so also is the imprudent who repeats his foolishness.

[[proverbs-26-12]]
^12^ Have you seen a man who seems wise to himself? There will be greater hope held for the unwise than for him.

[[proverbs-26-13]]
^13^ The lazy one says, “There is a lion along the way, and a lioness in the roads.”

[[proverbs-26-14]]
^14^ Just as a door turns upon its hinges, so also does the lazy one turn upon his bed.

[[proverbs-26-15]]
^15^ The lazy one conceals his hand under his arms, and it is a labor for him to move it to his mouth.

[[proverbs-26-16]]
^16^ The lazy one seems wiser to himself than seven men speaking judgments.

[[proverbs-26-17]]
^17^ Just like one who takes hold of a dog by the ears, so also is he who crosses impatiently and meddles in the quarrels of another.

[[proverbs-26-18]]
^18^ Just as he is guilty who let loose the arrows and the lances unto death,

[[proverbs-26-19]]
^19^ so also is the man who harms his friend by deceitfulness. And when he has been apprehended, he says, “I did it jokingly.”

[[proverbs-26-20]]
^20^ When the wood fails, the fire will be extinguished. And when the gossiper is taken away, conflicts will be quelled.

[[proverbs-26-21]]
^21^ Just as charcoals are to burning coals, and wood is to fire, so also is an angry man who stirs up quarrels.

[[proverbs-26-22]]
^22^ The words of a whisperer seem simple, but they penetrate to the innermost parts of the self.

[[proverbs-26-23]]
^23^ In the same manner as an earthen vessel, if it were adorned with impure silver, conceited lips are allied with a wicked heart.

[[proverbs-26-24]]
^24^ An enemy is known by his lips, though it is from his heart that he draws out deceit.

[[proverbs-26-25]]
^25^ When he will have lowered his voice, do not believe him, for there are seven vices in his heart.

[[proverbs-26-26]]
^26^ Whoever covers hatred with deceit, his malice shall be revealed in the assembly.

[[proverbs-26-27]]
^27^ Whoever digs a pit will fall into it. And whoever rolls a stone, it will roll back to him.

[[proverbs-26-28]]
^28^ A false tongue does not love truth. And a slippery mouth works ruin.


[[proverbs-27]]
== Chapter 27

[[proverbs-27-1]]
^1^ Do not boast about tomorrow, for you do not know what the future day may bring.

[[proverbs-27-2]]
^2^ Let another praise you, and not your own mouth: an outsider, and not your own lips.

[[proverbs-27-3]]
^3^ A stone is weighty, and sand is burdensome; but the wrath of the foolish is heavier than both.

[[proverbs-27-4]]
^4^ Anger holds no mercy, nor does fury when it erupts. And who can bear the assault of one who has been provoked?

[[proverbs-27-5]]
^5^ An open rebuke is better than hidden love.

[[proverbs-27-6]]
^6^ The wounds of a loved one are better than the deceitful kisses of a hateful one.

[[proverbs-27-7]]
^7^ A sated soul will trample the honeycomb. And a hungry soul will accept even bitter in place of sweet.

[[proverbs-27-8]]
^8^ Just like a bird migrating from her nest, so also is a man who abandons his place.

[[proverbs-27-9]]
^9^ Ointment and various perfumes delight the heart. And the good advice of a friend is sweet to the soul.

[[proverbs-27-10]]
^10^ Do not dismiss your friend or your father’s friend. And do not enter your brother’s house in the day of your affliction. A close neighbor is better than a distant brother.

[[proverbs-27-11]]
^11^ My son, study wisdom, and rejoice my heart, so that you may be able to respond to the one who reproaches.

[[proverbs-27-12]]
^12^ The discerning man, seeing evil, hides himself. The little ones, continuing on, sustain losses.

[[proverbs-27-13]]
^13^ Take away the garment of him who has vouched for an outsider. And take a pledge from him on behalf of foreigners.

[[proverbs-27-14]]
^14^ Whoever blesses his neighbor with a grand voice, rising in the night, shall be like one who curses.

[[proverbs-27-15]]
^15^ A roof leaking on a cold day, and an argumentative woman, are comparable.

[[proverbs-27-16]]
^16^ He who would restrain her, he is like one who would grasp the wind, or who would gather together oil with his right hand.

[[proverbs-27-17]]
^17^ Iron sharpens iron, and a man sharpens the countenance of his friend.

[[proverbs-27-18]]
^18^ Whoever maintains the fig tree shall eat its fruit. And whoever is the keeper of his master shall be glorified.

[[proverbs-27-19]]
^19^ In the manner of faces looking into shining water, so are the hearts of men made manifest to the prudent.

[[proverbs-27-20]]
^20^ Hell and perdition are never filled; similarly the eyes of men are insatiable.

[[proverbs-27-21]]
^21^ In the manner of silver being tested in the refinery, and gold in the furnace, so also is a man tested by the mouth of one who praises. The heart of the iniquitous inquires after evils, but the heart of the righteous inquires after knowledge.

[[proverbs-27-22]]
^22^ Even if you were to crush the foolish with a mortar, as when a pestle strikes over pearled barley, his foolishness would not be taken from him.

[[proverbs-27-23]]
^23^ Be diligent to know the countenance of your cattle, and consider your own flocks,

[[proverbs-27-24]]
^24^ for you will not always hold this power. But a crown shall be awarded from generation to generation.

[[proverbs-27-25]]
^25^ The meadows are open, and the green plants have appeared, and the hay has been collected from the mountains.

[[proverbs-27-26]]
^26^ Lambs are for your clothing, and goats are for the price of a field.

[[proverbs-27-27]]
^27^ Let the milk of goats be sufficient for your food, and for the necessities of your household, and for the provisions of your handmaids.


[[proverbs-28]]
== Chapter 28

[[proverbs-28-1]]
^1^ The impious flees, though no one pursues. But the just, like a confident lion, shall be without dread.

[[proverbs-28-2]]
^2^ Because of the sins of the land, it has many princes. And because of the wisdom of a man, and the knowledge of those things that are said, the life of the leader shall be prolonged.

[[proverbs-28-3]]
^3^ A poor man slandering the poor is like a violent rainstorm in advance of a famine.

[[proverbs-28-4]]
^4^ Those who abandon the law praise the impious. Those who guard it are inflamed against him.

[[proverbs-28-5]]
^5^ Evil men do not intend judgment. But those who inquire after the Lord turn their souls toward all things.

[[proverbs-28-6]]
^6^ Better is the pauper walking in his simplicity, than the rich walking in ways of depravity.

[[proverbs-28-7]]
^7^ Whoever keeps the law is a wise son. But whoever feeds gluttons brings shame to his father.

[[proverbs-28-8]]
^8^ Whoever piles up riches by usury and profit gathers them for him who will give freely to the poor.

[[proverbs-28-9]]
^9^ Whoever turns away his ears from listening to the law: his prayer will be detestable.

[[proverbs-28-10]]
^10^ Whoever deceives the just in a malicious way will fall into his own perdition. And the simple shall possess his goods.

[[proverbs-28-11]]
^11^ The rich one seems wise to himself. But the poor one, being prudent, shall evaluate him.

[[proverbs-28-12]]
^12^ In the exultation of the just, there is great glory. When the impious reign, men are brought to ruin.

[[proverbs-28-13]]
^13^ Whoever hides his crimes will not be guided. But whoever will have confessed and abandoned them shall overtake mercy.

[[proverbs-28-14]]
^14^ Blessed is the man who is ever fearful. Yet truly, whoever is hardened in mind will fall into evil.

[[proverbs-28-15]]
^15^ An impious leader over a poor people is like a roaring lion and a hungry bear.

[[proverbs-28-16]]
^16^ A leader destitute of prudence will oppress many through false accusations. But whoever hates avarice shall prolong his days.

[[proverbs-28-17]]
^17^ A man who slanders the blood of a life, even if he flees to the pit, no one will tolerate him.

[[proverbs-28-18]]
^18^ Whoever walks simply shall be saved. Whoever is perverse in his steps will fall all at once.

[[proverbs-28-19]]
^19^ Whoever works his land shall be satisfied with bread. But whoever pursues leisure will be filled with need.

[[proverbs-28-20]]
^20^ A faithful man shall be greatly praised. But whoever rushes to become rich will not be innocent.

[[proverbs-28-21]]
^21^ Whoever shows favoritism in judgment does not do well; even if it is for a morsel of bread, he forsakes the truth.

[[proverbs-28-22]]
^22^ A man who hurries to become rich, and who envies others, does not know that destitution will overwhelm him.

[[proverbs-28-23]]
^23^ Whoever corrects a man, afterward he shall find favor with him, more so than he who deceives him with a flattering tongue.

[[proverbs-28-24]]
^24^ Whoever takes away anything from his father or mother, and who says, “This is not a sin,” is the associate of a murderer.

[[proverbs-28-25]]
^25^ Whoever boasts and enlarges himself stirs up conflicts. Yet truly, whoever trusts in the Lord will be healed.

[[proverbs-28-26]]
^26^ Whoever trusts in his own heart is a fool. But whoever treads wisely, the same shall be saved.

[[proverbs-28-27]]
^27^ Whoever gives to the poor shall not be in need. Whoever despises his petition will suffer scarcity.

[[proverbs-28-28]]
^28^ When the impious rise up, men will hide themselves. When they perish, the just shall be multiplied.


[[proverbs-29]]
== Chapter 29

[[proverbs-29-1]]
^1^ The man who, with a stiff neck, treats the one who corrects him with contempt will be suddenly overwhelmed to his own destruction, and reason shall not follow him.

[[proverbs-29-2]]
^2^ When just men are multiplied, the common people shall rejoice. When the impious take up the leadership, the people shall mourn.

[[proverbs-29-3]]
^3^ The man who loves wisdom rejoices his father. But whoever nurtures promiscuous women will lose his substance.

[[proverbs-29-4]]
^4^ A just king guides the land. A man of avarice will destroy it.

[[proverbs-29-5]]
^5^ A man who speaks to his friend with flattering and feigned words spreads a net for his own feet.

[[proverbs-29-6]]
^6^ A snare will entangle the iniquitous when he sins. And the just shall praise and be glad.

[[proverbs-29-7]]
^7^ The just knows the case of the poor. The impious is ignorant of knowledge.

[[proverbs-29-8]]
^8^ Pestilent men squander a city. Yet truly, the wise avert fury.

[[proverbs-29-9]]
^9^ A wise man, if he were to contend with the foolish, whether in anger or in laughter, would find no rest.

[[proverbs-29-10]]
^10^ Bloodthirsty men hate the simple one; but the just seek out his soul.

[[proverbs-29-11]]
^11^ A foolish one offers everything on his mind. A wise one reserves and defers until later.

[[proverbs-29-12]]
^12^ A leader who freely listens to lying words has only impious servants.

[[proverbs-29-13]]
^13^ The pauper and the creditor have met one another. The Lord is the illuminator of them both.

[[proverbs-29-14]]
^14^ The king who judges the poor in truth, his throne shall be secured in eternity.

[[proverbs-29-15]]
^15^ The rod and its correction distribute wisdom. But the child who is left to his own will, brings shame to his mother.

[[proverbs-29-16]]
^16^ When the impious are multiplied, crimes will be multiplied. But the just shall see their ruin.

[[proverbs-29-17]]
^17^ Teach your son, and he will refresh you, and he will give delight to your soul.

[[proverbs-29-18]]
^18^ When prophecy fails, the people will be scattered. Yet truly, whoever guards the law is blessed.

[[proverbs-29-19]]
^19^ A servant cannot be taught by words, because he understands what you say, but he disdains to respond.

[[proverbs-29-20]]
^20^ Have you seen a man rushing to speak? Foolishness has more hope than his correction.

[[proverbs-29-21]]
^21^ Whoever nurtures his servant delicately from childhood, afterwards will find him defiant.

[[proverbs-29-22]]
^22^ A short-tempered man provokes quarrels. And whoever is easily angered is more likely to sin.

[[proverbs-29-23]]
^23^ Humiliation follows the arrogant. And glory shall uphold the humble in spirit.

[[proverbs-29-24]]
^24^ Whoever participates with a thief hates his own soul; for he listens to his oath and does not denounce him.

[[proverbs-29-25]]
^25^ Whoever fears man will quickly fall. Whoever hopes in the Lord shall be lifted up.

[[proverbs-29-26]]
^26^ Many demand the face of the leader. But the judgment of each one proceeds from the Lord.

[[proverbs-29-27]]
^27^ The just abhor an impious man. And the impious abhor those who are on the right way. By keeping the word, the son shall be free from perdition.


[[proverbs-30]]
== Chapter 30

[[proverbs-30-1]]
^1^ The words of the Gatherer, the son of the Vomiter. The vision that the man spoke. God is with him, and he, being strengthened by God and abiding with him, said:

[[proverbs-30-2]]
^2^ “I am the most foolish among men, and the wisdom of men is not with me.

[[proverbs-30-3]]
^3^ I have not learned wisdom, and I have not known the knowledge of sanctity.

[[proverbs-30-4]]
^4^ Who has ascended to heaven and also descended? Who has grasped the wind in his hands? Who has tied the waters together, as with a garment? Who has raised all the limits of the earth? What is his name, and what is the name of his son, if you know?

[[proverbs-30-5]]
^5^ Every word of God is fire-tested. He is a bronze shield to those who hope in him.

[[proverbs-30-6]]
^6^ Do not add anything to his words, lest you be reproved and be discovered to be a liar.

[[proverbs-30-7]]
^7^ Two things I have asked of you; do not deny them to me before I die.

[[proverbs-30-8]]
^8^ Remove, far from me, vanity and lying words. Give me neither begging, nor wealth. Apportion to me only the necessities of my life,

[[proverbs-30-9]]
^9^ lest perhaps, being filled, I might be enticed into denial, and say: ‘Who is the Lord?’ Or, being compelled by destitution, I might steal, and then perjure myself in the name of my God.

[[proverbs-30-10]]
^10^ Do not accuse a servant to his lord, lest he curse you, and you fall.

[[proverbs-30-11]]
^11^ There is a generation which curses their father, and which does not bless their mother.

[[proverbs-30-12]]
^12^ There is a generation which seems pure to themselves, and yet they are not even washed from their filthiness.

[[proverbs-30-13]]
^13^ There is a generation, whose eyes have been elevated, and their eyelids are lifted on high.

[[proverbs-30-14]]
^14^ There is a generation which has swords in place of teeth, and which commands their molars to devour the indigent from the earth and the poor from among men.

[[proverbs-30-15]]
^15^ The leech has two daughters, who say, ‘Bring, bring.’ Three things are insatiable, and a fourth never says ‘Enough’:

[[proverbs-30-16]]
^16^ Hell, and the mouth of the womb, and a land that is not filled with water. And truly, fire never says, ‘Enough.’

[[proverbs-30-17]]
^17^ The eye of one who mocks his father and who despises the childbearing of his mother, let the ravens of the torrent tear it out, and let the sons of the eagles consume it.

[[proverbs-30-18]]
^18^ Three things are difficult for me, and about a fourth, I am nearly ignorant:

[[proverbs-30-19]]
^19^ the way of an eagle in the sky, the way of a serpent on a rock, the way of a ship in the middle of the sea, and the way of a man in adolescence.

[[proverbs-30-20]]
^20^ Such is the way also of an adulterous woman, who eats, and wiping her mouth, says: “I have done no evil.”

[[proverbs-30-21]]
^21^ By three things, the earth is moved, and a fourth it is not able to sustain:

[[proverbs-30-22]]
^22^ by a slave when he reigns, by the foolish when he has been filled with food,

[[proverbs-30-23]]
^23^ by a hateful woman when she has been taken in matrimony, and by a handmaid when she has been heir to her mistress.

[[proverbs-30-24]]
^24^ Four things are least upon the earth, and they are wiser than the wise:

[[proverbs-30-25]]
^25^ the ants, an infirm people who provide food for themselves at the harvest,

[[proverbs-30-26]]
^26^ the rabbit, a sickened people who make their bed upon the rock.

[[proverbs-30-27]]
^27^ The locust has no king, but they all depart by their troops.

[[proverbs-30-28]]
^28^ The lizard supports itself on hands and dwells in the buildings of kings.

[[proverbs-30-29]]
^29^ There are three things that advance well, and a fourth that marches happily on:

[[proverbs-30-30]]
^30^ a lion, the strongest of beasts, who fears nothing that he meets,

[[proverbs-30-31]]
^31^ a rooster prepared at the loins, likewise a ram, and a king, whom none can resist.

[[proverbs-30-32]]
^32^ There is one who has appeared foolish, after he was lifted up on high; for if he had understood, he would have placed his hand over his mouth.

[[proverbs-30-33]]
^33^ But whoever strongly squeezes the udder to bring out the milk, presses out butter. And whoever violently blows his nose, brings out blood. And whoever provokes wrath, brings forth discord.”


[[proverbs-31]]
== Chapter 31

[[proverbs-31-1]]
^1^ The words of king Lamuel. The vision by which his mother instructed him:

[[proverbs-31-2]]
^2^ “What, O my beloved? What, O beloved of my womb? What, O beloved of my vows?

[[proverbs-31-3]]
^3^ Do not give your substance to women, or your riches to overthrow kings.

[[proverbs-31-4]]
^4^ Not to kings, O Lamuel, not to kings give wine. For there are no secrets where drunkenness reigns.

[[proverbs-31-5]]
^5^ And perhaps they may drink and forget judgments, and alter the case of the sons of the poor.

[[proverbs-31-6]]
^6^ Give strong drink to the grieving, and wine to those who are bitter in soul.

[[proverbs-31-7]]
^7^ Let them drink, and forget their needs, and remember their sorrow no more.

[[proverbs-31-8]]
^8^ Open your mouth for the mute and for all the cases of the sons who are passing through.

[[proverbs-31-9]]
^9^ Open your mouth, declare what is just, and do justice to the indigent and the poor.

[[proverbs-31-10]]
^10^ Who shall find a strong woman? Far away, and from the furthest parts, is her price.

[[proverbs-31-11]]
^11^ The heart of her husband confides in her, and he will not be deprived of spoils.

[[proverbs-31-12]]
^12^ She will repay him with good, and not evil, all the days of her life.

[[proverbs-31-13]]
^13^ She has sought wool and flax, and she has worked these by the counsel of her hands.

[[proverbs-31-14]]
^14^ She has become like a merchant’s ship, bringing her bread from far away.

[[proverbs-31-15]]
^15^ And she has risen in the night, and given a prey to her household, and provisions to her maids.

[[proverbs-31-16]]
^16^ She has considered a field and bought it. From the fruit of her own hands, she has planted a vineyard.

[[proverbs-31-17]]
^17^ She has wrapped her waist with fortitude, and she has strengthened her arm.

[[proverbs-31-18]]
^18^ She has tasted and seen that her tasks are good; her lamp shall not be extinguished at night.

[[proverbs-31-19]]
^19^ She has put her hand to strong things, and her fingers have taken hold of the spindle.

[[proverbs-31-20]]
^20^ She has opened her hand to the needy, and she has extended her hands to the poor.

[[proverbs-31-21]]
^21^ She shall not fear, in the cold of snow, for her household. For all those of her household have been clothed two-fold.

[[proverbs-31-22]]
^22^ She has made embroidered clothing for herself. Fine linen and purple is her garment.

[[proverbs-31-23]]
^23^ Her husband is noble at the gates, when he sits among the senators of the land.

[[proverbs-31-24]]
^24^ She has made finely woven cloth and sold it, and she has delivered a waistband to the Canaanite.

[[proverbs-31-25]]
^25^ Strength and elegance are her clothing, and she will laugh in the final days.

[[proverbs-31-26]]
^26^ She has opened her mouth to wisdom, and the law of clemency is on her tongue.

[[proverbs-31-27]]
^27^ She has considered the paths of her household, and she has not eaten her bread in idleness.

[[proverbs-31-28]]
^28^ Her sons rose up and predicted great happiness; her husband rose up and praised her.

[[proverbs-31-29]]
^29^ Many daughters have gathered together riches; you have surpassed them all.

[[proverbs-31-30]]
^30^ Charm is false, and beauty is vain. The woman who fears the Lord, the same shall be praised.

[[proverbs-31-31]]
^31^ Give to her from the fruit of her own hands. And let her works praise her at the gates.
