[[wisdom]]
= The Wisdom of Solomon
:short: Wisdom

[[wisdom-1]]
== Chapter 1

[[wisdom-1-1]]
^1^ Love justice, you who judge the land. Think of the Lord in goodness and seek him in simplicity of heart.

[[wisdom-1-2]]
^2^ For he is found by those who do not test him, yet he reveals himself to those who have faith in him.

[[wisdom-1-3]]
^3^ For perverse thoughts separate from God. But his virtue, when it is tested, corrects the foolish.

[[wisdom-1-4]]
^4^ For wisdom will not enter into a malicious soul, nor dwell in a body subdued by sin.

[[wisdom-1-5]]
^5^ For the holy spirit of instruction will flee from falsehood, and he will withdraw himself from thoughts that are without understanding, and he will not be reached when iniquity overcomes.

[[wisdom-1-6]]
^6^ For the spirit of wisdom is benevolent, and will not release the evil speaker from his talk, because God is a witness of his temperament, and a true examiner of his heart, and an auditor of his words.

[[wisdom-1-7]]
^7^ For the spirit of the Lord has filled the world, and he who contains all things, retains knowledge of every voice.

[[wisdom-1-8]]
^8^ Therefore, he who speaks unjust things cannot escape notice, nor will the chastising judgment pass him by.

[[wisdom-1-9]]
^9^ For inquiry will be made into the thoughts of the impious, his conversation also will reach the hearing of God, to the chastising of his iniquities.

[[wisdom-1-10]]
^10^ For the zealous ear hears all things, and the disturbance of complaining will not be hidden.

[[wisdom-1-11]]
^11^ Therefore, keep yourselves from complaining, which benefits nothing, and refrain your tongue from slander, because secret conversation will not pass into nothingness, and the mouth that lies kills the soul.

[[wisdom-1-12]]
^12^ Do not court death by the error of your life, nor procure your destruction by the works of your hands,

[[wisdom-1-13]]
^13^ because God did not make death, nor does he rejoice in the loss of the living.

[[wisdom-1-14]]
^14^ For he created all things that they might exist, and he made the nations of the world curable, and there is no medicine of extermination in them, nor a kingdom of hell upon the earth.

[[wisdom-1-15]]
^15^ For justice is perpetual and immortal.

[[wisdom-1-16]]
^16^ But the impious, with hands and words, have called death to them, and, esteeming it a friend, they have fallen away and have made a covenant with death, because they deserved to take part in it.


[[wisdom-2]]
== Chapter 2

[[wisdom-2-1]]
^1^ For they have said, reasoning with themselves incorrectly: “Our lifetime is brief and tedious, and there is no relief within the limits of man, and no one is acknowledged to have returned from the dead.

[[wisdom-2-2]]
^2^ For we are born from nothing, and after this we will be as if we had not been, because the breath in our nostrils is like smoke, and conversation sends out sparks from the stirring of our heart;

[[wisdom-2-3]]
^3^ therefore, when it is extinguished, our body will be ashes, and our spirit will be diffused like a soft breeze, and our life will pass away like the wisp of a cloud, just as a mist is dissolved when it is driven away by the rays of the sun and overpowered by its heat.

[[wisdom-2-4]]
^4^ And in time our name will surrender to oblivion, and no one will have remembrance of our works.

[[wisdom-2-5]]
^5^ For our time is like the passing of a shadow, and nothing can reverse our end, for it is signed and sealed, and cannot be returned.

[[wisdom-2-6]]
^6^ Therefore, hurry, let us enjoy the good things of the present time, and let us quickly use up passing things, just as in youth.

[[wisdom-2-7]]
^7^ Let us indulge ourselves with costly wine and ointments, and let no flower of youth pass us by.

[[wisdom-2-8]]
^8^ Let us surround ourselves with rosebuds before they wither; let no meadow be left untouched by our indulgence.

[[wisdom-2-9]]
^9^ Let no one among us be exempt from our indulgence. Let us leave behind tokens of enjoyment everywhere, for this is our portion, and this is fate.

[[wisdom-2-10]]
^10^ Let us oppress the poor just man, and not spare the widow, nor respect the aged grey hairs of elders.

[[wisdom-2-11]]
^11^ But let our strength be the law of justice, for what is weak is found to be useless.

[[wisdom-2-12]]
^12^ Therefore, let us encircle the just, because he is useless to us, and he is against our works, and he reproaches us with our legal offenses, and makes known to us the sins of our way of life.

[[wisdom-2-13]]
^13^ He promises that he has the knowledge of God and he calls himself the son of God.

[[wisdom-2-14]]
^14^ He was made among us to expose our very thoughts.

[[wisdom-2-15]]
^15^ He is grievous for us even to behold, for his life is unlike other men’s lives, and immutable are his ways.

[[wisdom-2-16]]
^16^ It is as if we are considered by him to be insignificant, and he abstains from our ways as from filth; he prefers the newly justified, and he glories that he has God for his father.

[[wisdom-2-17]]
^17^ Let us see, then, if his words are true, and let us test what will happen to him, and then we will know what his end will be.

[[wisdom-2-18]]
^18^ For if he is the true son of God, he will receive him and deliver him from the hands of his adversaries.

[[wisdom-2-19]]
^19^ Let us examine him with insult and torture, that we may know his reverence and try his patience.

[[wisdom-2-20]]
^20^ Let us condemn him to a most shameful death, for, according to his own words, God will care for him.”

[[wisdom-2-21]]
^21^ These things they thought, and they were mistaken, for their own malice blinded them.

[[wisdom-2-22]]
^22^ And they were ignorant of the mysteries of God; they neither hoped for the reward of justice, nor judged the value of holy souls.

[[wisdom-2-23]]
^23^ For God created man to be immortal, and he made him in the image of his own likeness.

[[wisdom-2-24]]
^24^ But by the envy of the devil, death entered the world,

[[wisdom-2-25]]
^25^ yet they imitate him, who are from his side.


[[wisdom-3]]
== Chapter 3

[[wisdom-3-1]]
^1^ But the souls of the just are in the hand of God and no torment of death will touch them.

[[wisdom-3-2]]
^2^ In the eyes of the foolish, they seemed to die, and their departure was considered an affliction,

[[wisdom-3-3]]
^3^ and their going away from us, a banishment. Yet they are in peace.

[[wisdom-3-4]]
^4^ And though, in the sight of men, they suffered torments, their hope is full of immortality.

[[wisdom-3-5]]
^5^ Troubled in few things, in many things they will be well compensated, because God has tested them and found them worthy of himself.

[[wisdom-3-6]]
^6^ Like gold in the furnace, he has proved them, and as a holocaust victim, he has received them, and in the time of their visitation

[[wisdom-3-7]]
^7^ they will shine, and they will dash about like sparks among stubble.

[[wisdom-3-8]]
^8^ They will judge the nations and they will rule over the people, and their Lord will reign forever.

[[wisdom-3-9]]
^9^ Those who trust in him, will understand the truth, and those who are faithful in love will rest in him, because grace and peace is for his elect.

[[wisdom-3-10]]
^10^ But the impious will be chastised according to their thoughts, for they have neglected the just and have retreated from the Lord.

[[wisdom-3-11]]
^11^ For whoever abandons wisdom and instruction is unhappy, and their hope is empty, and their labors without fruit, and their works useless.

[[wisdom-3-12]]
^12^ Their wives are foolish and their sons are wicked; the things that serve them are accursed.

[[wisdom-3-13]]
^13^ Therefore, fertile is the barren and undefiled, who has not known transgressions in bed; she will bear fruit by caring for holy souls.

[[wisdom-3-14]]
^14^ And fertile is the celibate, who has not wrought iniquity with his hands, nor thought wickedness against God; for to him will be given a special gift of faith and a very welcome place in the temple of the Lord.

[[wisdom-3-15]]
^15^ For the fruit of good labors is glorious and the root of wisdom shall never perish.

[[wisdom-3-16]]
^16^ But the sons of adulterers will not reach completion, and the offspring of a sinful bed will be banished.

[[wisdom-3-17]]
^17^ And if they live long, they will be counted as nothing, and their last years of old-age will be without honor.

[[wisdom-3-18]]
^18^ And if they die quickly, they will have no hope, nor words of comfort on the day of reckoning.

[[wisdom-3-19]]
^19^ For the iniquities of the people have a dreadful result.


[[wisdom-4]]
== Chapter 4

[[wisdom-4-1]]
^1^ O how beautiful is the chaste fruit of purity! For its remembrance is immortal, because it is observed both with God and with men.

[[wisdom-4-2]]
^2^ When it is present, they imitate it, and they desire it when it has withdrawn itself, and it triumphs crowned forever, winning the reward of undefiled conflicts.

[[wisdom-4-3]]
^3^ But the great number of the many different kinds of the impious will not be to their advantage, and spurious seedlings will not be given deep roots, nor will they establish any firm foundation.

[[wisdom-4-4]]
^4^ And if they spring forth with branches for a time, yet, being set infirmly, they will be shaken by the wind, and, by the superabundance of the winds, they will be eradicated.

[[wisdom-4-5]]
^5^ For the incomplete branches will be broken, and their fruits will be useless, and bitter to eat, and fit for nothing.

[[wisdom-4-6]]
^6^ For all the sons born from iniquity are witnesses of wickedness against their parents at their interrogation.

[[wisdom-4-7]]
^7^ But the just, if death seizes him beforehand, will be refreshed.

[[wisdom-4-8]]
^8^ For old age is made venerable, neither by lasting long, nor by counting the number of years; yet understanding is the gray hair of wisdom for men,

[[wisdom-4-9]]
^9^ and an immaculate life is a generation of sages.

[[wisdom-4-10]]
^10^ Pleasing to God, having been made beloved, and living among sinners, he was transformed.

[[wisdom-4-11]]
^11^ He was quickly taken away, for malice could not alter his understanding, nor could deceit beguile his soul.

[[wisdom-4-12]]
^12^ For fascination with entertainment obscures good things, and the unfaithfulness of desire subverts the mind without malice.

[[wisdom-4-13]]
^13^ Completed in a short time, he fulfilled many times.

[[wisdom-4-14]]
^14^ Truly his soul was pleasing to God. Because of this, he hastened to bring him out of the midst of iniquities, but the people see this and do not understand, nor do they place such things in their hearts:

[[wisdom-4-15]]
^15^ that the grace and mercy of God is with his holy ones, and he watches over his elect.

[[wisdom-4-16]]
^16^ But the just dead will condemn the impious living, and youth hastily completed results in a long unjust life.

[[wisdom-4-17]]
^17^ For they will see the end of the wise, and will neither understand, nor imagine, that he is of God, and that therefore the Lord has safeguarded him.

[[wisdom-4-18]]
^18^ For they will see and despise him, but the Lord will ridicule them.

[[wisdom-4-19]]
^19^ And after this, they will fall without honor and with contempt among the dead forever. Seeing that they are puffed up and speechless, he will shatter them and will shake them from the foundations all the way to the top, to their utter desolation, and they will grieve and their remembrance will perish.

[[wisdom-4-20]]
^20^ They will hurry with fear at the understanding of their sins, and their iniquities will bear witness against them.


[[wisdom-5]]
== Chapter 5

[[wisdom-5-1]]
^1^ Then the just will stand with great steadfastness against those who have oppressed them and have taken away their labors.

[[wisdom-5-2]]
^2^ Seeing this, they will be troubled with terrible fear, and they will be amazed at the suddenness of unexpected salvation.

[[wisdom-5-3]]
^3^ Driven toward regret, and through the anguish of their groaning spirit, they will say within themselves: “These are the ones whom we held for some time in derision and in mocking reproach.

[[wisdom-5-4]]
^4^ We foolish considered their life to be madness, and their end to be without honor.

[[wisdom-5-5]]
^5^ How is it that they are counted among the sons of God, and their place is among the holy?

[[wisdom-5-6]]
^6^ Therefore, we have strayed from the way of truth, and the light of justice has not shined on us, and the sun of understanding has not risen on us.

[[wisdom-5-7]]
^7^ We exhausted ourselves in the way of iniquity and perdition, and have walked a difficult way, while ignoring the way of the Lord.

[[wisdom-5-8]]
^8^ How has arrogance benefited us? Or what has exalting in riches brought us?

[[wisdom-5-9]]
^9^ All those things have passed away like a shadow, and like a messenger traveling quickly by;

[[wisdom-5-10]]
^10^ and like a ship passing over the waves of water, when it has gone by, its trace cannot be found, nor can the pathway of its keel in the waves;

[[wisdom-5-11]]
^11^ or, like a bird flying through the air, there is no evidence of her journey to be found, but there is hardly a sound as the beating of her wings lifts up the air and, by the force of her journey, divides the air she has flown across, which was disturbed by her wings, and afterwards there is no sign of her journey to be found;

[[wisdom-5-12]]
^12^ or, like an arrow shot at a selected mark, the air continues to be divided and to be brought together again, so that its passing is unknown.

[[wisdom-5-13]]
^13^ And in like manner we, having been born, continuously cease to exist, and indeed, we depart with no sign of virtue to show, but we are consumed in our malice.”

[[wisdom-5-14]]
^14^ Such things those who sinned said in hell.

[[wisdom-5-15]]
^15^ For the hope of the impious is like feathers, which are blown away by the wind, and like a thin foam, which is dispersed by a storm, and like smoke, which is scattered by the wind, and like the memory of a guest who passes by one day.

[[wisdom-5-16]]
^16^ But the just will live forever, and their reward is with the Lord, and the thought of them is with the Most High.

[[wisdom-5-17]]
^17^ Therefore, they will receive a beautiful kingdom and a crown of splendor from the hand of the Lord, for with his right hand he will cover them, and with his holy arm he will defend them.

[[wisdom-5-18]]
^18^ And his zeal will take up arms, and he will equip his servants for retribution on their enemies.

[[wisdom-5-19]]
^19^ He will put on justice as a breastplate, and he will grasp sure judgment as a helmet.

[[wisdom-5-20]]
^20^ He will select fairness as an invincible shield.

[[wisdom-5-21]]
^21^ Yet he will sharpen his severe wrath into a spear, and he will fight with those of the world against the irrational.

[[wisdom-5-22]]
^22^ Shafts of lightning will hurl forth accurately, and, as if from a well-curved bow of clouds, they will be expelled and will fly to the determined mark.

[[wisdom-5-23]]
^23^ And hail will be cast like stones full of anger, and the water of the sea will rise up against them, and the rivers will charge forth harshly.

[[wisdom-5-24]]
^24^ The spirit of virtue will stand firm against them and like a whirlwind will divide them, and he will lead all the world of iniquity into a wasteland, and malice will overthrow the seats of power.


[[wisdom-6]]
== Chapter 6

[[wisdom-6-1]]
^1^ Wisdom is better than power, and a prudent man is better than a powerful one.

[[wisdom-6-2]]
^2^ Therefore, hear, O kings, and understand; learn, you judges of the ends of the earth.

[[wisdom-6-3]]
^3^ Listen closely, you who hold the attention of the crowds, and who please yourselves by disturbing the nations.

[[wisdom-6-4]]
^4^ For power has been given to you from the Lord and strength from the Most High, who will examine your works and scrutinize your thoughts.

[[wisdom-6-5]]
^5^ For, when you were ministers of his kingdom, you did not judge correctly, nor keep the law of justice, nor walk according to the will of God.

[[wisdom-6-6]]
^6^ Horribly and quickly he will appear to you, because he will make a severe judgment for those who are in charge.

[[wisdom-6-7]]
^7^ For, to the little, great mercy is granted, but the powerful will endure powerful torment.

[[wisdom-6-8]]
^8^ For the Lord will not exempt anyone’s character, nor will he stand in awe of anyone’s greatness, because he himself made the little and the great, and he is equally concerned for everyone.

[[wisdom-6-9]]
^9^ But a powerful torture pursues the powerful.

[[wisdom-6-10]]
^10^ Therefore, O kings, these, my words, are for you, so that you may learn wisdom and not perish.

[[wisdom-6-11]]
^11^ For those who have justly preserved justice will be justified, and those who have learned these things will find what to answer.

[[wisdom-6-12]]
^12^ Therefore, desire my words, love them, and you will have instruction.

[[wisdom-6-13]]
^13^ Wisdom is pure and never fades away, and is easily seen by those who love her and found by those who seek her.

[[wisdom-6-14]]
^14^ She anticipates those who desire her, so that she first reveals herself to them.

[[wisdom-6-15]]
^15^ Whoever awakens early to seek her, will not labor, for he will find her sitting at his door.

[[wisdom-6-16]]
^16^ Therefore, by thinking about her, understanding is perfected, and whoever remains watchful for her, will quickly be secure.

[[wisdom-6-17]]
^17^ For she goes about seeking such as are worthy of her, and she reveals herself to them cheerfully in the ways, and meets them with all foresight.

[[wisdom-6-18]]
^18^ For the very true beginning of her is the desire for instruction.

[[wisdom-6-19]]
^19^ Therefore, the zeal for instruction is love, and love is the keeping of her laws, and the keeping of her laws is the perfection of incorruptibility,

[[wisdom-6-20]]
^20^ while incorruptibility makes us near to God.

[[wisdom-6-21]]
^21^ And so, the desire for wisdom leads to an everlasting kingdom.

[[wisdom-6-22]]
^22^ If, therefore, your delight is in thrones and scepters, O kings of the people, love wisdom, so that you may reign forever;

[[wisdom-6-23]]
^23^ love the light of wisdom, all you who lead the peoples.

[[wisdom-6-24]]
^24^ But what wisdom is, and how she was made, I will report, and I will not hide the mysteries of God from you, but I will investigate her from the beginning of her birth, and I will place the knowledge of her in the light, and will not pass over the truth.

[[wisdom-6-25]]
^25^ Neither will I hold to the path that dwindles away with envy, because such a man will not partake in wisdom.

[[wisdom-6-26]]
^26^ For the proliferation of the wise is sanity for the world, and a wise king is the mainstay of the people.

[[wisdom-6-27]]
^27^ Therefore, receive instruction by my words, and it will benefit you.


[[wisdom-7]]
== Chapter 7

[[wisdom-7-1]]
^1^ Certainly, I myself am also a mortal man, like everyone, and the offspring of this earth, which was made beforehand; and in my mother’s womb I was fashioned with care,

[[wisdom-7-2]]
^2^ within the time of ten months, made of blood, from the seed of man and the delight of sleeping together.

[[wisdom-7-3]]
^3^ And when I was born, I drew in the common air, and in similar fashion, I fell upon the earth, and the first voice I uttered, like everyone, was crying.

[[wisdom-7-4]]
^4^ I was nursed in swaddling clothes and with great care.

[[wisdom-7-5]]
^5^ For none of the kings had any other beginning of birth.

[[wisdom-7-6]]
^6^ Therefore, there is only one entrance for everyone into life, and the same in leaving.

[[wisdom-7-7]]
^7^ Because of this, I chose, and understanding was given to me; and I prayed, and the spirit of wisdom came to me;

[[wisdom-7-8]]
^8^ and I placed her before kingdoms and thrones, and I considered riches nothing in comparison with her.

[[wisdom-7-9]]
^9^ Neither did I compare to her a precious stone, for all gold in comparison with her is like a little sand, and silver, in view of her, will be valued as if dirt.

[[wisdom-7-10]]
^10^ I loved her above health and beauty, and I placed having her before light, for her light is unfailing.

[[wisdom-7-11]]
^11^ Yet all good things came to me together with her, and innumerable honors by her hand;

[[wisdom-7-12]]
^12^ and I rejoiced in all these, because this wisdom went before me, although I did not know that she is the mother of them all.

[[wisdom-7-13]]
^13^ This I have learned without falsehood and communicate without envy, and her integrity I do not hide.

[[wisdom-7-14]]
^14^ Indeed, she is an infinite treasure chest for men, and those who make use of it, become partakers in the friendship of God, because they are recommended by the gifts of instruction.

[[wisdom-7-15]]
^15^ Yet God has given to me to speak my mind, and to conceive thoughts worthy of those things that are given to me, because he is the leader of wisdom and the repairer of understanding.

[[wisdom-7-16]]
^16^ For in his hand are both we, and our words, and all wisdom, and the works of science, and instruction.

[[wisdom-7-17]]
^17^ For he has given me true knowledge of these things which exist: so as to know the orderly arrangement of the world, and the powers of the elements,

[[wisdom-7-18]]
^18^ the beginning and the end and the midpoint of the seasons, the characteristics of changing things, and the divisions of time,

[[wisdom-7-19]]
^19^ the courses of the years, and the orderly arrangement of the stars,

[[wisdom-7-20]]
^20^ the natures of animals, and the rage of wild beasts, the force of winds, and the reasonings of men, the diversities of plants, and the benefits of roots,

[[wisdom-7-21]]
^21^ and all such things as are hidden and unexpected, I have learned; for wisdom, the artisan of all things, taught me.

[[wisdom-7-22]]
^22^ For in her is the spirit of understanding: holy, singular, manifold, subtle, perceptive, lively, chaste, reliable, gracious, loving, good, astute, who forbids nothing beneficial,

[[wisdom-7-23]]
^23^ humane, kind, steadfast, trustworthy, secure, having all virtue, watching for all things and grasping all things with a pure and most delicate understanding of spirit.

[[wisdom-7-24]]
^24^ For wisdom is more active than all active things, yet she reaches everywhere because of her purity.

[[wisdom-7-25]]
^25^ For she is a breath of the virtue of God and a genuine emanation from the purity of the almighty God, and therefore nothing unclean can invade her.

[[wisdom-7-26]]
^26^ Indeed, she is the brightness of eternal light, and the unspotted mirror of the majesty of God, and the image of his goodness.

[[wisdom-7-27]]
^27^ And though she is one, she can do all things; and, unchanging in herself, she renews all things, and throughout the nations she conveys herself to holy souls, establishing them as friends and prophets of God.

[[wisdom-7-28]]
^28^ For God loves none but those who dwell with wisdom.

[[wisdom-7-29]]
^29^ For she is more spectacular than the sun, and above the array of all the stars; compared with the light, she is found to be before it.

[[wisdom-7-30]]
^30^ Indeed, after her comes night, but wisdom will not be overcome by malice.


[[wisdom-8]]
== Chapter 8

[[wisdom-8-1]]
^1^ Thus, she reaches mightily from one end all the way to the other, and she orders all things sweetly.

[[wisdom-8-2]]
^2^ I have loved her and searched for her from my youth, and have asked to take her to me as my spouse, and I became a lover of her form.

[[wisdom-8-3]]
^3^ She glorifies her lineage by having companionship with God; yes and of all things, the Lord loves her.

[[wisdom-8-4]]
^4^ For she teaches the teaching of God and is the chooser of his works.

[[wisdom-8-5]]
^5^ And if riches are longed for in life, what is richer than wisdom, which is being served in all things?

[[wisdom-8-6]]
^6^ But if the mind is to be served, who, of all that exists, is a greater artisan than she?

[[wisdom-8-7]]
^7^ And if anyone loves justice, her labors hold great virtues; for she teaches temperance and prudence, justice and virtue, and nothing is more useful in human life.

[[wisdom-8-8]]
^8^ And if one desires a multitude of knowledge, she knows the past and forecasts the future; she knows the subtleties of conversation and the response to arguments; she understands the signs and portents, before the events take place, events both of the present time and of future ages.

[[wisdom-8-9]]
^9^ Therefore, I resolved to take her to me to live together, knowing that she will be a good counselor and will console my thoughts and my weariness.

[[wisdom-8-10]]
^10^ Because of her, I have clarity in the midst of confusion, and honor among the elders in my youth;

[[wisdom-8-11]]
^11^ and I will be found to be astute in judgment, and will be admired in the sight of the mighty, and the faces of leaders will wonder at me.

[[wisdom-8-12]]
^12^ When I am silent, they will wait for me; when I speak, they will respect me; and when I talk for too long, they will put their hands on their mouths.

[[wisdom-8-13]]
^13^ Thus, by means of her, I will have immortality, and I will bequeath an everlasting memorial to those who come after me.

[[wisdom-8-14]]
^14^ I will set the peoples in order, and nations will be subject to me.

[[wisdom-8-15]]
^15^ Hearing me, terrible kings will be afraid; to the multitude, I will be seen as good and valiant in war.

[[wisdom-8-16]]
^16^ When I go into my house, I will repose myself with her, for her conversation has no bitterness, nor her company any tediousness, but only joy and gladness.

[[wisdom-8-17]]
^17^ Thinking these things within myself, and recalling in my heart that immortality is the intention of wisdom,

[[wisdom-8-18]]
^18^ and that in her friendship is good enjoyment, and in the works of her hands are honors without flaw, and in debate with her is understanding, and glory in sharing conversation with her; I went about seeking, so that I might take her to myself.

[[wisdom-8-19]]
^19^ For I was an ingenious boy and had been dealt a good soul.

[[wisdom-8-20]]
^20^ Even more so, being good, I came to have an undefiled body.

[[wisdom-8-21]]
^21^ And since I know that it is not possible to be chaste except as a gift from God, and that it is a point of wisdom to know whose gift it is, I approached the Lord, and I besought him, and I said with my whole heart:


[[wisdom-9]]
== Chapter 9

[[wisdom-9-1]]
^1^ “God of my fathers and Lord of mercy, who has made all things with your word,

[[wisdom-9-2]]
^2^ and by your wisdom has established man to have dominion over the creatures which have been made by you,

[[wisdom-9-3]]
^3^ so that he would order the world in equity and justice, and execute judgment with an upright heart,

[[wisdom-9-4]]
^4^ give me wisdom, the handmaiden at your throne, and be unwilling to reject me from among your children,

[[wisdom-9-5]]
^5^ because I am your servant, and the son of your handmaid, a weak man, and short-lived, with limited understanding of judgment and laws.

[[wisdom-9-6]]
^6^ And if someone were perfect among the sons of men, yet if your wisdom was taken away from him, he would be counted as nothing.

[[wisdom-9-7]]
^7^ You have chosen me to be a king of your people, and a judge of your sons and daughters.

[[wisdom-9-8]]
^8^ And you called me to construct a temple on your holy mount, and, in the city of your dwelling, an altar in the likeness of your holy tabernacle, which you have prepared from the beginning.

[[wisdom-9-9]]
^9^ And with you is wisdom, who is familiar with your works, and who was nearby when you made the world, and who knows what is pleasing to your eyes, and who is guided by your teachings.

[[wisdom-9-10]]
^10^ Send her out of your holy heavens and from the throne of your majesty, so that she is with me and labors with me, and I will know what is acceptable with you.

[[wisdom-9-11]]
^11^ For she knows and understands all things, and will lead me soberly in my works, and will guard me by her power.

[[wisdom-9-12]]
^12^ And my works will be acceptable, and I will govern your people justly, and I will be worthy of the throne of my father.

[[wisdom-9-13]]
^13^ For who among men can know the counsel of God? Or who can imagine the will of God?

[[wisdom-9-14]]
^14^ For the thoughts of mortals are timid, and our foresight is uncertain.

[[wisdom-9-15]]
^15^ For the corruptible body weighs down the soul, and this earthy dwelling presses many thoughts upon the mind.

[[wisdom-9-16]]
^16^ And we assess with difficulty the things that are of earth, and we discover with labor the things that are within our view. So who will search out the things that are in heaven?

[[wisdom-9-17]]
^17^ Moreover, who will know your mind, unless you give wisdom and send your holy spirit from on high?

[[wisdom-9-18]]
^18^ And in this way, those who are on earth are corrected in their path, and men learn the things that are pleasing to you.

[[wisdom-9-19]]
^19^ For by wisdom they are saved, who have pleased you, O Lord, from the beginning.”


[[wisdom-10]]
== Chapter 10

[[wisdom-10-1]]
^1^ This is he, who was formed first by God, the father of the world, who was alone when created; she preserved him,

[[wisdom-10-2]]
^2^ and led him out of his offense, and gave him the power to maintain all things.

[[wisdom-10-3]]
^3^ After this, when the unjust man withdrew from her in his anger, he perished through anger by the murder of his brother.

[[wisdom-10-4]]
^4^ Because of this, when water destroyed the earth, wisdom healed it again, guiding the just by means of contemptible wood.

[[wisdom-10-5]]
^5^ Moreover, when the nations had conspired together to consent to wickedness, she knew the just, and preserved him without blame before God, and preserved his strength out of mercy for his sons.

[[wisdom-10-6]]
^6^ She freed this just man from the destruction of the impious, fleeing descending fire in the Five Cities,

[[wisdom-10-7]]
^7^ which, as a testimony to their wickedness, is a constantly smoking desolate land, and the trees bear fruit at uncertain times, and a figure of salt stands as a monument to an unbelieving soul.

[[wisdom-10-8]]
^8^ For, in disregarding wisdom, they are fallen, not so much in this, that they were ignorant of good, but that they bequeathed to men a memorial of their foolishness, so that, in the things in which they sinned, they were unable to escape notice.

[[wisdom-10-9]]
^9^ Yet wisdom has freed from sorrow those who are self-observant.

[[wisdom-10-10]]
^10^ She led the just man, this fugitive of his brother’s wrath, by the right ways, and revealed to him the kingdom of God, and gave him the knowledge of holiness, honored him in his labors, and completed his labors.

[[wisdom-10-11]]
^11^ In the midst of encircling deceit, she flowed around him and made him honest.

[[wisdom-10-12]]
^12^ She guarded him from his enemies, and she defended him from seducers, and she gave him a strong conflict so that he might overcome and might know that the power of all things is wisdom.

[[wisdom-10-13]]
^13^ She did not abandon the just man when he was sold, but freed him from sinners; she went down with him into the pit,

[[wisdom-10-14]]
^14^ and she did not abandon him in chains, while she brought him the scepter of the kingdom and power against those who oppressed him, and revealed them to be liars who had dishonored him, and gave him everlasting glory.

[[wisdom-10-15]]
^15^ She freed this just people and the blameless offspring, from the nations that had oppressed them.

[[wisdom-10-16]]
^16^ She entered the soul of the servant of God and stood against dreadful kings in the midst of portents and signs,

[[wisdom-10-17]]
^17^ and she rendered to the just the wages of their labors, and led them along a wondrous way; and she was to them, like a cover by day, and like the light of the stars by night.

[[wisdom-10-18]]
^18^ She carried them through the Red Sea, and led them across a great water.

[[wisdom-10-19]]
^19^ But their enemies, she submerged in the sea, and from the furthest depths, she drew them up. Therefore, the just carried off the spoils of the impious.

[[wisdom-10-20]]
^20^ And they chanted to your holy name, Lord, and they together praised your victorious hand,

[[wisdom-10-21]]
^21^ because wisdom opened the mouth of the mute, and made the speech of infants eloquent.


[[wisdom-11]]
== Chapter 11

[[wisdom-11-1]]
^1^ She directed their works in the hands of the holy prophet.

[[wisdom-11-2]]
^2^ They made a path through desolate areas, which were uninhabited, and set up their homes in remote places.

[[wisdom-11-3]]
^3^ They stood firm against the enemy, and vindicated themselves from their adversaries.

[[wisdom-11-4]]
^4^ They thirsted, and they called upon you, and water was given them out of the deepest rock, and respite from thirst out of the hard stone.

[[wisdom-11-5]]
^5^ For through water, their enemies had been punished, by the corruption of their drinking water; and so, among them, when the sons of Israel lacked the abundance they would have had, their enemies rejoiced;

[[wisdom-11-6]]
^6^ yet through water, when they were in need, it turned out well for them.

[[wisdom-11-7]]
^7^ For instead of a fountain, even everlasting in flow, you gave human blood to the unjust,

[[wisdom-11-8]]
^8^ and while they would be crushed into disgrace because of the murdering of infants, you unexpectedly gave your own abundant water,

[[wisdom-11-9]]
^9^ revealing through the thirst, which occurred at that time, how you would exalt your own and would kill their adversaries.

[[wisdom-11-10]]
^10^ For when they were being tested, and even when receiving merciful correction, they knew in what way, when your wrath judged the impious, they would suffer torments.

[[wisdom-11-11]]
^11^ For these, advising like a father, you approved; but the others, interrogating like a severe king, you condemned.

[[wisdom-11-12]]
^12^ For whether absent or present, they were tortured alike.

[[wisdom-11-13]]
^13^ For they had received double: weariness and groaning in the remembrance of things past.

[[wisdom-11-14]]
^14^ For when they paid attention to their punishments, to attend to their own benefit, they called to mind the Lord, admiring the end result.

[[wisdom-11-15]]
^15^ For though they showed scorn by throwing out distorted statements, in the end they were amazed at the result, but this is not the same as thirsting for justice.

[[wisdom-11-16]]
^16^ For according to the thinking of their irrational iniquity, because some, going astray, were worshiping mute serpents and worthless beasts, you sent upon them a multitude of mute beasts for vengeance,

[[wisdom-11-17]]
^17^ so that they might know that by whatever things a man sins, by the same also is he tormented.

[[wisdom-11-18]]
^18^ For it was not impossible for your all-powerful hand, which created the world from unknown material, to send forth upon them a multitude of bears, or fierce lions,

[[wisdom-11-19]]
^19^ or, in anger, beasts of a new kind, massive and strange, either breathing out a fiery vapor, or sending forth an odorous smoke, or shooting horrible sparks from their eyes;

[[wisdom-11-20]]
^20^ whereby, not only wounds would be able to destroy them, but also the very sight would kill them through fear.

[[wisdom-11-21]]
^21^ Yet, even without these, they could have been killed with one breath, suffering persecution of their own making and being scattered by your spirit of virtue; but you have ordered all things in size and number and weight.

[[wisdom-11-22]]
^22^ Though many are strong, you alone always overcome. And who will withstand the strength of your arm?

[[wisdom-11-23]]
^23^ For, like a tiny grain on a scale, just so is the world before you, and like a drop of dew before dawn, which descends upon the earth.

[[wisdom-11-24]]
^24^ But you are merciful to all, because you can do all, and you dismiss the sins of man because of repentance.

[[wisdom-11-25]]
^25^ For you love all things that are, and you hate nothing of the things you have made; for you would not have created or established anything that you hated.

[[wisdom-11-26]]
^26^ For how could anything endure, except by your will? Or what, having been called by you not to exist, would be preserved?

[[wisdom-11-27]]
^27^ Yet you spare all things, because they are yours, O Lord, who loves souls.


[[wisdom-12]]
== Chapter 12

[[wisdom-12-1]]
^1^ O how good and gracious, Lord, is your spirit in all things!

[[wisdom-12-2]]
^2^ Therefore, those who wander afield, you correct, and, as to those who sin, you counsel them and admonish them, so that, having abandoned malice, they may believe in you, O Lord.

[[wisdom-12-3]]
^3^ For those ancient inhabitants of your holy land, who you abhorred,

[[wisdom-12-4]]
^4^ because they were doing works hateful to you, through unjust medicines and sacrifices,

[[wisdom-12-5]]
^5^ and the merciless murderers of their own sons, and the eaters of human entrails, and the devourers of blood apart from your community sacrament,

[[wisdom-12-6]]
^6^ and the sellers performing the ceremonies of helpless souls, you willed to destroy by the hands of our parents,

[[wisdom-12-7]]
^7^ so that they might worthily secure the sojourn of the children of God, in the land which is most beloved by you.

[[wisdom-12-8]]
^8^ Yet, so that you were lenient even to these men, you sent wasps, forerunners of your army, so that you might destroy them little by little,

[[wisdom-12-9]]
^9^ not because you were unable to subdue the impious under the just by war or by cruel beasts, or with a harsh word to exterminate them at once,

[[wisdom-12-10]]
^10^ but, in judging by degrees, you were giving them a place of repentance, not unaware that their nation is wicked, and their malice is inherent, and that their thinking could never be changed.

[[wisdom-12-11]]
^11^ For this offspring was accursed from the beginning. Neither did you, fearing anyone, give favor to their sins.

[[wisdom-12-12]]
^12^ For who will say to you, “What have you done?” Or who will stand against your judgment? Or who will come before you as a defender of unfair men? Or who will accuse you, if the nations perish, which you have made?

[[wisdom-12-13]]
^13^ For neither is there any other God but you, who has care of all, to whom you would show that you did not give judgment unjustly.

[[wisdom-12-14]]
^14^ Neither will king or tyrant inquire before you about those whom you destroyed.

[[wisdom-12-15]]
^15^ Therefore, since you are just, you order all things justly, considering it foreign to your virtue to condemn him who does not deserve to be punished.

[[wisdom-12-16]]
^16^ For your power is the beginning of justice, and, because you are Lord of all, you make yourself to be lenient to all.

[[wisdom-12-17]]
^17^ For you reveal power to those who do not believe you to be perfect in power, and you expose the arrogance of those who do not know you.

[[wisdom-12-18]]
^18^ Yet, you are the master of power, since you judge with tranquility, and since you administer us with great reverence; for it is close to you to be used whenever you will.

[[wisdom-12-19]]
^19^ But you have taught your people, through such works, that they must be just and humane, and you have made your sons to be of good hope, because in judging you provide a place for repentance from sins.

[[wisdom-12-20]]
^20^ For even if the enemies of your servants were deserving of death, you afflicted them with great attentiveness, providing a time and a place whereby they would be able to be changed from malice;

[[wisdom-12-21]]
^21^ with what diligence, then, have you judged your sons, whose parents you have given oaths and covenants in good faith!

[[wisdom-12-22]]
^22^ Therefore, while you give us discipline, you give our enemies a multiplicity of scourges, so that in judging we may think on your goodness, and when we are judged, we may hope for mercy.

[[wisdom-12-23]]
^23^ Therefore, also to these, who have lived their life irrationally and unjustly, through these things that they worshiped, you gave the greatest torments.

[[wisdom-12-24]]
^24^ And, indeed, they wandered for a long time in the way of error, valuing those things as gods, which are worthless even among animals, living in foolish irrational behavior.

[[wisdom-12-25]]
^25^ Because of this, you have given a judgment in derision, as if from foolish children.

[[wisdom-12-26]]
^26^ But those who have not been corrected by mockery and chiding, have experienced a judgment worthy of God.

[[wisdom-12-27]]
^27^ For among those who were indignant at their sufferings, which came through those things that they reputed to be gods, when they saw that they would be destroyed by these same things, those who formerly refused knowledge of him, now acknowledged the true God, and, because of this, the end of their condemnation came upon them.


[[wisdom-13]]
== Chapter 13

[[wisdom-13-1]]
^1^ But all men are vain, who are not under the knowledge of God, and who, from these good things that are seen, were not able to understand he who is, nor, by paying attention to the works, did they acknowledge he who was the artisan.

[[wisdom-13-2]]
^2^ Instead, they had considered either the fire, or the air, or the atmosphere, or the circle of stars, or the great sea, or the sun and moon, to be the gods that rule the world.

[[wisdom-13-3]]
^3^ If they, being delighted by such sights, supposed them to be gods, let them know how great the Lord of them is in splendor. For he who created all things is the author of beauty.

[[wisdom-13-4]]
^4^ Or, if they wondered at their power and their effects, let them understand by these things, that he who created them is mightier than they are.

[[wisdom-13-5]]
^5^ For, by the greatness of the creation and its beauty, the creator of these will be able to be seen discernibly.

[[wisdom-13-6]]
^6^ Yet, up to this point, the complaint about this is lesser. For perhaps they made a mistake in this, while desiring and seeking to find God.

[[wisdom-13-7]]
^7^ And, indeed, having some familiarity with him through his works, they search, and they are persuaded, because the things that they are seeing are good.

[[wisdom-13-8]]
^8^ But, then again, neither can their debt be ignored.

[[wisdom-13-9]]
^9^ For, if they were able to know enough so that they could value the universe, how is it they did not easily discover the Lord of it?

[[wisdom-13-10]]
^10^ Yet they are unhappy, and their hope is among the dead, for they have called ‘gods’ the works of the hands of men, gold and silver, the inventions of skill, and the likeness of animals, or a useless stone, the work of an ancient hand.

[[wisdom-13-11]]
^11^ Or, it is as if a craftsman, a workman of the forest, had cut straight wood, and, with his expertise, shaved off all of its bark, and, with his skill, diligently fashioned a vessel, practical for use in life,

[[wisdom-13-12]]
^12^ and even the remains of his work were exhausted in the preparation of food;

[[wisdom-13-13]]
^13^ and, from the remainder of this, which has become useful for nothing, a curved piece of wood and full of knots, he diligently carves it in his spare time, and, through the knowledge of his art, forms it and makes it in the image of a man,

[[wisdom-13-14]]
^14^ or something comparable to an animal, thoroughly rubbing it with red ochre, to make it red with the color of the pigment, and to cover every imperfection which is in it;

[[wisdom-13-15]]
^15^ and it is as if he made a fitting resting place for it, even setting it in a wall and fastening it with iron,

[[wisdom-13-16]]
^16^ providing for it, lest it should fall, knowing that it is unable to help itself, for it is an image and it is in need of help.

[[wisdom-13-17]]
^17^ And then, making an offering, he inquires about his wealth, and about his sons, and about marriage. And he is not ashamed to talk to that which has no soul.

[[wisdom-13-18]]
^18^ And for health, indeed, something unhealthy is being prayed to, and for life, he petitions what is dead, and for help, he calls upon something helpless,

[[wisdom-13-19]]
^19^ and for a good journey, he entreats that which is unable to walk, and for acquiring, and for working, and for success in all things, he entreats that which is useless in all things.


[[wisdom-14]]
== Chapter 14

[[wisdom-14-1]]
^1^ Again, another, thinking to sail, and beginning to make his voyage through the raging waves, calls upon a piece of wood more fragile than the wood that carries him.

[[wisdom-14-2]]
^2^ For this is what desire has contrived to be acquired, and the craftsman has formed its understanding.

[[wisdom-14-3]]
^3^ But your providence, O Father, governs, because you have provided for both a way in the sea and a very reliable path among the waves,

[[wisdom-14-4]]
^4^ revealing that you are able to save out of all things, even if someone were to go to sea without skill.

[[wisdom-14-5]]
^5^ But, so that the works of your wisdom might not be empty, therefore, men trust their souls even to a little piece of wood, and, crossing over the sea by raft, they are set free.

[[wisdom-14-6]]
^6^ But, from the beginning, when the proud giants were perishing, the hope of the world, fleeing by boat, gave back to future ages a seed of birth, which was governed by your hand.

[[wisdom-14-7]]
^7^ For blessed is the wood through which justice is made.

[[wisdom-14-8]]
^8^ But, through the hand that makes the idol, both it, and he who made it, is accursed: he, indeed, because it has been served by him, and it, because, though it is fragile, it is called ‘god.’

[[wisdom-14-9]]
^9^ But the impious and his impiety are similarly offensive to God.

[[wisdom-14-10]]
^10^ For that which is made, together with him who made it, will suffer torments.

[[wisdom-14-11]]
^11^ Because of this, and according to the idolatries of the nations, there will be no refuge, for the things created by God have been made into hatred, and into a temptation to the souls of men, and into a snare for the feet of the foolish.

[[wisdom-14-12]]
^12^ For the beginning of fornication is the search for idols, and from their invention comes corruption of life.

[[wisdom-14-13]]
^13^ For they neither existed from the beginning, nor will they exist forever.

[[wisdom-14-14]]
^14^ For by the great emptiness of men they came into the world, and therefore their end is soon discovered.

[[wisdom-14-15]]
^15^ For a father, embittered with the suffering of grief, made an image of his son, who had been suddenly taken away from him, and then, he who had died as a man, now begins to be worshiped as if a god, and so rites and sacrifices are established among his servants.

[[wisdom-14-16]]
^16^ Then, in the course of time, iniquity gains strength within this erroneous custom, so that this error has been observed as if it were a law, and this figment has been worshiped at the command of tyrants.

[[wisdom-14-17]]
^17^ And those, whom men could not openly honor because they were far off, a likeness of them was carried from far off, and from it they made a similar image of the king that they wanted to honor, so that, by their solicitude, they might worship he who was absent, just as if he were present.

[[wisdom-14-18]]
^18^ Yet, it passes into their care, and those whom they did not know, they love because of the excellence of the artist.

[[wisdom-14-19]]
^19^ For he, wishing to please the one who hired him, embellished his art, so as to fashion a better likeness.

[[wisdom-14-20]]
^20^ But the multitude of men, brought together by the beauty of the work, now considered him to be a god, whom they had formerly honored as a man.

[[wisdom-14-21]]
^21^ And this was the deception of human life: that men, serving either their own inclination or their kings, assigned the unutterable name to stones and wood.

[[wisdom-14-22]]
^22^ And it was not enough for them to go astray concerning the knowledge of God, but also, while living in a great war of ignorance, they call so many and such great evils ‘peace.’

[[wisdom-14-23]]
^23^ For either they sacrifice their own sons, or they make dark sacrifices, or they hold vigils full of madness,

[[wisdom-14-24]]
^24^ so that now they neither protect life, nor preserve a clean marriage, but one kills another through envy, or grieves him by adultery.

[[wisdom-14-25]]
^25^ And all things are mixed together: blood, murder, theft and fraud, corruption and infidelity, disturbances and perjury, disorder within good things,

[[wisdom-14-26]]
^26^ forgetfulness of God, pollution of souls, alteration of procreation, inconstancy of marriage, unnatural adultery and homosexuality.

[[wisdom-14-27]]
^27^ For the worship of unspeakable idols is the cause, and the beginning and the end, of all evil.

[[wisdom-14-28]]
^28^ For they either act with madness while happy, or they insistently speak wild lies, or they live unjustly, or they are quick to commit perjury.

[[wisdom-14-29]]
^29^ For, while they trust in idols, which are without a soul, vowing evil, they hope not to be harmed themselves.

[[wisdom-14-30]]
^30^ Therefore, from both sides it will fittingly happen, because they have thought evil of God, paying attention to idols, and because they have sworn unjustly, in guile despising justice.

[[wisdom-14-31]]
^31^ For swearing is not virtue, but sinning always comes around to a punishment according to the transgression of the unjust.


[[wisdom-15]]
== Chapter 15

[[wisdom-15-1]]
^1^ But you, our God, are gracious and true, patient, and in mercy ordering all things.

[[wisdom-15-2]]
^2^ And, indeed, if we sin, we are yours, knowing your greatness; and, if we do not sin, we know that we are counted with you.

[[wisdom-15-3]]
^3^ For to have known you is perfect justice, and to know justice and your virtue is the root of immortality.

[[wisdom-15-4]]
^4^ For the skillful planning of evil men has not led us into error, nor the shadow of a picture, a fruitless labor, an image having been sculpted through the use of diverse colors,

[[wisdom-15-5]]
^5^ the sight of which gives desire to the foolish, and he loves the likeness of a lifeless image without a soul.

[[wisdom-15-6]]
^6^ Deserving are the lovers of evil, those who hope in such things, and those who make them, and those who love them, and those who promote them.

[[wisdom-15-7]]
^7^ But even the potter, pressing laboriously, molds the soft earth into vessels, each one for our use. And from the same clay he molds vessels, those which are for clean use, and similarly, those which are for the opposite. But, as to what is the use of a vessel, the potter is the judge.

[[wisdom-15-8]]
^8^ And with effort he molds an empty god of the same clay, he who a little before had been made from the earth, and, after brief time, he himself returns from whence he came, to be claimed by he who holds the debt of his soul.

[[wisdom-15-9]]
^9^ Yet his concern is, not what his work will be, nor that his life is short, but that he is being contested by those who work with gold and silver, yet he also does the same to those who work with copper, and he glories that he makes worthless things.

[[wisdom-15-10]]
^10^ For his heart is ashes, and his hope is worthless dirt, and his life is more common than clay,

[[wisdom-15-11]]
^11^ because he ignores the One who molded him, and who instilled in him a working soul, and who breathed into him a living spirit.

[[wisdom-15-12]]
^12^ Yet they even considered our life to be a plaything, and the usefulness of life to be the accumulation of wealth, and that we must be acquiring things in every possible way, even from evil.

[[wisdom-15-13]]
^13^ For, above all else, he knows himself to be lacking, who, from fragile material of the earth forms vessels and graven images.

[[wisdom-15-14]]
^14^ For all the foolish and unhappy, in charge of the way of the arrogant soul, are enemies of your people and rule over them,

[[wisdom-15-15]]
^15^ because they have esteemed all the idols of the nations as gods, which neither have the use of eyes to see, nor noses to draw breath, nor ears to hear, nor the fingers of hands to grasp, and even their feet are slow to walk.

[[wisdom-15-16]]
^16^ For man made them, and he who borrowed his own breath, formed them. For no man will be able to form God in the likeness of himself.

[[wisdom-15-17]]
^17^ For, being mortal, he forms a dead thing with his unjust hands. Yet, he is better than those things that he worships, because he indeed has lived, though he is mortal, but they never have.

[[wisdom-15-18]]
^18^ Moreover, they worship the most miserable animals, for, to make a foolish comparison, these others are worse.

[[wisdom-15-19]]
^19^ But not even from their appearance can anyone discern anything good in these animals. Yet they have fled from the praise of God, and from his blessing.


[[wisdom-16]]
== Chapter 16

[[wisdom-16-1]]
^1^ Because of this, and by means of things similar to these, they were allowed to endure fitting torments, and they were exterminated by a multitude of beasts.

[[wisdom-16-2]]
^2^ Instead of these torments, you administered your people kindly, giving them a desire for a new taste from your delights, and preparing quails for their food,

[[wisdom-16-3]]
^3^ so that, even those desiring food, because of those things which were sent and revealed to them, were now turned away from a necessary desire. Yet these, after a brief time, having become weak, tasted a new food.

[[wisdom-16-4]]
^4^ For it was necessary, though they are without excuse, for them to unexpectedly come upon the ruin of exercising tyranny, yet this was as if to show them how their enemies were being exterminated.

[[wisdom-16-5]]
^5^ And so, when fierce beasts overcame them in anger, they were exterminated by the bites of perverse snakes.

[[wisdom-16-6]]
^6^ But your anger did not continue forever, though they were troubled for a short time for their correction, they have a sign of salvation as a remembrance of the commandment of your law.

[[wisdom-16-7]]
^7^ For he who turned to it was not healed by what he saw, but by you, the Savior of all.

[[wisdom-16-8]]
^8^ Yet in this you revealed to our enemies that you are he who delivers from all evil.

[[wisdom-16-9]]
^9^ For they were killed by the biting of locusts and flies, and there was found no remedy for their life, because they deserved to be destroyed by such things.

[[wisdom-16-10]]
^10^ But not even the teeth of venomous serpents conquered your sons, for your mercy came to them and healed them.

[[wisdom-16-11]]
^11^ For, in remembrance of your words, they were examined and were quickly saved, for forgetfulness is not engraved into your altar so that they would be unable to obtain your help.

[[wisdom-16-12]]
^12^ And, indeed, neither an herb, nor a poultice, healed them, but your word, O Lord, which heals all.

[[wisdom-16-13]]
^13^ For it is you, O Lord, who holds the power of life and death; you both lead to the threshold of death and you restore.

[[wisdom-16-14]]
^14^ Yet man, indeed, kills his own soul through malice, and when his spirit goes forth, it will not be returned, nor will he call back his soul when it has been received.

[[wisdom-16-15]]
^15^ But it is impossible to escape your hand.

[[wisdom-16-16]]
^16^ For the impious, having refused to know you, have been scourged by the strength of your arm, enduring persecution by unusual waters, and by hailstorms, and by rain storms, and being consumed by fire.

[[wisdom-16-17]]
^17^ For there was something extraordinary in water, which extinguishes all things; it has prevailed more than fire; for the world is the defender of the just.

[[wisdom-16-18]]
^18^ Indeed, at a certain time, the fire was subdued, so as not to burn away the animals, which were sent against the impious; and so that, in seeing this, they might know that they are suffering persecution by the judgment of God.

[[wisdom-16-19]]
^19^ And, at another time, fire burned, beyond its own power, in the midst of water, and it flared up from all around, so as to destroy the nations of an unjust land.

[[wisdom-16-20]]
^20^ Instead of these things, you nourished your people with the food of angels, and, having prepared bread from heaven, you served them without labor that which holds within itself every delight and the sweetness of every flavor.

[[wisdom-16-21]]
^21^ For your nature showed your sweetness, which you hold within your sons, and serving the will of each one, it was converted to what each one preferred.

[[wisdom-16-22]]
^22^ But snow and ice held back the strength of fire, and did not melt, so that they might know that fire, burning in the hail and flashing in the rain, destroyed the fruits of the enemies.

[[wisdom-16-23]]
^23^ Yet it was also the case, so that the just might be nourished, that fire had even been deprived of its own power.

[[wisdom-16-24]]
^24^ For the creature serving you, the Creator, grows red hot in the midst of the conflict against the unjust, and yet it subsides for the benefit of those who trust in you.

[[wisdom-16-25]]
^25^ Because of this, and at that time, having been transfigured in all things, your grace was diligently serving as the nursemaid of all things, according to the will of those who long for you,

[[wisdom-16-26]]
^26^ so that your sons, whom you loved, O Lord, might know that it is not the fruits of nature which feed men, but your word, which preserves those who believe in you.

[[wisdom-16-27]]
^27^ For that which could not be destroyed by fire, was immediately melted when warmed by a few rays of the sun,

[[wisdom-16-28]]
^28^ so that it might be clear to all that it is right to come before the sun to bless you, and to adore you at the dawning of the light.

[[wisdom-16-29]]
^29^ For the hope of the ungrateful will melt away like the winter’s ice and will disperse like overflowing water.


[[wisdom-17]]
== Chapter 17

[[wisdom-17-1]]
^1^ For your judgments, O Lord, are great, and your words are indescribable. Therefore, undisciplined souls have wandered astray.

[[wisdom-17-2]]
^2^ For, while they managed to convince the unjust, so as to obtain dominion over the holy nation, they themselves were fettered with chains of darkness and of endless night, enclosed in their houses, fugitives of everlasting providence, lying in ruins.

[[wisdom-17-3]]
^3^ And, while they thought to escape notice in their secret sins, they were scattered under a dark veil of oblivion, being horribly afraid, and having been disturbed with great astonishment.

[[wisdom-17-4]]
^4^ For neither did the cave which enclosed them preserve them from fear, because descending noises disturbed them, and the sorrowful persons appearing to them intensified their fear.

[[wisdom-17-5]]
^5^ And, indeed, even fire had no strength to provide them light, nor could the clear flames of the stars illuminate that horrible night.

[[wisdom-17-6]]
^6^ Yet there appeared to them a sudden fire, filled with fear; and, having been struck with the fear of that face which is unseen, they considered those things which they did see to be worse,

[[wisdom-17-7]]
^7^ and, having been ridiculed, the illusions were removed from their arts along with their contemptuous rebuke of glorious wisdom.

[[wisdom-17-8]]
^8^ Indeed, those who promised to drive away fears and disturbances from a languishing soul, though they were filled with derision, were themselves languishing in fear.

[[wisdom-17-9]]
^9^ And, even if nothing unnatural disturbed them, yet being agitated by the passing of animals and the hissing of snakes, they died of fear, denying what they themselves saw even in the air, which no one thinks to be able to escape.

[[wisdom-17-10]]
^10^ For, while there may be apprehension with wickedness, it gives testimony to condemnation, for a troubled conscience always forecasts harshness.

[[wisdom-17-11]]
^11^ For fear is nothing else but unfaithfulness to thinking helpful things.

[[wisdom-17-12]]
^12^ And, while expectation is driven from within, the cause of this is supposing that one is great in knowledge, and as a result, conflict excels.

[[wisdom-17-13]]
^13^ Yet those who were truly powerless that night, being overcome by both the vilest and the deepest hell, were sleeping the same sleep,

[[wisdom-17-14]]
^14^ sometimes stirred up by the fear of unnatural things, other times sinking down in disgrace of soul, for a sudden and unexpected fear overcame them.

[[wisdom-17-15]]
^15^ Then, if any among them had fallen away, he was kept in a prison without bars which had been left open.

[[wisdom-17-16]]
^16^ For if a farmer, or a shepherd, or a worker in a field of labor were suddenly overcome, he endured an inescapable necessity.

[[wisdom-17-17]]
^17^ For they were all bound together with one chain of darkness. Or if there were a whistling wind, or the sweet sound of birds among the thick tree branches, or the force of water rushing excessively,

[[wisdom-17-18]]
^18^ or the strong noise of rocks crashing down, or the scattering of playful animals having been seen, or the strong voice of bellowing beasts, or the resounding of the highest mountain echo, these things made them sink down because of fear.

[[wisdom-17-19]]
^19^ For the whole world was enlightened with a clear light, and none were being hindered in their labors.

[[wisdom-17-20]]
^20^ But then, the heavy night was placed over the sun for them, an image of that darkness which was about to overcome them. Yet they were more grievous to themselves than was the darkness.


[[wisdom-18]]
== Chapter 18

[[wisdom-18-1]]
^1^ But your saints were your greatest light, and they heard your voice, but did not see your form. And because they themselves did not also suffer the same things, they praised you greatly.

[[wisdom-18-2]]
^2^ And those who were wounded before, gave thanks, because they were no longer being wounded, and because they had petitioned for this gift, that there would be this difference.

[[wisdom-18-3]]
^3^ Because of this, they had a burning column of fire as a guide on the unknown way, and you displayed a harmless sun of a good hospitality.

[[wisdom-18-4]]
^4^ The others, indeed, deserved to be deprived of the light and to endure a prison of darkness, who watched for an opportunity to imprison your sons, by whom the incorruptible light of the law was beginning to be given to future generations.

[[wisdom-18-5]]
^5^ When they thought to kill the babes of the just, one son having been exposed and set free, to their disgrace, you took away a multitude of their sons and destroyed them all together in a mighty water.

[[wisdom-18-6]]
^6^ For that night was known beforehand by our fathers, so that, knowing the truth of the oaths in which they had trusted, they might be more peaceful in their souls.

[[wisdom-18-7]]
^7^ Yet your people received not only the salvation of the just, but also the destruction of the unjust.

[[wisdom-18-8]]
^8^ For just as you wounded our adversaries, so also did you greatly esteem calling us forth.

[[wisdom-18-9]]
^9^ For the just children of goodness were secretly offering sacrifice, and in agreement they administered the law of justice, so that both good and bad would be able to receive justice, and so that you might now approve of their chanting to the father.

[[wisdom-18-10]]
^10^ On the other hand, a dissimilar voice was resounding from the enemies, and a lamentable wailing was heard for the children who were being cried over.

[[wisdom-18-11]]
^11^ But the same punishment afflicted the servant with the master, and the common man endured the same as the king.

[[wisdom-18-12]]
^12^ Therefore, all were the same, with one name for death, and the dead were innumerable. For neither were the living sufficient to bury the dead, because, with a single effort, their most illustrious nation was exterminated.

[[wisdom-18-13]]
^13^ For they would not believe anything because of the drugs; then truly, at the beginning, when the extermination of the firstborn happened, they pledged the people to belong to God.

[[wisdom-18-14]]
^14^ For, when a quiet silence surrounded all things, and when the course of the night was passing the middle of its journey,

[[wisdom-18-15]]
^15^ your almighty word from heaven leapt down from your royal throne, as a fierce warrior in the midst of the land of extermination,

[[wisdom-18-16]]
^16^ as a sharp sword carrying your unfeigned authority, and standing, filled all things with death, and, standing on the earth, reached all the way up to touch heaven.

[[wisdom-18-17]]
^17^ Then, incessant visions of nightmares disturbed them, and unexpected fears overcame them.

[[wisdom-18-18]]
^18^ And another was thrown down elsewhere half-alive; and so, by means of that which was dying, the cause of death was revealed.

[[wisdom-18-19]]
^19^ For the visions that disturbed them had forewarned of these things, lest they should perish and not know why they suffered these evils.

[[wisdom-18-20]]
^20^ Yet, at that time, the trial of death touched even the just, and there was a disturbance of the multitude in the wilderness, but your wrath did not continue for long.

[[wisdom-18-21]]
^21^ For a blameless man, prospering, is to be entreated for your people, bringing forth the shield of your service, through prayer and incense, making prayerful supplication, he withstands anger, and so establishes an end to the necessary difficulty, revealing that he is your servant.

[[wisdom-18-22]]
^22^ Yet he outlasted the disturbance, not by virtue of the body, nor by force of arms, but, with a word, he subdued those who were troubling him, commemorating the oaths and covenant of the parents.

[[wisdom-18-23]]
^23^ For when they were now fallen down dead by heaps one upon another, he stood between them and cut off their attack, and he divided those who controlled the path to the living.

[[wisdom-18-24]]
^24^ For, within the garment of shame which he held, the world was all together, and the great deeds of the parents were engraved on four orders of stones, and your majesty was engraved on the crown of his head.

[[wisdom-18-25]]
^25^ Yet he who was exterminating yielded even to those he frightened. For one trial of wrath was sufficient.


[[wisdom-19]]
== Chapter 19

[[wisdom-19-1]]
^1^ But the impious, all the way to the very end, were overcome by anger without mercy. Indeed, he knew beforehand even their future.

[[wisdom-19-2]]
^2^ Yet, seeing that they might have repented, so that they would be led by him and be sent forth with great concern, the just sought the impious, while regretting their deeds.

[[wisdom-19-3]]
^3^ For, while the just were still holding grief in their hands and weeping at the tombs of the dead, these others took upon themselves another senseless thought, and they cast out the legislators and pursued them as if they were fugitives.

[[wisdom-19-4]]
^4^ For a fitting necessity was leading them to this end, and they were losing the remembrance of those things which had happened, so that what was lacking in the sufferings of the conflict might be completed by the punishment,

[[wisdom-19-5]]
^5^ and so that your people, indeed, might wonderfully pass through, but these others might find a new death.

[[wisdom-19-6]]
^6^ For every creature according to its kind was fashioned again as from the beginning, diligently serving your teachings, so that your children would be preserved unharmed.

[[wisdom-19-7]]
^7^ For a cloud overshadowed their camp, and where water was before, dry land appeared, and in the Red Sea, a way without hindrance, and out of the great deep, a level field sprung up,

[[wisdom-19-8]]
^8^ through which the whole nation passed, protected by your hand, seeing your miracles and wonders.

[[wisdom-19-9]]
^9^ For they consumed food like horses, and they leapt about like lambs, praising you, O Lord, who had freed them.

[[wisdom-19-10]]
^10^ For they were still mindful of those things which had happened during the time of their sojourn, how, instead of cattle, the earth brought forth flies, and instead of fish, the river cast up a multitude of frogs.

[[wisdom-19-11]]
^11^ And, lastly, they saw a new kind of bird, when, being led by their desire, they demanded a feast of meat.

[[wisdom-19-12]]
^12^ For, to console their loss, the quail came up to them from the sea, and yet troubles overcame the sinners, though they were not without the evidence of what had happened before by the power of lightning, for they suffered justly according to their own wickedness.

[[wisdom-19-13]]
^13^ And indeed, they set up a more detestable inhospitality. Certainly, some have refused to receive unknown foreigners, but these others were drafting good guests into servitude,

[[wisdom-19-14]]
^14^ and not only foreigners, but also those who had been under their care, because they were reluctantly sheltering the outsiders.

[[wisdom-19-15]]
^15^ Yet whoever had sheltered them with gladness, by making use of the very same justice, they afflicted with the most severe sorrow.

[[wisdom-19-16]]
^16^ Yet they were struck with blindness, like someone brought before the gates of justice, so that they were suddenly covered with darkness, and each one was left searching for the threshold of his front door.

[[wisdom-19-17]]
^17^ For the elements in themselves are in the process of being changed, just as when the sound of a musical instrument is being altered in quality, yet each one keeps its own sound, from where it is considered to be and according to its fixed appearance.

[[wisdom-19-18]]
^18^ For the countryside was transformed by water, and things which were swimming, crossed over the land.

[[wisdom-19-19]]
^19^ Fire prevailed in the midst of water, beyond its own power, and the water forgot its quenching nature.

[[wisdom-19-20]]
^20^ On the other hand, the flames did not trouble the bodies of the mortal animals walking around, nor did they melt that good food, which is as easily melted as ice. For in all things, O Lord, you magnified your people, and honored them, and did not despise them, but at every time and in every place, you assisted them.
