[[obadiah]]
= The Prophecy of Obadiah
:short: Obadiah

[[obadiah-1]]
== Chapter 1

[[obadiah-1-1]]
^1^ The vision of Obadiah. Thus says the Lord God to Edom: We have heard a report from the Lord, and he has sent an envoy to the nations: “Arise, and let us together rise up in battle against him.”

[[obadiah-1-2]]
^2^ Behold, I have made you little among the nations. You are greatly contemptible.

[[obadiah-1-3]]
^3^ The arrogance of your heart has lifted you up, living in the clefts of the rocks, exalting your throne. You say in your heart, “Who will pull me down to the ground?”

[[obadiah-1-4]]
^4^ Though you have been lifted high like an eagle, and though you have placed your nest among the stars, from there I will pull you down, says the Lord.

[[obadiah-1-5]]
^5^ If thieves had approached you, if robbers by night, how would you have remained unnoticed? Would they not have stolen all that they wanted? If the grape-pickers had approached you, would they not have left you at least a cluster?

[[obadiah-1-6]]
^6^ In what way have they been examining Esau? They investigated his secrets.

[[obadiah-1-7]]
^7^ They have sent you out all the way to the limit. All the men of your alliance have deceived you. Your men of peace have prevailed against you. Those who eat with you will place snares under you. There is no foresight in him.

[[obadiah-1-8]]
^8^ Shall I not, in that day, says the Lord, wipe away understanding from Idumea and foresight from the mount of Esau?

[[obadiah-1-9]]
^9^ And your strong from the Meridian will be afraid, so that man may perish from the mount of Esau.

[[obadiah-1-10]]
^10^ Because of the execution, and because of the iniquity against your brother Jacob, confusion will cover you, and you will pass away into eternity.

[[obadiah-1-11]]
^11^ In the day when you stood against him, when strangers seized his army, and foreigners entered into his gates, and they cast lots over Jerusalem: you also were just like one of them.

[[obadiah-1-12]]
^12^ But you shall not show disdain for the day of your brother in the day of his sojourn. And you shall not rejoice over the sons of Judah in the day of their perdition. And you shall not magnify your mouth in the day of anguish.

[[obadiah-1-13]]
^13^ And neither shall you enter into the gate of my people in the day of their ruin. And neither shall you also show disdain for his troubles in the day of his desolation. And you shall not send out against his army in the day of his desolation.

[[obadiah-1-14]]
^14^ Neither shall you stand at the exits to execute those who will flee. And you shall not enclose their remnant in the day of tribulation.

[[obadiah-1-15]]
^15^ For the day of the Lord is near, over all nations. Just as you have done, so will it be done to you. He will turn back your retribution on your own head.

[[obadiah-1-16]]
^16^ For in the manner that you drank on my holy mountain, so shall all nations drink continually. And they will drink, and they will absorb, and they will be as if they were not.

[[obadiah-1-17]]
^17^ And on mount Zion there will be salvation, and it will be holy. And the house of Jacob will possess those who had possessed them.

[[obadiah-1-18]]
^18^ And the house of Jacob will be a fire, and the house of Joseph a flame, and the house of Esau stubble. And they will be set on fire among them, and they will devour them. And there will be no remnant of the house of Esau, for the Lord has spoken.

[[obadiah-1-19]]
^19^ And those who are towards the South, and who are in the camps of the Philistines, will inherit the mount of Esau. And they will possess the region of Ephraim, and the region of Samaria. And Benjamin will possess Gilead.

[[obadiah-1-20]]
^20^ And the exiles of this army of the sons of Israel, all the places of the Canaanites all the way to Sarepta, and the exiles of Jerusalem who are in Bosphoro, will possess the cities of the South.

[[obadiah-1-21]]
^21^ And the saviors will ascend to mount Zion to judge the mount of Esau. And the kingdom will be for the Lord.
