[[habakkuk]]
= The Prophecy of Habakkuk
:short: Habakkuk

[[habakkuk-1]]
== Chapter 1

[[habakkuk-1-1]]
^1^ The burden that Habakkuk the prophet saw.

[[habakkuk-1-2]]
^2^ How long, O Lord, shall I cry out, and you will not heed? Shall I shout to you while suffering violence, and you will not save?

[[habakkuk-1-3]]
^3^ Why have you revealed to me iniquity and hardship, to see plunder and injustice opposite me? And there has been judgment, but the opposition is more powerful.

[[habakkuk-1-4]]
^4^ Because of this, the law has been torn apart, and judgment does not persevere to its conclusion. For the impious prevail against the just. Because of this, a perverse judgment is issued.

[[habakkuk-1-5]]
^5^ Gaze among the nations, and see. Admire, and be astounded. For a work has been done in your days, which no one will believe when it is told.

[[habakkuk-1-6]]
^6^ For behold, I will raise up the Chaldeans, a bitter and swift people, marching across the width of the earth, to possess tabernacles not their own.

[[habakkuk-1-7]]
^7^ It is dreadful and terrible. From themselves, judgment and their burden will issue.

[[habakkuk-1-8]]
^8^ Their horses are more nimble than leopards and swifter than wolves in the evening; their horsemen will spread out. And then their horsemen will approach from far away; they will fly like the eagle, hurrying to devour.

[[habakkuk-1-9]]
^9^ They will all approach towards the prey; their face is like a burning wind. And they will gather captives together like sand.

[[habakkuk-1-10]]
^10^ And concerning kings, he will triumph, and sovereign rulers will be his laughingstock, and he will laugh over every fortress, and he will transport a rampart and seize it.

[[habakkuk-1-11]]
^11^ Then his spirit will be altered, and he will cross over and fall. Such is his strength from his god.

[[habakkuk-1-12]]
^12^ Have you not existed from the beginning, Lord my God, my holy one, and so we shall not die? Lord, you have stationed him for judgment, and you have established that his strength will be swept away.

[[habakkuk-1-13]]
^13^ Your eyes are pure, you do not behold evil, and you cannot look towards iniquity. Why do you look upon the agents of iniquity, and remain silent, while the impious is devouring one who is more just than himself?

[[habakkuk-1-14]]
^14^ And you will make men like the fish of the sea and like the creeping things that have no ruler.

[[habakkuk-1-15]]
^15^ He lifted up everything with his hook. He drew them in with his dragnet, and gathered them into his netting. Over this, he will rejoice and exult.

[[habakkuk-1-16]]
^16^ For this reason, he will offer victims to his dragnet, and he will sacrifice to his netting. For through them, his portion has been made fat, and his meals elite.

[[habakkuk-1-17]]
^17^ Because of this, therefore, he expands his dragnet and will not be lenient in continually putting to death the peoples.


[[habakkuk-2]]
== Chapter 2

[[habakkuk-2-1]]
^1^ I will stand firm during my watch, and fix my position over the fortification. And I will observe carefully, to see what might be said to me and what I might respond to my opponent.

[[habakkuk-2-2]]
^2^ And the Lord responded to me and said: Write the vision and explain it on tablets, so that he who reads it may run through it.

[[habakkuk-2-3]]
^3^ For as yet the vision is far off, and it will appear in the end, and it will not lie. If it expresses any delay, wait for it. For it is arriving and it will arrive, and it will not be hindered.

[[habakkuk-2-4]]
^4^ Behold, he who is unbelieving, his soul will not be right within himself; but he who is just shall live in his faith.

[[habakkuk-2-5]]
^5^ And in the manner that wine deceives the heavy drinker, so will the arrogant man be deceived, and he will not be honored. He has enlarged his life like hellfire, and himself like death, and he is never fulfilled. And he will gather to himself all nations, and he will amass for himself all peoples.

[[habakkuk-2-6]]
^6^ Shall not all these take up a parable against him, and an enigmatic utterance about him? And it will be said, “Woe to him who increases what is not his own.” How long, then, will he lay down dense clay against himself?

[[habakkuk-2-7]]
^7^ Shall they not suddenly rise up, who would bite you, and be stirred up, who would tear you, so that you will be a prey for them?

[[habakkuk-2-8]]
^8^ Because you have despoiled many peoples, all those who are left of the people shall despoil you, because of the blood of men, and the iniquity of the earth, of the city and all who dwell therein.

[[habakkuk-2-9]]
^9^ Woe to him who gathers together an evil greed for his house, so that his nest may be exalted, and thinking that he might free himself from the hand of evil.

[[habakkuk-2-10]]
^10^ You have devised confusion for your house, you have cut to pieces many peoples, and your soul has sinned.

[[habakkuk-2-11]]
^11^ For the stone will cry out from the wall, and the wood that is between the joints of the building will respond.

[[habakkuk-2-12]]
^12^ Woe to him who builds a town with blood and prepares a city by iniquity.

[[habakkuk-2-13]]
^13^ Are not these things before the Lord of hosts? For the people will labor amid a great fire, and the nations will labor in emptiness, and they will fail.

[[habakkuk-2-14]]
^14^ For the earth shall be filled, that they might know the glory of the Lord, like the waters spreading over the sea.

[[habakkuk-2-15]]
^15^ Woe to anyone who gives a drink to a friend, releasing a drug and inebriating, so as to look upon their nakedness.

[[habakkuk-2-16]]
^16^ You are filled with disgrace in place of glory. So then, drink and fall fast asleep, for the cup of the right hand of the Lord will surround you, and a disgraceful vomit will cover your glory.

[[habakkuk-2-17]]
^17^ For the iniquity of Lebanon will cover you, and the devastation of animals which will deter them from the blood of men, and the iniquity of the earth and the city, and of all who dwell therein.

[[habakkuk-2-18]]
^18^ Of what benefit is the graven image? For its maker has formed it, a molten and imaginary deception. For its maker has hoped in a figment of his own creation, so as to make a dumb likeness.

[[habakkuk-2-19]]
^19^ Woe to him who says to wood, “Awaken,” to the silent stone, “Arise.” Is it able to teach? Behold, it has been entirely covered with gold and silver; and there is no spirit at all in its inner workings.

[[habakkuk-2-20]]
^20^ But the Lord is in his holy temple. May all the earth be silent before his face.


[[habakkuk-3]]
== Chapter 3

[[habakkuk-3-1]]
^1^ A Prayer of Habakkuk the Prophet on Behalf of Those Who Are Ignorant.

[[habakkuk-3-2]]
^2^ Lord, I heard what has been said about you, and I was afraid. Lord, your work, in the midst of years, revive it. In the midst of years, you will make it known. When you have become angry, you will remember mercy.

[[habakkuk-3-3]]
^3^ God will come from the south, and the Holy One from mount Pharan. His glory has covered the heavens, and the earth is full of his praise.

[[habakkuk-3-4]]
^4^ His brightness shall be like the light; horns are in his hands. There, his strength has been hidden.

[[habakkuk-3-5]]
^5^ Death will go forth before his face. And the devil shall depart before his feet.

[[habakkuk-3-6]]
^6^ He stood, and measured the earth. He looked, and dissolved the Gentiles. And the mountains of ages past have been shattered. The hills of the world became curved by the journeys of his eternity.

[[habakkuk-3-7]]
^7^ I saw the tents of Ethiopia for their iniquity; the tent-skins of the land of Midian will be thrown into confusion.

[[habakkuk-3-8]]
^8^ Could you have been angry with the rivers, Lord? Or was your fury within the rivers, or your indignation in the sea? He will ascend upon your horses, and your four-horse chariots are salvation.

[[habakkuk-3-9]]
^9^ Being stirred up, you will take up your bow, the oaths you have spoken to the tribes. You will split apart the rivers of the earth.

[[habakkuk-3-10]]
^10^ They saw you, and the mountains grieved. The great body of waters crossed over. The abyss uttered its voice. The pinnacle lifted up its hands.

[[habakkuk-3-11]]
^11^ The sun and the moon have stood firm in their dwelling place; with the light of your arrows, they shall go forth in the splendor of your flashing spear.

[[habakkuk-3-12]]
^12^ With a roar, you will trample the earth. In your fury, you will cause the nations to be stupefied.

[[habakkuk-3-13]]
^13^ You have gone forth for the salvation of your people, for salvation with your Christ. You struck the head of the house of the impious. You have laid bare his foundation all the way to the neck.

[[habakkuk-3-14]]
^14^ You have cursed his scepters, the head of his warriors, those who approached like a whirlwind so as to scatter me. Their exultation was like one who devours the poor in secret.

[[habakkuk-3-15]]
^15^ You made a way in the sea for your horses, in the mud of great waters.

[[habakkuk-3-16]]
^16^ I heard, and my stomach became troubled. My lips trembled at the voice. Let decay enter into my bones and gush forth from within me. Then I may rest in the day of tribulation, so that I may ascend to our people well-prepared.

[[habakkuk-3-17]]
^17^ For the fig tree will not flower, and there will be no bud on the vines. The labor of the olive tree will be misleading, and the farmland will produce no food. The sheep will be cut off from the sheepfold, and there will be no herd at the manger.

[[habakkuk-3-18]]
^18^ But I will rejoice in the Lord; and I will exult in God my Jesus.

[[habakkuk-3-19]]
^19^ The Lord God is my strength. And he will set my feet like those of the stag. And he, the victor, will lead me beyond my high places while singing psalms.
